### ISSUE TITLE
rrm.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10]
http://rrm.pl/

cookies

strona nie dziala w firefox z powodu cookies

**Comment by MajkiIT** [comment]
U mnie jest OK.

**Comment by xxcriticxx** [comment]
nie dziala z jak sa wlonczone te listy z twoja cookie lista chodzi super

Block-EU-Cookie-Shit-List‎ : 0 used out of 1,085purge cache
Prebake - Filter Obtrusive Cookie Notices‎ : 777 used out of 779purge cache
