### ISSUE TITLE
10000 post congratulations!

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10000]

**Comment by gargaamel** [comment]
closed 8967 + open 65 = 9032,
10000 - 9032 = 968 brakujące,
te 968 brakujących zgłoszeń to te ze sflagowanych kont (w tym sporo moich, ale na pewno nie 968 więc jak widać sporo innych kont też dostało flagę), pozdrawiamy wszystkie sflagowane konta hehe

**Comment by krystian3w** [comment]
Wystarczy się zarejestrować na temp mail, wrzucić zgłoszenie, konto oflaguje bot i ubywa.
