### ISSUE TITLE
koncertomania.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10004]
![opera zdjecie_2018-11-21_011241_www koncertomania pl](https://user-images.githubusercontent.com/36385327/48810625-93dddc00-ed2a-11e8-9176-e7d94a31604d.png)

**Comment by krystian3w** [comment]
`##.conv_active.conv_type_offer.conv_id_screen.conv-screen`

lub łapiemy na "`position:fixed` / "`position:fixed`"

**Comment by krystian3w** [comment]
`##.conv-widget-h`
