### ISSUE TITLE
shop.ticketpro.pl/pl/Account/LogOn

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10005]
![opera zdjecie_2018-11-21_011307_shop ticketpro pl](https://user-images.githubusercontent.com/36385327/48810635-a48e5200-ed2a-11e8-80fa-953dab0e10a3.png)

**Comment by krystian3w** [comment]
`##body > div:not([id]):not([class])[style*="position"][style*="fixed"]`

---

`https://shop.ticketpro.pl/pl/Account/LogOn`
