### ISSUE TITLE
wskaznikizrp.stat.gov.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10002]
http://wskaznikizrp.stat.gov.pl
https://sdg.stat.gov.pl/dane.jsf?poziom=_krajowy2&jezyk=pl
![opera zdjecie_2018-11-21_010956_wskaznikizrp stat gov pl](https://user-images.githubusercontent.com/36385327/48810540-3184db80-ed2a-11e8-8e25-1a652b1b923b.png)

**Comment by krystian3w** [comment]
`##body > div:not([id]):not([class])[style*="position"][style*="fixed"]`

---

`https://shop.ticketpro.pl/pl/Account/LogOn`

**Comment by krystian3w** [comment]
`wskaznikizrp.stat.gov.pl,sdg.stat.gov.pl##table[id$="gridStopka"] > tbody > .ui-panelgrid-even.ui-widget-content > .ui-panelgrid-cell`
