### ISSUE TITLE
agrosystems.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10018]
ciasteczka / rodo / polityka

![ss068](https://user-images.githubusercontent.com/44813765/48836763-f7e0be80-ed83-11e8-93f5-43188298e551.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
CSS / wstrzykiwanie skryptu.

Opcjonalnie przekopać liniowe skrypty za komunikatem.

**Comment by krystian3w** [comment]
`$(function(){if(!Cookies.get("rodo")){$('.modal-rodo').fadeIn();$('body').css('overflow-y','hidden');$('.modal-rodo button, .modal-rodo .button-close').click(function(){Cookies.set("rodo",!0,{expires:365})})}else $('.modal-rodo').remove()`

więc raczej html filtering odpada, bo to jest w pliku "`resource.js`".

**Comment by gargaamel** [comment]
> krystian3w : wstrzykiwanie skryptu.

Nie wiem czy jeszcze ci potrzebne ale w razie czego: 
`agrosystems.pl##+js(abort-on-property-read.js, Cookies.get, rodo)`

**Comment by krystian3w** [comment]
Raczej nie, scroll nie jest na siłę przyblokowany, by był trudny do nadpisania w Nano Adblocker.
