### ISSUE TITLE
rck.pila.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10014]
ciasteczka / rodo / polityka

![ss064](https://user-images.githubusercontent.com/44813765/48836664-a5070700-ed83-11e8-8ac1-bf328fd6feae.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by gargaamel** [comment]
> krystian3w > no znowu, nie mam, lecimy na incognito...

Ja mam, zarówno na Firefox jak i na Operze

> krystian3w : może `pl##.plg_system_eprivacy_module:not(body):not(html)`

Niestety nie przynosi efektu.

**Comment by krystian3w** [comment]
A masz widoczny element z tym filtrem pod wszystkie `pl` domeny?

**Comment by gargaamel** [comment]
<details not-open>
<summary>Nawet nie jest znaleziony:</summary>

![ss058](https://user-images.githubusercontent.com/44813765/48839870-2f079d80-ed8d-11e8-908a-65f2f3daf206.png)

</details>

**Comment by gargaamel** [comment]
Nie - jest już ukryty.

**Comment by krystian3w** [comment]
Dobra, mam w Firefox, a generyczny filtr wyłapuje nieaktywny (pusty, bez CSS) element dla tej domeny.
