### ISSUE TITLE
kinonet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10027]
showmax 

https://kinonet.pl/filmy-online/Leniwy_smok_/11764

nie mozemy zablokowac calego `||leadmy.pl^`?

![capture](https://user-images.githubusercontent.com/15007183/48840839-c2c17580-ed5d-11e8-9f53-a6337930c01e.PNG)

**Comment by xxcriticxx** [comment]
fake player 

https://kinonet.pl/filmy-online/_Miskow___och_w_Nowym_Jorku_/11807

![capture](https://user-images.githubusercontent.com/15007183/48943787-54fa8280-eef2-11e8-98d6-bb14e04127aa.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx poprawione. Dzięki
