### ISSUE TITLE
powiatowy.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10029]
Coś blokuje strone

**Comment by krystian3w** [comment]
Sami sobie zgotowaliśmy ten los:

https://github.com/MajkiIT/polish-ads-filter/blob/0933e6636db902effb8ddb2ca2a412e01959f76a/polish-adblock-filters/adblock.txt#L2074


I bym może odświeżył reguły dla strony np. `###pasek` za mało wycina z górnej reklamy
