### ISSUE TITLE
podatekvat.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10047]
ciasteczka / rodo / polityka

![ss063](https://user-images.githubusercontent.com/44813765/48852906-a699f480-edae-11e8-841b-282b5ae38992.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
chyba trzeba zobaczyć za spisem "grupa Gofin".
