### ISSUE TITLE
luxlux.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10046]
ciasteczka / rodo / polityka

![ss062](https://user-images.githubusercontent.com/44813765/48852774-5c187800-edae-11e8-91b2-4aef42b7c514.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
Nie może, w `pl##+js(...)` ja tego raczej nie puszczę (a skrypty bez domeny lub typu domen nie przechodzą) a regexem czy sieciowo niby niebezpiecznie wyciąć bo Gemius.

**Comment by krystian3w** [comment]
@gargaamel  możesz złapać w wolnym czasie witrynę z `.net` kupioną przez O2 kiedyś lub później przez WP.

Chyba że to fałszywa detekcja na `publicWWW.com`

Nie chciało mi się na ich limity wydawać 50 $ / 500 $.
