### ISSUE TITLE
downdetector.pl

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#10040]
https://downdetector.pl/status/facebook
![screenshot_2018-11-21 facebook - biezace problemy i awarie](https://user-images.githubusercontent.com/18214146/48849242-3edfab80-eda6-11e8-801f-352faef9f12d.png)

**Comment by krystian3w** [comment]
Było, nie można go wyciąć, chyba że nie czytasz tam disqus #8653 - czytaj: https://github.com/MajkiIT/polish-ads-filter/issues/8653#issuecomment-433516505

**Comment by krystian3w** [comment]
I ze strony `uAsset/uBlock-Origin` też raczej można zapomnieć o regule, która pozwoli załadować komentarze disqus.
