### ISSUE TITLE
poczta.wp.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#10051]
Coś na tej nowej `poczcie.wp.pl` jest za mocno blokowane i pojawiają się dziwne pola ładowania wiadomości  **w segregatorach** i nie znikają:

![obraz](https://user-images.githubusercontent.com/35370833/48871999-80dd1180-ede7-11e8-9ec7-f36d0f243e06.png) |
--- |

**Comment by krystian3w** [comment]
Tak i dalej mam, rozumiem, że muszę wyłączać listę po liście?

![image](https://user-images.githubusercontent.com/35370833/48895904-84ec4c00-ee46-11e8-8241-ac5f38d508cd.png) |
--- |

A i czy na pewno też masz przełączone konto na nowe serwery / interfejs.
Moje z okolic 2008 zostało przeniesione jakoś w październiku br. dopiero.

**Comment by krystian3w** [comment]
To coś musi być w liscie na polskie reklamy z naszego repozytorium, wyłączam, reklamy wracają i ten bug się naprawia  i mam komunikat o pustym segregatorze np. "społeczność".

**Comment by MajkiIT** [comment]
@krystian3w 
Po zalogowaniu wpadam na adres https://poczta.wp.pl//k/#/mails/?label=1

A to pomaga?
`poczta.wp.pl#@#+js(set-constant.js, WP.gdpr.init, noopFunc)`

**Comment by krystian3w** [comment]
Tak pomaga, ale wyciekają reklamy. 

I chyba psuło opcje napisania nowej wiadomości (stary widok - może ktoś dalej ma np. konta 2009~2016).
