### ISSUE TITLE
airdron-polska.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10055]
ciasteczka / rodo / polityka

![ss058](https://user-images.githubusercontent.com/44813765/48906357-7a40af80-ee64-11e8-843b-87275e5f2067.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
W sumie można wyciąć i na Adblock zostanie popsuty scroll przy pierwszej wizycie i potem się naprawi ten "nice-scroll-rails".

Chyba, że on jest w skrypcie zewnętrznym, wtedy odpada i tylko dla uBO / AdGuard.
