### ISSUE TITLE
galopuje.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10059]
ciasteczka / rodo / polityka

![ss062](https://user-images.githubusercontent.com/44813765/48906606-49ad4580-ee65-11e8-9176-8e4a031af788.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
`galopuje.pl##+js(abort-current-inline-script.js, SendAccept2)`

i dziwne, że nie działa html filtering, albo źle wycinam div-a / script.

**Comment by gargaamel** [comment]
U mnie działa.

**Comment by krystian3w** [comment]
O ile nie wyjdzie, że jest wycięty i z zewnętrznego pliku go reaktywuje.

**Comment by krystian3w** [comment]
https://github.com/gorhill/uBlock/issues/3391
