### ISSUE TITLE
fili.cc

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#10079]
Reklama w playerze vidoza link przykladowy

https://fili.cc/serial/doktor-who/s10e11/world-enough-and-time/17602

**Comment by MajkiIT** [comment]
@gzenio22 jakiś zrzut? U mnie nic nie ma

**Comment by KonoromiHimaries** [comment]
tez mam

**Comment by gargaamel** [comment]
Niestey nie pomaga, dalej reklama bez zmian.

**Comment by MajkiIT** [comment]
2 podejście 
```
||vidoza.net/js/pop.js$script
||vidoza.net/dl?op=view&*adb=$xmlhttprequest
||vidoza.net/srt/empty.srt?v1$media,xmlhttprequest
||vidoza.net/js/videojs.swf$object
||vidoza.net/js/videojs$script
```

**Comment by gargaamel** [comment]
Działa, z tym, że trzeba wcisnąć 2 x play, czyli jest defekt taki sam jak tu: https://github.com/MajkiIT/polish-ads-filter/issues/10013.

**Comment by MajkiIT** [comment]
@gargaamel Ok, dziękuję.

**Comment by krystian3w** [comment]
Ten defekt to był nawet mocniejszy, mnie działał tylko ten mały play z zielonego paska.
