### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1007]
Ta reguła `##[href*="hit.gemius.pl/hitredir/"]` ukrywa obrazek/link do filmu tutaj - `http://sportowefakty.wp.pl/euro-2016/wideo/23042/polska-litwa-nieuznany-gol-milika`

Z regułą
![image](https://cloud.githubusercontent.com/assets/11742596/15835788/e6e4d7b2-2c31-11e6-8079-027a8374b55d.png)

Bez reguły
![image](https://cloud.githubusercontent.com/assets/11742596/15835812/043d19be-2c32-11e6-98b0-a102ea3bf2b6.png)

**Comment by MajkiIT** [comment]
Dzięki.

~sportowefakty.wp.pl##[href*="hit.gemius.pl/hitredir/"]
