### ISSUE TITLE
polbox.tv/pl/

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10077]
cookie

 Ta strona korzysta z cookies (tzw. ciasteczek). Dalsze przeglądanie strony oznacza wyrażenie zgody na ich używanie. Więcej informacji

**Comment by krystian3w** [comment]
biało u mnie...

**Comment by xxcriticxx** [comment]
`##.cc-banner`

ja mam za kazdym razem 

![capture](https://user-images.githubusercontent.com/15007183/48923424-63a65280-ee7c-11e8-9aba-c7d1b81b5c95.PNG)

**Comment by krystian3w** [comment]
Ja mam dalej biało jakbym miał filtr:

`polbox.tv##^html` a nawet podgląd źródła strony pusty.

**Comment by xxcriticxx** [comment]
@krystian3w na foxie?

**Comment by krystian3w** [comment]
tak, dyskryminują Firefox?

**Comment by xxcriticxx** [comment]
chrome

![capture](https://user-images.githubusercontent.com/15007183/48923573-d532d080-ee7d-11e8-9ea9-73a1e705ac36.PNG)

zaraz sprawdze foxa

**Comment by krystian3w** [comment]
Ja mogę zmienić DNS-y na inne niż Google, bo chyba do tych wróciłem po tym jak dużo awarii miało CloudFlare i ich `1.1.1.1` / `1.0.0.1`.

**Comment by xxcriticxx** [comment]
ja jade na googlu. na foxie tez mam, moze to jest przez usa ip?

**Comment by xxcriticxx** [comment]
`pl##.cc-banner:not(body):not(html)`

juz jest dawno na liscie

**Comment by krystian3w** [comment]
Ale to nie jest <code>polbox<b>.pl</b>/pl</code> albo <code>polbox<b>.pl</b>/tv</code>, więc nie działa.

**Comment by xxcriticxx** [comment]
o shit ten sie konczy na .tv

**Comment by gargaamel** [comment]
> xxcritic : ja jade na googlu. na foxie tez mam, 

Ja też jade na google dns i mam pustą białą stronę zarówno na Firefoxie jak i na Operze

> xxcritic : moze to jest przez usa ip?

Najwyraźniej, bo gdy połączyłem się przez proxy USA to strona się normalnie ładuje.

Dla ciekawskich, polska lista RODO-ciasteczkowa tego nie usuwa ale usuwają to dwie inne listy:

Filtr statyczny `##.cc-container` znajdujący się w: Fanboy’s Cookiemonster List
Filtr statyczny `##.cc-banner:not(body):not(html)` znajdujący się w: I don't care about cookies
Filtr statyczny `###cookiesAgreement:not(body):not(html)` znajdujący się w: I don't care about cookies

**Comment by krystian3w** [comment]
`###cookiesAgreement`, to niestety w tym wypadku sam button zgody `:not(button)` jakby jeszcze zmniejszyć wycinanie.

**Comment by gargaamel** [comment]
Nie zagłębiałem się w to, podałem co w loggerze pokazuje.
