### ISSUE TITLE
funclub.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10088]
ciasteczka / rodo / polityka

![ss070](https://user-images.githubusercontent.com/44813765/48942722-03b5b780-ef21-11e8-891f-f73dcabbdb0e.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
Chyba przepiszę na filtrowanie po zawartości, za szybko coś aktualizują stronę.

**Comment by krystian3w** [comment]
A stary filtr nagle zaczął po ich zmianach wycinać tylko strzałkę powrotu na górę :persevere:.
