### ISSUE TITLE
jacus.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10098]
Błąd / anomalia kontinuum czasoprzestrzennego - po wejściu na stronę, zaczyna się ona sama z siebie automatycznie odświeżać / przeładowywać w nieskończoność (prawdopodobnie próbuje przenieść się w czasie), podobny przypadek jaki miałem niedawno tu: https://github.com/MajkiIT/polish-ads-filter/issues/10035#issuecomment-440683143, tylko że tam miałem tak przy otwartej konsoli i tylko na ABP i musiałem dodatkowo pierwszy raz sam ręcznie odświeżyć stronę, a w tym przypadku jest tak na uBO i wystarczy wejść na stronę.

**Comment by hawkeye116477** [comment]
Próbują doczytać reklamy cwaniaki, ale nie mogą...
`@@||jacus.pl/images/reklamy/*$image`
