### ISSUE TITLE
immergas.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10096]
ciasteczka / rodo / polityka:

![ss063](https://user-images.githubusercontent.com/44813765/48956527-c0287100-ef53-11e8-8565-9d47f2b426e8.png)

normalnie nie zgłaszałbym tego bo jest usuwane przez Fanboy's Cookiemonster List:
![ss064](https://user-images.githubusercontent.com/44813765/48956544-da624f00-ef53-11e8-85c9-c93f569f3961.png)

ale zgłaszam bo po włączeniu I don't care about cookies (bez różnicy czy z listą czy bez listy Fanboy's Cookiemonster List), jakiś błąd/defekt i wygląda to tak:
![ss065](https://user-images.githubusercontent.com/44813765/48956577-10073800-ef54-11e8-8d20-eaeebe2b3d0a.png)

Mając nadzieję, że usunięcie tych ciasteczek w POL liście RODO-ciasteczkowej usunie przy okazji ten defekt, ale nie jestem pewien, bo jak wyżej już pokazałem, lista Fanboy's Cookiemonster List już je usuwa, a pomimo tego defek dalej jest, więc tak czy inaczej może przy okazji naprawicie ten defekt.

**Comment by krystian3w** [comment]
Usuniemy i śmiało zgłaszaj.

Kiboke brakuje generyka lub zamyka to dodatkiem (taką ma politykę np. czasem overlaye usuwa dodatkiem).
