### ISSUE TITLE
gastrowypozyczalnia.pl/pl/

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10109]
cookies

Polityka Prywatności
Informujemy, że na swojej stronie www stosujemy pliki cookies (tzw. ciasteczka), aby zwiększyć komfort korzystania z naszych usług i zoptymalizować naszą witrynę.

Kliknij "Zgadzam się", aby ta informacja nie pojawiała się więcej.

Kliknij Cookies, sprawdzić wykaz plików cookies wykorzystywanych w serwisie www.gastrowypozyczalnia.pl oraz jak zarządzać nimi za pośrednictwem swojej przeglądarki internetowej.

Kliknij Polityka prywatności, aby dowiedzieć się jakie dane gromadzimy.

**Comment by krystian3w** [comment]
`gastrowypozyczalnia.pl###popup1`
