### ISSUE TITLE
schelleracademy.com.pl/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10106]
cookies 

Serwis używa plików cookies, aby mógł lepiej spełniać Państwa oczekiwania. Podczas korzystania z serwisu pliki te są zapisywane w pamięci urządzenia. Zapisywanie plików cookies można zablokować, zmieniając ustawienia przeglądarki.

Akceptuję - Zamknij

**Comment by krystian3w** [comment]
Fajne pytajniki mają :rofl:.

`###cookieInfoPanel`

**Comment by xxcriticxx** [comment]
@krystian3w thats copy&paste for you

**Comment by krystian3w** [comment]
Jeszcze coś namotałem, wklejam sobie w starszą wersję filtów na dev :rofl:
