### ISSUE TITLE
e-konferencje.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10107]
cookies

Ta witryna wykorzystuje pliki cookies by zarządzać sesją użytkownika. Cookies używane są także do monitorowania statystyk strony, oraz zarządzania reklamami.
W kazdej chwili możesz wyłączyć cookies. Wyłączenie ciasteczek może spowodować nieprawidłowe działanie witryny. Więcej w naszej polityce prywatności.

**Comment by krystian3w** [comment]
`##body > div[style="width: 970px; border:1px solid gray; margin: 3px auto; color: gray; padding: 3px; text-align: center; font: 10px Verdana, sans-serif;"]`
