### ISSUE TITLE
unileverfoodsolutions.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10108]
cookies 

Advice on Cookies
Unilever and its partners use cookies to enhance your online experience, personalize the content and ads you see and provide social media features.
For more info, visit our Cookie Notice or use our Cookie Management Tool to manage your choices.

**Comment by krystian3w** [comment]
Zamykamy to dodatkiem:

https://github.com/PolishFiltersTeam/PolishCookieConsent#jak-zainstalowa%C4%87

Inaczej na nie ma trochę zdjęć i Evidon plugin psuje strony w np. Norwegii / Mołdawii.

---

Niestety dalej nie mam pomysłu na wykrywanie wersji dodatku i dodawania do harmonogramu zadań Windows dla Chromium i jeszcze nie wiemy co jak w Chromium 71 zniknie opcja ręcznej instalacji (wersji developer nie możemy polecać, nie ładnie by tak było).

**Comment by xxcriticxx** [comment]
@krystian3w browser plugin?

**Comment by krystian3w** [comment]
Tak.

**Comment by krystian3w** [comment]
Taki dodatek `I do not care about Cookies` pod polskie Cookie Walle.

Nie zamierzamy robić kobyły podobnej do `I do not care about Cookies` co by akceptowała i wycinała wszystkie komunikaty zamiast listy do blokerów reklam.

**Comment by xxcriticxx** [comment]
@hawkeye116477 / @krystian3w good luck boys!

**Comment by krystian3w** [comment]
> ![obraz](https://user-images.githubusercontent.com/35370833/48962100-a0a53e80-ef7b-11e8-832b-861ac55f048e.png)

**Comment by hawkeye116477** [comment]
@xxcriticxx Extension, a nie plugin :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 czemu nie wtyczka?

**Comment by hawkeye116477** [comment]
@xxcriticxx `https://mozillapl.org/wiki/FAQ:_Rozszerzenia#Czyli_.22rozszerzenie.22_to_to_samo.2C_co_.22wtyczka.22.2C_tak.3F`

**Comment by hawkeye116477** [comment]
`jeszcze nie wiemy co jak w Chromium 71 zniknie opcja ręcznej instalacji (wersji developer nie możemy polecać, nie ładnie by tak było).`
@krystian3w Ale to się raczej tyczy instalacji z pliku crx, rozpakowane pewnie nadal będzie można.
