### ISSUE TITLE
malinowydwor.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10103]
cookies

Szanowni Państwo, w celu świadczenia usług na najwyższym poziomie, w ramach naszego serwisu stosujemy pliki cookies Korzystanie z witryny bez zmiany ustawień dotyczących cookies oznacza, że będą one zamieszczane w Państwa urządzeniu końcowym. Jeśli nie wyrażają Państwo zgody, uprzejmie prosimy o dokonanie stosownych zmian w ustawieniach przeglądarki internetowej. Aby dowiedzieć się więcej na temat używanych przez nas cookies odwiedź zakładkę: Polityka prywatności.

**Comment by krystian3w** [comment]
`###mlUsingCookies`
