### ISSUE TITLE
filmowakraina.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10110]
da rade ustawic odliczanie na 1sec?

test link:
https://filmowakraina.tv/movies/25442-the-domestics

**Comment by krystian3w** [comment]
`filmowakraina.tv##+js(nano-setInterval-booster.js)` niby z CDA działa w uBO.

**Comment by MajkiIT** [comment]
@ale chyba psuje clipwatching

**Comment by krystian3w** [comment]
Raczej zepsuty na starcie był.

**Comment by krystian3w** [comment]
`Wczytanie nie powiodło się dla elementu „script” ze źródłem „https://clipwatching.com/js/adframe.js”.`

Chyba trzeba skrypt dopuścić lub zneutralizować, zamiast pozwolić easylist zablokować.
