### ISSUE TITLE
siemashop.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10145]
ciasteczka / rodo / polityka

![ss066](https://user-images.githubusercontent.com/44813765/48970236-41dad600-f00a-11e8-96b6-f469128924f2.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
`||siemashop.pl/assets/*/js/cookie_agreement.js$script`

**Comment by MajkiIT** [comment]
@krystian3w A może lepiej tak ? `/js/cookie_agreement.js$script`

Powód ==> https://publicwww.com/websites/%22cookie_agreement.js%22/

**Comment by krystian3w** [comment]
Nie mogę podejrzeć domen z darmowym kontem, więc mnie to nie przekonuje.

**Comment by xxcriticxx** [comment]
@krystian3w nie trzeba nic podglondac jest kilka stron z cookie agreement i generic rule by się przydała

**Comment by krystian3w** [comment]
Trzeba, bo za pół roku będzie, że nie można czegoś na stronie zamówić i stracimy z 1000 użytkowników a tylko jeden zgłosi błąd.

**Comment by xxcriticxx** [comment]
Mamy z 5 użytkowników na githubue na palcach nas można policzyć

**Comment by krystian3w** [comment]
Chodziło mi o subskrybentów, pewnie z 10000 osób używa listy.

**Comment by xxcriticxx** [comment]
ostatnio bylo z 7 mil 

@MajkiIT podaj staty please?

**Comment by krystian3w** [comment]
No to z 2 polskie i im nie potrzeba.
