### ISSUE TITLE
zasysaj.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1016]
fake website

**Comment by MajkiIT** [comment]
@xxcriticxx wróciłeś?

**Comment by xxcriticxx** [comment]
tak konto mi zamkneli na pare dni

**Comment by MajkiIT** [comment]
a coś nabroił? trochę nas wystraszyłeś :D

**Comment by xxcriticxx** [comment]
poderzewali ze spamuje jaki auto bot mie zlapal hyba chodzilo ze za duzo innych url podaje
