### ISSUE TITLE
polskatelewizjausa.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10176]
cookies 

test link:
https://www.polskatelewizjausa.com/index.php/shop/abonamenty/product/36-30days-transfer

![capture](https://user-images.githubusercontent.com/15007183/48974313-e36e2180-f022-11e8-807e-7a78d0f03492.PNG)

**Comment by krystian3w** [comment]
`Website do not exist.`

**Comment by krystian3w** [comment]
Jakiś ban na Europę/UE i Rosję.

**Comment by hawkeye116477** [comment]
Tylko dla USA najwyraźniej.

**Comment by krystian3w** [comment]
Zrób zrzut z konsoli i daj co podpowiada uBlock Origin.

Proxy i wirtualne maszyny z systemem w USA wycinają komunikat.
