### ISSUE TITLE
ebrokerpartner.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10186]
ciasteczka / rodo / polityka

![ss070](https://user-images.githubusercontent.com/44813765/48978532-0ba26280-f0ad-11e8-888c-87f38aa83d08.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
wczoraj już złapałem przy jakimś zgłoszeniu @xMap

`ebrokerpartner.pl##.jsCookieInfoPlugin.cookie_plugin`

Potem się określi która klasa ważniejsza / popularniejsza / bezpieczniejsza.
