### ISSUE TITLE
nowy-sacz.info

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10199]
Napisy reklama
![opera zdjecie_2018-11-25_140516_www nowy-sacz info](https://user-images.githubusercontent.com/36385327/48979448-3398c280-f0bb-11e8-993c-36348cf03192.png)

**Comment by gargaamel** [comment]
1 było zgłaszane https://github.com/MajkiIT/polish-ads-filter/issues/10061, admin usunął co uważał za słuszne, no chyba, że czegoś zapomniał, albo źle usunął
2 admin nie usunął napisów bo się nimi nie zajmuje, więc zostało zgłoszone tutaj https://github.com/easylistpolish/easylistpolish/issues/23

**Comment by MajkiIT** [comment]
@xMaap Jeśli dobrze pójdzie to przejmiemy EasyPolish

**Comment by xxcriticxx** [comment]
@MajkiIT wow to podwyzka bedzie?

**Comment by hawkeye116477** [comment]
Ja bym zrobił tak, ale dla ABP nie zadziała., lecz jest jedna i po krzyku :smile:
`nowy-sacz.info##:xpath(//div[contains(text(), 'REKLAMA')])`

**Comment by gargaamel** [comment]
Już filtry dodane, napisów nie ma, można zamknąć wątek.
