### ISSUE TITLE
pclab.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1019]
`http://pclab.pl/`
Jak kliknie się w miejsce zaznaczone na czerwono na obrazku poniżej, to otwiera się nowa karta.

![image](https://cloud.githubusercontent.com/assets/11742596/15973265/bc15f11a-2f42-11e6-8ef2-a4b47db089b3.png)

Można by to zablokować dodając na przykład taką regułę:
`pclab.pl##a[href^="http://csr.onet.pl/eclk/clk"]`

**Comment by MajkiIT** [comment]
dodane. Dzięki.

**Comment by ugcgithub** [comment]
Niestety dodanie tej regułki wycina nie tylko reklamy, ale również zwykłe linki. Przykład np. na stronie: http://kobieta.onet.pl/zdrowie/naprzodzalergia/ - po wyłączeniu Adblocka, z prawej strony wyświetla się zwykły przycisk "Dowiedz się więcej". A to tylko jeden z przykładów.

**Comment by MajkiIT** [comment]
Na moje oko to artykuł sponsorowany.
