### ISSUE TITLE
comperia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10201]
![opera zdjecie_2018-11-25_140646_www comperia pl](https://user-images.githubusercontent.com/36385327/48979471-7e1a3f00-f0bb-11e8-961b-098642708541.png)
![opera zdjecie_2018-11-25_140653_www comperia pl](https://user-images.githubusercontent.com/36385327/48979472-7e1a3f00-f0bb-11e8-8d66-95a017d4c3c8.png)

**Comment by krystian3w** [comment]
```
comperia.pl#@#.ad
comperia.pl#@#.ads
comperia.pl#@#[class$="-ads"]
comperia.pl#@#.adsbox
comperia.pl#@#.ad-placement
```

Ale są dziury potem.
