### ISSUE TITLE
tlp.is

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10202]
http://tlp.is
![opera zdjecie_2018-11-25_141019_tlp is](https://user-images.githubusercontent.com/36385327/48979489-e36e3000-f0bb-11e8-8232-9918ceee79cc.png)
![opera zdjecie_2018-11-25_141028_tlp is](https://user-images.githubusercontent.com/36385327/48979490-e406c680-f0bb-11e8-9e11-69244bfd2983.png)

http://tlp.is/artykuly/testy-sprzetu/test-telefonu-honor-8x-cos-dla-fanow-naprawde-duzych-telefonow
![opera zdjecie_2018-11-25_140834_tlp is](https://user-images.githubusercontent.com/36385327/48979492-ee28c500-f0bb-11e8-97a6-36f9a203c631.png)
![opera zdjecie_2018-11-25_140842_tlp is](https://user-images.githubusercontent.com/36385327/48979493-ee28c500-f0bb-11e8-862f-2995444c2fc7.png)
![opera zdjecie_2018-11-25_140852_tlp is](https://user-images.githubusercontent.com/36385327/48979494-ee28c500-f0bb-11e8-8848-d231f918a2e5.png)

**Comment by xxcriticxx** [comment]
ja mam cookies `tlp.is##.cookiepolicy`

**Comment by krystian3w** [comment]
na starszej też mam, ja ich nie czytam, @hawkeye116477 / @MajkiIT  widać również i 7 milionów użytkowników listy chyba olało że wycieka.

**Comment by xxcriticxx** [comment]
@krystian3w lucky 7!

**Comment by hawkeye116477** [comment]
@krystian3w Na telepolis.pl już jest wycinane przez ogólną, nie trzeba dodawać. Natomiast tlp.is to już inna sprawa jakby :smile:.

**Comment by xxcriticxx** [comment]
ops

**Comment by gargaamel** [comment]
Ten anty-adblock to jest wywoływany przez EasyList, można dać do POL listy:
`||tlp.is/media/cache/resolve/content_box/adsDetector/telepolis_zaslepka_adblok_01.jpg$image,~third-party`, zostaną 2 puste kontenery na głównej do ogarnięcia, ale one są nawet tam nawet bez anty-adblocka
