### ISSUE TITLE
allbox.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10203]
30 sec counter 

test link:

https://allbox.tv/film-online,niepodleglosc-2018,459024

**Comment by krystian3w** [comment]
```
allbox.tv##+js(nano-setInterval-booster.js)
allbox.tv##+js(nano-setTimeout-booster.js)
```

Nie działają bez parametrów..., może ktoś ci dopisze o ile to nie SSTI (server side timer/timeout injection).
