### ISSUE TITLE
allegro.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#10216]
### Zrzut ekranu
![screenshot_20181125_225932](https://user-images.githubusercontent.com/19818572/48985244-cb230300-f105-11e8-8d3b-0e7aeeeb44e8.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Nie wiem czy to do @MajkiIT czy kogoś innego, ale to niby reklama banku :smile:.

**Comment by gargaamel** [comment]
Alleblock to usuwa.

**Comment by hawkeye116477** [comment]
Mi tak samo. Stronę główną np za bardzo czyści, brakuje ofert promocyjnych.

**Comment by krystian3w** [comment]
Taki ich rotator np. allegro smart 1 dzień i potem znika z góry i jest tylko z boku.

**Comment by krystian3w** [comment]
`##div[data-box-name="Belka-desktop"]`  

https://github.com/maciejtarmas/AlleBlock/commit/3e39b2e8d8a7abe2505e16f9d9449a989f166a65#diff-5151fde775f35adadb3d7d37b4fd0435R34
