### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by Venom3x** [MajkiIT/polish-ads-filter#10221]
Po wejściu w którykolwiek z artykułów na sportowefakty.wp.pl nie da się rozwinąć komentarzy.
Po kliknięciu na "Pokaż więcej komentarzy" nic się nie dzieje.
Problem jest chyba w "Polskie Filtry RODO-Ciasteczkowe" po ich wyłączeniu komentarze działają.

**Przeglądarka internetowa:** CHROME

**Rozszerzenia i skrypty:** uBlock Origin + Nano Defender

**Listy filtrów:**
1. EasyList
2. POL: polskie filtry do Adblocka i uBlocka
3. Polish Privacy Filters
4. Polskie Filtry RODO-Ciasteczkowe
5. NoCoin Filter List
6. Nano defender integration + Nano filters
7. Adblock Warning Removal List

**Comment by krystian3w** [comment]
Cześć w takim razie chyba trzeba to dodać jakoś do dodatku: https://github.com/PolishFiltersTeam/PolishCookieConsent#jak-zainstalować

O ile uda się chwycić przycisk "zgadam się" (konkretnych ciastek raczej nie namierzymy).

---

Chyba że znajdzie się jakiś magik na nowe filtry kosmetyczne / sieciowe / skryptowe.

**Comment by krystian3w** [comment]
:warning: Uwaga   :warning: 

Na dev neguje najnowszy filtr pod RODO WP z trybu prywatnego/incognito dla sportowych faktów!

**Comment by Venom3x** [comment]
@krystian3w dodałem to co podałeś i komentarze faktycznie zaczęły działać :)

**Comment by krystian3w** [comment]
Mam nadzieje, że filtry reklamowe powstrzymają tam RODO (jakoś blokują i pewnie uszkadzają Gemiusa). 

Jakiś taki efekt uboczny, że znikają "boczki" (widać słonina, skwarki i smalec się przejadły).
