### ISSUE TITLE
zdrowiewkrakowie.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10226]
1 ciasteczka / rodo / polityka
2 resztka / napis po reklamie

![ss065](https://user-images.githubusercontent.com/44813765/49011869-e7f81e80-f177-11e8-9113-37af6d912ed0.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
###### _Reklama:_

```
##body > div:nth-of-type(1)[style="display: block; padding: 5px; text-align: center; background: rgb(250, 250, 250);"]
```

**Comment by krystian3w** [comment]
Na cookies dodałem takie coś:

`##body > div:nth-of-type(2)[style$="border-bottom: 5px solid #ec008c;"]`
