### ISSUE TITLE
gadzet.telchina.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#10232]
### Zrzut ekranu
![screenshot_20181126_140251](https://user-images.githubusercontent.com/19818572/49015631-fd734580-f183-11e8-978e-a3b2fe62d255.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Antyadblock

**Comment by krystian3w** [comment]
U mnie wystarcza na razie: `gadzet.telchina.pl#@##adsense`
