### ISSUE TITLE
szafiarka.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10231]
napisy / resztki po reklamach na całej stronie i podstronach

http://www.szafiarka.pl i podstrony np.
http://www.szafiarka.pl/welniane-rajstopy.html

1
![ss070](https://user-images.githubusercontent.com/44813765/49012750-a61ca780-f17a-11e8-8495-f7b2b507c888.png)

2
![ss071](https://user-images.githubusercontent.com/44813765/49012698-84232500-f17a-11e8-8963-72a9cbcf9ce8.png)

3
![ss072](https://user-images.githubusercontent.com/44813765/49012700-84bbbb80-f17a-11e8-98e1-71eee13ef7fa.png)

4
![ss073](https://user-images.githubusercontent.com/44813765/49012703-84bbbb80-f17a-11e8-83fe-5a41a96eb6df.png)

5
![ss074](https://user-images.githubusercontent.com/44813765/49012704-85545200-f17a-11e8-852f-92511737be24.png)

<details not-open>

<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Adguard Base Filters
EasyList Polish
Fanboy's Polish​
```
</details>

**Comment by krystian3w** [comment]
jak dla mnie `##.a-info`
