### ISSUE TITLE
vanessa.fm

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10235]
Dziwne PROMO " kina " ( po prawej ) w artykule, np tu: http://www.vanessa.fm/m-wos-nie-wykluczam-walki-o-fotel-prezydenta-miasta/

**Comment by xxcriticxx** [comment]
cookies

`vanessa.fm###moove_gdpr_cookie_info_bar`

Strona używa plików cookie w celu usprawnienia korzystania z jej zawartości przez użytkowników.

Więcej na temat polityki prywatności oraz działania plików cookie znajdziesz na stronie Polityka plików cookie.

**Comment by xxcriticxx** [comment]
`vanessa.fm###text-10` na kino wystarczy?

**Comment by krystian3w** [comment]
Wystarczający, a jak szkoda tych kilku kilobajtów to dla siebie można blokować te 4 obrazki:

<sup>

```
||vanessa.fm/wp-content/uploads/2014/06/multikino.jpg$image
||vanessa.fm/wp-content/uploads/2014/06/cinema_city2.jpg$image
||vanessa.fm/wp-content/uploads/2017/09/kedzierzyn-300x60-tanie-wtorki.gif$image
||vanessa.fm/wp-content/uploads/2014/06/feniks.jpg$image
```

</sup>

**Comment by gargaamel** [comment]
U mnie znowu jakaś anomalia - to już 3cia w ciągu ostatniego tygodnia, tym razem nie miga cała strona jak tu https://github.com/MajkiIT/polish-ads-filter/issues/10208#issuecomment-441464595, ale sam przycisk "START" i anomalia występuje nie na Operze, lecz na Firefoxie, po wyłączeniu uBO anomalia znika:

![anomaila_3](https://user-images.githubusercontent.com/44813765/49023281-2f41d780-f197-11e8-9c32-5864fe269d64.gif)

**Comment by krystian3w** [comment]
Wywal ten Adblock Plus, może popsuł profile przeglądarek.

(chodzi mi, że ręczne wyłączenie dodatków to nie reset profilu przeglądarki).
