### ISSUE TITLE
erif.pl infokonsument.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10249]
![opera zdjecie_2018-11-26_170622_erif pl](https://user-images.githubusercontent.com/36385327/49026240-a4b0a680-f19d-11e8-9518-2068b7c4da5f.png)

**Comment by krystian3w** [comment]
hmmm...

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/49029365-b0ec3200-f1a4-11e8-945c-7ee660e55ca2.png) | ![obraz](https://user-images.githubusercontent.com/35370833/49029414-cfeac400-f1a4-11e8-87d5-2ee7b729addf.png)
--- | ---

Nie wiem w sumie gdzie, niech zadecyduje @hawkeye116477  / @MajkiIT 

A łobuz fanboy dostanie to w zgłoszeniach na filtr `##div[data-nconvert-cookie]`

**Comment by hawkeye116477** [comment]
@krystian3w A Fanboy dodał to do listy ciasteczkowej...
