### ISSUE TITLE
badaniapsychologiczne.net

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10246]
ciasteczka

![ss064](https://user-images.githubusercontent.com/44813765/49024421-b6904a80-f199-11e8-84a8-284f216b2402.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
Ładnie dali, w socialu chyba dojdzie do wycięcia całego box-a z Facebookiem - chyba że ktoś poprawi na coś lepszego.
