### ISSUE TITLE
glogow-info.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10258]
Błąd w POL: polskie filtry do Adblocka i uBlocka, przy wycinaniu reklam za dużo wycinają: 

<details not-open>
<summary>za dużo wycinają (cały środek wycięty):</summary>

![ss066](https://user-images.githubusercontent.com/44813765/49036050-f7e32300-f1b6-11e8-9e57-99a88f4c691b.png)

</details>
.

<details not-open>
<summary>po wyłączeniu listy środek się pojawia:</summary>

![ss065](https://user-images.githubusercontent.com/44813765/49036128-2234e080-f1b7-11e8-8589-e8dcae0d1c41.png)

</details>

**Comment by krystian3w** [comment]
`glogow-info.pl#@##maincol-broad-800 > center` to by trzeba wyciąć dokładniej ze środka.

**Comment by krystian3w** [comment]
`###maincol-broad-800 > center > div:nth-of-type(-n+2)` 

:question:

**Comment by krystian3w** [comment]
A i trzeba uważać by nie pomylić z `glogow.info.pl`
