### ISSUE TITLE
glogow-info.pl (2)

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10264]
Reopen a propo fixu do https://github.com/MajkiIT/polish-ads-filter/issues/10258, bo teraz wyskoczyły napisy:

![ss061](https://user-images.githubusercontent.com/44813765/49043644-fa9c4300-f1cb-11e8-8ad3-58fb31dffad2.png)

**Comment by krystian3w** [comment]
Ja nie mam pomysłu, bo wycina mi coś z prawej strony, chyba że AdGuardem i jego wyliczania `nth-child()` będą lepsze od `nth-of-type()` uBlock Origin.

**Comment by krystian3w** [comment]
Albo już mam:
```
glogow-info.pl###leftcol > .module:nth-of-type(n+2):nth-of-type(-n+4)
glogow.info.pl###leftcol > .module:nth-of-type(n+2):nth-of-type(-n+4)
```
