### ISSUE TITLE
kolomnie.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10260]
Błąd w POL filtrach RODO-ciasteczkowych, brak scrolla:

![ss061](https://user-images.githubusercontent.com/44813765/49037634-0af7f200-f1bb-11e8-8006-9f46785eae5e.png)

po wyłączeniu listy i zaakceptowaniu komunikatu scroll jest.

**Comment by krystian3w** [comment]
Jakiś generyk wyciął lub po czasie sobie doblokowali i mają placek.

**Comment by krystian3w** [comment]
A już wiem jak z tym było - literówka w domenie z CSS-em na przewijanie a po czasie doszły generyki i one wymagają wyjątków dla Adblock Plus :rofl:.

**Comment by krystian3w** [comment]
@MajkiIT  da się dorzucić sprawdzanie chociaż części na padnięte domeny z filtrów uBlock Origin / AdGuard.

Szybciej by wyszła ta literówka na światło dzienne.

**Comment by gargaamel** [comment]
krystian3w co ci sprawdzić mogę domeny wyciągnąć

**Comment by krystian3w** [comment]
A ja nie nie mam pomysłu jak to wyłapać i za dużo do przeszukania jak gdzieś ręcznie wpisałem domenę zamiast `kopiuj-wklej`, tu by akurat pomogło pingowanie - nx domain error by był.
