### ISSUE TITLE
superkoszyk.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10262]
Błąd - to samo co w poprzednim zgłoszeniu https://github.com/MajkiIT/polish-ads-filter/issues/10261 ale jeszcze ciekawiej bo aż 4 listy ciasteczkowe mają błąd:
- Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
- Fanboy’s Cookiemonster List
- I don't care about cookies
- Prebake - Filter Obtrusive Cookie Notices

<details not-open>
<summary> źle wycięty komunikat o rodo, jakieś resztki - usunięty tylko napis, a pozostał pusty kontener i przycisk</summary>

![ss062](https://user-images.githubusercontent.com/44813765/49038407-2b28b080-f1bd-11e8-91c6-832204be1d9f.png)

</details>
.
<details not-open>
<summary>dopiero po wyłączeniu wszystkich 4 list komunikat jest przywrócony</summary>

![ss061](https://user-images.githubusercontent.com/44813765/49038412-2fed6480-f1bd-11e8-82ce-7439ecd0c01d.png)

</details>

**Comment by gargaamel** [comment]
Zgłoszone u Fanboya https://github.com/ryanbr/fanboy-adblock/issues/698, i nawet natychmiastowo naprawione.

**Comment by KonoromiHimaries** [comment]
po co przytaczać `Prebake - Filter Obtrusive Cookie Notices` skoro lista jest nie wspierana i nikt tego

**Comment by KonoromiHimaries** [comment]
podobnie jak skrypt który też już został porzucony na rzecz rozszerzenia

**Comment by KonoromiHimaries** [comment]
korzystając z listy `I don't care about cookies` powinieneś używać rozszerzenia

**Comment by gargaamel** [comment]
> KonoromiHimaries : po co przytaczać Prebake - Filter Obtrusive Cookie Notices skoro lista jest nie wspierana i nikt tego

Już to tłumaczyłem: https://github.com/MajkiIT/polish-ads-filter/issues/9732#issuecomment-437991840

> KonoromiHimaries : podobnie jak skrypt który też już został porzucony na rzecz rozszerzenia
https://github.com/PolishFiltersTeam/PolishCookieConsent#readme

To też już tłumaczyłem https://github.com/MajkiIT/polish-ads-filter/issues/9999#issuecomment-440277661, po prostu zapomniałem zamienić słowo `skrypt` na słowo `rozszerzenie`, poprawię to przeoczenie.

> KonoromiHimaries : korzystając z listy I don't care about cookies powinieneś używać rozszerzenia

Wiem, że do tej listy jest rozszerzenie tak jak do polskiej, tylko odłożyłem używanie rozszerzenia, bo nie mogłem znaleźć informacji czy to rozszerzenie zawiera w sobie listę i wtedy muszę listę wyłączyć, i używać tylko samoego rozszerzenia, czy nie zawiera i wtedy muszę używać jednocześnie i rozszerzenia i listy, bałem się, że mi się listy zduulują, więc odłożyłem tę kwesitę na później bo byłem zajęty, i miałem później się zorientować i najwyraźniej zapomniałem albo mi się nie chciało póki co, ale dowiem się.

**Comment by KonoromiHimaries** [comment]
> może ktoś przekopiuje (może też zmodyfikuje, albo mu to podsunie jakiś pomysł) filtry do POL listy, takie ułatwienie

operowanie na zniszczonej synergii nie jest dobre.

> używam list ciasteczkowych takich takich jakich mam ochotę używać

proszę używaj, ale jak zgłaszasz to używaj wspieranego software

**Comment by gargaamel** [comment]
> 
>  KonoromiHimaries :
>
> > może ktoś przekopiuje (może też zmodyfikuje, albo mu to podsunie jakiś pomysł) filtry do POL listy, takie ułatwienie
> 
> jak masz jakąś sugestie to po prostu wykonaj zgłoszenie.
> 
> > używam list ciasteczkowych takich takich jakich mam ochotę używać
> 
> proszę używaj, ale jak zgłaszasz to używaj wspieranego software

Ale przecież zgłaszam zgłoszenia i błędy dotyczące POL: polskie filtry do Adblocka i uBlocka, a o innych listach informuję przy okazji.

**Comment by gargaamel** [comment]
Czy mółgbyś jaśniej.

**Comment by KonoromiHimaries** [comment]
> Czy mółgbyś jaśniej co do "będziesz mógł zrobić znacznie więcej pozytywnych zgłoszeń."

np. pozytywna własność; w przeciwieństwie do negatywnej własności cechującej się nieistnieniem czegoś.

**Comment by gargaamel** [comment]
> 
> 
> > Czy mółgbyś jaśniej co do "będziesz mógł zrobić znacznie więcej pozytywnych zgłoszeń."
> 
> Także: określony przez istnienie czegoś, np. pozytywna własność; w przeciwieństwie do negatywnej własności cechującej się nieistnieniem czegoś.

Ale jaka jest twoja definicja "pozytywnego zgłoszenia", a jaka "negatywnego zgłoszenia" i jakie są między nimi różnice.

**Comment by KonoromiHimaries** [comment]
> Czy chodzi o to, że po wyłączeniu tej listy, będzie więcej komunikatów, które będę mógł zgłosić?

tak! dziękuję.

**Comment by KonoromiHimaries** [comment]
> Czy chodzi o to, że po wyłączeniu tej listy, będzie więcej komunikatów, które będę mógł zgłosić?

dokładnie tak

**Comment by gargaamel** [comment]
> KonoromiHimaries : 
> dokładnie!
> jeśli chcesz pomóc to powinieneś powyłączać te listy których inni nie używają, żeby móc robić zgłoszenia do list których ludzie używają.

Ale po co mam je zgłaszać do innej listy i mieć więcej roboty, skoro są już usuwane przez tę listę, więc mogę po prostu włączyć tę listę i mieć je z głowy, mi to róznicy nie robi, która lista usunie komunikat, a roboty jest mniej.

> KonoromiHimaries : 
> 
> na dodatek będą to zgłoszenia prawdziwe,
> zgłoszenia które rzeczywiści da się naprawić.
> 
> zgłoszenia które nie będą powodowane nie z naszej winy.

Zgłaszałem już tutaj setki komunikatów i błędów rodo-ciasteczkowych, i zawsze przed zgłoszeniem drugi raz sprawdzałem na samej tylko Polskie Filtry RODO-Ciasteczkowe czy nadal ten komunikat / błąd występuje właśnie po to żeby przypadkiem nie tworzyć zgłoszeń spowodowanych inną listą, ale to jest dodatkowa robota bo trzeba po dwa razy sprawdzać, więc widząc, że mam za sobą setki zgłoszeń i bardzo rzadko trafiało się coś spowodowane inną listą ciasteczkową, zdecydowałem się kilka dni temu na pominięcie tego drugiego sprawdzania i jak na razie tylko raz https://github.com/MajkiIT/polish-ads-filter/issues/10183 trafiło się zgłoszenie spowodowane inną listą. Nie sądzę, żeby 1 fałszywe na tak wiele zgłoszeń robiło jakiś problem.

**Comment by gargaamel** [comment]
Dobra wywaliłem tę listę: 

Prebake - Filter Obtrusive Cookie Notices ( https://github.com/liamja/Prebake ), 

najpierw chciałem ją zamienić na zaktualizowany fork: 

Custom Prebake - Filter Obtrusive Cookie Notices ( https://gitlab.com/isaakm/Custom-Prebake )

ale w https://gitlab.com/isaakm/Custom-Prebake/blob/master/README.md doczytałem, że ta lista została już dodana do listy Fanboya:

> I decided to merge the differences with the cookiemonster list of fanboy 
> @ https://github.com/ryanbr/fanboy-adblock
> Please commit your changes there

Przy okazji zauważyłem inną ciekawą kwesitę - to, że oryginał (Prebake - Filter Obtrusive Cookie Notices) po prawie 2 latach abstynencji przebudził się kilka miesięcy temu (dokładnie 28 maja) i sklonował swojego klon: https://github.com/liamja/Prebake/commits/master

**Comment by krystian3w** [comment]
I na jakieś 99% ma je w `common.css`: [common.zip](https://github.com/MajkiIT/polish-ads-filter/files/2618970/common.zip)

https://pastebin.com/WAfPNgyR

**Comment by gargaamel** [comment]
No wiem, że pomaga, tylko czy jest samodzielny i zawiera listę filtrów w sobie, (wtedy tą w uBO trzeba wyłączyć).

Właśnie sprawdziłem i okazało się, że dodatek ma już w sobie zintegrowaną listę, więc trzeba wyłączyć jej duplikat w uBO (https://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/).

Czy nie tak jak w Polskicm dodatku do którego trzeba mieć włączoną listę.

**Comment by krystian3w** [comment]
My robimy dodatek na cookie walle a nie lżejszy uBlock Origin "Annoyance", kontynuacja zamysłu skryptu na cookie walle i dodatek może szybciej wycinać niż skrypt np. problem z zbyt szybkim przeszukiwaniem shadow-root postów twitter.

**Comment by gargaamel** [comment]
Nie czynię żadnych zarzutów, jedynie stwierdziłem fakty, że jeden dodatek (I dont care about cookies) wymaga **wyłączenia** listy filtrów w uBO, a drugi dodatek (Polska Zgoda Ciasteczkowa) "wymaga" **włączenia** listy filtrów w uBO - Polskie Filtry RODO-Ciasteczkowe.

Chodzi o to żeby nie było sytuacji, że ktoś omyłkowo:
- doda sobie 2 dodatki I dont care about cookies + Polska Zgoda Ciasteczkowa i będzie myślał, że wszystko ok, a nie jest bo zapomniał włączyć  w uBO listy filtrów Polskie Filtry RODO-Ciasteczkowe​
- doda sobie 2 dodatki + 2 listy czyli  dodatek I dont care about cookies + listę I dont care about cookies oraz dodatek Polska Zgoda Ciasteczkowa + listę Polskie Filtry RODO-Ciasteczkowe​, i będzie myślał, że jest ok, a nie jest bo listę I dont care about cookies musi wyłączyć w uBO żeby się nie dublowały

Po prostu chodzi o to, że łatwo jest się nieobeznanemu pomylić.

**Comment by krystian3w** [comment]
Może kiedyś będzie na wiki opis jak optymalnie używać.

**Comment by gargaamel** [comment]
A ja tymczasem podtrzymuję pytanie:

> A teraz pytanie ile osób miało omyłkowo w uBO włączony I don't care about cookies dodatek i listę na raz, przez co się niepotrzebnie dublowały, przyznawać mi się po kolei haha

Przyznawać się bo do kozy pójdziecie.

**Comment by gargaamel** [comment]
> gargaamel : Zgłosiłem też mejlowo do I don't care about cookies​.

Przed chwilą naprawili, była aktualizacja dodatku.

**Comment by krystian3w** [comment]
Ja tam mam informacje, że dodatek wczoraj aktualizowany do 2.9.4, może odpisał po kilku godzinach.

**Comment by gargaamel** [comment]
Być może i już wczoraj była, ja dziś rano wcisnąłem aktualizacja dodatków i znalazło aktualizację (pomimo że mam także aktywną opcję automatycznej aktualizacji dodatków).

**Comment by gargaamel** [comment]
@KonoromiHimaries zdecydowałem się oprócz jak już wcześniej pisałem usunięcia listy Prebake, także na usunięcie listy I'm OK with cookies, więc już z nich nie korzystam.
