### ISSUE TITLE
capitalapart.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10261]
Błąd w aż 3 listach ciasteczkowych,
- Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
- Fanboy’s Cookiemonster List
- I don't care about cookies

<details not-open>
<summary> źle wycięty komunikat o rodo, jakieś resztki - usunięty tylko napis, a pozostał pusty kontener i przycisk</summary>

![ss062](https://user-images.githubusercontent.com/44813765/49037975-ea7c6780-f1bb-11e8-8776-bf4a814f5c5a.png)

</details>
.
<details not-open>
<summary>dopiero po wyłączeniu wszystkich 3 list komunikat jest przywrócony</summary>

![ss063](https://user-images.githubusercontent.com/44813765/49038043-1566bb80-f1bc-11e8-945f-0a1f49544da5.png)

</details>

**Comment by krystian3w** [comment]
Możesz dać propozycje gdzie dopisać `:not(p)` do wszystkiego odpada.

Ja tylko dotnę resztki.

**Comment by gargaamel** [comment]
Zgłoszone u Fanboya https://github.com/ryanbr/fanboy-adblock/issues/697, i nawet natychmiastowo naprawione.

**Comment by krystian3w** [comment]
Też dociął, nie naprawił generyków...

**Comment by gargaamel** [comment]
> gargaamel : Zgłosiłem też mejlowo do I don't care about cookies​.

Przed chwilą naprawili, była aktualizacja dodatku.
