### ISSUE TITLE
pzsnstart.eu paralympic.org.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10265]
![opera zdjecie_2018-11-26_224011_pzsnstart eu](https://user-images.githubusercontent.com/36385327/49043782-4fd85480-f1cc-11e8-90c6-0698536cc62f.png)

**Comment by krystian3w** [comment]
Brzydkie, nie mogę zablokować skryptu / xhr i zostaje html filtering / CSS / wstrzykiwanie skryptu.

**Comment by krystian3w** [comment]
`airdron-polska.pl,paralympic.org.pl##+js(nano-remove-elements-onready.js, .popmake-overlay[data-popmake*="cookies"])`

Takie coś może być jak na stronie jest "`nice-scroll-rails`", gorzej jak go usuną, wtedy zostaje awaryjna linia CSS.
