### ISSUE TITLE
gazetapraca.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10279]
Błąd w:
- liście Polskie Filtry RODO-Ciasteczkowe, 
- dodatku I don't care about cookies

<details not-open>
<summary>pojawia się cień/tło blokujące</summary>

![ss086](https://user-images.githubusercontent.com/44813765/49086132-164b2c00-f254-11e8-927d-71d9091e5021.png)

</details>
.
<details not-open>
<summary>po wyłączeniu listy Polskie Filtry RODO-Ciasteczkowe i dodatku I don't care about  cookies jest komunikat o polityce prywatności</summary>

![ss091](https://user-images.githubusercontent.com/44813765/49086201-37ac1800-f254-11e8-81bb-9fd5282e8e3b.png)

</details>
.
<details not-open>
<summary>po zaakceptowaniu / zamknięciu komunikatu strona ładuje się normalnie i pojawia się następny komunikat o polityce prywatności na dole</summary>

![ss092](https://user-images.githubusercontent.com/44813765/49086225-47c3f780-f254-11e8-9956-aa0ebf0139e4.png)

</details>
.

Już zgłosiłem mejlowo błąd do I don't care about cookies podobnie jak kilka innych błędów związanych tylko z dodatkiem I don't care about cookies oraz listą Fanboy's Cookiemonster List.

![ss091](https://user-images.githubusercontent.com/44813765/49086521-01bb6380-f255-11e8-9038-916ef7c33942.png)

**Comment by gargaamel** [comment]
Zdecydujcie się z tymi etykietami, bo  się robi syf i jak na razie dla:
- jednych zgłoszeń są dwie etykiety `błąd` i `cookies`
- dla innych są tylko `błąd`
- a jeszcze dla innych tylko `cookies`

**Comment by krystian3w** [comment]
> Już zgłosiłem mejlowo błąd do I don't care about cookies podobnie jak kilka innych błędów związanych tylko z dodatkiem I don't care about cookies oraz listą Fanboy's Cookiemonster List.

Widziałem, na  kilku musiałem i w naszej doblokować na dev.

**Comment by gargaamel** [comment]
Spoko, ale np. `brieftip.pl` i `norgips.pl` zgłaszałem tylko do I don't care about cookies 9zobacz screenshoot), więc o nich na pewno nie wiedziałeś, one mają brakujący scroll bar.

**Comment by krystian3w** [comment]
To chyba będzie `gazetapraca.pl###overlayJS`

**Comment by krystian3w** [comment]
> Spoko, ale np. `brieftip.pl`

Już sam nie wiesz co gdzie zgłaszasz...., to będzie wycinane html filteringiem i wstecznie CSS-em dla niewspierających.

`norgips.pl` - z tym się zgodzę.

**Comment by gargaamel** [comment]
> krystian3w : Już sam nie wiesz co gdzie zgłaszasz...,

Nie czaję, możesz jaśniej? Brakujący scroll bar w `brieftip.pl` i `norgips.pl` zgłosiłem tylko mejlowo do I don't care about cookies, bo błąd wystepuje tylko z I don't care about cookies.

**Comment by krystian3w** [comment]
`#703`

**Comment by xxcriticxx** [comment]
@gargaamel jestem czlowiekiem a nie robotem

chcialbys bota do tagowania @hawkeye116477 tobie zmontuje

**Comment by gargaamel** [comment]
> krystian3w : Już sam nie wiesz co gdzie zgłaszasz...,

Dobrze wiem co i gdzie zgłaszam, 

> #703

Do Fanboya jest zgłoszony cień/tło bo Fanboy's Cookiemonster List powoduje tylko cień/tło, a do I don't care about cookies zgłoszony brakujący scroll, bo I don't care about cookies powoduje tylko brakujący scroll.

Pomyliłem się co najwyżej wyżej teraz w swoich komentarzach https://github.com/MajkiIT/polish-ads-filter/issues/10279#issuecomment-442072223 i https://github.com/MajkiIT/polish-ads-filter/issues/10279#issuecomment-442073950 - źle po prostu sformułowałem wypowiedź

> gargaamel : Brakujący scroll bar w brieftip.pl i norgips.pl zgłosiłem tylko mejlowo do I don't care about cookies, bo błąd wystepuje tylko z I don't care about cookies.

> gargaamel : Nie czaję, możesz jaśniej? Brakujący scroll bar w brieftip.pl i norgips.pl zgłosiłem tylko mejlowo do I don't care about cookies, bo błąd wystepuje tylko z I don't care about cookies.

W przypadku `brieftip.pl`, zapomniałem napisać w powyższych komentarzach, że nie tylko był problem brakującego scrolla w I don't care about cookies ale także do zgłosiłem do Fanboya ło/cień.

Więc zdecydowanie wiem co i gdzie zgłaszam, po prostu pomyłka w komentarzu, wynikająca ze zmęczenia bo pół dnia już zgłaszam te cholerne bugi w listach ciasteczkowych więc mam prawo się zmęczyć, natomiast skontruję ci i odpiszę, że to ty nie widzisz, że w #703 jest zgłoszone tło/cień, a nie brakujący scroll i nie założyłeś w swoich przypuszczeniach zwyczajnej pomyłki w wypowiedzi.

**Comment by krystian3w** [comment]
Fanboy tła nie zablokuje, scrolla nie odblokuje, to tam wkleiłem wyjątek do ręcznej akceptacji.

Wątpię, że on się załapie na snippety Adblock Plus.

**Comment by gargaamel** [comment]
> krystian3w : Fanboy tła nie zablokuje, scrolla nie odblokuje

Tak przy okazji odnośnie tego co Fanboy nie zablokuje, a raczej nie odblokuje, to tutaj https://github.com/ryanbr/fanboy-adblock/issues/688#issuecomment-441432194 tworzy się swojego rodzaju META dla FETL dla powodującej tło/cień i ponoć szpiegującej (wg. Fanboya) ikony Facebookowej `https://apps.facebook.com/favicon.ico`

**Comment by gargaamel** [comment]
Tak, naprawione.
