### ISSUE TITLE
glogow-info.pl / glogow.info.pl (4)

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10270]
Kolejny reopen https://github.com/MajkiIT/polish-ads-filter/issues/10269 , chłopaki coraz lepiej wam idzie hehe, teraz mam i reklamy i napis:

1 - 2 x reklama (jedna wyżej, druga niżej, chyba wewnętrzna? ale co jak się zmieni na zewnętrzną? na wszelki wypadek zgłosiłem, nie wiem pogubiłem się)

![ss061](https://user-images.githubusercontent.com/44813765/49071789-09681180-f22f-11e8-89ee-552a2a7e902d.png)

![ss063](https://user-images.githubusercontent.com/44813765/49075680-8ac3a200-f237-11e8-9acd-ecd313f542c7.png)

![ss064](https://user-images.githubusercontent.com/44813765/49075719-a3cc5300-f237-11e8-8e44-c41150e9f953.png)

2 - napis
![ss062](https://user-images.githubusercontent.com/44813765/49071791-09681180-f22f-11e8-8751-4ad429b89dda.png)

**Comment by krystian3w** [comment]
Zawsze można wrócić do blokowania środka i zostaną boki :sagittarius:.

**Comment by gargaamel** [comment]
Ale przecież w środku są artykuły.

**Comment by krystian3w** [comment]
Ale będą boki bez reklam, no chyba że literówka w filtrach i wyciekło.

**Comment by krystian3w** [comment]
`###leftcol > .module:-abp-contains(Reklama)` 

zamiast 

`###leftcol > .module:nth-of-type(n+2):nth-of-type(-n+4)`

Te odliczanie nie da rady objąć elementu dużo niżej. A też nie za bardzo widzę sens by spuchło do:

```
###leftcol > .module:nth-of-type(n+2):nth-of-type(2)
###leftcol > .module:nth-of-type(n+2):nth-of-type(3)
###leftcol > .module:nth-of-type(n+2):nth-of-type(4)
###leftcol > .module:nth-of-type(n+2):nth-of-type(6)
```

**Comment by xxcriticxx** [comment]
@gargaamel podaj coś lepszego proszę

**Comment by gargaamel** [comment]
Nie znam historii tej strony, czy te reklamy są ruchome i się przemieszczają w górę i w dół, czy siedzą w jednym miesjcu.

**Comment by xxcriticxx** [comment]
@gargaamel jest pelno czasu poczekamy jak sie zapoznasz to podasz cos lepszego :)

**Comment by xxcriticxx** [comment]
jak na moje potrezeby strona jest wycienta wystarczająco

**Comment by gargaamel** [comment]
Reklamy po prawej są wycięte statykami:

```
glogow-info.pl,glogow.info.pl###rightcol-broad > .module:nth-of-type(1)
glogow-info.pl,glogow.info.pl###rightcol-broad > .module:nth-of-type(3)
glogow-info.pl,glogow.info.pl###rightcol-broad > .module:nth-of-type(4)
glogow-info.pl,glogow.info.pl###rightcol-broad > .module:nth-of-type(5)
```

więc idąc tą logiką te po lewej też powinny być, więc nie wiem w czym problem, a jeśli reklamy są ruchome, to wywalić wszystkie statyki, czyli:

```
glogow-info.pl,glogow.info.pl###leftcol > .module:nth-of-type(n+2):nth-of-type(-n+4)
glogow-info.pl,glogow.info.pl###rightcol-broad > .module:nth-of-type(1)
glogow-info.pl,glogow.info.pl###rightcol-broad > .module:nth-of-type(3)
glogow-info.pl,glogow.info.pl###rightcol-broad > .module:nth-of-type(4)
glogow-info.pl,glogow.info.pl###rightcol-broad > .module:nth-of-type(5)
```

i dać `##.module:-abp-contains(Reklama)`

Co do góry, to jest w tej chwili:
`glogow-info.pl,glogow.info.pl###maincol-broad-800 > center > div:nth-of-type(-n+2)`
wydaje się stabilne więc można zostawić, a jeśli ktoś się boi to może dać:
`glogow-info.pl,glogow.info.pl###maincol-broad-800 > center > [style^="background:none"]`

Co do środka to to wytnie pozostałe reklamy:
`||www.gpi2.website.pl/MOK/index.php$subdocument`

Zostaną napisy w środku, które są problematyczne, można je usunąć ale drogo:
`glogow-info.pl,glogow.info.pl##.contentpaneopen:-abp-contains(Reklama)`

Jeśli za drogo to zostawić.

**Comment by gargaamel** [comment]
> xxcritixx : jak na moje potrezeby strona jest wycienta wystarczająco

Ta, jak na twoje potrzeby to wystarczy gdy fryzjer cię nierówno ostrzyże (jeden bak wyżej, drugi niżej, grzywka też nierówno) i będzie ci to odpowiadało.

**Comment by gargaamel** [comment]
xxcritixx ty też tak niedorozwinięty pajac jak majkiIT  widze, na h...uj to ruszasz i zamykasz? Nie widzisz, że nienaprawione, dalej są reklamy i napisy, twoje poczucie "wystarczającego wyciencia" gó..no kogo obchodzi, reklamy są dalej nie widzisz?

@krystian3w weź zrób jakiegoś PR i ogarnij to, jeśli możesz.
