### ISSUE TITLE
pokatne.pl / nudelle.com [NSFW]

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10273]
Błąd w Polskie Filtry RODO-Ciasteczkowe:

<details not-open>
<summary>przycisk "Wchodzę" nie działa</summary>

1
![ss068](https://user-images.githubusercontent.com/44813765/49077332-463a0580-f23b-11e8-94f8-1b66eef621e5.png)

2
![ss067](https://user-images.githubusercontent.com/44813765/49077484-aaf56000-f23b-11e8-8e15-d7a10055531e.png)

3
![ss071](https://user-images.githubusercontent.com/44813765/49078003-20adfb80-f23d-11e8-81f0-b09912a98c57.png)

4
![ss070](https://user-images.githubusercontent.com/44813765/49077835-a0879600-f23c-11e8-806b-14aa53f9945b.png)

</details>
.

<details not-open>
<summary>po wyłączeniu listy działa:</summary>

![ss069](https://user-images.githubusercontent.com/44813765/49077457-9ca74400-f23b-11e8-95eb-930b7f37dcf5.png)

</details>
.

Przycisk "Wchodzę" tak samo nie działa gdy się wchodzi w "Galerię" (która kieruje na `nudelle.com`) (screenshoot nr 3 i 4 w pierwszym spojlerze)

**Comment by gargaamel** [comment]
etykieta ciasteczka też

**Comment by gargaamel** [comment]
Etykieta ciasteczka jeszcze

**Comment by krystian3w** [comment]
"`@@/js/jquery.cookie.min.js`"

`pl###cookies_compliance`
