### ISSUE TITLE
izyrardow.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#10274]
### Zrzut ekranu
![screenshot_20181127_125802](https://user-images.githubusercontent.com/19818572/49080487-193e2080-f244-11e8-8432-9e22a34ff8e1.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Antyadblock

**Comment by krystian3w** [comment]
a ja mam cookie:

![image](https://user-images.githubusercontent.com/35370833/49080791-155ece00-f245-11e8-9130-665ae3b2ba6d.png)

**Comment by krystian3w** [comment]
`@@||izyrardow.pl/static/js/ads.js$script`
