### ISSUE TITLE
lipinscy.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10278]
Błąd w Polskie Filtry RODO-Ciasteczkowe, 

<details not-open>
<summary>pojawia się cień/tło blokujące</summary>

![ss080](https://user-images.githubusercontent.com/44813765/49083381-b2713500-f24c-11e8-822b-d0ec18c1d407.png)

</details>
.
<details not-open>
<summary>po wyłączeniu listy jest komunikat RODO</summary>

![ss081](https://user-images.githubusercontent.com/44813765/49083393-be5cf700-f24c-11e8-90c8-76e5a421ce27.png)

</details>
.
<details not-open>
<summary>po zaakceptowaniu / zamknięciu komunikatu strona ładuje się normalnie</summary>

![ss082](https://user-images.githubusercontent.com/44813765/49083415-cb79e600-f24c-11e8-84f4-2c843f5e4aa8.png)

</details>
.

**Comment by krystian3w** [comment]
Wyjątek dla ABP i css / html filtering / script inject do odblokowania przewijania.

**Comment by krystian3w** [comment]
odświeżyli rodo i inaczej osadzili, to nie działa stara metoda.
