### ISSUE TITLE
nasze-kino.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10282]
cookies

We use cookies to ensure that we give you the best experience on our website. If you continue without changing your settings, we'll assume that you are happy to receive all cookies on this website. However, if you would like to, you can change your cookie settings at any time.

**Comment by krystian3w** [comment]
O to popsułem dalej niż 6 dni wstecz...

**Comment by krystian3w** [comment]
Albo nie, jakieś nowe...

`##..cc-window[aria-label="cookieconsent"]`
