### ISSUE TITLE
mamotoja.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10281]
https://mamotoja.pl/ukladanie-puzzli-pomaga-w-nauce-czytania-i-pisania-dlaczego,gry-i-zabawy-przedszkolak-artykul,26375,r1.html
![opera zdjecie_2018-11-27_150931_mamotoja pl](https://user-images.githubusercontent.com/36385327/49087143-8064d080-f256-11e8-96f0-5d48d6a9a46f.png)

**Comment by xxcriticxx** [comment]
`||gzstatics.adtelier.pl/pub/edi/0/6/640.htm$subdocument`
or
`mamotoja.pl###adocean_context > div:nth-of-type(2)`

@MajkiIT adtelier.pl do hostu maybe?
