### ISSUE TITLE
telesystem-world.com/web/pl_pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10283]
cookies

**Comment by xxcriticxx** [comment]
This site can’t be reached telesystem-world.com took too long to respond.
Search Google for telesystem world web
ERR_CONNECTION_TIMED_OUT

**Comment by hawkeye116477** [comment]
`http://www.telesystem-world.com/web/pl_pl/electronic/home.html`

**Comment by blocker999** [comment]
https://www.telesystem-world.com/web/pl_pl/electronic/home.html

**Comment by krystian3w** [comment]
`###cookies, #cover`
