### ISSUE TITLE
drogerium.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10293]
ciasteczka / rodo / polityka

![ss066](https://user-images.githubusercontent.com/44813765/49101397-5d4a1900-f276-11e8-9867-d3866f1ba4a5.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List
- lista I'm OK with cookies

</details>

**Comment by krystian3w** [comment]
Widać przebudowali ach te uparte "`wylecz.to`".

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/b49157ec45c60ca5eac67b07882848e0150257cc#diff-019c4d6c3918d69cd67e76aeec0a04a5L285

Widać ich pozew na miliony jest za duży... to ja jeszcze proproszę cofnąć ostatnio dodane wycinanie przycisków społecznościowych :rofl:

**Comment by DRHAshino** [comment]
Spoko, commitujcie - poprawimy.

**Comment by krystian3w** [comment]
Najpierw trzeba programisty całodobowego, przyciski FB i Instagrama nadal wycięte.

Albo bawić się w przeciążenia serwera z generowaniem co odświeżenie losowych klas / id.

**Comment by gargaamel** [comment]
> krystian3w : Albo bawić się w przeciążenia serwera z generowaniem co odświeżenie losowych klas / id + losowego układu elementów w drzewie DOM.

Tak jak na https://wp.pl

**Comment by krystian3w** [comment]
Marny programista, nie przywrócił buttonów social ze stopki.
