### ISSUE TITLE
electro-torrent.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#10304]
na podstronach z torrentami, nie mozna rozwiniac pola, jakie pliki sa w torrencie.

**Comment by krystian3w** [comment]
`@@||electro-torrent.pl/overlibusers.js$script`

ale pewnie przemycają w tym reklamy

**Comment by krystian3w** [comment]
opcjonalnie można rozwinąć na zawsze CSS-em:

```css
electro-torrent.pl###ka1:style(display: block !important;)
```

**Comment by lukjan32** [comment]
pierwszy nie dziala, drugi dziala.

wolalbym sam rozwijac.

**Comment by krystian3w** [comment]
`@@||electro-torrent.pl/java_klappe.js$script`

Ale pewnie dalej to coś więcej niż prosty skrypt na spoiler.

**Comment by lukjan32** [comment]
to, dziala, prosze dodac

**Comment by MajkiIT** [comment]
Dziękuję
