### ISSUE TITLE
gram.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#10302]
### Zrzut ekranu

![2018-11-27-window](https://user-images.githubusercontent.com/5884000/49108707-26c9c980-f289-11e8-8d36-1287724430c0.png)

### Link bezpośredni

`https://www.gram.pl/news/2018/06/08/hitman-2-wymagania-sprzetowe.shtml`

### Moja konfiguracja
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by MajkiIT** [comment]
`www.gram.pl###content-root > A`

**Comment by gargaamel** [comment]
Do dupy bo:

1_

nie chwyta w innych newsach np tu:
`https://www.gram.pl/news/2018/11/27/msi-i-gigabyte-z-kartami-grafiki-rtx-2070-dla-obudow-itx.shtml`
bo w tym przykładowym artykule jest w środku `p` więc musi być `www.gram.pl###content-root > p > A`

2_
w innych newsach wycina omyłkowo linki w treści newsa:
`https://www.gram.pl/news/2018/11/27/ponad-10-gier-zostanie-ogloszonych-na-the-game-awards.shtml`
<details not-open>
<summary> screenshoot 1</summary>

![ss070](https://user-images.githubusercontent.com/44813765/49112844-1f5bed80-f294-11e8-8f89-663cb65fe779.png)

</details>
.

3_

żeby było śmieszniej, podany peze ze mnie wyżej filtr `www.gram.pl###content-root > p  > A`, który bezproblemowo wycinał samą reklamę w linku podanym przeze mnie wyżej w 1_, w linku podanym w 2_ oprócz reklamy wycina tak jak w 2_ link w newsie oraz obrazek w newsie:

<details not-open>
<summary> screenshoot 2</summary>

![bez nazwy](https://user-images.githubusercontent.com/44813765/49113205-32bb8880-f295-11e8-9ec2-270ed41cc6cb.png)

</details>
.

**Comment by krystian3w** [comment]
`gram.pl##a[target="_blank"] > img.inner`

**Comment by gargaamel** [comment]
Też do dupy bo w przykładowym linku z 2_ wycina dodatkowo omyłkowo obrazek (ten sam co na zrzucie w screenshoot 3):

<details not-open>
<summary>screenshoot 4</summary>

![ss071](https://user-images.githubusercontent.com/44813765/49142701-b73ff280-f2f9-11e8-981d-573e0486a624.png)

</details>
.

No i zamiast `gram.pl` ma być` www.gram.pl`, bo jest sporo poddomen typu `poddomena.gram.pl`, na których:
- po pierwsze ten filtr mógłby coś uszkodzić
- po drugie nie ma tam reklam do wycinania tym filtrem

**Comment by krystian3w** [comment]
`:not([href*="gram"])` ale też walnie jak będą bawić się w WP i coś typu `kobieta.wp.pl` na `facet.wp.pl` jako link otwierający coś.

**Comment by gargaamel** [comment]
> @krystian3w : `:not([href*="gram"])`

Nie pomaga, dalej jest to samo i wycina obrazek jak w https://github.com/MajkiIT/polish-ads-filter/issues/10302#issuecomment-442383348.
I w ogóle nie wiem co miałoby to dać, chyba ci się coś pomyliło, bo to :`not` oznacza, że coś nie znajduje się w elemencie, a nie, że nie zawiera tego elementu.

**Comment by krystian3w** [comment]
Grafika nie może mieć `href=" "`

O takie coś mi chodziło:

![image](https://user-images.githubusercontent.com/35370833/49144407-9aa5b980-f2fd-11e8-980a-197c7557f65e.png)

----

Najwyżej będzie trzeba to dodać w kliku filtrach, nie wszystkie mają w linku:

* `/promo/`
* `utm_medium=News_banner` 
* `utm_content=News_banner`

**Comment by gargaamel** [comment]
To w takim razie rzeczywiście działa, i z tego co patrzyłem jest ok i nic przypadkowego nie wycina, dla pewności można jeszcze zmienić `="gram"` na `="gram.pl"`, bo może trafić się reklama z linkiem typu `https://gramyiwygyrywamy.pl/` i wtedy jej nie wytnie.
