### ISSUE TITLE
progrupa.com

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10318]
ciasteczka

![ss081](https://user-images.githubusercontent.com/44813765/49156891-cc7b4800-f31e-11e8-8690-33d5d2e29adb.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
A to co za badziewie:

> Know konami code? ➡ try it on Progrupa.com!

![image](https://user-images.githubusercontent.com/35370833/49159373-ab1d5a80-f324-11e8-8702-d2b7b81fbc97.png) |
--- |

**Comment by krystian3w** [comment]
Niby działa:

![obraz](https://user-images.githubusercontent.com/35370833/49168151-343d8d00-f337-11e8-8411-8d080872b2c7.png) |
--- |

Matrix mode on... ale bardziej mi chodziło jakim prawem skrypt w konsoli takie głupoty wyświetla jeszcze brakuje by wykonał jakiś kod luką 0 day.

**Comment by gargaamel** [comment]
> krystian3w  : jakim prawem skrypt w konsoli takie głupoty wyświetla

Prawem polecenia `console.log()`
