### ISSUE TITLE
kill adserwer.afilo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1032]

**Comment by gwarser** [comment]
Coś zostało z tym zrobione?
Na wykopie dodaje się tracking pixel `http://adserwer.afilo.pl/o/d106db1526648406,10fdba73fe0a9171?subid=null`
Teraz mam go tutaj `https://www.wykop.pl/wpis/32129599/` siedzi sobie w banerze po prawej stronie.
