### ISSUE TITLE
sopset.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1033]
`http://sopset.pl/`
Po wejściu na stronę, po około 30 sekundach pojawia się komunikat o adblocku.

![image](https://cloud.githubusercontent.com/assets/11742596/16015411/ce1a7110-3195-11e6-99e4-1fb0b4bcdb70.png)

`sopset.pl#@#.adsbygoogle`
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=sopset.pl`
`@@||pagead2.googlesyndication.com/pagead/js/r*/show_ads_impl.js$script,domain=sopset.pl`

**Comment by MajkiIT** [comment]
Dzięki

**Comment by MajkiIT** [comment]
Muszę być zalogowany?

**Comment by F4z** [comment]
Wcześniej na tej stronie dostępny był stream meczów z Euro 2016 i nie trzeba było się logować.
Teraz jak jak widać wymagana jest rejestracja i opłata za serwis.
Zamykam zgłoszenie, jak coś się zmieni, to wtedy napiszę.
