### ISSUE TITLE
procpu.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10345]
https://procpu.pl/p/1727/46559/defender-stalker-gk-170l-klawaitura-mechaniczna-outemu-blue-bonus-klawiatury-gaming-strefa-gracza.html
![opera zdjecie_2018-11-29_005712_procpu pl](https://user-images.githubusercontent.com/36385327/49190226-b9de2e80-f371-11e8-897a-49540d6b02e8.png)

**Comment by xxcriticxx** [comment]
@xMaap more info please?

**Comment by krystian3w** [comment]
Y Fanboy Cookie list...?

**Comment by krystian3w** [comment]
Nie umiem odtworzyć, może ktoś da radę.

**Comment by gargaamel** [comment]
A ja umiem, przyczyną problemu są filtry wewnętrzne @KonoromiHimaries

**Comment by krystian3w** [comment]
A jakiś konkretny, mnie w uBO lista nie zbugowała strony.

**Comment by krystian3w** [comment]
A mam już... się zestarzał.

**Comment by krystian3w** [comment]
@KonoromiHimaries https://github.com/KonoromiHimaries/PolishSubFilters/pull/46
