### ISSUE TITLE
ppe.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10346]
https://www.ppe.pl/news/127622/metal-gear-solid-doczeka-sie-odswiezonej-wersji-konami-zarejestrowalo-nowe-znaki-towarowe.html

Włączone
![opera zdjecie_2018-11-29_052503_www ppe pl](https://user-images.githubusercontent.com/36385327/49199332-95954880-f397-11e8-95f4-34819af68038.png)
Wyłączone
![opera zdjecie_2018-11-29_052546_www ppe pl](https://user-images.githubusercontent.com/36385327/49199333-95954880-f397-11e8-8b3c-9ff8cea56791.png)

**Comment by MajkiIT** [comment]
@xMaap Nie łapie co jest nie tak :/

**Comment by krystian3w** [comment]
Ja też nie...

**Comment by xMaap** [comment]
Jak nie da się to zamknąć i już :laughing:
