### ISSUE TITLE
cedc.com

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10366]
ciasteczka

![ss118](https://user-images.githubusercontent.com/44813765/49226117-04998e00-f3e6-11e8-86ca-6d84662820db.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
Podobno fałszywka - KAD.

**Comment by gargaamel** [comment]
Racja, zapomniałem włączyć listy KAD - Przekręty, wykorzystując otwarte zgłoszenie, zaktualizowałem zgłoszenie.

**Comment by krystian3w** [comment]
`cedc.com###cookies`
