### ISSUE TITLE
mondeoklubpolska.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10369]
http://www.mondeoklubpolska.pl/forum.php
![opera zdjecie_2018-11-29_134850_www mondeoklubpolska pl](https://user-images.githubusercontent.com/36385327/49222909-8802b180-f3dd-11e8-938b-2537aae5dc70.png)

**Comment by krystian3w** [comment]
`mondeoklubpolska.pl#@#.ad_global_header`

Polują na EasyList.

**Comment by MajkiIT** [comment]
Ja tego nie mam :/

**Comment by krystian3w** [comment]
Ja niestety mam i nie umiem dodać wyjątków (nie namierzyłem wabików).

**Comment by MajkiIT** [comment]
Nano defender chyba łapie ...

**Comment by krystian3w** [comment]
mam wyjątek:

`@@||mondeoklubpolska.pl/adframe.js`

w pliku jest zmienna nadpisująca:

```html
<script type="text/javascript">
    var adblock = true;
</script>
```

na FALSE.

**Comment by MajkiIT** [comment]
@krystian3w Dziekuję
