### ISSUE TITLE
fili.cc

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#10361]
Reklama CDA 

![screenshot_1](https://user-images.githubusercontent.com/21177361/49219005-4c161f00-f3d2-11e8-8f63-875c389db0c6.png)

https://fili.cc/film/camp-rock-2008/4792

**Comment by gargaamel** [comment]
`||n-*-*.dcs.redcdn.pl/file/o2/cda/vstatic/vast/*.mp4$media,domain=ebd.cda.pl`
