### ISSUE TITLE
oldcamera.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10373]
http://oldcamera.pl/popiol-i-diament-tragiczny-obraz-powojennej-polski/
![opera zdjecie_2018-11-29_140338_oldcamera pl](https://user-images.githubusercontent.com/36385327/49223660-a49fe900-f3df-11e8-8563-19970797b90c.png)
![opera zdjecie_2018-11-29_140346_oldcamera pl](https://user-images.githubusercontent.com/36385327/49223662-a49fe900-f3df-11e8-9f2b-3ff8d9436189.png)

**Comment by MajkiIT** [comment]
@xMaap Social ?

**Comment by xMaap** [comment]
@xMaap Tak
