### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10379]
Jakieś błędy, raz strona:

<details not-open>
<summary>nie ma scrolla</summary>

![ss123](https://user-images.githubusercontent.com/44813765/49227182-c9e52500-f3e8-11e8-8658-64132bd3d904.png)

</details>
.
<details not-open>
<summary>a innym razem ładuje się tak:</summary>

1
![ss121](https://user-images.githubusercontent.com/44813765/49227025-6ce96f00-f3e8-11e8-8c92-36b4e394ec30.png)

albo

2
![ss122](https://user-images.githubusercontent.com/44813765/49227120-a28e5800-f3e8-11e8-847a-4cd943f2e7ef.png)

</details>

**Comment by krystian3w** [comment]
@MajkiIT `.ws__wrapper` chyba wywołuje awarie ładowania grafik i CSS-a.

Scrolla raczej nie  (ja mam).

**Comment by krystian3w** [comment]
dla testu:

```
filmweb.pl#@##iframe, .clickArea, .screening-content, .topBillboard, .BILLBOARD, [id^="sad_"], .clickableAdBG, #screening, [id$="_ifame"], [id^="sas_"], div[class] > [href*="/click"], [src$=".html"], .advBtn, .ws__wrapper
filmweb.pl###iframe, .clickArea, .screening-content, .topBillboard, .BILLBOARD, [id^="sad_"], .clickableAdBG, #screening, [id$="_ifame"], [id^="sas_"], div[class] > [href*="/click"], [src$=".html"], .advBtn
filmweb.pl##.ws__wrapper
```

**Comment by krystian3w** [comment]
Scroll jest po reklamie, widać czyściłeś ciastka.

**Comment by krystian3w** [comment]
Scroll jest po reklamie, mam takie coś po wyczyszczeniu ciasteczek na te ~15 sekund emisji.

---

Błąd potem nie do wyjaśnienia jak dla mnie - jakby reklama blokowała dostęp do obrazów / grafik i  CSS / JS.

**Comment by MajkiIT** [comment]
@F4z Pomożesz?

**Comment by hawkeye116477** [comment]
Ja tam nie wiem o co chodzi, takiego problemu nie mam, za to czasem strona się coś psuje i błędnie wyświetla, tzn. 0 grafiki.

**Comment by krystian3w** [comment]
Scroll na pewno od reklamy lecącej mimo wycięcia jej elementu, bo u mnie wracał po 15 sekundach.

**Comment by MajkiIT** [comment]
Sprawdźcie to:

```
@@||go.eu.bbelements.com/please/code$script,domain=www.filmweb.pl
@@||ssl.mousestats.com/$script,domain=www.filmweb.pl
filmweb.pl#@#[class$="-ads"]
filmweb.pl#@#.adv_container
filmweb.pl#@#+js(setTimeout-defuser.js, notDetected)
```

**Comment by gargaamel** [comment]
Ty buraku etykiety poporawiaj mi w moich zgłoszeniach, bo jak nie to masz w mordę, i to przy wszystkich tu obecnnych https://github.com/MajkiIT/polish-ads-filter/issues/10407#issuecomment-443163572

**Comment by krystian3w** [comment]
Ktoś mi powie co robią `|` na końcu filtra sieciowego, przed określeniem typu, zakresu, domeny.
