### ISSUE TITLE
uplayconnect.ubi.com

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1037]
Ta reguła z ciasteczkowych filtrów blokuje możliwość zalogowania się na stronie Ubisoftu:
`/js/jquery.cookie.min.js$script`

Link do strony - `https://uplayconnect.ubi.com/?appId=880650b9-35a5-4480-8f32-6a328eaa3aad`
Na tej stronie powinna być możliwość wpisania loginu i hasła, ale reguła podana wyżej blokuje to, i widać tylko napis "Please wait...".

Gdyby link nie działał, to wejdź tutaj - `https://uplay.ubi.com/` potem na górze po prawej kliknij przycisk "Log In", powinno pokazać się okienko z możliwością zalogowania, ale cały czas widoczny jest tylko pasek ładowania.

![image](https://cloud.githubusercontent.com/assets/11742596/16048880/f7bd574c-3255-11e6-906a-6537db534e42.png)

**Comment by MajkiIT** [comment]
Dzięki poprawię.
