### ISSUE TITLE
androidnow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1039]
cookies + reklama z googleadservices.com

Ta strona używa cookies! Więcej informacjiTak wiem!

**Comment by MajkiIT** [comment]
nic takiego nie widzę.

**Comment by xxcriticxx** [comment]
zgadza sie poczekamy do jutra i zobaczymy

**Comment by xxcriticxx** [comment]
http://androidnow.pl/tapety/
http://androidnow.pl/news/
http://androidnow.pl/artykuly/

dzisaj tylko widze tapete pilke strony niema

**Comment by xxcriticxx** [comment]
@MajkiIT te strony sa cale biale jak wyloncze ublock wszystko jest ok tylko pelno reklam. sprawdzisz plz

http://androidnow.pl/reklama/
http://androidnow.pl/artykuly/
