### ISSUE TITLE
peka.poznan.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10399]
rodo

![ss144](https://user-images.githubusercontent.com/44813765/49253247-74c80400-f426-11e8-8f05-41deb9efa199.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by MajkiIT** [comment]
@gargaamel widzę, że standardowo musisz dorzucić zgłoszeń do odcięcia?

**Comment by krystian3w** [comment]
98% wycięte (coś mogłem źle wyciąć lub przeskoczyłem zgłoszenie), niestety mnie nie po drodze z gitem, bashem, gpg.
