### ISSUE TITLE
wyceniono.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10407]
rodo

![ss146](https://user-images.githubusercontent.com/44813765/49278527-5e04ca00-f485-11e8-8397-f6d55e7bdb9f.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
```
wyceniono.pl##^script:has-text(cookies)
wyceniono.pl$$.script[tag-content="cookies"]
wyceniono.pl##.qinfo
wyceniono.pl##.cinfo > *:style(filter: none !important;)
wyceniono.pl##.cinfo:style(overflow: auto !important;)
```

raczej ten skrypt liniowy więcej nie robi poza generowaniem daty na jakiś okres w ciasteczku.

**Comment by gargaamel** [comment]
No i zobacz @krystian3w dopiero co mu uwagę zwróciłem żeby poprawnie etykietował:  https://github.com/MajkiIT/polish-ads-filter/issues/10399#issuecomment-443115140, a ten czubek dalej daje etykietę ciasteczka zamiast rodo, pomimo, że ułatiwam mu robotę bo napisane ma jak wół: rodo, widać robi po złości.

**Comment by gargaamel** [comment]
@xxcriticxx czy mógłbyś zmienić etykietę na rodo? Nie każę ci, jeśli miałbyś chwilę czasu.
