### ISSUE TITLE
drogerium.pl (2)

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10406]
Rodo - reopen https://github.com/MajkiIT/polish-ads-filter/issues/10293, bo dalej to jest.

**Comment by krystian3w** [comment]
Już w dodatku, zaktualizuj do wersji 1.6, niestety skrypt dalej nie sprawdza wersji na Windows, nie umiem zrobić regexu w powershell a nie chce po cichu instalować jakiś wynalazków  dodających `sed.`

Zaproponowałem dodać tam, bo pokazałem że filtr wylatuje a sociale ma grupa `drogerium.pl & wylecz.to` widać gdzieś... (jakby brak kasy od FB, Insta, Twittera itd.).

**Comment by gargaamel** [comment]
Aktualizowałem przed reopenem - wciskałem "znajdź aktualizacje" i nie było aktualizacji, więc rozumiem, że aktualizacja wyszła po reopenie, bo teraz faktycznie, znowu wcisnąłem "znajdź aktualizacje" i już jest 1.6 i wycina to, więc teraz jest ok, więc zamykam.

**Comment by krystian3w** [comment]
W chromowatych trzeba ręcznie lub na własną odpowiedzialność odpalać wersję testową skryptu (na podstawie dwóch podobnych).

**Comment by krystian3w** [comment]
I lepiej ograniczyć uruchamianie do jednego na dzień by nie wykorzystać limitów zapytań github API.
