### ISSUE TITLE
przedszkolowo.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10411]
ciasteczka , nie mylić z przedszkolakowo.pl

![ss149](https://user-images.githubusercontent.com/44813765/49279761-9d80e580-f488-11e8-84a6-131eae8b710a.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
Tu mają fajną klasę a tam jakąś z cyframi i na szczęście liniowym CSS (może po nim będę łapać `przedszkolakowo.pl`)

**Comment by booleek** [comment]
> gargaamel : ciasteczka , nie mylić z przedszkolakowo.pl

I z przedszkola**n**kowo.pl https://github.com/ryanbr/fanboy-adblock/issues/715

**Comment by krystian3w** [comment]
Ja nie mam, pop-up "daj dotacje" wycinany w pop-upach EI.
