### ISSUE TITLE
swiat-whisky.sklep.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#10417]
### **RODO**

![ss157](https://user-images.githubusercontent.com/44813765/49286411-5a2f7280-f49a-11e8-9f23-8f1f45a7cd4e.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
@hawkeye116477  czemu te fancyboxy zamykają się tak że potem w żadnej przeglądarce nie muszę ich akceptować - brak w trybie prywatnym / innej przeglądarce (nawet w IE11 już nie wyskakuje).

**Comment by blocker999** [comment]
a " fb " ( button ) ?
