### ISSUE TITLE
iperfumy.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10426]
cookies 

Ta strona w kontekście świadczenia usług wykorzystuje pliki cookie, korzystając z witryny, zgadzasz się z ich stosowaniem. Aby uzyskać więcej informacji, w tym informacje usunięciu i zamknięciu zobacz tutaj.

**Comment by hawkeye116477** [comment]
`pl###cookie-compliance:not(body):not(html)`
