### ISSUE TITLE
stoczniowcy.pl

### ISSUE THREAD

**Issue by booleek** [MajkiIT/polish-ads-filter#10440]
pusty kontener po reklamie u góry `www.stoczniowcy.pl###reklama_top`

![ss169](https://user-images.githubusercontent.com/45492904/49329403-a653e300-f57e-11e8-88f0-20946cfbcb58.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- POL: polskie filtry do Adblocka i uBlocka​​​
- Adguard Base Filters
- EasyList Polish​
- Fanboy's Polish (wiem - nie wspierane)

</details>

**Comment by krystian3w** [comment]
Nie może być, nawigacja się przesuwa, chyba że taki fatal error nam odpowiada.

![obraz](https://user-images.githubusercontent.com/35370833/49332237-ce0c7080-f5a9-11e8-8f53-2317b9d9a270.png) |
--- |

**Comment by krystian3w** [comment]
trochę pomaga na error:

```
||www.stoczniowcy.pl/img/bg.jpg
```

lub CSS-em usunąć tło na dłużej.

---

I takie coś na reklamy z kolumn:

`www.stoczniowcy.pl#?#a:-abp-has([src^="img/reklama_"])`
