### ISSUE TITLE
powiatkamienski.pl

### ISSUE THREAD

**Issue by booleek** [MajkiIT/polish-ads-filter#10445]
rodo

![ss173](https://user-images.githubusercontent.com/45492904/49329575-70642e00-f581-11e8-874b-59206bb9cc9a.png)
![ss174](https://user-images.githubusercontent.com/45492904/49329576-70642e00-f581-11e8-8282-46fe9df3ae73.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
@hawkeye116477 do dodatku chyba
