### ISSUE TITLE
ugb.pl

### ISSUE THREAD

**Issue by booleek** [MajkiIT/polish-ads-filter#10453]
rodo

Powodzenia z tym na Firefoxie, na Operze poniższe filtry działają (poza `html` oczywiście), natomiast na Firefoxie nic nie działa

```
ugb.pl##^script:has-text(RODO)

ugb.pl##+js(abort-current-inline-script.js, alert, RODO)
ugb.pl##+js(abort-on-property-read.js, alert, RODO)
ugb.pl##+js(set-constant.js, alert(), noopFunc)
ugb.pl##+js(alert-buster.js)
```

o ile nie działa filtr `html` to mnie nie dziwi, bo : `charset=iso-8859-2'>`
ale żeby było zabawniej to `inject ` też nie działają, może gdzieś na repo uBO jest jakiś wątek o niedziałających `inject` w Firefoxie dla  `content='text/html; charset=iso-8859-2'>`

![ss176](https://user-images.githubusercontent.com/45492904/49330150-1e280a80-f58b-11e8-9d95-3a4ff1cc8997.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
Idzie do web archive, bo jak mi zniknie to sam nie zrobię...

**Comment by krystian3w** [comment]
W Firefox mnie działa to co dodałem i każde z osobna:

`ugb.pl##+js(abort-on-property-read.js, alert, RODO)`

`ugb.pl##+js(abort-current-inline-script.js, alert, RODO)`

`ugb.pl##+js(alert-buster.js)`

Jak połączyłeś moc skryptów to sam sobie zbugowałeś, wtedy mi też nie działa.

---

Lub jakiś dziwny bug z tym tagiem meta / xml / race condition / bug `set-constant.js`

**Comment by krystian3w** [comment]
`ugb.pl##+js(set-constant.js, alert(), null)`  taki set-constant też mi działa w Firefox, jakby bug z `noopFunc`.

Aż jestem ciekawy jak null dla set-constant działa w wersji dev z tą stroną - bo **`@`gorhill** go doprogramował.

**Comment by hawkeye116477** [comment]
@krystian3w Ale abort-on-property-read.js ma tylko 1 parametr.

**Comment by krystian3w** [comment]
Widać zależy to jakoś też od platformy skoro mnie potrafi ubijać alerty.

Najlepiej dodać `ugb.pl##+js(abort-current-inline-script.js, alert, RODO)` jak obsługuje 2 parametry i obserwować jak idzie naprawa bugów z meta charset / xml.

**Comment by krystian3w** [comment]
O w wersji 1.17.4 przeprogramowano już chyba null i **nie działa** mi:

`ugb.pl##+js(set-constant.js, alert(), null)`
