### ISSUE TITLE
finanse.wp.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#10452]
```
https://finanse.wp.pl/leszek-czarnecki-chroni-swoja-prywatnosc-mieszka-w-miami-6318930932107393a
```

Coś mi z uBlock Origin wycina film z artykułu... na Firefox 63.0.3 x64.

![obraz](https://user-images.githubusercontent.com/35370833/49330027-fb94f200-f588-11e8-80de-3b0310b89d9d.png) |
--- |

I wraca po całkowitej dezaktywacji `POL: polskie filtry do Adblocka i uBlocka​​​​​​​​`

**Comment by booleek** [comment]
Ten psuje: `~www.wp.pl,wp.pl##[class^="css-"]` trzeba dodać wykluczenie, tylko pytanie czy na innych poddomenach `wp.pl` też nie wcina filmu, bo wtedy być może trzeba będzie dodać więcej wykluczeń...

**Comment by krystian3w** [comment]
A jeszcze czemu ten filtr nie działa w Nano Adblocker?

userCSS w uBO wygrywa z WP a z braku w Nano Adblocker ukrywa mniej?

**Comment by booleek** [comment]
No właśnie nie wiem dlaczego, interesujące, bo w końcu to nie `inject`, który podlega wahaniom race condition w zależności od przeglądarki i szybkości komputera, tylko zwykły filtr kosmetyczny.

**Comment by booleek** [comment]
Nawet mi ten filtr nie podświetla tego filmiku w NA:

![ss192](https://user-images.githubusercontent.com/45492904/49331193-a1e8f380-f599-11e8-8af1-d3035709aa94.png)

Może dlatego nie łapie, może strona serwuje trohcę inną zawartośc na chromowatych i ma inne domy.

**Comment by krystian3w** [comment]
Może alfa od kobry :snake:: https://github.com/LiCybora/NanoCoreFirefox#nano-adblocker-core-for-firefox-unoffical

**Comment by booleek** [comment]
Wiesz co, nie wiem co jest grane, teraz gdy whitelistuję ten filtr to filmik i tak sie nie pojawia, więc to może nie ten filtr tylko jakiś `inject` z nami pogrywa.

**Comment by poompon** [comment]
Chciałem tylko dopisać jeszcze, (bo ten pedofil i kat komunistyczny dał mi właśnie bana po cichutku), żeby było jasne, że to naprawdę nie ten kosmetyk naprawił film bo na FF + uBO mam tak jak na NA + Opera:

<details not-open>
<summary>kosmetyk też nie łapie tego filmiku na FF</summary>

![ss194](https://user-images.githubusercontent.com/45492904/49331523-a06dfa00-f59e-11e8-826e-c3ef1918c4e2.png)

</details>
.

Więc najprawdopodobniej jakiś `inject` ma race condition i się bawi z nami.
