### ISSUE TITLE
tv.eurosport.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10473]
cookies

**Comment by krystian3w** [comment]
`||quantcast.mgr.consensu.org/v11/cmp.js` jak coś psuje to niestety zostaje tylko ubijanie późniejszych skryptów / xhr lub CSS-em naprawić przewijanie.

**Comment by krystian3w** [comment]
Podłączyłem pod inny filtr na quantcast

```
||static.quantcast.mgr.consensu.org/*/cmpui-banner.js$domain=tv.eurosport.pl
```

Dalej do obserwacji czy wideo działają, w innych serwisach niby quantcast blokuje wideo.
