### ISSUE TITLE
Mobile ads filter

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10472]
@MajkiIT wyciagniesz cos z tego scriptem?

https://filters.adtidy.org/extension/chromium/filters/11.txt

**Comment by MajkiIT** [comment]
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/adguard_mobile_host.txt

**Comment by krystian3w** [comment]
A czymś się różnią filtry dla innych platform (maOS, iOS (tam nawet jest filtr pod mobile safari), Firefox)?

**Comment by krystian3w** [comment]
`https://filters.adtidy.org/extension/firefox/filters/11.txt`
`https://filters.adtidy.org/windows/filters/11.txt`

**Comment by xxcriticxx** [comment]
@krystian3w ios ma 50k limit

**Comment by krystian3w** [comment]
iOS:

https://filters.adtidy.org/extension/firefox/filters/12.txt
https://filters.adtidy.org/mac/filters/12.txt
https://filters.adtidy.org/windows/filters/12.txt


---

Wiem, ale mają jakieś hosty np. blokadę pop-up.

**Comment by xxcriticxx** [comment]
@krystian3w byl plan zeby zrobic 7 albo 10 list po 50k na kazdej zeby ominelo limit

zapytaj adama @F4z po co tyle list

**Comment by hawkeye116477** [comment]
Dla FF mogą być jakieś dodatkowe reguły. To jest tak jak z dyrektywami `!#if` w uBO.
