### ISSUE TITLE
milenium.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10486]
![opera zdjecie_2018-12-03_112012_www milenium pl](https://user-images.githubusercontent.com/36385327/49367882-973f7300-f6ed-11e8-82b0-decd56a41b16.png)

**Comment by krystian3w** [comment]
`##.cookie_acceptation`

**Comment by krystian3w** [comment]
Reklama mam na dzieje, że wewnętrzna, że znowu nie wycinam w złym miejscu.
