### ISSUE TITLE
ktomalek.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10482]
cookies

**Comment by xxcriticxx** [comment]
@krystian3w please PR

**Comment by krystian3w** [comment]
Nie umiem uruchamiać tego skryptu, a nie chce co wersje wysyłać do dev wersji z usuniętym -S.

Jakiegoś gpg niby nie miałem w bashu aktywnego.

**Comment by krystian3w** [comment]
`git commit -S -m` chyba nie problemem, nie widzę RTM.

**Comment by krystian3w** [comment]
@hawkeye116477  polecasz jakieś dystrybucje pod Virtualbox? Ale taka żeby mi nie walnęła jak sobie zrobią kolejną rewolucje z np. `nowy interpreter JavaScriptu SpiderMonkey 52`, tak padł mi testowy Arch kiedyś - pierwszy start zamrażał XFCE.

**Comment by hawkeye116477** [comment]
@krystian3w No to jak to był Arch Testing, to wiadomo, że niestabilne i mogą różne rzeczy się dziać. Ja korzystam z Manjaro KDE, ale pod Virtualbox to może lepiej coś lżejszego, może Manjaro Deepin albo Manjaro LXDE. A tak w ogóle to polecam zamienić Virtualbox na VMWare Player, który jest o niebo lepszy, wydajniejszy :smile:.
