### ISSUE TITLE
miastodzieci.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10498]
Tło
![opera zdjecie_2018-12-04_131228_miastodzieci pl](https://user-images.githubusercontent.com/36385327/49441273-4ea7b880-f7c6-11e8-82a4-2db1f173d000.png)
Social
![opera zdjecie_2018-12-04_131237_miastodzieci pl](https://user-images.githubusercontent.com/36385327/49441274-4ea7b880-f7c6-11e8-8093-2e7e57608ea4.png)

**Comment by krystian3w** [comment]
Tło e EI?....
