### ISSUE TITLE
muzeumwspolczesne.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10494]
![opera zdjecie_2018-12-04_130817_muzeumwspolczesne pl](https://user-images.githubusercontent.com/36385327/49441058-aeea2a80-f7c5-11e8-9f5c-f649f60d75a3.png)

**Comment by krystian3w** [comment]
@travis-ci dostało fiksacji, 20 minut przetwarza plik...
