### ISSUE TITLE
forum.android.com.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#10490]
### Zrzut ekranu
![screenshot_20181203_142445](https://user-images.githubusercontent.com/19818572/49376348-39b82000-f707-11e8-96f3-42052e4aba0a.png)

**Comment by krystian3w** [comment]
Jak dla mnie awaria forum.

**Comment by krystian3w** [comment]
`File not found.` jak otwieram tematy / działy.

`https://forum.android.com.pl/forum/1808-rom-y-modyfikacje/`

**Comment by hawkeye116477** [comment]
Ok, zamykam, już jest gites :smile:.

**Comment by krystian3w** [comment]
Jeszcze coś tam się wali, nie da się zamknąć paska z zachętą do pracy:

`https://android.com.pl/news/160532-wordpress-developer-praca/`
