### ISSUE TITLE
plejada.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10507]
sociale po boku w artykułach, np tu : https://plejada.pl/newsy/conchita-wurst-zapowiada-powrot-jestem-gotowa-na-koncert-w-polsce/n901fwb

**Comment by krystian3w** [comment]
Ja ładnie nie umiem, bo zostaje w tym latającym puste koło.

**Comment by krystian3w** [comment]
```css
plejada.pl###content-share-top > .fb_share
plejada.pl##.detailContentWrapper .contentShareLeft .fb_share:style(background: transparent !important;)
```

**Comment by krystian3w** [comment]
Jak nie chcecie koła z Adblock Plus to trzeba wyciąć licznik komentarzy i przycisk "cofnij".
