### ISSUE TITLE
anime-odcinki.pl

### ISSUE THREAD

**Issue by wooles** [MajkiIT/polish-ads-filter#10509]
![ldixji3 1](https://user-images.githubusercontent.com/9068595/49520971-afa5be00-f8a4-11e8-8fa5-c642dfaadfe9.png)

**Comment by krystian3w** [comment]
hmmm...

**Comment by krystian3w** [comment]
@OtakuPL :rofl:

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/004b9a964afae50f590e6bf68ac72e893b7c282a#diff-6de60f294b8bd23c752f8fcbece875b1
