### ISSUE TITLE
podrogach.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#10503]
### Zrzut ekranu
![screenshot_20181204_215048](https://user-images.githubusercontent.com/19818572/49472018-ae29b680-f80e-11e8-8f41-553b9e624afa.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Reklamy opon i resztka po reklamie.

**Comment by krystian3w** [comment]
`podrogach.pl###popup_container`
