### ISSUE TITLE
internet.senior.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10505]
cookies i sociale w artykułach, np tu : http://www.internet.senior.pl/153,0,5-grudnia-2018-8211-Dzien-Darmowej-Dostawy,22858.html

**Comment by krystian3w** [comment]
E-mail to już social?

`##.podziel_links > img:nth-of-type(-n+4)`

Bo nie wiem czy nie wyciąć po prostu całego `##.podziel_links` i trudno z opcją wysyłania maila.

**Comment by krystian3w** [comment]
AdGuard np. już nie honoruje przycisków kopiuj link  / drukuj artykuł. Bo link mamy w pasku adresu a drukuj pod Ctrl + P lub w menu kontekstowym.

**Comment by blocker999** [comment]
@krystian3w  e-mail raczej nie ale to jest powiadomienie znajomego a to już bym chował, zresztą to jest tylko moje zdanie najlepiej poczekajmy na opinie @hawkeye116477 a może między czasie ktoś inny wyrazi swoją opinię ?

**Comment by hawkeye116477** [comment]
Drukowanie to raczej zostawić, ale kopiowanie linku i udostępnianie na maila to można-by wyciąć.

**Comment by krystian3w** [comment]
To poleci cały box links.

**Comment by krystian3w** [comment]
Done https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/a7392d7680e39281a0afdafe4cf81cc7600e6a76.
