### ISSUE TITLE
totalcasino.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10517]
![opera zdjecie_2018-12-05_195950_www totalcasino pl](https://user-images.githubusercontent.com/36385327/49537113-5ea7c100-f8c8-11e8-8351-bb8b9337bfc3.png)

**Comment by krystian3w** [comment]
Cookies i RODO powycinane, błąd o wycinaniu pop-upa z weryfikacją wieku może zgłoszę do Fanboya...

**Comment by krystian3w** [comment]
Fanboy jednak nie wycina pop-up-a o wieku:


> ![](https://user-images.githubusercontent.com/35370833/49538666-46d23c00-f8cc-11e8-926b-d73694c704d4.png) |
> --- |


Więc nie będę robił  śledztwa by wrócił jak nie wiem gdzie zacząć szukać.

**Comment by hawkeye116477** [comment]
A to hazardzista :smiley:

**Comment by krystian3w** [comment]
Że hoho...

**Comment by krystian3w** [comment]
To działa na Polskich deenesach?

**Comment by hawkeye116477** [comment]
@krystian3w No u mnie działa.
Skoro to nie jest problem związany z naszymi listami, to raczej do zamknięcia, a @xMaap powinien przeanalizować co tam ma, powyłączać, powłączać, a jak już znajdzie przyczynę to zgłosić tam gdzie trzeba :smile:.

**Comment by krystian3w** [comment]
Ja mogę zapewnić że RODO wyciąłem instrukcją `:if-not()` a nie po samym ID, jak zauważyłem że jest dynamicznie podmieniany środek.

Więc RTM problemu za kogoś nie naprawi i dalej będzie stało na wyciętym pytaniu o wiek.

**Comment by krystian3w** [comment]
W sumie nie namierzy o RTM się odblokuje scroll a overlay raczej się nie chwyci czymś takim:

`##.fn-popups:has(.gdpr-popup) ~ .fn-overlay`

**Comment by xMaap** [comment]
Winny jest Fanboy's Cookie List

**Comment by krystian3w** [comment]
A czyli jednak zielony guzik zatwierdzony.

**Comment by krystian3w** [comment]
To u nas i tak będzie dalej filtr z has lub łagodniejszy połączony z overlay.
