### ISSUE TITLE
gry.lotto.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10516]
![opera zdjecie_2018-12-05_195428_gry lotto pl](https://user-images.githubusercontent.com/36385327/49536831-c6a9d780-f8c7-11e8-9421-294932d79ddb.png)

**Comment by krystian3w** [comment]
Na razie wyciąłem cookies z góry, potem zobaczę na ile da się sieciowo RODO.

**Comment by krystian3w** [comment]
```css
gry.lotto.pl###baseModal, .modal-backdrop
gry.lotto.pl##.modal-open .portal-container:style(filter: none !important;)
sochaczew.pl,multimediago.pl,dane.gov.pl,24wroclaw.pl,zwolen.pl,wrzesnia.info.pl,ceres.pl,komugroup.eu,gry.lotto.pl##.modal-open:style(overflow: auto !important; padding-right: 0 !important;)
```

**Comment by lukjan32** [comment]
ja sie dolaczam, nie mozna potwierdzic, aby wyslac kupon, nie reaguje przycisk

**Comment by krystian3w** [comment]
@hawkeye116477 trzeba chyba wrzucić do dodatku jak się nie da injectem obejść.

**Comment by krystian3w** [comment]
Chyba, że doprecyzować pop-up i nie będzie blokowany nadmiarowy

**Comment by hawkeye116477** [comment]
Z tym obejściem, to nie wiem jak i co, bo tak szczerze mówiąc, to nie widzę, by coś było tam takiego co coś tam blokuje.
No chyba, że to jednak nie my psujemy, czy jednak po wyłączeniu listy RODO/EI jest ok?

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/49746952-9f298500-fca2-11e8-8cd0-5be9e139e38f.png)


Chyba ten pop-up się nie pojawia po wycięciu rodo...

**Comment by krystian3w** [comment]
I jeszcze bazują na LocalStorage...

**Comment by lukjan32** [comment]
> @lukjan32 No chyba, że to jednak nie my psujemy, czy jednak po wyłączeniu listy RODO/EI jest ok?
tak, po wylaczeniu dziala. gdzie zglosic?

**Comment by lukjan32** [comment]
> Z tym obejściem, to nie wiem jak i co, bo tak szczerze mówiąc, to nie widzę, by coś było tam takiego co coś tam blokuje.
> @lukjan32 No chyba, że to jednak nie my psujemy, czy jednak po wyłączeniu listy RODO/EI jest ok?

tak, po wylaczeniu dziala. gdzie zglosic?
