### ISSUE TITLE
se.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10521]
https://sport.se.pl/sporty-walki/mma/poruszajace-wyznanie-mameda-khalidova-zdania-nie-zmienie-mam-problemy-aa-smYY-7R6v-7z1u.html

Włączone
![opera zdjecie_2018-12-06_150859_sport se pl](https://user-images.githubusercontent.com/36385327/49589195-0bd21600-f969-11e8-81c3-88721aa7f46a.png)
Wyłączone
![opera zdjecie_2018-12-06_150920_sport se pl](https://user-images.githubusercontent.com/36385327/49589196-0bd21600-f969-11e8-86af-458c41e9d829.png)

**Comment by krystian3w** [comment]
resztka po reklamie, ta zielona krecha i lekki odstęp od lewej przez nią...?

**Comment by krystian3w** [comment]
Wywalenie kreski w **uBO**/AdGuard:

```
sport.se.pl##.lead:after
```

**Comment by krystian3w** [comment]
Jak przeszkadzają ci nieprzewijające się już nawigacje, to **unsub** list polskich wewnętrznych i sobie ręcznie po "modułach" poza tym jednym przywróć.

**Comment by hawkeye116477** [comment]
@krystian3w Ale ta reguła działa też w ABP.

**Comment by krystian3w** [comment]
Nie mam Adblock Plus 2.0 by zrobić test ani Safari by zobaczyć w Adblock Plus 1.X.

**Comment by krystian3w** [comment]
`sport.se.pl#@#.socials`
`sport.se.pl#@#.video`

Jak odblokowujemy, to i trzeba do Fanboya zgłosić by SE sobie inaczej dociął nisz `##.socials`

@hawkeye116477  / @MajkiIT

**Comment by krystian3w** [comment]
@xxcriticxx   to możesz zamknąć, Fanboy naprawił wycinanie wideo w ciągu 3 dni jak pamiętam.
