### ISSUE TITLE
fn.org.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10534]
sociale ( na dole )

**Comment by krystian3w** [comment]
# 404 Not Found
> Not Found
> 
> The requested URL / was not found on this server.

Czekam na link, bo z pół roku temu dodawałem z kopii na web.archive i poprawiałem z 2 razy.

**Comment by xxcriticxx** [comment]
@krystian3w http://www.fn.org.pl/

**Comment by krystian3w** [comment]
A..., czyli się przesunęło o 1 do tyłu, coś po prostu było przed socialem i to usunęli.
