### ISSUE TITLE
tekstowo.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10558]
Na głównej tego niema ale w tekstach jest " nk " np; tu : https://www.tekstowo.pl/piosenka,moonshade,rise_of_the_damned.html

**Comment by krystian3w** [comment]
GG też wyciąć?

**Comment by krystian3w** [comment]
A tekst "poleć" nie ma uchwytu kompatybilnego z blokerami reklam, trzeba by skrypt do tampermonkey / violentmoneky / greasymonkey.

**Comment by blocker999** [comment]
GG chyba nie

**Comment by krystian3w** [comment]
No to poprawiłem i raczej nie będę w ulepszeniach CSS maskować tekstu "poleć" białym prostokątem.
