### ISSUE TITLE
cryptoqueen.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10557]
https://www.cryptoqueen.pl/blog/czy-etf-zmieni-rynek-bitcoin-a-tak-jak-to-zrobił-z-rynkiem-złota
![opera zdjecie_2018-12-09_151330_www cryptoqueen pl](https://user-images.githubusercontent.com/36385327/49698501-0a9d2500-fbc5-11e8-96c8-036bb763b201.png)

**Comment by krystian3w** [comment]
`social-blog.wix.com###post-social-actions`

Fajny kradziej 
`https://social-blog.wix.com/czy-etf-zmieni-rynek-bitcoin-a-tak-jak-to-zrobi%C5%82-z-rynkiem-z%C5%82ota`

**Comment by xMaap** [comment]
Link do tej strony nie działa.

**Comment by krystian3w** [comment]
Crytoqueen po prostu w iframe wyświetla obce blogi, ja bym to zgłosił do kad może?

@azet12

**Comment by krystian3w** [comment]
> 
> 
> Link do tej strony nie działa.

A bo ramka ma jakiś klucz w url i bez niego nie przechodzi, więc poprawiłem na ten najdłuższy z wszystkimi zmiennymi w url, bez ręcznego suwania nieistotnych atrybutów.
