### ISSUE TITLE
przegladsportowy.pl

### ISSUE THREAD

**Issue by Venom3x** [MajkiIT/polish-ads-filter#10554]
### Zrzut ekranu
https://i.imgur.com/Fiao3Mm.png

### Link bezpośredni
https://www.przegladsportowy.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
Wystarczy wejść na stronę główną.

### Moja konfiguracja
**Przeglądarka internetowa:** CHROME

**Rozszerzenia i skrypty:** uBlock Origin + Nano Defender

**Listy filtrów:**
1. EasyList
2. POL: polskie filtry do Adblocka i uBlocka
3. Polish Privacy Filters
4. Polskie Filtry RODO-Ciasteczkowe
5. NoCoin Filter List
6. Nano defender integration + Nano filters
7. Adblock Warning Removal List

**Comment by blocker999** [comment]
https://www.certyficate.it/polskie-filtry-anti-adblock-brak-wsparcia-w-polskich-filtrach-szanowni-nasi-drodzy-od-07-12-2018-nastapia-zmiany-w-oficjalnych-polskich-filtrach/
