### ISSUE TITLE
x-kom.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10567]
https://promocje.x-kom.pl/x-mas
![opera zdjecie_2018-12-09_224318_promocje x-kom pl](https://user-images.githubusercontent.com/36385327/49703328-e7459a80-fc03-11e8-90d4-7f873a108204.png)

https://promocje.al.to/swiateczne-inspiracje?cenaod=500&cenado=1000&filtry=16_dlakogo[134]+14_zainteresowania[140]
![opera zdjecie_2018-12-09_224408_promocje al to](https://user-images.githubusercontent.com/36385327/49703332-f6c4e380-fc03-11e8-9b80-bcb9512f679c.png)

**Comment by krystian3w** [comment]
Znowu jakieś zabawy w WP.

```
promocje.al.to,promocje.x-kom.pl##.eyIGFs.sc-bdVaJa.fkDSIs.sc-1xlbelh-0:nth-of-type(3) > .bBthTs.j4pwsa-4##.eyIGFs.sc-bdVaJa.fkDSIs.sc-1xlbelh-0:nth-of-type(3) > .bBthTs.j4pwsa-4
```

**Comment by hawkeye116477** [comment]
Już i tak po promocji :smile:.

**Comment by krystian3w** [comment]
To zakomentuj / wywal.
