### ISSUE TITLE
wsqn.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#10573]
Stylizujemy nagłówek czy zostawić taki dziwaczny:

![obraz](https://user-images.githubusercontent.com/35370833/49759981-8bdae180-fcc3-11e8-913c-474c6d12c15e.png) |
--- |

I gdzie usuwać tę linię CSS-em:

- Cookies
- Social
- RSS
- EI

... ja bym wrzucił do ciastek `suplement`, bo on zajmował większość paska.

**Comment by krystian3w** [comment]
O ile css nie będzie za długi, już widzę, że minimum 2 reguły musiałyby być.

**Comment by hawkeye116477** [comment]
`wsqn.pl##.social_bookmarks` to do RSS może być, kontakt się i tak powtarza, więc nie zaszkodzi
`wsqn.pl##.extralight-border:style(border: none !important;)` to też do RSS (supplement)

**Comment by krystian3w** [comment]
Szkoda, że RSS nie ma wersji suplement, doczekała się tylko polonizacji.

A nie chce uwalić @travis-ci.

**Comment by krystian3w** [comment]
`wsqn.pl#$#.extralight-border { border: none !important; }`

Jak na to reaguje `AdBlock` i `Adblock Plus`? style uwala że nie działa cała lista.

**Comment by hawkeye116477** [comment]
@krystian3w Spokojnie, zaraz dodamy, nie pędź tak :stuck_out_tongue:
