### ISSUE TITLE
fcinter.pl

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#1057]
Proszę zablokować reklamę pod adresem https://go2goal.com/ na stronie fcinter.pl (reklama występuje pod każdym newsem).
![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/16161598/b32c6bc4-34ce-11e6-85bd-5dfb04e10b57.PNG)

**Comment by MajkiIT** [comment]
nie widzę tego.

**Comment by F4z** [comment]
Ja widzę. `http://fcinter.pl/news/28606-vazquez-nie-dla-suning`

![image](https://cloud.githubusercontent.com/assets/11742596/16171351/f5e9d304-356c-11e6-8427-5330d13f5147.png)

**Comment by MajkiIT** [comment]
Ok dzięki.
