### ISSUE TITLE
totalcasino.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10582]
Nie działa rejestracja konta

**Comment by hawkeye116477** [comment]
@xMaap A to hazardzista :smiley:
Najwyraźniej bez akceptacji RODO nie wpuszczą, a więc w takim razie usuniemy to z listy, a dodamy akceptację do rozszerzenia.

**Comment by xMaap** [comment]
@hawkeye116477 jeśli chodzi o rozszerzenie to nie dałoby rady zrobić tak aby samo się aktualizowało? W Chrome i podobnych jest to męczarnia niż w Firefox.

**Comment by hawkeye116477** [comment]
@xMaap Wypróbuj skrypt do PowerShella, instrukcje masz na => `https://github.com/PolishFiltersTeam/PolishCookieConsent#ii-chromechromiumvivaldichroperacent-yandex`
