### ISSUE TITLE
Koniec Showmax - info

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10599]
https://www.spidersweb.pl/2018/12/showmax-polska-koniec.html

**Comment by blocker999** [comment]
@xxcriticxx Na pocieszenie powiem że g+ kończy : https://www.wirtualnemedia.pl/artykul/luka-w-google-koniec-serwisu-kwiecien-2018-dlaczego-jak-skopiowac-dane
marne bo marne ale pocieszenie

**Comment by krystian3w** [comment]
To ja chce off-topic zamiast to-do dla fraza.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/search?q=Showmax&unscoped_q=Showmax

https://github.com/MajkiIT/polish-ads-filter/blob/5a1f19d71b2af0bf9ee5a5e56b166d83188bee4d/adblock_social_filters/adblock_social_list.txt#L2204

https://github.com/MajkiIT/polish-ads-filter/blob/5a1f19d71b2af0bf9ee5a5e56b166d83188bee4d/cookies_filters/adblock_cookies.txt#L1338

https://github.com/MajkiIT/polish-ads-filter/blob/ac2192f371f23241c21f4def0a65dfbb0c8e0b19/polish-adblock-filters/adblock.txt#L2690

**Comment by xxcriticxx** [comment]
jest juz jakis nowy shit `https://pl.chili.com/`

**Comment by hawkeye116477** [comment]
`https://www.dobreprogramy.pl/showmax-polska-tvp-filmy-seriale,News,99045.html`

**Comment by krystian3w** [comment]
https://www.wirtualnemedia.pl/artykul/tvp-chce-kupic-showmax-byly-juz-pierwsze-kontakty-na-poziomie-zarzadu

**Comment by krystian3w** [comment]
Ale pewnie zmienią szablon html...
