### ISSUE TITLE
flightradar24.com

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#1060]
https://www.flightradar24.com/
Proszę zablokować `www.flightradar24.com###responsiveBottomPanel`

**Comment by MajkiIT** [comment]
nie widzę, niczego podejrzanego.

**Comment by adreporter** [comment]
![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/16172516/b82f8b20-358b-11e6-9453-061472850009.PNG)

**Comment by adreporter** [comment]
Powinienem przekazać niepolskie reklamy do EasyList. Przepraszam za spam.

**Comment by MajkiIT** [comment]
@adreporter ale nic się nie dzieje. Pisz śmiało.

**Comment by adreporter** [comment]
Teraz to chyba będę musiał tutaj pisać :smile: 
![lol2](https://cloud.githubusercontent.com/assets/18214146/16174059/0b7f1f5c-35b4-11e6-81d5-9b254b46cde5.PNG)

**Comment by MajkiIT** [comment]
Pisz śmiało. Będziemy coś kombinować. A czemu cie zbanowali?

**Comment by adreporter** [comment]
Dlatego że próbowałem się zarejestrować używając tymczasowego maila. Jak wyskoczyła wiadomość, że nie mogę, to podałem mojego "prawdziwego" maila i się zarejestrowałem. Aktywowałem konto i po jakich 3 godzinach ta informacja, że zostałem zbanowany. Napisałem do admina z prośbą o odbanowanie, ale wątpię że mi odpisze.
Na githubie się zarejestrowałem używając tymczasowego maila i nic się nie stało.
