### ISSUE TITLE
krotoszynska.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10613]
adblock 

jest to juz na liscie ?

**Comment by xxcriticxx** [comment]
RODO

test link:
https://krotoszynska.pl/pl/19_wiadomosci_z_regionu

**Comment by HateAds** [comment]
U mnie na chromie nie widze adblocka.

**Comment by xxcriticxx** [comment]
@HateAds tak

**Comment by krystian3w** [comment]
Rodo miga przez sekundę i raczej jak nie ma sieciowego wycinania, to nic się z tym ciekawszego raczej nie zrobi.

**Comment by HateAds** [comment]
@xxcriticxx Sprawdzałem jeszcze raz, u mnie adblock się nie pojawia.

**Comment by krystian3w** [comment]
PiHole troubles?

**Comment by xxcriticxx** [comment]
@krystian3w nope za duzo list pihole4ever

@HateAds dzieki za pomoc u mnie juz teraz tez ok

**Comment by krystian3w** [comment]
@xxcriticxx a to RODO jakoś docinać pod pihole bo z uBO znika po sekundzie przy pierwszych odwiedzinach i raczej trudno jak blokują przewijanie.

**Comment by krystian3w** [comment]
Nie przyglądałem się czy oni mają osobny plik, mam nadzieje, że filtr bez `:not(body):not(html)` będzie szybszy.

**Comment by xxcriticxx** [comment]
@krystian3w pihole nie wycina RODO

**Comment by hawkeye116477** [comment]
Te pihole to tylko hosts obsługuje, a więc tam raczej komunikatów nie wytniemy, bo byśmy musieli całe strony zablokować :smile:
