### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by Jakeeeeeeee** [MajkiIT/polish-ads-filter#10623]
![filmweb](https://user-images.githubusercontent.com/29839335/49972278-6c48f080-ff31-11e8-8f62-e97447c4d159.PNG)

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. nic
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**
chrome
**Rozszerzenia i skrypty:**
ublock
**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by MajkiIT** [comment]
https://www.certyficate.it/polskie-filtry-anti-adblock-brak-wsparcia-w-polskich-filtrach-szanowni-nasi-drodzy-od-07-12-2018-nastapia-zmiany-w-oficjalnych-polskich-filtrach/
