### ISSUE TITLE
cda-tv.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10638]
@MajkiIT regex please!

**Comment by MajkiIT** [comment]
@xxcriticxx A co jest nie tak?

**Comment by xxcriticxx** [comment]
@MajkiIT wedziesz na strone to zobaczysz

**Comment by MajkiIT** [comment]
@xxcriticxx U mnie te skrypty wyłapuje Easylist .

**Comment by xxcriticxx** [comment]
@MajkiIT u mnie cos nie lapie moment wyczyszcze cache

**Comment by xxcriticxx** [comment]
@MajkiIT ok po refreshu dziala

**Comment by MajkiIT** [comment]
@xxcriticxx Ok, super. Dziękuję za info

**Comment by xxcriticxx** [comment]
@MajkiIT zostalo 5 sec odlyczanie da rade cos zrobic? zmienic timer na 1 sec?

**Comment by MajkiIT** [comment]
Za 30 min zobaczę

**Comment by xxcriticxx** [comment]
@MajkiIT ok

**Comment by MajkiIT** [comment]
@xxcriticxx Na razie nic mądrego nie wynalazłem.

**Comment by xxcriticxx** [comment]
@MajkiIT no problem 

zamykam

**Comment by hawkeye116477** [comment]
Nano-setTimeout-booster.js albo coś w tym stylu może by pomogło, no chyba, że to jest po stronie serwera, wtedy przekichane.

**Comment by MajkiIT** [comment]
@F4z Pomożesz?

**Comment by MajkiIT** [comment]
@xxcriticxx https://github.com/MajkiIT/polish-ads-filter/commit/43121111565ca60da822a6228c94c995c15ba2c0#diff-ca815c4f5fe404637a9387f434740d25

**Comment by xxcriticxx** [comment]
@MajkiIT dziala thanks!
