### ISSUE TITLE
change.shop.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10640]
scrollujący fb

**Comment by krystian3w** [comment]
Nie button?

I czy to go wycina:

> Filtr statyczny `pl##.fb-messengermessageus` znajdujący się w:
> 
>  *   Polskie Filtry Elementów Irytujących

**Comment by hawkeye116477** [comment]
Jest tam jeszcze `change.shop.pl###box_facebooklike`
