### ISSUE TITLE
forum.optymalizacja.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10649]
cookies 

This website uses cookies to ensure you get the best experience on our website.

**Comment by krystian3w** [comment]
`forum.optymalizacja.com##.cc_banner-wrapper`

A zobaczysz ten drugi pod nim komunikat?

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/50047643-f8861f80-00b9-11e9-9d26-bebdae015c9d.png) |
--- |
