### ISSUE TITLE
Dwie niebezpieczne strony

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#1065]
Proszę zablokować te dwie niebezpieczne strony: http://cofe-super.top i http://dfh.abb.tagmetanext.com

**Comment by MajkiIT** [comment]
A co z tymi stronami jest nie tak?

**Comment by adreporter** [comment]
Te strony generują pliki exe jak np ściągam plik wideo. http://cofe-super.top pochodzi z tusfiles.net a http://dfh.abb.tagmetanext.com z datafilehost.com
