### ISSUE TITLE
pl.vpnmentor.com

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#10662]
`https://pl.vpnmentor.com/blog/najlepsze-najgorsze-blokery-reklam-aktualizacja-listopad/` [](https://github.com/MajkiIT/polish-ads-filter/issues/8780)

Nie działa menu zmiany języka już pomijam jakość bloga.

To się nie rozwija:

![obraz](https://user-images.githubusercontent.com/35370833/50049209-8c1e1700-00df-11e9-86f9-dba709cf6dfc.png) |
--- |

problem powoduje:

```
pl.vpnmentor.com#@#script:inject(abort-on-property-write.js, bioEp)
```

filtr autorstwa **`@`okiehsch** jako zastępczy:

```
pl.vpnmentor.com##+js(setTimeout-defuser.js, bioEp.showPopup)
```

dodany do **uBO Annoyance** pod wszystkie języki.

---

_Może podmiana na CSS:_

<details><summary> CSS </summary>

`pl.vpnmentor.com###bio_ep, #bio_ep_bg`
`pl.vpnmentor.com##body[style]:style(overflow: auto !important;)`

</details>

**Comment by krystian3w** [comment]
Jakby nie blokować pop-up VPN inaczej to można dźwignąć  okienko języka:

```
pl.vpnmentor.com##.header .language:hover .navbar-nav .dropdown-menustyle:(display: block !important; margin-top: 0 !important;)
```

**Comment by hawkeye116477** [comment]
Ta podmiana na CSS to nie pomoże, a dlatego, że ten popup pojawia się po pewnym czasie. A jeżeli chodzi o regułę `@okiehsch`, no to ona u mnie niestety też nie działa.

**Comment by hawkeye116477** [comment]
No chyba podmiana na CSS będzie najlepsza, bo i będzie działać w AG, wtedy zdaje się, że chyba to nie działało, ale teraz najwyraźniej jest ok.

**Comment by krystian3w** [comment]
Może nano adblocker blokował.
