### ISSUE TITLE
Literówki

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#10660]
https://github.com/MajkiIT/polish-ads-filter/blob/de3a710a2877fa9b2bd0aa9604a498359d6ed663/polish-adblock-filters/adblock.txt#L3945

`:ab-has(` -> `:-abp-has(`

https://github.com/MajkiIT/polish-ads-filter/blob/de3a710a2877fa9b2bd0aa9604a498359d6ed663/polish-adblock-filters/adblock.txt#L38

`domain=~arriva.pl,~budus.pl` -> `domain=~arriva.pl|~budus.pl`

**Comment by gwarser** [comment]
> `:ab-has(` -> `:-abp-has(`

Sorki, klawiatura mi nawala, w pierwszym brak `-` na początku:

`:abp-has(` -> `:-abp-has(`

**Comment by MajkiIT** [comment]
@gwarser Poprawione. Jeszcze raz dziękuję.
