### ISSUE TITLE
f.kafeteria.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10661]
https://f.kafeteria.pl/temat-7391689-szybka-i-niezawodna-pozyczka/
![opera zdjecie_2018-12-16_030252_f kafeteria pl](https://user-images.githubusercontent.com/36385327/50049198-4e20f300-00df-11e9-8b26-1d65e754fb79.png)

![opera zdjecie_2018-12-16_030306_f kafeteria pl](https://user-images.githubusercontent.com/36385327/50049199-4e20f300-00df-11e9-959a-26ea96957a28.png)

**Comment by krystian3w** [comment]
Ups wyszedł łosoś w opisie zmian - https://pl.wiktionary.org/wiki/laks
