### ISSUE TITLE
ifotos.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#10673]
> Na iFotos.pl nie ma irytujących, wielkich reklam i wyskakujących okien. Głównym zarobkiem(z którego utrzymywany jest serwer i wysokiej jakości działanie naszej witryny!) są reklamy, więc ładnie prosimy wyłącz Adblocka :-) [Jak to zrobić?]()

Dedykowana lista nie wycina komunikatu już (czy też nie oszukuje strony że reklamy niby się wyświetliły).

**Comment by MajkiIT** [comment]
`@@/advertisement.js$script,domain=ifotos.pl`

**Comment by MajkiIT** [comment]
Wysłane do @olegwukr
