### ISSUE TITLE
topz.pl

### ISSUE THREAD

**Issue by gaargulec** [MajkiIT/polish-ads-filter#10698]
ciasteczka

![ss324](https://user-images.githubusercontent.com/45939728/50089559-6c354300-0206-11e9-9949-26ed0edc4265.png)

<details not-open>
<summary>Komunikat występuje nawet przy włączonych poniższych dodatkowych listach (i jak coś to nie zgłaszam komunikatów, które występują po ich wyłączeniu, bo mnie one nie interesują):</summary>

- dodatek I don't care about cookies
- lista Fanboy’s Cookie List

</details>

**Comment by krystian3w** [comment]
U mnie domena jakby padła

**Comment by hawkeye116477** [comment]
Nawet wujek o nich nic nie wie, więc zakładam, że pewnie literówka się wkradła...
