### ISSUE TITLE
tv.kafeteria.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10692]
http://tv.kafeteria.pl/Kochani-rodzice-przyslijcie-pieniadze-Co-zrobic-gd-eYIWrRIcHSt
![opera zdjecie_2018-12-17_094112_tv kafeteria pl](https://user-images.githubusercontent.com/36385327/50075698-e8686000-01df-11e9-8f81-b846af5b2b0b.png)

**Comment by HateAds** [comment]
@MajkiIT 
Nie ładuje się video z włączonym pl filtrem 
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda​​​​​
![image](https://user-images.githubusercontent.com/29756590/50077623-29af3e80-01e5-11e9-850c-2dacf1b747a1.png)

**Comment by krystian3w** [comment]
może znowu jak z #10493

**Comment by MajkiIT** [comment]
@xMaap @krystian3w Ja nie mam filmu nawet jak wyłączę blocker... sprawdzicie?
`
@@/^https:\/\/[a-z]{2,14}\.wp\.pl\/[a-zA-Z0-9_-]{450,}/$script,domain=kafeteria.pl`

**Comment by krystian3w** [comment]
chętnie.

**Comment by krystian3w** [comment]
Działa, ale trzeba coś nowego na reklamy.

I może lepiej:

```
@@/^https:\/\/[a-z]{2,14}\.wp\.pl\/[a-zA-Z0-9_-]{450,}/$script,domain=tv.kafeteria.pl
```

Na głównej lub na forum nie mamy chyba problemów z wideo.

**Comment by xMaap** [comment]
@krystian3w również pojawia się reklama
![opera zdjecie_2018-12-18_053955_tv kafeteria pl](https://user-images.githubusercontent.com/36385327/50132418-63388600-0287-11e9-859b-3aa7386b9039.png)


Jeszcze tutaj
https://kosmetyki.kafeteria.pl
![opera zdjecie_2018-12-18_054039_kosmetyki kafeteria pl](https://user-images.githubusercontent.com/36385327/50132459-882cf900-0287-11e9-80b6-ec1efd90ee1c.png)

**Comment by MajkiIT** [comment]
@xMaap aktualizacja filtrów i sprawdź.

**Comment by HateAds** [comment]
@MajkiIT Wygląda na to, że po aktualizacji wszystko działa.

**Comment by krystian3w** [comment]
Dociąć te przyciski social czy nie używasz listy?
