### ISSUE TITLE
rozterkistartuperki.pl

### ISSUE THREAD

**Issue by gaargulec** [MajkiIT/polish-ads-filter#10717]
błąd w ciasteczkach, pusta biała strona, błąd występuje także na Fanboy’s Cookie List https://github.com/ryanbr/fanboy-adblock/issues/813

**Comment by krystian3w** [comment]
U mnie nie jest biała, tylko nie działa slider, ten pod nawigacją.

**Comment by krystian3w** [comment]
Błąd mam tylko z listą social obecnie, poprawię jak namierzę.

**Comment by krystian3w** [comment]
Jak patrzę to oba pliki wymagane:


```
https://rozterkistartuperki.pl/wp-content/themes/yeahthemes-sparkle/js/yt.custom.min.js?ver=1.0
```
```
https://rozterkistartuperki.pl/wp-content/themes/yeahthemes-sparkle/js/yt.script.min.js?ver=1.0
```

więc tylko dokleiłem `/yt.` do adresu skryptów w wyjątkach.
