### ISSUE TITLE
tvporno.pl + porno720.pl NSFW

### ISSUE THREAD

**Issue by gaargulec** [MajkiIT/polish-ads-filter#10712]
błąd w ciasteczkach występujący aż w 3 listach ciasteczkowych, pusta czarna strona: https://github.com/ryanbr/fanboy-adblock/issues/804

**Comment by krystian3w** [comment]
`porno720.pl,tvporno.pl#@##cookieinfo:not(body):not(html)`
`@@||porno720.pl/core/js/cookieinfo.js$script,domain=porno720.pl`
