### ISSUE TITLE
mojestronywww.pl

### ISSUE THREAD

**Issue by gaargulec** [MajkiIT/polish-ads-filter#10715]
~~błąd w ciasteczkach występujący aż w 3 listach ciasteczkowych, nie do końca wycięty komunikat: https://github.com/ryanbr/fanboy-adblock/issues/805~~

ciasteczka:

![ss365](https://user-images.githubusercontent.com/45939728/50105123-1a9faf00-022c-11e9-8d2e-c9e398293e35.png)

**Comment by hawkeye116477** [comment]
U nas to akurat wcale nie wycięty, więc nie ma błędu :smile:

**Comment by gaargulec** [comment]
Fakt, w takim razie zamieniam zgłoszenie na ciasteczka do usunięcia.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/8cf87d0b5566163b794e6552c16923a186b561a5/cookies_filters/adblock_cookies.txt#L1702

Zakomentowane, widać trudniejszy lub coś się na stronie blokuje (grafiki, filmy, przewijanie...).

**Comment by krystian3w** [comment]
zrobiony generyk wystarcza:
https://github.com/MajkiIT/polish-ads-filter/blob/8cf87d0b5566163b794e6552c16923a186b561a5/cookies_filters/adblock_cookies.txt#L2094
