### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10738]
@MajkiIT jakos TV pod te EPG zalatwisz?

**Comment by krystian3w** [comment]
:rofl: :man_facepalming:

**Comment by krystian3w** [comment]
![](https://github.githubassets.com/images/icons/emoji/unicode/1f923.png) ![](https://github.githubassets.com/images/icons/emoji/unicode/1f926-2642.png)

**Comment by MajkiIT** [comment]
@xxcriticxx proszę 
https://ufile.io/xbd8y

**Comment by xxcriticxx** [comment]
@MajkiIT 

Your input can't be opened:
VLC is unable to open the MRL 'http://145.239.206.198:25461/live/Paultaylor2/O7KaBkPHs5/15228.ts'. Check the log for details.

**Comment by xxcriticxx** [comment]
@MajkiIT z jakich serwisow te listy?

**Comment by MajkiIT** [comment]
@xxcriticxx Weź sprawdź tą 2 listę

**Comment by MajkiIT** [comment]
@xxcriticxx Dostałem do testów ..

**Comment by xxcriticxx** [comment]
@MajkiIT druga sam sport dziala 

sprawdzalem w vlc bo nie mam tutaj kodi

**Comment by xxcriticxx** [comment]
@MajkiIT skasowalem na wszelki wypadek zeby nie bylo dymu
