### ISSUE TITLE
parenting.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10755]
https://parenting.pl/z-bolem-glowy-do-neurologa-niekoniecznie
![opera zdjecie_2018-12-18_053311_parenting pl](https://user-images.githubusercontent.com/36385327/50132259-857dd400-0286-11e9-831a-208c40e14668.png)
![opera zdjecie_2018-12-18_053319_parenting pl](https://user-images.githubusercontent.com/36385327/50132260-857dd400-0286-11e9-85dc-ee6fac61eac1.png)
![opera zdjecie_2018-12-18_053334_parenting pl](https://user-images.githubusercontent.com/36385327/50132261-857dd400-0286-11e9-927f-eb77d8a83d32.png)

**Comment by krystian3w** [comment]
może filtrem pod money czy podobnym z matches-css?
