### ISSUE TITLE
a-o.ninja

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#10762]
MOVED

**Comment by krystian3w** [comment]
kompleksowo? masz error mx domain?

**Comment by MajkiIT** [comment]
![screenshot_2018-12-18 informacja](https://user-images.githubusercontent.com/11302675/50181544-fb2c8300-030c-11e9-82db-929c00651ea6.png)

**Comment by krystian3w** [comment]
A to jak sprzedadzą to można uznać za zakończone przenosiny.

**Comment by xxcriticxx** [comment]
```
- Usuń reklamy ze strony, to proste: https://anime-odcinki.pl/reklamy-paypal.html TERAZ PROMOCJA!
- Ogłaszamy rekrutację na stanowiska tłumaczy i korektorów.
#20 Anime Express News [19.11-30.11] - poznaj najważniejsze newsy ze Świata anime
- Niektóre odtwarzacze mogą posiadać reklamy przeznaczone dla osób dorosłych, nie są to reklamy nasze, a właścicieli tych hostingów wideo.
```

**Comment by krystian3w** [comment]
Może wykupimy ich domenę?

**Comment by xxcriticxx** [comment]
@MajkiIT do ciebie machala 

![capture](https://user-images.githubusercontent.com/15007183/50182679-fdc3b400-02dd-11e9-8c26-a531ef201ec4.PNG)

**Comment by krystian3w** [comment]
To w sumie tylko w filtrach reklamowych i antyreklamowych by trzeba poprawić, za raz zobaczę czy strona zmarła ma jakiś pasek cookies.

**Comment by xxcriticxx** [comment]
w kolejności od lewej do prawej mamy @MajkiIT @hawkeye116477 @krystian3w 
![capture](https://user-images.githubusercontent.com/15007183/50182931-a7a34080-02de-11e9-9346-e5ab53ac2a16.PNG)

**Comment by krystian3w** [comment]
W uBO mają coś na wycofaną z 3 miesiące temu komparkę i obecnie nie widzę filtra na reklamy w jakieś subdomenie `kitsune-subs.a-o.ninja`

**Comment by MajkiIT** [comment]
@xxcriticxx kurde i te serduszka .... a skąd wiesz, że to do mnie ?

**Comment by hawkeye116477** [comment]
A co to jakieś requesty do `pushwhy.com`?

**Comment by xxcriticxx** [comment]
@hawkeye116477 się zaczęło zaraz regex bendzie potrzebny

**Comment by hawkeye116477** [comment]
Tak w zasadzie, to po aktualizacji uBO Filters już to się nie pojawia, ale byłem ciekaw do czego im to służy :smile:

**Comment by xxcriticxx** [comment]
push notifications

**Comment by krystian3w** [comment]
@hawkeye116477  a mają oni jeszcze `sw.js` czy tylko jak ustalili w uAsset brzydkim liniowym skryptem?

**Comment by hawkeye116477** [comment]
@krystian3w Nie mają `sw.js`, a więc tylko dla uBO można poblokować, zresztą w przeglądarce też to można wyłączyć :smile:.
