### ISSUE TITLE
Press Polska i inni

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#10776]
`aip24.pl,blog.ekstraklasa.net,budzetalert.pl,demaskator24.pl,dziennikbaltycki.pl,dzienniklodzki.pl,dziennikpolski24.pl,dziennikzachodni.pl,e-budownictwo.pl,e-dach.pl,e-instalacje.pl,e-izolacje.pl,e-lazienki.pl,e-mieszkanie.pl,e-ogrodek.pl,e-okna.pl,e-sciany.pl,echodnia.eu,ekstramagazyn.pl,expressbydgoski.pl,expressilustrowany.pl,forumbudowlane.pl,forumogrodowe.pl,gazetakrakowska.pl,gazetalubuska.pl,gazetawroclawska.pl,gk24.pl,glos.tv,gloswielkopolski.pl,gol24.pl,gp24.pl,gra.pl,gratka.pl,gs24.pl,juniorfutbol.pl,kurierlubelski.pl,miastakobiet.pl,motofakty.pl,naszahistoria.pl,naszekomunikaty.pl,naszemiasto.pl,nekrologi.net,nowiny24.pl,nowosci.com.pl,nto.pl,polskapress.pl,polskatimes.pl,pomorska.pl,poranny.pl,pracapolska.eu,prasa24.pl,regiodom.pl,sportowy24.pl,strefaagro.pl,strefabiznesu.pl,stronakobiet.pl,telemagazyn.pl,to.com.pl,tygodnikits.pl,urzadzone.pl,wider.pl,widerkontext.pl,widermobile.pl,wspolczesna.pl`

ekstramagazyn.pl - mignęło mi cookies.

**Comment by xxcriticxx** [comment]
`ekstramagazyn.pl` mam RODO

**Comment by krystian3w** [comment]
Głównie chodziło mi o cookies, olek antyadblocka chyba ogarnął.

**Comment by hawkeye116477** [comment]
@krystian3w No to nie trzeba pisać, tylko od razu działaćj jak coś :smile:.

**Comment by krystian3w** [comment]
Za dużo tych domen z ich pliku na anty-adblock a też nie wpiszę wszystkich pod "`###cross-dialog`".

**Comment by xxcriticxx** [comment]
na `wspolczesna.pl` mam adblock 

![capture](https://user-images.githubusercontent.com/15007183/50352930-ace9d080-0514-11e9-991e-ddc03c479418.PNG)

**Comment by HateAds** [comment]
@xxcriticxx Potwierdzam. Też mam adblocka. na wspolczena.pl

**Comment by hawkeye116477** [comment]
@MajkiIT Reklama dla ciebie na `gra.pl`

**Comment by xxcriticxx** [comment]
@hawkeye116477 no comments

**Comment by krystian3w** [comment]
Ja tam tej wsi bab nie widzę w domenach :sunglasses:  :eyeglasses:.

**Comment by hawkeye116477** [comment]
@krystian3w Jest, tylko zrobiłem literówkę, bo nie miasto, a miasta :smile:
