### ISSUE TITLE
ogrodnik-amator.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10775]
fb w artykułach ( po prawo ) np tu : http://ogrodnik-amator.pl/krzewy.php

**Comment by krystian3w** [comment]
`##a[href="http://www.facebook.com/pages/ogrodnik-amatorpl/459365410789108"]`

**Comment by blocker999** [comment]
href odpada bo zablokujesz całkowicie fb a chodzi by zablokować odnośnik na stronie, dlatego proponuje : `##[src="facebook_ogrodnik.jpg"]`
