### ISSUE TITLE
xlomza.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#10777]
### Link bezpośredni
`https://xlomza.pl/wiadomosci/10508-park-handlowy-zawadzka-vis-a-vis-galerii-veneda-juz-niebawem-foto/`

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Jakiś łobuziak schował zdjęcie centrum handlowego :smile:
Problemem jest ta reguła => `xlomza.pl##A > IMG[src^="/site/assets/files/"]`, a więc na reklamy trzeba będzie coś innego wykombinować :smile:.

**Comment by krystian3w** [comment]
raczej kiedyś mieli tam same reklamy :rofl:

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/4718

**Comment by MajkiIT** [comment]
@hawkeye116477 Dziękuję

**Comment by hawkeye116477** [comment]
@MajkiIT A reklamy im darujesz :smile:?

**Comment by krystian3w** [comment]
Chyba wewnętrzne, więc Mati.

**Comment by hawkeye116477** [comment]
@krystian3w No co ty, jak one są z innych stron, musicton, osk i fabrykavideo.
