### ISSUE TITLE
prezi.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10787]
cookies

**Comment by krystian3w** [comment]
dalej od 2012 brak polskiego i raczej wciąż prym wiodą PowerPointy.

**Comment by blocker999** [comment]
Artykuły są po Polsku np to : https://prezi.com/lhbmrzqrsizf/zwyczaje-bozonarodzeniowe-w-azji/
chodż niewiem czy to się klasyfikuje

**Comment by krystian3w** [comment]
Ja tam nie mam komunikatu, a na pewno mam wyłączone AdGuard Annoyance a z fanboy'a tylko social (nie cookie list / annoyance). 

A polski jest, bo ktoś z Polski wrzucił po polsku.

**Comment by hawkeye116477** [comment]
Tam nie ma artykułów, są tylko prezentacje... Za bardzo to on u nas w kraju chyba nie jest popularny, ale trochę o nim dyskutują, więc może jednak zrobimy wyjątek.

**Comment by krystian3w** [comment]
Ale ty musisz zrobić filtr, ja nie widzę paska cookies / pop-up GDPR.

Może kiedyś prezi dodadzą do książek, ale wątpię - bardziej w gestii nauczyciela XXI wieku.
