### ISSUE TITLE
globalne-archiwum.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#10794]
pusta sekcja reklama po prawej
pusta sekcja fb po prawej

**Comment by krystian3w** [comment]
`###text-60` - chyba trzeba lepiej wykrywać div po reklamie.

![image](https://user-images.githubusercontent.com/35370833/50472764-6c79cf00-09ba-11e9-8ee8-11517ae502b0.png) |
--- |

**Comment by krystian3w** [comment]
A social wycięty: 
https://github.com/MajkiIT/polish-ads-filter/blob/feb923de98dd5f0359168a8b20d8b7ce7f4d8f69/adblock_social_filters/adblock_social_list.txt#L1300
