### ISSUE TITLE
przegladpiaseczynski.pl

### ISSUE THREAD

**Issue by gargamelloss** [MajkiIT/polish-ads-filter#10816]
błąd w:
- POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
- Adguard base Filters

po kilku sekundach znika przewijanie po prawej:

![ss_338](https://user-images.githubusercontent.com/46057196/50377324-98dcc680-061b-11e9-83ff-607b3571f87a.png)

po wyłączeniu obu list wyskakuje komunikat:

![ss_340](https://user-images.githubusercontent.com/46057196/50377334-c6297480-061b-11e9-87dd-711d12feae1d.png)

po zaakceptowaniu komunikatu przewijanie nie znika:

![ss_341](https://user-images.githubusercontent.com/46057196/50377338-d80b1780-061b-11e9-9d01-a099775664ba.png)

**Comment by krystian3w** [comment]
@F4z  / @adamwr

**Comment by krystian3w** [comment]
@MajkiIT  u nas chyba też by trzeba dodać dla uBO odblokowanie przewijania i przemyśleć czy warto dodać wyjątek (pop-up tylko przy pierwszych odwiedzinach).

`przegladpiaseczynski.pl###html[class].wppas-model-open:style(overflow: visible!important;)`
