### ISSUE TITLE
mega.nz

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1084]
Ta reguła `##[class$="-ads"]` ukrywa zawartość strony tutaj - `https://mega.nz/#!nJIRXSDY!XuEM-SQvto56lldRZ9HH_iCO36KPdXlmWCwpN7wpF0k`

**Comment by xxcriticxx** [comment]
umnie jest ok 

nie piratuj win10 adam

**Comment by F4z** [comment]
Dziwne, u mnie w trzech przeglądarkach i na dwóch różnych komputerach jest ukryta treść.
Może masz zainstalowane rozszerzenie do Mega, jeśli tak, to wtedy uBlock nie filtruje tam treści.
Albo może nie masz najnowszej wersji filtrów, bo ta reguła została dodana wczoraj.

A odnośnie Win10, to był tylko przykład :stuck_out_tongue_closed_eyes:

**Comment by xxcriticxx** [comment]
v.2016061701 aktualizacja: ptk, 17 czerwca 2016, 13:20:00

zaraz zrobie test ponownie

**Comment by xxcriticxx** [comment]
dokladnie teraz jusz blokuje
