### ISSUE TITLE
tapeciarnia.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10846]
cookies oraz nieidzie pobrać żadnej tapety bo serwis wykrył adblocka

**Comment by MajkiIT** [comment]
@hawkeye116477 masz to?

**Comment by hawkeye116477** [comment]
@MajkiIT Tak

**Comment by MajkiIT** [comment]
@hawkeye116477 Ok dziękuję.

```
www.tapeciarnia.pl###reklama_pod_gorne_menu
www.tapeciarnia.pl##.thumb > table > tbody > tr > td  > div
```

**Comment by krystian3w** [comment]
`###div_info_cookies` ?

**Comment by krystian3w** [comment]
Jak dla mnie anti-adblock nie pokonany, dalej się nie da pobrać.

**Comment by krystian3w** [comment]
@hawkeye116477 ten filtr dalej istnieje w polskich filtrach: 

`tapeciarnia.pl#?#div[style*="text-align:center;"]:-abp-contains(REKLAMA)`


Bo @MajkiIT  słucha `gomoku` i dodał filtr, który nie ma racji bytu w ABP 3.9.5 i AdBlock 4.21.0: https://github.com/MajkiIT/polish-ads-filter/commit/cb568bd8179ea39b81d197c67b90e19626638ee9#diff-711027ed0794992ae3b8710d874f3df7R4742
