### ISSUE TITLE
odkryjpomorze.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10850]
fb ( ugóry ) oraz cookies

**Comment by krystian3w** [comment]
Social trudny do wycięcia...

Cookies prostsze:

`##.rounded.cookie_info`

**Comment by krystian3w** [comment]
W socialu mogę zablokować klikalność a grafikę mają zobacz jaką:

---

`##div.span6:nth-of-type(2) > map > area:nth-of-type(1)`
