### ISSUE TITLE
fastwhitecat.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10867]
za duzo wycinamy

**Comment by krystian3w** [comment]
Nie prawda...

EasyList Privacy psuje filtrem: -google-tag-manager/$script

```
-google-tag-manager/$script,badfilter
```

i już w uBO rusza.

**Comment by krystian3w** [comment]
czas |   | filtr | typ akcji filtru | typ pliku | link
-- | -- | -- | -- | -- | --
15:09:52 |   | `-google-tag-manager/$script` | -- | script | `https://fastwhitecat.com/wp-content/plugins/duracelltomi-google-tag-manager/js/gtm4wp-form-move-tracker.js?ver=1.8.1`
15:09:52 |   | `-google-tag-manager/$script` | -- | script | `https://fastwhitecat.com/wp-content/plugins/duracelltomi-google-tag-manager/js/gtm4wp-contact-form-7-tracker.js?ver=1.8.1`
15:09:52 |   | `-google-tag-manager/$script` | -- | script | `https://fastwhitecat.com/wp-content/plugins/duracelltomi-google-tag-manager/js/gtm4wp-email-link-tracker.js?ver=1.8.1`
15:09:52 |   | `-google-tag-manager/$script` | -- | script | `https://fastwhitecat.com/wp-content/plugins/duracelltomi-google-tag-manager/js/gtm4wp-download-tracker.js?ver=1.8.1`

Jakieś widać są wymagane.

**Comment by krystian3w** [comment]
`@@||fastwhitecat.com/wp-content/plugins/duracelltomi-google-tag-manager/js/gtm4wp-download-tracker.js`

ten wygląda na wymagany - @MajkiIT / @olegwukr  na jaką listę skoro winny EasyPrivacy chyba, że na obie.

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję
