### ISSUE TITLE
winicjatywa.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#10863]
cookies

**Comment by krystian3w** [comment]
Niestety pomieszane ze zgodą 18+

@xxcriticxx  było już poruszane w jakimś zaginionym zgłoszeniu garamela że takiego domyślnie nie wycinamy - podobnie jak niby newsletter rodo/ciasteczkowy tylko w newsletterach (jak dla mnie to są dalej zgody pod newsletter jakie dawniej były w porządnych newsletterach).
