### ISSUE TITLE
Życzenia 

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#10861]
@krystian3w @KonoromiHimaries @F4z @xxcriticxx @HateAds @blocker999 @xMaap @kasper93 @hawkeye116477

Życzę Wam spokojnych Świąt oraz abyście wypoczęli. Dodatkowo dziękuję za wszelką pomoc i wsparcie przy tworzeniu filtrów.

**Comment by gzenio22** [comment]
wesolych swiat

**Comment by hawkeye116477** [comment]
@MajkiIT A dla mnie nic? Nieładnie :stuck_out_tongue: 
Życzę wszystkim Wesołych Świąt Bożego Narodzenia i szczęśliwego Nowego Roku :smile: !

**Comment by xxcriticxx** [comment]
@hawkeye116477 dla ciebie rózga od Mikołaja nie zasłużyłeś wtym roku

**Comment by HateAds** [comment]
@MajkiIT Również Tobie życzę wesołych świąt.
Chciałem też Tobie podziękować i innym użytkownikom za pracę którą wkładacie w zwalczaniu reklam.

**Comment by F4z** [comment]
Wesołych Świąt.

**Comment by AarmsS** [comment]
Wesołych Świąt :)

**Comment by xxcriticxx** [comment]
@hawkeye116477 dodalem ciebie to pierwszego postu @MajkiIT

**Comment by hawkeye116477** [comment]
@MajkiIT Ok, wybaczam :smile:

**Comment by xxcriticxx** [comment]
happy new year!

**Comment by xMaap** [comment]
@MajkiIT nawzajem i obyś nie stracił chęci nad rozwojem filtrów.
