### ISSUE TITLE
About Karolina Hirth

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1087]
Zdjęcie Profilowe nie jest moje i jak komuś się to nie podoba, to może opuścić mój profil i zapomnieć o mnie. Jestem osobą transseksualną, zatem jak komuś to przeszkadza, to wie co ma zrobić (odejść z mojego życia)

A jak ktoś chce poznać mnie, oto trochę o mnie :)

Romantyczna i zbuntowana. Szalona i wrażliwa dziewczyna z pomorza. Pełna pasji i wizji idealistka. Jestem pełna sprzeczności i paradoksów, jestem silna psychicznie i wiele przeszłam, ale i wrażliwa, delikatna i łatwo mnie zranić. Bywam twarda i konsekwentna, jako liderka. Ale empatyczna i emocjonalna, jako kobieta. Mam duszę artystyczną, filozoficzną i pisarską. Ludzie co mnie znają, mówią, że jestem promykiem słońca, aniołem życia, zatem jestem raczej pozytywną osobą, choć mam temperament, dzięki któremu poruszam ciężkie i kontrowersyjne tematy, o których dużo napiszę w mojej książce.

**Comment by MajkiIT** [comment]
??

**Comment by xxcriticxx** [comment]
laska z fb co pisala o alltube.tv
