### ISSUE TITLE
haxmaps.com

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#1089]
reklamy

**Comment by xxcriticxx** [comment]
strona jest nie polska

**Comment by F4z** [comment]
Ta reguła powinna zablokować reklamy:
`||p1pa.com^$script,domain=haxmaps.com`
a ta wyskakujące okienka:
`||haxmaps.com/js/cb.js$xmlhttprequest`

**Comment by adreporter** [comment]
@xxcriticxx Wiem. Przeczytaj tu https://github.com/MajkiIT/polish-ads-filter/issues/1060

**Comment by xxcriticxx** [comment]
ok czytam i dalej nie rozumiem

**Comment by MajkiIT** [comment]
@F4z dzięki
@adreporter głosiłem do Easylist. Mają dodać.

**Comment by adreporter** [comment]
Znowu są reklamy i wyskakujące okna. Mógłbyś zgłosić?

**Comment by MajkiIT** [comment]
Ok zerknę dzisiaj.

**Comment by adreporter** [comment]
Reklamy wyskakują i się pojawiają jak klikniesz gdziekolwiek na stronie.

**Comment by MajkiIT** [comment]
Wysłałem poprawkę do Easylist.
