### ISSUE TITLE
dieta.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10910]
cookies

**Comment by krystian3w** [comment]
@hawkeye116477  - w Firefox nie mam, sprawdzisz kiedyś w Vivaldi?

**Comment by krystian3w** [comment]
`dieta.pl##.cookies__std`

https://github.com/MajkiIT/polish-ads-filter/blob/2a227bd2673604373a3ca794d7e9045dd212cc57/cookies_filters/adblock_cookies.txt#L337

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/d46f65a5aea2cb027a3d33ef09d3e15f3e22ae0a - źródło.
