### ISSUE TITLE
lunaticfiles.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#10920]
AA

**Comment by xxcriticxx** [comment]
@KonoromiHimaries ?

**Comment by krystian3w** [comment]
Anty Adblock...

**Comment by krystian3w** [comment]
`https://lunaticfiles.com/aiabze5c8xle/owca.png.html`

**Comment by krystian3w** [comment]
@olegwukr:

```
@@||lunaticfiles.com/ads.js$script,first-party
lunaticfiles.com#@#.adsbox
```

I nie stwierdziłem by wykrywali:

`lunaticfiles.com#@#.ad`
`lunaticfiles.com#@#.ads`

Może to pod AdGuard Base lub nie wiem co...

**Comment by krystian3w** [comment]
@olegwukr:

```
@@||lunaticfiles.com/ads.js$script
lunaticfiles.com#@#.adsbox
```

---

I nie stwierdziłem by wykrywali:

`##.ad`
`##.ads`

A więc dodatkowe wyjątki zbędne: 

`lunaticfiles.com#@#.ad`
`lunaticfiles.com#@#.ads`

Może to pod AdGuard Base lub nie wiem co...

**Comment by krystian3w** [comment]
@MajkiIT  tak jak myślałem `@@/js/ads.js` nic nie daje

**Comment by krystian3w** [comment]
musi być `@@||lunaticfiles.com/ads.js$script` lub:

`@@/ads.js$script,domain=lunaticfiles.com`

FYI @MajkiIT / @olegwukr
