### ISSUE TITLE
dziennikzachodni.pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#10935]
Witam czy mógł ktoś to naprawić.Widzę informacje o posiadaniu wałczonego ubloka.

https://dziennikzachodni.pl/

Z góry dzięki.

**Comment by MajkiIT** [comment]
https://www.certyficate.it/polskie-filtry-anti-adblock-brak-wsparcia-w-polskich-filtrach-szanowni-nasi-drodzy-od-07-12-2018-nastapia-zmiany-w-oficjalnych-polskich-filtrach/
