### ISSUE TITLE
gustaf.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#10945]
" like " w ofertach, np tu : http://gustaf.pl/opis/3362151/nokia-6235--bl-6c-1100mah-407wh-li-ion-37v-cameron-sino.html

**Comment by krystian3w** [comment]
na dev w szablonach już wycinam sieciowo, niestety coś padło i mamy `[detached HEAD ...] Update sections of ... [ci skip]`
