### ISSUE TITLE
naekranie.pl

### ISSUE THREAD

**Issue by d21d3q** [MajkiIT/polish-ads-filter#10968]
Prawidłowo wycięty jest modal z informacją o polityce prywatności, jednak zostaje `reveal-modal-bg`, który przyciemnia całą stronę.

### Link bezpośredni
naekranie.pl

### Moja konfiguracja
Firefox, ublock

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Fanboy's Cookie List
4. Fanboy’s Annoyance List

**Comment by krystian3w** [comment]
Zgaduje, że jak nie ma literówki w tym:

https://github.com/MajkiIT/polish-ads-filter/blob/ed278efc7792d928de107e6a62be1e7850c9445b/cookies_filters/adblock_cookies.txt#L45

To u Fanboya jest jakiś wyjątek że filtr samodzielnie nie działa.

**Comment by d21d3q** [comment]
Oj, chochlik w konfiguracji... (to dotyczyło innego zestawu filtrów)
jednak działa.

**Comment by krystian3w** [comment]
@d21d3q   ale mimo to dzięki za zgłoszenie zrobiłem korektę w wyjątkach pod ABP/AdBlock - `vod.naekranie.pl`, była konieczna po tym jak połączyłem w jedno filtry `.reveal-modal-bg` / `.modal-backdrop`.
