### ISSUE TITLE
tvzafree.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1097]
Reklamy + adblock - `http://tvzafree.pl/euro1/`
![image](https://cloud.githubusercontent.com/assets/11742596/16378161/7ff03490-3c6a-11e6-94fd-b9d01ab10898.png)
![image](https://cloud.githubusercontent.com/assets/11742596/16378166/8ba890e8-3c6a-11e6-9617-c8440cdf7c28.png)

Żeby nie wykrywało adblocka:
`tvzafree.pl#@##adsense`
Żeby zablokować reklamy:
`||rect.b2bpersonals.net^`

**Comment by MajkiIT** [comment]
Dodane. Dzięki.

**Comment by MajkiIT** [comment]
strona już nie działa.

**Comment by F4z** [comment]
No cóż, zdarza się :stuck_out_tongue_winking_eye:
Może to chwilowe, a jeśli nie, to będzie można usunąć tę regułę `tvzafree.pl#@##adsense`, bo wydaje mi się, że ta druga reguła może być przydatna też na innych stronach.

**Comment by MajkiIT** [comment]
wiem wiem. Damy radę. Nie robię niczego pochopnie. Poczekajmy zobaczymy co się będzie dziać.
