### ISSUE TITLE
multi Cookies

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#10986]
http://settlersonlinewiki.eu/
https://www.logitech.com/pl-pl
https://www.nvidia.pl/Download/index.aspx?lang=pl
https://www.wd.com/pl-pl/products/internal-storage/wd-red.html
https://www.wiocha.pl/
https://www.hopaj.pl/
http://www.wisla.krakow.pl/pl/

**Comment by krystian3w** [comment]
Uruchomiłem takie coś:

```
||consent.trust*.com/notice?domain=$script,domain=addthis.com|adidas.pl|ea.com|ibm.com|java.com|nespresso.com|oracle.com|origin.com|reebok.pl|wd.com|weather.com|wunderground.com
```

i wyłączyłem wycinanie filtrami kosmetycznymi na tych domenach.

**Comment by hawkeye116477** [comment]
No ciekawe tylko czy czegoś nie popsuje.

**Comment by krystian3w** [comment]
Ale jakby oni trzymali dane na serwerach truste? Po co? Takie lamy webmasterskie z nich że logowania do sklepu nie umieją zrobić?
