### ISSUE TITLE
chip.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#10988]
https://www.chip.pl/2019/01/dell-opatentowal-laptopa-z-dwoma-ekranami/
Napis reklama
![opera zdjecie_2019-01-06_142756_www chip pl](https://user-images.githubusercontent.com/36385327/50736568-555b8e00-11bf-11e9-86f6-9a17229a5b8d.png)

**Comment by krystian3w** [comment]
`##.widget_banner`
