### ISSUE TITLE
wylecz.to

### ISSUE THREAD

**Issue by DRHAshino** [MajkiIT/polish-ads-filter#10989]
Serdeczne gratulacje....

![image](https://user-images.githubusercontent.com/44258023/50738687-513b6a80-11d7-11e9-859d-ee225bbed2c5.png)

**Comment by xxcriticxx** [comment]
@DRHAshino jakis link please main page dziala bez problemu 

@krystian3w / @hawkeye116477 rodo sie pokazalo znowu

**Comment by hawkeye116477** [comment]
@xxcriticxx Rozszerzenie Polska Ciasteczkowa Zgoda zainstaluj :smile:.
A u mnie jest popsute, problemem jest reguła `wylecz.to##.display_detect`.

**Comment by MajkiIT** [comment]
@hawkeye116477 bo dziwnym trafem podmienili kod strony, aby ukurat coś psuło.

**Comment by xxcriticxx** [comment]
@MajkiIT dzieki za szybki fix!

**Comment by DRHAshino** [comment]
> @hawkeye116477 bo dziwnym trafem podmienili kod strony, aby ukurat coś psuło.

Nikt nic nie podmieniał.  .display_detect obsługuje lazy loader do obrazków (wszystkich) ... 

> @xxcriticxx Rozszerzenie Polska Ciasteczkowa Zgoda zainstaluj 😄.
> Jak za wolno idzie, to ewentualnie można by zrobić ciastko rodoHfM z wartością „true", pewnie wyjdzie na to samo co klik.

Zgadzam się z przedmówcą ... ;)

Miłego wieczoru panowie.
