### ISSUE TITLE
m.poczta.gazeta.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#10995]
**strona:**

`https://m.poczta.gazeta.pl/index.html#szczegoly,251815807`

**Problem:**

Resztka po reklamie

**Zrzut ekranu:**

![obraz](https://user-images.githubusercontent.com/35370833/50780716-f6bc1000-12a3-11e9-952b-6b5ae3275d05.png) |
--- |

**filtr:**

```
m.poczta.gazeta.pl###readmailGazetaAdvert-layer
```

lub

```
m.poczta.gazeta.pl###.readmailGazetaAdvert
```

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję
