### ISSUE TITLE
lubelska.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#11]
http://lubelska.pl/

cookies

KOMUNIKAT

Nasza witryna stosuje pliki "Cookies". W celu świadczenia usług na najwyższym poziomie, w tym w sposób dostosowany do indywidualnych potrzeb naszych użytkowników stosujemy narzędzia do zbierania danych. W każdym czasie można dokonać zmiany ustawień dotyczących tych narzędzi.
Więcej szczegółów w "Polityce Prywatności".

**Comment by MajkiIT** [comment]
Zaktualizuj filtry.
