### ISSUE TITLE
creepycorn.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11016]
social na środku + po lewej social widżet albo raczej jego resztki

![ss396](https://user-images.githubusercontent.com/46375428/50969930-34a57800-14e0-11e9-8fe7-d4b11604e4a3.png)

**Comment by krystian3w** [comment]
z lewej też, nie używaj AdGuard Annoyance jak chcesz uzupełnić polską o braki.

**Comment by garrgul** [comment]
> krystian3w: z lewej też 

Racja, zwyczajnie przegapiłem, odświeżyłem screenshoota w pierwszym komentarzu.

> krystian3w : nie używaj AdGuard Annoyance jak chcesz uzupełnić polską o braki.

Bez obaw, nie używam do zgłaszania sociali ani Adguard Annoyance ani Fanboy Annoyance, używam kombo: Fanboy’s Social + Polskie Social.
