### ISSUE TITLE
jarek-kefir.org

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#11013]
puste kontenery po reklamie na dole w footer strony jest info o RODO

**Comment by garrgul** [comment]
po prawej social:

![ss388](https://user-images.githubusercontent.com/46375428/50967506-9c57c500-14d8-11e9-9423-174d2a5fce5f.png)

**Comment by krystian3w** [comment]
> footer strony jest info o RODO

link do wpisu, linków nie wycinamy, nie nasza wina że on ma plugin "infinity footer" i jest przypięta do dołu okna strony.

**Comment by krystian3w** [comment]
> po prawej social:

`jarek-kefir.org##.sidebar-main.col-sidebar > #media_image-61`

mam nadzieje że wytnie tylko ten jeden element i nie ma on zmiennych ID.
