### ISSUE TITLE
pafere.org

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11019]
social po prawej na dole

![ss395](https://user-images.githubusercontent.com/46375428/50969130-a92ae780-14dd-11e9-96ba-e0beed45f6d6.png)

**Comment by krystian3w** [comment]
`##.td_block_template_13:nth-of-type(n+4):nth-of-type(-n+6) > .td_single_image_bg`

filter może być kwestią **s<ins>porną</ins>**.
