### ISSUE TITLE
kierunekchorwacja.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11022]
social po lewej w połowie strony

![ss400](https://user-images.githubusercontent.com/46375428/50969803-e42e1a80-14df-11e9-9377-41f9b8f223dd.png)

**Comment by krystian3w** [comment]
i jakaś reklama pod `##.third-col__advert`

**Comment by krystian3w** [comment]
@MajkiIT  dalej jest kwadrat pomarańczowy :tangerine:  po reklamie.
