### ISSUE TITLE
motopodhale.info

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11021]
reklama po prawej

![ss399](https://user-images.githubusercontent.com/46375428/50969717-9ca78e80-14df-11e9-8773-9715583dd634.png)

**Comment by krystian3w** [comment]
I na "środku" resztka po reklamach Google.

![image](https://user-images.githubusercontent.com/35370833/50969852-ff992580-14df-11e9-805c-21d9bbbfd204.png) |
--- |

**Comment by garrgul** [comment]
Tu jest reklama a nie social.
