### ISSUE TITLE
beskidy.news

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11049]
social widżet po lewej scrollujący

![ss430](https://user-images.githubusercontent.com/46375428/50972283-86e99780-14e6-11e9-8ed7-e480ba4a6073.png)

**Comment by krystian3w** [comment]
@MajkiIT  i reklama jak wjadę na zakładkę w czarnej nawigacji: 

`##.js-promo-slide.c-promo-slide` 
`##.o-promo--b.o-promo--center.o-promo`

![image](https://user-images.githubusercontent.com/35370833/51020940-59e9c300-1580-11e9-956b-7699a7dcd516.png) |
--- |

I dodatkowo ona psuje czytanie strony, bo u mnie nie umie się wyłączyć przy przewijaniu.


raczej nie dla @KonoromiHimaries 

---

Social `##.js-fb-page.c-fb-page`

**Comment by krystian3w** [comment]
@MajkiIT  dalej coś zostaje:

![obraz](https://user-images.githubusercontent.com/35370833/51076237-3022c000-1696-11e9-856e-f36c334c4eae.png) |
--- |

![obraz](https://user-images.githubusercontent.com/35370833/51076244-3add5500-1696-11e9-9572-c4489b4830e9.png) |
--- |
