### ISSUE TITLE
mar-grawer.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11041]
social prawy górny róg strony 

![ss419](https://user-images.githubusercontent.com/46375428/50971619-bac3bd80-14e4-11e9-8791-cf3dcf8d7370.png)

i social na dole
![ss420](https://user-images.githubusercontent.com/46375428/50971620-bac3bd80-14e4-11e9-80f0-789cb0257f83.png)

**Comment by krystian3w** [comment]
`mar-grawer.pl##.bd-icon.bd-icon-24, .bd-content-element.bd-textblock-28`

oby nie zbyt losowe.
