### ISSUE TITLE
forma.czest.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11042]
scrollujace widżety social po lewej

![ss422](https://user-images.githubusercontent.com/46375428/50971712-feb6c280-14e4-11e9-84cf-93c8f3c80f35.png)

![ss421](https://user-images.githubusercontent.com/46375428/50971711-feb6c280-14e4-11e9-85a0-11cd15ad629e.png)

![ss423](https://user-images.githubusercontent.com/46375428/50971740-12fabf80-14e5-11e9-94a2-8caced292abc.png)

**Comment by krystian3w** [comment]
`##.socialTabs`
