### ISSUE TITLE
strona (https://www.certyficate.it/adblock/)

### ISSUE THREAD

**Issue by azet12** [MajkiIT/polish-ads-filter#1105]
Na ekranach takich jak mój 1920x1080 tło na tej stonie źle się wyświetla - http://i.imgur.com/m5wMOuy.png
oraz ten link co ma teoretycznie dodać kilka list na raz nie działa z żadną wtyczką (testowałem na adblock, adblock plus i ublock).

**Comment by MajkiIT** [comment]
poprawione. Dzięki za info.

**Comment by azet12** [comment]
Jeden problem, zamiast
`abp:subscribe?location=https://raw.githubusercontent.com/azet12/KAD/master/KAD.txt&requiresTitle=KAD`
powinno być
`abp:subscribe?location=https://raw.githubusercontent.com/azet12/KAD/master/KAD.txt&title=KAD`
bo (przynajmniej w ublocku) nic się nie dzieje po kliknięciu tego.
Dzięki wielkie :)

**Comment by MajkiIT** [comment]
Gotowe

**Comment by azet12** [comment]
@MajkiIT na ublocku ciągle nie działa, bo "Title" jest z wielkiej litery, powinno być z małej :P
