### ISSUE TITLE
pbkm.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11057]
scrollujące social widżety po prawej

![ss437](https://user-images.githubusercontent.com/46375428/50982788-44cc5000-14fe-11e9-8795-13229bd4acad.png)

![ss438](https://user-images.githubusercontent.com/46375428/50982789-4564e680-14fe-11e9-965a-9c761614565e.png)

![ss439](https://user-images.githubusercontent.com/46375428/50982790-4564e680-14fe-11e9-803a-4beb1875546d.png)

**Comment by krystian3w** [comment]
`##.side-bar__item--instagram, .side-bar__item--facebook`
