### ISSUE TITLE
staresiolkowice.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11064]
scrollujące sociale po prawej

![ss446](https://user-images.githubusercontent.com/46375428/50984751-df2e9280-1502-11e9-8405-5b2f5ef0c795.png)

**Comment by MajkiIT** [comment]
@garrgul rozumiem, że znowu bawimy się w to samo ?

**Comment by xxcriticxx** [comment]
zamykamy?

**Comment by krystian3w** [comment]
Jak zrobiłeś PR?
