### ISSUE TITLE
motopodhale.info (2)

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11073]
(reklama) Reopen, powtarzam drugi raz, bo za pierwszym nie dotarło:  https://github.com/MajkiIT/polish-ads-filter/issues/11021#issuecomment-453177566.

**Comment by krystian3w** [comment]
`kierunekchorwacja.pl`

![obraz](https://user-images.githubusercontent.com/35370833/51076206-a541c580-1695-11e9-8ca5-84dfb3f27d62.png)

### `kierunekchorwacja.pl##.third-col__advert`

**Comment by krystian3w** [comment]
`beskidy.news`

 dalej coś zostaje:

![obraz](https://user-images.githubusercontent.com/35370833/51076237-3022c000-1696-11e9-856e-f36c334c4eae.png) |
--- |

![obraz](https://user-images.githubusercontent.com/35370833/51076244-3add5500-1696-11e9-9572-c4489b4830e9.png) |
--- |
