### ISSUE TITLE
ranking.abczdrowie.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#11070]
BŁĄD niemożna rozwinąć nr telefonu bez wyłączenia adblocka.
Błąd ten występuje tylko na profilach podających nr telefonu, np: https://ranking.abczdrowie.pl/d/katarzyna-mackowska-neurolog-bydgoszcz-78505#about

**Comment by hawkeye116477** [comment]
Wychodzi na to, że to wina :cookie:, a dokładniej tej reguły `ranking.abczdrowie.pl###app > div > div > div[class*=" "] > div`, @krystian3w do poprawy :smile:

**Comment by krystian3w** [comment]
A u mnie wcale nie naprawia jak mam ten pop-up about.

`#?##app > div > div > div > div:-abp-has(a[href="https://portal.abczdrowie.pl/strona/polityka-prywatnosci"])`

**Comment by hawkeye116477** [comment]
On powinien zresztą schować to chyba przed kliknięciem na „pokaż numer", a nie po, pop-up raczej nie aktywuje drugi raz komunikatu.

**Comment by krystian3w** [comment]
Mi chodzi o komunikat cookies, mam go po kliknięciu w pokaż numer ponownie.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/51076454-e091c380-1698-11e9-9217-3b9708881182.png)

**Comment by hawkeye116477** [comment]
@krystian3w A spróbuj wyczyścić dane. Bo to raczej wygląda mi na błąd, nie powinien się ponownie pokazać, skoro był już schowany, przycisk jedynie aktywuje dane kontaktowe, a nie komunikat :cookie:.

**Comment by krystian3w** [comment]
U mnie ma wtedy `:nth-of-type(5)`, więc to nie raczej błąd cache.

**Comment by krystian3w** [comment]
To samo nawet w trybie incognito, wraca i ma `:nth-of-type(5)`.

**Comment by hawkeye116477** [comment]
@krystian3w U mnie na Nano i Vivaldim jest ok, wychodzi na to, że to jest coś związane ze stylami użytkownika, bo sprawdziłem uBO i tam jest tak jak mówisz.

**Comment by krystian3w** [comment]
To zgłoś kiedyś do Raymonda i pochwal że jspenguin to naprawił już w marcu 2018?

**Comment by hawkeye116477** [comment]
@krystian3w Ale on tego nie naprawił, on wyłączył style użytkownika dla Chromium. Ale na FF z Nano też jest ten bug, po kliknięciu w popup, komunikat ciasteczkowy sam się uwidacznia. Ja bym to uznał za bug, bo skoro był już schowany, to jakim cudem nagle miałby „powstać z martwych" :smiley:

**Comment by krystian3w** [comment]
Maybe @licybora power on userCSS in Firefox unofficial version?

**Comment by hawkeye116477** [comment]
@krystian3w Nie ma co ją wołać, tak jest nawet i w uBO dla FF, w ABP i innych.
Tylko Nano ma ulepszenie :smiley:

**Comment by krystian3w** [comment]
A co tam testujesz?

`www.knorr.pl###_evidon_banner`?

Raczej będzie bezpieczne i trudno jak mamy polonie w Norwegii / Mołdawii.

**Comment by krystian3w** [comment]
`https://www.knorr.pl/produkty/fixy`

**Comment by hawkeye116477** [comment]
@krystian3w Hehe, Knora nie testuję, tak tylko mówiłem :smiley: 
uBO i Nano wycinają, tylko AG nie.
