### ISSUE TITLE
Multi Social

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11083]
Żeby nie spamować repo socialami, będę robił zgłoszenia w a potem je od razu zamykał i linka do zgłoszenia wklejał tutaj w tym jednym zbiorczym wątku. W konkretnych zgłoszeniach należy prowadzić dyskusję, wklejać filtry itp. można też wpisać w konkretnym zgłoszeniu frazę "do otwarcia" to wtedy otworzę takie zgłoszenie. Tu są tylko linki i ewentualnie jakieś ogólne kwestie.

Pula 1 (z dnia 12.01.2019):
https://github.com/MajkiIT/polish-ads-filter/issues/11076 https://github.com/MajkiIT/polish-ads-filter/issues/11077 https://github.com/MajkiIT/polish-ads-filter/issues/11078 https://github.com/MajkiIT/polish-ads-filter/issues/11079 https://github.com/MajkiIT/polish-ads-filter/issues/11080 https://github.com/MajkiIT/polish-ads-filter/issues/11081 ( w 11081 są też ciasteczka) https://github.com/MajkiIT/polish-ads-filter/issues/11082 https://github.com/MajkiIT/polish-ads-filter/issues/11084 https://github.com/MajkiIT/polish-ads-filter/issues/11085 https://github.com/MajkiIT/polish-ads-filter/issues/11086 https://github.com/MajkiIT/polish-ads-filter/issues/11087 https://github.com/MajkiIT/polish-ads-filter/issues/11088 https://github.com/MajkiIT/polish-ads-filter/issues/11089 https://github.com/MajkiIT/polish-ads-filter/issues/11090 https://github.com/MajkiIT/polish-ads-filter/issues/11091 https://github.com/MajkiIT/polish-ads-filter/issues/11092 https://github.com/MajkiIT/polish-ads-filter/issues/11093 https://github.com/MajkiIT/polish-ads-filter/issues/11094 https://github.com/MajkiIT/polish-ads-filter/issues/11095 https://github.com/MajkiIT/polish-ads-filter/issues/11096 https://github.com/MajkiIT/polish-ads-filter/issues/11097 https://github.com/MajkiIT/polish-ads-filter/issues/11098 https://github.com/MajkiIT/polish-ads-filter/issues/11099 https://github.com/MajkiIT/polish-ads-filter/issues/11100 https://github.com/MajkiIT/polish-ads-filter/issues/11101 https://github.com/MajkiIT/polish-ads-filter/issues/11102 https://github.com/MajkiIT/polish-ads-filter/issues/11103 https://github.com/MajkiIT/polish-ads-filter/issues/11104 https://github.com/MajkiIT/polish-ads-filter/issues/11105 https://github.com/MajkiIT/polish-ads-filter/issues/11106 https://github.com/MajkiIT/polish-ads-filter/issues/11107 https://github.com/MajkiIT/polish-ads-filter/issues/11108 https://github.com/MajkiIT/polish-ads-filter/issues/11109 https://github.com/MajkiIT/polish-ads-filter/issues/11111 https://github.com/MajkiIT/polish-ads-filter/issues/11112 https://github.com/MajkiIT/polish-ads-filter/issues/11113 https://github.com/MajkiIT/polish-ads-filter/issues/11114 https://github.com/MajkiIT/polish-ads-filter/issues/11115 https://github.com/MajkiIT/polish-ads-filter/issues/11116 https://github.com/MajkiIT/polish-ads-filter/issues/11117 https://github.com/MajkiIT/polish-ads-filter/issues/11119 https://github.com/MajkiIT/polish-ads-filter/issues/11120 

Pula 2 (z dnia 13.01.2019):
MajkiIT/polish-ads-filter#11123 MajkiIT/polish-ads-filter#11124 MajkiIT/polish-ads-filter#11125 MajkiIT/polish-ads-filter#11126 MajkiIT/polish-ads-filter#11128 MajkiIT/polish-ads-filter#11129 MajkiIT/polish-ads-filter#11130 MajkiIT/polish-ads-filter#11131 MajkiIT/polish-ads-filter#11132 MajkiIT/polish-ads-filter#11133 MajkiIT/polish-ads-filter#11134 MajkiIT/polish-ads-filter#11135 MajkiIT/polish-ads-filter#11136 MajkiIT/polish-ads-filter#11137 https://github.com/MajkiIT/polish-ads-filter/issues/11139 https://github.com/MajkiIT/polish-ads-filter/issues/11140 https://github.com/MajkiIT/polish-ads-filter/issues/11141 https://github.com/MajkiIT/polish-ads-filter/issues/11142 https://github.com/MajkiIT/polish-ads-filter/issues/11143 https://github.com/MajkiIT/polish-ads-filter/issues/11144 https://github.com/MajkiIT/polish-ads-filter/issues/11145 https://github.com/MajkiIT/polish-ads-filter/issues/11146 https://github.com/MajkiIT/polish-ads-filter/issues/11147 https://github.com/MajkiIT/polish-ads-filter/issues/11148 https://github.com/MajkiIT/polish-ads-filter/issues/11149 https://github.com/MajkiIT/polish-ads-filter/issues/11150 https://github.com/MajkiIT/polish-ads-filter/issues/11153 https://github.com/MajkiIT/polish-ads-filter/issues/11154 https://github.com/MajkiIT/polish-ads-filter/issues/11155 https://github.com/MajkiIT/polish-ads-filter/issues/11156 https://github.com/MajkiIT/polish-ads-filter/issues/11157 https://github.com/MajkiIT/polish-ads-filter/issues/11158 https://github.com/MajkiIT/polish-ads-filter/issues/11159 https://github.com/MajkiIT/polish-ads-filter/issues/11160 https://github.com/MajkiIT/polish-ads-filter/issues/11161 https://github.com/MajkiIT/polish-ads-filter/issues/11162 https://github.com/MajkiIT/polish-ads-filter/issues/11163

**Comment by krystian3w** [comment]
>https://github.com/MajkiIT/polish-ads-filter/issues/11089#issuecomment-453810271
>
> To jest niby do logowania, jak innych logowań nie usuwamy a nawet zgłaszamy by Fanboy naprawiał (i najczęściej naprawia), to bym to zostawił.

**Comment by krystian3w** [comment]
>https://github.com/MajkiIT/polish-ads-filter/issues/11098#issuecomment-453811678
>
>ABP / AdBlock obsługuje regex w `:-abp-contains`?

**Comment by krystian3w** [comment]
> https://github.com/MajkiIT/polish-ads-filter/issues/11099#issuecomment-453812048
> 
>  blokować slajd karuzeli?
> 
> ```
> ##a[href="https://www.facebook.com/45minutpl"] > .carousel-caption
> 
> ##a[href="https://www.facebook.com/45minutpl"] > img[src="/slider-pic/7/"]:style(visibility: hidden !important;)
> ```

**Comment by krystian3w** [comment]
> https://github.com/MajkiIT/polish-ads-filter/issues/11100#issuecomment-453812217
> 
> A to jak zablokować by nie migało przy przewijaniu...
> 
> ```
> ||kamaciuch.pl/modules/homeslider/images/1d85d9f6c8028a5b5dcc4190cccdadd6.png$image
> ```
> 
> :question:

**Comment by krystian3w** [comment]
> https://github.com/MajkiIT/polish-ads-filter/issues/11107#issuecomment-453813109
> 
> ```
> ##div.partial_staged_slideL.single_fading_slide:nth-of-type(5)
> ```
> 
> wycinamy takie coś?

**Comment by krystian3w** [comment]
```
||kamaciuch.pl/modules/homeslider/images/1d85d9f6c8028a5b5dcc4190cccdadd6.png$image
45minut.pl##.carousel-inner > .item.active > a[href="https://www.facebook.com/45minutpl"]:style(visibility: hidden !important;)


termgaz.pl###widget_social
wspomagamy.pl###text-5
elektrownia2.nazwa.pl##.header-image > p > a > img[src*="logo"]
firany.sklep.pl###footer .footer_Img.Img.module_box_one
beautyduty.pl###footer #text-5
multimetro.pl##.footer__fb
tago.com.pl##.float-social
carpetvista.pl##.g-padTstd.r-5cols.std > div.r-colspan1.r-col:nth-of-type(5)
eldomagd.eu##.pro-social-block
vubu.pl##.top_baner2 > a
vubu.pl##.trigger-facebook
supergrosz.pl##div.footerColumn:nth-of-type(3)
tortytorty.pl###top-menu > li:nth-of-type(n+5), #contact > .content > p:nth-of-type(4), .like-facebook
fefaq.pl###contact.contact
hotto.pl##.header-social
smartandart.pl##.contact-box-facebook
meteo.org.pl##.f > div:nth-of-type(2), .s
laracroft.pl##center > a[href="http://www.facebook.com/WorldOfTombRaider"] > img, img[src="sitegfx/menu_fb.jpg"], img[src="sitegfx/tube.jpg"]
holidon.pl###social
fandroid.com.pl##t.btIconWidget:nth-of-type(1)
tmproject.com.pl##.vc_column-inner > .wpb_wrapper:-abp-contains(/INSTAGRAM|MEDIA SPOŁECZNOŚCIOWE/)
pizzeriaubatmana.pl##.facebook-right
urz.pl##a.btn-default.button[href="https://www.facebook.com/SSURz"]
creaweb.pl###fb_all
as.cmielow.com.pl##.social
homeoffice360.pl###footerColumn2 > h3:nth-of-type(1), #footerColumn2 > a > img[src*="/xhtml/img/stopka_"]
dreamlandstory.com###section-4 > .container > .cta > a > img, .container > .bannerButtons > a:nth-of-type(3)
swietarodzina.pila.pl##div.partial_staged_slideL.single_fading_slide:nth-of-type(5)
ombre.pl###menu_buttons3 > .bxslider
ombre.pl###links_footer_3
dziennikwschodni.pl##.read-us-widget__social-item:nth-of-type(-n+2), div.footer__group:nth-of-type(4)
e-vasco.pl##.facebook-box-slider
narzedziadiamentowe.com###wysuwane
tint.pl##.noopslikebox
antywirus-nod32.pl##.page-footer div.span4:nth-of-type(3) > div > h4, .page-footer div.span4:nth-of-type(3) > div > h4 + ul > li > a > img
bialaowca.pl##.sidebar-box-menu > a:nth-of-type(1)
szczecin.uw.gov.pl###header-icons > a:nth-of-type(n+4):nth-of-type(-n+5) > img
ziolowaapteka.pl###fb-p
mzk-ostrow.com.pl##.rightpane p:nth-of-type(n+52):nth-of-type(-n+58)
nightwish.pl##.sidebar div.boxNoPadding.box:nth-of-type(1), .sidebar section.boxNoPadding
```
