### ISSUE TITLE
loveit.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11089]
Social - nie wiem czy to się kwalifikuje czy nie, czy to jakieś logowanie

![ss466](https://user-images.githubusercontent.com/46375428/51076537-fb186c80-1699-11e9-9843-e98720d24e97.png)

**Comment by krystian3w** [comment]
To jest niby do logowania, jak innych logowań nie usuwamy a nawet zgłaszamy by Fanboy naprawiał (i najczęściej naprawia), to bym to zostawił.

@hawkeye116477  / @blocker999 ?

**Comment by hawkeye116477** [comment]
@krystian3w Tak, zostawiamy.

**Comment by hawkeye116477** [comment]
@krystian3w Czy ja wiem, logowanie jest niby oddzielnie, a to jest niby szukanie znajomych, zapraszanie ich do serwisu, więc może jednak to schować.
