### ISSUE TITLE
tmproject.com.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11098]
wielki social

![ss479](https://user-images.githubusercontent.com/46375428/51076753-fbfecd80-169c-11e9-9d29-b9fe14350e5e.png)

**Comment by krystian3w** [comment]
@hawkeye116477  ABP / AdBlock obsługuje regex w `:-abp-contains`?

**Comment by hawkeye116477** [comment]
@krystian3w Nie wiem, zainstaluj i sprawdź :smile:.

**Comment by krystian3w** [comment]
No bo jak nie to trzeba przerobić na dwa.
