### ISSUE TITLE
tortytorty.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11090]
sociale

u góry
![ss467](https://user-images.githubusercontent.com/46375428/51076543-2b600b00-169a-11e9-9a32-ea148ae947d1.png)

na dole
![ss468](https://user-images.githubusercontent.com/46375428/51076544-2b600b00-169a-11e9-99ac-da9720494db3.png)

**Comment by krystian3w** [comment]
Jak coś wycinam też przycisk blog, niby już kilkanaście jest poblokowanych.
