### ISSUE TITLE
ceneo.pl

### ISSUE THREAD

**Issue by azet12** [MajkiIT/polish-ads-filter#1109]
http://www.ceneo.pl/Komputery
promowane oferty na górze i trochę niżej na lewym pasku (pod filtrami)
oraz przy dowolnej rzeczy, np. http://www.ceneo.pl/27556884 nad opiniami pojawiaja się pasek także promowanych ofert.

Aha, i przy okazji, sprawdź https://github.com/MajkiIT/polish-ads-filter/issues/1105#issuecomment-231593643

**Comment by xxcriticxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/15007183/16747900/037be85c-478f-11e6-9cad-24c742fba139.PNG)
