### ISSUE TITLE
dziennikwschodni.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11109]
sociale

1
![ss492](https://user-images.githubusercontent.com/46375428/51077890-c366f000-16ac-11e9-982d-219bc33d9b46.png)

2
![ss491](https://user-images.githubusercontent.com/46375428/51077891-c4981d00-16ac-11e9-8be5-4416c014f0cd.png)

**Comment by krystian3w** [comment]
demo link?
