### ISSUE TITLE
kamaciuch.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11100]
wielki baner social

![ss481](https://user-images.githubusercontent.com/46375428/51076773-6fa0da80-169d-11e9-97a9-ba8677369b4d.png)

**Comment by krystian3w** [comment]
A to jak zablokować by nie migało przy przewijaniu...

```
||kamaciuch.pl/modules/homeslider/images/1d85d9f6c8028a5b5dcc4190cccdadd6.png$image
```

:question:

**Comment by krystian3w** [comment]
zmienione na:

```
kamaciuch.pl##+js(remove-attr.js, href, .homeslider-container [href="https://www.facebook.com/kamaciuch"])
```

Przynajmniej się nie kliknie.
