### ISSUE TITLE
dreamlandstory.com

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11106]
sociale

1
![ss487](https://user-images.githubusercontent.com/46375428/51077795-5e5eca80-16ab-11e9-9d7e-0ce667234bfd.png)

2
![ss488](https://user-images.githubusercontent.com/46375428/51077796-5ef76100-16ab-11e9-8b7c-e976ad43ae9c.png)

**Comment by krystian3w** [comment]
hmmm...

```
###section-4 > .container > .cta > a > img, .container > .bannerButtons > a:nth-of-type(3)
```

:question:
