### ISSUE TITLE
swietarodzina.pila.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11107]
wielki baner social

![ss489](https://user-images.githubusercontent.com/46375428/51077820-a120a280-16ab-11e9-8e04-a9e40762c4a4.png)

**Comment by krystian3w** [comment]
```
##div.partial_staged_slideL.single_fading_slide:nth-of-type(5)
```

@hawkeye116477  / @blocker999  - wycinamy takie coś?

**Comment by hawkeye116477** [comment]
@krystian3w Czy ja wiem, mogą tam zawsze potem wstawić coś innego, może lepiej to zostawić :smile:.

**Comment by krystian3w** [comment]
mogę dodać wykrywanie "parafia w sieci".

**Comment by hawkeye116477** [comment]
@krystian3w Ale wtedy też będzie mniej wydajnie, raczej nie opłaca się :smile:.

**Comment by krystian3w** [comment]
@hawkeye116477  / @blocker999  `http://www.mixcloud.com/SwietaRodzina/` to już dla was Social?

**Comment by hawkeye116477** [comment]
@krystian3w Można uznać.

**Comment by krystian3w** [comment]
No to zostanie sam tekst z grafiką, chyba że linki z slajdu oszczędzimy.

Tekst:

![obraz](https://user-images.githubusercontent.com/35370833/51085558-931a6280-173b-11e9-8199-8e31f8dcfa44.png) |
--- |
