### ISSUE TITLE
hd-opinie.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11110]
reklama po prawej + ponad nią jakieś puste belki

![ss494](https://user-images.githubusercontent.com/46375428/51077913-3d977480-16ad-11e9-890a-f6ed2cd64f88.png)

**Comment by krystian3w** [comment]
belki i reklamę za raz dodam do muli aktualizacji

**Comment by krystian3w** [comment]
```
||hd-opinie.pl/wp-content/themes/hdopinie/images/rightcol_shadow.png$image

hd-opinie.pl###text-5, #better-text-3, #better-text-5, #better-text-6, #better-text-7
```

**Comment by krystian3w** [comment]
`###better-text-2.fanpage` widgetach social będzie @MajkiIT byś czasem sam nie dodał jako element reklamowy.
