### ISSUE TITLE
euroticket.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11123]
social

![ss505](https://user-images.githubusercontent.com/46375428/51083845-ea5f0980-1720-11e9-8d4e-afe6ba44f476.png)

**Comment by krystian3w** [comment]
@garrgul  doklejaj tak by się nie pomieszało z starymi.

**Comment by garrgul** [comment]
@krystian3w ok to oddzielę w głównym wątku

**Comment by krystian3w** [comment]
Może być podział na daty wklejenia.
