### ISSUE TITLE
buu.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11131]
wielki social

![ss513](https://user-images.githubusercontent.com/46375428/51084027-dc5eb800-1723-11e9-8dcb-13183d13dc0d.png)

**Comment by krystian3w** [comment]
```
###footer > div.omega.alpha.grid_24:nth-of-type(5), div.omega.alpha.grid_24:nth-of-type(4) p:nth-of-type(5)
```

ciekawe czy losują grida lub jest więcej elementów.
