### ISSUE TITLE
pangrono.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11145]
sociale po prawej

1
![ss532](https://user-images.githubusercontent.com/46375428/51084726-1f725880-172f-11e9-83ab-97b66262e5a0.png)

2
![ss531](https://user-images.githubusercontent.com/46375428/51084725-1f725880-172f-11e9-96c6-ec92c1e364eb.png)

**Comment by krystian3w** [comment]
1 - newsletter raczej :walking_woman: 

2.  już na social się nadaje.
