### ISSUE TITLE
dzdn.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11144]
social link po lewej (nie jestem pewien czy zwykły link (bez ikony) się kwalifikuje)

![ss530](https://user-images.githubusercontent.com/46375428/51084698-ad9a0f00-172e-11e9-8ad9-dcdc84eca7e3.png)

**Comment by krystian3w** [comment]
Musiałem jakoś ominąć. W sumie można wyciąć i tak ostatnio dobezpieczam by nie wycinało za dużo linków z góry.
