### ISSUE TITLE
multitouch.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11157]
duży social po lewej na środku długości strony

![ss542](https://user-images.githubusercontent.com/46375428/51087357-789fb380-1752-11e9-85da-245634747148.png)

**Comment by krystian3w** [comment]
`http://multitouch.pl/aktualnosci/najnowsze-realizacje-juz-na-facebooku` czyli ich zawartość i raczej zostaje
