### ISSUE TITLE
niepoprawni.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#11168]
Twoja wtyczka AdBlock Plus zablokowała tu banner do cennej inicjatywy. Prosimy zrób wyjątek i odblokuj bannery na niepoprawni.pl!

Licznik wykrytych blokad tego banera:
Darmowy licznik odwiedzin

**Comment by krystian3w** [comment]
`###block-block-29.block-block.block` - ale trochę słabe wycinać komunikat, to już nawet w uBO wolą regułę skryptową.

**Comment by hawkeye116477** [comment]
A u mnie nic nie ma.

**Comment by krystian3w** [comment]
U mnie wskoczyło jak wyłączyłem i włączyłem.

**Comment by krystian3w** [comment]
![image](https://user-images.githubusercontent.com/35370833/51109565-e0f3a100-17f5-11e9-9764-a7770ab6cb1f.png) |
--- |

**Comment by krystian3w** [comment]
`||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=noopjs,domain=niepoprawni.pl,important`

@olegwukr  - https://github.com/olegwukr/polish-privacy-filters/blob/b9669fc83024b1239a5499c49b4ab147c9c5fb80/anti-adblock-suplement.txt#L55

**Comment by hawkeye116477** [comment]
Ale lepiej wyciąć komunikat niż robić skryptowo, bo wtedy też zadziała dla ABP :smile:.

**Comment by krystian3w** [comment]
A to dla ABP/AdGuard może:

`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=niepoprawni.pl` i inaczej zablokować reklamę jak na pewno jakaś wycieknie? uBO będzie broniło "`important`".

**Comment by hawkeye116477** [comment]
@krystian3w U mnie whitelist nie pomaga. A te wycinanie to trochę słabe, bo jeszcze pod logowaniem wyskakuje komunikat.

**Comment by hawkeye116477** [comment]
`||niepoprawni.pl/sites/all/libraries/copier/_bck.js`

**Comment by krystian3w** [comment]
to jeszcze w AdGuard znaleźli taki: https://github.com/AdguardTeam/AdguardFilters/commit/1042c6ba1c6b25e6e9fa9e451dbff82ec802fb15 i załatali w AdGuard Base, CSS-em.

**Comment by MajkiIT** [comment]
@krystian3w A Nano Defender nie wycina tego ?

**Comment by krystian3w** [comment]
Nie, dodatkowo rozbudowali skrypt:

```js
(function(_0x201c23) {
    var _0x3ea642 = function() {
        var _0x1caa43 = !![];
        return function(_0x5c8552, _0x33062c) {
            var _0x39b46c = _0x1caa43 ? function() {
                if (_0x33062c) {
                    var _0x55ab7d = _0x33062c['apply'](_0x5c8552, arguments);
                    _0x33062c = null;
                    return _0x55ab7d;
                }
            } : function() {};
            _0x1caa43 = ![];
            return _0x39b46c;
        };
    }();
    var _0x41ccc0 = _0x3ea642(this, function() {
        var _0x4f0b54 = function() {
                return 'dev';
            },
            _0x1afd0f = function() {
                return 'window';
            };
        var _0x379349 = function() {
            var _0x17b502 = new RegExp('\\w+ *\\(\\) *{\\w+ *[\'|\"].+[\'|\"];? *}');
            return !_0x17b502['test'](_0x4f0b54['toString']());
        };
        var _0x550f90 = function() {
            var _0x57086a = new RegExp('(\\\\[x|u](\\w){2,4})+');
            return _0x57086a['test'](_0x1afd0f['toString']());
        };
        var _0x2c9520 = function(_0x2b3238) {
            var _0x24c4de = ~-0x1 >> 0x1 + 0xff % 0x0;
            if (_0x2b3238['indexOf']('i' === _0x24c4de)) {
                _0x544626(_0x2b3238);
            }
        };
        var _0x544626 = function(_0x45107d) {
            var _0x27fb3a = ~-0x4 >> 0x1 + 0xff % 0x0;
            if (_0x45107d['indexOf']((!![] + '')[0x3]) !== _0x27fb3a) {
                _0x2c9520(_0x45107d);
            }
        };
        if (!_0x379349()) {
            if (!_0x550f90()) {
                _0x2c9520('indеxOf');
            } else {
                _0x2c9520('indexOf');
            }
        } else {
            _0x2c9520('indеxOf');
        }
    });
    _0x41ccc0();
    var _0x4be7ce = document['createElement']('div');
    _0x4be7ce['setAttribute']('class', 'ads adsbox ad');
    _0x4be7ce['setAttribute']('style', 'position: fixed; ' + 'top: 0; ' + 'left: 0; ' + 'width: 1px; ' + 'height: 1px; ' + 'opacity: 0.1; ');
    _0x4be7ce['innerText'] = '_';
    _0x201c23['document']['body']['appendChild'](_0x4be7ce);
    _0x201c23['adsSupported'] = _0x4be7ce;
}(window));
```

Kiedyś to tam mieli chyba tylko wysyłanie zmiennej / parametru "można wyświetlić reklamy", a teraz siedzi nawet generator wabika jak ktoś nie wycina sieciowo elementów.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/commit/b947d3e44cdf129ae9236c11a5bf1514bf28b0bf jacyś stadionowcy

**Comment by krystian3w** [comment]
@MajkiIT  / @olegwukr  dalej są komunikaty na `solarmovies.pl` / `stadionowioprawcy.net` / `lunaticfiles.com/ufxjzmo2w6p8/owca.png.html`

**Comment by hawkeye116477** [comment]
Dla uBO już nie ma, gorzej mają ci co mają ABP. W przypadku raciborza nie ma dla nich ratunku, ale stadionowców można dodać.
