### ISSUE TITLE
mgr.farm

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#11164]
![capture](https://user-images.githubusercontent.com/15007183/51089093-9f9bbc80-1735-11e9-88d1-23bba1ee05dc.PNG)

**Comment by krystian3w** [comment]
O nie mają brzydki blur pod komunikatem.

**Comment by krystian3w** [comment]
I po drugie wymagają potwierdzenia w komunikacie że jesteś farmaceutą.

**Comment by hawkeye116477** [comment]
@krystian3w No to co darujemy? Farmaceuci i lekarza sobie poradzą, a inni pewnie i tak tam nie wchodzą :smiley:

**Comment by garrggul** [comment]
Przy okazji błąd u Fanboya: https://github.com/ryanbr/fanboy-adblock/issues/911
