### ISSUE TITLE
cda.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#11172]
https://www.cda.pl/video/525488ba/vfilm
Reklamy w playerze.
![image](https://user-images.githubusercontent.com/29756590/51090175-31c4b480-1778-11e9-86b6-f134ca9d4a25.png)

**Comment by krystian3w** [comment]
@MajkiIT  regex?

**Comment by MajkiIT** [comment]
@krystian3w @HateAds Poprawione
