### ISSUE TITLE
charlizemystery.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#11174]
![zrzut ekranu z 2019-01-14 07-11-43](https://user-images.githubusercontent.com/36385327/51098606-ca385480-17cb-11e9-837d-cadd0a68a90d.png)

**Comment by krystian3w** [comment]
`charlizemystery.com#?##popups:-abp-has(> .popup_box > .cookie-empty)`

**Comment by hawkeye116477** [comment]
@krystian3w A nie lepiej `charlizemystery.com##.cookie-empty`?

**Comment by krystian3w** [comment]
chyba pasek zostawał?

**Comment by hawkeye116477** [comment]
@krystian3w Tak
