### ISSUE TITLE
fandroid.com.pl (2)

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11182]
Social - reopen https://github.com/MajkiIT/polish-ads-filter/issues/11097 bo pomimo, że jakiś filtr był dodany, to dalej to jest.

**Comment by krystian3w** [comment]
w sumie cud, bo wycięłoby wyszukiwarkę:

`##t.btIconWidget:nth-of-type(1)` 

```html
<t clas="...">
F
</t>
```

tag t - :rofl:

**Comment by hawkeye116477** [comment]
`fandroid.com.pl##a.btWidgetWithText.btAccentIconWidget.btIconWidget:nth-of-type(1)`

**Comment by krystian3w** [comment]
Jak coś wystarczają na razie dwie klasy i nth-of-type:

`##.btAccentIconWidget.btIconWidget:nth-of-type(1)`
