### ISSUE TITLE
sweetdecor.pl (2)

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11181]
Social - reopen https://github.com/MajkiIT/polish-ads-filter/issues/11154, bo przeoczyłem w zgłoszeniu wielki baner na środku:

![ss_041](https://user-images.githubusercontent.com/46375428/51116068-4f425e80-180a-11e9-9b1f-73312bc5f1dc.png)

**Comment by krystian3w** [comment]
@hawkeye116477  / @blocker999  - z tym co, nazwy w mikro-wpisie nie ma by przeszukać grupy facebook.

**Comment by hawkeye116477** [comment]
Artykuły raczej zostawiamy :smile:.
