### ISSUE TITLE
tago.com.pl (2)

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11180]
Social - reopen https://github.com/MajkiIT/polish-ads-filter/issues/11082, bo przeoczyłem w zgłoszeniu,  że takie same ikony/przyciski są także w prawym dolnym rogu:

![ss389](https://user-images.githubusercontent.com/46375428/51115927-ec50c780-1809-11e9-8696-06dc9b28579b.png)

**Comment by krystian3w** [comment]
`##.social`
