### ISSUE TITLE
kaufland.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11200]
Social x 2 po lewej:

1
![ss407](https://user-images.githubusercontent.com/46375428/51119729-e3fd8a00-1813-11e9-9bf4-1004033732b4.png)

2
![ss408](https://user-images.githubusercontent.com/46375428/51119730-e65fe400-1813-11e9-98bf-8717eb086620.png)

**Comment by krystian3w** [comment]
I 3 w stopce "Social Media".
