### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11208]
Reopen błędu https://github.com/MajkiIT/polish-ads-filter/issues/11004#issuecomment-452669132, bo powrócił z jeszcze większą mocą, teraz poza trzema górnymi, to prawie wszystkie zdjęcia/obrazki się nie wczytują, błąd jest krytyczny, strona bardzo popularna:

<details not-open>
<summary>screenshooty</summary>

![ss_047](https://user-images.githubusercontent.com/46375428/51127455-c802e400-1825-11e9-9391-28d352ac4fa0.png)
![ss_050](https://user-images.githubusercontent.com/46375428/51127457-c802e400-1825-11e9-90ad-745b291ce6b0.png)
![ss_051](https://user-images.githubusercontent.com/46375428/51127458-c89b7a80-1825-11e9-8cd7-3ad995990999.png)
![ss_052](https://user-images.githubusercontent.com/46375428/51127459-c89b7a80-1825-11e9-8044-bd204418e754.png)
![ss_053](https://user-images.githubusercontent.com/46375428/51127460-c89b7a80-1825-11e9-8c08-019b14622bfb.png)
![ss_054](https://user-images.githubusercontent.com/46375428/51127462-c9341100-1825-11e9-9b3d-6d1e6a02573f.png)
![ss_055](https://user-images.githubusercontent.com/46375428/51127463-c9341100-1825-11e9-854d-74550fb675d0.png)
![ss_056](https://user-images.githubusercontent.com/46375428/51127464-c9341100-1825-11e9-895a-b8ca4e4a3c05.png)
![ss_057](https://user-images.githubusercontent.com/46375428/51127465-c9cca780-1825-11e9-9d39-842e8cdbb067.png)
![ss_058](https://user-images.githubusercontent.com/46375428/51127466-c9cca780-1825-11e9-9420-b4b03a90c09c.png)
![ss_059](https://user-images.githubusercontent.com/46375428/51127467-c9cca780-1825-11e9-8b96-210fd4800643.png)
![ss_060](https://user-images.githubusercontent.com/46375428/51127468-c9cca780-1825-11e9-81a5-6e092a65c011.png)
![ss_061](https://user-images.githubusercontent.com/46375428/51127472-cb966b00-1825-11e9-8b82-84e51af4a465.png)
![ss_062](https://user-images.githubusercontent.com/46375428/51127473-ccc79800-1825-11e9-9fc9-49e7307de811.png)

</details>

**Comment by MajkiIT** [comment]
@garrgul Juz powinno być ok

**Comment by krystian3w** [comment]
> po tych kilkunastu sekundach przewijanie samo wraca, (...) dopóki ręcznie nie odświeży się strony


reklama bez wsparcia odblokowania CSS-em przewijania?

**Comment by krystian3w** [comment]
Albo jednak cookies/RODO po awarii nawigacji, a **`@`hawkeye116477**  mówił że zbędne. 

Normalnie druga `Autostrada-a2.pl`, będzie niedługo z filmweba.

**Comment by hawkeye116477** [comment]
@krystian3w Jeżeli chodzi o RODO, to u mnie ten problem nie występuje ani na FF z uBO ani Vivaldim z Nano.

**Comment by garrgulowy** [comment]
Usterka z przewijaniem również naprawiona, do zamknięcia, (zamknąłbym sam ale dostałem banana na tamten nick).

**Comment by krystian3w** [comment]
A dasz link gdzie tego szukać..

I trzy trzeba na tym :hankey:  się rejestrować...

**Comment by lukjan32** [comment]
tak, trzeba.

![filmweb](https://user-images.githubusercontent.com/17565773/51892004-f09be980-23a0-11e9-953e-c149f06c356f.jpg)

**Comment by krystian3w** [comment]
Logowanie/rejestrowanie jest jakieś dziwne, szary tekst nie znika jak coś wpisuje. Rejestracja przez Google też nie działa.

**Comment by krystian3w** [comment]
To chyba błąd w Operze z Filmwebem, nawet RODO się nie akceptuje.

**Comment by lukjan32** [comment]
nawet nie pomaga czyszczenie ciasteczek w filmweb.

**Comment by krystian3w** [comment]
Ja to miałem raz w Firefox i nie chce wskoczyć, najwyżej będzie trzeba znów z teamviewer.

**Comment by lukjan32** [comment]
jak dodam do wyjatkow to dziala.

**Comment by krystian3w** [comment]
No wiem, ale lepiej naprawić, poza tym paczaj jak oni mają walniętą tę stronę:

![image](https://user-images.githubusercontent.com/35370833/51893354-e380f980-23a4-11e9-9ff1-ee15ac41b557.png) |
--- |

Suwak poziomy się robi jakby szerokość strony była 3 razy taka jak jest.

**Comment by lukjan32** [comment]
samo sie naprawillo

**Comment by krystian3w** [comment]
U mnie w Operze 57 dalej nie działa logowanie: 

![image](https://user-images.githubusercontent.com/35370833/51893858-7706fa00-23a6-11e9-9a87-f3b899f9ab8d.png) |
--- |
![image](https://user-images.githubusercontent.com/35370833/51893876-838b5280-23a6-11e9-8f69-c74c52e55142.png) |
