### ISSUE TITLE
homebook.pl 

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11206]
RODO (dodałem tag RODO, żeby admin nie pomylił z socialami):

![ss_044](https://user-images.githubusercontent.com/46375428/51120588-b9143580-1815-11e9-814a-5b76f38ff837.png)

**Comment by krystian3w** [comment]
Ja nie mam... ale skoro to te z WP, to dopiszę do skryptu "dyfuzorowego".
