### ISSUE TITLE
purina.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11219]
Social na dole:

![ss395](https://user-images.githubusercontent.com/46375428/51136314-74e85b80-183c-11e9-93c8-e369244846ff.png)

**Comment by krystian3w** [comment]
@garrgul  / @hawkeye116477  tylko białe i video zostawić?

bo tak to się robi dziwny suwak po użyciu:
`##div[data-block-plugin-id="views_block:nppe_base_community_iframe-block_1"]`

**Comment by hawkeye116477** [comment]
@krystian3w U mnie jest ok, wycinamy całe.

**Comment by krystian3w** [comment]
Dobra suwak będą mieli niewidomi i niedowidzący lub osoby co wymuszą zoom na 120% i więcej.

**Comment by hawkeye116477** [comment]
@krystian3w Mam Full HD (1920x1080), ustawiłem DPI na 125 i nadal mam tylko 1 suwak :stuck_out_tongue:

**Comment by krystian3w** [comment]
Ale Operę masz? u mnie robią się dalej dwa i pomaga tylko zmiana wielkości okna na niepełne lub zoom 80%.

**Comment by hawkeye116477** [comment]
@krystian3w Tak

**Comment by garrgul** [comment]
> krystian3w: 
> 
> @garrgul / @hawkeye116477 tylko białe i video zostawić?
> 
> bo tak to się robi dziwny suwak po użyciu:
> `##div[data-block-plugin-id="views_block:nppe_base_community_iframe-block_1"]`

> hawkeye116477 :
> 
> @krystian3w U mnie jest ok, wycinamy całe.

Potwierdzam problem jak u krystian3w, wyskakuje drugi suwak (tylko na Operze, na Firefoxie nie), oraz także potwierdzam, że ustawienie zoomu na 90% i suwak znika.

<details not-open>
<summary>Opera:</summary>

![opera](https://user-images.githubusercontent.com/46375428/51175752-75740700-18bb-11e9-926f-e0fda7e29f04.gif)

</details>
<br>
<details not-open>
<summary>Firefox:</summary>

![firefox](https://user-images.githubusercontent.com/46375428/51175757-79078e00-18bb-11e9-8134-92a0e54b61ce.gif)

</details>
