### ISSUE TITLE
publolek.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11226]
Social ikony/przyciski na środku:

![ss401](https://user-images.githubusercontent.com/46375428/51136972-060c0200-183e-11e9-8223-36bce0b3d53a.png)

**Comment by krystian3w** [comment]
`/plugins/uk-cookie-consent/assets/js/uk-cookie-consent-js.js$script,domain=pl` @hawkeye116477  psuje wgrywanie tła pod tym widgetem.
