### ISSUE TITLE
domhobbyogrod.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11234]
Social widżet scrollujący po prawej:

![fb3](https://user-images.githubusercontent.com/46375428/51138212-c692e500-1840-11e9-9d72-15a3acfbdaa4.gif)

**Comment by krystian3w** [comment]
Nie mam, zależne od ustawień w przeglądarce / systemie... lub masz nie wiadomo skąd generichide?

**Comment by krystian3w** [comment]
@hawkeye116477  masz to, bo mi coś już to ukrywa.

**Comment by hawkeye116477** [comment]
@krystian3w `pl##.no_print.toplayerSpecialClass` w widgetach EI.

**Comment by krystian3w** [comment]
Dzięki.
