### ISSUE TITLE
paga.org.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11230]
Social ikony/przyciski po prawej na dole:

![ss407](https://user-images.githubusercontent.com/46375428/51137608-3902c580-183f-11e9-9b07-a57a0139f0bc.png)

**Comment by krystian3w** [comment]
@hawkeye116477  `##.footer-icons` chyba będzie bezpieczne, bo mają też zestaw pod mobile i nie widoczny z dużym monitorem.
