### ISSUE TITLE
drogerielaboo.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11240]
Social wielki baner po środku:

![ss419](https://user-images.githubusercontent.com/46375428/51138778-4e2d2380-1842-11e9-9fda-b5b10dc6acf9.png)

**Comment by krystian3w** [comment]
`##div > a[href="http://facebook.com/drogerielaboo"]`

Chyba, że slider będzie umiał bez problemu wyświetlać t**ę** drugą grafik**ę** i nie zrobi się puste pole.
