### ISSUE TITLE
https://www.certyficate.it/adblock/

### ISSUE THREAD

**Issue by azet12** [MajkiIT/polish-ads-filter#1124]
łącze do mojego filtra nadal nie działa na ublocku, pewnie dlatego bo "Title" w linku jest z wielkiej litery, czyli powinno być
`<a href="abp:subscribe?location=https://raw.githubusercontent.com/azet12/KAD/master/KAD.txt&title=KAD" style="font-style: normal; font-size: 50px;">Dodaj filtr chroniący przed przekrętami jak np. subskrypcje SMS.</a>`

**Comment by MajkiIT** [comment]
gotowe
