### ISSUE TITLE
napiachu.pl

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11257]
Social wielki baner na środku:

![ss436](https://user-images.githubusercontent.com/46375428/51140070-d5c86180-1845-11e9-9efb-1a437e2c06d8.png)

oraz po lewej na dole social:

![ss437](https://user-images.githubusercontent.com/46375428/51140086-e4af1400-1845-11e9-8900-48f9487b4685.png)

**Comment by MajkiIT** [comment]
@garrgul ty tak celowo po złości ?

**Comment by garrgul** [comment]
Nie, co ty: 1) z uzależnienia / chęci, 2) z chęci odstrzału elementu socjalnego.

**Comment by krystian3w** [comment]
`napiachu.pl##+js(remove-attr.js, href, .carousel-inner  a[href="https://www.facebook.com/napiachu/"])`

nie usuwam karuzeli by strona nie skakała lub się ludzie nie dezorientowali z pustych slajdów.

**Comment by krystian3w** [comment]
to tak lista filtrów, mam 58 - liczyć od 1200.

Niby może braknąć dwóch zgłoszeń:

```
alkalicznystylzycia.com##.footer-instagram-wrapper, .header-info-text > a:nth-of-type(-n+3)
biutiq.pl##.slidebox
car-rental.pl##.box_social_instagram
dnagdansk.com###facebookdna
domhobbyogrod.pl##.toplayerSpecialClass+ .toplayerSpecialClass
drogerielaboo.pl##div[style] > [href="http://facebook.com/drogerielaboo"]
elwico.com.pl##.kac-sm-block
festiwalinspiracji.pl##div.tzSpace_default.vc_row-fluid.wpb_row.vc_row:-abp-contains(OBSERWUJ NAS NA FACEBOOKU)
fifek.pl###float_facebook_box
hotel-tulipan.pl##div.banner2:nth-of-type(-n+4)
iaeste.pl##a > img[src="/images/template/icons/icon-inst.png"],a > img[src="/images/template/icons/icon-lin.png"]
inkubatorstarter.pl##.social
janniezbedny.pl###social_gp
jedz-bezpiecznie.pl###wys, a > img[src^="foto/elementy/social-media-"]
kwadranszpodkopem.com###text-3
lazienkiportal.pl###fb_box
motoperfekt.pl##.userfooter
nagraniahipnotyczne.pl##.facebook-bookmark
najblizejludzi.pl###contact.footer .col-xl-3
oculino.com##.site-social-icons-facebook, .site-social-icons-googleplus, .site-social-icons-youtube
oskko.net#?#span.style18:nth-of-type(2):-abp-contains(Dołącz do nas na:)
oskko.net##td > a[href="https://plus.google.com/+oskko"]
paga.org.pl##div.footer-icons
proline.pl##a[href="https://www.youtube.com/c/proline"] > img
publolek.pl##.footer-widget-1.widget-column, .info-box > div:nth-of-type(2) > a
release24.pl###rightwindow > div:nth-of-type(2) > div > ul > li:nth-of-type(4)
starecegly.com###box_facebooklike
swingwithme.pl###text-3, #widget_sp_image-5
twardepierniki.pl##.socialmedia-panels
wege-warszawa.pl##.header-social, #text-5 > .textwidget > table
winers.pl###text-3, .sc_columns
wrodzinie.pl###text-3, #text-5
accu-chek.pl###accuchek-facebook
czynnecaladobe.pl###face-slider
dekea.pl##div.footer-widget.col-sm-3:nth-of-type(5)
dziecieceinspiracje.pl###HTML1, #HTML2
elancut.pl###flashContent > img[src="/baner/fb.jpg"]
eyca.pl##.fb-lang
eyca.pl##.fb-logo
fundacjakibica.pl###fb_rozwin
gosnet.pl##a[href="https://www.facebook.com/Gosnet"] > img
jaion.pl###text-29
jaion.pl##.clearfix.cb-column.cb-one:-abp-has(> #custom_html-3)
jedz-bezpiecznie.pl##a[href="https://www.facebook.com/groups/pracawmotoryzacji/"] > img
kaufland.pl##.g-layout-columns--2.g-layout-columns.g-row > div.g-col-2.g-col-spacing.g-col:nth-of-type(1)
kaufland.pl##.g-layout-columns--3.g-layout-columns.g-row > .g-col-4.g-col-spacing.g-col
kaufland.pl##.o-footer__social-media
www.mbank.pl###facebook
www.money.pl##.fuOmTF.sc-7nq3hz-0
nepalshop.pl##a > img[src="/public/assets/ico-yt.png"], a > img[src="/public/assets/ico-insta.png"]
papurazzi.pl##.socialeFooter
pilotpen.pl##.plt-Footer_social_list, .plt-Footer_title, .plt-Header_tools
podkop.com###text-14 > .textwidget p > a:not([href="http://podkop.com/kontakt/"])
projektgamma.pl###face-slider2
purina.pl##div[data-block-plugin-id*="nppe_base_community"]
superkantor.pl###fb_rozwin
v1ncent.pl##.here_are_socials, .sidebar .col-lg-12 > h3.border-bottom:nth-of-type(2), .sidebar > h3.first_on_top.border-bottom:nth-of-type(2)
webcamera.pl##.instagram-box

**Comment by garrgul** [comment]
Jako, że wczoraj czy dzisiaj w uBO ukazała się nowa lista socjalna: AdGuard Social Media filter, to chciałem poinformować, że od teraz będę korzystał również i z niej jako z przydatnego uzupełnienia do Fanboy’s Social Blocking List:

![ss443](https://user-images.githubusercontent.com/46375428/51181195-ca6b4980-18ca-11e9-99a0-6e759b18ea86.png)

**Comment by krystian3w** [comment]
Nas raczej nie zadowala, nie wycinają przycisków, więc raczej dalej by zgłoszenia buttonów wpadały.

A lista niby dużo wcześniej wskoczyła, może nawet tydzień temu o ile to nie była norweska gadka, że udało się dodać nową listę mimo zakazu.

**Comment by hawkeye116477** [comment]
Jakiego zakazu? Można było i sporo wcześniej samemu dodać :stuck_out_tongue:

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/commit/7af452a1eb735c49ca646ca2c18e13dc98aedcb9
https://github.com/uBlockOrigin/uBlock-issues/commit/24139c2fb67d98536cb82ac78e027dc0f9055841
https://github.com/uBlockOrigin/uBlock-issues/commit/632f9eee156808e31509e65d1ef7ff839e7ebaa6

**Comment by MajkiIT** [comment]
> 
> 
> Nie, co ty: 1) z uzależnienia / chęci, 2) z chęci odstrzału elementu socjalnego.

@garrgul To już przeginka... My idziemy na jkość a nie na ilość.

**Comment by hawkeye116477** [comment]
No właśnie, ja mu też to mówiłem, a on dalej swoje.

**Comment by garrgulowy** [comment]
Dobra weźcie już nie odwracaj kota ogonem, że to ze mną nie idzie się dogadać, bo próbowałem pójść na kompromis, założyłem wątek zbiorczy https://github.com/MajkiIT/polish-ads-filter/issues/11083, który nikomu nie przeszkadzał, mogłem w nim zgłaszać social ile chciałem, a wy robiliście ile wam się chciało, a ja te zrobione bym wykreślał, kompromis bardzo dobry, bo wilk syty i owca cała, nikomu to nie przeszkadzało, tylko tobie zaczęło, zdziwiłem się w jaki niby sposób może to przeszkadzać, więc zapytałem, i odpisałeś w swoim komentarzu jakieś niejasne powody typu baletnicy rąbek u spódnicy, a na moj komentarz żeby wyjaśnić te powody, już nie odpisałeś, a wątek zbiorczy zamknąłeś, więc kto tu przestał się pierwszy odzywać i prowadzić dialog, komu skończyły się pierwszemu argumenty, z kim nie szło się dogadać? Ale teraz najlepiej zwalić na mnie. To może odpiszesz chociaż tutaj w czym niby przeszkadzał wątek zbiorczy?

**Comment by hawkeye116477** [comment]
Było zrobione wszystko, więc zamknięte :stuck_out_tongue: 
Czy wszystko w jednym czy pojedynczo to większej różnicy nie robi, bo i tak robotę trzeba kiedyś chyba skończyć, a jak będziemy tak robić po 10 dziennie, a ty będziesz dokładał codziennie, to do usranej śmierci tego nie skończymy. Dlatego każdy chce nadgonić, by mieć też czas na inne rzeczy. My to robimy za darmo, nie jesteś naszym szefem, więc nie powinieneś dawać tyle roboty.

**Comment by xxcriticxx** [comment]
this party is over now!
