### ISSUE TITLE
oskko.net

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11254]
Social ikony/przyciski:

![ss433](https://user-images.githubusercontent.com/46375428/51139815-31deb600-1845-11e9-82c8-e3f17e50848a.png)

**Comment by krystian3w** [comment]
a na samym dole jakiś osierocony "[google+]()".

**Comment by garrgul** [comment]
![ss441](https://user-images.githubusercontent.com/46375428/51178975-912fdb00-18c4-11e9-8169-ab5a1105b7aa.png)


Racja, tyle, że to sam link, bez ikony, a nie dawno zgłaszałem takie zgłoszenie z właśnie takim linkiem socjalnym, nie będąc pewnym czy się kwalifikuje https://github.com/MajkiIT/polish-ads-filter/issues/11144 i zostało zamknięte ale nie naprawione, bo dalej ten link jest, więc pomyślałem, że skoro tak to gołe linki się nie kwalifikują, a jednak mówisz, że się kwalifikują, to w takim razie rozumiem przez to, że tamto kwalifikuje się do reopenu.

**Comment by krystian3w** [comment]
czekaj zobaczę je ponownie, może przejechałem mimo posiadania:

`github.com##.comment-body a.issue-link:visited:style(color: green !important; font-size: small !important;)`
Jeszcze musiałbym dorobić kolorowanie na liście.
