### ISSUE TITLE
oculino.com

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11252]
Social przyciski/ikony: u góry po prawej + na dole po prawej:

1
![ss438](https://user-images.githubusercontent.com/46375428/51177704-a73b9c80-18c0-11e9-954d-7cb01ac7ed35.png)

2
![ss431](https://user-images.githubusercontent.com/46375428/51139703-e0cec200-1844-11e9-918a-d6d05608cf22.png)

**Comment by krystian3w** [comment]
na górze też.

**Comment by garrgul** [comment]
U mnie nie ma bocznych nawet po wyłączeniu uBO zarówno na Firefoxie jak i Operze, natomiast u mnie z kolei na Operze coś za dużo ukrywa i to nawet z wyłączonym uBO, bo nawet to co u ciebie widać tę grafikę to znika po chwili:

<details not-open>
<summary>Opera</summary>

![ss440](https://user-images.githubusercontent.com/46375428/51178390-aefc4080-18c2-11e9-9b86-aef0105b11bc.png)

</details>
<br>
<details not-open>
<summary>Firefox</summary>

![ss_073](https://user-images.githubusercontent.com/46375428/51178395-b3285e00-18c2-11e9-86dc-ba3caede8e3b.png)

</details>
