### ISSUE TITLE
xerox.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#11267]
cookies

xerox.com/index/plpl.html

**Comment by krystian3w** [comment]
@hawkeye116477  - `###consent_blackbar` / `###truste-consent-track`

i chyba działa bezpiecznie `||consent.truste.com/notice?domain=xerox.com`.

**Comment by hawkeye116477** [comment]
Chyba tak

**Comment by krystian3w** [comment]
Ogólnie korzyści z tego truste są dopiero po zaakceptowaniu kliknięciem np. geolokalizacja na tej amerykańskiej `wunderground.com`.
