### ISSUE TITLE
dzdn.pl (2)

### ISSUE THREAD

**Issue by garrgul** [MajkiIT/polish-ads-filter#11262]
Social reopen https://github.com/MajkiIT/polish-ads-filter/issues/11144 bo dalej to jest, powiązane z https://github.com/MajkiIT/polish-ads-filter/issues/11254#issuecomment-454361684 i z  https://github.com/MajkiIT/polish-ads-filter/issues/11254#issuecomment-454368477.

**Comment by krystian3w** [comment]
@hawkeye116477  może jednak cofamy aż takie wycinanie? i w sumie co z tym linkiem z 
https://github.com/MajkiIT/polish-ads-filter/issues/11254#issuecomment-454361684
