### ISSUE TITLE
homebook.pl

### ISSUE THREAD

**Issue by garrgulowy** [MajkiIT/polish-ads-filter#11298]
Reopen RODO https://github.com/MajkiIT/polish-ads-filter/issues/11206 bo co prawda na Firefoxie usunięte, ale na Operze dalej jest.

**Comment by krystian3w** [comment]
No to dodam ukrywanie komunikatu CSS i może w dodatku dopisze się domenę.

**Comment by hawkeye116477** [comment]
@xxcriticxx Można już zamknąć :smile:
