### ISSUE TITLE
https://www.tempmailaddress.com/ [Incorrect Blocking]

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#11292]
### Screenshot
![image](https://user-images.githubusercontent.com/8361299/51244372-9dcc3600-198d-11e9-9181-ae2c7d0159a3.png)

### Direct link
https://www.tempmailaddress.com/

### What do you need to do to appear element, an ad or an error?
1. Just open the site

### My configuration
**Web browser:**

**Extensions and scripts:**

**Filter lists:**
1. EasyList
2. Official Polish Filters For AdBlock, uBlock Origin and AdGuard
3. 
4. 

**Other important informations that may be relevant (optional):**

**Comment by krystian3w** [comment]
Fixed in 2/3 hours in FilterRegistry.

https://github.com/MajkiIT/polish-ads-filter/blob/1d566db8fa0cb0eee3ce9e6da728fe223496693f/cookies_filters/adblock_cookies.txt#L1668
