### ISSUE TITLE
e-manufaktura.com (2)

### ISSUE THREAD

**Issue by garrgulowy** [MajkiIT/polish-ads-filter#11297]
Social reopen https://github.com/MajkiIT/polish-ads-filter/issues/11247 bo dalej to jest.

**Comment by krystian3w** [comment]
nie widzę, wyciąłem inne po PR, slider z lewej i jakiś dziwny button instagrama.

**Comment by garrgulowy** [comment]
Dziwne, też już u mnie nie ma, nawet po wyłączeniu uBO, więc chyba zmienili przed chwilą szatę, a teraz jest z kolei to:

![ss459](https://user-images.githubusercontent.com/46742966/51251429-9c086f80-1999-11e9-8381-77c8eefbd1ce.png)

Może to to samo, tylko w nowej szacie.
