### ISSUE TITLE
keybase.io

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#11291]
co myślicie o tym?

**Comment by MajkiIT** [comment]
W niektórych projektach używałem tego ... nawet niegłupie.

**Comment by hawkeye116477** [comment]
Trochę wyglądem przypomina chyba Messenger.
A z szyfrowanych jest jeszcze takie cudo => `https://about.riot.im/what-is-riot/#item5` albo `https://zulipchat.com/why-zulip`. 

A no właśnie, mamy Discorda, niby jest dobry, ale jednak ma wadę, że jest closed source.

**Comment by hawkeye116477** [comment]
@xxcriticxx Klepiemy trzy po trzy, to o tym, a to o tamtym :smiley: A ty tam byłeś w ogóle kiedyś, tylko wpadłeś i od razu wypadłeś, nie liczy się :stuck_out_tongue:

**Comment by xxcriticxx** [comment]
@MajkiIT włącz opcje żeby tylko contributors/collaborators mogli otwierać nowe tematy!

**Comment by krystian3w** [comment]
Nie bo potem jak znów coś wyłapie AdGuard błędnego to będą musieli wołać po nickach w ich tematach.

**Comment by xxcriticxx** [comment]
@krystian3w sprawa do przemyslenia

mozemy podlonczyc email pod bot czy cos podobnego

**Comment by hawkeye116477** [comment]
@xxcriticxx Zapraszamy na Discord, fotel Prezesa czeka :smiley:

**Comment by xxcriticxx** [comment]
@hawkeye116477 same as always

![capture](https://user-images.githubusercontent.com/15007183/51282892-66bd4b00-19b4-11e9-9d11-a5d85e6db03b.PNG)

**Comment by krystian3w** [comment]
Spróbuj nie przez Safari.

**Comment by hawkeye116477** [comment]
Powinno być git => `https://discord.me/polskiefiltry`. A to on ma MacOS?

**Comment by krystian3w** [comment]
Podobno zaproszenia nie działają w Safari, dziwny bug z strony discorda?
