### ISSUE TITLE
zlotyaniol.pl

### ISSUE THREAD

**Issue by garrgulowy** [MajkiIT/polish-ads-filter#11315]
Social ikony/przyciski:

1 po prawej u góry
![ss462](https://user-images.githubusercontent.com/46742966/51260624-fc55dc00-19ae-11e9-9385-d789c78f632b.png)

2 po lewej na dole
![ss463](https://user-images.githubusercontent.com/46742966/51260635-024bbd00-19af-11e9-8403-bed0c25f19cb.png)

**Comment by krystian3w** [comment]
@hawkeye116477  nie umiem namierzyć duszka CSS z grafiką fb, blogger, :telephone_receiver:.

By go dźgnąć w uBO/AdGuard.

**Comment by krystian3w** [comment]
I jak dla mnie stopka też skomplikowana, bo przerośnięty duszek CSS z newsletterem.

**Comment by krystian3w** [comment]
No to dobrze, że się nie siłowałem z tym wycinając na kilku stronach RSS, też miały duszki pod stopkę i tylko wyłączałem klikalność regułą składni ABP.

**Comment by krystian3w** [comment]
I ten drugi:

`zlotyaniol.pl/template/4/images/top.png`
