### ISSUE TITLE
bitcoinheavy.org

### ISSUE THREAD

**Issue by garrgulowy** [MajkiIT/polish-ads-filter#11332]
Social wielki baner na dole:

![ss479](https://user-images.githubusercontent.com/46742966/51262460-b4d14f00-19b2-11e9-8bab-687e71f9c990.png)

**Comment by krystian3w** [comment]
@hawkeye116477  nie ma to uchwytu, wycinać filtrami `:-abp-contains`?

**Comment by hawkeye116477** [comment]
@krystian3w Tak
