### ISSUE TITLE
enfamil.pl

### ISSUE THREAD

**Issue by garrgulowy** [MajkiIT/polish-ads-filter#11331]
Social widżet scrollujący po lewej:

![ss478](https://user-images.githubusercontent.com/46742966/51262404-953a2680-19b2-11e9-8e0a-6ff6d3924184.png)

**Comment by krystian3w** [comment]
`enfamil.pl##.legal-alert-popup-content, .legal-alert-popup-overlay`

czy ich pop-up to Cookies/RODO:


> Karmienie piersią jest najlepszym sposobem żywienia niemowląt. Karmienie sztuczne powinno następować w przypadku, gdy karmienie piersią jest niemożliwe lub utrudnione. Decyzja o zaprzestaniu karmienia piersią może być trudna do odwrócenia, a wprowadzenie częściowego karmienia butelką może zredukować ilość pokarmu u matki. Należy rozważyć korzyści finansowe związane z karmieniem piersią przed podjęciem karmienia butelką. Brak starannego przestrzegania instrukcji przygotowywania preparatu może być szkodliwy dla zdrowia dziecka. Pamiętaj, aby preparaty do początkowego żywienia niemowląt stosować wyłącznie po zasięgnięciu porady lekarza pediatry lub położnej. Na kolejnych stronach znajdują się informacje o mlekach początkowych firmy Mead Johnson Nutrition. **Decydując się na uzyskanie dostępu do tych informacji, przyjmujesz do wiadomości, że Mead Johnson Nutrition udostępnia te informacje na Twoje indywidualne życzenie w celach informacyjnych.**

@MajkiIT  / @xxcriticxx  / @hawkeye116477  / @blocker999  / @KonoromiHimaries
