### ISSUE TITLE
savicki.pl

### ISSUE THREAD

**Issue by garrgulowy** [MajkiIT/polish-ads-filter#11427]
Social ikony/przyciski na dole:

![ss534](https://user-images.githubusercontent.com/46742966/51367114-6377ab80-1ae9-11e9-964d-54be3b764969.png)

**Comment by krystian3w** [comment]
@MajkiIT / @hawkeye116477  strona sama się opróżnia po kilku sekundach, podobnie jak kiedyś w zgłoszeniu AdGuarda z https://github.com/AdguardTeam/AdguardFilters/issues/27711
