### ISSUE TITLE
mitsubishi.pl

### ISSUE THREAD

**Issue by garrgulowy** [MajkiIT/polish-ads-filter#11435]
Social ikony/przyciski na dole po lewej:

![ss544](https://user-images.githubusercontent.com/46742966/51367450-f9600600-1aea-11e9-94c9-ca64bf26a370.png)

**Comment by krystian3w** [comment]
`##.social.row > .columns > .beforeFooterMenu > li:not(:nth-of-type(5))`

jak w:

#11299
