### ISSUE TITLE
wiadomosci.onet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1143]
ad block 

http://wiadomosci.onet.pl/kraj/aplikacja-3ppr-na-sdm-w-krakowie/km2zge

![capture](https://cloud.githubusercontent.com/assets/15007183/17235131/6d1da73e-550c-11e6-827d-4e20685117ba.PNG)

**Comment by MajkiIT** [comment]
używasz listy AAK ?

**Comment by xxcriticxx** [comment]
tak
