### ISSUE TITLE
wyborcza.biz

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1146]
reklama play

![capture](https://cloud.githubusercontent.com/assets/15007183/17270384/5fea0bba-562f-11e6-9337-cc1131f58ae2.PNG)

**Comment by F4z** [comment]
Sprawdź tę regułę:
`||a.ib.gazeta.pl^$image`
Jeśli nie zadziała od razu, to wyczyść cache/cookie i sprawdź ponownie.

**Comment by xxcriticxx** [comment]
dziala wspaniale

**Comment by xxcriticxx** [comment]
ta sama reklama jest pod subdomain: 

http://www.blox.pl/
http://www.tokfm.pl/

**Comment by F4z** [comment]
Ok, ale ta reguła `||a.ib.gazeta.pl^$image` powinno działać również na tych stronach.
Nie działa?

**Comment by xxcriticxx** [comment]
moze i dziala ja dzisaj siedze na innym pc tutaj reguly niemam az @MajkiIT doda do listy

**Comment by MajkiIT** [comment]
ja tego nie widzę .

**Comment by F4z** [comment]
Ta reklama jest tylko czasami.

**Comment by MajkiIT** [comment]
Ok, to dodam jak wy ją widzicie.
