### ISSUE TITLE
wiadomosci.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1147]
adblock

http://wiadomosci.wp.pl/kat,1329,title,Papiez-poblogoslawil-malego-Szczepana-Jego-matka-przyszlismy-zrobic-zdjecie-dostalismy-bonus,wid,18446751,wiadomosc.html

http://wiadomosci.wp.pl/kat,1356,title,Sueddeutsche-Zeitung-dla-wielu-Polakow-papiez-jest-zbyt-liberalny-ws-uchodzcow,wid,18445811,wiadomosc.html?ticaid=117756

**Comment by MajkiIT** [comment]
masz aktualne filtry?

**Comment by xxcriticxx** [comment]
tak

**Comment by MajkiIT** [comment]
nadal masz ten problem?

**Comment by xxcriticxx** [comment]
nie zastosowalem fix z #1149
