### ISSUE TITLE
werandafamily.com

### ISSUE THREAD

**Issue by gargulcowaty** [MajkiIT/polish-ads-filter#11480]
Sociale  + przycisk:

![ss596](https://user-images.githubusercontent.com/46758818/51372094-5912dd00-1afc-11e9-9071-104a38f724b5.png)

**Comment by krystian3w** [comment]
Widzę tylko to instagram description...

**Comment by gargamelowy** [comment]
Nie wiem o jakie "instagram descrption" chodzi, czy mógłbyś dać zrzut ekranu.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/51442710-b450f500-1cdf-11e9-9505-e25eefc23628.png) | instagram description
--- |    ---

**Comment by krystian3w** [comment]
A linki mi znikają z lewego rogu po sekundzie, może sami twórcy nie umieją robić animacji CSS3/4

**Comment by krystian3w** [comment]
@hawkeye116477  wycinamy tak mocno im stronę, ja bym najwyżej zablokował klikalność w uBO w którym zaczytał się skrypt `remove-attr.js`.

**Comment by krystian3w** [comment]
_A i przewijania im nie uruchamiam, za skomplikowanie przyblokowali by go nie było i używać tego pomarańczowego koła._

**Comment by hawkeye116477** [comment]
No chyba raczej tylko klikalność, bo tak to wyjdzie goła i wesoła strona :smiley:.

**Comment by gargamelowy** [comment]
(generalne ta sama kwestia co opisana na dole pierwszego komentarza #11570 patrz **mini-galerie - unieszkodliwainie linków i innych elementów w zdjęciach**:)

**Comment by krystian3w** [comment]
@gargulcowaty  się nie łapie, grafiki się nie powiększają tutaj.

**Comment by gargamelowy** [comment]
Ja nic nie mówię, tylko referencję zrobiłem w celach informacyjnych.
