### ISSUE TITLE
dumeldiscovery.pl

### ISSUE THREAD

**Issue by gargulcowaty** [MajkiIT/polish-ads-filter#11499]
Social ikony/przyciski:

1 u góry
![ss617](https://user-images.githubusercontent.com/46758818/51373581-d2143380-1b00-11e9-9235-1c77fca9fd84.png)

2 na środku
![ss618](https://user-images.githubusercontent.com/46758818/51373597-d4768d80-1b00-11e9-8294-ec7cc23793be.png)

3 na dole
![ss619](https://user-images.githubusercontent.com/46758818/51373607-d80a1480-1b00-11e9-9aa0-e52e5397b483.png)

**Comment by krystian3w** [comment]
`.slick-slide` zamiast active / current.
