### ISSUE TITLE
telepolis.pl

### ISSUE THREAD

**Issue by gargulcowaty** [MajkiIT/polish-ads-filter#11494]
Social ikony/przyciski na dole:

![ss612](https://user-images.githubusercontent.com/46758818/51373157-be1c0200-1aff-11e9-9a07-2114a1c68d3b.png)

**Comment by krystian3w** [comment]
@hawkeye116477  a jak mu to przywraca np. `AdGuard Social Media` (wycinają tylko "widgety") to blokować kosmetycznie jakoś inaczej?

**Comment by hawkeye116477** [comment]
No chyba trzeba będzie, ale po co oni odblokowują.

**Comment by krystian3w** [comment]
Bo nie blokują linków odgórnie, o ile to znów nie zbugowana Opera, że strony migają, linki się nie klikają, wali errorami w konsoli developera.

**Comment by hawkeye116477** [comment]
`~ozracing.com,~byhours.com,~lumosity.com,~mvideo.ru,~zadowolenie.pl,~telepolis.pl,~transfermarkt.ch,~transfermarkt.at,~transfermarkt.co.uk,~transfermarkt.pl,~transfermarkt.nl,~transfermarkt.tv,~transfermarkt.it,~transfermarkt.com.tr,~transfermarkt.es,~transfermarkt.pt,~transfermarkt.com,~transfermarkt.de,~kompas.com,~hvv.de,~33sk.tv,~skrill.com,~neoldu.com,~leitesculinaria.com,~akhisarhaber.com,~eda.yandex,~mobillsapp.com,~itc.uam~autoscout24.de,~tokyohive.com,~teknolojioku.com,~popcrush.com,~tasteofcountry.com,~gardenista.com,~nauchpoint.com,~stasis.net,~kino.de,~entrepreneur.com,~jaxenter.de,~bilecikhaber.com.tr,~tvp.info,~tvp.pl,~androidpolice.com,~kingdomcomerpg.com,~canliradyodinle.web.tr,~dailycaller.com,~tvnz.co.nz,~pdc.tv,~redrivertravel.com,~lolking.net,~canon.de,~dawanda.com,~mcfit.com,~siemens.com,~actimel.de,~budapester.com,~yirmidort.tv,~volvic.de,~barmer.de,~wunderweib.de,~7up.com,~standard.co.uk,~basf.com,~godmode-trader.de,~thesun.co.uk,~howtogeek.com,~infranken.de,~developer.mozilla.org,~apkmirror.com,~gog.com,~dlisted.com,~tjournal.ru,~ain.ua,~aklamio.com,~cnnturk.com,~comediansincarsgettingcoffee.com,~forbes.com,~hubs.ua,~iguides.ru,~kicker.de,~logaster.com,~minfin.com.ua,~pexels.com,~t3n.de,~theverge.com,~deezer.com##.icon-facebook`

Nie rozumiem tego, lista Social powinna raczej też ukrywać ikony, a oni dali wyjątek.

**Comment by krystian3w** [comment]
No co za  :cow:  :cow2:  to AdGuard oblokowuje...

**Comment by krystian3w** [comment]
`telepolis.pl##a.icon-facebook, a.icon-twitter`

może takie coś.

**Comment by krystian3w** [comment]
@hawkeye116477  i to na `bugi_AdGuard.txt`?

**Comment by hawkeye116477** [comment]
@krystian3w Tak, może być.
@F4z Dlaczego odblokowałeś ikony/przyciski socialowe?

**Comment by krystian3w** [comment]
Już pisałem im linki nie przeszkadzają, tylko wycinają widgety.

**Comment by hawkeye116477** [comment]
Ale mają np. `marca.com##.icon-facebook` i jakoś nie widzę by czymś się to różniło. Także jakoś tak nie konsekwentnie.

**Comment by krystian3w** [comment]
Może dodał to ktoś na okresie próbnym i review przeszedł przypadkiem.

Jak oglądam jak szkolą nową osobę, to jakby jej nie dali żadnych porad co blokują co nie.

**Comment by krystian3w** [comment]
Jest też opcja, że ten przykład się zestarzał, oni raz do roku umieją usuwać filtr i potem przywracać.

**Comment by F4z** [comment]
>@F4z Dlaczego odblokowałeś ikony/przyciski socialowe?

Filtr mediów społecznościowych AdGuarda nie blokuje tego typu linków - https://kb.adguard.com/en/general/adguard-filter-policy#social-media-filter

Swoją drogą, jeśli są dwie oddzielne reguły, na przykład takie:
`~ozracing.com,~telepolis.pl,~deezer.com##.icon-facebook`
`##.icon-facebook`
to i tak to powinno być nadal zablokowane.

>Ale mają np. marca.com##.icon-facebook i jakoś nie widzę by czymś się to różniło. Także jakoś tak nie konsekwentnie.

To widocznie przypadek/niedopatrzenie, bo ta reguła blokuje też "lajki".

**Comment by hawkeye116477** [comment]
Ale w AG też chyba jest coś nie halo, bo mam włączony tylko podstawowy filtr i dodaje `##.icon-facebook` i nic, nadal mam ikonę, dopiero jak wpiszę `##a.icon-facebook`, to wtedy działa.

**Comment by krystian3w** [comment]
Ciekawe, na Firefox czegoś takiego nie miałem.

**Comment by gargamelowy** [comment]
Ja tylko dodam, że faktycznie to https://github.com/MajkiIT/polish-ads-filter/issues/11494#issuecomment-455880803 prawda, po wyłączeniu AdGuard Social Media filter i odświeżeniu strony przyciski social znikają, po włączeniu listy znowu się pojawiają, więc jeśli to wina AdGuard Social Media filter to nie wiem, czy zgłoszenie się w ogóle kwalifikuje tutaj, bo Polskie Filtry Społeczniościowe bazują tylko na Fanboy’s Social Blocking List, chociaż z drugiej strony może to być wina jakiejś innej listy, albo jak tu sugerowano adblockera lub przeglądarki, więc to do ewentualnej decyzji co z tym zgłoszeniem dalej zrobić.

**Comment by krystian3w** [comment]
To jest z winy listy AdGuard Social Media i ich polityki blokowania elementów społecznościowych.

**Comment by F4z** [comment]
>Ale w AG (Chromium) też chyba jest coś nie halo, bo mam włączony tylko podstawowy filtr i dodaję ##.icon-facebook i nic, nadal mam ikonę, dopiero jak wpiszę ##a.icon-facebook, to wtedy działa.

U mnie ten przycisk na dole znika, jeśli chodzi o przycisk na górze po prawej, to on ma `display: inline!important;`, więc w przypadku AdGuarda trzeba by było użyć reguły z wyższym priorytetem.

**Comment by krystian3w** [comment]
Znaczy jak:

> 
> A już wiem znowu jakaś limitacja AdGuarda (już o tym pisałem) - nie umie on negować `display: block !important` (i tym podobnych) w Chromium.
> 
> ![image](https://user-images.githubusercontent.com/35370833/42311948-52f4e33a-803f-11e8-9a58-5d2ed5d6aac4.png) |
> --- |
> 
> ---
> 
> * https://codepen.io/anon/pen/aKBvRq - demo 1, nie można przy pomocy AdGuarda w Chromium odkryć elementu jak ma w stylu zewnętrznym CSS `!important`.
> 
> * https://codepen.io/anon/pen/QxRQQM - demo 2, z sytuacją jak na `focus.pl` - ukryj coś co wymusza strona jako widoczne w Chromium. 
> 
> Niestety nie umiem tego znaleźć w ich repozytoriach jako ograniczenie i czy są w stanie to jakoś naprawić.

**Comment by krystian3w** [comment]
Na demach nie umiem zablokować lub odblokować ukrytego elementu.

---

http://raymondhill.net/ublock/adbox.html

**Comment by F4z** [comment]
Możesz użyć:
`raymondhill.net#?#.ADBox`
ewentualnie:
`raymondhill.net#$#.ADBox { position: absolute!important; left: -3000px!important; }`


>demo 1, nie można przy pomocy AdGuarda w Chromium odkryć elementu jak ma w stylu zewnętrznym CSS !important.

`s.codepen.io#$?#ul > li > p { display: block !important; }`

>demo 2, z sytuacją jak na focus.pl - ukryj coś co wymusza strona jako widoczne w Chromium.

Tak samo jak z `.ADBox`

**Comment by krystian3w** [comment]
Czyli ukrytych userCSS dla "kumatych"?

**Comment by krystian3w** [comment]
Trzeba to zaproponować jspenguin2017 :penguin: może.

**Comment by gwarser** [comment]
> @gwarser:
> 
> > > Swoją drogą, jeśli są dwie oddzielne reguły, na przykład takie:
> > > `~ozracing.com,~telepolis.pl,~deezer.com##.icon-facebook`
> > > `##.icon-facebook`
> > > to i tak to powinno być nadal zablokowane
> > 
> > 
> > No to w takim razie, to jest bug uBO, bo po wprowadzeniu tych reguł jest tak, że się to odblokowuje, natomiast w ABP widzę, że nie ma tego problemu.
> 
> Tak by nie pytać na razie na reddit lub nie zgłaszać coś co nie jest bugiem.

Pamiętam coś takiego. Muszę poszukać.

**Comment by krystian3w** [comment]
Powodzenia.

**Comment by gargamelowy** [comment]
> natomiast w ABP widzę, że nie ma tego problemu.

https://arestwo.org/famlam/redundantRuleChecker.html również pokazuje tak jak w ABP:

Finished (after 1 second)!  1 redundant rule found!
`~www.telepolis.pl##.icon-facebook` has been made redundant by `##.icon-facebook`

a nie w drugą stronę, więc chyba błąd w uBO, a jeśli tak to błąd stary jak świat bo jest nawet na wersji z prawie przed roku (1.15.2).

**Comment by krystian3w** [comment]
Możesz sprawdzić na wersji krisa (0.9.x) i wyjdzie, że błąd ma z 4 lata.

**Comment by gargamelowy** [comment]
Już mi się nie chciało sprawdzać, ale jeśli błąd jest faktycznie aż tak stary, jak sam uBlock ,to aż dziwne, że nikt wcześniej go nie zauważył, to chyba treba szampana otworzyć, i toast wznieść, że taki zabytkowy błąd odkryto, odkrycie nr 2 zaraz za odkryciem Ameryki przez Krzysztofa Kolumba.

**Comment by gwarser** [comment]
Specyficzność albo trick z przecinkiem: `telepolis.pl##.icon-facebook,cokolwiek`,
`telepolis.pl##a>.icon-facebook`.

**Comment by krystian3w** [comment]
To mamy oba w jednym.



> 
> 
> `telepolis.pl##a.icon-facebook, a.icon-twitter`
> 
> może takie coś.

**Comment by gwarser** [comment]
`telepolis.pl##.icon-facebook.icon-facebook` też powinno działać.

Poprostu uBO odrzuca duplikaty i traktuje `~domena##` tak samo jak `domena#@#`

**Comment by krystian3w** [comment]
No to już wiem skąd, trudno.

**Comment by krystian3w** [comment]
Najgorzej będzie, jak `AGSMF` będzie aktualizowany co aktualizacja polskiej listy społecznościowej.

W takim wypadku już wolę informacje, że lista cookies wycina coś za dużo i trzeba to poprawić.

**Comment by hawkeye116477** [comment]
Ok, to w takim razie uznajemy, że ci co mają AG Social to nie będą chcieli ukrywać takich ikon :smile:.

**Comment by krystian3w** [comment]
Unsub!

**Comment by gwarser** [comment]
ABP ma odwrotny problem, ukrywa za dużo: https://issues.adblockplus.org/ticket/5665

Jak ktoś chce, to niech zrobi zgłoszenie w uBlock-issues, to się tam podsumuje i wrzuci obejścia wszystkie. Jak nie, to sam później zrobię.

**Comment by krystian3w** [comment]
Ja tam nie zgłaszam bo jeszcze bana dostanę, że literówki na reddicie wytykam.

**Comment by gwarser** [comment]
@krystian3w jakie tam literówki, luki bezpieczeństwa znajdujesz! Jakies bug bounty by się przydało :smile:

**Comment by krystian3w** [comment]
Ostanio zwróciłem Raymondowi uwagę, że napisał `coam` w url, może się obraził (ale poprawił).

**Comment by gwarser** [comment]
Jakiś dziwny problem mam na forum - po sekundzie strona robi się biała. Nawet jak dodam na białą listę, to przekierowuje mnie na doubleclick a potem na comperia:

![image](https://user-images.githubusercontent.com/886325/62707500-c3845f80-b9f1-11e9-8e56-48994bd5512e.png)

**Comment by hawkeye116477** [comment]
@gwarser Utwórz nowe zgłoszenie, bo @MajkiIT nie czyta zamkniętych.

**Comment by gwarser** [comment]
Raczej nieważne. Nawet bez adblockera przekierowuje mnie na stronę z reklamą, która ładuje się wiecznie:

![image](https://user-images.githubusercontent.com/886325/62708443-b6687000-b9f3-11e9-9e1d-232270b7d7bc.png)

**Comment by hawkeye116477** [comment]
@gwarser `telepolis.pl##+js(abort-on-property-write.js, m3_u)`

**Comment by krystian3w** [comment]
Chyba zrezygnowano z:

 `~ozracing.com,~telepolis.pl,~deezer.com##.icon-facebook`
"`~ozracing.com,~telepolis.pl,~deezer.com##.icon-twitter`"

w AdGuard Social Media.
