### ISSUE TITLE
maciejowka.org

### ISSUE THREAD

**Issue by gargulcowaty** [MajkiIT/polish-ads-filter#11506]
Social ikony/przyciski na dole po prawej:

![ss625](https://user-images.githubusercontent.com/46758818/51374072-1eac3e80-1b02-11e9-80ea-8d80093d5d43.png)

**Comment by krystian3w** [comment]
`##.copyrights .wpv-first-level a:nth-of-type(-n+2) > .icon`

Czyli tekstu nie da się wyciąć i zostawiam ikonę aplikacji na telefon i wyszukiwarkę.
