### ISSUE TITLE
poradnik-seo.pl

### ISSUE THREAD

**Issue by gargulcowaty** [MajkiIT/polish-ads-filter#11513]
Social ikona/przycisk na dole po prawej:

![ss632](https://user-images.githubusercontent.com/46758818/51374870-9713ff00-1b04-11e9-92ca-39de9441b8e4.png)

**Comment by krystian3w** [comment]
te "Team" przywraca AdGuard?

Pod opisami panów.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/51444048-92ad3900-1cf2-11e9-8d42-65d54a291820.png) |
--- |

**Comment by gargamelowy** [comment]
Nie, bez AdGuard Social Media filter też są.
