### ISSUE TITLE
polish-ads-filter w Adguard

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1151]
@F4z adguard my na stacku nasz polskie fitry bo cos nie widze na github?

**Comment by F4z** [comment]
Nie wiem czy dobrze zrozumiałem pytanie, ale po instalacji Adguarda polskie filtry są automatycznie włączone (przynajmniej u mnie), a oprócz tego są dostępne na liście do wyboru.
![image](https://cloud.githubusercontent.com/assets/11742596/17277203/65b79166-573d-11e6-84c8-34b25784d270.png)

**Comment by xxcriticxx** [comment]
cookies sam dodales? czy byly?

**Comment by F4z** [comment]
Były.

**Comment by xxcriticxx** [comment]
ok to hyba zostaly dodane jak prosilem
