### ISSUE TITLE
mbp.opole.pl

### ISSUE THREAD

**Issue by gargulcowaty** [MajkiIT/polish-ads-filter#11520]
Sociale linki na dole po prawej:

![ss639](https://user-images.githubusercontent.com/46758818/51375476-41d8ed00-1b06-11e9-986d-112b4a018cd8.png)

**Comment by hawkeye116477** [comment]
No teraz to chyba naprawdę po złości, ile tego jeszcze dzisiaj będzie 100 więcej?

**Comment by gargulcowaty** [comment]
Nie po złości, człowieku, powtarzasz to samo jak on, wrzucam z pasji, już koniec nic więcej nie będzie póki co.

**Comment by krystian3w** [comment]
#11400 - do tylu dojechałem jak coś.
