### ISSUE TITLE
kkslech.com

### ISSUE THREAD

**Issue by gargulcowaty** [MajkiIT/polish-ads-filter#11530]
Sociale po prawej:

![ss649](https://user-images.githubusercontent.com/46758818/51376229-1ce57980-1b08-11e9-9a6b-4e0a21571155.png)

**Comment by hawkeye116477** [comment]
@MajkiIT Mnóstwo resztek po reklamach.
@xxcriticxx Dorzuć label reklama.

**Comment by gargamelowy** [comment]
Screeny tych resztek (nagłówki reklam):

![ss658](https://user-images.githubusercontent.com/46759102/51443364-21688880-1ce8-11e9-99be-ed5e387427f2.png)
![ss659](https://user-images.githubusercontent.com/46759102/51443365-21688880-1ce8-11e9-95c5-bfe2ef7558d0.png)
![ss660](https://user-images.githubusercontent.com/46759102/51443366-22011f00-1ce8-11e9-9c6e-c65f68551227.png)
![ss661](https://user-images.githubusercontent.com/46759102/51443367-22011f00-1ce8-11e9-9da6-4cab5042cb16.png)
![ss662](https://user-images.githubusercontent.com/46759102/51443368-2299b580-1ce8-11e9-999f-8211ffcca18b.png)
![ss663](https://user-images.githubusercontent.com/46759102/51443369-2299b580-1ce8-11e9-9a21-b8eb0b12523f.png)

**Comment by krystian3w** [comment]
*   proceduralnymi filtrami:

   `kkslech.com#?#.widget_text.widget:-abp-has(>h3:-abp-contains(Reklama))`

     I można uprościć do (sprawdzanie czy tekst jest w h3 nadmiarowe):

    `kkslech.com#?#.widget_text.widget:-abp-contains(Reklama)`

     ---

*  Lub po ID:

   `kkslech.com###text-36, #text-52, #text-47, #text-61, #text-41, #text-53`
