### ISSUE TITLE
ridgid.eu/pl/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#11538]
JAK KORZYSTAMY Z PLIKÓW COOKIE: Korzystamy z plików cookie i podobnych technologii w celu doskonalenia naszej strony internetowej, personalizacji treści znajdujących się na stronie oraz wyświetlania reklam i ofert zawierających treści, które mogą zainteresować użytkownika. Bardziej szczegółowe informacje na temat sposobów wykorzystywania przez nas plików cookie można znaleźć w naszej Informacji dotyczącej plików cookie. Rozumiem i nie pokazuj tego komunikatu ponownie. Kliknij X, aby zamknąć ten komunikat.

**Comment by krystian3w** [comment]
`ridgid.eu##.cookie-warning`
