### ISSUE TITLE
interpretacje-podatkowe.org

### ISSUE THREAD

**Issue by gargulcowaty** [MajkiIT/polish-ads-filter#11533]
Social ikona/przycisk u góry po prawej:

![ss652](https://user-images.githubusercontent.com/46758818/51376399-836a9780-1b08-11e9-8d8e-b4ee959d47bc.png)

**Comment by hawkeye116477** [comment]
Link wytniemy, ale ikona niestety musi zostać, bo to sprite, złączone razem z RSS, ale jako, że w Fitlrach RSS mieliśmy założenie, że wycinamy nawet z socialem, jeśli zostaje resztka, to tak też zrobimy w RSS :smile:.
