### ISSUE TITLE
targeo.pl, mapa.targeo.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#11537]
brak rozwijanych list miast i ulic i przyciskow, na stronach targeo.pl i mapa.targeo.pl

**Comment by krystian3w** [comment]
@MajkiIT  - cookies, nie social i możesz dodać etykietę "błąd".

**Comment by krystian3w** [comment]
`targeo.pl#@#body > div:not([id]):not([class])[style^="position: absolute;"]`

tymczasowo aż nie będzie poprawki w listach cookies @lukjan32

**Comment by lukjan32** [comment]
ok, czekam

**Comment by lukjan32** [comment]
dzieki, jeszcze brakuje przycisku, na stronie glownej :(

**Comment by krystian3w** [comment]
Daj zdjęcie

**Comment by krystian3w** [comment]
`targeo.pl#@#A[target="_blank"] > IMG`

@MajkiIT / @hawkeye116477  są tam jakieś reklamy jeszcze

**Comment by lukjan32** [comment]
tak, to

**Comment by krystian3w** [comment]
To już majki it zaakceptował odblokowanie.

**Comment by lukjan32** [comment]
aha
