### ISSUE TITLE
mapa.targeo.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1154]
Reklamy - `https://mapa.targeo.pl/Warszawa%20%20,26,20.8206329,52.2406311?data=eyJmdHMiOnsicSI6IldhcnN6YXdhICAiLCJlIjoiYWRyZXMtNDc5NzIyNCJ9LCJ3aW4iOiJzZWFyY2gtZm9ybSJ9`

![image](https://cloud.githubusercontent.com/assets/11742596/17302143/1fa38be2-581b-11e6-8cd8-91aa6ce6e353.png)

Na przykład:
`mapa.targeo.pl###bblbrd_outer`
`mapa.targeo.pl###ftswin_outer`
Ewentualnie to:
`||news.targeo.pl/oarm.php$xmlhttprequest,domain=mapa.targeo.pl`

**Comment by MajkiIT** [comment]
Dziękuje. Dodane.
