### ISSUE TITLE
Multi Social Reopen - klepanie blachy/szlifierka poweekendowa.

### ISSUE THREAD

**Issue by gargamelowy** [MajkiIT/polish-ads-filter#11570]
(Social) Skoro zgłoszenia zostały już pozakładane, to nie ma sensu na nowo robić osobno reopenów dla każdego zgłoszenia, więc mini wątek zbiorczy z listą zgłoszeń social z tego weekendu, które wymagają poprawek/doszlifowania/doklepania blachy, bo zostały nienaprawione bo przegapione albo błędnie/niekompletnie naprawione, albo ja przegapiłem coś jeszcze do zgłoszenia (jeśli możliwe to dyskusje należy kontynuować w poszczególnych zgłoszeniach):

Reopeny - bo dalej to jest: 

https://github.com/MajkiIT/polish-ads-filter/issues/11356, 
https://github.com/MajkiIT/polish-ads-filter/issues/11378, 
https://github.com/MajkiIT/polish-ads-filter/issues/11387, 
https://github.com/MajkiIT/polish-ads-filter/issues/11401, 
https://github.com/MajkiIT/polish-ads-filter/issues/11404, 
https://github.com/MajkiIT/polish-ads-filter/issues/11498 w tym dodatkowo znalazłem ikonę social u góry po lewej, którą wcześniej przegapiłem: 
![ss664](https://user-images.githubusercontent.com/46759102/51461931-a2169b80-1d5f-11e9-8535-d93945da55e0.png), 
https://github.com/MajkiIT/polish-ads-filter/issues/11461 w tym został usunięty tylko napis, a ikona została,
https://github.com/MajkiIT/polish-ads-filter/issues/11473 w tym została ikona Twittera (screenshoot 2),
https://github.com/MajkiIT/polish-ads-filter/issues/11495 na Operze usunięte, ale na Firefoxie dalej to jest

Reopeny - bo ja przegapiłem coś jeszcze do złgoszenia:

https://github.com/MajkiIT/polish-ads-filter/issues/11475 przegapiłem ikonę social u góry po prawej
![ss665](https://user-images.githubusercontent.com/46759102/51462613-5a910f00-1d61-11e9-8897-f0d4ba813ce8.png)
https://github.com/MajkiIT/polish-ads-filter/issues/11499, namyśliłem się i stwierdziłem, że jednak link też do zgłoszenia: [screenshoot](https://user-images.githubusercontent.com/46759102/51462923-210cd380-1d62-11e9-9e72-f464b1b9434c.png),
https://github.com/MajkiIT/polish-ads-filter/issues/11373  przegapiłem taki sam element (a raczej kontener z nagłówkiem po nim) tylko, że statyczny: [screenshoot 1](https://user-images.githubusercontent.com/46759102/51463104-af815500-1d62-11e9-8684-13726cb734a1.png), [screenshoot 2](https://user-images.githubusercontent.com/46759102/51463105-af815500-1d62-11e9-9a21-2f41a3468843.png),

**mini-galerie - unieszkodliwainie linków i innych elementów w zdjęciach:**
https://github.com/MajkiIT/polish-ads-filter/issues/11470 przegapiłem kontener social ze zdjęciami:
[screenshoot 1](https://user-images.githubusercontent.com/46759102/51466700-186ccb00-1d6b-11e9-8287-cf3668eee9dd.png), [screenshoot 2](https://user-images.githubusercontent.com/46759102/51466702-19056180-1d6b-11e9-918d-2f293a268840.png) - chodzi żeby wyciąć te czaty social ze screenshoota 2 oraz ze screenshoota 1 po najechaniu kursorem na miniaturę, - żeby tylko nie wycinać żadnych zdjęć
https://github.com/MajkiIT/polish-ads-filter/issues/11468 zgłaszam do poprawki - do przywrócenia, bo zdjęcia zostały wycięte - cofam zgłoszenie, myślałem że prowadzą do strony social, ale po kliknięcu otwiera się powiększone zdjęcie, więc zwyczajna galeria, nie ma po co wycinać.

**Comment by krystian3w** [comment]
[born86.pl scr 2](https://user-images.githubusercontent.com/46759102/51466700-186ccb00-1d6b-11e9-8287-cf3668eee9dd.png) - nie umiem naprawić, więc nie wycinam po powiększeniu.

**Comment by gargamelowy** [comment]
Hmm, dziwne, przecież ten filtr co na screenshocie działa:

![ss_004](https://user-images.githubusercontent.com/46759102/51470354-f0ce3080-1d73-11e9-99cf-275cba7fa4cb.png)

**Comment by krystian3w** [comment]
Białe pole może dezorientować.

**Comment by garrggul** [comment]
> gargamelowy: #11499, namyśliłem się i stwierdziłem, że jednak link też do zgłoszenia: screenshoot,

<details not-open>
<summary>Link został usunięty, ale gdy przesunie się karuzelę to jest jeszcze drugi link:</summary>


![anim](https://user-images.githubusercontent.com/46904255/51558563-0c266200-1e80-11e9-8450-2f53c63711d8.gif)

</details>
