### ISSUE TITLE
auto50.pl

### ISSUE THREAD

**Issue by gargamelowy** [MajkiIT/polish-ads-filter#11574]
Social widżet scrollujący po prawej:

![social](https://user-images.githubusercontent.com/46759102/51467241-5e765e80-1d6c-11e9-97b3-c7ba318e5e14.gif)

**Comment by krystian3w** [comment]
@gargamelowy  ja nie mam, znowu AdGuard przypadkiem odblokował i uBO przepuścił?

**Comment by gargamelowy** [comment]
Nie, mam to nawet bez AdGuarda, zarówno na Firefoxie jak i na Operze, a powiedzmi, który filtr ci wycina blokuje i z jakiej listy?

**Comment by krystian3w** [comment]
A jakiś z :poland: EI, niestety tam nie lubi się nic "sticky" / "fixed".

**Comment by gargamelowy** [comment]
Jeszcze coś się ostało (nawet bez AdGuard, na obydwu przeglądarkach):

![ss691](https://user-images.githubusercontent.com/46759102/51476516-0cdacd80-1d86-11e9-9089-0173c1537884.png)

**Comment by krystian3w** [comment]
a za dużo mają, to nie wyciąłem instagrama.

**Comment by gargamelowy** [comment]
No ok, jak chcesz, więc lusterko zostaje.
