### ISSUE TITLE
sebucja.pl 

### ISSUE THREAD

**Issue by gargamelowy** [MajkiIT/polish-ads-filter#11576]
Social:

### 1: dwie takie same mini galerie ze zdjęciami jedna po prawej, druga na dole:

<details not-open>
<summary>galeria 1a na dole do wycięcia razem z napisem social - generalnie cały wielki kontener na dole do wycięcia</summary>

![ss_003](https://user-images.githubusercontent.com/46759102/51469026-97183700-1d70-11e9-8e76-1a9aa1b2eb15.png)

</details>
<br>

<details not-open>
<summary>galeria 1b po prawej do zostawienia, tylko linki w zdjęciach do unieszkodliwienia (generalne ta sama kwestia co opisana na dole pierwszego komentarza #11570 patrz **mini-galerie - unieszkodliwainie linków i innych elementów w zdjęciach**:)</summary>

![ss676](https://user-images.githubusercontent.com/46759102/51468635-c7aba100-1d6f-11e9-8221-76a0efa429d4.png)

</details>
<br>

### 2: kontener z nagłówkiem po prawej
![ss677](https://user-images.githubusercontent.com/46759102/51468833-2c66fb80-1d70-11e9-8a45-468194a18fab.png)

**Comment by krystian3w** [comment]
@gargamelowy to jak z tą galerią, jak mamy być konsekwentni to ona traci title i podkreślenie pod title i tyle...

chyba, że ja już nie rozumiem ratowania tego widgetu...

**Comment by krystian3w** [comment]
@hawkeye116477  a ty co myślisz, strona nie będzie "głowa".

**Comment by hawkeye116477** [comment]
Ja bym wyciął obie galerie całe.

**Comment by krystian3w** [comment]
Dobra, czyli oszczędzamy gdy się nie da ominąć białych dziur / psucia karuzel z grafikami (skakanie, kompletna dezaktywacja karuzeli w wyniku uszkodzenia kodu, białe dziury).
