### ISSUE TITLE
przedsiebiorcza.com 

### ISSUE THREAD

**Issue by gargamelowy** [MajkiIT/polish-ads-filter#11575]
Social 

1: zdjęcia na dole strony - trzeba linki unieszkodliwić (nie wycinać zdjęć) - zgłoszenie generalne ta sama kwestia co tutaj opisana na dole pierwszego komentarza https://github.com/MajkiIT/polish-ads-filter/issues/11570 patrz **mini-galerie - unieszkodliwainie linków i innych elementów w zdjęciach**:

![ss674](https://user-images.githubusercontent.com/46759102/51467635-4fdc7700-1d6d-11e9-8623-d50c7ec6d849.png)

2: ikony/przyciski social pod artykułami: 
http://przedsiebiorcza.com/2017/10/przedsiebiorcze-w-swiecie-mody-portphonetka/

![ss445](https://user-images.githubusercontent.com/46759102/51477656-6f819880-1d89-11e9-926e-9360ad93000c.png)

![ss692](https://user-images.githubusercontent.com/46759102/51477578-2d585700-1d89-11e9-9e80-5c063e040356.png)

**Comment by krystian3w** [comment]
@gargamelowy to tu też bym wyciął, raczej stroje autorki nie są za bardzo fascynujące by je oglądać jak nie robi wpisu.

**Comment by gargamelowy** [comment]
OK, jak chcecie.

**Comment by gargamelowy** [comment]
Zauważyłem teraz jeszcze ikony/przyciski social pod artykułami - edytowałem pierwszy komentarz.

**Comment by krystian3w** [comment]
`##.author-social-profile`

**Comment by gargamelowy** [comment]
Działa.

**Comment by krystian3w** [comment]
`##.author-social-profile > .author-icons > [class]:not(.wordpress)` 

niby ikona odsyła na głowną.
