### ISSUE TITLE
prostowsmak.com 

### ISSUE THREAD

**Issue by gargamelowy** [MajkiIT/polish-ads-filter#11578]
Social:

1: galeria na dole linki w zdjęciach  do unieszkodliwienia (generalne ta sama kwestia co opisana na dole pierwszego komentarza #11570 patrz **mini-galerie - unieszkodliwainie linków i innych elementów w zdjęciach**:)

![ss682](https://user-images.githubusercontent.com/46759102/51469799-76e97780-1d72-11e9-8ead-c78875467ae5.png)

2: resztki po prawej:

![ss681](https://user-images.githubusercontent.com/46759102/51469733-57eae580-1d72-11e9-8b2b-3c1132f6cd56.png)

**Comment by gargamelowy** [comment]
referencja https://github.com/MajkiIT/polish-ads-filter/issues/11570

**Comment by gargamelowy** [comment]
OK, na chwilę obecną wszystkie zgłoszenia aż do #11580 włącznie, zrobione.

**Comment by gargamelowy** [comment]
OK, na chwilę obecną wszystkie zgłoszenia aż do #11580 włącznie, zrobione.

**Comment by krystian3w** [comment]
Ja mam nadzieje, że dobrze wyciąłem mini galerie, które nie są potrzebne (nie robią luk jak na #11480)

**Comment by gargamelowy** [comment]
Komentarz zbiorczy dla mini-galerii:

Zrobione (stare): ~#11468, #11470, #11480, #11580, #11575, #11576, #11578~
Niezrobione (nowe): #11582, #11583, #11584
