### ISSUE TITLE
swedish-princesses.pl

### ISSUE THREAD

**Issue by gargamelowy** [MajkiIT/polish-ads-filter#11580]
Social

1: mini-galeria na samym dole - linki w zdjęciach do unieszkodliwienia (generalne ta sama kwestia co opisana na dole pierwszego komentarza #11570 patrz **mini-galerie - unieszkodliwainie linków i innych elementów w zdjęciach**)
![ss685](https://user-images.githubusercontent.com/46759102/51471629-933be300-1d77-11e9-837a-f90012871b03.png)

2: resztki po prawej
![ss686](https://user-images.githubusercontent.com/46759102/51471643-9a62f100-1d77-11e9-8cb4-d9e82ca71fa0.png)

3: social po prawej:
![ss687](https://user-images.githubusercontent.com/46759102/51473651-3f33fd00-1d7d-11e9-8e60-ebe9ec944f49.png)

4 resztki na dole:
![ss688](https://user-images.githubusercontent.com/46759102/51474461-b5d1fa00-1d7f-11e9-8814-ccce5ba81aba.png)

**Comment by krystian3w** [comment]
`swedish-princesses.pl###Image1.widget, #HTML1, #HTML4, #HTML5`
