### ISSUE TITLE
HostsMan

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1159]
http://www.dobreprogramy.pl/Blokowanie-reklam-MS-Edge,Blog,74406.html

http://www.softpedia.com/get/Network-Tools/Misc-Networking-Tools/HostsMan.shtml

**Comment by azet12** [comment]
Edge już chyba obsługuje wtyczki w najnowszym updejcie win10, w tym adblock i adblock plus, ale program fajny.

**Comment by xxcriticxx** [comment]
moze sie przydac
