### ISSUE TITLE
faniperfum.pl 

### ISSUE THREAD

**Issue by gargamelowy** [MajkiIT/polish-ads-filter#11597]
Reklama na środku:

![ss465](https://user-images.githubusercontent.com/46759102/51489510-d3678980-1da8-11e9-93d4-04bd08bd175b.png)

**Comment by krystian3w** [comment]
Ja mam reklamę dalej, a przycisku logowania nie wycinam, chyba że im padła aplikacja i już się nie da logować fejsbukiem by kupić pachnidło?
