### ISSUE TITLE
klassikauto.pl

### ISSUE THREAD

**Issue by gargamelowy** [MajkiIT/polish-ads-filter#11593]
Sociale:

1 po prawej puste kontenery z nagłówkami:
![ss459](https://user-images.githubusercontent.com/46759102/51489043-70292780-1da7-11e9-9fda-bd32419f0b36.png)

2 na dole panel z linkami:
![ss460](https://user-images.githubusercontent.com/46759102/51489054-761f0880-1da7-11e9-8253-ad9a5158216e.png)

**Comment by garrggul** [comment]
Te "1 po prawej puste kontenery z nagłówkami" dalej są.

**Comment by krystian3w** [comment]
`###custom_html-3, #text-17, #text-18`
