### ISSUE TITLE
www.epiotrkow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#116]
anti ad block 

Korzystasz z dodatku AdBlock i ingerujesz jednocześnie w treść strony.

Wyłącz blokowanie na epiotrkow.pl, aby korzystać z wszystkich funkcji portalu i wyłączyć ten komunikat.

**Comment by MajkiIT** [comment]
https://github.com/reek/anti-adblock-killer/issues/842
