### ISSUE TITLE
kinonet.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#11611]
https://kinonet.pl/seriale-online/Tajemnice_Smallville/s10e3/Odcinek__/21062
Adblock
![image](https://user-images.githubusercontent.com/29756590/51503607-2c044a00-1ddc-11e9-91a6-16cb94a69eb6.png)

**Comment by MajkiIT** [comment]
`@@||kinonet.pl^$generichide`
