### ISSUE TITLE
zdrowemiasto.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#11612]
Reklamy w artykułach, np tu : http://www.zdrowemiasto.pl/i/13/szepty/suplementy-witamin-w-formie-estru,7577.html

**Comment by krystian3w** [comment]
`##div[style] small, center > a  > img`

Ale takie jakieś plebsowe.

**Comment by krystian3w** [comment]
```
zdrowemiasto.pl###headBanner:style(visibility: hidden !important;)
```

**Comment by MajkiIT** [comment]
@KonoromiHimaries twoje ?

**Comment by krystian3w** [comment]
@MajkiIT  `www.zdrowemiasto.pl###headBanner:style(visibility: hidden !important;)` to raczej można u nas dodać
