### ISSUE TITLE
national-geographic.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1161]
adblock

http://www.national-geographic.pl/galeria/wspieramy-polskich-paraolimpijczykow-we-wrzesniu-ruszaja-igrzysk/wspieramy-polskich-paraolimpijczykow-z-londynu-przywiezli-praw-3

![capture](https://cloud.githubusercontent.com/assets/15007183/17457696/74521676-5bcd-11e6-9152-eb3899f5ff85.PNG)

**Comment by F4z** [comment]
Sprawdź tę regułę: `@@||national-geographic.pl/bundles/burdacore/js/adv.js$script`

Na górze, nad galerią zostanie pusta przestrzeń po reklamie.
Nie widzę zbytnio możliwości usunięcia tego zwykłą regułą żeby nie uciąć obrazka i kawałka tekstu (ale może za słabo szukałem), bo po użyciu tej reguły `national-geographic.pl##.advertising-billboard`, u mnie wygląda to tak:
![image](https://cloud.githubusercontent.com/assets/11742596/17457985/e8e2702a-5c05-11e6-8d01-e6979133a48d.png)
Czyli jest źle.

Natomiast jeśli korzystasz z uBlocka Origin i masz wersję 1.8.0 lub wyższą, to możesz spróbować tego: `national-geographic.pl##.advertising-billboard:style(height: 0px!important;)`
Powinno być ok.

**Comment by xxcriticxx** [comment]
z element picker

||www.national-geographic.pl/bundles/burdamedia/images/adblock.jpg

###adoceanmyaordcsmkgudz
##.advertising-billboard

**Comment by xxcriticxx** [comment]
kaka z national-geographic.pl##.advertising-billboard:style(height: 0px!important;)

![capture](https://cloud.githubusercontent.com/assets/15007183/17458121/1c6087a4-5bd7-11e6-99a9-b8bc3ccf8863.PNG)

**Comment by F4z** [comment]
Te dwie reguły są potrzebne:
`@@||national-geographic.pl/bundles/burdacore/js/adv.js$script`
`national-geographic.pl##.advertising-billboard:style(height: 0px!important;)`

**Comment by xxcriticxx** [comment]
bingo! dziala

**Comment by MajkiIT** [comment]
@F4z A nie lepiej tak.... www.national-geographic.pl##.advertising-billboard

**Comment by xxcriticxx** [comment]
testuje

**Comment by xxcriticxx** [comment]
obrazek za wysoko scina
![capture](https://cloud.githubusercontent.com/assets/15007183/17458443/67e6b8fe-5bde-11e6-9b6a-a45855051303.PNG)

**Comment by MajkiIT** [comment]
@F4z dzięki dodałem i sprawdzimy jak to będzie działać. Tworzenie 2 list spowoduje chaos, bo ludzie nie będą do końca wiedzieć co dodawać.

**Comment by F4z** [comment]
Ok, dzięki.
Tylko wydaje mi się, że w przypadku użytkowników Adblock/Adblock Plus może być tak, że strona będzie się źle wyświetlać, albo będą jakieś inne problemy.
Dlatego zaproponowałem stworzenie oddzielnej listy.

**Comment by MajkiIT** [comment]
No właśnie widzę, że działa to średnio, ale coś wymyśle.

**Comment by F4z** [comment]
Ok, to może będę zgłaszał te reguły do twórcy uBlocka, w zasadzie tak byłoby najlepiej.
Ta reguła `motobanda.pl###mvideo:style(z-index: 1!important;)` dodana już jest do listy "uBlock filters‎", więc może inne też doda.

**Comment by F4z** [comment]
Swoją drogą chyba powinieneś usunąć te specjalne reguły do uBlocka, bo u mnie z nimi Adblock i Adblock Plus nie do końca poprawnie działają.

**Comment by MajkiIT** [comment]
@F4z dzięki usunąłem te reguły. 
Dodatkowo dodałem nową listę 
`https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt`

**Comment by F4z** [comment]
Ok, to później napiszę co można jeszcze dodać do tej listy :smiley:

**Comment by MajkiIT** [comment]
@F4z dzięki wielkie.
