### ISSUE TITLE
multi social - osamotnione resztki/napisy/kontenery - 173 strony

### ISSUE THREAD

**Issue by garrggul** [MajkiIT/polish-ads-filter#11623]
Jako, że to są drobne i niegrożne/nieaktywne resztki, to odpuszczę sobie robienie setek zgłoszeń + screenshotów, bo mi się nie chce i nawet nie wiem czy komuś też będzie się chciało tym zająć, więc wkleję tylko linki do stron, na każdej z nich znajdzie się jakiś osamotniony napis/resztka/kontener social typu "śledź nas na", "obserwuj nas", "dołącz do nas" itp., zazwyczaj na dole w stopce lub po prawej, przykładowo:
![ss481](https://user-images.githubusercontent.com/46904255/51559719-f5353f00-1e82-11e9-8b34-cbaf8a69fa9d.png) | ![ss482](https://user-images.githubusercontent.com/46904255/51559721-f5cdd580-1e82-11e9-8fd0-002851fceeef.png)

wklejam 

<details not-open>
<summary>173 linki posortowane alfabetycznie, powodzenia:</summary>

#11136 
~#11145~ (w tym są jednak spore kontenery to zgłoszę osobno)
http://2plus3d.pl/
http://agencjaroleplay.pl/
http://artkulinaria.pl/
http://ashika.it/
http://bada-world.pl/
http://bazylika-pszow.pl/
http://bitmon.pl/
http://borshop.pl/
http://cdrl.pl/
http://danutaantas.blogspot.com/
http://docelu.radom.pl/
http://dogorynogami.org/
http://driftopen.com/
http://exploringaround.pl/
http://foodmag.pl/
http://golebiowate.blogspot.com/
http://h1z1.eu/
http://heart-dimension.com/
http://inzynier-medyczny.pl/
http://itvregion.pl/
http://jakosxleci.blogspot.com/
http://jeffs.com/
http://kolna.pl/
http://kominki7.pl/
http://kreatorniazmian.pl/
http://lifefestival.pl/
http://losgrafikos.pl/
http://mamado.pl/
http://mamokazje.pl/
http://marekowczarz.pl/
http://moje-drinki.pl/
http://mynaszlaku.pl/
http://nakanapa.pl/
http://naszczelincu.pl/
http://nbalabs.pl/
http://nowykamieniarz.pl/
http://openstreetmap.org.pl/2018/infografika-podsumowanie-roku-2017/
http://organeoblog.pl/
http://prospectrum.pl/
http://przedszkolowo.pl/
http://przegladbaltycki.pl/
http://radio.opole.pl/
http://salonmodyxxl.pl/
http://sanatoriumchemik.pl/
http://shebang.pl/
http://sielska.eu/
http://skawina24.com/
http://slepsksuwalki.pl/
http://smog.krakow.pl/
http://sportowetv.pl/
http://stolowka-warminska.pl/
http://strefafana.pl/
http://vstars.pl/
http://whyart.pl/
http://wizytowki4you.pl/
http://wolontariat.org.pl/
http://www.13ulica.pl/schedule/day/today
http://www.akademiads.pl/
http://www.akademiakotaleonarda.pl/
http://www.ap-goal.pl/
http://www.arsdental.pl/
http://www.businessbar.pl/
http://www.chatazzalipia.pl/
http://www.coachingbalance.pl/
http://www.danfoss.pl/home/#/
http://www.delia.pl/
http://www.geekweek.pl/
http://www.gloswojewodzki.pl/
http://www.grapplerinfo.pl/
http://www.ibrpolska.pl/
http://www.joga-joga.pl/
http://www.kasianafali.pl/
http://www.klodzko.pl/pl/
http://www.klub-malawi.pl/
http://www.kulturatka.pl/
http://www.kurpas.com.pl/
http://www.ladyofthehouse.pl/
http://www.leksyka.pl/
http://www.nasza-chata.pl/
http://www.newtonmedia.pl/pl
http://www.paczkiwpodrozy.pl/
http://www.patriotyczna.com/pl/
http://www.pljasien.pl/
http://www.poszkole.pl/
http://www.prawojazdyradom.com.pl/
http://www.slaskieradio.com/
http://www.thecoachingmaps.eu/
http://www.windowsmania.pl/forum.php
http://www.zso11.zabrze.pl/
http://www.zyraffa.pl/
http://www.zywiec112.com.pl/
http://zarabiamykase.com.pl/
http://zbawienie.pl/jak-badac-biblie-1/
https://3xk.pl/
https://anikagotuje.blogspot.com/
https://bbfan.pl/
https://bewood.pl/
https://bezglutenowamama.pl/
https://bezstresowa.pl/
https://bieliznaujoli.pl/
https://brzeszcze.pl/
https://cerrad.com/
https://cichlidae.pl/
https://cukroweozdoby.pl/
https://e-mcklein.pl/
https://eduzabawy.com/
https://fundacjaiskierka.pl/
https://gorydlaciebie.pl/
https://imssport.pl/
https://jumpcity.pl/
https://korty.org/
https://laserwradomiu.pl/
https://manito.pl/
https://meblehubertus.pl/
https://mvpmagazyn.pl/
https://netland.pl/
https://notimi.pl/
https://paradise-rpg.pl/
https://piaseczno.eu/
https://polifoska.pl/
https://portal.bikeworld.pl/
https://salumanus.eu/
https://secretplace.pl/
https://shopconnector.pl/
https://termos24.pl/
https://ustrzyki-narty.pl/
https://wksklep.pl/
https://wroclawfashionoutlet.com/
https://www.agriaffaires.pl/
https://www.bata.pl/
https://www.beautyever.pl/
https://www.biorezonans.zgora.pl/
https://www.bizuteria-tytanowa.pl/
https://www.bogactwokaw.pl/
https://www.butynalata.pl/
https://www.dulux.pl/pl
https://www.e-madame.pl/
https://www.esab.pl/pl/pl/index.cfm
https://www.ewaipiotr.pl/
https://www.gazetkonosz.pl/
https://www.groupon.pl/
https://www.hotelprzystan.com/
https://www.karmimypsiaki.pl/
https://www.kiloutou.pl/
https://www.krainadrzwi.pl/
https://www.kreskowki.tv/kreskowka/p/41702/fukigen_na_mononokean_tsuzuki__odcinek_01
https://www.kuzdrowiu.com.pl/
https://www.limango.pl/
https://www.machineryzone.pl/
https://www.miastokobiet.pl/
https://www.monedo.pl/now
https://www.nikon.pl/pl_PL/
https://www.nokiantyres.pl/
https://www.paker.co.uk/
https://www.paniswojegoczasu.pl/
https://www.porscheinterauto.pl/
https://www.protan.pl/
https://www.raisin-sklep.pl/
https://www.sanatorium.mobi/
https://www.skef.pl/
https://www.spot-a-shop.pl/
https://www.superprezenty.pl/spektakl-i-kolacja-dla-dwojga-w-teatrze-sabat--warszawa-teatr-sabat
https://www.taxor.pl/
https://www.vans-shop.pl/
https://www.visa.pl/
https://www.woda.com.pl/
https://www.wzielonej.pl/
https://wyciskarki.pl/
https://xdrive-service.pl/
https://youngface.tv/
https://zlapkuriera.pl/

</details>

**Comment by bug-rules** [comment]
🐍
