### ISSUE TITLE
dziennikzachodni.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#11631]
```
https://dziennikzachodni.pl/smog-na-slasku-smierdzi-spalinami-jakosc-powietrza-jest-katastrofalnie-zla-w-katowicach-gliwicach-zabrzu-zywcu/ar/13829492
https://dziennikbaltycki.pl/smiertelny-wypadek-na-al-hallera-w-gdansku-23012019-samochod-uderzyl-w-restauracje-kierowca-uciekal-przed-policja-55latek-nie/ar/13829422#motofakty
https://gp24.pl/sprawca-falszywych-alarmow-juz-byl-na-policji-teraz-sad/ar/13830918#wiadomosci
https://dzienniklodzki.pl/horoskop-dzienny-na-srode-horoskop-dzienny-23-stycznia-znaki-zodiaku-i-horoskop-dzienny-na-23-stycznia-2019-sprawdz/ar/13828914#horoskop
https://gloswielkopolski.pl/kotwica-kornik-pilkarki-oskarzaja-bylego-trenera-o-molestowanie/ar/13831242#sport
https://dziennikpolski24.pl/frans-timmermans-w-krakowie-hold-dla-pawla-adamowicza-i-mocne-stwierdzenie-o-hejcie-morderstwo-zaczyna-sie-od-slow/ar/13831052#aktualnosci
https://echodnia.eu/swietokrzyskie/rodzina-i-przyjaciele-pozegnali-macieja-topolskiego-kieleckiego-dziennikarza-bylego-rzecznika-firmy-kolporter-zdjecia/ar/13831362#wiadomosci
https://polskatimes.pl/nowy-podejrzany-w-sprawie-tomasza-komendy-wychodzi-na-wolnosc/ar/13830668#aktualnosci
https://expressbydgoski.pl/28letni-bydgoszczanin-wpadl-z-narkotykami-zostal-zatrzymany-na-parkingu-gdy-skrobal-zamarzniete-szyby/ar/13830730#bydgoszcz
https://expressilustrowany.pl/studniowki-2019-studniowka-xxxiii-liceum-ogolnoksztalcacego-w-lodzi-zdjecia/ar/13803095#sport
https://nowiny24.pl/kara-w-zawieszeniu-dla-sprawcy-smiertelnego-wypadku-kierowca-tira-nie-ustapil-pierwszenstwa-rowerzystce-na-sciezce-rowerowej/ar/13830592#motofakty
https://gazetakrakowska.pl/frans-timmermans-w-krakowie-hold-dla-pawla-adamowicza-i-mocne-stwierdzenie-o-hejcie-morderstwo-zaczyna-sie-od-slow/ar/13831052#aktualnosci
https://pomorska.pl/300-lozek-zniknelo-ze-szpitali-w-regionie-a-to-nie-koniec/ar/13787790
https://nto.pl/mamy-wysyp-dziur-drogi-nie-wytrzymuja-takiej-zimy/ar/13831246#motofakty
https://gazetawroclawska.pl/nowy-podejrzany-w-sprawie-tomasza-komendy-wychodzi-na-wolnosc/ar/13830668#wiadomosci
https://wspolczesna.pl/miecze-wypadek-smiertelny-na-dk-61-potracony-pieszy-zginal-na-miejscu/ar/13831370#wypadek
https://gp24.pl/sprawca-falszywych-alarmow-juz-byl-na-policji-teraz-sad/ar/13830918#wiadomosci
```
![opera zdjecie_2019-01-23_233138_dziennikzachodni pl](https://user-images.githubusercontent.com/36385327/51641685-11aaa780-1f67-11e9-8f6d-6edfc445bb9c.png)

**Comment by krystian3w** [comment]
@olegwukr  pewnie coś z grupą Polska Press.

**Comment by krystian3w** [comment]
tak na szybko:

```
@@||s-pt.ppstatic.pl/*/reklama.js$script,domain=dzienniklodzki.pl|gloswielkopolski.pl|dziennikpolski24.pl|echodnia.eu|polskatimes.pl|expressbydgoski.pl|expressilustrowany.pl|nowiny24.pl|gazetakrakowska.pl|pomorska.pl|nto.pl|gazetawroclawska.pl|wspolczesna.pl|gp24.pl

**Comment by krystian3w** [comment]
Wersja dla uBO:

```
dzienniklodzki.pl,gloswielkopolski.pl,dziennikpolski24.pl,echodnia.eu,polskatimes.pl,expressbydgoski.pl,expressilustrowany.pl,nowiny24.pl,gazetakrakowska.pl,pomorska.pl,nto.pl,gazetawroclawska.pl,wspolczesna.pl,gp24.pl##+js(set-constant.js, pp_adblock_is_off, trueFunc)
||s-pt.ppstatic.pl/*/reklama.js$script,redirect=noopjs,important,domain=dzienniklodzki.pl|gloswielkopolski.pl|dziennikpolski24.pl|echodnia.eu|polskatimes.pl|expressbydgoski.pl|expressilustrowany.pl|nowiny24.pl|gazetakrakowska.pl|pomorska.pl|nto.pl|gazetawroclawska.pl|wspolczesna.pl|gp24.pl
```

**Comment by hawkeye116477** [comment]
Najlepiej chyba będzie od razu dać `@@||s-pt.ppstatic.pl/*/reklama.js` bez wypisywania domen.

**Comment by krystian3w** [comment]
I trochę szkoda, że na uBO samo `set-contsant` musi być wspomagane `noopjs`.

**Comment by hawkeye116477** [comment]
@krystian3w Ale po co tak kombinować, wyjątek będzie lepszy. Co innego jakby tam coś było więcej w tym skrypcie, a to tylko zwyczajna pułapka :stuck_out_tongue:

**Comment by xMaap** [comment]
@krystian3w Jeszcze tutaj
https://dziennikzachodni.pl/rybnik-pikieta-i-blokada-przejscia-dla-pieszych-pod-urzedem-miasta-gdy-nie-dostaniemy-podwyzek-dojdzie-do-strajku-w-szkolach/ar/13833942#wiadomosci
https://gazetalubuska.pl/lubuskie-tu-sie-zyje-oto-kilka-miejsc-pod-gorzowem-gdzie-mysli-zakloca-co-najwyzej-moj-wlasny-oddech-albo-odglos-butow-w-biegu/ar/13834800#wiadomosci
https://dziennikbaltycki.pl/wejherowo-walczylo-o-tytul-swietlnej-stolicy-polski-ostatecznie-zajelo-4-miejsce-wygral-sedziszow-malopolski/ar/13829762#swiec-sie
![opera zdjecie_2019-01-25_035552_dziennikzachodni pl](https://user-images.githubusercontent.com/36385327/51722280-2d8c7700-2055-11e9-9b01-23928ffc4066.png)

**Comment by krystian3w** [comment]
To jak nie zrobili rewolucji to do wyjątku można dopisać kolejne lub plik dopuścić globalnie.

```
pl,eu##+js(set-constant.js, pp_adblock_is_off, trueFunc)
||s-pt.ppstatic.pl/*/reklama.js$script,redirect=noopjs,important
```

I znów niby działają też  te trzy nowe strony powiązane z Grupa Press Polska.

**Comment by naraoia** [comment]
krystian3w - działa!
Poprosze o dopisanie tej reguły do filtrów 
Dziękuję

**Comment by naraoia** [comment]
krystian3w - działa!
Poprosze o dopisanie tej reguły do filtrów 
Dziękuję

**Comment by xxcriticxx** [comment]
ad block jest znowu 

https://dziennikbaltycki.pl/odwroceni-ojcowie-i-corki-odcinek-4-gdzie-ogladac-cyga-wpada-pod-pociag-odwroceni-ojcowie-i-corki-tvn-18032019-i-na-playerpl/ar/13952459

![Capture](https://user-images.githubusercontent.com/15007183/54569584-c97d9380-49b1-11e9-9220-1190a7d36a26.PNG)

**Comment by gaaargull** [comment]
Na tych stronach z pierwszego komentatrza są popsute filmiki przez aż 3 listy ciasteczkowe: 
https://github.com/ryanbr/fanboy-adblock/issues/973

**Comment by krystian3w** [comment]
Aha czyli nadgirliwa sieciówka to i może psują zdrowie radiozet.

**Comment by krystian3w** [comment]
`@@||sso.ppapi.pl/rodo.js$xmlhttprequest` i niby wideo rusza.

**Comment by krystian3w** [comment]
@naraoia - to chyba cudem działa, bo już chyba z 6 razy wracało i z przynajmniej 3 atrapy neutralizowano.

**Comment by gaaargull** [comment]
> krystian3w:  i niby wideo rusza.

Zaraz to przetestuję, jedynie nadmienię póki co, że czasami video się nie ładują same z siebie nawet przy wyłączonych tych 3 listach ciasteczkowych (jakieś lagi na stronie czy coś), więc dla pewności czy video się ładują czy nie zalecam kilkukrotne sprawdzanie (odświeżanie strony) i dokonanie kilku sprawdzeń, w celu wyeliminowania nieładowania się video z powodów niezwiązanych z filtrami.

**Comment by gaaargull** [comment]
Na chwilę obecną przy dodanym wyjątku, raz video się ładują , a innym razem nie, przy czym trudno stwierdzić, czy wtedy gdy się nie ładują to z powodu lagów na stronie, czy nieefektywności wyjątku.

**Comment by gaaargull** [comment]
Dobra zwracam honor, bo testy robiłem przy włączonych 3 listach caisteczkowych, i dopiero po wyłączeniu IDCAC, filmiki śmigają za każdym razem, czyli wyjątek naprawia 2 listy cisteczkowe, a IDCAC wymaga dodatkowego naprawienia.

**Comment by krystian3w** [comment]
Zawsze można u na wrócić do starych wyłapanych plików `rodo.js`.

Najgorsze że efektywność miały one najwyżej jak były to pełniejsze adresy URL zamiast złapania w jeden i z domen wymienić - coś podobnego do `priv.pl`.


Ja sam wyłapałem jeszcze że wideo ma jakieś tło i chyba go nie odblokowuje sam xhr.

**Comment by krystian3w** [comment]
Ciekawe więc co ma napsute Kiboke...

**Comment by gaaargull** [comment]
Z włączonym Kiboke i podanymi rozwiązaniami, raz działa, kilka razy nie działa, raz działa, kilka razy nie działa i tak w kółko, nie wiem o co kaman, jak coś to używam dodatku Kiboke, a nie listy.

**Comment by krystian3w** [comment]
A to z skryptem w dodatku już nie dam rady pomóc.

**Comment by gaaargull** [comment]
No to się wyjaśniło, gdy wyłączę dodatek, a włączę listę + podane rozwiązanie, to rzeczwyiście video działają, a dodatek musi naprawić sam Kiboke.

**Comment by krystian3w** [comment]
Pewnie podobny problem jak makaron spaghetti w ND.
