### ISSUE TITLE
seansik.nl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1165]
Strona wykrywa adblocka - `http://seansik.nl/film/iluzja-2-now-you-see-me-2-2016-napisy/8871`

![image](https://cloud.githubusercontent.com/assets/11742596/17463231/fa7220d0-5cc1-11e6-8b2b-8fdf928c0ae0.png)

Na przykład:
`@@||seansik.nl/seansik/js/ads.js$script`

**Comment by xxcriticxx** [comment]
cos mi strona sie nie laduje

**Comment by xxcriticxx** [comment]
@F4z kodi uzywasz?

**Comment by F4z** [comment]
Mi strona działa.
Nie używam kodi.

**Comment by xxcriticxx** [comment]
router udusilem privoxy ustawialem

**Comment by xxcriticxx** [comment]
hyba to wszystkie subdomains

http://alltube.tv/
http://kinex.tv/
http://seansik.nl/

**Comment by F4z** [comment]
Odnośnie alltube.tv to teraz można do uBlocka dodać odpowiednie reguły aby ominąć czekanie.
`alltube.tv###please-wait-container`
`alltube.tv###iframe-container:style(display: block !important;)`

**Comment by xxcriticxx** [comment]
alltube odliczanie mam dodac sobie? czy bendzie na liscie?

**Comment by MajkiIT** [comment]
Dodałem do nowej listy, bo jak mówił @F4z na Adblocku powoduje to problemy.

`https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt`

**Comment by xxcriticxx** [comment]
dodalem thx

**Comment by xxcriticxx** [comment]
Adblock & uBlock polish filters‎ : 2 used out of 8

czemu tylko 2 filtry uzywa

**Comment by F4z** [comment]
Może nie zaktualizowałeś polskiej listy filtrów "POL: polskie filtry do Adblocka i uBlocka"‎, i część reguł nadal tam jest.

**Comment by xxcriticxx** [comment]
moment zaraz to zrobie

**Comment by xxcriticxx** [comment]
dokladnie to teraz jest 8 z 8
