### ISSUE TITLE
extrakupony.pl

### ISSUE THREAD

**Issue by garrggul** [MajkiIT/polish-ads-filter#11659]
Jakiś dziwny błąd, nie wiem czy to błąd w AdGuard Social Media filter ale po włączeniu tej listy wyskakuje komunikat i nie działa przycisk zamknij ( "X"), przez co nie da się wejśc na stronę:

![extrakupny_pl_1](https://user-images.githubusercontent.com/46904255/51770561-82c49900-20e6-11e9-9b50-5df34c70ab34.png)

Po wyłączeniu tej listy strona normalnie się ładuje:

![extrakupny_pl_2](https://user-images.githubusercontent.com/46904255/51770575-966fff80-20e6-11e9-839d-fd0dcc73afba.png)

**Comment by krystian3w** [comment]
@F4z  sprawdzisz czy to jest powiązane z Social Media?

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/51787382-6457af80-2171-11e9-9c33-f8e421c0b656.png) |
--- |

Jak to odblokuję to znika.

```
@@||extrakupony.pl/js/zakladki.js$script,domain=extrakupony.pl
```

@hawkeye116477  to gdzieś dodajemy czy AdGuard Team lub MajkiIT naprawia?

**Comment by hawkeye116477** [comment]
@krystian3w Majki raczej zajmuje się reklamami, skoro ten problem dotyczy listy AG Social, to w takim razie jest to robota dla Adama :smile:.

**Comment by krystian3w** [comment]
OK.  To trzeba by wywalić do dany wyjątek w bugach adguard generowany przez listę a nie takie a nie inne wsparcie danej przeglądarki i blokowania w niej elementów.
