### ISSUE TITLE
zuch.media

### ISSUE THREAD

**Issue by garrggul** [MajkiIT/polish-ads-filter#11661]
http://zuch.media/kim-sa-patostreamerzy/

Social galeria x 2 (kolejna do kolekcji https://github.com/MajkiIT/polish-ads-filter/issues/11578#issuecomment-456112570) po kliknięciu na zdjęcie przekierowuje na Instagram:: 

po prawej:
![ss487](https://user-images.githubusercontent.com/46904255/51770817-434a7c80-20e7-11e9-9ea4-aa80a0d71624.png)

i na dole:
![ss488](https://user-images.githubusercontent.com/46904255/51770822-47769a00-20e7-11e9-8512-fe5e45e7b2c7.png)

**Comment by krystian3w** [comment]
Obie nie robią "goło i wesoło" więc out.

**Comment by krystian3w** [comment]
Nie wiem czy górną boczną może przywraca AdGuard SM.

**Comment by krystian3w** [comment]
Poproszę ID i klasy CSS tej górnej "prawej" jak masz ją.

**Comment by garrggul** [comment]
Nie przywraca, dalej są obydwie po wyłączeniu AdGuard

<details not-open>
<summary>ID i klasy</summary>

`###fw_instagram-4.widget_fw_instagram.fw-widget-instagram.widget`

![ss503](https://user-images.githubusercontent.com/46904255/51788379-ba325480-217d-11e9-90ba-ae72d025f839.png)

</details>

**Comment by krystian3w** [comment]
A to już wiem `##.widget_fw_instagram.fw-widget-instagram`  taki wyciął dwa to nie mam.
