### ISSUE TITLE
Nowe reguły

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1167]
Zacznę od wstawienia całej listy.

<pre># http://alltube.tv/
# Ominięcie czekania
alltube.tv###please-wait-container
alltube.tv###iframe-container:style(display: block !important;)

# http://www.czasbajki.pl/
# Ominięcie czekania
czasbajki.pl###kAdd
czasbajki.pl###kSplash
czasbajki.pl###kFinal:style(display: block !important;)

# http://www.efilmy.tv/
# Ominięcie przycisku "Close Ad and Watch as Free User"
efilmy.tv###step1
efilmy.tv###hideOnClick
efilmy.tv###playerVidzer:style(display: block !important;)

# http://gahe.pl/
# Ominięcie czekania
gahe.pl###gameloader
gahe.pl###flashgame:style(visibility: visible; display: block;)

# http://www.gry.jeja.pl/
# Ominięcie czekania
jeja.pl##.gameLoading
jeja.pl###adLoading
jeja.pl###swf:style(visibility: visible !important; position: static !important; left: 0px !important;)
jeja.pl###game:style(visibility: visible !important; position: static !important; left: 0px !important;)

# http://www.national-geographic.pl/
# Puste miejsce po reklamie
@@||national-geographic.pl/bundles/burdacore/js/adv.js$script
national-geographic.pl##.advertising-billboard:style(height: 0px !important;)

# http://www.vidzer.net/
# Ominięcie przycisku "Close Ad and Watch as Free User"
vidzer.net###step1
vidzer.net###hideOnClick
vidzer.net###playerVidzer:style(display: block !important;)

# http://www.wykop.pl/
# Usunięcie komunikatu o ciasteczkach
wykop.pl##.cookie
wykop.pl##.type-permanent+#nav:style(top: 0px !important)
wykop.pl##.type-permanent+#nav+div:style(padding-top: 49px !important)
</pre>

1) alltube.tv - ominięcie czekania, wiadomo o co chodzi

2) czasbajki.pl - ominięcie czekania, wiadomo o co chodzi

3) efilmy.tv - ominięcie przycisku "Close Ad and Watch as Free User"
Link - `http://www.efilmy.tv/seriale.php?cmd=show_regular&id=104`

![image](https://cloud.githubusercontent.com/assets/11742596/17465190/1ab4e42a-5cf1-11e6-9240-8743142caeb2.png)

4) gahe.pl - ominięcie czekania, teraz żeby zagrać w jakąkolwiek grę trzeba poczekać 20 sekund
Link - `http://gahe.pl/graonline,17871,ninjago-masters-of-spinjitzu-coloring-page-kolorowanka-lego-ninjago`

![image](https://cloud.githubusercontent.com/assets/11742596/17465205/9dd92d20-5cf1-11e6-8983-11f611bd776a.png)

5) jeja.pl - ominięcie czekania przed grami
Link - `http://www.gry.jeja.pl/5682,zrujnowany-dom.html`

![image](https://cloud.githubusercontent.com/assets/11742596/17465242/8adb35c8-5cf2-11e6-933a-c774b4815c9b.png)

Przy okazji można zablokować reklamę, zaznaczyłem na obrazku, na dole.
I poprawić/usunąć tę regułę `gry.jeja.pl###top`, bo ucina trochę strony, zaznaczyłem na obrazku na górze, ale te dwie rzeczy, to już przy użyciu normalnych filtrów.

6) national-geographic.pl -  puste miejsce po reklamie, wiadomo o co chodzi

7) vidzer.net - ominięcie przycisku "Close Ad and Watch as Free User", czyli to samo co przy efilmy.tv
Link - `http://www.vidzer.net/file/9fc74544770a02eec7321dd63d89d1e5`

8) wykop.pl - usunięcie komunikatu o ciasteczkach, to też wiadomo o co chodzi

**Comment by xxcriticxx** [comment]
zalukaj.tv przejrzyj

**Comment by F4z** [comment]
Jeśli chodzi o przycisk "KLIKNIJ, ABY OBEJRZEĆ", to nie widzę możliwości żeby go ominąć za pomocą tego typu reguł.
Natomiast po kliknięciu w ten przycisk pojawia się jednosekundowa reklama.
![image](https://cloud.githubusercontent.com/assets/11742596/17465526/93fd9252-5cf9-11e6-9587-b77a87286566.png)

I ją już można pominąć:
`zalukaj.com###freePlayerWatch`
`zalukaj.com###free_player:style(display: block !important;)`

**Comment by xxcriticxx** [comment]
Zaraz podam jeszcze kilka stron

**Comment by xxcriticxx** [comment]
Zobacz ten plus player pierwszy czy drugi wpis

**Comment by F4z** [comment]
Nie da rady za pomocą reguł ominąć tej reklamy.

Ale możesz spróbować dodać sobie taki skrypt do Greasemonkey/Tampermonkey, może zadziała :stuck_out_tongue_closed_eyes: 
<pre>
// ==UserScript==
// @name         playpuls.pl
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Ominięcie reklamy
// @author       Adam
// @match        http://playpuls.pl/*
// @grant        none
// @run-at document-start
// ==/UserScript==

Object.defineProperty(window, 'ads', {
    get: function() { return {}; }
});
</pre>

**Comment by xxcriticxx** [comment]
dodalem ale jak to odpalic

**Comment by xxcriticxx** [comment]
ok sie zdaje ze dziala zaraz wyloncze zobaczymy co bendzie

**Comment by xxcriticxx** [comment]
freedisc.pl
kinex.tv
iptak.pl
tvseriesonline.pl
zobaczto.tv
bajkionline.com
bajkipopolsku.com
kreskowkazone.pl
meczyki.pl
meczelive.tv
filmydokumentalne.eu
ipla.tv
serialnet.pl
tosiewytnie.pl

**Comment by xxcriticxx** [comment]
script do playpuls.pl dziala

**Comment by xxcriticxx** [comment]
@F4z do kinoman.tv/lajt.kinoman.tv mozesz zrobic ominiecie Vidzer?

**Comment by F4z** [comment]
@xxcriticxx chodzi o to?

![image](https://cloud.githubusercontent.com/assets/11742596/17592512/e24ba37c-5fe2-11e6-9615-07bd27435ba6.png)

Jeśli tak, to reguły z "polskie filtry do uBlocka uzupelnienie" powinny to usuwać.

**Comment by xxcriticxx** [comment]
Ok got It

**Comment by xxcriticxx** [comment]
przejdz do odtwarzacza da sie stym cos?
