### ISSUE TITLE
arcontact.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#11683]
resztka po fb i G+ ( buttons ) oraz G+ ( na dole )

**Comment by krystian3w** [comment]
@hawkeye116477  ja wyciąłem tu tylko 1 button G+, więc zostaje ta jakaś resztka do wypatrzenia :eagle: wzrokiem / okiem.

**Comment by blocker999** [comment]
@krystian3w resztka jest nad G+ co prawda niewidoczna ale po najechaniu myszą się rozwija

**Comment by krystian3w** [comment]
To będzie dopiero za dwa dni.

**Comment by hawkeye116477** [comment]
Nieprawda, już dodałem, tylko, że w innej linii razem z resztą dla tej strony.
