### ISSUE TITLE
www.tekstowo.pl

### ISSUE THREAD

**Issue by azet12** [MajkiIT/polish-ads-filter#1168]
przy dowolnym tekście nie da się włączyć poglądu piosenki, uruchamia się player z 0 sekundami i tak stoi, po wyłączeniu adblocka jest to player z reklamą 30 sekundową, który znika po skończeniu reklamy

oraz dodatkowo reklama "giercownia" kiedy zjedzie się trochę niżej strony przy dowolnej piosence (prawy dolny róg)

**Comment by F4z** [comment]
To powinno pomóc:
`||maxart.pl$script`
`||giercownia.pl/widget/*.loader.js$script`
Tylko trzeba dwa razy kliknąć w wideo żeby zaczęło się odtwarzać.

**Comment by MajkiIT** [comment]
@F4z 
a nie lepiej

@@/videojs.ads.$script,domain=filmiki4.maxart.pl
##[id^="giercowniaAd"]

**Comment by F4z** [comment]
Jeśli chodzi o tę regułę `@@/videojs.ads.$script,domain=filmiki4.maxart.pl`, to lepiej, bo nie trzeba dwa razy klikać :smiley:
A w przypadku tej drugiej, to jak kto woli, ale gdy zablokuje się skrypt, to elementy które są przez niego pobierane (na przykład obrazki) w ogóle nie zostaną pobrane.
