### ISSUE TITLE
ostrowiecnews.pl

### ISSUE THREAD

**Issue by garrggul** [MajkiIT/polish-ads-filter#11684]
Błąd w Polskie Filtry Społecznościowe, nie ładują się grafiki/zdjęcia:

![ss_072](https://user-images.githubusercontent.com/46904255/51787922-a388ff00-2177-11e9-89fe-f6194e0fb020.png)

Po wyłączeniu listy strona ładuje się normalnie:
![ss_070](https://user-images.githubusercontent.com/46904255/51787930-b8659280-2177-11e9-8b43-53a026ab26bf.png)

**Comment by krystian3w** [comment]
@hawkeye116477  mogę to naprawić, że `/yt.` wycinać ma tylko grafiki?

Bo wycina skrypty i to druga zbugowana strona.

**Comment by hawkeye116477** [comment]
@krystian3w Możesz
