### ISSUE TITLE
Regular expressions meta characters

### ISSUE THREAD

**Issue by ameshkov** [MajkiIT/polish-ads-filter#1169]
Hey from Adguard!

We recently had an issue with one of the regular expression based rules in the "Adblock polskie reguły". The issue detailed description is here: https://github.com/AdguardTeam/AdguardForiOS/issues/128#issuecomment-238498979

The problematic rule is: `@@/:\/\/.*[.]wp[.]pl\/[a-z0-9_]{30,50}[.][a-z]{2,5}\b/`

You see, Safari supports only a limited subset of regular expressions options. We validate regexp rules, but it appears that we've missed to check for meta characters:). Could you please change this rule a bit temporarily? For instance, you could replace `\b` with `[/:&?]?`, I suppose it should solve the issue.

All these regexp issues are important for Safari and iOS as in their case any invalid rule causes the compilation failure for the whole content blocker.

**Comment by xxcriticxx** [comment]
@ameshkov thx for letting us know

**Comment by MajkiIT** [comment]
Ok, I will do it.

**Comment by ameshkov** [comment]
Thank you!

**Comment by MajkiIT** [comment]
No problem. Thanks for your help.
