### ISSUE TITLE
astar.czest.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#11711]
Reklamy pomagają nam rozwijać tę stronę
Kiedy odwiedzasz naszą stronę, nasi Zaufani Partnerzy mogą odczytywać i korzystać z określonych informacji zapisanych na Twoim urządzeniu, aby wyświetlać odpowiednie reklamy bądź spersonalizowane treści. Klikając „Zaakceptuj wszystko” wyrażasz zgodę na przetwarzanie informacji zapisanych na Twoim urządzeniu przez nas oraz Zaufanych Partnerów w celu wyświetlania odpowiednich reklam lub spersonalizowanych treści.Dowiedz się więcej.
Informacje jakie mogą być używane.Cele przechowywania informacji.

**Comment by krystian3w** [comment]
I anti-adblock @olegwukr 

![obraz](https://user-images.githubusercontent.com/35370833/51792270-fe8a1880-21ae-11e9-8800-b2d4be2cfe0f.png) |
--- |

**Comment by krystian3w** [comment]
```
astar.czest.pl#@#.text_ad
astar.czest.pl#@#.textAd
astar.czest.pl#@#.text-ads
astar.czest.pl#@#.text-ad-links
astar.czest.pl#@#.text-ad
astar.czest.pl#@#.pub_728x90
astar.czest.pl#@#.pub_300x250m
astar.czest.pl#@#.pub_300x250
```

albo

`@@||astar.czest.pl^$generichide`

**Comment by krystian3w** [comment]
uBO:

`astar.czest.pl##^script:has-text(KillAdBlock)`
`astar.czest.pl##+js(abort-current-inline-script.js, KillAdBlock)`
