### ISSUE TITLE
user script

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1171]
@MajkiIT moze bys dodal teczke user script. jeden jusz jest do playpuls.pl

// ==UserScript==
// @name         playpuls.pl
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Ominięcie reklamy
// @author       Adam
// @match        http://playpuls.pl/*
// @grant        none
// @run-at document-start
// ==/UserScript==

Object.defineProperty(window, 'ads', {
    get: function() { return {}; }
});

**Comment by MajkiIT** [comment]
Ok coś pomyślimy. Dzięki .
