### ISSUE TITLE
optimalg.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#11718]
cookies + RODO

**Comment by krystian3w** [comment]
@hawkeye116477  możesz sprawdzić jaki skrypt trzeba ubić / wyciąć html filteringiem.

**Comment by hawkeye116477** [comment]
@krystian3w `optimalg.com##^#rodoModal`

**Comment by krystian3w** [comment]
U mnie nie dodawało przewijania, chyba że modal-backdrop po przecinku bugował.

**Comment by hawkeye116477** [comment]
@krystian3w Jest przewijanie, także pewnie było tak jak mówisz.

**Comment by krystian3w** [comment]
OK.

**Comment by krystian3w** [comment]
to w suplementach zostawiłem poprawkę na pasek cookies, bo jakoś dziwnie tło przesuwają.
