### ISSUE TITLE
ec.europa.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#11717]
cookies 

test link:
http://ec.europa.eu/citizens-initiative/public/?lg=pl

**Comment by krystian3w** [comment]
dubel: https://github.com/MajkiIT/polish-ads-filter/blob/4f2591e0496865534272905e3f6a6a0d25dd570b/cookies_filters/adblock_cookies.txt#L403

**Comment by xxcriticxx** [comment]
@krystian3w check test link cookies dalej sie pokazuja

**Comment by krystian3w** [comment]
U mnie nie - uaktualnij listę i sprawdź.

**Comment by krystian3w** [comment]
Na czerwono czyli zablokowany:

![obraz](https://user-images.githubusercontent.com/35370833/51802069-4dcf5800-2246-11e9-8af3-8476d4e554b6.png) |
--- |
