### ISSUE TITLE
legia.net (2)

### ISSUE THREAD

**Issue by garrggul** [MajkiIT/polish-ads-filter#11721]
Reopen https://github.com/MajkiIT/polish-ads-filter/issues/11663 bo dalej to jest.

**Comment by krystian3w** [comment]
`legia.net###first-col div.module:nth-of-type(7) > .module-header, #second-col div.module:nth-of-type(6) > .module-header`

Wskoczy coś innego, to trzeba będzie sięgnąć po `:-abp-contains( )`.
