### ISSUE TITLE
tv-slupsk.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#11723]
cookies oraz fb ( na dole )

**Comment by krystian3w** [comment]
cookies nie mam, Firefox mi się popsuł po odświeżeniu i sam ukrywa za dużo.

**Comment by krystian3w** [comment]
dubel: https://github.com/MajkiIT/polish-ads-filter/blob/4f2591e0496865534272905e3f6a6a0d25dd570b/cookies_filters/adblock_cookies.txt#L1974

innych cookies nie widzę w Chrome.

**Comment by krystian3w** [comment]
FB chyba przepuszcza Nano #10028
