### ISSUE TITLE
lacha.pl (2) NSFW

### ISSUE THREAD

**Issue by garrggul** [MajkiIT/polish-ads-filter#11722]
Reopen https://github.com/MajkiIT/polish-ads-filter/issues/11703 bo dalej to jest.

**Comment by krystian3w** [comment]
Chyba trzeba do filtrów własnych i tyle.

**Comment by garrggul** [comment]
A dlaczego, skoro to reklama zewnętrzna.

**Comment by garrggul** [comment]
To po co xxcriticxx zgłasza reklamy na takich stronach.

**Comment by krystian3w** [comment]
Go chyba nikt nie informuje jak się nawet dowiedział o wyniesieniu filtrów anty-adblock po fakcie.

**Comment by garrggul** [comment]
No ale skoro siedzi na tym repo kilka lat, to nie wmówisz mi, że nie wiedziałby, że stron porno ta lista nie obsluguje.

**Comment by xxcriticxx** [comment]
@krystian3w dla mnie nowość myślałem ze blokujemy wszystko

**Comment by garrggul** [comment]
Właśnie.

> krystian3w: lepiej chronić dzieci blokujące reklamy przed pornografią, filtr może je zachęcić do odblokowania.

Jakaś pokręcona filozofia być niańką, a w Polsce to jeszcze pewnie wszystkie dzieci to sieroty, jakoś na innych listach reklamowych typu EasyList, AdGuard Base filter, uBlock filters itd., reklamy na stronach porno są blokowane tak jak każde inne reklamy na innych stronach, czy mógłbyś rozjaśnić o co chodzi w tej twojej dziwnej filozofii bycia niańką dla polskich sierot i dlaczego polska lista odstaje filozofią od innych list reklamowych.

**Comment by krystian3w** [comment]
> dzieci to sieroty

"bo miejsce dziecka jest w domu dziecka".
