### ISSUE TITLE
wikar.pl

### ISSUE THREAD

**Issue by garrggul** [MajkiIT/polish-ads-filter#11734]
Ciasteczka:

![ss512](https://user-images.githubusercontent.com/46904255/51828735-875a9e80-22ec-11e9-9ab9-89930890b0a4.png)

**Comment by krystian3w** [comment]
`##div > aside.type-10.widget`

**Comment by krystian3w** [comment]
Jak coś to teraz filtr puścił i najpopularniejsze układy to:

```
##div[class]:not([id])                          > aside.type-10.widget
##seciton[class]:not([id])                      > aside.type-10.widget
##div[class]:not([id]) > div[id].type-10.widget > aside.type-10.widget
```

<sup> `aluzja.gorzow.pl,artgos.pl,ck.przemysl.pl,diagmed.info.pl,hostgrafia.pl,mojawww.com,osrodek-terapii.com,puch-kotlowski.pl,sls.info.pl,swiatdeski.pl,tomiicars.com.pl,treningkrakow.pl,vagaru.pl,wikar.pl` </sup>
