### ISSUE TITLE
wowhungary.wp.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#11736]
Adblock
http://wowhungary.wp.pl/zarobki-w-forintach-jak-zalozyc-firme-na-wegrzech-i-dlaczego-warto-to-zrobic
![image](https://user-images.githubusercontent.com/29756590/51860597-76d11500-233a-11e9-9cfb-f9701eeddb22.png)

**Comment by MajkiIT** [comment]
@@||wowhungary.wp.pl/js/ads.js
