### ISSUE TITLE
Lista domen usuniętych

### ISSUE THREAD

**Issue by garrggul** [MajkiIT/polish-ads-filter#11733]
Może komuś się przyda: https://www.dns.pl/lista_domen_usunietych

Np. zamiast odpytywać DNS zdalnie które domeny `.pl` zostały usunięte można pobrać i odpytać lokalnie tę listę, o wiele szybsza metoda, a pozostałe domeny można odpytywać zdalnie w DNS.

**Comment by krystian3w** [comment]
Może @MajkiIT  dorzuci do skryptu, albo @hawkeye116477  do swojego forka jakiegoś projektu.

**Comment by MajkiIT** [comment]
@krystian3w To jest zbędne....
