### ISSUE TITLE
fitqbe.com

### ISSUE THREAD

**Issue by garrggul** [MajkiIT/polish-ads-filter#11806]
Social ikona na dole:

![ss585](https://user-images.githubusercontent.com/46904255/51912787-691c9d80-23d5-11e9-9281-b29882dc8f87.png)

**Comment by krystian3w** [comment]
100% proof.

Drażni, ale nie da się kliknąć by coś otworzyła.

**Comment by gargulll** [comment]
Wiem, że nie da się kliknąć, ale drażni, dlatego zgłosiłem, to co, ma tak sobie siedzieć i drażnić dalej, skoro drażni więc powinno zostać usunięte, zwłaszcza, że da się łatwo i bez problemu usunąć?
