### ISSUE TITLE
cda-online.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1181]
ad block

Wykryto AdBlock!

Adblock blokuje pełną funkcjonalność oraz uniemożliwia odtwarzanie materiałów wideo znajdujących się w portalu!

Wykryliśmy że używasz Adblock lub podobnego oprogramowania. Jeżeli chcesz korzystać z tego portalu musisz wyłączyć Adblock lub dodać portal cda-online.pl do wyjątków (whitelist).

 
ZAMKNIJ

**Comment by MajkiIT** [comment]
jakiś konkretny adres?
