### ISSUE TITLE
porscheinterauto.pl

### ISSUE THREAD

**Issue by garrggul** [MajkiIT/polish-ads-filter#11835]
Sociale na dole:

![ss_115](https://user-images.githubusercontent.com/46904255/51914166-7d15ce80-23d8-11e9-83b4-e76ebb1c8e58.png)

**Comment by gargulll** [comment]
A te opinie Google to dalej są, to zdaje się, że chodzi o opinie z Google+, wiec też do usunięcia.

**Comment by krystian3w** [comment]
Nie są podpisane że z google plus, mogły by być np. widoczne w mapach Google.

**Comment by krystian3w** [comment]
https://www.google.com/maps/place/Salon+i+serwis+Audi+-+Porsche+Po%C5%82czy%C5%84ska/@52.2158664,20.8876181,17z/data=!4m13!1m7!3m6!1s0x471ecad54a7b3a77:0x3512b5ffcf6917d8!2sPo%C5%82czy%C5%84ska+107,+01-303+Warszawa!3b1!8m2!3d52.2158664!4d20.8898068!3m4!1s0x471ecad533ff7f37:0xd45de04f5a0eeb3!8m2!3d52.2159536!4d20.8888789

**Comment by garrrgul** [comment]
Skoro to jednak z Map Google a nie z Google+ to w takim razie ok, nie nalegam, zadecydujecie sami.
