### ISSUE TITLE
onet.pl - regex 

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1183]

**Comment by xxcriticxx** [comment]
co stym?

**Comment by MajkiIT** [comment]
chce zrobić multiregex pod to. Dla każdej strony jest inny url.

**Comment by xxcriticxx** [comment]
znalazlem to u reeka

 mapx- commented 20 hours ago

or add
/http://[a-z0-9]{8}.onet.pl/$script

**Comment by xxcriticxx** [comment]
sorry zdjecia stym sie nieda zmienic
