### ISSUE TITLE
brzesckujawski.pl

### ISSUE THREAD

**Issue by garrggul** [MajkiIT/polish-ads-filter#11853]
Social widżet scrollujący po prawej:

![anim 003](https://user-images.githubusercontent.com/46904255/51916819-696d6680-23de-11e9-9817-baa76009c43f.gif)

**Comment by krystian3w** [comment]
Na firefox nie mam, może znowu AdGuard uważa to za pozytywny element.

**Comment by krystian3w** [comment]
`brzesckujawski.pl##.pwebbox-plugin-facebook_page_plugin`
