### ISSUE TITLE
przepisy.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#11891]
@hawkeye116477 

Treść wiadomości:
filtr elementów irytujących blokuje tutaj pobieranie
https://www.przepisy.pl/ebook/zero-waste-i-nic-sie-nie-zmarnuje?utm_source=newsletter&utm_medium=email&utm_campaign=2019-01-26&utm_content=ebook

**Comment by krystian3w** [comment]
@hawkeye116477  jak coś ręcznie wkleiłem cookies do EI, bo dalej się nie pobrało, widać git na Windows ułomny a VSC i Kraken trochę przekombinowane.

**Comment by hawkeye116477** [comment]
Ok, ja tam myślę, że to coś u ciebie z netem nie tak, skoro nie pobiera. Git tu nie ma nic do tego, bo skrypt pobiera z raw, nie wykorzystuje do tego gita.

**Comment by krystian3w** [comment]
Ale żeby aż dwa różne źródła internetu "popsute", jeszcze mogę kiedyś odpalić z Manjaro do zobaczenia czy ten też się wywali.

I co to za jakieś null zaproszenie do CircleCI? Niby widać że próbuję robić RTM i nie widać tego na githubie?

**Comment by hawkeye116477** [comment]
@krystian3w W konsoli powinieneś na początku widzieć 200 OK, jak uruchamiasz skrypt.
Wpisz i zobacz co się stanie `wget --spider https://raw.githubusercontent.com/hawkeye116477/polish-ads-filter/master/cookies_filters/adblock_cookies.txt`.
Potem dorobię jeszcze do skryptu sprawdzanie czy łączy się z raw.github, jak nie, to zatrzyma skrypt i nie będzie nic robić.

**Comment by krystian3w** [comment]
Ja tam widzę milion zmieniamy entery Windowsa na linuksowe.

**Comment by krystian3w** [comment]
i w tym Bashu to nawet nie ma `wget` czyli muszę jakiś doinstalować? dzięki!

**Comment by krystian3w** [comment]
ale mam za to `curl` - gorsze to?

**Comment by krystian3w** [comment]
`https://web.archive.org/web/20190122090916/https://eternallybored.org/misc/wget/` 1.19 chyba działa.

**Comment by hawkeye116477** [comment]
@krystian3w Curl ma też trochę inne zastosowanie, a konkretniej to on jest głownie do odpytywania api, wymiany żądań/odpowiedzi z serwerem, wget jest bardziej do zwyczajnego pobierania plików.
Także proponuję doinstalować wget.
