### ISSUE TITLE
filmbit.ws

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#11927]
@MajkiIT regex please

**Comment by xxcriticxx** [comment]
@MajkiIT jak zmieniasz na topie strona glowna, filmy, seriale , tv to jeszcze cos wyskakuje 

![capture](https://user-images.githubusercontent.com/15007183/52163823-ec7c0e80-26b5-11e9-831d-0de2bacb9609.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx Zrób proszę update do wersji 2019020204 i powinno być OK

**Comment by xxcriticxx** [comment]
@MajkiIT fake cloudflare

Nasz system zabezpieczeń wykrył atak na naszą stronę. Trwa sprawdzanie twojej przeglądarki.

Potrwa to około 5 sekund.

**Comment by xxcriticxx** [comment]
@MajkiIT naciskajac na TV to mi wyskoczylo

![capture](https://user-images.githubusercontent.com/15007183/52164427-34ebfa00-26bf-11e9-8041-246ddbb95ca7.PNG)

**Comment by xxcriticxx** [comment]
naciskajac na film 21 gram ten sam `||ousufauk.com^` wyskakuje

**Comment by xxcriticxx** [comment]
@MajkiIT jak klikniesz na logo strony sie otwiera nowa karta z  `gsafe.getawesome1.com`

**Comment by xxcriticxx** [comment]
@MajkiIT 

test link:
https://filmbit.ws/serial-online/wolf-creek/2025/odcinek-6

pod play jest podlonczony shit

**Comment by MajkiIT** [comment]
@xxcriticxx Spróbuj z wersją 2019020301 . Będziemy łatać po kolei.

**Comment by xxcriticxx** [comment]
@MajkiIT dalej z gounlimited sie os otwiera `gsafe.getawesome1.com` and `prmtracking.com`

**Comment by MajkiIT** [comment]
@xxcriticxx Nadal to masz?

**Comment by xxcriticxx** [comment]
@MajkiIT sure

**Comment by xxcriticxx** [comment]
@MajkiIT wyglonda na git zamykam
