### ISSUE TITLE
mobile.de/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#11921]
cookies

**Comment by krystian3w** [comment]
Widać się zdezaktualizowało:

https://github.com/MajkiIT/polish-ads-filter/blob/4f2591e0496865534272905e3f6a6a0d25dd570b/cookies_filters/adblock_cookies.txt#L995

**Comment by xxcriticxx** [comment]
`mobile.de###consentBanner`
