### ISSUE TITLE
AlleBlock

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1193]
twoje?

https://tarmas.pl/alleblock/

**Comment by xxcriticxx** [comment]
https://tarmas.pl/alleblock/alleblock.txt

**Comment by MajkiIT** [comment]
Nie, ale widziałem.

**Comment by xxcriticxx** [comment]
Zapros go do nas jeszcze jedna osoba sie przyda

**Comment by MajkiIT** [comment]
Może masz rację. Pytanie czy dodawać zawartość tej listy do moich filtrów.

**Comment by xxcriticxx** [comment]
zapytaj autora czy bendzie ok

tak samo jak filtry do wykop sa na liscie
