### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#11931]
RODO

https://www.dobreprogramy.pl/mapy-google-alkohol-kradziez-pieniedzy,News,100114.html

![capture](https://user-images.githubusercontent.com/15007183/52168377-bd868c80-26f7-11e9-8560-9a501cac831c.PNG)

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishCookieConsent/issues/19 - jak będzie podobnie jak na forum to w dodatku trzeba by coś głębiej podebugować.

**Comment by krystian3w** [comment]
Jak coś to u mnie skryptowa reguła dalej działa w Firefox. A na forum nie i dodałem na dev filtr, że ten element miga tam.
