### ISSUE TITLE
moneyv.wp.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#11937]
Uszkodzona strona (brak odtwarzacza wideo) i resztki po reklamach:

```
https://moneyv.wp.pl/gospodarka/efekty-wprowadzenia-zakazu-handlu-ciekawe-wyniki-analiz-6345148059879041v.html
```

**Comment by krystian3w** [comment]
@hawkeye116477  nie wiem czy może akceptacja rodo nie psuje tej strony.

**Comment by HateAds** [comment]
@krystian3w U mnie ładuje się odtwarzacz ( po jakiś 8-10 sekundach )
Ale mam wszędzie szare pola z napisem wp reklama

**Comment by HateAds** [comment]
Wszedłem teraz 15 razy pod rząd i u mnie ładuje się za każdym razem, ale po jakiś 10-15 sekundach.
Tak przy okazji sprawdzałem na Chromie.

**Comment by xxcriticxx** [comment]
u mnie pokazuje sie i znka mam tez szare pola z wp reklama chrome 71.0.3578.98 (Official Build) (64-bit)

**Comment by hawkeye116477** [comment]
Tak, to wina `wp.pl##+js(addEventListener-defuser.js, DOMContentLoaded, default.setTimeout)`, ale jak zrobimy whitelist, to zaraz też reklamy się pojawią :smile:.

**Comment by krystian3w** [comment]
reklamy przez  wiadomo co :wink:.

**Comment by krystian3w** [comment]
`wp.pl,moneyv.wp.pl#@#+js(addEventListener-defuser.js, DOMContentLoaded, default.setTimeout)`

dezaktywacja filtra nie pomaga, więc nie on pewnie najmocniej blokuje odtwarzacz w Firefox.
