### ISSUE TITLE
social reopen (kilka stron)

### ISSUE THREAD

**Issue by gargulll** [MajkiIT/polish-ads-filter#11941]
Social reopen 4 stron bo dalej to jest: https://github.com/MajkiIT/polish-ads-filter/issues/11751, https://github.com/MajkiIT/polish-ads-filter/issues/11756, https://github.com/MajkiIT/polish-ads-filter/issues/11797, https://github.com/MajkiIT/polish-ads-filter/issues/11853
Oraz w przypadku 2 stron nie jestem pewny (pytałem, ale nie było odpowiedzi): https://github.com/MajkiIT/polish-ads-filter/issues/11806, https://github.com/MajkiIT/polish-ads-filter/issues/11835

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/11797, https://github.com/MajkiIT/polish-ads-filter/issues/11853

Tego nie widzę w Firefox.

**Comment by krystian3w** [comment]
To zostaje kwestia:
- czy wycinamy puste zdjęcie FB w "żałobie" 
- czy wycinamy i te fałszywe opinie Google z 5 :star: :star: :star: :star: :star:

hot spraye, urbanaki i te dwa pewboxy docięte na dev w "templatkach".
