### ISSUE TITLE
mojegliwice.pl + mojmikolow.pl + orzesze.com.pl + piekaryslaskie.com.pl + rudaslaska.com.pl + rybnicki.com + sosnowiecki.pl

### ISSUE THREAD

**Issue by gargulll** [MajkiIT/polish-ads-filter#11940]
1 RODO/ciasteczka
2 Social ikony/przyciski na dole
3 Napisy reklama na całej stronie

1 RODO/ciasteczka:
![ss_001](https://user-images.githubusercontent.com/47152854/52182506-21937880-27fe-11e9-8fb5-b2fb2fb488d1.png)

2 Social ikony/przyciski na dole:
![ss460](https://user-images.githubusercontent.com/47152854/52182524-5bfd1580-27fe-11e9-8681-3b568d73332b.png)

3 Napisy reklama na całej stronie:
![ss461](https://user-images.githubusercontent.com/47152854/52182543-7afba780-27fe-11e9-94ea-754cd41381a5.png)
![ss462](https://user-images.githubusercontent.com/47152854/52182544-7afba780-27fe-11e9-940e-cc8f1979b00b.png)
![ss463](https://user-images.githubusercontent.com/47152854/52182545-7afba780-27fe-11e9-88ff-6c97c18469c6.png)

**Comment by krystian3w** [comment]
Mnie rodo znika, brak przycisków social na dole, brak resztek po reklamach.

**Comment by krystian3w** [comment]
Sprawdź więc filtry na obecność `@@||` (...) `$generichide`.

**Comment by krystian3w** [comment]
I jak to nie jest popularna lista to strony raczej nie dostaną filtrów:

`com,pl###rodo-popup:not(body):not(html):not(.fade):not(.modal)`
`com,pl###footer-social`
`com,pl##.advert`

**Comment by krystian3w** [comment]
@xxcriticxx  / @gargulll  można zamknąć efekt testowania z zaznaczoną opcją:

"`Ignoruj ogólne filtry kosmetyczne`"

Więc elementy się wyświetlą, bo nie są blokowane sieciowo (nie da się).
