### ISSUE TITLE
milmag.pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#11950]
Cookies

**Comment by krystian3w** [comment]
Ja nie mam, jaka przeglądarka, jaki dodatek do przeglądania filtrów, czy zaktualizowałeś filtry przed zgłoszeniem.

Bo już mamy filtr z sprzed 5 dni i dalej działa:
https://github.com/MajkiIT/polish-ads-filter/blob/80a73b4f9a40e37fc8753b541d11a729e6c97fff/cookies_filters/adblock_cookies.txt#L998

**Comment by kolor33** [comment]
Firefox 65 i uBlock original .Dalej widać te informacje o cookies .

**Comment by krystian3w** [comment]
To tak, czy tą stronę masz ustawioną jako "startową" / "domową" lub jest automatycznie odzyskiwania z przywracania ostatniej zamkniętej sesji?

**Comment by kolor33** [comment]
Nie to jest jakaś tam strona .Żadne przywracanie .

**Comment by krystian3w** [comment]
Inne cookies ci wycina?

**Comment by kolor33** [comment]
Nie rozumie co mi wycina .

**Comment by krystian3w** [comment]
Na innych stronach, może ktoś ci odznaczył lub usunął filtr ciasteczkowy z subskrybowanych?

**Comment by krystian3w** [comment]
Oraz tak mają być skonfigurowane opcje w zakładce filtrów:

![image](https://user-images.githubusercontent.com/35370833/52277640-7990c300-2955-11e9-8cf8-47805196d150.png) |
--- |

"**Przetwarzaj i stosuj filtry kosmetyczne**" koniecznie zaznaczone.

**Comment by kolor33** [comment]
czy te filtry wystarcza 
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda​​​​​5
​​POL: Oficjalne polskie filtry przeciwko alertom o Adblocku

**Comment by kolor33** [comment]
Mam to włączone .

**Comment by krystian3w** [comment]
Nie, nie wystarczą, musisz sobie dodać:

```
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt
```

[Polskie Filtry RODO-Ciasteczkowe Subscribe][Polskie Filtry RODO-Ciasteczkowe Subscribe]*

\* - link ten może nie działać, wtedy ręcznie musisz dodać lub przeładować zgłoszenie "`milmag.pl #11950`"


[Polskie Filtry RODO-Ciasteczkowe Subscribe]: https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt&title=Polskie%20Filtry%20RODO-Ciasteczkowe

**Comment by kolor33** [comment]
No teraz inna gadka .Działa .Nie widzę tego dziadostwa .Dzięki .

Ten link co podałeś tez działa i się wgrał do Ubloka

**Comment by krystian3w** [comment]
U mnie nigdy nie działa po wklejeniu do odpowiedzi, dopiero odświeżenie go naprawia.
