### ISSUE TITLE
AdblockList.org - blokuj reklamy na polskich stronach

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1195]
http://adblocklist.org/adblock-pxf-polish.txt

**Comment by Isamaul** [comment]
> Last modification: 15-07-2012 12:09:08 (CEST)

Nie będzie to problemem? Lista może być nieaktualna. Być może warto sprawdzić każdy z filtrów, czy się nie powtarzają z już istniejącymi regułami - aby uniknąć redundancji. Zweryfikowanie każdego osobno jest lepszą opcją.

**Comment by xxcriticxx** [comment]
to bendzie hyba juz dead dead

**Comment by MajkiIT** [comment]
Wydaje mi się, że po 4 latach ta lista już jest umarła i nie ma sensu szukać czegoś co się przyda.
