### ISSUE TITLE
thezoereport.com

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#11956]
Cookies

**Comment by krystian3w** [comment]
Popularne jakieś, bo nie widzę :poland:.

**Comment by hawkeye116477** [comment]
Zagraniczne mało popularne w :poland: to raczej do I don't care about cookies.

**Comment by krystian3w** [comment]
Lub do filtrów własnych: `thezoereport.com##body > div > .aP.aO > .aQ`

Ale nie powiem świetne klasy.

**Comment by krystian3w** [comment]
@kiboke try cut or accept cookies on `https://www.thezoereport.com/`.

**Comment by kiboke** [comment]
`thezoereport.com##body > div > .aP.aO > .aQ` is not a good filter since these classnames are random and already changed from my point of view. Perhaps: `thezoereport.com##body > div > div[class*=" "]`

**Comment by krystian3w** [comment]
Also try accept with script or use slower procedrual filtering.
