### ISSUE TITLE
pracawgdansku.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1196]
ad block poprawak potrzebna

http://pracawgdansku.com.pl/details,10483401-lt.html

Zauważyliśmy, że korzystasz z wtyczki AdBlock.
Niektóre elementy naszych stron mogą wyświetlać się niepoprawnie.

Wyłącz wtyczkę AdBlock dla TROJMIASTO.PL»

Nie wyświetlamy wielkich, irytujących reklam przesłaniających treść,
a te które prezentujemy są źródłem utrzymania portalu.

**Comment by MajkiIT** [comment]
niestety nic nie widzę ...

**Comment by xxcriticxx** [comment]
ten duzy szary box co jest tam jest adblock
