### ISSUE TITLE
deepbrid.com

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#12006]
### Zrzut ekranu
https://i.ibb.co/7S4rK6x/s.png

### Link bezpośredni
https://www.deepbrid.com/adblock?return_url=https%3A%2F%2Fwww.deepbrid.com%2Fdl%3Ff%xxx

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wygenerować link
2. Przejść do pobrania

### Moja konfiguracja
Firefox

Ublock

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by garrrgul** [comment]
Nie ten adres, do angielskojęzycznych stron ten tracker: 
https://github.com/uBlockOrigin/uAssets/issues.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/4806

**Comment by krystian3w** [comment]
@Barticf fałszywy link, niby na jego podstawie nie można ubić komunikatu.

**Comment by Barticf** [comment]
> 
> 
> @Barticf fałszywy link, niby na jego podstawie nie można ubić komunikatu.

https://www.deepbrid.com/dl?f=9d4db48d58c857abffaeaa3a542fdaa9
