### ISSUE TITLE
buyblo.com/pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#12005]
Rodo

**Comment by hawkeye116477** [comment]
A ja widzę, jak zescrollujesz trochę, to wskakuje.

**Comment by krystian3w** [comment]
U mnie jak zwykle nie, wspaniały Firefox gdzieś wywalił.

**Comment by krystian3w** [comment]
Zobaczę w Chrome.

**Comment by krystian3w** [comment]
I dupa, raz wyskoczyło a uBlock Origin powiedział, że nie będzie działał element picker.

**Comment by xxcriticxx** [comment]
@krystian3w 

![capture](https://user-images.githubusercontent.com/15007183/52300688-87931380-2956-11e9-83ce-cd833ac041e0.PNG)

**Comment by krystian3w** [comment]
No już wyciął na dev:

![obraz](https://user-images.githubusercontent.com/35370833/52300728-e5405380-2988-11e9-9a33-8c879176e2f4.png) |
--- |
