### ISSUE TITLE
gazetkonosz.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#12008]
https://www.gazetkonosz.pl/leroy-merlin/aktualna-gazetka-od-srody-23-01-2019-2/?page=10

Trzeba kilka razy zmienić stronę gazetki i pojawia się:
![image](https://user-images.githubusercontent.com/11385099/52333474-a3052980-29fd-11e9-9d53-ce46bf2a7f76.png)

**Comment by krystian3w** [comment]
nic nie trzeba zmienić mam od razu:

```
gazetkonosz.pl###overlayAd
```

**Comment by krystian3w** [comment]
Reklama jest na każdej "5" stronie np. 15:

```
https://www.gazetkonosz.pl/leroy-merlin/aktualna-gazetka-od-srody-23-01-2019-2/?page=15
```

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję
