### ISSUE TITLE
jedenslad.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12009]
https://jedenslad.pl
https://ride.jedenslad.pl
![opera zdjecie_2019-02-06_123604_jedenslad pl](https://user-images.githubusercontent.com/36385327/52338877-e1094a00-2a0b-11e9-8836-3ce592937dbe.png)

**Comment by krystian3w** [comment]
```
jedenslad.pl##.popup-overlay.js-gdpr
jedenslad.pl##.noscroll:style(overflow: auto !important;)
```

chyba, że coś psują bez zgody.
