### ISSUE TITLE
open.fm

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#12015]
Niby się popsuło (u mnie np. nie chce się załadować i polecają aplikacje na Androida) i AdGuard poluzował jakiś regex na anty-adblock a u nas może blokuje jakiś regex anty-reklamowy.

`https://open.fm/play/27`

**Comment by xxcriticxx** [comment]
@krystian3w na chromie wszystko gra

![capture](https://user-images.githubusercontent.com/15007183/52377550-3b69d100-2a33-11e9-98e6-61da487dc5be.PNG)

**Comment by krystian3w** [comment]
A u mnie na Firefox nie:

![obraz](https://user-images.githubusercontent.com/35370833/52378038-e9db3980-2a66-11e9-9985-dbc6cba89c6f.png) |
--- |

**Comment by xxcriticxx** [comment]
jak tak mialem na poczatku ale potem player sie zaladowal

**Comment by krystian3w** [comment]
U mnie się ładuje gdzieś na tym tekście mniejszą czcionką i znika.

**Comment by xxcriticxx** [comment]
na foxie dzial tez player jest za RODO muzyka dziala

![capture](https://user-images.githubusercontent.com/15007183/52378284-46bdfc00-2a35-11e9-8d42-9754706faeb4.PNG)

**Comment by krystian3w** [comment]
Na te rodo nie ma mocnych, trzeba by zaufać adamowi że chyba nie psuje gemiusa i blokować cały WP lib lub tylko akcje popupa że niby się wykonał.

**Comment by xxcriticxx** [comment]
@krystian3w zamykamy temat?

**Comment by krystian3w** [comment]
Jak nie jesteśmy w stanie odtworzyć na innych to możemy zamknąć.

W wolnym czasie zobaczę wyłączając listy.

**Comment by krystian3w** [comment]
Naprawiłem sobie, widać nie można było globalnie używać:

```
||wpcdn.pl^$script
```
