### ISSUE TITLE
hyperreal.info

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#12014]
Pozostałości po reklamach:

![image](https://user-images.githubusercontent.com/11385099/52344738-cf2fa300-2a1b-11e9-83c6-dd47efccd7b8.png)

**Comment by krystian3w** [comment]
``
##.makhaslo
```
```
###acid
``

prawej nie mam.

**Comment by mathew85** [comment]
Zapomniałem o linku:
https://hyperreal.info/talk/

**Comment by krystian3w** [comment]
no to na tamto może być: `##.row > .acidacid`


Tylko nie wiem jaki kwas brali twórcy strony...

(acid - kwas, nie wiem czy to coś znaczy w "slangu webmasterów").
