### ISSUE TITLE
wiadomosci.wp.pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#12019]
Przy włączonym Ublock wejście w artykuły linki nie działają .Nie idzie wejść i czytać artykuły.
Po wyłączeniu Ubloka bez problemu ale reklamy się lądują na stronie .

**Comment by MajkiIT** [comment]
@krystian3w @xxcriticxx zerkniecie ? ja nie mam tego. 
@kolor33 Jaka przeglądarka?

**Comment by kolor33** [comment]
Firefox 65

**Comment by krystian3w** [comment]
Jakieś wp spa niedostępne:

![obraz](https://user-images.githubusercontent.com/35370833/52441546-35eab480-2b21-11e9-8754-f0e72d523f8e.png) |
--- |

**Comment by krystian3w** [comment]
`wiadomości.wp.pl#@#+js(set-constant.js, WP.gdpr.init, noopFunc)` i niby kilkalność wraca, kosztem migania resztek po reklamach.

**Comment by krystian3w** [comment]
`wp.pl#@#+js(set-constant.js, WP.gdpr.init, noopFunc)`

ale jest u mnie klikalne za drugim razem, i nowy komunikat błędu:

![obraz](https://user-images.githubusercontent.com/35370833/52442339-240a1100-2b23-11e9-9f52-eb65f014dc80.png)
`ReferenceError: wve2rdb`

**Comment by seba2282** [comment]
Ktoś pisze o wiadomosi.wp.pl? 
<img width="960" alt="reklammasa" src="https://user-images.githubusercontent.com/16944478/52469808-c8746d80-2b8c-11e9-925c-fb09d2b5c207.png">

Może to zablokujecie też?

**Comment by kolor33** [comment]
Nie ktoś pisze tylko ja .Pracownik FSB of course this is joke .

**Comment by seba2282** [comment]
Chodzi mi o tą masę reklam co jest tutaj. Ekipa Polish Filters, możecie je zablokować regułami?

**Comment by xxcriticxx** [comment]
@MajkiIT od czasu do czasu mi wyskakuje ze strona nie istnije ale potem artykow sie laduje

**Comment by krystian3w** [comment]
@xxcriticxx  WP pada na chwilę może.

@seba2282  - niestety to nie takie łatwe, jak one umieją uciekać po 1 odświeżeniu lub są z powodu akceptowania RODO, bo nie mamy jak wyciąć na `homebook` / `forum.dobreprogramy.pl` / `sportowefakty.wp.pl` i może czasem `open.fm`.

**Comment by seba2282** [comment]
Niby Adguard Team zafixował problemy z updatem filtrów, ale player od konkretnego radia na open.fm wyświetla reklamy. One są tylko w playerze. Reszta wyglądała na fixed. Edge z Adguard i wszystkie filtry co mam aktywne (bez tych problematycznych) i z blokowaniem pożądanych reklam.

**Comment by krystian3w** [comment]
Oni mają swoje lepsze reguły skryptowe, tak bym powiedział.

**Comment by xxcriticxx** [comment]
@krystian3w adguard?

**Comment by krystian3w** [comment]
Jak AdGuard nie zamulał `dobrychprogramów` i `komórkomanii` i nie psuje wykresów giełdowych na `money` to myślę że mają lepsze.

**Comment by seba2282** [comment]
To może napiszę jeszcze prośbę o open.fm, aby pozbyli się tych reklam już w konkretnych playerach. 😁 
Jak widać, UBO/Nano sobie nie radzą zbytnio nawet po dodaniu filtrów dodatkowych. Albo ich twórcy już mają powoli olew przez informacje o nowym api w chromium. Adguard serio może być przygotowany na zmiany.

**Comment by krystian3w** [comment]
No wiesz co, my byśmy wycieli jakimś regexem ale  @salionPL potwierdza, że one psują odtwarzacz i trzeba więcej klikać play lub nagle samo się przerywa - https://github.com/MajkiIT/polish-ads-filter/issues/10013#issuecomment-440659686.

**Comment by kolor33** [comment]
To znaczy nie da się tego opanować.???

**Comment by krystian3w** [comment]
open.fm raczej na razie nie, a `widadomosci.wp.pl` musiałyby mieć przepisane reguły skryptowe jak nie widzi ci się otwieranie rolką myszy w nowej karcie.
