### ISSUE TITLE
promocyjni.interia.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#12013]
https://promocyjni.interia.pl/castorama/gazetka-promocyjna-lazienka-47739#page=7

Tutaj też reklama po kilku  zmianach strony:
![image](https://user-images.githubusercontent.com/11385099/52339298-03e82e00-2a0d-11e9-8991-1bd3f79791df.png)

**Comment by MajkiIT** [comment]
```
promocyjni.interia.pl##.l-app__content__paper-fold._95ssv1s > div
promocyjni.interia.pl##._m2boqwj
promocyjni.interia.pl##[id^="slot-"]
promocyjni.interia.pl##.l-app__content__paper-fold._qmandit
```

**Comment by krystian3w** [comment]
@MajkiIT  to jakieś `_95ssv1s` się zmienia np. inne na 10 stronie.
