### ISSUE TITLE
dailyweb.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#12025]
![capture](https://user-images.githubusercontent.com/15007183/52476457-ad920100-2b6c-11e9-86df-fa37cabbdc3a.PNG)

**Comment by krystian3w** [comment]
Jak nic nie robi to może być i:

`##.adwse-blockerr` 

chyba że szybko, dopisują kolejne r lub nagle będzie `blockers` / `blockert`...

**Comment by krystian3w** [comment]
Dodatkowo reklamy:

https://dailyweb.pl/canonowskie-zawirowania-czyli-kolejny-przeciek/

![obraz](https://user-images.githubusercontent.com/35370833/52504539-0f904c00-2be9-11e9-948e-13b9cf1e02f5.png)

np.:

```
###text-18
```
