### ISSUE TITLE
answers.microsoft.com/pl-pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#12027]
cookies 

test link:
https://answers.microsoft.com/pl-pl/mobiledevices/forum/all/lumia-535-dual-sim-bateria-sie-nie-laduje/8c261fea-e28a-4347-89d0-d05c29f5e5ee

**Comment by krystian3w** [comment]
`microsoft.com###msccBanner`

Może czas nie bawić się z tym pod każdy serwis.
