### ISSUE TITLE
fiatpunto.com.pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#12029]
Widoczna informacja o Ublock .

**Comment by xxcriticxx** [comment]
@kolor33 to jest message co user dostaje jak jest wykryty adblock

**Comment by kolor33** [comment]
No dobra ale nie widzę treści i muszę wyłączyć Ubloka .

**Comment by xxcriticxx** [comment]
@kolor33 masz konto do forum? podaj test link please

**Comment by kolor33** [comment]
Nie nie mam pokazuje mi to 
http://fiatpunto.com.pl/1.png
http://fiatpunto.com.pl/2.png

**Comment by krystian3w** [comment]
A jak to odtworzyć?

**Comment by krystian3w** [comment]
```
<script type="text/javascript">
if (blokowanie_reklam) {
 window.location.href = "http://fiatpunto.com.pl/adb.htm";
}
</script>
``


dla liska:

```
fiatpunto.com.pl##^script:has-text(blokowanie_reklam)
```

**Comment by krystian3w** [comment]
AdBlock / ABP:

```
@@||fiatpunto.com.pl/adsense.js
```

**Comment by krystian3w** [comment]
@olegwukr  jak chcesz możesz spróbować dopuścić plik `adsense.js`, bo na razie ma tylko parametr przekazujący wartość false.

**Comment by kolor33** [comment]
Czyli muszę sam dodać regułę .Nie dopiszesz tego do listy Ubloka.

**Comment by MajkiIT** [comment]
@kolor33 Oleg dodał
https://github.com/olegwukr/polish-privacy-filters/commit/708f27212a9682c72032d38e648d4ea26a9c3c66#diff-6de60f294b8bd23c752f8fcbece875b1

**Comment by krystian3w** [comment]
Jak będą wyciekać reklamy to daj znać, wtedy się przyblokuje plik i wykorzysta html filtering i skryptowe przekazywanie, że można wyświetlać reklamy.
