### ISSUE TITLE
mmorpg.org.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1204]
Strona wykrywa adblocka - `http://mmorpg.org.pl/`

![image](https://cloud.githubusercontent.com/assets/11742596/17890735/0ba68e86-6938-11e6-8a57-dff3dd4ad5fd.png)

Na przykład:
`@@||mmorpg.org.pl/imads.js$script`
lub po prostu
`mmorpg.org.pl###myHello`

Oprócz tego, jak kliknie się gdzieś z prawej lub lewej strony (zaznaczyłem na niebiesko na obrazku), to wyskakuje okienko z reklamą.
Na przykład:
`||bit.ly/2a$popup,domain=mmorpg.org.pl`

**Comment by MajkiIT** [comment]
Dzięki

**Comment by Warlander** [comment]
Blokada adblocka została nieco "ulepszona", teraz działa na nią następujący skrypt (choć pewnie istnieje jakiś bardziej optymalny): 
`mmorpg.org.pl##DIV[style*="position: fixed"]`

**Comment by MajkiIT** [comment]
u mnie tego nie ma. @F4z u ciebie jest ten monit?

**Comment by F4z** [comment]
Ja też nie mam tego komunikatu.
Ta reguła, która została dodana do polskiej listy powinna działać:
'@@||mmorpg.org.pl/imads.js$script'

**Comment by F4z** [comment]
Strona znowu wykrywa adblocka - `http://mmorpg.org.pl/`
Na przykład:
`@@||mmorpg.org.pl/*ads.js$script`
lub coś takiego jak podał Warlander:
`mmorpg.org.pl##div[id][style*="position: fixed"]`
Ewentualnie obie reguły.

**Comment by MajkiIT** [comment]
@F4z dzięki dodałem.
