### ISSUE TITLE
http://forsal.pl/

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1206]
forsal.pl###a_201

**Comment by F4z** [comment]
Zgłaszam to tutaj, bo to są powiązane ze sobą strony.

Podobnie jest na prawnik.pl - `http://www.prawnik.pl/prawo/prawo-w-praktyce/artykuly/969683,msz-pokazuje-swoja-klase-w-strasburgu.html`
`prawnik.pl###a_201`

Na gazetaprawna.pl też to jest, ale żeby zobaczyć tę pustą przestrzeń przewiń na dół strony i wróć na górę, powinno się pokazać - `http://www.gazetaprawna.pl/artykuly/970081,usa-wspolpracuja-z-turcja-w-ocenie-dowodow-przeciwko-gulenowi.html`
`gazetaprawna.pl###a_201`
Jeszcze tuż nad komentarzami jest taka pusta przestrzeń, oraz na dole strony.

![image](https://cloud.githubusercontent.com/assets/11742596/17938984/af2356ac-6a28-11e6-933e-cb4f1a2fa5c7.png)

![image](https://cloud.githubusercontent.com/assets/11742596/17938994/bbc06ad0-6a28-11e6-97f4-6374936ba511.png)

Na przykład:
`gazetaprawna.pl##.col-xs-off.tpl_ads_adsense.tpl_std_module`
`gazetaprawna.pl##.tpl_ads_adexon.tpl_std_module`

**Comment by MajkiIT** [comment]
@F4z dzięki dodane.
