### ISSUE TITLE
malopolska.beskidzka.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12068]
reklamy tzn dziwne bo baner pod headerem próbóje się załadować i czasami strona skacze oraz euczęści ( po prawo )

**Comment by krystian3w** [comment]
ta strona to niby jedna wielka grafika xd.

**Comment by krystian3w** [comment]
`home.pl###metaslider_240 > A`

**Comment by krystian3w** [comment]
`home.pl###metaslider_240 > A`
`home.pl##.textwidget > ul > li > h3, .textwidget > ul > li > ul > li > p > img`

**Comment by krystian3w** [comment]
```
home.pl###metaslider_240 > A
home.pl###text-12 > .textwidget > ul > li h3, #text-12 > .textwidget > ul > li img
```

**Comment by krystian3w** [comment]
`serwer1418128.home.pl###header-right-sidebar > .widget_metaslider_widget`
