### ISSUE TITLE
forum.pcformat.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1207]
Pomiędzy postami czasami jest link/ogłoszenie sponsorowane - `http://forum.pcformat.pl/Karta-graficzna-do-okolo-1300-zl-t?pid=3754334#pid3754334`

![image](https://cloud.githubusercontent.com/assets/11742596/17940657/66b39488-6a30-11e6-9495-da8d6d1f19e4.png)

Na przykład:
`forum.pcformat.pl##.classic.post:not([style]):not([id])`

Ewentualnie coś takiego, tyle że ta reguła działałaby jedynie w uBlocku:
`forum.pcformat.pl##.classic.post:has([alt="Link sponsorowany"][title="Link sponsorowany"])`

**Comment by xxcriticxx** [comment]
mozna dodac do adblock_ublock.txt i do normalnej adblock.txt

**Comment by xxcriticxx** [comment]
btw droga ta karta do 1300 zl :(

https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=graphics+card

**Comment by F4z** [comment]
Zamykam, bo reguła została dodana - https://github.com/MajkiIT/polish-ads-filter/commit/4bf1e6bf1750c657c4e405785d5d72dca585b3bf#diff-711027ed0794992ae3b8710d874f3df7R314
