### ISSUE TITLE
CMC Media

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#12083]
### Link bezpośredni
```
ciechanowinaczej.pl
infosiedlce.pl
ibialoleka.pl
izoliborz.pl
imokotow.pl
golub-cgd.pl
```

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Reklamy.
Jakby co, to przypominam, ta reguła `/static/files/inline_images/$image` była :boom: :smile:

**Comment by MajkiIT** [comment]
@hawkeye116477 to może tak ?
`ciechanowinaczej.pl,infosiedlce.pl,ibialoleka.pl,izoliborz.pl,imokotow.pl,golub-cgd.pl##[class*="l-box-"] > P > A > IMG[src*="/static/files/"]`

**Comment by hawkeye116477** [comment]
No chyba jest ok :smile:.
