### ISSUE TITLE
upi.com

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#12099]
Cookies

**Comment by krystian3w** [comment]
Znów brak polskiego, brak dowodów popularności w polszy / wśród Polonii.

**Comment by krystian3w** [comment]
Jak coś zgłosiłem Admiral do uAsset, dziwne, że popup ma `i18l`... https://github.com/uBlockOrigin/uAssets/issues/4881

**Comment by krystian3w** [comment]
Do filtrów własnych może dodaj:

`||vendorlist.consensu.org/vendorlist.json$xmlhttprequest,domain=www.upi.com`

lub: `||admiral.mgr.consensu.org^$domain=www.upi.com`

Prawie się nabrałem, że to Anty-AdBlock z admirala.

**Comment by kolor33** [comment]
wpisze to na listę jak możesz .Ja tam ręcznie nic nie manipuluje .

**Comment by krystian3w** [comment]
@MajkiIT jak mierzyć popularność zagranicznych stron przed dodaniem?

**Comment by hawkeye116477** [comment]
No to na pewno nie jest takie popularne, parę wyjątków zrobiliśmy, więcej pewnie nie będzie.
@kolor33 Od takich stron jest I don't care about cookies albo Fanboy, oczywiście poleciłbym bardziej zainstalować rozszerzenie I don't care about cookies z AMO/Chrome Store, bo jest skuteczniejsze niż zwykła lista w uBO.

**Comment by kiboke** [comment]
Blocking pattern caringzinc.com/v2 will do the trick.
