### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by Asthaven** [MajkiIT/polish-ads-filter#1210]
Podczas przełączania się pomiędzy stronami pojawiają się reklamy ze strony PopAds.net Przeglądarka otwiera je jako osobne strony przypominające aplikacje. Nie jestem w stanie namierzyć podstrony lub adresu aby blokować te reklamy nie blokując jednocześnie całej strony.

**Comment by MajkiIT** [comment]
masz easylist?

**Comment by xxcriticxx** [comment]
5 sec counter jest jak film sie odpala

**Comment by xxcriticxx** [comment]
forum wants to show notifications allow or block na chrome
