### ISSUE TITLE
budujmase.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#12103]
RODO

**Comment by krystian3w** [comment]
w dodatku, też "h-f media" niby.

**Comment by hawkeye116477** [comment]
@xxcriticxx Nadal nie masz PCZ?

**Comment by xxcriticxx** [comment]
@hawkeye116477 what is PCZ?

**Comment by hawkeye116477** [comment]
@xxcriticxx Polska Ciasteczkowa Zgoda => `https://github.com/PolishFiltersTeam/PolishCookieConsent#jak-zainstalowa%C4%87` :smile:.

**Comment by krystian3w** [comment]
Nie będzie miał bo nie odrzuca zgód cookies.

**Comment by xxcriticxx** [comment]
doklanie

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale zgoda buduje, a nie zgoda rujnuje :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 ja tylko te strony zwiedzam a nie uzywam
