### ISSUE TITLE
fiat-partner.pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#12108]
Rodo

**Comment by xxcriticxx** [comment]
@kolor33 Grrr dodajesz mi roboty!

**Comment by kolor33** [comment]
sorry for it .

**Comment by xxcriticxx** [comment]
@kolor33 jak podajesz strony to bez `http` i bez `//` please

**Comment by krystian3w** [comment]
@hawkeye116477 które na zasięg globalny:

`||global.silnet.pl/media/js/vue/silnet-privacy-policy.vue$xmlhttprequest`

`||global.silnet.pl/media/js/vue/silnet-privacy-policy-popup.vue$xmlhttprequest`

**Comment by hawkeye116477** [comment]
Może to pierwsze, krótsze, to może nic się nie sknoci :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 ja dorabiam za bota @MajkiIT cos testowa z firebot ale nie wiem jak sie skonczylo

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale firebot jest do robienia zgłoszeń bez posiadania GH, a ja mówię o bocie do etykiet => `https://github.com/PolishFiltersTeam/PolishWorkflowBot` :smile:

**Comment by xxcriticxx** [comment]
@hawkeye116477 zagadaj z @MajkiIT ty najlepjej w tym obgadany

**Comment by krystian3w** [comment]
Bot do etykiet nie poprawia na razie tytułów, nawet w EI.

**Comment by hawkeye116477** [comment]
Jakich tytułów?

**Comment by hawkeye116477** [comment]
No tak, ale etykiety dodaje, to zawsze mniej roboty :smile:.
