### ISSUE TITLE
pl.mouser.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#12106]
cookies

**Comment by krystian3w** [comment]
Nie potrafię włączyć polskiego, więc jak przelicznik do czegoś nie jest wystarczający to odpada.

**Comment by hawkeye116477** [comment]
@xxcriticxx We won't fix that, I don't care about cookies is your friend bro.

**Comment by krystian3w** [comment]
`@Jaziko` a ten to kto / skąd?

Mam w podpowiedzi jak piszę `@`.
