### ISSUE TITLE
wbudowie.pl

### ISSUE THREAD

**Issue by gaargul** [MajkiIT/polish-ads-filter#12148]
Reklamy:

1 po lewej:
![ss508](https://user-images.githubusercontent.com/47386482/52899394-e293f880-31e9-11e9-9690-ee05adf84ef6.png)

2 na środku:
![ss509](https://user-images.githubusercontent.com/47386482/52899398-e758ac80-31e9-11e9-8966-8068ce8bde15.png)

**Comment by hawkeye116477** [comment]
@MajkiIT Narozrabiałeś.
Na Discordzie się ktoś odezwał:
`Witajcie, mam pytanie dotyczące tego zgłoszenia: https://github.com/MajkiIT/polish-ads-filter/issues/12148. Klasa która została dodana do filtrów jest troszeczkę zbyt ogólna i ukrywa nam też treści na stronie to tu to tam. Macie jakiś schemat postępowania w takich wypadkach?`

**Comment by krystian3w** [comment]
Opcjonalnie niech przebuduje szablon na jakiś grid / flexbox bez boostrapa?

**Comment by broiniac** [comment]
@krystian3w Być może następny prace rozwojowe po stronie frontendu wprowadzą grid/flexbox, na chwilę obecną jednak taka zmiana nie jest to opłacalne z punktu widzenia organizacji. Bootstrap nie jest w użytku.

**Comment by krystian3w** [comment]
A info o dev to z szklanej kuli? Równie dobrze ktoś może często przegląda stronę.

**Comment by broiniac** [comment]
@krystian3w @hawkeye116477 Chłopaki, ja tu jestem xD

**Comment by krystian3w** [comment]
Pr chyba zaakceptowany niestety do 2 dni jak adblocki go zassają...

Jak nowe "[rel=nofollow]" za dużo tnie to się poprawi "do trzech razy sztuka" (mięsa).

https://github.com/MajkiIT/polish-ads-filter/blob/155a7cae481ecf396c01485b5ec0397c9a33b485/polish-adblock-filters/adblock.txt#L2801

**Comment by krystian3w** [comment]
Teraz pewnie wycina linki z komentarzy.

**Comment by hawkeye116477** [comment]
@krystian3w Jest nowa propozycja, zapraszam na Discorda, tak jak zresztą Pana Prezesa :smile:
