### ISSUE TITLE
fabsdeals.com

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#12149]
jest blokada, nie mozna pobrac torrenta, https://fabsdeals.com/I6Jw

**Comment by krystian3w** [comment]
Nie polskie do uAssets.

**Comment by krystian3w** [comment]
@mapx- / @okiehsch / @ZaphodBeebblebrox fyi.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/4920

The fix works on my end.

**Comment by krystian3w** [comment]
Thank you!

**Comment by krystian3w** [comment]
@lukjan32 powinno pomóc wymuszenie aktualizacji filtra "uBlock filters".

![xc](https://user-images.githubusercontent.com/35370833/52909715-52a78a80-328d-11e9-8b7c-2051d0bc7841.gif)

**Comment by lukjan32** [comment]
dziala

**Comment by lukjan32** [comment]
nie pomoglo, znow tak samo, teraz nie dziala wymuszenie

**Comment by krystian3w** [comment]
A bo kupili nową domenę `https://geki.tech/I6Jw`...

**Comment by lukjan32** [comment]
da sie poprawic?

**Comment by krystian3w** [comment]
Tak, jak **`@`okiehsch ** poprawi adresy.

**Comment by lukjan32** [comment]
dzieki, jakby co, bede pisal tu.

**Comment by lukjan32** [comment]
znow jest blokada

**Comment by krystian3w** [comment]
Znowu nowa domena?

Poza tym twój link wygasł i nie ma jak pobrać torennta.

**Comment by krystian3w** [comment]
Już podrzucone do uAsset. Jedynie nie wiem jak szybko znajdą wolną chwilę na aktualizację.

**Comment by lukjan32** [comment]
z tej strony pobieram psarips.net

**Comment by krystian3w** [comment]
Niby od wczoraj naprawione, wymuś uaktualnianie filtrów.

**Comment by lukjan32** [comment]
jest

**Comment by krystian3w** [comment]
Wyczyść całą pamięć podręczną z Opery / chrome i ponów aktualizacje filtrów?

Lub spróbuj około 18:00 i już musi pobrać najnowsze filtry.

**Comment by lukjan32** [comment]
dziala

**Comment by lukjan32** [comment]
znow jest blokada

**Comment by krystian3w** [comment]
Naprawione jakieś 12 godzin przed twoim napiasniem o tym.

**Comment by lukjan32** [comment]
niestety nie, dalej blokada.

**Comment by krystian3w** [comment]
No to wyczyść znowu pamięć podręczną z ustawień przeglądarki, najlepiej z minimum tygodnia czasu.

Potem zaktualizować filtry w uBO `uBlock filters`.

**Comment by lukjan32** [comment]
na tej stronie psarips.net, sa filmy w kodeku x265 hevc

**Comment by krystian3w** [comment]
I co niby ci da aktualizacja kodeka raz na tydzień?

Za słaba karta graficzna i procesor to musisz wymienić by oglądać 4k / 8k.

**Comment by lukjan32** [comment]
plik filmu ma 900 mb, zamiast 2 gb w x264

**Comment by lukjan32** [comment]
znow blokada jest

**Comment by krystian3w** [comment]
Znowu jakby naprawili przed tobą, to z króliczkiem to klikaj w lewej zielonej kolumnie.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/5343

**Comment by lukjan32** [comment]
u mnie jest
![1](https://user-images.githubusercontent.com/17565773/57032669-3b045f00-6c4b-11e9-8d67-45bcd984f460.jpg)

**Comment by krystian3w** [comment]
To aktualizuj link przy zgłaszaniu to już nie są chyba fabdealsy do skracania linków...

**Comment by krystian3w** [comment]
```
fc.lc##+js(abort-on-property-read.js, app_vars.force_disable_adblock)
fc.lc##+js(abort-on-property-write.js, adBlockDetected)
/sw.js$script,domain=fc.lc
```

**Comment by lukjan32** [comment]
aha, dobra, bedzie dodanie do filtrow?

**Comment by lukjan32** [comment]
ok, juz jest

**Comment by krystian3w** [comment]
niby nikt nie zgłosił to zgłosiłem to powyższe i dodali coś podobnego.

**Comment by lukjan32** [comment]
aha, i pomoglo.

**Comment by krystian3w** [comment]
To pamiętaj by dawać url i będę sprawdzać czy jest zgloszone do uAsset.

**Comment by lukjan32** [comment]
dobra

**Comment by lukjan32** [comment]
link fc.lc

**Comment by krystian3w** [comment]
Cloud flare to nie anty-adblock ani błąd 404:

```
Error: The requested address '/I6Jw' was not found on this server.
```

**Comment by krystian3w** [comment]
`clk.ink/I6Jw` mi działa obecnie.

**Comment by lukjan32** [comment]
ok, mi tez juz dziala.

**Comment by lukjan32** [comment]
znow jest blokada, na innej podstronie.

**Comment by krystian3w** [comment]
Y ktoś odkopał wątek lub GitHub odkopuje powiadomienia sprzed kilku miesięcy.
