### ISSUE TITLE
e-madame.pl

### ISSUE THREAD

**Issue by gaargul** [MajkiIT/polish-ads-filter#12158]
Sociale napisy/kontenery po prawej:

![ss513](https://user-images.githubusercontent.com/47386482/52899580-df017100-31eb-11e9-9c35-93c5d1a23360.png)

**Comment by krystian3w** [comment]
W sumie to tam jest od `n` `a` `j` `e` `b` `a` `n` `i` `a` facebooka

niby przegapiasz aż 5 elementów: `www.e-madame.pl##.widget-item.widget_facebook`

**Comment by krystian3w** [comment]
OK, w takim razie trzeba użyć `#facebook-1`
