### ISSUE TITLE
gdanskrebiechowo.pl + zbiorkom.pl

### ISSUE THREAD

**Issue by gaargul** [MajkiIT/polish-ads-filter#12159]
Social link na dole:

![ss514](https://user-images.githubusercontent.com/47386482/52899592-fb051280-31eb-11e9-8906-b552853da031.png)

![ss529](https://user-images.githubusercontent.com/47386482/52899881-803df680-31ef-11e9-8393-4e971f2edfe7.png)

**Comment by krystian3w** [comment]
@MajkiIT  / @hawkeye116477  - odblokowywać jakoś:

`lufthansa`?

![obraz](https://user-images.githubusercontent.com/35370833/52910321-1a587a00-3296-11e9-8e85-387e4b44f66f.png) |
--- |

bo niby wycina go pewnie filtr reklamowy lub Oleg.

**Comment by hawkeye116477** [comment]
No chyba raczej trzeba.

**Comment by krystian3w** [comment]
No to wadliwy jest polski filtr prywatności, więc raczej trzeba zrezygnować z listy.


Filtr | `##A[href*="k.tradedoubler.com/click"]`
---| ---
Lista filtrów  |Polish Privacy Filters 
Kontekst | `gdanskrebiechowo.pl`
Typ | `dom`
Adres URL | `http://gdanskrebiechowo.pl/`
