### ISSUE TITLE
annapoplawska.pl

### ISSUE THREAD

**Issue by gaargul** [MajkiIT/polish-ads-filter#12154]
Sociale:

1 bannery klikalne na środku:

![ss_008](https://user-images.githubusercontent.com/47386482/52899556-9944a880-31eb-11e9-8b44-713242c9f218.png)

2 napisy na dole:

![ss_007](https://user-images.githubusercontent.com/47386482/52899529-54207680-31eb-11e9-8db4-248c22a14852.png)

**Comment by krystian3w** [comment]
Zapraszam na :popcorn: [ Tilde glitch/freeze Preview mode in element picker #425  <sup>https://github.com/uBlockOrigin/uBlock-issues/issues/425</sup>](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fgithub.com%2FuBlockOrigin%2FuBlock-issues%2Fissues%2F425)
