### ISSUE TITLE
pierwsze-kroki.com

### ISSUE THREAD

**Issue by gaargul** [MajkiIT/polish-ads-filter#12150]
Reopen bo dalej jest jedna rzecz po prawej:

![ss510](https://user-images.githubusercontent.com/47386482/52899466-d6f50180-31ea-11e9-832e-5af87bb4d582.png)

**Comment by krystian3w** [comment]
Dziwne... 

https://github.com/MajkiIT/polish-ads-filter/blob/3220da304fa807b8e07ae4b1c3d27a757b3c6077/adblock_social_filters/adblock_social_list.txt#L2571
