### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1216]
http://miniskrypt.hubaiitv.pl/thread-54-post-779.html#pid779

**Comment by xxcriticxx** [comment]
podam link do mrknow to na kodi to przerobi

**Comment by MajkiIT** [comment]
@xxcriticxx @kasper93 @F4z 
Możecie sprawdzić czy to `http://miniskrypt.blogspot.com/2014/04/3-w-1.html` to wam działa na player.pl?
How use ==> https://www.youtube.com/watch?v=Q24rqrNCe9g

**Comment by F4z** [comment]
@MajkiIT nie działa w przypadku materiałów 360° (`http://player.pl/kolekcje/player-360,305/`), ale przy innych filmach, które sprawdziłem działało :)

**Comment by MajkiIT** [comment]
@F4z ok dzięki. No to miały mały krok do przodu.
