### ISSUE TITLE
bolesławiec.pl

### ISSUE THREAD

**Issue by gaargul** [MajkiIT/polish-ads-filter#12162]
Social ikony/przyciski na dole po prawej:

![ss517](https://user-images.githubusercontent.com/47386482/52899622-533c1480-31ec-11e9-8e8c-e92f8a03f226.png)
![ss518](https://user-images.githubusercontent.com/47386482/52899623-533c1480-31ec-11e9-8811-a0083d06d8c5.png)

**Comment by krystian3w** [comment]
@hawkeye116477 / @MajkiIT  nazwa z znakami pl czy wymusić format:

`xn--bolesawiec-e0b.pl`

**Comment by hawkeye116477** [comment]
A nie wiem, w ogóle dziwnie zrobili, zwykle adres jest bez polskich znaków.
