### ISSUE TITLE
saga.info.pl

### ISSUE THREAD

**Issue by gaargul** [MajkiIT/polish-ads-filter#12170]
Social ikona/przycisk na dole (nieklikalny, ale drażniący, już był podobny przypadek, ale nie pamiętam czy został zakwalifikowany):

![ss530](https://user-images.githubusercontent.com/47386482/52899887-9ea3f200-31ef-11e9-8ce5-423171d63ba2.png)

**Comment by krystian3w** [comment]
a po prawej wigdet wyciął AdGuard team?

Ten pójdzie do wycięcia, bo kolega obok ma linka, może założą jeszcze twittera - a tamten przykład nie dodawany bo reszta ikon marek też nie była klikalna, nie wycięto tam parterów "medialnych/strategicznych" to i nie wycinałem ikonki.
