### ISSUE TITLE
polska lista do pi-hole

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1217]
@MajkiIT podaj liste najwiekszych reklamowcow w polsce. musze zrobic liste w formacie host file.

**Comment by xxcriticxx** [comment]
gdzie masz to liste do internet explorer?

**Comment by MajkiIT** [comment]
Nie mam pod ręką. Coś postaram się przekonwertować.

**Comment by xxcriticxx** [comment]
kiedys mi podales byl link na stronie internetowej

**Comment by MajkiIT** [comment]
http://www.certyficate.it/polskie-filtry-reklam-ie-9-11/

**Comment by xxcriticxx** [comment]
@MajkiIT zrobilem cos takiego. przejrzyj moze cos trzeba zmienic lub dodac. 

[hosts.txt](https://github.com/MajkiIT/polish-ads-filter/files/446270/hosts.txt)
