### ISSUE TITLE
sokol.wp.pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#12187]
Widzi ubloka 

sokol.wp.pl/w-1979-roku-zaczela-sie-jego-historia-smiglowiec-w-3-sokol

**Comment by krystian3w** [comment]
fajnie.

**Comment by krystian3w** [comment]
Takie byle jakie na szybko: sokol.wp.pl##body > div.page ~ div[id][style="display: block;"]

**Comment by krystian3w** [comment]
Niby lepsze:

`@@||sokol.wp.pl/js/ads.js$script,domain=sokol.wp.pl`
