### ISSUE TITLE
nexto.pl hałaśliwa reklama - wywiad na każdej stronie

### ISSUE THREAD

**Issue by ap-r** [MajkiIT/polish-ads-filter#1218]
<IFRAME
src="http://get.x-link.pl/1d...4a7044534fb8,embed.html" >

Chciałabym, żeby Adblock wyciszał lub blokował takie reklamy. Nikt nie lubi autoodtwarzania czegoś, czego sam nie włączał, a filmik włącza się przy każdym przejściu między podstronami. Kupując poranną gazetę, raczej nie jesteśmy przygotowani na taki atak, prawda?

**Comment by MajkiIT** [comment]
Sprawdź coś takiego
www.nexto.pl##iframe[src^="http://get.x-link.pl/"]
