### ISSUE TITLE
polska-ie.com

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#12184]
`https://www.polska-ie.com/`

anty-adblock:

![anty-ablock](https://user-images.githubusercontent.com/35370833/52911374-5219ee80-32a3-11e9-81ec-ed8000e9e3eb.png)

---

Jakoś naprawiony w Nano Defender, więc dla AdBlock / ABP:

`@@||polska-ie.com^$generichide`

**Comment by krystian3w** [comment]
pomaga niby np.:

`@@||polska-ie.com^$generichide`

**Comment by MajkiIT** [comment]
A Pigwin tego nie wycina?

**Comment by krystian3w** [comment]
Listami filtrów nie.

**Comment by krystian3w** [comment]
Ale po zainstalowaniu niby już działa: https://addons.mozilla.org/en-US/firefox/addon/nano-defender-firefox/

@olegwukr  ratujesz użytkowników ABP / AdBlock, oni nie powinni używać Nano Defender z braku wsparcia ze strony twórcy.

**Comment by MajkiIT** [comment]
@krystian3w Dziekuję
