### ISSUE TITLE
http://www.onet.pl/  anti-adblock page lock

### ISSUE THREAD

**Issue by Zireael** [MajkiIT/polish-ads-filter#1219]
Hi,
http://www.onet.pl/ shows anti-adblock message blocking access to the website.

![image](https://cloud.githubusercontent.com/assets/3856578/18127296/77651580-6f77-11e6-9a87-7323cebea75a.png)

**Comment by MajkiIT** [comment]
Do you have latest version of filters?

**Comment by xxcriticxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/15007183/18129467/e2fdf9f2-6f58-11e6-9737-d2015b097409.PNG)

reklamy skapiec na dole

**Comment by MajkiIT** [comment]
@xxcriticxx ok dodam dzisiaj regułę.
