### ISSUE TITLE
goryiludzie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12194]
![opera zdjecie_2019-02-20_102907_goryiludzie pl](https://user-images.githubusercontent.com/36385327/53081105-715e8900-34fa-11e9-8f7b-0ed93ed4af11.png)
![opera zdjecie_2019-02-20_102919_goryiludzie pl](https://user-images.githubusercontent.com/36385327/53081106-71f71f80-34fa-11e9-97d5-c11392667b16.png)

**Comment by krystian3w** [comment]
`@||revive.goryiludzie.pl/www/dvr/alog.php$image,~third-party`

**Comment by krystian3w** [comment]
Nie umiem odtworzyć, Pingwin :penguin:  już naprawia filtrami lub `Adblock Warning Removal List` (ale oni raczej przypadkiem).

**Comment by hawkeye116477** [comment]
@xMaap Nie chcesz :chocolate_bar:  :smiley:? 
A tak w ogóle to ja nic takiego tam nie mam.

**Comment by krystian3w** [comment]
@hawkeye116477  też nie mam, dziwne to jakby nagle wywalili, bo się zawstydzili.

**Comment by xMaap** [comment]
Pojawiła się reklama rankomat

**Comment by hawkeye116477** [comment]
Ale ja tą reklamę widzę cały czas.
@MajkiIT Let's do the job :smile:

**Comment by krystian3w** [comment]
```
###horizontal > a[href*="/www/dvr/aklik.php"]
```
