### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#12217]
Są jakieś gotowe filtry na usunięcie tych fbclid które fb dodaje do zewnętrznych linków udostępnianych na tablicy ?
http://jakasstrona.pl?fbclid=wartość śledząca

**Comment by hawkeye116477** [comment]
Filtry to nie wiem czy są, ale dla FF chyba takie coś pomoże => https://addons.mozilla.org/pl/firefox/addon/facebook-container/.
W ABP jest coś takiego jak `$rewrite` i to właśnie pozwala na takie zabawy, byla już na temat dyskusja u gorhilla i gość się nie zgodził, nie chce tego dodać chyba ze względów bezpieczeństwa, bo może się potem trafić jakiś cwaniaczek, który zrobi listę z niespodzianką, przepisze adresy tak, by kierowały na wirusy.

Znalazłem też coś takiego => `https://www.michalspacek.com/using-javascript-to-modify-urls-and-hide-fbclid`, może to można dodać do skryptu ViolentMonkey i będzie działać, ale nie testowałem tego.

**Comment by krystian3w** [comment]
> trafić jakiś cwaniaczek, który zrobi listę z niespodzianką, przepisze adresy tak, by kierowały na wirusy.

Niby aż tak mocno nie można przemodyfikować - zdaniem Adblock Plus.

---

Podejrzewam, że tego też nie usunie AdGuardowe replace https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#replace-modifier (wystarczy by ograniczyli je do zakładki własne filtry i list ich autorstwa).

**Comment by hawkeye116477** [comment]
@krystian3w :penguin: ma w planach `$replace`.
Oczywiście, że mogliby je ograniczyć, ale gorhill coś na razie nie chce wprowadzać uprzywilejowanych reguł. A tymczasem `$rewrite` dodali do uBlock LLC, ale widzę też, że już zaczęli się bawić w akceptowalne reklamy, zrobili włączone dla wszystkich jako domyslne :smile:

**Comment by krystian3w** [comment]
Mnie tam zbanowali za post co nowego jest w uBO względem `uBlock LLC`... 

Nawet się nie bali podlinkować tego w opcji czemu mam bana.

**Comment by F4z** [comment]
>Podejrzewam, że tego też nie usunie AdGuardowe replace[...]

Zgadza się, `$replace` tego nie usunie, ale jedna z reguł z listy `Filtr elementów szpiegujących AdGuard` usuwa tego typu rzeczy. Oprócz tego, w wersji 3.x (na razie beta), jest coś takiego jak "Tryb Niewidzialności" i tam jest opcja do usuwania różnych parametrów z adresów.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/11742596/53289251-0d56f180-3794-11e9-9856-7ad52578258a.png)

</details>

**Comment by hawkeye116477** [comment]
Znalazłem też coś bardziej zaawansowanego => `https://addons.mozilla.org/pl/firefox/addon/requestcontrol/`, jest to tylko dla :fox_face:, ale można też samemu robić reguły

**Comment by krystian3w** [comment]
Może to javascript doczepia do linka?

Jak jest czysty przed kliknięciem / najechaniem.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/4526

**Comment by Barticf** [comment]
Z tego co widzę to jest dodawane od razu a nie taka jak z wsj (o ile tam dobrze zrozumiałem) że dopiero po kliknięciu myszką

**Comment by krystian3w** [comment]
No to tylko inny dodatek (wymienione, beta AdGuard) / skrypt pod Violentmonkey / Tampermonkey.

Może to jakoś naprawił @ublock-user w https://github.com/uBlock-user/uBO-Scriptlets/blob/master/scriptlets.txt (possible create scriplet to remove attribs from url?).

**Comment by Barticf** [comment]
Z FB Purity ktoś korzysta ? Bezpieczne to jest ?

**Comment by krystian3w** [comment]
```
facebook.com,facebookcorewwwi.onion##div[id^=hyperfeed_story_id_]:has(div[data-testid="story-subtitle"]:has(span[data-ft]:has(s > s)))

facebook.com,facebookcorewwwi.onion##[id^="hyperfeed_story_id_"]:has([data-testid="story-subtitle"] [role="link"])
```

Bo nikt ich w uBO raczej nie aktualizuje, jak raz na dzień nie działa lub w wielu miejscach jest np. w Marketplace, może ten ludzie oglądają i im nie działa.

**Comment by hawkeye116477** [comment]
```
Może to javascript doczepia do linka?
Jak jest czysty przed kliknięciem / najechaniem.
```

No tak nie do końca przed, on to usuwa po wystąpieniu żądania. Trochę takie oszustwo, bo w AMO pisze, że przed requestem jest usuwane a na GH jest napisane, że to jednak nie tak :smile:

**Comment by hawkeye116477** [comment]
`Z FB Purity ktoś korzysta ? Bezpieczne to jest ?`
A nie wiem, widzę reklamują go i polecają, a ten stripper nie działa?

**Comment by krystian3w** [comment]
Pewnie ma dość wycieków "SpPonNnSorowWWWaAaneeEEe".

**Comment by Barticf** [comment]
Działa ale tylko jeśli wejdzie się na ten link, jeśli chce się go tylko skopiować to jest nadal z tym fbclid

**Comment by krystian3w** [comment]
uBO blokowanie by ręcznie kopiować oczyszczony link:

https://github.com/kowith337/PersonalFilterListCollection/issues/19

**Comment by hawkeye116477** [comment]
Po paru latach w końcu marzenie @Barticf się spełniło, gorhill dodał `$queryprune` => https://github.com/gorhill/uBlock/releases/tag/1.31.0.
