### ISSUE TITLE
nowosci.com.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#12227]
`https://nowosci.com.pl/cos-o-przyrodzie-i-cos-o-swiecie/ar/10893033`

![obraz](https://user-images.githubusercontent.com/35370833/53300255-04722880-3845-11e9-9d49-a7c0410eef3b.png) |
--- |

~~Może w całym serwisie~~ raczej w każdym nowszym artykule.

**Comment by hawkeye116477** [comment]
Bait `@@/ads.js$domain=nowosci.com.pl`

**Comment by hawkeye116477** [comment]
Chyba trzeba będzie znowu zgłosić do @olegwukr.
