### ISSUE TITLE
expressbydgoski.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#12226]
* `https://expressbydgoski.pl/wikidotcom-wyklikaj-sobie-strone/ar/11965724`

* `https://expressbydgoski.pl/studniowki-2017-w-bydgoszczy/ar/12040414`

* `https://expressbydgoski.pl/najlepszych-bydgoszczanin-roku-2017/ar/12910211`

* `https://expressbydgoski.pl/bydgoszczanin-roku-2017-wyniki-plebiscytu/ar/12882513`

![obraz](https://user-images.githubusercontent.com/35370833/53300198-30d97500-3844-11e9-9cb8-d27854110b89.png) |
--- |

Przy pierwszym otwarciu i na innych artykułach nowszych artykułach (2018/19) nie ma.

**Comment by hawkeye116477** [comment]
`@@/reklama.js$domain=expressbydgoski.pl`
