### ISSUE TITLE
odsluchane.eu

### ISSUE THREAD

**Issue by gaarguul** [MajkiIT/polish-ads-filter#12236]
Ciasteczka na dole po prawej:

![ss568](https://user-images.githubusercontent.com/47940872/53345963-546cf000-3916-11e9-8e2e-3a1b4ccea1fc.png)

Dodatkowo ciekawostka - anty-adblock nawet po wyłączeniu adblocka:
**https://www.odsluchane.eu/top.php?r=2&m=2&y=2019**
![anim 001](https://user-images.githubusercontent.com/47940872/53345989-6484cf80-3916-11e9-9335-7427ead9c610.gif)

**Comment by krystian3w** [comment]
Pewnie trzeba anty-adblock ubić skryptem skoro zrobili wadliwy...
