### ISSUE TITLE
menshealth.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12235]
info o adblocku, " podziel się " ( po lewo ) oraz resztka ( po prawo )

**Comment by krystian3w** [comment]
#12234 / #12234 / #12233 / #12232 / #12231 


---

`##.mh-community-floating > div.title:nth-of-type(1)` - social

**Comment by MajkiIT** [comment]
@blocker999 masz nano Defender ?

**Comment by krystian3w** [comment]
Wydaje mi się, że nie ma, ale jak nie przekombinowali to się powinno dać to naprawić.

**Comment by blocker999** [comment]
@MajkiIT A widzi miałem ale wyłączony
