### ISSUE TITLE
auto-motor-i-sport.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12231]
info o adblocku oraz " podziel się " w artykułach ( po lewo ) np : https://www.auto-motor-i-sport.pl/wydarzenia/Specjalne-wydanie-auto-motor-i-sport-w-sprzedazy,36020,1

**Comment by krystian3w** [comment]
A anty-adblock ubija już Nano Defender / filtry Nano Defendera do uBO.

---

`##div.amis-community-docked > .amis-community `
