### ISSUE TITLE
mirjan24.pl

### ISSUE THREAD

**Issue by gaarguul** [MajkiIT/polish-ads-filter#12237]
RODO:

![ss_004](https://user-images.githubusercontent.com/47940872/53346383-3784ec80-3917-11e9-9a4d-a9fbb3ed05ba.png)

**Comment by krystian3w** [comment]
O wyskakuje po kliku sekundach #11662  - czyżby uciekło?

**Comment by krystian3w** [comment]
```
mirjan24.pl##body.compensate-for-scrollbar:style(overflow: auto !important;)
mirjan24.pl###fancybox-container-1:has(#gdpr)
mirjan24.pl##.compensate-for-scrollbar:style(margin-right: 0 !important;)
```

@hawkeye116477  to niby dalej działa w filtrach własnych.

**Comment by krystian3w** [comment]
@hawkeye116477  jak coś mnie nie działa z tym nowym oficjalnym Nano Adblocker 1.0.0.89 dla Firefox.

**Comment by hawkeye116477** [comment]
Ale @krystian3w wie, że to jest dla nie mających filtrowania html :stuck_out_tongue: 
Na html jest inna reguła i ona najwyraźniej nie działa

**Comment by krystian3w** [comment]
Chyba fancybox zniknął z kodu html  (doładowywany w trakcie) lub coś licybora popsuł?

**Comment by hawkeye116477** [comment]
@krystian3w No zniknął albo wcześniej ktoś się pomylił :smile:

**Comment by krystian3w** [comment]
Dobra, zaktualizowałem filtr html, mam nadzieje, że strona będzie działać a nie jak kiedyś że gdzieś wcieło z 80% grafik (morele - 1 dzień (ten pop-up że zmienili wygląd sklepu) / jakaś inna stronka co miała html filtering przez 2 dni)/

**Comment by krystian3w** [comment]
A te tkaniny z lewej to widget EI czy już reklama dla @MajkiIT?

**Comment by hawkeye116477** [comment]
Raczej reklama, no chyba, że właściciel jest ten sam, a ja nie zauważyłem.

**Comment by krystian3w** [comment]
Jak oni to też hurtownia to i może wyjść że reklama wewnętrzna...

**Comment by krystian3w** [comment]
To przeniosłem proceduralne filtry do suplementu by nie kombinować co wyciąć html filteringiem by się nigdy nie pojawiało, najwyżej będzie trzeba dotestować czy 3 filtry działają z Firefox i chromowatymi + uBO i Nano Adblockerem.

**Comment by krystian3w** [comment]
Chyba jednak wewnętrzne, więc już jest w EI  w widgetach wrzucone i będzie czekać na "RTM".

**Comment by hawkeye116477** [comment]
To już powinno być raczej zamknięte.

**Comment by krystian3w** [comment]
Oba już wycinane w RTM, nawet w modułach mimo uproszczenia nazw o jedno `p`.
