### ISSUE TITLE
runners-world.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12233]
info o adblocku oraz " podziel się " w artykułach ( po lewo ) i resztka ( po prawo ) np: https://www.runners-world.pl/sprzet/Buty-do-biegania-Reebok-Floatride-Run-Fast-RECENZJA,31050,1

**Comment by krystian3w** [comment]
#12232  / #12231 

---

Mnie tu nawet ta sekcja artykułowa wyjechała...

![obraz](https://user-images.githubusercontent.com/35370833/53357781-ed0f6a00-392e-11e9-997a-c7c673631a58.png) |
--- |
