### ISSUE TITLE
womenshealth.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12234]
info o adblocku, " podziel się " ( po lewo ) oraz resztki po reklamach np tu ; https://www.womenshealth.pl/fitness/10-dobrych-powodow-by-regularnie-cwiczyc,5184,3

**Comment by krystian3w** [comment]
#12233 / #12232  / #12231 

---

`##.wh-community-floating > div.title:nth-of-type(1)` - social
