### ISSUE TITLE
mxwojcik.pl

### ISSUE THREAD

**Issue by gaarguul** [MajkiIT/polish-ads-filter#12243]
Reklamy po prawej (na czerwono), niektóre z nich to socjale (na niebiesko):

![ss_010](https://user-images.githubusercontent.com/47940872/53347370-3654bf00-3919-11e9-8baf-123a98843b74.png)
![ss_012](https://user-images.githubusercontent.com/47940872/53347715-fc37ed00-3919-11e9-8206-51dcef4c985d.png)

**Comment by krystian3w** [comment]
Dziwaczne te reklamy facebookowe:

`##A[href^="https://www.facebook.com/"]` - 4 (może łapie jakiś link bez grafiki.
`##A[href^="https://www.facebook.com/"][target="_blank"]` - 2 otwierane w nowej karcie.
`##A[href^="https://www.facebook.com/"] > IMG` - 3 będące grafiką jakie zaznaczyłeś.
