### ISSUE TITLE
mylomza.pl

### ISSUE THREAD

**Issue by gaarguul** [MajkiIT/polish-ads-filter#12248]
Reklamy na środku i po prawej +  pusty kontener po reklamie u góry:

![ss_018](https://user-images.githubusercontent.com/47940872/53348664-ca278a80-391b-11e9-9ab3-fbf8b13fdbfc.png)
![ss_001](https://user-images.githubusercontent.com/47940872/53348669-cbf14e00-391b-11e9-9129-0177c1f61cd2.png)
![ss_002](https://user-images.githubusercontent.com/47940872/53348672-cbf14e00-391b-11e9-9271-e6f6fc4da898.png)

W artykułach też reklamy: np. https://mylomza.pl/artykul/pija-i-wsiadaja-za/612847

![ss592](https://user-images.githubusercontent.com/47940872/53399546-7ca72e00-39ac-11e9-9639-fbe6f1006ad4.png)

**Comment by krystian3w** [comment]
#11643, #11729, #12083

**Comment by krystian3w** [comment]
Pewnie większość pójdzie po zrobionych kosmetycznych pod ten szablon.

**Comment by krystian3w** [comment]
@olegwukr  - u mnie coś aktywuje anty-ablock:

![obraz](https://user-images.githubusercontent.com/35370833/53359318-e1be3d80-3932-11e9-8c14-42216ea58fb9.png) |
--- |

może `##body > div[id][style="display: block;"]:first-child`

Chyba że losują układ tego paska to lepiej wtedy namierzyć bait.
