### ISSUE TITLE
mapy.geoportal.gov.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12250]
![opera zdjecie_2019-02-25_171611_mapy geoportal gov pl](https://user-images.githubusercontent.com/36385327/53351208-188b5800-3921-11e9-8e87-eb3be0971af8.png)

**Comment by krystian3w** [comment]
@hawkeye116477  chyba do akceptacji w dodatku lub do **@kiboke - do you have scriplet for this site?**

**Comment by hawkeye116477** [comment]
@krystian3w Tak, trzeba upiec :cookie:. 
Można też dodatkowo zgłosić do :penguin:.

**Comment by krystian3w** [comment]
Jest wybór, więc będzie wisiało na zasadzie, że może ktoś używa Nano tylko do wycinania bez reklam i ochrony prywantości?

**Comment by hawkeye116477** [comment]
Innej opcji tu nie ma, albo akceptujesz albo opuszczasz portal, także :penguin: powinien dodać bezx marudzenia :smiley:

**Comment by kiboke** [comment]
> @hawkeye116477 chyba do akceptacji w dodatku lub do **@kiboke - do you have scriplet for this site?**

I can only set the cookie "regulationsAccepted=true" in advance.

**Comment by krystian3w** [comment]
Your autoclicker no generate errors on loop click?

> ![](https://user-images.githubusercontent.com/35370833/53367679-120fd700-3947-11e9-9148-f611bd754978.png)

**Comment by kiboke** [comment]
I didn't notice that alert.
