### ISSUE TITLE
iptv service

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#12254]
sorry za off topic

@MajkiIT jaki iptv service teraz uzywasz?

**Comment by MajkiIT** [comment]
best buy tv

**Comment by xxcriticxx** [comment]
url?

**Comment by xxcriticxx** [comment]
and how much?

**Comment by MajkiIT** [comment]
https://bestbuyiptv.net/pricing/

**Comment by xxcriticxx** [comment]
@MajkiIT cos ta strona umnie cala sie nie laduje
