### ISSUE TITLE
Ruszamy na podbój reddita?

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#12256]
Jest już profil na fejsie, ale nie ma na „pierwszej stronie Internetu". Na Discordzie raczej ruch niewielki, więc co wy na to, by na redditcie założyć społeczność „Oficjalne Polskie Filtry Majkela" :smile:?

**Comment by xxcriticxx** [comment]
majkel jackson?

**Comment by KonoromiHimaries** [comment]
jeszcze twitter

**Comment by xxcriticxx** [comment]
@hawkeye116477 bot nam potrzebny czy dasz radę coś zorganizować?

@KonoromiHimaries maybe instagram?

**Comment by hawkeye116477** [comment]
@xxcriticxx Jaki bot?

**Comment by xxcriticxx** [comment]
@hawkeye116477 tags, quick reporting?

**Comment by KonoromiHimaries** [comment]
@xxcriticxx może formularz byłby lepszy?

**Comment by xxcriticxx** [comment]
@KonoromiHimaries maybe?

**Comment by hawkeye116477** [comment]
@xxcriticxx Jakie tagi? Może chodziło o labele, jeśli tak to @MajkiIT musi zainstalować => `https://github.com/PolishFiltersTeam/PolishWorkflowBot` i wrzucić na `glitch.com`.
Jeżeli chodzi o zgłoszenia to może `https://ez34.net/2016/12/publish-anonymous-issues-on-github.html` (można zrobić własny formularz na stronie i ustawić action, by Google Forms przetwarzało odpowiedzi) albo `https://github.com/pixeline/portable-github-issues-form`. Drugi sposób trochę jakby gorszy, bo token będzie widoczny dla wszystkich.

**Comment by gaarguul** [comment]
KonoromiHimaries dlaczego się nie odzywasz i nie ogarniesz tego: https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues?q=is%3Aissue+is%3Aopen+label%3A%22.rekl.+wewn.%22, od czego w końcu jest ta lista filtrów wewn., prowadzisz ją czy wisi sobie na githubie dla ozdoby...

**Comment by hawkeye116477** [comment]
Jeszcze jest takie coś `https://gitmate.io/`, ale trochę lipnie to działa, bo jak ktoś komentarz zaktualizuje, to labela nie zmieni albo nie usunie.

**Comment by xxcriticxx** [comment]
@hawkeye116477 Github wystarczy pisałem dawno. Lepjej bot jakiegoś tutaj ściągnąć!

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale to jest właśnie bot...

**Comment by xxcriticxx** [comment]
@hawkeye116477 i kto to ma zmontować @MajkiIT?

**Comment by hawkeye116477** [comment]
@xxcriticxx Tak, to owner musi zrobić.

**Comment by xxcriticxx** [comment]
zamykamy? czy sa jakies inne opinie?

**Comment by hawkeye116477** [comment]
Jeszcze @MajkiIT nic nie napisał

**Comment by krystian3w** [comment]
Pewnie zajęty.
