### ISSUE TITLE
tukero.org 

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#12257]
Witam, tak jak w temacie. Kiedyś któryś z polskich filtrów umiał to ukryć. Ale od dłuższego czasu na tukero.org ten element nie jest już ukrywany. Chodzi mi o ten symbol RSS co na obrazku nad czatem: 
![bug](https://user-images.githubusercontent.com/16944478/53406329-07425a00-39ba-11e9-9b93-0f796a5fc438.png)
Czy można poprosić o jakiś fix?

**Comment by xxcriticxx** [comment]
@seba2282 strona nie PL

**Comment by gaarguul** [comment]
> seba2282: Kiedyś któryś z polskich filtrów umiał to ukryć.

Nie wydaje mi się, bo polskie filtry nigdy nie obsługiwały i nie obsługują stron obcojęzycznych, chyba, że jakoś omyłkowo przypadkiem, od ikon RSS są Polskie filtry RSS https://github.com/PolishFiltersTeam/PolishRSSFilters , ale tylko do stron polskojęzycznych.

**Comment by xxcriticxx** [comment]
@gaarguul prawie social :)

**Comment by seba2282** [comment]
@gaarguul, gdzie w takim razie to zgłosić?

**Comment by xxcriticxx** [comment]
@seba2282  nigdzie masz element picker `tukero.org##.clearfix.widget-content` dodaj do wlasnych skriptow

**Comment by seba2282** [comment]
@xxcriticxx, dziękuję działa. Ale jest jakiś filtr do blokowania zagranicznych takich rzeczy, gdzie mógłbym poprosić o tą regułę, aby była dodana?

**Comment by gaarguul** [comment]
xxcriticxx masz rację, sorry, moja uwaga niepotrzebna, to faktycznie jakby resztka po socjalach, a tworzenie etykiety RSS dla jednego zgłoszenia nie ma sensu.

> seba2282: Ale jest jakiś filtr do blokowania zagranicznych takich rzeczy, gdzie mógłbym poprosić o tą regułę, aby była dodana?

- 1_tak jak już zgłosiłeś czyli AdGuard Annoyances filter 
- 2_ oraz możesz też spróbować zgłosić do Fanboy’s Annoyance List:
https://github.com/ryanbr/fanboy-adblock/issues
- 3 znalazłem też taką listę która również zawiera sekcję/filtry RSS:
 https://mrsatterly.com/abp_filters.html

**Comment by seba2282** [comment]
Ekipa Adguard zafiksowała mój problem i nie widzę już tego RSS.
