### ISSUE TITLE
ekspresjaroslawski.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12263]
resztka po reklamie ( na dole ), np ; https://ekspresjaroslawski.pl/artykul/co-dalej-z-jks-em/613127

**Comment by gaarguul** [comment]
Ja już dawno nie wrzucam tu takich resztek, tylko tam: https://github.com/easylistpolish/easylistpolish/issues, a nawet tam tylko niektóre są naprawiane, a w ogóle to mnie już te resztki chyba przestały obchodzić, tak jak i adminów, wrzucam je tam, ale lata mi czy zostaną naprawione.
