### ISSUE TITLE
tvn24.pl

### ISSUE THREAD

**Issue by monkeyhook85** [MajkiIT/polish-ads-filter#12269]
Wlaczajac strone wyskakuje okno z filmem na pol ekranu telefonu i mimo przewijania strony okno z filmeme ciagle zajmuje pol ekranu az skonczy sie film.

Kilka miesiecy temu zainstalowalem adblock i adguard i polskie filtry i okno z filmem nie pojawialo sie. Dzis chcialem przeczytac newsa i znowu okno nie znika :/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. 
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**
Safari na iphone se

**Rozszerzenia i skrypty:**
Adblock
Adguard

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Złe repo - takie coś wycina EI https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters - może wystarczy dosubskrybować i zniknie...?

**Comment by krystian3w** [comment]
`tvn24.pl##.videoPlayer.stuck--top`

nie zadziała to trzeba będzie nowszy filtr skombinować albo pchać nawet w AdGuard byle na Safari przetestować.

**Comment by monkeyhook85** [comment]
Dziala !

W adguard poszukalem cos jak wyzej Majki podal: ~Polskie filtry elementow
irytujacych i po wczytaniu filtrow jak przewijam strone z filmem to film
sie pauzuje i przwija strone normalnie ;)

Wielkie dzieki!

W dniu śr., 27.02.2019 o 15:49 krystian3w <notifications@github.com>
napisał(a):
