### ISSUE TITLE
phoenixcontact.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#12298]
cookies 

test link:
https://www.phoenixcontact.com/online/portal/pl?1dmy&urile=wcm:path:/plpl/web/home

or 

https://www.phoenixcontact.com/online/portal/pl?1dmy&urile=wcm:path:/plpl/web/main/products/subcategory_pages/PLC_and_I_O_systems_P-21/cb588613-fd60-41e7-a3e4-61c93d94155e

**Comment by krystian3w** [comment]
@xxcriticxx  spróbujesz kosmetycznie zablokować tam gdzie mi nie wyskakiwało?
