### ISSUE TITLE
wp.pl na iphone 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1230]
zamontowalem adguard iso na iphone6. uzywam naszej listy na iphone na wp.pl jednak mam reklame lidl ktorej niemam w firefoxie. zdjecia dodam potem. 

@MajkiIT pytanje czy to jest jakis nowy typ reklamy? mobile only maybe
@F4z wiem ze uzywasz adguard czy masz to samo?

**Comment by F4z** [comment]
Na komputerze korzystam z Adguarda i uBlocka Origin, i nie widzę żadnych reklam na wp.pl.
Na telefonie z androidem i Adguardem też nie widzę żadnych reklam na wp.pl.
Na tablecie z iOS i Adguardem mam reklamy na wp.pl, ale moim zdaniem to jest jakiś problem z wczytaniem polskich reguł. To znaczy jak włączę "Adblock polskie reguły" i chcę sprawdzić aktualizacje filtrów w Adguardzie, to wyskakuje mi błąd, gdy wyłączę polskie reguły, to błędu nie ma.
Czyli wychodzi na to, że u mnie polskie reguły nie chcą się wczytać w Adguardzie na iOS, więc może u Ciebie też jest podobny problem.

**Comment by xxcriticxx** [comment]
iphone
![iphone](https://cloud.githubusercontent.com/assets/15007183/18351484/59af26f2-75a8-11e6-9463-7246eaa06889.PNG)

firefox:
![firefox](https://cloud.githubusercontent.com/assets/15007183/18351495/624bc0fe-75a8-11e6-9f0a-87bc253b6589.PNG)

**Comment by xxcriticxx** [comment]
umnie filtry laduja sie bezblendu na iphone

ostatnio byl problem z tym https://github.com/MajkiIT/polish-ads-filter/issues/1169 ale niby poprawione jest

**Comment by F4z** [comment]
Widziałem ten problem, jeszcze wczoraj teoretycznie u mnie było ok, a dzisiaj już coś jest nie tak i to nie po raz pierwszy.
W każdym razie, nie mogę włączyć polskich filtrów w Adguardzie na iOS, a nawet jak uda mi się je włączyć, to wtedy jest jakiś problem z aktualizacją i nadal nie działają.

A jeśli chodzi o reklamy, to możesz spróbować ręcznie dodać tę regułę:
`||fntajkb.wp.pl^`

**Comment by xxcriticxx** [comment]
trzetestuje jutro rano bo teraz tej reklamy niestety niemam

**Comment by xxcriticxx** [comment]
`||fntajkb.wp.pl^` Potwierdzam, to dziala na iso 9.3.5 iphone 6

**Comment by MajkiIT** [comment]
przypadkiem iOS nie ma problemów z multiregex?

**Comment by xxcriticxx** [comment]
ma ale niby zostalo poprawione w https://github.com/MajkiIT/polish-ads-filter/issues/1169

**Comment by xxcriticxx** [comment]
@F4z dzisaj jusz error Filters cannot be loaded into Safari. Therefore, you recent changes were not applied.

**Comment by F4z** [comment]
No właśnie, ja mam podobny problem.

**Comment by xxcriticxx** [comment]
ok ale wczoraj dzialalo

@MajkiIT mozna dostac liste bez multiregex do testow?

**Comment by xxcriticxx** [comment]
@F4z doklanie mam to samo co ty masz na iso. niewiem tylko dlaczego wczoraj dzialalo.

**Comment by xxcriticxx** [comment]
nadziwniesze ze wylonczylem wszyskie polskie filtry i dalej na wp.pl niemam reklam

**Comment by xxcriticxx** [comment]
@F4z for your information https://github.com/AdguardTeam/AdguardForiOS/issues/148

**Comment by F4z** [comment]
Ok, wielkie dzięki za informację.

**Comment by xxcriticxx** [comment]
@F4z  `||fntajkb.wp.pl^` narazie 3 dni i dziala na ver pro

**Comment by F4z** [comment]
To dobrze, ale jak widać w Adguardzie na iOS nie wszystkie reguły z wyrażeniami regularnymi działają.

**Comment by xxcriticxx** [comment]
ta ale wystarczy zapytaj i poprawiaja
