### ISSUE TITLE
MajkIT DNS

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1231]
czy kiedys otym myslales?

https://github.com/AdguardTeam/AdguardDNS

**Comment by MajkiIT** [comment]
Boje się, że skończy się tak, jak z twoim blokowaniem poprzez hosts.

**Comment by xxcriticxx** [comment]
czyli jak?

**Comment by MajkiIT** [comment]
że wyświetlał Ci się, alert o adblocku.

**Comment by xxcriticxx** [comment]
mozna sie stym bobawic i potestowac trzeba tracking cookie hyba przepuscic jest opcja whitelist 

`127.0.0.1 hit.gemius.pl             #[Tracking.Cookie]`
`127.0.0.1 pro.hit.gemius.pl	# May interfere with some video sites `
