### ISSUE TITLE
media.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12329]
cookies

**Comment by krystian3w** [comment]
padli?

`Domena media.pl jest zaparkowana na serwerach premium.pl. `

**Comment by blocker999** [comment]
http://www.ww.media.pl/?page=Structure&id=1

**Comment by krystian3w** [comment]
A to generyk powinien wyciąć, gdzieś był ten ciastek i IDCAC ma pod niego generyk to i do naszej skopiowany został.
