### ISSUE TITLE
vod.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1233]
Strona wykrywa adblocka - `http://vod.pl/filmy-i-bajki-dla-dzieci/dzieci-z-timpelbach-online-za-darmo/cy44x4e`
![image](https://cloud.githubusercontent.com/assets/11742596/18382722/8239e4b0-7682-11e6-8f62-8263c9ae07e0.png)

W zasadzie to jest to samo co na onecie, więc ta reguła powinna rozwiązać problem:
`/:\/\/[a-zA-Z0-9]{6,8}\.onet\.pl\//$xmlhttprequest,domain=vod.pl`
ewentualnie to:
`@@||vod.pl^$generichide`

**Comment by MajkiIT** [comment]
Dodane dzięki.

**Comment by F4z** [comment]
Znowu to samo - `http://vod.pl/filmy-i-bajki-dla-dzieci/hulk-podwojne-starcie-hulk-vs-wolverine-online-za-darmo/pzgmy11`
![image](https://cloud.githubusercontent.com/assets/11742596/18688165/6c35d110-7f83-11e6-810e-47f866eb5822.png)

Na przykład:
`||bcx.onet.pl$xmlhttprequest,domain=vod.pl`
lub
`/:\/\/(?!media)[a-zA-Z0-9]{3,8}\.onet\.pl\//$xmlhttprequest,domain=vod.pl`
w przypadku tej reguły może być tak, że zostanie za dużo zablokowane, więc warto ją jeszcze sprawdzić
lub
`@@||vod.pl^$generichide`
