### ISSUE TITLE
darmowa-telewizja.online

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#12338]
**Site Sample** | 
----------------|
http://darmowa-telewizja.online/polsatnews.html

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Mozilla Firefox Quantum x64 (lastest)
Adblocker							   | uBlock Origin (lastest)

| **Filters enabled**
|:--------------------------
| **CAT :: Main**
| uBlock filters
| uBlock filters - Badware risks
| uBlock filters - Privacy
| uBlock filters - Resource abuse
| uBlock filters - Unbreak
| **CAT :: Ads**
| Adblock Warning Removal List
| Adguard Base filter
| EasyList
| **CAT :: Privacy**
| Adguard Spyware
| EasyPrivacy
| Fanboy’s Enhanced Tracking List
| **CAT :: Malware**
| Malvertising filter list by Disconnect​​​​​
| Malware Domain List​​​​​
| Malware domains​
| Spam404​
| **CAT :: Annoyances**
| AdGuard Annoyances filter​​​​​
| AdGuard Social Media filter​
| Fanboy's Cookie List​
| Fanboy’s Annoyance List​
| Fanboy’s Social Blocking List​
| **CAT :: External**
| Peter Lowe’s Ad and tracking server list
| **CAT :: Customs**
| Polish Main
| Polish Adblock Warning Removal List
| KAD - Fraud/Scam
| NoCoin Filter List​​
| Polish Privacy Filters​​
| Polish Annoyances
| Polish Social 
​​​​| AlleBlock​
| EasyList Polish

### Issue:

Adblock detect 

<details><summary><b>Screenshot:</b></summary>

![s](https://i.imgur.com/x0RTLSV.png)

</details><br/>

@AdamWr

**Comment by hawkeye116477** [comment]
Nieładnie, nie da Zygmuntowi zarobić :smiley:
PS: Najtańsze pakiety z PSN => `http://sklep.cyfrowypolsat.pl/devices?deviceTypeCode=DEKODER&processSegmentationCode=DTH.CP.ACQ&marketTypeCode=IND&offerNSICode=RODZINNY&contractConditionCode=24A&tariffPlanCode=ROD20&positionFilterCode=&instCode=`, `https://sklep.ncplus.pl/oferta/comfortplus-ns?dllist=sg`.

**Comment by FadeMind** [comment]
@hawkeye116477 konsola
```
Wczytanie nie powiodło się dla elementu „script” ze źródłem „https://www.googletagmanager.com/gtag/js?id=UA-76527842-3”. polsatnews.html:5:1
TypeError: player is null[Więcej informacji] polsatnews.html:227:13
Logging system initialised at Mon Mar 04 2019 14:14:01 GMT+0100 (czas środkowoeuropejski standardowy) common.js:206:17
Wczytanie nie powiodło się dla elementu „script” ze źródłem „http://st.chatango.com/js/gz/emb.js”. polsatnews.html:189:1
Wczytanie nie powiodło się dla elementu „script” ze źródłem „http://s10.histats.com/js15_gif_as.js”. polsatnews.html:1:1
Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „http://c1.popads.net/pop.js” (brakujący nagłówek CORS „Access-Control-Allow-Origin”).[Więcej informacji]
Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „http://c1.popads.net/pop.js” (nieudane żądanie CORS).[Więcej informacji]
URI źródła elementu „script” jest niedozwolony w tym dokumencie: „http://c1.popads.net/pop.js”. polsatnews.html:1:1
Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „http://c2.popads.net/pop.js” (brakujący nagłówek CORS „Access-Control-Allow-Origin”).[Więcej informacji]
Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „http://c2.popads.net/pop.js” (nieudane żądanie CORS).[Więcej informacji]
URI źródła elementu „script” jest niedozwolony w tym dokumencie: „http://c2.popads.net/pop.js”. polsatnews.html:1:1
Wczytanie nie powiodło się dla elementu „script” ze źródłem „http://www.wnzmauurgol.com/h.js”. polsatnews.html:1:1
Wczytanie nie powiodło się dla elementu „script” ze źródłem „http://www.jyahmckzsbh.com/gq.js”. polsatnews.html:1:1
Wczytanie nie powiodło się dla elementu „script” ze źródłem „https://www.googletagmanager.com/gtag/js?id=UA-135108712-1”. polsat-news.php:20:1
Wczytanie nie powiodło się dla elementu „script” ze źródłem „http://dolohen.com/apu.php?zoneid=2451109”. polsat-news.php:30:1
Wczytanie nie powiodło się dla elementu „script” ze źródłem „http://dolohen.com/apu.php?zoneid=2465064”. polsat-news.php:31:1
Wczytanie nie powiodło się dla elementu „script” ze źródłem „http://dolohen.com/apu.php?zoneid=2465148”. polsat-news.php:32:1
Logging system initialised at Mon Mar 04 2019 14:14:02 GMT+0100 (czas środkowoeuropejski standardowy) common.js:206:17
Wczytanie nie powiodło się dla elementu „script” ze źródłem „https://glumtitu.net/ajax/p5/1.15.42/p5.min.js”. polsat-news.php:1:1
Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://glumtitu.net/static/eqcss/1.15.42/eqcss.min.css” (nieudane żądanie CORS).[Więcej informacji]
```

**Comment by hawkeye116477** [comment]
`@@||darmowa-telewizja.online^$generichide`

**Comment by FadeMind** [comment]
@hawkeye116477 
Prawie dobrze  😉 

![a](https://i.imgur.com/kthpc9c.png)

**Comment by hawkeye116477** [comment]
@FadeMind Po odświeżeniu będzie ok. A tak w ogóle, to ja tu widzę, że masa śmieci jest na tej stronie, łączy się z jakimiś dziwnymi domenami.

**Comment by hawkeye116477** [comment]
@FadeMind To dodaj jeszcze:
`twojetv.ws##+js(abort-current-inline-script.js, atob, decodeURIComponent)` :smile:.

**Comment by FadeMind** [comment]
@hawkeye116477 dziękuję 😘

**Comment by MajkiIT** [comment]
@hawkeye116477 dziękuję

**Comment by hawkeye116477** [comment]
@MajkiIT Ale Jeszce nikt nie dodał do listy, a ten atob to chyba do ciebie, bo to reklamy :smile:.

**Comment by krystian3w** [comment]
Coś zmienili w 4 dni, albo nie nadaje się do Polish Anti-Adblock "Privacy" Filters?

**Comment by hawkeye116477** [comment]
Przecież to już jest na liście.

**Comment by krystian3w** [comment]
Ale nie działa u mnie, nie mogę oglądać Canal plus, dalej się aktywuje ten niemiecki Anty-adblock...

**Comment by hawkeye116477** [comment]
@krystian3w `https://sklep.ncplus.pl/oferta/comfortplus-premium-12m?dllist=sg` :smile:

**Comment by krystian3w** [comment]
Zobaczymy jak naprawią w AdGuard:

```
https://github.com/AdguardTeam/AdguardFilters/issues/32150
```

**Comment by krystian3w** [comment]
Dodam, że mnie nawet ten Polsat Plus nie działa.

**Comment by krystian3w** [comment]
```
 darmowa-telewizja.online##+js(addEventListener-defuser.js, load, onload)
```

Niby u mnie takie coś na razie pomaga.

Aż jestem ciekaw co u mnie wabi `antiblock.org`,

**Comment by FadeMind** [comment]
@krystian3w  po kliknięciu na dowolny odnośnik otwiera popup z logo.png albo próbuje przekierować na stronę z reklamą.

**Comment by krystian3w** [comment]
To pewnie skrypt "z coś tam" naruszający prywatność - zobaczę kiedyś czy on przerywa takie interakcje.

**Comment by hawkeye116477** [comment]
@FadeMind `darmowa-telewizja.online##+js(abort-current-inline-script.js, atob, decodeURIComponent)`

**Comment by krystian3w** [comment]
PS. to moje też by trzeba było przemyśleć czy warto dodać, by ubić ten `anti-adblock.org` "skutecznie".

**Comment by krystian3w** [comment]
W sumie wychodzi, że to jest to coś na z:

```
darmowa-telewizja.online##+js(abort-current-inline-script.js, RegExp, zfgloaded)
```

działa jak skrypt od hawkeye, jak nie trafi do polskich filtrów prywatności to można zgłosić do uAssets problem.

**Comment by hawkeye116477** [comment]
Już wcześniej tą samą regułę, co podałem dodał do antyadblockowych, ale na inną domenę.

**Comment by krystian3w** [comment]
Jak ubijała i anty-adblock to może, jak same pop-upy / brzydkie reklamy to trochę dziwne.

**Comment by hawkeye116477** [comment]
@krystian3w Ona była na te popupy właśnie `https://github.com/MajkiIT/polish-ads-filter/issues/12338#issuecomment-469258792`

**Comment by krystian3w** [comment]
to czemu id tego issue?

**Comment by FadeMind** [comment]
> `darmowa-telewizja.online##+js(abort-current-inline-script.js, RegExp, zfgloaded)`

działa 

ślicznie dziękuję 😁

**Comment by Branzeturi** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/120376
