### ISSUE TITLE
mocnefirmy.pl

### ISSUE THREAD

**Issue by gaaargull** [MajkiIT/polish-ads-filter#12340]
Sprawa dla reportera - błąd na stronie (zarówno w Firefoxie jak i w Operze), a nie w filtrach, ale wrzucam to tu jako kolejną ciekawostkę/zagwostkę/zagadkę/anomalię kontinuum czaso-przestrzennego dla chętnych - o co w tym chodzi, że po załadowaniu się strony razem ze zdjęciami/obrazkami, po chwili wszystkie zdjęcia/obrazki nagle wyparowują po kolei:

Firefox:
![anim 001](https://user-images.githubusercontent.com/48046250/53732643-e3ca5400-3e7e-11e9-9168-154dfd9abb8f.gif)

Opera:
![anim 002](https://user-images.githubusercontent.com/48046250/53732644-e3ca5400-3e7e-11e9-872a-b87bf14071c4.gif)

**Comment by hawkeye116477** [comment]
A to ciekawe , bo u mnie na Moz://a Firefox KDE Edition for Manjaro linux 65.0.2 jest wszystko ok :stuck_out_tongue:

**Comment by MajkiIT** [comment]
To wina chyba filtru `187x196`

**Comment by krystian3w** [comment]
System do reinstalacji? Łącze do reklamacji?

**Comment by krystian3w** [comment]
> `187x196`

to nic nie psuje, już niby reklamy ukryło.
