### ISSUE TITLE
Jakie filtry warto dodać z polskich? 

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#12351]
Takie ogólne pytanie. Zainstalowałem nano adblocker z nano defender na Firefox (w końcu oba dodatki powróciły). I moje pytanie, jakie filtry warto dodać z tych polskich? Widzę, że część jest zintegrowana z wewnętrznymi i irytującymi. Web ultralist annoyances też dodałem. 
Pozdrawiam serdecznie

**Comment by hawkeye116477** [comment]
Zależy co ciebie interesuje. Polecam przejrzeć `https://polishannoyancefilters.netlify.com/otherfiltersforadblockers/`, możesz tam wybrać interesujące ciebie kategorie :smile:.

**Comment by seba2282** [comment]
Mam to jako dodatkowe: 
![dodatkowe](https://user-images.githubusercontent.com/16944478/53798976-b42c5200-3f39-11e9-85ee-d5925d7c11a0.png)
I chodzi mi o jak najskuteczniejsze blokowanie reklam z ucieczkami przed blokowaniem adblocka. :) 
Czy jeszcze coś powinienem dodać?

**Comment by hawkeye116477** [comment]
Wszystkie językowe, na pewno potrzebne :stuck_out_tongue: ? Na reklamy może być jeszcze AdGuard Base.

**Comment by seba2282** [comment]
Powiedzmy, że chodzę po różnych stronach (ni tylko PL). :P Dlatego spytałem. Czy coś jeszcze muszę dodać czy wystarczy?

**Comment by gaaargull** [comment]
Jeśli chodzi o polskie filtry to masz wszystkie, poza tą: Polskie Filtry RSS.
Jeśli chodzi o zagraniczne to jeszcze sporo znajdziesz do dodania, tutaj: https://filterlists.com/ masz wszystkie listy świata we wszystkich językach.

**Comment by seba2282** [comment]
Ale dodałem RSS i usuwając je, one wskakiwały (nie pamiętam dokładnie) do irytujących lub wewnętrznych i ilość używanych reguł zwiększała się o te RSS. Nie mam żadnych dodatków. Interesują mnie listy rozwijane. A I don't care about cookies jako filtr, jakby ukrywał masę tych cookies automatycznie.

**Comment by gaaargull** [comment]
> seba2282 : Ale dodałem RSS i usuwając je, one wskakiwały (nie pamiętam dokładnie) do irytujących lub wewnętrznych i ilość używanych reguł zwiększała się o te RSS. 

No to poprawiam się - Polskie Filtry RSS pewnie też masz, widocznie są albo w irytującyh albo w wewnętrznych.

> seba2282 : Nie mam żadnych dodatków.

No to dodaj:
- ten: [Polska Zgoda Ciasteczkowa](https://github.com/PolishFiltersTeam/PolishCookieConsent)
- ten: [Decentraleyes](https://addons.mozilla.org/pl/firefox/addon/decentraleyes/) (jako dodatkowe zabezpieczenie przeciwko śledzeniu)

> seba2282 : A I don't care about cookies jako filtr, jakby ukrywał masę tych cookies automatycznie.

Tego nie rozumiem, przecież dodatek też ukrywa to samo automatycznie bo ma w sobie tę listę już wbudowaną.

**Comment by seba2282** [comment]
Ten ciasteczkowa zgoda potrzebuje listy czy wystarczą z irytującymi? I firefox blokuje mi dodanie ciasteczkowej zgody.

**Comment by gaaargull** [comment]
> seba2282 : Ten ciasteczkowa zgoda potrzebuje listy czy wystarczą z irytującymi?

Wystarcza z irytującymi.

> seba2282 : I firefox blokuje mi dodanie ciasteczkowej zgody.

To trzeba kliknąć Zezwól, a potem Dodaj, i powinno pójść.

**Comment by seba2282** [comment]
![bug](https://user-images.githubusercontent.com/16944478/53802150-63b8f280-3f41-11e9-87e3-9d6a082d6239.png)

**Comment by gaaargull** [comment]
U mnie nie ma błędu:

1
![ss539](https://user-images.githubusercontent.com/48046250/53802222-97941800-3f41-11e9-88e2-388e45bd6b53.png)

2
![ss540](https://user-images.githubusercontent.com/48046250/53802256-af6b9c00-3f41-11e9-9fb8-9b32efe2d2ef.png)

3
![ss541](https://user-images.githubusercontent.com/48046250/53802265-b397b980-3f41-11e9-8562-66dfe4073679.png)

**Comment by hawkeye116477** [comment]
A nie wiem o co chodzi, SceneAddict na Discordzie też miał ten sam problem.

**Comment by gaaargull** [comment]
seba2282 spróbuj z wyłączonym adblockerem, skoro masz tylko różnych list to może któraś ci przyblokowała pobieranie.

**Comment by hawkeye116477** [comment]
Może to być też certyfikat od antywirusa, np. Kaspersky instaluje certyfikaty, wtedy oczywiście wyłączenie Kaspra nie pomoże, trzeba zająć się certyfikatami.

**Comment by seba2282** [comment]
Spróbowałem z wyłączonym nano i ten sam błąd.

**Comment by hawkeye116477** [comment]
@seba2282 Może spróbuj `https://support.eset.pl/kb6004/?locale=pl_PL&viewlocale=pl_PL`.

**Comment by seba2282** [comment]
To nie jest to. Mało tego jest wtedy gorzej, jak tak zrobię, wg poradnika Eseta.

**Comment by hawkeye116477** [comment]
@seba2282 A jak wyłączysz filtrowanie SSL?

**Comment by seba2282** [comment]
Poszło. To ja już nie ogarniam, dlaczego filtrowanie SSL blokuje pobieranie tylko niektórych rzeczy, a reszta działa.

**Comment by hawkeye116477** [comment]
Może GH używa nieaktualnego protokołu SSL v2 do pobrań z GH Releases.

**Comment by seba2282** [comment]
Dodałem też barblock rozszerzenie w celu niewidzenia tego frustrującego DCMA. Ale czy nadal jest skuteczny?

**Comment by krystian3w** [comment]
Co do Polish RSS to nie ma go w Polish EI (tylko ciacha). Więc są w wewnętrznych reklamach.

**Comment by seba2282** [comment]
Czyli mam takie dodatkowe filtry: 
![screenshot_2019-03-05-13-51-30](https://user-images.githubusercontent.com/16944478/53806772-3161c200-3f4e-11e9-803e-40751132a1fd.png)
Na PC i Android
Następujące dodatki: 
![screenshot_2019-03-05-13-51-56](https://user-images.githubusercontent.com/16944478/53806821-50605400-3f4e-11e9-85de-63b5b1a53ad2.png)

Kto może mi wyjaśnić, dlaczego jak zaznaczę tą nie zaznaczoną opcję, dostaję komunikat po angielsku, że ta opcja łamie strony internetowe i w ogóle do czego ta opcja służy? 
![screenshot_2019-03-05-13-52-10](https://user-images.githubusercontent.com/16944478/53806940-95848600-3f4e-11e9-86e1-6a05eccd8c5c.png)

**Comment by krystian3w** [comment]
Może neotralizują skrypty jak uBO neutralizuje Google i AddThis by nie mogły śledzić.

A psuje, bo może nagle braknąć na stronach 90% JavaScript i będą pewnie działać jakbyś cały JavaScript wyłączył.

**Comment by gaaargull** [comment]
> krystian3w : Może neotralizują skrypty jak uBO neutralizuje Google i AddThis by nie mogły śledzić.

To robi dodatek sam w sobie ogólnie, a on spytał o konkretną opcję.

> krystian3w : A psuje, bo może nagle braknąć na stronach 90% JavaScript i będą pewnie działać jakbyś cały JavaScript wyłączył.

No, tutaj już bardziej z sensem, a tylko dodam od siebie:

> seba2282 : łamie strony internetowe

Psuje, a nie łamie, a raczej, w sensie, że może czasem/często psuć, chociaż nie zawsze, ale pewnie częściej niż rzadziej.

> seba2282 : i w ogóle do czego ta opcja służy?

Ta taka opcja "przezorny zawsze ubezpieczony" / "opcja atomowa" / "super ubezpieczenie na wyrost" , czyli jeśli nie potrafi unieszkodliwić /zneutralizować jakiegoś skryptu / żądania śledzącego to go po prostu blokuje, to tak jak kazać adblockerowi blokowac każdy skrypt / żądanie, którego nie ma na żadnej liście filtrów, wtedy jesteśmy super bezpieczni, bo nieznane złośliwe skrypty na stronie się nie odpalą, ale jako, że razem z tymi skryptami często jest zawarta funkcjonalność strony to i strona się najprawdopodobniej uszkodzi.

**Comment by seba2282** [comment]
To teraz nie wiem czy włączyć tą opcję czy nie (blokuj żądania brakujących zasobów).

**Comment by gaaargull** [comment]
To kur..wa włącz i surfuj po internecie, jeśli będziesz miał większość stron internetowych popsutych, to będziesz wiedział czy ją mieć włączoną czy nie.

**Comment by gaaargull** [comment]
Dodatek respektuje pierwszeństwo innych dodatków (np. adblockera) więc może się okazać, że po włączeniu tej opcji wcale dużo stron nie będzie popsutych, zwłaszcza, że dodatek posiada większość skryptów, więc dopiero po wyłączeniu adblockera większość stron byłaby popsute, ale tak czy inaczaej jakieś strony mogą być popsute, czy dużo czy mało, nie wiem bo nie testowałem.

**Comment by seba2282** [comment]
Dziękuję za informacje.

**Comment by seba2282** [comment]
Sprawdziłem i ta opcja psuje np. odtwarzanie filmików w playerach. Jeżeli czegoś nie wiem, wolę zawsze dopytać.

Dzięki wszystkim za pomoc.

**Comment by krystian3w** [comment]
@seba2282 masz błąd formatowania markdown w Sprawdzonej poradzie:

https://forum.dobreprogramy.pl/t/koslawe-teksty-zamiast-gwiazdek/594418
