### ISSUE TITLE
pl.delfi.lt

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#12354]
`delfi.lt###header-top-banner + [class]:not(.container):has(img)`

WP się do nich nie umywa chyba, nawet umieją wymyślać nieistniejące tagi html.

**Comment by xxcriticxx** [comment]
@krystian3w wp.pl czy WordPress?

**Comment by krystian3w** [comment]
:globe_with_meridians:  :poland:

**Comment by hawkeye116477** [comment]
`pl.delfi.lt`
Na górze nie widać, dopiero gdzieś na dole.

**Comment by krystian3w** [comment]
ROFL.

**Comment by krystian3w** [comment]
Słabo spolszczone.

**Comment by xxcriticxx** [comment]
dokladnie cookies po litewsku

Informuojame, kad šioje svetainėje naudojami slapukai (angl. cookies). Sutikdami, paspauskite mygtuką „Sutinku“ arba naršykite toliau. Savo duotą sutikimą bet kada galėsite atšaukti pakeisdami savo interneto naršyklės nustatymus ir ištrindami įrašytus slapukus.

Czytaj więcej: https://pl.delfi.lt/

**Comment by krystian3w** [comment]
Dobra na reklamy zalecam subskrypcje "`LTU: EasyList Lithuania​​​​​​​​`",

**Comment by krystian3w** [comment]
https://github.com/EasyList-Lithuania/easylist_lithuania/issues/6

**Comment by gymka** [comment]
Don't know that is said above, but i fight with delfi ads with 'snippets' whole story and current code is in https://github.com/abp-filters/abp-filters-anti-cv/issues/57

**Comment by krystian3w** [comment]
No works with uBO - planning supplement for uBO?

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#pre-parsing-directives or Eyeo / Adblock Puls Company block this?

**Comment by gymka** [comment]
i think it's ubo syntax: delfi.lt##+js(abort-on-property-read.js, __dabd)
in abp syntax is: delfi.lt#$#abort-on-property-read __dabd
i("easylist lithuania" maintainer) fought maybe week with simple rules, like blocking images/div, etc, but later asked for community help :D nothing helps, you need deeper code, not simple rules

**Comment by krystian3w** [comment]
>  like blocking images/div

Yes, when I remove `^="h"]` filter cutt first video section.
