### ISSUE TITLE
wbudowie.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#12352]
Do przejrzenia, @MajkiIT trochę narozrabiał wcześniej i zgłosił się dev strony. Więc ja zamieniłem to na `wbudowie.pl##[rel="nofollow"]`, niby ja nie widzę już problemów, jednak nadal z niektórymi linkami w niektórych tekstach może być problem. Także zostawiam do dalszej analizy :smile:.

Aktualizacja: Najlepiej byłoby jakby Prezes wszedł na Discorda i pogadał z tym panem.

**Comment by krystian3w** [comment]
Ja bym to może chwytał wolniej, po tekscie `reklama`.

**Comment by gaaargull** [comment]
> hawkeye116477 : niby ja nie widzę już problemów

Ja też nie zauważyłem.

**Comment by krystian3w** [comment]
Jak coś to lepiej wstrzymać się do jutra a to wywalić przy zamykaniu innych zgłoszeń.

**Comment by krystian3w** [comment]
Poczytajcie sobie do czego jest nofollow.

**Comment by xxcriticxx** [comment]
@krystian3w kto cie sledzi?

**Comment by krystian3w** [comment]
śledzie?

https://support.google.com/webmasters/answer/96569?hl=pl

https://pl.wikipedia.org/wiki/Nofollow

**Comment by broiniac** [comment]
Panowie, aktualizacja z mojej strony:
Wspomniana wyżej klasa .advContainer została dodana do wszystkich zewnętrznych banerów reklamowych pochodzących z naszego wewnętrznego systemu.
 Gdybym coś przeoczył dajcie mi proszę znać.  Wiem, że filtry chwilę będą się propagować, dlatego poczekamy na spokojnie na efekty. Czy możemy już usunąć wbudowie.pl##[rel="nofollow"]?
