### ISSUE TITLE
bileteria-online.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12367]
![opera zdjecie_2019-03-07_100420_bileteria-online pl](https://user-images.githubusercontent.com/36385327/53944799-69891200-40c0-11e9-8f94-3c45665c74e4.png)

**Comment by krystian3w** [comment]
`###popek` - rap strona?

**Comment by xMaap** [comment]
To samo

```
polonuspartner.pl
zdo.pl
```

**Comment by krystian3w** [comment]
dalej popek zbyt ogólny, by w nim były cookies, więc dopiszę domeny z nazwy do specyficznych ukrywających.
