### ISSUE TITLE
 pl.todoist.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12369]
![opera zdjecie_2019-03-07_100728_todoist com](https://user-images.githubusercontent.com/36385327/53944995-dac8c500-40c0-11e9-9343-eb61a3257799.png)

**Comment by krystian3w** [comment]
anglojęzycznej nie czyszczę tylko tą z pl, chyba, że dasz linki gdzie jest polski bez `pl.`.

**Comment by xMaap** [comment]
Ja tam mam od razu bez pl. po Polsku


![zrzut ekranu z 2019-03-08 01-02-24](https://user-images.githubusercontent.com/36385327/53997789-e0182500-413d-11e9-88c2-3d25b97ace61.png)

**Comment by krystian3w** [comment]
#15853
