### ISSUE TITLE
seansik.nl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1236]
15 sec counter 

http://www.seansik.nl/film/iluzja-2-now-you-see-me-2-2016-napisy/8871
http://www.seansik.nl/film/legion-samobojcow-suicide-squad-2016-dubbing/16134
http://www.seansik.nl/film/jason-bourne-2016-napisy/16121

**Comment by F4z** [comment]
Na przykład:
`seansik.nl###over-player`

**Comment by xxcriticxx** [comment]
dziala mozna dodac to listy
