### ISSUE TITLE
Zmiana taxify.eu na bolt.eu

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12370]
W filtrach społecznościowych zamiast 

`taxify.eu##.app-footer .list-inline > li`
teraz powinno być
`bolt.eu##.app-footer .list-inline > li`

**Comment by krystian3w** [comment]
Nowe, nie wyprane w pervollu.

**Comment by krystian3w** [comment]
będzie `.icon-facebook-with-circle, .icon-twitter-with-circle, .icon-instagram-with-circle`
