### ISSUE TITLE
gtv.com.pl/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#12381]

**Comment by krystian3w** [comment]
Błędy lepiej opisać może ktoś nie mieć go i co?

**Comment by hawkeye116477** [comment]
No właśnie, ja mam tylko Polską Listę Reklamową i nie mam tego problemu, także trzeba dodać label won't fix i invalid :smiley:

**Comment by xxcriticxx** [comment]
@krystian3w dobrze ze sobie poradziles
