### ISSUE TITLE
garmin.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12389]
Social

```
https://www.garmin.com/pl-PL/
https://buy.garmin.com/pl-PL/PL/c12521-p1.html
https://explore.garmin.com/pl-PL/active-captain/
```
![opera zdjecie_2019-03-07_150601_www garmin com](https://user-images.githubusercontent.com/36385327/53962164-a36f0e00-40ea-11e9-9b3d-4eaee420aff3.png)

`https://support.garmin.com/pl-PL/`
![opera zdjecie_2019-03-07_150741_support garmin com](https://user-images.githubusercontent.com/36385327/53962212-c699bd80-40ea-11e9-9df9-f7205110493d.png)

**Comment by krystian3w** [comment]
Cookies też jest, nie używam już dawno Fanboyowego :cookie:  ani Kibokowego :cookie:.

**Comment by gaaargull** [comment]
> krystian3w : Cookies też jest, nie używam już dawno Fanboyowego ani Kibokowego .

A możesz łaskawie powiedzieć dlaczego, pytam bo już szlag mnie trafia jak tak patrzę jak te repo jest dzień w dzień zasypywane dziesiątkami zgłoszeń rodo-ciasteczkowych i końca nie widać, ja używam obydwu tych dużych list ciasteczkowych + polskie ciasteczka oczywiście + jeszcze Adguard moduł i od jakiegoś miesiąca nie mam żadnych ciaseczek/rodo, może od biedy jedno na tydzień się trafi, dlaczego polskie ciasteczka nie bazują na choćby jedenj dużej liście ciasteczkowej, tak jak inne polskie regionalne listy:
- polskie filtry reklamowe są uzupełnieniem EasyList
- polskie filtry prywatności są uzupełnieniem EasyPrivacy
- polskie filtry social są uzupełnieniem Fanboy's Social Blocking List
- przydałoby się żeby w końcu polskie filtry rodo-ciasteczkowe były uzupełnieniem dla Fanboy's Cookie List albo I don't care about cookies bo inaczaej utoniemy wkrótce w tych rodo-ciasteczkach...

Wiem, że w Fanboy's Social jest sporo błędów, większosć błędów to typu "osamotnione tło", czasem tylko strona jest uwalona - rzadko kiedy przez brak not:(body):not(html), ale sporo już wyzgłaszałem i ponaprawiane zostało, zresztą coś za coś - nie da się idealnie wybić wszystkich natłoku ciastek i rodo bez jakiś błędów czasami, chyba lepiej mieć spokój z tymi komunikatami i oszczędzić repo  i roboty kosztem jakiegoś błędu raz na jakiś czas niż bombardować repo w nieskończoność tymi zgłoszeniami.

A co znowu jest nie tak z I don't care about cookies żeby nie mogła służyć jako baza?

**Comment by krystian3w** [comment]
A nie wiem, ja mam tylko sprawdzać czy kiboke ma generyk jak ma to pod pl go u nas dodać i domeny pl czyste.

**Comment by krystian3w** [comment]
na pewno nawet boskie generyki nie wykluczą bugów jak gtv.com.pl

**Comment by krystian3w** [comment]
> oszczędzić repo i roboty kosztem jakiegoś błędu raz na jakiś czas niż bombardować repo w nieskończoność tymi zgłoszeniami.

`Data-noconvert-cookie`?

**Comment by gaaargull** [comment]
`badfilter` dla kosmetyków byłoby wystarczającym rozwiązaniem?

**Comment by krystian3w** [comment]
Nie wiem czy zrozumieją, i pewnie stwierdzą, że lista nie domyślna to nie nasz problem i na ile niby złe:

`#@#[data-nconvert-cookie]`

**Comment by gaaargull** [comment]
> krystian3w : `#@#[data-nconvert-cookie]` - jak dla mnie to już "badfilter off buster".

Możesz bardziej po polsku, co masz na myśli?

**Comment by krystian3w** [comment]
Kosmetyczny filtr chyba działa jak badfilter pod źle zrobione filtry sieciowe, w porównaniu do:

`@@coś`

**Comment by gaaargull** [comment]
- po pierwsze podajesz nieistniejący filtr, bo na liście Fanboy's Cookie nie ma `##[data-nconvert-cookie]`, jest natomiast `##div[data-nconvert-cookie]`
- po drugie co do `#@#div[data-nconvert-cookie]`, ale wtedy nie dodasz już takiego filtra. np. `mojastrona.pl##div[data-nconvert-cookie]`, stąd propozycja `badfilter`.

**Comment by krystian3w** [comment]
`mojastrona.pl##div[data-nconvert-cookie][id]`, `mojastrona.pl##div[data-nconvert-cookie][class]`?

**Comment by gaaargull** [comment]
Skoro to wystarczy to w czym problem.

**Comment by krystian3w** [comment]
W mentalności fanboya? A co do listy bazy to tylko mogę zasugerować by może to wdrożyć.

--- 

Jeszcze też można dopisać styl wymuszający jakkolwiek ukrycie dla uBO/AdGuarda.
