### ISSUE TITLE
teraz-wilanow.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12394]
http://teraz-wilanow.pl/stanislawa-celinska-koncert-koled-i-pastoralek/
![opera zdjecie_2019-03-08_094329_teraz-wilanow pl](https://user-images.githubusercontent.com/36385327/54017559-aae3f500-4186-11e9-9d9d-879a2ee39f01.png)

I nie wiem czy ten "Facebook" się nadaje
![opera zdjecie_2019-03-08_094409_teraz-wilanow pl](https://user-images.githubusercontent.com/36385327/54017582-bf27f200-4186-11e9-8e40-03987efe2d0d.png)

**Comment by krystian3w** [comment]
Nadaje, to jakaś resztka widgetu
