### ISSUE TITLE
kzkgop.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#12396]

**Comment by krystian3w** [comment]
To nie cookies? A strona poleca używać już:

https://rj.metropoliaztm.pl/rozklady/
https://www.metropoliaztm.pl/pl/

**Comment by krystian3w** [comment]
Jak chodzi o coś innego to proszę o pełny link do "archiwum" kzkgop.

A ten pop-up ja sam unieszkodliwiłem, by się pojawiał na dole strony i nie przypominał pop-upa, jedynie trzeba by opcjonalnie dobić skanie strony do niego.

**Comment by hawkeye116477** [comment]
@krystian3w Na dole jest :stuck_out_tongue:

**Comment by hawkeye116477** [comment]
Jest już `kzkgop.com.pl##.alert-info.alert:has-text(cookies)`

**Comment by krystian3w** [comment]
Ale może on widzi inne? Albo niby lepsze było 50 filtrów wycinające prostym CSS-em paski "bootstrap"?

**Comment by krystian3w** [comment]
niby tylko na pewnej stronie "greckiej" by się przydało sprawdzać co było w pasku "bootsrap" by nie wycinać że ich Google w wynikach wyszukiwania doceniło...

**Comment by hawkeye116477** [comment]
Skoro nie podaje opisu, to proponuję dodać label invalid i won't fix . A można też nawet dodać bota, by sam puste zamykał :smiley:
