### ISSUE TITLE
sklep.visionexpress.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12395]
![opera zdjecie_2019-03-08_123028_sklep visionexpress pl](https://user-images.githubusercontent.com/36385327/54026435-0a013400-419e-11e9-93bf-0aa11d727a7f.png)

**Comment by xxcriticxx** [comment]
RODO sie nie pokazuje 

![capture](https://user-images.githubusercontent.com/15007183/54027601-28503b00-4170-11e9-8c61-8cd6d66e0da9.PNG)

**Comment by krystian3w** [comment]
Bo nie powinno, niesety niemożliwe jest zabezpieczyć każdy generyk tak by nie aktywował się jak nie ma perzewijania / blokują css-em treść ( blur/ brak klikalności) i wycinania tła pod nim jak jest z d.u.p.y niepasujące do całej reszty prawie identycznych na innych stronach.

**Comment by krystian3w** [comment]
Błędu nie ma - nie naprawiamy listy `Fanboy cookie list` / cookies od kiboke...

Jak można to zmień na "błąd filtrów zewnętrznych".

**Comment by krystian3w** [comment]
Może błąd przekaże do tych panów `gargamel`, ja najwyżej dontę w polskich cookies jak hakweye nie zrobi tego pierwszy.

**Comment by gaaargull** [comment]
OK, przekazane: https://github.com/ryanbr/fanboy-adblock/issues/967

>  krystian3w : Jak można to zmień na "błąd filtrów zewnętrznych".

Lepiej nie bo znalazłem rodo tutaj: https://trendy.visionexpress.pl ==> https://trendyopticians.pl/

![ss_004](https://user-images.githubusercontent.com/48046250/54046261-1c966000-41d4-11e9-86ce-8f39660b8d87.png)

**Comment by krystian3w** [comment]
Da się w tym sklepie html filteringiem lub skryptem ubijać rodo, bo za wolno wycina najprostsze filtrowanie znacznikami CSS.
