### ISSUE TITLE
pl.linkedin.com

### ISSUE THREAD

**Issue by mino815** [MajkiIT/polish-ads-filter#12403]
cookies

**Comment by hawkeye116477** [comment]
Nic tam nie ma. Dopiero po zalogowaniu?

**Comment by krystian3w** [comment]
daj znać jak po zakceptowaniu pr i wymuszeniu aktualizacji filtrów gdzieś będzie wyskakiwało, bo niby na to mają fanboy i kiboke po 6 filtrów.

**Comment by mino815** [comment]
Działa :-) już nic się nie pojawia, dzięki!

**Comment by krystian3w** [comment]
Dobrze, bo potem są babole z 12 filtrami a 11 nieaktualnych.

**Comment by hawkeye116477** [comment]
@mino815 No to jak działa, to co nie zamykasz :smile:?
