### ISSUE TITLE
play.eune.leagueoflegends.com/pl_PL

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#12408]

**Comment by hawkeye116477** [comment]
@xxcriticxx Grasz w Lola? A ten LOL w ogóle będzie działał bez akceptacji?

**Comment by krystian3w** [comment]
strona tak...

**Comment by hawkeye116477** [comment]
A nie lepiej `||consent.trustarc.com/notice?domain=$script,domain=leagueoflegends.com`. Od razu to drugie też się schowa :smile:

**Comment by krystian3w** [comment]
Drugie mi się nie załadowało, ale można potem przerobić.

**Comment by xxcriticxx** [comment]
@hawkeye116477 nope

**Comment by krystian3w** [comment]
- Z mlekiem czy bez?
- tak.

:rofl:
