### ISSUE TITLE
stooq.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1240]
reklama

**Comment by F4z** [comment]
Do zablokowania samych reklam te dwie reguły powinny wystarczyć:
`stooq.pl##[onclick*="http://stooq.pl/ads/"]`
`stooq.pl##a[href^="ads/f/"]`

Jeśli chodzi o te puste miejsca po reklamach, to można spróbować tych reguł:
`stooq.pl##table[border="0"][cellpadding="0"][cellspacing="0"][align="center"]:not([width])`
`stooq.pl##table[border="0"][cellpadding="0"][cellspacing="0"][align="center"][height="252"]`
`stooq.pl##[style^="letter-spacing:"][id]`

Ta pierwsza reguła powinna ukrywać puste miejsce po reklamach na głównej stronie i na różnych podstronach, na przykład tutaj - `http://stooq.pl/mol/?id=6594`
Ta druga powinna ukryć puste miejsce po reklamie tutaj - `http://stooq.pl/n/?f=1098935&c=1`
Ta trzecia powinna ukryć napis "REKLAMA" na wszystkich stronach.
Tylko te reguły trzeba jeszcze sprawdzić, czy za dużo nie ukrywają.

**Comment by xxcriticxx** [comment]
ublock only czy normalne fitry?

**Comment by F4z** [comment]
Normalne.

**Comment by MajkiIT** [comment]
@F4z a co powiesz aby dodać tylko te? na moje oko reklam nie ma. 

```
stooq.pl##table[border="0"][cellpadding="0"][cellspacing="0"][align="center"]:not([width])
stooq.pl##table[border="0"][cellpadding="0"][cellspacing="0"][align="center"][height="252"]
stooq.pl##[style^="letter-spacing:"][id]stooq.pl##table[border="0"][cellpadding="0"][cellspacing="0"][align="center"]:not([width])
stooq.pl##table[border="0"][cellpadding="0"][cellspacing="0"][align="center"][height="252"]
stooq.pl##[style^="letter-spacing:"][id]
```

**Comment by F4z** [comment]
Tutaj zostanie reklama - `http://stooq.pl/q/?s=wig`
![image](https://cloud.githubusercontent.com/assets/11742596/18447813/89b6bac6-7928-11e6-939e-2d96312f8402.png)
więc ta reguła też się przyda - `stooq.pl##a[href^="ads/f/"]`

Tę pierwszą regułę `stooq.pl##[onclick*="http://stooq.pl/ads/"]` raczej można pominąć.

**Comment by F4z** [comment]
Swoją drogą, te reguły można też zastosować na tej samej stronie, tyle że z końcówką `.com` - `http://stooq.com/`

`stooq.pl,stooq.com##table[border="0"][cellpadding="0"][cellspacing="0"][align="center"]:not([width])`
`stooq.pl,stooq.com##table[border="0"][cellpadding="0"][cellspacing="0"][align="center"][height="252"]`
`stooq.pl,stooq.com##[style^="letter-spacing:"][id]`

Dodatkowo ta dla wersji `.pl` - `stooq.pl##a[href^="ads/f/"]`
bo dla wersji `.com` już jest taka na liście - https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock.txt#L663
