### ISSUE TITLE
plus.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12428]
![Zrzut ekranu z 2019-03-11 15-00-37](https://user-images.githubusercontent.com/36385327/54129546-c95c2180-440e-11e9-9017-16e9f9fafdcf.png)

`cyfrowypolsat.pl`
Włączony
![Opera Zdjęcie_2019-03-11_150438_www cyfrowypolsat pl](https://user-images.githubusercontent.com/36385327/54129665-0b856300-440f-11e9-845f-a56fe4e215e8.png)
Wyłączony
![Opera Zdjęcie_2019-03-11_150451_www cyfrowypolsat pl](https://user-images.githubusercontent.com/36385327/54129666-0b856300-440f-11e9-8e2a-8d890406686f.png)

**Comment by krystian3w** [comment]
Puls docięty z RODO wczoraj w commitach nawet wrzuciłem link.
_Takie coś tylko do uniknięcia jakby dało się sieciowo wyciąć i webmasterzy nie majstrowali z komunikatem._

Co do cyfrowego polsatu to błąd reklamowy (nasz lub EasyList) / fanboya social?

**Comment by krystian3w** [comment]
To tak dla @MajkiIT:

by przewrócić karuzele trzeba zluzować blokady reklamowe:

```
@@||www.googletagmanager.com/gtm.js$script,domain=www.cyfrowypolsat.pl
@@||myao.adocean.pl/files/js/ado.js$script,domain=www.cyfrowypolsat.pl
@@||myao.adocean.pl/ad.xml$xmlhttprequest,domain=www.cyfrowypolsat.pl
@@||myao.adocean.pl/_*/ad.js$script,domain=www.cyfrowypolsat.pl
@@||myao.adocean.pl/__/ad.xml$xmlhttprequest,domain=www.cyfrowypolsat.pl
```

I zobaczyć na ile co jest zbędne.

**Comment by lukjan32** [comment]
u mnie tak samo, i brak mozliwosci wejscia na podstrony.

**Comment by krystian3w** [comment]
Niestety nie umiem naprawić pod siebie skryptu do aktualizacji cookies tutaj, to wisi coś nawet po 7 dni.

**Comment by lukjan32** [comment]
dobra :(

**Comment by krystian3w** [comment]
Cookies powinno już zniknąć z wymuszeniem akualizacji filtrów.

Co do sludera to pewnie zostanie luka...

**Comment by lukjan32** [comment]
dobra, i tak dam do wyjatkow, jak nie da rady zrobic slajdow.

**Comment by Lukjan37** [comment]
brak podstron.
