### ISSUE TITLE
anime-odcinki.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1242]
OGŁASZAMY REKRUTACJĘ NA KOREKTORÓW! Więcej info znajdziesz tu: Forum A-O

UWAGA: Jeśli macie problem z wyświetleniem się strony lub playerów (widziecie znak kodów, bądz prostokąt czarny), wyczyśćcie pamięć cache swojej przeglądarki lub wyłączcie Adblocka, gdyż w większości przypadków powoduje on zakłócenia z jquery i skryptami java. Niedziałające playery Google są wycofywane z użytku. UWAGA: Pracujemy nad nowym update'em naszego portalu.

**Comment by MajkiIT** [comment]
statyczny baner

**Comment by xxcriticxx** [comment]
wiem obczaj player

**Comment by MajkiIT** [comment]
tutaj mi działa ==> http://anime-odcinki.pl/anime/ange-vierge/9
