### ISSUE TITLE
rmfon.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#12420]
Zablokowanie skryptu
```
||js.iplsc.com/inpl.adb/1.0.20/inpl.adb.js$script,domain=www.rmfon.pl
```
usuwa reklamy audio przed odtworzeniem głównego kanału radiowego na stronie.  @MajkiIT

**Comment by krystian3w** [comment]
`||js.iplsc.com/inpl.adb/*/inpl.adb.js$script,domain=www.rmfon.pl`

może dłużej podziała jak nagle zrobią wydanie 1.0.21 :wink:
