### ISSUE TITLE
motokorzysci.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12439]
Social
![Opera Zdjęcie_2019-03-12_053914_motokorzysci pl](https://user-images.githubusercontent.com/36385327/54174951-390ef280-4489-11e9-8da2-236a415cd0d2.png)

**Comment by krystian3w** [comment]
Wygląda na nie gotowe, wstawione źle, więc pewnie jak poprawią to i nam filtr padnie i nijak to zablokować tak by nie poprawiać po edycji strony...

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/blob/master/sections/adblock_social_list/specyficzne_ukrywajace.txt

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/38d45e5118f6549a9ee86ff69317eab6e65e9781
