### ISSUE TITLE
pudelek.pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#12433]
Rodo ,cookies

**Comment by krystian3w** [comment]
Gdzie masz pasek cookies...?

Ja mam tylko reklamy, jak nie działa już filtr dla uBlock i ten z AdGuard Annoyance to potem się doda do "Polskiej Zgody Ciasteczkowej" - niby już wycieka w trybie incognito.

**Comment by krystian3w** [comment]
@gwarser / @F4z  jak się da to może nowy filtr skryptowy, akceptacja RODO wgrywa po klika nowych reklam potem w wielu serwisach WP.
