### ISSUE TITLE
sklepdorotka.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12441]
Nie wiem dlatego, ale z włączonym Nano Adblocker podczas scrollowania strona miga z wyłącznym już nie.

**Comment by krystian3w** [comment]
Może się w tle ładuje - mi też jakaś ostatnio dziwnie skakała / błyskała.

**Comment by krystian3w** [comment]
Dobra też mam to ładowanie, trzeba by znaleźć wadliwy filtr który nagle ukrywa 3/4 treści.

**Comment by krystian3w** [comment]
Mam `#menu_newsletter` - zły filter

**Comment by krystian3w** [comment]
I złe miejsce zgłoszenia, bo to EI rozwala.

**Comment by krystian3w** [comment]
Mam `##.scrollTop:not(body):not(html)` - zły filtr.

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/c41cbaed401ec6e18a66a713a0ffa46439006394

--- 

I złe miejsce zgłoszenia, bo to EI rozwala.
