### ISSUE TITLE
poranny.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12442]
https://poranny.pl/jest-praca-w-centrum-powiadamiania-ratunkowego-w-bialymstoku-operatorzy-zarobia-mniej-niz-w-biedronce/ar/13954639#zdrowie
https://wspolczesna.pl/wniosek-o-doplaty-bezposrednie-2019-zlozysz-juz-w-tym-tygodniu-zobacz-kto-pomoze-ci-wypelnic-ewniosek/ar/13955989#strefa-agro
![Opera Zdjęcie_2019-03-12_055553_poranny pl](https://user-images.githubusercontent.com/36385327/54175544-9015c700-448b-11e9-8232-ea4a80efae36.png)

**Comment by krystian3w** [comment]
@olegwukr  / @MajkiIT  na współczesnej mam komunikat anty-adblock tak by wam nie umknęło...

**Comment by xxcriticxx** [comment]
@krystian3w dalej jest ten ad block?

**Comment by krystian3w** [comment]
Można zamknąć już opanowany.
