### ISSUE TITLE
komorkomania.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#12443]
![s](https://i.imgur.com/Ot1CVSC.png)

**Comment by krystian3w** [comment]
Nie da się wyciąć niby by nie rozpoczynać potyczek z Gemiusem.

W AdGuardzie 6.X (na Windows) nie możemy nawet użyć skryptowej reguły i trzeba by używać AdGuard Annoyance z filtrem skryptowym jaki stworzył @adamwr z 5 miesięcy temu.
Nie sprawdzałem czy filtr AdGuarda też ma już problem z blokowaniem jak alternatywny do uBlock Origin.

**Comment by krystian3w** [comment]
Opcjonalnie dla użytkowników z uBlock Origin i userCSS można rozszerzyć wolne ukrywanie pop-upa i próbę naprawy rozmazania i blokady przewijania.

Wada - będzie migało co odświeżenie strony jak będzie cała ładowana od zera.
