### ISSUE TITLE
pl.pandora.net/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#12444]

**Comment by krystian3w** [comment]
Widać coś przebudowali...

https://github.com/MajkiIT/polish-ads-filter/blob/2342185c75bad02288a496ec864d37d0b3280baa/cookies_filters/adblock_cookies.txt#L865

https://github.com/MajkiIT/polish-ads-filter/blob/2342185c75bad02288a496ec864d37d0b3280baa/cookies_filters/adblock_cookies.txt#L1180-L1181

**Comment by krystian3w** [comment]
Teraz niby używają "ccc":

`##.ccc`

**Comment by krystian3w** [comment]
Ogólnie to chyba stare filtry są do wywalenia - ten z wykrywaniem UI obecnie wycina wybór kontynetu / kraju:

https://pl.pandora.net/pl/Language

Ale tak to się kończy wstawianie rodo w pop-up.

**Comment by krystian3w** [comment]
@hawkeye116477  namierzysz mi kiedy wyprawiały z dev filtry https://github.com/MajkiIT/polish-ads-filter/issues/12444#issuecomment-471987271

Żeby nie było, bo ja ich nie widzę a nic nie wskazuje by były sprzątnięte w ciągu 20 godzin, więc zniknęły po ostatnim RTM/PR.
