### ISSUE TITLE
newonce.net

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12471]
RODO

**Comment by krystian3w** [comment]
I znowu jakiś anty-adblock:

![obraz](https://user-images.githubusercontent.com/35370833/54386915-61ba0680-469a-11e9-8483-bfa893ca5362.png) |
--- |

**Comment by gaaargull** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/12507#issuecomment-473684732 + 
https://github.com/MajkiIT/polish-ads-filter/issues/12507#issuecomment-474027857

**Comment by krystian3w** [comment]
Niby można pod "AdBlock/Plus". Co do playera to wiem że temat trudny - można nawet wywłać crash karty / zakładki a niby komuś filtr pomaga.
