### ISSUE TITLE
inpost.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#12478]
PO zalogowaniu do zaplecza wyświetla się okno z RODO:
https://manager.paczkomaty.pl/auth/login

![s](https://i.imgur.com/jvAkvzb.png)

**Comment by krystian3w** [comment]
Nie mam konta, będzie trzeba założyć.

**Comment by krystian3w** [comment]
Mam nadzieje, że nie generują innych pop-upów `##.modal` bo znów się pewnie obrazi @F4z  / @adamwr że wycinamy za dużo lub źle.

**Comment by AdamWr** [comment]
Może się mylę, ale `.modal` jest też prawdopodobnie używane w momencie kiedy kliknie się na przycisk do tego aby opłacić/anulować wysyłkę.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/54468758-6d87f480-4790-11e9-8701-d19a21852bdf.png)

</details>

**Comment by krystian3w** [comment]
No to tylko po has-text lub html filteringiem jak rodo jest w podglądzie źródła.

Nie za bardzo mam możliwości debugować ~10 godzin by użyć skryptów kompatybilnych z uBO, a na ciastko i tak zostanie olany bez opcji "zaufany".

**Comment by krystian3w** [comment]
Jak dasz radę @AdamWr  to zobacz czy ten pop-up ma:

 ```
<app-regulations-modal>

</app-regulations-modal>
```

Bo atrybuty ma identyczne i trzeba na podstawie zawartości. Już pomijam bug, że pewnie się w starym uBO zablokuje może pop-up z anulowaniem transakcji.

wtedy by było o jedno mniej sprawdzania lub kombinowania z przerywaniem ładowania rodo.
