### ISSUE TITLE
polsatsport.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#12477]
https://www.polsatsport.pl/film/hurkacz-mecz-z-federerem-to-bedzie-wydarzenie_6849833/?ref=wideo_najnowsze
Adblock w playerze.
![image](https://user-images.githubusercontent.com/29756590/54385875-f4a57180-4697-11e9-99e5-397eff39084c.png)

**Comment by krystian3w** [comment]
W firefox działa.

---

https://ipla-e2-19.pluscdn.pl/dituel/cp/g4/g4d53g5fnx3uczoziw1pnam2zw5smuwc.mp4

**Comment by xMaap** [comment]
Opera, ale za to leci dwusekundowa reklama.
![Opera Zdjęcie_2019-03-15_003204_www polsatsport pl](https://user-images.githubusercontent.com/36385327/54398378-0ac42980-46ba-11e9-8f9f-29b8ec5ee12c.png)

**Comment by gaaargull** [comment]
Na video-reklamy (które pokazują się też na `www.polsatnews.pl`):  
`||redirector.redefine.pl/r/*$media,redirect=noopmp4-1s,domain=www.polsatsport.pl|www.polsatnews.pl`
(bez redirecta niestety zapętla się, miga i chrzani, więc musi być)

Co do video-adblocka, to na tej stronie nie pokazuje się, ale za to pokazuje się na innych: `www.geekweek.pl` i `www.poszkole.pl`, więc trzeba dodać domeny do znajdującego się na liśce "POL: Oficjalne polskie filtry przeciwko alertom o Adblocku" filtra:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=games.cdn.famobi.com|grydladzieci.pl|fm.tuba.pl|wp.pl|player.pl|animezone.pl|ipla.tv|www.polsatnews.pl|playpuls.pl|polsatsport.pl|twojapogoda.pl|wtk.pl|www.geekweek.pl|www.poszkole.pl`

A obok tego filtra: 
`@@||ipla.hit.stat24.com/*ad.xml$xmlhttprequest,domain=polsatnews.pl|polsatsport.pl|twojapogoda.pl` dodać drugi:
`@@||redefine.hit.stat24.com/*/ad.xml$xmlhttprequest,domain=www.poszkole.pl|www.geekweek.pl`

Albo jakoś połączyć je w jeden np. `@@||hit.stat24.com/*ad.xml$xmlhttprequest,domain=polsatnews.pl|polsatsport.pl|twojapogoda.pl|www.poszkole.pl|www.geekweek.pl`

**Comment by HateAds** [comment]
Dziś adblocka nie mam, ale pojawiła się reklama 2 sekundowa tak samo jak u @xMaap ( testowałem na Chromie wersja 73.0.3683.75 (Oficjalna wersja) (64-bitowa) )

**Comment by gaaargull** [comment]
To fajnie byłoby gdybyś także łaskawie przetestował na podanej przeze mine wyżej regule, która tę reklamę eliminuje...(chociaż 2 sekundowa przerwa dalej zostanie, jeśli ktoś potrzebowałby i tę przerwę wyeliminować to potrzebny jest zastrzyk).
