### ISSUE TITLE
duolingo.com

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#12485]
jest blokada strony duolingo.com, podstrona pomoc zle wyswietla sie, nie wiem jak pozostale podstrony

**Comment by krystian3w** [comment]
Co znaczy źle wyświetla?

Może link do zepsutej podstrony opisu - na tę chwilę to ja widzę tylko social w stopce do wycięcia.

**Comment by lukjan32** [comment]
dziwne, w tej chwili jest dobrze.

**Comment by krystian3w** [comment]
Co co do blokady anty-adblock to uAssets / Pingwin2017 / AdGuard o tym wiedzą i problem jest trudny do zbadania - jakieś 50% że wyskoczy w trakcie rozwiązywania kursu.

**Comment by lukjan32** [comment]
aha, dobra

**Comment by hawkeye116477** [comment]
Ale w AG oni już to rozwiązali.
