### ISSUE TITLE
bauer media

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12483]
@krystian3w  wyciek RODO, tzn takie opóżnienia już będą czy da się to naprawić ?

https://www.cdaction.pl/

https://www.pcformat.pl/

https://www.styl.pl/

https://teletydzien.interia.pl/

**Comment by krystian3w** [comment]
Jak mi nie naprawisz pliku make_RTM to jesteśmy zależni od hawykeye.

Nie jestem w stanie ustalić co mi generuje error http 422.

**Comment by krystian3w** [comment]
Nie wiem czy może reinstalaxja uBO / Nano Adblocker może ci naprawi problem? Tylko pamiętaj by sobie zrobić kopię ustawień.

**Comment by krystian3w** [comment]
Na moje takiego migania nie naprawiamy? Niby je generuje `:not(body):not(html)`.

Nie wykluczam spadku wydajności w uBO 1.17+.

**Comment by krystian3w** [comment]
Raczej nie gerują skryptem komunikatu, by się wcale nie generował.

A filtr pozbawiony `:not(...)` może generować komunikat że jest możliwa redundancja.

**Comment by krystian3w** [comment]
Filtrem skryptowym może, ale nie wiem czy by mi się udało namierzyć sposób ubijania.

**Comment by krystian3w** [comment]
@hawkeye116477 a może dodać do dodatku - chyba że  tam tylko skrajne miganie jak z visionexpress, że zawsze wycina za późno?

**Comment by hawkeye116477** [comment]
A będą jakieś negatywne efekty po dodaniu `||prywatnosc.interia.pl/rodo-iframe`?

**Comment by krystian3w** [comment]
Nie działa? Zostaje otoczka pop-upa? Ona dalej może migać?
