### ISSUE TITLE
chcemybycrodzicami.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12480]
reklamy i dziwny blur np : https://www.chcemybycrodzicami.pl/artykuly/

**Comment by MajkiIT** [comment]
@hawkeye116477 to dla ciebie ...popup

**Comment by hawkeye116477** [comment]
@MajkiIT A co z reklamami, ja tam widzę, np. reklamę jakiegoś Supramen...
