### ISSUE TITLE
sport.tvp.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1248]
Podczas oglądania transmisji na żywo/niektórych filmów wykrywany jest adblock - `http://sport.tvp.pl/igrzyska-paraolimpijskie-rio/26728584/plywanie-k-i-m-finaly`

Albo tutaj - `http://sport.tvp.pl/igrzyska-paraolimpijskie-rio/26941604/piate-zloto-polakow-wilk-mistrzem-paraolimpijskim`

![image](https://cloud.githubusercontent.com/assets/11742596/18530107/4742e01c-7ad0-11e6-8ff6-27aef2a4fa74.png)

Na przykład:
`@@||myao.adocean.pl/_*/ad.xml$xmlhttprequest,domain=sport.tvp.pl`
lub:
`sport.tvp.pl###tvpoverlay_abdinfo`

**Comment by MajkiIT** [comment]
Dzięki
