### ISSUE TITLE
retailnet.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12492]
![Opera Zdjęcie_2019-03-16_020250_retailnet pl](https://user-images.githubusercontent.com/36385327/54468705-ad021100-478f-11e9-9b1c-1ab7327a42ea.png)

**Comment by krystian3w** [comment]
Nie lubisz ubierać się modnie?

**Comment by xxcriticxx** [comment]
chyba nie
