### ISSUE TITLE
zdrowie.radiozet.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12494]
filmiki niedziałają  " wczytywanie wideo... " - https://zdrowie.radiozet.pl/Psychologia/Zaburzenia-odzywiania/Olaf-Lubaszenko-w-Radiu-ZET-do-walki-z-otyloscia-sklonil-mnie-hejt

**Comment by krystian3w** [comment]
Jakiś badziew "wyślij na messenger" się pojawił...
