### ISSUE TITLE
www.kzkgop.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#125]
cookies

Ten serwis używa cookies. Jeśli nie wyrażasz zgody na używanie cookie, zgodnie z aktualnymi ustawieniami przeglądarki zmień jej ustawienia.
Brak zmiany ustawienia przeglądarki oznacza akceptację stosowania plików cookies.
Informacja o plikach cookies.

**Comment by close-alert** [comment]
Filtr(-y) wycina elementy informujące o nowej wersji i zamknięciu starej w niedługim czasie.
