### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#12507]
**Site Sample** | 
----------------|
https://player.pl/programy-online/kuba-wojewodzki-odcinki,455

Information			| Value
---					| ---
Operating system:	| Windows 10 1809 x64
Browser:			| Google Chrome Stable x64 (lastest)
Adblocker:			| uBlock Origin (lastest development build)

| **Filters enabled**
|:--------------------------
| **SECTION :: Main**
| uBlock filters
| uBlock filters – Annoyances​​​​​
| uBlock filters - Badware risks
| uBlock filters - Privacy
| uBlock filters - Resource abuse
| uBlock filters - Unbreak
| **SECTION :: Ads**
| Adblock Warning Removal List
| Adguard Base filter
| EasyList
| **SECTION :: Privacy**
| Adguard Spyware
| EasyPrivacy
| Fanboy’s Enhanced Tracking List
| **SECTION :: Malware**
| Malvertising filter list by Disconnect​​​​​
| Malware Domain List​​​​​
| Malware domains​
| Spam404​
| **SECTION :: Annoyances**
| AdGuard Annoyances filter​​​​​
| AdGuard Social Media filter​
| Fanboy’s Annoyance List​
| Fanboy's Cookie List​
| Fanboy’s Social Blocking List​
| **SECTION :: External**
| Peter Lowe’s Ad and tracking server list
| **SECTION :: Languages**
| Polish Adblock Warning Removal List
| Polish Main
| **SECTION :: Customs**
| AlleBlock​
| CoinBlockerLists by ZeroDot1 uBlock
| EasyList Polish
| KAD - Fraud/Scam
| NoCoin Filter List​​
| Polish Annoyances
| Polish Privacy Filters​​
| Polish Social

**Customs**
```
com###end-play
com###privacy-consent
pl##.cookies
pl##.facebook-comments
pl##.facebook-login.btn
pl##.fbComments
pl##.fbpageplugin.widget
pl##.hidden-xs.art__header__socials
pl##.menuSocialBar
pl##.text-center.fb-loading__placeholder
szukajka.tv##footer
vidoza.net##.vjs-topbar
www.ipla.tv##.action.vod-actions__share
www.polsatnews.pl##.app-ad--target.app-ad
www.polsatnews.pl##.news__comments
www.polsatnews.pl##div.container__layout--aside.container__layout.container__box:nth-of-type(3) > .section
zakazany-humor.pl###secondary
||apis.google.com/js/client:plusone.js$script
||js.iplsc.com/inpl.adb/*/inpl.adb.js$script,domain=www.rmfon.pl
||nieruchomosci.interia.pl/modul-promocyjny.html$subdocument
||www.polsatnews.pl/templates/pnews2018/build/gfx/share/*$image,domain=www.polsatnews.pl
```
### Issue:

Adblock detect 

<details><summary><b>Screenshot:</b></summary>

![s](https://i.imgur.com/orFfANk.jpg)

</details><br/>

**Comment by gaaargull** [comment]
Bez Nano Defendera jest, z Nano Defenderem nie.

**Comment by FadeMind** [comment]
Chodzi o to, by z uBlockiem nie było 😁

**Comment by gaaargull** [comment]
Domyślam się, tylko podzieliłem się informacją + dodatkowo dzięki temu może ktoś wyciągnie reguły z Nano Defendera, a przy okazji zapytam dlaczego nie używasz Nano Defendera.

**Comment by krystian3w** [comment]
Nano Defender to nie reguły a dedykowany skrypt, raczej nie ma szans by trafił on do "`resources`" w uAssets uBO.

Ogólnie to już nawet w Firefox nie działa.

**Comment by FadeMind** [comment]
@krystian3w mam `Violentmonkey` więc proszę poratuj panie skryptem ❤️

**Comment by gaaargull** [comment]
Typie ale o co ci biega, masz już to skryptem ogarnięte: Nano Defender.

**Comment by xxcriticxx** [comment]
@gaaargull delikatnej klientelę odganiasz

**Comment by krystian3w** [comment]
Mnie chodziło że kiedyś tylko Chromium miało problem i wymagało AdGuarda / Nano Defender.

**Comment by gaaargull** [comment]
> xxcriticxx gaaargull delikatnej klientelę odganiasz
> krystian3w reacted with thumbs up emoji

Czy moglibyście zachowywać się delikatniej i się ode mnie odczepić, bo odganiacie chętnych darmowych ciężko pracujących pracowników takich jak ja, którzy dużo już klientów przyciągnęli swoją cieżką darmową pracą, a jeśli chodzi o tego klienta, to podobnie jak wy również nie był zbyt delikatny bo:

- 1_ - wkleja prześmiewcze emotki https://github.com/MajkiIT/polish-ads-filter/issues/12507#issuecomment-473684835 którą sugeruje wszystkim, jakobym jak jakiś głąb się nie domyślił, że ma działać bez Nano Defendera, co było niedelikatne z jego strony, bo doskonale wiem, że pol lista nie wymaga Nano Defendera
- 2_ następnie, pomimo, że jak wyżej pokazałem był niedelikatny, to ja spytałem nadal delikatnie dlaczego nie używa Nano Defendera: https://github.com/MajkiIT/polish-ads-filter/issues/12507#issuecomment-473699353, a typ mnie znowu niedelikatnie zingorował i nie odpowiedział mi nawet, a na pytanie wypada odpowiedzieć

Więc zwyczajnie niedelikatność była z jego strony, z mojej strony to co najwyżej wdzięczność, a że wdzięczność to dobra cecha, to dziwi mnie, że jeśli już, to zamiast od was usłyszeć pochwałę za wdzięczność,  to usłyszałem burę za mylnie przypisaną mi niedelikatnośc, a klient który faktycznie tę niedelikatnośc posiada nie słyszał od was zarzutów o niedelikatności typu:  
- "delikatnej, bo gdy ktoś ciężko robi darmowo, to nie wypada wyśmiewać, odganiasz pracowników"
- "delikatniej, gdy ktoś robi darmowo i pyta, to wypada odpowiedzieć, bo odganiasz " 

No ale to normalne u troli jest, że odwracają kota ogonem, z ofiary robią winnego, a z winnego ofiarę, zaleciało od was wykopem.pl, a tu taki cytat o takich jak wy co się lubią czepiać nie tych co trzeba, polecam tę litrugię:  http://3zdania.pl/2017/02/07/czep-sie-tramwaju/.

A teraz naprawdę odczepcie się ode mnie bo poskażę się administratorowi i poproszę go o burę dla was za złośliwe czepianie się i odganianie ciężko i darmowo pracującego pracownika.

**Comment by FadeMind** [comment]
@gaaargull Zainstalowałem nanoAdblocker i nanoDefender aktywowałem następujący zestaw:
```

Filtry sieciowe: 131 688 + filtry kosmetyczne: 151 430 z:
 Moje filtry​​​​​ użytych 24 z 24​​​​
Wbudowane (10/11)
Nano Defender Integration​​​​​ użytych 2 449 z 2 671​​​​
Nano filters​​​​​ użytych 90 z 195​​​​
Nano filters – Annoyance​​​​​ użytych 12 z 18​​​​
Nano filters – Whitelist​​​​​ użytych 0 z 1​​​​
uBlock filters​​​​​ użytych 13 733 z 14 183​​​​
uBlock filters – Annoyances​​​​​ użytych 1 063 z 1 088​​​​
uBlock filters – Badware risks​​​​​ użytych 98 z 98​​​​
uBlock filters – Privacy​​​​​ użytych 144 z 157​​​​
uBlock filters – Resource abuse​​​​​ użytych 113 z 281​​​​
uBlock filters – Unbreak​​​​​ użytych 818 z 880​​​​
Reklamy (3/5)
Adblock Warning Removal List​​​​​ użytych 585 z 630​​​​
AdGuard Base filter​​​​​ użytych 22 044 z 23 192​​​​
EasyList​​​​​ użytych 88 050 z 88 283​​​​
Prywatność (3/3)
AdGuard Spyware filter​​​​​ użytych 3 242 z 7 553​​​​
EasyPrivacy​​​​​ użytych 16 079 z 16 675​​​​
Fanboy's Enhanced Tracking List​​​​​ użytych 2 985 z 3 068​​​​
Domeny ze złośliwym oprogramowaniem (4/4)
Malvertising filter list by Disconnect​​​​​ użytych 702 z 2 791​​​​
Malware Domain List​​​​​ użytych 1 090 z 1 105​​​​
Malware domains​​​​​ użytych 26 892 z 26 907​​​​
Spam404​​​​​ użytych 6 670 z 6 671​​​​
Elementy irytujące (6/6)
AdGuard Annoyances filter​​​​​ użytych 15 982 z 18 511​​​​
AdGuard Social Media filter​​​​​ użytych 7 157 z 7 949​​​​
Anti-Facebook List​​​​​ użytych 49 z 68​​​​
Fanboy's Annoyance List​​​​​ użytych 12 468 z 52 059​​​​
Fanboy's Cookie List​​​​​ użytych 14 288 z 14 295​​​​
Fanboy's Social Blocking List​​​​​ użytych 25 274 z 25 275​​​​
Wielofunkcyjne (2/4)
NoCoin Filter List​​​​​ użytych 621 z 623​​​​
Peter Lowe's Ad and tracking server list​​​​​ użytych 2 938 z 2 950​​​​
Regiony, języki (2/37)
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda​​​​​ użytych 5 863 z 5 962​​​​
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku​​​​​ użytych 707 z 707​​​​
Własne (7/7)
AlleBlock​​​​​ użytych 394 z 394​​​​
CoinBlockerLists by ZeroDot1 uBlock / This list disables browser based miners such as coin-hive​​​​​ użytych 679 z 846​​​​
EasyList Polish​​​​​ użytych 4 475 z 4 606​​​​
KAD - Przekręty​​​​​ użytych 1 510 z 1 555​​​​
Polish Privacy Filters​​​​​ użytych 70 z 100​​​​
Polskie Filtry Elementów Irytujących​​​​​ użytych 9 157 z 9 573​​​​
Polskie Filtry Społecznościowe​​​​​ użytych 4 885 z 4 907​​​​
```
reklamy nie ma. Wybacz, jeżeli miałeś wrażenie ignorancji. Mea culpa

**Comment by gaaargull** [comment]
xxcriticxx & krystian3w skoro jesteście tacy delikatni, to może kupcie sobie pampersy w razie czego...

**Comment by lukjan32** [comment]
znow jest blokada

**Comment by krystian3w** [comment]
Jak znowu ciągle była, zdechło z aktywnym Nano Defender @lukjan32?

**Comment by lukjan32** [comment]
nie wiem

**Comment by seba2282** [comment]
@Lukjan38 Po tym, jak nano defender został sprzedany, próbowałeś dodać filtr bogachenko do specjalizującego się w pomijaniu anty adblocków? 

https://github.com/bogachenko/fuckfuckadblock

+ player.pl poszedł tylko w komercję i biorą już kasę za wszystko xD

**Comment by Lukjan38** [comment]
juz jest ok
