### ISSUE TITLE
mmorpg.org.pl

### ISSUE THREAD

**Issue by Warlander** [MajkiIT/polish-ads-filter#1250]
Powrót agresywnego AdBlocka na stronie [mmorpg.org.pl](http://mmorpg.org.pl):

![17-25-58](https://cloud.githubusercontent.com/assets/3524664/18555864/ab9f9386-7b69-11e6-8176-62ff24e08478.png)

Tym razem istnieje możliwość tymczasowego wyłączenia bannera (po odczekaniu pół minuty od kliknięcia przycisku "OK") na czas jednego odświeżenia strony, ale pomijając to nic się nie zmieniło.

**Comment by xxcriticxx** [comment]
@Warlander link do ad blocka plz

**Comment by Warlander** [comment]
https://chrome.google.com/webstore/detail/adblock-plus/cfhdojbkjhnklbpkdaibdccddilifddb?hl=pl

**Comment by xxcriticxx** [comment]
@Warlander link do strony co widziales ad block

**Comment by F4z** [comment]
@xxcriticxx strona jest podana w temacie oraz w pierwszym poście.

@Warlander w polskich filtrach jest dodana odpowiednia reguła, który u mnie cały czas działa.
Jesteś pewny, że w rozszerzeniu do blokowania reklam masz dodaną/włączoną polską listę?
