### ISSUE TITLE
joemonster.org

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1251]
Reklama na górze strony - `http://joemonster.org/`
Jeśli nie pojawi się za pierwszym razem, to odśwież stronę i poczekaj kilka sekund.

![image](https://cloud.githubusercontent.com/assets/11742596/18601078/31e11224-7c61-11e6-990f-c30031a9b7cb.png)

Na przykład:
`joemonster.org##[id^="bmone2n"]`
ewentualnie coś takiego:
`/http:\/\/joemonster\.org\/[a-z]{3,10}/$xmlhttprequest`

**Oprócz tego jest pusta przestrzeń po reklamie.**

![image](https://cloud.githubusercontent.com/assets/11742596/18601590/fa6547f4-7c63-11e6-8d37-7a180dabe3b5.png)

Na przykład:
`joemonster.org##.matchedContent.BoxContent`

**Również jest coś takiego jak "Sponsorowane".**

![image](https://cloud.githubusercontent.com/assets/11742596/18601671/91264634-7c64-11e6-840b-3535e539eaa7.png)

Na przykład:
~~`joemonster.org##div > .rgHome.indexart`~~
~~`joemonster.org##div > .rgHome.indexart + hr`~~
~~Ta druga reguła jest po to, żeby ukryć jedną niepotrzebną szarą poziomą linię oddzielającą artykuły.~~
Odnośnie tych dwóch ostatnich reguł, to warto jeszcze je dokładniej sprawdzić, czy aby na pewno nie ukrywają za dużo.

**Edycja**
Pośpieszyłem się, ta przekreślona reguła za dużo ukrywa.
 Ta chyba będzie lepsza:
`joemonster.org##a[href*="utm_source=JoeMonster&utm_medium=Rectangle&utm_campaign="]`
Ewentualnie ta, tyle że tylko do uBlocka/Adguarda:
`joemonster.org##div > .rgHome.indexart:has(a[href*="utm_source=JoeMonster&utm_medium=Rectangle&utm_campaign="])`
I tak przydałoby się jeszcze te reguły sprawdzić.

**Comment by xxcriticxx** [comment]
sprawdze jak bende w domu

**Comment by xxcriticxx** [comment]
co jakis czas toyota wyskakuje. jedna i druga jest nie dobra

**Comment by F4z** [comment]
@xxcriticxx do zablokowania reklamy toyoty podałem te dwie reguły.
Tę - `joemonster.org##[id^="bmone2n"]`
lub tę - `/http:\/\/joemonster\.org\/[a-z]`
Te sprawdzałeś, czy inne?

Pozostałe reguły były żeby pozbyć się innych rzeczy.

**Comment by xxcriticxx** [comment]
nie sorry tylko testowalem te na dole

**Comment by F4z** [comment]
Ok, spoko.
Te reguły na dole były żeby zablokować te "Sponsorowane" coś, co wygląda jak reklama koszulek.

**Comment by xxcriticxx** [comment]
widzialem to reklame koszulek na innych stronach

**Comment by xxcriticxx** [comment]
a monkey happy nie trzeba?

**Comment by F4z** [comment]
To jest jakaś gra, więc raczej nie.

**Comment by xxcriticxx** [comment]
`joemonster.org##div > .rgHome.indexart:has(a[href*="utm_source=JoeMonster&utm_medium=Rectangle&utm_campaign="])
joemonster.org##[id^="bmone2n"]`

to hyba bendzie najlepsze

**Comment by F4z** [comment]
@MajkiIT dodałeś tę regułę do listy `joemonster.org##div > .rgHome.indexart:has(a[href*="utm_source=JoeMonster&utm_medium=Rectangle&utm_campaign="])`
ona nie działa w Adblocku, nie będzie sprawiała problemów?

**Comment by MajkiIT** [comment]
@F4z Poprawione dzięki.
