### ISSUE TITLE
lifetimetv.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12513]
https://www.lifetimetv.pl/programy/r-kelly-jego-wszystkie-ofiary

Ukrywa treść
![Opera Zdjęcie_2019-03-19_215058_www lifetimetv pl](https://user-images.githubusercontent.com/36385327/54640902-21d79280-4a91-11e9-89b9-5eb5a530e567.png)

Social
![Opera Zdjęcie_2019-03-19_215113_www lifetimetv pl](https://user-images.githubusercontent.com/36385327/54640908-256b1980-4a91-11e9-9d94-b08548cca08f.png)

**Comment by krystian3w** [comment]
Nie wiem co ukrywa treść na razie.

**Comment by krystian3w** [comment]
Jest też cookies.
