### ISSUE TITLE
chocolissimo.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12527]
![Zrzut ekranu z 2019-03-19 22-48-15](https://user-images.githubusercontent.com/36385327/54644224-30c24300-4a99-11e9-9510-833a60786028.png)

**Comment by xxcriticxx** [comment]
newslettera cos zjadlo 

![Capture](https://user-images.githubusercontent.com/15007183/54647381-9e11ac00-4a78-11e9-96e9-a55034cf66eb.PNG)

**Comment by gaaargull** [comment]
> xxcriticxx: newslettera cos zjadlo

Polskie Filtry Elementów Irytujących - a dokładniej moduł Wyskakujące Okienka

ale nie problem w tym, że zjadło bo od tego ten moduł jest, (ewentualnie filtr zastąpić lepszym), generalnie po prostu jeszcze trzeba ubić tło, które się ostało.

**Comment by krystian3w** [comment]
Ale blokują scroll... chamsko...

**Comment by krystian3w** [comment]
Newsletter wraca jak używamy Adblock / ABP.

**Comment by gaaargull** [comment]
To z innego repo (to nie repo EI), więc dlaczego to zostało zrobione, przecież wg https://github.com/MajkiIT/polish-ads-filter/pull/12567#issuecomment-475790516

> hawkeye116477: To na innym repo, nie liczy się.
