### ISSUE TITLE
404.g-net.pl

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#1252]
[Strona](http://404.g-net.pl/2016/09/paramount-pictures-zada-usuniecia-ubuntu-internetu/) jest biała przez filtr ciasteczek
`~niepoddawajsie.pl,~krasnale.pl,~futurevoicesystem.pl,~wmeritum.pl,~pl.forum.elvenar.com,~mcdonalds.co.uk,~astroweb.pl,~zadane.pl,~apteka-amic.pl,~naziemna.info,~planeteplus.pl,~abctygodnik.pl,~fundraising.org.pl,~filmydokumentalne.eu,~mvno-gsm.pl,~infoskawina.pl,~pikio.pl,~qt.io,~teleman.pl,~tablety.pl,~com##[class*="cookie-"]` 
w Adblock & uBlock polish cookies filters

**Comment by MajkiIT** [comment]
@gwarser dzięki poprawię.
