### ISSUE TITLE
multi social

### ISSUE THREAD

**Issue by gaaargull** [MajkiIT/polish-ads-filter#12537]
[75 stron](https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues?page=1&q=is%3Aissue+is%3Aopen+label%3A.social+-label%3A%22napr.+w+dev%22&utf8=%E2%9C%93)

**Comment by krystian3w** [comment]
Niby jednak 109.

**Comment by gaaargull** [comment]
Coś ci się pomyliło, bo patrzysz na nie ten licznik, na który trzeba, ten górny to zawsze pokazuje ilość wszystkich otwartych zgłoszeń bez względu na zawartość pola wyszukiwania, licznik uwzględniający pole wyszukiwania jest pod polem wyszukiwania:

<details not-open>
<summary>screenshoot</summary>

![liczniki](https://user-images.githubusercontent.com/48046250/54754159-21e7a780-4be3-11e9-83d1-50dcd11611fa.png)

</details>

a te pozostałe 33 to reklamy wewnętrzne (+ 1 wątek ogólny).
