### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by megitu** [MajkiIT/polish-ads-filter#12534]
adblock detect
https://www.wp.pl/

![]( https://i.imgur.com/17OurAG.png)

**Comment by xxcriticxx** [comment]
please report under https://github.com/MajkiIT/polish-ads-filter/issues/7533

**Comment by gaaargull** [comment]
Kolejny duplikat do zamknięcia, bo dla `wp.pl` mamy specjalnie wydzielony wątek zbiorczy, który jest ciągle otwarty: https://github.com/MajkiIT/polish-ads-filter/issues/7533, wewntulanie można się udzielić w kestii anty-adblocka w tym otwartym wątku: https://github.com/MajkiIT/polish-ads-filter/issues/12512

Jako, że to jest już ostatnio czwarty duplikat `wp.pl`: https://github.com/MajkiIT/polish-ads-filter/issues/12109, https://github.com/MajkiIT/polish-ads-filter/issues/12201, https://github.com/MajkiIT/polish-ads-filter/issues/12434, https://github.com/MajkiIT/polish-ads-filter/issues/12534 to sensowne wydaje się rozważenie "przypięcia" głównego wątku wp.pl.

**Comment by xxcriticxx** [comment]
@gaaargull nawet jak zostanie przypiety beda otwierac nowe
