### ISSUE TITLE
getlevel.info

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12566]
`https://getlevel.info`
![Opera Zdjęcie_2019-03-22_091433_getlevel info](https://user-images.githubusercontent.com/36385327/54809225-f87e5880-4c82-11e9-9fba-f2c0e08b3b76.png)

`https://getlevel.info/jezdzisz-duzo-samochodem-sprawdz-xblitz-x300-pro/`
![Opera Zdjęcie_2019-03-22_091245_getlevel info](https://user-images.githubusercontent.com/36385327/54809245-016f2a00-4c83-11e9-914d-ed2e3957ff67.png)
![Zrzut ekranu z 2019-03-22 09-13-29](https://user-images.githubusercontent.com/36385327/54809251-046a1a80-4c83-11e9-91d6-9944f32f625e.png)

**Comment by krystian3w** [comment]
Zowu ciasteczka.
