### ISSUE TITLE
cookup.pl

### ISSUE THREAD

**Issue by gaaargull** [MajkiIT/polish-ads-filter#12583]
Social mini-galeria na dole:

![](https://user-images.githubusercontent.com/47386482/53418900-14bb0c80-39d9-11e9-9d3c-781f9013bb31.png)

**Comment by krystian3w** [comment]
Ja mam resztki  (sam tytuł) nagle w jeden dzień coś wycina grafiki...

@F4z / @adamwr może znowu jakieś konflity uBO (inny system dodawania wyjątków i ich rozpatrywania) i  Social Media AdGuard?
