### ISSUE TITLE
cezar.eu

### ISSUE THREAD

**Issue by gaaargull** [MajkiIT/polish-ads-filter#12595]
Social ikony/przyciski na dole po lewej:

![ss548](https://user-images.githubusercontent.com/48046250/54879310-afbbd080-4e37-11e9-9739-b11f9c870f38.png)

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/9a81c112e8b98373a68b560f330b0b1a63021a4f
