### ISSUE TITLE
loco-travel.pl

### ISSUE THREAD

**Issue by gaaargull** [MajkiIT/polish-ads-filter#12607]
Social video na dole po lewej:

![](https://user-images.githubusercontent.com/47386482/53486282-9a49c580-3a88-11e9-89eb-0d782a2337a3.png)

**Comment by krystian3w** [comment]
@hawkeye116477  nadaje się? Jak tak to dużo prawych kolumn z jakimś filmem youtube nie dodałem.

**Comment by hawkeye116477** [comment]
Raczej nie
