### ISSUE TITLE
yuliyababich.eu

### ISSUE THREAD

**Issue by gaaargull** [MajkiIT/polish-ads-filter#12602]
Social widżet wysuwany scrollujący po prawej:

![](https://user-images.githubusercontent.com/47386482/53481699-0a068300-3a7e-11e9-9a23-3f253bfc204c.gif)

**Comment by krystian3w** [comment]
Ikon się nie da...

> ![](http://www.yuliyababich.eu/Content/_images/kontctcontainer1.png) |
> --- |
