### ISSUE TITLE
agwerblog.pl

### ISSUE THREAD

**Issue by gaaargull** [MajkiIT/polish-ads-filter#12614]
Social kontener z przyciskiem/linkiem po prawej:

![](https://user-images.githubusercontent.com/47386482/53633932-23900200-3c19-11e9-8451-22d16cae6195.png)

**Comment by krystian3w** [comment]
ten nad to też social - google plus?

**Comment by gaaargull** [comment]
Nie wiem, bo nie widzę żadnego Google+, jeszcze zauważyłem dopiero teraz przycisk social na dole po lewej:
![ss548](https://user-images.githubusercontent.com/48046250/55136204-18ec5e00-512e-11e9-8bd2-6a8b7da66153.png)
