### ISSUE TITLE
ganjamafiashop.com

### ISSUE THREAD

**Issue by gaaargull** [MajkiIT/polish-ads-filter#12627]
Social ikony/przyciski na dole po prawej:

![](https://user-images.githubusercontent.com/47386482/53635256-d4e46700-3c1c-11e9-986f-1cbf2985569b.png)

**Comment by krystian3w** [comment]
@hawkeye116477  nic złego że ich odtwarzacz po wycięciu sociala robi się 2 razy dłuższy a na chyba całą szerokość po wycięciu `zapisz się do newslettera`?
