### ISSUE TITLE
grctechnologie.pl

### ISSUE THREAD

**Issue by gaaargull** [MajkiIT/polish-ads-filter#12647]
Social ikony/przyciski u góry po prawej:

![](https://user-images.githubusercontent.com/47386482/53634095-8d101080-3c19-11e9-80cd-06cac02b6f30.png)

**Comment by gaaargull** [comment]
Już skończyłem, więcej zgłoszeń nie będzie, chcieli żeby przenieść tu, bo nie chceili zrobić tam, to przeniosłem (https://github.com/MajkiIT/polish-ads-filter/issues/12537), a ja musiałem wszystko na raz bo w rozdrabnianie się nie bawię, chciałem mieć z głowy po prostu, dodatkowo jak widać 61 zgłoszeń, a nie 75, bo 14 zgłoszeń, ktoś gdzieś już ponaprawiał w między czasie.

**Comment by krystian3w** [comment]
zrobione dwa z 63:

#12605 i #12627
