### ISSUE TITLE
nanonet.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12655]
Ukryte treści

**Comment by krystian3w** [comment]
@hawkeye116477 / @blocker999  nieładnie 🔍 :mag: 👓 :

```
||mailerlite.com^$third-party
```

**Comment by hawkeye116477** [comment]
Jest to też w AG Annoyance, pomysł na dodanie był właśnie chyba od nich :smile:

**Comment by krystian3w** [comment]
@adamwr - no to pewnie też macie bug.

**Comment by AdamWr** [comment]
Poprawione, dzięki.

**Comment by krystian3w** [comment]
Myślę że można zamknąć już na pewno przemiemielił bot w wyjątkach filtrów elementów irytujących.
