### ISSUE TITLE
sygic.com/pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12677]
![Opera Zdjęcie_2019-03-29_083851_www sygic com](https://user-images.githubusercontent.com/36385327/55216838-23762880-51fe-11e9-8470-332b1a351c34.png)

**Comment by hawkeye116477** [comment]
Ten Sygic to tak bardziej do Fanboya, bo to jest międzynarodowa strona

**Comment by krystian3w** [comment]
Ale polonizacja "legitna".

**Comment by krystian3w** [comment]
@smed79 can You create PR?

https://github.com/easylist/easylist/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+sygic.com - 0 found.

**Comment by hawkeye116477** [comment]
@krystian3w No niby tak, ale skoro nasza lista to uzupełnienie Fanboya, to w takim razie takie międzynarodowe to bardziej do niego :smile: Tak czy siak, tym razem zrobiłem wyjątek i dodałem wczoraj.
