### ISSUE TITLE
Sagittarius A*...

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#12675]
https://github.com/ProximaB

ktoś zna?

**Comment by xxcriticxx** [comment]
Nope

Chcesz to cię umówię z Bartkiem

**Comment by krystian3w** [comment]
Jak coś chodzi o dziwne forkowanie polskich filtrów z sprzed 11 dni - jak kolejny raz próbowałem coś ruszyć dalej z skryptem do PR pod cookies / social.

**Comment by xxcriticxx** [comment]
na pewno nie dlugo sie dowiem o co chodzi
