### ISSUE TITLE
myspeed.pl / zabieganamama.com

### ISSUE THREAD

**Issue by gaaargull** [MajkiIT/polish-ads-filter#12673]
Błąd w Polskie Filtry RODO-Ciasteczkowe, nie ładują się banery:

<details not-open>
<summary>myspeed.pl</summary>

![ss_016](https://user-images.githubusercontent.com/48046250/55157641-3be23680-515d-11e9-9608-18bd867e895b.png)

</details>
<details not-open>
<summary>zabieganamama.com</summary>

![Screenshot_2019-03-28 Zabiegana Mama Zabiegana Mama Elwira Zbadyńska](https://user-images.githubusercontent.com/48046250/55158227-ae9fe180-515e-11e9-93ea-856de5946b67.png)

</details>

Po wyłączeniu listy jest już ok:

<details not-open>
<summary>myspeed.pl</summary>

![ss_015](https://user-images.githubusercontent.com/48046250/55157659-47cdf880-515d-11e9-805c-b6a2acbae2b6.png)

</details>
<details not-open>
<summary>zabieganamama.com</summary>

![Screenshot_2019-03-28 Zabiegana Mama Zabiegana Mama Elwira Zbadyńska2](https://user-images.githubusercontent.com/48046250/55158369-03dbf300-515f-11e9-840f-c00ad72b4af8.jpg)

</details>

(Przy okazji tak żeby było wiadomo: 
https://github.com/ryanbr/fanboy-adblock/issues/716
https://github.com/ryanbr/fanboy-adblock/issues/784)

**Comment by krystian3w** [comment]
na zabieganej mamie jeszcze jest div "data-nconver-cookie"?

**Comment by MajkiIT** [comment]
@hawkeye116477 wrzucisz jakiś pull ?

**Comment by krystian3w** [comment]
Tylko jak coś to ja utnknąłem gdzies na #12618 - czyli z 30 zgłoszeń zostało do docięcia.

**Comment by xxcriticxx** [comment]
@krystian3w moze pomalu zaczne zamykac?

**Comment by krystian3w** [comment]
Raczej nie, potem będą skargi że jednak dalej są sociale i cookies mimo aktualizowania filtrów.

**Comment by xxcriticxx** [comment]
zamkne do #12618
