### ISSUE TITLE
uwaga.tvn.pl

### ISSUE THREAD

**Issue by gaaargull** [MajkiIT/polish-ads-filter#12674]
Błąd - brak video w POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
na podstronach z reportażami np:
https://uwaga.tvn.pl/reportaze,2671,n/zaglodzone-zwierzeta-rodzinny-dramat-i-urzednicza-niemoc-oficjalna-strona-programu-uwaga-tvn,286589.html
Błąd powodują 2 filtry kosmetyczne z polskiej listy: `##[class^="ad-"]` i `##.ad`, wystarczy dodać wykluczenie domeny `~uwaga.tvn.pl` do obydwu.

![ss_020](https://user-images.githubusercontent.com/48046250/55168606-62ab6780-5173-11e9-8bb7-05d0a84cb892.png)

po wyłączeniu listy:
![ss_019](https://user-images.githubusercontent.com/48046250/55168585-5cb58680-5173-11e9-8153-478f916887b9.png)

**Comment by krystian3w** [comment]
na fakt.pl też nie mam video, coś za mocno wycina `x-get.link.pl`

**Comment by xxcriticxx** [comment]
`x-get.link.pl` wycina host lista

**Comment by krystian3w** [comment]
A jak to działa jak niby cały tvn ma generichide?

**Comment by gaaargull** [comment]
Bo te filtry z pierwszego komentarza / commita nie są filtrami generycznymi, bo mają oprócz wykluczeń domen także domeny:
`...,pl,...##[class^="ad-"]`
`,anglia.today,dbnao.net,pl##.ad`
a choćby jedna domena powoduje, że filtr nie jest już generyczny.

**Comment by krystian3w** [comment]
A co przywraca 4/5 ikon social?

**Comment by gaaargull** [comment]
> krystian3w: A co przywraca 4/5 ikon social?

Nic nie przywraca, bo zazwyczaj nie korzystam z list social i mam je w yłączone gdy zgłaszam rzeczy nie związane z socialami, ale przy okazji znalazłem jeszcze dwa linki/loga social do zablokowania po prawej stronie:

![Bez nazwy](https://user-images.githubusercontent.com/48046250/55222763-f4b37e80-520c-11e9-8672-88a6f733f3b6.png)
