### ISSUE TITLE
podstacja.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12686]
![Opera Zdjęcie_2019-03-29_221142_podstacja com](https://user-images.githubusercontent.com/36385327/55262965-db8fe980-526f-11e9-96f7-d797df037954.png)

**Comment by krystian3w** [comment]
No to czemu nie wyłączysz?

**Comment by krystian3w** [comment]
AdNauseam ratujemy czy niech twórcy naprawiają?

```
podstacja.com#@#.reklama
podstacja.com#@#.adsbygoogle

! AdNauseam fail generichide

podstacja.com#@#*[class^="adsby"]
```

**Comment by krystian3w** [comment]
@olegwukr  naprawiłeś jakoś?
