### ISSUE TITLE
komorkomania.pl 

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#12682]
Witam, jak za pierwszym razem wchodzę na komorkomania.pl, mam informacje o cookies z rodo. W Ublock Origin dla Firefoxa mam dodane co prawda elementy irytujące i I don't care about cookies filter i akurat tego nie pomija na wspomnianej stronie. Czy możecie dorzucić tą stronę też jako irytujące cookie? 

A teraz pytanie. Czy są plany, aby zintegrować Alleblock z elementami irytującymi bądź z filtrami wewnętrznymi? 
Pozdrawiam

**Comment by krystian3w** [comment]
Nie możemy (nikt nie ma czasu na debugowanie "WP JS lib" i są podejrzenia że metoda zapożyczona od AdGuard przyblokuje Gemius i będzie drugi wątek jak z `converti.se` i linkami sponsorowanymi) - zainstaluj roszszerzenie "polska zgoda ciasteczkowa".

Robi podobne kilkanie jak **Kiboke** w IDCAC na wp - nie ma on w kodzie reszty domen wchłoniętych przez WP/O2.

**Comment by krystian3w** [comment]
Planów integracji alleblock z EI nie ma - lista jak dla mnie i hawkeye za bardzo speczyficzna.

Planów Matiego nie znam czy ma chęć zasysania listy jak kolejnej z wielu.

**Comment by seba2282** [comment]
Wydaje mi się, że zablokowanie całego Gemius byłoby ciekawym wyjściem. Ale o co chodzi z tym podejrzeniem, o którym piszesz, @krystian3w, że zablokuje Gemius?

**Comment by krystian3w** [comment]
Ja nie wiem - biblioteki WP są zbyt rozbudowane na moją wiedzę.

Typowe powtarzanie plotki 😌.

---

Dla uBO można by dodać blokowanie konkretnego div-a ale ma to bugi jak filtr jest zbyt prosty np. na poczcie wp w `ofertach` jakoś wciska się magicznie fraza "RODO" i znikają nagle maile jakby żadnych tam nie było.

**Comment by seba2282** [comment]
A wiesz o tym, że Gemius połączył się z Adocean? 
https://adocean-global.com/pl/

**Comment by krystian3w** [comment]
Może się łączyć nawet z wodną planetą z innego układu planetarnego / galatyki... 😂 🌊.

**Comment by seba2282** [comment]
Wydaje mi się, że powoli dąży do tego, aby blockery blokowały Adocean/Gemius i redcdn Adserver.
