### ISSUE TITLE
pragroup.pl 

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12691]
Cookies
![Opera Zdjęcie_2019-03-30_095710_pragroup pl](https://user-images.githubusercontent.com/36385327/55273927-41ad5880-52d2-11e9-9aa3-ff500650241e.png)

**Comment by krystian3w** [comment]
Można z tytułu wywalić drugą domenę, ten sam sposób i działa:

```
pragroup.pl###wpfront-notification-bar
```
