### ISSUE TITLE
wabrzezno-cwa.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12713]
reklama ( burgery )

**Comment by krystian3w** [comment]
Are You vegan/vegetarian?

**Comment by gaaargull** [comment]
> blocker999: reklama ( burgery )

![ss549](https://user-images.githubusercontent.com/48046250/55481478-c83f9e00-5622-11e9-9584-d4910689167b.png)

A na dole po lewej też reklama (czesciauto24.pl).

![ss551](https://user-images.githubusercontent.com/48046250/55481513-dbeb0480-5622-11e9-8594-b7bc7f740237.png)
