### ISSUE TITLE
chillizet.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12710]
https://www.chillizet.pl/Styl-zycia/Dom/Goralkski-wiezowiec-Kontrowersyjna-inwestycja-pod-Tatrami-15084
![Opera Zdjęcie_2019-04-02_172829_www chillizet pl](https://user-images.githubusercontent.com/36385327/55415263-04182c00-556d-11e9-877c-51231ce45bd5.png)
![Opera Zdjęcie_2019-04-02_172847_www chillizet pl](https://user-images.githubusercontent.com/36385327/55415264-04182c00-556d-11e9-9941-accd2b70c06d.png)

**Comment by krystian3w** [comment]
Social i  webpush?
