### ISSUE TITLE
truckeronroad.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12724]
![Opera Zdjęcie_2019-04-03_061609_truckeronroad com](https://user-images.githubusercontent.com/36385327/55452443-095e9080-55d8-11e9-8e61-cc1fa567d489.png)

**Comment by gwarser** [comment]
`truckeronroad.com##div.fusion-text, .fusion-no-lightbox` ukrywa treść artykułu: `https://truckeronroad.com/komentarz-eksperta-czy-kontrola-drogowa-moze-sie-odbyc-podczas-wymaganej-przerwy-kierowcy-ciezarowki/`
