### ISSUE TITLE
pebx.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1272]
Strona - `https://pebx.pl/`
Ta reguła `pebx.pl##.message.sectionMain:not([id^="post-"])` ukrywa za dużo, po zalogowaniu się nie ma możliwości odpowiadania na posty oraz jest problem z wyświetleniem wiadomości prywatnej.
Ta powinna być lepsza:
`pebx.pl##li[class="sectionMain message"]:not([id^="post-"])`

Puste miejsce na górze strony - `https://pebx.pl/t/dobry-vpn.1527319/`
![image](https://cloud.githubusercontent.com/assets/11742596/18617088/a3a22c64-7dc8-11e6-9b9d-1317b5590efa.png)
Na przykład:
`pebx.pl##.defaultBorderRadius.pageContent > .funbox.sectionMain`

Przy okazji można też pozbyć się tej pustej przestrzeni z dołu strony.
![image](https://cloud.githubusercontent.com/assets/11742596/18617102/d1ade242-7dc8-11e6-9b85-a5592191dd72.png)
Na przykład:
`pebx.pl###uix_stickyFooterSpacer`

**Comment by MajkiIT** [comment]
@F4z dzięki wielkie
