### ISSUE TITLE
polsatnews.pl

### ISSUE THREAD

**Issue by Tasiorsa** [MajkiIT/polish-ads-filter#12722]
### Zrzut ekranu

![polsatnews](https://user-images.githubusercontent.com/35109319/55425831-aba05900-5583-11e9-8ea3-9808bfc96f74.png)

### Link bezpośredni

http://www.polsatnews.pl/wiadomosc/2019-04-01/po-ko-pyta-o-dzialania-cba-ws-podkarpackiej-seksafery-kuchcinski-to-obrzydliwe-insynuacje/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Kliknąć w link - zamiast odtworzenia materiału filmowego, informacja o Adblocku 

### Moja konfiguracja
**Przeglądarka internetowa:**
Firefox 66.0.2 x64 Win 7 x64 Pro

**Rozszerzenia i skrypty:**

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Oficjalne polskie filtry przeciwko alertom o Adblocku

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by MajkiIT** [comment]
@Tasiorsa Adblock?

**Comment by krystian3w** [comment]
u mnie działa, chyba dobrze przekiopiowane filtry z wątku FadeMind a propozycja od Gmoku i dodatkowe dwa kosmetyczne, by nie dłubać dalej w JS.

**Comment by Tasiorsa** [comment]
Nano Adblocker + Nano Defender

**Comment by gaaargull** [comment]
Po włączeniu listy Adguard Base Filter anty-adblocka nie ma, bo jest taki filtr:
`@@||redefineadpl.hit.gemius.pl/*redataredir?url=*ipla.hit.stat24.com*ad.xml$domain=polsatsport.pl|polsatnews.pl`

Można go jeszcze ograniczyć do żądania `xmlhttprequest` i domeny `www.polsatnews.pl` (bo na `www.polsatsport.pl` anty-adblock nie wyskakuje póki co) czyli:
`@@||redefineadpl.hit.gemius.pl/*redataredir?url=*ipla.hit.stat24.com*ad.xml$xmlhttprequest,domain=www.polsatnews.pl` no chyba, że ktoś chce zapobiegawczo dać też odrazu na `www.polsatnews.pl`

Na POL: Oficjalne polskie filtry przeciwko alertom o Adblocku są podobne filtry: https://github.com/olegwukr/polish-privacy-filters/blob/b3aa4e0f11e7802e2cd371e82b9605e5921ade86/anti-adblock.txt#L362-L363

**Comment by Tasiorsa** [comment]
@gaaargull Dzięki drugi filtr dopisany do Moje Filtry i wszystko dziala :)
