### ISSUE TITLE
wiadomosci.radiozet.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12749]
![Opera Zdjęcie_2019-04-03_233046_wiadomosci radiozet pl](https://user-images.githubusercontent.com/36385327/55514487-876a7800-5668-11e9-8e55-e23d4f8f44f7.png)

**Comment by MajkiIT** [comment]
co jest źle ?

**Comment by krystian3w** [comment]
Webpush ale czemu to zgłaszasz do Macieja, EI nie wycina geolokalizacji i nikt tego nie robi... a webpush dalej możesz normalnie zgłaszać do EI.

**Comment by krystian3w** [comment]
@MajkiIT niby lewe kolumny są poste, chyba o to chodzi i tu wstawiony źle screen.

Jak się da to @xMaap  "nie baw" się w starożytny Egipt i hieroglify, grafika powinna dać znać gdzie szukać jak coś jest trudne do namierzenia na stronie.
