### ISSUE TITLE
meloradio.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12748]
https://www.meloradio.pl/Wiadomosci-muzyczne/Sprzedaz-muzyki-w-2018-roku-zdecydowanie-wzrosla
Pozostałość po reklamie
![Opera Zdjęcie_2019-04-03_232937_www meloradio pl](https://user-images.githubusercontent.com/36385327/55514450-6b66d680-5668-11e9-9be1-fa01564f3ead.png)

**Comment by MajkiIT** [comment]
Co tutaj jest źle ?

**Comment by hawkeye116477** [comment]
@MajkiIT Chyba chodzi o napis „przeczytaj więcej".

**Comment by xMaap** [comment]
@MajkiIT chodzi o "PRZECZYTAJ WIĘCEJ"

**Comment by gaaargull** [comment]
Zgłoszenie kwalifikuje się jako etykieta "błąd" (wycięte sekcje). 
Chyba za dużo wykastrowane, no chyba, że tak ma być? 
<details not-open>
<summary>strona z adblockerem (wykastrowana) - screenshoot</summary>

![z_adblockerem](https://user-images.githubusercontent.com/48046250/55686316-f1806700-595f-11e9-8c0a-1d4421a6f143.png)

</details>
<details not-open>
<summary>strona bez adblockera - screenshoot</summary>

![bez_adblockera](https://user-images.githubusercontent.com/48046250/55686307-e4637800-595f-11e9-94bb-25db48098f03.jpg)

</details>

Generalnie to są 3 sekcje:
- POLECANE po rawej
- POLECANE pod artykułem
- PRZECZYTAJ WIĘCEJ (jeszcze niżej)

Każda z tych sekcji oprócz artykułów zawiera wmieszane pomiędzy nimi reklamy/sponsorowane, sęk chyba w tym, żeby wyciąć tylko reklamy/sponsorowane, a normalne artykuły zostawić. A żeby bylo ciekawiej to błąd występuje chyba na 8 listach filtrów...dopiero po wyłączenia całego adblockera sekcje i artykuły są u mnie przywracane, a listy, które musiałem wyłączyć

```
AdGuard Spyware filter
Fanboy’s Enhanced Tracking List
EasyList
AdGuard Base filter
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda​​​​​użytych
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku​
Polish Privacy Filters​​
Polskie Filtry RODO-Ciasteczkowe DEV​​
```

To tak na szybko, nie jestem pewien, być może któraś z tych list nie psuje, ale chyba większość. No jednego błędu na tylu listach to chyba jeszcze nie spotkałem (znajdowałem sprośne błędy na max 4 listach o ile pamiętam)...

**Comment by krystian3w** [comment]
Na pewno coś podobnego wycina też czasem EI.

**Comment by hawkeye116477** [comment]
Oczywiście to nadal jest nienaprawione, nieładnie @MajkiIT.

**Comment by krystian3w** [comment]
Chyba trzeba na PR jak inne łatwiejsze reklamy zostaną sprzątnięte.

Na pewno w tym chowają po 2 reklamy (jedna na rząd).
