### ISSUE TITLE
pzkosz.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12756]
```
pzkosz.pl
szkolenie.pzkosz.pl
rozgrywki.pzkosz.pl
bbf.pzkosz.pl
sedziowanie.pzkosz.pl
koszkadra.pl
```

![Opera Zdjęcie_2019-04-04_022102_pzkosz pl](https://user-images.githubusercontent.com/36385327/55521256-5007c580-5680-11e9-8583-d21f210deb5c.png)

`koszykowkanawozkach.pl`
Treść ukryta
![Opera Zdjęcie_2019-04-04_022211_koszykowkanawozkach pl](https://user-images.githubusercontent.com/36385327/55521296-86454500-5680-11e9-9bdc-1aff0537fb0f.png)
Social
![Opera Zdjęcie_2019-04-04_022251_koszykowkanawozkach pl](https://user-images.githubusercontent.com/36385327/55521305-92310700-5680-11e9-8857-c9c671f71b6d.png)

**Comment by krystian3w** [comment]
`||koszykowkanawozkach.pl/wp-content/uploads/2018/08/Header-facebook.jpg` - xd
