### ISSUE TITLE
oktawave.com/pl/rodo

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12750]
Bez www nie przekierowuje tam gdzie trzeba
![Opera Zdjęcie_2019-04-03_234450_www oktawave com](https://user-images.githubusercontent.com/36385327/55515331-a8cc6380-566a-11e9-80c2-32e45595d547.png)

**Comment by krystian3w** [comment]
Skąd wiesz gdzie miało przekierować pracujesz w tej firmie?

**Comment by xMaap** [comment]
Bo sprawdzałem :full_moon_with_face:
