### ISSUE TITLE
national-geographic.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1278]
ad block is back!

http://www.national-geographic.pl/galeria/wystartowala-photokina-to-najwazniejsze-na-swiecie-targi-fotogra/wystartowala-photokina

**Comment by F4z** [comment]
Masz dodane do uBlocka "polskie filtry do uBlocka uzupelnienie"?

**Comment by xxcriticxx** [comment]
@F4z nie sorry zamykam bo wstyd
