### ISSUE TITLE
telewizja-live.com

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1279]
Strona wykrywa adblocka - `http://telewizja-live.com/filmowe/canal-plus/`

![image](https://cloud.githubusercontent.com/assets/11742596/18685912/50ba8218-7f7a-11e6-8b49-61b92aee76df.png)

Na przykład:
`@@||osgchmura.tk/tv/player/ads.js$script`

**Comment by xxcriticxx** [comment]
@F4z dzieki za strone narescie discovery polska sobie po oglondam
