### ISSUE TITLE
candy.pl/pl_PL/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12799]
![Opera Zdjęcie_2019-04-06_184306_www candy pl](https://user-images.githubusercontent.com/36385327/55672487-e3691280-589b-11e9-8ce2-10af1dc23897.png)

**Comment by hawkeye116477** [comment]
@xxcriticxx `https://github.com/MajkiIT/polish-ads-filter/pull/12797`
