### ISSUE TITLE
4programmers.net

### ISSUE THREAD

**Issue by TomaszGorczeczewski** [MajkiIT/polish-ads-filter#12796]
### Zrzut ekranu
![4programmers net](https://user-images.githubusercontent.com/49339803/55669001-37f79800-5872-11e9-9591-3b132b7f31a5.png)

### Link bezpośredni
https://4programmers.net/Forum/Off-Topic/325006-strajk_nauczycieli_protesty_grup_spolecznych

(to znajduje się na KAŻDEJ podstronie w dowolnym temacie forum, nie da się tego wyłączyć)

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Po prostu wejść w dowolny temat strony

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome najnowszy

**Rozszerzenia i skrypty:**
uBlock Origin

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Kod HTML tego wnerwiającego elementu to:

`<section class="box sidebar-job-offers java">`

Można to zablokować, blokując klasę CSS **"sidebar-job-offers"**

**Comment by xxcriticxx** [comment]
@TomaszGorczeczewski nie wiem czy to ma sens to blokowac

**Comment by hawkeye116477** [comment]
Jak Ojciec Dyrektor nie będzie tego chciał, to przygarniemy to do EI.

**Comment by xxcriticxx** [comment]
@hawkeye116477 dokladnie mozna dodac do listy EI

**Comment by krystian3w** [comment]
A jako `inny element` czy Widget kontaktowy / feedback?

**Comment by hawkeye116477** [comment]
@krystian3w Inny element

**Comment by MajkiIT** [comment]
@hawkeye116477 @krystian3w to dodajcie do siebie proszę.

**Comment by hawkeye116477** [comment]
Już wczoraj @krystian dodał https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/c7f2612db4224f63d1df507b46f27c474ab2fb07 :smile:
