### ISSUE TITLE
gry-online.poszkole.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1280]
reklama pogoda360

**Comment by F4z** [comment]
Na przykład:
`gry-online.poszkole.pl##a[href^="http://www.pogoda360.pl"]`

Swoją drogą, można też zrobić żeby gry się wcześniej ładowały i nie trzeba było czekać, ale to tylko w uBlocku.
Na przykład ta gra - `http://gry-online.poszkole.pl/gra,Mr_Bean_Hidden_Stars,341244.html`
Obecnie jak się ją włączy, to jest coś takiego - 
![image](https://cloud.githubusercontent.com/assets/11742596/18726429/b167bdf4-8044-11e6-8b00-dfab179b0f6c.png)

>REKLAMA
Trwa ładowanie gry 10%

Po dodaniu tych reguł gra się wczyta bez tego "ładowania":
`gry-online.poszkole.pl###fgame:style(width: 850px !important; height: 600px !important;)`
`gry-online.poszkole.pl###mr-tomato`

**Comment by MajkiIT** [comment]
@F4z Dzięki wielkie. Dodane do obu list.

**Comment by F4z** [comment]
Odnośnie reklamy jeszcze, to pod samą grą jest blokowana, ale na stronie głównej już nie.
![image](https://cloud.githubusercontent.com/assets/11742596/18729104/a2096270-8050-11e6-8c14-88a157983e7f.png)

Ta reklama jest prawie na samym dole strony.

Może coś takiego:
`||static.osemka.pl/pixad/$image,domain=gry-online.poszkole.pl`

**Comment by MajkiIT** [comment]
Poprawione. Dzięki

**Comment by F4z** [comment]
Ok, tylko ta reguła -  `gry-online.poszkole.pl##[id^="billboard"]` źle działa, bo strona dziwnie wtedy wygląda. To znaczy, jeden z elementów strony, który powinien być na dole, idzie wyżej i zasłania inne rzeczy, na przykład tutaj - `http://gry-online.poszkole.pl/najnowsze.html`

![image](https://cloud.githubusercontent.com/assets/11742596/18740419/db5f400e-80a9-11e6-8f80-059c16e70f2e.png)

**Comment by MajkiIT** [comment]
Już poprawiam.
