### ISSUE TITLE
gry.lotto.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12819]
![Opera Zdjęcie_2019-04-10_023611_gry lotto pl](https://user-images.githubusercontent.com/36385327/55843615-77a3d580-5b39-11e9-9d91-e20c3cce886d.png)

**Comment by krystian3w** [comment]
Lotto w dodatku, bo dodatki mogą zablokować za dużo pop-upów - błąd w stylu: https://github.com/uBlockOrigin/uBlock-issues/issues/341

**Comment by xMaap** [comment]
Mam zainstalowany
![Opera Zdjęcie_2019-04-10_192223_startpage](https://user-images.githubusercontent.com/36385327/55899806-02321680-5bc6-11e9-8b82-c2de52f04e38.png)

**Comment by krystian3w** [comment]
OK, no to pewnie się naprawi w podobnym czasie jak Yahoo, jak hawkey skończy proces automatyzacji pod AMO.
