### ISSUE TITLE
vod.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1281]
@F4z @xxcriticxx

Na vod.pl wrócił komunikat o adblocku. Możecie sprawdzić czy ta reguła wam zadziała?
`||bcx.onet.pl$xmlhttprequest,domain=vod.pl`

**Comment by F4z** [comment]
@MajkiIT pisałem o tym wczoraj 😛, ale chyba powinienem otworzyć nowy temat do tego, bo pisanie w stary wątku nie zwraca tak uwagi.

https://github.com/MajkiIT/polish-ads-filter/issues/1233#issuecomment-248431744

Odnośnie pytania, ta reguła u mnie działa.

**Comment by MajkiIT** [comment]
@F4z Przepraszam uleciało mi. Może masz rację otwieraj nowe zgłoszenie to nie uleci.

**Comment by F4z** [comment]
@MajkiIT nie ma problemu, następnym razem tak zrobię :)

**Comment by xxcriticxx** [comment]
narazie tylko vod.pl czy onet.pl tak samo?

**Comment by F4z** [comment]
U mnie onet.pl też.
@MajkiIT myślę, że możesz dodać też  onet do tej reguły.

**Comment by MajkiIT** [comment]
Ok zaraz dodam,.

**Comment by F4z** [comment]
@MajkiIT znowu jest komunikat o adblocku na vod.pl

Dzisiaj jest `btr.onet.pl`, jutro pewnie będzie co innego.

Można dodać tę regułę, ale pewnie nie będzie działała długo:
`||btr.onet.pl$xmlhttprequest,domain=vod.pl`

Można dodać tę, tylko trzeba sprawdzić czy nic nie psuje:
`/:\/\/(?!media)[a-zA-Z0-9]{3,8}\.onet\.pl\//$xmlhttprequest,domain=vod.pl`

Można dodać też tę:
`@@||vod.pl^$generichide`

albo takie coś:
<pre>vod.pl#@#.text_ads
vod.pl#@#.text_ad
vod.pl#@#.text-ad
vod.pl#@#.textAd
vod.pl#@#.text-ads
vod.pl#@#.text-ad-links
vod.pl#@#.pub_728x90
vod.pl#@#.pub_300x250m
vod.pl#@#.pub_300x250
vod.pl#@##admain</pre>

Ewentualnie można zablokować ten skrypt - `http://sgqcvfjvr.onet.pl/YnthN0xfTTlyfXVpbGQvZGxBcGkve3E3UlZRb31kbC5saWIubWluLmpz`, tyle że nie wiem czy przy okazji nie zablokuje się czegoś potrzebnego do prawidłowego działania strony:
`||sgqcvfjvr.onet.pl^$script,domain=vod.pl`

**Comment by MajkiIT** [comment]
Celował bym w to /:\/\/(?!media)[a-zA-Z0-9]{3,8}\.onet\.pl\//$xmlhttprequest,domain=vod.pl . Wydaje się najbardziej uniwersalna.

**Comment by xxcriticxx** [comment]
a ja bym hyba to po testowal `@@||vod.pl^$generichide`

**Comment by MajkiIT** [comment]
@F4z zmieniłem regułę zamieniająć 8 na 9 
`/:\/\/[a-zA-Z0-9]{6,9}\.onet.pl\//$script,xmlhttprequest,domain=www.onet.pl|vod.pl `
