### ISSUE TITLE
lg.com/pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12829]
![Opera Zdjęcie_2019-04-10_161915_www lg com](https://user-images.githubusercontent.com/36385327/55886637-6d6eef00-5bac-11e9-95ea-5d2650b68850.png)

**Comment by krystian3w** [comment]
Jak gdzieś poza home jest to przerobię na sprawdzanie zawartości.

**Comment by xMaap** [comment]
Nie ma nigdzie.

No może poza tym http://lgnews.pl
![Opera Zdjęcie_2019-04-10_192634_lgnews pl](https://user-images.githubusercontent.com/36385327/55900047-97cda600-5bc6-11e9-8b69-92385334d644.png)
