### ISSUE TITLE
lenovo.com/pl/pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12827]
![Opera Zdjęcie_2019-04-10_161801_www lenovo com](https://user-images.githubusercontent.com/36385327/55886554-444e5e80-5bac-11e9-8e12-6f407c5aea65.png)

**Comment by krystian3w** [comment]
`##.m-footerSocial`

RSS to fejk...

**Comment by krystian3w** [comment]
A i nie mam ochoty pchać tego do Fanboya, niech kiedyś Smed79 zablokuje.

**Comment by hawkeye116477** [comment]
RSS robi za forum, także może lepiej to zostawić :smile:.
