### ISSUE TITLE
pl.search.yahoo.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12824]
![Opera Zdjęcie_2019-04-10_024956_consent yahoo com](https://user-images.githubusercontent.com/36385327/55843969-58a64300-5b3b-11e9-859e-f852e2c8b948.png)

**Comment by krystian3w** [comment]
To nie my - Fanboy to rozwalił.

**Comment by krystian3w** [comment]
Yahoo / Oath zamyka dodatek "Polska ciasteczkowa zgoda".

**https://github.com/PolishFiltersTeam/PolishCookieConsent/blob/master/README.md#jak-zainstalowa%C4%87**

**Comment by krystian3w** [comment]
Błędny filtr do Fanboyów zgłoszony a domenę ogarnie się po ogarnięciu dodatku w `sklepie dodatków Moz://a`.

**Comment by gaaargull** [comment]
> krystian3w: Yahoo / Oath bad filters in Cookie list #1003 / Błędny filtr do Fanboyów zgłoszony

Już to zgłaszałem 16 dni wcześniej, założyłeś duplikat mojego zgłoszenia: https://github.com/ryanbr/fanboy-adblock/issues/1003#issuecomment-481754483.

**Comment by krystian3w** [comment]
Jak tyle im zajmuje analiza...

**Comment by gaaargull** [comment]
> krystian3w Jak tyle im zajmuje analiza...

To może załóż kolejny duplikat albo od razu 10, będzie jeszcze bardziej widoczne, spamem raczej nie wymusza się od autorów szybszego naprawiania...

**Comment by krystian3w** [comment]
No to zrobiłem PR, pewnie za dwa miesiące zaakceptują / odrzucą.

**Comment by gaaargull** [comment]
Chociaż przyznam, że fanboy tam już długo nie ogarniał jakoś ze 3 tygodnie, ale co to jest w porównianu z EasyList, moje zgłoszenia tam wiszą od 5 miesięcy: https://github.com/easylist/easylist/issues/created_by/kulfoon, nie wspominajac o innych zgłoszeniach.

**Comment by krystian3w** [comment]
Lepiej sprawdź mi tę domenę czy wyłapujesz jakąś inną, by się Khrin nie czepiał/czepiała jak będzie mieć chęć naprawy pod nieobecność "Rynbara"?
