### ISSUE TITLE
fanclub.huaweipolska.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12825]
![Opera Zdjęcie_2019-04-10_052152_fanclub huaweipolska pl](https://user-images.githubusercontent.com/36385327/55849357-9792c380-5b50-11e9-8b18-535b9f514d54.png)

**Comment by krystian3w** [comment]
Jezu jakie 💩, 2 statyczne kolumny a 3 się przewija i jeszcze jakieś czarne coś wyskakuje przy przewijaniu...
