### ISSUE TITLE
trawnikproducent.pl/pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12830]
![Opera Zdjęcie_2019-04-10_162111_trawnikproducent pl](https://user-images.githubusercontent.com/36385327/55886812-b45ce480-5bac-11e9-9b1d-521f7dbfdfdd.png)

**Comment by krystian3w** [comment]
Niby od tygodnia nie działa Google+?

**Comment by krystian3w** [comment]
@hawkeye116477 wiesz coś o planach oczyszczania znanych filtrów social z Google Plus?

**Comment by hawkeye116477** [comment]
@krystian3w Nie
