### ISSUE TITLE
sokolow.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12833]
![Opera Zdjęcie_2019-04-10_162414_sokolow pl](https://user-images.githubusercontent.com/36385327/55887045-1f0e2000-5bad-11e9-9f4c-02c050172efd.png)

**Comment by krystian3w** [comment]
Golden i pracuj out?

**Comment by xMaap** [comment]
Jak Linkedin jest to i Gloken powinien być to prawie to samo.

**Comment by krystian3w** [comment]
No niby tak a co z pracuj, wyciąłem bo badziewnie wygląda 1 kafelek na białym tle.

Jak ma zostać to w uBO trzeba wyśrodkować i tło podmienić by nie było badziewnie.

**Comment by xMaap** [comment]
A wytnij to i już
