### ISSUE TITLE
forum.cdaction.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1283]
Ogłoszenie sponsorowane - `http://forum.cdaction.pl/topic/62728-okazyjne-ceny-gier-w-r%C3%B3%C5%BCnych-sklepach/?page=1`

![image](https://cloud.githubusercontent.com/assets/11742596/18728876/90f7fbf0-804f-11e6-8dd5-b8407140df94.png)

Na przykład:
forum.cdaction.pl##[class="cPost ipsBox ipsComment ipsComment_parent ipsClearfix ipsClear ipsColumns ipsColumns_noSpacing ipsColumns_collapsePhone"]:not([id^="elComment_"])

**Comment by MajkiIT** [comment]
Tylko ublock?

**Comment by F4z** [comment]
Nie, to "normalna" reguła i w Adblocku powinna też działać.

**Comment by MajkiIT** [comment]
Już dodaje.
