### ISSUE TITLE
polskawoda.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12831]
Social
![Opera Zdjęcie_2019-04-10_162230_www polskawoda com pl](https://user-images.githubusercontent.com/36385327/55886913-e66e4680-5bac-11e9-86f1-7de49ab806e8.png)

**Comment by krystian3w** [comment]
Trochę łysy będzie 1 slajd, może kiedyś się wytnie go html filteringiem lub filtrami 🐧.
