### ISSUE TITLE
media.polsatsport.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12847]
https://media.polsatsport.pl/szczesny-nie-jestem-spokojny-przed-rewanzem-ale-wierze-w-ronaldo-PAYz2N-18289879.html
![Opera Zdjęcie_2019-04-11_204237_media polsatsport pl](https://user-images.githubusercontent.com/36385327/55983015-6d4d1d00-5c9a-11e9-9edb-b6a004ad0a80.png)

**Comment by krystian3w** [comment]
```
@@||www.google-analytics.com/analytics.js$script,domain=dcs.redcdn.pl
@@||gapl.hit.gemius.pl/gplayer.js$script,domain=dcs.redcdn.pl
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=dcs.redcdn.pl
```

teraz oczyścić z nadmiernych dopuszczeń.

**Comment by krystian3w** [comment]
uBO nabiera stronę na pusty dopuszczony plik:

```
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect=noopjs,domain=dcs.redcdn.pl
||www.google-analytics.com/analytics.js$script,redirect=noopjs,domain=dcs.redcdn.pl
```
