### ISSUE TITLE
e-lokalne.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12849]
3 x FB ( u góry )

**Comment by krystian3w** [comment]
@hawkeye116477  masz to?

**Comment by krystian3w** [comment]
`#?#.box-nieb:-abp-has(a[href*="facebook"] ~ a[href*="twitter"])`

ale to na prawo...

**Comment by hawkeye116477** [comment]
@krystian3w 
![Screenshot_20190412_172506](https://user-images.githubusercontent.com/19818572/56048514-fa01e480-5d47-11e9-9c64-cc19b631ca93.png)

**Comment by krystian3w** [comment]
W artykułach @MajkiIT są reklamy:

http://e-lokalne.pl/index2.php?idmodyf=227&tab=weekend

`##.box-ziel` może bezpiecznym filtrem

![obraz](https://user-images.githubusercontent.com/35370833/56050133-574b6500-5d4b-11e9-94bd-4b0cb45c4955.png) |
--- |
