### ISSUE TITLE
zubr.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12842]
Social
![Opera Zdjęcie_2019-04-11_000900_zubr pl](https://user-images.githubusercontent.com/36385327/55916934-0d00a180-5bee-11e9-8f8c-76b34bf1c932.png)

**Comment by krystian3w** [comment]
Gdzie, to nie są social buttony a druga lista FAQ-a.

![obraz](https://user-images.githubusercontent.com/35370833/55972789-77642100-5c84-11e9-8023-f70678ddce51.png) |
--- |
