### ISSUE TITLE
e-chorzow.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#12859]
cookies

**Comment by krystian3w** [comment]
@hawkeye116477  wiesz może co tam blokuje ładowanie zdalnej czcionki?

**Comment by hawkeye116477** [comment]
No na pewno nie filtry, to wina admina strony.

**Comment by krystian3w** [comment]
Bo już prawie to wyciąłem jako strzałkę w górę ale potem patrzę a to niby search.
