### ISSUE TITLE
www.serialnet.pl

### ISSUE THREAD

**Issue by exmil** [MajkiIT/polish-ads-filter#1286]
przy kliknięciu w cokolwiek, pojawia się reklama w nowej karcie, która zazwyczaj mówi o ściągnięciu programu/ czyszczeniu maca itp.

**Comment by MajkiIT** [comment]
Jakiś konkretny adres?

**Comment by xxcriticxx** [comment]
naciskasz na tytul serialu i sie odtwiera nowe okno za kazdym razem cos nowego 

http://play.leadzupc.com/?m=0CA5JG162036&offer_key=162036&a=157e5264b14d5d247113350
http://www.dogbreedersguide.com/wp-content/themes/foodica-child/homepage.php?utm_source=P6&utm_medium=click&utm_campaign=top-videos&utm_term=
http://forums.philosophyforums.com/ads/quotelist.php?utm_source=AC6&utm_medium=click&utm_campaign=top-videos&utm_term=
http://gametrone.com/wp-content/themes/tronee/categorycheats.php?utm_source=AC6&utm_medium=click&utm_campaign=top-videos&utm_term=AC6

**Comment by F4z** [comment]
Może ta reguła rozwiąże problem:
`||130.211.198.219^$script`

**Comment by MajkiIT** [comment]
ja za Chiny nie mam czegoś takiego.

**Comment by xxcriticxx** [comment]
@MajkiIT ty masz pirackje filtry :)

**Comment by xxcriticxx** [comment]
@F4z ta regula dziala super

**Comment by F4z** [comment]
@MajkiIT ja w Firefoksie też tego nie mam, ale w Chrome i Operze tak.

**Comment by xxcriticxx** [comment]
ale jest hyba ad block jak odciek wlaczas http://serialnet.pl/ogladaj-online/1-53328/100-greatest-discoveries-sezon-1-odcinek-3 chce sie z google polonczyc

**Comment by MajkiIT** [comment]
@F4z Ok dodam regułę do następnej wersji.

**Comment by MajkiIT** [comment]
Dodane
