### ISSUE TITLE
www.onet.pl

### ISSUE THREAD

**Issue by AndrzejKw** [MajkiIT/polish-ads-filter#1287]
Nie działa poprawnie przy aktualnym filtrze.
Często nie ładują się elementy strony a w konsoli widzę:
Problem loading scripts - try to reload or disable adblock

**Comment by Isamaul** [comment]
Niestety po aktualizacji listy losowo znikają obrazki - niby jakoś straszne to nie jest, ale trochę jednak przeszkadza

<img width="839" alt="screenshot at wrz 23 12-12-07" src="https://cloud.githubusercontent.com/assets/20810329/18782601/86d29412-8187-11e6-87d3-0e744a41bdef.png">

**Comment by MajkiIT** [comment]
zaraz zerknę

**Comment by MajkiIT** [comment]
@AndrzejKw @Isamaul pobierzcie aktualizację filtrów

**Comment by AndrzejKw** [comment]
Jest ok. Działa poprawnie :) 
Dzięki!!!

**Comment by MajkiIT** [comment]
@AndrzejKw Dzięki

**Comment by Jurigag** [comment]
@MajkiIT u mnie na operze i natywnym blokerze znowu nie działa :C

**Comment by MajkiIT** [comment]
Bo musiałem zastosować multiregex i tam to nie działa.

**Comment by MajkiIT** [comment]
Element który jest za to odpowiedzialny to  k266d5zsl.onet.pl .... dodaje to i sprawdź 

||k266d5zsl.onet.pl/$xmlhttprequest,domain=vod.pl|www.onet.pl

**Comment by Jurigag** [comment]
U mnie takiego adresu nawet nie ma :P O dziwo wyczyściłem cookiesy i local storage i działa, wtf.
