### ISSUE TITLE
filing.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12886]
`http://filing.pl/ta-firma-zamienia-dzieciece-rysunki-w-przytulne-pluszowe-zabawki/`
![Zrzut ekranu z 2019-04-13 04-03-42](https://user-images.githubusercontent.com/36385327/56073267-28f87480-5da1-11e9-95ba-24e0db0b14bf.png)

**Comment by krystian3w** [comment]
Nie mam - wyłącz na próbę Fanboy Cookie List.

@kulfoon  zobacz czy to może fanboy nie dodał wyjątków pod overlay?

**Comment by xMaap** [comment]
@krystian3w wyłączyłem i nic

**Comment by xMaap** [comment]
Jeszcze jest tam social
![Opera Zdjęcie_2019-04-13_231256_filing pl](https://user-images.githubusercontent.com/36385327/56085343-b5f30a80-5e41-11e9-8166-7d6bbddeea27.png)

**Comment by krystian3w** [comment]
A jak wyłączysz to pokazuje się pop-up z czymś?

**Comment by xMaap** [comment]
@krystian3w 
![Opera Zdjęcie_2019-04-13_231836_filing pl](https://user-images.githubusercontent.com/36385327/56085388-81338300-5e42-11e9-94bf-69fa0b2846c4.png)

**Comment by xMaap** [comment]
Wina Fanboy's Social Blocking List

**Comment by krystian3w** [comment]
A to dziwne, aż "jutro" to obadam chyba w Chrome i w świeżym Firefox z Adblock Plus czy wyskoczy.

**Comment by gaaargull** [comment]
Zgadzam się, że dziwne, bo ja to wczoraj sprawdzałem i u mnie tego błędu nie ma ani na Firefoxie ani na Operze, zawsze pokzauje się ten popup social, nawet pomimo usilnych prób wywołania tego błędu czyli różnych kombinacji list Adguard i Fanboy i kilku innych list.

**Comment by krystian3w** [comment]
Może EI go wycina a xMapp używa nagle kilku modułów zamiast całej.
