### ISSUE TITLE
tygodnik.tvp.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#12888]
https://tygodnik.tvp.pl/41813226/obroncy-tradycji-przegrali-z-postepem-czy-inna-cywilizacja

```
pl##.facebook-paragraph
```

![s](https://i.imgur.com/PAYVAEd.png)

**Comment by xMaap** [comment]
http://sport.tvp.pl/42182264/real-madryt-santiago-bernabeu-przebudowa-kredyt-finansowanie-575-milionow-7965-miliona
![Opera Zdjęcie_2019-04-13_094139_sport tvp pl](https://user-images.githubusercontent.com/36385327/56076358-74764700-5dd0-11e9-9be9-bec53c0f87ea.png)

**Comment by FadeMind** [comment]
@xMaap 
```
pl##.news-tags__social
```

**Comment by krystian3w** [comment]
Zakładam że każda sudomena tvp to ma i jeszcze gdzieś znaleźliście.
