### ISSUE TITLE
dobiegania.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12880]
Social
```
https://www.dobiegania.pl
https://www.badmin.pl
https://www.squashtime.pl
```
![Opera Zdjęcie_2019-04-13_035641_www dobiegania pl](https://user-images.githubusercontent.com/36385327/56073183-4842d200-5da0-11e9-92f3-46013a8913e3.png)

**Comment by krystian3w** [comment]
@hawkeye116477  ten kupon to nie ruszać nigdzie?

**Comment by hawkeye116477** [comment]
@krystian3w Tak, zostawiamy
