### ISSUE TITLE
addnature.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12885]
Social
![Opera Zdjęcie_2019-04-13_040134_www addnature pl](https://user-images.githubusercontent.com/36385327/56073241-dfa82500-5da0-11e9-8796-afa2c2a753cf.png)

**Comment by krystian3w** [comment]
@hawkeye116477  dotniesz brzydki newsletter?

**Comment by hawkeye116477** [comment]
W kodzie w komentarzu zamieścili reklamę :smiley:

**Comment by krystian3w** [comment]
Co?

**Comment by hawkeye116477** [comment]
```
<!--
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@8c  cCc: .o@@@@@@@@@@@@
@@@@@@@@@O:C@@@8.    o@@@@8.@@@@@@@@@@@@
@@@@@@o  .@@C..o     o@@@@8.8@@@@@@@@@@@
@@@@C   c@@@@@@@o.   C@@@@8 8@@@@@@@@@@@
@@@c   O@@@@@@@@@@@@oO@@@@@.oo::... @@@@
@8      cO@@@@@@@@@@@@@@@@@@@@@@@@@C.@@@

Looking for a job?
We're hiring, apply now! http://www.internetstores.com/karriere.html
-->
```

**Comment by krystian3w** [comment]
A to niczym nie wytniesz. Nawet html filteringiem.

**Comment by hawkeye116477** [comment]
No przecież wiem, tak tylko informuje :smile:

**Comment by krystian3w** [comment]
A co to oni namalowani w tym ASCII - nic nie widzę szczególnego...

**Comment by gargul2** [comment]
Jakiegoś gościa pchającego wózek, czyli typowy symbol pracownika.
