### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#12890]
`https://www.elektroda.pl/`

Anty-adblock.

![obraz](https://user-images.githubusercontent.com/35370833/56081928-f38c6f00-5e12-11e9-971a-fbedc047f757.png) |
--- |

Stare rozwiązania z Ads by Google nie chcą działać.

**Comment by gaaargull** [comment]
To zgłoszenie to kolejny przypadek tego samego bugu: https://github.com/uBlockOrigin/uBlock-issues/issues/521#issuecomment-482869220, a jak coś to działa: `@@||elektroda.pl^$generichide`, jeśli ktoś chce szukać konkretnych filtrów, które wywołują anty-adblocka (bo przez bug w uBO, w loggerze uBO ich nie ma pokazanych) to musi szukać ręcznie i życzę mu powodzenia...

**Comment by krystian3w** [comment]
Albo taki koszmarek:

```
###main > .content-wrap > .container > .row > div[class*="-"][class*=" "]:nth-of-type(1):nth-child(1)
```

`nth` dla "zmniejszenia ryzyka".

**Comment by gaaargull** [comment]
Zapomniałem wspomineć przy okazji, że anty-adblock jest usuwany również przez Nano Defndera.

**Comment by gaaargull** [comment]
Najpierw trzeba sprawdzić czy pierwsze rozwiązanie z `generichide` w czymś przeszkadza (czy wyskakują jakieś reklamy/kontenery), bo jeśli nie, to wystarczy.

A jeśli w czymś przeszkadza, to jako alternatywne rozwiązanie tak jest krócej i lepiej (chwyta szybko, bez spowolnienia): `www.elektroda.pl##section.row > div[class]:nth-of-type(1):-abp-contains(Adblock)`.

Ale `generichide` chyba wystarczy bo jak widać został już dodany:
https://github.com/olegwukr/polish-privacy-filters/commit/25c195857e7e05853aa766b1b211c52a003e93d0

===================================================================

<details not-open>
<summary>
Przy okazji chciałem zapytać czy te reklamy też kwalifikują się do zablokowania czy nie, czy to są reklamy ? reklamy wewnętrzne ? a może sponsorzy ?:</summary>

![ss_001](https://user-images.githubusercontent.com/48046250/56091248-d2785c80-5eac-11e9-8c54-3b22f5520f15.png)

</details>

<details not-open>
<summary>Po zastosowaniu Filtrów Wewnętrznych + Irytujących tylko część górnych jest usunięta:</summary>

![ss_003](https://user-images.githubusercontent.com/48046250/56091281-592d3980-5ead-11e9-8bc6-c520ddace3da.png)

</details>

**Comment by gaaargull** [comment]
Zgłoszone tu: https://github.com/easylistpolish/easylistpolish/issues/107
