### ISSUE TITLE
bikester.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#12892]

**Comment by krystian3w** [comment]
@hawkeye116477  jak te nowe wycinasz to przy ostatnim dodaj sławne "zrobione do #...".

**Comment by hawkeye116477** [comment]
@krystian3w Tych póki co nie ruszałem, jedynie moje własne znaleziska.

**Comment by krystian3w** [comment]
To jak coś wszystkie od tego w górę nie ruszszałem.


Zgloszenia xMapp i Blokera reklamowe rzadko przeglądałem ile cookies wycina Kiboke / Fanboy.
