### ISSUE TITLE
overwatch.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#12891]
`https://overwatch.pl/`

Anty-adblock.

![obraz](https://user-images.githubusercontent.com/35370833/56081954-5847c980-5e13-11e9-89a8-b96f92f029f6.png) |
--- |

<!---

`overwatch.pl##+js(abort-on-property-read.js, adBlockDetected)`

```
overwatch.pl#@#.rightAd
overwatch.pl#@#.mini-ad        
overwatch.pl#@#.bottomAd

overwatch.pl#@#.adlabel 
overwatch.pl#@#.advertbox3 
overwatch.pl#@#.sky_advert 
overwatch.pl#@#.top_ad_game
```

**Comment by gaaargull** [comment]
U mnie ten anty-adblock się nie pokazuje.

**Comment by krystian3w** [comment]
Tak i twórcy stwierdzili że nie naprawią...

**Comment by krystian3w** [comment]
https://github.com/dhowe/AdNauseam/issues/1484

**Comment by krystian3w** [comment]
Albo i samo nagle zniknęło...

**Comment by gaaargull** [comment]
Hmm chyba już naprawili w EasyList (tak szybko?) bo u mnie to nawet z EasyList ten anty-adblock się nie pokazuje.

**Comment by krystian3w** [comment]
Od kiedy niby EasyList naprawia..., nie wierzę też w naprawę ze strony: `Adblock Warning Removal List` Albo 🐧.

**Comment by krystian3w** [comment]
Musiało się coś na noc zbugować przy okazji tam.

**Comment by gaaargull** [comment]
> krystian3w: Od kiedy niby EasyList naprawia

Kilka razy w niektórych zgłoszeniach na https://github.com/uBlockOrigin/uAssets/issues widziałem dołączone dodatkowe commity EasyList zrobione szybko od ręki, bo coś tam trzeba było w EasyList naprawić przy okazji, ale w tym przypadku jednak nie naprawili nic bo nie widać w commitach żeby coś w ciągu kilku ostatnich godzin naprawili: https://github.com/easylist/easylist/commits/master, więc jednak raczej przyczyny, który ty podajesz.
