### ISSUE TITLE
piekarniabialogon.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12913]
![Opera Zdjęcie_2019-04-14_040424_piekarniabialogon pl](https://user-images.githubusercontent.com/36385327/56087384-70970300-5e6a-11e9-99b1-3a1e622cd760.png)

**Comment by gaaargull** [comment]
To jest błąd filtrów zewnętrznych (Fanboy Cookie List), zgłosiłem to przed chwilą: https://github.com/ryanbr/fanboy-adblock/issues/987.
