### ISSUE TITLE
onet.pl | vod.pl 

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1293]
Znowu adblock.
Na przykład:
`/:\/\/(?!media)(?!www)[a-zA-Z0-9]{3,15}\.onet\.pl\//$xmlhttprequest,domain=vod.pl|www.onet.pl`
albo
`/:\/\/(?!media)(?!www)[a-zA-Z0-9]{3,}\.onet\.pl\//$xmlhttprequest,domain=vod.pl|www.onet.pl`

Ewentualnie te:
`@@||onet.pl^$generichide`
`@@||vod.pl^$generichide`

**Comment by xxcriticxx** [comment]
a player.pl?

**Comment by F4z** [comment]
@xxcriticxx player.pl to tak samo jak tutaj - https://github.com/MajkiIT/polish-ads-filter/issues/1292
Możesz sprawdzić te reguły:
`@@||player.pl$generichide`
`@@||tvn.adocean.pl/ad.xml$xmlhttprequest,domain=player.pl`
`@@||tvn.adocean.pl/__/ad.xml$xmlhttprequest,domain=player.pl`
Niestety to rozwiązanie nie działa w Firefoksie, bo tam jest wykorzystywany silverlight, ale w Chrome i Operze powinno działać tak samo jak na stronie tvnturbo. Czyli co jakiś czas będzie komunikat, że "materiał jest niedostępny", ale po kilku odświeżeniach strony powinno ruszyć.
Jeszcze jedną wadą tego jest to, że gdy reklama jest w trakcie filmu, to w momencie kiedy powinna się wyświetlić, film zostanie przerwany i dalej nie będzie się odtwarzał.
Niestety na razie nie znalazłem lepszego rozwiązania dla wtyczek blokujących reklam.

Możesz też sprawdzić trzeci punkt stąd - http://www.certyficate.it/tvn-wp-player-pl-bez-reklam-adblock-usuwanie-reklam/

Ewentualnie można jeszcze zainstalować Adguarda dla Windowsa i dodać odpowiednie reguły (których nie obsługują wtyczki), ale on jest płatny.

**Comment by xxcriticxx** [comment]
mam adguard pro na iphone ale tez nie dziala

**Comment by F4z** [comment]
Ale Adguard Pro na iOS to co innego niż Adguarda dla Windowsa.
O ile się dobrze orientuję, to Adguard w wersji na iOS ze względu na pewne ograniczenia nie obsługuje nawet wszystkich typów reguł, które obsługują wtyczki do przeglądarki.

**Comment by xxcriticxx** [comment]
ta safari ma limit 50000 filtrow czy cos takiego czyli easylist niema ale jest cos innego teraz mam prawie 29000 filtrow

**Comment by F4z** [comment]
No tak, jest limit, ale mi chodziło o reguły, które mogą na przykład zmienić zawartość strony - https://adguard.com/en/filterrules.html#replace
zmienić style danych elementów - https://adguard.com/en/filterrules.html#cosmetic-css-rules albo reguły opierające się na javascript - https://adguard.com/en/filterrules.html#javascript-rules bo tych Adguard na iOS niestety nie obsługuje.

Swoją drogą, na iPhonie sprawdzałeś przez przeglądarkę, czy przez aplikację player.pl?

**Comment by xxcriticxx** [comment]
przez przegladarke. jestem poza granica aplikacja nie dziala

**Comment by F4z** [comment]
A to bez Adguarda przez przeglądarkę Ci działa?
Bo mi coś nie chce.

**Comment by xxcriticxx** [comment]
rozmawiamy o turbo czy player?

**Comment by F4z** [comment]
Ja o player.pl pisałem.

**Comment by xxcriticxx** [comment]
tak player.pl dziala normalnie w safari tylko musze polskie ip zlapac

**Comment by xxcriticxx** [comment]
@F4z zobacz cos nie tak z wp.pl po dzisejszym updatecie https://github.com/MajkiIT/polish-ads-filter/issues/1294

jest teraz na maszynie bez host file firefox 49 i lista @MajkiIT

**Comment by F4z** [comment]
U mnie przez safari coś nie działa, nawet jak wyłączę Adguarda, potem sprawdzę co jest nie tak.
Ok, zaraz odpiszę w temacie z wp.pl.

**Comment by xxcriticxx** [comment]
jak wykryje na safari ad block na player.pl to play i zwiastun guzik znika

**Comment by xxcriticxx** [comment]
przed:

![img_3347](https://cloud.githubusercontent.com/assets/15007183/18893317/63b14e7c-84db-11e6-8c9b-fa06a18cc2ee.PNG)

trakcje:

![img_3348](https://cloud.githubusercontent.com/assets/15007183/18893335/78487874-84db-11e6-8f1e-2904c3ada917.PNG)

po:

![img_3347](https://cloud.githubusercontent.com/assets/15007183/18893338/7df2b4a6-84db-11e6-8ad2-47282d821e65.PNG)

**Comment by xxcriticxx** [comment]
ok napisalem o turbo.pl do adguard zobaczymy co bendzie do zobaczenia za godzine

**Comment by F4z** [comment]
Ok, dzięki.
