### ISSUE TITLE
masz.gliwice.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12936]
Social
![Opera Zdjęcie_2019-04-14_044917_www masz gliwice pl](https://user-images.githubusercontent.com/36385327/56087718-b35bd980-5e70-11e9-8bf5-82b9c8b0f039.png)

**Comment by krystian3w** [comment]
```
##.col-social-icons.col > .footer-h4
##.fa-google-plus.fa
```

@hawkeye116477  może być tak? Zostanie ta enova i przycisk łatwiej będzie okresowo sprawdzać czy usunięty po wyłączeniu G+.

**Comment by hawkeye116477** [comment]
@krystian3w Tak
