### ISSUE TITLE
firstweb.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12933]
Social
![Opera Zdjęcie_2019-04-14_044603_firstweb pl](https://user-images.githubusercontent.com/36385327/56087689-40eaf980-5e70-11e9-98c3-78ec6d944110.png)

**Comment by hawkeye116477** [comment]
Certyfikat im wygasł, zaraz dodamy do KADa :smile:.

**Comment by krystian3w** [comment]
Do fanboya generyk `##.dslc-social`... z 2000 domen...

**Comment by hawkeye116477** [comment]
Certyfikat rok temu wygasł, także raczej już nie odnowią.

**Comment by krystian3w** [comment]
Ale nagle innych 2000 stron nie padnie, bo firma szabloniarska by niby zniknęła.
