### ISSUE TITLE
shinden.pl 

### ISSUE THREAD

**Issue by HeheheM** [MajkiIT/polish-ads-filter#12949]
### Zrzut ekranu
https://i.imgur.com/DHFzSGx.png

### Link bezpośredni
https://shinden.pl/episode/2395-death-note/view/24267

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść w link powyżej z adguardem.

### Moja konfiguracja
**Przeglądarka internetowa:**
Opera
**Rozszerzenia i skrypty:**
Adguard
**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Wczoraj jeszcze wszystko działało, dzisiaj musieli coś namieszać.

**Comment by HeheheM** [comment]
Już spatchowane, wszystko działa jak należy, można zamknąć.

**Comment by krystian3w** [comment]
Znowu wszędzie padło - uBO / AdGuard.
