### ISSUE TITLE
film.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1294]
ad block z dzisiejszymi filtrami

filtry z v.2016092701 aktualizacja: wt, 27 września 2016, 18:50:00

http://film.wp.pl/osobliwy-dom-pani-peregrine-najlepszy-film-tima-burtona-od-lat-6041438519469185a

![capture](https://cloud.githubusercontent.com/assets/15007183/18892739/b4bff456-84d8-11e6-8c56-ba0c57d9f798.PNG)

**Comment by xxcriticxx** [comment]
http://gwiazdy.wp.pl/steph-lecor-w-przeswitujacej-sukience-seksowna-6041618487182465g
http://www.money.pl/gospodarka/wiadomosci/artykul/palenie-weglem-ustawa-antysmogowa-krakow,194,0,2161602.html
http://finanse.wp.pl/kat,1033781,title,Firma-Zywiec-Zdroj-wznawia-sprzedaz-wody-mocno-gazowanej,wid,18520730,wiadomosc.html

**Comment by F4z** [comment]
Jeśli chodzi o wykrycie adblocka, to ta reguła powinna pomóc:
`@@/:\/\/.*[.]wp[.]pl\/[a-z0-9_]{10,50}[.][a-z]{2,5}[/:&?]?/`

A to powinno zablokować te reklamy:
`film.wp.pl##[style][class="qd-US"]`

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z Dzięki
