### ISSUE TITLE
uzdrowiska-pgu.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12940]
Social
![Opera Zdjęcie_2019-04-14_045249_uzdrowiska-pgu pl](https://user-images.githubusercontent.com/36385327/56087738-32e9a880-5e71-11e9-9bbd-ea554cc6a855.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 wrzucisz jakiegoś pulla ?

**Comment by hawkeye116477** [comment]
@MajkiIT Wrzucę po 16:00.
