### ISSUE TITLE
dobreprogramy.pl - logowanie dodatkowe widgety społecznościowe

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#12952]
Witam, tak jak w temacie. Czy można prosić o ukrycie przycisków logowania się przy pomocy portali społecznościowych na dobreprogramy.pl ?
![przyciski](https://user-images.githubusercontent.com/16944478/56196431-1b5c1c80-6037-11e9-8165-fa7e0b80c6bf.png)
Z góry dziękuję i pozdrawiam

**Comment by hawkeye116477** [comment]
Nie ukrywamy przycisków logowania socialami.

**Comment by krystian3w** [comment]
A nawet zamknąć. Fanboye też przywracają przyciski logowania po zgłoszeniu "błędu".

**Comment by seba2282** [comment]
A jaki to błąd był, że Fanboye odblokowują te przyciski? 😁

**Comment by krystian3w** [comment]
No niby może ktoś nie dać rady aktywować klasycznego logowania hasłem.

Już nie mówiąc o cudach jakie kiedyś lukjan wymyślił by mu na liście social odblokować przyciski udostępniania z AddThis.

**Comment by seba2282** [comment]
Teraz to żartujesz @krystian3w?

**Comment by krystian3w** [comment]
No niby ustawienie hasła może być problematyczne - trzeba użyć formularz resetowania hasła, potem zobaczyć jakie pola wymagają do potwierdzenia tożsamości - najgorzej jak się komuś udało założyć konto FB / Google by nie podawać maila i "pęczek profili" nie wymagał przy kolejnych łączeniach ustawienia maila.

**Comment by seba2282** [comment]
I takie rzeczy były zgłaszane do Fanboy'i ?
