### ISSUE TITLE
pokoleniesmart.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12960]
Ukrywa treść 
https://www.pokoleniesmart.pl/wentylator-zhimi-dc-w-sam-raz-na-letnie-upaly/
![Opera Zdjęcie_2019-04-16_174058_www pokoleniesmart pl](https://user-images.githubusercontent.com/36385327/56223864-dc49bd80-606e-11e9-81af-faf85154257d.png)

**Comment by krystian3w** [comment]
`pokoleniesmart.pl#@#.post-share-container`

czyli fanboy.
