### ISSUE TITLE
java programer 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1296]
potrzebujemy kogos z java hyba? co myslicie?

**Comment by MajkiIT** [comment]
przydałby się, ale masz kogoś?

**Comment by xxcriticxx** [comment]
nope ale poszukamy

**Comment by xxcriticxx** [comment]
maybe @Piter432?

**Comment by xxcriticxx** [comment]
@szymon1118 znasz sie troche na js?

**Comment by szymon1118** [comment]
@xxcriticxx No trochę ogarniam (pomogłem z TVN'em tym skryptem), a o co chodzi?

**Comment by xxcriticxx** [comment]
@szymon1118 bys wpadal tutaj od czasu do czasu szukamy takiej osoby jak ty
