### ISSUE TITLE
challengeme.gg

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#12970]
![Opera Zdjęcie_2019-04-17_135544_www challengeme gg](https://user-images.githubusercontent.com/36385327/56285921-a82ad700-6118-11e9-8dbc-b69458aaa521.png)

**Comment by krystian3w** [comment]
Twórcy nie umieją w webmastering?

**Comment by krystian3w** [comment]
No to niby do akceptacji w Polskiej Zgodzie Ciasteczkowej. Po akceptacji tło jest.

PS. "Stopka" ma linki społecznościowe.

**Comment by hawkeye116477** [comment]
@krystian3w Ale tło można przecież odblokować.

**Comment by krystian3w** [comment]
`##.text-right.media-links`.

Niby za mocna jakaś seciówka?

**Comment by krystian3w** [comment]
W sumie nie łobuzuje, całego internetu nie przeglądnie pod generyk ani kulą nie przewidzi kto przerobi w pop-up.

**Comment by hawkeye116477** [comment]
`nie przewidzi kto przerobi w pop-up.`
@krystian3w Ale ta reguła jest używana tylko do pop-upów :stuck_out_tongue:  Jeśli chodzi o kurtynę, to zawsze może przejrzeć `publicwww` w poszukiwaniu podobnych, by nieco ograniczyć błędy.
