### ISSUE TITLE
instalki.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1297]
nowe reklamy jako tło + zamaskowany link na instalkach (chyba js):
http://s000.tinyupload.com/index.php?file_id=25050275991333186007

@F4z @xxcriticxx 

Zerkniecie u siebie, bo ja mam pusto?

**Comment by F4z** [comment]
Ja nie widzę żadnych reklam.

**Comment by xxcriticxx** [comment]
ja niewiem czego szukam jakis screen shot please

**Comment by xxcriticxx** [comment]
@azet12 obczaj to instalki.pl @MajkiIT hyba jakis malware znalazl

**Comment by azet12** [comment]
Pusto.

**Comment by xxcriticxx** [comment]
Huawei pracuje nad zegarkiem z systemem Tizen_ - Instalki.pl_files.zip 

to @MajkiIT podal ale to jakis virus/malware

**Comment by azet12** [comment]
Nope, nic niebezpiecznego

**Comment by xxcriticxx** [comment]
Wiec czekamy na @MajkiIT

**Comment by MajkiIT** [comment]
Mi ktoś wrzucił komentarz na stronie. Przeleciałem to virus total i jest w miarę ok

https://www.virustotal.com/pl/file/97589a95d624e27432144989f47d0f85ace4ea8aae0fa2a480701012edda9c7b/analysis/1475215381/
