### ISSUE TITLE
nk.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#13]
Zagraj ze znajomymi w fajne gry

    Na ryby
    Na ryby
    Zarzuć wędkę z przyjaciółmi i we…
    World Holdem Club
    World Holdem Club
    Graj z przyjaciółmi i wysyłaj pr…
    Goodgame Empire
    Goodgame Empire
    Jeśli kiedyś marzyliście, by zos…
    Rycerze i księżniczki
    Rycerze i księżniczki
    Wejdź do cudownego świata rycerz…

**Comment by MajkiIT** [comment]
Chcesz aby zablokować te elementy? Dla mnie to typowe linki do gier online.

**Comment by xxcriticxx** [comment]
jest ok
