### ISSUE TITLE
lomianki.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13007]
![Opera Zdjęcie_2019-04-17_185855_www lomianki pl](https://user-images.githubusercontent.com/36385327/56306486-e3da9680-6142-11e9-8c95-6de370fcab48.png)

**Comment by krystian3w** [comment]
Jak coś to można sieciowo, klikalność to jakaś pętla wewnątrz strony:

`<div id="banner" onclick="location='index.php'"></div>`
