### ISSUE TITLE
ekorodzice.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#13012]
### Zrzut ekranu

![Screenshot_20190418_103249](https://user-images.githubusercontent.com/19818572/56347803-59874680-61c5-11e9-9785-f2072700cb7c.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Reklama Pstryczka i inne fajne reklamy :smile:

**Comment by krystian3w** [comment]
#`ekorodzicie`

**Comment by hawkeye116477** [comment]
@MajkiIT Nadal są reklamy, bo tutaj są ba**nn**ery, a nie banery :smile:
