### ISSUE TITLE
grudziadz.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13010]
![Opera Zdjęcie_2019-04-17_190051_grudziadz pl](https://user-images.githubusercontent.com/36385327/56306600-2e5c1300-6143-11e9-9f9e-e47c899ff50e.png)

**Comment by krystian3w** [comment]
`grudziadz.pl##.header_nav_items > li.header_nav_item:nth-of-type(7)`
