### ISSUE TITLE
facebook.com - broken ads manager

### ISSUE THREAD

**Issue by BlazDT** [MajkiIT/polish-ads-filter#13029]
https://www.facebook.com/adsmanager/

<img width="716" alt="fb-ad-manager" src="https://user-images.githubusercontent.com/34266271/56360634-8e0afa80-61e5-11e9-8909-b12bca097770.png">

Screenshot was created with rule excluded.

Problematic rule:
`##[id^="ads_"]`

Fix:
`facebook.com#@#[id^="ads_"]`
or just adding ~facebook.com to it

**Comment by MajkiIT** [comment]
@BlazDT Thanks
