### ISSUE TITLE
programtv.naziemna.info

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#13032]
https://programtv.naziemna.info/program/stacja/tvp1=2019-04-20
reklama " nan2 "

**Comment by MajkiIT** [comment]
Niestety nie mam tego.

**Comment by krystian3w** [comment]
Takie coś można spróbować dociąć:

```
programtv.naziemna.info#?#div.row > .my-padding-small.col-lg-12 > .panel-default.panel > .panel-body.panel:-abp-has(.adsbygoogle)
```

dwa puste pola po reklamach.

**Comment by hawkeye116477** [comment]
Tak będzie lepiej `programtv.naziemna.info#?#div.row > .my-padding-small.col-lg-12 > .panel-default.panel:-abp-has(.ads-label)`.
A tej reklamy to ja też nie mam.
