### ISSUE TITLE
chronpesel.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13033]
![Opera Zdjęcie_2019-04-18_233211_chronpesel pl](https://user-images.githubusercontent.com/36385327/56392645-4199dc00-6232-11e9-8bb4-7f67000b557b.png)

**Comment by krystian3w** [comment]
A to jak zablokowane, zaczynamy się bawić w AdGuard i Alexia Ranks (brak odwiedzających).
