### ISSUE TITLE
mmorpg.org.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1303]
Znowu adblock - `http://mmorpg.org.pl/`

Na przykład:
`@@||mmorpg.org.pl/expop.js$script`
lub:
`@@||mmorpg.org.pl/*.js$script`
ewentualnie:
`mmorpg.org.pl##div[id][style*="position: fixed"]`

**Comment by xxcriticxx** [comment]
duplicate z https://github.com/MajkiIT/polish-ads-filter/issues/1250

**Comment by F4z** [comment]
Zgadza się, zgłaszane było również i tutaj - https://github.com/MajkiIT/polish-ads-filter/issues/1204 ale wolałem otworzyć nowe żeby było bardziej widoczne, bo zmienili trochę sposób wykrycia adblocka.

**Comment by xxcriticxx** [comment]
fajnie ze jest rozwiazanie

**Comment by F4z** [comment]
Bardzo fajnie 😄

**Comment by xxcriticxx** [comment]
ok to do potem

**Comment by MajkiIT** [comment]
@F4z dzięki

**Comment by F4z** [comment]
@MajkiIT myślę, że można usunąć tę regułę `@@||mmorpg.org.pl/*.js$script`, bo teraz i tak nie działa.

Link - `http://mmorpg.org.pl/`

![image](https://cloud.githubusercontent.com/assets/11742596/19221798/9be0eef6-8e4a-11e6-9e40-33cf2ee78897.png)

Jeśli ktoś korzysta ze skryptu AAK, to nie powinien widzieć tego komunikatu.
Do uBlocka Origin można dodać tę regułę - `mmorpg.org.pl##script:inject(fuckadblock.js-3.2.0)`
Do Adblocka te dwie:
`@@||mmorpg.org.pl^$generichide`
`mmorpg.org.pl##.adsbygoogle`

**Comment by MajkiIT** [comment]
@F4z dzięki

**Comment by F4z** [comment]
Ta reguła `mmorpg.org.pl##script:inject(fuckadblock.js-3.2.0)` została dodana do filtrów uBlocka, więc jak ktoś korzysta z uBlocka, to nie powinien widzieć już tego komunikatu.
