### ISSUE TITLE
it-manuals.info

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#13047]
### Zrzut ekranu
![Screenshot_20190419_170315](https://user-images.githubusercontent.com/19818572/56429981-1a401f00-62c5-11e9-9dcf-73d747f80bd4.png)

### Link bezpośredni
`http://www.it-manuals.info/czarna-lista-zasilaczy-jakich-nie-kupowac.html`

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Reklama VPNa.

**Comment by MajkiIT** [comment]
`www.it-manuals.info###pum-822`

**Comment by hawkeye116477** [comment]
@MajkiIT A scroll?
