### ISSUE TITLE
centrum.fm

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13051]
![Zrzut ekranu z 2019-04-20 05-59-53](https://user-images.githubusercontent.com/36385327/56452513-b99afb80-6331-11e9-9c8e-aa4a8e1c6307.png)

**Comment by MajkiIT** [comment]
to życzenia

**Comment by hawkeye116477** [comment]
@krystian3w

**Comment by krystian3w** [comment]
Fanboy czy przypadkowo reklamowe filtry wycieły.

**Comment by krystian3w** [comment]
Życzenia na majówkę? Ja tego nie mam...

**Comment by krystian3w** [comment]
Na pocieszenie w AdGuard takie coś umie się przeterminować, bo zgłoszenie musi czekać z 2 tygodnie na przykład.

**Comment by hawkeye116477** [comment]
Pewnie raczej świąteczne były, a święta, święta były i po świętach, no to zdjęli w końcu :smile:
