### ISSUE TITLE
autocentrum.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1305]
Ta reguła - `##div[class*="cookie"]` - z ciasteczkowej listy ukrywa górną część strony - `http://www.autocentrum.pl/testy/ford-ranger-wildtrak-na-dzikiej-sciezce/`

Chodzi o to, co jest zaznaczone na czerwono.
![image](https://cloud.githubusercontent.com/assets/11742596/19003750/86db8cc2-8752-11e6-9cbb-c1861be6bafe.png)

**Comment by MajkiIT** [comment]
@F4z Dzięki
