### ISSUE TITLE
stooq.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1306]
Reklamy - `http://stooq.pl/` oraz `http://stooq.com/`

Na przykład:
`stooq.pl##[onclick*="http://stooq.pl/ads/f/"]`

`stooq.com##[onclick*="http://stooq.com/ads/f/"]`
`stooq.com##a[href^="ads/f/"]`

Można też ukryć to puste miejsce po reklamie:
`stooq.pl,stooq.com##table[border="0"][cellpadding="0"][cellspacing="0"]:not([width]):has([id="ads_goog_1"])`
Ta reguła jest dla obu stron, ale działa tylko w uBlocku/Adguardzie.

**Comment by MajkiIT** [comment]
@F4z Dzięki

**Comment by F4z** [comment]
@MajkiIT znowu są reklamy.
Żeby ukryć same reklamy można użyć na przykład tych reguł:
`stooq.pl,stooq.com##div[onclick^="(function"]`
`stooq.pl,stooq.com##a[href][target="_new"]`

Natomiast jeśli chodzi o pozostałości po reklamach i te napisy "REKLAMA", to można próbować ukryć je przy pomocy zwykłych reguł, ale ta strona jest tak zrobiona, że łatwo zablokować treść, która nie jest reklamą. Może znajdziesz sposób żeby ukryć to za pomocą zwykłych reguł i nie ukryć prawidłowej treści.

Zdecydowanie łatwiej można to zrobić przy użyciu reguł do uBlocka/Adguarda.
Żeby ukryć puste miejsce po reklamie dla obu:
`stooq.pl,stooq.com##table[border="0"][cellpadding="0"][cellspacing="0"]:not([width]):has([id="ads_goog_1"])`

Żeby ukryć te napisy "REKLAMA", na przykład:
uBlock: `stooq.pl,stooq.com##:xpath(//*[@align="center"]/*[@id][contains(text(),"REKLAMA")])`
Adguard: `stooq.pl,stooq.com##[align="center"] > [id]:contains(REKLAMA)`
