### ISSUE TITLE
ekorodzice.pl (2)

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#13072]
### Zrzut ekranu

![Screenshot_20190418_103249](https://user-images.githubusercontent.com/19818572/56347803-59874680-61c5-11e9-9785-f2072700cb7c.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Reklama Pstryczka i inne fajne reklamy :smile:
Otwieram ponownie, bo Prezes dodał błędną regułę i zamknął zgłoszenie. Napisałem potem, że nadal są reklamy, nawet w PR potem napisałem, żeby zrobił reopen, a on nic, `normalnie chamstwo w państwie` jakby to powiedział Ferdek...

**Comment by gaaargull** [comment]
> hawkeye116477 : (...) i zamknął zgłoszenie. Napisałem potem, że nadal są reklamy (...) a on nic (...)

Hahaha o ja nie mogę - już o to pytałeś, a ja odpisałem https://github.com/MajkiIT/polish-ads-filter/pull/12341#issuecomment-469418740, ale chyba nie dociera do ciebie, że on nie odpisuje w zamkniętych, ale tak ogólnie to bardziej chciałem teraz wstawić się za tobą:

> hawkeye116477 :
>
> Reklama Pstryczka i inne fajne reklamy
> Otwieram ponownie, bo Prezes dodał błędną regułę i zamknął zgłoszenie. Napisałem potem, że nadal są > reklamy, nawet w PR potem napisałem, żeby zrobił reopen, a on nic, `normalnie chamstwo w państwie` jakby to powiedział Ferdek...

Hahaha a niemówiłem, widzisz, ten typ tak ma, taką wyje.kę na innych, nawet gdy staniesz na głowie, to on nic, nie odzywa się wcale albo kiedy mu się podoba, człowiek może pczuć się totalnie olany, i tak było już gdy pierwszy raz się tu pojawiłem: https://github.com/MajkiIT/polish-ads-filter/issues/2064, stąd kłótnia i moja niechęć do tej persony, a teraz te same odczucia w stosunku do tej persony potwierdza najbliższy znajomy tej persony - sokoleoko116477,  więc coś musi być jednak na rzeczy, w zachowaniu tego typa i może jednak gomoku miał trochę racji.  Ten typ pewnie zaraz może odpisać, że nie zawsze ma czas odpisać, nie wszędzie zagląda, że jest zajęty, że nie na githubie świat się kończy, że robi za darmo, żę nikt mu nie będzie dyktował itp., ale tak przecież jest u każdego, i każdy robi za darmo, a jakoś ludzie potrafią znależć tę sekundę i odpisać kiedy trzeba, tylko nie on... a gdy kiedyś dopytywałem dlaczego tak robi to odpisał coś w stylu "jak coś nie pasuje to do widzenia"...przez to mam alegrię na tego typa i cieszy mnie, że ktoś inny też zaczyna ją mieć na niego. Tyle z mojej strony, nie chcę się kłócić, czy wyzywać, a jedynie potwierdzić pewną cechą u pewnego typa, którą stwierdził teraz nawet jego własny znajomy, więc chyba za pisanie prawdy bananów się nie dostaje. Bywajcie..

**Comment by hawkeye116477** [comment]
Jaki tam znajomy, nie znamy się osobiście. Z tym zamykaniem to już chyba drugi czy trzeci raz się zdarzyło. Możliwe, że to jednak przez brak czasu, ale wg mnie jeżeli coś napiszę w PR i on nie ma czasu przeczytać, to powinien zaczekać z akceptacją, a nie gonić jak lokomotywa.

**Comment by gaaargull** [comment]
> hawkeye116477 : Jaki tam znajomy, nie znamy się osobiście. 

Haha ale kontekstu nie wziąłeś pod uwagę, no przecież jesteśmy na githubie i piszemy o kwestiach githbuowych, więc chodziło mi o znajomego z githuba / githubowego, tacy co się znają na githubie, a nie po za nim. To tyle, nie chcę przeszkadzać w dyskusji, bo co miałem napisać napisałem. Znikam.

**Comment by MajkiIT** [comment]
@hawkeye116477 a to jakiś problem ? Odpisałem, że tego nie zrobię?

**Comment by hawkeye116477** [comment]
@MajkiIT Właśnie chodzi o to, że nic nie odpisałeś. A ja nie czytam też w myślach, więc nie wiem o co komu chodzi, dlatego mogłem to błędnie odczytać jako olanie sprawy.

**Comment by garggul** [comment]
Najpierw mój pierwszy skasowany komentarz:

> hawkeye116477 : (...) i zamknął zgłoszenie. Napisałem potem, że nadal są reklamy (...) a on nic (...)

Hahaha o ja nie mogę - już o to pytałeś, a ja odpisałem #12341 (comment), ale chyba nie dociera do ciebie, że on nie odpisuje w zamkniętych, ale tak ogólnie to bardziej chciałem teraz wstawić się za tobą:

> hawkeye116477 :
>
> Reklama Pstryczka i inne fajne reklamy
> Otwieram ponownie, bo Prezes dodał błędną regułę i zamknął zgłoszenie. Napisałem potem, że nadal są reklamy, nawet w PR potem napisałem, żeby zrobił reopen, a on nic, `normalnie chamstwo w państwi`e jakby to powiedział Ferdek...

Hahaha a niemówiłem, widzisz, ten typ tak ma, taką wyje.kę na innych, nawet gdy staniesz na głowie, to on nic, nie odzywa się wcale albo kiedy mu się podoba, człowiek może pczuć się totalnie olany, i tak było już gdy pierwszy raz się tu pojawiłem: #2064, stąd kłótnia i moja niechęć do tej persony, a teraz te same odczucia w stosunku do tej persony potwierdza najbliższy znajomy tej persony - sokoleoko116477, więc coś musi być jednak na rzeczy, w zachowaniu tego typa i może jednak gomoku miał trochę racji. Ten typ pewnie zaraz może odpisać, że nie zawsze ma czas odpisać, nie wszędzie zagląda, że jest zajęty, że nie na githubie świat się kończy, że robi za darmo, że nikt mu nie będzie dyktował itp., ale tak przecież jest u każdego, i każdy robi za darmo, a jakoś ludzie potrafią znależć tę sekundę i odpisać kiedy trzeba, tylko nie on... a gdy kiedyś dopytywałem dlaczego tak robi to odpisał coś w stylu "jak coś nie pasuje to do widzenia"...przez to mam alegrię na tego typa i cieszy mnie, że ktoś inny też zaczyna ją mieć na niego. Tyle z mojej strony, nie chcę się kłócić, czy wyzywać, a jedynie potwierdzić pewną cechą u pewnego typa, którą stwierdził teraz nawet jego własny znajomy, więc chyba za pisanie prawdy bananów się nie dostaje. Bywajcie..

**Comment by garggul** [comment]
A teraz mój drugi skasowany komentarz:

> hawkeye116477 : Jaki tam znajomy, nie znamy się osobiście.

Haha, jak widać nie załapałeś kontekstu, bo jestesmy na githubie i piszemy o kwestiach githubowych, jak coś to chodziło mi o znajomego z githuba / githubowego, a nie takiego w realu.

**Comment by garggul** [comment]
@hawkeye116477, @krystian3w i inni ...

Widzicie co ten psychol wyprawia...złośliwie pokasował moje 2 normalne komentarze + wlepił banana, pomimo, że w moich 2 komentarzach nie użyłem ani jednego wyzwiska czy zabronionego słowa, ani nie kłóciłem się, nie krzyczałem, a jedynie całkowicie spokojnie napisałem normalny komentarz tak jak ty, w którym ci przytaknąłem, że zgadzam się z tym co napisałeś i dodałem, że mnie też tak kiedyś traktował (i jak widać dalej traktuje, podobnie jak sokolego oka) i dlatego mam na niego alergię, jak widać tak go mocno prawda / krytyka zabolała, że aż szału dostał...

Skoro on i tak kasuje nawet normalne komentarze, w których nie ma wyzwisk i niczego złego, to już mi nie zależy, żeby pisać normalne komentarze bo on nawet takie kasuje, więc co za różnica, dlatego tym razem go nazwałem tak jak go nazwałem, zresztą jak widać po jego poczynaniach jest to słowo uzasadnione i chyba nikt temu nie zaprzeczy.

Skoro on nie zagląda do zamkniętych komentarzy, to może nie skasuje mi znowu tych komentarzy, tylko za to, że znowu o nim prawdę napisałem, no chyba, że ktoś z was jest konfidentem, albo ten typ z ciekawości prześledzi mój nowy nick i zajrzy nawet do zamkniętych komentarzy i znowu skasuje + wklepi banana po złości, ale to będzie świadczyć tylko i wyłącznie o nim i jego psychozie maniakalnej.

Ja tu ciężko pracuję jak wy i od dłuższego czasu nie wrzucam masowych zgłoszeń oraz zachowuję się, a ten typ taki mi się odwdzięcza za moją pomoc, że jednym machnięciem ręki kasuje mi komentarze i banuje, napisałem normalne komentarze, tak jak sokole oko, w których była tylko napisane, że nie jest taki święty, na jakiego wygląda, po co zaraz się awanturuje o nic, kasuje komentarze i wyrzuca/banuje kogoś z repozytorium, bo napisałem prawdę, delikatniej bo odstrzaszasz pracowników.
