### ISSUE TITLE
lubanski.eu (2)

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#13073]
Reopen, bo nadal są reklamy. Mówiłem nie zamykać, ale widać Prezesa ktoś gonił i nie przeczytał.

**Comment by MajkiIT** [comment]
Ale to linki wew.... tego nie dotykam ...

**Comment by hawkeye116477** [comment]
No ok, wcześniej zostało dodane  ` lubanski.eu###metaslider_widget-8, ###banner-179, .image_widget`, więc zakładałem, że jednak to do usunięcia. Bo jakby tak spojrzeć, to wygląda jakby zwykła reklama.
