### ISSUE TITLE
wylecz.to

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#13071]
klasa css zmieniona, może:

```
wylecz.to##div[class^="ad"] > div[style] > div[style]
```

Najwyżej sobie sami znów coś podmienią by wycinało za dużo.

**Comment by MajkiIT** [comment]
Ale nie widzę reklam ...

**Comment by hawkeye116477** [comment]
Ja widze 2 reklamy Preventic, ale to co @krystian3w to już nie działa.
![Screenshot_20190422_155917](https://user-images.githubusercontent.com/19818572/56504066-ab0e3900-6517-11e9-9bad-093bb9ff98cb.png)

**Comment by krystian3w** [comment]
No tak, ktoś zrobił zmianę z ad na coś `2b0d`.

**Comment by xxcriticxx** [comment]
@hawkeye116477 słyszałem ze tęsknisz za mną?

**Comment by krystian3w** [comment]
```
##div.col-md-3.col-sm-6.col-xs-12 > div[class] > div[style^="border-bottom: 20px"] > div[style]
```

Teraz takie coś.

**Comment by hawkeye116477** [comment]
@xxcriticxx No, bo mój przyjacielu, byłeś mi naprawdę bliski.... :smiley: I tak się zastanawiałem gdzie ty się podziewasz, mówię pewnie pije wino, pije aż do dna :smiley:

**Comment by xxcriticxx** [comment]
@hawkeye116477 teraz jestem ale znowu planuje wolne na początku maja

**Comment by hawkeye116477** [comment]
Rutinacea została jeszcze.

**Comment by garggul** [comment]
Jakieś reklamy wróciły, 3 reklamy: u góry , po prawej i na dole:

https://wylecz.to/laryngologia/co-robic-po-peknieciu-blony-bebenkowej/

![ss_002](https://user-images.githubusercontent.com/50133507/57194639-6e940180-6f49-11e9-8cb4-eb18728284a5.png)

![ss_004](https://user-images.githubusercontent.com/50133507/57194637-66d45d00-6f49-11e9-98f9-90d9bc79b22e.png)

**Comment by krystian3w** [comment]
Pytanie czy nie zrobią ataku na EasyList Polish a Ci nagle odpuszczą.

**Comment by krystian3w** [comment]
`##a[href^="/zze_click/"]:xpath(../..[div][@style])`

niby ładnie wycina, minus że AdamWr i ekipa muszą sobie inaczej tam docinać reklamy jak chcą.

**Comment by garggul** [comment]
Wycina ładnie, ale wolno, reklamy najpierw migną na pół sekundy / sekundę zanim znikną, jak wtedy: https://github.com/MajkiIT/polish-ads-filter/issues/7533#issuecomment-478963121.

**Comment by krystian3w** [comment]
Skrypt chyba odpada, nie ten typ reklam...


> na co on był, reklamy dalej są.

Zależy gdzie to miało wyciąć, ja o głównej hawkey o artykułach.

**Comment by garggul** [comment]
No miałem na mysli, że reklamy, które ja zgłosiłem dalej są, może to było na jakieś inne.

**Comment by garggul** [comment]
Niezależnie od filtrów kosmetycznych na kontenery z reklamami i napisami, to dodatkowo żeby reklamy nie migały zanim znikną, to taki regex do przetestowania na same reklamy:

Wersja dłuższa / bezpieczniejsza:
`/^htt(p|ps):\/\/wylecz\.to\/media\/filer_public_thumbnails\/filer_public\/[a-z0-9]{2}\/[a-z0-9]{2}\/[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}\/[a-zA-Z0-9]{8}\.(jpg|png|gif)$/$~third-party,image,domain=wylecz.to`

Wersja krótsza:
`/^htt(p|ps):\/\/wylecz\.to\/media\/filer_public_thumbnails\/filer_public\/[a-z0-9/-]+\/[a-zA-Z0-9]{8}\.(jpg|png|gif)$/$~third-party,image,domain=wylecz.to`
