### ISSUE TITLE
forum.dobreprogramy.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1307]
Puste miejsce po reklamie - `https://forum.dobreprogramy.pl/`
![image](https://cloud.githubusercontent.com/assets/11742596/19015954/9e93563a-880e-11e6-92f8-9fb96a2a432d.png)

Na przykład:
`forum.dobreprogramy.pl##[style="text-align:center;padding:0px 0px 15px 0px;"]`

**Comment by MajkiIT** [comment]
@F4z Dzięki
