### ISSUE TITLE
dniwolne.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#13079]
info o adblocku oraz cookies

**Comment by krystian3w** [comment]
```

                            <script type="text/javascript">
                                window.onload = function () {
                                    setTimeout(function () {
                                        if (typeof (window.google_jobrunner) === 'undefined') {
                                            alert('Prosimy o wyłączenie programów blokujących reklamy ...');
                                        }
                                    }, 3000);
                                };
                            </script>
```

Przerwać skryptem w uBO/Nano lub wypalać co z Google dopuścić.

**Comment by MajkiIT** [comment]
A nie masz tego nawet bez niczego ?

**Comment by krystian3w** [comment]
Wtedy nie ma.

**Comment by garggul** [comment]
> krystian3w: lub wypalać co z Google dopuścić.

Wybadałem:
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=dniwolne.eu`
`@@||pagead2.googlesyndication.com/pagead/js/r*/r*/show_ads_impl.js$script,domain=dniwolne.eu`

**Comment by krystian3w** [comment]
U mnie znowu by trzeba zgłaszać skargę na Generyki `adnauseam` lub ekstremalnie skompresowane EasyList  🇳🇴 autorstwa.

**Comment by krystian3w** [comment]
> widoczny kontener po reklamie z napisem reklama:
> powiększy się jeszcze bardziej:

No to na moje, nie da się go naprawić nie inaczej jak przerywając skrypt i wywalając resztkę - wtedy kod nie ma co wykryć i luki nie ma.

**Comment by krystian3w** [comment]
@MajkiIT  zostanie dodane jedno z dwóch?

https://github.com/MajkiIT/polish-ads-filter/issues/13079#issuecomment-485968851

wtedy dla uBO można i na liście suplementu `anty-adblock` dociąć "##.axv".
