### ISSUE TITLE
docer.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#13070]
Strona odzyla i ma kope reklam Xd

**Comment by krystian3w** [comment]
może nawet i koparkę...

```
||adk.docer.pl^
```

kiedyś działało, może teraz dziwne sztuczki z ponawianiem ładowania i stąd mam efekt koparki...

**Comment by krystian3w** [comment]
może nawet i koparkę...

```
||ad.docer.pl^
||adk.docer.pl^
||docer.pl/aserver/*
```

kiedyś działało (https://github.com/MajkiIT/polish-ads-filter/issues/6693#issuecomment-376416570, https://github.com/NanoAdblocker/NanoFilters/issues/51#issuecomment-376419164), może teraz dziwne sztuczki z ponawianiem ładowania i stąd mam efekt koparki...

**Comment by krystian3w** [comment]
* Niby trzecia blokuje najszybciej (4 blokady żądań sieciowy na 4), 
* potem pierwsza (4 blokady żądań sieciowy na 8), 
* a częściowo i "najwolniej blokuje ta druga *4 blokady żądań sieciowy na 12).

**Comment by krystian3w** [comment]
* niby trzecia blokuje najszybciej (4 blokady żądań sieciowych na 4), 
* potem pierwsza (4 blokady żądań sieciowych na 8), 
* a częściowo i "najwolniej blokuje ta druga (4 blokady żądań sieciowych na 12).

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję
@gzenio22 ale nie ma reklam :/

**Comment by gzenio22** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/21177361/56502867-1fdf7400-6514-11e9-98db-bc71ce543e08.png)


Jak nie ma jak sa

**Comment by hawkeye116477** [comment]
Nie ma reklam.
@gzenio22 Niech poda swój konfig, `screenfetch` z konsoli :smile:

**Comment by gzenio22** [comment]
@hawkeye116477 

https://gist.github.com/gzenio22/d40f71eb13894aabcbe87b2b46f5f8a9

**Comment by hawkeye116477** [comment]
@gzenio22 A OS i przeglądarka, W10 z ChrOperą?

**Comment by gzenio22** [comment]
zgadza sie

**Comment by hawkeye116477** [comment]
@gzenio22 No to na `58.0.3135.127` nic nie ma, ale na Linuksie, W10 nie posiadam, nawet moja płyta nie wspiera zresztą. Update do 60 nie robiłem jeszcze. A nową płytę za parę dni dopiero będę miał. A procesor, który masz to Ryzen 7 1700?

**Comment by krystian3w** [comment]
Ja i tak bym zablokował którąś z domen, nie skaczą wam w lewym rogu ładowania z serwerów niepowiązanych ze stroną?

**Comment by gzenio22** [comment]
@hawkeye116477 kurde faktycznie sorry za zamieszanie Zamykam
