### ISSUE TITLE
www.gazetapolska.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#131]
cookies

Nasza strona używa cookies czyli po polsku ciasteczek. Do czego są one potrzebne może Pan/i dowiedzieć się tu. Korzystając ze strony wyraża Pan/i zgodę na używanie ciasteczek (cookies), zgodnie z aktualnymi ustawieniami Pana/i przeglądarki. Jeśli chce Pan/i, może Pan/i zmienić ustawienia w swojej przeglądarce tak aby nie pobierała ona ciasteczek.

**Comment by xxcriticxx** [comment]
sub domains 

Strefa Wolnego Słowa: niezalezna.pl | www.gazetapolska.pl | www.panstwo.net | vod.gazetapolska.pl | naszeblogi.pl | gpcodziennie.pl

**Comment by MajkiIT** [comment]
Element statyczny.
