### ISSUE TITLE
meloradio.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#13113]
### Zrzut ekranu
<img src="https://user-images.githubusercontent.com/36385327/55514450-6b66d680-5668-11e9-9be1-fa01564f3ead.png">

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Brakuje 2 sekcji `Polecane` (jednej po prawej, a drugiej pod artykułem) i jednej  `Czytaj więcej`. Zapewne są blokowane dlatego, że są połączone z reklamami, tzn. trochę jest reklam, a trochę normalnych artykułów. Także raczej przydałoby się to jakoś elegancko naprawić. Mi się zdaje, że większość problemów powoduje lista Pete Lowe, ale polska chyba też. 
`www.meloradio.pl/Wiadomosci-muzyczne/Sprzedaz-muzyki-w-2018-roku-zdecydowanie-wzrosla`

**Comment by krystian3w** [comment]
No nie takie chop siup jednak z 43 dopuszczenia ruchu sieciowego a przeczytaj więcej nie odblokowałem.

W połowie wyszło że to też może blokować EasyPrivacy i przekierowania w uBO na czystą wersje skryptów Google.

**Comment by krystian3w** [comment]
```
@@||static-pl.plista.com^$script,domain=www.meloradio.pl
@@||farm-pl.plista.com^$script,domain=www.meloradio.pl
@@||static-pl.plista.com/image/*$image,domain=www.meloradio.pl
@@||static-pl.plista.com^$image,domain=www.meloradio.pl
@@||farm-pl.plista.com^$subdocument,domain=www.meloradio.pl
```

tyle by odblokować polecane boczne i dolne,

---

 a tego "przeczytaj więcej z Google Ads to nie dokopałem się:

```
www.meloradio.pl#@#.advert
www.meloradio.pl#@#.adsbygoogle
www.meloradio.pl#@#[id^="aswift_"]
@@||pagead2.googlesyndication.com^$script,domain=www.meloradio.pl
@@||adservice.google.com^$script,domain=www.meloradio.pl
@@||www.googletagmanager.com/gtm.js?id=GTM-NX5JXRN$script,domain=www.meloradio.pl
@@||www.google-analytics.com^$script,domain=www.meloradio.pl
@@||adservice.google.pl^$script,domain=www.meloradio.pl
@@||www.google-analytics.com^$image,domain=www.meloradio.pl
@@||doubleclick.net^$subdocument,domain=www.meloradio.pl
@@||doubleclick.net^$image,domain=doubleclick.net
@@||googlesyndication.com^$script,domain=doubleclick.net
```

Może jakiś skrypt jeszcze to blokuje.

**Comment by hawkeye116477** [comment]
No jest też opcja, że ten napis `przeczytaj więcej` wyciąć, a kto se będzie chciał to znajdzie na głównej to czego dusza potrzebuje...

**Comment by krystian3w** [comment]
```
@@||pl.plista.com^$image,script,subdocument,domain=meloradio.pl
meloradio.pl##div.container > .esi > .title-block
```

To takie coś po dużym uproszczeniu i coś nie bardzo mam pewność że wytnę tylko 1 tytuł.

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie tak szybko kowboju.

**Comment by krystian3w** [comment]
Było poprawić przy okazji gorącej poprawki?

**Comment by hawkeye116477** [comment]
A no tak, w sumie można było dodać. Ale @krystian3w miał jeszcze jakieś wątpliwości, więc uznałem, że lepiej będzie zaczekać, nie spieszyć się tak.

**Comment by krystian3w** [comment]
Te klasy CSS jakieś takie byle jakie a szkoda sięgać po `-abp-contains`.

I w sumie niby czasem ładuje się jeden z dwóch modułów `pl.plista.com` jak zbiłem wszystko w jedno.

**Comment by garggul** [comment]
sokoloeoko116477 jak coś jest nienaprawione to się w pierwszym komentarzu podaje link do poprzedniego zgłoszenia i tyle, a nie kradnie/przywłaszcza i wkleja czyjeś komentarze i pracę podpisując ją swoją ksywką:
- xMaap: https://github.com/MajkiIT/polish-ads-filter/issues/12748#issue-428984052
- hawkeye116477: https://github.com/MajkiIT/polish-ads-filter/issues/12748#issuecomment-480606302

**Comment by krystian3w** [comment]
No u mnie to nie zawsze dopuszczenie całego pl.lista ładuje te dwa pluginy. Google odblokuj sobie w filtrach własnych robiąc z 10 dopuszczeń sieciowo / kosmetycznych.
