### ISSUE TITLE
nba.com

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1311]
Ta reguła z ciasteczkowej listy - `/cookie.js$script` - "blokuje" jeden z elementów strony - `http://www.nba.com/`

![image](https://cloud.githubusercontent.com/assets/11742596/19022986/cf1953d8-88e3-11e6-9c8c-2a224aa2ea70.png)

Tam gdzie jest zaznaczone na czerwono powinny się wyświetlać wyniki meczów.

Na przykład:
`@@||www.nba.com/themes/custom/membership/js/lib/cookie.js$script`

**Comment by F4z** [comment]
@MajkiIT dzięki za aktualizację ciasteczkowej listy, ale chyba zapomniałeś dodać reguły dla tej strony, bo u mnie nadal nie wyświetlają się wyniki meczów.

**Comment by MajkiIT** [comment]
@F4z wybacz poprawiłem już. Przez przypadek pominąłem.

**Comment by F4z** [comment]
@MajkiIT nie ma problemu, dzięki.

Swoją drogą widzę, że dodałeś reguły dla uBlocka do głównej listy.
Ogólnie uważam, że to dobry pomysł, ale mam wrażenie, że po dodaniu tych reguł Adblock Plus zachowuje się dziwnie. Jakby część reguł nie działała.
Na przykład sprawdź na `wykop.pl` zostaje przestrzeń po reklamie i są sponsorowane treści.

![image](https://cloud.githubusercontent.com/assets/11742596/19222852/4268e2ee-8e62-11e6-8d4b-e944950275da.png)

Teoretycznie też komunikat o ciastkach powinien zostać ukryty, a nie jest.
Dodanie własnej reguły nie działa, na przykład żeby ukryć całą stronę wykopu - `wykop.pl##body`
Trzeba wyłączyć polską listę aby zaczęło działać. To tylko przykład, ale dzieje się tak na wszystkich stronach, których dotyczą te specjalne reguły dla uBlocka.

**Comment by MajkiIT** [comment]
@F4z usunąłem te filtry. Jutro rozkmnienię o co tu chodzi.

**Comment by F4z** [comment]
Ok, dzięki :)
