### ISSUE TITLE
tradee.com

### ISSUE THREAD

**Issue by BlazDT** [MajkiIT/polish-ads-filter#13128]
Pictures not shown due to this rule:

`~adaware.com,~mynet.com,~pistonheads.com,~hispasonic.com,~otodom.pl,~kbb.com,~wuxiaworld.com,~uzywane.com,~przegladsportowy.pl,~crunchyroll.com,~nationalgeographic.com,~wpolityce.pl,~box.com,~hardcorowo.pl,~gumtree.com,~hulu.com,com,~filmweb.pl,pl,~fakro.pl,~dziennikwschodni.pl,~schneiderpackaging.com,~vancourier.com,~galilu.pl,~uwaga.tvn.pl##[class^="ad-"]`

https://github.com/AdguardTeam/AdguardFilters/issues/32912

**Comment by MajkiIT** [comment]
@BlazDT thanks
