### ISSUE TITLE
goryiludzie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13124]
Reklama
![Opera Zdjęcie_2019-04-23_182157_goryiludzie pl](https://user-images.githubusercontent.com/36385327/56598447-cd29b900-65f4-11e9-86c3-309c8dff09ab.png)

**Comment by krystian3w** [comment]
U mnie się nie ładuje, daj do nich link, może chamsko pod częścią wpisów.

**Comment by xMaap** [comment]
Teraz się nie pokazuje. Reklama jest na stronie głównej.

**Comment by krystian3w** [comment]
`##.block-gilad.block`
`##a[href^="https://revive.goryiludzie.pl/www/dvr/aklik.php"]`

Raczej do filtrów własnych skoro nagle po 15 minutach znika.

**Comment by MajkiIT** [comment]
@krystian3w @xMaap Dziekuję
