### ISSUE TITLE
fotoblogia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13127]
Social. Trzeba się przegrzebać na środek strony.

![Opera Zdjęcie_2019-04-23_222152_fotoblogia pl](https://user-images.githubusercontent.com/36385327/56613116-4b4a8780-6616-11e9-96be-808853c09da0.png)

**Comment by hawkeye116477** [comment]
Coraz to zmyślniej...

**Comment by krystian3w** [comment]
Fitnes WP też ma:

![obraz](https://user-images.githubusercontent.com/35370833/56620011-c36d7900-6627-11e9-9a32-fda6a8b2a506.png) |
--- |

**Comment by krystian3w** [comment]
```
##.grid-item__social.grid-item:style(visibility: hidden !important; display: block !important; padding-top: 0 !important;)
```

Najlepsze by nie psuć jak coś się wciśnie w środek lub z boków, bo leci na lewo.
