### ISSUE TITLE
konsoleigry.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1312]
Ta reguła - `##[class^="adv-"]` - ukrywa element na dole strony - `http://konsoleigry.pl/`

Z regułą:
![image](https://cloud.githubusercontent.com/assets/11742596/19037642/96f99744-8977-11e6-9822-051190feb8c9.png)

Bez reguły:
![image](https://cloud.githubusercontent.com/assets/11742596/19037658/b079f81c-8977-11e6-9344-eaf562a00269.png)

**Comment by MajkiIT** [comment]
@F4z Dzięki

**Comment by F4z** [comment]
@MajkiIT chyba przez pomyłkę nie tu gdzie trzeba dodałeś stronę do wykluczeń.
`~konsoleigry.pl,~thenextweb.com,~pcgamingwiki.com,~gamepedia.com,~mega.nz##[class$="-ads"]`

A powinno być tutaj:
`~megadyskont.pl##[class^="adv-"]`

**Comment by MajkiIT** [comment]
:( Zgadza się dzięki
