### ISSUE TITLE
wamiz.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13134]
![Opera Zdjęcie_2019-04-25_141421_wamiz pl](https://user-images.githubusercontent.com/36385327/56734973-8e1a7580-6764-11e9-87bf-310e84600d80.png)
![Opera Zdjęcie_2019-04-25_141432_wamiz pl](https://user-images.githubusercontent.com/36385327/56734974-8e1a7580-6764-11e9-9546-8bdad0546c59.png)
![Opera Zdjęcie_2019-04-25_141446_wamiz pl](https://user-images.githubusercontent.com/36385327/56734976-8eb30c00-6764-11e9-932e-ad9562f3b59e.png)

**Comment by krystian3w** [comment]
Więcej testów @xxcriticxx  ten blur to nie błąd a efekt normalny otwarcia menu bocznego 🤣
