### ISSUE TITLE
wakacje.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13133]
![Opera Zdjęcie_2019-04-25_002042_www wakacje pl](https://user-images.githubusercontent.com/36385327/56697803-114db400-66f0-11e9-90d5-3fe0d3401250.png)

**Comment by krystian3w** [comment]
@hawkeye116477  / @blocker999  jak potencjalnie dociąć schowek czy może zostaje...

**Comment by hawkeye116477** [comment]
Schowek teoretycznie w EI, ale czy się komuś przyda, to nie wiem.

**Comment by krystian3w** [comment]
Teoretycznie, ale niby EI nie wymaga na siłę blokowania social albo o czymś nie wiem, bo tak zostaje dziura i wykrywać mam że elementy są wszystkie ukryte?

**Comment by krystian3w** [comment]
To tak zniknie dziura w uBO / AdGuard jak się ma pełne EI lub dwa moduły  (feedback + other elements) i aktywny filtr Social.

**Comment by krystian3w** [comment]
Te wakacje pl to się chyba `ze`­`sz`­`ma`­`ci`­`ły` - żaden stary filtr już nie działa, randomizacja jak na WP.

**Comment by hawkeye116477** [comment]
`Teoretycznie, ale niby EI nie wymaga na siłę blokowania social `
Ale schowek to już inna sprawa.

**Comment by krystian3w** [comment]
> Ale schowek to nie social, schowek to schowek

Wytnij wszystkie 3 i robi się przywieszony pusty prostokącik z cieniem.
