### ISSUE TITLE
cda-online

### ISSUE THREAD

**Issue by rigis1** [MajkiIT/polish-ads-filter#1313]
![o](http://i.imgur.com/Yo7IKMZ.png)

**Comment by MajkiIT** [comment]
podasz link?

**Comment by xxcriticxx** [comment]
https://cda-online.pl/bog-umarl-2/

**Comment by xxcriticxx** [comment]
ja nic tam nie widze umnie caly czas tylko sie kreci

**Comment by xxcriticxx** [comment]
https://camo.githubusercontent.com/b74c6d54e4aac711723a4e0aa3f69c66e01526ec/687474703a2f2f692e696d6775722e636f6d2f596f37494b4d5a2e706e67

**Comment by MajkiIT** [comment]
@xxcriticxx u mnie jest ok.

**Comment by xxcriticxx** [comment]
umnie zaladowalo ale caly czas bufferuje

**Comment by MajkiIT** [comment]
już mam ... na adblocku jest błąd.

**Comment by xxcriticxx** [comment]
OK SUPER

**Comment by MajkiIT** [comment]
@rigis1 dodaj sobie AAK scripts https://github.com/reek/anti-adblock-killer
