### ISSUE TITLE
legalniewsieci.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#13144]
`legalniewsieci.pl##A > IMG:last-child`

---

źle wycina reklamy, o wiele za dużo, trzeba przerobić.

```
https://www.legalniewsieci.pl
```

https://github.com/PolishFiltersTeam/KAD/issues/884#issuecomment-486734628

**Comment by hawkeye116477** [comment]
Ale tam nie ma reklam...
