### ISSUE TITLE
stooq.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1316]
@MajkiIT znowu są reklamy.
Żeby ukryć same reklamy można użyć na przykład tych reguł:
`stooq.pl,stooq.com##div[onclick^="(function"]`
`stooq.pl,stooq.com##a[href][target="_new"]`

Natomiast jeśli chodzi o pozostałości po reklamach i te napisy "REKLAMA", to można próbować ukryć je przy pomocy zwykłych reguł, ale ta strona jest tak zrobiona, że łatwo zablokować treść, która nie jest reklamą. Może uda znaleźć Ci się sposób żeby ukryć to za pomocą zwykłych reguł i nie ukryć prawidłowej treści.

Zdecydowanie łatwiej można to zrobić przy użyciu reguł do uBlocka/Adguarda.
Żeby ukryć puste miejsce po reklamie dla obu:
`stooq.pl,stooq.com##table[border="0"][cellpadding="0"][cellspacing="0"]:not([width]):has([id="ads_goog_1"])`

Żeby ukryć te napisy "REKLAMA", na przykład:
uBlock: `stooq.pl,stooq.com##:xpath(//*[@align="center"]/*[@id][contains(text(),"REKLAMA")])`
Adguard: `stooq.pl,stooq.com##[align="center"] > [id]:contains(REKLAMA)`

**Comment by MajkiIT** [comment]
Dzięki coś popatrzę

**Comment by xxcriticxx** [comment]
element picker ale slowo REKLAMA dalej zostaje

`stooq.pl##table > tbody > tr:nth-of-type(2) > td > table > tbody > tr > td > table > tbody > tr > td > table:nth-of-type(6) > tbody > tr > td:nth-of-type(3) > table > tbody > tr > td:nth-of-type(1) > table:nth-of-type(1) > tbody > tr > td > div`
`stooq.pl##table > tbody > tr:nth-of-type(2) > td > table > tbody > tr > td > table > tbody > tr > td > table:nth-of-type(5) > tbody > tr > td > table > tbody > tr > td:nth-of-type(2) > table > tbody > tr > td > div`

**Comment by xxcriticxx** [comment]
@F4z napisz do gorhill moze cos cos wymyslimy

**Comment by F4z** [comment]
Ale ja ukryłem te napisy "reklama" przy użyciu reguł do uBlocka.

**Comment by xxcriticxx** [comment]
sorry nie doczytalem

**Comment by F4z** [comment]
Nie ma problemu :)

**Comment by xxcriticxx** [comment]
`stooq.pl##div[onclick*="window.open('http://stooq.pl/ads/"]`

**Comment by F4z** [comment]
@MajkiIT znowu zmienili, teraz dodane reguły ukrywają stronę całkowicie. 😃
Trzeba usunąć tę regułę - `stooq.pl,stooq.com##div[onclick^="(function"]`
i dodać na przykład taką - `stooq.pl,stooq.com##div[onclick^="(function"][onclick*="window.open"][style^="animation"]`
oraz taką - `stooq.pl,stooq.com##[id] > b > a[href^="?"]`

**Comment by xxcriticxx** [comment]
@F4z twoja nowa ulubiona strona

**Comment by xxcriticxx** [comment]
lol

Zero reklam w serwisie Stooq

Cennik*

25 zł / 3 miesiące
50 zł / 6 miesięcy
75 zł / 9 miesięcy
100 zł / 1 rok

**Comment by xxcriticxx** [comment]
@F4z `REKLAMA`  dalej zostaje

**Comment by F4z** [comment]
U mnie jest tak, że teraz cała strona jest ukryta. Muszę dodać tę regułę żeby się wyświetlała:
`stooq.pl,stooq.com#@#div[onclick^="(function"]`

Te dwie reguły żeby ukryć reklamy:
`stooq.pl,stooq.com##div[onclick^="(function"][onclick*="window.open"][style^="animation"]`
`stooq.pl,stooq.com##[id] > b > a[href^="?"]`

Żeby pozbyć się napisu "REKLAMA" tę regułę:
`stooq.pl,stooq.com##:xpath(//*[@align="center"]/*[@id][contains(text(),"REKLAMA")])`

I żeby pozbyć się pustego miejsca po reklamach tę:
`stooq.pl,stooq.com##table[border="0"][cellpadding="0"][cellspacing="0"]:not([width]):has([id="ads_goog_1"])`

**Comment by xxcriticxx** [comment]
slowo REKLAMA pokazalo sie ale zniklo 

dobra robota buddy

**Comment by MajkiIT** [comment]
@F4z dodane dziekuje

**Comment by F4z** [comment]
@MajkiIT dzięki za aktualizację filtrów, ale te dwie reguły:
`stooq.pl,stooq.com##:xpath(//*[@align="center"]/*[@id][contains(text(),"REKLAMA")])`
`stooq.pl,stooq.com##table[border="0"][cellpadding="0"][cellspacing="0"]:not([width]):has([id="ads_goog_1"])`
powinny zostać dodane tylko do tej specjalnej listy dla uBlocka, bo w Adblocku mogą sprawiać problemy.

**Comment by MajkiIT** [comment]
Chcę aby w głównych filtrach były równiez filtry typowo do ublocka. Testuje na Adbloku i jest ok.

**Comment by F4z** [comment]
Myślałem, że będą jakieś problemy przez to, ale jak jest ok, to spoko. 
Dzięki za odpowiedź.
