### ISSUE TITLE
allcaster.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#13170]
Panowie jest sprawa To jedyna strona na ktorej są odcinki cobry ale ktores z filtrow calkowicie wycinaja player 

Jest tam kupa reklam ogolem ale dali byscie rade odratowac player z serialami? :D

**Comment by xxcriticxx** [comment]
@gzenio22 linky sa z freedisc.pl podaj jakis link do odcinku co nie dziala 

@MajkiIT regex potrzebny pod play jest shit podpiety

![Capture](https://user-images.githubusercontent.com/15007183/56849403-c7b4c300-68c1-11e9-9474-a655ca0710ca.PNG)

**Comment by gzenio22** [comment]
@xxcriticxx one dzialaja tylko przed startem  odc kilka razy okno przeskakuje na nowa karte

**Comment by xxcriticxx** [comment]
@gzenio22 napisales ze player wycina

**Comment by gzenio22** [comment]
juz ci pokazuje o co B

![Screenshot_1](https://user-images.githubusercontent.com/21177361/56850085-9ce86000-68fd-11e9-8232-d4f5868701e1.png)

**Comment by xxcriticxx** [comment]
@gzenio22 na temp fix wylacz blocker opery i czekamy jak @MajkiIT regex poprawi

**Comment by gzenio22** [comment]
@xxcriticxx ale ja bloker opery mam na off Xd

**Comment by xxcriticxx** [comment]
@gzenio22 to jakas lista host blokuje. na ubo sie otwiera nowa karta ale jest przyblokowana przez ubo

**Comment by MajkiIT** [comment]
@gzenio22 @xxcriticxx Testujemy 
https://github.com/MajkiIT/polish-ads-filter/commit/6e9a137d36a1c490156880491462577490a976d2#diff-711027ed0794992ae3b8710d874f3df7

**Comment by xxcriticxx** [comment]
![Capture](https://user-images.githubusercontent.com/15007183/56852791-7ae6e180-68ed-11e9-8c14-09b16c837d6a.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx wersja 2019042702 ?

**Comment by xxcriticxx** [comment]
@MajkiIT yes sir v.2019042702 aktualizacja: sob, 27 kwietnia 2019, 18:55:00

**Comment by MajkiIT** [comment]
@xxcriticxx za każdym razem masz popup ?

**Comment by xxcriticxx** [comment]
@MajkiIT nope tylko za pierwszym razem na swierzym ciastku jest podlonczony pod guzik play

**Comment by MajkiIT** [comment]
Zaktualizuj proszę do 2019042703 i sprawdź

**Comment by xxcriticxx** [comment]
@MajkiIT dziala od czasu do czasu sie pokazuje captcha
![Capture](https://user-images.githubusercontent.com/15007183/56853961-09169400-68fd-11e9-868f-e30ea391c29c.PNG)

**Comment by xxcriticxx** [comment]
@gzenio22 potwierdzasz?

**Comment by gzenio22** [comment]
Tak smiga a captha juz chyba nie przeskoczymy :D

**Comment by gzenio22** [comment]
zamykam
