### ISSUE TITLE
rosebelle.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#13172]
cookies

**Comment by krystian3w** [comment]
Wersja EU się nie otwiera, potrzebny link bezpośredni jak otwarłeś wersje EU bez przekierowania na PL.

**Comment by xxcriticxx** [comment]
https://rosebelle.pl/

ale nie widze tam cookies

**Comment by krystian3w** [comment]
No właśnie, jakby w "3 godziny" rebranding z polską domeną.
