### ISSUE TITLE
H&M

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#13185]
Jakiś problem z suwakiem poziomym, jakby po RODO?

```
https://www2.hm.com/pl_pl/index.html#modal-2
```

**Comment by MajkiIT** [comment]
https://www.screencast.com/t/v7n7CLlyi

**Comment by krystian3w** [comment]
No niby tak, ale zmniejsz sobie okno jak masz monitor full hd i taki filtr:

`##.takeover-wrapper.responsive.modaloverlay`

i taki efekt:

> ![obraz](https://user-images.githubusercontent.com/35370833/56909832-5c2d4a00-6aa9-11e9-9911-a3660ff84601.png) |
> --- |
