### ISSUE TITLE
next.gazeta.pl - adblock detect

### ISSUE THREAD

**Issue by Isamaul** [MajkiIT/polish-ads-filter#1318]
Reguła:
next.gazeta.pl##.uzr_adblock_articles.adb_port

Powinna wystarczyć
![image](https://cloud.githubusercontent.com/assets/20810329/19124173/61254368-8b32-11e6-809f-d99cf92bb321.png)

**Comment by xxcriticxx** [comment]
@Isamaul podaj link gdzie jest ten adblock please

**Comment by Isamaul** [comment]
@xxcriticxx 
http://next.gazeta.pl/next/7,151003,20792715,zarabiasz-6-tys-zl-na-reke-minister-kowalczyk-zapowiada-dla.html#MT2

Proszę

**Comment by xxcriticxx** [comment]
@Isamaul umnie dziala bez problemu

dodaj sobie projekt reeka https://github.com/reek/anti-adblock-killer
