### ISSUE TITLE
siemianowice.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#13188]

**Comment by krystian3w** [comment]
@gwarser, można by nazwać bugiem, że element picker mi podmienia background na wersje uproszczoną w hex bez innych wartości z takiej: `background: rgb(30, 42, 75) none repeat scroll 0% 0%;`?

**Comment by gwarser** [comment]
Heh. Dobrze widzę? Jak się ukryje element za pomocą podglądu, to atrybut style się reformatuje? Pisz buga.

**Comment by krystian3w** [comment]
Trochę za trudne, znów z 30 minut będą pytać o czym ja piszę...

**Comment by krystian3w** [comment]
Albo lepiej zalecą detekcje "X" lub słowa "cookies" i jeszcze najlepiej z xpath...

**Comment by gwarser** [comment]
Idzie ci coraz lepiej :D
