### ISSUE TITLE
teledyski.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#13186]
ad block 
test link:
http://mp3.teledyski.info/link/?id=NHFKS1lBYTZuZUhXcUwyZTdHUVhSRndWT3lSZTRDd1RjeEV2WXpSQnBiWjJZa3BZWjNaalIyeHRNRzVCYm5rMlJrVmxNaXRQWjNkeWRURjVNWFZGU2xOWFZURktPVEoxUWxscFZtMXNkWHB4YVRoSWJtaGFjVkJxVm5seFNUaEc=

![Capture](https://user-images.githubusercontent.com/15007183/56936769-12ebf300-6ac7-11e9-9f23-230af1f5b38a.PNG)

cookies 

Serwis internetowy, z którego korzystasz, używa plików cookies. Są to pliki instalowane w urządzeniach końcowych osób korzystających z serwisu, w celu administrowania serwisem, poprawy jakości świadczonych usług w tym dostosowania treści serwisu do preferencji użytkownika, utrzymania sesji użytkownika oraz dla celów statystycznych i targetowania behawioralnego reklamy (dostosowania treści reklamy do Twoich indywidualnych potrzeb). Informujemy, że istnieje możliwość określenia przez użytkownika serwisu warunków przechowywania lub uzyskiwania dostępu do informacji zawartych w plikach cookies za pomocą ustawień przeglądarki lub konfiguracji usługi. Szczegółowe informacje na ten temat dostępne są u producenta przeglądarki, u dostawcy usługi dostępu do Internetu oraz w Polityce prywatności plików cookies.

**Comment by krystian3w** [comment]
Nano Defender nie pomaga / nie błąd na poziomie PiHole?

**Comment by krystian3w** [comment]
```
@@/show_ads.js$script,domain=mp3.teledyski.info
```

**Comment by xxcriticxx** [comment]
@krystian3w dziala thanks

**Comment by krystian3w** [comment]
A co na to PiHole trzeba domeny wykluczać z filtrowania i zdawać się na uBO?

**Comment by krystian3w** [comment]
PS. zmienna atrybutu tu mnie nie przekonuje by iść z duchem czasu i sięgać po np. `set-constant.js`:

> 
> ```
> var GFSJHGSYUNNBSDYOOWJHSGI=true;
> ```

**Comment by krystian3w** [comment]
@bogachenko https://github.com/MajkiIT/polish-ads-filter/issues/13186#issuecomment-487899084

no I cannot found better solution, `set-constant` maybe need still update  randomize varible.

**Comment by xxcriticxx** [comment]
@krystian3w ten problem to nie z piholem

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/16407 https://github.com/MajkiIT/polish-ads-filter/issues/13186 https://github.com/MajkiIT/polish-ads-filter/issues/20293
