### ISSUE TITLE
plasterlodzki.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#13197]
fb ( u góry obok logo )

**Comment by krystian3w** [comment]
Nie mam, bug Vivaldi / uBO?

lub hawkey wyciął już na dev z minimum 4 godziny temu.

**Comment by krystian3w** [comment]
Dobra raczej bug uBO:

![obraz](https://user-images.githubusercontent.com/35370833/57032820-8880cc00-6c4b-11e9-86f5-4c3de7b87ccf.png)
