### ISSUE TITLE
rodzinnywyjazd.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#13194]
https://rodzinnywyjazd.pl/tu-mi-wolno

jakiś anty-adblock:

`rodzinnywyjazd.pl###window-container` - niby będzie "OK".

Bo sami robią identycznie:

> 
> ```js
> document.getElementById('window-container').remove();
> ```

**Comment by krystian3w** [comment]
Albo trzeba dopuścić gadzinę:

```
@@||rodzinnywyjazd.pl/gads.js$script
```

**Comment by krystian3w** [comment]
@bogachenko you have other idea?

**Comment by bogachenko** [comment]
No. But they are not needed. After all, your options work @krystian3w
