### ISSUE TITLE
account.microsoft.com

### ISSUE THREAD

**Issue by BlazDT** [MajkiIT/polish-ads-filter#13191]
https://account.microsoft.com/privacy/ad-settings

Rule `[class^="ad-"]` is breaking site (no "See ads that interest you" and other options there).

Broken:
<img width="710" alt="microsoft-account" src="https://user-images.githubusercontent.com/34266271/56944897-773d9f80-6b25-11e9-9db5-cec164479954.png">

Rule whitelisted for this domain:
<img width="776" alt="microsoft-account2" src="https://user-images.githubusercontent.com/34266271/56944944-a7853e00-6b25-11e9-9774-3eee0b2a9e81.png">

**Comment by krystian3w** [comment]
Why FAZ stop fix this bugs?

**Comment by MajkiIT** [comment]
@BlazDT Thanks
