### ISSUE TITLE
www.polskaniepodlegla.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#132]
cookies

Korzystanie ze strony polskaniepodlegla.pl jest jednoznaczym wyrażeniem zgody na wykorzystanie ciasteczk portalu oraz podmiotów współpracujących do prawidłowego działania strony
(ciasteczka sesyjne, wtyczki społecznościowe, google analytics i reklamowe). Więcej informacji jak wyłączyć ciasteczek na stronie.

**Comment by MajkiIT** [comment]
element statyczny
