### ISSUE TITLE
psy-pies.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13207]
![Opera Zdjęcie_2019-05-01_131738_psy-pies com](https://user-images.githubusercontent.com/36385327/57015152-8ac73400-6c13-11e9-89f0-fbc6affb4e89.png)

**Comment by garggul** [comment]
Bruźdi filtr w POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda,
pomaga jego wyłączenie `psy-pies.com#@#.appear.no-display.img-responsive` albo usunięcie.
