### ISSUE TITLE
nwloclawek.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#13202]
info o adblocku

**Comment by garggul** [comment]
Wrzucam screenshoota dla jasności:

![ss_003](https://user-images.githubusercontent.com/50133507/57014548-e47a2f00-6c10-11e9-8a39-a5fe45878a9f.png)


Antidotum `@@||imgcdn.nwloclawek.pl/static/js/ads.js$script,~third-party` lub wziąć bardziej ogólną wersję filtra z jednej z list, po których włączeniu anty-adblock również znika:
- AdGuard Base List (`@@/js/ads.js|$first-party,script,domain=~internethaber.com`)
- Fanboy’s Enhanced Tracking List ( `@@/js/ads.js$script`)
