### ISSUE TITLE
upflix.pl

### ISSUE THREAD

**Issue by garggul** [MajkiIT/polish-ads-filter#13208]
Anty-adblock np. https://upflix.pl/serial/zobacz/the-legend-of-korra-2011:

![ss_006](https://user-images.githubusercontent.com/50133507/57033668-ce3e9400-6c4d-11e9-9729-37fd479f4ad2.png)

Brużdżą 2 filtry/listy:

1 https://github.com/MajkiIT/polish-ads-filter/blob/fb4ffb96eb9f594851d878945fb6e104ae0b497a/polish-adblock-filters/adblock.txt#L105
2 

https://github.com/easylist/easylist/blob/6e16e999905aea82628193ecb0e0102cad7decc4/easylist/easylist_general_hide.txt#L17306

Na ten z EasyList będzie: `upflix.pl#@#.reklama`
Na ten z Polskiej Listy: wywalić `upflix.pl` z filtra albo `upflix.pl#@#[class*="reklama"]`

**Comment by krystian3w** [comment]
Albo olać wyjątkowanie i czekać aż przebudują bar:

```
##body > #mc > .container > .row > .col > div[style]
```

**Comment by krystian3w** [comment]
Z nudy można przerwać funkcje:

```js
adBlock = function() {
    if ($('#mc .c').length && $('.ad.banner').length && !$('.ad.banner:visible').length) {
        $('#mc .c').before('<div class="container"><div class="row"><div class="col"><div ' + 'style="' + 'width: 100%;' + 'margin-bottom: 40px;' + 'padding: 1rem !important;' + 'color: #0c5460;' + 'background-color: #d1ecf1; text-align: center;' + 'border-radius: 3px; border: 1px #bee5eb;"' + '>Nie mamy agresywnych reklam. Z gĂłry dziÄki za wyĹÄczenie AdBlocka! :)</div></div></div></div>')
    }
};
updateTypeControlClass = function() {
    control_type.removeClass('active');
    if (control_type.data('value') && control_type.data('value').trim().length) {
        control_type.addClass('active');
    }
};
sticky = function() {
    var adContainer = $('#video-ad-container > div');
    if (adContainer.length) {
        adContainer.stick_in_parent({
            recalc_every: 1,
            parent: '.col-video-1',
            spacer: '#video-ad-container'
        });
    }
};;
```
