### ISSUE TITLE
gra.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#13218]
adblock detect

**Comment by garggul** [comment]
Tak informacyjnie podaję zrzut ekranu oraz link, bo jemu sie nie chciało:

https://gra.pl/playstation-5-moze-byc-drozsze-niz-przewidywano-playstation-5-cena/ar/c12-14079625

![ss_005](https://user-images.githubusercontent.com/50133507/57099725-6d7e8c80-6d1d-11e9-9944-74aa5a72e5a2.png)

</details>

Anty-adblock znika po włączeniu listy AdGuard Base List, dzięki takiemu filtrowi:
`​@@||tools.services.tvn.pl/_ads/advert.js`

**Comment by xxcriticxx** [comment]
@MajkiIT / @olegwukr  bedzie jakis update do listy anti-adblock soon?

**Comment by krystian3w** [comment]
może kiedyś, jak skończą majówkę.

**Comment by krystian3w** [comment]
ten wystarczy dopisać do wyjątków i skryptów pod Press Polska.

**Comment by MajkiIT** [comment]
@xxcriticxx za kilka godzin powinna być.
@krystian3w a co ty taki sceptyczny ?

**Comment by xxcriticxx** [comment]
@MajkiIT sorry zapomniałem ze u was holiday

**Comment by krystian3w** [comment]
Tylko zróbcie by w uBO działał skrypt `set-constant` i `reddirect=noopjs`, bo to ma potencjał jak Press Polska nie umie bawić się w kotka i myszkę.

**Comment by garggul** [comment]
Kwestia taka, gdzie w końcu zamieszczać te zgłoszenia anty-adblock, bo jak widać jest bałagan - jedne zgłoszenia są zgłaszane tu, a inne na innym repo. A bałagan jest związany z tym, że w jednym miejscu, czyli na [blogu poslkich filtrów](https://www.certyficate.it/polskie-filtry-anti-adblock-brak-wsparcia-w-polskich-filtrach-szanowni-nasi-drodzy-od-07-12-2018-nastapia-zmiany-w-oficjalnych-polskich-filtrach/) zostało napisane żeby zgłaszać na tym repo:

> Jedynie o co możemy Was prosić to, nadal zamieszczanie w [naszym repo](https://github.com/MajkiIT/polish-ads-filter/issues) informacji o stronach gdzie wyświetlany jest alert o Adblocku, lecz nie my będziemy to wspierać.

A 3 dni później na [stronie polskich filtrów](https://github.com/MajkiIT/polish-ads-filter#polish-filters-for-adblock-ublock-origin--adguard) zostało napisane żeby zgłaszać innym repo:

> [Zgłoś](https://github.com/olegwukr/polish-privacy-filters/issues)

Czy pomyłka jest na blogu polskich filtrów czy na stronie polskich filtrów...należy poprawić błąd, żeby nie robić bałaganu i zamieszania.

**Comment by xxcriticxx** [comment]
@garggul naprawimy ten error thanks za info

**Comment by krystian3w** [comment]
Ja wrzucam do Olga jak tu zamkną i oleją propozycje, i mi zależy by może jednak naprawić problem - wtedy widzi i jak mi zamknie wątek bez PR to olewam.

**Comment by krystian3w** [comment]
Po części dużo też miesza nam Mati - "niby masz zgłaszać na dev problemy z cookies / social", ale niby czemu?
