### ISSUE TITLE
jsbeautifier.org

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1323]
Ta reguła - `/jquery.cookie.js$script` - z ostatniej aktualizacji ciasteczkowej listy psuje działanie strony.
Link - `http://jsbeautifier.org/`

**Comment by F4z** [comment]
Ta sama reguła blokuje możliwość oglądania filmów tutaj - `http://shinden.pl/external-video/970-dragon-ball-z/view/15410`
Po kliknięciu w przycisk "Pokaż" nic się nie dzieje.

**Comment by F4z** [comment]
Przez tę samą regułę nie wyświetlają się komentarze na rmf24.pl
Link - `http://www.rmf24.pl/fakty/news-legia-warszawa-zagra-z-realem-madryt-przy-pustych-trybunach-,nId,2289643`

**Comment by Isamaul** [comment]
Zablokowany został plugin do jQuery, za pomocą którego można w łatwy sposób zapisać/odczytać cookie w JavaScript - dodanie tej reguły może też mieć skutek w wielu innych miejscach, ponieważ jest to dość popularna wtyczka, a niektóre preferencje użytkownika zapisuje się właśnie w cookie ;)

**Comment by MajkiIT** [comment]
Usunięte.

@F4z @Isamaul dzięki
