### ISSUE TITLE
e-sadownictwo.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13231]
![Opera Zdjęcie_2019-05-05_023601_www e-sadownictwo pl](https://user-images.githubusercontent.com/36385327/57186397-bdf11800-6ede-11e9-99d1-3fca2913d8a4.png)

**Comment by krystian3w** [comment]
Reklama czegoś, pewnie zewnętrzna:

![obraz](https://user-images.githubusercontent.com/35370833/57186755-61ddc200-6ee5-11e9-8df1-0965be75a407.png) | `https://www.activ.com.pl/adriatica.html`
--- | ---

**Comment by krystian3w** [comment]
`e-sadownictwo.pl##.rstboxes`
