### ISSUE TITLE
ataksja.home.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#13236]
cookies

forum

http://www.ataksja.home.pl/forum/index.php

**Comment by krystian3w** [comment]
W sekcji ogłoszeń cookies nie wycinamy, nie ma opcji "zamknij"/"x" - wadzi wytnij swoją listą.

**Comment by krystian3w** [comment]
@MajkiIT / @KonoromiHimaries  jakaś reklama:

`ataksja.org.pl###text-3`
