### ISSUE TITLE
darmowa-telewizja.online (2)

### ISSUE THREAD

**Issue by garggul** [MajkiIT/polish-ads-filter#13234]
Reopen https://github.com/MajkiIT/polish-ads-filter/issues/12338 bo co prawda na Operze jest ok, ale na Firefoxie dalej to jest - zarówno anty-adblock jak i wyskakujące okienko. 

(Wskazówka/ciekawostka - na anty-adblocka pomaga włączenie Fanboy’s Enhanced Tracking List​ albo Nano Defendera, ale wyskakujące okienko nadal się pojawia).

**Comment by krystian3w** [comment]
Na anty-adblock działa mi:

```
 darmowa-telewizja.online##+js(addEventListener-defuser.js, load, onload)
```

Na pop-upy jedno z dwóch, zależy co komu szybciej się zdezaktualizuje lub na ile lepiej umie w JavaScript:

`darmowa-telewizja.online##+js(abort-current-inline-script.js, atob, decodeURIComponent)`

`darmowa-telewizja.online##+js(abort-current-inline-script.js, RegExp, zfgloaded)`

---

Oczywiście jak lepiej zrobić z 6 dopuszczeń wg składni ABP i łatwiej je aktualizować to już nie wnikam.

**Comment by garggul** [comment]
> krystian3w: Na anty-adblock działa mi:
> 
> ` darmowa-telewizja.online##+js(addEventListener-defuser.js, load, onload)`

Działa, ale coś prostszego też: `@@||darmowa-telewizja.online/logo.png$image,~third-party`
Tu coś pod samego Firefoxa: `darmowa-telewizja.online##^script:has-text(wb24)
`

> krystian3w: Na pop-upy jedno z dwóch, zależy co komu szybciej się zdezaktualizuje lub na ile lepiej umie w JavaScript:
>
> `darmowa-telewizja.online##+js(abort-current-inline-script.js, atob, decodeURIComponent)`
> `darmowa-telewizja.online##+js(abort-current-inline-script.js, RegExp, zfgloaded)`

Działają obydwa, można też tak: `darmowa-telewizja.online##+js(setTimeout-defuser.js, m(x), 300)`

**Comment by krystian3w** [comment]
Podobno `setTimeout-defuser.js` może doprowadzać do race condition z  `zfgloadedpopup`
