### ISSUE TITLE
liptonicetea.com (2)

### ISSUE THREAD

**Issue by garggul** [MajkiIT/polish-ads-filter#13235]
Reopen https://github.com/MajkiIT/polish-ads-filter/issues/77 bo:

<details not-open>
<summary>1 - komunikat o ciasteczkach (wskazówka/ciekawostka - komunikat można usunąć włączając Fanboy's Cookie list i/lub I don't care about cookies)</summary>

![ss_003](https://user-images.githubusercontent.com/50133507/57190912-375d2a80-6f20-11e9-8025-0df67a3ce559.png)

</details>

<details not-open>
<summary>2 - błąd EasyPrivacy - po zaakceptowaniu komunikatu o ciasteczkach strona się nie ładuje, tylko cała pusta na żółto</summary>

![ss_004](https://user-images.githubusercontent.com/50133507/57190928-5c519d80-6f20-11e9-94ca-d3e4d8e780d5.png)

</details>

Co do błędu w EasyPrivacy to rozwiązaniem będzie kolejny przykładowy wyjątek: 
`@@||www.liptonicetea.com/pl-PL/templates/liptonglobal/js/lib/google-analytics.js$script,~third-party` - chodzi o to, że skopiowali ten plik google-analitycs na własną domenę, ciekawe dlaczego, może go dodatkowo zmodyfikowali i coś do niego podrzucili - jakąś niespodziankę...a no i ta poprawka to kwalifikuje się raczej na listę Polskie Filtry Prywatności (Privacy) to i te inne poprawki co już są na POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda można też przy okazji przenieść:
https://github.com/MajkiIT/polish-ads-filter/blob/12bfa1960e5bc3885c45ac12278658a99233fbf8/polish-adblock-filters/adblock.txt#L3681

<details not-open>
<summary>a tak wygląda normalnie załadowana strona bez komunikatu ciasteczkowego i błędu:</summary>

![ss_005](https://user-images.githubusercontent.com/50133507/57191035-6627d080-6f21-11e9-885b-8e46935d73bd.png)

</details>

**Comment by krystian3w** [comment]
Wyłączyć komunikat, czyli sieciowo?

Jak dla mnie to jest "ściana ciastek" pod nią nie ma treści. A evidon to taki crap że potem Norwegowie czy Mołdawinie nie przeczytają strony - takie dziadostwo.

**Comment by krystian3w** [comment]
PS. wyjątek pod Google trzeba dodać już w filtrach na reklamy lub jak Oleg chętny to u niego - ale @garggul  pamiętasz interię, tam ci nie naprawił Gemiusa  to i może będą za duże batalię by strony czytać np. coś w stylu kary boskiej dla strony że chce analizować ruch i kliknięcia.

**Comment by krystian3w** [comment]
Lipton tea naprawiona w uBlock Origin i forkach: https://github.com/uBlockOrigin/uAssets/commit/0254b660cf9a1d8c9e4c06a80b3c4aa924cc50ad

**Comment by garggul** [comment]
Zgadza się.
