### ISSUE TITLE
dziendobry.tvn.pl

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#1324]
http://dziendobry.tvn.pl/wideo,2064,n/proste-cwiczenia-na-poprawe-krazenia,3193.html

![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/19271323/83cea684-8fc4-11e6-89ef-c53bf2d51100.PNG)

Mógłbyś proszę to naprawić?
Mam też Anti-Adblock Killer (a propos, wiecie czy autor tego skryptu wróci?)

**Comment by xxcriticxx** [comment]
nie reek dalej m.i.a.

@MajkiIT @F4z da rade cos stym zrobic?

**Comment by MajkiIT** [comment]
@F4z to pewnie to samo co na player.pl ... czyli na Chrome będzie ok.

**Comment by xxcriticxx** [comment]
@MajkiIT na chromie nie dziala testowalem

**Comment by F4z** [comment]
@MajkiIT bardziej jak na tvnturbo - https://github.com/MajkiIT/polish-ads-filter/issues/1292#issuecomment-249720872
Powinno działać w Chrome i Firefox, tylko czasami będzie komunikat, że "materiał jest niedostępny", wtedy trzeba odświeżyć kilka razy i powinno ruszyć.
Reguły:
`@@||tvn.adocean.pl/ad.xml$xmlhttprequest,domain=tvn.pl`
`@@||tvn.adocean.pl/__/ad.xml$xmlhttprequest,domain=tvn.pl`
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=tvn.pl`

**Comment by MajkiIT** [comment]
@F4z @xxcriticxx 

U mnie jest tak
![blad_onet](https://cloud.githubusercontent.com/assets/11302675/19303967/1026c6b0-906b-11e6-936d-33c9e81b2877.png)

**Comment by adreporter** [comment]
Z ciekawości wyłączyłem uBlock'a i po reklamie był filmik. Czyli wiemy, że materiał jest dostępny. Niestety te reguły, nawet po kilkunastu odświeżeń, nie pomogły. Teraz tylko pytanie, czy jakieś inne reguły pomogą.

**Comment by F4z** [comment]
@MajkiIT wczoraj jak sprawdzałem, to działało, tak jak opisałem. Dzisiaj z tego co widzę, to za każdym razem gdy chcę odtworzyć film, to następuje próba (próba, bo uBlock blokuje reklamę) wyświetlenia reklamy, a wczoraj co któryś raz reklama nie była wyświetlana i wtedy wyświetlało się "normalne" wideo.
Na razie nie widzę możliwości żeby odtworzyć film bez reklam, przy użyciu obecnych reguł do Adblocka/uBlocka, ale może ktoś coś wymyśli.
Można dodać tę regułę żeby wyświetlały się reklamy:
`@@||redcdn.pl/*/TVN-Adserver/*.mp4$xmlhttprequest,media,domain=tvn.pl`

Wszystkie reguły żeby film się wyświetlał, ale będą reklamy:
`@@||tvn.adocean.pl/ad.xml$xmlhttprequest,domain=tvn.pl`
`@@||tvn.adocean.pl/__/ad.xml$xmlhttprequest,domain=tvn.pl`
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=tvn.pl`
`@@||redcdn.pl/*/TVN-Adserver/*.mp4$xmlhttprequest,media,domain=tvn.pl`

**Comment by xxcriticxx** [comment]
@F4z podaj na forum adguard moze chlopaki cos wymysla

**Comment by xxcriticxx** [comment]
ticket open on easylist forum 

https://forums.lanik.us/viewtopic.php?f=62&t=33394

**Comment by F4z** [comment]
@xxcriticxx no niby mogę napisać, ale ostatnio na forum adguarda był temat związany z player.pl - https://forum.adguard.com/index.php?threads/resolved-video-not-playing-at-all-on-www-player-pl.10376/
I o ile się nie mylę, to odtwarzacz na stronie player.pl i na innych stronach TVNu działa w oparciu o ten sam mechanizm. Ogólnie skończyło się to tak, że w przypadku rozszerzenia dla przeglądarek, reklamy zostały odblokowane, a w przypadku Adguarda dla Windowsa zablokowane i filmy normalnie się wyświetlają.

**Comment by xxcriticxx** [comment]
@F4z widzialem ciebie na easylist bys przetestowal co tam podali 

`@@||tvn.pl^$generichide`
`@@||behavioralengine.com^$script,domain=tvn.pl`
`@@||tvn.pl/*ad$script`
`@@||tvn.adocean.pl^$xmlhttprequest,domain=tvn.pl`
`@@||imasdk.googleapis.com^$domain=tvn.pl`
`@@||cdntvn.pl/$xmlhttprequest`

poza krajem dostaniesz material jest niedostepny tak jak napisalem na easyforum

**Comment by F4z** [comment]
Ja dostaję ten sam komunikat. Nic się nie zmienia.

**Comment by xxcriticxx** [comment]
gdzie jestes w kraju? czy poza?

tutaj hbya bendzie potrzebna modyfikacja skriptu od reeka

**Comment by F4z** [comment]
W kraju i mam ten komunikat dopóki nie zezwolę na reklamy, czyli tak samo jak pisałem wcześniej.
Tak, najlepiej byłoby to zrobić przy użyciu skryptu, ale to trzeba znać się na JavaScript.

**Comment by xxcriticxx** [comment]
zobacz na reeka moze cos dasz rade zmienic

**Comment by MajkiIT** [comment]
Dostałem takie coś od Zdzisława

> Odnośnie tego anti adblocka na stronach tvn'u, to może byście zapytali o pomoc właściciela tego projektu: https://github.com/X01X012013/AdBlockProtector skoro AAK nie jest już wspierany. Sam chciałem trochę w tym pomóc (modyfikując skrypt AdblockProtectora), ale nic to nie dało. Analizowałem trochę strony tvn'u, żeby odnaleźć możliwie wszystkie źródła reklam i skryptów i po wyłączeniu adblocka itp. trafiłem na taki adres: api.behavioralengine.com w źródłach w konsoli chrome'a, a adres: behavioralengine.com przekierowuje na http://onaudience.com/ i grzebiąc trochę na ich stronie przeczytałem, że wymyślili takie narzędzie: http://onaudience.com/unblock. Może to co napisałem dużo nie wnosi (jak to wszystko wiedzieliście), ale przeczytałem, że to jest jakieś całkiem nowy system do obchodzenia blockerów reklam i nie wiadomo, czy użycie adblocka będzie w ogóle możliwe.

**Comment by MajkiIT** [comment]
https://github.com/X01X012013/AdBlockProtector/issues/23

**Comment by xxcriticxx** [comment]
@mikhoul can you help us pass this ad block?

**Comment by mikhoul** [comment]
Sadly I don't have enough time now but I looked quickly and the best way to do would be to replace the player file: http://s1-player5.cdntvn.pl/player.js to edit it and remove the addblock checker inside.

After you would have just to make a Userscript to stop the file from being loaded and replace player.js with the fixed player.js that don't check for addblocker.

This would only work with Firefox since it would be done with the `checkForBadJavascripts()` function. :octocat: 

Here's a post that explain how it work to block a script and change it with another: http://stackoverflow.com/questions/10472569/changing-javascript-on-an-html-page-out-of-my-control.


Good Luck and let me know if you are successful, I'm curious to know :smiley_cat:

**Comment by xxcriticxx** [comment]
@mikhoul when you have time we can wait this pass my pay grade

**Comment by xxcriticxx** [comment]
@F4z czy cos z tego rozumiesz?

**Comment by F4z** [comment]
@xxcriticxx wydaje mi się, że rozumiem o co chodzi, ale nie potrafię tego zrobić.
Tak swoją drogą jeszcze jest ten skrypt - `https://greasyfork.org/pl/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod-autor-przemek/code`
On bazuje na skrypcie stąd - `http://miniskrypt.blogspot.com/2014/04/3-w-1.html`
i po prostu dodaje przyciski do pobrania filmów.
Może komuś się przyda.

**Comment by xxcriticxx** [comment]
@F4z masz tam konto? moze go zapros do nas na github

**Comment by xxcriticxx** [comment]
@rysson 4 posty wyzej masz wytlumaczenie co trzeba zrobic

**Comment by MajkiIT** [comment]
@adreporter @xxcriticxx @F4z 

Możecie dodać ten skrypt do Grease Monkey i sprawdzić czy będzie OK?

http://pastebin.com/dMp1HpP8

**Comment by F4z** [comment]
@MajkiIT jeśli chodzi o strony `.tvn.pl` działa, ale dopiero po tym, jak wybiorę sobie jakość filmu.
W przypadku `player.pl` u mnie nie działa.

**Comment by MajkiIT** [comment]
@F4z Dziękuję, ale to już jakiś progress.

**Comment by xxcriticxx** [comment]
odpiska od rysson

@xxcriticxx, skoro tak offtopujemy, to zerknąłem jednym okiem. To nie Java tylko JavaScript. W dodatku potraktowany „zamętniaczem” (obscurer). Obawiam się, że nie dam rady pomóc. Raz, że JS nie jestem super biegły, dwa, że MrKnow mnie tu do wtyczki zagonił ;-) a trzy, że robota wisi.

**Comment by xxcriticxx** [comment]
@IDKwhattoputhere i wonder if you can look over this ad block for us?

**Comment by IDKwhattoputhere** [comment]
At first I get the message in https://github.com/MajkiIT/polish-ads-filter/issues/1324#issue-182260155. After adding these filters:
```
@@||dziendobry.tvn.pl^$generichide
@@*$script,~third-party,domain=dziendobry.tvn.pl
@@*$xmlhttprequest,third-party,domain=dziendobry.tvn.pl
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=dziendobry.tvn.pl
```
I get the message in https://github.com/MajkiIT/polish-ads-filter/issues/1324#issuecomment-253158006. Now I don't know if the content is geo-locked or if the filters aren't working.

**Comment by xxcriticxx** [comment]
video is not geo locked 

mikhoul recommended that we switch out the player with greasemonkey script but thats pass our skills

**Comment by IDKwhattoputhere** [comment]
I was able to download the video with JDownloader in case that helps anyone.
It seems as long as you block the MP4 file that is the video ad you will get the message in https://github.com/MajkiIT/polish-ads-filter/issues/1324#issuecomment-253158006. I'd say it's possible to circumvent that with a script but I can't code, sorry.

**Comment by xxcriticxx** [comment]
@IDKwhattoputhere if you have anyone that can help send them here 

@X01X012013 made a script for it before but he hasn't been online in while

**Comment by MajkiIT** [comment]
@adreporter @xxcriticxx @F4z 
Zerknijcie proszę na to ==> http://pastebin.com/TRawRUqy ewentualnie trzeba będzie dodać wyjątek @@||player.pl^$generichide

**Comment by adreporter** [comment]
@MajkiIT Przepraszam, że tak późno odpowiadam. Na dziendobry.tvn.pl tak jak napisał kolega @F4z, filmik można obejrzeć po wybraniu jakości:
![333](https://cloud.githubusercontent.com/assets/18214146/19934802/41ed2640-a118-11e6-960d-3fca4b73ec5a.PNG) 
Czyli problem jest rozwiązany. Dziękuję uprzejmie.

Natomiast jeżeli chodzi o player.pl to, używając Twojego najnowszego skryptu, działa ale niestety nie można przewinąć filmiku do przodu bo pojawia się to:
![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/19271323/83cea684-8fc4-11e6-89ef-c53bf2d51100.PNG)

**Comment by MajkiIT** [comment]
@adreporter 
twórca skryptu mnie poprawił. Chodziło mu o to aby wyłączyć filtry kosmetyczne. 
![orsycef](https://cloud.githubusercontent.com/assets/11302675/19958259/08f5ae4e-a19e-11e6-9cb9-fcd4f725d043.png)

**Comment by adreporter** [comment]
@MajkiIT Niestety ale u mnie nawet przy wyłączeniu filtrów kosmetycznych raz można odtworzyć filmiki a raz nie.

**Comment by xxcriticxx** [comment]
dodalem to:

`@@||*.tvn.pl^*$generichide`
`@@*^ad.xml^*$domain=tvn.pl`
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js|$domain=tvn.pl`
`@@*^TVN-Adserver^*$domain=tvn.pl`

potem zamontowalem `AdBlockProtector.user.js` i wszystko dziala tylko jest 30 sec reklama (head n shoulders) zanim film sie zacznie

**Comment by xxcriticxx** [comment]
zmienilem .tvn.pl na tvnturbo.pl i tez dziala 

`@@||*.tvnturbo.pl^*$generichide`
`@@*^ad.xml^*$domain=tvnturbo.pl`
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js|$domain=tvnturbo.pl`
`@@*^TVN-Adserver^*$domain=tvnturbo.pl`
