### ISSUE TITLE
hokejwpasy.pl

### ISSUE THREAD

**Issue by garggul** [MajkiIT/polish-ads-filter#13240]
Repoen https://github.com/MajkiIT/polish-ads-filter/issues/1512 bo anty-adblock wrócił:

![ss_001](https://user-images.githubusercontent.com/50133507/57197292-dc4e2680-6f65-11e9-9918-e6d1b98364d8.png)

**Comment by krystian3w** [comment]
Że wpis działa to nie znaczy że wrócił, mnie tam na razie nie przekierowuje na siłę pod tamten adres.

**Comment by garggul** [comment]
Zgadza się.
