### ISSUE TITLE
lowicz.pl

### ISSUE THREAD

**Issue by garggul** [MajkiIT/polish-ads-filter#13241]
Reopen https://github.com/MajkiIT/polish-ads-filter/issues/1608 bo anty-adblock wrócił.

**Comment by garggul** [comment]
Rozwiązanie podane tu: https://github.com/MajkiIT/polish-ads-filter/issues/1608#issuecomment-264712868 działa, więc nie wiem dlaczego dla xxcriticxx nie działało: https://github.com/MajkiIT/polish-ads-filter/issues/1608#issuecomment-264713052.

Lub alternatywne rozwiązanie: `||zspnr1.lowicz.pl/ezkw/index.js.php$script,~third-party`

**Comment by bogachenko** [comment]
`Lub alternatywne rozwiązanie: ||zspnr1.lowicz.pl/ezkw/index.js.php$script,~third-party`

breaks functionality

**Comment by garggul** [comment]
Ok, was aware of that it might happen as I didn't study it carefully, only at first glance and it was left to be tested by other people, so the first solution is the way.

**Comment by bogachenko** [comment]
@mapx- can you help

**Comment by garggul** [comment]
bogachenko - the  first solution from the first link: https://github.com/MajkiIT/polish-ads-filter/issues/13241#issuecomment-489584393 does work fine, unless you looking for a different non-whitelist solution.

**Comment by garggul** [comment]
Hahaha they used a trick to fool us, but I've found a scriplet solution finally (mainly for you bogatchenko, because polish filter list prefers whitelist solutions to keep ABP comatibility):
`zspnr1.lowicz.pl##+js(setInterval-defuser.js, seead)`
