### ISSUE TITLE
hentai-online.pl

### ISSUE THREAD

**Issue by garggul** [MajkiIT/polish-ads-filter#13244]
Reopen https://github.com/MajkiIT/polish-ads-filter/issues/9325 bo anty-adblock wrócił, ze zmienioną szatą:

![ss_001](https://user-images.githubusercontent.com/50133507/57194590-e1e94380-6f48-11e9-8f2d-c6d6813f8956.png)

**Comment by MajkiIT** [comment]
`hentai-online.pl##.post-entry > center`

**Comment by garggul** [comment]
krystian3w, masz anty-adblocka?

**Comment by krystian3w** [comment]
Jest. Z AdNuseam i ich generyków już nie korzystam.

**Comment by krystian3w** [comment]
```
@@||hentai-online.pl/wp-content/plugins/jgc-adblocker-detector/js/jgcabd-detect-adblock.js$script
```

Tyle, że może tematyka porno sprawi, że ten zostanie i trzeba do uAssets / JsPenguin2017...

**Comment by garggul** [comment]
Działa.

> krystian3w : Tyle, że może tematyka porno 

No jakoś tak niezbyt tego porno tam nie zauważyłem, nie widać za bardzo.

> krystian3w : sprawi, że ten zostanie i trzeba do uAssets / JsPenguin2017..

A nie do EasyList Polish? Ja tam właśnie zgłaszam wszystko co tu nie zosanie naprawione, nawet porno zgłosiłem : https://github.com/easylistpolish/easylistpolish/issues/99.

**Comment by krystian3w** [comment]
Oni nie naprawiają anty-adblock a porzucają wycinanie tam reklam.

**Comment by garggul** [comment]
A no tak, od anty-adblocków EasyList to Adblock Warning Removal jestale to raczej na ogólniejsze filtry, więc chyba masz rację, że do uAssets.

**Comment by krystian3w** [comment]
Chyba że skryptem przerwą ten lub akcje pop-up, wtedy lipa.
