### ISSUE TITLE
waw4free.pl

### ISSUE THREAD

**Issue by garggul** [MajkiIT/polish-ads-filter#13246]
Puste kontenery po reklamach z napisem reklama:

https://waw4free.pl/wydarzenie-59668-ventura-w-krainie-wulkanow-jaskin-i-skal-pol-roku-na-azorach

![ss_006](https://user-images.githubusercontent.com/50133507/57194759-dbf46200-6f4a-11e9-8706-fa92ebf02d85.png)

**Comment by MajkiIT** [comment]
```
waw4free.pl###detal_top
waw4free.pl##.adsbygoogle
waw4free.pl###opis > div > A
```

**Comment by krystian3w** [comment]
`waw4free.pl##div.zobacz-box` tego nie wykrywają.

**Comment by garggul** [comment]
Nr 3 nieukryty:

![waw4free](https://user-images.githubusercontent.com/50133507/57210758-1eb34a00-6fde-11e9-9728-aad3ccaf1cac.png)

**Comment by krystian3w** [comment]
3 to nie będzie ten adsbygoogle? Bo niby tej klasy nie wolno a bogachenko tam wykrył skrypt pod jakiś fork `fuckadblock`.

**Comment by garggul** [comment]
Na to wygląda, bo jak doda się `waw4free.pl##.adsbygoogle` co właśnie zrobił admin, to rzeczywiście wyskakuje adblock, ale jak się zamiast niego doda `waw4free.pl##.article_image > .adsbygoogle` to już anty-adblocka nie ma.

Ale nawet powycięciu tego kontenera, zostaje też napis, przez co mylnie wydaje się, że to zdjęcie nad napisem jest reklamą.

No i zdaje się, że te OPTI TAXI to też jest reklama.

**Comment by krystian3w** [comment]
Css pozwala ukryć ten tekst i niby skrypt nie ogarniał.

Dodatkowo wykrywają ukrycie Taxi 🚕 "div > a".

**Comment by garggul** [comment]
> krystian3w: Dodatkowo wykrywają ukrycie Taxi "div > a".

W którym dokładnie miejscu, bo nic nie znalazłem i czym to skutkuje bo z tym filtrem anty-adblocka nie ma.
