### ISSUE TITLE
podworko.nivea.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13255]
Cookies
![Opera Zdjęcie_2019-05-06_032217_podworko nivea pl](https://user-images.githubusercontent.com/36385327/57203194-51454e80-6fae-11e9-9abf-387f5bb8107f.png)

**Comment by xMaap** [comment]
https://baby.nivea.pl
![Opera Zdjęcie_2019-05-06_032516_baby nivea pl](https://user-images.githubusercontent.com/36385327/57203237-9ff2e880-6fae-11e9-87f1-ef167a1c58a4.png)

**Comment by krystian3w** [comment]
Na bejbi to niby coś wcięło newsletter.

**Comment by krystian3w** [comment]
Nie wiem co wcięło newsletter, pewnie wadliwość `Fanboy Cookie List`.
