### ISSUE TITLE
poczta.interia.pl

### ISSUE THREAD

**Issue by kamild1996** [MajkiIT/polish-ads-filter#1325]
Filtr ten powoduje, że na nowej wersji poczty Interii przycisk "Wyloguj" znika, zarówno w panelu kontaktów, jak i w ustawieniach.

Przed włączeniem: http://imgur.com/wsa3sNe
Po wyłączeniu: http://imgur.com/BRc13nw

**Comment by F4z** [comment]
Dodanie tej reguły powinno przywrócić przycisk:
`poczta.interia.pl#@#[href*=".hit.gemius.pl"]`

**Comment by MajkiIT** [comment]
@F4z dzięki
