### ISSUE TITLE
waw4free (2)

### ISSUE THREAD

**Issue by garggul** [MajkiIT/polish-ads-filter#13251]
Ho ho, reopen dopiero co zamkniętego przed chwilą: https://github.com/MajkiIT/polish-ads-filter/issues/13246, bo po ostatnim commicie to teraz wywala anty-adblocka, hehehe:

![ss_002](https://user-images.githubusercontent.com/50133507/57198624-33a7c300-6f75-11e9-8b83-11fe9943adb8.png)

**Comment by krystian3w** [comment]
To trudny przeciwnik, trzeba na około wycinać reklamy lub w liście anty-adblock.

**Comment by garggul** [comment]
>krystian3w: To trudny przeciwnik, trzeba na około wycinać reklamy lub w liście anty-adblock:
> 
> ```
> waw4free.pl##div.zobacz-box
> waw4free.pl##div.detal_szpalta-box
> ```

https://github.com/MajkiIT/polish-ads-filter/issues/13246#issuecomment-489520112

**Comment by krystian3w** [comment]
```
waw4free.pl#@#.zobacz-box, #detal_top, #opis > div > A, .adsbygoogle waw4free.pl##.zobacz-box waw4free.pl###opis > div waw4free.pl###detal_top waw4free.pl##.article_image > .adsbygoogle waw4free.pl##.article_image:style(visibility: hidden !important;) waw4free.pl##.article_image > a:style(visibility: visible !important;)
```

Filtry z style mają być w suplementach (można do obu - AdGuard i tak pewnie będzie miał filtr na deaktywacje wykrywania).

**Comment by krystian3w** [comment]
Oleg może dopisać do filtru na twój ogródek:

```
twojogrodek.pl,waw4free.pl##.pub_300x250.pub_300x250m.text-ad.textAd.text-ads.text-ad-links:style(display: block !important;)
```
