### ISSUE TITLE
blockchain.com/pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13253]
Social
![Opera Zdjęcie_2019-05-05_211832_www blockchain com](https://user-images.githubusercontent.com/36385327/57199089-60f76f80-6f7b-11e9-920c-8d444ba69394.png)

**Comment by xMaap** [comment]
@krystian3w I tutaj

```
https://www.blockchain.com/pl/markets
https://www.blockchain.com/pl/explorer
https://www.blockchain.com/pl/prices
https://www.blockchain.com/explorer
https://www.blockchain.com/markets
https://www.blockchain.com/pl/prices
```

**Comment by krystian3w** [comment]
A ten to jest zbyt zrandomizowany, trzeba przemyśleć czy po linkach to blokować.
