### ISSUE TITLE
forsal.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13261]
Nie działa dodawanie komentarzy i odpowiadania na komentarze.

`https://forsal.pl/artykuly/1410704,spelnia-sie-czarny-scenariusz-zabraknie-szczepionki-przeciw-gruzlicy.html`

**Comment by garggul** [comment]
A jesteś pewien, że to wina filtrów, a nie strony, czy próbowałeś z wyłączonym uBO.

Bo mi z uBO jeden komentarz nie chciał się dodać bo wyskoczył błąd, że nie wszystkie wymagane pola zostały uzupełnione, pomimo, że zostały (są tylko 2 pola, wiadomośc + autor), ale już potem kolejne komentarze już normalnie się dodawały bez problemów.

**Comment by xMaap** [comment]
A jednak winne tutaj są Polskie Filtry Elementów Irytujących @hawkeye116477 
Po wysączeniu ich
![Opera Zdjęcie_2019-05-07_153830_forsal pl](https://user-images.githubusercontent.com/36385327/57303729-37a32480-70de-11e9-9091-98dc3c60da32.png)

**Comment by garggul** [comment]
Już wcześniej sprawdzałem wszystkie listy filtrów, i nawet teraz sprwdziłem drugi raz i u mnie zarówno na Firefox jak i na Operze problemu żadnego nie ma, z resztą zrzutu ekranu nie wynika, czy dodawanie komentarzy działa czy nie, gdzie tu niby widać jakiś problem.

**Comment by garggul** [comment]
`forsal.pl#@#+js(abort-on-property-read.js, parseFloat)`

**Comment by hawkeye116477** [comment]
Czyli na filmiki scrollujące trzeba wykombinować coś innego.

**Comment by hawkeye116477** [comment]
Niby jest jeszcze samodzielny moduł, także jakby ktoś lubił ciastka, a nie lubił tych filmików, to alternatywa przydatna...

**Comment by garggul** [comment]
No tak, zapomniałem o modułach, pomimo, że sam z nich korzystam.

**Comment by xMaap** [comment]
Można zamknąć?

**Comment by hawkeye116477** [comment]
@xMaap Tak
