### ISSUE TITLE
leki.abczdrowie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13264]
`https://leki.abczdrowie.pl/p/coldrex-maxgrip-c-omega-pharma-poland-sp-z-oo`
![Opera Zdjęcie_2019-05-06_135801_leki abczdrowie pl](https://user-images.githubusercontent.com/36385327/57223649-073c8700-7007-11e9-97a2-3d4dc7ba7ae2.png)

**Comment by MajkiIT** [comment]
@xMaap czyściłeś ciasteczka ?

**Comment by xMaap** [comment]
@MajkiIT Tak

**Comment by xMaap** [comment]
Hmm nie ma już reklamy, ale

`https://portal.abczdrowie.pl/przeziebienie-jajnikow-objawy-i-sposoby-leczenia?src01=8d289`
Tutaj nie ma filmu
![Opera Zdjęcie_2019-05-06_141608_portal abczdrowie pl](https://user-images.githubusercontent.com/36385327/57224377-921e8100-7009-11e9-8632-b82ea75f0a7b.png)

**Comment by krystian3w** [comment]
Pewnie gdpr init?

**Comment by krystian3w** [comment]
Ameryki nie odkryję, ale na moje brak akceptacji rodo blokuje filmik.

Niestety nie pomoże to nawet jakiś "overlay-buster.js". Powodzenia w oszukiwaniu skryptu... 😭.

**Comment by garggul** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/7533#issuecomment-489734915

**Comment by krystian3w** [comment]
Magia - pomaga blokowanie całej biblioteki WP / Gemiusa:

```
||wp.pl/*-FwkqOxhmGz4XCSo7GGYbPhcJKjsYZhs-$script
```

Już z 3 miesiąc niby nazwa się utrzymuje dla pliku z RODO+.

**Comment by garggul** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/7533#issuecomment-478374110 - no już 3 miesiąc.

**Comment by krystian3w** [comment]
@MajkiIT  ten temat umie wyświetlać się w otwartych... - wtf 🤣
