### ISSUE TITLE
gadzetomania.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13267]
`https://gadzetomania.pl/60489,czarnobyl-bioroboty-likwidatorzy`
![Opera Zdjęcie_2019-05-06_141058_gadzetomania pl](https://user-images.githubusercontent.com/36385327/57224163-d1989d80-7008-11e9-9f63-23100faeaf8e.png)

**Comment by MajkiIT** [comment]
@xMaap Czyściłeś ciasteczka?
