### ISSUE TITLE
gumtree.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#13268]
Z włączonym adblockiem nie wyświetlają się ceny:
![image](https://user-images.githubusercontent.com/11385099/57237151-e126df00-7026-11e9-93a7-e24bc725008f.png)

bez:
![image](https://user-images.githubusercontent.com/11385099/57237091-bdfc2f80-7026-11e9-83d7-5d4a9de7ed57.png)

**Comment by garggul** [comment]
Za darmo rozdają hehe.

**Comment by garggul** [comment]
Bruździ ten filtr:

https://github.com/MajkiIT/polish-ads-filter/blob/dc6b8ca63975460afae44db2cbda327973fb253d/polish-adblock-filters/adblock.txt#L268

trzeba dodać wykluczenie: `~www.gumtree.pl`,
 a do tego momentu mathew85 może sobie dodać: `~www.gumtree.pl##[class^="ad-"]`

**Comment by krystian3w** [comment]
Bezpieczniej mimo wszystko podawać:

`www.gumtree.pl#@#[class^="ad-"]`

Nie zanosi się by "tak ma być" zostało zmienione w uBO lub cała reszta zmieniła idee na tą z uBO.

**Comment by garggul** [comment]
> 
> 
> > a do tego momentu mathew85 może sobie dodać
> 
> Bezpieczniej mimo wszystko podawać:
> 
> `www.gumtree.pl#@#[class^="ad-"]`
> 
> Nie zanosi się by "tak ma być" zostało zmienione w uBO lub cała reszta zmieniła idee na tą z uBO.

No akurat w tym przypadku dałoby się, ale nie zawsze się da tak jak ty proponujesz, cytat mnie samego z https://github.com/MajkiIT/polish-ads-filter/issues/7533#issuecomment-489734915: 

> Dodanie `abczdrowie.pl#@#+js(addEventListener-defuser.js, DOMContentLoaded, :setTimeout)` lub
> `~leki.abczdrowie.pl##+js(addEventListener-defuser.js, DOMContentLoaded, :setTimeout)`

A teraz spróbuj wykluczyć twoją metodą, czyli za pomocą małpki tylko same `leki.abczdrowie.pl` zamiast całe `abczdrowie.pl ` - `leki.abczdrowie.pl#@#+js(addEventListener-defuser.js, DOMContentLoaded, :setTimeout)` nie zadziała...zadziała natomiast metoda z tyldą `~`. (przykład teoretyczny, niezależny od tego czy na `abczdrowie.pl` lub `portal.abczdrowie.pl` też jest problem z filmikiem, bo wtedy w praktyce wykluczenie całej `abczdrowie.pl` miałoby sens i wtedy możnaby użyć metody z małpką `@`).
