### ISSUE TITLE
,$badfilter

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#13298]
co pliku rodo-ciasteczkowego wkradł się agresywny filtr sieciowy:

```
,$badfilter
```

https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/3d5e6ab9dd43aa64bb47adeae11d80147a690e50

**Comment by hawkeye116477** [comment]
@krystian3w Ale tego nie ma w stabilnym wydaniu :smile:

**Comment by krystian3w** [comment]
A to dziwne.

**Comment by hawkeye116477** [comment]
@krystian3w Wrzuciłem to o 19:15, a ty błąd zrobiłeś pół godziny później, zagadka rozwiązana :stuck_out_tongue:

**Comment by krystian3w** [comment]
A dziwne, że to co po spacji to zostało jakby zignorowane.
