### ISSUE TITLE
billbook.com/pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13293]
![Opera Zdjęcie_2019-05-08_221825_www billbook com](https://user-images.githubusercontent.com/36385327/57405707-6654f400-71df-11e9-99f0-fb7b7ddcfa03.png)

**Comment by krystian3w** [comment]
A skąd wersja oblana kawą / czekoladą?

**Comment by hawkeye116477** [comment]
Może zainstalował jakieś rozszerzenie, które robi dark mode.

**Comment by xMaap** [comment]
Zapomniałem wyłączyć na stronie Dark Reader.
