### ISSUE TITLE
hentai-online.pl (2)

### ISSUE THREAD

**Issue by garggul** [MajkiIT/polish-ads-filter#13292]
Reopen https://github.com/MajkiIT/polish-ads-filter/issues/13244 bo anty-adblock dalej jest, bo trzeba dodać jeszcze whitelist na EasyList:
`hentai-online.pl#@#.adsBox` albo odrazu dać 
`@@||hentai-online.pl^$generichide`.

=============================================================

Przy okazji chciałem spytać dlaczego w tych dwóch zgłoszeniach anty-adblockowych: https://github.com/MajkiIT/polish-ads-filter/issues/13234 + https://github.com/MajkiIT/polish-ads-filter/issues/13241
zostały wybrane rozwiązania skryptowe kompatybilne tylko z uBO zamiast prostszych rozwiązań whitelistująch kompatyblinych także z ABP, bo polskie listy starają się zachować kompatybilność z ABP i w więszkości przypadków zgłoszeń anty-adblockowych preferowanym rozwiązaniem są filtry whitelistujące zgodne z ABP, nawet sam admin na zarzut i pytanie ze strony:

> ghajini : https://github.com/MajkiIT/polish-ads-filter/issues/8544#issuecomment-411511204 

dlaczego tyle wyjątków i dlaczego nie dajemy skryptów odpisał:

> admin : https://github.com/MajkiIT/polish-ads-filter/issues/8544#issuecomment-411540732

bo chcemy być zgodni z ABP

hawkeye116477 gdzieś kiedyś pisał do mnie dokładnie to samo (akurat już nie mogłem tego znaleźć), że "zawsze lepiej wyjątek niż skrypt", znalazłem tylko inną podobną jego wypowiedź skierowaną do krystian3w https://github.com/MajkiIT/polish-ads-filter/issues/11631#issuecomment-457187310

A więc czy były jakieś problemy z filtrami whitelistującymi (poza tym u xxcriticxx, który może być już nieaktualny, albo coś było u niego nie tak, bo u mnie ten wyjątek działa)...żądam aby te osoby jako promotorzy pierwszeństwa rozwiązań whitelistującyh zgodnych z ABP nad rozwiązaniami skryptowymi zgodnymi tylko z uBO odezwali się w tej kwestii, no a przedewszystkim tego kto dodał filtry/commita: https://github.com/olegwukr/polish-privacy-filters/commit/4ebefe7c2cf7e6833099cb25e83969d21e3b221e i zwyczajnie uzasadnił - uwaga ja nie chcę się kłócić czy bić o to, które rozwiązanie zostało dodane, a tylko zwyczajnie dowiedzieć się dlaczego i jaka jest w tym logika, że do jednych zgłoszeń idzie wyjątek a do innych skrypt, jeśli był jakiś powód to nie ma problemu, tylko jaki, a może dodający zwyczajnie przegapił / nie zauważył / pomylił się...

**Comment by krystian3w** [comment]
Ja tam się nie będę bawić w wyjątki pod telewizje online jak mi filtr skryptowy działa, nie wiem czy ktoś się dokopał co szwankowało w Firefox.

Jak np. `dniwolne.eu` dało się dociąć, że nie zostaje pusty kontener to warto było to dodać i zostało dodane.

**Comment by krystian3w** [comment]
Co do łowicza to niby twoja wersja psuła coś za bardzo..., co to już nie wnikam.

**Comment by garggul** [comment]
> krystian3w : https://github.com/MajkiIT/polish-ads-filter/issues/13292#issuecomment-490608548 : przejdzie na "5 wyjątków".

Nie czaję, o które 5 wyjątków chodzi, pod tym linkiem: https://github.com/MajkiIT/polish-ads-filter/issues/12338#issue-416742416w loggerze widzę, tylko 1 - generichide od kosmetyków, a mój byłby drugim, chyba, że masz na myśli wyjątki, które mogłyby pojawić się w przyszłości:
![1](https://user-images.githubusercontent.com/50133507/57404335-03159280-71dc-11e9-8835-38248f869431.png)

===================================================================

> krystian3w : https://github.com/MajkiIT/polish-ads-filter/issues/13292#issuecomment-490610261 : Co do łowicza to niby twoja wersja psuła coś za bardzo..., co to już nie wnikam.

Psuł ten drugi już wykreślony, ale mi chodzi o ten pierwszy podany tu https://github.com/MajkiIT/polish-ads-filter/issues/13241#issuecomment-489584393: 

> First solution:
> Rozwiązanie podane tu: https://github.com/MajkiIT/polish-ads-filter/issues/1608#issuecomment-264712868 działa,

wymyślony przez admina, a odkopany przeze mnie, nic mi nie psuje, czy komuś coś psuje.

**Comment by krystian3w** [comment]
No to było przekopiować, pewnie Oleg nie miał ochoty kopać np. aż w komentarzach na `certyficate.it` (z okolic przed githubem) za domeną lub prosić o udostępnienie zgłoszeń mailowych jakie nie zostały nigdy skonwertowane do issues na github.

**Comment by krystian3w** [comment]
Jeszcze by można nawiązać, że tu nie ma wolontariuszy co jak w uAssets co 2 miesiące aktualizują  jakieś zgłoszenie sprzed kilku lat (zakładam że gdzieś na reddit ktoś nagle się przypomina lub na lanik.us lub niby to ulubiony kontent wolontariuszy niby od zgłoszenia - to aż korci by nie naprawić).

**Comment by garggul** [comment]
> krystian3w : https://github.com/MajkiIT/polish-ads-filter/issues/13292#issuecomment-490634479 : No to było przekopiować,

Baletnicy to i rąbek u spódnicy, co mam robić i jak komentarze pisać to ja dobrze wiem, i co może jeszcze laskę zrobić, zazwyczaj podaję link do źródła, bo po co duplikować materiał, nie moja wina, że ktoś okularów nie włożył albo nie zauważył albo mu się nie chciało kliknąć w link do komentarza, przez co przegapił filtr, ale najlepiej zwalić winę na mnie.

> krystian3w : pewnie Oleg nie miał ochoty kopać

A ja przekopiowywać..tak mogę odbić piłeczkę, ale tego nie zrobię, bo u mnie to kwestia nie chcenia, tylko tak jak już pisałem, zazwyczaj nie powielam źródeł tylko linkuję do nich i nikomu nic do tego, nie życzę sobie tego typu uwag.

Do tego co dalej napisane, to niestety, ale pomimo, że czytałem kilka razy, to się nie odniosę, bo musiałbym najpierw to zrozumieć, a żeby to zrozumieć to musiałbym najpierw zapalić to co ty. Dobranoc.

**Comment by xxcriticxx** [comment]
Ma ktoś jakieś staty ile z nas ABP używa?

@garggul o jakiego admina chodzi?

**Comment by garggul** [comment]
Hmm..już druga osoba, która przegapiła link w moim komentarzu (albo wg. hipotezy krystian3w nie chciało tej osobie się w niego kliknąć) , ale spoko, widocznie jakiś zbieg okoliczności ostatnio, bo jest i trzecia osoba, która przegapiła coś w moim komentarzu - nawet sam pingwin przegapił: 
`https://github.com/uBlockOrigin/uAssets/issues/5551#issuecomment-490707515 `. Ja też sam czasem coś przegapiam jak każdy, więc spoko, już nakierowuję co do kwestii admina & przegapienia linku: wystarczy kliknąć w link do komentarza, żeby zobaczyć kto jest autorem komentarza (adminem).

**Comment by krystian3w** [comment]
W sumie to u mnie pomagało dopuszczenie js / wyjątek pod AdBox niby też działa (pewnie chromium wymaga i go lub tylko go).

Ciekawe na ile w ABP pomaga sam dopuszczony plik js - możliwe że wcale

**Comment by xxcriticxx** [comment]
@garggul 

![Capture](https://user-images.githubusercontent.com/15007183/57445840-37f80880-7221-11e9-8ca8-45844f6c4fba.PNG)
![Capture2](https://user-images.githubusercontent.com/15007183/57445847-3af2f900-7221-11e9-9fcb-fff94b013ee8.PNG)

**Comment by garggul** [comment]
Czyli ci chodziło, że nazwałem osobę zarządzającą repo adminem, a nie właścicielem, czyli nie trzymałem się ściśle terminologi githubowej, no nie zaprzeczam, ale to przecież jeden walec, jak nazwie się taką osobę, ważne że wiadomo o kogo chodzi, to wzięło mi się i ostało z forów, tu przykład takiego forum, na którym przy okazji wspomnę, że udziela się aktywnie i dumnie nasz krystian3w: https://mozillapl.org/forum/:
![SS_013](https://user-images.githubusercontent.com/50133507/57448562-f6378400-7259-11e9-8486-36840e679e57.png)

Gratuluję ci, złapałeś mnie za ~~jaja~~ kulfona, aż mi spuchł do czerwoności i wygrałeś iPhone XR lub iPhone XS do wyboru w 6 kolorach, zhańbiłem się jako "naukowiec" bo użyłem terminologii  "zamiennej/slangowej/gwarowej"/ przyniesionej jako naleciałość z forum do których się przyzwyczaiłem, przeto błagam najświętszą Maryję zawsze dziewicę, żeby mi wybaczyła i pilnowała, abym mówił ziemniak, a nie kartofel albo pyra tudzież grula, oraz jednocześnie proszę o łagodną karę chłosty, tylko 5 uderzeń z perskiego bata.

Jednocześnie przy okazji skoro już zwracać komuś uwagę, to wszystkim co nie, a więc zaprośmy do zabawy innych i podziwiiajmy gwarę naszego:

1_ 
> blocker999 : https://github.com/MajkiIT/polish-ads-filter/issues/12235 : info o adblocku, " podziel się " ( po lewo ) oraz resztka ( po prawo ) 

( https://www.google.pl/search?q=po+lewo+po+prawo )

2_ 

> krystian3w : https://github.com/olegwukr/polish-privacy-filters/issues/72#issuecomment-490828348: Mi na Androidzie dyfuzery @garggul działają z odświeniem strony (dobre programy i forum, może podobne coś zreprodukuje na homebook / domodi).

( https://translate.google.pl/?hl=pl#view=home&op=translate&sl=pl&tl=en&text=defuser )

Po wciśnięciu obydwu ikonek głośniczka słychać wyraźnie odpowiednio : difiuzer / dyfiuzer a więc jest `i`

I co by nie wspomnieć jeszcze o żądanie przez rz

> krystian3w : https://github.com/olegwukr/polish-privacy-filters/issues/67#issuecomment-490793171 : plik / rządanie "XML"

Zabawa w chwytanie za mosznę (przyłapywanie) kogoś na czymś niezbyt istotym, ale zabawnym, jak ktoś chce się bawić, to nie ma problemu.

A tak w ogóle skoro już tak zabawnie się zrobiło hehe to xxcriticxx, specjalnie dla ciebie, chciałem jako kulfon opowiedzieć ci jak stałem się kulfonem...tak naprawdę byłem kiedyś plastusiem podobnym do ciebie...

![](https://pocisk.org/upload/images/large/2018/11/kulfon_2018-11-23_11-56-19.jpg)

**Comment by xxcriticxx** [comment]
@garggul ale off topic zrobiles

**Comment by garggul** [comment]
> xxcriticxx : https://github.com/MajkiIT/polish-ads-filter/issues/13292#issuecomment-490926722 : ale off topic zrobiles

Ty go zrobiłeś, a ja na niego z grzeczności tylko odpisuję, gdybyś go nie zrobił, to nie musiałbym na niego odpisywać, a teraz widzę, że z tej grzeczności tyle mam, że się znowu czepiasz i bezczelnie odwracasz kota ogonem i zwalasz na mnie, jasno widać teraz, że ten twój off-topic to zaplanowana prowokacja, które nie jeden już raz w przeszłości urządzałeś w moim kierunku, ale ja się nie dam sprowokować, więc jeśli mógłbyś przestać mnie zaczepiać to byłoby fajnie, bo inaczej poskarżę się na ciebie administratorowi tego repo oraz administracji githuba, a do pomocy mam kolegę, któremu pomagam i który się za mną wstawi @seba2282 i przedstawi mnie jako użytkownika, który tu dużo pomaga.

**Comment by seba2282** [comment]
@garggul @xxcriticxx nie wiem o co dokładnie chodzi. Ale jesteśmy społecznością na GH i powinniśmy sobie pomagać, a nie dogryzać. I @xxcriticxx cały czas czekam za regułą, która ukryje przyciski logowania przez Facebook i Google na dobreprogramy. Kiedy to dodacie? Pytam poważnie.

**Comment by krystian3w** [comment]
Nie dodamy, my takie odblokowujemy @MajkiIT  mamy zacząć blokowanie `przycisków logowania "Facebookiem"` w twojej liście na `elementy społecznościowe`?

**Comment by seba2282** [comment]
@MajkiIT, czekamy na oficjalne info. 🙂

**Comment by krystian3w** [comment]
Tak dla rozluźnienia uważajcie jak tłumaczycie `white` by nie wyszedł `wybielacz` czy z `kredki` wyszedł `ołówek`:

https://www.youtube.com/watch?v=Aejw6Ao0wOU

**Comment by seba2282** [comment]
@krystian3w, dobre 😂 
Mogę spytać. Czy twoja reguła, którą mnie poratowałeś, psuje gdzieś strony z domeny wp czy naprawia wszystko?

**Comment by krystian3w** [comment]
Wydaje mi się, że wtedy nie da się mimo wszystko rozwijać komentarzy na `sportowefakty.wp.pl` dlatego u Olega w domain jest podana by tam nie blokowała pliku.

I pod sportowe fakty mamy wtedy dodatek / `overlay-buster.js` / userCSS, bo niby da się nim wyciąć element najwyżej trzeba precyzować pozycje na stronie www, bo `has-text` działa za wolno i miga.

**Comment by krystian3w** [comment]
No oni mają własny skrypt i on nie psuje `sportowych faktów` ani `pilot.wp.pl`, ani `wideo.wp.pl` / `video.wp.pl`.

I w sumie można zobaczyć czy nie wskakuje anty-adblock od zablokowania tego pliku na tych:

* `pilot.wp.pl`
* `wideo.wp.pl` / `video.wp.pl`

**Comment by seba2282** [comment]
Twoja reguła pomogła w wysypywaniu się na starym Edge Cookies na dobrych programach. Tak myślę. Mógłbyś sprawdzić tą regułę co mi podałeś, ale bez wyłączania żadnych poddomen wp i te dwie reguły co tu podałeś razem do filtrów użytkownika i sprawdzić działanie, co będzie.

**Comment by MajkiIT** [comment]
@krystian3w @seba2282 ja bym nie blokował tego, bo wiele firm używa tego jako SSO. Jak coś to wrzucić to w filtry prywatności, bo rejestrując się w ten sposób pobierane są wszystkie dane prywatne z FB. Można utworzyć oddzielną listę ale nie wiem czy jest sens.

**Comment by seba2282** [comment]
@MajkiIT, dziękuję za konkretną odpowiedź. 👍
