### ISSUE TITLE
vod.tvp.pl

### ISSUE THREAD

**Issue by pufpuf89** [MajkiIT/polish-ads-filter#13294]
### Link bezpośredni
https://vod.tvp.pl/video/rodzinkapl,odc-260-kotleciki-dla-tomusia,42335304

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Blokada następuje po około 30 sekundach ogladania materiału. Video można oglądać / przewijać od dowolnego momentu ale blokada i tak się pojawia.

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome

**Rozszerzenia i skrypty:**
1. uBlock Origin + uBlock Origin Extra
2. Nano Defender

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Oficjalne polskie filtry przeciwko alertom o Adblocku
4. Próbowałem również:
- Nano Defender Integration​​​​​
- Nano Filters​​​​​
- Nano Filters - Whitelist

**Comment by krystian3w** [comment]
No w sumie tak, 30 sekunda i blokada, nie pomaga Nano Defender.

**Comment by krystian3w** [comment]
Pomaga niby wpuszczenie Google, może AdamWr wymyśli skrypt.

```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=vod.tvp.pl
@@||imasdk.googleapis.com/js/sdkloader/vpaid_adapter.js$script,domain=vod.tvp.pl
```

**Comment by pufpuf89** [comment]
Dla mnie to jest czarna magia ale pomogło. Dzięki wielkie :)

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję. 
Ja nie mam tego paska, ale regułę poproszę aby dodali.

**Comment by krystian3w** [comment]
Takie czerwone na pasku odtwarzania:

![obraz](https://user-images.githubusercontent.com/35370833/57474647-e0928080-7292-11e9-9ab0-9a26204a25b5.png) |
--- |

**Comment by MajkiIT** [comment]
@krystian3w Ok. Bardzo dziękuję.
