### ISSUE TITLE
fm.tuba.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1330]
thx to your friends from easylist `https://forums.lanik.us/viewtopic.php?f=62&t=33407`

adblock

`http://fm.tuba.pl/play/39/2/radio-tuba-top-hits`

`@@||tuba.pl^$generichide`
`@@||tuba.pl/*ad`

**Comment by MajkiIT** [comment]
@xxcriticxx dodane. Dzięki
