### ISSUE TITLE
tinder.com/?lang=pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13324]
Cookies
![Zrzut ekranu z 2019-05-12 19-33-20](https://user-images.githubusercontent.com/36385327/57585789-23e82b80-74ed-11e9-9347-4dba25f49cb2.png)

**Comment by krystian3w** [comment]
Mała uwaga dla archeologów, od teraz ten pasek wytnie tylko uBO/Nano Adblocker/AdGuard:

```
tinder.com###content > span > .App main div[class^="Pos"][class*="NetHeight"]:style(height: 100% !important;)
tinder.com###content > span > .App > div[class^="Pos"][class*="Start"]:has-text(pliki cookie)
```
