### ISSUE TITLE
arkowcy.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13328]
![Zrzut ekranu z 2019-05-13 02-57-39](https://user-images.githubusercontent.com/36385327/57590274-f15d2380-752a-11e9-8445-7f87f50d79d4.png)

**Comment by xxcriticxx** [comment]
@xMaap w jakim timezone jestes ze postujesz tak pozno?

**Comment by garggul** [comment]
Na anty-adblocka pomaga włączenie listy: Fanboy’s Enhanced Tracking List, wyciągnięta reguła:
`@@/advertisement.js$script` jeśli zbyt ogólna, to można ściślejszą:
`@@||arkowcy.pl/js/advertisement.js$script,~third-party`
