### ISSUE TITLE
chelsea24news.pl

### ISSUE THREAD

**Issue by garggul** [MajkiIT/polish-ads-filter#13337]
U góry duży pusty kontener po reklamie:

![ss_011](https://user-images.githubusercontent.com/50133507/57770862-8cafed80-7711-11e9-8371-3190c2aab9b2.png)

**Comment by MajkiIT** [comment]
@garggul Jak wyłączysz bloker to masz reklamę ?

**Comment by garggul** [comment]
Tak, reklama Google `https://adclick.g.doubleclick.net/pcs/click?xai= (...)` :

![ss_005](https://user-images.githubusercontent.com/50133507/57984263-6912dd00-7a5a-11e9-8ac0-e1e269098109.png)

**Comment by MajkiIT** [comment]
```
chelsea24news.pl##.header-wrap
chelsea24news.pl##body > center
```
