### ISSUE TITLE
poki.pl

### ISSUE THREAD

**Issue by garggul** [MajkiIT/polish-ads-filter#13338]
Puste kontenery po reklamach:
https://poki.pl/g/subway-surfers

![ss_012](https://user-images.githubusercontent.com/50133507/57772337-760b9580-7715-11e9-8ee0-386a71820ef7.png)

**Comment by kizimizi** [comment]
Działa: [https://kizi-mizi.pl/s/subway-surfers](https://kizi-mizi.pl/s/subway-surfers)
