### ISSUE TITLE
fakty.interia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13358]
Social to białe puste miejsce.
![Zrzut ekranu-20190516014757-946x580](https://user-images.githubusercontent.com/36385327/57816775-daae0b00-777c-11e9-8dc8-2be77bfca858.png)

**Comment by krystian3w** [comment]
Inne mają podobne?

**Comment by xMaap** [comment]
Z tego co zauważyłem to jest to tylko na fakty.interia.pl i nigdzie indziej.
