### ISSUE TITLE
biedronka.pl

### ISSUE THREAD

**Issue by salionPL** [MajkiIT/polish-ads-filter#13398]
### **Brakuje jednego kafelka z produktem.**

![Screenshot_2019-05-17 Codziennie nowy hit dnia - Biedronka pl](https://user-images.githubusercontent.com/38588787/57954102-449bf100-78f2-11e9-9657-c9b8a11a3d72.jpg)

**Adres strony:** https://www.biedronka.pl/pl/codziennie-nowy-hit-dnia

**Moja konfiguracja:**

Windows 10 [64bit]
Firefox 66.0.5 [64bit]
uBlock Origin 1.19.2

**Moje listy filtrów:**
<details>

![filtry](https://user-images.githubusercontent.com/38588787/50219917-f90c0800-0390-11e9-98a8-19244775bb61.png)
</details>

**Comment by xxcriticxx** [comment]
@salionPL wazne ze browar sie pokazal na przecenie

**Comment by salionPL** [comment]
Dzisiaj się pokazał, a jak jutro czteropak się nie pokaże? :fearful: Trzeba to poprawić, bo inaczej marny los abstynenta nas czeka ;)

**Comment by krystian3w** [comment]
Szkoda, że w Chrome nie działa dom inspector, można by szybciej namierzyć.

**Comment by krystian3w** [comment]
@MajkiIT może wywalmy to:

`biedronka.pl##.position10x1`

`biedronka.pl#@#.position10x1` @salionPL i raczej już 4-pak nie ucieknie.

**Comment by krystian3w** [comment]
`##.position10x1` - to też na głównej wycina wyszukiwarkę sklepów...
 
![obraz](https://user-images.githubusercontent.com/35370833/57966985-6d0b0600-7959-11e9-925b-33b2998c13d1.png) |
--- |

**Comment by MajkiIT** [comment]
@xxcriticxx @krystian3w @salionPL Dziekuję
