### ISSUE TITLE
jurajska.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13422]
![Screenshot_20190519_123500](https://user-images.githubusercontent.com/36385327/57981007-a3688400-7a32-11e9-8dc2-dc4279339bae.png)

**Comment by krystian3w** [comment]
@hawkeye116477  próbować naprawiać to drzewko, niby można takie coś zrobić ale jak coś dopiszą to się może bardziej `rozpierniczyć`.

![obraz](https://user-images.githubusercontent.com/35370833/58115819-3227fd00-7bfb-11e9-81de-21b0028be2eb.png)
