### ISSUE TITLE
pecetowicz.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13438]
![Screenshot_20190521_001445](https://user-images.githubusercontent.com/36385327/58055291-95fbe880-7b5d-11e9-9ac3-e2d3bd58bae9.png)

**Comment by krystian3w** [comment]
@hawkeye116477  nie lepiej przerobić może ten filtr do "Zajebistej Czcionki" 3.X/4.X/5.X?

Może jest więcej przypadków, że są w linku a nie obok luzem nieklikalne?

`pl##a .fa-twitter.fa` - wtedy nie znika z przycisku logowania ale nie mierzyłem skuteczności na cały polski internet.

**Comment by krystian3w** [comment]
Co do reklamy i anty-adblock to widać się obrazili że im naprawiliśmy problem z zbyt mocnym wycinaniem?
