### ISSUE TITLE
mvno-gsm.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13441]
https://mvno-gsm.pl/
![Screenshot_20190521_002018](https://user-images.githubusercontent.com/36385327/58055518-4669ec80-7b5e-11e9-915e-e9dc33fcf399.png)

https://mvno-gsm.pl/busuu-w-plusie/
![Screenshot_20190521_002053](https://user-images.githubusercontent.com/36385327/58055565-64cfe800-7b5e-11e9-9718-9ba612caff19.png)
![Screenshot_20190521_002109](https://user-images.githubusercontent.com/36385327/58055566-64cfe800-7b5e-11e9-8150-66d5b7f74e86.png)

**Comment by krystian3w** [comment]
Jeszcze anty-adblock aka https://github.com/MajkiIT/polish-ads-filter/issues/12184 / https://github.com/MajkiIT/polish-ads-filter/issues/13027 - znów neutralizowany tylko skryptem w AdGuard.

**Comment by xxcriticxx** [comment]
@krystian3w open again?

**Comment by krystian3w** [comment]
Nie trzeba jak się jeszcze trochę nazbiera to pomyślę nad filtrem "sieciowym" tzw. "`generichide`" i przetestuję jak sprawdza się skrypt podany w #13027
