### ISSUE TITLE
kliknijwzdrowie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13443]
https://kliknijwzdrowie.pl/swiatowy-dzien-pszczol-dlaczego-warto-dbac-o-pszczoly/
Ukrywa artykuł
![Screenshot_20190521_055016](https://user-images.githubusercontent.com/36385327/58067088-5993b100-7b8c-11e9-9df6-63e14fdfd6f8.png)

Reklamy
https://kliknijwzdrowie.pl/
![Screenshot_20190521_055100](https://user-images.githubusercontent.com/36385327/58067170-ad05ff00-7b8c-11e9-951f-24a1ccdf4caa.png)
![Screenshot_20190521_055114](https://user-images.githubusercontent.com/36385327/58067171-ad9e9580-7b8c-11e9-9187-d6b2a58eae9f.png)
![Screenshot_20190521_055127](https://user-images.githubusercontent.com/36385327/58067173-ad9e9580-7b8c-11e9-8577-999510c935af.png)
![Screenshot_20190521_055140](https://user-images.githubusercontent.com/36385327/58067174-ad9e9580-7b8c-11e9-85ed-4de21e9fcc43.png)
![Screenshot_20190521_055156](https://user-images.githubusercontent.com/36385327/58067175-ad9e9580-7b8c-11e9-8fa2-ef208fd72905.png)
![Screenshot_20190521_055208](https://user-images.githubusercontent.com/36385327/58067176-ae372c00-7b8c-11e9-9f9e-318770c0536a.png)
![Screenshot_20190521_055219](https://user-images.githubusercontent.com/36385327/58067177-ae372c00-7b8c-11e9-851b-85784e457cb7.png)
![Screenshot_20190521_055229](https://user-images.githubusercontent.com/36385327/58067178-ae372c00-7b8c-11e9-8587-1cbe83f63287.png)

**Comment by garggul** [comment]
> xMaap :
>
> https://kliknijwzdrowie.pl/swiatowy-dzien-pszczol-dlaczego-warto-dbac-o-pszczoly/
> Ukrywa artykuł
> (Screenshot)

Nie te repo, psute przez `Fanboy’s Social Blocking List`, odpowiednie repo: https://github.com/ryanbr/fanboy-adblock/issues.

**Comment by krystian3w** [comment]
To może i zrób pr usuwający plik i sekcje bugi Fanboy...

**Comment by garggul** [comment]
Nie zajmuję się na codzień socjalami, jak widać, swój komentarz https://github.com/MajkiIT/polish-ads-filter/issues/13443#issuecomment-494272963 edytowałem niepotrzebnie, bo moja pierwsza wersja komentarza była:

> Nie to repo, psute przez Fanboy’s Social Blocking List, odpowiednie repo: https://github.com/ryanbr/fanboy-adblock/issues (chyba, że to jest też naprawianie gdzieś w polskich socjalach).

Bo coś mi świtało, że to jest naprawiane w polskich socjalach, ale potem się rozmyśliłem i usunąłem fragment `(chyba, że to jest też naprawianie gdzieś w polskich socjalach)`, a jednak "pierwsza myśl" była dobra...

**Comment by krystian3w** [comment]
No jest bo staramy się do 8 dni robić PR a tak to czasem z 15 dni naprawia Rayan / Khrin.
Poza tym pewnie różnie dodatek zasysa filtry i może rzadziej bazę...?
