### ISSUE TITLE
se.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13449]
Ukrywa wideo
https://www.se.pl/wiadomosci/polska/jasnowidz-jackowski-ujawnia-czy-hitler-przezyl-ii-wojne-swiatowa-to-szokujace-aa-LmRi-pfVC-DVBM.html
https://superseriale.se.pl/m-jak-milosc/koniec-m-jak-milosc-artur-rogowski-znow-bedzie-ojcem-wzruszajaca-chwila-na-slubie-uli-aa-YZGm-VyHp-cAS2.html

**Comment by garggul** [comment]
Bruździ: 
https://github.com/MajkiIT/polish-ads-filter/blob/6279a3c55ba2c575aadb1459229547abc15170f7/polish-adblock-filters/adblock.txt#L2388

Pomaga w Moje Filtry: `www.se.pl,superseriale.se.pl#@#.video`
Na listę do filtra pewnie pójdą kolejne wykluczenia: `~www.se.pl,~superseriale.se.pl`

**Comment by krystian3w** [comment]
To i pewnie Fanboy znów też psuje. Jak dla mnie raczej teraz do wywalenia.
