### ISSUE TITLE
antyweb.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#13451]
Social
![scr-1558437520-001](https://user-images.githubusercontent.com/9846948/58091847-f5dca880-7bca-11e9-8f7f-eb177595e735.png)

```
antyweb.pl##.box-social-counter
```

PS
Wróciłem do Adguarda 😎

**Comment by garggul** [comment]
> FadeMind :
> 
> PS
> Wróciłem do Adguarda 

hehe może dlatego bo na WP ciągle reklamy i błędy?, a ponoć AdGuard ogarnia reklamy na WP (chociaż ja jeszcze nie testowałem).

**Comment by krystian3w** [comment]
Ogarnęli BSOD 😂.

**Comment by FadeMind** [comment]
> ponoć AdGuard ogarnia reklamy na WP

Ogarnia skutecznie. 

> Ogarnęli BSOD 😂.

Póki co 😁

**Comment by krystian3w** [comment]
Ten filter nie chywci?

**Comment by krystian3w** [comment]
Tak, to na 90% problem z nadpisaniem CSS strony:

`pl##.group.box-social-counter`

https://github.com/MajkiIT/polish-ads-filter/blob/0b3ef9d878340e0834d3f9882cf0d90553f6421e/adblock_social_filters/adblock_social_list.txt#L506

**Comment by krystian3w** [comment]
>  a ponoć AdGuard ogarnia reklamy na WP (chociaż ja jeszcze nie testowałem).

Lepsze skrypty, tyle ile się da w replace z `display: block` na `display: none`.

**Comment by krystian3w** [comment]
O mam, to winy @olegwukr... jakiś fail na anty-adblock...
