### ISSUE TITLE
wgospodarce.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13459]
Nie działa przewijanie strony.

**Comment by krystian3w** [comment]
@adamwr:

```
​http://static.wgospodarce.pl/snippy/64d8e47840583fec8352336b1301a949.css
```

`||static.wgospodarce.pl/snippy/64d8e47840583fec8352336b1301a949.css$stylesheet`

Jak coś wycwanili się i plik otwiera Google.
