### ISSUE TITLE
digitmedia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13464]
![Screenshot_20190522_112739](https://user-images.githubusercontent.com/36385327/58163668-abb7fd80-7c84-11e9-854a-a41ca01bff7c.png)

**Comment by krystian3w** [comment]
duplicate of #13455 

raczej nie padło ofiarą nieporozumienia: https://github.com/MajkiIT/polish-ads-filter/blob/ae994f07d1e4cff44eba2ea723acf20adbd29e2f/cookies_filters/adblock_cookies.txt#L417

**Comment by xMaap** [comment]
To nie wiem dlaczego się pojawiło drugi raz.
