### ISSUE TITLE
studentbeans.com/pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13469]
Social + cookies
![Screenshot_20190522_181205](https://user-images.githubusercontent.com/36385327/58190601-2e5caf00-7cbd-11e9-95f4-bc4f931ae2a4.png)

**Comment by xMaap** [comment]
https://www.studentbeans.com/student-discount/pl/keeper/code-30-znizka-dla-studentow-e7329208-c7e3-4de2-88bb-b45ce2fc22ee
![Screenshot_20190522_181407](https://user-images.githubusercontent.com/36385327/58190738-6f54c380-7cbd-11e9-9a12-993cb8df0800.png)

**Comment by krystian3w** [comment]
Mam nadzieje, że to będzie dłużej stabilne niż 1 dzień:

```
##.single-offer > .single-offer__details + aside > ul > li:nth-of-type(-n+2), div[style="text-align:center"] > a[name="Student Beans"] + ul > li
```
