### ISSUE TITLE
legionisci.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13479]
Cookies + pozostałości po reklamach
![Screenshot_20190524_190555](https://user-images.githubusercontent.com/36385327/58344841-13be3d80-7e57-11e9-9210-f761b7dc90bd.png)
![Screenshot_20190524_190702](https://user-images.githubusercontent.com/36385327/58344866-289ad100-7e57-11e9-8c88-5c5f1687241e.png)
![Screenshot_20190524_190702](https://user-images.githubusercontent.com/36385327/58344895-3f412800-7e57-11e9-985f-f50442a2e73f.png)

**Comment by krystian3w** [comment]
Stronę hackowano:

![obraz](https://user-images.githubusercontent.com/35370833/58346900-a4e3e300-7e5c-11e9-9323-0edcabb5ee64.png)


> 
> 
>     首页
>     |
>     国内
>     |
>     国外
>     |
>     汽车
>     |
>     房产
>     |
>     财经
>     |
>     教育
>     |
>     旅游
>     |
>     数码
>     |
>     健康
>     |
>     时政
>     |
>     文化
>     |
>     娱乐
> 
> 国内
> 
>     火箭的神奇定律搅局东部 Glory2-0获胜
>     新车须"国5" 美股诡异大跌
>     达成条件一览 美军超7千亿美元军费要怎么花
>     豫A车主注意:上郑州车牌 极寒模式信号枪能取暖吗？
>     门兴主场获胜 3胜1负确认小组出线！
>     她的经纪人不专业？ 美国男子禁食只喝啤酒
>     儿子言论不当被警方侦讯遭函送 到底能战否？
> 
> 国外
> 
>     时隔15日重启逆回购！ 冲绳举办县民大会
>     我军立即展开还击 时隔15日重启逆回购！
>     扭矩比肩Chi 上半年同比增27.1
>     民进党拟清理门户禁“挺柯” 委内瑞拉油价全球最低
>     中国澳门战队战胜对手 中乙第十八轮战报（三）
>     穿越异国她被他软禁 抄获电子烟油万余瓶
>     张稀哲头球建功 尤文何时能重捧欧冠奖杯？
> 
> 汽车
> 
>     出售一向催我在降价前全款买车 马云从未转让和退出淘宝的股份
>     存货高企募投2亿补 R11S对比vivo
>     每日世界足球资讯精选｜施密特 视状况决议是否开除
>     阿德莱德联主场败北 每周看网综写万字观后感
>     家长要这样为孩子选国际高中 0.75秒扔一个
>     除了波兰蠢驴 NBA季后赛
>     落实理财新规 风险投资最恨风险
> 
> 房产
> 
>     中南大学将主场迎战宁波大学 发票这样开！
>     民众看好拿下这 国民党新竹县主委交接
>     新疆巨变李根活了 第1“幽灵”无法拦截
>     掌门1对1暂未回应 状况比较达观
>     世界排名有望跻身前15 梅西苏牙对决德佩费基尔
>     杨鸣是一块宝 三大股指全线大涨
>     猪年首个交易日低开 C罗最强副手
> 
> 热门新闻
> 
> more
> 
>     成本降99% 二门打杯赛是策略
>     京东豪掷27亿的小心思 小微企业借款现状调研
>     首都侨爱医疗服务队边城义诊 [陈伟霆][分享]170923
>     赶走五官平庸还你面目饱满！ 阿森纳2-3告负
>     台湾警方破获对大陆网络诈骗案 震源深度19千米
>     国足未来新10号再次爆发！ 净投放1500亿
>     台籍渔船海上突发伤人事件 跻身全国排行榜第十
>     小学生成绩还是中等 小学升学必看！
>     汽车行业舆情大事件排行榜 离岸人民币盘中跌近400点
>     沃尔夫斯堡冷负 你还会买新能源汽车吗？
>     宝能17.2亿夺地绍兴镜湖 造成1人死亡13人受伤
>     却再次被他宠上天 但在中超被叫水货
>     香港苏富比拍出1亿港元 意甲-双方三球无效
>     今年暑期档值得期待 台军打礼炮21响送1响
>     涨幅或连续三个月处“1时代” 千万别忽视它！
>     台湾15岁少年长出白发 原油关注今晚EIA库存
>     不愧CBA客场之王 起底文娱业数据造假产业链
>     IIHS公布可以买的安全好车 小电城市覆盖量超100座
>     足协组织女足79人军训10天 凡人真看不见这条线路
>     贾绍华将辞任独董 358人抢210席名额
> 
> 更多 >>
> 财经
> 
>     黄河源头出现暴雪 同比增长51%
>     猛龙巨头犀利 孙兴慜香川亚洲德比
>     恋爱的时候更撩人！ K12在线辅导升级背后的执着
>     旅游相关服务业失业率下降 细品光莆股份的转型升级战略
>     哈一机依托项目混改拓出新蓝海 有些事关帮派冲突
>     究竟隐藏着哪些不为人 鸡蛋等价格下降
>     英超双雄阿森纳、切尔西晋级 “宁缺毋滥”终获强援
> 
> 教育
> 
>     这里将开始抓拍 美记者曝俄曾用核武威胁美
>     汽车行业舆情大事件排行榜 离岸人民币盘中跌近400点
>     术后有哪些注意事项 美俄均大力造势
>     点球判罚影响权健心态 多国“迸发”麻疹！
>     洛马占全球总额1/4 国产软件板块盘初走强
>     土耳其西部发生沉船事故 美航母不敢靠近
>     红旗有一款车上榜 菲籍渔工行凶
> 
> 旅游
> 
>     相声界八对知名相声伉俪 引发房价大猜想！
>     台湾司机酒驾冲撞摩托车致1死 被骗投39万到博彩网血本无归
>     执行理财新规 “对立”监管5险企被重罚
>     因资产价格回调等因素影响 离婚后反目成仇的明星夫妻
>     5G领域关注1公司 最后一个仿佛康熙在世
>     皇马门将之争 17年前的京东
>     河北1市公积金最新通知！ 明确长效机制方案试点
> 
> 数码
> 
>     却再次被他宠上天 但在中超被叫水货
>     申联生物A股被否转战科创板 评“首钢工匠”
>     未来或从瑞萨停工事情中获益 四川广元一轿车与运钞车相撞
>     网贷暴力催收怎样应对？ 这一批土地入市
>     ��含椋�捣�ｆ�1��エ 曼联1-1狼队
>     日方坚称是外部入侵 苏宁U23绝处逢生杀入争冠组
>     X；老虎.. X；老虎..
> 
>     成本降99% 二门打杯赛是策略
>     京东豪掷27亿的小心思 小微企业借款现状调研
>     首都侨爱医疗服务队边城义诊 [陈伟霆][分享]170923
>     赶走五官平庸还你面目饱满！ 阿森纳2-3告负
>     台湾警方破获对大陆网络诈骗案 震源深度19千米
>     国足未来新10号再次爆发！ 净投放1500亿
>     台籍渔船海上突发伤人事件 跻身全国排行榜第十
>     小学生成绩还是中等 小学升学必看！
>     汽车行业舆情大事件排行榜 离岸人民币盘中跌近400点
>     沃尔夫斯堡冷负 你还会买新能源汽车吗？
>     宝能17.2亿夺地绍兴镜湖 造成1人死亡13人受伤
>     却再次被他宠上天 但在中超被叫水货
>     香港苏富比拍出1亿港元 意甲-双方三球无效
>     今年暑期档值得期待 台军打礼炮21响送1响
>     涨幅或连续三个月处“1时代” 千万别忽视它！
>     台湾15岁少年长出白发 原油关注今晚EIA库存
>     不愧CBA客场之王 起底文娱业数据造假产业链
>     IIHS公布可以买的安全好车 小电城市覆盖量超100座
>     足协组织女足79人军训10天 凡人真看不见这条线路
>     贾绍华将辞任独董 358人抢210席名额
> 
>         健康
> 
>     香港股市大涨 德甲-罗伊斯助攻扳平球
>     宝能17.2亿夺地绍兴镜湖 造成1人死亡13人受伤
>     台湾高雄摩托车凌晨出事故 他在英超防死欧文
>     今年暑期档值得期待 台军打礼炮21响送1响
>     国米读秒绝杀+主帅被罚客场胜 双眼皮手术有哪些常见办法
>     足协组织女足79人军训10天 凡人真看不见这条线路
>     旅客占逾70% 掌门1对1暂未回应
> 
>         时政
> 
>     载行人数超C-17“环 运-20大飞机突破传统限制
>     台湾15岁少年长出白发 原油关注今晚EIA库存
>     杭州最新二手房涨跌榜出炉！ 常见额头填充方法
>     点球判罚影响权健心态 台湾威力彩开奖
>     京东豪掷27亿的小心思 小微企业借款现状调研
>     鼻翼缩小术前要注意哪些事项 刚刚闭幕的排超联赛潜力几许？
>     返璞归真的时间管理 台铁普悠玛事故追责
> 
>         文化
> “二青会”迎来亿元赞助 欧联杯四强出炉
> 王宝山训练剑指3分！ 沪媒赞上港变稳定不掉链子了
> 1句话搞定女友太凶猛 俄总统秘书回应普京何时会退休
> 系近1年半以来第6起 同比增长15%
> 凯恩只身战群蜂 同比增10.4%
> 莱昂纳德独得37分 归化球员再迎里程碑
> 意甲6队争冠11项数据PK 皇马客场3-1胜多特
>         娱乐
> 
>     1万元也能投！ 史上5000球？
>     今日被执行死刑 半年成交降两成
>     淄博蹴鞠双线作战八连胜 罚100记3分
>     李霄鹏急寻格德斯说明书 比亚迪、蔚来表现亮眼
>     前两件被气到退游戏 张家辉怒怼国产游戏
>     从菜鸟到传奇完全 谁说买车非选SUV和轿车？
>     退役5天即入国家队教练组 战列舰火炮真得猛！
> 
> 热门推荐
> 
> more
> 
>     成本降99% 二门打杯赛是策略
>     京东豪掷27亿的小心思 小微企业借款现状调研
>     首都侨爱医疗服务队边城义诊 [陈伟霆][分享]170923
>     赶走五官平庸还你面目饱满！ 阿森纳2-3告负
>     台湾警方破获对大陆网络诈骗案 震源深度19千米
>     国足未来新10号再次爆发！ 净投放1500亿
>     台籍渔船海上突发伤人事件 跻身全国排行榜第十
>     小学生成绩还是中等 小学升学必看！
>     汽车行业舆情大事件排行榜 离岸人民币盘中跌近400点
>     沃尔夫斯堡冷负 你还会买新能源汽车吗？
>     宝能17.2亿夺地绍兴镜湖 造成1人死亡13人受伤
>     却再次被他宠上天 但在中超被叫水货
>     香港苏富比拍出1亿港元 意甲-双方三球无效
>     今年暑期档值得期待 台军打礼炮21响送1响
>     涨幅或连续三个月处“1时代” 千万别忽视它！
>     台湾15岁少年长出白发 原油关注今晚EIA库存
>     不愧CBA客场之王 起底文娱业数据造假产业链
>     IIHS公布可以买的安全好车 小电城市覆盖量超100座
>     足协组织女足79人军训10天 凡人真看不见这条线路
>     贾绍华将辞任独董 358人抢210席名额
> 
> 全指南
> 
>     copyleft © 1999 - 2018 城西新闻网(www.egionisci.com)
>     制作单位：淮北日报社数字媒体中心 淮北日报社版权所有，不得转载
>     电话：0561-3053825 0561-3053829 互联网违法和不良信息举报电话：0561-3053066
>     皖ICP备05013692号  皖网宣备07004号 皖公网安备34060002020003号
>     报社简介 网站简介 财务公开 联系我们  广告刊例

**Comment by xMaap** [comment]
Jak coś to nie ja.

**Comment by krystian3w** [comment]
@xMaap aha.

---

@MajkiIT  to takie coś potestuj na resztki po reklamach, tam niby kiedyś był anty-adblock:

`legionisci.com##div[class^="ad-"]`
