### ISSUE TITLE
poczta.o2.pl

### ISSUE THREAD

**Issue by DiabloPiotr** [MajkiIT/polish-ads-filter#13471]
### Link bezpośredni
https://poczta.o2.pl

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Włączony Adblock

### Moja konfiguracja
**Przeglądarka internetowa:**
chrome
**Rozszerzenia i skrypty:**
nano adblocker + nano defender
**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda

Po wejściu na stronę, automatycznie robi się ona cała biała

**Comment by xxcriticxx** [comment]
duplicate https://github.com/MajkiIT/polish-ads-filter/issues/13456
