### ISSUE TITLE
Pi-hole - blokowanie nie działa

### ISSUE THREAD

**Issue by Jeder321** [MajkiIT/polish-ads-filter#13470]
Cześć, dzisiaj zainstalowałem Pi-hole na swojej malinie, zainstalowałem również wszystkie mi potrzebne filtry, jednak zauważyłem, że na polskich stronach w ogóle mi nie filtruje. Po przeglądnięciu list mam takie wrażenie, że są one źle skonstruowane, wszystkie listy które mi zainstalowało przy instalacji mają tylko linki, a polskie listy mają strukturę pliku hosts. Czy to na pewno tak działa?

**Comment by MajkiIT** [comment]
A masz w panelu pihole zablokowane domeny ?

**Comment by Jeder321** [comment]
Tak, tutaj jest lista najczęściej blokowanych 
![image](https://user-images.githubusercontent.com/12257652/58200044-20655900-7cd2-11e9-9112-3dce64950bff.png)

**Comment by MajkiIT** [comment]
czyli blokuje. Lista ma taką konstrukcje, bo można dodać też ją do innych blokerów. Pamiętaj, że to blokuje domeny, a nie elementy na stronie.

**Comment by Jeder321** [comment]
Tylko, że na stronach typu cnn czy theverge wszystko mi blokuje, pokazuje np, napis AD zamiast reklamy, a na takim wp.pl czy onecie wszystko przechodzi

**Comment by MajkiIT** [comment]
Bo polska to królestwo reklam. Reklamy są serwowane np. z domeny www.xyz.pl/ads/image.jpg a wtedy nie można zablokować tego bez strat. Na CNN reklamy zapewne są serwowane z adresu adv.cnn.com

**Comment by Jeder321** [comment]
Czyli bez ublocka się nie obejdzie?

**Comment by MajkiIT** [comment]
@Jeder321 to sprawdź czy zablokuje ci taką domenę:
```
 Match found in https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt:
   shoplov.in
 Match found in https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/all_ads_filters.txt:
   shoplov.in
```

**Comment by Jeder321** [comment]
Zablokowało

**Comment by MajkiIT** [comment]
@Jeder321 no to polskie filtry działają.

**Comment by Jeder321** [comment]
No to chyba jest tak jak mówisz, trzeba będzie dowalić ublocka
