### ISSUE TITLE
sochaczewianin.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13484]
Reklamy + social
![Screenshot_20190524_210716](https://user-images.githubusercontent.com/36385327/58351066-fba2ea00-7e67-11e9-9c58-9cac822b3045.png)
![Screenshot_20190524_210820](https://user-images.githubusercontent.com/36385327/58351104-1aa17c00-7e68-11e9-8a44-424b9dfcbaa5.png)

**Comment by krystian3w** [comment]
Cookies też.
