### ISSUE TITLE
ozptd.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13486]
![Screenshot_20190524_211015](https://user-images.githubusercontent.com/36385327/58351207-6522f880-7e68-11e9-9209-492e0b7cfcc3.png)
![Screenshot_20190524_211046](https://user-images.githubusercontent.com/36385327/58351222-72d87e00-7e68-11e9-9160-df1a14f23d43.png)

**Comment by xxcriticxx** [comment]
@xMaap not cookies
