### ISSUE TITLE
jbzdy.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13497]
![Screenshot_20190524_214633](https://user-images.githubusercontent.com/36385327/58352984-833f2780-7e6d-11e9-97a8-b272dd7c8c43.png)

**Comment by krystian3w** [comment]
Załatane... https://github.com/olegwukr/polish-privacy-filters/commit/e60a9b76fc57fad7ded4ce475a406355b1b8491b
