### ISSUE TITLE
FDB.pl

### ISSUE THREAD

**Issue by klocus** [MajkiIT/polish-ads-filter#13517]
### Zrzut ekranu
![Zrzut ekranu 2019-05-25 o 16 00 30](https://user-images.githubusercontent.com/2962987/58370383-3ce9d700-7f06-11e9-83ed-a6b545c335df.png)

### Link bezpośredni
https://fdb.pl/

### Moja konfiguracja
**Przeglądarka internetowa:**
Opera (wbudowany w Operę adblocker)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Reklamy się nie wyświetlają, ale pozostaje pusty box
```
<div id="legacy-ads-bilboard" class="ads ads-bilboard1 loaded">
```

**Comment by krystian3w** [comment]
Jak dla mnie lepiej przejść na uBlock Origin, bo bloker Opery widać nie rozumie filtra:

`pl##.ads`

W takiej formie...

https://github.com/MajkiIT/polish-ads-filter/blob/55b6f29297372a3f8eadf4eb6d0313380c5a68ec/polish-adblock-filters/adblock.txt#L190

**Comment by klocus** [comment]
@krystian3w dokładnie z tego powodu zamknąłem wątek, bo zobaczyłem, że to nie wina filtrów, lecz Opery.
