### ISSUE TITLE
Sponsorzy

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#13521]
Co sądzicie o `https://github.com/sponsors`? @xxcriticxx zainteresowany?

**Comment by xxcriticxx** [comment]
@hawkeye116477 towyglonda na kopjowanie patrona

**Comment by krystian3w** [comment]
My nie mamy programu...

**Comment by krystian3w** [comment]
Można by to na Polskiej Zgodzie uruchomić, może ktoś zapłaci.

**Comment by xxcriticxx** [comment]
jest juz donate na froncie repo https://paypal.me/pools/c/87zNJ8OJ3I

**Comment by hawkeye116477** [comment]
Raczej do PCZ nie przewiduję donacji. No chyba, że @krystian3w chce uzbierać na konto deweloperskie do MS Store (Edge) albo jakieś Safari czy coś.
A @MajkiIT nie zainteresowany albo @xxcriticxx nie potrzebuje na wino :smiley:?

**Comment by krystian3w** [comment]
> jest juz donate na froncie repo

No i nic więcej się nie zrobi, chyba że MajkiIT uruchomi w tym repozytorum polski "uBlock Origin".

Raczej CSS, nie jest programem ani nie można za niego uznać skryptozakładki niedziałające bez uBlock Origin resources.

**Comment by xxcriticxx** [comment]
Są lepsze zeczy na które można zrobić zbiórkę nisz konto dev na edge

**Comment by hawkeye116477** [comment]
My tam nic specjalnego nie mamy, więc może by się udało, ale trzeba byłoby specjalnie kupić MacBooka i jeszcze co roku płacić haracz 400 zł dla :apple: No to Microsoft wychodzi znacznie taniej, 60 zł tylko raz, ale skoro będzie można instalować z Chrome Web Store, no to nie opyli się :smile:.

**Comment by krystian3w** [comment]
są ziemniaki 🥔, jest melasa...
