### ISSUE TITLE
gtaforum.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#13526]
Anty AdBlock

### Zrzut ekranu
![image](https://user-images.githubusercontent.com/18230443/58383310-6d4c7680-7fd5-11e9-9e1a-5b5c59d1be38.png)

### Link bezpośredni
https://gtaforum.pl

**Comment by krystian3w** [comment]
Ja nie mam, wyłącz swoje niestandardowe listy i sprawdź ponownie.

**Comment by krystian3w** [comment]
`##.ipsDialog_medium.ipsDialog, .ipsModal`

**Comment by RikoDEV** [comment]
@krystian3w Wejdź w przykładowy temat na wylogowanym koncie. https://gtaforum.pl/temat/10312-nowy-server-gitrp-nabor-na-lsc-ems-lspd-942395172

**Comment by krystian3w** [comment]
I co niby tam nie działa wtedy `pl##.ipsDialog_medium.ipsDialog, .ipsModal`? Aż usuwają wpisy z forum?

**Comment by RikoDEV** [comment]
Bardziej chłodziło mi o ten modal.

**Comment by krystian3w** [comment]
Tam znalazłeś inny modal?

**Comment by RikoDEV** [comment]
Zablokowałeś już wszystkie. 😄

**Comment by RikoDEV** [comment]
![image](https://user-images.githubusercontent.com/18230443/58383597-06c95780-7fd9-11e9-9fd5-31b8e5d99b09.png)

**Comment by krystian3w** [comment]
Odpada, bo wraca anty-adblock...

**Comment by krystian3w** [comment]
`##center:-abp-has(> .adsbygoogle)` wtedy strona nie kuma że zablokowano reklamy Google.
