### ISSUE TITLE
co naprawiają te generichide:

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#13528]
https://github.com/MajkiIT/polish-ads-filter/blob/55b6f29297372a3f8eadf4eb6d0313380c5a68ec/polish-adblock-filters/adblock.txt#L3690

https://github.com/MajkiIT/polish-ads-filter/blob/55b6f29297372a3f8eadf4eb6d0313380c5a68ec/polish-adblock-filters/adblock.txt#L3705

https://github.com/MajkiIT/polish-ads-filter/blob/55b6f29297372a3f8eadf4eb6d0313380c5a68ec/polish-adblock-filters/adblock.txt#L3707

https://github.com/MajkiIT/polish-ads-filter/blob/55b6f29297372a3f8eadf4eb6d0313380c5a68ec/polish-adblock-filters/adblock.txt#L3729

https://github.com/MajkiIT/polish-ads-filter/blob/55b6f29297372a3f8eadf4eb6d0313380c5a68ec/polish-adblock-filters/adblock.txt#L3732

https://github.com/MajkiIT/polish-ads-filter/blob/55b6f29297372a3f8eadf4eb6d0313380c5a68ec/polish-adblock-filters/adblock.txt#L3735-L3736

**Comment by MajkiIT** [comment]
@krystian3w na moje oko to ADB . Jedynie katowickisport nie jestem przekonany.

**Comment by MajkiIT** [comment]
@krystian3w Ktoś rozwija filtry adblock?

**Comment by krystian3w** [comment]
`katowickisport` ten ma jakieś przekierowanie na inną domenę:

```
https://sportdziennik.com/
```

**Comment by krystian3w** [comment]
> Ktoś rozwija filtry adblock?

`commit` od bogachenko to jego wizja rozwijania filtrów REK bez `userscript.js` "makaronowe spaghetti", a tak to wolałem się upewnić czy może nie powinny migrować do Olega.

**Comment by xxcriticxx** [comment]
Olek ostatnio ma opóźnienie z dodawaniem PR

**Comment by krystian3w** [comment]
Najfajniejsze, że mogę ukryć swoje posty jako obrażanie / spam / przestarzałe / rozwiązane:


![obraz](https://user-images.githubusercontent.com/35370833/58386292-be706080-7ffd-11e9-9372-009623f523ca.png) |
--- |

Wcześniej tego nie zauważyłem.

**Comment by MajkiIT** [comment]
Może warto pchać to w jedną listę. Nie wiem czy jest sens to dublować?

**Comment by krystian3w** [comment]
To spróbuję u Olega zaproponować dodanie tych na fakt ("Onet"?) i TVN.
