### ISSUE TITLE
host file windows

### ISSUE THREAD

**Issue by BondasH** [MajkiIT/polish-ads-filter#13522]
Dodałem host z pihole do windows na 2 sposoby 127 i 0 
po uruchomieniu np. tvp vod żąda wyłączenia adblocka po usunięciu wpisów zaczyna działać normalnie.

nie zastosowałem żadnego adblocka ,ublocka w przeglądarce czysta przeglądarka czy jest jakaś możliwość w hoście blokować ten alert zabezpieczenia przed blokowaniem reklam

dokładniej chciałem przyblokować to.
0.0.0.0 api.deep.bi
0.0.0.0 gsi.gstatic.com 
0.0.0.0 myao.adocean.pl

ogólnie to dało by się przeżyć te kilka minut reklam ale nie jestem w stanie zaakceptować tego ze przez ładowanie się tych śmieci wszystko zwalnia o 70%

na androidzie wiem że jakiś czas temu sprawdzałem i dodawałem do hosta te reguły które widać wyżej i wszystko było w porządku na windows są alerty.

dzięki za ogromny wkład w pozbywaniu się tego syfu z przeglądarek ........

**Comment by xxcriticxx** [comment]
Problemem jest adocean to tworzy adbloka. Przepuszczając to bendziesz miał reklamy

**Comment by BondasH** [comment]
tak czy siak mam zablokowane bo używam nano adblocka , ale pytam z ciekawosci czy można ubić tą blokade adblock worning w host file 

czy jest to script a tego to żaden host nie załatwi.

**Comment by xxcriticxx** [comment]
Tylko scriptem dasz radę oszukać host file ma limity

**Comment by krystian3w** [comment]
I też zależy jak naprawiono problem z adblockami, czasem nie da się nic lepszego jak dopuścić plik JS:

```
@@.js$domain=...
```

Jak hosts wcześniej wytnie plik, to dopuszczenie uBO / NaA / ABP / AdBlock nie zadziała.

**Comment by BondasH** [comment]
to słabo troche,zrobiłem sobie małe exe własnie z vod tvp ale nie potrafie w nim umiescic adblocków a host 
w windows nie spełnia wymagań ponieważ po odpaleniu programu własnie wykrywa blokade reklam
niby mam premium na tvp vod i tych reklam jest bardzo mało ale i tak po zablokowamiu ich 100% szybciej wszystko chodzi

**Comment by xxcriticxx** [comment]
@BondasH nie wiem co tam kombinujesz ale musisz się kierować w stronę user scripts a nie exe

**Comment by BondasH** [comment]
nic to nie da kolego chyba ze zastąpie wszystki bbb na aaa, jutro ci podesle cała zawartość i sam zobaczysz
mam nadzieje ze cvxcvx to to samo

**Comment by xxcriticxx** [comment]
@BondasH sorry nie rozumiem
