### ISSUE TITLE
neonet.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#13535]
cookies

**Comment by krystian3w** [comment]
Nie widzę... @hawkeye116477  sprawdź.

**Comment by krystian3w** [comment]
@blocker999  a jak bez I don't care about cookies?

@Xmaap masz to może z Fanboy Cookie list?

**Comment by xMaap** [comment]
@krystian3w brak informacji o cookies.

**Comment by hawkeye116477** [comment]
@blocker999 Pora na złożenie nowego kompa?
