### ISSUE TITLE
gotujzmaka.blogspot.com

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#13538]
Reklamy.

**Comment by MajkiIT** [comment]
```
gotujzmaka.blogspot.com###HTML26
gotujzmaka.blogspot.com###HTML23
```

**Comment by hawkeye116477** [comment]
No trochę tego więcej.
`gotujzmaka.blogspot.com###HTML1, #HTML6, #HTML8, #HTML11, #HTML18, #HTML23, #HTML24, #HTML25, #HTML26` :smile:

**Comment by MajkiIT** [comment]
@hawkeye116477  no tak ... aż tak daleko nie zajechałem na tej stronie :D. Dzięki
