### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by Venom3x** [MajkiIT/polish-ads-filter#13565]
### Zrzut ekranu
https://i.imgur.com/aSqBs9H.png

### Link bezpośredni
https://sportowefakty.wp.pl/

### Moja konfiguracja
**Przeglądarka internetowa:** CHROME

**Rozszerzenia i skrypty:** Nano Adblocker + Nano Defender

**Listy filtrów:**
1. EasyList
2. POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. POL: Oficjalne polskie filtry przeciwko alertom o Adblocku
4. Polish Privacy Filters
5. Polskie Filtry RODO-Ciasteczkowe
6. NoCoin Filter List
7. Nano defender integration + Nano filters
8. Adblock Warning Removal List

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Po wyłączeniu listy "POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda" informacja o adblocku znika.

**Comment by krystian3w** [comment]
Tak tak, na razie naprawione w AdGuard base.
