### ISSUE TITLE
marketerplus.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13604]
![Screenshot_20190530_115836](https://user-images.githubusercontent.com/36385327/58625242-56a66800-82d2-11e9-93e6-dc1b272534f0.png)

**Comment by hawkeye116477** [comment]
@xMaap Ja tam widzę normalny pop-up. Sprawdź, która lista powoduje problem i zgłoś to odpowiedniej osoby.

**Comment by ggargul** [comment]
To błąd w Fanboy's Cookie List: https://github.com/ryanbr/fanboy-adblock/issues/1056
