### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1361]
Strona wykrywa adblocka, a co ciekawe u mnie ten problem występuje tylko w Chrome, w Firefoksie i Operze nie widzę tego.

Link - `http://www.komputerswiat.pl/nowosci/sprzet/2016/37/playstation-4-pro-i-nowe-playstation-4-pokazane-w-nowym-jorku.aspx`

![image](https://cloud.githubusercontent.com/assets/11742596/19538296/b5c9c62e-9653-11e6-90db-bd465c5a8b92.png)

Najprościej będzie "wyłączyć" ogólne reguły kosmetyczne:
`@@||komputerswiat.pl^$generichide`
i dodać tę żeby zablokować puste miejsce po reklamie:
`komputerswiat.pl##.adsense`
albo takie coś:
`komputerswiat.pl#@#.text_ads`
`komputerswiat.pl#@#.text_ad`
`komputerswiat.pl#@#.text-ad`
`komputerswiat.pl#@#.textAd`
`komputerswiat.pl#@#.text-ads`
`komputerswiat.pl#@#.text-ad-links`
`komputerswiat.pl#@#.pub_728x90`
`komputerswiat.pl#@#.pub_300x250m`
`komputerswiat.pl#@#.pub_300x250`
`komputerswiat.pl#@##admain`

Może da się to w jakiś inny sposób ominąć, bez wyłączania tych ogólnych reguł kosmetycznych, ale na razie nic lepszego nie wymyśliłem.

**Comment by xxcriticxx** [comment]
taki sam ad block jak na onecie?

**Comment by MajkiIT** [comment]
@F4z dzięki
