### ISSUE TITLE
noizz.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13625]
https://noizz.pl/ekologia/uschla-slynna-palma-przy-rondzie-de-gaullea-w-warszawie/xzytnxp
Social
![Screenshot_20190602_165307](https://user-images.githubusercontent.com/36385327/58763083-fecc6300-8556-11e9-9aac-619136ee543c.png)

Jeszcze ukrywa 

> Dalszy ciąg losów palmy będzie można śledzić na profilu "". 

Włączony
![Screenshot_20190602_165408](https://user-images.githubusercontent.com/36385327/58763096-30ddc500-8557-11e9-9adb-0914b314abd8.png)
Wyłączony
![Screenshot_20190602_165429](https://user-images.githubusercontent.com/36385327/58763097-34714c00-8557-11e9-926a-21eace4c4973.png)

**Comment by krystian3w** [comment]
Social na dev dodałem z 2 dni temu, link pewnie jest przekierowujący przez `gemius.pl` / `doubleclick.net` / `adform.net`.
