### ISSUE TITLE
autokult.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13627]
https://autokult.pl/33935,volvo-v60-kontra-mercedes-klasy-c-i-audi-a4-porownanie-najlepszych-kombi-klasy-sredniej-nizszej
Social
![Screenshot_20190602_171827](https://user-images.githubusercontent.com/36385327/58763411-954e5380-855a-11e9-87d5-2517855216f7.png)
![Screenshot_20190602_171843](https://user-images.githubusercontent.com/36385327/58763412-954e5380-855a-11e9-9a58-d2daefca0a48.png)

**Comment by xMaap** [comment]
@krystian3w Pojawia się
![Screenshot_20190603_035605](https://user-images.githubusercontent.com/36385327/58771295-995a8f80-85b3-11e9-9188-131c5d604d79.png)

I jakby można było ukryć ten napis
![Screenshot_20190603_035852](https://user-images.githubusercontent.com/36385327/58771412-5baa3680-85b4-11e9-84b3-ac3fb913385e.png)

**Comment by krystian3w** [comment]
A to już jest osobnym elementem, niestety mnie nie wskoczyła żadna galeria 2 z 4.

**Comment by krystian3w** [comment]
I podejrzewam że tekst na instagramie zostanie z Nano Adblockerem, za duże ryzyko wycinać każde title by ten 1 się nie pojawił.
