### ISSUE TITLE
portal.abczdrowie.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#13623]
https://portal.abczdrowie.pl/

Jak się kliknie na WIĘCEJ obok loga to rozwijane menu pojawia się na sekundę po czym znika. 

![scr-1559387037-001](https://user-images.githubusercontent.com/9846948/58747601-c4d36200-846d-11e9-88eb-57d97935982a.png)
![scr-1559387048-001](https://user-images.githubusercontent.com/9846948/58747602-c4d36200-846d-11e9-99b5-3129641487b6.png)

**Comment by krystian3w** [comment]
U mnie nie ma problemu, testować  z AdGauardem?

**Comment by krystian3w** [comment]
`@@||portal.abczdrowie.pl^$generichide`

`@@||portal.abczdrowie.pl^$jsinject`

Zobacz czy może któreś przywróci - jak `jsinject` to będzie musiał pomóc AdmaWr / F4z.

**Comment by FadeMind** [comment]
@krystian3w  `@@||portal.abczdrowie.pl^$generichide` zrobił robotę. Dzięki. Nie testowałem `jsinject` skoro `generichide` działa poprawnie

**Comment by krystian3w** [comment]
Spróbuję to jakoś wepchać do zgłoszeń AdGuard, `generichide` może sprawić że wrócą przy okazji przyciski do sociali "portalu zdrowie" jak nie mamy ich dociętych filtrami pod domenę `abczdrowie.pl##` lub `pl##`.

**Comment by krystian3w** [comment]
O mam, to winy @olegwukr... jakiś fail na anty-adblock...

**Comment by krystian3w** [comment]
OK jak dla mnie problem robi `EasyList Polish` - @easylistpolish dasz radę to naprawić i czy dodatkowo jakoś do ciebie to zgłaszać do repo / na mail?

@admawr  jak chcesz możesz śledzić postęp naprawy i najwyżej nadpisać wadliwy filtr po namierzeniu jak naprawa będzie zbyt długa.

**Comment by krystian3w** [comment]
`portal.abczdrowie.pl#@#div[style$="display: block;"]>*:not(.modal__body)`

Na takie coś może podmień sobie generichide @FadeMind.

**Comment by easylistpolish** [comment]
Hej, dzięki wielkie za zgłoszenie! Problem powinien zniknąć po aktualizacji Easylist Polish
