### ISSUE TITLE
Github po polsku...?

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#13624]
Nagle widzę:
- "20 sekund temu",
-  "1 minutę temu",
-  "16 godzin temu", 
- "wczoraj", 
- "przedwczoraj", 
- "3 dni temu".

**Comment by xMaap** [comment]
![Screenshot_20190601_230848](https://user-images.githubusercontent.com/36385327/58753624-4fde4780-84c2-11e9-916a-c462a1b40964.png)

Tylko to widzę po polsku.

**Comment by krystian3w** [comment]
No dziwne właśnie...

**Comment by hawkeye116477** [comment]
@krystian3w Ja mam po angielsku.

**Comment by xMaap** [comment]
Może ktoś się nudził albo Microsoft kazał przetłumaczyć.

**Comment by hawkeye116477** [comment]
Raczej beta-testy dla wybranych, pewnie wkrótce dadzą opcję zmiany języka jak na GitLabie (tam jest do wyboru język polski, ale mało jest przetłumaczone).

**Comment by xxcriticxx** [comment]
@krystian3w jestes wybrancem
