### ISSUE TITLE
tech.wp.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1362]
Puste miejsce po reklamach - `http://tech.wp.pl/`

![image](https://cloud.githubusercontent.com/assets/11742596/19558123/0816c038-96c9-11e6-9c90-aaa69c27cfab.png)

Na przykład:
`tech.wp.pl##[style][class="qd-US"]`

**Comment by MajkiIT** [comment]
@F4z dzięki
