### ISSUE TITLE
e-dym.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13632]
![Screenshot_20190602_232232](https://user-images.githubusercontent.com/36385327/58767566-62718300-858d-11e9-9793-971a19cc31a6.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 To chyba do ciebie ...

**Comment by hawkeye116477** [comment]
Nie widzę kurtyny, pewnie znowu pan Fanboy.

**Comment by krystian3w** [comment]
Coś takiego:

![obraz](https://user-images.githubusercontent.com/35370833/58806020-8d9fb500-8615-11e9-82c6-aeddab8ae41c.png)

**Comment by krystian3w** [comment]
Jak dla mnie niech sobie gmoku zgłosi błąd do fanboya i wymusi coś lepszego od:

docięcia `##.cp-popup-overlay` a np. `#@#.cp-popup`

**Comment by krystian3w** [comment]
Jak dla mnie raczej pop-up powinien zostać by ktoś nie przeżył podróży do sklepu bo mu pocztą / kurierem nie wyślą...
