### ISSUE TITLE
joemonster.org

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1363]
Baner na górze strony - `http://joemonster.org/`
![image](https://cloud.githubusercontent.com/assets/11742596/19571119/32697f72-96fd-11e6-8567-00da7c6070b3.png)

Na przykład:
`joemonster.org##a[onclick^="window.location.href='https://www.facebook.com/JoeMonster.org/"]`
lub
`joemonster.org##a[onclick^="window.location.href='https://www.facebook.com/JoeMonster.org/"] > img`

Oprócz tego baneru "Jesteśmy na Facebooku" czasami pojawia się też reklama.
![image](https://cloud.githubusercontent.com/assets/11742596/19571179/6a433fe6-96fd-11e6-95f5-7ea324fab58a.png)

Na przykład:
`joemonster.org##div[style="width: 750px; height: 200px; left: 0px; top: 0px;"]`
lub
`joemonster.org###bg > div:not([id])`

Jako ciekawostkę dodam, że w połączeniach widać zapowiadanego kilka miesięcy temu "UnBlock'a".
`http://antyweb.pl/unblock-polska-adblock/`
`http://www.cloudtechnologies.pl/`
`http://onaudience.com/`
![image](https://cloud.githubusercontent.com/assets/11742596/19572131/42c7076e-9701-11e6-9947-fe5ce1ef42d3.png)

Nie wiem czy na joemonster wyświetlane są reklamy przy jego użyciu*, bo sam "skrypt" wygląda tak `adBlock;` - `http://avangarde.unblock.onaudience.com/static/showad.js,` więc może sprawdzane jest czy korzysta się z adblocka.
Można jeszcze rozważyć dodanie takiej reguły `@@||avangarde.unblock.onaudience.com/static/showad.js$xmlhttprequest,domain=joemonster.org` bo po jej dodaniu nie widzę już tego baneru.

*Jest jeszcze zagnieżdżony skrypt, który zawiera w sobie słowo "unblock" - http://wklej.org/id/2920690/txt/
Ten sam/podobny skrypt dostępny jest też tutaj - `http://avangarde.unblock.onaudience.com/static/worker.js`
więc może w jakiś sposób jest to wykorzystywane.

Dodatkowo zauważyłem, że Adguard dla Windowsa pokazuje połączenia, których nie widzę w przeglądarce.
![image](https://cloud.githubusercontent.com/assets/11742596/19574744/ec5b17fc-970b-11e6-8f3b-05a310eb0838.png)

Jak do Adguarda dodam taką regułę:
`||avangarde.unblock.onaudience.com^`
to nie widzę tego baneru/reklam na górze strony, ale w przypadku uBlocka to nie działa.

**Comment by MajkiIT** [comment]
Ja dodałem przed chwilą 2 inne reguły, które też działają. A co do twojej wypowiedzi odnośnie unblock, to zerknę w wolnej chwili. Dziękuję.

**Comment by F4z** [comment]
Ok, dzięki.
Nie wiem jak u Ciebie, ale u mnie `joemonster.org###main_billboard` blokuje baner tylko na głównej stronie.
Jak przejdę tutaj - `http://joemonster.org/filmy` - to nadal mi się to wyświetla.

**Comment by xxcriticxx** [comment]
@F4z jaki browser?

**Comment by F4z** [comment]
Google Chrome

**Comment by xxcriticxx** [comment]
onaudience.com = Measure and monetize ad blocked traffic

**Comment by xxcriticxx** [comment]
script crazy konca nie widac

**Comment by MajkiIT** [comment]
@F4z @xxcriticxx 
Poprawiłem dzięki
