### ISSUE TITLE
wiadomosci-lodz.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13649]
![Screenshot_20190604_200955](https://user-images.githubusercontent.com/36385327/58903079-d1251c80-8704-11e9-9378-6102de6cf5aa.png)

**Comment by krystian3w** [comment]
Chyba pierwszy raz `##cookie-law-info-bar:not(body):not(html)` w brzydkim popupie...

**Comment by krystian3w** [comment]
@kiboke:

`###cookie-law-info-bar:not(body):not(html):not([class="cli-bar-popup cli-modal-content"])`

❓

**Comment by krystian3w** [comment]
@xxcriticxx, naprawione w PR do cookies, można zamknąć, kiboke kiedyś sobie zrobi poprawkę jak i fanboy, nie będziemy na nich tu czekać.
