### ISSUE TITLE
uBlock - polish-ads-filter ignorowany

### ISSUE THREAD

**Issue by genjusz** [MajkiIT/polish-ads-filter#1365]
![screenshot](http://www.drop.abneg.at/Screen-Shot-2016-10-21-12-47-27-3Rn8qSWdI6.png)

Macie pomysł dlaczego nie parsuje mi Waszego głównego pliku z filtrami :
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt
?

**Comment by MajkiIT** [comment]
Bo jest zintegrowana z Ublockiem w filtrach regionalnych

**Comment by genjusz** [comment]
👍  Dzięki ! 
wcześniej był tam jakiś totalnie nie aktualny filtr, dlatego nie zwróciłem uwagi

**Comment by xxcriticxx** [comment]
@genjusz znasz sie na javascript?

**Comment by genjusz** [comment]
@xxcriticxx - jestem bardziej deweloperem PHP, ale JavaScript też ogarniam.
Dlaczego pytasz ?

**Comment by xxcriticxx** [comment]
@genjusz szukamy kogos co by pomagal z javascriptem

**Comment by genjusz** [comment]
hmmm... a jakiś przykład w jakiego typu rzeczach potrzebujecie pomocy ?

**Comment by xxcriticxx** [comment]
niektore strony tak jak player.pl potrzebny jest script zeby ominac reklamy

**Comment by genjusz** [comment]
hmmmm... ok... a są jakieś wytyczne jak to zrobić, czy trzeba kombinować ? :)
Może jak spojrzę na przykłady rzeczy, które już działają to da mi to lepszy obraz na to, czy byłbym w stanie podołać...

**Comment by xxcriticxx** [comment]
@MajkiIT zagadaj jutro z @genjusz

**Comment by MajkiIT** [comment]
@xxcriticxx dzięki za pomoc

@genjusz chodzi nam o pomoc w rozwiązaniu problemu np. tutaj https://github.com/MajkiIT/polish-ads-filter/issues/1324 . Kiedyś działał w tym Reek i jego skrypt https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer.user.js /musisz znaleźć sekcje dla player.pl/ , ale Reek porzucił projekt i zostaliśmy z niczym. Zerkniesz na to?

**Comment by genjusz** [comment]
Wyjeżdżam teraz na urlop i niestety nie będę miał teraz czasu wgłębić się w temat.
Jeżeli Wam to nie przeszkadza, mogę mocniej przy tym pogrzebać gdzieś w drugiej połowie listopada. Na pierwszy rzut oka ciężko mi się zorietnować, czy uda mi się to ogarnąć.
