### ISSUE TITLE
Firefox zablokuje trackery internetowe

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#13654]
https://android.com.pl/news/226424-firefox-zablokuje-trackery-internetowe/

**Comment by krystian3w** [comment]
Jak nie za mocno by włączać komunikat anty-ablock na TVP VOD i Pilot WP, to czemu nie.

**Comment by xMaap** [comment]
Za mocno blokuje na WP Pilot
![Screenshot_20190606_024507](https://user-images.githubusercontent.com/36385327/58999282-57288c80-8805-11e9-88fd-91a959925bc3.png)

Ale żeby było ciekawiej pojawiają się reklamy mimo włączonego uBlocka (tak nie Nano :full_moon_with_face:)
![Screenshot_20190606_024656](https://user-images.githubusercontent.com/36385327/58999331-9b1b9180-8805-11e9-9590-1e821b867346.png)
![Screenshot_20190606_024703](https://user-images.githubusercontent.com/36385327/58999332-9b1b9180-8805-11e9-8e08-0066c00e15e3.png)
A po wyłączeniu tarczy na stronie czysto:
![Screenshot_20190606_024858](https://user-images.githubusercontent.com/36385327/58999367-c30af500-8805-11e9-967d-b5dc79c63b53.png)
![Screenshot_20190606_024906](https://user-images.githubusercontent.com/36385327/58999370-c4d4b880-8805-11e9-906d-505497f354f5.png)


TVP VOD
![Screenshot_20190606_025226](https://user-images.githubusercontent.com/36385327/58999461-3ad91f80-8806-11e9-90e3-738a78f38f48.png)

**Comment by krystian3w** [comment]
Jakby ktoś chciał to na takich ustawieniach przechodzi:

![obraz](https://user-images.githubusercontent.com/35370833/60047559-46fc2280-96ca-11e9-8339-bf02aeedc6cd.png)


Czyli wyłączam wadliwy moduł jakiego nie naprawi Mozilla ani Disconnect (na ich listach w końcu bazują).
