### ISSUE TITLE
m.bankier.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#13656]
https://m.bankier.pl

![Screenshot_2019-06-05-15-19-40-1](https://user-images.githubusercontent.com/35370833/58959534-99ba7c80-87a5-11e9-800a-7a12187f9d79.png) | ----------------------------------------------
--- |-------------------------------

Popsuty w Kiwi / Firefox na telefonie.

**Comment by krystian3w** [comment]
Jak coś nie namierzyłem listy filtrów z błędem, ale niby na 90% jest w to zamieszane blokowanie reklam.

**Comment by hawkeye116477** [comment]
U mnie jest ok na Kiwi/MIUI 10.3.1 (Android 9.0)/Redmi Note 5 AI :smile:

**Comment by krystian3w** [comment]
- może pomaga set-constant na latające wideo,
- może jakaś nadrzędna lista naprawiona
- może `gazeta.pl` naprawiła bankiera....
