### ISSUE TITLE
benchmark.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13659]
Social. Powinno wyskoczyć powiadomienie i trzeba kliknąć, że chce się przetestować nową wersje.

![Screenshot_20190606_023426](https://user-images.githubusercontent.com/36385327/58998998-e59c0e80-8803-11e9-98a7-9b62b491c3ed.png)
![Screenshot_20190606_023416](https://user-images.githubusercontent.com/36385327/58998997-e5037800-8803-11e9-9ce1-b343f7d808d9.png)

**Comment by krystian3w** [comment]
W sumie ciekawe co wcisną przed i za za jakiś czas...
