### ISSUE TITLE
virustotal.com

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#13658]
### Zrzut ekranu
![Screenshot_20190605_205722](https://user-images.githubusercontent.com/19818572/58982350-8c68b680-87d4-11e9-8820-5d1040dc4615.png)

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Posiadać Chromium/Vivaldi/ChrOperę (dla :fox_face: nie ma atrakcji)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
@krystian3w Zadanie specjalne dla ciebie, trzeba schować element z shadow roota albo jakieś :cookie: upiec. O dziwo na FF też jest shadow root, ale tam najwyraźniej uBO sobie z tym radzi.

**Comment by xxcriticxx** [comment]
@hawkeye116477 jest pl wersja strony?

**Comment by krystian3w** [comment]
Ten najnowszy gui chyba nie ma translacji.

**Comment by krystian3w** [comment]
A u mnie niby magicznie komunikat wycina Nano Adblocker, bez pieczenia, bez niczego...

**Comment by hawkeye116477** [comment]
@krystian3w W Firefoksie działa, ale w Chromium nie.

**Comment by krystian3w** [comment]
Myślę, że nie dam rady wgryźć się w ten `shadow-root` samym blokerem reklam, więc:

- trzeba raz zamknąć i nie czyścić ciastek
- poczekać na wydanie `1.35` piekące ciastka  (dalej nie wiem czy w 2019 można jakoś wyłączyć skutecznie weryfikacje kilkudniową każdej wersji dodatku). Opcjonalnie wersja z github i konserwator
- dla zaawansowanych w Nano Adblocker z Chromium z odpowiednimi przełącznikami zadziała też: `virustotal.com##+js(nanop-easy-set-cookie.js,euConsent=1)`, wada, że robi to ciasteczka co odświeżenie a nie raz na rok je odświeża.

**Comment by hawkeye116477** [comment]
Kiedyś działało `/deep/`, ale teraz już chyba nie trybi.

**Comment by krystian3w** [comment]
Mnie tam uBo nie trybi z Chrome 74 / 75.
