### ISSUE TITLE
expressilustrowany.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13668]
`https://expressilustrowany.pl/po-17-latach-malzenstwa-dowiedzial-sie-ze-wychowuje-nie-swoje-dziecko-prokuratura-odmowila-wystapienia-z-urzedu-o-zaprzeczenie/ar/c1-14189487`
Wycina film.
![Screenshot_20190608_024102](https://user-images.githubusercontent.com/36385327/59139908-12345f80-8997-11e9-8a02-8dd467685e7f.png)

**Comment by krystian3w** [comment]
Filtr `/_sess/script.js`
Lista filtrów `EasyPrivacy`

?

**Comment by krystian3w** [comment]
Psuje przekierowanie uBo na przyjazny plik Google gtm (niby blokada pierwotna z EasyPrivacy gorsza, dlatego takie coś zrobili):

`@@||www.googletagmanager.com/gtm.js$script,domain=expressilustrowany.pl`


Czyli do sekcji bugów EasyPrivacy lub do listy polskich filtrów prywatności Olega, opcjonalnie pchaj to w uAssets, może dalej lubią wszystko u siebie naprawiać?

**Comment by xMaap** [comment]
To samo na 

```
https://kurierlubelski.pl/przykra-niespodzianka-goscie-z-wroclawia-stracili-swojego-lidera-a-i-tak-wygrali-w-lublinie-ze-speed-car-motorem/ar/c2-14194779
https://stronakobiet.pl/jak-dbac-o-higiene-jamy-ustnej-dziecka/ar/c6-14168993
```
Ale nie chce mi się teraz sprawdzać na ich wszystkich serwisach.

Jeszcze tutaj social i gratka.
`https://www.motofakty.pl/artykul/elektryczne-hulajnogi-ministerstwo-proponuje-nowe-przepisy.html`
![Screenshot_20190608_073328](https://user-images.githubusercontent.com/36385327/59142523-e4afdc00-89bf-11e9-8470-8d5780ce3019.png)

**Comment by krystian3w** [comment]
```
@@||www.googletagmanager.com/gtm.js$script,domain=expressilustrowany.pl|motofakty.pl|kurierlubelski.pl|stronakobiet.pl
```

**Comment by krystian3w** [comment]
Gratkę wycina EI, niby nie nadaje się do wycinana jako reklama "zewnętrzna".

**Comment by hawkeye116477** [comment]
@krystian3w Nie wycieka.
