### ISSUE TITLE
kulturalnemedia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13671]
`https://kulturalnemedia.pl/film/najbardziej-wyczekiwane-serialowe-premiery/`
![Screenshot_20190608_075443](https://user-images.githubusercontent.com/36385327/59142747-ea5af100-89c2-11e9-8987-9443ef539b09.png)
![Screenshot_20190608_075603](https://user-images.githubusercontent.com/36385327/59142748-f3e45900-89c2-11e9-9a62-e00d9a64a68c.png)

**Comment by krystian3w** [comment]
No generichide, to wyciekł social...
