### ISSUE TITLE
adrenaline.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13674]
`https://adrenaline.pl/`
![Screenshot_20190608_113238](https://user-images.githubusercontent.com/36385327/59145247-52203480-89e1-11e9-83ae-7bdc57d98177.png)
`https://sneakershop.pl/`
![Screenshot_20190608_113354](https://user-images.githubusercontent.com/36385327/59145255-65cb9b00-89e1-11e9-8caa-814345fca078.png)
`https://jejsklep.pl/`
![Screenshot_20190608_113429](https://user-images.githubusercontent.com/36385327/59145260-7bd95b80-89e1-11e9-9ae1-9221afcd6a7f.png)

**Comment by krystian3w** [comment]
Generyka z tego się zrobić nie da niestety...
