### ISSUE TITLE
Exclude do important

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#13676]
Jest regułą ||google-analytics.com/analytics.js$important,script . Filtr jest w uBlock Filters. Da się zrobić dla niej exclude dla jednej domeny ?

**Comment by hawkeye116477** [comment]
Oj jest trochę inaczej, tzn => `||google-analytics.com/analytics.js$script,redirect=google-analytics.com/analytics.js,important`. Jest redirect, więc możemy tylko całość zanegować, nie da się zrobić wyjątku tylko dla jednej.

**Comment by krystian3w** [comment]
Ale na co ci ta analityka na blogu tak szczerze?

**Comment by krystian3w** [comment]
I żeby nie było, że przekierowanie uBO dla plików `gtm.js` i `analytics.js` było złe - źle robią ludzie pobierając ten plik na swój hosting lub Google pozwalając tam wklejać za wiele kodu...

**Comment by MajkiIT** [comment]
@krystian3w No niby czemu jest złe ? Możesz rozwinąć myśl ?

**Comment by krystian3w** [comment]
Tam powinna być minimalna ilość kodu - nie wrzucamy w niego naszego całego js by plik robił za CDN.

**Comment by MajkiIT** [comment]
Ale kod GA to raptem 5 linijek kodu wrzucany HEAD strony. Chyba ty mówisz o GTM itp.
