### ISSUE TITLE
infoladnydom.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#13683]
```
http://infoladnydom.pl/temat/ladnydom/siding+wewn%C4%99trzny
```

galeria w artykule bez zdjęć  / bez odtwarzaczy z filmami.

> ![obraz](https://user-images.githubusercontent.com/35370833/59164106-ecc76300-8b08-11e9-82b2-9b7175c24966.png)

**Comment by krystian3w** [comment]
O i anty-adblock nagle:


> ![obraz](https://user-images.githubusercontent.com/35370833/59164018-424f4000-8b08-11e9-9ff5-ab9d4a9f46ac.png)

**Comment by bogachenko** [comment]
How to cause it? I don't have anti-block. where is it

**Comment by krystian3w** [comment]
Above first photo.

**Comment by krystian3w** [comment]
I see this if enable `Adblock Warning Removal List` recomended by @jspenguin2017, so maybe fix in Nano filters?

**Comment by jspenguin2017** [comment]
@krystian3w I can't reproduce anti-adblock.

**Comment by krystian3w** [comment]
Maybe geolocked.

**Comment by bogachenko** [comment]
I have no block KOMUNICAT by the way

![Скриншот сделанный 2019-06-10 в 08 13 37-fullpage](https://user-images.githubusercontent.com/8535285/59164386-bb29b880-8b57-11e9-8fbd-3fee99436600.png)

**Comment by krystian3w** [comment]
try many refresh and disable added `set-constant` in "My Filters" panel (tab).

> ![obraz](https://user-images.githubusercontent.com/35370833/59164407-8a706180-8b0c-11e9-95b1-f673077582a4.png)

**Comment by bogachenko** [comment]
I turned off extensions in general, ads everywhere, but the player does not exist at all. This not normal. Okay, the problem is on my end. No matter. I added filters, trust you
![Безымянный](https://user-images.githubusercontent.com/8535285/59164477-e95bc800-8b58-11e9-9126-229c4c3a7efe.png)

**Comment by jspenguin2017** [comment]
Hum... OK, I see that `adblock_notify.js` is blocked by the warning removal list. I'll add an exception rule for it.

**Comment by krystian3w** [comment]
Jak coś nie umiem dodać wyjątków tak by odblokować galerię / filmy i komunikat anty-adblock jaki może się pojawić też już unieszkodliwiony.

Możliwe, że coś po stronie "Gazety" poszło nie tak jak robiła siostrzane serwisy.

**Comment by krystian3w** [comment]
@mrkisame are blocked...
