### ISSUE TITLE
kinoseans.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#13684]
@MajkiIT regex pls

test link:
http://kinoseans.pl/brytania/s01e02/108012

**Comment by krystian3w** [comment]
U mnie pop-upy zdechły, podobnie jak video na openload.co co pokasowali.

---

Zablokowałem push filtrem sieciowym, możliwe, że w pliku service worker siedzi też jakieś inne badziewie przy okazji.

**Comment by MajkiIT** [comment]
@xxcriticxx już powinno być ok.

**Comment by xxcriticxx** [comment]
@MajkiIT jeszcze jak counter da sie przestawic na 1 sec i bendzie malina 

Odtwarzacz pojawi się za 8s.

**Comment by krystian3w** [comment]
To już dla gargulca wyzwanie do sprawdzenia czy czas jest weryfikowany z serwerem i jakim skryptem najkorzystniej przyśpieszyć.

**Comment by xxcriticxx** [comment]
gargula chyba znowu ma zakaz wstępu
