### ISSUE TITLE
tvokazje.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#13695]
https://www.tvokazje.pl/325-ogladaj-na-zywo

Wystarczy dodać do `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script` domenę `tvokazje.pl`

Pełna reguła

```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=redefine.pl|redcdn.pl|polsatnews.pl|polsatsport.pl|twojapogoda.pl|tvokazje.pl
```

@F4z @krystian3w

**Comment by MajkiIT** [comment]
@FadeMind Adblock ?

**Comment by FadeMind** [comment]
@MajkiIT  podałem już SETUP w poprzednim zgłoszeniu 😉 


Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.0.x Nightly** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
|Disable cache for 3rd-party requests
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuckadblock
| **SECTION :: Ads**
| Adguard Base Filter 
| EasyList
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| EasyPrivacy
| Fanboy's Anti-Facebook List 
| Fanboy's Enhanced Tracking List 
| **SECTION :: Social**
| Adguard Social Filter
| Fanboy's Social Blocking List 
| **SECTION :: Annoyances**
| Adblock Warning Removal List
| Adguard Annoyances
| Fanboy's Annoyances 
| Fanboy's Cookiemonster List
| **SECTION :: Security**
| Malware Domains
| Spam404
| NoCoin Filter List 
| **SECTION :: Customs**
| AlleBlock
| EasyList Polish 
| KAD - fraud/scam
| Polish Annoyances Filters
| Polish Anti Adblock List Filters
| Polish Main Filters
| Polish Social Filters

**Comment by xxcriticxx** [comment]
@FadeMind więcej filtrów nie dało się wlonczyc?

**Comment by FadeMind** [comment]
@xxcriticxx można, ale nie potrzebuję 😁

**Comment by MajkiIT** [comment]
@FadeMind dziękuję

**Comment by bogachenko** [comment]
@krystian3w as I said (returning to our previous conversation), for some reason it works for me without google
![Безымянный](https://user-images.githubusercontent.com/8535285/59263330-8e2af200-8c8c-11e9-9c1d-896ab47df8f1.png)
