### ISSUE TITLE
rmfmaxxx.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#13735]
https://www.rmfmaxxx.pl/muzyka/hity 

rodo znowu zaczęło migać, nie pomaga blokowanie tam ramki lub ma inny adres:

https://github.com/MajkiIT/polish-ads-filter/blob/22a98826ecacc20ec1ac6ab4ce0d1845c605d05a/cookies_filters/adblock_cookies.txt#L2044

**Comment by hawkeye116477** [comment]
@krystian3w `||rmfmaxxx.pl/zgody/css/rodo-popup-n.css`
