### ISSUE TITLE
kozaczek.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1373]
reklama sodexo

![capture1](https://cloud.githubusercontent.com/assets/15007183/19620556/1d3a1358-984e-11e6-93d7-9b470c96c0a7.PNG)

**Comment by MajkiIT** [comment]
Ja nic nie mam. Możesz sprawdzić jeszcze raz?

**Comment by MajkiIT** [comment]
dobra już złapałem

**Comment by MajkiIT** [comment]
||kozaczek.pl/stats.php$xmlhttprequest
