### ISSUE TITLE
apteline.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13740]
![Screenshot_20190613_093529](https://user-images.githubusercontent.com/36385327/59412916-cc283300-8dbe-11e9-8d51-85f89aaed840.png)

**Comment by MajkiIT** [comment]
`||cookies.aptelink.pl/nc.js`

**Comment by krystian3w** [comment]
Jest może więcej nc.js w public www / nerdy data?
