### ISSUE TITLE
otodom.pl

### ISSUE THREAD

**Issue by urbanex** [MajkiIT/polish-ads-filter#13741]
### Zrzut ekranu

![image](https://user-images.githubusercontent.com/31351412/59422455-b459aa80-8dd0-11e9-8872-956622249935.png)

### Link bezpośredni

https://www.otodom.pl/sprzedaz/dzialka/budowlana/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. wejsc w link podany wyzej
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**

**Rozszerzenia i skrypty:**

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by hawkeye116477** [comment]
@MajkiIT `otodom.pl#@#[class$="-ads"]`
