### ISSUE TITLE
google

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1374]
Serdeczna prośba o zrobienie nowych filtrów -Przypomnienie o Polityce prywatności Google- znów zaczęło się pojawiać.Aby ułatwić sprawę podrzucam moje usiłowania zablokowania komunikatu ublockiem.:

**Comment by xxcriticxx** [comment]
fb?

**Comment by MajkiIT** [comment]
email

**Comment by xxcriticxx** [comment]
google.pl?

**Comment by MajkiIT** [comment]
tak
