### ISSUE TITLE
majsterkowo.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13772]
Reklamy
`https://majsterkowo.pl/chcesz-oszczedzac-energie-zbuduj-licznik-impulsow/`

![Screenshot_20190615_203800](https://user-images.githubusercontent.com/36385327/59555095-c0e72a00-8fad-11e9-919c-59d5be98ae67.png)

![Screenshot_20190615_203829](https://user-images.githubusercontent.com/36385327/59555096-c0e72a00-8fad-11e9-86bf-44593a5c86b2.png)

![Screenshot_20190615_203844](https://user-images.githubusercontent.com/36385327/59555097-c0e72a00-8fad-11e9-8467-a0760ff43616.png)

**Comment by MajkiIT** [comment]
@KonoromiHimaries wew
