### ISSUE TITLE
zyciesiedleckie.pl/pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#13785]
RODO 

@krystian3w idzie przyśpieszyć blokowanie ?

Można dać jakąś ogólną regułe bo takich stron jest więcej.

**Comment by krystian3w** [comment]
Można akceptować ciastkiem w PCZ. Ale tam raczej z generykiem będzie kiepsko (ciastka tylko pod konkretne domeny można zrobić). Raczej w rosjan nie będziemy się bawić by łagodny skrypt odpalać pod cały internet - tzw. makarony spaghetti 🍜.

-- 


Raczej też nie siedzi to w pliku js / css - więc jak blokuje przewijanie to trzeba wszystkie popularne pl domeny wyłapać ręcznie lub zobaczyć co wypluje `nerdy data` / `public www`.

**Comment by krystian3w** [comment]
Co do generyka to jest najszerszego zasięgu:

https://github.com/MajkiIT/polish-ads-filter/blob/d451780b366a3a51468883c3158d9514c8e8cd56/cookies_filters/adblock_cookies.txt#L2882

niby taki z dopisanym PL będzie odrobinę szybszy i nie będzie migać, tyle że nagle zacznie to być na com / eu  / info / org itd.

**Comment by hawkeye116477** [comment]
`zyciesiedleckie.pl##+js(abort-current-inline-script.js, $, rodo-overlay)`
