### ISSUE TITLE
fpiec.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13783]
![Screenshot_20190616_190101](https://user-images.githubusercontent.com/36385327/59567090-3f54d200-9069-11e9-8f1c-88cd78d1c40e.png)

![Screenshot_20190616_190213](https://user-images.githubusercontent.com/36385327/59567102-690df900-9069-11e9-9204-6114dcd9a796.png)

![Screenshot_20190616_190229](https://user-images.githubusercontent.com/36385327/59567104-6ca18000-9069-11e9-972c-5bafb938d41f.png)

**Comment by MajkiIT** [comment]
`fpiec.pl##[id^="offerID-"]`
