### ISSUE TITLE
filme.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#13805]
Kontynuacja problemu z: https://github.com/PolishFiltersTeam/KAD/issues/914

```
filme.pl##a[href*="https://leadmy.pl/"]
filme.pl#?#.float-xl-left.col-lg-8 > div.mb-3.card:nth-of-type(3):-abp-has(a[href*="https://leadmy.pl/"])
filme.pl#?#.float-xl-right.col-lg-4 > div.mb-3.card:nth-of-type(2):-abp-has(a[href*="https://leadmy.pl/"])
```

reklamy filmów dostępnych w chili np. Kler.

Na razie nie wiem czy to nie będzie trzeba aktualizować co jakieś 24 godziny lub wycinając obrazki a nie po linku.

**Comment by krystian3w** [comment]
Potencjalna opcja z wycinaniem po adresie obrazków:

```
##img[src*="static2.mylead.global/img/programs/banners/"]
```

wycięcie samego obrazka zostawia luki.

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/fc891fca1b466806c253235f9374016de0c41b50#diff-711027ed0794992ae3b8710d874f3df7

@krystian3w Zaryzykowałem tak

**Comment by krystian3w** [comment]
O to tę jelonkę można uzupełnić o kropkę jak kiedyś czepiał się gargul jak kilka filtrów poprawiałem przy okazji do składni ABP:

`||static*jelonka.com^` 
na:
`||static*.jelonka.com^`
