### ISSUE TITLE
aquatechnika.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13811]
Social
![Screenshot_20190618_124841](https://user-images.githubusercontent.com/36385327/59676316-94a6f580-91c7-11e9-9477-ec139281be50.png)

**Comment by hawkeye116477** [comment]
@krystian3w Co nie robisz?

**Comment by krystian3w** [comment]
Bo mam anginę, jak skacze gorączka to nawet siedzieć się nie da.

**Comment by hawkeye116477** [comment]
@krystian3w Aha, ok, to życzę szybkiego wyzdrowienia. A ja wieczorem jeszcze zerknę na resztę :smile:.
