### ISSUE TITLE
rp.pl

### ISSUE THREAD

**Issue by ggargul** [MajkiIT/polish-ads-filter#13829]
Sprośny błąd - ukryte video, w aż 4 różnych listach anty-rodo-ciasteczowych: https://github.com/ryanbr/fanboy-adblock/issues/1071.

**Comment by hawkeye116477** [comment]
Mała strata, filmik niezwiązany z artykułem. Ale niech będzie, dodamy do PCZ.
@ggargul Sprawdź jeszcze `gremimedia.pl, rpkom.pl` i `zw.com.pl`.
