### ISSUE TITLE
naszemiasto.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#13825]
Adguard usuwa player z TVN na stronach. 
http://gniezno.naszemiasto.pl/artykul/urlop-potrafi-rozczarowac-oczekiwania-kontra-rzeczywistosc,5171671,gal,t,id,tm.html

![scr-1561042251-001](https://user-images.githubusercontent.com/9846948/59858623-a16c4a80-937b-11e9-96d8-486a2f84a530.png)

![scr-1561042542-001](https://user-images.githubusercontent.com/9846948/59858994-42f39c00-937c-11e9-9b8d-95ec2be8b1b4.png)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.0.x Nightly** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
|Disable cache for 3rd-party requests
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuckadblock
| **SECTION :: Ads**
| Adguard Base Filter 
| EasyList
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| EasyPrivacy
| Fanboy's Anti-Facebook List 
| Fanboy's Enhanced Tracking List 
| **SECTION :: Social**
| Adguard Social Filter
| Fanboy's Social Blocking List 
| **SECTION :: Annoyances**
| Adblock Warning Removal List
| Adguard Annoyances
| Fanboy's Annoyances 
| Fanboy's Cookiemonster List
| **SECTION :: Security**
| Malware Domains
| Spam404
| NoCoin Filter List
| **SECTION :: Customs**
| AlleBlock
| EasyList Polish 
| KAD - fraud/scam
| Polish Annoyances Filters
| Polish Anti Adblock List Filters
| Polish Main Filters
| Polish Social Filters

@AdamWr 

@ameshkov

**Comment by Alex-302** [comment]
@FadeMind which filter causes it?

**Comment by BlazDT** [comment]
Not reproduced with filters available in AdGuard and listed. Following are not listed by AdGuard:

Polish Annoyances Filters
Polish Anti Adblock List Filters
Polish Main Filters
Polish Social Filters

**Comment by Alex-302** [comment]
Not reproduced with your filters

**Comment by Alex-302** [comment]
> Polish Main Filters

Easylist Polish, I guess

**Comment by FadeMind** [comment]
@BlazDT I using only FFA and CoinBlockerList as externals

![scr-1561055886-001](https://user-images.githubusercontent.com/9846948/59873007-57935c80-939b-11e9-841d-95d97ed8b221.png)

Polish Language lists are in Adguard Filter Registry (I using english common translation names instead of original name)

![scr-1561055730-001](https://user-images.githubusercontent.com/9846948/59872866-fff4f100-939a-11e9-99f0-3fa10fd8edb9.png)
![scr-1561055739-001](https://user-images.githubusercontent.com/9846948/59872868-008d8780-939b-11e9-93ea-7456bfee8879.png)



JSON > https://pastebin.com/raw/1pGHMcJg

**Comment by krystian3w** [comment]
Coś blokuje: `get.x-link.pl/`?

**Comment by FadeMind** [comment]
@krystian3w tak.  
![scr-1561056389-001](https://user-images.githubusercontent.com/9846948/59873584-9b3a9600-939c-11e9-8f83-539718ad8a4e.png)
![scr-1561056406-001](https://user-images.githubusercontent.com/9846948/59873585-9b3a9600-939c-11e9-997f-201bf9de83e6.png)

**Comment by Alex-302** [comment]
Please check 
`@@||get.x-link.pl/*,embed.html$replace=/video:"(autoplay|scroll_pause)"\,/video:""\,/`

**Comment by krystian3w** [comment]
Also test allow xhr from rodo.js file:

`@@||sso.ppapi.pl/rodo.js$xmlhttprequest` - also break players on Press Media sites.

**Comment by FadeMind** [comment]
Bez zmian 
![scr-1561057036-001](https://user-images.githubusercontent.com/9846948/59874203-020c7f00-939e-11e9-982e-03ff09edb5ef.png)

**Comment by krystian3w** [comment]
A spróbuj dopuścić ogólnie plik rodo, może nagle się nie dogaduje taka blokada z aplikacją na Windows?

`@@||sso.ppapi.pl/rodo.js$script,xmlhttprequest`

**Comment by FadeMind** [comment]
@krystian3w też to zastosowałem, wynik masz w moim poprzednim komentarzu. 
Łapcie config do adguarda > 
[20190620_205814_adg_settings_7.1.2817.0.zip](https://github.com/MajkiIT/polish-ads-filter/files/3311764/20190620_205814_adg_settings_7.1.2817.0.zip)

**Comment by krystian3w** [comment]
OK, po imporcie rzeczywiście coś blokuje z AdGuard 7.

**Comment by krystian3w** [comment]
Błąd mam w liście Anti-Facebook od Fanboyów?

**Comment by krystian3w** [comment]
@adamwr chyba tu coś psuje tryb niewidzialności / Stealth Mode.

**Comment by FadeMind** [comment]
> `@@||sso.ppapi.pl/rodo.js^$third-party`
naprawił błąd 😁  dzięki

**Comment by krystian3w** [comment]
Spoko, mam nadzieję, że jakoś to potem zrobią by odblokowywało to również:

`@@||sso.ppapi.pl/rodo.js?pp_pr=null$stealth`


Czarno widzę że Fanboye usuną wadliwe: `/rodo.js?pp_pr=` - opcjonalnie można to wywalać na poziomie filters registry również.
