### ISSUE TITLE
footroll.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13839]
Nie wczytują się obrazki
Włączony
![Screenshot_20190622_071622](https://user-images.githubusercontent.com/36385327/59959766-dda7c400-94bd-11e9-96ae-07f664dde0e3.png)
Wyłączony
![Screenshot_20190622_071635](https://user-images.githubusercontent.com/36385327/59959770-e1d3e180-94bd-11e9-9273-60a4c735ccd6.png)

**Comment by krystian3w** [comment]
u mnie OK, spróbuj wyłączyć `fanboy cookie list`?

**Comment by krystian3w** [comment]
```
@@||footroll.pl/js/vendor/cookiebox.min.js
```

fix dla @xMaap  aż fanboy sobie nie naprawi.
