### ISSUE TITLE
zycieczestochowy.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13838]
Social
![Screenshot_20190622_071034](https://user-images.githubusercontent.com/36385327/59959718-ffed1200-94bc-11e9-8d57-31fe20bafb38.png)

Reklama
![Screenshot_20190622_071111](https://user-images.githubusercontent.com/36385327/59959720-0d0a0100-94bd-11e9-8ec6-9eab60aad4f5.png)

Ukrywa
![Screenshot_20190622_071211](https://user-images.githubusercontent.com/36385327/59959731-39258200-94bd-11e9-840b-cea8eb022b15.png)
![Screenshot_20190622_071204](https://user-images.githubusercontent.com/36385327/59959737-4cd0e880-94bd-11e9-97cd-35906d0657e9.png)

**Comment by krystian3w** [comment]
@MajkiIT  Nie można tak blokować tego slideru jak wypychają tam własny artykuł?

**Comment by MajkiIT** [comment]
@krystian3w no właśnie to takie obejście ... po jakimś czasie on się pojawia ... A uważasz, że trzeba ukryć go całkowicie ?

**Comment by krystian3w** [comment]
Podejrzewam, że pewnie cała strona skacze jak on wraca, trzeba by sięgnąć po html filtering by wyciąć reklamowe slajdy i dla chrome może skrypt od 🐧 "remove-elements-on-ready" jak zadziała z tym sliderem (niestety nie na każdy działa, testowane na liście social, ze zgłoszeń gargulca, gdzie go raziły takie slajdy).
