### ISSUE TITLE
PopupBlocker

### ISSUE THREAD

**Issue by azet12** [MajkiIT/polish-ads-filter#1384]
Niedawno pewna osoba napisała do mnie, że stworzyła filtry. Nie chciała tych rzeczy zgłaszać do Was, lecz chciała mieć to jako oddzielny projekt. 
Jest dostępny tutaj: https://github.com/azet12/PopupBlocker/blob/master/PPB.txt
@MajkiIT @xxcriticxx @F4z Jeśli macie czas, rzućcie okiem. Dzięki

**Comment by MajkiIT** [comment]
Ta lista to jednorazowy strzał czy będzie rozwijana?

**Comment by azet12** [comment]
Autor chciałby najpierw rozwinąć lekko listę i ewentualnie później doczepić ją do większego projektu.

**Comment by MajkiIT** [comment]
@azet12 Ok, tylko w tej liście jest dużo reguł redundantnych. To celowe jak u ciebie?

**Comment by azet12** [comment]
Nie ja robiłem te filtry, więc nie wiem. Zawsze można coś zmienić.

**Comment by MajkiIT** [comment]
to jak sobie autor życzy... chcesz abym wrzucił to do siebie?

**Comment by azet12** [comment]
Na chwilę obecną nie

**Comment by xxcriticxx** [comment]
@azet12 wyglonda to na generic filters mamy to potestowac?

**Comment by azet12** [comment]
Pewnie.

**Comment by xxcriticxx** [comment]
za duzo to hyba nie zablokuje

@F4z co myslisz o liscie?

**Comment by azet12** [comment]
dostalem liste stron, na ktorych cos jest blokowane, wiec troche tego jest. Usuwa to bodajze tez wszystkie okienka proszace o podanie emaila (newsletter).

```
https://gadzetomania.pl/
https://komorkomania.pl/
https://wirtualnemedia.pl/
https://media2.pl/
https://ozonee.pl/
https://www.denley.pl/
http://olika.com.pl/
https://www.sakolife.pl/
http://www.monashe.pl/
http://shop.prettyone.pl/
https://byinsomnia.com/
http://wearmedicine.com/on-5-k.html
http://dstreet.pl/
https://ombre.pl/
http://e-ciucholand.com/
http://factoryprice.pl/
http://japanstyle24.pl/
http://galeriamarek.pl/
http://ptakmoda.com/
http://pandzior.pl/
https://unhuman.pl/
https://bylola.pl/
http://avaro.pl/
http://fashionata.pl/
http://www.9fashion.pl/Sklep/
http://www.51015kids.eu/
http://e.lauraguidi.pl/
http://www.halens.pl/#popup
http://50style.pl/meskie-ubrania,plec,MM,K/
https://www.czasnabuty.pl/
https://deezee.pl/
http://pantofelek24.pl/
http://www.kupbuty.com/
http://akardo.pl/
https://www.casu.pl/
http://www.renee.pl/
http://ebuty.pl/
http://brilu.pl/buty_damskie.html
http://www.intershoe.com.pl/
http://www.stylowebuty.pl/
https://www.rylko.com/pl
https://www.macris.com.pl/
https://3i-store.com/dla-niej/obuwie-damskie
http://mcarthur.com.pl/
http://arturo-obuwie.pl/
http://buu.pl/pl/
http://butylukow.pl/
https://www.sklepkamil.pl/
http://aligoo.pl/
https://www.mivo.pl/
http://www.butyibuty.pl/
https://butosklep.pl/
http://www.gemre.com.pl/
http://www.uniformix.pl/
http://dayli.com.pl/
http://www.wispol.eu/
http://kosmetykomania.pl/
http://www.bodyland.pl/
https://www.nocanka.pl/
http://d24h.pl/
http://www.superkoszyk.pl/kosmetyki.html
answear.com
deezee.pl
domodi.pl
e-przepisykulinarne.pl
jubilerbogart.pl
kwiaciarnia-rikka.pl
markizasklep.pl
multikino.pl
pl.tripadvisor.com
salesandshopping.pl
store.nike.com
twojasuknia.pl
wojas.pl
www.booking.com
www.diversesystem.com
www.galeriabronowice.pl
www.galeria-kaskada.pl
www.galeria-warminska.pl
www.handkate.com
www.kwiaciarnia-olivia.pl
www.limango.pl
www.pogotowiegotowkowe.info
www.redisbad.pl
www.sklepmartes.pl
www.twojekwiaty.pl
www.tygertenis.pl
www.wec.com.pl
yes.pl
zoio.pl
```

**Comment by xxcriticxx** [comment]
@azet12 projekt sie zapowiada super jak bendzie wiecej rozwiany

**Comment by adreporter** [comment]
@azet12 z włączonym PopupBlockerem nie można ściągnąć programu z tej strony: http://acestream.org/ (przycisk pobierania jest na dole po lewej)

**Comment by blocker999** [comment]
dzięki zaraz poprawie

**Comment by blocker999** [comment]
Bardzo proszę o zrzut ekranu z zaznaczeniem na czerwono co nie tak i dopiero postaram się poprawić, bo umnie niby jest ok, proszę dokładnie napisać o co chodzi czy o ikonke pobierania czy o blokade.

**Comment by azet12** [comment]
Mam ten sam problem, po kliknięciu przycisku pobierania w lewym dolnym rogu nic się nie wyświetla, powodem tego jest reguła: `###popup`

**Comment by adreporter** [comment]
@blocker999 
Jak klikam w
![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/19931038/5a5450ee-a10b-11e6-8f14-e4e65b387b63.PNG)
to nic się nie dzieje, a powinno się pokazać
![2](https://cloud.githubusercontent.com/assets/18214146/19931058/6d08ff5a-a10b-11e6-8e9a-d3aa466aa69e.PNG)

**Comment by adreporter** [comment]
@blocker999 Jest jeszcze jeden problem z inną stroną, ale niestety wymaga ona podania informacji osobistych. Chodzi o http://www.inter.it/it/esclusivo Na tej stronie też jak klikam w obrazek to nic się nie dzieje. Powodem są te dwie reguły: `###simplemodal-container` i `###simplemodal-overlay`
![3](https://cloud.githubusercontent.com/assets/18214146/19931719/d28d6c7e-a10d-11e6-9d3b-123381758a87.PNG)

**Comment by blocker999** [comment]
dobra na chwile obecną jest już zaktualizowane
