### ISSUE TITLE
wprost.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#13849]
zdjecia sie nie laduja

test link:
https://www.wprost.pl/sport

![Capture](https://user-images.githubusercontent.com/15007183/59966857-08ab0b80-94f0-11e9-8b9b-9beda79b5059.PNG)

**Comment by krystian3w** [comment]
ładują, masz wolny net lub długo łączy z polskim serwerem, daj minutę a wskoczą może.

Ja mam po jakiś 10 sekundach.

**Comment by krystian3w** [comment]
Lazy loadingu w uBlock Origin się nie naprawia, musisz sobie wyskorbać skrypt w Violentmonkey / tampermonkey - @hawkeye116477  zrób mu jak umiesz ogarnąć jak działa ich ten lazy loader.

**Comment by krystian3w** [comment]
Na siłę @MajkiIT  można takie coś dodać:


````
www.wprost.pl##[class*="lazy"] img:style(display: inline-block !important;)
```

do suplementu dla uBO / AdGuard.
