### ISSUE TITLE
krbrd.gov.pl/pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13846]
Cookies
![Screenshot_20190622_190639](https://user-images.githubusercontent.com/36385327/59966761-162cb980-9521-11e9-9a55-f7d9506cecc8.png)

**Comment by krystian3w** [comment]
| BŁĄD 404Nie znaleziono stronyPrzejdz do strony głównej
-- | --

**Comment by krystian3w** [comment]
@hawkeye116477 ja nie mam tego paska...

**Comment by krystian3w** [comment]
`DIV[style*="background:url(images/cookies_tlo.png)"]`
