### ISSUE TITLE
kalinowo.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13851]
![Screenshot_20190623_015308](https://user-images.githubusercontent.com/36385327/59969900-d7672580-9559-11e9-9adb-3dc5543fd60a.png)

**Comment by ggargul** [comment]
Błąd w Fanboy Cookie List: https://github.com/ryanbr/fanboy-adblock/issues/1073.

**Comment by krystian3w** [comment]
Jaki błąd, komunikat wcale nie wycięty na polskiej liście.

**Comment by ggargul** [comment]
Sraki, a niby co jest w pierwszym komentarzu na zrzucie ekranu - komunikat wycięty i tło zostało, to typowy błąd w Fanboy's Cookie List, więc może do okulisty.
