### ISSUE TITLE
jazzforum.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13860]
![Screenshot_20190623_204127](https://user-images.githubusercontent.com/36385327/59980527-7aba4800-95f7-11e9-86b1-325ba124b099.png)
![Screenshot_20190623_204140](https://user-images.githubusercontent.com/36385327/59980526-7aba4800-95f7-11e9-8d74-e16be464e551.png)

**Comment by xxcriticxx** [comment]
@xMaap reklama or social?

**Comment by krystian3w** [comment]
oba, przycisk nie do logowania.
