### ISSUE TITLE
kobieta.onet.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13862]
Reklama. Chodzi o te kółko ze strzałką (?) i jest to reklama Huawei 
https://kobieta.onet.pl/dom/piekny-dom-parterowy-ktory-wybudujesz-w-cenie-mieszkania/6h78ger
![Screenshot_20190624_024100](https://user-images.githubusercontent.com/36385327/59984396-e74e3a80-9629-11e9-9ffe-6f385e05c964.png)

**Comment by MajkiIT** [comment]
@xxcriticxx @krystian3w Macie to ?

**Comment by krystian3w** [comment]
Mam z Nano Adblocker:

![image](https://user-images.githubusercontent.com/35370833/60242908-4ffe1700-98b7-11e9-973a-7cfbbf08cc16.png)

**Comment by krystian3w** [comment]
@xMaap  masz już Nano Adblocker 1.0.0.118? czy jakiś dużo starszy?

**Comment by hawkeye116477** [comment]
Ale to nawet z uBO jest.

**Comment by krystian3w** [comment]
ID / klasy CSS ci łapią?

Kij jak batuu z z linka sponsorowanego zmienia się w allegro.pl

**Comment by hawkeye116477** [comment]
@krystian3w Tak. Batuu prowadzi do doubleclick, a potem na alledrogo.

**Comment by xxcriticxx** [comment]
@MajkiIT tak mam allegro tak jak @krystian3w 

![Capture](https://user-images.githubusercontent.com/15007183/60265335-83d73d80-98b3-11e9-96cf-cd5b1607319b.PNG)

**Comment by krystian3w** [comment]
@hawkeye116477  on chyba nam odpadł przed kliknięciem "czytaj dalej". W AdGuard na razie też nie ogarnęli jak to zablokować.

**Comment by xMaap** [comment]
@krystian3w Przeszedłem z Nano Adblocker na uBlock Origin.

To chyba mnie Huawei prześladuje i dalej mam ich reklamę  "Huawei P30 Lite i Huawei P30 w supercenie!"

**Comment by krystian3w** [comment]
Jest bo nie było próby blokady buttona.

**Comment by xMaap** [comment]
Chyba można zamknąć.
