### ISSUE TITLE
vod.pl | onet.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1386]
Komunikat o adblocku - `http://vod.pl/filmy-i-bajki-dla-dzieci/planet-hulk-hulk-na-obcej-planecie/6yxxbzw`

![image](https://cloud.githubusercontent.com/assets/11742596/19660878/d3fea79a-9a31-11e6-856a-bfc7f205bebc.png)

Na przykład:
`@@||vod.pl^$generichide`

Jeśli chodzi o onet, to bardzo rzadko widzę  ten komunikat* i czasami wystarczy, że wyczyszczę ciasteczka/cache albo po prostu odświeżę stronę, i już go nie mam.
Teoretycznie dodanie tej reguły powinno sprawić, że w ogóle tego nie będzie:
`@@||onet.pl^$generichide`
Wtedy można jeszcze dodać te dwie reguły, bo widzę, że są ogólne/generyczne, a przez powyższą regułę zostaną "wyłączone":
`onet.pl###extraAdsBlock`
`onet.pl##.addthis_toolbox`

*w zasadzie to nie widzę komunikatu, bo jest ukryty przez regułę kosmetyczną, ale wtedy strona jest ścięta i widać tylko jej górną część
![image](https://cloud.githubusercontent.com/assets/11742596/19661437/02c868b6-9a34-11e6-8ca8-db72c4ea5c52.png)

**Comment by MajkiIT** [comment]
co powiesz na to onet.tv,vod.pl#@#.text-ad ??

**Comment by F4z** [comment]
U mnie to nie działa.
Nadal mam komunikat o adblocku.

**Comment by MajkiIT** [comment]
@F4z dodane dziękuję.
