### ISSUE TITLE
stronazdrowia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#13879]
test link:
https://stronazdrowia.pl/osteoporoza-co-to-objawy-bolowe-przyczyny-leczenie-sprawdz-jak-powinna-wygladac-dieta-ludzi-z-osteoporoza/ar/c14-13569196

**Comment by krystian3w** [comment]
dopisać do rozwiązań na press Polskę.

**Comment by krystian3w** [comment]
@olegwukr:

`stronazdrowia.pl##+js(set-constant.js, pp_adblock_is_off, trueFunc)`

jak zwykle dalej działa.

---

`@@||s-pt.ppstatic.pl/*/reklama.js`
`@@/adblockdetect/*`

do tych dwóch też można dopisać.
