### ISSUE TITLE
srodowisko.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13917]
Reklamy

```
https://www.srodowisko.pl/
https://www.wyposazeniemedyczne.pl/
```
![Screenshot_20190626_125323](https://user-images.githubusercontent.com/36385327/60174532-8aad7400-9811-11e9-932c-422b0475d0d0.png)

```
https://www.automatyka.pl/
https://www.elektroinzynieria.pl/
https://www.obrabiarki.xtech.pl/
https://www.wodkaneko.pl/

```
![Screenshot_20190626_125437](https://user-images.githubusercontent.com/36385327/60174623-b4669b00-9811-11e9-83ad-220d3c9680f3.png)

```
https://www.energetykacieplna.pl/
https://www.laboratoria.xtech.pl
```
![Screenshot_20190626_125541](https://user-images.githubusercontent.com/36385327/60174685-da8c3b00-9811-11e9-9e40-897572528627.png)

**Comment by MajkiIT** [comment]
`www.srodowisko.pl,www.wyposazeniemedyczne.pl,www.automatyka.pl,www.elektroinzynieria.pl,www.obrabiarki.xtech.pl,www.wodkaneko.pl,www.energetykacieplna.pl,www.laboratoria.xtech.pl##.frame, .advertHd`
