### ISSUE TITLE
gramwzielone.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13915]
Reklamy + cookies
![Screenshot_20190626_124653](https://user-images.githubusercontent.com/36385327/60174201-d6135280-9810-11e9-831b-e01f45e0b365.png)
![Screenshot_20190626_124701](https://user-images.githubusercontent.com/36385327/60174202-d6135280-9810-11e9-8d48-0d0050130bd7.png)
![Screenshot_20190626_124710](https://user-images.githubusercontent.com/36385327/60174203-d6135280-9810-11e9-94bb-3c9cd2383c78.png)
![Screenshot_20190626_124718](https://user-images.githubusercontent.com/36385327/60174204-d6135280-9810-11e9-88cd-e3e9cc200ec5.png)

**Comment by MajkiIT** [comment]
##.banner
