### ISSUE TITLE
urzadzamy.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13914]
Pozostałości po reklamach 
http://www.urzadzamy.pl/salon/balkon-i-taras/ogrod-zimowy-jak-zaaranzowac-ogrody-zimowe-od-do-z,151_17571.html
![Screenshot_20190626_124456](https://user-images.githubusercontent.com/36385327/60174063-82a10480-9810-11e9-8d97-9bdb682b5ab3.png)
![Screenshot_20190626_124504](https://user-images.githubusercontent.com/36385327/60174064-82a10480-9810-11e9-87ff-4c8759e5d08d.png)
![Screenshot_20190626_124511](https://user-images.githubusercontent.com/36385327/60174065-83399b00-9810-11e9-984a-cd95e8236640.png)

**Comment by MajkiIT** [comment]
`##[id^="placement_"]`
