### ISSUE TITLE
rynekinstalacyjny.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13916]
Reklamy
![Screenshot_20190626_124949](https://user-images.githubusercontent.com/36385327/60174329-183c9400-9811-11e9-8abc-1f99869038b2.png)
![Screenshot_20190626_124958](https://user-images.githubusercontent.com/36385327/60174330-183c9400-9811-11e9-96e6-40eef586ff66.png)

**Comment by MajkiIT** [comment]
`##.banner`
