### ISSUE TITLE
pracuj.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13922]
Cookies + social
![Screenshot_20190627_021817](https://user-images.githubusercontent.com/36385327/60224360-6178fc00-9882-11e9-917f-e3f93314f812.png)
![Screenshot_20190627_021826](https://user-images.githubusercontent.com/36385327/60224361-62119280-9882-11e9-8c01-22ead34746b7.png)

**Comment by krystian3w** [comment]
Wycięte, dodatkowo dziwny jakiś dział otwarty, nie mam tak zbudowanej stopki.

**Comment by krystian3w** [comment]
@xMaap  jak samo nie zniknie to podrzuć link lub opis co klikać albo czy to niespodzianka dla zalogowanych.

**Comment by xMaap** [comment]
@krystian3w nie jestem zalogowany https://www.pracuj.pl/
![Screenshot_20190628_183646](https://user-images.githubusercontent.com/36385327/60357412-e0317e80-99d3-11e9-9a07-2444f8dbbdc6.png)

**Comment by krystian3w** [comment]
No to Opera dostaje inny HTML?

**Comment by krystian3w** [comment]
Albo nagle serwują i mi nowy brzydki szablon html - @hawkeye116477  jak coś to ich klasy są śmieszne jakby randomy...

1.

**Comment by krystian3w** [comment]
@xMaap a masz u nich konto, niby logowanie włącza jakiś ten nowy Layout.

**Comment by xMaap** [comment]
Nieee mam tam konta. Przeglądałem w trybie incognito.
