### ISSUE TITLE
parenting.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#13925]
https://parenting.pl/jaka-rybe-wybrac-na-wakacjach-nad-baltykiem-wideo

Czasem wideo ucieka i najczęściej wyskakuje komunikat "błąd 13" - "wykryto AdBlock".

> ![Screenshot_2019-06-27-14-21-37-1](https://user-images.githubusercontent.com/35370833/60265861-0decc980-98e7-11e9-9cdd-31652cffa225.png) |
> --- |

**Comment by bogachenko** [comment]
i have no antiadblock

**Comment by krystian3w** [comment]
Try on this:

https://portal.abczdrowie.pl/choroba-konskiego-ogona-zagraza-posiadaczom-dlugich-wlosow-nie-wiaz-wlosow-w-kucyk-wideo

Also have error 13 in player

**Comment by xxcriticxx** [comment]
Cannot Reproduce

**Comment by bogachenko** [comment]
@krystian3w 
>Try on this: https://portal.abczdrowie.pl/choroba-konskiego-ogona-zagraza-posiadaczom-dlugich-wlosow-nie-wiaz-wlosow-w-kucyk-wideo

![Безымянный](https://user-images.githubusercontent.com/8535285/60265408-65b02280-9931-11e9-8826-21427d332df7.png)

nothing lol. twisted expansion hola, too anything

**Comment by krystian3w** [comment]
@naxcriticx na "pareting" niby pomaga dopisanie ".wp", ale abc raczej takiego adresu nie ma i nie umiem znaleźć filtra z przekierowaniem na krótki mp3/mp4.

**Comment by xxcriticxx** [comment]
@krystian3w comprende

**Comment by HateAds** [comment]
@krystian3w Tak samo na money.pl potrafi wykryć adblocka w odtwarzaczu.

**Comment by krystian3w** [comment]
@HateAds sprawdź pod money:

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=parenting.pl|abczdrowie.pl|money.pl`

niby player czasem używa ima3.js...
