### ISSUE TITLE
trojmiasto.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1393]
cala strona biala hyba z powodu slowa "adblock"

http://www.trojmiasto.pl/portal/adblock/

**Comment by F4z** [comment]
To wina tej reguły - `##[class$="-ads"]`
`trojmiasto.pl#@#[class$="-ads"]`
Chociaż u mnie nie zawsze strona jest ukryta, nie wiem czemu tak się dzieje.

**Comment by xxcriticxx** [comment]
kiedys byl tam adblock teraz hyba juz to omijamy

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z Dzięki
