### ISSUE TITLE
alltube.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#13932]
@MajkiIT regex trzeba podkrecic w sekcji seriale

http://alltube.pl/seriale-online/

**Comment by MajkiIT** [comment]
@xxcriticxx co tutaj jest źle ?

**Comment by xxcriticxx** [comment]
@MajkiIT wczoraj pod guzikem Przejdź mialem reklame dzisaj mi wyskakuje puste biale okno co zaraz znika

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/eac5f41ad5ed123fcff969fa6d2212cd79844b13#diff-c7961743ee76611643d0539b8a50a2c1

**Comment by xxcriticxx** [comment]
dziala

**Comment by MajkiIT** [comment]
@xxcriticxx Dziękuję
