### ISSUE TITLE
opinie.news

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#13946]
RODO

**Comment by krystian3w** [comment]
Jezu...

**Comment by krystian3w** [comment]
Na razie to chyba tylko `alert-buster.js`...

**Comment by krystian3w** [comment]
Chyba się skończy, że dla Chromowatych to będzie w zgodzie ciasteczkowej jak wyłapie się wymagane cookies.

**Comment by hawkeye116477** [comment]
Można zrobić zgodę/odrzucenie nawet w uBO, a tak właściwie to już dodałem. Oczywiście zgadzamy się, by nie było problemów :smile:
