### ISSUE TITLE
twojglos.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#13948]
reklamy i info o adblocku

**Comment by krystian3w** [comment]
`@@||cdn.cmc-gallery.pl/static/js/ads.js`

@olegwukr

**Comment by MajkiIT** [comment]
`.l-box-`

**Comment by krystian3w** [comment]
a anty-ablock?

**Comment by krystian3w** [comment]
@bogachenko try other sites from CMC media:

> ### List of portals by administrative division
> 
> 
> 
> **mazowieckie**
> [ciechanowinaczej.pl](http://ciechanowinaczej.pl)
> [egarwolin.pl](http://egarwolin.pl)
> [pultusk24.pl](http://pultusk24.pl)
> [plonszczak.pl](http://plonszczak.pl)
> [iotwock.pl](http://iotwock.pl)
> [twojradom.pl](http://twojradom.pl)
> [wio.waw.pl](http://wio.waw.pl)
> [iochota.pl](http://iochota.pl)
> [ipragapoludnie.pl](http://ipragapoludnie.pl)
> [itvpiaseczno.pl](http://itvpiaseczno.pl)
> [imokotow.pl](http://imokotow.pl)
> [ibialoleka.pl](http://ibialoleka.pl)
> [e-wyszogrod.pl](http://e-wyszogrod.pl)
> [izoliborz.pl](http://izoliborz.pl)
> [gpr24.pl](http://gpr24.pl)
> [izabelin24.pl](http://izabelin24.pl)
> [wolomin24.info](http://wolomin24.info)
> [izyrardow.pl](http://izyrardow.pl)
> [ikampinos.pl](http://ikampinos.pl)
> [twojzwolen.pl](http://twojzwolen.pl)
> [babice2](http://babice24.pl)
> 
> **dolnośląskie**
> [24jgora.pl](http://24jgora.pl)
> [olawa24.pl](http://olawa24.pl)
> [nolesnica.pl](http://nolesnica.pl)
> [24wroclaw.pl](http://24wroclaw.pl)
> tulegnica.pl
> 
> **kujawsko-pomorskie**
> [ototorun.pl](http://ototorun.pl)
> [nwloclawek.pl](http://nwloclawek.pl)
> [rypin-cry.pl](http://rypin-cry.pl)
> [lipno-cli.pl](http://lipno-cli.pl)
> [golub-cgd.pl](http://golub-cgd.pl)
> [wabrzezno.pl](http://wabrzezno.pl)
> [brodnica-cbr.pl](http://brodnica-cbr.pl)
> [inowroclaw.info](http://inowroclaw.info)
> [nswiecie.pl](http://nswiecie.pl)
> 
> **łódzkie**
> [lowicz24.eu](http://lowicz24.eu)
> [iskierniewice.pl](http://iskierniewice.pl)
> 
> **podlaskie**
> [mylomza.pl](http://mylomza.pl)
> [zambrow.org](http://zambrow.org)
> [ddb24.pl](http://ddb24.pl)
> [ibielsk.pl](http://ibielsk.pl)
> [kurierpodlaski.pl](http://kurierpodlaski.pl)
> [sejny.net](http://sejny.net)
> [fakty.bialystok.pl](http://fakty.bialystok.pl)
> [esiemiatycze.pl](http://esiemiatycze.pl)
> 
> **lubuskie**
> [egorzow.pl](http://egorzow.pl)
> 
> **zachodniopomorskie**
> [szczecinek.com](http://szczecinek.com)
> 
> **podkarpackie**
> [ekspresjaroslawski.pl](http://ekspresjaroslawski.pl)
> 
> **wielkopolskie**
> [zlotowskie.pl](http://zlotowskie.pl)
> [zycie.pila.pl](http://zycie.pila.pl)
> [zyciekalisza.pl](http://zyciekalisza.pl)
> 
> **opolskie**
> [nowinynyskie.com.pl](http://nowinynyskie.com.pl)
> 
>  
> 
> **LIFESTYLE**
> [splendo.pl](http://splendo.pl)
> [poluje.pl](http://poluje.pl)
> [galopuje.pl](http://galopuje.pl)
> [wterenie.pl](http://wterenie.pl)

**Comment by MajkiIT** [comment]
@krystian3w tak jest ... Adblock

**Comment by bogachenko** [comment]
@krystian3w 
thank/

@MajkiIT
>@krystian3w tak jest ... Adblock

Not everywhere. Here, for example, on these only ads 
```
wio.waw.pl
iochota.pl
ipragapoludnie.pl
ibialoleka.pl
izoliborz.pl
wolomin24.info
ikampinos.pl
twojzwolen.pl
olawa24.pl
24wroclaw.pl
ototorun.pl
wabrzezno.pl
lowicz24.eu
ddb24.pl
fakty.bialystok.pl
esiemiatycze.pl
ekspresjaroslawski.pl
zycie.pila.pl
splendo.pl
poluje.pl
galopuje.pl
```

(by the way, some sites do not open for me, some kind of problem with dns, the proxy does not help)
