### ISSUE TITLE
atutszkola.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13955]
![Screenshot_20190629_142446](https://user-images.githubusercontent.com/36385327/60384076-d2cecf80-9a79-11e9-9101-290e398922f5.png)

**Comment by hawkeye116477** [comment]
My nie naprawiamy po fanboyu :smile:

**Comment by krystian3w** [comment]
On nawet już rok nie chce wywalić wadliwego filtra cookie, zdecydowanie won't fix.
