### ISSUE TITLE
Ta strona zaleca stosowanie AdBlocka

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1395]
![capture](https://cloud.githubusercontent.com/assets/15007183/19776258/5d7843d0-9c41-11e6-9ebd-276888c16bfa.PNG)

**Comment by MajkiIT** [comment]
Dobre.... nawet bardzo dobre.

**Comment by xxcriticxx** [comment]
wrzuc na fb

**Comment by xxcriticxx** [comment]
@MajkiIT or @F4z widze ze dodali 25 second reklamy zanim kanal sie zacznie 

Close the ads in 25 seconds

**Comment by xxcriticxx** [comment]
@F4z da sie cos z odliczaniem zrobic?

**Comment by F4z** [comment]
@xxcriticxx możesz podać link?

**Comment by xxcriticxx** [comment]
`http://tele-miki.pl/Telewizja-animal-planet.html`

**Comment by F4z** [comment]
@xxcriticxx dzięki za link, ale w tej chwili ciężko mi to sprawdzić, bo strona mi się długo wczytuje i nie widzę tego odtwarzacza.

**Comment by xxcriticxx** [comment]
@F4z internet problems???

**Comment by F4z** [comment]
@xxcriticxx raczej nie, inne strony normalnie działają, oprócz tego niewielka część odtwarzaczy z podanej strony też działa, na przykład ten - `http://tele-miki.pl/Telewizja-tvp-canalplus.html` i ten `http://tele-miki.pl/Telewizja-discoverylife.html` ale nie widzę tu żadnego odliczania.

**Comment by xxcriticxx** [comment]
@F4z check this link out

`tele-wizja.com/player/animalplanet.html`

**Comment by xxcriticxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/15007183/19820329/efd8c0ac-9d26-11e6-8ac8-be1b8559c23f.PNG)

**Comment by F4z** [comment]
@xxcriticxx ten link u mnie nie działa.
Masz dodaną do uBlocka listę  `Anti-Adblock Killer | Reek‎`?

**Comment by xxcriticxx** [comment]
nope

dodac?

**Comment by F4z** [comment]
Po dodaniu nie powinieneś tego widzieć.
Ewentualnie dodaj sobie tę regułę:
`privatestream.tv##[id^="timer"]`

**Comment by xxcriticxx** [comment]
@MajkiIT ostatnio krzyczal zeby wylaczyc liste reeka

**Comment by MajkiIT** [comment]
@xxcriticxx ja kiedy?
