### ISSUE TITLE
wieleliter.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13957]
Napisy "Reklama"
https://wieleliter.pl/2019/06/27/koniec-kolejek-bramki-abc-skroca-czas-odprawy-na-lotnisku-choina/
![Screenshot_20190629_142757](https://user-images.githubusercontent.com/36385327/60384135-4e308100-9a7a-11e9-83b6-64ae97930c9d.png)
![Screenshot_20190629_142812](https://user-images.githubusercontent.com/36385327/60384137-4e308100-9a7a-11e9-9c92-b6857461f812.png)

**Comment by MajkiIT** [comment]
`##.wiele-widget.widget`
