### ISSUE TITLE
otodom.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13965]
Social
![Screenshot_20190701_023139](https://user-images.githubusercontent.com/36385327/60404365-8fbf4a00-9ba8-11e9-9da6-a71e33164df4.png)

https://www.otodom.pl/oferta/mieszkanie-ID3ALrl.html

**Comment by krystian3w** [comment]
`##.socialbox` - sprawdź czy ci się nie wyłączył filtr Fanboya @xMaap, bo mi on już wycina.
