### ISSUE TITLE
CCleaner/AVG Browser

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#13967]
> - http://www.benchmark.pl/aktualnosci/ccleaner-browser-bezpieczna-przegladarka-download.html
> - https://www.dobreprogramy.pl/ccleaner-browser-przegladarka-internetowa,News,102514.html
> - https://www.komputerswiat.pl/aktualnosci/programy/ccleaner-browser-nowa-przegladarka-skupiona-na-prywatnosci/02y510q
> - https://www.instalki.pl/aktualnosci/software/36389-ccleaner-browser-to-nowa-przegladarka-dla-milosnikow-czystosci-i-bezpieczenstwa.html

Niby Avast Browser w osłonce przejętego CCleaner.

**Comment by krystian3w** [comment]
Jak ustaliłem to dwa uBlocki Origin są w wydaniu `1.18.16.420` czyli z dwa do tyłu i ciekawe czy one będą aktualizowane...

**Comment by hawkeye116477** [comment]
@krystian3w Oficjalnie nie wspieramy, liczy się tylko uBO w wersji 1.20+ i Nano oparty na podobnej wersji uBO, a jak ktoś nie ma to musi się przesiąść, nie będziemy czekać aż Avast wyda przemalowanego cudacznego Adblockera w nowej wersji, zresztą pewnie tak dużo osób tego nie używa, a co zaskakujące jest, przy instalacji antywirusa Avast proponują Chrome, a nie własną przeglądarkę :smile:

**Comment by krystian3w** [comment]
```
​https://ext-update.avastbrowser.com/adblock/13001/filterlist.txt
```

Czyżby oni odblokowali składnie document, by odblokowywać reklamy?

**Comment by krystian3w** [comment]
```
https://ext-update.avastbrowser.com/adblock/13001/filterlist.txt
```

```css
@@||ads.google.com$domain=ads.google.com
@@||apnanalytics.com^
@@||ask.com^
@@||avast.com^
@@||avastbrowser.com^
@@||avg.com^
@@||avgbrowser.com^
@@||bing.com^
@@||booking.com^
@@||http://search.ocra.info/^
@@||http://ocra1-2w3auu9iq9yw.stackpathdns.com/^
@@||iacapps.com^
@@||mysearch.com^
@@||myway.com^
@@||priceline.com^
@@||sse-iacapps.com^
@@||video.aktualne.cz$domain=aktualne.cz
@@||yahoo.co.jp^
@@||yahoo.com^
@@||yimg.com^
```

Czyżby oni odblokowali składnie `document`, by odblokowywać reklamy?

**Comment by krystian3w** [comment]
https://www.avg.com/pl-pl/secure-browser

**Comment by hawkeye116477** [comment]
Rany, po co im tyle tego. Avast Browser, AVG Browser i CCleaner Browser...

**Comment by krystian3w** [comment]
Wygląda, że kopiowanie uBo już im nie na rękę i przerwali pewnie we wrześniu 2020.
