### ISSUE TITLE
naekranie.pl

### ISSUE THREAD

**Issue by figureliusz** [MajkiIT/polish-ads-filter#13966]
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wyłączyć adblocka (nie plusa)
2. domyślne filtry wyłączają elementy strony: naekranie poleca oraz np. zdjęcie recenzenta
3. 

### Moja konfiguracja
**Przeglądarka internetowa: CHROME**

**Rozszerzenia i skrypty:**

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by figureliusz** [comment]
![naekranierecenzja](https://user-images.githubusercontent.com/52409974/60433575-739dc600-9c05-11e9-9601-1b330d044778.jpg)
![naekraniepoleca](https://user-images.githubusercontent.com/52409974/60433576-74365c80-9c05-11e9-8177-ad8afa73e5cc.jpg)

**Comment by xxcriticxx** [comment]
@figureliusz podaj link please

**Comment by xxcriticxx** [comment]
btw nowa tapeta jest 

![Capture](https://user-images.githubusercontent.com/15007183/60450772-970e4400-9bf8-11e9-840a-4f5416b31311.PNG)

**Comment by krystian3w** [comment]
```
##[class^="r"]:not([class^="rate"]):not([class^="recommend"]) > div > [class^="r"]:not([class^="rate"]):not([class^="recommend"])
```

taka zmiana przywróci widget rekomendowane.

---

Awatara recenzenta szukać nie będę, za dużo zachodu...

**Comment by krystian3w** [comment]
@xxcriticxx te nowe reklamy to są już w części na literę "S", pewnie wystarczy przetestować gdzie zostawiamy R a gdzie już zmieniamy na S.

**Comment by xxcriticxx** [comment]
@krystian3w nie da zrobic reguly od A do Z for future?

**Comment by krystian3w** [comment]
No raczej się nie opłaca, bo się zrobi z 120 linii pod samo naekranie.pl - opcjonalnie można skryptem ubijać, noszą znamiona ładowania z plików JS.

**Comment by xxcriticxx** [comment]
Zapytajmy @MajkiIT co o tym myśli

**Comment by krystian3w** [comment]
Ja mogę zobaczyć czy może AdGuard ma jakieś skrypty na reklamy w `naekranie.pl`, replace raczej nas nie interesuje aż nie będzie chętny na to grohill by dodać do przyszłych wersji uBO.

**Comment by xxcriticxx** [comment]
no teraz gitara

**Comment by figureliusz** [comment]
> @figureliusz podaj link please

https://naekranie.pl - ten box "na ekranie poleca" leci chyba ROS
A ikonki recenzentów - są przy recenzjach :)
Na przykład: https://naekranie.pl/recenzje/swiat-miniony-recenzja-ksiazki

**Comment by krystian3w** [comment]
```
##[class^="r"]:not([class^="rate"]):not([class^="recommend"]):not([class^="reviewer"]) > div > [class^="r"]:not([class^="rate"]):not([class^="recommend"]):not([class^="reviewer"])
```

I wróci awatar.

**Comment by xxcriticxx** [comment]
@krystian3w cinema city is back na linku od @figureliusz 

![Capture](https://user-images.githubusercontent.com/15007183/60508067-95478d80-9c97-11e9-87b1-cac64ca47dbe.PNG)

**Comment by xxcriticxx** [comment]
od czasu do czasu mam netflix reklame na caly screen 

![Capture](https://user-images.githubusercontent.com/15007183/60672662-f1e7ab80-9e43-11e9-9937-8a88c5146fe4.PNG)

**Comment by krystian3w** [comment]
`naekranie.pl##body > div[id]:not([class]):has(header, iframe)`
`naekranie.pl##body.ws-active:style(overflow: auto !important;)`


takie dwa niby powinny rozwiązać problem

**Comment by krystian3w** [comment]
@gwarser masz pomysł jak skryptem ubić reklamy albo czy taki zapis jest poprawny:

`:has(header, iframe)` - czy on zawsze znajduje oba tagi html i tylko wtedy ukrywa?

**Comment by krystian3w** [comment]
Jak coś AdamWr wymyślił jakiś skrypt na tę wielką reklamę, na małe musiałby pomoc jakby znowu zmienili literki.

**Comment by hawkeye116477** [comment]
@MajkiIT Dlaczego zamykasz jak nie naprawione?

**Comment by gwarser** [comment]
@krystian3w  Ja to nawet nie wiem czy gorhill myślał o tym, czy to będzie obsługiwało przecinki do łączenia kilku selektorów. Dodałem to do zakładek kilka dni temu, ale nie mam czasu sprawdzić w kodzie jak to działa.

Niby w CSS4 będzie specjalny "operator" do tego (już chyba to znalazłeś?)

**Comment by krystian3w** [comment]
> (już chyba to znalazłeś?)

Nie.

---

`:is()` to raczej coś innego, to jak z lenistwa nie chcemy wypisywać podobnych. Nie umie się w SCSS/LESS ani żaden język preprocesorowy CSS.

No i trochę szkoda, że jednak bug w Quantum/Gecko i WebKit/Blink (webkitu od Apple nie mam jak testować).
