### ISSUE TITLE
centrumxp.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#13960]
### Zrzut ekranu
![Screenshot_20190629_233219](https://user-images.githubusercontent.com/19818572/60389668-48608d00-9ac6-11e9-8150-cded74452115.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Reklama MS Office i kablówki.
`https://www.centrumxp.pl/Publikacja/Microsoft-przejmuje-i-udostepnia-za-darmo-narzedzie-Pull-Panda-dla-platformy-GitHub`

**Comment by krystian3w** [comment]
`||www.centrumxp.pl/api/Images/GrafikiOsadzone/osadzony_`
`||www.centrumxp.pl/api/Images/Bannery/`
`centrumxp.pl##.article > p > span`

myślę, że osadzone i Bannery to same reklamy, a span to wycięcie napisu "Reklama".

**Comment by krystian3w** [comment]
Już łobuzy pozmieniały, @seba2282 mówi że za mało czytamy centrum xp.
