### ISSUE TITLE
elevensports.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13970]
RODO
![Screenshot_20190702_142629](https://user-images.githubusercontent.com/36385327/60512700-95667e00-9cd5-11e9-9081-58ee1cfd0bd8.png)
Social
![Screenshot_20190702_142641](https://user-images.githubusercontent.com/36385327/60512711-9b5c5f00-9cd5-11e9-8c27-8a4988a32c6d.png)

**Comment by krystian3w** [comment]
Ktoś namierzył więcej tego, IPLA TV ma identyczne.

**Comment by blocker999** [comment]
@krystian3w  Masz ; 

https://mgr.farm/

**Comment by krystian3w** [comment]
To nie to samo i oni mają wciśnięte "jestem lekarzem" a większość nie jest.
