### ISSUE TITLE
niepoprawni.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1397]
ad block 

http://niepoprawni.pl/przewodnik/polityka-reklam

Szanowny Użytkowniku!

Używasz programu blokującego reklamy - AdBlock Plus lub innego podobnego.
Nie mamy agresywnych reklam. Mamy tylko banery do partnerów, zaprzyjaźnionych portali, cennych inicjatyw. Jeśli pojawią się nawet reklamy to nie są agresywne, nie zasłaniają innych treści tak jak w innych serwisach komercyjnych. Prosimy odblokuj naszą stronę.

Jak zrobić to w Adblock Plus?

Kliknij w małą ikonkę z czerwonym znakiem stopu i z łapką lub literami ABP w środku. Następnie kliknij: wstrzymaj blokowanie na stronach w tej domenie lub wyłącz blokowanie na niepoprawni.pl.

Dziękujemy! :)
Nie trzeba walczyć z reklamami w naszym serwisie :)
Pozdrawiamy!
Administracja 

P.s. Po odblokowaniu pewnie nie zauważysz różnicy :)

P.s. 2 Jeśli uważasz, że nas odblokowałeś, a ten komunikat nadal wyskakuje - upewnij się że odblokowałeś naszą całą domenę.

**Comment by F4z** [comment]
`||niepoprawni.pl/sites/all/libraries/copier/bck.js$script`
lub to
`niepoprawni.pl#@##headerAd`

**Comment by MajkiIT** [comment]
@F4z dzięki
