### ISSUE TITLE
pilot.wp.pl/tv

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#13986]
https://pilot.wp.pl/tv

Jak się kliknie na dowolny kanał TV to nic się nie dzieje. Najnowszy Adguard. Wyłączyłem nawet dodatkowe źródła filtrów i bez zmian. 

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.1.xxxx NIGHTLY** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
|Disable cache for 3rd-party requests
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuckadblock
| **SECTION :: Ads**
| Adguard Base Filter 
| EasyList
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| EasyPrivacy
| Fanboy's Anti-Facebook List 
| Fanboy's Enhanced Tracking List 
| **SECTION :: Social**
| Adguard Social Filter
| Fanboy's Social Blocking List 
| **SECTION :: Annoyances**
| Adblock Warning Removal List
| Adguard Annoyances
| Fanboy's Annoyances 
| Fanboy's Cookiemonster List
| **SECTION :: Security**
| Malware Domains
| Spam404
| NoCoin Filter List
| **SECTION :: Customs**
| AlleBlock
| EasyList Polish 
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

Ustawienia adguard:
[20190701_131621_adg_settings_7.1.2817.0.zip](https://github.com/MajkiIT/polish-ads-filter/files/3360125/20190701_131621_adg_settings_7.1.2817.0.zip)

@Alex-302 

![scr-1562260842-001](https://user-images.githubusercontent.com/9846948/60681824-f8e8db00-9e90-11e9-8c85-4415c6bab2db.png)
![scr-1562260855-001](https://user-images.githubusercontent.com/9846948/60681825-f8e8db00-9e90-11e9-8f77-6307fe230309.png)

**Comment by krystian3w** [comment]
Jak bez stealth mode?

**Comment by FadeMind** [comment]
@krystian3w bez zmian.

**Comment by krystian3w** [comment]
@MajkiIT ale nie naprawiłeś buga ani nie przerzuciłeś do adguard "isues"...

**Comment by FadeMind** [comment]
@krystian3w w nanoAdblocker + nanoDefender odtwarzanie na WP działa bez problemu, więc to wina wewnętrzna Adguarda.
