### ISSUE TITLE
polishteam.ru

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#13994]
cookies

test link:
https://polishteam.ru/forum/

**Comment by krystian3w** [comment]
no bo ruskie...

**Comment by xxcriticxx** [comment]
mam podac do adguarada?

**Comment by krystian3w** [comment]
Nie, jedynie mówię czemu wycieka pasek a tak to poczekaj aż @hawkeye116477 zrobi kolejne PR.
