### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by ggargul** [MajkiIT/polish-ads-filter#13991]
Reklamy:

`https://www.elektroda.pl/`

![elektroda1a](https://user-images.githubusercontent.com/51117730/60688013-dcf63100-9eb2-11e9-94b7-22539c7a10c5.gif)

![elektroda1](https://user-images.githubusercontent.com/51117730/60688012-dc5d9a80-9eb2-11e9-9b3f-3ee64d5578a5.gif)

`https://www.elektroda.pl/rtvforum/forums.html`

![elektroda2](https://user-images.githubusercontent.com/51117730/60688014-dcf63100-9eb2-11e9-81cc-66b22b496d9d.gif)

`https://www.elektroda.pl/rtvforum/topic3508518.html`

![elektroda3](https://user-images.githubusercontent.com/51117730/60688015-dcf63100-9eb2-11e9-8f8f-ec6016e5822f.gif)
![elektroda3b](https://user-images.githubusercontent.com/51117730/60688016-dcf63100-9eb2-11e9-97d9-1abcbad4a629.gif)

**Comment by gulson** [comment]
Bardzo bym prosił nie blokować tych reklam. Serwis z czegoś musi żyć. Reklamy są nieinwazyjne, zgodne z standardami, są to tak naprawdę zwykłe grafiki.

**Comment by xxcriticxx** [comment]
@ggargul już to przerabialiśmy nie opłaca się jutro i tak pozmieniają nazwy div

Ostatecznie można dodać do filtrów własnych

**Comment by ggargul** [comment]
> gulson : Bardzo bym prosił nie blokować tych reklam. Serwis z czegoś musi żyć. Reklamy są nieinwazyjne, zgodne z standardami, są to tak naprawdę zwykłe grafiki.

Dobry żart, bo jest zupełnie odwrotnie, reklamy zamieszczone w tym wątku są reklamami inwazyjnymi, pan dobrze o tym wie i pan zwyczajnie kłamie.

> gulson : zgodne z standardami

Z którymi, bo na pewno nie z tymi: 
https://acceptableads.com/en/about/criteria. (wersja angielska)
https://translate.google.pl/translate?hl=pl&sl=en&tl=pl&u=https%3A%2F%2Facceptableads.com%2Fen%2Fabout%2Fcriteria (wersja polska przez translator)

> gulson : Reklamy są nieinwazyjne

Kłamstwo - reklamy są inwazyjne, bo łamią 3 główne kryteria + 1 dodatkowe (umieszczone w podanych wyżej linkach):  

01 PLACEMENT (POŁOŻENIE), 

"Reklamy nie mogą zakłócać naturalnego przepływu odczytu użytkownika. Takie reklamy muszą być umieszczane na górze, stronie lub pod Treścią podstawową. 1" 

czyli reklamy nie mogą znajdować się pomiędzy newsami, artykułami albo postami forum, czyli przeszkadzać w czytaniu głównej treści przez odwiedzającego i odwracać jego uwagę, TĘ ZASADĘ ŁAMIĄ PRAWIE WSZYSTKIE REKLAMY PRZEDSTAWIONE NA WSZYSTKICH ZRZUTACH EKRANU W TYM WĄTKU!

02 DISTINCTION (OZNACZENIE) - 

"Reklamy powinny być zawsze rozpoznawalne jako reklamy i odróżniać się od wszystkich innych treści (np. Nie ukrywają etykiety, nie wprowadzają użytkowników w błąd, że reklama jest częścią podstawowej treści). Reklamy powinny być wyraźnie oznaczone słowem „reklama” lub jego odpowiednikiem." 

czyli reklamy nie mogą być pozbawione tytułu "REKLAMA" lub zbliżonego, podstępnie stwarzając wrażenie, że są jednym z newsów, arttkułów lub postów,  TĘ ZASADĘ ŁAMIĄ WSZYSTKIE REKLAMY PRZEDSTAWIONE NA WSZYSTKICH ZRZUTACH EKRANU W TYM WĄTKU!

03 SIZE (ROZMIAR) - reklamy nie mogą być za duże, TĘ ZASADĘ ŁAMIĄ PRAWIE WSZYSTKIE REKLAMY PRZEDSTAWIONE NA WSZYSTKICH ZRZUTACH EKRANU W TYM WĄTKU!

> gulson : są to tak naprawdę zwykłe grafiki.

Kłamstwo - To nie są zwykłe grafiki, to są animowane grafiki! - "Co nie jest uważane za dopuszczalną reklamę? Animowne reklamy."

Ale kłamczuch.

**Comment by gulson** [comment]
Podtrzymuję poprzednie zdanie. Już sam fakt, że potrafisz odróżnić reklamy od zwykłych treści oznacza, że reklamy są odpowiednio oddzielone. Proszę nie wyzywaj kogoś od kłamców, tylko dlatego, że ktoś ma odmienną opinie. Taka rada na przyszłość.

**Comment by xMaap** [comment]
Odróżnia ponieważ świecą po oczach, a niektóre migają jak głupie.

**Comment by ggargul** [comment]
> gulson : Podtrzymuję poprzednie zdanie. Już sam fakt, że potrafisz odróżnić reklamy od zwykłych treści oznacza, że reklamy są odpowiednio oddzielone.

Ja potrafię bo jestem zaawansowanym użytkownikiem internetu, ale wielu mniej zaawansowanych użytkowników "typowych Kowalskich" może nie odróżnić.

> gulson : Proszę nie wyzywaj kogoś od kłamców, tylko dlatego, że ktoś ma odmienną opinie. Taka rada na przyszłość.

Moja rada, że nie ma zbytnio sensu z tobą zbytnio dyuskutować, bo powoływałeś się na jakieś bliżej nieokreślone standardy, a gdy pociągnąłem za język i zapytałem które to standardy (jakiś link / źrodło?) to nie podałeś żródła / linku, a na mój materiał dowodowy oparty o realne standardy, że reklamy zaprezentowane w tym wątku są inwazyjne, odpowiadasz swoimi prywatnymi jednoosobowymi subiektywnymi opiniami, które nie mogą być wyznacznikiem czy reklama jest inwazyjna czy nie, bo od  stwierdzania tego są dokumenty / standardy, (link / źródło), a nie jednosobowe prywatne opinie osoby która dodatkowo próbuje być sędzią we własnej sprawie zgodnie z przysłowiem: każda lisza swój ogonek chwali, więc dopóki nie zanczniesz opierać się na czymś realnym, to twoje prywatne jednoosobowe opinie nikogo za bardzo nie interesują i nie mają mocy prawnej.

> gulson : Blokujecie AdSense oraz inne reklamy. Jeśli jakąkolwiek nieinwazyjną reklamę uda się w ogóle pokazać użytkownikowi, to zaraz jest dopisywana do Waszych filtrów. Co jest nie w porządku w tym, że darmowy serwis elektroda.pl próbuje zarobić na swoje utrzymanie?

Do tego się nie odniosę bo to nie moja działka, ja się tylko póki co wypowiadam co do tego konkretnego wątku i reklam w nim zaprezentowanych.
