### ISSUE TITLE
kawiarniany.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14001]
Social
![Screenshot_20190707_182922](https://user-images.githubusercontent.com/36385327/60771245-5d9c7380-a0e5-11e9-8af1-03893ceb57c9.png)

Pozostałość po reklamie Booking
![Screenshot_20190707_182639](https://user-images.githubusercontent.com/36385327/60771252-6f7e1680-a0e5-11e9-8d65-90b04351daf6.png)
![Screenshot_20190707_182648](https://user-images.githubusercontent.com/36385327/60771253-6f7e1680-a0e5-11e9-891f-35ac894ce1da.png)

**Comment by krystian3w** [comment]
Nie umiem złapać tego social "colorbox" pop-upa.

**Comment by xMaap** [comment]
@krystian3w to wyskakuje po jakimś czasie.

**Comment by krystian3w** [comment]
Nie mają jakieś koparki, strona cholernie muli.

**Comment by xMaap** [comment]
Nie zauważyłem aby coś muliło no chyba, że coś u mnie blokuje.
