### ISSUE TITLE
Firefox Premium

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#14019]
Wkrótce pojawi się :fox_face: w edycji Premium. Za opłatą będzie brak reklam na stronach internetowych, VPN, dysk internetowy, synchronizacja artykułów i utworów audio oraz treści od najlepszych autorów na świecie (oczywiście m.in. od grupy WP :smiley:). Najtańszy abonament będzie wynosił ok 19 zł m/c, będą też 2 droższe opcje za ok. 38 zł i 49 zł. Usługa wystartuje w październiku tego roku.
Ktoś zainteresowany, będzie ktoś płacił za treści od WP bez reklam :smile:?

<img src="https://rootblog.pl/wp-content/uploads/2019/07/chrome_LICBmWZWJR.png">

**Comment by krystian3w** [comment]
Powinni spróbować zrobić okres testowy 30 - 90 dni, a nie jak netflix to likwidować.

Niby płatność kartą wystarczająco ogranicza opcje kombinować by z kilka lat przenetflixować na darmówce.

**Comment by krystian3w** [comment]
@hawkeye116477 

```
||ocdn.eu/pulscms-transforms/1/1lgk9kpturbxy82mja2ymyzntrmztrkotc5odhlogmyogm3mjc4otnios5wbmeslqlnaxqawsovagdnavjcw4ghmau$image
```

Warto blokować ten denny obrazek o tekstach sponsorowanych?

**Comment by hawkeye116477** [comment]
@krystian3w Nie wiem o czym ty mówisz, ale to już chyba nie na ten temat, więc proponowałbym przenieść dyskusję do innego wątku lub na nasz czat PFT :smile:

**Comment by blocker999** [comment]
Za darmo tego niechce bo blokuje tylko reklamy na stronach a jak to się będzie mieć na filmikach z vod albo yt, no i co z cookies, rodo i Elementami Irytującymi np pop-up ?

**Comment by krystian3w** [comment]
A kto powiedział że reklamy będą wycinać modułem ochrony prywatności bazującym na Disconnect.

**Comment by krystian3w** [comment]
Coś ruszyło, niby dalej Proxy Addon darmowy, jedynie wersja `15` ma ulepszone wykrywanie czy jesteśmy w USA (VPN uruchomiony na PC / ze smartfona raczej nie pomoże) - czyli trzeba używać `14`.
