### ISSUE TITLE
gram.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14023]
```
https://www.gram.pl/
https://forum.gram.pl/
```
Napisy reklama
![Screenshot_20190709_123423](https://user-images.githubusercontent.com/36385327/60881505-2a252a80-a246-11e9-9902-c5cb47735e61.png)

`https://forum.gram.pl/temat/113110-problem-z-gra/`
Social
![Screenshot_20190709_123534](https://user-images.githubusercontent.com/36385327/60881556-3c9f6400-a246-11e9-9de4-51a9c6ca28b8.png)

**Comment by krystian3w** [comment]
@hawkeye116477  masz ten social?

@xMaap dalej uBlock Origin? Nie masz w loggerze jakiegoś zielonego **generichide**?

**Comment by hawkeye116477** [comment]
@krystian3w Nie mam sociala.

**Comment by krystian3w** [comment]
Najpewniej to wina nieaktywnego Fanboy Social po przejściu na uBlock Origin, tak sądzę.

**Comment by hawkeye116477** [comment]
A jeśli chodzi o te napisy reklamowe, to może `forum.gram.pl##.d-flex.justify-content-center:before, .d-flex.justify-content-end:before, .d-flex.justify-content-start:before`

**Comment by krystian3w** [comment]
I może na głównej:

`www.gram.pl##.text-ad-center`

raczej nie mają anty-adblocka.

**Comment by xMaap** [comment]
@krystian3w chyba przypadkowo wyłączyłem Fanboy. Tak uBlock Origin.
