### ISSUE TITLE
pocztowy.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14025]
`https://www.pocztowy.pl
`
Social
![Screenshot_20190709_124006](https://user-images.githubusercontent.com/36385327/60881868-eb43a480-a246-11e9-96bc-1d14d1bc25d3.png)

```
https://ir.pocztowy.pl/
https://media.pocztowy.pl/
https://ekonomiczny.pocztowy.pl/
```
Social
![Screenshot_20190709_124110](https://user-images.githubusercontent.com/36385327/60881900-03b3bf00-a247-11e9-9876-19bac8ef41ba.png)

**Comment by krystian3w** [comment]
@hawkeye116477 ja tam znowu nie mam.

@xMaap Lista obowiązkowa Fanboy Social włączona w uBlock Origin?

[![Fanboy Social][Fanboy Social]](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/fanboy-social.txt&title=Fanboy-Social)

[Fanboy Social]: https://img.shields.io/badge/INT-Fanboy%20Social-blue.svg

**Comment by krystian3w** [comment]
@xxcriticxx cookies przez przypadek jako label, na zdjęciach nie widzę i na żadnym pocztowym podanym nie wycieka.
