### ISSUE TITLE
eurobank.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14026]
`https://eurobank.pl/
`
Social
![Screenshot_20190709_124330](https://user-images.githubusercontent.com/36385327/60882052-59886700-a247-11e9-9930-48a9b1f5c490.png)

`https://kredyt-eurobank.pl/
`
Cookies
![Screenshot_20190709_124412](https://user-images.githubusercontent.com/36385327/60882112-7c1a8000-a247-11e9-97fe-c6ebe2c6ce39.png)

**Comment by krystian3w** [comment]
Socialu znowu brak, nie możliwe by tyle wyciekało z braku userCSS / manipulacji observeMutatorem.

---

![Fanboy Social][Fanboy Social] - [subskrybuj!](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/fanboy-social.txt&title=Fanboy%20Social)

[Fanboy Social]: https://img.shields.io/badge/INT-Fanboy%20Social-blue.svg
