### ISSUE TITLE
etsy.com/pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14021]
Social
![Screenshot_20190709_123129](https://user-images.githubusercontent.com/36385327/60881300-b125d300-a245-11e9-8aeb-9fc7cd38ae67.png)

**Comment by krystian3w** [comment]
@xMaap czym ci Fanboy wycina popup Cookies/RODO?

**Comment by xMaap** [comment]
@krystian3w Wycina.
