### ISSUE TITLE
start.ingbusiness.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14028]
Cookies
![Screenshot_20190709_125034](https://user-images.githubusercontent.com/36385327/60882510-580b6e80-a248-11e9-9c55-159abffb307b.png)

**Comment by xMaap** [comment]
`https://spolecznosc.ingbank.pl/`
Social
![Screenshot_20190709_125142](https://user-images.githubusercontent.com/36385327/60882574-7cffe180-a248-11e9-84b7-74b1cd7951a7.png)

**Comment by krystian3w** [comment]
U mnie obu brak, więc cookies może zniknie przy następnym PR a social chyba wycieka z dziury w konfiguracji uBlock Origin.

I raczej wykluczam że tak cię dopieszczają nagle polskimi beta nowymi dizajnami, by trzeba robić koretky na wakacje.

---

![Fanboy Social][Fanboy Social] - [subskrybuj!](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/fanboy-social.txt&title=Fanboy%20Social)

[Fanboy Social]: https://img.shields.io/badge/INT-Fanboy%20Social-blue.svg

**Comment by krystian3w** [comment]
U mnie cookies brak na biznesie.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/3cf947a0ee0f7cef2a3866dc45b8184ccf1f37b1/cookies_filters/adblock_cookies.txt#L2814

niby to mi wycina taki w pop-upie, nie wiem więc czemu ty masz w postaci paska.

**Comment by krystian3w** [comment]
`https://start.ingbusiness.pl/ing2/login/`...
