### ISSUE TITLE
pkobp.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14029]
Social
![Screenshot_20190709_125341](https://user-images.githubusercontent.com/36385327/60882739-cc461200-a248-11e9-993b-0d939ebe20f8.png)

**Comment by krystian3w** [comment]
Nie mam, musisz mieć wyłączony Fanboy Social.

Jedynie co mogę to naprawić RSS, fanboy go wyciął generykiem "`.social-icon`"
