### ISSUE TITLE
santander.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14031]
Social
![Screenshot_20190709_125603](https://user-images.githubusercontent.com/36385327/60882948-2f37a900-a249-11e9-8b25-e7b43886aa2f.png)

**Comment by krystian3w** [comment]
Mam kompletnie przesunięty język na lewo a nie 2 na klika ikonek.

---

![Fanboy Social][Fanboy Social] - [subskrybuj!](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/fanboy-social.txt&title=Fanboy%20Social)

[Fanboy Social]: https://img.shields.io/badge/INT-Fanboy%20Social-blue.svg
