### ISSUE TITLE
pekao.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14030]
Social
![Screenshot_20190709_125510](https://user-images.githubusercontent.com/36385327/60882843-00213780-a249-11e9-94e5-ce40c696262c.png)

**Comment by krystian3w** [comment]
U mnie nie ma.

---

![Fanboy Social][Fanboy Social] - [subskrybuj!](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/fanboy-social.txt&title=Fanboy%20Social)

[Fanboy Social]: https://img.shields.io/badge/INT-Fanboy%20Social-blue.svg

**Comment by xMaap** [comment]
Ale tutaj będzie https://www.dm.pkobp.pl/
![Screenshot_20190710_025023](https://user-images.githubusercontent.com/36385327/60932296-a7d84d00-a2bd-11e9-9787-c76d0c43ab7b.png)

**Comment by krystian3w** [comment]
To się poprawi, nie będzie wypisywania subdomen np. "bankowoscprywatna.".

**Comment by xMaap** [comment]
I jeszcze tutaj
`https://www.pkopte.pl
`![Screenshot_20190710_153651](https://user-images.githubusercontent.com/36385327/60973533-c293db80-a328-11e9-865f-ac66d695cb2e.png)
