### ISSUE TITLE
bankmillennium.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14036]
Social
![Screenshot_20190710_023655](https://user-images.githubusercontent.com/36385327/60931910-cccbc080-a2bb-11e9-8e58-e7f06ce30bd7.png)

**Comment by krystian3w** [comment]
goodie to już social? @blocker999  / @hawkeye116477

**Comment by hawkeye116477** [comment]
Raczej nie.

**Comment by krystian3w** [comment]
to może zostać "`not("goodie")`".

Chyba, że bank nagle uruchomi RSS albo inne cuda wianki np. Wiki w stopce...

**Comment by blocker999** [comment]
ok goodie zostaje
