### ISSUE TITLE
interia.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14032]
coś blokuje panel z artykułami ( po lewo )

![interia](https://user-images.githubusercontent.com/23176832/60908982-66c04880-a27d-11e9-8503-418196942ffe.png)

**Comment by krystian3w** [comment]
Mnie nic... 🐳 🐋

**Comment by krystian3w** [comment]
Pokaż logger i co masz na liście spod przycisku "`</>`".
