### ISSUE TITLE
cryptoprofit.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#14045]
### Zrzut ekranu
![Screenshot_20190711_193408](https://user-images.githubusercontent.com/19818572/61072092-dfa4d900-a412-11e9-967a-b24a28d1faca.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Resztka po reklamie. 4 dni temu reguła została usunięta, zapewne z racji tego, że tymczasowo strona nie działała, nieładnie @MajkiIT, dlatego zawsze lepiej dodatkowo sprawdzać za pomocą whois (a najlepiej polecam nasz skrypt/nakładkę => https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/master/scripts/expired_domains.sh) :stuck_out_tongue:  

https://github.com/MajkiIT/polish-ads-filter/commit/af9dbf29b7004c5cb1f0b37442713a3bbed79a28#diff-711027ed0794992ae3b8710d874f3df7

**Comment by krystian3w** [comment]
Ja tam tego nie mam.

**Comment by hawkeye116477** [comment]
@krystian3w Reklama już nieaktualna, ale resztka jest :smile:

**Comment by krystian3w** [comment]
Ciekawi mnie jaka sieciówka go wycina, bo nic kosmetycznego ani skryptowego.

**Comment by krystian3w** [comment]
Może taki będzie fajniejszy niż jakiś "custom 2":

```
##.header-banner
```

I w artykułach jest jakaś wewnętrzna reklama z kodem rabatowym:

> ![obraz](https://user-images.githubusercontent.com/35370833/61072333-56da6d00-a413-11e9-94fc-0ebe466ea8df.png) |
> --- |

@KonoromiHimaries ?

**Comment by hawkeye116477** [comment]
Jakieś resztki też są po prawej w artykułach.

**Comment by MajkiIT** [comment]
@hawkeye116477 @krystian3w Dziekuję
