### ISSUE TITLE
silesia.info.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14055]
Na stronach tej grupy RODO znika bardzo powoli ( lista stron jest na głównej, po prawo " wybierz miasto " )

@krystian3w da się to przyśpieszyć ?

**Comment by krystian3w** [comment]
Nie zawsze umiem to odtworzyć, niby wczoraj mi migło na "rudzie śląskiej".

**Comment by krystian3w** [comment]
Na Chromowatych chyba nie wymyślę nic poza CSS-em by nie było "dubli" a próbowało szybciej ukrywać od:

https://github.com/MajkiIT/polish-ads-filter/blob/f13f09b5c9af88b143d76bd5236b02b585e66797/cookies_filters/adblock_cookies.txt#L2907

**Comment by hawkeye116477** [comment]
A  takie coś `rudaslaska.com.pl##+js(nano-remove-elements-onready.js, #rodo-popup)`?

**Comment by krystian3w** [comment]
Kij wie trzeba by w trybie prywatnym testować.

**Comment by krystian3w** [comment]
Dobra odpada https://github.com/MajkiIT/polish-ads-filter/issues/14055#issuecomment-511134960, dalej miga na 1 wejście:

https://rudaslaska.com.pl/i,ruda-slaska-supermarket-intermarche-na-halembie-zostanie-zlikwidowany,200274,1369254.html

**Comment by hawkeye116477** [comment]
@krystian3w No to coś chyba po twojej stronie nie trybi, bo u mnie nic nie miga, od razu widać różnicę.
