### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14059]
@MajkiIT możesz podać ile osób używa listy? Czy te info jest tajne?

**Comment by krystian3w** [comment]
> smile, sweet, sister, sadistic

https://www.youtube.com/watch?v=IvkNeXkF5CY

:question:

**Comment by MajkiIT** [comment]
@xxcriticxx dokładnych danych nie mam ale ze starego linku jest Ok 800 tys pobrań dziennie. Na github nie ma licznika.
