### ISSUE TITLE
AdGuard odfiltruje kropki

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14065]
Przykład na Węgrach:

```
!----- TEMPORARY -----
! travis failed to build filters - extended CSS issue
! https://github.com/AdguardTeam/ExtendedCss/issues/75
prohardver.hu##p:-abp-contains(Amikor a szoftver illeszkedik a meglévő üzleti folyamatokhoz.)
prohardver.hu##div[id="center"] > div:-abp-has(div):-abp-has(a):-abp-has(Mostantól bármely bank ügyfelének elérhető a mobilfizetés élménye.)
```

---

`ogloszenioteka.pl#?#div.article.lfloat:-abp-contains(Zapraszamy na nasz profil na Facebooku.)`

`puccini.pl#?#.page > .col1-layout.main-container:-abp-contains(na instagramie.)`

raczej trzeba je usunąć, bo oni chyba je przetwarzają na niejawny regex jako każdy dowlony znak jak miewam.

**Comment by hawkeye116477** [comment]
@krystian3w No to się nie czaj, tylko usuwaj :smile:.

**Comment by hawkeye116477** [comment]
@krystian3w Co nie zamykasz?
