### ISSUE TITLE
ciechanowinaczej.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14063]
event tło w artykułach:

https://ciechanowinaczej.pl/artykul/zasnela-za-kierownica/719775

![obraz](https://user-images.githubusercontent.com/35370833/61150774-7f7e6780-a4e4-11e9-8338-c2844d1a4ac1.png) |
--- |

to już do EI @hawkeye116477  / @blocker999  / @KonoromiHimaries?

**Comment by hawkeye116477** [comment]
Ale ja tego nie mam.

**Comment by krystian3w** [comment]
A czyli jak mam jakieś wczorasze EI?

**Comment by krystian3w** [comment]
A nie wskakuje ci po jakimś 3 odświeżeniu może:

```
||cdn.gallery/pic/assets/uploads/files/7287-1562761150-tlokasztelan.jpg
```

**Comment by krystian3w** [comment]
Też niby Nano Adblocker i AdGuard będą się ksztusić z CSS-em bo liniowy w atrybucie `style="..."`` z `!important`.

**Comment by hawkeye116477** [comment]
@krystian3w Zaktualizowałem komentarz :stuck_out_tongue:
