### ISSUE TITLE
zambrow.org

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14064]
https://zambrow.org/

brak slidera na głównej z artykułami - same reklamy tam? no nie sądzę 😉 

---

Kubica pod wyciętym sliderem na głównej:

![obraz](https://user-images.githubusercontent.com/35370833/61150865-c4a29980-a4e4-11e9-9452-78a98d0d645b.png) |
--- |

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/61174190-4a821b80-a59d-11e9-97a3-f55c6b0ea61b.png)


to na pewno reklama?

**Comment by xxcriticxx** [comment]
@krystian3w na screenszacie jest Orlen

**Comment by krystian3w** [comment]
Mi chodzi o ten slider, czy to jeszcze jest reklama, bo zapomniałem dodać co tam mają.

**Comment by xxcriticxx** [comment]
ja slider mam i dziala ale znika mi zdjecie co masz na screenszocie

**Comment by hawkeye116477** [comment]
Nie mam slidera tak jak @krystian3w. 
Nieładnie @MajkiIT.

**Comment by MajkiIT** [comment]
@hawkeye116477 ładnie ładnie :D Dzięki
