### ISSUE TITLE
faktykaliskie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14069]
![Screenshot_20190713_003156](https://user-images.githubusercontent.com/36385327/61161794-d34d7880-a505-11e9-963c-8aced1a25968.png)

**Comment by xxcriticxx** [comment]
@xMaap need more info

**Comment by krystian3w** [comment]
reklama w nagłówku:

```
###banner-top-of-menu
```

jednak luka zostaje, chyba CSS dla uBO / AdGuard...
