### ISSUE TITLE
pl160.microsoft.com-odebrac-nagrode.pw

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#1407]
Proszę zablokować tę stronę: http://pl160.microsoft.com-odebrac-nagrode.pw/d1-v739-pl-l/index.html?isp=UPC%20Polska%20Sp.%20z%20o.o.&model=Desktop&voluumdata=BASE64dmlkLi4wMDAwMDAwNS1hY2NjLTQ5YWMtODAwMC0wMDAwMDAwMDAwMDBfX3ZwaWQuLmEyODM4MDAwLTlkNmEtMTFlNi04NjJjLTU3NWIyOGVjMTkyNF9fY2FpZC4uOGIxN2VjYzItZGFmNC00MWI4LThlM2UtYzdiZTZiMjJmZGZhX19ydC4uREpfX2xpZC4uN2M4NTc2YTMtNjJjOC00MTQxLTkxNTktZTFkNzMyYTU1NWYwX19vaWQxLi5kMTZlOTZkMS0wNGQwLTRkMDctODg5MS00MTI0NDk4ZDNiOTNfX3ZhcjEuLjE0ODYwNTZfX3ZhcjMuLjM1X192YXI0Li5QTF9fdmFyNS4uMzQ3MF9fdmFyNi4uMTk1MjU0MzMyOTJfX3JkLi5sYnlwcHB3ZnZhZ3FcLlxjb21fX2FpZC4uX19hYi4uX19zaWQuLg&websiteid=1486056&keyword=&categoryid=35&country=PL&IMPRESSIONID=19525433292&bid=0.00116

**Comment by xxcriticxx** [comment]
@adreporter masz litry KAD?

**Comment by adreporter** [comment]
litry KAD?

**Comment by adreporter** [comment]
@xxcriticxx filtry KAD? jakieś nowe?

**Comment by azet12** [comment]
witam, filtry istnieją od kilku miesięcy, zalecam zasubskrybować: https://azet12.github.io/KAD/

**Comment by xxcriticxx** [comment]
+1 ;)

**Comment by adreporter** [comment]
@xxcriticxx @azet12 aha chodzi o filtry ktore juz sie znajduja na liscie POL: polskie filtry do Adblocka i uBlocka‎: "!-----------------------SMS Fake Pages-------------------------------! !included https://raw.githubusercontent.com/azet12/KAD/master/KAD.txt"

**Comment by adreporter** [comment]
@xxcriticxx aha o to chodzi, btw te filtry KAD sa dolaczone do listy "polskie filtry do Adblocka i uBlocka"

**Comment by adreporter** [comment]
@azet12 Dziękuję.
