### ISSUE TITLE
lot.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14075]
`https://www.lot.com/pl/pl/miles-and-more`
Social
![Screenshot_20190714_064643](https://user-images.githubusercontent.com/36385327/61179473-5acce180-a603-11e9-8ae4-fee0e3010a24.png)

`https://www.lot.com/pl/pl/metody-platnosci`
![Screenshot_20190714_064738](https://user-images.githubusercontent.com/36385327/61179477-7afca080-a603-11e9-8699-95f18d12e05e.png)

**Comment by krystian3w** [comment]
Metody płatności psuje `Fanboy Cookie List`?

**Comment by krystian3w** [comment]
`lot.com#@#.cookie-promo`

ale nie wiem czy naprawi `https://www.lot.com/pl/pl/metody-platnosci`

**Comment by xMaap** [comment]
Naprawia

**Comment by krystian3w** [comment]
To potem przetestuje to na ABP / AdGuard.

Nano w Firefox ignoruje już chyba filtry dla body / html.

**Comment by xMaap** [comment]
Z tego co widzę to na AdGuard różnie jest biała strona.
