### ISSUE TITLE
se.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#14080]
https://www.se.pl/
FIX - ADGUARD - box reklamy w kilku miejscach 
```
se.pl##.zpr_inside_1_wide, .active
```

![scr-1563124686-001](https://user-images.githubusercontent.com/9846948/61186997-55f04800-a66c-11e9-98a1-6ea0859afc41.png)
![scr-1563124704-001](https://user-images.githubusercontent.com/9846948/61186998-5688de80-a66c-11e9-8308-03ab6ae8fa5b.png)

@MajkiIT  @krystian3w

**Comment by krystian3w** [comment]
```
##div[id^="inside"][class*="zpr_inside"]
```

I to jest nawet z uBlock Origin + Firefox 68.

**Comment by FadeMind** [comment]
@krystian3w działa. Adguard nie ma tej reguły (i wy w swoich też nie) 😉 Dzięki

**Comment by krystian3w** [comment]
Ogólnie to wygląda podobnie do tych boxów co były kiedyś na np. `poradnikzdrowie`.

**Comment by FadeMind** [comment]
@krystian3w 
na superbiz.se.pl jest inaczej:
```
superbiz.se.pl##.zpr_bottom_1
```
```
superbiz.se.pl##.zpr_rect
```

![scr-1563129088-001](https://user-images.githubusercontent.com/9846948/61187823-d6b44180-a676-11e9-9a9e-40cfb7e4dc0b.png)

![scr-1563129367-001](https://user-images.githubusercontent.com/9846948/61187840-18dd8300-a677-11e9-8231-5751eb9c947f.png)
![scr-1563129396-001](https://user-images.githubusercontent.com/9846948/61187841-18dd8300-a677-11e9-9c24-23f6a79b96c1.png)

**Comment by krystian3w** [comment]
`##div[class^="zpr_box"]`
