### ISSUE TITLE
maserati.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14085]
Social
![Screenshot_20190715_065410](https://user-images.githubusercontent.com/36385327/61196261-903e0180-a6cd-11e9-9da0-f661a38db3c3.png)

**Comment by krystian3w** [comment]
Ja mam popup reklamę auta.

uBO/AdGuard solucja:

```
maserati.pl###sgcboxWrapper, #sgcboxOverlay
maserati.pl##.sgpb-disable-page-scrolling:style(overflow-y: auto !important;)
```
