### ISSUE TITLE
bmw-motorrad.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14086]
`https://www.bmw-motorrad.pl/pl/home.html#/filter-wszystkie`

Nie działa scrollowanie strony.

**Comment by krystian3w** [comment]
Agresywne cookies @hawkeye116477  da się wykrywać że ono ma zablokowany scroll?

```
<section> blocked by:
.cookielayer:not(body):not(html)
```

`:not(section)`...?

**Comment by hawkeye116477** [comment]
Nie wiem, zależy co tam inne strony mają, spróbować zawsze można.

**Comment by krystian3w** [comment]
Remove on ready mogę dać, na Firefox komunikat że Nano przeciąża przeglądarkę.

`bmw-motorrad.pl##+js(nano-remove-elements-onready.js, .cookielayer)`

**Comment by hawkeye116477** [comment]
@krystian3w Ale od czego przeciąża? Bez zagadek mi tu...

**Comment by krystian3w** [comment]
Jakby mu za ciężko na tym bmw usunąć cookielayer i co takiego daje reset "wysokości" na initial?

**Comment by hawkeye116477** [comment]
@krystian3w A pokaż zrzut z komunikatem. U mnie niby nie ma, ale może dlatego, że mam bardzo wydajny CPU :smile:

**Comment by krystian3w** [comment]
HTML nie robi problemu, jak podmieniłem go na skrypt to przewijanie po odświeżeniu wróciło i niestety:


![obraz](https://user-images.githubusercontent.com/35370833/61235296-7cc68100-a735-11e9-9786-96cb058889e6.png)


tyle że u mnie było polecenie dezaktywacji Nano Adblocker jako bliżej określonej przyczyny.

Może otwarcie w tle z 8 kart też dało swoje.
