### ISSUE TITLE
hotshare.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1408]
reklama

**Comment by F4z** [comment]
@MajkiIT reguła którą dodałeś - `hotshare.pl##center` - blokuje obrazek z captchy, tutaj - `http://www.hotshare.pl/sendmessage.php`

![image](https://cloud.githubusercontent.com/assets/11742596/19829722/942964f0-9de9-11e6-8658-3c220ca9b2d9.png)

Może lepiej będzie tak - `hotshare.pl##div > center` albo jeszcze coś innego.

**Comment by MajkiIT** [comment]
@F4z poprawione. Dzięki
