### ISSUE TITLE
poradnikzdrowie.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#14098]
Zrzuty ekranu: https://imgur.com/a/33xTSVm
Adguard. 

Sample
![s](https://i.imgur.com/VpvIZQs.png)

@krystian3w  tutaj też są ZPR BOXY 😉

**Comment by krystian3w** [comment]
O czyli przeprogramowali.

@MajkiIT zostawiam na razie - bo na poradniku może być wykrywacz, że ktoś to "schował".

**Comment by krystian3w** [comment]
Przerobione że użyty został ich CSS do budowy napisów "Reklama na czarnym tle".

```
##.zpr_m_inside_top.active, div[class*="zpr_m_inside"].active, div[class*="zpr_inside"].active, div[class*="zpr_box"].active > div[class*="zpr_"]
```

Wcześniejsze pod samo `SE.pl` wycinało za bardzo stopkę na `poradniku`.
