### ISSUE TITLE
onet.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14092]
" Podziel się tym artykułem:  " w tabeli " Masz ciekawy temat? Napisz do nas list! "

https://sport.onet.pl/pilka-nozna/liga-europy/szybkie-wyroki-po-bojce-pseudokibicow-w-bratyslawie/jjktpqw

**Comment by krystian3w** [comment]
Onet - generichide, nie ma co tam łączyć - czyli nowe lub nikt tak nisko nie czytał.

**Comment by xxcriticxx** [comment]
@krystian3w social or adblock?

**Comment by krystian3w** [comment]
Social - tak tylko analizuję, bo skompresowałem w socialu jakieś 150 linii i niby po czasie wyszło że za dużo w jeden dzień.

Ale raczej to nie od tego.
