### ISSUE TITLE
grupapietrzak.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14091]
`https://grupapietrzak.pl/`
Cookies + social + ukrywa treść
![Screenshot_20190715_133100](https://user-images.githubusercontent.com/36385327/61213464-69032680-a705-11e9-864a-1fc5f34d9f4b.png)

`https://maseratipietrzak.pl/`
Cookies + ukrywa treść
![Screenshot_20190715_133424](https://user-images.githubusercontent.com/36385327/61213500-81734100-a705-11e9-92a0-6af68c03895c.png)

```
http://renaultjaworzno.pl/
http://renaultrybnik.pl/
http://renaultswietochlowice.pl/
http://daciajaworzno.pl/
http://daciaswietochlowice.pl/
http://autodealer.pl/
```
Cookies + social + ukrywa treść
![Screenshot_20190715_133819](https://user-images.githubusercontent.com/36385327/61213698-14ac7680-a706-11e9-96b4-caca398cc5fe.png)

`http://daciakatowice.pl/`
Ukrywa treść
![Screenshot_20190715_133940](https://user-images.githubusercontent.com/36385327/61213753-3b6aad00-a706-11e9-810e-18ddc380d531.png)

`http://renaultkatowice.pl/`
Social + ukrywa treść
![Screenshot_20190715_134057](https://user-images.githubusercontent.com/36385327/61213797-62c17a00-a706-11e9-8db9-1d406ef10341.png)

`https://katowice.alpinecars.com/`
Cookies
![Screenshot_20190715_134116](https://user-images.githubusercontent.com/36385327/61213826-7240c300-a706-11e9-92c2-2b77272a7db1.png)

`https://ferrarikatowice.pl/`
Cookies + Social + ukrywa treść
![Screenshot_20190715_134141](https://user-images.githubusercontent.com/36385327/61213854-8ab0dd80-a706-11e9-9f76-f8246f2eea3a.png)

`https://ferrariwarszawa.com/`
Cookies + social
![Screenshot_20190715_134223](https://user-images.githubusercontent.com/36385327/61213872-9ef4da80-a706-11e9-8536-1e2561a67507.png)

**Comment by krystian3w** [comment]
Jak bez filtrów Cookie Fanboy?

**Comment by hawkeye116477** [comment]
To raczej wina EasyList.
`@@||img.dladealera.pl/ads/*$image,domain=grupapietrzak.pl`

**Comment by krystian3w** [comment]
@hawkeye116477 jak chcesz możesz przerobić generyk na wypisanie 8 polskich domen.

Podobnie z przyciskiem `.fbFIXED` jak podejrzewasz że większość używa kodu do załadowania czegoś innego co nie jest socialem.

**Comment by hawkeye116477** [comment]
Nie wiem jak `.fbFIXED`, ale to `pl##.fixedInfo > .fixedInfoContent` pewnie raczej nie przejdzie, nic to nie mówi, może być cokolwiek...

**Comment by krystian3w** [comment]
@MajkiIT  brzydkie filtry reklamowe:

```
ferrarikatowice.pl#@#[class$="-ads"]
```
