### ISSUE TITLE
ipla.tv

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#14094]
https://www.ipla.tv/wideo/rozrywka/Najlepsze-skecze/5016593/Ewa-Blachnio-O-facetach/68adf51c1d3c4870827fdbb7ab99c62b

Usunięcie ikon SOCIAL

![s](https://i.imgur.com/jho1LDX.png)

```
ipla.tv##.social-icons-list
```
Ewentualnie odnośnika głównego do podmenu

![d](https://i.imgur.com/veM48ef.png)

```
ipla.tv##.vod-actions__share, .action
```

**Comment by krystian3w** [comment]
`##.social-icons-list, .social-icons-list + .block-separator`

tak by nie psuć tym co pasek adresu się chowa xd.
