### ISSUE TITLE
tvntl.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14097]
wchodząc na strone http://tvntl.pl/nasze-programy/magazyn-sportowy
przekierowuje mnie na jakąś inną i jest info że jetem roobotem

**Comment by xxcriticxx** [comment]
ja mam to samo 

![Capture](https://user-images.githubusercontent.com/15007183/61220003-68f22f00-a6e3-11e9-97d2-bf8092d152ad.PNG)

**Comment by xxcriticxx** [comment]
captcha to element irytujacy czy social?

**Comment by krystian3w** [comment]
Invalid, raczej do blokady jako KAD przekęrty.

---

@blocker999 wrzuć jeszcze raz tutaj żeby nie uciekło: https://github.com/PolishFiltersTeam/KAD/issues

**Comment by blocker999** [comment]
givemegreenbottle.icu #927
