### ISSUE TITLE
biznesinfo.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#14101]
Rodo na 3/4 strony xD

https://www.biznesinfo.pl/grzegorz-schetyna-ultimatum-lider-po-ma-czas-do-srody

![s](https://i.imgur.com/eTTqNEw.png)

@krystian3w

**Comment by krystian3w** [comment]
`###loadCookiePolicy` - @kiboke

A tak to chyba nikt takiego ID nie widział....:

https://publicwww.com/?q=id%3D%22loadCookiePolicy%22

**Comment by hawkeye116477** [comment]
@krystian3w Ale to do nas, a nie do niego :smile:

**Comment by krystian3w** [comment]
Ale on też ma listę i niech sobie doda.

**Comment by krystian3w** [comment]
No chyba że chytrze skryptem to już zamyka - tego nie testuje w ogóle.

Ale skoro 2 polskie strony na krzyż to mają i jedna nie do końca znana to raczej wątpię w tak unikatowy skrypt i blokadę strony, bo nie było akceptacji GDPR/Cookies.

**Comment by hawkeye116477** [comment]
Ale my nie wymagamy jego listy, do niego zagraniczne tylko, on zresztą też nas nie woła do blokowania polskich :smile:

**Comment by krystian3w** [comment]
On zrobił dodatek międzynarodowy to nie może się zamykać że ktoś dotnie sobie PL listeczką czy też PCZ.

To nie fanboy i stwierdzenie, nie wartościowo jest zablokować te 6 linków social ale "doblokuję" reklamę jaką już dociął skryptem projetkt Anty-CV i smed79 z Khrin sieciowo blokują ramki.

**Comment by hawkeye116477** [comment]
No ok, ale skoro my to dodajemy i dotyczy polskich stron, to jakoś nie widzę sensu do innych zgłaszać.

**Comment by krystian3w** [comment]
Taki podział potem robi potem, że filtry na reklamy wewnętrzne naprawiają jakieś ruchome nawigacje, bo projekt UltraWebAnnoyance stwierdził że polskie lepiej tam ustatyczniać.

**Comment by hawkeye116477** [comment]
@krystian3w Nie wiem o czym ty teraz, ale UltraWebAnnoyance to raczej normalne, że ustatycznia, taki był cel tej listy.

**Comment by krystian3w** [comment]
Ustatycznia ale międzynarodowe strony, Mati ma sobie w liście filtrów wewnętrznych dla polskich robić.

Może efekt że się pochwalił że ustatycznia...

**Comment by hawkeye116477** [comment]
@krystian3w Nadal nie wiem w czym problem. Ale konkurencji nie wspieramy raczej, bo trochę mija się z sensem wtedy ta lista. To tak jakbyś ty założył własną piekarnię, miał swoją recepturę i przekazał ją konkurencji...

**Comment by hawkeye116477** [comment]
@krystian3w Nadal nie wiem w czym problem. Nie dublują się nawzajem, to raczej chyba dobrze.

Może właśnie my tez powinniśmy przestać dublować, po co sobie pracy dodatkowej robić,  wymaganie IDCAC pewnie nie jest to taki dobry pomysł, ale możemy przecież chyba zaincludować IDCAC :smile:

**Comment by kiboke** [comment]
> `###loadCookiePolicy` - @kiboke
> 
> A tak to chyba nikt takiego ID nie widział....:
> 
> https://publicwww.com/?q=id%3D%22loadCookiePolicy%22

Thank you guys. If possible please speak english in the future, google translate doesn't do a very good job when it translates your conversation :-)
