### ISSUE TITLE
pi-hole webpage broken

### ISSUE THREAD

**Issue by Th3M3** [MajkiIT/polish-ads-filter#14105]
### Screenshot

<img width="960" alt="Unbenannt" src="https://user-images.githubusercontent.com/28313514/61269015-9b606280-a79d-11e9-81c8-d1b3702802e1.PNG">

Excerpt from the blocking protocol::
<img width="910" alt="Unbenannt2" src="https://user-images.githubusercontent.com/28313514/61269024-a0251680-a79d-11e9-8ead-0ded564230b8.PNG">

### What do you need to do to appear element, an ad or an error?
The blue and orange tiles on pi-hole page gets blocked.

The mysterious thing is that if I disable Adblock for pi.hole page, it enables itself after some time.

### My configuration
**Web browser:** Opera on Windows 10
**Extensions and scripts:** Adguard Plugin

**Filter lists:**
1. EasyList
2. Official Polish Filters For AdBlock, uBlock Origin and AdGuard
3. 
4. 

**Other important informations that may be relevant (optional):**

**Comment by krystian3w** [comment]
@xxcriticxx ten błąd będzie pewnie też z ABP / uBlock Origin.

---

`pi.hole#@##[id^="ads_"]`

or

`@@||pi.hole^$generichide`

**Comment by xxcriticxx** [comment]
@Th3M3 why not add your pi up to your whitelist? That ip should always be static.

**Comment by Th3M3** [comment]
Adding `pi.hole#@#[id^="ads_"]` to the user's filter works actually.

But if I disable AdGuard on pi.hole site (which is the same as adding it to the Whitelist), it gets enabled blocking after some time again for some reason.

And annoyingly I have to whitlist it on all devices on my network.

Is there not an easy way to adapt the filter list to prevent overblocking?

**Comment by krystian3w** [comment]
`##[id^="ads_"] ` maybe now more agresive.

> Is there not an easy way to adapt the filter list to prevent overblocking?

No body have in mind offline copy all Internet.

This defective filter can be easily disabled on the `pi.hole` page - enough add to list domain with prefix `~`.

**Comment by xxcriticxx** [comment]
@Th3M3 try the latest list and let's see what happens

**Comment by krystian3w** [comment]
fix no arrived to AdGuard server: https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_216_PolskiFiltr

(You usually have to wait up to 3 hours)

So now only visible for ABP/uBlock Origin.

**Comment by Th3M3** [comment]
Works fine now. Thanks a lot, great work 😘
