### ISSUE TITLE
Linux 

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#14104]
@xxcriticxx Daj temu offtop

Słuchajcie siedze sobie na Kubuntu i mam pare pytań 

1 Kopsnij ktoś liste skrotow klawiszowych systemu 
2 Jak na stałe włączyć num pada (Wpienia mnie ciagle klikanie numlock jak chce coś wpisać cyferkami 
3 jest tu cos na wzor Treya w windzie? chodzi mi zeby chować aplikacje ktore zadziej uzywam za ta taka strzalke jak w windzie

**Comment by xMaap** [comment]
1. Ustawienia > Ustawienia Systemowe > Skróty
2. Ustawienia > Ustawienia Systemowe > NumLock po uruchomieniu Plazmy > Zastosuj

**Comment by gzenio22** [comment]
@xMaap w Kubuntu takich prostych ustawien nie mam Xd

**Comment by hawkeye116477** [comment]
@gzenio22 3. No przecież jest tacka systemowa, taka strzałka, klikasz ppm na to i tam masz elementy i możesz ukrywać, pokazywać.

**Comment by xMaap** [comment]
@gzenio22 w KDE musisz trochę się naszukać, bo ma tyle tego. Zawsze możesz:
1. Alt + F2 i wyszukać
2. Wejść w Menu i wyszukać w wyszukiwarce
3. Wejść w Ustawienia i wyszukać w wyszukiwarce

@hawkeye116477 O ten Tray chyba mu chodziło aby dodać własne aplikacje.

**Comment by hawkeye116477** [comment]
To niech zainstaluje KDocker.

**Comment by gzenio22** [comment]
Jestescie mega jutro potestuje dzis juz uciekam spac trzymajcie sie

**Comment by gzenio22** [comment]
@hawkeye116477 

Wiesz jak sobie z tym poradzić?
![67406024_2415661718649743_808787847015301120_n](https://user-images.githubusercontent.com/21177361/61718740-db0de800-ad63-11e9-9a63-1503510c6f50.png)

**Comment by hawkeye116477** [comment]
@gzenio22 A po co ci W10 na VMWare? Na Linuksie masz Wine, PlayOnLinux i Steam Play jakby co.
Tak czy siak nie instalowałem W10 na VMWare, więc nie wiem, ale dlaczego W10 nazwałeś siódemką?
Zainstalowałeś 7, potem upgrade do 10? Jak tak, to może to coś pomoże => `https://communities.vmware.com/thread/516581`, nie bój się wujka Google :stuc
