### ISSUE TITLE
remekdabrowski.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#14109]
http://remekdabrowski.pl/
Overlay
![s](https://i.imgur.com/mirWxTv.png)

![f](https://i.imgur.com/lnXnyPk.png)
@krystian3w

**Comment by krystian3w** [comment]
To będzie naprawione w polskim EI - newsletter.

A treść wyciął wadliwy generyk z `fanboy cookie list` (cookiemonster).

https://github.com/ryanbr/fanboy-adblock/issues/976

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersRegistry/commit/8d0ca4133db6376f3de889383ed05c31e01709a6#diff-fbea08e09a9cc0672ff4a870595479d1R1206
