### ISSUE TITLE
oknonawagrowiec.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#14111]
https://oknonawagrowiec.pl/

![s](https://i.imgur.com/UvUP2IF.png)

**Comment by FadeMind** [comment]
@MajkiIT  @krystian3w 
```
oknonawagrowiec.pl##.penci-promo-item, .penci-banner-has-text
```
![scr-1566802348-001](https://user-images.githubusercontent.com/9846948/63671065-d911cb80-c7de-11e9-8334-083a82c340f0.png)

```
oknonawagrowiec.pl##.penci-social-counter
```
![scr-1566802407-001](https://user-images.githubusercontent.com/9846948/63671112-fb0b4e00-c7de-11e9-8b88-b965cb9fe138.png)

**Comment by krystian3w** [comment]
Social trzeba podzielić na dwa jak funkcjonalny button RSS (np. nie robi za blog / forum).

Vs_space to raczej fail filtr.

**Comment by FadeMind** [comment]
@krystian3w ktoś w ogóle korzysta z RSS??? 😱

**Comment by krystian3w** [comment]
1 na 10 000  niby tak ("`_Puma_`").

**Comment by krystian3w** [comment]
Social niby wycieka z bugów "braku" userCSS chyba, uBO go nie ma wcale - czyli naprawa jako bug Fanboya, bo wyciął za dużo w naszym mniemaniu, potem podziałki i filtr dla AG jak po rodzieleniu będzie dalej problem z ukryciem w AG.

---

Podobnie może z tą reklamą?

**Comment by krystian3w** [comment]
Social jak nikt nie przyśpieszy filtrów RSS zniknie w poniedziałek, tam dociąłem cały blok.

Reklama jest też z uBO więc będzie w polskich filtrach z przecinka.

**Comment by hawkeye116477** [comment]
@FadeMind Była kiedyś ankieta => https://www.strawpoll.me/15296599/r i większość była przeciwko ukrywaniu RSS.

**Comment by krystian3w** [comment]
trolle podbiły ankietę, ma 40 procent lub nie mam "zadnia" zaważyło i jak z głosowaniem na prezydenta 50.0000000X%?

**Comment by FadeMind** [comment]
@krystian3w @MajkiIT odgrzewam wątek po latach
![20210419-1618855408-001](https://user-images.githubusercontent.com/9846948/115282336-67705900-a14a-11eb-9bce-26200f8076d7.png)

**Comment by krystian3w** [comment]
Może strona żyje na kredytach z BNP, wtedy to może jest reklama wewnętrzna / self-promo.

Niby jak chcesz by zniknęła to lepiej wklejać jako nowe zgłoszenie na liście otwartych, zamknięte pewnie utonie na e-mailach poczty Majkiego.
