### ISSUE TITLE
vacansoleil.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14115]

**Comment by krystian3w** [comment]
@kiboke: 

`###__tealiumGDPRecModal:not(body):not(html)`

?

other Polish:

```
3mpolska.pl,logitechg.com,bosch-professional.com,logitech.com,command.pl
```

https://github.com/MajkiIT/polish-ads-filter/blob/fec7652580e41e93c88b9618238fddafa31c6475/cookies_filters/adblock_cookies.txt#L30

**Comment by kiboke** [comment]
#__tealiumGDPRecModal is already a general filter in IDCAC.

**Comment by krystian3w** [comment]
but I see only:

`###__tealiumGDPRcpPrefs:not(body):not(html)`

and no works on PL sites?

**Comment by kiboke** [comment]
You are right, it is excluded because it breaks some domains. I will sync the rule with https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt for filter list version.
