### ISSUE TITLE
travelplanet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14117]

**Comment by krystian3w** [comment]
Ja nie mam, link poproszę.

https://github.com/MajkiIT/polish-ads-filter/blob/fec7652580e41e93c88b9618238fddafa31c6475/cookies_filters/adblock_cookies.txt#L1800

**Comment by xxcriticxx** [comment]
ja tez dzisiaj nie mam jutro sprawdze
