### ISSUE TITLE
wylecz.to

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#14127]
Reklamy w boxach w różnych miejscach.
https://wylecz.to/
https://wylecz.to/twarz/jak-przygotowac-skore-do-opalania/

Zrzuty ekranu https://imgur.com/a/JLQV6gi

@krystian3w 

SETUP

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64 (lastest)
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.1.2817 RELEASE** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Block WebRTC/Location API/Java/Flash
|Hide your search queries
|Remove X-Client-Data header from HTTP requests
|Send Do-Not-Track header
|Strip tracking parameters from URLs
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuckadblock
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| Fanboy's Annoyances
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/13071#issuecomment-489447487

> taki regex do przetestowania na same reklamy:
> 
> Wersja najdłuższa / najbezpieczniejsza:
> ```
> /^htt(p|ps):\/\/wylecz\.to\/media\/filer_public_thumbnails\/filer_public\/[a-z0-9]{2}\/[a-z0-9]{2}\/[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}\/[a-zA-Z0-9]{8}\.(jpg|png|gif)$/$~third-party,image,domain=wylecz.to
> ```
> 
> Wersja średnio długa / średnio bezpieczna:
> ```
> /^htt(p|ps):\/\/wylecz\.to\/media\/filer_public_thumbnails\/filer_public\/[a-z0-9/-]+\/[a-zA-Z0-9]{8}\.(jpg|png|gif)$/$~third-party,image,domain=wylecz.to
> ```
> 
> Wersja krótka / mniej bezpieczna:
> ```
> /\/[a-zA-Z0-9]{8}\.(jpg|png|gif)$/$~third-party,image,domain=wylecz.to
> ```

może dalej działają...

**Comment by krystian3w** [comment]
RODO w dodatku PZC lub do AdamaWr by sobie z nimi wojował.

**Comment by krystian3w** [comment]
w uBO dalej działa:

```
wylecz.to##a[href^="/zze_click/"]:xpath(../..[div][@style])
wylecz.to##iframe[src^="/zze_click/"]:xpath(../..[div][@style])
```

Na lepszym kompie to jest jakieś 500 ms i reklama znika, co do zapisu `[div][@style]` nie mam pewności.

Najwyżej można zalecić AdGuard Base dla tej strony jako wymagany - AdGuard Team dodał filtry z `:has(...)`.
