### ISSUE TITLE
interia.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14128]
@krystian3w Coś blokuje scroll na stronie po wylogowaniu z poczty, niewiem gdzie to zamieścić wię daje to tu a może całkowicie to zablokować ?

https://www.interia.pl/wyloguj.html#utm_source=konto&utm_medium=pasek_portalowy&utm_campaign=Wylogowania_z_poczty&iwa_source=layer_logout_mail

**Comment by krystian3w** [comment]
Tutaj, bo po wylogowaniu jest reklama.

**Comment by krystian3w** [comment]
Sprawdź takie coś na przewijanie:

```
www.interia.pl##+js(remove-attr.js, scrolling, iframe#sg-iframe[scrolling="no"])
```

**Comment by krystian3w** [comment]
Chyba że taki badziewny CSS:

```
www.interia.pl##iframe#sg-iframe[scrolling="no"]:style(height: 8050px;)
```

Jednak lipa jak dłuższe lub za dużo ramek się rozrośnie...

**Comment by hawkeye116477** [comment]
Ja tu nie widzę :cookie: .

**Comment by krystian3w** [comment]
Ja też nie, to błąd filtrów reklamowych (wycięły reklamę, "generykiem") mam zrobić PR do suplementu uBO?

Byłbym za usuwaniem atrybutu niż ręcznym rozszerzaniem ramki.

**Comment by hawkeye116477** [comment]
@krystian3w To przy okazji możesz tym się też zająć => `https://github.com/MajkiIT/polish-ads-filter/issues/14172` :smile:
