### ISSUE TITLE
kopaczka.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14141]
`http://kopaczka.pl/viewtopic.php?f=14&t=38593
`
Reklamy
![Screenshot_20190718_202837](https://user-images.githubusercontent.com/36385327/61482428-e09db380-a99a-11e9-9d4f-0e4bd0f3e17b.png)

**Comment by krystian3w** [comment]
`||kopaczka.pl/ban/*$image,subdocument`
