### ISSUE TITLE
mubi.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14149]
`https://mubi.pl/`
Social
![Screenshot_20190720_115516](https://user-images.githubusercontent.com/36385327/61577282-76455a00-aae5-11e9-9aa8-16b3016e8e04.png)

`https://kalkulator-oc-ac.mubi.pl/
`Cookies
![Screenshot_20190720_115601](https://user-images.githubusercontent.com/36385327/61577288-8fe6a180-aae5-11e9-82a0-c5c84ef6ffad.png)

**Comment by krystian3w** [comment]
cookies makabryczne:

```
##div#root > div[class] > header  ~ div[class]:not([id]):contains(plików cookies)
```

**Comment by krystian3w** [comment]
Jest więcej subdomen z tym mubi.pl?

**Comment by xMaap** [comment]
Nie ma.
