### ISSUE TITLE
justwatch.com/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14159]
USUŃ TĘ REKLAMĘ

![Capture](https://user-images.githubusercontent.com/15007183/61579176-dcbf7d80-aacf-11e9-9884-33af3595b8b5.PNG)

**Comment by krystian3w** [comment]
Mnie znika po sekundzie.

**Comment by krystian3w** [comment]
Sprawdź czy masz filtr:

`##.ad-unit` w EasyList, jak nie to wymuś aktualizację.

**Comment by xxcriticxx** [comment]
mam to w easylist ale dla mnie nie znika  

```
##.ad-unit
##.ad-unit-300
##.ad-unit-300-wrapper
##.ad-unit-970x90
##.ad-unit-anchor
##.ad-unit-container
##.ad-unit-editorial-well
##.ad-unit-horisontal
##.ad-unit-inline-center
##.ad-unit-label
##.ad-unit-medium-retangle
##.ad-unit-mpu
##.ad-unit-panel
##.ad-unit-site-takeover
##.ad-unit-text
##.ad-unit-top
##.ad-unit-wrapper
```

**Comment by krystian3w** [comment]
Nie masz w loggerze zielonego generichide:

> ![obraz](https://user-images.githubusercontent.com/35370833/61579855-e4e8de80-ab0a-11e9-8bb5-27b074288fc1.png) |
> --- |


 lub zaznaczonych okularów:

> ![obraz](https://user-images.githubusercontent.com/35370833/61579837-b4a14000-ab0a-11e9-8c69-773010f8bd4b.png) |
> --- |

 bo coś ci nie działało?

**Comment by xxcriticxx** [comment]
no clue co bylo teraz dziala jak powinno
