### ISSUE TITLE
proama.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14152]
`https://saleswww.proama.pl/frontend/www?execution=e2s1`
RODO
![Screenshot_20190720_122852](https://user-images.githubusercontent.com/36385327/61577613-3339b580-aaea-11e9-94ef-5c442522bf57.png)

**Comment by krystian3w** [comment]
Ja nie mam..., Fanboy generykiem odblokował?

**Comment by krystian3w** [comment]
A nie złe linki dajesz:

```
https://saleswww.proama.pl/frontend/www/nnw-dziecka
https://saleswww.proama.pl/frontend/www/podroz
```
