### ISSUE TITLE
medianarodowe.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#14158]
`https://medianarodowe.com/category/wideo/`

pusta sekcja reklama

**Comment by krystian3w** [comment]
Nie można wyciąć na sztywno z boksami, reklamami...

Może uAssets, AdGuard team wytnie sam tekst?

> ![obraz](https://user-images.githubusercontent.com/35370833/61579121-515ee000-ab01-11e9-8098-cb9b339ec2b6.png) |
> --- |

**Comment by krystian3w** [comment]
@MajkiIT  kolorować to białym kwadratem z użyciem CSS3 jako filtr "`:before:style(...)`"?
