### ISSUE TITLE
please fix 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14163]
shortcut z main page repo do discord nie dziala

![Capture](https://user-images.githubusercontent.com/15007183/61585026-744cbc80-ab20-11e9-81d5-0a5f032acde2.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Wygląda na to, że usunęli nas z listy serwerow na discord.me i trochę pozmieniali to i owo na stronie, ale już naprawione, dodałem ponownie.

**Comment by xxcriticxx** [comment]
teraz gitara love you long time master @hawkeye116477
