### ISSUE TITLE
torsluzewiec.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14161]
![Screenshot_20190720_155121](https://user-images.githubusercontent.com/36385327/61579530-799d0d80-ab06-11e9-9434-c2bb92e491d3.png)

**Comment by krystian3w** [comment]
@kiboke

```
torsluzewiec.pl###gdpr-info-container
```

**Comment by kiboke** [comment]
I'll create a general filter in IDCAC for now.
