### ISSUE TITLE
totalizator.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14162]
Biała strona
![Screenshot_20190720_155715](https://user-images.githubusercontent.com/36385327/61579582-4ad36700-ab07-11e9-8581-b20478931158.png)

**Comment by krystian3w** [comment]
Fanboy Cookie pewnie, tylko czemu w chromium nie dało się zaimplementować zakazu ukrywania body / html?

**Comment by hawkeye116477** [comment]
Niemożliwe i sprawdziłem nawet tego Fanboya i u mnie nie ma takiego problemu.

**Comment by krystian3w** [comment]
Możliwe, sprawdź z pomocą AdGuard / AdBlock / Adblock Plus.

Albo zacytuj klasy dla "body".
```
<body class=" cookie-info ">
```

Jest to w chormowatych nie działa funkcja anty `breakage` - nie pamiętam commita, kiedy to dodali.

**Comment by hawkeye116477** [comment]
Akurat korzystam z Vivaldiego i NA. A to @xMaap przeszedł na AG?

**Comment by krystian3w** [comment]
Na uBlock Origin (...) po ekscesach z wyciekającym socjalem WP?


Możliwe, że to się bugaje sporadycznie (funkcja ochrony widoczności tagów `body`, `html`) i nawet nie ma jak tego debugować.

**Comment by hawkeye116477** [comment]
Tak czy siak, zgłoszenie do zamknięcia, to sprawa dla Fanboya, by dodał `:not(body):not(html)`.

**Comment by krystian3w** [comment]
Pewnie doda w sierpniu jak go Khrin nie wyprzedzi?

**Comment by krystian3w** [comment]
Nawet pchać na PR się nie opłaca bo sprawdzają za wolno lub po chińsku naprawiają w bardziej dla nich czytelny sposób.

**Comment by hawkeye116477** [comment]
@xMaap Dobrze byłoby jakbyś sprawdzał przed zgłaszaniem która lista odpowiada za destrukcyjny efekt :smile:

**Comment by gwarser** [comment]
> tylko czemu w chromium nie dało się zaimplementować zakazu ukrywania body / html generykami...?
> 
> @gwarser - niby niemożliwe do osiągnięcia w chromium?

To chyba odwrotnie, bo w Firefox mam cały czas biało. Ta klasa jest dodawana skryptem i może dlatego raz działa a raz nie.

**Comment by krystian3w** [comment]
A jest zabezpieczenie czy u mnie już z 5 takie zgłoszenie już Firefox jakoś zablokował niechcący JS?

**Comment by krystian3w** [comment]
No bo niby już blokuje jakieś entery śledzące na Dobre programy w komentarzach... (sic!).

**Comment by gwarser** [comment]
Ja pierwsze słyszę o jakimś zabezpieczeniu i właściwie to szukałbym błędów, ale jak mówisz, że jakieś jest to pytam o co chodzi.

**Comment by krystian3w** [comment]
Na początku lipca jak z nudów przeglądałem coś w commitach uBO, to była w kodzie jakaś zmiana o elementach body / html w "funkcji" i myślałem, że ona nie pozwala na ukrywanie body / html prostym filtrem generycznym i tak sobie zacząłem tłumaczyć czemu u mnie Fanboy Cookie za chiny nie chce robić "blank page".

Niestety nie wiem jak daleko się cofnąłem, więc może to być nawet commit z początku maja.

**Comment by xMaap** [comment]
Używam uBlock Origin z włączonymi filtrami AdGuard, ale już wiem co jest winne. Winny jest filtr AdGuard Base List.

**Comment by krystian3w** [comment]
To oni niby co ukrywają divy wszystkie na stronie?

**Comment by xMaap** [comment]
Nie wiem jak, ale nie ma białego ekranu.
![Screenshot_20190721_003156](https://user-images.githubusercontent.com/36385327/61584838-2c915980-ab4f-11e9-835c-66ad9d854a38.png)

Mam zainstalowane Polska Ciasteczkowa Zgoda.

**Comment by krystian3w** [comment]
Jak udowodnisz, że rodo musi być akceptowane, to będziemy zamykać w PCZ/PCC.

**Comment by xMaap** [comment]
@krystian3w jest tylko jest tylko Akceptuj oraz Regulamin i nic innego więcej nie ma do zaznaczenia.

**Comment by xMaap** [comment]
A jak się kliknie w "X" i przejdzie na podstronę to ponownie wyświetla się RODO.

**Comment by hawkeye116477** [comment]
Dodajemy tam zgody tylko jak ukrywanie elementów coś psuje.

**Comment by krystian3w** [comment]
Bo "X" widać ma zamykać tymczasowo - będzie wycięte z PR, bo nikt nie udowodnił że strona popsuta po blokadzie pop-upa "rodo".

https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/5004cf2cbe0a56fb3a9ab53aa16171bc92752183

**Comment by gwarser** [comment]
@krystian3w tłumaczę o co chodzi: ta klasa, `.cookie-info`, jest dodawana do `<body>` dynamicznie przez skrypt. Dla filtrów globalnych uBO skanuje DOM w poszukiwaniu pasujących elementów i ukrywa dopiero jak znajdzie. Robi to raz, zaraz po załadowaniu, a potem obserwuje zmiany w DOM, dodawanie/usuwanie elementów, ale nie zmiany `class`/`id`. Kojarzysz `:watch-attr()`? To jest to samo, tylko że z generycznym filtrem. Czasami `.cookie-info` zdąży się dodać przed uBO i wtedy zadziała. U mnie działa przy starcie przeglądarki, przy przywróceniu sesji.

Gorhill podlinkował też przypadek z dodawaniem klasy przy przewijaniu https://github.com/gorhill/uBlock/issues/1885#issuecomment-238520014

Jako ciekawostka: `##.cookie-info:watch-attr()` działa stabilnie (zawsze ukrywa) jak masz włączony `allowGenericProceduralFilters`.

**Comment by krystian3w** [comment]
A czym uszkadza AdGuard Base w uBO?

Można by im zgłosić by pododawali więcej `!+ NOT_Platform(ext_ublock)`.

**Comment by gwarser** [comment]
> A czym uszkadza AdGuard Base w uBO?

Pojęcia nie mam, bo nie udało mi się jeszcze tego powtórzyć.

**Comment by gwarser** [comment]
A nie przypadkiem AdGuard Annoyances? Bo ma ten sam filtr.
