### ISSUE TITLE
magazyn.wp.pl

### ISSUE THREAD

**Issue by salionPL** [MajkiIT/polish-ads-filter#14171]
**Adres strony:** https://magazyn.wp.pl/artykul/but-w-ktorym-chodzi-caly-swiat

![Screenshot_2019-07-21 But, w którym chodzi cały świat – Magazyn WP](https://user-images.githubusercontent.com/38588787/61590633-867c3880-abbc-11e9-849b-16ec6cbd53d1.png)

**Moja konfiguracja:**

Windows 10 [64bit]
Firefox 68.0.1 [64bit]
uBlock Origin 1.20.2

**Moje listy filtrów:**
<details>

![filtry](https://user-images.githubusercontent.com/38588787/59618352-53abd400-9128-11e9-8391-fa1e67d20cd5.png)
</details>

**Comment by krystian3w** [comment]
No obecnie to tak zrandomizowali, że trzeba wycinać po grafice tego "pióra" / stalówki.

**Comment by krystian3w** [comment]
```css
!#if cap_user_stylesheet
magazyn.wp.pl##div:has(div > img[src*="NDM0MzY2YSUsUjtJdklsMG8KbxkpWhE3OVRvVntHbH5vHyQXOFUrN2JRLBh2XCcmY0AjHXtP"])
magazyn.wp.pl##body:style(overflow: auto !important;)
!#endif
magazyn.wp.pl##+js(overlay-buster.js)
```

Jestem ciekaw jak oni oszukają overlay-buster.js, bo chyba jak zrobią większą randomizacje, to będzie jedyną nadzieją jak ciężko namierzyć bait.

**Comment by krystian3w** [comment]
Niby tech WP też przywróciło ten komunikat:

https://tech.wp.pl/maly-krok-gdyby-byl-wiekszy-astronauta-potknalby-sie-o-kabel-6404269922420865a

tam może da się szukać tła obrazkowego?

**Comment by MajkiIT** [comment]
@F4z @adamWr @krystian3w Nie wróciło to ?

**Comment by krystian3w** [comment]
Na magazynie działa dodany `overlay-buster.js`. Adam naprawia jak może w AdGuard ale niestety z uBlock Origin są kwiatki w postaci blokowania przewijania i rozmazywaniem elementów filtrami CSS3.

---

@lain566 can you create better scriplet for this 💩? IMO now no possible safe hide po-pup with procedural filtering.

**Comment by xMaap** [comment]
Na tym `https://tech.wp.pl/maly-krok-gdyby-byl-wiekszy-astronauta-potknalby-sie-o-kabel-6404269922420865a` mam takom lukę
![Zrzut ekranu z 2019-07-25 06-04-51](https://user-images.githubusercontent.com/36385327/61845089-262e1500-aea2-11e9-9be3-1754ad2939bc.png)

**Comment by xMaap** [comment]
To samo
`https://moto.wp.pl/karetka-na-skraju-zalamania-nerwowego-6404321947252353a`

**Comment by krystian3w** [comment]
Tam wcisnęli coś nad nagłówek, to bardzo utrudnia ukrycie resztki jak się uda zrobić 1 dniowy filtr na wycięcie komunikatu.

Div jakby był odporny na filtrowanie kosmetyczne w uBO.

**Comment by lain566** [comment]
@krystian3w This filter blocks the cookie consent notice, and at the same time blocks the anti adblock.
`wp.pl##+js(abort-on-property-read.js, wp_consent_version)`


But, If you add that filter, does this site break?
`https://sportowefakty.wp.pl/tenis/831925/hubert-hurkacz-moge-byc-na-szczycie`

**Comment by krystian3w** [comment]
Suppose can break comments expand if WP troll wrote more than 5.
