### ISSUE TITLE
otube.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14174]
to samo co na horrtube kiedys bylo 

test link:
https://otube.pl/serial-online/the-society/2816/like-a-f-ing-god-or-something

![Capture](https://user-images.githubusercontent.com/15007183/61591297-1ad1a580-ab93-11e9-951b-5ae008a62897.PNG)

**Comment by xxcriticxx** [comment]
chyba to dziala `otube.pl###aliLink`

**Comment by krystian3w** [comment]
Najlepiej dopisać do wszystkich filtrów dla horrortube i test.
