### ISSUE TITLE
I kept my multimillion dollar business secret

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14187]
https://www.bbc.com/news/business-49015609

**Comment by hawkeye116477** [comment]
@xxcriticxx To tyle masz kasy i nie dałeś nic na wsparcie Oficjalnych Polskich Filtrów Reklamowych? Nieładnie :stuck_out_tongue:

**Comment by xxcriticxx** [comment]
@hawkeye116477 poczytaj jak krajowy się dorobił może i ciebie coś dobrego wyrośnie
