### ISSUE TITLE
torsluzewiec.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14194]
![Screenshot_20190723_161846](https://user-images.githubusercontent.com/36385327/61719627-9420f200-ad65-11e9-904f-2b9bf876d1a7.png)

**Comment by krystian3w** [comment]
Duplicate of #14161

**Comment by krystian3w** [comment]
@hawkeye116477 chyba trzeba odpalić PR, by było mniej "sklerozy".

**Comment by xMaap** [comment]
Ja głupi.

**Comment by hawkeye116477** [comment]
PR będzie jutro.
