### ISSUE TITLE
AdBlock X za darmo na iOS

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#14196]
@xxcriticxx Coś dla ciebie, AdBlock X na iOS wcześniej kosztował 26 zł, a teraz jest promocja i jest za friko :smile:
`https://www.pepper.pl/promocje/adblock-x-safari-ios-za-darmo-174739`

**Comment by xxcriticxx** [comment]
@hawkeye116477 gracias dios por este dia
