### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#14197]
**Site Sample** | 
----------------|
https://pilot.wp.pl/tv

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64 (lastest)
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.1.xxxx NIGHTLY** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Block WebRTC/Location API/Java/Flash
|Hide your search queries
|Remove X-Client-Data header from HTTP requests
|Send Do-Not-Track header
|Strip tracking parameters from URLs
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuckadblock
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| Fanboy's Annoyances
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

TV nie działa bo:
```
www.googletagmanager.com/gtm.js?id=GTM-5K4W5WJ:1 Failed to load resource: the server responded with a status of 500 ()
wpjslib-sgap.js:1 Uncaught SyntaxError: Unexpected token }
static.hotjar.com/c/hotjar-1107077.js?sv=6:1 Failed to load resource: the server responded with a status of 500 ()
static.hotjar.com/c/hotjar-1078844.js?sv=6:1 Failed to load resource: the server responded with a status of 500 ()
light-app.c5cac688801ac23c6365.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at light-app.c5cac688801ac23c6365.min.js:1
    at Array.map (<anonymous>)
    at light-app.c5cac688801ac23c6365.min.js:1
    at l (light-app.c5cac688801ac23c6365.min.js:1)
    at f (light-app.c5cac688801ac23c6365.min.js:1)
    at light-app.c5cac688801ac23c6365.min.js:1
raven.min.js:2 GA set userId: ReferenceError: ga is not defined
raven.min.js:2 Uncaught TypeError: Cannot read property 'application' of undefined
    at Object.runGaf (app.c5cac688801ac23c6365.min.js:1)
    at app.c5cac688801ac23c6365.min.js:1
    at Object.next (app.c5cac688801ac23c6365.min.js:1)
    at HTMLDocument.<anonymous> (app.c5cac688801ac23c6365.min.js:1)
    at HTMLDocument.d (raven.min.js:2)
    at Xa.h (<anonymous>:156:174)
    at mc (<anonymous>:174:1034)
    at <anonymous>:162:358
    at <anonymous>:156:378
    at HTMLDocument.dispatchEvent (<anonymous>:155:474)
    at light-app.c5cac688801ac23c6365.min.js:1
    at d (raven.min.js:2)
```

<details><summary><b>Screenshot:</b></summary>

![s](https://i.imgur.com/Ual8Etl.png)

</details><br/>

**Comment by krystian3w** [comment]
Error niby że Google przeciążone, AdGuard nie wspiera chyba jeszcze przekierowania na oczyszczony Google Tag Manager, a przynajmniej dalej w Aplikacji na Windows?

**Comment by FadeMind** [comment]
@krystian3w nie wiem o co mnie pytasz. Nadmienię, że w nanoAdblocker też nie działało z tym samym błędem.

**Comment by AdamWr** [comment]
>`7.1.xxxx NIGHTLY`

To raczej wina tego błędu - https://github.com/AdguardTeam/CoreLibs/issues/1014
W wersji stabilnej działa u mnie prawidłowo.

**Comment by krystian3w** [comment]
U mnie nie działa może co drugi kanał ale niekoniecznie od blokowania googli/hot jarów/śledzenia.

**Comment by FadeMind** [comment]
> W wersji stabilnej działa u mnie prawidłowo.

To ciekawe, że z rozszerzeniem ADG (stable) ze sklepu Google też jest to samo (Adguard for WIndows wyłączony). 

![s](https://i.imgur.com/hy2BbaV.png)

**Comment by AdamWr** [comment]
U mnie z rozszerzeniem działa prawidłowo.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/61814892-5e553980-ae49-11e9-96f7-d88e03fd2d98.png)

</details>

Spróbuj może odświeżyć stronę używając `Ctrl + F5`.

**Comment by FadeMind** [comment]
@AdamWr jakie masz filtry aktywne?

**Comment by AdamWr** [comment]
<details><summary>Filtry</summary>

```
Podstawowy filtr AdGuard
Peter Lowe's list

Filtr elementów szpiegujących AdGuard
EasyPrivacy

Filtr mediów społecznościowych AdGuard
Filtr irytujących elementów AdGuard

NoCoin Filter List

Uproszczony filtr nazw domen AdGuard
Eksperymentalny filtr AdGuard

Niemiecki filtr AdGuard 
Rosyjski filtr AdGuard 
KAD - Przekręty 
Official Polish filters for AdBlock, uBlock Origin & AdGuard 
Polish Anti Adblock Filters 
Polskie Filtry Ciasteczkowe 
```

</details>

Moim zdaniem problem dotyczy tego `wpjslib-sgap.js:1 Uncaught SyntaxError: Unexpected token }` i jest to najprawdopodobniej spowodowane przez błąd o którym pisałem wcześniej.
Próbowałeś w trybie prywatnym/incognito?

**Comment by FadeMind** [comment]
@AdamWr cofnąłem do wersji stabilnej - działa. Dzięki.

![a](https://i.imgur.com/fdqO8HT.png)
