### ISSUE TITLE
certum.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14209]
Resztka po socialach ( po lewo )
Co z tym czy do sociali czy do EI a może do obu ?

**Comment by krystian3w** [comment]
Tylko w social, nie ma tam np. koszyka wciśniętego.

**Comment by blocker999** [comment]
a widżety z tej stronki : https://www.stanmed24.pl/  
jak kwalifikować ?

**Comment by krystian3w** [comment]
Poza FB i YT to one do EI w `inne.txt`. 

Wycinaj każdy z osobna - czyli 3 filtry, potem się zbije w 1.
