### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1421]
Prawdopodobnie ta reguła `pl##.ad` ukrywa autora i datę dodania tekstu.
Link - `http://www.komputerswiat.pl/`
![image](https://cloud.githubusercontent.com/assets/11742596/19839215/0a3ed612-9ede-11e6-8da9-1d8172b594f3.png)

Na przykład:
`komputerswiat.pl#@#.ad`

**Comment by MajkiIT** [comment]
@F4z Dzięki
