### ISSUE TITLE
powiat-piaseczynski.info

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14224]
RODO + reklama : kolonoskopia

**Comment by krystian3w** [comment]
Karmienie w prawej kolumnie to chyba też jakaś reklama?

**Comment by krystian3w** [comment]
`##.powiatpiaseczynski_bannergroup`

lub

`##div[class$="bannergroup"]`

---

wycina obie reklamy i 8 już ukrytych.
