### ISSUE TITLE
"polskie filtry do Adblocka i uBlocka" a filtry KAD

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#1423]
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt

![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/19850139/30effd58-9f57-11e6-9415-1ed8f555e416.PNG)

@MajkiIT Myślałem, że filtry KAD są dołączone do Twojej listy. Okazuje się, że jednak nie są i trzeba ręcznie dodać oddzielną subskrypcję. Testowałem z http://pl160.microsoft.com-odebrac-nagrode.pw/d1-v739-pl-l/index.html?isp=UPC%20Polska%20Sp.%20z%20o.o.&model=Desktop&voluumdata=BASE64dmlkLi4wMDAwMDAwNS1hY2NjLTQ5YWMtODAwMC0wMDAwMDAwMDAwMDBfX3ZwaWQuLmEyODM4MDAwLTlkNmEtMTFlNi04NjJjLTU3NWIyOGVjMTkyNF9fY2FpZC4uOGIxN2VjYzItZGFmNC00MWI4LThlM2UtYzdiZTZiMjJmZGZhX19ydC4uREpfX2xpZC4uN2M4NTc2YTMtNjJjOC00MTQxLTkxNTktZTFkNzMyYTU1NWYwX19vaWQxLi5kMTZlOTZkMS0wNGQwLTRkMDctODg5MS00MTI0NDk4ZDNiOTNfX3ZhcjEuLjE0ODYwNTZfX3ZhcjMuLjM1X192YXI0Li5QTF9fdmFyNS4uMzQ3MF9fdmFyNi4uMTk1MjU0MzMyOTJfX3JkLi5sYnlwcHB3ZnZhZ3FcLlxjb21fX2FpZC4uX19hYi4uX19zaWQuLg&websiteid=1486056&keyword=&categoryid=35&country=PL&IMPRESSIONID=19525433292&bid=0.00116

Proszę to naprawić.

**Comment by xxcriticxx** [comment]
dodals filtry pod 3rd party filters > custom ? 

![capture](https://cloud.githubusercontent.com/assets/15007183/19851514/b1523646-9f34-11e6-8445-96d84b77a7d5.PNG)

**Comment by adreporter** [comment]
@xxcriticxx Tak.

**Comment by xxcriticxx** [comment]
zrobiles update? jak dzialaja zobaczysz to co ja mam

**Comment by adreporter** [comment]
Ale ja widzę to co ty.

**Comment by xxcriticxx** [comment]
o co chodzi?

**Comment by adreporter** [comment]
Chodzi o to, że jak odznaczysz filtry KAD to będziesz miał reklamę.

**Comment by xxcriticxx** [comment]
ale poco je odznaczac?

**Comment by adreporter** [comment]
Ostatni raz piszę: chodzi o to, że nie powinieneś mieć tej reklamy, bo te filtry KAD są już automatycznie zawarte w liście o nazwie "polskie filtry do Adblocka i uBlocka".

**Comment by xxcriticxx** [comment]
@adreporter zapytamy @MajkiIT 

@MajkiIT dziala te twoje automatycznie dodawanie?

**Comment by MajkiIT** [comment]
Niestety one są dodawane z automatu. Wpis w liście filtrów to tylko informacja dla kogoś, ze jest oddzielna lista.
