### ISSUE TITLE
eska.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14244]
https://www.eska.pl/news/kuce-z-bronksu-co-to-jest-imiona-bohaterow-aa-WQy9-ZM6D-BrcA.html

też ma boxy reklamowe jak: #14098, #14080

**Comment by MajkiIT** [comment]
to pasuje ?
`##.zpr_m_inside_top.active, div[class*="zpr_m_inside"].active, div[class*="zpr_inside"].active, div[class*="zpr_box"].active > div[class*="zpr_"]`

**Comment by krystian3w** [comment]
Tak 👍.
