### ISSUE TITLE
Problem wp

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1424]
Na Wirtualnej Polsce nie wyświetla całej strony, tylko górną jej część. Po wyłączeniu Adblocka widać całość. Pozdrawiam

**Comment by F4z** [comment]
@MajkiIT u mnie nic takiego się nie dzieje, swoją drogą opis przypomina to co na onecie było.
Natomiast ja mam znowu komunikat o adblocku przy filmach, na przykład tutaj - `http://sportowefakty.wp.pl/pilka-nozna/641925/inter-mediolan-chetny-do-pozyskania-grzegorza-krychowiaka-wykorzysta-problemy-po`
Poprawiona reguła:
`@@/:\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(.{0,10}[&!*;@\$)[\]:%].*|(?!gaf|cap|vad)[a-zA-Z0-9\W_]{1,10})\.(js|html|xml|jpg|gif|png)/`

**Comment by xxcriticxx** [comment]
u mnie jest ok na wp.pl widze cala strone 

`http://sportowefakty.wp.pl/pilka-nozna/641925/inter-mediolan-chetny-do-pozyskania-grzegorza-krychowiaka-wykorzysta-problemy-po`

to sie umnie nie laduje caly czas tylko sie kreci

**Comment by adreporter** [comment]
U mnie też jest ok na Wirtualnej Polsce.

**Comment by adreporter** [comment]
Mi też się wyświetla poprawnie cała strona wp

**Comment by MajkiIT** [comment]
Dzięki
