### ISSUE TITLE
autodesk.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14245]
![Zrzut ekranu z 2019-07-27 23-04-32](https://user-images.githubusercontent.com/36385327/61999519-0f1a3d80-b0c3-11e9-8fed-8dcdc2ecafe3.png)

**Comment by krystian3w** [comment]
```
autodesk.pl###adsk-eprivacy-body-parent
autodesk.pl##.adsk-eprivacy-force-html, .adsk-eprivacy-force-html body:style(overflow: auto !important;)
```

sprawdź czy odblokowuje ci przewijanie.

**Comment by xMaap** [comment]
Działa.
