### ISSUE TITLE
zasada.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14246]
![Zrzut ekranu z 2019-07-27 23-10-45](https://user-images.githubusercontent.com/36385327/61999543-cc0c9a00-b0c3-11e9-82af-b31fd4793eea.png)

**Comment by krystian3w** [comment]
zbugowany:

`pl###cookie-info:not(body):not(html)`

**Comment by krystian3w** [comment]
@kiboke:

`###cookie-glass:not(body):not(html)`

?

**Comment by kiboke** [comment]
Thanks!
