### ISSUE TITLE
Polskie filtry elementów społecznościach

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#1425]
@MajkiIT

Czy interesuje Cię współpraca nad tym filtrem?

czy nie będzie on kontynuowany?

**Comment by xxcriticxx** [comment]
@blocker999 podaj wiecej info?

**Comment by blocker999** [comment]
O jakie info konkretnie Ci się rozchodzi?, po prostu mam około 300 skryptów blokujących a pytam się o takową aktualizacje gdyż nie chce dublować paczek.

**Comment by xxcriticxx** [comment]
to jest cos dla @MajkiIT

**Comment by blocker999** [comment]
@xxcriticxx

Tak, ale śmiało możesz dorzucić swoją propozycje aby jakoś go przekonać do współpracy lub zaproponować inne rozwiązanie.

**Comment by xxcriticxx** [comment]
to twoje filtry @azet12 podawal?

**Comment by xxcriticxx** [comment]
o te filtry chodzic?

`https://raw.githubusercontent.com/azet12/PopupBlocker/master/PPB.txt`

**Comment by blocker999** [comment]
Tak, filtry udostępnione przez azet12 to moja sprawka, lecz tym razem chodzi mi o osobny projekt tzn o blocker social mediów na Polskich stronach (  uzupełnienie Fanboy’s Social Blocking List  )

Konkretnie o współprace nad aktualizacją projektu MajkiIT :  

http://www.certyficate.it/polskie-filtry-elementow-spolecznosciach/

**Comment by MajkiIT** [comment]
@xxcriticxx dzięki za pomoc

@blocker999 jeśli chcesz to bardzo chętnie. Ja niestety nie mam już tyle czasu aby się tym zajmować, ale jeśli masz moce przerobowe to zmieniaj śmiało.

**Comment by blocker999** [comment]
Ok, tzn jak to zrobić podesłać Ci na maila czy tu udostępnić a Ty zaktualizujesz tą paczke?.

**Comment by MajkiIT** [comment]
Jak Ci wygodniej. Dostosuje sie.

**Comment by xxcriticxx** [comment]
@MajkiIT jak to testujemy?

**Comment by blocker999** [comment]
Paczka jest tu: #1426

Zapraszam
