### ISSUE TITLE
procopy.info.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14260]
cookies i FB ( button )

**Comment by krystian3w** [comment]
@hawkeye116477  a tu jak cookies wycieka, blokowane tylko na dev?

**Comment by hawkeye116477** [comment]
Nie wycieka, ale scrolla coś blokuje.

**Comment by krystian3w** [comment]
A może on ma uBO dev z poprawką by logger nie pokazywał filtrów `:style(...)` jak nie ma dopasowania do drzewa DOM html strony?

**Comment by blocker999** [comment]
@hawkeye116477  Dzięki ale wole lapki poleasingowe, może jakieś propozycje ?
