### ISSUE TITLE
Social media blocker ( PL )

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#1426]
Zapraszam wszystkich do testów i proszę pisać co jest w tej paczce nie tak lub o inne sugestie.

[social media blocker ( PL ).txt](https://github.com/MajkiIT/polish-ads-filter/files/565121/social.media.blocker.PL.txt)

**Comment by xxcriticxx** [comment]
@blocker999 dodaj to w innym formacie bo wszystko sie zlewa w txt pliku

**Comment by F4z** [comment]
@blocker999 można się czepiać? 😛

Te trzy reguły są raczej niepoprawne:
`#div(sledzik_box)`
`#div(sledzik_promo)`
`#sledzik_box{display:none;}`

Tej regule brakuje dwóch kratek (##) z przodu:
`li:nth-of-type(2)`
Swoją drogą, nie wiem czy zapomniałeś jej usunąć, czy właśnie dodać tych kratek, ale ta reguła jest "niebezpieczna", bo zablokuje na wielu stronach prawidłowe treści.

Tej regule też brakuje dwóch kratek:
`div:nth-of-type(2) > div > .protected.floatingElem > .shareWidget`

Ta reguła - `/images/*.png$image` też wygląda na "niebezpieczną". Nie wiem czy to zamierzone, ale na stronie `https://www.google.pl/` blokuje logo i inne ikonki , tutaj też blokuje logo sklepu - `http://www.ultima.pl/` , tu też blokuje wiele obrazków - `http://www.fabrykakluczy.pl/`
Tutaj - `http://ekstraklasa.tv/skroty/korona-legia-2-4-zobacz-skrot-meczu/r906wx` blokuje logo strony oraz ikonki z odtwarzacza. Na innych stronach też blokuje obrazki, które nie powinny być zablokowane.

Ta reguła - `www.polsat.pl##header > .topFixed.topDarkActive.top > .top-container > .top-links > .fb-top` u mnie nie działa, widocznie coś zmienili.
Wystarczy usunąć `.topFixed` i będzie działać - `www.polsat.pl##header > .topDarkActive.top > .top-container > .top-links > .fb-top`

Te trzy reguły:
`###sidebar > .no-mobile.block:nth-of-type(7) > .block-content > .clearfix.nested-grid:nth-of-type(1) > .span-2:nth-of-type(1) > a[href="http://www.facebook.com/dobreprogramy"] > h3`
`###sidebar > .no-mobile.block:nth-of-type(7) > .block-content > .clearfix.nested-grid:nth-of-type(1) > .span-2:nth-of-type(2) > a[href="http://www.twitter.com/dobreprogramy"] > h3`
`###sidebar > .no-mobile.block:nth-of-type(7) > .block-content > .clearfix.grid-margin-top.nested-grid > .span-2:nth-of-type(1) > a[href="https://plus.google.com/+dobreprogramy"] > h3`
blokują same linki, ikonki zostają.
![image](https://cloud.githubusercontent.com/assets/11742596/19910934/9021a2d8-a090-11e6-9a74-e9f4b13502e1.png)
A tak w ogóle, moim zdaniem to mało prawdopodobne żeby te trzy reguły zadziałały na innych stronach, więc można dodać do nich konkretną stronę. To dotyczy też kilku innych reguł.

Ze względu na to, że ta reguła - `###cbp-hrmenu > ul > .visible-lg-inline-block.sc.img:nth-of-type(13) >` jest prawdopodobnie nieprawidłowa i nie działa, to na stronie `https://www.radiolodz.pl/` zostaje ikonka facebooka, w prawym górnym rogu.
Oprócz tego, to te 8 reguł, które dotyczą tej strony, można by zastąpić jedną, na przykład taką:
`radiolodz.pl##a[rel="me noopener"][target="_blank"]`

Jak będę miał więcej czasu to jeszcze popatrzę na inne reguły.
Miałem też przejrzeć listę `PopupBlocker` i po części to zrobiłem, ale że była aktualizacja, to może coś zostało poprawione.
Tutaj moje uwagi:
<pre>
! 27.10.2016, 20:43:29 http://www.monashe.pl/ - do poprawy
monashe.pl###fancybox-overlay
monashe.pl##.fancybox-wrap

! 27.10.2016, 20:46:29 http://wearmedicine.com/on-5-k.html - do poprawy
wearmedicine.com###colorbox
wearmedicine.com###cboxOverlay

! 27.10.2016, 20:49:44 http://dstreet.pl/ - do poprawy, niewidoczny element blokuje możliwość kliknięcia w niektóre elementy (element jest mniej więcej po środku)
dstreet.pl###tws_i_0

! 27.10.2016, 21:00:19 https://factoryprice.pl/ - reguła do poprawy, brakuje jednej kratki (#) - ##simplemodal-overlay
factoryprice.pl###simplemodal-overlay

! 27.10.2016, 21:02:41 http://japanstyle24.pl/ - do poprawy, niewidoczny element blokuje możliwość kliknięcia w niektóre elementy (element jest po prawej stronie)
japanstyle24.pl###tws_i_0

! 27.10.2016, 21:08:37 http://ptakmoda.com/ - w ogóle nie jest ukrywane okienko
ptakmoda.com##.fancybox-overlay
ptakmoda.com##html.fancybox-lock:style(overflow: auto !important;)

! 27.10.2016, 21:12:06 http://pandzior.pl/ - do poprawy, id generowane losowo, te reguły nie działają - ###grwf2_3453105_fiiif ###grwf2_6564003_tut7h ###grwf2_6565603_dfd0d
pandzior.pl##[class^="grwf2"]

! 27.10.2016, 21:21:40 http://avaro.pl/ - do poprawy, niewidoczny element blokuje możliwość kliknięcia w niektóre elementy (element jest mniej więcej po środku)
avaro.pl###tws_i_0

! 27.10.2016, 21:28:45 http://www.9fashion.pl/Sklep/ - do poprawy, niewidoczny element blokuje możliwość kliknięcia w niektóre elementy (element jest mniej więcej po środku)
9fashion.pl##.lpl-window

! 27.10.2016, 21:34:37 http://www.halens.pl/#popup - do poprawy, nie da się przewijać strony
halens.pl##html > body.freeze > #container:style(z-index: 0 !important; position: relative !important;)
halens.pl###popup-container
Ale nie jest to dobre rozwiązanie, bo reguły ###popup i ###popup-container blokują możliwość obejrzenia filmu, potem może wymyślę coś lepszego

! 27.10.2016, 21:56:26 https://www.czasnabuty.pl/ - w ogóle nie jest ukrywane okienko
czasnabuty.pl###pushpushgo-container

! 27.10.2016, 21:57:55 http://pantofelek24.pl/ - do poprawy, niewidoczny element blokuje możliwość kliknięcia w niektóre elementy (element jest mniej więcej po środku)
pantofelek24.pl###tws_i_1

! 27.10.2016, 22:01:38 http://www.kupbuty.com/ - do poprawy, niewidoczny element blokuje możliwość kliknięcia w niektóre elementy (element jest mniej więcej po środku)
kupbuty.com###tws_i_1
</pre>

Ogólnie dużo tych stron i reguł, i ciężko przejrzeć wszystko od razu.
Moim zdaniem część tych reguł jeśli się da, to warto uprościć albo dodać domeny przed nimi, jeśli wyglądają "podobnie" do tych, które były do strony dobreprogramy, czy euronews.

**Comment by xxcriticxx** [comment]
@F4z nie mozesz spac?

**Comment by MajkiIT** [comment]
@F4z jesteś kozak 👍

**Comment by blocker999** [comment]
Wielkie dzięki dla @F4, poprawie te błędy i opublikuje tu poprawianą wersje.

**Comment by blocker999** [comment]
Ok, aktualizacja dodana, więc tak: usunąłem całkowicie te trzy reguł do śledzika bo prawdopodobnie są niepoprawne i jeszcze usunąłem  /images/*.png$image gdyż za dużo blokuje, te dwie reguły z kratkami poprawione polsacik też, reguły na Dobrychprogramach zostawiłem, ponieważ ma to być tylko uzupełnienie filtra " Fanboy’s Social Blocking List " który blokuje ikonki na tej stronie, mogę zrobić ustępstwo ale nie wiem poco dublować reguły?. radiolodz.pl ma zoptymalizowaną regułę.

@F4z 

Na pewno warto niektóre reguły uprościć, ale nie wiem jak, więc w tej kwesti liczę na Twą pomoc lub 
kolegów.

Jeszcze raz przejże te filtry i ewentualnie do niektórych dodam domeny tak by nie blokowały coś na innych stronach.
[social media blocker ( PL ) - 2.txt](https://github.com/MajkiIT/polish-ads-filter/files/567449/social.media.blocker.PL.-.2.txt)

**Comment by F4z** [comment]
@blocker999 ok, tak na szybko, bo w tej chwili nie chce mi się dokładniej sprawdzać.
Ta reguła - `##li:nth-of-type(2)` jest "niebezpieczna", bo blokuje na wielu stronach wiele elementów, które są zwykłą treścią.
Na przykład na pclab.pl
![image](https://cloud.githubusercontent.com/assets/11742596/19943650/9fa76370-a138-11e6-908a-79f7d3c2c2dd.png)
![image](https://cloud.githubusercontent.com/assets/11742596/19943679/ba071aa8-a138-11e6-9571-c97bcdade8bd.png)

Te elementy podświetlone na czerwono zostaną ukryte przez tę regułę, więc moim zdaniem tak jak już pisałem poprzednio, ją też warto usunąć.

Odnośnie dobrychprogramów, to ok, skoro to uzupełnienie "Fanboy’s Social Blocking List", to jest w porządku. Tylko mi chodziło też o to, żeby dodać domenę przed samą regułą:
`dobreprogramy.pl###sidebar > .no-mobile.block:nth-of-type(7) > .block-content > .clearfix.nested-grid:nth-of-type(1) > .span-2:nth-of-type(1) > a[href="http://www.facebook.com/dobreprogramy"] > h3`
`dobreprogramy.pl###sidebar > .no-mobile.block:nth-of-type(7) > .block-content > .clearfix.nested-grid:nth-of-type(1) > .span-2:nth-of-type(2) > a[href="http://www.twitter.com/dobreprogramy"] > h3`
`dobreprogramy.pl###sidebar > .no-mobile.block:nth-of-type(7) > .block-content > .clearfix.grid-margin-top.nested-grid > .span-2:nth-of-type(1) > a[href="https://plus.google.com/+dobreprogramy"] > h3`
bo jest mało prawdopodobne żeby taka reguła `###sidebar > .no-mobile.block:nth-of-type(7) > .block-content > .clearfix.nested-grid:nth-of-type(1) > .span-2:nth-of-type(1) > a[href="http://www.facebook.com/dobreprogramy"] > h3` zadziała na innej stronie, a z tego co wiem, to reguły, które nie są ogólne, są szybciej ładowane w przypadku uBlocka.
Tutaj https://easylist-downloads.adblockplus.org/fanboy-social.txt też wiele reguł zawiera konkretną domenę.

Jeśli chodzi o uproszczenie reguł, to na przykładzie dobrychprogramów:
`dobreprogramy.pl##.span-2 > a[href="https://plus.google.com/+dobreprogramy"] > h3`
`dobreprogramy.pl##.span-2 > a[href="http://www.facebook.com/dobreprogramy"] > h3`
`dobreprogramy.pl##.span-2 > a[href="http://www.twitter.com/dobreprogramy"] > h3`
albo jeszcze prościej:
`dobreprogramy.pl##a[href="https://plus.google.com/+dobreprogramy"]`
`dobreprogramy.pl##a[href="http://www.facebook.com/dobreprogramy"]`
`dobreprogramy.pl##a[href="http://www.twitter.com/dobreprogramy"]`

Można też sobie spojrzeć jak są właśnie zrobione reguły "Fanboy’s Social Blocking List", tam zazwyczaj te reguły są "krótkie", dotyczą na ogół konkretnej "klasy", "id", linku, a nie całej "ścieżki" do tego.
Wiem, że nie zawsze też da się zrobić w ten sposób regułę, bo czasami ukrywając element o danej nazwie ukryje się też inne przydatne rzeczy, ale często jest to możliwe.
Oczywiście to tylko moje zdanie i możesz się z nim nie zgadzać.

**Comment by xxcriticxx** [comment]
@blocker999 jak bendzie troche czasu to potestuje :)

**Comment by blocker999** [comment]
@xxcriticxx Ok

**Comment by xxcriticxx** [comment]
@blocker999 ty w usa? or polonia?

**Comment by blocker999** [comment]
@xxcriticxx  nie nie Ja być z Polska a ty chyba america bo śpisz

**Comment by xxcriticxx** [comment]
usa

**Comment by blocker999** [comment]
ok, ale łączy na język Polski, moje blokery są głównie skierowane na Polskie strony ale mogą być i polonijne, ważne że chcesz pomóc.

**Comment by xxcriticxx** [comment]
ja przerabiam tylko poslkie strony

**Comment by blocker999** [comment]
ok, to dobrze się składa bo u mnie tylko są, rzuć okiem na tą liste jak będziesz miał wolny czas

**Comment by xxcriticxx** [comment]
postaram sie

**Comment by blocker999** [comment]
Jaki tu spokój ...

**Comment by xxcriticxx** [comment]
nuda...

**Comment by xxcriticxx** [comment]
@blocker999 bendzie jakis nowy update?

**Comment by blocker999** [comment]
Tak będzie całkiem nowa wersja w środe, wiem że to troche późno ale czekałem na  Twoje " rady " i się nie doczekałem więc postanowiłem zrobić odnowa całą liste ale cały czas opartą na blokowaniu social mediów na Polskich stronach.

**Comment by xxcriticxx** [comment]
@blocker999 ja podaje strony chlopaki robja reszte czyli rady odemnie bendzie cieszko dostac

**Comment by xxcriticxx** [comment]
@blocker999 polecam otworzyc swoje respositorie i podac nam info

**Comment by blocker999** [comment]
Dziś przedstawiam nową wersje, choć wiele jest starych reguł , generalnie chciałem uprościć filtry ale niewiem czy mi się to udało, więc proszę o pomoc.

[social media new.txt](https://github.com/MajkiIT/polish-ads-filter/files/609813/social.media.new.txt)
[social media new.docx](https://github.com/MajkiIT/polish-ads-filter/files/609814/social.media.new.docx)
[social media new.pdf](https://github.com/MajkiIT/polish-ads-filter/files/609817/social.media.new.pdf)

**Comment by MajkiIT** [comment]
@blocker999 dzięki

**Comment by blocker999** [comment]
@MajkiIT  Narazie to wersja testowa ale za jakiś czas się odezwe w sprawie aktualizacji filtru " Polskie filtry elementów społecznościach " tylko czekam na uwagi i wskazówki aby to doszlifować, by bublu niewydać.

**Comment by blocker999** [comment]
@xxcriticxx @F4z i wszyscy Wy którzy chcecie aby oczyścić Polski internet rzućcie okiem na te filtry.

**Comment by MajkiIT** [comment]
@blocker999 może wrzucę na FB info? Co myślisz?

**Comment by blocker999** [comment]
Ja bym wolał narazie tego nie głosić na FB no chyba że liczysz na " testerów ", można dać te info albo poczekać na oficjalną wersje ale rób jak chcesz.

**Comment by blocker999** [comment]
@MajkiIT czy warto dodać przed skryptem domene ( .pl ) by szybciej się ładowały filtry?

**Comment by MajkiIT** [comment]
to zależy, bo domena może być różna .com, .org i nie zadziała. Na początku możemy dać z pl jak coś będziemy zmieniać.

**Comment by blocker999** [comment]
@MajkiIT 

nie, tzn wiem i mam listę i te tzw inne domeny niż.pl będą mieć  pełny adres, a reszta będzie mieć .pl ponieważ stron tego typu je wiele a ja sam, ok?

**Comment by MajkiIT** [comment]
ok, niech tak będzie :)

**Comment by blocker999** [comment]
ok, w takim razie jutro podeśle Ci na meila oficjalną wersje

TEMAT DO ZAMKNIECIA

**Comment by blocker999** [comment]
@MajkiIT Ktoś uwas odbiera poczte?

**Comment by xxcriticxx** [comment]
listonosz

**Comment by blocker999** [comment]
dobrze że nie komornik

**Comment by MajkiIT** [comment]
@blocker999 ja odczytuje. Co tam?
