### ISSUE TITLE
komputerytriton.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14273]
RODO

**Comment by krystian3w** [comment]
Dziwny ten pum "pop-up" - przewija się strona a suwaka nie widać 🤣

**Comment by krystian3w** [comment]
A już widzę tam jest "nice-scroll-rails".

`#airdron-polska.pl,paralympic.org.pl,manageronline.pl`

https://github.com/MajkiIT/polish-ads-filter/issues/10265#issuecomment-441835474
