### ISSUE TITLE
take-kino.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#14284]
https://take-kino.pl/

Overlay + popup?

![s](https://i.imgur.com/RLQY1r5.png)

```
take-kino.pl##div.ui-widget-overlay.ui-front:last-child
take-kino.pl##div.ui-dialog.ui-widget.ui-widget-content.ui-corner-all.ui-front.ui-resizable:nth-child(25)
```

@krystian3w

**Comment by krystian3w** [comment]
Kij wie co to jest, może wykrywacz "AdBlocka".

**Comment by krystian3w** [comment]
No chyba to jest wykrywacz "AdBlocka" więc dla Olega zadanie jakkolwiek wyciąć / oszukać.

**Comment by krystian3w** [comment]
`@@/wp-admin/admin-ajax.php?action=adblockvisitor$domain=take-kino.pl`

?

**Comment by FadeMind** [comment]
@krystian3w  Jednolinijkowiec 😉 

`take-kino.pl##.ui-dialog, .ui-widget, .ui-widget-content, .ui-corner-all, .ui-front, .ui-resizable, .ui-widget-overlay`

**Comment by krystian3w** [comment]
Mnie bardziej, chodzi że to nie jest pop-up z reklamą / facebookiem / reklamą wewnętrzną i trzeba by w filtrach anty-adblock wyciąć.

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/d5a69b96bdf5557f05ce06c01b601602afe35eeb#diff-6de60f294b8bd23c752f8fcbece875b1
