### ISSUE TITLE
propozycja allegro.pl

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#1429]
Proponuję usunąć białe puste części na stronie allegro.pl
na górze
![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/20026160/224c7b70-a2f7-11e6-9790-37971281f605.PNG)
w środku
![przechwytywanie2](https://cloud.githubusercontent.com/assets/18214146/20026173/48bf827a-a2f7-11e6-8cf0-f85616265521.PNG)
i na dole
![przechwytywanie3](https://cloud.githubusercontent.com/assets/18214146/20026180/66af4112-a2f7-11e6-9dbd-55a0e702f1d3.PNG)

Filtry które usuwają puste części:
`||ucdn.allegrostatic.pl/showcaseService/static/images/placeholders/1200x400.png$image`
`allegro.pl###main_page_main_1200_400 > .showcase-carousel-container > .showcase-slider-namespace > .carousel-showcase.carousel-fade.carousel > .carousel-indicators`
`allegro.pl###main_page_main_1200_400`
`allegro.pl###mainpage-marketing-showcases > .clearfix`
`allegro.pl###main_page_hr_980_180`

**Comment by MajkiIT** [comment]
@adreporter ok dzięki przetestuje.

**Comment by blocker999** [comment]
Nie chcę się wtrącać ale filtry do allegro są tu: https://tarmas.pl/alleblock/

**Comment by adreporter** [comment]
@blocker999 Dziękuję za informację, wypróbowałem te filtry, ale ja osobiście nie mogę się przyzwyczaić do "prawie pustej" strony Allegro. Natomiast filtry które ja zaproponowałem nie usuwają okazji, oferty własnej i ostatnich przeglądanych produktów.
