### ISSUE TITLE
hitech.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14290]
cookies ( błąd )

" Pętla przekierowań

Podczas łączenia z serwerem „hitech.com.pl” wystąpił błąd.

    Problem ten może się pojawić w wyniku zablokowania lub odrzucenia ciasteczek. "

**Comment by hawkeye116477** [comment]
U mnie jest ok.

**Comment by krystian3w** [comment]
Może:

`akceptCookie:tak` w PZC?

**Comment by hawkeye116477** [comment]
Na razie czekamy na wyjaśnienia od @blocker999, bo niewiele napisał.

**Comment by blocker999** [comment]
na firefoxie z Nano Adblockiem 1.0.0.123 jest błąd
![pętla przekierowań](https://user-images.githubusercontent.com/23176832/62195088-85e16000-b37b-11e9-8fc2-c313a975c0b9.png)

 a na waterfoxie z Nano Adblockerem 1.0.0.103 jest ok

**Comment by hawkeye116477** [comment]
@blocker999 Ale to po zalogowaniu się pojawia czy kiedy? Opisz kroki, które wykonywałeś.

**Comment by blocker999** [comment]
@hawkeye116477 odrazu po wpisaniu adresu w wyszukiwarke firefox ( niewiem może mam coś nagrzebane ) chyba zamkne temat ?

**Comment by hawkeye116477** [comment]
@blocker999 Aha, no to w takim razie chyba jednak coś nie tak po twojej stronie, bo sprawdziłem na FF i NA i jest ok, także do zamknięcia.

**Comment by krystian3w** [comment]
Sprawdź na jakimś darmowym VPN może twój dostawca coś miesza np. lokalni blokują port 53 (DNS) i potem się kłuć że niby nie mogą.
