### ISSUE TITLE
prośba

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1430]
@xxcriticxx  @F4z 
Możecie podać mi maila do siebie? Chciałem coś obgadać z Wami.

**Comment by F4z** [comment]
Wysłałem Ci wiadomość.

**Comment by xxcriticxx** [comment]
az tak zle

**Comment by MajkiIT** [comment]
@xxcriticxx napisz do mnie maila lub podaj

**Comment by xxcriticxx** [comment]
`xxcritic2001xx`
@ 
`hotmail.com`

**Comment by xxcriticxx** [comment]
@MajkiIT done? moge skasowac?

**Comment by MajkiIT** [comment]
Tak już usunąłem. Dziękuje

**Comment by xxcriticxx** [comment]
dostalem emaila thx
