### ISSUE TITLE
xboxforum.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1431]
ad block 

Wykryliśmy, że twoja przeglądarka używa AdBlock'a! :(
Jesteśmy otwartym i darmowym forum dla całej spółczesności graczy na konsolach Xbox. Dlatego potrzebujemy reklam aby pokryć koszty serwera.
Proszę wyłącza AdBlock'a lub zakup RANGĘ SPECJALNĄ, która wyłączy reklamy na forum.

**Comment by F4z** [comment]
@xxcriticxx masz włączoną listę `Anti-Adblock Killer | Reek‎`?

**Comment by xxcriticxx** [comment]
hyba tak :)

**Comment by F4z** [comment]
Pytam, bo tam jest reguła, która powinna ukrywać ten komunikat - `xboxforum.pl##.noticeContainer:not(.hidden)`

**Comment by xxcriticxx** [comment]
zaponialem ze jestem na nowym pc

ok lista wlonczona zamykam

**Comment by F4z** [comment]
Ok :)
