### ISSUE TITLE
MLP

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14329]
@hawkeye116477 coś dla ciebie kupiłem!

![0D4542D8-8ED0-4DDE-9ADB-6E90C43E1F98](https://user-images.githubusercontent.com/15007183/62426402-6f584300-b6b2-11e9-9954-90cabe3a2805.jpeg)

**Comment by hawkeye116477** [comment]
Nie jestem zainteresowany MLP :stuck_out_tongue:

**Comment by krystian3w** [comment]
Jesienią będą kuce z Bronksu seria 2 odc. 8 lub seria 3.

https://www.youtube.com/channel/UCof4jJ9hM9RLsBII8laZI5A

**Comment by hawkeye116477** [comment]
Nie interesują mnie kucyki, wolę hity Marvela albo Gwiezdne Wojny :stuck_out_tongue:

**Comment by xxcriticxx** [comment]
@hawkeye116477 nie zmieniaj tematu

**Comment by hawkeye116477** [comment]
@xxcriticxx A ja też mam coś dla ciebie
<img src="https://vignette.wikia.nocookie.net/kiepscy/images/f/f2/2017-08-31_20.56.35.png/revision/latest/scale-to-width-down/180?cb=20170831185644"/> :smile:

**Comment by xxcriticxx** [comment]
dzięki
