### ISSUE TITLE
odkrywamyzakryte.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#14331]
cookie

**Comment by krystian3w** [comment]
wciąż brak info czy jak KAD blokuje `pseudonaukę` / `fakenews` to czy na stronie wycinamy:

- reklamy
- cookies
- social
- komunikaty Anty-adblock - niby na tej nienaprawiony https://github.com/MajkiIT/polish-ads-filter/issues/12945:

   > ![image](https://user-images.githubusercontent.com/35370833/62452898-61b5c280-b771-11e9-9c75-718c61546a2c.png) |
   > --- |

   * a nic mi nie wiadomo by nagle wszyscy Polacy musieli aktywować listę `Bogachenko FFA ` / AdGuard Base czy AdGuard Annoyance by się pozbyć komunikatu.

**Comment by hawkeye116477** [comment]
Jest sekcja odblokowująca również te strony, więc raczej chyba powinniśmy też wycinać tam social i ciastka,
