### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#14332]
Bardzo duża pusta przestrzeń pomiędzy sekcjami głównymi.
```
dobreprogramy.pl###page-content > div.home-section.grid-margin-px30-top:nth-child(3)
```

https://imgur.com/a/GXhMYcQ

@krystian3w

**Comment by krystian3w** [comment]
@AdamWr / @F4z chyba popsute w AdGuard Annoyance (RODO filtr na platformy bez obsługi odpowiednich skryptów.

Adam, dopisz do filtra sieciowego wyjątek:

https://github.com/MajkiIT/polish-ads-filter/blob/ee78fd29040daddbb79032c10c9c17d4ee3e481b/polish-adblock-filters/adblock.txt#L4101

lub oceńcie to czy u was wymagane:

https://github.com/AdguardTeam/AdguardFilters/pull/38079

---

@FadeMind sprawdź czy ci pomoże:

`@@||wp.pl/*-FwkqOxhmGz4XCSo7GGYbPhcJKjsYZhs-$script,domain=pilot.wp.pl|www.dobreprogramy.pl`

**Comment by FadeMind** [comment]
> sprawdź czy ci pomoże:

NOPE. Bez zmian.

**Comment by krystian3w** [comment]
No to może `rewrite` jakieś do aktualizacji jak np. nowa kampania po Huwaei i stąd luka w AdGuard.

---

`-FwkqOxhmGz4XCSo7GGYbPhcJKjsYZhs-` to już się więc chyba rozpłynęło (plik pewnie ma nową nazwę), niby rodo teraz ma inny wygląd i dodatkowy pasek u dołu strony.

**Comment by AdamWr** [comment]
Ok, zaraz postaram się to naprawić (mam na myśli aplikację na Windowsa).
W przypadku rozszerzenia te reguły powinny to naprawiać - https://github.com/AdguardTeam/AdguardFilters/commit/9305ad9c5b202eee94e7f044df3b0c0fd45e6a4a#diff-48cd1634a8224e1bf6ce278856af9f2aR4311-R4315

>chyba popsute w AdGuard Annoyance

Ta reguła dotyczy tylko iOS, kontent blokera dla Androida, rozszerzenia Safari i Edge:
https://github.com/AdguardTeam/AdguardFilters/blob/ca2d5bfacfba631db3f0399b221fbc77638399d2/AnnoyancesFilter/sections/cookies_specific.txt#L2469-L2470

Jeśli jest taka konieczność, to mogę dodać wykluczenia dla blokerów, które nie obsługują reguł CSS.

**Comment by krystian3w** [comment]
Ja tam widziałem, że blokada pliku generuję jakąś czerwoną kropkę na "ikonie programu" że miał aktualizację.

![obraz](https://user-images.githubusercontent.com/35370833/62483049-14f4da80-b7b7-11e9-85dc-b33993e34200.png) |
--- |


tej kropki jak jest dopuszczony niezbędny CSS i JS nie ma w ogóle, ona powinna być tylko na awatarze.

![obraz](https://user-images.githubusercontent.com/35370833/62483167-584f4900-b7b7-11e9-8d62-bbdc4a48fc61.png) |
--- |

Jak dla mnie to trochę za dużo by dopisywać najbliższy CSS przywracający funkcje / usuwający dziwolągi.

**Comment by AdamWr** [comment]
Dodałem:
```
||dobreprogramy.pl/cdn/*assets/js/wpjslib-sgap.js$replace=/(display:\\s\*)none(\\s\*!important)/\$1\$2/,important
```
Prawdopodobnie konieczne będzie odświeżenie strony używając `Ctrl + F5`.

>Ja tam widziałem, że blokada pliku generuję jakąś czerwoną kropkę na "ikonie programu" że miał aktualizację.

Ok, dodałem `~www.dobreprogramy.pl` do tej reguły - `||wp.pl/*-FwkqOxhmGz4XCSo7GGYbPhcJKjsYZhs-$script`
Swoją drogą nie wiem jak to odtworzyć.
