### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#14348]
### Zrzut ekranu
![Screenshot_20190808_101539](https://user-images.githubusercontent.com/19818572/62686765-a20d7e80-b9c5-11e9-8bdb-e79f7d220d49.png)

### Link bezpośredni
`https://www.filmweb.pl/serial/Stranger+Things-2016-750359`

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Biały pasek przysłania część strony.

Te chyba będą do usunięcia:
```
filmweb.pl##^#mainSkyBanner-pl_PL
filmweb.pl###mainSkyBanner-pl_PL:style(position: absolute !important; left: -3000px !important;)
```
Przywróci to też info o rozdaniu Oskarów FIlmwebu :smiley:

**Comment by xxcriticxx** [comment]
duplicate of https://github.com/MajkiIT/polish-ads-filter/issues/14324

**Comment by hawkeye116477** [comment]
Ta, ale otworzyłem nowy, bo @MajkiIT ignoruje zamknięte.

**Comment by MajkiIT** [comment]
@hawkeye116477 Dziękuję. Ale tej reguły nie widzę 
`filmweb.pl###mainSkyBanner-pl_PL:style(position: absolute !important; left: -3000px !important;)`

**Comment by hawkeye116477** [comment]
Ah, ok, najwyraźniej coś mi się pomyliło, chodziło o `filmweb.pl##+js(remove-attr.js, style, #skyBanner)`

**Comment by xxcriticxx** [comment]
zdarza sie i ekspertom sie pomylic

**Comment by MajkiIT** [comment]
@hawkeye116477 Dziękuję

**Comment by hawkeye116477** [comment]
Trochę słabo z tym aktualizowaniem wersji, bo jak coś to nikt raczej nie patrzy na wersję suplementu, a i oddzielnie suplementu też raczej nie subskrybuje, więc powiedziałbym, że można tam wcale wersji nie wpisywać, za to przydałoby się jakby przy każdej aktualizacji suplementu, wersja głównej listy była podbijana :smile:

**Comment by krystian3w** [comment]
W sumie pytanie jak uBO sprawdza, AdGuard raczej wychwytuje do 4 godzin od modyfikacji swoim "botem".

**Comment by hawkeye116477** [comment]
@krystian3w Zależy jaka jest wartość expired, no i raczej patrzy tylko na jedną wartość expired.
Ale mi chodzi o ludzi, że jakby co, to patrzą na jedną wersję, no bo w uBO to jest jednak jakby 1 plik połączony.
