### ISSUE TITLE
pl-store.acer.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14344]
Social
![Zrzut ekranu z 2019-08-07 04-28-08](https://user-images.githubusercontent.com/36385327/62590178-cc7b1100-b8cb-11e9-8e96-b088719c45d8.png)

**Comment by hawkeye116477** [comment]
U mnie twierdzą, że przeglądam stronę z innego kraju, coś im się chyba popsuło wykrywanie lokalizacji.

**Comment by krystian3w** [comment]
A jak powie "no wort this"?

**Comment by hawkeye116477** [comment]
@krystian3w A niby dlaczego miałby powiedzieć, oczyszczanie sieci z Socializmu to przecież jego obowiązek :smile:

**Comment by krystian3w** [comment]
Jakoś na `gamefront.com` uznał, że trzeba wyciąć reklamę a wyciekające około 6 z 12 ikonek social olać, nawet nie odblokuje tych przypadkowo zablokowanych filtrem na ikonki AwesomeFont.

**Comment by krystian3w** [comment]
Nawet sądzę, że celowo wyłączył filtry `ABP Anti-CV` w swoim Adblock Plus skoro dalej widział reklamę po zablokowaniu jej tam od jakiś 3 dni.

**Comment by hawkeye116477** [comment]
@krystian3w Niespodzianka => https://github.com/easylist/easylist/commit/d614470e5bb1263ab7fda6ebd8b1df696b81fdfc

**Comment by krystian3w** [comment]
A działa, dodałem co innego... może wyciął RSS "blogowy".

**Comment by krystian3w** [comment]
I czemu ten "rytm" nie zgłoszony jako zbugowany?

**Comment by hawkeye116477** [comment]
@krystian3w Nie chciało mi się pisać sprawozdania :stuck_out_tongue:
