### ISSUE TITLE
bytom.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14345]
Cookies
![Zrzut ekranu z 2019-08-07 05-59-20](https://user-images.githubusercontent.com/36385327/62593824-8a0c0100-b8d8-11e9-8857-72cc3ead7961.png)

**Comment by hawkeye116477** [comment]
Strona padła.

**Comment by hawkeye116477** [comment]
Ta strona jest coś podejrzana, co jakieś parę minut pada...
