### ISSUE TITLE
lidl.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1434]
`http://www.lidl.pl/pl/index.htm`

@F4z lewa prawa strona da rade?

**Comment by F4z** [comment]
@xxcriticxx chodzi o to tło?
`http://www.lidl.pl/statics/lidl-pl/ds_img/layout/tapeta_tydzien_polski.jpg`
Jeśli tak, to ta reguła powinna to zablokować:
`||lidl.pl/statics/lidl-pl/ds_img/layout/tapeta_tydzien_polski.jpg$image`

**Comment by xxcriticxx** [comment]
dziala super thx
