### ISSUE TITLE
begio.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14342]
Napisy "Reklama"

**Comment by krystian3w** [comment]
I social w stopce: https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/c258b52670c7da9edbca23528242063beb744ff7

**Comment by krystian3w** [comment]
I niby prawe zobacz również lepiej w filtrach reklamowych a nie EI: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1688#issuecomment-518995335

`begio.pl###text-8`

Nie wiem czy odblokowanie Google tam nie zrobi wysupu reklam i wymogu blokowania kosmetycznie.

**Comment by krystian3w** [comment]
I niby prawe zobacz również lepiej w filtrach reklamowych a nie EI: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1688#issuecomment-518995335

`begio.pl###text-8`

---

Nie wiem czy odblokowanie Google tam nie zrobi wysupu reklam i wymogu blokowania kosmetycznie:

```
@@||googlesyndication.com^$domain=begio.pl|doubleclick.net|google.com|googletagservices.com
      @@||doubleclick.net^$domain=begio.pl|doubleclick.net|google.com|googletagservices.com
 @@||adservice.google.com^$domain=begio.pl|doubleclick.net|google.com|googletagservices.com

begio.pl#@#[id^="aswift_"]
begio.pl#@#.adsbygoogle
begio.pl##div[id^="aswift_"]:not([id^="aswift_2"])
begio.pl##ins[id^="aswift_"]:not([id^="aswift_0"])
begio.pl##center > .adsbygoogle
begio.pl###text-6
```

**Comment by krystian3w** [comment]
Myślę, że jednak bezpieczniej wyciąć sekcje, w pluginie 2 drugi to teraz reklama zewnętrzna.

**Comment by krystian3w** [comment]
Majki zamknie.
