### ISSUE TITLE
otube.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14347]
![Capture](https://user-images.githubusercontent.com/15007183/62654360-a2f2d180-b92d-11e9-8c85-9818e25b8e6e.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx zaktualizuj proszę filtry, bo ja tego nie widzę niestety.

**Comment by hawkeye116477** [comment]
@krystian3w Strona ewidentnie do prześwietlenia.

**Comment by hawkeye116477** [comment]
Strona jest zainfekowana jakby, nawet po aktualizacji listy próbuje przenieść do jakiejś szemranej strony.

**Comment by hawkeye116477** [comment]
Strona jest zainfekowana jakby, nawet po aktualizacji listy próbuje przenieść do jakiejś szemranej strony.
`otube.pl##+js(abort-current-inline-script.js, Math.random)`

@krystian3w Dla ciebie zadanie, prześwietlić ich dokładniej, nie wiem czy by całej strony nie dodać do KADa.

@xxcriticxx Na filmy to najlepiej iść do kina albo kupić Bluray w jakimś Empiku :smile:

**Comment by xxcriticxx** [comment]
@hawkeye116477 w nyc nie empiku

**Comment by xxcriticxx** [comment]
strona skacze do `faidoud.com` ale `stasy` dzisiaj nie mam

**Comment by hawkeye116477** [comment]
@xxcriticxx No to popatrz czy u ciebie takie są => `https://www.yelp.com/search?find_desc=Blu+Ray+Stores&find_loc=New+York%2C+NY` :smile:. Jeszcze z legalnych źródeł pewnie jest Netlifx, Amazon, HBO GO albo Chilli.

**Comment by xxcriticxx** [comment]
@hawkeye116477 thanks za off topic!

**Comment by krystian3w** [comment]
Nie za bardzo widzę, by naciągali. Pop-up to może tylko agresywna reklama?

**Comment by hawkeye116477** [comment]
@krystian3w Tzn. to z tymi fotkami nadal wyskakuje?

**Comment by krystian3w** [comment]
Tych z rogu nie mam, widać wyczyścili lub skrypt siadł.

**Comment by hawkeye116477** [comment]
@krystian3w Nie ma, bo Majk dodał odpowiednie reguły.

**Comment by hawkeye116477** [comment]
@krystian3w To co miał @xxcriticxx to też dzisiaj nie miałem, ale wyskakiwało coś wcześniej, że jakieś tam fotki mają, ale Majk dodał już na to odpowiednie reguły.

**Comment by krystian3w** [comment]
Mi wczoraj może z dwa razy pop-up stylizowany na Android 4 (jakieś randki?), ale też może wycięte jako reklama. Kliknięcie "nie" nic nie otwierało - niby lepiej nie klikać w ogóle :rofl:.

Potem nawet nie wskakiwało po wyłączeniu blokad i czyszczenia cookies (może zła domena czyszczona w przeglądark).

**Comment by hawkeye116477** [comment]
`Mi wczoraj może z dwa razy pop-up stylizowany na Android 4 (jakieś randki?), ale też może wycięte jako reklama.`
Nie wycięte, a czasem też chyba znowu jakieś przekierowania.
Może jednak lepiej dodać ich do KADa, to się skończy pajacowanie...

**Comment by MajkiIT** [comment]
@hawkeye116477 Dodałem już regex ... może na dłużej starczy
