### ISSUE TITLE
tvsztum.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14349]
blokada przewijania strony

**Comment by hawkeye116477** [comment]
Wygląda na to, że ktoś chyba zapomniał dodać regułę odblokowującą scroll w przypadku RODO, bo niby jest w suplemencie ale bez odblokowania scrolla.
Problem pewnie był tu => `https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/4ba7ba9bf4ffd5404a6395f5b43e23484965eaa3#diff-4e67f89aa5de6a619fc8a7287a4e441b`, literówkę ktoś zrobił, a ja usunąłem, no bo takiej domeny nie ma..

**Comment by krystian3w** [comment]
Musiało się zepsuć w ciągu ostatnich 9 miesięcy: https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/5c748c4d5a264f4e22c6ece05f7a890c3400159b

**Comment by hawkeye116477** [comment]
Aha, czyli to jednak @krystian3w łobuzuje :smiley:
