### ISSUE TITLE
centrumxp.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14353]
> Garść nowości w Windows 10 19H2. Aż dwie aktualizacje w Slow Ring

https://www.centrumxp.pl/Publikacja/Garsc-nowosci-w-Windows-10-19H2-Az-dwie-aktualizacje-w-Slow-Ring

reklama office widoczna u @seba2282

Podobne #13960

**Comment by hawkeye116477** [comment]
Pewnie to jednak zostanie, bo jest w ich sklepie.

**Comment by krystian3w** [comment]
@KonoromiHimaries

**Comment by seba2282** [comment]
Trochę czytam na centrum xp i dłuższy czas co artykuł widzę tą reklamę i dlatego zapytałem @krystian3w czy ktoś już ją widział i czemu nie jest naprawiona. 🙂

**Comment by krystian3w** [comment]
https://github.com/KonoromiHimaries/PolishSubFilters/commits/master najwyżej w EI dołączy do reklam aptekowych (je w sumie można sprawdzić czy dawno wycięte u Matiego).

**Comment by hawkeye116477** [comment]
Do EI odpada, takie małe sobie darujemy, dodajemy raczej jedynie jak jest tło albo się coś rusza.

**Comment by seba2282** [comment]
@hawkeye116477, to możesz dodać do odpowiednich filtrów, które uważasz za odpowiednie? 🙂

**Comment by hawkeye116477** [comment]
@seba2282 Ja się takimi elementami nie zajmuję, to do pana @KonoromiHimaries.

**Comment by seba2282** [comment]
@hawkeye116477, a myślałem, że dasz radę pomó. 🙂

**Comment by KonoromiHimaries** [comment]
> @seba2282 Ja się takimi elementami nie zajmuję, to do pana @KonoromiHimaries.

ja niby też, od tego jest lista easylist polish
https://github.com/easylistpolish/easylistpolish/issues

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Jak to, już wewnętrznych nie wycinasz?
EasyListPolish też nie wycinają wewnętrznych, w takim razie @seba2282 musi sam utworzyć listę :smile:

**Comment by KonoromiHimaries** [comment]
wewnętrzne, ale takie których nie ogarnia easylist polish

**Comment by seba2282** [comment]
@KonoromiHimaries, to Easypolish ich nie ogarnia.

**Comment by KonoromiHimaries** [comment]
@seba2282 dobrze, więc proszę o pr do głównej gałęzi listy
https://github.com/KonoromiHimaries/PolishSubFilters/blob/master/internal-filters/wewnetrzne.txt#L32

**Comment by seba2282** [comment]
@KonoromiHimaries, jeżeli bym się znał, jak stworzyć to, to bym ci dał, ale lepszy ze mnie tester gotowych reguł. 😂

**Comment by KonoromiHimaries** [comment]
@seba2282 najeżdżasz na element, klikasz prawym u myszki, zablokuj element, utwórz

**Comment by KonoromiHimaries** [comment]
ewentualnie możesz stworzyć swoją własną listę https://gist.github.com/
a jak będzie wartościowa, to ja ją mogę dołączyć do filtrów wewnętrznych

**Comment by krystian3w** [comment]
gist się nie nadaje na listy, lepsze repo.

**Comment by KonoromiHimaries** [comment]
@krystian3w nadaje się na jedną listę, tylko trzeba adres skrócić z https://cdn.statically.io/gist/KonoromiHimaries/text/raw/text/mylist.txt
na
https://cdn.statically.io/gist/KonoromiHimaries/text/raw/mylist.txt

**Comment by krystian3w** [comment]
U mnie raw po edycji ma inny "hash", tego chyba nawet CDN nie ogarnie by ciągnąć właściwy hash.

**Comment by KonoromiHimaries** [comment]
@krystian3w u mnie działa właściwie

**Comment by seba2282** [comment]
Sprawdzę chłopaki te zablokowanie elementu. To akurat umiem, bo to robiłem w UBO i AG.

**Comment by hawkeye116477** [comment]
Jak nowocześnie, zgłaszający jak ma problem to sam musi dodać odpowiednią regułę do listy, takie rzeczy tylko w Erze... W takim razie ten Riot tam chyba tylko do ozdoby/plotkowania :smiley:

**Comment by KonoromiHimaries** [comment]
@hawkeye116477 prowadzę taki notatniczek, gdzie zapisuje do przejrzenia wszystkie zgłoszenia.

**Comment by KonoromiHimaries** [comment]
@hawkeye116477 prowadzę taki notatniczek, gdzie zapisuje wszystkie zgłoszenia do przejrzenia.

**Comment by krystian3w** [comment]
@seba2282  to co tam ci się wyłapało jako sidebar?

`##section.sidebar-news-grid:nth-of-type(1)`  https://github.com/MajkiIT/polish-ads-filter/issues/14353#issuecomment-519895140

**Comment by seba2282** [comment]
Właśnie tą regułę uzyskałem.

**Comment by hawkeye116477** [comment]
@seba2282 Nieładnie, my to robimy za darmo, nie płacisz nam i mam rozumieć, że oczekujesz, że specjalnie dla ciebie utworzymy listę filtrów dla każdego elementu, który tobie się nie podoba? Sorry, ale nie jesteś szefem, więc nie możesz od nas żądać, że coś musimy zrobić, bo ty tak chcesz. Każdy ma swoje zadania i czas na to. Do piekarni też chodzisz i mówisz „a gdzie jest szynka", a potem obsmarowujesz ich za to, że nie mają szynki?
`https://forum.dobreprogramy.pl/t/gmail-ruski-spam-od-miesiecy/600652/27`

**Comment by seba2282** [comment]
@hawkeye116477, przecież już jest wszystko zrozumiałe. Wypowiedziałeś się pod wspomnianym wątkiem na DP. Więc w czym problem. Temat uznałem za zamknięty, ponieważ zrozumiałem twoją odpowiedź. Nie musiałeś jeszcze na GH. Jest wszystko ok. Choć irytowało trochę brak podstawowej reguły we filtrach polskich. Ale już wszystko jest w porządku.

**Comment by hawkeye116477** [comment]
@seba2282 Miałem spore wątpliwości, zabrzmiało trochę jak foch. Więc uznałem, że należy lepiej przetłumaczyć :smile:

**Comment by seba2282** [comment]
@hawkeye116477, powiedzmy był gorszy dzień + osobiste problemy. I fakt, za gwałtownie zareagowałem. Ale mi nie trzeba dużo tłumaczyć. 🙂
