### ISSUE TITLE
Oszczędzanie energii

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#14350]
Jakby, co to @MajkiIT może usunąć :cookie:, :+1: , RSS i EI z poszukiwania wygasłych domen. W końcu po co marnować energię, PFT i tak korzysta ze swoich ulepszonych skryptów (`https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/master/scripts/expired_domains.sh`, `https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/master/scripts/DSC.sh`) :smile:

**Comment by krystian3w** [comment]
`blogspot.co` jakoś przeszedł?

https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/231623f963d68428155baf1a2fe9b1eccbdfde76

**Comment by hawkeye116477** [comment]
@krystian3w Bo `blogspot.co` nie wygasł, nadal jest. Skrypt nie sprawdza np. `poczta.wp.pl`, tylko `wp.pl`, bo whois nie działa na subdomeny.

**Comment by krystian3w** [comment]
to i tak dziwne, że nigdzie tej `kamiry` (3 nieznane, a nie ma w pliku nieznane przez minimum 3 tygodnie?) nie zapisało ani `alkowska.com` (ktoś kupił i nie konfiguruje lub nie do WWW?).

**Comment by hawkeye116477** [comment]
@krystian3w Jeżeli chodzi o `alkowska.com`, to skrypt wyciąga dane z przed hasha, a że nie było tam hasha to nie wypluł tej domeny, zagadka rozwiązana :smile:

**Comment by krystian3w** [comment]
A kamry da się może na przyszłość wciągnąć bez podglądu co bash widział?

**Comment by hawkeye116477** [comment]
@krystian3w Zaraz dodam poprawkę, Trochę inaczej zrobimy, teraz będzie sprawdzał obydwie i jeżeli subdomena będzie leżała, a główna nie, to subdomena trafi do listy niewiadomych, a jeżeli obydwie będą offline, to wtedy wynik z whois, a jak nic nie zwróci, to kod z curla.

**Comment by hawkeye116477** [comment]
@MajkiIT W ramach oszczędności proponuję jeszcze poprawić skrypt, by aktualizował listy, tylko wtedy gdy jest taka potrzeba i jakby co, to VICHS od PolishFiltersTeam potrafi to robić :smile:

**Comment by xxcriticxx** [comment]
@hawkeye116477 może w końcu nauczysz bot zamykać wątki jak PR zrobicie?

dzienne PR tez bym się nie obraził

**Comment by hawkeye116477** [comment]
@xxcriticxx Raczej nierealne do wykonania. No chyba, że MS doda opcję, że napiszemy np 'fixes l:cookies` i wtedy zamknie wszystko z taką etykietą.

**Comment by xxcriticxx** [comment]
Zostawiam to dla ciebie  napewno coś wymyślisz

**Comment by hawkeye116477** [comment]
@xxcriticxx Może dałoby się zrobić, ale ja się nie znam na robieniu takich botów. Najlepiej, jakby Phil dodał to co mówię, albo też np `fixes #1544 - #1555`, przydałoby się, od razu szybciej by szło.
Także pisz komputerowy list do MS albo Tonego Starka :smiley:

**Comment by xxcriticxx** [comment]
Może lepiej do kapitan America albo do thora?

**Comment by hawkeye116477** [comment]
Oni się nie znają, tylko geniusze takiego pokroju jak Stark się znają. Ale czekaj, przecież on nie żyje. No to może Peter Parker :smile:?

**Comment by hawkeye116477** [comment]
@xxcriticxx Kapitan Ameryka cofnął się w czasie (Avengers Endgame, sorry za spoiler), a Thor to menel :smiley: Tak więc, wracamy do Starka, ale on już nie żyje (sorry, za kolejny spoiler). Więc pozostaje ci chyba jeszcze ewentualnie Peter Parker albo Microsoft :smile:

**Comment by xxcriticxx** [comment]
@hawkeye116477 done

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale miał być spoiler :smile:

**Comment by xxcriticxx** [comment]
@hawkeye116477 jest

**Comment by hawkeye116477** [comment]
Raczej jest mój nick zamiast słowa **spoiler** :stuck_out_tongue:

**Comment by xxcriticxx** [comment]
@hawkeye116477 close enough

**Comment by hawkeye116477** [comment]
@MajkiIT Co się nie odzywasz, nie chcesz by pro eko :smile?

**Comment by MajkiIT** [comment]
@hawkeye116477 Nie odzywałem się, bo miałem trochę zamieszania rodzinnego. 

ad 1 to data wygenerowania plików 
ad 2 dobrze usunę jak nie korzystacie z tego 

a tak apropo to jest EKO, bo prąd idzie z kolektorów słonecznych w obecnej chwili. :D

**Comment by krystian3w** [comment]
Nawet zimą jak świeci "5 godzin" :clock5: i jak chronisz je przed gradem wielkości piłek do tenisa :tennis: / jabłek :apple:.

**Comment by hawkeye116477** [comment]
`ad 1 to data wygenerowania plików`
No tak, chodzi o to, że mógłby podbijać tą datę, tylko jeżeli zmieni się zawartość listy, bo często widzę, że brak zmian, a data jest podbijana, a jak dla mnie trochę bez sensu to podbijać, jak nie ma nowych zmian. VICHS potrafi pobierać listy i zamieniać je na hosts i podbijać wersję tylko, gdy się coś zmieniło i która swoją drogą też może być w formacie daty wygenerowania (parę formatów jest do wyboru, w zasadzie wszystkie mają w sobie datę, w niektórych jest też liczba commitów).

**Comment by xxcriticxx** [comment]
@hawkeye116477 VICHS co to za monster?

**Comment by krystian3w** [comment]
i "tę" "datę".

**Comment by hawkeye116477** [comment]
@xxcriticxx Version Checksum Include Sort - taki skrypt, dzieło inżynierów z Polish Filters Team :smile: https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/master/scripts/VICHS.sh

**Comment by MajkiIT** [comment]
@krystian3w obecnie od 1,5 ms mam 6 paneli fotowoltaicznych i Heat pipe aby podgrzewać wodę. Na razie nie miałem takiej sytuacji i obecnie sięgając pamięcią to nie pamiętam kiedy tak grad był. Planuję to ubezpieczyć, ale muszę pozyskać oferty. Obecnie większość energii oddaję do sieci niż jej pobieram ... zrobiłem mechanizm, że po wyjściu wszystkich z domu po 20 min wyłączają się wszystkie zbędne odbiorniki. Obecnie cały stary sprzęt serwerowy sprzedałem, bo był za kosztowny pod względem użycia prądu. Teraz przerzuciłem się na Raspberry PI 3+ i 4 . Dodatkowo router, switche i Access Pointy i pozostałe elementy pobierają ok max 120 W. Szczyt jest w weekend jak jest cała rodzina i jest gotowanie, TV itp. 

@hawkeye116477 to wynika z problemu maili.... z pytanie czemu listy przestały się aktualizować.  Można dodać datę sprawdzenia listy .... poczytam o tym co proponujesz.

**Comment by hawkeye116477** [comment]
@MajkiIT Taka mała sztuczka => `https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/master/scripts/VICHS.sh#L456`. Robimy kopię starego pliku, usuwamy z niego komentarze, potem przetwarzamy nowy plik, dodajemy nowe reguły i robimy kopię odświeżonej listy, a na kopii usuwamy komentarze. Potem sprawdzamy md5 starej i nowej kopii, jak jest taka sama suma, to data nie jest podbijana.

**Comment by xxcriticxx** [comment]
@MajkiIT prosimy o zdjecie tej twojej sieci elektrycznej

**Comment by hawkeye116477** [comment]
Nadal widzę  :cookie:, :+1: , RSS i EI w `https://github.com/MajkiIT/polish-ads-filter/tree/master/dead-domains`, a my tym czasem zaaktualizowaliśmy nasz eko skrypt (https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/master/scripts/ECODFF.sh) :smiley:

**Comment by hawkeye116477** [comment]
W ramach oszczędności może `eglobalcentral.pl` do usunięcia z listy reklamowej, bo kiedyś to chyba był ok sklep, ale teraz to już 6 osób zrobili w konia => `https://www.legalniewsieci.pl/aktualnosci/podejrzane-sklepy-internetowe`.
