### ISSUE TITLE
http://shinden.pl/

### ISSUE THREAD

**Issue by azet12** [MajkiIT/polish-ads-filter#1435]
przez pewien czas otrzymuję w zgłoszeniach na stronie kad o tej stronie, gdzie występują bardzo nieciekawe reklamy, a szczególnie skrypty
przykłady stron: `ibqmccuuhjqc.com, jwfdyujffrzt.com, hnoajsaivjsg.com, srppykbedhqp.com`
staram się to blokować, ale ciągle powstają nowe

wiadomo, że pochodzą z adresów ip poniżej i mają coś wspólnego z popads
https://virustotal.com/pl/ip-address/216.21.13.14/information/ 
https://virustotal.com/pl/ip-address/216.21.13.15/information/ 

co o tym sądzicie?

**Comment by xxcriticxx** [comment]
widzialem ten temat na easylist forum

**Comment by xxcriticxx** [comment]
@azet12 more info tutaj

`https://forums.lanik.us/viewtopic.php?f=62&t=32538&p=107131&hilit=popads#p107131`

**Comment by azet12** [comment]
ok, dzięki

**Comment by xxcriticxx** [comment]
@azet 12 otworzylem nowy temat

https://forums.lanik.us/viewtopic.php?f=62&t=33913

**Comment by xxcriticxx** [comment]
@MajkiIT dodasz do listy

`|http://$script,third-party,domain=shinden.pl`
`|https://$script,third-party,domain=shinden.pl`
`@@||ajax.googleapis.com/ajax/libs/$script,domain=shinden.pl`
`@@||cdnjs.cloudflare.com/ajax/libs/$script,domain=shinden.pl`

**Comment by MajkiIT** [comment]
@xxcriticxx Ok
