### ISSUE TITLE
bosch.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14365]
Zdefiniuj swoje ustawienia prywatności
Marketing
W celu zapewnienia dostępu do naszej oferty strona zawiera pliki cookie, które są wymagane do jej prawidłowego działania. Pliki cookie i mechanizmy śledzenia, które nie są wymagane do jej prawidłowego działania, ale umożliwiają nam zapewnienie łatwiejszej obsługi oraz prezentację ofert indywidualnych (marketingowe pliki cookie i mechanizmy śledzenia) są przez nas stosowane wyłącznie po udzieleniu Twojej zgody: więcej
Cofnięcie zgody
W sekcji ustawienia prywatności możesz w dowolnej chwili wycofać swoją zgodę ze skutkiem na przyszłość. Więcej informacji można znaleźć w sekcji polityka ochrony danych osobowych / informacje korporacyjne.

**Comment by krystian3w** [comment]
@kiboke yo block generic this?

```
||btm.bosch.com/rb/cookie/bosch-privacy-settings-*.min.js$script,domain=www.bosch.pl
```

**Comment by kiboke** [comment]
> @kiboke you block generic this?

Yes, with `/bosch-privacy-settings-`
Bosch has many domains, the same rule applies to all of them.
