### ISSUE TITLE
centrumkomputerowe.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14379]
RODO i 2xfb

**Comment by krystian3w** [comment]
@hawkeye116477  to by trzeba w dodatku, 10 sekund zmuszają do czytania i przekierowują na:

`http://centrumkomputerowe.eu/home.html`

**Comment by krystian3w** [comment]
Sociale jak dla mnie nie do ruszenia. Mogę się pomęczyć z blokadą klikalności jak są klikalne.

----

 @gwarser uBO obsługuje `:XPath` z podmianą tekstów?

https://github.com/AdguardTeam/ExtendedCss/issues/86 / https://github.com/AdguardTeam/Scriptlets/issues/29

**Comment by hawkeye116477** [comment]
@krystian3w To co się czaisz, dodawaj :stuck_out_tongue:

**Comment by gwarser** [comment]
Ten napis `ads` można wskazać za pomocą xpath, ale nie ma jak potem go ukryć, bo nie ma do czego dodać `display:none`. No chyba, ze czegoś nie rozumiem.

**Comment by krystian3w** [comment]
Ja wykopałem takie coś: https://developer.ibm.com/answers/questions/323189/xpath-to-change-the-value-of-text-node/

ale ja najwyżej umiem się cofać od unikalnego elementu w dół lub wymusić by niższy element by np. divem z atrybutem "`[style]`".

**Comment by hawkeye116477** [comment]
Sociale nie są klikalne i są wbudowane w obrazek razem z resztą, więc @blocker999 będzie musiał jakoś przeżyć :smile:

**Comment by gwarser** [comment]
@krystian3w pobaw się tym: `file-up.org##.text-center.page-wrap > div:nth-of-type(2)::first-line:style(color:white!important)`

**Comment by krystian3w** [comment]
A możesz to testowo dodać do `filters.txt`?

**Comment by krystian3w** [comment]
> Sociale nie są klikalne

były:

https://github.com/MajkiIT/polish-ads-filter/blob/de47f04be4ae00fd093dbe36e695bbbba35e7072/adblock_social_filters/adblock_social_list.txt#L1231

**Comment by hawkeye116477** [comment]
@krystian3w No tak, ale stan obecny się liczy :smile:
