### ISSUE TITLE
bosch-easycontrol.com/pl/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14373]

**Comment by krystian3w** [comment]
@kiboke you accept this or remove with CSS (unlock scrolling)?

**Comment by krystian3w** [comment]
@hawkeye116477 używać `[lang="pl"]` / `:lang(pl)` dla ograniczenia by nie wycinało na innych wersjach językowych.

https://caniuse.com/#search=%3Alang

**Comment by hawkeye116477** [comment]
@krystian3w Nie, bo pewnie będzie wolniej.

**Comment by kiboke** [comment]
> @kiboke you accept this or remove with CSS (unlock scrolling)?

I auto-accept it.
