### ISSUE TITLE
junkers.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14370]
blad from cookies

**Comment by krystian3w** [comment]
@kiboke:

`#cookielaw:not(body):not(html)`

no cut background.

**Comment by krystian3w** [comment]
@hawkeye116477  masz ten swój acer widoczny w pliku Fanboy Social, niby siadł im Bot i np. dropboxa nie dodał.

**Comment by hawkeye116477** [comment]
@krystian3w Nie mam.

**Comment by krystian3w** [comment]
No dobra, tak to jest jak oni mają około 3 mirrory z różnym przygotowaniem na obciążenia.

**Comment by hawkeye116477** [comment]
Coś ten fanboy sknocił. W jednym checksum jest, w drugim nie ma.

**Comment by hawkeye116477** [comment]
@krystian3w Jeszcze zostaje margines, najlepiej chyba będzie dodać `:not(.fade)`, bo wtedy często też i scrolla blokują. Tutaj o dziwo niby jest blokada scrolla, ale jednak w html coś tam ponownie go przywraca.

**Comment by krystian3w** [comment]
https://easylist-downloads.adblockplus.org/fanboy-social.txt - tu też nie ma socialu...

**Comment by hawkeye116477** [comment]
@krystian3w No bo już poszła aktualizacja, wcześniej była tam wersja z godziny 14 i ta reguła tam była.

**Comment by krystian3w** [comment]
@hawkeye116477  a da się nasze generyki zaktualizować jak np. Kiboke wycofał lub rozbudował `not`?

**Comment by hawkeye116477** [comment]
@krystian3w Ręcznie trzeba.

**Comment by krystian3w** [comment]
@Kiboke added `:not(.modal)` better as :(fade)?

**Comment by hawkeye116477** [comment]
My tam na razie zostawiamy tak, jak będzie problem, to wtedy zmienimy.
