### ISSUE TITLE
bosch-industrial.com/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14374]

**Comment by krystian3w** [comment]
podobnie jak z #14370, sieciowo strona nie chce się nabrać.

**Comment by hawkeye116477** [comment]
Mnie przekierowują na brytyjską stronę. Chyba nie chcą, by Polacy im zawracali głowę.

**Comment by krystian3w** [comment]
Mnie nie, może padł Manjaro lub nie dobrze go w ustawieniach spolonizowałeś?

**Comment by krystian3w** [comment]
Niby też działa html filtering:

`com##^#cookielaw`

**Comment by hawkeye116477** [comment]
@krystian3w To raczej nie zależy od systemu czy tam przeglądarki, oni po IP rozpoznają. Przez Proxy z Holandii czy Niemiec niby nie ma przekierowania i to jest dziwne.
Na pewno masz polskie IP? Sprawdź na `https://www.iplocation.net`.

**Comment by krystian3w** [comment]
`Polska - Dolnośląskie - Wrocław`, ale internet od Plusa i to na różne polskie miasta pokazuje, najczęściej w okolicy Koła lub Warszawy.

**Comment by hawkeye116477** [comment]
Ok, dziwne, no to w takim razie może patrzą na województwa albo miasta czy coś. Ale dziwne też, że za granicą nie robią przekierowania.

**Comment by krystian3w** [comment]
I może jeszcze nie masz blokad "America Only 🇺🇸"?

**Comment by hawkeye116477** [comment]
@krystian3w A jak to sprawdzić, na co mam wejść :smile:?

**Comment by krystian3w** [comment]
Nie wiem może na jakieś zgłoszenia cookies @xxcriticxx  jak ja pisałem, że są z blokadą regionalną.

**Comment by hawkeye116477** [comment]
@krystian3w No to https://github.com/MajkiIT/polish-ads-filter/issues/10176 działa

**Comment by krystian3w** [comment]
Mi już też - pewnie zlikwidowali blokady.
