### ISSUE TITLE
istotne.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14397]
tło po info o blokadzie reklam

**Comment by xxcriticxx** [comment]
blad z cookies blokuje website scrolling 

cc @krystian3w / @hawkeye116477 

test link:
https://istotne.pl/jelenia-gora

**Comment by hawkeye116477** [comment]
@xxcriticxx To nie ciastka, tylko @olegwukr dodał `istotne.pl##.modal-dialog` i to bloknęło scrolla.

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale to nieprawdziwe reklamy :smile:
@MajkiIT Kiedy wraca ten twój kolega z wakacji?

**Comment by MajkiIT** [comment]
@hawkeye116477 
Już wrócił :D
https://github.com/olegwukr/polish-privacy-filters/commit/809ac7b5c6b7461fc29d075c4fe2b128294807b0#diff-6de60f294b8bd23c752f8fcbece875b1
