### ISSUE TITLE
laptopmarket.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14391]
sociale ( na dole )

**Comment by krystian3w** [comment]
u mnie nie wyciekają, z 5 razy odświeżyć stronę, może też ci wytnie w końcu filtr polskie generyki:

`pl##.fa-youtube`
`pl##.fa-instagram`
`pl##.fa-facebook`

opcjonalnie do filtrów wlanych: `laptopmarket.pl##.fx-socials`
