### ISSUE TITLE
http://mmorpg.org.pl/

### ISSUE THREAD

**Issue by Ravko** [MajkiIT/polish-ads-filter#1443]
pojawia się komunikat o używaniu addblocka w postaci div id=random(number)>  /div>
blokując komunikat raz, po chwili dostajemy nowy o nowym ID-ku

Addblock niby nie jest tam niezbędny, ale w prawym górnym rogu strona odtwarza automatycznie filmiki, przez co gdy otworzymy kilka artykułów w wielu tabach nasze łącze się zapycha ;/

**Comment by xxcriticxx** [comment]
@Ravko zamontuj reeka script

**Comment by Ravko** [comment]
Zamontowałem i komunikat raz się pojawia raz nie. mniej więcej co trzecie wejście dostaje bez komunikatu.

**Comment by xxcriticxx** [comment]
@Ravko you got it
