### ISSUE TITLE
pl.msi.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14456]
![Zrzut ekranu z 2019-08-14 16-28-30](https://user-images.githubusercontent.com/36385327/63029299-954ec600-beb0-11e9-9f51-d04f917f40fc.png)

**Comment by hawkeye116477** [comment]
@xMaap Ale to już jest na liście.

**Comment by xMaap** [comment]
@hawkeye116477 Robiłem i dalej wyskakuje.

**Comment by hawkeye116477** [comment]
@xMaap No to może musisz zrobić reset ustawień uBO do fabrycznych. Bo naprawdę ja tego nie widzę :smile:. Więc albo to u ciebie coś nie tak z uBO albo może któraś lista ci odblokowuje to (ale nie ma reguły generycznej, więc wątpię) albo komputer do zamiany na nowszy model.

**Comment by xMaap** [comment]
W innych przeglądarkach działa (Chrome i Firefox) tylko w Brave nie.

**Comment by krystian3w** [comment]
Brave blocker czy uBO osobny?

**Comment by krystian3w** [comment]
Może blokada sieciowo zadziała?

**Comment by hawkeye116477** [comment]
@krystian3w Moim zdaniem nie ma co zgadywać :stuck_out_tongue:

**Comment by xMaap** [comment]
> lub zrobić reset do ustawień fabrycznych.

I pomogło
