### ISSUE TITLE
plonskwsieci.pl/pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14457]
Reklama na cały ekran
![Zrzut ekranu z 2019-08-14 16-31-22](https://user-images.githubusercontent.com/36385327/63029519-02625b80-beb1-11e9-9018-7acdb00f1100.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 @krystian3w macie to ?

**Comment by hawkeye116477** [comment]
@MajkiIT Nie ma :droplet: na :desert:

**Comment by MajkiIT** [comment]
@hawkeye116477 Dziękuję

**Comment by hawkeye116477** [comment]
Jeszcze przycisk przysłania artykuł.
`https://plonskwsieci.pl/pl/550_na_luzie/4217_dwa_ujecia_naszej_plockiej_szymon_kirczuk_na_weekend.html`
![Screenshot_20190817_150308](https://user-images.githubusercontent.com/19818572/63212129-33849b00-c100-11e9-9e8f-058354010d47.png)
Najwyraźniej jest tak, bo tam była reklama i wszystko się przesunęło.
