### ISSUE TITLE
weszlo.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#14463]
sociale u góry i na dole

**Comment by krystian3w** [comment]
Nie mam, może pr z filtrami?

@hawkeye116477 czy generichide bogachenko obsługujemy?

**Comment by krystian3w** [comment]
Jak nie rozważamy naprawy bugów jego listą to proszę sobie testować:

```
*$generichide,domain=weszlo.com,important
```

**Comment by hawkeye116477** [comment]
@krystian3w Ale tam nie ma komunikatu, nawet z wyłączoną listą antyadblockową.

**Comment by krystian3w** [comment]
Ale w artykułach nie masz `Adquesto` po dezaktywacji skryptu.

Mogę nawet podlinkować zgłoszenie AdGuard kiedy bogachenko dodał na to `generichide` a AdGuard je aktywowała dla iOS i Content Blockera.

**Comment by hawkeye116477** [comment]
@krystian3w No właśnie nie ma.

**Comment by xxcriticxx** [comment]
musze sprobowac tego adguard na ios

**Comment by hawkeye116477** [comment]
@xxcriticxx Na iOS jest słaby, działa jak każdy inny ze względu na ograniczenia Apple.
@krystian3w Chyba skończyli zabawę.

**Comment by krystian3w** [comment]
@bogachenko consider turning off generichide.

**Comment by hawkeye116477** [comment]
W kodzie niby coś tam nadal jest, ale mi się nie aktywowało.

**Comment by krystian3w** [comment]
No to trzeba przemyśleć czy każdy wyciek sprawdzać czy robi bogachenko i co do niego zgłaszać by sobie ogarniał?

**Comment by hawkeye116477** [comment]
No nie wiem, jego lista nie jest domyślna nigdzie, jak coś to chyba raczej patrzymy tylko na Adblock Warning Removal i Nano Defendera. No i nie wiem czy te generchide akurat na tamto działało, bo jednak nikt z polskiego teamu nie dodał takiej reguły, a przecież chcieli wspierać ABP.

**Comment by krystian3w** [comment]
Naprawione, już generyki fanboya powinny być aktywne.
