### ISSUE TITLE
muza.com.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#14479]
https://muza.com.pl/audiobooki/2169-pochlaniacz-audiobook-9788377589083.html

**Comment by xxcriticxx** [comment]
@MajkiIT to jest RODO na 3/4 strony :)

**Comment by krystian3w** [comment]
nie wiem czy czasem nie do akceptacji w dodatku, nawigacja ma dziwną kreskę czerwoną na headerze:

![obraz](https://user-images.githubusercontent.com/35370833/63214223-b9f7a780-c115-11e9-8c87-d55e5972d20e.png)

**Comment by krystian3w** [comment]
Niby im teraz strona padła:

> ### Przekroczono limit czasu połączenia
> 
> Serwer muza.com.pl zbyt długo nie odpowiada.

**Comment by hawkeye116477** [comment]
@krystian3w Ta kreska to taka ozdoba najwyraźniej, bo nawet jest po akceptacji :smile:

**Comment by krystian3w** [comment]
A da się tam html filteringi czy lepiej nie - samo znika po 2 wizycie.

**Comment by hawkeye116477** [comment]
@krystian3w Nie wiem, jak chcesz próbuj, ja nie odczuwam spowolnień.

Można też niby css przyblokować, wtedy skraca się liczba reguł
```
||muza.com.pl/modules/rodoinfo$css
muza.com.pl##.remodal-wrapper
muza.com.pl##body:style(padding-right: 0 !important;)
```
Teoretycznie wtedy też można dodać dla tych z ABP, o ile im margines nie będzie wadził.

**Comment by krystian3w** [comment]
Nie wadzi, to tylko "17px" przy pierwszym otwarciu, ale może wyjść z tego drugi #14471.

**Comment by hawkeye116477** [comment]
@krystian3w Nie patrz tak daleko w przyszłość, równie dobrze mogliby zmienić nazwy tych klas. Będzie problem, to się poprawi.

**Comment by krystian3w** [comment]
@hawkeye116477 może testowo blokujemy plik JS, nie wygląda by zrobili z pliku CDN na skrypty.

A kreska z sociala się robi, brzydki fanboy sieciówkami powycinał z nagłówka i się rozjechało.

**Comment by hawkeye116477** [comment]
@krystian3w Ok, to testuj.

**Comment by hawkeye116477** [comment]
@krystian3w Jak zablokujesz, to im główny skrypt się krzaczy i wtedy nie dodają ciastka „visits".

**Comment by krystian3w** [comment]
Ale koszyk wtedy działa, nie trzeba też CSS dla uBO, nie robią się klasy "Remodal-is-blocked".

**Comment by krystian3w** [comment]
Jedynie inne remodale z oszczędności by znikały - na to by pomogło tylko doklejenie `:has(cookies)`

**Comment by hawkeye116477** [comment]
Ah, to chyba będzie jednak zbędne:
```
	if ( jQuery.cookie('visits') > 1 ) {
		var inst = $('[data-remodal-id=modalav]').remodal();
		inst.close();
	} else {
		inst.open();
	}
```
Czyli **visits** jest po to, by po kolejnych wejściach pop-up się nie pokazywał.

**Comment by krystian3w** [comment]
Tak.

**Comment by hawkeye116477** [comment]
`A kreska z sociala się robi, brzydki fanboy sieciówkami powycinał z nagłówka i się rozjechało.`
Z tym to nie takie proste, żeby się nie rozłaziło, to chyba ci co mają ABP, musieli by przeżyć z tymi socialami.
A dla uBO i AG => `muza.com.pl###header:style(padding-top: 30px !important;)`
