### ISSUE TITLE
plonskwsieci.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#14478]
### Zrzut ekranu
![Screenshot_20190817_150308](https://user-images.githubusercontent.com/19818572/63212129-33849b00-c100-11e9-9e8f-058354010d47.png)

### Link bezpośredni
`https://plonskwsieci.pl/pl/550_na_luzie/4217_dwa_ujecia_naszej_plockiej_szymon_kirczuk_na_weekend.html`

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
 Przycisk przysłania tytuł artykułu.
Najwyraźniej jest tak, bo tam była reklama z marginesem i wszystko się przesunęło.

Proponowana poprawka:
```
plonskwsieci.pl#@#.a-d-v-i
plonskwsieci.pl##.a-d-v-i:not(.box-margin)
plonskwsieci.pl##.a-d-v-i.box-margin > *
```

**Comment by MajkiIT** [comment]
@hawkeye116477 Dziękuje
