### ISSUE TITLE
oktawave.com/pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14471]
Nie działa przewijanie strony.

**Comment by hawkeye116477** [comment]
@krystian3w Nieładnie => https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/0c18abc2a74ab16c9574d964ab6aa35f903d2914 :stuck_out_tongue:

**Comment by krystian3w** [comment]
To napisz bota, co sam będzie sprawdzał czy dodali blokowanie przewijania, wtedy pewnie działało.

**Comment by hawkeye116477** [comment]
Ah, to oni dodali, myślałem, że zapomniałeś po prostu odblokować przewijanie.

**Comment by hawkeye116477** [comment]
@xxcriticxx To też możesz zamknąć.
