### ISSUE TITLE
lagardere-tr.pl/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14485]

**Comment by krystian3w** [comment]
@kiboke:


`lagardere-tr.pl###tarteaucitronRoot > #tarteaucitronAlertBig.tarteaucitronAlertBigBottom`

**Comment by kiboke** [comment]
I already deal with it by blocking `/tarteaucitron/tarteaucitron.js` script - many websites have it.
