### ISSUE TITLE
mojewypiekiinietylko.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14490]

**Comment by krystian3w** [comment]
@hawkeye116477  może katapulta dla `com` i `pl`?

**Comment by xxcriticxx** [comment]
sure

**Comment by krystian3w** [comment]
niby zniknie aż 21 domen z filtra wtedy `beskidzkie.com,brainsociety.com,comel-it.com,dom1n.com,fastwhitecat.com,girlswhowp.com,hdtvpolska.com,indianpoland.com,konstantinkanin.com,mecze.com,mojewypiekiinietylko.com,naszawyspa.com,olgasmile.com,polacywewloszech.com,tb4hr.com,telewizja-cyfrowa.com,trenerangielskiego.com,tsintegracje.com,yato.com,zorganizowana.com,moje-przepisy.com###catapult-cookie-bar` i niby u Kiboke brak jakiś bugów, że wyłącza je na jakiś domenach (akceptowanych skryptem nie za bardzo da się wyszukać).

**Comment by hawkeye116477** [comment]
Można też po prostu zacząć wymagać I don't care about cookies :smile:

**Comment by xxcriticxx** [comment]
ja lubie i dont care about @hawkeye116477 app

**Comment by krystian3w** [comment]
Może trochę winne w tym jest, to że on zrobił sobie płatny dodatek blokujący wszystko irytujące za roczną licencję (~9 €)?

**Comment by hawkeye116477** [comment]
Jest I don't care about cookies z licencją GPL3, to powinno być repozytorium raczej.
