### ISSUE TITLE
mytastepol.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14491]

**Comment by xxcriticxx** [comment]
jaka jest roznica jak sie oddziela dwa domeny `,` albo `|` ?

**Comment by krystian3w** [comment]
Tak.

kosmetyczne przecinkami, sieciowe "ścianką" (pipe?).

Jak pomylisz/dasz za dużo obok siebie, to filtr nie zadziała tak jak chcesz (jak nic nie zrobi to chwała Bogu).

**Comment by hawkeye116477** [comment]
`sieciowe "ścianką" (pipe?)`
Tak, to jest pipe, a po polsku to pionowa kreska :smile:

**Comment by xxcriticxx** [comment]
ok roger
