### ISSUE TITLE
Tesco

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14497]
https://businessinsider.com.pl/wiadomosci/glovo-kupuje-pizzaportal-od-amrestu/kz71h73

**Comment by hawkeye116477** [comment]
A lista Tesco do zamknięcia się powiększa, a jacyś tam przyjaciele z Niemiec kupią 5 hipermarketów Tesco => `http://www.portalspozywczy.pl/handel/wiadomosci/4-friends-investment-kupuje-sklepy-tesco-w-polsce,174689.html`.

**Comment by krystian3w** [comment]
Tesco niby zmieni się w coś wielkości 2 żabek jako lokal.

**Comment by hawkeye116477** [comment]
No niektóre hipermarkety mają się zmniejszyć, bo „duże markety się nie sprawdzają" albo raczej drogie ceny :smile:.

**Comment by krystian3w** [comment]
No dostawy do domu podrożały, teraz trudno by nie było taniej jak 15 złotych.

**Comment by krystian3w** [comment]
Ciekawe czy Carrefour wycofa darmowy dowóz do domu jak będzie przekraczać ~ 180 złotych lub kod rabatowy na to przy pierwszych zakupach online dezaktywują.

**Comment by hawkeye116477** [comment]
`No dostawy do domu podrożały`
W zasadzie głównie miałem na myśli produkty, Biedronka i reszta sklepów ma taniej nawet bez promocji.

**Comment by MajkiIT** [comment]
@krystian3w a Frisco ?

**Comment by krystian3w** [comment]
`##div[class="mini-notification _cookie BL"]`?

**Comment by krystian3w** [comment]
A do mnie tylko DPD wysyłają, nic szklanego i nic mrożonego.

**Comment by krystian3w** [comment]
A lipa jednak Tesco znika i będzie więcej Netto:

https://www.wirtualnemedia.pl/artykul/siec-supermarketow-tesco-wycofuje-sie-z-polski
https://www.dlahandlu.pl/detal-hurt/wiadomosci/netto-przejmuje-tesco-polska,88797.html
https://www.money.pl/gospodarka/netto-przejmuje-tesco-polska-6522724721813121a.html

**Comment by hawkeye116477** [comment]
> Tesco znika

W moim mieście już od paru miesięcy nie ma.

> będzie więcej Netto

No nie wszędzie, gdzieniegdzie porobili Kauflandy i Leroy Merlin, a możliwe, że gdzieś jeszcze pewnie Biedronka się wprowadzi.
