### ISSUE TITLE
wp.pl/o2.pl (AdblockDetected)

### ISSUE THREAD

**Issue by mhajder** [MajkiIT/polish-ads-filter#14504]
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Przejść do jakiegoś artykułu.

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome (chyba najnowsza, bo nie prosi o aktualizacje)

**Rozszerzenia i skrypty:**
uBlock

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
AdblockDetected

**Comment by hawkeye116477** [comment]
Duplicate of https://github.com/MajkiIT/polish-ads-filter/issues/13818

**Comment by hawkeye116477** [comment]
Najlepsza reguła => `0.0.0.0 wp.pl`, następnie polecam poszukać jakiejś lepszej witryny, może onet?

**Comment by mhajder** [comment]
@hawkeye116477 A co myślisz na temat AdGuarda? On by to blokował?

**Comment by hawkeye116477** [comment]
@mhajder Oni nic z tym nie zrobili na razie.

**Comment by krystian3w** [comment]
Naprawione MajkiIT wyłączył skrypt zamykający resztki po reklamach i odinstaluj skrypt "`polish_ads_wp.user.js`".

**Comment by krystian3w** [comment]
AdGuard pewnie zmodyfikuje skrypt boodies i zniknie komunikat.

**Comment by mhajder** [comment]
@krystian3w Nie mam zainstalowanego żadnego skryptu js. Czysty uBlock z filtrami.

**Comment by krystian3w** [comment]
to nie masz dzisiejszej aktualizacji: https://github.com/MajkiIT/polish-ads-filter/commit/e04a8e71899a2ae6b9ff1ef38202a3fe681c04ac

**Comment by krystian3w** [comment]
A i μBlock 0.9.5 wymienić na prawdziwy uBlock Origin 1.21+.

**Comment by mhajder** [comment]
Posiadam najnowsze wersje list i oczywiście miałem na myśli uBlock Origin 1.21.6.

**Comment by hawkeye116477** [comment]
No i tu jest problem, nikt na to nie patrzy => `https://github.com/MajkiIT/polish-ads-filter/commit/e04a8e71899a2ae6b9ff1ef38202a3fe681c04ac`, wersja powinna być podbita w głównej liście @MajkiIt.

**Comment by krystian3w** [comment]
@hawkeye116477 ale co mu wciskasz wycinanie newsletterów z kolumn, nie widzę by miał na to subskrypcje - lubi takie małe.

**Comment by mhajder** [comment]
@hawkeye116477 Dzięki, lecz nie chce blokować wszystkiego.

**Comment by krystian3w** [comment]
To tak jak myślałem, wywal: `    "https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt",`

newslettery w kolumnach i stopkach się odblokują, bo tego nie masz jako suplement.

---

Jedynie marnujesz nam transfer mają prawie każdy suplement i główną i osobno cookies (uBO nie lubi tylko plików 40 MB jako filtry, nawet jako plik z dysku).

**Comment by mhajder** [comment]
A to w takim razie wywalam te pojedyncze.
