### ISSUE TITLE
turystyka.wp.pl

### ISSUE THREAD

**Issue by salionPL** [MajkiIT/polish-ads-filter#14507]
**Adres strony:** https://turystyka.wp.pl/ugasmyplucaswiata-wojciech-cejrowski-o-pozarach-w-amazonii-6417008617936513a

### Dodatkowo nie działa tryb zaznaczania elementów w ublocku.

**Moja konfiguracja:**

Windows 10 [64bit]
Firefox 68.0.2 [64bit]
uBlock Origin 1.21.2

**Moje listy filtrów:**
<details>

![filtry](https://user-images.githubusercontent.com/38588787/59618352-53abd400-9128-11e9-8391-fa1e67d20cd5.png)
</details>

**Comment by krystian3w** [comment]
U mnie można, filtry na anty-adblock jakby psuły akceptacje rodo dodatkiem...

**Comment by krystian3w** [comment]
Prawdopodobnie, nie działa CSS:
https://github.com/MajkiIT/polish-ads-filter/blob/b8e26b348b6bc44b74f3e90b037010ee1f0bbbd6/polish-adblock-filters/adblock_ublock.txt#L164

---

MajkiIT porada od `okiehsch` działa tak szybko że psuje zamykanie RODO dodatkiem: https://github.com/PolishFiltersTeam/PolishCookieConsent nie ma szans na wyrobienie się...

Dodatkowo blur po RODO to usuwa słabo, wciąż on zostaje.

**Comment by krystian3w** [comment]
Tymczasowe obejście:

`turystyka.wp.pl##html > body > div#app:style(overflow: auto !important;)`

**Comment by gwarser** [comment]
`overflow` jest resetowany przez coś z opóźnieniem.

Widzę `filter:blur(8px)` na `body>div#app`

**Comment by krystian3w** [comment]
blur widzisz, bo jest z cookies / rodo - ten jest naprawiany dodatkiem a overlay-buster nie pozwala klikać dodatkowi.

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/63653931-e2b21980-c773-11e9-900a-d60c7dd715f8.png)
