### ISSUE TITLE
pudelek.pl

### ISSUE THREAD

**Issue by Tasiorsa** [MajkiIT/polish-ads-filter#14500]
### Zrzut ekranu
<!
![pudelek](https://user-images.githubusercontent.com/35109319/63515810-f8ada900-c4eb-11e9-867c-da1b060d2e64.png)
--
Przeciągnij i upuść tutaj swój zrzut lub zamieść do niego link.
-->

### Link bezpośredni

https://www.pudelek.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wystarczy wejść na główną stronę https://www.pudelek.pl/ 
 
### Moja konfiguracja
**Przeglądarka internetowa:**
Najnowszy Firefox/Chrome

**Rozszerzenia i skrypty:**
Nano Adblocker + Nano Defender

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. POL: Oficjalne polskie filtry przeciwko alertom o Adblocku
4. Wszystkie polskie dodatkowe z MajkiIT

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Maskowanie jako mobilna przeglądarka - niby WP nie wykrywa tam...

**Comment by MajkiIT** [comment]
@krystian3w chyba to samo na sportowefakty.wp.pl jest to samo?
@F4z @AdamWr pomożesz?

**Comment by krystian3w** [comment]
Nie wiem czy da radę, w uBO jest ten blur i zablokowane przewijanie - AdGuard dostaje lżejszą wersję lub tylko pop-up tam wycieka co jakiś czas.

**Comment by Tasiorsa** [comment]
Problem nie jest rozwiazany. Glowna strona wchodzi, pudelek z pierwszego posta znika ale nie da sie wejsc w zadna zakladke :)

**Comment by krystian3w** [comment]
Pewnie konflikt z Rodo a pudelek raczej już nie powinien wskakiwać jak masz dzisiejszą listę "polskie anty-ablock.

**Comment by Tasiorsa** [comment]
Rodo wylaczylem filtry zaktualizowane - strona dalej nie dziala. Pojawia sie pudel po 0,5 sek znika ale nie da sie wejsc w zaden link

**Comment by krystian3w** [comment]
No dobra, pudel niby już shackowano. Co do znikania i nieklikaności to tego nie umiem namierzyć.

Jest też opcja, że Oleg uznał że nie trzeba skopiować 2 dopuszczeń i jednej linijki CSS by skrypt nabrać?

**Comment by krystian3w** [comment]
@olegwukr skopiuj tak jak podał @AdamWr i ja podzieliłem na dwa pliki u nas.

Niby bez CSS i dopuszczeń na pudelku maskują linki.

https://github.com/AdguardTeam/AdguardFilters/commit/cf3e436a835c32846b758d99c8d441b55251fbe9

> `anti-adblock.txt`
> 
> ```
> o2.pl,pudelek.pl,film.wp.pl,finanse.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,ksiazki.wp.pl,magazyn.wp.pl,moto.wp.pl,opinie.wp.pl,sportowefakty.wp.pl,tech.wp.pl,wiadomosci.wp.pl#@#.pub_300x250
> o2.pl,pudelek.pl,film.wp.pl,finanse.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,ksiazki.wp.pl,magazyn.wp.pl,moto.wp.pl,opinie.wp.pl,sportowefakty.wp.pl,tech.wp.pl,wiadomosci.wp.pl#@#.text_ads
> ```
> 
> `anti-adblock-suplement.txt`
> ```
> o2.pl,pudelek.pl,film.wp.pl,finanse.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,ksiazki.wp.pl,magazyn.wp.pl,moto.wp.pl,opinie.wp.pl,sportowefakty.wp.pl,tech.wp.pl,wiadomosci.wp.pl##+js(set-constant.js, Object.prototype.isBlocked, false)
> o2.pl,pudelek.pl,film.wp.pl,finanse.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,ksiazki.wp.pl,magazyn.wp.pl,moto.wp.pl,opinie.wp.pl,sportowefakty.wp.pl,tech.wp.pl,wiadomosci.wp.pl##+js(set-constant.js, Object.prototype.aggressiveAB, false)
> o2.pl,pudelek.pl,film.wp.pl,finanse.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,ksiazki.wp.pl,magazyn.wp.pl,moto.wp.pl,opinie.wp.pl,sportowefakty.wp.pl,tech.wp.pl,wiadomosci.wp.pl##.pub_300x250:style(display: block !important;)

**Comment by Tasiorsa** [comment]
U Was wszystko dziala? U mnie wrocil pudel jak z pierwszego postu i nie da sie przegladac strony :P

**Comment by krystian3w** [comment]
Wystarczy aktywować `adguard base list`, wtedy znika i linki do artykułów działają bez żadnego problemu.

**Comment by Tasiorsa** [comment]
Faktycznie nie mialem tej listy zaptaszonej. Teraz jest OK. Dzieki :)

**Comment by krystian3w** [comment]
Może Pingiwn z uAsset będą w stanie wskazać jakie dopuszczenia AG działają, bo na razie chcą wywalić:

https://github.com/MajkiIT/polish-ads-filter/blob/75a9a5b1a0eb6e6a83c89bef17dde0ece7a594b6/polish-adblock-filters/adblock_ublock.txt#L139 https://github.com/MajkiIT/polish-ads-filter/blob/75a9a5b1a0eb6e6a83c89bef17dde0ece7a594b6/polish-adblock-filters/adblock_ublock.txt#L162

A alternatyw nie podali..., czyli masa reklam do wycinania 1 dniowym filtrem kosmetycznym.

**Comment by Tasiorsa** [comment]
U mnie chyba wrocil pudel z pierwszego postu. A 3 dni temu dzialalo :/

**Comment by krystian3w** [comment]
Trzeba zobaczyć jak Adguard to wyciął 1 dniowym filtrem niekompatybilnym z uBO.
albo napisali skrypt, bo false z set-constant za szybko idzie wykryć.
