### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by majaczos22** [MajkiIT/polish-ads-filter#14506]
![wp](https://user-images.githubusercontent.com/54483181/63641845-2f82eb00-c6b5-11e9-9738-58466485d4ee.jpg)

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na stronę.
2. 
3. 

### Moja konfiguracja
Firefox 68.0.2

**Rozszerzenia i skrypty:**
Tampermokey + Reklamy WP
ADB Plus

**Listy filtrów:**
1. EasyList + EasyList Polish
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Polskie filtry elementów irytujących
4. ABP Filters

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
W ABP nie da się naprawić, co innego wykrywają jako problem.

Rozważ wymianę na uBlock Origin. Tam się da jako tako naprawić: https://github.com/MajkiIT/polish-ads-filter/issues/14504, https://github.com/MajkiIT/polish-ads-filter/issues/14500 - minus, RODO też wycina. potem psują się playery WP w artykułach lub komentarze w sportowych faktach (wtedy trzeba doinstalować: https://addons.mozilla.org/pl/firefox/addon/polish-cookie-consent/)

**Comment by majaczos22** [comment]
Ciekawe bo mi ABP wycina znacznie więcej reklam niż uBlock. Najgorsze jest to, że przed reinstalką systemu miałem tak dobrane filtry ABP że nic nie wyskakiwało, ale straciłem profil przeglądarki, a wraz z nim wszystkie dodatki i ich ustawienia...

Zmieniłem ABP na uBlock Origin. W zalinkowanych wątkach nie widzę za bardzo działających rozwiązań ponad to co już mam zainstalowane. Mimo że filtrów mam od groma:
![filtry](https://user-images.githubusercontent.com/54483181/63655787-e8682900-c78c-11e9-8927-2ddbdbc2ebd6.jpg)

Niestety wciąż wyskakuje AdBlocker na sportowefakty.wp.pl czy wiadomosci.wp.pl. Jak już wspomniałem w pierwszym poście - mam tez skrypt "Reklamy WP" do Tampermonkey i też nic...

**Comment by krystian3w** [comment]
Skrypt jest skonwertowany do filtru dla uBO, więc jest teraz jedynie dla ABP / AdBlock lub do testów.

https://github.com/MajkiIT/polish-ads-filter/blob/c364320d67c06485dcb9fd365a605afa5a31b292/polish-adblock-filters/adblock_ublock.txt#L162

---

Komunikat po "sekundzie" ma znikać od tego:

https://github.com/MajkiIT/polish-ads-filter/blob/c364320d67c06485dcb9fd365a605afa5a31b292/polish-adblock-filters/adblock_ublock.txt#L163
to usuwać blur komunikatu Anty-Ablock: 
https://github.com/MajkiIT/polish-ads-filter/blob/c364320d67c06485dcb9fd365a605afa5a31b292/polish-adblock-filters/adblock_ublock.txt#L164

Jak zostaje blur to on jest po RODO-Cookies, te da się tylko sieciowo blokować i nie wiem czy ktoś będzie aktualizować filtr, niby wysłałem poprawkę url skoro `overlay-buster.js` zaburza pracę dodatku: https://addons.mozilla.org/pl/firefox/addon/polish-cookie-consent/

Szybciej ukrywać się obecnie raczej nie da, niby nie można zrezygnować z filtru 
https://github.com/MajkiIT/polish-ads-filter/blob/c364320d67c06485dcb9fd365a605afa5a31b292/polish-adblock-filters/adblock_ublock.txt#L162

Opcjonalnie w Firefox wyłącz wbudowaną ochronę prywatności: https://mozillapl.org/forum/viewtopic.php?p=245098#p245098


---

Reklamy swoje na WP wrzuć tu: #13818

**Comment by MajkiIT** [comment]
@krystian3w Nie masz teraz zmiany URL na główną stronę Sportowych Faktów ?

**Comment by krystian3w** [comment]
Na razie nie:

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +143 | `\|\|wp.pl/b3rvq2h1tvizfccbr0par3*dtbskw=$script,domain=~pilot.wp.pl\|~www.dobreprogramy.pl` | -- | sportowefakty.wp.pl | 1 | script | `https://sportowefakty.wp.pl/b3RvQ2h1TVIzFCcBR0pAR3BMc1EYWT1AJhJzHkpuQAlwKQ5tN249bA0pDm03bj1sDSkObTduPWwNKQ5tN249bA0pDm03bj1sDSkObTduPWwNKQ5tN249bA0pDm03bj1sDSkObTduPWwNKQ5tN249bA0pDm03bj1sDSkObTduPWwNKQ5tN249bA0pDm03bj1sDSkObTduPWwNKQ5tN249bA0pDm03bj1sDSkObTduPWwNKQ5tN249bA0pDm03bj1sDSkObTduPWwNKQ5tN249bA0pDm03bj1sDSkObTduPWwNKQ5tN249bA0pDm03bj1sDSkObTduPWwNKQ5tN249bA0pDm03bj1sDSkObTduPWwNKQ5tN249bA0pDm03bj1sDSkObTduPWwNKQ5tN249bA0pDm03bj1sDSkObTduPWwNVH0QHRNYEX0BIVgbXQtRfUR_AUYCUwt9ASFYG10LUX8VOUcGWk9XOxc2XAdCFloxWDtBSkw=` |
</details>

Dziwne że filtr się pobrał mi przez uBO w tle.

**Comment by krystian3w** [comment]
Jak @F4z  / @adamwr nie widzi nic przeciwko, to takie coś można skonwertować na składnie uBO i wrzucić do Olega (luźne linki po refferer pewnie od nas przyśpieszają hacki WP na skrypty JS / CSS  / dupuszczania):

https://github.com/AdguardTeam/AdguardFilters/commit/cf3e436a835c32846b758d99c8d441b55251fbe9

`anti-adblock.txt`

```
o2.pl,pudelek.pl,film.wp.pl,finanse.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,ksiazki.wp.pl,magazyn.wp.pl,moto.wp.pl,opinie.wp.pl,sportowefakty.wp.pl,tech.wp.pl,wiadomosci.wp.pl#@#.pub_300x250
o2.pl,pudelek.pl,film.wp.pl,finanse.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,ksiazki.wp.pl,magazyn.wp.pl,moto.wp.pl,opinie.wp.pl,sportowefakty.wp.pl,tech.wp.pl,wiadomosci.wp.pl#@#.text_ads
```

`anti-adblock-suplement.txt`
```
o2.pl,pudelek.pl,film.wp.pl,finanse.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,ksiazki.wp.pl,magazyn.wp.pl,moto.wp.pl,opinie.wp.pl,sportowefakty.wp.pl,tech.wp.pl,wiadomosci.wp.pl##+js(set-constant.js, Object.prototype.isBlocked, false)
o2.pl,pudelek.pl,film.wp.pl,finanse.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,ksiazki.wp.pl,magazyn.wp.pl,moto.wp.pl,opinie.wp.pl,sportowefakty.wp.pl,tech.wp.pl,wiadomosci.wp.pl##+js(set-constant.js, Object.prototype.aggressiveAB, false)
o2.pl,pudelek.pl,film.wp.pl,finanse.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,ksiazki.wp.pl,magazyn.wp.pl,moto.wp.pl,opinie.wp.pl,sportowefakty.wp.pl,tech.wp.pl,wiadomosci.wp.pl##.pub_300x250:style(display: block !important;)
```


---

Przy okazji przydałoby się plik z filtrami `anti-adblock.txt` (pod "ABP") wysprzątać z pośpiesznie tam dodanych filtrów `:has()` / `:matches-css()` / `:style()`. 

Część zaczęła wycinać RODO, bo niby pop-up ten jest `position: fixed` i np. `top: 0`. Już niewspominając o co się dzieje jak ktoś ma ABP 2.X (w technologii XUL) na Firefox 4-56.

_Teoretycznie możemy spróbować w nim podbić ABP do 3.5 i część dopuszczeń przerobić na rewrite (redirect znane z uBO i AdGuard scriplets)  https://help.eyeo.com/adblockplus/how-to-write-filters#rewrite, o ile nadrzędnie nie zadziała na to `easyprivacy` / `easylist` (ABP nie ma funkcji important, by w razie czego takie podmiany zasobów wymusić jak generyk za działa prędzej i specyficzny filtr już wcale)._

---

Następnie przemyśleć czy psujemy dalej WP `overlay-buster` w celu usuwania RODO w suplemencie filtrów reklamowych. Może czas się pogodzić z tym że dodatek musi to zamykać: https://addons.mozilla.org/pl/firefox/addon/polish-cookie-consent/

**Comment by majaczos22** [comment]
Na sportowefakty.wp.pl wszystko ukrywa, ale przy okazji znika pasek przewijania. Na pozostałych podstronach nie tylko nie ma paska, ale zostaje też "blur", prawdopodobnie po RODO. RODO mogę kliknąć, który filtr wyłączyć żeby RODO zaczęło się znowu pojawiać?
Bardziej niepokoi mnie znikanie paska przewijania.

**Comment by krystian3w** [comment]
Już AdamWr zorzgryzł WP


W uBo wymuś aktualizacje "oficjalne polskie filtry anty-adblock".

**Comment by krystian3w** [comment]
Jak nie zadziałają filtry od AdamaWr to WP już zrobiło kolejny myk by komunikat wrócił.

**Comment by xxcriticxx** [comment]
see https://github.com/MajkiIT/polish-ads-filter/issues/13818
