### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by domker** [MajkiIT/polish-ads-filter#14511]
### Zrzut ekranu
Białe tło + GUI przeglądarki
(nie ma co wklejać)

### Link bezpośredni
https://ssl.dobreprogramy.pl/Logowanie.html
https://forum.dobreprogramy.pl

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. W trybie/widoku mobilnym  otworzyć URL
2. Kliknąć (tapnąć?) w pole np. do wpisania loginu lub na forum przycisk "odpowiedz" (będąc zalogowanym)
3. Odczekać 1-2 sek.
4. Klawiatura na moment się pojawia, chowa i cała zawartość strony znika.

### Moja konfiguracja
Przeglądarka: Kiwi Browser (wersja Genie)
System: Android 8.0, MIUI Polska 10.5 (9.8.15)
**Rozszerzenia i skrypty:**
- uBlock Origin
- uBlock Origin Extra
- Privacy Badger
**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Peter Lowe’s Ad and tracking server list
4. Fanboy's (wszystkie trzy)
5. Easy Privacy
6. Domyślne uBlocka
**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
- Błąd występuje tylko, gdy włączone są filtry "Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda"
- Błąd występuje tylko w przeglądarce mobilnej przy widoku mobilnym strony. (po przełączeniu na tryb desktopowy nie ma błędu)

**Comment by krystian3w** [comment]
`ssl.dobreprogramy.pl#@#+js(overlay-buster.js)`

❓

**Comment by krystian3w** [comment]
@seba2282 filtr na anty-adblock (i ubocznie RODO) to psuje.

**Comment by seba2282** [comment]
@krystian3w, dobrze wiedzieć.

**Comment by seba2282** [comment]
Ja mam inny problem oprócz wspomnianego tutaj. @krystian3w, czy u ciebie na głównej DP w Microsoft Edge (stary EdgeHtml) i Ublock Origin masz też w pewnym momencie wielki odstęp między artykułami (taki wielki odstęp,

**Comment by hawkeye116477** [comment]
@seba2282 Za pierwszym razem się pojawia, po odświeżeniu znika.

**Comment by krystian3w** [comment]
Może efekt uboczny jakiegoś XHR, niby całe XHR od WP zablokowałeś.

Jest też opcja że bilioteka WP "z rodo" Ci się nie umie załadować, nikt jej na siłę przy pierwszych odwiedzinach nie będzie wciskał w stronę.

Masz problem bez blokowania, zgłoś na forum i może `docent` naprawi np. rękami `Lisek` / "`narnadil`" / "`sp.spczek`" (nicki dwóch ostatnich osób są za trudne do zapisu z głowy)?

Przy czym pamiętaj, że szablon nie wspiera IE11, to może i EdgeHTML 12-19 ("silnik" 22 - 44).

**Comment by seba2282** [comment]
Przy czym ja już dawien dawno usunąłem tę regułę z xhr i jej nigdzie nie mam, @krystian3w. I tradycyjnie ublock origin bez dodanych dodatkowych reguł, w tzw. moje filtry (reguły). Ale z tymi samymi filtrami, jak zawsze miałem. 
@hawkeye116477, dziękuję za informację.

**Comment by seba2282** [comment]
Wydaje mi się, że u mnie problem z logowaniem się na urządzeniu mobilnym znikł. Testowałem z oczyszczeniem wszystkich ciasteczek i nie mam już problemu. :)

**Comment by krystian3w** [comment]
Tak domena wykreślona z filtra, overlay-buster zakomentowany po efektach białej o2.pl i uszkadzania otwierania "plotek" z pudelka.

**Comment by lukjan32** [comment]
sa reklamy

**Comment by hawkeye116477** [comment]
`sa reklamy`
I raczej zostaną, niestety brak chętnych, by poprawiać codziennie, chyba posłuchali dawnej rady gorhilla, która brzmiała coś w stylu „skoro codziennie poprawiają, to nie ma sensu, lepiej olać ich i poszukać lepszej witryny" :smile:

**Comment by seba2282** [comment]
@hawkeye116477, to skrypt dla tampermonkey też nie działa na domeny WP?😂

**Comment by hawkeye116477** [comment]
@seba2282 Te rozwiązanie już jest na liście dla uBO, dla AG też chyba i już nie działa.

**Comment by seba2282** [comment]
@hawkeye116477, kiedy @krystian3w dał mi fajną regułę, to chyba wywaliło to wszystko włącznie z upierdliwymi cookies/rodo na domenach wp. To było coś z xhr. Ale czy nadal to działa? Nie wiem. Nie mam już niestety tej reguły od niego. A dostałem dlatego, bo poprosiłem o fixa dla starego MS Edge, w którym widać, że blokery reklam cały czas nie radzą sobie za dobrze.

**Comment by krystian3w** [comment]
Tyle że plik z biblioteką WP ma obecnie nowy schemat nazwy i na reszcie portali też coś go używają do detekcji dodatków blokujących reklamy.

**Comment by krystian3w** [comment]
Przykład:

```
https://wawalove.wp.pl/MDUwODIwYiU0FTl3ZgxvMHdNbSc5HxI3IRNtaGsob353KBAbFigSGwooEBsWKBIbCigQGxYoEhsKKBAbFigSGwooEBsWKBIbCigQGxYoEhsKKBAbFigSGwooEBsWKBIbCigQGxYoEhsKKBAbFigSGwooEBsWKBIbCigQGxYoEhsKKBAbFigSGwooEBsWKBIbCigQGxYoEhsKKBAbFigSGwooEBsWKBIbCigQGxYoEhsKKBAbFigSGwooEBsWKBIbCigQGxYoEhsKKBAbFigSGwooEBsWKBIbCigQGxYoEhsKKBAbFigSGwooEBsWKBIbCigQGxYoEhsKKBAbFigSGwooEBsWKBIbCigQGxYoEhsKKBAbFigSGwooEBsWKBIbCigQGxYoEhsKKBAbFigSGwooEBsWKBIbCigQGxYoEmZ5VTpmc1ViMyUdPCggFWJ2e0Rhd3pCYjMlHTwoIBVgJz0CIS9kGSIwPBEmJygDJCs7WSU3awo=
```

**Comment by seba2282** [comment]
@krystian3w, to użyć jakiś Defuser, ale nie pingwinkowego, bo i on sobie nie radzi. A jest wielce reklamowany. 🙂

**Comment by krystian3w** [comment]
Dziurę na głównej naprawia takie coś: (znika efekt popsutych list programów i czerwona kropka na ikonie powiadomienia znikąd...)


```
dobreprogramy.pl#@#+js(set-constant, Object.prototype.bodies, true)
dobreprogramy.pl#@#.ads
@@||www.googletagservices.com/tag/js/gpt.js$script,domain=www.dobreprogramy.pl
```

Tyle, że rodo trzeba odrzucić / zaakceptować i stronę może 2 razy odświeżyć.

**Comment by seba2282** [comment]
A ten upierdliwy anty adblock na wp.pl?
Ludzie psiaczą na to. A do taty mówię : "po co ci .... wp, skoro są lepsze portale?
😂😂😂

A tak do tematu wracając, co się dzieje, że domeny wp są dla was specjalistów ostatnio takie problematyczne?

**Comment by MajkiIT** [comment]
@seba2282 cokolwiek naprawimy to WP zmienia coś i przestaje działać.

**Comment by seba2282** [comment]
@MajkiIT, dzięki za informację. 🙂

**Comment by gzenio22** [comment]
Nowe cacko na dobrych programach sie pokazało :D 

![Screenshot_1](https://user-images.githubusercontent.com/21177361/65049653-696aa880-d966-11e9-902f-761b3ddd5af8.png)

Na tym bialym tle tez sie czasem zaczytuje

**Comment by krystian3w** [comment]
Załóż konto, dwa komentarze na miesiąc i reklamy znikną - jednie wypadałoby może ogarnąć bug że zalogowani mają od filtrów białą dziurę, popsuty widget i zbugowane powiadomienia.

https://github.com/MajkiIT/polish-ads-filter/issues/14511#issuecomment-530476935

**Comment by seba2282** [comment]
Jak Adguard robi, że nie ma problemu z DP, a na pilot wp jest RODO? Cały nie wiem.

**Comment by krystian3w** [comment]
Tyle ile się dało to MajkiIT przerobił w `set-constanty`, widać ten niedomaga lub coś ominięto.

**Comment by seba2282** [comment]
Czy wp wszystko wciska pomiędzy gemius i google adsense?

**Comment by seba2282** [comment]
@krystian3w, @MajkiIT nie wiem czy zakładać nowy wątek. Ale jeżeli wywołałem stronę gemius.pl, to wyskoczyło mi blokowane przez dan ballack filters. Jak dodałem blokuj stale, to tak jakby na chwilę antyadblock z wp odszedł, natomiast zacząłem widzieć reklamy. Może moglibyście zobaczyć od tej strony?

**Comment by krystian3w** [comment]
Wolontariusz uBO zdegradował filtry na reklamy. Stwierdził że były na to 3 tygodnie, ale reklam nie dociął.

**Comment by seba2282** [comment]
Jak widać, można i tak. Ale ja tak czułem, że WP wszystko wrzuca między gemius i google adsense.

**Comment by seba2282** [comment]
@krystian3w, interesujące. ||gemius.pl odblokowuje reklamy i nie masz antyadblock na wp. Natomiast 
 ||gemius.pl,domain=wp.pl zablokowuje reklamy i masz antyadblock.

**Comment by hawkeye116477** [comment]
@seba2282 Obie reguły nie do końca są poprawne, w pierwszej brakuje `^`, a w drugiej zamiast przecinka powinien być dolar.

**Comment by krystian3w** [comment]
> `||gemius.pl,domain=wp.pl`

błąd w składni, tak powinno być:

`||gemius.pl$domain=wp.pl`

**Comment by krystian3w** [comment]
I jak dla mnie dalej wymagane:

```
dobreprogramy.pl#@#+js(set-constant, Object.prototype.bodies, true)
dobreprogramy.pl#@#.ads
@@||www.googletagservices.com/tag/js/gpt.js$script,domain=www.dobreprogramy.pl
```

Nowy wynalazek Adama / Gwarsera nie naprawia blogów.

**Comment by xMaap** [comment]
Pojawiły się reklamy.

**Comment by hawkeye116477** [comment]
No to trzeba iść do konkurencji => `https://teamquest.pl/blog`, komentarzy nie mają i nieco mniej artykułów, ale przynajmniej piszą o tym, o czym powinni, trzymają poziom i nie mają trolli piszących wpisy :smile:.

**Comment by seba2282** [comment]
@hawkeye116477, rejestracja tam też darmowa?

**Comment by hawkeye116477** [comment]
@seba2282 Tam nie ma rejestracji.

**Comment by seba2282** [comment]
@hawkeye116477, to nie można być zarejestrowanym użytkownikiem tam? 🙂

**Comment by hawkeye116477** [comment]
@seba2282 Czytaj uważnie => nie ma komentarzy.

**Comment by seba2282** [comment]
@hawkeye116477, czytaj uważnie => spytałem o możliwość rejestracji, czy darmowa?

**Comment by hawkeye116477** [comment]
@seba2282 Nie można pisać komentarzy, więc raczej logiczne, że rejestracji też nie ma, no bo i po co miałaby niby być :stuck_out_tongue:

**Comment by seba2282** [comment]
@hawkeye116477, czyli teraz się zrozumieliśmy. 🙂

**Comment by xMaap** [comment]
Przyzwyczajenie robi swoje mimo panującego tam od kilku lat syfu. To co podałeś już dawno znam.

**Comment by krystian3w** [comment]
Nie każdy zna angielski by tam czytać.

**Comment by hawkeye116477** [comment]
To ja podam jeszcze inne polskie:
`pclab.pl`
`benchmark.pl`
`computerworld.pl`
`spidersweb.pl`
`geek.justjoin.it`

**Comment by krystian3w** [comment]
```
@@||www.dobreprogramy.pl^$generichide
||wp.pl^$subdocument,domain=www.dobreprogramy.pl
```

Nie wiem ile reklam zniknie ale rozwiązuje to "na dobre" problem z widgetem programów po prawej.

**Comment by krystian3w** [comment]
```
@@||www.dobreprogramy.pl^$generichide
||wp.pl^$subdocument,domain=www.dobreprogramy.pl
```

**Comment by xxcriticxx** [comment]
@krystian3w google translate is your friend!

**Comment by seba2282** [comment]
@xxcriticxx Nie może być Microsoft translate? 😂

**Comment by hawkeye116477** [comment]
Tłumacz nie zawsze dobrze się spisuje, ale raczej nie potrzeba wchodzić na zagraniczne strony, skoro tyle jest polskiej konkurencji.

**Comment by seba2282** [comment]
@hawkeye116477 Nowinki o Windows 10 to tylko zagraniczne fora, bo nasi coś nie piszą rzetelnie i zazwyczaj nic nie wiedzą. Najlepszy przykład WP z jego odłamkami. Znajdź rzetelnie napisany artykuł tam.

**Comment by hawkeye116477** [comment]
Może `https://www.centrumxp.pl/`?
Ja tam nie korzystam z W10, więc za bardzo się nie wypowiem. Kiedyś próbowałem i miałem problem taki, że po paru dniach wifi nie chciało się włączyć, cały czas mi wywalał ten standardowy komunikat jaki jest tylko na Windowsie przy łączeniu (chyba jakaś weryfikacja czy coś) i jedynie reinstall pomógł, a potem znowu za parę dni to samo...  Obecnie mam 8.1, choć rzadko tam wchodzę, częściej przesiaduję na Manjaro.

**Comment by seba2282** [comment]
@hawkeye116477 chyba że oni. Oni mają chyba najbardziej wiarygodne źródła i piszą rzetelnie.

**Comment by xxcriticxx** [comment]
off topic

**Comment by seba2282** [comment]
@xxcriticxx czasami potrzeba, aby rozluźnić emocje. 😂😂😂
A tak do rzeczy. @krystian3w masz możliwość dodania reguł do filtrów, które usuwają te wielkie białe odstępy na głównej DP? Adguard to jakoś ukrywa, ale na Android jako firefox extension robi mega zamulenie. 🙂

**Comment by krystian3w** [comment]
U mnie je usuwa generichide i ubicie ramek (jakby skrypt na reklamy WP cudem uciekł z ramki), jak WP pracuje w soboty nad "reklamy ~~tworzenie~~ to nasza pasja" no to trudno..., wyjdzie że będą jak programiści do Fortnite (z 18h programowania by raz na tydzień coś nowego w grze było).

**Comment by Barticf** [comment]
Znowu wyświetla reklamy

**Comment by krystian3w** [comment]
Trzeba się najlepiej zalogować i pisać 2 komentarze co 2 dni.

albo jak masz powodzenie w receznzjach to 1 co 90 dni (ale dolicz okres moderacji - zalecane wtedy wrzucenie dodatkowych 2 komentarzy).
