### ISSUE TITLE
megacennik.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14518]

**Comment by krystian3w** [comment]
Nie wiem, chyba siedzi to w:

`||google-analytics.com^` - czyli Peter Lowe za dużo ci psuł
`||freegeoip.net^$third-party` - magia z EasyPrivacy?

**Comment by krystian3w** [comment]
`##.cc-window[aria-label="cookieconsent"], .cc-revoke`
