### ISSUE TITLE
bose.pl/pl_pl/index.html

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14528]
Bez /index.html nie wejdzie się na stronę
![Zrzut ekranu z 2019-08-28 08-05-49](https://user-images.githubusercontent.com/36385327/63829809-ccba7980-c96a-11e9-9c0b-bbf541a9c365.png)

**Comment by krystian3w** [comment]
Nie prawda?

`https://www.bose.pl/` i samo tam przekierowuje.
