### ISSUE TITLE
sklep-domwhisky.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14529]
`https://sklep-domwhisky.pl/product-pol-9467-GlenDronach-20-letni-D-1994-B-2014-Single-Cask-3201-56-2-0-7.html`

![Zrzut ekranu z 2019-08-28 08-08-02](https://user-images.githubusercontent.com/36385327/63829872-fecbdb80-c96a-11e9-8e4b-616b70051b20.png)
![Zrzut ekranu z 2019-08-28 08-08-11](https://user-images.githubusercontent.com/36385327/63829874-ff647200-c96a-11e9-9765-003e2dd35c83.png)

**Comment by krystian3w** [comment]
@kiboke please no use on this site: `##.rodo-popup:not(body):not(html)`

**Comment by kiboke** [comment]
> @kiboke please no use on this site: `##.rodo-popup:not(body):not(html)`

Why not? I don't see that element anywhere.

**Comment by krystian3w** [comment]
![Screenshot_20190829-104832](https://user-images.githubusercontent.com/35370833/63925582-9eac6680-ca4a-11e9-95f7-59ad8b157cf1.png)

Here is it. So visible only "ok" button.

**Comment by kiboke** [comment]
> Here is it. So visible only "ok" button.

After a minute or so, I spotted it myself. Thanks!
