### ISSUE TITLE
jbzdy.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14520]
![Capture](https://user-images.githubusercontent.com/15007183/63718059-ad5f0780-c817-11e9-99ce-3a3cf0f28d01.PNG)

**Comment by krystian3w** [comment]
Jak? Nie **odz**naczyłeś sobie "[] `Przetwarzaj i stosuj filtry kosmetyczne`"?

Takiej konfiguracji nie wspieramy, nie wszystko da się sieciowo wyciąć, skrypty i html filtering to niby dalej kosmetyka?

**Comment by krystian3w** [comment]
Jak? Nie **odz**naczyłeś sobie "[] `Przetwarzaj i stosuj filtry kosmetyczne`"?

Takiej konfiguracji nie wspieramy, nie wszystko da się sieciowo wyciąć, skrypty i html filtering to niby dalej kosmetyka?

> https://github.com/MajkiIT/polish-ads-filter/blob/ba6d8ac653af79b7e0ee43e27e93c1e801a5c8bd/cookies_filters/adblock_cookies.txt#L743
>
> https://github.com/MajkiIT/polish-ads-filter/blob/ba6d8ac653af79b7e0ee43e27e93c1e801a5c8bd/cookies_filters/cookies_uB_AG.txt#L121

---

Ma być tak:

> ![obraz](https://user-images.githubusercontent.com/35370833/63721300-3d6d7300-c851-11e9-961b-c9c6b9f44590.png) |
> --- |

**Comment by krystian3w** [comment]
No to w chrome nagle się to uaktywniło, w trybie prywatnym niby wyskakuje rozwinięty pop-up.

Próbuj pobrać dzisiejszą aktualizacje cookies, klikając w zegar ":clock9:" i "Update Now".
