### ISSUE TITLE
Coś blokuje mi o2.pl i inne strony

### ISSUE THREAD

**Issue by DajMiliona** [MajkiIT/polish-ads-filter#14535]
Mam taki problem na o2.pl oraz na innych mam biala strone. Nie wiem co jak kliknac aby bylo normalnie. Nie zawsze sie to pojawia. Na kilku stronach O2 i czasem wp.pl
![2019-08-28_22h53_24](https://user-images.githubusercontent.com/39501742/63891954-af2af580-c9e6-11e9-840f-7af1d71e9d2b.png)
Jak wylacze ublock to wszystko dziala
![2019-08-28_22h55_05](https://user-images.githubusercontent.com/39501742/63892045-edc0b000-c9e6-11e9-8043-85d77d620804.png)

**Comment by hawkeye116477** [comment]
Duplicate of https://github.com/MajkiIT/polish-ads-filter/issues/13818

**Comment by krystian3w** [comment]
to chyba overlay-buster, nieźle się chyba bawią devsi WP.
