### ISSUE TITLE
anyfiles.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1453]
ad block

http://anyfiles.pl/Polska-Rumunia-3-0-2018-Skrot-meczu-11-11-2016/Sport/video/178016

Używasz Ad-Blocka, prosimy o jego wyłączenie.

**Comment by Isamaul** [comment]
Wystarczy zablokować element  `.adblInfo`
Dodatkowo wyszukiwarka nie działa z aktualną listę filtrów (pod globalny wpada - w urlu jest paramtert ads=true).

Dodając ```@@||anyfiles.pl/pageloading/search-media-loader.jsp?``` odblokujemy funkcjonalność wyszukiwania, ale na stronie wyszukiwania zostanie nam biały placek po reklamie - filtrem kosmetycznym się go nie poprawi, ale wyszukiwanie zadziała :)

**Comment by xxcriticxx** [comment]
film dziala ale dalej mam "Używasz Ad-Blocka, prosimy o jego wyłączenie." na srodku

**Comment by F4z** [comment]
Tutaj też się lista nie wczytuje - `http://anyfiles.pl/all.jsp`
To powinno pomóc:
`@@||anyfiles.pl/pageloading/all-loader.jsp?ads=true`

A te puste miejsca można chyba ukryć przy użyciu tych reguł:
`anyfiles.pl###SearchVideosLoadDiv > .media-list > .media > .thumbnail:not([title])`
`anyfiles.pl###AllVideosLoadDiv > .media-list > .media > .thumbnail:not([title])`

Swoją drogą, komunikat o adblocku się pojawia, bo ten skrypt jest blokowany `http://anyfiles.pl/js/ads.js`, więc go też można odblokować.
`@@||anyfiles.pl/js/ads.js$script`

**Comment by F4z** [comment]
@MajkiIT widzę, że usunąłeś tę regułę - `@@||anyfiles.pl/pageloading/search-media-loader.jsp?ads=true$xmlhttprequest` i dodałeś tę - `@@||anyfiles.pl/pageloading/all-loader.jsp?ads=true` ale ta pierwsza też jest potrzebna, bo teraz wyszukiwanie znowu nie działa.
Ewentualnie można dodać jedną taką:
`@@||anyfiles.pl/pageloading/*-loader.jsp?ads=true`

**Comment by MajkiIT** [comment]
@F4z Dzięki. Poprawiłem
