### ISSUE TITLE
joemonster.org

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#14538]
![scr-1567067751-001](https://user-images.githubusercontent.com/9846948/63924609-d6b2aa00-ca48-11e9-968f-985f31276713.png)

```
joemonster.org##.advert-label
```

`Adguard Extension 3.2.1`

@krystian3w  @MajkiIT

**Comment by krystian3w** [comment]
uBo daje radę czymś ukryć. Czyli raczej znowu do suplementu.

Wersja mobilna ma za to jakieś pola po reklamach.

**Comment by FadeMind** [comment]
@krystian3w 
```
joemonster.org##.right-column-rectangle-advert
```
![scr-1567069193-001](https://user-images.githubusercontent.com/9846948/63926464-2d6db300-ca4c-11e9-9185-082ecc4aa287.png)

**Comment by krystian3w** [comment]
No jak cały boks to w sumie i dla uBO się przyda.
