### ISSUE TITLE
tibiopedia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14545]
test link:
https://tibiopedia.pl/welcome

![Capture](https://user-images.githubusercontent.com/15007183/63946855-d8c63a00-ca43-11e9-9bdf-f2f6ecccd80e.PNG)

**Comment by krystian3w** [comment]
Ja nie mam czyli naprawione w filtrach nano defender / Adblock Warning Removal List​​​​​.

**Comment by krystian3w** [comment]
info   |   info
--- | ---
Filtr | `@@\|\|tibiopedia.pl/js/show_ads.js$script,domain=tibiopedia.pl`
Lista filtrów | Nano Defender Integration

**Comment by xxcriticxx** [comment]
sorry zapomnialem wlaczyc ta liste

**Comment by krystian3w** [comment]
@olegwukr  kopujesz do nas dla ABP / AdBlock?
