### ISSUE TITLE
topfilmiki.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14540]
adblock 

test link:
https://www.topfilmiki.pl/play/6482,rebak-do-drewna-hitem-internetu-

![Capture](https://user-images.githubusercontent.com/15007183/63945663-b8957b80-ca41-11e9-88a9-a5614ac3d046.PNG)

**Comment by krystian3w** [comment]
`@@||topfilmiki.pl^$generichide`
`topfilmiki.pl##.adsbygoogle`

Nie wiem czy wszystkie boxy po reklamach usuwa `adsbygoogle`.

---

@bogachenko - Are you planning to cut out the leftovers from ads? Eg. `topfilmiki.pl##.adsbygoogle`. There is no 100% certainty that the holes will not disturb someone or will have a million lists to do.
