### ISSUE TITLE
downdetector.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14552]
`https://downdetector.pl/status/youtube`

Popsute akceptowanie polityki prywatności filtrem reklamowym:

https://github.com/MajkiIT/polish-ads-filter/blob/ef641f95d18454a2d2ae60b30ed0bc46d4540f82/polish-adblock-filters/adblock.txt#L3303

https://github.com/MajkiIT/polish-ads-filter/commit/46485c29074316bc1b94e8181b28bfac371866f1

Przez co nie ma (i nie będzie) komentarzy disqus; żółty przycisk nigdy nie działał, tylko ten z pop-upa pozwalał ładować disqus. 

I niby disuqs jest ładowany skryptem evidon, więc nie wystarczy odblokowanie do zaakceptowania i dalsze blokowanie.

**Comment by hawkeye116477** [comment]
To evidon ładuje reklamy? Może chodziło o AdChoices, ale to jest polityka prywatności, więc w takim razie chyba nie powinno być to blokowane przez listę reklamową.
`https://www.evidon.com/faqs/saw-adchoices-icon-ad-website-companys-name/`

**Comment by krystian3w** [comment]
Tam się psuły jakieś obrazki z prawej kolumny, ale teraz mają jeszcze inny szablon i nowy pasek cookies.

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję
