### ISSUE TITLE
wprost.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14553]
`https://www.wprost.pl/prime-time/galerie/13662/4/tak-zmienili-sie-uczestnicy-pierwszej-edycji-big-brothera.html`

ktoś za mocno wyciął reklamę i slajd się zacina czasem na 4 stronie, czekając na koniec jakieś reklamy.

**Pomocne może być odtwarzanie tego emulując Android.**

**Comment by MajkiIT** [comment]
@krystian3w czeka na zatwierdzenie ciastek
![obraz](https://user-images.githubusercontent.com/11302675/65940104-efd3bf80-e427-11e9-84d4-2c1473ac3f09.png)

**Comment by krystian3w** [comment]
@MajkiIT to nie to - coś z EasyPrivacy lub Polskie filtry prywatności Olega.

@hawkeye116477 - cookies ubocznie wycięło EasyPrivacy, dociąć dla mających prywatność" w 4 literach (ABP / AdBlock / AdGuard [bez listy przed trackingiem, bez EI AdGuarda])?

**Comment by krystian3w** [comment]
```
@@||www.googletagservices.com/tag/js/gpt.js$script,domain=www.wprost.pl
```

Za raz wrzucę to i w Firefox na Androidzie, niby wtedy 0 zacinania się na PC jak udaję Androida.

**Comment by hawkeye116477** [comment]
@krystian3w Nie docinać, analityczne raczej do odblokowania.

**Comment by krystian3w** [comment]
Dobra. 

W sumie to my blokujemy i tak, później, zapomniałem że uprościłem dawno temu dla Polski Quancast / conseu, bo było blokowane na przynajmniej 5 różnych plikach.
