### ISSUE TITLE
community.spiceworks.com/regional/poland

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14577]

**Comment by krystian3w** [comment]
@hawkeye116477  zero polonizacji...

**Comment by krystian3w** [comment]
Zrobić tak jak z `forum.duolingo.com` i blokowanym pop-upem w EI?

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie masz włączonej listy I don't care about cookies.

**Comment by krystian3w** [comment]
Już wymagana a polskie nie przebudowane by miały 3 filtry na krzyż...?

**Comment by hawkeye116477** [comment]
Tak, od dzisiaj wymagamy :smile:
`polskie nieprzebudowane by miały 3 filtry na krzyż.`
No nie wiem czy z przebudowaniem to dobry pomysł, jak byśmy zdjęli ogólne, to zaraz pewnie byłyby zgłoszenia dot. generichide, więc chyba jednak lepiej na przyszłość zabezpieczyć się. 
3 reguły na krzyż raczej pewnie by nie były, on nie robi reguł dla uBO, no i jednak w ogóle podejrzewam, że mamy trochę więcej unikalnych reguł dla ABP nawet.

**Comment by krystian3w** [comment]
A to może lepiej je zasysać jak robi aktualizację raz na miesiąc?

**Comment by hawkeye116477** [comment]
@krystian3w Nie wiem czy dobrze rozumiem chcesz zaincludować IDCAC w naszych PFRC?
Rozważałem to już i nie wiem czy to taki dobry pomysł, jeszcze MS się obrazi... No na pewno całej nie, może ogólne tylko, ale nadal wtedy już chyba przekracza 1 MB.

**Comment by krystian3w** [comment]
To nie wiem, na sobotę / niedziele testy co można usunąć skryptami a co trzeba ręcznie przeglądać?

**Comment by hawkeye116477** [comment]
Ręcznie na pewno nie będziemy tego robić. Ja jednak jestem tego zdania, że najlepiej byłoby wymagać, bo jego lista i rozszerzenie raczej są popularne.

**Comment by krystian3w** [comment]
A dodawać czy pisać osobom, że nie mają odpowiedniej bazy aktywnej i już nie dodawać jak Kiboke blokuje.

Jakby wyciekało coś nowego prostego to by się dodawało by nie czekać 4 tygodni na poprawki w "polskim suplemencie rodo-ciasteczkowym".

**Comment by hawkeye116477** [comment]
No jeżeli wymagamy, to raczej skoro on już blokuje, to nie powtarzamy po nim już :smile:

**Comment by krystian3w** [comment]
Mi chodzi np. o:

`###cookies`
`##.cookies`

pewnie części nie usuwa on sieciowo, a generyki na nie średnio działają.

**Comment by hawkeye116477** [comment]
@krystian3w Co by to nie było, to jak u niego działa, to wtedy oczywiście że dodajemy.

**Comment by xxcriticxx** [comment]
panowie więcej list again? wow

**Comment by krystian3w** [comment]
Przynajmniej może blocker będzie zadowolony, że nie musi aż tak sprawdzać `com,eu,info,net`.

Chyba, że nie włączy listy, "bo strajk".

**Comment by hawkeye116477** [comment]
@xxcriticxx Żeby było mniej roboty, bo gość z I don't care about cookies robi naprawdę dobrą robotę i uznajemy, że nie ma co podwajać sobie roboty w związku z tym :smile:

**Comment by krystian3w** [comment]
Wada w dodatku to niby jak filtrem wycina, że sobie ktoś musi na miesiąc wpisać domenę na białą listę, raczej eksperymenty z 3 opcjami blokowania nie zawsze pomogą.

**Comment by hawkeye116477** [comment]
Nie wiem o co konkretnie chodzi, ale my nie będziemy wymagać rozszerzenia IDCAC, kto ma, to ma.

**Comment by krystian3w** [comment]
np. jak my mamy generyk już z 4 not a on z dwoma i nikt mu nie pokazał problematycznych by piekł ciastko.

**Comment by hawkeye116477** [comment]
No to wtedy będziemy robić tak jak z fanboyem, czyli wyjątki, a on jak poprawi to usuniemy.

**Comment by krystian3w** [comment]
Ale fanboy nie prowadzi apki nadrzędnej nad ABP by ABP nie umiało negować wadliwych filtrów.

---

I w sumie co będzie zasysane do EI, ~300 regułek jak mniej więcej tyle wyjdzie po ekstremalnej optymalizacji?

**Comment by hawkeye116477** [comment]
Miałem na myśli listę, rozszerzenie to jak kto tam chce.
`I w sumie co będzie zasysane do EI, ~300 regułek jak mniej więcej tyle wyjdzie po ekstremalnej optymalizacji?`
To co było, nic się nie zmieni na razie. I don't care about cookies tak samo wymagany.
Jeżeli chodzi o optymalizację listy RC no to raczej póki co nie planujemy optymalizacji.

**Comment by xxcriticxx** [comment]
aha
