### ISSUE TITLE
Zlecenie na ekstremalną listę

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#14573]
Gość na wykopie (`https://www.wykop.pl/wpis/43543937/hej-znacie-jakies-filtry-ktore-calkowicie-wylaczaj/`) chce listę, która by wycinała wszystkie JS na sprawdzonych stronach, `nie powodując przy tym zbytniego uszczerbku na ich funkcjonalności`. Czyli niby może nie być komentarzy.
Więc może komuś się nudzi i jest chętny na prowadzenie listy „Nie obchodzi mnie JS"? Może @xxcriticxx?

**Comment by krystian3w** [comment]
Niech sobie aktywuje filtr przeciwko koparkom?

**Comment by hawkeye116477** [comment]
Ale on nawet na dobrychprogramach chce wyciąć, a tam nie ma koparek...

**Comment by krystian3w** [comment]
na WP jest niby ciężki skrypt odtwarzacza czy innego badziewia. Ludzie blokują je jak nie oglądają wideo w artukułach lub działu Wideo na DP.

**Comment by hawkeye116477** [comment]
Po zablokowaniu wszystkich JS na dp też znika część fotek.

**Comment by krystian3w** [comment]
Ale jaki fotek? Nawala LazyLoad zrobiony w JS pod artykuły?

**Comment by hawkeye116477** [comment]
No np tutaj => `https://www.dobreprogramy.pl/AMD-Next-Horizon-relacja.-Szczegoly-na-temat-Zen-2-i-prezentacja-pierwszego-GPU-w-7-nm,News,91952.html`.

**Comment by krystian3w** [comment]
Mam wszystkie 3, jest też zdjęcie nad treścią a pod tytułem.

Pytanie czy mam używać:

`*$script,inline-script,domain=dobreprogramy.pl,important`
albo nawet html filteringu:

`dobreprogramy.pl##^script`

**Comment by hawkeye116477** [comment]
@krystian3w A wyczyściłeś dane przed użyciem reguły? Bo jak nie, to nic to nie dodaje, bo worker wczytuje z cache.

**Comment by krystian3w** [comment]
to nie można `ctrl+f5/r`?

**Comment by hawkeye116477** [comment]
@krystian3w To nie przejdzie.

**Comment by krystian3w** [comment]
Jak nie przejdzie, `sw.js` też blokowane, po `xhr` się odpala?

**Comment by hawkeye116477** [comment]
Już nieaktualne.

**Comment by krystian3w** [comment]
Niby jest obejście: https://stackoverflow.com/questions/15734546/using-html-data-attribute-to-set-css-background-image-url

**Comment by hawkeye116477** [comment]
@krystian3w Na co to? Oni niby dali noscript, więc powinny obrazki wczytywać się, ale to tylko zadziała jak ktoś sam z panelu/popupu uBO wyłączy js.
A tak apropo, to na stronie KADa korzystamy z tego rozwiązania do wczytywania obrazków => `https://varvy.com/pagespeed/defer-images.html` :smile:

**Comment by krystian3w** [comment]
W sumie też ciekawe czemu:

`dobreprogramy.pl##^script`

 wycina maks jeden skrypt, a resztę sieciowo:

`*$script,inline-script,domain=dobreprogramy.pl,important`

**Comment by xxcriticxx** [comment]
@hawkeye116477 na js jest `noscript` albo `umatrix` mozesz rekomendowac ja nie mam tam konta

**Comment by krystian3w** [comment]
Odpada, wątek jest jawny i możesz wyczytać, że twórcy nie odpowiadają takie dodatki.

**Comment by krystian3w** [comment]
Poza tym nie wiem ile procent internetu on przegląda i czy taki tylko po angielsku lista też by musiała ogarniać.

**Comment by hawkeye116477** [comment]
No właśnie, on chce gotową listę, żeby już za niego wszystko przetestowali, co gra a co nie gra.

**Comment by krystian3w** [comment]
Ciekawe czy napisze, że nie widzi różnicy bez zdjęć albo też uzna za rakowe.

Pod artykuły to może tryb czytania by się nadał, chyba też wywala js / zdjęcia / wideo / komentarze.

**Comment by hawkeye116477** [comment]
No chyba nie wywala, nadal się niby wczytują, jedynie wygląd się zmienia, więc powiedziałbym raczej, że to coś ala filtrowanie kosmetyczne.

**Comment by xxcriticxx** [comment]
@hawkeye116477 maybe Lynx web browser?

**Comment by hawkeye116477** [comment]
Na Vivaldim nadal po aktywacji trybu czytania, widać niby, że wczytuje się js. Choć na FF niby nie widać. Ale też tryb czytania nie działa wszędzie, np. na stronie głównej dp nie pokazuje się, tylko w artykułach i nie wiem czy ma on jakiś permanentny włącznik. 
@xxcriticxx Proponowali mu elinks2 i nie spodobało się, więc pewnie Lynx też nie. On po za tym mówił, że wszędzie nie chce wyłączać js, tylko na tych co się da.

**Comment by xxcriticxx** [comment]
no to zostaje maszyna do pisania na pewno js bedzie wylaczony

**Comment by hawkeye116477** [comment]
Powiedziałbym pewnie, że najlepsze rozwiązanie to te zaproponowane przez Konoromi => `https://www.dobreprogramy.pl/Web-Rendering-Proxy,Program,Windows,103135.html` skoro nie chce sam testować. Bo raczej pewnie nie będzie chętnych na robienie takiej ekstremalnej listy.

**Comment by xxcriticxx** [comment]
retro PC :)
