### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#14588]
**Site Sample** | 
----------------|
https://pilot.wp.pl/tv/#polsat

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64 (lastest)
Browser:                               | Firefox Quantum 69.0 x64 (lastest)
AdGuard version:                       | **7.2.2903.6 BETA [20190902]** 
Stealth Mode:					       | disabled

**Site Sample** | 
----------------|
https://pilot.wp.pl/tv/#polsat

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64 (lastest)
Browser:                               | Firefox Quantum 69.0 x64 (lastest)
AdGuard version:                       | **7.2.2903.6 BETA [20190902]** 
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuckadblock
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| Fanboy's Cookiemonster List
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

FB share 

```
pl###fb > span > iframe
```

<details><summary><b>Screenshot:</b></summary>

![scr-1567443191-001](https://user-images.githubusercontent.com/9846948/64127872-e36e2f80-cdb3-11e9-98e1-a96caa1b1b63.png)

</details><br/>

@krystian3w  @MajkiIT

**Comment by krystian3w** [comment]
uBo daje radę, ABP pewnie też, więc trafia to na listę bugów z braku userCSS.

**Comment by krystian3w** [comment]
Jakiś inny przykład polskiej z taki samym układem przycisku udostępnij, wyciekający z AG?

```html
<div id="fb">
    <span>
        <iframe src="..." {...}>
    </span>
</div>
```

**Comment by hawkeye116477** [comment]
Nano też daje radę.

**Comment by FadeMind** [comment]
![scr-1567444216-001](https://user-images.githubusercontent.com/9846948/64128156-5cba5200-cdb5-11e9-8be5-5e59dc8a11e1.png)

**Comment by krystian3w** [comment]
dalej wp.pl, znajdź taki na onet.pl albo interia.pl?

**Comment by hawkeye116477** [comment]
@FadeMind Nie masz Fanboy's Social

**Comment by krystian3w** [comment]
Może zapomniał dokelić "Fanboy Annoyance", niby miał zaznaczony.

**Comment by FadeMind** [comment]
@krystian3w mam Adguard Social, ale dodam Fanboy Annoyances zamiast Cookiemonster. Zobaczę.

**Comment by krystian3w** [comment]
@hawkeye116477 A AG tam blokuje strzałkę w górę, czy nikt nie dodał do EI?

**Comment by FadeMind** [comment]
@krystian3w bez zmian...

**Comment by krystian3w** [comment]
Dobra, to włączę chromę i zobaczę jaki wytnie 3 na raz ale raczej uruchomię go pod tylko jedną subdomenę wp.

Chyba że hawkeye szybciej doda.

---

Co do userCSS Nano to niestety tak nie można porównywać, trzeba koniecznie AG.

**Comment by FadeMind** [comment]
CC @ameshkov Adguard for windows leaking facebook 😁

**Comment by FadeMind** [comment]
> dalej wp.pl, znajdź taki na onet.pl albo interia.pl?

https://praca.interia.pl/news-w-najblizszym-czasie-wazne-zmiany-w-prawie-pracy,nId,3181652

```
praca.interia.pl##.social-facebook-fanpage-below-label
```
![scr-1567445138-001](https://user-images.githubusercontent.com/9846948/64128583-84aab500-cdb7-11e9-964b-4478aeb942fc.png)

**Comment by hawkeye116477** [comment]
Sprawdziłem na AdGuardzie i nie ma problemu, ale rozszerzenie na Vivaldim.
Może beta ma buga.

**Comment by AdamWr** [comment]
Jeśli chodzi o `pilot.wp.pl`, to nie potrafię tego odtworzyć u siebie.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/64128612-b02d9f80-cdb7-11e9-8498-7d9730f89765.png)

</details>

Spróbuj może wyłączyć po kolei listy "trzecie" takie jak `Fuck Fuckadblock` i sprawdź, czy nie powodują problemu.

**Comment by FadeMind** [comment]
@AdamWr  dokładnie FFA daje ciała. 

CC @bogachenko

**Comment by krystian3w** [comment]
Nie za bardzo `@@$generichide`, wp ma odgórnie w polskich filtrach anty-adblock, a z Interii mam napis na prawo pozbawiony linka.

`![obraz](https://user-images.githubusercontent.com/35370833/64128842-f33c4280-cdb8-11e9-8682-702c658bd058.png)`

**Comment by hawkeye116477** [comment]
`@@*$generichide, wp ma odgórnie w polskich filtrach anty-adblock`
To chyba ja jestem ślepy, bo ja tam tego nie widzę.

**Comment by krystian3w** [comment]
A dobra, niegrzeczny 🐧 tam używa generichide, ale widać nie pomaga skoro trzeba i tak jawnie użyć filtrów generycznych EasyList jako dopuszczenia.

![obraz](https://user-images.githubusercontent.com/35370833/64129088-3b0f9980-cdba-11e9-8359-e4da3dee0dc6.png) |
--- |

**Comment by hawkeye116477** [comment]
@krystian3w
` skoro trzeba i tak jawnie użyć filtrów generycznych EasyList jako dopuszczenia.`
Były ostatnio jakieś dopuszczenia na generyczne reguły? Raczej wstrzykiwanie js, bo inaczej to pewnie trzeba było odblokować reklamy.

**Comment by krystian3w** [comment]
Nic nie trzeba dodawać, nieświadomie blokowałem jako normalny brak w Fanboy social.

**Comment by krystian3w** [comment]
> Były ostatnio jakieś dopuszczenia na ogólne reguły?

Np. Dopuszczenia pod pudelka i  linia CSS robiąca to samo jaka padła tam po 17 godzinach od referrów z naszych jawnych linków, bo zgłoszenie nie nakazuje blokady klikalności.

**Comment by krystian3w** [comment]
Poza tym już coś zgłaszali, że `generichide` źle działa na iframe czy coś?

**Comment by hawkeye116477** [comment]
Generalnie to chyba generichide powinien wyłączać wszystkie kosmetyczne ogólne.

`Nic nie trzeba dodawać, nieświadomie blokowałem jako normalny brak w Fanboy social.`
No jak nie trzeba, jak :penguin: doczepił generichide..

**Comment by krystian3w** [comment]
Ja traktowałem każde zgłoszenie jakbym miał wyłączony NDI.

Nie wiem na ile wycieka social od NDI, większość raczej z lenistwa "Rayna" Fanboy'a Nowo Zelandczyka 🇳🇿.

**Comment by hawkeye116477** [comment]
Ja tam widzę jednak, że u mnie nie wycieka pomimo włączonej listy NDI.

**Comment by krystian3w** [comment]
No bo fanboy raczej nie przegląda polskiego WP.

**Comment by krystian3w** [comment]
Nagłówek "Więcej informacji" to niby, że szukać ich na FB / Insta?

**Comment by krystian3w** [comment]
Jak da się naprawić w samym FFA (np. stwierdzenie, że `generichide` już nic nie daje), to wtedy ten filtr można usunąć: https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/529a248f967eef6bc23d9db5ff3dc61443f18078

**Comment by FadeMind** [comment]
@krystian3w  dodałem `pilot.wp.pl#?#.fb_iframe_widget` i jest OK (FFA włączone), Fanboy Cookiemonster zamiast Annoy.

**Comment by krystian3w** [comment]
No zobaczymy czy @bogachenko namierzy bug w swojej liście, jak dla mnie może jednak w AG np. beta, jak Adam na stable sprawdzał.

**Comment by FadeMind** [comment]
@krystian3w z tego co @bogachenko mi tłumaczył to składnia skryptów dla Adguard dla Windows a Adgurd Extension jest odmienna. Po za tym Twórcy ADG ciągle grzebią w CoreLibs i być może ostatnie zmiany zaowocowały niekompatybilnością. Nadmieniam, że używając tego samego zestawu filtrów w Adguard Extension nie mam problemów z FB na WP Pilot. Problem pojawił się PO instalacji nowej dzisiejszej wersji AFW - stąd ten wątek :)

**Comment by bogachenko** [comment]
I did not read the thread, because it is not in English. but based on intuition, you are talking about Frame-Facebook, right? I have it blocked by AdGuard Social Media. Good to all.

**Comment by FadeMind** [comment]
@bogachenko  naprawił problem po stronie FFA @krystian3w 😁

**Comment by lukjan32** [comment]
jest blokada

**Comment by krystian3w** [comment]
Zmienić user-agent dla WP na mobilny Firefox/Chrome.

**Comment by lukjan32** [comment]
nie mam w smartfonie lte

**Comment by hawkeye116477** [comment]
Są jeszcze inne opcje => zrezygnować z Pilota WP i przejść do Platformy Canal+ albo do jakiejś oferty na kartę (nc+ na kartę) albo do jakiejś kablówki albo Netlifxa albo jeżeli tylko darmowe ciebie interesują, to jest NTC :smile:

**Comment by krystian3w** [comment]
> nie mam w smartfonie lte

https://github.com/MajkiIT/polish-ads-filter/issues/14588#issuecomment-529968253. Nie musisz kupić wiaderek do telefonu:

https://addons.opera.com/pl/extensions/details/user-agent-switcher-5/

https://addons.opera.com/pl/extensions/details/user-agent-switcher-8/

**Comment by lukjan32** [comment]
ktory lepszy?

**Comment by krystian3w** [comment]
W sumie bez różnicy, wybrałem dwa aktualizowane by nie było, że udajesz mobilną przeglądarkę z okolic 2014-15.

Co do tego co wychwytują z filtrów jako blokadę, to na razie nie namierzyłem.

**Comment by hawkeye116477** [comment]
Tak generalnie, to najlepszy jest https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg?hl=pl.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/14588#issuecomment-529967545 

wabiki to:

```
pilot.wp.pl#@#+js()
pilot.wp.pl#@#.ads
```

czyli trzeba dodać kosmetyk i sprawdzić jaki filtr / skrypt wadzi:



--- | --- | --- | --- | --- | ---
-- | -- | -- | -- | -- | --
+1 | `##+js(abort-on-property-write, __serviceAbModal)` |   | `www.wp.pl` |   | `dom`
+1 | `##+js(set-constant, WP.gaf.loadBunch, noopFunc)` |   | `www.wp.pl` |   | `dom`
+1 | `##+js(set-constant, Object.prototype.bodies, true)` |   | `www.wp.pl` |   | `dom`
+1 | `##+js(set-constant, PWA_adbd, 2)` |   | `www.wp.pl` |   | `dom`
+1 | `##+js(abort-on-property-read, WP.inline)` |   | `www.wp.pl` |   | `dom`
+0 | `##+js(abort-on-property-write, __serviceAbModal)` |   | `pilot.wp.pl` |   | `dom`
+0 | `##+js(set-constant, WP.gaf.loadBunch, noopFunc)` |   | `pilot.wp.pl` |   | `dom`
+0 | `##+js(set-constant, Object.prototype.bodies, true)` |   | `pilot.wp.pl` |   | `dom`
+0 | `##+js(set-constant, PWA_adbd, 2)` |   | `pilot.wp.pl` |   | `dom`
+0 | `##+js(set-constant, PWA_adbd, 0)` |   | `pilot.wp.pl` |   | `dom`

**Comment by hawkeye116477** [comment]
`pilot.wp.pl#@#+js(set-constant, WP.gaf.loadBunch, noopFunc)`
Ale wtedy niby pisze, że wszystkie kanały są niedostępne.

**Comment by lukjan32** [comment]
> > nie mam w smartfonie lte
> 
> [#14588 (comment)](https://github.com/MajkiIT/polish-ads-filter/issues/14588#issuecomment-529968253). Nie musisz kupić wiaderek do telefonu:
> 
> https://addons.opera.com/pl/extensions/details/user-agent-switcher-5/
> 
> https://addons.opera.com/pl/extensions/details/user-agent-switcher-8/

nie dziala.

**Comment by krystian3w** [comment]
W firefox wyłącz ochrony CSP;
mnie komunikat o niedostępności nie wyskakuje, bo nie używam skryptu do udawania Google Bota.

**Comment by lukjan32** [comment]
wiem, o tym.

**Comment by lukjan32** [comment]
nie da rady, zrobic filtru?

**Comment by hawkeye116477** [comment]
Może się da, ale raczej nie opłaca się, bo pewnie jutro znowu zrobią psikusa..

**Comment by hawkeye116477** [comment]
@lukjan32 Może się da, ale raczej nie opłaca się, bo pewnie jutro znowu zrobią psikusa...

Zainstaluj KODI wraz z wtyczką i po problemie.

**Comment by lukjan32** [comment]
aha, wole przegladarka

**Comment by Lukjan37** [comment]
nie da rady tego zrobic? :(
