### ISSUE TITLE
artexhome.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14586]
cookies

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/092ce21d2ede25884aec9469542e9940f96734b3

Ale to i tak raczej nie spełni w 100% czegoś w rodzaju bota co przejży cały internet i dobierze najlepszą metodę eliminacji pasków i pop-upów.
