### ISSUE TITLE
news.samsung.com/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14589]

**Comment by krystian3w** [comment]
https://filters.adtidy.org/extension/ublock/filters/229.txt

Wtedy nie ma, @hawkeye116477 tam jest padding po cookies czy mi się wydaje?

I jak z poprawkami na paddingi / mariginy - ABP musi obejść się smakiem?

**Comment by hawkeye116477** [comment]
Raz mi się tylko pojawił, potem zniknęło, nawet czyściłem dane i nie ma.
@xxcriticxx Zasubskrybuj `https://www.i-dont-care-about-cookies.eu/abp/`

**Comment by krystian3w** [comment]
A co z blockerem, bo chyba wyłączył.
