### ISSUE TITLE
tapeciarnia.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#14596]
### Zrzut ekranu
![Screenshot_20190904_235929](https://user-images.githubusercontent.com/19818572/64294826-0cd3ba80-cf70-11e9-8bb8-46071785ba00.png)

### Link bezpośredni
`https://www.tapeciarnia.pl/shrek`

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1.  Wejść na stronę
2.  Zerknąć i spostrzec, że Kot w Butach ze swoim spojrzeniem gdzieś się zapodział

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Brak części tapet, a tak po za tym jest też dziura po reklamie.

Może:
```
tapeciarnia.pl#@#div[style*="text-align:center;"]:has-text(REKLAMA)
tapeciarnia.pl###reklama_pod_gorne_menu
tapeciarnia.pl#?#.thumb td:-abp-contains(REKLAMA)
tapeciarnia.pl#?#td > div:-abp-contains(REKLAMA)
```

**Comment by MajkiIT** [comment]
@hawkeye116477 Dziękuję
