### ISSUE TITLE
pomponik.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14595]
https://www.pomponik.pl/plotki/news-23-letni-syn-beaty-kempy-ubiega-sie-o-mandat-posla-brak-dosw,nId,3185240

Na końcu jakaś Facebookowa reklama.

> ![Screenshot_20190904-165540](https://user-images.githubusercontent.com/35370833/64266450-e9d7e500-cf34-11e9-836d-42fcc8fb38ea.png) |
> --- |
> `\|\|www.facebook.com/plugins/post.php?*sandra.cieslak.921*posts*2276843322444321$subdocument,domain=www.pomponik.pl` |

Ani to rodzinie Kempy ani o Polityce...

**Comment by xxcriticxx** [comment]
Jak mam to zaznaczyć reklama czy social?

**Comment by krystian3w** [comment]
W sumie nie wiem.
