### ISSUE TITLE
portalwrc.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#14597]
Agitacja 🚫 , skrypt blokujący prawy klik 🛑  
![scr-1567653427-001](https://user-images.githubusercontent.com/9846948/64309469-d6606480-cf9c-11e9-9bbb-6df95a0f7d5f.png)
![scr-1567653583-001](https://user-images.githubusercontent.com/9846948/64309470-d6606480-cf9c-11e9-9645-8514186a925a.png)
@krystian3w

**Comment by krystian3w** [comment]
EI od roku nie odblokowuję już prawego kliku, @AdamWr.

**Comment by AdamWr** [comment]
Prawy klik naprawiony.
Dzięki.

**Comment by FadeMind** [comment]
@AdamWr Slider usunięty via
```
portalwrc.pl###djslider-loader127
```

![scr-1567680101-001](https://user-images.githubusercontent.com/9846948/64335157-86a08e00-cfda-11e9-8939-794055aed943.png)

**Comment by hawkeye116477** [comment]
@okiehsch Right click blocked

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/fa58b92375fb4077814a0d99fb22b61c45b8d9ac
