### ISSUE TITLE
www.vipera.com.pl/pl/index.php

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#146]
Pliki cookie
Na niniejszej stronie wykorzystywane są statystyki Analitycs firmy Google. Pliki cookie Google Analytics.
Podobnie jak wiele innych usług, narzędzie Google Analytics korzysta z własnych plików cookie do śledzenia działań użytkowników witryny. Pliki te służą do przechowywania informacji, np. czasu rozpoczęcia bieżących odwiedzin oraz tego, czy użytkownik był już kiedyś w tej witrynie i z jakiej witryny trafił na bieżącą stronę internetową. Przeglądarki internetowe nie współdzielą własnych plików cookie pomiędzy domenami.

**Comment by MajkiIT** [comment]
statyczny element
