### ISSUE TITLE
sdk.waw.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14602]

**Comment by krystian3w** [comment]
@kiboke:

`sdk.waw.pl###bpcookies`

or possible network filter?

**Comment by kiboke** [comment]
> @kiboke:
> 
> `sdk.waw.pl###bpcookies`
> 
> or possible network filter?

Thanks. I'll try with blocking `/jquery.bpcookies.min.js` pattern for now.
