### ISSUE TITLE
lista serwisów PPG

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14609]
@hawkeye116477 cos dla ciebie 

https://prywatnosc.polskapress.pl/nasze-serwisy

**Comment by hawkeye116477** [comment]
Ale to już było...

**Comment by xxcriticxx** [comment]
no to dzis pojechaly konie po betonie

**Comment by hawkeye116477** [comment]
Mój program na tą chwilę nie wyciąga stron ze zwykłego tekstu jeżeli o to chodzi, jedynie z href.
Ale tak jak mówię, tutaj jest podane praktycznie wszystko na tacy, więc można też to zrobić szybko ręcznie za pomocą zaznaczania kolumnowego w VSCode by dodać pipe czy tam przecinek :smile:

**Comment by xxcriticxx** [comment]
@hawkeye116477 nie tlumacz sie dzialaj!

**Comment by hawkeye116477** [comment]
A dlaczego ja, a może @xxcriticxx :stuck_out_tongue: ?

**Comment by xxcriticxx** [comment]
@hawkeye116477 ja nic nie umiem

**Comment by hawkeye116477** [comment]
No nie żartuj, zaznaczać pionowo w VSCode nie umiesz?
To mam dla ciebie lekturę => `https://code.visualstudio.com/docs/editor/codebasics#_column-box-selection`.

**Comment by xxcriticxx** [comment]
@hawkeye116477 Hello World!

**Comment by hawkeye116477** [comment]
Polecam również zainstalować takie cudo => https://marketplace.visualstudio.com/items?itemName=sgryjp.vscode-stable-sort&ssr=false#overview

`aip24.pl,aktywnamalopolska.pl,biuroreklamykrakow.pl,blog.ekstraklasa.net,budowlane.targibialystok.com,budzetalert.pl,demaskator24.pl,deweloperzy.bialystok.pl,dziennikbaltycki.pl,dzienniklodzki.pl,dziennikpolski24.pl,dziennikzachodni.pl,e-aranzacje.pl,e-bezposrednio.pl,e-budownictwo.pl,e-dach.pl,e-instalacje.pl,e-izolacje.pl,e-lazienki.pl,e-mieszkanie.pl,e-ogrodek.pl,e-okna.pl,e-sciany.pl,echodnia.eu,ekstramagazyn.pl,expressbydgoski.pl,expressilustrowany.p,extra.telemagazyn.pl,flexiformday.pl,forumbudowlane.pl,forumlokalnegobiznesu.pl,forumogrodowe.pl,forumprzedsiebiorcow.pl,gazetakrakowska.pl,gazetalubuska.pl,gazetawroclawska.pl,gk24.pl,glos.tv,gloswielkopolski.pl,gol24.pl,gp24.pl,gra.pl,gratka.pl,gs24.pl,internet.polskapress.pl,jarmark.com.pl,juniorfutbol.pl,kurierlubelski.pl,lh.gda.pl,lighthouse.gda.pl,lubietubyc.pomorska.pl,menedzerroku.pl,miastakobiet.pl,mieszkaniowe.targibialystok.com,motofakty.pl,napijsiekawy.pl,naszahistoria.pl,naszekomunikaty.pl,naszemiasto.pl,nekrologi.net,nowiny24.pl,nowosci.com.pl,nto.pl,podlasieguide.pl,polskapress.pl,polskatimes.pl,pomorska.pl,poranny.pl,pracapolska.eu,prasa24.pl,projektreklama.pl,regiodom.pl,regiofirma.pl,regiopedia.pl,regiopraca.pl,reklama.express.bydgoski.pl,reklamawroclaw.com,rir.info.pl,sportowy24.pl,strefaagro.pl,strefabiznesu.pl,stronakobiet.pl,stronazdrowia.pl,sud.polskapress.pl,telemagazyn.pl,to.com.pl,tygodnikits.pl,urzadzone.pl,wider.pl,widerkontext.pl,widermobile.pl,wspolczesna.pl,zlotasetkapodlaskie.pl`

**Comment by xxcriticxx** [comment]
jeszcze zebys to zrobil clickable to by bylo pol roboty z glowy

**Comment by krystian3w** [comment]
Nie ma klikable bo zaraz się zlecą dewsi  PPG na wątek i będzie druga blokada jak na WP, że trzeba im reklamy łagodniej wywalać i raz dziennie aktualizować.

**Comment by krystian3w** [comment]
@hawkeye116477 zobacz czy to jest ok: https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/6dd4df863aa399fa5ef085451137cd82e1b50c1a

Jak dla mnie raczej bezpieczne i nie trzeba sprawdzać tych 50 domen a innych polskich nie uszkodzi?

**Comment by hawkeye116477** [comment]
Nie wiem, a gdzie to w ogóle jest?

**Comment by krystian3w** [comment]
miałem wyciek np. tu: `demaskator24.pl`

I czy pamiętasz gdzie jest filtr na fb  z stopki od nich:

`echodnia.eu##.atomsNavigationFooterSocialmedia__button > svg` taki ci się nie podobał i nakićkałeś że nie widzę reszty domen.

**Comment by hawkeye116477** [comment]
@krystian3w Przecież Fanboy to wycina.

**Comment by hawkeye116477** [comment]
Nie pamiętam.

**Comment by krystian3w** [comment]
Dobra znalazłem jest w ogólnych i niby dlatego ma jakiś `"paramert="image=facebook""`.
