### ISSUE TITLE
kinobajka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14603]

**Comment by krystian3w** [comment]
Statyczne, bez zamykania, nie znika, mogą wcisnąć tam i jakąś reklamę jak stwierdzą, że już wszyscy przeczytali.

**Comment by hawkeye116477** [comment]
To do @KonoromiHimaries, on takie lubi :smile:

**Comment by krystian3w** [comment]
W jaki plik mati?

```
kinobajka.pl##body > div[style^="background"]:not([id]):not([class]):nth-of-type(1)
```

**Comment by KonoromiHimaries** [comment]
@krystian3w na główną, tylko otaguj
