### ISSUE TITLE
stronazdrowia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14608]
test link:
https://stronazdrowia.pl/ile-bylo-do-smierci-dni-moze-tygodnie-diagnoza-byla-jak-wyrok-ale-uratowal-ich-przeszczep-watroby/ar/c14-14321183

![Capture](https://user-images.githubusercontent.com/15007183/64474964-0a2cbd00-d14a-11e9-85b0-405c14bd01fc.PNG)

**Comment by hawkeye116477** [comment]
Nie ma wolności mediów bez oglądalności reklam :smile:

**Comment by krystian3w** [comment]
`stronazdrowia.pl##+js(set-constant.js, pp_adblock_is_off, trueFunc)`
