### ISSUE TITLE
otrservis.ru [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#14604]
### Screenshot

Without filter:

<details>

![image](https://user-images.githubusercontent.com/8361299/64417847-879cf280-d0a2-11e9-822f-783cf6c43594.png)

</details>

With filter background image is hidden:

<details>

![image](https://user-images.githubusercontent.com/8361299/64417868-91265a80-d0a2-11e9-8bd7-8d6dd7987c80.png)

</details>

### Direct link
http://otrservis.ru/

**Filter lists:**
1. EasyList
2. Official Polish Filters For AdBlock, uBlock Origin and AdGuard

Possible solution: `otrservis.ru#@#[src*="/banners/banner"]`

**Comment by hawkeye116477** [comment]
Or maybe better is changing from `##[src*="/banners/banner"]` to `pl##[src*="/banners/banner"]` :smile:.

**Comment by krystian3w** [comment]
But readable. No reported by Company nad his webmaster have vacations?

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/14604#issuecomment-528843309or remove at all (~8 also excluded).

**Comment by MajkiIT** [comment]
@Alex-302 @hawkeye116477 @krystian3w Thanks
