### ISSUE TITLE
kucharenka.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#14613]
### Zrzut ekranu
![Screenshot_20190907_154506](https://user-images.githubusercontent.com/19818572/64475709-7f1de800-d186-11e9-8aba-1c4ff4ea43b3.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Resztka po reklamie „znajdź coś dla siebie" po prawej.
`http://kucharenka.pl/delikatne-kotlety-mielone-z-kurczaka`

**Comment by krystian3w** [comment]
I na przepisy.pl trzeba jakiś kosmetyk #14487
