### ISSUE TITLE
e-budownictwo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14614]

**Comment by krystian3w** [comment]
To białe to nie cookies, a jakieś ogłoszenie `płatne`.

**Comment by krystian3w** [comment]
> Spółka Saint-Gobain - właściciel marki RIGIPS, oświadcza, że przygotowane na jej zlecenie filmy reklamowe pt. „Jak wymieszać masę szpachlową Rigips Start+ i Rigips Finisz+" oraz „Test wydajności masy szpachlowej Rigips Start+" dostępne w Internecie, stanowią niedozwoloną reklamę porównawczą, sprzeczną z dobrymi obyczajami. Saint-Gobain przeprasza wszystkich odbiorców, jak również Siniat sp. z o.o. - właściciela marki NIDA, za prowadzenie reklamy niezgodnej z prawem, a w szczególności za podanie w tej reklamie nierzetelnych informacji dotyczących gipsów szpachlowych NIDA Start oraz NIDA Finisz oraz oświadcza, że nie będzie podejmować takich działań w przyszłości.
> 
> OGŁOSZENIE PŁATNE

**Comment by xxcriticxx** [comment]
Test reklamowy

**Comment by hawkeye116477** [comment]
Etykieta invalid + won't fix :smile:

**Comment by xxcriticxx** [comment]
Ja bym to wyciął kiedyś ukaże się tam reklama/cookies

**Comment by krystian3w** [comment]
`##body > div[style]:nth-of-type(1)`

**Comment by hawkeye116477** [comment]
@xxcritcxxTo jak się ukaże to wytniemy...
Co ty drugi Dandelion? Gość dodał do filterlists.com listę, która jest w dopiero w planach.

**Comment by krystian3w** [comment]
Widać Collinowi nie przeszkadza.

**Comment by hawkeye116477** [comment]
No to w takim razie teraz kolej na dodanie Polskich Filtrów Elementów Sponsorowanych i Polskich Filtrów Fake-Newsowych do `filterlists.com`, które @MajkiIT planował :smiley:
