### ISSUE TITLE
teatr.bedzin.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14612]
zablokowany scroll strony

**Comment by krystian3w** [comment]
Celowe, proszę o `invalid` / `won't fix`.

Jak robię ujemne zbliżenie (zoom 50%) to i tak treść chamsko ucieka.

**Comment by krystian3w** [comment]
Chcesz poczytać to klikasz w "**repertuar**" lub "**cała reszta**".

**Comment by krystian3w** [comment]
Po 20:00 (**UTC+2**) eksperymentalnie `Polskie filtrów irytujących` dodadzą wymuszenie scrollowania.

Niby nie bugguje to przycisku "repertuar", ale dalej do filtrów reklamowych się nie za bardzo nadaje.
