### ISSUE TITLE
e-plytki.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14618]

**Comment by krystian3w** [comment]
`###cookie`

@kiboke no possible solution for this?

**Comment by hawkeye116477** [comment]
@krystian3w Pisz jaśniej, rozwiązanie jest możliwe... :stuck_out_tongue:

**Comment by kiboke** [comment]
Maybe he meant "no possible generic or script blocking solution is possible" :) It doesn't matter, we understand each other. Even your "Pisz jaśniej" was clear to me, in croatian it is "Piši jasnije" :)
