### ISSUE TITLE
budmat.com/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14619]

**Comment by krystian3w** [comment]
`##.cookies`

silimar hard as #14618 ...

**Comment by hawkeye116477** [comment]
Jakie trudne, nie rozumiem, nic tu specjalnego :stuck_out_tongue:

**Comment by krystian3w** [comment]
nie idzie z tego zrobić generyka, chyba że coś w stylu:

 `##body > .cookies:nth-of-type(-n+10)`

lub od końca:

 `##body > .cookies:nth-last-of-type(-n+10)`

**Comment by hawkeye116477** [comment]
Tego to lepiej, nie ruszać, kiedyś były podobne i o ile pamięć mnie nie myli, to psuły. Generyki lepiej dodać jak są :cookie: z dodatkiem, np. :chocolate_bar: :smiley:

**Comment by krystian3w** [comment]
W sumie nikt nie sprawdzał czy wtedy uszkadza je:

```
##body > .cookies
##body > .cookie
##body > #cookies
##body > #cookie
```

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/958 - to nawet nie umiałem wychwycić jak grać by odtworzyć bugi.
