### ISSUE TITLE
corbby.com.pl/pl/

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14610]

**Comment by krystian3w** [comment]
@kiboke this need accept - I cannot found `safe block network file`?

**Comment by xxcriticxx** [comment]
@krystian3w googlem tlymaczysz na english?

**Comment by krystian3w** [comment]
Nie, tak słabo umiem po prostu angielski.

**Comment by xxcriticxx** [comment]
zrozumialem dziekuje

**Comment by krystian3w** [comment]
@gwarser

chyba mam regresję:

`###tlight:has(.termspopupcontainer), #tfade` wycina w uBO 1.21.2 aż dwa elementy i niby działa "poprawnie", aż chyba sprawdzę w `v1.22.x`.

**Comment by gwarser** [comment]
@krystian3w chyba tylko szczęście, że ten akurat działa.

Mój test nadal nie https://github.com/uBlockOrigin/uBlock-issues/issues/453#issuecomment-471086120

**Comment by kiboke** [comment]
> @kiboke this need accept - I cannot found network block file to hide pop-up and recover scroll?

I think I'll have to accept it with JS I'm afraid.
