### ISSUE TITLE
Mamy jakieś setTimeout-logger / setInterval-logger?

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14617]
https://github.com/gorhill/uBlock/commit/c5536577b29cd0bcd401f7ecd143a921acdb4eb6#diff-d7616deaf3a39e3f19f8d70d098bfe7a

```
The two new scriptlets are meant to replace:
- setTimeout-defuser
- setTimeout-logger
- setInterval-defuser
- setInterval-logger

setTimeout-logger and setInterval-logger have been
removed, since they are not to be used in production.

To log setTimeout and setInterval usage, respectively
(using aliases):
- ##+js(stif)
- ##+js(siif)
```

**Comment by hawkeye116477** [comment]
No ba, są w EI.

**Comment by hawkeye116477** [comment]
PolishFiltersTeam już przerobił, został tylko @MajkiIT.

**Comment by krystian3w** [comment]
Znowu padnie:

https://github.com/gorhill/uBlock/commit/9367a6015b8cbb6b49347b00a105aab8f24df861

**Comment by krystian3w** [comment]
Teraz wyjdzie, że wystarczyło poczekać aż nazwa i alias się ustabilizują lub czekać na pełny dead defuserów, na razie wywali tylko loggery do konsoli jakby strona była trudna w debugowani i u każdego inny efekt.

**Comment by hawkeye116477** [comment]
Czyli jak dobrze rozumiem teraz nie trzeba będzie dawać wykrzyknika, bo nikt w ten sposób nie korzystał z tego. Ah ten gorhill, mógł najpierw zrobić rekonesans, potem wprowadzić zmianę.
