### ISSUE TITLE
fabryka-kuchni.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14628]
cookies

**Comment by krystian3w** [comment]
Katedra cookies jakiś

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/14631

@kiboke

**Comment by kiboke** [comment]
> #14631
> 
> @kiboke

What was the issue here? Cookie warning is already blocked.

**Comment by krystian3w** [comment]
Wasn't 7 days ago?  Or uBO too late download updated IDCAC.
