### ISSUE TITLE
miastakobiet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14624]
test link:
https://miastakobiet.pl/maz-alkoholik-skatowal-zone-kluczem-francuskim-kobieta-otrzymala-pomoc/ar/c15-14366845

![Capture](https://user-images.githubusercontent.com/15007183/64481872-3da43180-d1b4-11e9-9fb1-b7566521867d.PNG)

**Comment by krystian3w** [comment]
```
miastakobiet.pl##+js(set-constant.js, pp_adblock_is_off, trueFunc)
||s-pt.ppstatic.pl/*/reklama.js$script,redirect=noopjs,important
```
