### ISSUE TITLE
mera.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14629]
" Znajdź nas " ( na dole )

**Comment by krystian3w** [comment]
@hawkeye116477 jakaś uszkodzona, looader ma loop i część pod nim się nie załadowała...

**Comment by krystian3w** [comment]
`@@||mera.eu/wp-content/themes/mera/app/common/lib/lightGallery-1.1.3/demo/js/lg-share.min.js$xmlhttprequest,first-party`

...
