### ISSUE TITLE
copperconcept.org/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14620]

**Comment by krystian3w** [comment]
`##.coco-cookiebar`

@kiboke you disable this with addon?

**Comment by hawkeye116477** [comment]
@krystian3w On to akceptuje.

**Comment by hawkeye116477** [comment]
@krystian3w No, it's not on I don't care about cookies.

**Comment by xxcriticxx** [comment]
@krystian3w przestan wzywac cały internet!

**Comment by krystian3w** [comment]
Od kiedy jeden Chorwat to cały net...

**Comment by kiboke** [comment]
> Od kiedy jeden Chorwat to cały net...

One croatian, yeah, but I have influence in hundreds of thousands of lives ;)
Please keep letting me know whenever you find something I don't block with IDCAC, I'm grateful.
