### ISSUE TITLE
timoore.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14632]
cookies i fb ( na dole )

**Comment by krystian3w** [comment]
@kiboke:

`###ciacho-info-container` or `###ciacho-info`

ciacho - cookie with good sound in Polish 🇵🇱.

**Comment by krystian3w** [comment]
@hawkeye116477 ten fb to jakiś post jednak, takich nie usuwamy.

**Comment by hawkeye116477** [comment]
@krystian3w Sam możesz dodać taki generyk.

**Comment by krystian3w** [comment]
generyk generyk czy `pl,com,eu,info` jako mniej-więcej najpopularniejsze?

**Comment by hawkeye116477** [comment]
Raczej to pierwsze, jak polska nazwa jest, to wtedy nie dopisujemy końcówek.
