### ISSUE TITLE
luxmeble.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14639]
fb ( na dole ) i cookies

**Comment by krystian3w** [comment]
`###cookie` @kiboke.

**Comment by hawkeye116477** [comment]
@krystian3w Dodawaj do nas, nie musisz go wołać :stuck_out_tongue:

**Comment by xxcriticxx** [comment]
LOL

**Comment by kiboke** [comment]
> @krystian3w Dodawaj do naszej listy, nie musisz go wołać, daj mu odpocząć stuck_out_tongue
> No chyba, że jest błąd albo zagraniczne, to wtedy możesz krzyczeć.

Whenever he lets me know, I can improve IDCAC extension, so please let him do it :) Thanks @krystian3w
