### ISSUE TITLE
tally-weijl.com/pl_PL

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14648]
coś zadużo blokuje

**Comment by krystian3w** [comment]
To ładowanie z góry i fail po chwili?

Jak tak to psuje EasyPrivacy, chyba że mają zaświniony 🐷🐖🐽🐗 plik `gtm.js`.

**Comment by krystian3w** [comment]
`@@/frosmo.easy.js$script,domain=www.tally-weijl.com`

Ale trzeba ocenić na ile to reklama, bo to wycina tę blondynkę w jeansie.

**Comment by krystian3w** [comment]
@@||inpref.com/productApi$xhr

A to chyba do naprawy logowania / koszyka.

---

W uBO już można wymusić aktualizacje filtrów `unbreak`, EasyPrivacy nie wiadomo czy szybko naprawi.
