### ISSUE TITLE
brotkids.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1465]
ad block 

Zauważyłem, że korzystasz z AdBlocka, jeżeli chcesz pomóc mi w dalszym rozwoju strony i kanału, proszę o wyłączenie AdBlocka na tej stronie. Dziękuję za wszelką pomoc! Jesteś super mega!

**Comment by F4z** [comment]
`@@||brotkids.tv/media/mod_pwebadblock/js/ads.js$script`

**Comment by MajkiIT** [comment]
@F4z Dzięki
