### ISSUE TITLE
csbydgoszcz.pl

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#14664]
Przeglądarka stable Edge Chromium (x64), Windows 10, rozszerzenia ublock origin i I don't care about cookies.
Więc tak ukryta zawartość na stronie: 
www,csbydgoszcz.pl 
gdy ublock origin jest włączony
![CSBbezwylaczonegoublockorigin](https://user-images.githubusercontent.com/16944478/64857924-3652ad00-d626-11e9-860a-0377cb72b8a3.png)
I normalne funkcjonowanie powyższej strony, gdy ublock origin jest dla niej wyłączony
![CSBzwylaczonymublockorigin](https://user-images.githubusercontent.com/16944478/64857961-52eee500-d626-11e9-8234-6844a5c81eea.png)

**Comment by krystian3w** [comment]
@MajkiIT  zepsułeś tym:

```
www.csbydgoszcz.pl#@#[id^="ad_global"]
```

Filtr | `##[id^="ad_global"]`
--- | ---
Lista filtrów | `POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda`

**Comment by seba2282** [comment]
Aktualizacja filtrów moment temu nic nie dała.

**Comment by hawkeye116477** [comment]
Bo nie zostało nic usunięte, jedynie jakaś strona zablokowana.

**Comment by MajkiIT** [comment]
@seba2282 @krystian3w Dziękuję

**Comment by seba2282** [comment]
CSB cały czas ma ukrytą zawartość po aktualizacji filtrów. :(

**Comment by krystian3w** [comment]
To już pewnie nie przez nas? 

```
www.csbydgoszcz.pl##[id*="ads"]:style(display: block !important;)
```


`@@||csbydgoszcz.pl^$generichide`

**Comment by seba2282** [comment]
@krystian3w, sprawdzę już sobie to jutro na spokojnie, ale dzięki za twoją pomoc, jak i za pomoc pozostałych chłopaków od polskich list. 🙂

**Comment by seba2282** [comment]
@krystian3w , mógłbyś mi powiedzieć, który filtr odpowiada za to z tych wbudowanych do ublock origin? Wyłączyłem wszystkie dodatkowe i domyślnie (bez twoich reguł na generyki) CSB jest blokowane.

**Comment by hawkeye116477** [comment]
@seba Z tych domyślnych żaden, zrób screena, podaj co masz, a jeżeli tylko domyślnie zaznaczone, to zaktualizuj ponownie listy (czasem zdarza się, że aktualizacja nie zaskoczy) albo przywróć fabryczne ustawienia uBO.

**Comment by seba2282** [comment]
@hawkeye116477, Liste FR robi ukrytą zawartość - zgłoszone do easylist. Ale szukam winowajcy, który blokuje te ikonki, co mają połącz ze steam i itp. Obok gametracker. Na domyślnych opcjach ublock to też jest blokowane. Nie wiem jak z nano adblocker czy Adguard.

**Comment by seba2282** [comment]
@hawkeye116477 Polskie oficjalne filtry ubijają te linki Połącz Steam, GT i HLTV.,
obok tego monitoring na csb.

**Comment by krystian3w** [comment]
Gdzie tego szukać...

**Comment by krystian3w** [comment]
@smed79 can you try found bad generic filter - https://github.com/MajkiIT/polish-ads-filter/issues/14664#issuecomment-531556306

**Comment by seba2282** [comment]
Na głównej masz u góry listę serwerów z teamspeak. Obok masz adresy ip, potem gametracker, potem połącz steam, potem hltv. Widzisz to zaraz na początku strony csb?

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/14664#issuecomment-531572929

to łap:

`@@/reklamy/*$image,domain=csbydgoszcz.pl`

--

@MajkiIT dopisz domenę do:

`/reklamy/*$image,domain=~selgros24.pl|~jacus.pl`

🔽 

```
/reklamy/*$image,domain=~selgros24.pl|~jacus.pl|csbydgoszcz.pl
```

**Comment by hawkeye116477** [comment]
@krystian3w Ale wiesz, że @MajkiIT nie zagląda do zamkniętych zgłoszeń. Trzeba utworzyć nowe zgłoszenie :smile:
