### ISSUE TITLE
Likwidacja serwera na Discordzie

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#14668]
Proponuję zlikwidować serwer na Discordzie, ponieważ rzadko kiedy ktoś tam wchodzi, a @MajkiIT to już chyba od jakiegoś czasu wcale tam nie zagląda. Czasem niby ludzie tam przychodzą i wypytują o Ojca Dyrektora, który jest nieobecny , a ja go wołam, a on nic :smiley: Ewentualnie można by zastąpić Discord redditem, jeżeli się Prezesowi nie podoba. Na redditcie podobnie można zrobić czat tylko dla VIP'ów, zresztą jak na GH zrobi się organizację, to wtedy też tam można. Z racji, że reddit to forum, więc pewnie nieco bardziej by odpowiadał, o ile w ogóle jest takie coś potrzebne, może wystarczy jedynie formularz na stronie + email + GH.

**Comment by xxcriticxx** [comment]
GitHub wystarczy mamy taki zajebisty ruch ze drugiego forum nie potrzebujemy

**Comment by MajkiIT** [comment]
Czytam tylko wiadomości prywatne i skupiam się na tym co tutaj się pojawia.

**Comment by hawkeye116477** [comment]
Czyli rozumiem, że wszyscy zgadzają się na likwidację serwera na Discordzie.

**Comment by xxcriticxx** [comment]
@hawkeye116477 ty ostatnio za dużo ECO jesteś

**Comment by hawkeye116477** [comment]
Ok, serwer usunięty. 
@MajkiIT Pozostała tylko aktualizacja w Readme i na stronie `certyficate.it`.

**Comment by hawkeye116477** [comment]
Eh, nadal ne zaktualizowane, tak samo zresztą parę innych spraw pomimo zapewnień, trzeba będzie chyba utworzyć nową listę skarg i zażaleń.
