### ISSUE TITLE
na kiedyś

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14670]

**Comment by krystian3w** [comment]
001 #11136
002 #11145 (w tym są jednak spore kontenery to zgłoszę osobno)
003 http://2plus3d.pl/
004 http://agencjaroleplay.pl/
005 http://artkulinaria.pl/
006 http://ashika.it/
007 http://bada-world.pl/
008 http://bazylika-pszow.pl/
009 http://bitmon.pl/
010 http://borshop.pl/
011 http://cdrl.pl/
012 http://danutaantas.blogspot.com/
013 http://docelu.radom.pl/
014 http://dogorynogami.org/
015 http://driftopen.com/
016 http://exploringaround.pl/
017 http://foodmag.pl/
018 http://golebiowate.blogspot.com/
019 http://h1z1.eu/
020 http://heart-dimension.com/
021 http://inzynier-medyczny.pl/
022 http://itvregion.pl/
023 http://jakosxleci.blogspot.com/
024 http://jeffs.com/
025 http://kolna.pl/
026 http://kominki7.pl/
027 http://kreatorniazmian.pl/
028 http://lifefestival.pl/
029 http://losgrafikos.pl/
030 http://mamado.pl/
031 http://mamokazje.pl/
032 http://marekowczarz.pl/
033 http://moje-drinki.pl/
034 http://mynaszlaku.pl/
035 http://nakanapa.pl/
036 http://naszczelincu.pl/
037 http://nbalabs.pl/
038 http://nowykamieniarz.pl/
039 http://openstreetmap.org.pl/2018/infografika-podsumowanie-roku-2017/
040 http://organeoblog.pl/
041 http://prospectrum.pl/
042 http://przedszkolowo.pl/
043 http://przegladbaltycki.pl/
044 http://radio.opole.pl/
045 http://salonmodyxxl.pl/
046 http://sanatoriumchemik.pl/
047 http://shebang.pl/
048 http://sielska.eu/
049 http://skawina24.com/
050 http://slepsksuwalki.pl/
051 http://smog.krakow.pl/
052 http://sportowetv.pl/
053 http://stolowka-warminska.pl/
054 http://strefafana.pl/
055 http://vstars.pl/
056 http://whyart.pl/
057 http://wizytowki4you.pl/

**Comment by krystian3w** [comment]
058 http://wolontariat.org.pl/
059 http://www.13ulica.pl/schedule/day/today
060 http://www.akademiads.pl/
061 http://www.akademiakotaleonarda.pl/
062 http://www.ap-goal.pl/
063 http://www.arsdental.pl/
064 http://www.businessbar.pl/
065 http://www.chatazzalipia.pl/
066 http://www.coachingbalance.pl/
067 http://www.danfoss.pl/home/#/
068 http://www.delia.pl/
069 http://www.geekweek.pl/
070 http://www.gloswojewodzki.pl/
071 http://www.grapplerinfo.pl/
072 http://www.ibrpolska.pl/
073 http://www.joga-joga.pl/
074 http://www.kasianafali.pl/
075 http://www.klodzko.pl/pl/
076 http://www.klub-malawi.pl/
077 http://www.kulturatka.pl/
078 http://www.kurpas.com.pl/
079 http://www.ladyofthehouse.pl/
080 http://www.leksyka.pl/
081 http://www.nasza-chata.pl/
082 http://www.newtonmedia.pl/pl
083 http://www.paczkiwpodrozy.pl/
084 http://www.patriotyczna.com/pl/
085 http://www.pljasien.pl/
086 http://www.poszkole.pl/
087 http://www.prawojazdyradom.com.pl/
088 http://www.slaskieradio.com/
089 http://www.thecoachingmaps.eu/
090 http://www.windowsmania.pl/forum.php
091 http://www.zso11.zabrze.pl/
092 http://www.zyraffa.pl/
093 http://www.zywiec112.com.pl/
094 http://zarabiamykase.com.pl/
095 http://zbawienie.pl/jak-badac-biblie-1/
096 https://3xk.pl/
097 https://anikagotuje.blogspot.com/
098 https://bbfan.pl/
099 https://bewood.pl/
100 https://bezglutenowamama.pl/
101 https://bezstresowa.pl/
102 https://bieliznaujoli.pl/
103 https://brzeszcze.pl/
104 https://cerrad.com/
105 https://cichlidae.pl/
106 https://cukroweozdoby.pl/
107 https://e-mcklein.pl/
108 https://eduzabawy.com/
109 https://fundacjaiskierka.pl/
110 https://gorydlaciebie.pl/
111 https://imssport.pl/
112 https://jumpcity.pl/
113 https://korty.org/
114 https://laserwradomiu.pl/

**Comment by krystian3w** [comment]
115 https://manito.pl/
116 https://meblehubertus.pl/
117 https://mvpmagazyn.pl/
118 https://netland.pl/
119 https://notimi.pl/
120 https://paradise-rpg.pl/
121 https://piaseczno.eu/
122 https://polifoska.pl/
123 https://portal.bikeworld.pl/
124 https://salumanus.eu/
125 https://secretplace.pl/
126 https://shopconnector.pl/
127 https://termos24.pl/
128 https://ustrzyki-narty.pl/
129 https://wksklep.pl/
130 https://wroclawfashionoutlet.com/
131 https://www.agriaffaires.pl/
132 https://www.bata.pl/
133 https://www.beautyever.pl/
134 https://www.biorezonans.zgora.pl/
135 https://www.bizuteria-tytanowa.pl/
136 https://www.bogactwokaw.pl/
137 https://www.butynalata.pl/
138 https://www.dulux.pl/pl
139 https://www.e-madame.pl/
140 https://www.esab.pl/pl/pl/index.cfm
141 https://www.ewaipiotr.pl/
142 https://www.gazetkonosz.pl/
143 https://www.groupon.pl/
144 https://www.hotelprzystan.com/
145 https://www.karmimypsiaki.pl/
146 https://www.kiloutou.pl/
147 https://www.krainadrzwi.pl/
148 https://www.kreskowki.tv/kreskowka/p/41702/fukigen_na_mononokean_tsuzuki__odcinek_01
149 https://www.kuzdrowiu.com.pl/
150 https://www.limango.pl/
151 https://www.machineryzone.pl/
152 https://www.miastokobiet.pl/
153 https://www.monedo.pl/now
154 https://www.nikon.pl/pl_PL/
155 https://www.nokiantyres.pl/
156 https://www.paker.co.uk/
157 https://www.paniswojegoczasu.pl/
158 https://www.porscheinterauto.pl/
159 https://www.protan.pl/
160 https://www.raisin-sklep.pl/
161 https://www.sanatorium.mobi/
162 https://www.skef.pl/
163 https://www.spot-a-shop.pl/
164 https://www.superprezenty.pl/spektakl-i-kolacja-dla-dwojga-w-teatrze-sabat--warszawa-teatr-sabat
165 https://www.taxor.pl/
166 https://www.vans-shop.pl/
167 https://www.visa.pl/
168 https://www.woda.com.pl/
169 https://www.wzielonej.pl/
170 https://wyciskarki.pl/
171 https://xdrive-service.pl/
172 https://youngface.tv/
173 https://zlapkuriera.pl/

**Comment by krystian3w-archive-projects** [comment]
ez
