### ISSUE TITLE
musicexpress.pl/pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14671]
W nic nie da się kliknąć.

**Comment by krystian3w** [comment]
@xMaap  wina fanboya!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 🤣 

Jak dla mnie źle wyciął rodo. Spróbuj tego a zgłoszenie to może jutro.

```
musicexpress.pl##.rodo-info, .modal-backdrop
```

**Comment by krystian3w** [comment]
Jakby ktoś kiedyś chciał wyciąć jak najmniej backdropów w uBO / AG:

`##.modal-backdrop:has(~ .rodo-info)`

ABP / AdBlock tego nie wspierają.
