### ISSUE TITLE
tvsudecka.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14672]
Reklama
`https://www.tvsudecka.pl/wiadomosci/67483,kolejna-sciezka-rowerowa-w-gory-sowie
`
![Zrzut ekranu z 2019-09-14 23-06-03](https://user-images.githubusercontent.com/36385327/64913644-4b256280-d744-11e9-8750-da3fa2eaa853.png)

**Comment by krystian3w** [comment]
`tvsudecka.pl##.social > .twitter` - przegapiłeś.

`Podziel się` też do wycięcia.
