### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#14677]
https://shinden.pl/episode/2943-seirei-no-moribito/view/28919#column-one-inner

macie adblocka nawet po wyłączeniu blokad ?

**Comment by MajkiIT** [comment]
@xxcriticxx @hawkeye116477 @krystian3w

**Comment by xxcriticxx** [comment]
guzika play nie widze

![Capture](https://user-images.githubusercontent.com/15007183/64920828-ce1cdc00-d789-11e9-904e-47fdaaae0aa7.PNG)

**Comment by krystian3w** [comment]
Nie mam:

![obraz](https://user-images.githubusercontent.com/35370833/64923570-28925880-d7db-11e9-8576-453ea40bb839.png)

---

@xxcriticxx nie testuj, banują USA... (testuje US proxy by CloudFlare).

**Comment by krystian3w** [comment]
> macie adblocka nawet po wyłączeniu blokad ?

Nie, wtedy kupa reklam i działa niby wideo.

**Comment by krystian3w** [comment]
@lain566

can you update this:

`shinden.pl#@#+js(abort-on-property-write, _pop)`

https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-491094068 - source.

Maybe no needed now?

**Comment by krystian3w** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/1d44e8aa2f923004ccf193e2c7e5e83f103d2fb5
