### ISSUE TITLE
otodom.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14681]
Cookies
`https://www.otodom.pl/oferta/dom-14pokoi-hostel-przychod-15-20tys-pln-mc-ID3XmG8.html
`![Zrzut ekranu z 2019-09-15 21-05-42](https://user-images.githubusercontent.com/36385327/64926351-9b5ffb80-d7fc-11e9-98cd-659196abf3ec.png)

**Comment by krystian3w** [comment]
Nie umiem odtworzyć.

Filtr | `otodom.pl###root > footer ~ div`
--- | ---
Lista filtrów | I don't care about cookies

**Comment by krystian3w** [comment]
@hawkeye116477 nie dodawać?

**Comment by hawkeye116477** [comment]
@krystian3w Tak jak wcześniej było ustalone :smile:
