### ISSUE TITLE
ekstraklasa.tv

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14680]
Cookies
![Zrzut ekranu z 2019-09-15 21-04-32](https://user-images.githubusercontent.com/36385327/64926337-7cfa0000-d7fc-11e9-927d-7b05c0882fc6.png)

**Comment by krystian3w** [comment]
`ekstraklasa.tv##div[class^="components-CookieNotice"]`

bo to za długie i ma dziwne cyfry/litery na końcu:

`##.components-CookieNotice-___styles__cookie-notice___1vuta`

nie chciało mi się sprawdzać czy są w `web.archive.org`
