### ISSUE TITLE
nanarty.info 

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#14706]
Resztki po reklamach po prawej nad napisem `NARTY W POLSCE`.
Otwieram ponownie, bo coś zostało dodane, ale to jednak nie to, zresztą to nawet nie resztka, a wewnętrzna reklama aplikacji serwisu, więc ona raczej powinna zostać, jednakże z pośpiechu nie została dodana kropka, więc i tak to nie zadziałało. 
Radzę, by nie śpieszyć się tak, bo to na dobre nie wychodzi. Jak się nie ma czasu, to lepiej odłożyć to na później, nic nie ucieknie przecież, my poczekamy tyle ile będzie trzeba :smile:

Moja propozycja => `nanarty.info#?#.sppb-addon:-abp-has(>.sppb-addon-content>.custom)`
(może ktoś coś lepszego wymyśli bez hasa?)

**Comment by krystian3w** [comment]
`##.page-content > .sppb-section > .sppb-container-inner > .sppb-row > div[class^="sppb-col"]:nth-of-type(4) > .sppb-addon-container > div[id^="sppb-addon"]:nth-of-type(n+2):nth-of-type(-n+3) > div[class^="sppb-addon"]`

hmmm?

**Comment by hawkeye116477** [comment]
@krystian3w No też chyba jest ok. Ale zdaje się, że można to jednak nieco skrócić => `nanarty.info##div[class^="sppb-col"]:nth-of-type(4) > .sppb-addon-container > div[id^="sppb-addon"]:nth-of-type(n+2):nth-of-type(-n+3) > .sppb-addon`
