### ISSUE TITLE
irwin.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14705]

**Comment by krystian3w** [comment]
Wywala na EU, pl mam jakieś błędy o limicie czasu i jego przekroczeniu.

**Comment by hawkeye116477** [comment]
Mam ten sam problem.

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale eu nie jest po polsku i IDCAC już to ukrywa :smile:

**Comment by xxcriticxx** [comment]
@hawkeye116477 na tym kompie mam nie mam IDCAC
