### ISSUE TITLE
rossman.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14704]
`https://www.rossmann.pl/` 

https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.rossmann.pl%2F

coś miesza na rossmanie:

![obraz](https://user-images.githubusercontent.com/35370833/65055241-19441400-d96f-11e9-8ddd-6488e8fd1ed0.png) |
--- |

I efekt jest taki, że nie ma żadnej treści - biały ekran.

@gwarser coś tam co sekundę odpytuje o plik `gtm.js` i nawet plik z neutralizowany jako przekierowanie nie pomaga.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/65055452-78098d80-d96f-11e9-9b04-454f42bba885.png) |
--- |

**Comment by krystian3w** [comment]
Teoretycznie może też to być od cookies sprzed 30 dni i odwiedzenie sklepu przez US proxy Firefox / CloudFlare.

**Comment by MajkiIT** [comment]
@krystian3w chyba już jest ok.

**Comment by krystian3w** [comment]
No niby tak, niech "powisi" do 3 dni jakby komuś też się sklep po długiej przerwie zawiesił.

Nawet nie ma za bardzo jak dopuścić ładowania plik, nazwa i zmienna / atrybut taki sam.

**Comment by krystian3w** [comment]
3 dni później no to zamykam.
