### ISSUE TITLE
hmt.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#14723]
Biała plama po reklamie.
![Screenshot_20190918_142857](https://user-images.githubusercontent.com/19818572/65148599-d9d60000-da20-11e9-8e67-088d48f71918.png)

Propozycje rozwiązania:
a) `hmt.pl##div.cdp-item:nth-of-type(1):style(background-color: transparent; border: none;)`
b) `hmt.pl##div.cdp-item:nth-of-type(1)`

**Comment by xxcriticxx** [comment]
@hawkeye116477 nie bede pytal o jakiej tematyce ta strona jest

**Comment by krystian3w** [comment]
Chyba druga lepsza, jak zdjęcie jest na środku to nawet nie wygląda tragicznie.
