### ISSUE TITLE
Stepstone.pl niesłusznie zablokowane

### ISSUE THREAD

**Issue by beardedqa** [MajkiIT/polish-ads-filter#14728]
Cała domena stepstone.pl została zablokowana w https://github.com/MajkiIT/polish-ads-filter/blob/393c9fe59ed9acf18ecc808b1c36fab9468008c4/polish-adblock-filters/adblock.txt#L3597

Reguła jest niepoprawna, uniemożliwia normalne korzystanie ze strony. 

Dostarczę PR.

**Comment by beardedqa** [comment]
PR: https://github.com/MajkiIT/polish-ads-filter/pull/14732

**Comment by hawkeye116477** [comment]
Jest też na liście dla Pi-hole.

**Comment by beardedqa** [comment]
> No i jest też to na liście dla Pi-hole.

Racja, usunąłem też to. Dzięki za wskazanie :)

**Comment by hawkeye116477** [comment]
@MajkiIT Jeszcze w pihole zostało.
