### ISSUE TITLE
filmox.org

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1473]
reklama chcesz iPhone 6S? + wygraj ten telefon

http://filmox.org/baza-ksiezycowa-moonbase-online-lektor-pl-1997/

![capture](https://cloud.githubusercontent.com/assets/15007183/20271178/f3a7eb66-aa57-11e6-80d4-75a3ed4ef1f4.PNG)

**Comment by F4z** [comment]
`||vshare.io/watch_video.php$script`
`vshare.io###sendif`

**Comment by xxcriticxx** [comment]
testowalem dziala
