### ISSUE TITLE
siatka.org

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14744]
@hawkeye116477 rss ( button ), gdzie to dać ?

**Comment by hawkeye116477** [comment]
@blocker999 https://github.com/PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement

**Comment by hawkeye116477** [comment]
Label niewłaściwy, RSS nie dajemy do Sociala, więc powinno być chyba won't fix z uwagi na to, że to nie do repo @MajkiIT.

**Comment by xxcriticxx** [comment]
@hawkeye116477 dla mnie to typ social jak nie pasuje to sie zmieni

@MajkiIT jaki label dac?

**Comment by hawkeye116477** [comment]
@xxcriticxx On nie ma czasu i takimi sprawami się nie zajmuje, jego działka to reklamy. Tak jak mówię, u nas RSS to osobna kategoria. Tak czy siak,to już raczej można zamknąć :smile:.
