### ISSUE TITLE
patriotyczna.listastron.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14747]
mini RODO

**Comment by krystian3w** [comment]
`||toplista.pl/tac/pp-t-a-c.js$script,domain=patriotyczna.listastron.pl`

**Comment by krystian3w** [comment]
`http://toptorrenty.listastron.pl/`

**Comment by krystian3w** [comment]
`http://blog.listastron.pl/`

**Comment by krystian3w** [comment]
`http://pielgrzymrowerowy.listastron.pl/`

**Comment by krystian3w** [comment]
`http://hhrrr.listastron.pl/`

**Comment by krystian3w** [comment]
`http://noclegi.listastron.pl/`

**Comment by krystian3w** [comment]
`http://zawodbloger.listastron.pl/`

**Comment by krystian3w** [comment]
`http://psia.listastron.pl/`

**Comment by krystian3w** [comment]
`http://ezoteryka.listastron.pl/`

**Comment by krystian3w** [comment]
`http://vjera.listastron.pl/`

**Comment by krystian3w** [comment]
`http://igre.listastron.pl/`

**Comment by krystian3w** [comment]
`http://vgh.listastron.pl/`

**Comment by krystian3w** [comment]
i wiele wiele wiele.
