### ISSUE TITLE
zakopane.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14745]
https://www.zakopane.pl/strefa-miejska
https://www.zakopane.pl/strefa-turystyczna

@krystian3w Oddziel sociale a reszta do EI

**Comment by krystian3w** [comment]
`##.bar-menu > ul > li:nth-of-type(-n+3)`

co do reszty - bip / epuap / głuchoniemi to niech @hawkeye116477  oceni potrzebność
