### ISSUE TITLE
wbijam.pl

### ISSUE THREAD

**Issue by Zwiedzajacy** [MajkiIT/polish-ads-filter#14759]
### Zrzut ekranu

![](https://s6.ifotos.pl/img/Przechwyt_qsawqss.jpg)
![](https://s6.ifotos.pl/img/Przechwyt_qsawqsa.jpg)

### Link bezpośredni

[https://wbijam.pl](https://wbijam.pl)

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Nie bardzo się znam na waszych kodach do filtrów
2. Prosiłbym o usunięcie reklam z wbijam.pl bo są bardzo uciążliwe :(
3. Na podstronach z playerami jest 3x więcej reklam niż na głównej. [link](https://blackclover.wbijam.pl/odtwarzacz-R40XfMRMBUrd6B74_UK_IykYYSwoFQw9YaL.html)

### Moja konfiguracja
**Przeglądarka internetowa:**
Opera Wersja:63.0.3368.94
**Rozszerzenia i skrypty:**
Bloker z Opery i adblock
**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda

Strona co kilka dni coś robi, że żadne blokery nie działają i wszystkie reklamy się wyświetlają. 
**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by xxcriticxx** [comment]
@Zwiedzajacy musisz wiecej napisac o swoim blokerze na ubo jest czysto

**Comment by xxcriticxx** [comment]
cookies widze na tym linku (https://blackclover.wbijam.pl/odtwarzacz-R40XfMRMBUrd6B74_UK_IykYYSwoFQw9YaL.html) co podales

**Comment by krystian3w** [comment]
Napisał - Opera AdBlock mechanism. Czyli lipa raczej z wywaleniem reklam Google.

**Comment by krystian3w** [comment]
Znajdziesz zamykać cookies to się wytnie.

**Comment by xxcriticxx** [comment]
`###stopka_dol`

**Comment by krystian3w** [comment]
To nie zamykacz niech ci @hawkeye116477  wytnie albo zgłoś do kiboke i może doda filtr pod 1 domenę.

**Comment by krystian3w** [comment]
@Zwiedzajacy  w AdBlock / Adblock Plus wyłącz filtr / opcję **użytecznych reklam** albo **akceptowalnych reklam**. Podobnie w ustawieniach blokera Opery sprawdź czy nie dodali takiego czegoś.

**Comment by hawkeye116477** [comment]
Raczej po pierwsze to @Zwiedzajacy powinien się zdecydować, którego adblockera chce używać. Dwa na raz mogą powodować tylko problemy, to tak jakby zainstalował Avasta i Kaperskiego na jednym komputerze :smile:.

**Comment by krystian3w** [comment]
On czeka na PR a nawet nie może podlinkować pod jaką linijką mu wkleić.

**Comment by KonoromiHimaries** [comment]
jest pusta sekcje reklama po prawej na podstronach

**Comment by krystian3w** [comment]
Są a nie jest.
