### ISSUE TITLE
google.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14757]
Wandale z EasyList popsuły / popsuli usługę Google:

https://www.google.pl/intl/pl/ads/publisher/partners/find-a-partner/

```
@@.pl/ads/*/static/$stylesheet,script,domain=google.pl
```

CSS przywraca wygląd, SCRIPT interaktywną wyszukiwarkę podmiotów na stronie.

**Comment by MajkiIT** [comment]
@krystian3w Dziękuje
