### ISSUE TITLE
rozrywka.tvp.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14767]
sociale w " udostępnij " ( po lewo ) i coś blokuje filmik

https://rozrywka.tvp.pl/44551670/baron-ostrzega-przed-bednarkiem

**Comment by xxcriticxx** [comment]
github ma jakis problem labels sie nie laduja w tej chwili

**Comment by krystian3w** [comment]
daj może etykietę anty-adblock jak się odbuguje.

> <div class="tp2 tp2-widget tp2-widget-message" style="z-index: 950;"><div class="tp2thm tp2thm-layer-message tp2thm-active"><div class="tp2thm tp2thm-error-adblock"><div class="tp2thm tp2thm-error-adblock-inner"><div class="tp2thm tp2thm-header"><img class="tp2thm" src="https://s.tvp.pl/files/TVPlayer2/player2-theme-default/1.0.0-beta59/images/png/error.png" alt="Error"><p class="tp2thm">Drogi użytkowniku</p></div><p class="tp2thm tp2thm-description">Wygląda na to, że używasz dodatku do swojej przeglądarki, który blokuje nasze reklamy. Aby móc oglądać materiał, prosimy Cię o jego wyłączenie. Dziękujemy!</p><p class="tp2thm tp2thm-description">Zespół TVP</p><a class="tp2thm tp2thm-error-btn" href="https://vod.tvp.pl/page/path,26191007" target="_blank">Wyłącz blokadę</a></div></div></div><div></div><div></div></div>
