### ISSUE TITLE
facet.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1476]
reklama

http://facet.wp.pl/joanna-krupa-znow-pozuje-nago-6058459455779457g

![capture](https://cloud.githubusercontent.com/assets/15007183/20274890/50259968-aa64-11e6-9262-5ae26cd5ecc4.PNG)

**Comment by MajkiIT** [comment]
Sprawdź to ||v.wpimg.pl/$script,domain=facet.wp.pl

**Comment by MajkiIT** [comment]
@xxcriticxx zaktualizuj polskie filtry i Easylist

**Comment by xxcriticxx** [comment]
@MajkiIT po updajcie dalej mam reklamy 

`||v.wpimg.pl/$script,domain=facet.wp.pl` stym zostaja puste box ze slowem REKLAMA

**Comment by MajkiIT** [comment]
@F4z możesz zerknąć u siebie, bo u mnie jest OK.

**Comment by xxcriticxx** [comment]
tutaj tez puste boxy po REKLAMACH 

http://film.wp.pl/piekna-i-bestia-olsniewajaca-emma-watson-tanczy-z-bestia-zwiastun-6058572873434241a

**Comment by F4z** [comment]
@MajkiIT u mnie jest tak samo jako u @xxcriticxx czyli zostają te miejsca z napisem "REKLAMA".
Ta reguła u mnie działa:
`facet.wp.pl,film.wp.pl##[class="qd-US"]`

**Comment by MajkiIT** [comment]
@F4z dziękuje
