### ISSUE TITLE
anime-odcinki.pl 

### ISSUE THREAD

**Issue by Zwiedzajacy** [MajkiIT/polish-ads-filter#14768]
### Zrzut ekranu
![image](https://user-images.githubusercontent.com/55771503/65690703-e76a3600-e06f-11e9-8d4a-b88c9318219d.png)

### Link bezpośredni
https://anime-odcinki.pl

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Na głównej slider z ostatnimi odcinkami PL powinien mieć 2 rzędy, adblock najnowszy rozwalił css lub coś blokuje czego nie powinien.
2. Strona nie ma już wyskakujących okienek na głównej, artykułach i szukajkach, 1 jest na podstronach z playerami. 
3. Mimo iż mam zaznaczoną opcję "Zezwalaj na nienatrętne reklamy" nie wyświetlają mi się żadne banerki zgodne z wyświetlaniem się, bo raczej mają standardowe wymiary.

### Moja konfiguracja
Wersja 77.0.3865.90 (Oficjalna wersja) (64-bitowa)
Firefox 69.0.1 (64 bity) na u-block ten sam problem, identyczny. 

**Rozszerzenia i skrypty:**
Mam tylko adblock  i nic więcej.

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Coś nie tak się dzieje z stroną główna powinna wyglądać tak:
https://s6.ifotos.pl/img/Przechwyt_qsassne.jpg
+ Zezwalaj na nienatrętne reklamy raczej tam nie działa.
Byłbym wdzięczny za sprawdzenie który filtr za to odpowiada i możliwą naprawę.
Pozdrawiam

**Comment by MajkiIT** [comment]
U mnie jest OK

**Comment by krystian3w** [comment]
U mnie niby też, liczenie rzędów to trochę lipa.

**Comment by krystian3w** [comment]
> Mam tylko adblock i nic więcej.

wyłącz i postestuj ublock Origin?

**Comment by Zwiedzajacy** [comment]
@krystian3w ok, włączyłem firefoxa bez dodatków, zostawiłem włączone U-block Origin i z u-block wygląda tak: https://s6.ifotos.pl/img/01JPG_qsaahpq.jpg a bez ublocka tak: https://s6.ifotos.pl/img/02JPG_qsaahhp.jpg 
To samo się robi przy chrome z zwykłym adblockiem bez żadnych (plus) itp.
Co do str głównej i rzędów to tak:
- Odcinki emitowane PL: 2 rzędy
- Odcinki emitowane ENG: 1 rząd
- Filmy ANIME PL: 1 rząd
- Filmy ANIME ENG: 1 rząd
- Ostatnio dodane (starsze sezony): rzędy
Tak powinno to wyglądać: https://s6.ifotos.pl/img/screensho_qsaahhh.png

Jest to ewidentnie jakiś błąd filtrów bo jak wyłączam adblocka czy u-blocka to strona wraca do normy :(

**Comment by MajkiIT** [comment]
@Zwiedzajacy To kwestia zapewne filtrów. Wyłączaj po kolei i sprawdzaj.

**Comment by krystian3w** [comment]
Może trzeba tam dopuścić skrypt fuck adblock 3.2 podobne było z ich starą domeną.

**Comment by krystian3w** [comment]
```
@@||anime-odcinki.pl/wp-content/plugins/jgc-adblocker-detector/js/jgcabd-detect-adblock.js$script
```

EasyList blokuje to nie sądzę by Eyeo nam odmówiło po dopuszczeniu pomocy.

**Comment by krystian3w** [comment]
Zadziała też:

`*/jgcabd-detect-$script,redirect=nofab.js`

**Comment by krystian3w** [comment]
Działają też badfilter:

```
/jgcabd-detect-$badfilter
/jgc-adblocker-$badfilter
-adblocker-detector/$badfilter
-detect-adblock.$badfilter
```

@gwarser mam bug:

> ![obraz](https://user-images.githubusercontent.com/35370833/65784731-0261a680-e153-11e9-94cf-6f6e8c47353a.png) |
> --- |

uBO twierdzi po dodaniu badfilter że niby mam generyk a ja neguję go tylko.

Jak odtworzyć:

1. filtrujemy w rejestratorze tak, by pokazał jeden z 4 "generyków" EasyList
2. do filtrów własnych wklejamy to co wyżej podałem
3. klikamy w starą detekcje i jakiś "regex" nawala i pokazuje, że niby i w moje filtry mam problematyczną regułę...

**Comment by Zwiedzajacy** [comment]
Da się coś zrobić? czy jeszcze pracujecie nad tym?

**Comment by krystian3w** [comment]
Nie wiem czy ktoś pracuje, dodaj sobie do filtrów własnych to i problem zniknie:

`@@||anime-odcinki.pl/wp-content/plugins/jgc-adblocker-detector/js/jgcabd-detect-adblock.js$script`

**Comment by Zwiedzajacy** [comment]
Ale nie chodzi o mój problem, tylko globalnie jakiś filtr psuje serwis, pisze w imieniu portalu. Moderuje tam.  Bardzo proszę o naprawę tego problemu bo nie został rozwiązany :/

**Comment by krystian3w** [comment]
Naprawiony dla użytkowników uBlock Origin, skrypty pierwszoplanowe dopuścili w całości.

Filtrów tych EasyList nie zamierza usunąć:

```
/jgcabd-detect-
/jgc-adblocker-
-adblocker-detector/
-detect-adblock.
```

@olegwukr dodaj to dla ABP / AdBlock i AdGuard:

```
@@||anime-odcinki.pl/wp-content/plugins/jgc-adblocker-detector/js/jgcabd-detect-adblock.js$script
```

Oczywiście użytkownicy ABP / AdBlock i AG muszą to przeczytać: 

https://www.certyficate.it/polskie-filtry-anti-adblock-brak-wsparcia-w-polskich-filtrach-szanowni-nasi-drodzy-od-07-12-2018-nastapia-zmiany-w-oficjalnych-polskich-filtrach/

---

> I dziwne, że moderatorom nie piorą mózgów by odradzali blokowanie wszelkich reklam...

**Comment by Zwiedzajacy** [comment]
@krystian3w potwierdzam, na uBlock Origin jest już OK :)

**Comment by Zwiedzajacy** [comment]
A jednak nie do końca, dla zalogowanych działa, po wylogowaniu ze strony już nie, czyściłem cache przeglądarki jak coś i to samo.

**Comment by krystian3w** [comment]
Ja się w cale nie loguję i działa, uBO też nie chce widzieć nowego zgłoszenia by użyli:

```
anime-odcinki.pl##+js(nofab.js)
```

**Comment by Zwiedzajacy** [comment]
Swoją drogą adblock i u-block powinien też kasować informację o RODO i cookies?  Jak tak to nie było pytania, jak nie to blokuje xD

**Comment by krystian3w** [comment]
> Swoją drogą adblock i u-block powinien też kasować informację o RODO i cookies?

**Domyślnie nie**, widać nie masz filtrów `RODO-ciasteczkowych` i `I Don't Care About Cookies` (boże i te amerykańskie kapitaliki...) zasubskrybowanych.

---

Wykluczam opcje, że jest wyciek cookies/rodo na anime-odcinki.pl - tak robi tylko Google i WP...

**Comment by Zwiedzajacy** [comment]
@krystian3w  Jednak serio nie działa jak powinno, tylko dla zalogowanych jest ok, dla niezalogowanych główna się rozwala czy tam css..
Sprawdziłem z mojego drugiego PC i z SHELL dla pewności, aktualizowałem uBlock Origin 1.22.4 i cache przeglądarki i ciągle jest bez zmian główna zepsuta. Testowałem na uBlock Origin 1.22.4 i Firefox 69.0.1 (64 bity).  
Na chrome 77.0.3865.90 i adblock 3.55.1 to samo. 
Testowałem beż innych wtyczek niż blokery wymienione wyżej.

**Comment by krystian3w** [comment]
Zbyt ogólnikowe, nagraj wideo i na nie nanieś etykietki z opisami co i kiedy jest popsute.

**Comment by Zwiedzajacy** [comment]
Na firefoxie łap, wgrałem na mega bo bez reklam itp xD https://mega.nz/#!9pMiiYgY!_UEHs37ZLpgIZ4E2c-L6nMVun3ZJ3nMGgEwMUmzaZA4
na google drive też mogę wgrać.  Nie wiem czy jest sens na chrome to samo nagrywać bo identycznie się zachowuje.

**Comment by krystian3w** [comment]
Problem jaki widzę, to brak wejścia do uBO i aktualizacji filtrów w nim, niby są interwały 7 godzinne (czy kij wie jakie), pewnie świeża instalacja ma zassane w kodzie filtry sprzed 2-3 dni, nie wiem jakie będzie miała wersja 1.22.4 (nie sprawdzałem czy ona jest z dzisiaj czy może od 2-3 dni).

**Comment by Zwiedzajacy** [comment]
Patrzyłem na firefox to u-block już naprawiony, jeszcze zwykły adblock został :)

**Comment by Zwiedzajacy** [comment]
Naprawi to ktoś?

**Comment by xxcriticxx** [comment]
nope

**Comment by Zwiedzajacy** [comment]
Czemu? przecież to filtry adblock sprawiają problemy :( a tu się zgłasza tego typu problemy do naprawy.  Przecież nie może tak zostać na zawsze xD

**Comment by krystian3w** [comment]
Jak @olegwukr nie dokopiował to dla ABP / AdBlock nie będzie ratunku jak ręczne dodawanie wyjątku pod skrypt `F**ck Adblock 3.2.1`.

---

@olegwukr  i anime odcinki chyba wymagają `generichide` tak by skrypt nie reagował na jakieś 10 generyków z EasyList jak jeszcze nie mamy.
