### ISSUE TITLE
swiatrolnika.info

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14773]
Social + cookies
![2019-09-28 07 53 43 www swiatrolnika info 8f81c41a9ade](https://user-images.githubusercontent.com/36385327/65812277-2a89ed80-e1c5-11e9-9b7f-b8bedcf7fbde.png)

**Comment by krystian3w** [comment]
```
##body > div#rodo:not([style*="fixed"]):not([class*="modal"])
```
