### ISSUE TITLE
ticketos.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14772]
![2019-09-28 07 52 58 ticketos pl f6575cdbe03f](https://user-images.githubusercontent.com/36385327/65812265-07f7d480-e1c5-11e9-8991-865cafd0a0a8.png)

**Comment by krystian3w** [comment]
Może migać, losowe klasy, trzeba wymuszać wyszukiwanie "RODO" w tekście by nie wyciąć za dużo pop-upów jednym filtrem.
