### ISSUE TITLE
zmiksowani.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14788]
![Capture](https://user-images.githubusercontent.com/15007183/65820451-3a222a00-e1f7-11e9-904b-5a4e6cfccf2a.PNG)

**Comment by krystian3w** [comment]
`@@||zmiksowani.pl/script/ads.js`

Ale to za mało, uBO blokuje dynamiczne ładowanie innych artykułów...
