### ISSUE TITLE
gameinn.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14789]
W nic nie da się kliknąć.

**Comment by krystian3w** [comment]
Proszę "wywalić" Fanboy cookie list, on ma generyk co wywala newslettery jako cookies/rodo/politykę prywatności a nimi nie są.

Nawet to go nie przekonuje: https://github.com/ryanbr/fanboy-adblock/issues/976
Chyba olał i nie otwiera by nie urazić autora, że ma to w 4 literach.

**Comment by krystian3w** [comment]
A najlepsze, że z 100 domen tło dociął ręczenie a nie użył opcji negacji filtru.

**Comment by krystian3w** [comment]
proszę o zmianę na "błąd filtrów zewnętrznych".

Oraz usunięcie etykiety cookies.

![obraz](https://user-images.githubusercontent.com/35370833/65835763-71253800-e2ea-11e9-8775-4ddb8fa5485b.png) |
--- |


@xMaap pobierz nowe EI i możesz zamknąć wątek.

**Comment by hawkeye116477** [comment]
`Chyba olał i nie otwiera by nie urazić autora, że ma to w 4 literach.`
Ale wątek jest otwarty...

**Comment by krystian3w** [comment]
Ale ile miesięcy, filtr powinien po prostu wywalić a nie słuchać smed79 jak go wygenerował/a...

**Comment by xMaap** [comment]
To chyba można zamknąć.
