### ISSUE TITLE
kolporter.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14783]
coś zadużo wycina na głównej

**Comment by krystian3w** [comment]
Padła im strona hahahaha...

**Comment by krystian3w** [comment]
Nie, niby czemu, nic nie mają ciekawego na głównej to Majki wyciął reklamę, ubocznie RODO, 6 innych filtrów jest na blokadę śledzenia.

**Comment by krystian3w** [comment]
Ja bym nie przywracał tego baneru, lepiej jak jest wycięty.

**Comment by MajkiIT** [comment]
@krystian3w OK, dzięki
