### ISSUE TITLE
poczta-polska.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14782]
brak tego przelicznika sprzedaj/kup ( na czerwonym tle )

**Comment by krystian3w** [comment]
Za mało danych, nie każdy online używa poczty-polskiej.

**Comment by krystian3w** [comment]
Poza tym to wygląda na celową blokadę:

```
||rkantor.com/widget/$script
```

https://github.com/MajkiIT/polish-ads-filter/blob/7ae60bb40a11f6cba5c3a429e5938cb812edccc3/polish-adblock-filters/adblock.txt#L3558

Czyli won z kantorem, jak na poczcie ci waluty nie wymienią, kursy znajdziesz też na NBP.
