### ISSUE TITLE
gracz.org

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14792]
`https://gracz.org/z-cyklu-wspomnienia-gracza-21-tekken-tag-tournament/
`
Reklama
![2019-10-01 06 19 40 gracz org 87ebb20be585](https://user-images.githubusercontent.com/36385327/65933859-7b8f2100-e413-11e9-8817-915b465e598c.png)
![2019-10-01 06 20 25 gracz org 6cd665a1d137](https://user-images.githubusercontent.com/36385327/65933877-93ff3b80-e413-11e9-8114-acf81e41af62.png)

**Comment by MajkiIT** [comment]
`###custom_html-4`

**Comment by krystian3w** [comment]
`###custom_html-4, #custom_html-12`

**Comment by krystian3w** [comment]
oba raczej, a nie tylko ze stopki.
