### ISSUE TITLE
magazyngitarzysta.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14793]
Reklama
`https://magazyngitarzysta.pl`
![2019-10-01 06 32 56 magazyngitarzysta pl bb7efd79bc71](https://user-images.githubusercontent.com/36385327/65934371-661af680-e415-11e9-9b68-043583943e17.png)
![2019-10-01 06 33 54 magazyngitarzysta pl bd2a5652c2cc](https://user-images.githubusercontent.com/36385327/65934388-7632d600-e415-11e9-98ac-bf47bbfd1e37.png)

Social
```
https://cozaile.pl
https://informatorbudownictwa.pl
https://audio.com.pl
```
![2019-10-01 06 34 39 cozaile pl 875824f9a47e](https://user-images.githubusercontent.com/36385327/65934465-df1a4e00-e415-11e9-9684-031aba8e2bcc.png)

`https://czasnawnetrze.pl`
![2019-10-01 06 41 18 czasnawnetrze pl 7fa004696b47](https://user-images.githubusercontent.com/36385327/65934624-7da6af00-e416-11e9-91a4-390e28c9b376.png)

**Comment by MajkiIT** [comment]
`magazyngitarzysta.pl##.transition-all.site-canvas > div > A`

**Comment by krystian3w** [comment]
Albo

`||cdn.avt.pl/webs/*/750x250_*.jpg`

propocja wskazuje, że to zawsze będzie reklama, niby 3 obrazki już są "zablokowane" czyli nawet `||cdn.avt.pl/webs/` może jest tylko do reklam...?
