### ISSUE TITLE
tvn24.pl

### ISSUE THREAD

**Issue by Tasiorsa** [MajkiIT/polish-ads-filter#14794]
### Zrzut ekranu
![videotvn24](https://user-images.githubusercontent.com/35109319/65954140-b01bd080-e445-11e9-84c4-53951ffe5f68.png)

### Link bezpośredni
https://www.tvn24.pl/barwy-kampanii-relacja-z-kampanii-wyborczej-wybory-parlamentarne-2019,973696,s.html
-->

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Otworzyć jakikolwiek materiał w którym jest film - zamiast filmu zobaczymy napis Materiał Niedostępny

### Moja konfiguracja
**Przeglądarka internetowa:**
Firefox 69.0.1
**Rozszerzenia i skrypty:**
Nano Adblocker + Nano Defender

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Wszystkie filtry MajkiIT
4. Filtry przeciwko Adblock

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
?

**Comment by Tasiorsa** [comment]
Po otwarciu dowolnego artykulu na www.tvn24.pl nie idą dołączone do artykułu nagrania. Przy wyłączonym Nano Adblocker idą. Idzie najpierw reklama potem materiał. Gdy mam wlacxzony nano Adblocker + nano Defender wyskakuje od razu material jest niedostepny.

**Comment by krystian3w** [comment]
> Piotr Marciniak...


 *  https://support.mozilla.org/pl/kb/ochrona-przed-sledzeniem

 *  https://support.mozilla.org/en-US/kb/tracking-protection

u mnie leci bez aktywnego ND (ani z AMO, ani z Github releases).

**Comment by Tasiorsa** [comment]
U mnie nie leci nawet jak przełączyłem ze standardowe na własne i odfajkowałem wszystko :(

**Comment by krystian3w** [comment]
Wyczyść cookies / localstorage / cache spod okienka certyfikatu?

**Comment by Tasiorsa** [comment]
DNS adguard nie pomógł.
Test Firefoxa wyszedł Good we wszystkich pozycjach
Wyczyszczenie cache i cookies nie pomoglo.
Pomaga jedynie wylaczenie NanoAdblocker

**Comment by krystian3w** [comment]
Eksport ustawień ND, eksport filtrów własnych do osobnego pliku.

---

Wywalić AG i ND, zainstaluj wersje z AMO:


https://addons.mozilla.org/pl/firefox/addon/nano-adblocker-firefox/
https://addons.mozilla.org/pl/firefox/addon/nano-defender-firefox/

---

I potem zacznij od przywrócenia swoich filtrów własnych, następnie od dodania filtrów:

- RODO/Cookies + IDCAC
- SOCIAL / EI jak używasz
- jakieś z listy w Nano (np. AdGuard Base)
- własne jakieś dziwne

**Comment by Tasiorsa** [comment]
reset nano Adblocker do domyslnych odblokowal filmy. De dodawac pojedynczo filtry MajkiIT

**Comment by krystian3w** [comment]
Jak masz czas na ręczne deaktywowanie to ok.

Logger ma funkcje zbierania w listę, ale dowala do kopiowania cyfry niepotrzebnie...

**Comment by Tasiorsa** [comment]
Dziwne po resecie do default i dodaniu wszystkich majkiIT i kilku wlasnych jest OK. Temat rozwiazany.
Pozdrawiam i dzięki Krystian za pomoc

**Comment by krystian3w** [comment]
@adamWr sprawdzisz gdzie trzeba dodać not `ublock`?

**Comment by AdamWr** [comment]
A jakie reguły widoczne są w loggerze?

**Comment by krystian3w** [comment]
```
||gemius.pl^
/pix.gif?
||adocean.pl^
||googletagmanager.com/gtag/$third-party
@@||youtube.com/api/stats/watchtime?$domain=youtube.com
||youtube.com/api/stats/qoe?
||doubleclick.net^
@@||tvn24.pl^$generichide
##+js(abort-on-property-write, Vublock)
||google-analytics.com/analytics.js
@@||gemius.pl/gstream.js
||tvn.pl/sweqevub.js
###adocean-screening-layer
##.ads
||facebook.com/tr/?
||log.pinterest.com^$third-party
||twitter.com/i/jot
```

**Comment by AdamWr** [comment]
Ok, dziękuję za odpowiedź.
Z uBO i włączoną listą AdGuard Base nie potrafię tego odtworzyć w Chrome i Firefoksie.
Z Nano nie korzystam.

Mogę wykluczyć regułę, jak będę wiedział, która powoduje problem.

**Comment by krystian3w** [comment]
`||adform.net^$badfilter` + Z EasyList aktywnym.

tylko czemu ten z AG base by działał

**Comment by krystian3w** [comment]
Dobra, ja się poddaje, co 2 odświeżenie z pominięciem cache mam błąd jak mam tylko tyle filtrów:

![obraz](https://user-images.githubusercontent.com/35370833/65960849-abf7af00-e455-11e9-93a4-cd8213e82cba.png) |
--- |

Normalnie mam więcej list i chyba 99% odświeżeń ładuje film.

**Comment by Tasiorsa** [comment]
U mnie tez niestety raz dziala raz nie...I jedna z TVN24 sie laduja inne nie. Np z podstrony Szklo kontaktowe wcale :)

**Comment by krystian3w** [comment]
Mnie `szkło` się ładuje, filmy tam też. Ale używam AdGuard Base / Annoyance / Anti-Tracking.

Może to pomoże: https://greasyfork.org/pl/scripts/390159-player-pl

**Comment by Tasiorsa** [comment]
Usunalem Nano Adblocker wgralem Adguard i jest OK. Powiedz mi przy adguard musi zostac Nano Defender czy jest zbędny?

**Comment by krystian3w** [comment]
Raczej jest zbędny. Też jest większa szansa, że unikalne skrypty AG będą się kłóciły z ND.

Upewnij się tylko, że masz w nim już aktywowane "Polish antiadblock filters" i na część anty-adblocków również "AdGuard Annoyance" ("AdGuard filtry elementów irytujących").

**Comment by Tasiorsa** [comment]
Dziękuje. Powłączałem wszystkie Polskie i dziala bardzo ladnie

**Comment by xxcriticxx** [comment]
@krystian3w co ten twoj script robi?

**Comment by krystian3w** [comment]
Oszukuje TVN że reklamy się załadowały i na prawie każdym wideo TVN eksperymentalnie odblokowuje prawy klawisz myszy:

wtedy jak wideo jest w html5 to mogę zmienić szybkość odtwarzania, używać zapętlenia trybu PiP na Chrome czy też eksperymentalnie w Firefox 68+: https://www.ghacks.net/2019/04/22/firefox-68-picture-in-picture-mode-for-video/

**Comment by xxcriticxx** [comment]
@krystian3w dodaj to voddownloader

**Comment by krystian3w** [comment]
A ten: https://greasyfork.org/pl/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod

```
ipla.tv
player.pl
tvp.pl
cda.pl
atmcdn.pl
redcdn.pl
wp.pl
wp.pl
vod.pl
ninateka.pl
arte.tv
pulsembed.eu 
regionalne:(bialystok|katowice|lodz|rzeszow|bydgoszcz|kielce|olsztyn|szczecin|gdansk|krakow|opole|warszawa|gorzow|lublin|poznan|wroclaw).tvp.pl
```

https://github.com/zacny/voddownloader

**Comment by krystian3w** [comment]
Zacny jako jedyny aktualizuje a nie jak dwóch że od roku lub dwóch są popsute.

**Comment by xxcriticxx** [comment]
dokladnie cos tam dlubie od czasu do czasu

**Comment by xxcriticxx** [comment]
btw pingwin dalej supportuje nano?

**Comment by krystian3w** [comment]
Tak, "raz na miesiąc" jakaś nowa wersja jest, choćby z powodu wp dodał usuwanie blura i wymuszanie przewijania w domenie WP.pl

**Comment by ggargul** [comment]
> AdamWr: https://github.com/MajkiIT/polish-ads-filter/issues/14794#issuecomment-536999719 : Mogę wykluczyć regułę, jak będę wiedział, która powoduje problem.

Ta powoduje: `@@||tvn.adocean.pl/*ad.xml$xmlhttprequest,domain=player.pl|tvn24.pl` bo po dodaniu `,badfilter` filmy się odtwarzają.

**Comment by AdamWr** [comment]
Ok, w takim razie wykluczę tę regułę z listy dla uBO.
Dziękuję.
