### ISSUE TITLE
cda.pl

### ISSUE THREAD

**Issue by pepek1122583** [MajkiIT/polish-ads-filter#14806]
### Zrzut ekranu

![image](https://user-images.githubusercontent.com/21297574/66222472-837be900-e6d1-11e9-89ca-c6f231769274.png)
### Link bezpośredni

https://www.cda.pl/video/300149749?wersja=1080p
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Jakikolwiek filmik włączyć 

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome
**Rozszerzenia i skrypty:**
![image](https://user-images.githubusercontent.com/21297574/66222554-b9b96880-e6d1-11e9-9c35-f5ed5613b3ac.png)

AdBlock Plus
Steam Inventory Helper 
Distill
Stylish
Spigot Search Engine
Twitch5
BetterTTV
**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Stylus zamień na Stylus by nie sprzedawali twojej historii przeglądania?

**Comment by xxcriticxx** [comment]
adblock plus zamien ublock origin

**Comment by MajkiIT** [comment]
@pepek1122583 Zamień Adblocka tak jak pisał @xxcriticxx na uBlock Origin. Jeśli jednak jesteś bardzo przywiązany to zaktualizuj filtry i sprawdź poprawkę.

**Comment by pepek1122583** [comment]
Dla mnie jeden diabeł :D byle by mnie to działało :X ale to kwestia braku doinformowania :X

**Comment by pepek1122583** [comment]
na uBlock origin działa. ABP usuniety, stylish zmieniony na stylus
dziekuje
