### ISSUE TITLE
philips.pl/c-m-so/telewizor

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14801]
![2019-10-03 14 30 07 www philips pl 5c34d8cc54a8](https://user-images.githubusercontent.com/36385327/66126678-53a5e600-e5ea-11e9-86f0-b12b3d72ffd6.png)

**Comment by krystian3w** [comment]
@hawkeye116477 takie coś wywalam:

```
philips.pl##.p-open.p-panel
```

psuje prawy widget "nawigacyjny".
