### ISSUE TITLE
menshealth.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14814]
Napisy " reklama " w artykułach, np: https://www.menshealth.pl/sprawy/Jesienne-prace-ogrodowe,13999,1

**Comment by MajkiIT** [comment]
`www.menshealth.pl##.side-right > p`

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/66270834-1e9ecb00-e858-11e9-9969-ace9669cdb19.png)

https://www.womenshealth.pl/welcome-page,Dietology,13382

**Comment by krystian3w** [comment]
> `www.menshealth.pl##.side-right > p`

na `kobiece zdrowie` / `świecie biegaczy` to samo @MajkiIT
