### ISSUE TITLE
radioopornik.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14810]
sociale ( na dole )

**Comment by krystian3w** [comment]
Na górze też, czas chyba na optometrystę nadchodzi.

**Comment by krystian3w** [comment]
Po odświeżeniu już wycina Fanboy, widać strona zbugowana, raczej kolejne filtry nie przyśpieszą.

**Comment by krystian3w** [comment]
Opcjonalnie do filtrów własnych:

`||scmplayer.co/script.js$script,domain=www.radioopornik.eu` widać za bardzo player buguje stronę.

**Comment by krystian3w** [comment]
ja bym poprosił też o etykietę błąd jakiś plugin się nie ładuje z prawej kolumny:

![obraz](https://user-images.githubusercontent.com/35370833/66257810-de7b1200-e79d-11e9-8d80-5c000d851039.png) |
--- |
