### ISSUE TITLE
ugporaj.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14825]
RODO i FB ( u góry )

**Comment by krystian3w** [comment]
`###fancybox-wrap:-abp-contains(iod), #fancybox-overlay`

@gwarser, to jest poprawne dalej...?

**Comment by gwarser** [comment]
> `###fancybox-wrap:-abp-contains(iod), #fancybox-overlay`
> 
> @gwarser, to jest poprawne dalej...?

Lepiej unikać. Coś w rodzaju - "zachowanie niezdefiniowane".
