### ISSUE TITLE
Reklamy na Wp

### ISSUE THREAD

**Issue by DajMiliona** [MajkiIT/polish-ads-filter#14849]
### Zrzut ekranu

![2019-10-08_21h47_38](https://user-images.githubusercontent.com/39501742/66427984-6880e000-ea15-11e9-83d2-b2f9ed68e41d.png)

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Jak pozbyc sie reklamy zaznaczonej kwadratem?
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**
Firefox
Windows 7

**Rozszerzenia i skrypty:**

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
uAsset wyłączyło filtr trzeba by poprosić by wywalili. 
Opcjonalnie zaryzykować z inną wartością: `false` / `falseFunc` / `undefinied` / `''` / `null`.

I wtedy dla `www.wp.pl` by można aktywować, na głównej nie walą pop-upem o swoich pasjach.

Pod subdomeny to raczej będzie męczarnia jak nie chce się za dużo ubić na stronie.

```
finanse.wp.pl##div[class]:has(> img[src^="https://v.wpimg.pl/"] + div > *:empty)
finanse.wp.pl##div[class]:has(> img[src^="https://v.wpimg.pl/"] + div > * > *:empty)
```
```
www.wp.pl##div[class*=" "]:has(> img[src*="//v.wpimg.pl/"] + div:empty)
```

i problem, że już mamy wątek zbiorczy:  https://github.com/MajkiIT/polish-ads-filter/issues/13818

**Comment by xxcriticxx** [comment]
wszystkie posty wp.pl pod https://github.com/MajkiIT/polish-ads-filter/issues/13818
