### ISSUE TITLE
ebay-kleinanzeigen.de [incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#1484]
https://www.ebay-kleinanzeigen.de/s-lcd-fernseher-defekt/k0
Search results not shown
Screenshot
<details>
![image](http://img.ii4.ru/images/2016/11/18/792806_kiss_58kb.png)
</details>
Caused by:

```
~box.com,~hardcorowo.pl,~gumtree.com,~hulu.com,~svobodneforum.cz##[class^="ad-"]
```

**Comment by Alex-302** [comment]
The same issue:
http://www.gebraucht-kaufen.de/angeln-defekt

**Comment by MajkiIT** [comment]
@Alex-302 Fixed. Thanks
