### ISSUE TITLE
Polskie filtry w blokerze Slimjet 24 / Slimbrowser 11

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#14846]
Ich aplikacja zwraca błąd, że nie może pobrać filtrów, moje podejrzenia:

> https://github.com/MajkiIT/polish-ads-filter/blob/6006076d32dd1128829026638fd8cdd3d042e043/polish-adblock-filters/adblock.txt#L1

lub

> https://github.com/MajkiIT/polish-ads-filter/blob/6006076d32dd1128829026638fd8cdd3d042e043/polish-adblock-filters/adblock.txt#L3621  <br> inne widzę nie działały bez "important" lub nie da się pogodzić dopuszczenia by zachować wsparcie dla AdGuard / starych AdBlocków i ABP (czyli np. takie co nie wspierają nawet `-abp-has` i `-abp-contains`).

[adblocker filter lists.txt](https://github.com/MajkiIT/polish-ads-filter/files/3703672/adblocker.filter.lists.txt)

**Comment by hawkeye116477** [comment]
W tabelce jest zgodność i nie ma Slimjeta, więc zakładam, że „no support for Slimjet, sorry".

**Comment by krystian3w** [comment]
No mnie zaskoczyło, że aż tam by trzeba sięgać po EasyList Polish.

**Comment by KonoromiHimaries** [comment]
```
https://spyware.neocities.org/articles/slimjet.html
```

**Comment by hawkeye116477** [comment]
Ta, o Waterfoksie też pisze, że niby wysoki poziom szpiegostwa, że zbiera informacje o systemie, itd. No sorry, ale jak ma aktualizacja działać bez zbierania info o systemie? Ten gość co to pisał nie ma kompletnie pojęcia na czym to wszystko polega :stuck_out_tongue:

**Comment by xxcriticxx** [comment]
najlepiej zamontowac netscape
