### ISSUE TITLE
vod.tvp.pl

### ISSUE THREAD

**Issue by SebaK666** [MajkiIT/polish-ads-filter#14848]
Title: Official Polish Filters for AdBlock, uBlock Origin & AdGuard

Aż dziw, że tego nikt nie zauważył:
Włączony:
![vod1](https://user-images.githubusercontent.com/33153803/66417951-64e35e00-ea01-11e9-86a8-b14d795c748f.jpg)

Wyłączny:
![vod2](https://user-images.githubusercontent.com/33153803/66417977-72004d00-ea01-11e9-9bbc-8c7ec357455d.jpg)

Brak suwaka wideo i przycisku pełnego ekranu

**Comment by krystian3w** [comment]
Może się po prostu tam telewizji nie ogląda, nikt raczej raz dziennie nie odwiedza 2 tysięcy domen dla codziennej korekty filtrów.

**Comment by krystian3w** [comment]
Co do problemu to ja mam "pasek": 

https://vod.tvp.pl/video/o-mnie-sie-nie-martw,odc-4xi,44332877

![obraz](https://user-images.githubusercontent.com/35370833/66418643-cf48ce00-ea02-11e9-9e90-3be8f4fdec6c.png)


ty masz widać ich starszy rodzaj playera (TVP nie umie raz a dobrze zmienić wszystkich...).

**Comment by SebaK666** [comment]
Teraz używam przeglądarkę Serpent na bazie Firefox - bo dla mojego XP Firefox nie jest już aktualizowany. Dla niektórych domen zmieniam sobie general.useragent.override Ale Nawet ustawiony dla Win 10 na vod.tvp nie mam takich dodatkowych opcji playera jak u Ciebie. A te filtry dla Ublock Origin działają dobrze, tylko że mam ostatnią możliwą wersję 1.17.4. Ale w filtrze coś blokuje, skoro przy wyłącznym mam suwak, a przy włączonym nie.

**Comment by krystian3w** [comment]
Spróbuj uruchomić logger i w nim potem taki przycisk: `</>`

pokaże ci użyte filtry i skoro to "Firefox" to i może podświetli na czerwono player.

**Comment by SebaK666** [comment]
Z tego co widzę, to dla tego filtra wychodzi że gemius. Jest to możliwe?

![vod3](https://user-images.githubusercontent.com/33153803/66421641-81cf5f80-ea08-11e9-914c-042a2c2da4b2.jpg)

**Comment by krystian3w** [comment]
Raczej wątpię:

```
||gemius.pl^$badfilter
||gemius.pl^$domain=~gemius.pl
```

ja mam dezaktywowane ręcznie banowanie domeny jak celowo ją otwieramy.

**Comment by krystian3w** [comment]
No i w sumie przydałyby się te żółte jak taki ci nie pomaga:

`tvp.pl#@#[class$="-ads"]`

**Comment by SebaK666** [comment]
Exactly. This is it. 
tvp.pl#@#[class$="-ads"] powoduje pokazania się suwaka. To było to.

W ogóle ten player mają trochę skopany. Nawet przy wyłączonym adblocku nie można przesuwać filmu - chociaż przyciski dźwięku, pełnego ekranu działają prawidłowo.
Dzięki za pomoc.

**Comment by krystian3w** [comment]
Ogólnie to oni mają własną technologię do przyśpieszania czy spowalniania odtwarzania.

Jak używam API przeglądarki to po reklamie wciśniętej pomiędzy wideo szybkość mi się resetuje (reklama jest zazwyczaj między 1/4 a 3/4 wideo).

**Comment by SebaK666** [comment]
Na tym alternatywnym playerze też blokuje reklamy, jest tylko chwilowy przeskok i film idzie bez reklamy w trakcie. Chociaż kiedyś pamiętam było całkowicie bez tego nawet przeskoku.

**Comment by xxcriticxx** [comment]
voddownloader This is it.

**Comment by krystian3w** [comment]
Tak czy siak lepiej filtr wyłączyć na tvp to trochę zbyt mocny generyk jak widać.
