### ISSUE TITLE
expresskaszubski.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14856]
Reklamy

**Comment by MajkiIT** [comment]
Nie widzę tego :(

**Comment by blocker999** [comment]
Bo to sprytne artykuły reklamowe podpisane drobnym drukiem " reklama ": niebieski balonik ... , damian jarzębiński, stanisław lamczyk i radomir  szumełda, jeśli to możliwe daj jakąś ogólną regułe na tego typu artykuły bo te zaraz znikną a pojawią się nowe.

**Comment by MajkiIT** [comment]
`##div.box-margin.col-sm-6.col-md-6  > .title > span`

**Comment by krystian3w** [comment]
To nie ukrywa reklam a napisy.

**Comment by krystian3w** [comment]
Jak usuwamy tylko "Resztkę reklamową" to może jednak sprawdzanie tekstu;

`#?#.title > span:-abp-contains(REKLAMA)`

ma 3 detekcje i jak nie przymuli strony to "bezpieczniejsze"

---

`.col-sm-6.col-md-6` - to jest też w wariancie: `.col-sm-4.col-md-4`.
