### ISSUE TITLE
porażka roku

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14866]
![Capture](https://user-images.githubusercontent.com/15007183/66517116-894a4380-eab0-11e9-8937-cc07972d3284.PNG)

**Comment by hawkeye116477** [comment]
Brave też ma adblockera i ma reklamy, usuwają reklamy konkurencji i dodają własne :smiley:
Tylko, że tam akurat jest to opcjonalne i za oglądanie dają kryptowaluty (https://cryptomaniak.pl/przegladarka-brave-rozdaje-darmowe-kryptowaluty-bat/).

**Comment by xxcriticxx** [comment]
@hawkeye116477 nope still iphone dostalem wczoraj telefon androida na dzien do zabawy

**Comment by krystian3w** [comment]
To jest jakaś podróbka...

**Comment by krystian3w** [comment]
PS. `Adblock Plus Browser` ma plany porzucenia aktualizacji do Firefox "Quantum" Mobile na rzecz użycia kodu Chromium. W becie już mają wersje na Chromium a nie Firefox.
