### ISSUE TITLE
zabkowice.express-miejski.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14876]
resztki po reklamach

**Comment by krystian3w** [comment]
rozszerzyłbym poszukiwania o całą:

```
http://www.express-miejski.pl/
``

**Comment by krystian3w** [comment]
`express-miejski.pl##div[class] > .small:-abp-contains(REKLAMA)`

Białe luki trudne do eliminacje, strona ma dziwne pozycjonowanie elementów...
