### ISSUE TITLE
natemat.pl 

### ISSUE THREAD

**Issue by Tasiorsa** [MajkiIT/polish-ads-filter#14880]
### Zrzut ekranu

![nat](https://user-images.githubusercontent.com/35109319/66636431-7ac76d80-ec11-11e9-9948-9132a1874013.png)

### Link bezpośredni

https://natemat.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Na głównej stronie białe pole nad napisem "Na Temat" 

### Moja konfiguracja
**Przeglądarka internetowa:**
Firefox 69.0.2
**Rozszerzenia i skrypty:**
Adguard
**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Wszystkie polskie filtry które dało się włączyć w Adguard

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Ja nie mam, włącz `AdGuard Base` w AdGuard.

**Comment by krystian3w** [comment]
A w ustawieniach odznacz `Nie blokuj pożądanych reklam` lub usuń subskrypcje:

`Filtr użytecznych reklam`

**Comment by krystian3w** [comment]
I EasyList niby zbędne w AG, braknie to filtry obecnie śmiało są dodawane do `AdGuard Base` sekcja "foregin". Niestety już chyba nikt nie ma czasu by to wrzucać w polski suplement dla AdGuard (i nagle byłoby miejsce na filtry anty-adblock).

**Comment by Tasiorsa** [comment]
Podstawowe filtry Adguard włączone.  Filtr użytecznych reklam wyłączony. Nie blokuj pożądanych reklam wyłączony i mam białe pole nad Na temat :)

**Comment by krystian3w** [comment]
Inne opcje i odznacz "`Użyj filtrów zoptymalizowanych`" na komputerze niby dla AdGuard to zbędne (bez EasyList mają o jakieś 60 tysięcy filtrów i tak mniej).

**Comment by krystian3w** [comment]
Spróbuj wybrać opcje "zablokowania elementu" kod jaki wygeneruje wrzuć do wątku.

**Comment by Tasiorsa** [comment]
Nie ma elementu do zablokowania w tym miejscu - ot zostalo puste miejsce - czyli cala strona powinna pojsc do gory :). Na nano Adblocker + NanoDefender z wlaczonymi filtrami kosmetycznymi jest OK. Na Adguard nie.

**Comment by krystian3w** [comment]
Jak dźwignie się dla `body` lub `html` to niestety niby nie rusza w górę nagłówek a opada to co pod nagłówkiem - mam jakąś wersje "v2" ich szablonu.

Spróbuj spakować stronę do zip po użyciu opcji "Zapisz jako" i zip wrzuć, może się zachowa dziwny margines.

**Comment by Tasiorsa** [comment]
Tylko czemu przy Nano Adbloker + Nano Defender tego Marginesu nie ma :)

**Comment by krystian3w** [comment]
Nie wiem, może jakieś filtry z AdGuard go doklejają, podajesz że używasz 3 i ja mając z 6 w AdGuard nie mam problemu.

Nie chcesz zipować to zgłoś błąd opcją spod wysuwanej chmurki, najwyżej i AdGuard zamknie ci wątek, bo mają inny szablon bez buga.

![obraz](https://user-images.githubusercontent.com/35370833/66705536-6de96d80-ed28-11e9-925b-7745b0176dca.png) |
--- |

https://reports.adguard.com/en/new_issue.html - PS. z tego linka otwiera się to samo, ale on wymaga wtedy ręcznie podania:
* wersji AdGuard
* aktywnych filtrów (zapomnisz jakiś i już może być problem jak np. Polskie Filtry Wewnętrzne mieszają - @KonoromiHimaries sprawdź czy nie trzeba tej grupie domen poprawić nagłówka by nie był ruchomy).
* linka do strony.

**Comment by krystian3w** [comment]
Dobra mam winowajcę: https://github.com/KonoromiHimaries/PolishSubFilters

**Comment by Tasiorsa** [comment]
@krystian3w sobota zona nie było mnie...
Dzięki za zaangażowanie - faktycznie wylłązenie polskich skryptów wewnętrznych naprawia błąd

**Comment by krystian3w** [comment]
Już powinna być w AdGuard nowsza lista z dodanym wsparciem też layoutu mobilnego (PR scalone około 1 w nocy, więc od około 4-5 rano AdGuard pewnie zassał na `filters.adtidy.org`).
