### ISSUE TITLE
e-chelmno.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14886]
Pop-up ( PiS )

**Comment by krystian3w** [comment]
Pewnie w poniedziałek zniknie a za blokowanie "polityki" to uAssets może nas zbanować w uBO i rozważą aktywacje EasyList i przekopiowanie wszystkich filtrów Olega by i on nie mógł cenzurować.

**Comment by MajkiIT** [comment]
@krystian3w a były takie przypadki ?

**Comment by krystian3w** [comment]
Tak Fin zaczął wycinać linki o problemach politycznych, uAsset zakomentowało to i potem stwierdzono że listę zmienią na fork z Github.

**Comment by MajkiIT** [comment]
No to kicha ...
