### ISSUE TITLE
lubiepowietrze.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1489]
ad block maybe?

`http://lubiepowietrze.pl/uzywasz-adblocka`

Zostałeś przekierowany do tej strony, ponieważ używasz AdBlocka.

Drażnią Cię reklamy na blogu i artykuły sponsorowane? Masz jakiś problem z tym, że pobieram opłaty za dostęp do strefy premium? Sądzisz, że blog powinien być tworzony jedynie z myślą o czytelnikach lub co gorsze: jedynie społecznie lub charytatywnie?

Jeśli twoja odpowiedź brzmi TAK – to z pewnością nie jest to miejsce dla Ciebie.

Jeśli twoja odpowiedź brzmi NIE – dodaj mojego bloga do listy wyjątków w Twoim AdBlocku i wróć do interesującej Cię treści.

**Comment by F4z** [comment]
Ta reguła powinno pomóc:
`||lubiepowietrze.pl/wp-content/uploads/nRrK9mD1obIl/7caz711emjAJ.js$script,domain=lubiepowietrze.pl`
Ewentualnie bardziej ogólnie:
`||lubiepowietrze.pl/wp-content/uploads/*.js$script,domain=lubiepowietrze.pl`
