### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by SebaK666** [MajkiIT/polish-ads-filter#14908]
Na sportowefakty.wp.pl blokuje górny pasek (scoreboard) z wynikami meczów, w relacjach też nie można zmieniać zakładek - relacja na żywo, komentarze, składy o meczu.
Blokuje to ten wpis:
wp.pl##script:inject(set-constant.js, WP.gaf.loadBunch, noopFunc)
dodanie do swoich filtrów takiego odblokowuje to:
wp.pl#@#script:inject(set-constant.js, WP.gaf.loadBunch, noopFunc)
ale pojawiają się z kolei reklamy. Nie ma żadnego sposobu na WP.pl żeby zablokować reklamy, ale nie blokować tym samym funkcjonalności strony??

**Comment by krystian3w** [comment]
Trzeba by znowu poanalizować kod strony i nowy skrypt albo ułomnie wyciąć je używając `:has(...)` / `:matches-css-before/after(...)`.

**Comment by krystian3w** [comment]
Inny problem, że chyba uBO dalej nie umie ci pobrać nowszych filtrów.

`script:inject` nie występuje już w listach, mają `+js` i raczej logger tego nie zmienia w starszą składnię?

**Comment by SebaK666** [comment]
Za twoją radą na uAssets zmieniłem wersję 1.7 na 1.16.4.11
W przeciwieństwie do tamtej Easy List, Easy Privacy mam teraz aktualne, wasze też. Jedynie zniknęły ma własne dodane jako custom, zmieniłem z powrotem na 1.7 ale już ich nie odzyskałem. Miałem tam taki Fuck Adblock. Teraz za cholerę nie moge go znaleźć. Pomożesz?

**Comment by krystian3w** [comment]
https://github.com/bogachenko/fuckfuckadblock#use

Co do wycięcia reklam to raczej nie tu #13818 też chętnych nie ma by obejrzeć choćby co jest w `AdGuard Base` na reklamy wirtualnej Polski w postaci filtrów skryptowych i co zakomentowali jako "szkodliwe".

**Comment by krystian3w** [comment]
Może reklamy powinny poczekać aż na "SF.WP" zmienią layout na biały jak na `wiadomości` / `finanse` itp. subdomenach.

**Comment by SebaK666** [comment]
Dzięki za pomoc, linki. Zresztą wiem że WP najbardziej chyba w Polsce kombinuje.  Dziwne też, że coś mi blokowało WP na poprzedniej, od dawna używanej wersji 1.7. Zmieniłem na 1.6, także powróciłem chwilę na 1.7 ale nie było już zamazanej strony i komunikatu o adblocku na WP.  Przez przypadek trochę sobie poprawiłem sytuację. Czyli nieraz sam adblock powoduje kłopot, ten sam skrypt, filtr działa inaczej nawet na tej samej wersji. Nie mówię o w/w sytuacji, ale  ogóle. Możliwe że to urok systemu, przeglądarki. Mając Win 10 na najnowszy Firefoks pewnie byłoby zgodnie ze standardami, ale nie zawsze można to mieć.
