### ISSUE TITLE
centrumxp.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14903]
Ukrywa
![2019-10-13 05 10 28 www centrumxp pl 27764fdd88b4](https://user-images.githubusercontent.com/36385327/66710402-d4e24300-ed77-11e9-8f7e-1c2e882bfc37.png)

**Comment by krystian3w** [comment]
`||www.centrumxp.pl/api/images/bannery/$image,badfilter`

`centrumxp.pl##.article > p > a > img[src*="Bannery"]`
