### ISSUE TITLE
sucharry.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1490]
ad block 

Pan Suchar jest smutny, ponieważ używasz programu typu AdBlock. Reklamy na Sucharrach nie są i nigdy nie były nachalne (żadnych wyskakujących okienek itp.). Jeśli lubisz Sucharry, rozważ wyłączenie AdBlocka na naszej stronie (zobacz jak to zrobić).

**Comment by F4z** [comment]
Tutaj najprościej będzie ukryć ten komunikat.
`sucharry.pl###adb`
