### ISSUE TITLE
benchmark.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14902]
![2019-10-13 05 02 38 www benchmark pl ddc251e1014c](https://user-images.githubusercontent.com/36385327/66710344-b29bf580-ed76-11e9-991f-75fadbe5112c.png)

**Comment by xxcriticxx** [comment]
@xMaap podaj wiecej info krysztalowej kuli nie posiadamy

**Comment by hawkeye116477** [comment]
Zgaduję, że chodzi o reklamę tej sieci, co tak w kółko czyszczą tam te magazyny :smiley:
