### ISSUE TITLE
fili.cc

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#14906]
Macie przekierowanie z https://fili.cc/ na https://filmiki.tv/ ?

**Comment by krystian3w** [comment]
Tak.

**Comment by krystian3w** [comment]
I zrobione na sztywno lub nie przekopiowali wszystkiego:

`https://fili.cc/film/camp-rock-2008/4792` > `filmiki.tv homepage`

**Comment by MajkiIT** [comment]
@krystian3w Dziękuje

**Comment by MajkiIT** [comment]
@krystian3w Widziałeś czy ten regex coś wyłapuje ? Mi się wydaje, że obecnie tam nic nie ma.

**Comment by xxcriticxx** [comment]
Narazie nic tam niema
