### ISSUE TITLE
kursbootstrap.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1491]
ad block

`https://kursbootstrap.pl/tutorial/`

Dziękuję! Widzę, że nie używasz AdBlocka. To dobrze:) Reklamy są nieodłączną częścią darmowych stron i pozwalają autorom na ich rozwój. Jeśli doceniasz pracę innych, nie używaj AdBlocka na tych witrynach.

**Comment by F4z** [comment]
W komunikacie jest, że "[...] **nie** używasz AdBlocka[...]" :)
Jeśli komuś przeszkadza ten komunikat, to ta reguła powinna go ukryć:
`kursbootstrap.pl##.alert-dismissible.alert-success.alert`
