### ISSUE TITLE
jastrzebieonline.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1492]
ad block 

`http://jastrzebieonline.pl/news,4236,kradli-kolpaki-z-kol-wpadli-na-goracym-uczynku.html`

Używasz AdBlocka? Prosimy, wyłącz go dla tej strony.

Wykryliśmy, że blokujesz reklamy w swojej przeglądarce. Portal utrzymuje się z reklam, a blokowanie banerów nie sprzyja jego rozwojowi oraz jest nie fair w stosunku do naszych reklamodawców.

**Comment by F4z** [comment]
Jeśli chodzi o komunikat o adblocku, to ta reguła powinna wystarczyć:
`||jastrzebieonline.pl/js/scripts.js$script,domain=jastrzebieonline.pl`
Ewentualnie:
`jastrzebieonline.pl###billboard`
Wtedy też reklamy powinny zostać ukryte.
Można też zablokować źródło tych reklam:
`||jastrzebieonline.pl/files/banners/$domain=jastrzebieonline.pl`

Wszystkie:
`jastrzebieonline.pl###billboard`
`||jastrzebieonline.pl/js/scripts.js$script,domain=jastrzebieonline.pl`
`||jastrzebieonline.pl/files/banners/$domain=jastrzebieonline.pl`

**Comment by MajkiIT** [comment]
@F4z Dzięki
