### ISSUE TITLE
katowicedzis.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#14924]
`https://katowicedzis.pl/2019/10/wojewodzki-osrodek-ruchu-drogowego-w-katowicach-komentuje-nowe-przepisy-wkrotce-beda-one-obowiazywaly-wszystkich-kierowcow/
`
![2019-10-18 20 53 07 katowicedzis pl 470ed3d548ea](https://user-images.githubusercontent.com/36385327/67120357-6d9a1800-f1e9-11e9-95fd-662d3d102031.png)

**Comment by krystian3w** [comment]
@hawkeye116477  reklama społecznościowa, to otwiera facebooka...?

**Comment by krystian3w** [comment]
`##a[href="https://www.facebook.com/magdabachirfotografia/"] > img`

**Comment by hawkeye116477** [comment]
Ja bym chyba jednak dał ją dla @MajkiIT, no chyba, że nie chce, to wtedy dodajemy do Sociala.

**Comment by krystian3w** [comment]
No to musi czekać, ciekawe czy PR z sprzątaniem przejdzie.

**Comment by MajkiIT** [comment]
Niestety nie mam tego :(

**Comment by hawkeye116477** [comment]
Ja tam nadal mam.
![Screenshot_20191020_181722](https://user-images.githubusercontent.com/19818572/67162620-e4f4b680-f365-11e9-9b48-941ed7a281a6.png)

**Comment by MajkiIT** [comment]
@hawkeye116477  Już mam dziękuje

**Comment by hawkeye116477** [comment]
Jest jeszcze druga taka sama, może lepsze byłoby g-single.

**Comment by krystian3w** [comment]
albo po linku lub nazwie promocyjnej kanału.
