### ISSUE TITLE
lec.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14928]
polowa strony jest biala

**Comment by hawkeye116477** [comment]
@kiboke Can you add `@@||lec.com.pl/wp-content/plugins/cookie-message/js/custom.js`?

**Comment by xxcriticxx** [comment]
@hawkeye116477 wyjatki moze do naszej listy

**Comment by krystian3w** [comment]
Do naszej tak, 3-4 tygodnie czekania mogą być.

**Comment by krystian3w** [comment]
Zenbox.pl down site:

![obraz](https://user-images.githubusercontent.com/35370833/67166244-e76b0680-f38d-11e9-8a09-5a5d3fe97dd2.png)

**Comment by kiboke** [comment]
> @kiboke Can you add `@@||lec.com.pl/wp-content/plugins/cookie-message/js/custom.js`?

I will remove blocking of `/wp-content/plugins/cookie-message` alltogether and find an alternative approach. Thanks!
