### ISSUE TITLE
teologiapolityczna.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#14920]
cookies

**Comment by krystian3w** [comment]
Jeszcze coś uszkadza wersje angielską:

http://en.teologiapolityczna.pl/

robi się biała strona.

<details open><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +60 | ##.twitter-share |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +60 | ##.social |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +60 | ##.newsletterbox |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +60 | ##.newsletterBox |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +60 | ##.newsletter:not(#popup_newsletter):not(.in-line):not(.curvyIgnore) |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +60 | ##.fb-share |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +60 | ##.fa.icon |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +60 | ##.fa-youtube-play.fa |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +60 | ##.fa-twitter.fa |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +60 | ##.fa-instagram |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +60 | ##.fa-facebook |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +59 | /piwik.$script,domain=~matomo.org\|~piwik.org | -- | en.teologiapolityczna.pl | 3 | script | `http://stat.mikolaj.org.pl/piwik.js` |
| +59 | google-analytics.com/ga.js | << | en.teologiapolityczna.pl |  | script | `http://www.google-analytics.com/ga.js` |
| +59 | \|\|google-analytics.com^ | -- | en.teologiapolityczna.pl | 3 | script | `http://www.google-analytics.com/ga.js` |
| +59 | `##a[href^="http://www.facebook.com/sharer.php"]` |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +59 | `##a[href^="http://twitter.com/share?"]` |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +59 | `##a[href^="http://twitter.com/share"]` |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +59 | ##[name="fb_share"] |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +59 | ##.Facebook |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +59 | ###\5f __plusone_0 |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +59 | ###SocialMedia |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +59 | \|\|google.com^*/fastbutton?$third-party | -- | en.teologiapolityczna.pl | 3 | frame | `https://apis.google.com/u/0/se/0/_/+1/fastbutton?usegapi=1&size=small&hl=pl&origin=http%3A%2F%2Fen.teologiapolityczna.pl&url=http%3A%2F%2Fen.teologiapolityczna.pl%2F&gsrc=3p&ic=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.pl.usD5eixTy2I.O%2Fam%3DwQE%2Fd%3D1%2Frs%3DAGLTcCPR9E4m2-dLNXDecleWeQgUtV8YwQ%2Fm%3D__features__#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh&id=I0_1571328351637&_gfid=I0_1571328351637&parent=http%3A%2F%2Fen.teologiapolityczna.pl&pfname=&rpctoken=26329712` |
| +59 | /piwik.$script,domain=~matomo.org\|~piwik.org | -- | en.teologiapolityczna.pl | 1 | script | `http://stat.teologiapolityczna.pl/piwik.js` |
| +59 | google-analytics.com/ga.js | << | en.teologiapolityczna.pl |  | script | `http://www.google-analytics.com/ga.js` |
| +59 | \|\|google-analytics.com^ | -- | en.teologiapolityczna.pl | 3 | script | `http://www.google-analytics.com/ga.js` |
| +59 | /js/fb.share\|$third-party | -- | en.teologiapolityczna.pl | 3 | script | `http://static.ak.fbcdn.net/connect.php/js/FB.Share` |
| +59 | \|\|facebook.com*/plugins/like.php?$third-party | -- | en.teologiapolityczna.pl | 3 | frame | `http://www.facebook.com/plugins/like.php?href=http://www.teologiapolityczna.pl/about&layout=button_count&show_faces=false&width=100&action=like&colorscheme=light&height=80` |
| +59 | \|\|googlesyndication.com^ | -- | en.teologiapolityczna.pl | 3 | script | `http://pagead2.googlesyndication.com/pagead/show_ads.js` |
| +59 | /js/fb.share\|$third-party | -- | en.teologiapolityczna.pl | 3 | script | `http://static.ak.fbcdn.net/connect.php/js/FB.Share` |
| +59 | \|\|googlesyndication.com^ | -- | en.teologiapolityczna.pl | 3 | script | `http://pagead2.googlesyndication.com/pagead/show_ads.js` |
| +11 | ##.twitter-share |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +11 | ##.social |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +11 | ##.newsletterbox |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +11 | ##.newsletterBox |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +11 | ##.newsletter:not(#popup_newsletter):not(.in-line):not(.curvyIgnore) |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +11 | ##.fb-share |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +11 | ##.fa.icon |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +11 | ##.fa-youtube-play.fa |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +11 | ##.fa-twitter.fa |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +11 | ##.fa-instagram |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +11 | ##.fa-facebook |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +9 | `##a[href^="http://www.facebook.com/sharer.php"]` |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +9 | `##a[href^="http://twitter.com/share?"]` |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +9 | `##a[href^="http://twitter.com/share"]` |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +9 | ##[name="fb_share"] |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +9 | ##.Facebook |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +9 | ###\5f __plusone_0 |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +9 | ###SocialMedia |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +9 | \|\|google.com^*/fastbutton?$third-party | -- | en.teologiapolityczna.pl | 3 | frame | `https://apis.google.com/u/0/se/0/_/+1/fastbutton?usegapi=1&size=small&hl=pl&origin=http%3A%2F%2Fen.teologiapolityczna.pl&url=http%3A%2F%2Fen.teologiapolityczna.pl%2F&gsrc=3p&ic=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.pl.usD5eixTy2I.O%2Fam%3DwQE%2Fd%3D1%2Frs%3DAGLTcCPR9E4m2-dLNXDecleWeQgUtV8YwQ%2Fm%3D__features__#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh&id=I0_1571328301834&_gfid=I0_1571328301834&parent=http%3A%2F%2Fen.teologiapolityczna.pl&pfname=&rpctoken=33983384` |
| +9 | \|\|facebook.com*/plugins/like.php?$third-party | -- | en.teologiapolityczna.pl | 3 | frame | `http://www.facebook.com/plugins/like.php?href=http://www.teologiapolityczna.pl/about&layout=button_count&show_faces=false&width=100&action=like&colorscheme=light&height=80` |
| +0 | ###\5f __plusone_0 |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +0 | `##a[href^="http://www.facebook.com/sharer.php"]` |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +0 | `##a[href^="http://twitter.com/share?"]` |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +0 | `##a[href^="http://twitter.com/share"]` |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +0 | ##[name="fb_share"] |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +0 | ##.Facebook |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +0 | ###SocialMedia |  | en.teologiapolityczna.pl |  | dom | `http://en.teologiapolityczna.pl/` |
| +0 | \|\|google.com^*/fastbutton?$third-party | -- | en.teologiapolityczna.pl | 3 | frame | `https://apis.google.com/u/0/se/0/_/+1/fastbutton?usegapi=1&size=small&hl=pl&origin=http%3A%2F%2Fen.teologiapolityczna.pl&url=http%3A%2F%2Fen.teologiapolityczna.pl%2F&gsrc=3p&ic=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.pl.usD5eixTy2I.O%2Fam%3DwQE%2Fd%3D1%2Frs%3DAGLTcCPR9E4m2-dLNXDecleWeQgUtV8YwQ%2Fm%3D__features__#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh&id=I0_1571328292943&_gfid=I0_1571328292943&parent=http%3A%2F%2Fen.teologiapolityczna.pl&pfname=&rpctoken=85074010` |
| +0 | \|\|facebook.com*/plugins/like.php?$third-party | -- | en.teologiapolityczna.pl | 3 | frame | `http://www.facebook.com/plugins/like.php?href=http://www.teologiapolityczna.pl/about&layout=button_count&show_faces=false&width=100&action=like&colorscheme=light&height=80` |
</details>
