### ISSUE TITLE
Po kliknięciu Subskrybuj Ublock nie robic nic

### ISSUE THREAD

**Issue by Usernameisalreadytaken5** [MajkiIT/polish-ads-filter#14947]
![image](https://user-images.githubusercontent.com/36273555/67356839-20040f00-f54b-11e9-9013-535f164facf0.png)

**Comment by MajkiIT** [comment]
ale te filtry są już w uBlock Origin. Ale sprawdzimy.

**Comment by xMaap** [comment]
@MajkiIT Ja bym pousuwał te które są domyślnie już włączone. Dodatkowo te filtry za screena jakoś inaczej oznaczył, ponieważ widzę w internecie że ludzie to i to dodają.
![2019-10-23 09 54 40 github com 9ac6a2ec2cd8](https://user-images.githubusercontent.com/36385327/67370655-55c0ec00-f57b-11e9-873b-3518d1251a07.png)
Jeszcze dodał  **I don't care about cookies** https://www.i-dont-care-about-cookies.eu/pl

**Comment by krystian3w** [comment]
# bug gitchub

Kto chce nie ubije skryptem lazyload stron i się naprawi.

**Comment by KonoromiHimaries** [comment]
@Usernameisalreadytaken5 sprawdź https://majkiit.github.io/polish-ads-filter/

**Comment by Usernameisalreadytaken5** [comment]
@KonoromiHimaries a no dzięki działa

**Comment by krystian3w** [comment]
skąd tam te BR?

**Comment by krystian3w** [comment]
https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fgithub.com%2FMajkiIT%2Fpolish-ads-filter%23about taki też na 100% odbuguje się.

**Comment by hawkeye116477** [comment]
`skąd tam te BR?`
Bo w readme jest wpisane, po to by były odstępy, a Jekyll najwyraźniej błędnie przetwarza.

**Comment by KonoromiHimaries** [comment]
> Ja bym pousuwał te które są domyślnie już włączone

@xMaap nie jest to dobry pomysł, w końcu ktoś może mieć je wyłączone.

**Comment by KonoromiHimaries** [comment]
> widzę w internecie że ludzie to i to dodają

@xMaap nie szkodzi, ważne że ublock ich nie dubluje.
