### ISSUE TITLE
joemonster.org

### ISSUE THREAD

**Issue by Usernameisalreadytaken5** [MajkiIT/polish-ads-filter#14948]
### Zrzut ekranu
![image](https://user-images.githubusercontent.com/36273555/67358582-7162cd00-f550-11e9-9f09-1ae7e39d50fb.png)

### Link bezpośredni
https://joemonster.org/art/48213/Dwa_rozne_filmy_to_samo_uniwersum_Czy_agent_J_23_pojawil_sie_w_Czterech_pancernych_

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
zablokowac te jebany adquesto

ps wyłączenie JS pomogłoa a strona smiga 

![image](https://user-images.githubusercontent.com/36273555/67359656-50e84200-f553-11e9-8d55-b65570b35c37.png)

### Moja konfiguracja
Firefox 70

**Rozszerzenia i skrypty:**
Ublock

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Po użyciu reader view
![image](https://user-images.githubusercontent.com/36273555/67358981-89871c00-f551-11e9-94a9-eb1947804333.png)

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/de609f859b8bfd69d1e7dc2763f60cad0c24640d#diff-6de60f294b8bd23c752f8fcbece875b1

**Comment by Barticf** [comment]
EasyList u mnie powoduje ten problem

**Comment by Usernameisalreadytaken5** [comment]
No dzięki tera smiga zajebiście

**Comment by krystian3w** [comment]
`##+js(acis, parseInt, adblock)`

i problem znika, tylko trzeba sobie domeny dopisać przed `##`.
