### ISSUE TITLE
linuxiarze.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1494]
niema polowy strony hyba przez slowo reklama

http://linuxiarze.pl/reklama/#baner

**Comment by F4z** [comment]
Dokładnie.
`linuxiarze.pl#@#[class*="reklama"]`
Chociaż w tym przypadku, osoby korzystające z programów/rozszerzeń do blokowania reklam raczej nie będą zainteresowaną tą treścią.

Jeszcze można ukryć ten baner, link - `http://linuxiarze.pl/opensuse-42-2/`
![image](https://cloud.githubusercontent.com/assets/11742596/20458150/f93e0fbc-ae9c-11e6-868b-3f9eaa4386aa.png)
Nie wiem jak długo będzie ta reguła działała, bo pewnie jak będzie już "normalna" reklama, to link się zmieni, ale tymczasowo można dodać, na przykład:
`linuxiarze.pl##a[href="http://linuxiarze.pl/reklama/#baner"]`
