### ISSUE TITLE
puratos.pl/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#14940]

**Comment by krystian3w** [comment]
A lipa znika po 5 sekundach i wychodzi, że masz problem z IDCAC:

![obraz](https://user-images.githubusercontent.com/35370833/67313417-34bcb480-f503-11e9-9a11-c86194475a47.png) |
--- |

**Comment by krystian3w** [comment]
A i to nie jest tak popularne jak Interia by robić filtr specyficzny, który przy pierwszych odwiedzinach ukryje szybciej.
