### ISSUE TITLE
joemonster.org adquesto

### ISSUE THREAD

**Issue by kayvax** [MajkiIT/polish-ads-filter#14950]
### Zrzut ekranu
![adquesto](https://user-images.githubusercontent.com/6639788/67435307-20a0b200-f5ec-11e9-9e08-5d61c5f855b9.jpg)

### Link bezpośredni
https://joemonster.org/art/48214/Microsoft_pokazal_gre_na_widok_ktorej_wszystkim_opadly_szczeki_W_co_jest_grane_

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Otworzyć stronę.
2. Zjechać na dół
3. 

### Moja konfiguracja
Vivaldi	2.8.1664.44

**Rozszerzenia i skrypty:**
uBlock Origin v1.22.4
uMatrix 1.4.0

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. AakList (Anti-Adblock Killer)
4. AlleBlock  
5. Fuck Fuckadblock
6. Malware domains (long-lived)
7. Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for uBlock Origin
8. Polish Privacy Filters
9. Polskie Filtry Elementów Irytujących
10. Polskie Filtry RODO-Ciasteczkowe

I standardowe z listy uBlock Origin

**Comment by MajkiIT** [comment]
Wczoraj był ten temat 
https://github.com/MajkiIT/polish-ads-filter/issues/14948

Brakuje POL: Oficjalne polskie filtry przeciwko alertom o Adblocku lub są nieaktualne.
