### ISSUE TITLE
dns blocking

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1495]
@F4z jak masz chwile bysmy dns potestowali mam zamkniene filmy na wp.pl znajduje ad blocka i niewiem co trzeba przepuscic aby zaczely dzialac

**Comment by F4z** [comment]
@xxcriticxx mam chwilę.

**Comment by F4z** [comment]
W zasadzie to co mam zrobić?

**Comment by xxcriticxx** [comment]
podaj mi jake domeny mam whitelist zrobic na wp.pl filmach bo ja mam ad block blokuje na pozmiomie host

film do testow jest na dole:

http://www.money.pl/gospodarka/wiadomosci/artykul/wybory-w-usa-donald-trump-rosja-brexit,106,0,2196074.html

**Comment by F4z** [comment]
Sprawdź te:
`adv.wp.pl`
`rek.www.wp.pl`
`owabgxis.wp.pl`
`fntajkb.wp.pl`

Jeśli nie zadziała, to dodaj jeszcze to:
`dot.wp.pl`

**Comment by xxcriticxx** [comment]
dodalem wszystkie i no go jest cos jeszcze

**Comment by xxcriticxx** [comment]
mysle ze to bendzie cos z domen gemius.pl

**Comment by F4z** [comment]
Ale masz komunikat o adblocku, czy jakiś inny?

**Comment by xxcriticxx** [comment]
tak

![capture](https://cloud.githubusercontent.com/assets/15007183/20458310/72bf642c-ae6f-11e6-8840-3a9408cdc579.PNG)

**Comment by F4z** [comment]
Jest możliwość żeby zobaczył listę tych domen, które blokujesz?
Bo na podstawie dziennika żądań sieciowych z uBlocka nie mam już za bardzo pomysłu.

**Comment by xxcriticxx** [comment]
wtym problem jest ich ze 100 tys

**Comment by F4z** [comment]
To sporo, może spróbuj "odblokować" wszystkie związane z wp.pl?

**Comment by xxcriticxx** [comment]
dodalem wszystkie co podalem film dalej nie dziala mysle ze to bendzie jakis server poza wp

**Comment by F4z** [comment]
Ciężko mi będzie pomóc jak nie wiem co jest na liście.
Może jeszcze to?
`imasdk.googleapis.com`

**Comment by xxcriticxx** [comment]
prawie sukces film sie zaczyna ale po sec ad block

**Comment by F4z** [comment]
Może jeszcze to:
`s0.2mdn.net`
chociaż nie wiem, czy ma to jakiekolwiek znaczenie.

Sprawdzasz to korzystając też z uBlocka?
Jeśli tak, to mógłbyś zrobić screenshota z loggera/dziennika żądań uBlocka?

**Comment by xxcriticxx** [comment]
ok moment

**Comment by xxcriticxx** [comment]
![capture1](https://cloud.githubusercontent.com/assets/15007183/20458698/abf77f0e-ae79-11e6-9a3c-8a6728c07243.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15007183/20458699/aef9a6a0-ae79-11e6-8cd0-66da22a4e1cc.PNG)
![capture3](https://cloud.githubusercontent.com/assets/15007183/20458701/b179d8fa-ae79-11e6-8488-a36ad9c04a1e.PNG)
![capture4](https://cloud.githubusercontent.com/assets/15007183/20458702/b46d48ee-ae79-11e6-9c85-dd563b258950.PNG)

**Comment by F4z** [comment]
Dzięki.
Rozumiem, że to jest bez uruchomienia filmu?
Jak tak patrzę na różnice, to w zasadzie występują tylko w przypadku zablokowanych rzeczy, u Ciebie pewnie ich nie widać, bo są zablokowane przez host.

Możesz spróbować dodać to:
`atemda.com`
`adnxs.com`
`pubmatic.com`
`openx.net`
`criteo.com`

Swoją drogą nie widzę też tego - `http://rek.www.wp.pl/gaf.js` (to tylko początek, bo nazwa tego jest dłuższa), nie masz tego w loggerze uBlocka?

**Comment by xxcriticxx** [comment]
jest tylko raz `http://rek.www.wp.pl/9ejoty!(:27chmrw.&]05afkpuz@)%3C38dinsx,*;16bglqv_$[%3E49ejoty!(:27chmrw.&]05afkpuz@)%3C38din.gif?9ejoty!(:27chmrw.&]05afkpuz@)%3C38dinsx,`

**Comment by F4z** [comment]
Po uruchomieniu filmu powinno być też to - `http://rek.www.wp.pl/vad.xml`
Masz takie coś?

**Comment by xxcriticxx** [comment]
nope

te strony co podales atemda.com i reszta pokazuje ze nie poprawne sa niewiem czemu

**Comment by F4z** [comment]
Mam wrażenie, że w jakiś sposób nadal masz blokowane rzeczy z wp.pl, a przynajmniej z `rek.www.wp.pl`, ale może się mylę.
Ogólnie, to niestety nie mam już więcej pomysłów.

**Comment by xxcriticxx** [comment]
wyloncze i flush dns  moze
