### ISSUE TITLE
fili.cc

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#14961]
Już wiadomo co się stało ... 
http://policja.pl/pol/aktualnosci/180670,Udostepnil-nielegalnie-ponad-10-tysiecy-utworow-audiowizualnych-teraz-stanie-prz.html

**Comment by xxcriticxx** [comment]
Miałem kiedyś taka case od coolmaster

**Comment by gzenio22** [comment]
Fili to pryszcz zaczne sie bac o takie strony jak zalukaj padnie Xd
