### ISSUE TITLE
paypal donations 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1497]
dasz rade dodac?

**Comment by MajkiIT** [comment]
na Patronite można wspierać za pomocą Paypal

**Comment by xxcriticxx** [comment]
Podaj linka please

**Comment by MajkiIT** [comment]
https://patronite.pl/polskiefiltry

**Comment by xxcriticxx** [comment]
@MajkiIT prosto do paypal nieche sie rejestrowac na patronie. 

najlepjej podaj na swoj paypal ja do ciebie ty do patrona
