### ISSUE TITLE
joemonster.org

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1499]
reklama 

http://joemonster.org/forum/

![capture](https://cloud.githubusercontent.com/assets/15007183/20464579/adaf9914-af17-11e6-9c44-b18c09dcf640.PNG)

**Comment by xxcriticxx** [comment]
jest tutaj i tutaj

http://joemonster.org/mg/thumbnails.php?album=lastup
http://joemonster.org/phorum/read.php?f=36&t=204976
http://joemonster.org/gry/79748/Monkey_Go_Happy_Army_Base
http://joemonster.org/blog/
http://joemonster.org/submit-article

**Comment by F4z** [comment]
Sprawdź, powinno działać:
`@@||unblock.onaudience.com/static/showad.js$xmlhttprequest,domain=joemonster.org`

**Comment by MajkiIT** [comment]
@F4z dzięki
