### ISSUE TITLE
moto.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15]
http://moto.pl/MotoPL/0,0.html

reklama eurobank + oferty

**Comment by MajkiIT** [comment]
Mogę prosić o zrzut ekranu?

**Comment by xxcriticxx** [comment]
wczoraj byla juz dzisaj niema na przyszlosc zaczne robic prt scr

cos takiego tylko inna tresc reklamy "tania szybka pożyczka w eurobank"

http://www.centrumkredyt.pl/wp-content/uploads/2015/07/kredyt-eurobank_pl_gotowka-2-680x365_c.png
