### ISSUE TITLE
Adblocker do telewizji

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#15001]
Wymyślili jakieś nowe cudactwo, niby adblocker do telewizji zwany Advoider, automatycznie przełącza na kanały m.in. wolne od reklam, wycisza dźwięk lub wyłącza dekoder i odbiornik telewizyjny na czas trwania niepożądanych treści. Obsługuje CP i C+.

> Lista kanałów monitorowanych: TVP 1, TVP 2, TVP Seriale, Polsat, Polsat Film, Polsat Café, Polsat Play, TV4, TVN, TVN7, TVN Style, TVN Turbo, TV Plus, HGTV, TTV, Stopklatka, Kino Polska, TVN Fabuła, Discovery Channel, 4Fun TV, Polo TV, Eska TV, TVN 24, TVP Info, Polsat News, TVP Sport, Polsat Sport, Eurosport 1, TVP ABC, Disney Junior, Nick Jr, Nickelodeon, Mini Mini+, Cartoon Network. 

Kosztuje 4 stówy.

Więcej na https://www.advoider.pl/.

Ktoś zainteresowany :smiley:?

<img src="https://www.instalki.pl/images/newsy/10-2019/2019-10-29_150238.jpg">

**Comment by MajkiIT** [comment]
hahahaha ciekawe, można zamówić i zwrócić w razie co.  Ale to jakieś mega dziwne.

**Comment by xxcriticxx** [comment]
no

**Comment by blocker999** [comment]
fajne urządzonko cena chyba z kosmosu noi ja mam dvb-t czyli się nielicze a szkoda

**Comment by hawkeye116477** [comment]
@blocker999 Jest też aplikacja z powiadomieniami o rozpoczęciu i zakończeniu reklam, na 14 dni możesz przetestować.
https://play.google.com/store/apps/details?id=com.qdiqo.advoiderlite&hl=pl

**Comment by krystian3w** [comment]
Pytanie czy oni robią statystykę ile filmu leci, ile reklama trwa. Bo raczej nie wtyki.
