### ISSUE TITLE
investors.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#15000]
investors.pl
![2019-10-29 22 49 46 investors pl a3cfa5120823](https://user-images.githubusercontent.com/36385327/67812303-280a0480-fa9f-11e9-885b-f0e9b27d1b1e.png)

`https://online.investors.pl/investors/#/logowanie`
Cookies + social

**Comment by krystian3w** [comment]
Socialu nie widzę, pop-up z rodo wytnie się, dźwignąć można nawigacje, bo na sztywno obniżona.
