### ISSUE TITLE
rip openload 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15017]
https://torrentfreak.com/openload-and-others-taken-down-by-anti-piracy-alliance-ace-191031/

@MajkiIT teraz bedziesz mogl usunac kilka filtrow

**Comment by xxcriticxx** [comment]
lol

![Capture](https://user-images.githubusercontent.com/15007183/68020060-bcc55b80-fc73-11e9-9765-bb59c1a4dd21.PNG)

**Comment by krystian3w** [comment]
W sumie pytanie czy my mamy te filtry tylko dla użytkowników ABP, bo uAsset ma wiele skryptowych pod stronę czy odtwarzacz.

**Comment by krystian3w** [comment]
I niby znów się przenieśli `https://www1.openload.watch/` chyba że ktoś zrobił podróbkę.

**Comment by xxcriticxx** [comment]
@krystian3w to nie ta sama strona

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki, ale chyba nie mieliśmy żadnych reguł odnośnie tego, ale popatrzę.

**Comment by krystian3w** [comment]
Są dwie jakieś sieciówki.

**Comment by krystian3w** [comment]
streamango also Rip, niby ten sam podmiot ich zbanował.

Pod streamango chyba też mamy filtr, bo wykopowicze zgłaszali.

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję

**Comment by xxcriticxx** [comment]
rapidvideo tez chyba poszlo sie pieprzyc
