### ISSUE TITLE
paintballmarket.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15018]

**Comment by krystian3w** [comment]
`###header > .adblock-info`

albo samo:

`##.adblock-info`

Generichide raczej mniej, bo wycieknie ikonka social a raczej to tylko irytujący pasek a nie że strona ma popsutą funkcjonalność.

**Comment by krystian3w** [comment]
@MajkiIT wadliwy generyk:

`www.paintballmarket.pl#@#[class^="ad-"]`

```
https://www.paintballmarket.pl/advertisementsDetails/15
```
