### ISSUE TITLE
mybank.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#1502]
Adblock

http://kursy-walut.mybank.pl/

**Comment by xxcriticxx** [comment]
podaj jakiegos screenshot bo ja nic niemam

**Comment by mathew85** [comment]
http://imgur.com/a/WABD6

Google Chrome 55.0

**Comment by xxcriticxx** [comment]
firefox jest ok tylko wyskakuje to w google chrome

**Comment by F4z** [comment]
Te reguły powinny sprawić, że adblock nie będzie wykrywany:
`@@||mybank.pl^$generichide`
`@@||pagead2.googlesyndication.com/pagead/show_ads.js$script,domain=mybank.pl`
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=mybank.pl`
`@@||pagead2.googlesyndication.com/pagead/js/r*/show_ads_impl.js$script,domain=mybank.pl`

Te trzeba dodać żeby ukryć pozostałość po reklamach:
`mybank.pl##.adsbygoogle`
`mybank.pl##div[id^="div-gpt-ad"]`
`mybank.pl##[id^="aswift_"]`

A tę można dodać żeby ukryć komunikat o ciasteczkach:
`mybank.pl##.ciasteczka`

**Comment by MajkiIT** [comment]
@F4z dzieki
