### ISSUE TITLE
rp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15020]
RODO

test link:
https://www.rp.pl/Koleje/303179939-Zbliza-sie-koniec-monopolu-PKP.html

**Comment by krystian3w** [comment]
Rodo w dodatku, ty go nie lubisz, to masz problem, nikt tego nie wytnie filtrem pod uBO, bo dalej gryzie się kod pop-upa z odtwarzaczami wideo w artykułach.

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishCookieConsent/issues/32 - opcjonalnie w dodatku przyda się wprowadzić pomysł z datą AdamaWr (statyczną jakby strona banowała czy coś).
