### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#15022]
### Zrzut ekranu
![image](https://user-images.githubusercontent.com/886325/68088848-4ab36900-fe63-11e9-8db5-331cdee4edcb.png)

### Link bezpośredni
https://www.wykop.pl/mikroblog/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Otworzyć link
2. bez logowania
3. wyskakuje po chwili
1. można spróbować inne zakładki (wykop/wykopalisko/hity)

### Moja konfiguracja
**Przeglądarka internetowa:** Chrome 77 Firefox Nighly

**Rozszerzenia i skrypty:**

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. uBO default + obie POL
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

src: `https://www.wykop.pl/cdn/c728492/adblock_49_xWXnK9pExDRY.jpg`

Może `||www.wykop.pl/*/adblock_$image`?

**Comment by xxcriticxx** [comment]
@gwarser szacunek za wypelnienie template :)

**Comment by gwarser** [comment]
Gorhill szkolił :)

>2. bez logowania

Zaczęło wyskakiwać na zalogowanym.
