### ISSUE TITLE
szyldy.nf.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15043]
coś blokuje, strone : http://szyldy.nf.pl/firma/tv-morag-telewizja-lokalna-B327945452

**Comment by krystian3w** [comment]
@kiboke bad generic filter:

`/cookiesdirective`

---

`@@||nf.pl/js/libs/cookiesDirective.js$script`

**Comment by kiboke** [comment]
@krystian3w thanks, I'll add the exception.
match case is supported by adblock plus as well.
