### ISSUE TITLE
www.exsite.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1504]
www.exsite.pl###adkon_box_1

**Comment by xxcriticxx** [comment]
pisalem o upfiles reklamie kilka razy

**Comment by MajkiIT** [comment]
@xxcriticxx ale oni ciągle coś zmieniają.

**Comment by xxcriticxx** [comment]
@MajkiIT ok dodajmy te upfiles a ja bende sprawdzal
