### ISSUE TITLE
facet.wp.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1505]
Reklamy -` https://facet.wp.pl/`
Na przykład:
`/:\/\/facet\.wp\.pl\/.{200,}[a-zA-Z0-9=]\//$script,important`
i żeby ukryć pozostałość po reklamach:
`facet.wp.pl##._1gZ6Rt0`
lub
`facet.wp.pl##[class="_1gZ6Rt0"]`

@MajkiIT jeszcze odnośnie wp.pl, ta reguła jest nadal potrzebna?
W ogóle pamiętasz do czego ona była?

`@@/:\/\/(?!biuropodrozy)(?!websocket)(?!liveblog)(?!relacje)(?!opinie)(?!zalacznik)(?!magazyn)(?!newsletter)(?!facet)(?!wyleczto)(?!kuchnia)(?!film)(?!moto)(?!gwiazdy)(?!teleshow)(?!finanse)(?!kobieta)(?!dom)(?!pogoda)(?!tech)(?!historia)(?!czat)(?!ksiazki)(?!gryonline)(?!hotele)(?!narty)(?!samoloty)(?!wycieczki)(?!hosting)(?!irlandia)(?!multikurs)(?!casino)(?!foto)(?!tech)(?!www)(?!stg)(?!doladowania)(?!fantasyliga)(?!funduszeue)(?!imperiumstylu)(?!kodyrabatowe)(?!alefolwark)(?!angielski)(?!arenamody)(?!beniamin)(?!bon)(?!bsg)(?!casino)(?!diety)(?!dlaprasy)(?!dlugi)(?!doladowania)(?!dom)(?!dysk)(?!ebiznes)(?!ebooki)(?!empire)(?!fantasyliga)(?!film)(?!fundusze)(?!ogloszenia)(?!orangekinoletnie)(?!rekrutacja)(?!rycerzeiksiezniczki)(?!speedwaymanager)(?!sportowefakty)(?!sportowybar)(?!talesofmagic)(?!ubezpieczenia)(?!warofdragons)(?!wiadomosci)(?!gazetki)(?!gry)(?!horoskop)(?!kalendarz)(?!katalog)(?!khanwars)(?!komiks)(?!konflikty)(?!kontakty)(?!korsarze)(?!kultura)(?!mini)(?!mmho)(?!mobilna)(?!morizon)(?!moto)(?!muzyka)(?!narty)(?!naryby)(?!onas)(?!orangekinoletnie)(?!piraci)(?!poczta)(?!pomoc)(?!praca)(?!profil)(?!programtv)(?!pytamy)(?!rekrutacja)(?!rss)(?!rtvagd)(?!rycerzeiksiezniczki)(?!smeet)(?!speedwaymanager)(?!szkola)(?!szukaj)(?!tech)(?!teleshow)(?!triviador)(?!turystyka)(?!twojeip)(?!ulubiency)(?!warodfragons)(?!wycieczki)(?!zdrowie)(?!zoomumba)(?!topnews)(?!erotyka)(?!dzieci)(?!fitness)(?!gielda)(?!finansomat)(?!biznes)(?!sport)[a-zA-Z0-9]{4,9}\.wp\.pl\//$xmlhttprequest`

**Comment by MajkiIT** [comment]
Ta reguła kiedyś pozwalała na oglądania filmów na wp.pl . Przejrzę dzisiaj i zobaczę czy gdzieś się pojawia.

**Comment by F4z** [comment]
@MajkiIT ok, dzięki za odpowiedź.

**Comment by MajkiIT** [comment]
@F4z dzięki za pomoc.

**Comment by F4z** [comment]
@MajkiIT jak ta reguła - `facet.wp.pl##._1gZ6Rt0` przestanie działać, to można wtedy dodać reguły z forum Adguarda - https://forum.adguard.com/index.php?threads/resolved-facet-wp-pl.16170/#post-114275
albo można je od razu dodać.

**Comment by MajkiIT** [comment]
@F4z Dzięki zmieniłem.
