### ISSUE TITLE
demotywatory.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1506]
Link - `http://demotywatory.pl/`

Ta reguła za dużo ukrywa:
`demotywatory.pl###main_container > .demots > article:nth-of-type(10)`

Oprócz tego można ukryć pozostałość po reklamie.
![image](https://cloud.githubusercontent.com/assets/11742596/20546418/4633fd84-b115-11e6-9f93-00af81863931.png)

Na przykład:
`demotywatory.pl##.abox-view-content.center`

**Comment by MajkiIT** [comment]
@F4z dzięki
