### ISSUE TITLE
do dodania

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1507]
prosze dodac napisy24.pl, satkurier.pl, emag.pl i extratorrent.cc

**Comment by xxcriticxx** [comment]
extratorrent.cc nie polish

**Comment by F4z** [comment]
@MajkiIT masz może więcej informacji na temat tych stron, o co dokładnie chodzi?

Na stronie napisy24.pl nie widzę żadnych reklam, jedynie przy próbie pobrania napisów wykrywa adblocka.
Tutaj jest do tego zgłoszenie - https://github.com/MajkiIT/polish-ads-filter/issues/1503

---

**satkurier.pl** domyślam się, że chodzi o te reklamy:

1. Na stronie głównej:

![image](https://cloud.githubusercontent.com/assets/11742596/20568686/8d63b6c6-b19d-11e6-9bf4-f2c548c092a6.png)

2. Na samym dole pod artykułem, ta sama reklama, na przykład tutaj - `http://satkurier.pl/news/153746/sport-wazny-dlaczego-slaba-ogladalnosc-premier-league.html`

![image](https://cloud.githubusercontent.com/assets/11742596/20568908/5c9d3d72-b19e-11e6-8999-c11b2cde15cf.png)

3. Puste miejsce po reklamie, ten sam link - `http://satkurier.pl/news/153746/sport-wazny-dlaczego-slaba-ogladalnosc-premier-league.html`

![image](https://cloud.githubusercontent.com/assets/11742596/20568958/9adb0984-b19e-11e6-9437-391d98d5b642.png)

4. Pozostałość po reklamie.

![image](https://cloud.githubusercontent.com/assets/11742596/20569062/03f1428a-b19f-11e6-8986-d5fd3de9a75b.png)

Na stronie `http://digi-tv.pl/` są podobne reklamy.

Reguły:
`digi-tv.pl,satkurier.pl##[id^="pasek_hollex"]`
`digi-tv.pl,satkurier.pl###SATKurierNews_top_750x100_r`
`digi-tv.pl,satkurier.pl##[id^="idmnet_"]`
`digi-tv.pl##[id^="banner_"]`
Dodatkowo można dodać jeszcze te dwie:
`||satkurier.pl/getRandomBanner`
`||satkurier.pl/laravel/banery/`

Na digi-tv.pl wykrywany jest też adblock.
![image](https://cloud.githubusercontent.com/assets/11742596/20569570/d08c50d6-b1a0-11e6-9174-0aac1cedea4e.png)

Na przykład:
`@@||digi-tv.pl/js/ads.js$script`

---

Na emag.pl później spojrzę.
Odnośnie extratorrent.cc , to w sumie najlepiej będzie tutaj zgłaszać - https://forums.lanik.us/viewtopic.php?f=64&t=33265

**Comment by MajkiIT** [comment]
@F4z Dzięki

**Comment by lukjan32** [comment]
w napisy24.pl, chodzi mi o blokade pobierania napisow.
w satkurier.pl, o reklamy i nie ma pelnej tresci artykulow.
w emag.pl, brak na stroniej glownej slajdu.
w extratorrent.cc, brak forum.

musze dac te strony do wyjatkow.

**Comment by F4z** [comment]
@lukjan32 
1. Sprawdź proszę te reguły:
`||napisy24.pl/run/js/blad1.js$script`
`||napisy24.pl/run/js/blad2.js$script`
Gdyby nie działały, to odśwież kilka razy stronę `Ctrl + F5`, jeśli nadal nie będą działać, to dodaj te reguły:
`@@||google.com/*/ads.html$xmlhttprequest,subdocument,domain=napisy24.pl`
`napisy24.pl#@#.pub_300x250`
`napisy24.pl#@#.pub_300x250m`
`napisy24.pl#@#.pub_728x90`
`napisy24.pl#@#.text-ad`
`napisy24.pl#@#.textAd`
`napisy24.pl#@#.text_ad`
`napisy24.pl#@#.text_ads`
`napisy24.pl#@#.text-ads`
`napisy24.pl#@#.text-ad-links`
A jeśli korzystasz z uBlocka Origin to zamiast tych powyżej, dodaj te:
`napisy24.pl##script:inject(fuckadblock.js-3.2.0)`
`@@||google.com/*/ads.html$xmlhttprequest,subdocument,domain=napisy24.pl`
2. Możesz podać link do artykułu, gdzie nie ma pełnej treści?
Reklamy powinny już zostać zablokowane, gdyby jednak gdzieś były, to podaj proszę link i najlepiej zrób zrzut ekranu, żebym wiedział gdzie szukać.
3. Potem zobaczę.
4. Nie znam tej strony, więc może się mylę, ale ja forum widzę - `http://extratorrent.cc/forum/`

**Comment by lukjan32** [comment]
gdzie mam dodac te reguly w ublock?

kazdy artykul na kazdej stronie z strony glownej

**Comment by lukjan32** [comment]
dzieki, wszystko dziala, oprocz emag.pl
![bez tytulu](https://cloud.githubusercontent.com/assets/17565773/20640162/4cf07f0c-b3d7-11e6-864c-d0be7ac7513f.jpg)

**Comment by F4z** [comment]
@lukjan32 to artykuły na `satkurier.pl` też już Ci się normalnie wyświetlają?

Odnośnie `emag.pl`.
Możesz sobie dodać te reguły (w zakładce "Moje filtry"):
`emag.pl#@#[href^="http://pubads.g.doubleclick.net/"]`
`@@||pubads.g.doubleclick.net/gampad/ad$image,domain=www.emag.pl`
`@@||pagead2.googlesyndication.com/pagead/imgad$image,domain=www.emag.pl`
`@@||googletagmanager.com/gtm.js$script,domain=www.emag.pl`

Wtedy te obrazki powinny się wyświetlać, ale jak na jakiś klikniesz, to strona zostanie zablokowana przez uBlocka.
![image](https://cloud.githubusercontent.com/assets/11742596/20640620/6a8a2bf6-b3e3-11e6-9386-1c80d29f1425.png)

Po dodaniu tej reguły:
`@@||pubads.g.doubleclick.net/gampad/jump?iu=/*/Slider_Home_*&sz=*&`
uBlock nie powinien tego blokować, ale nie wiem czy na innych stronach nie pojawią się przez to reklamy.
Ewentualnie w zakładce "Moje reguły" możesz dodać to:
 `no-strict-blocking: pubads.g.doubleclick.net true`
Nie wiem, która z tych dwóch reguł jest lepsza.

**Comment by lukjan32** [comment]
tak, dobrze.

nie chce sie dodac do moje reguly

**Comment by xxcriticxx** [comment]
@lukjan32 a jaki jest probleml?

**Comment by lukjan32** [comment]
jak dodaje do tymczasowych regul, to nie pojawia sie i nie zapisuje.

mam  ublock origin

**Comment by xxcriticxx** [comment]
@lukjan32 dodajesz do zakladki MY FILTERS a potem APPLY CHANGES

**Comment by xxcriticxx** [comment]
@lukjan32 sorry nie doczytalem co @F4z napisal 

naciskasz na MY RULES potem na TEMPORARARY RULES potem EDIT i SAVE

**Comment by lukjan32** [comment]
dzieki, dziala

**Comment by lukjan32** [comment]
napisyy24.pl, znow maja blokade pobierania napisow

**Comment by MajkiIT** [comment]
@lukjan32 masz aktualne polskie filtry?

**Comment by lukjan32** [comment]
tak, mam.

tak.

**Comment by F4z** [comment]
@lukjan32 u mnie te dwie reguły cały czas działają:
`||napisy24.pl/run/js/blad1.js$script`
`||napisy24.pl/run/js/blad2.js$script`
Masz je dodane?

**Comment by MajkiIT** [comment]
@lukjan32 masz AAK filtry?

**Comment by MajkiIT** [comment]
@F4z dopisać te reguły do polskich filtrów?

**Comment by lukjan32** [comment]
prosze dopisac

**Comment by MajkiIT** [comment]
Gotowe

**Comment by lukjan32** [comment]
aktualizacja bedzie jutro?

**Comment by lukjan32** [comment]
prosze dodac dla wszystkich, dla emag.pl

**Comment by lukjan32** [comment]
czy jest szansa, abyscie dodali do pliku skrypt, dla wszystkich do emag.pl

emag.pl#@#[href^="http://pubads.g.doubleclick.net/"]
@@||pubads.g.doubleclick.net/gampad/ad$image,domain=www.emag.pl
@@||pagead2.googlesyndication.com/pagead/imgad$image,domain=www.emag.pl
@@||googletagmanager.com/gtm.js$script,domain=www.emag.pl

i do electro-torrent.pl

|http://$third-party,script,domain=electro-torrent.pl

**Comment by F4z** [comment]
@MajkiIT myślę, że można dodać te reguły.

**Comment by MajkiIT** [comment]
@lukjan32 @F4z a to nie miało być w Easylist?

**Comment by lukjan32** [comment]
dodacie do pliku?

**Comment by MajkiIT** [comment]
już jest dodane.

**Comment by lukjan32** [comment]
ok, dziiala, dzieki
