### ISSUE TITLE
grupazpr.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#1508]
Mimo filtru PL, roi się od reklam na stronach grupy ZPR Media.

Chodzi mi o strony murator itp, bo wszedłem teraz na strone eski i wyskoczył mi wielki baner z reklamą na całą strone, dla pocieszenia powiem że u góry był krzyżyk aby móc zamknąć, ale nie poto dodaje filtr PL aby oglądać reklamy.

**Comment by xxcriticxx** [comment]
podaj dokladne linky please

**Comment by blocker999** [comment]
Chodzi mi dokładnie o ich wszystkie radia, tv i prase oraz portale internetowe, jednym słowem wszysko.

http://www.grupazpr.pl/nasze-marki

**Comment by blocker999** [comment]
Dokładnie natknąłem się na reklamy na http://www.eska.pl oraz http://muratordom.pl ale jest tego więcej, ogólnie rzecz ujmując, strony od zpr media to jedno wysypisko reklam. ( śmieci ).

Pomaga tylko filtr:  Malvertising filter list by Disconnect‎ , ale nie każdy go używa a PL raczej wszyscy.

**Comment by Isamaul** [comment]
@blocker999 
Dziwne - na pewno nie dodałeś czegoś do wyjątków?
Mi się żadna reklama tam nie wyświetla - tylko popup z newsletterem...

**Comment by blocker999** [comment]
Sprawdze

**Comment by blocker999** [comment]
@Isamaul 

Masz racje, coś ja namieszałem, Przepraszam !!!.

**Comment by xxcriticxx** [comment]
+1
