### ISSUE TITLE
jbzd.cc

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#15096]
nowa końcówka, wcięło też `Y`.

uAssets już dało generichide na antyadblock.

**Comment by xMaap** [comment]
Chyba również można zablokować social
![Zrzut ekranu z 2019-11-07 02-38-40](https://user-images.githubusercontent.com/36385327/68352752-bfa6cd00-0107-11ea-9548-34c6030ed667.png)

**Comment by krystian3w** [comment]
Niekoniecznie można, jak utną teraz nagle `d` z nazwy lub będzie za kropką to i tak filtr padnie.

```
DABUR
DAD
DANCE
DATA
DATE
DATING
DATSUN
DAY
DCLK
DDS
DE
DEAL
DEALER
DEALS
DEGREE
DELIVERY
DELL
DELOITTE
DELTA
DEMOCRAT
DENTAL
DENTIST
DESI
DESIGN
DEV
DHL
DIAMONDS
DIET
DIGITAL
DIRECT
DIRECTORY
DISCOUNT
DISCOVER
DISH
DIY
DJ
DK
DM
DNP
DO
DOCS
DOCTOR
DODGE
DOG
DOMAINS
DOT
DOWNLOAD
DRIVE
DTV
DUBAI
DUCK
DUNLOP
DUPONT
DURBAN
DVAG
DVR
DZ
```
