### ISSUE TITLE
justwatch.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#15107]
Pozostałości po reklamach
`https://www.justwatch.com/pl/film/watchmen-straznicy`
![Zrzut ekranu z 2019-11-08 04-01-10](https://user-images.githubusercontent.com/36385327/68446306-a28ffe00-01dc-11ea-956f-7e0de3f7c97b.png)
![Zrzut ekranu z 2019-11-08 04-01-26](https://user-images.githubusercontent.com/36385327/68446307-a28ffe00-01dc-11ea-9357-0ddbb604b4d4.png)
Ukrywa ikonę YouTube
`https://www.justwatch.com/pl/film/watchmen-straznicy`
Włączone
![Zrzut ekranu z 2019-11-08 04-04-27](https://user-images.githubusercontent.com/36385327/68446446-fa2e6980-01dc-11ea-8a4a-a401cf96e28d.png)
Wyłączone
![Zrzut ekranu z 2019-11-08 04-04-48](https://user-images.githubusercontent.com/36385327/68446449-fef31d80-01dc-11ea-8152-76fb3261faa8.png)

**Comment by MajkiIT** [comment]
Niestety tego nie widzę

**Comment by krystian3w** [comment]
Też nie widzę, EasyListy zaktualizuj, @xxcriticxx  już miał z tym problem i po dniu mu zniknęło https://github.com/MajkiIT/polish-ads-filter/issues/14159

**Comment by krystian3w** [comment]
`www.justwatch.com#@#img[title="YouTube"]`
