### ISSUE TITLE
puste box na wp

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1511]
@F4z please check it out 

http://kobieta.wp.pl/szukala-ich-cala-ameryka-co-sie-z-nimi-stalo-6061716112168065g
http://opinie.wp.pl/muniek-staszczyk-nie-ma-podstaw-by-sie-nienawidzic-wszyscy-jestesmy-polakami-6061806391006337a
http://film.wp.pl/monica-bellucci-i-vincet-cassel-uklad-sie-nie-sprawdzil-6061640545932417g
http://gwiazdy.wp.pl/justin-bieber-pobil-fana-6061627179156097a
http://tech.wp.pl/chiny-testuja-rakiete-ktora-moze-niszczyc-samoloty-z-odleglosci-300-km-6061757318656641a
http://turystyka.wp.pl/tradycyjne-dania-z-15-panstw---sprawdz-czy-znasz-je-wszystkie-6060353938367617q

**Comment by F4z** [comment]
`film.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,opinie.wp.pl,tech.wp.pl,teleshow.wp.pl,turystyka.wp.pl##div[class^="_"][style^="min-height: 250px; line-height: 250px;"]`
`film.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,opinie.wp.pl,tech.wp.pl,teleshow.wp.pl,turystyka.wp.pl##div[class^="_"][style^="min-height:250px;line-height:250px;"]`
`film.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,opinie.wp.pl,tech.wp.pl,teleshow.wp.pl,turystyka.wp.pl##div[class^="_"][style^="min-height:200px;line-height:200px;"]`
`film.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,opinie.wp.pl,tech.wp.pl,teleshow.wp.pl,turystyka.wp.pl##div[class^="_"][style^="min-height: 200px; line-height: 200px;"]`
`film.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,opinie.wp.pl,tech.wp.pl,teleshow.wp.pl,turystyka.wp.pl##div[class^="_"][style^="min-height: 600px; line-height: 600px;"]`
`film.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,opinie.wp.pl,tech.wp.pl,teleshow.wp.pl,turystyka.wp.pl##div[class^="_"][style^="min-height:600px;line-height:600px;"]`

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z
Gotowe i dziękuję.
