### ISSUE TITLE
kayak.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#15111]
Cookies
```
https://www.kayak.pl/hotels
https://www.kayak.pl/magazine/
```
![Zrzut ekranu z 2019-11-08 07-02-52](https://user-images.githubusercontent.com/36385327/68453447-d297cb00-01f5-11ea-80ce-95d1e8765385.png)

Nie chce się załadować
`https://www.kayak.pl/routes/`
![Zrzut ekranu z 2019-11-08 07-06-58](https://user-images.githubusercontent.com/36385327/68453623-68335a80-01f6-11ea-83d2-ed1c4d70fad7.png)

**Comment by krystian3w** [comment]
Nie ładuje się, bo @kiboke popsuł:

`/gdpr/cookieconsent`

**Comment by kiboke** [comment]
I will remove blocking of cookieconsent.js from IDCAC, thanks. Also, rule ` www.kayak.pl##.cdk-overlay-container` may also leave scrolling disabled. IDCAC will deal with the cookie warning using javascript there.

**Comment by krystian3w** [comment]
Yesterday scroll no was locked.

**Comment by krystian3w** [comment]
@kiboke you not added exception for: ` https://www.kayak.pl/routes/`
