### ISSUE TITLE
pcformat.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#15125]
```
https://pcformat.pl
https://forum.pcformat.pl
```
![Zrzut ekranu z 2019-11-09 06-46-34](https://user-images.githubusercontent.com/36385327/68523688-b4e16900-02bc-11ea-8e3d-cfcad9a23f95.png)

**Comment by krystian3w** [comment]
podpiąłem pod filtr cd-action.
