### ISSUE TITLE
Manjaro Pamac mi nie działa

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#15126]
Hej ja znowu nie na temat przepraszam jakis czas temu pisalem na discordzie z @hawkeye116477 o Manjaro ale jak zamkneliscie serwer filtrow nie jestem w stanie napisac bo nie mamy powiązania Xd tak wiem dziwne 

Zainstalowalem manjaro od nowa doinstalowalem pamaca z linijki od niego ale sie nie uruchamia w sensie pojawia mi sie na sekunde ikonka programu na pasku i zaraz znika przyzwyczajony do windy szukam procesu w menagerze zadan KDE i dupa bo nie ma takiego zadania help nie wiem co robić Xd @xxcriticxx Daj label pytanie

**Comment by hawkeye116477** [comment]
A który pakiet zainstalowany, pamac-gtk czy pamac-qt, a może pamac-tray-appindicator?
Musisz zainstalować ten z dopiskiem gtk, tamten qt to alpha i może czasem sprawiać problemy, tzn. w ogóle się nie odpalać.
Do konsoli:
`sudo pacman -S pamac-gtk`.

Tak poza tym jest polskie forum Manjaro => https://forum.manjaro.pl/.

**Comment by gzenio22** [comment]
instalowalem ten z twoiej linijki wiec to GTK

**Comment by hawkeye116477** [comment]
@gzenio22 Post edytowałem, więc przeczytany uważnie do końca, bo nie dałeś odpowiedzi na dalszą część, więc nie wiem?

**Comment by gzenio22** [comment]
Po tej komendzie w terminalu sie otwiera ale z ikonki kurde nie a to feler

**Comment by hawkeye116477** [comment]
@gzenio22 Wejdź we właściwości ikony i sprawdź w sekcji Program, jakie tam polecenie masz wpisane.

**Comment by gzenio22** [comment]
pamac-manager tak jak kazales mi wpisac w terminal mowie odpala sie na sekunde z ikony i znika

**Comment by hawkeye116477** [comment]
@gzenio22 No to wypróbuj jeszcze `sudo pacman -Syu`.

**Comment by gzenio22** [comment]
zaczelo mi w terminalu zasysac aktualizacje :D

**Comment by hawkeye116477** [comment]
@gzenio22 Pomogła aktualizacja?

**Comment by gzenio22** [comment]
@hawkeye116477 Tak zalapalo :) dzieki za pomoc :)

**Comment by hawkeye116477** [comment]
@gzenio22 To co nie zamykasz?
