### ISSUE TITLE
przeslij.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15130]
strona pokazuje sie i znika

test link:
https://przeslij.com/JU

**Comment by krystian3w** [comment]
Anty-adblock też jest.

**Comment by krystian3w** [comment]
A znikanie robi też:

```
Filtr - ###adblockinfo
Lista filtrów - Adblock Warning Removal List 
```

Czyli trzeba by pisać do pingwina by go wyłączył w `Nano Defender Integration`.

**Comment by xxcriticxx** [comment]
ja pingwina latami nie widzialem

**Comment by krystian3w** [comment]
@olegwukr:

`@@||przeslij.com/*/js/advertisement.js$script`

i się naprawia całkowicie, skrypt robi pusty div:

`document.write('<div style="display:none;" id="bannerad">some banner ad</div>');`

**Comment by xxcriticxx** [comment]
thanks
