### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#15137]
Coraz więcej logujących się ma chamsko włączony tryb "dotykowy" / dla niedowidzących z wielkimi 3-4 kaflami na rząd:

https://userstyles.org/styles/177216/5-columns-youtube-please
https://userstyles.org/styles/177214/youtube-smaller-thumbnails
https://userstyles.org/styles/177183/make-youtube-small-again
https://userstyles.org/styles/177156/fixed-nov-2019-youtube-layout
https://userstyles.org/styles/177154/youtube-old-home-style
https://userstyles.org/styles/177057/youtube
https://userstyles.org/styles/177035/youtube-small-thumbnails

**Comment by hawkeye116477** [comment]
A tak apropo, mają pojawić się na telewizorach w aplikacji YT reklamy na pół ekranu. Cieszycie się?
https://www.komputerswiat.pl/aktualnosci/aplikacje/youtube-na-telewizory-wprowadza-reklamy-zaslaniajace-niemal-pol-ekranu/eld415c

**Comment by xxcriticxx** [comment]
zajebiscie

**Comment by krystian3w** [comment]
Ja rozwaliłem pilot do TV 📺  ale raczej mam za stary software i aplikacje YouTube w TV 📺.

**Comment by MajkiIT** [comment]
@hawkeye116477 tego jeszcze nam brakowało

**Comment by hawkeye116477** [comment]
U mnie aplikacja nazywa się po prostu YouTube bez tego dopiska TV i ostatnia aktualizacja była 16 października. Mam system WebOS. Pod nazwą Youtube TV występuje na Androidzie => `https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.unplugged`.
