### ISSUE TITLE
onet.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#15139]
mobilna główna ma jakiś dziwne puste kwadraty:

`##.onet-ad`

![obraz](https://user-images.githubusercontent.com/35370833/68903773-745e7100-073c-11ea-8ce6-527ad0bb1d1e.png) |
--- |

**Comment by krystian3w** [comment]
Pewnie na PC one generują pop-up anty-adblock.

**Comment by trackerless** [comment]
#15184

**Comment by krystian3w** [comment]
U mnie pół już nie ma, więc zamykam.

Bluru i pop-upa antyadblock na razie na komórkach nie ma (iOS Safari raczej nie wspieramy).
