### ISSUE TITLE
cda-online.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1513]
https://cda-online.pl/rekiny-wojny/

extra shit sie otwiera pop-ups http://firefox-241114.reupd.net/protect/enable

**Comment by xxcriticxx** [comment]
`http://jutquieta.xyz/sup/sda6p_cir9a/lp002/?ubn=Firefox&kw=1066307&aid=noads&cid=ffexnorpuf&cc=cc001&lp=jlp2dffex`

`http://travelwednesday.com/videos/content49fo1.php`

**Comment by MajkiIT** [comment]
Sprawdź proszę to

`||searchiq.xyz/$domain=cda-online.pl`

**Comment by xxcriticxx** [comment]
@MajkiIT no good trzeba chyba na easylist forum dodac

**Comment by xxcriticxx** [comment]
please dodaj filtry z easylist forum 

`@@||4*.net/*.js|$domain=openload.co`
`@@||5*.net/*.js|$domain=openload.co`
`||openload.co/*packed.`
`||openload.co/*license.`
