### ISSUE TITLE
webtest.app

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15138]
test link:
https://webtest.app/?url=https://wp.pl

**Comment by krystian3w** [comment]
Google niby się ładuje o 2 sekundy dłużej.

**Comment by krystian3w** [comment]
I chyba przeciążono serwer, bo stron z małą oglądalnością nie idzie sprawdzić:

![obraz](https://user-images.githubusercontent.com/35370833/68960526-9efa0980-07d0-11ea-9c03-4c4f0f84e318.png)

Z 48 godzin czekam na test, trochę za długo...

**Comment by xxcriticxx** [comment]
lol to zamykamy temat
