### ISSUE TITLE
dead strony filmowe

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15146]
sprawdzcie to jeszcze swoim magicznymi narzedziami

http://filmbit.ws/
tele-wizja.is
http://darmowa-tv.pl/
http://boxfilm.pl/
http://kino123.pl/
nasze-kino.tv
http://nasze-kino.online/
http://darmowa-telewizja.online/
http://centrum-mangi.ninja/
http://tele-wizja.ru/

**Comment by krystian3w** [comment]
- `filmbit.ws` error 523 nie wskazuje na usunięcie / ban;
- `tele-wizja.is` możesz kupić, włączają się spam reklamy;
- `kino123.pl` sami coś popsuli; raczej dalej ktoś płaci by nie stracić domeny/hostingu?;
- `nasze-kino.tv` zwinęli się, domenę można wykupić;
- `nasze-kino.online` możesz kupić, włączają się spam reklamy;
- `darmowa-telewizja.online` wygląda na ban.
- `centrum-mangi.ninja` domena została, może za jakiś czas do kupienia

Pozostałe trzeba w whois sprawdzić czy są wolne.

**Comment by xxcriticxx** [comment]
http://openkatalog.ml/
abcast.net
filmowo.co
http://allonline.pl/

**Comment by krystian3w** [comment]
- `openkatalog.ml` - otwiera po chwili seks kamerki...
- `abcast.net` możliwe do kupienia
- `filmowo.co` zablokuję w kad przekręty "przekierowania do przekrętów" (otwiera `cinematekę.pl`)
- `allonline.pl` już blokowane jako przekręt, ale w marcu padli.

**Comment by xxcriticxx** [comment]
http://boxfilm.pl/

**Comment by krystian3w** [comment]
mają wykupioną do `maja 2020`. Jak pisałem, ją trzeba było w whois.

darmowa-tv.pl - 1 grudnia 2019, nie zapłacą to każdy może kupić jak usługodawca zwolni.
nasze-kino.tv - do września 2020
tele-wizja.ru - do lutego 2020

online i ninja nie chce mi się sprawdzać w egzotycznym whois.

**Comment by xxcriticxx** [comment]
sorry znowu dubluje

**Comment by krystian3w** [comment]
No to pozostaje do większości rok czekania lub rzeźnia, licząc że ktoś już siedzi w pierdlu lub dostał taką karę, że żyje gorzej niż na debecie.

**Comment by MajkiIT** [comment]
http://filmbit.ws/ - zobaczymy co będzie z tym. 
@xxcriticxx @krystian3w Dziękuję

**Comment by MajkiIT** [comment]
@krystian3w filmowo.co leci na przekręt ...
