### ISSUE TITLE
cdahd.ml

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15145]
adblock na main page

![Capture](https://user-images.githubusercontent.com/15007183/68994066-9a733680-084c-11ea-8f4f-b2317a17524c.PNG)

**Comment by krystian3w** [comment]
u mnie czysto, może tylko chrome ma problem.

**Comment by MajkiIT** [comment]
@xxcriticxx ochrona prywatności w FF to robi

**Comment by xxcriticxx** [comment]
ja uzywam chrome moze szybciej pihole
