### ISSUE TITLE
gierkionline.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15148]
adblock

test link:
https://www.gierkionline.pl/gry/Gry+Zrecznosciowe/Bubble+Shooter+Arcade.html

**Comment by krystian3w** [comment]
```
@@||games.softgames.com/assets/showads.js$script,domain=games.softgames.com
@@||games.softgames.com/assets/advertisement.js$script,domain=games.softgames.com
```

@hawkeye116477  cookies u nas czy męczyć Kiboke?

![obraz](https://user-images.githubusercontent.com/35370833/68994471-a4fcf280-0883-11ea-9c3a-33149105279a.png) |
--- |

**Comment by xxcriticxx** [comment]
ja mam 14.5 lat znowu nie zagram  :(

**Comment by hawkeye116477** [comment]
@krystian3w Jak nie ma wymogów co do wieku, to może być u nas. No chyba, że dodajemy nowe ustawienie, mam ... lat z opcją wpisania ile lat :smiley:

**Comment by xxcriticxx** [comment]
14.5 lat da rade?

**Comment by krystian3w** [comment]
Najpierw muszę zrobić, by mi z cache nie leciała gra po odblokowaniu, bo miałem przycisk "open" a teraz ją ładuje, że nawet dość szybko stopując to cookies nie ma.

**Comment by hawkeye116477** [comment]
@xxcriticxx Niestety za młody jesteś na grę w kulki :smiley:

**Comment by xxcriticxx** [comment]
bieda :(

**Comment by krystian3w** [comment]
Dobra postęp, w Incognito widać to cookies i można będzie kombinować z pieczeniem ciastek, jak ma to tracić do PCC / PZC.

🤣

**Comment by hawkeye116477** [comment]
Raczej nie ma co kombinować, skoro nie ma dodatkowego przycisku do zgody, jest jedynie „play" jak w każdej grze i tyle.

**Comment by xxcriticxx** [comment]
zamykamy?

**Comment by hawkeye116477** [comment]
Nie, bo jeszcze antyadblocka nikt nie ”naprawił".

**Comment by xxcriticxx** [comment]
tam napewno bendzie tego wiecej trzeba inne gry sprawdzac
