### ISSUE TITLE
chomikuj.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#15142]
`https://chomikuj.pl/action/PrivateMessage`

Jak nie padnie nagle jak openload, to jest reklama u zalogowanych użytkowników:

`chomikuj.pl#?##InboxTable > tbody > tr:-abp-has(> td > .spons)`

![obraz](https://user-images.githubusercontent.com/35370833/68992618-1336ba80-086e-11ea-842d-aad40fa2c9a3.png) |
--- |

**Comment by MajkiIT** [comment]
@krystian3w Dziękuje
