### ISSUE TITLE
virpe.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15144]
test link:
https://virpe.com/tvp-online-free/lesniczowka/

![Capture](https://user-images.githubusercontent.com/15007183/68993941-1cfaf680-084b-11ea-8d1f-11e505f051f2.PNG)

**Comment by krystian3w** [comment]
Mnie pomaga:

`virpe.com#@#.adsBox`

ostatecznie generichide.
