### ISSUE TITLE
vodgo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15157]
widziej link do filmu z wylaczonym ublock?

test link:
https://vodgo.pl/film/krol-lew/2023

![Inked69029240-abe74a80-09d4-11ea-833a-ab19d496a645_LI](https://user-images.githubusercontent.com/15007183/69055604-2d8ea680-09dc-11ea-9329-d77308415d3f.jpg)

**Comment by xMaap** [comment]
Może jestem ślepy, ale nie widzę różnicy z włączanym
![Zrzut ekranu z 2019-11-18 15-57-12](https://user-images.githubusercontent.com/36385327/69063132-3f903980-0a1c-11ea-866f-a43b269e9214.png)

Proponuje za to poukrywać te z "Chili".

**Comment by MajkiIT** [comment]
@xMaap Dodane
@xxcriticxx Ja też nie widzę różnicy.

**Comment by xxcriticxx** [comment]
ja nie widze tej sekcji na stronie i jeszcze nie wiem dlaczego

**Comment by krystian3w** [comment]
`##.bg-black.w-100.list-group-item` nie łapie poprawnie sekcji `Chili`.

**Comment by xxcriticxx** [comment]
cos mi wycina linki ale jeszcze nie wiem co

**Comment by krystian3w** [comment]
Ja mogę powiedzieć, że nie filtry polskie reklamowe / social / rodo-ciasteczkowe / elementów irtujących z suplementem RSS.

Sprawdź Pi-Hole i listy aktywowowane ręcznie poza stockowymi (domyślnymi).

**Comment by xxcriticxx** [comment]
nie pihole nie ublock testowalem z wlaczonym i wylzczonym

szybciej będzie geo lock z usa

@krystian3w masz vpn z usa zeby zrobic test?

**Comment by krystian3w** [comment]
Mam jedynie Firefox proxy USA (cloudflare).

**Comment by xxcriticxx** [comment]
ok to szukam dalej
