### ISSUE TITLE
allegrolokalnie.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15158]
RODO

**Comment by krystian3w** [comment]
wycięte:

https://github.com/MajkiIT/polish-ads-filter/blob/fe74ea07d18b8eec229cd13e0c7d14e45909e010/cookies_filters/adblock_cookies.txt#L2162

Nie działają sieciówki to mocno odświeżyć stronę i zniknie.

**Comment by hawkeye116477** [comment]
Może listy nie zaktualizował, bo to było wczoraj dopiero...
@xxcriticxx Zamykamy
