### ISSUE TITLE
wroclawskiejedzenie.pl

### ISSUE THREAD

**Issue by J4cku** [MajkiIT/polish-ads-filter#15154]
### Zrzut ekranu
<img width="925" alt="Screenshot 2019-11-17 at 18 09 34" src="https://user-images.githubusercontent.com/9265664/69010941-6d667700-0965-11ea-8920-1143836e6a82.png">

### Link bezpośredni
http://wroclawskiejedzenie.pl/2019/11/15/shakshuka-wroclaw-czasami-lepsze-jest-wrogiem-dobrego/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na stronę ;)

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome
**Rozszerzenia i skrypty:**
uBlock Origin 1.23
nano defender 15.0.0.170

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda

**Comment by krystian3w** [comment]
`wroclawskiejedzenie.pl##+js(abort-current-inline-script.js, parseInt, adblock)`

albo cudem może:

```
@@||lib.wtg-ads.com/prebid/prebid_*.js$xmlhttprequest,domain=joemonster.org|innpoland.pl|wroclawskiejedzenie.pl
```
