### ISSUE TITLE
variatkowo.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#15153]
### Zrzut ekranu
![Screenshot_20191117_145518](https://user-images.githubusercontent.com/19818572/69008396-4babc680-094a-11ea-960e-729ac2c7299c.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Antyadblock.

**Comment by krystian3w** [comment]
`variatkowo.pl##+js(aopr, anOptions)`

**Comment by krystian3w** [comment]
a i ktoś psuje plugin komentarzy, na wyłączonym uBO dało się dodać.
