### ISSUE TITLE
empik.com

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#15163]
https://www.empik.com/salony-empik

Brak mapki.

**Comment by xxcriticxx** [comment]
za mocno piholem? u mnie jest gitara

![Capture](https://user-images.githubusercontent.com/15007183/69187857-5e103680-0ae9-11ea-9b01-a78a5fe59cab.PNG)

**Comment by krystian3w** [comment]
Nie pi-hole, na Firefox wcięło.

**Comment by krystian3w** [comment]
`empik.com##^.cookies-accept` to chyba musi iść do lamusa i trzeba przerobić na ukrywanie CSS-em / skryptem.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/15164
