### ISSUE TITLE
black-friday.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15162]
BŁĄD : brak logo oral-b ( " Wyróżnione oferty BLACK FRIDAY "  oraz reklamy, ( po prawo i na dole )

**Comment by krystian3w** [comment]
bo to spamerski button sam zobacz:

```
www.black-friday.pl#@#A[href*="k.tradedoubler.com/click"]
```

tracking.

**Comment by hawkeye116477** [comment]
Sądziłem, że to EasyPrivacy, ale najwyraźniej winny jest pan `Peter Lowe`. Także zażalenia prosimy kierować do tego pana :smile:.

**Comment by krystian3w** [comment]
`k.tradedoubler.com/click` jakby padło:

![obraz](https://user-images.githubusercontent.com/35370833/69501132-43cbc380-0f02-11ea-9b53-f0bd0afce48e.png) |
--- |

Z wycinanych jest też `pl##a[href*="://converti.se/click/"]`

**Comment by krystian3w** [comment]
Jeszcze znalazłem taki:

> uBlock Origin zablokował wczytywanie następującej strony:
> ```
> https://ad.doubleclick.net/ddm/trackclk/N879210.1932310LIGHTREACTION/B21649943.228341901;dc_trk_aid=451667121;dc_trk_cid=105509398;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=?http://clk.tradedoubler.com/click?a=2990528&p=292755&g=24630940&tduid=003d591dd5cc456e850c03c426efd740
> ````
> Powodem zablokowania jest filtr
> ```
>  ||doubleclick.net^
> ```
>
> Filtr znajduje się na liście: `Peter Lowe's Ad and tracking server list`  • `POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda`

**Comment by hawkeye116477** [comment]
Czyli trzeba by stworzyć listę odblokowującą afiliacje, bo Majki blokuje chyba świadomie o ile pamiętam.
