### ISSUE TITLE
natemat.pl

### ISSUE THREAD

**Issue by Cysioland** [MajkiIT/polish-ads-filter#15175]
### Zrzut ekranu

![Zrzut ekranu z 2019-11-23 21-47-11](https://user-images.githubusercontent.com/913522/69485093-fdf7f800-0e3a-11ea-893b-107387be7ea5.png)

### Link bezpośredni

https://natemat.pl/235195,slychac-strzaly-co-wiemy-o-filmiku-z-miejsca-katastrofy-smolenskiej

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Wejść na stronę
2. Przescrollować trochę

### Moja konfiguracja
**Przeglądarka internetowa:** Google Chrome Wersja 78.0.3904.108 (Oficjalna wersja) (64-bitowa)

**Rozszerzenia i skrypty:** uBlock Origin, uMatrix

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Oficjalne polskie filtry przeciwko alertom o Adblocku
4. uBlock filters​​​​​
5. uBlock filters – Badware risks​​​​​
6. uBlock filters – Privacy​​​​​
7. uBlock filters – Resource abuse
8. uBlock filters – Unbreak
9. EasyPrivacy
10. Malware Domain List
11. Malware domains
12. Peter Lowe’s Ad and tracking server list
13. Nano Filters
14. Nano Filters - Whitelist

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Naprawione chyba, że zamykają wątek bez PR w wykonaniu @olegwukr.

w dodatku wymuś aktualizację: `Oficjalne polskie filtry przeciwko alertom o Adblocku`

https://github.com/MajkiIT/polish-ads-filter/issues/15167#issuecomment-557252205 - ręcznie możesz skopiować skrypt lub filtr dopuszczający (kompatybilny z Adblock / ABP / AdGuard)

**Comment by Cysioland** [comment]
Niestety dalej mi nie działa ;__;

**Comment by krystian3w** [comment]
Ręcznie sprawdź w uBO listę `Oficjalne polskie filtry przeciwko alertom o Adblocku` czy jest w kodzie domena `natemat`.

2 dni temu działał skrypt jak i filtr dopuszczający zapytania `xhr`.

**Comment by Cysioland** [comment]
@krystian3w Jest: `@@||lib.wtg-ads.com/prebid/prebid_*.js$xmlhttprequest,domain=joemonster.org|innpoland.pl|dadhero.pl|wroclawskiejedzenie.pl|natemat.pl`, ale dalej mi nie działa. Może nas wykiwali?

**Comment by krystian3w** [comment]
No to może w Chrome nie działa samo dopuszczenie, ja bym nie szedł w `generichide`, bo trzeba by wyciąć ręcznie z 10 ikonek social jakie wyciekną.

Spróbuj artykuł odświeżyć po przez `CTRL + F5`.

**Comment by Cysioland** [comment]
@krystian3w Próbowałem nawet "Opróźnij pamięć podręczną i wymuś ponowne załadowanie" z narzędzi deweloperskich

**Comment by krystian3w** [comment]
No to zobacz czy w Chrome masz wyłączony mechanizm blokady natrętnych reklam?

Jak nie to się doda skrypt `natemat.pl##+js(abort-current-inline-script.js, parseInt, adblock)`

On raczej już zadziała.

**Comment by Cysioland** [comment]
@krystian3w Ta linijka zadziałała, dzienia

**Comment by krystian3w** [comment]
@olegwukr  zobacz z chrome / operą jak działa samo dopuszczenie, nie działa to pod chromium i jakieś 80% użytkowników może być niezbędny skrypt.

**Comment by deejayscream81** [comment]
Ta sama zabawa na weszlo.com w safari na IOS. Jest ktoś kto wie co i gdzie trzeba dodać/jaki filtr żeby to się nie pojawiało??

**Comment by krystian3w** [comment]
jak twój blocker na iOS obsługuje filtry własne to przetestuj:

`@@||lib.wtg-ads.com/prebid/prebid_$domain=weszlo.com`

albo:

`@@||weszlo.com^$generichide`

Dla samego iOS nie widzę sensu globalnie używać generichide - wyciek przycisków social / reklam wycinanych generykiem.

**Comment by deejayscream81** [comment]
Wystarczyła ta pierwsza reguła.Wygląda,że zadziałało:)Dzięki!

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/ae5a36fdf37d971533624fd1025ecfcda30d0a62#diff-6de60f294b8bd23c752f8fcbece875b1

**Comment by deejayscream81** [comment]
Na weszło znowu się pojawia. (IOS- Adguard). Dodałem Polish Privacy Filters i Polish Anti Adblock Filters do filtrów niestandardowych,czyszczenie danych podręcznych Safari i update filtrów do wersji z 26.11 i dalej to samo.Akurat na tej stronie to jest jakaś zmora :) Co mogę jescze dodać?

**Comment by krystian3w** [comment]
Najlepiej zgłoś problem przy pomocy AdGuard.

Bez sprawdzania co wyłapują zostaje tylko:

```
@@||weszlo.com^$generichide
```

Do przetestowania. 😰😨

**Comment by deejayscream81** [comment]
Oni chyba też nie do konca wiedzą,ostatnio jak pisałem,to pytali czy jest Annoyances filter aktywny.Pozostaje mi testować dalej.

**Comment by krystian3w** [comment]
Opcjonlanie może to robi problem:

`weszlo.com##.adv`

https://github.com/MajkiIT/polish-ads-filter/blob/1c558ec991c16dfd71abe8108bd14410269df737/polish-adblock-filters/adblock.txt#L2970

uBO ma CSS-em wycinane a prostego filtra nie usunięto.

Fix do ręcznych filtrów:

```
weszlo.com#@#.adv
```

**Comment by deejayscream81** [comment]
Czyli,to ostatnie mam dodać jako regułę własną?

**Comment by krystian3w** [comment]
Tak i zobaczyć czy strona odpuści?

Jak tak to filtr się może usunie lub podklei:

"`!NOT (Plafrom iOS)`"

**Comment by krystian3w** [comment]
I w przypadku @Cysioland chyba uMatrix wymusza używanie skryptowego filtru (pewnie nadrzędnie blokuje `/prebid/prebid_`).

**Comment by deejayscream81** [comment]
> Tak i zobaczyć czy strona odpuści?
> 
> Jak tak to filtr się może usunie lub podklei:
> 
> "`!NOT (Plafrom iOS)`"
> 
> Bo zakładam, że w ABP na PC nikt nie ma adquesto.

Nie odpuszcza,tak chodzi tylko o IOS,bo na mac os/pc nie ma tego problemu z tym zestawem filtrów

**Comment by deejayscream81** [comment]
Ok,pozbierałem do kupy wszystkie ewentualne możliwe filtry,które mogą wpłynąć na usunięcie adquesto ze strony weszlo.com na IOS. Testowałem chyba pół nocy.Aktualnie dodane do reguł:

@@||weszlo.com^$generichide
@@weszlo.com##.adv
@@||lib.wtg-ads.com/prebid/prebid_$domain=weszlo.com
forsal.pl,kresy.pl,mambiznes.pl,prnews.pl,weszlo.com#%#AG_abortInlineScript(/adBlock/, 'parseInt');
natemat.pl##+js(abort-current-inline-script.js, parseInt, adblock)

I chyba tylko ten pierwszy go usuwa.Ale usuwa go w ten sposób,że usuwa również komentarze użytkowników pod artykułem :)

![IMG_6F95BAAF2D0B-1](https://user-images.githubusercontent.com/58123985/70863110-011b6b00-1f45-11ea-820d-61b23b7ec170.jpeg)

Czy można coś jeszcze z tym zrobić?

**Comment by krystian3w** [comment]
```
@@weszlo.com##.adv
```

to jest niepoprawny filtr. Powinien wyglądać tak:

`weszlo.com#@#.adv`

**Comment by deejayscream81** [comment]
Ok,usunięte,zostały więc tylko 3.

**Comment by krystian3w** [comment]
Sprawdź może jeszcze: `@@||weszlo.com^$genericblock`

to wyłącza niby filtry co są napisane specjalnie pod domenę `weszlo.com` lub chyba nawet cały zakres domen "`.com`".

**Comment by deejayscream81** [comment]
Zmieniłem @@||weszlo.com^$generichide  na @@||weszlo.com^$genericblock
Strona wygląda tak jak ma wyglądać!Komentarze są.
Pojawiają się jedynie jakies flash'owe banery,które ewentualnie mogę dodać do adguarda.
Czyli rzeczywiście,możłiwe,że IOS jak mówisz nie obsługuje genericblock.
