### ISSUE TITLE
komputronik.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15171]
black week sale 

test link:
https://www.komputronik.pl/informacje/jaki-router-wifi-10-porad/

**Comment by hawkeye116477** [comment]
Ale to nawet nie ma podpiętego linku. A jeżeli to ma być wyprzedaż w sklepie, no to to będzie raczej dla @KonoromiHimaries.

**Comment by xxcriticxx** [comment]
@hawkeye116477 test link w pierwszym poscie

**Comment by KonoromiHimaries** [comment]
@hawkeye116477 sezonówek nie dodaje, to bez sensu.
