### ISSUE TITLE
Czytaj więcej na onecie i spółce

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#15185]
Ktoś się chyba kiedyś pytał (może @blocker999)  czy da się coś zrobić z tym, że czasem jak klika się na artykuł, to przekierowuje na podstronę i trzeba ponownie kliknąć „czytaj dalej", żeby przeczytać. Otóż można to obejść, w FF wchodzimy do `about:config`, szukamy `network.http.sendRefererHeader` i ustawiamy na 0 i voila. W następnej wersji Waterfoksa będzie to też w opcjach/preferencjach jako `wysyłanie nagłówka odsyłającego`.

W przypadku Chromium i spółki jest takie coś => `https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin`.

**Comment by xMaap** [comment]
Albo ja nie potrafię z tego rozszerzenia korzystać, albo nie wiem.

**Comment by hawkeye116477** [comment]
@xMaap Referer Control status musi być na active, Block Javascript Referer też na active i default referer for all other sites na block. Potem oczywiście musisz odświeżyć tamtą onetową stronę jeżeli wcześniej ją załadowałeś.

**Comment by krystian3w** [comment]
Adam chyba napisał do użytku własnego skrypt pod Onet lub WP (oba mają ten dziadowski button) z AdGuard.

W skrypcie robi kilka sprawdzań i po upewnieniu się po chwili klika w button.
Niby blokowanie refferer lepsze i bardziej uniwersalne.

**Comment by xMaap** [comment]
@hawkeye116477 to może na Onecie działa, ale nie mogę znaleźć artykułu co wymaga kliknąć "Czytaj dalej".
Na WP nic nie robi https://portal.abczdrowie.pl/ i artykuł "Ukryty cukier. W tych produktach się go nie spodziewasz" link bezpośredni https://www.wp.pl/?s=portal.abczdrowie.pl/ukryty-cukier-w-tych-produktach-sie-go-nie-spodziewasz&src01=8d289 
Zauważyłem, że jak ma się włączone rozszerzenie to nie można się zalogować na github 
![Zrzut ekranu z 2019-11-26 12-46-15](https://user-images.githubusercontent.com/36385327/69629127-53efba00-104c-11ea-8b24-377e72460dd8.png)

**Comment by hawkeye116477** [comment]
No to pewnie na GH musiałbyś dodać wyjątek, by nie blokowało tego nagłówka.
W przypadku WP no faktycznie niestety nie działa, widać mają inną cwaną metodę.

**Comment by xMaap** [comment]
Na FF wszystko działa jak należy.

**Comment by hawkeye116477** [comment]
Na FF to czy coś zmieni się czy nie, to na WP nie ma tego „czytaj więcej", jakby przygotowali to jedynie dla Chromium.

**Comment by krystian3w** [comment]
A to wam leci, ja mam "errory 500" https://www.interia.tv/wideo-czym-jest-udar-neurolog-wyjasnia,vId,2791745#

**Comment by krystian3w** [comment]
@hawkeye116477 ten klucz ma wątek na bugzilli by im podrzucić video Interii?

**Comment by hawkeye116477** [comment]
@krystian3w No to faktycznie jest błąd. Chyba raczej powinieneś założyć nowy wątek na bugzilii.

**Comment by hawkeye116477** [comment]
@krystian3w PlayStation Store też się psuje przez blokowanie referrera. Tak więc te rozwiązanie Moz://i nie jest takie dobre, lepsze jest raczej właśnie te rozszerzenie, bo można dodawać strony do białej listy.

**Comment by krystian3w** [comment]
W sumie to nie działa też wtedy IMGUR / SNAG.GY, niby da się wgrać bez śledzenia np. github daje radę.

**Comment by krystian3w** [comment]
`network.http.referer.XOriginPolicy` to stara nazwa `network.http.sendRefererHeader`?

**Comment by hawkeye116477** [comment]
@krystian3w Chyba raczej nie...
https://wiki.mozilla.org/Security/Referrer
