### ISSUE TITLE
auratorrent.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1518]
co jest nie tak z tą strona i czemu po próbie pobrania torrentu pokazują się  jakieś dziwne strony których ciężko się pozbyć. Jedyna możliwość to zamkniecie ich, ale to jest strasznie uciążliwe.

http://auratorrent.pl/index.php

||thnqemehtyfe.com/$script,domain=auratorrent.pl
||104.198.188.213/$popup
||xjsqhlfscjxo.com/$script,domain=auratorrent.pl

**Comment by MajkiIT** [comment]
@F4z @xxcriticxx 

czy możecie sprawdzić czy u Was jest ok. Potrzebne aktualne filtry Polskie + KAD

**Comment by xxcriticxx** [comment]
jest ok od czasu do czasu cos miga ale to jest standard

**Comment by xxcriticxx** [comment]
just in case dodam do easylist

**Comment by F4z** [comment]
Żeby tak "nie migało" można dodać tę regułę - `auratorrent.pl##script:inject(noeval.js)` (działa tylko w uBlocku).
W ogóle jak tam coś pobrać?
Za każdym razem widzę link do strony `z0x.pl`, która jest blokowana przez KAD (i prawidłowo).
Trzeba się zarejestrować żeby widzieć "normalne" linki?
Ta strona wygląda mi na jakieś oszustwo 😛

**Comment by xxcriticxx** [comment]
dokladnie

**Comment by xxcriticxx** [comment]
@MajkiIT please dodaj z easylist forum

`|http://$third-party,script,domain=auratorrent.pl`

**Comment by xxcriticxx** [comment]
@MajkiIT for chrome add

`||104.198.188.21^$popup`

**Comment by MajkiIT** [comment]
@F4z @xxcriticxx Dzięki
