### ISSUE TITLE
shop.buybox.pl

### ISSUE THREAD

**Issue by jacekch** [MajkiIT/polish-ads-filter#15180]
### Link bezpośredni

https://github.com/MajkiIT/polish-ads-filter/blob/72cde6727486a7304556c9c3ec4d67d033aabf01/polish-adblock-filters/adblock.txt#L4514

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
Błędna reguła. Wskazana reguła filtru nic nie zmienia dla użytkownika, nie eliminuje żadnych reklam, tylko zabrania załadowania skryptu wykorzystywanego przez sklepy internetowe.
1. Wystarczy wejść na strony sklepu internetowego korzystającego ze skryptu, np. https://dadada.pl/
2. Wejście na strony z aktywnym adblockiem i bez adblocka nie wykazuje żadnej różnicy dla użytkownika.

### Moja konfiguracja
**Przeglądarka internetowa:**
Dowolna
**Rozszerzenia i skrypty:**
Skrypt pobierany z adresu blokowanego przez problematyczną regułę, czyli shop.buybox.click
**Listy filtrów:**
1. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda

**Comment by MajkiIT** [comment]
W tym wypadku nie ... ==> ale w innym już tak. Nawet na stronie 

![obraz](https://user-images.githubusercontent.com/11302675/69519662-e152e180-0f5a-11ea-89d4-aab419bafbf2.png)

**Comment by jacekch** [comment]
Po zrzucie zgaduję, że chodzi o stronę https://getbuybox.com/dla-wydawcow/ -- na tej stronie w ogóle nie pojawia się "shop.buybox.click", więc tym bardziej reguła nie robi żadnej różnicy dla użytkownika.

**Comment by MajkiIT** [comment]
ale rozchodzi, że użytkownik może budować ==> "Promuj opisywane produkty na wiele sposobów. Nie tylko opis, recenzja, czy średnia cena mają znaczenie. Pokaż precyzyjnie swoim użytkownikom, gdzie i w jakiej cenie mogą kupić opisywany przez Ciebie produkt. Wstaw widget BUY.BOX. Przykład możesz zobaczyć obok na zdjęciu"

**Comment by jacekch** [comment]
Dlaczego uważacie, że uzupełnienie wpisu na blogu o informację o cenach opisywanego produktu w sklepach internetowych jest niewłaściwe? To nie jest reklama, tylko informacja będąca dodatkiem związanym z treścią wpisu. Blokując wyświetlanie tej informacji ograniczacie wartość strony dla czytelnika, a chodzi chyba o to, żeby ludziom ułatwiać życie, a nie utrudniać.

**Comment by MajkiIT** [comment]
Jak mówiłem wcześniej na FB, to nie ja siedzę i nie analizuję cały polski internet. Wpadło zgłoszenie i wyświetlane były produkty trochę od czapy. 

![obraz](https://user-images.githubusercontent.com/11302675/69521803-1ada1b80-0f60-11ea-99c9-2da33727f8a7.png)

**Comment by jacekch** [comment]
Rozumiem. Poproszę zatem o link do tego zgłoszenia. Najwyraźniej było nierzetelne, albo słabo je sprawdziliście. Po pierwsze, widget nie wyświetla różnych produktów, tylko informacje o cenach w sklepach internetowych dla jednego wskazanego produktu. Po drugie, dodana reguła nie działa.

Skoro wystarczyło jedno zgłoszenie, żeby regułę dodać. To proszę potraktować to moje zgłoszenie jako zgłoszenie usunięcia tej reguły. Też powinno wystarczyć.

**Comment by MajkiIT** [comment]
zgłoszenie było mailowe. Nie mam jak udostępnić. Reguła została usunięta i podmieniona na działającą. Dodatkowo Państwa domena jest blokowana przez inne listy i to nie jest problemem rozumiem ?

**Comment by jacekch** [comment]
Nie rozumiem -- po co dodawać regułę, która nie blokuje reklam, tylko obniża wartość dla czytelnika strony? Popieram ideę filtrów. Sam korzystam z adblocka. Ale w tym przypadku blokowanie treści tego typu mija się z celem, bo finalnie użytkownik traci, a nie zyskuje. O co chodziło w oryginalnym zgłoszeniu?  Podano jakiś adres URL? Może wskazano na jakieś nadużycie systemu i będziemy w stanie pomóc inaczej?

Wspominając o innych regułach, pewnie chodzi o `||buybox.click/analytics.js` z EasyPrivacy. Ta reguła wyłącza skrypt raportujący zdarzenia związane z interakcją użytkowników z widgetem. Jeśli ktoś nie chce, żeby analizowano jego zachowanie w sieci, to nie musi się na to zgadzać. Może to wyłączyć w ustawieniach serwisu wydawcy, przeglądarki lub właśnie za pomocą adbloka. Nie ogranicza wartości dla czytelnika i nie mamy z tym problemu.

**Comment by jacekch** [comment]
Ponownie zgłaszam potrzebę usunięcia tej bezwartościowej dla czytelnika reguły.

**Comment by MajkiIT** [comment]
Ta reguła jest jak widać potrzebna ==> https://help.getbuybox.com/pl/articles/1290807-skrypty-sklepowe. 

"Służą one do poprawnego rejestrowania transakcji i naliczania prowizji odpowiednim partnerom."

Zgłosiłem te filtry do filtrów prywatności. Jak dodadzą to usunę od siebie.

**Comment by jacekch** [comment]
Bez możliwości rozliczania prowizji ten system nie ma racji bytu i przestanie dostarczać wartość dla czytelników. Mechanizm rozliczania prowizji nie rejestruje informacji o czytelniku i w żaden sposób nie narusza jego prywatności. Dlatego nadal uważam, że reguła jest bezwartościowa dla czytelnika i proszę o jej usunięcie.

**Comment by MajkiIT** [comment]
To już ich decyzja... jak tylko będę wydawał nową wersję to usunę.
