### ISSUE TITLE
popkulturysci.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#15197]
### Zrzut ekranu

![obraz](https://user-images.githubusercontent.com/32641928/69750362-dfe90b00-114c-11ea-857a-14161c62380f.png)

### Link bezpośredni
https://popkulturysci.pl/najbardziej-niedoceniani-superbohaterzy-marvela/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na stronę
2. Jeśli nie pojawi się od razu to trzeba zacząć przewijać w dół

### Moja konfiguracja
**Przeglądarka internetowa:**
Firefox

**Rozszerzenia i skrypty:**
uBlock
Nano Defender

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Przeciwko Alertom (Anti-adblock)
4. Polskie Filtry Elementów Irytujących (Annoyance)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by Barticf** [comment]
U mnie dalej info o wyłączeniu adblock

**Comment by krystian3w** [comment]
Bo nie "wymagamy" używania listy Bogachenko jako niezbędnej?

Bogachenko dodał:

```
||pagead2.googlesyndication.com^$important,script,redirect=noopjs,domain=popkulturysci.pl
||pagead2.googlesyndication.com^$important,xmlhttprequest,redirect=nooptext,domain=popkulturysci.pl
```

regexy poprawił przy okazji dopisując "o". U mnie są zbędne.
