### ISSUE TITLE
lowcygier.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#15191]
@hawkeye116477  zgłasza, że strona znowu wciska post "prosimy nie blokować reklam".

Zakładam, że to jest pewnie nieaktualne: https://github.com/olegwukr/polish-privacy-filters/commit/b9302d48a9a1a70b4a3727eb8c80c371a8dcf871#diff-6de60f294b8bd23c752f8fcbece875b1R346

nowsze `@@||lowcygier.pl/zgodny-pieprz.js?*=*&ad_keyword=$script,domain=lowcygier.pl`
to można uciąć: `?*=*&ad_keyword=$script` do postaci:

```
@@||lowcygier.pl/zgodny-pieprz.js&domain=lowcygier.pl
```

---

Pewnie potem zmienią na np. `slodki-cukier.js?...&ad_slot=`

**Comment by hawkeye116477** [comment]
No coż, przynajmniej nie stosują metody WP.

**Comment by hawkeye116477** [comment]
No coż, przynajmniej nie stosują metody WP.
