### ISSUE TITLE
epicdrama.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15193]

**Comment by krystian3w** [comment]
![Epic_Fetus_Icon](https://user-images.githubusercontent.com/35370833/69654717-88c43700-1075-11ea-834a-90e5f0bcd944.png) ![Epic_Fetus_App](https://user-images.githubusercontent.com/35370833/69654700-806bfc00-1075-11ea-81e2-3bf8b7cb97a9.png) ![Epic_Fetus_Tears](https://user-images.githubusercontent.com/35370833/69654752-9b3e7080-1075-11ea-9680-099ba17f8af1.png)

![Item_altar](https://user-images.githubusercontent.com/35370833/69654723-8e218180-1075-11ea-8292-d6200fcd68a3.png)
