### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by Tasiorsa** [MajkiIT/polish-ads-filter#15195]
### Zrzut ekranu
![Screenshot_2019-11-26 Rock'N'Rolla RocknRolla](https://user-images.githubusercontent.com/35109319/69663430-84ece080-1086-11ea-99df-41eae6cf9cb7.png)

### Link bezpośredni

https://www.filmweb.pl/film/Rock%27N%27Rolla-2008-441997

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na filmweb.pl i otworzyć dowolny film

### Moja konfiguracja
**Przeglądarka internetowa:**
Firefox 70.0.1
**Rozszerzenia i skrypty:**
Adguard

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Wszystkie dodatkowe filtry polskie 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Na Firefox z Nano nie widzę problemu - pomaga html filtering?

opcjonalnie wyłącz oba i po każdym odświeżaj:

<ol><li>

```
filmweb.pl#@#+js(nano-remove-elements-onready, #skyBanner)
```

<li>

```
filmweb.pl#@#^#mainSkyBanner-pl_PL > script:has-text(skyBanner)
```

</ul>

**Comment by krystian3w** [comment]
Na Firefox z Nano nie widzę problemu - pomaga html filtering?

We filtrach własnych spróbuj:

```
filmweb.pl$$#mainSkyBanner-pl_PL > script:has-text(skyBanner)
```

**A i czy wymagane jest zalogowanie się...?**

---

@F4z  / @adamwr

**Comment by krystian3w** [comment]
Na Firefox z Nano nie widzę problemu - pomaga html filtering?

We filtrach własnych spróbuj:

```
filmweb.pl$$#mainSkyBanner-pl_PL > script[tag-contains="skyBanner"]
```

**A i czy wymagane jest zalogowanie się...?**

---

@F4z  / @adamwr

**Comment by Tasiorsa** [comment]
nie pomoglo :( 
filmweb.pl$$#mainSkyBanner-pl_PL > script:has-text(skyBanner)
Dalej to samo

**Comment by krystian3w** [comment]
Bo błąd składni musi być: `[tag-contains="skyBanner"]`

**Comment by AdamWr** [comment]
Nie potrafię tego u siebie odtworzyć, ale sprawdź proszę tę regułę:
```
filmweb.pl$$script[tag-content="adblockDisplayInformation."][min-length="8000"][max-length="50000"]
```

**Comment by krystian3w** [comment]
Wycina komunikat.

**Comment by krystian3w** [comment]
Na moje bruździ: `EasyList Polish`.

Po `Ctrl + F5` mam komunikat...

**Comment by Tasiorsa** [comment]
filmweb.pl$$script[tag-content="adblockDisplayInformation."][min-length="8000"][max-length="50000"]
rozwiązuje problem!
Dziękuje!

**Comment by AdamWr** [comment]
Tutaj jest podobne zgłoszenie - https://github.com/AdguardTeam/AdguardFilters/issues/44783#issuecomment-558698232, ale szczerze mówiąc nie wiem, która reguła to powoduje, bo u mnie ten komunikat się nie pojawia.
Zaraz dodam tę regułę do filtrów AdGuarda (aktualizacja będzie dostępna za około 1-2 godziny).

Dziękuję za sprawdzenie.

**Comment by krystian3w** [comment]
@gwarser w uBO planowane jest kiedyś ulepszanie spinnetów?

```
filmweb.pl##+js(aeld, document.querySelector, adblockDisplayInformation.)
filmweb.pl##+js(acis, /adblockDisplayInformation\./, document.querySelector)
```

Bo niby są nieskuteczne jak się zablokuje:

`filmweb.pl###mainSkyBanner-pl_PL`

Opcjonalnie to efekt "`Race condition`"...

i wtedy tylko pomoże html filtering:

```
filmweb.pl##^script:has-text(adblockDisplayInformation.):min-text-length(8000)
```

**Comment by gwarser** [comment]
@krystian3w zamieniłeś miejscami? Składnia nie pasuje.

**Comment by krystian3w** [comment]
Czyli AdGuard ma odwróconą względem uBo?

Mnie chodzi że AdGuard chyba z 3 razy optymalizował swój spinnet na acis by blokował więcej/szybciej.

**Comment by gwarser** [comment]
Gdzie oni mają dokumentację do tego?

     filmweb.pl#%#//scriptlet("prevent-addEventListener", "document.querySelector", "adblockDisplayInformation.")

Wygląda na odwrócone. `adblockDisplayInformation` to event, w uBO event jest pierwszy.

**Comment by AdamWr** [comment]
To mój błąd, tam nie powinno być `prevent-addEventListener` a `abort-current-inline-script`.

Dokumentacja jest tutaj - https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md

**Comment by gwarser** [comment]
Są obydwa.

**Comment by AdamWr** [comment]
W jakim sensie są obydwa?
Mam na myśl, że tutaj dodałem złą regułę - https://github.com/AdguardTeam/AdguardFilters/commit/2896d59e8e3522cfd32aa5db34e5a0440cdea12b#diff-48cd1634a8224e1bf6ce278856af9f2aR5707

Zamiast `prevent-addEventListener` powinno być `abort-current-inline-script`.

**Comment by gwarser** [comment]
Filtr AG jest odwrócony.

A ten `filmweb.pl#%#AG_abortInlineScript` dwie linie niżej to nie?

**Comment by krystian3w** [comment]
Pewnie w takim że tylko ABP zostaje w tyle i zamiast naprawiać filtry proceduralne to wymyślili '`...if-hidden..`".

**Comment by AdamWr** [comment]
>A ten filmweb.pl#%#AG_abortInlineScript dwie linie niżej to nie?

Ten był wcześniej, został tylko lekko zmieniony.
W tym przypadku ta reguła jest obecnie tylko dla aplikacji, bo aplikacje w wersji stabilnej nie obsługują "scriptletów".

Poprawiłem i teraz jest prawidłowo - https://github.com/AdguardTeam/AdguardFilters/commit/4fcdae228719317d462c79b440122ecf7256ac56

`AG_abortInlineScript` ma inną składnię - `AG_abortInlineScript(regex, property, debug)`
