### ISSUE TITLE
xboxforum.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#15205]
Social
`https://xboxforum.pl/threads/aktualizacja-2-1.204327/#post-1426189
`
![Zrzut ekranu z 2019-11-29 01-35-34](https://user-images.githubusercontent.com/36385327/69836367-9847a980-1248-11ea-81b1-491a963602ea.png)

**Comment by krystian3w** [comment]
`##.shareButtons-button:not([class*="mail"]):not([class*="link"])`
