### ISSUE TITLE
[styl] [interia] [pomponik] iplsc.com

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#15209]
nie można dawać łapek w górę:+1:/w dół:-1: do komentarzy. 

https://www.styl.pl/zdrowie/news-domowe-sposoby-na-oczyszczanie-jelit,nId,3357751

https://www.pomponik.pl/plotki/news-martyna-wojciechowska-i-przemyslaw-kossakowski-kolejna-proba,nId,3324311

https://motoryzacja.interia.pl/samochody-nowe/testy/news-volkswagen-arteon-2-0-tdi-cos-wiecej-niz-design,nId,2914439

<details open><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +413 | \|\|hit.interia.pl^ | -- | `www.styl.pl` | 3 | script | `https://rkm.hit.interia.pl/getrec1,nPack,1,startNo,9?callback=recommendCallback1&e%5B%5D=3357751-article&uid=f75d7e8f-fce0-4ee6-a71b-d1d7f93b3fb2&ref=styl.pl&cnt=8` |
| +413 | \|\|hit.interia.pl^ | -- | `www.styl.pl` | 3 | script | `https://rkmp2041.hit.interia.pl/getrec1,nPack,1,startNo,0?callback=recommendCallback0&e%5B%5D=3357751-article&uid=c85d2ec9-1a32-4b9c-b999-b4ea65eeb3c9&ref=styl.pl&cnt=9` |
| +413 | \|\|shoperia.pl/$subdocument | -- | `www.styl.pl` | 3 | frame | `https://shoperia.pl/embed,34416.html` |
| +251 | \|\|hub.com.pl^$3p | -- | `www.styl.pl` | 3 | script | `https://a.hub.com.pl/z-ostatniej-chwili/zoc.js` |
| +249 | \|\|imasdk.googleapis.com^$3p | -- | `www.styl.pl` | 3 | script | `https://imasdk.googleapis.com/js/sdkloader/ima3.js` |
| +249 | \|\|interia.pl/iframe$subdocument | -- | `www.styl.pl` | 3 | frame | `https://ifr-lib.interia.pl/iframe.html?s=nsaudience&u=www.styl.pl/zdrowie/news-domowe-sposoby-na-oczyszczanie-jelit,nId,3357751&c=false` |
| +248 | \|\|hit.gemius.pl^ | -- | `www.styl.pl` | 3 | script | `https://stream-interia.hit.gemius.pl/gemiuslib.js` |
| +247 | \|\|emisja.adsearch.pl/$xmlhttprequest | -- | `www.styl.pl` | 3 | xhr | `https://emisja.adsearch.pl/_/ads2/?QAPS_interia=9e8f2b41220dd505de5cdf808ccc40df&host=www.styl.pl` |
| +247 | \|\|js.iplsc.com/inpl.webpush/*/inpl.webpush.js$script | -- | `www.styl.pl` | 3 | script | `https://js.iplsc.com/inpl.webpush/1.0.38/inpl.webpush.js` |
| +247 | \|\|iplsc.com/internal/inpl.copy/*/inpl.copy.js$domain=pl | -- | `www.styl.pl` | 3 | script | `https://w.iplsc.com/internal/inpl.copy/1.0.10/inpl.copy.js` |
| +247 | \|\|emisja.adsearch.pl/$xmlhttprequest | -- | `www.styl.pl` | 3 | xhr | `https://emisja.adsearch.pl/_/itxads/?hash=95ac86a13b23160c3c8775e3ffc25b6a&prefix=interia&host=www.styl.pl` |
| +247 | \|\|shoperia.pl/$subdocument | -- | `www.styl.pl` | 3 | frame | `https://shoperia.pl/embed,34416.html` |
| +247 | \|\|prywatnosc.interia.pl/rodo-iframe$subdocument | -- | `www.styl.pl` | 3 | frame | `https://prywatnosc.interia.pl/rodo-iframe?origin=https%3A%2F%2Fwww.styl.pl` |
| +247 | /gemius.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/gemius.js?v=3` |
| +247 | \|\|criteo.net^$3p | -- | `www.styl.pl` | 3 | script | `https://static.criteo.net/js/ld/publishertag.js` |
| +247 | /ads.js? | -- | `www.styl.pl` | 3 | script | `https://js.iplsc.com/inpl.abd/2.0.24/ads.js?pub_300x250&pub_300x250m&pub_728x90&text-ad&textAd&text_ad&text_ads&text-ads&text-ad-links` |
| +247 | google-analytics.com/analytics.js | << | `www.styl.pl` |  | script | `https://www.google-analytics.com/analytics.js` |
| +247 | \|\|google-analytics.com^ | -- | `www.styl.pl` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +247 | \|\|hit.interia.pl^ | -- | `www.styl.pl` | 3 | script | `https://iwa3.hit.interia.pl:8443/iwa_core?ts=1575063961616&u=https%3A%2F%2Fwww.styl.pl%2Fzdrowie%2Fnews-domowe-sposoby-na-oczyszczanie-jelit%2CnId%2C3357751&sh=styl.pl` |
| +247 | /iwa.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/iwa.js` |
| +247 | /xgemius. | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/xgemius.js` |
| +247 | \|\|iplsc.com/internal/inpl.copy/*/inpl.copy.js$domain=pl | -- | `www.styl.pl` | 3 | script | `https://w.iplsc.com/internal/inpl.copy/1.0.10/inpl.copy.js` |
| +247 | /gemius.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/gemius.js?v=3` |
| +240 | \|\|hub.com.pl^$3p | -- | `www.styl.pl` | 3 | script | `https://a.hub.com.pl/z-ostatniej-chwili/zoc.js` |
| +238 | \|\|imasdk.googleapis.com^$3p | -- | `www.styl.pl` | 3 | script | `https://imasdk.googleapis.com/js/sdkloader/ima3.js` |
| +237 | \|\|interia.pl/iframe$subdocument | -- | `www.styl.pl` | 3 | frame | `https://ifr-lib.interia.pl/iframe.html?s=nsaudience&u=www.styl.pl/zdrowie/news-domowe-sposoby-na-oczyszczanie-jelit,nId,3357751&c=false` |
| +236 | \|\|hit.gemius.pl^ | -- | `www.styl.pl` | 3 | script | `https://stream-interia.hit.gemius.pl/gemiuslib.js` |
| +236 | \|\|emisja.adsearch.pl/$xmlhttprequest | -- | `www.styl.pl` | 3 | xhr | `https://emisja.adsearch.pl/_/ads2/?QAPS_interia=9e8f2b41220dd505de5cdf808ccc40df&host=www.styl.pl` |
| +236 | \|\|js.iplsc.com/inpl.webpush/*/inpl.webpush.js$script | -- | `www.styl.pl` | 3 | script | `https://js.iplsc.com/inpl.webpush/1.0.38/inpl.webpush.js` |
| +236 | \|\|iplsc.com/internal/inpl.copy/*/inpl.copy.js$domain=pl | -- | `www.styl.pl` | 3 | script | `https://w.iplsc.com/internal/inpl.copy/1.0.10/inpl.copy.js` |
| +236 | \|\|emisja.adsearch.pl/$xmlhttprequest | -- | `www.styl.pl` | 3 | xhr | `https://emisja.adsearch.pl/_/itxads/?hash=95ac86a13b23160c3c8775e3ffc25b6a&prefix=interia&host=www.styl.pl` |
| +236 | \|\|shoperia.pl/$subdocument | -- | `www.styl.pl` | 3 | frame | `https://shoperia.pl/embed,34416.html` |
| +235 | /gemius.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/gemius.js?v=3` |
| +235 | \|\|criteo.net^$3p | -- | `www.styl.pl` | 3 | script | `https://static.criteo.net/js/ld/publishertag.js` |
| +235 | \|\|prywatnosc.interia.pl/rodo-iframe$subdocument | -- | `www.styl.pl` | 3 | frame | `https://prywatnosc.interia.pl/rodo-iframe?origin=https%3A%2F%2Fwww.styl.pl` |
| +235 | /ads.js? | -- | `www.styl.pl` | 3 | script | `https://js.iplsc.com/inpl.abd/2.0.24/ads.js?pub_300x250&pub_300x250m&pub_728x90&text-ad&textAd&text_ad&text_ads&text-ads&text-ad-links` |
| +235 | google-analytics.com/analytics.js | << | `www.styl.pl` |  | script | `https://www.google-analytics.com/analytics.js` |
| +235 | \|\|google-analytics.com^ | -- | `www.styl.pl` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +235 | \|\|hit.interia.pl^ | -- | `www.styl.pl` | 3 | script | `https://iwa3.hit.interia.pl:8443/iwa_core?ts=1575063949848&u=https%3A%2F%2Fwww.styl.pl%2Fzdrowie%2Fnews-domowe-sposoby-na-oczyszczanie-jelit%2CnId%2C3357751&sh=styl.pl` |
| +235 | /iwa.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/iwa.js` |
| +235 | /xgemius. | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/xgemius.js` |
| +235 | \|\|iplsc.com/internal/inpl.copy/*/inpl.copy.js$domain=pl | -- | `www.styl.pl` | 3 | script | `https://w.iplsc.com/internal/inpl.copy/1.0.10/inpl.copy.js` |
| +235 | /gemius.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/gemius.js?v=3` |
| +191 | \|\|hub.com.pl^$3p | -- | `www.styl.pl` | 3 | script | `https://a.hub.com.pl/z-ostatniej-chwili/zoc.js` |
| +190 | \|\|hit.interia.pl^ | -- | `www.styl.pl` | 3 | script | `https://rkm.hit.interia.pl/getrec1,nPack,1,startNo,9?callback=recommendCallback1&e%5B%5D=3357751-article&uid=bb331077-527e-4955-b7a1-6eda073f0e9e&ref=styl.pl&cnt=8` |
| +190 | \|\|hit.interia.pl^ | -- | `www.styl.pl` | 3 | script | `https://rkmp2041.hit.interia.pl/getrec1,nPack,1,startNo,0?callback=recommendCallback0&e%5B%5D=3357751-article&uid=386adc43-d95f-4fce-bb0c-c263c0a764b9&ref=styl.pl&cnt=9` |
| +189 | \|\|imasdk.googleapis.com^$3p | -- | `www.styl.pl` | 3 | script | `https://imasdk.googleapis.com/js/sdkloader/ima3.js` |
| +189 | \|\|interia.pl/iframe$subdocument | -- | `www.styl.pl` | 3 | frame | `https://ifr-lib.interia.pl/iframe.html?s=nsaudience&u=www.styl.pl/zdrowie/news-domowe-sposoby-na-oczyszczanie-jelit,nId,3357751&c=false` |
| +188 | \|\|hit.gemius.pl^ | -- | `www.styl.pl` | 3 | script | `https://stream-interia.hit.gemius.pl/gemiuslib.js` |
| +188 | \|\|emisja.adsearch.pl/$xmlhttprequest | -- | `www.styl.pl` | 3 | xhr | `https://emisja.adsearch.pl/_/ads2/?QAPS_interia=9e8f2b41220dd505de5cdf808ccc40df&host=www.styl.pl` |
| +188 | \|\|js.iplsc.com/inpl.webpush/*/inpl.webpush.js$script | -- | `www.styl.pl` | 3 | script | `https://js.iplsc.com/inpl.webpush/1.0.38/inpl.webpush.js` |
| +188 | \|\|shoperia.pl/$subdocument | -- | `www.styl.pl` | 3 | frame | `https://shoperia.pl/embed,34416.html` |
| +187 | \|\|iplsc.com/internal/inpl.copy/*/inpl.copy.js$domain=pl | -- | `www.styl.pl` | 3 | script | `https://w.iplsc.com/internal/inpl.copy/1.0.10/inpl.copy.js` |
| +187 | \|\|emisja.adsearch.pl/$xmlhttprequest | -- | `www.styl.pl` | 3 | xhr | `https://emisja.adsearch.pl/_/itxads/?hash=95ac86a13b23160c3c8775e3ffc25b6a&prefix=interia&host=www.styl.pl` |
| +187 | \|\|shoperia.pl/$subdocument | -- | `www.styl.pl` | 3 | frame | `https://shoperia.pl/embed,34416.html` |
| +187 | /gemius.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/gemius.js?v=3` |
| +187 | \|\|criteo.net^$3p | -- | `www.styl.pl` | 3 | script | `https://static.criteo.net/js/ld/publishertag.js` |
| +187 | \|\|prywatnosc.interia.pl/rodo-iframe$subdocument | -- | `www.styl.pl` | 3 | frame | `https://prywatnosc.interia.pl/rodo-iframe?origin=https%3A%2F%2Fwww.styl.pl` |
| +187 | /ads.js? | -- | `www.styl.pl` | 3 | script | `https://js.iplsc.com/inpl.abd/2.0.24/ads.js?pub_300x250&pub_300x250m&pub_728x90&text-ad&textAd&text_ad&text_ads&text-ads&text-ad-links` |
| +187 | google-analytics.com/analytics.js | << | `www.styl.pl` |  | script | `https://www.google-analytics.com/analytics.js` |
| +187 | \|\|google-analytics.com^ | -- | `www.styl.pl` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +187 | \|\|hit.interia.pl^ | -- | `www.styl.pl` | 3 | script | `https://iwa3.hit.interia.pl:8443/iwa_core?ts=1575063901837&u=https%3A%2F%2Fwww.styl.pl%2Fzdrowie%2Fnews-domowe-sposoby-na-oczyszczanie-jelit%2CnId%2C3357751&sh=styl.pl` |
| +187 | /iwa.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/iwa.js` |
| +187 | /xgemius. | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/xgemius.js` |
| +187 | \|\|iplsc.com/internal/inpl.copy/*/inpl.copy.js$domain=pl | -- | `www.styl.pl` | 3 | script | `https://w.iplsc.com/internal/inpl.copy/1.0.10/inpl.copy.js` |
| +187 | /gemius.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/gemius.js?v=3` |
| +153 | \|\|hub.com.pl^$3p | -- | `www.styl.pl` | 3 | script | `https://a.hub.com.pl/z-ostatniej-chwili/zoc.js` |
| +151 | \|\|imasdk.googleapis.com^$3p | -- | `www.styl.pl` | 3 | script | `https://imasdk.googleapis.com/js/sdkloader/ima3.js` |
| +151 | \|\|hit.interia.pl^ | -- | `www.styl.pl` | 3 | script | `https://rkm.hit.interia.pl/getrec1,nPack,1,startNo,9?callback=recommendCallback1&e%5B%5D=3357751-article&uid=73a10ba2-3d54-4b21-994c-1d5816439c0e&ref=styl.pl&cnt=8` |
| +151 | \|\|hit.interia.pl^ | -- | `www.styl.pl` | 3 | script | `https://rkmp2041.hit.interia.pl/getrec1,nPack,1,startNo,0?callback=recommendCallback0&e%5B%5D=3357751-article&uid=7c2e25b5-ea67-46c6-ba3c-dcdb0c43cfd1&ref=styl.pl&cnt=9` |
| +151 | \|\|interia.pl/iframe$subdocument | -- | `www.styl.pl` | 3 | frame | `https://ifr-lib.interia.pl/iframe.html?s=nsaudience&u=www.styl.pl/zdrowie/news-domowe-sposoby-na-oczyszczanie-jelit,nId,3357751&c=false` |
| +150 | \|\|shoperia.pl/$subdocument | -- | `www.styl.pl` | 3 | frame | `https://shoperia.pl/embed,34416.html` |
| +149 | \|\|hit.gemius.pl^ | -- | `www.styl.pl` | 3 | script | `https://stream-interia.hit.gemius.pl/gemiuslib.js` |
| +149 | \|\|emisja.adsearch.pl/$xmlhttprequest | -- | `www.styl.pl` | 3 | xhr | `https://emisja.adsearch.pl/_/ads2/?QAPS_interia=9e8f2b41220dd505de5cdf808ccc40df&host=www.styl.pl` |
| +149 | \|\|js.iplsc.com/inpl.webpush/*/inpl.webpush.js$script | -- | `www.styl.pl` | 3 | script | `https://js.iplsc.com/inpl.webpush/1.0.38/inpl.webpush.js` |
| +149 | \|\|iplsc.com/internal/inpl.copy/*/inpl.copy.js$domain=pl | -- | `www.styl.pl` | 3 | script | `https://w.iplsc.com/internal/inpl.copy/1.0.10/inpl.copy.js` |
| +149 | \|\|emisja.adsearch.pl/$xmlhttprequest | -- | `www.styl.pl` | 3 | xhr | `https://emisja.adsearch.pl/_/itxads/?hash=95ac86a13b23160c3c8775e3ffc25b6a&prefix=interia&host=www.styl.pl` |
| +149 | \|\|shoperia.pl/$subdocument | -- | `www.styl.pl` | 3 | frame | `https://shoperia.pl/embed,34416.html` |
| +149 | /gemius.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/gemius.js?v=3` |
| +149 | \|\|criteo.net^$3p | -- | `www.styl.pl` | 3 | script | `https://static.criteo.net/js/ld/publishertag.js` |
| +148 | \|\|prywatnosc.interia.pl/rodo-iframe$subdocument | -- | `www.styl.pl` | 3 | frame | `https://prywatnosc.interia.pl/rodo-iframe?origin=https%3A%2F%2Fwww.styl.pl` |
| +148 | /ads.js? | -- | `www.styl.pl` | 3 | script | `https://js.iplsc.com/inpl.abd/2.0.24/ads.js?pub_300x250&pub_300x250m&pub_728x90&text-ad&textAd&text_ad&text_ads&text-ads&text-ad-links` |
| +148 | google-analytics.com/analytics.js | << | `www.styl.pl` |  | script | `https://www.google-analytics.com/analytics.js` |
| +148 | \|\|google-analytics.com^ | -- | `www.styl.pl` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +148 | \|\|hit.interia.pl^ | -- | `www.styl.pl` | 3 | script | `https://iwa3.hit.interia.pl:8443/iwa_core?ts=1575063863065&u=https%3A%2F%2Fwww.styl.pl%2Fzdrowie%2Fnews-domowe-sposoby-na-oczyszczanie-jelit%2CnId%2C3357751&sh=styl.pl` |
| +148 | /iwa.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/iwa.js` |
| +148 | /xgemius. | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/xgemius.js` |
| +148 | \|\|iplsc.com/internal/inpl.copy/*/inpl.copy.js$domain=pl | -- | `www.styl.pl` | 3 | script | `https://w.iplsc.com/internal/inpl.copy/1.0.10/inpl.copy.js` |
| +148 | /gemius.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/gemius.js?v=3` |
| +135 | \|\|hit.interia.pl^ | -- | `www.styl.pl` | 3 | script | `https://rkm.hit.interia.pl/getrec1,nPack,1,startNo,9?callback=recommendCallback1&e%5B%5D=3357751-article&uid=b9960e77-d30a-4bbd-9702-dcd09723ed79&ref=styl.pl&cnt=8` |
| +135 | \|\|hit.interia.pl^ | -- | `www.styl.pl` | 3 | script | `https://rkmp2041.hit.interia.pl/getrec1,nPack,1,startNo,0?callback=recommendCallback0&e%5B%5D=3357751-article&uid=8e44d2d1-a84f-45c3-849f-b520a4dc7cf6&ref=styl.pl&cnt=9` |
| +6 | \|\|hub.com.pl^$3p | -- | `www.styl.pl` | 3 | script | `https://a.hub.com.pl/z-ostatniej-chwili/zoc.js` |
| +3 | \|\|imasdk.googleapis.com^$3p | -- | `www.styl.pl` | 3 | script | `https://imasdk.googleapis.com/js/sdkloader/ima3.js` |
| +3 | \|\|interia.pl/iframe$subdocument | -- | `www.styl.pl` | 3 | frame | `https://ifr-lib.interia.pl/iframe.html?s=nsaudience&u=www.styl.pl/zdrowie/news-domowe-sposoby-na-oczyszczanie-jelit,nId,3357751&c=false` |
| +2 | \|\|hit.gemius.pl^ | -- | `www.styl.pl` | 3 | script | `https://stream-interia.hit.gemius.pl/gemiuslib.js` |
| +1 | \|\|shoperia.pl/$subdocument | -- | `www.styl.pl` | 3 | frame | `https://shoperia.pl/embed,34416.html` |
| +1 | \|\|emisja.adsearch.pl/$xmlhttprequest | -- | `www.styl.pl` | 3 | xhr | `https://emisja.adsearch.pl/_/ads2/?QAPS_interia=9e8f2b41220dd505de5cdf808ccc40df&host=www.styl.pl` |
| +1 | \|\|js.iplsc.com/inpl.webpush/*/inpl.webpush.js$script | -- | `www.styl.pl` | 3 | script | `https://js.iplsc.com/inpl.webpush/1.0.38/inpl.webpush.js` |
| +1 | \|\|iplsc.com/internal/inpl.copy/*/inpl.copy.js$domain=pl | -- | `www.styl.pl` | 3 | script | `https://w.iplsc.com/internal/inpl.copy/1.0.10/inpl.copy.js` |
| +1 | \|\|emisja.adsearch.pl/$xmlhttprequest | -- | `www.styl.pl` | 3 | xhr | `https://emisja.adsearch.pl/_/itxads/?hash=95ac86a13b23160c3c8775e3ffc25b6a&prefix=interia&host=www.styl.pl` |
| +1 | \|\|shoperia.pl/$subdocument | -- | `www.styl.pl` | 3 | frame | `https://shoperia.pl/embed,34416.html` |
| +1 | /gemius.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/gemius.js?v=3` |
| +1 | \|\|criteo.net^$3p | -- | `www.styl.pl` | 3 | script | `https://static.criteo.net/js/ld/publishertag.js` |
| +1 | \|\|prywatnosc.interia.pl/rodo-iframe$subdocument | -- | `www.styl.pl` | 3 | frame | `https://prywatnosc.interia.pl/rodo-iframe?origin=https%3A%2F%2Fwww.styl.pl` |
| +0 | /ads.js? | -- | `www.styl.pl` | 3 | script | `https://js.iplsc.com/inpl.abd/2.0.24/ads.js?pub_300x250&pub_300x250m&pub_728x90&text-ad&textAd&text_ad&text_ads&text-ads&text-ad-links` |
| +0 | google-analytics.com/analytics.js | << | `www.styl.pl` |  | script | `https://www.google-analytics.com/analytics.js` |
| +0 | \|\|google-analytics.com^ | -- | `www.styl.pl` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +0 | \|\|hit.interia.pl^ | -- | `www.styl.pl` | 3 | script | `https://iwa3.hit.interia.pl:8443/iwa_core?ts=1575063715243&u=https%3A%2F%2Fwww.styl.pl%2Fzdrowie%2Fnews-domowe-sposoby-na-oczyszczanie-jelit%2CnId%2C3357751&sh=styl.pl` |
| +0 | /iwa.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/iwa.js` |
| +0 | /xgemius. | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/xgemius.js` |
| +0 | \|\|iplsc.com/internal/inpl.copy/*/inpl.copy.js$domain=pl | -- | `www.styl.pl` | 3 | script | `https://w.iplsc.com/internal/inpl.copy/1.0.10/inpl.copy.js` |
| +0 | /gemius.js | -- | `www.styl.pl` | 3 | script | `https://iwa.iplsc.com/gemius.js?v=3` |
</details>

**Comment by hawkeye116477** [comment]
EasyPrivacy psuje.

**Comment by krystian3w** [comment]
No to tak czy siak przydałoby się namierzyć konkretny filtr.

**Comment by hawkeye116477** [comment]
@xxcriticxx To nie Social i łapki są do naprawy, a nie wycięcia.

**Comment by xxcriticxx** [comment]
@hawkeye116477 pasuje?

**Comment by hawkeye116477** [comment]
@xxcriticxx :ok: 
@krystian3w `@@||iwa.iplsc.com/iwa.js$script,domain=www.styl.pl`

**Comment by krystian3w** [comment]
@olegwukr dodasz do swojej czy w reklamowej "Bugi EasyPrivacy"?

**Comment by krystian3w** [comment]
A i problem ma też często większość wpisów interii i pomponika.

**Comment by hawkeye116477** [comment]
@krystian3w Lista olega nie jest domyślna w uBO, więc raczej powinno to trafić do reklamowej.

**Comment by krystian3w** [comment]
Jest podana, i tak pewnie nie dadzą rady odtworzyć, wystarczy że cudem się załadował kiedyś portal z wyłączonym blokowaniem i potem strona olewa że przywrócono blokady i nawet usunięto dane z przeglądarki o odwiedzeniu witryny.

Tak jakby interia robiła odcisk przeglądarki  (opcjonalnie może po IP) i uznała Internautę za człowieka a nie bota.

**Comment by hawkeye116477** [comment]
`Jest podana`
O co konkretnie chodzi? Podałeś jedynie wersję adblockera, a nie napisałeś czy to uBO czy inny wynalazek :smile:.

**Comment by MajkiIT** [comment]
@krystian3w Chyba już działa

**Comment by hawkeye116477** [comment]
@MajkiIT Coś słabo sprawdzasz.
Czasem też komentarze znikają.

**Comment by krystian3w** [comment]
A znikanie to nawet nie wiem co robi.

`otherwise you need to clean your cookies / local storage for the domain "iplsc.com".`

takie coś dokleiłem do zgłoszenia w EasyList.

**Comment by krystian3w** [comment]
@hawkeye116477  jeszcze opcja że Oleg zrobił wyjątek dla trackerów i odblokwał dla jego subskrybentów i Majki używa.

**Comment by hawkeye116477** [comment]
@krystian3w Nic nowego nie dodał. Bardziej właśnie podejrzewam, że ma wyłączone EP i może teraz dopiero włączył i nic nie zobaczył, bo dopiero po wyczyszczeniu danych jest efekt.

**Comment by MajkiIT** [comment]
@krystian3w @hawkeye116477 @xxcriticxx Dzięki
