### ISSUE TITLE
wiktormeble.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15218]
buttons

**Comment by krystian3w** [comment]
@hawkeye116477  co to za 💩:

https://www.google.pl/search?q=Wiktor+Meble+Salon+meblowy+Tarnobrzeg&ludocid=11567467292239089308&lpsid=3778590443661095064&source=sh/x/localposts&lsig=AB86z5VuYAwhrX0VTjzjXlp2SoQ3#lpstate=pid:3778590443661095064

![obraz](https://user-images.githubusercontent.com/35370833/69983333-bce89d80-1536-11ea-9966-f964c799ec38.png) |
--- |

Jak dla mnie nie social i guzik niebieski w `Inne.txt`.

**Comment by hawkeye116477** [comment]
@krystian3w Jakiś feedback

**Comment by hawkeye116477** [comment]
@krystian3w 
`https://www.butlerbranding.com/social-media/google-my-business-social-network/`

**Comment by krystian3w** [comment]
Coś im nie wyszło, ten pop-up blokuję ocenę, a niebieskim przyciskiem wracam znowu na ich stronę.
