### ISSUE TITLE
mamadu.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#15228]
`https://mamadu.pl/140787,jak-zmienic-negatywne-podejscie-do-swiata-neurony-lustrzane-czym-sa
`
![Zrzut ekranu z 2019-12-03 19-35-40](https://user-images.githubusercontent.com/36385327/70079141-68abef00-1604-11ea-853e-51a41b007dfd.png)

**Comment by krystian3w** [comment]
uAssets próbowało ale im nie wyszło:

```
mamadu.pl##+js(acis, Object.defineProperty, requestAnimationFrame)
```

---

Ja proponuję dla iOS/ABP:

```
@@||lib.wtg-ads.com/prebid/prebid_*.js$xmlhttprequest,domain=aszdziennik.pl|dadhero.pl|innpoland.pl|mamadu.pl|natemat.pl
```

uBO (z uMatrix pomaga tylko skrypt!):

```
aszdziennik.pl,dadhero.pl,innpoland.pl,mamadu.pl,natemat.pl##+js(abort-current-inline-script, parseInt, adblock)
```

**Comment by hawkeye116477** [comment]
Zamiast `nooptext` teraz powinno być `noop.txt`.

**Comment by krystian3w** [comment]
xmap- chce no-stiff :rofl:

`mamadu.pl##+js(nostif, , 1)`
