### ISSUE TITLE
webkod.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#15239]
### Zrzut ekranu 
![obraz](https://user-images.githubusercontent.com/32641928/70386361-89739c00-1998-11ea-94de-67c263d5972e.png)

### Link bezpośredni 
https://webkod.pl/kurs-css/lekcje/dzial-1/dziedziczenie-wlasciwosci-css

### Co trzeba zrobić, aby pojawił się błąd?
1. Wejść na strone

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock
Nano defender

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Fuck Fuckadblock
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by MajkiIT** [comment]
@Barticf to wina blokowania skryptów przez FF

**Comment by krystian3w** [comment]
Nie?

---

Prędzej Bogachenko generykiem wywiał burzę, bo my mamy fix z pojedynczymi wyjątkami:

```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=dieroten.pl|ps3-hack.pl|dniwolne.eu|webkod.pl|cdahd.ml
```

Na moje dalej wystarcza, pod szarą masę.

---

@Barticf wymuś aktualizacje `Fuck Fuckadblock`.
