### ISSUE TITLE
media.netflix.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15235]
cos blokuje cala strone moze cookies

test link:
https://media.netflix.com/pl/press-releases/netflix-announces-its-first-original-series-in-polish-language-academy-award-nominee-agnieszka-holland-to-direct

**Comment by krystian3w** [comment]
@kiboke

`media.netflix.com#@##cookieAlert`

**Comment by krystian3w** [comment]
@kiboke cookies blink on wolfram alpha:

`###root > div > header + div + section`

footer is loaded dynamically (because blinking).

**Comment by xMaap** [comment]
A tutaj informacja jest o cookies
`https://media.netflix.com/pl/only-on-netflix/81078819`
![Zrzut ekranu z 2019-12-08 10-04-37](https://user-images.githubusercontent.com/36385327/70387187-27b82f80-19a2-11ea-88a8-002a52f1bf3c.png)

**Comment by hawkeye116477** [comment]
@kiboke Broken scroll on `filmboxlive.com`.
```
filmboxlive.com#@#.cookie-policy-popup:not(body):not(html)
filmboxlive.com#@##cookiePolicy
```

**Comment by kiboke** [comment]
> @kiboke
> 
> `media.netflix.com#@##cookieAlert`

Thank you.  I will expand the generic `#cookieAlert` rule into `#cookieAlert:not(body)`
