### ISSUE TITLE
ztm.waw.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#15234]
`https://www.ztm.waw.pl/`
![Zrzut ekranu z 2019-12-05 05-37-39](https://user-images.githubusercontent.com/36385327/70204591-70ad8100-1721-11ea-9b2e-a11822ee774b.png)

`https://www.wtp.waw.pl/
`
![Zrzut ekranu z 2019-12-05 05-38-52](https://user-images.githubusercontent.com/36385327/70204639-976bb780-1721-11ea-8ed9-5c567eab45eb.png)
![Zrzut ekranu z 2019-12-05 05-39-01](https://user-images.githubusercontent.com/36385327/70204641-99357b00-1721-11ea-9012-d9c90063798f.png)

**Comment by krystian3w** [comment]
A ikonę RSS to co wycięło na `wtp.waw.pl`?

**Comment by xMaap** [comment]
Fanboy’s Annoyance

**Comment by krystian3w** [comment]
Aha.
