### ISSUE TITLE
test

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15232]

**Comment by xxcriticxx** [comment]
@hawkeye116477 nie wiem jak to ma dzialac ale jakos blank przechodzi bez problemu

**Comment by hawkeye116477** [comment]
@xxcriticxx Po prostu link „create blank" z dołu znika i tyle.

**Comment by xxcriticxx** [comment]
Btw cookies I off topic nie taguje

**Comment by hawkeye116477** [comment]
@xxcriticxx To kto to niby otagował https://github.com/MajkiIT/polish-ads-filter/issues/15233 :stuck_out_tongue: ?

**Comment by krystian3w** [comment]
Bo nie ma sensu robienia templatki pod etykiętę "off topic".

Potem lista zrówna się długością jak były osobne angielskie wersje.

**Comment by xxcriticxx** [comment]
my kochamy otwierac tematy "off topic"

**Comment by xxcriticxx** [comment]
@hawkeye116477 zmien formularz zeby nie wyznaczalo MajkiIT caly czas do reklam

**Comment by hawkeye116477** [comment]
@xxcriticxx A to coś przeszkadza?

**Comment by xxcriticxx** [comment]
jemu nie ale dla mnie tak

**Comment by krystian3w** [comment]
To może filtr indywidualny do uBo?

Można napisać taki co jak wykryje etykietę reklama to będzie wycinał nick z zgłoszenia i listy zgłoszeń (tu może być odrobinę trudniej ze sprawdzaniem wierszy).

**Comment by xxcriticxx** [comment]
poprawiłem i na razie jest gitara
