### ISSUE TITLE
hdkino.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15230]
please block fake page

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale to nie na te repo raczej, tylko to do KADa.
Ping @krystian3w

**Comment by xxcriticxx** [comment]
@hawkeye116477 ja poważniejsze rzeczy dodaje main listy

**Comment by hawkeye116477** [comment]
@xxcriticxx Główna lista jest raczej od reklam, KAD jest natomiast od przekrętów, oszustw, różnych zagrożeń. Nie wiem co takiego wyjątkowego w tej stronie miałoby być jeśli miałaby trafić do głównej listy. 
Tak czy siak, temat już chyba można zamknąć, skoro dodane :smile:.
