### ISSUE TITLE
facet.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1524]
http://facet.wp.pl/marita-lorenz-kobieta-ktora-na-zlecenie-cia-miala-zabic-fidela-castro-6062686467581057a

film na tej samej stronie wykrywa ad blocka
Zobacz też: Umięśnione kobiety mogą być seksowne. Zobaczcie

reklama

![capture](https://cloud.githubusercontent.com/assets/15007183/20640369/f0562670-b3a9-11e6-9e9f-768558fe7b41.PNG)

**Comment by xxcriticxx** [comment]
jest tez jakis prezentowy hit of foto wp fotokalendarz z twoim zdjeciami

**Comment by F4z** [comment]
Ten "Prezentowy hit od foto wp" się pojawia, bo w regule, która ma blokować reklamy brakuje litery "t" na końcu -  `/:\/\/facet\.wp\.pl\/[a-zA-Z0-9\W_]{200,}\//$script,importan`
Poprawiona reguła:
`/:\/\/facet\.wp\.pl\/[a-zA-Z0-9\W_]{200,}\//$script,important`
Film zaraz zobaczę.

**Comment by F4z** [comment]
To powinno chyba wystarczyć:
`@@||v.wpimg.pl$script,domain=facet.wp.pl`

Jak nie zadziała, to sprawdź jeszcze dodatkowo te dwie reguły:
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=facet.wp.pl`
`@@||googleads.g.doubleclick.net/pagead/ads?sdkv=*&video_product_type=*&url=http%3A%2F%2Ffacet.wp.pl%2F*&description_url=http%3A%2F%2Fwp.tv`

**Comment by xxcriticxx** [comment]
wszystko dziala ale musialem wszystkie reguly dodac

` /:\/\/facet\.wp\.pl\/[a-zA-Z0-9\W_]{200,}\//$script,important`
`@@||v.wpimg.pl$script,domain=facet.wp.pl`
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=facet.wp.pl`
`@@||googleads.g.doubleclick.net/pagead/ads?sdkv=*&video_product_type=*&url=http%3A%2F%2Ffacet.wp.pl%2F*&description_url=http%3A%2F%2Fwp.tv`

**Comment by MajkiIT** [comment]
@xxcriticxx u mnie same polskie filtry dały radę. Oczywiście poprawiłem to co @F4z wskazał.

**Comment by xxcriticxx** [comment]
@MajkiIT skasowalem wszystko z my filters update filtrow zrobilem wszystko jest ok tylko film na dole sie pokazuje i sam znika i go znalesc nie moge

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z 

A teraz jest ok?

**Comment by xxcriticxx** [comment]
@MajkiIT nic nie dziala dalej mam boxy po reklamach i zadna obrazki sie nie laduja

**Comment by F4z** [comment]
Też to widzę.
Nie ładują się obrazki, i w ogóle strona nie wyświetla się prawidłowo przez tę regułę - `/:\/\/facet\.wp\.pl\/[a-zA-Z0-9\W_]{200,}\//$important,script`

W zasadzie teraz jak wyszła nowa wersja uBlocka Origin 1.10.0 (na razie dostępna tylko na Mozille Firefox, ale za dzień/kilka powinno być też dostępna na inne przeglądarki*), to można spróbować z taką regułą:
`facet.wp.pl##script:inject(abort-on-property-write.js, gafBodies)`
To powinno zablokować reklamy.
Jeśli chodzi o te miejsca z napisem "Reklama", to ta reguła powinna je ukryć (nie działa w Adblocku):
`facet.wp.pl##div[class^="_"]:matches-css(background-image:url("data:image/png;base64*"))`
Ale nie wiem jak długo będzie działać.

*Na inne przeglądarki też jest dostępna i można ręcznie zainstalować, na przykład stąd - https://github.com/gorhill/uBlock/releases/tag/1.10.0
ale ten dzień/kilka trzeba poczekać na aktualizację z Chrome Web Store czy z oficjalnej strony z rozszerzeniami dla Opery.

**Comment by xxcriticxx** [comment]
@F4z to `facet.wp.pl##script:inject(abort-on-property-write.js, gafBodies)` nie dziala z 1.10.0

zaczelo dopiero dzialac jak wylonczylem polskie filtry

**Comment by F4z** [comment]
@xxcriticxx w jakim sensie nie działa?
Nie działa, bo dalej strona nie wyświetla się poprawnie, czy nie działa, bo widzisz reklamy?
Jeśli nie działa, bo strona nie wyświetla się poprawnie, to jest to wina tej reguły - /`:\/\/facet\.wp\.pl\/[a-zA-Z0-9\W_]{200,}\//$important,script` i jak ona zostanie usunięta, to ta reguła - `facet.wp.pl##script:inject(abort-on-property-write.js, gafBodies)` będzie prawidłowo działać

**Comment by xxcriticxx** [comment]
paging @MajkiIT poprawka potrzebna

**Comment by xxcriticxx** [comment]
@F4z pull request mozesz zrobic do listy @MajkiIT potem merge with master

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z gotowe

**Comment by xxcriticxx** [comment]
ok update i testujemy

**Comment by xxcriticxx** [comment]
film pokazuje sie i znika automatycznie ale wszystkie obrazki sie pokazaly

**Comment by F4z** [comment]
Ten film już wcześniej znikał, więc to **najprawdopodobniej** wina jakiejś innej reguły.
Potem postaram się sprawdzić czemu tak się dzieje.
Nie wiem jak u Was, ale ja znowu mam komunikat o adblocku przy filmach, na przykład tutaj - `http://sportowefakty.wp.pl/sportowybar/649216/spiewa-disco-polo-i-walczy-na-macie-marcin-siegienczuk-z-brazowym-medalem`
Jak widać, oni tam ciągle coś zmieniają.

**Comment by xxcriticxx** [comment]
ja mam roznie albo kreci albo znika albo adblock alco czarno

**Comment by xxcriticxx** [comment]
umnie film gra bez problemu. moze skasujmy wszystkie reguly z wp.pl i zaczniemy od nowa?

**Comment by F4z** [comment]
U mnie po wyczyszczeniu ciasteczek i pamięci cache pojawił się ten komunikat.
Nie chce mi się od nowa zaczynać, jak będę miał trochę więcej czasu, to postaram się poprawić te reguły.

**Comment by F4z** [comment]
Tutaj się pomyliłem - https://github.com/MajkiIT/polish-ads-filter/issues/1524#issuecomment-263693300
Ta reguła nie ukrywa tych elementów - `facet.wp.pl##div[class^="_"]:matches-css(background-image:url("data:image/png;base64*"))`

Ta działa:
`facet.wp.pl##div[class^="_"]:matches-css(background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADgAAAAtCAMAAADMQ1gEAAACiFBMVEUAAAD///////+qqqq/v7/MzMzV1dXb29u/v7/GxsbMzMzR0dHV1dXExMTIyMjMzMzPz8/S0tLGxsbMzMzR0dHIyMjKysrMzMzOzs7IyMjKysrMzMzOzs7Pz8/Ly8vMzMzPz8/JycnLy8vMzMzNzc3Ozs7KysrLy8vNzc3Ozs7KysrLy8vMzMzNzc3Ozs7KysrLy8vMzMzNzc3Ozs7KysrLy8vMzMzNzc3KysrLy8vMzMzNzc3Ozs7Ly8vLy8vMzMzNzc3Ly8vNzc3Nzc3Ly8vLy8vNzc3Nzc3Ly8vLy8vMzMzNzc3Nzc3Ly8vLy8vMzMzNzc3Nzc3Ly8vLy8vNzc3Nzc3Ly8vLy8vNzc3Nzc3Ly8vMzMzMzMzMzMzNzc3MzMzMzMzNzc3Ly8vMzMzMzMzMzMzMzMzMzMzNzc3Ly8vMzMzNzc3Ly8vMzMzMzMzMzMzMzMzMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzLy8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzNzc3MzMzMzMzMzMzNzc3Ly8vMzMzMzMzNzc3MzMzMzMzMzMzNzc3Ly8vMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMx9Jm/RAAAA13RSTlMAAQIDBAUGBwgJCgsMDQ4PEBESFBYXGBkaHB0eHyAiIyUmJygpKissLi8wMTIzNDU2Nzg5Ojs8PT9AQUJDREVGR0lMTU5PUVJTVFVWV1hZWltcXV5gYWJjZWZnaGlqa21ucHFydHd4eXp7fH+AgYKDhoeIiYqLjI2Oj5GSk5SVlpeYmZqbnJ2eoKGjpKWmp6ipqqusra6vsbO0tba3uLm7vb6/wMHCw8XGx8jJysvMzc7P0NLT1NXX2Nna29zd3uDh4uPk5ebn6Ozt7vHy8/T19vf5+vv8/oGvxekAAANiSURBVHgB7dLrW1RVFIDxdxiERCkSSIlLUmRlTolFRCZUaiVmSpJFCVoEWWbaGFLRxSYpLVOIzC5aUJZxCQuwEhutwAgxsUTWv9Pae87AYR7Fh+/+PriW8+x34OwD1sxDInK8iInytIm1mbDohS/412RxMbeII4eQub+LsS8NK7P6tedXP7QgcwoRssXxLlb6KQnpSUIl/i2OjlUe3GIHJeQ41jsStge1VEbtGlvuF0c6xh8SNnw18Jy4lOG2RhwrUQkR594Wl9+icEkTx7bRR+6z5xuAz3UO+P01gZ2ndcvDrdMJj6Dut+uBe0UdBTp0dmEs160St03hZ7oKKLNr3bRh80E8mEttwojT7WXccsSxBNhotxp+Db3aWPMFOzFidH0TN2/4Vb0ObLXbOnaYUUqKGdUj3+9njA+csBP4yG7FrDYjwGwznoGYZF+rbo8xxsPhh0yEJrvlc7MZrdxtRlHUF2KdS2WMhLNO+QActsv1RA/qGPQuETU/V0K2E6FRQl61t6guh2/NzCoRlblcrO+nEuEpJ2wzt6gGgCpRyypFxWWc039/KZ9EpAwnPDsl1c6fgQdF+U1+Eu5c7EvifNqdcsEcO/ZD6EU01tk/oAurcMIN99hRi+oRRwsXFv5dm5+0Yz2qThwbGUeHuBWjFklIfwrj2CAuQ9NRnvpQl894Us64wios79qWYPumZMZXISO+jmUCPFuGxfrvlUlMTPYbbf3HPqtM4WIuuSQQCFQXRumsVyVsvhFiqm6lPgNr8q7bgNyA/e/iQAJw+3selFQUrjhUA71FPp8vjd6FENjtQXxYjwx9CJTIFlSXzADqh/IAe+Kufg11gglLmyczEn6z/kyChp19l8G8DhMmnqjZHg5X/egK87qTGQlnDsS1PqFh054VUFtuwqffmn06HpCv6lv6rtWiJxgMJtF7dKCU0fClHaxt1vBg/nfE/5Vuwq4cDj8KSJHvjsatrp9438mskTD6RHVhmVxHyQ+e7lmP107XcN4/Sws/OeCcyD3mCll35MpwuOhPvfSf/JS0U17Tmj1Dw20H9aN/rwmduGnM5Xh2f+l1wr3PAgW9Xg2n9Xeg4dRTNwANL0JQlyu6Z7GvXb1P83yI+7SYdmNuSyrgbZqzbC/4V5IUTCpoQBV8zP9FOJzfMoGB/QAAAABJRU5ErkJggg=="))`

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z 

Co powiecie na coś takiego
`facet.wp.pl##a[href^="https://v.wpimg.pl/"]`
`facet.wp.pl##._3vbc33`

ewentualnie jeszcze to
`facet.wp.pl##._10airj`

**Comment by xxcriticxx** [comment]
te obrazki sa hyba z fb i mamy cos co blokuje fb

**Comment by F4z** [comment]
@MajkiIT ta reguła - `facet.wp.pl##a[href^="https://v.wpimg.pl/"]` działa i ukrywa samą reklamę/reklamy, która się pojawia jak skrypt od reklam nie jest zablokowany, ale te puste miejsca nadal zostają.
Te dwie reguły u mnie nie działają:
`facet.wp.pl##._3vbc33`
`facet.wp.pl##._10airj`
zakładam, że pewnie znowu coś zmienili.

**Comment by xxcriticxx** [comment]
@F4z tutaj mam ad block na filmiku 

`http://facet.wp.pl/joanna-krupa-w-skapym-bikini-6062076757800065g`

**Comment by F4z** [comment]
@xxcriticxx wydaje mi się, że jak w tej regule - `/:\/\/(?!biuropodrozy)(?!websocket)(?!liveblog)(?!relacje)(?!opinie)(?!zalacznik)(?!magazyn)(?!newsletter)(?!facet)(?!wyleczto)(?!kuchnia)(?!film)(?!moto)(?!gwiazdy)(?!teleshow)(?!finanse)(?!kobieta)(?!dom)(?!pogoda)(?!tech)(?!historia)(?!czat)(?!ksiazki)(?!gryonline)(?!hotele)(?!narty)(?!samoloty)(?!wycieczki)(?!hosting)(?!irlandia)(?!multikurs)(?!casino)(?!foto)(?!tech)(?!www)(?!stg)(?!doladowania)(?!fantasyliga)(?!funduszeue)(?!imperiumstylu)(?!kodyrabatowe)(?!alefolwark)(?!angielski)(?!arenamody)(?!beniamin)(?!bon)(?!bsg)(?!casino)(?!diety)(?!dlaprasy)(?!dlugi)(?!doladowania)(?!dom)(?!dysk)(?!ebiznes)(?!ebooki)(?!empire)(?!fantasyliga)(?!film)(?!fundusze)(?!ogloszenia)(?!orangekinoletnie)(?!rekrutacja)(?!rycerzeiksiezniczki)(?!speedwaymanager)(?!sportowefakty)(?!sportowybar)(?!talesofmagic)(?!ubezpieczenia)(?!warofdragons)(?!wiadomosci)(?!gazetki)(?!gry)(?!horoskop)(?!kalendarz)(?!katalog)(?!khanwars)(?!komiks)(?!konflikty)(?!kontakty)(?!korsarze)(?!kultura)(?!mini)(?!mmho)(?!mobilna)(?!morizon)(?!moto)(?!muzyka)(?!narty)(?!naryby)(?!onas)(?!orangekinoletnie)(?!piraci)(?!poczta)(?!pomoc)(?!praca)(?!profil)(?!programtv)(?!pytamy)(?!rekrutacja)(?!rss)(?!rtvagd)(?!rycerzeiksiezniczki)(?!smeet)(?!speedwaymanager)(?!szkola)(?!szukaj)(?!tech)(?!teleshow)(?!triviador)(?!turystyka)(?!twojeip)(?!ulubiency)(?!warodfragons)(?!wycieczki)(?!zdrowie)(?!zoomumba)(?!topnews)(?!erotyka)(?!dzieci)(?!fitness)(?!gielda)(?!finansomat)(?!biznes)(?!sport)[a-zA-Z0-9]{4,9}\.wp\.pl\/.{150,}/$important`

zmieni się `150` na `180`, ewentualnie na `200`, to powinno działać.

Jeśli nadal nie będzie działać, to z tej reguły - `@@/:\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(.{0,15}[&!*;@\$)[\]:%].*|(?!gaf|cap|vad|display)[a-zA-Z0-9\W_]{1,10})\.(js|html|xml|jpg|gif|png)/` trzeba będzie usunąć `gaf`.

Tylko żeby zaczęło działać konieczna jest zmiana w polskich filtrach, bo dodanie tego w zakładce "Moje filtry" nic nie da.

Poprawione reguły:
`/:\/\/(?!biuropodrozy)(?!websocket)(?!liveblog)(?!relacje)(?!opinie)(?!zalacznik)(?!magazyn)(?!newsletter)(?!facet)(?!wyleczto)(?!kuchnia)(?!film)(?!moto)(?!gwiazdy)(?!teleshow)(?!finanse)(?!kobieta)(?!dom)(?!pogoda)(?!tech)(?!historia)(?!czat)(?!ksiazki)(?!gryonline)(?!hotele)(?!narty)(?!samoloty)(?!wycieczki)(?!hosting)(?!irlandia)(?!multikurs)(?!casino)(?!foto)(?!tech)(?!www)(?!stg)(?!doladowania)(?!fantasyliga)(?!funduszeue)(?!imperiumstylu)(?!kodyrabatowe)(?!alefolwark)(?!angielski)(?!arenamody)(?!beniamin)(?!bon)(?!bsg)(?!casino)(?!diety)(?!dlaprasy)(?!dlugi)(?!doladowania)(?!dom)(?!dysk)(?!ebiznes)(?!ebooki)(?!empire)(?!fantasyliga)(?!film)(?!fundusze)(?!ogloszenia)(?!orangekinoletnie)(?!rekrutacja)(?!rycerzeiksiezniczki)(?!speedwaymanager)(?!sportowefakty)(?!sportowybar)(?!talesofmagic)(?!ubezpieczenia)(?!warofdragons)(?!wiadomosci)(?!gazetki)(?!gry)(?!horoskop)(?!kalendarz)(?!katalog)(?!khanwars)(?!komiks)(?!konflikty)(?!kontakty)(?!korsarze)(?!kultura)(?!mini)(?!mmho)(?!mobilna)(?!morizon)(?!moto)(?!muzyka)(?!narty)(?!naryby)(?!onas)(?!orangekinoletnie)(?!piraci)(?!poczta)(?!pomoc)(?!praca)(?!profil)(?!programtv)(?!pytamy)(?!rekrutacja)(?!rss)(?!rtvagd)(?!rycerzeiksiezniczki)(?!smeet)(?!speedwaymanager)(?!szkola)(?!szukaj)(?!tech)(?!teleshow)(?!triviador)(?!turystyka)(?!twojeip)(?!ulubiency)(?!warodfragons)(?!wycieczki)(?!zdrowie)(?!zoomumba)(?!topnews)(?!erotyka)(?!dzieci)(?!fitness)(?!gielda)(?!finansomat)(?!biznes)(?!sport)[a-zA-Z0-9]{4,9}\.wp\.pl\/.{200,}/$important`

`@@/:\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(.{0,15}[&!*;@\$)[\]:%].*|(?!cap|vad|display)[a-zA-Z0-9\W_]{1,10})\.(js|html|xml|jpg|gif|png)/`

**Comment by xxcriticxx** [comment]
czyli @MajkiIT potrzebny albo zrobic pull request

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z 
1 zmiana poszła.

**Comment by MajkiIT** [comment]
u mnie bez zmian

**Comment by F4z** [comment]
U mnie też.
Dodaj proszę tę drugą regułę i sprawdźmy :)

**Comment by MajkiIT** [comment]
@F4z gotowe

**Comment by xxcriticxx** [comment]
same here bez zmian dalej ad block

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z z 2 regułą tez nic

**Comment by xxcriticxx** [comment]
z druga zaczol dzialac mi ten film `http://facet.wp.pl/joanna-krupa-w-skapym-bikini-6062076757800065g`

film na fidelu dalej ad blcok

**Comment by F4z** [comment]
@MajkiIT bo jeszcze jest ta reguła - `||rek.www.wp.pl/gaf.js$important`
Ją też trzeba usunąć.

**Comment by MajkiIT** [comment]
@F4z Gotowe

**Comment by MajkiIT** [comment]
u mnie to samo

**Comment by xxcriticxx** [comment]
umnie na krupie film dziala na fidelu film auto znika

**Comment by F4z** [comment]
@MajkiIT dzięki. U mnie teraz działa, odśwież może kilka razy stronę?
@xxcriticxx `na fidelu` to znaczy?

**Comment by xxcriticxx** [comment]
pierwszy link wtym poscie

**Comment by xxcriticxx** [comment]
w incognito mode mam na fidelu ad block nad krupie ad block 

lece przeglondarke historie wykasuje i dns flushne

**Comment by xxcriticxx** [comment]
ok po kasacji histori i dns flush na fidelu film znika na krupie dziala jak nalezy

**Comment by F4z** [comment]
Ten znikający film to raczej wina innych reguł, jeszcze dokładnie na to nie patrzyłem.

**Comment by xxcriticxx** [comment]
lece w korki nowo jorske sie widzimy jutro panowie 

@MajkiIT poczytaj co napisalem w nowym poscie

**Comment by MajkiIT** [comment]
@xxcriticxx a to nie wina AAK scripts?

**Comment by xxcriticxx** [comment]
Potestuje w domu I odpisze

**Comment by F4z** [comment]
Zauważyłem, że jak nie ładuje się plik z reklamą, to nie mam komunikatu o adblocku, a jak się ładuje to jest.
Obrazek z dziennika żądań uBlocka, kiedy zablokowane jest wideo z reklamą.
![image](https://cloud.githubusercontent.com/assets/11742596/20776391/81ab754e-b760-11e6-90c2-e0f541bd4610.png)
Po kilku odświeżeniach nie widzę tego i wtedy nie mam komunikatu o adblocku.
Jeśli jest tak jak opisałem, to może być problem z ominięciem tego przy użyciu reguł.

O ile dobrze pamiętam, to kiedyś już tak było i wtedy w Google Chrome ta reguła działała - `||rek.www.wp.pl/vad.xml$xmlhttprequest,redirect=noopframe,important`
ale w Mozilli Firefox nie.

**Comment by xxcriticxx** [comment]
Albo script time
