### ISSUE TITLE
yelp.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#15241]
Ukrywa formularz logowania/rejestracji
```
https://www.yelp.pl/login
https://www.yelp.pl/signup
```
![Zrzut ekranu z 2019-12-08 10-00-45](https://user-images.githubusercontent.com/36385327/70387149-b24c5f00-19a1-11ea-964d-581636445eb3.png)

Ukrywa treść
`https://www.yelp.pl/static?p=privacy`
![Zrzut ekranu z 2019-12-08 10-01-42](https://user-images.githubusercontent.com/36385327/70387157-cb551000-19a1-11ea-92b4-904c19ff60e4.png)

**Comment by hawkeye116477** [comment]
U mnie formularz logowania/rejestracji normalnie się wyświetla.

**Comment by krystian3w** [comment]
Może znowu jakiś hosts psuje np. `Dan Pollock’s hosts file` (kiedyś miałeś aktywnego).

Albo `fanboy annoyance` - znowu włączyłeś i pewnie rapotrujesz byle gdzie. 2/3 składowych listy nie są w naszym kręgu zainteresowań by ulepszać projekt EasyList / Rayanna z Nowej Zelandii 🇳🇿.
