### ISSUE TITLE
Nieaktywna domena

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#15242]
### Link bezpośredni 
`vodgo.pl`

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
:oncoming_police_car: 
`https://www.instalki.pl/aktualnosci/internet/38984-vodgo-pl-zamkniete-nastepca-i-alternatywa-dla-fili-cc-nie-dziala.html`

Polecane alternatywy:
* [Netflix](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.netflix.com/signup/planform)
* [Platforma Canal+ z Netflixem](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://pl.canalplus.com/netflix?pm_source=pl_canalplus&pm_medium=homepage-nc00&pm_campaign=Platforma-CPlus-X-mas-2019-Cplus-with-Netflix-MKT-SAL-PRO&pm_content=karuzela-v1-main-kv)
* [HBO Go](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://hbogo.pl/)
* [Amazon Prime Video](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.primevideo.com/)
* [Chilli TV](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://pl.chili.com/filmy)
* [Kupno Płyty Bluray w Empiku](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.empik.com/filmy/blu-ray)
* [Kupno Płyty Bluray u Merlina](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://merlin.pl/catalog/filmy-m10404223/)
* [Zakup biletu do kina IMAX](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.cinema-city.pl/imax#/)

**Comment by MajkiIT** [comment]
@hawkeye116477 Dziękuję
