### ISSUE TITLE
player.radiozet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15244]
mozliwe ze tylko u mnie za duzo pihole blokuje.czy moze ktos potwierdzic. 

![Capture](https://user-images.githubusercontent.com/15007183/70390260-73191080-1997-11ea-9378-4fcf3767b529.PNG)

**Comment by krystian3w** [comment]
Nie, to wykrywają EasyList:

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=player.radiozet.pl`
`player.radiozet.pl##.preloader__message__addblock`

Myślę, że to lepsze rozwiązanie od generichide by nim ukryć tekst "Proszę wyłączyć blokowanie reklam".

A jak jakieś reklamy będą wciskać to trzeba pewnie sięgnąć po najpewniej `json-prune`.

**Comment by hawkeye116477** [comment]
A ja nie mam tej wiadomości antyadblockowej, odblokowanie ima wystarczy.

**Comment by xxcriticxx** [comment]
same shit na `player.antyradio.pl`

**Comment by hawkeye116477** [comment]
Może lepiej od razu całą grupę sprawdzić.
`https://www.eurozet.pl/Nasze-marki`

**Comment by xxcriticxx** [comment]
`player.meloradio.pl` ma to samo 

http://www.radiostacja.pl/ wam sie laduje?

**Comment by hawkeye116477** [comment]
@xxcriticxx Tak, na radiostacji wszystko gra i buczy.

**Comment by krystian3w** [comment]
Może czas na fejk konta w repozytorium Olega.

**Comment by xxcriticxx** [comment]
po co te fejk konto?

**Comment by krystian3w** [comment]
By trolle prawnicze miały trudniej składać pozew sądowy i aktualizacje były szybsze.

Z tego co rozumiem to googlowskie ima trzeba dodać do listy reklamowej.

**Comment by xxcriticxx** [comment]
sorry @krystian3w dalej nie kumam o co tobie biega
