### ISSUE TITLE
regionalnyportal.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15258]
a może do KAD : https://niebezpiecznik.pl/post/uwazaj-na-kursy-jezykowe-z-dotacjami-nie-wiadomo-kto-przetwarza-dane-osobowe-ale-mozna-sie-tego-domyslic/

**Comment by krystian3w** [comment]
Że niby niebezpiecznik go wytypował?

Te z niebezpiecznika też mogą być nie po polsku i dwa że padły (ban lub kwarantanna).
