### ISSUE TITLE
glosrzeszowa.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15259]
" c brand i kravet "
Proponuje dać ogólną bo kolejna strona to ma tym razem : http://www.glosrzeszowa.pl/
a wcześniej #15254

**Comment by xxcriticxx** [comment]
![Capture](https://user-images.githubusercontent.com/15007183/70462535-1bf36880-1a89-11ea-9a47-b3f44240e27a.PNG)

**Comment by krystian3w** [comment]
Webrootwi niby lepiej nie ufać, niby antywirus to kilkaset KiB (a teraz w "modzie" kobyły rozmiaru 1 GiB).
