### ISSUE TITLE
cookies maybe today?

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1526]
@MajkiIT make new cookies filters please

**Comment by MajkiIT** [comment]
@xxcriticxx kończę projekt dla klienta. Postaram się ogarnąć to wieczorem lub w nocy.

**Comment by xxcriticxx** [comment]
@MajkiIT w jaki ty biznes teraz prowadzisz?

**Comment by MajkiIT** [comment]
Mam firmę i zajmuję się administracją systemami, siecią, budową systemów, zabezpieczaniem tego itp.

**Comment by xxcriticxx** [comment]
wow ok mr robot

**Comment by MajkiIT** [comment]
Gotowe
