### ISSUE TITLE
ddwloclawek.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15268]
Resztka ( krzyżyk ) - niewiem poczym

![DDW](https://user-images.githubusercontent.com/23176832/70536365-d43f1080-1b5e-11ea-9da3-ce239f3f8207.png)

**Comment by xxcriticxx** [comment]
po RODO

**Comment by xxcriticxx** [comment]
jaki browser? na chromie czysto

**Comment by krystian3w** [comment]
Vivaldi lub Waterfox "56".

**Comment by krystian3w** [comment]
Prawdopodobnie race-condition z słabym PC / procesorem:

https://github.com/MajkiIT/polish-ads-filter/blob/fb353d529098bdc5fc6902620549530455005fd0/cookies_filters/cookies_uB_AG.txt#L311

Vivalidi nie ma html-filteringu to "RODO" tam będzie migać lub zostawać w części.
