### ISSUE TITLE
biznesforum.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1528]
ad block

http://www.biznesforum.pl/chcialbym-zainwestowac-300-tys-zlotych-i-tutaj-mam-do-was-vt847.html

Zauważyliśmy, że używasz programu blokującego reklamy. Na naszym forum stosujemy lekkie i mało obciążające komputer reklamy Google AdSense. Wpływy z reklam to jedyny dochód forum, który pozwala na jego utrzymanie. Jeśli możesz, to zezwól na wyświetlanie reklam na forum.
Dziękujemy.

**Comment by F4z** [comment]
Powinno działać:
`@@||biznesforum.pl/adsense.js$script,domain=biznesforum.pl`

Można też usunąć te "linki reklamowe".
![image](https://cloud.githubusercontent.com/assets/11742596/20648863/780d71a0-b4b2-11e6-86da-17a51e3286bd.png)

Na przykład:
`biznesforum.pl##div[style="border-left:1px solid #cccccc;border-right:1px solid #cccccc;padding:0px;"]:not([id])`
