### ISSUE TITLE
lubliniec.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15294]
dziwne cookie bo na stronie głównej ale już w zakładkach jest, np : https://lubliniec.eu/index.php/o-miescie-lubliniec.html

**Comment by krystian3w** [comment]
Czasem robią tak, że tylko w artykułach aktywują, nic nie poradzisz na pokręconą logikę.

A 2-3 paski cookies to już chyba efekt jak jest kilku webmasterów lub robi "blog" ktoś nieogarniający CMS-a.

**Comment by krystian3w** [comment]
@kiboke you add generic "`###cadre_alert_cookies`" for this or this break Internet:

```
fabryka-kuchni.eu,mebledom.eu,owczarska.eu###cadre_alert_cookies
lubliniec.eu###cadre_alert_cookies
```

**Comment by kiboke** [comment]
That used to be a generic rule but it breaks some websites. I'll add a domain base rule, thanks and sorry for the delay!
