### ISSUE TITLE
limanowianin.in

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15316]
Ciekawa strona, reklamy u góry i na dole a pomiędzy białe tło ( błąd )

**Comment by krystian3w** [comment]
`@@||limanowianin.in/wp-content/plugins/soslider-social-slider/js/jquery.soslider.min.js$script`

**Comment by krystian3w** [comment]
Po akceptacji PR usuwamy tag "błąd": https://github.com/MajkiIT/polish-ads-filter/pull/15319
