### ISSUE TITLE
geekweek.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15330]
mozliwe ze to tylko u mnie

test link:
https://www.geekweek.pl/vod/poszukiwacze-historii-tajna-kwatera-luftwaffe_6894902/poszukiwacze-historii_1055517/

![Capture](https://user-images.githubusercontent.com/15007183/70862558-e4af0c80-1f0b-11ea-9313-e37f61bb32cd.PNG)

**Comment by krystian3w** [comment]
Nie, każdy powinien mieć.

![obraz](https://user-images.githubusercontent.com/35370833/70863574-d54eb400-1f49-11ea-87a4-013202637515.png) |
--- |

**Comment by krystian3w** [comment]
Fix:

```
www.geekweek.pl#@#[class$="-ads"]
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=www.geekweek.pl
@@||www.google-analytics.com/analytics.js$script,domain=www.geekweek.pl
@@||hit.stat24.com^$script,xmlhttprequest,domain=www.geekweek.pl
```

**Comment by krystian3w** [comment]
Nie mam głowy by zrobić filtr skryptowy oszukujący, że się załadowały aż 3 skrypty, a `pl##[class$="-ads"]` jest w tym wypadku za generyczne.

**Comment by krystian3w** [comment]
### Częściowa poprawka:

```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=www.geekweek.pl
@@||hit.stat24.com^$script,xmlhttprequest,domain=www.geekweek.pl
```

nie kopiować z powiadomień e-mail!

---

Nie mam głowy by zrobić filtr skryptowy oszukujący, że się załadowały aż 2 skrypty.

Pod `sdkloader/ima3.js` wymiękł sam JsPenguin i porzucił plany zneutralizowanego skryptu do przekierowań.

---

### Coś dalej blokuje ścieżkę🔉  **AUDIO** 🔉 ❗️❗️❗️

**Comment by krystian3w** [comment]
### Częściowa poprawka:

```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=www.geekweek.pl
@@||hit.stat24.com^$script,xmlhttprequest,domain=www.geekweek.pl
geekweek.pl##.adocean-billboard
```

nie kopiować z powiadomień e-mail!

---

Nie mam głowy by zrobić filtr skryptowy oszukujący, że się załadowały aż 2 skrypty.

Pod `sdkloader/ima3.js` wymiękł sam JsPenguin i porzucił plany zneutralizowanego skryptu do przekierowań.

---

### Coś dalej blokuje ścieżkę🔉  **AUDIO** 🔉 ❗️❗️❗️ 

albo Firefox nie ogarnia znowu kodowania jak  `iPla.tv` nie robi konwersji staroci:

`https://www.ipla.tv/wideo/serial/S-w-K/759/S-1/760/O-1/4208`

Nie będę instalować Waterfox "56" by mieć ścieżkę audio.

**Comment by hawkeye116477** [comment]
`Nie będę instalować Waterfox "56" by mieć ścieżkę audio.`
@krystian3w 56 to dawno temu była, teraz jest Classic 2019.12 albo Current 2019.10...

**Comment by krystian3w** [comment]
Ja tam nie widzę potrzeby dodawania `@@/redataredir$xmlhttprequest,domain=www.geekweek.pl` robiąc zwykłe odświeżnie nie wskakuje.

**Comment by hawkeye116477** [comment]
@krystian3w Jak masz EasyPrivacy. to wskakuje.

**Comment by krystian3w** [comment]
Ja mam chyba zbyt zaktualizowane EasyPrivacy lub zrobiłeś bardziej specyficzne dopuszczenia pod "`stat24`".

Szary to jest ich CSS:

> ![obraz](https://user-images.githubusercontent.com/35370833/70864780-c79f2b80-1f55-11ea-9ced-8412394205cf.png)

**Comment by hawkeye116477** [comment]
@krystian3w Mam niby wersję z dzisiaj 13:42, co najdziwniejsze w Vivaldim jest Nano i wersja z dzisiaj z 14:51, a w FF nie chce iść aktualizacja, pewnie jest rozbieżność, bo jak zwykle są mirrory i w którymś jest nie halo, standard u Fanboya i spółki...

**Comment by xxcriticxx** [comment]
Co mam dodać do chroma?

**Comment by hawkeye116477** [comment]
@xxcriticxx 
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=www.geekweek.pl
@@||hit.stat24.com^$script,xmlhttprequest,domain=www.geekweek.pl
@@/redataredir$xmlhttprequest,domain=www.geekweek.pl
```

**Comment by krystian3w** [comment]
to też warto gdzieś dodać:

`geekweek.pl##.adocean-billboard`

pusty boks między headerem a artykułem.

**Comment by xxcriticxx** [comment]
na chromie mam ten szary ekran ale potem film sie odpala 

w domu za mozna pihole trzyma

**Comment by krystian3w** [comment]
Jak uwalasz nim `stat24.com` to może się okazać wymagane dodanie wyjątku, by przeglądarka widziała domenę.
