### ISSUE TITLE
kresy.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15347]
resztka po reklamie ( u góry ) i błąd blokuje tekst pod zdjęciami ( szary prostokąt )

**Comment by MajkiIT** [comment]
@blocker999 Jakiś przykład ?

**Comment by xxcriticxx** [comment]
@MajkiIT 

test link:
https://kresy.pl/wydarzenia/polska/jelenia-gora-szykuje-umowe-o-partnerstwie-z-neobanderowcami/

brakuje textu:
Jelenia Góra szykuje umowę o partnerstwie z neobanderowcami

**Comment by krystian3w** [comment]
Za dużo do debugowania 60 filtrów i jakby na pół podzielone (z 30 sieciowych blokad, z 30 ukryć elementów kosmetycznie).

**Comment by krystian3w** [comment]
Na szybko to coś z ich własnych skryptów:

`@@||kresy.pl^$script,~third-party`

iOS:
`@@||kresy.pl^$script,domain=kresy.pl`
