### ISSUE TITLE
lech.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1534]
ad block

http://lech.tv/video-id-23636-lech_ii_poznan_vineta_wolin_40_skrot

![capture](https://cloud.githubusercontent.com/assets/15007183/20649010/5d5e36e8-b483-11e6-9207-15b31f33cb5d.PNG)

**Comment by F4z** [comment]
Powinno zadziałać:
`lech.tv#@#.advertising_banner`
`lech.tv#@#.advertising_block`
`lech.tv#@#.reklama`
`lech.tv#@#[class*="reklama"]`
ale jakbyś mógł, to sprawdź czy u Ciebie działa.

Ewentualnie można dodać to:
`@@||lech.tv^$generichide`
tylko wtedy trzeba sprawdzić, czy gdzieś nie ma reklamy albo pustego miejsca po reklamie.

**Comment by xxcriticxx** [comment]
> Powinno zadziałać:
lech.tv#@#.advertising_banner
lech.tv#@#.advertising_block
lech.tv#@#.reklama
lech.tv#@#[class*="reklama"]
ale jakbyś mógł, to sprawdź czy u Ciebie działa.

dziala thank you
