### ISSUE TITLE
joemonster.org

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1537]
reklamy vivus.pl tylko umnie???

http://joemonster.org/art/38023/Demotywatory_CCV_jak_w_prosty_sposob_zostac_oligarcha

**Comment by F4z** [comment]
Ja też widzę czasami reklamy.
Te dwie reguły powinny chyba to ukryć:
`joemonster.org##iframe[mysrc]`
`joemonster.org##a[style="cursor: pointer"][onclick^="window.location.href="][target="_blank"]`

**Comment by xxcriticxx** [comment]
no hyba dziala testowalem pare stron i jest ok

**Comment by F4z** [comment]
Swoją drogą, dodanie do pliku hosts tego - `unblock.onaudience.com` też powinno zablokować te reklamy.

**Comment by xxcriticxx** [comment]
@F4z computer z plikem hostu ma dead hard drive :(

**Comment by F4z** [comment]
Nadal raz na jakiś czas pojawia się reklama.
