### ISSUE TITLE
zyczenia noworoczne 2020

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15456]
tutaj prosze napisac zyczenia noworoczne
======================================
write New Year's wishes here
======================================

**Comment by xxcriticxx** [comment]
Szampana w bród, wódeczki ciut, kaca małego i brzuszka pełnego, zdartych zelówek, wielu śpiewanych solówek, porannej kawy i wspaniałej Sylwestrowej zabawy !!!

Zyczy Ekipa polish-ads-filter

**Comment by hawkeye116477** [comment]
Niechaj w Nowym Roku ceny paliw będą niskie,
niech Reprezentacja Polski w nogę dobrze ciśnie,
niechaj wiek emerytalny pójdzie w dół, a płace w górę,
i żeby nowe Gwiezdne Wojny były jak „Imperium Kontratakuje"
Tego wam życzę w Nowym Roku 2020.

**Comment by hawkeye116477** [comment]
@xxcriticxx Skoro lubisz sąsiadów, to znalazłem coś dla ciebie => https://www.epicgames.com/store/pl/product/hello-neighbor/home :smile:

**Comment by xxcriticxx** [comment]
@hawkeye116477 moj avatar przypomina mi ciebie i @krystian3w

**Comment by xxcriticxx** [comment]
![image](https://user-images.githubusercontent.com/15007183/71638359-da8b4e80-2c2b-11ea-8842-311a90059f29.gif)
