### ISSUE TITLE
lazienkaplus.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#15452]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/71492281-302fb780-2836-11ea-96e5-ec59b70b8741.png)

### Link bezpośredni 
https://www.lazienkaplus.pl/

### Co trzeba zrobić, aby pojawił się błąd?
1. Wejść na stronę
2. Na chwilę pojawia się strona i znika (biała strona)

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox

**Rozszerzenia i skrypty:** 

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Nano defender
4. Fuck Fuckadblock​
5. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
U mnie znowu OK, nie ma efektu białej strony...

**Comment by krystian3w** [comment]
@gwarser - zrób test czy jakiś generyk cookies od `Kiboke` / `EasyList Cookies` nie robi psikusa?

**Comment by gwarser** [comment]
U mnie w porządku. Na moim profilu z I-dont-care i na czystym z nowy Nano defenderem.

**Comment by krystian3w** [comment]
A strona dopisuje dość późno klasę na body?

**Comment by gwarser** [comment]
Tylko troszkę. I po ukryciu komunikatu szpara zostaje.

**Comment by gwarser** [comment]
Ale masz rację - są generyki:

	[rdk@on filterlists.com_resources]$ grep -r '\.cookies-policy$'
	250_Fanboy's Cookiemonster List.txt:##.cookies-policy
	250_Fanboy's Cookiemonster List.txt:diy.com#@#.cookies-policy
	250_EasyList Cookie List.txt:##.cookies-policy
	250_EasyList Cookie List.txt:diy.com#@#.cookies-policy
	255_Fanboy's Ultimate List.txt:##.cookies-policy
	255_Fanboy's Ultimate List.txt:diy.com#@#.cookies-policy
	247_Fanboy's Annoyance List.txt:##.cookies-policy
	247_Fanboy's Annoyance List.txt:diy.com#@#.cookies-policy
	224_Polish GDPR-Cookies Filters.txt:mydhl.express.dhl##.cookies-policy
	30_Polish Annoyance Filters.txt:mydhl.express.dhl##.cookies-policy
	175_Block the EU Cookie Shit List.txt:##.cookies-policy
	[rdk@on filterlists.com_resources]$ 

Który to był błąd?

**Comment by gwarser** [comment]
To pewnie https://github.com/MajkiIT/polish-ads-filter/issues/14162#issuecomment-513543430 ? (https://github.com/gorhill/uBlock/issues/1885#issuecomment-238520014)

**Comment by krystian3w** [comment]
Tak, dokładnie o takie coś mi chodzi, mnie to nigdy nie łapie, a tobie niby zawsze.

**Comment by Barticf** [comment]
Teraz jest ok.

**Comment by Barticf** [comment]
Teraz jest ok.

**Comment by Barticf** [comment]
Jednak nadal problem występuje. Wchodzę na stronę jest ok, otwieram kilka stron z produktami w tle i któraś wywala białą stronę (nie ma reguły co do tego, bo raz strona z danym produktem powoduje białą stronę innym razem nie)

**Comment by gwarser** [comment]
Spróbuj z `lazienkaplus.pl#@#.cookies-policy`.

**Comment by Barticf** [comment]
Pomogło lazienkaplus.pl#@#.cookies-policy

**Comment by krystian3w** [comment]
Nie wspieramy `EasyList cookies`, śledź: https://github.com/ryanbr/fanboy-adblock/issues/1279

**Comment by krystian3w** [comment]
A `Block the EU Cookie Shit List` niby słynie z zbytniej agresywności przy usuwaniu cookies.
