### ISSUE TITLE
themoviedb.org

### ISSUE THREAD

**Issue by kavillock** [MajkiIT/polish-ads-filter#15458]
### Link bezpośredni 

https://www.themoviedb.org/tv/62699-the-young-pope/images/posters

### Co trzeba zrobić, aby pojawił się błąd?
1.  Wybrać jakikolwiek plakat

### Moja konfiguracja 

**Przeglądarka internetowa:** 
chrome 79
**Rozszerzenia i skrypty:** 

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Wybór jakiegokolwiek plakatu, czy innego elementu używającego pop-boxa jest blokowany przez regułę
`||image.tmdb.org$popup`

**Comment by krystian3w** [comment]
U mnie filtr nie działa, nie blokuje otwierania grafik w nowej karcie.

**Comment by xxcriticxx** [comment]
@krystian3w testowales na chromie?

**Comment by xxcriticxx** [comment]
temp fix `@@||image.tmdb.org^$popup`

**Comment by MajkiIT** [comment]
@kavillock zaktualizowałem filtry. Dzięki za info.
