### ISSUE TITLE
Noworoczne postanowienia Dyrektora

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#15461]
Kiedyś coś pisałem i najwyraźniej umknęło komuś czy coś... Tak czy siak, może uda się Panu Dyrektorowi dotrzymać części postanowień na Nowy Rok 2020:
- [ ] poprawić skrypt, by aktualizował listy Pihole, tylko wtedy gdy jest taka potrzeba i jakby co, to VICHS od PolishFiltersTeam potrafi to robić (podbija datę/timestamp/wersję, tylko gdy jest nowa zawartość)
- [x] usunąć :cookie:, :+1: , RSS i EI z poszukiwania wygasłych domen. W końcu po co marnować energię, PFT i tak korzysta ze swoich ulepszonych skryptów (`https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/master/scripts/expired_domains.sh`, `https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/master/scripts/DSC.sh`) :smile: 
- [x] zaktualizować listę list filtrów na `https://www.certyficate.it/adblock/`
- [x] listę list filtrów zrobić bardziej przyjazną dla urządzeń mobilnych, bo obecnie to trochę słabo jest, że trzeba przewijać w bok. Przykład można brać z `https://polishannoyancefilters.netlify.com/otherfiltersforadblockers/`, ja może nawet mógłbym pomóc, ale strona musiałaby być zmigrowana na Hugo (https://gohugo.io/) i na GH powinien być cały kod, a potem ustawia się w Netlify tak, by automatycznie przebudowywał stronę co każdy commit :smile: 
- [x]  dodać opcję sortowania i wyszukiwania do tabelki z listą filtrów
- [x]  dodać więcej linków do tabelki z listą filtrów (podgląd listy, zgłaszanie problemów, strona główna) i przyciski
- [x]  dodać możliwość wyboru ciemnej strony mocy dla tabelki z listą filtrów
- [x] zaktualizować instrukcję instalacji Polskiej Ciasteczkowej Zgody (https://www.certyficate.it/uzupelnienie-filtrow-ciasteczek-i-rodo/)

**Comment by MajkiIT** [comment]
ad 1 na razie nie mogę tego zmienić. Jak zaktualizuję skrypty na Mikrotik to użyję tego 
ad 2 poprawiłem 10 min temu
ad 3 OK
ad 4 nie widzę sensu na taką ilość filtrów
ad 5 o jakiś konkretnych myślisz?
ad 6 a to aż takie potrzebne ?

**Comment by hawkeye116477** [comment]
Co do punktu 4 to faktycznie może na razie nie jest aż takie niezbędne, ale jak się doda więcej list, to się może przydać.

Co do 5 punktu, to czytaj uważnie i obserwuj jak to jest w przypadku PAF => `https://polishannoyancefilters.netlify.com/otherfiltersforadblockers/` :smile:

`ad 6 a to aż takie potrzebne ?`
Niekonieczne, ale byłoby dobrze jakby się taka opcja pojawiła.

**Comment by hawkeye116477** [comment]
Coś słabo Panie Dyrektorze, tylko jedne postanowienie zrealizowane póki co. Na`https://www.certyficate.it/adblock/` nadal np widzę RSS. Dobrze byłoby jakby całość strony była na GH jak to jest też w przypadku stron list KAD i PAF, wtedy parę PR i strona aktualna :smile:.

**Comment by MajkiIT** [comment]
Tak wiem, trochę jestem od początku w niedoczasie. Obiecuję poprawę :D . Już usunąłem  Discorda. A o co chodziło z RSS?

**Comment by hawkeye116477** [comment]
@MajkiIT Nazwa listy RSS i opis zmienił się. Zobacz jak jest na https://github.com/MajkiIT/polish-ads-filter#polish-filters-for-adblock-ublock-origin--adguard.

**Comment by hawkeye116477** [comment]
@MajkiIT Coś dla ciebie => https://www.netlify.com/blog/2020/03/23/migrate-your-wordpress-site-to-the-jamstack/.

**Comment by MajkiIT** [comment]
@hawkeye116477 Ok, dzięki

**Comment by hawkeye116477** [comment]
Panie Prezesie @MajkiIT, 7 kwietnia o 18:00 odbędzie się webinarium Netlify nt. migracji z Wordpressa do JAMStack, rejestrować może się na `https://netlify.zoom.us/webinar/register/3415853374049/WN_hVvYQLy_Sd2YACOogtqM4w`.

**Comment by hawkeye116477** [comment]
Chyba strona `certyficate.it` się popsuła, na górze zawsze było piękne logo, a teraz zniknęło...

**Comment by MajkiIT** [comment]
@hawkeye116477 już jest. Po upgrade WP i szablonu się rozjechało. Dzięki.

**Comment by hawkeye116477** [comment]
Odnośnie https://github.com/MajkiIT/polish-ads-filter/commit/dcd084c8f79354a84bba57f29e10b8129decca1d. To czy przypadkiem te sklepy nie są już czyste (https://maxkersten.nl/2020/05/06/backtracking-magecart-infections/#raw-results)...

**Comment by MajkiIT** [comment]
@hawkeye116477 Klient chciał abym zablokował te domeny to to zrobiłem.

**Comment by hawkeye116477** [comment]
@MajkiIT Czyli rozumiem, że nikt nawet nie sprawdzał. Ja tam zazwyczaj weryfikuję zgłoszenia.
Czyli ta lista jest robiona na zamówienie dla 1 osoby? Jeżeli tak, to może nie powinna być na GH.
W sumie tak w zasadzie opisu też brak, więc nie wiadomo jaki zakres jest/będzie blokowany.

**Comment by MajkiIT** [comment]
Tak, obecnie dla jednego, ale ma rozbudowaną infrę czyli ponad 4 tys serwerów itp. Plik powstał dla testu a podpięli się pod ten pik produkcyjnie. Jeśli będzie więcej chętnych to przeniosę to.

**Comment by hawkeye116477** [comment]
No to zostały 2 zadania do wykonania, 1-sze zadanie jakby nie do końca wykonane, bo niby aktualizuje tylko jak trzeba, ale numerku wersji w ogóle nie podbija, a rozwiązanie w zasadzie jest łatwe - wykorzystać VICHS. Natomiast jeżeli chodzi o 2-gą misję, to tylko kopiuj i wklej ze strony https://github.com/PolishFiltersTeam/PolishCookieConsent.

**Comment by MajkiIT** [comment]
@hawkeye116477 
Ad 1 Jak mówiłem flow importu pod spodem jest inny. 
ad 2 Zrobione.
