### ISSUE TITLE
hdseans.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15466]
przy wyborze odcina sie otwiera extra popup

test link:
https://hdseans.pl/seriale/13-posterunek-1997-802235/S1-E1

extra popup:
`https://obcas.pl/magda-wojcik-odrzucila-role-w-serialu-z-czego-zyje-i-na-co-poswiecila-wygrana/`

**Comment by krystian3w** [comment]
`hdseans.pl###player:empty`

**Comment by krystian3w** [comment]
mousedown event
```
function() {
  w.jconfirm.lastClicked = $(this);
}
```

**Comment by krystian3w** [comment]
Albo dopisać do #14952 / #15143

**Comment by krystian3w** [comment]
Niby umie otworzyć też się Aju:

`https://aju.pl/wiadomosci/zwierzeta-ktorym-drukarka-3d-uratowala-zycie/`

**Comment by krystian3w** [comment]
Może czas na użycie:

`ebd.cda.pl##+js(window.open-defuser.js)`

https://github.com/gorhill/uBlock/wiki/Resources-Library#windowopen-defuserjs-
