### ISSUE TITLE
teb.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15477]
resztka po RODO blokuje scroll

**Comment by hawkeye116477** [comment]
@kiboke Blocked scroll => `teb.pl#@##cookieModal:not(.countryCookieModalContainer)`.

**Comment by krystian3w** [comment]
Oni mają więcej domen:

@kiboke:
```
technikum.pl#@##cookieModal:not(.countryCookieModalContainer)
```

**Comment by krystian3w** [comment]
Udostępniania na FB/Twitter nie namierzyłem, nie będę się rejestrować dla tej funkcji w "eksranet".
