### ISSUE TITLE
co sądzicie o SponsorBlock

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#15474]
https://github.com/ajayyy/SponsorBlock

**Comment by xxcriticxx** [comment]
sadzimy ze jest niepotrzebne

**Comment by xxcriticxx** [comment]
nie zamykaj moze komus sie przyda

**Comment by krystian3w** [comment]
W sumie ciekawe jak wykrywa ręcznie, jak na bazie zgłoszeń od użytkowników - to raczej trzeba oglądać dużo po premierze.
