### ISSUE TITLE
dane.gov.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15473]

**Comment by krystian3w** [comment]
Ja nie mam.

**Comment by krystian3w** [comment]
To wycina dalej OK:

https://github.com/MajkiIT/polish-ads-filter/blob/8111b0c6ffe57a44249b3d364e9fa7ccbd53c38c/cookies_filters/cookies_uB_AG.txt#L10
https://github.com/MajkiIT/polish-ads-filter/blob/8111b0c6ffe57a44249b3d364e9fa7ccbd53c38c/cookies_filters/cookies_uB_AG.txt#L67
https://github.com/MajkiIT/polish-ads-filter/blob/8111b0c6ffe57a44249b3d364e9fa7ccbd53c38c/cookies_filters/cookies_uB_AG.txt#L68
