### ISSUE TITLE
busradar.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15480]
2x blablakar ( góra i dół ) np tu : https://www.busradar.pl/szukaj/?From=Kraków&To=Warszawa&When=2020-01-08&WhenReturn=&Passengers=1&ShowTrain=false&ShowRidesharing=true&ShowRidesharing=false

**Comment by krystian3w** [comment]
Może:

`##div[id^="leaderboard-"]`
