### ISSUE TITLE
popkulturysci.pl

### ISSUE THREAD

**Issue by wooles** [MajkiIT/polish-ads-filter#15494]
https://i.imgur.com/EAnZbKb.jpg

https://popkulturysci.pl/

Wywala komunikat o adblocku po wejściu ( u mnie po jakichś 5 sekundach) na stronę główną, albo w jakikolwiek artykuł.

**Comment by krystian3w** [comment]
https://www.certyficate.it/polskie-filtry-anti-adblock-brak-wsparcia-w-polskich-filtrach-szanowni-nasi-drodzy-od-07-12-2018-nastapia-zmiany-w-oficjalnych-polskich-filtrach/

I zaktualizuj filtry, dodatkowo zalecamy przejście na uBlock Origin / AdGuard jak do tej pory masz Adblock Plus / AdBlock.

**Comment by krystian3w** [comment]
taki fix stosujemy dla uBO:

```
! popkulturysci.pl
||pagead2.googlesyndication.com^$important,script,redirect=noopjs,domain=popkulturysci.pl
||pagead2.googlesyndication.com^$important,xmlhttprequest,redirect=nooptext,domain=popkulturysci.pl
!
```

**Comment by wooles** [comment]
Mam uBlock Origin, dodatkowo dodany nano defender, nie wiem czemu, ale kiedy klikam na łącze do subskrypcji filtrów to nic się nie dzieje, znaczy wyskakuje pop out o potwierdzenie dodania do ubo ale w ustawianiach rozszerzenia nie widzę filtrów "Polish Anti Adblock Filters"

**Comment by krystian3w** [comment]
Tak:

![obraz](https://user-images.githubusercontent.com/35370833/72097524-dbec0380-331c-11ea-9343-b29f6fa4b63c.png) |
--- |


Co do `nano defendera`, to może makaron spaghetti "JS" winny.

**Comment by xxcriticxx** [comment]
@wooles nastepnym razem prosze o wypelnienie templetu
