### ISSUE TITLE
to.proste.info.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1550]
ad block 

http://to.proste.info.pl/index.php/Defragmentacja_bazy_miejsc_w_FireFox

![capture](https://cloud.githubusercontent.com/assets/15007183/20650647/b6b200bc-b4a1-11e6-89f8-ebef1d34a2e9.PNG)

**Comment by F4z** [comment]
`@@||to.proste.info.pl/menda/adsense.js$script,domain=to.proste.info.pl`
