### ISSUE TITLE
senda.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1551]
ad block 

http://senda.pl/adblock.php

![capture](https://cloud.githubusercontent.com/assets/15007183/20650658/e1c4488c-b4a1-11e6-89a5-88422bf3a3a7.PNG)

**Comment by F4z** [comment]
To powinno pomóc:
`senda.pl#@#.advert_box`
ale zostanie pusta przestrzeń po reklamie.
Nie można jej ukryć, bo wtedy adblock zostanie wykryty (a przynajmniej ja nie znalazłem sposobu).

Natomiast można zmienić jej rozmiar za pomocą tej reguły (działa tylko w uBlocku i Adguardzie):
`senda.pl##.advert_box > div > .tablebg:style(height: 1px !important;)`

**Comment by xxcriticxx** [comment]
@F4z dobre rozwiazanie testowalem jest ok
