### ISSUE TITLE
news.health-beauty.press/long-up/pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15517]
http://news.health-beauty.press/long-up/pl/zdrowa_potencja/?click_hash=RSDmZaHsy0&flow_hash=6277nw0rxi&sub1=2meta-pl-long-bm&sub2=5389&sub3=322-4211557-0&sub4=0.005&sub5=

lub to : 

http://news.health-beauty.press/long-up/pl/zdrowa_potencja/?click_hash=1YUkHsXfxV&flow_hash=6277nw0rxi&sub1=2meta-pl-long-bm&sub2=5389&sub3=322-4211570-0&sub4=0.005&sub5=

więcej tego ścierwa w google pod hasłem " Stare bilety PKP "

@hawkeye116477  podejrzane, może do KAD ?

**Comment by krystian3w** [comment]
invalid - nie to repozytorium
