### ISSUE TITLE
konfigurator.viessmann.com.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#15523]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/72225049-2bcb0480-3581-11ea-95eb-c4c7655fd773.png)

### Link bezpośredni 
https://konfigurator.viessmann.com.pl/

### Co trzeba zrobić, aby pojawił się błąd?
1. Wejść na stronę (nie da się korzystać z konfiguratora)
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox

**Rozszerzenia i skrypty:** 
Nano Defender

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Polskie Filtry Elementów Irytujących
4. Fuck Fuckadblock

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
`@@||konfigurator.viessmann.com.pl/js/CookieAlert.js$script,domain=konfigurator.viessmann.com.pl`

**Comment by krystian3w** [comment]
@kiboke please add white list `viessmann.com.pl`.

bad filter on your list is:

```
/cookiealert.js
```
