### ISSUE TITLE
lubimyczytac.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15538]

**Comment by krystian3w** [comment]
@hawkeye116477  a to: 

![obraz](https://user-images.githubusercontent.com/35370833/72462592-aee29980-37d1-11ea-8a53-452fd1d13277.png)


Niby nie wiem czym oni wykrywają "zoom" przeglądarki, wykryli DPI 125 z Windows... (niby to samo ale raczej nie do końca).
