### ISSUE TITLE
mojanorwegia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#15535]
![Bez tytułu](https://user-images.githubusercontent.com/36385327/72389210-24922b00-3728-11ea-8638-ed55c90caa4a.png)

**Comment by xMaap** [comment]
Reklama
`https://www.mojanorwegia.pl/biznes-i-gospodarka/magiczny-prog-100-miliardow-przekroczony-rekordowy-wynik-norweskiego-eksportu-ryb-16772.html`
![Screenshot_2020-01-14 Magiczny próg 100 miliardów przekroczony Rekordowy wynik norweskiego eksportu ryb](https://user-images.githubusercontent.com/36385327/72389276-425f9000-3728-11ea-8744-5f19e04594e8.png)

**Comment by krystian3w** [comment]
Oni nie mają pop-upa z cookies / rodo... - atakuje cię:

![obraz](https://user-images.githubusercontent.com/35370833/72462225-dab14f80-37d0-11ea-8660-ac2a86819b6c.png)


@xxcriticxx zmieniamy na `reklama`.

**Comment by MajkiIT** [comment]
```
www.mojanorwegia.pl##.artykuly2.ad_1507
www.mojanorwegia.pl##.mnBoxContent
```
