### ISSUE TITLE
dziendobry.tvn.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#15536]
Ukrywa film
`https://dziendobry.tvn.pl/a/wiecznie-glodny-nastolatek-jego-mama-z-laknienia-wybieral-jedzenie-z-kosza-na-smieci
`
![Screenshot_2020-01-15 Wiecznie głodny nastolatek Jego mama Z łaknienia wybierał jedzenie z kosza na śmieci ](https://user-images.githubusercontent.com/36385327/72396259-64fba400-373c-11ea-90ec-a0de7c6c0f42.png)

**Comment by MajkiIT** [comment]
`@@||get.x-link.pl/$subdocument,domain=dziendobry.tvn.pl`
EasyPrivacy

**Comment by krystian3w** [comment]
Fanboy specjalnie to zablokował...
