### ISSUE TITLE
ciechocinek.biz

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1553]
ad block 

![capture](https://cloud.githubusercontent.com/assets/15007183/20650754/48b4aa4e-b4a4-11e6-98c3-19c89f13ca44.PNG)

**Comment by F4z** [comment]
`||ciechocinek.biz/banery_$image`
`ciechocinek.biz##.a-d-v-i`
`@@||ciechocinek.biz/pl/js/show_ads.js$script,domain=ciechocinek.biz`
