### ISSUE TITLE
inwestycje.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1554]
cookie fix + reklama fix 

Szanowni państwo!
 W ramach naszej witryny stosujemy pliki cookies w celu świadczenia Państwu usług na najwyższym poziomie, w tym w sposób dostosowany do indywidualnych potrzeb. Korzystanie z witryny bez zmiany ustawień dotyczących cookies oznacza, że będą one zamieszczane w Państwa urządzeniu końcowym. Możecie Państwo dokonać w każdym czasie zmiany ustawień dotyczących cookies. Więcej szczegółów w naszej „Polityce Cookies”.

**Comment by F4z** [comment]
Jeśli chodzi o reklamy, to ta reguła powinna raczej wystarczyć:
`||rek.www.wp.pl/pliki/*.js$script,important`
Nie trzeba by było tego dodawać, gdyby na liście `Anti-Adblock Killer | Reek` nie było tej reguły - `@@||wp.pl^$script,image`

Można też poprawić tę regułę:
`@@/:\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(.{0,15}[&!*;@\$)[\]:%].*|(?!gaf|cap|vad)[a-zA-Z0-9\W_]{1,10})\.(js|html|xml|jpg|gif|png)/`
Żeby nie zezwalała na ten skrypt (chociaż on i tak zostałby przepuszczony przez regułę z listy AAK):
![image](https://cloud.githubusercontent.com/assets/11742596/20651431/bd394d66-b4e5-11e6-95e1-b1289acc7500.png)
Poprawiona reguła:
`@@/:\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(.{0,15}[&!*;@\$)[\]:%].*|(?!gaf|cap|vad|display)[a-zA-Z0-9\W_]{1,10})\.(js|html|xml|jpg|gif|png)/`

**Comment by MajkiIT** [comment]
@F4z dzięki
