### ISSUE TITLE
zyciesokolowa.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1555]
ad block 

Zauważyliśmy, że korzystasz z wtyczki AdBlock. Wyłącz ją, aby móc w pełni korzystać z portalu albo wyklucz domenę zyciesokolowa.pl

**Comment by F4z** [comment]
`||zyciesokolowa.pl/banery_$image`
`zyciesokolowa.pl##.a-d-v-i`
`@@||zyciesokolowa.pl/pl/js/show_ads.js$script,domain=zyciesokolowa.pl`
