### ISSUE TITLE
Nowa wersja Edge (Chromium)

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15562]
ciekawe czy ublock da sie zainstalowac?

https://antyweb.pl/dostepna-przegladarka-edge-chromium-microsoft-windows-10/

**Comment by krystian3w** [comment]
Tak, z `chrome web store` po zezwoleniu na instalacje z "zewnętrznych" sklepów dodatków.

**Comment by xxcriticxx** [comment]
![Capture](https://user-images.githubusercontent.com/15007183/72551880-c10d1800-3863-11ea-91b0-e0623656f29d.PNG)

**Comment by krystian3w** [comment]
Tak, klikasz allow i się odblokuje button do instalacji uBO.

Lub wersja stąd:

https://microsoftedge.microsoft.com/addons/detail/odfafepnkmbhccpbejgmiehpchacaeak (wersja 1.23.0 - czyli nie są na bieżąco, bo już jest 1.24.2)

**Comment by xxcriticxx** [comment]
to jest fork uBlock Origin Nik Rolls

**Comment by krystian3w** [comment]
Nie, to błędnie zaczytana nazwa starego developera z bazy MS, a kod sobie podkradają z Chrome Web Store:

https://github.com/nikrolls/uBlock-Edge - brak aktualizacji od 2 lat, dalej stoją na `1.15.24`

**Comment by xMaap** [comment]
Ciekawe czy po tym jakoś wpłynie na popularności Chrome. Jednak źle się dzieje, że wszystko teraz jest na Chromium.

**Comment by xxcriticxx** [comment]
wszyscy będą mieli takie same bugi :)

**Comment by hawkeye116477** [comment]
`Nie, to błędnie zaczytana nazwa starego developera z bazy MS`
Raczej pewnie ten cały Rolls wrzuca to do sklepu M$, dlatego jest tam wymieniony.
