### ISSUE TITLE
chodnikliteracki.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15572]
fb ( na dole )

**Comment by krystian3w** [comment]
Już wycinają ze dwa filtry fanboya:

```
/files/*facebook.png
##img[alt="Facebook"]
```

@hawkeye116477  trzeba się chyba złożyć na pasztet i chleb by miał na nowszy procesor.

**Comment by hawkeye116477** [comment]
No nie wiadomo czy nowy procesor wystarczy, może płytę główną też musi wymienić :smile:.

**Comment by hawkeye116477** [comment]
@krystian3w Obserwuj dokładnie.
![Screenshot_20200118_203423](https://user-images.githubusercontent.com/19818572/72669438-f2d3d980-3a31-11ea-9299-445954e9118c.png)
