### ISSUE TITLE
e-krajna.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1557]
ad block + reklamy

Zauważyliśmy, że korzystasz z wtyczki AdBlock. Wyłącz ją, aby móc w pełni korzystać z portalu albo wyklucz domenę e-krajna.pl

**Comment by F4z** [comment]
`||e-krajna.pl/banery_$image`
`e-krajna.pl##.a-d-v-i`
`@@||e-krajna.pl/pl/js/show_ads.js$script,domain=e-krajna.pl`

**Comment by MajkiIT** [comment]
Dzięki
