### ISSUE TITLE
seciki.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1558]
ad block 

http://www.seciki.pl/goo/aHR0cDovL3VwbG9hZHVqLm5ldC9EODE0ZjAvc2hvd3Rlay1mdC13ZS1hcmUtbG91ZHNvbm55LXdpbHNvbi1ib295YWhjcm91emVyLWJvb3RsZWctbXAzLw==

Szanowna Użytkowniczko, Szanowny Użytkowniku!

Wykryliśmy, że używasz Adblocka lub innego narzędzia blokującego wyświetlanie reklam w naszym serwisie.
Prawdobpodobnie powodem tego jest Twoje chroniczne uczulenie na reklamy.
Rozumiemy to i szanujemy, nie tylko Ciebie, ale także i Twoje zdrowie.

Dlatego też w trosce o Twoją kondycję zdrowotną postanowiliśmy zasłonić treści, które mogą pogorszyć Twój stan.
Życzymy szybkiego powrotu do zdrowia i oczywiście zapraszamy kiedy wydobrzejesz.
Nie bądź mendą, nie wysysaj

Nasz serwis utrzymuje się dzięki wyświetlanym reklamom.
Przychody z reklam pozwalają nam na pokrycie kosztów utrzymania serwerów, domeny oraz osób pomagających w administracji serwisem.

Będziemy wdzięczni, jeśli dodasz tę stronę do wyjątków w filtrze blokującym reklamy.
Za co z góry dziękujemy.

**Comment by F4z** [comment]
`@@||seciki.pl/menda/adsense.js$script,domain=seciki.pl`

**Comment by MajkiIT** [comment]
Dzięki
