### ISSUE TITLE
saskakepa.waw.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1559]
ad block 

http://www.saskakepa.waw.pl/kalendarium/dzien/2016-07-20

Drogi Czytelniku!
Nie używaj u nas AdBlocka / uBlocka
Nasz serwis utrzymuje się dzięki wyświetlanym reklamom, akceptując naszą prośbę wspierasz nasz serwis!

PS. Nie bój się, u nas nie spotkasz wyskakujących okienek ;-)

**Comment by F4z** [comment]
`@@||saskakepa.waw.pl/assets/js/ads.js$script,domain=saskakepa.waw.pl`

**Comment by MajkiIT** [comment]
@F4z Dzięki
