### ISSUE TITLE
ksiegarniaakademicka.cba.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15614]
cookies i pop-up

**Comment by krystian3w** [comment]
@MajkiIT  blokujemy te "bitcoiny"?

`cba.pl#?#body > div[style*="position"][style*="fixed"]:-abp-has([href="https://www.mintme.com/"])`

**Comment by krystian3w** [comment]
@hawkeye116477 ja paska cookies nie widzę, to się nadaje do @olegwukr:

`##body > div[style*="background"][style*="black"]:-abp-has([href*="://www.cba.pl/pl/donate/"])`

bardziej temu do "wykrywacza anty-adblock" lub ostrzeżenia przed blokowaniem reklam.

**Comment by hawkeye116477** [comment]
@krystian3w A nie raczej do @KonoromiHimaries?

**Comment by krystian3w** [comment]
Sugeruję się pierwszym zdaniem z paska, raczej i tak nikt płatnej wersji nie kupi, jak widać część ludzi irytuje / mylą z cookies a za mało też pewnie używa PSF.
