### ISSUE TITLE
forumkkozle.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1561]
ad block  

Wiemy, że Internet bez AdBlocka jest denerwujący...

staramy się jednak aby nasza strona nie odgrywała filmów ani muzyki i nie wkurzała Cię za bardzo.
Będziemy wdzięczni, jeśli spróbujesz używać naszego forum z wyłączonym AdBlockiem - daj nam szansę :)
Skoro używasz AdBlocka zapewne wiesz, jak go wyłączyć na naszej stronie ale jeśli nie - skorzystaj z tej instrukcji

**Comment by MajkiIT** [comment]
@xxcriticxx to nie artykuł statyczny?
