### ISSUE TITLE
strony sie same pojawiaja

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#1562]
na niektorych stronach, pojawiaja sie same strony, otwieraja sie lub same zamykaja, a ta strona ktora, chce otworzyc zamyka sie czasem.

**Comment by Isamaul** [comment]
@lukjan32 
Jakiś konkretny adres?

**Comment by lukjan32** [comment]
nie ma konkretno strona.

np. tu http://electro-torrent.pl

**Comment by MajkiIT** [comment]
@lukjan32 
Sprawdź to` ||uvakjjlbjrmx.com^`

**Comment by lukjan32** [comment]
tak samo

**Comment by F4z** [comment]
@lukjan32 a to - `||blprkaomvazv.com^`

**Comment by xxcriticxx** [comment]
@lukjan32 jak podajesz to adres strony jest w tytule a w srodku co nie tak

@F4z to dziala ` |http://$third-party,script,domain=electro-torrent.pl`

@MajkiIT podaj na easylist just in case 

@Isamaul dzien dobry :)

**Comment by MajkiIT** [comment]
@xxcriticxx Ok, thanks

**Comment by lukjan32** [comment]
dobra.

tylko jak dac, aby to bylo na wszystkich stronach?

**Comment by MajkiIT** [comment]
a masz jeszcze jakąś aby porównać te 3 strony?

**Comment by lukjan32** [comment]
nie, to se otwiera automatyczne jak wchodze lub jak klikne na cos.

**Comment by MajkiIT** [comment]
ale podałeś 2 strony i na nich załataliśmy. Czy masz kolejną gdzie Ci się tak otwiera?

**Comment by lukjan32** [comment]
narazie nie

**Comment by lukjan32** [comment]
tamta strona, to nie ja prosilem.

**Comment by MajkiIT** [comment]
@lukjan32 ok, będziemy dalej działać.

**Comment by xxcriticxx** [comment]
from easylist

`@@||ajax.googleapis.com^$script,domain=electro-torrent.pl`
`|http://$script,third-party,domain=electro-torrent.pl`
`|https://$script,third-party,domain=electro-torrent.pl`

**Comment by xxcriticxx** [comment]
@lukjan32 na kazdej stronie jest inaczej otwieraj nowe zgloszenia i zobaczymy co da sie zrobic

**Comment by lukjan32** [comment]
dobra, dzieki. prosze dodac do pliku

**Comment by lukjan32** [comment]
chyba rozwiazalem problem z tymi pojawiajacymi stronami. 

na proba wpisalem tak |https://$script,third-party,domain=

**Comment by MajkiIT** [comment]
@lukjan32 ale to mega nieoptymalne. To będzie działać na każdej stronie i na bank będzie powodowało problemy.

**Comment by lukjan32** [comment]
wlasnie zauwazylem, nie mozna pobrac napisow :(

**Comment by xxcriticxx** [comment]
@lukjan32 podawaj linky to stron my sie zajmiemy reszta

**Comment by lukjan32** [comment]
dobra, dzieki

**Comment by MajkiIT** [comment]
@F4z kolejny przykład http://devil-torrents.pl/

`||vkdbvgcawubn.com/$script,domain=devil-torrents.pl`
`||skzhfyqozkic.com/$script,domain=devil-torrents.pl`
```

**Comment by xxcriticxx** [comment]
podam na easylist

**Comment by MajkiIT** [comment]
@lukjan32 @F4z @xxcriticxx 
znowu zmienił się IPek skryptów na kinomaniak.tv itp. zmieniłem w polskich filtrach.

**Comment by xxcriticxx** [comment]
ok boss super

**Comment by MajkiIT** [comment]
@F4z @xxcriticxx 
Możecie sprawdzić czy to wam zadziała na blokowanie tego losowego IP ?
`/:\/\/(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/.{30,}/$script,popup`

@F4z powiedź co sądzisz o tym regex?

**Comment by xxcriticxx** [comment]
@MajkiIT na jakiej to stronie?

**Comment by MajkiIT** [comment]
na kinoman.tv lub devil-torrents.pl

**Comment by xxcriticxx** [comment]
@MajkiIT nie dziala

**Comment by MajkiIT** [comment]
ale aktualizowałeś polskie filtry? jeśli tak, to wyłącz je do testu.

**Comment by xxcriticxx** [comment]
wylonczylem dalej mam popads.net

**Comment by MajkiIT** [comment]
to nie blokuje przed popads.net tylko skryptami z losowych IPków jak `130.211.230.53`

**Comment by xxcriticxx** [comment]
Mam podac na easylist?

**Comment by F4z** [comment]
@MajkiIT reguła ogólnie wygląda dobrze, tam chyba za ostatnim zamykającym nawiasem brakuje ukośnika `\`, chociaż nie ma to większego znaczenia.
Jeśli ta reguła byłaby ogólna, to zastanawiam się, czy nie będzie za dużo blokować.
Na przykład u mnie po zalogowaniu się do routera, kilka skryptów zostało zablokowanych.
![image](https://cloud.githubusercontent.com/assets/11742596/21294647/0ade1148-c542-11e6-8820-ff2bc75afa96.png)

**Comment by MajkiIT** [comment]
@F4z zaraz coś poprawie

**Comment by MajkiIT** [comment]
@F4z a ten ?

`/:\/\/((?!192\.168)(?!10\.)(?!172\.16)(?!172\.17)(?!172\.18)(?!172\.19)(?!172\.2)(?!172\.30)(?!172\.31)([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/.{30,}/$script,popup`

**Comment by xxcriticxx** [comment]
@MajkiIT ten dziala jeszcze nic mi nie wyskoczylo ale sobie popykam troche

**Comment by xxcriticxx** [comment]
no good wkoncu mi cos wyskoczylo

**Comment by xxcriticxx** [comment]
te filtry + ostatni regex dobrze dziala  

`|http://$script,domain=devil-torrents.pl,third-party`
`@@||ajax.googleapis.com^$domain=devil-torrents.pl`

**Comment by MajkiIT** [comment]
@xxcriticxx wiem, ale mi chodzi o blokowanie tych skryptów z losowych adresów IP.

**Comment by xxcriticxx** [comment]
@MajkiIT easylist tez testowal regexem ale tez im nie wychodzilo maja liste tylko z pop up domains

**Comment by MajkiIT** [comment]
@xxcriticxx ok, ale ja zaryzykuję i chciałbym spróbować.

**Comment by F4z** [comment]
@MajkiIT teraz już nie blokuje.

**Comment by xxcriticxx** [comment]
na devil torrentach dziala ale tylko z kombinacja z filtrami

**Comment by F4z** [comment]
Ja miałem na myśli, że nie blokuje mi skryptów po zalogowaniu do routera.

**Comment by MajkiIT** [comment]
@F4z już myślałem, że coś znowu nabroiłem :D

**Comment by MajkiIT** [comment]
@F4z apropo ruotera

`https://sekurak.pl/malware-w-reklamach-atakujacy-routery-dnschanger/ `

**Comment by xxcriticxx** [comment]
@F4z jakie ty scripty z routera odpalasz?

**Comment by xxcriticxx** [comment]
Unread postby -Mark- » Sat Dec 10, 2016 3:56 pm
Instead of adding these endless amount of domains, why not just create a regex filter and block them for once and for all ?
Unread postby fanboy » Sat Dec 10, 2016 4:11 pm
Regex would most likely cause false positives, or they'll just change it by a few more characters.
Unread postby -Mark- » Sat Dec 10, 2016 4:21 pm
Chances of false positives are less likely considering the regex filter will be for third-party domains with .com domains, and besides you can always create an exception filter for a third party domain if it happens to break the website, which is considerably better than the present situation where the whole easylist is being bloated with endless amount of filters based on endless amount of domains which keep popping up and with no end in sight. This isn't a solution, simply a setback for popads.

**Comment by MajkiIT** [comment]
@xxcriticxx no ok, ale im pochodziło o domeny /.com/ a mi o IPki. Mało kto normalny robiąc stronę wkleja w kodzie adres IP.

**Comment by F4z** [comment]
@xxcriticxx ja żadnych, po prostu po zalogowaniu, router sam ładuje skrypty potrzebne do działania, tak samo jak robią to inne strony.

**Comment by xxcriticxx** [comment]
@F4z nigdy nie zwracalem nato uwagi co router laduje

**Comment by MajkiIT** [comment]
@lukjan32 @F4z @xxcriticxx możecie przetestować na stronie 
`http://lobu.pl/lotr-1-gwiezdne-wojny-historie/`

taką regułę ?
`/^http:\/\/[a-zA-Z.]{10,}\.com\/[a-zA-Z]{2,}\.[a-zA-Z?=]{2,5}/$script,domain=lobu.pl`

**Comment by F4z** [comment]
Wygląda w porządku, tam tylko przed `js` jest raczej niepotrzebny ukośnik.

Odnośnie popads, to tutaj też jest lista tych adresów, ciągle aktualizowana - https://github.com/Yhonay/antipopads/blob/master/popads.txt
można sobie dodać do uBlocka.

Jak ktoś chce, to może też zainteresować się różnymi "trybami" w uBlocku - https://github.com/gorhill/uBlock/wiki/Blocking-mode
Tylko to wymaga odpowiedniej konfiguracji żeby za dużo nie blokowało.
Ja korzystam z tego "trybu" - https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode plus kilka dodatkowych list i odpowiednio skonfigurowane reguły.

**Comment by MajkiIT** [comment]
@F4z Dzięki, to wrzucę to wieczorem.

**Comment by MajkiIT** [comment]
@F4z @xxcriticxx 
Na stronach `http://devil-torrents.pl/` oraz `http://electro-torrent.pl/` znalazłem coś takiego` http://devil-torrents.pl/popup.js`.

Planuję to zablokować tym:
`pl/popup.js|$script`

Co sądzicie?

**Comment by MajkiIT** [comment]
@lukjan32 @F4z @xxcriticxx 
znowu coś pozmieniali na tych stronach, ale o dziwo po moich zmianach w filtrach jest super. Dziwne.

**Comment by xxcriticxx** [comment]
ja nie kozystam z torrnetow to @F4z piratuje windows 10 caly czas

**Comment by MajkiIT** [comment]
@xxcriticxx ja też nie korzystam z torrentów , ale chodzi mi o fakt działania filtrów.

**Comment by xxcriticxx** [comment]
@MajkiIT filtr jest na liscie czy trzeba znowu liste pl liste wylanczac do testow?

**Comment by MajkiIT** [comment]
@xxcriticxx wystarczy, że zaktualizujesz polskie filtry.

**Comment by xxcriticxx** [comment]
@MajkiIT na lobu mi otwiera extra `http://firefox-191219.reupd.net/protect/enable`
na eletro mi otwiera `http://firefox-191219.reupd.net/protect/enable` to samo na devil tez `http://firefox-191219.reupd.net/protect/enable`

**Comment by MajkiIT** [comment]
@xxcriticxx która wersja filtrów?

**Comment by xxcriticxx** [comment]
@MajkiIT moment zrobilem update ale dalej filtry mam z piatku flaszne cache i testuje jeszcze raz

**Comment by F4z** [comment]
@MajkiIT u mnie jest w porządku :)
Dla `devil-torrents` można jeszcze dodać tę regułę - `devil-torrents.pl##script:inject(noeval.js)` - żeby w ogóle nie próbowały wyskoczyć popupy z reklamami, z tych "losowych" adresów IP.

**Comment by MajkiIT** [comment]
@F4z super dzięki. Ta reguła pewnie do reguł uBlocka?

**Comment by F4z** [comment]
@MajkiIT już jest kilka reguł `##script:inject` na ogólnej liście, więc myślę, że tę też można dodać.

**Comment by xxcriticxx** [comment]
@F4z na lobu.pl filmy sie otwieraja jak na play naciskasz, hyba ze to tylko umnie 

test: 

`http://lobu.pl/odtwarzacz/?host=flashx.tv&plugin=flashx&id=wjasd0kd2a5z&ref=/barry/`

**Comment by F4z** [comment]
@xxcriticxx chodzi Ci, że się **nie** otwierają, tak?
U mnie jest to samo, ale to raczej wina jakiejś innej listy.

**Comment by xxcriticxx** [comment]
guzik play nie dziala

**Comment by F4z** [comment]
No tak, u mnie jest tak samo.

Sprawdź proszę, czy po dodaniu tej reguły działa:
`@@||files.fx.fastcontentdelivery.com/showad_.js$script,domain=www.flashx.tv`

**Comment by xxcriticxx** [comment]
@F4z niedziala

**Comment by F4z** [comment]
Ok, a po dodaniu tych dwóch?
`@@||files.fx.fastcontentdelivery.com/showad_.js$script,domain=www.flashx.tv`
`@@||cdn99.fx.fastcontentdelivery.com/flashx.js$script,domain=www.flashx.tv`

**Comment by F4z** [comment]
Ewentualnie te dwie:
`@@||files.fx.fastcontentdelivery.com/showad_.js$script,domain=www.flashx.tv`
`@@||files.fx.fastcontentdelivery.com/jquery2.js$script,domain=www.flashx.tv`

Albo te trzy:
`@@||files.fx.fastcontentdelivery.com/showad_.js$script,domain=www.flashx.tv`
`@@||cdn99.fx.fastcontentdelivery.com/flashx.js$script,domain=www.flashx.tv`
`@@||files.fx.fastcontentdelivery.com/jquery2.js$script,domain=www.flashx.tv`

**Comment by xxcriticxx** [comment]
@F4z nope niedziala tylko strasznie miga 

@MajkiIT co to za klient ten od kada z filtrami?

**Comment by lukjan32** [comment]
ja juz zaktualizowalem filtry, i  dziala.

**Comment by xxcriticxx** [comment]
@lukjan32 lobu.pl?

**Comment by lukjan32** [comment]
nie, ten electro-torrent.pl

**Comment by F4z** [comment]
To nie wiem, u mnie teraz działa bez dodawania żadnych reguł, ale po włączeniu filmu mam informację o adblocku, po dodaniu tej reguły - `@@||files.fx.fastcontentdelivery.com/showad_.js$script,domain=www.flashx.tv` - normalnie film się wyświetla.

**Comment by MajkiIT** [comment]
@xxcriticxx napisał do mnie na fb

**Comment by xxcriticxx** [comment]
chrome czy firefox?

**Comment by F4z** [comment]
Na obu sprawdzałem.

**Comment by MajkiIT** [comment]
@F4z u mnie nie działa.

**Comment by xxcriticxx** [comment]
@F4z na chromie mam ad block 

![capture](https://cloud.githubusercontent.com/assets/15007183/21328434/eb70300a-c601-11e6-93f0-9a95136285db.PNG)

**Comment by F4z** [comment]
@xxcriticxx masz tu włączone reguły i skrypt AAK?

Swoją drogą możesz w Firefoxie sprawdzić te dwie reguły?
`||www.flashx.tv/checkembed.php$script,domain=www.flashx.tv`
`@@||files.fx.fastcontentdelivery.com/showad_.js$script,domain=www.flashx.tv`

**Comment by xxcriticxx** [comment]
na foxie:

ess this video with Kodi / XBMC / TV BOX or AdBlock.

This is prohibited!


If we made a mistake, please contact us via contact form!
Or disable your adblock addon and try again.

Or try to reload the page! !! Click here !!

**Comment by MajkiIT** [comment]
@F4z u mnie po dodaniu tego
||www.flashx.tv/checkembed.php$script,domain=www.flashx.tv
@@||files.fx.fastcontentdelivery.com/showad_.js$script,domain=www.flashx.tv

zobaczyłem to co ma @xxcriticxx , ale jak kliknąłem Click Here jest ok.

**Comment by xxcriticxx** [comment]
@MajkiIT a to niedodalo strony do whitelisty?

**Comment by MajkiIT** [comment]
@xxcriticxx nie

**Comment by xxcriticxx** [comment]
ok

**Comment by MajkiIT** [comment]
@xxcriticxx a teraz z tymi 2 regułami od @F4z już jest bez adblocka

**Comment by xxcriticxx** [comment]
@MajkiIT ten napis mialem co skopjowalem wam
