### ISSUE TITLE
30days.ubi.com [cookies]

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#1563]
https://30days.ubi.com/Promotion/Calendar/
`Click on 1, then a popup opens where you need to login. With below rule it just sits at loading.`
Rule: 
`/js/jquery.cookie.min.js$script,domain=~rozklad-pkp.pl`
Fix: 
`@@||static2.cdn.ubi.com/uplay-connect/v2/live/default/js/jquery.cookie.min.js`

**Comment by MajkiIT** [comment]
Thanks
