### ISSUE TITLE
Filtr Youtube blokuje za dużo

### ISSUE THREAD

**Issue by the4anoni** [MajkiIT/polish-ads-filter#15632]
### Zrzut ekranu 
![Screenshot_20200123-114437_YouTube](https://user-images.githubusercontent.com/13403084/72978218-549b9700-3dd6-11ea-96e4-357da382a28f.png)

### Link bezpośredni 
https://youtu.be/1DqhpuEYNko

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
1. Wejść na powyższy link z aplikacji Youtube z włączonym filtrem YT

### Moja konfiguracja 
**Przeglądarka internetowa:** Nie dotyczy

**Rozszerzenia i skrypty:** Adguard Home

**Listy filtrów:** 

![Screenshot_20200123-115259_Chrome](https://user-images.githubusercontent.com/13403084/72978538-ee634400-3dd6-11ea-8722-359692427287.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Film odtwarza się poprawnie na chromecast (który korzysta z dns adguard home).

**Comment by MajkiIT** [comment]
Jak wyłączysz polskie filtry to jest OK?

**Comment by the4anoni** [comment]
@MajkiIT mogę sprawdzić, ale pogrzebałem i jak dodałem do wyjątków manifest.googlevideo.com
to jest już ok, nawet z Polskimi filtrami.

**Comment by MajkiIT** [comment]
Dziękuję. Usunąłem już filtr.
