### ISSUE TITLE
{NSFW} cosplayjav.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1564]
ad block 

from your friends at adguard.com

`https://forum.adguard.com/index.php?threads/resolved-cosplayjav-pl.16689/`

**Comment by MajkiIT** [comment]
@xxcriticxx dzięki

dodać
||cosplayjav.pl/wp-content/themes/cosplayjav/js/fuckadblock
cosplayjav.pl##.baner-bottom-section
