### ISSUE TITLE
microsoftedge.microsoft.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#15643]
![Bez tytułu](https://user-images.githubusercontent.com/36385327/73010306-7ca8eb80-3e12-11ea-9951-7c13f1aea19d.png)

**Comment by xMaap** [comment]
W Edge na stronie startowej również pojawia się informacja o Cookies
![Bez tytułu](https://user-images.githubusercontent.com/36385327/73011414-774ca080-3e14-11ea-92be-3c344df55f61.png)

Oraz reklamy tego typu
![Bez tytułu](https://user-images.githubusercontent.com/36385327/73011464-90ede800-3e14-11ea-9144-bba4ffe65ee6.png)

**Comment by krystian3w** [comment]
Strona startowa jest nietykalna przez dodatki, chcesz wyciąć to musisz popróbować jakimś AdGuard for Windows.

**Comment by krystian3w** [comment]
Dodatkowo sklepy też są nietykalne przez dodatki.

z tej domeny cookies ruszysz tylko AdGuardem: `microsoftedge.microsoft.com` w Edge.
