### ISSUE TITLE
filmy na wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1565]
cos mi dzisaj zadne filmy na wp nie chca wystartowac. moze ktos potwierdzic???

**Comment by F4z** [comment]
Po dodaniu tej reguły działa?
`@@||googleads.g.doubleclick.net/pagead/ads?sdkv=*&video_product_type=*&url=http%3A%2F%2F*wp.pl%2F*&description_url=http%3A%2F%2Fwp.tv`

**Comment by xxcriticxx** [comment]
zaj zaczynalismy to byly 3 kropki co sie krecily i krecily  po dodaju tej reguly jest ad block

**Comment by xxcriticxx** [comment]
tutaj dalej sie kreca 
http://sportowefakty.wp.pl/pilka-nozna/648117/bartosz-kapustka-nie-jest-jeszcze-gotowy-do-gry-na-poziomie-premier-league

tutaj jest ad block 
http://www.money.pl/gospodarka/wiadomosci/artykul/prawo-wodne-zeglarze-oplata-denna,168,0,2208168.html

**Comment by F4z** [comment]
Patrzyłem bez żadnego rozszerzenia do blokowania reklam, to te trzy kręcące się kropki też się pokazują.
Jeśli chodzi o adblocka, to ta reguła powinna pomóc:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=www.money.pl`

U mnie po kilku/kilkunastu odświeżeniach film zaczął działać, sprawdzałem z włączonym rozszerzeniem do blokowania reklam jak i z wyłączony i była ta sama sytuacja.
Może coś robią i dlatego i tak się dzieje.

**Comment by xxcriticxx** [comment]
ok to zobaczymy jutro czy sa jakies zmiany
