### ISSUE TITLE
wazcar.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15656]

**Comment by krystian3w** [comment]
@hawkeye116477 wycinać to?

![obraz](https://user-images.githubusercontent.com/35370833/73200246-afb2ee00-4136-11ea-899d-26344ba3cba4.png)

**Comment by hawkeye116477** [comment]
Nie, ważne info, zostawiamy.

**Comment by krystian3w** [comment]
A pamiętasz te domeny silent?

`global.silnet.pl/media/js/vue/silnet-privacy-policy.vue$xmlhttprequest`

niby schemat url mają jakiś nowy - inne foldery i subdomena

**Comment by hawkeye116477** [comment]
@krystian3w Nie.
