### ISSUE TITLE
nieruchomosci-bez-posrednikow.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15652]
to samo, tu : 

http://nieruchomosci-komercyjne.info/
http://www.firmy-uslugi24.pl/

**Comment by krystian3w** [comment]
co ja ci poradzę, nie uruchomimy generycznego:

`info,pl#?##body > div[style*="position"][style*="fixed"]:not([id]):not([class]):-abp-contains(/(cookies|RODO)/)`
