### ISSUE TITLE
notino.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15662]

**Comment by krystian3w** [comment]
@hawkeye116477 dociąć kosmetycznie jak już banuje to Peter Lowe?

`||exponea.com^`

na chromium może tej domeny nie widać - CNAME tracking.

**Comment by hawkeye116477** [comment]
@krystian3w Tak. Na WF Classic też nie widoczne, tak czy siak ta opcja z CNAME nie jest nawet w stabilnym wydaniu na razie.
