### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by takenek** [MajkiIT/polish-ads-filter#1566]
Cześć,
Od dawna używam Waszych filtrów niestety od paru dni zauważyłem, że na wp.pl i wielu innych portalach wyskakują mi reklamy... czy to specjalnie ? Zweryfikowałem strona nie jest dodana do zaufanych i niby adblock twierdzi, że zablokował 41 mimo to od groma reklam na www.wp.pl pojawia się....
Podobnie jest z wieloma innymi stronami.
Pozdr

**Comment by MajkiIT** [comment]
używasz AAK filters?

**Comment by takenek** [comment]
Chrome + adblock a używam wszystkich filtrów z http://www.certyficate.it/polski-filtr-adblock/ czyli:
- blokowanie reklam na polskich stronach (polski filtr adblock,ublock) – metoda polecana
- blokowanie komunikatów cookies na polskich stronach filtr komunikatów Cookies- metoda polecana
- blokowanie reklam na Facebooku
- blokowanie reklam na Youtube
- blokowanie komunikatów o włączonym dodatku Adblock/uBlock
- globalne filtry reklam

Zaktualizowane przed chwilą.

**Comment by MajkiIT** [comment]
Easylist?
Reek filters?

**Comment by takenek** [comment]
Używam dokładnie to co Ci podałem :-) Nic poza tym :-)

**Comment by MajkiIT** [comment]
Jak możesz daj zrzut z listy filtrów w Adblock

**Comment by takenek** [comment]
Podrzucę wieczorem bo pracuje na zdalnym pulpicie i coś mi print scr nie działa.

**Comment by MajkiIT** [comment]
ok, a może czas przejść na uBlock?

**Comment by takenek** [comment]
A jaka jest różnica między adblock a uBlock?

**Comment by takenek** [comment]
Cześć,
Zainstalowałem uBlock z automatu pobrał Twoje filtry i zero reklam na wp.pl :-)
Dzięki!
