### ISSUE TITLE
zdrowie.gazeta.pl

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#1567]
http://zdrowie.gazeta.pl/Zdrowie/10,112276,17942425,doktorze-czy-to-cos-powaznego-blahe-dolegliwosci-czy-juz-choroba.html

**Comment by MajkiIT** [comment]
@adreporter 

sprawdź proszę to:

`@@|http://cdnv.gazeta.pl/ad/banner/_adsense_/_adserver/_adview_.ad.json$xmlhttprequest,domain=gazeta.pl`

**Comment by xxcriticxx** [comment]
@MajkiIT good job dziala

**Comment by adreporter** [comment]
Potwierdzam, działa.
