### ISSUE TITLE
videopenny.net

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15685]
@MajkiIT regex fix please 

wybierajac host `youdbox` sie otwiera nowe okno z popup 

test link:
https://www1.videopenny.net/filmy-pol/pilsudski-2020-a3-a4,2564,100012,2564,09/

**Comment by MajkiIT** [comment]
@xxcriticxx Zaktualizuj i sprawdź proszę.

**Comment by xxcriticxx** [comment]
@MajkiIT thanks na razie jest super
