### ISSUE TITLE
Wyskakujące okna z reklamami

### ISSUE THREAD

**Issue by Gunderyk** [MajkiIT/polish-ads-filter#1568]
Na stronie http://www.efilmy.tv/filmy.html podczas otwierania filmu (prawie za każdym razem) pojawiają się wyskakujące okna z reklamami. Zarówno na Chrome jak i Firefox.

**Comment by MajkiIT** [comment]
u mnie jest ok. Zaraz inni sprawdzą .

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z 
zerkniecie u siebie?

**Comment by Gunderyk** [comment]
Mam Ublock Origin filtry aktualne, nie wiem o co chodzi. :(

**Comment by Gunderyk** [comment]
Rozszerzenie Tampermonkey coś zmieni?

**Comment by MajkiIT** [comment]
Nie powinno. Poczekaj xxcriticxx i F4z zerkną u siebie.

**Comment by Gunderyk** [comment]
Otworzyłeś film, a próbowałeś kliknąć w pasek postępu,by przesunąć film? Najczęściej wtedy wyskakuje zakłada z reklamą.

**Comment by xxcriticxx** [comment]
@MajkiIT ja mam to samo co @Gunderyk podaje jak klikasz na paske sie otwiera nowe okno. ale to jest hyba z streamin.to reklamy

**Comment by Gunderyk** [comment]
Tutaj: http://auratorrent.pl/ podobna sytuacja: przy logowaniu i nie tylko.

**Comment by xxcriticxx** [comment]
@Gunderyk czytaj https://github.com/MajkiIT/polish-ads-filter/issues/1518

**Comment by Gunderyk** [comment]
Nie wiem czy dobrze rozumiem, do Chrome dodać: ||104.198.188.21^$popup
Czy będzie ten filtr dodany do ogólnej listy?

**Comment by xxcriticxx** [comment]
@Gunderyk dodaj do my filters i potestuj 

@MajkiIT te filtry sa juz na lisicie?

**Comment by MajkiIT** [comment]
tak są, dokonałem małej poprawki i już jest ok. 
@Gunderyk zaktualizuj filtry

**Comment by Gunderyk** [comment]
Bardzo dziękuję na auratorrent.pl Ok :) Rozumiem, że na http://www.efilmy.tv/filmy.html w wolnej chwili także coś napiszecie, by zablokować reklamy. :)

**Comment by xxcriticxx** [comment]
@Gunderyk  podaj link do filmu

**Comment by Gunderyk** [comment]
Nie ma reguły prawie przy każdym wyskakiwały reklamy. Teraz po aktualizacji filtrów i dodaniu KAD jakoś nie, jeszcze poklikam.

**Comment by Gunderyk** [comment]
Otwarłem ok. 10 filmów jest takie 'szarpnięcie' ale nowa zakładka z reklamą się nie otwiera. Jeszcze jutro poklikam jak będzie ok, zamykamy. :)

**Comment by xxcriticxx** [comment]
na blyskanie  `auratorrent.pl##script:inject(noeval.js)` (działa tylko w uBlocku).

**Comment by Gunderyk** [comment]
Dodałem efilmy.tv##script:inject(noeval.js) nie mogę otworzyć filmu.

**Comment by xxcriticxx** [comment]
@Gunderyk kazdy domain jest inny

**Comment by xxcriticxx** [comment]
@Gunderyk na efilm proponuje kodi wtyczke

**Comment by Gunderyk** [comment]
"Szarpnięcie" mi nie przeszkadza, najważniejsze, że nie ma reklam. :) Dziękuję Panowie i pozdrawiam!

**Comment by xxcriticxx** [comment]
niedlugo cos dodamy do efilmy.tv w od dzielnym poscie

**Comment by Gunderyk** [comment]
Tak z ciekawości o to chodzi? https://chrome.google.com/webstore/detail/play-to-kodi/fncjhcjfnnooidlkijollckpakkebden

**Comment by xxcriticxx** [comment]
@Gunderyk 

https://github.com/mrknow/filmkodi
https://github.com/ramicspa/kodi

**Comment by Gunderyk** [comment]
Wszystko jasne, dziękuję, zamykam. :)

**Comment by F4z** [comment]
Trochę późno odpowiadam, ale wcześniej nie mogłem.
@Gunderyk jeszcze możesz spróbować z tą regułą (działa tylko w uBlocku):
`streamin.to##script:inject(noeval.js)`
Wtedy nie powinno "błyskać", "migać", "szarpać", a film powinien się normalnie wyświetlać.
Ewentualnie to:
`streamin.to#@#.adsbox`
Jeśli ta pierwsza działa, to tej drugiej nie trzeba dodawać.

**Comment by Gunderyk** [comment]
SZACUN PANOWIE! Ten filtr działa streamin.to##script:inject(noeval.js)  dodałem do uBlock. Pytanie czy ten filtr będzie dodany do ogólnych reguł ?

**Comment by xxcriticxx** [comment]
da sie cos zrobic

**Comment by Gunderyk** [comment]
Czyli w uBlock tymczasowo, później usunąć. Jeszcze raz dzięki.

**Comment by xxcriticxx** [comment]
jak @MajkiIT doda do listy to jedna regula automatycznie sie wylonczy

@Gunderyk podawaj nastepne strony nowym temacie :)

**Comment by Gunderyk** [comment]
Miałem problem z AVG AntiVirus Free,więc odinstalowałem. Mam teraz Awasta i pojawił się problem,gdy usunę filtr: 
streamin.to##script:inject(noeval.js) okna z reklamami nadal wyskakują. Proszę o dodanie do ogólnych filtrów.

**Comment by xxcriticxx** [comment]
@Gunderyk tlumaczylem ci przeciez oglondaj filmy przez kodi :)

**Comment by F4z** [comment]
Ta reguła - `streamin.to##script:inject(noeval.js)` działa tylko w uBlocku, więc pewnie zostanie dodana do dodatkowej listy "polskie filtry do uBlocka uzupelnienie", można ją sobie dodać ręcznie, dodając ten adres w uBlocku - https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt
Albo poprzez kliknięcie w drugi link na tej stronie - https://www.certyficate.it/adblock/

**Comment by Gunderyk** [comment]
@F4z Dziękuję,pozdrawiam. :)
