### ISSUE TITLE
mcdonalds.pl/mcdelivery/

### ISSUE THREAD

**Issue by p0358** [MajkiIT/polish-ads-filter#15686]
### Zrzut ekranu 

(nie powinien być potrzebny)

### Link bezpośredni 

https://mcdonalds.pl/mcdelivery/

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. Otwórz stronę
2. Żaden element nie jest klikalny

### Moja konfiguracja 

**Przeglądarka internetowa:** Firefox 73.0b10

**Rozszerzenia i skrypty:** uBlock Origin

**Listy filtrów:** 
```
Filtry sieciowe: 108 867 + filtry kosmetyczne: 125 583 z:

        Moje filtry​​​​​użytych 23 z 23​​​​ 
    Wbudowane (5/5)
        uBlock filters​

​​​​użytych 19 957 z 20 033​​
​​
uBlock filters – Badware risks​
​​​​użytych 829 z 830​​
​​
uBlock filters – Privacy​​​​​użytych 170 z 170​​
​​
uBlock filters – Resource abuse​​​​​użytych 117 z 117​​
​​
uBlock filters – Unbreak​​​​​użytych 1373 z 1376​​

    ​​ 

Reklamy (1/4)

    EasyList​

​​​​użytych 81 049 z 81 402​​

    ​​ 

Prywatność (3/3)

    AdGuard Tracking Protection​

​​​​użytych 8451 z 8566​​
​​
EasyPrivacy​
​​​​użytych 13 272 z 17 023​​
​​
Fanboy’s Enhanced Tracking List​
​​​​użytych 3381 z 3399​​

    ​​ 

Domeny ze złośliwym oprogramowaniem (2/4)

    Malware Domain List​​​​​użytych 1104 z 1104​​

​​
Malware domains​
​​​​użytych 26 845 z 26 860​​

    ​​ 

Elementy irytujące (5/7)

    AdGuard Annoyances​

​​​​użytych 22 853 z 24 971​​
​​
Anti-Facebook​
​​​​użytych 68 z 68​​
​​
EasyList Cookie​
​​​​użytych 16 738 z 16 742​​​​ Fanboy’s Annoyance​​​​​użytych 39 438 z 56 505​​
​​
uBlock filters – Annoyances​​​​​użytych 2947 z 2948​​

    ​​ 

Wielofunkcyjne (1/4)

    Peter Lowe’s Ad and tracking server list​

​​​​użytych 3294 z 3295​​

    ​​ 

Regiony, języki (2/35)

    POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda​

​​​​użytych 6135 z 6724​​
​​
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku​
​​​​użytych 1065 z 1078​​

    ​​ 

Własne (1/1)

    Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for uBlock Origin​​

​​​użytych 443 z 445​​​​
```

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Wygląda na to, że
`mcdonalds.pl##.cookies` 
rozwiązuje problem.
Jest element z klasą .cookies który przykrywa całą stronę, jest to wynikiem zablokowania skryptu z "cookies" w ścieżce.

**Comment by hawkeye116477** [comment]
@p0358 Jeżeli jest to blokowane przez listę Easylist Cookie, to raczej do nich ten problem proponuję zgłosić.

**Comment by hawkeye116477** [comment]
@p0358 Nie masz Polskiej Listy Rodo-Ciasteczkowej i I don't care about cookies.

**Comment by p0358** [comment]
@hawkeye116477 Faktycznie nie miałem wymienionych na tej instalacji. `I don't care about cookies` zawiera filtr który zawiera regułę naprawiającą problem dokładnie na tej stronie. Można zamknąć w takim razie
