### ISSUE TITLE
pepper.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#15690]
https://www.pepper.pl/promocje/aztez-od-13-do-20-lutego-w-epic-store-games-232771

**Comment by xxcriticxx** [comment]
@KonoromiHimaries gdzie ta reklama? jakis screenshot mozna prosic?

**Comment by krystian3w** [comment]
cofamy title i offtopic - promocja gry, wpis informacyjny.

**Comment by hawkeye116477** [comment]
Wiem, co tydzień są darmowe gry, kolekcjonuję już od zeszłego roku :smile:
