### ISSUE TITLE
devil-torrents.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1569]
`|http://$script,domain=devil-torrents.pl,third-party`
`@@||ajax.googleapis.com^$domain=devil-torrents.pl`
`devil-torrents.pl##script:inject(noeval.js)`

**Comment by F4z** [comment]
Żeby nie "migało" można jeszcze dodać tę regułę:
`devil-torrents.pl##script:inject(noeval.js)`

**Comment by xxcriticxx** [comment]
rozwiazanie z easylist 

`@@||devil-torrents.pl^$generichide`
`|http://$script,third-party,domain=devil-torrents.pl`
`@@||ajax.googleapis.com^$domain=devil-torrents.pl`
`||130.211.230.53^$popup`
