### ISSUE TITLE
zobacz.ws

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15697]
![Capture](https://user-images.githubusercontent.com/15007183/74112308-73858180-4b69-11ea-9ea9-0b133b356d2e.PNG)

**Comment by krystian3w** [comment]
```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=zobacz.ws
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=zobacz.ws,redirect=noopjs,important
@@/wp-content/plugins/deblocker/*$script,1p
```

`/wp-content/plugins/deblocker` takie coś dodało uAssets niby generycznie blokowało anty-adblocki a tu nie pomaga...

**Comment by xxcriticxx** [comment]
dziala
