### ISSUE TITLE
wyłącz AdBlock/uBlock

### ISSUE THREAD

**Issue by Janasek** [MajkiIT/polish-ads-filter#15693]
witajcie, 

postanowiłem zainstalować pi-hole na kodi po dodaniu kilku list 
i wprowadzeniu adresu ip kodi jako dns do routera coś zaczyna się dziać 

zainstalowałem też przeglądarke slimjet i opera nie dodałem żadnego adblockera nic 
nie jest blokowane za pomocą przeglądarki

teraz na wp.pilot info wyłącz adblocka bla bla bla
czy pi hole nie jest ukrytym programem który blokuje wszystko zanim to dotrze do przeglądarki?

nie jestem biegły w sumie uzywam to od kilku dni ale podejść robiłem kilkanascie rok ,dwa temu
na vps również ale odpuszczałem za kazdym razem z powodów braku integracji z vpn muszę mieć polskie ip zeby odpalić większość źródeł..... (na kodi reklam nie ma sprawa jasna ale poprzez ten program filtruje cały dom)

Sprawdziłem też adguard home tu problem z wp.pilot znika ale jakoś to nie chce działać na kodi
a tylko to mam włączone 24h 
sprawdałem również tylko dla przukładu jak działa blokowanie np. google.com
okazało się że nijak

0.0.0.0 google.com
127.0.0.1 google.com
||google.com^

nic to nie daje srona nadal wyświetla się

większoś z was uzywa tego typu zabawek czy też macie podobne problemy?
prawdopodobnie nie ten dział lub złe miejsce na zadawanie takich pytań ale nie bardzo wiem gdzie
szukać większych informacji na takie tematy

thx..

**Comment by xxcriticxx** [comment]
@Janasek mam pihole I mam vpn napisz z czym trzeba tobie pomoc

**Comment by krystian3w** [comment]
Google zbanujesz tylko tym:

```
0.0.0.0 www.google.com
0.0.0.0 www.google.pl
```

Potem zostaje używać:

https://duckduckgo.com/
https://www.qwant.com/
https://www.startpage.com/
https://privatelee.com/
https://searx.me/
https://www.ecosia.org/
https://gibiru.com/
https://www.bitclave.com/

**Comment by Janasek** [comment]
> @xxcriticxx 

z tym vpn sprawa wygląda tak:
tworzę vpn na vps i ten vpn nie działa z pi-hole ,on działa ale nie filtruje reklam po prostu omija pi-hole

w domu router ma wbite jako dns adres maszyny na której stoi pi-hole jest to 192.168.1.12
jak tworze vpn i dodam właśnie dns 192.168.1.12 to działa wszystko ale to tylko ta jedna opcja
używając innego vpn skąd by nie był nie ma w nim dns pi-hole i nie filtruje

@krystian3w 

to był tylko przykład i nie do pi-hole a do adguard ,chciałem sie dowiedzieć co źle robię że ten przykład nie działa , a skoro on dla testu nie działa to i inne też działac nie będą
wydaje się że ma bardziej rozbudowane filtrowanie: https://github.com/AdguardTeam/AdGuardHome

co prawda w 80% aplikacje jestem wstanie usunąć reklamy samodzielnie w kodi ich nie ma 
ale chciałem uzywać adguard czy pihole jako taki wstęp przed ublock widac różnicę dosyc sporą 
jak ublock nie musi filtrowac wszystkiego a tylko kosmetyke

**Comment by xxcriticxx** [comment]
@Janasek zeby mieć polski IP omijasz pihole i używasz DNS z vpn

**Comment by Janasek** [comment]
tak jak pisałem jak załaduje do vpn-a dns z pi-hole to dziala i reklam nie ma ,ale jak uzyje vpn-a od jakiegoś tam dostawcy np. mydevil reklamy są i nie są filtrowane , pogmatfane to troche i słabe
że nie da się używać klik i działa

**Comment by hawkeye116477** [comment]
`wydaje się że ma bardziej rozbudowane filtrowanie`
No najwyraźniej prawda => https://kb.adguard.com/en/general/dns-filtering-syntax, ale chyba póki co nie ma Polskich filtrów wykorzystujących to rozbudowane filtrowanie.

**Comment by Janasek** [comment]
0.0.0.0 example.org , wiekszość podejdzie od pihole
||example.org^ , adblock ,ublock i tym podobne

**Comment by xxcriticxx** [comment]
@Janasek ja i tak mieszam pihole z ublockiem na networku

wp.pl omijam z dala tak jak kościół

**Comment by Janasek** [comment]
tu masz racje ale chcialem sprawdzić jak to działa a wp i ipla to chyba jedne z najlepszych stron do tesów tam nie ma nic wiele oprócz reklam i okazało się że pihole wykrywalne dla  strony wp

ale pamiętam jak przy aplikacji grzebałem to **wp.pl** też rozwalało mi aplikacje podczas modyfikowania

**0.0.0.0 wp.pl** i to pewnie też jakiś konflikt i tu jest

czyli ten vpn nie bedzie dialal kazdy tylko wymagane jest własnie dns takie jakie ma pihole inne vpn-y dzialac nie będą ?

dobra spoko walczę dalej....

**Comment by xxcriticxx** [comment]
@Janasek nie używasz scriptu do oglondania player/TVP vod?

**Comment by Janasek** [comment]
ja to mam w android na boxie + w kodi tez mam kilka addonów

a skryptu to za bardzo nie znam, byl jakis do pobierania z servisów vod ale to lata temu

**Comment by xxcriticxx** [comment]
Dalej jest https://greasyfork.org/pl/scripts/6049-skrypt-umożliwiający-pobieranie-materiałów-ze-znanych-serwisów-vod/feedback

**Comment by Janasek** [comment]
myślałem o innym , strona jakoś tak sie nazywałą "przyjazne skrypty" "potzebne skrypty" jakoś tak
mniejsza z tym 

jak ktoś potrzebuje aplikacje tvp vod i wp to sa obie bez reklam 
nie podchodziłem do aplikacji na android tv nie wiem czy też jestem wstanie usunąć reklamy 
kiedyś jak bedzie więcej czasu to zaglądne i do nich ,na ten moment zawsze kupuje już zrotowane boxy i to co jest mi potrzebne to to około 15 linijek w pliku hosts nawet AdAway nie jest mi potrzebny.

a te aplikacje zrobiłem poprostu w celach szkoleniowych , co też robię z pi-hole i adguard bo nie znam ich za bardzo stąd też te pytania

https://github.com/Janasek/RapidLauncher

**Comment by xxcriticxx** [comment]
@Janasek ja używał win/Linux nie android

**Comment by hawkeye116477** [comment]
@xxcriticxx To co z ciebie taki słaby fan nadgryzionego 🍎...  A Apple TV masz?

**Comment by xxcriticxx** [comment]
Tak mam pełno złomu

**Comment by Janasek** [comment]
> @Janasek ja używał win/Linux nie android

ogarnołem temat blokady na wp. wywaliłem wszystkie filtry teraz nie wiem który to był ale chyba AdAWAY ,reszta powinna juz gladko pójść , strasznie mnie korci ten adguard jutro go na pc przetestuje zadna robota cmd i juz dziala nawet instalować nie trzeba

**Comment by xxcriticxx** [comment]
@Janasek co ty próbowałeś z pihole odpalać ze tobie nie działało?

**Comment by Janasek** [comment]
wp.pilot , i nie zależy mi na tej stronie ani troche ,ale drazni mnie ze nie działa i zamiast zając się czyms innym to szukam rozwiązanie i wcale nie wiem po co ,ale tak juz mam i wczesniej czy później to wyłapie

**Comment by xxcriticxx** [comment]
Patrzyłeś co jest blokowane w logu?

**Comment by Janasek** [comment]
niby tak poodchaczałem gemiusy wp jakies tam ale nic nie dalo ,wywaliłem wszystko od nowa i wydaje sie że tylko host file nie blokuje wp pewnie kilka jeszcze też przejdzie ,ale żeby to zbadać trzeba czyscic przeglądarke inaczej co bys nie dodał to działa ale po godzinie okazuje się ze jednak nie działa

**Comment by xxcriticxx** [comment]
@Janasek sprobuj tego:

`grep /etc/pihole/gravity.list` or `pihole -t | grep gravity.list`

na yt juz dawno rozwiazania nie ma. ja uzywam tego dziala na 50-75%

https://www.reddit.com/r/pihole/comments/9w5swx/i_think_ive_managed_to_block_youtube_ads_with/

**Comment by Janasek** [comment]
musze poszukac odpowiedników pod Dockera
przeskoczyłem na szybko na AdGuarda załadowałem kilka reguł ktore na pihole nie pozwalały na otwarcie video na stronie wp. i jak  do tej pory wszystko działa poprawnie nawet 
http://winhelp2002.mvps.org/hosts.htm
który też w pihole był wyłapywany przez wp działa poprawnie ,zobaczymy co ztego wyjdzie 
teraz tylko wyszukać fajną konfiguracje pod dockera i powinno byc.

**Comment by xxcriticxx** [comment]
Pihole ma oficjalny docker image nie wiem jak z adguardem zapytaj Adama

**Comment by Janasek** [comment]
też mają Pi-Hole udało mi się zainstalować bez najmniejszego problemu 
do adguarda podchodzilem raz bez rezultatu, zobaczymy nie uda się to usune libreelec i postawie windowsa jakiegoś okrojonego i na nim adguarda odpale, lub zainstaluje na vps ,ale tego chcę uniknąć.

**Comment by xxcriticxx** [comment]
@Janasek ja uzywam tych list okolo 900 k hostow blokuje 30% zero problemow

https://v.firebog.net/hosts/lists.php?type=tick

**Comment by Janasek** [comment]
spoko nie usunąłem pihole tylko wyłaczyłem pobawie się adguardem i załaduje te które podaleś 

czy po instalacji pihole pozostawiłes filtry które oni podali chyba 4 jak się nie myle?

**Comment by xxcriticxx** [comment]
dodalem 41 listy z tej strony co podalem te 4 standardowe tam chyba juz sa

**Comment by Janasek** [comment]
powoli dodaje twoje reguły i cała reszte + to co wyłapuje w telefonie poprzez Wicap

vpn ogornięte działa mobilna sieć 3g ,4g ale wskoczyłem na vps 
co do pozostalych vpn to pojęcia nie mam czy działaja takie jak express vpn ,vanish czy pure
ale jak nie to dalej kicha z użytkowaniem tego typu blokerów

**Comment by hawkeye116477** [comment]
Jest jeszcze KADhole => `https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhole.txt`.

**Comment by xxcriticxx** [comment]
@Janasek testowales czy nie masz jakis extra portow po otwieranych? AKA open dns resolver test

**Comment by Janasek** [comment]
@hawkeye116477 
dodane dzięki

@xxcriticxx 
niby coś sprawdzalem ale czy dobrze,pojecia nie mam 
podeślesz komendy ?

**Comment by xxcriticxx** [comment]
@Janasek to nie komendy to jest test na stronie internetowej

example: https://dnsleaktest.com/

**Comment by Janasek** [comment]
tu sprawdziłem i szału nie ma ,jest poddatny na ataki dns https://openresolver.com/

 https://dnsleaktest.com/ , jakieś austriackie strony nie wiem co to vpn mam pl ,widocznie mnie przechwytują

**Comment by xxcriticxx** [comment]
@Janasek pihole jest proste w uzytku i dla tego duzo ludzi z tego korzysta

**Comment by Janasek** [comment]
uzywanie jako tako ok ale jak dojdzie vpn to juz nie , jeszcze nabiles mi czpila tym sprawdzaniem i wychodzi na **poddatny na ataki** 
**Listen on all interfaces, permit all origins = poddatny**
reszta znów albo z vpn albo wcale i nadal nie osiągnąlem tego  co chciałem 
nie wiem czemu jest poddatny , oprogramowanie samo powinno chronic a jest odwrotnie

https://i.ibb.co/zFHDhYy/2020-02-10-15h10-35.png
https://i.ibb.co/cb9qspk/2020-02-10-15h15-47.png
https://i.ibb.co/HYrvgwP/2020-02-10-17h00-06.png

**Comment by hawkeye116477** [comment]
@Janasek https://docs.pi-hole.net/guides/vpn/dual-operation/

**Comment by Janasek** [comment]
tak robiłem to ,otwarcie opcji all interface oznajmnia mi to

https://i.ibb.co/zFHDhYy/2020-02-10-15h10-35.png

https://openresolver.com/

dobra po zabawie , zamykać czy pozostawić jeszcze na jakis czas|?

**Comment by xxcriticxx** [comment]
port 53 otwarty

**Comment by Janasek** [comment]
zablokowanie portu czy odwrotnie przez ufw nic nie zmienia
dobra nie wiem jak to zrobić tzn sieć domowa ok działa 
reszta do kosza nie zrobie bo po prostu nie mam wiedzy

**Comment by xxcriticxx** [comment]
@Janasek ile masz klientow? ile % blokuje?

**Comment by Janasek** [comment]
nie chodzi o blokowanie reklam tylko o zaaplikowanie vpn na wszystkie sieci
klientów mam 8

teraz mam tak: **Listen only on interface tun0** to dziala poprzez vpn

po właczeniu : **Listen on all interfaces, permit all origins** mam to 


![test image size](https://i.ibb.co/rtPQMwG/2020-02-10-15h10-35.png?raw=true)

co raczej zdrowe nie jest

**Comment by xxcriticxx** [comment]
@Janasek ja nie uzywam po za domem i tutaj tobie pomóc nie moge. pytales na pihole reddit?

**Comment by Janasek** [comment]
spoko dzięki i tak wiem więcej dzięki wam

**Comment by xxcriticxx** [comment]
dont worry amigo 

https://www.reddit.com/r/pihole/

**Comment by Janasek** [comment]
I'm not worried, I'm just pi..ed off
