### ISSUE TITLE
efilmy.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1570]
from our friend at easylist

`/adsvid/*`
`efilmy.tv##.addbackground`

@F4z masz cos na miganie ???

**Comment by F4z** [comment]
@xxcriticxx - https://github.com/MajkiIT/polish-ads-filter/issues/1568#issuecomment-263970879
`streamin.to##script:inject(noeval.js)`

**Comment by xxcriticxx** [comment]
ok
