### ISSUE TITLE
fasardi.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15716]
na środku : https://www.fasardi.com/pl/jeansy-z-perelkami-na-nogawkach-czarne-1036.html

**Comment by krystian3w** [comment]
przegapiony newsletter na dole:

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/edit/master/PPB/newslettery_nie_popupy.txt

**Comment by blocker999** [comment]
@krystian3w Przegapiam celowo bo od czego mam Ciebie ?
No chyba że wolisz mniej zgłoszeń ?
