### ISSUE TITLE
collaborators

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1571]
@MajkiIT wloncz to dla @F4z i zobaczymy czy on da rade liste zmienic 

https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

https://help.github.com/articles/permission-levels-for-a-user-account-repository/

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z Gotowe zerknijcie

**Comment by F4z** [comment]
@MajkiIT dzięki.
Widzę, że mam nowe opcje, ale najpierw muszę zrozumieć jak to działa i ogólnie przetestować (pewnie stworze dla testów coś u siebie) żeby niczego nie zepsuć.

**Comment by MajkiIT** [comment]
@F4z 
Tutaj masz pliczek i się pobaw 
https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/test.txt

**Comment by MajkiIT** [comment]
@F4z Jak coś to pytaj

**Comment by F4z** [comment]
@MajkiIT ok, dzięki :)
