### ISSUE TITLE
jackjones.com/pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15710]
( na dole )

**Comment by krystian3w** [comment]
Newsletter i strzałka:

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/edit/master/PPB/newslettery_nie_popupy.txt
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/edit/master/PPB/strzalki.txt
