### ISSUE TITLE
Windows 12

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#15721]
Macie już ten nowy Windows 12? Jak tam wrażenia, mniej bugów niż w 10? Podobno jest 3 razy szybszy, nie ma niespodziewanych aktualizacji, reklam i jest całkowicie odporny na wszelkie wirusy :smile:.

<img src="https://www.webhouses.co.uk/images/litedesk.png">

**Comment by xxcriticxx** [comment]
wtf? lol

**Comment by krystian3w** [comment]
GNU/Linux z „Windowsową” tapetą.

**Comment by krystian3w** [comment]
https://ginamiller.co.uk/

**Comment by xxcriticxx** [comment]
@hawkeye116477 to much free time?

**Comment by hawkeye116477** [comment]
Nie tylko tapeta, ikony też zmienione :smile:
<img src="https://preview.redd.it/o8pl847d9xf41.jpg?width=960&crop=smart&auto=webp&s=a4ee96a65a17417de7d722e8e16ca032488e345d">
