### ISSUE TITLE
rzeszow.citybuzz.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#15720]
`https://rzeszow.citybuzz.pl/newsy/dach-g2a-areny-zostal-uszkodzony-podczas-wichury/`
![Bez tytułu](https://user-images.githubusercontent.com/36385327/74179930-bc5b3a00-4c3e-11ea-968c-0258d16c4062.png)

**Comment by MajkiIT** [comment]
@xxcriticxx Masz to ?

**Comment by xxcriticxx** [comment]
@MajkiIT nope

**Comment by MajkiIT** [comment]
@xxcriticxx Thanks

`rzeszow.citybuzz.pl##.g1-sticky-widget`
