### ISSUE TITLE
websystem.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1573]
http://websystem.pl/SK-TU3-PBR-24V

![capture](https://cloud.githubusercontent.com/assets/15007183/20808143/7f891b30-b7cf-11e6-958c-5277e00480df.PNG)

zdjecia sie nie wyswietlaja

**Comment by F4z** [comment]
`@@||websystem.pl/environment/cache/images/300_250_$image,domain=websystem.pl`

**Comment by xxcriticxx** [comment]
@F4z dziala testowalem super thx
