### ISSUE TITLE
sklep.pl.canalplus.com

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#15756]
https://sklep.pl.canalplus.com/prepaid-mix
Popsuta strona, informują, że w ofercie nie ma żadnych kanałów.

Chyba filtr `/frosmo.easy.js` z EP powoduje problem.

**Comment by krystian3w** [comment]
`tally-weijl.com` miało podobnie.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/6282

**Comment by hawkeye116477** [comment]
@MajkiIT Poprosimy o fixa :smile:

**Comment by krystian3w** [comment]
Gorzej jak tylko w Polish Privacy

**Comment by MajkiIT** [comment]
ale frosmo.easy.js nie jest blokowane :D. Mam dodać wyjątek ?

**Comment by krystian3w** [comment]
Jest blokowane przez EasyPrivacy, na przyszłość wołaj może `Khrin`?

**Comment by hawkeye116477** [comment]
Problem nadal nie rozwiązany, a EP to lista domyślna.

**Comment by krystian3w** [comment]
#16521

**Comment by krystian3w** [comment]
https://github.com/NanoMeow/QuickReports/issues/3298
