### ISSUE TITLE
lycos.com

### ISSUE THREAD

**Issue by ghost** [MajkiIT/polish-ads-filter#1575]
Strona jest blokowana przez uBlock, po wyłączeniu filtrów kosmetycznych jest ok.

**Comment by F4z** [comment]
Powinno pomóc:
`lycos.com#@#.cookies`

**Comment by Gunderyk** [comment]
Dziękuję, jest okey. :) Proszę dodać do ogólnej listy.

**Comment by MajkiIT** [comment]
Dzięki
