### ISSUE TITLE
vod.tvp.pl

### ISSUE THREAD

**Issue by barolo** [MajkiIT/polish-ads-filter#1576]
Pojawiło się powiadomienie o adblocku na video, takie samo jak na sport.tvp*

**Comment by xxcriticxx** [comment]
@barolo podaj link plz

**Comment by F4z** [comment]
Dzięki za zgłoszenie, ta reguła powinna to ukryć:
`tvp.pl###tvpoverlay_abdinfo`

**Comment by barolo** [comment]
@F4z Działa, dzięki!
