### ISSUE TITLE
sadistic.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#15775]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/75613773-e8792500-5b31-11ea-8362-2ebd373d7ca7.png)

### Link bezpośredni 
https://www.sadistic.pl/

### Co trzeba zrobić, aby pojawił się błąd?
1. Włączyć jakiś filmik na stronie
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox

**Rozszerzenia i skrypty:** 
NanoDefender
uBlock

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Adguard
4. Inne polskie filtry

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Na firefoxie przy włączonym uBlock'u nie odtwarzają się filmiki, ciągły pasek ładowania. Na przeglądarce vivaldi nie ma takiego problemu, wyłączenie tego wbudowanego systemu przeciw śledzeniu nic nie daje.

**Comment by Barticf** [comment]
Wyłączenie filtru POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda pomaga

**Comment by krystian3w** [comment]
`JQuery` powoli odchodzi do lamusa, czas by portale od marnowania czasu (czy rozrywki niskich lotów) przeszły na czysty JavaScript w standardzie: `ecmascript 6`
