### ISSUE TITLE
filmninja.ws

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15780]
test link:
https://filmninja.ws/kanal/27/eleven-sports-2

![Capture](https://user-images.githubusercontent.com/15007183/75817688-a0dadf00-5d65-11ea-971f-df79aa9c1dd9.JPG)

**Comment by krystian3w** [comment]
`@@/js/ads.js$script,domain=filmninja.ws`

**Comment by xxcriticxx** [comment]
potwierdzam dziala

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/fc610143ac5d3fce84b326b935a35b98aff3599d#diff-6de60f294b8bd23c752f8fcbece875b1

**Comment by xxcriticxx** [comment]
adblock

test link do filmu trzeba nacisnac "Oglądaj":
https://filmninja.ws/film/skorumpowany-the-corrupted-2019

![Capture](https://user-images.githubusercontent.com/15007183/76700848-039b7700-6692-11ea-8bf3-d5d633575126.PNG)

**Comment by krystian3w** [comment]
`https://playtube.ws/embed-8hy77dwag0ol.html`

raczej zgłoś do AdGuard / uAssets jako międzynarodowe...
