### ISSUE TITLE
klimacold.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15798]
fb ( button ) i inne ciekawe elementy

**Comment by krystian3w** [comment]
@hawkeye116477 do kogo ta reklama:

![obraz](https://user-images.githubusercontent.com/35370833/76248572-e30e8f80-6241-11ea-8e7c-2ae8690c7fca.png) |
--- |

Polskie wewnętrzne?

**Comment by hawkeye116477** [comment]
Do EI.
