### ISSUE TITLE
eu.puma.com/pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15805]
( na dole )

**Comment by krystian3w** [comment]
@hawkeye116477 shadow root, może robimy listę bugi uBlock Origin (raczkuje by działały generyki z shadow root)?

**Comment by krystian3w** [comment]
@gwarser da się łączyć nadrzędny nod z nodem w shadow root?

chodzi mi, że taki filtr nie rusza:

```
eu.puma.com##puma-footer .puma-footer__section__title
eu.puma.com##puma-footer .puma-footer__more__icons
```

i muszę usunąć `<puma-footer>`

**Comment by hawkeye116477** [comment]
@krystian3w U mnie działa.

**Comment by krystian3w** [comment]
takie ci działa:

```
##.puma-footer__section__title
##.puma-footer__more__icons
```

Poza tym pewnie w legacy nie naprawili a pewnie Blady Księżyc obsługuje jakiś shadow root.

**Comment by hawkeye116477** [comment]
Nie korzystam z Bladego, w WF Classic takie:
`eu.puma.com##puma-footer .puma-footer__section__title
eu.puma.com##puma-footer .puma-footer__more__icons`
działają :smile:.

**Comment by krystian3w** [comment]
Na Firefox z `1.25.0 Commit/11037fc` nie.

**Comment by hawkeye116477** [comment]
A może to dlatego, że WF Classic nie obsluguje Shadow DOM v1. W sumie nie widzę tam shadow roota, więc pewnie tak.

**Comment by krystian3w** [comment]
Ja mam aż 2 w sumie:

![obraz](https://user-images.githubusercontent.com/35370833/76248176-1b619e00-6241-11ea-8289-7d23150f009c.png) |
--- |

**Comment by gwarser** [comment]
> da się łączyć nadrzędny element z podrzędnym już w shadow root?

Nie.

Zrobiłem mały research i tylko takie coś widzę:

- https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context() (to by pasowało pewnie ale tylko Chrome obsługuje)
- https://developer.mozilla.org/en-US/docs/Web/CSS/:host()
- https://developer.mozilla.org/en-US/docs/Web/CSS/:host

No i nawet nie chce mi działać w dev-tools.

**Comment by hawkeye116477** [comment]
Kiedyś była zabawa z /deep/, teraz najwyraźniej chyba już nie działa.
