### ISSUE TITLE
hdseans.pl - padł 

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#15806]
![obraz](https://user-images.githubusercontent.com/11302675/76246691-8198f180-623e-11ea-8d66-0798ed5bd5d1.png)

**Comment by MajkiIT** [comment]
https://ekino-tv.pl - też :/

**Comment by xxcriticxx** [comment]
teraz będą seedboxy sprzedawac

**Comment by MajkiIT** [comment]
Wydaje mi się, że to tylko zaślepka
