### ISSUE TITLE
kubofonista.net

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1583]
ad block 

Drogi Czytelniku, wygląda na to, że korzystasz z oprogramowania blokującego wyświetlanie reklam. Wyświetlane tu reklamy nie mają inwazyjnej formy i nie utrudnią Ci nawigacji, a środki z reklam pozwalają mi utrzymać serwis i pomagają w jego dalszym rozwoju. Z góry dziękuję za wyrozumiałość.

**Comment by F4z** [comment]
`@@||kubofonista.net/r/ad.htm$script,domain=kubofonista.net`
