### ISSUE TITLE
orange.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#15854]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/76679483-39ccee00-65e1-11ea-987b-395b665aad5a.png)

### Link bezpośredni 
https://www.orange.pl/

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. Kliknąć "Kontakt" na górze strony

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox

**Rozszerzenia i skrypty:** 
uBlock
Nano Defender
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Polskie Filtry Elementów Irytujących

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by xxcriticxx** [comment]
@Barticf masz zamontowane i-dont-care-about-cookies?

**Comment by Barticf** [comment]
@xxcriticxx nie

**Comment by xxcriticxx** [comment]
@Barticf prosze zamontuj jest wymagane z PL cookies
