### ISSUE TITLE
orange.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#15855]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/76679542-b8c22680-65e1-11ea-8a49-e45435a0bad9.png)

### Link bezpośredni 
https://www.orange.pl/

### Co trzeba zrobić, aby pojawił się błąd?
1. Kliknąć "Kontakt" 
2. Wybrać czat z doradcą
3. Kliknąć uruchom

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox

**Rozszerzenia i skrypty:** 
uBlock
Nanodefender

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Polskie Filtry Elementów Irytujących
4. Polskie Filtry Społecznościowe​

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Czat się nie uruchamia, po wyłączeniu uBlocka już jest ok

**Comment by xxcriticxx** [comment]
dla mnie to z wylaczonym blokerem nie dziala

**Comment by Barticf** [comment]
@xxcriticxx u mnie tak wygląda jak wyłączę
![obraz](https://user-images.githubusercontent.com/32641928/76681244-4bb68d00-65f1-11ea-83b6-37edf9dbbd43.png)

**Comment by xxcriticxx** [comment]
@Barticf ja posiadam ip spoza PL moze mnie zablokowac

**Comment by Barticf** [comment]
Wyłączenie Polskie Filtry Elementów Irytujących pomaga

**Comment by krystian3w** [comment]
Bo to widżet kontaktowy - @hawkeye116477 nie blokować go już nigdy więcej na Orange?

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/908d338f0d46b782f58fdf1289fae2f9598bd123/PPB/widgety_kontaktowe_informacji_zwrotnej.txt#L384

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/e4eac274c1b7f5ababf8155e9c1dbce0dfab4f34

**Comment by krystian3w** [comment]
Naprawione w:

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/605ccce778153807313e5ad36d477c10a20017e3#diff-e8b662a22222e5fb9f02df67781b8dccR3431

Do zgłoszenia invalid za złe miejsce zgłoszenie problemu.

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/issues/3108
