### ISSUE TITLE
zakupek.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1587]
ad block 

Drogi Czytelniku! Wygląda na to, że korzystasz z oprogramowania blokującego reklamy. Te obecne u nas nie mają inwazyjnej formy, a środki z ich emisji pozwalają utrzymać serwis przy życiu. Ostateczny wybór co do ich blokowania zawsze jednak należy do Ciebie! ;)

**Comment by F4z** [comment]
`@@||zakupek.pl/wp-content/themes/zakupek/bannery/adbanner.htm$script,domain=zakupek.pl`
