### ISSUE TITLE
forum.drivecenter.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1589]
ad block 

Wygląda na to, że twoja przeglądarka blokuje wyświetlanie reklam. Drivecenter.pl jest serwisem utrzymującym się wyłącznie z reklam i dotacji. Przychody z reklam pozwalają nam na pokrycie kosztów związanych z utrzymaniem serwisu. Będziemy wdzięczni, jeśli dodasz naszą stronę do wyjątków filtra blokującego reklamy.

Z góry dziękujemy za zrozumienie.

**Comment by MajkiIT** [comment]
`forum.drivecenter.pl##.rklm_sidebar`
`forum.drivecenter.pl##.rklm_forumlist`
