### ISSUE TITLE
kobieta.onet.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15890]
brak filmiku : https://kobieta.onet.pl/koronawirus-dodatkowe-zalecenia-higieniczne-na-czas-kwarantanny/ewcm7q7

**Comment by MajkiIT** [comment]
u mnie jest 

![obraz](https://user-images.githubusercontent.com/11302675/77077060-fe715b80-69f4-11ea-99d5-151a529f56d3.png)
