### ISSUE TITLE
multikino.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#15920]
blokuje tresc na multikino.pl

**Comment by krystian3w** [comment]
?

**Comment by krystian3w** [comment]
@kiboke consider remove:

`##.cookie-msg-box:not(body):not(html)`

another page with locked scroll.

**Comment by xxcriticxx** [comment]
@lukjan32 kino zamknięte zostaly tylko torrenty i newsgroups

**Comment by lukjan32** [comment]
wiem, ale jak byly otwarte, to nie mozna przewijac strony na dol

**Comment by hawkeye116477** [comment]
@xxcriticxx Nieładnie, już chcesz na złą drogę sprowadzić... 
Ja za to podpowiem => Netflix, Disney+, HBO GO, Amazon Prime, Ipla, Player ewentualnie zwykłe kanały satelitarne (HBO, Canal+, Polsat Film, AXN, Ale Kino, Cinemax, Fox, Paramount Channel, Sci Fi, Comedy Central). Platformy też zrobiły promocję w postaci dodatkowych kanałów w ramach akcji `#zostanwdomu`, np. `https://pl.canalplus.com/kanaly-odkodowane?content=karuzela`.

**Comment by xxcriticxx** [comment]
@hawkeye116477 milo cie widziec

**Comment by krystian3w** [comment]
Od 17 godzin można jak zaktualizowałeś filtry "Polskie filtry elementów irytujących" lub od  5 jak zaktualizowałeś "Polskie filtry ciasteczkowe :cookie:".

**Comment by lukjan32** [comment]
mnie nie bylo, dzieki

**Comment by hawkeye116477** [comment]
@lukjan32 Czyli jest ok, to co nie zamyka?

**Comment by lukjan32** [comment]
narazie ok

**Comment by hawkeye116477** [comment]
@xxcriticxx To może ciebie zainteresuje, że kino jutro ponownie otwierają i tylko 13 zł za bilet (https://www.wirtualnemedia.pl/artykul/od-srody-startuje-kino-wp-pilot-z-filmami-w-cenie-biletu-do-kina).

**Comment by Lukjan39** [comment]
@krystian3w brak rozwijanego opcji filtruj, przy kalendarzu przy dniach repertuaru.

**Comment by krystian3w** [comment]
Ale czemu, bo RODO ukryte?

**Comment by Lukjan39** [comment]
nie wiem, tak mam, jak naciskam filtruj, przy wlaczonym ublock origin.
![filtr](https://user-images.githubusercontent.com/104568362/205479448-0cb0cbfb-cae0-4d39-bdaf-d1087719dc5d.jpg)
