### ISSUE TITLE
androidbeztajemnic.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1593]
ad block 

Używanie AdBlocka krzywdzi szczeniaczki
Żartowałem. Nic nie jest jednak pewne - na wszelki wypadek go wyłącz lub zastanów się nad darowizną. Dziękuję.

**Comment by F4z** [comment]
Może to:
`androidbeztajemnic.com###text-16.widget.widget_text`
