### ISSUE TITLE
buliba.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#15958]
info o adblocku

**Comment by MajkiIT** [comment]
@blocker999 możesz dać jakiś zrzut ?

**Comment by xMaap** [comment]
Ja również nie widzę, ale jest pozostałość po reklamie
https://www.buliba.pl/nasze-gry/gry-zrecznosciowe.html
![Screenshot_2020-04-27 www buliba pl - Gry zręcznościowe](https://user-images.githubusercontent.com/36385327/80321404-0f479500-881d-11ea-95d1-32d9c9a9fb7c.png)
