### ISSUE TITLE
porteuropa.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1596]
ad block 

Wygląda na to, że korzystasz z Adblocka!
Reklamy są jedynym źródłem utrzymania strony.
Proszę, okaż nam wsparcie i wyłącz Adblocka na naszej stronie!!!!
Przeczytaj, dlaczego to takie ważne:
Lubisz nasz portal? Nie blokuj reklam!

**Comment by F4z** [comment]
Na przykład:
`porteuropa.eu##i#g207`
