### ISSUE TITLE
ofertynakarte.prv.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#15966]
### Zrzut ekranu 
![Screenshot_20200327_101006](https://user-images.githubusercontent.com/19818572/77740227-28d5a100-7013-11ea-8494-4ae6c491410e.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Biała ramka

**Comment by krystian3w** [comment]
`||ofertynakarte.prv.pl/prv_billboard`
