### ISSUE TITLE
Strona CIT/adblock

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#15961]
Po wejściu na `https://www.certyficate.it/adblock/`, po jakiś może 30 sekundach wskakuje przekierowanie na `https://majkiit.github.io/polish-ads-filter/`. Nie wiem czy tak miało być, ale tak czy siak trochę nie za elegancko, bo ktoś zdąży pół strony przeczytać i nagle przekierowane i z powrotem na górę leci. A tak po za tym, to tagi br są widoczne, najwyraźniej Jekyll i Hyde czy jak tam oni się zwą, niestety nie ogarniają htmla :smiley:

**Comment by MajkiIT** [comment]
po 3s :D 
<meta http-equiv="refresh" content="3; url=https://majkiit.github.io/polish-ads-filter/" />

**Comment by krystian3w** [comment]
Na wikipedii gorzej, powiększam obrazek i przewija mnie na sam szczyt...

**Comment by hawkeye116477** [comment]
`po 3s`
Tak czy siak albo przekierowanie do wylotu albo powinno być natychmiastowe bez lądowania na nieaktualną stronę.

**Comment by xxcriticxx** [comment]
@hawkeye116477 nasz web developer jest na kwartalnie

**Comment by hawkeye116477** [comment]
@xxcriticxx Na domowej kwarantannie? W tym przypadku w niczym to nie przeszkadza, w domu też może to załatwić :stuck_out_tongue:

**Comment by xxcriticxx** [comment]
@hawkeye116477 na domowej bez internetu :)

**Comment by xxcriticxx** [comment]
@MajkiIT script sprawdza filtry mikrotech i pihole co 30 min czy naprawde jest taka potrzeba? mysle ze by wystarzczylo raz na tydzien.

**Comment by krystian3w** [comment]
Już było by nie podbijać daty bez zmiany w filtrach (dodana / usunięta domena).

**Comment by xxcriticxx** [comment]
sie dziwie ze jeszcze github emaila nie wyslal

**Comment by hawkeye116477** [comment]
@xxcriticxx Wysłali, tylko @MajkiIT nie przeczytał i z powodu tego, że im nie odpisał ani nic się nie zmieniło w tej sprawie, kazali mi przekazać, żeby korzystał odpowiedzialnie z GH, nie przeciążał, bo inaczej dadzą mu szlaban na commitowanie na 2 tygodnie + :banana: na miesiąc dla @MajkiIT-automat :smile:.

**Comment by krystian3w** [comment]
I ogólnie to niby wersja `raw` ma około 5 minutową zawiechę (czasem takie coś mam z Polskie EI / KAD).

**Comment by MajkiIT** [comment]
@xxcriticxx jakie filtry  mikrotech i pihole ??

**Comment by MajkiIT** [comment]
@krystian3w To nie zawiecha, tylko cachowanie contentu. Cache wygasa po 5 min .

**Comment by xxcriticxx** [comment]
@MajkiIT `hole_cert_pl.txt` and `addHoleCertDomains.rsc` update jest co 30 min

**Comment by xxcriticxx** [comment]
@MajkiIT czemu wszystko z `hole_cert_pl.txt` ma takie same ip z przodu `195.187.6.34`?

**Comment by krystian3w** [comment]
Bo "mikrotik" umie wyświetlać stronę "195.187.6.34" zamiast błędu połączenia.

IP odpowiada adresowi:

`https://hole.cert.pl/`

**Comment by MajkiIT** [comment]
@xxcriticxx już poprawiłem i jest przy zmianie pliku. 

![obraz](https://user-images.githubusercontent.com/11302675/77823389-20f12c00-70fb-11ea-8f5b-3caae64740a4.png)

Ten adres IP to adres Cert PL i na nim jest ostrzeżenie 
![obraz](https://user-images.githubusercontent.com/11302675/77823408-441bdb80-70fb-11ea-9290-4a1a7cea4483.png)

**Comment by xxcriticxx** [comment]
@MajkiIT to bardzej nie pasuje do KAD filtrow?

**Comment by MajkiIT** [comment]
Chodzi ci o filtry ?

**Comment by xxcriticxx** [comment]
@MajkiIT tak

**Comment by MajkiIT** [comment]
@xxcriticxx 
Tak pokrywa się to, ale tych reguł nie ma w filtrach KAD i są to nowe domeny. Nic nie stoi na przeszkodzie aby je tam dodawać.

**Comment by xxcriticxx** [comment]
rozumiem

**Comment by MajkiIT** [comment]
@hawkeye116477 rozwiniesz swój palec w dół ?

**Comment by hawkeye116477** [comment]
`tych reguł nie ma w filtrach KAD`

Nieprawda, są i będą stale dodawane, nawet w formie regex dla skuteczniejszej ochrony. A tak w ogóle, to nieładnie usuwać komentarze na `https://www.certyficate.it/blokowanie-domen-z-listy-holecert-na-mikrotik/`.

**Comment by MajkiIT** [comment]
Domena 'platnik247.online' która była dodana do listy holecert o 10:28 na KAD pojawiła się o 13:04, czyli jak mówiłem, nie ma ich wcześniej w liście KAD. Ponadto łatwiej komuś wrzucić listę 60 domen niż 9 tys z listy KAD .

Twój komentarz/e nie są związane z listą holecert. Ot i cała zagadka.

**Comment by hawkeye116477** [comment]
`Twój komentarz/e nie są związane z listą holecert. Ot i cała zagadka.`

KADhole zawiera te domeny z HoleCert w formie regex, dlatego o tym napisałem .

**Comment by MajkiIT** [comment]
Projekt Holecert bazuje na blokowaniu w DNS w DNScache dostawców ISP. Aby dodać regex do pihole trzeba to wrzucić ręcznie, bo regex nie są importowane przy update. 

Chyba trzeba robic to tak ==> https://github.com/eternnoir/pihole-regex.list

**Comment by hawkeye116477** [comment]
@MajkiIT Można po prostu wykorzystać skrypt => https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/master/Readme_RLI_for_Pi-hole.md, potem dodać go do crona, no problem.

**Comment by MajkiIT** [comment]
Czyli trzeba robić coś dodatkowo i poza dasboardem PIHOLE. Takie podejście pewnie pewnie jest dla zaawansowanych userów.

**Comment by hawkeye116477** [comment]
Coś słabo wierzysz, poradzili sobie z instalacją PH, to i poradzą z tym. Tak czy siak, warto, to zawsze skuteczniejsza ochrona.


`czyli jak mówiłem, nie ma ich wcześniej w liście KAD`

Wiele domen nie pojawia się od razu jak są opisane. Jak ma być najwcześniej, to chyba najlepiej dodać bezpośrednio z `hole.cert.pl/domains/domains.txt`. Tak czy siak, mogliśmy zrobić automatyczną listę, jednak zastosowaliśmy inną strategię, dodajemy ręcznie, sprawdzamy czy lepiej dodać główną domenę czy subdomenę albo regex. A tak w ogóle, to mówiłeś, że nie ma, nie mówiłeś, że nie ma wcześniej, drobna różnica, ale jednak...  Tak czy siak, jak tam uważasz, ja nie protestuję.


`Ponadto łatwiej komuś wrzucić listę 60 domen niż 9 tys z listy KAD .`
Może łatwiej, ale jednak to trochę słaby argument, bo więcej = skuteczniejsza ochrona.

**Comment by krystian3w** [comment]
wildcard pod podatnika był chyba przed listą cert, więc oni mają laga...

**Comment by xxcriticxx** [comment]
Dziś jest ...Dzień Żelków

**Comment by MajkiIT** [comment]
@hawkeye116477 W co ja wierze to inna para kaloszy. 

Lista KAD była od dawna i na bank przyniosła korzyść nie raz. Rozwiązaniu Certu to rozwiązanie które dostaje pod nos użytkownikowi ochronę i niejako użytkownik dostaje ją w gratisie. Oba rozwiązania mogą się uzupełniać, bo ten kto korzysta z Wasze listy i tak będzie miał blokowane domeny a lista certu stanie się uzupełnieniem tego, ale patrząc na to, że lista certu odświeżana jest co 5 min to świadczyć to może o chęci szybkiej blokady. 

W cert też są ręczne weryfikacje, bo nic się nie dzieje z automatu, bo można zrobić "kuku". 

Doprecyzowując ===> 'czyli jak mówiłem, nie ma ich wcześniej w liście KAD' chodziło mi o to, że jak zobaczę wpis w liście Certu to domena jest "świeżynką" i nie ma jej w waszych listach. 

"Ponadto łatwiej komuś wrzucić listę 60 domen niż 9 tys z listy KAD ." Wyjaśniając.... aby wrzucić na Static DNS 9 tys domen trzeba mieć RAM na urządzeniu i nie każdy ma sprzęt tyle rekordów. Lista Certu ma być lekka a lista KAD jest już za duża. Można oczywiście wrzucić komuś to i powiedzieć, że jest SECURITY, ale coś za coś.

**Comment by hawkeye116477** [comment]
`W cert też są ręczne weryfikacje, bo nic się nie dzieje z automatu, bo można zrobić "kuku".`
Raczej chodziło mi o to, że u ciebie jest automat, ręcznie nie dodajesz.


`Lista Certu ma być lekka`
Gdzieś napisali, że takie mają postanowienie? Na razie może jest, ale ciekawe jak to będzie po paru latach. No chyba, że ty będziesz decydował co do usunięcia z listy.

**Comment by MajkiIT** [comment]
@hawkeye116477 Nie napisali, ale chyba żaden operator nie zdecyduje się na impost np. 9 tys domen. Ma to blokować domeny, które są aktywne obecnie, ale zobaczymy jak to będzie wyglądać, bo na razie jeszcze nawet tydzień nie minął.

**Comment by hawkeye116477** [comment]
`Ma to blokować domeny, które są aktywne obecnie`

W KAD też usuwamy nieaktywne, a jednak jakoś za specjalnie lista nie chudnie. 

Tak czy siak, jak tam stryjenka chce, PFT robi to po swojemu :smile:


A tym czasem, może pora wrócić do tematu => https://github.com/MajkiIT/polish-ads-filter/issues/15961#issuecomment-603941021. Oprócz tego nadal jest problem z tagami br, trochę to nieprofesjonalnie wygląda, może lepiej zrobić coś w stylu `https://gohugo.io/hosting-and-deployment/hosting-on-github/`, czyli osobne repo na stronę i wtedy można-by dorobić data file, by wygodniej dopisywać kolejne wpisy do tabeli. Oprócz tego można dostosować do urządzeń mobilnych.

**Comment by xxcriticxx** [comment]
30 marca - Światowy Dzień Muffinka

**Comment by xxcriticxx** [comment]
Dziś jest Światowy dzień budyniu

**Comment by krystian3w** [comment]
Budyń na wodzie, kisiel na mleku?

**Comment by hawkeye116477** [comment]
Raczej na odwrót...

**Comment by xxcriticxx** [comment]
Dziś jest Prima Aprilis!

**Comment by krystian3w** [comment]
Na razie usunęli jedną - ma podaną datę wykreślenia, bo ct8 zbanowało darmowe konto i subdomenę też; pewnie nazwa przez najbliższy rok nie wróci do rejestracji.

**Comment by hawkeye116477** [comment]
@xxcriticxx Dzisiaj jest Międzynarodowy Dzień Wróbelków :smile:

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/6404#issuecomment-607282868 - cert współpracuje z mobilnym operatorem...?

**Comment by MajkiIT** [comment]
@krystian3w tak, podmieniają adresy IP w DNS dla tych domen.

**Comment by xxcriticxx** [comment]
> @xxcriticxx Dzisiaj jest Międzynarodowy Dzień Wróbelków 

`Dziś jest Światowy Dzień Gołębia`

@hawkeye116477 twoje tematy ty ptaszki lubisz mocno

**Comment by hawkeye116477** [comment]
`twoje tematy ty ptaszki lubisz mocno`
Ja o tym pisałem, bo wiedziałem, że tutaj jest taki jeden ornitolog zwany @xxcriticxx :smile:.

**Comment by krystian3w** [comment]
Problem wciąż jest, **majkiIT** nie przepisał przekierowania na szybsze:

`.htaccess`
```
Redirect 301 /adblock https://majkiit.github.io/polish-ads-filter/
```

**Comment by xxcriticxx** [comment]
cc @MajkiIT

**Comment by MajkiIT** [comment]
@krystian3w spróbuj w trybie incognito ...

**Comment by krystian3w** [comment]
Jest OK.
