### ISSUE TITLE
dx-team.org

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#15965]
Komunikat o zapisie ciastek 
![Screenshot_1](https://user-images.githubusercontent.com/21177361/77644304-1569fd80-6f61-11ea-8dee-d35a41d24cbd.png)

strona: https://dx-team.org

**Comment by krystian3w** [comment]
Błędna konfiguracja - brak aktywnej listy:

https://github.com/MajkiIT/polish-ads-filter/blob/aaa962432f53854b6d477cbaabd3d598edac7c26/cookies_filters/adblock_cookies.txt#L6

https://github.com/MajkiIT/polish-ads-filter/blob/5d90e3abcff575d868c70a7f432ea44e73174ed3/.github/ISSUE_TEMPLATE/cookies.md#L42

https://github.com/MajkiIT/polish-ads-filter/blob/1a4654c56e5cc3b0a767b59b90689bd025a34bd5/README.md#L33

**Comment by hawkeye116477** [comment]
@xxcriticxx Won't fix, zamykamy :smile:
