### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#15979]
mam taki problem na chromie ze nie wszystkie tagi mi sie laduja 

![Capture](https://user-images.githubusercontent.com/15007183/77913114-b60e3500-7261-11ea-8bdb-aec110475b46.JPG)

**Comment by krystian3w** [comment]
<kbd>Ctrl</kbd>+<kbd>F5</kbd>?

Pewnie nie wyrabia "`shields.io`" lub github błędnie pobiera plik na własną domenę:

`camo.githubusercontent.com`

>
> [![Issues %](https://isitmaintained.com/badge/open/MajkiIT/polish-ads-filter.svg)](https://github.com/MajkiIT/polish-ads-filter/issues)
> [![Issues h](https://isitmaintained.com/badge/resolution/MajkiIT/polish-ads-filter.svg)](https://github.com/MajkiIT/polish-ads-filter/issues)
> [![Issues o](https://img.shields.io/github/issues/MajkiIT/polish-ads-filter.svg?colorB=1caf92)](https://github.com/MajkiIT/polish-ads-filter/issues)
> [![Patronite](https://img.shields.io/website-donate-down-green-red/https/patronite.pl/polskiefiltry.svg?label=Patronite&colorB=1caf92)](https://patronite.pl/polskiefiltry)
> 

Raczej nie ma alternatywnych przycisków co same liczą.

**Comment by xxcriticxx** [comment]
szybciej shield nie wyrabia naciskanie 5 razy refresh pomoga

**Comment by hawkeye116477** [comment]
A ja mam teraz `internal error` i `unresponsive`.

**Comment by hawkeye116477** [comment]
Alternatywy brak, są jedynie takie zabawy `https://github.com/mpyw/hub-purge`.

Tak czy siak, ten problem to mniejsza sprawa, u mnie net rozłącza się często na parę minut co jakieś parę godzin (lub raczej rozłączał, o dziwo dzisiaj na razie ok). Duży ruch jest teraz, to i problemy są, z tym shieldem pewnie podobnie.
