### ISSUE TITLE
tvp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1598]
from your friends at easylist `https://forums.lanik.us/viewtopic.php?f=62&t=34366`

`@@||tvp.pl/*ad`
`||quartic.pl^$third-party`
`tvp.pl###tvpoverlay_abdinfo`

**Comment by MajkiIT** [comment]
@xxcriticxx czyli to wyląduje w Easylist?

**Comment by xxcriticxx** [comment]
tak to podali ale niewiem czy wszystko co tam podaja wyloduje na liscie na wszelki wypadek mozna dodac
