### ISSUE TITLE
Niezablokowane reklamy bielsko.biala.pl

### ISSUE THREAD

**Issue by Eva850** [MajkiIT/polish-ads-filter#1599]
Na stronie głównej i podstronach jest dużo niezablokowanych reklam
![reklamy](https://cloud.githubusercontent.com/assets/20646455/20861867/e3b48b90-b99a-11e6-9e0a-3b1280a778d2.png)
![reklamy2](https://cloud.githubusercontent.com/assets/20646455/20861868/e5b63a06-b99a-11e6-9046-cc05d3adf754.png)

**Comment by F4z** [comment]
Dzięki za zgłoszenie, ta reguła powinna wystarczyć:
`||bielsko.biala.pl/userfiles/banery/$image,object`

**Comment by xxcriticxx** [comment]
dziala testowane!

**Comment by Eva850** [comment]
Potwierdzam, działa. Dziękuję bardzo!
