### ISSUE TITLE
pytanie

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1600]
@F4z coś ci pomóc?

**Comment by xxcriticxx** [comment]
tak ze zmianami do wp please

**Comment by MajkiIT** [comment]
tzn?

**Comment by F4z** [comment]
@MajkiIT dzięki, że się pytasz.
Tak się zastanawiam w jaki sposób robić aktualizacje i zamykać zgłoszenia.
Chciałem to robić w ten sposób, że każde zgłoszenie zamykałbym poprzez `change version to "numer wersji" fix #"numer zgłoszenia"` wyglądałoby to w tak jak w przypadku zamknięcia tego - https://github.com/MajkiIT/polish-ads-filter/issues/549
https://github.com/MajkiIT/polish-ads-filter/commits/master
Zaletą byłoby, że nie zamknąłbym zgłoszenia bez dodania poprawki, a wadą to, że byłoby dużo wersji w momencie kiedy jest dużo zgłoszeń.

Jak z regułami, które obsługuje tylko uBlock?
Na przykład tutaj - https://github.com/MajkiIT/polish-ads-filter/issues/1577#issuecomment-264578574
Podobna reguła jest na ogólnej liście, więc rozumiem, że tę też tam dodać.

**Comment by MajkiIT** [comment]
@F4z a może po prostu poprawić raz plik i w opisie podać listę nr zgłoszeń jakie poprawiasz. 

2 możliwość to wrzucenie pierw tak jak chcesz do gałęzi dev a potem ostatecznej wersji do master.

**Comment by F4z** [comment]
Dobra, będę robił tak jak proponujesz.

**Comment by MajkiIT** [comment]
@F4z jak tego nie czujesz to mów.... nie chcę dyktatury :)

**Comment by F4z** [comment]
Jest w porządku, tak jak podałeś będzie najlepiej 😄

**Comment by F4z** [comment]
@MajkiIT będziesz teraz robił jakąś aktualizację?
Pytam, bo jeśli nie, to pozamykam część zgłoszeń i dodam reguły, a bezsensu żeby dwie osoby naraz to robiły.

**Comment by MajkiIT** [comment]
Dzisiaj będę chciał wrzucić wszystko do filtrów, bo w pon jest najwiecej pobrań.
