### ISSUE TITLE
Reklama na Ratunek

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#16021]
Jutro o 18:45 Polsat włączamy, by pomóc w walce z koronawirusem, pamiętajcie.
https://www.polsatnews.pl/wiadomosc/2020-03-30/reklama-na-ratunek-2-kwietnia-o-1845-wlacz-polsat-i-pomoz-w-walce-z-koronawirusem/

**Comment by xxcriticxx** [comment]
![Capture](https://user-images.githubusercontent.com/15007183/78242621-52c61200-74b0-11ea-92d8-485bc926060f.PNG)

**Comment by krystian3w** [comment]
Pytanie czym liczą kto włączył..., beka jak nikt nie ogląda a jakaś agencja reklamowa szacuje że 3 miliony...

Pewnie tylko dekodery satelitarne i te z kablówki mają furtkę do inwigilacji / anonimowych danych statystycznych.

**Comment by hawkeye116477** [comment]
Akcja zakończona, więc temat zamykam.

**Comment by hawkeye116477** [comment]
@krystian3w 
`https://satkurier.pl/news/190719/3-mln-zl-zebrane-dzieki-akcji-reklamowej-polsatu.html`
Ponad 7 mln widzów oglądało i zebrlai ponad 3 mln złotych.

**Comment by krystian3w** [comment]
Tylko szacunki a nie wyciek "anonimizowanej telemetrii" z Netii / UPC  itd.
