### ISSUE TITLE
pl.ucoin.net

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16030]
pasek o info o adblocku ( na dole )

**Comment by krystian3w** [comment]
y więc zła etykieta?

**Comment by krystian3w** [comment]
Ja paska anti-adblock nie widzę (może uAssets ukryło) ani socialu.

@xxcriticxx  / @hawkeye116477

**Comment by krystian3w** [comment]
Dobra pasek umie wyciąć wywalone: `Adblock Warning Removal`

`ucoin.net###bottom-notice`

**Comment by hawkeye116477** [comment]
Gorhill listę skasował z uBO, to teraz do niego takie atrakcje...

**Comment by krystian3w** [comment]
W sumie ciekawe czy 🐧  usunie też w v`1.0.142` lub będzie okresowo dokleiać w "Nano Defender Integration".

**Comment by krystian3w** [comment]
@olegwukr  czyli nie wycinasz paska anty-adblock?

**Comment by hawkeye116477** [comment]
Raczej sądzę, że prezes zamknął wszystko z tagiem socialem i ciacha jak leci, nie patrzył nawet, że pomyłka. Tak czy siak, to międzynarodowa witryna, więc może jak mówiłem gorhill to weźmie do siebie.
