### ISSUE TITLE
poprostupycha.com.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#16040]
Nie wiem czy to celowo zostało pominięte czy też nie. Jeżeli tak, to wypadałoby coś napisać w tej sprawie. Tak czy siak, przypominam, reklama blendera na `https://poprostupycha.com.pl/przepis/sernik-czekoladowy-obledny/`, czasem bywa też na głównej. Kod rabatowy raczej nikomu się nie przyda, zwłaszcza, że te 100 zł to żadna obniżka, w normalnych sklepach kosztuje tyle samo co w tym sklepie z kodem. Ten sklep nie należy też do właściciela bloga.

**Comment by krystian3w** [comment]
I resztka po reklamie diety pudełkowej:

```
poprostupycha.com.pl###custom_html-4
```

Nawet jak jest tam kucharzem, to bym wyciął...

**Comment by hawkeye116477** [comment]
Tak w zasadzie, to resztka dzisiaj została dodana, tyle, że dyrek zjadł jeden hash (głodny był nie dziś, a parę dni temu) => `https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock.txt#L1772` i reguła nie działa.

**Comment by krystian3w** [comment]
W sumie to można kolejny raz sprawdzić jakie filtry są błędne np `xhr` a ABP wymaga:

```
xmlhttprequest
```

AdGuard chyba już dodał tłumaczenie skrótów uBo, ABP / AdBlock raczej nigdy.

**Comment by MajkiIT** [comment]
@hawkeye116477 Dzięki

**Comment by hawkeye116477** [comment]
@MajkiIT A co z tym blenderem?

**Comment by hawkeye116477** [comment]
@MajkiIT Nadal nie naprawione, a przecież mówiłem, że uciekinier nie wrócił...

A tak w ogóle wracając do pierwszego postu, nie wiem co z tym blenderem w „super promocji".

**Comment by krystian3w** [comment]
klasa css "własna" czyli musisz olać.

**Comment by hawkeye116477** [comment]
Sklep ma swój własny inny blog, tak więc wg mnie nadal kwalifikuje się do usunięcia.

**Comment by hawkeye116477** [comment]
Czyli jednak pominięte, bo ktoś się spieszył. Lepiej się nie śpieszyć, jak brakuje czasu to lepiej zostawić i odłożyć na później, nic nie ucieknie, a nawet gdyby, to będzie mniej roboty :smiley:

Podziękował za miłą współpracę i zamknął...

**Comment by MajkiIT** [comment]
@hawkeye116477 No śpieszyłem się :D przyznaje bez bicia :P
