### ISSUE TITLE
joemonster.org

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#1605]
Reklama:

http://joemonster.org/filmy/poczekalnia

http://imgur.com/zjby9KV

**Comment by xxcriticxx** [comment]
from easylist 

`|blob:$domain=joemonster.org`
`joemonster.org##div[style^="position: fixed; bottom: 0; width: 1020px; height: 100px; background-color: #eee;"]`

**Comment by F4z** [comment]
@xxcriticxx jesteś pewny, że te reguły działają?
Z tego co wiem, to uBlock Origin nie obsługuje czegoś takiego jak `blob`, a jak sprawdzałem z Adblock Plus, to w tym przypadku też nie działało.
Podana reguła kosmetyczna z tego co widzę, to raczej ma za zadanie ukryć komunikat o ciasteczkach, a nie reklamy.

W uBlocku ta reguła powinna działać:
`joemonster.org##script:inject(abort-on-property-write.js, ub_ct_load)`

Wcześniej (https://github.com/MajkiIT/polish-ads-filter/issues/1537) te reguły ukrywały reklamy, ale był moment, że przestały:
`joemonster.org##iframe[mysrc]`
`joemonster.org##a[style="cursor: pointer"][onclick^="window.location.href="][target="_blank"]`

**Comment by xxcriticxx** [comment]
@F4z mi sie zdawalo ze blokowalo reklamy poskakalem po 20 stronach i nic nie bylo po wylonczeniu blob na tych samych stronach byla reklama na srodku

**Comment by F4z** [comment]
@xxcriticxx a możesz sprawdzić jeszcze raz?
U mnie jak dodałem te reguły, to reklamy się wyświetlały.

**Comment by xxcriticxx** [comment]
@F4z podaj linka

**Comment by F4z** [comment]
@xxcriticxx może być i strona główna - `http://joemonster.org/`
Te reklamy nie zawsze się pokazują. Najlepiej odświeżaj stronę i poczekaj kilka sekund i jak się nie pojawi, to jeszcze raz, jak po kilkunastu razach nie wyskoczy, to przejdź do jakiegoś artykułu. Odśwież znowu kilka razy, wróć na stronę główną i znowu odśwież. Tylko ważne żebyś poczekał te kilka sekund, bo te reklamy od razu się nie pojawiają.

Jeszcze pytanie odnośnie przeglądarki. Zazwyczaj korzystam z Chrome i tutaj te reklamy się pojawiają.
Natomiast w Mozilli Firefox bez dodawania żadnych reguł w ogóle ich nie widzę, ale gdyby się pojawiły, to ta reguła powinna je zablokować:
`||unblock.onaudience.com^`

Swoją drogą dziwna sprawa, bo w Chrome nie widać tego połączenia z poziomu przeglądarki.

**Comment by xxcriticxx** [comment]
@F4z jestem na firefox 50 na ubuntu 16.04

**Comment by xxcriticxx** [comment]
@F4z zgadza sie sa dalej rekalamy na firefox z blob filtrem

**Comment by xxcriticxx** [comment]
from easylist please test 

`$websocket,domain=joemonster.org`

**Comment by F4z** [comment]
@xxcriticxx sprawdziłem w Chrome i nie działa, swoją drogą nie widzę w połączeniach niczego związanego z `websocket`.

**Comment by xxcriticxx** [comment]
podaje co mi podaja na easylist 

`joemonster.org##img[src^="data:image"]`

**Comment by F4z** [comment]
@xxcriticxx w ogóle sprawdzałeś reguły, które podałem?
`||unblock.onaudience.com^$third-party`
`joemonster.org##script:inject(abort-on-property-write.js, ub_ct_load)`
`joemonster.org##iframe[mysrc]`
`joemonster.org##a[style="cursor: pointer"][onclick^="window.location.href="][target="_blank"]`

**Comment by xxcriticxx** [comment]
@F4z sorry nie hyba przegapilem

**Comment by F4z** [comment]
@xxcriticxx ta reguła - `joemonster.org##img[src^="data:image"]` nie zawsze wszystko ukrywa.

![image](https://cloud.githubusercontent.com/assets/11742596/20869728/33634116-ba79-11e6-8c37-0420cfb8802e.png)
![image](https://cloud.githubusercontent.com/assets/11742596/20869731/3de5c6c2-ba79-11e6-8215-167d33c65bee.png)

**Comment by xxcriticxx** [comment]
mam to podac na easy?

**Comment by F4z** [comment]
Jak chcesz to możesz.
Po prostu ta reguła nie ukrywa wszystkiego, część reklam jest rzeczywiście ukryta, ale zdarzają się takie, które nadal się pokazują.

**Comment by xxcriticxx** [comment]
F4z moze bys sam wpadl na easylist forum i napisal cos madrego please

**Comment by MajkiIT** [comment]
@F4z a tak nie lepiej ?

joemonster.org###main_billboard

**Comment by F4z** [comment]
@xxcriticxx myślę, że nie ma takiej potrzeby. Wystarczy, że Ty tam zgłaszasz i dzięki Ci za to 👍

@MajkiIT ta reguła ukryje tylko reklamy na stronie głównej (https://github.com/MajkiIT/polish-ads-filter/issues/1363#issuecomment-255208790).
Tutaj nadal będą się wyświetlały - `http://joemonster.org/filmy/poczekalnia`

**Comment by mathew85** [comment]
U mnie z tym filtrem na uBlocku: 

`joemonster.org##script:inject(abort-on-property-write.js, ub_ct_load)`

brak reklam.
