### ISSUE TITLE
finn.no - cannot click on adverts

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#16056]
### Zrzut ekranu 

<details>

![image](https://user-images.githubusercontent.com/8361299/78574607-e2fab300-7832-11ea-8b08-450bae5ab343.png)

</details>

### Link bezpośredni 
`https://www.finn.no/bap/forsale/search.html?q=fujifilm&search_type=SEARCH_ID_BAP_ALL&stored-id=39606587`

### Co trzeba zrobić, aby pojawił się błąd?
1. Go to link
2. Try to click on any advert

Caused by `~facebook.com,~pi.hole##[id^="ads_"]`
This exclusion helps: `finn.no#@#[id^="ads_"]`

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Chrome 80
**Rozszerzenia i skrypty:** 
AdGuard
**Listy filtrów:** 
1. AdGuard Base filter
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 

Original report: https://github.com/AdguardTeam/AdguardFilters/issues/52881

**Comment by MajkiIT** [comment]
@Alex-302 Thanks.
