### ISSUE TITLE
zalukaj.vip

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#16065]
No dobra przyznaje sie zmieniłem zestaw list w ublocku 

https://gist.github.com/gzenio22/aa7a36a16a64fd017a1079d26b3a3262

I po tej operacji mam takiego kwiatuszka na tej stronie 

![Screenshot_1](https://user-images.githubusercontent.com/21177361/78712671-4101c600-7919-11ea-881b-0ec9edd532b1.png)

Dobra widze co powoduje wysypke :P 2 listy KAD przekręty i whitelista

Jesteście w stanie pomoc?

**Comment by krystian3w** [comment]
`||zalukaj*.*^$document,domain=~zalukaj.com,badfilter`

blokada, bo są jakieś 1000 podrób.

Nawet za bardzo stopka nie przekonuje że się dogadali z Netflix / Amazon / Fox / Disney / HBO GO.

**Comment by gzenio22** [comment]
@krystian3w to oczywiste ze stopka to wkręt ale strona działa i nie fejkuje mozna odblokować

**Comment by hawkeye116477** [comment]
@gzenio22 Nieładnie...
Widać trzeba ciebie nawrócić na dobrą drogę, podpowiem, są takie serwisy jak Netflix, Disney+, HBO GO, Amazon Prime, Ipla, Player, Kino WP Pilot :smile:

**Comment by gzenio22** [comment]
paanie po co placic za tyle serwisow zkoro mozna miec wszystko w jednym i to za free :P

**Comment by xMaap** [comment]
@gzenio22 zainstaluj sobie Kodi + wtyczkę  do niego i masz filmy z różnych stron.

**Comment by gzenio22** [comment]
@xMaap Kodi znam i urzywam wespol z Real-debrid tylko nie pisz mi o fanfilm bo ta wtyczka to najgorszy szrot ostatnio

**Comment by xxcriticxx** [comment]
``` 
Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   www.zalukaj.vip
   zalukaj.vip
 Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts:
   www.zalukaj.vip
   zalukaj.vip
```

**Comment by gzenio22** [comment]
Naprawione zamykam :) i dziękuje

**Comment by krystian3w** [comment]
Znowu nie działa, serwery przeciążyli i filmy pousuwali...
