### ISSUE TITLE
lowicz.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1608]
ad block 

`http://zspnr1.lowicz.pl/ezkw/index.php#`

Wykryto oprogramowanie blokujące wyświetlanie reklam!
Dzięki reklamom trenażer egzaminu zawodowego jest dostępny
bez rejestracji, zakładania konta i zupełnie za darmo!

Trenażer nie będzie działał prawidłowo dopóki nie zostanie wyłączone oprogramowanie blokujące reklamy!
Wyłącz oprogramowanie blokujące reklamy i odśwież stronę!

**Comment by MajkiIT** [comment]
@xxcriticxx mozesz sprawdzic?

@@||pagead2.googlesyndication.com/pagead/show_ads.js$script,domain=zspnr1.lowicz.pl

**Comment by xxcriticxx** [comment]
no good dalej ad block
