### ISSUE TITLE
hobbycentrum.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16080]
fb ( na dole )

**Comment by krystian3w** [comment]
Nie widzę, @hawkeye116477 blokujemy kawę włoską 292 polubienia - mimo że nie otwiera to facebooka a inny sklep?

**Comment by hawkeye116477** [comment]
Nie

**Comment by krystian3w** [comment]
@hawkeye116477 co robimy jak uBO używa `$shide` na antyadblocka i lista social nie działa?

Raczej im się nie chce robić aktualizacji `set-constant` raz dziennie.

**Comment by hawkeye116477** [comment]
$shide, to jakaś nowość?

**Comment by krystian3w** [comment]
Tak, to wyłącza specyficzne fility pod TLD lub konkretną domenę.
Jak dorzucą `ghide` to zostają praktycznie sieciowe filtry.

**Comment by hawkeye116477** [comment]
No to nie wiem co zrobić z tym fantem, ale do polskich stron dodali coś takiego?

**Comment by krystian3w** [comment]
tak do pomponika, w efekcie nie da się na Chrome usunąć facebooka / przewijanego "przejdź na główną Interia" bez Nano.

**Comment by hawkeye116477** [comment]
No to może oleg albo pingwin niech wykombinuje inny sposób, a tamto da jako badfilter czy coś. No chyba, że naprawdę inaczej się nie da, to chyba już by musiało tak wtedy zostać...

**Comment by hawkeye116477** [comment]
W każdym bądź razie, my na liście Social nic nie zmieniamy.
