### ISSUE TITLE
Kino ponownie otwarte

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#16096]
Wiem, że są tutaj kinomaniacy - @lukjan32, @gzenio22 i @xxcriticxx, więc mam dla nich dobrą wiadomość - kino znowu jest otwarte i w repertuarze są same wielkie hiciory w rewelacyjnej jakości High Definition, a bilety są w promocyjnej cenie, tylko 12,90 zł + popcorn gratis. Seans rozpocznie się dziś o 20:00.
Więcej informacji [na stronie kina](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://pilot.wp.pl/oferta/54/).

**Comment by xMaap** [comment]
Puszczają reklamy 30 minutowe jak w kinie? Niech zrobią VOD z filmami, ale bez robienia cyrku.
Ten sam film leganie bez wydziwiania
https://player.pl/playerplus/filmy-online/parasite,168221
https://www.cineman.pl/vods/vod.2148
https://vod.pl/filmy/parasite-caly-film-online/5v37198

**Comment by xxcriticxx** [comment]
@hawkeye116477 ja mam geo lock :(
