### ISSUE TITLE
zyczenia wielkanocne

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#16106]
Smacznej szynki i jajeczka W ten świąteczny ranek, a w koszyczku wielkanocnym samych niespodzianek.

**Comment by hawkeye116477** [comment]
<img src="https://media.giphy.com/media/y5xRFqfdkgEXS/giphy.gif">

Życzę wam, by na tę Wielkanoc robotę w kuchni odwalił za was zając, baranek potem posprzątał stoły, a żeby wam zostały tylko… obżarstwo i pierdoły!

**Comment by xxcriticxx** [comment]
![IMG_7616](https://user-images.githubusercontent.com/15007183/79043886-0e352780-7bd0-11ea-85c8-08d1696dc017.jpg)

**Comment by blocker999** [comment]
![wielkanoc](https://user-images.githubusercontent.com/23176832/79064994-9b9a7980-7cad-11ea-9ea4-3542ceba778f.jpg)

**Comment by seba2282** [comment]
Zdrowych, Szczęśliwych Świąt Wielkanocnych

**Comment by MajkiIT** [comment]
Wszystkiego dobrego dla Was, Zdrowych i spokojnych Świąt.

**Comment by xxcriticxx** [comment]
Happy Śmigus Dyngus!
