### ISSUE TITLE
reklama.ringieraxelspringer.pl (kontynuacja)

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#16105]
Niestety sprawa #16081 nie jest jeszcze zakończona, czcionki i skrypty są zablokowane, przez co część elementów nie działa/wygląda prawidłowo. Wyjątek powinien wyglądać podobnie jak reguła blokująca, czyli `@@/reklama.$~stylesheet,domain=reklama.ringieraxelspringer.pl`.

**Comment by MajkiIT** [comment]
@hawkeye116477 Dzięki masz rację.
