### ISSUE TITLE
pekao.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16115]

**Comment by krystian3w** [comment]
Animacja z figurami to loader.

**Comment by krystian3w** [comment]
@hawkeye116477 lepiej do filtrów własnych?

```
pekao.com.pl##.loader:before
```

**Comment by hawkeye116477** [comment]
Tak

**Comment by hawkeye116477** [comment]
@krystian3w Już część tego typu elementów dodawałeś przecież do EI.

**Comment by krystian3w** [comment]
No ale to bank, może też tym walą przy przelewie...

**Comment by hawkeye116477** [comment]
Jak uważasz, wg mnie bez loadera trochę łyso to wygląda...

**Comment by krystian3w** [comment]
Mnie się dosyć szybko ładuje, raczej nie ma efektu że strona się buduje z rozjechanego układu do "ułożonego".

**Comment by krystian3w** [comment]
Na pocieszenie panele dla firm i klientów mają normalnie osobną domenę.

**Comment by hawkeye116477** [comment]
@krystian3w A ja tam nadal widzę ten loader nawet z tą regułą, chyba tylko wyeliminowałeś blur.
