### ISSUE TITLE
motofilm.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16129]
![Screenshot_2020-04-20 motofilm pl](https://user-images.githubusercontent.com/36385327/79728056-9c568f80-82ed-11ea-8698-f2eb451959dc.png)
![Screenshot_2020-04-20 motofilm pl(1)](https://user-images.githubusercontent.com/36385327/79728060-9d87bc80-82ed-11ea-9654-12f21930e6e5.png)
![Screenshot_2020-04-20 motofilm pl(2)](https://user-images.githubusercontent.com/36385327/79728061-9e205300-82ed-11ea-96bd-d6b495dceb10.png)

**Comment by MajkiIT** [comment]
```
motofilm.pl##.widget_custom_html.custom_html-9.widget.widget_text
motofilm.pl##.archive-col-2.archive-col > .widget_custom_html.widget.widget_text
motofilm.pl##section.widget_custom_html.widget.widget_text > .widget-wrap.widget_text
```

**Comment by krystian3w** [comment]
Pierwsze można uciąć na 99% do:

`motofilm.pl##.custom_html-9`
