### ISSUE TITLE
Youtube,problem z ładowaniem filmów

### ISSUE THREAD

**Issue by deejayscream81** [MajkiIT/polish-ads-filter#16123]
Od ponad 2 tyg po ostatniej aktualizacji Safari do wersji 13.1 i moim zestawie filtrów Adguard,filmy nie ładują się od razu,należy zrobić refresh,dopiero wtedy film się ładuje.Sprawę poruszyłem na forum Adguarda,ale nie wiedzą gdzie leży problem.Wyłączenie Adguarda powoduje że problem znika,więc może któryś z filtrów,których używam to powoduje?

Wersja Adguard 2.3.2.710
Przeglądarka Safari 13.1 Mac OS
Brak rozszerzeń i skryptów
Lista użytych filtrów (wszystkie up to date 18 kwietnia):

-Polish Privacy Filters
-Podstawowy filtr Adguard
-Filtr elementów szpiegujących Adguard
-Filtr mediów społecznościowych
-Obsolete Anti-Adblock Killer Reek
-Official Polish filters for Adblock,ublock Origin and Adguard
-Polskie filtry ciasteczkowe
-Polish Anti Adblock Filters
-Alleblock

**Comment by xxcriticxx** [comment]
@deejayscream81 filtry reeka  wylacz/usun

**Comment by xxcriticxx** [comment]
@deejayscream81 zacznij pomału wylaczac listy w adguardzie az znajdziesz ta co psuje yt

zobacz czy to nie podobne #15632

**Comment by deejayscream81** [comment]
Znalazłem ten post również #15632,wygląda bardzo podobnie (poodbny komunikat o błędzie),ale to pod IOS. 
Pozostaje mi testować filtr po filtrze.

**Comment by xxcriticxx** [comment]
czysciles browsing history w przegladarce?

**Comment by deejayscream81** [comment]
> czysciles browsing history w przegladarce?

Nie zakładałbym wątku tutaj nie czyszcząc wcześniej historii przeglądania,cookies etc etc...
Na razie wygląda na to,że filtr Anti-Adblock Killer Reek powodował jakiś problem,może się z innym filtrem gryzło.

**Comment by krystian3w** [comment]
To już nie aktywuj Reek - w AG jest z braku alternatywy i nawet nie chcą wygasić (jedynie raz testowo aktywowali jakąś chińską listę, która umiała psuć Facebooka).

**Comment by xMaap** [comment]
@deejayscream81 Reek od lat nie jest aktualizowany.
Zobacz filtry https://majkiit.github.io/polish-ads-filter/ tylko pacz się które są do AdGuard.

**Comment by deejayscream81** [comment]
Na razie działa jakoś.Reek usunięty,ale nie chcę usuwać więcej,bo powróci problem z reklamą AD-questo na jednej z innych stron,z którą walczyłem dotąd.
Wszystkie filtry które mam działają pod Adguard,aktualizują się.

**Comment by xxcriticxx** [comment]
option 1
nie ma forka pingwina na safari?

option 2
bogachenko list zamiast reeka

option 3
yt premium z Indii

**Comment by krystian3w** [comment]
A potem Boollywood w proponowanych i ciekawe kiedy bank doliczy przewalutowanie z Rupii lub Peso (jak się nie ma darmowych takich transakcji)/

**Comment by xxcriticxx** [comment]
coś za coś @krystian3w

**Comment by xMaap** [comment]
@xxcriticxx chyba można zamknąć.
