### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by Gunderyk** [MajkiIT/polish-ads-filter#1612]
`http://www.dobreprogramy.pl/Google-Chrome,Program,Windows,13096.html `

W Chrome na dp (w Firefox jest ok.) muszę dodać tan filtr: www.dobreprogramy.pl###slide-menu > .target.center.page-element  ponieważ  od góry jest puste pole z napisami reklama. Można prosić o korektę w filtrach? :)

**Comment by FadeMind** [comment]
@xxcriticxx @MajkiIT 
Zablokujcie proszę także odnośnik do instalatora avasta na każdej stronie pobierania (także na stronach z instalkami innych programów AV) na `dobreprogramy.pl`
![image 003](https://cloud.githubusercontent.com/assets/9846948/20867030/7b7985f2-ba3b-11e6-859c-bffbaf084bcc.png)

```
www.dobreprogramy.pl###phContent_avastBadge
```

**Comment by MajkiIT** [comment]
@Gunderyk Ok sprawdzimy u siebie. Dzięki 
@FadeMind zaraz dodam

**Comment by FadeMind** [comment]
@MajkiIT  dodaj proszę drobiazg do `dobreprogramy.pl`

```
www.dobreprogramy.pl##.no-filter
```

Reguła usuwa puste miejsca na liście programów:
http://www.dobreprogramy.pl/NoweProgramy,Windows.html

![image 004](https://cloud.githubusercontent.com/assets/9846948/20928136/af0dd6d6-bbc4-11e6-9037-828ea486d73b.png)
<hr/>

![image 005](https://cloud.githubusercontent.com/assets/9846948/20928163/c8bdd37e-bbc4-11e6-92f0-84d8d5f0e523.png)

**Comment by MajkiIT** [comment]
@FadeMind Dzięki dodamy

**Comment by MajkiIT** [comment]
@FadeMind dorzucone.
