### ISSUE TITLE
pl pihole + dark theme

### ISSUE THREAD

**Issue by Janasek** [MajkiIT/polish-ads-filter#16121]
Trochę sie pobawiłem kilka rozwiązań wyszukałem / są za i przeciw ,ale ogólnie podoba mi się Pi-Hole
małe usparawnienie , może potrzebne może nie , 
Nie pełne tłumaczenie to bardziej experymemt ale może do rozwinięcia?

https://github.com/Janasek/pi-hole-darkstylevpl/blob/master/README.md

**Comment by gargul2** [comment]
Duplikat, już jest wątek od tego https://github.com/MajkiIT/polish-ads-filter/issues/6404 , po co zakładać kolejny i robić śmietnik...

**Comment by Janasek** [comment]
pihole list pl edition #6404, co to ma wsólnego z tym co jest w tym tzw. "off topic"?
polskie filtry to nie to samo co polski interfejs.....
chyba że czegoś się nie dopatrzyłem

**Comment by gargul2** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/6404 to wątek zbiorczy o Pi-Hole zdaje się, po co 2 wątki o Pi-Hole...zaraz ktoś przyjdzie i założy 3-ci itd...

**Comment by Janasek** [comment]
spoko ,

**Comment by xxcriticxx** [comment]
@Janasek nie daj sie strollować

**Comment by Janasek** [comment]
To już nie ma miejsca w necie gdzie by jakiś **pokemon** nie wtrącił swoich trzech jak że pouczających zdań, 

Nic, chcecie pomóć ,to do dzieła ,tak czy siak na spokojnie pociągne to co dam radę w czasie nie określonym, zepsuć niczego nie zepsuje zawsze można wycofać zmiany.

**Comment by gargul2** [comment]
> xxcriticxx : @Janasek nie daj sie strollować

xxcriticxx - dobry żart i teoria spiskowa, ale nie troluj już, bo w trolowaniu to ty jesteś tutaj mistrzem...ja nikogo tu nie troluję, zwyczajnie wyraziłem spokojnie opinię, że nie ma po co zakładać 2-go wątku, skoro już 1 mamy, i tyle...ale ty robisz z tego jakiś problem i teorie spiskowe, żę ja tu kogoś troluję, ty to zawsze masz jakiś ból dupy o nie wiadomo co, jakaś maść albo coś...

> Janasek : To już nie ma miejsca w necie gdzie by jakiś **pokemon** nie wtrącił swoich trzech jak że pouczających zdań,

To już nie ma miejsca w necie gdzie by jakiś **pokemon** nie dupilkował wątków i nie zaśmiecał...a gdy zwyczajnie zwrócić takiemu uwagę, że już 1 wątek mamy, to wielce oburzony i rzuca mięsem. Poza tym "pokemon" to ty masz na imię, nie rzucaj w moją stronę mięsem bo ja w twoją nie rzucam i sobie wypraszam takie wycieczki osobiste, w ogóle to zwyczajne chamstwo i słoma z sandałów wystaje...

Dalsze bezpodstawne trolowanie i rzucanie mięsem w moją stronę przez obydwu osobników będę raportował do administacji github, bo zwyczajnie nie chcę dać się wciągnąć w kolejną prowokację z ich strony, poziom i wypowiedzi to dno i metr mułu...

**Comment by gargul2** [comment]
> xxcriticxx : @Janasek nie daj sie strollować

Nie troluj już i nie podpuszczaj Janaska na mnie ani nie kasuj moich komentarzy, co do Janaska to ja tylko na spokojnie wyraziłem opinię, że po co 2-gi wątek skoro już 1 jest, ale ty zawsze masz jakiś ból dupy...

> janasek : To już nie ma miejsca w necie gdzie by jakiś **pokemon** nie wtrącił swoich trzech jak że pouczających zdań

To już nie ma miejsca w necie gdzie by jakiś **pokemon** nie duplikował wątków i zaśmiecał...a jak na spokojnie uwagę zwrócić to już wiele obrażony i  ból dupy...jak ci ulży to możesz sobie założyć 10 wątków o Pi-Hole...

Na ból dupy polecam panom maść.

**Comment by krystian3w** [comment]
https://github.com/lkd70/PiHole-Dark

Z tymi jest wada, bo niektórzy mają domenę przy pomocy HOSTS lub IP i nie można tego przewidzieć:
https://userstyles.org/styles/167398/pi-hole-theme
https://userstyles.org/styles/175110/pihole-dark-theme
https://userstyles.org/styles/166339/pi-hole-dark-theme
https://userstyles.org/styles/136389/pi-hole-dark

**Comment by Janasek** [comment]
większość ukończona ,zostały poprawki...
zamiana plików dla **Docker**  w LibreELEC 

Lokalizacja:
**/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/Docker_Container/diff/var/**

**Comment by xxcriticxx** [comment]
@Janasek na androidzie z libreelec to odpalasz?

**Comment by Janasek** [comment]
nie , coreelec mam na Amlogic dual boot ,to jest Libreelec generic na starej płycie od laptopa 
DUŻE RPI4

**Comment by xxcriticxx** [comment]
@Janasek mam starego androida gdziesc minix x8 jest na to jakis os linyxowy?

**Comment by Janasek** [comment]
obadaj to z karty bo do zamiast androida to raczej nie ....
https://forum.libreelec.tv/thread/12155-libreelec-9-0-kodi-18-x-for-minix-x8-x8h-x8h/

później instalujesz server.linux.io + Docker i przez shh jedną komendą instalujesz Pi-Hole...

Pewnie jeszcze coś wyciśniesz z niego 

https://forum.freaktab.com/forum/tv-player-support/amlogic-based-tv-players/s802/minix/firmware-roms-tools-ab/751661-linux-multi-boot-on-minix-neo-x8-h-plus

**Comment by xxcriticxx** [comment]
Ja mam wersie bez plusa

**Comment by Janasek** [comment]
Nie mam pojęcia musisz poszukać ,ja nie miałem takiej wersji ani zadnego minixa więc nie będę cie wprowadzał w błąd i pisał ten czy tamten , wszystko staryje z kardy sd więc możesz smiało sprawdza po kolei co ci podejdzie, jak tylko pod pi-hole czy np server dla pvr-next czy tvheadend to libreelec ci skropi nie wiem jakie prędkości zapisu odvzytu list osiągnie ale sprawdzić możesz...

**Comment by xxcriticxx** [comment]
kartę gdzież muszę tylko wykopać
