### ISSUE TITLE
kosmetykaaut.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16126]
Reklamy na głównej i na forum (przykładowy wątek na forum - https://kosmetykaaut.pl/topic/1692-czym-doczy%C5%9Bci%C4%87-z%C5%BC%C3%B3%C5%82k%C5%82y-plastik/):

### **Reklama u góry:** 
![1](https://user-images.githubusercontent.com/63287518/79690723-340b9d80-825c-11ea-9718-b32c38a5384c.gif)

### **Reklama na środku:**
![2](https://user-images.githubusercontent.com/63287518/79690725-35d56100-825c-11ea-8644-efdf50b7e74c.gif)

### **Reklama u dołu:**
![3](https://user-images.githubusercontent.com/63287518/79690726-366df780-825c-11ea-9e5a-5e2decaa3cc3.gif)

**Comment by MajkiIT** [comment]
`kosmetykaaut.pl##.ipsAreaBackground_light.ipsResponsive_inlineBlock.ipsResponsive_showDesktop > A > IMG`
