### ISSUE TITLE
main page wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1615]
box po reklamach

**Comment by MajkiIT** [comment]
www.wp.pl##._1tyMO

**Comment by MajkiIT** [comment]
@xxcriticxx 

www.wp.pl##._2Gdr9

**Comment by F4z** [comment]
@MajkiIT te dwie reguły, które podałeś działają u mnie.

**Comment by MajkiIT** [comment]
@F4z dzięki. Dodam na końcu odpowiednią sekcję aby nie mieszało się z główną listą i wrzucę te 2 reguły.

**Comment by F4z** [comment]
Na `facet.wp.pl` i `teleshow.wp.pl` znowu są reklamy.
Eksperymentalne reguły:
`facet.wp.pl,teleshow.wp.pl##div[class^="_"]:matches-css(background-image: /^url\(.*wp\.pl/)`
`facet.wp.pl,teleshow.wp.pl##script:inject(abort-on-property-write.js, iaqExt)`
`/^(http|https):\/\/[a-z]{1,20}\.wp\.pl\/.{200,}/$script,important`
Ta trzecia reguła może za dużo blokować.
Jeśli nadal będą reklamy albo te reguły będą za dużo blokować, to proszę pisać.
Jak ktoś znajdzie lepsze rozwiązanie, to też byłoby miło jakby napisał :)

**Comment by MajkiIT** [comment]
@F4z mi wydaje się ok. Czy możemy zrobić tak?

facet.wp.pl,teleshow.wp.pl##div[class^="_"]:matches-css(background-image: /^url\(.*wp\.pl/)
facet.wp.pl,teleshow.wp.pl##script:inject(abort-on-property-write.js, iaqExt)
/^(http|https):\/\/[a-z]{1,20}\.wp\.pl\/.{200,}/$script,important,domain=facet.wp.pl|teleshow.wp.pl

**Comment by F4z** [comment]
@MajkiIT jeszcze może być coś takiego:
`/^(http|https):\/\/(facet|teleshow)\.wp\.pl\/.{200,}/$script,important`

Swoją drogą chyba źle dodałeś tę regułę - `facet.wp.pl,teleshow.wp.pl##div[class^="_"]:matches-css(background-image: /^url\(.*wp\.pl/)`
W regule dodanej do listy brakuje `\` pomiędzy `url` a `(` i reguła nie działa, ta wyżej jest poprawna.

Tak samo ta reguła - `/^(http|https)://[a-z]{1,20}.wp.pl/.{200,}/$script,important,domain=facet.wp.pl|teleshow.wp.pl`
ona działa, ale brakuje kilku `\`, w zasadzie rozszerzenia do blokowania reklam powinny sobie z tym poradzić, ale przed kropką, ukośnik powinien być, bo jak nie ma, to traktowane jest jako dowolny znak.
Dlatego w przypadku tej reguły wolałbym żeby to wyglądało tak:
`/^(http|https):\/\/[a-z]{1,20}\.wp\.pl\/.{200,}/$script,important,domain=facet.wp.pl|teleshow.wp.pl`


> Dodatkowo widziałeś, że się adres zmienił ?
`https://e18sohhclse.wp.pl/Uk0vQm94L2MvYi9wcmViaWQ=/publishertag.js`
a my mamy regułę
`@@/:\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(.{0,15}[&!*;@\$)[\]:%].*|(?!cap|vad|display)[a-zA-Z0-9\W_]{1,10})\.(js|html|xml|jpg|gif|png)/`
która może być nieaktualna

Widziałem to, ale to raczej może być związane ze znikającymi filmami.
Pod tym adresem znajduje się prawie identyczny skrypt, co tutaj - `https://static.criteo.net/js/ld/publishertag.js`

**Comment by F4z** [comment]
Poprawiłem te dwie reguły.

**Comment by MajkiIT** [comment]
@F4z dzięki za poprawkę.
