### ISSUE TITLE
adblock on wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1616]
`http://opinie.wp.pl/pis-szuka-hakow-na-opozycje-jakub-majmurek-dobra-zmiana-dokreca-srube-6065935113331329a`

`http://kobieta.wp.pl/gwalt-aborcja-eutanazja-o-czym-minister-edukacji-anna-zalewska-z-dziecmi-rozmawia-6065928562029697a`

`http://facet.wp.pl/krzysztof-skiba-trzeba-przywrocic-polsce-normalnosc-6066034742116993a`

**Comment by xxcriticxx** [comment]
a na reszcie?

**Comment by F4z** [comment]
U mnie wykrywa adblocka.
@xxcriticxx możesz sprawdzić te reguły?
`@@||wp.hit.gemius.pl/xgemius.js$script,domain=wp.pl`
`@@||static.criteo.net/js/ld/publishertag.js$script,domain=wp.pl`

@MajkiIT nie wiem jak u Ciebie, ale u mnie ta reguła - `||fntajkb.wp.pl/$script,important,domain=sportowefakty.wp.pl`
z tej aktualizacji - https://github.com/MajkiIT/polish-ads-filter/commit/5c76c50281f346451bc12919856981371cfec7be#diff-711027ed0794992ae3b8710d874f3df7R1411
powoduje, że wykrywany jest adblock przy odtwarzaniu filmu, na przykład tutaj - `http://sportowefakty.wp.pl/pilka-nozna/650979/lukasz-teodorczyk-moze-pobic-transferowy-rekord`

Skoro i tak ta reguła działa tylko w uBlocku, to może zastąpić ją taką?
`money.pl,o2.pl,wp.pl,wp.tv##script:inject(abort-on-property-write.js, gafBodies)`
Można jeszcze dodać inne strony należące do wp, ale w tej chwili nie chce mi się szukać.

Tutaj też wykrywa adblocka - `http://wp.tv/i,smierc-pod-palmami,mid,1994090,cid,2303709,klip.html?ticaid=618378`
Ta reguła u mnie pomogła:
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=wp.tv`

**Comment by xxcriticxx** [comment]
@F4z stymi dwoma wszystko dziala tylko kilka razy miga ja film sie zacznie

**Comment by xxcriticxx** [comment]
na wp.tv mam BRAK KLIPU ale to moze ze poza krajem jestem 

![capture](https://cloud.githubusercontent.com/assets/15007183/20947045/5cc1bb38-bbdb-11e6-9c0b-785aa71c4be3.PNG)

**Comment by F4z** [comment]
Powiązane zgłoszenia: https://github.com/MajkiIT/polish-ads-filter/issues/1590 https://github.com/MajkiIT/polish-ads-filter/issues/1578 https://github.com/MajkiIT/polish-ads-filter/issues/1574  https://github.com/MajkiIT/polish-ads-filter/issues/1524
@MajkiIT możesz sprawdzić jak to u Ciebie wygląda i dodać odpowiednie reguły?

Zebrane reguły:
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=mybank.pl|gadzetomania.pl|komorkomania.pl|money.pl|portal.abczdrowie.pl|pudelek.tv|wp.pl|wp.tv`
`@@||wp.hit.gemius.pl/xgemius.js$script,domain=wp.pl`
`@@||static.criteo.net/js/ld/publishertag.js$script,domain=wp.pl`
