### ISSUE TITLE
onet.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16172]
https://github.com/easylist/easylist/issues/5117 dodać uszkodzone domeny (także tą z uBO) do: https://github.com/MajkiIT/polish-ads-filter/blob/4999220bb8c2e1593454caf06147acc88e5d9e74/polish-adblock-filters/adblock.txt#L4003 bo jak będziemy czekać aż w EasyPrivacy dodadzą to możemy się nie doczekać,  a w ogóle to ten filtr chyba powinien znajdować się w Polish Privacy Filters.

**Comment by krystian3w** [comment]
Jak `polish privacy` trafi jako domyślne regionalne filtry prywatności - to będzie a tak to rzeźbienie tam dla sztuki.

**Comment by gargul2** [comment]
A no tak, zapomniałem że nie jest domyślne.

**Comment by krystian3w** [comment]
`vod.pl` jeszcze by się przydało tam dodać jak dla mnie.

**Comment by gargul2** [comment]
W takim razie niepotrzebne już w uAssets, więc zgłosiłem i usunięte: https://github.com/uBlockOrigin/uAssets/commit/cb591710408434be6558afe5525c26d98fd73677

**Comment by krystian3w** [comment]
`ghide` możesz posprawdzać, `ublock-user` mimo komentarza że dodane, to nie usuwa w uAssets.
