### ISSUE TITLE
GROUP rynekinfrastruktury.pl

### ISSUE THREAD

**Issue by mazo20** [MajkiIT/polish-ads-filter#16197]
<img width="1680" alt="Screenshot 2020-04-24 at 17 11 33" src="https://user-images.githubusercontent.com/7370986/80227924-a7dbea80-864e-11ea-9570-1122bd07cdea.png">

https://www.rynekinfrastruktury.pl
https://www.transport-publiczny.pl
https://www.rynek-lotniczy.pl
http://www.rynek-kolejowy.pl

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
1. Pojawia się automatycznie po włączeniu strony

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Safari 13.1

**Rozszerzenia i skrypty:** 
[Wipr](https://apps.apple.com/it/app/wipr/id1320666476?l=en&mt=12)

**Listy filtrów:** 
1. polish-ads-filter
2. [inne](https://giorgiocalderolla.com/wipr-acknowledgements.html) ale raczej nie istotne 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Skrypt który to aktywuje - https://www.rynekinfrastruktury.pl/js/_GpTqHSvMVLmCusQXz.js
Nigdy się tym nie bawiłem ale bardzo chętnie się dowiem jak to blokować na przyszłość

**Comment by krystian3w** [comment]
Chyba nie da się dla `Wipr`...

z uBO nie umiem odtworzyć, nie widzę by ktoś naprawiał w uAssets lub `Polish anti-adblock filters`.

AdGuard załatało CSS-em: https://github.com/AdguardTeam/AdguardFilters/issues/54282#issuecomment-618927721

**Comment by krystian3w** [comment]
@xxcriticxx tu trzeba zmienić etykiety by Oleg nie musiał przeglądać wszystkich zgłoszeń reklamowych.

**Comment by xxcriticxx** [comment]
@hawkeye116477 please dodaj template na adblock bo brakuje

**Comment by hawkeye116477** [comment]
@mazo20 Może pora wypróbować jakąś lepszą przeglądarkę do której można doinstalować prawdziwego uBO, jak np. https://www.microsoft.com/pl-pl/edge, ewentualnie nadal używaj Safari i do tego https://adguard.com/pl/adguard-mac/overview.html :smile:

**Comment by krystian3w** [comment]
Adguard w Safarii ssie jak Content Blocker na iOS / Yandex / Samsung Internet.

Jak Wipr kosztował raz 4 dolary to już AdGuard na macOS 2.3.2 pewnie więcej z wieczystą licencją.

**Comment by hawkeye116477** [comment]
`Adguard w Safari ssie jak Content Blocker na iOS / Yandex / Samsung Internet.`

@krystian3w Ale ja nic nie proponowałem AdGuarda dla Safari, podałem linka do tego systemowego :stuck_out_tongue: .

**Comment by krystian3w** [comment]
Systemowy jest pewnie droższy od Wipr.

**Comment by hawkeye116477** [comment]
@krystian3w 

`Systemowy jest pewnie droższy od Wipr.`

`https://imagazine.pl/2019/10/04/safari-13-0-niestety-uniemozliwia-korzystania-z-ublock-origin-oto-kilka-alternatyw/` 


@krystian3w Apple to prestiż, trzeba płacić... Tam nawet ponoć w sklepie iOS bywają rzeczy płatne, które w Androidzie są za darmo.
