### ISSUE TITLE
wideo.wp.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16191]
Mocno uszkodzona strona: https://github.com/MajkiIT/polish-ads-filter/issues/13818#issuecomment-610269671

W celu naprawy należy dodać `~wideo.wp.pl` do:

### 1)
https://github.com/olegwukr/polish-privacy-filters/blob/8ebe634b537f3cc1ba6124f6fa99823c045f806f/anti-adblock-suplement.txt#L101

Oraz do:

### 2)
https://github.com/MajkiIT/polish-ads-filter/blob/150ee63e3104244579be0ca7fbd8edc008f0d580/polish-adblock-filters/adblock.txt#L4358

Gdy zostanie to naprawione w polskich listach, to wtedy zgłoszę do usunięcia z: uBlockOrigin/uAssets/issues/7265

**Comment by MajkiIT** [comment]
Odpowiednio 
https://github.com/olegwukr/polish-privacy-filters/commit/21f01550ff2dad91488da1523d35ed003701c512#diff-bde4d2ca165ca262b121296ccf4d1bc8


https://github.com/MajkiIT/polish-ads-filter/commit/3c4b244828022973c4bb7f10c137bbef362a99f0#diff-711027ed0794992ae3b8710d874f3df7

**Comment by gargul2** [comment]
No i gitara, działa, a tam zgłoszone do usunięcia: https://github.com/uBlockOrigin/uAssets/issues/7265#issuecomment-619326599
