### ISSUE TITLE
Sensancja na GitHubie

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#16194]
Patrzcie co się stało, Microsoft zablokował repo EnergizedProtection.

<img src="https://hub.filterlists.com/uploads/default/original/1X/f075fd447f6cc4b2ebe356e439a7163db3187acd.png">

`https://hub.filterlists.com/t/energized-protection-github-repo-is-down/80`

Kolejny może być @MajkiIT jeśli tak będzie często commitował, a wystarczyłoby może z 1-4 razy dziennie :stuck_out_tongue:

**Comment by krystian3w** [comment]
Ciekawe czy `uAssets` i `AdGuard Filters` (/ Filters Registry) odporne na taki ban.

**Comment by MajkiIT** [comment]
@hawkeye116477 Nie będę bo tutaj chodzi o rozmiar repo a nie ilość commitów. 

Ponadto jakieś zmiany w planach zrobili ==> https://help.github.com/en/github/getting-started-with-github/faq-about-changes-to-githubs-plans

**Comment by xxcriticxx** [comment]
wow

**Comment by hawkeye116477** [comment]
No tak w zasadzie to ilość commitów jest trochę powiązana z rozmiarem repozytorium. Każda zmiana jest zapisywana w historii, tak więc im więcej commitów, tym rozmiar repozytorium jest większy.

**Comment by gargul2** [comment]
Np. [tu](https://www.youtube.com/watch?v=AiWYIRqMCzk).

**Comment by gargul2** [comment]
[Wszyscy tańczą](https://www.youtube.com/watch?v=F1d41395fVY)

**Comment by gargul2** [comment]
hawkeye116477 ma rację, bo już odblokowane, ale zostało wykastrowane z historii commitów: 
https://github.com/EnergizedProtection/block/issues/423
https://github.com/EnergizedProtection/block/commits/master

**Comment by hawkeye116477** [comment]
A @MajkiIT już zajął łącznie 3,63 GB.

**Comment by xxcriticxx** [comment]
@hawkeye116477 lol

**Comment by hawkeye116477** [comment]
Automat powinien rzadziej commitować, może 1-2 razy dziennie by wystarczyło, w końcu nikt raczej co 15 minut aktualizacji nie ściąga.

**Comment by xxcriticxx** [comment]
dawno @MajkiIT o tym pisalem. moj znadniem raz na tydzien by wystarczylo.

**Comment by MajkiIT** [comment]
@hawkeye116477 chodzi ci o te commity ?
https://github.com/MajkiIT/polish-ads-filter/commits/master/polish-mikrotik-filters

@xxcriticxx Wszystko mam raz w tygodniu wydawać ?

**Comment by krystian3w** [comment]
jak pod te porwania to lepiej raz na dzień jak wysyłają to botnetami na FB z kont 13 latków.

**Comment by hawkeye116477** [comment]
@MajkiIT Nie tylko te, również dla pi-hole, generalnie https://github.com/MajkiIT/polish-ads-filter/commits?author=MajkiIT-automat.

**Comment by MajkiIT** [comment]
@hawkeye116477 Jak to taki problem to zmienię aby wysyłki na Github były rzadziej, ale pliki i tak będą generowane w tym samym tempie. A z tego co kojarzę to pliki są pobierane co 1 h przez niektórych.

**Comment by krystian3w** [comment]
zważono repo tamto czy rozmiar tylko dla osób co zarchiwizowały przed banem?

**Comment by hawkeye116477** [comment]
@krystian3w Niby gość napisał, że ważyło wcześniej ponad 6 GB.

**Comment by krystian3w** [comment]
a on musiał czyścić czy przyszedł mail że MS zaczął czyszczenie i repo wróci za dwa dni bez commitów?

**Comment by hawkeye116477** [comment]
`We had to squash our whole history`

Tak więc, rozumiem, że on to musiał zrobić.

**Comment by xxcriticxx** [comment]
@MajkiIT nie tylko hostfiles raz na tydzien reszta jest ok (wszystko co z automatu raz na tydzien)

**Comment by xxcriticxx** [comment]
@krystian3w ja mam 12.5 wiosen :)

**Comment by MajkiIT** [comment]
@hawkeye116477 
Trochę MS pozmieniałem. Obecnie limit to 100GB per repo. Przy 75GB dostajesz alert. 
https://stackoverflow.com/questions/38768454/repository-size-limits-for-github-com

**Comment by hawkeye116477** [comment]
Tyle, że zmiana niby jest od kwietnia, a on w kwietniu dostał blokadę, tak więc coś tu się nie zgadza.

**Comment by krystian3w** [comment]
ponad 6 czyli nie wie i MS mu nie zważył...

**Comment by hawkeye116477** [comment]
Sam mógł to zrobić za pomocą https://github.com/github/git-sizer.

Tak czy siak @MajkiIT, optymalnie zalecane jest 1 GB i ja bym dla bezpieczeństwa ograniczył commitowanie automatu do 1-2 razy dziennie. Raczej też niewielu jest takich wariatów co pobiera co godzinę :smiley:

**Comment by hawkeye116477** [comment]
@krystian3w Co nie odpisujesz na czacie teamu?
