### ISSUE TITLE
pepper.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#16198]
Jakiś łobuziak zablokował linki do AliExpress, np. `https://www.pepper.pl/promocje/ugreen-micro-usb-cable-3a-243010`.

**Comment by krystian3w** [comment]
Bo "pop-upy" na stronach z horrorami...

**Comment by hawkeye116477** [comment]
@MajkiIT Nadal jest blokada, jeszcze `||click.aliexpress.com^` do zwhitelistowania.

**Comment by hawkeye116477** [comment]
@MajkiIT Nie wyszło. Powinno być chyba raczej tak => `||click.aliexpress.com^$domain=~aliexpress.com` albo `||click.aliexpress.com^$third-party`.

**Comment by krystian3w** [comment]
Trzeba wywalić filtr lub zrobić inceptcję z `s.click.aliexpress.com` (bo nagle robią subdomenę 2 poziomu - pewnie dla ominięcia blokad **HOSTS** / **DNS** ale tej w uBO tak się nie da...).

**Comment by MajkiIT** [comment]
Ale na tej stronie nie ma takiego elementu. Nie widzę w blokowanych tego.

**Comment by hawkeye116477** [comment]
@MajkiIT Po kliknięciu idź do okazji jest przekierowanie na AliExpress.

**Comment by krystian3w** [comment]
`pepper -> click -> s.click -> ...` mniej więcej tak wskakuje.

W historii edycji były inne rozwiązania z `thrid-party` lub wykluczeniem by filtr był aktywny w całym ali
