### ISSUE TITLE
pytanie

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1620]
@F4z @xxcriticxx 

Co myślicie aby sklonować repo Reeka i podmienić regułę która nam powoduje problemy z reklamami na wp.pl ....

**Comment by xxcriticxx** [comment]
mozna zrobic pull request tylko niewiadomo kiedy reek sie pokaze

**Comment by MajkiIT** [comment]
No własnie chciałem tego uniknąć . On jest z doskoku i leci od najstarszych wpisów do naszego dojdzie za nie wiadomo ile.

**Comment by xxcriticxx** [comment]
napisz email maybe

@F4z moze cos modrego wymyslic. niema jakies reguly zeby jego regule zmieniala?

**Comment by xxcriticxx** [comment]
@MajkiIT przekierowanie do nowej listy tez by troche zajelo

**Comment by F4z** [comment]
@MajkiIT to dobry pomysł, tylko że pewnie wiele osób się o tym nie dowie niestety.

@xxcriticxx  w przypadku uBlocka można dodać odpowiednie reguły i będzie w porządku.
Na przykład:
`money.pl,o2.pl,wp.pl,wp.tv##script:inject(abort-on-property-write.js, gafBodies)`

W Adblocku Plus (w zwykłym Adblocku **chyba** też) dla Mozilli Firefox można wyłączyć poszczególne reguły z listy i też nie powinno być reklam.
![image](https://cloud.githubusercontent.com/assets/11742596/20946707/26a949ae-bc0c-11e6-91f5-7fb91aa8a123.png)

A jeśli chodzi o Adblocka(Plus) dla Chrome, to pozostaje nie korzystać z listy Reeka, tylko z tej przerobionej bez reguły.

**Comment by xxcriticxx** [comment]
@F4z dodasz to do listy dzisaj?

**Comment by F4z** [comment]
@xxcriticxx mogę dodać, ale to wtedy usunę tę regułę - `||fntajkb.wp.pl/$script,important,domain=sportowefakty.wp.pl`
Tutaj o tym pisałem - https://github.com/MajkiIT/polish-ads-filter/issues/1616#issuecomment-265289060 ok?
Najwyżej @MajkiIT mnie poprawi jak coś będzie źle działać 😛

**Comment by F4z** [comment]
@MajkiIT w którym miejscu dodawać reguły, które działają tylko w uBlocku, tak jak w tym przypadku - https://github.com/MajkiIT/polish-ads-filter/issues/1621
`||ipla.hit.stat24.com^$object,domain=ipla.tv,important`

**Comment by xxcriticxx** [comment]
hyba w uBlock polish filters - supplement

**Comment by MajkiIT** [comment]
@F4z moja reguła działała na Adblock Plus i obawiam się, że jej brak spowoduje lawinę reklamacji, ale poczekajmy.

**Comment by F4z** [comment]
@MajkiIT jesteś pewny?
Z tego co wiem, to Adblock Plus nie obsługuje czegoś takiego jak `important`, więc ta reguła nie powinna działać.
Przed chwilą sprawdziłem na stronie `o2.pl` w Firefoxie z niezaktualizowaną listą, gdzie ta reguła `||fntajkb.wp.pl/$script,important,domain=sportowefakty.wp.pl` jeszcze jest dodana i widzę reklamy oraz komunikat "Nieznana opcja filtra".
![image](https://cloud.githubusercontent.com/assets/11742596/20962740/de57b3ca-bc6a-11e6-904d-a94fe38311d0.png)

**Comment by MajkiIT** [comment]
@F4z masz rację. Moja wina. Zapomniałem o tym important

**Comment by F4z** [comment]
@MajkiIT ok, dzięki za odpowiedź, nie ma problemu :)

**Comment by F4z** [comment]
@MajkiIT te trzy reguły dodałem do ogólnej listy, bo one nie powodują problemów z Adblockiem:
`streamin.to##script:inject(noeval.js)`
` joemonster.org##script:inject(abort-on-property-write.js, ub_ct_load)`
` ||ipla.hit.stat24.com^$object,domain=ipla.tv,important`
Dodałem je na dole w sekcji `Rules temporary blocking filters`, bo nie wiedziałem, gdzie powinny być.
Może dodasz kolejną sekcję dla reguł do uBlocka, które "nie przeszkadzają" Adblockowi?

**Comment by MajkiIT** [comment]
@F4z dodałem na końcu odpowiednią sekcję. Dziękuję Ci za update filtrów.

**Comment by F4z** [comment]
Dziękuję.
