### ISSUE TITLE
player.chillizet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#16206]
adblock?

Trwa ładowanie ...
Proszę wyłączyć blokowanie reklam!

![Capture](https://user-images.githubusercontent.com/15007183/80310027-8857d580-87a6-11ea-9b99-f40306bb8d20.PNG)

**Comment by xxcriticxx** [comment]
moze piholem za duzo to samo mam na: 

https://player.radiozet.pl/
https://player.antyradio.pl/
https://player.meloradio.pl/

moze ktos przetestowac?

**Comment by krystian3w** [comment]
player.chillizet.pl - straszą "paluszkiem", audio się odtwarza po chwili
player.radiozet.pl - straszenie ukryte / dezaktywowane, audio się odtwarza po chwili
player.antyradio.pl - straszą "paluszkiem", audio się odtwarza po chwili
player.meloradio.pl - straszą "paluszkiem", audio się odtwarza po chwili

Jak masz ciągły loop to jakieś niestandardowe listy lub Pi-Hole.

**Comment by krystian3w** [comment]
`##.preloader__message__addblock` szukaj czegoś takiego dla `player.radiozet.pl` jak to nie dopuszczenie ukryły komunikat.

**Comment by xxcriticxx** [comment]
nie rozumiem o co chodzi z tym paluszkiem ale sprawdze na pc bez pihole i zobaczymy czy zadziala

**Comment by krystian3w** [comment]
Że nie próbują na siłę wyłączać odtwarzania (że player się nie załaduje), a tylko niby stwierdzenie "nie leci muza - wyłącz AdBlock i może będzie lecieć dalej...".

**Comment by xxcriticxx** [comment]
dziala bez problemu bez pihole czyli pihole jest winny za adblock
