### ISSUE TITLE
Reklamy video ipla.tv

### ISSUE THREAD

**Issue by Eva850** [MajkiIT/polish-ads-filter#1621]
Przed odtworzeniem video jest 2-minutowa reklama. Przykładowa strona http://www.ipla.tv/Serial/5001641-Paradokumentalny/5001989-Zdrady
![reklama](https://cloud.githubusercontent.com/assets/20646455/20944590/576e5294-bc04-11e6-9c07-e128a99f0fbe.png)

**Comment by F4z** [comment]
Nie widzę u siebie reklam.
Możesz podać z jakiej przeglądarki, rozszerzenia do blokowania reklam oraz filtrów/list korzystasz?

**Comment by Eva850** [comment]
Firefox + Ublock Origin + Greasemonkey + AAK script
Moje filtry: https://postimg.org/gallery/1b1qfhddk/
Do niedawna IPLA działała poprawnie a teraz nie działa ani blokada reklam ani pobieranie przez ten userscript: https://greasyfork.org/pl/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod-autor-przemek/code

**Comment by xxcriticxx** [comment]
ja mam na firefoxie 50 z ublockiem

![capture](https://cloud.githubusercontent.com/assets/15007183/20947537/a09980c8-bbdd-11e6-9d68-222e137313b2.PNG)

**Comment by xxcriticxx** [comment]
@Eva850 wow ale filtrow masz

**Comment by F4z** [comment]
Możecie sprawdzić tę regułę?
`||ipla.hit.stat24.com^$object,domain=ipla.tv,important`

**Comment by Eva850** [comment]
Dla mnie działa, brak reklam 👍

**Comment by xxcriticxx** [comment]
regula dobra mozna dodac
