### ISSUE TITLE
zespolmi.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1622]
http://zespolmi.pl/post/5635/wszystko-albo-nic

![image 006](https://cloud.githubusercontent.com/assets/9846948/20966651/9ce7a01a-bc7b-11e6-83cd-56ac22be2759.png)

```
zespolmi.pl##a[href^="https://prisonwarsonline.com/"]
```

@MajkiIT

**Comment by MajkiIT** [comment]
@FadeMind dzięki
