### ISSUE TITLE
Youtube Again...

### ISSUE THREAD

**Issue by deejayscream81** [MajkiIT/polish-ads-filter#16228]
Nie wiem kiedy się uporam z problemami na YT:)
Do swoich filtrów Adguard dodałem również dwa nowe,w związku z miejscem zamieszkania i używanego systemu:
Filtr Safari Adguard
Dandelion Sprout's Nordic Filters

Nie wiem czy dobrze zrobiłem ale potestuje jak Safari z tymi filtrami się bdzie zachowywać.
Od wczoraj przed każdym wyświetleniem clipu na YT pojawia się to:

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/58123985/80793998-ff231300-8b98-11ea-9123-b6630edf5259.png">

Any fix?

**Comment by xxcriticxx** [comment]
@deejayscream81 odznacz jedna listę potem druga zobacz która psuje yt

Zmień browsrer safari no gut!

**Comment by deejayscream81** [comment]
Dobra,Sorry za zasmiecanie.Równocześnie szukałem i szukałem i znalazłem paczkę filtrów wszelkiego rodzaju do odchudzenia YT i zaimplementowałem działa youtube jak nigdy dotąd :)
Do usunięcia albo zamknięcia.
Safari jest gut gut :)

**Comment by xxcriticxx** [comment]
Podaj filtry może komuś się przyda. Potem zamykam ten temat.

**Comment by deejayscream81** [comment]
https://filterlists.com
W szukajce youtube i do wybory do koloru.
Są filtry,które obcinają te stronę prawię do zera,ale to już dla hardcore'owców

**Comment by krystian3w** [comment]
To nie jest błąd, a przemycanie reklamy przez Google, raczej się takie coś będzie zdarzać.

**Comment by deejayscream81** [comment]
> To nie jest błąd, a przemycanie reklamy przez Google, raczej się takie coś będzie zdarzać.

Masz rację,wątek zamknięty,myślałem,że filtry YT które znalazłem pomogły,a jednak google to dalej przemyca co jakieś 10-15 wyświetleń. NIe wierzę,że nie ma jakiejś linijki w filtrach,która to potrafi ominąć.

**Comment by krystian3w** [comment]
Nie dla safari z iOS na macOS z AdGuard 2.5.X prędzej.

**Comment by deejayscream81** [comment]
? Możesz rozwinąć co masz na myśli?
