### ISSUE TITLE
skapiec.pl (mały bug)

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#1623]
http://www.skapiec.pl/cat/200-telefony-komorkowe.html na dole po prawej jak klikniesz na "ŚWIĄTECZNE PREZENTY" nic się nie dzieje

**Comment by MajkiIT** [comment]
Chyba powinno to zniknąć, bo to reklama. 
www.skapiec.pl##.creation-corner

**Comment by adreporter** [comment]
OK. Proszę zablokować http://k266d5zsl.onet.pl/adclick/CID=132824/CCID=355260/LU=201611180341438074300058/CS=fa4/NID=1358274/S=SKAPIEC/A=TELEFONY/SID=onet-ad-flat-widget/URL=http://www.skapiec.pl/lp/swiateczne-prezenty 
oraz http://k266d5zsl.onet.pl/adclick/CID=132824/CCID=349690/LU=201611180341438074300058/CS=fa4/NID=1358274/S=SKAPIEC/A=GLOWNA/SID=onet-ad-flat-widget/URL=http://www.skapiec.pl/lp/mikolajki

**Comment by MajkiIT** [comment]
@adreporter a gdzie masz te linki na stronie?

**Comment by adreporter** [comment]
Są to linki skopiowane z obrazków "ŚWIĄTECZNE PREZENTY" oraz "MIKOŁAJKI" na dole po prawej.

**Comment by F4z** [comment]
Można też zablokować skrypty z onetu, wtedy ta reklama w ogóle się nie pokaże.
`||onet.pl^$script,domain=www.skapiec.pl`
Tylko trzeba sprawdzić, czy ta reguła nie blokuje jakichś funkcji strony, ale raczej nie powinna.
