### ISSUE TITLE
tech.wp.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16230]
insta ( pod artykułem ) : https://tech.wp.pl/bill-gates-mowi-o-szczepionce-na-covid-19-zauwazyl-ogromny-problem-6505774831442049a

**Comment by krystian3w** [comment]
Nie powinno być z uBO 1.26.0+:

https://github.com/MajkiIT/polish-ads-filter/blob/5d1467be4acdc3399fb96b01ac7f4cddc2bfddea/adblock_social_filters/social_filters_uB_AG.txt#L87

Pod AdBlock i ABP trzeba by chyba przywrócić mój stary długi `-abp-has` i aktualizować co około miesiąc.
