### ISSUE TITLE
s-pt.ppstatic.pl

### ISSUE THREAD

**Issue by mdhry45sw** [MajkiIT/polish-ads-filter#16246]
Cześć,

Host s-pt.ppstatic.pl raczej powinien zostać odblokowany. Sypie się cała główna strona np. gazetawroclawska.pl gdy adres jest zablokowany.

**Comment by xxcriticxx** [comment]
@mdhry45sw dodaj sobie do whitelisty jako temp fix

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/a70e44f2060941edc2d9f3c8a04745e48631da71#diff-d8ea39860d41c52acbaf79f743dbd489
