### ISSUE TITLE
hdseans.pl

### ISSUE THREAD

**Issue by BlackGlassSkin** [MajkiIT/polish-ads-filter#16245]
"**hdseans.pl**"

Nie można uruchomić żadnego streamu w kodi

wygląda na to że po dodaniu poniższego wpisu do białej listy zaczyna działać.
**ebd.cda.pl**

**Comment by xxcriticxx** [comment]
@BlackGlassSkin na jakie liscie widzisz `ebd.cda.pl`?

**Comment by BlackGlassSkin** [comment]
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/a70e44f2060941edc2d9f3c8a04745e48631da71#diff-d8ea39860d41c52acbaf79f743dbd489
