### ISSUE TITLE
fd.nl [incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#1624]
Current behaviour
https://www.dropbox.com/s/2wadjusr465f8l8/Schermafdruk%202016-12-05%2011.34.35.png?dl=0
expected
https://www.dropbox.com/s/zse8cbe1357grfq/Schermafdruk%202016-12-05%2011.35.14.png?dl=0
caused by
```
~piekarniaanka.pl,~xboxarcade.pl,~everafterhigh.com,~wmeritum.pl,~microsoft.com,~paypal.com,~reserved.com,~zumi.pl,~komunikacja.bialystok.pl,~nvidia.com##:not(input)[id*="cookie"]
```

**Comment by MajkiIT** [comment]
Thanks
