### ISSUE TITLE
vod.pl

### ISSUE THREAD

**Issue by ghost** [MajkiIT/polish-ads-filter#1625]
Reklamy
nie są takie złe...
To dzięki nim masz darmowy dostęp
do naszych najlepszych treści.
Prosimy, odblokuj wyświetlanie reklam
w naszym serwisie.

**Comment by F4z** [comment]
@Gunderyk możesz podać z jakiej przeglądarki i z jakiego rozszerzenia do blokowania reklam korzystasz?

**Comment by Gunderyk** [comment]
Chrome,ublock orygin.

**Comment by F4z** [comment]
Ok, dzięki za odpowiedź.
Wydaje mi się, że to jakiś problem z działaniem uBlocka w Chrome.
Możesz sam sobie dodać tę regułę - `@@||vod.pl^$generichide` w zakładce "Moje filtry" ona jest na polskiej liście, ale mam wrażenie, że jakiegoś powodu nie zawsze działa.

Jak nadal będzie ten komunikat, to dodaj jeszcze tę regułę:
`vod.pl#@#.text-ad`

**Comment by Gunderyk** [comment]
Dziękuję! Ta reguła działa vod.pl#@#.text-ad  i jeśli można prosić o dodanie. :)

**Comment by MajkiIT** [comment]
Dodane

**Comment by F4z** [comment]
To był/jest problem z uBlockiem, w kolejnej wersji zostanie to naprawione.
Swoją drogą, tylko u mnie początkowe załadowanie filmu długo trwa?
Na przykład tu - `http://vod.pl/filmy-i-bajki-dla-dzieci/planet-hulk-hulk-na-obcej-planecie/6yxxbzw`
Po dodaniu tej reguły mam wrażenie, że jakoś szybciej się wczytuje:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=vod.pl`

**Comment by MajkiIT** [comment]
Tak jest dużo szybciej.

**Comment by Gunderyk** [comment]
@F4z @MajkiIT Dziękuję Panowie!
