### ISSUE TITLE
napiprojekt.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#16253]
![Capture](https://user-images.githubusercontent.com/15007183/81184413-6288b880-8f7e-11ea-8ad8-9651e3c790b7.JPG)

**Comment by gargul2** [comment]
Założyli pułapkę na EasyList-owy `/ads-2.`, trzeba ją ominąć:

`@@||www.napiprojekt.pl/js/ads-2.js$script,domain=www.napiprojekt.pl`

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/4656ce631f8f0057369457b1c2faf5aa35e9eb49#diff-6de60f294b8bd23c752f8fcbece875b1

**Comment by krystian3w** [comment]
Przycisk działa, nierzetelny test.

`##.ez-sticky-footer` - to resztka reklamowa, źle wycięta i zasłania zielony przycisk cookies.

**Comment by gargul2** [comment]
> krystian3w : Przycisk działa, nierzetelny test.

Kwestia interpretacji, punkt widzenia zależy od punktu siedzenia...uważam, że nie należy popadać w skrajności w definiowaniu/interpretacji kiedy coś działa, a kiedy nie, zależy jak kto interpretuje "działa".

Wiizualnie w praktyce  - nie działa - bo po kliknięciu nie ma żadnego efektu -  komunikat nie zostaje zamknięty, a ty znalazłeś przyczynę tego niedziałania/usterki i to że po usunięciu usterki technicznie przycisk sam w sobie działa, to raczej niczego nie zmienia, bo przycisk nie jest po to żeby działał tylko sam dla siebie/ sam w sobie i dla wybrańców/informatyków po usunięciu usterki, ale dla wszystkich, czyli przede wszystkim typowych Kowalskich odwiedziających stronę, a dla nich po prostu nie działa.

> krystian3w : `##.ez-sticky-footer` - to resztka reklamowa, źle wycięta i zasłania zielony przycisk cookies.

Nie napisałeś wycięta przez co, jeśli chodziło ci, że przez jakieś filtry, to nierzetelny test :grinning:, bo z wyłączonym adblockerem jest to samo, więc resztka jest źle wycięta przez samą stronę - błąd po stronie strony.

**Comment by zaba-monika** [comment]
> krysitan3w : Przycisk działa, nierzetelny test.

- chodziło o to, że nie działa wizualnie / w sensie praktycznym od strony typowego internauty: klika się w niego, a komunikat się nie zamyka, a pod maskę nie zaglądałem i technicznie nie analizowałem, więc faktycznie, zaglądając pod maskę / patrząc od strony technicznej, to jest tak jak piszesz.

> krysitan3w : `##.ez-sticky-footer` - to resztka reklamowa, źle wycięta i zasłania zielony przycisk cookies.

- tu się mylisz, bo to problem leżący po stronie strony (masło maślane) a nie filtrów, bo nawet przy wyłączonym adblockerze dalej to jest.

Tak czy inaczej, postanowiłem dokładnie udokumentować ten problem, który wcześniej znalazłem i pobieznie opisałem, a ty zajrzałeś głębiej, więc zrobiłem podsumowanie i dokumentację:

- problem leży po stronie strony a nie filtrów, bo nawet przy wyłączonym adblockerze dalej to jest
- ale może warto go zaadresować w którejś z polskich list
- a mianowicie na stronie jest niewidzialny / prezroczysty prostokąt: `www.napiprojekt.pl##.ez-sticky-footer`
- który nie spełnia żadnej przydatnej funkcji
- a tylko przeszkadza i uniemożliwia zamknięcie komunikatu ciasteczkowego bo przysłania zielony przycisk "ZAMKNIJ" od komunikatu ciasteczkowego, i przez to nie da się tego przycisku kliknąć, bez wcześniejszego pozbycia się tego niewidzalnego elementu, a w konsekwencji nie da się zamknąć komunikatu ciasteczkowego

![111](https://user-images.githubusercontent.com/72980128/97804042-a0c11500-1c4d-11eb-9857-c9243b751dcb.png)

- po aktywacji list ciasteczkowych komunikat ciasteczkowy jest ukryty, ale
- a) nie każdy korzysta z list ciasteczkowych
- b) dalej jest problem bo nie da się wcisnąć na stronie przycisków: "STRONA GŁÓWNA, "POBIERZ", "FORUM", "O PROGRAMIE", "RANKING", "POMOC", "ZESPÓŁ" oraz częśćiowo "REGULAMIN"

![222](https://user-images.githubusercontent.com/72980128/97804089-e67ddd80-1c4d-11eb-87df-6813a14d6029.png)

**Comment by MESWEB** [comment]
Przepraszam ze zapytam ale o co chodzi?

**Comment by krystian3w** [comment]
A żabcia zapisała sobie całą historię z poprzednich postów do notatnika i wkleja na potęgę po pół roku.

Jak dla mnie `ez-sticky-footer` nie nadaje się by blokować to jako cookies/rodo.

**Comment by zaba-monika** [comment]
> MESWEB : Przepraszam ze zapytam ale o co chodzi?

- dobry żart, a co nie umiesz czytać po polsku? 
- chodzi o to, co jest napisane, a napisane jest jasno, szczegółowo i po polsku.
- jeśli nie rozumiesz polskich słów to tu masz słownik: https://sjp.pwn.pl/
- chyba, że trzeba ci z polskiego na chiński przełożyć, a potem spowrotem, tylko nie wiem jaką to różnicę zrobi.
- opiero co [automat](https://github.com/MajkiIT/polish-ads-filter/discussions/17516) chciał tworzyć, a komentarza po polsku nie umie przeczytać...hehe normalnie zabawne.

> krystian3w : A żabcia zapisała sobie całą historię z poprzednich postów do notatnika i wkleja na potęgę po pół roku.

- dziwi cię to, skoro ktoś nabałaganił i pousuwał komentarze...to się je przywraca, 
- więc zły adres do zażaleń, prawidłowy to: https://support.github.com/request tam zapytaj dlaczego robią bałagan i usuwają komentarze / poproś o przywrócenie, to nie trzeba będzie przywracać.
- PS. akurat ten był przywrócony z pamięci i to przypadkiem, tylko dlatego bo ktoś założył wątek [z tą samą stroną](https://github.com/MajkiIT/polish-ads-filter/issues/17418), no i tylko połowa została przywrócona, bo komentarz został rozbudowany o połowę, któa wcześniej nie istniała.
- pozatym trochę hipokryzją wieje, może więcej konsekwencji, bo piszesz o wklejaniu na potęgę, a o wcześniejszym usuwaniu na potęgę przez github to nic nie wspominasz...więc stary najpierw ogarnij jaka była sekwencja zdarzeń: usunięcie > przywrócenie, usuwanie na potęgę = przywracanie na potęgę, najpierw była akcja: usuwanie a potem reakcja: przywracanie

**Comment by MESWEB** [comment]
@zaba-monika No sorki ale w pierwszym poscie widze tylko screen strony i nie wiem co z nim jest nie tak? Mam szukac w nim dead pixels czy Wallego? Jesli chodzi o Ciasteczka czy tez RODO to instalujesz I don't care about cookies i dziekuje dowidzenia.

**Comment by zaba-monika** [comment]
@ MESWEB 

- przecież na zrzucie ekranu w pierwszym komentarzu na samym środku jest komunikat na czerwonym tle "wyłącz adblocka" + obok komentarza jest żółta etykieta od zgłoszenia "adblock detect", więc nie wiem jak można nie widzieć / wiedzieć o co chodzi...:
![capture_034_03-11-2020_09-05-46](https://user-images.githubusercontent.com/72980128/97961601-ea2b7480-1db3-11eb-9d36-bc9e544c7e56.png)
- druga kwestia to: nie wiem czemu w ogóle wspominasz o pierwszym komentarzu skoro to zgłoszenie i ten adblock jest sprzed pół roku, został dawno naprawiony i już się nie pojawia póki co...
- trzecia kwestia:  to o czym ja pisałem w [swoim komentarzu](https://github.com/MajkiIT/polish-ads-filter/issues/16253#issuecomment-720090493) z przedwczoraj to dotyczy innej sprawy, a nie adblocka (jest ona przedstawiona na zrzutach ekranu i dokładnie opisana w komentarzu)...
- więc musiałeś się nieźle zakręcić żeby nie załapać o co chodzi, i to samo w sobie nie stanowi problemu, chodzi o sposób w jaki to zrobiłeś, napisałeś że nie wiesz o co chodzi, ale nie wskazałeś dokładnie czego nie rozumiesz (których słów / którego zdania)...więc wynika, że nie zrozumiałeś całego komentarza, więc niby co miałem ci wyjaśnić, miałem ci zrobić kopiuj wklej całego komentarza albo cały komentarz tłumaczyć / przepisywać na nowo, kiedy nie ma takiej potrzeby? Bo jak wszystcy rozumieją, oprócz jednej osoby, to nie będę pod jedną osobę przepisywał całego komentarza...
- dodatkowo, pisząc ogólnikowo, że nie wiesz o co chodzi, bez podawania których słów / zdań dokładnie nie rozumiesz,  czyli bez udowodnienia że cokolwiek było napisane niejasno, w brzydki sposób zasugerowałeś innym jakby to była moja wina... że ty czegoś nie zrozumiałeś i jakby to mój komentarz był niejasny, kiedy jest dokładnie odwrotnie, w komentarzu jest jasno i dokłanie opisane o co chodzi
- a dodatkowo przyklasnął ci i przytrollował temu krystian3w tak samo brzydko sugerując, że to moja wina bo umieszczam ponownie komentarze, które kiedyś były w innym miejscu, a potem zostały usunięte, a to wcale nie prawda, że przez mój komentarz ty nie zrozumiałeś, bo na początku mojego komentarza jest cytat wypowiedzi krystianw3 i zrzut ekranu żeby było wiadomo, że chodzi o ten komunikat, no ale troll krystian3w lubi sobie potrollować na potęgę wykorzytując sytuację...

- a wiecie na czym polega trollowanie lub zbiorowa głupota? 
- że przychodzi taki jeden bałwan i jednym zdaniem: "o co chodzi?" bez podawania szczegółów, podważa cały mój komentarz i sugeruje jakbym to ja coś niejasno napisał
- a potem przychodzi drugi bałan i również jednym zdaniem "A żabcia zapisała sobie" przyklaskuje temu co poprzednik napisał
- a potem przychodzi taka inteligentna osoba ja ja i musi was odtrolowywać
- a wiecie na czym polega cały szkopuł ?
- że trollom / bałwanom wystarczy przytrolowanie jednym zdaniem, żeby kogoś obrzucić błotem i zrobić z kogoś głupka, a temu komuś, z którego zrobiono głupka, potrzebne są elaboraty na całą stronę, żeby wszystko wyjasnić i wykazać, że nie jest się głupkiem i że winya leży po stronie osób które obrzucały błotem / trollowały, na tym polega trollowania, że do przytrolowania wystarczy jedno głupie zdanie, a do obrony potrzeny jest elaborat, ale ja pokonam każdego trolla..

**Comment by krystian3w** [comment]
Można jeszcze do nich napisać, że im się reklama w sticky-footer zepsuła, może naprawią...
