### ISSUE TITLE
exdb.net

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#16252]
![Capture](https://user-images.githubusercontent.com/15007183/81119386-a3d68500-8ef8-11ea-8869-c6ee65c09da4.PNG)

**Comment by gargul2** [comment]
Tam jest aż 5w1:
- anty-adblock
- blokada prawego przycisku myszy (menu)
- blokada zaznaczenia tekstu
- wyskakujące okienko. 
- i co zaskakujące nawet zablokowanie konsoli www i narzędzi dev

Po włączeniu uBlock Filters i/lub AdGuard Base filter jest ok, więc tmożna filtry wyciągnać z którejś  z tych 2 list i przerobić na odpowiedniki zgodne z ABP np. z AdGuard:

```
exdb.net##+js(abort-on-property-read, zfgformats)​​
exdb.net##+js(abort-on-property-write, _pop)​​
exdb.net##​+js(abort-on-property-read, mdpDeBlocker)
```

na

`exdb.net#$#abort-on-property-read zfgformats; abort-on-property-read mdpDeBlocker​; abort-on-property-write _pop​;`

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/9dd993d732eb4661a67fa4f1532531a6c97b5d68#diff-6de60f294b8bd23c752f8fcbece875b1

**Comment by gargul2** [comment]
I niby co ten commit ma naprawiać (pytanie retoryczne - bo nic nie naprawia - można co najwyżej ten whitelist zostawić zapobiegawczo na przyszłość):
- w ABP nic: whitelistowanie czegoś co nawet nie jest zablokowane
- w AdGuard nic: bo tam już jest taki sam whitelist, a nawet gdy się wyłączy ten whitelist to i tak nie ma anty-adblocka ani tych innych rzeczy, bo je skryptami ogranięli
- w uBO nic: bo w uBO też nie ma anty-adblocka ani tych innych rzeczy, bo też skryptami ogarnęli, nawet pomimo że żądanie zablokowane, bo tam się nie bawią w whitelistowanie tylko ubijają przy samej dupie, więc przepuszczenie tego żądania nic nie daje

Żeby było zabawniej -  teoretyczny filtr który ja podałem - składanka 3w1 przerobiona z AdGuarda też nie działa, czort wie czemu, (specjalnie zainstalowałem ABP tylko po to żeby sprawdzić z ciekawości) ale na razie nie analizowałem tego, później pomyślę.

**Comment by gargul2** [comment]
No to użytkownicy ABP są trochę w dupie bo to dziadostwo trzeba ubić skryptami, a filtry skryptowe ABP nie będą działały na innej liście niż ABP Anti-Circumvention Filter List: https://github.com/MajkiIT/polish-ads-filter/issues/16063#issuecomment-625266392 lub zakładce Moje Filtry, zresztą te filtry w ogóle mi nie działały nawet w zakładce Moje Filtry.

**Comment by gargul2** [comment]
Jednak się dało anty-adblocka ominąć zwykłym filtrem:
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=exdb.net`

Zobaczymy jak z resztą utrudnień na stronie.

**Comment by gargul2** [comment]
.

**Comment by krystian3w** [comment]
Jak już robić dopuszczenia to może z `if` wykluczający dla uBO i całej masy aplikacji AG (tzw. "not for platform")?

Prawy klik został odrzucone przez wszelkie polskie filtry, uAssets lub AdGuard...

**Comment by krystian3w** [comment]
Problem może magicznie znowu Pi-hole wyciąga na światło dzienne i skrypt działa za późno (i dopuszczenia / blokady może też?)...?

**Comment by gargul2** [comment]
Widzę, że do polskiej listy została dodana jakaś [mieszanka](https://github.com/olegwukr/polish-privacy-filters/commit/fe5e19fbe329823a2d5f3d97e1c1e38ce01c92e1) filtrów z [AG](https://github.com/AdguardTeam/AdguardFilters/commit/4d21c5455436f02cb6ffad590ffe434d3c3c2a6c) i [uBO](https://github.com/uBlockOrigin/uAssets/commit/51e7bf869f53c94ea97338b8f74a2c979760fcf9)

Tylko po pierwsze nie wiem po co skoro ani na uBO ani na AG nie ma anty-adblocka ani innych problemów na `exdb.net`, no ale może ktoś chciał żeby rozwiązanie było dodatkowo w ojczystej liście.

Po drugie, że owa mieszanka nie rozwiązuje problemu dla użytkowników ABP, bo należy dodać filtry podane przez mnie w moim poprzednim [komentarzu](https://github.com/MajkiIT/polish-ads-filter/issues/16252#issuecomment-625225262) na dole ("Komentarz 3").


> krystian3w : "Prawy klik" został odrzucony przez wszelkie polskie filtry, naprawy do uAssets lub AdGuard...

Został naprawiony 2 godziny temu przez "mieszankę".

**Comment by krystian3w** [comment]
Może dodane by uAsset usunęło u siebie - AG nie usuwa nigdy, przynajmniej aż lista nie uzyska poprawnie statusu `#recommend` (nie wiem co jeszcze wymaga uaktualnienia poza "FiltersRegistry" może jakieś corelibs...). 

Co do problemów z klikiem, klawiaturą i devtools to może takie coś daje `mdpDeBlocker` z aktywną armatą a nie samym pop-upem.

**Comment by gargul2** [comment]
> krystian3w: Może dodane by uAsset usunęło u siebie 

Ano taki wariant też możliwy (że ktoś chciał nie tyle **dodatkowo**, co **tylko** w polskiej liście), a który z tych dwóch wariantów był pobudką do dodania "mieszanki" na razie pozostaje owiane tajemnicą.

**Comment by gargul2** [comment]
████████████████████████████████████████████████████████████
Rozwiązanie pod ABP:

```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=exdb.net
||exdb.net/wp-content/plugins/*/*.js$script,~third-party
||xadsmart.com^$script,domain=exdb.net
||ntdvjlvau.com^$script,domain=exdb.net
||fthkmwrkqg.com^$script,domain=exdb.net
||ntdvjlvau.com^$popup,domain=exdb.net
||postlnk.com^$popup,domain=exdb.net
||exdb.net/wp-content/uploads/*$popup,domain=exdb.net
```

████████████████████████████████████████████████████████████
Opis powyższych filtrów:

### 1) 
na anty-adblocka: `@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=exdb.net`

### 2) 
zaktualizowany filtr do blokowania tego losowego skryptu, który wcześniej opisywałem we wcześniejszym [komentarzu](https://github.com/MajkiIT/polish-ads-filter/issues/16252#issuecomment-625225262) (Komentarz 3): `||exdb.net/wp-content/plugins/*/*.js$script,~third-party` , dlatego bo poprzednie rozwiązania:

```
||exdb.net/wp-content/plugins/uokjtwxqlymfa/wp-kwjv-qlsdzfr.js$script,~third-party
||exdb.net/wp-content/plugins/*/wp-*-*.js$script,~third-party
```
nie nadają się, bo skrypt ma co jakiś czas nazwę generowaną losowo:
```
https://exdb.net/wp-content/plugins/uokjtwxqlymfa/wp-kwjv-qlsdzfr.js
https://exdb.net/wp-content/plugins/cyewd-frdc/qomswtyis.js
```
### 3)
jakiś syf skryptowy, być może adserwery i można dać je jako np. `||xadsmart.com^$third-party`
``` 
||xadsmart.com^$script,domain=exdb.net
||ntdvjlvau.com^$script,domain=exdb.net
||fthkmwrkqg.com^$script,domain=exdb.net
```
### 4)
wyskakujące okienka, mogą być w nich otwierane różne strony, na razie takie wyłapałem, ale jak ich jest więcej to moż lepiej dać `*$popup,domain=exdb.net` tylko czy wtedy przypadkowo nie zablokuje jakiegoś normalnego/legalnego okienka.
```
||ntdvjlvau.com^$popup,domain=exdb.net
||postlnk.com^$popup,domain=exdb.net
||exdb.net/wp-content/uploads/*$popup,domain=exdb.net
```

Ogólnie sami widzicie, że ABP jest 10 lat za murzynami, i naprawianie w nim tego typu stron, jeśli w ogóle da się naprawić, to wymaga "spaghetti z filtrów".
