### ISSUE TITLE
cda-tv.online

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#16260]
jakas strona z grami podłączona pod guzik play

test link:
https://cda-tv.online/filmy-online/obecnosc/

**Comment by hawkeye116477** [comment]
Strona stworzona 1 maja tego roku...

**Comment by krystian3w** [comment]
film działa, na razie brak pop-upa o okupie.

**Comment by krystian3w** [comment]
Powinno wystarczyć dodanie:

`##.playbox > *:not(img)`

opcjonalnie z `visibility: hidden` by zostawało ładniej tło, jak nie chcemy tła to może najwyżej za `#fakeplayer`. Po ukryciu trzeba ręcznie wybrać wersje pop-upa z clipwatching

**Comment by krystian3w** [comment]
Powinno wystarczyć dodanie:

`###clickfakeplayer`

* opcjonalnie z `visibility: hidden` by zostawało ładniej tło,
* jak nie chcemy tła to może najwyżej za `#fakeplayer` (bez "click").
* Po ukryciu trzeba ręcznie wybrać wersje filmu z `clipwatching`

nie wiem czy jest sens modyfikować event listnerer by nie otwierał czegoś w nowej karcie:

```js
function() {
  1 == a("#player-option-1").length ? a("#player-option-1").click() : a(".dooplay_player_option:first-child").click()
}
```

**Comment by hawkeye116477** [comment]
A ja mam numer w Plusie na kartę, więc dla mnie jest aż 25 dodatkowych kanałów TV w Ipli bezpłatnie do 15 czerwca. Brawo ja :smile:

**Comment by xxcriticxx** [comment]
@hawkeye116477 gratuluje może w końcu czegoście się na uczysz z tv

**Comment by gargul2** [comment]
> hawkeye116477 : https://github.com/MajkiIT/polish-ads-filter/issues/16260#issuecomment-626240457 : 
>
> Tutaj się ogląda  https://www.ipla.tv/wideo/serial/Swiat-wedlug-Kiepskich/759, a nie tam na jakiś szemranych stronach

No już widzę jak obejrzysz tam film Obceność....

**Comment by xxcriticxx** [comment]
@hawkeye116477 obecność według Kiepskich

**Comment by krystian3w** [comment]
30 sezon wisi i się kisi...

**Comment by hawkeye116477** [comment]
@xxcriticxx To ja ci daję linki do takich hiciorów, a ty tak wybrzydzasz...

Ale wiem pewnie co polubisz, twój ulubiony sklep z szarlotkami i innymi produktami z dodatkiem jabłek => https://itunes.apple.com/pl/movie/-/id719774556?l=pl :smile:

A na `uplix.pl` znajdziesz inne spoko źródła.

**Comment by xxcriticxx** [comment]
@hawkeye116477 dzieki za offtopic :)

**Comment by xxcriticxx** [comment]
@MajkiIT nowe cuda wyskakuja `Flash Player Update`

![Capture](https://user-images.githubusercontent.com/15007183/82753942-bcb7b500-9d97-11ea-972c-590e8b91d3bb.PNG)

**Comment by xxcriticxx** [comment]
a na main page `PDF converter update`

![Capture](https://user-images.githubusercontent.com/15007183/82753975-f25c9e00-9d97-11ea-8bc9-a553833e2a7a.PNG)

**Comment by hawkeye116477** [comment]
@krystian3w To może teraz dodamy do KADa :smile:.
