### ISSUE TITLE
kategoria temp

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1629]
maly pomysl

panowie moze dodac kategorie temp gdziesz na liscie na dole albo na gorze tam stawiamy wszystko co testujemy albo niewiemy gdzie idzie i potem ktos znas to poprawia

**Comment by MajkiIT** [comment]
@xxcriticxx Chodzi Ci na filtrach?

**Comment by xxcriticxx** [comment]
yes sir

**Comment by MajkiIT** [comment]
Możemy zrobić oddzielny plik i tam wrzucać reguły. Będzie bezpieczniej, bo nie zrobimy problemów innym użytkownikom.

**Comment by xxcriticxx** [comment]
zapytaj @F4z czy to ma sens doadac nowy test liste bardziej myslalem ze natej samej to zrobic
