### ISSUE TITLE
forodecostarica.com [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#16304]
### Zrzut ekranu 

<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/DtF6ZnP.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/eQrUX24.jpg)
</details>

### Link bezpośredni 
`https://forodecostarica.com/discusion-general/163727-gobierno-2018-2022-era-carlos-alvarado-44.html#post3962920`

### Co trzeba zrobić, aby pojawił się błąd?
Just open the link.

### Moja konfiguracja 

**Przeglądarka internetowa:** Chrome

**Rozszerzenia i skrypty:** AdGuard

**Listy filtrów:** 
1. AdGuard Base filter
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Issue can be fixed by `forodecostarica.com#@#[id^="ad_global"]`

**Comment by MajkiIT** [comment]
@Alex-302 Thanks a lot. Fixed.
