### ISSUE TITLE
silvermet.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16327]
zdjęcie rękawiczek się nie wyświetla : https://silvermet.eu/produkt/rekawiczki-damskie-z-dzianiny-krata-ciemna-roz-m/

**Comment by hawkeye116477** [comment]
@ryanbr Picture of gloves is hidden. Can you add to Fanboy's Social => `@@||silvermet.eu/wp-content/plugins/arscode-social-slider/lionbars/jquery.lionbars.0.3.min.js`?
