### ISSUE TITLE
Zły link ND

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#16358]
```
https://majkiit.github.io/polish-ads-filter/docs/advanced/install-nano-defender/
```

```
https://majkiit.github.io/polish-ads-filter/
```

**Comment by krystian3w** [comment]
Ja bym jeszcze zmienił w Operze proponowane:

> Zainstaluj Extension Source Viewer.

 Jako awaryjną opcję. I jako preferowaną: 

> Zainstaluj Download Chrome Extension.

---

Zaleta to aktualizacja dodatku w tle, pewnie `ESV` dalej tego nie ogarnia dla crx.

**Comment by hawkeye116477** [comment]
@krystian3w No to możesz wyedytować => `https://github.com/MajkiIT/polish-ads-filter/edit/master/website/content/pl/docs/advanced/Jak-zainstalowac-Nano-Defender-na-Firefoksie,-Waterfoksie,-(Chr)Operze-albo-Chrome%3F.md`. Niestety tylko trzeba mieć `hugo`, by potem całą stronę wygenerować, bo @MajkiIT nie zrobił klucza i nie podpiął GH Actions.

**Comment by krystian3w** [comment]
To mogę wstawić jako draft na razie.

**Comment by krystian3w** [comment]
Dobra za wysokie progi:

```
$ git restore --source=HEAD :/
error: invalid path 'website/content/pl/docs/advanced/Jak-blokowac-reklamy-w-przegladarce-Yandex-na-Androidzie?.md'
error: invalid path 'website/content/pl/docs/advanced/Jak-zainstalowac-Nano-Defender-na-Firefoksie,-Waterfoksie,-(Chr)Operze-albo-Chrome?.md'
error: invalid path 'website/content/pl/docs/basic/Jak-zapobiec-zamienianiu-linkow-przez-Google-przy-kliknieciu-PPM?.md'
```

Na Windows nie można użyć plusa...

**Comment by hawkeye116477** [comment]
Ok, ja już zrobię dalszą część :smile:.
