### ISSUE TITLE
mtv.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16377]

**Comment by krystian3w** [comment]
Na pewno cookies a nie social w stopce?

**Comment by krystian3w** [comment]
@hawkeye116477  masz pomysł jak podkraść do nas akceptowanie masowo evidon? Niby Polonia w Norwegii i Mołdawii może mieć białą stronę zamiast jakiejkolwiek treści.

**Comment by xxcriticxx** [comment]
@krystian3w zamykamy?

**Comment by krystian3w** [comment]
Na razie bym zostawił, użyje Surfshark jak mają w płatnej wersji jakiś mołdawski i norweski serwer VPN.
