### ISSUE TITLE
radiolodz.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16379]
za dużo ikonek coś blokuje w artykułach, np w tym : https://www.radiolodz.pl/broadcast_posts/60809-sojusznik-w-walce-z-pandemia-czy-prawdziwy-wrog-login

![rad](https://user-images.githubusercontent.com/23176832/82435432-9989be80-9a94-11ea-8a42-ca848752b8f3.png)

**Comment by krystian3w** [comment]
fanboy, a twórcy mogli pomyśleć by zmianę rozmiaru wydzielić, niepełnosprawność to nie społecznościówka.
