### ISSUE TITLE
vivaldi.start.me/start

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16390]
( na dole )

**Comment by krystian3w** [comment]
AdBlock detected: `https://start.me/start/pl/strona-glowna`

@olegwukr  /  @MajkiIT 

![wyszukiwarka](https://user-images.githubusercontent.com/35370833/82444755-02c4fe00-9aa4-11ea-9a2c-ec3ccd3cbc39.JPG) |
--- |

**Comment by MajkiIT** [comment]
na reklamy `start.me##.widget-page__ads` ale adblocka nie widzę niestety

**Comment by gargul2** [comment]
Anty-adblock wyskakuje gdy się włączy jedną z tych list lub obydwie:
- Polskie Filtry Elementów Irytujących, filtr powodujący: 
`start.me##.app__message > .info-message, .cookiebar`
-  I Don't Care About Cookies, filtr powodujący: 
`start.me##.app__main-layout > .app__message`

Zwhitelistowanie obydwu filtrów rozwiązuje anty-adblocka, ale wtedy z kolei pojawia się komunikat cookies, więc jeśli ktoś chce usunąć anty-adblocka bez konieczności whitelistowania komunikatu cookies to: `start.me##+js(nostif, adBanner)`.
