### ISSUE TITLE
used by button 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#16399]
@MajkiIT dasz rade wlaczyc ten kuzik?

![Capture](https://user-images.githubusercontent.com/15007183/82501939-197b4d00-9ac4-11ea-901e-b960e8c0f952.PNG)

https://help.github.com/en/github/visualizing-repository-data-with-graphs/listing-the-packages-that-a-repository-depends-on

**Comment by hawkeye116477** [comment]
To jest do paczek instalowanych przy pomocy npm/Maven/Yarn/Python PIP. By wyświetlało się wymagany jest jeden mały plik, np. https://github.com/hawkeye116477/CS/blob/master/package.json, z tym, że w tym przypadku ja tylko wymagam, a żeby wyświetlało się „used by", moja paczka musiałaby być zależnością dla innych, używana przez inne paczki.

Tak więc @MajkiIT się nie bawi w żadne paczki, więc takie coś nie jest dla niego.

**Comment by krystian3w** [comment]
Jeszcze da się zrobić by obok nazwy repo pisało "(template)" ale to już pewnie tylko z ustawień repo i raczej ludzi by straszyło.
