### ISSUE TITLE
male porownanie ublock i przegladarek

### ISSUE THREAD

**Issue by Lukjan37** [MajkiIT/polish-ads-filter#16409]
musze cos napisac, male porownanie. mam na lapku opera, a na pc vivaldi, i ublock origin. na lapku sa reklamy, a na pc nie ma reklam. te same filtry.

**Comment by hawkeye116477** [comment]
`te same filtry`

No chyba jednak nie do końca, bo `uBO` obsługuje dyrektywę `!#include`, czyli ma dodatkową listę dołączoną do tamtej. Opera Adblocker tego nie obsługuje, jak i również niektórych reguł, które uBO obsługuje i chyba nawet też nie obsługuje paru reguł, które ABP obsługuje.

**Comment by lukjan32** [comment]
aha, dobra

**Comment by hawkeye116477** [comment]
@Moderator Chyba temat do zamknięcia :smile:
