### ISSUE TITLE
gram.pl (2)

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#16400]
### Zrzut ekranu 

![2020-05-20_21-16](https://user-images.githubusercontent.com/19818572/82487813-2eb1a500-9adf-11ea-9619-71a3ab350ea7.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

5x info `Ojej, czy to AdBlock? 😲`

Otworzyłem ponownie, bo #16398 zostało zamknięte, pomimo, że nienaprawione (ktoś coś dodał, ale chyba nie sprawdził, czy na pewno działa).

**Comment by gargul2** [comment]
A nawet gorzej, nawet zanim ktoś dodał to już [było mocno skopane](https://github.com/olegwukr/polish-privacy-filters/commit/d57a298b06e4b2fe4ff7fa9ae85bb773018ed5a4?diff=split#diff-6de60f294b8bd23c752f8fcbece875b1L264):
- zduplikowane: `domain=www.dieroten.pl`
- mało tego, jedno z nich znajdujące się przed `$` zamiast za
- jest `xmlhttprequest` zamiast `script` 

co skutkuje tym, że filtr już wcześniej nie działał nawet dla: `www.dieroten.pl`, co skutkuje anty-adblockiem na `www.dieroten.pl` - [link](https://www.dieroten.pl/art/show/sport-bild-bayern-chce-havertza-na-2021-rok/34987):
![capture_001_21-05-2020_15-21-10](https://user-images.githubusercontent.com/63287518/82563128-c1515300-9b76-11ea-95b9-ec6269df2149.gif)

Poprawnie ma być: `@@||adservice.google.com/adsid/integrator.js$script,third-party,domain=www.dieroten.pl|www.gram.pl`

**Comment by krystian3w** [comment]
ja bym uciął `www.` raczej nie mają subdomen, gdzie plik potrzebny a i może zaczną kombinować z wyłączeniem `www.` lub jak aliexpress z `s.click.aliexpress.com` by w Pi-Hole / Hosts uniknąć blokady z braku dopasowania.

**Comment by gargul2** [comment]
...okazało się, że dalej jest anty-adblock, bo okazało się, że zwhitelistowaliśmy integrator tylko z `adservice.google.com` , a jest jeszcze drugi, ojczysty integrator: `adservice.google.pl` więc trzeba dokleić domenę także do [drugiego filtra](https://github.com/olegwukr/polish-privacy-filters/blob/58c28992288cfa856b1a030fa3308465665fa779/anti-adblock.txt#L457)

Dodatkowo trzeaby uzupełnić ten filtr o opcję `,xmlhttprequest` bo w parze z ojczystym skryptem `intergatora` jest jego ojczyste dziecko - żądanie xhr.

A najlepiej jakby zbić obydwa filtry whitelistujące: [JEDEN](https://github.com/olegwukr/polish-privacy-filters/blob/58c28992288cfa856b1a030fa3308465665fa779/anti-adblock.txt#L277) i [DRUGI](https://github.com/olegwukr/polish-privacy-filters/blob/58c28992288cfa856b1a030fa3308465665fa779/anti-adblock.txt#L457) w jeden:
`@@||adservice.google.*/adsid/integrator.js$script,xmlhttprequest,third-party,domain=www.dieroten.pl|www.gram.pl|tvp.pl`

**Comment by hawkeye116477** [comment]
@gargul2 No to dziwna sprawa, bo ja tego ojczystego w ogóle nie mam.

**Comment by gargul2** [comment]
Na `dieroten.pl`, a nie na `gram.pl`
