### ISSUE TITLE
muzyka.teledyski.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#16407]
press play for adblock 

test link:
http://muzyka.teledyski.info/index.html?text=dmx&strona=0&file=global_test&name=eplik&dalej=Szukaj

![Capture](https://user-images.githubusercontent.com/15007183/82667254-7599ba80-9c05-11ea-86c0-bfb58a6ce18b.JPG)

**Comment by krystian3w** [comment]
"Błędny" link testowy, trzeba kliknąć ręcznie play.

ABP:

`@@*/ads.js$script,domain=mp3.teledyski.info`

**Comment by krystian3w** [comment]
ABP:

`@@*/ads.js$script,domain=mp3.teledyski.info`

Ale się mogą bawić z nazwą, parametrem i domeną, bo nadrzędnie blokuje skrypt EasyPrivacy, potem EasyList.

---

Ze skryptowym trochę gorzej, trzeba by używać niepewnego `set-constant`, dziwna zmienna "`GFSJHGSYUNNBSDYOOWJHSGIa`", nie polecam.

```
nie-polecam.*##+js(set, GFSJHGSYUNNBSDYOOWJHSGI, true)

! trolling ich skryptu z trybem `read-only`:
nie-polecam.*##+js(ro, GFSJHGSYUNNBSDYOOWJHSGI, truskawki)
nie-polecam.*##+js(ro, GFSJHGSYUNNBSDYOOWJHSGIa, truskawki)
```

**Comment by gargul2** [comment]
Jak coś to whitelist idzie [TU](https://github.com/olegwukr/polish-privacy-filters/blob/4725d7a552b8c172df42f070110fa46e1dcccf81/anti-adblock.txt#L248).

**Comment by xxcriticxx** [comment]
truskawki lol

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/16407 https://github.com/MajkiIT/polish-ads-filter/issues/13186 https://github.com/MajkiIT/polish-ads-filter/issues/20293
