### ISSUE TITLE
cdahd.co

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#16410]
![Capture](https://user-images.githubusercontent.com/15007183/82754322-191bd400-9d9a-11ea-8767-44527e16750a.PNG)

**Comment by krystian3w** [comment]
`@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js$script,domain=cdahd.co`

Skrypt może trzeba uaktualnić @gwarser? Niby teraz modne są `nosiif.js` i `nostif.js` pod BaoBaby i Faby.
