### ISSUE TITLE
play.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16412]
Na głównej brak ciastek ale w tych trzech zakładkach są : 

https://www.play.pl/dlaciebie/sklep/telefony/

https://www.play.pl/dlaciebie/sklep/bez-abonamentu

https://www.play.pl/dlaciebie/sklep/akcesoria

**Comment by krystian3w** [comment]
Na głównej jest z inną klasą: `##.cookies`

w działach są wersje minowe ![](https://i.imgur.com/dlB9grW.png)
