### ISSUE TITLE
pomponik.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#16413]
### Zrzut ekranu 
![2020-05-25_15-34](https://user-images.githubusercontent.com/19818572/82817404-3ab1b400-9e9d-11ea-9367-638cca7f1831.png)

**Comment by gargul2** [comment]
Whitelist idzie tu https://github.com/MajkiIT/polish-ads-filter/issues/16407#issuecomment-632775834

Ciekawostka - przy włączonej jednej z tych list lub obydwu na raz, anty-adblocka nie ma:
- AdGuard Base filter : `@@||js.iplsc.com/inpl.abd/latest/ads.js?$domain=pomponik.pl`
- Fanboy Enhanced Tracking List : `@@||js.iplsc.com^*/ads.js`

**Comment by krystian3w** [comment]
Za mało, trzeba dezaktywować najpierw `shide` jak radzi @fire-bot  #16416

**Comment by hawkeye116477** [comment]
Bot nic nie radzi, to tylko ktoś kto nazwał się pomponik...
