### ISSUE TITLE
GitHub Sponsors

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#16411]
opinije?

https://help.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/about-github-sponsors

**Comment by krystian3w** [comment]
Przecież mamy serduszko a MS kasą raczej nie sypnie.


![obraz](https://user-images.githubusercontent.com/35370833/82755298-f6f27800-9dd2-11ea-8ff4-8fc4794f18aa.png)

**Comment by xxcriticxx** [comment]
ten button prowadzi do `https://patronite.pl/polskiefiltry` ja podalem sponsor z githuba

do 1/1/2020 ms sypal kasa:

Note: The deadline to be eligible for the GitHub Sponsors Matching Fund expired on January 1, 2020. Applications for GitHub Sponsors received after January 1, 2020, are not eligible to participate in the GitHub Sponsors Matching Fund.

**Comment by MajkiIT** [comment]
Można spróbować, ale chyba nie wiem czy coś uda się ugrać.

**Comment by krystian3w** [comment]
Niby termin minął, trzeba było to znaleźć w sylwestra.

**Comment by xxcriticxx** [comment]
Każdy po 10 zł żuci to na kawę będzie

**Comment by hawkeye116477** [comment]
Do kaw jest specjalny serwis => https://www.buymeacoffee.com/ :smile:

**Comment by krystian3w** [comment]
Tam to i nagość / nudyzm jest...

**Comment by xxcriticxx** [comment]
@hawkeye116477 @MajkiIT pije tylko starbaksa

**Comment by krystian3w** [comment]
https://github.com/sponsors/accounts
