### ISSUE TITLE
swiat-magii.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16421]
![capture_005_26-05-2020_16-23-58](https://user-images.githubusercontent.com/63287518/82912812-cdba1f00-9f6d-11ea-8c57-c522de1f6cb7.gif)

Rozwiązanie: 
`swiat-magii.pl#@##ad-container` oraz
`~swiat-magii.pl` do:
https://github.com/MajkiIT/polish-ads-filter/blob/dc0c8721f55b4b276be6ecab0648d181e2511faa/polish-adblock-filters/adblock.txt#L257

**Comment by hawkeye116477** [comment]
@MajkiIT Do poprawy, jeden ~ za dużo.

**Comment by MajkiIT** [comment]
@hawkeye116477 Dzięki
