### ISSUE TITLE
Nowe ikony na GitHub

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#16435]
Wszystko takie jakieś dziwne nagle...

**Comment by xxcriticxx** [comment]
ms update zrobil do win10 github pro edition

**Comment by hawkeye116477** [comment]
Tak w zasadzie to są ikony Octicons v2, niby nie jest to wersja stabilna i prace są w toku... W PCZ też wkrótce zrobimy podmiankę ikon :smile:.
