### ISSUE TITLE
myspeed.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16474]
![2020-06-04 00 06 17 myspeed pl 4b1d499b40fd](https://user-images.githubusercontent.com/36385327/83693888-4452be80-a5f7-11ea-9a8f-2cea497f38e7.png)

**Comment by MajkiIT** [comment]
popup z informacją. @hawkeye116477 chcecie zabrać do siebie ?

**Comment by krystian3w** [comment]
Raczej powinien zostać, @mapx-  znowu masz aktywny `Fanboy Annoyance` lub `EasyList Cookies`?

Nieco gorzej jak generyk wycina, wtedy trzeba by użyć `has()`/`contains()` by generyk wycinał mniej.

**Comment by krystian3w** [comment]
co do błędu to jest to stary błąd **EasyList Cookie**:

```
#@#div[data-cookie]
```

raczej nigdy nie usuną błędu a najwyżej wytną bug z tłem...

**Comment by gargul2** [comment]
> stary błąd EasyList Cookie:

 I nie tylko, Fanboy Enhanced Tracking List też: https://github.com/ryanbr/fanboy-adblock/issues/716

Ogólnie te zgłoszenie to duplikat: 
- https://github.com/ryanbr/fanboy-adblock/issues/716 sprzed półtora roku i
- https://github.com/MajkiIT/polish-ads-filter/issues/12673 sprzed 1 roku i 2 miesięcy.

A więc nie spowodowane polskimi listami, etykieta "duplikat" i do zamknięcia.

**Comment by hawkeye116477** [comment]
@Moderator Wiesz co robić :smile:

**Comment by krystian3w** [comment]
Czemu spamujesz użytkownikowi bez aktywności od 7 lat?

**Comment by xxcriticxx** [comment]
@hawkeye116477 nie wiem co tu robie

**Comment by hawkeye116477** [comment]
@xxcriticxx 
/label odrzucone 
/issue close

**Comment by xxcriticxx** [comment]
@hawkeye116477 sie nie popisales kolego

**Comment by hawkeye116477** [comment]
@xxcriticxx No co, nie podoba się kubek? Ale ten pewnie ci się spodoba => https://allegro.pl/oferta/kubek-prezent-sasiedzi-zabawne-przyjaciele-8769867141 :rofl:
