### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by zabamt** [MajkiIT/polish-ads-filter#16473]
![FireShot Capture 008 - Wykopalisko - Wykop pl - www wykop pl](https://user-images.githubusercontent.com/66387829/83683765-33e61800-a5e6-11ea-8cea-078725895098.png)

**Comment by xxcriticxx** [comment]
@zabamt link? template?

**Comment by xMaap** [comment]
U mnie czysto.

**Comment by krystian3w** [comment]
`Hompeage` po zalogowaniu z ABP lub AdBlock?

**Comment by xxcriticxx** [comment]
@krystian3w wymagane jest konto sorry nie posiadam

**Comment by zabamt** [comment]
Przepraszam za brak opisu. 
Zakładka "wykopalisko", sprawa dotyczy Pi-Hole, ale @krystian3w już to wyjaśnił.

**Comment by xxcriticxx** [comment]
@zabamt testowales `(\.|^)adverts$` regex?
