### ISSUE TITLE
rozkodowanie linka

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#16484]
W jaki sposób mogę rozkodować ten link:

https://easefulnessfallow.club/?td=track.advancemerging.com&data2=w02oth04cidoirjv11lm3cui&city=Montclair&cep=iq1FFO8sMWOnRRnMlebeVElkEf4jCQpXFH51RWJoCI111P9sHJQNpQ_Us8WnkKIBdyCcTIcubreZLT4ZKoG_a4HJxVAcNgmPAXT8vtj75GS93XA7iL3hcISiCaZ94qA6ALiTA6I4Xkowhu8TBaTexVt8QTp6BTLnShGPPqPaQyaLYdJ1dBHvOzV7q7GdMI_9aCxiN8I-P0LpsQYBN801r9iSOUpWqY4rM8lRxxc6gYVLEO9VJHFNRzfTv5_NxdYkaNDDnnGC-EExYcoTeRqnkNIWfGKjlOJkVmGR1oG5aFUK9hNaLCGvqPuVkhMGjmb95U2KVjlXqQYl3YDujf1PgD7ENBhebFqepruqhL9K9jC_E8f-x4h3ngNl0lh9aOHJ-fabTjdBT79CHjSrA1w-4ASZYtnRkgIY95O46aDf5AOj4Pq5kCVETY8M5YAfqP7gRCQ2uP0Ygy3RTre8hZWz0bO_p89EBExx0i4hk54cRW1My5e3U4OdQZkmh3raKnNrhVgwRlWd1NgS_dxhKR2MLVhv1B03_QbC4_AQ4E6HK6hcJWkg0UrLgCGbYOq1nlDjLhyM9KgnKX83Z-4fb_7VF5qF1d_yn3WEte9SNcuhKPiay3QHPvnrBc6QgmZ19gKs7yR0KfnFOokvpcr-WhzVc2iMFuuCBPfwMxamddvvTjkERh7vYgGinsJFgxX7TzZrkf0PoQPNVTJsLoXG29YIsG9QNsiCUTi_6Ow0yKQt8XJbDOkJ1WWQLskTs_YlSecNiEdVgX54Mza38dlVIFHS-Rb_zIKwPH6XTA2uRP1GiPzxOhB-aCAFl_kD4tL0fsErurhEYOSAxDtxJzCHf71CQblq_ZDz9QJL2qrtFiFk7pLYcsfunOXsne0X1LcFwA_A5D-sA7jRhyRsvMt3ld-iWn6y8RH-M5oPBDH98oggbLEVrkLSlobh08ekGXr3IYS4&lptoken=1578914f53b7051615ae&subidaction=VjN8MTQyNjIwMDZ8MjI2MjgzOHwzMDIzNTA0OHwxNTkxNTI4NzE0fDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMHw5OC4xMDkuNzcuMjQ0fDF8c2g9NDUyNzc0NTEyM2JjZjIyNDg4MzBiYTY2ZTJmZjJmNDc4YTUyODI5NTE3MmY4YmU1MDQzOGVhZmU4NjNlMGRlNDc2MzVjMWMxZDgxNDVmMjg2NDc0MDdhNDJmNzEwMjA0MmEzYTRmNmYyOTA4Mjg2OTRiNzA2ZGI2ZmQ4ZGVlZmMyNDY3MTc0ZGYxM2VjODY2MzYxNjFmMjliNDQzZDY5NGJkYzFhODc5fDUwNzhjMjEwZTQ2YmUyMGQ4YmQzMjYwZmM1MmZkYTY3&placementid=14262006&campaignid=258804&bannerid=935826#

**Comment by gargul2** [comment]
To jest kodowane i dekodowane po stronie serwera, tylko serwer ma klucz szyfrująco-deszyfrujacy.

**Comment by xxcriticxx** [comment]
Tego sie spodziewalem. Czyli blokujemy czytelna czesc adresu?

**Comment by gargul2** [comment]
Nie wiem czy to jeszcze istotne, jeszcze niedawno mogłem na tę stronę wejść, szybko ją zablokowali:

![capture_182_07-06-2020_17-05-03](https://user-images.githubusercontent.com/63287518/83972560-23cd8180-a8e1-11ea-9f36-5e65b53e315a.gif)

**Comment by krystian3w** [comment]
Jakby się otwierała gra 18+ lub lub konkurs SMS to może w KAD?

**Comment by xxcriticxx** [comment]
@krystian3w KAD dalej pl czy mix?

**Comment by krystian3w** [comment]
Jak brzydka domena ma polonizację to blokujemy nawet jak końcówka to `.club`.

Osobiście staram się sprawdzać czy jest polski lub plugin `google translate`. Jedynie strony co po sekundzie otwierają inną z przekrętem zwalniam z weryfikacji języka.
