### ISSUE TITLE
we-are-gamers.com

### ISSUE THREAD

**Issue by Darkmoner** [MajkiIT/polish-ads-filter#1648]
`http://we-are-gamers.com/loa2/lp21/?voluumdata=BASE64dmlkLi4wMDAwMDAwOC01NzM3LTQ0ZjAtODAwMC0wMDAwMDAwMDAwMDBfX3ZwaWQuLmNjN2ZkMDAwLWMwOTQtMTFlNi04ZTAyLTgyMjMxNjhkMWZlMl9fY2FpZC4uNDRiNjg2MzUtYzg4NS00NjM5LThhNzQtNTRmMjk0NmQ1ZjBiX19ydC4uUl9fbGlkLi40ZGIxNzNiZi1kNGVjLTRjZDAtODdmZS0zNDE5NmMyYjQxZWJfX29pZDEuLmEzM2NkMDQ4LWYxMjktNDFhZS1iMTA4LTExYmIxNTFiNmU1M19fdmFyMS4uMTIxNzUxMF9fdmFyMi4uUExfX3JkLi53d3dcLlx2aWR6ZXJcLlxuZXRfX2FpZC4uX19hYi4uX19zaWQuLg&key=emt6RE1PSTREY3czTkF4dUFGOWpUQT09&zone=1217510&country=PL&clickid=14815679793107509205202366276354245`

**Comment by MajkiIT** [comment]
I co z tym?

**Comment by xxcriticxx** [comment]
@Darkmoner blokowane przez filtry kad
