### ISSUE TITLE
ubisoft.com/pl-pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16481]
https://www.ubisoft.com/pl-pl/
![2020-06-07 00 00 11 www ubisoft com 48b7916a0053](https://user-images.githubusercontent.com/36385327/83955320-ef5eb480-a851-11ea-836e-dcc8ec9cd8c6.png)

https://news.ubisoft.com/pl-pl/
![2020-06-07 00 01 15 news ubisoft com 83974822c3db](https://user-images.githubusercontent.com/36385327/83955328-069da200-a852-11ea-9647-adec90765e5a.png)

https://forums-pl.ubisoft.com/forumdisplay.php/18-Assassin-s-Creed?s=fe65b7d81c5e8754bbe21c974ff31ff4
![2020-06-07 00 05 45 forums-pl ubisoft com f5e250cfbfff](https://user-images.githubusercontent.com/36385327/83955384-a6f3c680-a852-11ea-8b1e-e54fae8d9305.png)

https://forums-pl.ubisoft.com/forumdisplay.php/24-Far-Cry?s=fe65b7d81c5e8754bbe21c974ff31ff4
![2020-06-07 00 06 05 forums-pl ubisoft com 08d3458593c7](https://user-images.githubusercontent.com/36385327/83955388-b70ba600-a852-11ea-9c36-092cd868206b.png)

https://forums-pl.ubisoft.com/forumdisplay.php/51-Ghost-Recon?s=fe65b7d81c5e8754bbe21c974ff31ff4
![2020-06-07 00 06 36 forums-pl ubisoft com e3eb471e1e8c](https://user-images.githubusercontent.com/36385327/83955393-c4c12b80-a852-11ea-807c-b94bb48c3e0a.png)

https://forums-pl.ubisoft.com/forumdisplay.php/30-Rainbow-Six?s=fe65b7d81c5e8754bbe21c974ff31ff4
![2020-06-07 00 06 57 forums-pl ubisoft com 5ab3c6f9f8b0](https://user-images.githubusercontent.com/36385327/83955397-d1458400-a852-11ea-92a2-a6d77eccfc12.png)

https://forums-pl.ubisoft.com/forumdisplay.php/85-Steep?s=fe65b7d81c5e8754bbe21c974ff31ff4
![2020-06-07 00 07 28 forums-pl ubisoft com a7fee5821a3a](https://user-images.githubusercontent.com/36385327/83955405-e3bfbd80-a852-11ea-8537-680048e38327.png)

https://forums-pl.ubisoft.com/forumdisplay.php/47-Tom-Clancy-s-The-Division?s=fe65b7d81c5e8754bbe21c974ff31ff4
![2020-06-07 00 07 49 forums-pl ubisoft com c7d4a86ef2d2](https://user-images.githubusercontent.com/36385327/83955410-efab7f80-a852-11ea-82fc-a0f4381442c9.png)

https://forums-pl.ubisoft.com/forumdisplay.php/40-Might-amp-Magic?s=fe65b7d81c5e8754bbe21c974ff31ff4
![2020-06-07 00 08 09 forums-pl ubisoft com a3bd5ed7918f](https://user-images.githubusercontent.com/36385327/83955412-fb974180-a852-11ea-9c48-07f3375b7a5c.png)

**Comment by hawkeye116477** [comment]
To międzynarodowa strona, więc jakby bardziej dla Fanboya,

**Comment by krystian3w** [comment]
Nie wiadomo czy wersja PL forum nie ma może innego kodu niż ta dla USA/UK/Kanady i Australii.

**Comment by krystian3w** [comment]
Poza tym oglądając kilka większych portali to oni chyba nie wyrabiają i już bez zgłoszeń nowych nie blokują.

**Comment by hawkeye116477** [comment]
Na forum to w zasadzie pewnie i tak Fanboy nie usunie, bo przyciski sprytnie zrobili, nie da się ich schować, co najwyżej klikanie zablokować.

**Comment by krystian3w** [comment]
W sensie są one tłem na sztywno? Lub duszek CSS png z innymi ikonami.

@gawrser uBo / AG obsługuje gradienty CSS?

```css
background: rgba(248,80,50,1);
background: -moz-linear-gradient(left, rgba(248,80,50,1) 0%, rgba(241,111,92,1) 50%, rgba(246,41,12,1) 51%, rgba(240,47,23,1) 71%, rgba(231,56,39,1) 100%);
background: -webkit-gradient(left top, right top, color-stop(0%, rgba(248,80,50,1)), color-stop(50%, rgba(241,111,92,1)), color-stop(51%, rgba(246,41,12,1)), color-stop(71%, rgba(240,47,23,1)), color-stop(100%, rgba(231,56,39,1)));
background: -webkit-linear-gradient(left, rgba(248,80,50,1) 0%, rgba(241,111,92,1) 50%, rgba(246,41,12,1) 51%, rgba(240,47,23,1) 71%, rgba(231,56,39,1) 100%);
background: -o-linear-gradient(left, rgba(248,80,50,1) 0%, rgba(241,111,92,1) 50%, rgba(246,41,12,1) 51%, rgba(240,47,23,1) 71%, rgba(231,56,39,1) 100%);
background: -ms-linear-gradient(left, rgba(248,80,50,1) 0%, rgba(241,111,92,1) 50%, rgba(246,41,12,1) 51%, rgba(240,47,23,1) 71%, rgba(231,56,39,1) 100%);
background: linear-gradient(to right, rgba(248,80,50,1) 0%, rgba(241,111,92,1) 50%, rgba(246,41,12,1) 51%, rgba(240,47,23,1) 71%, rgba(231,56,39,1) 100%);
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f85032', endColorstr='#e73827', GradientType=1 );
```

**Comment by hawkeye116477** [comment]
@krystian3w Są w tle na sztywno.

**Comment by krystian3w** [comment]
Wyciąłeś wszystkie + klikalność czy 3 tygodnie dla Fanboyów z oczekiwaniem jak szybko wytną?

**Comment by hawkeye116477** [comment]
@krystian3w Tylko z forum klikanie zablokowane, resztę zostawiłem dla Fanboya, bo on biedak, nie ma co robić :smiley:

**Comment by krystian3w** [comment]
Niby bawi się raz na dzień z filtrami Brave.

**Comment by hawkeye116477** [comment]
Widziałem, on tam jest VIPem. A tak w ogóle wysłałem poprawkę co do polskich list, ale coś się nie odzywają => https://github.com/brave/adblock-rust/pull/100.

**Comment by krystian3w** [comment]
Może pani Simsonowa bardziej wie kogo poprosić o weryfikację plików.

**Comment by gwarser** [comment]
@krystian3w heh, fajny pomysł, patrz na to:

![image](https://user-images.githubusercontent.com/886325/83974859-9bef7380-a8f0-11ea-85d3-fad3e0b3a10e.png)

https://stackoverflow.com/questions/19713813/fade-image-to-transparent-like-a-gradient
https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image
Tylko tego generatora to nie rozumiem za bardzo https://www.cssmatic.com/gradient-generator

**Comment by krystian3w** [comment]
A to ładnie, tylko trzeba by zrobić pod każde osobno...

I poprawka:

```
forums-pl.ubisoft.com##+js(remove-attr, href, area[href*="plus.google.com/"])
forums-pl.ubisoft.com##+js(remove-attr, href, area[href*="youtube.com/"])
forums-pl.ubisoft.com##+js(remove-attr, href, area[href*="twitter.com/"])
forums-pl.ubisoft.com##+js(remove-attr, href, area[href*="facebook.com/"])
forums-pl.ubisoft.com##+js(remove-attr, href, area[href*="instagram.com/"])
forums-pl.ubisoft.com##+js(remove-attr, href, area[href*="discordapp.com/"])
forums-pl.ubisoft.com##+js(remove-attr, href, area[href*="reddit.com/"])
```

bardziej uniwersalne i bezpieczniejsze pod:

`forums-pl.ubisoft.com/forumdisplay.php/30-Rainbow-Six`
