### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16483]
Wydzielone od xMaap https://github.com/MajkiIT/polish-ads-filter/issues/13818#issuecomment-639193532, ja z kolei znalazłem rozwiązanie:
`pilot.wp.pl#@#+js(set, Object.prototype.advViewability, undefined)`
`pilot.wp.pl#@#+js(abort-on-property-read, Object.prototype.rebuild)`

![](https://user-images.githubusercontent.com/36385327/83824433-c36af400-a6d6-11ea-9285-a1905cc675cd.png)

a na pasek reklamowy pod video:
`||i.wpimg.pl/x128/pilot-static.wpcdn.pl/dynamic_content/player_bar_*.png$image, domain=pilot.wp.pl` albo kosmetykiem `pilot.wp.pl##a[data-gtm-player-bar="guest_web_desktop"]` (jako gość z typowego komputera / laptopa, nie wiem jak po zalogowaniu, i / lub z Androida)
![capture_128_07-06-2020_10-50-07](https://user-images.githubusercontent.com/63287518/83964373-ef3fd280-a8ac-11ea-8d5f-f565ced30b04.gif)

**Comment by hawkeye116477** [comment]
`pasek reklamowy `

To jest reklama wewnętrzna, Majkel takich nie chowa.

**Comment by gargul2** [comment]
Masz rację, no to może ktoś sobie będzie chciał dodać do Moje Filtry.

**Comment by hawkeye116477** [comment]
Albo @KonoromiHimaries doda do swojej listy, on takie rzeczy uwielbia.

**Comment by gargul2** [comment]
Myślałem, że on już nie żyje, ale chyba jednak żyje, bo się uśmiecha. :smiley:

**Comment by gargul2** [comment]
> Jak dla mnie to wygląda na reklamę wewnętrzną, Majkel takich nie chowa.

[Ktoś jednak to chowa](https://github.com/olegwukr/polish-privacy-filters/commit/8fd08f79e6b9bdb6d9e87149a0692ebc8552dfbc?diff=split#diff-6de60f294b8bd23c752f8fcbece875b1R440) hahaha
