### ISSUE TITLE
swieta.wp.pl

### ISSUE THREAD

**Issue by Eva850** [MajkiIT/polish-ads-filter#1649]
Niezablokowana reklama Mediaexpert
http://swieta.wp.pl/gotowanie/artykul/jest-w-polskiej-kuchni-obecny-od-niepamietnych-czasow
![reklamy](https://cloud.githubusercontent.com/assets/20646455/21112702/0176a588-c0a7-11e6-8d91-320872dc1c10.png)

**Comment by Eva850** [comment]
||swieta.wp.pl/img/sprites-sc5d13da9e4.png$image
||swieta.wp.pl/img/bg-top.jpg$image
swieta.wp.pl##.section__baner.section

**Comment by MajkiIT** [comment]
@Eva850 trochę to uprościłem, ale reklam brak. Dzięki
