### ISSUE TITLE
Brave Browser is hijacking links and inserting affiliate codes, found out by Cryptonator1337 on Twitter.

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#16490]
https://old.reddit.com/r/linux/comments/gya0jv/brave_browser_is_hijacking_links_and_inserting/

**Comment by hawkeye116477** [comment]
> Ale od początku była mowa, że brave będzie podstawiał swoje reklamy w miejsce innych - na tym mają zarabiać.

**Comment by KonoromiHimaries** [comment]
> chodziło tutaj głównie o podmianę linków do giełdy kryptowalut.

nie tylko https://github.com/brave/brave-core/blob/1cac2377c9a2d5e35873d4d3d74130336b86d062/components/omnibox/browser/suggested_sites_provider_data.cc

rozwiązanie https://github.com/gab-ai-inc/defiant-browser https://gitlab.com/KevinRoebert/ClearUrls

**Comment by gargul2** [comment]
> ClearUrls

używam od kilku miesięcy, aczkolwiek na FF.
