### ISSUE TITLE
Kasujemy wszystkie wystąpienia fraz "blacklist/whitelist" oraz "master"?

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#16491]
```
https://go-review.googlesource.com/c/go/+/236857/
```

**Comment by xxcriticxx** [comment]
yo no comprendo

**Comment by KonoromiHimaries** [comment]
https://github.com/MajkiIT/polish-ads-filter/branches

**Comment by xxcriticxx** [comment]
@KonoromiHimaries sorry bro ale nikt nie rozumie o co tobie biega

**Comment by hawkeye116477** [comment]
Zapewne chodzi o to, że niby rasistowskie nazwy i trzeba zmienić...

Ale nie wiem co komu przeszkadza master...

**Comment by krystian3w** [comment]
Ciekawe jak je zmienią w starych PC z złączem ATA gdzie się kawałkiem plastiku zmieniało urządzenie z nadrzędnego na podrzędne lub w tryb automatyczny.

**Comment by hawkeye116477** [comment]
`Chyba, że github zachowuje w przekierowaniu starą nazwę gałęzi.`

Nic z tego, GH nie robi przekierowań po zmianie nazwy gałęzi. To tylko działa, jak zmienisz nazwę repozytorium albo nazwę konta użytkownika/organizacji albo jak [przekażesz](https://help.github.com/articles/how-to-transfer-a-repository) komuś repozytorium.
Tak więc @KonoromiHimaries musi napisać petycję do MS w tej sprawie :smile:

**Comment by xxcriticxx** [comment]
obey your master

**Comment by krystian3w** [comment]
W sumie jak nie udało się usunąć `F**k` i `B*******it` z cookies, to jak w jakimś `has`/`contains` pewnie też się nie uda.

**Comment by hawkeye116477** [comment]
A jeszcze do gorhilla trzeba napisać by w uBO zamienił białą listę na listę wykluczeń/zezwoleń...

Taka ciekawostka => https://www.ppe.pl/news/146567/hbo-cenzuruje-zwariowane-melodie-bugs-bron.html.

**Comment by krystian3w** [comment]
AG też ma "biała lista" / tryb odwrotnej "białej listy".

**Comment by KonoromiHimaries** [comment]
https://mobile.twitter.com/natfriedman/status/1271253144442253312

**Comment by KonoromiHimaries** [comment]
https://twitter.com/natfriedman/status/1271253144442253312

**Comment by KonoromiHimaries** [comment]
https://www.dobreprogramy.pl/Bojownicy-o-tolerancje-wytaczaja-dziala-przeciwko-Gitowi.-Nie-podoba-im-sie-galaz-master,News,108348.html

**Comment by hawkeye116477** [comment]
https://www.telepolis.pl/tech/wydarzenia/google-rezygnuje-z-czarnej-listy-bo-black-lives-matter

> Czy kolejnym krokiem będzie wymazanie z języka „czarnego charakteru”, „białego kapelusza”, albo „rycerza na białym koniu”? Sprawa budzi we mnie mieszane uczucia. Zmiana wydaje mi się równie bezsensowna, co walka z układem dysków master/slave, dziś już zapomnianym dzięki standardowi SATA.

-----------------------

@KonoromiHimaries Ale przekierowania chyba nie dodadzą ani wszystkim nie zmienią, jedynie domyślną nazwę ustawią na nową.

**Comment by krystian3w** [comment]
To lipa...

I czy już coś wiadomo o Afroamerykańskim Piątku? Pomijając że na jesień może znów umrzeć milion ludzi i odwołają?

**Comment by xxcriticxx** [comment]
@hawkeye116477 w lipcu odwiedza nas kosmici

**Comment by hawkeye116477** [comment]
@KonoromiHimaries W szacach też trzeba pozmieniać kolory , co nie :smiley:? 
https://www.spidersweb.pl/rozrywka/2020/07/01/szachy-rasizm-youtube-antonio-radic/

**Comment by hawkeye116477** [comment]
@krystian3w 

> Ciekawe jak je zmienią w starych PC z złączem ATA gdzie się kawałkiem plastiku zmieniało urządzenie z nadrzędnego ("władca") na podrzędne ("niewolnik") lub w tryb automatyczny ("cable select").

Już się zaczyna...
https://www.dobreprogramy.pl/Scalaki-SPI-bez-master-i-slave.-Tak-chodzi-oczywiscie-o-walke-z-rasizmem,News,108657.html
