### ISSUE TITLE
esarena.eu

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16500]
### 1) niby strona zakończyła działalność: 

> Uprzejmie informujemy, iż z dniem 31.01 strona ESARENA zakończyła funkcjonowanie. Więcej informacji znajdziecie na naszym Facebooku.

### 2) ale coś tam jednak na niej jeszcze jest, w tym na pewno anty-adblock (baobab):

![capture_235_09-06-2020_19-59-53](https://user-images.githubusercontent.com/63287518/84183954-da219a00-aa8c-11ea-80e0-025d4a4a4c43.gif)

### 3) czasem też strona nie chce się załadować:

![capture_236_09-06-2020_20-05-10](https://user-images.githubusercontent.com/63287518/84183988-e4dc2f00-aa8c-11ea-9c4f-8ceb8970ebbc.gif)

**Comment by hawkeye116477** [comment]
Skora zakończyła funkcjonowanie, to po co im te nagrody...
