### ISSUE TITLE
laczynaspilka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#16503]
test link:
https://www.laczynaspilka.pl/biblioteka/multimedia/index/wideoteka

**Comment by hawkeye116477** [comment]
@krystian3w Do zbadania, czy dla zalogowanych coś się popsuje po ukryciu...

**Comment by xxcriticxx** [comment]
@hawkeye116477 negative

**Comment by krystian3w** [comment]
Jak dla mnie to najlepiej piec "local storage" czyli wymagamy osobnego dodatku:

`laczynaspilka.pl(addToStorage, gdpr_accepted, true)`

Jak uBO zaakceptuje te zgłoszenie, to możemy wycofać pieczenie "local storage": https://github.com/uBlockOrigin/uBlock-issues/issues/382

```
#$#body[style*="hidden"]:not(:has(.modal--standardTop.modal)) { overflow: visible !important; }
```

oczywiście wtedy problemem będzie dopisywanie `:not(:has(...))` lub przecinka w has:
```
:not(:has(.modal--standardTop.modal, .player--standardTop.modal))
```

**Comment by xxcriticxx** [comment]
@
