### ISSUE TITLE
WordPress na celowniku

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#16502]
Coś dla @MajkiIT 

> Hakerzy pod koniec maja przeprowadzili zmasowane ataki na strony internetowe wykorzystujące niezwykle popularny CMS. Napastnicy próbowali wykraść wrażliwe dane: pliki konfiguracyjne oraz informacje potrzebne do logowania do baz danych. 

https://www.instalki.pl/aktualnosci/bezpieczenstwo/42281-wordpress-atak-wlamanie.html

**Comment by MajkiIT** [comment]
@hawkeye116477 Dzięki
