### ISSUE TITLE
tarnowska.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#16505]
reklama + adblock 

Drogi użytkowniku!
Wykryliśmy, że korzystasz z programu blokującego reklamy w przeglądarce (AdBlock lub inny).
Dzięki reklamom oglądasz nasz serwis za darmo.

Prosimy, wyłącz ten program i odśwież stronę.

test link:
https://www.tarnowska.tv/wiadomosci/5982,xxv-miedzynarodowy-turniej-rycerski-w-debnie-przelozony-na-2021-rok

**Comment by gargul2** [comment]
Dodać domenę [>> TUTAJ 1 <<](https://github.com/olegwukr/polish-privacy-filters/blob/c9af959ee56f497174a8aed7e60f519a83840f34/anti-adblock.txt#L70-L78 ) oraz jako, że to podobny przypadek jak https://github.com/MajkiIT/polish-ads-filter/issues/16410#issuecomment-633231385 więc trzeba też domenę dodać [>> TUTAJ 2 <<](https://github.com/olegwukr/polish-privacy-filters/blob/c9af959ee56f497174a8aed7e60f519a83840f34/anti-adblock.txt#L449) z tym że o ile w przypadku tamtego podobnego przypadku przepuszczenie FAB nie wywołało skutków ubocznych, to w tym przypadku uwalony zostaje filmik po lewej, czyli kosztem naprawy jednego filmu, uwala się drugi:

![capture_079_13-06-2020_18-15-50](https://user-images.githubusercontent.com/63287518/84574390-6b9f4d80-ada6-11ea-826e-b83a0eb9bfb8.gif)
