### ISSUE TITLE
bgzoptima.pl

### ISSUE THREAD

**Issue by Lukjan37** [MajkiIT/polish-ads-filter#16516]
po zalogowaniu na konto, nie mozna otworzyc tresc wiadomosci w zakladce wiadomosci

**Comment by hawkeye116477** [comment]
@Lukjan37 A dlaczego nie oznaczone etykietą? Powinieneś wybrać formularz „błąd". Zamknij zgłoszenie i otwórz ponownie :stuck_out_tongue:

**Comment by Lukjan37** [comment]
aha, dobra.

**Comment by xxcriticxx** [comment]
@Lukjan37 proszę podaj konto testowe

**Comment by hawkeye116477** [comment]
Do banku pewnie raczej nie będzie chciał, bo mu jeszcze kasę zabiorą. Tak więc jeżeli nikt kto się zna na adblockerach nie ma tam konta, to raczej do zamknięcia.

**Comment by xxcriticxx** [comment]
@Lukjan37 sorry nie wiedzialem ze to bank

**Comment by Lukjan37** [comment]
> Do banku pewnie raczej nie będzie chciał, bo mu jeszcze kasę zabiorą. Tak więc jeżeli nikt kto się zna na adblockerach nie ma tam konta, to raczej do zamknięcia, a jemu pozostanie po prostu wyłączeniu adblockera dla tej strony.

aha, czyli musze dodac do wyjatkow?

**Comment by gargul2** [comment]
Biedny Lukjan37,  już kiedyś miał problem https://github.com/MajkiIT/polish-ads-filter/issues/3766, teraz znowu coś się dzieje ze stroną, może wyczyszczenie cache & ciasteczek https://github.com/MajkiIT/polish-ads-filter/issues/3766#issuecomment-331692274 znowu zadziała.

Lukjan37 najlepiej byłoby gdybyś chociaż zorientował się która lista powoduje błąd, wyłaczając jedną po drugiej i sprawdzając za każdym razem czy błąd ustąpił, wtedy wystarczyłoby wyłączyć tylko tę listę, zamiast całego adblockera, dzięki czemu nie powyskakują ci reklamy, no i było by wiadomo, która lista powoduje, a wtedy może byśmy namierzyli filtr odpowiedzialny za błąd.

**Comment by Lukjan37** [comment]
tamtem problem byl inny, niz ten.

**Comment by krystian3w** [comment]
Mają opcję darmowego konta do śmierci i rejestracja przy pomocy selfie bez konferencji?

**Comment by krystian3w** [comment]
Strzał w ciemno:

```
bgzoptima.pl#@#.popup:has(.popup-contact__item + .popup-contact__item + .popup-contact__item)
```

**Comment by krystian3w** [comment]
Jak to ten w/w naprawia to po 20 sprawdź czy taki blokuje pocztę Banku:

`bgzoptima.pl##.home .popup:has(.popup-contact__item + .popup-contact__item + .popup-contact__item)`

**Comment by Lukjan37** [comment]
ok, oby

**Comment by gargul2** [comment]
> 
> 
> Strzał w ciemno:
> 
> ```
> bgzoptima.pl#@#.popup:has(.popup-contact__item + .popup-contact__item + .popup-contact__item)
> ```

Też o tym pomyślałem, jeszcze zanim o tym napisałeś, bo ostatnio coś było dodawane odnośnie mojego zgłoszenia https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1911 więc czasowo by się zgadzało, błąd pojawił się niedługo po naprawie tamtego zgłoszenia, ale po chwili pomyślałem sobie, że nie będę bawił się szklaną kulą jak hawkeye, bo tak na prawdę to może być tylko zbieg okoliczności, ale chętnie popatrzę z boku, czy podana wróżba się spełni.

**Comment by hawkeye116477** [comment]
> to po 20 sprawdź czy taki blokuje pocztę Banku

Dlaczego akurat po 20? Sam może przecież wpisać i sprawdzić :smile:

**Comment by Lukjan37** [comment]
ja skasowalem te wiadomosci

**Comment by gargul2** [comment]
Hahaha, i z wróżbitów też można się pośmiać, bo wróżba się nie spełniła.

**Comment by Lukjan37** [comment]
dziala, prosze dodac

**Comment by krystian3w** [comment]
Filtr już jest w nowej wersji:

`bgzoptima.pl##.home .popup:has(.popup-contact__item + .popup-contact__item + .popup-contact__item)`

Jak nie usunąłeś znowu za szybko to zaktualizuj ręcznie `Polskie filtry elementów irytujących`.

Jak dalej będzie psuć, to trzeba przebudować "`has`" na jeszcze coś innego, skoro pop-up z Wiadomościami banku ma jakieś 3 boxy kontaktowe obok siebie.

**Comment by Lukjan37** [comment]
dobra, dzieki. bede tutaj pisal, jakby co.

**Comment by gargul2** [comment]
> https://github.com/MajkiIT/polish-ads-filter/issues/16516#issuecomment-643799724 : Lukjan37 : ja skasowalem te wiadomosci

Nie wiadomo o co w tym patologicznym komentarzu chodziło Lukjanowi:
- pierwsze znaczenie: czy chodziło mu o to, że całe to zgłoszenie jest pomyłką, bo wiadomości mu się nie wyświetlały dlatego bo sam je skasował
- drugie znaczenie: czy chodziło mu o to, że skasował ostatnie wiadomości i przez to nie może sprawdzić czy filtr zadziała, bo nawet gdyby zadziałał to niemiałyby jakie wiadomości się wyświetlić, żeby to potwierdzić

Więc żeby nie wyjść na głupka, i nie odczytać źle jego patologicznego komentarza, chciałem się nie odzywać, do momentu kiedy będzie wiadomo, o co Lukjanowi chodziło.

No i zauważyłem pod komentarzem Lukjana emotki:
- hawkeye116477 dał temu komentarzowi łapkę w dół
- krystian3w dał temu komentarzowi uśmieszek

Widząc te emotki, wydawało się to jednoznaczne, że skoro jeden dał łapkę w dół, a drugi się śmieje, to znaczy, że Lukjanowi chodziło o to pierwsze znaczenie, no bo gdyby chodziło o to drguie znczenie, to raczej nie byłoby to powodem, że dawać łapkę w dół i się tak śmiać. Dlatego odebrałem te emotki jako potwierdzenie od hawkeye i krystiana, że Lukjanowi chodziło o to pierwsze znaczenie, zwłaszcza, że komentarz Lukjana brzmiał jak przyznawanie siędo winy.

Nagle Lukjan odezwał się, i napisał komentarz, z którego wynika, że chodziło mu jednak o to drugie znaczenie. I co teraz? Poza tym, że jest to dowodem na to, że wcześniejszy komentarz Lukjana był patologicznie niejednoznaczny, jest to również dowodem na to, że hawkeye i krystian się pomylili w jego ocenie, a ja zawierzając tej ocenie, zostałem wsadzony na minę. I nie byłoby to dla mnie problemem, gdyby nie to, że hawkeye dał mi łapkę w dół, za co? Za to, że sam się pomylił? To raczej sobie powinien dać łapkę w dół, a tych których wprowadził w błąd powinien przeprosić. Ale ten typ tak ma, że zawsze bezczelnie odwraca kota ogonem, i zwala winę na innych, i z innych próbuje zrobić głupka, to u niego norma, no chyba, że zaraz zacznie wciskać kit, że dał łapkę w dół dla Lukjana, za to, że Lukjanowi skasowały się ostatnie wiadomości, tylko kto w to uwierzy....co ten hawkeye odwala to nie wiem...

**Comment by Lukjan37** [comment]
bardzo smieszne, mi chodzilo, oto, ze wiadomosci sie nie pokazywaly.

**Comment by gargul2** [comment]
I tak nie wiadamo o co tobie chodzi, piszesz niejasno..., ale akurat bardziej do hawkeyea pisałem niż do ciebie.

**Comment by Lukjan37** [comment]
aha, dobra.

**Comment by hawkeye116477** [comment]
> Za to, że sam się pomylił?
> To raczej sobie powinien dać łapkę w dół, a tych których wprowadził w błąd powinien przeprosić.

Nic się nie pomyliłem, po prostu trochę nie spodobało mi się, że skasował te wiadomości wcześniej, przez to nie mógł potem sprawdzić czy działa.  Po za tym, ale wielki problem, z powodu tych paru łapek w dół świat się zawalił?

**Comment by gargul2** [comment]
> Nic się nie pomyliłem, po prostu trochę nie spodobało mi się, że skasował te wiadomości wcześniej, przez to nie mógł potem sprawdzić czy działa, choć jednak ostatecznie sprawdzone. 

No tłumacz się tłumacz, niedługo będziesz łapki w dół dawał za literówki, błędy ort. itp. nie przeszło mi przez myśl, że mogłeś mu za takie coś łapkę w dół dać, w szczególności wiedząc, że nie jest ekspertem komputerowym i raczej potrzebuje wsparcia niż łapek w dół, zwłaszcza, że wydaje się sympatyczny, więc uznałem, że dałeś mu za to, że chodziło mu o to, że całe zgłoszenie jest trefne i nie ma błędu, a wiadomości mu się nie ładują, bo sobie je pokasował, jeszcze przed założeniem zgłoszenia. Więc mój komentarz ze śmiechem, jest nie tyle moim błędem, co tym, że przejechałem się na twoim zachowaniu, którego bym się po tobie nie spodziewał, i które wsadziło mnie na minę...więc może jednak zdejmiesz tę swoją łapkę w dół, skoro już ci wytłumaczyłem, że moje zachowanie (komentarz ze śmiechem) wynikło z twojego zachowania, które mylnie zasugerowało mi, że Lukjan pokasował komentarze już przed założeniem wątku i że cały wątek jest trefny, ewentualnie możesz uznać, że byłem głupi bo nie dopuściłem sytuacji, że mogłeś dać Lukjanowi łapkę w dół za taki duperel, ale to traczej inny rodzaj głupoty niż typowa głupota, ale wtedy ja będę musiał uznać tak samo, że ty też byłeś głupi, bo nie założyłeś, że ja nie założyłem, że mogłeś Lukjanowi dać łapkę w dół za duperel i też ci dam za to łapkę w dół - a w zasadzie już dałem, więc jak chcesz żebym ci ją zdjął to ty mi też zdejmij, bo albo jesteśmy obydwoje głupi i zasługujemy na łapki w dół, albo nikt nie jest głupi i nie zasługuje na łapki w dół, nie będzie tak, że ty będziesz mądry, aze mnie zrobisz głupka, bo sytuacja wcale taka nie była.

>  Po za tym, ale wielki problem, z powodu tych paru łapek w dół świat się zawalił?

A jakbyś ich nie dał to też bylby wielki problem i by się świat zawalił? Jak wyżej napisałem, Lukjanowi dałeś za byle co, a mi nieadekwatnie do sytuacji.

**Comment by hawkeye116477** [comment]
@gargul2 Rozumiem, jakbym coś powiedział obraźliwego to można byłoby mieć pretensje, ale że wstawiłem jedną emotkę i od razu wielki szum? Czepiasz się jakby ciebie cała armia atakowała, wyluzuj trochę :stuck_out_tongue:

**Comment by gargul2** [comment]
O hawkeye zamiast zdjać mi łapkę w dół, dołożył mi kolejną, hehe, krystian też by mi dołożył, gdyby nie to że nie może, bo go zablokowałem, a tylko dlatego, bo on mnie pierwszy zablokował, co mnie zdziwiło.
