### ISSUE TITLE
www.efilmy.tv

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1651]
Po ostatniej aktualizacji filtrów w uBlock orygin nie można odtwarzać filmów na http://www.efilmy.tv/.

**Comment by F4z** [comment]
Usunąłem regułę, która sprawiała problem.
Już powinno być ok.

**Comment by xxcriticxx** [comment]
to gloszenie z fb?

**Comment by F4z** [comment]
http://www.certyficate.it/polski-filtr-adblock/#comment-16137

**Comment by MajkiIT** [comment]
@F4z dziękuję.
