### ISSUE TITLE
telewizjattm.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#16512]
test link:
https://telewizjattm.pl/dzien/2020-06-12/53560-mlody-chlopak-wypadl-z-okna-w-wejherowie.html?play=on

![Capture](https://user-images.githubusercontent.com/15007183/84574517-f6ffeb00-ad74-11ea-8b8b-b745791e1e69.JPG)

**Comment by gargul2** [comment]
Na anty-adblock dodajemy domenę [>> TUTAJ <<](https://github.com/olegwukr/polish-privacy-filters/blob/c9af959ee56f497174a8aed7e60f519a83840f34/anti-adblock.txt#L181)

No i jeszcze na stronie jest także reklama, któa mnie przekierowała na https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2110

**Comment by MajkiIT** [comment]
`telewizjattm.pl##.banner-main-page`
