### ISSUE TITLE
youtube.pl

### ISSUE THREAD

**Issue by Tasiorsa** [MajkiIT/polish-ads-filter#16526]
### Zrzut ekranu 
![yout](https://user-images.githubusercontent.com/35109319/84832019-bc27dc80-b02c-11ea-8172-3693f685c9fc.jpg)

### Link bezpośredni 

https://www.youtube.com/watch?v=ODxvPmU84qA (przykładowy link)

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
Pojawia się reklama przed każdym filmem na Youtube. Odlicza klepsydra czas i mamy przycisk Pomiń Reklamy.

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Firefox 77.0.1 x64

**Rozszerzenia i skrypty:** 
Adguard
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Wszystkie POLSKIE filtry do adguard

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by hawkeye116477** [comment]
No to chyba jakiś problem po stronie AG. YouTube jest stroną międzynarodową, więc może lepiej zawołamy @AdamWr, uBO ma regułę `youtube.com##+js(json-prune, playerResponse.adPlacements playerResponse.playerAds adPlacements playerAds)`, może jakiś odpowiednik dla AG przydałby się.

**Comment by AdamWr** [comment]
U części użytkowników YouTube testuje "nowe" reklamy i są one wyświetlane niezależnie od posiadanego blokera reklam, tutaj przykład - `https://github.com/AdguardTeam/AdguardFilters/issues/57483#issuecomment-645217023`
Niestety nie udało mi się jeszcze ich odtworzyć.

@Tasiorsa Możesz proszę włączyć w ustawieniach AdGuarda "Eksperymentalny filtr AdGuard", zaktualizować filtry, a następnie sprawdzić, czy te reklamy nadal się pojawiają?

**Comment by Tasiorsa** [comment]
Wlaczylem eksperymentalny filt w ADGuard - zaktualizowałem i jest dobrze. Monit ze screena znikl - od razu rusza film :) Możecie to zaaplikować do zwyklych filtrów. Dzięki bardzo :)

**Comment by krystian3w** [comment]
`/sw.js`

?

**Comment by krystian3w** [comment]
> od razu rusza film :) Możecie to zaaplikować do zwyklych filtrów. Dzięki bardzo :)

No niestety nie; chyba że wykluczając uBO / Nano Adblocker: https://github.com/uBlockOrigin/uAssets/issues/7542


drugi filtr Eksperymentalny `skryptowy` pracuje inaczej z uBO lub źle testujesz:
 https://github.com/uBlockOrigin/uAssets/commit/9d7610baf1449021a2974b2569444a0374c4245f

@AdamWr musicie użyć krótkiej nazwy `set` by commit uBO nadpisywał, bo podobno długa nazwa `set-constant` pozwala użyć dezaktywowany filtr drugi raz.

**Comment by AdamWr** [comment]
>Możecie to zaaplikować do zwyklych filtrów.

Niestety na razie nie, z tego co wiem, to u niektórych użytkowników te reguły powodowały, że strona główna się nieprawidłowo wyświetlała albo filmy nie działały.

**Comment by Tasiorsa** [comment]
Ja zostawiam Eksperymentalny w AdGuard bo po prostu u mnie jest dobrze. Testowałem czyszcząc cache. Nic się złego nie dzieje

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/57483#issuecomment-645217023

**Comment by Tasiorsa** [comment]
Youtube pokombinowal cos i z wlaczonym Adguard nie ruszają filmy. Jest czarne tlo i kreci kółko

**Comment by krystian3w** [comment]
Dezaktywuj sobie filtr `set-constant`

```
 youtube.com#@%#//scriptlet("set-constant", "ytInitialPlayerResponse.adPlacements", "undefined") 
```

**Comment by Tasiorsa** [comment]
Dziękuje za poradę :)

**Comment by krystian3w** [comment]
w uBO to set-constant więcej psuło niż ubijało pre-roll ads.

**Comment by krystian3w** [comment]
A nie błąd z filmami robi mocna literówka:

```
||goog
```

fix jak nie umiesz uaktualnić AdGuard base:

```
||goog$badfilter
```
