### ISSUE TITLE
gala.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1652]
ad block

`http://www.gala.pl/galeria/stylowe-podsumowanie-roku-2013-natasza-urbanska/stylowe-podsumowanie-roku-2013-natasza-urbanska-102576`

![capture](https://cloud.githubusercontent.com/assets/15007183/21159297/b0302cc8-c14e-11e6-9a7e-7606cbaf6514.PNG)

**Comment by F4z** [comment]
`@@||gala.pl/bundles/burdacore/js/adv.js$script,domain=gala.pl`

**Comment by xxcriticxx** [comment]
dziala dobra regula
