### ISSUE TITLE
uniroyal.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#16522]
https://www.uniroyal.pl/samochod/opony-poradnik/jazda-i-bezpieczenstwo/jak-sprawdzic-glebokosc-bieznika-opony

blokada scrolla

**Comment by hawkeye116477** [comment]
Wygląd na to, że to chyba IDCAC psuje.

**Comment by gargul2** [comment]
Dla ciekawskich - Fanboy Cookies też psuje tak samo, fix też działa.

**Comment by kiboke** [comment]
@hawkeye116477 thanks, or: dzięki :)
