### ISSUE TITLE
sklep.pl.canalplus.com

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#16521]
### Zrzut ekranu 
![2020-06-16_15-23](https://user-images.githubusercontent.com/19818572/84779975-55330500-afe5-11ea-85f4-6f8cde9cc97d.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
`https://sklep.pl.canalplus.com/prepaid-mix/formularze-skrocone/sklep-platforma-canal-oferta-na-karte?pm_source=pl_canalplus&pm_medium=subpage_telewizja-na-karte&pm_content=button&pm_campaign=20012020&pm_term=kup-tnk`
Podaje, że oferta nie ma żadnych kanałów, mimo, że są. 
Problem powoduje EasyPrivacy i można go rozwiązać regułą => `@@/frosmo.easy.js$domain=sklep.pl.canalplus.com`

**Comment by krystian3w** [comment]
Nowo Zelnadczyk ani uAssets nie umie zreprodukować...

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/15756

**Comment by krystian3w** [comment]
https://github.com/NanoMeow/QuickReports/issues/3298

**Comment by hawkeye116477** [comment]
Może jakaś geoblokada jest, bo niby za granicą nie mogą korzystać...
