### ISSUE TITLE
magazynmotomi.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16537]
Reklama po prawej https://magazynmotomi.pl/2020/06/15/samochod-elektryczny-jezdzil-co-10-polak/:

![capture_022_17-06-2020_11-02-02](https://user-images.githubusercontent.com/63287518/84878393-0f7c4800-b08a-11ea-9b20-3348a2ca3a3e.png)

**Comment by MajkiIT** [comment]
```
magazynmotomi.pl###custom_html-5
magazynmotomi.pl###custom_html-3
```
