### ISSUE TITLE
bug social 

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1653]
Hello,

your filter "Polski social filtr" is causing a false positive over at amazon.de (probably amazon.com etc. too). You can find more details at:

https://forum.adguard.com/index.php?threads/amazon-de.17055/#post-116764

**Comment by xxcriticxx** [comment]
arrows work for me on `amazon.com`

![capture](https://cloud.githubusercontent.com/assets/15007183/21188340/0f70151e-c1e9-11e6-8afd-d1d92e513102.PNG)

**Comment by xxcriticxx** [comment]
zaszybko odpowiedzialem bo nie maialem dodanego social filtru jak dodalem strzalki sa biale ale dzialaja
