### ISSUE TITLE
warzywapolowe.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16538]
Dużo reklam:

### 1 Na wejściu reklama w popupie:

![capture_023_17-06-2020_11-03-28](https://user-images.githubusercontent.com/63287518/84879199-2ff8d200-b08b-11ea-8bff-16bd02c34084.png)

### 2 Dalej na stronie ta sama reklama wraz z innymi reklamami:

![capture_025_17-06-2020_11-06-17](https://user-images.githubusercontent.com/63287518/84879212-3424ef80-b08b-11ea-95fb-fee263d789fa.png)

![capture_024_17-06-2020_11-05-25](https://user-images.githubusercontent.com/63287518/84879220-36874980-b08b-11ea-8975-c2afc0584677.png)

**Comment by MajkiIT** [comment]
```
www.warzywapolowe.pl###spu-bg-22199
www.warzywapolowe.pl##.td_uid_12_5eea140a3f636_rand.vc_raw_html.td_block_wrap.wpb_wrapper > .td-fix-index
www.warzywapolowe.pl##.td-pb-span4.tdc-column.vc_column_container.wpb_column.td_uid_28_5eea140a47095_rand.vc_column
```

**Comment by gargul2** [comment]
```
www.warzywapolowe.pl##.td_uid_12_5eea140a3f636_rand.vc_raw_html.td_block_wrap.wpb_wrapper > .td-fix-index
www.warzywapolowe.pl##.td-pb-span4.tdc-column.vc_column_container.wpb_column.td_uid_28_5eea140a47095_rand.vc_column
www.warzywapolowe.pl##.td_uid_10_5eea140a3f58d_rand.vc_raw_html.td_block_wrap.wpb_wrapper
```

Te filtry do poprawki, bo `td_uid_12_5eea140a3f636_rand` to losowy ciąg znaków alfanumerycznych, wszedłem na stronę z tymi filtrami i reklamy są dalej bozostał wygenerowany nowy inny ciąg.

**Comment by gargul2** [comment]
Trzeba jeszcze poprawić, ponieważ dodany commit/filtr: 
`www.warzywapolowe.pl##.vc_raw_html.td_block_wrap.wpb_wrapper`
zastąpił 2 z 3 wcześniejszych:
```
www.warzywapolowe.pl##.td_uid_12_5eea140a3f636_rand.vc_raw_html.td_block_wrap.wpb_wrapper > .td-fix-index
www.warzywapolowe.pl##.td_uid_10_5eea140a3f58d_rand.vc_raw_html.td_block_wrap.wpb_wrapper
```

Ale nie zastąpił tego w środku:
`www.warzywapolowe.pl##.td-pb-span4.tdc-column.vc_column_container.wpb_column.td_uid_28_5eea140a47095_rand.vc_column`
bo on jest trochę inny, przez co jest jeszcze dużo reklam i trzeba go czymś innym zastąpić.

No i ta reklama co z popupu to jako zwykła reklama też jest (DELFIN WG).

**Comment by gargul2** [comment]
Ok, teraz jest gitara.
