### ISSUE TITLE
domowyprzedszkolak.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16536]
Duży pusty przeszkadzający kontener po reklamie:

![capture_018_17-06-2020_10-52-36](https://user-images.githubusercontent.com/63287518/84877415-c37cd380-b088-11ea-8238-25ac0aaf3a82.png)

**Comment by MajkiIT** [comment]
`www.domowyprzedszkolak.pl##section.style-two.enroll-area`
