### ISSUE TITLE
matma.net.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16535]
Do czego to doszło:

![](http://i.wp.pl/a/i/wp_hit/wphit_100x100.gif)

![capture_016_17-06-2020_10-46-00](https://user-images.githubusercontent.com/63287518/84876897-15712980-b088-11ea-8296-fc323ed443a6.png)

**Comment by MajkiIT** [comment]
ale to jakiś stary sztrucel :D

**Comment by gargul2** [comment]
A no faktycznie, to jakiś stary zgniły kartofel, który 100 lat temu był tu gdzieś zgłaszany :)

**Comment by gargul2** [comment]
A tu kolejny: https://diablo2.pl/

![](http://i.wp.pl/a/i/wp_hit/wphit_200x40.gif)

![capture_016_18-06-2020_17-27-20](https://user-images.githubusercontent.com/63287518/85040486-26559400-b189-11ea-8914-734f4adc3bea.png)
