### ISSUE TITLE
super-nowa.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16542]
Reopen mojego starego zgłoszenia z zeszłego roku https://github.com/MajkiIT/polish-ads-filter/issues/11668 bo znowu wysypało te resztki po całej stronie:

![capture_037_17-06-2020_13-33-22](https://user-images.githubusercontent.com/63287518/84893427-8112c100-b09f-11ea-8fb7-6a861105c2d0.png)

![capture_038_17-06-2020_13-34-07](https://user-images.githubusercontent.com/63287518/84893542-b3bcb980-b09f-11ea-94f2-a6026f5c5c04.png)

![capture_039_17-06-2020_13-34-10](https://user-images.githubusercontent.com/63287518/84893550-b61f1380-b09f-11ea-81a6-2b0eefbb9104.png)

![capture_040_17-06-2020_13-34-15](https://user-images.githubusercontent.com/63287518/84893558-b8816d80-b09f-11ea-9881-7388d8ee9b8d.png)

**Comment by MajkiIT** [comment]
```
www.super-nowa.pl##.col-md-9
www.super-nowa.pl##.col-md-3
www.super-nowa.pl##.col-lg-12 > .row > .col-lg-9:-abp-contains(r e k l a m a)
www.super-nowa.pl##div.row > div.col-md-6:-abp-contains(reklama)
||placehold.it^$image
```

**Comment by gargul2** [comment]
Jedna resztka się ostała:

![capture_056_22-06-2020_11-27-26](https://user-images.githubusercontent.com/63287518/85271707-711e2700-b47b-11ea-98cc-3f2427cebb59.png)
