### ISSUE TITLE
czaskultury.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16544]
Jakaś resztka po reklamie:

![capture_042_17-06-2020_13-58-56](https://user-images.githubusercontent.com/63287518/84895644-eae09a00-b0a2-11ea-8975-8ff4d4140248.png)

**Comment by MajkiIT** [comment]
`##div.row > .col-md-12 > .line-header > span:-abp-contains(Reklama)`
