### ISSUE TITLE
mojprzepisna.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16540]
Reklama na dole po prawej:

![capture_031_17-06-2020_12-56-49](https://user-images.githubusercontent.com/63287518/84890020-1c089c80-b09a-11ea-9a5b-f5682216fc01.png)

**Comment by xxcriticxx** [comment]
@gargul2 nie masz listy na cookies?

**Comment by gargul2** [comment]
Kiedyś zawsze używałem, ale od jakiegoś czasu nie używam, ale ok - włączę! Włączone! Więc jak będzie cookies na zrzucie ekranu to są też cookies do zablokowania!

**Comment by MajkiIT** [comment]
`###text-20`
