### ISSUE TITLE
telewizja.lukow.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16556]
Dużo reklam

### 1  Na głównej - u góry i po prawej:

![Schowek01](https://user-images.githubusercontent.com/63287518/84996413-862e4980-b14d-11ea-8099-ff05520bfee3.gif)

### 2 W artykułach po prawej miejsce na reklamę niby ty tego nie blokujesz, ale to tak samo przeszkadza jak reklama (zrobisz co zechcesz): http://telewizja.lukow.pl/2020/06/17/nagrody-dla-recytatorow-z-lok/

![Schowek01](https://user-images.githubusercontent.com/63287518/84996942-38fea780-b14e-11ea-848a-3f1bbf368203.gif)

**Comment by MajkiIT** [comment]
`telewizja.lukow.pl###frontpage-area_g > .hgrid, #frontpage-area_a_3, #frontpage-area_b_2, #media_image-3, ##media_image-4`

**Comment by gargul2** [comment]
Jest ok.
