### ISSUE TITLE
goral.info.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16552]
https://goral.info.pl/samochody-terenowe-zniszczyly-laki-w-chocholowie-i-cichem/
![2020-06-17 20 19 01 goral info pl 94a1856ef68a](https://user-images.githubusercontent.com/36385327/84934635-e682a400-b0d7-11ea-88ac-bf2ed2884540.png)

**Comment by gargul2** [comment]
Ciekawostka, z włączoną EasyList Polish tych reklam nie ma, więc można (co nie znaczy od razu, że trzeba) stamtąd wziąć filtry.

**Comment by MajkiIT** [comment]
`##.g`

**Comment by gargul2** [comment]
U góry został pusty szary kontener / pasek po reklamie: `###sticky-footer-adv`

![capture_012_18-06-2020_08-56-57](https://user-images.githubusercontent.com/63287518/84989772-765e3780-b144-11ea-8ecc-5c3e4bd47ffe.png)
