### ISSUE TITLE
Zdezaktualizowany mirroring

### ISSUE THREAD

**Issue by bug-rules** [MajkiIT/polish-ads-filter#16557]
#13967 / #7361 

```
https://ext-update.avgbrowser.com/adblock/assets/regions/POL-0.txt
https://ext-update.avgbrowser.com/adblock/assets/regions/POL-2.txt
```
```
https://ext-update.avastbrowser.com/adblock/assets/regions/POL-0.txt
https://ext-update.avastbrowser.com/adblock/assets/regions/POL-2.txt
```

w efekcie jak coś lista psuje, to już przynajmniej 3 miesiące, jak coś nie wycina to też od 3 miesięcy.

**Comment by MajkiIT** [comment]
@xxcriticxx idealnie idzie to w termin COVIDa ... może kopiowali ręcznie

**Comment by xxcriticxx** [comment]
@MajkiIT ?

**Comment by MajkiIT** [comment]
@xxcriticxx przestali aktualizować pliki 15 marca 2020 .... jakby wirus ich wyhamował.

**Comment by xxcriticxx** [comment]
admin jest na pewno kwarantannie
