### ISSUE TITLE
wysokieobcasy.pl (reopen)

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16559]
Reopen bo https://github.com/MajkiIT/polish-ads-filter/issues/16547#issuecomment-645961626

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/2c8dda20f4c1a11ac1e04f129dc7672c100bfec0#diff-6de60f294b8bd23c752f8fcbece875b1

**Comment by gargul2** [comment]
Dalej źle, bo zamiast dodać domenę do istniejacego filtru-wyjątku, filtr-wyjątek został zduplikowany, a domeny dalej nie ma dodanej.
