### ISSUE TITLE
forumhurtowe.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16567]
### 1 Ogromny pusty kontener po reklamie na cały ekran (po źle załadowanej reklamie, mają literówkę - brak TLD w domenie w url do obrazka):

![capture_008_18-06-2020_15-22-44](https://user-images.githubusercontent.com/63287518/85025544-d15d5200-b177-11ea-8f93-4b757e503d05.png)

### 2 Reklamy na dole:

![capture_009_18-06-2020_15-22-51](https://user-images.githubusercontent.com/63287518/85025564-d6ba9c80-b177-11ea-9485-8ac27e05d0f8.png)

**Comment by MajkiIT** [comment]
`###coface, .ad728-wrapper`
