### ISSUE TITLE
comtv.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16563]
Dużo reklam:

![Schowek01](https://user-images.githubusercontent.com/63287518/85022680-ec2dc780-b173-11ea-92f7-51ad5e434739.gif)

**Comment by MajkiIT** [comment]
`##div.prawe1`

**Comment by gargul2** [comment]
Jedna reklama się ostała:

![capture_054_22-06-2020_11-16-48](https://user-images.githubusercontent.com/63287518/85270761-13d5a600-b47a-11ea-872c-143e14899c28.png)
