### ISSUE TITLE
tworzywa.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16568]
Cała strona w reklamach:

![Schowek01](https://user-images.githubusercontent.com/63287518/85027203-f0f57a00-b179-11ea-8e6d-84e94c9c6a96.gif)

**Comment by MajkiIT** [comment]
```
www.tworzywa.pl##.ban, #block-234, #block-231, #block-188, #bloki_5 > .containeriframe, #block-217, #block-225 > .header-block, #block-189, #block-195, #block-109 > .header-block, #block-191, .zd
||www.tworzywa.pl/gfx/tworzywa/userfiles/_public/$image
```

**Comment by gargul4** [comment]
@MajkiIT odbanuj mi gargul2, już nie będę wrzucał za dużo zgłoszeń, bo gdybym miał wrzucać dalej, to nie pytałbym o odbanowanie, tylko wrzucał...
