### ISSUE TITLE
pytanie

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1656]
@MajkiIT jak dobrze znasz sie na ubuntu 16.04?

@F4z znamy sie troche na ubuntu? specialisty szukam

**Comment by MajkiIT** [comment]
@xxcriticxx No coś tam umiem. Głównie ubuntu serwer ale to podobne.

**Comment by xxcriticxx** [comment]
mam kilka blendow i konsole mi sie auto crashuje mam problemy x11 tez i jakim geolock czy cos takiego

**Comment by MajkiIT** [comment]
to świeża instalacja, czy od niedawna tak Ci się dzieje?
jakieś logi?

**Comment by xxcriticxx** [comment]
dzisaj wieczorem

**Comment by xxcriticxx** [comment]
@MajkiIT `http://pastebin.com/9hw2GZ6y`

**Comment by MajkiIT** [comment]
@xxcriticxx ale to nowa instalacja czy stara i się popsuło?

**Comment by MajkiIT** [comment]
to błąd Wine na Linux

**Comment by xxcriticxx** [comment]
jak mam zmienic uzytkownika na root?

**Comment by MajkiIT** [comment]
na Ubuntu 1 użytkownik w systemie ma uprawnienia sudo. Wchodzisz w terminalu na usera a potem sudo su <enter> i hasło do usera .

**Comment by xxcriticxx** [comment]
to wiem ale tam hyba cox w x11 config trzeba zmienic

**Comment by MajkiIT** [comment]
http://linuxporady.pl/otwieranie-nowego-okienka-konsoli-przelaczanie-sie-pomiedzy-terminalami/

**Comment by xxcriticxx** [comment]
wtym problem ze konsol mi auto crashuje i sie auto zamyka musze uzywac xterm

**Comment by xxcriticxx** [comment]
i niewiem co to jest te username geoclue

**Comment by MajkiIT** [comment]
http://askubuntu.com/questions/142581/is-ubuntu-geoip-geoclue-used-for-tracking

**Comment by xxcriticxx** [comment]
zrobie hyba format na tym laptopie i jeszcze raz zamontuje ubuntu

**Comment by MajkiIT** [comment]
@F4z to twoje?
https://www.youtube.com/watch?v=WSQGKj91GHY

**Comment by F4z** [comment]
@MajkiIT tak.
