### ISSUE TITLE
mojewronki.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16576]
http://mojewronki.pl/2020/06/mieszkanka-powiatu-jednak-nie-ma-koronawirusa/

![capture_012_18-06-2020_17-15-46](https://user-images.githubusercontent.com/63287518/85038959-7fbcc380-b187-11ea-9909-f9b91f8b89e4.png)

**Comment by MajkiIT** [comment]
`###media_image-9`
