### ISSUE TITLE
sushi-shop.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16577]
![capture_013_18-06-2020_17-18-33](https://user-images.githubusercontent.com/63287518/85039255-d3c7a800-b187-11ea-8573-a360dc212008.png)

**Comment by MajkiIT** [comment]
```
sushi-shop.pl##li.AnimacjaMieszana
sushi-shop.pl###BanneryAnimacjaMieszanaPrzyciski
```
