### ISSUE TITLE
Ciasteczkowa lista

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1657]
W ostatniej aktualizacji jest kilka niepoprawnych reguł i trochę więcej niż kilka duplikatów.

Na przykład.
Niepoprawna reguła - `ciam.pl###privacy, .privacy, #mainPrivacyDiv, .privacyTop,`
Poprawiona - `ciam.pl###privacy-info`

Tak sobie patrzyłem i zastanawiam się, gdzie ta reguła coś zmienia? - `cinema-city.pl##.policy, #policy, .cpolicy`

Ta reguła jest niepoprawna - `coi.pl##.alert-info, .alert-warning, .alert-box.com.pl###wrap`
Na liście jest już reguła, która ukrywa komunikat o ciasteczkach na tej stronie - `##.alert-sm.alert-warning.alert`

Ta reguła - `cyanmod.pl##.cm-message, .ipsfocus_globalMessage`
pokrywa się z tą - `cyanmod.pl##.cm-show.cm-message`
nie widzę żadnego elementu na stronie jak - `ipsfocus_globalMessage`
więc reguła, która już była na liście wystarczy.
Chyba, że się mylę, ale to wtedy przydałaby się informacja, gdzie tego elementu szukać.

Nie widzę żeby ta reguła - `czescidobmw.pl###container > div[onclick]` coś ukrywała na stronie.
Komunikat o ciasteczkach jest ukrywany przez te reguły:
`##div[class*="cookie"]`
`##[id^="cookies-message"]`
`##:not(input)[id*="cookie"]`

Ta reguła działa - `dacter.pl###topbar, #topBar, .topbarBox, .topBarMessage, #__topBar, #top_bar` ale czy nie wystarczyłoby coś takiego? - `dacter.pl###topbar`

Lista niepoprawnych reguł.
```
ciam.pl###privacy, .privacy, #mainPrivacyDiv, .privacyTop,
coi.pl##.alert-info, .alert-warning, .alert-box.com.pl###wrap
dpd.com.pl###quickNav +
dzidziusiowo.pl##body > div:not([id]):not([class])[style*="position"][style*="fixed"], body >
ekskluzywna.pl###topInfoContainer0, #topInfoContainer1, #topInfoContainer1Mask,
epapierosylodz.pl###topInfoContainer0, #topInfoContainer1, #topInfoContainer1Mask,
fellow.pl##body > div:not([id]):not([class])[style*="position"][style*="fixed"], body >
filmowonline.pl###topInfoContainer0, #topInfoContainer1, #topInfoContainer1Mask,
fora.pl##body > div:not([id]):not([class])[style*="position"][style*="fixed"], body >
geovita.pl###privacy, .privacy, #mainPrivacyDiv, .privacyTop,
gg.pl##body > div:not([id]):not([class])[style*="position"][style*="fixed"], body >
google.pl###epbar, #cnsh, #pushdown, #consent-bump, div[data-ved="0CAEQ_EE"],
herba-farm.pl###topInfoContainer0, #topInfoContainer1, #topInfoContainer1Mask,
ingservicespolska.pl###privacy, .privacy, #mainPrivacyDiv, .privacyTop,
negrasport.pl###topInfoContainer0, #topInfoContainer1, #topInfoContainer1Mask,
sfinks.org.pl##body > div:not([id]):not([class])[style*="position"][style*="fixed"], body >
skrypt.com.pl###topInfoContainer0, #topInfoContainer1, #topInfoContainer1Mask,
v10.pl##body > div:not([id]):not([class])[style*="position"][style*="fixed"], body >
wiara.pl##body > div:not([id]):not([class])[style*="position"][style*="fixed"], body >
zaplo.pl##.notification, .Notification, .js-notification, .notifications-container, #notifications,
zmyslovezakupy.pl###topInfoContainer0, #topInfoContainer1, #topInfoContainer1Mask,
```

Tutaj można sprawdzić duplikaty i nieprawidłowe reguły - https://arestwo.org/famlam/redundantRuleChecker.html

Tyle, że trzeba wziąć pod uwagę, że część duplikatów może wynikać z innych reguł.
Na przykład to `vod.pl,onet.pl,komputerswiat.pl###cookieView has been made redundant by ###cookieView`
`vod.pl,onet.pl,komputerswiat.pl` trzeba było dodać oddzielnie, bo te strony wykrywały adblocka i reguła, która została dodana powoduje, że wszystkie ogólne kosmetyczne reguły na tych stronach są ignorowane.
Niestety ta strona nie pokaże wszystkich duplikatów, na przykład teraz na liście są dwie takie reguły:
`forumplay.pl###notices` i `forumplay.pl##li#navbar_notice_6` one się pokrywają i raczej wystarczyłaby jedna z nich.
Albo na stronie `fandemonium.pl`, ta reguła już była wcześniej - `fandemonium.pl##div[style="; color: #999; position: absolute; top: 0; right: 40px; text-align: center; background: #333; padding: 4px 0; margin-bottom: 5px; -webkit-border-bottom-right-radius: 8px; -webkit-border-bottom-left-radius: 8px; -moz-border-radius-bottomright: 8px; -moz-border-radius-bottomleft: 8px; border-bottom-right-radius: 8px; border-bottom-left-radius: 8px; font-size: 12px; -webkit-box-shadow: 2px 2px 3px 0px rgba(127, 127, 127, 0.4); box-shadow: 2px 2px 3px 0px rgba(127, 127, 127, 0.4);"]` i z tego co widzę, to cały czas działa. Teraz została dodana ta reguła - `fandemonium.pl##body > div:not([id]):not([class])` i ona też działa, ale moim zdaniem dwie reguły do tego samego nie są potrzebne.

Ogólnie przypadłoby się zrobić porządek na liście po ostatniej aktualizacji :)

**Comment by MajkiIT** [comment]
dzięki. Siądę do tego na spokojnie pewnie w sobotę. Tak się kończy robienie czegoś na szybko.

**Comment by xxcriticxx** [comment]
Może dodawaj `:not(body):not(html)` tak jak w "I don't care about cookies" tak jak gwarser pisal w #1619
