### ISSUE TITLE
extraswiecie.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16582]
http://extraswiecie.pl/wiadomosc/wypadki-kolo-nowego-i-w-tleniu-trzy-osoby-ranne-w-tym-jedna-ciezko

![capture_021_18-06-2020_20-19-41](https://user-images.githubusercontent.com/63287518/85057536-2bbed880-b1a1-11ea-81db-6e518319299b.png)

**Comment by MajkiIT** [comment]
`##.even.field-item > span > span`
