### ISSUE TITLE
spiswitryn.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16583]
![capture_023_18-06-2020_20-23-29](https://user-images.githubusercontent.com/63287518/85057910-a38d0300-b1a1-11ea-8c88-bb4e32f8f5b4.png)

**Comment by MajkiIT** [comment]
```
spiswitryn.pl##[src^="https://www.slubi.pro/banery/"]
spiswitryn.pl##h3:nth-of-type(3)
```
