### ISSUE TITLE
bitchute.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#16590]
### Co trzeba zrobić, aby pojawił się błąd?
1. wejść na karte odtwarzania
2. 
3. 

### Moja konfiguracja 
filtry społecznościowe

**Przeglądarka internetowa:** 
ff
**Rozszerzenia i skrypty:** 
uBlock Origin v1.27.11b4
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Brak polonizacji, brak wyjaśnienia co to "`wejść na karte odtwarzania`".

Nie widzę by filtry kosmetyczne ukrywały za dużo, playery działają.

**Comment by KonoromiHimaries** [comment]
u mnie nie wszystkie, ale wrzucenie na wh `@@.widget` pomaga

**Comment by krystian3w** [comment]
Ja nie mam w loggerze nic z `widget`, otwierasz jakieś wstydliwe widea to znajdź wersje uszkodzone z bajkami dla dzieci.

**Comment by krystian3w** [comment]
@gwarser możesz przeszukać frazą `.widget` na bazie `filterslists` jako filtr sieciowy (kosmetyczne trzeba jakoś odsiać, bo będzie z 300 FP)?

**Comment by gwarser** [comment]
>wrzucenie na wh `@@.widget` pomaga

Ale w ogóle wiadomo, że to `.widget` blokuje? Bo blokować może cokolwiek, a `@@.widget` po prostu pasuje do tego URLa.

>możesz przeszukać frazą `.widget`

To nie takie proste.

**Comment by KonoromiHimaries** [comment]
@gwarser tak, to ten skrypt.

**Comment by gwarser** [comment]
Ale blokujący filtr to `.widget`? Bo ten skrypt może być zablokowany też np. przez `tic/v116/js/th` i `@@.widget` też go odblokuje.

**Comment by krystian3w** [comment]
Zakładam że on w loggerze widzi `.widget` na ciemnoczerwono z pogrubieniem.

Ale widget nie musi być społecznościowy / socjalny a jak również:

* "funkcjonalny" 
* reklamowy
* anty-adblockowy
* irtytujący (np. push)

---

@KonoromiHimaries jak znajdziesz problematyczne wideo to otwórz logger (https://github.com/gorhill/uBlock/wiki/The-logger), odśwież kartę, kliknij w "blokowane":


`-- https://www.bitchute.com/static/v116/js/third-party/jquery.ui`**.widget**`.js`

i kliknij w niego i pokaże kto blokuje i najwyżej zostanie przeszukać czy ktoś nie "przyśmiałkował" na repozytorium EasyList?

**Comment by gwarser** [comment]
Nie znalazłem nic podobnego na razie - ściągam świeże listy.

**Comment by KonoromiHimaries** [comment]
![img](https://user-images.githubusercontent.com/5884000/85130301-f794f780-b234-11ea-90f0-6cfd5246af0d.png)

**Comment by krystian3w** [comment]
Nie umiem go znaleźć:

`##td[id*="LC"]:contains(/^.widget$/)` - może być otoczony przez spacje
`##td[id*="LC"]:contains(/.* $/)` - niby żadna linia nie ma dodatkowych spacji

Otwórz więc listę filtrów i przekopiuj jej numer np.:
```
! Version: 2020.6.16.0
! Last modified: Tue, 16 Jun 2020, 19:36 UTC+02
```

Niby jak istnieje to pewnie jakiś bug z `race condition` mi go odrzuca.

**Comment by gwarser** [comment]
@KonoromiHimaries to uBO dev? Może coś z parsowaniem się pochrzaniło.

**Comment by krystian3w** [comment]
Jeszcze jest opcja, że pobierałeś jakoś uszkodzoną wersję przez Errory 500 jakie były dzisiaj rano.

**Comment by krystian3w** [comment]
@gwarser to bug w dev RC zepsuło się "parsowanie"...

**Comment by krystian3w** [comment]
Mam, błąd po części w filtrach:

`csw.torun.pl#sidebar > .twinsbox > .widget`

**Comment by gargul2** [comment]
Hehe, też go znalazłem, ale uprzedziłeś mnie o kilkanaście sekund z komentarzem, ale teraz z kolei ja uprzedzę ciebie, bo znalazłem winowajcę, sprzed 5 miesięcy https://github.com/MajkiIT/polish-ads-filter/issues/15575 ==> https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/b29583587f1a4b123331127577e37a4d0aec5cb7 , ale bardziej powinniśmy obwiniać bug po stronie uBO, bo takie literówki zawsze parsował, a w uBO np. `1.27.11b10` już nie.
