### ISSUE TITLE
skibasport.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16591]
![Screenshot_2020-06-19 SkibaSport pl](https://user-images.githubusercontent.com/63287518/85123669-f2ca4680-b228-11ea-824a-19065b00d0f9.jpg)

**Comment by MajkiIT** [comment]
`skibasport.pl###link_1083, #link_927, #link_387, #link_97, #link_219, #link_57, #baner_92, #link_242, #link_1160, #link_1161, #link_339`
