### ISSUE TITLE
swieta.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1659]
mediaexpert produkty po prawej

`http://swieta.wp.pl/gotowanie/artykul/pasztet-z-kaczki`

**Comment by MajkiIT** [comment]
@xxcriticxx zerkniesz?

swieta.wp.pl##.article--enteries
swieta.wp.pl##a[href^="http://www.mediaexpert.pl/"]
swieta.wp.pl##SECTION + .section.section--bg-white.products--section

**Comment by xxcriticxx** [comment]
regula jest dobra mozna dodac
