### ISSUE TITLE
citymedia.waw.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16597]
![capture_037_19-06-2020_13-00-16](https://user-images.githubusercontent.com/63287518/85126029-ed6efb00-b22c-11ea-8827-e56bf2d9911a.png)

**Comment by MajkiIT** [comment]
@gargul2 poczekaj z tymi zgłoszeniami, bo to głupiego robota

**Comment by MajkiIT** [comment]
`##div.baner_ramka`
