### ISSUE TITLE
zadanie.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16609]
![capture_047_19-06-2020_17-30-48](https://user-images.githubusercontent.com/63287518/85150282-a267de80-b252-11ea-9fd4-60b44f75314a.png)

**Comment by gargul2** [comment]
### zgodnie z ABP, dodać domenę:

[>> TUTAJ  1a <<](https://github.com/olegwukr/polish-privacy-filters/blob/6d2eac5652ac862695e037caa4bc97d3a70da347/anti-adblock.txt#L43) i / lub [>> TUTAJ 1b <<](https://github.com/MajkiIT/polish-ads-filter/blob/0f3693a14ad7f7df86405d7cb9dde7c9232f7d80/polish-adblock-filters/adblock.txt#L241) **ORAZ**
[>> TUTAJ 2a <<](https://github.com/olegwukr/polish-privacy-filters/blob/6d2eac5652ac862695e037caa4bc97d3a70da347/anti-adblock.txt#L44) i / lub [>> TUTAJ 2b <<](https://github.com/olegwukr/polish-privacy-filters/blob/6d2eac5652ac862695e037caa4bc97d3a70da347/anti-adblock.txt#L166)

ale  wtedy wyskoczą puste kontenery:

<details not-open>
<summary>spoiler</summary>


![capture_048_19-06-2020_18-37-52](https://user-images.githubusercontent.com/63287518/85158091-a4369f80-b25c-11ea-93a6-65b42ea2364e.png)

</details>

### więc lepiej wybrać jedno z rozwiązań pod uBO:
dodać domenę [ >> TUTAJ 3 <<](https://github.com/MajkiIT/polish-ads-filter/blob/0f3693a14ad7f7df86405d7cb9dde7c9232f7d80/polish-adblock-filters/adblock_ublock.txt#L208-L210) **LUB**  `zadanie.pl##+js(nostif, .adblock_info, 1000)`

**Comment by MajkiIT** [comment]
@gargul2 to nie ja tylko @olegwukr 

```
zadanie.pl##div > .adsbygoogle
zadanie.pl##.adblock_text
zadanie.pl##.adblock_bg
```

**Comment by gargul2** [comment]
Acha, ok, bo wiesz... czort go wie kto tam zarządza..., zawsze sądziłem, że i tak to ty sterujesz z tylnego fotela jak "szeregowy poseł" kaczyński :)
