### ISSUE TITLE
twoja-czestochowa.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16621]
![capture_065_22-06-2020_11-58-22](https://user-images.githubusercontent.com/63287518/85274912-e0961580-b47f-11ea-9e9a-25fee960356f.png)

![capture_066_22-06-2020_11-58-34](https://user-images.githubusercontent.com/63287518/85274913-e1c74280-b47f-11ea-8264-29e07a25e634.png)

**Comment by MajkiIT** [comment]
@gargul2 zwolnij tempo

**Comment by xxcriticxx** [comment]
@gargul2 rekomenduje skladac wlasne PR
