### ISSUE TITLE
stalowemiasto.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1663]
prawa lewa strona

**Comment by F4z** [comment]
Może coś takiego:
`||stalowemiasto.pl/_reklamy/$image`
`||stalowemiasto.pl/colada2/_pliki/emisje/$object,image`
`stalowemiasto.pl##.main-cbaner`

**Comment by xxcriticxx** [comment]
dobre filtry
