### ISSUE TITLE
tradersarea.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16642]
Na głównej i w artykułach:

### Na głównej:
![capture_100_22-06-2020_17-03-21](https://user-images.githubusercontent.com/63287518/85303106-59aa6280-b4aa-11ea-96cf-f8dd30cf3268.png)

### W artykułach: https://tradersarea.pl/rpp-chce-slabszego-zlotego/
![capture_101_22-06-2020_17-04-21](https://user-images.githubusercontent.com/63287518/85303261-8a8a9780-b4aa-11ea-8363-a283f062df14.png)

**Comment by gargul3** [comment]
Na głównej i w artykułach:

na głównej
![capture_133_23-06-2020_14-26-19](https://user-images.githubusercontent.com/67320782/85403420-9daa6f80-b55d-11ea-89fa-51f5ab497cd3.png)


https://tradersarea.pl/rpp-chce-slabszego-zlotego/
![capture_132_23-06-2020_14-25-37](https://user-images.githubusercontent.com/67320782/85403342-75bb0c00-b55d-11ea-95a3-4a1730942a90.png)
