### ISSUE TITLE
lubin.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1664]
reklama

**Comment by F4z** [comment]
Mam nadzieję, że to zablokuje wszystkie reklamy:
`||lubin.pl/wp-content/themes/supernews-provider/adrotate_group.php`
`||lubin.pl/wp-content/uploads/baner$image`
`||lubin.pl/wp-content/uploads/reklama_$image`
`lubin.pl##.ad_group`
`lubin.pl##.a-.g-single`
`lubin.pl##.panel-widget-style.bottomspace.topspace`

**Comment by xxcriticxx** [comment]
filtry good
