### ISSUE TITLE
tvasta.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16649]
RODO

**Comment by krystian3w** [comment]
Dziwne...

## Chromium:
https://github.com/MajkiIT/polish-ads-filter/blob/c3867804f37558332e5af1ab32ce664a9ea9e512/cookies_filters/cookies_uB_AG.txt#L446 https://github.com/MajkiIT/polish-ads-filter/blob/c3867804f37558332e5af1ab32ce664a9ea9e512/cookies_filters/cookies_uB_AG.txt#L342

## Firefox* / Aplikacja AdGuard:
https://github.com/MajkiIT/polish-ads-filter/blob/c3867804f37558332e5af1ab32ce664a9ea9e512/cookies_filters/cookies_uB_AG.txt#L646 https://github.com/MajkiIT/polish-ads-filter/blob/c3867804f37558332e5af1ab32ce664a9ea9e512/cookies_filters/cookies_uB_AG.txt#L545

\* - zalecana aktualizacja do wersji 77 (naprawiono bug z przekierowaniami 301 / 302 że padł html filtering a dział w wersji 68 ESR)
