### ISSUE TITLE
krotoszynska.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16650]
coś blokuje

**Comment by krystian3w** [comment]
Znaczy co się zepsuło konkretnie.

Artykuły działają, główna działa, wideo z YT /  FB leci...

**Comment by blocker999** [comment]
jakiś filtr blokuje zdjęcia ( ( na głównej ), może mam zadużo i jakiś uszkodził sprawdzać to ?

**Comment by krystian3w** [comment]
Zacznij w uBO od wyłączenia "filtry własne", może coś testowałeś i masz literówkę - potem sobie znowu włącz jak to nie to.
Jak masz jakieś puste; to może błąd połączenia z internetem i na sztywno zajmują one powierzchnie.

Jak dla mnie na głównej jest tak wiele zdjęć, że trzeba by z dobre 10 minut porównywać czy na pewno tylko reklamy wycięte.

**Comment by blocker999** [comment]
dobra mam winowajce, to przez " Malicious URL Blocklist ".
