### ISSUE TITLE
ubisoft.com

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#1666]
nie mozna sie zalogowac, musialem dodac do wyjatkow. prosze dodac do pliku.

**Comment by MajkiIT** [comment]
@lukjan32 jakich filtrów od nas używasz?

**Comment by lukjan32** [comment]
takich, i polskich na dole.
![filtry](https://cloud.githubusercontent.com/assets/17565773/21293080/13c35cdc-c51a-11e6-93ef-f4e82ca5d8e6.jpg)

**Comment by F4z** [comment]
Wydaje mi się, że to jest powiązane z tym zgłoszeniem - https://github.com/MajkiIT/polish-ads-filter/issues/1563
Po aktualizacji ciasteczkowej listy nie powinno być już problemu.

**Comment by lukjan32** [comment]
czyli, jak?

**Comment by MajkiIT** [comment]
@lukjan32 Używasz naszych filtrów ciasteczek?

**Comment by lukjan32** [comment]
tak.

**Comment by MajkiIT** [comment]
to zaktualizuj je.

**Comment by lukjan32** [comment]
nie wiedzialem, ze automatyczne sie nie aktualizuje. juz jest dobrze.
