### ISSUE TITLE
londynek.net

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1668]
ad block na dole 

Uwaga! Adblock jest włączony
Strona może działać i wyświetlać się niepoprawnie

**Comment by F4z** [comment]
Chyba najprościej będzie to ukryć:
`londynek.net###ldnk-abp`

Jeszcze można dodać to, żeby schować napis "Reklama":
`londynek.net##.jd-oaz`

**Comment by xxcriticxx** [comment]
ad block jest good 

pod sub kategorie sa `Link Sponsorowany`

**Comment by F4z** [comment]
Dzięki.
Te reguły powinny to ukryć:
`londynek.net###ldnk-abp`
`londynek.net##.jd-oaz`
`londynek.net##.jd-sponsored-links-top`
`londynek.net##.jd-content-to-left.jd-content-3-2`
`londynek.net##.slTop`
`londynek.net##.bannersZoneB1`

**Comment by xxcriticxx** [comment]
jest good mozna dodac do listy

**Comment by F4z** [comment]
Ok, dzisiaj postaram się zrobić aktualizację.
