### ISSUE TITLE
olsztyn.wm.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1669]
ad block 

http://olsztyn.wm.pl/358827,Probowal-quotpoprawicquot-komunikacje-w-Olsztynie-Stanal-na-srodku-i-kierowal-ruchem-FILM.html

UWAGA! W tym miejscu umieszczony jest materiał video, który został zablokowany przez AdBlock/uBlock. Wyłącz blokowanie reklam lub dodaj naszą domenę do wyjątków, żeby obejrzeć materiał filmowy. DZIĘKUJEMY

**Comment by F4z** [comment]
Sprawdź proszę czy działa:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=exs.pl`
`||imasdk.googleapis.com/js/core/bridge*.html$subdocument,domain=exs.pl,important`

**Comment by xxcriticxx** [comment]
good film dziala
