### ISSUE TITLE
fachowyinstalator.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16708]
reklama " ferro " i fb ( po prawo )

**Comment by krystian3w** [comment]
@MajkiIT  w artykułach są też teksty "reklama" - również ukryłeś?

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/85947543-a6c78200-b94b-11ea-955b-f51740cb1fd8.png)


`##.fi-kontekstowa` - takiego nie widzę w filtrach
