### ISSUE TITLE
histmag.org

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16716]
![2020-06-27 13 12 52 histmag org 5b43be622775](https://user-images.githubusercontent.com/36385327/85920883-f63c7e00-b877-11ea-8b62-ecc6f20ae8ee.png)

**Comment by krystian3w** [comment]
@hawkeye116477 / @blocker999 patron = social?

Jak nie to poprawcie na dev.

**Comment by hawkeye116477** [comment]
Raczej powiedziałbym, że to donacje, czyli do @KonoromiHimaries.
