### ISSUE TITLE
gazetaolsztynska.pl

### ISSUE THREAD

**Issue by gargul4** [MajkiIT/polish-ads-filter#16718]
Anty-adblock - video sie nie odtwarza, naprawa:

- domenę dodajemy tu: https://github.com/olegwukr/polish-privacy-filters/blob/2b4abcaa63e6ffc00a7be0d8b5c6ce2c90e13fa3/anti-adblock.txt#L322

- oraz dodatkowo dodajemy: `@@||video.onnetwork.tv/adblock_notify.js$script,domain=video.onnetwork.tv`

### 1 przed naprawą 
![capture_279_27-06-2020_19-18-55](https://user-images.githubusercontent.com/67454905/85928124-0e79c080-b8ab-11ea-9308-8ba12565e119.gif)

### 2 po naprawie
![capture_278_27-06-2020_19-18-49](https://user-images.githubusercontent.com/67454905/85928153-31a47000-b8ab-11ea-83f5-1f8777dbcc71.gif)

**Comment by gargul2** [comment]
> gargul2 :  Anty-adblock - video sie nie odtwarza, naprawa:
>     domenę dodajemy tu: https://github.com/olegwukr/polish-privacy-filters/blob/2b4abcaa63e6ffc00a7be0d8b5c6ce2c90e13fa3/anti-adblock.txt#L322


Pomyłka z mojej strony, i anty-adblock dalej jest, bo trzeba zamiast `gazetaolsztynska.pl` dodać `video.onnetwork.tv`
