### ISSUE TITLE
gotujmy.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#16715]
`https://gotujmy.pl/pasta-z-lososia-do-kanapek,przepisy-dania-przepis,265773.html`

reklamy używające gemius do przekierowania na **Aledrogo**:

![obraz](https://user-images.githubusercontent.com/35370833/85892243-db72f680-b7f0-11ea-9caa-477708bf14c2.png) |
--- |

telefon do gotowania raczej nie jest niezbędny ani tym bardziej **jakiś "irobot rumba"**.

**Comment by krystian3w** [comment]
`##.ecomm-content-widget-type-custom`

?

**Comment by xxcriticxx** [comment]
@krystian3w zonka kazala obiad zrobic?

**Comment by hawkeye116477** [comment]
> telefon do gotowania raczej nie jest niezbędny ani tym bardziej jakiś "irobot rumba".

Jak to nie, przecież przepisy są w aplikacji, a robot posprząta po gotowaniu :smiley:

**Comment by krystian3w** [comment]
Ja bym wyciął mop do kuchni tańszy od "i robot rumby" allegrowej.
