### ISSUE TITLE
wiescirolnicze.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16713]
tło na wejściu po reklamie ( pop-up )

**Comment by MajkiIT** [comment]
`wiescirolnicze.pl###a8e0a98e6-f5d9-48d9-b9b0-5dd36b1a23a6`

**Comment by gargul4** [comment]
To wartość losowa, a nie lepiej `wiescirolnicze.pl##.topl` ?
