### ISSUE TITLE
bydgoszczcity.pl (re)

### ISSUE THREAD

**Issue by gargul4** [MajkiIT/polish-ads-filter#16728]
Reopen, bo jeden baner się ostał: https://github.com/MajkiIT/polish-ads-filter/issues/16720#issuecomment-650759928

**Comment by MajkiIT** [comment]
@gargul4 Dzięki

**Comment by gargul4** [comment]
Nie ma sprawy, zauważyłem też w powyższym commicie [>> niepotrzebnie zduplikowaną regułę <<](https://github.com/MajkiIT/polish-ads-filter/commit/969c37167f914af448c62cb43155888ca5a06e97?diff=split#diff-711027ed0794992ae3b8710d874f3df7R1973)

**Comment by gargul4** [comment]
Ok, to jeszcze raz wytłumaczę - chodziło o odwrotnie, o usunięcie: `muratorplus.pl##.zpr_box_side_bottom` 

ponieważ filtr: `muratordom.pl,mjakmama24.pl,muratorplus.pl##.active.placement__lazy, #bottom_1, .zpr_box_side_bottom` już zawiera zarówno domenę: `muratorplus.pl` jaki i klasę `.zpr_box_side_bottom`

**Comment by gargul2** [comment]
Przy okazji, żeby nie zakładać nowego zgłoszenia, bo te strony są powiązane, to jeszcze jest pusty kontener w: https://github.com/MajkiIT/polish-ads-filter/issues/16725#issuecomment-650971011

**Comment by gargul2** [comment]
Dalej są puste kontenery https://github.com/MajkiIT/polish-ads-filter/issues/16725#issuecomment-651060433
