### ISSUE TITLE
muratordom.pl

### ISSUE THREAD

**Issue by gargul4** [MajkiIT/polish-ads-filter#16725]
![capture_377_28-06-2020_09-34-20](https://user-images.githubusercontent.com/67454905/85941337-97800e80-b922-11ea-8e33-9073a88bbb09.gif)

**Comment by gargul2** [comment]
Jeszcze jest pusty kontener w artykułach np: https://muratordom.pl/instalacje/instalacja-kanalizacyjna/sedes-podwieszany-jaki-kupic-miska-ustepowa-wiszaca-na-stelazu-aa-xPSR-pe2x-YCHD.html

![capture_436_29-06-2020_08-53-02](https://user-images.githubusercontent.com/63287518/85982820-c069d780-b9e6-11ea-8678-f43b2c067753.gif)

**Comment by gargul2** [comment]
> https://github.com/MajkiIT/polish-ads-filter/commit/0961dc6c44c106a1337ac8af34abbe0c9aea854d#diff-711027ed0794992ae3b8710d874f3df7R1971

Dalej są kontenery w artykułach np. https://muratordom.pl/ogrod/ogrodzenia/nowoczesne-ogrodzenia-z-pustakow-i-cegiel-jak-je-budowac-aa-B669-aSqA-yrqT.html bo zamiast: `[id*="placement"]` które nic nie ukrywa, powinno być dodane  `[class*="placement"]`

![capture_437_29-06-2020_13-37-46](https://user-images.githubusercontent.com/63287518/86000375-c626e380-ba0d-11ea-83fd-08f0fd61f96a.gif)

**Comment by gargul2** [comment]
> https://github.com/MajkiIT/polish-ads-filter/commit/0961dc6c44c106a1337ac8af34abbe0c9aea854d#diff-711027ed0794992ae3b8710d874f3df7R1971

Dalej jest ten kontener w artykułach, bo zamiast `[id*="placement"]` które nic nie ukrywa, powinno być dodane `[class*="placement"]`
