### ISSUE TITLE
msportal.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16737]
- błąd w Polskie Filtry RODO-Ciasteczkowe - niedocięty przycisk ZAMKNIJ X
- przy okazji prenumerata

![capture_455_30-06-2020_09-50-102](https://user-images.githubusercontent.com/63287518/86099687-207c7e80-bab8-11ea-9b3d-f128b04431db.gif)

**Comment by bug-rules** [comment]
Pomyłka:

![obraz](https://user-images.githubusercontent.com/66819865/86150721-0ebdca00-bafe-11ea-8bdd-f1f5ea3fc1a7.png)

To jest po prenumeracie w pop-upie, więc nie można dociąć jako cookies/RODO.

**Comment by bug-rules** [comment]
`/reklama/*` - błąd EasyList (te od reklam, nie dawne `Fanboy's Cookiemonster`).

---

filtr przywracający grafikę: 

```
@@||msportal.pl/reklama/popup_*.png$image,domain=msportal.pl
```

**Comment by gargul2** [comment]
Ok faktycznie, błąd leży po stronie EasyList, a po wyłączeniu adblockera mamy taką sraczkę z przyciskami:

![capture_001_30-06-2020_19-14-37](https://user-images.githubusercontent.com/63287518/86157072-22b9f980-bb07-11ea-8c1c-3172665918fd.gif)

**Comment by gargul2** [comment]
A przy okazji, w tym zgłoszeniu https://github.com/MajkiIT/polish-ads-filter/issues/16738 się nie pomyliłem, a łapki w górę nie dostałem, rozumiem, że ktoś daje tylko łapki w dół, a w drugą stronę - czyli łapki górę już nie potrafi, jak takich ludzi nazwać, chyba złośliwcami...
