### ISSUE TITLE
pkw.gov.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16730]
![2020-06-29 07 14 43 pkw gov pl 9c193f04422d](https://user-images.githubusercontent.com/36385327/85975494-8691d480-b9d8-11ea-90c4-daff5533541c.png)

Social
![2020-06-29 07 18 39 pkw gov pl 7f74a606e8dc](https://user-images.githubusercontent.com/36385327/85975588-c953ac80-b9d8-11ea-9433-d44a13059765.png)

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/issues/30
