### ISSUE TITLE
tylkotorun.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16742]
reklama dzbanka z carfurta na wejściu ( pop-up )

**Comment by gargul2** [comment]
Ciekawostka - z EasyList Polish tego nie ma.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/41b4976f45e566778e8ff068d3a39b2aef6f5b2b/polish-adblock-filters/adblock.txt#L3057
