### ISSUE TITLE
rynek-kolejowy.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16748]
( u góry )

**Comment by krystian3w** [comment]
Można zamknąć:

https://github.com/MajkiIT/polish-ads-filter/blob/6f9bc437c3267961148580994436652df8e5f9e8/adblock_social_filters/adblock_social_list.txt#L4339

Ktoś zgłosił a nie zrobił aktualizacji listy.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/86387080-f03d0780-bc92-11ea-82bd-14705a9398b5.png)
