### ISSUE TITLE
staleo.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16750]
RODO ( pasek ) i reklamy

**Comment by krystian3w** [comment]
@hawkeye116477  ten o zmianie regulaminie / nowym zostaje?

Niby regulamin może ma sekcję o cookies/rodo i odsyłacze do kolejnych litanii?

**Comment by hawkeye116477** [comment]
Ten komunikat ma już rok czasu, więc do wycięcia w EI.
