### ISSUE TITLE
Przebudowa suplementów

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#16769]
https://github.com/AdguardTeam/AdguardFilters/issues/57685#issuecomment-647022651 + https://github.com/AdguardTeam/AdguardFilters/commit/c3f2c4c35e1ff3e94bbda9b78901935b14dc8496

AG widzi tylko jakiś jeden filtr skryptowy / przekierowanie (`redirect`): https://filters.adtidy.org/extension/chromium/filters/216.txt

`filmweb.pl#%#//scriptlet('ubo-abort-current-inline-script.js', 'decodeURIComponent', 'newAdblockBoardDisplayed')`

A przecież mamy ich dużo więcej.

---

https://github.com/MajkiIT/polish-ads-filter/blob/9f47dfe1bb9d764c2cbbbab6d5de520d29e6c45b/polish-adblock-filters/adblock.txt#L4765-L4771

Może trzeba zrobić ogólny suplement i do niego przekopiować `skrypty`, `redirect` i zduplikowany CSS.

**Comment by hawkeye116477** [comment]
W ogóle z racji tego, że AG obsługuje już nawet skryptlety, to może dobrze byłoby połączyć oba suplementy w jeden.

**Comment by krystian3w** [comment]
@hawkeye116477 chyba znowu coś oszalały `if-y`:

*  z Nano Adblocker 1.0.0.151 praktycznie wszystkie filtry AdGuard są używane przez Nano "11.27.101" na przykład taki:

https://github.com/MajkiIT/polish-ads-filter/blob/f9eb494e79be92617595270b1a5b4a00d299c764/polish-adblock-filters/adblock_adguard.txt#L154-L155

co generuje przekłamanie z #16999 

W uBO 1.29.2 takiego buga nie ma.

**Comment by hawkeye116477** [comment]
No to raczej to nie do mnie, ale Nano bazuje na `1.27.10`.
