### ISSUE TITLE
twojapogoda.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#16768]
Reklamy `pre-roll` w prawej kolumnie (odtwarzacz prognozy pogody).

```
||ipla-*-*.pluscdn.pl/p/r/*/*$media,redirect=noop-0.1s.mp3,domain=twojapogoda.pl
twojapogoda.pl##.ads .videoPlayer__vast, .ads .videoPlayer__mask[data-time]
```

Stary URL moim zdaniem padł: https://github.com/MajkiIT/polish-ads-filter/blob/fe3d1e7d75cb4abf1e390adf33c20ee9f27c5247/polish-adblock-filters/adblock_ublock.txt#L328-L329

Czasem są 30 sekundowe reklamy, więc dobrze by było uaktualnić `redirect=`

---

 a dla ABP może dodać rewrite pod linią:
https://github.com/MajkiIT/polish-ads-filter/blob/9f47dfe1bb9d764c2cbbbab6d5de520d29e6c45b/polish-adblock-filters/adblock.txt#L3885
`||ipla-*-*.pluscdn.pl/p/r/*/*$media,rewrite=abp-resource:blank-mp3,domain=twojapogoda.pl`

---

<del>Dodatkowo może czas przebudować suplementy tak by AdGuard widział **filtry skryptowe** i **przekierowania**: https://github.com/AdguardTeam/AdguardFilters/commit/c3f2c4c35e1ff3e94bbda9b78901935b14dc8496
</del>

**Comment by MajkiIT** [comment]
@F4z @AdamWr reguła '||ipla.hit.stat24.com/*ad.xml$xmlhttprequest,important,domain=twojapogoda.pl' powoduje adblocka,  Możesz usunąć lub zmienić ?

**Comment by AdamWr** [comment]
Ok, poprawiłem.

**Comment by MajkiIT** [comment]
@AdamWr Dziękuję
