### ISSUE TITLE
chwaszczyno.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1677]
reklama

**Comment by F4z** [comment]
`||www.chwaszczyno.pl/images/banners/$image`
`||www.chwaszczyno.pl/templates/chwaszczyno*/images/designer/*_baner*.jpg$image`
`www.chwaszczyno.pl##.bd-custom-image.bd-btn-success.bd-bootstrap-btn.bd-tagstyles.bd-blockcontent > .custom`
`www.chwaszczyno.pl##.bannergroup`
