### ISSUE TITLE
[CERT] usunięte strony z komunikatem "403"/"404" od ct8.pl i 5v.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#16780]
https://hole.cert.pl/domains/domains.json

|RegisterPositionId|DomainAddress                       |InsertDate         |DeleteDate         |
|------------------|------------------------------------|-------------------|-------------------|
|2662              |`www.allegroprize.pl`               |2020-07-02T10:34:29|2020-07-02T15:58:29|
|2496              |`bnpparibas.kantarpolska.com`       |2020-06-24T11:29:11|2020-06-24T13:54:20|
|2495              |`klient.bnpparibas.kantarpolska.com`|2020-06-24T11:28:33|2020-06-24T13:54:56|
|2373              |`ms-mbank.onfly.pl`                 |2020-06-17T11:52:07|2020-06-17T17:36:41|
|2127              |`df9e8783c33d.ngrok.io`             |2020-06-04T13:38:02|2020-06-08T09:07:16|
|1835              |`www.nagrania-covid-19.ct8.pl`      |2020-05-20T14:30:59|2020-05-20T17:19:42|
|1834              |`nagrania-covid-19.ct8.pl`          |2020-05-20T14:30:53|2020-05-20T17:19:14|
|1743              |`www.jhamarielvin.ct8.pl`           |2020-05-18T11:16:36|2020-05-20T12:34:58|
|1734              |`jhamarielvin.ct8.pl`               |2020-05-18T09:52:41|2020-05-20T12:33:30|
|1595              |`www.mfacebook.pl`                  |2020-05-14T15:54:12|2020-05-14T17:27:10|
|1448              |`prywatne-fotki.5v.pl`              |2020-05-10T21:46:14|2020-07-01T09:58:26|
|1447              |`www.prywatne-fotki.5v.pl`          |2020-05-10T21:46:08|2020-07-01T09:58:40|
|1433              |`www.podgladacze.5v.pl`             |2020-05-10T19:55:25|2020-07-01T09:58:04|
|1432              |`podgladacze.5v.pl`                 |2020-05-10T19:55:11|2020-07-01T09:58:17|
|1428              |`www.skryte-zdjecia.ct8.pl`         |2020-05-10T19:54:04|2020-05-20T12:35:09|
|1427              |`skryte-zdjecia.ct8.pl`             |2020-05-10T19:53:51|2020-05-20T12:33:49|
|1421              |`www.galeria-nagosci.ct8.pl`        |2020-05-10T08:05:48|2020-05-20T12:34:38|
|1420              |`galeria-nagosci.ct8.pl`            |2020-05-10T08:05:19|2020-05-20T12:32:51|
|1289              |`terminator3000.ct8.pl`             |2020-05-06T19:00:17|2020-05-20T12:34:14|
|1287              |`www.terminator3000.ct8.pl`         |2020-05-06T18:23:35|2020-05-20T12:35:17|
|1185              |`www.janskowron.ct8.pl`             |2020-05-04T11:51:47|2020-05-20T12:34:46|
|1184              |`janskowron.ct8.pl`                 |2020-05-04T11:51:41|2020-05-20T12:33:14|
|1170              |`krepujace-zdjeciaa.5v.pl`          |2020-05-03T19:49:02|2020-07-01T09:57:05|
|1167              |`tkozlowski.ct8.pl`                 |2020-05-03T19:00:21|2020-05-20T12:34:24|
|1166              |`www.tkozlowski.ct8.pl`             |2020-05-03T19:00:15|2020-05-20T12:35:28|
|1165              |`www.krepujace-zdjeciaa.5v.pl`      |2020-05-03T18:58:56|2020-07-01T09:57:17|
|1097              |`www.wiadomosci-lokalne.5v.pl`      |2020-04-30T17:09:18|2020-07-01T09:59:42|
|1091              |`wiadomosci-lokalne.5v.pl`          |2020-04-30T16:14:56|2020-07-01T09:59:52|
|957               |`www.planchashop.fr`                |2020-04-27T15:45:49|2020-04-27T15:57:39|
|516               |`www.adamdj.ct8.pl`                 |2020-04-15T09:47:40|2020-05-20T12:30:57|
|515               |`adamdj.ct8.pl`                     |2020-04-15T09:47:34|2020-05-20T12:31:33|
|512               |`www.wiad-info.5v.pl`               |2020-04-15T06:42:08|2020-07-01T09:58:55|
|511               |`wiad-info.5v.pl`                   |2020-04-15T06:42:01|2020-07-01T09:59:25|
|392               |`www.pllubiok.5v.pl`                |2020-04-11T11:52:40|2020-07-01T09:57:35|
|391               |`pllubiok.5v.pl`                    |2020-04-11T11:52:35|2020-07-01T09:57:45|
|390               |`centrumrozrywki.5v.pl`             |2020-04-11T11:48:55|2020-07-01T09:56:42|
|389               |`www.centrumrozrywki.5v.pl`         |2020-04-11T11:45:18|2020-07-01T09:56:52|
|161               |`direct3.greenfitness.net`          |2020-04-02T11:59:24|2020-04-02T12:22:39|
|14                |`gabriela.ct8.pl`                  |2020-03-24T21:29:20|2020-03-24T23:08:37|

**Comment by krystian3w** [comment]
Przekład takiego zombie 🧟 🧟‍♀️ na liście:

https://github.com/MajkiIT/polish-ads-filter/blob/3bc152a81ababf4ab41ecdb6ef141c0f7520fede/polish-pihole-filters/hole_cert_pl.txt#L2635

**Comment by MajkiIT** [comment]
@krystian3w https://github.com/PolishFiltersTeam/KAD/blob/master/KAD.txt#L2930

**Comment by krystian3w** [comment]
Samo się nie usuwa więc i tak musisz jakoś ogarnąć by z obu plików znikało.

**Comment by MajkiIT** [comment]
z hole_cert_pl.txt już wyleciało, ale wy trzymacie w KAD i stąd pojawia się w Forti_list.

**Comment by krystian3w** [comment]
W pliku `/hole_cert_pl.txt` najlepiej zmień plik na w którym nie ma śladu po domenie usuniętej np.:

`https://hole.cert.pl/domains/domains.txt`

Te będą złe, bo mają datę dodania i usunięcia/wykreślenia:

```
domains.csv
domains.json
domains.xml         
```

**Comment by MajkiIT** [comment]
@krystian3w tak zrobiłem

**Comment by hawkeye116477** [comment]
`allegroprize.pl` jeszcze działa.

**Comment by krystian3w** [comment]
Ale CERT już wykreślił: 

```
  {
    "RegisterPositionId": 2662,
    "DomainAddress": "www.allegroprize.pl",
    "InsertDate": "2020-07-02T10:34:29",
    "DeleteDate": "2020-07-02T15:58:29"
  },
```

Ja bym wykreślił skoro oni uznali że "malware" padło.
