### ISSUE TITLE
web.archive.org

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16782]
cookies 

https://web.archive.org/web/20170707174355/https://mac.gov.pl/aktualnosci/koniec-z-drobnym-druczkiem-od-dzis-obowiazuje-nowe-prawo-telekomunikacyjne

**Comment by krystian3w** [comment]
Takich niby się nie obsługuje, @hawkeye116477?

**Comment by krystian3w** [comment]
A ten pop-up nic nie mówi o cookies:

![obraz](https://user-images.githubusercontent.com/35370833/86539064-2a5c1280-befa-11ea-96bf-cefd4619b083.png) |
--- |


Jedynie radzi gdzie w przyszłości informacji szukać.

**Comment by krystian3w** [comment]
`###popup-cookies` znajdziesz u Kiboke: https://github.com/AdguardTeam/FiltersRegistry/blob/363337805f746249441d2bf2c06c5a2bffa1ca44/filters/ThirdParty/filter_229_IdontCareAboutCookies/filter.txt#L1216

**Comment by hawkeye116477** [comment]
@xxcriticxx Do zamknięcia i etykieta `won't fix`.

**Comment by blocker999** [comment]
Nie chodzi o pop-up bo to informacyjny ale o scrolujący pasek z cookies (na dole )

![gov](https://user-images.githubusercontent.com/23176832/86540976-3b605000-bf09-11ea-8112-d2739789c015.png)

**Comment by krystian3w** [comment]
Kupić `Ryzen` (i cały nowszy zestaw) a nie męczyć komputer z okolic 2008 w 2020, bo ten pasek ukrywa: https://github.com/AdguardTeam/FiltersRegistry/blob/363337805f746249441d2bf2c06c5a2bffa1ca44/filters/ThirdParty/filter_229_IdontCareAboutCookies/filter.txt#L1216

Jak masz zasięgi to zrób ankietę czy mamy wymuszać filtry dla starych PC z słabym CPU.

**Comment by krystian3w** [comment]
A i jakby śmieszek naprawiał jakiś anty-adblock  w `web.archive.org`, to dodaj sobie takie filtry pod `web.archive.org`:

```
*$shide,ehide,ghide=web.archive.org
```

wyłączą one zbyt uproszczone naprawy anty-adblock pamiętające czasy ABP.
