### ISSUE TITLE
fakt.pl 

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#16790]
https://www.fakt.pl/

![20200706-1594046134-001](https://user-images.githubusercontent.com/9846948/86605443-01de2200-bfa7-11ea-8eba-900a34f24404.png)

To samo dzieje się przy użyciu uBlock Origin czy Adguard. 
```
<div class="facebookLikePopup" data-run-module="local/main.facebookPopup" data-section="sgcurrentnews" style="background-image: url('https://ocdn.eu/faktucs/fakt_pl/facebook_popup_background_gradient.png')" data-run-module-isrun="1">
    <img src="https://scontent-waw1-1.xx.fbcdn.net/v/t1.0-9/12079543_10153658656424375_1369535674378705641_n.jpg?_nc_cat=1&amp;_nc_sid=09cbfe&amp;_nc_ohc=DZ-FU9QIcn4AX916o_8&amp;_nc_ht=scontent-waw1-1.xx&amp;oh=2ce204a90d51ad73c0e3b1ac4e3fcd6b&amp;oe=5F081837" alt="Facebook profile image" class="profile_image">
    <div class="text-wrapper">
        <span class="line_one">Polub FAKT na Facebooku!</span>
        <span class="line_two">1112155 polubień!</span>
    </div>
    <div id="fb-like">
        
    </div>
    <span class="close" id="FPUclose"></span>
</div>
```

**Comment by krystian3w** [comment]
Wycięty w socialu: https://github.com/MajkiIT/polish-ads-filter/blob/2a0de5321942d7a53a4be333b52dec36d737cdac/adblock_social_filters/adblock_social_list.txt#L40-L41

@F4z / @adamwr - to wymaga znowu użycia w chrome:

```
fakt.pl,medonet.pl#?#.facebookLikePopup 
fakt.pl,medonet.pl#?#.withFPU:before 
```

lub CSS `#$# { display: none !important }`

❓

**Comment by FadeMind** [comment]
@krystian3w  nie subuję Polish Social bo wycinają za dużo, i nie zostawiają odnośników do mediów społecznościowych tak jak robi domyślnie ublock czy adguard.
![20200706-1594047152-001](https://user-images.githubusercontent.com/9846948/86607057-18857880-bfa9-11ea-9eeb-e9d376a1331c.png)

**Comment by krystian3w** [comment]
No to raczej musisz czekać aż to się znajdzie w AdGuard Social Media / AdGuard Annoyance.

---

wychodzi, że wyłączyłeś też PL EI: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/5cb7626d19554909021b95075a9d476e9acb4399/PPB.txt#L1839-L1840 - zakładając, że to nie bug aplikacji na Windows z liniowym `display: block !important` by pop-up na pewno był widoczny_

**Comment by FadeMind** [comment]
w ublock origin to samo jest, więc to nie wina apki.

**Comment by krystian3w** [comment]
> tak jak robi domyślnie ublock 

Nie robi, nie specjalizują się w lepszej blokadzie elementów social jak nie jest to pop-up z zablokowanym przewijaniem:

> If the ABP-compatible fixes are for high-traffic sites, they should be added to uBO filters until they are added to EasyList.



Jak dla mnie najpierw odeślą cię po Fanboy Annoyance / AdGuard Annoyance a potem dopiero do reklamowej PL.

**Comment by krystian3w** [comment]
Moim zdaniem wina apki, mnie filtr social / EI działa z uBO/AdGuard Extension `3.4.31` (inna sprawa że oba wyłączyłeś).

![obraz](https://user-images.githubusercontent.com/35370833/86608363-b594e100-bfaa-11ea-90fe-6f2c88798f49.png) |
--- |
uBO nie wymaga używania style lub `:remove()` |

![obraz](https://user-images.githubusercontent.com/35370833/86608763-423f9f00-bfab-11ea-97f7-6f9fa8caf114.png) | ![obraz](https://user-images.githubusercontent.com/35370833/86609018-98144700-bfab-11ea-8224-beeae37de368.png)
--- | ---
PL social (działa, pop-up nie umie się przebić) | PL EI (działa, pop-up nie umie się przebić)

**Comment by FadeMind** [comment]
- Filtr Polski Socjal ogarnia i wycina popup. Przy okazji uwalając odnośniki do stron społecznościowych (czego adguard nie robi bo ma taką politykę, że zostawia wizytówki - odnośniki graficzne do profili), natomiast PL social wycina wsio (tak jak fanboy)
- w ublocku subuję filtry Adguard (Base, Annoyances, Spyware, Social), które fajnie się uzupełniają z ublock annoyances nie psując dostępu do wizytówek (umownie mówiąc). 
- Teraz pytanko, dlaczego Polski Social wycina wszystko, zamiast zostawić wizytówki, o ile są dostępne? 
;) 
```
"selectedFilterLists": [
    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "adguard-generic",
    "easylist",
    "adguard-spyware",
    "easyprivacy",
    "malware-0",
    "malware-1",
    "spam404-0",
    "adguard-annoyance",
    "adguard-social",
    "plowe-0",
    "POL-0",
    "POL-2",
    "https://alleblock.pl/alleblock/alleblock.txt",
    "https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_browser_UBO.txt",
    "https://www.i-dont-care-about-cookies.eu/abp/",
    "https://raw.githubusercontent.com/PolishFiltersTeam/KAD/master/KAD.txt",
    "https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt"
  ],
```

**Comment by krystian3w** [comment]
> Teraz pytanko, dlaczego Polski Social wycina wszystko, zamiast zostawić wizytówki, o ile są dostępne?

Bo @MajkiIT tak robił w przeszłości, nie zrobił polityki  `CONTRIBUTING.md`, że takich linków z nawigacji / bocznych kolumn / stopek ruszać nie wolno.

Dodatkowo one rażą po oczach np.: @blocker999 (dawny kontynuator listy - niby jakieś filtry dodawał dawno temu jak MajkiIT "zaczął" już tylko przyjmować PR i poprawiać jakieś błędy kardynalne w socialu np. biała strona).

Może @hawkeye116477 robił sondę czy linki mają zostać - niby była sonda, że RSS trafił do osobnego repozytorium.

---

Jak całe https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/ też stało się "be" 🐝, przez wycinanie prenumerat to może moduł wycinający pop-upy będzie OK: 

filtry na mały pop-up FB tam są: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/5cb7626d19554909021b95075a9d476e9acb4399/PAF_pop-ups.txt#L269-L270

https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_pop-ups.txt

Niby aplikacja AG już obsługuje subskrypcje spoza sprawdzonej / zweryfikowanej.

Chyba że ona też "be" 🐝, że wycinać będzie już mniej pop-upów:

[`CONTRIBUTING.md`](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/CONTRIBUTING.md)
```
NIE blokujemy/ukrywamy:

    wyskakujących okien informacyjnych m.in.:
        opisujących godziny urzędowania np. firm
        opisujących utrudnienia w wysyłkach, zamówieniach i odbiorze
        opisujących zmiany funkcjonowania transportu
        oryginalnie nie zawierających żadnej treści
        zawierających komunikaty o pełnoletności
```

**Comment by FadeMind** [comment]
@krystian3w  pomóc wam w weryfikacji gdzie co jak jest wycinane?? Bo Polish Social czy Polish Annoyances Suplement wycina jak leci xD

**Comment by hawkeye116477** [comment]
> Polish Annoyances Suplement 

Mówisz o https://github.com/PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement? Tam są wycinane elementy RSS, resztki po ukrytych newsletterach złączonych z elementami społecznościowymi i oczywiście newslettery i elementy społecznościowe też. To jest lista łącząca EI z Socialem, dla tych co mają obie listy.

**Comment by krystian3w** [comment]
> pomóc wam w weryfikacji gdzie co jak jest wycinane?

Mówisz, że chcesz sprzątnąć pro bono z 6 tysięcy filtrów, bo @MajkiIT  zapomniał dać zakaz by nie usuwać linków statycznych otwierających FB / Twitter / Instagram (na pewno takich będzie około 6 tysięcy, a te 1500 to będą pewnie resztki z wtyczek "udostępnij na FB/Twitter" jakie Fanboy przegapił)?

_(...)_

Jak masz na myśli przykłady źle działających filtrów, że:
* robią całe białe strony
- znika cała:
   - stopka 
   - nawigacja 
   - kolumna 

to takie jak masz czas to możesz zgłaszać jako błędne.

Przy ilości około 7 tysięcy domen na liście nie w sposób ręcznie sprawdzić szybko każdy czy rozwalił stronę kompletnie, pewnie nawet kiepsko to sprawdzić jakimś "web scrapingiem" (trzeba by bota nauczyć co ma wykrywać jako za mocne wycinanie).

Na pewno też nie wiele da używanie `:has()` i `:contains()` - efekt będzie taki, że pewnie część stron zwolni lub i tak taki ogranicznik nie zabezpieczy za dobrze przed wycięciem o wiele za dużo.

_(...)_

Jak chodzi o sprawdzenie, że nie wycina `AdGuard Social Media` lub `AdGuard Annoyance` to takie coś mogę sam zrobić - z bardziej egotystycznymi listami jak np. [`/yourduskquibbles/webannoyances`](https://github.com/yourduskquibbles/webannoyances) to tam raczej @KonoromiHimaries załatwił tak, że polskich "`.pl`" chyba nie warto zgłaszać.

---

Jak @MajkiIT nie da zakazu blokowania tych statycznych linków to ja i @hawkeye116477 raczej dalej będziemy je usuwać na postawie surfowania czy zgłoszeń ("jedna jaskółka wiosny nie czyni", a szklana kula nie mówi ile nie potrafi wyrazić swojej opinii, że jest za wycofaniem tak restrykcyjnego wycinania).

**Comment by krystian3w** [comment]
@MajkiIT  jak możesz to może zrób ankietę na `certyficate.it` i FB o tym czy lista social ma wycinać mniej.

Najwyżej jako długofalowy proces się będzie usuwało niesłusznie zablokowane statyczne linki społecznościowe jakich nie lubią np. @blocker999  i @xMaap.

**Comment by MajkiIT** [comment]
@krystian3w OK

**Comment by hawkeye116477** [comment]
> Najwyżej jako długofalowy proces się będzie usuwało niesłusznie zablokowane statyczne linki społecznościowe

A Fanboya zamienimy na https://filters.adtidy.org/ios/filters/4.txt?

**Comment by FadeMind** [comment]
> na pewno takich będzie około 6 tysięcy, a te 1500 to będą pewnie resztki z wtyczek "udostępnij na FB/Twitter" jakie Fanboy przegapił

To nie lepiej adoptować (wymagać filtrów adguarda i ewentualnie suplementować braki by wycinało FB/TW widgets? Insta przecież i tak przechodzi ;)

**Comment by hawkeye116477** [comment]
Ewentualnie można zrobić 2 wersje listy - light (wymagana lista AG) i full (wymagana lista Fanboya). Tylko trzeba byłoby poprzenosić do osobnych sekcji.

**Comment by krystian3w** [comment]
Jeszcze jest taki:

https://filters.adtidy.org/extension/android-content-blocker/filters/4.txt


Jak iOS nie zrównał się z Androidowym Content Blocker.

**Comment by blocker999** [comment]
Też jestem za dwoma listami ale niemam czasu teraz tego odsiewać, dla mnie obecna lista jest ok a jak @FadeMind brakuje wersji " light " to niech ją zrobi.

**Comment by KonoromiHimaries** [comment]
@hawkeye116477 nie lepiej zrobić subliste jako rozszerzenie dla light?

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Ale wtedy będą musieli dodatkową listę dosubskrybować i zaraz pewnie będą zgłoszenia, że coś nie wycięte. Skrypt jest, więc to nie problem połączyć obie listy, gorszy problem jest z oddzielaniem tego wszystkiego.

**Comment by krystian3w** [comment]
Jak AdGuard nie usunie przestarzałego `@@||civilization.com^$jsinject` i tak dla ABP / AdBlock lepiej robić mirror by nie było, że przez `$jsinject` dodatek nie filtruje prawie wcale lub rozwala się strona `civilization.com`.

Chyba, że Light będzie niedostępne dla ABP i AdBlock.

**Comment by KonoromiHimaries** [comment]
@hawkeye116477 nie widze sensu w tworzeniu wielu list, których i tak nikt nie zasubskrybuje.

**Comment by krystian3w** [comment]
Zobaczymy czy ankieta powstanie i czy ktoś będzie głosować by nie blokować statycznych linków social.

**Comment by hawkeye116477** [comment]
@KonoromiHimaries 

> nie widze sensu w tworzeniu wielu list, których i tak nikt nie zasubskrybuje.

To zdecyduj się w końcu, co to za różnica czy jest to zrobione za pomocą `#include` czy doklejone? Sublisty jednak sam  też robisz. Jeden chętny @FadeMind już jest, jak zrobią ankietę i będzie więcej, to wtedy ewentualnie rozważy się wprowadzenie listy light.

**Comment by MajkiIT** [comment]
@hawkeye116477 ja robiłem social aby wywalały wszystko co związane z social. No ale to było 6 lat temu :D . Rozumiem, że na prośbę @FadeMind poddajemy dyskusję aby filtry social nie usuwały:

odnośniki do stron społecznościowych oraz zostawiać wizytówki - odnośniki graficzne do profili

??

**Comment by krystian3w** [comment]
Tak.

**Comment by FadeMind** [comment]
> Rozumiem, że na prośbę @FadeMind poddajemy dyskusję aby filtry social nie usuwały:
> - odnośniki do stron społecznościowych oraz zostawiać wizytówki - odnośniki graficzne do profili

Tak.

**Comment by gargul2** [comment]
Np. https://github.com/MajkiIT/polish-ads-filter/blob/1a509ebc1c88fdd71b27684404f5b627636722c4/adblock_social_filters/adblock_social_list.txt#L5242 wycina odnośniki w https://github.com/MajkiIT/polish-ads-filter/issues/16861

**Comment by krystian3w** [comment]
* 33  lub 34 za zostawieniem tak jak jest ("agresywne" wycinanie wizytówek)
* 9 lub 10 za nowym lżejszym/łagodniejszym wycinaniem

Nie wiem czy da się zrobić podgląd bez konta Majkiego by liczyło nie procentowo lub głosowanie było jawne.



![obraz](https://user-images.githubusercontent.com/35370833/87950500-a718f000-caa7-11ea-9fa4-9e4ec4537234.png) |
--- |
https://www.facebook.com/CertyficateIT/posts/2655663981339838 |



Co do filtra to wycina on raczej dalej ze starą zasadą - czyli "wizytówki", nie widzę by wycinał np. miniaturki artykułów w środkowej kolumnie. Poprawić można by nie wycinał RSS i bug Fanboya by przywrócić RSS i opcjonalnie działał 1 z 2 tylko w headerze.

---

Jedna jaskółka wiosny nie czyni, zostało około 4999+ do wskazania i przeniesienia w plik:

`/social/agresywne_specyficzne_ukrywające.txt` po jego utworzeniu.

**Comment by krystian3w** [comment]
Ja też myślę, że to też nie na moje progi by szybko odsiać filtry na 2 grupy; z dużą pewnością najłatwiej będzie przefiltrować "blokujące" sieciowe, raczej praktycznie każdy jak nie jest to plik JS/ramka odpada z wersji "lekkiej" / "delikatnej".

Opcjonalnie poprzeklejać zgłoszenia pop-upów social do AdGuard jak wyciekają z AdGuard Social Media.
