### ISSUE TITLE
electrolux.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#16792]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/86638262-42559400-bfd7-11ea-959c-3741f67db480.png)
![obraz](https://user-images.githubusercontent.com/32641928/86638288-4ed9ec80-bfd7-11ea-960f-3d87dd181139.png)

### Link bezpośredni 
https://www.electrolux.pl/laundry/laundry/washing-machines/

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. Wejść na strone

Po wejściu na stronę nie da się przesuwać na dół jeśli jest włączony uBlock. Po wyłączeniu pojawia się komunikat Rodo i po zaakceptowaniu możliwe jest przesuwania strony na dół.

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox

**Rozszerzenia i skrypty:** 
uBlock
NanoDefender

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Polskie Filtry Rodo-Ciasteczkowe 
4. I don't care about cookies
5. Polskie Filtry Elementów Irytujących
6. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by gargul2** [comment]
https://github.com/easylist/easylist/issues/5684 - kolejny wstrętny błąd typu występujacy we wszystkich listach ciasteczkowych - buahaha.

**Comment by hawkeye116477** [comment]
Ale śmieszne...

**Comment by gargul2** [comment]
Jeśli wolisz, to może być tragiczne, mi to bez różnicy, buahaha.

**Comment by gargul2** [comment]
Reopen: znaleziono nowe uszkodzone domeny: `aeg.pl` + `zanussi.pl`, poczytać więcej można w gorącej dyskusji: https://github.com/easylist/easylist/issues/5684

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/blob/c8c6fefb1a8a005fbfcaf7832ca48aa150ecfc3c/SocialFilter/sections/specific.txt#L1999 - może to zobacz.
