### ISSUE TITLE
bytomski.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16805]
Większosć z tych losowych ~~filtrów~~ paździerzy znalezionych w wątku https://github.com/MajkiIT/polish-ads-filter/issues/16763 rozpruło się jak stare spodnie, kolejny z przykładów: `bytomski.pl##IMG[src^="http://www.bytomski.pl/images/banners/"], #sppb-addon-`**`1575199906458`**` > .sppb-text-center.sppb-addon-single-image.sppb-addon > .sppb-addon-content > .sppb-addon-single-image-container`

### w artykułach pusty kontener z napisaem po reklamie np. https://www.bytomski.pl/112/25344-bytomianin-probowal-przemycic-80-kg-kokainy

![capture_015_08-07-2020_14-57-25](https://user-images.githubusercontent.com/63287518/86921474-7b9f1880-c12b-11ea-834b-ad7757030bf4.gif)

**Comment by MajkiIT** [comment]
@gargul2 ale po co to dublujesz?

**Comment by gargul2** [comment]
Z tego samego powodu co tu https://github.com/MajkiIT/polish-ads-filter/issues/13818#issuecomment-618825281.

**Comment by gargul2** [comment]
Jak wyżej, jeszcze góra 6 zgłoszeń, OK?
