### ISSUE TITLE
download.komputerswiat.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#16835]
reklamy programu CloudBackup i resztki reklamowe w prawej kolumnie:

```
download.komputerswiat.pl##a[href^="/akcesoria-i-narzedzia/kopia-zapasowa-danych/cloud-backup"] > img
download.komputerswiat.pl##div.dl-floating-slot-wrapper
```

**Comment by xMaap** [comment]
To chyba też można wyciąć https://www.komputerswiat.pl/aktualnosci/sprzet/apple-ostrzega-przed-zamykaniem-laptopow-z-zaslonieta-kamerka/hznqye1?srcc=null
![2020-07-11 21 29 36 www komputerswiat pl cc832bb6a993](https://user-images.githubusercontent.com/36385327/87232241-a902f500-c3bd-11ea-84b1-8073c9b57022.png)

**Comment by krystian3w** [comment]
@hawkeye116477 wywalił filtry jak je dodałem w EI.

Niby komunikat musi zostać mimo poprawnego unieszkodliwienia linków w EI.

**Comment by hawkeye116477** [comment]
> Niby komunikat musi zostać mimo poprawnego unieszkodliwienia linków w EI.

EI nie ukrywa linków afiliacyjnych.
