### ISSUE TITLE
zyciesiedleckie.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1683]
ad block + reklamay 

Zauważyliśmy, że korzystasz z wtyczki AdBlock. Wyłącz ją, aby móc w pełni korzystać z portalu albo wyklucz domenę zyciesiedleckie.pl

**Comment by F4z** [comment]
`@@||zyciesiedleckie.pl/pl/js/show_ads.js$script,domain=zyciesiedleckie.pl`
`||zyciesiedleckie.pl/banery_foto/$image`
`zyciesiedleckie.pl##.a-d-v-i`
