### ISSUE TITLE
outdoorzy.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16839]
Social + ukryta treść
![2020-07-11 21 40 47 www outdoorzy pl c061916e4f5c](https://user-images.githubusercontent.com/36385327/87232434-53c7e300-c3bf-11ea-972a-342aca8bb4b5.png)

**Comment by krystian3w** [comment]
Treść raczej otwiera się przez zewnętrzne przekierowanie, zostaje dociąć lukę i nagłówek.
