### ISSUE TITLE
koronowo.net.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1684]
ad block 

Zauważyliśmy, że korzystasz z wtyczki AdBlock. Wyłącz ją, aby móc w pełni korzystać z portalu albo wyklucz domenę koronowo.net.pl

**Comment by F4z** [comment]
`@@||koronowo.net.pl/pl/js/show_ads.js$script,domain=koronowo.net.pl`
`||koronowo.net.pl/banery_foto/$image`
`koronowo.net.pl##.a-d-v-i`
