### ISSUE TITLE
ciechocinek.biz

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1685]
ad block 

Zauważyliśmy, że korzystasz z wtyczki AdBlock. Wyłącz ją, aby móc w pełni korzystać z portalu albo wyklucz domenę ciechocinek.biz

**Comment by F4z** [comment]
`@@||ciechocinek.biz/pl/js/show_ads.js$script,domain=ciechocinek.biz`
