### ISSUE TITLE
gameplanet.onet.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16850]
https://gameplanet.onet.pl/gry-online/zrecznosciowe/shards-the-brickbreaker/9ld7bs3
![2020-07-11 21 54 10 gameplanet onet pl 1dbda6ccebf9](https://user-images.githubusercontent.com/36385327/87232668-16645500-c3c1-11ea-8052-b9a8daea6f71.png)

**Comment by MajkiIT** [comment]
@xMaap nadal to masz?

**Comment by xMaap** [comment]
@MajkiIT tak
![2020-07-17 10 06 04 gameplanet onet pl 3cd2d4faf69e](https://user-images.githubusercontent.com/36385327/87763482-280c8900-c815-11ea-9fdf-2e6113c4108e.png)

**Comment by krystian3w** [comment]
`||pulsembed.eu^$script,domain=gameplanet.onet.pl` 

niby działa, jak ktoś chce lepiej to musi wymyślić coś dokładniejszego lub filtr skryptowy - zalecam, bo pewnie ktoś za raz znajdzie jakieś solucje pod `gameplanet.onet.pl` których nie można wtedy już nigdy więcej obejrzeć...

---

przy okazji jakiś bug chyba po implementacji * w domain @gwarser:

"`||testwa-blokada.eu.example^$script,domain=gameplanet.onet.pl/gry-online/`" - niby liczy to za "poprawny filtr"
Nawet linter Nano Adblockera się nie czepia.

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/87835045-58dbd500-c88c-11ea-9850-d2cbff7f8a64.png)

**Comment by krystian3w** [comment]
Niby nawet 1.19 tak ma że liczy to jako filtr z dzwinym URI/URL.

![obraz](https://user-images.githubusercontent.com/35370833/87835170-a8220580-c88c-11ea-81a3-6f525234f665.png) |
--- |

**Comment by gwarser** [comment]
1.27.10 nie pokazuje błędu w logu.

**Comment by krystian3w** [comment]
A powinien wykryć to raczej jako `! Invalid rule options:` i pokazywać 0 na 0 w "lista filtrów".
