### ISSUE TITLE
elektroda.pl - zablokowane obrazki

### ISSUE THREAD

**Issue by gulson-elektroda** [MajkiIT/polish-ads-filter#16860]
Witajcie,

Regułką:
/^(http|https):\/\/obrazki.elektroda.pl\/[0-9]{9,10}_[0-9]{9,10}.(jpg|gif)/$image,domain=elektroda.pl 
Zablokowaliście wszystkie obrazki na forum elektroda.pl
Przykładowy URL:
https://www.elektroda.pl/rtvforum/topic3712112.html
Nie da się załadować dużych obrazków (powiększyć).
Screenshot:
https://obrazki.elektroda.pl/3541689100_1594650183.png
Dodatkowo, jak user użyje dużego obrazka (a nie miniatury) w poście to go nikt nie zobaczy.

Wystawiam właśnie komunikat dla userów, że to z powodu Waszego filtru, aby pisali do Was reklamacje bezpośrednio, bo nie wiem czemu ja mam się tłumaczyć :)

**Comment by MajkiIT** [comment]
Nie do końca zablokował, bo działa :D 

![obraz](https://user-images.githubusercontent.com/11302675/87325079-47fc2e00-c531-11ea-98d5-83e02b4a588a.png)
