### ISSUE TITLE
[NSFW] Reguła /aserver/$script,subdocument blokuje treść na tube-bunny.com

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#16867]
[20200716-1594889516-001](https://user-images.githubusercontent.com/9846948/87650918-aeac6200-c752-11ea-8624-804639d2255a.png)
[20200716-1594889270-001](https://user-images.githubusercontent.com/9846948/87650924-afdd8f00-c752-11ea-8928-33887d6a967a.png)
[20200716-1594889193-001](https://user-images.githubusercontent.com/9846948/87650928-b0762580-c752-11ea-92fa-bc7b4b23c8ae.png)
[20200716-1594889173-001](https://user-images.githubusercontent.com/9846948/87650932-b10ebc00-c752-11ea-8c2d-32b137e37bc9.png)
Jak wyłączę zupełnie `/aserver/$script,subdocument` to reklamy się ładują oczywiście ale strona wczytuje się poprawnie. 
Może ograniczcie zasięg `/aserver/$script,subdocument` do polskich domen??

**Comment by xxcriticxx** [comment]
@FadeMind *tsk* *tsk* Nie oglądaj filmów porno!

**Comment by gargul2** [comment]
Bo ta reguła w ogóle jest błędna, bo jest traktowana jak regex (a ktoś na pewno nie chciał żeby to był regex):

> **The following error, warning or optimalization was encountered while checking the rules:**
> **/aserver/$script,subdocument** : Unnecessary regular expression. 
> Use 'aserver$script,subdocument' instead, 
> or use '/aserver/*$script,subdocument' if it isn't a regex

czyli `/aserver/` jako regex to to samo co reguła `aserver` - reguła zbyt ogólna więc blokuje i psuje za dużo, żeby reguła nie była traktowana jako regex, trzeba dodać gwiazdkę na końcu: `'/aserver/*$script,subdocument'` Oczywiście w uBO problemu nie ma, bo uBO się "domyśla" że to błąd i zamienia automatycznie na zwykłą regułę, więc nic nie jest psute, ale inne ad-blockery nie koniecznie się domyślają.

**Comment by FadeMind** [comment]
@gargul2  
używam obecnie Adguard dla Windowsa (7.5 Nightly 8) w Edge Chromium. Filtrowanie Adguard domyślnie korzysta z tej reguły i wycina wszystko.

**Comment by krystian3w** [comment]
a zaczęło się od docera:

https://github.com/MajkiIT/polish-ads-filter/commit/4b70311f6cc4962cd203a91cb919dbf9c81790a2

**Comment by gargul2** [comment]
Jeśli już to jest jeszcze taki filtr: https://github.com/MajkiIT/polish-ads-filter/blob/6b7132ddc23efda962b768a7f9e2538355522343/polish-adblock-filters/adblock.txt#L4687

**Comment by gargul2** [comment]
Ten xxcriticxx to chyba jak się nudzi to przychodzi popajacować i powkurzać..., jak nazwa wątku jest długa na kilometr (ten wątek) to nie skrócił, ale nazwę mojego (https://github.com/MajkiIT/polish-ads-filter/issues/16879) skrócił, i teraz kto zrozumie o co temu gościowi chodzi, ten wygra Iphone 11.

**Comment by krystian3w** [comment]
Jak dla mnie niesłusznie zamknięte, co by było jakby `Alex-302` lub AdamWr żądał poprawki, bo nie chcą kolejnej rzeczy naprawiać w AdGuard Base lub `FiltersRegistry` wycinając filtr na poziomie domeny `filters.adtidy.org`?
