### ISSUE TITLE
wirtualnemedia.pl

### ISSUE THREAD

**Issue by AdamWr** [MajkiIT/polish-ads-filter#16861]
### Zrzut ekranu 

<details><summary>Obrazki</summary>

![image](https://user-images.githubusercontent.com/29142494/87434197-74c04c00-c5ea-11ea-9437-89057d93ded0.png)

![image](https://user-images.githubusercontent.com/29142494/87434025-45114400-c5ea-11ea-940c-e0f566e412ba.png)

</details>

### Link bezpośredni 

`https://www.wirtualnemedia.pl/artykul/obwe-niepokoja-ksenofobiczne-homofobiczne-i-antysemickie-tresci-tvp-kampania-wyborcza`

### Co trzeba zrobić, aby pojawił się błąd?
1.  Wejść na stronę. 

### Moja konfiguracja 

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Ta reguła:
`wirtualnemedia.pl##A[target="_blank"] > IMG`
powoduje, że linki do portali społecznościowych i niektóre obrazki w artykułach są ukryte.

**Comment by gargul2** [comment]
Admin coś ostatnio szaleje z wycinaniem obrazków :smiley: (https://github.com/MajkiIT/polish-ads-filter/issues/16860)

**Comment by krystian3w** [comment]
A EP 6 dnień wyciąć nie może.

**Comment by gargul2** [comment]
> A EP 6 dnień wyciąć nie może.

Bo rzadko się zajmuje: https://github.com/easylistpolish/easylistpolish/issues/429#issuecomment-618924827

Ale skoro już wspomniałeś o EP i dla odmiany teraz linczujemy admina EP to mogę sie przyłączyć do "linczu" admina EP i pocieszyć naszego admina, bo admin EP też zaszalał z wycinaniem obrazków na elektrodzie  (https://github.com/easylistpolish/easylistpolish/issues/429#issuecomment-629088352 + https://github.com/easylistpolish/easylistpolish/issues/589) :smiley:

**Comment by MajkiIT** [comment]
@AdamWr Dzięki
