### ISSUE TITLE
pracawgdansku.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1686]
szary box po reklamach 

http://pracawgdansku.com.pl/details,12499694-lt.html

**Comment by MajkiIT** [comment]
@xxcriticxx takie coś zmniejsza przestrzeń, ale nie da się usunąć całości
`pracawgdansku.com.pl##TR[height="120px"]`

**Comment by xxcriticxx** [comment]
jest jakis bar niewidzialny na dole tez
