### ISSUE TITLE
crolove.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16874]
https://crolove.pl/park-przyrody-papuk-jankovac-mountain-park/
![2020-07-18 11 48 35 crolove pl 8380d802bf04](https://user-images.githubusercontent.com/36385327/87849928-a9831a80-c8ec-11ea-8566-774fc93e8205.png)

**Comment by krystian3w** [comment]
Oceny nie działają, bo pliki svg nie istnieją:

`https://crolove.pl/wp-content/plugins/wp-postratings/images/stars(png)/rating_over.png` - 404...
