### ISSUE TITLE
doleasingu.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16872]
![2020-07-17 09 58 50 doleasingu com 734015742db1](https://user-images.githubusercontent.com/36385327/87762931-28585480-c814-11ea-956f-9e876a89a773.png)

**Comment by krystian3w** [comment]
Kiboke bad filter:

`#@#body > #privacy[style*="display"]`

**Comment by krystian3w** [comment]
Kiboke bad filter:

`#@#body > #privacy[style*="display"]`
`#@##cookies-msg`

**Comment by krystian3w** [comment]
Kiboke bad filter:

`#@#body > #privacy[style*="display"]`
