### ISSUE TITLE
wrozbyonline.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16873]
![2020-07-18 02 58 31 www wrozbyonline pl 25f57892fa47](https://user-images.githubusercontent.com/36385327/87841007-ad8a4a80-c8a2-11ea-8735-d74ed5cd5b0b.png)

**Comment by krystian3w** [comment]
@hawkeye116477 wygląda na jedno z fejkowych, logować można się bez akceptacji;

 a motywów np. białego `#fff` lub czarnego `#fff` zamiast fioletowego `#636` nie mają...

---

`#6f326f` ~ `#636`
