### ISSUE TITLE
gg.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#16870]
( pop-up ) po zalogowaniu przez przeglądarke

**Comment by hawkeye116477** [comment]
Ktoś z tego jeszcze w ogóle korzysta?

**Comment by krystian3w** [comment]
Wtedy to i ten InPostowy by trzeba drugi raz sprawdzić czy zapisuje się na serwerze a nie na koncie https://github.com/MajkiIT/polish-ads-filter/issues/12478

**Comment by krystian3w** [comment]
Ja dodatkowo nie mam pop-upa, może jakiś glitch z niewydolnym CPU.

Kiboke jak coś klika to pewnie ten co my po prostu naprawiamy przewijanie:

https://github.com/MajkiIT/polish-ads-filter/blob/6c76f4817b379b75e923e7db0089b85794392dbd/cookies_filters/cookies_uB_AG.txt#L32-L33

**Comment by gargul2** [comment]
Ja mam stare konto na GG, z którego od kilku lat w ogóle nie korzystałem, a nawet zapomniałem o nim i dopiero to zgłoszenie mi przypomniało o jego istnieniu, ale popupa nie ma, bo tak jak napisał krystian: Kiboke już go klika i ukrywa i to jeszcze przed zalogowaniem, po zalogowaniu też nic nie wyskakuje.
