### ISSUE TITLE
swiecie.siecportali.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1687]
ad block 

Zauważyliśmy, że korzystasz z wtyczki AdBlock. Wyłącz ją, aby móc w pełni korzystać z portalu albo wyklucz domenę swiecie24.pl

**Comment by F4z** [comment]
`@@||swiecie.siecportali.pl/pl/js/show_ads.js$script,domain=swiecie.siecportali.pl`
`||swiecie.siecportali.pl/banery_foto/$image`
`swiecie.siecportali.pl##.a-d-v-i`
