### ISSUE TITLE
zwiadowcahistorii.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16888]
https://www.zwiadowcahistorii.pl/koty-w-polsce-juz-6-tys-lat-temu-zwalczaly-gryzonie/
![2020-07-21 14 21 21 www zwiadowcahistorii pl 300c8cb6e211](https://user-images.githubusercontent.com/36385327/88054359-7e533200-cb5d-11ea-8897-7f2dbd8c4be8.png)

**Comment by MajkiIT** [comment]
`www.zwiadowcahistorii.pl##.wp-block-image`
