### ISSUE TITLE
transport-publiczny.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16885]
![2020-07-21 14 19 18 www transport-publiczny pl 770f9a813e64](https://user-images.githubusercontent.com/36385327/88054164-33d1b580-cb5d-11ea-9dbc-0cfc078217ea.png)

**Comment by krystian3w** [comment]
W rss bo zmieszane, chyba że @hawkeye116477  rozbije to na 3 commity (RSS z nagłówkiem + newsletter + 2 ikonki do sociala).
