### ISSUE TITLE
forum.optymalizacja.com

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16891]
Reklamy np. https://www.forum.optymalizacja.com/topic/106557-generator-zda%C5%84-losowych-zawiraj%C4%85cych-podane-s%C5%82owofraz%C4%99

![capture_005_21-07-2020_22-11-50](https://user-images.githubusercontent.com/63287518/88102168-669c9d80-cb9f-11ea-8229-0b17247aa594.gif)

**Comment by MajkiIT** [comment]
```
www.forum.optymalizacja.com###ipsLayout_mainArea > .ipsSpacer_half.ipsSpacer_both
www.forum.optymalizacja.com##form > .ipsSpacer_half.ipsSpacer_both > .ipsList_noSpacing.ipsList_reset.ipsType_center.ipsList_inline
```
