### ISSUE TITLE
Mobilna apka github ukrywa teksty w <ul>, <ol>, nie wyświetla <hr> i psuje listy <dl> - zalecane czytanie zgłoszeń w przeglądarce

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#16895]
### Przykład:

```html
<ul>
niewidoczny tekst w apce - efekt pustej linii...
</ul>
```

```html
<dl>
  <dt>Tekst</dt>
    <dd>widoczny</dd>
  <dt>jednym</dt>
    <dd>ciągiem...</dd>
</dl> 
```

### Podgląd (linia pomiędzy jest ukrywana w apce):

(...)<ul>niewidoczny tekst w apce - efekt pustej linii...</ul>(...)

---

(...)<dl>
  <dt>Tekst</dt>
    <dd>widoczny</dd>
  <dt>jednym</dt>
    <dd>ciągiem...</dd>
</dl> 
(...)

### Obejścia na obecną chwilę np. zrobić cytowanie:

```html
> <ul>
> niewidoczny tekst w apce
> </ul>
```

> <ul>
> już jestem widoczny w mobilnej apce...
> </ul>

Dla `<dl>`/`<hr>` nie ma chwilowo ratunku.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/16894

**Comment by xxcriticxx** [comment]
na iphone dziala poprawnie

**Comment by krystian3w** [comment]
Jak działa poprawnie, zainstalowałeś a nie użyłeś na skróty Safari?

https://github.com/mobile

https://apps.apple.com/app/github/id1477376905?ls=1

**Comment by krystian3w** [comment]
<-- ![Screenshot_2020-07-25-20-50-51.png](https://user-images.githubusercontent.com/35370833/88464125-8e9a4280-ceb8-11ea-93a7-ae74868774f9.png) -->

**Comment by xxcriticxx** [comment]
![D16D7FB9-2F3B-4EB4-A2DA-95CB9032E0A0](https://user-images.githubusercontent.com/15007183/88464186-bbcdfd00-ce86-11ea-9218-6cff73eb5f2d.png)

**Comment by krystian3w** [comment]
źle przewinięte, zjedź do "Podgląd" i wtedy wrzuć dopiero.

**Comment by xxcriticxx** [comment]
![BAD324F6-E74B-4FB3-B06D-CB253219483D](https://user-images.githubusercontent.com/15007183/88464245-267f3880-ce87-11ea-8d8d-1caad1f0cf90.png)

**Comment by krystian3w** [comment]
Czyli tylko w apce na Android szwankuje coś już od wydania 0.9.x; beta 1.2.9 wyświetla jak stabilna 1.2.8 (z błedami)

**Comment by hawkeye116477** [comment]
@krystian3w https://github.com/contact

**Comment by krystian3w** [comment]
Mail już wysłany, ale ile osób aktualizuje a pewnie nie naprawią po stronie serwera tak jak to robi Facebook i Google (np. Youtube)...

**Comment by krystian3w** [comment]
Nie naprawili, dalej treści nie widać i ktoś może zamknąć zgłoszenie z mobilka, bo brak PC / przeglądarki mobilnej.
