### ISSUE TITLE
tko.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16893]
Nie działa przewijanie strony.

**Comment by hawkeye116477** [comment]
A jakieś więcej informacji, kto zawinił? Od razu mówię, że raczej nie polskie listy i odsyłam do lektury => https://github.com/gorhill/uBlock/wiki/The-logger :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 nie pomozesz dla kolegi?

**Comment by hawkeye116477** [comment]
Już mu pomogłem wskazując poradnik do loggera. Jeżeli jest błąd, to sam powinien też trochę popracować :smile:.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/88304743-f01baf00-cd08-11ea-8bdc-45cedb548bb1.png) |
--- |
a bo jest pop-up

Polskie EI niby takie teraz zostawia.

Błąd pewnie robi ktoś takim dziwadłem: `##[data-popmake*="cookies"]` jako generyk, pewnie EasyList Cookies (dawne Cookiemonster).

naprawa w filtrach własnych z uBO 1.20+ (scalenie pr chyba się przeciąga dla PaleMoon / Bazyliszka / Waterfox Classic):

```
tko.pl##.popmake-overlay[data-popmake*="cookies"]:remove()
```

**Comment by krystian3w** [comment]
```
##.pum-open:style(overflow: auto !important;)
##.pum[data-popmake*="uczelnia"]
```

Jak @MajkiIT będzie chciał wyciąć w suplementach uBO/AdGuard.

**Comment by hawkeye116477** [comment]
Odnośnie https://github.com/MajkiIT/polish-ads-filter/issues/16893#issuecomment-663070776, jeżeli chodzi o Waterfox Classic, to obsługuje on również wersję webextension, więc nie ma problemu :smile:.

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/0fe92ed52ca8fe78f9a6ef4dff2b28ad8d25d11d#diff-ca815c4f5fe404637a9387f434740d25
