### ISSUE TITLE
wyszkowiak.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#16901]
Kontenery / napisy po reklamach:

![capture_059_28-07-2020_15-25-18](https://user-images.githubusercontent.com/63287518/88671537-b373fd00-d0e6-11ea-8f54-a92137609e23.gif)

![capture_058_28-07-2020_15-24-18](https://user-images.githubusercontent.com/63287518/88671542-b4a52a00-d0e6-11ea-9253-48920c17e2f4.gif)

![capture_061_28-07-2020_19-43-49](https://user-images.githubusercontent.com/63287518/88701758-c0a2e300-d10a-11ea-9e90-284b29511fa9.gif)

**Comment by MajkiIT** [comment]
`##.introAfterNewsAds`

**Comment by gargul2** [comment]
Ok, ale to usunie tylko 2 napisy "reklama", ale nie usunie:
- kontenera po reklamie...więc na kontener też trzeba jakiś filtr: `wyszkowiak.pl##.introAds`
- kolejnego napisu "reklama", który dopiero teraz zauważyłem (dokleiłem screenshot do pierwszego komentarza na samym dole), i na ten napis trzebaby: `wyszkowiak.pl##.introMiddleAds`

Więc tak sumarycznie: `wyszkowiak.pl##.introAds, .introMiddleAds, .introAfterNewsAds`
albo po prostu: `wyszkowiak.pl##[class*="Ads"]`
