### ISSUE TITLE
www.mbank.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#16900]
@@||www.googletagmanager.com/gtm.js$script,domain=www.mbank.pl

test link:
https://www.mbank.pl/placowki-bankomaty/#indywidualni-i-firmy_placowki

**Comment by krystian3w** [comment]
Z linkiem lepiej, widać Google dostarcza dziwnie mapę lub przekombinowali.

**Comment by MajkiIT** [comment]
@krystian3w No chyba, nie myślałeś, że chce to odblokować bez powodu? Napisałem do mbank czy są świadomi tego.

**Comment by Lukjan37** [comment]
zglaszam inny problem

nie moge wejsc do ustawien i innych podston w systemie

"mBank
Nastąpił bład podczas pobierania zasobów mBanku. Mogły one zostać zablokowane przez firewall, proxy albo konfigurację przeglądarki. Naciśnij Ctrl+F5 lub Ctrl+Shift+F5 by spróbować jeszcze raz"

**Comment by krystian3w** [comment]
Test z wyłączonym filtrowaniem, jak załaduje się to może cudem uwala uBlock Origin lub jak masz uruchomione jakieś Pi-Hole.

Komunikat raczej wskazuje na problem ogólny z internetem w Operze lub problemy z serwerami mBanku...?

**Comment by Lukjan37** [comment]
jak dodam mbank do wyjatkow, to jest ok.

**Comment by krystian3w** [comment]
1. Cofnij wyjątki.

2. Włącz więc rejestrator: ![Przechwytywanie](https://user-images.githubusercontent.com/35370833/91178729-d85b9000-e6e5-11ea-9de9-bb61916c9611.JPG)

3. w polu "wyszukiwania" zaznacz "zablokowane"

4. potem wybierz opcje eksportu:  ![Przechwytywanie](https://user-images.githubusercontent.com/35370833/91178828-03de7a80-e6e6-11ea-8d51-9780b469056e.JPG)

5. wybierz formatowanie jako tabela i kod wklej w taki tekst:

```
<!--

(tu wklej)

-->
```



tak by nie każdy go zobaczył.

**Comment by krystian3w** [comment]
Logger pokazał tylko zablokowany z pomocą EasyPrivacy:

`/fingerprint.js`

spróbuj dodać taki:
```
@@/fingerprint.js$domain=mbank.pl
```

Jak nie pomoże to muszę sprawdzić jak się zapisują przekierowania w eksportowanym "pliku" tekstowym.

**Comment by Lukjan37** [comment]
jest, dodaj.

**Comment by krystian3w** [comment]
A usuń i zrób `Ctrl+F5`  lub `Ctrl+Shift+F5`, może jednak to błąd poza zasięgiem uBlock Origin?

**Comment by Lukjan37** [comment]
niestety nie, dodaj.

**Comment by krystian3w** [comment]
@MajkiIT dodasz:

`@@/fingerprint.js$domain=online.mbank.pl`

to pod:

https://github.com/MajkiIT/polish-ads-filter/blob/809c86140a71c377a50bb1fb46bd2b40e2ba8842/polish-adblock-filters/adblock.txt#L4771

w  EasyPrivacy pewnie bez nagrania, że strona pada nie przejdzie.

**Comment by Lukjan38** [comment]
w systemie transakcyjnym, brak gornego paska z podstronami
