### ISSUE TITLE
naszemiasto.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#16929]
`https://naszemiasto.pl/instagram-malgorzaty-sochy/ar/c11p1-20546603`

<div align="center">

[![https://i.imgur.com/yq6os06.png](https://i.imgur.com/LQ8wgcB.png)](https://i.imgur.com/yq6os06.png "https://i.imgur.com/yq6os06.png") |
--- |
miniaturka, kliknij ją aby powiększyć

</div>

Brzydka reklama wciśnięta w artykuł.

```
naszemiasto.pl#?#.componentsArticleContent hr:-abp-has(~ h3 > a[href*="ceneo.pl"])
naszemiasto.pl#?#.componentsArticleContent hr:-abp-has(~ p strong:-abp-contains(doskonałe))
naszemiasto.pl#?#.componentsArticleContent hr ~ p:-abp-has(strong:-abp-contains(doskonałe))
naszemiasto.pl#?#.componentsArticleContent ul:-abp-has(a[href*="ceneo.pl"])
naszemiasto.pl##.componentsArticleContent a[href*="ceneo.pl"]
```

Jak ktoś ma lepszy pomysł to może próbować podrzucić, sam już testowałem np. `upward` i za mocno wytnie.

Dużo utrudnia sprawdzanie `:-abp-has(~`, wtedy odpada łączenie podobnych.

**Comment by MajkiIT** [comment]
@krystian3w Dzięki
