### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#1692]
Reklamy:

http://imgur.com/a/tt4Th

**Comment by MajkiIT** [comment]
Może coś takiego
`elektroda.pl##.the-content.col-md-8 > [style="float: left"]`
`elektroda.pl##[style="float: left; position: relative;"]`
`elektroda.pl##.sec-ads`

**Comment by xxcriticxx** [comment]
@MajkiIT fitry dobre po prawej masz jeszcze zakladke `ADVERTISING`

**Comment by MajkiIT** [comment]
elektroda.pl##.button

**Comment by xxcriticxx** [comment]
elektroda is good

ja zakupuje produkty od mouser ikonka w prawym rogu
