### ISSUE TITLE
newsweek.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#16930]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/89688397-5e17c700-d902-11ea-86bf-7ce41186ff36.png)

-->

![obraz](https://user-images.githubusercontent.com/32641928/89688415-696af280-d902-11ea-8a37-10b345ef3cf7.png)

Przy włączonym uBlock'u nie wyświetla się cały tekst i obrazki na stronie.

### Link bezpośredni 
https://www.newsweek.pl/polska/spoleczenstwo/wakacje-2020-polacy-wyjezdzaja-mniej-niz-rok-temu-za-to-nad-morze-chetniej/7fln5br

### Co trzeba zrobić, aby pojawił się błąd?
1. Wejść na strone

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox

**Rozszerzenia i skrypty:** 
uBlock
NanoDefender

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Fuck Fuckadblock
4. I don't care about cookies 
5. AdGuard
6. Fanboy’s Enhanced Tracking List 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Wyłącz `Fuck Fuckadblock` (może pan z Rosji zaszalał i wyciął za dużo "regexem") i "AdGuard" (na przyszłość pisz jakie, bo są nawet regionalne wersje).

**Comment by krystian3w** [comment]
Tego może nie widzisz?

![obraz](https://user-images.githubusercontent.com/35370833/89717223-94158380-d9b4-11ea-8348-d9f4b682c2a5.png)


ale to jest prenumerata i wycina ją teraz polskie EI, mniej więcej zgrało to się z upadkiem "Polskich filtrów wewnętrznych" (może przyczyna ich skasowania).

**Comment by Barticf** [comment]
@krystian3w nie wyświetla się mi takie (ublock wyłączony jak i włączony).

**Comment by krystian3w** [comment]
> Jak wyłączę Fanboy’s Enhanced Tracking List to jest ok

a o tym nie ma mowy w "zasubskrybowanych", wrzucaj zrzut z zakładki aktywnych filtrów może.

Zgłoszenie błędu jak znasz angielski przyklej tutaj:  https://github.com/ryanbr/fanboy-adblock/issues 

https://github.com/ryanbr/fanboy-adblock/issues/new/choose
