### ISSUE TITLE
wnp.pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#16944]
Witam czy można tą reklamę zablokować.

https://www.wnp.pl/

**Comment by xMaap** [comment]
Nie widzę reklam

**Comment by kolor33** [comment]
Rodo
![1](https://user-images.githubusercontent.com/32041737/90049398-08ae3200-dcd5-11ea-86a2-7879b5bb5225.jpg)

**Comment by xMaap** [comment]
https://majkiit.github.io/polish-ads-filter/ i dodaj Polskie Filtry RODO-Ciasteczkowe lub Polskie Filtry Elementów Irytujących

**Comment by kolor33** [comment]
No i działa .Mam I do not care about cookies .Ale tego nie widzi.

**Comment by krystian3w** [comment]
Może nie widzieć, nie ma obowiązku tam zgłaszać wszystkiego ani on raczej nie jest chętny by cały projekt `Polskie Filtry RODO-Ciasteczkowe` wciągnąć na raz (pewnie z kilka dni by zajęło racjonalne scalenie filtrów).

My do niego głównie zgłaszamy bugi z jego filtrami lub jak się ma czas by w swoim rozszerzeniu rozważył wycinanie jakiś z zablokowanym przewijaniem - on reguł CSS nie pisze i takie coś już wkleja w dodatek.

**Comment by xxcriticxx** [comment]
@kolor33 nastepnym razem prosimy o wypelnienie templetu!

**Comment by krystian3w** [comment]
Ale to twój fail, pop-up rodo dawno wycięty, nie wyciekł, nie wymaga ulepszenia.

**Comment by gargul2** [comment]
Prenumerata: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2470
