### ISSUE TITLE
cuk.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16941]
Ukrywa
![2020-08-11 13 09 16 cuk pl 63db218988b6](https://user-images.githubusercontent.com/36385327/89890578-e680bb00-dbd3-11ea-9d90-c772c6f6f2e3.png)

**Comment by hawkeye116477** [comment]
U mnie wszystko ok.

**Comment by krystian3w** [comment]
Sprawdź, wyłączając `lista` po `liście` to co masz niestandardowe.

Za każdą dezaktywacją <kbd>Ctrl</kbd>+<kbd>F5</kbd> strony. Opcjonalnie nawala net...

---

Wstępnie wykluczone polskie filtry (poza "polskie filtry wewnętrzne" i "EasyList Polish" z "znanych").
Wkluczone też "AdGuard Annoyance/Social Media", "fanboy Annoaynce", "Spam404", stare usunięte listy "anty-malware".

**Comment by xMaap** [comment]
Po wyłączeniu "uBlock filters – Unbreak" jest tak jak powinno.

**Comment by krystian3w** [comment]
Czyli coś się zepsuło w uBO 1.28.X i pewnie 1.29.X też.

**Comment by hawkeye116477** [comment]
@xxcriticxx Czyli do zamknięcia, a sprawa do gorhilla...
