### ISSUE TITLE
google.pl | google.com

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#16947]
<dl>

<dt>

### URL:

</dt><dd>

`https://www.google.com/search?q=myszka+ps/2`
`https://www.google.pl/search?q=myszka+ps/2`

</dd><dt>

### Filtr:

</dt><dd>

```
google.com,google.pl##div[data-ismultirow="true"][data-id^="CarouselPLA-"] 
```

</dd><dt>

### Co się stało...:

<dt><dd>

Nowe reklamy kolumnowe testowane na terenie Polski:

> 
> ![](https://user-images.githubusercontent.com/35370833/90314704-038bf580-df16-11ea-8abd-4760bd0abff1.png) |
> --- |
>

Jak długo nie będą globalne - tak długo nie trafią one do np. `uBlock Filters` lub ogólnego `EasyList`.

</dd></dl>

**Comment by hawkeye116477** [comment]
Ja tego nie mam, no chyba, że uznają, że mam nie polskie IP, bo kiedyś już tak z jakąś stroną było, pomimo, że jednak mam polskie....

**Comment by MajkiIT** [comment]
@krystian3w dzięki
@hawkeye116477 Na moje oko to nie zawsze się pojawia. Wczoraj tego nie miałem a dzisiaj się nagle pojawiło.
