### ISSUE TITLE
donald.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16943]
Social + cookies
![2020-08-12 16 12 57 www donald pl 8e6a98912b2f](https://user-images.githubusercontent.com/36385327/90025830-df7ea900-dcb6-11ea-9c29-acf64f0f505e.png)
![2020-08-12 16 13 08 www donald pl 2232234b7eeb](https://user-images.githubusercontent.com/36385327/90025837-e1486c80-dcb6-11ea-911f-d07dfc0b583f.png)

**Comment by krystian3w** [comment]
Oraz białe dziury po reklamach Google - klasy losowe "`sc-`".

@MajkiIT zobacz taki filtr:

`donald.pl##div[data-component="Ad"]`
