### ISSUE TITLE
efilmy.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1694]
15 sec timer jest na kazdym filmie 

example

`http://www.efilmy.tv/film,30057,Sully-2016-Lektor-PL.html`

**Comment by F4z** [comment]
Nie widzę tego.
To znaczy widzę, jak wyłączę reguły kosmetyczne, więc jest już blokowane przez którąś z reguł.

**Comment by xxcriticxx** [comment]
@F4z reklamy niewidze ale czas dalej odlicza

**Comment by F4z** [comment]
@xxcriticxx nie widzę tego u siebie. Możesz kliknąć prawym przyciskiem myszy na to odliczanie, potem z menu wybrać "Zbadaj" i zrobić screena tak żeby widział ten element odliczania?
Tak jak na obrazku poniżej.
![image](https://cloud.githubusercontent.com/assets/11742596/21296138/b5c6dd8e-c564-11e6-999a-198579087851.png)

**Comment by xxcriticxx** [comment]
@F4z niemoge nic teraz nalesc ale wyglonda to tak u ciebie tylko umnie odlicza na dole

**Comment by xxcriticxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/15007183/21296504/75acc8f4-c53b-11e6-9950-5d97baf06ff8.PNG)

**Comment by F4z** [comment]
Na tym obrazku nie widzę żadnego odliczania, a patrząc na kod strony, to ta reguła - `efilmy.tv##.addbackground` - powinna to ukrywać.

**Comment by xxcriticxx** [comment]
Licznik zniknal zanim zrobilem screen shot nie lepjej by bylo zrobic supplementem filtrem zeby nie odliczalo?

**Comment by F4z** [comment]
Ale w tym przypadku to powinno dać się ukryć przy użyciu zwykłej reguły, u mnie ta reguła to ukrywa - `efilmy.tv##.addbackground` i nie muszę czekać.
W Firefoxie masz włączoną (i zaktualizowaną) polską listę i włączone filtry kosmetyczne w uBlocku?

**Comment by xxcriticxx** [comment]
Hyba tak
