### ISSUE TITLE
poczta-polska.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16958]
https://www.poczta-polska.pl
Włączony
![2020-08-23 07 23 32 www poczta-polska pl fb3d330009ae](https://user-images.githubusercontent.com/36385327/90971580-a4c80c80-e511-11ea-9a6e-ef9ebdda67b1.png)
Wyłączony
![2020-08-23 07 23 44 www poczta-polska pl 10a761e7eb04](https://user-images.githubusercontent.com/36385327/90971582-a85b9380-e511-11ea-9cb3-56bac5a3f7f6.png)

https://www.pocztex.pl
Włączony
![2020-08-23 07 24 58 www pocztex pl e89d7ff7dafc](https://user-images.githubusercontent.com/36385327/90971597-d0e38d80-e511-11ea-8e81-d2fedab8dcf4.png)
Wyłączony
![2020-08-23 07 25 14 www pocztex pl 1df054d61ae7](https://user-images.githubusercontent.com/36385327/90971600-d50fab00-e511-11ea-8474-031e1359e6ee.png)

http://www.pocztapolskarodzina.pl
Social
![2020-08-23 07 26 00 www pocztapolskarodzina pl e5b2cfa63721](https://user-images.githubusercontent.com/36385327/90971612-ebb60200-e511-11ea-963f-7c39cd1b147d.png)

**Comment by krystian3w** [comment]
@MajkiIT slidery uwala:

```
www.poczta-polska.pl#@#.active.item
```
