### ISSUE TITLE
sport.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1695]
Pozostałość po reklamie - `http://www.sport.pl/`

![image](https://cloud.githubusercontent.com/assets/11742596/21296799/0340f4aa-c574-11e6-87bd-af43d4fbe36c.png)

Podobne rzeczy są też na `gazeta.pl`, `wyborcza.pl` i podobnych, więc myślę, że można dodać tę regułę jako ogólną:
`##.adviewDFPBanner`

**Comment by xxcriticxx** [comment]
Kiedy update listy?
