### ISSUE TITLE
wiadomosciwarminskie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16962]
![2020-08-24 01 25 54 wiadomosciwarminskie pl ae69abe7b493](https://user-images.githubusercontent.com/36385327/90991345-ca542500-e5a8-11ea-9718-b4f345de00bd.png)

**Comment by MajkiIT** [comment]
`wiadomosciwarminskie.pl##.tdi_62_eed.vc_raw_html.td_block_wrap.wpb_wrapper`
