### ISSUE TITLE
gry-online.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1696]
Tylko u mnie po uruchomieniu wideo, obraz jest cały czarny/biały i słychać tylko dźwięk?
Link - `http://www.gry-online.pl/S013.asp?ID=101722`
Ten problem występuję głównie w Google Chrome, w Mozilli Firefox nie zawsze tak się dzieje.

![image](https://cloud.githubusercontent.com/assets/11742596/21297016/5fb3b1e2-c578-11e6-904b-3bdac0dc9cdc.png)

Po dodaniu tej reguły widać normalnie filmik:
`gry-online.pl#@#[class$="-ads"]`

**Comment by xxcriticxx** [comment]
A to na nodle pod filmem gol newsroom?

**Comment by F4z** [comment]
Myślę, że takie rzeczy, to raczej powinny być blokowane przez listę "Adblock polskie reguly social".

**Comment by xxcriticxx** [comment]
Ahh to @blocker999 sie tym zajmie

**Comment by F4z** [comment]
A film działa u Ciebie normalnie, czy musisz dodać regułę żeby nie był czarny/biały obraz?

**Comment by xxcriticxx** [comment]
na iphone i adguardem pro nie dziala 
na latopie z ubuntu dziala 
na win7 dziala

**Comment by F4z** [comment]
Ale Firefox czy Chrome?

**Comment by F4z** [comment]
W przypadku Firefoxa u mnie problem był raz kilka odświeżeń albo i rzadziej.
W Chrome za każdym razem tak się dzieje, to samo w Operze.

**Comment by xxcriticxx** [comment]
chrome mam w robocje jutro sprawdze

**Comment by F4z** [comment]
Ok

**Comment by xxcriticxx** [comment]
@F4z moment zaraz do roboty sie podloncze i sprawdze

**Comment by xxcriticxx** [comment]
@F4z testowalem na chrom z adblock plus i dziala bez problemu

**Comment by F4z** [comment]
@xxcriticxx dzięki za sprawdzenie.
U mnie z Adblock Plus też działa bez problemu, ale w Chrome z uBlock Origin mam czarny obraz.

**Comment by xxcriticxx** [comment]
@F4z moment zaraz zamontuje

**Comment by xxcriticxx** [comment]
@F4z tak jak pisales czarny obraz

**Comment by F4z** [comment]
@xxcriticxx ok, dzięki za sprawdzenie :)

**Comment by xxcriticxx** [comment]
@F4z dziala jak wylonczysz polska liste albo wlonczona polska lista i twoja regula ` gry-online.pl#@#[class$="-ads"]` czyli trzeba nasze filtry nata strone zobaczyc

**Comment by F4z** [comment]
@xxcriticxx no tak, to przez regułę z polskiej listy, tylko zastanawiam się czemu nie ma tego problemu jak korzysta się z Adblocka Plus.

**Comment by xxcriticxx** [comment]
@F4z albo czemu jest ok na firefoxie

**Comment by F4z** [comment]
U mnie co któreś odświeżenie na Firefoxie jest ten sam problem.

**Comment by xxcriticxx** [comment]
jest moze jakas genetic rule co przeszkadza
