### ISSUE TITLE
zdrowie.pap.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16969]
https://zdrowie.pap.pl
Źle ukryty social od Twittera
![2020-08-24 07 58 38 zdrowie pap pl dd07a878f4e6](https://user-images.githubusercontent.com/36385327/91008975-d0192d00-e5df-11ea-9ba6-2d68619cb782.png)

http://serwis.pap.com.pl
![2020-08-24 08 00 49 serwis pap com pl eae0687a5643](https://user-images.githubusercontent.com/36385327/91009031-f212af80-e5df-11ea-8e75-746af154c507.png)

https://dzieje.pl
Social
![2020-08-24 08 01 20 dzieje pl 7189cd44a7e7](https://user-images.githubusercontent.com/36385327/91009182-4f0e6580-e5e0-11ea-9bd1-9195f9aba313.png)

**Comment by krystian3w** [comment]
Nie źle, ale wcale, ja widzę a nie że została klikalność.
