### ISSUE TITLE
transfery.info

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16973]
`https://transfery.info/aktualnosci/dlaczego-messi-uzyl-faksu-do-poinformowania-barcelony-o-swojej-decyzji/139504`

![2020-08-26 08 59 32 transfery info 59645acb528e](https://user-images.githubusercontent.com/36385327/91271537-a34d4d00-e77a-11ea-9a25-c4cf70af6928.png)
![2020-08-26 08 59 59 transfery info 8db9eaa9cc3d](https://user-images.githubusercontent.com/36385327/91271578-b2cc9600-e77a-11ea-89cb-c893ae4ba6a4.png)

**Comment by krystian3w** [comment]
`##a > .fab.media-icon` i znikają wszystkie.
