### ISSUE TITLE
allegro.pl

### ISSUE THREAD

**Issue by jstasiak** [MajkiIT/polish-ads-filter#16998]
Na Allegro nie są blokowane "Oferty sponsorowane". Np. pod adresem https://allegro.pl/kategoria/sprzet-estradowy-studyjny-i-dj-ski widać coś takiego (uBlock Origin, polish-ads-filter włączone):

<img width="1325" alt="Screenshot 2020-08-31 at 23 13 28" src="https://user-images.githubusercontent.com/36209/91769515-d3b04380-ebdf-11ea-9ad7-bcc3d7b8430e.png">

(Oferty sponsorowane wrzucone są też losowo między listingi, nie tylko na górze czy na dole strony.)

uBlock pozwala na użycie takiego filtra, niestety nie znam lepszego sposobu niż `has-text`:

```
allegro.pl##article>div:has-text(Oferta sponsorowana)
```

Sytuacja wygląda wtedy tak:

<img width="1294" alt="Screenshot 2020-08-31 at 23 13 48" src="https://user-images.githubusercontent.com/36209/91769526-d90d8e00-ebdf-11ea-950e-0bdd10800081.png">

**Comment by gargul2** [comment]
Od tego jest inna lista: https://github.com/maciejtarmas/AlleBlock/issues/48, tylko od pewnego czasu jest w zastoju i ponoć we wrześniu miało cos ruszyć, no i już zaczął się wrzesień, więc zobaczymy.

**Comment by MajkiIT** [comment]
@jstasiak trzeba by było dodać komplet . Pytanie czy wrzucamy do filtrów zanim @maciejtarmas wróci ze swoją listą ?
```
allegro.pl##article>div:has-text(Oferta sponsorowana)
allegro.pl##h2:has-text(Oferty promowane)
```

**Comment by gargul2** [comment]
> jstasiak :
> uBlock pozwala na użycie takiego filtra, niestety nie znam lepszego sposobu niż has-text:
> `allegro.pl##article>div:has-text(Oferta sponsorowana)`

> MajkiIT :
> `allegro.pl##article>div:has-text(Oferta sponsorowana)`
> `allegro.pl##h2:has-text(Oferty promowane)`

- po pierwsze `:has` nie jest kompatybline z Adblockiem, więc jak już to `:-abp-contains`
- po drugie, jeśli chodzi o ten pierwszy to można lepszy bez potrzeby proceduralnych: 
`allegro.pl##[data-analytics-view-label="showSponsoredItems"]`

**Comment by gargul2** [comment]
Poza tym:
-  "Oferta sponsorowana": to raczej reklama wewnętrzna, a takie zdaje się na tym repo nie są blokowane
-  "Oferta sponsorowana" poza dodatkową etykieta "Oferta sponsorowana" jest w dalszym ciągu normalną ofertą, któej zablokowanie uniemożliwi zakup produktu...mogą być skragi i proces sądowy od Allegro
-  "Oferta sponsorowana" to praktycznie to samo co "Oferta promowana" tylko znajduje się jeszcze wyżej niż "Oferta promowana" więc skoro blokować "Sponsorowane" to na tej samej zasadzie trzebaby bokować również "Promowane" a że, "Promowanych" jest jeszcze więcej niż "Sponsorowancych to tymbardziej uniemożliwi wielu osobom zakup wielu legalnych produktów

**Comment by MajkiIT** [comment]
@gargul2 Ok

```
allegro.pl#?#h2:-abp-contains(Oferty promowane)
allegro.pl##[data-analytics-view-label="showSponsoredItems"]
```

**Comment by jstasiak** [comment]
Wrzuciłem też pull requesta do tamtego repozytorium, ale stwierdziłem, że zduplikuję go tutaj. Nie pogniewam się za zamknięcie tego tematu jeżeli faktycznie ten filtr tu nie pasuje za bardzo.

Potwierdzam, że `allegro.pl##[data-analytics-view-label="showSponsoredItems"]` działa, co mnie cieszy. To nie usuwa, z tego co wiem, istniejących normalnych aukcji tylko sponsorowane linki do nich, np.:

https://allegro.pl/kategoria/sprzet-estradowy-studyjny-i-dj-ski?string=naro%C5%BCnik%20akustyczny

<img width="1303" alt="Screenshot 2020-09-01 at 13 57 20" src="https://user-images.githubusercontent.com/36209/91848670-18c58b80-ec5b-11ea-9a76-fe2e291402de.png">

Ta oferta sponsorowana to link do https://allegro.pl/events/clicks?(...) co przekierowuje do https://allegro.pl/oferta/naroznik-akustyczny-pulapka-basowa-pb-mp-120x20cm-6490201656?(...) a na liście promowanych ofert jest https://allegro.pl/oferta/naroznik-akustyczny-pulapka-basowa-pb-mp-120x20cm-6490201656 co jest dokładnie tą samą ofertą.

Z tego co widzę nie ma ryzyka, że to komuś ukryje normalną aukcję i nie pozwoli kupić czegoś, ale mogłem o czymś nie pomyśleć.

Nie proponowałem ukrywania nagłówka "Oferty promowane", bo z tym za bardzo nie da się nic zrobić – samo ukrycie nagłówka sprawia, że dalej są dwie listy ofert, ale teraz pierwsza nie ma w ogóle żadnego opisu i człowiek się może zastanawiać, gdzie jest w ogóle.

**Comment by krystian3w** [comment]
AdGuard nie poleca wycinać nic sponsorowanego, raz argumentem było, że to są lepsze rzeczy niż cała reszta wyszukana.

Lista indonezyjsko-malezyjska też nie usunęła 20 sponsorowanych bloków tytoniu a zgłoszenie w AdGuard zamknięto.

**Comment by xxcriticxx** [comment]
oczywiscie mozna sprobowac zakupow na ebay.com

**Comment by zaba-monika** [comment]
Zgłoszenie kwalifikuje się na inną listę: https://github.com/maciejtarmas/AlleBlock, ale ta inna lista niestety coś ostatnio nie jest już rozwijana: https://github.com/maciejtarmas/AlleBlock/issues/48.

**Comment by krystian3w** [comment]
Niby teraz MajkiIT lub EasyList ukrywa sekcje sponosorowane pod opisem produktu: #17481
