### ISSUE TITLE
artsandculture.google.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16996]
https://artsandculture.google.com/partner/muzeum-narodowe-w-warszawie?hl=pl
![2020-08-31 11 27 00 artsandculture google com 77c278feb22b](https://user-images.githubusercontent.com/36385327/91705161-e6456100-eb7c-11ea-8847-655b4b99ad10.png)

**Comment by krystian3w** [comment]
@hawkeye116477 / @blocker999 

czy program `Classroom` to już media społecznościowe - moim zdaniem nie:

![Przechwytywanie](https://user-images.githubusercontent.com/35370833/91715772-aa1afc00-eb8e-11ea-8666-0cc05ec90677.JPG)

**Comment by hawkeye116477** [comment]
Nie.
