### ISSUE TITLE
placowki.poczta-polska.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#16997]
Klikalny social + ukryta ikona do Blog
```
https://placowki.poczta-polska.pl
https://kody.poczta-polska.pl/#/
https://rtv.poczta-polska.pl
https://cennik.poczta-polska.pl
https://eformularze.poczta-polska.pl
https://emonitoring.poczta-polska.pl
https://skrzynki.poczta-polska.pl
https://skrzynki.poczta-polska.pl
```
![2020-08-31 11 33 57 placowki poczta-polska pl 42e3cd77a8c4](https://user-images.githubusercontent.com/36385327/91706334-8c459b00-eb7e-11ea-8e54-11f72cc35536.png)

http://blog.poczta-polska.pl
![2020-08-31 11 38 13 blog poczta-polska pl 96b3c450bf02](https://user-images.githubusercontent.com/36385327/91706278-789a3480-eb7e-11ea-9a75-f0ca6dc9c8b5.png)

**Comment by krystian3w** [comment]
Blog - social - @hawkeye116477 ukrył kilka w przeszłości.

**Comment by krystian3w** [comment]
A informacji może szukaj na BIP-ie niż blogu:

http://bip.poczta-polska.pl/

**Comment by hawkeye116477** [comment]
Zgadza się, Fanboy jak i również my, uznajemy blogi za elementy społecznościowe.
