### ISSUE TITLE
niezalezna.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#17001]
Mam pytanie - czy to błąd czy to reklama i tak ma zostać:

1 tak jest teraz
![capture_002_02-09-2020_12-57-59](https://user-images.githubusercontent.com/63287518/91973142-01020c00-ed1c-11ea-9c41-a118d3cd641b.gif)

2 a tak jest po dodaniu: `@@/images/ads/puszczatv/*$image,domain=niezalezna.pl`

![capture_003_02-09-2020_12-58-21](https://user-images.githubusercontent.com/63287518/91973151-065f5680-ed1c-11ea-9c7e-8216252817af.gif)

**Comment by MajkiIT** [comment]
To raczej błąd. Już poprawiam.

**Comment by blocker999** [comment]
jeszcze dorzucam fb tu : https://niezalezna.pl/humor/1243-z-tym-zamachem-na-czajke-to-jednak-prawda i tu : https://niezalezna.pl/349630-zakaz-pisania-przez-rok-o-bonku-sad-knebluje-dziennikarza-gazety-polskiej
