### ISSUE TITLE
interpals.net

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#17005]
Co zablokuje po odświeżeniu wraca .Jakaś blokada .

=================
You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page.
======================

**Comment by xxcriticxx** [comment]
brak wersji polskiej

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues

i po angielsku, nie kasuj wzoru zgłoszenia a wypełniaj luki.
