### ISSUE TITLE
reebok.pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#17006]
Wyświetla mi pytanie o cookies. 

=================
Śledzące pliki cookie mające na celu zapewnienie najlepszej obsługi klienta Reebok
==============

**Comment by krystian3w** [comment]
@olegwukr ogarnij śledzenie/tracking na adidas.pl i reebok.pl, najlepiej przed tym jak to zrobi **EasyPrivacy**:

* https://github.com/gorhill/uBlock/wiki/Resources-Library#cookie-removerjs-
* https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#-%EF%B8%8F-remove-cookie
\+ exclusive dla AdGuarda:
* https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#cookie-modifier

**Comment by kolor33** [comment]
Nie mam szans .Nie wiem jak to zablokować.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/17006#issuecomment-687618286

A ty jesteś "Oleg" z Ukrainy i rozwijasz **polskie filtry prywatności**?

**Comment by kolor33** [comment]
Nie olek z Ukrainy tylko Putin z Polski .żartuje .

zablokuj podaj regułę .Nie mam pojęcia jak to zablokować.

**Comment by krystian3w** [comment]
Nie specjalizuje się w blokowaniu śledzenia / trackingu, a pop-up "rodo" zniknie po scaleniu #17007  lub aktualizacji w uBo:

> ![obraz](https://user-images.githubusercontent.com/35370833/92307704-8c87d100-ef98-11ea-98dd-6ede68e899ef.png) |
> --- |

**Comment by kolor33** [comment]
Dzieki
