### ISSUE TITLE
meczlive.pl | meczenazywo.tv

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#17011]
pop-upy STS / `efortuna.pl` po kliknięciu raz w byle co.

see https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2494 by @gargul2
see https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2495 by @gargul2

https://user-images.githubusercontent.com/63287518/92321972-b55aa580-f02e-11ea-8c46-7a06af3a7dc5.gif
https://user-images.githubusercontent.com/63287518/92321972-b55aa580-f02e-11ea-8c46-7a06af3a7dc5.gif

Może jakiś regex?

---

Nie wiem czy to działa:
```
||account.efortuna.pl^$popup,domain=meczlive.pl|meczenazywo.tv
||www.sts.pl^$popup,domain=meczlive.pl|meczenazywo.tv
```

---

Jak to reklama wewnętrzna, to proszę o jakiś sensowny dowód.

**Comment by MajkiIT** [comment]
@krystian3w Dzięki. Na razie taka propozycja. Pełnego rozwiązania chwilowo nie widzę.

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/df71b193f4e96161843665711c8dfed72ede2415#diff-711027ed0794992ae3b8710d874f3df7

**Comment by hawkeye116477** [comment]
A nie ładnie, mecze ogląda się na C+ => https://kup.pl.canalplus.com/oferta/wybierz-pakiet albo na Polsacie/Eleven :smiley_cat:
