### ISSUE TITLE
GitHubowe Dyskusje

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#17018]
Są zapisy do bety „GitHub Discussions" na https://github.community/t/can-one-apply-for-github-discussions-beta/121120/153. Tutaj w kółko @xxcriticxx o czymś plotkuje, więc może warto zgłosić też to repozytorium, by plotki były w oddzielnej zakładce. Co sądzicie?

**Comment by krystian3w** [comment]
Niby jest jakaś wait lista na sponsorów:

https://github.com/sponsors/accounts - hmm... #16411

**Comment by MajkiIT** [comment]
@hawkeye116477 wydaje mi się, że warto dodać. Nic się nie traci.

**Comment by xxcriticxx** [comment]
gadu gadu

**Comment by hawkeye116477** [comment]
No to na co dyrek czeka? Kolejka się już ustawiła, trzeba napisać komentarz na forum GH by do niej dołączyć :smile:

**Comment by krystian3w** [comment]
Może zapisał się tylko na "sakiewką potrząśnij".

**Comment by krystian3w** [comment]
Na moje trzeba by Majkiego dodać na tego tajnego slacka gdzie pisze EasyList / Pingwin / Norweg "Krzysiek" / uAssets.

**Comment by MajkiIT** [comment]
@krystian3w Nawet nie wiedziałem, że coś takiego jest :D

**Comment by krystian3w** [comment]
Stwierdzili że `hub.filterlists.com` jest zbyt publiczne.

**Comment by hawkeye116477** [comment]
Dyrku czyli rozumiem, że rezygnujesz?

**Comment by krystian3w** [comment]
Pewnie liczył, że ty lub ja zgłoszą to repo, ale pewnie taki wniosek będzie nieważny.

**Comment by MajkiIT** [comment]
@hawkeye116477 @krystian3w dodałem już. Za jakiś czas się pojawi wpis. Dzięki za pogonienie.

**Comment by MajkiIT** [comment]
@hawkeye116477 @krystian3w @xxcriticxx mamy to ==> https://github.com/MajkiIT/polish-ads-filter/discussions

**Comment by krystian3w** [comment]
Wygląda jak z Gitlaba wycięte.

**Comment by hawkeye116477** [comment]
W GL nie ma dyskusji. Jest tylko dodatkowo Service Desk, ale to po prostu pokazuje zgłoszenia wysyłane na specjalnego maila.

**Comment by krystian3w** [comment]
Ciekawe czy "fix #17138" oznacza dyskusje za zamkniętą lub "odpowiedziano"...

> W GL nie ma dyskusji. 

Ale mają identyczny system komentowania w Issues / PR.
