### ISSUE TITLE
lubanski.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1703]
wp-content reklama na sub pages 

`http://www.lubanski.eu/category/kultura/`

**Comment by MajkiIT** [comment]
Nie widzę żadnych reklam

**Comment by xxcriticxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/15007183/21312458/2a52f642-c5ba-11e6-8f1a-389ad945f58d.PNG)
