### ISSUE TITLE
ticket.energylandia.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#17037]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/92644256-5a9da400-f2e3-11ea-8588-91bc3b835436.png)

### Link bezpośredni 

https://ticket.energylandia.pl/pl/tickets

### Co trzeba zrobić, aby pojawił się błąd?
1. Wejść na stronę
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Ciągłe ładowanie elementu strony. Wyłączenie filtra EasyPrivacy pomaga.

**Comment by MajkiIT** [comment]
@Barticf sprawdź po aktualizacji.

**Comment by gargul2** [comment]
majki widziałeś to czy nie https://github.com/MajkiIT/polish-ads-filter/commit/df71b193f4e96161843665711c8dfed72ede2415#commitcomment-42151457 bo nie wiem ile razy mam się powtarzać

**Comment by Barticf** [comment]
@MajkiIT teraz jest ok.

**Comment by MajkiIT** [comment]
@gargul2 napisałeś, zgłoszenia nie zamknąłem to wrócę. Spoko luz.
@Barticf Dzięki

**Comment by gargul2** [comment]
Luz jest, tylko w takim razie czemu to tak dziwnie wisi od 3 dni, kiedy do innych zgłoszeń wokół dodawane są filtry/commity i zamykane, dlatego wolałem się upewnić.
