### ISSUE TITLE
cda.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#17039]
Skoro Premium się jednak kwalifikują (https://github.com/MajkiIT/polish-ads-filter/issues/17038) to nie ma problemu,
reklamy Premium na podstronach z filmami np.: https://www.cda.pl/video/43769676a,
filtry pisane na kolanie:

`||www.cda.pl/iframe/premium/banner_freetime.html$subdocument,~third-party`
`www.cda.pl##.top-anonco-cont, .Light-top-region, .infoBox, .video-baner, #tVC, #footer1 > div > .pg-wrap > .pg-cc`

![Schowek01](https://user-images.githubusercontent.com/63287518/92891275-1e1f9480-f418-11ea-9541-b8f11c4cb541.gif)

**Comment by seba2282** [comment]
@krystian3w @MajkiIT zobaczycie?
