### ISSUE TITLE
puratos.pl/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#17040]
cookies are back!

**Comment by krystian3w** [comment]
Nie wydaj mi się by wróciły, po prostu źle wycinane przez Kiboke, zgłoszone na jego support:

https://www.i-dont-care-about-cookies.eu/report/3.2.1/https%253A%252F%252Fwww.puratos.pl%252Fpl

PS. on ma około 15 tysięcy zgłoszeń do przejrzenia.
