### ISSUE TITLE
zw.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17049]
Social
http://www.zw.com.pl/artykul/2,673298-Pierwszy-powazny-sprawdzian-dla-osmioklasistow.html
![2020-09-13 05 49 18 www zw com pl f21819a73975](https://user-images.githubusercontent.com/36385327/93009780-32cd6b00-f585-11ea-9463-ba15209f12e3.png)

https://kancelarierp.pl/nazwa-wirusa-jako-znak-towarowy/
![2020-09-13 05 52 03 kancelarierp pl b6c264b61f15](https://user-images.githubusercontent.com/36385327/93009785-4ed10c80-f585-11ea-8467-7a9f996cbe90.png)
![2020-09-13 05 52 16 kancelarierp pl 0b7f03ade11e](https://user-images.githubusercontent.com/36385327/93009787-509ad000-f585-11ea-93e7-45088bf531cf.png)

RODO
https://www.parkiet.com
![2020-09-13 05 52 55 www parkiet com 05d562eb4d33](https://user-images.githubusercontent.com/36385327/93009793-61e3dc80-f585-11ea-8123-dab42ef71287.png)

**Comment by krystian3w** [comment]
**Części socialu brak...** - np. pole jest puste mimo że opcja drukuj i e-mail to nie social (`zw.com.pl`)

@xxcriticxx `parket.com` to jest ten sam podmiot co #17045 (`rp.pl`)  czyli @xMaap  musi go ręcznie tam zaakceptować lub jednym z dwóch dodatków:

* `Polska Ciasteczkowa Zgoda` - dodano kilkanie "dalej", potem w "zapisz" (zalecana ręcznie aktualizacja filtrów).
* IDCAC w formie dodatku - niby Kiboke częściej ogląda ich portale t.j. "Gremi Media"

**Comment by krystian3w** [comment]
`https://kancelarierp.pl/nazwa-wirusa-jako-znak-towarowy/ - `2020-09-13 05 52 03 kancelarierp pl b6c264b61f15`

Sprawdzić aktywność Fanboy Social @xMaap, możliwe że znów ci się **wyłączył** albo masz aktywne:

> - [x] Ignoruj ogólne filtry kosmetyczne 

(zalecane ręczne dezaktywowanie dla telefonów i tabletów), na PC powinno być nieaktywne a stary PC zmodernizować...

lub nieaktywne:

> - [ ] Przetwarzaj i stosuj filtry kosmetyczne 

Kto to włącza, to sam prosi się o kłopoty z wycinaniem reklam itp. generykami (będą wyciekać)...

**Comment by xMaap** [comment]
Dobra działa.

**Comment by krystian3w** [comment]
Niby uBO 1.29.3b16 robi postęp, ale takie coś może sprawiać, że pop-up będzie migać:

```css
rp.pl,parkiet.com##body:not(:has(iframe[src*="x-link.pl/"], iframe[src*="x-news.pl/"])) #rodo-popup > div:style(position: absolute !important; left: -9999px !important; top: -1000px !important;)
rp.pl,parkiet.com##body:not(:has(iframe[src*="x-link.pl/"], iframe[src*="x-news.pl/"])) #rodo-popup > div > div:style(position: absolute !important; left: -9999px !important; top: -1000px !important;)
```

Niby lepiej sprawdzać, może być powrót na x-link / x-news i glitch z pustymi dziurami po odtwarzaczach wrócić.
