### ISSUE TITLE
regiony.tvp.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17048]
Źle ukryte social
![2020-09-13 05 37 11 regiony tvp pl 2d69015640c9](https://user-images.githubusercontent.com/36385327/93009596-4d064980-f583-11ea-8acd-9db7f94d4687.png)

```
https://regiony.tvp.pl
https://gdansk.tvp.pl
https://bialystok.tvp.pl
https://katowice.tvp.pl
https://gorzow.tvp.pl
https://lodz.tvp.pl
https://rzeszow.tvp.pl
https://szczecin.tvp.pl
https://olsztyn.tvp.pl
https://kielce.tvp.pl
https://bydgoszcz.tvp.pl
https://krakow.tvp.pl
https://opole.tvp.pl
https://warszawa.tvp.pl
https://wroclaw.tvp.pl
https://poznan.tvp.pl
https://lublin.tvp.pl
```
Oraz
`https://wilno.tvp.pl`
![2020-09-13 05 40 18 wilno tvp pl e726352e3ea5](https://user-images.githubusercontent.com/36385327/93009634-a1112e00-f583-11ea-8dbe-432115328e36.png)

**Comment by krystian3w** [comment]
`https://wilno.tvp.pl` - mail to nie social:

```html
<a href="mailto:tvpwilno@tvp.pl">
```
