### ISSUE TITLE
cyfrowa.rp.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#17045]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/92994120-c0fb1000-f4f7-11ea-8097-81f3c53eae8e.png)

### Link bezpośredni 

https://cyfrowa.rp.pl/technologie/51805-ai-przewiduje-kto-popelni-przestepstwo-burza-w-ameryce
+ https://regiony.rp.pl/ i inne z rp.pl

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. Wejść na stronę
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
**RP wymaga akceptacji w Polska Zogda Ciasteczkowa, przetestuj po instalacji czy znika.**

Opcjonalnie dodatek Kiboke, jak ma już akceptowanie.

Bez akceptowania nie działają osadzone filmiki - kiedyś EasyPrivacy też blokowało, bo niby player szpiegował.

---

@xxcriticxx "invalid" i "won't fix".

**Comment by Barticf** [comment]
@krystian3w zainstalowałem ten dodatek i zaktualizowałem Wersja bazy ciasteczkowej: 2020.09.06.0 ale dalej wyskakuje.

**Comment by krystian3w** [comment]
A widzę, trzeba ulepszyć klikanie, by szło kliknąć kilka razy lub wracamy to metody z pieczeniem ciastka i kontrolą co zmienili (AdGuard piecze ciastko).

**Comment by krystian3w** [comment]
Naprawione - można pobrać nowszą bazę filtrów, są dwa filtry klikające i jak nie masz zbyt słabego PC to sobie poradzą.
