### ISSUE TITLE
nazwa.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17043]
https://nazwa.pl
![2020-09-11 18 44 07 nazwa pl 3dd3fdeafbe7](https://user-images.githubusercontent.com/36385327/92951551-d3753b00-f45e-11ea-8a98-fce747a534cf.png)

https://welcome.home.pl
![2020-09-11 18 44 42 welcome home pl 3e0bcaef7f88](https://user-images.githubusercontent.com/36385327/92951606-ebe55580-f45e-11ea-86ca-14ce0c52d528.png)

**Comment by krystian3w** [comment]
nazwa 🇵🇱 wykupiła niemiecki 🇩🇪  `home.pl`?

**Comment by krystian3w** [comment]
PS. blog ze stopki też wylatuje.

**Comment by xMaap** [comment]
Chyba nie, ale z jakiegoś powodu wkleiłem tutaj home2018 https://dailyweb.pl/polski-pojedynek-gigantow-nazwa-pl-pozywa-home-pl/

2018 https://dailyweb.pl/polski-pojedynek-gigantow-nazwa-pl-pozywa-home-pl/
