### ISSUE TITLE
betblog.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#17057]
https://betblog.pl/gdzie-ogladac-ekstraklase-w-internecie-transmisje-online-z-polskiej-ligi/

![capture_020_13-09-2020_17-15-59](https://user-images.githubusercontent.com/63287518/93021764-de59d800-f5e4-11ea-9166-21d9006eddee.gif)

**Comment by gargul2** [comment]
Po wycięciu zostały jakieś resztki:

![capture_021_14-09-2020_08-27-10](https://user-images.githubusercontent.com/63287518/93051002-194f2080-f664-11ea-86ab-89ef55c9037b.gif)

**Comment by MajkiIT** [comment]
@gargul2 Poprawione

**Comment by gargul2** [comment]
@MajkiIT gitara
