### ISSUE TITLE
blogbukmacherski.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#17052]
Na głównej i w artykułach:

### Na głównej:

![capture_006_13-09-2020_16-56-00](https://user-images.githubusercontent.com/63287518/93021312-43f89500-f5e2-11ea-8e25-31f3ea3ad757.gif)

### 1
![capture_001_13-09-2020_16-54-23](https://user-images.githubusercontent.com/63287518/93021364-84581300-f5e2-11ea-93f8-2bbb2a08679b.gif)

### 2
![capture_002_13-09-2020_16-54-46](https://user-images.githubusercontent.com/63287518/93021367-87530380-f5e2-11ea-8a5e-1a003eb5e52a.gif)

### 3
![capture_003_13-09-2020_16-54-53](https://user-images.githubusercontent.com/63287518/93021369-891cc700-f5e2-11ea-9698-fb6f87f0f06f.gif)

### 4
![capture_004_13-09-2020_16-54-57](https://user-images.githubusercontent.com/63287518/93021373-8b7f2100-f5e2-11ea-9a5f-65a694e6426f.gif)

### 5
![capture_005_13-09-2020_16-55-02](https://user-images.githubusercontent.com/63287518/93021378-8d48e480-f5e2-11ea-9079-9501c43d7cad.gif)

**Comment by gargul2** [comment]
Ten czerwony pasek na dole `29 PLN bez depozytu` dalej jest.

**Comment by MajkiIT** [comment]
@gargul2 ja tego nie mam. Nawet jak wyczyszczę ciasteczka.

**Comment by gargul2** [comment]
@MajkiIT jesteś pewien? Bo pojawia się dopiero po 15 sekundach.

**Comment by MajkiIT** [comment]
@gargul2 tak, ale poczekam jeszcze albo spróbuję na innym kompie.

**Comment by gargul2** [comment]
Mi się ciągle pojawia zarówno na Firefox i Operze.

**Comment by MajkiIT** [comment]
@gargul2 to podaj regułę to ją dodam.

**Comment by gargul2** [comment]
`blogbukmacherski.pl##[id^="cp-cp_id_"]`

Chyba, że wolisz po swojemu to tam jest dużo do wyboru:

![capture_026_14-09-2020_16-15-41](https://user-images.githubusercontent.com/63287518/93097272-a5ce0300-f6a5-11ea-9793-e715cc52aa9a.gif)

**Comment by MajkiIT** [comment]
@gargul2 Dzięki
