### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1706]
Reklama, link - `http://www.wykop.pl/`

![image](https://cloud.githubusercontent.com/assets/11742596/21297987/d3fb574c-c589-11e6-9451-129fbb2b6cce.png)

Na przykład:
`||wykop.pl/tracker/emiter/$image`
`||s1.cdn03.imgwykop.pl/static/wykoppl/img/rect/$image`
`wykop.pl##.r-block:has(a[href^="http://www.wykop.pl/tracker/"])`

**Comment by xxcriticxx** [comment]
paging @kasper93 mamy problem z wykop.pl

**Comment by xxcriticxx** [comment]
co z tym robimy

![capture](https://cloud.githubusercontent.com/assets/15007183/21298047/ca455116-c558-11e6-83c9-88e54c3a88f9.PNG)

**Comment by kasper93** [comment]
Właśnie jak ostatnio patrzyłem to nie mogłem tych trackerów znaleźć. Nie było ich przez jakiś czas. 

Dałbym ogólniejsze filtry niż proponowaliście. Sensownie wygląda, żeby wszystkie te trackery zabić. Jak pamiętam to od zawsze tylko do reklam były, nic sensownego tam nie dawali.
```
||wykop.pl/tracker
wykop.pl##.r-block:has(a[href*="wykop.pl/tracker"])
wykop.pl##a[href*="wykop.pl/tracker"]
```
ten filtr  `||s1.cdn03.imgwykop.pl/static/wykoppl/img/rect/$image` też można wrzucić chyba. Nie używają tego nigdzie oprócz tej reklamy z tego co widzę. 

@xxcriticxx Włącz blokowanie ;) To jest zablokowane przez ten filtr `wykop.pl,demotywatory.pl,joemonster.org,mistrzowie.org##[id^="bmone2n-"]`

**Comment by xxcriticxx** [comment]
@kasper93 dziekuje za info :)

**Comment by F4z** [comment]
@kasper93 dzięki za pomoc.
