### ISSUE TITLE
colian.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17062]

**Comment by krystian3w** [comment]
@hawkeye116477, nie da się zamknąć na `homepage` (wciśnięte w stopkę), a już nie ma `wewnętrznych` by statyczne bloki wycinać.

**Comment by hawkeye116477** [comment]
Odrzucamy, bo statycznych nie wycinamy, a nawet gdyby to byśmy musieli copyright i resztę też wyciąć, bo inaczej się nie da.
