### ISSUE TITLE
miastoiludzie.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1707]
@MajkiIT mzoe cos na wp-content wymyslisz

**Comment by MajkiIT** [comment]
`||miastoiludzie.pl/wp-content/uploads/*/baner_$image`
`miastoiludzie.pl###text-11`
`miastoiludzie.pl###header`

Dla wordpressa to będzie ciężkie, bo on uploaduje obrazki zawsze w podobne katalogi.
