### ISSUE TITLE
zycieczestochowy.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17075]
tło po pop-up

**Comment by gargul2** [comment]
Winowajca: https://github.com/MajkiIT/polish-ads-filter/blob/269df259d5f2465e0e0c74f37d15f4be8025536a/polish-adblock-filters/adblock.txt#L2523

![capture_023_14-09-2020_15-56-34](https://user-images.githubusercontent.com/63287518/93094957-d52f4080-f6a2-11ea-899a-437de3926b43.gif)
