### ISSUE TITLE
grupa - pl##.page-cookie

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17096]
Znalazłem kilka takich samych ciastek mają je głównie instytucje, wiec proponuje ogólną :   pl##.page-cookie

powiatstrzelecki.pl##.page-cookie

opolskie.pl##.page-cookie

gogolin.pl##.page-cookie

glucholazy.pl##.page-cookie

invest-park.com.pl##.page-cookie

Jest tego więcej ale za free niedają na publicwww

**Comment by hawkeye116477** [comment]
Można się zalogować, to pokażą więcej.
`visitopolskie.pl,tridex.pl,powiatglubczycki.pl,/wislica.pl`

**Comment by krystian3w** [comment]
Już widzę bug, niedowidzący mają tylko:

`##.slabowidzacyCookie`

**Comment by hawkeye116477** [comment]
Jeszcze Nerdydata wypluwa:
`turawa.pl,okulistyka.opole.pl,meltech.pl,sowa-okna.pl,pinb.opole.pl,psp32.opole.pl,dobrodzienskadycha.pl,domaszowice.pl,gzwm.com.pl`

**Comment by krystian3w** [comment]
Twórcy CMS też używają swojego kodu "cookies": `netkoncept.com`

**Comment by gargul2** [comment]
> hawkeye116477 : Czyli łącznie ok. 18 naliczyłem, więc może jakiś generyk trzeba dodać.

To chyba coś słabo liczysz, ja znalazłem 62: [LINK](https://publicwww.com/websites/%22class%3D%5C%22page-cookie%5C%22%22+site%3Apl/)

**Comment by blocker999** [comment]
@gargul2 to podaj nam adresy stron z linku

**Comment by hawkeye116477** [comment]
No właśnie, ja liczyłem tylko tyle ile jest podane za free, a w ogóle publicwww też czasem się myli/dane są nieaktualne, więc nie wiadomo czy faktycznie tyle jest.

**Comment by gargul2** [comment]
@gargul2 to podaj nam adresy stron z linku

Na h*j się sracie o te adresy, tak samo jak nie można być pewnym, że te strony istnieją, tak samo nie można być pewnym, że nie istnieją, a skoro jednak kilkanaście z nich istnieje w publicwww (te z podanymi adresami), to najprawdopodobniej co najmniej część z tych ukrytych też istnieje, bo trudno byłoby uwierzyć, że wg waszej szwankującej szkalnej kuli, te istniejące akurat kończą sie na równi z tymi odkrytymi, a wszystkie nieisniejące akurat zaczynają się na równi z nieodkrytymi, to tak jakby po wybuchu granatu wszystkie odłamki byłyby tych samych rozmiarów albo poleciały na tę samą odległość / w tę samą stronę, jakie jest prawdopodobieństwo tak dziwnego zbiegu okoliczności? Takie jak to, że mi pryszcz na nosie wyskoczy w ostatnim dniu miesiąca...wg. waszej hipotezy, równie dobrze te istniejace mogłyby się kończyć na tych które są odkryte bez zalogowania, a jednak po zalogowaniu widać, że nie kończą się, bo istniają kolejne..., a teraz idzimy krok dalej, i teoretycznie wykupmy konto premium, założę się, że po zalogowaniu na premium, pojawią się kolejne istniejące.

> hawkeye116477 : a liczyłem tylko tyle ile jest adresów podanych za free, a w ogóle publicwww też czasem się myli/dane są nieaktualne, więc nie wiadomo czy faktycznie tyle jest.

Domyśliłem się i z tego co dalej napisane też doskonale sobie zdawałem sprawę...ale mimo to podałem znalezione przez mnie 62, bo, jak przed chwilą wykazałem, wróżba podana z mojej szklanej kuli jest bardziej prawdopodobna niż ta podana z waszej...i żaden pedał / troll który ci lajkuje twój komentarz kciukiem w górę i robi ci z połykiem, nie zmieni tego prostego faktu, że wasza wróżba jest mniej prawdopodobna.

**Comment by hawkeye116477** [comment]
> sracie o te adresy, skoro i tak to ma być generyk

@gargul2 Chciałem sprostować, a ty jak zwykle. Calm down. Widzę znowu „zatrudniłeś" kolegę, by ci dawał łapki w górę...

**Comment by krystian3w** [comment]
Ja czekam aż zacznie bronić WP, że maja `<div>`-y z czystym tekstem "`REKLAMA`".

**Comment by gargul2** [comment]
> hawkeye116477 :
> 
> @gargul2 Chciałem sprostować, a ty jak zwykle, Calm down. 

Sami się uspokójcie,  bo sami prowokujecie swoją zbiorową głupotą, a twój kolega homo-głąb dodatkowo lajkami, więc postanowiłem udowodnić, że rację nie udowadnia się lajkami tylko wiedzą, inteligencją i doświadczeniem, i udało mi się, tyle w temacie...pozdrawiam...

"Iloraz inteligencji tłumu jest równy IQ najgłupszego jego przedstawiciela podzielonemu przez liczbę uczestników.
Maskarada"

> hawkeye116477 : 
>Widzę znowu „zatrudniłeś" kolegę, by ci dawał łapki w górę...

Nauczyłem się i wziąłem przykład od twojego kolegi, poza tym jakoś muszę się bronić, a często najlepiej robić to używając tej samej broni, tyle w temacie...pozdrawiam...

I życzę więcej rozumu na przyszłość

**Comment by gargul2** [comment]
Widzę generyk dodany, to w takim razie ta reguła już niepotrzebna:
https://github.com/MajkiIT/polish-ads-filter/blob/ef2bda5d443f67a9b972753aaa462e98d9fd5552/cookies_filters/adblock_cookies.txt#L228

Tu z kolei jest` .com`, ale raczej do zostawienia i jako ciekawostka, bo do generyków z tego co widzę, nie jest dodawane `.com`:

https://github.com/MajkiIT/polish-ads-filter/blob/ef2bda5d443f67a9b972753aaa462e98d9fd5552/cookies_filters/adblock_cookies.txt#L1480

**Comment by krystian3w** [comment]
jedno `com`, to nie warto robić przeciążeń z stronami co wcale polonizacji nie mają.

**Comment by gargul2** [comment]
> jedno `com` 

Myślałem, że jest ich [więcej](https://publicwww.com/websites/%22class%3D%5C%22page-cookie%5C%22%22+site%3Acom/), ale widocznie mi się wydawało.

**Comment by hawkeye116477** [comment]
Można po prostu dodać drugi wariant z langiem tak jak to robiliśmy w PAF.

**Comment by krystian3w** [comment]
Ja tam widzę tylko jedno `j******.com` a tak to publicwww podkreśla co mu się podoba:

![Przechwytywanie](https://user-images.githubusercontent.com/35370833/93870666-d9281780-fccd-11ea-9af3-3fdb67c55310.JPG)

**Comment by gargul2** [comment]
> krytsian3w : Ja tam widzę tylko jedno `j***.com` i dwa `(t|j)***.eu` a tak to publicwww podkreśla co mu się podoba:

W sumie racja, zupełnie zapomniałem, że te 3 nieodkryte to fałszywe trafienia / odpadki / spam dorzucane przez `publicwww`.

> krystian3w : Chyba, że te dziwne tworzą element w locie, to publicwww i nerdydata ich nie ma jak wtedy znaleźć (chyba, że zapisują stronę do pliku zamiast odczytać kod html bez żadnego wykonywania).

Nie, po prostu `publicwww` oprócz wyników na szukaną frazę dorzuca również spam w postaci wyników powstałych z  wyciągnięcia wyrazów alfanumerycznych z frazy i wyszkuania tych wyrazów na stronie w tej samej kolejnośći czyli: `"class=\"page-cookie\""` ==> `class + page + cookie`, być może takie wyniki dodatkowe czasem się przydają, ale częściej przeszkadzają jak typowy spam.
