### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1709]
![image 1](https://cloud.githubusercontent.com/assets/9846948/21311936/0c49abd4-c5ea-11e6-88c3-39958828260d.png)
Zaznaczyłem to co się dodatkowo wyświetla na czerwono. 
uBlockOrigin identyfikuje to jako `##.r-block:nth-of-type(2)` Zawartość tego bloku się zmienia. W zależności od odświeżenia stony.
![image 2](https://cloud.githubusercontent.com/assets/9846948/21312020/6e3a6702-c5ea-11e6-8cf0-1c3c823e0ab6.png)
@MajkiIT @F4z

**Comment by F4z** [comment]
@FadeMind dzięki za zgłoszenie.
Tutaj jest podobny temat - https://github.com/MajkiIT/polish-ads-filter/issues/1706

Te reguły pewnie zostaną dodane do listy:
`||wykop.pl/tracker`
`||s1.cdn03.imgwykop.pl/static/wykoppl/img/rect/$image`
`wykop.pl##a[href*="wykop.pl/tracker"]`
`wykop.pl##.r-block:has(a[href*="wykop.pl/tracker"])`
`wykop.pl##li.link:has(a[href*="wykop.pl/link/partnerredirect"])`

**Comment by xxcriticxx** [comment]
see #1706
