### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#1710]
Znowu afera, bo się jakiś kwadrat pojawia w prawym panelu :) 
http://www.wykop.pl/link/3510771/regula-do-zablokowania-spamu-na-prawej-belce-wykopu/

[Tu piszą](http://www.wykop.pl/artykul/3510771/regula-do-zablokowania-spamu-na-prawej-belce-wykopu/) że to powinno pomóc:
`||s1.cdn03.imgwykop.pl/static/wykoppl/img/rect*$image`

**Comment by gwarser** [comment]
Wygląda na to, że się spóźniłem 10 minut.

**Comment by MajkiIT** [comment]
@gwarser tak, zaktualizowałem reguły, ale dzięki za czujność.
