### ISSUE TITLE
diversesystem.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17100]
![2020-09-17 08 37 19 diversesystem com 4758941e3c76](https://user-images.githubusercontent.com/36385327/93429258-29b00700-f8c1-11ea-99a9-e61269c8a2be.png)

**Comment by krystian3w** [comment]
@hawkeye116477 nie widzę obu?

**Comment by xMaap** [comment]
Ja też z jakiegoś powodu nie mam

**Comment by krystian3w** [comment]
Pewnie fanboy wpadł i nam przeglądnął zgłoszenia, nieładnie, nie podpiął commitu...
