### ISSUE TITLE
joemonster.org syntax error

### ISSUE THREAD

**Issue by asedim** [MajkiIT/polish-ads-filter#1712]
http://i.imgur.com/8DWRzjY.png

Chrome 55.0.2883.87 m (64-bit)
Adblock v.3.8.1 (https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom)

Zostawiłem włączony tylko polish-ads-filter. Po wyłączeniu go błąd znika. Błąd powoduje wyświetlanie części reklam oraz zatrzymuje nakładanie customowych filtrów.

**Comment by MajkiIT** [comment]
ale to masz zamiast strony?

**Comment by F4z** [comment]
Taki błąd w konsoli jest widoczny.
![image](https://cloud.githubusercontent.com/assets/11742596/21328980/adc881be-c636-11e6-969a-cb6734993580.png)

Zakładam, że to wina jakiejś reguły specjalnie dla uBlocka Origin, możliwe, że tej:
`joemonster.org##script:inject(abort-on-property-write.js, ub_ct_load)`
Zaraz dokładniej sprawdzę.

**Comment by MajkiIT** [comment]
@F4z dzięki

**Comment by asedim** [comment]
Dokładnie, dzięki @F4z za szybką reakcję.

**Comment by F4z** [comment]
To na pewno wina tej reguły - `joemonster.org##script:inject(abort-on-property-write.js, ub_ct_load)`

Ogólnie problem jest taki, że na stronach, do których zostały dodane specjalne reguły dla uBlocka Origin, nie działają reguły kosmetyczne w Adblocku/Adblocku Plus.

**Comment by asedim** [comment]
Hm, czy jest jakaś sztuczka typu
```
<!--[if uBlock]>
joemonster.org##script:inject(abort-on-property-write.js, ub_ct_load)
<![endif]-->
```
?

**Comment by MajkiIT** [comment]
@F4z zaraz przeniosę do uBlockowych

**Comment by asedim** [comment]
@MajkiIT dzięki

**Comment by MajkiIT** [comment]
@asedim zaktualizuj filtry do wersji 2016121907

**Comment by asedim** [comment]
@MajkiIT zaktualizowałem, działa, dziękuję
