### ISSUE TITLE
zarabiam.com

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#17137]
Pełno nowych reklam.

`https://zarabiam.com/`
`https://zarabiam.com/Forum-Newsy-2`
`https://zarabiam.com/Temat-Migracja-Zarabiam-com-za-Nami-Nowy-Serwer-102523`

```
##div[id^="mylead_rotator_"]
```

---

@hawkeye116477 / @blocker999  czy to do sociala, czy reklama "zewnętrzna":

`||zarabiam.com/likefb.png`

![obraz](https://user-images.githubusercontent.com/35370833/93500802-de274880-f914-11ea-9903-29ffb8496942.png) | `##a[href="http://likefb.pl"]`
---- | ---

I gdzie wycinamy panią Anię z "Plaży":

![obraz](https://user-images.githubusercontent.com/35370833/93500917-057e1580-f915-11ea-8788-50078ab8daed.png) |
--- |
chyba też tylko w socialu? |

**Comment by hawkeye116477** [comment]
>  czy to do sociala, czy reklama "zewnętrzna":

Tak szczerze mówiąc to nie wiem, bo jednak trochę wygląda na reklamę, ale i też związane z socialem. Tak więc decyzja ostateczna należy do @MajkiIT .

> I gdzie wycinamy panią Anię z "Plaży":

Podobnie, czekamy na decyzję.

**Comment by MajkiIT** [comment]
@hawkeye116477 @krystian3w wezmę do siebie. Dzięki.
