### ISSUE TITLE
sjp.pwn.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17139]
Resztka po reklamie lub jakiś dziwny element ( czarny prostokąt  ) niewiem dokładnie ale to wkurza bo to sugeruje że coś jeszcze jest do odblokowania a po wyłączeniu adblocka jest tylko masa reklam więc proszę o obcięcie tego dołu.

To samo : 

https://encyklopedia.pwn.pl/

**Comment by gargul2** [comment]
To jakieś resztki po scrollującym filmiku / odtwarzaczu video, dziwne, pojawia się losowo / przy pierwszym wejściu na stronę, potem znika i już nie chce się pojawić, nawet po wyczyszczeniu ciasteczek / cache itp., ale udało mi się to UFO uchwycić i ukryć za pomocą `###vjs-rcp1`.

**Comment by krystian3w** [comment]
`encyklopedia.pwn.pl##div[style*="font-size"]:upward(div[class*="col"])`

Jakaś resztka, ale zmieszana z newsletterem, to może lepiej tylko:

`encyklopedia.pwn.pl##div[style*="font-size"]:not([id]):not([class])`
