### ISSUE TITLE
translate.google.pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#17136]
Witam czy istnieje możliwość zablokowania informacji o cookies.

![1](https://user-images.githubusercontent.com/32041737/93496116-217eb880-f90f-11ea-831d-67167084edeb.jpg)

**Comment by krystian3w** [comment]
Nie jak używasz bardzo starego uBO np. `1.7.9` z początku 2016 roku.

**Comment by krystian3w** [comment]
Potestuj takie:
```
translate.google.pl##header ~ div[data-cbh="consent.google.com"]
translate.google.com##header ~ div[data-cbh="consent.google.com"]
```

**Comment by kolor33** [comment]
Wrzuciłem te reguły ale nie działają.
translate.google.pl##header ~ div[data-cbh="consent.google.com"]
translate.google.com##header ~ div[data-cbh="consent.google.com"]
![2](https://user-images.githubusercontent.com/32041737/93509731-71b24680-f920-11ea-88f4-e96e6c97e399.jpg)

**Comment by krystian3w** [comment]
A bo to już inna wersja tłumacza, działa do momentu aż nie próbujesz tłumaczyć linków a czysty tekst.

**Comment by krystian3w** [comment]
tu ci wycieka:

https://translate.google.pl/translate?sl=auto&tl=pl&u=https%3A%2F%2Fgithub.com%2FMajkiIT%2Fpolish-ads-filter%2Fissues%2F17136

❓

**Comment by kolor33** [comment]
Pisz Po polsku .Nie rozumie o co chodzi.Jak to załatać.

**Comment by krystian3w** [comment]
Pytam czy pod tamtym URL-em https://github.com/MajkiIT/polish-ads-filter/issues/17136#issuecomment-694404990 masz też cookies, bo ja go tam nie widzę nawet w prywatnych kartach, chcesz pomocy to zapisz stronę 

![obraz](https://user-images.githubusercontent.com/35370833/93510607-c1454200-f921-11ea-9a20-92c7c2bfb1e0.png) 

skompresuj ją do ZIP-a i wrzuć do tego wątku.

Sam nie dajesz linku, to nie będę ręcznie sprawdzać co robi `jpost.com`, że widzisz cookies w tłumaczu.

**Comment by kolor33** [comment]
Jaką kolwiek stronę wrzucisz to pokazuje komunikat .Strona nie ma znaczenia.
Chyba że masz konto na Gmail i jesteś zalogowany wtedy tego nie widać.

**Comment by hawkeye116477** [comment]
Mi tam działa i na FF i Vivaldim. 

A może @kolor33 nie chcący wyłączył reguły kosmetyczne albo zasubskrybował coś co mu wyłącza takie reguły na tej stronie.

**Comment by krystian3w** [comment]
Nie łapie, bo tam nie ma headera.

**Comment by hawkeye116477** [comment]
Już wiem jak to zrobić, by się pokazało:
1. Wejdź na https://translate.google.pl/?hl=pl#view=home&op=translate&sl=auto&tl=pl&text=jpost.com.
2. Kliknij w link, za którymś razem się wyświetla.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/93514747-df15a580-f927-11ea-87ac-42563267b473.png)

Nie ma `<header>`-a, żadnego = 0 match.

**Comment by kolor33** [comment]
I co da się to zablokować .

**Comment by krystian3w** [comment]
Jutro lub w sobotę, mile widziane jak pomożesz wyciąć trochę przycisków społecznościowych:


<sup>https://github.com/MajkiIT/polish-ads-filter/issues?q=is%3Aissue+is%3Aopen+label%3A%22social+filters%22</sup>

["![obraz](https://user-images.githubusercontent.com/35370833/93520670-20f61a00-f92f-11ea-84fc-c59d293098c1.png)"](https://github.com/MajkiIT/polish-ads-filter/issues?q=is%3Aissue+is%3Aopen+label%3A%22social+filters%22)

**Comment by xMaap** [comment]
Nie tłumacz, ale wiadomości
https://news.google.com/topstories?hl=pl&gl=PL&ceid=PL:pl
![2020-09-18 09 03 05 news google com bcc3846beecf](https://user-images.githubusercontent.com/36385327/93566735-c8099e80-f98d-11ea-86af-a9f7230bcb78.png)

**Comment by krystian3w** [comment]
`news.google.*##div[data-cbh^="consent.google."]`
`news.google.*##html[class*="gb"]:style(overflow: visible !important;)`
