### ISSUE TITLE
plonszczak.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17140]
Coś z Easylist rozwala artykuły na stronie oraz jakby tego było mało są dwie reszki po reklamach, ta strona jest tylko podana jako przykład bo podobnych stron jest więcej, więc proponuje dać jakoś ogólną regułe.

![ab08bdb7-088d-4645-bf53-b17059f962fb](https://user-images.githubusercontent.com/23176832/93594024-60674980-f9b5-11ea-82eb-71e880bee06c.jpg)

**Comment by krystian3w** [comment]
Panie, sprawdzaj co chcesz odblokować, to reklamy:

![Screenshot_2020-09-18 Płońsk Sport plonszczak pl](https://user-images.githubusercontent.com/35370833/93594990-2ac36000-f9b7-11ea-99f3-544fa1bfadb5.png) |
--- |

**Comment by krystian3w** [comment]
Na białe luki:

`pl##li > div[id*="taboola"]:upward(li)`

PS. upward wklejamy do obu suplementów (AG i uBO), by nie było że są glitche w ABP/AdBlock.

---

Na dziwne przesunięcie w prawo - tak tu bug robi angielskie **EasyList**:

`plonszczak.pl#@#.reklama`

**Comment by gargul2** [comment]
Znalazłem też kolejny błąd - uwalone filmy w artykułach np. https://plonszczak.pl/artykul/plonszczak-na-dobry/1077213, w celu naprawy dodajemy wykluczenie domeny `|~plonszczak.pl` do psujacego filtra:
https://github.com/MajkiIT/polish-ads-filter/blob/2b782e941bc2520f312a3fe79619fcce49dd0679/polish-adblock-filters/adblock.txt#L3707

Przed naprawą:
![capture_031_18-09-2020_16-15-27](https://user-images.githubusercontent.com/63287518/93608664-299c2e00-f9cb-11ea-8619-1438612bbea9.gif)

Po naprawie:
![capture_033_18-09-2020_16-26-37](https://user-images.githubusercontent.com/63287518/93609062-ad561a80-f9cb-11ea-8d7e-711f9b19f39e.gif)

**Comment by blocker999** [comment]
tych filmików jest chyba więcej, np : https://ciechanowinaczej.pl/artykul/wiesci-z-mazowsza/1080705

trochę tego jest do przejrzenia, @gargul2 nudzisz się ? :

    mazowieckie
    ciechanowinaczej.pl
    egarwolin.pl
    pultusk24.pl
    plonszczak.pl
    iotwock.pl
    twojradom.pl
    wio.waw.pl
    iochota.pl
    ipragapoludnie.pl
    itvpiaseczno.pl
    imokotow.pl
    ibialoleka.pl
    e-wyszogrod.pl
    izoliborz.pl
    gpr24.pl
    izabelin24.pl
    wolomin24.info
    izyrardow.pl
    ikampinos.pl
    twojzwolen.pl
    babice2

    dolnośląskie
    24jgora.pl
    olawa24.pl
    nolesnica.pl
    24wroclaw.pl
    tulegnica.pl

    kujawsko-pomorskie
    ototorun.pl
    nwloclawek.pl
    rypin-cry.pl
    lipno-cli.pl
    golub-cgd.pl
    wabrzezno.pl
    brodnica-cbr.pl
    inowroclaw.info
    nswiecie.pl

    łódzkie
    lowicz24.eu
    iskierniewice.pl

    podlaskie
    mylomza.pl
    zambrow.org
    ddb24.pl
    ibielsk.pl
    kurierpodlaski.pl
    sejny.net
    fakty.bialystok.pl
    esiemiatycze.pl

    lubuskie
    egorzow.pl

    zachodniopomorskie
    szczecinek.com

    podkarpackie
    ekspresjaroslawski.pl

    wielkopolskie
    zlotowskie.pl
    zycie.pila.pl
    zyciekalisza.pl

    opolskie
    nowinynyskie.com.pl

    LIFESTYLE
    splendo.pl
    poluje.pl
    galopuje.pl
    wterenie.pl

**Comment by gargul2** [comment]
O ja pier*ole..ale w pytę tego jest :smiley: kolejna Grupa do kolekcji:
- to grupa [CMC Media](http://cmcmedia.pl/testowa/)
- przypominają mi się [STARE CZASY](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues?q=is%3Aissue+label%3AGrupa+is%3Aclosed+sort%3Acomments-desc+author%3Agomoku)
- znalazłem jeszcze `kurierbytowski.com.pl` (tak na szybki rzut, nie sprawdzałem dokladnie, może jeszcze coś się znajdzie)
- najpierw niech MajkiIT się wypowie czy mu w ogóle jeszcze do czegoś ten filtr potrzebny i czy go po prostu nie wywalić, [LEKTURA ](https://github.com/MajkiIT/polish-ads-filter/issues?q=is%3Aissue+exs.pl), biorąc pod uwagę, że system reklamowy tej Grupy jest połączony z filmami, nic dziwnego, że blokowanie tego pliku uwala też video
- jak filtr dalej zostanie na liście, to znajdę czas i wyszukm uszkodzone domeny żeby dodać wykluczenia

![capture_041_18-09-2020_20-18-43](https://user-images.githubusercontent.com/63287518/93631627-354c1c80-f9ec-11ea-8af1-283ab607eefc.gif)
