### ISSUE TITLE
mi-home.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17149]
![2020-09-19 12 28 44 mi-home pl 65ac7ec5b078](https://user-images.githubusercontent.com/36385327/93665043-b0a4e100-fa73-11ea-81d1-7ddb76f9b829.png)

**Comment by krystian3w** [comment]
Zgłoszenie na siłę z wyłączonym EI lub:

`mi-home.pl#@##newsletter_block_left`
