### ISSUE TITLE
zblogowani.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17150]
![2020-09-19 12 37 34 zblogowani pl 533819cf809a](https://user-images.githubusercontent.com/36385327/93665204-f4e4b100-fa74-11ea-80ea-2e8bfa72dbae.png)

**Comment by krystian3w** [comment]
@hawkeye116477  znowu jakiś bug z słabym PC, dezaktywowanymi wszelkimi generykami lub usuniętym `fanboy-social`.

`.social-box` - usuwa, dodatkowo jest pełno filtrów, że zostały by niebieskie puste koła lub białe "prostokąty".

**Comment by hawkeye116477** [comment]
To raczej pytanie do @xMaap, bo niestety ale moja czarodziejska kula się popsuła...
