### ISSUE TITLE
tw.waw.pl

### ISSUE THREAD

**Issue by aglowienka** [MajkiIT/polish-ads-filter#17159]
Jeden z wpisów blokuje wszystko na stronie w w/w domenie

### Link bezpośredni 
[https://tw.waw.pl/](https://tw.waw.pl/)

### Co trzeba zrobić, aby pojawił się błąd?
1. wejść na stronę

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

linia 171:
/tw.

**Comment by krystian3w** [comment]
ABP i podobne:

`@@/tw.`

uBO / AdGuard*:

`/tw.$badfilter`

\* - niby aplikacja AdGuard na Windows / Android / macOS nie obsługuje poprawnie `badfilter`.
