### ISSUE TITLE
deon.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17158]
https://deon.pl/kosciol/publikujemy-oredzie-ukrainskich-elit-prawoslawnych-wobec-sytuacji-na-bialorusi,996203
![2020-09-20 13 00 07 deon pl 3d1b42e03839](https://user-images.githubusercontent.com/36385327/93709749-380c5600-fb41-11ea-9340-88252dd2cdde.png)

https://jezuici.pl/2020/09/o-polskim-jezuicie-na-czeskim-uniwersytecie/
![2020-09-20 13 00 39 jezuici pl 15455f006a39](https://user-images.githubusercontent.com/36385327/93709759-4c505300-fb41-11ea-8626-fbc77bd1f73f.png)
![2020-09-20 13 00 54 jezuici pl 0acf07895a9b](https://user-images.githubusercontent.com/36385327/93709760-55412480-fb41-11ea-8921-70eaadb769ac.png)

**Comment by krystian3w** [comment]
Na jezuitach działa `.et-extra-social-icons`

@hawkeye116477  user @xMaap  nie chce kupić nowego PC lub włączyć `Fanboy Social`.

**Comment by xMaap** [comment]
Mam co roku kupować nowy PC?
![2020-09-20 19 55 00 cjpalhdlnbpafiamejdnhcphjbkeiagm 3d4a1d87546c](https://user-images.githubusercontent.com/36385327/93718261-365f8400-fb7b-11ea-82e5-8e1087e48594.png)

**Comment by krystian3w** [comment]
Tak, jak kupujesz jakiś szmelc.

Poza tym nie piszesz, że testujesz AdGuard Social Media, ja nie mam obowiązku go włączać by sprawdzać czy AdamWr z Alex-302 dodał pełno wyjątków by przyciski z nawigacji i stopki były ponownie widoczne.
