### ISSUE TITLE
kuchnia.wp.pl + tapeciarnia.pl + baborow.pl + przemysl.pl + film.wp.pl

### ISSUE THREAD

**Issue by gargul2** [MajkiIT/polish-ads-filter#17163]
https://github.com/MajkiIT/polish-ads-filter/commit/772ad2e7f25168d1dcef6791f5470645d16dde8c#r42557919

**Comment by MajkiIT** [comment]
@gargul2 Dzięki

**Comment by gargul2** [comment]
Tu też brakuje `?`: 
https://github.com/MajkiIT/polish-ads-filter/blob/2b28c6a9ebd739d5dd528680e34d4ba5318eb2ef/polish-adblock-filters/adblock.txt#L4738
