### ISSUE TITLE
portaloswiatowy.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#17169]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/93984063-a4769780-fd83-11ea-9b15-6ab3b3adde59.png)

### Link bezpośredni 

https://www.portaloswiatowy.pl/

### Co trzeba zrobić, aby pojawił się błąd?
1. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Nie da się "zjechać" niżej na stronie ani podstronach. Dodatkowo wyskakuje info o powiadomieniach.

**Comment by gargul2** [comment]
Zgłoszenie niekwalifikuje się na to repo, bo:

1) przewijanie jest uszkodzone przez:
- EasyList Cookie (można zgłosić tu https://github.com/easylist/easylist/issues)
- Adguard Annoyances (można zgłosić tu https://github.com/AdguardTeam/AdguardFilters/issues)

2) Popup z powiadomieniami również kwalifikuje się na inne repo, na repo Polskie Filtry Elementów Irytujących (można zgłosić tu https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues)

**Comment by krystian3w** [comment]
Wszystkie 4 uszkadzają przewijanie, trzeba je CSS-em lub JS naprawić, prosty filtr lub `:remove()` nie działa.

**Comment by gargul2** [comment]
Jak [TU](https://github.com/MajkiIT/polish-ads-filter/issues/17162#issuecomment-695957402), oceniałem wizualnie / zewnętrznie, i w przypadku Polskie Filtry RODO-Ciasteczkowe nie widać czy uszakodzone jest przewijanie, jedynie widać źle wycięty komunikat, więc tylko o nim poinformowałem, a w szczegóły technicznie się nie zagłębiałem, jeśli ty się zagłębiałeś i jest uszkodzone przewijanie, to ok, nie ma sprawy.

**Comment by gargul2** [comment]
Barticf po co to zamknąłeś skoro to jeszcze nienaprawione?

**Comment by Barticf** [comment]
@gargul2 bo mogę już przewijać na stronie, ale widzę zrobiłem błąd bo nadal te powiadomienia wyskakują tylko w trybie prywatnym.

**Comment by gargul2** [comment]
Barctif spoko,  chodzi mi tylko o ten [BŁĄD](https://github.com/MajkiIT/polish-ads-filter/issues/17169#issuecomment-697217468) nr 3 - ze źle wyciętym komunikatem ciasteczkowym w Polskie Filtry RODO-Ciasteczkowe.
