### ISSUE TITLE
work.ua [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#17166]
### Issue URL (Incorrect Blocking)
 [https://www.work.ua/ru/jobs-dnipro-%D1%81%D1%83%D1%82%D0%BA%D0%B8/?advs=1](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.work.ua%2Fru%2Fjobs-dnipro-%25D1%2581%25D1%2583%25D1%2582%25D0%25BA%25D0%25B8%2F%3Fadvs%3D1)
### Comment
> Blocked "Расширенный поиск"(advanced search) button

Caused by `~milionczesci.pl,~dizibox.com,~2dehands.be,~www.pudelek.pl,~btdb.eu##[id^="adv-"]:not(#adv-settings)`

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Iqwx7ig.png)
</details>
<details>
  <summary>Screenshot 2</summary>

![Screenshot 2](https://user-images.githubusercontent.com/8361299/93893308-291ad480-fcf6-11ea-937a-9ba74f2caf69.png)

</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.12
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard Japanese, <br/>EasyList Italy, <br/>EasyList Lithuania, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard

**Comment by MajkiIT** [comment]
@Alex-302 Thanks
