### ISSUE TITLE
aptekagemini.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#17176]
### Zrzut ekranu 

Pusta strona
![obraz](https://user-images.githubusercontent.com/32641928/94026812-6ea0d580-fdba-11ea-90ee-71e502e5db64.png)
__
FB
![obraz](https://user-images.githubusercontent.com/32641928/94027489-2d5cf580-fdbb-11ea-8871-fb60af75b625.png)
__reklamy
![obraz](https://user-images.githubusercontent.com/32641928/94027532-39e14e00-fdbb-11ea-8e5c-f86e345a5f6a.png)

![obraz](https://user-images.githubusercontent.com/32641928/94027554-3fd72f00-fdbb-11ea-8080-a9045703b05f.png)

### Link bezpośredni 

https://www.aptekagemini.pl/
https://www.aptekagemini.pl/podsumowanie/klient

### Co trzeba zrobić, aby pojawił się błąd?
1. Dodać produkt do koszyka
2. Przejść do koszyka
3. Kliknąć przycisk "Dalej" pod "Suma łącznie"
4. Przekierowuje na "pustą" podstronę /podsumowanie/klient

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

+ FB i instagram na górze strony
+ reklamy (po bokach, na dole strony)

__
Co do pustej strony pomaga wyłączenie Polskie Filtry Elementów Irytujących ale wtedy wyskakuje info o ciasteczkach

**Comment by krystian3w** [comment]
Sociala nie ma, masz stare listy lub używasz nieautoryzowanej alternatywy dla **Fanboy Social**: #16790

**Comment by krystian3w** [comment]
Białe luki sprawdź czy nie są z winy:

* `EasyList Cookie` - nie polecamy używania, mają generyki co wycinają pop-upy źle
* `Fuck Fuckadblock` - za duże lenistwo z używaniem `generichide`, tego pana nie obsługujemy jak dodał generichide dla apteki... (po co...)
* `Fanboy’s Enhanced Tracking List` - to jest chyba pole minowe przed dodaniem czegoś niebezpiecznego do EasyList/EasyPrivacy?

Jak jedna z tych, to raczej my tego nie naprawimy i musisz walczyć w ich repozytoriach o naprawę apteki.

**Comment by krystian3w** [comment]
`Bebilon` można by wyciąć w Polskie Filtry elementów irytujących, reklamują swój "produkt" (w sensie z oferty, nie opuszczając apteki).

**Comment by Barticf** [comment]
@krystian3w wyłączyłem te listy co napisałeś ale nadal nie działa. Wyłączenie Polskie Filtry Elementów Irytujących pomaga.

Co do tego FB to Polskie Filtry Społecznościowe mam wersję v.2020.9.20.2 aktualizacja: nie, 20 wrz 2020, 19:49 UTC+02.
