### ISSUE TITLE
tarnogorski.info

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17191]
dziwny błąd, krzyżyk ( X ) na dole

**Comment by hawkeye116477** [comment]
Ktoś po prostu nie dojadł :cookie:

**Comment by gargul2** [comment]
U mnie tego nie ma, jakieś szczegóły?

**Comment by gargul2** [comment]
Dobra jest po włączeniu I Don't Care About Cookies.

**Comment by krystian3w** [comment]
Jest generyk pod pl.

**Comment by kiboke** [comment]
@krystian3w `#cliSettingsPopup` will be added, thanks! Why do you think `/wp-content/plugins/cookie-law-info/public/`is a bad filter?
