### ISSUE TITLE
gram.pl

### ISSUE THREAD

**Issue by bug-rules** [MajkiIT/polish-ads-filter#17201]
Nie można grać, bo wycieka adocean.

**Comment by MajkiIT** [comment]
@bug-rules jakiś konkretny link ?

**Comment by bug-rules** [comment]
homepage

**Comment by gargul24** [comment]
Słuchaj MajkiIT ty ku_wa pecie do szczania i leszczu bez honoru. Za co tym razem ban? W [MOIM KOMENTARZU](https://github.com/MajkiIT/polish-ads-filter/issues/17185) nie było wyzwisk itp. to był normalny komentarz z uwagami i prośbą o wyjaśnienie kwestii technicznych, a ty co ku_wa robisz? Zamiast jak człowiek wyjaśnić, to banujesz i pacyfikujesz swoich ludzi, jak apodyktyczny psychol Łukaszenko, i to jeszcze kogoś kto tu dużo pomagał. Nie umiesz rozmawiać jak człowiek? Czyżby odrobina prawdy aż tak zabolała? Dobrze, niech jeszcze do tego piecze i swędzi, kup se maść na ból dupy to może przestanie piec i swędzieć, siedź tu sobie do usranej śmierci z tymi cymbałami i wlepiaj bany każdemu, kto ci delikatnie uwagę zwróci i poprosi o wyjaśnienie jakiejś kwestii. Jesteś apodyktycznym psycholem jak Łukaszenko, który nie potrafi rozmawiać z drugim człowiekiem, jakiekolwiek zwrócenie tobie uwagi, to odrazu się obrażasz jak dziecko, któremu zabrano lizaka, i bany rozdajesz, siedź sobie tu z tymi cymbałami, które cię w dupę całują, a takich tu nie brakuje, ale ja nie przywykłem kogoś w dupę całować. Skoro nie umiesz rozmawiać jak cywilizowany człowiek, to baw się dalej swoim panelem admina jak dziwka wibratorem i ukrywaj piękącą cię po dupie prawdę: zmieniaj tytuły wątków, kasuj komentarze, wklikuj bany, tak jak [TU](https://github.com/MajkiIT/polish-ads-filter/issues/17202) bo takie bezargumencie i apodyktyczny psychol jak ty nie umie normalnie się zachować, takiego trolla jak ty to świat nie widział.

I dlatego będe cię gnoił do zaje!ania aż zdechiniesz **ty pecie do szczania** i **leszczu bez klasy**.

**Comment by hawkeye116477** [comment]
> Nie można grać

A od kiedy na gram.pl można grać? Tam są jedynie artykuły.

**Comment by bug-rules** [comment]
Czyli kto naprawi te popsute ładowanie w szarych ramkach.

**Comment by hawkeye116477** [comment]
W zasadzie raczej @MajkiIT powinien naprawić (wyciąć to), skoro AdGuard Base nie jest wymagany.
