### ISSUE TITLE
mechatronikadlawszystkich.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17205]
![2020-09-25 15 51 58 mechatronikadlawszystkich pl a4a1dd8b386c](https://user-images.githubusercontent.com/36385327/94275332-1fd47680-ff47-11ea-8c4a-1fb4b3f9f81f.png)

**Comment by krystian3w** [comment]
@MajkiIT a reklama `bcweb.pl`? Niby podmioty zaprzyjaźnione?
