### ISSUE TITLE
aptekagemini.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#17217]
Nie da się przewijać na stronie.

### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/94357256-92ed0280-0097-11eb-908b-6d65136965e1.png)

### Link bezpośredni 
https://www.aptekagemini.pl/semaherba-melisa-fix-1-5-g-x-30-saszetek-0082181

### Co trzeba zrobić, aby pojawił się błąd?
1. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by hawkeye116477** [comment]
@Barticf Zaktualizuj wszystkie listy.
