### ISSUE TITLE
new bot test

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#17221]
### Typ elementu/problemu 
- [] Reklama 
- [] Wydobywanie kryptowalut 
- [] Anty-adblock 
- [] Komunikat dot. ciasteczek i polityki prywatności/RODO 
- [] Element społecznościowy 
- [] Pi-hole, hosts i spółka 
- [] Błąd 
- [] Pytanie 

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. 
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 

**Rozszerzenia i skrypty:** 

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by xxcriticxx** [comment]
@hawkeye116477 good job!

**Comment by krystian3w** [comment]
a teraz czy umie w drugą stronę, odznaczając (lub usuwając krzyżyk)

**Comment by xxcriticxx** [comment]
@krystian3w w druga strone no problem

**Comment by krystian3w** [comment]
Bot ma problem jak się użyje starych pojedynczych sprofilowanych zgłoszeń - usuwa tag, bo "tak".

**Comment by xxcriticxx** [comment]
Na pewno nie jest backwords compatible

**Comment by hawkeye116477** [comment]
`usuwa tag, bo "tak".`

On usuwa jak nie ma dopasowania, trochę słabo obmyślili. Powinna być raczej możliwość dodania warunku kiedy ma usuwać, a nie sam się rządzi...
