### ISSUE TITLE
parkiet.com

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#17225]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/94373627-f06c6800-0106-11eb-9d83-bd4fb6d53735.png)

### Link bezpośredni 
https://www.parkiet.com/

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. 
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Cookies parkietu tak samo jak `RP.pl` w dodatku IDCAC lub PCZ.

uBO nie pozwala wydajnie sprawdzić czy osadzone wideo jest z `one network tv` czy "`TVN` ("`x-link"` / "`x-news`")" - niby nie warto ryzykować wtopy, że starszy player z osadzonymi wideo wróci.

Jak PCZ klika za wolno to zostaje na razie kupno mocniejszego PC, bo `clickSetTimeout` nie ma wbudowanego licznika, że ma poczekać 15 sekund i dopiero kliknąć, bo PC się ksztusi od JavaScriptu.

**Comment by Barticf** [comment]
@krystian3w mam ten dodatek PCZ (zapomniałem dopisać), zaktualizowałem bazę ale nadal jak wchodzę na stronę to wyświetla mi powiadomienie. Na rp.pl też wyświetlało ale wystarczyło zjechać niżej na stronie i znikało.

**Comment by krystian3w** [comment]
mnie i @hawkeye116477  niby dodatek klika, jak stare masz CPU lub jak słaby/budżetowy?

Możliwe, że dodatek nawet na Ryzenie nie wyrobi jak ktoś pracuje z otwartymi 100 kart lub np. 20 bardzo zasobożernymi (WP / Facebook).

Dodatkowo na pewno masz w PCZ bazę z `2020.09.12.0`?

**Comment by xMaap** [comment]
@Barticf wejdź w ustanowienia Polska Ciasteczkowa Zgoda i zaktualizuj
![2020-09-28 11 33 08 bniijddcmabghibaojbkbnngbedopbno 6e764dd9d0dc](https://user-images.githubusercontent.com/36385327/94415950-84c5e180-017e-11eb-9f60-8eebe88d31e3.png)

Również zainstaluj I don't care about cookies który również blokuje powiadomienia o RODO na tej stronie.

**Comment by Barticf** [comment]
@krystian3w wersja "2020.09.12.0"
Ryzen 5 2600, co do otwartych kart to mam otwarte 4 więc to problemem nie powinno być.
Tylko to wyskakuje o rodo a nie ciasteczka tak jak na tym screenie wyżej.

**Comment by krystian3w** [comment]
Ja widzę Orange, Pekka<sub>oo</sub> <sup>(kana 2)</sup>, jak poczekasz z 15 sekund to może też ci podmienią na inne, czyli on stronę ogląda przez około 30 sekund i oba klikacze jak widać zawodzą na Ryżu/Rysiu.

**Comment by Barticf** [comment]
@krystian3w nie dodałem na białą listę. 
Dodatkowo nie da się tego zamknąć, klikam dalej ale nic się nie dzieje więc pewnie dlatego ten dodatek tutaj nie działa.

**Comment by krystian3w** [comment]
Zaktualizuj filtry w uBO, może jakiś przestarzały coś miesza.

Jak po aktualizacji w uBO będzie problem, to może być to wina:


- EasyList Cookies (znajdziesz bug, to najlepiej sam zgłoś i śledź czy naprawią poprawnie - raczej nie ma planu na uruchomienie "bugi_EasyListCookie" w polskich filtrach `RODO-ciasteczkowych`)
- Fuck Fuckadblock (nie ma gwarancji, że autor się nie wypnie o powie brzydko: "ignorować" ten pop-up).
- Fanboy’s Enhanced Tracking List (może jak robi błąd to się uda do 2 tygodni naprawić).

**Comment by Barticf** [comment]
@krystian3w jakiś błąd chyba u mnie z przeglądarką bo wyłączyłem ublock i inne dodatki a tu nadal nie działa ten przycisk "dalej". Na Vivaldim problemu nie ma ale tam znowu nie mam tych wszystkich list co na firefoxie.

**Comment by krystian3w** [comment]
`about:profiles` i zrób testowo nowy.

Jak dalej się będzie bugować parkiet to raczej uszkodzony głębiej Firefox.

**Comment by Barticf** [comment]
Jakiś problem z firefoxem u mnie bo na vivaldim po zainstalowaniu dodatku PCZ jest ok.

**Comment by krystian3w** [comment]
@adamwr / @F4z wymyślił szybszy sposób:

https://github.com/PolishFiltersTeam/PolishCookieConsent/commit/811785bd6634f92fd2c6c95de1d56fc1dbd4d02e
