### ISSUE TITLE
biznes.interia.pl | pomponik.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#17220]
# Problem:

- [x] Anty-adblock

# Opis:

Adblock wrócił.

![obraz](https://user-images.githubusercontent.com/35370833/94369522-7b8b3500-00ea-11eb-86cd-cb72442e1f93.png) |  ![obraz](https://user-images.githubusercontent.com/35370833/94369547-ae352d80-00ea-11eb-8120-6353e3a2f43d.png)
--- | ---
`biznes.interia.pl` | `pomponik.pl`

# rozwiązania (AdGuard Team):

Może czas na skrypty:

```
interia.pl,pomponik.pl##+js(set, Inpl.Abd.onDetected, noopFunc)
interia.pl,pomponik.pl##+js(set, isAdblockDetected, 0)
```

Jak to nie  działa; to trzeba zrobić analizę co teraz wykrywają z EasyList.

**Comment by skibbipl** [comment]
U mnie skrypty nie działają, dzisiaj wyskoczył komunikat.

**Comment by krystian3w** [comment]
Skrypty padły 2 dni po moim zgłoszeniu, pomysł `uBlock-user` też padł po około tygodniu.

Interii / Polsat pewnie zależy by pop-up wracał co 2 dni.

**Comment by AroKol78** [comment]
https://www.pomponik.pl/
https://biznes.interia.pl/
is back  "adblock detect"

**Comment by krystian3w** [comment]
Na pomponiku nie umiem odtwarzać.

---

Co do pomagania to, to drugi dezaktywować ma tylko `redirect`. Jak chcesz dopuścić ładowanie S.G.DC to usuń je:

`@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=biznes.interia.pl|pomponik.pl|iplsc.com`

**Comment by AroKol78** [comment]
**mapx-** znalazł na "adblock detect"
`https://github.com/uBlockOrigin/uBlock-issues/issues/1397#issuecomment-765574758`

część znajduje się w https://github.com/olegwukr/polish-privacy-filters
```
~poczta.interia.pl,interia.pl,pomponik.pl##+js(set, Inpl.Abd.onDetected, noopFunc)
interia.pl,pomponik.pl##+js(set, isAdblockDetected, 0)
```
https://github.com/olegwukr/polish-privacy-filters/blob/cf7c4db5d722d6e54f2cfe9cd77c725f570b8afc/anti-adblock-suplement-adguard.txt#L104-L105
https://github.com/olegwukr/polish-privacy-filters/blob/cf7c4db5d722d6e54f2cfe9cd77c725f570b8afc/anti-adblock-suplement.txt#L104-L105

dodałem do "My filters" 
`interia.pl,pomponik.pl##+js(no-setTimeout-if.js, , 500)`

nie wiem, czy trzeba to dodać `iplsc.com` ?
dzała 👍 na `biznes.interia.pl` `pomponik.pl`

może można dopisać do "POL: Oficjalne polskie filtry przeciwko alertom o Adblocku"
`interia.pl,pomponik.pl##+js(nostif, , 500)` do https://github.com/olegwukr/polish-privacy-filters
