### ISSUE TITLE
tv-trwam.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17226]
https://tv-trwam.pl/vods/vod.51993
Wystarczy kliknąć otwórz na odtwarzaczu
![2020-09-28 07 54 09 tv-trwam pl ff65a02b2054](https://user-images.githubusercontent.com/36385327/94395361-ce530400-015f-11eb-9a03-e756df53854c.png)

**Comment by krystian3w** [comment]
W dodatku, inaczej nie działa funkcjonalnie przycisk "`oglądaj`" na "`Program TV` (ramówka)":

https://github.com/PolishFiltersTeam/PolishCookieConsent#jak-zainstalowa%C4%87

https://tv-trwam.pl/program-tv - https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2493

PS na program-tv nie da się bezpiecznie dezaktywować scrollującego filmiku.
