### ISSUE TITLE
axa.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17229]
![Screenshot_2020-09-28 AXA - Ubezpieczenia, Emerytury, Inwestycje](https://user-images.githubusercontent.com/36385327/94396502-54704a00-0162-11eb-80bc-941b411ca672.png)

**Comment by krystian3w** [comment]
@hawkeye116477 to jest wycięte w PASS ogólnie cały blok.

Czy do sociala trzeba dodać 3 filtry by zniknęły buttony:
- fb
- yt
- blog

**Comment by krystian3w** [comment]
A może jednak: `axa.pl##footer .socials > a:not([href*="/rss/"])`
