### ISSUE TITLE
fakt.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#17232]
Brak pełnego artykułu gdy włączony jest ublock

### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/94545059-53b3e280-024c-11eb-9c51-5fa23d666550.png)

### Link bezpośredni 
https://www.fakt.pl/hobby/ksiazki/raport-w-opowiesc-rotmistrza-pileckiego/4x0pxz1?srcc=null#slajd-20

### Co trzeba zrobić, aby pojawił się błąd?
1. 
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by xMaap** [comment]
![2020-09-29 12 24 30 www fakt pl a29c40da369c](https://user-images.githubusercontent.com/36385327/94546917-d2aa1a80-024e-11eb-91e0-5b844d418137.png)

**Comment by xMaap** [comment]
Winne jest Fanboy’s Enhanced Tracking List

**Comment by hawkeye116477** [comment]
@Barticf https://github.com/ryanbr/fanboy-adblock/issues
