### ISSUE TITLE
repairlab.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17230]
https://repairlab.pl/blog/jak-zastrzec-numer-w-iphone-jak-ukryc-numer-iphone/
![Screenshot_2020-09-28 Jak zastrzec numer w iPhone Jak ukryć numer iPhone - RepairLab](https://user-images.githubusercontent.com/36385327/94468897-6fc07100-01c5-11eb-918f-53f62f92a12b.png)

**Comment by krystian3w** [comment]
`###sgpb-popup-dialog-main-div-wrapper, .sgpb-popup-overlay`

**Comment by MajkiIT** [comment]
@krystian3w dziękuje
