### ISSUE TITLE
hdtvpolska.com

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#17231]
https://hdtvpolska.com/jakie-aplikacje-wideo-zobaczymy-na-playstation-5-czy-beda-wsrod-nich-takze-polskie/

Nie wiem jak to skomentować, ale wygląda mi to na jakiś rodzaj reklamy zegarków Garmin...

![2020-09-29_11-24](https://user-images.githubusercontent.com/19818572/94540057-501d5d00-0246-11eb-89cc-62a3f80d9e38.png)

**Comment by xMaap** [comment]
Oby znowu nie znikło https://github.com/MajkiIT/polish-ads-filter/issues/17164#issuecomment-698194550

**Comment by AdamWr** [comment]
Wygląda na to, że ta reguła blokuje te reklamy:
`||pub.contexthub.net^`

**Comment by hawkeye116477** [comment]
Jakby co, to możliwości jest więcej. Można jeszcze tak:
```
hdtvpolska.com###_cntxt_43
hdtvpolska.com##iframe
```
albo
`hdtvpolska.com##+js(acis, _cntxt_pl)`

**Comment by AdamWr** [comment]
Tak, ale zablokowanie `pub.contexthub.net` powinno sprawić, że na innych stronach korzystających z `quizad` te reklamy też powinny być zablokowane.

`https://quizad.pl/demo/`

**Comment by krystian3w** [comment]
A to nie fejkowy paywall może?

**Comment by hawkeye116477** [comment]
Pomyliłem się przy scalaniu, iframe to nie id.

**Comment by krystian3w** [comment]
Co dalej nie zmienia faktu, że każda ramka to na pewno reklama.
