### ISSUE TITLE
kryminalnapolska.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17235]
https://kryminalnapolska.pl/2020/09/29/pijany-mezczyzna-zabil-3-miesieczne-dziecko-bo-plakalo-matka-nie-zareagowala/
![Screenshot_2020-09-30 Pijany mężczyzna zabił 3-miesięczne dziecko bo płakało Matka nie zareagowała](https://user-images.githubusercontent.com/36385327/94632438-cd8ab100-02ca-11eb-8af5-48de2186564b.png)

**Comment by MajkiIT** [comment]
`@@||wpfc.ml^$domain=kryminalnapolska.pl `
