### ISSUE TITLE
rbinternational.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17240]
![Screenshot_2020-09-30 https www rbinternational com pl](https://user-images.githubusercontent.com/36385327/94652054-bb743700-02f9-11eb-9a25-f2ab60a0a88e.png)

**Comment by krystian3w** [comment]
U Kiboke:
`rbinternational.com.pl###cms-cookie-approvment`

A Kiboke chyba nawet jakiś pop-up akceptuje (możliwe, że jakiś archiwalny kod nie usunął).

---

@hawkeye116477  duplikujemy czy wina, że celowo IDCAC wyłączony? Lub kupno szmelcu daje o sobie znać?
Możliwe, że @xMaap dalej jako bazę używa `EasyList Cookies` a dodatek IDCAC tylko reklamuje np. #17225

**Comment by hawkeye116477** [comment]
Cóż, w zasadzie to już duplikujemy parę polskich, więc może nie zaszkodzi.
