### ISSUE TITLE
krs-online.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17246]
![2020-10-04 02 10 10 www krs-online com pl 6da192a46d46](https://user-images.githubusercontent.com/36385327/95004087-ca533600-05e6-11eb-9688-38e32c2db9d9.png)

**Comment by krystian3w** [comment]
Oni mają starą bazę, gdzieś na 2018 się zatrzymali chyba.

---

Lepiej użyć coś co umie pobrać najnowszą lub tego:

`https://ppuslugi.mf.gov.pl/_/#1`
`https://www.podatki.gov.pl/wykaz-podatnikow-vat-wyszukiwarka`
