### ISSUE TITLE
Niepoprawne reguły

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1724]
Lista "[Adblock polskie reguly social](https://github.com/MajkiIT/polish-ads-filter/blob/master/adblock_social_filters/adblock_social_list.txt)" zawiera niepoprawne reguły, tutaj jest podobne zgłoszenie - https://github.com/azet12/PopupBlocker/issues/9

Chodzi o reguły kosmetyczne, które zaczynają się kropką, na przykład - `.pl#`

Z tego co widzę, to na polskiej liście też jest kilka takich reguł:
`.xyz##[class^="a_"]`
`.xyz##[id$="_right"]`
`.xyz,mecz.tv,ipilka.info##[class$="_right"]`
i chyba ta też:
`~.de,~box.com,~hardcorowo.pl,~gumtree.com,~hulu.com,~svobodneforum.cz##[class^="ad-"]`
Chodzi o `.xyz` i o `~.de`.

**Comment by MajkiIT** [comment]
Dobra jutro zerkne. Dzięki
