### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by MESWEB** [MajkiIT/polish-ads-filter#17247]
### Zrzut ekranu 
![Opera Snapshot_2020-10-04_011321_www filmweb pl](https://user-images.githubusercontent.com/2931024/95004132-0b474c80-05df-11eb-9ad1-41640db80665.png)

### Link bezpośredni 
Jakikolwiek do filmu 

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. Otworzyc link z filmem
2. Przecierac oczy
3. 

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Opera

**Rozszerzenia i skrypty:** 
uBlock Orgin, uMatrix

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Oficjalne polskie filtry przeciwko alertom o Adblocku 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
W Firefox pomaga html filtering.

**Comment by MESWEB** [comment]
@krystian3w Kolego ja to pol roku temu sam sobie ogarnalem nie znajac kompleltnie nic na temat adblock listy i filtrow. Wystarczy zablokowac div'a z zawartoscia + js i po klopocie. Dla kogos w temacie to 5 minut. Ja niestety musze szukac wszystkiego od nowa i czytac poradniki jak dodawac oddpowiednio filtr.

**Comment by krystian3w** [comment]
No to div jest zablokowany w Firefox, Opera i Chrome nie wspierają html filteringu by to blokować.

**Comment by MESWEB** [comment]
Wiec fajnie by bylo napisac regule dla tego typu strony? 5 minut to chyba nie duzo a innym sie przyda. Ten AdBlock Detector jest tam chyba juz ponad rok czasu.

**Comment by krystian3w** [comment]
Może jest ponad rok, ale średnio 2 dni po naprawie modyfikowany, html filtering widać tam jest odporny na drobne modyfikacje.

Implementacja html filteringu w Operze/Chrome to nie jest niestety 5 minut.

**Comment by MESWEB** [comment]
No my sie chyba nie rozumiemy. Aby wykryc AdBlocka strona **MUSI** uzyc javascript i teraz wystarczy zablokowac owy skrypt i strona juz nie wykryje AdBlocka. Mowie ze juz to kiedys sam to zrobilem - ale ze wzgledu ze sie nie znam jak wyszukac dane funkcje  javascript w przegladarce to mi to troche zajmuje. Po instalacji nowego systemu stracilem swoje filtry. Skoro wy tu dzialacie w takich sprawach to znalezienie skryptu odpowiedzialnego za wykrywanie AdBlocka nie bedzie stanowic dla was zadnego problemu.

**Comment by gargul03** [comment]
MESWEB, mi nie wyskakuje żaden anty-adblock.

**Comment by MESWEB** [comment]
@gargul03 Podaj konfiguracje bo na pewno masz inna niz ja.

**Comment by gargul03** [comment]
Hej, a skąd masz tę pewność, ze szklanej kuli wywróżyłeś, to twoja kula w takim razie szwankuje, pogadaj z hawkeye może on pożyczy ci swoją :smiley: bo sprawdzałem na takiej samej konfiguracji jak twoja + na kilku innych kombinacjach i nic nie wyskakuje, więc:
- albo fałszywy alarm i coś u ciebie skopane (niezaktualizowane listy, coś poprzestawiane itp.)
- albo jeszcze nie wyskakuje u mnie i wyskoczy np. jutro rano (zdarzało mi się tak kiedyś, że wyskoczyło dopiero na drugi dzień od czyjegoś zgłoszenia)
- albo może masz konto na filmweb i wyskakuje dopiero po zalogowaniu o czym zapomniałeś napisać, a ja nie mam konta więc sprawdzałem tylko jako gość
- albo ==> i tutaj każdy może wstawić swoje hipotezy, łącznie z UFO <==

To tyle jeśli chodzi o moją szklaną kulę :smiley: a życie i tak jest nieprzewidywalne i zabawne

Etykieta "sprawa dla reportera" "sprawa dla Elżbiety Jaworowcz" "Z archiwum X" dla zgłoszenia :smiley:

**Comment by hawkeye116477** [comment]
Również nie mam żadnego alertu antyadblockowego, ale sprawdzałem na Vivaldim. 

Możliwe, że @MESWEB został wybrańcem i dali mu jakąś wersję beta strony. Powinien też sprawdzić czy pomaga wyczyszczenie danych prywatnych, tj. cookies, cache. A jak to nie pomoże to zainstalować ponownie uBO albo zresetować jego ustawienia (czasem może się zdarzyć, że coś szwankuje i nie chce działać poprawnie), a w ostateczności wyłączyć i włączyć ponownie komputer :smiley:

**Comment by MESWEB** [comment]
@gargul03 & @hawkeye116477 
Windows 10 postawiony kilka dni temu.
Operan + uBlock Orgin + uMatrix + Opera’s built-in ad blocker,
W ustawieniach nie grzebalem.
Tak mam konto filmweb.pl i jestem zalogowany. Wylogowany z wyczyszczonymi ciasteczkami - ten sam efekt.
Blokada jest na samym dole strony. WYstarczy wlaczyc adblocka i prrzewinac na dol a co lepsze mozna sprawdzic czy na stronie jest skrypt ktory podalem [wyzej](https://github.com/MajkiIT/polish-ads-filter/issues/17247#issuecomment-703296376).

**Comment by krystian3w** [comment]
W takim razie wyłącz `Opera’s built-in ad blocker` lub wymuś w nim dodanie tej listy:

https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/anti-adblock.txt

Ale nie ma gwarancji, że filtr zadziała poprawnie w wbudowanym blokerze Opery/Vivalid (go też za bardzo projekt nie wspiera).

**Comment by hawkeye116477** [comment]
@MESWEB Mamy ten sam skrypt, tzn. no prawie, bo id jest inne, ale cała reszta identyczna.

**Comment by gargul03** [comment]
> MESWEB: Operan + uBlock Orgin + uMatrix + Opera’s built-in ad blocker,

Sprawdzałem różne kombinacje wyżej wymienionych, zanim jeszcze napisałem swój komentarz: https://github.com/MajkiIT/polish-ads-filter/issues/17247#issuecomment-703674860

> gargul03: + na kilku innych kombinacjach 

Ale i tak mi nie wyskoczyłanty-adblock.

**Comment by MESWEB** [comment]
@krystian3w @hawkeye116477 @gargul03 AdBlock Detector nie pokazuje sie jedynie kiedy uBlock Orgin + Opera’s built-in ad blocker jest wylaczony. Moje IP jest zagraniczne - moze to byc tez powodem. Bardzo dziwne bo ten problem jest juz od okolo 2 lat.
Tutaj jest wzmianka z 2014 roku o wykrywaczu AdBlocka na filmwebie wiec skonczcie swoje farmazony.
https://adblockplus.org/forum/viewtopic.php?t=25641

**Comment by krystian3w** [comment]
Ale to nie farmazony, `filmweb` / `wp` / `trojmiasto` / `interia` (Polsat) są tak skrupulatni że w 8 godzin umieją przywrócić reklamy/anty-adblock.

**Comment by hawkeye116477** [comment]
W linku, który podał nawet jest komentarz użytkownika, iż problem powrócił po paru dniach. Tak więc słaby troll @MESWEB...

**Comment by MESWEB** [comment]
Dobra naprawilem. Wrzucilem nowe rulesy + wylaczylem Opera’s built-in ad blocker
Jak widac Opera AdBlocker ma priorytet do blokowania reklam wiec filtry itp nie dzialaja z uBlocka

**Comment by hawkeye116477** [comment]
Czyli sprawa rozwiązana, więc należy wcisnąć „close" :smile:

**Comment by gargul03** [comment]
Haha.

**Comment by zaba-monika** [comment]
U mnie nie ma anty-adblocka, to zgłoszenie to fałszywy alarm, problem leżał po stronie zgłaszającego.
