### ISSUE TITLE
Bądźmy eko

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#17259]
Jest sprawa do dyrka @MajkiIT. Obecnie GitHub Actions uruchamia się po każdym push/merge, idealnie byłoby dobrze jakby działało to jedynie po dokonaniu zmian do strony. Więc otóż w ramach akcji eko trzeba utworzyć nową gałąź `gh-pages`,  a potem wejść w opcje repo i przestawić „GitHub Pages Source" na nową gałąź (katalog/folder niezmiennie docs). A jako ostatni krok w https://github.com/MajkiIT/polish-ads-filter/blob/master/.github/workflows/hugo.yml zmienić wszystkie wystąpienia `master` na nazwę nowej gałęzi `gh-pages` :smile:.

**Comment by MajkiIT** [comment]
@hawkeye116477 gotowe
