### ISSUE TITLE
fm.tuba.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1725]
Strona wykrywa adblocka.
Link - `http://fm.tuba.pl/play/8/2/radio-rock-radio?appId=02`

<details>
<summary>Obrazek</summary>

![image](https://cloud.githubusercontent.com/assets/11742596/21368818/70125448-c704-11e6-9826-0d74385aba40.png)

</details>

Na przykład:
`@@||fm.tuba.pl/vast/advertisement/GetReklamyMultimediaVast?advertisement$xmlhttprequest,domain=fm.tuba.pl`

Oprócz tego można zablokować jeszcze reklamę.
<details>
<summary>Obrazek</summary>

![image](https://cloud.githubusercontent.com/assets/11742596/21368964/062f9b2a-c705-11e6-8ffc-cb09d3db9b65.png)

</details>

Na przykład:
`fm.tuba.pl##tuba-ads`

**Comment by xxcriticxx** [comment]
@F4z kiedys bylo na liscie sie zmienlo cos?

**Comment by F4z** [comment]
@xxcriticxx na liście jest ta reguła - `@@||tuba.pl/*/ad/$xmlhttprequest` - i jak widać w tym przypadku nie działa.
Można dodać do niej gwiazdkę - `@@||tuba.pl/*/ad*/$xmlhttprequest` - i będzie działać.

**Comment by xxcriticxx** [comment]
@F4z ok thank you as always!

**Comment by F4z** [comment]
@MajkiIT znowu zmienili, można jeszcze usunąć ukośnik z końca reguły:
`@@||tuba.pl/*/ad*$xmlhttprequest`
