### ISSUE TITLE
epidemia-koronawirus.pl

### ISSUE THREAD

**Issue by skibbipl** [MajkiIT/polish-ads-filter#17267]
### Zrzut ekranu 
![obraz](https://user-images.githubusercontent.com/4746858/95471321-194ff100-0982-11eb-8c7c-26802a060187.png)

### Link bezpośredni 
https://epidemia-koronawirus.pl/

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. Wejść na stronę i zaczekać na załadowanie wszystkich danych
2. 
3. 

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Firefox 83.0a1 (2020-10-06) (64 bity)
**Rozszerzenia i skrypty:** 
uBlock Origin
Nano defender
uMatrix
CanvasBlocker

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Oficjalne polskie filtry przeciwko alertom o Adblocku 
4. Nano defenderowe filtry

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by gargul03** [comment]
`||epidemia-koronawirus.pl/wp-content/cache/wpfc-minified/*/201xr.js$script,~third-party`

Nie wiem czy `201` jest stabilne, więc można ewentualnie wstawić bardziej przyszłościową gwiazdkę `*`, 
swoją drogą w tym pliku siedzi nie tylko anty-adblock ale też wiele rzeczy jest poblokowanych np. myszka, konsola itp.,
no ale siedzą w tym samym jednym pliku więc ten jeden filtr wystarczy do odblokowania wszystkiego.

**Comment by skibbipl** [comment]
Działa

**Comment by krystian3w** [comment]
Jak `xr` nie będzie stabilne to trzeba przemyśleć, bo nazwa "katalogu" ma za dużo kompresowanych plików js.

**Comment by gargul03** [comment]
> gargul03 : Nie wiem czy `201` jest stabilne
> krystian3w: Jak `xr` nie będzie stabilne


Ani liczba ani litery nie są stabilne, przed chwilą wszedłem i jest `2snkd`, czyli nazwa jest losowo generowana.
Z kolei legalny skrypt też ma losowo generowaną: `ae5gr`, więc regex odpada, zostają skrypty.

**Comment by gargul03** [comment]
`epidemia-koronawirus.pl##+js(aeld, DOMContentLoaded, mdpDeBlocker)`

**Comment by krystian3w** [comment]
Użytkownicy ABP i uBO mogą się rozejść: https://github.com/AdguardTeam/AdguardFilters/commit/9b8803e070c1b20890142b42627c2a349791cc2d https://github.com/uBlockOrigin/uAssets/commit/1c5120278ad7528c9cee6a2b6fc1d696a9bf43f5

Zapraszamy fanów ABP/AdBlock to udziału w dyskusji jak wam naprawić.

**Comment by krystian3w** [comment]
Użytkownicy AG i uBO mogą się rozejść: https://github.com/AdguardTeam/AdguardFilters/commit/9b8803e070c1b20890142b42627c2a349791cc2d https://github.com/uBlockOrigin/uAssets/commit/1c5120278ad7528c9cee6a2b6fc1d696a9bf43f5

Zapraszamy fanów ABP/AdBlock to udziału w dyskusji jak wam naprawić - zostaje zaimportować pomysły używane w AdGuard dla iOS i Content Blocker. 
*Stosowanie tej metody w Safarii pewnie wynika z faktu wspierania starego dodatku 1.5.4, bez obsługi skryptów (lub nikt nie włącza trybu zaawansowanego by one działały).*

**Comment by gargul03** [comment]
Można samego anty-adblocka whitelistami, ale i tak resztę blokad trzeba scriptletem, 
który to scriptlet też usuwa anty-adblocka przy okazji, bo wszystklo i tak siedzi w jednym pliku,
więc jak komuś się chce to może zgłosić:
`epidemia-koronawirus.pl##+js(aopr, mdpDeBlocker)` ==>
`epidemia-koronawirus.pl#$#abort-on-property-read mdpDeBlocker`
na
https://github.com/abp-filters/abp-filters-anti-cv/issues ==> 
https://github.com/abp-filters/abp-filters-anti-cv/blob/master/polish.txt

**Comment by krystian3w** [comment]
Anti-CV nie naprawia blokad po wykryciu AdBlock/ABP ani blokad "kopiowania".

**Comment by gargul03** [comment]
No tak, zawsze się zapomniam, że te ułomne skrypty anti-cv to tylko na trudne / nawracające reklamy są, 
a zapominam się dlatego, bo skrypty do uBO i AdGuard, do których jestem przyzwyczajony, blokują wszystko co trudne, a ABP jak zawsze 10 lat za murzynami.
