### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by skibbipl** [MajkiIT/polish-ads-filter#17269]
### Zrzut ekranu 
![obraz](https://user-images.githubusercontent.com/4746858/95519577-a5373c80-09c5-11eb-8c17-a775d2035dad.png)

### Link bezpośredni 
https://www.komputerswiat.pl/aktualnosci/sprzet/amd-ryzen-5000-nowe-procesory-oficjalnie-zaprezentowane/jq24pml

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. Wejść na stronę i poczekać chwilę
2. 
3. 

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Firefox 83.0a1 (2020-10-06) (64 bity)
**Rozszerzenia i skrypty:** 
uBlock Origin
Nano defender
uMatrix
CanvasBlocker

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Oficjalne polskie filtry przeciwko alertom o Adblocku 
4. I don't care about cookies
Nano Defender Integration
Nano Filters
Nano Filters - Whitelist
Polskie Filtry Elementów Irytujących
Polskie Filtry RODO-Ciasteczkowe

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by gargul03** [comment]
U mnie nic nie wyskakuje, więc najprawdopodobniej to kolejny fałszywy alarm jak w https://github.com/MajkiIT/polish-ads-filter/issues/17247, znowu ktoś z dodatkowymi dodatkami i czort wie czym jeszcze...

**Comment by skibbipl** [comment]
Masz rację, na innej przeglądarce z innymi filtrami jest OK

**Comment by zaba-monika** [comment]
U mnie nie ma anty-adblocka, to zgłoszenie to fałszywy alarm, problem leży po stronie zgłaszającego, podobnie jak w https://github.com/MajkiIT/polish-ads-filter/issues/17247?_pjax=%23js-repo-pjax-container#issuecomment-711126945
