### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#17266]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/95452002-e5b49d00-0968-11eb-8b25-b0d94d5a9f29.png)

![obraz](https://user-images.githubusercontent.com/32641928/95452022-ebaa7e00-0968-11eb-948b-c1ad418cdb8b.png)

![obraz](https://user-images.githubusercontent.com/32641928/95452043-f238f580-0968-11eb-9a8f-810ebfc1f0bd.png)

![obraz](https://user-images.githubusercontent.com/32641928/95452072-fe24b780-0968-11eb-8dd2-85ff7ba4bfcb.png)

### Link bezpośredni 
https://www.dobreprogramy.pl/Amerykanska-ustawa-EARN-IT-grozna-dla-prywatnosci-w-internecie-EFF-ostrzega,News,111423.html

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
1. 
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Obejścia:

- zalogowanie się, 2 komentarze, 30 dni bez reklam, nie wylogowywać się.
- rozwiązanie z 90 dniami bez reklam wymaga napisania dobrego wpisu blogowego, który zostanie wyróżniony na głównej lub recenzji programu/dodatku, która przejdzie moderacje.

**Comment by gargul03** [comment]
> krystian3w : Mnie dają radę załadować się tylko napisy "`R E K L A M A`":

Jeszcze wczoraj i przedwczoraj sypało reklamami za kadżym razem (https://github.com/MajkiIT/polish-ads-filter/issues/13818#issuecomment-704487543)

Ale teraz faktycznie przy pierwszym wejściu same napisy, ale po odświeżeniu strony i również przy kolejnych wyskakują już reklamy, zarówno na FF i O, możesz potwierdzić?

**Comment by Barticf** [comment]
@krystian3w co to teraz za czary z tymi reklamami, że nie da rady zablokować ? Z YT i ogólnie google też problemy (nie działa automatyczne odtwarzanie, wyświetla info zalogowaniu)

**Comment by krystian3w** [comment]
Reklamy teraz opierają na skrypcie, który pewnie wykracza poza wepchanie go w logiczny regex, MajkiIT ani Oleg pewnie nie uczą się dalej jak czytać skrypt WP, by robić aktualizacje raz na tydzień gdy padnie stary jakiś `set-constant` i zrobi wyciek reklam lub pop-up z kółkiem.

Pewnie mój filtr padnie jak przerobią etykietki na używanie znaków z rosyjskiego/ukraińskiego/białoruskiego 🇷🇺 🇺🇦 🇧🇾 albo wcisną coś gdzieś (oni wiedzą).

---

Google widać chce by każdy założył konto Google, jak dla mnie te dwa pop-upy to taki łagodny bloker auto-odtwarzania w Chrome, nie mam w zwyczaju oglądania playlisty z 50 wideo po kolei.


Niby nawet Google kombinując jak reklamy przywrócić to uszkadza stare filtry/metody na pop-upy "Zanim przejdziesz dalej", "Zalogowani mają się lepiej" - teraz chyba zostaje na oba zainstalować `.user.js` co oba zamknie i kliknie potem "play" (gorzej jak chodzi by to leciało od któreś sekundy a nie od początku). W efekcie filtry z sierpnia 2020 tylko uszkadzają homepage a nie blokują załadowanie RODO / fejkowej ściany logowania.

https://greasyfork.org/en/scripts/410687-google-shut-up

(ten może już być zdezaktualizowany)
```js
// ==UserScript==
// @name        Dismiss YouTube login modal
// @namespace   https://www.youtube.com/
// @match       https://www.youtube.com/*
// @grant       none
// @version     0.1
// @description  Auto-click the dismiss button on YouTube's annoying login modal
// ==/UserScript==

(function() {
    "use strict";

    function clickButton(selector){
        let elm = document.querySelectorAll(selector)[0];
        if (elm){ elm.click(); }
    }

    function tick(){
        clickButton('#dismiss-button');
        clickButton('.ytp-large-play-button');
    }

    setInterval(tick, 10);
}());
```

---

@gargul03 niestety masz racje, po odświeżeniu już się reklamy obrazkowe ładują.

**Comment by gargul03** [comment]
Chłopaki coś wymajstrowałem, postestujcie każdy osobno (nie dwa na raz), reklamy ubite, niby nic nie uszkodzone, ale warto żebyście przetestowali czy oby coś nie uszkodzony itp (np. Gemius).:

`www.dobreprogramy.pl##+js(nostif.js,PrebidDamOpen,800)`
`www.dobreprogramy.pl##+js(aost, WP.gaf, prebidapi)`

**Comment by Barticf** [comment]
@gargul03 u mnie wygląda ok.

**Comment by krystian3w** [comment]
Nawet nie psuje powiadomień dla zalogowanych czy listy programów z sidebara (prawa kolumna) [przestarzałe set-constant słynęło z psucia obu).

**Comment by gargul04** [comment]
`www.dobreprogramy.pl##+js(nostif, PrebidDamOpen, 800)` lub
`www.dobreprogramy.pl##+js(aost, WP.gaf, prebidapi)` (<== wymaga uBO 1.30.0 lub wyżej)

**Comment by zaba-monika** [comment]
`www.dobreprogramy.pl##+js(nostif, PrebidDamOpen, 800)` lub
`www.dobreprogramy.pl##+js(aost, WP.gaf, prebidapi)` *wymaga uBO 1.30.0 lub wyżej)
