### ISSUE TITLE
otomoto.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17277]
![Screenshot_2020-10-11 OTOMOTO - nowe i używane samochody i motocykle oraz części samochodowe Ogłoszenia motoryzacyjne ](https://user-images.githubusercontent.com/36385327/95675364-02deab00-0bb7-11eb-8da8-1587a25529c1.png)

**Comment by krystian3w** [comment]
Randomizowane klasy, bawią się w WP to wyciekać będzie.

**Comment by gargul03** [comment]
A co ty Krystian piszesz jakimś polsko-angielskim, naród polski ma własne słowa np. "losowe" klasy...i gdyby twoja nauczycielka polskiego zobaczyła jak kaleczysz i zangielszczasz nasz piękny język ojczysty to by cię postawiła do kozy hahahaha (ok no ja tak pół-żartem, bo pewnie i mi się zdarzy użyć angielskiego wyrazu, pomimo polskiego odpowiednika) ale chyba raczej powinniśmy dbać o nasz język ojczyszty, czyż nie?! Hahaha :smiley:

**Comment by krystian3w** [comment]
To napisz lepszy filtr, który podziała 10 lat?

**Comment by gargul03** [comment]
Ja o języku, a ten o filtrze...a co ma filtr do języka? Tyle co pietrnik do wiatraka ale typ hahaha
