### ISSUE TITLE
press.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#1727]
tak wyglada strona, po wczytaniu. na dole sa reklamy. strona www.press.pl
![press](https://cloud.githubusercontent.com/assets/17565773/21394844/86b95f84-c79a-11e6-8b5a-299e07f241d5.jpg)

**Comment by xxcriticxx** [comment]
@lukjan32 ja nic nie widze jakis link maybe?

**Comment by lukjan32** [comment]
to znaczy?

**Comment by xxcriticxx** [comment]
@lukjan32 nie moge znalesc reklam podaj link albo screen shot

**Comment by lukjan32** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/17565773/21402792/5f71ab14-c7ba-11e6-8378-1dd3cff94196.jpg)

**Comment by MajkiIT** [comment]
Może coś takiego?
`www.press.pl##.big_image_post`
`www.press.pl##.appstore_post`

**Comment by lukjan32** [comment]
nie dziala

**Comment by MajkiIT** [comment]
Dodałeś to do moje filtry?

**Comment by lukjan32** [comment]
tak, i nic

**Comment by xxcriticxx** [comment]
@MajkiIT dziala tylko luki puste po reklamach

**Comment by lukjan32** [comment]
u mnie sa reklamy.

**Comment by xxcriticxx** [comment]
@lukjan32 podaj jakis screen shot? albo url?

**Comment by lukjan32** [comment]
cos chyba zadzialalo.
![1](https://cloud.githubusercontent.com/assets/17565773/21437125/68ee7370-c882-11e6-803e-a3387ce6b1cb.jpg)
![2](https://cloud.githubusercontent.com/assets/17565773/21437126/68f1591e-c882-11e6-93fd-73f2e1c01c6d.jpg)

**Comment by lukjan32** [comment]
reklamy nie ma, jest tylko puste miejsce, musze odswiezyc strone, to jest dobrze

**Comment by MajkiIT** [comment]
@lukjan32 sprawdzisz taką regułę?

`||www.press.pl/css/main_ads.css$stylesheet,domain=www.press.pl`

**Comment by lukjan32** [comment]
nie chce sie dodac, do moje reguly.

**Comment by MajkiIT** [comment]
@lukjan32 tzn?

**Comment by lukjan32** [comment]
jak daje zapisz, to ta regula znika.

**Comment by MajkiIT** [comment]
![2016-12-23_0950](https://cloud.githubusercontent.com/assets/11302675/21450238/3ee8d912-c8f5-11e6-9bb6-58aff5736574.png)

**Comment by lukjan32** [comment]
tak, daje, i znika regula.

**Comment by lukjan32** [comment]
dalej sa te puste miejsca, musze odswiezyc strona, to puste miejsca znikaja.

**Comment by MajkiIT** [comment]
W stronie strony jest kod który to robi trzeba użyć czegoś innego niż adblock/ublock.

**Comment by lukjan32** [comment]
aha, dobra.

**Comment by lukjan32** [comment]
znow, jest przerwa
