### ISSUE TITLE
wmeritum.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1729]
takie same reklamy jak na wykop

`http://wmeritum.pl/artur-dziambor-wystartuje-z-listy-wyborczej-grzegorza-brauna-otrzymal-jedynke-w-gdyni/119570`

![capture](https://cloud.githubusercontent.com/assets/15007183/21399446/a292185c-c779-11e6-9220-a3c1feca147f.PNG)

**Comment by MajkiIT** [comment]
`wmeritum.pl##[id^="wmeri-"]`

**Comment by xxcriticxx** [comment]
good strona cos dzisaj dlugo sie laduje
