### ISSUE TITLE
sacz.in

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17290]
( Biały baner w czerwonej ramce ) jest także, na : 

gorlice.in

limanowa.in

**Comment by krystian3w** [comment]
FAF `3.2.1`.

```
/js/adblock.js$script,redirect=nofab.js,domain=gorlice.in|limanowa.in|sacz.in,important
```

ABP wymaga dopuszczenia skryptu:

`@@/js/adblock.js$script,domain=gorlice.in|limanowa.in|sacz.in,important`

Niby w pliku nie ma nic co by ładowało substytut reklam "Google".

**Comment by gargul03** [comment]
> blocker999 : jest także, na : limanowa.in

No jest tylko co z tego, skoro już jest rozbrojony i sobie śpi (na uBO, nie wiem jak na ABP): https://github.com/olegwukr/polish-privacy-filters/blob/76c9760934854515ca974a9326fde8820c4eddd7/anti-adblock.txt#L272

> krystian3w : Niby w pliku nie ma nic co by ładowało substytut reklam "Google".

No nie ma, tylko co z tego, skoro jest w kodzie strony jako `inline`:

```js
<script>
	if(typeof fuckAdBlock === 'undefined') {
	    $('.adb').addClass('adbOn');
	} else {
		$('.adb').removeClass('adbOn');
	}
</script>
```

**Comment by krystian3w** [comment]
Mnie chodzi, że dopuszczenie może ułatwić im ładowanie reklam w przyszłości, dokleją coś do zaufanego pliku, bo pewnie łatwiej niż całą templatkę CMS.

**Comment by zaba-monika** [comment]
> blocker999 : limanowa.in

Tu się nie pojawia, bo jest już rozbrojony: https://github.com/olegwukr/polish-privacy-filters/blob/73321c85db3bfac95bf709cd77f9805d07bba44b/anti-adblock.txt#L272

> krystian3w : Niby w pliku nie ma nic co by ładowało substytut reklam "Google".

Jeśli nie ma w pliku to znaczy, że jest w kodzie strony jako inline:

```js
<script>
	if(typeof fuckAdBlock === 'undefined') {
	    $('.adb').addClass('adbOn');
	} else {
		$('.adb').removeClass('adbOn');
	}
</script>
```

**Comment by krystian3w** [comment]
@MajkiIT  jakaś resztka reklamowa w suplementach można spróbować użyć:

```css
gorlice.in,limanowa.in,sacz.in##.bannerContainer:style(visibility: hidden !important;)
```
