### ISSUE TITLE
oferia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1730]
reklama LEROY MERLIN 

`http://oferia.pl/zlecenie/item257007-wdrozenie-modulu-spolecznosciowego-na-joomla`

![capture](https://cloud.githubusercontent.com/assets/15007183/21399525/092a3b12-c77a-11e6-8423-74d71dc56bbb.PNG)

**Comment by F4z** [comment]
`||qad.quartic.pl/Ad/$script`
lub jeszcze bardziej ogólnie:
`||quartic.pl^$third-party`

**Comment by xxcriticxx** [comment]
ok

**Comment by kerbenii** [comment]
Hej, obawiam się, że dodaliście do listy za szeroki filtr.
Właśnie teraz wycinacie wszystkie nasze usługi (m.in. badania behawioralne, analitykę stron, podmiany produktów w ramkach sklepowych), zamiast usługi adservera.
Dodatkowo, co boli nas najbardziej blokujecie nasz panel klienta.

Bardzo proszę o zmianę filtru na:
```
||qad.quartic.pl/Ad/$script
||qad.quartic.pl/Ad/$script
||qad*.quartic.pl/Ad/$script
||qas*.quartic.pl/Ad/$script
```

który spowoduje zablokowanie wszystkich naszych adserverów (reklam), ale pozwoli nam świadczyć pozostałe usługi.

Dziękuję ślicznie,
Patryk Węgrzynek
Backend Developer
Quartic
