### ISSUE TITLE
przetargi.info

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17300]

**Comment by krystian3w** [comment]
@hawkeye116477 nie widzę paska, znowu dezaktywowane EasyList (te od reklam)?

Chyba, że to miał być likedin ze stopki...

**Comment by krystian3w** [comment]
Albo nas Kiboke z generykiem jakimś wyprzedził - tak też mogło być, raczej info nie zasługuje na dokopiowanie go, bo na słabych PC dobrze działa tylko ograniczenie pod domenę.
