### ISSUE TITLE
mmorpg.org.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17302]
https://mmorpg.org.pl/
![Screenshot_2020-10-12 Portal o grach MMO MMORPG MOBA ](https://user-images.githubusercontent.com/36385327/95793758-9662c980-0ce6-11eb-8b4c-87db5914c6f7.png)
https://forum.mmorpg.org.pl/categories
![Screenshot_2020-10-12 Forum o grach MMO MMORPG MOBA](https://user-images.githubusercontent.com/36385327/95793779-a2e72200-0ce6-11eb-805a-974ae689108f.png)

**Comment by krystian3w** [comment]
@hawkeye116477 / @blocker999  jaki status dla discord, to już "social media" w 2020?

**Comment by krystian3w** [comment]
A i ja widzę tam RSS, to tytuł z zaleceniem hawkeye w RSS/PASS.

**Comment by hawkeye116477** [comment]
No w zasadzie, Discord to jakby społeczność, nawet wiki tak mówi => https://en.wikipedia.org/wiki/Discord_(software) .

**Comment by blocker999** [comment]
Niewiem, nieznam się, może ktoś się wypowie i to uzasadni, np @xMaap
