### ISSUE TITLE
targowek.info

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17319]

**Comment by MajkiIT** [comment]
na razie strona padła

**Comment by krystian3w** [comment]
Nie padła: `http://www.targowek.info/`

wymaga `www.` i braku https

**Comment by gargul05** [comment]
Ciekawostka - z EasyList Polish (z której korzystam jako dodatkowe uzupełnienie) nie ma reklam na tej stronie.

**Comment by zaba-monika** [comment]
Ciekawostka / informacja: reklamy znikają po włączeniu list EasyList Polish (którą używam jako dodatkowe uzupełnienie).
