### ISSUE TITLE
onet.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1731]
Nie wiem, czy tylko ja mam takie "szczęście", ale u mnie znowu strona główna wykrywa adblocka - `http://www.onet.pl/`
To samo jest na vod.pl - `http://vod.pl/filmy-i-bajki-dla-dzieci/planet-hulk-hulk-na-obcej-planecie/6yxxbzw`
W przypadku onetu nie widać samego komunikatu, bo jest ukryty przez jedną z reguł kosmetycznych, ale strona jest mocno skrócona.
A na vod.pl wygląda to tak:
![image](https://cloud.githubusercontent.com/assets/11742596/21399686/d4c4fae6-c7ac-11e6-831d-3d0fc089912d.png)

Ta reguła u mnie pomogła:
`@@||csr.onet.pl/_s/csr-*/csr.jsx?site=*adblock$script,domain=onet.pl|vod.pl`

**Comment by MajkiIT** [comment]
mam to samo. Twoja reguła pomogła. Dodam ją do listy.
