### ISSUE TITLE
pl.kruk.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17325]
blokada scroola prawdopobnie przez ciastka

**Comment by krystian3w** [comment]
@kiboke please disable filtering elements on list - something like that:

`~pl.kruk.eu##.cookie-agreement:not(body):not(html)`
`~pl.kruk.eu###cookie_accept`

Filters break page if someone use ABP/AdBlock with only filters.

**Comment by kiboke** [comment]
I'll fix it, thanks!
