### ISSUE TITLE
pch24.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#1732]
Reklamy.

**Comment by F4z** [comment]
`||www.pch24.pl/js/banery.js$script`
`||www.pch24.pl/images/banery/$image`

**Comment by xxcriticxx** [comment]
cookie fix potrzebny na topie

**Comment by FadeMind** [comment]
@xxcriticxx 
`###showCookie:not(body):not(html)`
`###showCookie:not(body):not(html) ~ br`

**Comment by xxcriticxx** [comment]
@FadeMind thx dobra regula

**Comment by FadeMind** [comment]
@MajkiIT @F4z @xxcriticxx ( ͡° ͜ʖ ͡°)

Zaadoptujcie reguły z obszernego: https://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/

![image 1](https://cloud.githubusercontent.com/assets/9846948/21406017/ac30494c-c7c9-11e6-8d79-7fcde14092dc.png)

**Comment by xxcriticxx** [comment]
@FadeMind wiem @qwarser otym pisal
