### ISSUE TITLE
b2-biznes.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#1733]
Reklama pomiędzy artykułami.
Na przykład:

`http://b2-biznes.pl/wybory-w-usa-jest-decyzja-elektorow/`

`http://imgur.com/a/pD8Hz`

**Comment by F4z** [comment]
Powinno wystarczyć:
`||agoraperformance.pl^$third-party`

**Comment by xxcriticxx** [comment]
dobra
