### ISSUE TITLE
infokatowice.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1734]
reklama

`http://www.infokatowice.pl/2016/12/20/centrum-katowic-nagle-zrobilo-sie-bialo-tego-smrod-spalenizny-wideo/`

**Comment by F4z** [comment]
`infokatowice.pl##.widget_text.widget > .textwidget`
`infokatowice.pl##.vc_align_center.wpb_content_element.wpb_single_image`
`infokatowice.pl##.td-a-rec-id-content_inline.td-a-rec`

**Comment by xxcriticxx** [comment]
good pls add
