### ISSUE TITLE
tychy.info

### ISSUE THREAD

**Issue by Lukjan37** [MajkiIT/polish-ads-filter#17359]
brak udostepniania fb w artykulach

**Comment by krystian3w** [comment]
@hawkeye116477  znowu się zaczyna - @Lukjan37 aktywował filtry social i znowu narzeka.

**Comment by Lukjan37** [comment]
bedzie poprawka?

**Comment by krystian3w** [comment]
Nie, ta lista takie buttony wycina, wyłącz ją i zapomnij że istnieje.

**Comment by Lukjan37** [comment]
mam to wylaczyc EasyPrivacy i uBO Filters Privacy?

**Comment by krystian3w** [comment]
Nie te dwie.

Ty nie rozumiesz do czego ma służyć `Fanboy Social` i `Polskie filtry społecznościowe`. One ukrywają przyciski udostępniania.

Najlepiej będzie jak ci social będzie wyciekał a nie co kilka dni będziesz pytał jak odblokować kolejny przycisk "udostępnij w moich mediach społecznościowych (facebook / instagram / twitter / wykop).

**Comment by Lukjan37** [comment]
aha, wylaczylem polskie filtry i jest, mam tego nie dodawac w przyszlosci?

**Comment by krystian3w** [comment]
Wystarczy jak wyłączysz te dwa:

`Fanboy Social` i 
`Polskie filtry społecznościowe`

Bo określenie "polskie filtry", może znaczyć że wyłączyłeś też te dwa (co jest bez sensu):

![Przechwytywanie](https://user-images.githubusercontent.com/35370833/96223401-20808b80-0f8e-11eb-9f13-90fc68505b91.JPG) |
--- |

**Comment by Lukjan37** [comment]
tego fanboy social, nie mialem. 

dzieki.
