### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#1736]
Jeżeli przejdę z onetu na jakiś artykuł w komputerswiat, to na ich stronie wyświetli się informacja o adblocku:

Na przykład:
`http://imgur.com/a/TXfbY`

Adblock po przejściu:
`http://imgur.com/a/z9AdQ`

**Comment by xxcriticxx** [comment]
see #1731

**Comment by F4z** [comment]
Powinno pomóc:
`@@||csr.onet.pl/_s/csr-*/csr.jsx?site=*adblock$script,domain=komputerswiat.pl|onet.pl|vod.pl`

**Comment by mathew85** [comment]
Listę mam aktualną . @F4z Twoja reguła pomogła. Dzięki!

**Comment by xxcriticxx** [comment]
@F4z zmien regula @MajkiIT 

ja potestuje wiecej
