### ISSUE TITLE
quantcast.mgr.consensu.org

### ISSUE THREAD

**Issue by bug-rules** [MajkiIT/polish-ads-filter#17361]
Kilka nowych domen mogą być uszkodzone:

- `apkmirror.com`
- `tumblr.com`
- `cnews.fr`
- `hideout.co`
- `crfashionbook.com`
- `independent.co.uk`
- `today.it`
- `joe.co.uk`
- `ladbible.com`

Posortowane:

```
||quantcast.mgr.consensu.org^$domain=~apkmirror.com|~cnews.fr|~crfashionbook.com|~hideout.co|~independent.co.uk|~joe.co.uk|~joe.ie|~ladbible.com|~mirror.co.uk|~sourceforge.net|~sportsjoe.ie|~today.it|~tumblr.com|~vi.nl
```

wersja z filtru reklamowego: https://github.com/MajkiIT/polish-ads-filter/blob/26a5f7155ff45f48b187901a8b02b1ab94d9deca/polish-adblock-filters/adblock.txt#L3964

**Comment by hawkeye116477** [comment]
Może jednak lepiej po prostu byłoby to dodać jedynie dla `.pl`, w końcu to polska lista :smile:.

**Comment by MajkiIT** [comment]
@hawkeye116477 tak też zrobiłem :D
