### ISSUE TITLE
[META] Fałszywe alarmy (problem był po stronie zgłaszającego)

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17375]
Wątek techniczno-informacyjno-edukacyjno-archiwumowy, w którym można wklejać fałszywe zgłoszenia, w których problem był po stronie zgłaszającego (nie wiem czy ten wątek ma być w formie `otwarty` czy `zamknięty`):

#17247 
#17269 
#17374

**Comment by zaba-monika** [comment]
> https://github.com/MajkiIT/polish-ads-filter/issues/17374#issuecomment-711149120 : hawkeye116477 : 
>
> Ciekawe hobby. Ty to wszystko Monia zapisujesz :rofl: ? Może poleciłbym bardziej kolekcjonowanie jakiś pudełek z płytami z grami na PS/X albo kartridżami na Pstryczka, ewentualnie znaczków pocztowych...

Co do hobby, uważam, że poniekąd ciekawe i ma jakąś wartość edukacyjną, a jeśli dla ciebie niezbyt, to mogę specjalnie dla ciebie założyć wątek znikających kont na gihubie...myslę, że na pewno by cię zafascynował.

A trochę od strony technicznej - pokaż waszej obłudnej hipokryzji...na repo EI takie moje komentarze off-topic były przez was złośliwie ukrywane jako off-topic, bez względu na fakt, że nie mogłem ich umieścić w odpowiedniejszym wątku, bo go wcześniej zablokowaliście bez powodu / z powodu waszej nadgorliwości. Niniejszym w celu pokazania wam próbki waszej własnej hipokryzji wnioskuję do ciebie o samoukaranie, czyli żebyś sam ukrył swój własny komentarz jako off-topic jeśli masz jakieś resztki honoru, ale czy hipokryta może mieć w ogóle honor...

**Comment by xxcriticxx** [comment]
@gargul duzo jeszcze nickow masz?

**Comment by zaba-monika** [comment]
xxcriticxx nie off-topuj, idź stąd i nie przeszkadzaj jeśli nie chcesz udzielić się w temacie, bo zgłoszę cię do administracji za zakłócanie.

**Comment by zaba-monika** [comment]
Tyle ile trzeba żeby obejść wasze bezpodstawne bany.

**Comment by zaba-monika** [comment]
Nie mogę ci odpisać i ustosunkować się do twojej wypowiedzi w tamtym wątku ponieważ autor tamtego wątku wskutek porażki na argumenty w dyskusji ze mną zablokował mnie, więc odpiszę ci tutaj:
> https://github.com/MajkiIT/polish-ads-filter/issues/17374#issuecomment-711204823 : hawkeye116477 : Co za niegrzeczna dziewczyna ta Monia, chyba powinna dostać jakąś karę, może do kąta i 100 pompek...


Grzeczniej proszę, nie ubliżaj mi.

**Comment by zaba-monika** [comment]
Do adminów @xxcriticxx i @MajkiIT edytowałem pierwszy komentarz: https://github.com/MajkiIT/polish-ads-filter/issues/17375, warto przeczytać i zacząć etykietować takie fałszywe zgłoszenia.

**Comment by felix-22** [comment]
Lukjan - fałszywe trafienie odkrył krystian: https://github.com/MajkiIT/polish-ads-filter/issues/19368#issuecomment-809673686
