### ISSUE TITLE
bham.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17371]
https://bham.pl/wiadomosci/wielka-brytania/15116-dodatkowy-dyzur-konsularny-w-sobote
![Screenshot_2020-10-17 Dodatkowy dyżur konsularny w sobotę](https://user-images.githubusercontent.com/36385327/96338660-0333e600-1090-11eb-90fd-de379e2b763e.png)

**Comment by xMaap** [comment]
Social i jeszcze reklama

**Comment by xMaap** [comment]
@MajkiIT Tutaj się pojawiło
https://bham.pl
![2020-10-19 21 18 50 bham pl 0db660f1fc56](https://user-images.githubusercontent.com/36385327/96501484-b2b7b680-1250-11eb-8837-8fbd0f1fadf7.png)

https://bham.pl/wiadomosci/wielka-brytania/15123-restrykcje-w-anglii-nie-dzialaja-puby-powinny-byc-zamykane-o-18-00-lub-nawet-wczesniej
![2020-10-19 21 20 09 bham pl 14e7097f5d51](https://user-images.githubusercontent.com/36385327/96501619-e2ff5500-1250-11eb-8947-73cc0541c182.png)

I można zamknąć.

**Comment by MajkiIT** [comment]
@xMaap Dzięki
