### ISSUE TITLE
usa.se.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17379]
https://usa.se.pl/matka-zgwalcila-12-letniego-syna-pedofilka-aresztowana-aa-hJ7Y-QTfw-pjNS.html
![Screenshot_2020-10-18 Matka zgwałciła 12-letniego syna Pedofilka aresztowana](https://user-images.githubusercontent.com/36385327/96374772-110f6700-1175-11eb-9aaf-c9b9d545e95d.png)

**Comment by krystian3w** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/73321c85db3bfac95bf709cd77f9805d07bba44b

**Comment by MajkiIT** [comment]
@krystian3w a nie masz nawet adblocka o wyłączeniu filtrowania?
