### ISSUE TITLE
film.onet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1738]
ad block 

`http://film.onet.pl/zwiastuny/la-la-land-trzeci-polski-zwiastun/xmj814`

![capture](https://cloud.githubusercontent.com/assets/15007183/21406371/471c4446-c799-11e6-8f4f-931f845240bd.PNG)

**Comment by MajkiIT** [comment]
U mnie czysto.

**Comment by xxcriticxx** [comment]
see #1739

**Comment by Isamaul** [comment]
Patrzyłem kiedyś na to - wpada nawet bez adblocka jak coś się z odtwarzaniem popsuje

**Comment by xxcriticxx** [comment]
ok rozumiem
