### ISSUE TITLE
zabkowice.express-miejski.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17397]
" pelet drzewny " ( na dole ) : http://zabkowice.express-miejski.pl/gazeta-archiwum/16558,dza-20-306-2020

**Comment by MajkiIT** [comment]
http://zabkowice.express-miejski.pl/img/pubfiles/202010/1603096911353_5_16558_ZEEXM1016s001.jpg

To cały obrazek
