### ISSUE TITLE
etsy.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17409]
![2020-10-21 06 08 18 www etsy com 7506cf81f57d](https://user-images.githubusercontent.com/36385327/96672130-d881b000-1363-11eb-96b7-50f58b0e8b22.png)

**Comment by krystian3w** [comment]
@hawkeye116477 trzeba im pop-upy zamykać, używają czegoś podobnego do `vivrehome` - bo inaczej nie zmienimy `kraju`/`języka`/`waluty`.

Niby jest nawet pop-up powitalny i niby kiboke zamyka jeden z dwóch i dodatek się "wywala".
