### ISSUE TITLE
vivo.com/pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17408]
![2020-10-21 04 50 31 www vivo com c06a2b1d3fb4](https://user-images.githubusercontent.com/36385327/96667232-f5fd4c80-1358-11eb-99b6-63cbddeab810.png)

**Comment by krystian3w** [comment]
Znowu nas kiboke wyprzedził @hawkeye116477, duplikować:

`vivo.com##.common-prompt-privacy-bg, .common-prompt-cookie-bg`

Oni to chyba są z Polski i się rozlali na Europę...?

**Comment by hawkeye116477** [comment]
> Oni to chyba są z Polski

A skąd, to Chińczyki, należą do tej samej spółki co OnePlus.
