### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by machond** [MajkiIT/polish-ads-filter#17417]
### Zrzut ekranu:
![shinded3](https://user-images.githubusercontent.com/44931854/96748191-7fe4fe00-13c9-11eb-8f7a-8fe4936b0b07.PNG)

### Link bezpośredni:
Wstaw tutaj link bezpośredni do strony, na której występuje reklama albo błąd.
https://shinden.pl/epek/34848-shingeki-no-kyojin-2nd-season/view/158822#column-one-inner

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. Wejśc na link 
2. Otworzyć dowolny player
3. 

### Moja konfiguracja 
**Przeglądarka internetowa:**
Chrome
**Rozszerzenia i skrypty:** ublock

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Oficjalne polskie filtry przeciwko alertom o Adblocku 
4. Większość od MajkiIT.

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):** 
Oni mają bardzo agresywnego anit-adblocka, było już kilka ticketów o nich.

**Comment by MajkiIT** [comment]
@machond ja nie widzę linków to playerów 
![obraz](https://user-images.githubusercontent.com/11302675/96753315-fa188100-13cf-11eb-8b58-bd868af83edb.png)

**Comment by machond** [comment]
Może trzeba być zalogowanym.

Większy screenshot, za nim wciśnie się link do konkretnego playera.

![shinded3](https://user-images.githubusercontent.com/44931854/96754312-69db3b80-13d1-11eb-9990-5a14801ab409.PNG)

**Comment by zaba-monika** [comment]
> MajkiIT : @machond ja nie widzę linków to playerów

U mnie to samo, zarówno na Firefoxie jak i na Chroperze, 
pewnie trzeba mieć konto i być zalogowanym,
ciekawe czy problem jest tylko po zalogowaniu,
@machond dasz radę znaleźć link do jakiegoś video z tym anty-adblock, 
ale niewymagający logowania?

**Comment by machond** [comment]
@MajkiIT i @zaba-monika:
sprawdźcie tutaj: https://shinden.pl/episode/16217-0/view/116992#column-one-inner
Mi bez logowania wyświetla tam playera + tą capatche po kliknięciu w odtwarzacz.

Jeśli nie, dajcie znać zrobię Wam konto i dam dane ;)

**Comment by MajkiIT** [comment]
@machond sprawdź to 
`@@||spolecznosci.mgr.consensu.org/js/cmp.stable.min.js$script,domain=shinden.pl`

**Comment by machond** [comment]
Nope, dalej jest walidacja.

**Comment by MajkiIT** [comment]
@machond a jak dodasz?
`shinden.pl#@##ad-player, .box.ads`

**Comment by zaba-monika** [comment]
Mi działa po dodaniu obydwu na raz.

**Comment by machond** [comment]
No nie wiem, ja po dodaniu obydwu dalej dostaję capatche. Jesteście pewni, że działa?

**Comment by zaba-monika** [comment]
Faktycznie, znowu psują coś te listy ciasteczkowe jak zwykle których ostatnio nie używam... 
działa dopiero po wyłączeniu list / dodatków ciasteczkowych:
- Polskie Filtry RODO-Ciasteczkowe
- I don't Care About Cookies

**Comment by machond** [comment]
Wyłączyłem listy cookies, jednak dalej nie znika capatcha. Chociaż 2 komunikatu o ciasteczkach nie dostałem. Pierwszy o prywatności ręcznie akceptowałem.

**Comment by zaba-monika** [comment]
To widocznie trzeba zaakceptować także ten drugi, wyłączaj kolejne dodatkowe listy, zostaw tylko te podstawowe, aż wyskoczy ci też ten drugi i go też zaakceptuj.

**Comment by krystian3w** [comment]
Drugi można olać, bazują tylko na `consensu`, ciekawe czy potem wymuszą widoczność przycisków `fb`/`discord`.

**Comment by krystian3w** [comment]
@kiboke we need accept cookies on https://shinden.pl/episode/16217-0/view/116992#column-one-inner

So recommend is update generic on list:

```diff
-~a10.com,~gry.pl##body > div[class^="app_gdpr"]
+~a10.com,~gry.pl,~shinden.pl##body > div[class^="app_gdpr"]
```

**Comment by machond** [comment]
Any progress on it?

**Comment by krystian3w** [comment]
Wymuś aktualizację filtrów.

Nowy link (?), niby poprawki z dopuszczeniem `consensu` powinien widzieć uBO. Jak używasz [PCC/PCZ](https://github.com/PolishFiltersTeam/PolishCookieConsent) to najlepiej wymusić aktualizacje a nie czekać 7 dni aż 30 października lub 1 listopada sama się raczy wykonać (im później zainstalujesz dodatek tym bardziej się przesunie np. aż na 4 listopada).

W przypadku projektu **Kiboke**, to nie widzę by na liście dodano shinden do wyjątków (niby zaczynają się pojawiać aktualizacje co około 2 dni), dodatek nie został zaktualizowany do wersji 3.2.4 z akceptowaniem dla shinden.

---

Przy okazji AdGuard obszedł problem `hCaptcha` po przez JavaScript (Firefox raczej filtr zobaczy dopiero od wersji dodatku `3.5.13`+):

```js
var a=document.querySelectorAll('div[id^="COŚ_TAM"]');
0<a.length&&a.forEach(function(b){b.appendChild(document.createElement("COŚ_TAM")
```

czyli nie żaden np. `aopr` kompatybilny z uBO.

**Comment by kiboke** [comment]
> @kiboke we need accept cookies/GDPR `consensu` on https://shinden.pl/episode/16217-0/view/116992#column-one-inner
> 
> So recommend is update generic on list:
> 
> ```diff
> -~a10.com,~gry.pl##body > div[class^="app_gdpr"]
> +~a10.com,~gry.pl,~shinden.pl##body > div[class^="app_gdpr"]
> ```

I wasn't able to understand why it's needed. Could you please explain it in english? :)

**Comment by krystian3w** [comment]
Page have glitch with GDPR, no loads ads before accept, so hide pop-up generate anti-adblock "`reCAPTCHA`" test on users.

in code just ommit `+`, becasue `\`\`\`diff `no support hide `+` sign.

**Comment by machond** [comment]
Hi, problem with hCaptcha still exist like in first comment in this topic.
![image](https://user-images.githubusercontent.com/44931854/117799513-7e3e3300-b252-11eb-8ce0-eaab1fc9c5a4.png)

**Comment by krystian3w** [comment]
Jak chcemy dodać filtr `ape.js` to najlepiej z komentarzem:

```
! zobacz: https://github.com/gorhill/uBlock/wiki/Advanced-settings#userresourceslocation
! userResourcesLocation https://raw.githubusercontent.com/uBlock-user/uBO-Scriptlets/master/scriptlets.js
shinden.pl##+js(ape, [id^="spolecznosc"], div, style, display:block !important)
```

Podobnie można zrobić z suplemenetem reklamowym a kilka filtrów wymagających składni uBlock-user przegrupować w jedno miejsce. Gorzej jak uBo legacy nie wspiera kilku źródeł rozdzielonych spacjami - tamci jak muszą mieć swoje dziwne to muszą regularnie doklejać `scriptlets.js` jak rusza z uBO legacy (a nie musi), wtedy i ręcznie konwertować do starego formatu.

**Comment by machond** [comment]
Nie mam żadnego z nich: EasyList Cookies" i/lub "Fanboy's Annoyances.
Czyli co muszę zrobić, by pozbyć się tego hcaptcha?
