### ISSUE TITLE
napiprojekt.pl

### ISSUE THREAD

**Issue by MESWEB** [MajkiIT/polish-ads-filter#17418]
### Zrzut ekranu 
![Opera Snapshot_2020-10-21_212239_www hellozdrowie pl](https://user-images.githubusercontent.com/2931024/96778574-c9424700-13e3-11eb-9139-3d91e7ddbc7e.png)

### Link bezpośredni 
https://www.napiprojekt.pl/napisy-szukaj

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
1. Wyszukca tytul filmu
2. Kliknac w link filmu
3. Otworzy se reklama pelnoekranowa

### Moja konfiguracja 
**Przeglądarka internetowa:** Opera

**Rozszerzenia i skrypty:** 
1. AdBlock built-in
2. uBlock
3. uMatrix

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Testowalem tylko na operze. Reklama nie wyskakuje zawsze. Mozliwe ze jest pokazywana raz na 3 dni lub cos w tym stylu.

**Comment by hawkeye116477** [comment]
@MESWEB Nie śpiesz się tak, bo wiesz co wtedy się dzieje :smile:

Poleciłbym raczej wyłączyć AdBlock Opery, uBO styknie, to tak samo jak z antywirusami, lepiej jeden, bo się gryzą. 

A tak w ogóle, to ja na zrzucie nie widzę reklamy. To jest jakaś inna strona...

**Comment by xMaap** [comment]
U mnie nie ma.

@MESWEB usuń AdBlock, uMatrix nie jest już wspierany i pamiętaj nie używaj uBlock tylko uBlock Orgin.
Co do uMatrix zobacz
https://github.com/gorhill/uBlock/wiki/Blocking-mode
Lub Noscript ewentualnie Privacy Badger, ale tutaj sam się uczy co ma blokować.

**Comment by zaba-monika** [comment]
Potwierdzam zgłoszenie, po kliknięciu w link z filmem przekierowuje na stronę: 
`https://www.hellozdrowie.pl/?utm_source=napi&utm_medium=referral&utm_campaign=src01`
która jest widoczna na zrzucie ekranu w pierwszym komentarzu.

Przekierowanie jest jednorazowe, później już go nie ma, nawet po wyczyszczeniu cache & ciasteczek i twardym przeładowaniu strony. Jednakże wystarczyło zmienić IP, i przekierowanie znowu następuje, oczywiście znowu tylko jeden raz, potem wystarczy zmienić IP i znowu jednorazowe przekierowanie...

**Comment by MESWEB** [comment]
Problem wciaz wystepuje. Wersja listy **2020102902**

**Comment by MajkiIT** [comment]
@MESWEB tak wiem

**Comment by MESWEB** [comment]
> @MESWEB tak wiem

Czyli problem nie zsotal rozwiazany? Myslalem ze ten nowy wpis z .js powinien dzialac.

**Comment by MajkiIT** [comment]
@MESWEB powinien, ale nie działa. Szukam powodu.

**Comment by zaba-monika** [comment]
- przy okazji, na tej stronie był też inny problem https://github.com/MajkiIT/polish-ads-filter/issues/16253#issuecomment-720090493, 
- widać, że nie został on zaadresowany w żadnej z list, a dalej istnieje
- oczywiście problem jest po stronie strony ,a nie filtrów, i być może właśnie dlatego nie został naprawiony w filtrach, ale może pomimo tego, może warto byłoby go jednak zaadresować po stronie filtrów

**Comment by krystian3w** [comment]
Na liście reklamowej albo nigdzie.

**Comment by MajkiIT** [comment]
@AdamWr masz jakiś pomysł na to ?

**Comment by krystian3w** [comment]
Niby serwer weryfikuje czy ładować `hellozdrowie`, czyli uBO nie może nic zrobić (nie ma skryptletu na ładowanie ramki - oficjalnego, ten od `uBlock-user` raczej się nie liczy), AG może próbować w 1px ramce ładować losową stronę z napisami:

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#javascript-rules-1

**Comment by krystian3w** [comment]
`insert-iframe.js` https://github.com/uBlock-user/uBO-Scriptlets/blob/4d88c8f660b5da5053a9e70b23e09df9011851b4/scriptlets.js#L354

Tylko że takie coś nie chce działać, nie widzę w kodzie wstawionej ramki wcale:
`napiprojekt.pl##+js(ii, honeypot, body, https://www.napiprojekt.pl/napisy-42731-Ostatni-U-Boot-(1993), width: 1px !important; height: 1px !important; position: absolute !important; left: -3000px !important)`

**Comment by AdamWr** [comment]
Wygląda na to, że sposób zaproponowany przez Krystiana działa prawidłowo :)


> Tylko że takie coś nie chce działać, nie widzę w kodzie wstawionej ramki wcale:
> 
> > ```css
> > napiprojekt.pl##+js(ii, honeypot, body, https://www.napiprojekt.pl/napisy-42731-Ostatni-U-Boot-(1993), width: 1px !important; height: 1px !important; position: absolute !important; left: -3000px !important)
> > ```
> 
> w loggerze widzę, że niby się wykonało `insert-iframe` (czyli błąd dokumentacji lub blokady CSP na stronie?).
> 

Próbowałeś zmienić `honeypot` na jakąś liczbę?

**Comment by krystian3w** [comment]
Aha czyli to jest liczba ramek 🤯.
