### ISSUE TITLE
joemonster.org

### ISSUE THREAD

**Issue by 123tomek** [MajkiIT/polish-ads-filter#1742]
advertisment on joemonster.org during looking on films

**Comment by MajkiIT** [comment]
@123tomek jakiś konkretny url?

**Comment by 123tomek** [comment]
dowolny odtwarzany film (http://joemonster.org/filmy/80506/Takie_cudo_zbudowal_John_Joseph_Merlin_w_1773_roku) powoduje po przescrolowaniu ekranu w dół (aż zniknie wyświetlany film) wyświetlenie miniaturki z odtwarzanym filmem. Obecnie jest małe okno, w momencie zgłoszenia był jeszcze wielgachny czarny pas przez całą szerokość ekranu.
