### ISSUE TITLE
malydziennik.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1744]
![image 001](https://cloud.githubusercontent.com/assets/9846948/21438865/697521e6-c88b-11e6-9bc3-781e5274dbe5.png)

```
##.sda-slide-link
```

```
##.desktop.ads:nth-of-type(2)
```

**Comment by MajkiIT** [comment]
@FadeMind 
co powiesz na to?
malydziennik.pl##.desktop
||adsplayer.pl$inline-script
||adsnet.pl$script

**Comment by xxcriticxx** [comment]
masz cos na NETMEDIABROKER po prawej?

**Comment by FadeMind** [comment]
@MajkiIT 
![2](http://i1.memy.pl/obrazki/e851900631_co_to_za_czary.jpg)

**Comment by MajkiIT** [comment]
@FadeMind działa?

**Comment by F4z** [comment]
@MajkiIT `||adsplayer.pl$inline-script` nie psuje u Ciebie działania odtwarzacza na stronie?

![image](https://cloud.githubusercontent.com/assets/11742596/21440457/642a1252-c893-11e6-9dab-75314debe15b.png)

Chyba, że to jakiś typ reklamy, to wtedy raczej lepiej dać `||adsplayer.pl$script`, bo Adblock chyba `$inline-script` nie obsługuje?

**Comment by FadeMind** [comment]
Działa. Zastanawiają mnie puste miejsca w boxach: 
![image 004](https://cloud.githubusercontent.com/assets/9846948/21440515/a34ba3b0-c893-11e6-8f37-6ea2c56b0ea5.png)

**Comment by MajkiIT** [comment]
@F4z masz rację. Zostaje

malydziennik.pl##.desktop
||adsnet.pl$script
