### ISSUE TITLE
pozegnania.net

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1746]
cookie fix

**Comment by FadeMind** [comment]
![image 002](https://cloud.githubusercontent.com/assets/9846948/21439296/784c66c8-c88d-11e6-8232-6d79c22c092a.png)

**Comment by FadeMind** [comment]
Dodatkowo przyda się ukryć baner:
![image 003](https://cloud.githubusercontent.com/assets/9846948/21439318/a53cf0bc-c88d-11e6-920c-4e2069ab91bf.png)
```
###pozeg_billboard
```

**Comment by xxcriticxx** [comment]
regula jest dobra thx @FadeMind
