### ISSUE TITLE
support.kaspersky.com/pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17468]
https://support.kaspersky.com/pl/viruses/general
![Przechwytywanie zawartości sieci Web_25-9-2020_4339_support kaspersky com](https://user-images.githubusercontent.com/36385327/97097921-1ee25200-1677-11eb-86fb-2859eac51d43.jpeg)
https://support.kaspersky.com/pl/consumer
![Przechwytywanie zawartości sieci Web_25-9-2020_4512_support kaspersky com](https://user-images.githubusercontent.com/36385327/97097931-505b1d80-1677-11eb-8789-590205a4ae8b.jpeg)

**Comment by hawkeye116477** [comment]
W zasadzie to niby bardziej do Fanboya, bo jednak strona jest międzynarodowa.

**Comment by krystian3w** [comment]
Na pierwsze machnie ręką lub źle wytnie...

`##.footerLinkWrap:nth-of-type(1) p:nth-of-type(n+7):nth-of-type(-n+8)`

takiego filtru oni nie tworzą.
