### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17469]
Po tym jak opera uznala nanoblockera za niebespiecznego w filmach na YT wskakuje mi ramka z reklamą sama reklama sie nie odpala ale musze klikac pomiń reklame za kazdym razem jak cos chce odtworzyc obecnie używam tylko ublock origin z listami
![Screenshot_1](https://user-images.githubusercontent.com/21177361/97104016-aa2c0980-16b0-11eb-9db7-7a065d8854f7.png)

https://gist.github.com/gzenio22/04c79d272f899e23626497dceb07ea6f

**Comment by zaba-monika** [comment]
Nie dziwne skoro sobie cały youtube zwhitelistowałeś:

>  netWhitelist": "about-scheme\nallbox.tv\nalltube.com.pl\nclk.tradedoubler.com\ndarmowe.gry-online.pl\nepremki.com\ngabbbocakeomblphkmmnoamkioajlkfo.chrome-extension-scheme\ngry.jeja.pl\nhttps://www.youtube.com/channel/UCViVL2aOkLWKcFVi0_p6u6g\nlive.ipla.tv\nmediadisco.pl\nmoz-extension-scheme\nncplusgo.pl\nopera-scheme\nsupernatural.com.pl\ntinyfileshost.com\nuwaga.tvn.pl\nvivaldi-scheme\nwww.fakt.pl\nwww.gawex.pl\nwww.ipla.tv\nwww.kinoman.co\nwww.mygica.com\nwww.showmax.com\nwww.tapeciarnia.pl\nwww.twitch.tv\nwww.youtube.com\nxhamsterpremium.com

**\nwww.youtube.com**
