### ISSUE TITLE
poczta.interia.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17475]
poczta bez reklam 20% taniej ( obok logowania )

**Comment by krystian3w** [comment]
Ja tam na stronie logowania mam biały kwadrat. Musisz więc udowodnić, że po wyłączeniu blokady reklam nie zostaje reklama poczty premium za 17 zł + VAT.

---

@MajkiIT  nowy filtr na rozciąganie formularza logowania:
```
poczta.interia.pl##.ad-box
poczta.interia.pl##.border:has(+ .ad-box)
poczta.interia.pl#$##mainApp #sitebar, #mainApp #sitebar form { width: 100% !important; max-width: 100% !important }
``

**Comment by zaba-monika** [comment]
I znowu, podobnie jak w zgłoszeniu: https://github.com/MajkiIT/polish-ads-filter/issues/17471, nie ma tego przy włączonej liście `AdGuard Base`:

<details not-open>
<summary>zrzut ekranu 1</summary>


![capture_022_26-10-2020_12-45-33](https://user-images.githubusercontent.com/72980128/97168735-3d387280-1789-11eb-89ae-07029a0ab694.gif)
</details>

Pojawia się dopiero po wyłączeniu `AdGuard Base`:

<details not-open>
<summary>zrzut ekranu 2</summary>


![capture_021_26-10-2020_12-45-24](https://user-images.githubusercontent.com/72980128/97168790-54776000-1789-11eb-804b-bef3b3571154.gif)
</details>

Ale to chyba nie adblock tylko reklama.
