### ISSUE TITLE
vizjer.pl

### ISSUE THREAD

**Issue by m4st3rch3f** [MajkiIT/polish-ads-filter#17471]
Denerwujące pop-upy wyskakują przy kliknięciu w jakikolwiek element strony

**Comment by zaba-monika** [comment]
- strona ładuje video w ramce z innej strony: `playtube.ws` 
- `playtube.ws` było już zgłaszane i naprawiane kilka miesięcy temu: https://github.com/uBlockOrigin/uAssets/issues/7106
- jak widać filtr na popupy jest już przestarzały: https://github.com/uBlockOrigin/uAssets/blob/c340bccee4d1bb830456d7caaf0dd8f10c995a74/filters/filters.txt#L23390
więc trzeba go zaktualizować i zamienić, czyli: 
`playtube.ws##+js(aopw, _pop)` na 
`playtube.ws##+js(aopw, _run)`

**Comment by krystian3w** [comment]
strona ma śmieci dla KAD i @MajkiIT, nie trzeba odpalać żadnego wideo. Event listener pracuje już na homepage.

---

`hXXps://handelpro[.]vip/Ps18351m?external_id=67fe2f74940282d440f85fa81b2d28c6&creative_id=1211910&campaign_id=372486&publisher_id=15541892&utm_campaign=mb&utm_source=adsterra&utm_medium=pol_pop&utm_term=H_pol_pop_web_big_bl` - fake news stylizowany na puls biznesu / fakt 24.

**Comment by zaba-monika** [comment]
Ja jakoś tego całego syfu nie miałem, jedynie w odtwarzaczu, ale już wiem czemu, dopiero wyskoczył po wyłączeniu listy `AdGuard Base`...tam jest taki regex, który łapie skrypt z tym syfem:

`/^https?:\/\/([a-z0-9]{8,10}\.)?[a-z0-9]{5,}\.(com|bid|online|top|club)\/([a-z0-9]{2}\/){3}[a-f0-9]{32}\.js$/$script,third-party`

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/20aacb9b9fd01346883b19ad56b3944556031680#diff-eab2aaf469314f57267f6f71855a766738837ca60234d6105317854abe61152c

**Comment by zaba-monika** [comment]
Ooo jak widać po commicie, u nas też jest podobny, wystarczyło domenę dokleić...

**Comment by krystian3w** [comment]
Tyle, że zakres domen AdGuard nie pasuje, nie blokują `.biz` a jakieś `.bid`.

Czyli regex źle uBO "naprawia" lub AdGuard źle go zapisał, że łapie domenę spoza puli.
