### ISSUE TITLE
rynekinfrastruktury.pl

### ISSUE THREAD

**Issue by Yolocaust2137** [MajkiIT/polish-ads-filter#17480]
Na stronie podanej w tytule jest anti adblock. Używam firefoxa, adguarda + wszystkie filtry od MajkiIT, a i tak nie da się przeglądać, bo wyskakuje okno gdzie piszą, żeby wyłączyć adblocka

**Comment by MajkiIT** [comment]
@Yolocaust2137 ja nic nie widzę

**Comment by Yolocaust2137** [comment]
> 
> 
> @Yolocaust2137 ja nic nie widzę

![767](https://user-images.githubusercontent.com/73483922/97188948-5e5a8c80-17a4-11eb-949b-e66899f7da0e.png)

**Comment by Yolocaust2137** [comment]
Filtry, które mam:
![1](https://user-images.githubusercontent.com/73483922/97189228-a7124580-17a4-11eb-8e92-3c99c4dbcb26.png)
![2](https://user-images.githubusercontent.com/73483922/97189231-a7aadc00-17a4-11eb-97d4-11c0a6126667.png)
![3](https://user-images.githubusercontent.com/73483922/97189232-a8437280-17a4-11eb-9733-d9b6f30602e3.png)

**Comment by Yolocaust2137** [comment]
Sprawdziłem i nie miałem EasyList, więc dodałem, ale problem dalej występuje

**Comment by AdamWr** [comment]
@Yolocaust2137 Spróbuj proszę wyłączyć Privacy Badger.
Swoją drogą, to też jest Twoje zgłoszenie - https://github.com/AdguardTeam/AdguardFilters/issues/66411?

**Comment by Yolocaust2137** [comment]
> 
> 
> @Yolocaust2137 Spróbuj proszę wyłączyć Privacy Badger.
> Swoją drogą, to też jest Twoje zgłoszenie - [AdguardTeam/AdguardFilters#66411](https://github.com/AdguardTeam/AdguardFilters/issues/66411)?

Tak, ale potem sobie przypomniałem, że są przecież filtry

**Comment by AdamWr** [comment]
>Tak, ale potem sobie przypomniałem, że są przecież filtry.

Nie wiem, czy dobrze zrozumiałem odpowiedź, ale to zgłoszenia w repozytorium AdGuarda też dotyczy filtrów.

>Wyłączyłem privacy badgera i dalej to samo

Jak wyłączysz AdGuarda, to komunikat nadal się pojawia?

**Comment by Yolocaust2137** [comment]
> 
> 
> > Tak, ale potem sobie przypomniałem, że są przecież filtry.
> 
> Nie wiem, czy dobrze zrozumiałem odpowiedź, ale to zgłoszenia w repozytorium AdGuarda też dotyczy filtrów.
> 
> > Wyłączyłem privacy badgera i dalej to samo
> 
> Jak wyłączysz AdGuarda, to komunikat nadal się pojawia?

Wyłączyłem adguarda i problemu nie ma. Włączyłem privacy badgera i też problemu nie ma

**Comment by AdamWr** [comment]
Sprawdź proszę regułę z tego komentarza - https://github.com/AdguardTeam/AdguardFilters/issues/66411#issuecomment-716601920

Dodaj ją proszę do filtrów użytkownika.
Reguła:
`rynekinfrastruktury.pl#$#body div.adBanner { display: block !important; }`
i zostaw włączony tylko Podstawowy filtr AdGuard.

**Comment by Yolocaust2137** [comment]
> 
> 
> Sprawdź proszę regułę z tego komentarza - [AdguardTeam/AdguardFilters#66411 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/66411#issuecomment-716601920)
> 
> Dodaj ją proszę do filtrów użytkownika.
> Reguła:
> `rynekinfrastruktury.pl#$#body div.adBanner { display: block !important; }`
> i zostaw włączony tylko Podstawowy filtr AdGuard.

Nie musiałem wyłączać reszty filtrów. Dodałem tylko ten, który podałeś i działa. Dzięki!

**Comment by AdamWr** [comment]
Dziwna sytuacja. Na Twoich zrzutach ekranu widać, że większość filtrów była ostatni raz zaktualizowana w 2018 roku.
Spróbuj zaktualizować filtry ręcznie.

**Comment by Yolocaust2137** [comment]
> 
> 
> Dziwna sytuacja. Na Twoich zrzutach ekranu widać, że większość filtrów była ostatni raz zaktualizowana w 2018 roku.
> Spróbuj zaktualizować filtry ręcznie.

A jak to mogę zrobić?

**Comment by AdamWr** [comment]
Na przykład otworzyć główne okno AdGuarda i kliknąć przycisk do aktualizacji filtrów (tak jak na obrazku poniżej).

<details><summary>Obrazek</summary>

![image](https://user-images.githubusercontent.com/29142494/97193369-36b9f300-17a9-11eb-9cbb-ca461a07faf6.png)

</details>

Swoją drogą, wygląda na to, że korzystasz też ze starej wersji.

**Comment by Yolocaust2137** [comment]
> 
> 
> Na przykład otworzyć główne okno AdGuarda i kliknąć przycisk do aktualizacji filtrów (tak jak na obrazku poniżej).
> Obrazek
> 
> ![image](https://user-images.githubusercontent.com/29142494/97193369-36b9f300-17a9-11eb-9cbb-ca461a07faf6.png)
> 
> Swoją drogą, wygląda na to, że korzystasz też ze starej wersji.

A faktycznie, ślepy jestem, już zaktualizowałem, dzięki

**Comment by AdamWr** [comment]
Czy po aktualizacji filtrów problem z `rynekinfrastruktury.pl` i `wiadomosci.wp.pl` - https://github.com/AdguardTeam/AdguardFilters/issues/66414 nadal występuje?

Przy okazji, lista `Anti-Adblock Killer` od dłuższego czasu nie jest już aktualizowana, więc polem ją usunąć.

**Comment by MajkiIT** [comment]
@AdamWr dziękuję

**Comment by AdamWr** [comment]
Nie ma za co :)

**Comment by zaba-monika** [comment]
U mnie też nie ma anty-adblocka, pewnie kolejna fałszywka.

**Comment by Yolocaust2137** [comment]
> 
> 
> Czy po aktualizacji filtrów problem z `rynekinfrastruktury.pl` i `wiadomosci.wp.pl` - [AdguardTeam/AdguardFilters#66414](https://github.com/AdguardTeam/AdguardFilters/issues/66414) nadal występuje?
> 
> Przy okazji, lista `Anti-Adblock Killer` od dłuższego czasu nie jest już aktualizowana, więc polecam ją usunąć.

Już jest w porządku, dzięki
