### ISSUE TITLE
freesslvpn.us

### ISSUE THREAD

**Issue by Sergey-Lyapin** [MajkiIT/polish-ads-filter#17485]
`##.ad` rule is causing antiadblock on `freesslvpn.us`

The original issue with screenshots:
https://github.com/AdguardTeam/AdguardFilters/issues/66426

**Comment by krystian3w** [comment]
MajkiIT to trzeba by wykluczyć na poziomie listy reklamowej - USA nie wie by włączyć listę `PL anty-adblock` lub ona ciągle w AdGuard ma problemy by się włączała równocześnie z filtrami na polskie reklamy.

**Comment by krystian3w** [comment]
Domeny siostrzane z tym samym problemem:

`https://receivedsms.com/`
`https://robotvpn.com/`
