### ISSUE TITLE
memy.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1749]
mamy pusta pola po reklamach 

@FadeMind co to za czary?

**Comment by FadeMind** [comment]
`##.break-row.row`

`##.container:nth-of-type(2)`

**Comment by F4z** [comment]
@FadeMind myślę, że `##.container:nth-of-type(2)` jest trochę "niebezpieczne" i tutaj - `http://generator.memy.pl/` zdecydowanie za dużo ukrywa.

Ja bym zaproponował coś takiego:
`memy.pl##.container > div[style="height:250px; width:970px; margin-bottom: 10px;"]`
`memy.pl##.content-stream.view-meme > div[style="height:200px; width:750px;"]`
`memy.pl##.side-stream > div[style="height:600px; width:300px;"]`
`memy.pl##.content-stream.view-meme > #news > .break-row.row`

**Comment by MajkiIT** [comment]
@F4z Dzięki
