### ISSUE TITLE
strony filmowe

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#17499]
cuda na playerach online clipwatching + playtube + mixdrop
vodi.cc
filmeria.co

mucho popups
vizjer.pl
ekinomaniak.net

**Comment by zaba-monika** [comment]
Mi nic nigdzie nie wyskakuje, a `vizjer.pl` przecież dopiero co naprawiony https://github.com/MajkiIT/polish-ads-filter/issues/17471, może masz listy niezaktualizowane albo wyłączył ci się adblocker albo siedzisz na adblock plus haha

**Comment by krystian3w** [comment]
`vizjer` mógł wymyślić nowy sposób na `AaDetector`/`lieDetector` by obejść regexy:
 - AG, 🥇

     ```js
    /^https?:\/\/([a-z0-9]{8,10}\.)?[a-z0-9]{5,}\.(com|bid|online|top|club)\/([a-z0-9]{2}\/){3}[a-f0-9]{32}\.js$/$script,third-party
    ```
- Chińskie "EasyList" (niby najgorszy)

    ```js
    /\.com\/[0-9a-z]{2}\/[0-9a-z]{2}\/[0-9a-z]{2}\/[0-9a-z]{32}\.js/$script,3p
    ```

- Francuskie, 🥈 

    ```js
     /^https?:\/\/(www\.)?([a-z0-9]{3,10}\.)?[a-z0-9]{5,20}\.(click|co|com|bid|net|online|top|club)\/([a-z0-9]{2,3}\/){3}[a-f0-9]{32}\.js$/$script,xmlhttprequest
    ```

- Majkiego 🥉 
    ```js
    /^https?:\/\/[a-z0-9]{5,}\.(com|top|pro)\/[a-z0-9]{1,}\/[a-z0-9]{1,}\/[a-z0-9]{1,}\/[a-z0-9/]{4,}\.js/$script
    ```

---
Podobnie `playtube.ws`, dalej używa `_pop` razem z `_run`, posortowanie raczej nie zmnijesza szansy na race condition.

**Comment by MajkiIT** [comment]
@xxcriticxx możesz przeklikać po aktualizacji, bo chyba powinno być OK. Zerknij po swojej stronie proszę.

**Comment by zaba-monika** [comment]
> krysitan3w: Podobnie `playtube.ws`, uAssets dalej używa `_pop` razem z `_run`, posortowanie raczej nie zmniejsza szansy na race condition w uBO.

- uAssets używał i używa dalej tylko `_pop`, 
- `_run` jest tylko w AdGuard Base
- w uAssets zamiast `_run` dodali `+js(nowoif)`, czyli `window.open-defuser` który ubija każde okno, bez względu czy się nazywa `_pop `czy `_run` czy `sraka_szympansa`, ale nazywaj to dalej posortowaniem...

Generalnie za dużo zabawy w "zgaduj-zgadula" co się dzieje u xxcriticxx, u mnie nic się nie dzieje, musiałby podać więcej szczegółów, typu konkretne linki, listy itp.

**Comment by krystian3w** [comment]
>`_run` jest tylko w AdGuard Base

Nie widzę wycofania tego commita: https://github.com/uBlockOrigin/uAssets/commit/557317a2620d23527cdd8eb8369d2cf29a9dddae#diff-03b955eebef8886aa0f1ef70b305e9b7996de9a9e0adc9fe002db5a21d301c9fR23401

**Comment by zaba-monika** [comment]
No ok, faktycznie ktoś dodał, tylko skoro został dodany [WCZEŚNIEJ](https://github.com/uBlockOrigin/uAssets/commit/bb5d3a37c1294ef9ce0e2f89a441a38e9c67667a#diff-03b955eebef8886aa0f1ef70b305e9b7996de9a9e0adc9fe002db5a21d301c9fR23403) `playtube.ws##+js(nowoif)` który ubija każde okno bez względu na nazwę: `_pop`, `_run` czy `sraka-szympansa` to ciekawe:
- dlaczego nie usunięto `_pop` 
- po co dodano `_run`

Nie ma to jak duplikować filtry...

**Comment by krystian3w** [comment]
> ja nie dostałem powiadomienia o commicie

Ja też nie, to jest chyba poza subskrypcją tematu lub wyciszyłem temat jak przyszedł "`ganiji`".

**Comment by xxcriticxx** [comment]
ok robie update i testujemy

**Comment by xxcriticxx** [comment]
vodi.cc = gut
filmeria.co = strona mi sie rozjezdza
![Capture](https://user-images.githubusercontent.com/15007183/97432655-aee00000-18f2-11eb-9784-354eba5435ef.PNG)

**Comment by krystian3w** [comment]
> a byłem przekonany że miałem zaktualizowaną,

MS/GitHub cię oszukał, `gorhill` / `uBO-user` coś pisał, że przy przeciążeniu serwera dostajesz starszy plik niż istnieje byle obciążenie zaczęło spadać.

**Comment by xxcriticxx** [comment]
vizjer.pl = gut
ekinomaniak.net = gut

**Comment by zaba-monika** [comment]
> > zaba-monika: a byłem przekonany że miałem zaktualizowaną,
> 
> krystian3w : MS/GitHub cię oszukał, `gorhill` / `uBO-user` coś pisał, że przy przeciążeniu serwera dostajesz starszy plik niż istnieje byle obciążenie zaczęło spadać.

Raczej nie, po prostu aktualizowałem wszystkie listy i widocznie zapomniałem o listach `uBlock`.

==========================================================================

> xxcriticxx : filmeria.co = strona mi sie rozjezdza

> krystian3w : chyba tylko jak musi wysłać film aż do USA lub pi-hole ma źle zbanowaną jakąś domenę (tylko jaką, skoro zewnętrzne pliki to fonty Google/Awesome)?

U mnie się Interia rozjeżdza w taki sam sposób  https://github.com/MajkiIT/polish-ads-filter/issues/17497#issuecomment-717444366

**Comment by krystian3w** [comment]
U mnie niestety nawet w Chrome poprawnie załadowane, jak bez filtrowania się wywala to nie ma co szukać winy w uBO.

**Comment by zaba-monika** [comment]
No jeśli chodzi o mnie to ja winy w uBO nie szuałem i nie szukam, wspominałem tylko jako o ciekawostce...: "Przy okazji ciekawostka,"

**Comment by xxcriticxx** [comment]
wyczyszczenie historii + cookies i filmeria.co dziala z piholem

**Comment by zaba-monika** [comment]
A u mnie te same czynności nie pomagają w przypadku `interia.pl` która na Chroperze dalej się rozjeżdza...

**Comment by xxcriticxx** [comment]
@zaba-monika zaloz nowe issue dla `interia.pl`

**Comment by krystian3w** [comment]
Już jakieś ma: https://github.com/MajkiIT/polish-ads-filter/issues/17481, jak to jakiś CDN to testuj np.:

https://chrome.google.com/webstore/detail/localcdn/njdfdhgcmkocbgbhcioffdbicglldapd?hl=pl
https://www.localcdn.org/

PS. jak dla mnie może to psuć `redirect=`.
