### ISSUE TITLE
cdahd.co

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#17498]
Adblock został wykryty, prosimy o wyłączenie go na naszej witrynie, bo reklamy pozwalają tej stronie żyć, musimy zapłacić za hosting! Odśwież tę stronę po jego wyłączeniu! Dzięki!

**Comment by zaba-monika** [comment]
`@@||raupsica.net/bootstrap.css$xmlhttprequest,domain=cdahd.co`

**Comment by xxcriticxx** [comment]
działa dzięki

**Comment by krystian3w** [comment]
Rozwiązanie miało jakąś wadę:

https://github.com/olegwukr/polish-privacy-filters/commit/531939e14b3ace19676e7cf57cfe1b345836081c

Pewnie plik CSS nie był plikiem CSS i pozwalał ładować reklamy z pomocą JS.

**Comment by krystian3w** [comment]
Rozwiązanie miało jakąś wadę:

https://github.com/olegwukr/polish-privacy-filters/commit/531939e14b3ace19676e7cf57cfe1b345836081c

Pewnie plik CSS nie był plikiem CSS i pozwalał ładować reklamy z pomocą JS. Lub domena stała się nieosiągalna poza rejestrem whois.
