### ISSUE TITLE
lurker.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#17492]
https://www.lurker.pl/

**Comment by krystian3w** [comment]
Nie widzę, trzeba mieć konto, testowane z nową bazą "`I don't care about cookies`"?

---

Nie chodzi może o bardzo wąski pasek przesuwania w chrome lub strzałkę "przewiń w górę"?

`###scrollTopBtn`

**Comment by hawkeye116477** [comment]
Mam listę IDCAC z 23 października i tam to już jest, więc najwyraźniej @MajkiIT nie zasubskrybował wymaganej listy.

**Comment by krystian3w** [comment]
Niby dodał około 16 października: https://github.com/AdguardTeam/FiltersRegistry/commit/983765745c4691245da6b72bc401677b1596893b#diff-0b02fdda200b9e2bb01431d66384571bdf2ab30dbd077b128dde0eb4c6921080R19326
