### ISSUE TITLE
Pytanie dot list

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17502]
Hej jeśli źle wybrałem kategorie postu przepraszam i prosze o przypisanie innej etykiety... Ogl dawno mnie tu nie było i widze że sporo sie tu po zmieniało jest więcej list do wyboru na certyficate :D a dostalem tez info ze sam mialem nabalaganione w subskrybowanych listach więc postanowilem przywrucic ublocka do domyślnych i po bawić sie od zera 

s tąd moje pytanie 

Czy zrobiłem wszystko dobrze? co mogłbym dodać a co ewentualnie usunąć może któraś z list robi to samo co inna ktorą też subuję? 

https://gist.github.com/gzenio22/18f04604d88c2385cc06ce514ef89470

Z góry przepraszam za kłopot

**Comment by krystian3w** [comment]
Z oczywistych widzę:
```
    "https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt",
    "https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt",
```

`PPB` (**Polskie Filtry Elementów Irytujących**) ma w całości przekopiowane Polskie Filtry RODO-Ciasteczkowe czyli subskrypcje `adblock_cookies` można dezaktywować a i nawet usunąć.

---

> wybrałem kategorie

chyba w przyszłości trzeba użyć dyskusji: https://github.com/MajkiIT/polish-ads-filter/discussions

**Comment by krystian3w** [comment]
Z braków, to zapomniałeś o Fanboy Social:

[`https://easylist.to/easylist/fanboy-social.txt`](https://subscribe.adblockplus.org/?location=https://easylist.to/easylist/fanboy-social.txt&title=Fanboy-s-Social-Blocking-List)

Niezbędne jak chcesz poprawnie nam zgłaszać niewycięty social.

**Comment by gzenio22** [comment]
Ok usunołem nocoina i to co dodałem ręcznie no i ciasteczkowe dziękuje za pomoc :) zamykam

**Comment by zaba-monika** [comment]
> Z mniej oczywistych zbędne może być `NoCoin`, bo **gorhill** niby zapewnia, że wszytko jest w domyślnie aktywnym `uBlock filters – Resource abuse`.
> 
> To zostaje do twojej oceny jak niby czujesz, że strony mają koparki i dopiero NoCoin je unieszkodliwia poprawnie.

No właśnie, ja używam `NoCoin`, pomimo, że słyszałem kiedyś te zapewnienia goryla, a dlaczego, ano dlatego, że `Resource abuse` zawiera 117 filtrów podczas gdy `NoCoin` 1227 filtrów, teraz pytanie -  jak `Resource abuse` ma blokować tyle co 10 razy większa lista `NoCoin`, ktoś wie? Te 1227-117=1100 brakujących filtrów to niby gdzie są w `EasyList` albo w `EasyPrivacy`? Ktoś się orientuje?

**Comment by krystian3w** [comment]
Jeszcze zostaje kwestia gdy np. uBO nalicza `all` jako `x5` a AG taki precedens uznaje za 1 filtr:

```
---------------------------
Filter ID: 242
Filter name: NoCoin Filter List
Compiled rules: 636
Excluded rules: 38
URL: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
```

https://github.com/AdguardTeam/FiltersRegistry/blob/594917659badc68e764a7534d145ea074e5e683f/report.txt#L386-L387

Doliczając 18 skryptletów, z czego tylko 3 są użyte w uBO da nam:

```
692
```
