### ISSUE TITLE
nowaosada.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17500]
https://publicwww.com/websites/%22jak+najlepsza+obs%C5%82ug%C4%99%22+site%3Apl/

### https://lato.nowaosada.pl/

![capture_025_28-10-2020_09-52-50](https://user-images.githubusercontent.com/72980128/97413681-5d8c3c80-1903-11eb-870c-8096bc37999f.gif)

### https://zima.nowaosada.pl/

![capture_026_28-10-2020_09-52-56](https://user-images.githubusercontent.com/72980128/97413685-5ebd6980-1903-11eb-909b-36e3c4331744.gif)

### https://wiosna.nowaosada.pl/

![capture_027_28-10-2020_09-57-01](https://user-images.githubusercontent.com/72980128/97414194-fc189d80-1903-11eb-9d22-3a8525b6f1fe.gif)

![capture_028_28-10-2020_09-57-12](https://user-images.githubusercontent.com/72980128/97414202-fe7af780-1903-11eb-8e12-bcb39b6b2c87.gif)

**Comment by 5mintest** [comment]
Przyklejam:

> można jedynie eksperymentalnie odpalić generyk:
> 
> `pl#?#.popup:has(p:has-text(jak najlepsza obsługę))`
> 
>  z racji, że pop-up ma popularną klasę "`.popup`". Na to że `publicwww` i `nerdydata` nie zwracają innych użytecznych próbek stron nie wspomnę.
> 
> Ale im więcej takich będzie, tym bardziej pewnie spowolnią polskie strony.
>
> Pewnie niewiele da ogólny html filtering / skryptlet dla domen `pl`.

**Comment by zaba-monika** [comment]
> można jedynie eksperymentalnie odpalić generyk:

Filtr generalnie działa ( w sensie zamysł / projekt ), ale wykonanie do doszlifowania / poprawki:
`pl` ==> `nowaosada.pl`
`:has` ==> `-abp-has`
`:has-text` ==> `-abp-contains`
więc finalnie: `nowaosada.pl#?#.popup:-abp-has(p:-abp-contains(jak najlepsza obsługę))` 

> Ale im więcej takich będzie, tym bardziej pewnie spowolnią polskie strony.

Dokładnie, nie ma sensu dla kilku nieznanych stron dawać generyka i ryzykować spowalnianie, więc wystarczy jako domenę zamiast `pl` dać `nowaosada.pl`, co pokryje wszystkie pory roku:  `zima` , `lato ` oraz `jesien` i `wiosna` (w razie gdyby w przyszłości zaczęły działać.)

> Pewnie niewiele da ogólny html filtering / skryptlet dla domen `pl`.

- HTML filtering jest kompatybliny tylko z FF
- skryplet jest kompatybilny tylko z uBO i AdGuard (do `abp-circumvention` nie dodają filtrów ciasteczkowych)
- no chyba, że ktoś chciałby dodać jako uzupełnienie, ale po co, lepiej zmienić `pl` na `nowaosada.pl` do filtra, który jest kompatybilny ze wszystkim ad-blockerami, wtedy nie będzie ryzyka spowolnienia.

**Comment by 5minutes-bella** [comment]
> ale wykonanie do doszlifowania / poprawki:

Niekoniecznie. 

1. Obecna wersja bazuje na zaufaniu, że nie ma innych pop-upów z tą klasą (nie powinno mocno migać, jak miga to np. wina obsługi CSS w przeglądarce - https://github.com/uBlockOrigin/uBlock-issues/issues/1302#issuecomment-712283822):

    https://github.com/MajkiIT/polish-ads-filter/blob/a4eaf8b85408283901c1b3e4384ddedda7dbdac6/cookies_filters/adblock_cookies.txt#L744

2. ABP i AdBlock odrzucają `pl#?#` z `-abp` za brak konkretnej domeny, możesz na [Git**Lab**](https://gitlab.com/eyeo/adblockplus/adblockpluscore/-/issues/new)/[help.getadblock.com](https://help.getadblock.com/support/tickets/new) (tego Git**Laboranci** raczej nie czytają) zaproponować zniesienie blokady (lub propozycje uznawania `TLD`/public suffix za "domenę"), raczej zamkną "od razu".

    Czyli generyk `pl#?#` jest tylko sztuka dla sztuki:
    
    > `pl#?#.popup:-abp-has(p:-abp-contains(jak najlepsza obsługę))`

**Comment by zaba-monika** [comment]
>  1. Obecna wersja (...):
>        https://github.com/MajkiIT/polish-ads-filter/blob/a4eaf8b85408283901c1b3e4384ddedda7dbdac6/cookies_filters/adblock_cookies.txt#L744

Czy to znowu jakieś niedo.ebanie uBO z aktualizacją list czy co...:

<details not-open>
<summary>commit 14 godzin temu:</summary>



![111](https://user-images.githubusercontent.com/72980128/97539146-c5a15800-19c1-11eb-8440-bb0516111ce4.gif)

</details>


<details not-open>
<summary>zaktualizowałem listę ciasteczkową wczoraj 1-2 godziny po commicie </summary>


![2](https://user-images.githubusercontent.com/72980128/97539076-b0c4c480-19c1-11eb-884f-8d8af7f90bb1.gif)
</details>

i dalej cały wieczór miałem ten komunikat ciasteczkowy pomimo zaktualizowanej listy ciasteczkowej... 
dziś rano po przeczytaniu twojego komentarza, z filtrem `##.popup`  zacząłem się zastanawiać: skoro taki filtr  został dodany to jakim cudem wczoraj po aktualizacji listy ciasteczkowej ciągle ten komunikat ciasteczkowy wyskakiwał...więc wchodzę przed chwilą na `(lato|zima).nowaosada.pl` i nagle nie ma komunikatu, a nie aktualizowałem dziś listy...

> 
> 
> > > zaba-monika: a byłem przekonany że miałem zaktualizowaną,
> > 
> > 
> > krystian3w : MS/GitHub cię oszukał, `gorhill` / `uBO-user` coś pisał, że przy przeciążeniu serwera dostajesz starszy plik niż istnieje byle obciążenie zaczęło spadać.
> 
> Raczej nie tym razem, po prostu aktualizowałem wszystkie listy kilka godzin temu i teraz sobie przypomniałem, że zapomniałem o listach `uBlock`.
> 
> ==========================================================================

Może faktycznie masz rację z tymi przeciązeniami...do h.ja to niepodobne..pamiętasz ten stary błąd z nieaktualizowaniem się list w uBO? Od kiedy zostało to zgłoszone i naprawione u goryla, myślałem, że będzie święty spokój z tym cyrkiem na kółkach nazywającym się "pomimo, że zaktualizowałem listy, to nagle z dupy okazuje się przypadkiem, że lista jest niezaktualizowana, a ja wychodzę na głupka / ślepca" a tu jednak dalej cyrk na kółkach...

▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

> 2. ABP i AdBlock odrzucają `pl#?#` z `-abp` (...)

Jesteś pewien? Tzn masz na mysli również `nowaosada.pl#?#` ? Bo o ile `pl#?#` nie działa, to ja pisałem i proponowałem `nowaosada.pl#?#` , które działa bezproblemowo pod ABP (przed chwilą sprawdzałem na FF i Chroperze)...
