### ISSUE TITLE
Grupa - siecportali.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17501]
kolniak24.eu

fb ( u góry )

**Comment by blocker999** [comment]
i jeszcze : 

ciechocinek.biz
gniewkowo.eu
ki24.info
nizanskie.info

a reszta, powinna mieć, regułe ogulną :    pl##.scroll-down

**Comment by krystian3w** [comment]
Sprawę reklam pilnujesz na własną rękę.

**Comment by MajkiIT** [comment]
@krystian3w o co chodzi z tymi reklamami ?

**Comment by krystian3w** [comment]
Policz sobie zamknięte zgłoszenia @xmaap, gdzie zamknąłeś i olałeś reklamę.
