### ISSUE TITLE
topics.nl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1750]
Link - `http://www.topics.nl/`
Ta reguła - `##div[class*="cookie"]` - blokuje komunikat o ciasteczkach, przez co nie da się wejść na stronę.

Rozwiązanie:
`topics.nl#@#div[class*="cookie"]`

Znalazłem to tutaj - https://forum.adguard.com/index.php?threads/topics-nl-cookie-notification-filter-blocks-site.17977/#post-119408

**Comment by xxcriticxx** [comment]
Bylo to ostatnio tutaj gdzies

**Comment by F4z** [comment]
Jesteś pewny, że to samo?
Nie widzę takiego tematu - https://github.com/MajkiIT/polish-ads-filter/issues?utf8=%E2%9C%93&q=.nl

**Comment by xxcriticxx** [comment]
alex cos z adguard ostatatnio pisal
