### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by MESWEB** [MajkiIT/polish-ads-filter#17512]
### Zrzut ekranu 
![Opera Snapshot_2020-10-29_162418_www wykop pl](https://user-images.githubusercontent.com/2931024/97602653-767c1700-1a03-11eb-8fd0-dd9de6609a89.png)

### Link bezpośredni 
https://wykop.pl

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejsc na portal
2. Informacja powinna wyskoczyc natychmiast

### Moja konfiguracja 

**Przeglądarka internetowa:** Opera
**Rozszerzenia i skrypty:** uBlock Orgin, uMatrix
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda

**Comment by zaba-monika** [comment]
To wyskakujące okienko, a takie raczej kwalifikują sie na inne repo: `Polskie Filtry Elementów Irytujących` jako `popup`: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues, no chyba, że to się kwalifikuje jako `social`.

**Comment by MESWEB** [comment]
> Przypomina mi to to samo okienko zachęcające do rejestracji, które wyskakiwało osatnio na `youtube`, ale etykiety do zgłoszenia autor zgłoszenia nie dodał, więc czort go wie gdzie to się niby ma kwalifikować...@MESWEB jako co to zgłaszasz?

Ze tak powiem. Wy tu jestescie expertami - ja tu tylko sprzaram. Wybierzcie wedlug swego uznania.

**Comment by zaba-monika** [comment]
- akurat mi klasyfikowanie niektórych zgłoszeń sprawia trudności i przyprawia o zawrót główy więc..niech inni eksperci się wypowiedzą...
- `wykop.pl` od dawna (kilkunastu miesięcy) mam zablokowany za pomocą `||wykop.pl^` bo to zwykła trollownia i sama patologia tam siedzi...
- no ale dla celów zgłoszeniowych zrobiłem wyjątek i wszedłem, i na Firefoxie nie mam tego okienka nawet po wyłączeniu adblockera...
- a z kolei na Chroperze takie cuś:
![222](https://user-images.githubusercontent.com/72980128/97621478-3dec3580-1a23-11eb-964a-98e52f5576f7.gif)

**Comment by zaba-monika** [comment]
`wykop.pl##.closableContainerpopup_register`

**Comment by MESWEB** [comment]
> * `wykop.pl` od dawna (kilkunastu miesięcy) mam zablokowany za pomocą `||wykop.pl^` bo to zwykła trollownia i sama patologia tam siedzi...
Akurat mam tam perm bana i tylko poczytam wiadomosci i tyle. Wiem co sie tam odprawia oraz wiem o tym ze moderacja uzywa fake kont aby podtrzymywac sztuczny ruch na stronie.

**Comment by zaba-monika** [comment]
No ja tam kiedyś jako nowy użytkownik wrzuciłem wykop / news o pewnym tytule i został zakopany...

3 dni później ktoś inny wrzucił identyczny wykop / news o takim samym tytule i został wykopany (przez kilka razy liczebniejszą grupę osób)...

gdy się zapytałem co to za walenie w h.ja że dwa identyczne wykopy i mój pierwszy został zakopany a tamten drugi identyczny został wykopany, 

to ludzie odpisywali że najprawdopodbniej dlatego że ten drugi identyczny wykop wrzucony był przez użytkownika wykopu o nazwie `rmffm.pl` stąd miał większą popularność i został wykopany przez fanboyów / trolli z `rmffm.pl`

To ja pier.olę taką sprawiedliwość / równość..i podziękowałem temu ścierwu o nazwie `wykop.pl`, bo przypomina to wybory na Białorusi, gdzie większość ludzi głosowało na opozycyjnego kandydata, a w praktyce sfałszowali / strollowali wybory i wygrał psychopata Łukaszenko...

**Comment by krystian3w** [comment]
Social raczej nie, nie wiem czy on używa PolishAnnoyanceFilters (Polskie filtry elementów irtyujących), jak nie używa i nie chce używać, to dodawanie tam będzie drugą aferą #16790.

**Comment by zaba-monika** [comment]
To w takim razie idzie do [Polskie Filtry Elementów Irytujących](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues), a to że ich nie używa to jego problem, to sobie niech w takim razie wklei `wykop.pl##.closableContainerpopup_register` do Moje Filtry. Tyle w temacie.
