### ISSUE TITLE
zaluknij.xyz

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17510]
Hej 

Ta strona działa ma kupe reklam ale playery są darmowe i działają jeśli jest szansa po blokujmy reklamy ale ze spisu całych stron zablokowanych to zdejmijmy :)

**Comment by xxcriticxx** [comment]
Match found in https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt:
   www.zaluknij.xyz 
   zaluknij.xyz 
 Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   www.zaluknij.xyz 
   zaluknij.xyz

**Comment by zaba-monika** [comment]
Niby strona jest zablokowana jako oszustwo w KAD-Przekręty: https://github.com/PolishFiltersTeam/KAD/issues/1242
ale w praktyce, po wyłączeniu listy KAD wszedłem na stronę i normalnie oglądam film po polsku: 
https://zaluknij.xyz/movies/tajemnice-grobowca-w-sakkarze/
więc niby gdzie tu przekręt skoro można normalnie oglądać filmy, 
więc albo:
- a) strona niesłusznie dodana
- b) strona była kiedyś stroną typu przekręt z fałszywymi filmami, ale już nie jest (nawróciła się)
- c) albo np. niektóre inne filmy są fałszywe - poproszę w takim razie link da takiego fałszywego filmu

<br>

- stronę jako przekręt zgłosił internauta @mino815 : https://github.com/PolishFiltersTeam/KAD/issues/1242#issuecomment-622968249 
- a następnie stronę dodał do listy @krystian3w : https://github.com/PolishFiltersTeam/KAD/commit/905410ef6e3d8de9326f20d9702d69ad739d6718

Czy rzeczywiście strona w momencie zgłaszania i dodania do KAD była przekrętem czy może obydwu panom jednak należy się chłosta 10 uderzeń po tyłku z końskiego bata za niesłuszne dodanie zakwalifikowanie strony jako przekręt...

**Comment by MESWEB** [comment]
![Opera Snapshot_2020-10-29_163215_zaluknij xyz](https://user-images.githubusercontent.com/2931024/97603413-56992300-1a04-11eb-9a4e-54d19a71351c.png)
Mi ESET pokazuje ze jest tam jakis skrypt niehalo. Prosze sprawdzic skrypt jaki jest zgloszony.

**Comment by MajkiIT** [comment]
@MESWEB zaktualizowałeś filtry ?

**Comment by MESWEB** [comment]
> @MESWEB zaktualizowałeś filtry ?

Tak pokazuje mi ze mam zaktualizowane listy lecz nie wszystkie itemy sa uzyte.

**Comment by MajkiIT** [comment]
@MESWEB ja nie widzę u siebie alertu w eset

**Comment by krystian3w** [comment]
Może ma ustawiony tryb "paranoidalny" w heurystyce.
