### ISSUE TITLE
życzenia

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1753]
@xxcriticxx @kasper93 @F4z @FadeMind @blocker999 @mathew85 @gwarser 

Chłopaki chciałem Wam podziękować za pomoc i wsparcie. Przy okazji chciałem Wam życzyć spokojnych świat.

**Comment by FadeMind** [comment]
![15380558_10155204866811840_8687445085922347022_n](https://cloud.githubusercontent.com/assets/9846948/21449576/f7316996-c8ee-11e6-9080-10fd070457e3.jpg)

**Comment by blocker999** [comment]
Spokojnych Świąt, bez reklam życze wszystkim.

**Comment by xxcriticxx** [comment]
and happy new year!

**Comment by F4z** [comment]
Ja również życzę wszystkim wesołych i spokojnych Świąt.

**Comment by azet12** [comment]
No, wesołych.

**Comment by mathew85** [comment]
Wesołych Wam wszystkim!
