### ISSUE TITLE
poloniainfo.se

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17534]
resztki po reklamach i wyśrodkójcie tę strone

**Comment by krystian3w** [comment]
odkomentuj to i będzie wyśrodkowana:

```css
#thePage { /*	
    position: relative;
    margin: 0px auto 0px auto;
     max-width: 980px;
     background-color:white;
    padding: 0px 0px 0px 20px; */	
}

**Comment by zaba-monika** [comment]
A w czym problem?:
`www.poloniainfo.se###thePage:style(position: relative; margin: 0px auto 0px auto; max-width: 980px; background-color:white; padding: 0px 0px 0px 20px;)`

**Comment by krystian3w** [comment]
Powiedziałbym że w lenistwie, blocker nie chce się nauczyć jak używać element picker ani obsługi `-abp-has` / `-abp-contains`.

**Comment by zaba-monika** [comment]
Hahaha, skoro tak no to ok...a w ogóle to zabrzmiało jakby niemowlak nie chciał nauczyć się ssać z cycka..hahaha
Ja tam nie będę wnikała, bo kiedyś już blockera zganiłam wystarczająco w przeszłości, więc nie chcę mu znowu dokładać biedakowi, teraz ~~chłopaka~~ niemowlaka raczej oszczędzam i chwalę, bo dużo zgłasza. hihi

**Comment by bug-rules** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/17664
