### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by akmLaVx** [MajkiIT/polish-ads-filter#17530]
### Zrzut ekranu
Screen recording available here: https://drive.google.com/file/d/10hnyMGjWl05GxRyz1OjETzZ-1ZujazUF/view

### Link bezpośredni 
Any YouTube livestream will suffice.

### Co trzeba zrobić, aby pojawił się błąd?
1.  You should be a live stream moderator
2.  Type any message in chat. Message should contain Polish diacritic characters.
3.  Message will appear with a significant delay. Message without diacritics are not affected.

### Moja konfiguracja 

**Przeglądarka internetowa:** Chrome Release

**Rozszerzenia i skrypty:** AdGuard browser extension (ver. 3.5.20)

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Base
4. AdGuard Social Media
5. AdGuard Annoyances

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Problem can only be resolved by disabling _Official Polish Filters For AdBlock, uBlock Origin and AdGuard_. User has contacted AdGuard Support as a primary point of contact. Please @ me if you need any further details (HAR files, etc.).

**Comment by krystian3w** [comment]
Taki problem ma część normalnych użytkowników, w AdGuard Filters "repo" chyba 2 osoby się na to skarżyły.

**Comment by akmLaVx** [comment]
Dziękuję za odpowiedź! Ponieważ język polski nie jest moim językiem ojczystym, obecnie korzystam z usług tłumacza. 

Zgłosiłem ten problem twórcom filtrów AdGuard. Po kilku sprawdzeniach po naszej stronie, doszliśmy do wniosku, że AdGuard nie ma z tym nic wspólnego.

**Comment by MajkiIT** [comment]
I installed this add-on on Firefox and I don't have this problem. 
@AdamWr do you know something about it ?

**Comment by AdamWr** [comment]
I can't reproduce this issue with AdGuard extension for Chrome (3.5.20), but I'm not a moderator on any live stream.
@akmLaVx Does the first step ("You should be a live stream moderator") is necessary to reproduce this issue?

**Comment by akmLaVx** [comment]
Unfortunately, the issue still persists.
@AdamWr Yes, you should have mod privileges in a chat. I've tried doing it as a non-moderator - nothing seems to have helped.

**Comment by AdamWr** [comment]
>I've tried doing it as a non-moderator - nothing seems to have helped.

@akmLaVx  Do I understand correctly that you were able to reproduce it?
If so, could you please check this rule:
`@@||youtube.com^$elemhide`
