### ISSUE TITLE
allegro.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17557]
![Screenshot_1](https://user-images.githubusercontent.com/21177361/98532545-2104fd00-2282-11eb-9150-3780fe6893b2.png)

Znalazłem kwiatuszka :D zaznaczam ze mam tą liste filtrow do allegro

**Comment by krystian3w** [comment]
Sprawdź bez listy pod Allegro, nie miała aktualizacji od roku: https://github.com/MajkiIT/polish-ads-filter/discussions/17400

Niby Allegro i tak ma jakieś bugi, że infromacje o sprzedawcy załaduje za drugim razem, podobnie treść w pop-upie "a może frytki do tego  🍟" jak coś dodajesz do koszyka.

**Comment by gzenio22** [comment]
ouu bez listy alleblock czyli tej od alledrogo mam to samo

**Comment by krystian3w** [comment]
Sprawdź na innym źródle internetu np. hotspot z telefonu lub użyj jakiegoś VPN np. AdGuard (trzeba założyć darmowe konto):

https://adguard-vpn.com/en/welcome.html

Jak się naprawi to może wina leży w dostawcy internetowym.
