### ISSUE TITLE
cowkrakowie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17551]
Reklamy + cookes
https://cowkrakowie.pl/2020/11/kladka-im-o-bernatka-bedzie-rozswietlona-w-kolorze-bialym/
![Zrzut ekranu z 2020-11-05 08-18-03](https://user-images.githubusercontent.com/36385327/98209609-82a23000-1f3f-11eb-82d9-aabfe90af194.png)
![Zrzut ekranu z 2020-11-05 08-19-34](https://user-images.githubusercontent.com/36385327/98209701-acf3ed80-1f3f-11eb-8bad-76783e1e92f7.png)

**Comment by xMaap** [comment]
@MajkiIT https://cowkrakowie.pl/
![Zrzut ekranu z 2020-11-06 07-23-34](https://user-images.githubusercontent.com/36385327/98333429-03753080-2001-11eb-88ae-aca9d9eac979.png)

**Comment by krystian3w** [comment]
chyba self-promotion, jakby byli z sąsiedniego miasta...
