### ISSUE TITLE
onet.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1755]
Znowu wykrywa adblocka - `http://www.onet.pl/`
U mnie ta reguła pomogła:
`@@||lib.onet.pl/s.csr/adp/px.gif?$image,domain=onet.pl`

**Comment by xxcriticxx** [comment]
@F4z dodaj reszte domains na vod.pl jest problem 

![capture](https://cloud.githubusercontent.com/assets/15007183/21459931/0d78eb1c-c911-11e6-8223-88af826891bf.PNG)

**Comment by F4z** [comment]
@MajkiIT a może te dwie reguły zrobić ogólne?
`@@||csr.onet.pl/_s/csr-*/csr.jsx?site=*adblock$script,domain=komputerswiat.pl|onet.pl|vod.pl|auto-swiat.pl`
`@@||lib.onet.pl/s.csr/adp/px.gif?$image,domain=onet.pl`

Tak:
`@@||csr.onet.pl/_s/csr-*/csr.jsx?site=*adblock$script`
`@@||lib.onet.pl/s.csr/adp/px.gif?$image`

Czy lepiej nie?

**Comment by xxcriticxx** [comment]
maybe?

**Comment by MajkiIT** [comment]
@F4z jest super. Zaraz poprawię.

**Comment by F4z** [comment]
Znowu jest blokada, ta reguła powinna wystarczyć:
`@@||csr.onet.pl/_s/csr-*/csr.jsx?site=*adbIock$script`

Oprócz tego, można też dodać tę regułę:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=onet.tv`
żeby film, który jest po prawej stronie, na stronie głównej się szybciej wyświetlał.

**Comment by MajkiIT** [comment]
@F4z dodałem to 
`@@||onet.hit.gemius.pl/xgemius.js$script`

**Comment by F4z** [comment]
@MajkiIT ok, ta reguła też działa.
