### ISSUE TITLE
super-polska.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17553]
http://www.super-polska.pl/index.php
![Zrzut ekranu z 2020-11-06 07-55-02](https://user-images.githubusercontent.com/36385327/98335511-636dd600-2005-11eb-8e0c-b998a87c8cc2.png)
![Zrzut ekranu z 2020-11-06 07-55-19](https://user-images.githubusercontent.com/36385327/98335529-6ec10180-2005-11eb-95fd-876d0eb6647e.png)

http://www.super-polska.pl/id?id_artykulu=25379&Ukryci_w_naczepie_podr%C3%B3%C5%BCowali_do_Holandii
![Zrzut ekranu z 2020-11-06 07-56-04](https://user-images.githubusercontent.com/36385327/98335581-88624900-2005-11eb-8e32-3ab00fa424cf.png)

**Comment by MajkiIT** [comment]
```
www.super-polska.pl##.single_category > .single_bottom_rightbar > A > IMG
www.super-polska.pl##.content_bottom_right > A > IMG
```
