### ISSUE TITLE
filman.tv

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17554]
Kolejna strona zablokowana niesłusznie w KAD strona działa zawiera odnosniki do odtwarzaczy danych filmów

**Comment by MajkiIT** [comment]
@hawkeye116477 lub @krystian3w

**Comment by xxcriticxx** [comment]
wow...  Filmy online bez logowania, SMS-ów i kont premium.

**Comment by krystian3w** [comment]
Zniknie chyba o 19, jak chcesz to użyj `,badfilter`.

**Comment by gzenio22** [comment]
Wiem :) Ja tylko zgłaszam błędy w tym przypadku :)

**Comment by gzenio22** [comment]
działa zamykam
