### ISSUE TITLE
Polecane filtry

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#17559]
Czy możecie dodać "EasyList Polish" do listy polecanych filtrów (https://majkiit.github.io/polish-ads-filter/) 
EasyList Polish :
https://easylist-downloads.adblockplus.org/easylistpolish.txt
https://github.com/easylistpolish/easylistpolish

**Comment by krystian3w** [comment]
@hawkeye116477 jest na nie - usunął z mirroru https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters.netlify.com/commit/87b1ac9a15f53ed4095107fd3728fe5772cbfe25#diff-b2582afed7e81c621c6391c854eadc18b556b6ebebc4357456afc2108cc2db2dL227,
mi to obojętne,
więc to zależy czy @MajkiIT chce promować konkurencję.

**Comment by AroKol78** [comment]
żadna konkurencja , wzajemnie się uzupełniają

POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda​​​​​ użytych 7 100 z 7 233​
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku​​​​​ użytych 1 146 z 1 158

EasyList Polish​​​​​ użytych 3 677 z 3 835

**Comment by zaba-monika** [comment]
> AroKol78 : wzajemnie się uzupełniają

Zgadzam się, też byłam kiedyś tego samego zdania, ale goryl się pruł https://github.com/uBlockOrigin/uBlock-issues/issues/301 i nie chciał dodać EasyList Polish do uBO, bo jak argumentował :

> goryl : If anything is missing in the current POL list which is not in that EasyList Polish, I am sure the maintainers of the current POL list will quickly address such issues.

Po przetłumaczeniu na polski:

> goryl : Jeśli na aktualnej liście POL brakuje czegoś, czego nie ma w EasyList Polish, jestem pewien, że osoby prowadzące aktualną listę POL szybko zajmą się takimi problemami (stronami).

No fajnie tylko kto te strony znajdzie i pozgłasza...? Bo upłynęło 2 lata od odpowiedzi goryla, a EasyList Polish dalej usuwa reklamy na wielu stronach, na których nie usuwa reklam POL lista (i vice versa).

**Comment by hawkeye116477** [comment]
Mi się trochę nie podobał styl prowadzenia tej listy, sporo jakiś losowych reguł, np. https://github.com/easylistpolish/easylistpolish/blob/master/easylistpolish/easylistpolish_specific_block.txt#L831 i fakt, to konkurencja. Chociaż moje zdanie nie jest tu najważniejsze, liczy się zdanie szefa.

**Comment by zaba-monika** [comment]
- **co do losowych reguł:** I znowu kolejne oblicze twojej dobrze znanej hipokryzji, bo doskonale wiesz, że jeszcze nie dawno, tego typu losowych reguł było tak samo sporo w POL liście i był wątek gargamela gdzie on znalazł od pyty tego typu reguł w POL liście (a także w liście EI), wskazał wiele stron na których przez takie paździerzowe reguły powysypywało reklamy (teraz już ich tyle być może nie ma bo dzięki zgłoszeniu gargamela admin je pousuwał / ponaprawiał).

- **co do konkurencji:** Pewnie ty i twój szef wolelibyście monopol? Bo ktoś robi w waszej branży to od razu dla was wróg / niebezpieczeństwo i musicie go wyeliminować... i najlepiej żeby od razu twój szef razem z tobą rządził całą Polską? To macie z szefem zapędy jak Łukaszenka...A to że użytkownikom przydaje się EasyList Polish bo znakomicie uzupełnia POL listę, to pewnie was już nie obchodzi, by wy dwoje i wasze zapędy Łukaszenko-podobne są najważniejsze. Dalej - obydwie listy się wzajemnie uzupełniają, więc i tak każdy będzie używał obydwu list, a konkurencja jest zdrowsza niż monopol.

- **poza tym**: sporo zgłoszeń tutaj jest zamykanych bez naprawiania, i te nienaprawione oraz olane zgłoszenia zgłaszający wrzucają potem do EasyList Polish gdzie są naprawiane, nie wspominając, że admin nie lubi się z niczego tłumaczyć, a jak mu zwrócić uwagę to banuje jak Łukaszenko na Białorusi

Więc dobrze, że jest EasyList Polish która świetnie uzupełnia braki w liście POL (i vice versa).

**Comment by hawkeye116477** [comment]
> pewnie ty i twój szef wolelibyście monopol

Aha, czyli Biedronka na swojej stronie powinna zamieścić też ofertę z Lidla?

**Comment by AroKol78** [comment]
Na stonie https://majkiit.github.io/polish-ads-filter/ jest logo ABP i linki - więc reklama ?
Co przeszkadza dodać jeszcze jeden link do "EasyList Polish" ?

**Comment by MajkiIT** [comment]
@hawkeye116477 kiedy stałem się Twoim szefem ? 

@AroKol78 
A co dodania tych filtrów to ja ich nie używam i nie czuję potrzeby aby był sens ich dodawać. Ktoś uważa, że są potrzebne to niech sobie doda, ale ja ich nie zalecam. Szanuję zdanie @hawkeye116477 czy @krystian3w bo są wsparciem dla rozwoju Polskich filtrów. Co do błędów to każdemu się zdarzają i to normalne. Ktoś miał potrzebę robić oddzielne polskie filtry to spoko ma do tego prawo.

**Comment by AroKol78** [comment]
Dziękuje za informacje.

**Comment by hawkeye116477** [comment]
Po prostu miałem na myśli, że to twoja lista, repozytorium, więc ty tutaj rządzisz.

**Comment by zaba-monika** [comment]
> hawkeye116477 : Powiedziałbym, że rzadziej się zdarzały. 

Bazujmy na faktach / liczbach a nie na opiniach / "na oko" więc:
- albo dalej trolujesz wykorzystując fakt, że wątek gargamela został skasowany przez github więc ślady zatarte odnośnie ilości takich losowych reguł na POL liście...
- albo po prostu się mylisz i wydajesz mylne opinie wprowadzające w błąd na podstawie tego co wydawało ci się "na oko" , nie dokonując wcześniej żadnych wyliczeń / porównań ...tylko pogratulować ściśle naukowego podejścia do kwestii ściśle matematycznych...

Bo przed chwilą policzyłam i znalazłam 41 reguł losowych w EasyList Polish, a dobrze pamiętam, że takich reguł losowych w POL liście było conajmniej tyle samo albo nawet jeszcze więcej, więc nawet biorąc pod uwagę, że POL lista jest 2 razy większa, to dużej różnicy w ilości losowych filtrów nie było pomiędzy listami, w jaki sposób by tego nie szacował.

> hawkeye116477 : Lista EP natomiast jest tworzona stricte pod ABP, więc pewnie dlatego też jest trochę gorzej zoptymalizowana.

Z tą optymalizacją to chodziło ci o te losowe reguły, czy o jakieś nowe zarzuty?
Jeśli o nowe to czy mógłbyś wyjaśnić wszystkim na czym polegają te braki w optymalizacji, no chyba, że to znowu kolejne pomówienia bez pokrycia, bo poprzednie z losowymi regułami się nie udały...

> hawkeye116477 : Aha, czyli Biedronka na swojej stronie powinna zamieścić też ofertę z Lidla lub linki.

No i widać jak bizensowo do tego podchodzicie, no ale co się dziwić odkąd pojawił się na repo POL przycisk dotacji...to prywante interesy są ponad interesami internautów / społeczności. To po prostu napiszcie, że nie chcecie promowac konkurencji bo zarabiacie na POL liście.

> AroKol78 : Co przeszkadza dodać jeszcze jeden link do "EasyList Polish" ?

Właśnie dopiero co wyżej odpowiedziałem na twoje pytanie.

> MajkiIT : A co dodania tych filtrów to ja ich nie używam i nie czuję potrzeby aby był sens ich dodawać.

- jak już pisałem, chodzi o to czy społeczność / internauci chcą używać / czują potrzebę / uważają / polecają, a nie ty czy Łukaszenko, ale widać prywata górą...to może zmienić nazwę listy na POL: Prywatne Polskie Filtry...
- no i raczej chodzi o konkretne fakty / argumenty za lub przeciw, a nie o to ktoś "chce" czy "nie czuje" czy "nie zaleca" albo "uważa", bo z tego nic nie wynika jeśli nie stoją za tym jakieś konkretne argumenty, a póki co konkretne argumenty stoją za tym, żeby EasyList Polish używać, bo zwyczajnie blokuje sporo tego czego nie blokuje POL lista...a ty nie wymieniłeś póki co żadnych argumentów przeciw, poza "chceniem", "czuciem", "uważaniem" ,"polecaniem" itp. słuchać się tego nie da, gadasz o czymś nie mając uzasadnienia, zupełnie jak twój kolega hawkeye którego gadanie  o losowych regułach obaliłem

> MajkiIT :  ale ja ich nie zalecam.

A dlaczego to już pewnie zapomniałeś napisać..i niby gdzie tu argument?
A święty mikołaj napisze, że zaleca, i co z tego wynika? Nic.
Póki co argument "za" został podany, a argumentu "przeciw" póki co nie ma, pomijajac ten obalony z losowymi regułami.

**Comment by hawkeye116477** [comment]
Widać nie umiesz odpuścić, nie to nie.

> prywata górą

Czyli nikt nie ma prawa umieszczać według własnego zdania, musi być tak jak inni chcą... Rozumiem, co innego jakby prowadził serwis `listyfiltrow.pl`, to wtedy można byłoby się czepiać, że ogranicza konkurencję, ale to jest przede wszystkim personalny zbiór rekomendacji. Zresztą masz teraz dopisane na końcu, że jak chcesz więcej to zapraszamy na `filterlists.com`. Ale co tu dużo gadać, ty się zachowujesz tak samo jak zawsze, musi być tak jak on chce, bo jak nie to zrobi awanturę.

**Comment by AroKol78** [comment]
Co jest grane - dogadany monopol/wyłączność , zmowa korporacyjna
https://github.com/uBlockOrigin/uBlock-issues/issues/1336

**Comment by krystian3w** [comment]
Teraz najbardziej o dodaniu decyduje https://github.com/orgs/uBlockOrigin/teams/ublock-filters-volunteers/ i są oni tajni.

**Comment by AroKol78** [comment]
aż tak tajni - 404

**Comment by hawkeye116477** [comment]
@AroKol78 Tak, trzeba napisać do UOKiK :rofl: 
Co innego jakby gorhill dodał EasyList Polish i parę innych polskich list reklamowych na listę złych list (do której dodaje problematyczne listy), by nie można było samemu ich dodać, to już wtedy można byłoby podejrzewać o celowe ograniczanie konkurencji.

**Comment by AroKol78** [comment]
ELP nie jest problematyczną listą a wręcz przeciwnie. Ludzie powinni wiedzieć że taka lista istnieje i sami decydować czy używać.

> dogadany monopol/wyłączność , zmowa korporacyjna
  Zwraca 404, bo niestety tak już GH zadecydował, że drużyny organizacji są widoczne tylko dla jej członków.

nie pomyliłem się : Majestic-12

**Comment by AroKol78** [comment]
> * nom - poziom utajnienia: Ypsilon 😃

👍 🥇 👍 

> * nom, wszędzie ciche niepisane układy, powiązania, interesiki 😃 : mają powiązania z gorylem poprzez gwarsera proste...
> * a w ogóle to przydałoby się zaprosić stronę, skoro się o niej dyskutuje, a nie tak za plecami obgadywać, nie uważasz? 😃 @adblock-filters @TrollZbozowy @easylistpolish

👍 👍

**Comment by hawkeye116477** [comment]
> taki hawkeye jest wierny swojemu szefowi jak pies swojemu panu, więc żadne argumenty go chyba nie przekonają

A czy to jest moje repozytorium? Ja tutaj nie rządzę, więc nie mogę robić coś na przekór. Do sąsiada też chodzisz i ciasto mu podjadasz albo rozkładasz się mu na łóżku mimo, że zabronił?  

Na resztę szkoda mi nawet atramentu...

**Comment by AroKol78** [comment]
> taki hawkeye jest wierny swojemu szefowi jak pies swojemu panu

 👎  @zaba-monika - bez obrażania ludzi - bardzo proszę
> A czy to jest moje repozytorium? Ja tutaj nie rządzę, więc nie mogę robić coś na przekór.

👍  rozumiem i szanuje.

**Comment by zaba-monika** [comment]
@ hawkeye nikt nie każe ci robić nic na przekór, chodzi o to żebyś miał swoje własne zdanie, a nie całe życie przytakiwał dyrektorowi i kłapał tak samo jak on :smiley:

> hawkeye116477 :  Każdy twórca ma swoją wizję. 

- Łukaszenka też :smiley:

> hawkeye116477 : Na resztę szkoda mi nawet atramentu...

- przykro mi, że argumenty ci się skończyły...ty nawet jakbyś miał litr atramentu to byś i tak nic nie wymyślił na to co ja napisałem, bo kilka razy już mieliśmy dłuższe dyskusje i zawsze kończyło się tak samo, czyli twoim trolowaniem:
- 1) najpierw gdy ci kończą argumenty, to obrzucasz jakimś urojonymi albo złośliwymi zarzutami ad-personam
- 2) później imputujesz mi zawsze, że się awanturuję, nawet gdy tylko spokojnie dyskutuję
- 3) potem chowasz głowę w piasek jak struś i uciekasz od porażki w dyskusji takimi wymówkami typu: "i tak nie zrozumiesz", "szkoda czasu ci tłumaczyć" , "szkoda atramaentu" itp. to takie wygodne

Ale co tu dużo gadać, ty się zachowujesz tak samo jak zawsze, musi być tak jak on chce, bo jak nie to zaczyna trolować... :smiley:

> AroKol78  :  bez obrażania ludzi - bardzo proszę

A gdzie ty tu niby obrażanie widzisz, to tylko metafora, nie nazwałem go psem a ni nie zwróciłem się do niego "psie" , jedynie chodziło o porównanie wierności..no ale baletnicy to i rąbek u spódnicy...Lepiej zobacz jak on troluje w każdej dyskusji...a trolowanie to też obrażanie...

**Comment by AroKol78** [comment]
jest już w polecanych `urlhaus-filter, KAD, NoCoin, Spam404`
to może można dodać (szczególnie ten pierwszy) do `https://majkiit.github.io/polish-ads-filter/`

`https://gitlab.com/curben/phishing-filter` "Phishing URL Blocklist"
`https://curben.gitlab.io/phishing-filter-mirror/phishing-filter.txt`

`https://phishing.army/`
`https://phishing.army/download/phishing_army_blocklist.txt`

wiem że jest `https://filterlists.com/` , ...

**Comment by hawkeye116477** [comment]
Hehe, pomoc o2 jest jako phishing :smiley:

**Comment by AroKol78** [comment]
zgłosiłem się na `https://github.com/curbengh/phishing-filter`

**Comment by krystian3w** [comment]
Nie wiem czy on czyta tamte zgłoszenia, powinien zablokować skoro to raczej "mirror".

https://gitlab.com/curben/phishing-filter/-/issues?scope=all&utf8=%E2%9C%93&state=opened

**Comment by AroKol78** [comment]
zgłosiłem na `https://gitlab.com/curben/phishing-filter/-/issues`

**Comment by AroKol78** [comment]
"Phishing URL Blocklist" `||pomoc.o2.pl/polityka-prywatnosci$all`

`https://pomoc.o2.pl/polityka-prywatnosci` - blokowane ?
`https://pomoc.wp.pl/polityka-prywatnosci` - nie blokowane ?

**Comment by krystian3w** [comment]
Trzeba drugi raz poprosić o jeszcze jedno "exclude".

tu zobaczysz że system usunął ban domeny ale dodał ban "katalogu"/"ścieżki".

**Comment by AroKol78** [comment]
pierwsza naprawa - `https://gitlab.com/curben/phishing-filter/-/commit/99ca30b7deacbf18c329c373a429f364b2ee73b5`
podany link - `https://phishtank.com/phish_detail.php?phish_id=6891502` :smiley:(udowodnienie że jestem wielbłądem :camel:)

**Comment by hawkeye116477** [comment]
Jakiś dowcipniś zgłosił najwyraźniej. No chyba, że hakerzy się wtedy włamali na parę dni i jakieś konkursy urządzali, jak to było np w przypadku MPK....

**Comment by krystian3w** [comment]
Albo to efekt, że WP kupuje brzydkie domenki i robi przekierowanie z pomocą PHP / `.htaccess`.

**Comment by hawkeye116477** [comment]
https://www.hybrid-analysis.com/sample/00fedfebe4cdd68fdcea0233e7396e5b791ab175ca21ec034e647a6184707d7d/601c0898135ddc10c630a03f

**Comment by krystian3w** [comment]
Może czepiają się kompresji pliku biblioteki WP ale to jeszcze nie powód by tracking WP uznawać za phising.

**Comment by AroKol78** [comment]
zrozumiałem tylko tyle (za cienki jestem w uszach) :
`phishtank` profilaktycznie zablokował z powodów opisanych w powyższych komentarzach
`wp` wprowadza "nową politykę prywatności" - łącz z każdym

konkluzja :
problem ma `wp` -  jak ich politykę "prywatności" określają  jako "phish 73%"
za mały powód by zrezygnować z "Phishing URL Blocklist" dla jednej strony `https://pomoc.o2.pl/polityka-prywatnosci` (przyznaje się - dwa razy na niej byłem 😄)
(ciekawie jak wygląda sprawa dla `https://pomoc.wp.pl/polityka-prywatnosci`)

**Comment by AroKol78** [comment]
`https://pomoc.o2.pl/` ("Phishing URL Blocklist")
"Dane osobowe podane w formularzu będą przetwarzane w celach związanych z obsługą zgłoszenia zgodnie z naszą **polityką prywatności**." link `https://pomoc.wp.pl/polityka-prywatnosci` działa bezpośrednio z witryny (na tej samej karcie), ale jak otwieram w nowej karcie to problem `||pomoc.o2.pl/polityka-prywatnosci$document`

**Comment by krystian3w** [comment]
Nie napisałeś po polsku "jaka krzywda dzieje się w tej nowej otwartej karcie".

Pan od listy "Phishing" wyjaśnił, że masz sobie zgłosić FP jak ruszy rejestracja w **PhishTank**(OpenDNS) lub dodać dla siebie:

```
||pomoc.o2.pl/polityka-prywatnosci$document,badfilter
```

z racji, że nie warto robić forka jego listy z dodatkowym wykluczeniem w post produkcji (za duża strata czasu na reklamę projektu jako "lepszy od oryginału").

**Comment by AroKol78** [comment]
> Nie napisałeś po polsku "jaka krzywda dzieje się w tej nowej otwartej karcie".

?
