### ISSUE TITLE
piratebay.com

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17566]
https://spidersweb.pl/2020/11/domena-piratebay-org-thepiratebay-domena-zapasowa.html

Ja to tu zostawie a wy po niuchajcie czy cos faktycznie ta domena teraz wyciąga

**Comment by krystian3w** [comment]
Pirate Bay chyba nie miało nigdy polonizacji.

```
https://odysee.com/?utm_source=PB&utm_medium=referral
```

Niby polski jest ale spolonizowanych filmów nie widzę.
