### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17588]
WP szaleje tempermonkey mam ustawiony na zawsze blokuj wiec nie wiem

**Comment by zaba-monika** [comment]
Duplikat mojego zgłoszenia: https://github.com/MajkiIT/polish-ads-filter/issues/17364

**Comment by krystian3w** [comment]
tampermonkey nie blokuje reklam, skrypt jest przestarzały.

**Comment by gzenio22** [comment]
Ubo z listami tez nie Xd

**Comment by krystian3w** [comment]
Nie bynajmniej a przynajmniej
