### ISSUE TITLE
wygląd - "Polecane listy filtrów"

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#17587]
1. menu listy powinno być wyrównane do lewej
2. niektóre ikony są słabo widoczne
3. dużo przewijania - może jakiś zwarty układ (wersja mobilna/desktop)

https://majkiit.github.io/polish-ads-filter/ res 1440x900
![fixlist1](https://user-images.githubusercontent.com/70756447/98739493-bf3fb280-23a9-11eb-88db-4c76a15170c1.PNG)

**Comment by hawkeye116477** [comment]
ad. 1. Tekst w rozwijanym menu jest już wyrównany do lewej, więc nie wiem co masz na myśli, chcesz usunąć margines?
ad. 2. To już pewnie jest subiektywne. A tak dokładniej to które?
ad. 3. Przewijania tabeli czy chodzi o te menu rozwijane z wyborem list? W menu wyboru jest wyszukiwarka, by za dużo się nie namęczyć przy przewijaniu :smile:. Fakt, jest trochę problem na mobilnych, bo wychodzi nieco za ekranJeżeli chodzi o tabelę to swą dwa układy - na PC jest bardziej tradycyjny z racji większego ekranu, a na mobilnych jest nieco inny, by uniknąć przewijania w bok.

**Comment by zaba-monika** [comment]
W sumie mam d.pie taką upolitycznioną liste, ale skoro ktoś założył taki wątek, a ja mam chwilę czasu, to znalazłem błąd logiczny, wypisałem wszystkie możliwe logiczne kombinacje, aktualnie stosowana kombinacja to **3**, podczas gdy jedynie kombiacje **1** i **2** są logiczne, a **3** i **4** są pozbawione logiki, to pozbawienie logiki polega na tym, że część pogrubiona znajduje się tylko w jednym z punktów, zamiast w obydwu albo w żadnym, może ktoś nie zwrócił uwagi / pomylił się albo jego logika "w kratkę" pozostawia wiele do życzenia, bo gdyby  narysować człowieka wg. takiej logkiki, to nie miałby jednej ręki albo nogi..:

### Kombinacja 1:
* a) Jeżeli masz rozszerzenie I don’t care about cookies, to nie musisz subskrybować listy o tej samej nazwie.

* b) Jeżeli korzystasz z Polskich Filtrów Elementów Irytujących, to nie dodawaj listy RODO-Ciasteczkowej.

### Kombinacja 2:
* a) Jeżeli masz rozszerzenie I don’t care about cookies, to nie musisz subskrybować listy o tej samej nazwie, **ponieważ Filtry I don’t care about cookies znajdują się już w dodatku I don’t care about cookies.**

* b) Jeżeli korzystasz z Polskich Filtrów Elementów Irytujących, to nie dodawaj listy RODO-Ciasteczkowej, **ponieważ Filtry RODO-Ciasteczkowe znajdują się już w Filtrach Elementów Irytujących.**

### Kombinacja 3:
* a) Jeżeli masz rozszerzenie I don’t care about cookies, to nie musisz subskrybować listy o tej samej nazwie.

* b) Jeżeli korzystasz z Polskich Filtrów Elementów Irytujących, to nie dodawaj listy RODO-Ciasteczkowej, **ponieważ Filtry RODO-Ciasteczkowe znajdują się już w Filtrach Elementów Irytujących.**

### Kombinacja 4:
* a) Jeżeli masz rozszerzenie I don’t care about cookies, to nie musisz subskrybować listy o tej samej nazwie, **ponieważ lista I don’t care about cookies znajduje się już w dodatku I don’t care about cookies.**

* b) Jeżeli korzystasz z Polskich Filtrów Elementów Irytujących, to nie dodawaj listy RODO-Ciasteczkowej.

**Comment by AroKol78** [comment]
1. lista wychodzi poza ekran - powinna być przesunięta do środka, zachowuje się tak jakby nie miał miejsca po lewej stronie (1440x900)
2. adguard-home , diversion  (dark mode)
3. całą stronę , przewijanie list jest ok

nie chodzi o żaden konkretny filtr

**Comment by hawkeye116477** [comment]
@zaba-monika Lepiej zjedz Snickersa...

**Comment by krystian3w** [comment]
W sumie dodatek **Kiboke** może mieć przestarzałe filtry lub makaron spagetti 🍝 JS w wyniku czego można uzyskać różne rezultaty blokowania pasków i wyskakujących okienek RODO/ciasteczowych.

**Comment by AroKol78** [comment]
1. bardzo dobra robota 👍 :trophy:
2. diversion 👍 ,adguard-home ? black
3. dużo przewijania - może jakiś zwarty układ (1440x900) ?
![fixpllist02](https://user-images.githubusercontent.com/70756447/98836056-894e0d00-2441-11eb-820d-a4af3534d9c4.PNG)

**Comment by krystian3w** [comment]
`revert(180)` bo `1` pewnie od Chrome 86 i Firefox 82 działa.

**Comment by zaba-monika** [comment]
> hawkeye116477 : Lepiej zjedz Snickersa.

A ty idź do stolarza, bo ci się klepki poluzowały...

**Comment by hawkeye116477** [comment]
> invert(180) bo 1 pewnie od Chrome 86 i Firefox 82 działa.

To cię zaskoczę, bo działa nawet i w Bazyliszku/FF 52.

**Comment by krystian3w** [comment]
Ale nie z ciemnym motywem i hugo blokuje jasny motyw.

**Comment by AroKol78** [comment]
adguard-home w menu zawsze dobrze - niezależnie od motywu, a na stronie zawsze black

**Comment by hawkeye116477** [comment]
![2020-11-11_18-29](https://user-images.githubusercontent.com/19818572/98843939-e949b100-244b-11eb-999a-9316f1c38f6e.png)

Tak chyba powinno być nieco mniej scrollowania od razu bez wyboru mirroru. A te menu wyboru mirroru usuniemy :smile:

**Comment by krystian3w** [comment]
To jeszcze czy hugo może być mniej nachalny i dać szansę ręcznego włączania jasnego motywu w Windows 10?

**Comment by xxcriticxx** [comment]
cc @MajkiIT 

@zaba-monika ostatnie ostrzezenie nastepnego juz nie bedzie

**Comment by hawkeye116477** [comment]
> To jeszcze czy hugo może być mniej nachalny

Hugo to generator, on nic tu nie ma do tego, za to odpowiada skrypt https://github.com/coliff/dark-mode-switch z drobnymi modyfikacjami, ale ok, poprawimy :smile:

**Comment by zaba-monika** [comment]
> xxcriticxx : @zaba-monika ostatnie ostrzezenie nastepnego juz nie bedzie

Chyba sobie żarty stroisz (albo po prostu trolujesz i bronisz kolegę), typ do mnie wyskoczył z głupim tekstem, to mu takim samym tekstem odpisałem, więc nie wiem w ogóle o co tobie chodzi, gdybyś mógł wyjasnić o co tobie chodzi to łatwiej byłoby ciebie zrozumieć, bo tak to nikt nie rozumie o co ci w ogóle chodzi...

**Comment by xxcriticxx** [comment]
@zaba-monika no rude, offensive, or hateful comments **PLEASE**

**Comment by zaba-monika** [comment]
xxcritcxx stop trolling please, the only offensive are you and your friend hawkeye, Im only defending...please stop harassing me on github , because you are violating github conduct of code...

**Comment by hawkeye116477** [comment]
@xxcriticxx Do niego nic nie trafia, lepiej podjąć natychmiastowe środki moderacyjne albo olać.

**Comment by zaba-monika** [comment]
Jestem atakowany i trolowany przez użytkowników @hawkeye116477 i @xxcriticxx, zaczepiają mnie i wypisują na mnie różne bzdury...a teraz chcą mnie bez powodu zbanować...

**Comment by AroKol78** [comment]
adguard-home icons 👍

"LINKI ALTERNATYWNE" zredukowane , submenu działa w porządku
 - bez wpływu ilość na scrollowania - dla mnie ok ( "taki design wg Google.")

**Comment by AroKol78** [comment]
drobna sugestia - zapamiętywanie wyboru w menu, tak jak  jasny/ciemny tryb.

**Comment by zaba-monika** [comment]
Nom, takie cuś jak [TU](https://polishannoyancefilters.netlify.app/issues/)

**Comment by krystian3w** [comment]
Tam nie zapamiętuje a raczej skrypt wymusza ciemny/jasny.

**Comment by AroKol78** [comment]
"TU" potwierdzam błąd
> zapamiętywanie wyboru w menu

mam jeden adblocer i chciałbym, żeby lista zapamiętała wybór, na razie za każdym razem muszę wybierać

**Comment by krystian3w** [comment]
Teoretycznie obejściem na zapamiętywanie może być link:

[`https://majkiit.github.io/polish-ads-filter/?adblocker=uBO`](https://majkiit.github.io/polish-ads-filter/?adblocker=uBO)

Gorzej jak chodzi by nie używać tego jako zakładka a z paluszka wpisujesz i wybierasz adres z brzegu.

**Comment by AroKol78** [comment]
> by nie używać tego jako zakładka

?

**Comment by krystian3w** [comment]
No że dodajesz do na pasek zakładek zamiast w pasek adresu klepać:

`adblocker=uBO`, bo na 99% będziesz mieć wersje bez parametru też jako podpowiedź również (mnie denerwują te co się zapisują jako kotwica HTML).

**Comment by AroKol78** [comment]
leci już do "Bookmarks ToolBar"
proste a skuteczne - dzięki @krystian3w 🥇

**Comment by AroKol78** [comment]
"TU" wybór motywu znów działa

**Comment by hawkeye116477** [comment]
@krystian3w Odnośnie trybu ciemnego, za dużo kombinowałeś, naprawione => https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters.netlify.com/commit/07d0ac8b5aac05d36fd75adb4b460fadb7a6a3b9 :smile:

**Comment by AroKol78** [comment]
nie zauważyłem - nie wgryzam się za mocno w URL (aby początek się zgadzał, potem to przeważnie czarna magia)

**Comment by krystian3w** [comment]
Podobno w przyszłości będzie widać tylko `majkiit.github.io` nawet bez nazwy katalogu...

**Comment by zaba-monika** [comment]
Chłopaki, nie wiem co wy tam narobiliście ale padłą wam strona:
- https://polishannoyancefilters.netlify.app/otherfiltersforadblockers/
Ale np. główna działa.:
- https://polishannoyancefilters.netlify.app/

**Comment by AroKol78** [comment]
>Chyba padła strona admina z polecanymi listami:
>-    https://polishannoyancefilters.netlify.app/otherfiltersforadblockers/ ==> https://majkiit.github.io/polish-ads-filter/

potwierdzam

https://polishannoyancefilters.netlify.app/otherfiltersforadblockers/
teraz jest na
https://polishannoyancefilters.netlify.app/issues/

**Comment by krystian3w** [comment]
W kodzie na GH strony EI można zobaczyć, że Hawkeye uruchomił obiecane przekierowanie na tabelę (redirect 302).

Więc to wasze przekierowanie nie ma racji bytu jako błąd, po prostu tabela się zestarzała i korzystniej przekierować ruch na aktualizowaną u Majkiego, dodatkowo działa ona lepiej z uBO 1.30+ (nie trzeba ręcznie kopiować adresów list).
