### ISSUE TITLE
ogladajanime.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17598]
![Screenshot_1](https://user-images.githubusercontent.com/21177361/98872238-83beea00-2476-11eb-987c-6d58287766de.png)

**Comment by gzenio22** [comment]
@xxcriticxx z jakiej racji zamknołeś temat skoro problem nadal występuje?

**Comment by AroKol78** [comment]
double - https://github.com/MajkiIT/polish-ads-filter/issues/17599

**Comment by gzenio22** [comment]
@AroKol78 racja sorki
