### ISSUE TITLE
ogladajanime.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17599]
RODO

![Screenshot_1](https://user-images.githubusercontent.com/21177361/98872347-ad781100-2476-11eb-84a7-bcdbf29bca54.png)

**Comment by gzenio22** [comment]
@MajkiIT zamknołeś temat a rodo dalej sie pokazuje

**Comment by zaba-monika** [comment]
@gzenio22 naprawione, tylko musisz zaktualizować listę ciasteczkową.
