### ISSUE TITLE
epodreczniki.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17608]
![capture_048_12-11-2020_13-55-08](https://user-images.githubusercontent.com/72980128/98942677-ae4c8980-24ee-11eb-865f-2b4e73b4a525.png)

**Comment by bug-rules** [comment]
Ale to nie jest komunikat cookies/RODO.

Polityki EI też nie spełnia - bo informacyjny.

**Comment by zaba-monika** [comment]
Masz rację, wśród setek komunikatów ciasteczkowych łatwo o niedopatrzenie.
