### ISSUE TITLE
seckin.com.tr incorrect blocking

### ISSUE THREAD

**Issue by Sergey-Lyapin** [MajkiIT/polish-ads-filter#17617]
The rule `###ad` blocks "name" section in this site's registration form.

https://www.seckin.com.tr/loginregister

The original issue: https://github.com/AdguardTeam/AdguardFilters/issues/67401

**Comment by MajkiIT** [comment]
@Sergey-Lyapin I fixed it. Please check.

**Comment by Sergey-Lyapin** [comment]
@MajkiIT The name element is visible now, thank you.
