### ISSUE TITLE
napiprojekt.pl

### ISSUE THREAD

**Issue by mysteriously** [MajkiIT/polish-ads-filter#17611]
### Link bezpośredni 
https://www.napiprojekt.pl/napisy-szukaj

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
1. Wejść na https://www.napiprojekt.pl/napisy-szukaj
2. Wpisać nazwę filmu
3. Kliknąć w dowolny film
4. Uwaga! Reklama pojawia się tylko raz na jakiś czas (chyba raz dziennie dla danego IP). Jesteśmy przekierowani z napiprojekt do www.hellozdrowie.pl w tej samej karcie

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Chrome x64 Version 86.0.4240.198 (Official Build) (64-bit)
**Rozszerzenia i skrypty:** uBlock Origin

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Fanboy’s Annoyance
4. Polskie Filtry Elementów Irytujących 
5. I don't care about cookies

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by zaba-monika** [comment]
Duplikat istniejącego już zgłoszenia: https://github.com/MajkiIT/polish-ads-filter/issues/17418, nastęnym razem użyj funkcji "szukaj" zamiast zakładać bezmyślnie duplikaty, no chyba, że jednak szukałeś ale nie zauważyłeś (co zdarza się każdemu).

**Comment by xxcriticxx** [comment]
please see #17418

**Comment by mysteriously** [comment]
> Duplikat istniejącego już zgłoszenia: #17418, następnym razem bądź łaskaw użyć funkcji "szukaj" zamiast zakładać bezmyślnie duplikaty, no chyba, że zapomniałeś albo szukałeś ale jakimś cudem przeoczyłeś istniejące już zgłoszenie (co każdemu się czasem zdarza).

Idź się przewietrz
