### ISSUE TITLE
gamefinity.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17613]
![Zrzut ekranu z 2020-11-12 19-05-50](https://user-images.githubusercontent.com/36385327/98978376-2aa89200-251a-11eb-932b-eb4f775c28ee.png)
![Zrzut ekranu z 2020-11-12 19-07-03](https://user-images.githubusercontent.com/36385327/98978471-50ce3200-251a-11eb-8eab-21efae4a2008.png)

**Comment by krystian3w** [comment]
@hawkeye116477  znowu jakiś błąd bieda PC, u mnie uBO poprawnie ukrywa zablokowane sieciowo grafiki.

**Comment by krystian3w** [comment]
@xMaap nie odznaczaj w uBO:

<h3>

- [x] Ukrywaj symbole zastępcze zablokowanych elementów

</h3>

to nie poprawia wydajności w żadnym stopniu.
