### ISSUE TITLE
telewizyjka.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1761]
Cookies fix
```
###wyswietlcookie
```

**Comment by xxcriticxx** [comment]
@FadeMind filtry cookies posiadasz?

**Comment by FadeMind** [comment]
@xxcriticxx używam https://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/

**Comment by xxcriticxx** [comment]
@FadeMind ja z lista @MajkiIT zadnych cookies na tej stronie niema
