### ISSUE TITLE
twitch.tv

### ISSUE THREAD

**Issue by MSIKT4AV** [MajkiIT/polish-ads-filter#17628]
Od pewnego czasu filtry przestały blokować reklamę video w playerze. Po wejściu na dowolny stream odpala się 10 sekundowa reklama i później co różną liczbę minut (to już zależy od danego streamera). Na reddit są jakieś rozwiązania/filtry, ale subskrybowanie jakiegoś pliku js od nie wiadomo kogo jest ryzykowne.

**Comment by zaba-monika** [comment]
Hej nie siedzę zbytnio w temacie Twitch, ale z tego co się ogólnie orientuję w kwestii Twitch to te reklamy sa ciągle naprawiane na bieżąco w uBlock origin w tym wątku https://github.com/uBlockOrigin/uAssets/issues/5184, ale jak ledwo co zostaną one naprawione, to ci z Twitcha po chwili zmieniają coś w kodzie strony i znowu reklamy wyskoczą, i potem developrzery uBO znowu naprawią a Twitch po chwili znowu obejdzie filtry, taka zabawa w kota i myszkę pomiędzy twórcami adblocków/filtrów a twórcami Twitch.

Podobna zabawa trwa z Facebookiem: https://github.com/uBlockOrigin/uAssets/issues/3367

**Comment by gzenio22** [comment]
na facebooka jest patent sprawdzal ktos metode dzialania wtyczki socjalfixer?

**Comment by krystian3w** [comment]
Facebooka wystarczy blokować z pomocą filtrów własnych, mój pomysł z ścieżką/układem div-ów działa już z 3 miesiąc.

Niby też Facebook porządnie wygasił niebieski wygląd.

**Comment by MajkiIT** [comment]
@krystian3w sprawdź to https://oldlayout.com/

**Comment by krystian3w** [comment]
Na moich 3 kontach nie działa już (dwa mam do testowania reklam i postów "sugestie dla ciebie").

Nie będę co 2 tygodnie konta zakładać jak wymuszą nowy layout, mniej-więcej 14 dni można mieć stary layout na świeżym koncie i wymuszają nowy.

**Comment by MajkiIT** [comment]
@krystian3w u mnie na FF jest ok.

**Comment by krystian3w** [comment]
Moje konta nie podlegają zmianom na stary.

Jak autor zrobił restylowanie jak kiedyś robiło się w Stylish (teraz Stylus) to raczej takie średnie.

**Comment by gzenio22** [comment]
@MajkiIT Bardziej chodzilo mi o tą wtyczke : https://socialfixer.com/ 

Notabene jest to tego samego autora i w opcjach jest ukrywanie sponsorowanych

**Comment by zaba-monika** [comment]
> https://github.com/MajkiIT/polish-ads-filter/discussions/17449#discussioncomment-114218 : hawkeye116477 : 
A dzisiaj jest coś co zainteresuje @zaba-monika - **Dzień Odpoczynku dla Zszarganych Nerwów.**
>> xxcriticxx : na to jest clonazepam

Posłuchaj trollu (hawkeye116477):
- po pierwsze nie obsmarowywuj kogoś, gdy nie dajesz mu możliwości obronienia się i zripostowania na twoje wypociny, bo to jak kopanie leżącego, nie posiadasz jakiegokolwiek honoru:
![blok](https://user-images.githubusercontent.com/72980128/99354731-48be1b80-28a7-11eb-8955-10cd6c45790d.png)
- dopiero co kilka dni temu razem ze swoim przydupasem xxcriticxx już raz mnie prowokowaliście w [TYM WĄTKU](https://github.com/MajkiIT/polish-ads-filter/issues/17587#issuecomment-725452043) żeby tylko mieć pretekst do obwinienia mnie o cokolowiek i zbanowania mnie, ale na spokojnie zripostowałam was, a admin przejrzał na oczy, że mnie zaczepiacie i prowokujecie + że ja tu dużo pomagam, więc wasze marzenie o bezpodstawnym zbanowaniu mnie się nie ziściło, bo przynajmniej admin miał trochę rozsądku, i tym razem też tak będzie, bo znowu spokojnie ripstuję wasze prowokacje + dużo pomagam, więc admin tym razem też nie wysłucha waszych wypocin w moją stronę
- po drugie jak to zwykle u was, hipokryzja jak zawsze, bo wytykacie komuś zszargane nerwy, po tym gdy sami wpierw te nerwy komuś próbujecie zszargać + skoro komuś bez powodu nerwy próbujecie zszargać i atakujecie to świadczy też o tym, że sami macie zszargane...a ten dzień wymyślono właśnie przez takich trolli jak ty i twój przydupas xxcritcicxx, którzy próbują szargać innym nerwy, więc rzeczywiście czasem mi się przyda odpoczynek od takich jak wy
- 
> xxcriticxx : na to jest clonazepam

jak wyżej: to jest również na takich nadpobudliwych agresywnych trolli jak wy, którzy próbują szargać innym nerwy swoimi prowokacjami / zaczepkami o Snickersach i clonazepamie, a sami mają zszargane skoro bez powodu próbują zszargać je innym, o czym oczywiście hipokryci nie wspomną...

- na koniec: takich prób zszargania mi nerwów oraz prowokacji / trolowania / zaczepiania bez powodu z waszej strony było już wiele, na tym repo i na repo EI, więc albo się w końcu uspokoicie, albo trzeba będzie was wysłać do psychiatry, żeby wyleczyć wasze trolowanie i hipokryzję, chociaż w sumie niektórzy to powinni się leczyć raczej na nogi bo na głowę już za późno...ewentualnie można na was wezwać hycla

- jesteście doskonałymi przykładami trolli internetowych, a troll to nikt inny jak psychopata o zszarganych nerwach, pełen hipokryzji, który chce innym zszargać nerwy bo mu (trollowi) w życiu się nie ułożyło...

- na koniec diagnozy którą wam postawiłem, ulotka lekarska promująca leki dla was:

![indeks](https://user-images.githubusercontent.com/72980128/99357699-a30dab00-28ac-11eb-97b8-b76967a96a65.jpg) ![bbbbb](https://user-images.githubusercontent.com/72980128/99357781-cafd0e80-28ac-11eb-8500-4ab4de3e4ec6.jpg) ![tttt](https://user-images.githubusercontent.com/72980128/99357915-0bf52300-28ad-11eb-8c10-6052d9159bbe.jpg)

**Comment by zaba-monika** [comment]
> krystian3w : https://github.com/MajkiIT/polish-ads-filter/issues/17587#issuecomment-727575474 : W kodzie na GH strony EI można zobaczyć, że Hawkeye uruchomił obiecane przekierowanie na tabelę Majkiego (redirect 302).
> 
> Więc to wasze przekierowanie nie ma racji bytu jako błąd, po prostu tabela się zestarzała i korzystniej przekierować ruch na aktualizowaną u Majkiego, dodatkowo działa ona lepiej z uBO 1.30+ (nie trzeba ręcznie kopiować adresów list).

Muszę sprostować twój komentarz, bo nigdzie nie twierdziłam, że błędem jest samo przekierowanie, jedynie napisałam, ża padła domena `majkiit.github.io` i tylko o to mi chodziło.

**Comment by zaba-monika** [comment]
Nie działa formularz: https://polishannoyancefilters.netlify.app/issues/, zawsze mi działał, a dzisiaj kilka razy próbowałam z 2 różnych przeglądarek i nie da rady, gdy wciskam "wyślij"  za każdym pisze razem że wysłane, ale zgłoszenie nie pojawia się.

**Comment by krystian3w** [comment]
Pewnie awaria na Google forms, ostatnio często się wywala, musisz czekać aż @hawkeye116477  ustali czy nie trafiłeś na spam listę (jak innym działa).

Jak zgłoszenia nie trafiły w `dev/null` to niby będzie dało się je ręcznie wypchać z Google forms do GH.

**Comment by hawkeye116477** [comment]
Wszystko działa, może po prostu wujek dodał gargulca na czarną listę...

**Comment by zaba-monika** [comment]
No coś tak właśnie podejrzewałam / domyslałam się, że to jakiś anty-spam mnie wycina...ale:
- nie chciało mi się już skakać po kolejnych proxy/VPN żeby to sprawdzić
- wydawało mi się, że na tym samym proxy wcześniej zgłaszałam kilka dni temu i mnie nie wycinało...(chociaż dokładnie nie pamiętam czy zmieniałam od ostatniego udanego zgłoszenia, proxy/VPN, być może zmieniałam tylko nie pamiętam)

Więc po prostu prościej było mi się zwyczajnie zapytać, więc teraz ponowię próby utworzenia zgłoszenia z innych proxy/VPN i zobaczymy czy przyedzie, w razie gdyby problem nie ustąpił to dam znać...

**Comment by zaba-monika** [comment]
Ty bez jaj, wysłałam zgłoszenia z 3 kolejnych IP, czyli razem już z 6 różnych IP i dalej nic tworzy zgłoszenia...

**Comment by zaba-monika** [comment]
DODANE 1:
Ty bez jaj, wysłałam dziś zgłoszenia z 3 kolejnych IP (czyli tak jak wczoraj), czyli razem już z 6 różnych IP i dalej nie tworzy zgłoszenia...

DODANE 2: dobra w końcu poszło na 9 IP z rzędu... masakra...oczywiście pomyłka z etykietą przez:
- ten mechanizm anty-spamowy i niekończące się próby wysłania zgłoszenia
- oraz formularz który przy nowym zgłoszeniu wymusza odznaczenie etykiety i zaznaczenie ponownie -
zaznaczyłam omyłkowo dodatkową inną etykietę oprócz już zaznaczonej wcześniej poprawnej, to oczywiście doszło tylko z tą jedną niepotrzebną, pomimo, że była zazanaczona też druga prawidłowa - masakra...
- oczywiście doszło akurat te zgłoszenie w którym się pomyliłam z etykietą, a w 8 poprzednich się nie pomyliłam ale wtedy oczywisćie żadne nie doszło, masakara...los jest złośliwym skur...

**Comment by zaba-monika** [comment]
Co za badziewie - jedno zgłoszenie doszło, a kolejne ( z tego samego IP) już nie chcą...weźcie to naprawcie..

**Comment by zaba-monika** [comment]
To co nie doszło...doszło ale z jakimś opóźnieniem... nie wiadomo czy się śmiać czy płakać

**Comment by zaba-monika** [comment]
Dobra hu. z tym, próbuję kolejne zgłoszenie ciekawe jakie teraz będą jaja...

**Comment by zaba-monika** [comment]
Niesamowite, jakbym wyczuła, że znowu coś się zesra...wypełniłam zgłoszenie i jestem w ostatnim ktroku 4/4 przeciągałam zrzut ekranu do przeglądarki i nie najechałam odpowiednio dokładnie na obrys na który trzeba trafić i w miesjce strony z formularzem załadowała się strona ze zrzutem ekranu, cofnęłam z nadzieją, że cofnie mnie do kroku 4/4 ale gdzie tam, anulowało i wyczyściło całe zgłoszenie i formularz od nowa krok 1/4 czy ja śnię czy to się dzieje naprawdę?

**Comment by zaba-monika** [comment]
Dobra zaczynam to zgłoszenie od nowa, zobaczymy co się teraz stanie...

**Comment by zaba-monika** [comment]
Uwaga zamierzam wcisnać przycisk WYŚLIJ ! 3..2...1..

**Comment by zaba-monika** [comment]
No w końcu chociaż te poszło normalnie za pierwszym razem, a nie rodziło się w bólach...

**Comment by zaba-monika** [comment]
Co za tempo, średnio jedno zgłoszenie na kilka godzin, bo już od wczoraj próbowałam je zgłosić...

**Comment by zaba-monika** [comment]
Relacja zakończona, gargul dojechał do mety po kilkunastu godzinach...!!

**Comment by zaba-monika** [comment]
Ile pownnio zająć zgłoszenie 3 zgłoszeń? 15 minut a nie 15 godzin...

**Comment by zaba-monika** [comment]
- czytając powyższy komentarz, to wynika z tego, że ten formularz nadaje się co najwyżej do dupy...
- za każdym razem gdy chcę jakiegoś dnia wysłać 2-3 zgłoszenia to zaczyna się jakaś parodia...
a) a to zgłoszenie nie dojdzie w ogóle
b) a to zgłoszenie dojdzie zduplikowane (dwa takie asme zgłoszenia)
c) a to dojdzie, ale z opóźnieniem
d) a to w zgłoszeniu brakuje etykiety pomimo, że była zaznaczona przy wysyłaniu

**Comment by AroKol78** [comment]
**techsetter.pl** pisze tu bo ...
zaakceptowałem ciastka - potem już niema "adblock detect"

**Comment by krystian3w** [comment]
Akceptacja paska cookies nie powoduje znikania anty-adblock, mylisz efekt odświeżenia, bo anty-adblock jest zapisywany w cookies że się wyświetlił:

```
    aiADB:bdaeabeb
```

**Comment by AroKol78** [comment]
wiem, efekt brak "adblock detect"

**Comment by krystian3w** [comment]
To nie pisz, że mamy dodać ręczną akceptację w Polska Zogda Ciasteczkowa:

> zaakceptowałem ciastka - potem już niema

**Comment by AroKol78** [comment]
ja nie używam "Polska Zogda Ciasteczkowa" ani tym podobnych związanych z ciastkami
chciałem tylko pomuc zab...

**Comment by krystian3w** [comment]
No to nie bardzo pomogłeś, bo uBlock-user zlikwidował kilkanaście tygodni temu `set-cookie.js` by móc użyć `aiADB:bdaeabeb`.

**Comment by zaba-monika** [comment]
> Musisz czekać aż @olegwukr naprawi techsetter.pl.

Po prostu przez weekend nie miałam czasu się zająć tym anty-adblockiem, dziś zajrzę do niego.

**Comment by zaba-monika** [comment]
@blocker999 z tą etykietą to wszystko przez ten szwankujący formularz https://github.com/MajkiIT/polish-ads-filter/issues/17628#issuecomment-731015197

**Comment by gzenio22** [comment]
@blocker999  zaba jak cos oznacza sie bez spacji po małpce

**Comment by zaba-monika** [comment]
@gzenio22 Jak bym nie wiedziała...już to tłumaczyłam: https://github.com/MajkiIT/polish-ads-filter/issues/17717#issuecomment-730196550.
