### ISSUE TITLE
filmy na wp

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1762]
@F4z te domain so blokowane na dns host jak film na wp.pl sie odpala 

 `wp.hit.gemius.pl` 
 `rek.www.wp.pl` 
 `adv.wp.pl` 
 `static.criteo.net`

**Comment by F4z** [comment]
@xxcriticxx nie bardzo rozumiem co mam z tym zrobić.
Możesz dokładniej wyjaśnić o co chodzi?

**Comment by xxcriticxx** [comment]
@F4z  kiedys testowaliśmy dns umnie pamiętasz?

**Comment by FadeMind** [comment]
@xxcriticxx 
https://github.com/StevenBlack/hosts
https://github.com/FadeMind/hosts.extras

FYI

**Comment by F4z** [comment]
@xxcriticxx pamiętam https://github.com/MajkiIT/polish-ads-filter/issues/1495

**Comment by xxcriticxx** [comment]
@FadeMind `https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt`

@F4z dokladnie

**Comment by FadeMind** [comment]
@xxcriticxx zamiast `127.0.0.1` lepiej używać `0.0.0.0`

https://gist.githubusercontent.com/FadeMind/388b942bb7f31509b26a95f5cabe318b/raw/16923c729232b4362240fb54e9eb34e50ea754ee/hosts

Dodatkowo usunąłem niepotrzebne spacje i tabulatory. 
[pl.hosts.txt](https://github.com/MajkiIT/polish-ads-filter/files/672299/pl.hosts.txt)

**Comment by xxcriticxx** [comment]
@FadeMind thank you

**Comment by xxcriticxx** [comment]
@F4z jak moge wyjatki zrobic w ublock?

**Comment by F4z** [comment]
@xxcriticxx ale chcesz dodać strony do wyjątków, czy reguły?

**Comment by xxcriticxx** [comment]
strony tylko wp wkoncu zrobilem sprawdzalo domenu i cookie teraz juz filmy dzialaja

**Comment by F4z** [comment]
To znaczy, że już sobie poradziłeś?
Jak chcesz dodać całą stronę do wyjątków, to dodajesz ją w zakładce "Wyjątki"/"Whitelist", tutaj możesz przeczytać na ten temat - https://github.com/gorhill/uBlock/wiki/Dashboard:-Whitelist
https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site

**Comment by xxcriticxx** [comment]
z filmai tak ale ze dodalem tych kilka stron to reklamy sie pojawily zaraz przekasuje zobacze czy cookie wystarczy na adblock

**Comment by MajkiIT** [comment]
Ja na Mikrotik rzucę się na:
http://stopad.generate.club

**Comment by xxcriticxx** [comment]
@MajkiIT tlumaczenie za free plz?

**Comment by MajkiIT** [comment]
@xxcriticxx to rozwiązanie dla routerów Mikrotik. Wrzucasz na router skrypt a on pobiera wybrane przez ciebie listy i dodaje automatycznie reguły blokujące wybrane urle.

**Comment by xxcriticxx** [comment]
@MajkiIT https://github.com/pi-hole/pi-hole

**Comment by F4z** [comment]
@MajkiIT jeśli mam włączoną listę AAK, to czasami przez tę regułę - `@@/:\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(.{0,15}[&!*;@\$)[\]:%].*|(?!cap|vad|display)[a-zA-Z0-9\W_]{1,10})\.(js|html|xml|jpg|gif|png)/`

widzę reklamy na niektórych stronach wp, na przykład tutaj - `http://komorkomania.pl/34041,nokia-d1c-smartfon-z-androidem`
Te reklamy nie pojawiają się zawsze, zazwyczaj są przy pierwszym wejściu na stronę.

![image](https://cloud.githubusercontent.com/assets/11742596/21509518/1ac13776-cc8a-11e6-9892-70c9548c62a4.png)

Mógłbyś sprawdzić, czy jak wyłączysz listę AAK i usuniesz regułę, o której wspomniałem wcześniej, ale dodasz to:

`@@/^(http|https):\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(.{0,15}[&!*;@\$)[\]:%].*|(?!gaf|cap|vad|display|dis3rd)[a-zA-Z0-9\W_]{0,10})\.(js|html|xml|jpg|gif|png)|^(http|https):\/\/rek\.www\.wp\.pl\/gaf\.js$|^(http|https):\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/[a-zA-Z0-9=]{1,180}=$|^(http|https):\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(?!gaf|cap|vad|display|dis3rd)[a-zA-Z0-9,_]{0,180}\.(js|html|xml|jpg|gif|png)|^(http|https):\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(?!gaf|cap|vad|display|pliki)[a-zA-Z0-9]{15,50}$/`

to czy działają filmy i nie wyświetlają się reklamy na stronach wp?
