### ISSUE TITLE
AdGuard 

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17629]
Hej

Kilkoro z was mnie tu zna w sumie zgłaszam wam reklamy chyba już od lat jednak ostatnimi czasy Ublock origin zaczął mnie mocno irytować zauważyłem u siebie fakt ze często na przykładzie sportowefakty od WP u mnie mimo że razem z bodaj @krystian3w ostatnio dobieraliśmy listę moich filtrów reklamy np na tej stronie nie są blokowane mimo ze na głównej WP już tak.

Zastanawiam się co jest tego przyczyną bo wczoraj dla testu zainstalowałem sobie apke tą testową 3 dniową adguarda i ona już mi te reklamy na całym WP blokuje bez pierdnięcia jedyne na razie jedyne co musiałem dorzucić od nas stricte to filtry rodo 

Nosze się kurde z zakupem licencji adguarda nie wiem jak to do końca działa ale czy ta apka wykonuje skrypty list po stronie serwera i wysyla do mnie gotowy efekt ze to działa lepiej czy coś ja mam spaprane w ublocku a w adguardzie działa to poprawnie?

Zgaduje ze przez takie kwiatki tylko was irytuje bo zgłaszam problemy których po waszej stronie nie ma i zaczyna was to drażnić bądź drażni od dłuższego czasu 

Moje pytanie to: Co o tym sądzicie czy błąd jest po moiej stronie jeśli tak to jak to naprawić? czy Ublock sobie nie radzi i również jak to naprawić? Pozdrawiam i przepraszam ze tak sie rozpisałem...

**Comment by zaba-monika** [comment]
- te reklamy na `sportowefakty.wp.pl` zgłaszałam już prawie miesiąc temu: https://github.com/MajkiIT/polish-ads-filter/issues/17364

- nie tylko na `sportowefakty.wp.pl` są reklamy, bo są też na kilkunastu innych domenach WP i je również zgłaszałam na POL repo i AdGuard repo, ale nie zostały do tej pory naprawione: https://github.com/MajkiIT/polish-ads-filter/issues/13818#issuecomment-711344072
- o ile się orientuję zazwyczaj MajkiIT czeka aż najpierw naprawi AdamWr w AdGuardzie jakimiś filtrami typu `+js` i wtedy przekopiowuje do POL listy, ale w AdGuardzie te reklamy póki co zostały naprawione skryptami kompatybilnymi tylko z AdGuardem i niekompatybilnymi z uBO i AdamWr powiedział, że jak znajdzie rozwiązanie kompatybilne z uBO to doda: https://github.com/AdguardTeam/AdguardFilters/issues/65427#issuecomment-711339264
- póki co tego rozwiązania pod uBO AdamWr jeszcze nie znalazł, być może nie ma czasu i jest zajęty / nie chce mu się / nie umie znaleźć rozwiązania albo po prostu wolą nie promować konkurencji w postaci uBO i wolą zarabiać na AdGuard, podobnie jak MajkiIT nie chce promować konkurencji EasyList Polish bo też ma u siebie przycisk "donate"...
- w takim razie skoro juz prawie miesiąc i te reklamy na kilkunastu stronach WP nie są naprawione pod uBO ani na POL liście, ani na AdGuard liście, to trzeba to zgłosić do uAssets

**Comment by krystian3w** [comment]
Jak ci nie przeszkadza brak trybu Firewall, mniej inteligenty element picker do blokowania ręcznego to możesz zostać na AdGuard AdBlocker.

**Comment by gzenio22** [comment]
@krystian3w naczy bardziej mi chodzi o to zeby wam nie robic dublujących sie albo nie właściwych zgłoszeń bo wiem ze tym męcze

**Comment by krystian3w** [comment]
Myślę, że problem z reklamami WP raczej będzie ciągle w uBO aż MajkiIT i Oleg nie opanują ręcznego pisania skryptletów:

https://github.com/gorhill/uBlock/wiki/Resources-Library

Nie zanosi się by szybko AdGuard wyrównał zachowanie `set-constant`, by było identyczne jak z uBO, by sobie podbierać rozwiązania z AdGuard Base co 2 tygodnie.

**Comment by zaba-monika** [comment]
- w obecnej chwili na większości stron WP reklamy są ubite za pomocą:
 `##+js(set, Object.prototype.advViewability, undefined)`

- przed chwilą sprawdziłem i ten filtr działa też na `sportowefakty.wp.pl` i również tych stronach WP https://github.com/MajkiIT/polish-ads-filter/issues/13818#issuecomment-711344072  (nie sprawdzałem na wszystkich, tylko na kilku) , na `sportowefakty.wp.pl` na głównej reklamy ubite, w artykułach też, co najwyżej w artykułach może zostać kilka pustych szarych kontenerów po reklamach

- więc nie wiem dlaczego do tej pory ten filtr nie został dodany do wszystkich stron WP, może ktoś to przeoczył, z tego co wiem to ten filtr się ponoć zdezaktualizował / przestał działać jakiś czas temu: https://github.com/MajkiIT/polish-ads-filter/issues/13818#issuecomment-586639734 + https://github.com/MajkiIT/polish-ads-filter/issues/13818#issuecomment-678713306 , ale jak widać nadal działa, a chyba przestał działać raczej z powodu błędu w uBO z `set-constant` o którym nikt przez służszy czas nie wiedział: https://github.com/MajkiIT/polish-ads-filter/issues/13818#issuecomment-710031789, a po naprawieniu tego błędu w uBO, reguła jak widać znowu działa:

**Comment by zaba-monika** [comment]
@MajkiIT, jak w komentarzu wyżej

**Comment by zaba-monika** [comment]
@MajkiIT

> zaba-monika : co najwyżej w artykułach może zostać kilka pustych szarych kontenerów po reklamach

`sportowefakty.wp.pl##.section__separator`

![capture_071_14-11-2020_19-23-24](https://user-images.githubusercontent.com/72980128/99154275-db479a80-26ae-11eb-82aa-64b92dd20379.png)

**Comment by zaba-monika** [comment]
@gzenio22 naprawione, zaktualizuj polskie filtry w uBO i sprawdź, powinno już nie być reklam, to wtedy można zamknąć zgłoszenie.

**Comment by zaba-monika** [comment]
@MajkiIT https://github.com/MajkiIT/polish-ads-filter/commit/06d2dba2bae3c1a6cbd5f96396e61532b741f93f#r44192375

**Comment by gzenio22** [comment]
faktycznie już działa :) zostawie to jeszcze bo coś tu @zaba monika jeszcze oznacza :P

**Comment by zaba-monika** [comment]
@gzenio22 możesz już zamknąć

**Comment by zaba-monika** [comment]
Albo jeszcze lepiej nie zamkykaj.

**Comment by gzenio22** [comment]
wiecie co? skorzystam z okazji ze to jeszcze jest otwarte i zapytam moze to pytanie glupie ale czy adguard blokuje tez reklamy wyskakujace w okienku np tą reklame z GG? chodzi mi o reklame z programu na desktopie nie te ze strony komunikatora online

**Comment by zaba-monika** [comment]
Tak, [AdGuard pod Windows](https://adguard.com/pl/adguard-windows/overview.html) blokuje wszystkie rodzaje reklam, we wszystkich programach, a czy blokuje akurat tę konkretną z GG, powinien, ale jako, że nie korzystam z AG pod Windows to nie potwierdzę na 100%.

**Comment by gzenio22** [comment]
no właś nie tej z GG nie blokuje dlatego tu napisalem jak cos wes zglos to w odpowiednie miejsce :)

**Comment by krystian3w** [comment]
Z obcych apek musisz ręcznie po angielsku tutaj:

https://github.com/AdguardTeam/AdguardFilters/issues/new/

A tu przykład zgłoszenia źle bittorrent z komunikatem GDPR w aplikacji: https://github.com/AdguardTeam/AdguardFilters/issues/62127

**Comment by gzenio22** [comment]
maine ang leży i kwiczy Xd rozumiem co ktos pisze mowi sam sie wole nie odzywac

**Comment by krystian3w** [comment]
Nie, raczej nikt nie jest chętny na instalacje GG i opisanie gdzie i jakie reklamy tam wyciekają.

**Comment by gzenio22** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/21177361/99187599-ddb1ff00-2757-11eb-901a-2cf8550be2ca.png)
![Screenshot_1](https://user-images.githubusercontent.com/21177361/99187602-e3a7e000-2757-11eb-8bcb-e4cfff0d0e60.png)

**Comment by zaba-monika** [comment]
@ gzenio22 do zrobienia zgłoszenia nie trzeba super angielskiego, wystarczy średni taki z [TRANSLATORA](https://translate.google.com/?sl=auto&tl=en&text=no%20wi%C4%99c%20jestem%20gzenio22%20%3A\)%20i%20chcia%C5%82em%20powiedzie%C4%87%20...&op=translate)

**Comment by zaba-monika** [comment]
@MajkiIT  

### 1
Do [TEJ REGUŁY](https://github.com/MajkiIT/polish-ads-filter/commit/06d2dba2bae3c1a6cbd5f96396e61532b741f93f#diff-d827a1b7316ce797a25db7dd2fd861d32c02e0d491fb392c28675cb73d49a311R201) jeszcze trzeba dodać te 2 strony: `tv.wp.pl,horoskop.wp.pl` bo sypie reklamami ( https://github.com/MajkiIT/polish-ads-filter/issues/17382 + https://github.com/MajkiIT/polish-ads-filter/issues/17378 ):
https://github.com/MajkiIT/polish-ads-filter/blob/e23619eae81980df08b2ce28485a8a530bba330c/polish-adblock-filters/adblock_ublock.txt#L201


### 2

Na `tv.wp.pl` ( https://github.com/MajkiIT/polish-ads-filter/issues/17380 ) trzeba dodać coś na puste szare kontenery po reklamach, 
niestety nie da się takim prostym filtrem jak w `sportowefakty.wp.pl` ( https://github.com/MajkiIT/polish-ads-filter/issues/17364#issuecomment-727247405 ), bo są losowe klasy, możę ktoś coś wymyśli, jak nie to ja też spróbuję.
