### ISSUE TITLE
interia

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#17637]
Anty-adblock
https://biznes.interia.pl/
https://www.pomponik.pl
![ineria01](https://user-images.githubusercontent.com/70756447/99198635-3a360e00-279a-11eb-8926-7a08ad31b253.PNG)

dodatkowo występują **reklamy** "plush" w grupie podstron interia.pl - to tylko przykłady
https://sport.interia.pl/serie-a/news-serie-a-arkadiusz-milik-odmowil-jedynie-fiorentinie,nId,4856647
https://kobieta.interia.pl/uroda/news-jak-dbac-o-wlosy-aby-rosly-szybciej,nId,4852704
https://film.interia.pl/wiadomosci/news-arnold-schwarzenegger-nawoluje-amerykanow-do-odwiedzania-cme,nId,4856563
https://kobieta.interia.pl/uroda/news-jak-dobrac-neonowy-cien-do-teczowki,nId,4852987
https://motoryzacja.interia.pl/wiadomosci/news-ponad-polowa-zatrzymanych-ciezarowek-nie-powinna-byc-na-drog,nId,4853037
https://muzyka.interia.pl/wiadomosci/news-the-four-bitwa-o-slawe-kto-wygral-w-finale,nId,4855051

![db1fix](https://user-images.githubusercontent.com/70756447/99152904-1e047500-26a5-11eb-81aa-d0561833c5ed.PNG)

**Comment by gzenio22** [comment]
adb detekt nie uświadczam co do reklamy plusha tak pokazuje sie

**Comment by Brissinger** [comment]
Na wirtualnej i jej pochodnych i o2 już nie mam info o adblocku, ale na tych 2 podanych tak.

**Comment by zaba-monika** [comment]
### 1 Co do anty-adblocka na `biznes.interia.pl` + `pomponik.pl` :
- w uBO Legacy pojawia się na obydwu stronach, zarówno w Firefox jak i w Chroperze / Chromowatych
- w uBO normalnym pojawia się tylko na `biznes.interia.pl` i tylko na Chroperze / Chromowatych ( na `pomponik.pl` być może też się pojawia, ale trudno to stwierdzić bo przeglądarka nie ładuje strony:
<details not-open>
<summary>zrzut ekranu</summary>


![capture_074_16-11-2020_08-19-50](https://user-images.githubusercontent.com/72980128/99223878-9eca8a80-27e5-11eb-8a54-0fe737e548af.png)
</details>

### 2 Co do reklam `Plush` :
- zgłaszałem je jakiś tydzień temu ale tylko na głównej stronie wiec tylko na głónej zostały naprawione
- a dlaczego nie zgłosiłem tej reklamy na podstronach? bo jej nie miałem, bo ukrywały mi je listy: AdGuard Base filter + EasyList Polish, więc dopiero teraz po wyłączeniu tych list reklamy na podstronach się pokazują

**Comment by krystian3w** [comment]
Ja nie nam na obu, pewnie uBlock-user znowu sobie napisał kolejny set-constant, okresowo otwierając Interię/pomponik.

**Comment by AroKol78** [comment]
używam "uBlock-for-firefox-legacy 1.16.4.26" (https://github.com/gorhill/uBlock-for-firefox-legacy) bez żadnych dodatkowych skryptów, nie używam "chrome" ani żadnych "chromowatych"

**Comment by zaba-monika** [comment]
@MajkiIT @ zgłaszający

Naprawą jest dodanie reguły wziętej z listy AdGuard Base:
`@@||iwa3.hit.interia.pl^*/iwa_core?ts=$domain=pomponik.pl|interia.pl`

**Comment by AroKol78** [comment]
👍  @zaba-monika dałbym kciuka w góre ale nie moge
Anty-adblock https://biznes.interia.pl/ https://www.pomponik.pl rozwiązane 👍

**Comment by krystian3w** [comment]
`chrome://settings/content/ads` - może tam trzeba dodać do wyjątków, tylko jak Interia złapała się na algorytm ciężkich/zasobożernych reklam?

**Comment by zaba-monika** [comment]
> @zaba-monika dałbym kciuka w góre ale nie moge

- spoko, widocznie kiedyś lubiłeś dać także w dół (bez argumentu), więc musiałam cię przyblokować...
- najważniejsze, że anty-adblock naprawiony

> u mnie główna strona interii jest w porządku , nie jest rozjechana

- na Operze? bo u mnie jest rozjechana tylko na Operze

**Comment by zaba-monika** [comment]
> `chrome://settings/content/ads` - może tam trzeba dodać do wyjątków, tylko jak Interia złapała się na algorytm ciężkich/zasobożernych reklam?

- masz na myśli to? miałam  i mam to zawsze wyłączone więc to nie to...

![333](https://user-images.githubusercontent.com/72980128/99268540-96923f80-2825-11eb-8a1a-5505ed0a9134.png)

**Comment by AroKol78** [comment]
> - jedynie jest zabawna sytuacja na Chroperze + nowy uBO, gdzie nawet **po wyłączeniu adblockera** dalej pojawia się anty-adblock i nie da się przeglądać strony...ale to już problem po stronie Interia

raczej po stronie przeglądarki

**Comment by zaba-monika** [comment]
Masz rację, może to być nie tylko problem strony ale również problem przeglądarki.

**Comment by AroKol78** [comment]
ktoś jeszcze używa Opery o koretne wersji ?
czy wszyscy użytkownicy Opery zgłaszją problemy ?
czy ktoś tu pisze co używa ?

**Comment by zaba-monika** [comment]
> czy ktoś tu pisze co używa ?

No właśnie mało kto pisze czego używa...trzeba się zazwyczaj bawić w zgaduj-zgadula  :smiley:

**Comment by zaba-monika** [comment]
Przy okazji do adminów: etykietę "reklama" poprosimy.

**Comment by AroKol78** [comment]
brak reklam 👍 
na Anty-adblock dodać
@@||iwa3.hit.interia.pl^*/iwa_core?ts=$domain=pomponik.pl|interia.pl
i można zamykać

**Comment by zaba-monika** [comment]
I ty to wymyśliłeś, że sobie autorstwo przypisujesz? Kolejny krystian3w się znalazł (on może jużtak nie robi, po tym jak kiedyś dostał ochrzan)...jak coś kopiujesz to nie kradnij tylko podawaj autora albo link: https://github.com/MajkiIT/polish-ads-filter/issues/17637?_pjax=%23js-repo-pjax-container#issuecomment-728102959, jak ja podałem rozwiązanie to podałęm, że wziąłęm z AdGuarda.

**Comment by zaba-monika** [comment]
AroKol78 chyba zapomniałeś, że jesteś autorem wątku, masz możliwość zamknięcia w dowolnej chwili :smiley:
