### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#17631]
### Zrzut ekranu
![db2fix](https://user-images.githubusercontent.com/70756447/99152787-450e7700-26a4-11eb-93ad-b9dc2b63eab5.PNG)

### Link bezpośredni
https://www.dobreprogramy.pl/

### Moja konfiguracja
Serpent/UXP 52.9.0 20201113

**Rozszerzenia i skrypty:**
uBlock-for-firefox-legacy 1.16.4.26 (scripts brak)

**Listy filtrów:** 
![db1fix](https://user-images.githubusercontent.com/70756447/99152904-1e047500-26a5-11eb-81aa-d0561833c5ed.PNG)
**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
reklamy pojawią (na początku, w środku i na końcu) się po 2-3 sekundach

**Comment by krystian3w** [comment]
Obejście:

- Wystarczy założyć konto, 
- wrzucić 2 komentarze, 
- poczekać aż moderator je zatwierdzi (opcjonalnie po tygodniu niby komentarz od razu leci jako publiczny)
- potem regularnie co 30 dni dodawać dwa nowe komentarze

Strona ma też opcje wyłączenia reklam na 90 dni:
- jak napiszesz recenzje programu i moderator ją zaakceptuje
- jak napiszesz świetny wpis na swoim dobroprogramowym blogu https://www.dobreprogramy.pl/Blog.html i trafi on aż na główną po wrużnieniu przez redakcję "WP" lub moderatora blogów (jeden moderator jest redaktorem, drugi raczej nie ma statusu redaktora, o tym by był dalej 3 moderator bloga nic nie słyszałem).

**Comment by AroKol78** [comment]
> Obejście

to tak jakby leczyć cholerę dżumą

**Comment by zaba-monika** [comment]
- włącz listę AdGuard Base
- albo wyciągnij i dodaj se regułę z AdGuard Base: 
`dobreprogramy.pl##+js(set-constant.js, Object.prototype.advViewability, undefined)` 
(czyli ta sama reguła o której dopiero co wspominałem tutaj: https://github.com/MajkiIT/polish-ads-filter/issues/17629#issuecomment-727221525)

**Comment by 0xtrzy** [comment]
po dodaniu reguły w Brave
dobreprogramy.pl##+js(set-constant.js, Object.prototype.advViewability, undefined)
nadal działa
![Przechwycenie obrazu ekranu_2020-11-27_10-49-54](https://user-images.githubusercontent.com/59196690/100435620-7c1a5a80-309e-11eb-947f-8ac26c729e8f.png)

**Comment by AroKol78** [comment]
u mnie jest bez reklam

**Comment by krystian3w** [comment]
Brave specific, bo niby filtr jest w: https://github.com/MajkiIT/polish-ads-filter/commit/6dc847b6113c618db669369dd624fd94c845426b

@0xtrzy zrób test jak usuniesz z nazwy `-constant.js` lub samo `.js`, uBO powinno umieć wstrzyknąć. Brave Blocker pewnie już nie ogarnia dostępności 3 nazw dla skryptletu.

**Comment by AroKol78** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/17877#issuecomment-734999750 > @zaba-monika spójrz tutaj https://github.com/MajkiIT/polish-ads-filter/issues/17631#issuecomment-734747930

**Comment by krystian3w** [comment]
AdamWr już wymyślił z chyba 3 nowe skryptlety na reklamy WP.
