### ISSUE TITLE
kwejk.pl cookie fix

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1764]
![image 010](https://cloud.githubusercontent.com/assets/9846948/21472362/f29e50a4-cad5-11e6-8d29-4ad9b21f8e06.png)

```
kwejk.pl###cookies-politics
```

**Comment by kerbenii** [comment]
Myślę, że spokojnie można nawet to zrobić tak:
`pl###cookies-politics`
