### ISSUE TITLE
paypal.com

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17641]
Ciastko po zalogowaniu się na konto

![Screenshot_1](https://user-images.githubusercontent.com/21177361/99370229-b5dcab80-28bd-11eb-8edc-010f38237ea3.png)

**Comment by zaba-monika** [comment]
hehe, no zaraz będziecie mieli dużo ciastek..

**Comment by zaba-monika** [comment]
gzenio ale ja tego komunikatu nie mam, ukrywa mi go Polskie Filtry RODO-Ciasteczkowe

**Comment by krystian3w** [comment]
Przydałby się poradnik krok po kroku, bo tu nie widzę:

https://www.paypal.com/myaccount/summary

dodatkowo to są różne layouty.

**Comment by krystian3w** [comment]
PayPal podobno nie wygasa, więc zapomniałeś hasła lub cię usunięto.

PS. jak miałeś jakieś środki lub 50 złotych to nowy regulamin sprawi, że po 12 miesiącach nieaktywności ci znikną.

**Comment by krystian3w** [comment]
@gwarser, przy dodawaniu karty lub rachunku bankowego mają jakiś bug w layoucie i nie można go tym naprawić na dłuższą metę:

```js
! https://www.paypal.com/myaccount/money
paypal.com##body.vx_hasOpenModal:has(> #mainModal:matches-css(display: none)) > div.vx_foreground-container:style(position: relative !important;)

paypal.com##body.vx_hasOpenModal > #mainModal:matches-css(display: none) ~ div.vx_foreground-container:style(position: relative !important;)
```

Niby jak klikam w zamknij pop-up to strona zapomina usunąć klasę "vx_hasOpenModal" i przewijanie się psuje aż web developer nie naprawi.

**Comment by zaba-monika** [comment]
Chyba nie d oczytałeś mojego komentarza

>  krystian3w com : więc zapomniałeś hasła 

Nie zapomniałam,  jak już napisałam: "pomimo wpisania poprawnych danych", dane mam zapmiętane w przeglądarce, nie wpisywałem ich z kartki ani z pamięci...

>  krystian3w com : lub cię usunięto.

Wiem, bo już wspominałam: "i chyba wygasło" 
chyba, że dla ciebie "usunięto" znaczy co innego niż "wygasło"

**Comment by krystian3w** [comment]
Ja tam mam już tylko formularz, gdzie login jest oddzielony od hasła. Trochę dziwne by tylko Opera miała jakiś inny.

**Comment by zaba-monika** [comment]
- nie wiem czy z tą Operą, to piszesz o swojej przeglądarce / zrzucie ekranu czy o moim, ale ja swój zrzut ekranu zrobiłam na Firefoxie...
- taki formularz jak na twoim zrzucie jest tylko za pierwszym razem, po wpisaniu jakiś danych i przejściu dalej, od tego momentu formularz jest taki jak na moim zrzucie, ale wystarczy wyczyścić cache & ciasteczka & dane itp. i znowu będzie za pierwszym razem tak jak na twoim zrzucie...

**Comment by gzenio22** [comment]
moj screen jest ze strony domowej konta zaraz po zalogowaniu nie chcialem pokazac kwoty Xd ale jest wsumie te ciacho na kazdej ze stron

**Comment by krystian3w** [comment]
No to nie wiem, ja nie mam niech ci @hawkeye116477  wytnie po połączeniu przy pomocy VNC / TeamViewer / AnyDesk.

**Comment by hawkeye116477** [comment]
A co się stanie jak zaakceptujesz? Jeżeli raz to zrobisz i jest zapisywane na konto, a potem już nie pytają, to nie ma sensu dodawać na to reguły.

**Comment by krystian3w** [comment]
Nie zapisują na IP/Konto, z 3 razy już akceptowałem.

Może on ma jakiś layout "beta".

**Comment by gzenio22** [comment]
To co Panowie zostawiamy to? w sumie ta stopka niby nie przeszkadza no ale wedle zasady powinna byc zdjęta przez filtr

**Comment by gwarser** [comment]
@krystian3w pomogło by coś jak `:watch-attr()` ale sprawdzającego atrybuty styli (`:matches-css()`) zamiast atrybutów nodów?

<sub>Kurde, tylko ja nie mam paypala? Trzeba chyba założyć i link gdzieś wrzucić, może nazbieram na klawiaturę xD</sub>

**Comment by krystian3w** [comment]
Nie sądzę; ale ustaliłem, że to nadgorliwość skryptu w Dodatku Google:

https://tools.google.com/dlpage/gaoptout?hl=pl

Wywalamy i strona się naprawia.

**Comment by gzenio22** [comment]
@krystian3w tylko ja nie mam tego dodatku Xd

**Comment by krystian3w** [comment]
A ja dalej nie widzę tego paska i nie zapisuje się on na IP/konto.

**Comment by zaba-monika** [comment]
krystian mógłbyś etykietę poprawić z łaski swojej

**Comment by krystian3w** [comment]
Nie mam uprawnień do etykiet, tylko majkiit i xcitrinix.

**Comment by zaba-monika** [comment]
chodziło mi o etykietę na repo EI...

**Comment by gzenio22** [comment]
nie wiem czy ktos cos kminil ale mi rodo z PP znikło?

**Comment by krystian3w** [comment]
Nie było ruszane, prosisz się o wpisanie na listę "oszustów" 🤣.

Albo PayPal wyłączył testy A/B na twoim koncie i widzisz taki sam pop-up RODO jak niezalogowani.

**Comment by gzenio22** [comment]
ej ja wrzucam cos po sprawdzeniu nie na czuja Xd ja chce pomagac a nie robić pod góre zostawic to jeszcze czy zamknąć problem?

**Comment by krystian3w** [comment]
Ja bym zamknął, jak znów będziesz miał to musisz pomyśleć jak zapisać to do pliku zip bez twoich prywatnych danych lub czy zezwolisz @hawkeye116477 na test z użyciem np. TeamViewer.

---

PS. dalej nie zapisują tego do Konta lub IP.

**Comment by gzenio22** [comment]
pozwolę zarówno @hawkeye116477 jak i @MajkiIT chwile ten kontakt juz mamy narazie zamykam
