### ISSUE TITLE
ssl.sisms.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17659]
Wiem, że statyczny, ale jest na środku ekranu więc w uproczywym miejscu to chyba raczej jednak się kwalifikuje:

![capture_102_17-11-2020_11-29-55](https://user-images.githubusercontent.com/72980128/99378926-4fa95600-28c8-11eb-86bc-4d2bd2dbbcc8.png)

**Comment by bug-rules** [comment]
Jest zamykacz, ten drugi link to "X" ale słownie.

Nawet ma coś w rodzaju ID - `[name]`

**Comment by zaba-monika** [comment]
- spoko, faktycznie, ale czy to znaczy, że się nie kwalifikuje i mam zamknąć? P
-  pytam bo się nie orientuję, i o ile wywalczyłam szczegółową instrukcję dla EI: 
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/CONTRIBUTING.md, 
to walczenie o stworzenie podobnej dla repo ciasteczkowego 
https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev
nie przyniosło rezultatu...
