### ISSUE TITLE
strabag-pfs.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17664]
![capture_108_17-11-2020_11-41-13](https://user-images.githubusercontent.com/72980128/99380118-d01c8680-28c9-11eb-8367-930e924830c5.png)

**Comment by bug-rules** [comment]
@MajkiIT  trzeba wyśrodkować dla @blocker999

**Comment by zaba-monika** [comment]
- póki co na szybko:powiązane: https://github.com/MajkiIT/polish-ads-filter/issues/17534
- reguła osadzająca za jakiś moment, w końcu to nie wyścigi formuły 1, chociaz czasem to tak wygląda :smiley:

**Comment by zaba-monika** [comment]
Nie wiem w jaki dokładnie sposób ktoś chce to osadzać, ale do wyboru:

- prosty:
 `strabag-pfs.pl###page_margins:style(position: relative !important;)`
- albo taki jak z tego podobnego zgłoszenia:
`strabag-pfs.pl###page_margins:style(position: relative !important; margin: 0px auto 0px auto !important; max-width: 980px !important; background-color:white !important; padding: 0px 0px 0px 20px; !important)`

**Comment by bug-rules** [comment]
`[align]` nie ma nic do tego u nich (i raczej nigdzie jak jest na `body`), `#padding_margins` ma pozycjonowanie absolutne do lewego górnego rogu, więc `static`/`relative` sprawia, że ignorowane i wygrywa wyśrodkowanie CSS-em `margin: 0 auto`.

**Comment by zaba-monika** [comment]
@MajkiIT pewnie nie zauważył że trzeba wyśrodkować, @xxcriticxx reopen please
