### ISSUE TITLE
medonet.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1766]
Po lewej stronie dodano  link do strony głównej, który przesuwa się automatycznie i zasłania treść.

```
###goback
```
http://www.medonet.pl/zdrowie,lekarze-ppoz-nie-podpisuja-kontraktow-z-nfz-na-2017-r-,artykul,1722617.html

![image 014](https://cloud.githubusercontent.com/assets/9846948/21472993/e63e8c02-caf3-11e6-9950-8e723ac3928d.png)

**Comment by FadeMind** [comment]
**Aktualizacja**

Ten baner link WRÓĆ NA ONET występuje obecnie na wszystkich domenach podrzędnych (ale nie własnych onetu):
![image 015](https://cloud.githubusercontent.com/assets/9846948/21473004/8562f840-caf4-11e6-8b73-9b2fdf7cbfb4.png)

**Comment by MajkiIT** [comment]
@FadeMind dzięki
