### ISSUE TITLE
archiwum.giodo.gov.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17660]
![capture_103_17-11-2020_11-33-20](https://user-images.githubusercontent.com/72980128/99379241-b4fd4700-28c8-11eb-8cfe-262c9b76f61e.png)

**Comment by bug-rules** [comment]
Znowu awaria OCR.

**Comment by zaba-monika** [comment]
> Znowu awaria OCR

Dzięki za wyłapanie fałszywego trafienia, ale to nie awaria, moduł OCR nie jest idealny, tak po prostu działa, że czasem łapie "trociny" o czym już pisałam: https://github.com/MajkiIT/polish-ads-filter/pull/17630#issuecomment-727229927, nie należy oczekiwać od niego 100% skuteczności w rozróżnianiu komunikatów, po prostu odczytał frazę "ochrony danych osobowych", moduł OCR nie jest człowiekiem i nie umie stwierdzić kontekstu w jakim ta fraza została napisana, lepszą skuteczność i mniej fałszywych trafień będzie miał moduł AI, który powstanie w bliżej nie określonej przyszłości, ale i jemu sporadycznie mogą się trafić "fałszywki" chociaż na pewno o wiele rzadziej, będzie to zależało od czasu poświęconego na jego wytrenowanie

> i też nie dla EI

Zgadza się, zamykam bo to się nie kwalifikue bo to jest "informacyjny", chociaż nawet dla człowieka do złudzenia przypominający komunikat RODO - gdyby patrzeć tylko wizualnie i bez szczegółowego odczytywania tekstu to ic złowiek mógłby się pomylić...
