### ISSUE TITLE
bwa.katowice.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17685]
![Zrzut ekranu z 2020-11-17 13-02-39](https://user-images.githubusercontent.com/36385327/99388018-36f36d00-28d5-11eb-8f52-469af237d77e.png)

**Comment by krystian3w** [comment]
@hawkeye116477 / @blocker999 - soundcloud to już social media? przyrównywać do YT?

**Comment by hawkeye116477** [comment]
Tak
