### ISSUE TITLE
[NSFW] plotek.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1770]
![image 022](https://cloud.githubusercontent.com/assets/9846948/21501632/b64edf90-cc49-11e6-8525-ac42196982e3.png)

```
##.houdini
```

Site http://www.plotek.pl/plotek/7,78649,21169718,renata-kaczoruk-i-wojewodzki-swieta-spedzaja-w-brazylii-zdjecia.html

**Comment by MajkiIT** [comment]
@FadeMind super dzięki
