### ISSUE TITLE
Quartic.pl - za szeroki filtr.

### ISSUE THREAD

**Issue by kerbenii** [MajkiIT/polish-ads-filter#1771]
Hej, obawiam się, że dodaliście do listy za szeroki filtr.
Właśnie teraz wycinacie wszystkie nasze usługi (m.in. badania behawioralne, analitykę stron, podmiany produktów w ramkach sklepowych), zamiast usługi adservera.
Dodatkowo, co boli nas najbardziej blokujecie nasz panel klienta.

Bardzo proszę o zmianę filtru na:
```
||qad.quartic.pl/Ad/$script
||qad.quartic.pl/Ad/$script
||qad*.quartic.pl/Ad/$script
||qas*.quartic.pl/Ad/$script
```

który spowoduje zablokowanie wszystkich naszych adserverów (reklam), ale pozwoli nam świadczyć pozostałe usługi.

Dziękuję ślicznie,
Patryk Węgrzynek
Backend Developer
Quartic

**Comment by MajkiIT** [comment]
Ok, dzięki za info. Dodamy wyjątek. 
`||quartic.pl^$third-party,domain=~quarticon.com|~quartic.pl`

**Comment by MajkiIT** [comment]
@kerbenii a jak dużo danych pobieracie z sesji klienta? 
`http://www.admonkey.pl/gemius-we-wspolpracy-z-quartic-wprowadza-gemiusrecommend-nowy-produkt-dla-dunskiego-e-commerce-9092.html`

**Comment by MajkiIT** [comment]
@kerbenii ponadto ten wasz cdn nic nie cachuje.

**Comment by kerbenii** [comment]
Więc tak,  po konsultacjach z Architektem:
Nasz cdn (domena cst) cacheuje zdjęcia produktów ze współpracujących sklepów e-commerce (nie widzicie ich zapewne dlatego że macie je zablokowane w filtrze, albo patrzycie na stronę na której robimy tylko advertising internal). Nie lecą przez nie żadne cookiesy. 

Gemius Recommend jest produktem wygasłym (do sprawdzenia na ich stronie internetowej). Nie wysyłamy im żadnych danych. 

Pozostaje cookie maching, który dokonują adservery (już przez was zablokowane). 

Zbieramy w sesji jedynie adresy produktów jakie użytkownik odwiedził (można to zweryfikować poprzez filtr TT w Network trackerze).
