### ISSUE TITLE
miejska.info.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17711]

**Comment by hawkeye116477** [comment]
Reklamy lokalne zostają?

**Comment by krystian3w** [comment]
Jak nie reklamują usług `miejska.com.pl` (pytanie jakie np. kursy CMS / html???) to raczej powinny być wycinane.

Może problem jest jak to wyciąć sieciowo lub jakim filtrem proceduralnym (ExtendedCSS) by strona nie muliła.

**Comment by krystian3w** [comment]
Ja bym wyciął np. tę inteligentną agencje reklamową od LED-ów / przyczep / kliniki urody tym:

```
#?#li[class*="slide-"]:-abp-has(a img[src*="banner"]:not([src*="miejsce_na_reklame"]), a img[src*="reklama"]:not([href*="miejsce_na_reklame"]))
```

Reklamy mają ze 3 lata.

Jedynie pytanie czy zostaje plansza: "Miejsce na reklamę" jak też znika to można wywalić oba `:not([src*="miejsce_na_reklame"])`,

**Comment by felix-22** [comment]
Już tych reklam nie ma nawet po wyłączeniu adblockera, są tylko 3 puste kontenery po prawej, ale są puste nawet po wyłączeniu adblockera i sąw kolorze tła strony, więc nawet ich nie widać, a i tak nie wiadomo czy to od reklam czy od zdjęć. Na chwilę obecną reklam nie ma, można zamknąć zgłoszenie.

**Comment by krystian3w** [comment]
Jak dla mnie to strona zmieniła szablon/CMS - wcześniej był bordowy i jakby z '2010'.
