### ISSUE TITLE
Grupa NEUCA (11 stron)

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17720]
aptekarska.pl
cefarm-cz.com.pl
dolpharma.pl
galenicapanax.pl
hurtowniamulti.pl
itero-silfarm.pl
mojezdrowie.com.pl
optimaradix.pl
pregosa.pl
prosper.pl
torfarm.pl

- **przykładowy zrzut ekranu z komunikatem ciasteczkowym:**

![capture_007_18-11-2020_20-10-50](https://user-images.githubusercontent.com/72980128/99576350-2678ea80-29da-11eb-975f-ad8e080377c5.png)

- **zrzut ekranu Grupa NEUCA:**

![capture_008_18-11-2020_20-11-08](https://user-images.githubusercontent.com/72980128/99576414-3db7d800-29da-11eb-84b0-a745bfeece3e.png)

**Comment by MajkiIT** [comment]
tych domen jest więcej ...

**Comment by zaba-monika** [comment]
Jeśli chodzi o mnie to:
- wiem, ale mnie one nie interesują, bo mam już na nich ciastka ubite przez dodatkowe listy: EasyList Cookie + kilka własnych filtrów generycznych...więc to już wasza sprawa jeśli się okaze, że wam ciastka wyskakują na kilku dodatkowych stronach...
- kilka razy w przeszłości już tłumaczyłam, że korzystam z kilku dodatkowych list zarówno ciasteczkowych jak i  reklamowych i jeśli one mi już coś ukrywają to ja tego zazwyczaj nie zgłaszam
- nie podam linków do komentarzy w których o tym pisałam bo poznikały razem z kontami...
- chociaż jeden znajdę sprzed kilku dni, tutaj https://github.com/MajkiIT/polish-ads-filter/issues/17637#issuecomment-727792719 w punkcie nr **2** pisałam, że zazwyczaj nie zgłaszam czegoś, gdy mi już jakaś dodatkowa lista ukrywa...
- ale czy ktoś to w ogóle czyta...

A jeśli o tym wszystkim wiesz i pomimo tego tylko chciałeś poinformować kolegów, że jest więcej stron to naprawy to ok, nie bronię...

**Comment by MajkiIT** [comment]
`www.30lat.neuca.pl##.landend-infobar-light`
