### ISSUE TITLE
komorkomania.pl

### ISSUE THREAD

**Issue by Eva850** [MajkiIT/polish-ads-filter#1772]
Komunikat o blokowaniu reklam, nie odtwarza się video
http://komorkomania.pl/33976,android-7-1-samsung-sony
![adblock](https://cloud.githubusercontent.com/assets/20646455/21507946/ffc8cf72-cc7c-11e6-9e7a-ab29459fe2da.png)

**Comment by MajkiIT** [comment]
@Eva850 AAK filters masz wyłączone?

**Comment by xxcriticxx** [comment]
@Eva850 umnie dziala bez problemu

**Comment by F4z** [comment]
@MajkiIT tylko ja widzę reklamy na tej stronie?

**Comment by xxcriticxx** [comment]
@F4z podaj jakis link albo screen shot

**Comment by F4z** [comment]
@xxcriticxx link - `http://komorkomania.pl/33976,android-7-1-samsung-sony`

![image](https://cloud.githubusercontent.com/assets/11742596/21508162/eb1bc53c-cc7e-11e6-9bea-356d2776a1be.png)

**Comment by Eva850** [comment]
Próbowałem z wyłączonym AAK oraz z tą wersją:
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/anti-adblock-killer/anti-adblock-killer-filters.txt
ale nadal video nie działa

**Comment by Eva850** [comment]
Wspomnianej reklamy nie mam

**Comment by xxcriticxx** [comment]
@Eva850 clear your recent history and/or remove individual cookies

**Comment by xxcriticxx** [comment]
@F4z filtry jakiej ver?

**Comment by xxcriticxx** [comment]
@F4z zrobilem update filtrow do najnowyszych tez mam reklamy

**Comment by Eva850** [comment]
Wersja 27 December 2016  2016122702

**Comment by F4z** [comment]
Z wyłączonym AAK też nie mam tej reklamy, z tą listą - https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/anti-adblock-killer/anti-adblock-killer-filters.txt - też tej reklamy nie będzie, bo jest usunięta reguła, która za dużo zezwala, ale filmy się nie wyświetlają.

@Eva850 sprawdź tę regułę:
`@@/^(http|https):\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(.{0,15}[&!*;@\$)[\]:%].*|(?!gaf|cap|vad|display|dis3rd)[a-zA-Z0-9\W_]{0,10})\.(js|html|xml|jpg|gif|png)|^(http|https):\/\/rek\.www\.wp\.pl\/gaf\.js$|^(http|https):\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/[a-zA-Z0-9=]{1,180}=$|^(http|https):\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(?!gaf|cap|vad|display|dis3rd)[a-zA-Z0-9,_]{0,180}\.(js|html|xml|jpg|gif|png)|^(http|https):\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(?!gaf|cap|vad|display|pliki)[a-zA-Z0-9]{15,50}$/`

**Comment by xxcriticxx** [comment]
w private mode mam puste box po reklamach i ad block 

zmieniaja cos na stronie?

**Comment by xxcriticxx** [comment]
po wylonczeniu reeka listy mam tylko puste pola po reklamch

**Comment by F4z** [comment]
U mnie jest tak, że jak wyłączę AAK i dodam tę regułę:
`@@/^(http|https):\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(.{0,15}[&!*;@\$)[\]:%].*|(?!gaf|cap|vad|display|dis3rd)[a-zA-Z0-9\W_]{0,10})\.(js|html|xml|jpg|gif|png)|^(http|https):\/\/rek\.www\.wp\.pl\/gaf\.js$|^(http|https):\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/[a-zA-Z0-9=]{1,180}=$|^(http|https):\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(?!gaf|cap|vad|display|dis3rd)[a-zA-Z0-9,_]{0,180}\.(js|html|xml|jpg|gif|png)|^(http|https):\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(?!gaf|cap|vad|display|pliki)[a-zA-Z0-9]{15,50}$/`

To filmy działają, ale czasami mam puste miejsce po reklamie, a to z tego powodu, że ta reguła za dużo zezwala - `@@/:\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(.{0,15}[&!*;@\$)[\]:%].*|(?!cap|vad|display)[a-zA-Z0-9\W_]{1,10})\.(js|html|xml|jpg|gif|png)/`

**Comment by Eva850** [comment]
Niestety u mnie nadal nie działa nawet po dodaniu tej reguły i usunięciu AAK list

**Comment by xxcriticxx** [comment]
@Eva850 wp.pl sprawdza cookies tez skasuj historie z dzisaj i wszystkie cookie z wp.pl

**Comment by F4z** [comment]
@Eva850 możesz zrobić screenshota z dziennika żądań z uBlocka z samymi zablokowanymi połączeniami?
https://github.com/gorhill/uBlock/wiki/The-logger

Najlepiej żeby to wyglądało tak jak na obrazku poniżej.
![image](https://cloud.githubusercontent.com/assets/11742596/21508610/acb78f5c-cc82-11e6-81f3-5948dc36f00e.png)

**Comment by F4z** [comment]
@Eva850 jeszcze takie pytanie, bo zauważyłem, że masz ikonkę tarczy z lewej strony na pasku adresu.
Nie zmieniałaś ustawień Firefoxa, czegoś związanego z ochroną przed śledzeniem w `about:config`, czy gdzieś indziej?
Bo to też może być tego wina.

**Comment by Eva850** [comment]
![log](https://cloud.githubusercontent.com/assets/20646455/21508784/18c0110a-cc84-11e6-9d4a-441f9ee854a1.png)

**Comment by Eva850** [comment]
Wyłączenie ochrony przed śledzeniem (ikona tarczy) rozwiązało problem, video działa. Dziękuję

**Comment by F4z** [comment]
To dobrze.

**Comment by F4z** [comment]
Trololo https://github.com/MajkiIT/polish-ads-filter/issues/1762#issuecomment-269394124

**Comment by xxcriticxx** [comment]
na jakiej boxie? dns? czy normalnej?

**Comment by F4z** [comment]
?

**Comment by xxcriticxx** [comment]
naczym mam to testowac #1762 (comment) bo napisales pod #1762 tam bylo o dns

**Comment by F4z** [comment]
W przeglądarce internetowej z uBlockiem Origin najlepiej :)

**Comment by xxcriticxx** [comment]
ale jak mam to jedna regule wylonczyc? ta opcja jest tylko w adblock plus jak dobrze pamietam

**Comment by xxcriticxx** [comment]
film dziala i sa reklamy dalej 

![capture](https://cloud.githubusercontent.com/assets/15007183/21510199/b7f81900-cc5e-11e6-9123-649ee5f769a7.PNG)

**Comment by F4z** [comment]
Ale wyłączyłeś tę regułę?
`@@/:\/\/(adv|rek\.www|owabgxis|fntajkb)\.wp\.pl\/(.{0,15}[&!*;@\$)[\]:%].*|(?!cap|vad|display)[a-zA-Z0-9\W_]{1,10})\.(js|html|xml|jpg|gif|png)/`

**Comment by xxcriticxx** [comment]
w private mode niemam reklam ale mam adblock na filmie 

nie wylonczylem jak ja wylonczy tylko to jenda regule?

**Comment by F4z** [comment]
@xxcriticxx na czas testów wyłącz polską listę oraz AAK i dodaj tę - http://pastebin.com/raw/w4tiJML9
Tam usunąłem regułę, przez którą są reklamy i dodałem tę, dzięki której powinny się filmy wyświetlać.

**Comment by xxcriticxx** [comment]
puste pole REKLAMA film dziala

![capture](https://cloud.githubusercontent.com/assets/15007183/21510294/b485cb18-cc5f-11e6-9bf8-01b201c4d6d3.PNG)

**Comment by F4z** [comment]
Nie powinno ich być, możesz zrobić screenshota z loggera uBlocka?

**Comment by F4z** [comment]
Masz włączoną polską listę?

**Comment by xxcriticxx** [comment]
wylonczona dodalem to z pastebin

**Comment by xxcriticxx** [comment]
sorry shit jak cudem sie wlonczyla jeszcze raz test zrobie

**Comment by xxcriticxx** [comment]
sorry mam wylonczona ta z pastebin pokazuje mi sie jako ze mam POL liste wlonczona

**Comment by xxcriticxx** [comment]
muszisz to na adblock plus przetestowac zeby mozna ta regule wylonczyc 

albo zrobic update do glownej listy do testow 

ja lece bende za 30 min

**Comment by F4z** [comment]
Już się pogubiłem.
Na pierwszym obrazku, który przed chwilą wysłałeś jest widoczne coś takiego `@@/:\/\/(adv|rek\.www|owabgxis|fntajkb)`, ta reguła jest z polskiej listy, bo ja ją usunąłem.

Odznacz po prostu polską listę w uBlocku a tę z pastebin wrzuć na dole.

![ubo](https://cloud.githubusercontent.com/assets/11742596/21510505/7600b260-cc94-11e6-9599-08d09af3a8a2.JPG)

**Comment by xxcriticxx** [comment]
@F4z jedzcze raz testuje

**Comment by xxcriticxx** [comment]
@F4z reklam niema ale filmu sprawdze za 5min

**Comment by xxcriticxx** [comment]
niema reklam i filmy dzialaja mozna dodac

**Comment by MajkiIT** [comment]
@Eva850 @xxcriticxx @Eva850 
Dzięki za wyjaśnienie sytuacji.

@F4z poprawisz co trzeba w regułach, bo ja nie chcę namieszać.
