### ISSUE TITLE
wydarzenia.interia.pl

### ISSUE THREAD

**Issue by wiaczeslaw-swoboda** [MajkiIT/polish-ads-filter#17738]
### Zrzut ekranu 

![image](https://user-images.githubusercontent.com/74715056/99664730-ec0a5e80-2a68-11eb-97f6-e25ae55522a6.png)

### Link bezpośredni 

https://wydarzenia.interia.pl/lodzkie/news-sieradz-32-letnia-pracownica-kantoru-ukradla-100-tys-zlotych,nId,4846778

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
1. Po prostu wejsc na strone

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Opera 72
**Rozszerzenia i skrypty:** 
Adblock Plus 3.10
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Polskie Filtry Społecznościowe

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by AroKol78** [comment]
uBlock legacy
u mnie bez reklam
![poo204](https://user-images.githubusercontent.com/70756447/99666194-f0377b80-2a6a-11eb-89b0-1731d436b91a.PNG)

**Comment by krystian3w** [comment]
Czyli trzeba sięgnąć po Operę i Adblock Plus (ABP).

W wersji ABP 3.10 niby trochę zmian było https://adblockplus.org/releases/adblock-plus-310-for-chrome-firefox-microsoft-edge-and-opera

**Comment by zaba-monika** [comment]
A więc tak, mam Operę i ABP 3.10 więc sprawdziłam:

- również nie mam tej reklamy u góry, ale za to mam kilka pustych kontenerów po reklamach, legenda:
- zielone kreski tylko oddzielają zrzuty ekranu
- czerowne prostokąty to właśnie puste kontenery po reklamach

<details not-open>
<summary>zrzut ekranu 1</summary>



![11111](https://user-images.githubusercontent.com/72980128/100205350-4d1cb100-2f05-11eb-82ec-500b1fb47494.png)
</details>

- wszystkie znikają po odznaczeniu "Zezwalaj na akceptowalne reklamy":

<details not-open>
<summary>zrzut ekranu 2</summary>


![222222](https://user-images.githubusercontent.com/72980128/100205478-76d5d800-2f05-11eb-8615-9a0cb219ac77.png)
</details>

@wiaczeslaw-swoboda jeśli masz włączone "Zezwalaj na akceptowalne reklamy" to spróbuj wyłączyć i odświeżyć stronę.

**Comment by zaba-monika** [comment]
@MajkiIT można to zamknąć
