### ISSUE TITLE
[repo EI] - nie dochodzą zgłoszenia za pomocą formularza

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17741]
Wiem, że to dotyczy repo EI, ale właśnie problem polega na tym, że nie mogę tam się zapytać bo mnie zablokowali, a formy kontaktu innej niż github również nie znalazłam...a problem jest poważny bo zgłoszenia utworzone za pomocą formularza przestały dochodzić jak w: https://github.com/MajkiIT/polish-ads-filter/issues/17628#issuecomment-730414038 (proszę tam odpisywać w razie czego, bo te zgłoszenie to tylko informacyjne tak na chwilę, żeby ktoś dostrzegł tamten komentarz)

**Comment by MajkiIT** [comment]
@hawkeye116477 @krystian3w zerkniecie ?

**Comment by zaba-monika** [comment]
Ale jak coś to niech odpisują w tym wątku: https://github.com/MajkiIT/polish-ads-filter/issues/17628#issuecomment-730414038
