### ISSUE TITLE
[NSFW] abdcn.pro

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#1775]
`http://abdcn.pro/rndr/XXL_Power_Life_blog_PL/?a=1&utm_term=1&esub=-4A25sMQL6BQGoBJu39ooAAkiIAQAC6xYCBgICeCsCBgEBAAQNb5j6AA&subacc=PL_pa_titan_under_web&utm_source=Windows%20/%2010&subacc2=1298644&subacc3=General/Computers&subacc4=Opera%20/%20Opera%20%28Desktop%29&utm_medium=1&rid=-4AAAAAAACSIgAAAAAAAAE2zV5IwA`

**Comment by xxcriticxx** [comment]
@adreporter to hyba dla KAD filters?

**Comment by FadeMind** [comment]
@xxcriticxx 
`hyba`

zlituj się...

**Comment by xxcriticxx** [comment]
@FadeMind ???

**Comment by MajkiIT** [comment]
@xxcriticxx jemu chodziło, że napisałeś "hyba" zamiast "chyba"

**Comment by xxcriticxx** [comment]
@FadeMind ja nie z kraju pisownie mam na potstawie 3 klasy blendy napewno benda :)

**Comment by adreporter** [comment]
@xxcriticxx Tak, masz rację, powinienem zgłosić do KAD. @azet12 już naprawił. Zamykam.
