### ISSUE TITLE
techsetter.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17769]
![capture_019_20-11-2020_11-32-55](https://user-images.githubusercontent.com/72980128/99790993-3a7d3300-2b25-11eb-9b9b-0e1482f5aa70.png)

**Comment by zaba-monika** [comment]
xxcriticxx może rozbroisz anty-adblock skoroś taki mundry

**Comment by bug-rules** [comment]
`techsetter.pl##+js(acis, ai_front, adb)` - może psuć wygląd mobilny, bo skrypt łączą z tym do wykrywania telefonów.

pomysłu dla ABP i AdBlock na razie brak

**Comment by xxcriticxx** [comment]
@zaba-monika dawno pisalem ze tutaj nic nie robie tylko sprzatam

**Comment by bug-rules** [comment]
Takie niby powinno działać z ABP, AdBlock, uBO i AdGuard:

```
techsetter.pl#@##banner-advert-container
techsetter.pl#@##adsense
techsetter.pl#@#.adsense
techsetter.pl#@#.ad-inserter
techsetter.pl#@#.sponsor-ad
techsetter.pl#@#.ad-img
techsetter.pl#@#.ad-index
techsetter.pl#@##im_popupFixed
techsetter.pl#@#[class^="ad-"]
@@||techsetter.pl/*/ad-inserter$script,image,domain=techsetter.pl
@@||adnxs.com^$image,domain=techsetter.pl
@@||contextual.media.net/dmedianet.js$script,domain=techsetter.pl
@@||router.infolinks.com^$image,domain=techsetter.pl
```

`adnxs.com` / `media.net` / `infolinks.com` blokuje niby tylko lista HOSTS Petera Lowe (w uBO niestety aktywna).

**Comment by zaba-monika** [comment]
bug-rules 

- twoje rozwiązania działają
- co do reguły skryptowej, to w uAssets dają ją w takiej formie: `techsetter.pl##+js(aopw, ai_front)`, 
a) ale to nic nie zmienia w kwestii ewentualnego psucia na tej stronie, 
b) więc wymyśliłam mniej inwazyjną regułę: `techsetter.pl##+js(nostif, _actions(a), 2)`

███████████████████████████████████████████████████████████████████████████

xxcriticxx 
- a) najwyraźniej nie dostrzegłeś ironii w moim komentarzu...
- b) po mnie sprzątnąłeś niesłusznie, zapraszam do lektury: https://github.com/MajkiIT/polish-ads-filter/issues/17775#issuecomment-731814956, ale do winy przecież się nie przyznasz...
- c) skoro już sprzątasz / zamykasz to zacznij od sprzątania po sobie i twoim koledze hawekeye te wasze wypociny w dyskusjach w moją stronę, bo póki co uparłeś się żeby sprzątać tylko po mnie (najpierw mi zamknąłeś niesłusznie dyskusję, potem niesłusznie zgłoszenie...)

Amen.

**Comment by bug-rules** [comment]
pewnie aopw ma mniejsze `race-condition` lub część stron nie ma tego jako skrypt liniowy wklejony byle gdzie.

**Comment by zaba-monika** [comment]
@MajkiIT 
- nie ma na co czekać
- rozwiązanie pod ABP masz tu: https://github.com/MajkiIT/polish-ads-filter/issues/17769#issuecomment-732122453
- rozwiązanie pod uBO: są podane 3 reguły `+js`, wybierz sobie jedną
