### ISSUE TITLE
www.wp.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17775]
https://github.com/AdguardTeam/AdguardFilters/issues/68197

PS. jednak do świąt żadne filtry nie wytrzymają...zbliżają się święta, więc renifery WP pedzą z saniami pełnymi prezentów...

**Comment by xxcriticxx** [comment]
tutaj wszystko wp.pl #13818

**Comment by zaba-monika** [comment]
- to może powiesz mi niby jak, skoro mam kłódkę od autora wątku mistrzu inteligentny, i o tej kłódce już dawno informowałam, chyba każdy to wie, tylko oczywiście nie ty...:
![2222](https://user-images.githubusercontent.com/72980128/99914064-52a6ab00-2cfb-11eb-9590-e68c11fd75cb.png)
- po drugie było ustalane również dawno temu, że tamten wątek jest do dyskusji ogólnej o WP, a konkretne zgłoszenia i tak trzeba wydzielić adminowi bo inaczej nie dostrzeże ich w natłoku wiadomości w tamtym wątku...
- tłumaczyłam to w szystko  jakiś czasu twojemu koledze hawkeyowi bo też się jakiś czas temu przywalił, że osobne zgłoszenie WP założyłam, a teraz to samo muszę tłumaczyć tobie, ciekawe komu jeszcze...
- lepiej zostaw to zgłoszenie otwarte, bo jak naprawią w AdGuard, to miałam zamiar napisać komentarz do admina, żeby przekopiował rozwiązanie do POL listy, na co tu mącisz, ja pomagam naprawiać reklamy, potem admin zapomni przekopiować z AdGuard i będzie twoja wina...
- nara
