### ISSUE TITLE
styl.pl+pomponik.pl

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#17777]
nie na wszystkich stronach są reklamy
brak https://www.styl.pl/newsy/aktualnosci/zdjecie,iId,2981601,iAId,390315
są np. na
https://www.styl.pl/newsy/aktualnosci/news-gora-plastiku,nId,4867684#iwa_source=worthsee
https://www.styl.pl/podroze/news-gigantyczne-oko-zachwycilo-swiat-zdjecie-podbija-siec,nId,4872508
![styllpl01](https://user-images.githubusercontent.com/70756447/99967911-bcc15d80-2d98-11eb-873c-b3938bb5455c.PNG)

https://www.pomponik.pl/plotki/news-kinga-rusin-zlamala-przepisy-policja-nie-oszczedzila-dzienni,nId,4872382#iwa_source=worthsee
![styllpl02](https://user-images.githubusercontent.com/70756447/99967920-c0ed7b00-2d98-11eb-8d62-70d69189bff4.PNG)

uBlock legacy
![db1fix](https://user-images.githubusercontent.com/70756447/99152904-1e047500-26a5-11eb-81aa-d0561833c5ed.PNG)

**Comment by krystian3w** [comment]
Mnie znikają po pełnym załadowaniu strony, wymuś aktualizację i zobacz czy będziesz mieć podobnie.

---

Najwyżej trzeba będzie sprawdzić używając np. Waterfox Classic jak tam to działa a potem czy błąd nie wymaga hotfix w uBO legacy.

**Comment by krystian3w** [comment]
`pomponik.pl,styl.pl#?#div[style*="sticky"]:-abp-has(> .boxHeader ~ a[href][target="_blank"][onclick*="'polsat'"])`

niby może być.

**Comment by krystian3w** [comment]
Wróciło, już nie ma headera:

https://www.styl.pl/newsy/gwiazdy/news-ewa-farna-juz-tak-nie-wyglada,nId,4878841

`interia.pl,pomponik.pl,styl.pl#?#div[style*="sticky"]:-abp-has(a[onclick*="'polsat'"])`

@MajkiIT

**Comment by AroKol78** [comment]
:up:

**Comment by krystian3w** [comment]
@MajkiIT

**Comment by krystian3w** [comment]
#17910
