### ISSUE TITLE
eurogamer.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#17779]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/99990349-00759080-2db4-11eb-8e99-be4ce6f76204.png)

### Link bezpośredni 

https://www.eurogamer.pl/articles/2020-11-23-wiedzmin-tez-czeka-na-swieta-nastrojowy-zwiastun-serialu-netflixa

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. 
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by zaba-monika** [comment]
- u mnie tego nie ma, widocznie masz niezaktualizowane:
`I don't care about cookies` lub `Polska Ciasteczkowa Zgoda`
- przy okazji ciekawostka https://github.com/AdguardTeam/AdguardFilters/issues/68007

**Comment by Barticf** [comment]
@zaba-monika Wersja bazy ciasteczkowej: 2020.11.23.0
W trybie prywatnym też ci to nie wyskakuje ?

**Comment by Barticf** [comment]
Nie włączyłem dodatku Polska Ciasteczkowa Zgoda dla trybu prywatnego w ustawieniach przeglądarki.

**Comment by zaba-monika** [comment]
Tak czy inaczej:
- jak ci w ogóle wyskakuje ten komunikat, skoro EasyList Coookie go uwala psując video tak jak tu https://github.com/AdguardTeam/AdguardFilters/issues/68007 ?
- muszę cię dodać tu:

**Comment by Barticf** [comment]
@zaba-monika mi filmy działają.

**Comment by krystian3w** [comment]
Pewien zagraniczniak wymyślił takie coś https://github.com/AdguardTeam/AdguardFilters/issues/64284 jak mu coś po-doradzałem:

`eurogamer.*,usgamer.*##.onetrust-pc-dark-filter, #onetrust-banner-sdk`

Pop-up z ustawieniami zaawansowanymi ma inne NODY.

**Comment by zaba-monika** [comment]
krystian3w:  zobacz jaka parodia:

- tutaj ukrywa dodatek, a lista nie:
> zaba-monika : https://github.com/MajkiIT/polish-ads-filter/issues/17779#issuecomment-732290084 :  
> (..) - przy okazji ciekawostka: **dodatek** `I don't care about cookies` również to ukrywa, ale ty masz tylko **listę** więc ci nie ukrywa,  (..)

- a tutaj odwrotnie, ukrywa lista, a dodatek nie:

> zaba-monika : https://github.com/MajkiIT/polish-ads-filter/issues/17778#issuecomment-732363626 : 
> (..) po wyłączeniu listy `I don't care about cookies`, a jednocześnie przy wciąż włączonym **dodatku**  `I don't care about cookies` komunikat się pojawia, chyba lista `I don't care about cookies` jest bardziej aktualna od dodatku póki co - 13 dni różnicy (..)

**Comment by zaba-monika** [comment]
> Barticf : https://github.com/MajkiIT/polish-ads-filter/issues/17779#issuecomment-732358580: @zaba-monika mi filmy działają.

Ciekawe jakim cudem, bo mi nie:

<details not-open>
<summary>zrzut ekranu 1</summary>


![capture_047_24-11-2020_09-10-54](https://user-images.githubusercontent.com/72980128/100066225-15decf00-2e35-11eb-8d78-99a32eae7ab8.png)
</details>

Działa dopiero po wyłączeniu EasyList Cookie:

<details not-open>
<summary>zrzut ekranu 2</summary>



![capture_048_24-11-2020_09-13-18](https://user-images.githubusercontent.com/72980128/100066363-4aeb2180-2e35-11eb-91b2-510baeea36fc.png)

</details>

**Comment by Barticf** [comment]
@zaba-monika w trybie prywatnym to odpalam. Na chwilę pojawia się ten komunikat dotyczący ciasteczek ale dzięki PZC zaraz znika. Filmik działają bez problemu

**Comment by zaba-monika** [comment]
> Edit: Jak wyłączę listę "AdGuard Annoyances" ale zostawię "EasyList Cookie" to wtedy pojawia się ten problem o którym piszesz.

- bo jak już pisałam ten błąd naprawiono na listach AdGuard: https://github.com/AdguardTeam/AdguardFilters/issues/68007 i widocznie łatka naprawiająca działa również na błąd w `EasyList Cookie`
