### ISSUE TITLE
instalacjebudowlane.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#17778]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/99973384-fea1d200-2d9f-11eb-81c0-fce356bf338c.png)

### Link bezpośredni 

https://www.instalacjebudowlane.pl/

### Co trzeba zrobić, aby pojawił się błąd?
1. 
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by hawkeye116477** [comment]
Najwyraźniej to jakaś resztka po reklamie.

**Comment by krystian3w** [comment]
Lepiej `#panel`, bo blokada tła nie odblokowuje klikalności u dołu ekranu.

**Comment by zaba-monika** [comment]
Nie wiem czy ktoś zagląda do zamkniętych zgłoszeń / commitów więc wykorzystując istniejące zgłoszenie z błędem, to tu też wkleję na wszelki wypadek : https://github.com/MajkiIT/polish-ads-filter/pull/17776#issuecomment-732261112

**Comment by krystian3w** [comment]
Poprawka w drodze, Orange wymaga zapisu do pliku zip lub HAR*

\* - ale HAR nie umiem przeglądać by sobie wyłapać gdzie filtr proceduralny może się gubić: https://github.com/MajkiIT/polish-ads-filter/blob/a64c4cbea36c912a47a61a427a6aeabf7123ee06/cookies_filters/adblock_cookies.txt#L1224

możliwe, że nie masz np. `opacity` albo nie masz typowego `#__next`

**Comment by zaba-monika** [comment]
- na `orange.pl` przestał się komunikat pojawiać
- pewnie kod komunikatu zmienił się na pasujący do filtra
- a za jakiś czas może zmienić się znowu na niepasujący do filtra i wyskoczy komunikat
- jak upoluję komunikat to zapiszę stronę do pliku / spróbuję sam napisać filtr

**Comment by zaba-monika** [comment]
- to co wyżej nieaktualne
- mam go znowu po wyłączeniu **listy** `I don't care about cookies`, którą miałam włączoną tylko na chwilę w związku z https://github.com/MajkiIT/polish-ads-filter/issues/17779 i zapomniałam wyłączyć, po wyłączeniu listy a jednocześnie przy wciąż włączonym **dodatku**  `I don't care about cookies` komunikat się pojawia, chyba lista `I don't care about cookies` jest bardziej aktualna od dodatku póki co - 13 dni różnicy:
- lista `! Last modified: 23 Nov 2020 08:26 UTC`
- dodatek `Ostatnia aktualizacja 10 listopada 2020`
- po włączeniu **listy** `I don't care about cookies` filtr, ktłóry ukrywa mi komunikat to:
`orange.pl###__next > div > section[role="region"], .opl-cookie-control`

**Comment by krystian3w** [comment]
OK, zobaczymy czy obejdą `:upward(1)` i taką ścieżkę: `:-abp-has(> div > div > strong:-abp-contains(Informacja o cookies))`

`Upward` powinien szybciej ukrywać, więc użytkownicy uBO i AdGuard może nie odczują migania.

**Comment by zaba-monika** [comment]
krystian3w gdy wysłałam swój komentarz: https://github.com/MajkiIT/polish-ads-filter/issues/17778#issuecomment-732363626 to w tym samym momencie pojawił się twój, a nie sądzę, żebyś przeczytał mój drugi komentarz w 1 sekundę, więc myślę, żę odpisałeś na pierwszy, a drugi mogłeś przeoczyć, więc tak tylko informuję.

>> ten komentarz niedługo uleganie autodestrukcji <<

**Comment by krystian3w** [comment]
Pewnie to u niego tymczasowy filtr zanim dodatek zaktualizuje do 3.2.6, ja bym nie ukrywał `section[role="region"]`, bo można wyciąć za dużo.

Zakładam, że w 3.2.6 doda pewnie klikanie, bo już jakieś ma dla `orange.pl`.

**Comment by zaba-monika** [comment]
krysitan3w : [orange.zip](https://github.com/MajkiIT/polish-ads-filter/files/5585275/orange.zip)

**Comment by krystian3w** [comment]
OK, to powinno zadziałać to: https://github.com/MajkiIT/polish-ads-filter/blob/14ad4faaa35abe746ca4d739178e437aae2d4720/cookies_filters/adblock_cookies.txt#L1224 i to: https://github.com/MajkiIT/polish-ads-filter/blob/14ad4faaa35abe746ca4d739178e437aae2d4720/cookies_filters/cookies_uB_AG.txt#L195

na localhost jest 100% dopasowanie dla obu.

**Comment by zaba-monika** [comment]
niestety żadne nie działa

**Comment by zaba-monika** [comment]
dobra sorry, miałam odznaczonego ptaszka przy Moje Filtry, potwierdzam, twoje filtry działają

**Comment by zaba-monika** [comment]
@Barticf już naprawione, możesz zamknąć.
