### ISSUE TITLE
cdahd.co

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17787]
po wejściu na strone taki kwiatek

![Screenshot_1](https://user-images.githubusercontent.com/21177361/100100804-a9c69000-2e61-11eb-93aa-2aeb874b649f.png)

**Comment by zaba-monika** [comment]
- było już naprawione: https://github.com/MajkiIT/polish-ads-filter/issues/17498#issuecomment-717778571
- może MajkiIT zapomniał dodać filtra

**Comment by gzenio22** [comment]
u mnie sie to wyswietla wiec podalem

**Comment by krystian3w** [comment]
0/10  - z umiejętności "czytanie ze zrozumieniem".

Naprawa polegała, że xxcriticxx wkleił sobie do filtrów własnych i o problemie zapomniano.

**Comment by zaba-monika** [comment]
> gzenio22 : https://github.com/MajkiIT/polish-ads-filter/issues/17787#issuecomment-733117805: bu mnie sie to wyswietla wiec podalem

- tłumaczysz się jakbym ci zabraniała...tymczasem  uważam odwrotnie: dobrze, że zgłosiłeś, bo admin po cichu wycofał łatkę i nie poinformował o tym w zgłoszeniu, przez co zostawił stronę z nieubitym anty-adblockiem co jest nieprofesjonalnym zachowaniem
