### ISSUE TITLE
dobregniazdka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#17784]

**Comment by zaba-monika** [comment]
xxcriticxx rozumiem, że podobnie jak gzenio22 tydzień temu: https://github.com/MajkiIT/polish-ads-filter/issues/17641#issuecomment-728798773, tym razem ty dajesz sygnał "do ataku" ciasteczkowego...wiesz nie ma dla mnie problemu, UFO zebrało obfite plony i zapas ciasteczek już czeka na zrzut
