### ISSUE TITLE
powiatkamienski.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17814]
![capture_077_25-11-2020_14-40-08](https://user-images.githubusercontent.com/72980128/100234993-232ab500-2f2c-11eb-8a71-452f1fb2890f.png)
![capture_078_25-11-2020_14-40-09](https://user-images.githubusercontent.com/72980128/100234995-23c34b80-2f2c-11eb-8a1e-2a221b1812d6.png)

**Comment by bug-rules** [comment]
Dawno zrobione, chyba że umiesz arsenałem uBO zrobić to samo:

https://github.com/PolishFiltersTeam/PolishCookieConsent/commit/3c76a26ff90f8cdf0effe8dcfc0f7343ecfdb83a

**Comment by zaba-monika** [comment]
- niby zrobione (https://github.com/MajkiIT/polish-ads-filter/issues/10445) , ale na zrzutach ekranu masz komunikat, to dlaczego się on pojawił...
- wszedłem ponownie teraz i już komunikat się nie pokazuje i przekierowanie działa, więc może to był jakiś jednorazowy glitch...

**Comment by zaba-monika** [comment]
Coś jednak nie masz racji, i macie zabugowane u siebie:
- tu owszem naprawione:  `powiatkamienski.pl`
- ale np. tu wyskakuje `www.powiatkamienski.pl`
