### ISSUE TITLE
darmowa-tv.ws

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17839]
Tym razem mam dla was nietypowego kwiatka bo adblocka wykrywa tylko na Chromowatych w moim wypadku jest to chrome ale sprawdzilem tez na chroperze z kolei na FF czysto 

![Screenshot_1](https://user-images.githubusercontent.com/21177361/100273125-93e9c580-2f5c-11eb-9707-da122b218820.png)

**Comment by zaba-monika** [comment]
U mnie tego nie ma.

**Comment by gzenio22** [comment]
wykrywa mi to na kazdej z list wyłączałem każdą po kolei

**Comment by AroKol78** [comment]
też  "adblock detect"
![db1fix](https://user-images.githubusercontent.com/70756447/99152904-1e047500-26a5-11eb-81aa-d0561833c5ed.PNG)

**Comment by krystian3w** [comment]
W Chrome działa pomysł Bogachenko:

```
darmowa-tv.ws##+js(abort-on-property-write.js, adcashMacros)
||googlesyndication.com^$important,script,redirect=googlesyndication.com/adsbygoogle.js,domain=darmowa-tv.ws
```
Nie wiem czy ruszy on z Firefox 52 ESR (Legacy) z uBO 1.16.X (legacy).

Opera raczej łyknie haczyk z skryptletem i przekierowaniem.

**Comment by gzenio22** [comment]
u mnie na chrome dalej wywala detecta mimo aktualizacji filtrow

**Comment by krystian3w** [comment]
Aktualizacja nie ma sensu aż MajkiIT nie poprosi.

**Comment by gzenio22** [comment]
sorki ten fix wyzej mnie zbił z pantałyku XD

**Comment by zaba-monika** [comment]
- ja dalej nie mam anty-adblocka na Chropera 72 + uBO 1.30.9.rc2
- za to mam go na Firefox 52.9 + uBO Legacy 1.16.4.26, działa dodanie:
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=darmowa-tv.ws`
z jakiś powodów nie działa `redirect`, który jest na liście uBlock więc trzeba po prostu dodać regułę whitelistującą

**Comment by zaba-monika** [comment]
gzenio22 spróbuj zaktualizować listę `uBlock filters`

**Comment by gzenio22** [comment]
@zaba-monika zaktualizowałem i nadal to mam

**Comment by krystian3w** [comment]
Żaba używa **AdGuard Base** pewnie, to się "naprawia".

A ten dalej nie ma statusu wymaganego dla regionu "Polska"  / "strony polskojęzyczne".

**Comment by gzenio22** [comment]
boom potwierdzam pomaga to co podał @krystian3w

**Comment by krystian3w** [comment]
No to jeszcze zostaje opracowanie rozwiązania dla ABP/AdBlock (chyba że tam naprawa robi wyciek reklam...).

Potem ustalenie co z uBO Legacy + Firefox 52.

**Comment by zaba-monika** [comment]
> krystian3w : Żaba używa **AdGuard Base** pewnie, to się "naprawia".

Bzdura:
- nawet bez `AdGuard Base` mi nie wyskakuje anty-adblock, 
- dopiero po wyłączeniu `uBlock filters` się pojawia, 
a po włączeniu `uBlock filters` znika, 
dlatego proponowałam dla `gzenio22` aktualizację listy `uBlock filters`

**Comment by gzenio22** [comment]
w takim razie jakoś dziwnie działa ten detect...

**Comment by krystian3w** [comment]
Czasem są takie źle napisane, że z góry mamy około 10-30% szans na reprodukcje komunikatu.

**Comment by zaba-monika** [comment]
Na takich listach nie mam anty-adblocka:

<details not-open>
<summary>zrzut ekranu</summary>


![44444](https://user-images.githubusercontent.com/72980128/100331584-a1d92e00-2fd0-11eb-859e-c0fc4308ce35.png)

</details>

**Comment by krystian3w** [comment]
Za raz wyjdzie, że to polskie EI, Fanboy Social lub RODO-ciasteczkowe robia anty-adblock.

**Comment by zaba-monika** [comment]
Nie robią, też sprawdzałam z różnymi dodatkowymi listami, które wymieniłeś.

![3333](https://user-images.githubusercontent.com/72980128/100332010-2461ed80-2fd1-11eb-9a99-7a8d132e7e91.png)

**Comment by krystian3w** [comment]
No to zostaje regresja z `redirect-rule` lub daszkiem: `||googlesyndication.com/pagead/js/adsbygoogle.js^`

Daszki niby nadużywała lista norweska i nie było problemów.

Chyba, że strona ma inną ścieżkę do pliku.

**Comment by zaba-monika** [comment]
Z `redirect` kiedyś już wyłapałam błąd w uBO na pewno pamiętasz tę historię: https://github.com/olegwukr/polish-privacy-filters/issues/67

**Comment by zaba-monika** [comment]
> krystian3w : https://github.com/MajkiIT/polish-ads-filter/issues/17839#issuecomment-734174771 : 
> Raczej odpada, że GitHub się przeciążył i dostajemy przestarzałe filtry dla `pagead2.googlesyndication.com` i `darmowa-tv.ws`:
> 
> `23,884 used out of 25,323`

no nie wiem czy odpada..jak widać u mnie na zrzucie ekranu z Chropery jest `24937` filtrów w `uBlock filters` więc chyba ktoś tu ma niezaktualizowaną listę...

**Comment by zaba-monika** [comment]
Czy macie te filtry?:
- https://github.com/uBlockOrigin/uAssets/blob/98f5db9faeaef10dd17416cf2f0fe6e28965a4a4/filters/filters-2020.txt#L5391-L5393
- https://github.com/uBlockOrigin/uAssets/blob/98f5db9faeaef10dd17416cf2f0fe6e28965a4a4/filters/filters-2020.txt#L5808-L5809

**Comment by gzenio22** [comment]
zabrzmi to ciulowo ale jak to sprawdzic? Xd

**Comment by krystian3w** [comment]
Mam wszystkie 3.

@gzenio22  jak masz listę "uBlock filters" to klikasz w oko 👁️, potem w górnej szukajcie sprawdzasz czy masz każde.

Mnie `redirect-rule` nie działa przez ten bezsensowny daszek `^`.

**Comment by zaba-monika** [comment]
> gzenio22 : https://github.com/MajkiIT/polish-ads-filter/issues/17839#issuecomment-734221080 : zabrzmi to ciulowo ale jak to sprawdzic? Xd

No właśnie problem polega na tym, że listy uBlock nie zawierają sygnatury i trudno być pewnym czy ma się aktualną listą, a np. Polskie listy mają sygnatuę, którą dwie osoby mogą sobie porównać: 
https://github.com/MajkiIT/polish-ads-filter/blob/6b869503dceaa607001b4dafa8fc9aae159c662a/polish-adblock-filters/adblock.txt#L11-L13

**Comment by krystian3w** [comment]
Przecież ona nie jest potrzebna, podgląd listy w uBO jest wydajny i wyszukiwarka na pewno znajdzie te filtry sprzed 20 i 36 dni.

**Comment by zaba-monika** [comment]
Acha , czyli po co koparka skoro można kopać łopatą...

**Comment by gzenio22** [comment]
mam wsio

**Comment by krystian3w** [comment]
No to winny dla uBO 1.30.6 jest daszek `^`, od wersji 1.31.X redirect ma niebieski kolor w konsoli i go widać jak każdy inny filtr.

**Comment by zaba-monika** [comment]
https://github.com/gorhill/uBlock/issues/3590#issuecomment-723355988

**Comment by krystian3w** [comment]
W Chrome też wciąż sprawdzają kod:

![Screenshot_2020-11-26 uBlock Origin](https://user-images.githubusercontent.com/35370833/100344029-7cecb700-2fe0-11eb-8e87-fb1524a65f36.png) |
--- |

**Comment by AroKol78** [comment]
używam Basilisk/UXP 52.9.0 20201120 --- uBO Legacy 1.16.4.26
nie Firefox 52 ESR

**Comment by zaba-monika** [comment]
- sama kiedyś gdy zaczęłam używać uBO to siedziałam na oficjalnych wersjach uBO
- ale szybko przekonałam się, że bez względu na to ile błędów naprawiono już w uBO przez lata, to uBO jest dalej tak mocno zabugowany, że zmusza mnie to siedzenia na wersjach dev
- chociaż to działa też w drugą stronę, i każdy kij ma dwa końce: wersje dev potrafią mieć błędy których nie ma w oficjalnych...
- dlatego każdy wybiera to co lubi, jedni wolą siedzieć na oficjalnych, inni na dev

**Comment by krystian3w** [comment]
Tak czy siak zrób testy obu kombinacji @AroKol78:

```
! od AdamWr
darmowa-tv.ws##+js(abort-on-property-read, daau_app)
||googlesyndication.com^$xhr,redirect=noop.txt,domain=darmowa-tv.ws,important
||googlesyndication.com^$script,redirect=googlesyndication.com/adsbygoogle.js,domain=darmowa-tv.ws,important
```
```
! od Bogachenko
darmowa-tv.ws##+js(abort-on-property-write.js, adcashMacros)
||googlesyndication.com^$redirect=googlesyndication.com/adsbygoogle.js,domain=darmowa-tv.ws,important
```

**Comment by krystian3w** [comment]
Tak czy siak zrób testy obu kombinacji @AroKol78:

```
! od AdamWr
darmowa-tv.ws##+js(abort-on-property-read.js, daau_app)
||googlesyndication.com^$xhr,redirect=nooptext,domain=darmowa-tv.ws,important
||googlesyndication.com^$script,redirect=googlesyndication.com/adsbygoogle.js,domain=darmowa-tv.ws,important
```
```
! od Bogachenko
darmowa-tv.ws##+js(abort-on-property-write.js, adcashMacros)
||googlesyndication.com^$redirect=googlesyndication.com/adsbygoogle.js,domain=darmowa-tv.ws,important
```

**Comment by zaba-monika** [comment]
> AroKol78 : https://github.com/MajkiIT/polish-ads-filter/issues/17839#issuecomment-734237882 : 
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=darmowa-tv.ws`
> działa 

Spoko, to gitara.

Hmm nie wiem czy krystian3w robi to po złości, bo już drugi raz odnosząc się do rozwiązania pod uBO legacy, pominął moje rozwiązanie https://github.com/MajkiIT/polish-ads-filter/issues/17839#issuecomment-734160415, pierwszy raz pominął je w ty mkomentarzu: https://github.com/MajkiIT/polish-ads-filter/issues/17839#issuecomment-734170984

**Comment by krystian3w** [comment]
Oleg po prostu zapomni dodać coś takiego:
```
!#if env_legacy

!#endif
```
z dopuszczeniem pod stary Firefox.

**Comment by AroKol78** [comment]
od AdamWr 👍 
od Bogachenko 👎

**Comment by krystian3w** [comment]
Czyli przekierowania da się uruchomić też w legacy, może legacy wymaga 2 lub ma race-condition z `##+js(abort-on-property-write.js, adcashMacros)`

**Comment by AroKol78** [comment]
👍 
! od Bogachenko
darmowa-tv.ws##+js(abort-on-property-write.js, adcashMacros)
||googlesyndication.com^$script,redirect=googlesyndication.com/adsbygoogle.js,domain=darmowa-tv.ws,important

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/b559279f2367470c870f3ff11a160497f5651a83#diff-4a6978b41c01edec9e42a612c659cd9fdd99e12c90dfca77cbd53379c960bb2c

**Comment by gzenio22** [comment]
naprawione zamykam :)

**Comment by bogachenko** [comment]
@krystian3w 
>Skopiuj drugi raz rozwiązanie Bogachenko, wcięło mi script z filtra - teraz też powinien ruszyć.

@AroKol78
> od Bogachenko 👎

It turns out that uBO has a bug (or, in their case, it's a feature) my sheet contained these 2 filters

`||pagead2.googlesyndication.com^$important,script,redirect=googlesyndication-adsbygoogle,domain=...{somedomains}...`
`||pagead2.googlesyndication.com^$important,script,redirect=googlesyndication_adsbygoogle.js,domain=...{somedomains}...`

the `googlesyndication-adsbygoogle` was the **1nd** in a row (FIlter for Adguard)
the `googlesyndication_adsbygoogle.js` was the **2nd** in a row (FIlter for uBO)

So uBO met with the first row of the filter `googlesyndication-adsbygoogle`,  and stopped at the filter that goes first, and which he does not understand, and the filter that is created for uBO `googlesyndication_adsbygoogle.js` (which comes RIGHT after the Adguard filter) it doesn't see.

Adguard understands uBO markup, but not on the contrary.

**Comment by AroKol78** [comment]
od https://github.com/MajkiIT/polish-ads-filter/issues/17839#issuecomment-734145532
> W Chrome działa pomysł Bogachenko:
> 
> ```
> darmowa-tv.ws##+js(abort-on-property-write.js, adcashMacros)
> ||googlesyndication.com^$important,script,redirect=googlesyndication.com/adsbygoogle.js,domain=darmowa-tv.ws
> ```

od https://github.com/MajkiIT/polish-ads-filter/issues/17839#issuecomment-734240381
> ```
> ! od Bogachenko
> darmowa-tv.ws##+js(abort-on-property-write.js, adcashMacros)
> ||googlesyndication.com^$script,redirect=googlesyndication.com/adsbygoogle.js,domain=darmowa-tv.ws,important
> ```

w różnych miejscach
`$important` `,important`

**Comment by krystian3w** [comment]
To nie ten błąd, Bogachenko opisuje swoje doświadczenia, a nie to co się u ciebie stało w Serpent Browser.

**Comment by zaba-monika** [comment]
> AroKol78 :
> w różnych miejscach
> `$important` `,important`

Opcje w filtrach mogą być na dowolnych pozycjach, jest to bez znaczenia i nie jest to traktowane jako błąd, to ma jedynie znaczenie wizualne / czytelność.

**Comment by zaba-monika** [comment]
> AroKol78 : https://github.com/MajkiIT/polish-ads-filter/issues/17948

- ktoś dodał `redirect` z `important` : https://github.com/olegwukr/polish-privacy-filters/commit/4f8fef5f083f264954f35e6bad3f622a0f4e2812

- w ten sposób nadpisując moją regułę whitelistującą, przez co ona nie działa: https://github.com/MajkiIT/polish-ads-filter/issues/17839#issuecomment-734240757
- żeby ominąć anty-adblocka trzeba spowrotem odblokować moją regułę whitelistującą która działała, czyli:
a) usunąć regułę z `redirect` 
b) albo usunąć z niej `important` 
c) a tymczasem ktoś może sobie ją zdezaktywować dodając regułe dezaktywującą z `,badfilter` do Moje Filtry:
`||googlesyndication.com^$script,redirect=googlesyndication.com/adsbygoogle.js,domain=darmowa-tv.ws,important,badfilter`

**Comment by AroKol78** [comment]
👍 **zaba-monika** 🥇 dzięki 


> c) a tymczasem ktoś może sobie ją zdezaktywować dodając regułę dezaktywującą z `,badfilter` do Moje Filtry:
> `||googlesyndication.com^$script,redirect=googlesyndication.com/adsbygoogle.js,domain=darmowa-tv.ws,important,badfilter`

dzała

**Comment by krystian3w** [comment]
Raczej nie ma szans, by `googlesyndication.com/adsbygoogle.js` zostało uaktualnione pod jedną stronę która wie jak go edytować w swoim panelu Google lub sprawdza coś spoza specyfikacji neutralizacji uBO/AdGuard.
