### ISSUE TITLE
plejada.pl

### ISSUE THREAD

**Issue by tom610** [MajkiIT/polish-ads-filter#1785]
Problem adblock: "Reklamy nie sa takie zle"

**Comment by MajkiIT** [comment]
@F4z lookniesz?

Na bank powinno być to 
@@||csr.onet.pl/_s/csr-*/csr.jsx$script

**Comment by MajkiIT** [comment]
@F4z to Plejada proponuje dodać aby nie widzieć tego komunikatu, ale chyba sami się pomieszali, bo nie działa.
`http://lib.onet.pl/s.csr/whitelist/plejada.pl.txt`

**Comment by xxcriticxx** [comment]
tez mam ad block

**Comment by MajkiIT** [comment]
sprawdźcie coś takiego

`@@||plejada.pl^$generichide`
`plejada.pl###extraAdsBlock`
`plejada.pl###onet-ad-float-div`

**Comment by F4z** [comment]
@MajkiIT ta reguła - `@@||plejada.pl^$generichide` - u mnie działa.
Pod komentarzami mam reklamy, z tego samego powodu co tutaj - https://github.com/MajkiIT/polish-ads-filter/issues/1778#issuecomment-269648584

**Comment by xxcriticxx** [comment]
reklamy przed komentarzem

`http://plejada.pl/flesz-celebrycki-extra-patryk-vega-o-swoim-nawroceniu-punktem-zwrotnym-byl-wypadek-w/smst6w`

![capture](https://cloud.githubusercontent.com/assets/15007183/21551991/7c79f438-cdcc-11e6-96dd-e8704be578fc.PNG)

**Comment by F4z** [comment]
@MajkiIT nadal czasami mam komunikat o adblocku.

![image](https://cloud.githubusercontent.com/assets/11742596/21567135/07818338-ceaa-11e6-949d-97ef90cca6db.png)

Więc myślę, że ta reguła - `@@||plejada.pl^$generichide` - też powinna zostać dodana.

Odnośnie tych reklam pod komentarzami, to u mnie czasami się jeszcze pokazują.
Ta reguła powinna je zablokować, ale może też popsuć funkcjonalność strony:
`||sgqcvfjvr.onet.pl^$script,domain=plejada.pl`
Dlatego myślę, że chyba lepiej je będzie po prostu ukryć:
`plejada.pl##div[id^="multi-"] > iframe[id^="iframe-multi-"]`

**Comment by MajkiIT** [comment]
Poprawione. Dzięki
