### ISSUE TITLE
pudelekx.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1786]
ad block 

`http://pudelekx.pl/emily-ratajkowski-wygina-sie-w-wannie-61026`

![capture](https://cloud.githubusercontent.com/assets/15007183/21550965/d514cfba-cdcb-11e6-83a9-e48dab027d19.PNG)

**Comment by F4z** [comment]
Powinno wystarczyć:
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=pudelekx.pl`

**Comment by xxcriticxx** [comment]
@F4z dziala ale jest 15 sec reklama zanim film sie zacznie albo jest tak nagrany z reklama

**Comment by F4z** [comment]
@xxcriticxx to jest tak nagrane.

**Comment by xxcriticxx** [comment]
@F4z thx regula jest dobra
