### ISSUE TITLE
*.wp.pl (20 stron)

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17877]
@ admin

- wysypało reklamy na kilkunastu domenach WP, naprawa:

### 1
- te strony
`abczdrowie.pl,autokult.pl,echirurgia.pl,film.wp.pl,fotoblogia.pl,gadzetomania.pl,gry.wp.pl,horoskop.wp.pl,kobieta.wp.pl,komorkomania.pl,medycyna24.pl,money.pl,parenting.pl,pogoda.wp.pl,tech.wp.pl,tv.wp.pl,twojeip.wp.pl,wiadomosci.wp.pl,wideo.wp.pl,www.wp.pl`
doklejamy do tej reguły:
https://github.com/MajkiIT/polish-ads-filter/blob/e46701e96abcfe846dc60530078d239a4086deb0/polish-adblock-filters/adblock_ublock.txt#L208

### 2
- z `AdGuard Base` dodatkowo dodajemy regułę, która również usuwa reklamy, 
bo co dwie reguły usuwające reklamy, to nie jedna, więc może potrzyma dłużej na tych 2 stronach: 
`sportowefakty.wp.pl,www.wp.pl##+js(aopr, Object.prototype.bodyCode)`

### 3
- z powodu uwalonych video w artykułach usuwamy strony: `autokult.pl,fotoblogia.pl,gadzetomania.pl,komorkomania.pl` z tych reguł:
https://github.com/MajkiIT/polish-ads-filter/blob/e46701e96abcfe846dc60530078d239a4086deb0/polish-adblock-filters/adblock_ublock.txt#L203-L204

- przykład uwalonego video https://autokult.pl/39488,kia-ceed-dostala-nowy-naped-1-5-t-gdi-zastapi-dotychczasowe-1-4-i-moze-byc-miekka-hybryda

<details not-open>
<summary>zrzut ekranu 1 video popsute</summary>

![capture_146_27-11-2020_17-31-56](https://user-images.githubusercontent.com/72980128/100469426-7b051f80-30d6-11eb-8062-98d51b96e2f2.png)

</details>

<details not-open>
<summary>zrzut ekranu 2 video działające</summary>

![capture_147_27-11-2020_17-33-45](https://user-images.githubusercontent.com/72980128/100469562-b4d62600-30d6-11eb-9547-b5561fa335a6.png)

</details>

### 4 

<details not-open>
<summary>przykładowy zrzut ekranu reklamy na www.wp.pl
</summary>

![11111](https://user-images.githubusercontent.com/72980128/100441196-5c873000-30a6-11eb-9b64-8a134d4835a6.png)
![22222](https://user-images.githubusercontent.com/72980128/100441202-5ee98a00-30a6-11eb-8870-2ea29f21d732.png)
![3333](https://user-images.githubusercontent.com/72980128/100441204-601ab700-30a6-11eb-9ed0-799211376015.png)
</details>

powiązane z https://github.com/MajkiIT/polish-ads-filter/issues/13818

**Comment by xxcriticxx** [comment]
@zaba-monika thank you!

**Comment by 0xtrzy** [comment]
dobreprogramy.pl też

**Comment by zaba-monika** [comment]
@MajkiIT
- zapomniałam napisać, że na puste szare kontenery po reklamach, na niektórych stronach WP, trzeba jeszcze będzie dodać jakieś kosmetyki, ale to już jutro wymyślę i podam

@0xtrzy
- jeśli chodzi o `dobreprogramy.pl` to nie widzę tam reklam...zaktualizuj listy i sprawdź jeszcze raz, 
- a jeśli dalej masz reklamy to:
a) albo masz Adblock Plus, z którym obecnie dodane reguły nie sa kompatybline (są one tylko pod uBO / AG),  więc trzeba będzie wymyślić /przepisać reguły pod ABP i zgłosić je tu żeby dodali: https://github.com/abp-filters/abp-filters-anti-cv
b) albo masz jakieś nietypowe ustawienia: przeglądarka ? adblocker? lub coś skopane po twojej stronie

Z wyżej wymienionych powodów zostawiam zgłoszenie otwarte na jutro.

**Comment by zaba-monika** [comment]
Dalej odnośnie `dobreprogramy.pl` w https://github.com/MajkiIT/polish-ads-filter/issues/17631:
- chłopaki chyba pobłądzili, więc trochę ich naprostuję
- najpierw została dodana moja reguła:
 `www.dobreprogramy.pl##+js(nostif, PrebidDamOpen, 800)`, 
która trzymała przez ileś dni
- w końcu przestała trzymać więc została dodana reguła z AdGuard: 
`www.dobreprogramy.pl##+js(set-constant, Object.prototype.advViewability, undefined)`
która również trzymała przez ileś dni
- a teraz również i ona przestała trzymać, ale znowu z kolei zaczęła trzymać moja...
- a żeby było jeszcze ciekawiej, to kolejna reguła z AdGuard: 
`www.dobreprogramy.pl##+js(aopr, Object.prototype.bodyCode)` również działa
- więc różne reguły trzymają warty na zmianę...i to jest przykład, 
że warto trzymać wszystkie reguły (jeśli nic nie psują), 
bo czasem nowe przestają działać, a spowrotem
zaczynają działać stare i tak na zmianę...
- w tej chwili dla `www.dobreprogramy.pl` w POL filtrach są dodane:
 `www.dobreprogramy.pl##+js(nostif, PrebidDamOpen, 800)`, 
` www.dobreprogramy.pl##+js(set-constant, Object.prototype.advViewability, undefined)`
i póki co tylko ta pierwsza (moja) działa, ale to się może w każdej chwili znowu zmienić...
- jeśli dla @ 0xtrzy wyskakują reklamy to może z powodu przeglądarki Brave albo ma coś skopane u siebie,
tak czy inaczej tylko u niego są reklamy więc to pojedyczny przypadek i raczej coś u niego...
może spróbować dodać 3-cią regułę: `www.dobreprogramy.pl##+js(aopr, Object.prototype.bodyCode)`
ale pewnie też nie zadziała u niego bo coś ma skopane u siebie i nawet gdy doda 10 regułą to żadna mu nie zadziała..

**Comment by zaba-monika** [comment]
@MajkiIT 

Na puste szare kontenery po reklamach:
- doklejamy `money.pl,wideo.wp.pl` do
https://github.com/MajkiIT/polish-ads-filter/blob/27aaab65ba08bd6215cb953c278e9b566b1c2bd9/polish-adblock-filters/adblock_ublock.txt#L214
- oraz dodajemy te reguły:
`tv.wp.pl##div[height="auto"]:upward(1)`
`parenting.pl,abczdrowie.pl##[class^="content-aside__"], div[class^="article "], div[class^="article__textbox "]`
- na kontenery na `pogoda.wp.pl` i `praca.money.pl` wynalezienie reguł będzie musiało poczekać bo nie jest tak łatwo

**Comment by zaba-monika** [comment]
@MajkiIT sorry głupia literówka w jednej z moich reguł : https://github.com/MajkiIT/polish-ads-filter/commit/6e6687687a693b4174db792470f29d2862329eca#r44617272

**Comment by zaba-monika** [comment]
> zaba-monika : https://github.com/MajkiIT/polish-ads-filter/issues/17877#issuecomment-735219533 : 
> - na kontenery na `pogoda.wp.pl`  i niektóre na `money.pl` 
> wynalezienie reguł będzie musiało poczekać bo nie jest tak łatwo

@MajkiIT właśnie wynalazłam:

`pogoda.wp.pl#?#.desktop > div[class*=" "]:-abp-has(div)`
`www.money.pl###app > div > div:matches-css(background-image: /^url\("https:\/\/v\.wpimg\.pl/)`

**Comment by zaba-monika** [comment]
@MajkiIT 

- dopiero zauważyłam, że jeszcze tu od pyty ich jest: 
- https://pogoda.wp.pl/pogoda-na-dzis/huaycuyo/3938973
- tu też jakiś https://pogoda.wp.pl/mapa

`pogoda.wp.pl##li > .item + div[class*=" "]`
`pogoda.wp.pl##.grid-right > div:matches-css(background-image: /data:image\/png;base64,/)`

**Comment by zaba-monika** [comment]
- tutaj https://github.com/MajkiIT/polish-ads-filter/issues/17877#issue-752161159 (punkt 3) były usuwane domeny z dwóch filtrów `+js` bo było popsute video w artykułach no i niestety okazało się, że `o2.pl` też trzeba usunąć bo też uwalone video np. tu: https://www.o2.pl/informacje/obraz-wywolal-burze-artysta-namalowal-jaroslawa-kaczynskiego-i-nie-tylko-jego-6561681578908544a

<details not-open>
<summary>zrzut ekranu 1 video popsute</summary>


![capture_225_08-12-2020_14-47-24](https://user-images.githubusercontent.com/72980128/101496453-0fd70b00-396a-11eb-8de2-aa50aba23463.png)

</details>

<details not-open>
<summary>zrzut ekranu 2 video działające</summary>



![capture_226_08-12-2020_14-51-07](https://user-images.githubusercontent.com/72980128/101496463-14032880-396a-11eb-9c2f-9609b95eb689.png)

</details>

- ale na szczęście reklam nie wysypie bo trzyma inny filtr:
https://github.com/MajkiIT/polish-ads-filter/blob/6af2612158453f03b7d7a9f201680f2ec77e0213/polish-adblock-filters/adblock_ublock.txt#L207

**Comment by zaba-monika** [comment]
> zaba-monika : https://github.com/MajkiIT/polish-ads-filter/issues/17877#issuecomment-740655203 : 
> - ale na szczęście po wykluczeniu domeny reklam nie wysypie bo jakieś inne filtry trzymają

jednak wysypało reklamy, ale dziwne bo gdy sprawdzałam wcześniej to nie było

**Comment by zaba-monika** [comment]
@MajkiIT 

- ten cały filtr do usunięcia / zakomentowania:
https://github.com/MajkiIT/polish-ads-filter/blob/463ef98815143e6cc80e67b24b271ee7466551cb/polish-adblock-filters/adblock_ublock.txt#L198

- bo psuje video, zdjęcia i komentarze w artykułach na wielu domenach WP
- przykłady zepsucia:

 https://autokult.pl/39611,test-bmw-530e-g30-opinia-dane-techniczne:

<details not-open>
<summary>zrzut ekranu 1</summary>



![obraz](https://user-images.githubusercontent.com/72980128/101624129-c645f900-3a19-11eb-823a-af2b4af5997e.png)
</details>

https://wiadomosci.wp.pl/koronawirus-w-polsce-ministerstwo-zdrowia-o-nowych-przypadkach-9-grudnia-6584327338953440a

<details not-open>
<summary>zrzut ekranu 2</summary>



![43333](https://user-images.githubusercontent.com/72980128/101624314-11f8a280-3a1a-11eb-9a1a-e9fa549d4eb9.png)
</details>

**Comment by zaba-monika** [comment]
- niektóre domeny (np. wspomniany w poprzednim komentarzu `autokult.pl`) dalej są uwalone także przez następny filtr, który również trzeba usunąć albo zakomentować:
https://github.com/MajkiIT/polish-ads-filter/blob/463ef98815143e6cc80e67b24b271ee7466551cb/polish-adblock-filters/adblock_ublock.txt#L171

**Comment by zaba-monika** [comment]
- okazało się, że niektóre domeny (np. wspomniany w poprzednim komentarzu `autokult.pl`) dalej są uwalone także przez następny filtr, który również trzeba usunąć albo zakomentować:
https://github.com/MajkiIT/polish-ads-filter/blob/463ef98815143e6cc80e67b24b271ee7466551cb/polish-adblock-filters/adblock_ublock.txt#L171

**Comment by zaba-monika** [comment]
@MajkiIT 

- jako, że dwa filtry `+js` zostały wyłączone bo psuły strony, to na kilku stronach wyskoczyły reklamy, ale na szczęście wystarczy dokleić te strony `fitness.wp.pl,wawalove.wp.pl,gwiazdy.wp.pl,teleshow.wp.pl` do mojego jeszcze trymającego i póki co niepsująego filtra:
https://github.com/MajkiIT/polish-ads-filter/blob/da032cfda37ad2541028158df254535895598fd7/polish-adblock-filters/adblock_ublock.txt#L207

**Comment by zaba-monika** [comment]
@bug-rules a z tym: https://github.com/MajkiIT/polish-ads-filter/issues/13818#issuecomment-741679536to co dokładnie zrobić żeby zreprodukować

**Comment by zaba-monika** [comment]
@MajkiIT 

- tu kolejny problem https://github.com/MajkiIT/polish-ads-filter/issues/13818#issuecomment-741982041, uwalona główna WP (po paru sekundach biała strona i rdzeń procesora na 100%), na szybko sprawdziłam na kolanie podane łatki i działają więc `www.wp.pl` do wykluczenia z tych filtrów / filtry do dezaktywacji / usunięcia, ale dokładniej tego nie badałam bo już czas spać:

<details not-open>
<summary>zrzut ekranu</summary>


![capture_017_09-12-2020_21-50-23](https://user-images.githubusercontent.com/72980128/101685855-8a865000-3a68-11eb-9405-d0e69ca62ba8.png)
</details>

**Comment by zaba-monika** [comment]
@ admin

- jako, że po naprawie `www.wp.pl` wyskoczyły rekalmy, to dodajemy domenę do:
https://github.com/MajkiIT/polish-ads-filter/blob/da032cfda37ad2541028158df254535895598fd7/polish-adblock-filters/adblock_ublock.txt#L207

**Comment by felix-22** [comment]
Co do reklam na `www.wp.pl` (https://github.com/MajkiIT/polish-ads-filter/issues/13818#issuecomment-745253923) i `www.o2.pl` (https://github.com/uBlockOrigin/uAssets/issues/8261#issuecomment-747535306)
- po włączeniu listy `AdGuard Base` nie ma reklam na `www.wp.pl` i `www.o2.pl` w Opera/Chromebrowsers, na Firefox dalej są niestety
- jeśli chodzi o `www.wp.pl` to naprawili reklamy filtrem: `www.wp.pl##+js(abort-on-property-read, __headpayload)`
- jeśli chodzi o `www.o2.pl` to nie wiem którym filtrem, ale nie był to `+js`, może ktoś wyciągnie filtry którymi naprawili `www.o2.pl`

**Comment by Lukjan38** [comment]
znow sa reklamy :(
