### ISSUE TITLE
Huawei

### ISSUE THREAD

**Issue by mariusz689** [MajkiIT/polish-ads-filter#17875]
Witajcie, ktoś wrzucił na wykopie link do waszego forum i jestem.
Mój problem dotyczy Huawei, opisałem swój problem na forum AdGuard ale bez odzewu. link do mojego wątku: https://forum.adguard.com/index.php?threads/huawei-inverter-fusionsolar.40272/ 

Używam filtru AdGuard poprzez DNS na mikrotiku.

Opiszę na czym polega problem, może ktoś go tutaj rozwiąże, lub ma kolegów którzy zajmują się filtrami adguard lub po prostu wskaże gdzie mam się udać z problemem.

Mam falownik Huawei do paneli fotowoltaicznych który jest cały czas podpięty do internetu aby przesyłać statystyki i monitorować pracę falownika. Używam też aplikacji na telefonie Fusionsolar aby łączyć się z falownikiem i oglądać historię produkcji prądu. Można się zalogować przez przeglądarkę do fusionsolar i też oglądać historię i stan falownika. 
Problem polega na tym że filtr adguard który blokuje reklamy poprzez serwer dns blokuje również połączenie falownika z internetem. Blokuje aplikację fusionsolar na andorida ale nie blokuje zarządzania na stronie fusionsolar poprzez przeglądarkę.

**Comment by xxcriticxx** [comment]
@mariusz689 napewno cos musisz dodac do whitelisty tylko jest pytanie co?

cc @MajkiIT mikrotik twoje tematy 

cc @AdamWr moze cos pomoze te sprawe po pchac

**Comment by gzenio22** [comment]
trzymam kciuki żeby chłopaki doszli o co biega :)

**Comment by mariusz689** [comment]
Ustawień używałem ze strony: https://adguard.com/pl/adguard-dns/overview.html
a dokładniej używam DNS: 94.140.14.14

Mogę spróbować zobaczyć w Mikrotik za pomocą "Torch"  z jakimi adresami IP chce łączyć się telefon podczas uruchamiania aplikacji fusionsolar, oraz sprawdzić z jakimi IP chce łączyć się falownik Huawei - jeśli ma to ułatwić rozwiązanie problemu. Dzięki za szybką odpowiedź :)

**Comment by xxcriticxx** [comment]
Próbowałeś zmienić na server Google? 8.8.8.8 and/or 8.8.4.4?

**Comment by krystian3w** [comment]
IP może wiele nie pomóc jak nie damy rady do niego dopasować np. domeny jak twórcy aplikacji takiej używają.

Podgląd listy AdGuard: https://filters.adtidy.org/windows/filters/15.txt

**Comment by MajkiIT** [comment]
@mariusz689 czyli podsumowując ... masz na MT ustawiony ich DNS do filtracji reklam a przy okazji blokuje ci domeny związane z zarządzaniem Falownikiem ?

**Comment by krystian3w** [comment]
Tak, a AdGuard pewnie nie zakupił ich to nawet nie ma jak testować czy są w stanie namierzyć błędny filtr/blokadę.

**Comment by MajkiIT** [comment]
No to trzeba zobaczyć na zewn DNS zobaczyć na jaki adres IP rozwiązuje się domena i zrobić wpis statyczny na MT. To powinno ominąć filtrację.

**Comment by mariusz689** [comment]
Nie trzeba kupować falownik Huawei aby zbadać problem. Wystarczy pobrać na telefon z androidem aplikację FusionSolar, w pole nazwa użytkownika wpisać jakiś losowy mail oraz w pole hasła też cokolwiek wpisać i kliknąć w "Zaloguj się" wtedy pojawia się komunikat na górze "Sieć działa nieprawidłowo. Podłącz telefon do internetu".
Gdy dane nie lecą przez filtr DNS adguard gdy zrobimy to samo co powyżej, zwrócony zostanie komunikat o błędnym loginie i haśle - czyli w tym przypadku jest komunikacja z serwerem.
Podejrzewam że na Falowniku Huawei jest system android i zarówno aplikacja w telefonie jak i w falowniku działa na takiej zasadzie ponieważ logując się na stronę https://eu5.fusionsolar.huawei.com/ aby sprawdzić w czasie rzeczywistym pracę falownika mogę to sprawdzić. Podejrzewam, że falownik łączy się z jakimś serwerem X na którym są przechowywane informacje o pracy mojego falownika oraz łączy się z serwerem Y - nie wiem w jakim celu, może w celu sprawdzenia aktualizacji czy czegoś tam jeszcze. Serwer Y jest blokowany w taki sposób, że aplikacja w telefonie jak i falownik odrzuca całkowicie połączenie z internetem i zwraca błąd połączenia z internetem. 

Czy w takiej sytuacji mam coś zrobić czy czekać na wasze zbadanie i rozwiązanie problemu ? 

@MajkiIT - dokładnie tak, sytuację opisałem powyżej wynika z niej, że blokuje działanie tej aplikacji ale z wyjątkiem dostępu do konta poprzez przeglądarkę www

@krystian3w podejrzewam że problem jest mało popularny lub nikt wcześniej nie zwrócił uwagi że adguard blokuje działanie tej aplikacji. Chyba nikt wcześniej nie użył takiej konfiguracji aby na mikrotik ustawić dns adguard do blokowania reklam i do tego podłączyć jeszcze falownik Huawei.

**Comment by zaba-monika** [comment]
> krystian3w : https://github.com/MajkiIT/polish-ads-filter/issues/17875?_pjax=%23js-repo-pjax-container#issuecomment-734681339 : Podgląd listy AdGuard: https://filters.adtidy.org/windows/filters/15.txt

- wiem, że to nie IP, ale znalazłam takie blokowane domeny:
`||libfre.obs.cn-east-3.myhuaweicloud.com^`
`||teslaamg.obs.cn-east-3.myhuaweicloud.com^`

- a tu ktoś założył jakieś zgłoszenie Huawei: [LINK](https://github.com/AdguardTeam/AdguardFilters/issues?q=is%3Aissue+in%3Atitle+huawei+label%3A%22T%3A+Incorrect+Blocking%22)

**Comment by MajkiIT** [comment]
@mariusz689 a czemu nie chcesz zacząć używać pihole ?

**Comment by krystian3w** [comment]
Może nie ma malinki lub gdziekolwiek go postawić.

**Comment by MajkiIT** [comment]
@krystian3w No możliwe ... :D

**Comment by mariusz689** [comment]
@zaba-monika Podczas uruchamiania aplikacji fusionsolar w telefonie, sprawdziłem w Mikrotik przez Torch, że bardzo często podczas uruchamiania aplikacji generowany jest ruch z adresem IP: 103.235.46.39:443, pojawiają się też inne IP ale generują mniejszy ruch i mogą być zwykłym szumem.
Próbowałem na Mikrotik przez Layer7 wychwycić pakiety z fusionsolar ale jak widać ruch jest szyfrowany przez https więc nie sprawdzę co siedzi w tym pakietach. 

@MajkiIT Nie mam malinki. Może kiedyś kupię i się nim pobawię :)  Czy pihole lepiej blokuje reklamy niż adguard ? blokuje też reklamy na filmikach na youtube ? Wiem że adguard nie potrafi blokować reklam na YT. Kiedyś czytałem na forum adguard, że nie mogą blokować reklam na yt, bo na tym samym serwerze z reklamami stoją też normalne strony. 

Myślicie, że coś da się zrobić z tym adguard i problemem z fusionsolar ?

**Comment by zaba-monika** [comment]
> mariusz689 : z adresem IP: 103.235.46.39:443

- https://reverseip.domaintools.com/search/?q=103.235.46.39 w wersji darmowej  wyświetliło 3 domeny: 
`045111.com`, `1809.com`, `1869.com`, ale żadnej z nich nie ma blokowanej w 
https://filters.adtidy.org/windows/filters/15.txt
- https://ipinfo.io/103.235.46.39 mówi, że jest 58 domen, ale w wersji darmowej wyświetliło tylko 16:

`045111.com,2008.com,66linux.com,game1322.com,huiji.xyz,intlbp.com,jisentrip.com,kissnet.gq,magicdd.xyz,peilily.top,qinggerui.com,rainbowangle.com,www.66linux.com,www.qinggerui.com,www.rainbowangle.com,xiangyunvps.cn` 
ale również żadnej z nich nie ma na liście

> mariusz689 : Czy pihole lepiej blokuje reklamy niż adguard ? blokuje też reklamy na filmikach na youtube ?

- niektórych reklam nie da się zablokować na poziomie domeny ( za pomocą hosts / dns ), 
bo na tych samych serwerach mogą leżeć pliki potrzebne do działania strony i zablokowanie tych plików uwali stronę
- w tym przypadku niezbędne jest blokowanie na poziomie żądań, czyli np. za pomocą adblockerów, czyli np. 
a) jedno żądanie z tej samej domeny blokujemy: `www.strona.pl/reklamy` bo to są reklamy, 
b) a drugie przepuszczamy `www.strona.pl/filmy` bo to są filmy, 
c) jak widzisz dodanie `www.strona.pl` jest zbyt ogólne bo uwali nie tylko reklamy, ale też filmy...więc to leczenie dżumy cholerą...
- czasem nawet `www.strona.pl/reklamy` nie pomoże bo trzeba użyć skryptów javascript dostępnych w adblockerach / menedżerach skryptów, przykad: strony z grupy WP np.: `https://github.com/MajkiIT/polish-ads-filter/issues/17877`

**Comment by xxcriticxx** [comment]
pihole możesz temp zainstalować na docer albo vm

**Comment by mariusz689** [comment]
@zaba-monika używam blokowania reklam dns adguard oraz mam wtyczkę ghostery w przeglądarce, chyba dobra wtyczka? czy może używacie innej wtyczki do blokowania reklam ?

Wczoraj wieczorem, włączałem i wyłączałem aplikację fusionsolar na telefonie i patrzyłem jakie adresy IP pojawiają się w Torch na Mikrotiku. Podczas mozolnego włączania i wyłączania fusionsolar na telefonie, może za 20 razem aplikacja się uruchomiła poprawnie i działała tak jak powinna (przypuszczam, że aplikacja "czasami" próbuje się połączyć z innym lustrzanym serwerem w przypadku problemu z połączeniem "i ten lustrzany" serwer nie jest zablokowany. W tym przypadku gdy fusionsolar zadziałał był generowany większy ruch z adresami IP: 90.84.191.21:443 oraz 103.235.46.39:443
(Adres IP 103.235.46.39:443 pojawiał się chyba zawsze przy próbie odpalenia fusionsolar - nawet w tym przypadku gdy działał oraz nie działał)

Bardzo często pojawiał się też adres IP: 104.193.88.77:443 a według strony ipinfo na tym adresie ip stoi ponad 17 tys domen.

Nie mam więcej pomysłów jak rozwiązać problem. Nie jestem programistą jedynie hobbystycznie zajmuję się siecią i ustawieniami na mikrotik. Pewnie programiści z adguard rozwiązaliby problem w 5 minut lub przynajmniej udzielili odpowiedzi dlaczego fusionsolar jest zablokowany.

@zaba-monika Podałaś w poprzednim poście:
||libfre.obs.cn-east-3.myhuaweicloud.com^
||teslaamg.obs.cn-east-3.myhuaweicloud.com^

Czy można sprawdzić to na jakim adresie IP stoi ?

**Comment by zaba-monika** [comment]
> mariusz689 : @zaba-monika używam blokowania reklam dns adguard oraz mam wtyczkę ghostery w przeglądarce, chyba dobra wtyczka? czy może używacie innej wtyczki do blokowania reklam ?

- używamy lepszych wtyczek niż [Ghostery](https://pl.wikipedia.org/wiki/Ghostery), Ghostery to nic innego jak lista hosts, czyli to o czym pisałam wyżej - blokowanie na poziomie domen, większosć reklam i tropicieli wybije, ale np. wejdź na jakąś stronę WP np. www.wp.pl - będziesz miał reklamy, i na wielu innych stronach www też, my używamy rozszerzeń przeglądarkowych [uBlock Origin](https://pl.wikipedia.org/wiki/UBlock_Origin) lub [AdGuard](https://adguard.com/pl/adguard-browser-extension/overview.html) tudzież [AdBlock Plus](https://pl.wikipedia.org/wiki/Adblock_Plus), które są bardziej zaawansowane i usuwają reklamy prawie ze wszystkich stron www.

> mariusz689 : a według strony ipinfo na tym adresie ip stoi ponad 17 tys domen.

- no to skoro aż tyle to w ten sposób do niczego nie dojdziemy za dużo domen do sprawdzenia, zresztą i tak pokazuje tylko kilkanaście w wersji darmowej.

> mariusz689 : Pewnie programiści z adguard rozwiązaliby problem w 5 minut lub przynajmniej udzielili odpowiedzi dlaczego fusionsolar jest zablokowany.

- spróbuj zgłosić tutaj: https://github.com/AdguardTeam/AdguardFilters/issues

> mariusz689 : @zaba-monika Podałaś w poprzednim poście: Czy można sprawdzić to na jakim adresie IP stoi ?

- można np. tu: http://domaintoipconverter.com/index.php
Your Results:
`libfre.obs.cn-east-3.myhuaweicloud.com > 119.3.120.60`
`teslaamg.obs.cn-east-3.myhuaweicloud.com > 121.36.239.130`

**Comment by xxcriticxx** [comment]
@mariusz689 masz system na windows? Ta wtyczka pokaze tobie co trzeba whitelistowac do danej strony. 

https://chrome.google.com/webstore/detail/adamone-assistant/fdmpekabnlekabjlimjkfmdjajnddgpc?hl=en

**Comment by zaba-monika** [comment]
Niby można spróbować zwhitelistować te domeny, chociaż on z tego co pisał to nie ma problemu z logowaniem sie przez stronę, a jedynie przez apkę... więc apka chyba korzysta z jeszcze jakiś innych serwerów.

**Comment by krystian3w** [comment]
Niby Huwei FusionSolar wymaga połączeń z `www.baidu.com` (nie są blokowane)
niby używa nawet jakiegoś CNAME "`a.shifen.com`" (nie jest blokowane)

>`rekord A, 103.235.46.39` - CNAME `a.shifen.com` / `www.shifen.com`
>`103.235.46.39:443` - niby `www.baidu.com` (bez szyfrowania po https jak się w przeglądarce otwiera).


Na tyle ile logger aplikacji wskazał to AdGuard DNS robi 20-61 sekundowy lag (ping np. 60678 ms) dla zapytania na serwer główny "Baidu".

Niby te zapasowe szybciej odpowiadają.

Jak umiecie MT zrobić takie coś `baidu.com:103.235.46.39`, to zróbcie.

**Comment by MajkiIT** [comment]
@mariusz689 a nie możesz zrobić na falownika oddzielnej sieci wifi na chwilę. Dla tej sieci ustawić serwer DNS ten który jest na MT . Dla obecnej sieci ustawić na DHCP DNS IP serwerów Adgurd. Wtedy będziesz widział w DNS cache do czego łączył się falownik.

**Comment by xxcriticxx** [comment]
```
Match found in https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt:
   a.shifen.com 
   www.a.shifen.com 
```

**Comment by krystian3w** [comment]
AdGuard w logu robi na czerwono jak jest blokowany. 

Ja widzę na szaro, czyli AdGuard nie stosuje projektu `anudeepND/blacklist`.

---

Obstawiałbym, że `103.235.46.39` to serwer głównie w Chinach, stąd taki lag sięgający do 60 sekund.

**Comment by xxcriticxx** [comment]
`No results found for 103.235.46.39 within the block lists`

**Comment by mariusz689** [comment]
@MajkiIT Nie wiem czy ustawiłem DNS serwer tak jak chciałeś, ale przy prawie chwilowo zerowym ruchu na mikrotiku i wyczyszczeniu listy dns, pojawiły się takie wpisy. Przez Torch zaobserwowałem, że falownik co jakiś czas chyba około jednej minuty lub dłużej (nie sprawdzałem dokładnie) generuje ruch z IP: 90.84.191.21:27251 (który trwa jedną sekundę). 

![huawei](https://user-images.githubusercontent.com/75099245/100524993-55067a80-31bd-11eb-86f7-782e6b52b272.png)

**Comment by MajkiIT** [comment]
`https://forum.huawei.com/enterprise/en/configuration-for-fusionsolar-in-smartlogger-1000-and-1000a/thread/603206-100027`

**Comment by krystian3w** [comment]
Ja tam dalej upieram się, że logowanie sprawdzają gdzieś w Chinach z serwerem Baidu.

**Comment by AroKol78** [comment]
huawei is made in china (baidu/alibaba)

**Comment by mariusz689** [comment]
@MajkiIT widać, że ktoś poruszył temat odnośnie tego IP. Tam było coś o zmianie parametrów na falowniku połączenia do serwera? Dlaczego miałbym coś zmieniać na falowniku? Falownik łączy się przez ten sam ISP, problem pojawia się wtedy gdy ruch puszczę przez DNS AdGuard.

@krystian3w Gdy sprawdzałem z jakimi IP łączy się falownik, obserwacje zacząłem prowadzić gdy już falownik połączył się na testowy wifi. Może w chwili pierwszego połączenia łączy się z innymi serwerami w celu autoryzacji konta a później łączy się tylko z 90.84.191.21  w celu synchronizacji ?

**Comment by zaba-monika** [comment]
- możesz utworzyć zgłoszenie tutaj:
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues
- możesz załadować do telefonu własny plik hosts / DNS AdGuard:
 https://github.com/r-a-y/mobile-hosts/blob/master/AdguardDNS.txt
następnie metodą bisekcji usuwaj część wpisów przed każdą próbą użycia apki 
najpierw usuń połowę wpisów z pliku hosts, żeby zobaczyć, w której połowie coś blokuje
potem połowę połowy, żęby mieć ćwiartkę itd. aż dojdziesz do domen które uwalają apkę

**Comment by MajkiIT** [comment]
@mariusz689 no mnie ciekawi gdzie się łączy dokładnie ten falownik. Przydał by się rejestr chronologiczny z listą jakie domeny są blokowane itp. Najlepiej tak jak napisał @zaba-monika ustawić listę Adgurd DNS i patrzyć co blokuje. Na razie to zgadujemy i bazujemy na tym co się ujawni.

**Comment by krystian3w** [comment]
Nic nie jest blokowane, DNS nie wyrabia i robi się lag 20000 - 60000 ms, przez co aplikacja myśli że nie ma internetu.

**Comment by mariusz689** [comment]
Załadowałem ten filtr DNS i coś takiego się zrobiło 
![Screenshot_2020-11-29-21-13-21-176_com adguard android contentblocker](https://user-images.githubusercontent.com/75099245/100552583-7b451c80-3288-11eb-8337-bdbdfa0a2d90.jpg)
Czy poprawnie lista została załadowana ?

**Comment by krystian3w** [comment]
Źle, załadowałeś kod html jako filtry własne.

Jak dla mnie winny jest czas odpowiedzi ze serwera wynoszący 20-60 sekund, apka pewnie przewiduje opóźnienie maksymalnie do 1 sekundy.

**Comment by zaba-monika** [comment]
- mi chodziło o zwykłą prostą edycję / podmianę pliku hosts w Androdzie
- no ale skoro jest aplikacja AdGuard pod Android która też umożliwia załadowanie tej listy i będzie działała jak hosts dla tej apki to OK

**Comment by mariusz689** [comment]
Niestety nie mam zrootowanego telefonu więc chyba nici z podmianą pliku hosts na telefonie ?

@krystian3w serwer Huawei są zamulone czy serwer AdGuard DNS ?

**Comment by krystian3w** [comment]
Raczej serwery AdGuard DNS, że nie umie się dobić na chińskie Baidu w krótszym czasie niż 20 sekund.

**Comment by mariusz689** [comment]
Przed chwilą ustawiłem na Mikrotik DNS AdGuard:

Dla "Bez filtrowania":
94.140.14.140

I problem z połączeniem nadal występuje. Ten rodzaj filtru "Bez filtrowania" jest chyba bez jakikolwiek blokad i ograniczeń - po prostu ruch przechodzi przez DNS bez żadnego blokowania, dobrze rozumiem?

**Comment by mariusz689** [comment]
@krystian3w wygląda na to, że AdGuard ma problem z komunikacją z chińskim Baidu. Czyżby Baidu ogranicza w jakiś sposób ruch z serwerami AdGuard ? To dziwne dlaczego, logując się bez żadnego pomocniczego DNS mogę to zrobić bez problemu. (Czasami występują opóźnienia, mam wrażenie że aplikacja muli się przy logowaniu, bo niekiedy logowanie trwa 10-30sekund.) średnio co piąte logowanie tak wygląda.

**Comment by AroKol78** [comment]
> ...Czyżby Baidu...
 
szpiegowało :laughing:

>...bo niekiedy logowanie trwa...

**Comment by MajkiIT** [comment]
@krystian3w czyli jakby na MT zrobić statyczny wpis dla tej domeny to nie trzeba by było odpytywać serwerów Baidu i problem powinien rozstać rozwiązany ?

**Comment by krystian3w** [comment]
Jak pozwala on na przesłanie przez inny DNS (co wydaje się dziwne, ale "funkcjonalne") lub zmniejszy się opóźnienie to można próbować i może będzie 99% skuteczność logowania bez komunikatów "sieć działa źle".

**Comment by zaba-monika** [comment]
> mariusz689 : https://github.com/MajkiIT/polish-ads-filter/issues/17875#issuecomment-735458790 : Niestety nie mam zrootowanego telefonu więc chyba nici z podmianą pliku hosts na telefonie ?

- ponoć da się też bez roota, za pomocą `Android Debug Bridge` 
w tym artykule jest to opisane ("The non-root method"):
https://www.modmy.com/how-modify-hosts-file-your-android-device

>  mariusz689 : https://github.com/MajkiIT/polish-ads-filter/issues/17875#issuecomment-735469774 : Czyżby Baidu ogranicza w jakiś sposób ruch z serwerami AdGuard ?
- dziwne pytanie, niby jak miałby ograniczać?

>  mariusz689 : https://github.com/MajkiIT/polish-ads-filter/issues/17875#issuecomment-735469774 :  To dziwne dlaczego, logując się bez żadnego pomocniczego DNS mogę to zrobić bez problemu.

- a co tu dziwnego, przecież od założenia tego wątku wiadomo, że AdGuard DNS blokuje jakąś domenę, albo dlatego, że po prostu blokuje, albo wg. teorii krystiana bo zamula z jakaś domeną

**Comment by mariusz689** [comment]
@AroKol78 czyli teorie o tym że Huawei szpieguje i wycofanie sprzętu tej marki z nadajników bts jest słusznym posunięciem ? :D 

@MajkiIT "...nie trzeba by było odpytywać serwerów Baidu..." chyba powinno być "serwerów AdGuard" ?

@zaba-monika dzięki za instrukcje w wolnej chwili ustawię te host bez roota na telefonie.

Kilka godzin temu przy aktywnym AdGuard DNS na mikrotiku, spróbowałem zalogować się na swoje konto w aplikacji Fusionsolar na telefonie, dziwne ale się zalogowało. Kilka razy wyłączałem aplikację i uruchamiałem ją ponownie - i tak zalogowałem 5 razy z rzędu. To sobie pomyślałem, coś się naprawiło to szybko ruch z falownika puściłem przez Mikrotik z aktywnym AdGuard DNS i falownik pozytywnie nawiązał połączenie ze światem. Później jeszcze może raz lub dwa razy spróbowałem zalogować się do aplikacji fusionsolar na telefonie i później już wyświetlał się błąd. Ale uwaga falownik nadal ma połączenie ze światem. Aplikacja na telefonie Fusionsolar czasami się loguje czasami jest "błąd połączenia z internetem" - (Przy aktywnym filtrze AdGuard DNS na Mikrotik). Chyba falownik podczas nowego połączenia z internetem wysyła jakąś prośbę o uwierzytelnienie konta (połączeniem z Baidu) a później łączy się tylko z tą chmurą Orange w celu synchronizacji danych. dobrze myślę ? Czyli nie jest winny wpis w filtrze AdGuard tylko jakieś opóźnienie między serwerami tak jak pisał @krystian3w , zgadza się?

@zaba-monika napisałaś że jakiś wpis w AdGuard DNS blokuje ruch z jakąś domeną, ale AdGuard udostępnia też DNS z opcją bez filtrowania. Mają też filtr DNS "ochrona rodzinna" na każdym DNS pojawiały się problemy. W jakim celu AdGuard udostępnia DNS z opcją "bez filtrowania"  ?

W takiej sytuacji gdzie leży problem?, bo już sam nie wiem.

**Comment by zaba-monika** [comment]
> mariusz689 : W jakim celu AdGuard udostępnia DNS z opcją "bez filtrowania" ?

- to zwykły DNS, który nic nie blokuje, taka alternatywa do wyboru przy normalnym korzystaniu z internetu, w stosunku do innych DNS: https://thecamels.org/pl/ktory-dostawca-dns-jest-najszybszy/
- po drugie bo jest niby "bezpieczny i niezawodny" jak napisali u siebie na stronie
https://adguard.com/pl/adguard-dns/overview.html :

> AdGuard : Zwróć uwagę: serwery DNS "Bez filtrowania" **dostarczają bezpieczne i niezawodne połączenie**, ale nie filtrują niczego jak serwery "Domyślne" i "Rodzinne". Nie używaj ich proszę jeśli nie wiesz co robisz.

- tylko że pewnie każdy dostawca DNS pewnie pisze to samo i zachwala swoje, wiadomo...

> mariusz689 : Czyli nie jest winny wpis w filtrze AdGuard tylko jakieś opóźnienie między serwerami tak jak pisał @krystian3w , zgadza się?

> mariusz689 : W takiej sytuacji gdzie leży problem?, bo już sam nie wiem.

- może być też tak, że serwer autoryzacji z którym łączy się apka, a który jest blokowany przez AdGuard DNS, może się zmieniać, czyli mogą być np. 2 serwery autoryzacji:
-  (np. główny i zapasowy / alternatywny): apka próbuje się łączyć z głównym, ale że jest zablokowany w AdGuard DNS, to łączy się z alternatywnym, który nie jest zablokowany w AdGuard DNS i udaje się
- albo losowo / przypadkowo raz z jednym (zablokowanym), innym razem z drugim (niezablokowanym)
- zresztą chyba sam o tym nawet wspominałeś...

**Comment by AroKol78** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/17875#issuecomment-736135771
> AroKol78 czyli teorie o tym że Huawei szpieguje i wycofanie sprzętu tej marki z nadajników bts jest słusznym posunięciem ? :D

jak czas temu abw zatrzymało przedstawiciela Huawei
co do nadajników bts - ogólnie mi nie przeszkadzają, pytanie kto będzie miał nad nimi rzeczywistą kontrolę

**Comment by mariusz689** [comment]
Umieściłem komentarz w drugim wątku. Kilka godzin temu pobrałem AdGuard z oficjalnej strony a nie ze sklepu google i teraz aplikacja AdGuard działa prawidłowo. Jest pełny log z połączeń i w logach jest informacja między innymi o pingu 20000-60000ms . Jeśli chcecie możecie wejść w mój drugi wątek i zobaczyć screeny z logami z aplikacji. Ciekawe czy to naprawią.

**Comment by krystian3w** [comment]
Ja widziałem dokładnie to samo co na twoich zrzutach:

![obraz](https://user-images.githubusercontent.com/35370833/100974212-32b58980-353c-11eb-8a8d-92dbd970e4ab.png) | ![obraz](https://user-images.githubusercontent.com/35370833/100974283-4bbe3a80-353c-11eb-9363-eb141cfa5d12.png)
--- | ---


Może polska infrastruktura internetowa jest wymagana do odtworzenia błędów.

**Comment by zaba-monika** [comment]
A mnie zastanawia pewna rzecz: 
- na pierwszych dwóch zrzutach ekranu od mariusz689 gdzie kiedy apka działa poprawnie jest: 
`Typ wydarzenia : Żądanie DNS`
- na tych zrzutach na których są lagi jest:  
`Typ wydarzenia : Tunel HTTPS`
czy to nie jest jakieś proxy / VPN? to by tłumaczyło lagi, przez które apka ma problemy...
ponoć ten tunel jest potrzebny dla AdGuard DNS w  celu usunięcia niektórych reklam:
https://kb.adguard.com/en/android/faq#https może spróbuj wyłączyć te tunelowanie?
