### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17874]
reklamy wrociły

**Comment by zaba-monika** [comment]
hehe, co chwilę jakaś strona WP naprawiona i usuniete reklamy, a po kilku dniach znowu wyskakują...idą święta, Mikołaj WP nie próżnuje...

**Comment by krystian3w** [comment]
No niby portal **prof. dr hab. mgr inżynierów**.

**Comment by zaba-monika** [comment]
@MajkiIT `sportowefakty.wp.pl##+js(aost, WP.prebid, onLoad)`

**Comment by zaba-monika** [comment]
@gzenio22 / chłopaki, zostało naprawione, jeśli nie ma reklam ani błędów, to można zamknąć.

**Comment by gzenio22** [comment]
potwierdzam zamykam zobaczymy na jak długo :D

**Comment by zaba-monika** [comment]
Kilka / kilkanaście dni zazwyczaj, jeśli wytrzyma do świąt / sylwestra to będzie nader dobrze... :smiley:

**Comment by SebaK666** [comment]
Na SportowychFaktach oczywiście poprawiło się, zniknęły reklamy, ale o ile na głównej stronie wyświetla belkę z wynikami meczów, to już na poszczególnych działach jak piłka nożna, żużel itp, brak tej belki, także nieklikalny jest przycisk szukania, a także nie można rozwijać komentarzy, bo podobnie do opcji szukania, jest to nieklikalne.
![SF](https://user-images.githubusercontent.com/33153803/102377108-9754f780-3fc4-11eb-829c-64a102bb69dd.jpg)
![SF2](https://user-images.githubusercontent.com/33153803/102378283-ef402e00-3fc5-11eb-9789-70b737b6d341.jpg)

Widzę że dni mijają, a nikt tego nie widzi, nie poprawia. Fajnie jest jakiś filtr dodać, ale jeszcze trzeba sprawdzić, prztestować, czy nie blokuje za dużo, czegoś, czego nie powinien
