### ISSUE TITLE
wiadomosci.wp.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17878]
https://wiadomosci.wp.pl/ktos-zabral-telefon-zmarlemu-na-covid-19-bylo-tam-nagrane-pozegnanie-z-rodzina-6579137149250432a?utm_medium=WSP_Wykop_KAMP&utm_source=wykop_pl&utm_campaign=wspWykop_wp_wiadomosci

w komentarzach sie zaplątały 2 reklamy Tmobile i bodaj WP pilot

**Comment by zaba-monika** [comment]
Wysypało reklamy na kilkunastu domenach WP...hehehe
