### ISSUE TITLE
Pytanie o... 

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#17873]
![Screenshot_1](https://user-images.githubusercontent.com/21177361/100367240-37d97c80-3002-11eb-856d-8d685ebe8962.png)

Kiedys była lista blokująca takie kwiatki przypomnicie ktora to?

**Comment by gzenio22** [comment]
@MajkiIT @zaba-monika 

patrzcie rozwalamy wykop https://www.wykop.pl/link/5820329/polskie-filtry-do-adblocka-ublocka-origin-i-adguarda/

**Comment by zaba-monika** [comment]
> gzenio22 : Kiedys była lista blokująca takie kwiatki przypomnicie ktora to?

To jest blokowane przez `Polskie Filtry Elementów Irytujących` (moduł Powiadomienia Web Push)

**Comment by gzenio22** [comment]
@zaba-monika to chyba bylo to

**Comment by krystian3w** [comment]
Push to nie zgoda na lokalizację, tej nikt nie blokuje.

Jak nie używasz geolokalizacji na PC to ją wyłącz z ustawień przeglądarki.

**Comment by gzenio22** [comment]
@krystian3w szczerze to nie moje pytanie przenioslem je tu z wykopu notabene wielkie dzieki za help tam w komentarzach :D

**Comment by zaba-monika** [comment]
> Push to nie zgoda na lokalizację, tej nikt nie blokuje.

Ale i Push i Zgoda są w takim samym dymku, może mu chodziło o wszelkiego rodzaju takie dymki...

**Comment by krystian3w** [comment]
No to na ten rodzaj roślinki to listy filtrów raczej publicznej nie ma.

**Comment by gzenio22** [comment]
facebook.com##div[data-pagelet^="FeedUnit_"]:has(a[aria-label="Sponsorowane"])

Sprawdzcie tego rodzynka bo nie wiem czy typa nie zminusowac

**Comment by MajkiIT** [comment]
@gzenio22 widzę, że poszedłeś w marketing 👍

**Comment by krystian3w** [comment]
@gzenio22 może działać, ale jak zmienisz język interfejsu to padnie.

Poza tym nie wiadomo kiedy link straci "`[aria-label="Sponsorowane"]`" lub dla niewidomych użyją "sPonSOrowANe", bo synteza mowy i tak pewnie przeczyta tak samo.

Dodatkową wadą jest pułapka, że niby każdy post ma atrybut "`[aria-label="Sponsorowane"]`", więc trzeba ograniczyć go do szukana tylko na `<div>`-ach lub linkach (`<a>` w html).

**Comment by gzenio22** [comment]
@MajkiIT No wiesz robicie dobrą robote jakoś musiałem sie w końcu odwdzięczyć 
@krystian3w weź tam wyjaśnij to samo co teraz mi temu co to napisał na wykopie Xd a i oznaczylem cie przy jednym pytaniu o safari Xd

**Comment by gzenio22** [comment]
https://filterlists.com/

@MajkiIT @krystian3w chyba niezły stuff do przejzenia czy to sie na cos nadaje Xd

**Comment by gzenio22** [comment]
panie i panowie mam pytanie pewnie znowu smieszne ale czy jak kupie już sobie adguarda bede mogl odinstalowac te wtyczki co dzis dostalem czyli idont care about i polskie ciasteczkowe czy to ma byc mimo adguarda?

Jego też chce jak cos jak najlepiej skonfigurowac zeby nie walić wam błędnymi zgłoszeniami Xd

**Comment by krystian3w** [comment]
To zależy czy @F4z / @adamwr dodał to co my mamy w bazie do akceptowania  w AdGuard Annoyance lub uważa że przekierowanie zamiast ręcznego klikania jest dobre dla społeczności (cookiewall i fake-cookiewalle):

```
! redirect
=http://edytor-serwis.com.pl/(redirect, index2.html, false)
=http://www.edytor-serwis.com.pl/(redirect, index2.html, false)
=https://powiatkamienski.pl/(redirect, aktualnosci.dhtml, false)
=https://www.powiatkamienski.pl/(redirect, aktualnosci.dhtml, false)
f1racing.pl(redirect, x-set-cookie, true, x-id-cookie-yes=)
```

Pewnie ty nie musisz na codzień czytać `powiatkamienski.pl` / `edytor-serwis.com.pl` lub `f1racing.pl`.


Lista IDCAC i tak by była zalecana do subskrypcji w AdGuard dla Windows/Android.

**Comment by gzenio22** [comment]
liste to ja zasubuje pytalem raczej o wtyki do przegladarek :P

**Comment by zaba-monika** [comment]
- większość komunikatów ciasteczkowych da się usunąć za pomocą filtrów / list adblockerowych, czyli bez potrzeby instalowania kolejnych rozszerzeń, ale niektóre komunikaty ciasteczkowe są złośliwe i trzeba je zaakceptować / kliknąć "Akcpetuję / OK / Zgadzam się / Przechodzę dalej" itp. , bo gdy usunie się je za pomocą filtra w adblockerze to owszem komunikat zostanie usunięty, ale strona zostanie popsuta, więc dlatego te złośliwe komunikaty ciasteczkowe muszą być "kliknięte" w tradycyjny sposób, a adblockery ze względów bezpieczeństwa nie mają zaimplementowanego "klikania", więc potrzeba zainstalować dodatkowo rozszerzenie typu `I Don't Care About Cookies` i `Polska Zgoda Ciasteczkowa` dla tych złośliwych komunikatów ciasteczkowych, na tej samej zasadzie istniał kiedyś `Nano Defender` które blokował złośliwe komunikaty anty-adblockowe, z którymi nie dawał sobie rady goły `uBO`
- `AdGuard` i `uBlock Origin` posiadają listy filtrów elementów irytujących, czyli odpowiedniki `Polskie Filtry Elementów Irytujących`, odpowiedniki te nazywają się: `AdGuard Annoyances` i `Fanboy’s Annoyance`, odpowiedniki te podobnie jak `Polskie Filtry Elementów Irytujących`, zawierają wbudowane listy ciasteczkowe i socjalne, ale każda z tych list elementów irytujących na pewno usuwa coś czego nie usuwa inna...wzajemnie się uzupełniają...ale nie potrafią "klikać" więc nawet wszystkie na raz nie usuną ci tych komunikatów, do których potrzeba rzoszerzenia `I Don't Care About Cookies` i `Polska Zgoda Ciasteczkowa`

**Comment by krystian3w** [comment]
AdGuard Annoyance umie klikać ma filtry JavaScript:

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#javascript-rules

Takim czymś klika w "przechodzę dalej" lub piecze ciastko na parkiet.com i rp.pl

`rp.pl,parkiet.com#%#//scriptlet('set-cookie', '__gm_tcfconsent_v2', '1')` <sup>https://github.com/AdguardTeam/AdguardFilters/blob/80e8ba33850712854b34f8e9e3abb51037be7a8d/AnnoyancesFilter/sections/cookies_specific.txt#L4697</sup>

**Comment by zaba-monika** [comment]
Dlatego dopisałam na końcu, jeszcze przed twoim komentarzem:

> zaba-monika : chociaż nie korzystam z `AdGuard` więc nie jestem pewna czy może jednak `AdGuard` potrafi klikać..chłopaki od ciasteczek pewnie będą wiedzieli

Stary ledwo zdążyłam dopisać te ostatnie zdanie, a prawie zdążyłeś wdupić się ze swoim komentarzem, szybki jesteś...

**Comment by zaba-monika** [comment]
- wracając do `AdGuard` nawet jeśli klika to raczej nie klika wszystkiego tego co klika `I Don't Care About Cookies` i `Polska Zgoda Ciasteczkowa`...

**Comment by gzenio22** [comment]
zaczne sie bawic adguardem na powaznie po swietach jak juz bede go mial :D licze ze mnie wesprzecie w poznawaniu tego cudeńka :D

**Comment by zaba-monika** [comment]
- może bardziej krystian3w cię wesprze, bo ja AdGuard nie używam, jedynie czasem włącze rozszerzenie w przeglądarce przy ogarniania jakieś strony / zgłoszenia

**Comment by krystian3w** [comment]
Takie coś ubija geolokalizacje `*,~gov.pl##+js(set, navigator.geolocation.getCurrentPosition, falseFunc)`

w AG powinno wystarczyć:

`#%#//scriptlet('set-constant', 'navigator.geolocation.getCurrentPosition', 'falseFunc')`

Niby psuło kiedyś Allegro.cz ale `falseFunc` naprawia problem.
