### ISSUE TITLE
GRUPA "Lokalne Ogłoszenia" (ponad 1000 stron) 😃

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17887]
**Pierwsza sprawa:**

- kontynuacja poprzedniego zgłoszenia: https://github.com/MajkiIT/polish-ads-filter/issues/17867 bo ani ja jako zgłaszająca ani naprawiający ani nikt inny, nie zwrócili uwagi, że oprócz tych 3 stron, jest tam jeszcze około... 230 stron z nieusuniętym komunikatem ciasteczkowym, być może tych stron jest jeszcze więcej (ponoć 370)...aktualizacja: jak widać okazało się, że jest ponad 1000 https://github.com/MajkiIT/polish-ads-filter/issues/17887#issuecomment-735831750
- przy okazji jest to pobicie rekordu rozmiaru GRUPY ciasteczkowej, poprzedni rekord wynosił 100 stron, tu: https://github.com/MajkiIT/polish-ads-filter/issues/17809, oczywiście obydwa rekordy by zaba-monika

<details not-open>
<summary>około 230 stron - spoiler</summary>

http://belchatowpraca.pl/
http://bialapodlaskaogloszenia.pl/ (zrobione)
http://bialapodlaskapraca.pl/
http://bialogardogloszenia.pl/
http://bialystokpraca.pl/
http://bielskobialapraca.pl/
http://bochniapraca.pl/
http://brzezinyogloszenia.pl/
http://bydgoszczpraca.pl/
http://bytompraca.pl/
http://chelmpraca.pl/
http://chojnicepraca.pl/
http://chorzowpraca.pl/
http://czestochowaogloszenia.pl/ (zrobione)
http://dabrowapraca.pl/
http://debicapraca.pl/
http://elblagpraca.pl/
http://elkpraca.pl/
http://fajnenoclegilodz.pl/
http://gdanskpraca.pl/
http://gdyniapraca.pl/
http://gliwicepraca.pl/
http://gnieznopraca.pl/
http://gorzowpraca.pl/
http://grodziskpraca.pl/
http://grudziadzpraca.pl/
http://inowroclawpraca.pl/
http://jaworznopraca.pl/
http://kaliszpraca.pl/
http://katowicepraca.pl/
http://kepnonoclegi.pl/
http://kielcepraca.pl/
http://klobuckogloszenia.pl/
http://kolobrzegogloszenia.pl/
http://kolobrzegpraca.pl/
http://koninpraca.pl/
http://koszalinnoclegi.pl/
http://koszalinogloszenia.pl/ (zrobione)
http://koszalinpraca.pl/
http://krakowofertypracy.pl/
http://krosnopraca.pl/
http://kwaterydabki.pl/
http://kwaterydarlowo.pl/
http://kwaterysarbinowo.pl/
http://kwateryustroniemorskie.pl/
http://laskogloszenia.pl/
http://leczycaogloszenia.pl/
http://legnicapraca.pl/
http://lesznopraca.pl/
http://lodzogloszenia.pl/
http://lodzpraca.pl/
http://lomzapraca.pl/
http://losiceogloszenia.pl/
http://lubliniecogloszenia.pl/
http://lubliniecpraca.pl/
http://lublinpraca.pl/
http://lukownoclegi.pl/
http://lukowogloszenia.pl/
http://myslowicepraca.pl/
http://myszkownoclegi.pl/
http://noclegibialapodlaska.pl/
http://noclegibobolice.pl/
http://noclegibobolin.pl/
http://noclegikluczbork.pl/
http://noclegimiasto.pl/
http://noclegipabianice.pl/
http://noclegipiotrkow.pl/
http://noclegiradzyn.pl/
http://noclegisiemiatycze.pl/
http://noclegiskierniewice.pl/
http://noclegiwielun.pl/
http://noclegiwlodawa.pl/
http://noclegizawiercie.pl/
http://noclegizgierz.pl/
http://nowysaczpraca.pl/
http://nysapraca.pl/
http://ofertypracyczestochowa.pl/
http://ofertypracyolsztyn.pl/
http://ofertypracyradom.pl/
http://ofertypracyradomsko.pl/
http://ofertypracywroclaw.pl/
http://ogloszeniamyszkow.pl/
http://ogloszeniaolesno.pl/
http://ogloszeniaozorkow.pl/
http://ogloszeniaslawno.pl/
http://opolepraca.pl/
http://ostrolekapraca.pl/
http://ozorkownoclegi.pl/
http://pabianiceogloszenia.pl/
http://pabianicepraca.pl/
http://pajecznoogloszenia.pl/
http://parczewogloszenia.pl/
http://piasecznopraca.pl/
http://pilapraca.pl/
http://plockpraca.pl/
http://poddebiceogloszenia.pl/
http://pokojekutno.pl/
http://pokojelubliniec.pl/
http://polczynzdrojogloszenia.pl/
http://poznanpraca.pl/
http://pracaaugustow.pl/
http://pracabartoszyce.pl/
http://pracabialogard.pl/
http://pracabilgoraj.pl/
http://pracablonie.pl/
http://pracaboleslawiec.pl/
http://pracabraniewo.pl/
http://pracabrodnica.pl/
http://pracabrzesk.pl/
http://pracabrzeziny.pl/
http://pracabusko.pl/
http://pracaciechanow.pl/
http://pracadzierzoniow.pl/
http://pracagarwolin.pl/
http://pracagizycko.pl/
http://pracagorlice.pl/
http://pracagrajewo.pl/
http://pracagrojec.pl/
http://pracahajnowka.pl/
http://pracajaroslaw.pl/
http://pracajastrzebie.pl/
http://pracajedrzejow.pl/
http://pracajeleniagora.pl/
http://pracakepno.pl/
http://pracaketrzyn.pl/
http://pracaklobuck.pl/
http://pracaklodzko.pl/
http://pracakluczbork.pl/
http://pracakoscian.pl/
http://pracakozienice.pl/
http://pracakrasnik.pl/
http://pracakrasnystaw.pl/
http://pracakutno.pl/
http://pracalask.pl/
http://pracaleczna.pl/
http://pracaleczyca.pl/
http://pracalegionowo.pl/
http://pracalezajsk.pl/
http://pracalimanowa.pl/
http://pracalosice.pl/
http://pracalowicz.pl/
http://pracalukow.pl/
http://pracamazury.pl/
http://pracamragowo.pl/
http://pracamyszkow.pl/
http://pracaoborniki.pl/
http://pracaolawa.pl/
http://pracaolesno.pl/
http://pracaopoczno.pl/
http://pracaostroda.pl/
http://pracaozarow.pl/
http://pracapajeczno.pl/
http://pracaparczew.pl/
http://pracapiekary.pl/
http://pracapiotrkow.pl/
http://pracaplonsk.pl/
http://pracapoddebice.pl/
http://pracapruszkow.pl/
http://pracapszczyna.pl/
http://pracaradzynpodlaski.pl/
http://pracarudaslaska.pl/
http://pracasandomierz.pl/
http://pracasanok.pl/
http://pracasiemianowice.pl/
http://pracasiemiatycze.pl/
http://pracaskierniewice.pl/
http://pracaslawno.pl/
http://pracasopot.pl/
http://pracasrem.pl/
http://pracastrykow.pl/
http://pracaswidwin.pl/
http://pracaswiebodzin.pl/
http://pracaswietochlowice.pl/
http://pracaswinoujscie.pl/
http://pracaszamotuly.pl/
http://pracaturek.pl/
http://pracatychy.pl/
http://pracawadowice.pl/
http://pracawielun.pl/
http://pracawolomin.pl/
http://pracawolsztyn.pl/
http://pracawyszkow.pl/
http://pracazdunskawola.pl/
http://pracazuromin.pl/
http://przemyslpraca.pl/
http://raciborzpraca.pl/
http://radomskonoclegi.pl/
http://radomskoogloszenia.pl/
http://radzynpodlaskiogloszenia.pl/
http://rybnikpraca.pl/
http://rzeszowpraca.pl/
http://siedlcenoclegi.pl/
http://siedlcepraca.pl/
http://siemiatyczeogloszenia.pl/
http://sieradznoclegi.pl/
http://sieradzogloszenia.pl/
http://sieradzpraca.pl/
http://sochaczewpraca.pl/
http://stalowawolapraca.pl/
http://strykowogloszenia.pl/
http://suwalkipraca.pl/
http://swidnicapraca.pl/
http://swidwinogloszenia.pl/
http://szwecjapraca.pl/
http://tanienoclegibelchatow.pl/
http://tanienoclegiczestochowa.pl/
http://tarnobrzegpraca.pl/
http://tarnowpraca.pl/
http://tczewpraca.pl/
http://torunpraca.pl/
http://trew.pl/
http://walbrzychpraca.pl/
http://warszawaofertypracy.pl/
http://wejherowopraca.pl/
http://wielunogloszenia.pl/
http://wloclawekpraca.pl/
http://wrzesniapraca.pl/
http://www.job365.pl/
http://zabrzepraca.pl/
http://zamoscpraca.pl/
http://zarypraca.pl/
http://zdunskawolaogloszenia.pl/
http://zgierzogloszenia.pl/
http://zgierzpraca.pl/
http://zgorzelecpraca.pl/
http://zielonagorapraca.pl/
http://zorypraca.pl/
http://zyrardowpraca.pl/
http://zywiecpraca.pl/

</details>

████████████████████████████████████████████████████████████████████████

**Druga sprawa:**
- tu https://github.com/MajkiIT/polish-ads-filter/issues/17828 został usunięty tylko jeden komunikat, 
a jeszcze został drugi, co prawda statyczny ale `na środku` + `czerwonym kolorem na szarym tle` czyli przeszkadzający, więc do usunięcia tak samo jak na tej samej zasadzie został usunięty tego typu komunikat tutaj:
 https://github.com/MajkiIT/polish-ads-filter/issues/17862 `na środku` + `białą czcionką na niebieskim tle`, jak widać obydwa przypadki takie same a tylko w jednym zgłoszeniu został usunięty, więc w tym drugi też musi, wg. tej samej  logiki

████████████████████████████████████████████████████████████████████████

- obydwie sprawy powiązane z https://github.com/MajkiIT/polish-ads-filter/pull/17886

**Comment by bug-rules** [comment]
W sumie będzie 1012:

http://pracamiasto.pl/index.php
http://lokalneogloszenia.com/index.php
http://noclegimiasto.pl/index.php

**Comment by zaba-monika** [comment]
Hahaha, no to grubo
![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTb6ymiDQAuwmoq3_akxtzxQkX-FAxnr_LRIQ&usqp=CAU)
