### ISSUE TITLE
nike.com/pl/pl_pl/

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1788]
resztki cookies 

http://store.nike.com/pl/pl_pl/pd/buty-dla-duzych-presto-extreme/pid-11256011/pgid-11840698?ref=https%253A%252F%252Fwww.google.com%252F&flh=store&loc=PL&ref=https://www.google.com/

![capture](https://cloud.githubusercontent.com/assets/15007183/21556642/3a1b9938-cdf0-11e6-868b-372f2086036f.PNG)

**Comment by kerbenii** [comment]
Z tym mam problem, bo ten element jest w drzewie osadzony tak:
`.modal-mask-class >.modal-window-class.nsg-bg--white > .modal-content-class > div > .cookie-settings-manager-container`

no ale dopiero jak znajdziemy  .cookie-settings-manager-container możemy go zablokować.
W CSS można to osiągnąć poprzez has, lub (w CSS 4) !, ale obie pseudoklasy nie są wspierane przez adblock'a. Ktoś ma jakiś pomysł?

**Comment by F4z** [comment]
Może w ten sposób?
`||nike.com/*/CookieSettingsManager`

**Comment by kerbenii** [comment]
Myślałem o tym, ale po paru przejściach pomiędzy stronami ten pojawiający się i znikający preloader zaczyna wkurzać.

**Comment by F4z** [comment]
Ok, też to czasami widzę.
Czy przy tej regule nadal tak "miga"?
`||nike.com/*CookieSettingsManager$xmlhttprequest`

**Comment by xxcriticxx** [comment]
@F4z dalej miga

**Comment by FadeMind** [comment]
Adres
```
http://store.nike.com/pl/pl_pl/nikestore/gadget/nike/gadget/CookieSettingsManager?gadgetName=nike.gadget.CookieSettingsManager
```
blokuje z `Fanboy+Easylist-Merged Ultimate List` za pomocą

```
/cookiesettingsmanager?
```

**Comment by kerbenii** [comment]
Niestety.Ogólnie wstrzykuje go NikeScriptManager jak nie znajdzie cookies'a o nazwie sq

**Comment by kerbenii** [comment]
Przetestujcie to proszę:
`||nike.com/*CookieSettingsManager`

**Comment by F4z** [comment]
To już nic nie wymyślę.
Ogólnie u mnie ta reguła - `||nike.com/*CookieSettingsManager$xmlhttprequest` - działa, bo przy poprzedniej czasami migało.
I o ile się nie mylę, to w tym przypadku blokowany jest skrypt, który odpowiada za wyświetlenie tego komunikatu - `http://store.nike.com/pl/pl_pl/script.js?assets=nike.gadget.CookieSettingsManager&loaded=nike.exp.global.Ad%2Cnike.page.OneNikeShell%2Cnike.fonts.glyphPolyfill%2Clogging%2Cnike%2Cnike.EventBus%2Cnike.exp.global.CookieSettingsCheck%2Cnike.page.OneNikePageLayout%2Cnike.style.exp.exp-desktop%2Cnike.Chat%2Cnike.nsgInit%2Cnike.exp.global.CookieSettingsHandler%2Cnike.exp.util.shared.desktop.CookieSettings%2Cnike.exp.util.shared.base.TextReplacement%2Cnike.ScriptLoader%2CjQuery%2Cpolyfills%2Cnike.gadget.BuyingOptions%2Cnike.exp.pdp.PdpPage&format=optimized&showFurnitureKeys=null`

**Comment by F4z** [comment]
Samo - `||nike.com/*CookieSettingsManager` - będzie za dużo blokować.
Tutaj strona przestanie działać - `https://www.nike.com/pl/pl_pl/p/myactivity`

**Comment by kerbenii** [comment]
Niestety, masz rację...
To może @F4z niech zostanie ta twoja a jak coś to poprosi się ich ładnie o id'ka.

**Comment by xxcriticxx** [comment]
@F4z sie zdaje co podal @kerbenii jest good `||nike.com/*CookieSettingsManager`

**Comment by xxcriticxx** [comment]
@F4z right strona myactivity sie nie laduje to niech moze lepjej miga :)

**Comment by F4z** [comment]
@xxcriticxx a to z tą reguła nadal Ci miga? - `||nike.com/*CookieSettingsManager$xmlhttprequest`

@kerbenii nie wiem czy dobrze Cię tutaj zrozumiałem - https://github.com/MajkiIT/polish-ads-filter/issues/1788#issuecomment-269863950
Jest możliwość ukrycia tego przy użyciu `has` w uBlocku?
Na przykład tak?
`store.nike.com##.modal-mask-class:has(.cookie-settings-manager-container)`
Tylko wtedy nadal strony nie będzie dało się przewinąć.
Czy o coś innego Ci chodziło?

**Comment by kerbenii** [comment]
Nie wiem jakie możliwości ma uBlock.
Jeżeli da się tam jeszcze usunąć klasę modal-show z tagu html to będzie śmigać.

**Comment by kerbenii** [comment]
Jest tam coś takiego jak Stylish rule i z tego co doczytałem to tam się CSSy wpina.
Wtedy teoretycznie wystarczy tam majdnąć coś takiego:
html.modal-show{
    overflow: visible;
}

**Comment by F4z** [comment]
Usunąć się nie da, jedynie ukryć.
Można też w ten sposób:
`store.nike.com##.modal-mask-class:has(.cookie-settings-manager-container)`
`store.nike.com##html.modal-show:style(overflow: visible !important;)`

Ale też będzie migać.

**Comment by xxcriticxx** [comment]
@F4z miga jak skacze po meczyni kobiety chlopcy te sekcje na topie

**Comment by xxcriticxx** [comment]
miga malo jak kategorie zmieniasz da sie zyc

**Comment by F4z** [comment]
@xxcriticxx ok, widzę.
A z tymi regułami jak jest?
`||nike.com/*/script.js?assets=nike.gadget.CookieSettingsManager&loaded=nike.exp.global.Ad*nike.ScriptLoade$script`
`||nike.com/*CookieSettingsManager$xmlhttprequest`

**Comment by xxcriticxx** [comment]
@F4z jest malina!

**Comment by kerbenii** [comment]
@F4z wow, you made it! xD
@xxcriticxx, @F4z tak w ogóle to wolicie żeby wam robić pull requests czy pisać w komentarzach regułki?

**Comment by F4z** [comment]
@kerbenii dzięki za pomoc.
Osobiście wolę w komentarzach, ale najlepiej żeby tutaj wypowiedział się @MajkiIT, bo to on przede wszystkim dodaje reguły do listy :)

**Comment by MajkiIT** [comment]
@kerbenii Komentarze są lepsze, bo łatwiej komuś sprawdzać porównywać i w razie co jest historia działań nad filtrami.
