### ISSUE TITLE
wydarzenia.interia.pl

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#17888]
co prawda reklamy nie pokazuje ale pasek trwa parę sekund (nie tyle co pokazuje - czas co 15 sec)
czy tak ma być
video - Śniadanie w Polsat News. 29 listopada
ten sam materiał wideo bez problemu na [polsatnews](https://www.polsatnews.pl/wiadomosc/2020-11-29/sniadanie-w-polsat-news-transmisja-od-godziny-10/?ref=slider) (inny interfejs)
https://wydarzenia.interia.pl/news-barbara-nowacka-potraktowana-gazem-marszalek-sejmu-oczekuje-,nId,4885083
![intervideo01](https://user-images.githubusercontent.com/70756447/100548819-42e51480-326f-11eb-9d77-70d6e917e4da.PNG)

dodatkowo proszę o **styl.pl+pomponik.pl** https://github.com/MajkiIT/polish-ads-filter/issues/17777#issuecomment-735011261

**Comment by MajkiIT** [comment]
Tak się dzieje, bo przez chwile czeka na plik z reklamą np. taki ==> https://redirector.redefine.pl/r/w66u2n5ch4juhafj5od2pgrzsdudansw.mp4
