### ISSUE TITLE
styl.pl+pomponik.pl poprawka

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#17908]
poprawka do https://github.com/MajkiIT/polish-ads-filter/issues/17777
od krystian3w https://github.com/MajkiIT/polish-ads-filter/issues/17777#issuecomment-735011261
> Wróciło, już nie ma headera:
> 
> https://www.styl.pl/newsy/gwiazdy/news-ewa-farna-juz-tak-nie-wyglada,nId,4878841
> 
> `interia.pl,pomponik.pl,styl.pl#?#div[style*="sticky"]:-abp-has(a[onclick*="'polsat'"])`

ps
nie wiem czemu nie mogę ponownie otworzyć zgłoszenia (brak **Reopen issue**)

**Comment by krystian3w** [comment]
Bo jak zamknie owner lub collaborator (MajkiIT lub xxcriticxx), to opcja się traci dla autora jak nie jest dodany do listy uprawnionych w repozytorium (coś pomiędzy contributor a collaborator).

**Comment by krystian3w** [comment]
#17910 - identyczna

**Comment by AroKol78** [comment]
**krystian3w** dzięki za wyjaśnienie zagadki

**Comment by xxcriticxx** [comment]
@AroKol78 jeszcze troche i bedziesz takim ekspertem jak @krystian3w
