### ISSUE TITLE
echirurgia.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17907]
@ admin
- naprawa: doklejamy domenę do: https://github.com/olegwukr/polish-privacy-filters/blob/3f3626bea47984f9439b629ec8b09fdbe0614886/anti-adblock.txt#L334

![capture_162_30-11-2020_19-03-16](https://user-images.githubusercontent.com/72980128/100646729-b3a73200-333e-11eb-8a21-abe61dd62e27.png)

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/f48570e23bbebeaf927a3825d9f7ce4ebeca12e9#diff-4a6978b41c01edec9e42a612c659cd9fdd99e12c90dfca77cbd53379c960bb2c
