### ISSUE TITLE
rabatio.com

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#17906]
`https://rabatio.com/kupony`

reklamy popunder jak klikniemy w "**pokaż kod**":

```
$popunder,domain=rabatio.com
```

Nie znam rozwiązania dla ABP ani AdGuard - może @zaba-monika zna.

---

Jak dla mnie to otwieranie zakładki z obcym sklepem jest zbędne, raczej ludzie już mają wypełniony koszyk i szukają rabatu by koszty dostawy wyszły na 0 - dodatkowo strona używa czegoś w rodzaju atrybutów `utm_` co podchodzi pod śledzenie.

**Comment by zaba-monika** [comment]
> Nie znam rozwiązania dla ABP ani AdGuard - może @zaba-monika zna.

- typowymi scripletami z ABP i AG nie da się zamknąć popundera, jak widać tylko uBO to potrafi,
jedynie osiągnęłam połowniczy efekt, czyli nie ładuje się syf do popundera:
`rabatio.com##+js(aopr, focus)`  (uBO)
`rabatio.com#$#abort-on-property-read focus` (ABP)
`rabatio.com#%#//scriptlet('abort-on-property-read', 'focus')` (AG)

- w AG można odpalać dowolny JS więc coś pewnie się da wykombinować za pomocą
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#javascript-rules
tylko, że tam są jakieś restrykcje, że to działa tylko w "Moje Filtry" lub na liście AG
- podobnie jak skryplety w ABP działają tylko w "Moje Filtry" lub na liście 
https://github.com/abp-filters/abp-filters-anti-cv 
może jak ktoś zrobi tam zgłoszenie i zaproponuje:
`rabatio.com#$#abort-on-property-read focus`
to może dodadzą

**Comment by krystian3w** [comment]
W sumie problem, że `rabatio.com#%#//scriptlet('abort-on-property-read', 'focus')` wyleci ze suplementu, więc do pliku AG trzeba by wkleić składnie uBO `rabatio.com##+js(aopr, focus)`.

**Comment by zaba-monika** [comment]
Jeśli odnosiłeś się do czegoś czego już nie ma w moim komentarzu to wiedz, że usunęłam / edytowałam to **zanim** przeczytałam twój komentarz, sytuacja identyczna do https://github.com/MajkiIT/polish-ads-filter/issues/17873#issuecomment-735396581

**Comment by zaba-monika** [comment]
@MajkiIT jak coś to skrypt z pierwszego komentarza też trzeba dodać: https://github.com/MajkiIT/polish-ads-filter/issues/17906#issue-753685395

**Comment by krystian3w** [comment]
Wychodzi, że naprawili bugi ze składnią, można w AG preferować ich składnie skrypletów:

https://filters.adtidy.org/extension/chromium/filters/216.txt = już nie myśli skrypt że to dowolny JavaScript.

W takim wypadku można by skonwertować ["bakeCookie"](https://github.com/PolishFiltersTeam/PolishCookieConsent/blob/938ccb135a7210d34f6db98a7726a698b17c30d7/src/content.js#L83) na [`//scriptlet("set-cookie",`](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#set-cookie) - niby większość jest z wartościami "`true`".

**Comment by zaba-monika** [comment]
krystian ty to zawsze musisz się tak szybko wdupić z komentarzem w nieodpowiednim moemncie, że to trzeba chyba w końcu nazwać jakimś zjawiskiem, zobacz wsadziłeś się pomiędzy moje referencje, jedna z nich jest teraz za twoim komentarzem, a powinna być przed, bo gdy jest za, to sugeruje, że jakoby dotyczyła twojego komentarza, a one dotyczą wcześniejszych commitów, hehe

**Comment by zaba-monika** [comment]
> krystian3w : https://github.com/MajkiIT/polish-ads-filter/issues/17906#issuecomment-736287971 : 
W takim wypadku można by skonwertować ["bakeCookie"](https://github.com/PolishFiltersTeam/PolishCookieConsent/blob/938ccb135a7210d34f6db98a7726a698b17c30d7/src/content.js#L83) na [`//scriptlet("set-cookie",`](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#set-cookie)

- dziwne, że tutaj nie dodali `set-cookie`: 
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/compatibility-table.md#scriptlets

**Comment by zaba-monika** [comment]
> https://github.com/MajkiIT/polish-ads-filter/issues/17906#issuecomment-736289952


Tu kolejny mistrz wdupiania się z komentarzami w nieodpowiednim momencie:
- tu się wdupił : `https://github.com/easylist/easylist/issues/6476#issuecomment-737175642`
- a po chwili tu się wdupił : `https://github.com/easylist/easylist/issues/6476#issuecomment-737188448`
