### ISSUE TITLE
wbj.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1790]
reklama Mercedes Class E

![capture](https://cloud.githubusercontent.com/assets/15007183/21567006/a42861fe-ce76-11e6-84d6-831d55dab700.PNG)

**Comment by F4z** [comment]
Jak chcesz możesz sprawdzić jeszcze, ale powinno być ok:
`||wbj.pl/wp-content/plugins/adkingpro/js/adkingpro-functions.js$script`
`||wbj.pl/adv/`
`wbj.pl##.akpbanner`

**Comment by xxcriticxx** [comment]
@F4z good thx?
