### ISSUE TITLE
esporter.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17910]
Reklama + social
https://www.esporter.pl/newsy/news-call-of-duty-mobile-wojna-przenosna,nId,4887398
![Zrzut ekranu z 2020-11-30 20-57-25](https://user-images.githubusercontent.com/36385327/100657827-aa25c600-334e-11eb-91e0-5dea4d901d00.png)
![Zrzut ekranu z 2020-11-30 20-57-45](https://user-images.githubusercontent.com/36385327/100657976-b578f180-334e-11eb-8dc9-68c660df5e41.png)

**Comment by krystian3w** [comment]
Na reklamę pomoże takie coś:
```
esporter.pl,interia.pl,pomponik.pl,styl.pl#?#div[style*="sticky"]:-abp-has(a[target="_blank"][onclick*="'polsat'"])
```

https://github.com/MajkiIT/polish-ads-filter/issues/17777#issuecomment-735011261

**Comment by AroKol78** [comment]
od **krystian3w** https://github.com/MajkiIT/polish-ads-filter/issues/17777#issuecomment-735011261
u mnie działają trzy wersje na esporter.pl+styl.pl+pomponik.pl (sprawdzałem każdą oddzielnie)

`esporter.pl,interia.pl,pomponik.pl,styl.pl#?#div[style*="sticky"]:-abp-has(a[onclick*="'polsat'"])`

`esporter.pl,interia.pl,pomponik.pl,styl.pl#?#div[style*="sticky"]:-abp-has(a[target="_blank"][onclick*="'polsat'"])`

`esporter.pl,interia.pl,pomponik.pl,styl.pl#?#div[style*="sticky"]:-abp-has(> .boxHeader ~ div > a[href][target="_blank"][onclick*="'polsat'"])`

stara wersja już nie działa https://github.com/MajkiIT/polish-ads-filter/commit/850162150e4f76dc9b7993e58a4b3ad5d5da1e1b
`interia.pl,pomponik.pl,styl.pl#?#div[style*="sticky"]:-abp-has(> .boxHeader ~ a[href][target="_blank"][onclick*="'polsat'"])`
