### ISSUE TITLE
pebx.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1791]
Reklama na górze strony - `https://pebx.pl/forum/filmy.38/`

![image](https://cloud.githubusercontent.com/assets/11742596/21570923/aafbfd02-ceca-11e6-8c25-4d7a1a34d832.png)

Na przykład:
`||dropbox.com/s/zsjrfjhzufr8g18/20161230-skoki-bonus.jpg$image,domain=pebx.pl`
lub
`pebx.pl##a[href^="https://www.bet365.com/dl/~offer"]`

**Comment by F4z** [comment]
@MajkiIT znowu jest ta reklama - `https://pebx.pl/`
Ta reguła ciągle działa:
`||dropbox.com/s/zsjrfjhzufr8g18/20161230-skoki-bonus.jpg$image,domain=pebx.pl`
albo
`pebx.pl###header > script + div[style="text-align:center;width:100%;text-align:center;"] > a[href][rel="nofollow"]`
Można też w inny sposób, ale to już jak uważasz :)

**Comment by MajkiIT** [comment]
@F4z dzięki . Jak coś to zmieniaj i nie musisz czekać na mnie 👍

**Comment by F4z** [comment]
@MajkiIT ok :)
