### ISSUE TITLE
twojstyl.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#17936]
RODO

```
https://twojstyl.pl/
https://swiatwiedzy.pl/

```
![Zrzut ekranu z 2020-12-02 11-41-28](https://user-images.githubusercontent.com/36385327/100862319-5375d480-3493-11eb-80ae-8165e7f7cdc7.png)

Social
https://swiatwiedzy.pl/
![Zrzut ekranu z 2020-12-02 11-41-50](https://user-images.githubusercontent.com/36385327/100862368-612b5a00-3493-11eb-8dff-3f4ec4ee03c1.png)

**Comment by krystian3w** [comment]
Na stylu tylko miga (#17935), czyli pomysł z ubijaniem iframe lub pliku CSS powoduje, że dolna połowa ekranu jest na sekundę czarna.

świat wiedzy nie łapie się na generyk `pl` ani generyk Kiboke.
