### ISSUE TITLE
trackitonline.ru [Incorrect Blocking]

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#17931]
### Issue URL
 [https://es.trackitonline.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fes.trackitonline.ru%2F)
### Comment
> Search form is blocked by `~allegro.pl,~dipp.pl,~motobanda.pl##.advert`

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/svGcLzJ.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/IM8x0fM.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.23
Browser: | Edge
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard French, <br/>AdGuard Russian, <br/>AdGuard Chinese, <br/>AdGuard German, <br/>AdGuard Dutch, <br/>AdGuard Spanish/Portuguese, <br/>EasyList China, <br/>EasyList Italy, <br/>Liste AR, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>Dandelion Sprout's Nordic Filters

**Comment by MajkiIT** [comment]
@Alex-302 Thanks
