### ISSUE TITLE
bstok.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#17955]
@ admin

- ktoś zrobił literówkę / chochlika: postawił niepotrzebną kropkę `.` na początku filtra, 
przez którą cały filtr nie działa i wyciekają reklamy na stronie (ale na szczęście bystre oko zaby-moniki czuwa):
https://github.com/MajkiIT/polish-ads-filter/blob/47eac8891333c6e4d48aff856e3bcf7251e0a095/polish-adblock-filters/adblock.txt#L4837

**Comment by MajkiIT** [comment]
@zaba-monika Dzięki 
https://github.com/MajkiIT/polish-ads-filter/commit/4ec0442c3837a018adacbffc3ab629927ed46301#diff-eab2aaf469314f57267f6f71855a766738837ca60234d6105317854abe61152c
