### ISSUE TITLE
piotrkow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1796]
cookies na dole 

Używamy plików cookies, aby ułatwić Ci korzystanie z naszego serwisu oraz do celów statystycznych. Jeśli nie blokujesz tych plików, to zgadzasz się na ich użycie oraz zapisanie w pamięci urządzenia. Pamiętaj, że możesz samodzielnie zarządzać cookies, zmieniając ustawienia przeglądarki. Korzystanie z serwisu oznacza akceptację Polityki Prywatności.

**Comment by kerbenii** [comment]
Sprawdź proszę czy działa:
`piotrkow.pl###coocies_warning`

**Comment by FadeMind** [comment]
**Adblock & uBlock polish cookies filters** ogarnia temat
```
##div[class*="cookie"]
```
@MajkiIT
