### ISSUE TITLE
zegocina.in

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#17977]

**Comment by MajkiIT** [comment]
nie widzę reklam .... a ty masz?

**Comment by krystian3w** [comment]
Prawa kolumna:

`#?#.wpb_wrapper .td_block_template_1:-abp-contains(Reklama)`

PS filtr średnio wydajny, sprawdza 17 elementów pod istnienie tekstu `Reklama`.

**Comment by MajkiIT** [comment]
@krystian3w dzięki
