### ISSUE TITLE
bezprawnik.pl

### ISSUE THREAD

**Issue by ChieftainY2k** [MajkiIT/polish-ads-filter#18013]
### Zrzut ekranu 
![image](https://user-images.githubusercontent.com/968529/101182728-c6777a80-364e-11eb-9e1f-0f91b43d1122.png)

### Link bezpośredni 
https://bezprawnik.pl/faktura-z-google-play/

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. Wejść na stronę https://bezprawnik.pl/faktura-z-google-play/

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Firefox 83.0 , Win10 x64

**Rozszerzenia i skrypty:** 
Noscript, HTTPS Everywhere

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Oficjalne polskie filtry przeciwko alertom o Adblocku 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by ChieftainY2k** [comment]
Randomizowane klasy elementów, trzeba będzie zablokować po zawartości

**Comment by ChieftainY2k** [comment]
![image](https://user-images.githubusercontent.com/968529/101182863-f757af80-364e-11eb-9af3-ebaa7d154112.png)

**Comment by zaba-monika** [comment]
- u mnie nie ma anty-adblocka
- jaki masz adblocker?
- tak czy inaczej spróbuj dodać którąś z tych reguł, albo wszystkie na raz lub ich kombinacje:
`@@||bezprawnik.pl^$generichide`
`@@||bezprawnik.pl^$specifichide`
`@@||www.google-analytics.com/analytics.js$script,domain=bezprawnik.pl`
`@@||www.googletagservices.com/tag/js/gpt.js$script,domain=bezprawnik.pl`

**Comment by ChieftainY2k** [comment]
Dodanie reguły `@@||bezprawnik.pl^$generichide` pomogło, dziekuję za pomoc!

**Comment by krystian3w** [comment]
Naprawione dla uBO odgórnie, do testów trzeba użyć ABP/Adblock/AdGuard.
