### ISSUE TITLE
instagram.com

### ISSUE THREAD

**Issue by domino264** [MajkiIT/polish-ads-filter#18034]
![2020-12-06 (3)](https://user-images.githubusercontent.com/75551768/101269186-3596c100-376c-11eb-80ee-b5afcd226cc6.png)

**Comment by krystian3w** [comment]
Blokowane jak zmienisz ABP na uBlock Origin lub AdGuard:

https://github.com/MajkiIT/polish-ads-filter/blob/4b7f1355e35d8dc78982f96329b85e3445f04824/cookies_filters/cookies_uB_AG.txt#L173-L174

Lub zaktualizujesz dodatek IDCAC do wersji 3.2.6 - Kiobke wszystko co ma zablokowany scroll naprawia we własnym dodatku a nie filtrem CSS:

> https://github.com/MajkiIT/polish-ads-filter/blob/4b7f1355e35d8dc78982f96329b85e3445f04824/cookies_filters/cookies_uB_AG.txt#L174

**Comment by zaba-monika** [comment]
> Blokowane jak zmienisz ABP/AdBlock na uBlock Origin lub AdGuard:

- `uBlock Origin` lub `AdGuard` nie jest wymagany...

> Lub zaktualizujesz dodatek IDCAC

- dodatek IDCAC te nie jest wymagany (tylko lista)...

<br>

- więc gdy ktoś używa `ABP`  to czy jednak zgłoszenie nie kwalifikuje się do `Polska Zgoda Ciasteczkowa` 
(jeśli nie da się naprawić w `Polskie Filtry RODO-Ciasteczkowe`?)
- pytam bo już się pogubiłam i od razu to samo pytanie odnośnie: https://github.com/MajkiIT/polish-ads-filter/issues/18047#issuecomment-739516507

**Comment by krystian3w** [comment]
Do PCC nie, bo można zainstalować uBO.

Blokowane przewijanie to jeszcze nie warunek by PCC akceptowało komunikat (dopiero stwierdzenie uszkodzeń jak komunikat jest ukrywany np. niezaładowane wideo, zablokowany formularz logowania).

**Comment by zaba-monika** [comment]
- spoko, czyli to jest na zasadzie: wymagane to i to, ale jak coś nie będzie ukryte na tych minimalnych wymaganiach, a jest ukryte gdy zmieni się `ABP` na `uBO/AG` albo liste `IDCAC` na dodatek `IDCAC`, to musisz se zmienić bo my nie naprawiamy teraz łapię

**Comment by krystian3w** [comment]
Dodatek IDCAC trzeba sprawdzać czy nie jest to "lenistwo", gdy Kiboke nie chce wprowadzać filtrów:

* `##body:style(overflow: initial !important;)` lub 
* `##body, body > *:style(filter: none !important;)`

Dodatkowo np. Evidon i OneTrust trzeba testować na okoliczność białej strony (kompletne zepsucie) lub braku filmów (Kiboke pierwsze generycznym JS zamyka, drugi najczęściej po zgłoszeniu dopisuje do filtru klikającego).
