### ISSUE TITLE
speedtest.net

### ISSUE THREAD

**Issue by domino264** [MajkiIT/polish-ads-filter#18035]
![2020-12-06 (4)](https://user-images.githubusercontent.com/75551768/101269740-3c283700-3772-11eb-9fa2-ab7f937ce829.png)

**Comment by zaba-monika** [comment]
To jest już ukrywane przez:
- **dodatek** I Don't Care About Cookies

**Comment by domino264** [comment]
> To jest już ukrywane przez:
> 
> * **dodatek** I Don't Care About Cookies

Mam aktualną wersję na chrome i niestety nie działa.

**Comment by krystian3w** [comment]
Więc zalecamy czekanie na premierę dodatku 3.2.7

**Comment by zaba-monika** [comment]
> domino264 :
> > zaba-monika : To jest już ukrywane przez:
> > 
> > * **dodatek** I Don't Care About Cookies
> 
> Mam aktualną wersję na chrome i niestety nie działa.

Na `Firefox` i `Chropera`:
- jest ukrywane przez **dodatek** `I don't care about cookies 3.2.6`
- natomiast nie jest ukrywane przez **listę** `I don't care about cookies`
- albo jakiś dziwny przypadek, że nie działa tylko na `Chrome`
- albo masz **listę** a nie **dodatek**
