### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by domino264** [MajkiIT/polish-ads-filter#18033]
![2020-12-06 (1)](https://user-images.githubusercontent.com/75551768/101269148-d638b100-376b-11eb-98b6-5b70f5a0b2e8.png)

**Comment by krystian3w** [comment]
* Blokowane jak masz uBlock Origin.

* AdGuard dla Facebook blokuje [filtry proceduralne](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters) z obcych projektów: https://github.com/AdguardTeam/FiltersRegistry/blob/91d77880aca97277bbf221c4bc1bba43a8978e4a/filters/exclusions.txt#L24-L26, więc dla FB musisz aktywować wtedy w AdGuard Annoyance.

* IDCAC jako dodatek 3.2.6 powienien poprawnie zamykać pop-up

**Comment by krystian3w** [comment]
@zaba-monika to się może kwalifikować na listę "wstydu"

**Comment by zaba-monika** [comment]
- ok to w takim razie dodaję na Listę Wstydu
