### ISSUE TITLE
pikio.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1803]
![image 033](https://cloud.githubusercontent.com/assets/9846948/21577810/bbdd84bc-cf68-11e6-83e6-d36c36f10a9a.png)

```
pikio.pl###modal
```

**Comment by F4z** [comment]
Możesz sprawdzić czy działa?
`||pikio.pl/wp-content/plugins/wp-adblock-dedect/dedect.js$script`

**Comment by FadeMind** [comment]
@F4z działa.

**Comment by mathew85** [comment]
Adblock wrócił:

![image](https://cloud.githubusercontent.com/assets/11385099/23102159/2b943366-f6a4-11e6-9a3f-866a5e36eb0e.png)

**Comment by F4z** [comment]
Dla uBlocka:
`pikio.pl##script:inject(fuckadblock.js-3.2.0)`

**Comment by xxcriticxx** [comment]
@mathew85 zamotowales ten script co ostatnio tobie mowilem?

**Comment by mathew85** [comment]
Z skryptem rzeczywiście nie ma, ale dodałem go później.
@F4z Twoja reguła też działa :thumbsup:

**Comment by xxcriticxx** [comment]
cool
