### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by domino264** [MajkiIT/polish-ads-filter#18045]
![2020-12-06 (6)](https://user-images.githubusercontent.com/75551768/101279027-9e5b5900-37bf-11eb-94f0-229bc431b37d.png)

**Comment by zaba-monika** [comment]
Duplikat wątku: https://github.com/MajkiIT/polish-ads-filter/issues/15243, do zamknięcia, należy zgłaszać w istniejącym wątku.

@xxcriticxx

**Comment by xxcriticxx** [comment]
please see https://github.com/MajkiIT/polish-ads-filter/issues/15243
