### ISSUE TITLE
tvn24.pl/tvnwarszawa

### ISSUE THREAD

**Issue by domino264** [MajkiIT/polish-ads-filter#18044]
![2020-12-06 (5)](https://user-images.githubusercontent.com/75551768/101278817-45d78c00-37be-11eb-99bf-5be279d64877.png)

**Comment by zaba-monika** [comment]
Podobnie jak tu https://github.com/MajkiIT/polish-ads-filter/issues/18047, kolejne fałszywe zgłoszenie,
bo ten komunikat jest już ukrywany przez:
- **dodatek** I Don't Care About Cookies
- dodatek Polska Ciasteczkowq Zgoda

Niestety alo znowu lecisz na listę hańby.

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishCookieConsent#jak-zainstalowa%C4%87

inaczej żadne wideo nie startuje, można powiedzieć że poprawnie skonstruowany pop-up o polityce prywatności a nie lipa by się tylko prawnicy nie przyczepili.
