### ISSUE TITLE
popundery na stronach z rabatami

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#18048]
Kontynuacja #17906:

Podobne pop-undery jak klikamy "pokaż kod" na stronie głównej.

```
$popunder,domain=alerabat.com
```

 znowu brak pomysłu dla ABP/AdGuard - może @zaba-monika nowy ma?

**Comment by MajkiIT** [comment]
@krystian3w dzięki

**Comment by zaba-monika** [comment]
Takich stron jest więcej:
- https://kodyrabatowe.olx.pl/
- https://kod.rabatowy.pl/benevento
- https://salesandshopping.pl/wydarzenia/weekend-znizek-z-magazynem-wysokie-obcasy-extra-w-calej-polsce-17-19-wrzesnia-2020-29631

Niestety, pomimo, że wszystkie strony stosują ten sam trick w postaci otwierania "popundera", to kod wykonywany pod przyciskiem `Pokaż kod` na tych stronach różni się od tego z https://github.com/MajkiIT/polish-ads-filter/issues/17906, a nawet między tymi stronami też się czasem różni (chociaż czasem np. 2 strony mają taki sam) więc trzebaby kilka nowych reguł `js` , a nawet nie wiadomo czy da rady wymyślić regułę dla każdej strony.

@MajkiIT

**Comment by zaba-monika** [comment]
- na `uAssets` też przed chwilą mieli jakieś zgłoszenie ze stronami z "popunderami" https://github.com/uBlockOrigin/uAssets/issues/8332
- jak widac jakiś wysyp takich stron nie tylko u nas

**Comment by krystian3w** [comment]
No to na razie zamykam z racji braku pomysłów dla ABP/AdGuard i `rabatowy.pl` (same rraczej się nie pojawią).

**Comment by zaba-monika** [comment]
- może inni nie mają pomysłów, ale jeśli chodzi o mnie to po prostu nie miałam czasu się tym zająć póki co

**Comment by zaba-monika** [comment]
> krystian3w : https://github.com/MajkiIT/polish-ads-filter/issues/18048#issuecomment-741616588 :  i `rabatowy.pl`

- sprawdziłam tę stronę i na Operze (Chromowatych) działa `$popunder` więc można dodać...
- natomiast rzeczywiście nie działa na Firefox więc:
- stworzyłam: https://github.com/uBlockOrigin/uAssets/issues/8348
- a póki co można dodać też `kod.rabatowy.pl##+js(nostif, gotoUrl, 300)` pod uBO pod Firefox oraz odpowiednik pod AG pod wszystkie przeglądarki

**Comment by zaba-monika** [comment]
>zaba-monika : https://github.com/MajkiIT/polish-ads-filter/issues/18048#issuecomment-742460675 :  `kod.rabatowy.pl##+js(nostif, gotoUrl, 300)` pod uBO pod Firefox

- jak pisałam, tylko **pod Firefox** czyli trzeba użyć dyrektywy, bo gdy `$popunder` połączymy z tym `+js`, 
to  `+js` nadpisuje `$popunder` i `$popunder` nie działa
- więc poprawnie ma być tak:

```
!#if env_firefox
kod.rabatowy.pl##+js(nostif, gotoUrl, 300)
!#endif
```
