### ISSUE TITLE
gratyzchaty.pl

### ISSUE THREAD

**Issue by domino264** [MajkiIT/polish-ads-filter#18046]
![2020-12-06 (7)](https://user-images.githubusercontent.com/75551768/101279158-9f40ba80-37c0-11eb-978a-b4d00a0f51ff.png)

**Comment by zaba-monika** [comment]
Przeglądarki nie otwierają tej strony, (nie wiem jak Chrome albo jakieś inne):

<details not-open>
<summary>screenshoot Firefox</summary>



![capture_196_06-12-2020_13-04-28](https://user-images.githubusercontent.com/72980128/101279602-969db380-37c3-11eb-8ca9-7628dbbe5b43.png)
</details>


<details not-open>
<summary>screenshoot Chropera</summary>



![capture_195_06-12-2020_13-04-26](https://user-images.githubusercontent.com/72980128/101279618-b7fe9f80-37c3-11eb-8870-ef76d2c963c0.png)

</details>

**Comment by AroKol78** [comment]
> Przeglądarki nie otwierają tej strony, (nie wiem jak Chrome albo jakieś inne)

+Basilisk+PaleMoon (The certificate expired on 2 października 2020 13:42. The current time is 6 grudnia 2020 13:31.)

potwierdzam https://github.com/MajkiIT/polish-ads-filter/issues/18046#issuecomment-739493569

**Comment by domino264** [comment]
Mają problem z certyfikatem SSL.

**Comment by krystian3w** [comment]
`###wymog_uee`

**Comment by krystian3w** [comment]
https://www.nerdydata.com/reports/wymog_uee/47b3d046-9d7e-45e8-9465-6456307d0962
https://publicwww.com/?q=%23wymog_uee
