### ISSUE TITLE
patronite.pl

### ISSUE THREAD

**Issue by domino264** [MajkiIT/polish-ads-filter#18047]
![2020-12-06 (8)](https://user-images.githubusercontent.com/75551768/101279231-22621080-37c1-11eb-91d5-48872efc9770.png)

**Comment by zaba-monika** [comment]
Ten komunikat jest już ukrywany zarówno przez:
- **dodatek** I Don't Care About Cookies jak i 
- Polskie Filtry RODO-Ciasteczkowe

**Comment by zaba-monika** [comment]
@domino264 

Przed zgłoszeniem komunikatów ciasteczkowych zapoznaj się z instrukcją:
https://majkiit.github.io/polish-ads-filter/#polskie_filtry_rodo-ciasteczkowe

Musisz mieć dodane:

- `Polskie Filtry RODO-Ciasteczkowe` lub `Polskie Filtry Elementów Irytujących`
- dodatek lub listę `I don't care about cookies`
- dodatek `Polska Ciasteczkowa Zgoda`

**Comment by zaba-monika** [comment]
- hmm jednak pod ABP to jest ukrywane tylko przez **dodatek** `I Don't Care About Cookies`, 
który nie jest wymagany (wymagana jest tylko lista) więc skoro wymagana jest tylko lista `IDCAC`, to wynika z tego że jednak poprawne zgłoszenie i to powinno być naprawione w: `Polskie Filtry RODO-Ciasteczkowe` a gdy się nie da to w `Polska Ciasteczkowa Zgoda` ...?

**Comment by krystian3w** [comment]
ABP nie pozwala usunąć rozmazania pod pop-upem: https://github.com/MajkiIT/polish-ads-filter/blob/4b7f1355e35d8dc78982f96329b85e3445f04824/cookies_filters/cookies_uB_AG.txt#L126

> Jak zezwolą na użwanie globalnie np. `#$#remove-class blur` z [**MutationObserver**](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to wtedy pewnie się poprawi.
> 
> https://help.eyeo.com/adblockplus/snippet-filters-tutorial

---

Skoro on widzi blur, to musi mieć ABP / AdBlock, bo wykluczam że aż 6 stron serwuje mu dziwne testy A/B.

**Comment by zaba-monika** [comment]
> ABP nie pozwala usunąć rozmazania pod pop-upem: 

- ale `Polska Zgoda Ciasteczkowa` pozwala...? I tylko o to pytałam czy nie powinno być to naprawione w `Polska Zgoda Ciasteczkowa`, ale odpowiedź już dostałam w https://github.com/MajkiIT/polish-ads-filter/issues/18034#issuecomment-739519988
