### ISSUE TITLE
szukam-informacji.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#18051]
![capture_199_06-12-2020_19-15-30](https://user-images.githubusercontent.com/72980128/101288531-6ec84300-37f7-11eb-8e18-62e8b62c51ff.png)

**Comment by bug-rules** [comment]
Nie ma na co przekierować, pasek w headerze wycięty, biała luka zostaje.

**Comment by zaba-monika** [comment]
- @bug-rules ale mi chodzi o to co zaznaczone czerwonym obramowaniem:

![22222](https://user-images.githubusercontent.com/72980128/101366288-12236180-38a5-11eb-89ad-0ab7373143b1.png)

**Comment by bug-rules** [comment]
To tak jakby teraz na innych stronach wykastrować zakładki:

`github.com/rodo`

homepage tej strony jest używany jako odsyłacz dla kilku portali.

**Comment by zaba-monika** [comment]
> homepage tej strony jest używany jako odsyłacz dla kilku portali.

- acha, nie wiedziałam, bo w większości przypadków, jeśli takie coś jest używane jako odsyłacz, to leży na swojej poddomenie np. `cookies.bermar.pl` i dopiero gdy leży na swojej poddomenie to nigdy nie zgłaszam
