### ISSUE TITLE
 orionblues.pinger.pl (reopen)

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#18069]
- reopen https://github.com/MajkiIT/polish-ads-filter/issues/18030 bo dalej to jest (pomimo, że niby w `PCZ` jest domena `WP` `pinger.pl` i powinno zdaje się klikać także na poddomeny) 
- a może to błąd po stronie strony bo po wejściu na stronę bardzo długo się ona wczytuje jakby jakaś zacięta pętla js chodziła przez jakąś prawie minutę zanim się uspokoi i przez cały czas rdzeń procesora obciążony na 100%, w loggerze jakieś zapętlone żądania youtube, dzieje się tak zarówno na `Firefox` jak i `Chropera`, nawet z wyłączonym adblockerem, jak się wkurzę to zgłoszę stronę do `uAssets` do dodania na listę nadużyć zasobów `uBlock filters – Resource abuse` : `||orionblues.pinger.pl^$all`, chyba, że jakoś namierzyć i zablokować problematyczny skrypt filtrem blokującym, jeśli tylko ten skrypt nie jest krytyczny / wymagany do działania strony, bo wtedy to trzeba próbować skrypletem `+js`, pamiętam kilka razy mi się zdarzyło namierzać i blokować skrypt na stronach które w podobny sposób nadużywały

**Comment by bug-rules** [comment]
`/^https\:\/\/(www\.)?youtube(-nocookie)?.com\/embed\//$3p,frame,object,redirect=click2load.html,domain=~withgoogle.com|~withyoutube.com|~reddit.com`

Jak chcesz to zgłaszaj by dodali jak MajkiIT nie doda tam blokady ładowania ramek.

Z zablokowanymi ramkami raczej nie ma skoku CPU ani lagu dla PCC.

**Comment by zaba-monika** [comment]
- dodałam ale dalej są obydwa problemy: wyskakuje komunikat RODO + strona zamula
- chyba regex nie łapie..

**Comment by zaba-monika** [comment]
sorry działa miałam nie aktywne "Moje Filtry"

**Comment by zaba-monika** [comment]
Już wczoraj to zauważyłam, ale byłam zbyt śpiąca żeby o tym wspomnieć: w tym regexie są jeszcze 2 literówki:
- niepotrzebnie uwsteczniony dwukropek `\:` ==> `:` - dwukropków w regexach nie potrzeba uciekać
- nieuwsteczniona kropka `.com` ==> `\.com` - kropki w domenach należy uwsteczniać, bo inaczej oznaczają dowolny znak

@bug-rules jak coś to [TUTAJ](https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/f00621596581430b0d43d03316abe8d68a0d6b45) też powielone literówki do poprawki
@MajkiIT nie wiem czy ty tu jeszcze zajrzysz

**Comment by bug-rules** [comment]
W sumie jeszcze trzeba by przenieść do suplementu uBO, by nie zablokowało w ABP całkowicie filmu jak filtr wykona się bez modyfikatorów (oleje 3, typy i nieznane redirect).

**Comment by zaba-monika** [comment]
Poprawił, za wyjątkiem https://github.com/MajkiIT/polish-ads-filter/issues/18069#issuecomment-740463253 :

>  - niepotrzebnie uwsteczniony dwukropek `\:` ==> `:` - dwukropków w regexach nie potrzeba uwsteczniać
