### ISSUE TITLE
mapaodoru.pgkslupsk.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#18064]
![capture_215_07-12-2020_16-17-47](https://user-images.githubusercontent.com/72980128/101368731-c7efaf80-38a7-11eb-8f31-e1e746651377.png)

**Comment by bug-rules** [comment]
Jak chcesz by PCC akceptowało takie coś odgórnie (czyli też w newsletterach zamiast je wycinać), to trzeba by raczej zaproponować jako ogólne ulepszenie.

Dodatkowo `clickTimeout` ani `clickInteractive` nie umie kilką by było:

- [X] wyrażam
