### ISSUE TITLE
tabletowo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1808]
reklama ASUS ZENBOOK3

**Comment by FadeMind** [comment]
```
tabletowo.pl##.textwidget
```
Ta reguła usuwa dodatkowo inne reklamy:
![image 035](https://cloud.githubusercontent.com/assets/9846948/21578233/935f7d1e-cf78-11e6-9456-6751f83c715e.png)
@xxcriticxx  proszę sprawdzić ;)
