### ISSUE TITLE
portalplock.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18111]

**Comment by MajkiIT** [comment]
```
portalplock.pl##.text-center.d-block, .ads-programmatic.d-lg-block.d-none
portalplock.pl##h6:-abp-contains(Reklama)
```

**Comment by krystian3w** [comment]
zabrakło `#?#`, znowu będzie lament, że nie działa w ABP/AdBlock.

`.text-center.d-block` = może wyciąć każdy wycentrowany "blok" w przyszłości.

**Comment by krystian3w** [comment]
`.d-lg-block.d-none` lepiej usunąć z filtra, bo reklama będzie wracać jak ktoś dokona poprawek i usunie kłócące się klasy.
