### ISSUE TITLE
*.wp.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#18122]
https://github.com/MajkiIT/polish-ads-filter/issues/17877#issuecomment-741712782

**Comment by zaba-monika** [comment]
@MajkiIT https://github.com/MajkiIT/polish-ads-filter/issues/17877#issuecomment-741783852

**Comment by zaba-monika** [comment]
@MajkiIT jeszcze to https://github.com/MajkiIT/polish-ads-filter/issues/17877#issuecomment-741786361

**Comment by MajkiIT** [comment]
@zaba-monika chyba jest komplet

**Comment by zaba-monika** [comment]
Tak zgadza się, bo wdupiłeś się podobnie jak krystian3w niedawno temu: https://github.com/MajkiIT/polish-ads-filter/issues/17906#issuecomment-736289952 (oczywiście nieświadomie i nie mam pretensji, jedynie wyjaśniam) z drugim commitem i referencją dokładnie w momencie kiedy przenosiłam drugi komentarz sprzed pierwszej referencji za nią, usuwając komentarz i tworząc na nowo (bo z pośpiechu się pomyliłam i zrobiłam najpierw drugi komentarz a potem referencję do pierwszego komentarza, zamiast odwrotnie), w ten sposób narpawiłam kolejność...ale i tak znowu ją rozdupczyłeś, teraz już nie cofnę komentarza przed twojąreferencję bo do tyłu się nie da...
