### ISSUE TITLE
goodie.pl

### ISSUE THREAD

**Issue by crazyjack79** [MajkiIT/polish-ads-filter#18146]
### Zrzut ekranu 
![Schowek01](https://user-images.githubusercontent.com/35058050/101761593-a3304d80-3adc-11eb-83ab-91a8dc87c6f3.jpg)

### Link bezpośredni 
www.goodie.pl

### Co trzeba zrobić, aby pojawił się błąd?
1. wpisuję adres www.goodie.pl
2. biała strona
3. jak wyłączę filtry Polskie Filtry RODO-Ciasteczkowe to strona się ładuje

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Microsoft Edge 87.0.664.57
**Rozszerzenia i skrypty:** 

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Polskie Filtry RODO-Ciasteczkowe
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Nie umiem reprodukować.

Założenia są dwa:

- masz jakiś test A/B z nowym layoutem
- uBO stabilne ma jakiś bug i w wersji dev już nie występuje.

**Comment by zaba-monika** [comment]
- dziwne, weszłam i rzeczywiście po chwili zrobiła się biała strona
- wyłączyłam dodatki: `I don't care about cookies` + `Polska Ciasteczkowa Zgoda`, przełądowałm stronę i już błędu nie ma
- włączyłam spowrotem obydwa dodatki i...błędu dalej nie ma

**Comment by krystian3w** [comment]
Ja w Edge obu nie mam i błędu też nie, zostaje wywalić stare filtry i najnowszy zabezpieczyć dłuższym "`abp-has`".

**Comment by zaba-monika** [comment]
- odświeżyłam stronę po 5 minutach i znowu biała strona

**Comment by krystian3w** [comment]
Że pusty tag `<body>` lub `<html>`?

**Comment by zaba-monika** [comment]
- niby ten filtr powoduje białą stronę, naprawa: 
`goodie.pl#@#body > div[class]:not(id):last-of-type:has(a[href="/ochrona-danych"])`

**Comment by krystian3w** [comment]
Dziwne, filtr nie tyka nawet BODY:

![obraz](https://user-images.githubusercontent.com/35370833/101778030-99feab00-3af3-11eb-9950-b1df5e04fae1.png) |
--- |

**Comment by krystian3w** [comment]
> `goodie.pl#@?#body > div[class]:not(id):last-of-type:-abp-has(a[href="/ochrona-danych"])`

Błędne, AdamWr miał rację, ABP pozwala na omijanie tam pytajnika.

**Comment by krystian3w** [comment]
Postestujcie sobie to:

`goodie.pl#?#body > #body-wrapper ~ div[class]:not(id):last-child:-abp-has(> div > span > a[href="/ochrona-danych"])`

**Comment by crazyjack79** [comment]
Dodałem powyższy wpis do moich filtrów - dalej strona jest biała

**Comment by krystian3w** [comment]
Źle testujesz, musisz użyć wyłączającego stary i ten nowy:



    goodie.pl#@#body > div[class]:not(id):last-of-type:-abp-has(a[href="/ochrona-danych"])
    goodie.pl#?#body > #body-wrapper ~ div[class]:not(id):last-child:-abp-has(> div > span > a[href="/ochrona-danych"])

**Comment by krystian3w** [comment]
PS. Ja już wiem czemu to tak działa (m.in. testowanie nodów nie puszcza a winnego nie widać w dom debuggerze - `</>`).

**Comment by zaba-monika** [comment]
> krystian3w : https://github.com/MajkiIT/polish-ads-filter/issues/18146#issuecomment-742522762
> krystian3w : https://github.com/MajkiIT/polish-ads-filter/issues/18146#issuecomment-742538138

Działa bez problemów.
