### ISSUE TITLE
hrkgame.com

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#18147]
### Issue URL (Incorrect Blocking)
 [https://www.hrkgame.com/en/account/settings/security](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.hrkgame.com%2Fen%2Faccount%2Fsettings%2Fsecurity)
### Comment
> Click on 2-Step Verification Activate > when adguard works - popup overlay will not show. When adguard is disabled - all is fine - popup works.  You have to login to see this page. 

https://github.com/AdguardTeam/AdguardFilters/issues/69498
Caused by these rules from `Polskie Filtry Ciasteczkowe`:
```
7ryb.pl,etransport.pl,grupawsparcia.pl,hrkgame.com#$#.dimmable, .dimmed { overflow: auto !important; }
7ryb.pl,etransport.pl,grupawsparcia.pl,hrkgame.com##.modals.dimmer
```

I hope this is a correct repository)

> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/s0AqTqv.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/HwTzOJI.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.23
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist<br/><br/><b>Language-specific:</b><br/> Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>Polskie Filtry Ciasteczkowe, <br/>KAD - Przekręty, <br/>Polish Anti Adblock Filters, <br/>AlleBlock

**Comment by krystian3w** [comment]
@zaba-monika / @gwarser czemu tam nie chce działać `watch-attr`?

```
hrkgame.com#@#.modals.dimmer
hrkgame.com##.modals.dimmer.ui > .ui.gdpr.visible:upward(1)
hrkgame.com##html:root .modals.dimmer.ui > .ui.gdpr.hidden:upward(1):style(display: flex !important;)
```

Próbuję sprawdzać zmiany klasy `.gdpr.visible` <===> `.gdpr.hidden`

Sprawdzając - winny nie jest `:upward` ani `:has`.

**Comment by gwarser** [comment]
@krystian3w ups...

	[rdk@on uBlock-git]$ git bisect bad && ./tools/make-chromium.sh 
	35aefed92616cbfb75f12f37c7ea7fb3a3cc3369 is the first bad commit
	commit 35aefed92616cbfb75f12f37c7ea7fb3a3cc3369
	Author: Raymond Hill <rhill@raymondhill.net>
	Date:   Mon Sep 7 08:28:01 2020 -0400
	
	    Add support to chain `:style()` to procedural operators
	    
	    Related issue:
	    - https://github.com/uBlockOrigin/uBlock-issues/issues/382
	    
	    Additionally, remnant code for pseudo-user stylesheets
	    has been removed. Related commit:
	    - https://github.com/gorhill/uBlock/commit/5c68867b92735931a791dfedf4ef9608cc364862
	
	 platform/chromium/vapi-background.js     |  23 ++-
	 platform/chromium/vapi-client.js         |   8 +-
	 src/js/background.js                     |   4 +-
	 src/js/contentscript.js                  | 278 ++++++++++++-------------------
	 src/js/cosmetic-filtering.js             | 167 ++++++-------------
	 src/js/epicker-ui.js                     |  17 +-
	 src/js/scriptlets/cosmetic-logger.js     |   6 +-
	 src/js/scriptlets/dom-inspector.js       |  23 ++-
	 src/js/scriptlets/dom-survey-elements.js |   4 +-
	 src/js/scriptlets/epicker.js             | 180 ++++++--------------
	 src/js/static-filtering-parser.js        |  43 +++--
	 11 files changed, 281 insertions(+), 472 deletions(-)
	*** uBlock0.chromium: Creating web store package
	*** uBlock0.chromium: copying common files
	*** Packaging assets in dist/build/uBlock0.chromium/assets... rm: cannot remove 'dist/build/uBlock0.chromium/assets/ublock/resources.txt': No such file or directory
	done.
	*** uBlock0.chromium: Generating meta...
	*** uBlock0.chromium: Package done.
	[rdk@on uBlock-git]$

**Comment by krystian3w** [comment]
To naprawiamy czy je wygaszamy?

**Comment by gwarser** [comment]
Okazało się że w ogóle "odkrywanie" nie działa.

AdGuard zaimplementował `watch-attr`? Nie widzę dokumentacji w https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters

**Comment by krystian3w** [comment]
Dodali niby natywne, ale musisz sprawdzać czy element ukrywa `style="display: none !important"` czy `tabs.insertCSS()`.

Jakieś tam wsparcie dla `tabs.insertCSS()` dodali dla AdGuard 3.3.2+.

**Comment by gwarser** [comment]
Na chrome nie działa. Z tego co rozumiem, filtry z `#?#` są dodawane w atrybucie `style`.

**Comment by krystian3w** [comment]
Tak ale ExtendedCSS nie powinien być odrazu konwertowany na style, jak testowałem to z miesiąc temu w listopadzie to umiał dodatek używać `tabs.insertCSS()`.

Domyślnie `#?#` powwino się przekształcać w atrybut tylko jak napotka prosty filtr:

`example.org#?#h2`

lub CSS:

`example.org#$?#h2 { color: red }`

**Comment by gwarser** [comment]
Ah, ok, właśnie widzę, że  mi wstawia `style`. Ale AdGuard ma chyba identyczny błąd co uBO - jak kliknę drugi guzik to nic się nie dzieje, a dopiero jak kliknę pierwszy to się kwadrat pojawia. No chyba, że coś nie tak z moim testem jest.

**Comment by krystian3w** [comment]
@ameshkov can you recheck implementation for issue https://github.com/AdguardTeam/ExtendedCss/issues/77?

**Comment by gwarser** [comment]
@krystian3w https://github.com/ameshkov/web/pull/2
