### ISSUE TITLE
posilkiwchorobie.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#18155]
Ciasteczka + reklama z boku

### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/101803094-7302a200-3b10-11eb-80dc-7d8196c9671b.png)

![obraz](https://user-images.githubusercontent.com/32641928/101803108-772ebf80-3b10-11eb-9f97-0a0ae97bc27c.png)

### Link bezpośredni 

posilkiwchorobie.pl

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. 
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda (2020.12.10.0)
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances, Base, Mobile Ads
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List
11. AdGuard Tracking Protection
12. AdGuard Base, Mobile Ads
13. AdGuard Mobile Ads

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Zakładam, że to reklama wewnętrzna, nawet jak otworzy się np. `doz.pl`?

**Comment by MajkiIT** [comment]
To wew ... promują swój produkt a to producent
