### ISSUE TITLE
ppe.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1815]
ad block 

`http://www.ppe.pl/news/29640/zapraszamy-na-wizyte-do-siedziby-valve.html`

![capture](https://cloud.githubusercontent.com/assets/15007183/21578335/3548f51c-cf4a-11e6-9687-342cd25a1244.PNG)

**Comment by FadeMind** [comment]
http://reek.github.io/anti-adblock-killer/
