### ISSUE TITLE
holandia.wortale.net

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1816]
ad block

`https://holandia.wortale.net/holenderskie,ac91/kuchnia-holenderska-gin-jenever,218`

![capture](https://cloud.githubusercontent.com/assets/15007183/21578345/91fc772a-cf4a-11e6-8105-73460f4e641b.PNG)

**Comment by FadeMind** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/1805#issuecomment-269869299
