### ISSUE TITLE
Reklamy w google

### ISSUE THREAD

**Issue by Yolocaust2137** [MajkiIT/polish-ads-filter#18179]
Jak w temacie. Jakieś kilka dni temu zaczęły się pojawiać reklamy w google i nie wiem czy to wina któregoś filtru czy samego adguarda. Wcześniej wszystko było w porządku. Używam najnowszych filtrów do adguarda, które wziąłem stąd: https://majkiit.github.io/polish-ads-filter/
![333](https://user-images.githubusercontent.com/73483922/101987031-e67fed00-3c91-11eb-9d10-c272550465ee.png)
,

**Comment by zaba-monika** [comment]
- niby ja nie mam reklam nawet bez zaznaczonego "zezwalaj na stronach z wynikami wyszukiwania", ale pamiętam komuś kto używał Opery kiedyś w jakimś zgłoszeniu też wyskakiwały reklamy i  pomogło zazanczenie tej opcji, albo tej drugiej "zezwalaj w trybie incognito":

<details not-open>
<summary>zrzut ekranu 1</summary>


![capture_002_12-12-2020_16-22-40](https://user-images.githubusercontent.com/72980128/101987852-d28aba00-3c96-11eb-957d-e9cf3ae1acf8.png)
</details>


- niby ja nie mam reklam w AdGaurd nawet gdy mam zaznaczone "Nie blokuj pożądanych reklam":

<details not-open>
<summary>zrzut ekranu 2</summary>


![capture_003_12-12-2020_16-23-55](https://user-images.githubusercontent.com/72980128/101987878-e59d8a00-3c96-11eb-8e23-e0391158cff2.png)
</details>

- ponoć jest też jakiś błąd w AdGuard, że po instalacji nie włączają się automatycznie Polskie listy, ale ty zdaje się włączyłeś manualnie więc powinny zaskoczyć a nawet po ich odznaczeniu nie mam reklam:

<details not-open>
<summary>zrzut ekranu 3</summary>


![55555](https://user-images.githubusercontent.com/72980128/101988001-6197d200-3c97-11eb-9e4d-8bf611363ae9.png)

</details>

**Comment by AroKol78** [comment]
na "uboL" nie uraczyłem reklam
![db1fix](https://user-images.githubusercontent.com/70756447/99152904-1e047500-26a5-11eb-81aa-d0561833c5ed.PNG)

**Comment by krystian3w** [comment]
Na reddit było coś o nowym boksie z reklamami: https://pl.reddit.com/r/uBlockOrigin/comments/k96wt3/google_ads_are_back/

**Comment by AroKol78** [comment]
jak masz Opere - to może ustawienia wewnętrznego blokera

**Comment by krystian3w** [comment]
Nie, raczej opera wewnętrznym blokerem nie dokleiła tych reklam, dodatkowo to by był koniec Opery jakby zaczęła negować filtry sieciowe i kosmetyczne uBlock Origin.

**Comment by krystian3w** [comment]
Podobno bug w aplikacji AdGuard: https://github.com/AdguardTeam/AdguardFilters/issues/69696#issuecomment-743769072
