### ISSUE TITLE
gala.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#18172]
zablokowane filmy - napis "false":

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=gala.pl`

https://www.gala.pl/artykul/kapusta-z-grzybami-wigilijna-przepis-magdy-gessler-krok-po-kroku-181222102536

**Comment by zaba-monika** [comment]
- nie wystarczy, bo dalej film zablokowany i jest kolejny błąd "Media error: Format(s) not supported or source(s) not found":
<details not-open>
<summary>zrzut ekranu</summary>


![capture_047_12-12-2020_08-21-08](https://user-images.githubusercontent.com/72980128/101978126-02b06980-3c53-11eb-8661-9846c2b8943e.png)
</details>

- więc potrzebny jeszcze jeden whitelist: `@@||storage.platform.moviads.pl^$media,domain=www.gala.pl` 
- lub alternatywnie jeśli ktoś woli (ale raczej nie ma potrzeby jeśli poza filmami nic innego nie jest popsute) to może dodać `|~gala.pl` do:
https://github.com/MajkiIT/polish-ads-filter/blob/9f771e76c8687b91bdf83a76343587587cbbdfc0/polish-adblock-filters/adblock.txt#L4013

**Comment by zaba-monika** [comment]
@MajkiIT 

- skoro dodałeś oby dwa filtry, jeden z komentarza od krystian3w a drugi z mojego to dlaczego dałeś "kciuka w górę" tylko dla jego komentarza? nie wydaje się to sprawiedliwe, proszę postąp spawiedliwie i albo mi też pogratuluj kciukiem w górę, albo usuń filtr który skopiowałeś z mojego komentarza
