### ISSUE TITLE
scigacz.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1818]
ad block 

`http://www.scigacz.pl/Jak,sprzedac,motocykl,kilka,podstawowych,zasad,21222.html`

![capture](https://cloud.githubusercontent.com/assets/15007183/21578367/3b59935c-cf4b-11e6-87fc-6cd2802ca3ae.PNG)

**Comment by FadeMind** [comment]
http://reek.github.io/anti-adblock-killer/
