### ISSUE TITLE
mylead.global

### ISSUE THREAD

**Issue by myleadd** [MajkiIT/polish-ads-filter#18180]
Dzień dobry,
piszę w sprawie listy filtrów (https://github.com/MajkiIT/polish-ads-filter/blob/dde49920ee7d3e65d397fc735aff4e4401437ab4/polish-adblock-filters/adblock.txt), na której znajdują się domeny niewykorzystywane w reklamach.

Problem ten skutkuje chociażby niepokazywaniem się log tutaj:
https://promolovers.pl/

Z blockerem reklam prezentuje się to tak: https://prnt.sc/w17b66, przy czym bez blockera wygląda to tak https://prnt.sc/w17bc5

Przeglądarka: Firefox
Wtyczka: uBlock Origin 1.31.0
Listy filtrów: Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda

Byłbym bardzo wdzięczny za usunięcie domeny mylead.global z listy blokowanych domen w filtrach (pozycja 4133).

**Comment by MajkiIT** [comment]
Błąd poprawiony. Nie trzeba usuwać domeny.

**Comment by zaba-monika** [comment]
Zgadza się, wystarczyło do filtra dokleić wyjątek dla strony `mylead.global`, dzięki czemu filtr działa na wszystkich strnoach poza `mylead.global`.

**Comment by myleadd** [comment]
Działa, dziękuję najmocniej za pomoc
