### ISSUE TITLE
genapps.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#18199]
![Zrzut ekranu z 2020-12-14 09-47-28](https://user-images.githubusercontent.com/36385327/102059633-70929780-3df1-11eb-8802-b4f2a374106b.png)
![Zrzut ekranu z 2020-12-14 09-47-46](https://user-images.githubusercontent.com/36385327/102059640-72f4f180-3df1-11eb-9d00-4a404dd65c5a.png)

**Comment by MajkiIT** [comment]
`###container > .columns-container > .column-750, #content > div.columns-container > .column-750`
