### ISSUE TITLE
gloswielkopolski.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#18207]
Nie działają filmiki. Czasem po odświeżeniu filmik się pojawia ale po ponownym ponownie jest tylko szare tło.
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/102121161-cc860c00-3e43-11eb-884d-4f451f604880.png)

### Link bezpośredni 

https://gloswielkopolski.pl/gdzie-wyrzucic-karton-po-pizzy-nie-uwierzysz-jakie-to-skomplikowane-zasad-jest-cale-mnostwo/ar/c1-15338774

### Co trzeba zrobić, aby pojawił się błąd?
1. 
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda (2020.12.10.0)
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances, Base, Mobile Ads
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List
11. AdGuard Tracking Protection
12. AdGuard Base, Mobile Ads
13. AdGuard Mobile Ads

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by zaba-monika** [comment]
- bruździ lista `Polish Privacy Filters`, a dokładniej ten filtr: https://github.com/olegwukr/polish-privacy-filters/blob/2035fdb215feb66650b032dfbcf5e528c884d144/adblock.txt#L144
- naprawa do wyboru: wykluczenie ==> `||privacy-center.org^$domain=~gloswielkopolski.pl`
- lub whitelistiing:
`@@||sdk.privacy-center.org/*/loader.js$script,domain=gloswielkopolski.pl`
`@@||sdk.privacy-center.org/sdk.*.js$script,domain=gloswielkopolski.pl`
- tych stron z udzkodzonymi filmami może być więcej bo to jakaś grupa: https://github.com/MajkiIT/polish-ads-filter/issues/14609

**Comment by krystian3w** [comment]
Filmy może da się kolejny raz odratować po przez uaktualnienie metod na anty-adblock w playerze.

AdamWr z rok temu stwierdził, że player wymaga dopuszczenia Google Ads i niby działa, a uAssets wymyśliło filtry `aeld` i jakiś `redirect=`.

**Comment by krystian3w** [comment]
@majkiit / @olegwukr  mam odtrutkę dla uBO z pomocą `,badfilter`:

`||ppstatic.pl/assets/nsk/*/js/compiled/atoms/ads/branding-video.js$script,important,redirect=noopjs,domain=pl|eu,badfilter`

czyli to można zakomentować w oryginale.

---

Filtr set-constant (`##+js(set-constant, pp_adblock_is_off, trueFunc)`) można zmienić na taki:

`dziennikbaltycki.pl,dzienniklodzki.pl,dziennikpolski24.pl,dziennikzachodni.pl,echodnia.eu,expressbydgoski.pl,expressilustrowany.pl,gazetakrakowska.pl,gazetalubuska.pl,gazetawroclawska.pl,gk24.pl,gloswielkopolski.pl,gol24.pl,gp24.pl,gra.pl,gs24.pl,kurierlubelski.pl,motofakty.pl,naszemiasto.pl,nowiny24.pl,nowosci.com.pl,nto.pl,polskatimes.pl,pomorska.pl,poranny.pl,sportowy24.pl,strefaagro.pl,strefabiznesu.pl,stronakobiet.pl,telemagazyn.pl,to.com.pl,wspolczesna.pl##+js(aeld, , show)`

`Set-constant` i `noopjs` się po prostu przeterminowały już tam.

---

Jak ktoś ma czas może sprawdzić czy film leci z AdGuard / ABP / AdBlock.

**Comment by krystian3w** [comment]
Przy okazji do aktualizacji jest stare rozwiązanie anty-adblock @majkiit / @olegwukr:

`#@#+js(set-constant, pp_adblock_is_off, trueFunc)`

zmieniamy na:

`dziennikbaltycki.pl,dzienniklodzki.pl,dziennikpolski24.pl,dziennikzachodni.pl,echodnia.eu,expressbydgoski.pl,expressilustrowany.pl,gazetakrakowska.pl,gazetalubuska.pl,gazetawroclawska.pl,gk24.pl,gloswielkopolski.pl,gol24.pl,gp24.pl,gra.pl,gs24.pl,kurierlubelski.pl,motofakty.pl,naszemiasto.pl,nowiny24.pl,nowosci.com.pl,nto.pl,polskatimes.pl,pomorska.pl,poranny.pl,sportowy24.pl,strefaagro.pl,strefabiznesu.pl,stronakobiet.pl,telemagazyn.pl,to.com.pl,wspolczesna.pl##+js(aeld, , show)`

A filtr sieciowy `||ppstatic.pl/assets/nsk/*/js/compiled/atoms/ads/branding-video.js$script,important,redirect=noopjs,domain=pl|eu,badfilter` na taki:

`||ppstatic.pl/*/reklama.js$script,domain=dziennikbaltycki.pl|dzienniklodzki.pl|dziennikpolski24.pl|dziennikzachodni.pl|echodnia.eu|expressbydgoski.pl|expressilustrowany.pl|gazetakrakowska.pl|gazetalubuska.pl|gazetawroclawska.pl|gk24.pl|gloswielkopolski.pl|gol24.pl|gp24.pl|gra.pl|gs24.pl|kurierlubelski.pl|motofakty.pl|naszemiasto.pl|nowiny24.pl|nowosci.com.pl|nto.pl`

**Comment by krystian3w** [comment]
@kiboke this GDPR pop-up need disable filtering `sdk.privacy-center.org` on many Polish domains:

```
sdk.privacy-center.org$domain=~lequipe.fr|~telegraaf.nl|~gamepro.de|~gamestar.de|~dumpert.nl|~funradio.fr|~rtl.fr|~mundodeportivo.com|~gofeminin.de|~onmeda.de|~dziennikbaltycki.pl|~dzienniklodzki.pl|~dziennikpolski24.pl|~dziennikzachodni.pl|~echodnia.eu|~expressbydgoski.pl|~expressilustrowany.pl|~gazetakrakowska.pl|~gazetalubuska.pl|~gazetawroclawska.pl|~gk24.pl|~gloswielkopolski.pl|~gol24.pl|~gp24.pl|~gra.pl|~gs24.pl|~kurierlubelski.pl|~motofakty.pl|~naszemiasto.pl|~nowiny24.pl|~nowosci.com.pl|~nto.pl
```

new:

```
~dziennikbaltycki.pl|~dzienniklodzki.pl|~dziennikpolski24.pl|~dziennikzachodni.pl|~echodnia.eu|~expressbydgoski.pl|~expressilustrowany.pl|~gazetakrakowska.pl|~gazetalubuska.pl|~gazetawroclawska.pl|~gk24.pl|~gloswielkopolski.pl|~gol24.pl|~gp24.pl|~gra.pl|~gs24.pl|~kurierlubelski.pl|~motofakty.pl|~naszemiasto.pl|~nowiny24.pl|~nowosci.com.pl|~nto.pl
```

**Comment by kiboke** [comment]
@krystian3w are you sure all of these domains need exceptions? I checked a couple of them. I don't see `sdk.privacy-center.org` being loaded, i see `rodo.js` instead. Can you recheck please?
