### ISSUE TITLE
cukrzyca.info.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#18202]
Biała strona
![Zrzut ekranu z 2020-12-14 10-01-29](https://user-images.githubusercontent.com/36385327/102061141-61144e00-3df3-11eb-9c9f-61dafb4f39c3.png)

**Comment by AroKol78** [comment]
![cukrzy01](https://user-images.githubusercontent.com/70756447/102075665-dccbc600-3e06-11eb-8d68-ff6d9e705c5e.PNG)
Basilisk uBlock legacy
![db1fix](https://user-images.githubusercontent.com/70756447/99152904-1e047500-26a5-11eb-81aa-d0561833c5ed.PNG)

**Comment by hawkeye116477** [comment]
U mnie jest ok.

**Comment by krystian3w** [comment]
Odświeżajcie z kilka razy, może filtr proceduralny na ukrywanie czegoś źle działa.

@xMaap przypomniamy że my nie wspieramy naprawy `EasyList Cookie list` ani `Fanboy Annoyance`. Musisz to samodzielnie sprawdzać czy oni psują stronę i zgłaszać bezpośrednio po angielsku do twórców na Github lub na forum `lanik.us`.
