### ISSUE TITLE
vaillant.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#18236]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/102386910-0421bf00-3fd0-11eb-963d-0a67e8dad8d4.png)

### Link bezpośredni 

https://www.vaillant.pl/klienci-indywidualni/porady-i-wiedza/poradnik/pompy-ciepla-i-instalacje-hybrydowe/jak-najefektywniej-zaprogramowac-ogrzewanie-domu-i-wody/

### Co trzeba zrobić, aby pojawił się błąd?
1. 
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda (2020.12.10.0)
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances, Base, Mobile Ads
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List
11. AdGuard Tracking Protection
12. AdGuard Base, Mobile Ads
13. AdGuard Mobile Ads

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Niby to zostało uznane za powód do akceptacji pop-upa:

`https://www.vaillant.pl/klienci-indywidualni/aktualnosci/filmy-produktowe/`

ale mnie normalnie działa przycisk "oglądam".

**Comment by Barticf** [comment]
@krystian3w u mnie też działa.

**Comment by krystian3w** [comment]
OK, czyli my będziemy jeszcze wycinać ten komunikat w liście Cookies/EI filtrem `##.modal`.

Postaram się jeszcze zobaczyć czy nie używają go do np. galerii fotograficznych, wtedy trzeba by używać np. `-abp-has` / `-abp-contains` a jak to nie pomaga to wtedy jak Kiobke, cookies do akceptacji w ["Polish Cookie Consent"](https://github.com/PolishFiltersTeam/PolishCookieConsent#jak-zainstalowa%C4%87) (nie zawsze galerie zadziałają z `watch-attr`).

**Comment by Barticf** [comment]
@krystian3w dostępna jest ta aktualizacja listy ? Zaktualizowałem listy ale nadal ten problem jest, gdy dodaje twój wpis ręcznie do uBlocka to problem znika.

**Comment by krystian3w** [comment]
Jeszcze nie ma, trzeba dodać do listy zgłoszenia z dzisiaj

**Comment by Barticf** [comment]
@krystian3w dalej chyba nie zostało dodane do listy.
@xxcriticxx

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/f617157edbb34adf078a2af3faa2625a79298d95/cookies_filters/adblock_cookies.txt#L2332

Ja widzę, chyba że widzisz w tamtej linii literówki (ja mam dysleksję i czasem nie widzę np. "####" albo np. "rynek rynek zdrowia.pl").
