### ISSUE TITLE
tvmalbork.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1823]
ad block 

`http://www.tvmalbork.pl/aktualnosci/12465,budzet-malborka-na-rok-2017-przyjety-8-glosow-za-1`

![capture](https://cloud.githubusercontent.com/assets/15007183/21578479/bcc90f22-cf4f-11e6-9b60-81c5aa965f36.PNG)

**Comment by kerbenii** [comment]
`www.tvmalbork.pl##.adblock-placeholder`
