### ISSUE TITLE
f.kafeteria.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1825]
ad block 

`http://f.kafeteria.pl/temat/f4/uniewaznienie-malzenstwa-cogdziekiedy-poradzcie-p_3213396`

**Comment by F4z** [comment]
Rozumiem, że chodzi o film.
Z tego co widzę, to z włączoną listą AAK działa.
Potem poprawię odpowiednią regułę żeby i bez AAK działało.

**Comment by MajkiIT** [comment]
@F4z Dzięki

**Comment by F4z** [comment]
Tak jak teraz patrzę, to działa z samą polską listą, więc raczej nie trzeba nic zmieniać.
Moglibyście sprawdzić u siebie?

Swoją drogą, to tę regułę można już usunąć:
`@@/:\/\/.*[.]wp[.]pl\/[a-z0-9_]{10,50}[.][a-z]{2,5}[\/:&?]?/`

**Comment by MajkiIT** [comment]
@F4z jest git. usunę tą regułę.
