### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#18251]
ubo legacy `$all` is fine
sponsorowany
https://www.dobreprogramy.pl/Bezplatny-dodatek-do-internetowej-przegladarki-wystarczy-by-nie-przeplacic-za-zakupy,News,112314.html
`||dynacrems.wp.pl^$all,domain=dobreprogramy.pl`

dodatkowo video "detect adblock" np.https://www.dobreprogramy.pl/Firefox,Program,Windows,13108.html
video raz działa ,raz nie działa - dziwne

**Comment by krystian3w** [comment]
`All` nie działa z ABP/AdBlock - filtr może nie zablokować, bo zostanie pominięty.

**Comment by Lukjan38** [comment]
nie pokazuje informacji.

![dp](https://user-images.githubusercontent.com/17565773/115970263-98350180-a541-11eb-94db-667b54ea5de4.jpg)

**Comment by krystian3w** [comment]
Przecież jest temat zbiorczy dla WP: #18472

**Comment by Lukjan38** [comment]
aha, ok
