### ISSUE TITLE
sadeczanin.info

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#18250]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/102520619-2d0b8800-4094-11eb-8f9f-77377174b026.png)

+ Facebook
![obraz](https://user-images.githubusercontent.com/32641928/102520708-3f85c180-4094-11eb-9e67-eb147e28ffaa.png)

### Link bezpośredni 

https://sadeczanin.info/wiadomosci/katastrofa-zamykaja-calkowicie-hotele-i-stoki-branza-krzyczy-oklamali-nas

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
1. 
2. 
3. 

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda (2020.12.10.0)
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances, Base, Mobile Ads
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List
11. AdGuard Tracking Protection
12. AdGuard Base, Mobile Ads
13. AdGuard Mobile Ads

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Widgetu facebooka nie widzę, pewnie jest to lista dla której nie oferujemy naprawy czyjegoś "widzimisię" np.:

* `Fuck Fuckadblock`

  Jak dodał `generichide` to raczej nie ma co mu już zgłaszać że widżet wycieka a my raczej nie będziemy sprawdzać czy filtr ma jako 2001 domenę kolejny polski portal.

   Może i `ghide` skutecznie walczy z race-condition dla skryptletów, ale czy na pewno 99% internautów dalej używa jakiegoś Android 2.X lub instaluje przeglądarkę na "pralce"?

**Comment by hawkeye116477** [comment]
Z tego co widzę, to @Barticf nie ma Fanboy's Social.

**Comment by MajkiIT** [comment]
A reklamę widzicie ?

**Comment by krystian3w** [comment]
Tak, wciśnięta w tylko ten linkowany artykuł:

```
||sadeczanin.info/sites/default/files/wsb_0.png

sadeczanin.info##.article-content a[href="https://www.wsb-nlu.edu.pl"] img
```

Być może wewnętrzna bo nie ma czegoś takiego jak "nowo-sączanin" (mieszkańca np. "Starego Sącza" nazwiemy identycznie), tylko że wtedy nieładnie blokować reklamy jedzenia na innych stronach miastowych jak też lokale są z tego samego miasta i nie mają rozbudowanej sieci na całą Polskę.

**Comment by MajkiIT** [comment]
@krystian3w dzięki

**Comment by krystian3w** [comment]
Lista do dodania jak nie dodałeś 9 dni temu:

[https://easylist.to/easylist/fanboy-social.txt](https://subscribe.adblockplus.org/?location=https://easylist.to/easylist/fanboy-social.txt&title=Fanboy%20Social)
