### ISSUE TITLE
galleyla.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1828]
ad block

`http://www.galleyla.pl/news.php`

![capture](https://cloud.githubusercontent.com/assets/15007183/21578530/9545a558-cf51-11e6-9928-17b5cc88c921.PNG)

**Comment by kerbenii** [comment]
To jest statycznie dorzucane przez serwer.
Możemy to zablokować poprzez usunięcie całego tekstu span color red, ale nie wiem czy aż takie ogólne filtry chcemy stosować 👅
