### ISSUE TITLE
gazetawroclawska.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18295]
" Czytaj wygodniej najważniejsze wiadomości "

https://gazetawroclawska.pl/prasowka-21122020-wydarzenia-dnia-podsumowanie-z-wczoraj-sprawdz-czy-nie-minelo-cie-nic-waznego/ar/c1p1-19960895

**Comment by MajkiIT** [comment]
`gazetawroclawska.pl##.component.componentsPromotionsArticlePromotedList`
