### ISSUE TITLE
nowa funkcja opery a ciasteczko

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#18301]
Tutaj troche inna sytuacja otuż opera w nowej wersji na bocznym pasku posiada zakładke odtwarzacz po wybraniu np spotify przechodzi na strone spotify a tu taki kwiatuszek 

![Screenshot_1](https://user-images.githubusercontent.com/21177361/102916057-337a7500-4483-11eb-84e8-e5cb5c3589f6.png)

Nie wiem czy poradzi sobie z tym UBO czy to juz kwestja do adguarda ale zglaszam co widze

**Comment by hawkeye116477** [comment]
Pewnie raczej AdGuard i tylko ten systemowy.

**Comment by gzenio22** [comment]
sprawdzisz czy adguard to zdejmuje? jak nie to weź to przekieruj bo ja obecnie nie mam licencji

**Comment by zaba-monika** [comment]
* jeśli chodzi o uBO:
   * da się usunąć komunikat filtrem sieciowym: `||cdn.cookielaw.org^$script,domain=open.spotify.com` - taki filtr działa zarówno na normalnej stronie, jak również na stronie wewnętrznej Opery tak jak u zgłaszającego, tylko nie wiem czy usunięcie komunikatu filtrem sieciowym nie popsuje przy okazji czegoś na stronie...
   * niestety nie da się usunąć filtrem kosmetycznym np. `open.spotify.com###onetrust-consent-sdk` bo o ile takie działają na normalnej stronie, to już nie działają na stronie otwartej jakby wewnątrz Opery
* jeśli chodzi o adblocker wbudowany w Operę:
   * da się usunąć komunikat zarówno filtrem sieciowym jak i kosmetycznym, bo jedne i drugie działają zarówno na normalnej stronie, jak również na stronie wewnętrznej Opery
 * jeśli chodzi o AdGuard (browser extension):
    * nie da się usunąć komunikatu ani filtrem kosmetycznym, ani sieciowym, bo działają one tylko na normalnej stronie

**Comment by krystian3w** [comment]
AdGuard dla Windows 7.5 "zamyka czymś", czym to nie wiem nie widzę tego nawet w pliku JSON - z podglądu może filtrem kosmetycznym (czyli widzi stronę jak wbudowany bloker reklam).

**Comment by gzenio22** [comment]
potwierdzam jak to zglaszalem adguard jeszcze tego nie łapał
