### ISSUE TITLE
Wesołych świąt Bożego Narodzenia i szczęśliwego Nowego Roku życzy wam załoga polish-ads-filter

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#18304]
![DC5D2492-24E4-48B4-831E-445E5D539894](https://user-images.githubusercontent.com/15007183/102985812-c811c100-44dd-11eb-8070-44c8b0a56af8.jpeg)

**Comment by zaba-monika** [comment]
xxcriticxx pamiętasz stare dobre czasy https://github.com/MajkiIT/polish-ads-filter/issues/9025

**Comment by xxcriticxx** [comment]
zaba-monika for sure!

**Comment by hawkeye116477** [comment]
Nazwajem, tyle, że to jednak chyba bardziej temat do dyskusji (https://github.com/MajkiIT/polish-ads-filter/discussions) :smile:.

**Comment by MajkiIT** [comment]
@xxcriticxx wzajemnie i dziękuję wszystkim za kolejny rok walki z reklamami i nie tylko :D

**Comment by xxcriticxx** [comment]
@hawkeye116477 moim zdaniem to byl topic na main repository

**Comment by blocker999** [comment]
Wesołych
