### ISSUE TITLE
streambase.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#18302]
Coś w liście polskich filtrów elementów irytujących ubija shoutboxa na tej stronie 

Z aktywną listą

![Screenshot_1](https://user-images.githubusercontent.com/21177361/102917543-b4d30700-4485-11eb-9c0a-0eff5ecdf346.png)

Bez

![Screenshot_1](https://user-images.githubusercontent.com/21177361/102917662-e9df5980-4485-11eb-8ea0-265f0a828349.png)

**Comment by hawkeye116477** [comment]
W takim razie drogi @gzenio22 to nie to repozytorium....

**Comment by gzenio22** [comment]
przekazane tu zamykam
