### ISSUE TITLE
kodiwpigulce.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#18309]
Resztka po reklamie

![Screenshot_1](https://user-images.githubusercontent.com/21177361/103092386-59288b00-45f7-11eb-90af-8569aae285c9.png)

**Comment by xxcriticxx** [comment]
@kodiwpigulce nie wiem co za filmy w teraz tam puszczacie na forum

![Capture](https://user-images.githubusercontent.com/15007183/103094661-4a78ae80-45cc-11eb-9965-6d4ad90101fb.JPG)

**Comment by gzenio22** [comment]
zadnych Xd uzyj VPN

**Comment by zaba-monika** [comment]
> gzenio22 : https://github.com/MajkiIT/polish-ads-filter/issues/18309#issue-774456073 : Resztka po reklamie

- to nie resztka , tylko reklama:
![1111](https://user-images.githubusercontent.com/72980128/103097845-ede7b480-4608-11eb-8ab8-9ff99b7568b6.gif)

**Comment by kodiwpigulce** [comment]
Ta zablokujcie jeszcze reklamę naszego darmowego serwisu z epg.

**Comment by zaba-monika** [comment]
- czyli wychodzi na to, że gzenio22 zgłosił reklamę wewnętrzną, a takie reklamy o ile się orientuję zazwyczaj nie są blokowane na POL liście, tylko czasami, pewnie przyjdzie admin to zdecyduje

**Comment by gzenio22** [comment]
znaczy ja nie chcialem zablokowac tego okienka z EPG to wewnętrzne więc odpada poza tym nawet jesli to reklama jest bardzo suptelna i pomocna raczej chodzilo mi o ten napis reklama dla tego potraktowalem to jako resztke mój błąd przepraszam niech admin zdecyduje ale jak dla mnie to powinno zostac

**Comment by xxcriticxx** [comment]
@gzenio22 opps

**Comment by zaba-monika** [comment]
* sam już nie wiem, czy to jedna reklama, czy 2 osobne reklamy obok siebie:
   * baner bez napisu "reklama" (1)
   * przycisk/pasek z napisem "reklama"  (2)
* tak czy inaczej obydwie prowadzą na tę samą stronę: `epg.ovh`:


![3333](https://user-images.githubusercontent.com/72980128/103128151-66478780-4694-11eb-8264-ec81f929a89e.gif)

**Comment by hawkeye116477** [comment]
No właśnie, raczej chyba powinno być 2 w 1, podpis pod obrazkiem i jeden link, skoro to to samo...

**Comment by MajkiIT** [comment]
Raczej to po prostu reklama EPG nie ma chyba sensu tego blokować. Jest to związane z tematyką i jest chyba produktem ich.

**Comment by gzenio22** [comment]
zamykam w takim razie i sorry za kłopot
