### ISSUE TITLE
iplex.eu

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#18311]
adblocker Adguard 

Po prawej komunikat o ciastku

![Screenshot_1](https://user-images.githubusercontent.com/21177361/103139556-c1519c80-46dd-11eb-9111-eac6f60a3111.png)

**Comment by zaba-monika** [comment]
- strona mi się nie ładuje
- poza tym zarówno strona jaki i komunikat nie są po polsku, więc chyba znowu kolejne fałszywe zgłoszenie

**Comment by hawkeye116477** [comment]
Potwierdzam.

@gzenio22 Jeszcze Sylwester się nie zaczął, a ty już szalejesz...
