### ISSUE TITLE
ogloszenia.trojmiasto.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1832]
ad block 

`http://ogloszenia.trojmiasto.pl/potrzebuje-pomocy/`

![capture](https://cloud.githubusercontent.com/assets/15007183/21578554/1f0ae34c-cf53-11e6-819f-873c033480b9.PNG)

**Comment by kerbenii** [comment]
`ogloszenia.trojmiasto.pl##.block-info-wrap`
