### ISSUE TITLE
kingston.com/poland/pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#18334]
![Zrzut ekranu z 2020-12-29 11-31-06](https://user-images.githubusercontent.com/36385327/103277483-606de100-49c9-11eb-9a62-52d73ccc730f.png)

**Comment by hawkeye116477** [comment]
PS: Nie polecam od nich kart microsd, psują się, a potem trzeba robić format i zabawa od początku

**Comment by krystian3w** [comment]
A co z newsletterem.
