### ISSUE TITLE
kurnik.pl

### ISSUE THREAD

**Issue by zaba-monika** [MajkiIT/polish-ads-filter#18335]
- anty-adblock wrócił: https://github.com/MajkiIT/polish-ads-filter/issues/2064 (+ https://github.com/MajkiIT/polish-ads-filter/issues/2292)
<br>

- w tym filtrze: 

> F4z : https://github.com/MajkiIT/polish-ads-filter/issues/2064#issuecomment-275250762 :
> A to dodatkowo do uBlocka żeby zmniejszyć puste miejsce po reklamie:
> `kurnik.pl##.adsbygoogle:style(height: 1px !important; width: 1px !important;)`

trzeba zmienić `height: 1px` na `height: 2px`

**Comment by bug-rules** [comment]
Nie umiem reprodukować.

AdGuard ma jescze to:

`kurnik.pl#%#//scriptlet("abort-on-property-read", "abask")`

**Comment by zaba-monika** [comment]
- do zreprodukowania trzeba mieć konto i się zalogować, na "gościu" nie wyskoczy, chyba, że zalogowałeś się i mimo to dalej nie mogłeś zreprodukować
- co do tej drugiej reguły, nie jest konieczna, ale w sumie można dodać, może dłużej potrzyma

**Comment by zaba-monika** [comment]
> @MajkiIT : https://github.com/olegwukr/polish-privacy-filters/commit/0c45e4f501f1574aa37db3cd81e32c0053673268

Ale to ma iść:
- `kurnik.pl#%#//scriptlet("abort-on-property-read", "abask")` ma iść do AG supplement
- `kurnik.pl##+js(aopr, abask)` ma iść do uBO supplement

**Comment by zaba-monika** [comment]
@MajkiIT musisz jeszcze usunąć stary filtry stylowy:
https://github.com/MajkiIT/polish-ads-filter/blob/18ff74adde7409c7d7e9d0b44017d47444d204da/polish-adblock-filters/adblock_ublock.txt#L222-L225

, bo inaczej ma on pierwszeństwo przed tym nowym, i ten nowy nie działa.

**Comment by bug-rules** [comment]
> że zalogowałeś się i mimo to dalej nie mogłeś zreprodukować

Tak, pewnie nie na każdym koncie lub bug w kodzie obniżający prawdopodobieństwo uruchomienia anty-adblock...

> bo inaczej ma on pierwszeństwo przed tym nowym, i ten nowy nie działa.

Lepiej użyć określenia "ignorowany".

Bo jeszcze usunie oba i zostaniemy z skryptem, który widać padł skoro tobie już nie działa.

A co do wyścigu  jaki filtr stylowy zostanie użyty to trzeba oceniać to na podstawie co widać w [DOM inspectorze </>](https://github.com/gorhill/uBlock/wiki/DOM-inspector), bo zakładam, że jakaś kolejność jest brana pod uwagę skoro `tabs.insertCSS()` umie w specyficzność CSS.

**Comment by zaba-monika** [comment]
> zostaniemy z skryptem, który widać padł skoro tobie już nie działa.

- działa, tylko go wyłączyłam na czas testowania reguły stylowej, było to konieczne bo jak niby inaczej miałabym przetestować regułę stylową bez wcześniejszego wyłączenia skryptowej, skoro każda z nich z osobna (stylowa oraz skryptowa) ukrywają anty-adblocka

> A co do wyścigu jaki filtr stylowy zostanie użyty to trzeba oceniać to na podstawie co widać w [DOM inspectorze </>](https://github.com/gorhill/uBlock/wiki/DOM-inspector), bo zakładam, że jakaś kolejność jest brana pod uwagę skoro `tabs.insertCSS()` umie w specyficzność CSS.

- nie zagłębiałam się w to, pisząc o pierwszeństwie nie pisałam generalnie, tylko odnosiłam się do aktualnego przypadku w danej chwili, a co do kolejności to tak przez chwilę sobie pomyślałam, że może po prostu 1px uruchamia się pierwszy bo leży alfabetycznie przed 2px, ale to tylko zgaduj-zgadula

**Comment by bug-rules** [comment]
Może być jak ze zwykłym CSS, że późniejszy nadpisuje wcześniejszy ale jak zrobić podgląd wielkiej "magicTable" z uBO który filtr jest na której pozycji...

Jak aktualizacja wpływa na kolejność to jednak dobrze, że stary zniknął https://github.com/MajkiIT/polish-ads-filter/commit/4aaeb423a4b578c804ea004f1a2b96c696fdd237.
