### ISSUE TITLE
wawalove.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1833]
ad block 

`http://wawalove.pl/Dla-nas-zabawa-dla-nich-noc-pelna-stresu-Jak-troszczyc-sie-o-zwierzeta-w-sylwestrowa-noc-a25162`

**Comment by kerbenii** [comment]
`wawalove.pl##.cookie__text`

**Comment by xxcriticxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/15007183/21578767/851d8dcc-cf5a-11e6-9176-69e6c58cec5f.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx 
zerkniesz ?
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=wawalove.pl`
