### ISSUE TITLE
burzowo.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1834]
ad block 

![capture](https://cloud.githubusercontent.com/assets/15007183/21578573/be6505ee-cf53-11e6-9a69-79ac4525e459.PNG)

**Comment by kerbenii** [comment]
Fajnie by było jakby @FadeMind tutaj swoją magię zadziałał, bo też ja to najchętniej bym zwhitelist'ował https://burzowo.info/scripts/ad.js?adtype=adserver&what=ads&type=AdSense&cos=/AdSense/wyswietl&a=/pub/ads/costam&baner=reklama&ad_keyword=ads&ad_type_id=ads&adname=ads&adspace=das&adtype=1&advertiserid=21 które zwraca adblocker = false;

**Comment by FadeMind** [comment]
@kerbenii 
```
burzowo.info###redbox
```
ukrywa monit od wykryciu adblocka. 
Log z ublock origin
![image 041](https://cloud.githubusercontent.com/assets/9846948/21578816/3f9fdae0-cf8f-11e6-8458-2b7a7876ffec.png)

**Comment by kerbenii** [comment]
A toto ja tez znalazłem bez problemu xD 
Ale z AdBlockiem ładuje ci się statyczny obrazek mapy, a jak go wylaczysz (albo wywolasz przy lądowaniu strony wartość tej zmiennej z poprzedniego komentarza), to jest mapa dynamiczna, podobna do Google Maps.

**Comment by F4z** [comment]
`@@||burzowo.info/scripts/ad.js$script,domain=burzowo.info`

**Comment by kerbenii** [comment]
o, właśnie o to mi chodziło 👅 
Jak to znalazłeś @F4z ?

**Comment by F4z** [comment]
Dokładnie, tutaj też jest to opisane - https://adblockplus.org/en/filter-cheatsheet
