### ISSUE TITLE
terrarium.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1835]
ad block 

`http://www.terrarium.com.pl/2372-tonkinbolus-dollfusi/`

![capture](https://cloud.githubusercontent.com/assets/15007183/21578581/fd07bc2e-cf53-11e6-97b9-880273d872f9.PNG)

**Comment by kerbenii** [comment]
`terrarium.com.pl###k224
terrarium.com.pl##.ABD_display_wrapper`

**Comment by MajkiIT** [comment]
A AAK tego nie blokuje?

**Comment by xxcriticxx** [comment]
@MajkiIT hyba tak ale co robimy jak user niema reeka listy? moze to trzeba obgadac

**Comment by MajkiIT** [comment]
No dobre pytanie. No są 2 wyjścia albo ktoś musi dodać AAK lub my będziemy dublować wpisy.

**Comment by F4z** [comment]
@MajkiIT u mnie skrypt AAK blokuje, bo sama lista nie wystarcza.
Myślę, że tę regułę - `terrarium.com.pl##.ABD_display_wrapper` - warto dodać, bo ukrywa puste miejsca, a tę drugą to jak uważasz.

**Comment by MajkiIT** [comment]
@F4z ok dodałem
