### ISSUE TITLE
national-geographic.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#18392]
https://www.national-geographic.pl/artykul/zimowa-wyprawa-na-k2-waldemar-kowalewski-ewakuowany-z-bazy
![Zrzut ekranu z 2021-01-04 07-33-20](https://user-images.githubusercontent.com/36385327/103507298-24220100-4e5f-11eb-9edc-0548ccbb4f5a.png)

**Comment by AroKol78** [comment]
lub `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=national-geographic.pl`

do https://github.com/olegwukr/polish-privacy-filters

**Comment by krystian3w** [comment]
@olegwukr  ten sam na:

https://www.mojegotowanie.pl/przepis/szynka-z-musem-jajecznym-i-remulada

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/d9de283313f2782194e98d080b5ca8dc18b93258#diff-4a6978b41c01edec9e42a612c659cd9fdd99e12c90dfca77cbd53379c960bb2c
