### ISSUE TITLE
purepc.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1840]
![image 043](https://cloud.githubusercontent.com/assets/9846948/21581406/707cb29e-d031-11e6-8a34-1af721eb2e56.png)

**Comment by F4z** [comment]
Niestety tutaj zwykła reguła nie działa, bo po pięciu sekundach ta reklama znowu się pojawia.
To powinno działać:
`purepc.pl##a[href^="https://www.purepc.pl/redir.php"]:style(height: 0px !important; position: absolute !important;)`
ale tylko w uBlocku Origin/Adguardzie.
