### ISSUE TITLE
karmopedia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#18410]
http://www.karmopedia.pl/ziwipeak-originals-sucha-karma-dla-psow/
Social + Reklama
![Zrzut ekranu z 2021-01-05 13-38-30](https://user-images.githubusercontent.com/36385327/103647274-5022ac80-4f5b-11eb-8919-39d04b8d8e84.png)
Antiadblock
![Zrzut ekranu z 2021-01-05 13-39-15](https://user-images.githubusercontent.com/36385327/103647367-7ba59700-4f5b-11eb-8a67-3d0a013f1d9d.png)

**Comment by krystian3w** [comment]
Częściowo anty-adblock naprawia:

`@@||partnerzyapi.ceneo.pl/External/ap.js$script,domain=www.karmopedia.pl`

Ale ceny się nie ładują, pewnie prościej wyciąć kosmetycznie ostrzeżenie a cennik traktować jako reklamę "zewnętrzną".


---

Pieski można wyciąć filtrem:

`-baner$image,domain=karmopedia.pl`

po stwierdzeniu, że inne banery "wewnętrzne" nie używają `-baner`

**Comment by krystian3w** [comment]
z bardziej zaawansowanego można użyć skryptlet:

`##+js(acis, showAdblockImage)`
`##+js(nostif, showAdblockImage, 2000)`

ale wtedy nie ma wsparcia dla ABP/AdBlock.

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/dc93866a3013061c64debd9e48790135258872bb#diff-5c6d18ca8ff0fdc3e0613016fe097ec8ca38949105772035ec0bb49a40a328fc
