### ISSUE TITLE
wp.pl mobile

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1841]
@F4z dasz rade dodac filtry na mobile wersie strony?

**Comment by F4z** [comment]
@xxcriticxx jak na komputerze wejdę na mobilną wersję strony - `http://www.wp.pl/mini.html` - to nie widzę reklam. Tak samo nie widzę reklam na telefonie z Androidem i Adguardem.
Możesz napisać dokładniej o co Ci chodzi?

**Comment by xxcriticxx** [comment]
Ja na iPhone z Adguard mam pelno

**Comment by xxcriticxx** [comment]
![img_4156](https://cloud.githubusercontent.com/assets/15007183/21581759/8b70c622-d00d-11e6-8efb-a72e0f453644.PNG)

**Comment by xxcriticxx** [comment]
@F4z dostalem do od alexa na adguardzie teraz jest mniej reklam na main page ale zostaly puste box po reklamach 

`wp.pl##.header+div > div[class] > div[style*="display: block;"]`
`wp.pl###section_topnews > div:not([class])  > div[style] > div > a > img[style]`


http://imgur.com/a/P4GpB
http://imgur.com/a/VQIcA

**Comment by xxcriticxx** [comment]
@F4z testowales `http://www.wp.pl/mini.html` na comp z adguardem? jesli nie mozesz please

**Comment by F4z** [comment]
@xxcriticxx testowałem. Z Adguardem w wersji na komputer nie mam reklam (sprawdzałem przy wyłączonym uBlocku).

**Comment by xxcriticxx** [comment]
@F4z chlopaki z adguardu napisali ze na ios jest limit i troche tych regul nie bendzie narazie dzialac
