### ISSUE TITLE
Filman.cc

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#18429]
Nie wiedziałem pod co to podpiąć więc dałem inne

opis wywołania : Uruchom jakiś film czy serial wybierz chosting clipwatching kliknij play na playerze

To wywoła przekierowanie na strone clipwatching a to chyba nie jest konieczne

**Comment by MajkiIT** [comment]
Ale tak jest wskazane w player. Najedź myszką i sprawdź.

**Comment by gzenio22** [comment]
już sie naprawiło chyba samo :D
