### ISSUE TITLE
businessinsider.com.pl

### ISSUE THREAD

**Issue by jacetomczak** [MajkiIT/polish-ads-filter#1843]
http://businessinsider.com.pl/finanse/twoje-pieniadze/jak-madrze-wydawac-pieniadze-jak-oszczedzac-na-zakupach/te59qv9

**Comment by FadeMind** [comment]
@jacetomczak U mnie strona wyświetla się właściwie. Jaki masz problem? Możesz zrobić zrzut ekranu?

**Comment by F4z** [comment]
Tak bez żadnego opisu, to zgaduję, że chodzi o wykrycie adblock, które ostatnio było opisywane.
Między innymi tu - `http://www.wirtualnemedia.pl/artykul/uzytkownicy-adblockow-bez-dostepu-do-tresci-na-business-insider-polska-i-plejada-pl`
oraz tu - `http://www.dobreprogramy.pl/Onet-rozszerza-kampanie-przeciw-adblockom-na-kolejne-serwisy-ulepsza-swoje-skrypty,News,78208.html`
Podobne zgłoszenie już było - https://github.com/MajkiIT/polish-ads-filter/issues/1737
U siebie nie potrafię tego odtworzyć, ale że na tej stronie wykrywają adblocka w ten sam sposób jak na onecie, to ta reguła powinna działać:
`@@||businessinsider.com.pl^$generichide`

**Comment by F4z** [comment]
@FadeMind okej, to też jest blokowane przez listę `Peter Lowe’s Ad and tracking server list‎`, która jest chyba domyślnie włączona w uBlocku. Oprócz tego `uBlock filters – Privacy` też zawiera odpowiednią regułę do tego przypadku, ale dzięki :)

**Comment by FadeMind** [comment]
@F4z `Peter Lowe’s Ad and tracking server list` oraz `uBlock filters – Privacy`  nie blokują tego. 🚫

**Comment by F4z** [comment]
@FadeMind `Peter Lowe’s Ad and tracking server list` blokuje.

![image](https://cloud.githubusercontent.com/assets/11742596/21583232/1ecd0466-d078-11e6-9715-5d1b474dbb66.png)

`uBlock filters – Privacy` też ma odpowiednią regułę w tym przypadku - `||scorecardresearch.com/beacon.js$script,redirect=scorecardresearch.com/beacon.js`

**Comment by FadeMind** [comment]
szukałem po dokładnej regule `b.scorecardresearch.com` 🏷

**Comment by jacetomczak** [comment]
Dzień dobry!

Nie sądziłem, że ktoś odpowie na to zgłoszenie dlatego nie wysilałem się z
opisem.

Po wejściu na stronę http://businessinsider.com.pl/ po chwili wyskakuje
monit o blokowaniu reklam.
Bo paru sekundach jest on 'usuwany' przez adblock'a.
Po kolejnej sekundzie monit wraca ponownie i już 'zostaje'.

Pozdrawiam,
Jacek

[image: Obraz w treści 1]

2017-01-01 23:20 GMT+01:00 Tomasz Przybył <notifications@github.com>:

**Comment by F4z** [comment]
@jacetomczak okej, czyli tak jak pisałem.
Sprawdzałeś regułę, którą podałem?
`@@||businessinsider.com.pl^$generichide`
Musisz to dodać do swoich reguł. Nie wiem z jakiego rozszerzenia/programu do blokowania reklam korzystasz, więc ciężko mi podać konkretną instrukcję. Jak będziesz miał problem, to pomogę.

@MajkiIT czy `contentstream` nie powinno być blokowane?
Na przykład tutaj - `http://businessinsider.com.pl/finanse/rynek/kurs-bitcoina-styczen-2016/4j3vc5s`
![image](https://cloud.githubusercontent.com/assets/11742596/21591419/045791be-d104-11e6-811c-689b59eea551.png)

![image](https://cloud.githubusercontent.com/assets/11742596/21591428/129fac0c-d104-11e6-85b9-2ab55e00e0af.png)

Widzę kilka reguł na liście odnośnie tego, tylko że teraz zmienili adres z `emisja.contentstream.pl` na `emisjao.contentstream.pl`
To może warto dodać reguły żeby to też blokować?
Na przykład:
`##a[href*="/emisjao.contentstream.pl/_/ctr/"]`
`||emisjao.contentstream.pl^$script`

**Comment by xxcriticxx** [comment]
@F4z to mi sie zdaje ze dziala `@@||businessinsider.com.pl^$generichide`

**Comment by jacetomczak** [comment]
Faktycznie działa!

Bardzo dziękuję!

Jacek

2017-01-02 16:21 GMT+01:00 xxcriticxx <notifications@github.com>:
