### ISSUE TITLE
flashbatcraft2.000webhostapp.com

### ISSUE THREAD

**Issue by Sergey-Lyapin** [MajkiIT/polish-ads-filter#18447]
CSS doesn't load to this site because of rule `||000webhostapp.com^`

Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/71126

**Comment by MajkiIT** [comment]
@Sergey-Lyapin Thanks
https://github.com/MajkiIT/polish-ads-filter/commit/cb04731861d024aa42edba8694847d5f1167109a#diff-eab2aaf469314f57267f6f71855a766738837ca60234d6105317854abe61152c
