### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#18446]
https://www.elektroda.pl/rtvforum/topic2888198.html#13911871
[myList](https://user-images.githubusercontent.com/70756447/102889523-1a5dce00-445b-11eb-9dfa-8919f5ae110c.PNG) ("AdGuard Base" nie pomaga)
reklama 3 x czujki ... + niby "adblock detect" czy tylko napis
![elektroda01](https://user-images.githubusercontent.com/70756447/104137058-591bdf80-539a-11eb-82fd-f88970651c49.PNG)

**Comment by krystian3w** [comment]
Zakładając, że każdy obrazek z posta ma `.fancybox` lub `.postlink` (a pewnie nie mają go ręcznie wstawione małe przy pomocy `[img] [/img]`) to może takie:

`elektroda.pl##a:not(.fancybox) img[src^="https://obrazki.elektroda.pl/"]`

lub

`elektroda.pl##a:not(.postlink) img[src^="https://obrazki.elektroda.pl/"]`

reklamy wyglądają na generowane w PHP / wciśnięte w szablon po stronie serwera (nie ładuje ich raczej żaden JavaScript).

**Comment by krystian3w** [comment]
Skrypt na wykrycie adblock wygląda tak:

```js
document.querySelectorAll('.d9460dd5a-b5517335b632a70').length > 0) {
  var adBlockTest = document.createElement('div');
  adBlockTest.innerHTML = '&nbsp;',
  adBlockTest.className = 'adBanner advert advertisement adsby',
  document.body.appendChild(adBlockTest),
  window.setTimeout(function () {
    0 === adBlockTest.offsetHeight && document.querySelectorAll('.d9460dd5a-b5517335b632a70') [0].classList.add('eb88a7fd7fa2'),
    adBlockTest.remove()
  }, 100)
}
```

Można próbować naprawić CSS-em:

```css
elektroda.pl##html:root body .adBanner.advert.advertisement.adsby[class*="ad"]:style(display: block !important;)
```

Naprawa dla ABP i AdBlocka wymaga dodania kilku wyjątków i może już czas na `generichide`.

```

**Comment by krystian3w** [comment]
Dodatkowo na homepage widzę, że wróciła reklama "przejdź do strony":

![elektroda pl - elektronika, forum dyskusyjne, forum komputerowe, forum GSM, forum AGD, forum samochod](https://user-images.githubusercontent.com/35370833/104170852-1261d000-5402-11eb-8a23-429c8a0263c7.png) |
--- |

**Comment by AroKol78** [comment]
**krystian3w**
działa na na reklame 👍 
```
elektroda.pl##section a:not([href*="elektroda.pl/"]):not([href*="/rtvforum/"]):not(.fancybox):not(.postlink) img[src^="https://obrazki.elektroda.pl/"]
elektroda.pl###main .col-md-8 a:not([href*="elektroda.pl/"]) img[src^="https://static.elektroda.pl/"]
```
> Dodatkowo na homepage widzę, że wróciła reklama "przejdź do strony":

👍 `www.elektroda.pl##+js(set-constant.js, loadElement, noopFunc) `

> wykrycie adblock

👍  `elektroda.pl##html:root body .adBanner.advert.advertisement.adsby[class*="ad"]:style(display: block !important;)`

`elektroda.pl##+js(abort-on-property-read.js, adBlockTest)` za dużo blokuje - część stron nie wczytuje się,kręcące kółka
(jeszcze tme.eu)
![bug2elektroda](https://user-images.githubusercontent.com/70756447/104184162-4f828e00-5413-11eb-8b05-2effd0f88b31.PNG)

**Comment by krystian3w** [comment]
czyli skryptowo anty-adblock trzeba jeszcze inaczej, na razie zostaje więc CSS lub dopuszczenia w stylu ABP/AdBlock.

**Comment by krystian3w** [comment]
Co do wyszukiwarki "T E M" to nie wiem czy ją wycinać, jak Adam ją wywalał to my też możemy czymś takim:
```
###main .col-md-8 form > table
```

**Comment by AroKol78** [comment]
👍 `elektroda.pl##+js(setTimeout-defuser.js, adBlockTest, 100)`
👍 `elektroda.pl###main .col-md-8 form > table`

> Co do wyszukiwarki "T E M"

jak uważacie / zrobicie tak będzie

**Comment by xxcriticxx** [comment]
jutro napewno nazwy beda po zmieniane

**Comment by AroKol78** [comment]
dodali nową wyszukiwarkę do home ( w stylu "T E M")

**Comment by krystian3w** [comment]
"Micros", może nawet dużo starsza.

`###main .col-md-8 form[action*="tme"]:upward(2)`
`###main .col-md-8 form[action*="micros"]:upward(2)`

Niby upward liczbowy działa z uBO legacy (ale już wcale z ABP/AdBlock - tam trzeba posiłkować się `-abp-has`).

**Comment by AroKol78** [comment]
> `###main .col-md-8 form[action*="//"][action*="m"][action*="."]:upward(.col-md-8 > div)`

tylko cały pasek gdzie są  wyszukiwarki

**Comment by krystian3w** [comment]
Tak tak.

**Comment by AroKol78** [comment]
🥇 **krystian3w** 👍  jak na razie działa bez problemu 
 (na Adguard mają problem z `elektroda.pl` - `https://github.com/AdguardTeam/AdguardFilters/issues/72472`)

🥇 **MajkiIT** 👍 dzięki `open.fm` 👍 https://github.com/MajkiIT/polish-ads-filter/commit/b4e41bfc9ee5e4f6702986489e679acad2239e52 https://github.com/MajkiIT/polish-ads-filter/commit/41625f4a8fa914747b5034d1905b46f3c7cfee71

**Comment by AroKol78** [comment]
autor **krystian3w** 👍  
```
elektroda.pl##section a:not([href*="elektroda.pl/"]):not([href*="/rtvforum/"]):not(.fancybox):not(.postlink) img[src^="https://obrazki.elektroda.pl/"]
elektroda.pl###main .col-md-8 a:not([href*="elektroda.pl/"]) img[src^="https://static.elektroda.pl/"]
elektroda.pl###main .col-md-8 form[action*="//"][action*="m"][action*="."]:upward(.col-md-8 > div)
elektroda.pl##+js(no-setTimeout-if.js, adBlockTest, 100)
www.elektroda.pl##+js(set-constant.js, loadElementBlock, noopFunc)
```

**Comment by krystian3w** [comment]
Adguard usunął wykrywanie height

**Comment by AroKol78** [comment]
**krystian3w** - zostanę przy twoich filtrach - (nie skacze strona,nie mrugnie reklama,anty-adblock,w przyszłość wytnie dodane wyszukiwarki)

**Comment by krystian3w** [comment]
Z ciekawostek, AdGuard też wyciął "macros" z pomocą ":upward(2)".

**Comment by AroKol78** [comment]
"AdGuard Base"
`elektroda.pl#?#.col-md-8 div[style*="micros"] > div[style] > form[action^="https://www.micros.com.pl/"]:upward(2)`
a jak zmienią / dodadzą wyszukiwarkę
> Ciekawostka takie ukrywają cały div z reklamami [homepage]:
`###main .col-md-8 form[action*="//"][action*="m"][action*="."]:upward(.col-md-8 > div)`

👍

**Comment by AroKol78** [comment]
@felix-22
ja używam https://github.com/MajkiIT/polish-ads-filter/issues/18446#issuecomment-763791292
brak Anty-adblock

**Comment by AroKol78** [comment]
czy potrzebne łączenie się z domeną `caringcast.com` ?

**Comment by krystian3w** [comment]
Sprawdź czy bo zablokowaniu się dalej ładuje lub nie wlepia bana na IP.

Jakby wleciał ban to można próbować robić przekierowania na puste pliki html/txt/js/png/mp4.

**Comment by AroKol78** [comment]
strona dział dobrze z i bez `caringcast.com`
`...` = nazwa długa i niezrozumiała tak jak na wp
`https://caringcast.com/v...P` = script

**Comment by krystian3w** [comment]
No to oceń czy to się nadaje na listę:

- reklamową
- Polish Privacy Filter (moduł szpiegujący)
-  EI (np. umie generować pop-upy czy jakieś linki "otagowane" otwierające artykuły elektrody")
- KAD (np. podejrzenie luki w systemach elektrody i to jest "wirus")

**Comment by AroKol78** [comment]
nie umiem ocenić
plik tekstowy z script spakowany (29kb a wypakowany 103kb)
[sriptCaringcast.zip](https://github.com/MajkiIT/polish-ads-filter/files/6409861/sriptCaringcast.zip)

**Comment by AroKol78** [comment]
przejrzałem z grubsza i mi wygląda na 3 pierwsze rzeczy wymienione + "że przymierzają się do wdroż..."
mogę się mylić

**Comment by krystian3w** [comment]
Czyli to generator reklam zewnętrznych + tracker + możliwy generator self-promo?

**Comment by krystian3w** [comment]
@olegwukr oceń czy warto blokować coś jako elementy śledzące użytkowników.

**Comment by AroKol78** [comment]
na razie niby włączone `!` (chyba)
to znalazłem i nie wiem co to ma być (nie znam domeny i jestem podejrzliwy, coś znanego bym jeszcze strawił)
![elektroCos0](https://user-images.githubusercontent.com/70756447/116817834-a4841480-ab68-11eb-944f-990d79cf8371.PNG)

**Comment by krystian3w** [comment]
Ten wykrzyknik to nie wyłączenie a najkrótsza forma uruchamiania skryptu.

AdGuard ma klikanaście skryptletów z wykrzyknikiem na początku i dopiero usunięcie sprawia, że filtr nie działa

**Comment by AroKol78** [comment]
jak usunąć bez `id`/`div`/`class`
na razie używam (profilaktycznie) `^$all` 
może należne miejsce jest tu "Polish Privacy Filter"

`caringcast.com` > `https://github.com/ShadowWhisperer/BlockLists/blob/master/Lists/Tracking#L1260`
`https://github.com/ShadowWhisperer/BlockLists/` dużo tego

**Comment by krystian3w** [comment]
Teoretycznie jak chcesz jeszcze ubić ruch trzecioplanowy na stronie `caringcast.com` to przyda się wersja:

`$all,domain=caringcast.com`

**Comment by AroKol78** [comment]
te `caringcast` jest na `elektroda`
nigdy nie byłem na stronie `caringcast.com` ,nigdy wcześniej nie widziałem tej domeny
pierwszy raz zobaczyłem to na`elektroda.pl`

**Comment by AroKol78** [comment]
:brain::thought_balloon::satisfied: `spawarka.pl##+js(acis, document.createElement, szpieg.com)`
nawet nie łączy się z _szpieg.com_ (nie tworzy pierwszej linii dla użycia `^$all`)

:question:
czy jest całkowicie dezaktywowane 6 linijek zaznaczony na :blue_square: , czy jeszcze muszę iść do :school:

**Comment by krystian3w** [comment]
W Firefox legacy lepsze może być:

`spawarka.pl##script:contains(/document\.createElement.*szpieg\.com/)`

jak ruszy regex dla prostego filtrowania html elementów

Wersja dla Firefox Quantum i odpowiednio nowe uBO:


`spawarka.pl##^script:has-text(/document\.createElement.*szpieg\.com/)`

Z kolei skryptlet może zostać jakby strona zaczęła blokować html filtering i dla chromium.

---

`acis` ma niby szansę na to, że zadziała za późno.

**Comment by AroKol78** [comment]
czy wersja z `/document\`całkowicie dezaktywowane 6 linijek w  `type="text/javascript"` zaznaczonych na niebiesko

**Comment by krystian3w** [comment]
Czyli słowa są inaczej ułożone (cudem `szpieg.com` jest przed `document.createElement`) lub strona nie wspiera html filteringu w wersji skromnej lub na Quantum w wersji dopracowanej.

**Comment by AroKol78** [comment]
pierwsze wystąpienie `szpieg.com` jest tworzone przez inline-script przez `document.createElement`
`acis` sprawia, że linia z `szpieg.com` nie jest tworzona (ta pierwsza z zrzutu https://github.com/MajkiIT/polish-ads-filter/issues/18446#issuecomment-830825173)

**Comment by felix-22** [comment]
Na planszę reklamową: https://github.com/MajkiIT/polish-ads-filter/issues/18446#issuecomment-757866820, w starym filtrze: : https://github.com/MajkiIT/polish-ads-filter/blob/c56c3c3d45c193e66eb0d9754ebadc0eb4df8faf/polish-adblock-filters/adblock_ublock.txt#L384

zmieniamy `loadElement` na `loadElementAbk`

**Comment by AroKol78** [comment]
mi działa na reklamy między postami to `elektroda.pl##[class*=" postlink "]`
spacje muszą być bo za dużo wytnie (pic gpu-z) test na https://www.elektroda.pl/rtvforum/topic2888198.html#13911871
