### ISSUE TITLE
pcformat.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1846]
Pozostałość po reklamie na dole strony - `http://www.pcformat.pl/`

![image](https://cloud.githubusercontent.com/assets/11742596/21591678/a2029b50-d106-11e6-9853-84ea227ccd25.png)

Na przykład:
`pcformat.pl###ad_dol_srodek`

**Comment by xxcriticxx** [comment]
@F4z testowalem dobra regula
