### ISSUE TITLE
parkiet.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18470]
https://www.parkiet.com/artykul/170902.html

**Comment by xMaap** [comment]
U mnie czysto. Masz I don't care about cookies?

**Comment by krystian3w** [comment]
Cookies w dodatku PCZ lub dodatku IDCAC.

https://github.com/PolishFiltersTeam/PolishCookieConsent - ostatnio zmieniłem akceptowanie z klikania na pieczenie ciastek: https://github.com/PolishFiltersTeam/PolishCookieConsent/commit/811785bd6634f92fd2c6c95de1d56fc1dbd4d02e
