### ISSUE TITLE
kobieta.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1849]
maybe?

`http://www.kobieta.pl/rozrywka/kultura/zobacz/artykul/kinga-preis-nie-jestem-leniem/`

![capture](https://cloud.githubusercontent.com/assets/15007183/21593277/733d3e24-d0e3-11e6-96e6-447b66a15991.PNG)

**Comment by FadeMind** [comment]
```
kobieta.pl##.kolor_99cccd
```
albo
```
||ceneo.kobieta.pl/ceneo.php
```
ale wtedy zostaje ramka.

**Comment by kerbenii** [comment]
`kobieta.pl##.kolor_99cccd` jest za mocne, zniknie ramka "Najczęściej czytane - rozrywka".
ja radzę: `kobieta.pl###c11865`
