### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by TheChilliPL** [MajkiIT/polish-ads-filter#18509]
### Zrzut ekranu 

<img src="https://user-images.githubusercontent.com/18823939/104823907-ea34ff80-584d-11eb-8097-6bad41f76747.png" width=300>
<img src="https://user-images.githubusercontent.com/18823939/104824010-bf977680-584e-11eb-9789-f01ee4d524dd.png" width=300>
(click to open in full resolution/kliknij by otworzyć w pełnej rozdzielczości)

### Link bezpośredni 

<https://player.pl/programy-online/nauka-jazdy-odcinki,507/odcinek-2,S06E02,98992>

### Co trzeba zrobić, aby pojawił się element albo błąd?
Just open any video on Player.pl.
Wystarczy otworzyć jakikolwiek filmik na Player.pl.

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Chrome 87.0.4280.141 x64

**Rozszerzenia i skrypty:** 
Adblock Plus 3.10.1

**Listy filtrów:** 
1. EasyList Polish+EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Oficjalne polskie filtry przeciwko alertom o Adblocku 
4. ABP Filters

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):** ―

**Comment by xMaap** [comment]
Nie wiem jak działa w tych gdzie wymaga konta, ale np tutaj https://player.pl/seriale-online/chylka-odcinki,15976/odcinek-1,S01E01,124842 działa jak powinno.
Proponuje wywalić Adblock Plus i zainstalować uBlocka Origin lub AdGuard.

**Comment by TheChilliPL** [comment]
Być może faktycznie przez AdBlocka, na podanym linku mam ten sam problem. Później sprawdzę na innym adblocku

**Comment by TheChilliPL** [comment]
Zmiana rozszerzenia na AdGuard (aplikacja, nie rozszerzenie) i dodanie domyślnych filtrów + `Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda` wydaje się działać, zamykam issue

**Comment by krystian3w** [comment]
W sumie brak rozwiązań dla AdBlock / ABP i podobnie technicznie ograniczonych.
