### ISSUE TITLE
focusnauka.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#18514]
```
https://www.focusnauka.pl/artykul/odkryto-super-ziemie-liczaca-10-mld-lat-moze-byc-dowodem-na-istnienie-zycia-przed-ludzmi
https://www.przyslijprzepis.pl/przepis/serowe-mini-paczusie-z-nuta-pomaranczy
https://www.glamour.pl/artykul/glamour-glammies-2021-zgloszenia-do-7-edycji-wielkiego-urodowego-plebiscytu
```
![Zrzut ekranu z 2021-01-18 01-52-53](https://user-images.githubusercontent.com/36385327/104861386-e37eb900-592f-11eb-9894-f32d7e9ad8ef.png)

**Comment by AroKol78** [comment]
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=focusnauka.pl|glamour.pl`
 `focusnauka.pl` , `glamour.pl` do https://github.com/olegwukr/polish-privacy-filters
`przyslijprzepis.pl` już jest zrobione


tymczasowy  fix `@@||moviads.pl^$domain=glamour.pl`
do wymiany `||moviads.pl^$domain=~moviads.pl|~gala.pl` na `||moviads.pl^$domain=~moviads.pl|~gala.pl|~glamour.pl`

**Comment by AroKol78** [comment]
trochę więcej
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=focusnauka.pl|glamour.pl|elle.pl|kobieta.pl|elleman.pl
@@||moviads.pl^$domain=glamour.pl|kobieta.pl
```

**Comment by AroKol78** [comment]
@MajkiIT dodaj `kobieta.pl` https://github.com/MajkiIT/polish-ads-filter/commit/d60ef74912c4b7e34d3ea0840336a7176f5bb469#diff-eab2aaf469314f57267f6f71855a766738837ca60234d6105317854abe61152cR4088

test - https://www.kobieta.pl/artykul/bo-to-grzech-nowy-serial-hbo-porusza-przemilczany-temat-pandemii-aids-w-latach-80-210116111611
