### ISSUE TITLE
geekweek.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#18510]
Znika 3/4 strony: https://github.com/AdguardTeam/AdguardFilters/issues/72312

Naprawa:
```
#if !env_adguard
geekweek.pl##.adocean-billboard
#endif
```

**Comment by AroKol78** [comment]
nie tylko adguard - u mnie też (uBlock-for-firefox-legacy)
pomaga fix od **krystian3w** `https://github.com/AdguardTeam/AdguardFilters/issues/72312#issuecomment-761814370`
👍 `geekweek.pl#@#.adocean-billboard`

**Comment by AroKol78** [comment]
home `geekweek.pl` pas przezroczysty - nacisne w zaznaczonym miejscu, zwija się w prawo,[myList](https://user-images.githubusercontent.com/70756447/102889523-1a5dce00-445b-11eb-9dfa-8919f5ae110c.PNG) ("AdGuard Base" nie pomaga)
![bugeek1](https://user-images.githubusercontent.com/70756447/104850267-5ebf7b00-58ee-11eb-9675-02c0dca9c5b3.PNG)

**Comment by MajkiIT** [comment]
@krystian3w Dzięki

**Comment by AroKol78** [comment]
> home `geekweek.pl` pas przezroczysty - na....

pomaga wyłączenie - "POL: Oficjalne polskie filtry przeciwko alertom o Adblocku" 
(niezwiązane z `geekweek.pl#@#.adocean-billboard` - mam w "My filters")

**Comment by krystian3w** [comment]
Nie można zamknąć, skoro to `.adocean-billboard` psuje w Firefox "Legacy" i na Chromium.

W takim wypadku zostaje przemyśleć czy filtr ma racje bytu jak uszkadza stronę dla około 90% internatów, bo FX Quantum raczej mniej niż 10% używa.

**Comment by krystian3w** [comment]
https://github.com/olegwukr/polish-privacy-filters/issues/128

**Comment by AroKol78** [comment]
miałem podobne (góra załadowana-potem biało) https://github.com/AdguardTeam/AdguardFilters/issues/72312#issue-786945640 Screenshot 1
nie umiem powtórzyć błędu

> W takim wypadku zostaje przemyśleć czy filtr ma racje bytu jak uszkadza stronę dla około 90% internatów

jak zauważyłeś dotyczy to filtra "polish-privacy-filters"  - wystarczy usunąć zaznaczone fragmenty filtra https://github.com/olegwukr/polish-privacy-filters/issues/128#issuecomment-761865016
