### ISSUE TITLE
allegro.pl 

### ISSUE THREAD

**Issue by Tasiorsa** [MajkiIT/polish-ads-filter#18512]
### Zrzut ekranu 

![Screenshot_2021-01-17 Smartfon Xiaomi POCO X3 NFC 6 64GB LTE Dual SIM](https://user-images.githubusercontent.com/35109319/104853471-68061300-5901-11eb-80d7-f715d1d68c6d.png)

### Link bezpośredni 

Dowolny przedmiot na allegro.pl po otwarciu zdjęć.
Ponadto wycina pod nazwą użytkownika  "Jesteś SMART"

### Co trzeba zrobić, aby pojawił się błąd?
1. Zaktywować filtr alleblock
2. Otworzyć dowolną aukcję
3. Kliknąć na dowolne zdjęcie w aukcji

### Moja konfiguracja 
Adguard for Firefox

**Przeglądarka internetowa:** 
Firefox 84.0.2
**Rozszerzenia i skrypty:** 

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Alleblock
4. Polskie filtry językowe

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by MajkiIT** [comment]
@maciejtarmas chyba to Twoje

**Comment by krystian3w** [comment]
@MajkiIT nie to bug w Firefox, @Tasiorsa takie coś mam nawet na profilu bez dodatków, zapraszamy do otwarcia zgłoszenia na bugzilli:

https://bugzilla.mozilla.org/ (zalecany opis po angielsku).

**Comment by Tasiorsa** [comment]
Ale po wyłączeniu filtrów Alleblock allegro działa w Firefox poprawnie. To na pewno bug FF?

**Comment by krystian3w** [comment]
Tak, spróbuj załadować np. "informacje o sprzedawcy" też się ładują w kółko i drugie odświeżenie dopiero pozwala załadować oceny i opinie:

![ac](https://user-images.githubusercontent.com/35370833/104884492-bd284000-5966-11eb-8a34-f7a850df54e6.png) |
--- |

Edge za pierwszym razem ładuje opinie bez problemu.

**Comment by Tasiorsa** [comment]
U mnie bez filtrow alleblock ładuje się wszystko poprawnie!
[https://i.imgur.com/OlqLloy.png](url)

Moje eksportowane settings: `{"protocol-version":"1.0","general-settings":{"app-language":"pl","allow-acceptable-ads":false,"show-blocked-ads-count":true,"autodetect-filters":true,"safebrowsing-enabled":true,"filters-update-period":3600000},"extension-specific-settings":{"use-optimized-filters":false,"collect-hits-count":false,"show-context-menu":true,"show-info-about-adguard":true,"show-app-updated-info":true},"filters":{"enabled-groups":[1,2,3,4,5,7],"enabled-filters":[13,14,16,1,224,2,3,4,6,9,105,109,120,216,217,221,227,232,238,246,207,242,249],"custom-filters":[],"user-filter":{"rules":"powrotroberta.pl###page > div.elementor.elementor-18571.elementor-location-header:nth-child(2) > div.elementor-section-wrap > section.elementor-section.elementor-top-section.elementor-element.elementor-element-a4bf1a3.elementor-section-stretched.elementor-section-full_width.elementor-section-height-default:first-child > div.elementor-container.elementor-column-gap-no > div.elementor-row > div.elementor-column.elementor-col-100.elementor-top-column.elementor-element.elementor-element-32ee50a > div.elementor-column-wrap.elementor-element-populated > div.elementor-widget-wrap > div.elementor-element.elementor-element-8383bc2.elementor-widget.elementor-widget-image > div.elementor-widget-container > div.elementor-image > a > img\npepper.pl###toc-target-deals > div.cept-event-deals.js-threadList.listLayout-main:first-child > a.cept-event-banner.countdownBanner--h-6.box--all-b.box--fromW2-f.width--all-12.space--h-3.space--v-3.space--fromW3-h-4.space--fromW3-t-4.space--fromW3-b-4.boxAlign-ai--all-c.hAlign--all-c.bg-img--cover.bg--color-feature.text--color-white.listLayout-mainItem:nth-child(4)","disabled-rules":""},"whitelist":{"inverted":false,"domains":["alltube.tv","cda-flix.pl","dropgalaxy.com","www.corsair.com","www.asus.com","alltube.pl","192.168.1.34","kinovod.tv","alltube.com.pl","www.orange.pl","drive.google.com","www.gov.pl","szczepimysie.pacjent.gov.pl"],"inverted-domains":[]}}}`

Po włączeniu AlleBlock mam tak jak Ty @krystian3W

**Comment by krystian3w** [comment]
Ja nie używam, a opinie się nie ładują w Firefox od chyba wydania 79+.

**Comment by krystian3w** [comment]
Na bug z grafikami działa:

`||a.allegroimg.com/original/*$domain=allegro.pl,badfilter`

nie wiem co oryginalnie blokowało, ale to już raczej zostaje regex lub przebudowa na kilka filtrów.

**Comment by Tasiorsa** [comment]
||a.allegroimg.com/original/*$domain=allegro.pl,badfilter

Faktycznie rozwiązuje problem nie wyświetlanych grafik i o sprzedającym. Jeszcze tylko został mały problem że wycina "Jesteś SMART" i ten panel pod nazwą użytkownika

**Comment by krystian3w** [comment]
To już raczej założenie listy by "nie kupować" smart (czy też ukrywanie tego zbędnego napisu) i raczej w ustawieniach zaawansowanych pilnować czy nie chcemy płacić z automatu kolejnych "49 zł" za darmowe wysyłki i czasem kuriera.

Co do panelu to chyba przyda się znowu zdjęcie - homepage raczej z założenia też ma być pusty i musisz szukać konkretów i filtrują łapać perełki. Pewnie promocje lub promocje smart są uznane za wietrzenie magazynów lub wabik do kolejnego "zakupoholizmu".

**Comment by Tasiorsa** [comment]
Bez Alleblock
https://i.imgur.com/kBEEv5C.png

Z AlleBlock
https://i.imgur.com/mQze958.png

Chodzi o to że napis Jesteś Smart i link pod nim oraz ten panel "Cześć Krzysztof" i te 3 pozycje w dół powinny zostać z włączonym AlleBlock

**Comment by Tasiorsa** [comment]
Masz rację panel powrócił. A żeby wrócił napis jesteś SMART? Bo jak klikasz to ci sie otwiera panel do smarta i okazje dla SMARtowców

**Comment by krystian3w** [comment]
Sprawdzałeś: `allegro.pl#@#div[data-box-name="allegro.login.smart.status"]` ja mam "wkrótce wygasa" i to go przywraca.

Niby 5-12 ofert widzę pod adresem:

https://allegro.pl/moje-allegro/zakupy/allegro-smart (raczej mało zachęcające) (`##div[data-box-name^="mysmart"] + div + div`)

**Comment by Tasiorsa** [comment]
allegro.pl#@#div[data-box-name="allegro.login.smart.status"]
Elegancko przywróciło jesteś SMART. Dla mnie można zamknąć!
Dziękuje za pomoc!

**Comment by krystian3w** [comment]
Możesz zrobić to samodzielnie, Maciej od AlleBlock ma już 2 zgłoszenia o zbugowanych ikonach spod `a.allegroimg` w swoim repozytorium.

**Comment by xxcriticxx** [comment]
@Tasiorsa what's up Krzysztof
