### ISSUE TITLE
radiokolor.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1853]
pusta box po reklamie

**Comment by MajkiIT** [comment]
`radiokolor.pl##.advert750x100`

**Comment by kerbenii** [comment]
Moim zdaniem skuteczniejszy będzie:
`planeta-kobiet.pl##.boxAdvert`

Bo przecież reklamy mogą mieć też inne wymiary ;)

**Comment by MajkiIT** [comment]
@kerbenii ale to nie do tej strony :D

**Comment by kerbenii** [comment]
Do tej tylko się machnąłem i domeny nie zmieniłem jak przeklejałem xD
`radiokolor.pl##.boxAdvert`
