### ISSUE TITLE
kobieta.pl

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#18546]
https://www.kobieta.pl/artykul/jak-przeniesc-szalony-styl-lat-80-do-stylizacji-wedlug-najnowszych-trendow-201028121453
![kobietplbug2](https://user-images.githubusercontent.com/70756447/105160026-08318700-5b10-11eb-98c7-85527f0f5113.PNG)
"POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuard"
błąd `||moviads.pl^$domain=~moviads.pl|~gala.pl|~glamour.pl`
naprawa `||moviads.pl^$domain=~moviads.pl|~gala.pl|~glamour.pl|~kobieta.pl`
tymczasowa naprawa `@@||moviads.pl^$domain=kobieta.pl`

(:confused: https://github.com/MajkiIT/polish-ads-filter/issues/18514#issuecomment-762440238)

**Comment by krystian3w** [comment]
Jak zadziała to:

`||moviads.pl^$important,redirect=noopmp4-1s,domain=moviads.pl|gala.pl|glamour.pl|kobieta.pl`

**Comment by AroKol78** [comment]
testowałem
off -"POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuard"
add my filtr -`||moviads.pl^$important,media,object,redirect=noopmp4-1s,domain=moviads.pl|gala.pl|glamour.pl|kobieta.pl`
**nie działa**
czy ubo legacy w ogóle obsługuje `redirect=`, czy przepuści / zablokuje wszystko `redirect=noopmp4-1s'

**Comment by krystian3w** [comment]
Raczej  puste mp4 już było w uBO 1.13.2+.

**Comment by AroKol78** [comment]
> Co do działania to widzę, że raz na 10 prób będzie alternatywny materiał z domeny:
`https://storage.platform.streamextension.com/307/g/m/3/x/gm3xy72yuy_360p.mp4`

może trzeba dodać wyjątki też na `streamextension.com`
tak jak to ma miejsce w przypadku `moviads.pl`

**Comment by krystian3w** [comment]
> może trzeba dodać wyjątki też na `streamextension.com`

Jak znajdziesz przykład reklam serwowanych z ich domeny, jak tak to raczej nie warto blokować domeny w ogóle.

**Comment by AroKol78** [comment]
```
||moviads.pl^$important,media,redirect=noopmp4-1s,domain=moviads.pl|gala.pl|glamour.pl|kobieta.pl
||moviads.pl^$important,object,redirect=noopmp4-1s,domain=moviads.pl|gala.pl|glamour.pl|kobieta.pl
```
odtwarz tylko 1s , wcisnę play nastepny filmik 1s

---
póki co 1 komentarz jest aktualny
