### ISSUE TITLE
futbol.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1855]
sponsor serwisu Milenium

**Comment by kerbenii** [comment]
Ci to już tak naprali tymi reklamami 👅 
`
/img/bg_milenium_logo.png
futbol.pl###gbbill_866951
futbol.pl##header > .container > a >img
futbol.pl##.advert
futbol.pl##.adroll-block
`

**Comment by xxcriticxx** [comment]
@kerbenii ten język to masz na auto ustawione ze za każdym razem się wyświetla

**Comment by kerbenii** [comment]
@xxcriticxx usunąłem. Jakoś tak go dzisiaj wklejam xD
