### ISSUE TITLE
meteo.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#18573]
### Zrzut ekranu 
![image](https://user-images.githubusercontent.com/18230443/105671895-c2940600-5ee3-11eb-8d90-bd437bc1c531.png)
Białe divy po zablokowanych reklamach.

### Link bezpośredni 
http://www.meteo.pl/

**Comment by krystian3w** [comment]
Więc nie błąd a resztka reklamowa.
