### ISSUE TITLE
interia.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#18584]
![Screenshot_1](https://user-images.githubusercontent.com/21177361/105850376-edfd1a80-5fe1-11eb-8618-ff71b3df329e.png)

https://biznes.interia.pl/finanse/news-oszczedzanie-lutowe-obligacje-z-niezmienionym-oprocentowanie,nId,5008778

**Comment by AroKol78** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/17220

**Comment by krystian3w** [comment]
U mnie też, @olegwukr / @MajkiIT  dokopujcie `redirect` do pliku `anti-adblock-suplement-adguard.txt`.

https://github.com/olegwukr/polish-privacy-filters/blob/71aba105f84943b9afbdffe23b48d7bf69e0c2b2/anti-adblock-suplement-adguard.txt#L104 - gdzieś około linii 104

**Comment by krystian3w** [comment]
@AroKol78 ale nie chodzi by sobie ręcznie naprawiać Interię, na dwa dni warto wkleić do suplementów tamten filtr skryptowy lub zobaczyć czy AdGuard też blokuje czymś:

`securepubads.g.doubleclick.net/tag/js/gpt.js`

**Comment by AroKol78** [comment]
> AroKol78 ale nie chodzi by sobie ręcznie naprawiać Interię, na dwa dni warto wkleić do suplementów tamten filtr skryptowy lub zobaczyć czy AdGuard też blokuje czymś:

nie wiedziałem że chodzi konkretnie o AdGuard
w ubo (googletagservices_gpt.js) mi naprawili jak zgłosiłem
pisałem o problemie w https://github.com/MajkiIT/polish-ads-filter/issues/17220

**Comment by xxcriticxx** [comment]
ja na ubo 1.32.4 tez mam adblock

**Comment by gzenio22** [comment]
Ja bez problemu moge do adguarda to zgłosić tylko po co jak to i tak najprawdopodobniej trafilo by do nas? interia hehe nie jest serwisem globalnym @AroKol78 Przynajmniej obecnie nie jest bo kto wie co soroż ze swoim polsatem wymyśli

**Comment by AroKol78** [comment]
interia korzysta z globalne usługi "googletagservices"

tak jak na ubo łatają "googletagservices"
"Missing neutralized GPT (googletagservices_gpt.js) library method calls throw script errors"

**Comment by krystian3w** [comment]
> interia hehe nie jest serwisem globalnym

ale nie jest też portalem z 52 odwiedzającymi na rok by ich olać. Mogą w każdej chwili na każdą subdomenę `.interia.pl` aktywować tę planszę skoro na pomponiku się sprawdza.

**Comment by gzenio22** [comment]
@krystian3w  puscic to do Adguarda? To sugerujesz? :) ja tam nie wiem jakie interia ma wejscia i szczerze nie bardzo mnie to interesi :D

**Comment by AroKol78** [comment]
zrobione https://github.com/olegwukr/polish-privacy-filters/commit/a7c9da93056bdf40a34475cc8f8534309c073115

**Comment by gzenio22** [comment]
zatem zamykam i dziękuje :)
