### ISSUE TITLE
criteo.net

### ISSUE THREAD

**Issue by ghost** [MajkiIT/polish-ads-filter#1859]
Tak z ciekawości 👅 
Czemu static.criteo.net jest na whiteliście?

**Comment by xxcriticxx** [comment]
need for wp.pl

**Comment by F4z** [comment]
Chodzi o to - `@@||static.criteo.net/js/ld/publishertag.js$script,domain=wp.pl`?
Jeśli tak, to to zostało dodane, bo znikały filmy na różnych podstronach wp.pl - https://github.com/MajkiIT/polish-ads-filter/issues/1616 https://github.com/MajkiIT/polish-ads-filter/issues/1627

**Comment by kerbenii** [comment]
a, kk.
To wp to nieźle stara się adBlock'a wykiwać widzę

**Comment by xxcriticxx** [comment]
My tez się staramy!

**Comment by kerbenii** [comment]
Wiem, przecież sam to robię :-) Tylko się śmieje, że aż takie zabezpieczenia robią 👅 
Bo tutaj wręcz oni sprawdzają czy odpowiedni obiekt istnieje, albo czy odpowiedni request przeszedł xD

**Comment by xxcriticxx** [comment]
Jest tego trochę więcej

**Comment by xxcriticxx** [comment]
@F4z @MajkiIT 

chyba dla @kerbenii konto zamkneli?

**Comment by MajkiIT** [comment]
@xxcriticxx no coś w tym jest. Może za to samo co Tobie kiedyś?

**Comment by MajkiIT** [comment]
A nie on jest teraz @ghost ?

**Comment by xxcriticxx** [comment]
ghost = deleted user

**Comment by F4z** [comment]
Ja miałem tak samo.
Napisałem do nich używając tego formularza - https://github.com/contact - i po niecałej godzinie odblokowali mi konto.
