### ISSUE TITLE
cowkrakowie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#18593]
![Screenshot_2021-01-28 Wiadomości z Krakowa, Kraków Informacje - Co w Krakowie - Twoje źródło informacji](https://user-images.githubusercontent.com/36385327/106202695-8948e800-61ba-11eb-9aa9-333f9d3a95cf.png)

**Comment by MajkiIT** [comment]
`###custom_html-6`

**Comment by xxcriticxx** [comment]
@MajkiIT Ja bym ta pania w czarnym zostawil :)
