### ISSUE TITLE
android.com.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#18605]
![Screenshot_1](https://user-images.githubusercontent.com/21177361/106968179-a5173580-6748-11eb-96c8-213ea10fa932.png)

link : https://android.com.pl/porady/193065-brak-miejsca-w-pamieci-telefonu/

**Comment by MajkiIT** [comment]
@gzenio22 u mnie czysto

**Comment by xxcriticxx** [comment]
@gzenio22 adguard?

**Comment by gzenio22** [comment]
@MajkiIT U mnie teraz też czysto @xxcriticxx Tak Adguard

**Comment by gzenio22** [comment]
Zamykam bez sensu zeby wisiało skoro reklama znikła
