### ISSUE TITLE
whatnext.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#18612]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/107198851-eda74b00-69f5-11eb-8239-a82d99854f35.png)
-->
![obraz](https://user-images.githubusercontent.com/32641928/107198893-fc8dfd80-69f5-11eb-90ff-599903bfefc5.png)

### Link bezpośredni 

https://whatnext.pl/test-dysku-samsung-970-evo-plus-1-tb/

### Co trzeba zrobić, aby pojawił się błąd?
1. 
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda (2021.01.14.0)
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List
11. AdGuard Tracking Protection
12. AdGuard Base
13. AdGuard Mobile Ads
14. Fanboy’s Social 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Brak obrazków przy włączonym ublocku

**Comment by hawkeye116477** [comment]
`whatnext.pl#@#a[data-size="0x0"] > img`

**Comment by hawkeye116477** [comment]
Gdzie się podział @MajkiIT? Już z tydzień go nie ma.

**Comment by xxcriticxx** [comment]
@hawkeye116477 zakwasy ma po sniegu

**Comment by MajkiIT** [comment]
@hawkeye116477 Mam trochę roboty w pracy w nowych projektach. Za tydzień powinno być już po staremu. Dzięki za troskę. 
@xxcriticxx :D a ty miałeś mnie nie podglądać :P
