### ISSUE TITLE
disco-polo.info

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#18625]
![Screenshot_1](https://user-images.githubusercontent.com/21177361/107796383-0eef9a80-6d5a-11eb-8ec7-48a06b89b781.png)

**Comment by krystian3w** [comment]
Masz nieaktywną pewnie listę Fanboy Social lub polskie filtry społecznościowe.

Sprawdź wtedy, jak wycieka to musismy dodać fix w pliku bugi_AdGuard (AdGuard uwielbia je odblokowywać w swojej liście "Social Media").

**Comment by gzenio22** [comment]
@krystian3w  Nie uzywam fanboya mam naszą listę socjalną to nasza nie blokuje

**Comment by krystian3w** [comment]
Nasza wymaga właśnie dalej Fanboy Social.

**Comment by gzenio22** [comment]
@krystian3w oki dodałem i gitara działa więc zamykam
