### ISSUE TITLE
reklama-wolomin.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18620]
Waterfok UK versjon ma a na PL niema

**Comment by krystian3w** [comment]
Znaczy co ma?

W prawym rogu normalnie widzę:

```
reklama-wolomin.pl##.eu-cookies-bar-cookies-bar-wrap
reklama-wolomin.pl##.eu-cookies-bar-cookies-settings-call-button

```

**Comment by blocker999** [comment]
ciastka, na angielskiej wersji Waterfoxa

**Comment by krystian3w** [comment]
Ale inne niż `eu-cookies-bar-cookies-bar-wrap` / `eu-cookies-bar-cookies-settings-call-button`
