### ISSUE TITLE
adblock - informacja

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1867]
http://www.wirtualnemedia.pl/artykul/uzytkownicy-adblockow-bez-dostepu-do-tresci-na-business-insider-polska-i-plejada-pl

**Comment by FadeMind** [comment]
SOA#1
![inwestorzy uciekli z polski najwiekszy odplyw kapitalu od stycznia - google chrome_001](https://cloud.githubusercontent.com/assets/9846948/21609700/3c57316c-d1c4-11e6-83f8-5b2ceaebe76c.png)
