### ISSUE TITLE
www.neuca.pl 

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#18670]
/cookiecon__cookieConsent?$script globalnie dla SalesForce

https://www.neuca.pl/s/?language=pl

**Comment by krystian3w** [comment]
Ja tego nie widzę, chyba że złe demo dajesz.

Raczej już żaden projekt nie dba by "zawsze" blokować dla oszczędności transferu danych a sięga się po filtry CSS `:style` i `+js`.

**Comment by MajkiIT** [comment]
![obraz](https://user-images.githubusercontent.com/11302675/107979354-ba992480-6fbe-11eb-8952-d875ba1baaae.png)

**Comment by hawkeye116477** [comment]
Chyba to lista Pete Lowe's już blokuje.
