### ISSUE TITLE
antyweb.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1869]
@F4z @xxcriticxx @mathew85 @FadeMind @kerbenii 

mam do Was prośbę. Czy możecie otworzyć stronę:` http://antyweb.pl/anti-adblock-killer-czyli-adblock-ktory-blokuje-tych-ktorzy-blokuja-adblocka/`

najpierw bez reguły a potem z regułą `||disqus.com$domain=antyweb.pl` i porównać czas otwierania?

**Comment by FadeMind** [comment]
@MajkiIT bez `disqus` strona wczytuje się szybciej, ale nie ma obsługi komentarzy.
`
![zaznaczenie_003](https://cloud.githubusercontent.com/assets/9846948/21611562/a08ff156-d1cd-11e6-9180-57feb1f1e2de.png)

**Comment by F4z** [comment]
@MajkiIT patrząc po czasie pokazywanym w panelu "network" w Chrome oraz sprawdzając na tej stronie - `http://www.raymondhill.net/ublock/pageloadspeed.html` - to u mnie jest jakieś niecałe pół sekundy różnicy. W przypadku sprawdzania na stronie, to średnio było 260,86 milisekund różnicy.
Nie używając żadnych tego typu narzędzi w zasadzie większej różnicy nie widzę.

**Comment by mathew85** [comment]
U mnie to jakieś 1-1,5s różnicy na stronie, którą podał @F4z

**Comment by xxcriticxx** [comment]
@MajkiIT strona dziala wolno?

**Comment by MajkiIT** [comment]
@xxcriticxx no właśnie wczoraj coś muliło i szukałem powodu.
