### ISSUE TITLE
architekci.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18712]
fb ( u góry )

**Comment by krystian3w** [comment]
Nie liczy się; to jest button do logowania, niech Ci @seba2282 uruchomi listę w jakiej wycina przyciski umożliwiające logowanie Facebookiem / kontem Google.

A problem z blokowaniem uszkodzonych buttonów logowania jest taki, że już raczej nikt w ciągu roku nie sprawdzi czy twórcy naprawili wtyczkę `facebook.com/dialog/oauth`

**Comment by seba2282** [comment]
> Nie liczy się; to jest button do logowania, niech Ci @seba2282 uruchomi listę w jakiej wycina przyciski umożliwiające logowanie Facebookiem / kontem Google.
> 
> A problem z blokowaniem uszkodzonych buttonów logowania jest taki, że już raczej nikt w ciągu roku nie sprawdzi czy twórcy naprawili wtyczkę `facebook.com/dialog/oauth`

 
O co chodzi? @krystian3w

**Comment by krystian3w** [comment]
Strona ma buttonik logowania Facebookiem w nagłówku, jak ten na dobrych programach z pomocą konta Google / Gmail.

MajkiIT powiedział że nie ma sensu ich blokować, to jak wam wadzą to musicie zrobić własny projekt - "listę".

**Comment by seba2282** [comment]
Mobilnie go nie widzę. Możesz dać screen? Mam firefox nightly Android.

**Comment by krystian3w** [comment]
DP.do | architekci
--- | ---
![obraz](https://user-images.githubusercontent.com/35370833/108423399-18847100-7238-11eb-9dd2-ccf818119dda.png) | ![obraz](https://user-images.githubusercontent.com/35370833/108423484-30f48b80-7238-11eb-8c8a-9d9aa72da3b5.png)

**Comment by krystian3w** [comment]
> Tylko przycisk Facebook? 

 Tak ale jak uruchomisz swoje repozytorium:

"[github.com/seba2282/social-login-buttons-blocker-list](/seba2282/social-login-buttons-blocker-list)"

**Comment by seba2282** [comment]
Sądziłem, że mam dać mu regułę do blokowania. 😅

**Comment by seba2282** [comment]
> ||architekci.pl/static/img/fb-connect.png

Ja to też uzyskałem biorąc na ublock origin zablokuj element.

**Comment by seba2282** [comment]
@krystian3w sprawdź czy dobrze działa dla DP: 
ssl.dobreprogramy.pl##.version2.fb-body.fb-button-frame.form-input-group

**Comment by krystian3w** [comment]
Łapie cały blok WP/Google/FB, musisz ustalić czy Blocker będzie chciał ukrywać też zaloguj usługą "1login od WP".

**Comment by seba2282** [comment]
Można i tak, ale kto chce patrzeć na WP login? :D

**Comment by seba2282** [comment]
@blocker999 
Cały blok (WP/Google/FB) na dobreprogramy:
ssl.dobreprogramy.pl##.version2.fb-body.fb-button-frame.form-input-group

Lub bez WP 1login na dobreprogramy:
ssl.dobreprogramy.pl##.version2.fb-body.fb-button-frame.form-input-group

Architekci.pl przycisk FB:
||architekci.pl/static/img/fb-connect.png
lub:
architekci.pl##.fb-login

**Comment by krystian3w** [comment]
Y... źle ci się skopiowało oszczędzanie "1login od WP".

**Comment by seba2282** [comment]
Teraz dobrze, tak sądzę.

**Comment by seba2282** [comment]
Chcę gdzieś dodać na cały blok tych social do blokowania. Macie gdzieś miejsce gdzie można te filtry testowo dodać? Albo nie wiem, jak to nazwać.

**Comment by krystian3w** [comment]
może na `gist.github.com`? https://gist.github.com/

```
[Adblock Plus 3.5]
! Title: Blokuj logowanie Facebookiem - itp.
! Version: 1
! Expires: 1 day
! Homepage: https://https://gist.github.com/seba2282/---/edit
! Authors: @seba2282, @blocker999 
!
! ### Cały blok (WP/Google/FB) na dobreprogramy:
ssl.dobreprogramy.pl##.version2.fb-body.fb-button-frame.form-input-group
!
! ### Lub bez WP 1login na dobreprogramy:
ssl.dobreprogramy.pl##:not(#lnkOneLogin).social-login-button
!
!
! ### Architekci.pl przycisk FB:
||architekci.pl/static/img/fb-connect.png
! # lub:
architekci.pl##.fb-login
!
```

W linku z przycisku raw (po zapisie) usuwasz drugą część za frazą /raw/:
```
  [link demonstracyjny]
https://gist.githubusercontent.com/krystian3w/98226cc9ee052c97b12ae894cfe235a8/raw/658a3a7892f9e92ef92ce9720f0c8d2b7ed0e8af/base64.html
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                    (wywalamy id commita by plik dynamicznie pobierał się najnowszy)
```

**Comment by seba2282** [comment]
https://gist.github.com/seba2282/7b517bcf0b6f75a38be8f51f69539111#file-special-filter-by-seba2282

Testowy. Nie wiem czy dobrze mi wyszedł.

**Comment by krystian3w** [comment]
taki próbuj zasubskrybować:

[https://gist.githubusercontent.com/seba2282/7b517bcf0b6f75a38be8f51f69539111/raw/special%2520filter%2520by%2520seba2282](https://subscribe.adblockplus.org/?location=https://gist.githubusercontent.com/seba2282/7b517bcf0b6f75a38be8f51f69539111/raw/special%2520filter%2520by%2520seba2282&title=Blokuj%20logowanie%20Facebookiem%20-%20itp.)

**Comment by seba2282** [comment]
Mam go dodany i działa mi.

**Comment by seba2282** [comment]
@krystian3w Gdzie teraz jest temat wp?
Potwierdzisz skuteczność na blokowanie reklam na dobreprogramy.pl (bez zalogowania) z tą regułą i na wp.pl, że ona nie blokuje obrazów? U mnie działa 

 ||v.wpimg.pl/*$image,domain=dobreprogramy.pl

**Comment by seba2282** [comment]
https://gist.githubusercontent.com/seba2282/7b517bcf0b6f75a38be8f51f69539111/raw/e10ac0ccc2681895212b5dd2d10c6ae5c6a93247/special%2520filter%2520by%2520seba2282

Trochę edytowałem i wyciągnąłem raw.

**Comment by krystian3w** [comment]
Nie widzę wycieku reklam po wylogowaniu, a najnowszy temat znajdziesz pod numerem `18472`

Na dobrych programach raczej dalej grafiki są z `dpcdn.pl`, więc filtr można wrzucić jak w loggerze widać mnóstwo grafik reklamy ukrytych kosmetycznie lub pokonujących filtry `+js(...` / `redirect=...` (opcjonalnie już masz nowszą wersje skryptu reklam WP odporną na starsze filtry).

**Comment by seba2282** [comment]
> (opcjonalnie już masz nowszą wersje skryptu reklam WP odporną na starsze filtry)

Mi wyciekały reklamy, które są na v.pimg.pl 
Wiedząc, że zablokowanie całego v.wpimg.pl wiąże się z ukryciem obrazów na wp.pl (wszystkich), pozwoliłem sobie na przyblokowanie tego na DP, bo tutaj jest na v.wpimg.pl.

**Comment by seba2282** [comment]
https://gist.githubusercontent.com/seba2282/7b517bcf0b6f75a38be8f51f69539111/raw/special%2520filter%2520by%2520seba2282

**Comment by seba2282** [comment]
Dodałbym jeszcze to na ukrycie sponsor linku do innej strony na dole prawa strona

`www.architekci.pl##.mamf`
