### ISSUE TITLE
animalpoint.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18738]
fb ( na dole )

**Comment by seba2282** [comment]
`www.animalpoint.pl##._2lW-H`

`www.animalpoint.pl##._3LmCZ`

`www.animalpoint.pl###i4x7lb8s > .yuKeh`

`www.animalpoint.pl###comp-k1fk8koe`


FB button, te cyferki co były pod buttonem i to po lewej stronie, co sygnalizuje, że nie można było załadować strony z jakiegoś tam innego serwera, co nie działa aktualnie.
