### ISSUE TITLE
mobileclick.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#18732]
https://mobileclick.pl/poznaj-10-przydatnych-aplikacji-dla-seniora/
![Zrzut ekranu z 2021-02-19 11-38-42](https://user-images.githubusercontent.com/36385327/108493807-10afe580-72a7-11eb-9e52-72548dd11e07.png)

**Comment by hawkeye116477** [comment]
Strona się teraz popsuła 😔
