### ISSUE TITLE
pawelkrolart.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18735]
( na dole )

**Comment by seba2282** [comment]
www.pawelkrolart.com###dataItem-im552wi91-comp-im552whw > ._3LmCZ
www.pawelkrolart.com###dataItem-jtjtkqcw2-comp-jtjtkq9j > ._3LmCZ

**Comment by AroKol78** [comment]
```
używaj znaku ` na początku i końcu linii
```

**Comment by seba2282** [comment]
> **seba2282**
> 
> ```
> używaj znaku ` na początku i końcu linii
> ```

Gdzie? W postach?

**Comment by AroKol78** [comment]
@seba2282
tak tylko w postach , nie dawaj w swoim liście
będzie bardziej czytelny , **github nie zinterpretuje tego po swojemu**
przykład
 `www.pawelkrolart.com###dataItem-im552wi91-comp-im552whw > ._3LmCZ`

jeśli chcesz zaznaczyć więcej linii, podaj trzy znaki na początku i na końcu bloku
przykład
```
www.pawelkrolart.com###dataItem-im552wi91-comp-im552whw > ._3LmCZ
www.pawelkrolart.com###dataItem-jtjtkqcw2-comp-jtjtkq9j > ._3LmCZ
```

**Comment by AroKol78** [comment]
**seba2282**
widzę że poszukiwałeś znaku https://github.com/MajkiIT/polish-ads-filter/issues/18735#issuecomment-782390344
```
klawisz ze znakiem [`] znajduje się przed klawiszem [1] , między klawiszem [esc] a klawiszem [tab]
```
(standardowa klawiatura "qwerty" - standardowy układ klawiszy)

**Comment by seba2282** [comment]
Tak poszukiwałem mobilnie tego znaku także.
