### ISSUE TITLE
polnapol.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18736]
( na dole )

**Comment by seba2282** [comment]
www.polnapol.com.pl##._2qI_L

**Comment by krystian3w** [comment]
Randomowe, w kodzie strony są lepsze "czytelniejsze":

````
~polnapol.com.pl##ul[aria-label="Pasek społecznościowy"]
 polnapol.com.pl##ul[aria-label="Pasek społecznościowy"] > li:nth-of-type(n+2):nth-of-type(-n+4)
              pl##ul[aria-label="Social Bar"]
````

Ale to raczej powinno zainteresować fanboya, bo Wix generator stron jest "międzynarodowy".

**Comment by krystian3w** [comment]
To też Wix: https://github.com/MajkiIT/polish-ads-filter/issues/18736#issuecomment-782634647

**Comment by seba2282** [comment]
No masz. A dodałeś regułę do DP też na reklamy? Bo nie wiem jak w firefox, ale na Edge chromium, wyciekają one na v.wpimg.pl, kiedy nie jesteś zalogowany. @krystian3w

**Comment by krystian3w** [comment]
Nie dodawałem, bo nie mam uprawnień do edycji listy reklamowej bez wysłania `Pull requesta`.

Raczej brzydko będzie blokować te obrazki w liście:

- społecznościowej (PR needed)
- rodo/ciasteczkowej (PR needed)
- KAD - przekręty/anty-scam
- Filtry elementów irytujących (głównie tła autopromocyjne pod treścią)
- w RSS, obecnie nazywanym `PolishAntiAnnoyingSpecialSupplement`

**Comment by seba2282** [comment]
Ja się tak zastanawiam, bo na razie idzie mi amatorsko. Coś tam zablokuję, ale wy i tak dajecie inne reguły finalnie. Więc czemu mnie otagowałeś jako do usuwania buttonów, jeżeli robisz to lepiej? Ja jestem na razie amatorem i nie jestem doświadczony. A ty masz długi staż pracy z regułami do adblockerów, @krystian3w :)

**Comment by krystian3w** [comment]
To ty coś źle zrozumiałeś (że musisz zacząć wycinać wszystkie buttony social/paski cookies/sekcje z partnerami strony), mogę cię oznaczać jak znowu Blocker lub xMaap zgłosi button do logowania a nie przekierowujący na "fanpage".

**Comment by seba2282** [comment]
@krystian3w, ale na większość co kliknąłem, przekierowywało na fanpage. Nie wiem czy dobrze zrobiłem dotychczas, ale nadal próbuję. Cóż jeszcze słabo mi to idzie. 😅😅😅😅😅😅😅😅😅😅😅😅😅😅😅😅 Ale jest trochę frajdy, że mogę się udzielać w drobnej pomocy wam wszystkim. 🙂🙂🙂🙂🙂🙂🙂🙂🙂🙂
