### ISSUE TITLE
arena.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#18730]
![Zrzut ekranu z 2021-02-19 11-36-26](https://user-images.githubusercontent.com/36385327/108493556-bf075b00-72a6-11eb-9f8f-16a462a080ce.png)

**Comment by seba2282** [comment]
arena.pl##.jss1324.MuiContainer-maxWidthXl.jss1325.MuiContainer-root  

arena.pl##.MuiGrid-direction-xs-column.MuiGrid-container.MuiGrid-root

arena.pl##.MuiGrid-spacing-xs-1.MuiGrid-container.jss1336.MuiBox-root.MuiGrid-root

Partnerzy, cookies na dole i social media przyciski.

**Comment by krystian3w** [comment]
Cookies wycięte wczoraj, partnerzy wadzą tylko @xMaap i może tobie (majkiit już rzadko je wycina jak nie wyprosisz).

Dodatkowo randomowe, zmienią numerek `jss` i momentalnie padnie.

**Comment by seba2282** [comment]
> Cookies wycięte wczoraj, partnerzy wadzą tylko @xMaap i może tobie (majkiit już rzadko je wycina jak nie wyprosisz).
> 
> Dodatkowo randomowe, zmienią numerek `jss` i momentalnie padnie.

Ja wyciąłem dla niego wszystko. I dodałem reguły. :)
