### ISSUE TITLE
tvp.pl

### ISSUE THREAD

**Issue by Lukjan38** [MajkiIT/polish-ads-filter#18747]
na tvp.pl, brak reszty strony, tylko jest gora.

**Comment by MajkiIT** [comment]
To nie wina adblocka tylko alertu o RODO/Ciasteczkach #@#.tvp-cookie-overlay

**Comment by Lukjan38** [comment]
jak wyczyszcze cookies na tvp.pl, to nie pomaga

**Comment by seba2282** [comment]
> To nie wina adblocka tylko alertu o RODO/Ciasteczkach `#@#.tvp-cookie-overlay`

Odnośnie tvp.pl mam inny problem. Nie działa mi przewijanie strony w Edge chromium (przynajmniej wczoraj to widziałem).

**Comment by krystian3w** [comment]
Dajcie dokładne linki do testowania jak trzeba odblokować przewijanie lub dziwignąć header.

**Comment by krystian3w** [comment]
@MajkiIT  ale tylko taki filtr jest w liście:

https://github.com/MajkiIT/polish-ads-filter/blob/e7ded5355166b76729f459a4abd5e2ca32434bcc/cookies_filters/adblock_cookies.txt#L415

kiboke ma z dwoma `:not(...)` i nie wolno ich pomijać w `#@#`.

**Comment by seba2282** [comment]
Pytałeś o dokładny o dokładny link. Główna. Moment przewija, ale jak się załaduje, przewijak stopuje funkcjonalność.

Mówisz Kiboke skopał w dodatku? Czy w filtrze? Bo używam dodatku aktualnie.

**Comment by krystian3w** [comment]
Skopał w liście filtrów, dodatek nie akceptuje RODO na `www.tvp.pl` pewnie w 3.2.9 doda  takie coś:

```
||tvp.pl/files/portale-*/polityka-prywatnosci/*.$script,stylesheet
```

Niby można zablokować sieciowo ten folder

**Comment by seba2282** [comment]
@krystian3w, możliwe.

**Comment by krystian3w** [comment]
Jak coś to dodatek ma niby minimalną funkcjonalność AdBlocka:
- blokuje pliki sieciowe
- próbuje CSS-em nanosić filtry kosmetyczne

więc ma w sobie listę sprzed około miesiąca.

**Comment by seba2282** [comment]
Czyli w takim razie co? Zrezygnować z kiboke? To czym blokować te EU Rodo?

**Comment by krystian3w** [comment]
Rezygnacja z filtrów/dodatku Kiboke spowoduje, że trzeba by dodać z kilkaset nowych filtrów:

- ogólne blokujące
- ogólne ukrywające

**Comment by seba2282** [comment]
> Rezygnacja z filtrów/dodatku Kiboke spowoduje, że trzeba by dodać z kilkaset nowych filtrów:
> 
> * ogólne blokujące
> * ogólne ukrywające

I tu zmierzamy do tego, Że zgoda ciasteczkowa, która jest częściej aktualizowana przez team PL niż I don't care about cookies przez Kiboke, nie radzi sobie z EU.

**Comment by krystian3w** [comment]
> Że zgoda ciasteczkowa, (...) , nie radzi sobie z EU.

Nie radzi, bo ona jest jak w uBO nie da się naprawić skrypletem, html filteringiem lub `:style()` (czyt. "CSS-em"). 

Tam dodajemy tylko gdy bez zaakceptowania pop-upa nie działa np.:
*  wideo lub widać,
lub że pop-up miga co odświeżanie strony np.:
* kiedyś `visionexpress` lub obecnie `hrkgame.com` i nie ma opcji by uBO szybciej ukrywał ten pop-up.

**Comment by seba2282** [comment]
> > Że zgoda ciasteczkowa, (...) , nie radzi sobie z EU.
> 
> Nie radzi, bo ono jest jak w uBO nie da się naprawić skrypletem, html filteringiem lub `:style()` (czyt. "CSS-em").
> 
> Tam dodajemy tylko gdy bez zaakceptowania pop-upa nie działa np.:
> 
> * wideo lub widać,
> 
> lub że pop-up miga co odświeżanie strony np.:
> 
> * kiedyś `visionexpress` lub obecnie `hrkgame.com` i nie ma opcji by uBO szybciej ukrywał ten pop-up.

To w takim razie dodatek Kiboke jest tylko atrapą, co niby działa, a tak na prawdę większość EU zdejmują filtry do ublock origin / adguard?

**Comment by krystian3w** [comment]
Nie, myślałem że ty uważasz, że PCZ powinna działać identycznie jak IDCAC (czyli nie trzeba nic dodawać do uBO / AdGuard jako dodatkową listę).

**Comment by seba2282** [comment]
> Nie, myślałem że ty uważasz, że PCZ powinna działać identycznie jak IDCAC (czyli nie trzeba nic dodawać do uBO / AdGuard jako dodatkową listę).

Nie uważałem tak, ale widzę jak sobie filtry radzą i dlatego pytam o te tematy. Wybacz moją ciekawość.

**Comment by krystian3w** [comment]
Może problem jest w tym, że on sam to ogarnia niby cudem jakoś do kodu dopuszcza Krzyśka z Norwegi (ten od listy "Norydyckie filtry") i jeszcze ma jakieś 4 dodatki (które utrzymuje):

https://www.kiboke-studio.hr/browser-extensions/

**Comment by seba2282** [comment]
A gdyby osoby tworzące filtry w całej UE dodawały ukrywanie cookies, to nie byłoby problemów. Tak sądzę. Filtry mają za zadanie to ściągać ze stron.

**Comment by krystian3w** [comment]
Polityka EasyList zabrania tego, część projektów regionalnych ma w nazwie EasyList i państwo.

Jedynie chyba lista Czesko-Słowacka by mogła sobie tak robić (niby naprawiają anty-adblocki a projekty EasyList nie powinny), bo hebrajska EasyList niby już zaleca pchać to do listy elementów irytujących typu "Fanboy Annoyances" / "uBlock - Annoyances".

**Comment by seba2282** [comment]
@krystian3w Dobrze wiedzieć :)
