### ISSUE TITLE
Adguard tryb niewidzialnosci

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#18748]
Hej napiszę tutaj bo po angielsku trudno mi sie pisze a tłumacz często tłumaczy jak chce Xd

słuchajcie jak mam włączoną opcje niewidzialności w adguard for win nie mozna sie do mnie dodzwonić np na facebooku a jak ja dzwonie to sie połącze ale nie słysze 2 strony pytanie czy to jest przewidziany efekt uboczny czy to jest błąd ktory należy zgłosic jesli to jest poprawna reakcja to ktora z opcji w tej zakładce może to powodować? :)

**Comment by krystian3w** [comment]
Ty masz jakąś za mocną konfiguracje trybu niewidzialności, cofnij ją do domyślnych ustawień i wtedy nowy test połączeń na Facebooku.

Jak sam coś zmieniasz na bardziej restrykcyjne to jest to raczej twoja wina - np.:
- ustawiasz usuwanie cookies zewnętrznych po "0 min" a AdGuard wymusił 48-72h.
- ustawiasz bardzo krótki czas dla pierwszoplanowych cookies (first party cookies) gdzie AdGuard nie poleca opcji "włączać" a czas ustawił na 48-72h.

Jak się upszesz to może AdGuard team wyłączy całkowicie działanie StealthMode na Facebooku takim czymś:
```
@@||facebook.com^$stealth
@@||messenger.com^$stealth
@@||instagram.com^$stealth
```

ze szkodzą dla całej reszty użytkowników AdGuard jak sobie chwalili opcje.

**Comment by gzenio22** [comment]
@krystian3w tyle ze ja te opcje ktorych adguard nie zaleca mam po odznaczane :) nie modyfikowalem nic jade na fabrycznych poza odznaczeniem opcji wykrywania danego języka list Xd

**Comment by krystian3w** [comment]
to zobacz czy pomaga ci:

`@@||facebook.com^$stealth`

Bo to może być błąd blokady `WebRTC` wtedy AdGuard  zaleca rezygnacje z tej funkcji, bo trzeba by setki IPv4 / IPv6 facebooka dodać na listę wyjątków (np. co około miesiąc możesz odczuwać, że znowu nie działa dzwonienie lub nie słyszycie się).

**Comment by gzenio22** [comment]
nie mam teraz z kim sprawdzic Xdd

**Comment by gzenio22** [comment]
chyba jest git
