### ISSUE TITLE
fotouslugi.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18744]
( buttons )

**Comment by seba2282** [comment]
`www.fotouslugi.pl###cewe-sidebar-BBB5E27B18D8494BA35ACD10E867CF00`

`www.fotouslugi.pl###cewe-sidebar-58F56BA140FE43ADAAE6EC7000F5BB14`

`www.fotouslugi.pl###cewe-sidebar-F01601B899054451BBC624EB3D06CDD5`

`www.fotouslugi.pl##.cewe-footer-bottom`
