### ISSUE TITLE
outlabsklep.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18742]
fb ( button )

**Comment by seba2282** [comment]
FB: 
`outlabsklep.pl###widget_shop8`

opineo.pl:
`outlabsklep.pl##[href="http://www.opineo.pl/opinie/outlabsklep-pl"]`

VISA i coś jeszcze bankowego, co nie chce się załadować normalnie:
`outlabsklep.pl##.col-md-offset-1.col-md-5.col-sm-12.col-xs-24`
