### ISSUE TITLE
proservicegliwice.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18740]
( na dole )

**Comment by seba2282** [comment]
`www.proservicegliwice.com##._3MMC_`

**Comment by seba2282** [comment]
Tutaj reguły na ukrycie "partnerzy" : 

`www.proservicegliwice.com###ContainermainPage > div > div > ._1Z_nJ`

`www.proservicegliwice.com###j3d5oc72`

`www.proservicegliwice.com###WPht1-68t`

`www.proservicegliwice.com###i2spc30s`

`www.proservicegliwice.com###iwxd0tqp`

`www.proservicegliwice.com###WPht0-mv7`
