### ISSUE TITLE
inwestinfo.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#18751]
https://www.inwestinfo.pl/notowania-na-swiecie/notowania-obligacji-na-swiecie/
![Zrzut ekranu z 2021-02-22 20-09-10](https://user-images.githubusercontent.com/36385327/108757304-f47fa300-7549-11eb-9ca4-32884e3ce030.png)

**Comment by seba2282** [comment]
`www.inwestinfo.pl##div > div > .container`

**Comment by krystian3w** [comment]
`##body > div > div[style*="position"][style*="fixed"]:not([id]):not([class])`
