### ISSUE TITLE
teleshow.wp.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1875]
Tylko u mnie wyświetla się tylko część strony?
Link - `http://teleshow.wp.pl/`
Tak samo mam na - `http://facet.wp.pl/` i na `http://gwiazdy.wp.pl/`

Chyba trzeba poprawić tę regułę - `/^(http|https):\/\/[a-z]{1,20}\.wp\.pl\/.{200,}/$script,important,domain=facet.wp.pl|gwiazdy.wp.pl|teleshow.wp.pl`

na przykład na taką:
`/^(http|https):\/\/[a-z]{1,20}\.wp\.pl\/.{250,}/$script,important,domain=facet.wp.pl|gwiazdy.wp.pl|teleshow.wp.pl`

**Comment by xxcriticxx** [comment]
@F4z ja dalej mam czesc strony z nowa regula

**Comment by F4z** [comment]
@xxcriticxx ale sprawdzałeś z wyłączoną polską listą, czy po prostu dodałeś tę regułę?

**Comment by MajkiIT** [comment]
@F4z Jest git. Dzięki
