### ISSUE TITLE
Filmweb.pl - sekcja program tv i program tv (play now) jak ukryć ?

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#18752]
Tak jak w tytule. Filmweb.pl - sekcja program tv i program tv (play now) jak ukryć ?
Ublock Origin co prawda blokuje przekierowanie jako pro gemius, ale mi chodzi o ukrycie (wyłączenie tego button z menu program tv.

**Comment by xMaap** [comment]
Tutaj też można ukryć Play Now, bo i tak jest blokowane przekierowanie
https://www.filmweb.pl/serials
![Zrzut ekranu z 2021-02-22 22-11-30](https://user-images.githubusercontent.com/36385327/108770712-eede8900-755a-11eb-8c5d-6567bac825f8.png)
![Zrzut ekranu z 2021-02-22 22-12-41](https://user-images.githubusercontent.com/36385327/108770822-19304680-755b-11eb-83ed-4c86b156d833.png)

Canal+ https://www.filmweb.pl/zostanwdomu
![Zrzut ekranu z 2021-02-22 22-13-21](https://user-images.githubusercontent.com/36385327/108770941-3e24b980-755b-11eb-8c7a-a0209124de5d.png)

Jeszcze Canal+
![Zrzut ekranu z 2021-02-22 22-16-57](https://user-images.githubusercontent.com/36385327/108771329-cb680e00-755b-11eb-80b1-abda0a0a038d.png)

Sekcja Filmy i Seriale
![Zrzut ekranu z 2021-02-22 22-19-09](https://user-images.githubusercontent.com/36385327/108771516-13873080-755c-11eb-9398-170e687faf60.png)

Sekcja Rankingi
![Zrzut ekranu z 2021-02-22 22-20-43](https://user-images.githubusercontent.com/36385327/108771696-4df0cd80-755c-11eb-9c3a-af46fa9fb4ad.png)

Sekcja Program TV
![Zrzut ekranu z 2021-02-22 22-22-05](https://user-images.githubusercontent.com/36385327/108771830-75479a80-755c-11eb-955e-050482480eee.png)

**Comment by seba2282** [comment]
Jeden Canal+ ukryłem we filtrze nad którym pracuję na bieżąco. Ma trochę restrykcyjne reguły. I wojuję nad tym play now, kiedy rozwiniesz na górze program TV, to masz poniżej do play now i jest przekierowanie zablokowane przez ubo. A tak z ciekawości, ktoś patrzył na mój filtr? I co sądzicie o nim?

**Comment by seba2282** [comment]
@xxcriticxx @krystian3w @MajkiIT @hawkeye116477 @blocker999 i pozostali możecie pomóc? Z tym canal plus i play now? 
Aktualnie mam takie reguły:

`www.filmweb.pl##.facebookLoginButton__link`

`www.filmweb.pl##.FacebookLoginButton.facebookLoginButton`

`www.filmweb.pl##.authButton--google.authButton.authPage__button`

`www.filmweb.pl###canalPlusDesktopLink > .item-title`

`www.filmweb.pl##.floatingActionBox__button--visible.floatingActionBox__button`

`www.filmweb.pl##.FilmActionBox.filmActionBox`

A interesuje mnie zablokowanie tego całego sponsoringu, co pokazuje @xMaap

**Comment by krystian3w** [comment]
Ja tam mam popsuty scroll w zakołace `/serials` ("Seriale").

**Comment by krystian3w** [comment]
Dodatkowo coś psuje odtwarzacz zwiastunów na filmwebie:

https://www.filmweb.pl/video/Zwiastun/Gambit+kr%C3%B3lowej+Zwiastun+nr+1+polski-55194 - bez tego filtru się ciężko włącza (trzeba by używać dodatku "szybkość odtwarzania"):

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/dc031e70793c052bb942602c91a55d8c893c3ef0/PPB/inne.txt#L260

**Comment by seba2282** [comment]
@krystian3w Te elementy leżą po różnych sekcjach. Np dwa leżą we wszystkich, ale oznaczone jako a class= "menuPromoExtra coś tam" i nie wiem jak to zablokować. Mało tego po kliknięciu UBO blokuje jako smartserver i pro hit gemius. I nie mogę zlokalizować gdzie osadzony jest ten promo play now w kodzie strony.

**Comment by krystian3w** [comment]
Wtedy sugerowałbym używać opcji zbadaj element zamiast element pickera.

Z brzydkich animowanych menu kojarzę tylko iTunes/Apple music, gdzie trzeba było symulować kliknięcie, bo element wyparowywał z kodu strony "dynamicznie".

**Comment by seba2282** [comment]
Skoro mówisz, spróbuję tego, @krystian3w

**Comment by seba2282** [comment]
<a class="menuPromoExtra menuPromoCanalPlus menuCanalPlusFilms" href="https://pro.hit.gemius.pl/hitredir?id=.KtArbS4a2t3caNx6E27asSZDfXyF_d4HMDEcK4J.nb.v7&amp;et=action&amp;extra=canalPlus_mainMenu_click=desktop_film&amp;url=https://www.filmweb.pl/canalplus"> Poznaj nowości od CANAL+ </a>

<a class="menuPromoExtra menuPromoFilmwebAwards menuFilmwebAwardsFilms" href="https://www3.smartadserver.com/h/cc?imgid=26312157&amp;tmstp=[timestamp]&amp;tgt=[reference]"> Nagrody Filmwebu 2021 </a>

To zlokalizowałem i to jest w różnych sekcjach menu. Nadal tylko filmweb skutecznie ukrywa promo z play now w rankingach i program tv.

**Comment by MajkiIT** [comment]
@seba2282 widzę, że każdy z tych elementów ma podpięty link do hit.gemius.pl

**Comment by krystian3w** [comment]
Lub `smartadserver`.

I niby przydałoby się coś lepszego na tę 30-45 sekundową pełnoekranową reklamę.

**Comment by seba2282** [comment]
> @seba2282 widzę, że każdy z tych elementów ma podpięty link do hit.gemius.pl

I linki są blokowane po kliknięciu. Mnie interesuje po ukrywanie/usunięcie tych buttonów, żeby nie były widoczne. Wiesz jak się do tego dobrać? 

@xMaap pokazał te elementy na screenach. Udało mi się wstępnie ukryć vsocial + ten canal plus na liście przycisków na górze na wysokości gdzie masz seriale, ranking, mój Filmweb, obok był canal plus jako osobny button.

**Comment by seba2282** [comment]
> Lub `smartadserver`.
> 
> I niby przydałoby się coś lepszego na tę 30-45 sekundową pełnoekranową reklamę.

Nadal jest reklama w playerze? Bo nie przeglądałem jeszcze odtwarzania.

**Comment by MajkiIT** [comment]
@krystian3w no ja nie mam niestety tej reklamy pełnoekranowej. Jakaś specyficzna przeglądarka ?

**Comment by krystian3w** [comment]
W Firefox 86 było wczoraj.

Niby można by dać:

```
filmweb.pl##body:not([class]):style(overflow: auto !important;)
```

Ale bardziej mi chodzi, czy to nie wymaga dopuszczeń w ABP/AdBlock (czyli jak ktoś chce to może próbować zgłaszać do projektu Anti-CV https://github.com/abp-filters/abp-filters-anti-cv czy dadzą radę kiedyś zablokować `snippetem js`), bo taki bug może sprawić że uciekną z filmweb i sprawdzą kolejny wynik z wyszukiwarki i tyle.

**Comment by seba2282** [comment]
> filmweb.pl##body:not([class]):style(overflow: auto !important;)

Nie wiem co ta reguła robi do końca, ale wyłączyłem na chwilę filtr, co stworzyłem do testu bez reguł, co zamieściłem wewnątrz i widzę, ta reguła nic nie blokuje na filmweb @krystian3w

**Comment by krystian3w** [comment]
Bo ona ma naprawiać brak przewijania jak przy pierwszej wizycie zładuje się częściowo pełnoekranowa reklama wideo (30-45 sekund).

**Comment by seba2282** [comment]
'filmweb.pl##body:not([class]):style(overflow: auto !important;)'

Dodana do filtra.

Ale co dalej? Nadal zostają te elementy, co pokazał @xMaap

**Comment by krystian3w** [comment]
Może... `##[class*="menupromoextra" i]`

szuka wszystkich elementów co mają w klasie tekst `menupromoextra` w dowolnym rozmiarze znaków czyli nawet wersji pokemon: "`MeNuPrOmOeXtRa`".

**Comment by seba2282** [comment]
@krystian3w Promo poszły w długą. Zostaje teraz tylko play now zakładka program tv. Coś, co wywali całkiem play now znaczy się ukryje?

**Comment by seba2282** [comment]
![filmweb](https://user-images.githubusercontent.com/16944478/109193224-706f2a80-7798-11eb-9376-b5b7103c6434.png)
![filmweb1](https://user-images.githubusercontent.com/16944478/109193233-7238ee00-7798-11eb-8e0d-d1e90d9012cc.png)

Widzę, że jest użyte w kodzie "==0" Więc domniemam, że ma atrybut "hidden"?

Jak te dwa rozgryść i zablokować? @krystian3w @MajkiIT

**Comment by krystian3w** [comment]
ślepa uliczka `==0` to oznaczenie aktywnego elementu jakby kolorowanie tła miało być zbyt mało kontrastowe (np. ślepota barw).

**Comment by seba2282** [comment]
No i teraz wszystko jasne dla mnie, @krystian3w. Ale cały czas pozostaje jak się pozbyć tych "play now". One też mają podpięte "pro hit gemiusy".

**Comment by krystian3w** [comment]
jak nie boisz się powrotu plansz anty-adblock to może:

`filmweb.pl##a[href*="pro.hit.gemius.pl/"], a[href*="smartadserver"]`

przy czym na Interii Olegwukr wycofał usuwanie linków Gemius, bo namiętnie dawna interia tak oznaczała posty "zobacz również" jakie są czasem w połowie artykułu.

**Comment by seba2282** [comment]
I wtedy do Bogachenko o regułę anty Adblock kill? Sprawdzę eksperymentalnie regułę wyłączając najpierw filtr do którego wrzucam reguły. I na serio Olegwukr nie może nic z tym zrobić?

**Comment by seba2282** [comment]
Nie mam anty adblock. Ale teraz reguła, która umożliwi działanie playerów na Filmweb i powinno być wszystko w porządku. nawet wszelkie śmieci poznikały.

**Comment by seba2282** [comment]
Po dodaniu 

`filmweb.pl##a[href*="pro.hit.gemius.pl/"], a[href*="smartadserver"]`

+ 

`filmweb.pl##.vjs-preloading.vjs-inactive.video-js:after`

Odtwarzanie działa, aczkolwiek nie ma przycisków start, pause, itp w odtwarzaczu.

**Comment by krystian3w** [comment]
Receptą na odtwarzacz zwiastunów powinna być aktualizacja listy Kiboke/dezaktywacja dodatku IDCAC na filmweb aż nie będzie wersji 3.2.9 i Polskiej Rodo-Ciasteczkowej - problem robi blokada `sdk.privacy-center.org`.

Ja nie zalecam używania `EasyList Cookie List`, bo czasem naprawiają coś 2 miesiące albo wcale z racji. że filtr mimo że `obusieczny` to nie mogą wycofać (są chyba takie trzy kosmetyczne) - a ma podobny filtr jaki Kiboke dezaktywował dla filmweb.

**Comment by seba2282** [comment]
> Ja nie zalecam używania `EasyList Cookie List`, bo czasem naprawiają coś 2 miesiące albo wcale z racji. że filtr mimo że `obusieczny` to nie mogą wycofać (są chyba takie trzy kosmetyczne) - a ma podobny filtr jaki Kiboke dezaktywował dla filmweb.

Tylko, że po wyłączeniu easy cookie list, jest ten sam problem.

**Comment by seba2282** [comment]
> Po dodaniu
> 
> `filmweb.pl##a[href*="pro.hit.gemius.pl/"], a[href*="smartadserver"]`
> 
> 
> `filmweb.pl##.vjs-preloading.vjs-inactive.video-js:after`
> 
> Odtwarzanie działa, aczkolwiek nie ma przycisków start, pause, itp w odtwarzaczu. @krystian3w masz recepturę na to też?

@MajkiIT potrzebny fix na widzenie przycisków odtwarzania, itp. (start, pause, pasek stanu, żeby wiedzieć, ile jest obejrzanego wideo). Masz pomysł?

**Comment by krystian3w** [comment]
To sprawdź po dezaktywacji dodatku IDCAC jak używasz.

W loggerze uBO / AdGuard rób filtrowanie `privacy-center.org`, bo być może jakaś lista blokuje filtr z przełącznikiem `$important` / `,important`  na chybił trafił może Szwedzi tak zablokowali i kilka szwedzkich domen naprawili.

A ten stary filtr: `filmweb.pl##.vjs-preloading.vjs-inactive.video-js:after` to tylko półśrodek, bo ktoś może nie wiedzieć że `poster` jest filmem a nie zwykłą grafiką:

informacja co to poster - https://www.w3schools.com/tags/att_video_poster.asp

**Comment by seba2282** [comment]
||privacy-center.org^$3p
Lista filtrów
AdGuard Annoyances 
Fanboy’s Annoyance 
EasyList Cookie 
Kontekst
www.filmweb.pl
Lokalność
(3) filmweb.pl ⇒ privacy-center.org
Typ
script

I mamy winowajców.

**Comment by krystian3w** [comment]
Ale ten filtr ma słabą moc:

`||privacy-center.org^$3p`, nie ma `important` to dopuszczenie go dezaktywuje: https://github.com/MajkiIT/polish-ads-filter/blob/a12c5d9ba79b4e305d2db3cbf7f8fd0cfaebe462/cookies_filters/adblock_cookies.txt#L3621

Możliwe, że twój zestaw aktywnych filtrów `regionalnych`/list `hosts`/Fanboy's Enhanced Tracking List coś psuje.

**Comment by seba2282** [comment]
Jak dać fixa? Bez fanboy enhanced tracking list mam to samo.

**Comment by seba2282** [comment]
Wyłączam kolejno filtry (mój jest wyłączony cały czas do testów) i mam to samo.

**Comment by seba2282** [comment]
Macie może już pomysł na te kontrolki przy playerach? Cały czas ich nie mam. Kiedy włączę jaki kolwiek zwiastun.

**Comment by krystian3w** [comment]
To już jest dawno naprawione, nawet w liście Kibokiego:

```
sdk.privacy-center.org$domain=~lequipe.fr|~marianne.net|~allocine.fr|~standaard.be|~dziennikzachodni.pl|~naszemiasto.pl|~telegraaf.nl|~gamepro.de|~gamestar.de|~dumpert.nl|~funradio.fr|~rtl.fr|~mundodeportivo.com|~franceinter.fr|~filmweb.pl|~franceculture.fr|~gofeminin.de|~onmeda.de
```

Jak widzisz jego filtr już nie blokuje domeny znanej z zarządzania plikami cookies by było to zgodne z "RODO".

Nawet "Rayanbr" 🇳🇿 poprawił listę EasyList Cookie List by ona nie blokowała tak mocno domeny `privacy-center.org`.

**Comment by seba2282** [comment]
Rodo nie widzę, ale dzisiaj rano włączyłem Filmweb i cały czas brak kontrolek. Kiedy to zostało naprawione?

**Comment by krystian3w** [comment]
W listach na usuwanie pop-up/pasków cookies+rodo z około tydzień temu a Fanboy w sobotę będzie miał "tygodnicę":

https://github.com/easylist/easylist/commit/139e830cb36c99d2c1fb13f3aa2491c4a8447ba1

**Comment by seba2282** [comment]
To znaczy, że można już wywalić tą połowiczną regułę na preloading video, co ją podałeś? @krystian3w

**Comment by krystian3w** [comment]
Tak, bo już nie powinno być elementu `.player-inactive`.

Błąd z brakiem paska i działania play/pause może robi się też bez aktywacji blokady reklam - wtedy nie naprawisz tego inaczej jak czymś takim:

https://addons.mozilla.org/pl/firefox/addon/html5-video-everywhere-next/ - ale ten dodatek działał w zakresie kilku domen i niby witryny są tak uaktualnione, że tam już on nie działa.

**Comment by seba2282** [comment]
> Tak, bo już nie powinno być elementu `.player-inactive`.

Wywaliłem już tą regułę.

**Comment by seba2282** [comment]
> Tak, bo już nie powinno być elementu `.player-inactive`.
> 
> Błąd z brakiem paska i działania play/pause może robi się też bez aktywacji blokady reklam - wtedy nie naprawisz tego inaczej jak czymś takim:
> 
> https://addons.mozilla.org/pl/firefox/addon/html5-video-everywhere-next/ - ale ten dodatek działał w zakresie kilku domen i niby witryny są tak uaktualnione, że tam już on nie działa.


Później to sprawdzę, @krystian3w

**Comment by krystian3w** [comment]
Możliwe przyczyny:

- agresywny DNS blokujący za dużo trackingu/reklam
- podobne agresywne reguły skopiowane do pliku host lub zapory systemu Windows
- twój dostawca internetowy ma problemy z infrastrukturą sieciową i nie może od kilku dni zapewnić stabilnego połączenia z filmweb

**Comment by seba2282** [comment]
@krystian3w Wątpię, aby były problemy u UPC. Mam stabilne połączenie. Coś jest w tych przeglądarkach bazujących na chromium. Stabilność jest, DNS host nie dogrywałem do zapory systemu (Windows 10 na domyślnym, jeżeli chodzi o zaporę). Ale zastanawia mnie, dlaczego bez blokowania nie działa, a z blokowaniem ubo + rule preloading, odtwarzacz działa, ale brak kontrolek. Wina leży po stronie filmweb moim zdaniem.

**Comment by seba2282** [comment]
Naprawili playery. Nie możliwe.

**Comment by krystian3w** [comment]
Opcjonalnie Majkiit naprawił zezwalając na tracking pliku google `/ima3.js`.  Artykuły z wideo zaczęły wymagać ładowania tego jak domeny `privacy-center.org` w zwiastunach.

**Comment by seba2282** [comment]
@krystian3w A co z tą regułą reloading, bo cały czas ją mam?

**Comment by seba2282** [comment]
Poprawiliście tutaj, a i tak canal + jest widoczny na Filmweb w menu.

**Comment by krystian3w** [comment]
Kto coś poprawiał?

**Comment by seba2282** [comment]
Nie widzę już tych promo play now i tego drugiego, po wyłączeniu mojego filtru, więc dodaliście reguły.
