### ISSUE TITLE
allegro.pl (Safari + Adguard)

### ISSUE THREAD

**Issue by maciejtarmas** [MajkiIT/polish-ads-filter#18758]
### Zrzut ekranu 
<img width="1292" alt="Screen Shot 2021-02-23 at 21 53 36" src="https://user-images.githubusercontent.com/3435387/108906812-9920e400-7621-11eb-8739-120f59d1df1d.png">

### Link bezpośredni 
https://allegro.pl/listing?string=anker&bmatch=cl-e2101-d3685-c3683-ele-1-2-0218

### Co trzeba zrobić, aby pojawił się błąd?
1. Wejść w listing ofert albo w samą ofertę przez Safari z Adguardem

### Moja konfiguracja 

**Przeglądarka internetowa:** Safari (macOS/iOS)

**Rozszerzenia i skrypty:** 
Adguard for Safari

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Inne, ale to bez znaczenia

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Poniższa reguła blokuje zaciąganie obrazów z a.allegroimg.com, co powoduje niewyświetlanie się obrazów na liście ofert i w samej ofercie:

`||a.a^`

Problem dotyczy tylko Adguarda dla Safari. Testowane pod iOS i macOS. Wersja dla FF działa prawidłowo.

**Comment by seba2282** [comment]
Tak się zastanawiam, ale jest napisane "problem tylko z safari i adguard". Czy to nie powinno pójść do teamu adguard dla fix ich produktów (wtyczki także)? 

@AdamWr możesz spojrzeć w ten temat?

**Comment by maciejtarmas** [comment]
Właśnie się zastanawiam, dlaczego tylko pod Safari to wyłazi, bo reguła jest napisana tak jak powinna być, czyli powinna wycinać wszystkie adresy zaczynające się na „a.a”.

Tymczasem ani uBlock Origin ani AdGuard pod Firefoksem nie wycinają domeny a.allegroimg.com, choć chyba powinny.

No i pytanie co ta reguła w ogóle miała wyciąć.

**Comment by seba2282** [comment]
@maciejtarmas ja myślę, że wina jest po stronie AG wtedy. I to by trzeba im zgłosić. Ale @AdamWr coś może powiedzieć na temat tego problemu czy to po ich stronie.

**Comment by AdamWr** [comment]
Co prawda nie potrafię odtworzyć tego bezpośrednio na `allegro.pl`, ale po wejściu w obrazek widzę, że strona jest zablokowana.
Wygląda to na błąd, więc zgłosiłem to w odpowiednim miejscu.
Jako tymczasowe rozwiązanie możesz dodać `||a.a^$badfilter` do reguł użytkownika.

Odnośnie samej reguły, to z tego co rozumiem, ona powinna blokować tylko stronę typu `a.a` (`a.allegroimg.com` nie powinno być blokowane), ale wydaje mi się, że taki adres jest nieprawidłowy, więc szczerze mówiąc nie wiem dlaczego ta reguła została dodana :)

**Comment by krystian3w** [comment]
Raczej powinno się używać modelu "konsultacja z twórcami list", jak się nie da dogadać to naprawa badfilterami lub w FiltersRegistry.

**Comment by maciejtarmas** [comment]
OK, doczytałem sobie i faktycznie to powinno blokować tylko domenę a.a, tak więc sama reguła wydaje się być bez sensu, dlatego wnioskuję o jej wywalenie :)

Z drugiej strony wyszedł tez najwyraźniej bug w AdGuardzie dla Safari przy parsowaniu standardowych reguł na te zrozumiałe dla Safari, bo oczywiście Apple musi mieć to po swojemu. Wieczorem przysiądę do komputera i im to zgłoszę w odpowiednim repozytorium.

**Comment by krystian3w** [comment]
Wystarczy to zasubskrybować: https://github.com/AdguardTeam/AdGuardForSafari/issues/537

**Comment by maciejtarmas** [comment]
Jest git, dzięki :)
