### ISSUE TITLE
tuba.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1876]
ad block 

http://fm.tuba.pl/play/39/2/radio-tuba-top-hits

![capture](https://cloud.githubusercontent.com/assets/15007183/21651737/d22f4612-d277-11e6-9f8b-912fc9628e88.PNG)

**Comment by F4z** [comment]
`@@||fm.tuba.pl/banner/banery/750x100.php$xmlhttprequest,domain=fm.tuba.pl`
albo ogólniej
`@@||fm.tuba.pl^$xmlhttprequest,domain=fm.tuba.pl`

**Comment by xxcriticxx** [comment]
@F4z ja lubie ogolniej dziala super :)

**Comment by MajkiIT** [comment]
@F4z dzięki
