### ISSUE TITLE
majkiit.github.io

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#18760]
Opcja subskrybcji list po kliknieciu subskrybuj w prawym górnym rogu zamiast wymusić subskrybcje listy przez ublocka przekierowuje mnie do zawartości listy w formie tekstowej 

W skrócie nie da sie zasubskrybować wybranej listy na klik jak kiedyś dzieje sie tak na Ubo z kolei adguarda wymusza poprawnie

Ogarniam to znajomemu sam używam adguarda tak czy siak

**Comment by xxcriticxx** [comment]
cc @MajkiIT / cc @hawkeye116477

**Comment by krystian3w** [comment]
Tak ma działać = **zasubskrybowana** uruchamia automatycznie podgląd jej stanu/wersji w uBO.

Nieposiadana generuje żółty pasek z subskrybuj w prawym rogu:

![Przechwytywanie](https://user-images.githubusercontent.com/35370833/109002093-09714900-76a6-11eb-8b5a-eabea883a827.PNG)
