### ISSUE TITLE
harderfit.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18779]
( u góry )

**Comment by seba2282** [comment]
Na górze:

`||harderfit.eu/wp-content/uploads/20*.png$image`

+ Pozostałe:

`harderfit.eu##.et_pb_gutters2.et_pb_equal_columns.et_pb_row_14.et_pb_row`

`harderfit.eu##.et-last-child.et_pb_column_inner_1.et_pb_column_inner.et_pb_column_1_3.et_pb_column`

`harder.perfectgym.pl##.auth-form-social`

**Comment by krystian3w** [comment]
`||harderfit.eu/wp-content/uploads/20*.png$image` za dużo może blokować.

podpowiedź nie może zwalniać z myślenia.

**Comment by seba2282** [comment]
`harderfit.eu##.et_pb_bg_layout_light.et_pb_text_align_left.et_pb_text_39.et_pb_text.et_pb_module > .et_pb_text_inner > p`

`harderfit.eu##.et_pb_bg_layout_light.et_pb_text_align_left.et_pb_text_40.et_pb_text.et_pb_module > .et_pb_text_inner > p`

`harderfit.eu##.et_pb_bg_layout_light.et_pb_text_align_left.et_pb_text_41.et_pb_text.et_pb_module > .et_pb_text_inner > p`

`harderfit.eu##.et_pb_row_7.et_pb_row`

`harderfit.eu##.et_pb_row_8.et_pb_row`

`harderfit.eu###menu-item-214 > [href="https://web.facebook.com/harderpolska/"]`

`harderfit.eu###menu-item-216 > [href="https://www.instagram.com/harder_hiit/"]`

`harderfit.eu###menu-item-5194 > [href="https://www.linkedin.com/company/12624933/"]`


Albo masz lepszy pomysł? @krystian3w

**Comment by krystian3w** [comment]
To jest chyba to: https://github.com/MajkiIT/polish-ads-filter/issues/18800#issuecomment-787897718

czyli trudny szablon, gdzie bazujesz na dziwnym "ID" klasy np. `##.et_pb_text_40` lub preferowanej kolorystyce. Więc jak "ID" klasy się zmieni lub preferowane odcienie na np. zielone "wiosenne" to może filtr nic nie ukrywać.

**Comment by seba2282** [comment]
Trzeba znaleźć jakąś neutralną regułę i blokować wybrane elementy konkretnie. Żeby zmiany nie wpłynęły na filtr do blokowania i cały czas, żeby filtr działał. Pomysły? Jeżeli chodzi o word press, itp podobne, kiepsko ze znajomością u mnie.

**Comment by seba2282** [comment]
@krystian3w Na razie widzę, że wszystko blokuje jak należy znaczy po logach i na stronie - elementy ukryte.
