### ISSUE TITLE
leftlane.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#1877]
Informacja o Adblocku.

**Comment by xxcriticxx** [comment]
jeszcze 4 dni temu reeka lista tym sie zajmowala

**Comment by F4z** [comment]
Jakoś tak nie mogę znaleźć wspólnego punktu.
Dla uBlocka mogą być takie reguły, raczej działają i nie powinny za dużo ukrywać:
`leftlane.pl##[class*="clearfix grpelem"]:has(:scope > p[id] > span[id] + br + span[id])`
`leftlane.pl##[class*="clearfix grpelem"] > [class]:has(script[src="//81.2.255.5/adserver/www/delivery/asyncjs.php"])`
`leftlane.pl##[class*="clearfix grpelem"][data-content-guid]:has(script[src="//81.2.255.5/adserver/www/delivery/asyncjs.php"])`

Sprawdzałem na tych stronach:
<pre>
http://www.leftlane.pl/
http://www.leftlane.pl/lis16/ministerstwem-rozwoju-zainteresowane-arrinera-hussarya-bedzie-sukces.html
http://www.leftlane.pl/paz16/nowe-bmw-serii-5-g30-z-silnikami-o-mocach-190-462-km.html
http://www.leftlane.pl/sty17/faraday-future-ff-91-tak-wyglada-pogromca-tesli.html
http://www.leftlane.pl/sty17/nowa-skoda-octavia-rs-przyspiesza-do-100-kmh-w-6,7-s.html
http://www.leftlane.pl/wrz16/tesla-model-x-zawiozla-kierowce-z-zatorem-plucnym-do-szpitala-ale.html
http://www.leftlane.pl/paz16/traficar-nowa-alternatywa-dla-wlasnego-samochodu-taksowek-i-ubera.html
http://www.leftlane.pl/paz16/az-16-tys-kierowcow-uniknie-mandatu-z-fotoradaru.html
</pre>
ale jeśli gdzieś nadal jest jakiś komunikat o adblocku albo za dużo schowane, to proszę pisać :)
