### ISSUE TITLE
balex.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18785]
( u góry i na dole )

**Comment by seba2282** [comment]
`balex.eu##.facebook-ms.jm-module-raw`

`balex.eu##.youtube-ms.jm-module-raw`

`balex.eu##.number-ms.jm-module-raw`

`balex.eu##.hidden-phone.jm-testimonials.mod-327.jm-module`

`balex.eu###jm-footer > .container-fluid`

`balex.eu##.items-2.jmm-list`

`balex.eu##a.conf-thermano:nth-of-type(3)`
