### ISSUE TITLE
ksgornik.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18781]
( buttons i na środku )

**Comment by seba2282** [comment]
`ksgornik.eu##.ssb-anim-slide.ssb-disable-on-mobile.ssb-btns-right`

`ksgornik.eu##.slide.carousel`

`ksgornik.eu##div.col-md-3:nth-of-type(7)`

`ksgornik.eu##div.col-md-3:nth-of-type(6)`

`ksgornik.eu##div.col-md-3:nth-of-type(5)`

`ksgornik.eu##[src="http://ksgornik.eu/wp-content/themes/ksp/img/header-polkowice.png"]`

Buttony i różne promo.
