### ISSUE TITLE
besco.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18789]
( na dole )

**Comment by seba2282** [comment]
`www.besco.eu##.Axis-xs-cross-center.Row.Order-xs-1.Display-md-flex.Display-xs-none.Besco-MainNavigation-SocialMedia`

`www.besco.eu##.Cell-xl-5x.Cell-md-4x12.Cell-xs-12x12.Besco-BottomNavigation`

Na górze i na dole social.
