### ISSUE TITLE
ienergia.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18780]
( na dole )

**Comment by seba2282** [comment]
`ienergia.eu##div.col-sm-3:nth-of-type(4)`

**Comment by krystian3w** [comment]
`##div.col-sm-3:nth-of-type(4)` za dużo - może wycinać wiele czwartych kolumn, lepiej dodać jakiś "footer" jak stopka ma.

**Comment by seba2282** [comment]
Tylko, że footer wycina całość, a żeby zniwelować tą kolumnę, jest potrzebne z tym of type 4. Masz jakieś sugestie, @krystian3w

**Comment by krystian3w** [comment]
źle czytasz, o takie coś mi chodzi:

`ienergia.eu##footer div.col-sm-3:nth-of-type(4)`

wtedy mniej elementów ucierpi.

**Comment by seba2282** [comment]
Faktycznie podziałało
