### ISSUE TITLE
donashop.eu/pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18796]
fb ( u góry i na dole )

**Comment by seba2282** [comment]
`www.donashop.eu###contact-link > p > .facebook`

`www.donashop.eu##.facebook-info`

`www.donashop.eu##p:nth-of-type(4)`

`www.donashop.eu###platnosci`

`www.donashop.eu##.copyright.text-center`

`www.donashop.eu##.slide.carousel`
