### ISSUE TITLE
e-plytki.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18792]
( na dole )

**Comment by seba2282** [comment]
`e-plytki.eu##.container.userfooter > .in-view.box_custom.resetcss.box`

`e-plytki.eu##div:nth-of-type(6)`

**Comment by krystian3w** [comment]
`##div:nth-of-type(6)` może zacząć wycinać losowe elementy `div` co będą szóste w dowolnym miejscu.

**Comment by seba2282** [comment]
`##div:nth-of-type(6)` 

Tylko, że ta wycina tylko tą stronę sponsorowaną na dole, a dodanie footer div nie działa.

**Comment by krystian3w** [comment]
No to w takim razie może:

`e-plytki.eu#?#body > div:nth-of-type(6):-abp-has(> a:only-child)`

`-abp-has` znaczy, że to filtr proceduralny, sprawdzający istnienie linka w tym szóstym div-ie, może robić efekt migania jak będziesz odświeżać stronę jak dojechałeś do stopki.

Niby efektu migania nie będzie jak zaczniesz przewijanie na ekran wcześniej niż stopka.

**Comment by seba2282** [comment]
`e-plytki.eu#?#body > div:nth-of-type(6):-abp-has(> a:only-child)`

`e-plytki.eu##.container.userfooter > .in-view.box_custom.resetcss.box`

Ładniej wygląda bez luki. @krystian3w
