### ISSUE TITLE
sklep.maszynykrawieckie.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18793]
( na dole )

**Comment by seba2282** [comment]
`sklep.maszynykrawieckie.eu##.container > .row > .col-lg-3.col-md-3.col-sm-3.col-xs-12`

`sklep.maszynykrawieckie.eu##.text-muted.clearfix.copyright`

`sklep.maszynykrawieckie.eu##.panel-default.panel.box-info`

`sklep.maszynykrawieckie.eu###leaselinkSlideButton1`
