### ISSUE TITLE
taniefototapety.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18790]
G+ ( button )

**Comment by seba2282** [comment]
G button

`www.taniefototapety.eu##[href="https://plus.google.com/105765460150850902330"]`

Jakieś opinie poniżej przekierowujące na inną stronę 

`www.taniefototapety.eu##.opinions_badge`

Partnerzy

`www.taniefototapety.eu##.container.clearfix.n60972_main`

Newsletter 

`www.taniefototapety.eu##.mrg-b.col-sm-12.col-md-12`

Logowanie/rejestracja za pomocą social

`www.taniefototapety.eu###client_new_social`

**Comment by krystian3w** [comment]
newsletter ma unikalne ID `###menu_newsletter`

**Comment by seba2282** [comment]
`www.taniefototapety.eu##.sm-gplus`

`www.taniefototapety.eu###client_new_social`

`www.taniefototapety.eu##.container.clearfix.n60972_main`

`www.taniefototapety.eu##.ck_dsclr_v2.no_print`

Zaktualizowane reguły.
