### ISSUE TITLE
wbijam.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1879]
REKLAMY

`http://www.gintama.wbijam.pl/odcinki_specjalne-006.html`

`http://www.gintama.wbijam.pl/pierwsza_seria.html`

`http://www.gintama.wbijam.pl/odcinki_specjalne.html`

**Comment by xxcriticxx** [comment]
reklamy na filmach plus pop up ads chyba podam to do easylist 

`http://www.inne.wbijam.pl/fmab.html`

**Comment by F4z** [comment]
Do zablokowania reklam na stronie ta reguła powinna wystarczyć:
`||gintama.wbijam.pl/tempa/banery/$image`

Jeśli chodzi o reklamy na filmach i popupy, to możesz podać w których odtwarzaczach tak się dzieje?

Tutaj widzę popupy - `http://www.inne.wbijam.pl/wideo-vidfile-16-54q9s26376q1r-0-0-0.html`
Możesz sprawdzić te reguły?
`|http://$third-party,script,domain=vidfile.net`
`vidfile.net##script:inject(noeval.js)`

**Comment by xxcriticxx** [comment]
na `http://www.inne.wbijam.pl/wideo-fileone-16-58473nsp49059-0-0-0.html` sterowanie filmem obcina na dole 

![capture](https://cloud.githubusercontent.com/assets/15007183/21665125/c3815858-d2b8-11e6-8f34-b6116af8819c.PNG)

**Comment by xxcriticxx** [comment]
ok
