### ISSUE TITLE
dragon-survival.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18809]
( na dole )

**Comment by seba2282** [comment]
Dziwna reguła. Pierwszy raz się spotykam z obrazkami w takich rzeczach, ale autentycznie zablokowanie przez ublock origin tworzy taką regułę.

`dragon-survival.eu##div.ds-🙀.ds-🚂:nth-of-type(4)`

**Comment by krystian3w** [comment]
Google też używa emoji w nazwach klas CSS choćby tutaj:

`https://console.actions.google.com`
