### ISSUE TITLE
rejs.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18804]
yt ( na dole )

**Comment by seba2282** [comment]
+ Social

`www.rejs.eu##.social`

**Comment by krystian3w** [comment]
za dużo wytnie, logo drzewa to nie element społecznościowy:

![Imgur](https://i.imgur.com/aG4q2sK.png)

**Comment by seba2282** [comment]
@krystian3w tylko, że te drzewko po kliknięciu przeniosło mnie na FB. Za moment pomyśle, jak lepiej dopasować reguły. Ale dzięki za podpowiedzi.

**Comment by krystian3w** [comment]
Drzewko normalnie nie jest klikalne = to grafika bez linka.

**Comment by seba2282** [comment]
Gdzieś obok tego drzewka jest ukryty buttom FB i jak klikniesz, przenosi cię do fb. Ja kliknąłem w pewny punkt i przeniosło mnie. Nie mogę do końca z lokalizować gdzie to jest i podejrzewam, że jakiś fanboy albo Adguard ukrywa tylko, ale odnośnik jest aktywny. Wiem, bo z social drzewko znika, bez social znika to obok drzewka jako jedno. Więc - coś jest nie tak, bo social wywala social, więc nie powinno ruszyć drzewka.

**Comment by krystian3w** [comment]
Może link FB jest większy niż button.

**Comment by seba2282** [comment]
I właśnie tego próbuję się pozbyć. Znaczy tego ukrytego odnośnika FB po części w drzewku.

**Comment by krystian3w** [comment]
Tyle, że w drzewku nie jest on ukryty.

spróbuj np.:

```
##.social > a[href*=".com/"]
```

lub na dwa filtry blokować twitter i fb:

`##.fb-f, .yt-f`

Niby druga wersja miałaby szanse kiedyś być generycznym filtrem bez wypisanych domen.

**Comment by seba2282** [comment]
`rejs.eu##.social > a[href*=".com/"]`
