### ISSUE TITLE
sportowahurtownia.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18800]
fb ( button )

**Comment by seba2282** [comment]
FB button

`sportowahurtownia.eu##.hidden-sm.hidden-xs.align-right`

+ Kosmetyczne

`sportowahurtownia.eu##div.abs-footer-item-width-full:nth-of-type(2)`

`sportowahurtownia.eu##.abs-footer-bottom-text`

**Comment by krystian3w** [comment]
`##.hidden-sm.hidden-xs.align-right` wytnie wszystko co jest wyrównane do prawej i nie ma prawa być w layoucie mobilnym dla telefonów.

**Comment by seba2282** [comment]
@krystian3w Czy inne reguły są w porządku i tylko hidden do poprawki?

**Comment by krystian3w** [comment]
Pewnie w innych wątkach też by trzeba pomyśleć nad kwestiami na ile rozumiesz layout z klasami:

`.elementor-54e34-column > .elementor-45dce-list` (niby wtyczka do m.in. WordPress tak barwi strony)
`.td-column-warpper-x54w > .td-item-list-45xc`

Jak dla mnie to są dwa najgorsze potwory, jak przychodzi ukryć lekkim filtrem jakiś większy div w ich szablonie gdy padną te losowe cyferki.

**Comment by seba2282** [comment]
`sportowahurtownia.eu###facebookLabel`

Pozostałe dwie wyglądają na dobrze. Mógłbyś zobaczyć własnym okiem? @krystian3w
