### ISSUE TITLE
pepegi.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18808]
fb ( button i na dole )

**Comment by seba2282** [comment]
+ Social 

`pepegi.eu###client_new_social`

`pepegi.eu##.no_print.toplayerSpecialClass`

`pepegi.eu##div.col-xs-12.col-sm-6.col-md-3.menu_button_wrapper:nth-of-type(2)`


+ Newsletter

`pepegi.eu###toplayer_newsletter`

+ Partnerzy

`pepegi.eu##.clearfix.n60972_main`

**Comment by krystian3w** [comment]
`pepegi.eu###toplayer_newsletter` - zostawia kwadrat na środku w którym nie da się klikać.

**Comment by seba2282** [comment]
A i wszystko jasne. Macie niedociągnięcie tutaj i potrzebny fix (tak sądzę):

Filtr
###menu_newsletter:lang(pl)
Lista filtrów
Polskie Filtry Elementów Irytujących 
Kontekst
pepegi.eu
Typ
dom
Adres URL
https://pepegi.eu/

**Comment by krystian3w** [comment]
Raczej nie,  to sprawa indywidualna czy warto usuwać div nad ID `###menu_newsletter`

A `:lang(pl)` to zabezpieczenie przed psuciem się stron w innym języku niż polski lub stronie bez zdefiniowanego języka na jakimikolwiek sposób (np. atrybutem [lang] na tagu html/body).

**Comment by seba2282** [comment]
> Raczej nie,  to sprawa indywidualna czy warto usuwać div nad ID `###menu_newsletter`, jaką masz pewność, że tylko silnik sklepowy idoSell tego używa.
> 
> A `:lang(pl)` to zabezpieczenie przed psuciem się stron w innym języku niż polski lub stronie bez zdefiniowanego języka na jakimikolwiek sposób (np. atrybutem `[lang]` na tagu html/body, jakoś tagiem xml dla stron np. `xhtml5`).


Z tym idosell jest do ukrycia tej promowanej strony na dole. Mi ukryło i nie widać tego. Natomiast nie wiem jak się pozbyć pop up newsletter. Napisałem o tym w poście edytując.

**Comment by krystian3w** [comment]
Pop-up niby można wyciąć po tym dziwnym ID:

```
aba-sport.pl,autochemia.pl,awangardashoes.com,californiaskateshop.pl,damizabawki.pl,dowarsztatu.com,kupbuty.com,meskiegacie.pl,pepegi.eu,pomocna24.pl,portalokienny.pl,sportowybazar.pl,vitasport.pl###tws_i_0
```

Niby typowe dla pop-upów ze sklepów idoSell, jak strona ma więcej wygenerowanych to zdarzają się też:
```
tws_i_1
tws_i_2
tws_i_100000
tws_i_100001
```

I radziej mutacja z `_s_`, lub S znaczy tło/"overlay" pod pop-upem:
```
tws_s_0
tws_s_100001
```

**Comment by seba2282** [comment]
@krystian3w więc trzeba by znaleźć wspólną regułę, co wytnie wszystkie tws_i/s z numerami po nich. A zablokowanie całego "tws" czym skutkuje?

**Comment by krystian3w** [comment]
Niby zadziała:

`##div[id^="tws_i_"]`
`##div[io^="tws_s_"]`

Ale trzeba by patrzeć ile stron ma jeszcze pop-up (ze znanych w EI lub liście cookies) i ile ich jest informacyjnych, że sklep stacjonarny jest zamknięty/pracuje krócej/ile wynosi wysyłka (a wykluczenie wtedy wymagałoby zapisu `~sklep.xd##` i pewnie filtrem proceduralnym ukrywać tam pop-upy np. newsletterowe).

Druga trudność, to jaką literę mają widgety przypięte do boków ekranów, jakąś mają i w EI usunęliśmy ten filtr by nie wycinał przycisków social a tylko te do Allegro/Mapy Google/Portalu z Opiniami.

**Comment by seba2282** [comment]
Czyli następna strona wymaga przemyślenia. @krystian3w, a co jest w EI, to tylko guru wie. 😅😅😅😅😅😅😅😅😅😅😅😅😅

**Comment by seba2282** [comment]
> `##div[id^="tws_i_"]`
> `##div[io^="tws_s_"]`

Po dodaniu tych reguł, widzę w logach, że wszystko jest prawidłowo blokowane.
