### ISSUE TITLE
kostes.eu/pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18803]
( u góry )

**Comment by seba2282** [comment]
+Social

`kostes.eu##[src="https://kostes.eu/img/cms/001-instagram-logo.png"]`

`kostes.eu##[src="https://kostes.eu/img/cms/002-facebook-logo.png"]`

+Przekierowanie na jakąś stronę sponsr

`kostes.eu##div.row.salon:nth-of-type(4)`
