### ISSUE TITLE
sklep.regalia.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18827]

**Comment by seba2282** [comment]
@krystian3w ciasteczko cookie na tej stronie.

**Comment by krystian3w** [comment]
Przecież jest etykieta / label pod tytułem i po prawej...

**Comment by seba2282** [comment]
@krystian3w możesz dać do ciastek to? Cytuję RODO/cookie treść ze strony. 
 
"OD 25 MAJA OBOWIĄZUJĄ NOWE PRZEPISY O OCHRONIE DANYCH OSOBOWYCH.
W związku z tym przygotowaliśmy dla Ciebie niezbędne informacje, które znajdziesz tutaj:

Klauzula Informacyjna
Polityka Prywatności
Prawo do wycofania zgody na przetwarzanie danych osobowych
Dowiesz się, w jaki sposób przetwarzamy Twoje dane osobowe oraz jakie masz związane z tym prawa. Nie musisz przekazywać nam żadnych informacji ani żadnych Twoich danych osobowych, w tym hasła.

Jeśli chcesz zgodzić się na przetwarzanie przez Zaufanych Partnerów Regalia Polska Manufaktura Wojciech Sobierański Twoich danych osobowych, które udostępniasz w historii przeglądania stron i aplikacji internetowych, w celach marketingowych (obejmujących zautomatyzowaną analizę Twojej aktywności na stronach internetowych i w aplikacjach w celu ustalenia Twoich potencjalnych zainteresowań dla dostosowania reklamy i oferty) w tym na umieszczanie znaczników internetowych (cookies itp.) na Twoich urządzeniach i odczytywanie takich znaczników, kliknij przycisk „Przejdź do serwisu” lub zamknij to okno.

Pozdrawiamy,
Zespół Regalia"

**Comment by seba2282** [comment]
> Przecież jest etykieta / label pod tytułem i po prawej...

Widzę, ale chcę potem dobrać się do innych elementów.

**Comment by krystian3w** [comment]
No raczej nie za 5 dwunasta.

Dodatkowo niby dobrze sprawdzić czy te RODO blokuje odtwarzacz video i czy działa tam klikanie dodatkiem PCZ.

**Comment by seba2282** [comment]
> No raczej nie za 5 dwunasta.
> 
> Dodatkowo niby dobrze sprawdzić czy te RODO blokuje odtwarzacz video i czy działa tam klikanie dodatkiem PCZ.

Dobra, najwyżej za parę godzin. :)
