### ISSUE TITLE
pzkosz.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1883]
koszulka kibica reprezentacji polski

**Comment by KerbenII** [comment]
`pzkosz.pl##.aside-ad-block`

**Comment by xxcriticxx** [comment]
@KerbenII co sie stal ze starym nickem?

**Comment by KerbenII** [comment]
@xxcriticxx to jest to samo konto (sprawdź daty utworzenia moich repozytoriów).
Ogólnie "long support story".

**Comment by xxcriticxx** [comment]
@KerbenII Joined on Jan 5, 2017 

napisz donich to tobie ten nick naprawia

**Comment by KerbenII** [comment]
Już wystarczająco im zawracałem głowę ostatnio 👅

**Comment by xxcriticxx** [comment]
mi tez kiedys nicka zamkneli pare email i wszystko bylo spowrotem
