### ISSUE TITLE
ulub.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1888]
KLIKmapa

`http://ulub.pl/jA19jOEb66/the-chainsmokers-dont-let-me-down-bass-boosted`

**Comment by xxcriticxx** [comment]
`http://ulub.pl/pqA6QrmHN3/avril-lavigne-wish-you-were-here-youtube`

**Comment by MajkiIT** [comment]
ulub.pl##a[href="http://www.klikmapa.pl"]
