### ISSUE TITLE
zdrowie.gazeta.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1891]
ad block 

`http://zdrowie.gazeta.pl/Zdrowie/12,112276,19475015.html`

![capture](https://cloud.githubusercontent.com/assets/15007183/21742052/a27adc26-d4b4-11e6-8d73-7cb1b8fb5731.PNG)

**Comment by F4z** [comment]
`@@||video.gazeta.pl/cdn/ads/ad/banner/_adsense_/_adserver/_adview_.ad.json$xmlhttprequest,domain=video.gazeta.pl`
