### ISSUE TITLE
pl.whokeys.com jako przekręt

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#18917]
Tak jak w temacie.

 whokeys.com 

Według mnie jest to strona typu przekręty. Powód: np. klucze do produktów microsoft są po zbyt niskich cenach.  Nie będę się rozpisywać. 

I nie wiem gdzie napisać ten temat, ale strona wymaga zweryfikowania i zablokowania jako przekręt.

**Comment by xxcriticxx** [comment]
wrong repo 

I nie wiem gdzie napisać ten temat, ale strona wymaga zweryfikowania i zablokowania jako przekręt.
najlepiej w KAD repo

**Comment by seba2282** [comment]
@xxcriticxx Dzięki za informację. ☺️

**Comment by krystian3w** [comment]
Niby są z Chin 🇨🇳

**Comment by seba2282** [comment]
> wrong repo
> 
> I nie wiem gdzie napisać ten temat, ale strona wymaga zweryfikowania i zablokowania jako przekręt.
> najlepiej w KAD repo

Zgłosiłem jako podejrzaną stronę.
