### ISSUE TITLE
gazeta.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#18937]
https://buzz.gazeta.pl/buzz/0,0.html#e=GFootLink
To coś
![Zrzut ekranu z 2021-03-07 11-11-12](https://user-images.githubusercontent.com/36385327/110236402-f415dd80-7f35-11eb-9e41-d70edcb1b569.png)
Pozostałość po reklamie
![Zrzut ekranu z 2021-03-07 11-12-27](https://user-images.githubusercontent.com/36385327/110236409-03952680-7f36-11eb-9572-240a8ac13406.png)

https://www.sport.pl/zimowe/7,79229,26857965,fantastyczny-fenomenalny-przejazd-maryny-gasienicy-daniel.html#s=SMT_Img_1
Pozostałość po reklamie
![Zrzut ekranu z 2021-03-07 11-13-17](https://user-images.githubusercontent.com/36385327/110236437-23c4e580-7f36-11eb-9204-0ba6ff990c6b.png)
![Zrzut ekranu z 2021-03-07 11-13-39](https://user-images.githubusercontent.com/36385327/110236445-2de6e400-7f36-11eb-8fcd-1d62a6b6bca1.png)
![Zrzut ekranu z 2021-03-07 11-13-54](https://user-images.githubusercontent.com/36385327/110236454-36d7b580-7f36-11eb-80ae-361115cdbe2f.png)

https://www.plotek.pl/plotek/0,0.html
To coś
![Zrzut ekranu z 2021-03-07 11-14-49](https://user-images.githubusercontent.com/36385327/110236495-68508100-7f36-11eb-9e9e-48f22325a677.png)
Pozostałość po reklamie
![Zrzut ekranu z 2021-03-07 11-15-36](https://user-images.githubusercontent.com/36385327/110236507-79998d80-7f36-11eb-8513-921d4fe13877.png)
https://www.plotek.pl/plotek/7,154063,26857959,agustin-egurrola-powital-na-swiecie-syna-pokazal-zdjecia-z.html#disableRedirect
Pozostałość po reklamie
![Zrzut ekranu z 2021-03-07 11-16-20](https://user-images.githubusercontent.com/36385327/110236537-9b931000-7f36-11eb-99d5-d5b0a5a68a3b.png)
![Zrzut ekranu z 2021-03-07 11-16-31](https://user-images.githubusercontent.com/36385327/110236541-9f269700-7f36-11eb-9f4a-7f2380977488.png)
![Zrzut ekranu z 2021-03-07 11-16-41](https://user-images.githubusercontent.com/36385327/110236542-a057c400-7f36-11eb-8f31-6f95a176e0e2.png)

https://next.gazeta.pl/next/0,0.html
Pozostałość po reklamie
![Zrzut ekranu z 2021-03-07 11-17-35](https://user-images.githubusercontent.com/36385327/110236571-c8dfbe00-7f36-11eb-8da3-11f52128ce35.png)
![Zrzut ekranu z 2021-03-07 11-17-46](https://user-images.githubusercontent.com/36385327/110236574-caa98180-7f36-11eb-8389-f0659b952d24.png)

https://kultura.gazeta.pl/kultura/0,0.html
Pozostałość po reklamie
![Zrzut ekranu z 2021-03-07 11-18-50](https://user-images.githubusercontent.com/36385327/110236606-f462a880-7f36-11eb-9882-ce2aad41d096.png)
![Zrzut ekranu z 2021-03-07 11-19-02](https://user-images.githubusercontent.com/36385327/110236608-f62c6c00-7f36-11eb-9325-fa61481ca812.png)

https://www.edziecko.pl/edziecko/0,0.html
Pozostałość po reklamie
![Zrzut ekranu z 2021-03-07 11-20-59](https://user-images.githubusercontent.com/36385327/110236645-40155200-7f37-11eb-8654-cc6ba72c75ca.png)
![Zrzut ekranu z 2021-03-07 11-21-13](https://user-images.githubusercontent.com/36385327/110236649-43a8d900-7f37-11eb-90bb-fa91573a0e86.png)
Napis REKLAMA
![Zrzut ekranu z 2021-03-07 11-21-44](https://user-images.githubusercontent.com/36385327/110236660-515e5e80-7f37-11eb-8407-f3c8a5ae7bcc.png)
Pozostałość po reklamie
![Zrzut ekranu z 2021-03-07 11-22-07](https://user-images.githubusercontent.com/36385327/110236669-61763e00-7f37-11eb-91be-07b6923c6347.png)
https://www.edziecko.pl/starsze_dziecko/7,79351,26853429,przemyslaw-czarnek-chce-walczyc-z-otyloscia-wsrod-dzieci-nowy.html
![Zrzut ekranu z 2021-03-07 11-23-26](https://user-images.githubusercontent.com/36385327/110236694-8bc7fb80-7f37-11eb-8930-13455c39db88.png)
![Zrzut ekranu z 2021-03-07 11-23-39](https://user-images.githubusercontent.com/36385327/110236701-94203680-7f37-11eb-9a77-21bbe68e0979.png)
![Zrzut ekranu z 2021-03-07 11-23-56](https://user-images.githubusercontent.com/36385327/110236707-9d110800-7f37-11eb-92b1-b4267ab535ae.png)
![Zrzut ekranu z 2021-03-07 11-24-12](https://user-images.githubusercontent.com/36385327/110236712-a7330680-7f37-11eb-9fe1-ea06e7cb5f52.png)

https://zakupy.avanti24.pl / https://avanti24.pl/
Social
![Zrzut ekranu z 2021-03-07 11-25-12](https://user-images.githubusercontent.com/36385327/110236735-ccc01000-7f37-11eb-9108-39eea93c0e79.png)
Napis Reklama
![Zrzut ekranu z 2021-03-07 11-25-41](https://user-images.githubusercontent.com/36385327/110236744-dd708600-7f37-11eb-9559-48ecdbe8605b.png)
Social
![Zrzut ekranu z 2021-03-07 11-26-26](https://user-images.githubusercontent.com/36385327/110236769-fc6f1800-7f37-11eb-8210-1b6cd9da5526.png)
https://avanti24.pl/newsy/7,176333,26830008,malgorzata-kozuchowska-zachwyca-sukienka-w-kwiaty-polskiej-marki.html
Pozostałość po reklamie
![Zrzut ekranu z 2021-03-07 11-27-18](https://user-images.githubusercontent.com/36385327/110236802-26c0d580-7f38-11eb-9ba9-6c824bae8be6.png)
![Zrzut ekranu z 2021-03-07 11-27-26](https://user-images.githubusercontent.com/36385327/110236805-29232f80-7f38-11eb-93eb-2fa19d140040.png)

**Comment by krystian3w** [comment]
Majki IT daj znać jakby te "takie coś" z tym dziwnym JavaScript to był jednak social:

```js

                                    putBanDFPInViewObject({
                                        slot: '099-BOMBKA',
                                        divId: 'banP99_DFP',
                                        kw: ['tiles']
                                    });
```
