### ISSUE TITLE
google.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1893]
to tylko umnie tak bo ja poza krajem?

`https://www.google.pl/maps/@51.9189046,19.3211462,7z`

![capture](https://cloud.githubusercontent.com/assets/15007183/21742571/b2cee08a-d4bf-11e6-8d76-dc18a5e75eea.PNG)

**Comment by FadeMind** [comment]
To jest standardowa informacja **TOS** 
https://www.google.com/policies/terms/

IMO NOT_A_BUG

@MajkiIT

**Comment by MajkiIT** [comment]
@FadeMind dzięki
