### ISSUE TITLE
clikcoin.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1895]
ad block 

![capture](https://cloud.githubusercontent.com/assets/15007183/21750509/684d48ee-d582-11e6-8b39-631cc0db2bd2.PNG)

**Comment by F4z** [comment]
Skrypt AAK to blokuje.

Do uBlocka można dodać tę regułę:
`clikcoin.pl##script:inject(bab-defuser.js)`

W przypadku Adblocka te dwie reguły powinny wystarczyć:
`@@||clikcoin.pl^$generichide`
`clikcoin.pl##.adsbygoogle`
