### ISSUE TITLE
sklep.unimet.pl + b2b.unimet.pl + wsk.unimet.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#18969]
![screenshoot_101984](https://user-images.githubusercontent.com/75935068/110296577-c5aa0800-7ff2-11eb-8a79-031f6fcfd08c.png)

**Comment by strict-block** [comment]
`b2b.unimet.pl` otwiera coś innego: `https://nowe-b2b.unimet24.pl/login`

*i raczej rejestracja w B2B jest poza zasięgiem nawet po rejestracji firmy "1 osobowej".*

Jak się da to może podaj dokładny URL, który otwiera starą wersję systemu B2B bez przekierowań.

**Comment by felix-22** [comment]
### 1

> `b2b.unimet.pl` otwiera coś innego: `https://nowe-b2b.unimet24.pl/login`
> Jak się da to może podaj dokładny URL, który otwiera starą wersję systemu B2B bez przekierowań.

- hahaha nosił wilk razy kilka, ponieśli i wilka...Jasiu, siadaj, pała z matematyki, jakiś czas temu widziałem czyjeś zgłoszenie, w którym MajkiIT wszedł i napisał komentarz że strona się nie ładuje / nie istnieje, a ty potem napisałeś komentarz i dałeś burę adminowi bo okazało się, że po dodaniu `www.` strona jednak się ładuje i istnieje, co przeoczył nasz admin, więc co mi pozostaje jak nie to samo, czyli wg. twojego prawa teraz ty zasługujesz na burę, bo nie sprawdziłeś strony z `https`:
   - domyślnie ładuje się wersja `http`: `b2b.unimet.pl` ==> `http://b2b.unimet.pl` ==> `https://nowe-b2b.unimet24.pl/login`
   - a stara wersja o którą pytasz to wersja z `https`: `https://b2b.unimet.pl/`, oczywiście najpierw wyskoczy komunikat z ostrzeżeniem, który trzeba ominąć, (a mój bot jakimś cudem omija takie coś z automatu więc udało mu się wejść na stronę):
<details not-open>
<summary>zrzuty ekranu</summary>


![capture_084_08-03-2021_13-46-29](https://user-images.githubusercontent.com/75935068/110323364-cce20d80-8014-11eb-843e-6366d1039ea1.png)

![capture_085_08-03-2021_13-51-10](https://user-images.githubusercontent.com/75935068/110323770-5abdf880-8015-11eb-9483-feb9d87a259a.png)

</details>

   - na twoje pocieszenie twoją obroną może być teraz np. to że stron z ostrzeżeniami nie bierzecie pod uwagę bo i tak typowy użytkownik nie wejdzie na taką stronę, nie pamiętam dokładnie, ale nawet kiedyś chyba ktoś mi pisał czy uwzględniacie takie strony czy nie, a ja już po prostu zapomniałem i dlatego wolałem na wszelki wypadek dodać tę stronę, ale jeśli jednak nie uwzględniacie to ok

### 2
- niezależnie od powyższego, znalazłem także inną stonę z komunikatem: `wsk.unimet.pl`
