### ISSUE TITLE
skkp.org.pl + cedus.edu.pl (reopen)

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#18963]
Reopen https://github.com/MajkiIT/polish-ads-filter/issues/18924 bo dalej jest.

**Comment by strict-block** [comment]
Sprawdź jaki projekt banuje filtr:

`/cookie/banner`

* Raczej zalecamy aktualizacje równoległą bazy IDCAC, bo dalej istnieje: https://github.com/AdguardTeam/FiltersRegistry/commit/b133bcffb45e1663c4de7ce8b6ba6ecb9dfa39af#diff-0b02fdda200b9e2bb01431d66384571bdf2ab30dbd077b128dde0eb4c6921080R21414 (niestety nie zanosi się by dodatek miał premierę nowej wersji do 3 razy na tydzień wtedy można czuć lekkie poszkodowanie)

* Filtr ma około 3 dni: https://github.com/AdguardTeam/FiltersRegistry/commit/934af0aa69a362be9b29d0ed5fad4fb3fe063e58#diff-0b02fdda200b9e2bb01431d66384571bdf2ab30dbd077b128dde0eb4c6921080R21386

**Comment by felix-22** [comment]
- nic nie banuje, chodzi o to drugie co piszesz, przed założeniem zgłoszenia, dla pewności aktualizowałem wszystkie dodatki ale nie bylo żadnych dostępnych aktualizacji i było IDCAC w wersji `3.2.8` (4 marca), dopiero teraz zaktualizowało mi na `3.2.9` (8 marca), i już komunikaty zostały ukryte
