### ISSUE TITLE
GRUPA "IdoSell" (ponad 2700 stron) 😃

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#18975]
- pamiętacie poprzednią rekordową grupę, ponad 1000 stron: https://github.com/MajkiIT/polish-ads-filter/issues/17887 ?
- to teraz jest nowa, ponad 2700 stron: https://publicwww.com/websites/%22ck_dsclr%22/
- a tutaj dla przykładu jak wygląda komunikat ciasteczkowy z tej Grupy X: https://github.com/MajkiIT/polish-ads-filter/issues/18918 - jak widać ten sam komunikat w różnych kolorach
- nie wiedziałem jak ta Grupa się nazywa i czy w ogóle ma jakąś nazwę czy to po prostu zbiór przypadkowych stron korzystających z tego samego komunikatu, więc dałem Grupa "X", chyba, że ktoś znajdzie lepszą / odpowiedniejszą  nazwę _EDIT: padła propozycja nowej nazwy : https://github.com/MajkiIT/polish-ads-filter/issues/18975#issuecomment-792633873 więc tytuł został zaktualizowany, a Grupa to https://www.idosell.com/pl/_
- wniosek z tego taki: "niezbadane są głębiny morskie / oceaniczne" i nie wiadomo co jeszcze czycha w głębokich czeluściach / odmętach wody, może za jakiś czas znajdzie się kolejną grupę np. 5000 stron
- oczywiście już wczoraj został dodany generyk na polską listę ciasteczkową, więc będzie spokój z tym cholerstwem, a wątek jest informacyjny

**Comment by strict-block** [comment]
Już są dwa generyki: 

* sklepy idoSell z polskim językiem w kodzie html poza domeną `.pl` https://github.com/MajkiIT/polish-ads-filter/blob/8957b9bcfc665783bb44866b7202aa8aa0ab727f/cookies_filters/adblock_cookies.txt#L2799

* sklepy idoSell w polskiej domenie: https://github.com/MajkiIT/polish-ads-filter/blob/8957b9bcfc665783bb44866b7202aa8aa0ab727f/cookies_filters/adblock_cookies.txt#L2817

Poszkodowanie może być takie:

- sklep użyje wtyczki na cookies/RODO i wrzuci tam coś zupełnie innego, wtedy pop-up zniknie jakby zażywał hepaslimin (ale nazwa wskazuje na **c**oo**k**ie **d**i**scl**aimer...)
   - naprawa raczej ręczna jak ratujemy fanów AdBlock i Adblock Plus (w uBO i AG można spokojnie użyć upward i bazować na linkach jak pop-up będzie miał stabilny link).

- sklepy anglojęzyczne w polskiej domenie - wtedy to niby zabawa dla kiboke by on uruchomił swój generyk a nie my

- szablon sklepu idoSell nie będzie miał  języka zdefiniowanego w kodzie html i poza polską domeną "`.pl`" - tam wtedy nie wytnie filtr

**Comment by strict-block** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/4273
