### ISSUE TITLE
lohmann.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#18978]
![screenshoot_105008](https://user-images.githubusercontent.com/75935068/110441723-61eb1200-80ba-11eb-83df-3032436c7931.png)

**Comment by strict-block** [comment]
Znowu dziwna pętla, niby tylko z Google trafia się poprawnie na:

`lohmann-tapes.pl`

**Comment by felix-22** [comment]
Nom, bo to identyczny przypadek jak w https://github.com/MajkiIT/polish-ads-filter/issues/18969:
- link z google to `http`: `http://www.lohmann.pl/`, który przekierowuje na nową wersję strony ==> `https://www.lohmann-tapes.pl/`
- natomiast znaleziony przez mojego bota link to stara wersja strony z `https`: `https://www.lohmann.pl/` która nie przekierowuje na nową
- trochę to dziwne, bo tak jakby twórcy strony zapomnieli zrobić przekierowania z wersji strony `https`

**Comment by strict-block** [comment]
Mnie żadna przeglądarka po zignorowaniu TLS nie ładuje paska a strona po niemiecku.
