### ISSUE TITLE
portalhodowcy.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18987]
Polskie filtry za dużo blokują, proszę odblokować : 

1 - " okładki "

2 - " button - owady "

3 - " button koszyka "

oraz prosze zablokować button fb ( to do społecznościowych )

![ph](https://user-images.githubusercontent.com/23176832/110456917-63bcd180-80ca-11eb-9acc-84b31a5d0762.png)

**Comment by krystian3w** [comment]
Owady blokuje ten filtr:

https://github.com/MajkiIT/polish-ads-filter/blob/3e1567f98e62cb230954709e77ff79a8a3d9e0e8/polish-adblock-filters/adblock.txt#L2732

Okładki chyba zablokowane na prośbę @felix-22 jako prenumerata.

**Comment by krystian3w** [comment]
Co do buttona sklepu, to on chyba out jako element irytujący, przewijany - link do sklepu jest też w **HEADERZE** (nagłówku "nawigacyjnym").

**Comment by blocker999** [comment]
ok EI blokuje to co ma blokować ale zgłaszam te drobne niedociągniecia

**Comment by krystian3w** [comment]
Ten button social nie ma typowej klasy `kac-sm-fb` to wycieka, filtr proceduralny z `has-text` raczej nie jest optymalny, nie widzę jak tu użyć `upward` dla uBO/AG.

Owady wrócą jak MajkiIT znajdzie lepszy filtr na reklamy.
