### ISSUE TITLE
sklep.agroas.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#18998]
jesteśmy ( na dole )

**Comment by seba2282** [comment]
`www.sklep.agroas.pl##.footer_nls > .container`

`www.sklep.agroas.pl##.footer3`

`www.sklep.agroas.pl##.footer2`

`www.sklep.agroas.pl##div.container:nth-of-type(5)`

`www.sklep.agroas.pl##.joinus`
