### ISSUE TITLE
trybi.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1900]
ad block 

`https://trybi.pl/Blokada.html`

![capture](https://cloud.githubusercontent.com/assets/15007183/21751030/4be20d96-d58e-11e6-8120-6fbdb4327295.PNG)

**Comment by F4z** [comment]
Skrypt AAK sobie z tym radzi.

Do uBlocka można dodać taką regułę:
`trybi.pl##script:inject(fuckadblock.js-3.2.0)`

W przypadku Adblocka to:
`@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/$script,domain=trybi.pl`
`@@||trybi.pl$generichide`
`trybi.pl##.adsbygoogle`

Można jeszcze zablokować pozostałość po reklamach, na przykład:
`trybi.pl###main_content_section > div[style=" text-align: center; height: 260px;"]`
`trybi.pl##.bannerInner`
