### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19025]
Anty-adblock powodowany przez listę: 
`POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda`

<br>

![capture_089_10-03-2021_10-15-18](https://user-images.githubusercontent.com/75935068/110605676-a396be00-8189-11eb-9975-b3bdc700fdb5.png)

**Comment by felix-22** [comment]
@MajkiIT 

Najlepiej dodać obydwa:
(dla uBO) `elektroda.pl##+js(nostif, adBlockTest, 100)` 
(dla uBO + ABP) `elektroda.pl##section.row > div[class*="-"][class*=" "]:nth-child(1):-abp-contains(Adblock)`

**Comment by strict-block** [comment]
Zjadłeś `?` znowu źle dodadzą i nie zauważą buga, @olegwukr pamiętaj by filtry z `:-abp-` używały `#?#` a nie: `domena##filtr`

**Comment by felix-22** [comment]
No, chochliki zjadły, przy okazji: komuś innemu też zjadły:
https://github.com/MajkiIT/polish-ads-filter/blob/9b76322e8af4b83e8c51fcd4adc73de408b337c9/polish-adblock-filters/adblock.txt#L473

@MajkiIT

**Comment by felix-22** [comment]
### 1 Adblock naprawiony https://github.com/olegwukr/polish-privacy-filters/commit/238fd3797bd6e49dd309caf369a653aa766a1a69, więc zamykam.

### 2 Błąd 
https://github.com/MajkiIT/polish-ads-filter/blob/0c048a4386e00458fe35cf5482e801056abd21b0/adblock_social_filters/adblock_social_list.txt#L2143 nadal nienaprawiony pomimo dodatkowego zgłoszenia  https://github.com/MajkiIT/polish-ads-filter/issues/19700, tak czy inaczej tu zamykam, a od błędów jest osobne zgłoszenie https://github.com/MajkiIT/polish-ads-filter/issues/19700.

**Comment by strict-block** [comment]
Na dev poprawiony social.

**Comment by strict-block** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/d80262b8301095060588df76b70b8f31f9f971de/adblock_social_filters/adblock_social_list.txt#L2175

**Comment by strict-block** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/50735d274abc829de6b93749f82be43d950301cc#diff-d219502403e45626ef2a85625d1ee4e01c41c0c047a3817376ff039a5161fbc3L2143-R2157

**Comment by felix-22** [comment]
W [STARYM FILTRZE](https://github.com/olegwukr/polish-privacy-filters/blob/3bcffe8a41f1eddf25f44867eaa461431c2d1c68/anti-adblock-suplement.txt#L190) : `elektroda.pl##+js(no-setTimeout-if.js, adBlockTest, 100)`
zmieniamy `adBlockTest` na `adBlockElement`
