### ISSUE TITLE
kobieta.wortale.net

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1902]
maybe ad block

`https://kobieta.wortale.net/dziecko,ac151/odpowiedzialni-rodzice,ac158/twoje-dziecko-zaczelo-uzywac-brzydkich-slow-co-robic,369`

![capture](https://cloud.githubusercontent.com/assets/15007183/21751438/737f84bc-d595-11e6-8ead-6f942628e01e.PNG)

**Comment by FadeMind** [comment]
```
wortale.net##.adblock-alt
```
