### ISSUE TITLE
onnshop.pl ==> onninen.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19045]
![screenshoot_115270](https://user-images.githubusercontent.com/75935068/110763727-7bbf5d00-8252-11eb-880c-01a4c2216a25.png)

**Comment by strict-block** [comment]
Duplicate of #18974

**Comment by strict-block** [comment]
Nie widzę fizycznej opcji zatrzymania przekierowań po stronie serwera (nie wygląda by to robił JavaScript).

**Comment by felix-22** [comment]
Racja, duplikat.
