### ISSUE TITLE
oferty.dsautomobiles.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19048]
![screenshoot_116212](https://user-images.githubusercontent.com/75935068/110764077-e2447b00-8252-11eb-9da9-14f3cce589e5.png)

**Comment by strict-block** [comment]
To newsletter / formularz informacji zwrotnej, nie można wyciąć i jest poza celami akceptacji cookies/RODO projektu PCC/PCZ.

**Comment by felix-22** [comment]
Skoro to formularz / newsletter to zamykam, nie chodziło mi o wycinanie komunikatu ciasteczkowego z newslettera, cały formularz wyglądał do złudzenia jak komunikat ciasteczkowy i za taki go mylnie wziąłem.

**Comment by strict-block** [comment]
W sumie to nawet i brak podstrony gdzie będzie drugi raz, można najwyżej zobaczyć, czy da się przypiąć, by się nie przewijał.

**Comment by felix-22** [comment]
Znalazłem kilka podobnych, przeanalizuj:

### 1) oferty.citroen.pl
![screenshoot_150221](https://user-images.githubusercontent.com/75935068/111901883-e46cbd80-8a3a-11eb-921c-fd0894cc586b.png)

### 2) ofertysezonowe.citroen.pl
![screenshoot_150222](https://user-images.githubusercontent.com/75935068/111901919-0ebe7b00-8a3b-11eb-943f-0ca65779f6bf.png)

### 3) testuj.peugeot.pl
![screenshoot_150229](https://user-images.githubusercontent.com/75935068/111901929-1ed65a80-8a3b-11eb-9404-f96768850b34.png)

### 4) oferty.peugeot.pl
![screenshoot_150230](https://user-images.githubusercontent.com/75935068/111901954-331a5780-8a3b-11eb-8404-31d9c6725dee.png)

### 5) zima.peugeot.pl
![screenshoot_150232](https://user-images.githubusercontent.com/75935068/111901971-47f6eb00-8a3b-11eb-968b-1ad9faa9c69d.png)

**Comment by felix-22** [comment]
![ss_151695_wnioski toyotabank pl_](https://user-images.githubusercontent.com/75935068/112623089-30997280-8e2c-11eb-86b4-01b02f517865.png)
