### ISSUE TITLE
petanque.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19043]
![screenshoot_114488](https://user-images.githubusercontent.com/75935068/110680896-7671fc00-81d9-11eb-8ef8-74fc976268d4.png)

**Comment by strict-block** [comment]
Można zamknąć i zostaje ten z EI, nie da się wycinać w newsletterach pół do potwierdzania RODO/Regulaminów - zwłaszcza jak dodatkowo po stronie serwera weryfikują "post" / "get".

**Comment by felix-22** [comment]
Nom, to w ogóle pomyłka z mojej strony, to miało iść tylko na EI (newsletter), a o ten komunikat ciasteczkowy w newsletterze to nawet mi nie chodziło.
