### ISSUE TITLE
avip.com.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19063]
Nie wiem czy to się kwalifikuje jako ciastko czy raczej do EI (jako nie wiem co - np. pływająca stopka) a może takich pływających stopek też już nie robicie i kwalifikuje się np. do https://github.com/yourduskquibbles/webannoyances/issues (bo skoro pływających nagłówków już nie robicie to chyba stopek w takim razie też nie)

![screenshoot_119547](https://user-images.githubusercontent.com/75935068/110979885-7dc61080-8365-11eb-868d-e0f4280d92cd.png)

**Comment by strict-block** [comment]
Do "Jurka" zgłoś jak używasz jego listy, to są statyczne linki więc nie do cookies ani nie przypniemy tego w polskim EI.

**Comment by felix-22** [comment]
Ok.
