### ISSUE TITLE
pacjent.szpital.com.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19065]
Nie jestem pewien czy takie statyczne jest irytujące i się kwalifikuje czy nie

![screenshoot_120673](https://user-images.githubusercontent.com/75935068/110980609-50c62d80-8366-11eb-8b46-bfb6b9b1c3d7.png)

**Comment by strict-block** [comment]
Jak wejść, niby są offline lub dziwny musi być url np.

`www7.pacjent.szpital.com.pl` - w google takich brak.

**Comment by felix-22** [comment]
Przypominam po raz 3-ci ([TU1](https://github.com/MajkiIT/polish-ads-filter/issues/18969#issuecomment-792737974) był 1-szy raz , a [TU2](https://github.com/MajkiIT/polish-ads-filter/issues/18978#issuecomment-793968760) 2-gi raz) był 1szy raz,  
proszę pamiętać o protokole: owszem, z `http` strona jest offline, 
ale z `https` strona się ładuje (po ominięciu ostrzeżenia)
