### ISSUE TITLE
marbus.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19088]
![screenshoot_125587](https://user-images.githubusercontent.com/75935068/111083769-6034aa80-850f-11eb-8f2d-a69c71e9c9ab.png)

**Comment by strict-block** [comment]
Strona niby padła lub została shackowana (opróżniona).

**Comment by felix-22** [comment]
Przed chwilą wszedłem i działa.

**Comment by strict-block** [comment]
Dalej jakieś magie:

```html
<html><head><title>Secured Home of marbus.pl</title></head>
<body>
<center>Welcome to marbus.pl<br>
To change this page, upload a new index.html to your private_html folder<br></center>
</body>
</html>
```

I nie nie mogę cofnąć i włączyć jej na `HTTP`

**Comment by felix-22** [comment]
Też to mam na wersji `https`, ale na `http` normalnie strona się ładuje.

**Comment by felix-22** [comment]
[MAR-BUS.zip](https://github.com/MajkiIT/polish-ads-filter/files/6170213/MAR-BUS.zip)
