### ISSUE TITLE
starosadeckie.info

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#19098]
Brak tekstu w artykule, gdy aktywny jest polski filtr
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/111122716-b258e880-856e-11eb-81d4-971a790cdf93.png)
![obraz](https://user-images.githubusercontent.com/32641928/111122739-ba188d00-856e-11eb-80fc-f31f335d0007.png)

### Link bezpośredni 

https://www.starosadeckie.info/wydarzenia/testy-wykrywajace-przeciwciala-sars-cov-2-od-poniedzialku-do-kupienia-w-biedronce/

### Co trzeba zrobić, aby pojawił się błąd?
1. 
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda (2021.01.14.0)
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List
11. AdGuard Tracking Protection
12. AdGuard Base
13. AdGuard Mobile Ads
14. Fanboy’s Social 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Za agresywny: https://github.com/MajkiIT/polish-ads-filter/blob/d1cefd405f247155eedf095a4edc76485ce95c60/polish-adblock-filters/adblock.txt#L3028

`starosadeckie.info#@#.entry-content > p`

może dodajmy w jego miejsce:

`starosadeckie.info#?#.entry-content > p:-abp-contains(Reklama)`

Lub do kasacji.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/18431

**Comment by MajkiIT** [comment]
@krystian3w dzięki
