### ISSUE TITLE
bip.ops.stepnica.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19097]
![screenshoot_128318](https://user-images.githubusercontent.com/75935068/111084200-73e11080-8511-11eb-8ecc-28e00a982179.png)

**Comment by strict-block** [comment]
Brak sensownej opcji przekierowania na "stronę domową" - nie ma żadnego czegoś w tylu `/index2.html`.

Znajdź gdzie to przekierowywać, by ludzie nie czytali a się nie dziwili, że widzą "oferty pracy" a nie ich szukali wpisując adres z "łapy".
