### ISSUE TITLE
agrolas.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19099]
fb ( na dole )

**Comment by seba2282** [comment]
`www.agrolas.com##.copyright`

`www.agrolas.com##[href="https://www.facebook.com/beata.witkowska.948"]`


P.S. @xxcriticxx Czy mógłbyś nie zamykać tak szybko zgłoszeń, na które nie odpowiedziałem jeszcze? No wiesz, mam kilka prywatnych spraw i odpowiadam w miarę szybko, jak to jest możliwe. :)

**Comment by xxcriticxx** [comment]
@seba2282 ja jestem bot i dlatego robie to tak szybko bo nie posiadam prywatnego zycia

**Comment by seba2282** [comment]
@xxcriticxx To żeś powiedział.
