### ISSUE TITLE
organichouse.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19102]
( na dole )

**Comment by seba2282** [comment]
`organichouse.eu##[href="https://www.facebook.com/ORGANICHOUSE.eu"]`

`organichouse.eu##[href="https://www.instagram.com/zdrowedaktyle/"]`

`organichouse.eu###menu-item-10772 > [href="https://www.zdrowedaktyle.pl/"]`

`organichouse.eu###menu-item-3098 > [href="https://www.zdrowedaktyle.pl/"]`

`organichouse.eu###bx-item-actions-3 > .fader-on.fader.clearfix.grid-1.grid-container > .last-col.elements-meta.grid-2x-col.grid-col > .elements-buttons`

`organichouse.eu##.panel-row-style-for-322-2.panel-row-style.siteorigin-panels-stretch`
