### ISSUE TITLE
agro-eko.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19105]
fb ( po prawo ) i reszta ( na dole )

**Comment by seba2282** [comment]
`agro-eko.com.pl##.col-md-5.col-sm-7.col-lg-2.col`

`agro-eko.com.pl##div.col-sm-3.col-md-2.col-lg-1.col:nth-of-type(4)`

`agro-eko.com.pl###m4774 > .slides > .slide`

`agro-eko.com.pl###m2616 > .slides > .slide`

`agro-eko.com.pl##div.col-md-3.col-lg-2.col-sm-12.col:nth-of-type(5)`
