### ISSUE TITLE
kinoman.tv

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1910]
usunąć reguły
http://film.wp.pl/serwis-kinoman-tv-zawieszony-kolejny-tego-typu-portal-znika-z-sieci-6078253596119681a

**Comment by xxcriticxx** [comment]
sa juz nowe serwisy `cdax.tv`

**Comment by MajkiIT** [comment]
@xxcriticxx wiem :D dzięki

**Comment by FadeMind** [comment]
Mają rozmach xD @xxcriticxx dzięki

BTW. Jakoś nikt nie zamyka openload czy vshare xD

**Comment by xxcriticxx** [comment]
nastepny serwise `http://kinostar.tv` wschodza jak grzyby po deszczu
