### ISSUE TITLE
fc.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19113]
![screenshoot_129153](https://user-images.githubusercontent.com/75935068/111162372-615fe900-859c-11eb-95a6-001b2aea5ff4.png)

**Comment by strict-block** [comment]
Nie da się bezpiecznie wyciąć, za sztywno osadzili tekst i znikną inne cztery elementy:

![obraz](https://user-images.githubusercontent.com/79422224/111674861-c590e000-881c-11eb-875e-6c3f239d1c97.png) |
--- |
