### ISSUE TITLE
agrimar.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19118]
( na dole )

**Comment by seba2282** [comment]
`agrimar.pl##div.vc_row-fluid.wpb_row.vc_row:nth-of-type(30)`

`agrimar.pl##.copyright-footer`

**Comment by krystian3w** [comment]
filtr z wycinaniem 30 diva raczej kiepski, może coś zniknie wyżej i będzie miał niższy numer?

**Comment by seba2282** [comment]
Wiem gdzie to jest teraz. Blokowałem ten sklep z innej strony. Ale tutaj teraz dodatkowo doszło inna strona pomiędzy markami + w tym sliderze masa promowania innej firmy, co jest partnerem. Jakaś polaris. I ten sklep, slider i w partnerach porzebuję zablokować, a copyright footer wygląda na dobrze.

**Comment by seba2282** [comment]
+ slider:
`agrimar.pl##.vc_row-no-padding.vc_custom_1453200552863.vc_row-fluid.wpb_row.vc_row > .vc_col-md-12.vc_column_container.wpb_column > .vc_column-inner`


+ sklep: `agrimar.pl##.animated.wpb_start_animation.bounceIn.wpb_bounceIn.wpb_animate_when_almost_visible.vc_align_center.wpb_content_element.wpb_single_image > .vc_figure.wpb_wrapper > .vc_box_border_grey.vc_single_image-wrapper > .attachment-full.vc_single_image-img`


Spróbowałem się tego polaris pozbyć kosztem paru marek:
`agrimar.pl##.vc_row-has-fill.vc_custom_1570535643868.logotypy-glowna.vc_row-fluid.wpb_row.vc_row > div.vc_col-md-2.vc_column_container.wpb_column > .vc_column-inner > .wpb_wrapper > .vc_align_center.wpb_content_element.wpb_single_image > .vc_figure.wpb_wrapper > .vc_box_border_grey.vc_single_image-wrapper`

**Comment by krystian3w** [comment]
Pozmieniają numerki `vc_custom_` i padnie.

ten o sklepie też długi i bazujesz na tym jak niby coś animują na tym obiekcie.

**Comment by seba2282** [comment]
@krystian3w to w takim razie co sugerujesz?

**Comment by seba2282** [comment]
@krystian3w masz jakieś sugestie, jak rozgryźć te trzy elementy do zablokowania?

**Comment by krystian3w** [comment]
Sklep jednym z dwóch albo łącząc:

`||agrimar.pl/wp-content/uploads/20*/*/mfshop2*.png`
`agrimar.pl##a[href*="shop.massey"][target="_blank"] > img`

Jednak średnio ogarniam obrazy RWD, więc filtr sieciowy może wymagać zmiany na mniej czytelny:

`||agrimar.pl/wp-content/uploads/20*/*/mfshop2$image`

---

Polarisa samego to może:

`agrimar.pl#?#.featured-content, logotypy-glowna > div:-abp-has(a[href*="polaris.pl"][target="_blank"] > img)`

ale może warto wtedy wywalić rzędy logotypów i nagłówek?

**Comment by seba2282** [comment]
@krystian3w Więc jak sugerujesz, by było lepiej? Jeżeli rzędami logotypy, więc jak? A może lepiej wszystkie te logotypy ukryć?

**Comment by krystian3w** [comment]
Jak tylko polaris i nie widzisz więcej postów sponsorowanych niż ja ten jeden, to masz praktycznie gotowca.

Jak całą sekcje to na szybko takie coś:
```
agrimar.pl#?#h2:-abp-contains(Oferta według marek)
agrimar.pl#?#h2:-abp-contains(Oferta według marek):upward(4) ~ .logotypy-glowna
```

Układ strony chyba wymaga by to było rozbite na dwa filtry. Przy czym drugi pewnie dalej nie ruszy w AG z racji używania `Sizzle.js` i chyba `:upward(4)` wymagałby zmiany na np. `.vc-row` (bez cyferek) dla mniejszych szkód, a najbardziej będzie spowalniać sprawdzanie tekstu w `<h2>` (nagłówku).

**Comment by seba2282** [comment]
A ten slider taki Wielki też ma promo Polaris. @krystian3w

**Comment by seba2282** [comment]
Mam taką pustą rubrykę po sklepie + slider z polaris, ten baner co się przewija.

**Comment by seba2282** [comment]
`agrimar.pl##.copyright-footer`
`agrimar.pl##a[href*="shop.massey"][target="_blank"] > img`
`agrimar.pl#?#h2:-abp-contains(Oferta według marek)`
`agrimar.pl#?#h2:-abp-contains(Oferta według marek):upward(4) ~ .logotypy-glowna`
`agrimar.pl#?#.featured-content, logotypy-glowna > div:-abp-has(a[href*="polaris.pl"][target="_blank"] > img)`
`agrimar.pl##.tp-revslider-mainul`
`agrimar.pl##div.vc_row-fluid.wpb_row.vc_row:nth-of-type(29)`
`agrimar.pl##.vc_col-md-8.vc_column_container.wpb_column`

@krystian3w Finalnie te pomagają.

**Comment by krystian3w** [comment]
Dalej jakieś 29 coś - "row" - wiersz i bazuje na stylowaniu jako "fluid". i wycinasz niby każdą kolumnę co ma rozmiar 8/12 (większa) lub 4/12 (niniejsza).

**Comment by seba2282** [comment]
@krystian3w to jakie sugestie?

**Comment by seba2282** [comment]
> `agrimar.pl##div.vc_row-fluid.wpb_row.vc_row:nth-of-type(29)`
> `agrimar.pl##.vc_col-md-8.vc_column_container.wpb_column`

@krystian3w Dasz jakąś lepszą sugestię do tych dwóch? Bo chyba o nich mówisz.
