### ISSUE TITLE
film.wp.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1912]
Wycwanili się xD @MajkiIT 
```
film.wp.pl##._2PL-mL0.kBUqizx
```

![screenshot_20170109_110210](https://cloud.githubusercontent.com/assets/9846948/21762870/4feff9f2-d65b-11e6-961b-beab9cac377f.png)

**Comment by MajkiIT** [comment]
@FadeMind spoko ogarniemy. Dzięki
