### ISSUE TITLE
edostawcze.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19133]
![Zrzut ekranu z 2021-03-15 16-54-59](https://user-images.githubusercontent.com/36385327/111182461-3763f200-85af-11eb-9e2f-0b6674f638a0.png)

**Comment by seba2282** [comment]
`edostawcze.pl##.ed-header-social-icons`

`edostawcze.pl##.kswr_bnone.kswr_mnone.kswr_pnone.vc_row-has-fill.vc_custom_1585582634368.text-shadow.text-white-color.pix-row-overlay.pix-vc_row-no-padding.vc_row-fluid.wpb_row.vc_row > .vc_col-sm-12.vc_column_container.wpb_column`

`edostawcze.pl###openContactPopup`

`edostawcze.pl##.vc_col-sm-12.vc_column_container.wpb_column > .vc_column-inner > .wpb_wrapper > .kswr-theelement.kswr-heading-container > .kswr-shortcode-element.kswr-heading-content > p`

`edostawcze.pl##.wpb_wrapper > .kswr-style-changer.km-socials-share-modern`
