### ISSUE TITLE
agro-kowalski.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19131]
fb ( u góry )

**Comment by seba2282** [comment]
`www.agro-kowalski.com.pl##li:nth-of-type(1)`

**Comment by krystian3w** [comment]
Zbyt generyczne, uszkodzi każdą listę wypunktowaną w innych miejscach na stronie.

**Comment by seba2282** [comment]
`www.agro-kowalski.com.pl##[href="https://www.facebook.com/agrokowalskiwrzesnia/"]`

Teraz? @krystian3w

**Comment by krystian3w** [comment]
To już lepsze ale bloker zalecałby dodanie np. `img` / `svg` jakby cudem link był luźno w artykule w zdaniu:

"posialiśmy o tym na naszym <ins>facebooku</ins> rano".

jak nie ma grafiki to sprawdź:

`www.agro-kowalski.com.pl##li [href="https://www.facebook.com/agrokowalskiwrzesnia/"]`

Wtedy takie luźne stania nie stracą sensu.

**Comment by seba2282** [comment]
Też działa.

> www.agro-kowalski.com.pl##li [href="https://www.facebook.com/agrokowalskiwrzesnia/"]
