### ISSUE TITLE
sylwa.eu

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19134]
https://sylwa.eu/rerum/pl/akademia-smorgonska/
![Zrzut ekranu z 2021-03-15 16-57-03](https://user-images.githubusercontent.com/36385327/111182750-8447c880-85af-11eb-834d-9a05d2c26992.png)
![Zrzut ekranu z 2021-03-15 16-57-18](https://user-images.githubusercontent.com/36385327/111182759-86118c00-85af-11eb-9acf-0864301109d4.png)

**Comment by seba2282** [comment]
`sylwa.eu##.astra-widget-list-icons.widget`

`sylwa.eu##.site-footer`

`sylwa.eu##div.wp-block-image:nth-of-type(6)`

**Comment by krystian3w** [comment]
grafikę lepiej po nazwie `||sylwa.eu/rerum/wp-content/uploads/20*/*/*Please-follow-us-on-Facebook-*.png`

**Comment by seba2282** [comment]
`||sylwa.eu/rerum/wp-content/uploads/20*/*/*Please-follow-us-on-Facebook-*.png`
`sylwa.eu##.astra-widget-list-icons.widget`
`sylwa.eu##.wp-image-238`
`sylwa.eu##.site-footer`

**Comment by krystian3w** [comment]
nie mam pewności czy ID obrazka się nie zmieni, raczej Wordpress nie powinien losować mu numerka do czasu wymiany na inny/podmiany.

**Comment by seba2282** [comment]
> nie mam pewności czy ID obrazka się nie zmieni, raczej Wordpress nie powinien losować mu numerka do czasu wymiany na inny/podmiany.

Taki ID wskazało, to wziąłem po ID. :)
