### ISSUE TITLE
vod.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1913]
`http://vod.pl/seriale/spadkobiercy-za-darmo-online/mz6ebre`

![screenshot_20170109_192528](https://cloud.githubusercontent.com/assets/9846948/21777916/6c152b8e-d6a1-11e6-912d-dafeeece21b6.png)

W całym serwisie VOD się to pojawia. AAK + AAK SC jest aktywny, ale nie ogarnia.

**Comment by F4z** [comment]
Nie widzę tego u siebie.

**Comment by xxcriticxx** [comment]
Nie możemy wyświetlić filmu
Materiał nie jest dostępny w Twoim kraju

**Comment by FadeMind** [comment]
Mój błąd. Mam restrykcyjny plik hosts.
Dodałem na białą listę csr.onet.pl:
```
# 0.0.0.0 csr.onet.pl
```
BTW:

```
$ cat /etc/hosts|grep onet.pl
0.0.0.0 banery.onet.pl
0.0.0.0 banki.onet.pl
0.0.0.0 boksy.dir.onet.pl
0.0.0.0 boksy.onet.pl
# 0.0.0.0 csr.onet.pl
0.0.0.0 ds.onet.pl
0.0.0.0 kropka.onet.pl
0.0.0.0 novem.onet.pl
0.0.0.0 reklama.onet.pl
0.0.0.0 republika.onet.pl
0.0.0.0 toronet.pl
0.0.0.0 www.toronet.pl
0.0.0.0 emisjawidgeet.onet.pl
0.0.0.0 stats.media.onet.pl
```

**Comment by xxcriticxx** [comment]
@FadeMind czego ty uzywasz do hostow?

**Comment by FadeMind** [comment]
https://github.com/FadeMind/hosts.extended

**Comment by xxcriticxx** [comment]
tylko dnsmasq?

**Comment by FadeMind** [comment]
`/etc/hosts` :file_cabinet:

**Comment by xxcriticxx** [comment]
testowales pi-hole albo privoxy

**Comment by FadeMind** [comment]
@xxcriticxx  nie.

**Comment by xxcriticxx** [comment]
`https://pi-hole.net` uzywam tego na ubuntu 16.04
