### ISSUE TITLE
bagramet.eu/pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19143]
( buttons )

**Comment by seba2282** [comment]
`bagramet.eu##.socialmedia_wid.moduletable`

`bagramet.eu##div.col-sm-3.custom:nth-of-type(4)`

**Comment by krystian3w** [comment]
filtr na wycinanie partnerów może być wadliwy użyj `##footer ...`

**Comment by seba2282** [comment]
`bagramet.eu##.socialmedia_wid.moduletable`
`bagramet.eu##footer.col-sm-3.custom:nth-of-type(4)`

Teraz? @krystian3w

**Comment by krystian3w** [comment]
Nie miało być ze spacją po footer.

**Comment by seba2282** [comment]
`bagramet.eu##.socialmedia_wid.moduletable`
`bagramet.eu##footer .col-sm-3.custom:nth-of-type(4)`

Bez kropki przed col-sm...?

**Comment by krystian3w** [comment]
Z kropką, to nazwa klasy, że element jest na szerokość 3 pól z 12 czyli w układzie "4 kolumnowym".

**Comment by seba2282** [comment]
To już mamy w takim razie.
