### ISSUE TITLE
e-pasaz.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19148]
cookies i fb ( button )

**Comment by seba2282** [comment]
+ Dla @xxcriticxx nie wiem czy dobra reguła dla cookie. Możesz ją sprawdzić? 
`e-pasaz.com###cookies-wiadomosc-content`


+ Inne:
`e-pasaz.com##.facebook`

`e-pasaz.com###orderShop`

`e-pasaz.com##[href="http://obf.com.pl/"]`
