### ISSUE TITLE
butyraj.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19156]
fb ( u góry i na dole )

**Comment by seba2282** [comment]
`www.butyraj.pl##header.clearfix > .clearfix.row`
`www.butyraj.pl##div.menu_button_wrapper:nth-of-type(6)`
`www.butyraj.pl##div.menu_button_wrapper:nth-of-type(7)`
`www.butyraj.pl##.menu_buttons2`
`www.butyraj.pl##.container.clearfix.n60972_main`
