### ISSUE TITLE
blog.trueblue.pl ==> kawalekkodu.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19168]
(można dodać także etykietę "cookies", bo anty-adblocka wywołuje lista ciasteczkowa)

- anty-adblocka wywołuje dodatek `I don't care about cookies` 
(nie sprawdzałem, czy lista też, bo nie używam listy, tylko dodatku)
- pomyślałem, że wrzucę to tutaj bo `Polskie Filtry RODO-Ciasteczkowe` bazują na `I don't care about cookies`  i może:
   -  zawołacie Kiboke żeby to naprawił (bo czasem pingujecie go z naszych repo) 
   - i/albo naprawicie to sami w `Polskie Filtry RODO-Ciasteczkowe` bo macie sekcję `! Bugi Kiboke`

![screenshoot_136661](https://user-images.githubusercontent.com/75935068/111446318-8ecba480-870c-11eb-904e-55cde3a35251.png)

**Comment by strict-block** [comment]
Kiboke allow load these:

`https://kawalekkodu.pl/bl-plugins/cookie-consent/js/advert.js`

**Comment by kiboke** [comment]
@strict-block I will, thanks!
