### ISSUE TITLE
liderbudowlany.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19162]
( na dole )

**Comment by seba2282** [comment]
`www.liderbudowlany.pl##.d-md-flex.d-none.no-gutters.row.promos > .padd.col-12 > .lg.banner.hp-promo > [href="https://tarnopak.pl/"] > .wp-post-image.img-fluid`
`www.liderbudowlany.pl##[href="http://creativeheads.pl"]`
`www.liderbudowlany.pl##.pt-md-0.pt-4.social.col`
`www.liderbudowlany.pl##[href="https://www.mea-group.com/pl/"] > .wp-post-image.img-fluid`
