### ISSUE TITLE
forum.e-hodowca.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19166]
![screenshoot_136382](https://user-images.githubusercontent.com/75935068/111444610-d7825e00-870a-11eb-8daf-b5da25472378.png)

**Comment by strict-block** [comment]
Forum nawala errorami 404 jakby padł CDN  "LiteSpeed Web Server"

![Screenshot_2021-03-19 404 Not Found](https://user-images.githubusercontent.com/79422224/111756227-45a95b00-889a-11eb-82a2-b4d6397423d6.png) |
---|

też nie da się ominąć wymuszanego https

**Comment by felix-22** [comment]
> też nie da się ominąć wymuszanego https

Raczej literówka i `http` chciałeś napisać, bo na `https` to właśnie sypie błędem 404 jak u ciebie, ale na `http` strona normalnie się ładuje.

[kroliki.zip](https://github.com/MajkiIT/polish-ads-filter/files/6170257/kroliki.zip)
