### ISSUE TITLE
katalogprzedsiebiorstw.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19160]
fb ( prawy górny róg )

**Comment by seba2282** [comment]
`www.katalogprzedsiebiorstw.pl##[href^="http://www.facebook.com/pages/KatalogPrzedsiebiorstwpl/166448756715059"]`
`www.katalogprzedsiebiorstw.pl##[href="https://www.ltb.pl/"]`
`www.katalogprzedsiebiorstw.pl###footerwidgeted-4 > .widget_text.widget`
`www.katalogprzedsiebiorstw.pl##.footer2`
`www.katalogprzedsiebiorstw.pl##[href="http://www.vipturystyka.pl"]`
`www.katalogprzedsiebiorstw.pl##[href="http://www.agroturystyczny24.pl"]`
`www.katalogprzedsiebiorstw.pl###text-506`
`www.katalogprzedsiebiorstw.pl###text-503`
`www.katalogprzedsiebiorstw.pl##td:nth-of-type(2)`
