### ISSUE TITLE
antyradio.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1916]
```
antyradio.pl##.node-2.esi-tiled.adsearch-adkontekst
```

**Comment by MajkiIT** [comment]
@FadeMind Co ta reguła robi?

**Comment by FadeMind** [comment]
![screenshot_20170110_101658](https://cloud.githubusercontent.com/assets/9846948/21800434/f0274c82-d71d-11e6-8ae1-33e239e989dd.png)

**Comment by MajkiIT** [comment]
Ok dzięki
