### ISSUE TITLE
synonimy.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19171]
https://www.synonimy.pl/synonim/gazeta/

![synonimy](https://user-images.githubusercontent.com/23176832/111450109-57f78d80-8710-11eb-8eef-8501a9db78c7.jpg)

**Comment by felix-22** [comment]
blocker999 dlaczego nie dałeś etykiety "adblock detect"

**Comment by AroKol78** [comment]
adblock detect - 
`@@||stats.g.doubleclick.net/dc.js$script,domain=synonimy.pl`

(+belka info o ciastkach)

**Comment by krystian3w** [comment]
Belki cookies nie ma - kiboke używa generyka `###ciasteczka_alert` a dodatek niby zapobiegawczo klika w "Wiem, zamknij", nie filtrujesz elementów to generujesz FP.
