### ISSUE TITLE
*.krzemieniewo.pl (13 stron)

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19183]
> Serwis używa cookies aby zapamiętać otwartą sesję i ewentualne dane o logowaniu.
> Brak zmiany ustawień przeglądarki oznacza zgodę na to.

bip.gops.krzemieniewo.pl
bip.gck.krzemieniewo.pl
bip.przedszkole.krzemieniewo.pl
bip.przedszkole2.krzemieniewo.pl
bip.zlobek.krzemieniewo.pl
bip.sppawlowice.krzemieniewo.pl
bip.spdrobnin.krzemieniewo.pl
bip.zsgarzyn.krzemieniewo.pl
bip.spnowybelecin.krzemieniewo.pl
archiwumbip.krzemieniewo.pl
start.krzemieniewo.pl
sport.krzemieniewo.pl
oswiata.krzemieniewo.pl

![screenshoot_140867](https://user-images.githubusercontent.com/75935068/111594946-f137aa00-87cb-11eb-9496-7e5c1fb996be.png)

![screenshoot_140874](https://user-images.githubusercontent.com/75935068/111595085-0ca2b500-87cc-11eb-8319-9efb806f9f7e.png)

![screenshoot_140877](https://user-images.githubusercontent.com/75935068/111594982-f8f74e80-87cb-11eb-8cbb-4ea2f0470684.png)

**Comment by strict-block** [comment]
Ze startem / sportem / oświatą się nie uda, wytnie informacje o CMS-ie :/ (źródło sztywnego osadzania komunikatu).
