### ISSUE TITLE
polandia.nl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19189]
![Zrzut ekranu z 2021-03-18 09-52-06](https://user-images.githubusercontent.com/36385327/111598590-ad46a400-87cf-11eb-94fe-c9371ec4175b.png)

**Comment by seba2282** [comment]
`polandia.nl###ipsLayout_footer`
`polandia.nl##[href="https://facebook.com/forumpolandia"]`
`polandia.nl##.cSignInTeaser_right.ipsGrid_span4 > form`
`polandia.nl##li.ipsResponsive_block.ipsBox.ipsWidget_vertical.ipsWidget > .ipsType_richText.ipsPad.ipsWidget_inner`
`polandia.nl##li.ipsBox.ipsWidget_vertical.ipsWidget:nth-of-type(3)`
`polandia.nl##.mfb-component__wrap`
`polandia.nl##[href="https://www.p-tv.nl/"]`
`polandia.nl###elRegisterSocial`
