### ISSUE TITLE
sne.olsztyn.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19181]
![screenshoot_140215](https://user-images.githubusercontent.com/75935068/111594388-4a530e00-87cb-11eb-84d2-821b5fde9304.png)

**Comment by strict-block** [comment]
Chyba strony hostingu fc.pl mają awarię 🤣.

**Comment by felix-22** [comment]
U ciebie znowu awaria, a umnie działa, tak jak tu: https://github.com/MajkiIT/polish-ads-filter/issues/19088#issuecomment-802191621

- może były awarie, ale już minęły
- albo ci łącze szwankuje i tylko u ciebie jest awaria


- gdy masz awarię to sprawdzaj czy to awaria tylko u ciebie czy u wszystkich, na tej stronie: https://downforeveryoneorjustme.com/

**Comment by strict-block** [comment]
Po dwóch VPN ach też padała i wymyszała adres `sne.fc.pl`, jakby awaryjny darmowy np. sklep-1234.home.pl a normalnie powinien działać pod `sklepki-budowlany-i-rolniczy.pl`
