### ISSUE TITLE
gazetabaltycka.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19187]
![Zrzut ekranu z 2021-03-18 09-50-12](https://user-images.githubusercontent.com/36385327/111598325-68227200-87cf-11eb-8417-d4a043c4c43d.png)

**Comment by seba2282** [comment]
`gazetabaltycka.pl###header3-1-right`
`gazetabaltycka.pl##[href="http://www.motoreplika.pl"]`
`gazetabaltycka.pl##div.widget_text.section:nth-of-type(2)`
`gazetabaltycka.pl##div.widget_text.section:nth-of-type(6)`
