### ISSUE TITLE
igomedia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19190]
![Zrzut ekranu z 2021-03-18 09-53-11](https://user-images.githubusercontent.com/36385327/111598692-c3ecfb00-87cf-11eb-89a2-c52f8fd30a7a.png)

**Comment by krystian3w** [comment]
Na pewno dobra nazwa domeny - niby coś padło i widzę taki "crap":

![obraz](https://user-images.githubusercontent.com/35370833/111703431-e9b0e900-883d-11eb-9931-968e2cbd0711.png)

**Comment by xMaap** [comment]
Ucięło "i".

**Comment by seba2282** [comment]
`www.igomedia.pl##ul.links-list:nth-of-type(1)`
