### ISSUE TITLE
tele-wizja.com

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#1919]
Reklamy

http://tele-wizja.com/tvp1.html

**Comment by FadeMind** [comment]
![screenshot_20170110_184654](https://cloud.githubusercontent.com/assets/9846948/21817691/4afa66ac-d765-11e6-8d58-1dea80b04240.png)
![screenshot_20170110_184739](https://cloud.githubusercontent.com/assets/9846948/21817696/4ef19dfc-d765-11e6-9296-a2de19fc3060.png)

**Comment by xxcriticxx** [comment]
@FadeMind ???

**Comment by FadeMind** [comment]
@xxcriticxx tyle tego tam jest xD

**Comment by xxcriticxx** [comment]
@FadeMind rozumiem oco chodzi tobie ale prosty uzytkownik niewie nawet naco patrzy podaj jakies reguly a @mathew85 i ja potetstuje (sorry za blendy w pisowni)

**Comment by FadeMind** [comment]
```
||js-agent.newrelic.com^
###ad_overlay_countdown
###ad_overlay_content
###ad_overlay
###ad_footer
||s10.histats.com^
.me/ads/
||www.google-analytics.com^
||t.mdn2015x2.com^
/show_ads_
||api.wipmania.com^
||st.chatango.com/*/*/*/id.html$subdocument
||imqkdsdgfygm.com^$third-party
||ormnduxoewtl.com^$third-party
||c2.popads.net^
||clksite.com^
||c1.popads.net^
tele-wizja.com##.col-md-9
||imqkdsdgfygm.com^$third-party
||ormnduxoewtl.com^$third-party
||c2.popads.net^
||c1.popads.net^
||stat.4u.pl^
||widgets.amung.us^
||c1.popads.net^
||adstat.4u.pl^
||livelooker.com/img/$image
||clksite.com^
```

**Comment by xxcriticxx** [comment]
@FadeMind zaduzo blokujesz niema PLAY guzika i chatroom wcielo

**Comment by FadeMind** [comment]
@xxcriticxx u mnie działa odtwarzacz. Chatroom ukryłem celowo. :package:

**Comment by xxcriticxx** [comment]
mojm zdaniem za duzo niech @mathew85 potestuje

tvp1 niema guzika play 

to jescze zostalo na dole 

![capture](https://cloud.githubusercontent.com/assets/15007183/21819126/66da8e6a-d738-11e6-8f1a-ae85f8c744c4.PNG)

**Comment by FadeMind** [comment]
Zamknij srebrnym guzikiem popup i będziesz mieć dostęp do odtwarzacza.

**Comment by mathew85** [comment]
U mnie na domyślnych filtrach w zasadzie to tylko dwa banery nie są blokowane + reklama z odtwarzacza.
![image](https://cloud.githubusercontent.com/assets/11385099/21820837/983ba348-d771-11e6-8177-85c1d03af60e.png)

Filtry @FadeMind usuwają banery, ale nie reklamę z odtwarzacza. Pytanie czy ją da się też jakoś usunąć?

**Comment by FadeMind** [comment]
Free Sport jest osadzony z JS. @MajkiIT lub @F4z mogą ogarnąć :)

**Comment by xxcriticxx** [comment]
@FadeMind thx man

**Comment by F4z** [comment]
Żeby zablokować reklamę, która jest w odtwarzaczu z TVP1 można użyć tej reguły:
`castto.me##[id^="floatLayer"]`

Żeby zablkować reklamę "graj w gry" -  `||tele-wizja.com/gamehags.jpg` lub tak
` tele-wizja.com##a[href^="https://gamehag.com/r/"]`
albo ogólnie - `##a[href^="https://gamehag.com/r/"]`

Do zablokowania reklamy "SUPER BONUS..."
`tele-wizja.com##a[href^="http://affiliates.bet-at-home.com/processing/clickthrgh.asp"]`
albo ogólnie - `##a[href^="http://affiliates.bet-at-home.com/processing/clickthrgh.asp"]`

Ten live looker to w sumie jest serwis z różnymi transmisjami, widziałem taki baner na niejednej stronie, nie wiem czy to jest reklama, ale można to zablokować tą regułą:
`||livelooker.com/img/button$image`
lub
`##a[href="http://www.livelooker.com"]`

Wszystkie reguły:
`castto.me##[id^="floatLayer"]`
`##a[href^="https://gamehag.com/r/"]`
`##a[href^="http://affiliates.bet-at-home.com/processing/clickthrgh.asp"]`
i livelooker
`##a[href="http://www.livelooker.com"]`

**Comment by F4z** [comment]
Do odtwarzacza z Polsatem jeszcze ta reguła:
`privatestream.tv##[id^="timer"]`

**Comment by FadeMind** [comment]
@F4z Dziękuję.
![s](https://cdn.meme.am/cache/instances/folder128/400x/37900128.jpg)

**Comment by F4z** [comment]
Odtwarzacz z TVNem:
`tvope.com##[id^="ads"]`

Jak ktoś jeszcze znajdzie reklamę albo pozostałość po reklamie w jakimś odtwarzaczu, to proszę pisać :)

**Comment by FadeMind** [comment]
@F4z  jeszcze tu jest jakaś pozostałość (sam X)  `http://tele-wizja.com/polnewss.html`

**Comment by F4z** [comment]
@FadeMind dzięki.
`dotstream.tv##[id^="timer"]`

**Comment by FadeMind** [comment]
@F4z 
Jak już przy streamach jesteśmy:
```
http://nowwatchtvlive.co/01-tvn-online-za-darmo-tvn-hd-telewizja-live/
```

**Comment by mathew85** [comment]
@F4z   :thumbsup:

**Comment by F4z** [comment]
@FadeMind jeśli chodzi o reklamy to te reguły powinny wystarczyć:
`||abcast.net/p.js$script`
`||fullon.tv/matuma300x250.php$subdocument`
`||nowwatchtvlive.co/matomyads$subdocument`
`||cloudfront.net^$script,domain=telewizja-live.com`
`tvtoss.me##.bannerfloat`

Zauważyłem też czasami wykrycie adblocka.
Te reguły powinny sobie z tym poradzić, ale wymagają jeszcze przetestowania (nie działają w Adblocku):
`abcast.net##span[id="nf37"]`
`abcast.net##body > #nf37 ~ span:style(display: block !important;)`

**Comment by MajkiIT** [comment]
@F4z te reguły powyżej to zbiorcze?

**Comment by MajkiIT** [comment]
`||abcast.net/p.js$script`
`||fullon.tv/matuma300x250.php$subdocument`
`||nowwatchtvlive.co/matomyads$subdocument`
`||cloudfront.net^$script,domain=telewizja-live.com`
`tvtoss.me##.bannerfloat`
`castto.me##[id^="floatLayer"]`
`##a[href^="https://gamehag.com/r/"]`
`##a[href^="http://affiliates.bet-at-home.com/processing/clickthrgh.asp"]`
`##a[href="http://www.livelooker.com"]`

**Comment by FadeMind** [comment]
@MajkiIT 
Dodaj proszę jeszcze drobiazg:
```
dotstream.tv##[id^="deny"]
```
Ukrywa wyświetlaną informację na odtwarzaczu
![screenshot_20170111_112205](https://cloud.githubusercontent.com/assets/9846948/21844781/362844fc-d7f0-11e6-9e07-28d5111db74d.png)

**Comment by MajkiIT** [comment]
@FadeMind ok dzięki
