### ISSUE TITLE
bip.biblioteka.lodz.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19203]
![screenshoot_144705](https://user-images.githubusercontent.com/75935068/111752985-9f0f8b00-8896-11eb-9085-2807016799ea.png)

**Comment by strict-block** [comment]
Jak dla mnie to jak kolejny przykład stron "GOPS" https://github.com/MajkiIT/polish-ads-filter/issues/19097#issuecomment-802155036 z brakiem `/index2.php` z np. aktualnościami "wieści z biblioteki".

**Comment by felix-22** [comment]
Tak też podejrzewałem ale na wszelki wypadek wrzuciłem żebyś się upewnił.
