### ISSUE TITLE
bollywood-hollywood.skubacz.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19202]
czy to się kwalifikuje, czy nie, ja tam nie wiem....jakby podobne/podchodzi pod cookies/gdpr, coś tam gdzieś chyba chce  zapisywać, coś wspomina o prywatności / trybie prywatnym

![screenshoot_144360](https://user-images.githubusercontent.com/75935068/111752177-a8e4be80-8895-11eb-8dcd-d5c92348ad3f.png)

**Comment by strict-block** [comment]
Nie widzę tego, wygląda to na komunikat że twoja przeglądarka za mocno dba o prywatność i bazy "IndexedDB" uznaje za zagrożenie gorsze od śledzenia ciasteczkami?

Niby można próbować używać sessionStorage zamiast cookies.

Pewnie z zablokowanymi nie działa np. koszyk.

**Comment by felix-22** [comment]
Jak bot wszedł to mu się pokazało, ale też tego nie widzę, gdy wejdę normalnie sam na stronę.

**Comment by strict-block** [comment]
To może lepiej zostawić, nie straszą przy zbilansowanej prywatności, to może bot używa internet explorer do renderowania, a tam niby kiepskie wsparcie zamiennika cookies - przynajmniej jak ktoś z XP lub Visty zamawiałby szamę to będzie widział, że nie powinien używać IE8/IF9, jakby to było źródło po zbyt agresywnej blokadzie "IndexedDB".

**Comment by felix-22** [comment]
Jak chcesz, jak tam nie mam zielonego pojęcia.
