### ISSUE TITLE
infotex.com.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19200]
![screenshoot_144131](https://user-images.githubusercontent.com/75935068/111752007-72a73f00-8895-11eb-9af9-949276739bc3.png)

**Comment by strict-block** [comment]
Niezgodność domeny z nazwą, sprawdź co bot otwierał pod numerem "`144131`".

**Comment by felix-22** [comment]
Ok już poprawione.
