### ISSUE TITLE
twin.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19208]
![screenshoot_145395](https://user-images.githubusercontent.com/75935068/111869026-92199700-897d-11eb-95ef-0aa53ed761e8.png)

**Comment by strict-block** [comment]
Mnie działa to:
```
instagram.com##body[style*="overflow: hidden;"]:style(overflow-y: scroll !important;)
instagram.com##div[role="presentation"]:has(> div[role="dialog"] h3 ~ div > a[href="/legal/cookies/"])
```

Więc musisz zapisać stronę do zip w trybie bota, bo nie widzę testu A/B, że przewijanie jest inaczej zbudowane lub link cookies zginął lub był gdzieś indziej w drzwie DOM.

Opcjonalnie screen później lub dopisek, spróbujcie zrobić by znikało szybciej niż sekundę po załadowaniu.

**Comment by strict-block** [comment]
Sprawdź czemu botowi to nie odpowiada:
```
instagram.com##body[style*="overflow: hidden;"]:style(overflow-y: scroll !important;)
instagram.com##div[role="presentation"]:has(> div[role="dialog"] h3 ~ div > a[href="/legal/cookies/"])
```

https://github.com/MajkiIT/polish-ads-filter/blob/0e9343397f01984743caf70f2da19e78af07e7d4/cookies_filters/cookies_uB_AG.txt#L190-L191

filtry raczej są dość stare - więc jak to nie test A/B (nowa metoda blokady przewijania / link do polityki cookies jest w innym miejscu (drzewo dom)) to może CPU nie wyrabia.

Raczej nie widzę szybszego bezpiecznego filtru, pewnie tam nie ma tego w kodzie liniowo.

**Comment by felix-22** [comment]
Gdy wchodzę sam z lepszego komputera, to komunikat jest ukrywany, więc faktycznie możliwe, że cpu nie wyrobił, lub/i strona nie wyrobiła i się zbyt długo ładowała / przylagowała, i nie zdążyła się załadować, a komunikat zostać ukryty, zanim bot zrobił zrzut ekranu, to samo czasem dzieje się gdy bot wchodzi na strony blogów `pinger.pl`.

Przy okazji, odnośnie filtrów, które podałeś, to nie tylko lista ciasteczkowa ukrywa ten komunikat, bo także Polska Zgoda Ciasteczkowa go ukrywa.

**Comment by strict-block** [comment]
Tylko fb i messenger ma kliker, by się posty/wiadomości(interfejs) ładowały dla zalogowanych.

Raczej to przypadkowa korelacja, że Insta podkrada cookies o akceptacji popupa fb/messenger.
