### ISSUE TITLE
rezerwacje.naturhouse-polska.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19228]
![screenshoot_151105](https://user-images.githubusercontent.com/75935068/111901658-c2bf0680-8a39-11eb-8ed3-f9b37242c5e7.png)

**Comment by strict-block** [comment]
Raczej zostaje do ręcznej akceptacji, formularz sam się nie wypełni danymi to i pole można kliknąć.

PCC/PCZ nie przewiduje zaznaczania tego (pociągałoby to za sobą wszelkie formularze rejestracji i newsletterów).

**Comment by felix-22** [comment]
Ok, to w takim razie zamykam.
