### ISSUE TITLE
*gov.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19236]
http://www.gugik.gov.pl
```
www.gugik.gov.pl##.fb
www.gugik.gov.pl##.yt
```
https://granica.gov.pl/
`granica.gov.pl###logoSocial
`

https://www.malopolska.uw.gov.pl
```
www.malopolska.uw.gov.pl##[href="https://www.facebook.com/Ma%C5%82opolski-Urz%C4%85d-Wojew%C3%B3dzki-1322952864433993/"]
www.malopolska.uw.gov.pl##[href="https://www.instagram.com/muwkrakow"]
www.malopolska.uw.gov.pl##.rowfix.col-md-12 > [href="https://www.youtube.com/user/MalopolskiUrzadWojew"]
www.malopolska.uw.gov.pl##[href="https://twitter.com/Malopolski_UW"]
```
https://www.lodzkie.eu/
```
www.lodzkie.eu##[href="https://www.instagram.com/luw_lodz/"]
www.lodzkie.eu##[href="https://www.facebook.com/%C5%81%C3%B3dzki-Urz%C4%85d-Wojew%C3%B3dzki-284612289166/"]
```
https://wielkopolska.policja.gov.pl
`wielkopolska.policja.gov.pl###social`

https://www.gdansk.uw.gov.pl
`www.gdansk.uw.gov.pl##.header-info.header-ico
`
https://www.uzp.gov.pl

```
www.uzp.gov.pl##[href="https://www.youtube.com/channel/UCUNA8W3OduntyBa4cWlWSbw"]
www.uzp.gov.pl##[href="https://www.linkedin.com/company/uzp/"]

```

https://konsument.gov.pl
```
konsument.gov.pl##div.delay-000.vc_col-sm-3.vc_column_container.wpb_column:nth-of-type(1)
konsument.gov.pl##div.delay-000.vc_col-sm-3.vc_column_container.wpb_column:nth-of-type(3)
konsument.gov.pl##.NoEffect.ih-item > [href="https://www.facebook.com/EuropejskieCentrumKonsumenckie/"]
```

https://udsc.gov.pl
`udsc.gov.pl##.yt
`
https://www.poznan.uw.gov.pl
`www.poznan.uw.gov.pl##ul.shortcuts-icons:nth-of-type(6)`

**Comment by seba2282** [comment]
Gdzie dodałeś te reguły? @xMaap

**Comment by xMaap** [comment]
@seba2282 ja? W Moje filtry
![Zrzut ekranu z 2021-03-21 19-15-51](https://user-images.githubusercontent.com/36385327/111916164-ea35c380-8a79-11eb-8f4d-528aa79f52bd.png)

**Comment by seba2282** [comment]
@xMaap Ja wiem to. Myśl, że do polskich filtrów dodajesz.

**Comment by seba2282** [comment]
+  http://www.gugik.gov.pl
`www.gugik.gov.pl##.social`
`www.gugik.gov.pl##[href="http://www.asgeupos.pl"]`

+ https://granica.gov.pl/ 
`granica.gov.pl###logoSocial`
`granica.gov.pl##.flexMenu > li`
`granica.gov.pl###kolumna33a`

+ https://www.malopolska.uw.gov.pl 
`www.malopolska.uw.gov.pl##.rowfix.hidden-xs.col-sm-6.col-md-6 > .rowfix.col-md-12`
`www.malopolska.uw.gov.pl##div.banner_button:nth-of-type(18)`
`www.malopolska.uw.gov.pl##div.banner_button:nth-of-type(19)`

+ https://www.lodzkie.eu/
`www.lodzkie.eu###header_right`
`www.lodzkie.eu##.banners_bottom`
`www.lodzkie.eu##div.footer_dept [href="http://www.sse.lodz.pl/"]`

+ https://wielkopolska.policja.gov.pl
`wielkopolska.policja.gov.pl##div:nth-of-type(5)`
`wielkopolska.policja.gov.pl###footer-bottom`

+ https://www.gdansk.uw.gov.pl
`www.gdansk.uw.gov.pl##.header-infos`

+ https://www.uzp.gov.pl
`www.uzp.gov.pl##.clearfix.header__top__links > li`
`www.uzp.gov.pl##.footer__copyright`

+ https://konsument.gov.pl
`konsument.gov.pl##div.delay-000.vc_col-sm-3.vc_column_container.wpb_column:nth-of-type(1)`
`konsument.gov.pl##div.delay-000.vc_col-sm-3.vc_column_container.wpb_column:nth-of-type(3)`
`konsument.gov.pl##.NoEffect.ih-item > [href="https://www.facebook.com/EuropejskieCentrumKonsumenckie/"]`

+ https://udsc.gov.pl 
`udsc.gov.pl##.yt`
`udsc.gov.pl##.designby`

+  https://www.poznan.uw.gov.pl
www.poznan.uw.gov.pl##ul.shortcuts-icons:nth-of-type(6)`

**Comment by krystian3w** [comment]
Pewnie propozycje z racji 150 zgłoszeń, na razie raczej nie ma chętnych i wystarczająco umiejących w tworzenie ścieżek.
