### ISSUE TITLE
kobieta.pl + elleman.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19239]
https://www.kobieta.pl
![Zrzut ekranu z 2021-03-21 22-49-00](https://user-images.githubusercontent.com/36385327/111921954-a5208a00-8a97-11eb-9653-124c90c54fef.png)
https://www.elleman.pl
![Zrzut ekranu z 2021-03-21 22-49-18](https://user-images.githubusercontent.com/36385327/111921969-b5d10000-8a97-11eb-82cf-fc89c37d42b3.png)

`national-geographic.pl,kobieta.pl,elleman.pl##.social-media-fix
`

**Comment by seba2282** [comment]
`www.kobieta.pl##.footermenu-social-label`
`www.elleman.pl##.elle-footer-right`
`pl##.social-media-fix`

Może tak? @xMaap

**Comment by xMaap** [comment]
@seba2282 u mnie ##.social-media-fix wycina wszystkie social.

**Comment by seba2282** [comment]
Czyli działa. Dałem na razie tutaj pod postem na tylko pl. Globalnie nie chcę na razie. Nie wiem jaka teraz ci pasuje. Globalnie czy tylko na razie PL. @xMaap
