### ISSUE TITLE
hajnowka.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19238]
`hajnowka.pl##[href="https://www.facebook.com/hajnowkawita"]`

**Comment by seba2282** [comment]
`hajnowka.pl##.nav-link-http--mapainspire-hubpl--hajnowka.nav-link`
`hajnowka.pl##.nav-link-http--vps450175ovhnet-kamera2html.nav-link`
`hajnowka.pl##.block-views-blockpartnerzy-block-1.block-views.block.views-element-container`
`hajnowka.pl###block-szablon-podpis > .content > .field__item.field--label-hidden.field--type-text-with-summary.field--name-body.field.text-formatted.clearfix [href]`
`hajnowka.pl##[href="https://www.facebook.com/hajnowkawita"]`
