### ISSUE TITLE
mistrzowiebezpieczenstwa.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1923]
`http://mistrzowiebezpieczenstwa.wp.pl/artykul/odpowiedni-tor-jazdy-technika-jazdy?utm_source=SGWP&utm_medium=zajawka&utm_campaign=editorial`

![capture](https://cloud.githubusercontent.com/assets/15007183/21825613/723f959c-d752-11e6-85b3-2b7f6d93f96c.PNG)

**Comment by MajkiIT** [comment]
Ok dodam. Dzięki
