### ISSUE TITLE
pl.canalplus.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19237]
Cookies + Social

https://pl.canalplus.com/lp/orly/
`pl.canalplus.com##.social-ico-wrapper`
`pl.canalplus.com##.cookies`
![Zrzut ekranu z 2021-03-21 16-40-07](https://user-images.githubusercontent.com/36385327/111911098-54dc0480-8a64-11eb-9395-fbfe8cfdb7ca.png)

**Comment by seba2282** [comment]
`pl.canalplus.com##.cookies`
`pl.canalplus.com##.footer-sekcja-4`

**Comment by krystian3w** [comment]
flaga powinna zostać to nie social

**Comment by seba2282** [comment]
@krystian3w nie mogę się pozbyć napisu nad flagą po zastosowaniu reguły @xMaap dla social.

**Comment by krystian3w** [comment]
`##.footer-sekcja-4 > p:nth-of-type(1)`

`#?#.footer-sekcja-4 > p:-abp-has(+ .social-ico-wrapper)`

można też nadmiarowo robić cofanie w górę (chyba dalej niekompatybilne z ABP):

`##.footer-sekcja-4 > .social-ico-wrapper:upward(1) > p:nth-of-type(1)`

**Comment by seba2282** [comment]
`pl.canalplus.com##.cookies`
`##.footer-sekcja-4 > p:nth-of-type(1)`
`pl.canalplus.com##.social-ico-wrapper`

**Comment by Lukjan38** [comment]
na stronie glownej, pojawia sie ciemne tlo, nie mozna potwierdzic cookies.

**Comment by krystian3w** [comment]
Raczej reklama.

**Comment by seba2282** [comment]
To ty nie masz jak dodać tej reguły, tam gdzie powinna?
