### ISSUE TITLE
[nsfw] playboy.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1924]
`http://www.playboy.pl/ludzie/531/wywiady-playboya-bill-gates`

![screenshot_20170111_141823](https://cloud.githubusercontent.com/assets/9846948/21849995/d4f30cc6-d808-11e6-8d51-5da6553a2494.png)

```
||mr1-1a.exs.pl^
```

**Comment by MajkiIT** [comment]
`||exs.pl/$script`
