### ISSUE TITLE
agrohandel.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19255]

**Comment by krystian3w** [comment]
Trzeba pomyśleć nad usunięciem: 
https://github.com/MajkiIT/polish-ads-filter/blob/f60069d82fe1517ea27fc88e823d0ae66d198262/cookies_filters/adblock_cookies.txt#L2954

lub przerobie to na:

`pl##body:not([style*="overflow"]) cadre_alert_cookies`
