### ISSUE TITLE
herbapol.com.pl

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#19284]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/112174319-9bf9ff00-8bf6-11eb-9d9b-1c0c4389a97a.png)

### Link bezpośredni 

https://www.herbapol.com.pl/

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. 
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda (2021.03.14.0)
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List
11. AdGuard Tracking Protection
12. AdGuard Base
13. AdGuard Mobile Ads
14. Fanboy’s Social 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
`###pop`
