### ISSUE TITLE
pl.tommy.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19299]

**Comment by krystian3w** [comment]
@hawkeye116477 pamiętasz po co tam używamy `visibility: hidden`?

https://github.com/MajkiIT/polish-ads-filter/blob/f60069d82fe1517ea27fc88e823d0ae66d198262/cookies_filters/cookies_uB_AG.txt#L328

**Comment by hawkeye116477** [comment]
Nie

**Comment by krystian3w** [comment]
Aha czyli pewnie jakiś eksperyment z AdGuard albo raczej się nie dowiemy co bugowało się w kodzie z 2018.
