### ISSUE TITLE
alejabielany.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19292]
https://www.alejabielany.pl/pl-pl/stores/deichmann

fb ( po lewo ) oraz reszta ( na dole )

**Comment by seba2282** [comment]
`www.alejabielany.pl##.icon-facebook-with-circle.store-centre--social--link`
`www.alejabielany.pl##.footer--column.is-12-mobile.is-full-tablet.is-one-third-desktop.column`
`www.alejabielany.pl##.footer--copyright`
