### ISSUE TITLE
nhl.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#1929]
Baner u góry strony + reklamy między postami.

![image](https://cloud.githubusercontent.com/assets/11385099/21862787/fc59ba08-d83a-11e6-88d4-f8927778a48b.png)

**Comment by FadeMind** [comment]
```
||adglare.org^$image
```

**Comment by xxcriticxx** [comment]
@mathew85 kup sobie chromebooka

**Comment by F4z** [comment]
Można też skrypt zablokować.
`||nhlpl.engine.adglare.org^$script,domain=www.nhl.pl`
albo nawet bardziej ogólnie:
`||adglare.org^$third-party`

Żeby ukryć post z reklamą, do uBlocka można dodać tę regułę:
`nhl.pl##.ipbtable:has(div[align="center"] > script[src^="//nhlpl.engine.adglare.org"])`

**Comment by MajkiIT** [comment]
@F4z Dzięki

**Comment by mathew85** [comment]
@xxcriticxx potrzebuje coś kupić, ale chce z normalnym systemem :)

**Comment by xxcriticxx** [comment]
na chrombook zamontujesz ubuntu 16.04 bez problemu
