### ISSUE TITLE
sklepbiegacza.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19309]
" Bądź na bieżąco " ( na dole )

**Comment by seba2282** [comment]
`sklepbiegacza.pl##.auth__other`
`sklepbiegacza.pl##.auth__methods`
`sklepbiegacza.pl##.footer__shops`
`sklepbiegacza.pl##.footer__opinions`
`sklepbiegacza.pl##[href="https://www.facebook.com/messages/t/234418653277851"]`
`sklepbiegacza.pl##.footer__header--center.footer__header`
