### ISSUE TITLE
butomania.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19307]
( na dole )

**Comment by seba2282** [comment]
`www.butomania.pl###client_new_social`
`www.butomania.pl##div.menu_button_wrapper:nth-of-type(3)`
`||www.butomania.pl/ajax/poweredby_IdoSell_Shop_white.svg$image`
`www.butomania.pl##[href="http://www.opineo.pl/opinie/butomania-pl"]`
