### ISSUE TITLE
Proszę o pomoc

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#1930]
Nie mogę odtworzyć filmiku na tej stronie http://www.fcinter1908.it/video/video-kondogbia-che-numero-thereau-mandato-letteralmente-al-bar-boato-dello-stadio/
Pamiętam, że jakieś półtora miesiąca temu mogłem odtwarzać filmiki na tej stronie.
@F4z @MajkiIT Moglibyście proszę mi pomóc z dodaniem odpowiedniej reguły?

**Comment by F4z** [comment]
@adreporter czy po dodaniu tych reguł działa?
`@@||c.betrad.com/geo/h1.js$script,domain=www.fcinter1908.it|video.gazzanet.gazzetta.it`
`@@||c.betrad.com/pub/*/*.js$script,domain=www.fcinter1908.it|video.gazzanet.gazzetta.it`

**Comment by adreporter** [comment]
@F4z Niestety nie. Jest sam obraz bez przycisku odtwarzania.
Może to "wina" jakiejś reguły znajdującej się w filtrach których używam:
![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/21867642/5dcac50c-d84f-11e6-8ebc-7891b14384e5.PNG)
![przechwytywanie2](https://cloud.githubusercontent.com/assets/18214146/21867650/642e6ca0-d84f-11e6-94f7-ed30d22e181c.PNG)
![przechwytywanie3](https://cloud.githubusercontent.com/assets/18214146/21867654/676a9290-d84f-11e6-979b-ec5820d2d530.PNG)

**Comment by adreporter** [comment]
Ten filmik pochodzi od strony http://video.gazzetta.it/ na której niestety nie da się odtworzyć żadnego filmiku.

**Comment by adreporter** [comment]
Przykład: http://video.gazzetta.it/2009-beckham-debuttava-oggi-col-milan-riguarda-qualche-prodezza/41090e58-d74e-11e6-a8ec-661998b7c716?playlistId=fbc56f68-7fe6-11e5-8d3c-99fdc4027405&vclk=HP

**Comment by F4z** [comment]
@adreporter ok, a z tymi regułami?
`@@||betrad.com/geo/h1.js$script,domain=www.fcinter1908.it|gazzetta.it`
`@@||betrad.com/pub/*/*.js$script,domain=www.fcinter1908.it|gazzetta.it`

**Comment by adreporter** [comment]
@F4z Niestety też nie działa.

**Comment by F4z** [comment]
U mnie to wygląda w ten sposób, że pojawia się komunikat na górze, chyba o ciasteczkach i jak zjadę niżej to znika i strona się ponownie ładuje i filmy działają.

**Comment by adreporter** [comment]
Hehe wyobraź sobie, że jak mi napisałeś że dostajesz komunikat o ciasteczkach to od razu pomyślałem o tym, że mam zainstalowany dodatek "I don't care about cookies" który przed chwilą skasowałem i teraz filmik działa. Trzeba będzie zgłosić błąd do autora tego dodatku. Dziękuję za pomoc.

**Comment by F4z** [comment]
@adreporter nie ma za co, dobrze że udało się rozwiązać problem :)
