### ISSUE TITLE
artyferia.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19319]
pinterest ( na dole )

**Comment by seba2282** [comment]
Tu też nie mam pojęcia.
![bug1](https://user-images.githubusercontent.com/16944478/112875589-aa4b8d80-90c4-11eb-8d26-ae764480d32a.png)
Wyłączyłem i mój filtr i te z firm trzecich, co blokują zawartość i tak sądzę, że któryś z polskich to blokuje. I tu potrzebuję do pomocy @krystian3w i pozostałą ekipę do polskich filtrów. Wykluczyłem mój filter, bo mam go wyłączony.

**Comment by krystian3w** [comment]
Wyklucz listy hosts i specyficzne językowe.

Potem wyklucz błędy w Fanboy Annoyance.

**Comment by seba2282** [comment]
> Wyklucz listy hosts i specyficzne językowe.
> 
> Potem wyklucz błędy w Fanboy Annoyance.

Mogę spróbować, @krystian3w

**Comment by seba2282** [comment]
+ EasyList Cookie 
+ Fanboy’s Annoyance 
Są winowajcami. 


`artyferia.pl##[href="http://www.dotpay.pl/"]`
`artyferia.pl##.fa-pinterest-square.fa`   - Adguard social to też ma.

**Comment by krystian3w** [comment]
to jak to nie button do udostępniania, to źle ktoś go dodał do `AdGuard Social Media`.

Jak ci 2 miesiące oczekiwania na naprawę nie przeszkadzają to wklej tu: https://github.com/easylist/easylist/issues/new

Jako błąd podawaj używanie `EasyList Cookie`, bo mają tendencje naprawy w złych plikach, jak to niby też błąd powiele fanboy annoyance (to jest jak kopiowanie polskich ciasteczek do polskiego EI bez listy kiboke).

**Comment by seba2282** [comment]
> `artyferia.pl##.fa-pinterest-square.fa` - Adguard social to też ma.

Mam na myśli, ta reguła jest u adguard social na ten pinterest.

**Comment by krystian3w** [comment]
No to źle wycina, oni nie wycinają tego.

**Comment by seba2282** [comment]
> to jak to nie button do udostępniania, to źle ktoś go dodał do `AdGuard Social Media`
> No to źle wycina, oni nie wycinają tego.

@AdamWr
