### ISSUE TITLE
inbluobuwie.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19313]
( na dole ) + fb " Śledź nasz profil! "

**Comment by seba2282** [comment]
`inbluobuwie.pl###client_new_social`
`inbluobuwie.pl##.button3_sub`
`||inbluobuwie.pl/ajax/poweredby_IdoSell_Shop_black.svg$image`

**Comment by krystian3w** [comment]
to logowanie `###client_new_social`?
