### ISSUE TITLE
spidersweb.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1931]
Reklama - `http://www.spidersweb.pl/`
![image](https://cloud.githubusercontent.com/assets/11742596/21866361/2c943b62-d84a-11e6-981a-e42ad3027b82.png)

Na przykład:
`||spidersweb.pl/reklamy/$subdocument`

**Comment by MajkiIT** [comment]
@F4z dzięki

**Comment by spidersweb-header** [comment]
#2337 ?
