### ISSUE TITLE
obi.pl

### ISSUE THREAD

**Issue by Lukjan38** [MajkiIT/polish-ads-filter#19325]
jest komunikat, nie mozna wylaczyc.

**Comment by xMaap** [comment]
Na stronie głównej widzisz komunikat?

**Comment by Lukjan38** [comment]
tak

![obi](https://user-images.githubusercontent.com/17565773/112744341-9e19e000-8f9f-11eb-9d7d-f2bff1c33d4b.jpg)

**Comment by xMaap** [comment]
U mnie tego nie ma. Jakie masz filtry?

EasyLis konkretnie /marketing-banners/* blokuje treść
![Zrzut ekranu z 2021-03-28 09-06-04](https://user-images.githubusercontent.com/36385327/112745189-df61be00-8fa6-11eb-9045-b1d6b3259e6c.png)
![Zrzut ekranu z 2021-03-28 09-05-31](https://user-images.githubusercontent.com/36385327/112745193-e25cae80-8fa6-11eb-81d5-391a798e5cb1.png)

**Comment by Lukjan38** [comment]
![fil](https://user-images.githubusercontent.com/17565773/112745323-c0176080-8fa7-11eb-932f-932ffb9051a5.jpg)

**Comment by xMaap** [comment]
Nic nie ma.
https://majkiit.github.io/polish-ads-filter/
Sprawdź 
![Zrzut ekranu z 2021-03-28 09-38-39](https://user-images.githubusercontent.com/36385327/112745537-7e87b500-8fa9-11eb-9a74-7e30353bedde.png)
![Zrzut ekranu z 2021-03-28 09-39-24](https://user-images.githubusercontent.com/36385327/112745539-80ea0f00-8fa9-11eb-828f-384903c975fb.png)

**Comment by Lukjan38** [comment]
co, sprawdzic?

**Comment by felix-22** [comment]
- też mam czasem glitch z pustym komunikatem ciasteczkowym, jak Lukjan38: https://github.com/MajkiIT/polish-ads-filter/issues/19325#issuecomment-808854750
- ale nie za każdym razem, na kilkanaście wejść na stronę, pojawił się ze 2-3 razy
- to jest ten komunikat ciasteczkowy, czasem jest wycięty tylko tekst i zostaje samo puste okno:

![capture_001_28-03-2021_10-42-25](https://user-images.githubusercontent.com/75935068/112746892-4cc71c00-8fb2-11eb-9734-0b4fd26b9533.png)

**Comment by Lukjan38** [comment]
zrobilem czyszczenie, i jest ok.

**Comment by felix-22** [comment]
Lukjan38 i tak może lepiej nie zamykaj tego zgłoszenia póki co, niech spece od ciasteczek się przyjrzą dla pewności.

**Comment by Lukjan38** [comment]
dobra

**Comment by krystian3w** [comment]
@MajkiIT odblokowujemy slider?

> https://github.com/MajkiIT/polish-ads-filter/issues/19325#issuecomment-808858883
