### ISSUE TITLE
innovaconcept.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19333]
`cookies`

![ss_151742_innovaconcept pl_](https://user-images.githubusercontent.com/75935068/112623092-31320900-8e2c-11eb-8a68-d76e19ef847f.png)

**Comment by strict-block** [comment]
`pl##+js(acis, $, warningCoookie)`

**Comment by felix-22** [comment]
Działa.

**Comment by strict-block** [comment]
Psuje pocztę Interia (layout stary), ha ha ha...

**Comment by felix-22** [comment]
Nie wiem, ja tylko sprawdziłem czy komunikat jest ukryty na `innovaconcept.pl`, nie sprawdzałem czy coś jest uszkodzone, ani nie korzystam z poczty na Interia.
