### ISSUE TITLE
tygodnikprzeglad.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19347]
![Zrzut ekranu z 2021-03-28 08-05-26](https://user-images.githubusercontent.com/36385327/112743999-737a5800-8f9c-11eb-9537-0397c5127e36.png)
tygodnikprzeglad.pl##.widget.widget-5

**Comment by seba2282** [comment]
`www.tygodnikprzeglad.pl##.header-block`
`www.tygodnikprzeglad.pl##.widget.widget-5`
`www.tygodnikprzeglad.pl##.widget.widget-7`
`www.tygodnikprzeglad.pl##.footer-darowizna-widgets`
`www.tygodnikprzeglad.pl##.widget.widget-10`
`www.tygodnikprzeglad.pl##.widget.widget-11`
