### ISSUE TITLE
turystyka.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1934]
bla bla car 

`http://turystyka.wp.pl/tarnowskie-gory-padl-rekord-w-zabytkowej-kopalni-srebra-i-sztolni-czarnego-pstraga-6078361032807553g/`

![capture](https://cloud.githubusercontent.com/assets/15007183/21868755/55bb7d98-d822-11e6-8e0d-7e10af2125a2.PNG)

**Comment by F4z** [comment]
`turystyka.wp.pl##body > div:nth-of-type(1)[style^="display: block;"]`
`turystyka.wp.pl##div[class^="_"]:matches-css(background-size: 56px 45px)`
`turystyka.wp.pl##.scr-wallpaper`

**Comment by MajkiIT** [comment]
Dzięki
