### ISSUE TITLE
postnowicjat.kapucyni.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19350]
`cookies`

![ss_156159_postnowicjat kapucyni pl_](https://user-images.githubusercontent.com/75935068/112747046-38cfea00-8fb3-11eb-9a71-632e767601b0.png)

**Comment by xxcriticxx** [comment]
@felix-22 no cookie here!

**Comment by felix-22** [comment]
To kup se okulary:

![112747046-38cfea00-8fb3-11eb-9a71-632e767601b0](https://user-images.githubusercontent.com/75935068/112761334-1d88cd00-8ffb-11eb-8624-fc64581eb101.png)

**Comment by xxcriticxx** [comment]
wyglada na static text

**Comment by felix-22** [comment]
No i co z tego, wkurzające (rzucające się w oczy) static też są ukrywane, bo są irytujące, 
zgłaszałem takich już wiele, i zazwyczaj są dodawane do listy, 
podobnie jak `Newslettery static (bez wyskakujących okienek)` i 
`Prenumeraty i E-wydania Gazet (static)`

**Comment by seba2282** [comment]
@xxcriticxx spójrz na ta regułę. Wiem, że trzeba zaatakować div content:  ` ##div.content`

**Comment by seba2282** [comment]
@krystian3w a tutaj merged?
