### ISSUE TITLE
autopart.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19355]
`cookies`

![ss_157351_autopart pl_](https://user-images.githubusercontent.com/75935068/112797552-d981e080-906b-11eb-9793-54f544a71bf6.png)

**Comment by strict-block** [comment]
Duplicate of #19254

**Comment by strict-block** [comment]
Przy okazji możesz dorzucić kod z dom w polu markdown:

<pre>
```html

```
</pre>

Jak element picker podaje głupie propozycje.

**Comment by felix-22** [comment]
- komunikat pojawia się po wejściu pod adres z `https` np.: 
   - `https://autopart.pl/` i wtedy przekierowuje na `https://www.autopart.pl/` 
   - lub bezpośrednio na `https://www.autopart.pl/`

- dziwne, bo po wejściu pod adres: z `http` czyli `http://autopart.pl/` lub `http://www.autopart.pl/`
   - też przekierowuje na `https` `: https://www.autopart.pl/` ale już komunikat się nie pojawia...

- tak czy inaczej kod:
```html
<div id="privacy">
    <span data-action="dismiss" class="prvClose">×</span>
    Ta strona używa cookie. Korzystając z niej wyrażasz zgodę na ich używanie, zgodnie z aktualnymi ustawieniami przeglądarki.    . 
</div>
```

**Comment by strict-block** [comment]
Niby robi się adres:

 `https://www.autopart.pl//`

i chyba połowa JS na stronie pada (niby szukają folderu "bez nazwy").

**Comment by felix-22** [comment]
Te mi się robi czasem `//`.
