### ISSUE TITLE
tawernaskipperow.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19352]
![Zrzut ekranu z 2021-03-28 08-27-07](https://user-images.githubusercontent.com/36385327/112744330-7c205d80-8f9f-11eb-9b4f-14305d90b403.png)
##.social

**Comment by seba2282** [comment]
`www.tawernaskipperow.pl##.social`
`www.tawernaskipperow.pl##[href="https://morze.org"]`
`www.tawernaskipperow.pl##[href="https://sklep.charternavigator.pl/"]`
`www.tawernaskipperow.pl##[href="https://www.charternavigator.pl/"]`
