### ISSUE TITLE
onet.pl > komputerswiat.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1937]
przejscie z onetu na komputerowy swiat 

ad block 

`http://www.komputerswiat.pl/nowosci/internet/2017/02/allegro-od-lutego-znaczne-zmiany-w-zdjeciach.aspx`

![capture1](https://cloud.githubusercontent.com/assets/15007183/21869236/a313f302-d824-11e6-8352-1d34509d7099.PNG)
![capture](https://cloud.githubusercontent.com/assets/15007183/21869239/a571b486-d824-11e6-8fd3-a66c01989220.PNG)

**Comment by F4z** [comment]
@xxcriticxx możesz sprawdzić czy działa?
`komputerswiat.pl#@#.adsense`
`komputerswiat.pl#@#.trizer-bnr`
`komputerswiat.pl#@##ks_breaking_news`
`komputerswiat.pl##.adsbygoogle`

**Comment by xxcriticxx** [comment]
@F4z tak dziala thx
