### ISSUE TITLE
codenga.pl | eduj.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19372]
![Zrzut ekranu z 2021-03-30 10-12-38](https://user-images.githubusercontent.com/36385327/112956177-77df7600-9140-11eb-9940-3739c758bbac.png)

`##.b-site-footer__social
`

**Comment by seba2282** [comment]
`codenga.pl##.b-site-footer__social`
`codenga.pl##.b-site-footer__bottom.l-col-12`


`eduj.pl##div.l-container:nth-of-type(9)`
`eduj.pl##.b-site-footer__social`
`eduj.pl##.b-site-footer__bottom-developed`
`eduj.pl##.l-justify-center.u-display-flex.l-offset-md-3.l-col-md-3.l-col-12 > [href]`
