### ISSUE TITLE
voxfm.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19373]
https://www.voxfm.pl/wiadomosci/polaczyla-ich-milosc-rozlaczyla-pandemia-rozdzielone-pary-walcza-o-mozliwosc-zobaczenia-sie-ak-4bTv-oKpf-PERE.html
![Zrzut ekranu z 2021-03-30 13-20-27](https://user-images.githubusercontent.com/36385327/112980859-b4b86680-915a-11eb-8147-d22a132e891a.png)

```
#@#.ad
#@#[class$="-ads"]
#@#[class$="-ads"]
#@#.ad-placement
```

**Comment by gzenio22** [comment]
Coś ostatnio @MajkiIT zniknoł sporo tych zgłoszeń tu

**Comment by krystian3w** [comment]
był dwa dni temu: https://github.com/MajkiIT/polish-ads-filter/commit/ef0f8c8fee8f2b6fae77a7dc19d176587ab45f52

a anty-adblock naprawia niby Oleg w Ukrainie 🇺🇦 : https://github.com/olegwukr/polish-privacy-filters/commit/01bae5e4433e253586615794ef21bdf6fac680b2

**Comment by xxcriticxx** [comment]
@gzenio22 tesknisz za dyrektorem?

**Comment by gzenio22** [comment]
a ty nie? @xxcriticxx Xd

**Comment by MajkiIT** [comment]
@gzenio22 żyję ale mniej czasu mam na filtry :D . Nie musicie tęsknić :D

**Comment by gzenio22** [comment]
@MajkiIT Rozumiem :P Kiedyś jakoś mieliśmy ten kontakt większy dla tego tak mowie cos tu za spokojnie :package:
