### ISSUE TITLE
Tępaki Inne wiochy	 Z łOnetu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1939]
`http://www.wiocha.pl/1389862,Tepaki`

**Comment by MajkiIT** [comment]
Sporo w tym prawdy. Pod przyciskiem OK jest subskrypcja wyjątków, tylko one nie działają już.

**Comment by MajkiIT** [comment]
odnośnie wiochy
`www.wiocha.pl###rectcont`
