### ISSUE TITLE
winotoskanii.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19401]
![Zrzut ekranu z 2021-04-01 10-38-18](https://user-images.githubusercontent.com/36385327/113267222-616b2300-92d6-11eb-9ab5-08c1c0158abb.png)

`winotoskanii.pl##div.menu__social_button_row:nth-of-type(1)`

**Comment by krystian3w** [comment]
źle - bloggera też wycinamy.
