### ISSUE TITLE
vaude-sklep.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19403]
![Zrzut ekranu z 2021-04-01 10-42-29](https://user-images.githubusercontent.com/36385327/113267758-fd952a00-92d6-11eb-81cd-b93afe9675a6.png)

```
vaude-sklep.pl##[src="/data/gfx/pol/navigation/15_4_i_4471.png"]
vaude-sklep.pl##[src="/data/gfx/pol/navigation/15_4_i_4470.png"]
```

**Comment by krystian3w** [comment]
losowe...

`##.footer_links_sub img[alt="fb"]`
`##.footer_links_sub img[alt="inst"]`
