### ISSUE TITLE
sestimi.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19416]
![Zrzut ekranu z 2021-04-01 11-10-45](https://user-images.githubusercontent.com/36385327/113271522-ea845900-92da-11eb-8660-3b2b1d850c37.png)

```
sestimi.pl##.menu_contact_item--facebook.menu_contact_item
sestimi.pl##.menu_contact_item--instagram.menu_contact_item
```

**Comment by krystian3w** [comment]
@gwaser ciekawostka:

element picker tworzy dla pop-upa filtr:

`###mailchimp-email-subscibe\ `

i oznacza go jako błędny:

```html
<div id="mailchimp-email-subscibe ">
...
</div>
```
