### ISSUE TITLE
rosarosie.iai-shop.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19417]
![Zrzut ekranu z 2021-04-01 11-12-55](https://user-images.githubusercontent.com/36385327/113271830-39ca8980-92db-11eb-8ed8-bdf1a76f65e6.png)

```
rosarosie.iai-shop.com###tws_a_1
rosarosie.iai-shop.com##center
```

**Comment by krystian3w** [comment]
center ukryje wszystko wyśrodkowane, lepiej sprawdza się już filtr:

`/ikony-social`
