### ISSUE TITLE
laczynaspilka.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19425]
https://www.laczynaspilka.pl/biblioteka
![Zrzut ekranu z 2021-04-02 11-11-57](https://user-images.githubusercontent.com/36385327/113401852-61395900-93a4-11eb-9205-70224001f95f.png)

Po akceptacji jeszcze jest regulamin ukryty
![Zrzut ekranu z 2021-04-02 11-12-27](https://user-images.githubusercontent.com/36385327/113401915-79a97380-93a4-11eb-9a4c-8e3f4b1bbbf5.png)

**Comment by krystian3w** [comment]
W dodatku jest akceptowanie: https://github.com/PolishFiltersTeam/PolishCookieConsent/commit/1059b2518e7d4e163186600d19ad28ac865fe8b0

**Comment by krystian3w** [comment]
Duplicate of #16503

**Comment by xMaap** [comment]
Jak coś to mam zainstalowane
![Zrzut ekranu z 2021-04-02 14-52-54](https://user-images.githubusercontent.com/36385327/113417206-34e10500-93c3-11eb-93f0-08f3191e6928.png)
