### ISSUE TITLE
rootblog.pl | zwiadowcahistorii.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19438]
`https://rootblog.pl/gamakay-k66-recenzja/`
Psuje galerię i nie da się jej przeglądać.
`https://www.zwiadowcahistorii.pl/polscy-naukowcy-odkryli-kodeks-aztekow-w-bibliotece-watykanskiej/`
Całkowicie usuwa obrazki

Winne jest `##.wp-block-image` z Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
Dodanie `##.size-full.aligncenter` powinno ukryć reklamy i z tego co widzę nic nie psuje.

**Comment by MajkiIT** [comment]
@xMaap dzięki
