### ISSUE TITLE
fly-lab.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19447]
`cookies`

![ss_165837_fly-lab pl_](https://user-images.githubusercontent.com/75935068/113570742-41f53280-9615-11eb-9b24-1c1907e6f5f2.png)

**Comment by strict-block** [comment]
Spakować do zip lub ustawić w bocie opóźnienie pod tę stronę:

https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/6f78846a7abc7cc9877568883e3adedd9776bb62#diff-6f98407a7a986519cd07d449bef61e175604f80f079ed19e531ad016b0e55c9bR270 - 2 letni filtr

raczej żadna popularna lista nie używa `generichide`.

**Comment by felix-22** [comment]
- też tego nie mam, pewnie z tych samych przyczyn co tu: #19208 (comment)
