### ISSUE TITLE
poczta.interia.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1947]
@MajkiIT  dodaj proszę na białą listę tę regułę:
```
@@||hub.com.pl^$script,subdocument,domain=poczta.interia.pl
```

Bez tego nie działa poczta na interii - nie wczytuje się zawartość IFRAME.

**Comment by MajkiIT** [comment]
Ok, jutro dodam jutro, bo ogarniam nowy router ....
