### ISSUE TITLE
gazetaprawna.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#1948]
Pozostałość po reklamie + myślę, że prenumeratę też można usunąć.

![image](https://cloud.githubusercontent.com/assets/11385099/21903806/79f0b216-d901-11e6-89d1-e16367ef1f45.png)

**Comment by xxcriticxx** [comment]
@mathew85 jak stym laptopem sie skonczylo?

**Comment by mathew85** [comment]
@xxcriticxx poluję na jakąś używkę w miarę nową. Coś na i5 lub i7, bo do pracy potrzebuje. Pewnie chwile to potrwa, ale nie mam dużego ciśnienia na to.

**Comment by xxcriticxx** [comment]
ibm/lenovo thinkpad po $300 na ebay

**Comment by MajkiIT** [comment]
@mathew85 do jakiej kwoty szukasz?

**Comment by mathew85** [comment]
2000-2500zł. Liczę jednak, że jakiś nietrafiony prezent uda mi się kupić :). Pojawia się trochę tego na olxie, ale spokojnie czekam na jakąś okazję.

**Comment by MajkiIT** [comment]
@mathew85 http://www.taniekomputery.pl/laptopy_notebooki_uzywane
Jak coś będę wiedział to dam ci znać. Kupa firm wyprzedaje sprzet.
