### ISSUE TITLE
filmweb.pl - odświeżanie strony po czasie nieaktywności

### ISSUE THREAD

**Issue by mysteriously** [MajkiIT/polish-ads-filter#19493]
### Link bezpośredni 
https://www.filmweb.pl/film/Wonder+Woman+1984-2020-792498

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na stronę filmweb.pl
2. Przejść na jakąkolwiek stronę z filmem, aktorką itp.
3. Zmienić kartę w przeglądarce
4. Odczekać kilka minut
5. Powrócić do poprzedniej karty
6. Strona się odświeża nie wiadomo po jakiego grzyba...

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Chrome
**Rozszerzenia i skrypty:** 
uBlock Origin

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. 
4.

**Comment by felix-22** [comment]
U mnie na Firefoxie jest to samo.

**Comment by krystian3w** [comment]
WP ma to samo...

**Comment by krystian3w** [comment]
Jak możecie to wykluczcie bug z infinity loading: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/8215b3a26cdee92b3a50d96c31b7c49e7d8ca9a0/PPB/inne.txt#L269

Jak dla mnie to irytująca funkcja i fajnie że tak łatwo się ona dezaktywuje. Dla przykładu portale Onetu mają:

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/8215b3a26cdee92b3a50d96c31b7c49e7d8ca9a0/PPB/inne.txt#L842
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/8215b3a26cdee92b3a50d96c31b7c49e7d8ca9a0/PPB/inne.txt#L126
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/8215b3a26cdee92b3a50d96c31b7c49e7d8ca9a0/PPB/inne.txt#L910

**Comment by hawkeye116477** [comment]
@MajkiIT It's not a bug, it's a feature :smile:.

**Comment by Barticf** [comment]
Wyświetla wam obrazki na filmwebie jak jesteście zalogowani i macie włączony uBlock ?

**Comment by krystian3w** [comment]
Pamiętaj by sprawdzać bez listy "rozszerzona prywatność Fanbojów" i "W 4 literach (_ _ _ _) mam komunikaty anty-adblock").

**Comment by krystian3w** [comment]
Wadliwy wydaje się obecnie filtr:

`#@#^script:has-text(webPushPublicKey)`

czyli trzeba tylko `filmweb.pl##+js(abort-on-property-read, webPushPublicKey)` blokować push.

**Comment by Barticf** [comment]
@krystian3w Polskie Filtry Elementów Irytujących u mnie powoduje brak obrazków itd.

**Comment by mysteriously** [comment]
Nadal występuje

**Comment by krystian3w** [comment]
Raczej dalej nieznana przyczyna, potestuj z AdGuard (ich darmowym rozszerzeniem).

Się naprawi to może bug jest z EasyList lub EasyPrivacy/Peter Lowe list.

**Comment by krystian3w** [comment]
Można spróbować tego na Firefox:

https://addons.mozilla.org/pl/firefox/addon/stop-auto-reload/

Może podobny / identyczny jest dla Chromium.

**Comment by krystian3w** [comment]
Bump

**Comment by krystian3w** [comment]
xd
