### ISSUE TITLE
weszlo.com

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1949]
Reklama - `http://weszlo.com/2017/01/12/aubameyang-vs-lewandowski-uczen-koncu-dorownal-mistrzowi/`

![image](https://cloud.githubusercontent.com/assets/11742596/21906113/3b48f2e0-d90a-11e6-9ac7-bd5da3547bb9.png)

Na przykład:
`weszlo.com###bsa-html`
albo
`weszlo.com##.top-adw`

Myślę, że jako ogólną można też dodać taką regułę:
`##a[href^="http://record.betssongroupaffiliates.com/"]`

**Comment by MajkiIT** [comment]
@F4z dzięki
