### ISSUE TITLE
urson.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19495]
https://urson.pl/ciagniki/

yt ( na dole )

**Comment by seba2282** [comment]
`urson.pl##[href="http://urson.otomoto.pl/"]`
`urson.pl##.span6 > [href="http://www.youtube.com/user/TheUrson2"]`  
`urson.pl##.sf-menu > .page-item-4437.page_item > [href="https://rolnictwo.olx.pl/#items"]`
