### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1950]
Zgłoszenie stąd - `https://www.facebook.com/photo.php?fbid=173239193157176&set=o.1456786284560953&type=3&theater`

Link - `http://www.filmweb.pl/`

W przypadku uBlocka ta reguła powinna wystarczyć:
`filmweb.pl##script:inject(abort-on-property-write.js, sndBox)`
To też można dodać:
`||fwcdn.pl/adv/$script,domain=filmweb.pl,important`

Dla Adblocka może być ta reguła:
`filmweb.pl###clickUrl1`
ale niestety zostanie puste miejsce po reklamie.

**Comment by xxcriticxx** [comment]
@F4z przegoniles mnie

**Comment by xxcriticxx** [comment]
dodam obrazek :)

![capture](https://cloud.githubusercontent.com/assets/15007183/21906817/d9ce8b3a-d8da-11e6-80a4-4ec96c8d7cbc.PNG)
