### ISSUE TITLE
bielsk.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19517]
( na dole )

https://bielsk.eu/bielsk-podlaski/32382-rolnicy-podlasie-andrzej-wyremontowal-ciagnik-fani-ale-z-ciebie-zgrywus-2

**Comment by seba2282** [comment]
`bielsk.eu##.item-692 > .knysz`
`bielsk.eu##.item-551 > .knysz`
`bielsk.eu##.isokcenter.sp-column > .custom > p > span`
`bielsk.eu###sp-bottom`
`bielsk.eu###sp-comments`
