### ISSUE TITLE
ipla.tv 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1952]
Joh Doe Yesterday at 12:44pm

Czy da się coś zrobić z reklamami które są wyświetlane podczas odtwarzania filmów na ipla.tv

**Comment by MajkiIT** [comment]
AAK Scripts?

**Comment by F4z** [comment]
uBlock Origin powinien wystarczyć.
Skrypt AAK nie działa chyba przy wszystkich filmach, ale to muszę jeszcze sprawdzić dokładniej.

**Comment by FadeMind** [comment]
Ja mam inny problem: Brak reklam, odtwarzacz flash i automagicznie w tle włączany film bez ścieżki video (słychać tylko audio) xD

**Comment by xxcriticxx** [comment]
@FadeMind to maz problem

**Comment by F4z** [comment]
Na przykład ten film - `http://www.ipla.tv/Ogniem-i-mieczem/vod-5582099`
Jak korzysta się z Chrome i skryptu AAK, to obraz w ogóle się nie wyświetla, jest tylko dźwięk ;)
W przypadku Firefoxa film się wyświetla, ale w odtwarzaczu ze strony, a nie tym ze "skryptu".

**Comment by xxcriticxx** [comment]
ja mam najlepszy ad block 

![capture](https://cloud.githubusercontent.com/assets/15007183/21907871/6a79b98a-d8df-11e6-908b-0794a0f12967.PNG)

**Comment by FadeMind** [comment]
@F4z sprawdź proszę to:
```
||http://r.dcs.redcdn.pl/file/o2/redefine/iplatv-assets/*/*/$script,domain=ipla.tv
```

**Comment by F4z** [comment]
@FadeMind to blokuje odtwarzacz i może inne rzeczy też.

Z samym uBlockiem normalnie mi działają filmy, bez reklam.

**Comment by MajkiIT** [comment]
@F4z no własnie mam to samo

**Comment by FadeMind** [comment]
@F4z u mnie to działa, brak reklam, plik MP4 odtwarzany w Playerze IPLA bez problemu.i nie mam 2x głos. :)

SOA#1

**Comment by MajkiIT** [comment]
@FadeMind tryb prywatny?

**Comment by FadeMind** [comment]
W trybie prywatnym mam dodatkowo informację o ograniczeniu wiekowym - grafika. Po za tym odtwarza się bez reklam (hosts) w odtwarzaczu flash.

**Comment by FadeMind** [comment]
```
22:04:24		||js-agent.newrelic.com^	--	script	https://js-agent.newrelic.com/nr-1016.min.js
22:04:24		##img[alt="Youtube"]	--	dom	http://www.ipla.tv/Miodowe-lata-lepsze-zycie-pl/vod-6409912#/r-30ai-4
22:04:24		##img[alt="Facebook"]	--	dom	http://www.ipla.tv/Miodowe-lata-lepsze-zycie-pl/vod-6409912#/r-30ai-4
22:04:24		##[id^="ad"]	--	dom	http://www.ipla.tv/Miodowe-lata-lepsze-zycie-pl/vod-6409912#/r-30ai-4
22:04:24		##:not(input)[id*="cookie"]	--	dom	http://www.ipla.tv/Miodowe-lata-lepsze-zycie-pl/vod-6409912#/r-30ai-4
22:04:24		###cookies-info:not(body):not(html)	--	dom	http://www.ipla.tv/Miodowe-lata-lepsze-zycie-pl/vod-6409912#/r-30ai-4
22:04:24		###cookies-info	--	dom	http://www.ipla.tv/Miodowe-lata-lepsze-zycie-pl/vod-6409912#/r-30ai-4
22:04:24		||pro.hit.gemius.pl^	--	image	http://pro.hit.gemius.pl/redot.gif?l=41/id=nXAwEjOaL5RneOgnbZdXsJdSfbuUt0ei1rpFPyshg2X._7&href=http%3A%2F%2Fwww.ipla.tv%2F%3FCat%3DWideo%2FSERIAL%2FKomediowy%2FMiodowe_Lata%26m%3DMiodowe_Lata_-_Lepsze_%C5%BCycie.pl&ref=&extra=GoalName%3DInterfejs%2FPrzegl%C4%85danie%7Cc%3Dipla-www%2F1.0%2FLinux%2FLinux%7Clt%3Dnone&et=view
22:04:23		||pro.hit.gemius.pl^	--	script	http://pro.hit.gemius.pl/xgemius.js
22:04:23		||www.googletagmanager.com^	--	script	http://www.googletagmanager.com/gtm.js?id=GTM-NDHB9L
22:04:23		/logos/facebook-	--	image	http://r.dcs.redcdn.pl/file/o2/redefine/iplatv-assets/logos/facebook-38d8beba4f323bb83d6ec98404ed6c86.png
22:04:23		||http://r.dcs.redcdn.pl/file/o2/redefine/iplatv-assets/*/*/$script,domain=ipla.tv	--	script	http://r.dcs.redcdn.pl/file/o2/redefine/iplatv-assets/core/2013/new_watch-825e9d4d4dd2ccb580330af5a96dfe53.js
22:04:23		||http://r.dcs.redcdn.pl/file/o2/redefine/iplatv-assets/*/*/$script,domain=ipla.tv	--	script	http://r.dcs.redcdn.pl/file/o2/redefine/iplatv-assets/core/user/facebook-4762dac94165f09a6496954660bd1d87.js
22:04:23		||http://r.dcs.redcdn.pl/file/o2/redefine/iplatv-assets/*/*/$script,domain=ipla.tv	--	script	http://r.dcs.redcdn.pl/file/o2/redefine/iplatv-assets/core/player/iplaReloaded-b86444b8d75fd06e7002e9e3406bf79b.js
22:04:23		||redefine.hit.stat24.com^	--	script	http://redefine.hit.stat24.com/files/js/ado.js
```

**Comment by FadeMind** [comment]
![screenshot_20170112_220807](https://cloud.githubusercontent.com/assets/9846948/21908344/9f6e70fc-d913-11e6-9d1a-8e6344ccdb09.png)

**Comment by F4z** [comment]
Ale to jest ze skryptu AAK odtwarzacz i on nie działa na wszystkich filmach, sprawdź tutaj - `http://www.ipla.tv/Ogniem-i-mieczem/vod-5582099`

**Comment by FadeMind** [comment]
Teraz widzę. Mam audio, ale nie ma odtwarzacza. Pewnie zagnieżdżony w gemiusie :>
