### ISSUE TITLE
wpzen.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19533]
![Nagrywaj_2021_04_09_13_40_26_984](https://user-images.githubusercontent.com/75935068/114174986-b8f23a00-9939-11eb-9a80-a6f23c4a3cc5.gif)

**Comment by strict-block** [comment]
Ja tego nie mam, sprawdź obecność listy Fanboy Social i czy uBO dev nie psuje filtrów kosmetycznych.

**Comment by felix-22** [comment]
- mam Fanboy Social, a sprawdzane było na normalnej wersji uBO 1.34.0 (nie dev) + FF 87.0, i dalej to jest, a wyskakuje po jakiś 5 sekundach w prawym dolnym rogu, więc sprawdź jeszcze raz, może sam przegapiłeś.

- a tak przy okazji, przy włączaniu/wyłaczaniu filtrów kosmetycznych zmienia swój wygląd, nie wiem czy to ma związek:
![Nagrywaj_2021_04_11_19_04_30_541](https://user-images.githubusercontent.com/75935068/114313929-e6391680-9af8-11eb-88fd-695dc9a78a4a.gif)

**Comment by felix-22** [comment]
Czyli wyszło, że przegapiłeś, bo widzę że już naprawione.
