### ISSUE TITLE
pcformat.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1955]
resztki reklamy 

`http://www.pcformat.pl/News-Nokia-6---Finowie-chca-wrocic-do-gry,n,16656`

![capture](https://cloud.githubusercontent.com/assets/15007183/21908978/04f23e20-d8e4-11e6-9c64-9190eb095df2.PNG)

**Comment by MajkiIT** [comment]
`www.pcformat.pl###ad_news`
