### ISSUE TITLE
gramp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1964]
`http://www.gram.pl/news/2016/12/14/the-last-guardian-spelnione-marzenia-recenzja.shtml`

![capture](https://cloud.githubusercontent.com/assets/15007183/21914964/9ed5247e-d904-11e6-9c67-0c587dd4d24f.PNG)

**Comment by MajkiIT** [comment]
`gram.pl##FIGURE.obrazek `
