### ISSUE TITLE
film.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1966]
reklama

`http://film.wp.pl/stanislaw-ulam-bohaterem-filmu-przygody-matematyka-6079297474131073a`

![capture](https://cloud.githubusercontent.com/assets/15007183/21915605/044ee91c-d909-11e6-99e7-ff6001ddaf29.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15007183/21915606/07065ea6-d909-11e6-952a-ea38fc9b5c5f.PNG)

**Comment by MajkiIT** [comment]
`facet.wp.pl,gwiazdy.wp.pl,teleshow.wp.pl,kobieta.wp.pl,film.wp.pl##body > div:nth-of-type(1)[style^="display: block;"]`
`facet.wp.pl,gwiazdy.wp.pl,teleshow.wp.pl,kobieta.wp.pl,film.wp.pl##div[class^="_"]:matches-css(background-size: 56px 45px)`
