### ISSUE TITLE
moto.onet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1968]
ad block 

`http://moto.onet.pl/aktualnosci/10-najciekawszych-nowosci-z-salonu-w-detroit/pz56yf`

![capture](https://cloud.githubusercontent.com/assets/15007183/21915847/834badda-d90a-11e6-94b7-a4ae6cad00c9.PNG)

**Comment by MajkiIT** [comment]
U mnie jest ok.

**Comment by MajkiIT** [comment]
`onet.pl#@#.trizer-bnr`

**Comment by xxcriticxx** [comment]
@MajkiIT dalej mam adblocka z najnowszymi filtrami 

` v.2017011301 aktualizacja: ptk, 13 stycznia 2017, 11:10:00`

**Comment by FadeMind** [comment]
@MajkiIT ja nie mam blokady ADblock na domenie `moto.onet.pl`

**Comment by F4z** [comment]
Ja w trybie prywatnym widzę ten komunikat.
Te reguły u mnie pomogły:
`moto.onet.pl#@##extraAdsBlock`
`moto.onet.pl#@#.addthis_toolbox`
`moto.onet.pl#@#.autopromoapp`
`moto.onet.pl#@#[id^="onet-ad-flat"]`
`moto.onet.pl#@##onet-ad-top`

Można też bardziej ogólnie:
`onet.pl#@##extraAdsBlock`
`onet.pl#@#.addthis_toolbox`
`onet.pl#@#.autopromoapp`
`onet.pl#@#[id^="onet-ad-flat"]`
`onet.pl#@##onet-ad-top`

Albo po prostu usunąć z listy te reguły:
`onet.pl###onet-ad-top`
`onet.pl##.autopromoapp`
`onet.pl##[id^="onet-ad-flat"]`
`onet.pl###extraAdsBlock`
`onet.pl##.addthis_toolbox`

**Comment by MajkiIT** [comment]
@F4z dzięki
