### ISSUE TITLE
noizz.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1969]
ad block 

`http://noizz.pl/noizz-food/idealna-przekaska-panierowane-rozyczki-kalafiora/ktfpp4y?dr=http://www.onet.pl&utm_source=onet.pl&utm_medium=referral&utm_campaign=sgwidget_1`

![capture](https://cloud.githubusercontent.com/assets/15007183/21930262/0fc5180c-d963-11e6-9232-4974ae43017d.PNG)

**Comment by F4z** [comment]
Możesz sprawdzić te reguły?
`@@||noizz.pl^$generichide`
`noizz.pl#@#.trizer-bnr`

**Comment by FadeMind** [comment]
@F4z działa pięknie
