### ISSUE TITLE
Brak ? w #?#

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19700]
Wydzielam żeby admin w końcu zauważył:
https://github.com/MajkiIT/polish-ads-filter/issues/19025#issuecomment-817321853 + 
https://github.com/MajkiIT/polish-ads-filter/issues/19025#issuecomment-817337442

**Comment by strict-block** [comment]
Zazwyczaj sprawdzam tylko pliki `_ukrywajace.txt` metodą zakładek:

- znajdź `:-abp-` i zaznacz linię
- usuń linie bez zakładek
- wracam do pliku i korekcja


Niby można by nawet użyć regex w edytorze webowym np.:

```regex
/##(#|\.|\\|\[\:\|([a-zA-Z]))?.*\:\-abp\-/
```

ale trzeba by go zapisać sobie, bo pisanie z palca czasem znajduje poprawne `#?#`.

**Comment by felix-22** [comment]
@MakiIT

 - to lepiej niech ten bot oznaczy admina jako "nieaktualny" albo "odrzucony" lub nowa etykieta: "przegapione":

>https://github.com/MajkiIT/polish-ads-filter/issues/19025#issuecomment-817337442:
>
> 1
> https://github.com/MajkiIT/polish-ads-filter/blob/9b76322e8af4b83e8c51fcd4adc73de408b337c9/polish-adblock-filters/adblock.txt#L473

błąd dalej nienaprawiony, pomimo, że błąd był zgłaszany 2 razy w 2 osobnych zgłoszeniach oraz nawet bot przypomniał po raz 3-ci, i upłynęło już dużo czasu: półtora miesiąca...jednocześnie w międzyczasie admin nie miał problemów z zauważaniem i naprawianiem innych błędów, i to po kilku dniach oraz bez dodatkowych przypomnień: https://github.com/MajkiIT/polish-ads-filter/issues/19901, https://github.com/MajkiIT/polish-ads-filter/issues/19911, więc albo nie zauważył/nie zaczaił błędu, albo z jakiś niewyjaśnionych przyczyn uparł się jak osioł żeby tego błędu nie naprawiać, ale wtedy wypadałoby żeby podał przyczynę i wyjaśnił kwestię, bo to nie Archiwum X.

- niech to zgłoszenie sobie tu wisi otwarte nawet 10 lat dopóki admini nie naprawi błędu albo nie wyjaśni dlaczego błędu naprawić nie chce
