### ISSUE TITLE
moto.onet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1974]
reklama skapiec na dole 

`http://moto.onet.pl/aktualnosci/skoda-kodiaq-rs-bedzie-wielkim-hitem/vsrf72`

![capture](https://cloud.githubusercontent.com/assets/15007183/21948660/7e04f6a0-d9ba-11e6-9c8d-ca7ca384da2d.PNG)

**Comment by xxcriticxx** [comment]
more skapiec

`http://muzyka.onet.pl/rock/me-and-that-man-cyrulik-jack-teledysk/2dlwsh`

**Comment by MajkiIT** [comment]
Ja tego nie widzę, nawet w trybie prywatnym. Możesz sprawdzić jeszcze raz?

**Comment by xxcriticxx** [comment]
na hoscie tego niemam sorry
