### ISSUE TITLE
flowday.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19744]
`cookies / rodo`

![ss_209957_flowday pl_](https://user-images.githubusercontent.com/75935068/115226544-a634ed80-a10f-11eb-8e8b-59eb6b759763.png)

**Comment by strict-block** [comment]
Chyba błędne zdjęcie, mały pasek cookies znika bez interwencji.

**Comment by strict-block** [comment]
Opcjonalnie pech, że zmienili layout.

**Comment by felix-22** [comment]
> strict-block : Chyba błędne zdjęcie

Albo błędna strona w tytule zgłoszenia, niestety już się tym nie zajmuję, więc nie odnajdę tej strony, więc zamykam.

**Comment by strict-block** [comment]
Raczej to wygląda, że dzień po zgłoszeniu uruchomili już nowy wygląd bez pop-upa (w web.archive.org on jest jako rozwalony z braku plików js/css).
