### ISSUE TITLE
tech.wp.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1975]
@MajkiIT 

```
tech.wp.pl##._2PL-mL0.kBUqizx
```
Cookie fix.

**Comment by xxcriticxx** [comment]
@FadeMind gdzie te cookies? bo nic nie widze

**Comment by FadeMind** [comment]
Na dole mi się pojawił.

**Comment by xxcriticxx** [comment]
ja na samym dole nic niema

**Comment by FadeMind** [comment]
Okno otwarte w trybie prywatnym:
![screenshot_20170114_141508](https://cloud.githubusercontent.com/assets/9846948/21955102/df92f058-da63-11e6-8321-21ed0cf07141.png)

**Comment by xxcriticxx** [comment]
zapomnialem o trybie prywatnym. patrze ze reklamy masz na hoste file

**Comment by xxcriticxx** [comment]
@FadeMind co za os? linux mint?

**Comment by FadeMind** [comment]
https://manjaro.org/

Akurat nie wszystkie domeny mam zablokowane w hosts file :package:

**Comment by xxcriticxx** [comment]
ja na hoscie blokuje okolo 105k domenow ale polskie listy sa slabe

**Comment by MajkiIT** [comment]
@xxcriticxx masz gdzieś swoją listę do hosts?

**Comment by xxcriticxx** [comment]
@MajkiIT https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt

**Comment by MajkiIT** [comment]
@xxcriticxx dziękuję
