### ISSUE TITLE
sklep.tayama.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19768]
`cookies / rodo`

![ss_212606_sklep tayama pl_](https://user-images.githubusercontent.com/72945564/115291092-98ee2200-a154-11eb-85d3-9258b088ef14.png)

**Comment by xxcriticxx** [comment]
@felix-22 Zaznacz te swoje ciastka bo mi juz sie znudzilo je znaczyc. Od jutra bedziemy zamykac nie zaznaczone watki. 

cc @MajkiIT / @hawkeye116477 / @krystian3w

**Comment by felix-22** [comment]
> felix22 : https://github.com/MajkiIT/polish-ads-filter/issues/19371#issuecomment-809581817 : 
> 
> xxcriticxx o ile dobrze pamiętam, nie musisz każdego mojego zgłoszenia etykietować osobno, zdaje się, że wystarczy zaznaczyć taki ptaszek u góry, żeby się automatycznie zaznaczyły wszystkie moje zgłoszenia i wtedy idzie etykieta do wszystkich moich zgłoszeń, za jednym kliknięciem (ale jak mówię, nie jestem pewny bo nie pamiętam).

Nawet nie sprawdziłeś / nie odpisałeś w kwestii mojej rady, co jest lekceważące z twojej strony, a teraz płaczesz jak baba, więc pomimo, że też powinienem tak samo olać cię ciepłym moczem, jak ty mnie, to jednak skutkowałoby to tym, że z własnej głupoty zamykałbyś moje zgłoszenia, więc specjalnie dla ciebie przygotowałem wersję dla ułomnych:

![Nagrywaj_2021_04_20_10_03_05_32](https://user-images.githubusercontent.com/75935068/115360315-cf14bb80-a1bf-11eb-9599-a0bddac83f0f.gif)

(no chyba, że tak się nie da z poziomu collaboratora, bo sprawdzałem tylko jako admin repo, ale zdaje się, że collabolator ma te same uprawnienia)

**Comment by felix-22** [comment]
- to, że zachowujesz się jak gbur, cham, prostak, 6-letnie dziecko, któremu odebrano lizaka, bo ignorujesz i olewasz, zamykasz, zamiast się dogadać to już udowodniłem w komentarzu wyżej
- to, że jesteś ułomny, też
- to, że z tobą nie da się normalnie dogadać też

- ale nie rozumiem dlaczego mi zamykasz po złości zgłoszenia, skoro podałem ci sposób w jaki można łatwo masowo dać etykietę dla wielu zgłoszeń. 
- jeśli ci ten sposób niedziała z jakiś powodów, to też mógłbyś łaskawie otworzyć tę parszywą gębę, to byśmy sprawdzili o co chodzi
- a jeśli nie chce ci się nawet w prosty sposób masowo dać etykiety bo to też dla ciebie za dużo, to nie dawaj, ale po co zamykasz zgłoszenia? Po złości? Ekipa od ciasteczek będą wiedzieli, że to zgłoszenia "cookies" i będą je normalnie ogarniać, i zamkną gdy ogarną i będzie PR
- te zgłoszenia to tak naprawę dla ciebie moja przysługa, ja też wykonuję pracę, żeby te zgłoszenia tu dostarczyć, trochę szacunku

Ktoś mu coś powie temu burakowi? Czy znowu ja będę winny jak zawsze i trolle-psychole  z polskiego repa się zlecą żeby mi dołożyć, a siebie bronić, jak zawsze.

@seba2282 ty chyba jedyny tu jesteś normalny i neutralny i widzisz, jak on się zachowuje, gdy ja się zachowuję w porządku..czy mógłbyś coś z tym zrobić? Np. zagadać do MajkiT żeby xxcriticxx nie zamykał zgłoszeń i nie robił mi po złości, bo ty masz z MajkiIT dobry kontakt zdaje się. Thx.

**Comment by felix-22** [comment]
@strict-block będziesz ogarniał te zamknięte zgłoszenia?

**Comment by strict-block** [comment]
Jeszcze trzeba zawiesić zgłoszenia automatyczne, tam trzeba labelować i title zmieniać.

**Comment by seba2282** [comment]
@xxcriticxx ale powiedziałem ci, żebyś się nie spieszył z zamykaniem. Daj trochę szansy dla ludzi. Chcą współpracować w rozwijaniu filtrów i ty spieszysz się cały czas z zamykaniem. Co jest złego sfinalizować, odpisać i zamknąć temat? Po wszelkich zatwierdzeniach 🙂

**Comment by seba2282** [comment]
@MajkiIT Moglibyście faktycznie nie zamykać tak szybko tematów? Najpierw zatwierdźcie, napiszcie jakiś komentarz i wtedy zamknijcie temat, jak będzie finalnie dodana reguła i itp. Widzisz np. że każdy ma np. prywatne sprawy i odpowiada na ile jest to możliwe. Więc proszę dajcie szansę w tematach przed ich zamknięciem.

**Comment by felix-22** [comment]
@seba2288 jak coś to ja nie zmuszam xxcriticxx żeby dodawał etykiety do moich zgłoszeń, skoro mu się nie chce, tylko po co zamyka te zgłoszenia? Chłopaki od ciasteczek wiedzą, że to są zgłoszenia `cookies` więc normalnie je zrobią a potem gdy będzie Pull Request to zostaną zamknięte.

**Comment by seba2282** [comment]
@felix-22 a tak właściwie, skąd ty zacząłeś sądzić, że mam dobre relacje z chłopakami od PL filtrów? Powiem tak, staram się być miły dla wszystkich i się nie unoszę. I podchodzę z szacunkiem do wszystkich. I to tyle

**Comment by felix-22** [comment]
@seba2288 jak coś to ja nie zmuszam xxcriticxx żeby dodawał etykiety do moich zgłoszeń, skoro mu się nie chce, tylko po co zamyka te zgłoszenia? Chłopaki od ciasteczek wiedzą, że to są zgłoszenia `cookies` więc normalnie je zrobią a potem gdy będzie Pull Request to zostaną zamknięte. No chyba, że mu się nie podoba wizualnie, że zgłoszenia są w kratkę: jedne z etykietą, a inne bez, ale ja na to nic nie poradzę, bo też już nie mam siły robić zgłoszeń ręcznie, bo tyle się ich w przeszłości pozakładałem, że teraz tylko bot mi zakłada.

**Comment by strict-block** [comment]
Raczej pod te niszowe stronki nie trzeba analizy czy mają tracking lub reklamy (zazwyczaj nie ma reklam, na blokowaniu śledzenia i wykrywaniu się nie znam za dobrze).

Zamknięte zgłoszenia istnieją dalej (znikną jak konto felixa zniknie lub je ktoś usunie/przeniesie do prywatnego repozytorium) i raczej nie będą czekać aż na 121 stronach Seba2282 wytnie stopki z linków do CMS o jaki ktoś zbudował sklep lub kto jest autorem strony.

**Comment by seba2282** [comment]
To wszyscy już wiedzą? Jak próbuję rozwijać filtr? 😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁

**Comment by felix-22** [comment]
Ponawiam pytanie https://github.com/MajkiIT/polish-ads-filter/issues/19768#issuecomment-824060039.

**Comment by felix-22** [comment]
Podoba się? W ten sposób będą od teraz oznaczone moje zgłoszenia, i tyle, kompromis elegancki, nikomu chyba nie przeszkadza, proszę więcej nie zamykać moich zgłoszeń.

@MajkiIT dopilnuj

**Comment by seba2282** [comment]
Te dogryzanie jest bez sensu. @xxcriticxx masz chyba uprawnienia do reopen tematu czy @MajkiIT nie obdarował pomocników przywilejem? Nie raz widziałem jak reopenowałeś tematy. Więc po co ten konflikt?

**Comment by strict-block** [comment]
Nie zrobimy reopenu około 600 tematów cookies, bo nie zdążyłeś powycinać:
- informacji kto tworzył stronę/z jakiego CMS korzysta
- patronów/partnerów strony

Założeniem w tamtych zgłoszeniach nie było czekanie aż ty wytniesz tamto a znajdzie się filtr na pasek/pop-up cookies lub metoda naprawy cookie-walla (w części takich fejkowych jak istnieje realna wersja np. "aktualnosci.html").

**Comment by seba2282** [comment]
Spytałem o ten konkretny temat dla @felix-22. I faktycznie zamykacie bardzo szybko. Ale dodatkowo narobiliście i mi roboty. Pościągaliście wszystkie reguły i nie wiem co usunąć i dodać do filtra. Muszę na nowo realizować wszystko.

**Comment by felix-22** [comment]
@strict-block

Proponuję rozdzielić 2 kwestie: moje i seba2282. Nie orientuje się w sprawach Seba, ale jeśli chodzi o mnie, to mi tylko chodzi o reopen moich 15 zgłoszeń ciasteczkowych, które zamknął mi wczoraj xxcriticxx, tyle i nic więcej.

**Comment by seba2282** [comment]
Najlepiej by było, jeżeli już się zgłasza co kolwiek i ma być zamknięte, to może jaki komentarz wcześniej to i to zostało dodane, tak jak @krystian3w robi z numerami i jest odnośnik do konkretnej reguły dodanej do filtra. I tyle. A nie, jak to robi ostatnio @xxcriticxx bez słowa closed temat. Czy to tak ciężko? @MajkiIT nawet pisze reguły pod tematami.

**Comment by felix-22** [comment]
Seba sam widzisz, że po grzeczności z nim nie da rady, na moje komentarze nie odpowiada, na twoje też nie, tylko wygłasza monologi, zamyka zgłoszenia, a potem ich nie otwiera, z takim człowiekiem się nie dogadasz, pokazał, że jest tu panem i władcą, i może mieć każego w dupie i każdym pomiatać, poza swoim przydupasem hawkeyem. Nas olał i inogruje, a  odpisać swojemu przydupasowi to miał czas: https://github.com/MajkiIT/polish-ads-filter/pull/19807#issuecomment-825594416

**Comment by seba2282** [comment]
@felix-22, ale do mnie ten @strict-block powiedział, że nie damy reopen. A się Spytam dlaczego? Czy jeżeli autor prosi o reopen jego tematu, to tutaj nie ma do tego prawa? Na różnych forach się spotkałem, że tylko sygnalizujesz do admina i on na życzenie otwiera temat. Więc co jest grane, drogi przyjacielu? 
@xxcriticxx masz uprawnienia i na prawdę ignorujesz prośbę autora tematu o ponowne otwarcie? To chciałbym zobaczyć w regulaminie pisania tu do was tematy zapiski "temat raz zamknięty nie będzie otwarty ponownie na życzenie aurora".  I teraz powiedz mi czy nie mam racji. Mówię to z pełnym szacunkiem do wszystkich i na prawdę uważam, że nie powinieneś tak robić.

**Comment by felix-22** [comment]
> seba2282 : To chciałbym zobaczyć w regulaminie pisania tu do was tematy zapiski "temat raz zamknięty nie będzie otwarty ponownie na życzenie aurora". 

Hehe, nie zobaczysz regulaminu, bo wtedy dyktatorzy musieliby się do niego sami stosować i łatwo byłoby ich przyłapać na jego łamaniu, i wymusić określone postępowanie godne z regulaminem. Dlatego oni wolą bez regulaminu, albo inaczej to ujmując, taki prosty regulamin: "ja mogę wszystko, a ty nic, a jak ci się nie podoba to wypad". Po prostu w takim miejscu bez regulaminu jesteś niewolnikiem / murzynem.

**Comment by strict-block** [comment]
Zawsze lepiej nowy temat niż ożywiać 5 letni na krańcu listy zgłoszeń np. temat 1700 będzie niżej niż temat 19768. Nie ma co się bawić że każda domena może mieć maksymalnie jedno Issue.

**Comment by felix-22** [comment]
Seba zobacz jaka grzeczna polityczna poprawność w tej sitwie / klice / gangu, gdy jeden z tej sitwy - mp. xxcriticxx, leci w kulki: pozamykał mi zgłoszenia i potem nie chce ich otworzyć, pomimo że już je polabelowałem, to inni z tej sitwy , nawet słowem się nie odezwą na xxcriticxx, żeby te zgłoszenia otworzył ponownie, pomimo że zgłoszenia polabelowane. A ty oczekujesz żeby ta sitwa miała jakikolwiek regulamin, to jest gang, albo jesteś w gangu razem z nimi, to wtedy cię traktują normalnie, a jak nie należysz do gangu, to jesteś dla nich nikim.

**Comment by felix-22** [comment]
Seba, zobacz czekałem cierpliwie 2 zasrane dni, aż pojawi się główny admin i otworzy moje zgłoszenia albo coś odpisze https://github.com/MajkiIT/polish-ads-filter/issues/19804, zobacz: wieśniak był wczoraj wieczorem https://github.com/MajkiIT/polish-ads-filter/commit/82a6501eb86ae24ca463685b0e8cc7c5bcf2b061, ale olał ciepłnym moczem moją prośbę ani nie odpisał nic, zachowanie identyczne co tego buraka xxcriticxx, przecież repoen 15 zgłoszeń zająłby mu 1 minutę?  Seba sam widzisz, że z tymi zasrańcami nie da się po grzeczności. Oni olewają , ignorują, pomiatają.
