### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19769]
1 reklamy (puste kontenery z napisem reklama)
2 błąd - uszkodzona strona, nie ładują się sekcje: "ZOBACZ RÓWNIEŻ", "PRZECZYTAJ TAKŻE"

zarówno na głównej jak i w artykułach, np.
https://www.komputerswiat.pl/aktualnosci/programy/firefox-88-zablokuje-ftp-mozilla-wkrotce-calkowicie-pozbedzie-sie-obslugi-standardu/7819sm0

![vv](https://user-images.githubusercontent.com/75935068/115363112-772b8400-a1c2-11eb-91e2-527a8048b8a3.png)

**Comment by strict-block** [comment]
Błąd z sekcjami robi blokada `csr.onet.pl` (EasyPrivacy)

`@@||csr.onet.pl^$domain=www.komputerswiat.pl`

Jak ktoś chce, to może zawężać co dopuszczać.

**Comment by strict-block** [comment]
Sekcja "przeczytaj także" raczej się nie załaduje, najwyżej osiągniesz białą lukę zamiast placholdera.

**Comment by felix-22** [comment]
Co masz na myśli? Bo po wyłączeniu adblockera, ta sekcja mi się normalnie ładuje:

![capture_002_20-04-2021_16-31-45](https://user-images.githubusercontent.com/75935068/115414075-0a31e180-a1f6-11eb-8f3d-c23dba07b7d4.png)

**Comment by strict-block** [comment]
Ja mam zawsze "zobacz również" zamiast "zobacz także".

Blokowanie Ładowania strony głównej po przewinięciu w dół jest w liście "Inne" dla EI, bo to raczej nie pop-upy są.

Jak pamiętam to chyba filtrem sieciowym by zniwelować efekt odświeżenia jak już byłeś na dole, wtedy filtr kosmetyczny nie działał.

Awaryjnie może html filtering i skryptlet (jakby plik zmienił nazwę a JS liniowy nie).

**Comment by strict-block** [comment]
Podobne na `https://businessinsider.com.pl/finanse/handel/majowka-2021-czy-beda-otwarte-sklepy/esvpl8d`
