### ISSUE TITLE
marekmeble.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19784]
( na dole )

https://www.marekmeble.pl/?zenid=o3t3dd8m4jskcr13c602mil9e6

**Comment by krystian3w** [comment]
to wygląda na przekręt "ale tanio": https://github.com/PolishFiltersTeam/KAD/issues/1037

- ceny niskie
- łamana polszczyzna
- fatalny CMS jakby z lat 90
