### ISSUE TITLE
fronima.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19794]
`cookies / rodo`

![capture_003_21-04-2021_10-13-33](https://user-images.githubusercontent.com/75935068/115520244-4020a580-a28a-11eb-863d-29f4aa556074.png)

**Comment by strict-block** [comment]
Wygląda na błąd, przeglądarki, pop-up nie otwiera się sam z siebie, link w stopce jest jedynym do polityki cookies, powinien zostać.
