### ISSUE TITLE
bip.kotla.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19792]
`cookies / rodo`

nie jestem pewien czy to znowu nie jest to samo co ostatnio czyli  niekwalifikujące się https://github.com/MajkiIT/polish-ads-filter/issues/19648#issuecomment-822057373

![ss_215974_bip kotla pl_](https://user-images.githubusercontent.com/75935068/115448651-36f7f000-a21a-11eb-8d79-b76fcafa0117.png)

**Comment by strict-block** [comment]
Raczej dalej BIP bez strony głównej, jak się nie da eventów, to dane teleadresowe.

Raczej nic się nie zrobi, bo przycisk strona główna generowałby pętle, trzeba by wychwycić dla każdego BIP ciastko "już tu kiedyś wchodziłem".
