### ISSUE TITLE
elton.com.ua - usefil button is hidden

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#1979]
Screenshot:
http://i90.fastpic.ru/big/2017/0114/53/75ab7eec050611ef92db55b4a28e7053.jpg
Caused by:
```
~konsoleigry.pl,~megadyskont.pl##[class^="adv-"]
```

**Comment by MajkiIT** [comment]
@Alex-302 Thanks, I will add it.
