### ISSUE TITLE
Do admina

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19804]
@MajkiIT mam prośbę (powiązane z https://github.com/MajkiIT/polish-ads-filter/issues/19768#issuecomment-824593866 + https://github.com/MajkiIT/polish-ads-filter/issues/19768#issuecomment-824703577).

Czy mógł byś zreopenować ~~15~~ 39 moich ostatnich zgłoszeń: https://github.com/MajkiIT/polish-ads-filter/issues?q=is%3Aissue+is%3Aclosed+author%3Afelix-22+%28%F0%9F%8D%AA+cookies%29
od https://github.com/MajkiIT/polish-ads-filter/issues/19764 wzwyż (tego jednego nie trzeba:  https://github.com/MajkiIT/polish-ads-filter/issues/19792)

**Comment by seba2282** [comment]
@MajkiIT @xxcriticxx  @hawkeye116477 @krystian3w co się ostatnio dzieje? Czemu ignorujecie ostatnio ludzi? Ale tak szczerze? Zawsze pomagaliście, a teraz jeden robi wojnę z ludźmi, drugi ignoruje wszystko i tak dalej. Czemu nie dacie tego reopen, jeżeli autor tematu o to prosi? To nie jest miłe, że ignorujecie i nie powiedziecie ani słowa w temacie.

**Comment by xxcriticxx** [comment]
@seba2282 czekamy na admin w ciszy i spokoju

**Comment by felix-22** [comment]
Uważaj bo się doczekasz, za tydzień albo miesiąc, czekamy już 3 dni w ciszy i spokoju, i się nie doczekaliśmy, bo admin był i nas olał, a tylko mi się zgłoszenia ciasteczkowe nazbierały i muszę się ich gdzieś pozbyć, chamujesz mi robotę.  A w ogóle po co chcesz czekać na admina? Sam możesz zrobić reopen, póki co wszyscy akceptują kompromis z etykietą w tytule, bo nikt nie zgłaszał, że mu to przeszkadza, więc dlaczego miałoby adminowi przeszkadzać, możesz zostawić to adminowi, a jak mu nie będzie pasowało to sam się odezwie i/lub pozamyka. Oczywiście pytania retoryczne, bo polska czereśnia nie udzieli odpowiedzi.

**Comment by felix-22** [comment]
Seba zobacz, xxcriticxx zamknął kolejne moich 24 zgłoszeń ciasteczkowych, razem z poprzednimi 16 któe zamknął wcześniej, to będzie już łącznie 40 zgłoszeń które mi zamknął.

**Comment by seba2282** [comment]
Na dwa trzy zdążyłem ci odpowiedzieć. @felix-22 Testowałeś te reguły? 

@xxcriticxx Co się dzieje? Może byście coś napisali przed zamykaniem? To nie jest miłe co robisz.

@MajkiIT, możesz coś z tym zrobić? Bo te sytuacje nie są miłe, jak @xxcriticxx wszystko zamyka od razu i bez słowa.

**Comment by felix-22** [comment]
> seba2282 : Na dwa trzy zdążyłem ci odpowiedzieć. felix-22 Testowałeś te reguły?

Nom, działają, odpisałem też w tamtych zgłoszeniach.

**Comment by seba2282** [comment]
> @seba2282 czekamy na admin w ciszy i spokoju


@xxcriticxx I gdzie jest jakiś odzew? 

@MajkiIT, dasz radę zabrać jakiś głos w tym temacie? Czy nadal ignorujesz ludzi, którzy normalnie kulturalnie proszą o coś (np. o reopen tematu)? Czy całkowicie nie ma regulaminu tutaj? Na innych portalach/forach i takiego typu jak github Admini nie robią problemu, jeżeli autor prosi o ponowne otwarcie jego tematu.

**Comment by xxcriticxx** [comment]
@seba2282 ja czekam na @MajkiIT niech zabierze glos w tej sprawie

**Comment by strict-block** [comment]
Jeśli można, to spróbuj nowsze zgłoszenia publikować z tym (niestety musisz znaleźć jak generować `<br>` inaczej niż w html/markdown):

```
- [] Reklama <!--Advert-->
- [] Wydobywanie kryptowalut <!--Cryptocurrency mining-->
- [] Anty-adblock <!--Anti-adblock wall-->
- [x] Komunikat dot. ciasteczek i polityki prywatności/RODO <!--Message about cookies and GDPR/privacy policy-->
- [x] Element społecznościowy <!--Social network element-->
- [] Pi-hole, hosts i spółka <!--Pi-hole, hosts & co-->
- [x] Błąd <!--Bug, mistake, no-no-->
- [] Pytanie <!--Question-->
```

Jak Github Actions się nie wywali to doda label od 15 do 30 minut od zapisu Issue - gorzej jak MS uzna to za przeciążenie usługi.

Wersja z krótszymi nazwami (system firebot) wymaga wielu regexów i chyba poprzedzenia tekstem "typ elementu:" więc jej nie polecam.

**Comment by felix-22** [comment]
Za późno na dialog, już się tym nie zajmuję, a bot ciasteczkowy został usunięty.

**Comment by seba2282** [comment]
> Za późno na dialog, zmarnowaliście swoją okazję, już się tym nie zajmuję, a bot ciasteczkowy został usunięty.
> 


Czyli rozwiązałeś problem, widzę. 😂

**Comment by felix-22** [comment]
Z [debilami](https://pl.wikipedia.org/wiki/Niepe%C5%82nosprawno%C5%9B%C4%87_intelektualna_w_stopniu_lekkim) się nie dogadasz.
