### ISSUE TITLE
legia.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19812]
Social + cookies
![Zrzut ekranu z 2021-04-24 15-49-11](https://user-images.githubusercontent.com/36385327/115960987-aae51180-a514-11eb-9f18-ab9c88d863c2.png)

**Comment by hawkeye116477** [comment]
Etykiety możesz zakreślać w formularzu, np:
- [] Reklama 
- [] Wydobywanie kryptowalut 
- [] Anty-adblock 
- [X] Komunikat dot. ciasteczek i polityki prywatności/RODO 
- [X] Element społecznościowy 
- [] Pi-hole, hosts i spółka 
- [] Błąd 
- [] Pytanie

**Comment by krystian3w** [comment]
Oni chyba bawią się w WP, a przecież pewnie do 10% wycina social/cookies a nie jak reklamy do 50% Polaków.
