### ISSUE TITLE
divanii.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19815]
![Zrzut ekranu z 2021-04-25 04-21-46](https://user-images.githubusercontent.com/36385327/115978133-cd5f4500-a57d-11eb-868e-999fe2d60ec3.png)

**Comment by krystian3w** [comment]
Duszek "CSS", nie da się wyciąć i raczej szkoda czasu na malowanie kwadratu białego nad grafiką stopki (jeszcze może ruszać się ze zmianą wymiarów okna.

**Comment by krystian3w** [comment]
I klikalne ikony nie są.
