### ISSUE TITLE
akademiastreamu.pl (🍪 cookies)

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19837]
`cookies / rodo`

![ss_221333_akademiastreamu pl_](https://user-images.githubusercontent.com/75935068/115988855-ca834500-a5bb-11eb-909d-35bb0b237521.png)

**Comment by seba2282** [comment]
`akademiastreamu.pl##.landend-infobar-dark`
@felix-22 sprawdź

**Comment by seba2282** [comment]
@xxcriticxx dodałeś tą regułę albo podobną do usunięcia tego cookie na stronie? bo nie widziałem, abyście usuwali już na filtrach. A zamknąłeś temat.

**Comment by felix-22** [comment]
Działa.

Seba, reguły sa dodawane, a zgłoszenia zamykane gdy pójdzie PR od chłopaków zajmujących się ciasteczkami, podam ci przykład takiego PR: https://github.com/MajkiIT/polish-ads-filter/pull/19723. Jak widzisz takie PR pojawiają się średnio raz na tydzień, no i pewnie niedługo będzie kolejny PR, oby chłopaki od ciasteczek porobili także te pozamykane zgłoszenia.

A z tym bucem to lepiej nie gadaj, bo znowu cię oleje.

**Comment by seba2282** [comment]
Problem jest taki, że nikt nie chce powiedzieć, co jest dodawane. Ja wiem, że nie jestem mocny z ciasteczkami, ale trzebaby też zgłosić do Daniela od I don't care about cookies o fix na liście i w dodatku. @felix-22 


@xxcriticxx, @MajkiIT długo będziecie ignorować ludzi? 


@felix-22 ja myślę, że na moim filtrze powywalam reguły i na nowo zacznę wszystko, bo żadne z panów od polskiej listy nie chce napisać, co mogę wyrzucić, co mogę już teraz zostawić. Spróbuję zablokować gemius/smartserver/adserver w całości i zobaczyć co będzie ze stronami. Będę też próbował usunąć zbędne rzeczy ze strony, jak próbuję to ostatnio robić, które są nie potrzebne, a nasi twierdzą, że muszą zostać. Po co np. allegro przekierowanie na stronie, która ma własny sklep, albo jakieś opinie z opineo? Nie irytuje to nikogo? Tylko mówcie prawdę. Ja chcę wyjść na przeciw ludziom i nie chcę ignorować nikogo. Ale też potrzebuję pomocy.
