### ISSUE TITLE
wojtstyl.leadsup.pl (🍪 cookies)

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19847]
`cookies / rodo`

![ss_226819_wojtstyl leadsup pl_](https://user-images.githubusercontent.com/75935068/115988869-d111bc80-a5bb-11eb-82ea-31717c6822ef.png)

**Comment by strict-block** [comment]
To raczej link z newsletterów, nie ma na co przekierować a to wygląda na przekręt z "suplementem" https://wojtstyl.leadsup.pl/metamorfoza/
