### ISSUE TITLE
zamki.pl (🍪 cookies)

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19851]
`cookies / rodo`

![ss_228237_zamki pl_](https://user-images.githubusercontent.com/75935068/115988876-d242e980-a5bb-11eb-958b-d9a6220c5f22.png)

**Comment by seba2282** [comment]
`www.zamki.pl##body > div`

Tutaj jest te cookie. Przynajmniej u mnie.

**Comment by felix-22** [comment]
Działa.

**Comment by strict-block** [comment]
Wytnie każdy najwyższy div, lepsze będzie np.: `##body > div[style*="position"][style*="absolute"]:not([id]):not([class])`

jak porzucą robienie strony o `<table>`

**Comment by seba2282** [comment]
> Wytnie każdy najwyższy div, lepsze będzie np.: `##body > div[style*="position"][style*="absolute"]:not([id]):not([class])`
> 
> jak porzucą robienie strony o `<table>`


Racja. @strict-block
