### ISSUE TITLE
Grupa TEZAP (8 stron)

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19852]
![ss_227398_tezap pl_](https://user-images.githubusercontent.com/75935068/115988635-f0f4b080-a5ba-11eb-9f7e-331cba9fbd0d.png)

tezap.pl
szafki-ubraniowe.pl
medyczne-meble.pl
warsztatowe.pl
krzesla.warsztatowe.pl
ogrodzenia-budowlane.com.pl
pojemniki.magazynowe.com.pl
zsypy.tezap.pl

**Comment by seba2282** [comment]
Spawdź `pl###jOftLayer`

**Comment by felix-22** [comment]
Działa.
