### ISSUE TITLE
noster.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19853]
### Błąd w:
- Polskie Filtry RODO-Ciasteczkowe
- I don't care a bout cookies

### Z włączonymi listami
![capture_004_25-04-2021_11-43-02](https://user-images.githubusercontent.com/75935068/115989076-cb68a680-a5bc-11eb-9bae-d9d0ecc7abfe.png)

### Po wyłączeniu list.
![capture_005_25-04-2021_11-43-40](https://user-images.githubusercontent.com/75935068/115989075-c99ee300-a5bc-11eb-817b-3eea3d11a93f.png)

**Comment by seba2282** [comment]
Widzę tylko jakiś blackscreen, bo używam dodatek I don't care about cookies i w zasadzie wszystkie filtry wbudowane + PL. 
Wówczas potrzebuję reguły : 'www.noster.pl##.black_overlay' bo nie wiem co u mnie wycina te cookie

**Comment by seba2282** [comment]
`www.noster.pl##.black_overlay`
`www.noster.pl##.ciacho-wrap-container`

I to załatwia u mnie całą sprawę.

**Comment by felix-22** [comment]
Działa.
