### ISSUE TITLE
plotkibiznesowe.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#19860]
### Zrzut ekranu 
![image](https://user-images.githubusercontent.com/18230443/116197100-95e6c900-a734-11eb-9efb-28388b82d1d9.png)

### Link bezpośredni 
https://plotkibiznesowe.pl/

**Comment by krystian3w** [comment]
`##.stream-item-above-header`

Z ciekawostek to reklama ich fanpage, więc może do listy social, ale z kolei tej nie używa już chyba RikoDev lub ogranicza się do `AdGuard social media`.
