### ISSUE TITLE
tvp.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#1987]
@MajkiIT @F4z FYI http://www.dobreprogramy.pl/TVP-wziela-sieza-blokowanie-adblockow-chce-zrekompensowac-sobie-koszty-produkcji-i-emisji,News,78543.html

**Comment by MajkiIT** [comment]
@FadeMind Dzięki. na chwilę obecną /odpukać/ z filtrami działa.

**Comment by MajkiIT** [comment]
Po prostu dramat
http://www.press.pl/tresc/47200,jacek-kurski-apeluje-o-pieniadze_-odbudowa_-albo-wygaszanie-telewizji-publicznej?utm_source=facebook.com&utm_medium=SM&utm_campaign=FB_Press

**Comment by xxcriticxx** [comment]
@MajkiIT czytaj maila
