### ISSUE TITLE
infowire.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19876]
![Zrzut ekranu z 2021-05-04 00-37-13](https://user-images.githubusercontent.com/36385327/116941970-f912b700-ac70-11eb-85dd-e8bb7d2cd0e9.png)

**Comment by krystian3w** [comment]
U mnie działa:

`pl##.cookies:not(body):not(html):not(#page):not(#container):not(.wrapper):not(.popup-newsletter):not(.js-cookies)`

https://github.com/MajkiIT/polish-ads-filter/blob/50c999152f963204259f4e2bdc699379bdf8adca/cookies_filters/adblock_cookies.txt#L3599

Filtr ma kilka miesięcy (około 2 lata): https://github.com/MajkiIT/polish-ads-filter/commit/02fcd39d6d2f5d48a04475ce3091ab50889e88fc#diff-a3cd7e608e0222e95d61e5620bdf8abdfc6fd401972d4bc4f503ce2f13752f4fR2714
