### ISSUE TITLE
czyztak.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19870]
https://czyztak.pl/
![Zrzut ekranu z 2021-04-29 21-29-51](https://user-images.githubusercontent.com/36385327/116607251-0ad32200-a932-11eb-8f23-dd09105d9080.png)
https://czyztak.pl/kategoria/informacje/marek-twarog-komentuje-dla-nas-swoje-zwolnienie-dzis-przestal-byc-naczelnym-dziennika-zachodniego
![Zrzut ekranu z 2021-04-29 21-30-18](https://user-images.githubusercontent.com/36385327/116607303-1b839800-a932-11eb-8aac-9f894ae562be.png)
![Zrzut ekranu z 2021-04-29 21-30-35](https://user-images.githubusercontent.com/36385327/116607339-250d0000-a932-11eb-95a2-f305dd4e25b8.png)

### Typ elementu/problemu 
- [x] Reklama 
- [] Wydobywanie kryptowalut 
- [] Anty-adblock 
- [] Komunikat dot. ciasteczek i polityki prywatności/RODO 
- [x] Element społecznościowy 
- [] Pi-hole, hosts i spółka 
- [] Błąd 
- [] Pytanie

**Comment by krystian3w** [comment]
@hawkeye116477 / @blocker999  czy Patrointe to już social media?

**Comment by hawkeye116477** [comment]
Chyba nie, raczej to do filtrów ukrywających donacje.

**Comment by blocker999** [comment]
Patrointe to nie social media, to do EI jako inny element

**Comment by krystian3w** [comment]
Statyczny link ze stopki / grafika też, nie widzę byś wycinał to regularnie jakbyś polegał na backupie listy anty-donejt.
