### ISSUE TITLE
widzieliście?

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#1988]
https://github.com/gorhill/uBO-Extra/releases

**Comment by xxcriticxx** [comment]
@MajkiIT more info pls???

**Comment by F4z** [comment]
Tak :)
To jest dawny uBlock Origin Websocket, tylko bardziej rozbudowany i jest tylko dla Chrome, bo w przypadku Firefoxa raczej nie jest potrzebny.

**Comment by xxcriticxx** [comment]
ok teraz rozumiem

**Comment by MrBeckham666** [comment]
Dzieki za dobrą robotę Panowie :+1:

**Comment by xxcriticxx** [comment]
@MrBeckham666 thank you
