### ISSUE TITLE
zametr.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19899]
https://zametr.pl/oferty/mieszkania/warszawa?market=&maxArea=any&minArea=any&minAreaPrice=any&maxAreaPrice=any&maxPrice=any&minPrice=any&maxRooms=any&minRooms=any&page=1

![Zrzut ekranu z 2021-05-13 11-22-32](https://user-images.githubusercontent.com/36385327/118106098-87a7d680-b3dd-11eb-9d4b-9b650fac1cfe.png)

**Comment by seba2282** [comment]
`zametr.pl##.sm\:text-base`
