### ISSUE TITLE
maxmodels.pl

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#19897]
napis reklama
np. `https://www.maxmodels.pl/` `https://www.maxmodels.pl/glamour.html` `https://www.maxmodels.pl/akt.html`

~`maxmodels.pl##div[class*="advert"]`~
~lub (nie wiem jaka różnica między `*` a `^`)~
`maxmodels.pl##div[class^="advert"]`

**Comment by krystian3w** [comment]
Jest i to "drastyczna":

* `[class*="advert"]` łapie wiele:

   ```html
   <div class="advert">...</div>
   <div class="advertowy swiat">...</div>
   <div class="under advert">...</div>
   <div class="under advertowy">...</div>
   <div class="under advert bottom"> ...</div>
   <div class="under advertowy bottom"> ...</div>
   <div class="under-advert-bottom"> ...</div>
   <div class="under-advertowy-bottom"> ...</div>
   ```

   i co tam sobie wymyślisz podobnego.

* a `[class^="advert"]` łapie mniej - z górnych przykładów tylko: 

   ```html
   <div class="advert">...</div>
   <div class="advertowy swiat">...</div>
   ```

---

mały kurs:

* najczęstsze:
   * https://www.w3schools.com/cssref/sel_attr_begin.asp (`^=`)
   * https://www.w3schools.com/cssref/sel_attr_contain.asp (`*=`)
   * https://www.w3schools.com/cssref/sel_attr_end.asp (`$=`)

* rzadziej używane lub wcale:
   * https://www.w3schools.com/cssref/sel_attribute_value_lang.asp (`|=`)
   * https://www.w3schools.com/cssref/sel_attribute_value_contains.asp (`~=`)
