### ISSUE TITLE
softonic.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1990]
reklama SCREEN LOCK GUARDIAN

`https://www.softonic.pl/online`

![capture](https://cloud.githubusercontent.com/assets/15007183/21997097/6b4a173c-dbfb-11e6-8eb2-a9f318f93526.PNG)

**Comment by FadeMind** [comment]
@xxcriticxx zrób nowe zgłoszenie w @azet12 KAD. 
Strony softonic to adware/scam. Wprowadzają w błąd użytkowników oferując instalatory z reklamami :package: 
```
[fademind@manjaro ~]$ cat /etc/hosts|grep softonic
0.0.0.0 softonic.com
0.0.0.0 softonic.it
0.0.0.0 adserver.softonic.com
0.0.0.0 aircrack-ng.softonic.fr
0.0.0.0 google-hacks.softonic.fr
0.0.0.0 keygen-password-generator.softonic.fr
0.0.0.0 quad-registry-cleaner.softonic.fr
0.0.0.0 rar-password-cracker.softonic.fr
0.0.0.0 serenescreen-marine-aquarium.en.softonic.com
0.0.0.0 serial-cloner.softonic.fr
0.0.0.0 universal-downloader.softonic.fr
0.0.0.0 warez.softonic.fr
0.0.0.0 razersoftonic.com
0.0.0.0 sms-softonicsolution.in
0.0.0.0 softonic.112.2o7.net
0.0.0.0 softonic.us.intellitxt.com
0.0.0.0 softonicsolution.com
0.0.0.0 vcard-converter.sd.softonic.de
0.0.0.0 web.softonic-analytics.net
0.0.0.0 www.razersoftonic.com
0.0.0.0 www.sms-softonicsolution.in
0.0.0.0 www.softonicsolution.com
0.0.0.0 www.vcard-converter.sd.softonic.de
0.0.0.0 netsr.softonicads.com
0.0.0.0 pub.softonic.com
0.0.0.0 net.softonicads.com
0.0.0.0 t1.softonicads.com
0.0.0.0 t2.softonicads.com
0.0.0.0 softonic-analytics.net
0.0.0.0 gsf-cf.softonic.com
0.0.0.0 softonic.de.intellitxt.com
```

**Comment by xxcriticxx** [comment]
@FadeMind zablokowalo tobie ten SCREEN LOCK GUARDIAN na hoscie?

**Comment by FadeMind** [comment]
@xxcriticxx nie, bo to siedzi tu: 
`va1pl.sftcdn.net/pl/img/ablock/leaderboard/screen_lock_guardian.jpg`

więc całą domena
```
va1pl.sftcdn.net
```
może lecieć na hosts ;P

**Comment by xxcriticxx** [comment]
dozuce to potem do siebie tez

**Comment by azet12** [comment]
Poklikałem i nie natrafiłem nigdzie na lewe instalatory, macie jakiś konkretny link? Pamiętam tę stronę, kiedyś nawet jakiś syf stamtąd zainstalowałem, ale to było dawno temu.

**Comment by xxcriticxx** [comment]
@azet12 narazie nic konkretnego nie ma obserwujemy dalej
