### ISSUE TITLE
bitcoin.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19907]
https://bitcoin.pl/film-dokumentalny/
![Zrzut ekranu z 2021-05-17 17-22-17](https://user-images.githubusercontent.com/36385327/118514156-9e7b5f80-b734-11eb-9864-064edb8d1f64.png)
![Zrzut ekranu z 2021-05-17 17-23-08](https://user-images.githubusercontent.com/36385327/118514163-9fac8c80-b734-11eb-8a28-aea689036a40.png)

### Typ elementu/problemu 
- [x] Reklama 
- [] Wydobywanie kryptowalut 
- [] Anty-adblock 
- [] Komunikat dot. ciasteczek i polityki prywatności/RODO 
- [x] Element społecznościowy 
- [] Pi-hole, hosts i spółka 
- [] Błąd 
- [] Pytanie

**Comment by krystian3w** [comment]
@blocker999  / @hawkeye116477  czy blokujemy telegram i signal jak obecnie:

- messenger
- whatsApp

?

Rosjanie w swoim suplemencie socjal usuwają telegram.

**Comment by seba2282** [comment]
`bitcoin.pl##.m-rek`
`bitcoin.pl##.space-x-6.flex`

**Comment by hawkeye116477** [comment]
@krystian3w Tak
