### ISSUE TITLE
portalpasazera.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#19916]
https://portalpasazera.pl/

![20210524-1621844456-001](https://user-images.githubusercontent.com/9846948/119318639-d83eef80-bc79-11eb-9fe6-45ad4d0251d1.png)

![20210524-1621844531-001](https://user-images.githubusercontent.com/9846948/119318756-f73d8180-bc79-11eb-8760-1313229c82d4.png)

![20210524-1621844541-001](https://user-images.githubusercontent.com/9846948/119318752-f6a4eb00-bc79-11eb-85f1-95a0f80fa205.png)

**Comment by krystian3w** [comment]
Czy działa portal po ukryciu (czyli nie czeka aż ktoś kliknie w "akceptuje")?

**Comment by krystian3w** [comment]
Jak ukrywamy, to lepiej tym:

`##.cookieman-window`
`##.modal-open:style(overflow: auto !important; padding-right: 0 !important;)`

**Comment by FadeMind** [comment]
@krystian3w szukajka działa, ale tak:
![20210524-1621847472-001](https://user-images.githubusercontent.com/9846948/119325072-cc0a6080-bc80-11eb-95dc-e3b7725efc9d.png)

**Comment by FadeMind** [comment]
@krystian3w reguły działają ;)

**Comment by krystian3w** [comment]
Czyli raczej nie musimy tego wrzucać w https://github.com/PolishFiltersTeam/PolishCookieConsent

https://github.com/MajkiIT/polish-ads-filter/blob/a0adb93f08c887faa9b8ff7c1e2511a8a01f9c7b/cookies_filters/adblock_cookies.txt#L3534 - ten filtr ukrywa personalizację w pop-upie?

Jak tak to raczej ją odblokujemy dla fanów ABP/AdBlock i iPhone/iPadów (Content blocker API).

**Comment by FadeMind** [comment]
@krystian3w  Wiem tylko tyle, że obecny set reguł przepuszcza popup o ciastkach i twoje nowe reguły ukrywają popup.
