### ISSUE TITLE
porowneo.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19918]
https://www.porowneo.pl/
![Zrzut ekranu z 2021-05-27 06-08-31](https://user-images.githubusercontent.com/36385327/119764602-07d83c80-beb2-11eb-9f07-89cd5d81a6d4.png)
![Zrzut ekranu z 2021-05-27 06-08-42](https://user-images.githubusercontent.com/36385327/119764608-09096980-beb2-11eb-8a66-d3987916b356.png)

https://podroze.porowneo.pl/form/
https://samochod.porowneo.pl/form/
https://mieszkanie.porowneo.pl/form/
![Zrzut ekranu z 2021-05-27 06-09-19](https://user-images.githubusercontent.com/36385327/119764673-23434780-beb2-11eb-9a12-220cc49e77e1.png)

### Typ elementu/problemu 
- [] Reklama 
- [] Wydobywanie kryptowalut 
- [] Anty-adblock 
- [x] Komunikat dot. ciasteczek i polityki prywatności/RODO 
- [x] Element społecznościowy 
- [] Pi-hole, hosts i spółka 
- [] Błąd 
- [] Pytanie

**Comment by krystian3w** [comment]
Strasznie ruchomy ten pasek cookies:
```
           porowneo.pl#?#footer >                       div[class^="sc-"]:last-child:-abp-has(>        button ~ div > a[href*="rules=polityka_prywatnosci"])
   podroze.porowneo.pl#?##root  >                       div[class^="sc-"]:nth-last-child(2):-abp-has(> button ~ div > a[href*="rules=polityka_prywatnosci"])
  samochod.porowneo.pl#?##root  > #main-app-container > div[class^="sc-"]:last-child:-abp-has(>        button ~ div > a[href*="rules=polityka_prywatnosci"])
mieszkanie.porowneo.pl#?##root  >                       div[class^="sc-"]:last-child:-abp-has(>        button ~ div > a[href*="rules=polityka_prywatnosci"])
```
