### ISSUE TITLE
Sample of invalid domains - ||onvictinitor.com$all

### ISSUE THREAD

**Issue by takenek** [MajkiIT/polish-ads-filter#19917]
[i] Target: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/urlhaus_filter_hosts.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 624865 domains, 1 domains invalid!
      Sample of invalid domains:
      - ||onvictinitor.com$all

Pozdrawiam!

**Comment by hawkeye116477** [comment]
Polecam oryginał => https://curben.gitlab.io/malware-filter/urlhaus-filter-hosts-online.txt :smile:

**Comment by takenek** [comment]
Ciekawe,
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/urlhaus_filter_hosts.txt
vs
https://curben.gitlab.io/malware-filter/urlhaus-filter-hosts-online.txt
To zupełnie inne pliki.

**Comment by hawkeye116477** [comment]
Jeszcze jest wersja dla uBO => https://curben.gitlab.io/malware-filter/urlhaus-filter-online.txt i ona jest podobna do tej z repo MajkiIT.

**Comment by hawkeye116477** [comment]
Jest ten Majkel czy zachorował?

Choć z drugiej strony widzę, że parę dni temu wykonał nawet nowsze zgłoszenia => https://github.com/MajkiIT/polish-ads-filter/commit/5a383206b7287632c26b1d0b857cdc20ee7a56e3. 
Dziwna polityka firmy, ja bym najpierw zaczynał od najstarszych :smile:

**Comment by krystian3w** [comment]
Może się od upałów rozpływa.

**Comment by hawkeye116477** [comment]
To niech kupi wiatrak...

Moim zdaniem raczej po prostu pewnie nie ma czasu i robi pierwsze lepsze, by było widać, że jednak nadal lista jest rozwijana. A w praktyce, może już zrezygnuje z rozwoju, bo lepszą płatną robotę ma i czasu już nie będzie miał...

**Comment by krystian3w** [comment]
Pobg
