### ISSUE TITLE
ofeminin.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19910]
![Zrzut ekranu z 2021-05-17 17-32-07](https://user-images.githubusercontent.com/36385327/118515702-e8187a00-b735-11eb-892c-cdecea14debe.png)
![Zrzut ekranu z 2021-05-17 17-32-22](https://user-images.githubusercontent.com/36385327/118515713-ea7ad400-b735-11eb-8d3d-3a9e24689c5a.png)

**Comment by krystian3w** [comment]
`##.socialProfiles` chyba, że Fanboje nas wyprzedzą...
