### ISSUE TITLE
procesor.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1991]
za duzo blokujemy zdjecia sie nie wyswietlaja

```
http://procesor.pl/windows-programy/dvdFab-hd-decrypter.html
http://procesor.pl/android-gry/strip-poker-fan-edition-hash3.html
```

**Comment by F4z** [comment]
Raczej za mało :)
Rozumiem, że chodzi o te puste miejsca nad i pod tekstem.
Jeśli tak, to tam są miejsca na reklamy.

Można je ukryć, na przykład taką regułą:
`procesor.pl###big-rectangle`

**Comment by xxcriticxx** [comment]
rozumiem
