### ISSUE TITLE
cyfrowypolsat.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#1993]
zaduzo blokujemy widze tylko top menu

`http://www.cyfrowypolsat.pl/program-tv/love/`

![capture](https://cloud.githubusercontent.com/assets/15007183/21997610/4006b1fe-dbfe-11e6-85ab-2725557645ee.PNG)

**Comment by F4z** [comment]
Bez blokowania reklam mam tak samo.
To jest raczej jakiś problem ze stroną.

**Comment by xxcriticxx** [comment]
ok zamykamy
