### ISSUE TITLE
worldcat.org

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19943]
( na dole ) : https://www.worldcat.org/title/gazeta-lekarska-pismo-tygodniowe-poswiecone-wszystkim-gaeziom-umiejetnosci-lekarskiej-farmacyi-i-weterynaryi/oclc/751259542

**Comment by krystian3w** [comment]
Chyba sztuczna polonizacja, czyli trzeba by sprawdzić czy fanboje powiedzą "no worth"/"no visitors".
