### ISSUE TITLE
tychy.naszemiasto.pl

### ISSUE THREAD

**Issue by Lukjan38** [MajkiIT/polish-ads-filter#19959]
nie dziala logowanie, po wylaczeniu ublock origin, jest ok.

**Comment by krystian3w** [comment]
U mnie działa, sprawdź listy niestandardowe i niebędące w tabelce:

https://majkiit.github.io/polish-ads-filter/

Dodatkowo na takie bugi może pomoże wymuszenie aktualizacji filtrów.

**Comment by Lukjan38** [comment]
niestety nie dziala, nadal po aktualizacji

**Comment by krystian3w** [comment]
Zrób kopię ustawień uBO i wrzuć tutaj lub wyłączaj listy niestandardowe aż logowanie się odblokuje.

Niby strona sama z siebie może nie dba o wymuszanie https:  https://github.com/PolishFiltersTeam/PolishCookieConsent/issues/47

**Comment by Lukjan38** [comment]
kopia

[ublock-kopia-zapasowa_2021-06-06_21.07.08.txt](https://github.com/MajkiIT/polish-ads-filter/files/6604723/ublock-kopia-zapasowa_2021-06-06_21.07.08.txt)

**Comment by krystian3w** [comment]
Nie umiem reprodukować, musisz czekać aż inny chętny namierzy bug w uBo 1.35.2 lub listach domyślnych (np. to nieszczęsne "EasyPrivacy") +:

 - AdGuard Base (wtedy konsultacja z AdGuard team)
 - I don't care about cookies (wtedy konsultacja z  kiboke lub hawkeye, bo ja nie widzę błędu)
 - KAD - Przekręty (wtedy konsultacja z  raczej hawkeye, nie widzę błędu)
 - Polish Privacy Filters (wtedy konsultacja z  majkiit/olegwukr)
 - Polskie Filtry RODO-Ciasteczkowe (wtedy konsultacja z  raczej hawkeye, nie widzę błędu)

---

> blokuje chyba easyprivacy

no to bardzo wyrywkowo i trzeba by mieć szczęście do namierzenia zbyt restrykcyjnej filtracji "szpiegowania"/"śledzenia". Upewnij się, że masz w miarę najnowszą wersje:
```
! Version: 202106061330
! Title: EasyPrivacy
! Last modified: 06 Jun 2021 13:30 UTC
```

Potem w loggerze trzeba by wyłapać co blokuje EasyPrivacy i jakie dopuszczenia naprawiają logowanie.


https://github.com/gorhill/uBlock/wiki/The-logger - szkoda, że logger uBO pokazuje po kliknięciu skąd kojarzy filtr  (AdGuard ma kolumnę z jakiej listy filtr się odpalił).

**Comment by Lukjan38** [comment]
mam najnowsza wersja. mam napisac do eeasyprivacy?

**Comment by AroKol78** [comment]
dla easylist / easyprivacy zgłoszenia - https://github.com/easylist/easylist/issues


spróbuje tylko z domyślnego listami
```
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe’s Ad and tracking server list
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku
```

**Comment by Lukjan38** [comment]
tak samo, na tych filtrach.

**Comment by AroKol78** [comment]
spróbuj z głównej `naszemiasto.pl`

jeśli `EasyPrivacy` wyłączysz to działa ?
tylko `/_sess/script.js` `/beacon.min.js` `/evercookie/` z `EasyPrivacy`
(nie zawsze widzę `/evercookie/` - dziwne)
spróbuje `@@/evercookie/$domain=naszemiasto.pl` lub `@@/evercookie/$domain=tychy.naszemiasto.pl` 
(nie jestem ekspertem)

**Comment by Lukjan38** [comment]
tak, po wylaczeniu easypriviacy, to dziala.

wyslalem maila do easyprivacy i nic.

**Comment by AroKol78** [comment]
sprawdź drogą eliminację dodając po kolei do "My-filters" (https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters)

`@@/evercookie/$domain=naszemiasto.pl`
`@@/_sess/script.js$domain=naszemiasto.pl`
`@@/beacon.min.js$domain=naszemiasto.pl` (najmniej prawdopodobne)
lub 
`@@/evercookie/$domain=tychy.naszemiasto.pl`
`@@/_sess/script.js$domain=tychy.naszemiasto.pl`
`@@/beacon.min.js$domain=tychy.naszemiasto.pl` (najmniej prawdopodobne)

chyba że ci za dużo blokuje  `||privacy-center.org^*/events` ( jest w `EasyPrivacy`)
`@@||privacy-center.org^$domain=naszemiasto.pl` lub `@@||privacy-center.org^$domain=tychy.naszemiasto.pl`

więcej nic znalazłem z `EasyPrivacy` (chyba że u ciebie coś więcej blokuje)

**Comment by Lukjan38** [comment]
prosze dodac ten @@/_sess/script.js$domain=naszemiasto.pl

**Comment by krystian3w** [comment]
@MajkiIT / @olegwukr  dodajcie jak chcecie naprawić szybciej niż fanboje pod koniec sierpnia.

**Comment by Lukjan38** [comment]
jeszcze nie ma :(

**Comment by krystian3w** [comment]
Może zrobili wątek w EasyList i wolą czekać na naprawę na początku września 2021 ale to raczej nie zabawa w Comarch z naprawami w +4 tygodnie, bo szybciej nie.

**Comment by krystian3w** [comment]
I raczej na wiarę by to odblokował Rayanbr / Khrin, bo raczej nie będą robić testowego konta.

**Comment by Lukjan38** [comment]
aha, szkoda

**Comment by AroKol78** [comment]
nie przejmuj się, sam ma prawie 100 filtrów w "My-filters"

**Comment by Lukjan38** [comment]
aha, napewno daja w wrzesniu?

**Comment by krystian3w** [comment]
Raczej nie wcześniej.

**Comment by Lukjan38** [comment]
ok, to dam to my filters, dopoki nie bedzie.

**Comment by Lukjan38** [comment]
dalej nie ma w filtrach :(

**Comment by krystian3w** [comment]
Jeszcze mają czasu a czasu na repodukcję i trzeba patrzeć, że na github muszą zamknąć z 361 zgłoszeń i scalić 544 "PR" (z 90% jest starsza niż błąd naszemiasto).

A kij wie ile zgłoszeń wisi na e-mailu / forum.lanik.us / tajnym systemie zgłoszeń  błędów  ABP.

**Comment by krystian3w** [comment]
Są bardzo zajęci.

**Comment by Lukjan38** [comment]
aha, szkoda :(

**Comment by Lukjan38** [comment]
od wczoraj juz nie ma, chyba skasowali :(

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/8053
