### ISSUE TITLE
opiekamedyczna.info

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19968]
https://www.opiekamedyczna.info/serwis.php?s=1463&pok=30550&id=4564794

https://www.opiekamedyczna.info/s/5135/81370-Apteki.htm

https://kursy.opiekamedyczna.info/

https://www.opiekamedyczna.info/s/3647/75165-Kierunki-medyczne.htm

**Comment by MajkiIT** [comment]
`www.opiekamedyczna.info##.bm1.bm`
