### ISSUE TITLE
bezpiecznyrynekpracy.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19979]
https://bezpiecznyrynekpracy.pl/inwestycje/sasiedzki-pl-najlepszym-agregatorem-ogloszen-w-internecie/qwa_hnut#lk:9fd2c605

**Comment by MajkiIT** [comment]
```
bezpiecznyrynekpracy.pl##.wrapper > .banner > .banner-block
bezpiecznyrynekpracy.pl##.banerart.banner-block
bezpiecznyrynekpracy.pl##.main-nosplit > .banner > .banner-block
```

**Comment by batate214** [comment]
> https://bezpiecznyrynekpracy.pl/inwestycje/sasiedzki-pl-najlepszym-agregatorem-ogloszen-w-internecie/qwa_hnut#lk:9fd2c605

xbncgfngfngfnfvngvngvn
