### ISSUE TITLE
operatorzy.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19983]
sociale ( na dole ), reklamy na ( głównej oraz w artykułach ), i mały błąd ( coś blokuje część artykułu " kody USSD " )  :

https://www.operatorzy.pl/telekomunikacja/telefonia-komorkowa/krotkie-kody-ussd/krotkie-kody-orange

![op1](https://user-images.githubusercontent.com/23176832/121804780-532b7280-cc48-11eb-8a1d-5e8408f80fac.png)

![op2](https://user-images.githubusercontent.com/23176832/121804785-56266300-cc48-11eb-89ca-8dc960738af4.png)

![op3](https://user-images.githubusercontent.com/23176832/121804786-56bef980-cc48-11eb-8116-1b9d86605c62.png)

**Comment by krystian3w** [comment]
Nie usuwaj tabelki z polami do zaznaczania, bo może cię `xxcriticxx` zablokuje na 30 dni i tyle.

**Comment by xxcriticxx** [comment]
@krystian3w tym razem podarujemy dla @blocker999

**Comment by krystian3w** [comment]
Na moje to coś w kodzie strony może jest nie tak, niby po dezaktywacji uBO i ochrony prywatności Firefox dalej umie znikać i co jakiś czas wracać.
