### ISSUE TITLE
olesnica.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19993]
![Zrzut ekranu z 2021-06-14 06-37-50](https://user-images.githubusercontent.com/36385327/121839755-1197d780-ccdb-11eb-9519-d4fbb8d53e3a.png)

**Comment by seba2282** [comment]
`olesnica.pl##.naglowek__buttons--container`

**Comment by krystian3w** [comment]
Jakiś spadek formy, przyciski dla  niepełonsprawnych i bip to nie social media
