### ISSUE TITLE
hdtvpolska.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#19996]
' magiclink " ( na dole ) pod artykułem
https://hdtvpolska.com/kanal-tvp-4k-dziala-test-w-naziemnej-telewizji-cyfrowej-dvb-t2-jak-odebrac/

**Comment by seba2282** [comment]
Nie wiem o który "magiclink" chodzi, ale coś tam created by... możesz usunąć tym: `hdtvpolska.com##.copyright`

**Comment by blocker999** [comment]
![ml](https://user-images.githubusercontent.com/23176832/122276188-d23cd700-cee4-11eb-9a90-31998a6aae44.png)

**Comment by hawkeye116477** [comment]
Info w stopce na dole nie jest aż tak irytujące jak ta reklama kabla za 200 zł. Widać mało chętnych jest na te cudo...

**Comment by krystian3w** [comment]
Cena pozłacania pewnie musi się zwrócić.

**Comment by hawkeye116477** [comment]
No to chyba jakieś specjalne mają, bo nawet kable Uniteka, którego na forach często polecają, są tańsze i również pozłacane ...
