### ISSUE TITLE
wcrs.wroclaw.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19994]
![Zrzut ekranu z 2021-06-14 06-38-18](https://user-images.githubusercontent.com/36385327/121839794-22484d80-ccdb-11eb-8109-a59e6dfbd631.png)

**Comment by seba2282** [comment]
`wcrs.wroclaw.pl##.menu-image-title-hide.menu-image`

**Comment by krystian3w** [comment]
o nie, bip to nie jest social media.
