### ISSUE TITLE
trzebnica.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19992]
https://trzebnica.pl/16/strona-glowna.html#contact
![Zrzut ekranu z 2021-06-14 06-36-39](https://user-images.githubusercontent.com/36385327/121839689-ec0ace00-ccda-11eb-9ddb-dd2dda1a0d49.png)

**Comment by seba2282** [comment]
`trzebnica.pl##.my-social`
