### ISSUE TITLE
filtry do adblock

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#20]
czy polskie filtry sa juz uzywane w adblocku?

to uzywam na iphonie i na ipadzie do blokowania

**Comment by MajkiIT** [comment]
![12196232_1677491472490432_3265194854754595633_n](https://cloud.githubusercontent.com/assets/11302675/11480018/7a80f6c2-9795-11e5-8f9a-da776cf5a3ed.png)

**Comment by xxcriticxx** [comment]
to widzialem ale co to znaczy?

jak to sprawdzic

**Comment by MajkiIT** [comment]
Na chwilę obecną nie ma. Przypomnę się im.

**Comment by xxcriticxx** [comment]
thx
