### ISSUE TITLE
make-cash.pl

### ISSUE THREAD

**Issue by myleadd** [MajkiIT/polish-ads-filter#20003]
Cześć,
chciałem zgłosić problemy z wyświetlaniem się grafik z portalu imgur.com na portalu make-cash.pl.

Przeglądarka: Opera
Wtyczka: uBlock Origin

Problem: z włączonymi filtrami POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda blokowane jest wyświetlanie grafik na portalu make-cash.pl. Z wyłączonymi filtrami problem nie występuje. Grafiki nie zawierają żadnych przekierowań.

Bez: https://i.imgur.com/yLcY7Vt.png
Z: https://i.imgur.com/NkFmkCN.png

Można to zobaczyć na przykład na https://make-cash.pl/wywiad-jak-zarabiać-bez-polecania-produktów-i-usług-t47418/

Widzę wpis w filtrach:
make-cash.pl##.ipsImage_thumbnailed.ipsImage, #ipsLayout_mainArea > .ipsResponsive_block.ipsResponsive_showDesktop

Jeśli to możliwe, to prosiłbym więc o możliwość wyświetlania grafik z portalu imgur, które w kontekście tematu powyżej nie są ładowane w formie jakiegokolwiek bannera lub czegoś podobnego.

**Comment by krystian3w** [comment]
To wygląda na reklamę YouTube, nie chcesz to dezaktywuj:

```
! Title: Polskie Filtry Społecznościowe
```
```
! Title: AdGuard Social Media filter
```
```
! Title: Fanboy's Social Blocking List
```

@hawkeye116477 zaktualizujesz link Fanboya na jego hosting, coś nie umieją na `easylist-downloads.adblockplus.org` aktywować poprawnie:

`!#include bla-bla-car.txt`

**Comment by myleadd** [comment]
To jest dział na forum z tematami będącymi aktualizacjami, poza tym taki temat mógłby być czymś innym, na przykład jakąś dyskusją i jeśli ktoś wkleiłby screenshota z imgura, to nadal byłby on zablokowany.

**Comment by krystian3w** [comment]
To musicie czekać, bo majkiit jest zapracowany / chory (być może ciężko przechodzi covid w warunkach szpitalnych już 2 tydzień).

**Comment by MajkiIT** [comment]
@myleadd ale niżej z tą klasą jest baner z linkiem . Z tego co pamiętam to właśnie blokowaliśmy. 

![obraz](https://user-images.githubusercontent.com/11302675/122709207-17069c00-d25e-11eb-9533-671a09b6eaf3.png)

**Comment by myleadd** [comment]
Okej, już rozumiem skąd taka decyzja. Myślę, że wtedy po prostu wrócę do tematu od razu, gdy będzie specjalna subdomena dla bannerów i sygnatur. Wtedy blokowane będą wyłącznie odpowiednie treści. Dzięki wielkie za informacje.
