### ISSUE TITLE
kurjerzy.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20022]
### Typ elementu/problemu 
- [] Reklama 
- [] Wydobywanie kryptowalut 
- [] Anty-adblock 
- [] Komunikat dot. ciasteczek i polityki prywatności/RODO 
- [x] Element społecznościowy 
- [] Pi-hole, hosts i spółka 
- [x] Błąd 
- [] Pytanie 

Polskie Filtry Społecznościowe za dużo wycinają ( na dole ) bo przy okazji tną "  O firmie " taki to efekt uboczny ( błąd )

**Comment by krystian3w** [comment]
Miałeś nie wycinać pól do zaznaczania, prosisz się o 30 dniowy urlop.

**Comment by blocker999** [comment]
OK, zapomniałem i obiecuje poprawe

**Comment by hawkeye116477** [comment]
Co to za błędy w pisowni, poprawnie pisze się kurierzy :smiley:

**Comment by krystian3w** [comment]
Pewnie z mody na "kur Zapiał".
