### ISSUE TITLE
bydgoszcz.naszemiasto.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2003]
resztki reklamy

![capture](https://cloud.githubusercontent.com/assets/15007183/22000908/e88fc804-dc0f-11e6-9674-d4ce256ce09e.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx zerkniesz ponownie, bo ja tego nie widzę?

**Comment by xxcriticxx** [comment]
@MajkiIT te pierwsze bylo na main page design sie zmienil i niema ale znalazlem cos na sub pages 

`http://bydgoszcz.naszemiasto.pl/artykul/pogoda-bydgoszcz-wtorek-24-stycznia,3992700,art,t,id,tm.html`

![3c01b000-dc5c-11e6-97b2-bfec95d45535](https://cloud.githubusercontent.com/assets/15007183/22249529/5c5b5daa-e211-11e6-86d3-0293bcc81331.png)
