### ISSUE TITLE
roweroweporady.pl

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#20035]
ja używam "ubo" bez "adguard base" 
`https://roweroweporady.pl/grupy-osprzetu-rowerowego-shimano/` z https://github.com/AdguardTeam/AdguardFilters/issues/86597
psuje "POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda" `||request.dqst.pl/$xmlhttprequest`

`@@||request.dqst.pl/$xmlhttprequest,domain=roweroweporady.pl`

`||request.dqst.pl/$xmlhttprequest,domain=~roweroweporady.pl`

`||lib.wtg-ads.com/prebid/prebid_*.js$xmlhttprequest,redirect=nooptext`

**Comment by seba2282** [comment]
Dziwne, tylko adguard base i nie widzę adblock detect

Filtr
||request.dqst.pl/v*/$xmlhttprequest
Lista filtrów
AdGuard Base 
Kontekst
roweroweporady.pl
Lokalność
(3) roweroweporady.pl ⇒ dqst.pl
Typ
xhr
Adres URL
https://request.dqst.pl/v1/reader

**Comment by AroKol78** [comment]
ja używam "ubo" **bez** "adguard base" i widzę "adblock detect"

mam bez "adblock detect" gdy zastosuje `@@||request.dqst.pl/$xmlhttprequest,domain=roweroweporady.pl`
lub gdy dodam filtr z "adguard base" `||lib.wtg-ads.com/prebid/prebid_*.js$xmlhttprequest,redirect=nooptext`

`||wtg-ads.com^` dziwne, że to nie pomaga z "POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda"

**Comment by AroKol78** [comment]
`||lib.wtg-ads.com/prebid/prebid_*.js$xmlhttprequest,redirect=nooptext`
do "POL: Oficjalne polskie filtry przeciwko alertom o Adblocku" dla ludzi używających domyślnych filtrów na "ubo"

**Comment by seba2282** [comment]
Widzę też, że niegdzie na stronie też działa filtr bogachenko na anty-adblock, kto ma dodany. On zezwala na jakąś regułę jak zwiedzasz więcej rzeczy na stronie. Ale wydaje mi się, że Adguard base powinien załatwić tu sprawę.

**Comment by AroKol78** [comment]
mi na "ubo" logger sypie błędami gdy używam Adguard base
"Invalid cosmetic filter in adguard-generic" i "Invalid network filter in adguard-generic"

**Comment by seba2282** [comment]
To dziwne. Bo z filtrami Adguard nie widziałem problemów. A może masz coś na kopane. Albo nie wiem.

**Comment by AroKol78** [comment]
to tylko nie wilki wycinek długiej listy
![noab01](https://user-images.githubusercontent.com/70756447/123158963-b600e300-d46c-11eb-814e-3ed07c276476.PNG)

**Comment by seba2282** [comment]
Tutaj trochę się np. wypowiadają: https://github.com/uBlockOrigin/uBlock-issues/issues/701

**Comment by hawkeye116477** [comment]
Widać AG dodał coś nowego, co uBO nie obsługuje.

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#jsinject-modifier

W uBO można chyba napisać tak `coub.com#@#+js`, ale tego jsinject nie ma...

**Comment by seba2282** [comment]
> Widać AG dodał coś nowego, co uBO nie obsługuje.
> 
> https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#jsinject-modifier
> 
> W uBO można napisać tak `coub.com#@#+js()`, ale tego `$jsinject` nie ma...

Tylko, że u mnie problem nie występuje. I kto mi to wyjaśni?

**Comment by hawkeye116477** [comment]
Błąd się zwykle pojawia po aktualizacji list.

**Comment by seba2282** [comment]
Aktualizuję na bieżąco i pierwszy raz to widzę. Może @AroKol78 niech kliknie w ten zegar blisko filtru dla zresetowania update i kliknie u góry aktualizuj w liście filtrów. Może problem zniknie.

**Comment by hawkeye116477** [comment]
> Może problem zniknie.

Nie zniknie, bo uBO tych reguł nie obsługuje. Więc albo AG musi to w liście zmienić albo gorhill dodać obsługę tej reguły.

**Comment by seba2282** [comment]
@AdamWr tutaj potrzebna pomoc ☺️

**Comment by AroKol78** [comment]
wiem, że błędne filtry są ignorowane, ale wprowadzają zamieszanie np. przy tych samych filtrach AG i UBO
jeden dział drugi nie i na odwrót, niewiadomo gdzie zgłaszać problem
wydaje się że problemy zgłaszane są naprawione, tylko że jednym dział a drugim nie, albo są odpowiedzi "Cannot reproduce"  / "Unable to reproduce"

**Comment by seba2282** [comment]
@AroKol78 zobaczymy co powie @AdamWr pod tematem. On i team Adguard potrzebują coś zrobić ☺️

**Comment by krystian3w** [comment]
Raczej MakiIT powinien poprosić olegwukr by znalazł nowe sposoby na adquesto.

**Comment by krystian3w** [comment]
Inne adquesto:

https://github.com/AdguardTeam/AdguardFilters/issues/86626
https://github.com/AdguardTeam/AdguardFilters/issues/86554

**Comment by AroKol78** [comment]
> Inne adquesto:
AdguardTeam/AdguardFilters#86626
AdguardTeam/AdguardFilters#86554

nie mam "adblock detect" (testowałem inne podstrony - na tych przykładowych mam 404)
player mi nie działa na `dziennik.pl`
pomaga `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=videotarget.pl`



`roweroweporady.pl` mi pomaga `||lib.wtg-ads.com/prebid/prebid_*.js$xmlhttprequest,redirect=nooptext`

**Comment by krystian3w** [comment]
Niby skrypt przerabia źle przecinki, zamień sobie wszystkie %C2 na przecinki.

**Comment by AroKol78** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/86626#issuecomment-869856217 to samo mam na stonach / podstronach `dziennik.pl`
mi pomaga `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=videotarget.pl`

**Comment by hawkeye116477** [comment]
Najwyraźniej pan Oleg sobie odpuścił rozwijanie listy albo wirus go złapał.

**Comment by felix-22** [comment]
Mam nadzieję, że to tylko wakacyjna przerwa i wszystko wróci wkrótce do normy, bo jeśli nie, to nieciekawie się robi, bo zamuła i cmentarzysko się robi... i to repo zacznie przypominać [repo EasyList](https://github.com/easylist/easylist/issues) gdzie wiele zgłoszeń czeka miesiącami.
Dla odmiany podam przykłady rep na których naprawdę szybko są naprawiane zgłoszenia : [uAssets](https://github.com/uBlockOrigin/uAssets/issues) i [AdGuard](https://github.com/AdguardTeam/AdguardFilters/issues)
