### ISSUE TITLE
wbieszczady.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#20048]
https://wbieszczady.pl/najpiekniejszy-zakatek-bieszczadow-10-miejsc-ktore-trzeba-zobaczyc/
![Zrzut ekranu z 2021-06-28 19-17-58](https://user-images.githubusercontent.com/36385327/123677596-9b03e980-d845-11eb-8cfc-59cb21bb3128.png)

**Comment by krystian3w** [comment]
U mnie już tego nie ma fizycznie w kodzie, sprawdź ponownie i określ czy widać to tylko w Chrome/Opera/Vivaldi.
