### ISSUE TITLE
podleze-piekielko.pl

### ISSUE THREAD

**Issue by BCFFF** [MajkiIT/polish-ads-filter#20052]
### Zrzut ekranu 

![obraz](https://user-images.githubusercontent.com/32641928/124264368-a94b5180-db34-11eb-96b1-01172ee9211c.png)

### Link bezpośredni 

http://podleze-piekielko.pl/

### Co trzeba zrobić, aby pojawił się błąd?
1. 
2. 
3. 

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List
11. AdGuard Tracking Protection
12. AdGuard Base
13. AdGuard Mobile Ads
14. Fanboy’s Social 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Cookies/rodo czy reklama?

Jak np. newsletter to złe repo :wink:.

**Comment by BCFFF** [comment]
@krystian3w cookies

**Comment by krystian3w** [comment]
Pop-up jest zamykalny po usunięciu `EasyList Cookie`? Jak tak to we własnym zakresie poproś o naprawę u nich też dla fanów AdBlock / Adblock Plus.

**Comment by krystian3w** [comment]
@xxcriticxx zamieniamy etykietę błąd na "błąd zewnętrznych" i dodatkowo poproszę "cookies".

**Comment by BCFFF** [comment]
@krystian3w Fanboy’s Annoyance i EasyList Cookie
