### ISSUE TITLE
static.mylead.global

### ISSUE THREAD

**Issue by myleadd** [MajkiIT/polish-ads-filter#20057]
Dzień dobry,
chciałem prosić o usunięcie rekordu static.mylead.global (aktualnie pozwala wyłącznie na obrazy z promolovers.pl). Mowa o tym konkretnie rekordzie:

||static*.mylead.global^$image,third-party,domain=~promolovers.pl

Jednocześnie prośba o dodanie do blokowania nowych subdomen, które zaczęły wykorzystywać reklamy od MyLead. Problem z blokowaniem wziął się z używaniem domeny static.mylead.global zarówno przez reklamy, na przykład bannery, jak i content wszelkiej innej treści, który nie są treścią reklamową. Aktualnie problem został rozwiązany.

Nowa subdomena, na której umieszczone są grafiki reklamowe (bannery + sygnatury):` https://zas.mylead.global/` zamiast `https://static.mylead.global/`
Nowy link przekierowań, który umieszczony został na grafikach reklamowych (bannery + sygnatury): `https://mylead.global/stl/XXXXXX` zamiast `https://mylead.global/sl/XXXXXX`

Dokonane zmiany można zobaczyć na:
- **https://zarabiam.com/** (banner na górze strony - https://i.imgur.com/kb89DTH.png; sygnatura pod postami konta MyLead - https://i.imgur.com/VM2YbRD.png)
- **https://make-cash.pl/** (sygnatura pod postami konta MyLead - https://i.imgur.com/DQCliQT.png
- **https://affnext.com/** (banner na górze strony - https://i.imgur.com/559048F.png)
- **https://www.affplus.com/** (banner w panelu po lewej [przy czym ten jest umieszczony na rotatorze, więc wyświetlany jest losowy banner] - https://i.imgur.com/FanmpwA.png)

Przeglądarka: Opera
Wtyczka: uBlock Origin

PS: w przypadku make-cash.pl jest też wpis:

make-cash.pl##.ipsImage_thumbnailed.ipsImage, #ipsLayout_mainArea > .ipsResponsive_block.ipsResponsive_showDesktop

**Comment by krystian3w** [comment]
Reklamy brzydkie, jak majkiit uzna to za self-promo to może będzie i blokowane w PolishAnnoyanceFilters.
