### ISSUE TITLE
diki.pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#20068]
Witam czy szłoby dodać filtr do tej strony na reklam.

diki.pl

**Comment by krystian3w** [comment]
Nie w ABP / Pi-Hole.

Reklama wymaga `:style()` do naprawy marginesów/odstępów.

**Comment by kolor33** [comment]
A w ublock jaką regułę dodać ?

**Comment by krystian3w** [comment]
Reguły dodajemy  do AdGuard (a lista reguła to "Filtr"), w uBo stosuje się filtry (uBo reguły ma tylko w trybie firewall a lista to "lista").

**Comment by kolor33** [comment]
No dobra to jaki filtr byś dodał by tą reklamę zablokować.

**Comment by krystian3w** [comment]
Może taki:

```css
##body:style(position: static !important; padding: 0 !important;)
```

**Comment by kolor33** [comment]
Dałem ten filtr niestety nie działa/

www.diki.pl##body:style(position: static !important; padding: 0 !important;)

**Comment by krystian3w** [comment]
Zrób zrzut ze strzałką na reklamy, u mnie górna reklama wtedy się nie pojawia i luka jest likwidowana.

Dodatkowo wymuś aktualizację do uBo 1.36.2+ - nie da się wstecznie naprawiać np. uBO 1.21.0, bo sobie zablokowałeś aktualizację.

**Comment by kolor33** [comment]
UBO jest aktualny a reguła taka 

||www.diki.pl##body:style(position: static !important; padding: 0 !important;)

nic to nie daje .Reklama zjeżdża na dół i już .
![1](https://user-images.githubusercontent.com/32041737/125168413-c96ab880-e1a5-11eb-9946-da578c1ea609.jpg)

**Comment by hawkeye116477** [comment]
Z przodu nie powinno być żadnych `||`.

**Comment by AroKol78** [comment]
> Wypróbuj `www.diki.pl##body:style(top: 0 !important;)`

plus `www.diki.pl##div[class="popupBannerContainer popupBannerDark"]`
lub plus `www.diki.pl##div[class^="popupBannerContainer"]

**Comment by hawkeye116477** [comment]
Lub krócej
```
www.diki.pl##body:style(top: 0 !important;)
www.diki.pl##.popupBannerContainer
```

**Comment by krystian3w** [comment]
Ale na co wam filtr 2 jak jest w PAF:

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/f798926f6bed244ed2b8375d8ac3f2fb68a04ae1#diff-17aed648b936a10d2b56ac0364305ab60933d39af10f7e7f656e4805bb0558e7R2

**Comment by hawkeye116477** [comment]
Ale to jest reklama, więc raczej powinna być na liście Majkela.

**Comment by AroKol78** [comment]
> Ale na co wam filtr "2" jak jest w PAF - moduł "pop-upy":

niestety nie miałem dodanego modułu - gubię się w wymaganiach konkretnych modułów 
(mam Polskie Filtry Elementów Irytujących - Powiadomienia Web Push / Scrollujące Filmiki)

**Comment by krystian3w** [comment]
To jest self-promo, relacja madka-curka:

https://web.archive.org/web/20200328182432/https://www.diki.pl/

Wcześniej był na dole.

**Comment by krystian3w** [comment]
Ja bym przeniósł to do `inne-suplement.txt`

**Comment by kolor33** [comment]
hawkeye116477  dzięki działa.

**Comment by krystian3w** [comment]
Opcjonalnie możesz oba wywalić, jest już w Polish Annoyances Filters jak i module "inne elementy":

* [Subskrybuj **całe** Polskie Filtry Elementów Irytujących](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2FPolishFiltersTeam%2FPolishAnnoyanceFilters%2Fmaster%2FPPB.txt&title=Polish%20Annoyance%20Filters "https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt") lub

* [Subskrybuj **moduł** Polskie Filtry Elementów Irytujących - **Inne Elementy**](https://subscribe.adblockplus.org/?location=https%3a%2f%2fraw.githubusercontent.com%2fPolishFiltersTeam%2fPolishAnnoyanceFilters%2fmaster%2fPAF_other_widgets.txt&title=PFEI%20-%20Inne%20Elementy "https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_other_widgets.txt")

Warunek, że używasz uBO lub AdGuard, w ABP uruchomiłem sprawdzanie `body:not([style])` jakby kiedyś wrócili do luźnego "pop-upa".

**Comment by kolor33** [comment]
krystian3w  dzięki zrobiłem jak powiedziałeś szacunek dla Panów.
