### ISSUE TITLE
swiatseriali.interia.pl

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#20069]
"adblock detect" standardowo przez `/ima3.js` na filmiku `https://swiatseriali.interia.pl/seriale/video,vId,3105312`
pomaga `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=embed.pluscdn.pl`

---
to samo co wyżej, filmik pod `https://www.pomponik.pl/plotki/news-klaudia-z-warsaw-shore-dotkliwie-pobita-przez-partnera-wstrz,nId,5353808`
pomaga `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=embed-e2-32.pluscdn.pl`

**Comment by krystian3w** [comment]
na dzienniku identycznie @olegwukr / @MajkiIT 

rekomenduję scalenie https://github.com/AdguardTeam/AdguardFilters/issues/86626#issuecomment-873962776 tego commitu do nas:

https://github.com/AdguardTeam/AdguardFilters/commit/678066eeb25035a641488cd7d98a90906daa0bc3

**Comment by AroKol78** [comment]
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=pluscdn.pl|videotarget.pl`
