### ISSUE TITLE
mobileclick.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#20081]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://mobileclick.pl/poznaj-10-przydatnych-aplikacji-dla-seniora/
```

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Vivaldi 4.0.2312.27

### Bloker (Blocker)

uBlock Origin v1.36.2

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Strona główna jest popsuta, brakuje górnych artykułów, a menu wysunięte jest poza obszar.

![2021-07-11_15-49](https://user-images.githubusercontent.com/19818572/125197834-91c04700-e25f-11eb-9ec2-458308649f07.png)

Rozwiązaniem problemu jest usunięcie reguły `mobileclick.pl##.entry-content > [href] > .lazy-loaded`, ale wtedy oczywiście wracają reklamy w artykułach, np w podanym linku.

![2021-07-11_15-51](https://user-images.githubusercontent.com/19818572/125197931-fed3dc80-e25f-11eb-9670-166060f3a6e7.png)

Po prawej stronie są też jakieś resztki z obiadu.

![2021-07-11_15-52](https://user-images.githubusercontent.com/19818572/125197956-1dd26e80-e260-11eb-8c75-8faa5fff5df3.png)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Może wystarczy nie akceptować rodo a je wyciąć?

**Comment by hawkeye116477** [comment]
Efekt będzie ten sam.

**Comment by hawkeye116477** [comment]
Problem nie został rozwiązany.

**Comment by krystian3w** [comment]
Może can't fix i trzeba gorhilla prosić o nowe skryptlety lub implementacje niestandardowego ExtendedCSS...

**Comment by hawkeye116477** [comment]
@krystian3w Jeszcze rozumiem może reklamy, ale tam występuje błąd, który trzeba rozwiązać.

**Comment by krystian3w** [comment]
Może nie umie zablokować nowych reklam wydajnie jak to robił stary filtr (nie chce dodawać np. 5 nowych), więc dlatego ocenia uszkodzenie za mało istotne.

**Comment by hawkeye116477** [comment]
Różnych rzeczy można się domyślać, ale tak naprawdę to powinno być oznaczenie i jakieś wyjaśnienie, jeżeli odrzucone.
Równie dobrze mógł zamknąć omyłkowo, ale jak on nigdy nic nie pisze, to kto go tam wie.
