### ISSUE TITLE
smaker.pl

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#20085]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [x] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://smaker.pl/newsy-jak-zrobic-mizerie-idealna-zdziwisz-sie-jakie-to-proste,1902360,a,.html
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

UXP custom

### Bloker (Blocker)

uBlock Origin Legacy 1.16.4.29

### Używane listy filtrów (Used filter lists)

My filters
uBlock filters
uBlock filters - Legacy
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy
Online Malicious URL Blocklist
uBlock filters – Annoyances
Peter Lowe’s Ad and tracking server list
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku
KAD - Przekręty
NoCoin Filter List
Polish Privacy Filters
Polskie Filtry Elementów Irytujących - Powiadomienia Web Push
Polskie Filtry Elementów Irytujących - Scrollujące Filmiki

### Inne rozszerzenia (Other extensions)

github-wc-polyfill

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

na reklame 
```
smaker.pl##div[id="adsmain"]
smaker.pl##div[class="advert-250-box"]
```
Anti-adblock przez `/ima3.js` na filmiku - rozwiązanie https://github.com/MajkiIT/polish-ads-filter/issues/20069#issuecomment-878201270

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
@olegwukr
