### ISSUE TITLE
ckm.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2008]
`||nsaudience.pl^`
`www.ckm.pl##.prenumerata-sklep-ckm`
`||exs.pl/ads.js$script`
`||adkontekst.pl^$image`
`||vendimob.pl^`

http://www.ckm.pl/m/dziewczyny/,18277,a.html

**Comment by xxcriticxx** [comment]
@MajkiIT cos nowego chyba ostatnio ckm byl

**Comment by F4z** [comment]
@MajkiIT czy ta reguła jest potrzebna - `||exs.pl/ads.js$script`?
Tak pytam, bo blokuje ten skrypt - `http://mr1a.exs.pl/ads.js` - a jego zawartość wygląda tak - `isAdBlockActive = false ;` więc zastanawiam się czy trzeba to blokować.

**Comment by F4z** [comment]
Podobnie tutaj - https://github.com/MajkiIT/polish-ads-filter/issues/1998
Ta reguła - `||www.wgrane.pl/html/ads.js$script,domain=www.wgrane.pl`

**Comment by MajkiIT** [comment]
@xxcriticxx wiem właśnie, dlatego zerknąłem

@F4z Ok poprawię. Dzięki
