### ISSUE TITLE
dyktanda.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#20091]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [X] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://dyktanda.pl/
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

FF 90+

### Bloker (Blocker)

uBo 1.36.2+

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. Polskie Filtry Anty-adblock

### Inne rozszerzenia (Other extensions)

n/d

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

anty-adblock z fejk z blurem "`backdrop-filter: blur(8px);`".

![obraz](https://user-images.githubusercontent.com/35370833/126231919-4036b47a-a5e0-4297-8881-42de33ee2b97.png)|
--- |
<sup> <sub> @olegwukr  </sub> </sup> |

Na szybciocha:

```
dyktanda.pl#?##modal:-abp-has(h3:-abp-contains(Blokujesz))
```

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by xxcriticxx** [comment]
felix-22 commented 6 days ago
To nie duplikat, po prostu nie mogę tam #20091 odpisać bo mnie zablokował i mam kłódkę, więc chciałem podać inne rozwiązanie: po włączeniu AdGuard Base anty-adblock znika, dzięki temu filtrowi: `||adnxs.com^$xmlhttprequest,redirect-rule=noop.txt` ( samo `||adnxs.com^$xmlhttprequest` też działa). Można także dodać `,domain=dyktanda.pl.`
