### ISSUE TITLE
opinie.wp.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2010]
`opinie.wp.pl,facet.wp.pl,gwiazdy.wp.pl,teleshow.wp.pl,kobieta.wp.pl,film.wp.pl##body > div:nth-of-type(1)[style^="display: block;"]`
`opinie.wp.pl,facet.wp.pl,gwiazdy.wp.pl,teleshow.wp.pl,kobieta.wp.pl,film.wp.pl##div[class^="_"]:matches-css(background-size: 56px 45px)`

**Comment by xxcriticxx** [comment]
@MajkiIT wp mnie pomalu juz dobija niemozemy zrobic czegos co dziala dluzej?

**Comment by MajkiIT** [comment]
@xxcriticxx wiem, mnie też. Napiszę zaraz maila do ciebie @F4z .
