### ISSUE TITLE
mobileclick.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#20102]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [X] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://mobileclick.pl/poznaj-10-przydatnych-aplikacji-dla-seniora/
```

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Vivaldi 4.0.2312.27

### Bloker (Blocker)

uBlock Origin v1.36.2

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Problem #20081 nie został rozwiązany, a nie wiedzieć dlaczego zamknięty (zapewne omyłkowo, ale może dlatego właśnie przydałoby się dodatkowo jakoś to etykietą oznaczać jako zatwierdzone/odrzucone i dopiero później zerknąć jeszcze raz i zamknąć), więc piszę ponownie. 

Strona główna `https://mobileclick.pl` jest popsuta, brakuje górnych artykułów, a menu wysunięte jest poza obszar.

![2021-07-11_15-49](https://user-images.githubusercontent.com/19818572/125197834-91c04700-e25f-11eb-9ec2-458308649f07.png)

Rozwiązaniem problemu jest usunięcie reguły `mobileclick.pl##.entry-content > [href] > .lazy-loaded` z listy, ale wtedy oczywiście wracają reklamy w artykułach, np w podanym linku.

![2021-07-11_15-51](https://user-images.githubusercontent.com/19818572/125197931-fed3dc80-e25f-11eb-9670-166060f3a6e7.png)

Po prawej stronie są też jakieś resztki z obiadu.

![2021-07-11_15-52](https://user-images.githubusercontent.com/19818572/125197956-1dd26e80-e260-11eb-8c75-8faa5fff5df3.png)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
oceń czy może to nie rozwiąże problemu czytelności nagłówka:

`mobileclick.pl##.site-hero`

**Comment by hawkeye116477** [comment]
To nie pomoże, bo nadal nie będzie artykułów na górze. Ta reguła o której pisałem po prostu musi zostać wykreślona.

**Comment by krystian3w** [comment]
Ale one są w sumie w lewej kolumnie najczęściej, w środkowej newsy.

**Comment by hawkeye116477** [comment]
Tak czy siak, te reklamy, można nawet lepiej sieciowo wyciąć.

**Comment by krystian3w** [comment]
O ile widzisz schemat w ich nazewnictwie na "hostingu".

Bo potem będzie nagle zabawa w regex z pomocą xpath jak mają tylko długi adres:

> `:xpath(//a[string-length(@href)>128])`

**Comment by hawkeye116477** [comment]
`||socialpress.pl/wp-content/uploads/*reklama.png$image,domain=mobileclick.pl`

**Comment by hawkeye116477** [comment]
Jeszcze na dole coś zostało, ale to chyba raczej robota dla @krystian3w.
![2021-08-05_22-24](https://user-images.githubusercontent.com/19818572/128416226-6d20ebcd-73e6-4de7-aec4-5342b730dd1c.png)

**Comment by krystian3w** [comment]
`##.essb-postbar`
`##.essb_mailform`

Potem zobaczę jak strona reaguje na dezaktywację ładowania kolejnych lub czy da się napisać regułę sieciową co blokuje pobierania propozycji do środkowej kolumny.

**Comment by krystian3w** [comment]
A tu można dodać etykietkę social, bo widzę że skrzętnie uciołęś stopkę by go nie było.
