### ISSUE TITLE
geselle.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#20107]
### Opis błędu:

Błąd wystepuje na wielu listach.

### Naprawa:
`@@||www.googletagmanager.com/gtm.js$script,domain=geselle.pl`

### Przed naprawą:
![capture_011_30-07-2021_15-53-20](https://user-images.githubusercontent.com/75935068/127676430-5e470d4b-eac7-4ebc-963f-29399040d688.png)

### Po naprawie:
![capture_010_30-07-2021_15-53-01](https://user-images.githubusercontent.com/75935068/127676476-a121a4dc-ca9c-4fec-9c4a-cfaafbe3e8e2.png)

**Comment by bug-rules** [comment]
Raczej i tak trzeba dezaktywować `redirect` w projektach uAssets/AdGuard.

Dodatkowo zrób test z uBO 1.37.2 lub nowszym po tym jak naprawiono skrypt do analityki Google.

**Comment by strict-block** [comment]
Hmm...

**Comment by felix-22** [comment]
> Dodatkowo zrób test z uBO 1.37.2 lub nowszym po tym jak naprawiono skrypt do analityki Google.

Już przed założenie zgłoszenia było sprawdzane, a teraz dodatkowo sprawdziłem na `1.37.3b3` i dalej to samo.
