### ISSUE TITLE
lomza.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2011]
box po cookies i zaduzo blokujemy na pogodzie 

![capture](https://cloud.githubusercontent.com/assets/15007183/22081103/42f3fe4c-dd90-11e6-9230-10423fb1498d.PNG)

**Comment by F4z** [comment]
Dla uBlocka może coś takiego?
`www.lomza.pl##html > body.polityka-cookies:style(margin-top: 0px !important; background-position: center 20px !important;)`
