### ISSUE TITLE
interia.pl

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#20129]
kwadraty z napisem "reklama"
`https://porady.interia.pl/koty/news-dieta-barf-dla-kota-czy-jest-zdrowa,nId,5409940`
`https://porady.interia.pl/komputery/news-jak-czyscic-ekran-laptopa,nId,5314909`
```
interia.pl##div[class="ad-article-vertical-track"]
interia.pl##div[class="ad-article-horizontal-wrapper"]
```
albo 
`interia.pl##div[class^="ad-article-"]`

**Comment by krystian3w** [comment]
> `interia.pl##div[class="ad-article-vertical-track"]`
>`interia.pl##div[class="ad-article-horizontal-wrapper"]`

Można uprościć do kropki:
`##.ad-article-vertical-track`
`##.ad-article-horizontal-wrapper`

**Comment by AroKol78** [comment]
> Można uprościć do kropki:
`##div.ad-article-vertical-track`
`##div.ad-article-horizontal-wrapper`

`##.ad-article-vertical-track, .ad-article-horizontal-wrapper`
też działa (poznaje składanie)
