### ISSUE TITLE
esklep.brandvital.eu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20130]

**Comment by krystian3w** [comment]
Kiboke can you generic in addon for close:

`.config-messages`

if contains words "`pliki cookies`"?

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/20152 https://github.com/MajkiIT/polish-ads-filter/issues/20151

**Comment by krystian3w** [comment]
#20130 #20151 #20152

**Comment by krystian3w** [comment]
#20130 #20151 #20152 #20153

**Comment by krystian3w** [comment]
#20130 #20151 #20152 #20153 #20154

**Comment by krystian3w** [comment]
#20130 #20151 #20152 #20153 #20154 #20155

**Comment by kiboke** [comment]
@krystian3w IDCAC filter list doesn't contain any adblocker specific selectors (like -abp-contains). It will be fixed on per domain level.

**Comment by krystian3w** [comment]
OK, I try check this Polish domains after you publish 3.3.4 in future.

Very rare `.config-message` / `.configMessage` is self-promo pop-up (big and center of page).
