### ISSUE TITLE
swissfon.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20146]
fb ( button )

**Comment by krystian3w** [comment]
Niestety nie widzę, może fanoby wyciął lub szablon się im popsuł (czasem strona nie ładuje CSS-ów)

fyi @hawkeye116477

**Comment by hawkeye116477** [comment]
Ta, u mnie psuje się strona z włączonym uBO, a w loggerze niby nie widzę nic podejrzanego.

**Comment by krystian3w** [comment]
Ja bym nie duplikował filtru, skoro generyk nie działa to pewnie CPU nie wyrabia a generyki niby działają w uBO równie szybko jak specyficzne.
