### ISSUE TITLE
polsatgo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#20157]
![Capture](https://user-images.githubusercontent.com/15007183/129494482-757573a0-5bdb-4b3e-b237-bcf1a07734a7.PNG)

**Comment by krystian3w** [comment]
Duplicate of https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/issues/108

**Comment by krystian3w** [comment]
Duplicate of #20161

**Comment by xxcriticxx** [comment]
@krystian3w kto kogo duplikowal zobacz po numerach albo po datach

**Comment by krystian3w** [comment]
Już prawie nigdzie nie patrzą na datę.

**Comment by xxcriticxx** [comment]
zobacz po numerach issues

**Comment by krystian3w** [comment]
Już prawie nigdzie nie patrzą na ID.

**Comment by xxcriticxx** [comment]
lol okay

**Comment by hawkeye116477** [comment]
A ja przyznaję rację dla critica, w końcu on pierwszy zgłosił. Z tym, że zgłoszenie lukjana dotyczy innego elementu.

**Comment by seba2282** [comment]
Możecie coś zrobić z tym cookies na polsatgo.pl ?

**Comment by krystian3w** [comment]
Będzie migać w uBo z filtrem proceduralnym (W ABP osoby z kursem szybkiego czytania pewnie rozpoznają tekst pop-upa zanim im zniknie).

Jak nawalą dziwnych enterów, co każde słowo to ratuje nas tylko "bakeCookie".

@gwarser jak wykrywać entery z pomocą `has-text`, bo regex się gubi z `/.*/`. Szkoda jak się nie da.

**Comment by gwarser** [comment]
@krystian3w spróbuj z `s` - `/regex z kropką dla entera./s` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll

**Comment by krystian3w** [comment]
Może to nie są Entery:

`view-source:data:text/html;charset=utf-8,%3Cp%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Wyra%C5%BCam%20zgod%C4%99%20na%20przechowywanie%20lub%20uzyskiwanie%20przez%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Zaufanych%20Partner%C3%B3w%20Telewizji%20Polsat%20Sp.%20z%20o.%20o%EF%B7%90.%20dost%C4%99pu%20do%20plik%C3%B3w%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20cookie%20p%EF%B7%AFrzechowywanych%20w%20moim%20urz%C4%85dzeniu%20przez%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Telewizj%C4%99%20Polsat%20w%20celach%20reklamowych%2C%20w%20tym%20ich%20profilowania.%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fp%3E`

`﷐` - dziwny znak "FDDO" dokleja się tylko jak ręcznie wklejamy, podgląd zaznaczenia go nie generuje.

**Comment by gwarser** [comment]
Jakiego programu i przeglądarki używasz? Ja tego nie widzę na Firefox w Manjaro ani na ChrEdge w Win10.

**Comment by krystian3w** [comment]
Firefox 91.0.1 na Windows 11 22k.160 raczej Dev niż Beta (uciekł na dobre wskaźnik zmiany).

**Comment by gwarser** [comment]
Skąd kopiujesz i gdzie wklejasz?

**Comment by gwarser** [comment]
To chyba taki ficzer Firefoksa, żeby w wygenerowanym podglądzie źródła strony pokazać gdzie się zaczyna i kończy zaznaczenie tekstu. 

Jak zaznaczysz "Domain" na `example.com` dostaniesz `...%EF%B7%90Domain%EF%B7%AF...`:

    view-source:data:text/html;charset=utf-8,%3Ch1%3EExample%20%EF%B7%90Domain%EF%B7%AF%3C%2Fh1%3E

**Comment by krystian3w** [comment]
Jeszcze zastanawiam się czy może  `\a` zadziała jak w `content:` z CSS.

**Comment by hawkeye116477** [comment]
@krystian3w Polsat Box Go testuje i tam jest taki sam popup.

**Comment by krystian3w** [comment]
https://polsatboxgo.pl/uzytkownik/zaloguj/regulaminy

Ile razy to akceptujemy?

**Comment by hawkeye116477** [comment]
Słaby serwis, Ipla była lepsza, bo mam numer w Plusie i miałem przywieleje, czyli jak dla abonamentów Polsatu robili promocję w postaci okienek otwartych, to ja też miałem za friko.

**Comment by krystian3w** [comment]
>> https://github.com/MajkiIT/polish-ads-filter/blob/4755aea006da00132817f9bff9407d94d9d560c5/cookies_filters/adblock_cookies.txt#L2132 https://github.com/MajkiIT/polish-ads-filter/blob/f50fbf15b2aad19489b90cdf6a1a578888ad2235/cookies_filters/adblock_cookies.txt#L2133

> na miganie polecamy [PCZ (PPC)](https://git.io/JEbKL), założenie wymaganego konta lub usługi iPolsat Box (dawne ICOK) lub specjalistę od skrypletów uBO (AdGuard postanowił pop-up akceptować podobnie jak PCZ)
