### ISSUE TITLE
polsatgo.pl

### ISSUE THREAD

**Issue by Lukjan38** [MajkiIT/polish-ads-filter#20161]
nie mozna patrzec na materialy

**Comment by xMaap** [comment]
Trzeba mieć konto, ale mail aktywacyjny nie przychodzi.

**Comment by Lukjan38** [comment]
do mnie od razu przyszedl

**Comment by Lukjan38** [comment]
jakby co, to wtorek i sroda, mnie nie ma na kompie.

**Comment by krystian3w** [comment]
Na Onet doszła błyskawicznie...

Dziwne że dyskryminują Interię/Gmail/WP...

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/129633049-2c7dfbab-b280-4ccd-856a-9dafcb9cc57c.png)


Może AdamWr już rozpracowuje naprawę odtwarzacza: https://github.com/AdguardTeam/AdguardFilters/issues/91253

**Comment by seba2282** [comment]
Ale ja usunąłem całkowite blokowanie gemius. @krystian3w

**Comment by krystian3w** [comment]
Ale ono jest w Polish Privacy Filters czy choćby EasyPrivacy, raczej obu nie nadpisujesz na bieżąco z pomocą `,badfilter`.

* https://github.com/easylist/easylist/blob/4db2c111818a07afe4fc41e5b14c583457bb3767/easyprivacy/easyprivacy_trackingservers.txt#L1022
* https://github.com/easylist/easylist/blob/eb1611a5b4796312e22af8833da04e452279c813/easyprivacy/easyprivacy_general.txt#L2010-L2015
* https://github.com/easylist/easylist/blob/eb1611a5b4796312e22af8833da04e452279c813/easyprivacy/easyprivacy_general.txt#L5003-L5005

~~

* https://github.com/olegwukr/polish-privacy-filters/blob/1d59b558ca2cf921bc30e18eacb05319dde1b77b/adblock.txt#L19-L22
* https://github.com/olegwukr/polish-privacy-filters/blob/1d59b558ca2cf921bc30e18eacb05319dde1b77b/adblock.txt#L92
* https://github.com/olegwukr/polish-privacy-filters/blob/1d59b558ca2cf921bc30e18eacb05319dde1b77b/adblock.txt#L94

**Comment by seba2282** [comment]
@krystian3w, a po co odblokowałeś te googleapis, jeżeli mowa o gemius? Te dwie blokują? Ja wywaliłem całkowite blokowanie na important all, bo miałem problem z playerami radio zet na przykład. Ale za prawdę powiadam ci, 3/4 śmieci reklamowych idą przez gemius/adocean/smartadserver/adserver. I to trzeba jakoś blokować. A sprawdziłeś, jak filtr bogachenko sobie radzi? Może do niego, jak nasi nie chcą dodać reguł?

**Comment by krystian3w** [comment]
Raczej żadnym:

- ipla = 0
- polsat = 1 FP o pilot.wp.pl a ma notatkę że WP nie naprawia jak chodzi o anty-adblock

Więc jak ci naprawia to ma jakiś generyk, że dopuszcza wszędzie plik `ima3.js` lub "3/4 gemiusa".

**Comment by xxcriticxx** [comment]
trzeba poczekac do 1 września az skoncza zmieniac wszystko

Świat zmienia się, a my wraz z nim. Polsat Box Go to marka, która od 1 września zastąpi marki Ipla i Cyfrowy Polsat Go. Wychodząc naprzeciw oczekiwaniom klientów, Polsat Box Go zapewni szeroki wybór treści i sposobów dostępu do nich - każdy będzie mógł oglądać ulubione treści i kanały - sportowe, filmowe, serialowe czy bajki w przystępnej dla niego technologii.
Dzięki harmonizacji serwisów i aplikacji ulubione treści będą dostępne online i na żądanie na różnych urządzeniach – telewizorze, smartfonie, tablecie, komputerze czy laptopie, w dowolnym miejscu i o dowolnej porze, kiedy i jak się chce. Teraz Ty rządzisz. Wybierz swoje wszystko.

**Comment by krystian3w** [comment]
Raczej nie wymyślą trudniejszego kodu anty-adblock.

**Comment by seba2282** [comment]
> trzeba poczekac do 1 września az skoncza zmieniac wszystko
> 
> Świat zmienia się, a my wraz z nim. Polsat Box Go to marka, która od 1 września zastąpi marki Ipla i Cyfrowy Polsat Go. Wychodząc naprzeciw oczekiwaniom klientów, Polsat Box Go zapewni szeroki wybór treści i sposobów dostępu do nich - każdy będzie mógł oglądać ulubione treści i kanały - sportowe, filmowe, serialowe czy bajki w przystępnej dla niego technologii.
> Dzięki harmonizacji serwisów i aplikacji ulubione treści będą dostępne online i na żądanie na różnych urządzeniach – telewizorze, smartfonie, tablecie, komputerze czy laptopie, w dowolnym miejscu i o dowolnej porze, kiedy i jak się chce. Teraz Ty rządzisz. Wybierz swoje wszystko.


Od ulubionych treści mamy inne portale i to za darmo można obejrzeć. A te pseudo legalne wołają kasę i świecą pustką. Więc o czym mowa? Opłacam internet, to czemu w pakiecie nie obejrzeć online czegoś za darmo? Tylko płać i płać?  😂😂😂

**Comment by seba2282** [comment]
> Raczej żadnym:
> 
> - ipla = 0
> - polsat = 1 FP o pilot.wp.pl a ma notatkę że WP nie naprawia jak chodzi o anty-adblock
> 
> Więc jak ci naprawia to ma jakiś generyk, że dopuszcza wszędzie plik `ima3.js` lub "3/4 gemiusa".



I to jest bez sensu. Bo gemius, który połączył się z adocean, to najgorsze śmieci. Po co takie coś używać?

**Comment by hawkeye116477** [comment]
`Polsat Box Go to marka, która od 1 września zastąpi marki Ipla i Cyfrowy Polsat Go. `

Tyle, że Polsat Box Go i Polsat Go to 2 różne serwisy :stuck_out_tongue: 
Polsat GO to darmowa część Ipli, a Polsat Box Go to płatna.

**Comment by krystian3w** [comment]
AdamWr używa json-prune ale chyba też cały AdGuard team poległ na oczyszczaniu rządań pliku `/ima3.js`.

Czyli Gemius da pewnie się pominąć jak dodatek wspiera dobrze `json-prune`.

**Comment by seba2282** [comment]
Mogę dodać z powrotem te blokady na all. Ale potem potrzebuję odblokować np. playery w radio zet. Nie wiem dlaczego strony bazują na tych śmieciach od gemius/adocean/smartadserver/adserver. 3/4 najgorszych śmieci jest stąd. 


Do @AdamWr masz jakąś koncepcję? Pytam do ciebie i jak znajdziesz chwilę, liczę na jakąś odpowiedź prosto od ciebie.

**Comment by krystian3w** [comment]
Może idą w płatne reklamy (trzeba porównać czy blok reklamowy FM jest identyczny z tym internetowym - jak różne to widać reklama klasyczna daje za mało zysku i lepiej rekompensuje to gemius/adocean), chyba że nie na to pokrycia z nadawaniem FM.

Być może `json-prune` pod radio zet nie może istnieć lub jest zbyt niestabilny w ciągu dnia.

Co do sięgania po tamte gotowce to może trudniej uruchomić własny odtwarzacz i w nim pre-roll i mid-roll ads (np. Gemius/AdOcean ma "doświadczenie").

Trud w neutralizacji `/ima3.js` może leży w tym samym jak na stronie zawodzi neutralizacja gpt.js czy google analityki.

**Comment by seba2282** [comment]
W easy privacy są reguły dla playerów i widzę jest przepuszczony fragment gemius js stream czy jakoś tak i coś jeszcze drugie js. Jak dam zablokuj cały gemius important, wtedy playery mają ładowanie w nieskończoność. Czyli coś trzeba znaleźć pośredniego.

**Comment by krystian3w** [comment]
Możliwe,  że te dwa dopuszczenia są za duże do analizy jak je naprawić skrypyletami.

Potem czy jest cień szansy na napisania źródła zneutralizowanego jak skryplety za bardzo ograniczają pole manewru.

**Comment by seba2282** [comment]
@krystian3w faktycznie coś w tym jest, co mówisz. I trzeba coś znaleźć, co zablokuje te śmieci internetowe typu gemius/adocean, a jednocześnie strony będą działać.

**Comment by Lukjan38** [comment]
dzieki, dziala.

**Comment by seba2282** [comment]
@krystian3w Dopuściliście cookies. Widzę je aktualnie.

**Comment by krystian3w** [comment]
Nikt nic nie dopuszczał, nie mamy na zapleczu wróżki co by na dzień przed recytowała kod HTML5 strony - za dużo oglądasz "paranormal activity" 🤪😝.

**Comment by hawkeye116477** [comment]
`będzie piekł ciastko`

Tylko, że niestety, ale samo ciacho nie wystarcza. Oni chyba jeszcze ustawiają wartość local storage, w której jest ip i inne rzeczy.

**Comment by olek52** [comment]
polsatgo.pl   przy użyciu uBlock Origin pojawia się komunikat aby wyłaczyc oprogramowanie do blokowania reklam patrz foto https://zapodaj.net/56b06b4442cf2.png.html pomoże  ktoś   ?  a jesli już  cos  takiego jest  to jak to zainstalowac  ? Dziekuje za pomoc

**Comment by xxcriticxx** [comment]
@olek52 dodaj to do wlasnych filtrow: 

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=polsatgo.pl`
`@@||gemius.pl/$script,domain=polsatgo.pl`

**Comment by seba2282** [comment]
@xxcriticxx Bogachenko też by mógł dodać do swojego filtra te reguły, bo to na anty Adblock, widzę. Więc teoretycznie Oleg powinien też dodać do filtra dla pl anty Adblock. I jestem ciekaw, jak @MajkiIT załatwi z nim sprawę. 


Swoją drogą @MajkiIT miło ciebie usłyszeć ponownie. ☺️

**Comment by hawkeye116477** [comment]
Dzisiaj była jakaś aktualizacja => https://github.com/olegwukr/polish-privacy-filters/commit/658774030a161b3828d0c749760beff9fee960dc.

**Comment by olek52** [comment]
@xxcriticxx   przepraszam  Cię  bardzo  a tak  na  rozum laika    bo nie wiem co i jak dodac do filtrów  .przepraszam  pomożesz krok po kroku ?

**Comment by AroKol78** [comment]
@olek52 może to będzie pomocne 
zaznacz "My-filters" info-> https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists
następnie wklej do "My-filters" info-> https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=polsatgo.pl
@@||gemius.pl/$script,domain=polsatgo.pl
```

**Comment by hawkeye116477** [comment]
Tyle tylko, że Aro pominął najważniejsze, bo zapewne olek nie wie jak odpalić panel sterowania uBO. Otóż należy kliknąć na ikonkę uBO i potem jak na fotce.

<img src="https://majkiit.github.io/polish-ads-filter/images/wiki/uBO_add1.png">

A potem to co pisze Aro.

**Comment by olek52** [comment]
@hawkeye116477   @xxcriticxx  @AroKol78  . Ale  drozdy nie wiecie że jestem tak cienki   i zapomnieliście  napisać  gdzie mam to wstawić  (czyli w uBlock Origin) wypiłem kawę i cos  dotarło  .  Dzięki za pomoc  i cierpliwość

**Comment by AroKol78** [comment]
> polsatgo.pl przy użyciu uBlock Origin pojawia się komunikat aby w ...

> ...zapomnieliście napisać gdzie mam to wstawić (czyli w uBlock Origin)...

normalnie jestem zmieszany i wstrząśnięty :smile:

**Comment by krystian3w** [comment]
Niby oleg skopiował dopuszczenia ale nie wykupił premium na `polsatgobox.pl` by i tam naprawić.

**Comment by krystian3w** [comment]
Filtry skopiowane, czas wykupić abonament na 30 dni by sprawdzić czy tam jest adblock:

`https://polsatboxgo.pl/start`

**Comment by seba2282** [comment]
Po co radykalnie? Nie ma opcji do przetestowania przed kupnem? Wtedy fake account, test abonament na ileś dni bez opłat i sprawdzić. CDA to umożliwia przy premium chyba są 7 czy 14 dni za darmo. @krystian3w

**Comment by hawkeye116477** [comment]
No niestety nie ma testów za friko. Mogę się logować kontem z Ipli i niestety pakietu darmowego dla posiadaczy Plusa na kartę też nie ma. Za to czytałem, że jak ktoś opłaca abonament w PB, to może sobie oglądać kanały w PB GO bez dodatkowych opłat.
