### ISSUE TITLE
auto-swiat.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2017]
Strona wykrywa adblocka (to samo co na onecie) - `http://www.auto-swiat.pl/eksploatacja/benzyna-czy-diesel-ktory-jest-trwalszy-i-stwarza-mniej-problemow/r1hk0y`

![image](https://cloud.githubusercontent.com/assets/11742596/22108174/1557e42c-de52-11e6-8fcb-096178ab0262.png)

Chyba powinno wystarczyć:
`@@||auto-swiat.pl^$generichide`
`auto-swiat.pl#@#.trizer-bnr`

**Comment by MajkiIT** [comment]
@F4z Dzięki
