### ISSUE TITLE
Usunięcie ngastatic.com z whitelisty

### ISSUE THREAD

**Issue by MaciejTarmas** [MajkiIT/polish-ads-filter#2018]
Prośba o usunięcie tej pozycji:

`@@||ngastatic.com/*/collect.js$script,domain=allegro.pl`

Na chwilę obecną nie ma już potrzeby whitelistowania domeny ngastatic.com, żeby Allegro działało poprawnie.

Obecność tego wpisu powoduje błędne działanie serwisu na wersji rozwojowej uBlock Origin dla Safari. Na liście przedmiotów nie ładują się wyskakujące opisy, nie można kliknąć tytułu aukcji i nie ładuje się koszyk.

Testowo wykomentowałem sobie tę linię i wszystko wraca do normy.

Prawdopodobnie to jest przyczyną tego buga:

https://github.com/MajkiIT/polish-ads-filter/issues/2007

Pozdrawiam,

Maciek (AlleBlock)

**Comment by MajkiIT** [comment]
Ok Dzięki
