### ISSUE TITLE
test regula 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2019]
@MajkiIT @F4z mozna gdzies pogadac poza github? na jakis chacie na 5 min mam pomysl to obgadania

**Comment by xxcriticxx** [comment]
niech moze ktos jakis chat skelic i poda info na email please ja jestem wolny za 20-30 min a jak nie to jakis inny czas

**Comment by MajkiIT** [comment]
FB?

**Comment by MajkiIT** [comment]
skype?

**Comment by xxcriticxx** [comment]
nie jakis chat na necie

**Comment by MajkiIT** [comment]
http://czat.wp.pl/i,1489,chat.html
