### ISSUE TITLE
az-polska.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20200]
( na środku )

https://www.az-polska.com/firmy/gazeta_miejscowa_legionowo_mz_wilanowska_1

**Comment by krystian3w** [comment]
@hawkeye116477 to miejsce raczej dla tego co zamieści "ogłoszenie", może być pomocne chyba.

**Comment by hawkeye116477** [comment]
Ta, mapy raczej nie usuwamy, ale została resztka „udostępnij”.

**Comment by krystian3w** [comment]
Bardziej mi chodziło o sekcję wideo, potem niby "Portale społecznościowe".

Wycięcie widea może działać jak nadgorliwość gargulca, że mu byle jakich wideo z sidebarów nie wycinamy.
