### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by Adasss** [MajkiIT/polish-ads-filter#2022]
Witam. Czy tylko u mnie wyskakuje plansza sprawdź jak wyłączyć blokowanie reklam np na: http://player.pl/programy-online/fakty-odcinki,516/odcinek-6958,18-01-2017,S00E6958,68935.html
Firefox 50.1.0
uBlock i zaptaszkowane "Anti-Adblock Killer | Reek‎ (github.com)"
Cos jeszcze trzeba zrobić ??

**Comment by xxcriticxx** [comment]
@Adasss umnie dziala ale narazie mam 2 min reklam przed faktami

![capture](https://cloud.githubusercontent.com/assets/15007183/22128965/553530d0-de71-11e6-8af1-acbc40c98da4.PNG)

**Comment by Adasss** [comment]
Ja nawet tych 2 min nie mam :/ Czyli jednak ja coś źle robię :/ Jak teraz dojść co jest nie tak ?

**Comment by xxcriticxx** [comment]
@Adasss polecam jedna wtyczkę na raz więcej nie trzeba super bendzie działać na jednym ublock orgin

`https://m.youtube.com/watch?v=Q24rqrNCe9g`

**Comment by Adasss** [comment]
Dzieki, działa świetnie. Pozostaje jeszcze pytanie co u mnie jest nie tak ze wykrywa mi ublocka i nie puszcza filmu? Oprócz admunchera, ublocka, i greasemonkey nie mam praktycznie innych wtyczek :/

**Comment by MajkiIT** [comment]
@xxcriticxx jaka przeglądarka? 
@F4z jaka przeglądarka?

W chrome nie ma silverlight.

**Comment by Adasss** [comment]
Zainstalowałem FF portale, i świeże wtyczki (Greasemonkey i uBlock Orgin). Do obu dodałem AAK i dalej po kliknięciu play wyskakuje plansza ze mam wyłączyć adblocka... Jakoś nie umiem sobie wyobrazić ze zrobiłem coś źle...

**Comment by MajkiIT** [comment]
@Adasss Mam to samo co ty na FF. @xxcriticxx ma pewnie chrome

**Comment by Adasss** [comment]
Dziwne bo na chrome (Wersja 55.0.2883.87 m (64-bit) + Tampermonkey i uBlock Orgin) mam to samo :/ Po wyłączeniu uBlock oglądam 2min reklam i mogę zobaczyć odcinek.

**Comment by xxcriticxx** [comment]
@MajkiIT safari na iphonie

**Comment by mathew85** [comment]
U mnie Adblock(Google Chrome 56):

`http://player.pl/programy-online/fakty-odcinki,516/odcinek-6962,22-01-2017,S00E6962,68939.html?atpl#play`

![image](https://cloud.githubusercontent.com/assets/11385099/22218075/aae319ca-e1a5-11e6-80e6-6b9bb10abcdd.png)

**Comment by F4z** [comment]
Jeśli chodzi o wykrycie adblocka to można dodać te reguły:
`@@||player.pl^$generichide`
`@@||tvn.adocean.pl/ad.xml$xmlhttprequest,domain=player.pl`
`@@||tvn.adocean.pl/__/ad.xml$xmlhttprequest,domain=player.pl`
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=player.pl`

Niestety w momencie kiedy będzie się chciała załadować reklama, to wyświetli się komunikat, że "materiał jest niedostępny".
Po dodaniu tej reguły powinno się odtwarzać, ale będę też reklamy:
`@@||redcdn.pl/*/TVN-Adserver/*.mp4$xmlhttprequest,media,domain=player.pl`

Tutaj jest podobne zgłoszenie - https://github.com/MajkiIT/polish-ads-filter/issues/1324

**Comment by mathew85** [comment]
Ok. Może na forum AdGuarda, by sobie z tym poradzili? Widziałem, że za pomocą skryptów z wp.pl im się udało. Chyba, że ten temat był już sprawdzany i nic nie można zrobić?

**Comment by F4z** [comment]
Był temat na forum Adguarda - https://forum.adguard.com/index.php?threads/resolved-video-not-playing-at-all-on-www-player-pl.10376/
W przypadku Adguarda dla Windowsa zostały dodane odpowiednie reguły i nie ma reklam, niestety w przypadku rozszerzenia po prostu zostały odblokowane reklamy.

Ale zawsze można ich o to zapytać, na przykład tutaj - https://forum.adguard.com/index.php?forums/custom-filters.69/

**Comment by F4z** [comment]
Swoją drogą tutaj ktoś podał zmodyfikowany skrypt AAK - https://github.com/X01X012013/AdBlockProtector/issues/23#issuecomment-261581585
http://pastebin.com/raw/PFecTWk1
Z tego co widzę to w większości przypadków działa, tylko trzeba poczekać kilka sekund na podmianę odtwarzacza.

**Comment by mathew85** [comment]
> https://forum.adguard.com/index.php?threads/resolved-player-pl.19371/

Działa bez reklam jedynie w AdGuard For Windows. Przy samym rozszerzeniu reklamy zostają. Chodzi pewnie o to:

> It will work when browser extensions support $empty.

Pytanie czy uBlock to wspiera?

**Comment by F4z** [comment]
uBlock nie ma czegoś takiego jak `empty`, za to ma coś takiego jak `redirect`, na przykład:
`||adocean.pl/*ad.xml$xmlhttprequest,domain=player.pl,important,redirect=nooptext`
Niestety w tym przypadku to nie pomaga.

**Comment by mathew85** [comment]
Właśnie też coś takiego kleiłem i również mi nie działa.
@F4z dałbyś rade może się spytać na uBlocku odnośnie tego? Ja mogę napisać tylko nie wiem, które jeszcze reguły potrzebujemy, aby to wszystko odblokować?

**Comment by F4z** [comment]
Prawdopodobnie te:
`@@||player.pl^$generichide`
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=player.pl`

`@@||tvn.adocean.pl/ad.xml$xmlhttprequest,domain=player.pl`
`@@||tvn.adocean.pl/__/ad.xml$xmlhttprequest,domain=player.pl`

Po dodaniu tych reguł powinien wyświetlać się komunikat "materiał jest niedostępny" albo powinien normalnie działać film.
Gdy pojawia się komunikat, to wtedy trzeba odblokować reklamy (ewentualnie odświeżyć kilka/kilkanaście razy stronę, chociaż to nie zawsze działa):
`@@||redcdn.pl/*/TVN-Adserver/*.mp4$xmlhttprequest,media,domain=player.pl`

Też tak sobie myślę, że to może nie działać z tego powodu, że w przypadku `empty` kod odpowiedzi HTTP to 200 (OK), a w przypadku `redirect` to 307 (Temporary Redirect) i dlatego to jakby "odrzuca/wykrywa", ale mogę całkowicie się mylić, bo się na tym nie znam :P
https://pl.wikipedia.org/wiki/Kod_odpowiedzi_HTTP

Problem z player.pl też jest taki, że osoby spoza Polski muszą to sprawdzać przy użyciu VPNów, czy innych programów do zmiany IP.
