### ISSUE TITLE
megawypas.com

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#20236]
Taki kwiatek wyskakuje u mnie na Adguardzie ale wiem też że swieci i na ubo

![Screenshot_1](https://user-images.githubusercontent.com/21177361/131629537-ba04b9f0-2608-4549-9a87-64ddf5a9fb3a.png)

**Comment by hawkeye116477** [comment]
Wszystko fajnie, ale to duplikat #20108 i pan Oleg od 27 maja nie robił żadnej aktualizacji, więc zapewne trzeba poprosić gorhilla, by zadziałał albo ewentualnie przerzucić się na listę pana B....

**Comment by xxcriticxx** [comment]
duplicate closing
