### ISSUE TITLE
polsatbox.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#20237]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
http://polsatbox.pl/index.jsp
```

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Vivaldi 4.1.2369.21 

### Bloker (Blocker)

uBlock Origin 1.37.2

### Używane listy filtrów (Used filter lists)

Domyślne uBO + AdGuard Base

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Ktoś coś za dużo wycina.

![2021-09-01_10-56](https://user-images.githubusercontent.com/19818572/131642710-2a0a5608-a250-4e63-8c43-ced6467aa511.png)

Naprawa:
```
@@||myao.adocean.pl/files/$image,domain=polsatbox.pl
@@||myao.adocean.pl/*ad.xml$domain=polsatbox.pl
```

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Nie trzeba odblokowywać, kiedyś zrobiłem filtr na ukrywanie placeholdera/lefovera.

**Comment by krystian3w** [comment]
@seba2282 pilnuj ten wątek, bo ci odblokują tracking.

**Comment by seba2282** [comment]
@krystian3w  Jaki tracking? Jeżeli wolno spytać?

**Comment by krystian3w** [comment]
Adocan - tracking gemius.

**Comment by seba2282** [comment]
Ale powiedziałem, że miałem problemy ze stronami i global gemius itp all usunąłem z reguł. Bo są konflikty

**Comment by xxcriticxx** [comment]
ktos wie czy @MajkiIT zyje? co robimy z watkami adblock?

sorry za hijack

**Comment by hawkeye116477** [comment]
3 dni temu jeszcze coś robił => https://github.com/MajkiIT/polish-ads-filter/commit/e46188023e3d11635add76df6f581d36a4b63749, więc raczej żyje, ale pewnie znalazł lepszą płatną robotę i brakuje mu już czasu.

**Comment by krystian3w** [comment]
Nie mamy żadnej mocy, Oleg przecież nie akceptuje PR od ~1,5 roku (z 3 moje dodał i potem zamykał, więc nie polecam robić).

Jedną opcją to tajne fejk konta u Olega, ale pewnie sprytni znajdą dopasowanie jaki kto nick wylosował - najlepiej robić commity jak Rosjanie i Francuzi (mail ustawiają na nieużywany w github, jedynie follow pozwala ustalić czy np. PolishJarvis dodał sam commit czy moimi rękami na podstawie błędnej konfiguracji git).

**Comment by xxcriticxx** [comment]
moze damy pare dni i zobaczymy czy @MajkiIT cos odpisze

**Comment by xxcriticxx** [comment]
Oczywiscie mozemy tutaj nowa liste otworzyć tylko kazdy sam recznie bedzie musial dodac do swego blokera.

**Comment by hawkeye116477** [comment]
A pisał ktoś maila do Olega?

**Comment by xxcriticxx** [comment]
nope

**Comment by krystian3w** [comment]
A na tej nowej płatnej ipli też jest adblock?

**Comment by MajkiIT** [comment]
@xxcriticxx jeszcze żyję. ... powoli to ogarnę. Postaram się do poniedziałku. Olega też kopnę trochę.

**Comment by xxcriticxx** [comment]
@MajkiIT dzieki za pomoc!

**Comment by hawkeye116477** [comment]
I znowu cisza przed burzą.... To jak będzie odblokujecie te 2 pliki (https://github.com/MajkiIT/polish-ads-filter/issues/20237#issue-984889290).?

**Comment by MajkiIT** [comment]
@hawkeye116477 no problem nie jest taki prosty jak ci się wydaje :D . Konsolę kupiłem dawno, ale nawet jej nie tknąłem . Robię co mogę, ale w obecnej chwili wybrałem to co jest krytyczne.
