### ISSUE TITLE
leroymerlin.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20245]

**Comment by krystian3w** [comment]
U mnie nie ma i nie miga, konkretny link potrzebny? WaterFox Classic falling website?

fyi @hawkeye116477

**Comment by krystian3w** [comment]
Kiobke ma dwa generyki a my nawet to:

https://github.com/MajkiIT/polish-ads-filter/blob/f99431f5d5f7dd2ed9bcef2235c008fbd6860ace/cookies_filters/adblock_cookies.txt#L54

Jak generyki nie wyrabiają na CPU i nasza gąsienica, to ja nie wiem czy nie trzeba gąsienicę sztucznie dzielić po 30 domen na linię.

**Comment by hawkeye116477** [comment]
Jest ok, nie ma komunikatu.
