### ISSUE TITLE
pomponik.pl + biznes.interia.pl

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#20249]
`https://www.pomponik.pl/plotki/news-krzysztof-ibisz-ujawnia-szczegoly-slubu-myslelismy-ze-poradz,nId,5469976`
`https://biznes.interia.pl/praca/news-linie-lotnicze-cathay-pacific-zwolnily-pracownikow-za-odmowe,nId,5469966`

"ubo legacy 1.16.4.30" ------------- przez "EasyPrivacy" -> `||hit.interia.pl^`
na szybko `@@||iwa3.hit.interia.pl/iwa_core^$script,domain=biznes.interia.pl|pomponik.pl`

to mi nie działa `@@||iwa3.hit.interia.pl^*/iwa_core?ts=$domain=pomponik.pl|interia.pl`
"POL: Oficjalne polskie filtry przeciwko alertom o Adblocku" (zastanawiam się co w tym przypadku robi `^*`)

(drobne niedopatrzenie 2x`videotarget.pl` "POL: Oficjalne polskie filtry przeciwko alertom o Adblocku")

**Comment by krystian3w** [comment]
to chyba zapis skopiowany od adamaWr, może atrybut ts= nie istnieje.

Jak dla mnie użycie daszka w ścieżce jest błędne: `/iwa_core^$`.

**Comment by AroKol78** [comment]
> może atrybut `ts=` nie istnieje lub jest 2 lub 3 w linku.

`ts=` jest - chciałem uprościć - jedną tą samą rzecz można zapisać na wiele sposobów 
"ubo logger" 
`@@||iwa3.hit.interia.pl/iwa_core?ts=1631704124068&u=https%3A%2F%2Fbiznes.interia.pl%2Fpraca%2Fnews-linie-lotnicze-cathay-pacific-zwolnily-pracownikow-za-odmowe%2CnId%2C5469966&sh=biznes.interia.pl$script,domain=biznes.interia.pl`

> jest błędne

za duże słowo, `^` najwyżej jest zbędne ale nie przeszkadza - działa na ubo legacy, nie testowałem na Adguard

nie mam tak wielkiej wiedzy jak Ty i zapewne masz racje

**Comment by krystian3w** [comment]
W tamtym miejscu ma ograniczać niby FP z takimi trollami:

`hit.interia.pieguski.icu/plexi/iwa_core`

Jak interia uruchomi Gemius spod losowej domeny typu "pieguski.icu" to może filtr Adama paść (filtr dopuszcza po prostu zagłębienie pliku w dziwnych folderach np. "/plexi/".

**Comment by AroKol78** [comment]
czyli tak powinien wyglądać filtr od mojego zgłoszenia
`@@||iwa3.hit.interia.pl/iwa_core?ts=$script,domain=biznes.interia.pl|pomponik.pl`
i trzeba przywrócić poprzedni
`@@||iwa3.hit.interia.pl^*/iwa_core?ts=$domain=pomponik.pl|interia.pl`

**Comment by krystian3w** [comment]
@olegwukr

**Comment by MajkiIT** [comment]
@krystian3w już Oleg wrzucił. Zaraz pojawią się zmiany. Dzięki

**Comment by krystian3w** [comment]
Ok.
