### ISSUE TITLE
flashscore.pl

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#2027]
http://www.flashscore.pl/
Proszę zablokować:
![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/22175115/f7295014-dfee-11e6-80b3-44c7f43e4939.PNG)
Adres tej reklamy to: http://www.flashscore.pl/promobox/3105/?sport=1

**Comment by F4z** [comment]
Na przykład:
`flashscore.pl##.scrolling-box-under-content`
