### ISSUE TITLE
autocentrum.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#2028]
Reklama.

Dodatkowo:
https://forums.lanik.us/viewtopic.php?f=62&t=35151

![image](https://cloud.githubusercontent.com/assets/11385099/22175308/af64f586-dff2-11e6-94b0-a7cdd4bd303a.png)

**Comment by F4z** [comment]
Dzięki.
Dla uBlocka:
`autocentrum.pl##script:inject(abort-on-property-write.js, ub_ct_load)`

Dla Adblocka:
`autocentrum.pl###new_banner + div[style="max-width: 750px; margin: 0 auto; padding-bottom: 15px;"]`
`autocentrum.pl##img[src^="data:image"]`
