### ISSUE TITLE
filmomaniak.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#20289]
https://filmomaniak.pl/
![Zrzut ekranu z 2021-09-25 02-47-26](https://user-images.githubusercontent.com/36385327/134752286-31f03093-d216-4455-bbc7-c6d1a4a8a5e3.png)
![Zrzut ekranu z 2021-09-25 02-50-11](https://user-images.githubusercontent.com/36385327/134752298-8ffe5d01-9319-4f47-aa80-c174e0f4d1df.png)
![Zrzut ekranu z 2021-09-25 02-50-28](https://user-images.githubusercontent.com/36385327/134752306-e334aa0e-1388-4aba-bedc-adb3f17fc3e9.png)

https://filmomaniak.pl/tvfilmy/
![Zrzut ekranu z 2021-09-25 02-50-46](https://user-images.githubusercontent.com/36385327/134752313-361c0845-bd61-4f4b-a176-9fdc1d525235.png)

https://filmomaniak.pl/tvfilmy/
![Zrzut ekranu z 2021-09-25 02-51-04](https://user-images.githubusercontent.com/36385327/134752318-2f7e02ba-a89a-45a8-ab8b-14d2b31f36d2.png)

**Comment by krystian3w** [comment]
@MajkiIT  chyba reklamy w nagłówku:

`##.baner-inner2`

**Comment by krystian3w** [comment]
@hawkeye116477 / @blocker999 zostawiamy ten obrazek i napis:

![obraz](https://user-images.githubusercontent.com/35370833/134821292-c50134d5-1ddf-474b-966e-0cf3b4f557b0.png)


Niby w elemencie social mocno osadzony, mogą w każdej chwili zmienić tekst na "śledź nas w social mediach".
