### ISSUE TITLE
teledyski.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#20293]
test link:
http://mp3.teledyski.info/link/?id=YzJTeTVzRTdHQ0NGMDBUTDFSOXREY09jaXBuVzZsYVE3VzJvdDJ3SUFXMXdNekoxVEVoTmNUSklXbGhaV2tsR2ExcE9ZV2RYUjA1TmVHOTRRbGczZEVodFdWWkpkWEkwV0ZSa1RIVTNXa3RyVUd0WVlpdHNjVGhwYWtwSE5HTTQ=

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/16407 https://github.com/MajkiIT/polish-ads-filter/issues/13186

**Comment by krystian3w** [comment]
Mnie się otwiera:

```
http://hostuje.net/file.php?id=0938690c496cfde2fc8f5408c1df4d09
```

bez reklam, może kiboke źle napisał klikanie co pop-up cookies...

**Comment by krystian3w** [comment]
W uBo zobaczcie:

`teledyski.info##+js(set, GFSJHGSYUNNBSDYOOWJHSGI, true)`

Jak działa to 3 rok nie zmienili nazwy losowej i chyba tylko o Adblock Plus/AdBlock słyszeli... 🤣.

**Comment by krystian3w** [comment]
W Pi-Hole do wyjąktów ręcznych dodaj:

`stats.teledyski.info`

bo ten filtr z nim się nie dogada:

https://github.com/MajkiIT/polish-ads-filter/blob/d940640383c375a0fb7caf1f983a020caa445e0c/polish-pihole-filters/firebog-Easyprivacy.txt#L9640 https://github.com/MajkiIT/polish-ads-filter/blob/a204e6d68f1005b58d53b023690754e85de9d583/polish-pihole-filters/easy_privacy_host.txt#L9969

**Comment by krystian3w** [comment]
@MajkiIT / @olegwukr pracujecie nad listą dopuszczeń pod Pi-Hole czy raczej użytkownicy muszą sami pisać dalej dopuszczenia lub liczyć że naprawi to `set-constant.js` wbudowany w ABP/AdBlock/AdGuard/uBO?

**Comment by krystian3w** [comment]
Mnie się otwiera:

```
http://hostuje.net/file.php?id=0938690c496cfde2fc8f5408c1df4d09
```

bez reklam/adblocka, może Kiboke źle napisał klikanie co zamknie pop-up cookies...

---


W uBo zobaczcie:

`teledyski.info##+js(set, GFSJHGSYUNNBSDYOOWJHSGI, true)`

Jak działa, to 3 rok nie zmienili nazwy losowej i chyba tylko o Adblock Plus/AdBlock słyszeli... 🤣.

**Comment by xxcriticxx** [comment]
pihole blokowalo teraz jest gitara

**Comment by krystian3w** [comment]
to możesz dodać tag pi-hole.

W blokerach treści mamy naprawione dopuszczeniem `@@/ads.js` https://github.com/olegwukr/polish-privacy-filters/blob/0798eed1340b20807bcae3a2a1a325c9d2d8015a/anti-adblock.txt#L272
