### ISSUE TITLE
grupa onet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#20303]
na request @krystian3w

**Comment by AroKol78** [comment]
źródło "AdGuard Base"
`onet.pl##div[class^="AdPlaceholder_"]`
`onet.pl##aside[class^="CenterAd_container"]`
(nie wszyscy używają "AdGuard Base")

**Comment by krystian3w** [comment]
Znane domeny z należenia do Onet:

`auto-swiat.pl,businessinsider.com.pl,fakt.pl,komputerswiat.pl,noizz.pl,ofeminin.pl,plejada.pl,przegladsportowy.pl`

**Comment by AroKol78** [comment]
`onet.pl##.desktop-ad-placeholder`
