### ISSUE TITLE
Grupa interia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#20301]
na request @AroKol78

**Comment by AroKol78** [comment]
kwadrat z napisem reklama
`https://deccoria.pl/artykuly/porady-domowe/jak-uporzadkowac-kable-najlepszy-sposob-na-porzadek-w-domu-25-9383`
POL-0 lista
wymiana `deccoria.pl##div[class="dc-billboard advert-250-box"]`
_____na `deccoria.pl##div[class="dc-billboard advert-250-box has-ad"]`

**Comment by felix-22** [comment]
Taka ciekawostka - może to dziwne ale prawdziwe, zastanawiałem się dlaczego nie mam tego kwadratu, i wyskoczył dopiero po wyłączeniu listy: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt, próbowałem znaleźć w loggerze, która to niby reguła go ukrywa, ale nie mogę znaleźć, więc odpuściłem.

<hr>

> xxcriticxx : na request @AroKol78

Jak tam chcecie, ale zaraz może przyjść ktoś inny i zachce kolejnej Grupy np. dla onet.pl

**Comment by krystian3w** [comment]
To ja poproszę o założenie wątku grupa `onet.pl` też domeny majkiit zaniedbuje i obrywa za to zgłoszeniami AdGuard i AdamWr.

**Comment by AroKol78** [comment]
> Taka ciekawostka - może to...

ma włączone "NoCoin Filter List 394 used out of 649" i jest kwadrat z napisem deccoria/reklama

**Comment by felix-22** [comment]
Sprawdziłem jeszcze raz dokładniej i to jeden z tych posranych przypadków, gdzie problem jest losowy, rzeczywiście - nie "NoCoin Filter List" jest przyczyną, ale tak to złudnie wyglądało, bo gdy włączałem tę listę to kontener znikał, a gdy wyłączałem to się z nowu pojawiał, ale widocznie to losowy przypadek, i nie zależy to od tej listy, nie wiem w takim razie od czego to zależy, ale w każdym razie problem nadal wystepuje:
- na Firefoxie gdy przeładuję stronę powiedzmy 10 razy, to czasem kontener się pojawia, a czasem nie, może jakiś filtr raz łapie, a innym razem nie łapie, Sprawa dla Reportera...

**Comment by AroKol78** [comment]
`https://deccoria.pl/filmy` kwadrat z napisem deccoria/reklama 
dodać `deccoria.pl##div[class="dc-billboard advert-250-box advert-250_margin has-ad"]`
lub 
zastąpić to https://github.com/MajkiIT/polish-ads-filter/commit/49abae1540170bd84ab4f47138c190dab05edc90#diff-eab2aaf469314f57267f6f71855a766738837ca60234d6105317854abe61152cR766
tym `deccoria.pl##div[class^="dc-billboard advert-250-box"]`

**Comment by krystian3w** [comment]
Nie wiem czy sens jest robić sprawdzanie kolejności klas, nagle jutro rano zmienią klasy miejscami w CMS i filtr momentalnie padnie.

Niby ten wymaga by zmienili nazwy klas (coś jak facebook, z generowaniem literówek w angielskim):

`deccoria.pl##div[class*="dc-billboard][class*="advert-250-box"]`

`##div[class*="dc-billboard"][class*="advert-250"][class*="box advert-250_margin has-ad"]`

**Comment by felix-22** [comment]
Admin był, porobił inne reklamy (https://github.com/MajkiIT/polish-ads-filter/commit/291b770c68e7037d1d5808a883fad2f518b6ecae), a tu przegapił.

**Comment by felix-22** [comment]
Wydzieliłem do https://github.com/MajkiIT/polish-ads-filter/issues/20390 bo inaczej tego nie naprawi.

**Comment by krystian3w** [comment]
Wróciła pełno-ekranowa reklama by @blocker999: `https://www.interia.pl/wyloguj.html`

**Comment by blocker999** [comment]
![inter](https://user-images.githubusercontent.com/23176832/158162340-13fafe33-6975-4cb7-84a5-bb6cff5a25f9.png)

**Comment by krystian3w** [comment]
W sumie ciekawe czy stary CSS i skryptlet można tylko skorygować i by zaczął działać.

**Comment by AroKol78** [comment]
kwadraty z napisem reklama
- `https://smaker.pl/ksiazka-kucharska-makarony,16814.html`
`smaker.pl##.block--adv--padding, .advert--container`

- `https://deccoria.pl/artykuly/porady-domowe/ruszt-kuchenki-gazowej-jest-brudny-i-lepiacy-namocz-w-roztworze-wlasnej-roboty-brud-szybko-zniknie-25-12917`
`deccoria.pl##.is-config.advert-250-box.dc-billboard`

dziury w artykułach np. na `geekweek`
`interia.pl##.desktop.article-body__ad-gora-srodek`

**Comment by AroKol78** [comment]
na końcu artykułu dziura
`https://geekweek.interia.pl/historia/news-przelomowe-odkrycie-w-egipcie-odkopano-pierwsze-takie-grobow,nId,7258652`
`###feed_grupa.ad`

**Comment by AroKol78** [comment]
na głównej `geekweek` psuje `.mixerAdTopRight-wrapper` i `.has-mixerAdTopRight` mi te na niebieskim tle (jak zrzut ekranu będzie potrzebny to zapodam)

temp fix
`interia.pl#@#.adStandardTop, #feed_grupa.ad, #ad-feed_grupa, .article-body__ad-gora-srodek, .mixerAdTopRight-wrapper, .has-mixerAdTopRight`
`interia.pl##.adStandardTop, #feed_grupa.ad, #ad-feed_grupa, .article-body__ad-gora-srodek`


ps. "closed this as completed" ???

**Comment by garry-ut99** [comment]
Pobieżnie przeleciałem strony Interiii z tego co widzę to chyba tylko na `geekweek` przesunęło 2 kafelki, jeśli mógłbyś oblecieć strony Interii i potwierdzić czy tylko na `geekweek` psuje, czy gdzieś jeszcze indziej to byłoby dobrze, z tego co widzę to dałeś wykluczenie na wszystkie strony, tu masz wykluczenie na samo `geekweek` :
```
~geekweek.interia.pl,interia.pl##.adStandardTop, #feed_grupa.ad, #ad-feed_grupa, .article-body__ad-gora-srodek, .mixerAdTopRight-wrapper, .has-mixerAdTopRight
geekweek.interia.pl##.adStandardTop, #feed_grupa.ad, #ad-feed_grupa, .article-body__ad-gora-srodek
```

**Comment by AroKol78** [comment]
> mógłbyś oblecieć strony Interii i potwierdzić czy tylko na geekweek psuje

problem tylko na `geekweek`, na innych stronach wycina reklamy lub co najwyżej przesuwa kafle bez psucia czy ich usunięcia.

> Nie ja to zamykałem

wiem, to kierownik.

> drobne błędy czy poprawki, albo pojedyńcze kontenery to można i w zamkniętym zgłaszać

ok, jak coś to tu będę dodawał

**Comment by garry-ut99** [comment]
> problem tylko na `geekweek`

Ok.

>  lub co najwyżej przesuwa kafle bez psucia czy ich usunięcia.

No wiem, czyli jest ok, bo tak ma być, zamierzony efekt czyli kafle wracają do szeregu, po wycięciu zbędnego/przeszkadzającego pustego kontenera po reklamie, który narozrabiał i je wcześniej poprzesuwał zajmując niepotrzebnie miejsce.

> wiem, to kierownik.

Ok, dobrze wiedzieć, że wiesz, teraz i ja wiem, że wiesz, chociaż się domyślałem, ale pewności nie mogłem mieć, bo nie sprecyzowałeś, więc na wszelki wypadek tylko się odniosłem, żeby nie było na mnie w razie czego.

> ok, jak coś to tu będę dodawał, no chyba, że bot zrobi "locked"

Ok, bot zablokuje chyba dopiero po 60 dniach od ostatniego posta, więc w sumie jeśli przez tyle czasu nic nie będzie zgłaszane i nic się nie będzie działo, to wtedy i tak wątek nie będzie już aż tak potrzebny, ewentualnie raz na 2 miesiące możesz mu sztuczne oddychanie zrobić metodą usta-usta i jakiś pusty komentarz wkleić na podtrzymanie.

I na koniec - uzupełniłem poprzedni komentarz  https://github.com/MajkiIT/polish-ads-filter/issues/20301#issuecomment-1894524084 o dodatkowy filtr ("wytnie tylko w artykułach, omijając główną."), a poprawka zostanie dodana do listy pewnie za jakiś czas, na dniach.

**Comment by garry-ut99** [comment]
U nas już naprawione, ale żeby było śmieszniej, przed chwilą zauważyłem, że w `EasyList Polish` też popsute : 
- https://github.com/easylistpolish/easylistpolish/issues/3175

Dziwne jest to, że niby mają popsute od 2 lat, a do tej pory nikt nie zgłosił, 
podczas gdy u nas zostało zgłoszone po kilku/nastu dniach od wystąpienia błędu
