### ISSUE TITLE
uwatchfree.*

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#20308]
Strona znanej marki jest psuta przez:

https://github.com/MajkiIT/polish-ads-filter/blob/58a219f2ba64f85ee3030e40bd7457c0e66058f7/polish-adblock-filters/adblock.txt#L4835

Demo:

`https://www.uwatchfree.pl/2021/10/homegrown-the-counter-terror-dilemma-2016-full-movie/`

![obraz](https://user-images.githubusercontent.com/35370833/135771744-1fad7f47-f7da-4838-af79-a7e219740203.png)

pod uBO trzeba by dodać wykluczenie domen:

`@@||wss.analyticacdn.com^$websocket,domain=hydrax.xyz`

(nie chce działać `redirect` dla websocketów, trzeba by napisać skryptlet jak nie można dopuścić np. wyciek reklam/prywatności)

Możliwe, że wiele domen działa w iframe, więc samo `hydrax.xyz` może naprawić pewnie z 10% osadzonego video.

**Comment by hawkeye116477** [comment]
> Strona znanej marki

Jaka tam znana, ja jakoś nie kojarzę...

**Comment by krystian3w** [comment]
uAssets chętnie ten filtr nadpisze, wtedy możesz zacząć tworzyć własny fork listy/dodatku z opcją:

`||wss.analyticacdn.com^$all,important`
