### ISSUE TITLE
metropoliaztm.pl

### ISSUE THREAD

**Issue by ghost** [MajkiIT/polish-ads-filter#20313]
nie mozna zaakceptowac cookies https://rj.metropoliaztm.pl/news/i/2182/ i na innych komunikatach

**Comment by Lukjan38** [comment]
tak jest 
![kom](https://user-images.githubusercontent.com/17565773/136603724-6dafb540-9026-4c3f-88aa-e4539df22062.jpg)

**Comment by Lukjan38** [comment]
pomoze ktos?

**Comment by hawkeye116477** [comment]
Co nie @krystian3w?

**Comment by krystian3w** [comment]
Jak dla mnie to tam nie trzeba akceptować.
