### ISSUE TITLE
chatbro.com widget jest błędnie ukrywany na stronach. 

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#20312]
Więc winowajcami są :

1. Polskie Filtry Elementów irytujących (blokowanie chatbro.com js) - @MajkiIT  i cały team PL filtrów

2. Adguard Annoyances (chatbro.com js z atrybutem important) - @AdamWr i team Adguard

Czyli tak:

1. Z wyłączonymi winowajcami

![Screenshot_2021-10-07-22-29-45.png](https://user-images.githubusercontent.com/16944478/136458374-aec3d620-c0d1-4822-b83a-f1b771408de6.png)

![Screenshot_2021-10-07-22-29-52.png](https://user-images.githubusercontent.com/16944478/136458417-6ba3f22a-bbdd-4254-b180-9beeb43a9da1.png)

2. Z włączonymi winowajcami

![Screenshot_2021-10-07-22-31-56.png](https://user-images.githubusercontent.com/16944478/136458501-baf938f1-b074-4470-a4db-975e57f51a4c.png)

Na przykładzie : 
dozaanimata.ro 

Mogę prosić o usunięcie reguł dla widgetu domeny chatbro.com ? Bo jest błędnie oznaczony jako irytujący przez was. A jest tak na prawdę wygodny, że z głównej można sobie podejrzeć wiadomości i napisać od razu. 

Pozdrawiam

**Comment by hawkeye116477** [comment]
Jeżeli chodzi o EI, to każdy latający widżet jest ukrywany, masz tam nawet sekcję „Widżety kontaktowe”.

**Comment by seba2282** [comment]
Mogę dodać opcjonalnie i do mnie, ale widzę, że jakieś js blokują a nie cookies czy kto co tam. To napisałem + ag robi to z important.

**Comment by seba2282** [comment]
> Btw, _MajkiIT_ nie jest winowajcą, bo nie odpowiada za Polskie Filtry EI. Tak więc tak naprawdę to zgłoszenie powinno trafić na https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues, a nie tutaj :stuck_out_tongue: 


Jeżeli bym tutaj napisał, wtedy drugie w dziale Adguard. A było łatwiej nie powielać tematu i napisać w błędnym blokowaniu.

**Comment by krystian3w** [comment]
Niby MS najszybciej dodał ale nie śledzę czy chcą szybciej od Google je wygasić.

https://www.google.com/search?q=ublock+origin+chrome&tbm=nws&tbs=qdr:m

![obraz](https://user-images.githubusercontent.com/35370833/136609457-7d725cf5-e51d-4055-bb69-d4481ff2ead2.png) |
--- |
Harmonogram wygaszania obsługi Manifestu v2 w Chrome |

**Comment by seba2282** [comment]
To niedobrze. Padnie ublock origin. Albo gorhill coś wymyśli.

**Comment by krystian3w** [comment]
W sumie może wersja w nodejs pozwoli zrobić fork chrome na bazie Electron (albo NW.js znanego wcześniej jako node-webkit) jak to chciał JsPenguin2017.

**Comment by hawkeye116477** [comment]
Tyle, że Majkel nic nie blokuje, więc nie wiem po co go ciągle przywoływać.

**Comment by felix-22** [comment]
Google search https://www.google.pl/search?q=chatbro.com+site%3Apl nie ukrywa nazw za paywallem:
- znalazło 2, których nie znalazł publicwww:
 https://uwierzbogu.pl/
http://www.dphome.cba.pl/
- znalazło 2, które najprawdopodobniej to te same z publicwww:
https://jargus.pl/ (w publicwww jako  `j***.pl`)
https://podolsze.pl/ (w publicwww jako  `p***.pl`)
- znalazło 2, które nie mają tego czatu zablokowanego, bo mają inną nazwę skryptu albo w inny sposób jest osadzony na stronie:
https://new.forum.preppersi.pl/
http://zit.lomza.pl
- znalazło 3, które okazała się porno-badwarem:
`http://167.adwokat-mk.pl/391`
`http://swieta-rodzina.olecko.pl/058os/siren-head-minecraft-seed-e44c85`
`https://kopula.org.pl/pgxhtogrzm-10-23739-skandinavisk_porno_free_sex_cam_chat/`
i to jest kolejny przykład na to, o czym już pisałem:
https://github.com/uBlockOrigin/uAssets/commit/56da93d9c59b2f351f2fc40c3e3a1cd1e8f1e227#commitcomment-57082062
 https://github.com/uBlockOrigin/uAssets/commit/56da93d9c59b2f351f2fc40c3e3a1cd1e8f1e227#commitcomment-57163165, 
że te badware zainfekowało cały internet, na jaką frazę nie wyszukiwać, nawet nie związaną z porno, to co któryś wynik to ten porno-badware, ciekawe jest również to, że ten porno-badware podszywa się pod strony katolickie...

**Comment by krystian3w** [comment]
Screen dla @AdamWr / Adguard team:

![Screenshot_20211011-082910_Galaxy Store](https://user-images.githubusercontent.com/35370833/136743224-9edb059f-f07b-4b90-8dd2-6fde803b2ad3.jpg)

Niby 80% Polaków co używa Android, to niby na Samsungach.

**Comment by krystian3w** [comment]
Ja rozumiem że adguard team nic nie wie, że któraś tam wersja przeglądarki "Internet" dodała API "Webextension", które powinno być
 Lepsze od wtyczki z Google Play za darmo i dla fanatyków unikania lokalnego VPN/Proxy.

Jedynie lekka lipa jak na telefonie nie działa w miarę najnowszy sklep "Galaxy Store" (dawniej "Samsung apps) np. Xiaomi.

**Comment by felix-22** [comment]
[Seby zgłoszenie](https://github.com/MajkiIT/polish-ads-filter/issues/20312#issue-1020441399) zostało ogarnięte po 1 dniu, tymczasem [moje zgłoszenie](https://github.com/MajkiIT/polish-ads-filter/issues/20312#issuecomment-939243868) tu wisi 2 dni i dalej nieogarnięte: te 3 złośliwe strony dalej niezablokowane w KAD, czy nie blokujecie już takich stron w KAD i trzeba do [uAssets Badware Risks](https://github.com/uBlockOrigin/uAssets/issues/10075) to zgłaszać?

**Comment by felix-22** [comment]
Na każdej miałem przekierowania:
> - Pierwsze to zbiór losowych słów (nie mam przekierowań), nie widzę sensu blokować. Nie widzę sensownego kontrataku niż listem poleconym ...

- a ja mam, to że ty nie masz przekierowań, to nie znaczy, że inni nie mają 
- teraz nie masz, a za jakiś czas możesz mieć, też tak miałem nie raz
- i widzę sens blokować bo zanim wyląduję na planszy blokującej uBO, to przelatuję przez kilka syfiastych szpiegujących stron, które spisują wszystkie moje dane, wszystkie one powinny zostać zablokowane (`787787.com`, `telecomfm.co.uk`):


<details>
  <summary>screenshoot</summary>
  
![11](https://user-images.githubusercontent.com/75935068/136909787-72366d71-42af-4df3-94ff-0c8a663f68d3.png)
  
</details>

 `787787.com/mydomains.php` : `function LoadAd() { parent.location.href="http://telecomfm.co.uk/inc/go.php?sid=1&tds-key="+encodeURIComponent(keyword); } LoadAd(); `

> - Drugie to zainfekowany WordPress dziwnym katalogiem, raczej trzeba by cały blog zablokować i do parafii napisać by od-infekowali.

- miałem przekierowanie wcześniej

> - Trzecie blokuje regex od Yuki: 

- tu z kolei ja już nie mam przekierowań, a miałem wcześniej
- nie wykluczone, że za jakiś czas znowu będę miał

<hr>

Przekierowania raz są, a raz ich nie ma:
- mogą być losowe, oparte na nieznanych losowych warunkach (pochodzenie geograficzne, przeglądarka, system, referrer itp.)
- mogą być na jakiś czas (dopóki twój unikalny identyfikator oraz IP nie zostaną wykasowane z logów serwera)

**Comment by krystian3w** [comment]
W sumie nie można zamknąć, element dalej widoczny na:

```
https://new.forum.preppersi.pl/
http://zit.lomza.pl
```

**Comment by hawkeye116477** [comment]
W przypadku EI nie trzeba dodawać wyjątków. Można po prostu zmigrować na moduły.
