### ISSUE TITLE
smartage.pl

### ISSUE THREAD

**Issue by CHKDSK88** [MajkiIT/polish-ads-filter#20310]
Kolejny paywall. 

Przykład, gdzie występuje:
https://www.smartage.pl/londynski-brutalizm-balfron-tower-trellick-tower-glenkerry-house/

![obraz](https://user-images.githubusercontent.com/26788522/133060348-f98feaf1-a446-4728-891d-13fa6c14f7ab.png)

Pomogło dodanie domeny `smartage.pl` do reguły w poniższej linijce:

https://github.com/olegwukr/polish-privacy-filters/blob/3bcffe8a41f1eddf25f44867eaa461431c2d1c68/anti-adblock-suplement-adguard.txt#L61

**Comment by krystian3w** [comment]
Dodane w: https://github.com/olegwukr/polish-privacy-filters/commit/83b4f977b34cece7d7f9e7bf37c77f31086c28ca

**Comment by krystian3w** [comment]
Przyszłoby się wyrównać stan pliku uBo suplement z AdGuard suplement.

najprościej by było wrzucić kompatybilne w jeden plik a ten pod AdGuard używać do dezaktywowania wadliwie działających skruptletów.

**Comment by krystian3w** [comment]
@olegwukr
