### ISSUE TITLE
kursjs.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#20340]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [X] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://kursjs.pl/kurs/ajax/async-await.php
```

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Waterfox Classic 2021.10

### Bloker (Blocker)

uBlock Origin 1.37.2

### Używane listy filtrów (Used filter lists)

Domyślne + KAD

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

`To nie jest cały kod - dowiedz się czemu` (podpowiedź jest w linku, czyli wykrywają adblockera)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by AroKol78** [comment]
problemem jest `-prebid.$script`

mi pomaga `@@||kursjs.pl/js/ads-prebid.js$script,first-party`

(opcja z `||...,redirect=noopjs` nie działa)

**Comment by krystian3w** [comment]
Czyli plik jest spersonalizowany, może AdamWr wymyślił skryptlet by pominąć ładowanie śmiecia.
