### ISSUE TITLE
loomi.tv

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#20342]
https://loomi.tv/pl/movie/the-thirteenth-floor

![obraz](https://user-images.githubusercontent.com/35370833/137643415-29b45fa7-9af6-4fac-bf31-d9ebc951d1d4.png)

niestety teraz trwają testy, więc pewnie Oleg naprawi za 3 miesiące jak będzie w pełni darmowa rejestracja.

**Comment by krystian3w** [comment]
Na moim PC wystarcza:

```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=loomi.tv
```

@seba2282 / @admawr / @F4z masz lepszy pomysł?

**Comment by seba2282** [comment]
Jeżeli więcej domen to potrzebuje, ja wtedy bym nie robił dla jednej domeny. Widziałem parę stron i pamiętam też rozmawialiśmy o podobnej regule @krystian3w

**Comment by krystian3w** [comment]
Nazwa kiepska, jak chcesz sobie dodać ukrywanie logowania Googlem/twarzo-książką.

https://www.google.com/search?q=der+die+das

**Comment by seba2282** [comment]
>  \"lub zaloguj się za pomocą\

Jest tylko ten napis. Nic więcej. Wy to nazywacie span (?).

**Comment by krystian3w** [comment]
Ja nie jestem webmasterem Opery "proszę pana". Webmaster sobie tak nazwał.

---

@Olegwukr pod uBo i AG działa tam przekierowanie na `noopjs`.
