### ISSUE TITLE
workstations.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20362]
( na dole )

**Comment by hawkeye116477** [comment]
Kto robił tą stronę, połowa po angielsku, połowa po polsku...

**Comment by krystian3w** [comment]
Pewnie drop ship z Chin.

**Comment by hawkeye116477** [comment]
Niby firma się nazywa IT BUSINESS GROUP, w Google 23 opinii sprzed paru lat. Wujek wskazuje, że mają też stronę `armafpolska.pl`, która w tej chwili nie działa
