### ISSUE TITLE
Problem z listami na Mikrotik

### ISSUE THREAD

**Issue by sharkov69** [MajkiIT/polish-ads-filter#20377]
W listach IP są zdublowane wpisy przez co Mikrotik przerywa import.
Czy możesz poprawić skrypt generujący listy na usuwanie zdublowanych wpisów lub dodać w każdej linii:
:do { add list=addressListMalware address="x.x.x.x" comment="addMalwareIPs CertyficateIT_Malware" } on-error={}
zamiast:
add list=addressListMalware address="x.x.x.x" comment="addMalwareIPs CertyficateIT_Malware"

**Comment by MajkiIT** [comment]
Poprawię to. Dzięki

**Comment by xxcriticxx** [comment]
bad bot :(

@MajkiIT poprawiles liste?

**Comment by sharkov69** [comment]
Dasz radę to zmienić?

**Comment by MajkiIT** [comment]
nie powinno już być błędów, poprawiłem duplikaty. Nadal to występuje ?

**Comment by sharkov69** [comment]
Dzisiejszy plik, 3 duplikaty, na linii 4184 skrypt się wysypuje  w MT: 
![obraz](https://user-images.githubusercontent.com/47471161/149725274-59303de9-9cda-4277-a5af-1deb0f6afefc.png)

**Comment by MajkiIT** [comment]
Zerknij proszę teraz

**Comment by krystian3w** [comment]
Bad bot

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/20854

**Comment by krystian3w** [comment]
#20376
