### ISSUE TITLE
przyslijprzepis.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20394]
https://www.przyslijprzepis.pl/przepis/czarny-miod-miod-z-czarnuszka-5

" Chcesz zobaczyć więcej? Wyłącz adblocka. "

**Comment by AroKol78** [comment]
u mnie gitara
jakie listy (może jakaś nadmiarowa lista coś blokuje)
https://github.com/MajkiIT/polish-ads-filter/issues/20302
