### ISSUE TITLE
interia.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#20390]
Puste kontenery po reklamach, wydzielam bo admin nie widzi / nie interesuje się: 
- https://github.com/MajkiIT/polish-ads-filter/issues/20301#issuecomment-943536289
- https://github.com/MajkiIT/polish-ads-filter/issues/20301#issuecomment-956323186

### a) https://teksciory.interia.pl/wykonawcy-litera-m,6.html
![1](https://user-images.githubusercontent.com/75935068/140606785-184da869-2430-4ba3-98ce-e946539ed15e.png)

### b) https://teksciory.interia.pl/monami-monika-miller-egoistka-feat-guova-tekst-piosenki,t,690309.html
![2](https://user-images.githubusercontent.com/75935068/140606789-b3e53534-7d0c-4dd3-abdb-b844b8886168.png)

**Comment by MajkiIT** [comment]
Dzięki
