### ISSUE TITLE
tatromaniak.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#20391]
za dużo zdjęć zostało ukrytych (patrz https://github.com/uBlockOrigin/uAssets/issues/10417)

`https://tatromaniak.pl/aktualnosci/kurtka-kurtce-nierowna-jak-wybrac-przeciwdeszczowa-kurtke-ktora-sprawdzi-sie-w-gorach/`

Błędnie działający filtr to:

```
~lowcygier.pl,pl##a[href*="://converti.se/click/"]
```

Zalecane wykluczenie domeny a jak znajdziemy z 3 nowe domeny to przepisanie na filtry tylko dla uBO i AdGuard:

`pl##+js(ra, href, a[href*="://converti.se/click/"], asap stay)`

**Comment by MajkiIT** [comment]
Dzięki
