### ISSUE TITLE
gniewkowo.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2040]
ad block 

Zauważyliśmy, że korzystasz z wtyczki AdBlock. Wyłącz ją, aby móc w pełni korzystać z portalu albo wyklucz domenę gniewkowo.eu

**Comment by MajkiIT** [comment]
`gniewkowo.eu##.a-d-v-i`
`gniewkowo.eu##.header-adblock`

**Comment by F4z** [comment]
Jeśli chodzi o adblocka, to można jeszcze w ten sposób:
`@@||gniewkowo.eu/pl/js/show_ads.js$script`

**Comment by MajkiIT** [comment]
@F4z dzięki
