### ISSUE TITLE
trustedshops.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20403]
( na dole )

![tr](https://user-images.githubusercontent.com/23176832/143444171-13929d26-6975-4007-825c-18500454cd9a.png)

**Comment by krystian3w** [comment]
Dziwny układ strony lub hawkeye za dużo wyciął...

**Comment by krystian3w** [comment]
Nie zostanie naprawione bez URL z taką stopką.
