### ISSUE TITLE
tibia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2045]
ad block czy static img ???

`PAMIĘTAJ! Źródłem utrzymania forum są reklamy. Dziękujemy za uszanowanie ich obecności. `

![capture](https://cloud.githubusercontent.com/assets/15007183/22183888/3e60a5e8-e096-11e6-9e9c-f8a5c9976f6d.PNG)

**Comment by MajkiIT** [comment]
static
