### ISSUE TITLE
i.ibb.co

### ISSUE THREAD

**Issue by roquez** [MajkiIT/polish-ads-filter#20515]
**i.ibb.co** to domena popularnego hostingu obrazków serwisu **imgbb.com**. Błędny filtr `||i.ibb.co^` całkowicie blokuje wyświetlanie przesłanych obrazów.

Przykładowy link: https://ibb.co/TwQRKvn

#### Tak powinno wyglądać:
![aa1](https://user-images.githubusercontent.com/21342425/145145816-0921bc97-f587-4581-8ff0-63f8bb819044.PNG)

#### A jest tak:
![aa2](https://user-images.githubusercontent.com/21342425/145145828-bd125342-2a5c-4f59-b10b-3c2d3cd1ad64.png)

**Comment by felix-22** [comment]
Ciekawostka: po włączeniu AdGuard Base błędu nie ma, bo już naprawili - dodali `||i.ibb.co^$badfilter`

**Comment by hawkeye116477** [comment]
> AdGuard pewnie uznał, że MajkiIT nie naprawi lub za 2 miesiące.

I słusznie uznali, to bardzo możliwe, że sporo czasu upłynie aż będzie następna aktualizacji. Wystarczy spojrzeć jak to ostatnio wyglądało :smile:.

**Comment by krystian3w** [comment]
W sumie w tym gąszczu blockera pewnie tylko majkel 5/10 kojarzy jaki zakres stron hostuje reklamę w tak niebezpieczny sposób (hostingi grafik czasem mają zapis o usunięciu jak przeciąża im serwer).
