### ISSUE TITLE
jira service desk

### ISSUE THREAD

**Issue by szczot3k** [MajkiIT/polish-ads-filter#20517]
### Link bezpośredni 
n/d: brak możliwości podania linku bezpośredniego do firmowej jiry

### Co trzeba zrobić, aby pojawił się błąd?
1. Wejść do zarządzania komponentami (plugins/servlet/project-config/(PROJECT-KEY)/administer-components)
2, Próbować edytować komponent, aby wybrać leada

### Moja konfiguracja 

**Przeglądarka internetowa:** Firefox 95.0

**Rozszerzenia i skrypty:** uBlock Origin

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):** div z nazwą `component-lead-container` łapie się pod filtr `pl##[id*="ad-container"]:not(#documents-upload-container):not(#editor-preload-container)`

**Comment by krystian3w** [comment]
czyli trzeba dodać `:not(#component-lead-container)` lub ocenić moc filtru (np. kasacja z racji zniknięcia tych reklam).

**Comment by MajkiIT** [comment]
@krystian3w dzięki
