### ISSUE TITLE
certyficate.it

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#20525]
Zdaje się, że formularz anonimowych zgłoszeń padł: https://www.certyficate.it/zglos-reklame/

można ze 30 minut czekać i ciągle kręci się strzałka 🔁.

Możliwe, że trzeba zresetować wtyczkę do formularzy, usługę mail na serwerze czy uprawnienia bota.

**Comment by AroKol78** [comment]
przepraszam, że podpiąłem się pod temat
ale nurtują mnie dwa wpisy na liście POL-0 dotyczące `certyficate.it`- czy są niezbędne?
`@@||google-analytics.com^$domain=certyficate.it`
`@@||googletagmanager.com/gtag/$script,domain=certyficate.it`

**Comment by krystian3w** [comment]
Pewnie do śledzenia konwersji kliknięć na blogu jaką zablokuje zneutralizowane źródło.

**Comment by hawkeye116477** [comment]
A to cwany dyrek, innym blokuje, a sobie odblokowuje :rofl:

**Comment by MajkiIT** [comment]
@hawkeye116477 ale na moich filtrach nie ma blokowania GA :P A dodanie tego wynikało z pewnego incydentu. Co do formularza to chwilowo celowe.

**Comment by hawkeye116477** [comment]
Ah, rozumiem, w końcu najlepsze kasztany są na placu Pigalle :smile_cat: .

**Comment by MajkiIT** [comment]
@hawkeye116477 chcesz na ten temat pogadać to możemy się zgadać poza tym czatem :P

**Comment by krystian3w** [comment]
L
