### ISSUE TITLE
bezprawnik.pl

### ISSUE THREAD

**Issue by LeonSolmyr** [MajkiIT/polish-ads-filter#20545]
https://bezprawnik.pl/ poprzez AdGuard na Androidzie nie wczytuje zawartości strony poza nagłówkiem i stopką.

**Comment by felix-22** [comment]
- potwierdzam błąd, występuje również na komputerach PC
- zła etykieta - powinno być `błąd`
- przyczyna błędu, a dokładniej klasa `.wall-bg-banner` wycina większość strony (środek) zostawiając tylko nagłówek i stopkę:
https://github.com/MajkiIT/polish-ads-filter/blob/27bae34d6a4cf52ae3adb58f72703e5b59d52829/polish-adblock-filters/adblock.txt#L469
- rozwiązanie: zastąpienie `.wall-bg-banner` klasą `.special-ad-top`, czyli poprawiony filtr ma wyglądać tak:
`bezprawnik.pl##.visual-wide, .special-ad-top, .col-xs-12.hidden-xs, .margin-bottom40.headline, .margin-bottom40.sidebar, .play_iframe, .wall-bg-link`
- naprawa tymczasowa dla użytkowników (wkleić do Moje Filtry) zanim łatka zostanie dodana do listy:
```
bezprawnik.pl#@#.visual-wide, .wall-bg-banner, .col-xs-12.hidden-xs, .margin-bottom40.headline, .margin-bottom40.sidebar, .play_iframe, .wall-bg-link
bezprawnik.pl##.visual-wide, .special-ad-top, .col-xs-12.hidden-xs, .margin-bottom40.headline, .margin-bottom40.sidebar, .play_iframe, .wall-bg-link
```
