### ISSUE TITLE
forsal.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#2058]
pojawia sie komunikat(za kilka sekund) o adblocku/ublocku na stronie forsal.pl

![capture](https://cloud.githubusercontent.com/assets/15007183/22203264/3c3798f4-e13a-11e6-9a22-3d37050027a8.PNG)

**Comment by F4z** [comment]
Powinno wystarczyć:
`@@||static.gazetaprawna.pl/js/ads.js$script`

**Comment by xxcriticxx** [comment]
a ja nic niemam /:

**Comment by xxcriticxx** [comment]
sub `http://forsal.pl/`

```
http://www.dziennik.pl/
http://www.gazetaprawna.pl/
http://www.prawnik.pl/
http://di.com.pl/
http://www.infor.pl/
```

**Comment by F4z** [comment]
@xxcriticxx jak wyłączysz skrypt AAK, to powinno się pokazać jak zaczniesz przewijać stronę (przynajmniej na forsal.pl).

**Comment by xxcriticxx** [comment]
mam zrobilem wam obrazek :)

**Comment by lukjan32** [comment]
czy bedzie w pliku?

**Comment by F4z** [comment]
Będzie.

**Comment by lukjan32** [comment]
ok, czekam.

**Comment by lukjan32** [comment]
dzieki, dziala

**Comment by MajkiIT** [comment]
@F4z dzięki

**Comment by lukjan32** [comment]
pojawil sie komunikat

**Comment by F4z** [comment]
Powinno wystarczyć:
`@@||static.forsal.pl/js/ads.js$script`
a gdyby znowu zmienili, to można też po prostu ukryć ten komunikat (chociaż i to też zawsze mogą zmienić):
`forsal.pl##.scrolled.infoBlock`

**Comment by lukjan32** [comment]
dziala, prosze zmienic w pliku i dodac.

**Comment by lukjan32** [comment]
dalej jest komunikat :(

**Comment by F4z** [comment]
Zaktualizowałem, powinno być ok.

**Comment by lukjan32** [comment]
dzieki, dziala
