### ISSUE TITLE
miniminiplus.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2059]
Nie da się oglądać wideo, bo strona wykrywa adblocka - `http://www.miniminiplus.pl/postac/teczowa-rubinka/45933`

![image](https://cloud.githubusercontent.com/assets/11742596/22212012/60359aee-e18f-11e6-8b10-23a9f9f00f94.png)

U mnie to pomogło:
`@@||miniminiplus.pl^$generichide`
`@@||tvn.adocean.pl/ad.xml$xmlhttprequest,domain=miniminiplus.pl`
`@@||tvn.adocean.pl/__/ad.xml$xmlhttprequest,domain=miniminiplus.pl`

**Comment by xxcriticxx** [comment]
a to z skad? fb?

**Comment by F4z** [comment]
Po prostu chciałem sobie obejrzeć bajki i tak się trafiło.

A tak poważnie, to zgłoszenie stąd - https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by xxcriticxx** [comment]
@F4z caly czas mnie zadziwiasz

paging @seba2282 zapraszamy!

**Comment by seba2282** [comment]
Nie wiem @F4z , jak to zrobiłeś, ale @@||miniminiplus.pl^$generichide
@@||tvn.adocean.pl/ad.xml$xmlhttprequest,domain=miniminiplus.pl
@@||tvn.adocean.pl/__/ad.xml$xmlhttprequest,domain=miniminiplus.pl  u mnie nie działa.

**Comment by F4z** [comment]
Na iOS?

**Comment by F4z** [comment]
@seba2282 podaj proszę z jakiego rozszerzenia/programu do blokowania reklam korzystasz oraz z jakiego systemu i przeglądarki, będzie łatwiej.

**Comment by seba2282** [comment]
Android i mam Adquard oraz www.miniminiplus.pl na białej liście w głównych opcjach i tylko włączone filtrowanie dns dodatkowo. Jak wyłączę wspomnianą opcję, to mnie atakują usuń wirusa, potrzebna aktualizacja, etc... ale wtedy działa miniminiplus.pl . A linki dodane do whitelist domain https są ignorowane przy filtrowaniu dns.

**Comment by seba2282** [comment]
I przeglądarka chrome mobile

**Comment by xxcriticxx** [comment]
Na mobile bendzie problem

**Comment by F4z** [comment]
Też korzystam z Adguarda na Androida, tyle że beż włączonej opcji "Filtruj zapytania DNS" .
Szukam jakiś informacji jak konkretnie ta opcja działa.

Swoją drogą, gdzie "atakują" Cię te reklamy typu "usuń wirusa", to moim zdaniem powinno być blokowane i bez tej opcji.

**Comment by xxcriticxx** [comment]
Ten dns to jest host file

**Comment by seba2282** [comment]
@F4z cdax.tv włącz jakiś film i tradycja w chrome twój telefon jest zainfekowany, bla bla bla...

**Comment by xxcriticxx** [comment]
na mobile z aguardem jest problem nie wszystko lapie

**Comment by F4z** [comment]
@seba2282 ok, też to mam, te reklamy są między innymi z odtwarzacza `raptu.com` i z tego co widzę, to wyskakują też w przypadku uBlocka i Adguarda na Windowsie.
Swoją drogą, ja nawet z włączoną opcją "Filtruj zapytania DNS" mam wyskakujące okienka na tej stronie na Androidzie.

A odnośnie niedziałającego filmu, to możesz jeszcze sprawdzić tę regułę:
`@@||adocean.pl`
Dodaj ją do filtrów użytkownika, a potem wyłącz i włącz ochronę Adguarda.
Nie jest to najlepsze rozwiązanie, bo na innych stronach przez mogą się pojawić reklamy, ale lepszego pomysłu nie mam.
Może warto też zgłosić to tutaj - https://github.com/AdguardTeam/AdguardDNS/issues?page=1&q=is%3Aissue+is%3Aopen

**Comment by seba2282** [comment]
Mam chrome na windows + ublock origin i na full opcje z uwzględnianiem filtrów kosmetycznych + wyjątki miniminiplus.pl , instagram.com i zero reklam. :)

**Comment by seba2282** [comment]
@@||adocean.pl O kurde działa. xD

**Comment by seba2282** [comment]
I to z dns

**Comment by F4z** [comment]
Tutaj jak włączysz film albo zatrzymasz to Ci nic nie wyskakuje? - `https://www.raptu.com/embed/2pWcyBvj`
Czasami wyskakujące okienko jest blokowane, ale nie wszystkie, zależy gdzie tam przekieruje chyba.
Najlepiej sprawdzić w trybie prywatnym i odświeżyć stronę jeśli popup został zablokowany...

**Comment by seba2282** [comment]
Na PC zero problemów z ublock origin. Natomiast tutaj wyskoczyło mi te gówno na raptu. Aktualizacja ...

**Comment by F4z** [comment]
Przed chwilą jak sprawdzałem kilka razy to coś tam się pootwierało.
![image](https://cloud.githubusercontent.com/assets/11742596/22227568/4330024e-e1cc-11e6-9060-7f2b06fdc8f8.png)

**Comment by seba2282** [comment]
Wywaliłem też z białej listy www.miniminiplus.pl i działa. Ale... została odblokowana cała domena tego gówna tych aktualizacja i usuń wirusy i mi tego nie blokuje teraz...

**Comment by F4z** [comment]
Mi tego nie blokowało w ogóle, cały czas miałem z tym problem, nawet bez dodawania tego wyjątku.
Domyślam się, że piszesz teraz o Adguardzie dla Androida, tam możesz sprawdzić tę regułę:
`raptu.com#%#Object.defineProperties(window, { "_impspcabe_alpha": { value: false, writable: false }, "_impspcabe_beta": { value: false, writable: false }, "_impspcabe_path": { value: 'about:blank', writable: false }, "_impspcabe": { value: false, writable: false } });`

**Comment by seba2282** [comment]
@F4z ustaw wszystkie filtry włącz, odznaczone ignoruj kosmetyczne. ustawienia te trzy ostatnie odznaczone. dalej usuń ten wyjątek adocean.pl oraz do ogólnych wyjątków dodaj miniminiplus.pl. no i update filtrów i zero śmieci na pc

**Comment by F4z** [comment]
Na pc korzystam z Adguarda i uBlocka Origin, dodałem tę regułę co przed chwilą podałem do Adguarda i nic mi nie wyskakuje.
U siebie nie dodawałem adocean.pl do wyjątków na komputerze, tylko sprawdzałem to na telefonie.
"Wszystkie filtry włącz", co masz na myśli, zupełnie wszystkie?

**Comment by seba2282** [comment]
Tak. Na PC w ublock origin. Jak będę na PC, to napiszę jak i to działa, choć miniminiplus.pl wtedy musi być w wyjątkach. Apropo, jak dodałem ten cały adocean, to reklamy na cdax.tv tradycyjnie zaczęły atakować. Jak nie było tej reguły, to nie atakowały...

**Comment by seba2282** [comment]
A teraz po wywaleniu reguł non stop wyskakuje, wygrałeś. Ten adocean trzeba dać na blacklist

**Comment by F4z** [comment]
Na PC jeśli korzystasz tylko z uBlocka Origin to miniminiplus działa po dodaniu tych reguł (nawet przy włączonych wszystkich listach):
`@@||miniminiplus.pl^$generichide`
`@@||tvn.adocean.pl/ad.xml$xmlhttprequest,domain=miniminiplus.pl`
`@@||tvn.adocean.pl/__/ad.xml$xmlhttprequest,domain=miniminiplus.pl`

Tak jak pisałem, ta reguła z adocean nie jest najlepsza, bo na innych stronach mogą być przez nią reklamy, ale nie powinno mieć to związku z reklamami na cdax.tv.

Odnośnie cdax.tv, to u mnie na Androidzie z Adguardem i włączoną opcją "Filtruj zapytania DNS" (bez dodawania reguły z adocean) wyskakiwały różne reklamy.
Po dodaniu tej reguły przestały:
`raptu.com#%#Object.defineProperties(window, { "_impspcabe_alpha": { value: false, writable: false }, "_impspcabe_beta": { value: false, writable: false }, "_impspcabe_path": { value: 'about:blank', writable: false }, "_impspcabe": { value: false, writable: false } });`

W przypadku komputera i tylko uBlocka Origin te dwie reguły powinny wystarczyć do zablokowania tych wyskakujących okienek:
`/^(http|https):\/\/[a-z0-9]{3,11}\.(party|website|science|webcam|bid)\/[0-9]{3,10}\//$xmlhttprequest,domain=streamin.to|raptu.com`
`||namesakeoscilloscopemarquis.com^$third-party,popup`
Ogólnie włączanie wszystkich filtrów w uBlocku nie jest najlepszym pomysłem, bo może wpływać negatywnie na wydajność oraz powodować problemy na niektórych stronach.

**Comment by F4z** [comment]
Jeszcze w przypadku odtwarzacza z `raptu.com` można do uBlocka Origin dodać tę regułę, zamiast tych dwóch ostatnich co podałem:
`raptu.com##script:inject(noeval.js)`

**Comment by seba2282** [comment]
Tylko po co na PC dodawać reguły ? Wywal Adquard z przeglądarki. Włącz w ublock origin w zakładce ustawienia wszystko oprócz trzech ostatnich. Następnie filtry wszystkie oprócz funkcji związanej z ignorowaniem kosmetycznych. No i wyjątki (biała lista) dodaj tylko miniminiplus.pl ten raptu (jeżeli chcesz) i instagram.com (jeżeli korzystasz). I to wszystko. Zero śmieci, nawet na MS Edge z ublock origin tak mam, choć opcje typu webrc i niektóre filytry nie są wspierane. I to tyle :)

**Comment by seba2282** [comment]
Wywaliłem tą regułę z adocean i po restarcie telefonu, w końcu Adquard z DNS blokuje na twoim linku z raptu domenę z reklamą. Coś takiego, że domena nie odpowiada :)

**Comment by seba2282** [comment]
Nie mam już pomysłów, a to wszystko przez ten player tvp / tvn sa - główna strona player.pl i taki Adquard się sypie po prostu...
