### ISSUE TITLE
glamour.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2060]
`http://www.glamour.pl/artykuly/jest-juz-zwiastun-kinowej-wersji-power-rangers-premiera-w-2017-roku`

![capture](https://cloud.githubusercontent.com/assets/15007183/22257123/14fe34f4-e22b-11e6-96b6-a558e33ed129.PNG)

**Comment by MajkiIT** [comment]
`www.glamour.pl##.products-set-items`
