### ISSUE TITLE
stoklasa.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20618]
pinterest ( na dole )

**Comment by seba2282** [comment]
`www.stoklasa.pl##[href="https://www.pinterest.com/stoklasacz/"]`

**Comment by krystian3w** [comment]
Odpada, będą potem, skargi, że blocker widzi urwane zdania gdzie wycięło słowa "na naszym facebooku" *pisaliśmy o tej tragedii*.

**Comment by krystian3w** [comment]
Lepsze będzie:

`||stoklasa.pl/img/pinterest-logo.jpg` zniknie po odświeżeniu strony jak się komuś załadował w przeszłości (cache przeglądarki).
