### ISSUE TITLE
harposoftware.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#20612]
test link:
https://harposoftware.com/pl/polski/234-Krzysztof-glos-Nuance.html

**Comment by krystian3w** [comment]
Kiboke dodał dwa generyki:

`###cookieNotice`
`###cookieNoticeContent`

lub masz bardzo niestandardową listę, co uruchomiła tam generchide.

**Comment by xxcriticxx** [comment]
@krystian3w update listy zrobilem i dziala thanks
