### ISSUE TITLE
ewybory.eu

### ISSUE THREAD

**Issue by OrginalS** [MajkiIT/polish-ads-filter#20627]
### Link bezpośredni 
https://ewybory.eu/

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. wejść na stronę

### Moja konfiguracja 
**Przeglądarka internetowa:** 
brave

**Rozszerzenia i skrypty:** 
ublockorigin

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Oficjalne polskie filtry przeciwko alertom o Adblocku 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
fix poniżej
ewybory.eu###ybfoexqv-blanket
ewybory.eu###ybfoexqv-blanket button
ewybory.eu###ybfoexqv-blanket>div
ewybory.eu###ybfoexqv-blanket>div>div
ewybory.eu##body:style(overflow: auto !important;)

**Comment by krystian3w** [comment]
Fixy mogą paść jak `ybfoexqv` jest słabo stabilne (np. maksymalnie tydzień - co daje do 52 aktualizacji w roku).

Jak są uparci jak WP, to komunikat może wymagać naprawy co 48 godzin.

**Comment by bogachenko** [comment]
@krystian3w hi. Here, the rule from Easylist interferes with the display of the page.

`##.advertisment`

**Comment by krystian3w** [comment]
That is not my filter/rule.

I can not edit @olegwukr repository also Eeyo protect repository of MajkiIT from law side - pr with exception in MajkiIT files is not welcome.

**Comment by OrginalS** [comment]
@bogachenko 

I have been using this rules for about a year. Some of them are probably redundant but I just add rules till there are no more adds and remove them only if something breaks. 

`ewybory.eu###ybfoexqv-blanket
ewybory.eu###ybfoexqv-blanket button
ewybory.eu###ybfoexqv-blanket>div
ewybory.eu###ybfoexqv-blanket>div>div
#ewybory.eu##mys-wrapper
#ewybory.eu##mys-overlay
#ewybory.eu##mys-content
#ewybory.eu##mys-meta
#ewybory.eu##ns-186hp-l-banner ns-186hp-v-0
#ewybory.eu##ns-186hp-l-banner
#ewybory.eu##ns-186hp-v-0
#ewybory.eu##ns-186hp-e-0
#ewybory.eu##ns-186hp-e-1
#ewybory.eu##ns-186hp-e-2
#ewybory.eu##ns-186hp-e-3
#ewybory.eu##ns-186hp-e-4
#ewybory.eu##ns-186hp-e-28
#ewybory.eu##ns-186hp-e-29
#ewybory.eu##ns-186hp-e-30
ewybory.eu##.ybfoexqv-disable-scroll
ewybory.eu##.ybfoexqv-disable-scroll #ybfoexqv-blanket
#ewybory.eu##.ybfoexqv-disable-scroll #ybfoexqv-blanket>div
ewybory.eu##body:style(overflow: auto !important;)`

**Comment by OrginalS** [comment]
@bogachenko 

I have been using this rules for about a year. Some of them are probably redundant but I just add rules till there are no more adds and remove them only if something breaks. 


ewybory.eu###ybfoexqv-blanket
ewybory.eu###ybfoexqv-blanket button
ewybory.eu###ybfoexqv-blanket>div
ewybory.eu###ybfoexqv-blanket>div>div
#ewybory.eu##mys-wrapper
#ewybory.eu##mys-overlay
#ewybory.eu##mys-content
#ewybory.eu##mys-meta
#ewybory.eu##ns-186hp-l-banner ns-186hp-v-0
#ewybory.eu##ns-186hp-l-banner
#ewybory.eu##ns-186hp-v-0
#ewybory.eu##ns-186hp-e-0
#ewybory.eu##ns-186hp-e-1
#ewybory.eu##ns-186hp-e-2
#ewybory.eu##ns-186hp-e-3
#ewybory.eu##ns-186hp-e-4
#ewybory.eu##ns-186hp-e-28
#ewybory.eu##ns-186hp-e-29
#ewybory.eu##ns-186hp-e-30
ewybory.eu##.ybfoexqv-disable-scroll
ewybory.eu##.ybfoexqv-disable-scroll #ybfoexqv-blanket
#ewybory.eu##.ybfoexqv-disable-scroll #ybfoexqv-blanket>div
ewybory.eu##body:style(overflow: auto !important;)

**Comment by bogachenko** [comment]
> @bogachenko
> 
> I have been using this rules for about a year. Some of them are probably redundant but I just add rules till there are no more adds and remove them only if something breaks.
> 
> ewybory.eu###ybfoexqv-blanket ewybory.eu###ybfoexqv-blanket button ewybory.eu###ybfoexqv-blanket>div ewybory.eu###ybfoexqv-blanket>div>div #ewybory.eu##mys-wrapper #ewybory.eu##mys-overlay #ewybory.eu##mys-content #ewybory.eu##mys-meta #ewybory.eu##ns-186hp-l-banner ns-186hp-v-0 #ewybory.eu##ns-186hp-l-banner #ewybory.eu##ns-186hp-v-0 #ewybory.eu##ns-186hp-e-0 #ewybory.eu##ns-186hp-e-1 #ewybory.eu##ns-186hp-e-2 #ewybory.eu##ns-186hp-e-3 #ewybory.eu##ns-186hp-e-4 #ewybory.eu##ns-186hp-e-28 #ewybory.eu##ns-186hp-e-29 #ewybory.eu##ns-186hp-e-30 ewybory.eu##.ybfoexqv-disable-scroll ewybory.eu##.ybfoexqv-disable-scroll #ybfoexqv-blanket #ewybory.eu##.ybfoexqv-disable-scroll #ybfoexqv-blanket>div ewybory.eu##body:style(overflow: auto !important;)

I didn't quite understand what you were talking about, because I said that the rule that is on the Easylist list breaks the Polish site, but thank you for speaking out
