### ISSUE TITLE
kurnik.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#2064]
Adblock po wybraniu gry.
Utworzyłem konto:
`Login: adblockpl`
`Hasło: adblock_pl123`

![image](https://cloud.githubusercontent.com/assets/11385099/22309982/deadca8a-e34d-11e6-87d1-a76558060c68.png)

Dodatkowo temat na easylist:
`https://forums.lanik.us/viewtopic.php?f=62&t=24196`

**Comment by F4z** [comment]
To raczej powinno wystarczyć żeby nie wykrywało adblocka:
`kurnik.pl#@#.adsbygoogle`

To można dodać żeby zablokować pozostałość po reklamie:
`kurnik.pl###pread`
![kurnik](https://cloud.githubusercontent.com/assets/11742596/22311384/8cd1c47c-e353-11e6-9e4c-1d04c1a11865.JPG)

A to dodatkowo do uBlocka żeby zmniejszyć puste miejsce po reklamie:
`kurnik.pl##.adsbygoogle:style(height: 1px !important; width: 1px !important;)`
![image](https://cloud.githubusercontent.com/assets/11742596/22311463/d4f9d974-e353-11e6-8022-270b0ba11c1b.png)

Reguły:
`kurnik.pl#@#.adsbygoogle`
`kurnik.pl###pread`
Dla uBlocka:
`kurnik.pl##.adsbygoogle:style(height: 1px !important; width: 1px !important;)`

**Comment by xxcriticxx** [comment]
gdzie jest kogut jak go potrzebujesz

**Comment by gomoku** [comment]
Siema polskie ludki, możecie zajrzeć również tutaj, tu również są filtry do Kurnika:
https://github.com/reek/anti-adblock-killer/issues/2752

ja jestem autorem powyższego wątku oraz także tego wątku:
https://forums.lanik.us/viewtopic.php?f=62&t=24196  oraz jego kontynuacji tutaj:
https://forums.lanik.us/viewtopic.php?f=23&t=23870

i jako pierwsza osoba na świecie zacząłem walczyć z tym anty-adblockiem z Kurnika gdy tylko się pojawił czyli ponad półtora roku temu, pierwsze co zrobiłem to półtora roku temu zgłosiłem na EasyList, dzień później ludki z forum podali działające filtry, z których oczywiście zacząłem korzystać i pewnie ileś innych osób też, ale to tylko połowa sukcesu, bo przecież nie o to chodzi, żeby każdy ręcznie dodawał filtry, bo druga połowa sukcesu to ważne jest też przecież aby filtr został dodany na jakąś główną listę, a dokładniej na Adblock Warning Removal List (https://easylist.to/pages/other-supplementary-filter-lists-and-easylist-variants.html) a dokładniej to taki suplement do EasyList przeznaczony właśnie do zwalczania takich anty-adblocków, i tu się zawiodłem na ludkach z EasyList, bo gdy wczoraj po półtora roku wróciłem na forum EasyList sprawdzić czy w końcu ten filtr został dodany, to się za głowę złapałem i wkurwiłem mocno, bo okazało się, że nie został dodany więc w tym drugim linku który wyżej podałem, zacząłem dopytywać i ciągnąć za język dlaczego do cholery ten filtr nie został jeszcze dodany po ponad półtora roku, i odpisał ludek z EasyList, że oni wszyscy nie zauważyli (czyli przeoczyli) wątku/filtru Kurnika, i że ja powinienem był odświeżać wątek, no i tu mnie kurwa szlag trafił, bo co kurwa w ogóle za pierdolenie, że nie zauważyli, jak można przez półtora roku nie zauważyć wątku i nie dodać filtra do listy? Zbiorowa ślepota ich dopadła nagle czy jaki huj? A po drugie wątek był odświeżany 3 razy przez cały pierwszy miesiąc i nawet admin forum w wątku na moje dopytywanie się kiedy w końcu zostanie dodany filtr do listy odpisał, że wtedy gdy autorzy listy będą mieli czas żeby dodać, czyli zasugerował mi (jak teraz widać celowo żeby wyprowadzić mnie w pole) żebym spokojnie czekał, zamiast się  ciągle dopytywać, skoro tak więc tak też zrobiłem, przestałem się dopytywać i odświeżać wątek i cierpliwie czekałem przez półtora roku, tylko po to żeby po półtora roku usłyszeć bezczelnie od autorów, że autorzy EasyList nie dodali filtra bo nie zauważyli wątku, bo go nie odświeżałem wystarczająco i gdzieś wątek utonął w dalszych stronach forum. A po chwili przyszedł admin forum i dorzucił bezczelnie, że przecież można sobie filtr dodać ręcznie i bezczelnie zablokował wątek jakby pociągał spłuczkę od kibla w toalecie, nie pozwalając tym samym dokończyć dyskusji i wytłumaczyć temu kretynowi, że on chyba nie czyta w ogóle, albo nie rozumie, że ja sobie kurwa ten filtr dodałem ręcznie już półtora roku, i że ręcznie to on może sobie konia zwalić, i że mi teraz chodzi tylko o to żeby ten filtr był dodany do listy, żeby każdy nawet nie znający się na dodawaniu filtrów miał blokowany Kurnik "out of box", czyli dokładniej ujmując dla szarych mas, dodatkowo ten admin forum podobnie blokuje wszystkie inne wątki tego typu np tu: https://forums.lanik.us/viewtopic.php?f=23&t=33220 , w których ktoś się dopytuje dlaczego jego filtr nie został dodany, tak jakby nie chciał żeby ktoś to drążył i zadawał niewygodne dla nich pytania i żeby nie musieli się  zbytnio tłumaczyć. Czyż człowieka w tej chwili może nie trafić szlag i może się nie domyślić prostego faktu, że te gnidy kłamliwie i bezczelnie wykręcają się bo blokowanie Kurnika nie było im w smak i prawdopodobnie są ułożeni z mafem i mieli z tego jakieś profity. Mam nadzieję, że po tym gdy ich przycisnąłem to teraz nie będą mieli wyjścia i w końcu dodadzą te filtry, ale nie jestem pewien bo w momencie gdy ten admin forum zablokował wątek, to w tym samym momencie dziwnym zbiegiem okoliczności dostałem jakby bana na forum, nie twierdzę, że dostałem bana, ale wygląda tak jakbym go dostał, tylko że w taki sprytny zakamuflowany sposób, tzw. cichy ban, otóż po zalogowaniu się na forum nie mogę nic zrobić, trzyma mnie w Panelu Użytkownika, nie mogę przeglądać forum, tworzyć wątków, dodawać postów, nawet wysłać prywatnej wiadomości, bo cokolwiek nie zrobię to otrzymuję jakieś komunikaty o błędach:

> You are not authorised to read private messages.

> You are not authorised to read this forum.

> This board has no forums.

> Fatal error: Cannot redeclare user_get_id_name() (previously declared in /home/lanik/forums/includes/functions_user.php:30) in **/home/lanik/forums/includes/functions_user.php** on line **85**

tym samym nie mogę nawet poinformować nikogo na forum o awarii, bez tworzenia drugiego konta, próbowałem także napisać posta jako gość, bo jako gość na szczęście mogę przeglądać forum ale nawet wtedy sypie błędem przy próbie napisania czegoś czy chociażby podglądu, nie wiem nawet czy będę mógł założyć nowe konto. Próbowałem czyścić ciasteczka / pamięć podręczną wiele razy, nawet zmieniałem IP i nic. Próbowałem nawet na forum poszukać coś o tym problemie i czy ktokolwiek miał kiedykolwiek taki problem, ale nikt nigdy nie miał, no masakra normalnie, a w Google są prawie same rozwiązania ze strony admina, a nie klienta. Jak widać mi przypadł ten zaszczyt jako pierwszemu doświadczyć tej parodii, zresztą zobaczcie na obrazkach:

https://i.imgbox.com/gfu9l15w.png
https://i.imgbox.com/K3W99bcB.png
https://i.imgbox.com/lOWyVlRO.png
https://i.imgbox.com/PzjPrjY2.png

Międzyczasie założyłem wątek na githubie do którego linka podałem na samym początku postu i poprosiłem o dodanie filtrów Kurnikowych do listy reek/anti-adblock-killer (to taka alternatywa dla tej listy Adblock Warning Removal List), ale tam także usłyszałem, żebym sobie dodał ręcznie, bo ta lista nie jest już aktywnie rozwijana i żebym międzyczasie poczekał aż ludki z EasyList dodadzą filtr na Adblock Warning Removal List. No cóż nie chciałbym snuć teorii spiskowych, ale z drugiej strony ta dziwna koincydencja dziwnych zdarzeń daje do myślenia, że maf jak widać mógł się ułożyć z co poniektórymi twórcami list, bo przecież gdy nie wiadomo o co chodzi to chodzi o pieniądze. Tak czy inaczej proszę wszystkich o rozpowszechnianie tego filtru Kurnikowego i dodawanie go do list.

**Comment by MajkiIT** [comment]
@gomoku dodaliśmy dzisiaj filtry zaproponowane przez @F4z z tego co widzę to działają. Zaraz napisze maila do twórców Easylist i zobaczymy co wyjdzie. Zawsze dodawali to i nie było problemu. Dam znać jak coś ustalę.

**Comment by gomoku** [comment]
No i co, kiedy dasz znać? Za 100 lat ? Buahahaha.  Nie no to chyba jakieś żarty, jeśli za 5 minut nie dodadzą filtra www.playok.com do EasyList lub jej suplementu Adblockowego to rozpierdolę im łeb za CELOWE niedodawanie tego filtra lub bardziej szczerze -  za SPRZEDANIE się mafowi + za kłamanie że "nie zauważyli" + za "zatykanie ust szmatą" (zamykanie topicu), a tobie za nieodzywanie się (a jeśli nie odzywasz się bo oni nie odzywają się, to i tak powinieneś o tym poinformować, więc dalej masz rozpierdolony łeb za nieodzywanie się, ale żeby ci było raźniej to oni też dodatkowo za nieodzywanie się tak jak ty, więc ostatecznie oni mają rozjebany łeb za 3 złe uczynki a ty za 1, no dobra to żeby było sprawiedliwie to tobie tylko połamię rękę). Wszyscy jesteście jak małpy nadające się do cyrku, No kurwa, tak nie można w huja ciąć.

**Comment by mathew85** [comment]
Naprawdę dobrze się czujesz? Przecież filtry zostały podane na forum EasyList. Dodaj je sobie manualnie do własnej listy. W czym problem? Przerasta Cię to?

A na przyszłość uszanuj cudzą pracę, którą się tutaj odwala, bo wszystko to jest za darmo w ramach wolnego czasu.

Jeżeli Ci to nie pasuję to naucz się samemu coś robić a nie liczyć, że wszystko zawsze dostaniesz pod nos.

Nie chcę karmić tego trolla, ale wg mnie to jest lekka przesada.

**Comment by gomoku** [comment]
> Naprawdę dobrze się czujesz? Przecież filtry zostały podane na forum EasyList. Dodaj je sobie manualnie do własnej listy. W czym problem? Przerasta Cię to?

Obalam twoją bzdurę, ciekawe pytanie to pierwsze, tylko że to pytanie to ja mogę zadać tobie (+ kilka innych), a nie ty mi:

Naprawdę dobrze się czujesz? 
Nie czytałeś co napisałem?
A może ja napisałem po chińsku? 
Albo ślepy jesteś?
A może nie umiesz czytać ze zrozumieniem?
Albo ułomny jesteś?
A może przerasta cię to?
Bo przecież wyraźnie napisałem:

" ja sobie kurwa ten filtr dodałem ręcznie już półtora roku, i że ręcznie to on może sobie konia zwalić, i że mi teraz chodzi tylko o to żeby ten filtr był dodany do listy, żeby każdy nawet nie znający się na dodawaniu filtrów miał blokowany Kurnik "out of box", czyli dokładniej ujmując dla szarych mas"


> A na przyszłość uszanuj cudzą pracę, którą się tutaj odwala, bo wszystko to jest za darmo w ramach wolnego czasu.
> 
> Jeżeli Ci to nie pasuję to naucz się samemu coś robić a nie liczyć, że wszystko zawsze dostaniesz pod nos

Obalam twoją kolejną bzdurę, znowu wracamy w górę i znowu to samo:

Naprawdę dobrze się czujesz? 
Nie czytałeś co napisałem?
A może ja napisałem po chińsku? 
Albo ślepy jesteś?
A może nie umiesz czytać ze zrozumieniem?
Albo ułomny jesteś?
A może przerasta cię to?
Bo przecież wyraźnie napisałem:

" Dzięki, że w ogóle tworzycie te listy"

> Nie chcę karmić tego trolla, ale wg mnie to jest lekka przesada.

 Obalam twoją kolejną bzdurę:
 
 Słuchaj muflonie,  wg mnie to jest lekka przesada to co piszesz i jeżeli ktoś tu jest trolem to ty, a nie ja, bo to ty pleciesz same bzdury, które obaliłem. Człeniu, proszę cię weź się ogarnij i jeżeli chcesz dyskutować ze mną to najpierw przeczytaj dokładnie co napisałem, bo póki co strzelasz ślepakami.

**Comment by MajkiIT** [comment]
@gomoku szczerze powiedziawszy to nie wiem podobnie @mathew85 o co Ci chodzi. Wysłałem maila i czekam. Do nich spada setki maili ze zgłoszeniami i nie będę kogoś pingował na siłę. Nie podali mi terminu w jakim się odezwą a czasami trwało to 3 tygodnie. 

Jak wiesz to nikt nie daje za korzystanie z filtrów ani złotówki i jak powiedział @mathew85 robimy to w wolnym czasie i nikt z nas nie dostał za to ani złamanego centa. 

Mam @gomoku prośbę do Ciebie przestań obrażać wszystkich, bo wcale to nie wychodzi na in plus. Dzięki tym osobom te filtry są dalej rozwijane i jestem za to im wdzięczny. Samo napisanie "Dzięki, że w ogóle tworzycie te listy" a po chwili walenie kogoś po głowie wcale nie świadczy o wdzięczności.

**Comment by gomoku** [comment]
> o co Ci chodzi.

O to żeby filtr do playok.com został w końcu dodany zanim nam włosy posiwieją.

**Comment by gomoku** [comment]
3 i pół tygodnia odkąd im przypomniałem o filtrze, którego rzekomo nie widzieli przez pół roku, oraz odkąd ty do nich napisałeś. I co? I gówno, śmiech na sali.

░░░░░░░░░░░█████████████
░░░░░░░░░███░███░░░░░░██
███░░░░░██░░░░██░██████████
████████░░░░░░████░░░░░░░██
████░░░░░░░░░░██░░██████████
████░░░░░░░░░░░███░░░░░░░░░██
████░░░░░░░░░░░██░░██████████
████░░░░░░░░░░░░████░░░░░░░░█
████░░░░░░░░░░░░░███░░████░░█
█████████░░░░░░░░░░████░░░░░█
███░░░░░██░░░░░░░░░░░░░█████
░░░░░░░░░███░░░░░░░██████
░░░░░░░░░░░██░░░░░░██
░░░░░░░░░░░░███░░░░░██
░░░░░░░░░░░░░░██░░░░██
░░░░░░░░░░░░░░░███░░░██
░░░░░░░░░░░░░░░░░██░░░█
░░░░░░░░░░░░░░░░░░█░░░█
░░░░░░░░░░░░░░░░░░██░██
░░░░░░░░░░░░░░░░░░░███

**Comment by gomoku** [comment]
Ty ziomek weź wytłumacz o co chodzi, bo filtr wciąż nie dodany, ja nie mogę od miesiąca nic napisać na ich forum bo mi ciągle nie działa (a nie chciałbym cię już męczyć, tylko właśnie ich), ty się nie odzywasz (być może dlatego bo oni się nie odzywają). Co jest kuurwa mać? Jakaś parodia.

**Comment by gomoku** [comment]
Widzisz ziomek, ty też jak widać trzymasz sztamę z nimi, ale to było do przewidzenia, bo jesteście wszyscy z tej samej branży i wszyscy będziecie się nawzajem bronić i milczeć jak grób:

1) pomimo upływu tak dużego czasu (ponad 1 rok i 7 miesięcy) i pomimo kilkunastu przypomnień i próśb z mojej strony te PSY z forums.lanik.us dalej celowo nie dodały filtru playok.com na główną listę, tłumacząc się zabawny i dziwny sposób, zbywając mnie i zamykając wątek w którym o tym pisałem

2) po chwili do tego doszło, że nie mogłem się zalogować na forums.lanik.us niby jakiś błąd, ale wyglądało na "cichy ban" i faktycznie okazało się, że to był cichy ban

3) poszedłem z tym wszystkim na forum AdBlock Plusa opisać tę blokadę konta:
[https://adblockplus.org/forum/viewtopic.php?f=23&t=51632](https://adblockplus.org/forum/viewtopic.php?f=23&t=51632)

,  i poprosiłem o odblokowanie konta na forum EasyList, no i odblokowali na EasyList mi konto,

4) no ale gdy później zacząłem opisywać zachowanie tego gościa lanika z EasyList to okazało się, że na  forum AdBlocka  jest to samo, niejaki mod "mapx" zaczął trolować tak samo jak ten mod "lanik" z forum EasyList, bronił tamtego, bo są z tej samej branży, podobnie jak tamten lanik, ten też nie mógł mnie pokonać w dyskusji na argumenty, lał wodę, zaczał trolować, nie odpowiadał na pytania, nie odnosił się merytorycznie, coś tam srał na mnie, gdy kontynuowałem dociskanie obroży za pomocą bezlitosnych argumentów, to zauważył że zaczał przegrywać dyskusję, więc zaczęło się to samo co na forum EasyList, zamyknął mi wątek 2krotnie, wyciał ostatni post, na końcu ban i na jednym forum:

[https://s3.dodajfote.pl/2017/03/11/adblock_ban7d651.png](https://s3.dodajfote.pl/2017/03/11/adblock_ban7d651.png)

i na drugim:

[https://s3.dodajfote.pl/2017/03/11/lanik_ban470ff.png](https://s3.dodajfote.pl/2017/03/11/lanik_ban470ff.png)

, powycinali moje posty, ukryli wątek na forum EasyList:

 [https://forums.lanik.us/viewtopic.php?f=9&t=35798](https://forums.lanik.us/viewtopic.php?f=9&t=35798)

 (nie usunęli tylko ukryli, że trzeba się zalogować żeby odczytać:

[https://s3.dodajfote.pl/2017/03/11/lanik_181bc5.png](https://s3.dodajfote.pl/2017/03/11/lanik_181bc5.png)

, ale nawet po zalogowaniu dalej zwykły użytkownik nie ma uprawnień żeby obejrzeć bo założyli klauzulę ściśle tajne:

[https://s3.dodajfote.pl/2017/03/11/lanik_234147.png](https://s3.dodajfote.pl/2017/03/11/lanik_234147.png)

, próbowałem odzyskać z archiwum internetowego ale niestety nie udało się, szkoda że nie zrobiłem kopii po prostu wyleciało mi to z głowy i zapomniałem że admini/modzi są w stanie posunąćsię do tak plugawych zagrawek.

Jeśli chodzi o ten wątek z pierwszego linku z punktu 3) to wycięli mi ostatni post tu jego kopia:

> 
> Oh  I see you you've removed my post so quickly, what are you so afraid you TROLL? It seems that the truth has hurted you, I'm really sorry. This is a copy of my last post which is being removed by you (just because you have lost the discussion):
> 
> [quote="mapx"]ok, you have presented your arguments, it's time to stop this "discussion".
> 
> topic closed.[/quote]
> 
> Yes, you are right, I've presented my arguments because a discussion requires arguments, but you haven't presented your arguments yet, and that's why it is me who is discussing and you who is "discussing", so stop saying that it is vice versa and stop saying that it is me who is "discussing" or that we both are "discussing", please stop comparing me to you, and stop bringing me to your level, because it is only you who is "discussing" (or more clearly - trolling) here.
> 
> I see you've locked the thread, any explanation why or is it your only "argument" - a lock thread button? It is  so sad, it seems that due to lack of arguments and therefore due to losing the discussion, you are running away from the discussion by means of arguments and merits. 
> 
> Could you just stop removing this post like a rat, and begin to behave like a human and explain to everyone why you've removed this post? I've not used vulgarims anywhere here in this post, so I'm wondering what is your [insert something] problem with locking threads/ removing posts. Stop being an [insert something]. You only gets ridiculed by locking threads / removing posts.

**Comment by gomoku** [comment]
I co plugawy kundlu milczysz jak grób.

**Comment by MajkiIT** [comment]
Nie odzywam się z wielu powodów. Jest to spowodowane tym, że masz każdego za nic i obrażasz wszystkich. Jeśli wszędzie stosujesz taki styl bycia to nie dziwię się, że każdy cię blokuje.

**Comment by MajkiIT** [comment]
@gomoku ponadto prosiłbym Cię powstrzymanie się o tego typu komentarzy w moim czy czyimkolwiek kierunku.

**Comment by gomoku** [comment]
Rzeczywiście nie odzywasz się z wielu powodów które są przypadkiem owiane tajemnicą i utajnione do poziomu epsilon, a jednym z nich jest brak kontr-argumentów, bo po prostu nabrałeś wody w usta, posłuchaj, teraz w tym twoim poście (do wcześniejszych nic nie mam) zachowujesz się podobnie jak oni (czyli tak jak zachowują się trole) bo lejesz wodę na młyn jak oni,  operujesz pustymi ogólnikami jak oni, spławiasz jak oni, w ogóle nie odniosłeś się ani trochę merytorycznie do mojego postu jak oni, do kwestii w nim poruszonych jak oni, nie podałeś żadnych kontr-argumentów jak oni lub nie przyznales mi racji , a tylko czepiłeś się na siłę o coś drugorzędnego, podobnie jak oni z całego długiego merytorycznego bogatego posta pełnego konkretnych twardych i sensownych argumentów i dowodów, wygrzebali i czepiali się na siłę się kilku ostrzejszych słów (które byly poparte argumentami) i próbowali zrobić ze mnie jakiegoś huligana, konczylo sie na zamykaniu wątku i wycinaniu postów w którym nie było wulgaryzmu. mam wrażenie, że zaraz zaczniecie chyba czepiać się literówek z braku argumentów. Za nic to mają oni mnie, od samego poczatku , co potwierdzili swoim zachowaniem które opisalem. I zauwazylem teraz ze ty ich kryjesz. No coz - koledzy po branzy.

**Comment by MajkiIT** [comment]
@gomoku nie owiane tajemnicą tylko nie mam ani siły ani czasu słuchać twoich żali na pół świata. Nie mam wpływu na nich i nie mam zamiaru zmuszać ich do czegoś. To ty walisz ogólnikami, bo nie znasz ani mnie ani ich. Ja  ani chłopaki nie dostajemy kasy za tworzenie filtrów i poświęcamy swój czas . Wyzywanie kogoś od kundli nie jest miłe a dodatkowo świadczy o tym, ty musisz się do kogoś przyczepić.
