### ISSUE TITLE
bet-at-home.com

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#2065]
nie mozna zrobic przelewu z przelewy24.pl, nie pojawia sie strona

**Comment by MajkiIT** [comment]
u mnie jest ok. Uzyłem konta gość.

**Comment by lukjan32** [comment]
aha, u mnie na koncie nie.

sprawdzilem, dalem do wyjatkow, i dziala.

**Comment by F4z** [comment]
@lukjan32 próbujesz zrobić przelew klikając na tej stronie? - `https://www.bet-at-home.com/pl/account/deposit`

Jeśli tak, to może coś takiego:
`@@||www.bet-at-home.com/pl/account/deposit/przelewy24$popup,domain=www.bet-at-home.com`

**Comment by F4z** [comment]
To blokuje ta reguła z listy AAK - `||bet-at-home.com^$popup`
Co ciekawe w Chrome/Operze to jest blokowane, a w Firefoxie już nie, a teoretycznie chyba powinno być?

**Comment by F4z** [comment]
To znaczy w Firefoxie czasami jest blokowane jako `popup` i zgodnie z regułą tak raczej powinno być, a czasami jest traktowane jako `popunder` i wtedy przechodzi do tej strony.

**Comment by lukjan32** [comment]
@F4z tak, z tej strony.

aha, prosze zrobic filtr i dac do listy.

**Comment by MajkiIT** [comment]
@F4z Dzięki 
Co powiesz na taką regułę, bo problem może być na innych stronach z szybkimi płątnościami?
`@@||www.bet-at-home.com/pl/account/deposit/$popup,domain=www.bet-at-home.com`

**Comment by F4z** [comment]
@MajkiIT no tak.
Można też zamiast `/pl/` wstawić gwiazdkę żeby jak ktoś korzysta ze strony w innym języku też nie blokowało.
`@@||www.bet-at-home.com/*/account/deposit/$popup,domain=www.bet-at-home.com`

**Comment by lukjan32** [comment]
dzieki, dziala.
