### ISSUE TITLE
secure.payu.com

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#20672]
url z puli: `https://secure.payu.com/pay/?orderId=[reacted]&statusCode=SUCCESS&refReqId=[reacted]#/status`

resztka po zakończeniu płatności:

```
payu.com#?#.status > .main > p:-abp-has(+ a[href^="https://ad.doubleclick.net/"])
```

Niestety nie mogę podać linka do testowania, musi wystarczyć zdjęcie:

![obraz](https://user-images.githubusercontent.com/35370833/152699409-146121dd-76e1-4e7e-b4dc-cbba3a4fa6db.png)

oryginalną reklamę blokuje EasyList tym: ` a[href^="https://ad.doubleclick.net/"]`

![obraz](https://user-images.githubusercontent.com/35370833/152699437-8447ed22-17be-492b-abc5-4dc5a408dfe9.png)

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję
