### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2067]
Komunikat o adblocku i reklamy - `http://www.elektroda.pl/`

![image](https://cloud.githubusercontent.com/assets/11742596/22339795/7dc859c6-e3eb-11e6-9650-73446fba2623.png)

Na przykład:
`elektroda.pl###x2-block-info`
`elektroda.pl##.toNiePrzeszkadza`
`elektroda.pl##.badzcieLudzmi`

**Comment by MajkiIT** [comment]
@F4z Dzięki 

Ciekawe czy te nazwy klas są skierowane do nas ?
`##.toNiePrzeszkadza`
`##.badzcieLudzmi`

**Comment by F4z** [comment]
Też się nad tym zastanawiałem 😜

**Comment by mathew85** [comment]
Na starym wyglądzie też się pojawiły(dostępny po zalogowaniu)
![image](https://cloud.githubusercontent.com/assets/11385099/22350566/9f60e3ea-e414-11e6-940e-bbb3a18a239e.png)

**Comment by MajkiIT** [comment]
@mathew85 dzięki. Poprawię jutro.
