### ISSUE TITLE
nokiahacking.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20697]
http://nokiahacking.pl/wszystkie-dzialajace-kody-serwisowe-vt44.htm

**Comment by MajkiIT** [comment]
@blocker999 nadal to masz?

**Comment by blocker999** [comment]
Tak

![nh](https://user-images.githubusercontent.com/23176832/154039569-9166a36c-a196-41d9-94f7-5e7141a2fd87.png)

**Comment by krystian3w** [comment]
To jest fejkowy post, tam normalnie jest ładowana reklama.

**Comment by krystian3w** [comment]
@olegwukr może dodać taki filtr:

`nokiahacking.pl###pfirstad`
