### ISSUE TITLE
pudelek.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#2069]
Adblock na filmach:
`http://www.pudelek.pl/artykul/104245/haker_ktory_ukradl_nagie_zdjecia_amerykanskich_gwiazd_zostal_skazany_na_9_miesiecy_wiezienia/#`

![image](https://cloud.githubusercontent.com/assets/11385099/22362047/04443b72-e460-11e6-8212-cffc3e4183fd.png)

**Comment by xxcriticxx** [comment]
grozny haker to @F4z :)
