### ISSUE TITLE
ranking.abczdrowie.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#20698]
`https://ranking.abczdrowie.pl/d/andrzej-szydelko-ginekolog-bytom-26054#opinion`

Strona robi się biała w Firefox na Android&Windows (nie mam GNU/Linux do testu and macOS).

Niby błąd generuje m.in. set-timeout defuser:

```
abczdrowie.pl##+js(no-setTimeout-if, visibility, 0)
```

Nie mam pomysłu na naprawę ale filtr może już nie blokuje reklam, wtedy można by go zakomentować. Nie wykluczam, że `#@#` jest już dodane w AdGuard Base.

**Comment by MajkiIT** [comment]
@krystian3w dziękuję
