### ISSUE TITLE
naziemna.info

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#2070]
na tej stronie nie mozna zaglosowac w ankiecie.

**Comment by MajkiIT** [comment]
`@@||www.naziemna.info/wp-content/plugins/uk-cookie-consent/assets/js/uk-cookie-consent-js.js$script,domain=www.naziemna.info`

**Comment by lukjan32** [comment]
dziala, prosze dodac

**Comment by MajkiIT** [comment]
Dzisiaj lub jutro zrobię update filtrów ciasteczek.

**Comment by lukjan32** [comment]
dobra, czekam :)

prosze wykombinowac cos krotszego, jak sie da.

**Comment by MajkiIT** [comment]
spoko damy radę :)

**Comment by lukjan32** [comment]
ok, czekam.
