### ISSUE TITLE
Grupa techManiaK.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20709]
Stary temat ale niedokończony #3587

Proszę o dodanie rtvmaniak.pl do ###okazja dnia oraz przenieście to do sociali gdyż to przekierowuje do profilu na fb.

Resztki na głównej oraz w artykułach : 

https://www.rtvmaniak.pl/9609806/promocja-na-dekoder-dvb-t2/
https://www.fotomaniak.pl/143122/aparat-do-2000-zl/
https://www.agdmaniak.pl/82065/irobot-warto-kupic/
https://www.gizmaniak.pl/90013/telewizor-65-cali-do-salonu-jaki-wybrac/
https://www.gsmmaniak.pl/1180989/amazfit-band-5-test/
https://www.luxmaniak.pl/41739/telewizja-i-internet-czym-sie-sugerowac-zanim-wybierzesz-operatora/
https://www.blogomaniak.pl/1418/najlepszy-widget-tworzenie-tabel-wordpressie/

Resztki na głównej oraz " ceneo " na headerze: 

acermaniak
techmaniak.pl

Proszę o jakieś uwagi w komentarzach być może coś przeoczyłem.

NIE ZAMYKAĆ, TEMAT BĘDZIE KONTYNUOWANY !!!

**Comment by krystian3w** [comment]
Ja bym zasugerował na takie okazje używać formularza z zaznaczaniem wielu punktów, bo potem nie widać że tu trzeba coś przenieść a majkiit raczej niechętnie zrobi PR w repozytorium dev w okolicy marca/kwietnia.

**Comment by krystian3w** [comment]
Drugą trudnością jest, że generycznie angielskie EasyList wycina iframe reklamowy w całości tym:

`/www/delivery/*`

Więc z 90% używających ABP/uBO/AG z dezaktywowanymi zgodami na nienatrętne reklamy całkowicie nie zobaczy na razie ramki.

---

Jak widzisz ramki to CPU niewyrabia lub ręcznie odblokujesz co zmiany w EasyList.
