### ISSUE TITLE
pulskids.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20711]
fb ( na dole )

**Comment by hawkeye116477** [comment]
Wygląda na to, że @krystian3w już to zrobił (https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/commit/45499e0d11b56a393827c3d10748402940ba3260).

**Comment by krystian3w** [comment]
Ogarnąłem te ze stopki puls.
