### ISSUE TITLE
audiostereo.pl #center

### ISSUE THREAD

**Issue by michalsamsel** [MajkiIT/polish-ads-filter#20719]
W filtrze w linii 2713 widnieje zapis blokujący tag center na wielu stronach w tym na audiostereo.pl, prosiłbym o usunięcie lub zmianę tego ponieważ niektóre elementy w narzędziach moderatorskich używają tego znacznika przez co korzystanie z nich jest utrudnione lub niemożliwe.

**Comment by krystian3w** [comment]
Linia może zmieniać pozycję, używaj lepiej "direct url" z numerem commitu:

https://github.com/MajkiIT/polish-ads-filter/blob/d35e1fe7e4aacc3972cdcca40de5fd56d1d3f34d/polish-adblock-filters/adblock.txt#L2713

`https://github.com/MajkiIT/polish-ads-filter/blob/d35e1fe7e4aacc3972cdcca40de5fd56d1d3f34d/polish-adblock-filters/adblock.txt#L2713`
