### ISSUE TITLE
The site gen.xyz is brocken beacause a list use absolutely incorrect filter

### ISSUE THREAD

**Issue by IRainman** [MajkiIT/polish-ads-filter#20718]
Filter
xyz##[class$="_right"]
Filter list
[POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda](moz-extension://b2d2d124-bfd4-451e-850c-30296519110d/asset-viewer.html?url=POL-0) 
Context
gen.xyz
Typedom
URL https://gen.xyz/account/domainchecker.php

**Comment by krystian3w** [comment]
But this is duplicated function from header:

![obraz](https://user-images.githubusercontent.com/35370833/156933782-17fdc240-62d0-4388-845c-fea725686f7b.png)
