### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by PerfectSalad** [MajkiIT/polish-ads-filter#20742]
**unhidden things**

### Link bezpośredni (Specific link)

```markdown
https://www.wp.pl/
```

### System operacyjny (Operating system)

macOS

### Przeglądarka internetowa (Web browser)

Google Chrome

### Bloker (Blocker)

uBlock Origin 1.41/8

### Używane listy filtrów (Used filter lists)

uBO enabled-by-default with english + your regional (Polish) filter list for uBlock Origin / AdGuard

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by hawkeye116477** [comment]
It's duplicate of #18472.
