### ISSUE TITLE
bgk.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20753]
Resztka ( tło )

**Comment by krystian3w** [comment]
Żadna resztka, scroll nie działa = błąd.

**Comment by krystian3w** [comment]
@gwarser, chyba ::before umie psuć element picker, że działają tylko sieciowe filtry, ale to jeszcze nie bug jaki czasem się zdarza z czapy, że nie działa kosmetyczne ukrywanie.

**Comment by gwarser** [comment]
Dla pseudoelementów chyba nigdy nie działał, bo nie można ich w JavaScripcie wskazać.
