### ISSUE TITLE
cdaction.pl

### ISSUE THREAD

**Issue by AroKol78** [MajkiIT/polish-ads-filter#20764]
puste miejsca po reklamach
`https://cdaction.pl/newsy/wojna-na-ukrainie-stanowisko-wargamingu-i-milion-dolarow-na-czerwony-krzyz`

propozycja: `cdaction.pl##div[id^="div-gpt-ad-"]`

**Comment by hawkeye116477** [comment]
Tyle tylko, że ta reguła jest odblokowywana przez listę gorhilla, zapewne chodziło o antyadblocka. Zamiast tego jest taka => `*##[id^="div-gpt-ad"]:style(width:1px!important;height:1px!important;min-width:1px!important;min-height:1px!important;margin:0!important;padding:0!important;overflow:hidden!important;opacity:0!important)`, ale ona nie działa w uBO Legacy, bo on nie obsługuje zapisu z gwiazdką.

**Comment by AroKol78** [comment]
> zapewne chodziło o antyadblocka antyadblocka

nie wiem o co chodzi

> strona nie wyświetla się prawidłowo na tych przeglądarkach, dla których jest uBO Legacy

nie wiem o co chodzi

> nie obsługuje zapisu z gwiazdką

tylko w `domain=` 

<details><summary>pic3:</summary>

**bez** `##div[id^="div-gpt-ad-"]`
![und01](https://user-images.githubusercontent.com/70756447/157871042-31e3f320-8dae-4799-b8bb-0a9bef413ce5.JPG)
**z** `##div[id^="div-gpt-ad-"]`
![und02](https://user-images.githubusercontent.com/70756447/157871057-48d46178-b332-4de9-8dce-5afb1c86b006.JPG)
![und03](https://user-images.githubusercontent.com/70756447/157871063-f11d5628-19af-4db9-a6ad-3593e6a7b672.JPG)

</details>

**Comment by hawkeye116477** [comment]
Tak jak mówię, problem ewidentnie jest jedynie w uBO Legacy.

> tylko w domain=

Czyli twierdzisz, że powinno to działać, więc może to błąd.

**Comment by AroKol78** [comment]
nie jestem specem od filtrów
> Tak w ogóle to ta strona nie wyświetla się prawidłowo na tych przeglądarkach, dla których jest uBO Legacy, brakuje np cytatu firmy Wargaming.

możesz wyjaśnić/rozwinąć/wskazać

**Comment by hawkeye116477** [comment]
> możesz wyjaśnić/rozwinąć/wskazać

Chodziło o ten pomarańczowy cytat, ale najwyraźniej jak zaobserwowałem problem występuję tylko w Pale Moonie dla Linuksa, a na Windzie jest ok.

PS: Logger uBO Legacy oznacza zapis z gwiazdką jako błędny w obu przyapdkach, czyli w `$domain` i jak jest na początku również.

**Comment by AroKol78** [comment]
ok
to może można dodać jak nie koliduje z innymi wariantami przeglądarek/blokerów
ewentualnie podrzucić do `uBlock filters - Legacy`
a jak nie to zachowam w "My filters"

**Comment by AroKol78** [comment]
offtopic:
> Chodziło o ten pomarańczowy cytat, ale najwyraźniej jak zaobserwowałem problem występuję tylko w Pale Moonie dla Linuksa, chyba to jest najwyraźniej ten słynny problem z ciemnym motywem.

może pomoże usunięcie `skia` z `gfx.canvas.azure.backends` `gfx.content.azure.backends`
i/lub wyłączenie "direct2d" (przełącznik `gfx.direct2d.disabled`)

**Comment by hawkeye116477** [comment]
Nie pomaga, podobnie zmiana motywu w systemie na jasny również nie. Tak więc chyba trzeba będzie to zgłosić na forum PM.

**Comment by krystian3w** [comment]
Ten adblock to nie na każdej stronie działa ale niby CSS uznano za lepszy niż globalnie odpalany skryptlet: `##+js(nostif, f.parentNode.removeChild(f), 100)`

przykładowo jak on wygląda:  https://github.com/uBlockOrigin/uAssets/issues/7986

**Comment by krystian3w** [comment]
uBO legacy można sprawdzić czy dalej ma buga z przecinkami:

```
fejkowa-domena.pl,##[id^="div-gpt-ad"]:style(width:1px!important;height:1px!important;min-width:1px!important;min-height:1px!important;margin:0!important;padding:0!important;overflow:hidden!important;opacity:0!important)
```

Ale może to naprawili jeszcze przez napisaniem WebExtension - wtedy ktoś musi te 1500 publicsuffixów wypisać na liście legacy.

**Comment by AroKol78** [comment]
> uBO legacy można sprawdzić czy dalej ma buga z przecinkami:
> 
> ```css
> fejkowa-domena.pl,##[id^="div-gpt-ad"]:style(width:1px!important;height:1px!important;min-width:1px!important;min-height:1px!important;margin:0!important;padding:0!important;overflow:hidden!important;opacity:0!important)
> ```

sprawdziłem  na `cdaction.pl` i z przecinkiem też czyści puste miejsca po reklamach

**Comment by krystian3w** [comment]
@Yuki2718 ask volunteers about add falback to support for `*##` by something like:
```
no-ported-asterix.com,##[id^="div-gpt-ad"]:style(width:1px!important;height:1px!important;min-width:1px!important;min-height:1px!important;margin:0!important;padding:0!important;overflow:hidden!important;opacity:0!important)
```

**Comment by krystian3w** [comment]
Czyli naprawili przecinek...

**Comment by AroKol78** [comment]
> problem ewidentnie jest jedynie w uBO Legacy.

"uBO Legacy" w sumie to niszowy bloker, więc nie ma co zabierać czasu
