### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by micielski** [MajkiIT/polish-ads-filter#20774]
### Zrzut ekranu 

![image](https://user-images.githubusercontent.com/73398428/157956897-2f8fa304-f7e9-4ee2-aa99-d893d9a71a46.png)
po prawej i lewej na czarnym pasku
### Link bezpośredni 
https://filmweb.pl

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
1. wejść na stronę filmweba
2. jeśli nie jest się zalogowanym, odświeżyć stronę lub przejść na jakąś podstronę

### Moja konfiguracja 
**Przeglądarka internetowa:** 
LibreWolf 97.0.2
**Rozszerzenia i skrypty:** 
Najnowszy uBlock Origin (wersja stabilna)

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda

**Comment by MajkiIT** [comment]
@micielski  nadal to masz ?

**Comment by micielski** [comment]
już nie
