### ISSUE TITLE
polkurier.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20772]
( na dole ) : https://www.polkurier.pl/

**Comment by krystian3w** [comment]
Kiboke dodał generyk, decyduje @hawkeye116477 czy powielamy "`###cookieIW`" z ograniczeniem do 1 przypadku lub "TLD" pl.

**Comment by hawkeye116477** [comment]
Nie powielamy, w innym przypadku lista IDCAC nie byłaby wymagana.
