### ISSUE TITLE
planeta.fm

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2079]
ad block 

`http://www.planeta.fm/sluchaj/online/Planeta-Trance.html`

![capture](https://cloud.githubusercontent.com/assets/15007183/22390552/b56e04ce-e4b9-11e6-8b65-cc1b8b6518ce.PNG)

**Comment by MajkiIT** [comment]
Po dodaniu 
`@@||myao.adocean.pl/files/js/ado.js$script,domain=www.planeta.fm`

znika adblock ale czeka na reklamę

**Comment by xxcriticxx** [comment]
@MajkiIT ja niemam zadnych reklam ztym gra odrazu muzyka to samo doastalem na easylist forum 


add

Code: Select all

`@@||myao.adocean.pl/files/js/ado.js$script,domain=planeta.fm`

privacy

Code: Select all

`/eplayer-stats.js`
`/google-publisher-tag.js`

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki

**Comment by xxcriticxx** [comment]
cos sie zmienilo ad block is back!

![capture](https://cloud.githubusercontent.com/assets/15007183/22591270/aa499c3e-e9e1-11e6-9968-bcbfe2dfef0a.PNG)

**Comment by xxcriticxx** [comment]
@F4z potrzebuje pomocy cos mi host file bolkuje i mam dalej ad block

**Comment by xxcriticxx** [comment]
host blokuje to na tej stronie


```
Feb  4 08:10:41 dnsmasq[14961]: /etc/pihole/gravity.list pro.hit.gemius.pl is 192.168.1.131
Feb  4 08:10:41 dnsmasq[14961]: /etc/pihole/gravity.list pro.hit.gemius.pl is fe80::9e85:682d:25:5dea
```

**Comment by F4z** [comment]
@xxcriticxx tylko to?
Nie blokuje niczego związanego z `adocean.pl`?

**Comment by xxcriticxx** [comment]
Moment sprawdze

**Comment by xxcriticxx** [comment]
tez jest 


```
::: /etc/pihole/list.0.raw.githubusercontent.com.domains (2 results)
0.0.0.0 myao.adocean.pl
0.0.0.0 s1.myao.adocean.pl
```

ale jak wchodze na strone to pokazuje ze blokuje `gemus.pl`

**Comment by xxcriticxx** [comment]
ok dodalem do whitelisty i pomoglo

**Comment by F4z** [comment]
To fajnie :)
