### ISSUE TITLE
lotto.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20793]

**Comment by krystian3w** [comment]
Pop-up trzeba wykluczyć, że blokuje pojawianie się weryfikacji wieku.

**Comment by blocker999** [comment]
RODO

**Comment by krystian3w** [comment]
Nie kumasz, trzeba sprawdzić  czy pod pop-upem renderuje się poprawnie inny pop-up.

A nie, że mnie ładuje się tekst "spadaj malolacie z Lotto".
