### ISSUE TITLE
Zdublowany adres blokuje wykonanie do końca importu na mikrotiku 

### ISSUE THREAD

**Issue by Pewes** [MajkiIT/polish-ads-filter#20854]
### Co trzeba zrobić, aby pojawił się element albo błąd?
1. Import pliku do mikrotika -> [polish-ads-filter](https://github.com/MajkiIT/polish-ads-filter)/[polish-mikrotik-filters](https://github.com/MajkiIT/polish-ads-filter/tree/master/polish-mikrotik-filters)/addHoleMalwareIPs.rsc
2. 
3. 

### Moja konfiguracja 
**Przeglądarka internetowa:** 

**Rozszerzenia i skrypty:** 

**Listy filtrów:** 
1. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Zdublowany adres: 67.165.206.193

**Comment by krystian3w** [comment]
Duplicate of #20377

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/20376
