### ISSUE TITLE
polstream.ml

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#20856]
Hej dawno mnie tu nie było ale mam kwiatuszka dla was od znajomego

Przeglądarka Opera
uBlock Origin 1.41.8
Używane listy: 
![unknown](https://user-images.githubusercontent.com/21177361/159544599-1017f0fc-bcd8-477a-8477-64215332c444.png)

Problem? wykrywanie adblocka.
 ![unknown (1)](https://user-images.githubusercontent.com/21177361/159544824-fc0a991c-6b90-4279-bbd8-d64080cef4cc.png)

**Comment by xxcriticxx** [comment]
@gzenio22 witamy po rocznej przerwie!

**Comment by gzenio22** [comment]
chyba strona fikła

**Comment by krystian3w** [comment]
AdamWr naprawił
