### ISSUE TITLE
witek.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20879]

**Comment by krystian3w** [comment]
Mnie działa stary filtr: `witek.pl##div[id^="st_notification_"][style*="display"]` https://github.com/MajkiIT/polish-ads-filter/blob/2c48e9e1e4909dae8f16a77bf70c97cc1bdd344d/cookies_filters/adblock_cookies.txt#L128

Jak CPU nie wyrabia to nie ma chętnych na optymalizację listy by miała mniej linii aka #20887 - tu raczej nie ma opcji przerobienia na filtr sieciowy jakby taki miał wyjątkowo mniejszy lag.

W przypadku wersji beta wyglądu proszę podawać url co ją aktywuje lub pełną instrukcję aktywacji.
