### ISSUE TITLE
szklo-dekor.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20887]
https://szklo-dekor.com/?lang=pl

**Comment by krystian3w** [comment]
mnie działa generyk Kiboke:

`/wp-content/plugins/cookie-notice$domain=~barzahlen.de|~kapitalkontor.com`

nie wiem na ile stary..., wykluczone domeny wskazują, że raczej stary - zostaje ocenić czemu CPU nie wyrabia i ignoruje filtry sieciowe.

**Comment by krystian3w** [comment]
Zostawiam do decyzji @hawkeye116477  czy jest na to jakieś obejście poza przepisywaniem większości na filtry kosmetyczne.

**Comment by hawkeye116477** [comment]
Jest też nawet reguła kosmetyczna na naszej liście. Także to jakiś problem po stronie blockera999.
