### ISSUE TITLE
zetchilli.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2090]
napis na dole o ad blocku ale radio gra

`http://www.zetchilli.pl/sluchaj/online/Chilli-ZET-online.html`

![capture](https://cloud.githubusercontent.com/assets/15007183/22398727/4456b756-e55c-11e6-97c5-d6757493e600.PNG)

**Comment by MajkiIT** [comment]
www.zetchilli.pl##.adblock-info
