### ISSUE TITLE
grupa - bilety od roboticket

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20906]
Proponuję dodać regułe ogólną `pl##.footer-social-media` bo troche tego jest i pewnie kilka przybędzie, oto przykładowe strony ( na dole ) : 

bilety.ksul.pl

bilety.lechia.pl

bilety.cracovia.pl

bilety.lechpoznan.pl

bilety.stalgorzow.pl

bilety.wartapoznan.pl

bilety.jagiellonia.pl

bilety.gornikzabrze.pl

bilety.gornik.leczna.pl

bilety.wybrzezegdansk.pl

**Comment by krystian3w** [comment]
Trochę za mało domen, mamy niby zbierane w  1 linię takie co mają z 50-80 marek na podobniej zasadzie `nazwa-miasta.pl` bez przerobienia na generyk, bo za rzadko tam dochodzą nowe.
