### ISSUE TITLE
duathlonradwanice.pl

### ISSUE THREAD

**Issue by lukasamd** [MajkiIT/polish-ads-filter#20938]
### Zrzut ekranu 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/1265016/162577035-148e7c65-b3ae-461f-8361-99b674bcf194.png">

### Link bezpośredni 
duathlonradwanice.pl

### Co trzeba zrobić, aby pojawił się błąd?
1. Wystarczy wejść na stronę

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Chrome stable

**Rozszerzenia i skrypty:** 
Adguard

**Listy filtrów:** 
1. Domyślne Adguarda
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by hawkeye116477** [comment]
To może trzeba dopisać `:not(body):not(html)` do reguły.

**Comment by krystian3w** [comment]
Lub obserwować ile jeszcze będzie AdGuard implementował ochronę obu w macOS.
