### ISSUE TITLE
otodom.pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#20958]
Witam Panowie czy istniej jakaś szansa by zablokować reklamę .Próbuje ale nic nie wychodzi.

**Comment by MajkiIT** [comment]
@kolor33  a mozesz podesłać, bo nie widzę?

**Comment by kolor33** [comment]
Jak szukasz to za pierwszym razem wyskakuje .

https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie/cala-polska#from404
![1](https://user-images.githubusercontent.com/32041737/163598003-26bb9714-ee95-40f5-8da1-2a087e446432.jpg)

**Comment by kolor33** [comment]
Czy Pomożesz .

**Comment by AroKol78** [comment]
jak dla mnie wygląda to na sprawę dla [FiltersHeroes/PolishAnnoyanceFilters](https://github.com/FiltersHeroes/PolishAnnoyanceFilters)

**Comment by kolor33** [comment]
Ale jak regułę użyć .Próbuje to blokować ale nić nie działa.

**Comment by kolor33** [comment]
Jak nie widzisz wyczyści cookie i zacznij szuka I ci wyskoczy.

https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie/katowice#from404

**Comment by AroKol78** [comment]
nic takiego nie nastąpiło (wyczyściłem ciastka strony,..., zaakceptowałem ciastka strony).
ikona „ubo” na Twoim zrzucie ekranu nic nie pokazuje - u mnie pokazuje 4 przy wyszukiwani.

**Comment by kolor33** [comment]
Pokazuje bo to mam wyłączone .Tu wchodzisz i szukasz.Filtry irytujące też mam.Blokowałem ręcznie ub ale to nic nie daje.

https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie/cala-polska

**Comment by AroKol78** [comment]
niestety nie pomogę - nie widzę u siebie (zbyt egzotyczna przeglądarka/bloker/ustawienia/...)

**Comment by kolor33** [comment]
No dobra ale mówiłeś że Ublock ci blokuje .Możesz podać te reguły które blokuje.

**Comment by AroKol78** [comment]
Serpent52+uBOLegacy
`googletagservices.com/gpt.js` <<
`||doubleclick.net^`
`||optimizely.com^$third-party`
`/?sentry_key=`
`/newrelic.js`
`##.adunitContainer`
`##.adBox`

**Comment by kolor33** [comment]
Dzięki niestety nic to nie daje .Ale dzięki za pomóc.

**Comment by krystian3w** [comment]
Te reklamy to pewnie self-promo.
