### ISSUE TITLE
zachodniopomorska.tv

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20950]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [X] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Comodo Dragon 98.0.4758.102

### Bloker (Blocker)

uBlock Origin 1.41.8

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

reklamy - na głównej i w artykułach, np : https://www.zachodniopomorska.tv/wiadomosci/6916,nowogard-informacja-na-temat-uchodzcow-z-ukrainy

sociale ( u góry )

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by blocker999** [comment]
@MajkiIT resztki po reklamach zostały

**Comment by krystian3w** [comment]
Social będzie wycięty w najbliższym PR, więc kontroluj by resztki lepiej zostały usunięte.

**Comment by krystian3w** [comment]
@xxcriticxx proszę o usunięcie labelu social i przywróceniu "reklama" by majkiit za miesiąc sprawdził jak dociąć.

**Comment by krystian3w** [comment]
Chyba te resztki to po self-promo.
