### ISSUE TITLE
noizz.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2096]
ad block z onet

`http://noizz.pl/lifestyle/youtube-pierwszy-taniec-minsk-mazowiecki/2rfct65?placement=popularne&position=0`

![capture1](https://cloud.githubusercontent.com/assets/15007183/22404260/1c96abe6-e5fb-11e6-8451-ec816f573eac.PNG)

**Comment by MajkiIT** [comment]
Na chwilę obecną u mnie tego nie ma. Sprawdzałem nawet w trybie prywatnym.

**Comment by F4z** [comment]
Ja też tego nie widzę.
Mam tylko puste miejsce po reklamie.
![image](https://cloud.githubusercontent.com/assets/11742596/22404522/aba8514a-e632-11e6-9768-8e57f3e67f0e.png)

Na przykład:
`noizz.pl##.intext-ads-container`

**Comment by xxcriticxx** [comment]
zgadza sie teraz tez tego nie mam moze jutro sie pokaze
