### ISSUE TITLE
centrumdekoracji.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20974]
( po prawo )

**Comment by krystian3w** [comment]
Fanboye nas wyprzedzili, mają:

`.widget_facebook_page_plugin_widget`

---

Proszę w nowym zgłoszeniu opisać jaka popularna lista na tej stronie wymusza generic hide - nie obsługujemy dalej `f(u)ck f(u)ck adblock` ani mu nie zgłaszamy, bo ma to gdzieś.
