### ISSUE TITLE
twojapogoda.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2098]
polopiryna complex 

`http://www.twojapogoda.pl/prognoza?utm_source=geekweek&utm_medium=image&utm_campaign=pixad`

![capture](https://cloud.githubusercontent.com/assets/15007183/22427854/ca5babe6-e6d2-11e6-85dc-fd7de6918b2f.PNG)

**Comment by FadeMind** [comment]
```
||www.twojapogoda.pl/images/box/search/big/polopiryna_complex2.jpg$image
```
