### ISSUE TITLE
agro-hurt.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#20992]
G+ ( button )

**Comment by krystian3w** [comment]
Napisz do nich, że od 2019 już nie działa google+

**Comment by krystian3w** [comment]
Ja widzę link do map google, to niech @hawkeye116477 decyduje gdzie wyciąć, raczej w inne w PAF.

**Comment by hawkeye116477** [comment]
Albo inne albo kontaktowe, jak tam uważacie.

**Comment by krystian3w** [comment]
Jak dla mnie zostaje w inne, nie każdy napisze pod opinią:

- dziękujemy
- przepraszamy

niektórzy mają na odpisywanie `wjyebane`.

**Comment by krystian3w** [comment]
Jej
