### ISSUE TITLE
 Adblock_PL_List/adblock_polska.txt

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#21]
https://github.com/adblockpolska/Adblock_PL_List/blob/master/adblock_polska.txt

twoje poczatki?

**Comment by MajkiIT** [comment]
Nie. Ktoś inny, ale z jakiegoś powodu projekt upadł..

**Comment by xxcriticxx** [comment]
mozna cos stym zrobic? jakos to użyć
