### ISSUE TITLE
wiadomosci.dziennik.pl

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#21025]
Witam da się to jakoś obejść.Widzi mojego ubloka.

wiadomosci.dziennik.pl/swiat/artykuly/8423572,pentagon-amerykanska-ambasada.html

**Comment by krystian3w** [comment]
Sprawdzić filtry na dezaktywację AdQuesto:

`dziennik.pl##+js(abort-on-property-write.js, adquestoConfig)`

potem 

`dziennik.pl##+js(abort-current-inline-script.js, parseInt, adblock)`


---

Jak oba nie pomogą to aktywuj w uBo listę "AdGuard Base" (rozwijamy sekcję "Reklamy").

**Comment by kolor33** [comment]
To działa ta reguła .
dziennik.pl##+js(abort-on-property-write.js, adquestoConfig)

Krystian a umiał byś coś zrobić z tym .???
https://github.com/MajkiIT/polish-ads-filter/issues/20958

**Comment by AroKol78** [comment]
**poza tematem**
> Na XP z Serpent/MyPal68 może nie da się odpalić AdQuesto.

podejrzewam, że to samo na najnowszym PM31 (Serpent52(UXP20220510))
```
Timestamp: 2022-05-24 16:11:54
Error: SyntaxError: bad method definition
Source File: https://ocdn.eu/dziennik/infor/adquestoConfig/adquestoConfig_v3.js
Line: 3, Column: 4
Source Code:
    useTcf = true; 
```

**Comment by kolor33** [comment]
Dzięki Krystian .Widzę że masz Pojecie o tym .Szacunek .

**Comment by xxcriticxx** [comment]
co to za nowe przegladarki?

**Comment by krystian3w** [comment]
Dla Windows XP i opcjonalnie Visty.

Raczej starocie, bo używają kodu Firefox 68 i PaleMoon (uznawany za vintage/legacy browser).

**Comment by xxcriticxx** [comment]
@krystian3w trzeba zakonczyc uzywanie XP i przerzucic sie na jakies ubuntu

**Comment by krystian3w** [comment]
Niby naprawione:

https://github.com/olegwukr/polish-privacy-filters/commit/fc363cd3115ca0c78d8ee60143bf1b8c2a29152e
