### ISSUE TITLE
Skrypty śledzące Koalametrics (śledzenie geolokalizacji + profilowanie behawioralne) w telefonach Android.

### ISSUE THREAD

**Issue by CelularBat** [MajkiIT/polish-ads-filter#21022]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [X] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [X] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
reports.koalametrics.com
```

### System operacyjny (Operating system)

Android

### Przeglądarka internetowa (Web browser)

filtr DNS

### Bloker (Blocker)

nextDNS.io

### Używane listy filtrów (Used filter lists)

1. github.com/MajkiIT/polish-ads-filter
2. Lista blokowania reklam i elementów śledzących od NextDNS
3. AdGuard DNS filter
4. EasyList
5. ...Używam wszystkich dostępnych filtrów dostępnych domyślnie w konfiguracji nextDNS.io (żaden z nich nie zablokował żądania)

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

W moim telefonie z Android przeszedłem na DNS od nextDNS.io Usługa oferuje w pełni konfiguralny osobisty DNS, umożliwia filtrowanie żądań do DNS wg. list podobnie jak Adblock ( ten zestaw filstrów jest dostępny w domyślnej konfiguracji), umożliwia też podgląd w logi. Podłączyłem do niego mój telefon i zostawiłęm sam sobie. Po godzinie zajrzałem w logi - z zaciekawieniem jakie żądania do DNS wysyłają aplikacje na moim telefonie gdy leży sobie odłogiem.
Odkryłem reports.koalametrics.com ,którego nie zablokował żaden filtr. Nie wiem, która aplikacja z zainstalowanych na telefonie ma wbudowaną tą wtyczkę. Mały research w internecie i to wygląda na hardcorową aplikację śledzącą:
https://www.justtag.com/images/Koala_Metrics_PL.pdf

Śledzi lokalizację użytkownika poprzez mapowanie dostępnych punktów Wifi. Buduje profile behawioralne. Chwalą się w swoim pdfie analizowaniem danych klientów dla sklepów.

Pomyślałem, że skoro ten zestaw filtrów służy również do blokowania na poziomie DNS, to może warto dodać, zwłaszcza, że to polska firma. 

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Lista social nie wycina telemetrii społecznościowej (https://filterlists.com/lists/polish-social-filters).

Raczej musisz prosić by dodał to Oleg do PolishPrivacyFilters: https://filterlists.com/lists/polish-privacy-filters (fyi @olegwukr).

Jak on odrzuci to zostaje EasyPrivacy i AdGuard Tracking Protection lub ich lista DNS:

https://filterlists.com/lists/easyprivacy
https://filterlists.com/lists/adguard-tracking-protection-filter-adguard-for-chromium
https://filterlists.com/lists/adguard-dns-filter

**Comment by hawkeye116477** [comment]
Tyle, że zgłaszający mówi tutaj o hosts, a tam nie ma listy Social (co jest zapewne pomyłką) i tak samo nie ma listy olega. Za to Majki chyba dodaje coś tam z „śledzących” do tej swojej listy hosts.

**Comment by krystian3w** [comment]
NextDNS umie przerobić listę Olega na Hosts (jedynie wada w logice NextDNS jest kopiowanie domen jak mają filtorwanie `$3p` lub `$popup` i nie chcą się z tego wycofać), jak się zgłosi to może go dodadzą.

**Comment by krystian3w** [comment]
@xxcriticxx można usunąć tag social, nie będziemy blokować w liscie social trackingu, więc temat zostaje dla MajkiIT i Olegawukr (zgłoszenie swojego projektu do konwersji na listę DNS automatycznym skryptem NextDNS jak to zrobili z listą EasyList/EasyPrivacy - one oficjalnego formatu hosts nie mają i każdy jest fanowski).
