### ISSUE TITLE
Filter breaks some Czech sites

### ISSUE THREAD

**Issue by jaroslavlibal** [MajkiIT/polish-ads-filter#2108]
Hello,

thanks for the plugin, works well on Polish sites; however it also breaks some Czech ones (most of them are from from the iinfo.cz corporation - eg. digizone.cz - and the result is just a white page.

Example:
http://www.digizone.cz/clanky/vlada-dnes-schvalila-dve-ze-tri-klicovych-legislativnich-zmen-pro-prechod-na-dvb-t2/

**Comment by MajkiIT** [comment]
@jaroslavlibal Thanks. I will fix it.
