### ISSUE TITLE
exsites.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#21098]
Wykryliśmy, że korzystasz z wtyczki typu AdBlock.
Część funkcji serwisu może nie działać dla Ciebie poprawnie. Zalecamy wyłączenie wtyczki, aby móc w pełni korzystać z serwisu. Sprawdź również czy antywirus lub VPN (jeżeli używasz) nie blokują reklam.
Po wyłączeniu wtyczki typu Adblock, odśwież stronę aby wprowadzone zmiany zadziałały.

![Capture](https://user-images.githubusercontent.com/15007183/174299113-9871e30b-8ca8-49c6-9443-89d80b8b25ca.PNG)

**Comment by krystian3w** [comment]
Jak Oleg dalej walczy to trzeba zgłosić do uAssets i AdGuard,  bo jak wybuchnie 3 wojna światowa to może i strona wygaśnie, bo nie opłacą hostingu i domeny.

**Comment by krystian3w** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/fc363cd3115ca0c78d8ee60143bf1b8c2a29152e - test, jak zniknęło to można zamknąć.

**Comment by xxcriticxx** [comment]
@krystian3w wszystko dziala tylko message na top trzeba schowac

**Comment by krystian3w** [comment]
Czyli fix Olega nie działa lub strona wymaga poprawek raz dziennie.

Tego nie można ukryć jak resztki reklamowej, bo strona próbuje w kółko dokleić na nowo "wykryliśmy AdBlock" - co po jakimś czasie zamulić może słabsze komputery jakich nie ulepszysz w ramach wolontariatu.

Jak masz inny komunikat np. "nowy cookies" to ja go nie widzę, wymuś wtedy aktualizację listy I don't care about cookies.
