### ISSUE TITLE
rmfon.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2110]
30 sec reklama 

http://www.rmfon.pl/play,5#utm_source=rmf24.pl&utm_medium=click&utm_content=head&utm_campaign=megaplayer

![capture](https://cloud.githubusercontent.com/assets/15007183/22524286/a2f1b5a4-e890-11e6-92ff-6d48c1ce2975.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx nadal to masz?

**Comment by xxcriticxx** [comment]
@MajkiIT oczywiscie za kazdym razem 

![capture](https://cloud.githubusercontent.com/assets/15007183/22590958/0d5d66f4-e9e0-11e6-9991-54d5328bac13.PNG)

**Comment by MajkiIT** [comment]
Ok, już mam 2 komp. Sprawdź proszę to: `||nazwa.pl/video/*.mp4$media,domain=www.rmfon.pl`

**Comment by xxcriticxx** [comment]
@MajkiIT  regula jest good thx!
