### ISSUE TITLE
ads.reddit.com

### ISSUE THREAD

**Issue by kolor33** [MajkiIT/polish-ads-filter#21109]
Witam jest możliwe co z tym zrobić. Strona widzi ubloka.

ds.reddit.com

**Comment by xxcriticxx** [comment]
https://github.com/spikecodes/libreddit

**Comment by kolor33** [comment]
Dzięki

**Comment by krystian3w** [comment]
Albo zrób test z wyłączonymi polskimi listami - wtedy uAssets musi naprawić https://github.com/uBlockOrigin/uAssets/issues/new/choose

**Comment by krystian3w** [comment]
Subdomena ads.reddit.com naprawiona w: https://github.com/uBlockOrigin/uAssets/commit/f82674c1e278cd262018cd7f7d99736da7798368

Reklama premium w prawym rogu to reklama typu self-promo (wewnętrzna).

Jak możesz to nie używaj domeny ds. tylko:

Old.reddit.com
Pl.reddit.com

**Comment by kolor33** [comment]
krystian3w że tak powiem Batman jesteś .Masz wiedze szacunek .zrobiłem tylko update filtrów i działa .he he

**Comment by krystian3w** [comment]
Oleg niby wykrył, że strona wymaga filtru kosmetycznego: https://github.com/olegwukr/polish-privacy-filters/commit/fc363cd3115ca0c78d8ee60143bf1b8c2a29152e
