### ISSUE TITLE
Poczta o2 - brak przycisku profilu (wylogowania) z 1login od WP

### ISSUE THREAD

**Issue by mkczyk** [MajkiIT/polish-ads-filter#21110]
### Zrzut ekranu 

Bez filtra:

![image](https://user-images.githubusercontent.com/11051213/175814101-80ac9a72-7c40-4033-b16d-6794a8f06817.png)

Z filtrem: 

![image](https://user-images.githubusercontent.com/11051213/175814116-fae6f1ca-9416-4fda-b3b5-22e54834c2fc.png)

### Link bezpośredni 

https://poczta.o2.pl/

### Co trzeba zrobić, aby pojawił się błąd?
1. Założyć konto na Poczta o2.
2. Włączyć 1login od WP (na zwykłym koncie przycisk jest).
3. Zalogować się. Nie ma przycisku profilu (a więc np. nie da się wylogować).

**Listy filtrów:**
1. POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda

(jestem pewny, że dotyczy tylko tej listy, bo po jej wyłączeniu przycisk wraca)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Pozycja w DOM: 

<details><summary>Screen</summary>

![image](https://user-images.githubusercontent.com/11051213/175814662-ea02ae72-4f5e-49a5-9f08-6d08ab32a8ad.png)

</details>

W trybie zaznaczania elementów: `##.styles-module_Button__miUzP.olw__button`

Zrzut z rejestratora (zablokowane, dom):
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +0 | ##dd-holder[slot^="BOX_LEFT_"] |  | poczta.o2.pl |  | dom | `https://poczta.o2.pl/w/#/mails/?label=1` |
| +0 | ##dd-holder[slot="DOUBLE_BILLBOARD"] |  | poczta.o2.pl |  | dom | `https://poczta.o2.pl/w/#/mails/?label=1` |
| +0 | ##html:style(overflow: visible!important; position: unset!important;) |  | poczta.o2.pl |  | dom | `https://poczta.o2.pl/w/#/mails/?label=1` |
| +0 | ##body:style(overflow: visible!important; position: unset!important;) |  | poczta.o2.pl |  | dom | `https://poczta.o2.pl/w/#/mails/?label=1` |
| +0 | ##body [class]:style(filter: none !important;) |  | poczta.o2.pl |  | dom | `https://poczta.o2.pl/w/#/mails/?label=1` |
| +0 | ##body > [class]:not(.settings--user):style(filter: none!important;) |  | poczta.o2.pl |  | dom | `https://poczta.o2.pl/w/#/mails/?label=1` |
</details>

**Comment by AroKol78** [comment]
Duplicate of #21075

**Comment by krystian3w** [comment]
Naprawione w uAssets.
