### ISSUE TITLE
z archiwum Antyweb-a

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2111]
Aby przeczytać archiwalne teksty z Antyweba należy zapisać się do newslettera.

Więc postanowiłem podzielić się z Wami filtremi odblokowującym :

```
http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js?ver=4.7

http://antyweb.pl/wp-content/themes/antyweb.autentika/js/main.js?ver=3.1
```

Jeśli chcecie to dodajcie je proszę.

**Comment by F4z** [comment]
Nie psuje Ci to działania strony?
U mnie po zablokowaniu tych skryptów nie działa wyszukiwarka na stronie i niektóre elementy nie do końca poprawnie się wyświetlają.

Może coś takiego (o ile też czegoś nie psuje i prawidłowo działa)?
`antyweb.pl##.newsletter-box`
`antyweb.pl##article.newsletter-block:style(filter: none !important; max-height: none !important; user-select: auto !important; border-top: none !important;)`

**Comment by blocker999** [comment]
@F4z 

Psuje to główną strone antyweba chociaż te filtry są ok, lecz proszę o pomoc tzn chodzi mi o to by tak je przerobić by nie gryzły się z główną.

Te filtry co podałeś wcześniej to są do czego innego bo nic niepomagają a mi chodzi konkretnie o archiwalne całe artykuły a nie blokade, np:
![anty](https://cloud.githubusercontent.com/assets/23176832/22569934/b3282e58-e999-11e6-8e21-58e69ad04ca1.jpg)

**Comment by F4z** [comment]
@blocker999 u mnie po dodaniu tych reguł, które podałem wyświetla się normalnie tutaj artykuł - `http://antyweb.pl/przepraszam-cie-facebooku/`
bez tych reguł miałem tak samo jak na obrazku, który wstawiłeś.

Możesz podać link, gdzie u Ciebie nie działa?

**Comment by blocker999** [comment]
No dobra artykuły archiwalne działają ok tylko niestety te filtry blokują strone główną, więc trzeba coś jeszcze pokombinować by nieblokowało to " Antyweb.pl "

Na tym linku co podałeś jest to samo, co na tym:

http://antyweb.pl/nowa-odslona-poczty-na-o2-pl-i-wp-pl/

**Comment by F4z** [comment]
Rozumiem, że piszesz o tych filtrach, które podałeś.
`http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js?ver=4.7`
`http://antyweb.pl/wp-content/themes/antyweb.autentika/js/main.js?ver=3.1`
Jeśli tak, to one nie tylko sprawiają nieprawidłowe działanie strony głównej, ale po ich dodaniu nie działa również wyszukiwarka.
Jeśli najedzie się myszką na przycisk "Tematy" albo "Felietony" na belce, na samej górze, to nieprawidłowo się wyświetla.
W momencie kiedy jakiś artykuł zawiera obrazek i się w niego kliknie to zamiast wyświetlić go w "galerii", to przechodzi bezpośrednio do tego obrazka.
Jak przejdzie się do jakiegoś artykułu, to po przewinięciu na dół powinny się wyświetlać kolejne, a tak się nie dzieje.
Ogólnie to psuje działanie strony, w takim przypadku lepiej podać jakiegoś tymczasowego emaila, niż blokować te skrypty.


Nie wiem dlaczego u Ciebie to nie działa, ale u mnie po dodaniu tej reguły (działa w uBlocku i Adguardzie):
`antyweb.pl##article.newsletter-block:style(filter: none !important; max-height: none !important; user-select: auto !important; border-top: none !important;)`
wyświetla się normalnie artykuł.
<details><summary>Obrazek</summary>

![antyweb](https://cloud.githubusercontent.com/assets/11742596/22595971/e63c761a-ea29-11e6-85bc-32d77e0af813.png)

</details>

**Comment by MajkiIT** [comment]
@F4z u mnie też jest ok... testowane na 5 kompach. Dzięki 

@blocker999 może tryb prywatny?
