### ISSUE TITLE
alltube.tv | alltube.pl 

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#21121]
https://github.com/MajkiIT/polish-ads-filter/blob/ef68baeef00c1353a8ae3ff780346e66f71d663e/polish-adblock-filters/adblock.txt#L4992

obie domeny zbanowane rękami: https://www.alliance4creativity.com/watch-it-legally/

---

Podobny ban dostały w 2019: openload.co, streamango.com, rapidvideo.com (nie udało się go odwołać by nazwa witryny trafiła do puli wolnych).

**Comment by krystian3w** [comment]
Chodzi by zbędne filtry wywalić (całe linie lub nazwy domen z pliku)...

**Comment by xxcriticxx** [comment]
@krystian3w comprende
