### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2113]
ad block 

![capture](https://cloud.githubusercontent.com/assets/15007183/22547563/3967d804-e910-11e6-99d2-1e07e8257d7a.PNG)

**Comment by MajkiIT** [comment]
Zobaczymy czy się zmieni.

`www.elektroda.pl##.bb096870`
`www.elektroda.pl###eb88a7fd7fa2f20fffeae422`

**Comment by mathew85** [comment]
Reklamy również przywrócili.

**Comment by mathew85** [comment]
Kolejna zmiana i reklamy wróciły.

**Comment by MajkiIT** [comment]
@mathew85 dzięki. Coś podziałamy.
@F4z masz jakiś pomysł?

**Comment by xxcriticxx** [comment]
to sie moze przyda `REKLAMA NA STRONIE GŁÓWNEJ`

```
http://www.elektroda.pl/rtvforum/companyabout.php
```

**Comment by F4z** [comment]
Może tak?
`elektroda.pl##.row > div[id][style="display: block;"]`

`elektroda.pl##.row > .the-content.col-md-8 > [class] > form`
`elektroda.pl##.row > .the-content.col-md-8 > [class] > div[style]`
`elektroda.pl##.row > .the-content.col-md-8 > [class] > [rel="nofollow"]`

`elektroda.pl##ul.the-list > li[class$=" clearfix"]`
`elektroda.pl##div.the-post-list > ul > li[class$=" clearfix"]`
`elektroda.pl##div.forumlist-wrap.clearfix > div[class$=" clearfix"]:not([style]):not([id])`

<details><summary>Obrazek</summary>

![elektroda1](https://cloud.githubusercontent.com/assets/11742596/22710116/71d021fe-ed7c-11e6-82ce-cf2b638fdb24.JPG)

</details>
<br>

Pierwsza reguła żeby ukryć komunikat o adblocku.
Druga, trzecia i czwarta żeby ukryć reklamy na górze strony.
Piąta żeby ukryć reklamę i pozostałość po reklamach na stronie głównej, na liście po prawej stronie.
Szósta żeby ukryć pozostałość po reklamach na stronie głównej przy tych wpisach "Wszystkie DIY".
Siódma żeby ukryć pozostałość po reklamach na forum - `http://www.elektroda.pl/rtvforum/forums.html`
Te dwie ostatnie to takie opcjonalne.

Jeszcze artykuły sponsorowane, których wcześniej nie zauważyłem:
`elektroda.pl##.row > .the-content.col-md-8 > .sponsored`

Ogólnie to przydałoby się sprawdzić, czy któraś reguła nie ukrywa za dużo, bo mogłem coś przeoczyć.
Nie sprawdzałem też tego przy starym wyglądzie. Potem założę konto i zobaczę.

**Comment by gulson** [comment]
Oj Panowie, Panowie, przecież ja jutro znowu wszystko pozmieniam :) Nie szkoda Wam czasu na tą zabawę? Czy Wam tak naprawdę przeszkadzają reklamy, które ani nie wyskakują, a nie grają? Z czego serwis ma się utrzymać? A te reguły to raczej pół serwisu załatwią, więc będę musiał postawić komunikat, kto zepsuł serwis :)  Ostatnio tak zepsuliście serwis, że żaden button się nie wyświetlał do pisania postów, bo zablokowaliście całą klasą button.

**Comment by xxcriticxx** [comment]
@gulson niema problemu jutro bendzie jutro :)

@gulson mozemy sie dogadac podaj jakies propozycje

**Comment by gulson** [comment]
Nie za bardzo rozumiem, co oznacza, że możemy się dogadać?

**Comment by xxcriticxx** [comment]
Unas wszystko narazie jest za darmo :)

@gulson zablokujemy ad blocka I reklamy zostawimy czy bendzie ok?

Oczywiście @majkiIT musi zatwierdzić to jego projekt

**Comment by gulson** [comment]
Na razie powiadasz bezpłatne :) A czy to trochę nie dziwne, w sensie czy jest to na pewno etyczne, że decydujecie o tym, co ma się wyświetlać czy nie wyświetlać w serwisie? Wiesz teraz informację o adblock zablokujecie, bo Wam się nie podoba (zrozumiałe), ale może za jakiś czas coś Wam się kolejnego nie spodoba? Jaką mam mieć pewność?

**Comment by xxcriticxx** [comment]
Szukamy java programera może się przydasz zamian się odblokuje ciebie

@gulson wpadniesz jutro jak bendzie @majkit i się dogadamy co ty nato?

**Comment by gulson** [comment]
OK niech majkit zabierze głos, ja jestem zawsze otwarty na współpracę.

**Comment by xxcriticxx** [comment]
Thank you miło się gadało :)

**Comment by MajkiIT** [comment]
@gulson No jak zmienisz to zmienisz, przecież koszuli ze złości nie podrę :) Co do etyki to jak widzisz staramy się tak tworzyć filtry aby przy wejściu na stronę nie dostać zeza od ilości reklam lub wyskakujących okien. Co do błędnie blokowanych elementów staramy się na bieżąco poprawiać i nie udajemy Panów sytuacji. Odezwij się proszę na maila errors@certyficate.it to machniemy offtopic.

**Comment by gulson** [comment]
Wyskakujących reklam w ogóle nie ma. Dodatkowo w momencie jak używasz Adblocka i domyślnych filtrów na elektrodzie nie widzisz już 90% reklam. To, co zostaje to drobnica, nie przeszkadzająca ani w żaden sposób nie denerwująca. Kolejna sprawa i piszę to w imieniu innych osób prowadzących strony czy blogi, czy nie wydaje się to trochę dziwne, aby to właściciel serwisu musiał pisać i błagać o odblokowanie klasy button, bo userom przestały się wyświetlać wszystkie przyciski? Dlaczego to właściciel serwisu ma ponosić za to odpowiedzialność? A ponosi, bo userzy najpierw do niego piszą, że coś nie działa, że strona jest zepsuta, czy piszą, że ktoś nie umie robić serwisu. Tak to przykro wygląda.

**Comment by gulson** [comment]
Na pewno będę zmniejszać ilość requestów. Jednak te reklamy, które blokujecie pochodzą z własnego serwera i w niczym nie przeszkadzają, nie zwiększają ilość requestów. Proszę jednak nie porównuj strony benefitsystem czy jakiekolwiek ecommerce, która utrzymuje się z własnej sprzedaży a nie reklam. Porównanie jest całkowicie błędne, bo na stronach ecommerce nie trzeba i nawet nie jest wskazanie zamieszczanie reklam. A jak wiesz już samo wstawienie reklam zewnętrznych powoduje wzrost requestów, ale te są wycinane przez AdBlock filtry domyślne i nie potrzeby dodatkowego filtrowania.

Odnośnie wyskakujących okien dobrze by było coś z tym zrobić na Twojej stronie:
![zrzut ekranu z 2017-02-08 12-58-53](https://cloud.githubusercontent.com/assets/6297081/22823320/5a7cddae-ef83-11e6-9836-7492545f3cf7.png)

Jest to bardzo denerwujące, jak takie coś atakuje na stronie. 

Oczywiście, że każdy ma wybór, ale niestety działacie na szkodę portalów, a niektóre Wasze zaawansowane działania można niestety porównać do łamania oprogramowania, co jest prawnie zabronione i w końcu jakiś portal horyzontalny, który płaci ogromne pieniądze za treści, może się Wam do skóry dobrać. To są prawie jak kiedyś cracki do oprogramowania tylko teraz do oprogramowania na stronach np VOD, dobra papuga byłaby w stanie to udowodnić, w naszym kraju wszystko możliwe. Tak pod rozwagę aby nie przeginać w żadnym kierunku :)

**Comment by F4z** [comment]
> Oczywiście, że każdy ma wybór, ale niestety działacie na szkodę portalów w szczególności tych co płacą za wytworzenie treści.

Dokładnie, każdy ma wybór i nikt nikogo nie zmusza do używania "Adblocka". Jak ktoś będzie chciał wspierać dany portal, to przecież zawsze może wyłączyć rozszerzenie/program do blokowania reklam, przekazać darowiznę, czy w jakikolwiek inny możliwy sposób go wspomóc. Nie widzę tutaj problemu.
Jeśli ktoś korzysta z Adblocka czy podobnych, to znaczy, że reklam widzieć nie chce, nawet tych najmniejszych. A jeśli chce zablokować tylko te najbardziej irytujące, to zawsze może włączyć opcję "Zezwalaj na nienatrętne reklamy".
Jeśli nie my, to i tak ktoś inny zablokuje te reklamy.
Dlaczego nie czepiasz się twórców EasyList i nie piszesz do nich, że blokują aż 90% reklam na Twojej stronie internetowej, tylko nas, jak chcemy "zablokować" te pozostałe 10%?

>  Niektóre Wasze dość mocne dla nich działania można niestety porównać do łamania oprogramowania i w końcu jakiś portal horyzontalny, który płaci ogromne pieniądze za treści, może się Wam do skóry dobrać. [...] I nawet jak nic nie zrobią, bo w Niemczech już próbowali, to Was niepotrzebnie przegonią i stracicie czas. Na razie jest spokój bo może nawet nie wiedzą o Waszym istnieniu czy nie wiedzą w ogóle jak to działa i jak dochodzi do rozpowszechniania i kto to rozpowszechnia.

Możesz wskazać konkretnie, o które "dość mocne działania" Ci chodzi?
Mocno wyolbrzymiasz (straszysz?), w Niemczech pozwali Eyeo, czyli firmę, która odpowiada za Adblock Plusa i z tego co wiem, to chodziło o **opłaty** związane z dodawaniem "nienachalnych reklam" do listy (wyjątków), a nie o same blokowanie reklam.
Nikt nie pozwał twórców list, bo trudno ich pozwać, same listy bez odpowiednich narzędzi są bezużyteczne.

Odnośnie całej reszty, bez adblocków mogłoby być dokładnie tak samo, może gorzej, może lepiej, kto wie?
Jest to zwykłe gdybanie i nie widzę sensu, żeby to dalej kontynuować.
Życzę więcej optymizmu :)
