### ISSUE TITLE
Zasubskrybowane listy nie aktualizują się.

### ISSUE THREAD

**Issue by zuku81** [MajkiIT/polish-ads-filter#21134]
Witam,
wszystkie zasubskrybowane listy lądują w zakładce "Własne" i wszystkie mają żółty wykrzyknik z napisem nieaktualne.
Przycisk "Aktualizuj" nic nie aktualizuje cały czas ten żółty wykrzyknij jest.

![ublock błąd](https://user-images.githubusercontent.com/23002928/179451947-62e646a2-4f7f-44b3-988c-76ebab242977.jpg)
Chrome 103.0.5060.114
Ublock Origin 1.43.0

**Comment by krystian3w** [comment]
Tak.

To mi wygląda na jakąś awarię serwera lub łącza - @gwarser może i pol-0 i pol-2 powinno mieć linki do mirrorów (delay raczej nie sprawi, że jakiś hotfix się nie uruchom z racji lagu na np. JSdeliver).

**Comment by gwarser** [comment]
Trochę dziwnie to wygląda, przy błędzie połączenia chyba czerwone ogniwo wyskakuje. Co jest w dymku po najechaniu na wykrzyknik?

**Comment by zuku81** [comment]
wywaliłem i zainstalowałem ponownie Ublocka listy się dodały, tylko jedna teraz ma przerwany spinacz, i ma tak cały czas już dwa dni:
![ublock błąd](https://user-images.githubusercontent.com/23002928/179730623-cb388faf-3531-48f5-bb21-e577e2b7a437.jpg)

**Comment by krystian3w** [comment]
URL wygląda na przestarzały, Curben nie radzi chyba sobie z popularnością listy w uBo I AdGuaed.

Najnowszy leci tak:

`https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-online.txt` (pisane z rąsi, mogą być literówki i autokaleki).

Prawdopodobnie nowszy masz w sekcji "domeny ze złośliwym oprogramowaniem" i tam  "Online Malicious URL blocklist.

Nazwana pechowo, to może dlatego dezaktuwowałes w obawie przed tym  by lista ułatwiała infekowanie komputerów/telefonów (sic!).
