### ISSUE TITLE
rynek-kolejowy.pl

### ISSUE THREAD

**Issue by ireun** [MajkiIT/polish-ads-filter#21130]
### Zrzut ekranu 
![image](https://user-images.githubusercontent.com/695818/179323727-59900afc-303a-4c26-a4f8-8b670c9ad09c.png)

### Link bezpośredni 
https://www.rynek-kolejowy.pl/

### Moja konfiguracja 
**Przeglądarka internetowa:** Chrome

**Rozszerzenia i skrypty:** Ublock Origin

**Listy filtrów:** 
![image](https://user-images.githubusercontent.com/695818/179323763-5005cd60-bb7e-42fc-9a85-32a7142a9b46.png)

**Comment by krystian3w** [comment]
@olegwukr
