### ISSUE TITLE
gry-online.pl

### ISSUE THREAD

**Issue by przemo20** [MajkiIT/polish-ads-filter#21152]
### Zrzut ekranu 

![Screenshot 2022-07-25 at 16-20-03 Seksizm w CS GO wciąż problemem; dziewczyny odchodzą z gry przez przykre doświadczenia GR](https://user-images.githubusercontent.com/22180480/180799940-687058a9-7b07-4f49-84da-903d6ff7d2ac.png)

### Link bezpośredni 

https://www.gry-online.pl/newsroom/csgo-nieprzyjazne-dla-kobiet-streamerka-pokazala-problem/ze226bb

### Co trzeba zrobić, aby pojawił się błąd?
1. Odwiedzić wyżej wymienioną stronę i przewinąć ją w dół

### Moja konfiguracja 

**Listy filtrów:** 
1. uBlock filters
2. uBlock filters – Badware risks
3. uBlock filters – Privacy
4. uBlock filters – Quick fixes
5. uBlock filters – Resource abuse
6. uBlock filters – Unbreak
7. EasyList
8. EasyPrivacy
9. Online Malicious URL Blocklist
10. Peter Lowe’s Ad and tracking server list
11. POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
12. POL: Oficjalne polskie filtry przeciwko alertom o Adblocku

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Po przewinięciu strony w dół karta przeglądarki zaczyna odtwarzać dźwięk/wideo, pomimo że jest ono ukryte (czyli trzeba by było w całości zablokować tę osadzoną treść, a nie tylko ukrywać, albo po prostu ją odblokować).
Winowajcą jest filtr `gry-online.pl##div > iframe[style^="border:"]:not([src])`:
![obraz](https://user-images.githubusercontent.com/22180480/180801926-dbf14045-a9d4-4649-bfe8-5842c4c56661.png)

Po dodaniu `gry-online.pl#@#div > iframe[style^="border:"]:not([src])` do moich filtrów normalnie wyświetla się embed z reddita:
![Screenshot 2022-07-25 at 16-20-43 Seksizm w CS GO wciąż problemem; dziewczyny odchodzą z gry przez przykre doświadczenia GR](https://user-images.githubusercontent.com/22180480/180801958-3f6652eb-bfb2-4a8e-8dc4-a42ac906130a.png)

**Comment by krystian3w** [comment]
Widać w ramkach z obramowniem są reklamy z losowym URL i domeną, stąd lepiej ukrywać je było komsetycznie.
