### ISSUE TITLE
cdax.tv

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#2116]
Reklama

![image](https://cloud.githubusercontent.com/assets/11385099/22563226/0e35e160-e980-11e6-904a-fa5935241c4c.png)

**Comment by MajkiIT** [comment]
`cdax.tv##.text-center`

**Comment by F4z** [comment]
@MajkiIT ale ta reguła chyba zblokuje odtwarzacz i inne elementy, na przykład tu - `https://cdax.tv/droga-bolu`

**Comment by MajkiIT** [comment]
@F4z Dzięki 

No to standard
`cdax.tv##a[href^="https://anon.to/"]`

**Comment by mathew85** [comment]
Dodali AdBlocka.

**Comment by xxcriticxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/15007183/22609153/0b5ffd0a-ea2e-11e6-9877-e73a444a32cc.PNG)

**Comment by F4z** [comment]
`@@||cdax.tv/js/ads.js$script`

**Comment by mathew85** [comment]
Hej. Czy u Was może też się tak dzieje, że jak odtwarzacie jakiś film na stronie w odtwarzaczu z openload to po kilku przewinięciach wyskakuje error?

![image](https://cloud.githubusercontent.com/assets/11385099/22620758/e6415e7a-eb12-11e6-8758-1a00ef6f9b72.png)

Dodatkowo mam dodane reguły z EasyList:
```
||openload.co/assets/js/license.
||openload.co/assets/js/script.
@@|https://*.club/*.js|$script,domain=openload.co
```

**Comment by MajkiIT** [comment]
U mnie jest Ok. Jutro zerkne w biurze na reszcie kompów.

**Comment by mathew85** [comment]
Reklama wróciła:

![image](https://cloud.githubusercontent.com/assets/11385099/22660240/08cc2224-eca1-11e6-9326-fd434532b22f.png)

**Comment by MajkiIT** [comment]
@mathew85 zerknę później, bo obecnie wywaliło im bazę 

`Database connection could not be established.`

**Comment by F4z** [comment]
Może tak?
`cdax.tv##.container > .row > .text-center.col-sm-12 > a[href]`

**Comment by MajkiIT** [comment]
@F4z Dzięki

**Comment by xxcriticxx** [comment]
naciskajac search wyskakuja nowe cuda

`https://ext.searchincognito.com/pads/redirect?implementation_id=pads-alone&subid2=8036e1b6-b14b-4006-bbde-53161df37992&cid=wA7QQ372OJ0CG4431RK28DNO&vlmtrk=true`

![capture](https://cloud.githubusercontent.com/assets/15007183/22711294/9fb69252-ed4e-11e6-8c8b-5b8edf385333.PNG)

**Comment by xxcriticxx** [comment]
podalem na easylist forum

**Comment by xxcriticxx** [comment]
from easylist please test

```
|https://$script,third-party,domain=cdax.tv
@@||code.jquery.com^$domain=cdax.tv
@@||cdax.tv/js/ads.js
```

**Comment by mathew85** [comment]
Zmienili chyba odtwarzacz. Inna sprawa, że strona bardzo wolno się ładuje.
Na nowym odtwarzaczu jest popup, żeby podać nr telefonu.
`
tps://cdax.tv/wielki-mur`


![image](https://cloud.githubusercontent.com/assets/11385099/24590141/867fa020-17e8-11e7-9fc2-4b14975bb6c9.png)

Pytanie czy da się tego pozbyć i czy to odblokuje film, bo u mnie odtwarzanie nie działa.
