### ISSUE TITLE
gralandia.tv

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2118]
Nie pokazuje się odtwarzacz - `http://www.gralandia.tv/bajka/10970-LoliRock:-Sezon-2-Odcinek-4-Super-slodki-kociak.html`

Powinno wystarczyć:
`gralandia.tv#@##ad_content`

**Comment by xxcriticxx** [comment]
Uwaga! Jeśli poniżej nie widzisz bajki, musisz wyłączyć program blokujący reklamy typu Adblock i inne. Po wyłączeniu Adblocka odśwież stronę!

**Comment by MajkiIT** [comment]
@F4z Dzięki
