### ISSUE TITLE
centrum-dramy.pl

### ISSUE THREAD

**Issue by OtakuPL** [MajkiIT/polish-ads-filter#21228]
### Zrzut ekranu 
![image](https://user-images.githubusercontent.com/12618580/184914884-d8b0d310-2f94-405f-95e8-7440a1b8ba7f.png)

### Link bezpośredni 
[https://centrum-dramy.pl/my-little-bride/](https://centrum-dramy.pl/my-little-bride/)

### Co trzeba zrobić, aby pojawił się błąd?
1.  Nie wyświetla playera, nakładka na reklamę chyba buguje się z adblock

### Moja konfiguracja 

**Przeglądarka internetowa:** 
Chrome Wersja 104.0.5112.81 (Oficjalna wersja) (64-bitowa)
**Rozszerzenia i skrypty:** 

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Proszę o naprawę

**Comment by krystian3w** [comment]
Klikanie w zamknij naprawia player.

**Comment by krystian3w** [comment]
Do testowania:

`centrum-dramy.pl##.video-content #overplay`

Jak zadziała w trybie incognito. Jak nie to trzeba skryptlet/przekierowanie neutralizujące lub jakieś dopuszczenia.

**Comment by OtakuPL** [comment]
Z adblock jest opcja "zamknij'
[image: image.png]
po wciśnięciu:
[image: image.png]
Nadal nic, możliwe że adblock blokuje domene harajuku.pl która wyświetla
ten odtwarzacz.
Z Incognito działa dobrze
[image: image.png]
Proszę o naprawę.
Dziękuję

wt., 23 sie 2022 o 19:29 krystian3w ***@***.***> napisał(a):

**Comment by garry-ut99** [comment]
Wredny losowy przypadek podobny do https://github.com/uBlockOrigin/uAssets/issues/14477, czyli dwie osobne przyczyny problemu (w tym jedna losowa):
- pierwsza przyczyna leży po stronie strony (btw. masło maślane) - nawet z wyłączonym uBO film czasem się nie ładuje
- drugą przyczyną mogą być niektóre filtry, u mnie powodował to filtr z listy `NoCoin Filter List`, tu zgłosiłęm błąd: , ale na domyślnych listach film działa, więc przypadek u ciebie to prawdopodobnie ten pierwszy (po stronie strony)

**Comment by OtakuPL** [comment]
Strona działa prawidłowo, sprawdzałem z wielu przeglądarek, zawsze się player ładuje bo korzystam z niej kilka lat. Wiele osób mi zgłasza ten błąd bo jestem tam w moderacji.
Tylko z adblock nie działa, scriptów na kryptowaluty miner też nigdy nie miała tak samo dOmena z playerem harajuku.pl

Bardzo proszę o naprawę 😅
Zależy mi na niej.

Pobierz aplikację Outlook dla systemu Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by krystian3w** [comment]
Jak umiesz zrobić 100 tys. testów to może i masz rację.

**Comment by OtakuPL** [comment]
Czyli nie naprawisz? Czy postarasz się to ogarnąć? Bo nie wiem jak mam to odbierać, jesteście chyba jedynymi osobami które mogą coś z tym zrobić 😇

Pobierz aplikację Outlook dla systemu Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by krystian3w** [comment]
Ja ani @gomoku pewnie nie, musisz czekać aż odtworzy błąd MajkiIT i będzie to można naprawić filtrami (błąd w budowie playera powinien naprawić webmaster jak strona nie została z niego osierocona i "Wordpressem" zajmuje się każdy mający jakieś uprawnienia).

**Comment by OtakuPL** [comment]
Player/odtwarzacz jest ok, też mam do kodu dostęp, działa ten odtwarzacz bez zarzutu z adblockiem na innej stronie,
 anime-odcinki.pl ten sam pozycja 1  (GDrive  PL do 1080p)
![image](https://user-images.githubusercontent.com/12618580/186411519-5ddf4073-5862-48e5-b633-34968ed47877.png)
Sam player bez strony, wpisany w url tak samo działa:  
![image](https://user-images.githubusercontent.com/12618580/186411787-f7f6b70d-8ee9-4ac0-8276-31fc157dc8ad.png)
tylko na centrum-dramy.pl nie otwiera się, nie wiem dlaczego, wyłączyłem nawet nakładkę na reklamę w tym szablonie na centrum-dramy.pl i nadal to samo, hmmm
Może to coś pomoze do rozwiązania problemu :)
Poczekam cierpliwie na MajkiIT, chyba ze wam coś sie uda zdziałać, byłbym mega wdzięczny :)

**Comment by garry-ut99** [comment]
> OtakuPL : Strona działa prawidłowo

Może ja niejasno się wyraziłem albo ty niezrozumiałeś jak trzeba, to doprecyzuję: nawet po wyłączeniu adblockera przeładowałem stronę kilka razy i film nie chciał się ładować, dopiero za którymś razem zaczął znowu działać więc bez adblockera też potrafi się film nie odpalić....

**Comment by OtakuPL** [comment]
Dziwne, nie widzę tego problemu u siebie, sprawdzałem z chrome i Opery GX i ładują się od razu, naprawdę nigdy nie było problemu z ładowaniem się playerów hmmm

Pobierz aplikację Outlook dla systemu Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by garry-ut99** [comment]
Chyba coś poprzestawiałeś w tym swoim adblocku i nie podajesz faktów zgodnych z rzeczywistością, u mnie z listami filtrów które podawałeś w zgłoszeniu (EasyList + Oficjalne Polskie Filtry) widzę 14 zablokowanych żądań na ikonce Adblocka, podczas gdy na twoim screenie jest to zaledwie 7, jedyny przypadek gdy mogę uzyskać 7 zablokowanych żądań na ikonce Adblocka to wtedy gdy włączę w Adblocku  "Ochrona przed kopaniem kryptowalut (Bitcoin)" czyli w praktyce jest to lista "NoCoin Filter List" i wtedy jest 7 zablokowanych żądań na ikonce Adblocka i filmik się nie ładuje...więc stary upewnij się lepiej albo najlepiej zainstaluj Adblocka z domyślnymi ustawieniami na innym profilu CHrome albo na innej przeglądarce i przetestuj jescze raz.

**Comment by OtakuPL** [comment]
Ok, sprawdzę - chociaż to dziwne bo to świerza instalacja adblock, nic nawet tam nie dotykałem, po prostu włączyłem... Tylko co niby robi NoCoin Filter List na tej stronie ;_; ostatni raz jak było na niej coś wspólnego z minerem to w 2017r i chyba od tej pory strona była zamknieta i postawiona nowa z nowym właścicielem nikt nie zaktualizował tego filtra na tej stronie, jeśli mogę prosić o usunięcie go, bede wdzieczny :)

Pobierz aplikację Outlook dla systemu Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by garry-ut99** [comment]
> OtakuPL : Tylko co niby robi NoCoin Filter List na tej stronie ;_; ostatni raz jak było na niej coś wspólnego z minerem to w 2017r i chyba od tej pory strona była zamknieta i postawiona nowa z nowym właścicielem nikt nie zaktualizował tego filtra na tej stronie, 

- blokuje `harajuku.pl` tak jak wspomniane w [zgłoszeniu](https://github.com/hoshsadiq/adblock-nocoin-list/issues/441)

> OtakuPL : jeśli mogę prosić o usunięcie go, bede wdzieczny :)

- nie my zarządzamy tą listą, tylko ktoś inny
- już przecież napisałem we [wcześniejszym komentarzu](https://github.com/MajkiIT/polish-ads-filter/issues/21228#issuecomment-1225518714) że już zgłosiłem ten błąd w [odpowiednie miejsce](https://github.com/hoshsadiq/adblock-nocoin-list/issues/441), pozostaje czekać aż naprawią

**Comment by OtakuPL** [comment]
Ok, dziękuję, przepraszam za nieogar z mojej strony.

Pobierz aplikację Outlook dla systemu Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by krystian3w** [comment]
Być może long COVID, udar albo jakiś glejak.

**Comment by OtakuPL** [comment]
To było nie miłe panie mangako, chętnie bym poczytał twoje prace, nie wyzywajmy się, ja tego nie robie.

Pobierz aplikację Outlook dla systemu Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by krystian3w** [comment]
Ale ja nie rysuję nawet hobbystycznie.

Najwyżej nakładam kwadraty i strzałki na screeny by pokazać reklamy i resztki reklamowe.
