### ISSUE TITLE
Joomla 4.x i toolbar

### ISSUE THREAD

**Issue by amnr** [MajkiIT/polish-ads-filter#21241]
### Co trzeba zrobić, aby pojawił się błąd?

Wystarczy wejść do palenu administracyjnego Joomli 4.x (testowane na wersji 4.2.2)
i w menu Articles nie pojawi się przycisk "Utwórz" a w edycji dowolnego artykułu
nie pojawią się przyciski "Zastosuj", "Zapisz i zamknij", itd.

### Przyczyna błędu

Toolbar joomli zawarty jest wewnątrz elementu:

<div id="subhead-container" class="subhead mb-3">…</div>

Problem związany jest z regułą z pliku polish-adblock-filters/adblock.txt:

~przelewy24.pl,~allegro.pl,~zaq2.pl,~docer.pl,~dpd.com.pl,~scp-wiki.net.pl,~swiat-magii.pl,~portable.info.pl,pl##[id*="ad-container"]:not(#documents-upload-container):not(#editor-preload-container):not(#component-lead-container)
~rp5.ua,~rp5.ru,~webcamera.pl##[id^="aswift_"]

### Naprawienie błędu

Dodanie :not(#subhead-container) do listy wykluczeń.

**Comment by krystian3w** [comment]
Zachowałeś 2 filtry.

Ten z 3 domenami na 99% nie jest jako id CSS w szablonie jumli (insane idea use `adswift_`).

**Comment by krystian3w** [comment]
Kody HTML poprzedaj i kończ ``` (jako osobne linie - składnia markdown).

Bo został przerobiony na 3 kropki z nadpisanym `.#user-content-subhead-container`
