### ISSUE TITLE
youtube z hostem 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2126]
@MajkiIT masz reklamy na youtube? umnie od czasu do czasu cos przepuszcza

**Comment by MajkiIT** [comment]
@xxcriticxx tak, od kilku dni coś się pojawia, ale to rzadko. Szukam powodu.

**Comment by MajkiIT** [comment]
@xxcriticxx wydaje mi się, że to przez to 
https://www.youtube.com/get_video_info?html5=1&video_id=QrwMloNa…ight=480&content_v=fX5USg8_1gA&authuser=0&ei=oyOaWO79MdDwNK2XgeAP

reguła `=adunit&`

**Comment by xxcriticxx** [comment]
@MajkiIT ja tez mam zadko ale cos tam sie pokaze hodzi mi z hoste plikem nie filtrami

**Comment by xxcriticxx** [comment]
temat jest juz na easylist forum i na adblock forum niby reklamy z Gemius

**Comment by MajkiIT** [comment]
Wiem, ale ja na routerze blokowałem urle które i wysłałeś i tak jak mówisz pojawiała się reklama co jakiś czas. Teraz dodałem ten regex i sprawdzam. Wczoraj po skakaniu pomiędzy filmami reklama się nie pojawiła. Dzisiaj potwierdzę Ci, że to to.

**Comment by MajkiIT** [comment]
@xxcriticxx chyba już same hosts nie blokują reklam. Dodatkowo doszły kolejne reguły. Nadal badam sprawę.

**Comment by xxcriticxx** [comment]
@MajkiIT pozyjemy zobaczymy. dogadales sie z elektroda napisz cos na email plz.

**Comment by xxcriticxx** [comment]
@MajkiIT script ready ver 5.36

**Comment by xxcriticxx** [comment]
@MajkiIT read `https://discourse.pi-hole.net/t/how-do-i-block-ads-on-youtube/253`

**Comment by MajkiIT** [comment]
@xxcriticxx dzięki. Siądę do tego dzisiaj.

**Comment by MajkiIT** [comment]
@xxcriticxx Testowałeś na moje oko ten skrypt nie działa prawidłowo.

**Comment by xxcriticxx** [comment]
@MajkiIT nope nie bylo czasu

**Comment by MajkiIT** [comment]
@xxcriticxx Dzisiaj siądę do tego. Będę miał 8 letniego testera YT to pójdzie sprawnie.

**Comment by xxcriticxx** [comment]
@MajkiIT powodzenia na tej stronie jest kilka nowych poprawek tego scriptu

**Comment by MajkiIT** [comment]
@xxcriticxx No właśnie walczę z tym.

**Comment by xxcriticxx** [comment]
@MajkiIT jakis postep do przodu?

**Comment by MajkiIT** [comment]
Tak, skrypt jest dobry, tylko wymaga aktualnej listy domen. Próbuje znaleźć sposób aby to ograć, bo ten sposób z DNS dumper korzysta z cache i jest odświeżany co miesiąc.

**Comment by xxcriticxx** [comment]
@MajkiIT domany chyba sa random i bendzie ich z 2mil przy 1mil dnsmasq siada

**Comment by MajkiIT** [comment]
Dlatego chcę dodać te wszystkie domeny do tabeli i robić skrypt, który będzie starał się rozwiązywać nazwę domeny. Jeśli będzie ok to wpisze do bazy. Potem export z bazy tych wartości, które mają IP i będzie ok.

**Comment by xxcriticxx** [comment]
@MajkiIT zgubiles mnie w polowie poczekam na gotowe scritp

**Comment by MajkiIT** [comment]
@xxcriticxx w dużym skrócie chce odpytywać o te 2 mln domen i sprawdzac ktore dzialaja.

**Comment by xxcriticxx** [comment]
@MajkiIT bendzie kotki oglondal?

**Comment by MajkiIT** [comment]
kotki?

**Comment by xxcriticxx** [comment]
funny cat videos :)

**Comment by MajkiIT** [comment]
not, why?

**Comment by xxcriticxx** [comment]
zeby uzyskac fingerprinty tych domenow

**Comment by MajkiIT** [comment]
nie, wygeneresuje skryptem wszystkie możliwości a potem będę o każdą domenę pytał serwerów DNS

**Comment by xxcriticxx** [comment]
@MajkiIT kiedy skonczysz podaj liste

**Comment by MajkiIT** [comment]
Może w ciągu tygodnia.

**Comment by MajkiIT** [comment]
@xxcriticxx Pierwsze testy są obiecujące 
![2017-02-19_1913](https://cloud.githubusercontent.com/assets/11302675/23104947/a566a272-f6d7-11e6-9e85-6146f287153f.png)

**Comment by xxcriticxx** [comment]
@MajkiIT ile masz finger printow?

**Comment by MajkiIT** [comment]
Na chwilę obecną zrobiłem sobie lokalnie na routerze, że wszystko co jest domeną *.googlevideos.com jest blokowane. To pozwoli mi na sprawdzenie czy to ma sens.

**Comment by xxcriticxx** [comment]
@MajkiIT router bierze wildcards?

**Comment by MajkiIT** [comment]
Tak.

**Comment by xxcriticxx** [comment]
@MajkiIT jest nowa ver tego scriptu 4h old

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki. Zaraz zerknę.

**Comment by MajkiIT** [comment]
@xxcriticxx ogarnąłem skrypt i wrzucam sobie domeny na routerze. Testuję.

**Comment by xxcriticxx** [comment]
@MajkiIT ile tego jest?

**Comment by MajkiIT** [comment]
w zależności od godziny od 96 -99 domen. Domeny pobieram co 1 h a skrypt przerabiam co 15min.

**Comment by xxcriticxx** [comment]
@majkiit Czyli jak oglondasz więcej wtedy jest więcej domenow?

**Comment by xxcriticxx** [comment]
@FadeMind masz jakis pomysl na youtube z hostem?

**Comment by MajkiIT** [comment]
@xxcriticxx Nie reklamy są serwowane z każdej domeny i jest to roundrobin. Nie wiesz na którą Ci to trafi. 

Mój pomysł to DNS, który wpiszesz sobie w ustawieniach. Wersja min to mikrotik w kolokacji lub usługa dns na cloudflare. Można też to wrzucać skryptem na router.... ja tak robię.

**Comment by xxcriticxx** [comment]
@MajkiIT podasz mi jakoś listę do testów?

**Comment by MajkiIT** [comment]
[yt.txt](https://github.com/MajkiIT/polish-ads-filter/files/791357/yt.txt)

Nie jestem przekonany. Czy to działa prawidłowo, bo domeny w kółko się zmieniają,

**Comment by xxcriticxx** [comment]
ok ale jak dodasz *.googlevideo.com to co sie dzieje?

**Comment by xxcriticxx** [comment]
@MajkiIT tak wyglonda jeden dzien umnie 

`http://pastebin.com/raw/5JjZ7pbU`

**Comment by MajkiIT** [comment]
Nie działa prawidłowo YT

**Comment by FadeMind** [comment]
```
[fademind@manjaro ~]$ cat /etc/hosts|grep "youtube.com"
0.0.0.0 s2.youtube.com
0.0.0.0 s.youtube.com
0.0.0.0 ads.youtube.com
0.0.0.0 askyoutube.com
0.0.0.0 img.youtube.com.kjpselecthardwoods.com
0.0.0.0 uyoutube.com
0.0.0.0 www.askyoutube.com
0.0.0.0 www.facebookvsyoutube.com
0.0.0.0 www.uyoutube.com
0.0.0.0 www.visitas-youtube.com
0.0.0.0 www.you-youtube.com
0.0.0.0 you-youtube.com
0.0.0.0 youtube.comsearch.musicfrost.com
```
Do tego mam zablokowane wszystkie subdomeny doubleclick etc.

**Comment by xxcriticxx** [comment]
@FadeMind masz reklamy na tabletach, iPadach , telefonach?

**Comment by xxcriticxx** [comment]
@MajkiIT zmieniłeś upstream DNS?

**Comment by FadeMind** [comment]
@xxcriticxx nie mam

**Comment by xxcriticxx** [comment]
@FadeMind potestuj bo yt coś zmienia

**Comment by FadeMind** [comment]
@xxcriticxx nie mam co testować, ja nie mam żadnych reklam na YT bo mam BARDZO restrykcyjny hosts file :stop_sign:

**Comment by xxcriticxx** [comment]
Yt używa random DNS hostów do serwowania reklam sam host nie wystarcza

**Comment by FadeMind** [comment]
@xxcriticxx ja nie mam reklam na YT w ogóle :) więc nie pomogę

**Comment by xxcriticxx** [comment]
Testuj naczymys co niema ublocka tylko sam host

Zobacz ile masz polonczen do videogoogle.com

**Comment by xxcriticxx** [comment]
Blokujesz https? Serwujesz własne certificaty?

**Comment by FadeMind** [comment]
Nie

**Comment by xxcriticxx** [comment]
Ok to zobacz czy masz polonczenia do googlevideo.com

Jakiego upstream DNS używasz?

**Comment by FadeMind** [comment]
@xxcriticxx openDNS.

Blokowane domeny/reguły na Youtube :
```
||s.youtube.com^
||youtube.com/set_awesome? 
||googleads.g.doubleclick.net^
||youtube.com/api/stats/ads?
/api/ads/*
googletagservices.com/gpt.js
||pagead2.googlesyndication.com^
||www.googletagservices.com^
/pagead/lvz?
||youtube.com/ptracking?
youtube.com##[href^="https://www.youtube.com/cthru?"]
com##[class^="ad-"]
/generate_204$image
##[class$="-ads"]
##.ytp-ad-progress-list
##.video-ads
##.ad-container
###watch7-sidebar-ads
###watch-channel-brand-div
```

**Comment by xxcriticxx** [comment]
Przetestuj na tablecie albo telefonie na samym hostcie bez ublocku

**Comment by xxcriticxx** [comment]
@MajkiIT jakes nowiny?

**Comment by MajkiIT** [comment]
@xxcriticxx niestety nie, bo miałem urwanie głowy i nie siadłem do swojego skryptu. Ten skrypt który był w tym linku jest zły.

**Comment by xxcriticxx** [comment]
@MajkiIT czytalem gdzies ze z opendns jest mniej reklam na yt. na tym poscie z innego forum widze ze jest jakas nowa lista do blokowania yt.

**Comment by xxcriticxx** [comment]
@MajkiIT jest teraz jakis nowy temat zeby uzyc regex z dnsmasq. potestujesz?

```
spacemonkey
I still get ads on my android devices and searching for *.googlevideo.com in pi-hole's log brings up results that were still not in any of the compiled lists. It's really a whack-a-mole situation.
I was looking up how to use regex in dnsmasq and it seems that there is a patch but it has to be compiled, which I have never done.
http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2013q2/007124.html2
https://github.com/cuckoohello/dnsmasq-regex3
https://gist.github.com/chriseldredge/73889202
```

**Comment by MajkiIT** [comment]
@xxcriticxx ok siądę do tego.... jak nie dzisiaj to jutro rano.

**Comment by xxcriticxx** [comment]
ja za slabo znam sie na ubuntu zeby taki experiment przeprowadzic

**Comment by xxcriticxx** [comment]
@MajkiIT dodalem do black listy `redirector.googlevideo.com` i narazie jest chyba dobrze

**Comment by MajkiIT** [comment]
@xxcriticxx chyba mam już. To u mnie przez 4 h nie dało żadnej reklamy a widzę, że domeny są działające. 
https://raw.githubusercontent.com/HenningVanRaumle/pihole-ytadblock/master/ytadblock.txt

**Comment by xxcriticxx** [comment]
@MajkiIT wczoraj podalem jemu nasze listy :)

**Comment by MajkiIT** [comment]
@xxcriticxx Ok odezwę się do niego i razem coś zrobimy, bo szkoda aby oddzielnie to machać.

**Comment by xxcriticxx** [comment]
@MajkiIT wlonczylem youtube na xtr pc i caly czas cos tam lecji generuje listy :)

**Comment by MajkiIT** [comment]
@xxcriticxx No właśnie wiem. Generowanie trwa za długo.

**Comment by xxcriticxx** [comment]
troche trwa pocalym dniu podaje dla van raumle i on updatetuje liste

**Comment by MajkiIT** [comment]
aha czaję. Taki sposób.

**Comment by xxcriticxx** [comment]
@MajkiIT jak u ciebie masz jakies reklamy? dasz rade zmienic na routerze dns do opendns?

**Comment by MajkiIT** [comment]
@xxcriticxx wczoraj nie widziałem żadnej reklamy. Testowałem na apple TV, Android oraz Ipad. Przepchałem ponad 14 GB danych dziennie z YT i nic. 

Tak co do OPENDNS to juz dodałem kolejnego SSID na routerze i przepnę coś na ten WLAN, aby potestować. Dam znać jutro co i jak.

**Comment by xxcriticxx** [comment]
uzywajac tej listy? zero reklam?

**Comment by MajkiIT** [comment]
Tak przerobiłem to /https://raw.githubusercontent.com/HenningVanRaumle/pihole-ytadblock/master/ytadblock.txt/ aby wrzucić na router z automatu za pomocą cron. Parsuje plik i wrzucam do DNS Cache na routerze.

Tak pracowałem w domu, słuchawki i muzyka z YT. Nic się nie pojawiło.

**Comment by xxcriticxx** [comment]
@MajkiIT vanraumle jakies tam zmiany zrobil widziales

**Comment by xxcriticxx** [comment]
@MajkiIT popowalem yt caly dzien 

```
http://pastebin.com/wgyab6yD
```

**Comment by MajkiIT** [comment]
@xxcriticxx szacun.

**Comment by xxcriticxx** [comment]
chyba nie damy rady

**Comment by xxcriticxx** [comment]
@MajkiIT w tobie jeszcze nadzieja stym regexem moze cos zrobisz. router mozna uzywac wildcards (*) ??????? i opendns trzeba trzeteswowac.

**Comment by MajkiIT** [comment]
@xxcriticxx w czym jest problem? 
U mnie na mikrotiku można ustawić regex, ale przy takim regexie i dużej ilości zapytań gubi się to. 
Co do opendns to testuje w pracy i jakoś nie za bardzo to działa, ale testuje dalej.

**Comment by xxcriticxx** [comment]
@MajkiIT ja moge blokowac z wildcardem `*.googlevideo.com` ale tez niewiem czy nie udusze sprzentu :)

**Comment by MajkiIT** [comment]
@xxcriticxx jeśli to nie jest robione na bazie filtru L7 to będzie ok. Np. DNS Cache będzie to robił.

**Comment by xxcriticxx** [comment]
@MajkiIT tak to bendzie wyglondalo poczytaj `https://discourse.pi-hole.net/t/how-do-i-add-wildcard-sites-to-the-blacklist/337`

**Comment by MajkiIT** [comment]
Czyli w ten sam sposób jaki chce to zrobić u siebie. Tylko ja chcę wszystkie możliwości wrzucić np. do tinydns i odpytywać jego.

**Comment by xxcriticxx** [comment]
@MajkiIT zamontuj sobie tego pihole i potestuj. wszystko dziala na raspberry pi za $35

**Comment by xxcriticxx** [comment]
albo na ubuntu jak masz jakis stary pc

**Comment by xxcriticxx** [comment]
@MajkiIT check this out `https://www.h3xed.com/blogmedia/youtube-info.php` jest maly problem bo domeny sa takie jak chcemy blokowac hostem <details>http://r7---sn-j5caxoxu-hh0e.googlevideo.com/videoplayback?itag=137&lmt=1486046219987050&pl=22&key=cms1&upn=IZYmYQyfjlc&dur=675.474&ipbits=0&expire=1488396097&source=youtube&gir=yes&clen=200680195&id=o-AHu0Ntxq6KRV56o-MFNlAJ4QRCzskqdOix0jEMz1Z_9G&mime=video%2Fmp4&signature=5ABC3F741C7402DA5A6683F0028B3E967161D06A.844A287A49850A62E72817E90B61CE7C1BAC24DB&ip=68.193.153.180&sparams=clen,dur,expire,gir,id,initcwndbps,ip,ipbits,ipbypass,itag,lmt,mime,mm,mn,ms,mv,pl,source,upn&redirect_counter=1&req_id=d493a90c96bfa3ee&cms_redirect=yes&ipbypass=yes&mm=31&mn=sn-j5caxoxu-hh0e&ms=au&mt=1488374433&mv=m</details>

![capture](https://cloud.githubusercontent.com/assets/15007183/23461615/a2fab22a-fe58-11e6-8626-a5938d3fa2a9.PNG)

**Comment by MajkiIT** [comment]
Zerknę, dzięki.

**Comment by MajkiIT** [comment]
@xxcriticxx dzisiaj zobaczyłem 1 reklamę na YT. Szukam sposobu aby wysupłać te domeny.

**Comment by xxcriticxx** [comment]
z jaka lista?

**Comment by xxcriticxx** [comment]
i czy z opendns?

**Comment by MajkiIT** [comment]
zatrzymałem się na tych https://github.com/MajkiIT/polish-ads-filter/files/791357/yt.txt

bez opendns. Z Opendns i tak miałem ich reklamy. Może rzadziej, ale były.

**Comment by MajkiIT** [comment]
@xxcriticxx używasz jeszcze tych reguł blokujących reklamy na YT ?

**Comment by xxcriticxx** [comment]
Nope tylko standardowe reguł mam. Mam reklamy tylko na mobile iphonach

**Comment by xxcriticxx** [comment]
Morzesz wykasować Please

**Comment by MajkiIT** [comment]
No właśnie ja coś porobiłem, że od 2 tygodni nie pojawiła mi się, żadna reklama na IPAD.

**Comment by xxcriticxx** [comment]
@MajkiIT napisz wiecej info

**Comment by MajkiIT** [comment]
@xxcriticxx cześć rzeczy usunąłem z tej listy `
https://raw.githubusercontent.com/HenningVanRaumle/pihole-ytadblock/master/ytadblock.txt`
Jutro postaram się napisać co. Wrzuciłem do DNSa i blokuje. Dodatkowo mam coś w blokowanych filtrach url. Też napiszę co.

**Comment by MajkiIT** [comment]
@xxcriticxx była aktualizacja https://github.com/HenningVanRaumle/pihole-ytadblock/commit/db198dbffa95d8e6199412ad835b566318fdefd3

**Comment by MajkiIT** [comment]
pokrywa się to z moją listą

**Comment by xxcriticxx** [comment]
@MajkiIT ja dalej nie lapie tego yt co mam tutaj zrobic?

**Comment by MajkiIT** [comment]
Dodaj sobie do hosts na routerze to co dodałem 2 posty wyżej. To od 3 tygodni powoduje, ze nie mam reklam.

**Comment by xxcriticxx** [comment]
ale pisales ze jeszcze oprocz tego cos blokujesz

**Comment by MajkiIT** [comment]
Wyłączyłem wszystko zbędne i tez nie ma reklam.
