### ISSUE TITLE
pudelek.pl

### ISSUE THREAD

**Issue by Lukjan39** [MajkiIT/polish-ads-filter#21291]
brak zdjec na podstronie galeri, np https://www.pudelek.pl/celebryci-inwestuja-w-domy-za-granica-ewa-chodakowska-w-grecji-natalia-siwiec-w-meksyku-malgorzata-rozenek-w-tajlandii-zdjecia-6814052224559968g

**Comment by MajkiIT** [comment]
@F4z @adamW zerkniesz ? Wydaje mi się, że to wina reguł Adguard.

**Comment by AdamWr** [comment]
Jeśli chodzi o te zdjęcia zaznaczone na obrazku poniżej, to u mnie się wyświetlają.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/192741289-3cf52e0a-a74b-40ff-89bd-354592030c1a.png)

</details>

**Comment by AdamWr** [comment]
Wygląda na to, że problem występuje tylko w przypadku uBlocka Origin.
To powinno rozwiązać problem  (wykluczę regułę z listy dla uBO):
```adblock
pudelek.pl#@?#div[class*=" "]:matches-css(position: relative) > img[class][src^="https://v.wpimg.pl/"][alt]:not([srcset]) + div:upward(1)
```

Nie wiem, czy to błąd, ale na przykład taka reguła:
```adblock
pudelek.pl#?#div[class*=" "]:matches-css(position: relative) > img[class][src^="https://v.wpimg.pl/"][alt]:not([srcset])
```
blokuje obrazki (wygląda jakby `:not([srcset])` nie było stosowane w tym przypadku.
Ale już coś takiego:
```adblock
pudelek.pl#?#div[class*=" "] > img[class][src^="https://v.wpimg.pl/"][alt]:not([srcset])
```
obrazków nie blokuje, a teoretycznie powinno blokować więcej, albo przynajmniej tyle samo elementów.

**Comment by Lukjan39** [comment]
teraz dziala ok

**Comment by krystian3w** [comment]
rere

**Comment by krystian3w** [comment]
@olegwukr
