### ISSUE TITLE
net-s.pl

### ISSUE THREAD

**Issue by DeJkSEBA** [MajkiIT/polish-ads-filter#21292]
Don't have to be blocked, usual polish e-commerce.

**Comment by MajkiIT** [comment]
@hawkeye116477 lub @krystian3w  to chyba u Was jest.

**Comment by krystian3w** [comment]
Ale tam chyba brak poprawy w realizacji zamówień (i pewnie dalej firma utrzymuje się z dofinansowania do niepełnosprawności części kadry jak nie prawie całości).

Plik hosts można edytować by blokadę cofnąć.

**Comment by hawkeye116477** [comment]
Na ceneo i opineo nie widać aż tak dużo negatywów, ale znalazłem więcej na https://www.okazje.info.pl/sklep-internetowy/net-s-pl/.
