### ISSUE TITLE
Newsweek.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2129]
Bardzo was proszę o pomoc przy usunięci ikonek social mediów z tej strony, tzn wiem że idzie to zrobić w łatwy sposób lecz zostają jakieś pozostałości i ikonki się jeszcze rozjeżdzają jakby tego było mało to filtr
 " Fanboy's Social Blocking List " usuwa wszystko a ja chcę pozostawić rss i wyszukiwarke więcej na fotce.

![newws](https://cloud.githubusercontent.com/assets/23176832/22752076/71fa6aa2-ee37-11e6-9ca9-dc2a139da3f0.jpg)

**Comment by MajkiIT** [comment]
Dobry task wrzuciłeś :) . Chciałem zablokować wszystkie elementy z class "Ico" a potem odblokować tylko RSS, nie dało rady.

**Comment by blocker999** [comment]
@MajkiIT 

Dobra to w takim razie będzie tak :

![news ok](https://cloud.githubusercontent.com/assets/23176832/22779964/16c93dbc-eebd-11e6-89fa-af37f54b4e5a.jpg)

**Comment by F4z** [comment]
Można też spróbować z takimi regułami:
`newsweek.pl##.facebookIco`
`newsweek.pl##.twitterIco`
`newsweek.pl##.gplusIco`

`newsweek.pl##nav.Top-Menu > .sharenavi:style(width: 35px !important;)`

Wiadomo, trzy pierwsze żeby ukryć te niechciane ikonki, a czwarta żeby ikonka rss była bliżej lupy i wtedy to powinno lepiej wyglądać.
Tylko, że to nie będzie działać w Adblocku.
