### ISSUE TITLE
dobrewiadomosci.net.pl patronite

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#21308]
### Zrzut ekranu 

![20220929-1664452718](https://user-images.githubusercontent.com/9846948/193049844-002f5418-40dd-455d-97e1-16934488134c.png)

bez działającego adguarda

![20220929-1664452728](https://user-images.githubusercontent.com/9846948/193049835-5c1cadb3-6f2e-46a5-a863-1c2cb8d1266e.png)

### Link bezpośredni 

https://dobrewiadomosci.net.pl

### Co trzeba zrobić, aby pojawił się błąd?
1. Otwórz stronę. 

### Moja konfiguracja 

**Przeglądarka internetowa:** Chrome Stable

**Rozszerzenia i skrypty:** Adguard Extension + Adguard Extra + Polska Ciasteczkowa Zgoda

**Listy filtrów:** 

```
AlleBlock
Filtr AdGuard Cookie Notices
Filtr Popupów AdGuard
Filtr elementów szpiegujących AdGuard
Filtr irytujących elementów AdGuard
Filtr mediów społecznościowych AdGuard
Filtr śledzenia URL AdGuard
Oficjalne polskie filtry dla AdBlock, uBlock Origin i AdGuard
Podstawowy filtr AdGuard
Polski Anty-irytujący Dodatek Specjalny
Polski filtr przeciwko alertom o Adblocku
Polskie Filtry Elementów Irytujących
Polskie Filtry Społecznościowe
```

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Dlaczego ukryto link do patronite? :> 
`dobrewiadomosci.net.pl,getlevel.info,tyna.info.pl,kryptoporadnik.pl,tkn24.pl,fakenews24.pl##center`

**Comment by krystian3w** [comment]
kiedyś widać były wycentrowane reklamy, najlepiej napisać by wembaster nie centrował self-promo.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/5585
