### ISSUE TITLE
nauka.rocks

### ISSUE THREAD

**Issue by szyha** [MajkiIT/polish-ads-filter#21313]
### Zrzut ekranu 

![firefox_h287acL8ah](https://user-images.githubusercontent.com/12976368/194752827-7fb23a5f-d258-4178-8686-e92eb3fb6d6f.png)

### Link bezpośredni 

https://nauka.rocks/sowa-ciemnolica/

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
1. Wejdź na powyższą stronę, zaczekać 3 sekundy 

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Firefox 105.0.3

**Rozszerzenia i skrypty:** 
uBlock Origin 1.44.4

**Listy filtrów:** 
  ![firefox_I3C4aC59LL](https://user-images.githubusercontent.com/12976368/194752705-2f81f14a-2a53-4646-86a1-b4b5b7451e4d.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Testowane na domyślnej konfiguracji z takim samym skutkiem.

**Comment by AroKol78** [comment]
`nauka.rocks###sticky-anchor`
