### ISSUE TITLE
kanalsportowy.pl

### ISSUE THREAD

**Issue by jacc555** [MajkiIT/polish-ads-filter#21314]
![SmartSelect_20221007-202123_Chrome](https://user-images.githubusercontent.com/70823330/194627704-440c6f71-a440-4365-bed9-8e58ce27677d.jpg)
[kanalsportowy.pl](http://kanalsportowy.pl/) 
1. Wykryto wtyczkę Adblock
2. Reklamy na filmach.

W [aplikacji](https://play.google.com/store/apps/details?id=pl.kanal.sportowy)  jest podobnie. Tzn z włączonym adguard filmy nie startują po wyłączeniu Adblock są reklamy.

**Comment by krystian3w** [comment]
Naprawione w https://github.com/AdguardTeam/AdguardFilters/commit/8006b8cad6ce0bbdc08cfcd2784059e9a0ac7649 /

**Comment by krystian3w** [comment]
#21416

**Comment by krystian3w** [comment]
beep
