### ISSUE TITLE
vod.tvp.pl

### ISSUE THREAD

**Issue by Lukjan39** [MajkiIT/polish-ads-filter#21323]
nowa wersja vod.tvp.pl, wykrywa blokada materialow.

**Comment by xxcriticxx** [comment]
@Lukjan39 podaj test link

**Comment by Lukjan39** [comment]
np https://vod.tvp.pl/seriale,18/komisarz-alex-odcinki,277681/odcinek-219,S18E219,318790

**Comment by siepa3** [comment]
moja mama w rozpaczy, vod.tvp.pl nie działa - potwierdzam

**Comment by Lukjan39** [comment]
zaktualizuj filtry, dziala ok

**Comment by siepa3** [comment]
dzieki, potwierdzam
