### ISSUE TITLE
Remove from AAk script

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2132]
Please see https://github.com/X01X012013/AdBlockProtector/issues/46

**Comment by xxcriticxx** [comment]
@MajkiIT @F4z  mieliscie cos usunac z starej listy aak bo wyswietla za duzo reklam na wp.pl

**Comment by F4z** [comment]
To `@@||wp.pl^$script,image` i MajkiIT to tutaj "wyłączył" - https://github.com/MajkiIT/polish-ads-filter/blob/master/anti-adblock-killer/anti-adblock-killer-filters.txt#L930

A [tutaj](https://github.com/X01X012013/AdBlockProtector/issues/46#issue-206683229) chyba pomyliłeś strony, bo napisałeś `work.pl`

**Comment by xxcriticxx** [comment]
tak ale adblockprotector zrobil forka aak i ta linia napewno tam jeszcze jest
