### ISSUE TITLE
pobieramy24.xyz

### ISSUE THREAD

**Issue by jacc555** [MajkiIT/polish-ads-filter#21321]
Po wejściu na stronę z włączonym uBlock pojawia się pasek informujący że korzystasz z uBlock i strona nie działa w pełni.
Po zalogowaniu/rejestracji przy włączonym uBlock zamiast widocznych linków do pobierania widnieje informacja o wyłączeniu blokowania reklam na stronie.
[przyklad](https://pobieramy24.xyz/topic/5884989-faceci-w-czerni-men-in-black-1997-multiremux2160puhdblu-rayhdrhevcatmos71-denda/)
![Przechwytywanie](https://user-images.githubusercontent.com/70823330/195975802-844542fa-f014-4f10-a7f4-7763e56e85b9.PNG)

**Comment by krystian3w** [comment]
@olegwukr

**Comment by krystian3w** [comment]
Meh

**Comment by krystian3w** [comment]
Trzeba być zalogowanym?
