### ISSUE TITLE
darmowe-torenty.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#21332]
Twoja przeglądarka ma zainstalowaną wtyczkę AdBlock lub podobną.
Do prawidłowego działania serwisu wymagane jest wyłączenie wtyczki na tej stronie.
Jeśli nie wyłączysz wtyczki, nie będziesz mógł w pełni korzystać z serwisu.

**Comment by krystian3w** [comment]
bump @olegwukr
