### ISSUE TITLE
moj.tauron.pl

### ISSUE THREAD

**Issue by mKoonrad** [MajkiIT/polish-ads-filter#21357]
moj.tauron.pl##div.ebok-pop-up
moj.tauron.pl##div.promo-box

![image](https://user-images.githubusercontent.com/11725227/203053688-c084ff30-4538-41cf-a8a5-5db6dcf54092.png)
![image](https://user-images.githubusercontent.com/11725227/203054542-88190315-0051-40d7-a28e-c15baf96157b.png)

**Comment by krystian3w** [comment]
Jak dla mnie to jest self-promo i nie każdy ma konto Tauron by to testować, ja bym musiał odblokować konto ojca do testów gdzie przekierowuje link o oczyszczaczach powietrza (np. do euro.com.pl i to już reklama a jak coś w stylu sklep.tauron.pl, to self-promo).

**Comment by mKoonrad** [comment]
@krystian3w Tylko ten ich "self-promo" to banner wyskakujący na całą stronę przy każdorazowym zalogowaniu się na konto, uniemożliwiający zrobienie czegokolwiek przed jego zamknięciem.

**Comment by krystian3w** [comment]
Możesz zasubskrybować moduł pop-upów:

https://polishannoyancefilters.netlify.app/modules

Link działający w domenie GitHub:

https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PAF_pop-ups.txt&title=Modu%C5%82%20Pop-upy

Jeszcze przydałałby się informacja czy pop-up blokuje przewijanie, aż nie zamkniesz witryny - wtedy filtr szkodzi użytkownikom i nie jest kompatybilny z AdBlock i Adblock Plus (ABP) jak nie siedzi to w np. `/pop.js`.


---

Oczyszczacze w module "inne" aż nie sprawdzę, że to zwykła reklama.

**Comment by krystian3w** [comment]
@mKoonrad / @MajkiIT ten filtr na pop-up jest zły, psuje pop-up o zmianie mejla kontaktowego do umowy.

Trzeba by dodać `-abp-has` do wykrywania linku/grafiki jako minimum.

**Comment by krystian3w** [comment]
Opcjonalnie można wyłapać użyteczne pop-upy tak:

```adb
moj.tauron.pl##div.ebok-pop-up:not(#popupContact)
```

ale to żmudne będzie.

**Comment by krystian3w** [comment]
Kod na "promo box" też do niczego, ukrywa mi baner o kończącym się cenniku na prąd...

taki nieco lepszy ale może przymulać witrynę:

```adb
##.promo-box:not(:matches-css(background: /odnowienia/))
```

**Comment by krystian3w** [comment]
Z nowości mam taki baner bez title:

> ![obraz](https://user-images.githubusercontent.com/35370833/208198809-0400e7b3-06de-40fe-9d90-c12b94825d04.png) |
> ---|


`https://moj.tauron.pl/Home/Pages/Faktury`

a na głównej dalej glitch z przedłużeniem umowy co się sama przedłużyła i czeka na aneks/eratę (sic!).

**Comment by krystian3w** [comment]
?
