### ISSUE TITLE
ikea.com/pl/pl/

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#21354]

**Comment by hawkeye116477** [comment]
To niestety będzie chyba musiało pójść do rozszerzenia, bo z jakiegoś powodu kiboke nałożył odblokowywanie tego.
Sprawa do zbadania dla @krystian3w.

**Comment by krystian3w** [comment]
Kiboke może wykrył zablokowane przewijanie i brak osobnego pliku (zmieszany js/xhr/json).

**Comment by hawkeye116477** [comment]
> może wykrył zablokowane przewijanie

Raczej odpada, bo u mnie przewijanie się nie blokuje. Raczej zakładam, że po zalogowaniu coś tam nie działa i stąd ten problem albo jakieś anomalie w innych krajach występują.

**Comment by krystian3w** [comment]
W Polsce działa logowanie, galeria, kody, podgląd 3D.

**Comment by krystian3w** [comment]
Już wiem, nie chce działać wysuwane menu w którym szybciej znajdziemy takie bajery:

![obraz](https://user-images.githubusercontent.com/35370833/202910400-e43c5972-456b-435f-b8f9-9d60e2eb3db4.png)

Czyli nie działa "wyloguj", dla zapamiętaj logowanie.
