### ISSUE TITLE
autofakty.pl [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#21352]
### Issue URL (Incorrect Blocking)
 [https://autofakty.pl/ubezpieczenia/jaki-wplyw-na-cene-oc-ma-pojemnosc-silnika-w-twoim-samochodzie/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fautofakty.pl%2Fubezpieczenia%2Fjaki-wplyw-na-cene-oc-ma-pojemnosc-silnika-w-twoim-samochodzie%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/1XKwq5W.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/h1X3rrM.png)
</details>

Caused by `autofakty.pl##.widget_text.widget, .entry`

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v4.1.39
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (2880), <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection, <br/>Legitimate URL Shortener<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media, <br/>Fanboy's Social Blocking List<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>Polish Social Filters, <br/>KAD - Anti-Scam, <br/>Polish Annoyances Filters, <br/>Polish Anti Adblock Filters

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/8551daa39ce9a498d07398ca968e4ac8cb1e7aa3/polish-adblock-filters/adblock.txt#L5248

z listy przeciwko reklamom.

**Comment by xxcriticxx** [comment]
paging doctor @MajkiIT

**Comment by krystian3w** [comment]
Spieszyć się nie musimy, na poziomie AdGuard filtr dezaktywowali (psuć może już tylko z ABP/uBo, w AG wymaga dezaktywacji AdGuard Base do reprodukcji).

**Comment by xxcriticxx** [comment]
MajkiIT ma te swoje automaty po ustawiane jak poprawisz to z automatu wroci

**Comment by MajkiIT** [comment]
@Alex-302 @xxcriticxx @krystian3w Thanks
