### ISSUE TITLE
vod.tvp.pl wykrywa AdGuard

### ISSUE THREAD

**Issue by konarsky** [MajkiIT/polish-ads-filter#21364]
### Zrzut ekranu 
https://i.imgur.com/Y0YOAVD.jpg

### Link bezpośredni 
https://vod.tvp.pl/seriale,18/ojciec-mateusz-odcinki,273907/odcinek-190,S15E190,305810)

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. otworzyć stronę z włączonym AdGuard
2. w lewym dolnym rogu kliknij przycisk "Odtwórz"

### Moja konfiguracja 
**Przeglądarka internetowa:** 
każda
**Rozszerzenia i skrypty:** 

**Listy filtrów:** 
1. EasyList
3. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
4. Oficjalne polskie filtry przeciwko alertom o Adblocku 
5. Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for AdGuard
6. EasyList Polish+EasyList
7. Peter Lowe's Blocklist
8. AdGuard Annoyances filter
9. AdGuard Other Annoyances filter
10. Adblock Warning Removal List
11. Polish Annoyances Filters

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
* Sprawdź bez "Adblock Warning Removal List".

   Jak się naprawi to raczej już bym listy nie włączał, nie ma tam jak dodać poprawek pod polskie witryny jak znowu nie zostaną dokopiowane w sekcję rosyjskich.

* Potem sprawdź wyłączając również: "EasyList Polish"

   Jak się naprawi to trzeba by zerpodukować błąd na Adblock Plus i dopytać czy oni naprawiają takie smaczki: https://github.com/easylistpolish/easylistpolish/issues (jak raz chcieli naprawić to właśnie wyjątek trafił do sekcji rosyjskiej "Adblock Warning Removal List", może zgłoszenia elektrody są OK jako podpórka) https://forums.lanik.us/viewforum.php?f=107-easylist-polish (na forum uważaj, bo może mapx- (intense) zalecić użycie uBlock Origin zamiast Adblock Plus lub AdGuarda)).

W przypadku jak to błąd z angielskiego EasyList to może jak wojna się skończy to zostanie naprawione hurtem: https://github.com/MajkiIT/polish-ads-filter/issues?q=label%3A%22adblock+detect%22+label%3Aodrzucone+is%3Aissue

Nie wiem na ile Eyeo jeszcze zagląda do listy adblock.txt, bo może nawet nie można usuwać filtrów, bo wskoczył anty-adblock.

W najgorszym razie trzeba to naprawić w filtrach "pierwszoplanowych" uAssets i AdGuardowych.

**Comment by xxcriticxx** [comment]
Wsparcie ABP powinno być dawno martwe.

**Comment by krystian3w** [comment]
To nic nie da, nie ma zamiennika EasyList pisanego składnią uBlock Origin MV2 i AdGuard MV2.

**Comment by konarsky** [comment]
Włączałem i wyłączałem filtry przed napisaniem postu tutaj. W podstawowym filtrze AdGuarda są dwie reguły:
1.) vod.tvp.pl#%#//scriptlet('prevent-fetch', 'pagead2.googlesyndication.com')
2.)vod.tvp.pl#%#//scriptlet('prevent-element-src-loading', 'script', 'hit.gemius.pl')
W momencie gdy są aktywne strona mieli bez powodzenia. Po wyłączeniu tych reguł strona ładuje się jednak zostaje wykryty adblock jak powyżej pisałem. No nic, przełącze się na uBlock Origin na tej stronie. 
Dzięki za pomoc.

**Comment by konarsky** [comment]
Może komuś się przyda:
w popdstawowym filtrze AdGuard (AdGuard Base Filter) wyłączyłem 3 reguły:

1) tvp.pl,tvp.info,swipeto.pl,sport.tvp.pl,cyfrowa.tvp.pl,vod.tvp.pl#%#//scriptlet('prevent-fetch', 'pagead2.googlesyndication.com')
2) tvp.pl,tvp.info,swipeto.pl,sport.tvp.pl,cyfrowa.tvp.pl,vod.tvp.pl#%#//scriptlet('prevent-element-src-loading', 'script', 'hit.gemius.pl')
3) tvp.info,tvp.pl#%#//scriptlet("json-prune", "ads_enabled data.ads.list.*")

Teraz wszystko działa jak należy.

**Comment by krystian3w** [comment]
To jest jakiś błąd biblioteki skrypletów, AdamWr gdzieś je dzisiaj linkował.

Wadliwie też działa `aeld` w domenach WP.

**Comment by konarsky** [comment]
Co ciekawe, AdBlocker Ultimate z tymi samymi regułami śmiga bez żadnych problemów.

**Comment by krystian3w** [comment]
Bo oni wolno kopiują kod AdGuard pewnie lub chamsko naprawili kilka minut po otwarciu zgłoszeń przez AdamaWr.

W drugim wypadku mogłoby było jakby wrzucili inną sugestię naprawy jak ta co zalecił AdamWr jest średnia.

**Comment by AdamWr** [comment]
Biorąc pod uwagę [ten komentarz](https://github.com/MajkiIT/polish-ads-filter/issues/21364#issuecomment-1344580706):
>Włączałem i wyłączałem filtry przed napisaniem postu tutaj. W podstawowym filtrze AdGuarda są dwie reguły:
1.) vod.tvp.pl#%#//scriptlet('prevent-fetch', 'pagead2.googlesyndication.com')
2.)vod.tvp.pl#%#//scriptlet('prevent-element-src-loading', 'script', 'hit.gemius.pl')
W momencie gdy są aktywne strona mieli bez powodzenia. Po wyłączeniu tych reguł strona ładuje się jednak zostaje wykryty adblock jak powyżej pisałem.

Domyślam się, że ten problem występuje w aplikacji w wersji "nightly" (7.12).
Jeśli tak, to jest to związane z tym błędem - https://github.com/AdguardTeam/Scriptlets/issues/264
Zostało to już naprawione, ale poprawka nie została jeszcze dodana do aplikacji.
W wersji stabilnej/w rozszerzeniach do przeglądarki powinno działać prawidłowo, ponieważ tam nadal używana jest stara wersja "skryptletów".

**Comment by Lukjan39** [comment]
tez nie dziala vod.tvp.pl, w adguard
