### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by jacc555** [MajkiIT/polish-ads-filter#21360]
Przy wejściu na stronę pojawia się taka reklama ale tylko raz dziennie przy kolejnym wejściu już jest czysto do następnego dnia.
![Screenshot_20221126-233056_1DM+](https://user-images.githubusercontent.com/70823330/204111322-903e0aab-766f-41bc-af4d-40d086f8c3db.jpg)

**Comment by MajkiIT** [comment]
@jacc555 nadal to masz?

**Comment by seba2282** [comment]
> @jacc555 nadal to masz?

@MajkiIT , na głównej pojawia się T-mobile. Masz coś innego z reklam?

**Comment by seba2282** [comment]
`www.filmweb.pl##.isReady.Section.page__section.MagentaDrawMovieSection.magentaDrawMovieSection`
Możesz zweryfikować to, @MajkiIT . Ta reguła u mnie ukrywa. 

Natomiast ta plansza ileś sekund jakiś filtr to ukrywa i nie ma problemów. Tylko nie pamiętam gdzie to wrzucone. (do autora i ekipy polskich filtrów).
