### ISSUE TITLE
forum.pasja-informatyki.pl incorrect blocking

### ISSUE THREAD

**Issue by awaluk** [MajkiIT/polish-ads-filter#21376]
### Zrzut ekranu 

![Zrzut ekranu z 2022-12-15 00-16-44](https://user-images.githubusercontent.com/13801608/207736095-818f3e40-0963-4b15-aa1a-3feab78f6b37.png)

### Link bezpośredni 

https://forum.pasja-informatyki.pl/576358/nie-dziala-ajax-na-hostingu?show=576365#c576365

### Co trzeba zrobić, aby pojawił się błąd?

W linku przykładowy temat na Forum Pasja Informatyki, gdzie obraz z linkiem wrzucony do dyskusji przez użytkownika jest wycinany przez filtr, prawdopodobnie dokładnie przez #5672. Screen zrobiony z włączoną listą, po wyłączeniu obrazek się pojawia. Sam autor posta jest zdezorientowany tym, że dodaje grafiki, a te się nie pojawiają, w takich przypadkach może nie być wiadomo o co chodzi w danej wypowiedzi w ogóle jeśli screen jest istotny dla kontekstu. Nie będę jednocześnie ukrywał, że jestem osobą zarządzającą forum i jak z jednej strony rozumiem blokowanie natrętnych reklam, tak wydaje się, że wycinanie z całej strony każdego obrazka z linkiem z target blank jest trochę zbyt daleko idące, co widać w tym przypadku.

### Moja konfiguracja 

Chrome, uBlock, "POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda"

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
A dasz radę ogarnąć proporcje obrazów? Kiepsko wygląda 16:9 ściskane do 9:16.

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by awaluk** [comment]
Takie dziwne rzeczy robi w niektórych przypadkach edytor do postów i uploadu obrazków, ale oczywiście zgoda, że to nie powinno tak wyglądać. Szykujemy poprawkę: https://github.com/CodersCommunity/forum.pasja-informatyki.local/pull/313

**Comment by krystian3w** [comment]
W sumie to i główna straciła obrazki (https://pasja-informatyki.pl/).

Może wymiana na takie specyfiki jest OK:

```adb
||forum.pasja-informatyki.pl/images/quesflo.png
forum.pasja-informatyki.pl#?#.qa-widget-side:-abp-has(.adsbygoogle)
forum.pasja-informatyki.pl#?#div[style^="width:728"]:-abp-has(> a[target="_blank"] > img)
```

**Comment by awaluk** [comment]
Wygląda dużo lepiej, dzięki
