### ISSUE TITLE
mediaexpert.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#21380]
### Link bezpośredni 

https://www.mediaexpert.pl/

### Co trzeba zrobić, aby pojawił się błąd?
1. Wejdź na stronę https://www.mediaexpert.pl/
2. Brak logo.

### Moja konfiguracja 

**Przeglądarka internetowa:** Chrome

**Rozszerzenia i skrypty:** 

Adguard Extension + Adguard Extra + Polska Ciasteczkowa Zgoda

**Listy filtrów:** 
Ad Blocking:
AdGuard Base

Privacy:
AdGuard Tracking Protection

Social Widgets:
AdGuard Social Media

Annoyances:
AdGuard Annoyances,
I don't care about cookies

Language-specific:
Official Polish filters for AdBlock, uBlock Origin & AdGuard,
Polish Social Filters,
KAD - Anti-Scam,
Polish Annoyances Filters,
Polish Anti Adblock Filters,
AlleBlock,
Polish Anti-Annoying Special Supplement

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

![20221222-1671740526](https://user-images.githubusercontent.com/9846948/209219566-7ffe8935-f873-46d0-9bf4-aafa76fe10da.png)

![20221222-1671740632](https://user-images.githubusercontent.com/9846948/209219844-4aaf34d6-9705-4af1-ba92-c524fdfc2971.png)

Reguła psująca
```
##[class$="-ads"]
```

Fix 

```
mediaexpert.pl#@#[class$="-ads"]
```
albo dodanie domeny do istniejącej białej listy 😉

**Comment by krystian3w** [comment]
Logo wróciło - brak klasy w kodzie.

Pewnie problem wróci przy jakimś kolejnym dużym święcie, bo pewnie nie czytają zgłoszeń tutaj (lub testują zawsze bez blokerów treści).
