### ISSUE TITLE
mmorpg.org.pl

### ISSUE THREAD

**Issue by szyha** [MajkiIT/polish-ads-filter#21399]
### Zrzut ekranu 
![firefox_yvKwNws5Yb](https://user-images.githubusercontent.com/12976368/211017646-3b64f8dc-89ec-450c-8b9b-77fb85f8b902.png)

### Link bezpośredni 
https://mmorpg.org.pl/news/zobacz/star-citizen-chwali-sie-liczba-graczy-liczba-pracownikow-i-liczba-kont

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. Wejść na powyższą stronę.
2. Odświeżać stronę lub poprzeglądać artykuły dopóki nie zostanie wykryty adblock.

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Firefox 108.0.2

**Rozszerzenia i skrypty:** 
uBlock Origin 1.46.0
I still don't care about cookies 1.1.0
Polska Ciasteczkowa Zgoda 1.45.1

**Listy filtrów:** 
![firefox_P4Di8L4k85](https://user-images.githubusercontent.com/12976368/211019290-de6906a8-9bdc-4dd3-9196-5a86dd28ef5a.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Testowane na domyślnej konfiguracji uBlocka oraz Firefoxa z takim samym skutkiem.
Filtr, który naprawia błąd.
``@@||lib.wtg-ads.com/publisher/*$domain=mmorpg.org.pl``

**Comment by krystian3w** [comment]
@masterkia can you copy to filters or unberak for few next months?

**Comment by krystian3w** [comment]
So too many custom filter lists?

**Comment by krystian3w** [comment]
Yes, I don't use in same time uBo stock with enabled:

AG Base, AG Annoyances, AG social media, Fanboy Annoyances, AG Spyware, dandelionSprout lists, RU AdList, PUP and Anti Phishing by [curbengh](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue+author%3Acurbengh) and uknown anti-grab.

**Comment by krystian3w** [comment]
@szyha spróbuj wyłączyć ETP dla normalnych sesji:

https://support.mozilla.org/pl/kb/wzmocniona-ochrona-przed-sledzeniem-firefox-desktop

**Comment by krystian3w** [comment]
MajkiIT recommended that submissions should continue here on the blog post.

Maybe because of the number of stars and viewers Oleg did not get on his repo.
