### ISSUE TITLE
sjp.pwn.pl

### ISSUE THREAD

**Issue by przemo20** [MajkiIT/polish-ads-filter#21401]
Puste boxy po reklamach.

### Zrzut ekranu 

#&#x2060;1
![sjp pwn pl_sjp_macher;2480343 html](https://user-images.githubusercontent.com/22180480/211144129-475e54c4-263a-4a2f-9ed8-10d6cd0340b8.png)

#&#x2060;2
![sjp pwn pl_](https://user-images.githubusercontent.com/22180480/211144139-b31d321d-4154-4e6a-8a37-bcd778e2f86a.png)

#&#x2060;3
![sjp pwn pl_poradnia](https://user-images.githubusercontent.com/22180480/211144145-09511c26-3915-41b2-9fab-390fb1dc8799.png)

### Link bezpośredni 

https://sjp.pwn.pl/sjp/macher;2480343.html
https://sjp.pwn.pl/
https://sjp.pwn.pl/poradnia

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Google Chrome 108.0.5359.125 (64-bit)

**Listy filtrów:** 
1. uBlock filters
2. uBlock filters – Badware risks
3. uBlock filters – Privacy
4. uBlock filters – Quick fixes
5. uBlock filters – Resource abuse
6. uBlock filters – Unbreak
7. EasyList
8. EasyPrivacy
9. Online Malicious URL Blocklist
10. Peter Lowe’s Ad and tracking server list
11. POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
12. POL: Oficjalne polskie filtry przeciwko alertom o Adblocku

**Comment by krystian3w** [comment]
Jakby fail z przywracaniem reklam po stronie PWN (zakładając, że co 3 miesiące nie zmieniają metody osadzania).

**Comment by krystian3w** [comment]
Halo
