### ISSUE TITLE
messenger

### ISSUE THREAD

**Issue by rafalohaki** [MajkiIT/polish-ads-filter#21406]
![image](https://user-images.githubusercontent.com/20607107/212237850-126c29ba-8cbb-40ff-99f1-465b1ca512e2.png)

**Comment by krystian3w** [comment]
Lista jest martwa, twórcy nie nanieśli zmian od kiedy MajkiIT uruchomił jej konwersje:

https://github.com/MajkiIT/polish-ads-filter/blob/6de703dcd302c2b026677f29031c6312d32f8603/polish-pihole-filters/Ad_filter_list_by_Disconnect.txt

**Comment by hawkeye116477** [comment]
Aha, czyli nadal sam numerek jest podbijany, mimo, że brak zmian.

**Comment by krystian3w** [comment]
Niestety tak.

Jedynie nie wiem co za błędy w skryptach opróżniły plik kilka razy i bot to wysłał (być może serwer był z 3 razy offline).
