### ISSUE TITLE
Brak powiadomień serwisu (np. błąd polubienia) hejto.pl

### ISSUE THREAD

**Issue by Acrivec** [MajkiIT/polish-ads-filter#21404]
![obraz](https://user-images.githubusercontent.com/26365504/211164491-df4eae7b-51c5-4ccd-8e97-a8943566dae5.png)
Jest to zasada usuwająca belkę RODO/Cookies, jednakże jest blokowana w sposób 'wylewający dziecko razem z kąpielą'. 
Po wyłączeniu obu widocznych na screenie list (a wystarczy jedna włączona, dowolna) komunikaty strony działają poprawnie.

Z włączoną listą:
![obraz](https://user-images.githubusercontent.com/26365504/211164559-356aad21-5183-4e04-b66f-fef6ba46191e.png)

Z wyłączoną listą:
![obraz](https://user-images.githubusercontent.com/26365504/211164571-081834ef-2d96-4f2d-9b8d-bb9068016cab.png)

**Comment by kiboke** [comment]
@Acrivec could you please tell me what do I have to click to see the red message in the corner myself? I'll try to modify the cookie related filter for "I don't care about cookies". Thanks!

**Comment by mailing12** [comment]
You should register, login and add comments under any shared post and now click in zap : "⚡".

Pure CSS is compatible:

```adb
##footer + .fixed:not([class="fixed bottom-0 right-0 z-20 transition-transform transform p-2 max-w-sm w-full"])
```

Works in Chrome 105+ and Safari 15.4:

```adb
##footer + .fixed:has(button)

! Error bar uses SVG for "❌"
```

https://caniuse.com/?search=has

**Comment by mailing12** [comment]
Page started using `cmp.quantcast.com`.
