### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by luk1337** [MajkiIT/polish-ads-filter#21414]
W końcu jest nowy wykop, więc wypadałoby zastąpić obecne filtry tym: `wykop.pl##section[data-label^="ad: "]` ^.^

Wywala on puste boxy typu:
![image](https://user-images.githubusercontent.com/6830979/212916127-c5ffe81b-03ed-4dbf-b63a-738885d35f6e.png)
![image](https://user-images.githubusercontent.com/6830979/212916142-283b5c30-7158-41f4-92c2-0f5d2a2d3dda.png)
![image](https://user-images.githubusercontent.com/6830979/212916179-9e7f7a28-832c-46fb-abfd-0c59d32dbd1f.png)

**Comment by zniteckivr** [comment]
@luk1337 zestaw moich filtrów, które usuwają te moje puste boxy, może się przydać:

```
wykop.pl##.sidebar-1.pub-slot-wrapper
wykop.pl##.top.pub-slot-wrapper
wykop.pl##.sidebar-2.sticky.pub-slot-wrapper
wykop.pl##.stream-bottom.pub-slot-wrapper
wykop.pl##.stream-1.pub-slot-wrapper
wykop.pl##.stream-2.pub-slot-wrapper
```

**Comment by luk1337** [comment]
No mój jeden filtr usuwa je wszystkie.

**Comment by krystian3w** [comment]
Można próbować wersję "Luka", o ile nie będzie jak na Allegro zmieniana (mutacja `data-id` w coś innego np. `data-campaign`)

W schemacie "Zenita" powtarza się: `.pub-slot-wrapper` może to klasa specyficzna dla reklam "public ad" (jakby im Portugalczycy/Hiszpanie robili szablon):

publicidad https://pl.glosbe.com/s%C5%82ownik-polsko-hiszpa%C5%84ski/reklama
publicidade https://pl.glosbe.com/s%C5%82ownik-polsko-portugalski/reklama

**Comment by luk1337** [comment]
pub raczej od publication...

**Comment by irrelevantperson** [comment]
> Można próbować wersję "Luka", o ile nie będzie jak na Allegro zmieniana (mutacja `data-id` w coś innego np. `data-campaign`)
> 
> W schemacie "Zenita" powtarza się: `.pub-slot-wrapper` może to klasa specyficzna dla reklam "public ad" (jakby im Portugalczycy/Hiszpanie robili szablon) ["private ad" pewnie mają na localhoscie]:
> 
> publicidad https://pl.glosbe.com/s%C5%82ownik-polsko-hiszpa%C5%84ski/reklama publicidade https://pl.glosbe.com/s%C5%82ownik-polsko-portugalski/reklama
> 
> Nie wykluczam, że obie będą padać w tym samym czasie np. "-wrapper" stanie się "-section"/"-article".

no kolego się rozpędziłeś z tym portugalskim/hiszpańskim xD

**Comment by krystian3w** [comment]
To raczej tylko utrwalona wiedza praktycznie bezużyteczna (czekająca na demencję/Alzheimera) - znajomość kilku słów z tych języków mi się nie przydaje.

**Comment by krystian3w** [comment]
W sumie wpakowali się na minę, używając `.wykop` do stopki:

https://github.com/MajkiIT/polish-ads-filter/blob/69d8ac0c0eb979b0367502a9930904cc5b09e089/adblock_social_filters/adblock_social_list.txt#L739

**Comment by krystian3w** [comment]
Naprawione na poziomie AdGuard Base:

https://github.com/AdguardTeam/AdguardFilters/commit/0f7e80b82445f602f17f45dc031891722ae10c45 - ulepszona wersja "Zenita".

PR dla majkela może zrobić każdy, wystarczy w 3 miejscach podmienić datę w nagłówku i wysłać.
