### ISSUE TITLE
zyciorysy.info

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#21413]
Paczka POL coś za dużo blokuje i w efekcie rozwala stronę główną.

**Comment by krystian3w** [comment]
"Paczka Pol" brzmi jakbyś konkretny sklep nazwał źle działającym, bo mają 1 przeterminowany produkt w historii są na rynku ponad 50 lat.

**Comment by xxcriticxx** [comment]
@hawkeye116477 where are you?

**Comment by krystian3w** [comment]
Hawkeye raczej nie ma loginu i hasła do konta Majkela.

**Comment by xxcriticxx** [comment]
tak tylko pytlem czy @hawkeye116477 nasz dalej odwiedza
