### ISSUE TITLE
teleman.pl

### ISSUE THREAD

**Issue by 3hr80FEZwlir** [MajkiIT/polish-ads-filter#21433]
### Link bezpośredni 
https://www.teleman.pl/

### Co trzeba zrobić, aby pojawił się element albo błąd?
Na stronie nie działają odnośniki. Po wyłączeniu https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt strona działa normalnie.

### Moja konfiguracja 

Brave 1.47.186, Chromium: 109.0.5414.119 (Official Build) (64-bit)]

**Rozszerzenia i skrypty:** 
Oprócz domyślnego blokowania zawartości Brave żadne, które wpływają na stronę Teleman.pl.

**Listy filtrów:** 
1. Domyślne Brave
2. EasyList-Cookie List - Filter Obtrusive Cookie Notices
3. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
4. Oficjalne Polskie Filtry Przeciwko Alertom o Adblocku
5. Oficjalne Polskie Filtry Przeciwko Alertom o Adblocku - Uzupełnienie
6. https://alleblock.pl/alleblock/alleblock.txt
7. https://fanboy.co.nz/fanboy-antifonts.txt
8. https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt
9. https://raw.githubusercontent.com/ScottHelme/revocation-endpoints/master/crl.txt
10. https://raw.githubusercontent.com/ScottHelme/revocation-endpoints/master/ocsp.txt

**Comment by xxcriticxx** [comment]
@3hr80FEZwlir co centralnie nie dziala na tej stronie?

**Comment by 3hr80FEZwlir** [comment]
> @3hr80FEZwlir co centralnie nie dziala na tej stronie?

"Centralnie"...? Odnośniki nie reagują na kliknięcia.

**Comment by krystian3w** [comment]
Przywracanie pop-upa:
```adb
teleman.pl#@#.qc-cmp-cleanslate
```

Pewnie trzeba zmienić na:

```adb
||cmp.quantcast.com/choice/*$script,domain=dobryslownik.pl|gry-online.pl|instrukcjaobslugipdf.pl|kalendarz-365.pl|medme.pl|mp.pl|polskieradio24.pl|termedia.pl|teleman.pl
! --------------------------------------------------------------------------------------------------------------------------------------------------------->  ^^^^^^^^^^^ < ------------

**Comment by xxcriticxx** [comment]
po zaakceptowaniu RODO wszystko dziala tak jak @krystian3w pisal

**Comment by krystian3w** [comment]
Najgorzej, że generyk sieciowy może psuć "wPolityce.pl" i kij wie co polskiego jeszcze.
