### ISSUE TITLE
haloursynow.pl

### ISSUE THREAD

**Issue by dabiOW** [MajkiIT/polish-ads-filter#21448]
<img width="751" alt="image" src="https://user-images.githubusercontent.com/4173488/218709565-c174a3b6-e82e-4094-ab75-111cdf16a5e9.png">

[Przykładowy artykuł ](https://haloursynow.pl/pl/11_wiadomosci/740_inwestycje/21854_trzaskowski-zapowiada-5-linii-metra-w-warszawie-do-2050-roku.html)

### Co trzeba zrobić, aby pojawił się element albo błąd?
1. Otworzyć dowolny artykuł na haloursynow.pl

### Moja konfiguracja 
**Przeglądarka internetowa:** Chrome 110

**Rozszerzenia i skrypty:** 

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. Oficjalne polskie filtry przeciwko alertom o Adblocku 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Jeszcze przy przewijaniu nagle zachodzi przeładowanie strony i wracamy na stronę główną...
