### ISSUE TITLE
eglos.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#21447]
### Zrzut ekranu 
![image](https://user-images.githubusercontent.com/18230443/218545284-7996227f-2702-4484-9711-75682344d609.png)

### Link bezpośredni 
https://eglos.pl/ogloszenia

Strona dodaje klase `ads-list` do listy ogłoszeń, aby wymusić wyłączenie adblocka.

**Comment by krystian3w** [comment]
To nie brzmi po polsku.

W blame można sprawdzić kto jest autorem filtru generycznego `##.ads-list` i pewnie nie będzie to "webmaster" domeny.

**Comment by krystian3w** [comment]
Jak MajkiIT nie skopiuje do siebie:

`eglos.pl#@#.ads-list`

 to nie wiadomo kiedy naprawi to OlegwUkr.
