### ISSUE TITLE
add from adguard spyware 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2145]
```
||adstat.4u.pl^$third-party
||gemius.pl^$third-party
||gostats.pl^$third-party
||stat.4u.pl^$third-party
||stat.pl/$third-party
||ut.o2.pl^
||quartic.pl/api/event^
||quartic.pl/t.php^
```

**Comment by MajkiIT** [comment]
spyware?

**Comment by xxcriticxx** [comment]
tak wyciagnelem te linky z adguard spyware listy

**Comment by xxcriticxx** [comment]
@F4z zepsuje to cos? pozna dodac? chyba wszystkie sa na statsy stron. gemiuz moze powodowac adblock?

**Comment by MajkiIT** [comment]
@xxcriticxx ale to nie spyware ....

**Comment by xxcriticxx** [comment]
wiem ale na adguardzie jest to na spyware liscie 

@MajkiIT check email

**Comment by MajkiIT** [comment]
@xxcriticxx przejrzę to co napisałeś i dzisiaj dodam. 
Odpisałem na maila

**Comment by xxcriticxx** [comment]
@MajkiIT email

**Comment by F4z** [comment]
Jeśli się nie mylę, to `Adguard Spyware Filter` (Filtr elementów szpiegujących) opiera się o `EasyPrivacy`.
Pięć pierwszych reguł już jest na liście `EasyPrivacy`, ale myślę, że pozostałe można dodać.

`||ut.o2.pl^`
`||quartic.pl/api/event^`
`||quartic.pl/t.php^`

**Comment by xxcriticxx** [comment]
od `stat.pl/$third-party` do dolu niego niema na `EasyPrivacy`

@F4z na adugard spyware jest wiece .pl ale niewiem czy te reguly sa potrzebne. zerkniesz?

**Comment by F4z** [comment]
Na `EasyPrivacy` jest `||stat.pl^$third-party` czyli w zasadzie to samo co `||stat.pl/$third-party`
Pozostałe reguły z `.pl` z `Adguard Spyware Filter` to wyjątki, raczej nie są potrzebne.

**Comment by MajkiIT** [comment]
Dodane dzięki
