### ISSUE TITLE
fandroid.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2147]
ad block 

`http://www.fandroid.com.pl/nokia-3-5-6-targi-mwc-3310-premiera,13906`

![capture](https://cloud.githubusercontent.com/assets/15007183/22904177/68cb0740-f209-11e6-8973-66361af45d34.PNG)

**Comment by F4z** [comment]
Na adblocka:
`||fandroid.com.pl/wp-content/uploads/jrZhZDbEbjaO/fFNLiNqpPAyb.js$script`

Jeszcze widzę reklamę.

![image](https://cloud.githubusercontent.com/assets/11742596/22904352/6bc43f42-f23c-11e6-8ce3-56ec36580b01.png)

Na przykład:
`fandroid.com.pl##.g1-ads`

**Comment by MajkiIT** [comment]
@F4z Dzięki
