### ISSUE TITLE
lubiepowietrze.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2148]
`http://lubiepowietrze.pl/uzywasz-adblocka`

![capture](https://cloud.githubusercontent.com/assets/15007183/22904518/c91b0a5e-f20a-11e6-92b4-926c8ee87436.PNG)

**Comment by F4z** [comment]
@xxcriticxx przekierowało Cię tam, czy po prostu znalazłeś link do tego?
Pytam, bo jest już dodana odpowiednia reguła na polskiej liście dla tej strony i powinna działać.

**Comment by xxcriticxx** [comment]
mozliwe niewiem wyskoczylo znowu
