### ISSUE TITLE
sport.interia.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#21482]
resztka ( u góry ) : https://sport.interia.pl/ms-planica-2023/news-mistrzostwa-swiata-planica-2023-gdzie-ogladac-w-telewizji-i-,nId,6597236

![int planica](https://user-images.githubusercontent.com/23176832/221861997-4dadacce-f8be-4ef0-8e45-a4a7c00cd96f.png)

**Comment by krystian3w** [comment]
Paski nawigacyjne przypina tylko Ultra Web Annoyances jak jako osobne zgłoszenie zaproponujesz zweryfikowany kod.

Jak wkleisz się do mega wątku, w którym mati "KonoromiHimaries" prosi o przywrócenie kilka💯 domen polskich to się pewnie nie doczekasz.

uAssets niby też może jak nie będą trącić nosem, że PAF ma zacząć się tym na nowo zajmować lub wkleić to do:

- `adblock_ublock.txt` i `adblock_adguard.txt`

**Comment by krystian3w** [comment]
Pewnie źle chwytasz i skryptlet `rc` i "remove-class" odpada (strona dodaje i skacze wszystko).
