### ISSUE TITLE
netgear.com/pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#21498]
( na dole ) oraz : https://accounts.netgear.com/login?redirectUrl=https:%2F%2Fmy.netgear.com%2Fdefault.aspx%3FReturnUrl%3Dhttp:%2F%2Fmy.netgear.com%2Fcases.aspx ( po prawo )

**Comment by krystian3w** [comment]
Strona logowania nie ma polonizacji...
