### ISSUE TITLE
kinowolnosc.pl

### ISSUE THREAD

**Issue by jklawiter** [MajkiIT/polish-ads-filter#21497]
### Zrzut ekranu 
![obraz](https://user-images.githubusercontent.com/52069843/222154181-8a93b066-771f-4f7e-b241-9ad3d5b2181b.png)

### Link bezpośredni 
https://kinowolnosc.pl/

### Co trzeba zrobić, aby pojawił się błąd?
1. wejść na kinowolnosc.pl
2. z włączonym filtrem easylist polska
3. nie widać na górze po środku pola wyszukiwania w serwisie 

### Moja konfiguracja 

**Przeglądarka internetowa:** Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0

**Rozszerzenia i skrypty:** AdGuard

**Listy filtrów:** 
1. Oficjalne polskie filtry dla AdBlock, uBlock Origin i AdGuard
Polski dodatek do EasyList.
2. Polski filtr przeciwko alertom o Adblocku
Oficjalne polskie filtry przeciwko alertom Adblock.
3. Podstawowy filtr AdGuard
EasyList + podstawowy filtr AdGuard. Te filtry są niezbędne do wysokiej jakości blokowania reklam.
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
kinowolnosc.pl to polska instancja sieci PeerTube (wolna alternatywa dla serwisów jak youtube czy vimeo). Po włączeniu w AdGuard zestawu:

Oficjalne polskie filtry dla AdBlock, uBlock Origin i AdGuard
Polski dodatek do EasyList.
wersja: 2.0.14.84 zaktualizowano: 1 marca 2023 14:21
[Wróć do strony głównej](https://github.com/MajkiIT/polish-ads-filter#polish-filters-for-adblock-ublock-origin--adguard)
#ads
#recommended
#lang:pl

znika pole wyszukiwania w serwisie.

Filtr znajduje się w dodatku w sekcji filtry/specyficzne językowe/ 

Przywróciłem domyślne ustawienia dodatku, wyłączałem filtry sztuka po sztuce i jestem pewien, że to ta lista. Nie wiem jak szukać który to konkretnie filtr odpowiada za błędne działanie zestawu.

**Comment by krystian3w** [comment]
Można użyć rejestratora/loggera AdGuard. Chociaż mnie szybciej było użyć DOM inspektora z uBo.

@MajkiIT błędnie działa:

https://github.com/MajkiIT/polish-ads-filter/blob/3f6eb34121df70821ce954f95d0f59cdfb99b964/polish-adblock-filters/adblock.txt#L264

Sugerowane działania:

- kasacja filtru
- dodanie domeny z ~
- użycie generycznego: `:not(#typeahead-container)`

**Comment by krystian3w** [comment]
Jak podobny błąd ma https://github.com/easylistpolish/easylistpolish to warto zrobić im osobne zgłoszenie, bo przywołanie po nicku może uciec gdy oznaczą jako "zakończone" zamiast "odcztytane" (nie kasuj z listy webowych powiadomień) [bardzo opcjonalnie używają tylko mejlów do powiadomień i nie ma takiego dylematu na misclick].

**Comment by jklawiter** [comment]
> Sugerowane działania: 
>     * kasacja filtru _(to już +13 zepsucie a nie można policzyć ile domen objęto z pomocą "not")_
>     * dodanie domeny z `~`
>     * użycie generycznego: `:not(#typeahead-container)` _(jak przejdą na model domeny co działa tylko 24 godziny i potem przekierowuje na nowy adres - popularne w Turcji)_

Jeśli to ma dotyczyć serwisu kinowolnosc.pl to nie sądzę, aby coś się tam miało dziać z domeną. Ale jednocześnie jest to jeden z wielu serwerów sieci PeerTube (https://joinpeertube.org/) opartych o to samo oprogramowanie więc generujących ten sam kod czyli… podpadających pod te same filtry. Ja zwróciłem uwagę na instancję kinowolnosc.pl bo tam mam konto, ale kolejna w Polsce to np https://tube.midov.pl/ i tam objawy są identyczne. Pole wyszukiwania znika po aktywacji filtra: 
Oficjalne polskie filtry dla AdBlock, uBlock Origin i AdGuard
Polski dodatek do EasyList.
wersja: 2.0.14.84 zaktualizowano: 2 marca 2023 13:04

Na ten moment sieć PeerTube to 1300 serwerów, w Polsce niewiele ale pewnie powstaną.

**Comment by krystian3w** [comment]
Kasacja sprawia, że filtr znika z aktualizacją listy.

Dopisanie domeny z `~` jak widać odpada, skoro strony na tym samym CMS zaczną powstawiać "jak grzyby po deszczu" i pewnie nie nadążymy ich dopisywać, wtedy dopisanie odpowiedniego `:not(` wykluczy ukrywanie aż CMS nie zmieni nazwy ID dla elementu z "typehead" na np. "type-head" i znowu zacznie znikać masowo wyszukiwarka). 

---

"słowniczek":

* CMS - https://pl.wikipedia.org/wiki/System_zarz%C4%85dzania_tre%C5%9Bci%C4%85
* `:not(` w CSS i AdBlockach: https://developer.mozilla.org/en-US/docs/Web/CSS/:not
