### ISSUE TITLE
legiobiznes.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2149]
ad block 

Proszę dodaj legiobiznes.pl, legiobiznes.pl/I, ogloszenia.legiobiznes.pl

![capture](https://cloud.githubusercontent.com/assets/15007183/22904634/1e6350d4-f20b-11e6-8efa-c3cfeaf11beb.PNG)

**Comment by F4z** [comment]
@xxcriticxx przekierowało Cię tam, czy po prostu znalazłeś link do tego?
Pytam, bo jest już dodana odpowiednia reguła na polskiej liście dla tej strony i powinna działać.

**Comment by xxcriticxx** [comment]
ok

**Comment by xxcriticxx** [comment]
zamykamy ten temat
