### ISSUE TITLE
katalogi.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2151]
reklama 

`http://katalogi.pl/237140-zestawienie-polecanych-laptop%C3%B3w-15617-cala.html`

![capture](https://cloud.githubusercontent.com/assets/15007183/22905945/4574232e-f210-11e6-80ff-0174f4fb0b55.PNG)

**Comment by MajkiIT** [comment]
`katalogi.pl###post_id_`
