### ISSUE TITLE
crazynauka.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#2154]
Adblock Detected Warning
![screenshot_20170214_111715](https://cloud.githubusercontent.com/assets/9846948/22924897/2a93efe8-f2a7-11e6-8f7a-ef8dae49cdf5.png)

**Comment by MajkiIT** [comment]
`crazynauka.pl#@##adsense`

**Comment by F4z** [comment]
Można też zablokować ten skrypt:
`||crazynauka.pl/wp-content/uploads/YCSSWOSUWCRX/OfgoiqLbscOY.js$script`

**Comment by MajkiIT** [comment]
@F4z boję się, że zaraz ten skrypt zmienią.

**Comment by F4z** [comment]
@MajkiIT ok.
Oni tam używają jakiegoś AdBlock Notify, podobnie jak tu https://github.com/MajkiIT/polish-ads-filter/issues/2149 https://github.com/MajkiIT/polish-ads-filter/issues/1897 i na tej stronie przez miesiąc nie zmienili tego skryptu, ale rozumiem :)

**Comment by MajkiIT** [comment]
@F4z już zrobiłem tak jak chciałeś. Ogarnąłem temat. Jeszcze raz dzięki.
