### ISSUE TITLE
pp.funhub.pl

### ISSUE THREAD

**Issue by slimacek** [MajkiIT/polish-ads-filter#2156]
@MajkiIT 
Proszę o usunięcie reguły:
`##a[href^="http://pp.funhub.pl/api/click/"]`

Powyższa reguła powoduje wycinanie ze stron linków do programu partnerskiego PP Funhub oraz wycinanie linków z samej strony panelu PP Funhub, co utrudnia korzystanie z niej.

Jeśli na jakichś stronach pojawiają się agresywne reklamy z takim podlinkowaniem, sugeruję dodawanie reguł dotyczących samego wyświetlania tych reklam, a nie linków, pod które kierują.

Z góry dziękuję.

**Comment by MajkiIT** [comment]
Powodem jest to https://github.com/MajkiIT/polish-ads-filter/issues/2026 . Możemy dodać domenę .
