### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2157]
Może ktoś coś poradzić z komunikatem "reklamy nie są złe" na komputerswiat.pl i zrobić coś, by filmiki nie odtwarzały się automatycznie na tej stronie?

**Comment by F4z** [comment]
Niedawno widziałem ten komunikat i jeśli się nie mylę, to było przez tę regułę:
`komputerswiat.pl##.adsbygoogle`
ale teraz tego nie widzę, więc nie jestem w stanie sprawdzić, czy "odblokowanie" tego działa.
`komputerswiat.pl#@#.adsbygoogle`
Niestety po dodaniu tej reguły zostaną puste miejsca po reklamach i w tym przypadku najprawdopodobniej żeby zmniejszyć te miejsca trzeba by było użyć reguł z `:style()`.
Swoją drogą czasami wyczyszczenie ciasteczek też działa.

Jeśli chodzi o automatycznie odtwarzające się filmy, to tutaj raczej potrzebny jest skrypt.

**Comment by xxcriticxx** [comment]
script mozna zamowic z @X01X012013

**Comment by X01X012013** [comment]
@xxcriticxx Hum, I'm not getting any block screen. 
![image](https://cloud.githubusercontent.com/assets/7283682/22956004/8ef6ea0a-f2dc-11e6-906d-4145d0178082.png)

**Comment by X01X012013** [comment]
Also I only speak English and Chinese, I don't know what you guys wrote.

**Comment by xxcriticxx** [comment]
@X01X012013 sorry my friend i am not getting any ad block at this time as well. our users looking for solution for video not to auto play i dont know if you can help with this.

**Comment by X01X012013** [comment]
@xxcriticxx 
Hum, we could patch the player... @szymon1118 , is there a better way?

**Comment by xxcriticxx** [comment]
@F4z you can find ad block on komputerowy.pl by accessing the website from onet.pl. this rule `komputerswiat.pl#@#.adsbygoogle` works with no problem. 

before:

![before](https://cloud.githubusercontent.com/assets/15007183/22956984/5d5c06b2-f2f3-11e6-9e04-99dc322a0d41.PNG)

after with empty box after ads:

![capture](https://cloud.githubusercontent.com/assets/15007183/22957003/6b78521e-f2f3-11e6-8fb9-673650a6459e.PNG)

**Comment by xxcriticxx** [comment]
@X01X012013 to recreate ad block please go to `www.onet.pl` on the right side find `TECHNOLOGIE I GRY` after that hit Nokia 3310 this will redirect you to komputerswiat.pl and create ad block 

attaching picture of what to click on onet.pl just in case:

![capture](https://cloud.githubusercontent.com/assets/15007183/22957086/0daa5564-f2f4-11e6-927f-e41b4df39ea8.PNG)

**Comment by xxcriticxx** [comment]
@X01X012013 right now is 2:29 AM in Poland i don't think @szymon1118 is up

**Comment by X01X012013** [comment]
@xxcriticxx 
Nope, I'm not getting block screens. Are you using Adblock Plus or uBlock Origin? 

I don't know what the time is in Poland, but he will be up eventually, there is no harm tagging him now.

**Comment by xxcriticxx** [comment]
ublock origin i am in usa maybe thats why i get ad blcok

**Comment by X01X012013** [comment]
@xxcriticxx I don't think that's the issue. Do you have Adblock Warning Removal List checked?

**Comment by xxcriticxx** [comment]
@X01X012013 yes i do but at home i also use host file i will test at work today see if i can get ad block

**Comment by hawkeye116477** [comment]
Co do tego komunikatu, to po aktualizacji filtru i zjedzeniu ciasteczek, już się nie pojawia. A na autoplay znalazłem radę, zainstalowałem rozszerzenie AutoPlay Toggle do Cyberfoxa, przynajmniej częściowo to rozwiązało problem, automatycznie się nie odtwarza, ale teraz wcale żaden filmik nie chce się załadować. Jeśli chcę żeby się załadował, to muszę ponownie włączyć autoplay za pomocą tego rozszerzenia.

**Comment by MajkiIT** [comment]
@hawkeye116477 ale update nie dotyczył tej strony.

**Comment by hawkeye116477** [comment]
Chyba za wcześnie powiedziałem, jeśli ponownie wyczyści się ciasteczka to komunikat może znowu się pojawić, ale potem znowu jak się wyczyści ciasteczka, to znika do czasu kolejnych wyczyszczeń (czyli jeśli wyczyszczę ciasteczka to może się pojawić lub zniknąć). 
Więc jeśli ten komunikat się wyświetli to trzeba będzie zjeść parę ciastek, by zniknął :)

**Comment by xxcriticxx** [comment]
@hawkeye116477 ciasteczka naczym?

**Comment by hawkeye116477** [comment]
@xxcriticxx Ciasteczka strony komputerswiat.pl na przeglądarce Cyberfox.

**Comment by xxcriticxx** [comment]
@hawkeye116477 filtry masz nasze do ciastek?

**Comment by hawkeye116477** [comment]
@xxcriticxx Tak

**Comment by xxcriticxx** [comment]
@hawkeye116477 wiec jaki jest problem? dalej masz wiadomosc o ciastkach na stronie?

**Comment by hawkeye116477** [comment]
Nie, wiadomość nie dotyczy ciastek, chodzi mi o ten komunikat "reklamy nie są złe". Po wyczyszczeniu ciastek nagle on znika, ale jeśli potem znowu zjem ciastka, to znowu się pojawia, ale nie zawsze tak jest.

**Comment by xxcriticxx** [comment]
dodaj sobie to co @F4z pisal albo wyloncz drugi porgram do blokowania reklam

**Comment by hawkeye116477** [comment]
Nie mam drugiego programu do blokowania. Ta reguła pomaga, ale jest niestety tak jak @F4z pisał, czyli puste miejsca zostają. Ale przynajmniej komunikatu już nie ma. Dzięki.

**Comment by xxcriticxx** [comment]
plugin sprawdz wczoraj byl porblem z ublock extras? host file masz?

**Comment by hawkeye116477** [comment]
Jeśli chodzi o uBlock Origin Extra to nie posiadam, ale on chyba jest z tego co kojarzę tylko dla przeglądarek typu Chromium, a ja mam Cyberfox (Firefox). Hosts file też nie mam.

**Comment by xxcriticxx** [comment]
masz cos xtr w my rules?

**Comment by hawkeye116477** [comment]
Jedynie to dodałem co @F4z polecał: komputerswiat.pl#@#.adsbygoogle . Więcej nic.

**Comment by xxcriticxx** [comment]
kasowales cookies i browsing history?

**Comment by hawkeye116477** [comment]
Tak i nie pomogło. Pewnie jakaś kolejna reguła by się przydała, by teraz usunąć te puste miejsca po reklamach.

**Comment by xxcriticxx** [comment]
żeby zmniejszyć te miejsca trzeba by było użyć reguły z :style().

@F4z sie pokaze to napisze co mial na mysli

**Comment by F4z** [comment]
Te puste miejsca można zmniejszyć na przykład przy użyciu takiej reguły (działa w uBlocku Origin i Adguardzie):
`komputerswiat.pl##.adsbygoogle:style(height: 1px !important;)`

**Comment by MajkiIT** [comment]
@F4z dzięki, wrzucimy to do ublockowych filtrów.

**Comment by hawkeye116477** [comment]
Te dwa filtry, pomogły. Dzięki.
komputerswiat.pl#@#.adsbygoogle
komputerswiat.pl##.adsbygoogle:style(height: 1px !important;)
