### ISSUE TITLE
forum.gazeta.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#21588]
test link:
https://forum.gazeta.pl/forum/w,11918,160450645,160450645,Polska_telewizja_w_USA.html

Droga Użytkowniczko, Drogi Użytkowniku, jeśli wyrazisz zgodę klikając AKCEPTUJĘ, Agora S.A. oraz jej Zaufani Partnerzy będą przetwarzać Twoje dane osobowe takie jak adresy IP, adresy e-mail czy identyfikatory plików cookie do celów marketingowych, w szczególności na potrzeby wyświetlania reklam dopasowanych do Twoich zainteresowań i preferencji w serwisach Agora S.A., jej aplikacjach i w Internecie. Wyrażenie zgody jest dobrowolne. Jeśli nie chcesz wyrazić zgody, chcesz ograniczyć jej zakres lub chcesz wycofać zgodę uprzednio udzieloną przejdź do „Ustawień Zaawansowanych”. Jeśli podstawą przetwarzania Twoich danych jest uzasadniony interes administratora, masz prawo wyrazić sprzeciw, aby to zrobić przejdź do „Ustawień Zaawansowanych”. Więcej informacji znajdziesz w dokumencie[Polityka Prywatności Gazeta.pl](https://pomoc.gazeta.pl/pomoc/7,154322,8856779,ochrona-prywatnosci.html)Poprzez kliknięcie AKCEPTUJĘ wyrażasz zgodę na zainstalowanie i przechowywanie plików typu cookie Agora S.A. oraz jej Zaufanych Partnerów na Twoim urządzeniu końcowym. Możesz w każdej chwili zmienić ustawienia plików cookie za pomocą przycisku „Zgody” znajdującego się w stopce serwisu. Zmiana ustawień plików cookie możliwa jest także za pomocą ustawień przeglądarki.My oraz nasi Zaufani Partnerzy możemy przetwarzać dane osobowe w następujących celach: Użycie dokładnych danych geolokalizacyjnych. Aktywne skanowanie charakterystyki urządzenia do celów identyfikacji. Przechowywanie informacji na urządzeniu lub dostęp do nich. Spersonalizowane reklamy i treści, pomiar reklam i treści, opinie odbiorców, rozwój produktu. Lista Zaufanych Partnerów

**Comment by krystian3w** [comment]
Zamyka go PCZ, bo na głównej zdarzyć się może zablokowane wideło.
