### ISSUE TITLE
search topic 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2159]
@MajkiIT mozesz dodac search topic keywords to tego repo? nopinam obrazek oco mi chodzi.

![capture](https://cloud.githubusercontent.com/assets/15007183/22980944/f5926e56-f368-11e6-8408-072384225412.PNG)

**Comment by MajkiIT** [comment]
zaraz zerknę

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z dodałem, jeśli macie inne pomysły to napiszcie.

**Comment by xxcriticxx** [comment]
```
pl
blocker 
ad-blocker 
filtry 
cookies 
reklamy
ciasteczka
polish-ads-filters
```
