### ISSUE TITLE
nostalgia.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#21617]
( u góry )

**Comment by krystian3w** [comment]
Napis jest duszkiem CSS, może @hawkeye116477 wymyśli jak to zamazać prostokątem w CSS.

**Comment by hawkeye116477** [comment]
Skoro to jest jako obraz/tło wraz z resztą przydatnych elementów, to raczej nic nie wymyślę i można zamknąć.
