### ISSUE TITLE
zeberka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2165]
jakies resztki czegos 

`http://www.zeberka.pl/art/najpierw-kylie-teraz-kim-zobaczcie-co-na-siebie-wlozyla-foto-44484`

![capture](https://cloud.githubusercontent.com/assets/15007183/23086403/b5664e32-f53a-11e6-8e6d-a77bc1bf832c.PNG)

**Comment by MajkiIT** [comment]
`||exs.pl/embed*.php$script,domain=www.zeberka.pl`
