### ISSUE TITLE
Yanosik app

### ISSUE THREAD

**Issue by jacc555** [MajkiIT/polish-ads-filter#21654]
Aplikacja Yanosik wyświetla baner reklamowe o 
 - warsztatach motoryzacyjnych w pobliżu.
[Warsztaty](https://warsztaty.yanosik.pl/warsztat/bialystok/pomoc-drogowa-smol-hol/19496) 

- o restauracjach w pobliżu
[Restauracje](https://mysubway.pl/wielkicezar?utm_source=Yanosik&utm_medium=Yanosik_POI&utm_campaign=SUB_Great_Caesar) 

![Screenshot_20230414_141412_Yanosik](https://user-images.githubusercontent.com/70823330/232043926-54e1f9fa-2883-4d9d-a468-b129156dceb8.jpg)

**Comment by krystian3w** [comment]
Raczej HOSTS, bo pewnie nie używasz AdGuard by ruszyła lista dla "uBlock Origin".

**Comment by jacc555** [comment]
Używam AdGuard
Coś mam dograć?

**Comment by krystian3w** [comment]
Możesz sprawdzić to:

```adb
||mobi.yanosik.pl^app=pl.neptis.yanosik.mobi.android,important
```

dodane do reguł własnych w aplikacji AdGuard.

Przy czym filtr jest stary: https://github.com/StevenBlack/hosts/issues/1799 i mogli zmienić miejsce hostowania grafik - wtedy w logach AdGuard musisz znaleźć najnowszą domenę/ścieżkę.

**Comment by krystian3w** [comment]
Możesz sprawdzić to:

```adb
||mobi.yanosik.pl^$app=pl.neptis.yanosik.mobi.android,important
```

dodane do reguł własnych w aplikacji AdGuard.

Przy czym filtr jest stary: https://github.com/StevenBlack/hosts/issues/1799 i mogli zmienić miejsce hostowania grafik - wtedy w logach AdGuard musisz znaleźć najnowszą domenę/ścieżkę.

**Comment by hawkeye116477** [comment]
Tyle, że na AdGuarda trzeba mieć wykupioną subskrypcję, by blokował we wszystkich aplikacjach, inaczej tylko przeglądarki internetowe są obsługiwane.
