### ISSUE TITLE
inpost.pl

### ISSUE THREAD

**Issue by przemo20** [MajkiIT/polish-ads-filter#21656]
Pozostałości po „reklamie”:
- widoczny przycisk X
- wyciemnienie ekranu/strony
- dwa razy musisz kliknąć na iksie, by się pozbyć tego pop-upa / tych pop-upów

### Zrzut ekranu 

Z włączonym uBlockiem:
![Przechwytywanie zawartości sieci Web_15-4-2023_101651_inpost pl](https://user-images.githubusercontent.com/22180480/232200496-14a9f844-5c17-4584-92ca-d98b705c4431.jpeg)

Z wyłączonym uBlockiem:
![Przechwytywanie zawartości sieci Web_15-4-2023_101442_inpost pl](https://user-images.githubusercontent.com/22180480/232201099-68ecf557-cc5d-4829-a80d-7dfd075ed8a7.jpeg)

### Link bezpośredni 

https://inpost.pl/sledzenie-przesylek?number=<Numer_przesyłki> (zamienić `<Numer_przesyłki>` na jakiś prawidłowy numer przesyłki)

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
1. Wyczyść historię przeglądania w przeglądarce (ciasteczka itp.) LUB otwórz okno prywatne/incognito
2. Odwiedź podany wyżej adres URL (w miejsce `<Numer_przesyłki>` wprowadź prawidłowy number przesyłki)
3. Zaakceptuj informację o ciasteczkach („Stosujemy pliki cookie w celu zapewnienia prawidłowego funkcjonowania serwisu”...)
4. Przesuń kursor myszy na pasek adresu przeglądarki (w tym momencie powinien wyskoczyć pop-up)

### Moja konfiguracja 
**Przeglądarka internetowa:** 
Firefox 112.0 (64-bit)
**Rozszerzenia i skrypty:** 

**Listy filtrów:** 
1. uBlock filters
2. uBlock filters – Badware risks
3. uBlock filters – Privacy
4. uBlock filters – Quick fixes
5. uBlock filters – Resource abuse
6. uBlock filters – Unbreak
7. EasyList
8. EasyPrivacy
9. Online Malicious URL Blocklist
10. Peter Lowe’s Ad and tracking server list
11. POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
12. POL: Oficjalne polskie filtry przeciwko alertom o Adblocku

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Prościej by było podać filtr na wycięcie tła, skoro nie używasz Polskie Filtry Elementów Irytujących (jakie wycięły by pop-up z pominięciem tła).

**Comment by krystian3w** [comment]
I na takim linku nie mogę odtworzyć:

https://inpost.pl/sledzenie-przesylek?number=643394209340173125458329

Wątpię, że MajkiIT coś specjalnie zamówi by wyciąć w ciągu 74 dni.

**Comment by przemo20** [comment]
@krystian3w Spróbuj z tym linkiem: https://inpost.pl/sledzenie-przesylek?number=521000016696513032160125

**Comment by krystian3w** [comment]
U mnie wtedy pop-up zostaje i trzeba go wyciąć czymś takim:

```adb
#?#div.snrs-modal-wrapper:-abp-has([href*="/przekierowanie-paczki-kurierskiej-w-aplikacji-inpost-mobile"])
```

czyli kij wie co ci wycina grafikę/link.
