### ISSUE TITLE
filmydokumentalne.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2166]
przejrzyj ktos dla mnie to strone i filtry sprawdzi jakos chodzi wolno. jakis player sie otwiera na pol ekranu

**Comment by MajkiIT** [comment]
U mnie wydaje się ok. Filmy lecą z YT. A może hosts Ci coś blokuje?

**Comment by xxcriticxx** [comment]
chyba tak i jakis player sie otwiera na cala strone

**Comment by MajkiIT** [comment]
a masz flasha?

**Comment by xxcriticxx** [comment]
@MajkiIT mam tylko ustawilem tak aby pytalo jak chce wystartowac plugin

**Comment by MajkiIT** [comment]
@xxcriticxx gdzie klikasz, że pojawia Ci się coś takiego?

**Comment by xxcriticxx** [comment]
@MajkiIT nigdzie otwieram strone w chromie i taki player mi sie otwiera

**Comment by xxcriticxx** [comment]
jest good mozna dodac
