### ISSUE TITLE
olx.pl   -   ( grupa )

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#21662]
to samo, na:

https://www.otomoto.pl/

https://www.otodom.pl/

**Comment by krystian3w** [comment]
Efekt przekonania Kiboke do kasacji generycznego `###onetrust-consent-sdk`.

Przy czym i my nie możemy generycznie blokować, bo czasem nie działa wideo na stronie lub dziwną metodą blokuje komunikat przewijanie lub inne pop-upy.
