### ISSUE TITLE
agora.pl   -   ( grupa )

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#21667]
https://www.gazeta.pl/

https://www.tokfm.pl/

https://magazyn-kuchnia.pl/

https://czterykaty.pl/

https://www.edziecko.pl/

https://haps.pl/

https://moto.pl/

https://www.plotek.pl/

https://www.sport.pl/

https://avanti24.pl/

https://ugotuj.to/

https://infozdrowie24.pl/

https://moto-wiadomosci.pl/

https://dyskusje24.pl/

https://www.gazeta.tv/

https://wpodrozy24.pl/

https://hapsvod.pl/

https://sport.gwar.pl/

**Comment by krystian3w** [comment]
Część jest w dodatku:

https://github.com/FiltersHeroes/PolishCookieConsent/blob/b5633083547e2a83f8860efb36d77deda6831666/src/cookieBase/PCB.txt#L71 (gazeta, tokfm, edziecko, haps, moto, sport, ugotuj, infozdrowie24, dyskusje24)

 
 bo ich RODO blokuje np. wideo a nie mamy 100 tysięcy lat na naprawę standardowym arsenałem uBo.

Jak nie działa tam klikanie to sugeruję ręcznie zaktualizować bazę a potem zreinstalować dodatek w tym "Comodo Dragon".

---

Awaryjnie można dodać podstrony jak ostatnio #21588 gdzie nie ma praktycznie użytecznego wideo (w treści posta się nie da osadzić). Ale takich będzie niewiele a nie podoba mi się pomysł `peace2000` z szukaniem na stronie tagów `video` i przy braku ukrywać (filtr będzie mulący dla Firefox i Chrome 88-104).
