### ISSUE TITLE
support.zoom.us/hc/pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#21678]

**Comment by xxcriticxx** [comment]
to raczej nie pl stonra

**Comment by blocker999** [comment]
niewiem ale strona jest polsku

https://support.zoom.us/hc/pl

**Comment by krystian3w** [comment]
dorzuci się do rodziny `###onetrust-consent-sdk`, na przyszłość lepiej dać dokładni link lub nie usuwać subdomeny z nazwy wątku.
