### ISSUE TITLE
se.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#2173]
Adblock:

> http://www.se.pl/wiadomosci/polska/spiskowa-teoria-w-sprawie-smogu-chodzi-o-gigantyczne-pieniadze_953473.html

![image](https://cloud.githubusercontent.com/assets/11385099/23102151/f82ecaa4-f6a3-11e6-8dbf-161bbe31d189.png)

**Comment by xxcriticxx** [comment]
eskago.pl ma ten sam ad block

**Comment by xxcriticxx** [comment]
@mathew85 masz AdBlock Protector Script zamontowany?

**Comment by mathew85** [comment]
Dodałem. Z zamontowanym skryptem film się odtwarza.

**Comment by xxcriticxx** [comment]
@mathew85 lista jest potrzeba tez dodales?

**Comment by F4z** [comment]
Można też dodać takie reguły:
`@@||se.pl/media/*js/ads.js$script,domain=se.pl`
`@@||nowa.tv/media/static/js/ads.js$script`

Ta druga żeby film się tutaj wyświetlał - `http://tv.se.pl/wiadomosci/proste-pytanie-sledztwo-ws-zabojstwa-jaroszewiczow,20560/`

**Comment by xxcriticxx** [comment]
@F4z zobacz na closed issues znalazlem takich stron kilka az sie kapnelem ze script mam wylonczony

**Comment by mathew85** [comment]
@xxcriticxx tak listę miałem dodaną
@F4z z Twoim filtrem też działa prawidłowo.
Osobiście wolałbym dodać reguły, ponieważ skrypt  AdBlock Protector wydaje mi się, że coś bardziej obciąża komputer.

**Comment by xxcriticxx** [comment]
@mathew85 tak samo zasuwa jak reeka script

**Comment by MajkiIT** [comment]
@F4z Dzięki za reguły.
