### ISSUE TITLE
Adblock Lista 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#21733]
@MajkiIT pora zmienic właściciela listy adblock

**Comment by MajkiIT** [comment]
tzn?

**Comment by xxcriticxx** [comment]
chodzi mi o liste olegwukr

**Comment by xxcriticxx** [comment]
@MajkiIT krzycz jesli zyjesz

**Comment by hawkeye116477** [comment]
Znalazłem już kandydata na następcę.
<img src="https://nonsa.pl/images/3/38/Kr%C3%B3l_Julian.JPG" width="30%" height="30%"/>
> A zatem, przysięgam, że was nie zawiodę, nie tylko nie zawiodę, ale powiodę ku zwycięstwu i chwale. Albowiem „We Are The Champions”!

Tylko uwaga, bo on już był kiedyś w Polsce i zastał ją murowaną, a zostawił pijaną.
