### ISSUE TITLE
player.eska.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#21799]
![Capture](https://github.com/MajkiIT/polish-ads-filter/assets/15007183/d09d4563-6894-4ab9-893d-a83676f88562)

**Comment by krystian3w** [comment]
Duplicate of #21567

**Comment by krystian3w** [comment]
Jedynie poszkodowani są teraz fani ABP/AdBlock: https://github.com/uBlockOrigin/uAssets/commit/3fb6e8cc1e87f50d89913a3d3d08401abef907a2

**Comment by xxcriticxx** [comment]
z suportu ABP dawano powinismy zrezygnowac
