### ISSUE TITLE
poczta.o2.pl 

### ISSUE THREAD

**Issue by DrunkenCommie** [MajkiIT/polish-ads-filter#21834]
Czołem. Chłopaki z Reddita[ polecili mi, bym przyszedł tutaj.](https://www.reddit.com/r/uBlockOrigin/comments/14deqss/last_week_pocztao2pl_started_displaying_ads/)

### Zrzut ekranu 
![image](https://github.com/MajkiIT/polish-ads-filter/assets/41784423/57c4a09b-7063-485e-9005-e2c83c001faa)

### Link bezpośredni 
https://poczta.o2.pl/w/mails/?label=152

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
Wejść do 'segregatora' Oferty.

### Moja konfiguracja 
**Przeglądarka internetowa:** Firefox 114.0.1 (privacy.resistfingerprinting = true)
 
**Rozszerzenia i skrypty:** ublock, cookie autodelete

**Listy filtrów:** 
1. EasyList, EasyPrivacy
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. FanBoy Annoyance, Enhanced Tracking
4. uBlockowe wszystkie 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Próbowałem załatwić to Element Pickerem, ale kod się często zmienia (właściwie co logowanie). DOM Inspector mi też nie pomógł, zablokował mi cały środek ekranu (wszystkie mejle zniknęły). W tej chwili, może (już-nie-działające) wpisy to:
```

! reklamy w górnym pasku się zaczęły otwierać, i z prawej strony, i potem na dole. element pickerem zadziałałem
poczta.o2.pl##nh-app-view > div > div > dd-holder
poczta.o2.pl##.mbox--main.shrink-none
poczta.o2.pl##.UiView > div > dd-holder

! 2023-06-13 https://poczta.o2.pl
! teraz miejsce na reklamy na górze się zrobiło, i niby 4 emaile reklamowe
poczta.o2.pl##.fLhKpi.hXjcrG.default___StyledBox-sc-8j3xo6-0.sc-bcXHqe
poczta.o2.pl##.iYbHyx.hXjcrG.default___StyledBox-sc-8j3xo6-0.sc-bcXHqe
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .ni2v71x

! 2023-06-19 https://poczta.o2.pl
! znowu te 4 mejle reklamowe, inna końcówka cholera
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .nls1gaf
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .rk9lntb
```

**Comment by krystian3w** [comment]
Duplicate of #18472

**Comment by DrunkenCommie** [comment]
No właśnie - co logowanie są inne (nie używam tego "1login od WP"). A jak zablokuję _piętro wyżej_ (czyli ten 'div'), to cała środkowa kolumna z mejlami znika. Nie ma na to jakiegoś _regular expression_? Coś w stylu `\.\w{7}` (bo to zawsze kropka i 7 małych liter i cyfr.

**Comment by krystian3w** [comment]
Jest od "niedawna" `:matches-attr`: https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectmatches-attrarg

wtedy pseudofiltr może wyglądać tak:

```adb
poczta.o2.pl##[class*="desktop__StyledThread"] > div > [class]:matches-attr(class="/[\w]{7}/")
```

Niby wspiera regex, ale jak zaczną kombinować, to mogą wstawiać spacje typu:

```html
<div class=" bardzo-anatretna-reklama ">
```

i znaków jednak jest 26 a nie jak podpowiada picker "24" (spacje oddzielają klasy stąd nie można propozycji pickera używać jako licznik znaków, bo newbie nie używa na co dzień `matches-attr`).

**Comment by krystian3w** [comment]
Opcjonalnie możesz bawić się w testera czy AdamWr naprawił to w AdGuard i ich filtr byłby optymalny dla uBO:

![image](https://github.com/MajkiIT/polish-ads-filter/assets/35370833/df3231a3-714c-46b8-a821-88ca111f4559)

Jednak jak problem nie występuje z dodatkiem AdGuard to uBo nie musi mieć naprawy problemu w ramach listy "AdGuard - Ads".

**Comment by DrunkenCommie** [comment]
Co ciekawe, gdy zmieniłem regexpa "znajdź też kropkę"
`poczta.o2.pl##[class*="desktop__StyledThread"] > div > [class]:matches-attr(class="/.[\w]{7}/")`
to teraz wyświetla tylko reklamy (a nie mejle pod nimi). To pewnie coś prostego - ale, co robię nie tak? Jak dodać zaprzeczenie _ale nie to_? :)

![image](https://github.com/MajkiIT/polish-ads-filter/assets/41784423/b959726b-d717-49da-8986-18534fe2f58f)

**Comment by krystian3w** [comment]
On nie szuka kropki a "prawie byle co" i 7 znaków z dużej puli `\w` (https://regex101.com/r/LWc9TR/1) - takie `/\w{8}/` z dopuszczonymi spacjami.

Zaprzeczyć można za pomocą `:not()` i pseudofiltr może wyglądać tak:

```adb
poczta.o2.pl##[class*="desktop__StyledThread"] > div > [class]:not(:matches-attr(class="/.[\w]{7}/"))
```

ale będzie wtedy działać bardzo podobnie do prostego `##[class*="desktop__StyledThread"] > div > [class]` z jednym pomijaniem gdy klasa ma 8 znaków (być może realne mejle).

**Comment by DrunkenCommie** [comment]
Muszę powiedzieć, że poddaję się. Odświeżyłem wszystkie subskypcje... i nagle zaczęło się jeszcze więcej reklam pojawiać (bo AdGuard - Ads zrobił jakieś wyjątki dla wp.pl i o2.pl

![image](https://github.com/MajkiIT/polish-ads-filter/assets/41784423/32529eab-c88f-4cb9-8fea-e2b57def16d2)

Już nie same tekstowe reklamy, ale wręcz obrazki po obu stronach listy mejli. I to ruchome obrazki. Och, _moje oczy_! :)
Tak więc, zaszalałem z Element Pickerem i w tej chwili moje wpisy odnośnie poczty o2 wyglądają:

```
! 2022-07-04 https://poczta.o2.pl
! reklamy w górnym pasku się zaczęły otwierać, i z prawej strony, i potem na dole. element pickerem zadziałałem
poczta.o2.pl##nh-app-view > div > div > dd-holder
poczta.o2.pl##.mbox--main.shrink-none
poczta.o2.pl##.UiView > div > dd-holder

! 2023-06-13 https://poczta.o2.pl
! teraz miejsce na reklamy na górze się zrobiło, i niby 4 emaile reklamowe
poczta.o2.pl##.fLhKpi.hXjcrG.default___StyledBox-sc-8j3xo6-0.sc-bcXHqe
poczta.o2.pl##.iYbHyx.hXjcrG.default___StyledBox-sc-8j3xo6-0.sc-bcXHqe
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .ni2v71x

! 2023-06-19 https://poczta.o2.pl
! znowu te 4 mejle reklamowe, co chwila inna końcówka cholera
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .nls1gaf
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .rk9lntb
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .cnxt7fy
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .r1ajf7a

! 2023-06-21 https://poczta.o2.pl
! krystian3w z Githuba zaproponował - ale za dużo blokuje, lub wręcz tylko reklamy pokazuje
!poczta.o2.pl##[class*="desktop__StyledThread"] > div > [class]:matches-attr(class="/[\w]{7}/")
!poczta.o2.pl##[class*="desktop__StyledThread"] > div > [class]:matches-attr(class="/\.[\w]{7}/")
poczta.o2.pl##[class*="desktop__StyledThread"] > div > [class]:matches-attr(class="/\.[a-z0-9]{7}/")

! 2023-06-21 https://poczta.o2.pl
! tymi paskami pod Element Pickerem się pobawiłem
!poczta.o2.pl##.gpYpKR.bbLVwL.hXjcrG.styled__Wrapper-sc-1ccth1a-2.sc-gswNZR.sc-bcXHqe
||wpext.pl^$subdocument,important
||www.wp.pl^$generichide,domain=www.wp.pl,important
||poczta.o2.pl^$generichide,domain=poczta.o2.pl,important
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .ckzm9zz
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .zl42fms
```


Niestety, co odświeżenie strony, od nowa te 4 tekstowe reklamy wyskakują, i ostatnia sekcja "kropka 7 małych liter i cyfr" się zmienia.  A nie jestem programistyczny na tyle, by zrozumieć poradę z `xPath`.

Chyba ktoś z WP czyta te wpisy i próbują nas przechytrzyć ;)

**Comment by krystian3w** [comment]
Możliwe że czytają tak by nie miało sensu nawet tworzenie PR lub commita jak MajkiIT uzna, że coś skopiuje do np. `adblock_ublock.txt`.

**Comment by krystian3w** [comment]
Nie wiem czy u ciebie reklamy tekstowe też mają fail i czytelne dla człowieka nazwy (ale nie takie jak `nh-native-link`):

```adb
! placeholder
/poczta\.(wp|o2)\.pl/##nh-native-link
! po załadowaniu
/poczta\.(wp|o2)\.pl/##.adbanner.ad-target.advertisement.ads.adv.stream-item__wrap
! większość dużych luk
/poczta\.(wp|o2)\.pl/##dd-holder
! górna nad nawigacją
/poczta\.(wp|o2)\.pl/##body > div > div[style*="height:"]
```

Jak padnie do 3 dni to czytają już.

**Comment by DrunkenCommie** [comment]
Nie, ten fragment "nic nie złapał" (wg Loggera).
A czy mają czytelne nazwy? Ciężko rzec, wg mnie nie - na obrazku sekcja tego Modivo. Wszystkie 4 reklamy mają ten sam string `nos8el7`, i ten string zmienia się co refresh strony.

![image](https://github.com/MajkiIT/polish-ads-filter/assets/41784423/24ed6073-f093-4ee2-8139-22136424773e)

A te 6 errorów to jakieś błędy w instrument.js - ale programistą nie jestem, i nie rozumiem tych błędów.

**Comment by krystian3w** [comment]
Wygląda, że czytają (mam już 0 dopasowań jak to nie wina odpalenia w Chrome np. brak "dd-holder") i być może nawet aktywowali subskrypcję na e-mail, więc nie ma za bardzo jak ci wysłać tego.

`##div[class*="Box"][style*="sticky"] ~ div:not([class])`
`##div[class*="Box"][style*="fixed"] ~ div:not([class])`

takie coś działa tak długo aż nawigacja (z segregatorami) nad będzie się przewijała również w Firefox.

`##div[class*="Listing__Container"]:upward(1) > div:not([class])`

takie coś będzie działać aż nazwa elementu z mejlami będzie "listingiem".

Najłatwiej im pewnie będzie dodać fejkową klasę tam gdzie jej brak i wszystkie 3 padną.

**Comment by DrunkenCommie** [comment]
No szlag mnie trafił, mam już fafnaście wpisów typu
```
! znowu te 4 mejle reklamowe, co chwila inna końcówka cholera
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .nls1gaf
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .rk9lntb
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .cnxt7fy
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .r1ajf7a
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .fk2i0lq
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .ckzm9zz
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .zl42fms
poczta.o2.pl##.eqakMd.hXjcrG.desktop__StyledThread-sc-1qia0o9-0.sc-bcXHqe > div > .dr3zk6l
```

Więc zacząłem czytać (znowu) regexp 101, i skoro `poczta.o2.pl##[class*="desktop__StyledThread"] > div > [class]:matches-attr(class="/[\w]{7}/")` łapało same reklamy (tylko sekcja z reklamami tekstowymi się pojawiała, nic więcej), to wróciłem do Twojego pomysłu z `:not` -- i działa.

Więc, poprawny wpis (sprawdziłem refreszując 10+ razy, też logout i login):
`poczta.o2.pl##[class*="desktop__StyledThread"] > div > [class]:not(:matches-attr(class="/[\w]{8}/"))`
(8 znaków, kropka plus 7 cyfroliter).

Co ciekawe, niby _dokładniejsze_ (nie "8 znaków", ale "kropka i 7 znaków")
`poczta.o2.pl##[class*="desktop__StyledThread"] > div > [class]:not(:matches-attr(class="/\.[a-z0-9]{7}/"))`
łapało same reklamy - i je po chwili "gasiło", i zostawałem z niczym.
Nie bardzo rozumiem czemu `\w{8}` działa, a `\.[a-z0-9]{7}` nie - ale co tam :) Grunt, że jest czysto.

Zobaczymy na jak długo (dowód, czy czytają).

**Comment by DrunkenCommie** [comment]
No więc - wróciło dziś. Po dwóch tygodniach (nowa wersja UI, na oko, inne fonty itd).
Pojawiło się też puste pole na górze. Szalejąc dziś z Pickerem, wyszły mi 4 filtry:

```
! 2023-07-07 https://poczta.o2.pl
poczta.o2.pl##.css-163vs9n.e14umhjn0 > div > .keyg7ct
poczta.o2.pl##.css-1cfowg8
poczta.o2.pl##.css-1gyf6rm
poczta.o2.pl##.css-163vs9n.e14umhjn0 > div > .buu61yc
poczta.o2.pl##.css-163vs9n.e14umhjn0 > div > .hqr2gvq
poczta.o2.pl##.css-163vs9n.e14umhjn0 > div > .jh9mln0
poczta.o2.pl##.css-163vs9n.e14umhjn0 > div > .tzz68f1
```
Te krótsze wycięły puste pola na górze, te dłuższe są do tych tekstowych reklam udających mejle (nowa wartość na końcu = zmienia co refresh strony).

Może jakiś pomysł, jak to bardziej elegancko ogarnąć?
Jak spróbowałem 
`poczta.o2.pl##[class*=".css-"] > div > [class]:not(:matches-attr(class="/[\w]{8}/"))`
czy 
`poczta.o2.pl##[class^=".css-"] > div > [class]:not(:matches-attr(class="/[\w]{8}/"))`
(czyli modyfikacja poprzedniego działającego) - to po prostu nie zaskoczyło, nic nie złapało.

**Comment by krystian3w** [comment]
Mnie padły nawet prywatne filtry na zmianę tła pod spamem z nazwą dostawcy "bla bla **/o2**".

**Comment by DrunkenCommie** [comment]
Co ciekawe, teraz jest jakby działanie z opóźnieniem. Wchodzę w te "oferty", przez chwilę jest czysto, i po niecałej sekundzie na górze robi się harmider i wskakują te pieprzone 4 reklamy.

W Fajerfoksowym inspektorze wygląda, że ten div to wygląda `{losowe znaki} cyfra kropka css minus cyfra {losowe znaki}`. (a tak naprawdę ".css-163", nie "minus cyfra").

Więc spróbowałem
`poczta.o2.pl,poczta.wp.pl##[class]:matches-attr(class="/[0-9].css-1/") > div > [class]:not(:matches-attr(class="/[\w]{8}/"))`
i - chyba działa. Kilka refreszy i logout/login, na razie wszystko OK. Spróbuj u siebie.

**Comment by krystian3w** [comment]
Górnej luki już nie łapie: ale prawą, dolną i 4 w segregatorze jeszcze tak.

**Comment by danekszy** [comment]
Od siebie mogę dorzucić info o blokowaniu skryptów odpowiedzialnych za reklamy na poczcie o2...
Zasada do adblocka:
```
/https?:\/\/poczta\.o2\.pl\/(?!.*\.js$).*/$script
```
W skrócie:
- URLe typu https://poczta.o2.pl/w/costam.js to assety statyczne serwowane a la CDN
- URLe typu https://poczta.o2.pl/jakis-dziwny-hash to skrypty odpowiedzialne za reklamy, serwowane w ten sposób, żeby ominąć adblocki

Mam nadzieję, że komuś się przyda 😉

**Comment by DrunkenCommie** [comment]
To może żeby podbić temat. Nasze filtry przestały właściwie działać (najlepiej chyba sztuczka Daniela). Z tymi placeholderami na reklamy nic już się właściwie nie da zrobić, trzeba się przyzwyczaić - i w dodatku trzeba wyłączyć _costmetic filtering_, żeby widzieć mejle jako takie (inaczej się śmiesznie rozmazuje).

Od paru dni natomiast pojawia się pusta belka na górze, z którą nic nie da się zrobić.
![image](https://github.com/MajkiIT/polish-ads-filter/assets/41784423/d3ea2440-9ead-4bf9-a6fe-7151a0fc614b)
Nie mogę jej usunąć Element Pickerem, bo cała strona (?) jest traktowana jako jeden obiekt (a dokładniej, wybieram element pickera, robi się typowo ciemniejszy ekran - ale żaden fragment ekranu nie jest klikalny). Jedyne co działa, to zapper (ta pierwsza ikonka, jakby pioruna) - on faktycznie usuwa tą ramkę - ale tylko na moment ("wejdziesz w mejla", wrócisz do głównego widoku i baner powraca).

Jest jakaś metoda żeby ten zapper pokazał co zrobił? (to wtedy bym to ręcznie w filtry wpisał)

**Comment by krystian3w** [comment]
> Jest jakaś metoda żeby ten zapper pokazał co zrobił? (to wtedy bym to ręcznie w filtry wpisał)

Wtedy wywali ci losowe klasy co i tak padną. Jak długo reklamy nie są w stałym miejscu by je obliczać z nth-child lub nth-of=type to raczej nie namierzysz wadliwych "`<div>`-ów".

**Comment by garry-ut99** [comment]
Inni też się już (bezskutecznie) dopraszali o usunięcie reklam z `poczta.o2.pl` : https://github.com/MajkiIT/polish-ads-filter/issues/21302

Zgłaszajcie do uAssets do tego wątku : https://github.com/uBlockOrigin/uAssets/issues/12214 - to jest taki wątek zbiorczy dla stron z grupy WP, ( taki odpowiednik naszego polskiego wątku : https://github.com/MajkiIT/polish-ads-filter/issues/18472 ), oni tam usunęli reklamy ze wszystkich stron WP, z `poczta.o2.pl` też usuną, tylko musicie założyć jakieś testowe konto mejlowe i podać im login i hasło.

@kolor33, @AroKol78, @DrunkenCommie
