### ISSUE TITLE
donate button

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#21842]
@MajkiIT przycisk darowizna nie działa

https://www.paypal.com/pools/c/87zNJ8OJ3I

We can't find that fundraiser
It looks like that fundraiser is no longer available.

**Comment by xxcriticxx** [comment]
@MajkiIT pasowałoby jakies zebranie firmowe zrobic i wyjasnic kilka spraw

**Comment by krystian3w** [comment]
Gorzej jak jego jakaś umowa o pracę/dzieło nie pozwala prać brudów publicznie.

**Comment by xxcriticxx** [comment]
@MajkiIT ma prawdziwe zycie, teraz nie ma czasu na prawnikow

**Comment by MajkiIT** [comment]
a co na spotkaniu będzie :P ?

**Comment by krystian3w** [comment]
Wystarczy sprawdzić konto PayPal i jak nie da się odmrozić zbiórki to załączyć nową lub nawet nowy PayPal i zedytować 4 linię:

![obraz](https://github.com/MajkiIT/polish-ads-filter/assets/35370833/45c6dc45-909a-463e-8b92-fec0e5b8f004)

Raczej nikt nie odda swojego PayPala z opcją przelewu na prywatny rachunek bankowy, jak porzucasz brytyjską platformę na dobre.
