### ISSUE TITLE
Filmweb.pl

### ISSUE THREAD

**Issue by ghost** [MajkiIT/polish-ads-filter#21868]
Na filmwebie ostatnio pojawiają się reklamy. Używam brave na telefonie Samsung A54 z włączonymi oficjalnymi filtrami do adblock i 2 uzupełnieniami do alertów przeciwko adblockowi i ustawieniami shielda na agresywne blokowanie.

![Screenshot_20230713_100819_Brave](https://github.com/MajkiIT/polish-ads-filter/assets/130224667/68456fe0-59a4-4349-899f-5fba7dda9e7b)

Link do reklamy:  https://www3.smartadserver.com/h/cc?imgid=30263569&tmstp=[timestamp]&tgt=[reference]

**Comment by Lukjan39** [comment]
blokuje zwiastuny filmow i seriali.

**Comment by wikigbw** [comment]
Także przy wchodzeniu na stronę zarówno na komputerza jak i telefonie pojawia się banner zasłaniający całą stronę przed wejściem.

![Screenshot_20230715_101904_Brave](https://github.com/MajkiIT/polish-ads-filter/assets/130224667/99a400e8-1340-432b-bc3e-c357c283bcc8)

**Comment by krystian3w** [comment]
Sprawdzić możesz czy AdGuard to ogarnął kompatybilnie z uBo:

> ![obraz](https://github.com/MajkiIT/polish-ads-filter/assets/35370833/440ed984-807c-4544-9006-03813d966292)


Opcjonalnie nie zamykać komunikatów Cookies/RODO i reklam też brak jak nie używamy odtwarzaczy #21882.

**Comment by pabli24** [comment]
Do blokowania pełnoekranowej reklamy
```
||fwcdn.pl/front/assets/WelcomeScreen-*.js$important,script,domain=filmweb.pl
```

Do blokowania denerwującego odświeżania się co jakiś czas strony:
```
||fwcdn.pl/front/assets/AutoRefreshModule-*.js$important,script,domain=filmweb.pl
```

**Comment by krystian3w** [comment]
Zmienią pewnie CDN lub nazwy plików.
