### ISSUE TITLE
kfcdostawa.pl

### ISSUE THREAD

**Issue by PrzemyslawKlys** [MajkiIT/polish-ads-filter#2188]
https://kfcdostawa.pl/ wycina za dużo ;-)

**Comment by xxcriticxx** [comment]
@PrzemyslawKlys screen shot please?

**Comment by PrzemyslawKlys** [comment]
![image](https://cloud.githubusercontent.com/assets/15063294/23136315/7881427e-f79c-11e6-98c5-122d04814412.png)

**Comment by xxcriticxx** [comment]
po zalogowanju?

**Comment by PrzemyslawKlys** [comment]
Nie, bez logowania wycina produkty i widac ze adblock przyblokowal kilka elementow

**Comment by xxcriticxx** [comment]
co mam nacisnac zeby reprodukowac blad?

**Comment by PrzemyslawKlys** [comment]
Jak wejdziesz na strone https://kfcdostawa.pl nie powinienes miec produktow ... 

![image](https://cloud.githubusercontent.com/assets/15063294/23136464/20933e5e-f79d-11e6-9dfa-660c352b3cb6.png)

Po ublock

![image](https://cloud.githubusercontent.com/assets/15063294/23136475/2cdd1f0e-f79d-11e6-9e2f-a817e368606c.png)

**Comment by xxcriticxx** [comment]
w firefox i ublock o mam produkty

**Comment by xxcriticxx** [comment]
w chromie tez widze wszystko 

na dole sa cookies. masz cookie filter wlonczony?

**Comment by PrzemyslawKlys** [comment]
![image](https://cloud.githubusercontent.com/assets/15063294/23136645/085c241c-f79e-11e6-9514-dff89c58d5e9.png)


z tego co widze to wlasnie przez filtr 

![image](https://cloud.githubusercontent.com/assets/15063294/23136665/1cdf3f28-f79e-11e6-983c-d89ff2eb91b6.png)

**Comment by PrzemyslawKlys** [comment]
jak go odznacze to widac obrazki.

**Comment by xxcriticxx** [comment]
odznacz reguly social

uzywasz jeszcze czegos do blokowania?

**Comment by PrzemyslawKlys** [comment]
Nie, odznaczylem social i działa. Nie uzywam w zasadzie tego wiec nie ma problemu. Generalnie tez nie mam problemu z tym, żeby ufać kfcdostawa więc wyłączyłem po prostu na niej ublocka.

**Comment by xxcriticxx** [comment]
jaki browser? opera jak dobrze pamietam

potestujemy damy znac

**Comment by PrzemyslawKlys** [comment]
Chrome :-)

**Comment by xxcriticxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/15007183/23137138/5a96037c-f76e-11e6-93d1-28e6d932b550.PNG)

**Comment by PrzemyslawKlys** [comment]
Z włączonym Adblock polskie reguły social ?

**Comment by xxcriticxx** [comment]
nope bo ja nie jestem social

**Comment by xxcriticxx** [comment]
@blocker999 spojzysz na to please?

**Comment by blocker999** [comment]
OK, to moja wina ale dzięki za zgłoszenie, zlokalizuje ten błąd i poprawie.

**Comment by blocker999** [comment]
Tak na szybko to @PrzemyslawKlys dodaj regułe 	`#@#.in` w zakładce Moje filtry i powinno być ok, zanim ja dodam kolejną aktualizacje.

**Comment by PrzemyslawKlys** [comment]
Nie ma potrzeby :-) Aż takim fanatykiem nie jestem, żeby blokować kfcdostawa więc po prostu odblokowałem :-)

**Comment by blocker999** [comment]
@PrzemyslawKlys 

OK ale dzięki za zgłoszenie

**Comment by MajkiIT** [comment]
@PrzemyslawKlys @xxcriticxx @blocker999 
Dzięki za pomoc.
