### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by Lukjan39** [MajkiIT/polish-ads-filter#21882]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Typ błędu

blokuje zwiastuny filmow i seriali.

**Comment by krystian3w** [comment]
Jak blokuje, to wtedy powinieneś zgłaszać jako błąd: https://github.com/MajkiIT/polish-ads-filter/labels/b%C5%82%C4%85d

**Comment by Lukjan39** [comment]
pisac od nowa?

**Comment by krystian3w** [comment]
Możesz to wkleić do  pierwszego posta: https://github.com/MajkiIT/polish-ads-filter/issues/21882#issue-1805239644

```md
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)


### Typ błędu

blokuje zwiastuny filmow i seriali.
```

===

Bot wtedy usunie etykietę reklama i zostawi tę od błędu.

**Comment by Lukjan39** [comment]
ok, juz. czekam na poprawke, filtru.

**Comment by krystian3w** [comment]
Możliwe, że naprawi się z uBo DEV i aktywacją listy:

- https://github.com/gorhill/uBlock/releases/download/1.50.1rc1/uBlock0_1.50.1rc1.firefox.signed.xpi - Firefox.
- 
- https://chrome.google.com/webstore/detail/ublock-origin-dev-build/cgbcahbpdhpcegmbfconppldiemgcoii - Chrome / Opera (i inne np. Brave, Vivaldi).

> uBlock filters – Cookie Notices

lub

> uBlock filters – Annoyances


Wychodzi na to, że tam nie można ukrywać komunikatu Cookies/RODO bazującego `didomi`.

Niestety tych filtrów nie można dodać do list Majkiego, bo są to `trusted-set-cookie`.
I zracji, że niedługo będzie się dało to zrobić na stabilnym uBo, to nie można by już dodawać do Polskiej Ciasteczkowej Zgody.

**Comment by Lukjan39** [comment]
chodzilo mi o te zwiastuny, np https://www.filmweb.pl/video/Relacja+wideo/Przygody+na+planie+%22Za+du%C5%BCy+na+bajki+2%22-65944

**Comment by krystian3w** [comment]
Też zależne od akceptacji RODO, w uBo dev `trusted-set-cookie` go zamyka.

**Comment by Lukjan39** [comment]
tez nie dziala po wylaczeniu AdGuard  Ads, w ublock origin

**Comment by Lukjan39** [comment]
dalej nic :(

**Comment by krystian3w** [comment]
No to zresetuj uBo do ustawień domyślnych.

**Comment by Lukjan39** [comment]
t,ez nic

takie mam filtry https://github.com/MajkiIT/polish-ads-filter/discussions/21902

przegladarka edge

**Comment by Lukjan39** [comment]
jak tam filtry?
