### ISSUE TITLE
odnośnik facebooka na odtwarzaczu

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2189]
Na pasku odtwarzacza w reklamie mobile vikings jest ikonka do ich profilu na facebooku.

![fb na mv](https://cloud.githubusercontent.com/assets/23176832/23137094/6109c0cc-f7a0-11e6-934b-8e3d37bcbcc9.jpg)

Przykładowa reklama jest na : http://www.telepolis.pl/wiadomosci/zyjnolimit-nowa-kampania-reklamowa-mobile-vikings,2,3,38210.html

**Comment by MajkiIT** [comment]
Ale to pokazuje reklamę ... mam osunąć ten film?

**Comment by blocker999** [comment]
NIE, chodzi mi tylko o usuniecie znaczka f na dole.
