### ISSUE TITLE
gs24.pl - Disable autoplay

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2190]
see https://github.com/X01X012013/AdBlockProtector/issues/56

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki. ja wczoraj miałem urwanie głowy.

**Comment by xxcriticxx** [comment]
Podaj na fb

@xxcriticxx Good news! This is added to 6.22! And it's toggle-able in settings page:
https://x01x012013.github.io/AdBlockProtector/settings.html

**Comment by MajkiIT** [comment]
Wrzuciłem rano. Dzięki
