### ISSUE TITLE
wiadomoscikosmetyczne.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#21915]
puste kontenery po reklamie reported by @SirShedi

**Comment by SirShedi** [comment]
ostatnimi razami dodanie wpisu do filtrów jak poniżej dla widocznych domen rozwiązało problem.

,~sadnowoczesny.pl,~warzywaiowoce.pl,~elita-magazyn.pl,~tygodnik-rolniczy.pl##[class$="-ads"]

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/21915#issuecomment-1671208524 = Twoja sugestia może umożliwia czytanie newsów ale niestety nie ukrywa resztek po reklamach na górze i prawej kolumnie.
