### ISSUE TITLE
wiadomoscihandlowe.pl 

### ISSUE THREAD

**Issue by SirShedi** [MajkiIT/polish-ads-filter#21914]
### Zrzut ekranu 

![ublock](https://github.com/MajkiIT/polish-ads-filter/assets/140722349/8c2b8252-63bd-4c7f-9940-b6d711555f1b)

### Link bezpośredni 
www.wiadomoscikosmetyczne.pl 
https://www.wiadomoscihandlowe.pl/gospodarka-i-finanse/prof-konrad-raczkowski-dla-wh-ceny-podnosza-rowniez-ci-ktorzy-nie-musza-2486460

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
1. Wyłączenie polskich filtrów powoduje prawidłowe wyświetlanie się stron oraz brak "chowania" pierwszego z 3 artykułów
2. 
3. 

### Moja konfiguracja 
**Przeglądarka internetowa:** 

**Rozszerzenia i skrypty:** 

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Brakuje etykiety błąd, skoro coś jest nieprawidłowo ukryte.

**Comment by krystian3w** [comment]
Tylko nie ma chętnych na PR by @xxcriticxx scalił.

**Comment by SirShedi** [comment]
no to wypada poczekac :P

**Comment by krystian3w** [comment]
Niektórzy czekają po 60 dni i nikt nie adresuje problemu.

**Comment by SirShedi** [comment]
W tym wypadku jest dość proste rozwiązanie bo już był dodawany wpis za każdym razem przy 5 portalach.
Jakoś teraz trwa to długo ...
