### ISSUE TITLE
olx.pl

### ISSUE THREAD

**Issue by jcubic** [MajkiIT/polish-ads-filter#21929]
### Zrzut ekranu 
![Przechwycenie obrazu ekranu_2023-08-05_01-30-46](https://github.com/MajkiIT/polish-ads-filter/assets/280241/9edf099c-7312-40ab-84ea-f3c66989bc49)

### Link bezpośredni 
https://www.olx.pl/d/oferta/nikkor-fisheye-16mm-2-8-CID99-IDWAIag.html?chat=1&isPreviewActive=0

### Co trzeba zrobić, aby pojawiła się reklama albo błąd?
1. wchodzisz na stronę oferty
2. Na górze pojawia się reklama która przechodzi przez filtr

### Moja konfiguracja 
**Przeglądarka internetowa:** Google Chrome

**Rozszerzenia i skrypty:** uBlock

**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
4. Domyślne ustawienia i domyślne filtry

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Kod HTML/DOM reklamy:

```html
<a id="baxter-top-inner-banner">
  <img src="https://cdn.admanager.baxter.olx.org/accounts/olx-group-pl/type/image/bf483ee6-9525-5fe9-941d-5fe0e6a84f75" width="1920" height="300" alt="Advertising">
</a>
```

Nie sprawdzałem co je ładuje. Ale chyba można zablokować sam obrazek. Zakładam że zmienia się tylko identyfikator na końcu. Widziałem tylko jedną reklamę, która jest na zrzucie ekranu, nie ma nazwy firmy ale to chyba są Cyfrowe.pl.

**Comment by krystian3w** [comment]
U mnie już brak.

Używaj tego ✔️: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=pl / https://microsoftedge.microsoft.com/addons/detail/ublock-origin/odfafepnkmbhccpbejgmiehpchacaeak?hl=pl-PL

tego unikaj ⚠️: https://chrome.google.com/webstore/detail/ublock/epcnnfbjfcgphgdmggkamkmgojdagdnn https://microsoftedge.microsoft.com/addons/detail/ublock/nffknjpglkklphnibdiadeeeeailfnog
