### ISSUE TITLE
mojegotowanie.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2194]
Reklamy 
![przepisy](https://cloud.githubusercontent.com/assets/23176832/23165659/8cf612ba-f83d-11e6-8dd5-81f090d41a89.jpg)

**Comment by MajkiIT** [comment]
||widgets.tracdelight.com/iframe/$subdocument

**Comment by MajkiIT** [comment]
@blocker999 dzięki

**Comment by blocker999** [comment]
Ostatnia aktualizacja rozwiązała ten problem ale tylko połowicznie, bo niestety reklamy dalej są a jak się odświeży strone to się pojawiają nowe.

![mg](https://cloud.githubusercontent.com/assets/23176832/23256657/acae5bf6-f9c0-11e6-8fa5-7e3309c434b8.jpg)
