### ISSUE TITLE
vod.tvp.pl

### ISSUE THREAD

**Issue by Lukjan39** [MajkiIT/polish-ads-filter#21962]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Typ błędu

@MajkiIT @krystian3w zle dziala strona, brak na liscie sezonow, nie dziala moja lista. mam adguard i edge

**Comment by krystian3w** [comment]
Dokładne linki gdzie ci sezony zniknęły i czy wymaga logowania dla zobaczenia listy.

**Comment by Lukjan39** [comment]
kazdy serial, trzeba sie zalogowac

**Comment by Lukjan39** [comment]
tu nie ma odcinkow
![vod](https://github.com/MajkiIT/polish-ads-filter/assets/104568362/97597c0c-7192-43e0-898d-2c20997b62e9)

nie ma darmowego konta

**Comment by Lukjan39** [comment]
@krystian3w nie dodasz nic do filtrow?

**Comment by garry-ut99** [comment]
On nie ma z tym nic wspólnego, to jest psute przez listę Privacy : 
- https://github.com/olegwukr/polish-privacy-filters/issues/149
- https://github.com/olegwukr/polish-privacy-filters/issues/147

**Comment by Lukjan39** [comment]
tzn, nie bedzie dodanie?

**Comment by garry-ut99** [comment]
Pytaj właściciela listy Privacy: `https://github.com/olegwukr` on nią zarządza, nie my, ale on raczej nic nie doda i nie naprawi, albo nawet się w ogóle nie odezwie, bo go nie ma już od ponad roku, i ostatnia aktualizację listy Privacy wykonał ponad rok temu, więc albo mu się nie chce, albo nie ma czasu, albo ma to związek z wojną na Ukrainie bo on chyba pochodzi z Ukrainy. Póki co jedyne co można zrobić to dodać filtry naprawcze samemu do "Moje filtry".

**Comment by Lukjan39** [comment]
aha, dobra

**Comment by garry-ut99** [comment]
>  Póki co jedyne co można zrobić to dodać filtry naprawcze samemu do "Moje filtry".

Klikasz zieloną ikonkę AdGuard w przeglądarce ==> potem Zębate koło (ustawienia AdGuard) ==> potem Reguły Użytkownikai wklejasz wszystkie na raz lub wybrane : 

- w celu naprawienia vod.tvp.pl :
 `@@||web.geb.snrbox.com/synerise-javascript-sdk.min.js$script,domain=vod.tvp.pl`
- w celu dodatkowego naprawienia vod.tvp.pl w razie gdyby coś się dalej psuło :
 `@@||proxy.geb.snrbox.com/rtom/configs/*/sw.js$script,domain=vod.tvp.pl`
- w celu naprawienia manager.paczkomaty.pl :
`@@||web.snrbox.com^$script,domain=manager.paczkomaty.pl`

**Comment by Lukjan39** [comment]
dobra, dzieki, moze sie odezwie i doda filtrow.

**Comment by garry-ut99** [comment]
>  moze sie odezwie i doda do filtrow.

Gdy się wojna skończy, to może i tak...czyli może za jakieś kilka/naście miesięcy...😂

**Comment by Lukjan39** [comment]
oby, szybko.

**Comment by garry-ut99** [comment]
A gdzie tu jest `adblock-detect`?, raczej etykieta `błąd`"

**Comment by Lukjan39** [comment]
tylko napisalem post, nie wiedzialem gdzie

**Comment by garry-ut99** [comment]
Nie wykręcaj się głupimi wymówkami i tłumaczeniami, bo już raz zgłaszałeś bardzo podobny `błąd` i wybrałeś `reklama` i zostałeś pouczony żeby wybierać `błąd`: https://github.com/MajkiIT/polish-ads-filter/issues/21882#issuecomment-1637126291, a pomimo pouczenia teraz znowu wybrałeś inną etykietę.

Nawet zostałeś też pouczony jak w razie pomyłki zmienić etykietę: https://github.com/MajkiIT/polish-ads-filter/issues/21882#issuecomment-1637145860, więc może byś łaskawie to zrobił.

**Comment by Lukjan39** [comment]
poprawione

**Comment by garry-ut99** [comment]
> poprawione.

No i gitara.

> a tak poza tym to jestem niepelnosprawny

Acha. Ale w sensie problemy z wypełnianiem formularzy (pamięć / wzrok / koncentracja itp.) ? 
Czy taka która w ogóle nie ma związku z githubem?

**Comment by Lukjan39** [comment]
slabo znam angielski, i nie wiem ktora, sekcja czasem wybierac

**Comment by garry-ut99** [comment]
Przecież te formularze są po polsku.

**Comment by krystian3w** [comment]
W sumie jak to błąd listy Olegowej, to można by zamknąć zgłoszenie tutaj i przekleić je do repo Olega by ludzie widzieli, że lista wymaga zmian.

**Comment by krystian3w** [comment]
Jak @Gomoku chce prowadzić listę anty-adblock to ja nie widzę przeciwwskazań, ktoś na pewno nie został zablokowany - by nie musiał się bawić jak bogachenko w obserwację połowy repozytoriów na GitHub gdzie ludzie zgłaszają wykrycie AdBlock i on umie ze swoją listą odtwarzać problem.

Listę Privacy można oznaczyć jako bad list i wygaśnie dla uBo kompletnie - jedynie chętny musi w uAssets opisać rączną przerwę i jak najwięcej przykładów psucia stron kosztem zwiększonej prywatności (uAssets lubi balans a nie popsute strony za co często obrywa EasyPrivacy).

**Comment by xxcriticxx** [comment]
@krystian3w kazdy by chciał listy uzywac ale chętnych do prowadzenia listy brakuje

**Comment by Lukjan39** [comment]
@krystian3w @MajkiIT nikt nie doda? :(
