### ISSUE TITLE
sklep.effector.pl

### ISSUE THREAD

**Issue by Lukjan39** [MajkiIT/polish-ads-filter#21973]
@MajkiIT @krystian3w jest ciemnie tlo, mam adquard

**Comment by krystian3w** [comment]
Nie ma metody idealnej na wycięcie wszystkich cookies i RODO, zwłaszcza jak admin strony zrobi je od zera samodzielnie.

**Comment by krystian3w** [comment]
@kiboke your `##.cookies-popup:not(body):not(html)` also is too agressive at pages:

`https://www.sklep.effector.pl/`
`https://www.effector.pl/`

- both pages lock scroll
- 1 page have fog without hide with diffrent "rule" like `##.footer-sticky__overlay`

**Comment by Lukjan39** [comment]
behdzie dodanie do filtrow, jak znajdziecie sposob?

**Comment by krystian3w** [comment]
Kiedyś niby tak, jak to ci działa: https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/commit/bbc6b750e11d0e4d9ba084aa9c709779f9e027b4

**Comment by kiboke** [comment]
@krystian3w thank you, it will be fixed in IDCAC soon.

**Comment by Lukjan39** [comment]
dobrze, rozumiem, ze bedzie dodanie do filtrow?
