### ISSUE TITLE
panwybierak.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#21974]
PanWybierak.pl przetwarza Twoje dane osobowe zbierane w Internecie, w tym informacje zapisywane za pomocą technologii służących do ich śledzenia i przechowywania, takich jak pliki cookies, sygnalizatory WWW lub innych podobnych technologii umożliwiających świadczenie dopasowanych i bezpiecznych usług, personalizację treści oraz reklamy, udostępnianie funkcji mediów społecznościowych oraz analizowanie ruchu w Internecie.

Kliknij "AKCEPTUJĘ I PRZECHODZĘ DO SERWISU", aby wyrazić zgodę na korzystanie w Internecie z technologii automatycznego śledzenia i zbierania danych, dostęp do informacji na Twoim urządzeniu końcowym i ich przechowywanie oraz na przetwarzanie Twoich danych osobowych przez PanWybierak.pl w celach marketingowych (w tym do zautomatyzowanego dopasowania reklam do Twoich zainteresowań i mierzenia ich skuteczności) i pozostałych, które wskazujemy poniżej.

Twoje dane osobowe zbierane w Internecie, takie jak adresy IP, identyfikatory Twoich urządzeń końcowych i identyfikatory plików cookie, informacje o Twoich wyszukiwaniach w Internecie będą przetwarzane przez PanWybierak.pl w celu: przechowywania informacji na urządzeniu lub dostęp do nich, wyboru podstawowych reklam, wyboru spersonalizowanych reklam, tworzenia profilu spersonalizowanych reklam, tworzenia profilu spersonalizowanych treści, wyboru spersonalizowanych treści, pomiaru wydajności reklam, pomiaru wydajności treści, stosowania badań rynkowych w celu generowania opinii odbiorców, opracowywania i ulepszania produktów, zapewnienia bezpieczeństwa, zapobiegania oszustwom i usuwania błędów, technicznego dostarczania reklam lub treści.

Ponadto PanWybierk.pl przetwarza Twoje dane na potrzeby funkcji i funkcji specjalnych, które ułatwiają nam świadczenie dopasowanych i bezpiecznych usług, personalizację treści oraz reklamy, udostępnianie funkcji mediów społecznościowych oraz analizowanie ruchu w Internecie: dopasowywania i połączenia źródeł danych offline, łączenia różnych urządzeń, użycia dokładnych danych geolokalizacyjnych, odbierania i wykorzystywania automatycznie wysłanej charakterystyki urządzenia do identyfikacji.

Cele przetwarzania szczegółowo opisujemy w ustawieniach zaawansowanych.

Zgoda jest dobrowolna i możesz ją w dowolnym momencie wycofać w ustawieniach zaawansowanych.

Ponadto masz prawo żądania dostępu, sprostowania, usunięcia lub ograniczenia przetwarzania danych. W polityce prywatności znajdziesz informacje jak zakomunikować nam Twoją wolę skorzystania z tych praw.

Cele przetwarzania Twoich danych bez konieczności uzyskania Twojej zgody w oparciu o uzasadniony interes PanWybierak.pl oraz informacje o możliwości sprzeciwienia się takiemu przetwarzaniu znajdziesz w polityce prywatności.
Szczegółowe informacje na temat przetwarzania Twoich danych znajdują się w polityce prywatności.

Używamy cookies i podobnych technologii m.in. w celach: świadczenia usług, reklamy, statystyk. Korzystanie z witryny bez zmiany ustawień Twojej przeglądarki oznacza, że będą one umieszczane w Twoim urządzeniu końcowym. Pamiętaj, że zawsze możesz zmienić te ustawienia. Szczegóły znajdziesz w [polityce prywatności](https://panwybierak.pl/regulamin/polityka-prywatnosci-panwybierakpl/10).

Ustawienia zaawansowane
[Ustawienia cookies](https://panwybierak.pl/)

**Comment by krystian3w** [comment]
Ja nie mam, proszę dokładny link dla @hawkeye116477

**Comment by hawkeye116477** [comment]
Zgadza się, nic tam nie ma. Proszę zaktualizować wszystko oraz wyłączyć i włączyć komputer :smile:.

> blokowanie sieciowo plików strony może wymagać usunięcia jej pamięci podręcznej

W tym przypadku sieciowa blokada jest tylko w celu odblokowania scrollowania, a sam komunikat jest kosmetycznie ukrywany.

**Comment by xxcriticxx** [comment]
test link:
https://panwybierak.pl/oferty-internet-warszawa/46,918123

![Capture](https://github.com/MajkiIT/polish-ads-filter/assets/15007183/3606a8e7-a183-4972-9648-0ef18fac9f5b)

**Comment by xxcriticxx** [comment]
Mam ubo 1.51.0 i edytowane filtry ciastek Polskie Filtry RODO-Ciasteczkowe 10,224 used out of 10,243 i dalej mam cookies 

problemem jest chyba jezyk USA/Canada

**Comment by krystian3w** [comment]
Chwyć to Pickerem i sprawdź co wypluje:

https://github.com/gorhill/uBlock/wiki/Element-picker

Dodatkowo sprawdź czy nie masz odblokowanego OKA dla strony:

https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering

Potem, czy masz poprawnie zaznaczone pola:

![obraz](https://github.com/MajkiIT/polish-ads-filter/assets/35370833/c0b18db0-b48d-4a23-81ce-b77769fe9097)

**Comment by xxcriticxx** [comment]
Opcja „zawieś aktywność sieciową” nie była zaznaczona. To ustawienie nie jest wybrane spośród ustawień domyślnych w ubo. Dzisiaj magicznie wszystko zaczęło działać. Podejrzewam, że aktualizacja filtrów w ubo zajęła trochę czasu.
