### ISSUE TITLE
Allegro.pl 

### ISSUE THREAD

**Issue by Genki-pl** [MajkiIT/polish-ads-filter#21984]
Strona: https://allegro.pl/oferta/ariel-pods-kapsulki-do-prania-color-72-szt-13619787803

Kilka nieblokowanych sekcji z reklamami.

![Zrzut ekranu 2023-09-17 012701](https://github.com/MajkiIT/polish-ads-filter/assets/93094131/a850a4f2-0be3-41c0-9ffb-cb117d42ed81)

![Zrzut ekranu 2023-09-17 012714](https://github.com/MajkiIT/polish-ads-filter/assets/93094131/b2e5a2cc-6012-428f-8bdb-cf1acbea94e8)

![Zrzut ekranu 2023-09-17 012732](https://github.com/MajkiIT/polish-ads-filter/assets/93094131/fa1e1de1-9447-45b2-9c38-6fce23289087)

![Zrzut ekranu 2023-09-17 012743](https://github.com/MajkiIT/polish-ads-filter/assets/93094131/62425cf7-7da3-4949-b08d-5d652fa1630a)

**Comment by hawkeye116477** [comment]
Jedno zgłoszenie na tę samą stronę raczej wystarczy... (https://github.com/MajkiIT/polish-ads-filter/issues/21983).
