### ISSUE TITLE
zrabatowani.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2198]
ad block 

![capture](https://cloud.githubusercontent.com/assets/15007183/23192589/4b2158ce-f872-11e6-9d92-f6027a5c63c9.PNG)

**Comment by MajkiIT** [comment]
`zrabatowani.pl###popup-adblock-bottom`

**Comment by F4z** [comment]
U mnie nadal jest komunikat o adblocku.

![image](https://cloud.githubusercontent.com/assets/11742596/23263569/e72f1c8e-f9de-11e6-841d-4fa1d923f033.png)

Może tak?
`@@||zrabatowani.pl/assets/js/ads.js$script`
