### ISSUE TITLE
allegro.pl 

### ISSUE THREAD

**Issue by Genki-pl** [MajkiIT/polish-ads-filter#21983]
Strona: https://allegro.pl/kategoria/srodki-do-prania-kapsulki-i-tabletki-do-prania-260126

Kilka nieblokowanych sekcji z reklamami.

![Zrzut ekranu 2023-09-17 011927](https://github.com/MajkiIT/polish-ads-filter/assets/93094131/7f78743e-2480-473e-8f28-8b9a83a5b3a0)

![Zrzut ekranu 2023-09-17 012026](https://github.com/MajkiIT/polish-ads-filter/assets/93094131/e92eec17-0ca8-4c57-a975-fb47e8e1221d)

![Zrzut ekranu 2023-09-17 012106](https://github.com/MajkiIT/polish-ads-filter/assets/93094131/42f72157-4662-48de-a64a-de39d71b40eb)

![Zrzut ekranu 2023-09-17 012210](https://github.com/MajkiIT/polish-ads-filter/assets/93094131/9e8fc8b0-000a-40ee-9025-9ad702962552)

**Comment by xxcriticxx** [comment]
see https://github.com/MajkiIT/polish-ads-filter/issues/21984
