### ISSUE TITLE
in the news 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#22]
http://diver.net.pl/abp

Filtry regionalne - polskie:
• Adblock Polska + Easy List (globalna lista)
• AdblockList.org -Polish Adblock Plus filter
• fanboy-polish-addon + Fanboy Adblock list
• Polskie Adblock (certyficate.it)
• MRC
• PLgeneral
• BSI Lista Polska

**Comment by MajkiIT** [comment]
thanks
