### ISSUE TITLE
Grupa - netstel

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#22002]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [X] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Comodo Dragon Version 116.0.5845.141 (64-bitowa)

### Bloker (Blocker)

uBlock Origin 1.52.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

calc.pl

odleglosci.info

liczebnik.pl

polonia.org

wypracowania24.pl/

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by hawkeye116477** [comment]
Wszystkie domeny grupy:
`calc.pl,ciufcia.pl,czaslotu.pl,dobaku.pl,docelu.pl,dojazd.org,dzidzius.pl,edodatki.pl,edupress.pl,eduranking.pl,eszkola.pl,filmnet.pl,flog.pl,fotoszukacz.pl,gwiazdor.pl,iglo.pl,interpunkcja.pl,irss.pl,krzyzowki.edu.pl,liczebnik.pl,lokmed.pl,mapa.info,materialy-budowlane.pl,meble.info,mojeprodukty.pl,mpcforum.pl,msze.info,naukowiec.org,odleglosci.info,ops.pl,ortograf.pl,photoblog.pl,pobierz.pl,polonia.org,polonista.pl,polscylekarze.org,polscyprawnicy.org,polski-slownik.pl,procesor.pl,przepisy24.pl,pupilek.pl,ratusz.pl,rozmiar.com,rymy.eu,sanatorium.pl,streszczenia.pl,synonim.pl,szkola.net,taniataxi.com,trasa.info,tvsport.pl,weekendowo.pl,wycieczka.pl,wypracowania.pl,wypracowania24.pl,wyznacz.pl,wyznaczanie-trasy.pl,xforex.pl,zyciorysy.pl,zyczenia.pl`

**Comment by blocker999** [comment]
Sporo tego i pewnie pojawią się nowe w przyszłości, dlatego proponuję dodać regułe ogólną : `##.qc-cmp2-main:lang(pl)`

**Comment by krystian3w** [comment]
O nie nie. Ten lubi blokować zaznaczanie tekstu na stronie i lepiej blokować sieciowo.
