### ISSUE TITLE
RODO - różne

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#22008]
### Opis sprawy (Case description)

iotwock.info

kartuzy.info

egarwolin.pl

plonszczak.pl

bolec.info

goral.info.pl

powiatowa.info

koscierski.info

powiatowa.info

Proponuje dodać regułę ogólną : `##.qc-cmp2-main:lang(pl)`

#22002

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines)).

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/22002#issuecomment-1807255045

Jak znajdziesz metodę wykrycia czy pop-up zablokował zaznaczanie, inaczej trzeba sieciowo wycinać.
