### ISSUE TITLE
telemagazyn.pl/vod

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#22009]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Comodo Dragon Version 116.0.5845.141 (64-bitowa)

### Bloker (Blocker)

uBlock Origin 1.52.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

![2023-10-01 18 05 25 telemagazyn pl 26b5d50362c6](https://github.com/MajkiIT/polish-ads-filter/assets/23176832/1bdaf2de-3b18-494e-940f-5c4d1770df3e)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by garry-ut99** [comment]
U mnie błędu nie ma, natomiast są puste kontenery po reklamach :

![ss_17](https://github.com/MajkiIT/polish-ads-filter/assets/72945564/474f2d9c-001b-4653-969d-3b642818edd2)
![ss_18](https://github.com/MajkiIT/polish-ads-filter/assets/72945564/09163319-9c23-4a8a-9020-86efee8f842b)
![ss_19](https://github.com/MajkiIT/polish-ads-filter/assets/72945564/fb6108a0-02e7-4571-a1b6-4f32b30df7b6)
![ss_20](https://github.com/MajkiIT/polish-ads-filter/assets/72945564/54826d23-49bf-4084-9881-04d906d38042)

**Comment by krystian3w** [comment]
On to pewnie rozmazał by pokazać jakim jest mistrzem "painta" i uszlachetnić prokrastynację listy.
