### ISSUE TITLE
olx.pl 

### ISSUE THREAD

**Issue by wiktorhek** [MajkiIT/polish-ads-filter#22011]
### Opis sprawy (Case description)

Proszę dodać opcję umożliwiającą usywanie elementów wyróznionych na stronie OLX.PL
Wyświetla się tego stanowczo zbyt dużo.

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines)).

**Comment by wiktorhek** [comment]
W międzyczasie sobie stworzyłem następującą regułę.
`www.olx.pl##div[data-cy^="l-card"]:has(a > div > div > div > div > div > div > div:has-text(/Wyróżnione/))`

**Comment by krystian3w** [comment]
Self-promo czy na krawędzie reklamy zewnętrznej?

**Comment by garry-ut99** [comment]
> @wiktorhek : Proszę dodać opcję umożliwiającą usywanie elementów wyróznionych na stronie OLX.PL
Wyświetla się tego stanowczo zbyt dużo.

Możesz podyskutować o tym również tutaj : 
- https://github.com/easylistpolish/easylistpolish/issues/3150
