### ISSUE TITLE
wyborcza.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2202]
**4 elementy**

1. zaznaczona na zielono to właściwie drobiazg no ale istotny mianowicie brak loga na szarym kwadraciku bo blokuje ją ta reguła :  `##[href*=".hit.gemius.pl"]`

2. to reklamy, zaznaczone na czerwono

3. i 4. zaznaczone na pomarańczowo, to info, no i nie wiem co z tym zrobić, więc zostawiam to do waszej oceny i proszę o ewentualne uwagi.

![gw](https://cloud.githubusercontent.com/assets/23176832/23212967/621d25f2-f909-11e6-95c9-c006a37b2906.jpg)

**Comment by MajkiIT** [comment]
@blocker999 to masz na stronie głównej?

**Comment by blocker999** [comment]
Nie ale w artykule, konkretnie tu : 

http://wyborcza.pl/7,75398,21402577,drzewo-to-sprawa-publiczna-politycy-powstrzymaja-wycinke.html

**Comment by MajkiIT** [comment]
@blocker999 ok dzięki.

Na pewno potrzebne to
wyborcza.pl##.mod-generic

**Comment by F4z** [comment]
@MajkiIT `##.mod-generic` wytnie za dużo na stronie głównej `wyborcza.pl`

**Comment by F4z** [comment]
Może tak?
`wyborcza.pl##[class^="mod-generic"][class*="la-http\:\/\/wyborcza\.pl\/"]`
`wyborcza.pl##.right-content-holder > [class^="mod-generic"][class*="la-http\:\/\/wyborcza\.pl\/"] + #rectangle-splint`
