### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by Tasiorsa** [MajkiIT/polish-ads-filter#22032]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [X] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
dowolny film na youtube
```

### System operacyjny (Operating system)

Windows 11

### Przeglądarka internetowa (Web browser)

Firefox 115.3 ESR

### Bloker (Blocker)

Adguard 4.2.189

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. Włączone wszystkie Polskie filtry w Adguard 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Pojawia się taki komunikat https://static.wirtualnemedia.pl/media/images/2013/imagesnew/youtubeblokujeadblocki-655.jpg
Nie regularnie przy próbie odpalenia dowolnego filmu

### Zasady pisania (Writing rules)

- [x] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by garry-ut99** [comment]
- po pierwsze czy jesteś pewien, że ten komunikat anty-adblockowy jest spowodowany przez polskie listy?
   - poodznaczaj polskie listy i sprawdź czy dalej będzie wyskakiwał
   - jak dalej będzie, to zgłaszaj na [AdGuard](https://github.com/AdguardTeam/AdguardFilters/issues/162262) (chyba, że już zgłosiłeś)
- po drugie, nawet jak nie będzie, to tutaj i tak już nikt nie naprawia anty-adblocków od dłuższego czasu

**Comment by Tasiorsa** [comment]
Nikt nie naprawia bo jest zakazane czy teraz odbywa się to gdzie indziej?

**Comment by xxcriticxx** [comment]
@Tasiorsa teraz jest o tym glosno na kazdym forum/social media portal. ta gra w kota i myszke jeszcze troche potrwa.

https://www.reddit.com/r/uBlockOrigin/comments/173jmog/youtube_antiadblock_and_ads_october_09_2023/

**Comment by Tasiorsa** [comment]
Tam trafiłem - zmieniłem na uBlock Origin i jest OK.
Napisałem tutajo bo dawniej zawsze tu zgłaszałemn i dostawałem odpowiedź :-)

**Comment by garry-ut99** [comment]
> Tasiora : Nikt nie naprawia bo jest zakazane czy teraz odbywa się to gdzie indziej?

Bo osoba która zajmowała się polską listą anty-adblockową i polską listą privacy, od ponad roku jest nieaktywna, więcej info na ten temat w poprzednim wątku:
- https://github.com/MajkiIT/polish-ads-filter/issues/21962

> Tasiora : Tam trafiłem - zmieniłem na uBlock Origin i jest OK.

Skoro tak, to jak coś to w  repozytorium uBlock Origin naprawiają youtube.com na bieżąco w tych wątkach:
- (stary) https://github.com/uBlockOrigin/uAssets/issues/7636
- (nowy) https://github.com/uBlockOrigin/uAssets/issues/19976

Trochę mi się chce śmiać, bo zamknęli stary wątek, bo za dużo komentarzy było, i myśleli że jak w nowym wątku wstawią instrukcje, to mniej spamu będzie, a i tak jest tyle samo spamu bo ludzie i tak nie czytają instrukcji bo mają w dupie albo są za głupi, byle szybciej itp. i nowy wątek rozrata się jak stary.

**Comment by Tasiorsa** [comment]
Dziękuję za info. Temat wyczerpany na teraz

**Comment by gzenio22** [comment]
Zmieniłem / kupiłem sobie licencje adguarda i nie żałuje miło że ktoś tu o mnie nadal pamięta :D

**Comment by garry-ut99** [comment]
Ale przecież Tasiorsa mówi, że na Adguard ma anty-adblocka na youtube i dlatego zmienił na uBlock Origin, ciekawe czy ty też masz anty-adblocka na youtube.

**Comment by gzenio22** [comment]
> Ale przecież Tasiorsa mówi, że na Adguard ma anty-adblocka na youtube i dlatego zmienił na uBlock Origin, ciekawe czy ty też masz anty-adblocka na youtube po AdGuardem.

Nie mam ale zaznaczam ze uzywam natywnej apki adguarda na PC nie wtyczki do przeglądarki

**Comment by Tasiorsa** [comment]
Obecnie youtube działa popprawnie zarówno na uBlock Origin jak i Adguard
