### ISSUE TITLE
livetv.sx

### ISSUE THREAD

**Issue by lica98** [MajkiIT/polish-ads-filter#22034]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
livetv652.me
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Chrome

### Bloker (Blocker)

Adguard

### Używane listy filtrów (Used filter lists)

Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

the issue is that Polish filter blocks the live streams

how to reproduce: 
go to livetv652.me, select a match 
![image](https://github.com/MajkiIT/polish-ads-filter/assets/74957561/e3923ecc-b3f3-47cd-95b4-5e0f0163df2a)

find a stream that says "Aliez" next to it (it appears when you hover the mouse on stream link)
![image](https://github.com/MajkiIT/polish-ads-filter/assets/74957561/45adffa7-daea-48bb-bdee-f1b04097cc7d)

open the stream and it is blocked 
![image](https://github.com/MajkiIT/polish-ads-filter/assets/74957561/23735532-ad63-4e58-aff0-f962582ec448)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
@MajkiIT ?

**Comment by garry-ut99** [comment]
@lica98 is the issue still actual ? I'm asking because:
- `livetv.sx` domain doesn't exist anymore
- `livetv652.me` redirects to `livetv739.me`
- I'm unable to find a link to reproduce - can't find a stream with "Aliez", 
I see only "Web" and "YouTube", could you provide a stream with "Aliez" to reproduce?
