### ISSUE TITLE
tech.wp.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#22039]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [X] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Comodo Dragon Version 116.0.5845.141 (64-bitowa)

### Bloker (Blocker)

uBlock Origin 1.52.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

( pasek )

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Może @hawkeye116477 ma pomysł czy pasek ucinać, bo pewnie drugi kliker do klikania w X byłby be jak nie da się ustawić by startował po kliknięciu w "przechodzę".

**Comment by hawkeye116477** [comment]
Może coś w tym stylu => `wp.pl##div:has(div:matches-css-after(content: /Klik/))`.

**Comment by krystian3w** [comment]
Odpada, maskują już tekst spacjami i jakimiś magicznymi znakami:

`K \t2453 l \t2353...`

Teoretycznie może @gomoku zgłosi skargę do uAssets, bo to na jego prośbę pasek wraca:

```adb
wp.pl,money.pl,pysznosci.pl,pudelek.pl,gadzetomania.pl,fotoblogia.pl,komorkomania.pl,dobreprogramy.pl,autokult.pl#@#+js(trusted-set-cookie, WPdp, lqqF1M2OyFTVgpTDxpTVkNdThICHBgVTktTN0BdWV1HQEldVV1AXCxTQFMcHlNLXV1TAQVTVkJdTgUCTktAWkhFVUdGVEdHVEBGEV1TOCFTVgpTDxpTVkBdThICHBgVTktTNyxTQFMcHlNLXV1TAQVTVkJdTgUCTktAWkhFVUdGVEdHVEBGEV1TOyE8TksKThIaTktDQFMSHwEYCFNLTipAQERdWl1JQEhdXUEsTl1TAQNTVkBdThwFTktCQFMFH1NLXUdIWEhHW0lHWklAW11TGRBTVkAMEQ==)
wp.pl,money.pl,pysznosci.pl,pudelek.pl,gadzetomania.pl,fotoblogia.pl,komorkomania.pl,dobreprogramy.pl,autokult.pl#@#+js(trusted-set-cookie, WPtcs2, CPyPo8APyPo8ABIACCPLDPCgAAAAAH_AAB5YAAATFAJMNS4gC7AgZCbQMIoUQIwrCAigUAAAAkDRAQAuDAp2RgE-sBkAKEUARwQAhgBRkACAAACAJCIAJAiwQAAQCAQAAgAQCAQAEDAAKACwEAgABAdAxTCgAUCwgSICIhTAhKgSCAlsqEEoLpBXCAIssAKARGwUACIAARWAAICxcAwRICVCQQJdQbQAAEACAUSoViCT00ACgkbLUAAA.YAAAAAAAAAAA)
wp.pl,dobreprogramy.pl,pysznosci.pl#@#+js(trusted-set-cookie, WPcbadcp, $now$)
```

Kombinacja tych 2-3 zamyka pop-up szybciej niż klikanie ale generuje nam pasek.

Zobaczmy czy to padnie za 2-3 dni.
```adb
wp.pl,money.pl,pysznosci.pl,pudelek.pl,gadzetomania.pl,fotoblogia.pl,komorkomania.pl,dobreprogramy.pl,autokult.pl##body > div > div:empty:matches-css(after, content: /K/) ~ div > svg:upward(2)
```

**Comment by garry-ut99** [comment]
>  bo to na jego prośbę pasek wraca.

Sratatata, brzmi jak szukanie kozła ofiarnego, a on tylko zgłaszał reklamy i problemy, żadnych filtrów nie proponował, oni naprawili to po swojemu, próbowali na różne sposoby, ale widocznie nie udało im się naprawić, bez efektu ubocznego w postaci paska, następujących problemów:
- złośliwe reklamy przekierowujące typu timer
- problemy z wejściem/kliknięciem w artykuły

Z dwojga złego, lepszy ten pasek niż te 2 wyżej wymienione problemy, które były o wiele bardzie uciążliwe,
jeżeli ktoś zna lepsze rozwiązanie, to może im zaproponować.

> nie umiem zakładki moje filtry zmusić by je dezaktywowała, więc trzeba to testować z loggera z trybem "Autora".

Naprawione 4 dni temu w rc8 : https://github.com/uBlockOrigin/uBlock-issues/discussions/2895#discussioncomment-7566581, więc masz jakąś starą wersję.

**Comment by krystian3w** [comment]
Dalej się nie słucha a stronę można zmienić, jest łagodniejszy Onet lub Interia.
