### ISSUE TITLE
dziennikwschodni.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#2203]
Adblock:
`http://www.dziennikwschodni.pl/pulawy/zderzenie-na-skrzyzowaniu-kierowca-ze-zlamana-noga-w-szpitalu-zobacz-moment-wypadku,n,1000194736.html`

![image](https://cloud.githubusercontent.com/assets/11385099/23214669/dfe98f4c-f90f-11e6-8edd-ef0926f9fce6.png)

**Comment by xxcriticxx** [comment]
@mathew85 umnie jest ok masz script?

**Comment by mathew85** [comment]
Ze skryptem i filtrami to samo.

**Comment by xxcriticxx** [comment]
@mathew85 jaki script masz?

**Comment by MajkiIT** [comment]
U mnie teź ok.

**Comment by mathew85** [comment]
Rzeczywiście jest OK. AdGuard mi działał w tle i wygląda, że przez niego.
