### ISSUE TITLE
zwierciadlo.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2204]
reklamy

**Comment by xxcriticxx** [comment]
@blocker999  chyba chodzi o `http://zwierciadlo.pl/` przez `L`

sorry zablendy

**Comment by blocker999** [comment]
Dokładnie to przez l, przecież niema adresów z polskimi znakami, więc będe uważał na przyszłość.

@xxcriticxx  Dzięki za słuszną uwage

**Comment by xxcriticxx** [comment]
my pleasure

**Comment by MajkiIT** [comment]
zwierciadlo.pl###superTopWrapper
zwierciadlo.pl##.srodtekstimg
