### ISSUE TITLE
myradioonline.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#22052]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [X] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://myradioonline.pl/open-fm
```

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Netscape Navigator 9.0.0.6

### Bloker (Blocker)

Blocker

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
najlepiej zrobić kopię do uAssets i AdGuard jak Oleg nie wróci do tygodnia czasu.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/18578

**Comment by krystian3w** [comment]
https://github.com/hufilter/hufilter-dev/issues/427

**Comment by krystian3w** [comment]
Z tego można wziąć pomysł dla fantyków ABP:

https://github.com/AdguardTeam/AdguardFilters/commit/32a7c1d1561167efadd7ca0d10f1dfc6759e7955

**Comment by garry-ut99** [comment]
> jak Oleg nie wróci do tygodnia czasu.

Haha, skont wiedziałeś, że wróci za tydzień, jak widać trafiłeś, bo wrócił tydzień temu i chyba naprawił tego anty-adblocka : https://github.com/olegwukr/polish-privacy-filters/commit/e2d8fa4e768cd246583bd37387abc70542d7c8a
