### ISSUE TITLE
allegro.pl

### ISSUE THREAD

**Issue by tomeczeka** [MajkiIT/polish-ads-filter#22067]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
allegro.pl
```

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

FF 119

### Bloker (Blocker)

uBlock Origin 1.52.2

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. Annoaynces - Adguard+easylist+ublcok
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Myślę, że warto żeby wyniki wyszukiwania sponsorowane i promowane były klasyfikowane jako reklamy

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by hawkeye116477** [comment]
Od tego kiedyś był https://github.com/maciejtarmas/AlleBlock.

**Comment by garry-ut99** [comment]
> tomeczeka : Myślę, że warto żeby wyniki wyszukiwania sponsorowane i promowane były klasyfikowane jako reklamy

Możesz podyskutować o tym tutaj : 
- https://github.com/easylistpolish/easylistpolish/issues/3150

**Comment by garry-ut99** [comment]
> Od tego kiedyś był [AlleBlock](https://github.com/maciejtarmas/AlleBlock).

Znalazłem jakiegoś forka: https://github.com/CrusheerPL/AlleBlock, ostatnie zmiany 4 miesiące temu, nie jest super aktualny, ale napewno świeższy od oryginału: `https://raw.githubusercontent.com/CrusheerPL/AlleBlock/master/alleblock.txt`

**Comment by xxcriticxx** [comment]
@garry-ut99 here is a newer version https://github.com/CrusheerPL/AlleBlockV2

**Comment by garry-ut99** [comment]
O to super.

**Comment by garry-ut99** [comment]
Na uAssets ktoś zgłosił, że filtr z polskiej listy psuje coś na Allegro :
- https://github.com/uBlockOrigin/uAssets/issues/22819
