### ISSUE TITLE
pilkanozna.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2206]
Reklamy

**Comment by MajkiIT** [comment]
`||pilkanozna.pl/images/r-gol/$image`

**Comment by blocker999** [comment]
ok, dzięki ale bardziej chodziło mi o reklame "STS" która jest np w tym artykule:
`
http://pilkanozna.pl/index.php/Wydarzenia/Ekstraklasa/909261-ukasz-bro-dla-pn-nie-czuj-si-gorszy-od-jdzy.html`

**Comment by MajkiIT** [comment]
||pilkanozna.pl/images/r-gol/$image
||pilkanozna.pl/images/reklamy_*.jpg$image
pilkanozna.pl###bglink
