### ISSUE TITLE
ciemnastrona.com.pl 

### ISSUE THREAD

**Issue by Bob-A-Dook** [MajkiIT/polish-ads-filter#22063]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://www.ciemnastrona.com.pl/2021/01/10/ciekawe-czasy#reklamy
```

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Firefox 119.0

### Bloker (Blocker)

uBlock Origin 1.52.2

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. Inne domyślne od uBO + EasyPrivacy, Peter Lowe's, Malicious URL Blocklist

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Jedna z reguł z listy chowa wszystkie elementy z atrybutem `id="reklamy"`. Mogą przez to znikać zwykłe nagłówki z tekstem „Reklamy”.

![ubo-naglowek](https://github.com/MajkiIT/polish-ads-filter/assets/71295073/0c9b61bd-f564-4202-947a-6d9a4c1d5294)

W linku umieściłem jeden przykład, tutaj mam [inny](https://www.ciemnastrona.com.pl/tags/#reklamy).

ID jest [automatycznie dodawane](https://kramdown.gettalong.org/converter/html.html#auto-ids) do nagłówka na podstawie jego tekstu. Tak działa Kramdown od Jekylla, może też inne silniki, więc sprawa może dotknąć większej liczby stron.

Pozdrawiam i dziękuję za filtry! :)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
@MajkiIT ?

**Comment by MajkiIT** [comment]
@krystian3w dzięki
