### ISSUE TITLE
firstonetv.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2208]
ad block

`https://www.firstonetv.eu/Live/Poland/Discovery-Channel-23`

![capture](https://cloud.githubusercontent.com/assets/15007183/23274367/7d462190-f9d0-11e6-9764-06d2fd5e2f88.PNG)

**Comment by MajkiIT** [comment]
W easylist jest reguła 
`@@||firstonetv.eu/*ad$first-party,script`
