### ISSUE TITLE
nextdns.io

### ISSUE THREAD

**Issue by szarekpl** [MajkiIT/polish-ads-filter#22084]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

nie dotyczy

### Bloker (Blocker)

nie dotyczy

### Używane listy filtrów (Used filter lists)

nie dotyczy

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)
Lista "CertyficateIT-Polish ads filter" nie jest odświeżana od 3 miesięcy

![Schowek01](https://github.com/MajkiIT/polish-ads-filter/assets/45143552/8636f483-83bb-4389-8df0-07bf49023309)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Może nie ma co banować na poziomie DNS, raczej lista polskich domen używanych do reklam nie jest długa i rzadko się rozszerza.

Sprawdź czy plik źródłowy dla HOSTS ma ponad 176 regułek - jak nie ma to musisz polegać na tym co EasyList w liście anglosaskiej wychwyci jako domena/subodmena tylko do reklam.

**Comment by hawkeye116477** [comment]
Nie nazwał bym tego błędem. Po prostu 4 miesiące temu była aktualizacja => https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-pihole-filters/hostfile.txt i więcej nic nowego się nie pojawiło, bo albo nie ma co dodawać nowego albo nie ma na to czasu, bo nawet widać, że ostatnio listę dla adblockerów zaniedbał, tzn. znacznie mniej wrzuca niż w ubiegłych roku, a zgłoszenia często są zamykane przez bota z powodu braku aktywności.

**Comment by garry-ut99** [comment]
> albo nie ma na to czasu, bo nawet widać, że ostatnio listę dla adblockerów zaniedbał, tzn. znacznie mniej wrzuca niż w ubiegłych roku, a zgłoszenia często są zamykane przez bota z powodu braku aktywności.

Dlatego wiele zgłoszeń ostatnio jest przekierowywanych na https://github.com/easylistpolish/easylistpolish/issues?q=sort%3Aupdated-desc i tam są naprawiane, więc proponuję subskrybować dodatkowo `EasyList Polish` jako uzupełnienie do `Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda`.

**Comment by szarekpl** [comment]
@garry-ut99 na nextdns jest tylko ta wspomniana wyżej

**Comment by garry-ut99** [comment]
@szarekpl : Nie pisałem o `nextdns`, odnosiłem się jedynie do zacytowanego fragmentu dotyczącego list dla adblockerów.
