### ISSUE TITLE
swiatleku.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#22081]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [X] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [X] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Comodo Dragon Version 117.0.5938.150 (64-bitowa)

### Bloker (Blocker)

uBlock Origin 1.52.2

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

cookies - blokada scrolla ( błąd )

social - fb ( button )

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
U mnie się przewija, może jak gitlab wykrywają egzotyczne przeglądarki lub systemy.

**Comment by krystian3w** [comment]
@kiboke can you test that page in your Chrome?

For me now bad is generic:

```adb
##.cookies-popup:not(body):not(html)
```

for Chrome - works fine in Firefox.

**Comment by kiboke** [comment]
@krystian3w I see the problem in Firefox as well. Thanks, I'll fix it soon in IDCAC.
