### ISSUE TITLE
wizaz.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#2209]
Reklama
`http://wizaz.pl/forum/showthread.php?t=536466`

![image](https://cloud.githubusercontent.com/assets/11385099/23300210/dca708de-fa84-11e6-8e01-785be84d44c6.png)

+ na dole strony są chyba jakieś reklamy. Tylko nie ładują się do końca:

![image](https://cloud.githubusercontent.com/assets/11385099/23300274/173173a4-fa85-11e6-8f64-c9cfca34f0a8.png)

**Comment by xxcriticxx** [comment]
moze cos takiego

```
wizaz.pl###forum-gad2
||static.wizaz.pl/dynamic/shopping/shopping-kwc.html
```
