### ISSUE TITLE
www.mediamarkt.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#221]
reklama

https://mediamarkt.pl/ad/click/3047/UlpXTkRCTHdQWTMwNDc7L2FjZXItY2FzaGJhY2stZG8tNjAwemw=

https://mediamarkt.pl/ad/click/4009/UlpXTkRCTHdQWTQwMDk7L3Byb21vY2phLXN3aWF0ZWN6bmEtc2Ftc3VuZw==

**Comment by xxcriticxx** [comment]
www.saturn.pl podobne reklamy maybe subdomain

**Comment by MajkiIT** [comment]
to banery. Wywalenie tego spowoduje odcięcie od promocji.
