### ISSUE TITLE
nfz-lodz.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#2210]
Cookie. Strona się nie ładuje.

`https://www.nfz-lodz.pl/dlapacjentow/najczesciej-zadawane-pytania/specjalistyka/4792-zabiegi-refundowane-i-nierefundowane`

![image](https://cloud.githubusercontent.com/assets/11385099/23300445/e1846134-fa85-11e6-8791-8849c6ce1e73.png)

**Comment by gwarser** [comment]
Komunikat jest ukrywany, ale przewijanie nie działa https://www.nfz-lodz.pl/dlapacjentow/profilaktyka/1642-profilaktyka-raka-jelita-grubego
