### ISSUE TITLE
poral.eu

### ISSUE THREAD

**Issue by zdm9981** [MajkiIT/polish-ads-filter#22100]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [X] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://poral.eu/
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Chrome

### Bloker (Blocker)

uBlock Origin 1.53.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Sprawdź z AdGuard, jak w przyszłym tygodniu nie zjawi się @olegwukr to lepiej zgłosić bezpośrednio do uAssets.

**Comment by garry-ut99** [comment]
Adblocka nie mam na Operze, a na Firefoxie wyskakuje nawet z wyłączonym uBO i wyłączoną wbudowaną Ochroną prywatności, więc to po ich stronie jakiś błąd.

Do naprawienia puste kontenery po reklamach :
![ss_10](https://github.com/MajkiIT/polish-ads-filter/assets/72945564/ef772400-dfd4-4b78-969e-60f924727ada)
![ss_12](https://github.com/MajkiIT/polish-ads-filter/assets/72945564/416272ec-f277-4b65-a7a4-5be8f811396a)
