### ISSUE TITLE
obywatel.gov.pl

### ISSUE THREAD

**Issue by Lukjan39** [MajkiIT/polish-ads-filter#22103]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
nie dziala po zalogowaniu
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

edge 119.0.2151.72

### Bloker (Blocker)

adguard 4.2.209

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Nie widzę jak tam się zalogować a `mobywatel.gov.pl` to zupełnie inna domena.

**Comment by Lukjan39** [comment]
nie mobywatel.gov.pl tylko obywatel.gov.pl

takze napisalem w adguard.

**Comment by Lukjan39** [comment]
jednak sprawka jest w samoniszczące ciasteczka firm pierwszych (niezalecane)

co zrobic?

**Comment by krystian3w** [comment]
Te zgłoszenie zamknąć a może @AdamWr poleci regułę do listy własnej typu:
```adb
@@*$stealth,domain=obywatel.gov.pl
```

lub

```adb
@@*$stealth=3p-cookie|1p-cookie,domain=obywatel.gov.pl
```

Na dłuższą metę może się skończyć rezygnacją z trybu Stealth ("Tryb Niewidzialności").
