### ISSUE TITLE
naekranie.pl

### ISSUE THREAD

**Issue by Lukjan39** [MajkiIT/polish-ads-filter#22113]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
brak elementow, komentarzy tez brak
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

edge 19.0.2151.93

### Bloker (Blocker)

adguard 4.2.209

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

![Bez tytułu](https://github.com/MajkiIT/polish-ads-filter/assets/104568362/aeafa6c7-9bf7-4fc3-bc09-7f9d0bae1119)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by Lukjan39** [comment]
juz jest dobrze.

**Comment by krystian3w** [comment]
To można zamknąć, bo bot zrobi to w lutym.
