### ISSUE TITLE
testerzy.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#22116]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [X] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
testerzy.pl
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Każda

### Bloker (Blocker)

AdGuard 7.16.0 Nightly 1

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Przydala by sie opcja wykrywania list filtrow jak w formulazu AdGuarda bo troche tego mam Xd ale znacie mnie juz nie od wczoraj i wiecie ze wam smiecia nie podrzucam ogl strona jest po prostu do po zamiatania :)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by hawkeye116477** [comment]
> Przydala by sie opcja wykrywania list filtrow jak w formulazu AdGuarda bo troche tego mam 

Może kiedyś zobaczę co da się z tym zrobić, ale oczywiście nie będzie to do końca automatyczne, bo trzeba będzie zrobić kopię ustawień i podesłać plik do analizy. W przypadku AG (`https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/Extension/filters/firefox/filters.json`), jak i też uBO (`https://github.com/gorhill/uBlock/blob/master/assets/assets.json`) pewnie nie będzie trudności, z plików z listą list wyciągniemy odpowiednią nazwę listy dla tych identyfikatorów z kopii ustawień. Oczywiście też bezpośrednio na GH tego nie zrobimy, tylko albo na stronce Majkela albo PAF i taki „pomocnik” będzie generował link do zgłoszenia z już wypełnionymi polami.

A co do tych reklam i anty-adblocka, to ja nic nie widzę na uBO.

**Comment by gzenio22** [comment]
Blokada zniknela jak skasowali info o blackfriday na cala strone @hawkeye116477 ale widze ze na belce gornej odnosniki zostaly odciete @krystian3w to wyglada jak cos zwiazanego z PL lista elementow irytujacych

**Comment by krystian3w** [comment]
Nie, to resztka po "Cookies" lub Rodo.

`testerzy.pl###cookieLawModal`

**Comment by krystian3w** [comment]
Na pewno wkurza minie, że teraz DOM inspector nigdzie nie działa dobrze i mam szare tło zamiast strony.

**Comment by krystian3w** [comment]
Ten pop-up to nie reklama zewnętrzna.

**Comment by xxcriticxx** [comment]
rozumiem ale jak to zamknac bo klikanie X tego nie zamyka

**Comment by gzenio22** [comment]
@krystian3w ok popup znikł ale caly czas odnosniki do artykulow i wgl na calej stronie np na gornej belce są nie klikalne a powinny byc
