### ISSUE TITLE
proshop.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#22120]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://www.proshop.pl/Plyta-glowna/ASRock-B650-LiveMixer-Plyta-glowna-AMD-B650-AMD-AM5-socket-DDR5-RAM-ATX/3112586
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Firefox 120.0.1

### Bloker (Blocker)

AdGuard 7.16.0 Nightli 3 (4487)

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

![387451833_899037108279570_399017819702760806_n](https://github.com/MajkiIT/polish-ads-filter/assets/21177361/d6889b7c-c723-4537-accf-5e28d0eef5eb)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by garry-ut99** [comment]
To są reklamy wewnętrzne (self-promo), a takie raczej nie są blokowane na większości listach adblock, chociaż czasem zdarza się, że są.
