### ISSUE TITLE
komorkomania.pl i dobreprogramy.pl

### ISSUE THREAD

**Issue by dev1anceONE** [MajkiIT/polish-ads-filter#22136]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [X] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://komorkomania.pl/blackberry-storm-czyli-kosztowna-przygoda-kanadyjczykow-z-w-pelni-dotykowymi-smartfonami-podroz-w-czasie,6779744784873089a
https://www.dobreprogramy.pl/sms-do-mamy-znany-schemat-nie-traci-popularnosci,6970757633841728a
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Chrome 119

### Bloker (Blocker)

uBlock Origin 1.54.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 💊 Dandelion Sprout's Anti-Malware List
4. KAD - Przekręty
5. Polski Antyirytujący Dodatek Specjalny
6. Polskie Filtry RODO-Ciasteczkowe
7. [更新終了/Deprecated] Anti Anti-adblock Enhancer for AdGuard
8. AdGuard Popups filter
9. Fanboy's problematic-sites
10. https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/Popups/sections/antiadblock.txt
11. https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/AakList.txt
12. https://raw.githubusercontent.com/jkrejcha/AdmiraList/master/AdmiraList.txt
13. https://winhelp2002.mvps.org/hosts.txt
14. Kiss Filters
15. NoCoin Filter List
16. Not on my shift!
17. Online Malicious URL Blocklist
18. Polish Anti Adblock Filters
19. Polish Anti Adblock Filters - supplement for uBlock Origin
20. Polish Privacy Filters
21. Spam404

### Inne rozszerzenia (Other extensions)

Privacy Badger 2023.12.1

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Problem jest jak wejdziemy do artykuły to jest wtedy szara/biała strona, potem jak odświeżymy i przescrollujemy, to też występuje ten problem
https://i.imgur.com/6VOPDxr.png Tutaj screenshot w razie wu, ale no nie ma na nim za wiele

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by garry-ut99** [comment]
Wyłączaj listy jedna po drugiej  i sprawdzaj czy problem nadal występuje, aż namierzysz listę która to powoduje.

**Comment by dev1anceONE** [comment]
> Wyłączaj listy jedna po drugiej i sprawdzaj czy problem nadal występuje, aż namierzysz listę która to powoduje.
Znalazłem, jakby ktoś miał ten sam problem to "uBlock filters – Annoyances" chyba że ktoś to naprawił w ostatnie 14h

**Comment by garry-ut99** [comment]
Możesz to zgłosić w tym wątku, żeby operatorzy listy to naprawili: https://github.com/uBlockOrigin/uAssets/issues/12214

**Comment by krystian3w** [comment]
> 19. Polish Anti Adblock Filters - supplement for uBlock Origin

Można usunąć jak masz w regionach poprawnie aktywowaną listę "POL-2" na anty-adblocki sprzed 2022.

**Comment by garry-ut99** [comment]
@dev1anceONE (ewentulanie @xxcriticxx) złe etykiety, zamień na `błąd`, no i w ogóle możesz zamknąć 
(no chyba, że jednak twierdzisz że masz tam anty-adblocka i reklamy, ale ja nic takiego nie mam)
