### ISSUE TITLE
propozycja, na nowe filtry, do filmikow.

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#2213]
prosze zglosic autorom ublock, aby dali nowe filtry, tzn, aby nie bylo komunikatow na filmikach.

**Comment by xxcriticxx** [comment]
@lukjan32 more info please?

podaj jakie strony please

**Comment by lukjan32** [comment]
na przyklad z wp.pl, na podstronach. i innych stron.

**Comment by F4z** [comment]
Jeśli chodzi o filmy na wp.pl to zostało zgłoszone do twórcy uBlocka, ale na razie nic z tym nie zrobił.
Żeby oglądać filmy na wp.pl możesz użyć tego skryptu - https://x01x012013.github.io/AdBlockProtector/ albo zamiast uBlocka zainstalować Adguarda.

W przypadku innych stron, to musiałbyś podać konkretne adresy, bo nie ma uniwersalnego rozwiązania.

**Comment by xxcriticxx** [comment]
info na temat scriptu znajdziesz tutaj

`http://www.certyficate.it/pomijanie-wykrywania-adblocka-portalach-wp/`

**Comment by lukjan32** [comment]
moze, mysli, jak to zrobic.

**Comment by xxcriticxx** [comment]
raczej niema czasu

**Comment by lukjan32** [comment]
aha.

**Comment by xxcriticxx** [comment]
@lukjan32 podawaj nowe strony my zrobimy reszte

**Comment by lukjan32** [comment]
dobra
