### ISSUE TITLE
dg.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2215]
wielki baner na górze strony.

**Comment by xxcriticxx** [comment]
kocham zapiekanki!

**Comment by got3n** [comment]
Heh! Tak w ogóle to witam wszystkich, właśnie założyłem konto na GitHub i zamierzam regularnie raportować nasze ukochane ads'y... ;-)

**Comment by MajkiIT** [comment]
`dg.pl##.top.banner`

**Comment by MajkiIT** [comment]
@got3n Dzięki i czekamy

**Comment by got3n** [comment]
@MajkiIT Tutaj również.

Ps. Jako, że jestem nowy są tutaj jakieś zasady czy coś o czym powinienem wiedzieć? :)

**Comment by xxcriticxx** [comment]
@got3n narazie niemamy zadnych zasad. ja pisze troche slabo po krajowemu ale napewno sie dogadamy.

**Comment by got3n** [comment]
@xxcriticxx no i elegancko... z niecierpliwością czekam na naszą współpracę!

**Comment by xxcriticxx** [comment]
@got3n zamotuj sobie ten script http://www.certyficate.it/pomijanie-wykrywania-adblocka-portalach-wp/

**Comment by got3n** [comment]
@xxcriticxx dzięki ale chyba mi się nie przyda bo nie korzystam z WP i reszty stron ktróe są tam wymienione.

**Comment by xxcriticxx** [comment]
@got3n ten script tez posiada generic code na wszystkie ad blockery i caly czas jest rozwiany

**Comment by got3n** [comment]
@xxcriticxx Ok, zobaczę jak to hula.

**Comment by xxcriticxx** [comment]
good luck

**Comment by got3n** [comment]
@MajkiIT widzę, że wrzuciłeś nowe filtry ale zapomniałeś dodać dg.pl z góry wielkie dzięki!
