### ISSUE TITLE
geoportal.gov.pl

### ISSUE THREAD

**Issue by antek821** [MajkiIT/polish-ads-filter#22150]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [X] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://www.geoportal.gov.pl
https://mapy.geoportal.gov.pl/imap/Imgp_2.html
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Vivaldi (chromium)

### Bloker (Blocker)

Adguard for Windows - 7.15.1

### Używane listy filtrów (Used filter lists)

1. I don't care about cookies
2. Fanboy's Annoyances
3. EasyPrivacy
4. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
5. Polskie filtry elementów irytujących
6. EasyList Polish

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Na stronie głównej jak i na podstronie z mapami wyświetlają się komunikaty o ciasteczkach:
Strona główna:
![image](https://github.com/MajkiIT/polish-ads-filter/assets/77172951/78e59101-93a0-4f0b-87e3-0b74c59f572a)

Podstrona z mapami:
![image](https://github.com/MajkiIT/polish-ads-filter/assets/77172951/ba00627b-639c-4dc5-b4a3-c1aa819856f2)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
mapy w dodatku:
https://github.com/FiltersHeroes/PolishCookieConsent/blob/master/README.pl.md#jak-zainstalowa%C4%87

Zaktualizuj filtry w nim lub przeinstaluj.

----

PR dodający wsparcie dla uBo 1.50+ mile widziany w:

https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/edit/master/sections/adblock_cookies/uBO_AG/komunikaty_suplement.txt

lub uAssets: https://github.com/uBlockOrigin/uAssets/edit/master/filters/annoyances-cookies.txt
