### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2217]
Ten problem mam już od co najmniej 2 miesięcy... komunikat o cookies pojawia się pomimo, że mam też aktywne nasze filtry do ciasteczek. Ma ktoś ten sam problem?

![fejs](https://cloud.githubusercontent.com/assets/26026382/23332283/5abbe99a-fb77-11e6-82bc-5001f39cbe1a.png)

**Comment by MajkiIT** [comment]
tak, musimy złapać regex.

**Comment by got3n** [comment]
No w końcu przynajmniej wiem co jest grane. Dzięki za info.

**Comment by F4z** [comment]
Taka reguła jest na liście `Prebake - Filter Obtrusive Cookie Notices`:
`facebook.com##.pam.fbPageBanner._3d9x.uiBoxGray.bottomborder`
Z tego co widzę, to działa.

**Comment by MajkiIT** [comment]
@F4z Dziękuje

**Comment by got3n** [comment]
@MajkiIT sprawdziłem u siebie tą regułę co F4z dodał i działa elegancko!
