### ISSUE TITLE
sport.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2219]
Zawsze spoko wiedzieć, że ma się nową pakernię w mieście... ;-)

![1](https://cloud.githubusercontent.com/assets/26026382/23333004/0441b290-fb84-11e6-9d9e-2ad49c5de3ba.png)

**Comment by xxcriticxx** [comment]
@got3n nie widze tego

**Comment by xxcriticxx** [comment]
@got3n wyloncz u siebie acceptable ads please

**Comment by got3n** [comment]
Hmm... faktycznie po wyłączeniu "Acceptable Ads" znikło. Ale kurde chciałbym zatrzymać to.

**Comment by xxcriticxx** [comment]
rekomenduje zebys zamontowal ublock origin

**Comment by got3n** [comment]
@xxcriticxx  Tak wiem, że uBlock origin jest świetny nawet testowałem swego czasu przez chwilę. Ale jednak zostanę przy "AdBlock" jakoś najbardziej mi pasuje. 

Nie ABP, nie uBlock ani Adguard tylko właśnie AdBlock.. można powiedzieć, że jestem ich fanem... ;)

**Comment by xxcriticxx** [comment]
ok powodzenia 

zobacz czy teraz znajdziesz jakies strony z reklamami
