### ISSUE TITLE
skrotymeczow.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2220]
Dwie reklamy:

1. FREEBET
![2](https://cloud.githubusercontent.com/assets/26026382/23333241/7aec9eba-fb88-11e6-95a4-77584580459d.png)

2. PEWNE TYPY

![1](https://cloud.githubusercontent.com/assets/26026382/23333242/8b6b88a0-fb88-11e6-8327-4fc01506b7a0.png)

**Comment by MajkiIT** [comment]
||skrotymeczow.pl/media/$image
||betonline.net.pl/images/$image
