### ISSUE TITLE
wylecz.to

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#22218]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [X] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Comodo Dragon Version 117.0.5938.150 (64-bitowa)

### Bloker (Blocker)

uBlock Origin 1.54.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Ten cookies znika po odświeżeniu strony:

https://github.com/MajkiIT/polish-ads-filter/blob/ec03237d3cff0f092756a1e5c5e9907b867ed329/cookies_filters/cookies_uB_AG.txt#L145

Niestety PCC od początku nie obsługiwało odświeżania ale uBo już tak:

https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/blob/80ae37a41ae6b2baedcb8fbfcea61ea714645f62/sections/adblock_cookies/uBO_AG/komunikaty_suplement.txt#L119-L120

**Comment by hawkeye116477** [comment]
> Niestety PCC od początku nie obsługiwało odświeżania

Chyba raczej było odwrotnie => https://github.com/FiltersHeroes/PolishCookieConsent/blob/master/src/content.js#L158.

**Comment by krystian3w** [comment]
W takim wypadku widać kłóci się uBo z PCC, wersja Alpha/Beta używa obu składni `, reload, 1` jak i `set-cookie-reload` dla skryptletu nie czekając na reakcje PCC.

**Comment by hawkeye116477** [comment]
Zgadza się, najwyraźniej ta reguła => `budujmase.pl,drogerium.pl,trec.pl,wylecz.to##+js(set-cookie, rodoHfM, true)` jakoś przeszkadza.

**Comment by krystian3w** [comment]
Drugi zapis wymaga nieco nowszego uBo, więc pewnie do czerwca lepiej zatrzymać oba by tylko sprzęty uruchamiane na 10 minut były problemem.

**Comment by hawkeye116477** [comment]
Wymaga wersji 1.53.0, która była pod koniec października, więc raczej wszyscy zdążyli zaktualizować. No chyba, że ktoś miał wakacje od komputera, to wtedy inna sprawa, ale raczej tego nie powinniśmy liczyć.

**Comment by krystian3w** [comment]
To jeszcze trzebaby zobaczyć czy FiltersRegistry akceptuję październikowy stan i nie odrzuci przez kilka miesięcy `set-cookie-reload` w składni uBo (by uniknąć kopiowania do pliku komunikaty_AdGuard w ich składni).
