### ISSUE TITLE
opieka.farm

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#22219]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [X] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://opieka.farm/jak-wyglada-prawidlowy-zapis-dawkowania-na-recepcie-wyjasniamy/
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Comodo Dragon Version 117.0.5938.150 (64-bitowa)

### Bloker (Blocker)

uBlock Origin 1.54.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

resztki - na głównej i w artykułach, np: https://opieka.farm/jak-wyglada-prawidlowy-zapis-dawkowania-na-recepcie-wyjasniamy/

cookies - ( na dole )

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by garry-ut99** [comment]
Tu omyłowo moderator zdjął etykietę `cookies` zamiast `reklama`  

( jeśli moderator nie poprawi to może to też poprawić  zgłaszający i może edytować swój pierwszy komentarz i odptaszkować `reklama` oraz `cookies`, poczekać chwilę aż bot zdejmie etykietę, a następnie edytować ponownie i zaptaszkować samo `cookies` - wtedy bot przywróci tylko tę etykietę - o ile się nie mylę)

@xxcriticxx @blocker999
