### ISSUE TITLE
datapremiery.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2223]
Nie potrzebna przestrzeń z reklamy

![222](https://cloud.githubusercontent.com/assets/26026382/23333309/042da5ce-fb8a-11e6-942a-6c390eebf5b3.png)

**Comment by MajkiIT** [comment]
datapremiery.pl##.item_top_mock_main

**Comment by F4z** [comment]
@MajkiIT tutaj chyba nadal będzie to puste miejsce - `http://datapremiery.pl/bociany-storks-premiera-filmu-13438/`

**Comment by F4z** [comment]
@MajkiIT może coś takiego?
`datapremiery.pl##.column_center > [class*="mock"]`

**Comment by MajkiIT** [comment]
Dzięki. Już poprawiam. Jak możesz to jak widzisz błąd to otwieraj zgłoszenie wtedy szybciej zobaczę.
