### ISSUE TITLE
vod.tvp.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#22236]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [X] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://vod.tvp.pl/informacje-i-publicystyka,205/teleexpress-odcinki,274125/odcinek-6213,S01E6213,1046121
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Comodo Dragon Version 117.0.5938.150 (64-bitowa)

### Bloker (Blocker)

uBlock Origin 1.54.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Brak przycisku - " odtwórz " i brak wyboru odcinków ( pod spodem )

![telee](https://github.com/MajkiIT/polish-ads-filter/assets/23176832/e72a59b5-8b13-4887-8a2b-d0aaeef610ec)

Winowajcą jest " Polish Privacy Filters " - https://github.com/olegwukr/polish-privacy-filters

Kiedy ktoś to przejmie i zacznie działać ?

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by garry-ut99** [comment]
Znany błąd, był już zgłaszany dwukrotnie, więc nie ma sensu zgłaszać w kółko :
- https://github.com/MajkiIT/polish-ads-filter/issues/21962
- https://github.com/olegwukr/polish-privacy-filters/issues/149

Polska Lista Prywatności jest mało aktywna, jedyne co można zrobić żeby ten błąd naprawić póki co, to do dodać filtry naprawcze do "Moje Filtry".
