### ISSUE TITLE
naekranie.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2224]
Patryk Vega na całej stronie... :X

**Comment by xxcriticxx** [comment]
reklama showmax

![capture](https://cloud.githubusercontent.com/assets/15007183/23333506/98d5d94c-fb5a-11e6-9e41-f70aa0450177.PNG)

**Comment by MajkiIT** [comment]
`||naekranie.pl/wp-content/themes/naekranie/partials/ado/`

Zerkniecie?

**Comment by got3n** [comment]
@MajkiIT Działa.
