### ISSUE TITLE
onet.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2225]
Powrócił słynny potworek... dziwne rzeczy z tym stworkiem raz AdBlock go blokuje a czasami wraca... jakieś pomysły?

![111](https://cloud.githubusercontent.com/assets/26026382/23333631/c20821ec-fb8e-11e6-9607-0daf54c734fd.png)

**Comment by xxcriticxx** [comment]
@got3n ja nic niemam

**Comment by got3n** [comment]
Właśnie dlatego piszę, że dziwna sprawa z tym... bo jak też na innym laptopie z tym samym setup'em też nie mam go.

**Comment by xxcriticxx** [comment]
jakie plugins masz zamontowane? jaki os jaki browser?

**Comment by got3n** [comment]
No więc na tym PC co się pojawił mam Win10+Chrome a na lapku Win 8.1+Chrome. Pluginów żadnych nie mam dodatkowych.

**Comment by xxcriticxx** [comment]
host file?

**Comment by got3n** [comment]
@xxcriticxx co to jest? Sorki, że nie ogarniam.

**Comment by xxcriticxx** [comment]
lista w routerze albo w pliku ktora blokuje reklamy zanim dotrze do twego pc

**Comment by got3n** [comment]
@xxcriticxx no nie podam Ci po zupełnie nie wiem... jak? gdzie? i co? znaleźć.

**Comment by xxcriticxx** [comment]
@got3n lepjej dlanas jak niewiesz

**Comment by got3n** [comment]
@xxcriticxx Hah! Dobrze wiedzieć.

**Comment by MajkiIT** [comment]
@got3n wyczyść cache i ciasteczka.

**Comment by got3n** [comment]
@MajkiIT Nic to nie dało w moim przypadku, no trudno zobaczymy może za kilka dni zniknie samo. Z tym mam największe jaja bo raz jest a raz nie, i weź to zrozum.

**Comment by xxcriticxx** [comment]
@got3n wykasuj browsing history i cookies

**Comment by got3n** [comment]
@xxcriticxx CCleanere'm wyczyściłem wszystkie dane w przeglądarce i też dupa...

**Comment by got3n** [comment]
@xxcriticxx aż z ciekawości wgram na chwile uBO żeby zobaczyć czy działa na to.

**Comment by xxcriticxx** [comment]
@got3n powodzenia podaj info jak poszlo

**Comment by got3n** [comment]
@xxcriticxx No niestety u mnie POTWÓR wciąż górą! A tutaj screen, że wgrałem UBO
![11](https://cloud.githubusercontent.com/assets/26026382/23334658/d43274a2-fba3-11e6-89df-18828f1b201f.png)

**Comment by F4z** [comment]
@got3n po zainstalowaniu uBlocka zaktualizowałeś listy?

**Comment by xxcriticxx** [comment]
@got3n cookies i browsing historia skasuj browserem nie cc. masz jakies inne wtyczki do blokowania? moze jakies firewall czy cos takiego?

**Comment by got3n** [comment]
LOL wyczyściłem ręcznie cookies/historie itc. i w AdBlock'u zadziałało. A ja myślałem, że CCleaner jest taki pro i wszystko ładnie czyści. Co do uBlocka nie wiem bo już usunąłem... ;-)

**Comment by xxcriticxx** [comment]
@got3n strasznie dlugo testowales :)

**Comment by got3n** [comment]
@xxcriticxx tak jak mówiłem, nie mam nic do uBlocka wiem że jest kozacki ale przyzwyczajenie wygrywa i zostaje przy AdBlock'u... ;-) jednak nie wykluczam jeśli w przyszłości będzie znacznie więcej syfu AdBlock przepuszczać niż uBlock to chyba będę zmuszony na stałe się przerzucić. Ale na chwilę obecną jest okej.

@MajkiIT możesz zamykać topic.
