### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2226]
Niepotrzebna przestrzeń po reklamie.

![1111111](https://cloud.githubusercontent.com/assets/26026382/23333732/03549372-fb91-11e6-8bd7-3106cc957cdd.png)

**Comment by xxcriticxx** [comment]
@got3n niewidze tego please zamontuj sobie ubo bo wszyscy bendziemy mieli wiecej roboty

**Comment by got3n** [comment]
@xxcriticxx nie sądzę, że to jest wina AdBlocka przecież chyba nie sądzisz, że wszyscy Polacy używają tylko UBO? ABP i AdBlock są najpopularniejsze.

**Comment by xxcriticxx** [comment]
tak to wyglonda umnie

![capture](https://cloud.githubusercontent.com/assets/15007183/23333881/ea7b41ea-fb61-11e6-9789-0a4a5f05ee87.PNG)

**Comment by got3n** [comment]
No nic pozostaje czekać co @MajkiIT powie na ten temat...

**Comment by xxcriticxx** [comment]
napewno to samo co ja :+1:

**Comment by xxcriticxx** [comment]
wszyscy uzwaja ubo @F4z ma chyba adguarda na laptopie gdzies

**Comment by MajkiIT** [comment]
@got3n 
@xxcriticxx ma rację to pole usuwa reguła 
`dobreprogramy.pl##body#top:style(background: none !important;) `

w Adblocku nie ma takiej możliwości.

**Comment by F4z** [comment]
Niestety w tym przypadku najprawdopodobniej nie da się ukryć tych wszystkich "pustych przestrzeni" przy użyciu Adblocka/Adblocka Plus.
To zaznaczone na obrazku jeszcze się da, na przykład tak:
`dobreprogramy.pl##.page-element.center.target[style="max-width:980px;margin:0px auto 30px auto;"]`
ale z innymi jest problem.
Jeśli się nie mylę, to oni używają skryptu żeby ponownie wczytać/załadować te elementy i przez to nie da się tego ukryć.

Adguard i uBlock Origin mają więcej możliwości niż Adblock/Adblock Plus.

**Comment by xxcriticxx** [comment]
@F4z witamy

**Comment by got3n** [comment]
@F4z Dzięki za obszerne info.

**Comment by lukjan32** [comment]
znow jest puste miejsce, po reklamach.

**Comment by xxcriticxx** [comment]
miejsce jest ale slowa "reklama" nie widzisz?

![capture](https://cloud.githubusercontent.com/assets/15007183/23360567/1aca35f0-fcba-11e6-83f2-b139e3e59b54.PNG)

**Comment by lukjan32** [comment]
slowo reklama jest, a reklamy brak

**Comment by xxcriticxx** [comment]
jaki blocker? jaki browser? jakie filtry? need more info please

**Comment by lukjan32** [comment]
ublock origin. opera 43. najnowsze.

**Comment by xxcriticxx** [comment]
na foxsie i na chromie nic niemam zobaczymy jak bendzie u reszty

**Comment by lukjan32** [comment]
opera, to juz chrome jest.

**Comment by xxcriticxx** [comment]
jaka ver filtrow? masz jeszcze jakis inne plugin do blokowania

ja z ta ver `v.2017022603 aktualizacja: nie, 26 lutego 2017, 22:20:00` nic niemam

**Comment by xxcriticxx** [comment]
ok po updatecje filtrow na chromie wyskoczylo 

czyli na foxie jest ok problem jest z chromem

![capture](https://cloud.githubusercontent.com/assets/15007183/23366378/7361c54c-fcd4-11e6-8212-b239bef8cf39.PNG)

**Comment by lukjan32** [comment]
tak, mam te wersje

**Comment by xxcriticxx** [comment]
stay tune fix bendzie nie dlugo

**Comment by lukjan32** [comment]
ok, czekam

**Comment by caleb59** [comment]
Korzystając z AdGuarda również pojawiło ponownie puste miejsce, sprawę zgłosiłem ponownie na ich forum i dałem znać prywatnie osobie, która się tym zajmowała poprzednio...

**Comment by got3n** [comment]
No i u mnie na AdBlock'u to samo! :)

**Comment by F4z** [comment]
Dla uBlocka:
`dobreprogramy.pl##script:inject(abort-on-property-read.js, Dp.checkNotifications)`
Jak coś będzie nieprawidłowo działać, to proszę zgłaszać.

W przypadku Adguarda trzeba zamienić w regule `unBlocker`na `checkNotifications` i chyba powinno prawidłowo działać, ale oni tam pewnie niedługo odpowiedzą :)

Dla Adblocka nie mam rozwiązania.

**Comment by xxcriticxx** [comment]
dziala w chromie thanks a million @F4z

**Comment by MajkiIT** [comment]
@F4z dzięki

**Comment by lukjan32** [comment]
dzieki
