### ISSUE TITLE
mbank.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2227]
Cookies

**Comment by xxcriticxx** [comment]
@got3n niewidze nic takiego

filtry cookies masz?

**Comment by got3n** [comment]
@xxcriticxx Tak mam.

**Comment by xxcriticxx** [comment]
@got3n screen shot please?

**Comment by got3n** [comment]
@xxcriticxx Do zamknięcia, mój błąd zapomniałem, że mbank.pl mam w whitelist i dlatego cookies wyświetlało. Po włączeniu AdBlocka nie ma komunikatu o cookies.
