### ISSUE TITLE
cgm.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2230]
Reklama Bisz/Radex... :-/

Da się zrobić żeby było całe czarne tło?

**Comment by xxcriticxx** [comment]
@got3n spac nie mozesz?

**Comment by got3n** [comment]
@xxcriticxx Haha... a kto będzie zwalczał reklamy w necie? :D

**Comment by xxcriticxx** [comment]
kacper i bugs bunny

**Comment by MajkiIT** [comment]
To na reklamy
||www.cgm.pl/_vault/_adver/$image,domain=www.cgm.pl

A to na te alerty
||dashboard.push-ad.com/$script,domain=www.cgm.pl

**Comment by got3n** [comment]
@MajkiIT Działają! A i nie zapomnij proszę też o tym dg.pl z wczoraj.

**Comment by MajkiIT** [comment]
@got3n Ok
