### ISSUE TITLE
canva.com 

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#22302]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [X] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://www.canva.com/pl_pl/funkcje/poprawianie-jakosci-zdjec/
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Comodo Dragon Version 117.0.5938.150 (64-bitowa)

### Bloker (Blocker)

uBlock Origin 1.55.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by hawkeye116477** [comment]
@krystian3w W EasyList Cookie dodali dziwną regułą => `##.fFOiLQ.Ekl2FA.RNFNIA._9y-BYQ._1CzyGhb`, która raczej wygląda na losową.

**Comment by krystian3w** [comment]
Oni tak lubią, kolejna wada zagraniczniaków.

**Comment by krystian3w** [comment]
@blocker999 aktywuj sobie `https://ublockorigin.github.io/uAssets/thirdparties/easylist-cookies.txt`:

https://subscribe.adblockplus.org/?location=https://ublockorigin.github.io/uAssets/thirdparties/easylist-cookies.txt&title=EasyList-Cookies

dla zmniejszenia FP że coś jest dalej widoczne a ELC wycięło.

**Comment by krystian3w** [comment]
Może takie coś w PL a ich filtr dezaktywować:

`#?#div[aria-live="polite"]:-abp-has(> div span a[href*="/policies/cookies-policy/"])`
