### ISSUE TITLE
lodz.oglaszamy24.pl

### ISSUE THREAD

**Issue by bobekos1** [MajkiIT/polish-ads-filter#2231]
Reklamy na tej stronie, informacje o używaniu adblocka/ublocka, cookies. Dzięki

**Comment by xxcriticxx** [comment]
@bobekos1 ja nic nie widze. jake filtry? jaki ad blocker? jaki browser? jaki os?

**Comment by bobekos1** [comment]
Ja korzystam z uBlocka origin. Napisz jak mam podać wyżej informacje...? :)

**Comment by xxcriticxx** [comment]
@bobekos1 podaj screena kdzie te reklamy

**Comment by bobekos1** [comment]
Większość sam już schowałem wykorzystując prawy u  myszy i ublock... Jak ci tutaj podać zdjęcie...? :)

**Comment by xxcriticxx** [comment]
print scr na klawiatorce i zucasz tam gdzie piszesz

**Comment by bobekos1** [comment]
![image](https://cloud.githubusercontent.com/assets/25938825/23342703/5dc3f694-fc5f-11e6-8874-7a7b0d5f4516.png)

**Comment by bobekos1** [comment]
![image](https://cloud.githubusercontent.com/assets/25938825/23342704/6da012fa-fc5f-11e6-8b36-0b2b61d93fa2.png)

**Comment by bobekos1** [comment]
dałem specjalnie w nowej przeglądarce żeby było widać jak jest bez ublocka

**Comment by xxcriticxx** [comment]
pokaz mi zdjecie filtry ubo?

**Comment by bobekos1** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/25938825/23342740/1f969af6-fc60-11e6-8d99-1b31977500f2.jpg)

**Comment by bobekos1** [comment]
![bez tytulu 2](https://cloud.githubusercontent.com/assets/25938825/23342743/2b073d00-fc60-11e6-98b8-317c077ca96a.jpg)

**Comment by xxcriticxx** [comment]
nacisni purge all caches i potem update now

jakies inne pluginy do blokoania oprucz ubo?

**Comment by bobekos1** [comment]
Co masz na myśli z tym 1 zdaniem. Korzystam jeszcze z tampermonkey

**Comment by xxcriticxx** [comment]
na topie masz wyczysc wszystkie cache i potem updatej filtry

**Comment by xxcriticxx** [comment]
tm z adprotector scriptem?

**Comment by bobekos1** [comment]
Chodzi ci że mam wyczyścić całą pamięć podręczną w ublocku? Czy po tej czynności i aktualizacji nie znikną mi te filtry które już dodałem?

**Comment by xxcriticxx** [comment]
niepowinny

**Comment by bobekos1** [comment]
Zrobiłem, ublock sam aktualizuje filtry czyli jak robicie jakieś aktualizacje to i same one wchodzą...?

**Comment by xxcriticxx** [comment]
tak ale najlepjej sciagnac najowsza ver recznie

**Comment by bobekos1** [comment]
Ok, ale przed ściągnięciem trzeba usunąć starą czy można zastąpić...?

**Comment by bobekos1** [comment]
Wyczyszczenie pamięci i aktualizacja nic nie dały :/

**Comment by bobekos1** [comment]
Będę musiał sam ukrywać za pomocą myszy reklamy które mi się nie podobają :P

**Comment by xxcriticxx** [comment]
@bobekos1 ta strona niema zadnyczh reklam :)

mozesz zresetowac caly ubo?

**Comment by bobekos1** [comment]
Jak to zrobić?

**Comment by xxcriticxx** [comment]
go to settings potem na samym dole reset to default settings

**Comment by bobekos1** [comment]
Ok ale czy nie wywali mi moich dodanych filtrów?

**Comment by xxcriticxx** [comment]
wykasuje wszystko zaczniesz od nowa

**Comment by bobekos1** [comment]
Ok, co do tych aktualizacji to można lepiej zastąpić tym co wyjdzie to co już jest czy usunąć filtr i ściągnąć go ponownie?

**Comment by xxcriticxx** [comment]
jak zaczniesz od nowa to zaznacz dwie polskie listy zrobic update i zobaczymy jak bendzie

**Comment by bobekos1** [comment]
a ty z czego korzystasz?

**Comment by xxcriticxx** [comment]
z tego samego co ty

**Comment by bobekos1** [comment]
Ok

**Comment by bobekos1** [comment]
Tak się zastanawiam czy to robić, bo na razie tylko na 1 stronie to zauważyłem...generalnie jest b. ok... Sam wbijam na ublocka reklamy które widzę...

**Comment by xxcriticxx** [comment]
poto jest polska lista zebys nic nie musial robic 

cos masz zle tam ustawione dlatego widzisz reklamy

**Comment by bobekos1** [comment]
Ok już to robię :)

**Comment by bobekos1** [comment]
Bez zmian, wszedłem nawet na najpopularniejszą tematykę tej strony...

**Comment by bobekos1** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/25938825/23343584/34daeecc-fc6e-11e6-99af-2d71b3359483.jpg)

**Comment by xxcriticxx** [comment]
masz ublockextra zamontowane albo adblock plus albo host file?

**Comment by xxcriticxx** [comment]
ghostery plugin

**Comment by bobekos1** [comment]
chodzi ci o rozszerzenia w google chrome?

**Comment by xxcriticxx** [comment]
tak 

pobrales najnowsze filtry?

**Comment by bobekos1** [comment]
nic nie robiłem, tylko przywróciłem ustawienia domyślne

**Comment by xxcriticxx** [comment]
ok to teraz dodac dwie polskie listy i updateduj wszystkie filtry

**Comment by bobekos1** [comment]
Mam zainstalowane ublock origin 1.11.0 i Tampermonkey 4.2.7

**Comment by xxcriticxx** [comment]
do czego tm 4.2.7 uzywasz?

**Comment by bobekos1** [comment]
Ja myślałem że chodzi ci o te które już są
![s324432](https://cloud.githubusercontent.com/assets/25938825/23343635/43b98024-fc6f-11e6-8180-e3b0981c3caf.jpg)

**Comment by xxcriticxx** [comment]
na topie jest update now

**Comment by bobekos1** [comment]
https://www.certyficate.it/pomijanie-wykrywania-adblocka-portalach-wp/

**Comment by xxcriticxx** [comment]
ok czy filtry updatowne?

**Comment by MajkiIT** [comment]
@bobekos1 a masz Easylist aktualne oraz AdBlock Protector List?

**Comment by xxcriticxx** [comment]
@MajkiIT ja smierdze na suporcie nikt zemna niechce pisac :)

**Comment by bobekos1** [comment]
gdzie znajde te 2 polskie listy co pisales wczesniej?

**Comment by MajkiIT** [comment]
@bobekos1 wbudowane w Ublock Origin

**Comment by xxcriticxx** [comment]
@bobekos1 to sa te listy co masz zaznaczone

masz moze teamviewer zamonowany bendzie szybcej

**Comment by bobekos1** [comment]
no są aktualne i ten sam problem

**Comment by xxcriticxx** [comment]
zmienailes jakies ustawienja? masz dodatkowe pluginy? masz teamviewer?

**Comment by bobekos1** [comment]
Po przywróceniu ustawień w ublocku tylko te filtry aktualizowałem przyciskiem co jest wbudowany... Chrome mam standardowe... Nie mam

**Comment by xxcriticxx** [comment]
ok stymi filtrami nie powinienies miec wiecej reklam jak wyglonda straona teraz?

**Comment by bobekos1** [comment]
Po przywróceniu ustawień jak mówiłeś, aktualizacji filtrów co są wygląda następująco dla przykładu: 
![ggg](https://cloud.githubusercontent.com/assets/25938825/23343786/293eef2a-fc71-11e6-84ea-11290be62e2a.jpg) ale na 2 stronie znów
![ggg2](https://cloud.githubusercontent.com/assets/25938825/23343796/4dd88cba-fc71-11e6-8756-9f4221e0cf16.jpg)

**Comment by bobekos1** [comment]
myślę że chyba z tym nie wygram :)

**Comment by bobekos1** [comment]
Będę musiał ręcznie usuwać i tyle...

**Comment by MajkiIT** [comment]
@bobekos1 zaktualizuj filtry do wersji 2017022603 i sprawdź

**Comment by xxcriticxx** [comment]
@bobekos1 i zamontuj adportector znowu

**Comment by bobekos1** [comment]
jak szybko zaktualizować...? :)

**Comment by xxcriticxx** [comment]
update now nacisniesz na topie tak jak zawsze

**Comment by bobekos1** [comment]
POL: polskie filtry do Adblocka i uBlocka​​​​​użytych 1 966 z 1 983​​​​
POL: polskie filtry do uBlocka uzupelnienie​​​​​użytych 51 z 55​​ 
Kliknąłem w te zegarki na końcu, następnie u góry mogłem wybrać "aktualizuj teraz" Dobrze? :)

**Comment by MajkiIT** [comment]
powinno być POL: polskie filtry do Adblocka i uBlocka​ ​​​​użytych x z 1 984​​

**Comment by xxcriticxx** [comment]
POL: polskie filtry do Adblocka i uBlocka​​​​​ 1,983 used out of 1,984​​
​​POL: polskie filtry do uBlocka uzupelnienie​ ​55 used out of 55​​​​

**Comment by bobekos1** [comment]
Mam tak: POL: polskie filtry do Adblocka i uBlocka​​​​​użytych 1 967 z 1 984​​​​
POL: polskie filtry do uBlocka uzupelnienie​​​​​użytych 51 z 55​​

**Comment by bobekos1** [comment]
teraz jak wchodzę to jest ok... :)

**Comment by bobekos1** [comment]
@bobekos1 i zamontuj adportector znowu- czy mam dodać?

**Comment by xxcriticxx** [comment]
dodac albo uaktywnic w tampermonkey

**Comment by bobekos1** [comment]
tampermonkey nie ruszałem więc chyba to nadal jest...

**Comment by xxcriticxx** [comment]
wykakuje ci ta wiadomosc o ad block jak kasowales filtry to liste staskowales

**Comment by bobekos1** [comment]
Jak sprawdzić czy jest z nim ok? :)

**Comment by bobekos1** [comment]
Wiem już jak aktualizować szybko wasze filtry ;)

**Comment by xxcriticxx** [comment]
wejdz na strone zobacz czy jest adblock msg

**Comment by bobekos1** [comment]
Jak klikam na ikonę tego rozszerzenia w chrome to mam taki widok: 
![bez tytulu](https://cloud.githubusercontent.com/assets/25938825/23344002/c5533882-fc74-11e6-8c71-45e9b304848b.jpg)

**Comment by xxcriticxx** [comment]
idz tutaj http://www.certyficate.it/pomijanie-wykrywania-adblocka-portalach-wp/ i nacisni na `Install`

Oraz dodać wymagane filtry:

    Install from github.com

**Comment by bobekos1** [comment]
Zrobiłem....?

**Comment by bobekos1** [comment]
mam teraz Specjalne (1)
AdBlock Protector List​​​​​użytych 2 102 z 2 160​​​​

**Comment by bobekos1** [comment]
a tem... nei wiem jak sprawdzić czy jest ok :)

**Comment by xxcriticxx** [comment]
idz do listy odznacz Anti-Adblock Killer | Reek​​​​​​​​​ i potem idz na sam dol i zrub update tego filtra co dodales

**Comment by bobekos1** [comment]
Anti-Adblock Killer | Reek​​​​​​​​​ mam od przywrocenia ustawien odznaczony... :)

**Comment by xxcriticxx** [comment]
ok pokasz zdjecie z tmonkey tak samo jak przedtem

**Comment by bobekos1** [comment]
Robiłem już update jak i tamtych i wynik jest jak wyzej bez zmian :)

**Comment by bobekos1** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/25938825/23344069/3d989ce6-fc76-11e6-9f64-e6a6d346d221.jpg)

**Comment by bobekos1** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/25938825/23344078/5edbdd46-fc76-11e6-884b-c54d33517ef8.jpg)

**Comment by xxcriticxx** [comment]
moment odpale chrome

**Comment by bobekos1** [comment]
ok, ja musze jedzenie do pracy zrobić :P

**Comment by bobekos1** [comment]
zapomniałęm ze jtro praca :P

**Comment by xxcriticxx** [comment]
masz jeszcze zaznaczone reek anti block killer

**Comment by bobekos1** [comment]
w ogóle tego nie mam...?

**Comment by xxcriticxx** [comment]
tak powino wyglondac 

![capture](https://cloud.githubusercontent.com/assets/15007183/23344145/21b4d02a-fc45-11e6-89ea-e5e938f2c118.PNG)

**Comment by bobekos1** [comment]
masz jeszcze zaznaczone reek anti block killer pokaż mi na princie gdzie to znajde... :)

**Comment by xxcriticxx** [comment]
we filtrach ubo

**Comment by bobekos1** [comment]
tak u mnie wygląda: 
![bez tytulu](https://cloud.githubusercontent.com/assets/25938825/23344190/400dd930-fc78-11e6-9b6b-f7caed587eb4.jpg)

**Comment by xxcriticxx** [comment]
ten co na dole dodales zrub udpates

**Comment by bobekos1** [comment]
Specjalne (1)
AdBlock Protector List​​​​​użytych 2 102 z 2 160​​​​ o ten ci chodzi? :)

**Comment by xxcriticxx** [comment]
tak update teraz zrobisz

AdBlock Protector List​​​​​2,105 used out of 2,163​​​​

**Comment by bobekos1** [comment]
zrobiłęm i mam: Specjalne (1)
AdBlock Protector List​​​​​użytych 2 102 z 2 160​​

**Comment by bobekos1** [comment]
chwila, mam już chyba jak wczesniej napisales

**Comment by bobekos1** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/25938825/23344250/55f1e416-fc79-11e6-85d4-8d6d3f40325f.jpg)
tak już mam

**Comment by xxcriticxx** [comment]
ok super teraz zrobisz donation za support link tutaj https://patronite.pl/polskiefiltry

**Comment by bobekos1** [comment]
czyli już jest ok, czy coś jeszcze polecasz? :) znalazłem już namiar na kolejną stronę ale chyba dziś już nie dam rady siedzieć dłużej

**Comment by xxcriticxx** [comment]
polecam donation na https://patronite.pl/polskiefiltry

**Comment by bobekos1** [comment]
a czy muszę robić konto? :) Co mi da konto i po co tak szczegółowe dane...?

**Comment by bobekos1** [comment]
Chętnie pomogę tylko nie lubię podawać imienia i nazwiska bo wiadomo jak to jest w sieci... :)

**Comment by bobekos1** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/25938825/23344442/dce8057e-fc7c-11e6-9a8e-d65e926ebefd.jpg)
Co wybrać?

**Comment by xxcriticxx** [comment]
allways allow domain

**Comment by MajkiIT** [comment]
@bobekos1 to jak chcesz kogoś dotować, jak przelew odpada, no chyba, że płatność ekspresowa, payu, paypal?

**Comment by bobekos1** [comment]
Jak wybrać "allways allow domain" jak już mi się nie pojawia ten komunikat...? Można smsem z telefonu...?

**Comment by MajkiIT** [comment]
@bobekos1 a to by Ci pasowało?

**Comment by bobekos1** [comment]
Tak, do postu mojego wyżej to można to jakoś jeszcze wybrać?

**Comment by MajkiIT** [comment]
Jak wyświetla Ci się komunikat. Nie wiem jak go wywołać. 

@bobekos1 a dotacje przez https://ehat.me/ pasowały by Ci?

**Comment by bobekos1** [comment]
Ja mógłbym pomóc jednorazowo
