### ISSUE TITLE
mmarocks.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2232]
Zerknijcie czy AdBlock nie blokuje wam obrazków i filmów... u mnie wygląda to tak:
![111](https://cloud.githubusercontent.com/assets/26026382/23340145/938aad00-fc31-11e6-818e-90994dd2774f.png)

**Comment by got3n** [comment]
Po wyłączeniu AdBlocka oczywiście wszystko się ładnie wczytuje.

**Comment by xxcriticxx** [comment]
@got3n tylko u ciebie 
![capture](https://cloud.githubusercontent.com/assets/15007183/23340198/31e9924a-fc00-11e6-83d1-91df2a3ec363.PNG)

**Comment by MajkiIT** [comment]
U mnie też jest ok.
