### ISSUE TITLE
hbomax.com

### ISSUE THREAD

**Issue by BigPebble123** [MajkiIT/polish-ads-filter#22337]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [x] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://play.hbomax.com
```

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Firefox 123.0.1

### Bloker (Blocker)

uBlock Origin 1.56.0

### Używane listy filtrów (Used filter lists)

Wszystkie dotępne w uBlock

### Inne rozszerzenia (Other extensions)

SponsorBlock v5.5.6

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Wyskakuje popup z informacją o polityce prywatności.

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Cookie wall, czyli naprawa tylko z pomocą `(trused-)set-*` lub [Polish Cookie Consent](https://github.com/FiltersHeroes/PolishCookieConsent/blob/master/README.pl.md) jak ktoś nie wpadnie co zablokować sieciowo (kompatybilnie z ABP)

**Comment by hawkeye116477** [comment]
W zasadzie to jest międzynarodowa strona, więc Fanboy albo gorhill mogliby się tym zająć :smile:.

**Comment by krystian3w** [comment]
Ale zrobią to wtedy:

```js
consentChoices:
    {
       "allowFunctionalCookies":true,
       "allowPerformanceCookies":false, // a my wolimy true
       "allowTargetingCookies":false,   // a my wolmy true
       "timestamp":"2024-03-10T16:48:57.101Z" // Fin preferuje ustawianie 1970 na początek
   }
```

Albo Fanboye wytną to CSS-em z zignorwaniem, że URL się w tle zmienia z pomocą pushState/replaceState (lub kij wie jakiego innego mechanizmu).

**Comment by hawkeye116477** [comment]
Wygląda na to, że się przeterminowało, bo teraz jest Max zamiast HBO Max.

**Comment by krystian3w** [comment]
Jak dobrze pójdzie to bot zamknie w październiku.
