### ISSUE TITLE
livetv763.me - player is blocked

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#22331]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://livetv764.me/eventinfo/195416313_sassuolo_napoli/#webplayer_alieztv|220678|195416313|2349149|11|1|ru
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Chrome 121

### Bloker (Blocker)

AdGuard 4.3

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

This rule blocks player
`~biblio.com,~milionczesci.pl,~dizibox.com,~2dehands.be,~ru,~ua,~www.pudelek.pl,~btdb.eu,~ewybory.eu##[id^="adv-"]:not(#adv-settings)`

<details>
<summary>Screenshot</summary>

![image](https://github.com/MajkiIT/polish-ads-filter/assets/8361299/7635b2db-0613-4089-b167-64174d806ee1)

</details>

Please note - they change domain every few days (`number_in_domain`+1)

Can be fixed by excluding `me` TLD (`~me,***`).

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
or by `:not(#adv-player)` / `:not(.adv-player-container)` / `:lang(pl)` - if page move into new TLD range e.g. `livetvXXX.icu`.

**Comment by Alex-302** [comment]
> if page move into new TLD range e.g. `livetvXXX.icu`

They use `.me` for years.

**Comment by D4niloMR** [comment]
Is this filter really needed?

See: https://github.com/uBlockOrigin/uAssets/issues/21741

**Comment by krystian3w** [comment]
For me, no, you have to find out when the filter was created and whether it is older than this repository (then the origin is secret or in the comments on MajkiIT's Wordpress).
