### ISSUE TITLE
synonim.net

### ISSUE THREAD

**Issue by BigPebble123** [MajkiIT/polish-ads-filter#22335]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://synonim.net/synonim/blokada
```

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Firefox 123.0.1

### Bloker (Blocker)

uBlock Origin 1.56.0

### Używane listy filtrów (Used filter lists)

Wszystkie uBlock

### Inne rozszerzenia (Other extensions)

SponsorBlock v5.5.6

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Wyskakują trzy reklamy w postaci statycznych obrazków - dwie na górze i jedna na dole.
Zrobiłem filtry uBlock dla tej strony za pomocą element pickera z uBlocka:

```
! 2024-03-06 https://synonim.net
synonim.net###iall
synonim.net##.pion
synonim.net##picture
```

### Zasady pisania (Writing rules)

- [x] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
`##picture` to zły filtr, to tak jakby przed xHTML 2.0 lub (x)HTML 5 blokować wszystkie `##img`.
