### ISSUE TITLE
paypal error 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#22344]
### Opis sprawy (Case description)

@MajkiIT can you fix this?

We can't find that fundraiser
It looks like that fundraiser is no longer available.
[Find another cause](https://www.paypal.com/generosity-network)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines)).

**Comment by hawkeye116477** [comment]
Chyba raczej zrezygnował, bo parę miesięcy temu usunął z readme => https://github.com/MajkiIT/polish-ads-filter/commit/843268e2e98bc050ee6d688a6cf9ccaa58dc04ff. Na <https://majkiit.github.io/polish-ads-filter/> już też nie powinno być, zamiast tego jest link do Patrionite przy nazwie listy.
