### ISSUE TITLE
android.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#22341]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [X] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://android.com.pl/moto/696789-test-kia-ev9-recenzja-opinia/
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Comodo Dragon Version 117.0.5938.150 (64-bitowa)

### Bloker (Blocker)

uBlock Origin 1.56.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

![and](https://github.com/MajkiIT/polish-ads-filter/assets/23176832/7c4db37c-ae04-4647-83d6-95325eda9ba4)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
A z IDCaC?

**Comment by blocker999** [comment]
TAK

**Comment by krystian3w** [comment]
To zostaje go włączyć, lista RODO-Ciasteczkowa raczej nie powinna naprawiać anty-adblocka opartego o IDCaC (coś co powinno ogarnąć konsorcjum Gen Digital Inc. jak nie planują przełączyć listy i dodatku w tryb offline).
