### ISSUE TITLE
pless.pl

### ISSUE THREAD

**Issue by jellizaveta** [MajkiIT/polish-ads-filter#22347]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://www.pless.pl/wiadomosci/82498-10-edycja-wiosny-z-fryderykiem-w-pszczynie-poznajcie-program-pszczyna
```

### System operacyjny (Operating system)

Android

### Przeglądarka internetowa (Web browser)

Chrome

### Bloker (Blocker)

AdGuard

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 

### Inne rozszerzenia (Other extensions)

-

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

<details>
  <summary>Screenshot 1 </summary>

  ![Screenshot 1](https://cdn.adguard.info/sitereports/78802s0u7csgogoogk0os4wg8ocog4kacpf4ui7wo8.png?nc=1)
</details>
<details>
  <summary>Screenshot 2 </summary>

  ![Screenshot 1](https://cdn.adguard.info/sitereports/qwshhid0g9w4cgwwks4wwwcoowk0sgghebtx08es4g.png?nc=1)
</details>
The comments section is blocked by a rule:
`pless.pl##.blok-artykul > .wrapper-row:nth-of-type(1)`

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by blocker999** [comment]
to samo, na : 

https://www.bielsko.info/wiadomosci/38675-konfiskata-aut-pijanym-kierowcom-mozliwa-ale-nie-obligatoryjna-rzad-wycofuje-sie-ze-zmian-bielsko-biala

https://www.czecho.pl/wiadomosci/42998-konfiskata-aut-pijanym-kierowcom-mozliwa-ale-nie-obligatoryjna-rzad-wycofuje-sie-ze-zmian

**Comment by krystian3w** [comment]
To raczej filtr do kasacji lub przerobienia na proceduralny/CSS4.
