### ISSUE TITLE
eska.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#22340]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [X] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://www.eska.pl/nerdsfera/rise-of-the-ronin-ze-swoim-odpowiednikiem-na-pc-od-sony-firma-chce-zachecic-graczy-do-kupna-ps5-aa-1YUA-6yWq-st7h.html
```

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Vivaldi 6.6.3271.45

### Bloker (Blocker)

uBlock Origin 1.56.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

![2024-03-08_182722](https://github.com/MajkiIT/polish-ads-filter/assets/19818572/a39f1a59-4364-4a09-92d2-bb4de0bd463c)

Nie wiem jak w przypadku reszty artykułów, ale tutaj jedynie jest filmik zupełnie niezwiązany z artykułem, więc może lepiej po prostu wyciąć to.

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Raz na sto chyba jest powiązany, więc to by się przydało dodać AI do uBo / list.

**Comment by krystian3w** [comment]
AdGuard niby naprawia to na bieżąco tak długo jak AdamWr/F4z nie zostanie przeniesiony na cały etat do twórcy skryptletów i jakiś ich śliników np. coreLib.
