### ISSUE TITLE
benchmark.pl

### ISSUE THREAD

**Issue by Szaquak** [MajkiIT/polish-ads-filter#22352]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
benchmark.pl###marketplaceProductBox
Wpis blokuje istotne elementy w artykułach typu TOP 10, dzie po prawej stronie są np cenówki, a czasem fotki pochodzące ze sklepu.
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Firefox 123.01

### Bloker (Blocker)

uBlock Origin 1.56.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by hawkeye116477** [comment]
Zabrakło przykładowego linku. 
https://www.benchmark.pl/testy_i_recenzje/telewizory-75-85-cali-top5-2024.html

Jednakże nie ta reguła jest problemem, a `benchmark.pl##.market`.

**Comment by krystian3w** [comment]
Zakładając, że WP już nie doda reklam z czytelnymi ID i klasami to można wywalić obie jako przestarzałe.

**Comment by hawkeye116477** [comment]
A to też jest ich? Rany, nie długo wykupią cały Internet :smiley: .
