### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by ozilwg** [MajkiIT/polish-ads-filter#22358]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://www.filmweb.pl/
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Opera GX

### Bloker (Blocker)

uBlock Origin 1.56.0

### Używane listy filtrów (Used filter lists)

uBlock filters
5/5
użytych 43 709 z 48 622

uBlock filters – Ads
użytych 33 415 z 37 407

uBlock filters – Badware risks
użytych 7219 z 7977

uBlock filters – Privacy
użytych 755 z 765

uBlock filters – Quick fixes
użytych 171 z 221

uBlock filters – Unbreak
użytych 2149 z 2252
Reklamy
3/3

AdGuard – Ads
użytych 77 459 z 79 903

AdGuard – Mobile Ads
użytych 8949 z 9143

EasyList
użytych 65 z 82 808
Prywatność
1/4

EasyPrivacy
użytych 50 126 z 50 395
Ochrona przed złośliwym oprogramowaniem, bezpieczeństwo
1/2

Online Malicious URL Blocklist
użytych 5030 z 7885
Wielofunkcyjne
1/2

Peter Lowe’s Ad and tracking server list
użytych 1143 z 3772

AdGuard – Social Media
użytych 21 451 z 22 669

EasyList – Social Widgets
użytych 14 570 z 15 782

uBlock filters – Annoyances
użytych 6678 z 6932
Regiony, języki
2/36

pl pl: Oficjalne Polskie Filtry
2/2
użytych 8925 z 10 000
Własne
22/23

💊 Dandelion Sprout's Anti-Malware List
użytych 90 301 z 91 558

pl  KAD - Przekręty
użytych 340 500 z 340 835

pl  Polski Antyirytujący Dodatek Specjalny
użytych 1041 z 1072

pl  Polskie Filtry Elementów Irytujących
użytych 23 095 z 23 676

pl  Polskie Filtry RODO-Ciasteczkowe
użytych 0 z 10 818

pl  Polskie Filtry Społecznościowe
użytych 14 678 z 15 053

AakList (Anti-Adblock Killer)
użytych 0 z 0

AdGuard Annoyances filter
użytych 77 126 z 77 323

AlleBlock
użytych 94 z 94

EasyList
użytych 82 768 z 82 785

EasyList Polish
użytych 3960 z 3961

Fuck Fuckadblock
użytych 0 z 0

https://github.com/jspenguin2017/uBlockProtector/raw/master/uBlockProtectorList.txt
użytych 2594 z 2625

https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
użytych 2501 z 2735

I don't care about cookies
użytych 24 057 z 25 840

Malicious URL Blocklist
użytych 155 490 z 155 490

NoCoin Filter List
użytych 664 z 672

Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for uBlock Origin
użytych 595 z 599

Online Malicious URL Blocklist
użytych 2624 z 2901

Polish Anti Adblock Filters - supplement for uBlock Origin
użytych 193 z 197

Polish Privacy Filters
użytych 139 z 145

Web Annoyances Ultralist
użytych 42 024 z 42 453

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Nie działa odtwarzanie zwiastunów, po wyłączeniu blokad na stronie odtwarzacz działa z masą reklam

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Sprawdź z wyłącznymi:

* Polish Privacy Filters

* Web Annoyances Ultralist

Pierwsza nie ma aktualizacji od wielu miesięcy a druga jest za duża jak na jednego chłopa i jego internetowego znajomego (obaj mało aktywni na GitHub w publicznych repozytoriach)

Potem bez:

* NoCoin Filter List

   Mogą blokować ważny plik niebędący koparką

* I don't care about cookies

  Polskie filtry RODO-ciasteczkowe migrujemy na EasyList Cookie z uBo Cookie Notices a IDCaC wymaga przebudowy przez nową korporację. 
  Jak nie odpowiada ci ELC to dla uBo jest z dużych list jeszcze AdGuard Cookie Notices ale nie ma planu użycia go jako bazy międzynarodowej lub innej listy jaką kojarzy @gomoku za aktualizowana do usuwania Cookies.

* 💊 Dandelion Sprout's Anti-Malware List

 Może być podobny w błędach jak lista do ubijania koparek (literówka lub zbyt globalny ban)

* `disconnect.me/simple_malvertising.txt`

 Lista może być zamrożona na stanie z 2016 (np. literówki)


Na końcu mogą być winne listy AdGuard Ads i Mobile Ads (metoda niekompatybilna z tą poleconą od uAssets)

**Comment by hawkeye116477** [comment]
Jeszcze uBlock Protector może odznaczyć, bo nie aktualizowany już parę lat.

**Comment by ozilwg** [comment]
@krystian3w zrobiłem tak jak napisałeś, wyłączyłem I don't care about cookies i dodałem EasyList Cookie, wyłączyłem też uBlock Protector tak jak pisał kolega niżej i dalej nie ładuje zwiastunów na filmweb.

Zrobiłem kopie zapasową ustawień ublock, mógłbyś zerknąć?
[ublock-kopia-zapasowa_2024-03-23_08.59.16.txt](https://github.com/MajkiIT/polish-ads-filter/files/14730737/ublock-kopia-zapasowa_2024-03-23_08.59.16.txt)

**Comment by krystian3w** [comment]
Taki mi leci na mojej konfiguracji jak odświeżę lub włączę go z "Seriale" (nie importowałem twojej kopii zapasowej): 

```adb
https://www.filmweb.pl/video/Zwiastun/Gra+o+tron+sezon+8+Zwiastun+nr+19+polski%2C-49393
```

Teoretycznie może trzeba dodać reload do uBo Cookie Notices:

```adb
filmweb.pl##+js(trusted-set-cookie, euconsent-v2, CPubvkAPubvkAAHABBENDMCgAAAAAAAAAB5YAAAAAAAA.YAAAAAAAAAAA, 1year)
```

czyli:

```adb
filmweb.pl#@#+js(trusted-set-cookie, euconsent-v2, CPubvkAPubvkAAHABBENDMCgAAAAAAAAAB5YAAAAAAAA.YAAAAAAAAAAA, 1year)

filmweb.pl##+js(trusted-set-cookie, euconsent-v2, CPubvkAPubvkAAHABBENDMCgAAAAAAAAAB5YAAAAAAAA.YAAAAAAAAAAA, 1year, , reload, 1)
```

**Comment by ozilwg** [comment]
Dodałem do 'moje filtry' `filmweb.pl#@#+js(trusted-set-cookie, euconsent-v2, CPubvkAPubvkAAHABBENDMCgAAAAAAAAAB5YAAAAAAAA.YAAAAAAAAAAA, 1year)
filmweb.pl##+js(trusted-set-cookie, euconsent-v2, CPubvkAPubvkAAHABBENDMCgAAAAAAAAAB5YAAAAAAAA.YAAAAAAAAAAA, 1year, , reload, 1)`
lecz dalej nie działa
![obraz_2024-03-25_094349246](https://github.com/MajkiIT/polish-ads-filter/assets/94186149/1b2c0c45-da49-4542-9a17-92bd804f3655)
Zaawansowane ustawienia mam zaznaczone ale nie wiem gdzie tam dodać 

> user-

**Comment by hawkeye116477** [comment]
> Zaawansowane ustawienia mam zaznaczone ale nie wiem gdzie tam dodać user-

<ttps://github.com/gorhill/uBlock/wiki/Advanced-settings#trustedlistprefixes>

**Comment by ozilwg** [comment]
Dobra już wiem i zmieniłem lecz nic się nie zmieniło i dalej na filmweb blokuje odtwarzacz

**Comment by krystian3w** [comment]
To jeszcze może być wina źle blokowanej "|"15 sekundowej" pełnoekranowej reklamy. "Nikt" nie umie w skryplety pod filmweb, więc zostało to ukryte CSS-em (kompatybilnie z ABP).

**Comment by ozilwg** [comment]
Na innych tematach z filmweb też nie zostało to rozwiązane bo sprawdzałem.
Dzięki za pomoc

**Comment by krystian3w** [comment]
Takie sprawdzenie staroci ma sens tylko gdy ktoś opisuje zacięty player.

**Comment by ozilwg** [comment]
Fakt ale nic innego nie znalazłem

**Comment by sixicr** [comment]
> krystian3w added a commit to krystian3w/polish-ads-filter that referenced this issue

Ale tam chyba nie ma żadnego patcha dla Filmwebu... 🙂

**Comment by krystian3w** [comment]
Misclick jak masz na myśli to: 

> ![Screenshot_20240524-091326](https://github.com/MajkiIT/polish-ads-filter/assets/35370833/be1f43c2-907b-4f43-a6b1-922cda24544d)

Możesz rozważyć tryb odwróconej białej listy i Filmweb oddać w ręce AdGuard MV2 (lub MV3 https://agrd.io/adguard_mv3, gdy przeglądarka za miesiąc wywali lub wyłączy ci AG MV2 pomimo polis przedłużających agonię o rok):




https://adguard.com/pl/adguard-browser-extension/

https://adguard.com/kb/adguard-browser-extension/features/filters/#allowlist

**Comment by sixicr** [comment]
No dobra, wystarczy wyłączyć:
AdGuard Annoyances filter
AdGuard – Cookie Notices

I działa! 🙂

**Comment by krystian3w** [comment]
Możesz spróbować włączyć resztę modłów na elementy irytujące AdGuard (przydatne do niepolskojęzynych irytacji w całym internecie):

* Filtr Popupów AdGuard
> Blokuje wszelkiego rodzaju wyskakujące okienka, które nie są niezbędne do działania witryn zgodnie z naszą Polityką filtrowania.

* Filtr Popupów AdGuard
> Blokuje wszelkiego rodzaju wyskakujące okienka, które nie są niezbędne do działania witryn zgodnie z naszą Polityką filtrowania.


* Filtr banerów aplikacji mobilnych AdGuard
> Blokuje irytujące banery promujące aplikacje mobilne stron internetowych.

* Filtr innych irytujących elementów AdGuard
> Blokuje irytujące elementy na stronach internetowych, które nie należą do popularnych kategorii irytacji. Już zawarte w filtrze AdGuard Annoyances.


* Filtr widżetów AdGuard
> Blokuje irytujące widżety innych firm: asystenci online, czaty na żywo itp. Już zawarte w filtrze AdGuard Annoyances.

**Comment by ozilwg** [comment]
> No dobra, wystarczy wyłączyć: AdGuard Annoyances filter AdGuard – Cookie Notices
> 
> I działa! 🙂

Masz racje, miałem tylko **AdGuard Annoyances filter** i po wyłączeniu działa

**Comment by krystian3w** [comment]
Jako że może robić ponad 20 tysięcy awarii to lepiej usunąć.

Chrome problem być może rozwiąże, że dodatek wyleci jak cała masa w formacie MV2 jak Avast/Norton się nie obudzi, że trzeba zrobić w ich przypadku prostą konwersję do MV3 (IDCaC nie ma potrzeby użycia limitu 1000 dynamicznych reguł (DNR)).
