### ISSUE TITLE
cdn.cookielaw.org

### ISSUE THREAD

**Issue by sefinek24** [MajkiIT/polish-ads-filter#22365]
### Opis sprawy (Case description)

Wydaje mi sie ze tej subdomeny nie powinno byc na liście, prawda?
https://blocklist.sefinek.net/generated/v1/0.0.0.0/other/polish-blocklists/MajkiIT/hostfile.fork.txt

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines)).

**Comment by xxcriticxx** [comment]
@hawkeye116477 / @krystian3w host file?

**Comment by hawkeye116477** [comment]
Tak, to sprawa nie do nas, tylko @MajkiIT.

**Comment by krystian3w** [comment]
Może jest tajny plan majkela o migracji listy Rodo-ciasteczkowej do pliku `adblock.txt`, ale wtedy ktoś musi przerobić skrypt do RTM by on edytował pliki adblock a stare wyróżnił z ostrzeżeniem, że lista jest złączona z plikiem do blokowania reklam.

**Comment by hawkeye116477** [comment]
Raczej nie ma żadnego planu. Majki do listy host od dawna różne rzeczy wrzuca, nie tylko same reklamy.

**Comment by sefinek24** [comment]
Tez bym to usunął, StevenBlack to naprawde dziwny gościu
=> https://github.com/StevenBlack/hosts/issues/2405 Tego nawet komentować nie będę, [@yoshim](https://github.com/StevenBlack/hosts/issues/2405#issuecomment-1684914733) dobrze to opisał
=> https://github.com/StevenBlack/hosts/issues/2505 Być może jest to tracker, ale za to blokowanie tego psuje pewną funkcjonalność Discorda; w tym kontekście weryfikacje kont poprzez email. Pulle list z yoyo i tak były wyłączone od 13 Maja, 2022, tragedai

**Comment by krystian3w** [comment]
Trzeba by zobaczyć blame linii, jak wkleja bot, to majkiit musi usunąć ze pliku pozagithubowego (lub jego prywatnego repo github).

**Comment by krystian3w** [comment]
Niby rozwala grupę TVN: #22463
