### ISSUE TITLE
audioteka.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#22366]
### Opis sprawy (Case description)

test link:
https://audioteka.com/pl/audiobook/dzika-karta

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines)).

**Comment by hawkeye116477** [comment]
To chyba obecnie da się załatwić jedynie w PCZ, no chyba, że pogadasz z gorhillem i on wykombinuje nowy scriptlet albo rozszerzy obecny, bo jest kilkanie, ale nie ma w oparciu o tekst lub XPath.

**Comment by gwarser** [comment]
Zgadza się. 

Zastanawiałem się, o co chodzi, bo u mnie nie ma żadnych ciastkowych dialogów — okazało się, że to dlatego, że blokuję globalnie `wp.pl$3p`.

Ten syntax z podwójnym `##+js(` to tak ma być?

**Comment by hawkeye116477** [comment]
> Ten syntax z podwójnym ##+js( to tak ma być?

Nie, najwyraźniej pośpieszyłem się przy kopiowaniu. Dzięki, poprawione.

**Comment by krystian3w** [comment]
Nie musi być klikanie, uAssets może dopisać to do filtrów `trusted-set-cookie` po udowodnieniu, że trzeba zaakceptować ciasteczka niezbędne by odmrozić resztę akcji na stronie (tj. że strona działa źle z ukrytym komunikatem, naprawionym przewijaniem i usuniętym rozmnażaniem elementów pod pop-upem).

Gorzej jak filtry działające dla `wp.pl,autokult.pl,fotoblogia.pl,gadzetomania.pl,polygamia.pl,dobreprogramy.pl` nie ruszą i muszą być oddzielone od siebie do czasu aż @gomoku z **JobcenterTycoon**.
