### ISSUE TITLE
studentnews.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2237]
Reklama Activejet po lewej i baner na górze...

**Comment by MajkiIT** [comment]
Może coś takiego?
www.studentnews.pl##a[href^="http://studentnews.pl/klik.php"]

**Comment by got3n** [comment]
Tutaj niestety chyba nic to nie da bo po kliknięciu na jakikolwiek link pojawia się znowu.

**Comment by xxcriticxx** [comment]
maybe cos takiego `||studentnews.pl/img/ban/b*.jpg` schowa ten banner na topie

**Comment by got3n** [comment]
@xxcriticxx teraz spoko, dzięki.

**Comment by MajkiIT** [comment]
@xxcriticxx dzięki
