### ISSUE TITLE
ublocked adserver

### ISSUE THREAD

**Issue by JobcenterTycoon** [MajkiIT/polish-ads-filter#22386]
### Opis sprawy (Case description)

Hello,

On `https://www.o2.pl/sport/pudzian-przylapal-pracownika-i-ty-dniowke-chcesz-7016178362985280a` i see 2 unblocked ad requests:

```
https://prd-prebid-bidder.adrino.io/bidder/bids/
https://lb3.adcontext.pl/
```

Please take a look.

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines)).

**Comment by krystian3w** [comment]
I doubt that MajkiIT included it in the quarterly schedule of tasks to be addressed, possibly with blocking filters.

The second name may seem like a bait (Can Run Ads == True family).
