### ISSUE TITLE
meczenazywo.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2240]
Betway na górze i w sumie tą trawę po bokach też bym wywalił, razi po oczach....

**Comment by MajkiIT** [comment]
@got3n Betway nie widzę 
a co do trawy to wrzuć sobie to.
||www.meczenazywo.pl/media/images/bg.jpg$image

**Comment by got3n** [comment]
@MajkiIT Ok, dzięki.
