### ISSUE TITLE
gamezilla.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2242]
reklama

`http://www.gamezilla.pl/newsy/2017/8/amd-oglasza-date-premiery-procesorow-amd-ryzen-7`

![capture](https://cloud.githubusercontent.com/assets/15007183/23383584/2aa2010a-fd15-11e6-9655-fe3cb303b230.PNG)

**Comment by MajkiIT** [comment]
`gamezilla.pl##DIV[style="width: 600px; height: 400px; margin: 20px auto;"]`
