### ISSUE TITLE
Brak zdjęć na domenach Polska Presse przez blokadę d-pa.ppstatic.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#22429]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://gloswielkopolski.pl/pierwszy-taki-sprzet-na-swiecie-trafil-do-szpitala-w-poznaniu-pozwala-przygotowac-mlodych-lekarzy-do-badania-wczesniakow/ar/c14p2-26318023
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Chrome 124.0.6367.156

### Bloker (Blocker)

Adguard Extension stable

### Używane listy filtrów (Used filter lists)

![20240510-1715364939](https://github.com/MajkiIT/polish-ads-filter/assets/9846948/cf66c0f7-fd30-4acc-90c8-03293aa5016b)

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Reguła
```
||d-pa.ppstatic.pl/frames/$image
```
z listy Oficjalne polskie filtry dla AdBlock, uBlock Origin i AdGuard

blokuje wszystkie zdjęcia na serwisach Polska Presse. 
Domeny:
```
e-ogrodek.pl,gra.pl,stronakuchni.pl,stronapodrozy.pl,strefaedukacji.pl,i.pl,stronazdrowia.pl,naszahistoria.pl,regiodom.pl,dziennikbaltycki.pl,dzienniklodzki.pl,dziennikpolski24.pl,dziennikzachodni.pl,echodnia.eu,expressbydgoski.pl,expressilustrowany.pl,gazetakrakowska.pl,gazetalubuska.pl,gazetawroclawska.pl,gk24.pl,gloswielkopolski.pl,gol24.pl,gp24.pl,gs24.pl,katowice.naszemiasto.pl,kurierlubelski.pl,motofakty.pl,naszemiasto.pl,nowiny24.pl,nowosci.com.pl,nto.pl,polskatimes.pl,pomorska.pl,poranny.pl,sportowy24.pl,strefaagro.pl,strefabiznesu.pl,stronakobiet.pl,telemagazyn.pl,to.com.pl,wspolczesna.pl
```
za `https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/Other/sections/annoyances.txt#L574`

![20240510-1715364755](https://github.com/MajkiIT/polish-ads-filter/assets/9846948/e4009442-d8fe-47d6-a3d5-0f9b6732b5d3)
![20240510-1715364750](https://github.com/MajkiIT/polish-ads-filter/assets/9846948/1eef718b-74fd-493f-bc1d-fb2e738e9d91)
![20240510-1715364746](https://github.com/MajkiIT/polish-ads-filter/assets/9846948/7f37ad3b-a187-44d1-9b23-fd770583a930)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by FadeMind** [comment]
Strona po odblokowaniu przez
```
@@||d-pa.ppstatic.pl/frames/$important,third-party
```
![20240510-1715365263](https://github.com/MajkiIT/polish-ads-filter/assets/9846948/2bcc5b41-7ff6-4892-b523-1d352d59f0a7)

**Comment by krystian3w** [comment]
Wygląda na błąd webmastera - nieświadomy że istnieją blokery treści.

**Comment by FadeMind** [comment]
@krystian3w usuniesz regułę psującą stronę?  :>

**Comment by krystian3w** [comment]
Bezpośrednio nie - trzeba by zrobić PR, jaki scali ostatecznie Majki lub xxcriticxx (AdamWr raczej nie zaloguje się na F4z jak nie stracił uprawnień).
