### ISSUE TITLE
Filmy w Player.pl nie odtwarzają się [Polish Pi-hole Filters]

### ISSUE THREAD

**Issue by dotvhs** [MajkiIT/polish-ads-filter#22463]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [X] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://player.pl/seriale-online/the-killing-odcinki,44453
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Firefox 128

### Bloker (Blocker)

AdGuard Home v0.107.52

### Używane listy filtrów (Used filter lists)

POL: Polish filters for Pi-hole

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Player.pl nie odtwarza filmów mając zasubkrybowane POL: `Polish filters for Pi-hole`, według logów w AdGuard Home, filtr który powoduje blokadę to `cdn.cookielaw.org`, odblokowanie tego pojedynczego filtru pozwala poprawnie odtwarzać filmy.

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by garry-ut99** [comment]
> AdGuard Home v0.107.52

Tu też ktoś coś zgłaszał (i miał powłączane Polskie listy oraz listy AdGuard):
- https://github.com/uBlockOrigin/uAssets/issues/24437

Nie zagłębiałem się w temat, czy to wina polskich filtrów, czy coś od AdGuarda, lub jeszcze jakaś inna przyczyna, jedynie dzielę się informacją, w razie gdyby okazało się, że jest jakieś powiązanie, i po prostu doklejam podobne zgłoszenie dotyczące `player.pl`.

**Comment by krystian3w** [comment]
#22365

**Comment by sefinek24** [comment]
Spośród 100 list które mam u siebie wrzuconych, `polish-blocklists/MajkiIT/hostfile.fork.txt` jest jedyną listą która blokuje `cdn.cookielaw.org`. Nadal potrzymuje swoje poprzednie stanowisko https://github.com/MajkiIT/polish-ads-filter/issues/22365#issuecomment-2028039691

https://blocklist.sefinek.net/generated/v1/0.0.0.0/other/polish-blocklists/MajkiIT/hostfile.fork.txt

Czas chyba dodać ją do whitelisty :D

![image](https://github.com/user-attachments/assets/49d40103-e457-483f-96ba-18142f6b8233)

**Comment by dotvhs** [comment]
Czy potrzeba przeprowadzić jakiś test by udowodnić, że to ten host powoduje nieodtwarzanie się filmów na Player? Jeśli tak, to mogę go wykonać. Oczywiście ja sprawdziłem u siebie, że odblokowanie tego jednego filtru naprawia problem, ale rozumiem, że jakiś proces weryfikacji może być wymagany tutaj.

**Comment by sefinek24** [comment]
@dotvhs szczerze to nie wydaje mi się żeby zostało to usunięte, ale miejmy jednak dobrą nadzieje

**Comment by dotvhs** [comment]
> @dotvhs szczerze to nie wydaje mi się żeby zostało to usunięte, ale miejmy jednak dobre nadzieje

To repo zdaje się być bardzo aktywne, więc jestem dobrej nadziei, ale rozumiem też, że z uwagi na popularność, oficjalny status, jak i profesjonalne podejście osób zarządzających tym repozytorium jakiś proces weryfikacji zgłoszeń jest potrzebny, więc stąd moje pytanie czy mogę to jakoś ułatwić :) Z mojej perspektywy to bez znaczenia, bo i tak dodałem tę jedną linię do wykluczeń a zgłosiłem by "uratować" od problemu innych, którzy mogli by się na to natknąć.

Może screen recording by pomógł, czy coś? Oczywiście mi się nie pali to zupełnie, bo problem rozwiązałem dla siebie, ale nie chcę przerzucać roboty weryfikacyjnej na osoby trzecie jeśli jest opcja ułatwienia tego z mojej strony.

**Comment by sefinek24** [comment]
@dotvhs, powiem Ci tak. Kiedyś mi też ten zablokowany host `cdn.cookielaw.org` popsuł jakąś stronę, ale nie pamiętam już niestety jaką. Też to zgłaszałem w #22365 i nadal nie zostało to usunięte.

Ostatecznie właśnie przed chwilą dodałem to do swojej whitelisty https://github.com/sefinek24/Sefinek-Blocklist-Collection/commit/aa0d35bc311c68a764c70842d20b871c42620270. Za kilka godzin `cdn.cookielaw.org` zniknie automatycznie [na produkcji](https://blocklist.sefinek.net/generated/v1/0.0.0.0/other/polish-blocklists/MajkiIT/hostfile.fork.txt).

Miałem już to generalnie wcześniej zrobić, ale zrobiłem dopiero teraz, bo urzekły mnie twoje zdania, z którymi się zgadzam 🥀

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/22463#issuecomment-2241730962 - raczej lata świetności ma za sobą:

https://github.com/MajkiIT/polish-ads-filter/issues?q=label%3Aodrzucone+label%3Areklama - bot zamka i kij wie czy Majkel w 90 dni zdążył wyciąć reklamy (https://github.com/MajkiIT/polish-ads-filter/pull/21992).

W historii przydałby się parametr do odrzucenia wkładu bota dla hosts/Pi-Hole/Mikrotik.

**Comment by sefinek24** [comment]
@krystian3w naprawde szkoda ze nikt nie zarządza tym repo już

**Comment by dotvhs** [comment]
> raczej lata świetności ma za sobą

Rozumiem, dzięki za informację. W takim razie przynajmniej jest to problem dość niszowej listy hostsów, każdy kto ma Pi-hole lub Adguard Home będzie raczej potrafił rozwiązać to po swojej stronie.

**Comment by krystian3w** [comment]
Plik wydaje się być poza kontrolą automatyzacji/mirroru botem:

> ![obraz](https://github.com/user-attachments/assets/1264c0a2-ad21-4f58-81d5-41482a64a159) |
> --- |
