### ISSUE TITLE
Filmy na serwisie Player nie odtwarzają się [Polish Pi-hole Filters]

### ISSUE THREAD

**Issue by dotvhs** [MajkiIT/polish-ads-filter#22462]
### Opis sprawy (Case description)

Polish Pi-hole Filters zawiera ten filtr: `cdn.cookielaw.org` który blokuje odtwarzanie filmów w serwisie Player. Wyłączenie tego jednego filtru powoduje, że filmy odtwarzają się poprawnie.

Przepraszam z góry, jeśli kategoria Issue na githubie nie jest właściwa, nie za bardzo widziałem bardziej pasującej.

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines)).

**Comment by dotvhs** [comment]
Źle zaraportowałem, przepraszam, zgłoszę w osobnym issue poprawnie.

**Comment by krystian3w** [comment]
Mamy już raport z prośbą o usunięcie #22365
