### ISSUE TITLE
www.msn.com/pl-pl/pogoda/mapy-pogody/severeweather/

### ISSUE THREAD

**Issue by DarekWa** [MajkiIT/polish-ads-filter#22460]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://www.msn.com/pl-pl/pogoda/mapy-pogody/severeweather/
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

MS Edge 126.0.2592.87

### Bloker (Blocker)

uBlock Origin 1.57.2

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Zrzut https://imgur.com/a/hotjNPs

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Strona raczej międzynarodowa, jak EL nie zaadresuje do grudnia to można przemyśleć.

**Comment by krystian3w** [comment]
Powoli można myśleć o regionalnej poprawce.
