### ISSUE TITLE
bezuzyteczna.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2247]
biala box na topie i na dole po reklamach

**Comment by MajkiIT** [comment]
Górne mozna tak
bezuzyteczna.pl##[style="width:700px;height:200px;"]

na dolne pole nie mam pomysłu.
@F4z zerkniesz?

**Comment by F4z** [comment]
A tak?
`bezuzyteczna.pl##section > script + div[id^="crt"][style]`
Wtedy na dole zostanie mały biały pasek, żeby go ukryć można użyć na przykład takiej reguły:
`bezuzyteczna.pl##section:has(script + div[id^="crt"][style])`
ale to nie będzie działało w Adblocku.

**Comment by MajkiIT** [comment]
@F4z dziękuję. Będzie ok.
