### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2248]
Pozostałość po reklamie na górze strony - `http://www.filmweb.pl/film/Scooby-Doo+Na+Dzikim+Zachodzie-2017-779044`

![fw](https://cloud.githubusercontent.com/assets/11742596/23437393/4554bf20-fe0e-11e6-9254-356995afb1b6.JPG)

Na przykład:
`filmweb.pl###skyBanner`

**Comment by MajkiIT** [comment]
@F4z Dzięki
