### ISSUE TITLE
radio.bialystok.pl is broken

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#22506]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [X] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://www.radio.bialystok.pl/wiadomosci
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Chrome 127.0.6533.120 

### Bloker (Blocker)

AdGuard 4.4.18

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Polskie Filtry Społecznościowe

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Page content is hidden. Breakage caused by 
`radio.bialystok.pl#?#.row > .columns .columns, .text-center .text-center > .columns:-abp-has(> h3:-abp-contains(ZNAJDŹ NAS))`

<details>
<summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/30fa7f4c-7527-4e0b-925f-7a327b54cfd7)

</details>

Related issue: https://github.com/AdguardTeam/AdguardFilters/issues/186796

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Often broken by glitch in ExtCSS: https://github.com/AdguardTeam/AdguardFilters/issues/78819
https://github.com/AdguardTeam/ExtendedCss/issues/122
