### ISSUE TITLE
Bug: aliexpress.com nieużywalne

### ISSUE THREAD

**Issue by C10udburst** [MajkiIT/polish-ads-filter#22504]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [X] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
e11956.x.akamaiedge.net
```

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

N/A

### Bloker (Blocker)

Pi-hole 5.18.2

### Używane listy filtrów (Used filter lists)

- https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
- https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
- https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
- https://adaway.org/hosts.txt
- https://someonewhocares.org/hosts/hosts
- https://v.firebog.net/hosts/Easylist.txt
- https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&amp;showintro=1&amp;mimetype=plaintext
- https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt
- https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/Ad_filter_list_by_Disconnect.txt
- https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/kad_host.txt
- https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt
- https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/easylist_host.txt
- https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/KADhosts.txt
- https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
- https://raw.githubusercontent.com/TheBlockList/Blocklist/master/huawei
- https://raw.githubusercontent.com/x0uid/SpotifyAdBlock/master/SpotifyBlocklist.txt
- https://raw.githubusercontent.com/TheBlockList/Blocklist/master/microsoft
- https://raw.githubusercontent.com/TheBlockList/Blocklist/master/google
- https://raw.githubusercontent.com/TheBlockList/Blocklist/master/twitch
- https://raw.githubusercontent.com/TheBlockList/Blocklist/master/gaming
- https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/adguard_mobile_host.txt
- https://github.com/vincentkenny01/spotblock/raw/master/spotify
- https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
- https://v.firebog.net/hosts/AdguardDNS.txt
- https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
- https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
- https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
- https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/windows
- https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/samsung
- https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/huawei
- https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
- https://gist.githubusercontent.com/C10udburst/fd52d5824cc79427184568b0c01aab95/raw/hosts.txt
- https://gist.githubusercontent.com/sgeto/36bd4b93fc23db9936be06fa8c6a5dc3/raw/lphosts
- https://gist.githubusercontent.com/quells/2f5fdb0669f87104ef80d408c761f77a/raw/boox-dns-blacklist

### Inne rozszerzenia (Other extensions)

N/A

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Ponieważ blokowana jest domena `e11956.x.akamaiedge.net`, komenda `dig aliexpress.com` zwraca `0.0.0.0`. Dodanie jej do whitelisty naprawia problem.

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
Ale na której liście to masz i  w przypadku tych to lepiej iść w plik źródłowy: https://github.com/MajkiIT/polish-ads-filter/tree/master/polish-pihole-filters

Dodatkowo to repozytorium to nie darmowa Matka Teresa co zgłosi błąd w innym repo.
