### ISSUE TITLE
antyweb.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2250]
Obrazki z HORIZON

**Comment by F4z** [comment]
Tak będzie ok?
`||antyweb.pl/wp-content/themes/antyweb.autentika/horizon/`
`||antyweb.pl/wp-content/uploads/2017/03/horizon-cover.jpg$image`
`||antyweb.pl/wp-content/themes/antyweb.autentika/aadv/js/aadv.js`
`antyweb.pl##.visible.grid-box-big > .group.grid > .customScroller > .cs-wrapper.group > .grid-item.width-4.height-2.transparent`

Jak kliknie się obok tych dwóch artykułów na górze strony, które dotyczą "Horizon: Zero Dawn" to przekierowuje do strony tej gry, więc ewentualnie można jeszcze to dodać:
`antyweb.pl##[data-url^="https://www.playstation.com/pl-pl/games/horizon-zero-dawn"][data-url*="&utm_medium=Display&utm_campaign=Horizon_Zero_Dawn&utm_source=AntyWeb_Welcome_Screen"]`
Tylko, że wtedy też zostaną ukryte te dwa artykuły.

**Comment by MajkiIT** [comment]
@F4z Dzięki. Jutro przetestuje.
