### ISSUE TITLE
[NSFW] 4chan.org/adv/

### ISSUE THREAD

**Issue by Vanishing-Point** [MajkiIT/polish-ads-filter#22515]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [X] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://boards.4chan.org/adv/catalog
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Firefox 130.0.1

### Bloker (Blocker)

uBlock Origin 1.59.0

### Używane listy filtrów (Used filter lists)

1. pl: Oficjalne Polskie Filtry do uBlocka Origin

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

Filtr `/adv/*$image,from=~arriva.pl|~budus.pl|~filmweb.pl` blokuje obrazki na 4chanie, na forum /adv/.
![obraz](https://github.com/user-attachments/assets/892d1a54-ccf3-4e3f-a4e0-ada51b97d1ff)
![obraz](https://github.com/user-attachments/assets/b8da5318-5d03-4ade-aad3-b64621e63a4b)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
A "karczan" ma podobny problem?

Jedynie lipa, że w są 3 PR od tygodnia i nikt nie scalił.
