### ISSUE TITLE
komorkomania.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2252]
Puste pole po reklamie na górze i poniżej jeszcze jedno...
![jkl](https://cloud.githubusercontent.com/assets/26026382/23504048/3e836102-ff3e-11e6-9e8e-601e86f0911e.png)

**Comment by MajkiIT** [comment]
U mnie jest ok.

**Comment by xxcriticxx** [comment]
u mnie tez ok na fox i na chromie

**Comment by got3n** [comment]
No nic pewnie tylko na uBlock'u działa.

**Comment by MajkiIT** [comment]
@got3n masz włączone filtry AAK by Reek??

**Comment by got3n** [comment]
@MajkiIT Tak. 
To jest mój CONFIG:
![ad](https://cloud.githubusercontent.com/assets/26026382/23510619/99c17b82-ff5a-11e6-8265-fa5b8bfd59df.png)

**Comment by MajkiIT** [comment]
@got3n AAK wywal i zastąp je tym https://x01x012013.github.io/AdBlockProtector/

**Comment by MajkiIT** [comment]
@got3n działa?

**Comment by got3n** [comment]
@MajkiIT Dzięki, działa.
