### ISSUE TITLE
eska.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2253]
Reklama na górze...
![34](https://cloud.githubusercontent.com/assets/26026382/23504224/e03633da-ff3e-11e6-8a02-4c19de31e527.png)

**Comment by MajkiIT** [comment]
@got3n masz włączony Easylist?

**Comment by MajkiIT** [comment]
||www.eska.pl/html/v4/js/_is_user_using_adb.js$script,domain=www.eska.pl
www.eska.pl##.zpr_top_1

**Comment by xxcriticxx** [comment]
@got3n wyloncz acceptable ads in Adblock Plus

**Comment by got3n** [comment]
@MajkiIT Tak mam EasyList
@xxcriticxx wyłączyłem na chwilę i faktycznie reklama znikła ale zostało puste białe pole...

**Comment by MajkiIT** [comment]
@got3n puste pole ogarniemy.
