### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#2254]
"Adblock polskie reguly social" filtr `/yt` rozwala mi fejsbuka! Strona logowania jest nieczytelna a po zalogowaniu nie działa messenger.
Znajduje ten ciąg w linku do jednego stylu i jednego skryptu.
`...Ua4/yT/l/pl_PL/om...KiU.js`
`.../v3/yt/r/3-0oh...mY.css`

**Comment by MajkiIT** [comment]
Ok zaraz go usunę. Dzięki

**Comment by blocker999** [comment]
@gwarser 

Może zamiast usuwać, lepiej zamienić na `yt.`

co otym sądzisz?

**Comment by gwarser** [comment]
Co to `yt/` ma blokować? Teraz sprawdziłem i na fb znajduje po dwa skrypty, style i obrazki z tym.

**Comment by blocker999** [comment]
Antyweb.pl miał no ale widze że już jest niepotrzebny.
