### ISSUE TITLE
grajteraz.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2255]
`http://www.grajteraz.pl/dla-dziewczyn/love-test`

![capture](https://cloud.githubusercontent.com/assets/15007183/23529692/89e0b59a-ff6c-11e6-816f-04935a4574c3.PNG)

**Comment by F4z** [comment]
Powinno wystarczyć:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=games.cdn.famobi.com`
