### ISSUE TITLE
chocianow.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2256]
`http://www.chocianow.com.pl/mapa_chocianowa/`

![capture](https://cloud.githubusercontent.com/assets/15007183/23530286/10a464c6-ff6f-11e6-97cb-aeb22a5a137f.PNG)

**Comment by MajkiIT** [comment]
Ja tego nie widzę.

**Comment by xxcriticxx** [comment]
jest gut script mialem wylonczony
