### ISSUE TITLE
telefirma.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2257]
cookie fix strona cala biala

**Comment by MajkiIT** [comment]
U mnie jest ok.

**Comment by xxcriticxx** [comment]
main page dziala otwieram nowa strone z artykulem co chce przeczytac i mam pusta biala strone

![capture](https://cloud.githubusercontent.com/assets/15007183/23553934/e7c81b10-fff0-11e6-88cb-f2059e6448d5.PNG)
