### ISSUE TITLE
telepolis.pl

### ISSUE THREAD

**Issue by Mitarr** [MajkiIT/polish-ads-filter#22607]
### Typ elementu lub problemu (The type of item or problem)

- [X] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://www.telepolis.pl/wiadomosci/prawo-finanse-statystyki/speedtest-global-index-pazdziernik-2024-szybkosc-internetu-polska-a-reszta-swiata
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Chrome / Firefox

### Bloker (Blocker)

uBlock Origin

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

video pod tytułem artykułu 
poniższe reguły to naprawiają :  
telepolis.pl##.embed-responsive
telepolis.pl##.lead + [class^="text-"]
telepolis.pl##.lead + [class^="text-"] + [class^="text-"]

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by MajkiIT** [comment]
@Mitarr dziękuję
