### ISSUE TITLE
bing.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#22602]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [X] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [ ] Pytanie (Question)

### Link bezpośredni (Specific link)

```markdown
https://www.bing.com/search?q=Popularne%20teraz%20w%20us%C5%82udze%20Bing&form=hpmscl


https://www.bing.com/search?q=adblock&PC=U316&FORM=CHROMN
```

### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Comodo Dragon Version 129.0.6668.90 (32-bitowa)

### Bloker (Blocker)

uBlock Origin 1.61.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. 
4. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

https://www.bing.com/search?q=Popularne%20teraz%20w%20us%C5%82udze%20Bing&form=hpmscl
![bing - cook](https://github.com/user-attachments/assets/e4350bb7-f948-489c-bff3-2b4cbf99545c)

https://www.bing.com/search?q=adblock&PC=U316&FORM=CHROMN
![bing](https://github.com/user-attachments/assets/856b3d95-68dd-43ef-80ec-8eb34d7c4f6e)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by krystian3w** [comment]
uAssets w uBo Annoyances/uBo Cookie Notices zamyka np. tym:

```adb
bing.com##+js(trusted-set-cookie, BCP, AD=0&AL=0&SM=0)
```


teoretycznie można skopiować do PZC ale kto będzie nadążał nad aktualizacją?
