### ISSUE TITLE
Co się dzieje ostatnio z polskimi filtrami w UBO na przeglądarkach?

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#22649]
### Typ elementu lub problemu (The type of item or problem)

- [ ] Reklama (Advert)
- [ ] Wydobywanie kryptowalut (Cryptocurrency mining)
- [ ] Anty-adblock (Anti-adblock wall)
- [ ] Komunikat dot. ciasteczek i polityki prywatności/RODO (Message about cookies and GDPR/privacy policy)
- [ ] Element społecznościowy (Social network element)
- [ ] Pi-hole, hosts i spółka (Pi-hole, hosts & co)
- [ ] Błąd (Bug, mistake, no-no)
- [X] Pytanie (Question)

### System operacyjny (Operating system)

Linux/Unix

### Przeglądarka internetowa (Web browser)

Firefox 

### Bloker (Blocker)

Ublock origin 

### Używane listy filtrów (Used filter lists)

Nie dotyczy 
![Screenshot_20241216-215620](https://github.com/user-attachments/assets/9190c251-0b15-4cbc-a956-d6ed0a1fb3df)

### Zasady pisania (Writing rules)

- [X] Zapoznałem się z [przewodnikiem dot. składania raportów](https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md) i [netykietą](https://pl.wikipedia.org/wiki/Netykieta) (I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines))

**Comment by hawkeye116477** [comment]
To się dzieję, że Majki raz wpisał nie istniejącą datę (31 November) i dlatego nie chce się aktualizować, ale wystarczy odznaczyć i zaznaczyć ponownie i zadziała.

**Comment by xxcriticxx** [comment]
32 października🤣

**Comment by seba2282** [comment]
🤣

**Comment by hawkeye116477** [comment]
> Nawiasem mówiąc, lista nie była aktualizowana od prawie miesiąca:

Nawet jak była aktualizowana, to i tak ostatnio pobieżnie. Zapewne nie ma czasu albo już mu się nie chce i przechodzi na "emeryturę".
