### ISSUE TITLE
poczta onet

### ISSUE THREAD

**Issue by mateusz1807** [MajkiIT/polish-ads-filter#2272]
![poczta onet](https://cloud.githubusercontent.com/assets/26255951/23667453/2fa3dbc0-035e-11e7-8fed-28f683d5c94e.JPG)

**Comment by xxcriticxx** [comment]
@mateusz1807 masz dwa blokery zamontowane najlepjej jest z jedym 

@MajkiIT @F4z ma ktos konto do testow? @mateusz1807 zalozysz konto do testow?

**Comment by mateusz1807** [comment]
Korzystam z dwóch bo się dobrze uzupełniają. W tym przypadku nie mogę dodać ręcznie. Czy to uBlock u AdBlock to po dodaniu tylko znika krzyżyk do zamknięcia a puste pole nadal zostaje.
Jak nikt nie ma konta na onecie to mogę założyć

**Comment by MajkiIT** [comment]
@mateusz1807 zaktualizuj filtry.
Co do 2 blockerów to wydaje mi się to przesadzone, bo jak mówi @xxcriticxx powodować będzie to tylko problemy.

**Comment by mateusz1807** [comment]
Nie pomogło. Nadal jest puste pole i teraz nie można tego zamknąć. Sprawdziłem bez uBlocka

**Comment by xxcriticxx** [comment]
@mateusz1807 wyczysc historie przegladania i cookies

**Comment by mateusz1807** [comment]
To samo
![onet](https://cloud.githubusercontent.com/assets/26255951/23674437/3a487dde-0376-11e7-8a7e-d0775a8faf44.JPG)

**Comment by xxcriticxx** [comment]
@MajkiIT zerkniesz?

**Comment by MajkiIT** [comment]
Spróbuj jeszcze raz zaktualizować filtry.

**Comment by mateusz1807** [comment]
Bez zmian

**Comment by xxcriticxx** [comment]
@mateusz1807 jaka ver fitrow masz?

v.2017030704 aktualizacja: wt, 7 marca 2017, 20:30:00

**Comment by mateusz1807** [comment]
Nie widzę takich informacji
![adblock](https://cloud.githubusercontent.com/assets/26255951/23674789/65e5a8d0-0377-11e7-88b2-8ec1fd6d8038.JPG)

**Comment by xxcriticxx** [comment]
mozesz dodac jaka ver masz?

**Comment by mateusz1807** [comment]
3.8.8

**Comment by xxcriticxx** [comment]
tak to wyglonda w ublock o v.2017030704 aktualizacja: wt, 7 marca 2017, 20:30:00

**Comment by F4z** [comment]
W przypadku uBlocka można spróbować z taką regułą:
`poczta.onet.pl##.side-box-right-300 > .wrapper > .frameWrapper > .frameContent:style(padding-right: 0px !important;)`

**Comment by mateusz1807** [comment]
Ok, sprawdzę jak wrócę do domu

**Comment by mateusz1807** [comment]
Nadal białe puste pole. Obecnie nie mam już nawet x żeby ręcznie zamknąć

**Comment by xxcriticxx** [comment]
@mateusz1807 a co natym polu bys chcial zobaczyc? mozliwe ze nic wiecej sie nieda stym zrobic

**Comment by mateusz1807** [comment]
Nic nie chce tam widzieć. Chce to po prostu zamknąć tak żeby lista wiadomości się rozszerzyła.

**Comment by MajkiIT** [comment]
@mateusz1807 tam nie ma już nic, ale styl css ustawia pole wiadomości na konkretną wielkość

**Comment by F4z** [comment]
@mateusz1807 u mnie z regułą, którą podałem nie ma tego białego pustego miejsca.

![onet](https://cloud.githubusercontent.com/assets/11742596/23719329/3d09e2ea-043b-11e7-9195-a152ee51c9ce.JPG)

Ale skoro u Ciebie nadal jest, to czy mógłbyś kliknąć prawym przyciskiem myszy w to puste miejsce, a potem z tego menu wybrać opcję "Zbadaj". Następnie zrobić screenshota tego co się pokaże.
Tak żeby było jak na tym obrazku.

![onet1](https://cloud.githubusercontent.com/assets/11742596/23719445/bca5575a-043b-11e7-9fe7-e4cd0f2367e8.JPG)

Ewentualnie jeszcze możesz w uBlocku sprawdzić tę regułę:
`poczta.onet.pl###mainContent:style(padding-right: 0px !important;)`

**Comment by mateusz1807** [comment]
A gdzie dodawałeś regułę do ublocka? Zakładka Moje reguły i tymczasowe reguły? Bo nigdzie indziej nie widzę opcji dodania

**Comment by F4z** [comment]
W zakładce "Moje filtry".

**Comment by mateusz1807** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/26255951/23720352/c7aa8bb8-043e-11e7-9851-bee2052e3b5a.jpg)

**Comment by F4z** [comment]
To ta reguła powinna działać (ta pierwsza, którą podałem raczej też):
`poczta.onet.pl###mainContent:style(padding-right: 0px !important;)`
Dodawałeś tę regułę w uBlocku w zakładce "Moje filtry"?

**Comment by mateusz1807** [comment]
Tak
![bez tytulu](https://cloud.githubusercontent.com/assets/26255951/23720735/cee21c42-043f-11e7-8ee2-173fb55a6584.jpg)

**Comment by mateusz1807** [comment]
O dobra już mam. Opcja "kosmetyczne filtrowanie na tej stronie" naprawiła problem
👍

**Comment by F4z** [comment]
No to dobrze :)
