### ISSUE TITLE
ojniet.pl to komputerswiat.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2280]
przejscie z onetu na komputerswiat powoduje ad block 

juz to kiedys przerabialismy

`http://www.komputerswiat.pl/poradniki/internet/anonimowosc/2017/03/jak-calkowicie-zniknac-z-sieci-infografika.aspx`

![capture](https://cloud.githubusercontent.com/assets/15007183/23728174/79abfd6c-0429-11e7-9fd8-db9b2246dd18.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx zaktualizuj proszę filtry i sprawdź proszę.
