### ISSUE TITLE
ojniet.pl to plejada.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2282]
ad block 

`http://plejada.pl/newsy/jennifer-lopez-pokazala-corke-mala-przypomina-mame/p2f0zz`

![capture](https://cloud.githubusercontent.com/assets/15007183/23774016/b7c4e368-04ef-11e7-9178-fddef38e3fdc.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx dzięki
