### ISSUE TITLE
www.auto-swiat.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2293]
Ciasteczka onet

**Comment by xxcriticxx** [comment]
@MajkiIT ja mam onet ad block 

![capture](https://cloud.githubusercontent.com/assets/15007183/23903588/659f0794-089b-11e7-9aa1-3cbc7c6a910f.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx zaktualizuj filtry. Już powinno być ok.
