### ISSUE TITLE
onet.pl - adblock detection

### ISSUE THREAD

**Issue by Alex-302** [MajkiIT/polish-ads-filter#2294]
Scroll down:

![image](https://cloud.githubusercontent.com/assets/15856304/23896985/2bf985be-08b4-11e7-8458-41201a170015.png)

On my side it is fixed by
```
@@||csr.onet.pl/*/csr.js*&callback=onetShowAsynchAds$domain=onet.pl
```
+ ad leftovers
```
onet.pl##.onetAdAuto
onet.pl###sponsDiv
```

**Comment by MajkiIT** [comment]
@Alex-302 Thanks, I will check it.

@F4z @xxcriticxx macie jakiś błąd odnośnie adblocka na stronie onetu?

**Comment by xxcriticxx** [comment]
ja niemam ad blocka

**Comment by MajkiIT** [comment]
@xxcriticxx dziękuję.

**Comment by xxcriticxx** [comment]
przetestujme chroma moment

**Comment by xxcriticxx** [comment]
nothing na chromie

**Comment by mathew85** [comment]
Ja ostatnio zauważyłem u siebie w pracy, że się pojawia. Tylko tam łączymy się przez zagraniczne proxy. Może to jest problemem, bo w domu u mnie jest OK.
Jutro jak nie zapomnę to też sprawdzę.

**Comment by MajkiIT** [comment]
@xxcriticxx jeszcze raz dzięki

@mathew85 dzięki, będę wdzięczny.

**Comment by Alex-302** [comment]
btw I am using Adguard. Checked with Polish and English filters.
It is strange, but I can't reproduce it now..

**Comment by MajkiIT** [comment]
@Alex-302 Maybe you update polish filters and few days ago I added exclude.

**Comment by Alex-302** [comment]
@MajkiIT no, that request is blocked, but detection is not triggered)

**Comment by xxcriticxx** [comment]
i checked with us ip both chrome and firefox i got nothing

**Comment by Alex-302** [comment]
ok then
