### ISSUE TITLE
212.180.250.94

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2298]
`http://212.180.250.94/telewizja/programy-polotv/kuchnia-polowa-69/vod/kuchnia-polowa-on---szczery-do-bolu-ona---czasem-rzuca-miesem-zobaczcie-zwiastun-najnowszego-odcinka-3425`

![capture](https://cloud.githubusercontent.com/assets/15007183/23923087/90a6205e-08db-11e7-8e1f-8d826aaab54c.PNG)

**Comment by MajkiIT** [comment]
@@|polotv.pl/assets/js/ads.js$script,domain=polotv.pl
@@||hit.gemius.pl/gplayer.js$script,domain=polotv.pl
