### ISSUE TITLE
filmaster.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2299]
Reklama na górze
![1](https://cloud.githubusercontent.com/assets/26026382/23946963/daf502fa-097c-11e7-8e6f-da5e5a4bcdee.png)

**Comment by xxcriticxx** [comment]
@got3n ja nic niemam mam tylko duza czarna dziure 

![capture](https://cloud.githubusercontent.com/assets/15007183/23950950/0de6561a-0963-11e7-8e5c-892bff0d4a6b.PNG)

**Comment by got3n** [comment]
Tak, teraz u mnie to samo reklama znikła ale dziura została do załatania.
