### ISSUE TITLE
www.pap.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#230]
trzeba cos poprawic vid niegra

http://www.pap.pl/aktualnosci/news,450034,kard-nycz-swieta-sa-okazja-do-pojednania---w-rodzinach-i-w-szerszych-kregach.html

http://www.pap.pl/aktualnosci/news,446998,nasz-kolega-dziennikarz-pap-pomagal-innym-dzis-sam-potrzebuje-pomocy.html

**Comment by MajkiIT** [comment]
co jest źle?

**Comment by xxcriticxx** [comment]
w video jest dzwienk niema obrazu 

zanim sie zacznie lecji reklama wten sam sposob odlicza timer 30 sec niema obrazu jest tylko dzwiek z reklamy

**Comment by MajkiIT** [comment]
Poprawiłem. Zaktualizuj filtry.
