### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by dthlfwp** [MajkiIT/polish-ads-filter#2302]
http://shinden.pl/external-video/3049-luckystar/view/29646
http://imgbox.com/sITC3Y76
Opera
Violentmonkey
uBlock
Anti-adblock-killer (List+Scipt) + Polish filters

Note: ABP icons shoud be buttons instead

Enabling Easylist OR Polish certificate.it list causes the problem

related anti-adblock-killer issue https://github.com/reek/anti-adblock-killer/issues/2955

**Comment by xxcriticxx** [comment]
@dthlfwp reek is outdated please use https://github.com/X01X012013/AdBlockProtector

@MajkiIT widze cookies na dole

**Comment by F4z** [comment]
Powinno wystarczyć:
`@@||reklama.shinden.eu/adpeeps.php$script,domain=shinden.pl`

Nie wiem, czy przez to nie będzie gdzieś reklam, ale teraz nie mam czasu się temu przyjrzeć.
Później postaram się dokładniej to sprawdzić.

**Comment by dthlfwp** [comment]
@xxcriticxx  zmieniłem na AdBlockProtector, bez różnicy w działaniu.
@F4z wydaje się być teraz OK, dzięki.

**Comment by xxcriticxx** [comment]
@dthlfwp dodales liste i script?

**Comment by MajkiIT** [comment]
@F4z Dzięki

**Comment by F4z** [comment]
@MajkiIT możesz dodać w ten sposób?
`@@||reklama.shinden.eu/adpeeps.php?*bzone=bloker$domain=shinden.pl`
Żeby też z Adguardem działało, ok?

**Comment by MajkiIT** [comment]
@F4z Ok już poprawiam,

**Comment by MajkiIT** [comment]
@F4z Zrobione i nie ma problemu

**Comment by halwiefal** [comment]
Niestety znowu zablokowali :(

**Comment by Twardykolo** [comment]
Zablokowane once again.

**Comment by krystian3w** [comment]
U mnie działa linki nie znikają, odtwarzacze raczej też.

**Comment by machond** [comment]
W dniu dzisiejszym ponownie zablokowane.

**Comment by krystian3w** [comment]
Najlepiej zrób nowe zgłoszenie, ja ostatnio czyściłem subskrypcje i może bez wołania po nicku nikt wątku nie śledzi.
