### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#2303]
Formatka logowania ukryta przez 'pl##.in' z listy social.

https://ssl.dobreprogramy.pl/Logowanie.html

**Comment by MajkiIT** [comment]
dzięki

**Comment by gwarser** [comment]
@MajkiIT co ten `.in` ma ukrywać? Znowu mam dwie strony z błędem.

https://swiatprzychodni.pl/osrodki/wojda-boguslaw-nzoz-poradnie-specjalistyczne-szczebrzeszyn/
http://placowki.mp.pl/unit/index.html?id=775516

**Comment by Isamaul** [comment]
`.in` usuwa bootstrapowe modale - więc w sumie dużo.

**Comment by blocker999** [comment]
chyba go całkiem usune, co?

**Comment by gwarser** [comment]
Ja już mam do niego wyjątek w moich filtrach bo mnie za bardzo wkurzał.

**Comment by blocker999** [comment]
Ok, to usune by innych też nie drażnił.
