### ISSUE TITLE
forum.dobreprogramy.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#2311]
![screenshot_20170316_165344](https://cloud.githubusercontent.com/assets/9846948/24005381/289a8f2e-0a69-11e7-9a5c-6c576f3de76c.png)

Reklama NC+ w tle

**Comment by F4z** [comment]
@FadeMind jak klikniesz w to co jest w tle, to przenosi Cię do tej reklamy?
Pytam, bo jedna z reguł z listy `polskie filtry do uBlocka uzupelnienie` powinna to blokować, ale mam wrażenie, że u Ciebie to nie działa.

Jeśli chodzi o samo tło, to ta reguła powinna je "ukryć":
`forum.dobreprogramy.pl##body[class]:style(background-image: none !important;)`

**Comment by FadeMind** [comment]
@F4z uzupełnienie do uBlocka mam włączone. Blokowanie przez hosty wyłączone. Reguła, którą podałeś ukrywa obraz tła i zostawia czarne tło. Dziękuję. Tło nie ma odnośnika (to static image).

**Comment by F4z** [comment]
Ma odnośnik, tylko musisz wyłączyć `polskie filtry do uBlocka uzupelnienie`.
Otwieram zgłoszenie, żeby nie zapomnieć dodać tego do listy potem.

**Comment by MajkiIT** [comment]
@F4z 
`forum.dobreprogramy.pl##body[class]:style(background-image: none !important;)`
to chyba można wrzucić do filtrów Adblock & Ublock?

**Comment by F4z** [comment]
@MajkiIT tak :)

**Comment by MajkiIT** [comment]
@F4z Ok dziękuję.

**Comment by F4z** [comment]
@MajkiIT aj wybacz, źle Cię zrozumiałem, myślałem, że Adblock & Ublock to ta druga lista.
Ta reguła najprawdopodobniej popsuje Adblocka.

**Comment by MajkiIT** [comment]
@F4z poprawione.

**Comment by F4z** [comment]
@FadeMind swoją drogą, jaki był/jest domyślny kolor tła forum, biały?
