### ISSUE TITLE
fxmag.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2313]
from reek's https://github.com/reek/anti-adblock-killer/issues/2960

**Comment by MajkiIT** [comment]
@xxcriticxx Sprawdzisz?

`@@||www.fxmag.pl/bundles/resources/js/ads.js$script,domain=www.fxmag.pl`

**Comment by MajkiIT** [comment]
@xxcriticxx już widzę tam jest rozwiązanie.
