### ISSUE TITLE
naekranie.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#2314]
![screenshot_20170317_084730](https://cloud.githubusercontent.com/assets/9846948/24033698/7b4d9f1a-0aee-11e7-847c-dc6f9f78f7cc.png)

**Comment by F4z** [comment]
Dzięki za zgłoszenie.
Ta reguła chyba powinna wystarczyć:
`naekranie.pl##[class^="welcome_screen"]`

**Comment by xxcriticxx** [comment]
@F4z regula jest dobra dziala ale jak zablokujesz TABU potem jest cos takiego

![capture](https://cloud.githubusercontent.com/assets/15007183/24045235/bf2d274a-0af4-11e7-91b1-4da3e19d847f.PNG)
