### ISSUE TITLE
trojmiasto.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2317]
Komunikat o adblocku

![trojmiasto](https://cloud.githubusercontent.com/assets/23176832/24053370/2461550c-0b39-11e7-8a52-8eb2c4538102.jpg)

**Comment by xxcriticxx** [comment]
@blocker999 masz adblockproctor script? jest to nowa ver projektu reek

**Comment by blocker999** [comment]
na tej przeglądarce, nie

**Comment by xxcriticxx** [comment]
jak daasz rade to dodaj albo @MajkiIT doda jakos regule na to
