### ISSUE TITLE
krakow.onet.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2318]
Reklamy

![krakow](https://cloud.githubusercontent.com/assets/23176832/24053500/82e1328c-0b39-11e7-846d-f4b1ae2aa29a.png)

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z zerkniecie bo ja nie widze tego.

**Comment by xxcriticxx** [comment]
nic niemam

**Comment by MajkiIT** [comment]
@xxcriticxx dzięki
