### ISSUE TITLE
spottedlublin.pl

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#2320]
Artykuł jest ukrywany przez `##.share-container` z "Fanboy’s Annoyance List", a ja się tam na forum dobić nie mogę. Możecie coś z tym zrobić?

http://spottedlublin.pl/tragiczny-final-domowej-awantury-pijany-43-latek-zabil-matke/

**Comment by xxcriticxx** [comment]
@gwarser ja nie widze tam forum

**Comment by MajkiIT** [comment]
@gwarser dodamy wyjątek. Dzięki. Ty jesteś z lbn ?

**Comment by gwarser** [comment]
@xxcriticxx chodziło mi o forum.lanik.us.
@MajkiIT że Lublin? Raczej tylko lubelskie.

**Comment by MajkiIT** [comment]
@gwarser No ja pochodzę z lbn dlatego pytam
