### ISSUE TITLE
telewizjarepublika.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2327]
resztki po reklamach 

![capture](https://cloud.githubusercontent.com/assets/15007183/24083375/40828d22-0cac-11e7-99e1-b3020918bb1b.PNG)

**Comment by xxcriticxx** [comment]
more joy na sub pagach 

![capture](https://cloud.githubusercontent.com/assets/15007183/24172465/a5d67b26-0e5e-11e7-940d-acb02cb62c3e.PNG)

`telewizjarepublika.pl##.box-szary`

**Comment by MajkiIT** [comment]
@xxcriticxx dzięki
