### ISSUE TITLE
biedronka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2331]
kup magazyn + lewa prawa strona jak przeszkadza

![capture](https://cloud.githubusercontent.com/assets/15007183/24199799/60d81db2-0ee1-11e7-9f95-1dc6f58073e5.PNG)

```
||static.biedronka.pl/img/background/bg-animals.jpg$image
||static.biedronka.pl/img/background/bg-animals-top.png?v=523$image
||cdn.biedronka.pl/__2017/T09B/moje_smaki_zycia/msz_970x145.jpg$image
biedronka.pl##.size6x1.position9x1.slot
```

**Comment by krystian3w** [comment]
#13398  - zepsułeś...

**Comment by krystian3w** [comment]
@KonoromiHimaries może takie coś na magazyn kropka:

`||cdn.biedronka.pl/*/*/*kropka*/*banner_970x145.jpg$image`

luki nawet filtr kosmetyczny nie zminimalizuje.
