### ISSUE TITLE
sport.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2336]
**MATERIALY PARTNERA** 

`http://www.sport.pl/mundial/1,154383,20825076,ranking-fifa-w-pazdzierniku-polska-najwyzej-w-historii.html`

![capture](https://cloud.githubusercontent.com/assets/15007183/24215359/e645965a-0f0e-11e7-890d-5bcc1318bce9.PNG)

**Comment by MajkiIT** [comment]
`||avanti.fashion/pub/ips/$subdocument`
