### ISSUE TITLE
spidersweb.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2338]
spidersweb.pl##.text-center
prawdopodobnie blokuje menu w nowym layout’cie ?

**Comment by F4z** [comment]
@MajkiIT dzisiaj już było zgłoszenie odnośnie tego, ale osoba która to zgłosiła najprawdopodobniej usunęła konto i zgłoszenie "wcięło" - https://github.com/MajkiIT/polish-ads-filter/issues/2337
Usunąłem już tę regułę - https://github.com/MajkiIT/polish-ads-filter/commit/4842628ff602b3a0aaaaae7428b300b10d42c454

Z tego co widzę, to trzeba też dodać taką regułę, bo nowa reklama się pojawiła:
`||spidersweb.pl/wp-content/themes/*/reklamy/$subdocument`

W tym usuniętym temacie pytałem się też, czy dodawać reguły, które zablokowałyby obrazki (reklamy) żeby po prostu ich nie pobierało.
```
||ocs-pl.oktawave.com/v1/AUTH_2887234e-384a-4873-8bc5-405211db13a2/spidersweb/2017/03/MV_nolimit_1180x200.jpg
||ocs-pl.oktawave.com/v1/AUTH_2887234e-384a-4873-8bc5-405211db13a2/spidersweb/2017/03/EXPLORE_1401_Spidersweb_3*x*px_V*_02-03-2017.jpg
||ocs-pl.oktawave.com/v1/AUTH_2887234e-384a-4873-8bc5-405211db13a2/spidersweb/2017/03/300x700.jpg
||ocs-pl.oktawave.com/v1/AUTH_2887234e-384a-4873-8bc5-405211db13a2/spidersweb/2017/03/400x400-1.jpg
||ocs-pl.oktawave.com/v1/AUTH_2887234e-384a-4873-8bc5-405211db13a2/splay/2017/03/xc_laser_400x400_2.jpg
||ocs-pl.oktawave.com/v1/AUTH_2887234e-384a-4873-8bc5-405211db13a2/splay/2017/03/xc_laser_300x700_2.jpg
||ocs-pl.oktawave.com/v1/AUTH_2887234e-384a-4873-8bc5-405211db13a2/spidersweb/2017/03/1200x300.jpg
```
Tylko tam mniej więcej co miesiąc są nowe reklamy, więc nie wiem czy warto to robić.
Chyba, że dodalibyśmy to gdzieś w sekcji "tymczasowych reguł" tak żeby było łatwo to odróżnić i zmienić potem?

**Comment by MajkiIT** [comment]
@F4z dzięki. A co tych reklma to dam do tych tymczasowych jak mówisz.

**Comment by xxcriticxx** [comment]
@MajkiIT @F4z co sie stalo z orinalnym postem?

**Comment by F4z** [comment]
@MajkiIT ta reguła jest zła, bo blokuje obrazki na stronie - `||ocs-pl.oktawave.com/v1/AUTH_2887234e-384a-4873-8bc5-405211db13a2/$image,domain=spidersweb.pl`

**Comment by MajkiIT** [comment]
@F4z dzięki
