### ISSUE TITLE
www.autocentrum.pl/joemonster.org

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2339]
@F4z @xxcriticxx Możecie zerknąc?

https://www.autocentrum.pl/
http://joemonster.org/art/39179/Faktopedia_CDXXVIII_co_sie_stalo_kiedy_Kojot_zlapal_wreszcie_Strusia_Pedziwiatra

Filtr statyczny joemonster.org##img[src^="data:image"] znajdujący się w:
POL: polskie filtry do Adblocka i uBlocka

Filtr blokuje część zdjęć.
Sprawdzone na przeglądarce roboczej oraz na przeglądarce tylko do testów gdzie nie wprowadzam dodatkowych filtrów sam

**Comment by xxcriticxx** [comment]
@MajkiIT niewiem czego szukam ale mi sie zdaje ze mam to samo 15 zdjec i 82 komentarze

**Comment by F4z** [comment]
@MajkiIT z tego co zaobserwowałem, to tak się dzieje, gdy `unblock` nie jest blokowany.
Czyli w Chrome/Operze z Adblockiem lub z uBlockiem Origin (gdy wyłączona jest lista "polskie filtry do uBlocka uzupelnienie") oraz w Firefoksie z Adblockiem.

Wydaje mi się, że oni tam sprawdzają, czy te elementy są ukryte - `pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links` - i jeśli tak jest, to wtedy część obrazków jest kodowana do base64 i wtedy przez tę regułę (`##img[src^="data:image"`]) zostają schowane.

Te reguły raczej powinny rozwiązać problem:
```
autocentrum.pl,gry-online.pl,joemonster.org#@#.pub_300x250
autocentrum.pl,gry-online.pl,joemonster.org#@#.pub_300x250m
autocentrum.pl,gry-online.pl,joemonster.org#@#.pub_728x90
autocentrum.pl,gry-online.pl,joemonster.org#@#.text-ad
autocentrum.pl,gry-online.pl,joemonster.org#@#.textAd
autocentrum.pl,gry-online.pl,joemonster.org#@#.text_ad
autocentrum.pl,gry-online.pl,joemonster.org#@#.text_ads
autocentrum.pl,gry-online.pl,joemonster.org#@#.text-ads
autocentrum.pl,gry-online.pl,joemonster.org#@#.text-ad-links
```

<details>Tak swoją drogą, to najlepiej by było, gdyby ludzie przestali korzystać z Adblocka/Adblocka Plus 😜</details>

**Comment by F4z** [comment]
Jeszcze ta reguła może być potrzebna:
`@@/ad/banner/_adsense_/_adserver/_adview_.ad.json?adzone=top&adsize=300x250&advid=$domain=autocentrum.pl|gry-online.pl|joemonster.org`

**Comment by xxcriticxx** [comment]
@F4z a to dzie sie pokazuje na topie?

**Comment by F4z** [comment]
@xxcriticxx nie wiem o co się pytasz, chodzi Ci o "znikające" obrazki, czy o coś innego?

**Comment by xxcriticxx** [comment]
@F4z pytam co to blokuje widze adzone=top to myslalem ze to gdzies jest na topie

**Comment by F4z** [comment]
@xxcriticxx te dwie ostatnie reguły odblokowują zablokowane połączenia.

![image](https://cloud.githubusercontent.com/assets/11742596/24323308/f1da9512-1173-11e7-90e0-109414524b62.png)

**Comment by xxcriticxx** [comment]
@F4z thx za info

**Comment by MajkiIT** [comment]
@F4z @xxcriticxx 
Dzięki za pomoc.
