### ISSUE TITLE
stooq.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2343]
reklama cmc market prawa strona 

![capture](https://cloud.githubusercontent.com/assets/15007183/24323948/d1988e82-1153-11e7-87fd-42dc423aaa97.PNG)

**Comment by F4z** [comment]
`stooq.com##div[onclick^="(function"][onclick*="window.open"][style^="animation"]`

**Comment by MajkiIT** [comment]
@F4z dzięki
