### ISSUE TITLE
tv.jardello.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2349]
@F4z da cos zrobic stym counterem?

`http://www.tv.jardello.com/film/35373`

![image](https://cloud.githubusercontent.com/assets/15007183/24324825/d421e652-1163-11e7-809e-070885f39c7b.png)

**Comment by F4z** [comment]
@xxcriticxx możesz sprawdzić?

`videosio.pl###video_player_container:style(display: inline !important;)`
`videosio.pl###preroll_placeholder`

**Comment by xxcriticxx** [comment]
film padl i timer dalej lecj ale juz widac film. poprostu jest lepjej niz bylo

![capture](https://cloud.githubusercontent.com/assets/15007183/24325286/cb082470-116b-11e7-8773-762cf16b3df0.PNG)

**Comment by F4z** [comment]
Ten "timer" można ukryć taką regułą:
`videosio.pl###preroll_placeholder`

Tylko wtedy tutaj też będzie to ukryte - `http://videosio.pl/watch.php?vid=dc27faf6f` - a w tym przypadku raczej potrzebny jest skrypt żeby to ominąć.

**Comment by xxcriticxx** [comment]
@F4z dodalem te dwie reguly i jest super ukrylo timer i film sie odpala odrazu tak jest na chromie na foxie bende za godzine

**Comment by xxcriticxx** [comment]
@F4z na foxie tez dziala dobrze. widze ze laduje popads.net to gdzies benda jeszcze reklamy

**Comment by MajkiIT** [comment]
@F4z te reguły jak mniemam do listy tylko do Ublocka?

**Comment by F4z** [comment]
@MajkiIT tak, tylko do uBlocka.
