### ISSUE TITLE
wiadomosci.wp.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2358]
@F4z @xxcriticxx 

Tylko u mnie napisy reklama?
http://wiadomosci.wp.pl/tragiczny-wypadek-busa-kolo-pawlowa-na-mazowszu-nie-zyje-5-osob-6105470686905473a

**Comment by xxcriticxx** [comment]
@MajkiIT nope ja tez mam. gdzie jest post telepizza?

![capture](https://cloud.githubusercontent.com/assets/15007183/24350533/892a2b98-12b0-11e7-95bc-cc139b217c91.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx ok dzięki. 

Co do telepizzy to znowu ktoś uisunął.

**Comment by xxcriticxx** [comment]
Wiedzialem niechcial być sponsorem :(

**Comment by MajkiIT** [comment]
No tak albo przynajmniej domyślam się, ale to nie powód aby usuwać zgłoszenia :(

**Comment by F4z** [comment]
@MajkiIT też to mam.
Ta reguła powinna to ukryć:
`wiadomosci.wp.pl##div[class^="_"]:matches-css(min-width: 300px):matches-css(background-color: rgb(242, 242, 242))`

Tak przy okazji, to wydaje mi się, że tutaj jest błąd - https://github.com/MajkiIT/polish-ads-filter/commit/9c0df98469e348ee720abf4f73f619e830eec7fc#diff-019c4d6c3918d69cd67e76aeec0a04a5R1056
Raczej zamiast przecinka `,` powinna być pionowa kreska `|`

`/js/jquery.cookie.min.js$script,domain=~rozklad-pkp.pl|~telepizza.pl`

**Comment by MajkiIT** [comment]
@F4z Dzięki, za obie informacje.
