### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by Eva850** [MajkiIT/polish-ads-filter#2360]
Puste miejsce po reklamach
http://wiadomosci.wp.pl/w-polsce-powstaje-kolejny-meczet-sprawdzilismy-6105535227019905a
![wp](https://cloud.githubusercontent.com/assets/20646455/24377557/0b570782-1340-11e7-908c-881523b8b687.png)

**Comment by xxcriticxx** [comment]
@Eva850 please update filters
