### ISSUE TITLE
filmyfantastyczne.pl

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#2363]
Ukrywane są obrazki filtrem `pl##.alignnone` z Adblock polskie reguly social

http://filmyfantastyczne.pl/newsy/kto-ja-zagral-i-jak-wygladala-na-planie-kulisy-slynnej-sceny-z-lotra-1?view-all=1

**Comment by MajkiIT** [comment]
Dzięki zaraz dodam wyjątek.

**Comment by gwarser** [comment]
To samo tutaj http://film.org.pl/news/angel-a-szykujcie-sie-na-rasowy-cyberpunk-prosto-z-polski-107593/

**Comment by MajkiIT** [comment]
@gwarser Dzięki

**Comment by gwarser** [comment]
http://www.crazynauka.pl/sonda-kosmiczna-przeleciala-pomiedzy-pierscieniami-saturna-sa-pierwsze-zdjecia-z-tego-wyjatkowego-manewru/

**Comment by MajkiIT** [comment]
@gwarser ???

**Comment by gwarser** [comment]
Coś się chyba spartoliło w tym kommicie https://github.com/MajkiIT/polish-ads-filter/commit/1394ea04e5fdaffa48454b77e02a6d299a97384a

bo wszystkie wyjątki zniknęły.

**Comment by gwarser** [comment]
Mam napisać nowe zgłoszenie?

**Comment by MajkiIT** [comment]
@ blocker999 zerkniesz?

**Comment by xxcriticxx** [comment]
maybe?

`filmyfantastyczne.pl##.main-top-sidebar-wrap`

**Comment by gwarser** [comment]
Nie chodzi o banner, tylko ukryte obrazki w tekście. To jest chyba jakiś plugin do bloga/skórka, która wstawia obrazki z klasą `.alignnone`. Lista socjalna ma taki filtr `pl##.alignnone` - dodawaliśmy w tym zgłoszeniu wyjątki do niego, i parę dni temu ktoś pewnie przywrócił ze swojego repo starszą wersję.

**Comment by xxcriticxx** [comment]
@gwarser mam to skasowac? chyba prawa collaborator mi na ta pozwalaja

**Comment by gwarser** [comment]
Było dodane tutaj https://github.com/MajkiIT/polish-ads-filter/commit/32f2d9948ac1728f61ca92f0835e352bbaa4e73f ale brak opisu. Nie wiem do czego to. Jak chcesz to usuwaj.

Wszystkie `\` też możesz usunąć, bo to jakiś błąd w jakimś skrypcie musi być. Oprócz tych: `pl###LinkArea\:SGfoG\+`, chyba wszystkie filtry były dodane bez backspejsów, tylko potem się jakoś "wkradły".

**Comment by MajkiIT** [comment]
@gwarser Dzięki zaraz poprawię

**Comment by MajkiIT** [comment]
@gwarser Dzięki poprawione.
