### ISSUE TITLE
appleworld.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2373]
`http://www.appleworld.pl/firma-apple-odrzuca-aplikacje-z-informacjami-o-cenie-np-free-w-tytule-aplikacji/`

![capture](https://cloud.githubusercontent.com/assets/15007183/24473543/ae186bc0-1497-11e7-8ee1-ac3812fae3d5.PNG)

**Comment by MajkiIT** [comment]
||moviads.pl$domain=~moviads.pl
||zolti.pl/ajax/affiliate-generator.php?$script
||adsb4track.com/?$script
||partnerzyapi.ceneo.pl$script
||disqus.com$subdocument
