### ISSUE TITLE
domeny do ciasteczek

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2381]
Przykłady - http://forum.fujiklub.pl, http://www.fly4free.pl, olx.pl czy otodom i wiele innych, gdzie mimo subskrybcji filtra cookie są one wyświetlane...

**Comment by xxcriticxx** [comment]
@MajkiIT ja nie widze zadnych info o ciastach na podanych stronach

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki. U mnie też jest ok.
