### ISSUE TITLE
bankier.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2389]
Znalezione tutaj - `http://www.wykop.pl/wpis/23027897/bankier-adblock-bye-bye-bankier-pl/`
Komunikat o adblocku - `http://www.bankier.pl/wiadomosc/Kwestia-gornictwa-wraca-na-GPW-Spadki-PGE-i-Energi-7508309.html`

![image](https://cloud.githubusercontent.com/assets/11742596/24523054/125beeae-1592-11e7-8ab3-ad377a98ca84.png)

Na przykład:
`||bankier.pl/static/js/gruffalo.js$script`
lub
`bankier.pl#@#.adsbox`

Dodatkowo do uBlocka można jeszcze dodać to:
`bankier.pl##.boxContent > ul > li[class^="item-"]:has(.premium-link)`
żeby ukryć linki do reklam na stronie głównej - `http://www.bankier.pl/`

![image](https://cloud.githubusercontent.com/assets/11742596/24523224/9f41e256-1592-11e7-8518-e6802e781db9.png)

**Comment by MajkiIT** [comment]
@F4z Dzięki

**Comment by F4z** [comment]
Znowu.

Na przykład:
`||bankier.pl/static/js/kichot.js$script`
lub
`bankier.pl#@#.adsbox`

**Comment by MajkiIT** [comment]
@F4z Dzięki

**Comment by MajkiIT** [comment]
@F4z Masz adblocka?

**Comment by F4z** [comment]
@MajkiIT tak.
Zmienili element, który sprawdzają.
Teraz to powinno działać:
`bankier.pl#@#.ads_box`
lub
`||bankier.pl/static/js/kichot.js$script`

Można też do reguł uBlocka coś takiego dodać:
`bankier.pl##script:inject(abort-on-property-write.js, detectAB)`

**Comment by MajkiIT** [comment]
@F4z Dziękuję. Dodane

**Comment by F4z** [comment]
@MajkiIT to - `/^http:\/\/www\.bankier.\pl\/static\/js\/[a-z]{5,9}\.js/$script` - blokuje trochę za dużo, bo w wyszukiwarce na stronie nie pokazuje podpowiedzi.

![image](https://cloud.githubusercontent.com/assets/11742596/25010455/7c465b00-206a-11e7-98bf-796638692f2c.png)

**Comment by MajkiIT** [comment]
@F4z Dzięki już poprawiam.
