### ISSUE TITLE
spidersweb.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2390]
Pozostałość po reklamie - `http://www.spidersweb.pl/2017/03/samsung-galaxy-s8-plus-premiera.html`
![image](https://cloud.githubusercontent.com/assets/11742596/24523628/f5a0f1ae-1593-11e7-9f6a-87c82a4001d2.png)

Na przykład:
`spidersweb.pl###top_banner`

**Comment by MajkiIT** [comment]
@F4z Dzięki
