### ISSUE TITLE
speedtest.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2405]
cos zjadlo cale menu 

`http://www.speedtest.pl/wiadomosci/`

![capture](https://cloud.githubusercontent.com/assets/15007183/24589135/4ae26dbc-17a3-11e7-8f22-fae013e5c9ce.PNG)

**Comment by MajkiIT** [comment]
Ale tam są reklamy chyba.

**Comment by xxcriticxx** [comment]
to nie lepjej calej strony do gory podciagnac

**Comment by blocker999** [comment]
oprócz reklam są też i należało by je odblokować

**Comment by F4z** [comment]
Te artykuły na górze, to mają takie same linki jak reklamy od google, więc nie wiem czy to powinno być odblokowane.

![image](https://cloud.githubusercontent.com/assets/11742596/24590828/63628e84-17f4-11e7-9737-e5f044d55d38.png)

**Comment by xxcriticxx** [comment]
@F4z ok jak idzie zamnknac te duza dziure?

**Comment by F4z** [comment]
@xxcriticxx na przykład tak:
`speedtest.pl##div[style^="width: 1068px; height: 470px; margin: 20px auto"]`

**Comment by xxcriticxx** [comment]
bingo mozna dodac

**Comment by MajkiIT** [comment]
@F4z Dzięki
