### ISSUE TITLE
auto.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2408]
`http://www.auto.pl/gielda/offer.php?kod=15pqcb`

![capture](https://cloud.githubusercontent.com/assets/15007183/24589483/0c26f588-17a9-11e7-8277-b94530728489.PNG)

**Comment by F4z** [comment]
@MajkiIT `auto.pl##.text-center` za dużo blokuje, na przykład na stronie głównej nie ma napisów przy niektórych elementach.

Link - `http://www.auto.pl/`

![image](https://cloud.githubusercontent.com/assets/11742596/24590534/f66847a6-17ee-11e7-9400-597e758fbc1e.png)

**Comment by MajkiIT** [comment]
poprawione.

**Comment by F4z** [comment]
@MajkiIT dzięki, ale wydaje mi się, że jeszcze element "Kliknij by wyświetlić numer" nie powinien być ukryty.
![image](https://cloud.githubusercontent.com/assets/11742596/24590915/40302fd2-17f6-11e7-808c-2392d38ab26f.png)

Link - `http://www.auto.pl/gielda/offer.php?kod=15pqcb`

**Comment by MajkiIT** [comment]
@F4z do 3 razy sztuka.
