### ISSUE TITLE
tvsudecka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2410]
reklama

`http://www.tvsudecka.pl/wiadomosci/62491,dkb-w-rankingu-najlepszych-piesciarzy`

![image](https://cloud.githubusercontent.com/assets/15007183/24589615/8e7dfeee-17ab-11e7-8fed-d8e726e2e766.png)

**Comment by xxcriticxx** [comment]
@MajkiIT jest tego wiecje zobacz z prawej strony i na dole i na $subdomumentach

**Comment by MajkiIT** [comment]
Dzięki moje przeoczenie.
