### ISSUE TITLE
zaufanatrzeciastrona.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2412]
Reklamy - `https://zaufanatrzeciastrona.pl/`

![image](https://cloud.githubusercontent.com/assets/11742596/24590577/81be869e-17ef-11e7-9bec-dc07b5d11427.png)

Chyba powinno wystarczyć:
```
zaufanatrzeciastrona.pl##a[href="https://zaufanatrzeciastrona.pl/ydAb"]
zaufanatrzeciastrona.pl##a[href="https://zaufanatrzeciastrona.pl/t1.php"]
zaufanatrzeciastrona.pl##a[href="https://zaufanatrzeciastrona.pl/t2.php"]
||zaufanatrzeciastrona.pl/wp-content/uploads/2017/03/a.jpg
||zaufanatrzeciastrona.pl/wp-content/uploads/2017/03/b.jpg
||zaufanatrzeciastrona.pl/wp-content/uploads/2017/03/c.jpg
||zaufanatrzeciastrona.pl/wp-content/uploads/2017/03/d.jpg
||zaufanatrzeciastrona.pl/wp-content/uploads/2017/03/e.gif
```

**Comment by MajkiIT** [comment]
Dzięki

**Comment by F4z** [comment]
Znowu.
Na przykład:
`zaufanatrzeciastrona.pl###sidebar > a[href]:nth-of-type(1) > img`
`zaufanatrzeciastrona.pl###sidebar > a[href]:nth-of-type(2) > img`
lub
`zaufanatrzeciastrona.pl###sidebar > a[href] > img`

**Comment by xxcriticxx** [comment]
ciekawe jak dlugo nazwy nie zmienia

`||zaufanatrzeciastrona.pl/wp-content/uploads/2017/03/e1.gif$image`
`||zaufanatrzeciastrona.pl/wp-content/uploads/2017/03/a1.jpg$image`

or 

`||zaufanatrzeciastrona.pl/wp-content/uploads/2017/03/*.gif$image`
`||zaufanatrzeciastrona.pl/wp-content/uploads/2017/03/*.jpg$image`

**Comment by F4z** [comment]
Te dwie ostatnie reguły są złe, bo zablokują obrazki, które nie są reklamami.

**Comment by xxcriticxx** [comment]
widze ze na supbages juz jest inna nazwa tego

**Comment by F4z** [comment]
Tak, jest tego więcej.

**Comment by xxcriticxx** [comment]
||zaufanatrzeciastrona.pl/wp-content/uploads/2017/03/b1.jpg

**Comment by xxcriticxx** [comment]
albo cos takiego?

zaufanatrzeciastrona.pl##img[src="https://zaufanatrzeciastrona.pl/wp-content/uploads/2017/03/b1.jpg"]

**Comment by F4z** [comment]
A to te reguły, które podałem nie działają?

`zaufanatrzeciastrona.pl##img[src="https://zaufanatrzeciastrona.pl/wp-content/uploads/2017/03/b1.jpg"]`
W przypadku, gdy znowu zmienią nazwę obrazka z reklamą, to też będzie trzeba zmienić taką regułę.

**Comment by xxcriticxx** [comment]
zaraz przetestuje

**Comment by xxcriticxx** [comment]
na ta pusta box na topie 

`zaufanatrzeciastrona.pl###sponsor2`

**Comment by xxcriticxx** [comment]
ok @F4z milej nocy zycze do jutra lece postac w korkach

**Comment by F4z** [comment]
@xxcriticxx ok, dzięki, do jutra.
Miłego stania w korkach 😛

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z dzięki.

**Comment by F4z** [comment]
Znowu.

**Comment by blocker999** [comment]
@MajkiIT 

Kiedy dodaszregułe na ta pusta box na topie

`zaufanatrzeciastrona.pl###sponsor2`

**Comment by xxcriticxx** [comment]
`zaufanatrzeciastrona.pl###rab1`

![capture](https://cloud.githubusercontent.com/assets/15007183/25041472/3bf87c26-20de-11e7-8e26-0add4124f5f7.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx zaktualizuj fitry
