### ISSUE TITLE
Problem MiniMiniPlus.pl Ublock Origin.

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#2415]
Tak jak w temacie. Jak nie dodam do wyjątków miniminiplus.pl, to filmy są nieosiągalne. Natomiast jak dodam, to zanim włączy się właściwe video, to poprzedza je diabelska prawie 20-30 sekundowa reklama i nic nie można z tym zrobić. Mam tak od niedawna w moim FF z Ublock Origin i od razu filtry wszystkie włączone i odznaczona (wyłączona) opcja związana z ignorowaniem filtrów kosmetycznych. Czy jest jakieś rozwiązanie na te tvn playery ?

Pozdrawiam

**Comment by F4z** [comment]
Przy użyciu samego uBlocka Origin w obecnej chwili nie widzę takiej możliwości.
Jako alternatywne rozwiązanie możesz zainstalować rozszerzenie "Tampermonkey" i dodać skrypt "AdBlock Protector" - https://x01x012013.github.io/AdBlockProtector/
Tylko trzeba go trochę zmodyfikować, bo na razie nie ma dodanej strony "miniminiplus.pl".
Żeby to zrobić musiałbyś w 912 linijce dodać "miniminiplus.pl" do listy stron, tak żeby wyglądało to jak na obrazku poniżej.

![image](https://cloud.githubusercontent.com/assets/11742596/24631860/4286f73a-18c2-11e7-8037-bb0ed29798d3.png)

Ewentualnie jeszcze możesz zainstalować Adguarda w wersji dla Windowsa, on też powinien sobie radzić z tym, tylko to jest płatny program.

**Comment by xxcriticxx** [comment]
@seba2282 @F4z zaraz zamowie poprawke

**Comment by F4z** [comment]
@xxcriticxx ok, dzięki :)

**Comment by seba2282** [comment]
Na Android to samo, z tym że film działa, ale reklama jak się włącza, to zasłania film...

**Comment by F4z** [comment]
Na Androidzie tego nie sprawdzałem.

**Comment by seba2282** [comment]
Adquard w ff robi to samo na wszystkich włączonych filtrach mobilnie na android (z uwzględnieniem blokowania pożądanych reklam). Nie wiem jak dla ff pc z adquard.

**Comment by seba2282** [comment]
Problem się rozwiązał. Dziękuję za pomoc.

**Comment by seba2282** [comment]
Jednak powróciło. A przez chwilę było dobrze na PC i Android. :(

**Comment by seba2282** [comment]
Jeżeli to pomoże, to teraz na PC film jest raz nieosiągalny, a raz dziala. Na android raz się pojawiają te zasłaniające kilku sekundowe banery, co potem nawet wyłączyć nie idzie, a raz chodzi perfekcyjnie bez reklam. Wszystko Firefox + Ublock Origin z włączonymi wszystkimi filtrami. Czy można prosić​ o jakiś dobry fix ? Bo widzę, że coś blokuje filmiki na MiniMiniPlus.pl

**Comment by xxcriticxx** [comment]
@seba2282 wykasuj browsing history i cookies zrob update ad protector

**Comment by seba2282** [comment]
Na PC nawet zrobiłem odśwież FF i na nowo ustawiałem, a w Android w aplikacjach FF i wyczyść dane i też na nowo. O co chodzi z tym Ad Protector ?

**Comment by F4z** [comment]
To że raz działa, a innym razem nie, to kwestia tego czy odtwarzacz chce wczytać reklamę, czy nie.
Jeśli chce wczytać reklamę, to uBlock ją zablokuje i dostaniesz komunikat "materiał jest niedostępny".
Gdy nie będzie ładował reklamy, to wtedy film będzie działał.
Niestety w tej chwili jedynym rozwiązaniem jakie widzę w przypadku Adblocka/uBlocka to odblokowanie reklam.

Tak jak pisałem wcześniej, alternatywne rozwiązanie, to instalacja rozszerzenia "Tampermonkey" i dodanie skryptu "AdBlock Protector" - https://x01x012013.github.io/AdBlockProtector/
Albo korzystanie z Adguarda w wersji na Windowsa.
Oba rozwiązania wczoraj testowałem i działały.

**Comment by xxcriticxx** [comment]
moze masz jakies inne aplikacje co blokuja? moze masz host file? najlepjej wszystko powylanczac i testowac z jedna

**Comment by seba2282** [comment]
Ani host file, ani nic blokującego. Tylko FF + UBO. Nie wiem co zrobili z tym github, że nie mogę pisać komentarzy na PC, a na Android zero problemów. Generalnie wydaje mi się, że winowajcą jest Anti block killer w UBO, który może oczekuje na fixa. Ale zauważyłem coś dziwnego. Jak zaczęłem szperać w UBO, gdzie wyświetla nazwy domen podłączonych do danej strony i prawie wszystkie jak dałem na fioletowy kolor, to tak jakby trochę blokowało te popupy. Przywróciłem z powrotem, jak było i problem znowu.

**Comment by xxcriticxx** [comment]
@seba2282 odmontuj aak listste i zamontuj ad protectora please

**Comment by seba2282** [comment]
Nie mam czegoś takiego jak aak, bo jest zintegrowany filtr antiblock killer w UBO. Ten protector nie wiem jak podmontować (Android i PC).

**Comment by xxcriticxx** [comment]
@seba2282 odznacz go z listy ubo i wykasuj script w tampermonkey/grease monkey

**Comment by seba2282** [comment]
Na FF Android nie działa. Nie wiem jak PC.

**Comment by seba2282** [comment]
Winowajcą jest gemius.pl Jak dodam to coś na czarną listę domen w Adquqrd Android, to mam znany komunikat, aby wyłączyć blokowanie reklam. Czy możecie to wytępić na polskim filtrze, aby było normalnie blokowane, a filmy działały ?

**Comment by MajkiIT** [comment]
czyli coś takiego powinno być ok

`@@||gemius.pl/$subdocument,script,domain=www.miniminiplus.pl`

Sprawdzicie?

**Comment by seba2282** [comment]
Nie mając w białej liście AdQuard www.miniminiplus.pl, ten filtr użytkownika powoduje i tak, że bloker nadal jest blokowany przez stronę. Natomiast jak dodam do białej listy użytkownika w opcjach Adquard www.miniminiplus.pl, to za pierwszym razem film się odpali, ale po restarcie chrome już się pojawia ta reklama przed filmem. Przypominam, że do testów mam AQ + chrome mobile, bo łatwiej ustalić wtedy co się dzieje. I stąd wiem, że gemius.pl to problem.

**Comment by MajkiIT** [comment]
@seba2282 to jak mówił @F4z czasami player ładuje reklamę a czasami nie. Wystarczy 2 raz odświeżyć i jest ok.  Filtr z gemiusem to połowiczne wyjście.

**Comment by seba2282** [comment]
Nie do końca. Za pierwszym razem, jak pójdzie filmik, dowolny. To po ponownym wejściu np w Chrome, czy gdzie kolwiek od tego momentu ładują się te reklamy, bądź filmiki nieosiągalne. I tak jest wtedy cały czas. Masz wgląd na kody stron player.pl, miniminiplus.pl, te całe tvn playery ? I na to co blokuje UBO bądź AQ ? Bo coś łączy te strony i coś cały czas jest przeoczane i trzeba coś dodać do filtrów. I wiemy to wszyscy tutaj.

**Comment by MajkiIT** [comment]
@seba2282 U mnie jest zawsze to samo https://www.screencast.com/t/QGAlzRr5 . Chce załadować reklamę a ublock ją blokuje. 

Jak napisał @F4z 
"To że raz działa, a innym razem nie, to kwestia tego czy odtwarzacz chce wczytać reklamę, czy nie.
Jeśli chce wczytać reklamę, to uBlock ją zablokuje i dostaniesz komunikat "materiał jest niedostępny".
Gdy nie będzie ładował reklamy, to wtedy film będzie działał."

**Comment by seba2282** [comment]
Ciekawe...

**Comment by xxcriticxx** [comment]
@seba2282 odmontowales AAK?

**Comment by seba2282** [comment]
@xxcriticxx Czemu się pytasz o AAK ? UBO ma zintegrowany filter Reek, jak i AQ. :)

**Comment by xxcriticxx** [comment]
@seba2282 ale script nie jest updatowany dlatego dgo lepjej odmontowac i zamontowac adblock protector. jest tam poprawka do minimini.

**Comment by seba2282** [comment]
Zrobiłem tak jak polecono. Ff + UBO Android. Odmontowałem AntiBlockKiller Reek i po kliknięciu na link Adblock Protector dodało mi wersję 10.0 do filtrów UBO bez niczego. I mam te cholerne reklamy zasłaniające filmiki.

**Comment by xxcriticxx** [comment]
@seba2282 zrobiles cos nie poprawnie. jest potrzebny script i lista tak jak bylo u reeka.

**Comment by seba2282** [comment]
Tylko nie pozwala mi zainstalować pierwszego, dopiero drugie z automatu się dodaje do android.

**Comment by xxcriticxx** [comment]
na telefownie z adroidem to chyba nie bendzie dzialac bo niema managera do scriptow

**Comment by xxcriticxx** [comment]
lista:

https://raw.githubusercontent.com/X01X012013/AdBlockProtector/master/AdBlockProtectorList.txt

script:

https://github.com/X01X012013/AdBlockProtector/raw/master/AdBlockProtector.user.js

**Comment by seba2282** [comment]
Na android już wczytało listy i n8by działa. Teraz spojrzę na PC i nie mam tarmomonkey, a filtruje.

**Comment by xxcriticxx** [comment]
jest potrzebny i script i lista domontuj TM sobie

**Comment by seba2282** [comment]
Niby na PC działa, ale mobilnie nie idzie. Kurka wodna...

**Comment by xxcriticxx** [comment]
na adroidzie niema scriptu managera niemysle ze bendzie dziala az autor cos dopisze

**Comment by xxcriticxx** [comment]
@seba2282 podaj info jaki o swoim adnroidzie. jaki os? jaki browser?

**Comment by seba2282** [comment]
Android 6.0 na P8 Lite i Firefox. Tak sobie pomyślałem, może i głupie, ale... Czy twórca tego adblocker protector i twórca ublock origin nie mogliby się dogadać i zintegrować ten protector w ubo i by filtrami się aktualizował i działał na Android czy też PC.

**Comment by xxcriticxx** [comment]
na pc dziala bez problemu

**Comment by seba2282** [comment]
Na PC, to ja wiem.

**Comment by xxcriticxx** [comment]
@seba2282 przetestuj please ff android+ubo android + usi android (https://addons.mozilla.org/en-Us/android/addon/userunified-script-injector/?src=cb-dl-toprated)

**Comment by seba2282** [comment]
Chwilowo nie wyskakują te popupy. Odznaczone antiblock killer od reek a aktywny ten protector. Zobaczymy, jak będzie to działać na dłuższą metę. :)

**Comment by xxcriticxx** [comment]
poprosilem adprotectora o anroid ver to trzymaj kciuki maybe cos z tego bendzie

**Comment by seba2282** [comment]
Było trzeba poprosić o implementację tego w ubo i aq. To by po filtrach działało na Android, PC, etc. :)

**Comment by xxcriticxx** [comment]
nieda rady sammym filtrem script jest potrzebny

**Comment by seba2282** [comment]
A Anti Block Killer też jest skryptem i dodali jako osobny filtr. A od kiedy nie aktualizują tego Killera  ?

**Comment by blocker999** [comment]
chyba tylko umatrix, powinien dać rade, choćby tymczasowo, spróbuj

**Comment by seba2282** [comment]
Na razie działa mi ten usi czy jakoś tak :)

**Comment by xxcriticxx** [comment]
@seba2282 od Latest commit a87431f on Nov 21, 2016

**Comment by xxcriticxx** [comment]
@blocker999 umatrix dziala na telefonie?

**Comment by seba2282** [comment]
@xxcriticxx AQ miał ostatnią aktualizację killera od reek 2 grudnia 2016, a UBO niedawno. Więc stąd było pytanie o ostatnią aktualizację killera.

**Comment by xxcriticxx** [comment]
nic nie bylo od zeszlego roku

**Comment by MajkiIT** [comment]
UBlock pobiera co wyznaczony interwał czasu filtry, bez względu czy się coś zmieniło czy nie.

**Comment by seba2282** [comment]
Ja muszę ręcznie aktualizować, bo jakoś automatycznie u mnie nie chce. Tylko aktywne aktualizuj mimo włączonej autoaktualizacji filtrów.

**Comment by xxcriticxx** [comment]
@seba2282 nic nie bylo od 2016

**Comment by seba2282** [comment]
@xxcriticxx Czy dla MS Edge też działa ten adblocker protector script ? Czy orientujesz się o wersji Android ale dla Chrome Mobile ? I AdQuard nie najlepiej radzi sobie z reklamami w moim odczuciu.

**Comment by xxcriticxx** [comment]
@seba2282 nie posiadam windows telfonu nie moge tego sprawdzic. na edge jest juz chyba fork ubo.

https://github.com/nikrolls/uBlock-Edge

**Comment by seba2282** [comment]
Ale nie wiem czy script działa tego protectora.

**Comment by xxcriticxx** [comment]
@seba2282 potestuj to sie dowiemy wszyscy 

https://tampermonkey.net/?browser=edge

**Comment by seba2282** [comment]
Ok. Jak wrócę z W7 do W10. A będę wiedział po wtorku czy całkiem rzucić W7. :)

**Comment by seba2282** [comment]
Na Android powróciły te popupy na miniminiplus.pl mimo skryptu. Albo coś się skopało albo nie wiem co. Chwilowo usunęłem po tym zdarzeniu ubo z tymi skryptami. Bo nie wiem, co jest grane. UBO działa ogólnie coraz gorzej...

**Comment by xxcriticxx** [comment]
@seba2282 mocno skaczesz po systemach ja sie jusz pogubilem

please podaj jakis test link i screenshot

**Comment by seba2282** [comment]
Na Android testowałem to co pisałeś. Usi + ubo + ff + lista + adblock protector script. I zaczęło mi w pewnym momencie wyświetlać te popupy znów. Na PC miałem testować na Edge dopiero, jak wejdę na W10.

**Comment by xxcriticxx** [comment]
@seba2282 skasuj browsing histroy i cookies znowu

**Comment by seba2282** [comment]
@xxcriticxx A orientujesz się, czy te skrypty zostaną zaimplementowane (znaczy zintegrowane) w UBO ?

**Comment by xxcriticxx** [comment]
napweno nie

**Comment by seba2282** [comment]
A przydałaby się taka świeżość we wtyczkach. :)

**Comment by xxcriticxx** [comment]
@seba2282 zamykamy to jak jest potrzeba utworz nowy temat

**Comment by seba2282** [comment]
@xxcriticxx Jasne.
