### ISSUE TITLE
fokus.tv

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2423]
VOD

![fokus tv](https://cloud.githubusercontent.com/assets/23176832/24676272/aa19d956-1982-11e7-90ae-7e4714ea130c.png)

**Comment by xxcriticxx** [comment]
@MajkiIT @F4z zrobicje testa ja jestem geo locked!

**Comment by F4z** [comment]
Powinno wystarczyć:
`@@||fokus.tv/assets/js/ads.js$script,domain=fokus.tv`
