### ISSUE TITLE
domzdrowia.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2425]
Po najechaniu u góry na pasek, ukazuje się obraz z fotkami porównawczymi.

![domzdrowia](https://cloud.githubusercontent.com/assets/23176832/24725384/0a4781a8-1a4f-11e7-9156-69f540d97cfd.jpg)

**Comment by xxcriticxx** [comment]
ten po prawej podobny do @MajkiIT

**Comment by MajkiIT** [comment]
@blocker999 dzięki
