### ISSUE TITLE
forum.android.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2428]
reklama

![forum android com](https://cloud.githubusercontent.com/assets/23176832/24802556/b435fa1e-1ba8-11e7-949b-a6c808351761.jpg)

**Comment by xxcriticxx** [comment]
maybe something like this

`forum.android.com.pl##iframe[src="https://www.ofertaplay.info/lp/lm/androidbaner/index.html"]`
