### ISSUE TITLE
gram.pl regula usuwa wszystkie obrazki w tekstach

### ISSUE THREAD

**Issue by sq5gvm** [MajkiIT/polish-ads-filter#2429]
Regula pochodzaca z #1964 
`gram.pl##FIGURE.obrazek`
Powoduje zablokowanie wyswietlania wszystkich obrazkow w tekstach (artykulach i newsach) na stronie gram.pl a nie tylko reklam...
Przykladowo http://www.gram.pl/artykul/2017/04/07/kodowanie-popkultury-wikingowie-z-kaczogrodu.shtml
z wylaczonym filtrem: http://imgur.com/USmxA6S
z wlaczonym filtrem: http://imgur.com/7Aka6Yn

**Comment by MajkiIT** [comment]
@sq5gvm Dzięki
