### ISSUE TITLE
unblock

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2431]
Dodać (pierwsza reguła tylko dla uBlocka):
`autocentrum.pl,demotywatory.pl,dziennik.pl,facetemjestem.pl,gala.pl,garnek.pl,gry-online.pl,jegostrona.pl,joemonster.org,kobieta.pl,komixxy.pl,v10.pl##script:inject(abort-on-property-write.js, ub_ct_load)`
`autocentrum.pl,demotywatory.pl,dziennik.pl,facetemjestem.pl,gala.pl,garnek.pl,gry-online.pl,jegostrona.pl,joemonster.org,kobieta.pl,komixxy.pl,v10.pl##div:not([class]):not([id]) > iframe[style^="border: none;"]:not([src])`

@MajkiIT ta druga reguła jest jeszcze do przetestowania, bo nie wiem czy gdzieś nie będzie za dużo ukrywać, więc jak będziesz robił aktualizację to na razie jej nie dodawaj, chyba że wcześniej sprawdzisz wszystkie podane wyżej strony, ok?
Ja postaram się przejrzeć te strony do końca tygodnia.

Do usunięcia:
`autocentrum.pl##img[src^="data:image"]`
`joemonster.org##img[src^="data:image"]`
`gry-online.pl##img[src^="data:image"]`
`autocentrum.pl,gry-online.pl,joemonster.org#@#.leadAd`
`@@/wp-content/plugins/banner-manager/*$domain=autocentrum.pl|gry-online.pl|joemonster.org`

**Comment by xxcriticxx** [comment]
@F4z nie lepjej zablokowac ten ||uncos tam?

maybe podac to do adprotectora?

**Comment by xxcriticxx** [comment]
`unblock.onaudience.com`

**Comment by F4z** [comment]
@xxcriticxx on jest zablokowany, taka reguła jest na liście. Tylko to działa w taki sposób, że w Chrome i podobnych to połączenie nie jest filtrowane, bo jest jako "ukryte żądanie", tutaj o tym pisałem - https://github.com/MajkiIT/polish-ads-filter/issues/2392#issuecomment-290805514
Raczej nie ma potrzeby żeby zgłaszać do AdBlockProtectora, bo reguły do uBlocka powinny wystarczyć.

**Comment by xxcriticxx** [comment]
zglosilek do ublock extra?

**Comment by xxcriticxx** [comment]
ja jestem firefox forever!

**Comment by F4z** [comment]
Zgłaszałem tutaj - https://github.com/uBlockOrigin/uAssets/issues/236

**Comment by xxcriticxx** [comment]
ok to super

**Comment by xxcriticxx** [comment]
@F4z tvn nie uzywal tego ostatnio?

**Comment by F4z** [comment]
@xxcriticxx używał, ale w przypadku TVNu to było związane z reklamami przed filmem.

**Comment by xxcriticxx** [comment]
@F4z dzieki za wyjasnienie sprawy

**Comment by F4z** [comment]
Nowa strona  - `http://transfery.info/`

Poprawione reguły:
`autocentrum.pl,demotywatory.pl,dziennik.pl,facetemjestem.pl,gala.pl,garnek.pl,gry-online.pl,jegostrona.pl,joemonster.org,kobieta.pl,komixxy.pl,transfery.info,v10.pl##script:inject(abort-on-property-write.js, ub_ct_load)`

`autocentrum.pl,demotywatory.pl,dziennik.pl,facetemjestem.pl,gala.pl,garnek.pl,gry-online.pl,jegostrona.pl,joemonster.org,kobieta.pl,komixxy.pl,transfery.info,v10.pl##div:not([class]) > iframe[style^="border: none;"]:not([src])`

**Comment by F4z** [comment]
Kolejna strona do dodania - `http://www.prawdaobiektywna.pl/`

**Comment by MajkiIT** [comment]
@F4z Dzięki
