### ISSUE TITLE
dead website 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2432]
`cdax.tv` ok to remove

**Comment by MajkiIT** [comment]
poczekam chwilę może wróci.

**Comment by xxcriticxx** [comment]
sa juz nowe cd-hd czy cos takiego

**Comment by xxcriticxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/15007183/25305244/c477f5be-2745-11e7-941e-68c391af49dd.PNG)

**Comment by MajkiIT** [comment]
Ok. Masz rację czas to usunąć.
