### ISSUE TITLE
memorizer.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2435]
https://www.memorizer.pl/nauka/8738/oskar-i-pani-roza/

![image](https://cloud.githubusercontent.com/assets/15007183/24830295/028c40e4-1c51-11e7-8fee-1ad85bb9df67.png)

**Comment by F4z** [comment]
Jeśli dobrze widzę, to po 30 sekundach pokazuje się ten komunikat, ale nie blokuje żadnych funkcji serwisu, więc najłatwiej będzie go po prostu ukryć.
`memorizer.pl##.adblockInfo`

**Comment by MajkiIT** [comment]
Dzięki
