### ISSUE TITLE
czasdiet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2436]
http://czasdiet.pl/dieta-biblijna-paul-nison/

![capture](https://cloud.githubusercontent.com/assets/15007183/24830281/ab38a01c-1c50-11e7-819a-1ebeb3982c71.PNG)

**Comment by F4z** [comment]
Powinno wystarczyć:
`czasdiet.pl##.contop + [style*="border:2px solid;"], .consid + [style*="border:2px solid;"]`

**Comment by MajkiIT** [comment]
Dzięki
