### ISSUE TITLE
opensubtitles.org/pl/pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#2437]
pojawia sie strona, jak kliknie sie na pole wyszukiwania

**Comment by xxcriticxx** [comment]
masz jakid screenshoot?

**Comment by lukjan32** [comment]
nie zdazam, bo, sie wylacza.

**Comment by xxcriticxx** [comment]
jaki browser? jak blocker?

**Comment by lukjan32** [comment]
opera, ublock

**Comment by xxcriticxx** [comment]
w foxie nic niemam na chromie nic niema

**Comment by lukjan32** [comment]
udalo mi sie zdazyc
![2](https://cloud.githubusercontent.com/assets/17565773/24831795/6c95f886-1ca1-11e7-90c1-76ddfa9d1fc2.jpg)

**Comment by xxcriticxx** [comment]
@F4z spojrzysz please

**Comment by xxcriticxx** [comment]
@lukjan32 acceptable ads masz wylonczone?

**Comment by lukjan32** [comment]
gdzie jest?

**Comment by xxcriticxx** [comment]
ublock extra masz zamontowane?

**Comment by lukjan32** [comment]
nie mam

**Comment by xxcriticxx** [comment]
poczekaj moze lepjej na @F4z

**Comment by lukjan32** [comment]
dobra, i tak ide spac

**Comment by F4z** [comment]
Może coś takiego?
`||opensubtitles.org/*==.js$script`
Tylko nie wiem czy to nie zepsuje jakiejś funkcji na stronie.

**Comment by lukjan32** [comment]
dziala, prosze dodac

**Comment by lukjan32** [comment]
znow sie pojawia.

**Comment by F4z** [comment]
Mógłbyś sprawdzić czy działa?

`||opensubtitles.org/*=.js$script`

**Comment by lukjan32** [comment]
dziala
