### ISSUE TITLE
dropbox.com

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2439]
Zostaje żółty pasek gdzie jest komunikat o cookies
![1](https://cloud.githubusercontent.com/assets/26026382/24839753/b6568534-1d60-11e7-85b8-9a17ab1e5e54.jpg)

**Comment by MajkiIT** [comment]
Dzięki

**Comment by MajkiIT** [comment]
@got3n tam są wyświetlane informacje od Dropbox.
