### ISSUE TITLE
efilmy.online

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2443]
test link:

https://efilmy.online/smerfy-poszukiwacze-zaginionej-wioski/9238/

naciskajac guziki na playerze otwieraja sie inne storny

**Comment by MajkiIT** [comment]
Otwierają się puste okna. Poszukam czegoś typowo do ublocka.

**Comment by xxcriticxx** [comment]
ulubiony filter @F4z 

`efilmy.online##script:inject(noeval.js)`

**Comment by F4z** [comment]
@xxcriticxx tak, to działa, ale wydaje mi się, że w tym przypadku można też użyć tej reguły:
`efilmy.online##script:inject(impspcabe-defuser.js)`

To też może się przydać:
`streamango.com##script:inject(abort-on-property-write.js, BetterJsPop)`

**Comment by MajkiIT** [comment]
@F4z Dzięki wielkie

**Comment by krystian3w** [comment]
`impspcabe-defuser.js` już nie ma i nawet nie zachował się ślad po nim w https://github.com/gorhill/uBlock/wiki/Resources-Library

**Comment by gargul2** [comment]
Admin raczej nie zagląda w zamknięte wątki.
