### ISSUE TITLE
Serialosy.pl

### ISSUE THREAD

**Issue by Krystianh42** [MajkiIT/polish-ads-filter#2446]

**Comment by MajkiIT** [comment]
i co jest tutaj nie tak?

**Comment by xxcriticxx** [comment]
@Krystianh42 ???

**Comment by Krystianh42** [comment]
Już nic poradziłem sobie . Przepraszam za wprowadzenie w błąd


2017-04-13 12:38 GMT+02:00 xxcriticxx <notifications@github.com>:

**Comment by xxcriticxx** [comment]
ok
