### ISSUE TITLE
klikplej.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2447]
`http://www.klikplej.pl/video/weOr6/czy-byles-kiedykolwiek-tak-pijany`

![capture](https://cloud.githubusercontent.com/assets/15007183/25001824/3a00fc50-2015-11e7-9893-53ece81aa5c0.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx u mnie pusto. @F4z zerkniesz u siebie?

**Comment by xxcriticxx** [comment]
@MajkiIT reklama jest po prawaj stronie na zdjeciu i jedna dole. moze masz cos w hoscie to wylapuje to.

**Comment by F4z** [comment]
@MajkiIT ja widzę te reklamy.
Na przykład:
`||ec.bankier.pl/show$script,domain=klikplej.pl`
`||klikplej.pl/a_d/banner.gif`
`klikplej.pl##.a-d-box`
`klikplej.pl##div[style="width:300px;height:42px;background:url(/img/font_reklama.png);"]`

**Comment by MajkiIT** [comment]
@F4z Dzięki
