### ISSUE TITLE
filiser [streamin]

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#2452]
@F4z  da się coś zrobić z pozostałością po popupie - niebieski X na playerze?
![20170414_001](https://cloud.githubusercontent.com/assets/9846948/25042705/6780ca60-211a-11e7-96f0-f99d38b8769c.png)

**Comment by xxcriticxx** [comment]
@FadeMind link do filmu please

**Comment by F4z** [comment]
@FadeMind to powinno wystarczyć:
`streamin.to###rkm`

**Comment by MajkiIT** [comment]
@F4z Dzięki
