### ISSUE TITLE
Outlook.com

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2453]
Ostatnio pojawiło się coś takiego w skrzynce po zalogowaniu... da się coś z tym zrobić?

![11](https://cloud.githubusercontent.com/assets/26026382/25048785/86fa1760-213e-11e7-9752-df5385b07e89.jpg)

**Comment by xxcriticxx** [comment]
@got3n zamontuj sobie adblock protector

**Comment by got3n** [comment]
To działa tylko na ublock'u tak?

**Comment by xxcriticxx** [comment]
@got3n chyba tak ale przetestuj z adblockem to sie dowiemy

**Comment by got3n** [comment]
No niestety nie działa na AdBlock i Adblock Plus.

Temat to zamknięcia.

**Comment by xxcriticxx** [comment]
pora zamontowac ublocko

**Comment by xxcriticxx** [comment]
@got3n potestuj to 

`outlook.live.com###owaadbar`

**Comment by got3n** [comment]
@xxcriticxx Działa, dzięki!

**Comment by xxcriticxx** [comment]
@got3n zuc 5zl na donacije dla @MajkiIT

**Comment by got3n** [comment]
Gdzie jest jakaś stronka z dotacjami?

**Comment by xxcriticxx** [comment]
https://patronite.pl/polskiefiltry
