### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#2454]
Na telefonie, gdy próbuję się dostać do menu (wylogowanie, powiadomienia), to widzę tylko strzałeczkę i prawą krawędź (czasami też wąziutki fragment menu):

![image19](https://cloud.githubusercontent.com/assets/886325/25053466/b5ab5042-2157-11e7-9b7c-56757629842f.png)

Chyba to jest winne `dobreprogramy.pl#@#DIV[style="color: #A9A9A9; text-align:center;font-size:11px;"]` ciężko to zdebugować.

https://www.dobreprogramy.pl/Windows-10-obsluga-kart-w-kazdym-oknie.-Ida-duze-zmiany-w-powloce,News,80522.html

**Comment by F4z** [comment]
@gwarser z tego co widzę to wina tej reguły którą podałeś.
Jeśli się nie mylę to obecną regułę (`dobreprogramy.pl##DIV[style="color: #A9A9A9; text-align:center;font-size:11px;"]`) można by zastąpić taką:
`dobreprogramy.pl##body:not(.variant-mobile) div[style="color: #A9A9A9; text-align:center;font-size:11px;"]`
Wtedy na stronie w wersji na komputery powinno być to ukryte, a w przypadku wersji mobilnej byłby napis reklama.
Teoretycznie da się go "schować" taką regułą:
`dobreprogramy.pl##body.variant-mobile div[style="color: #A9A9A9; text-align:center;font-size:11px;"]:style(visibility: hidden!important;)`
co prawda byłby tylko niewidoczny, ale ten napis chyba dużo miejsca nie zajmuje?
Jeśli masz jakieś lepsze pomysły, to proszę napisz :)

**Comment by xxcriticxx** [comment]
@F4z spac!

**Comment by MajkiIT** [comment]
@F4z @gwarser dzięki za pomoc
