### ISSUE TITLE
strony tv i filmowe 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2459]
strony zostaly pozyczone z innego repo oczywiscie bez pytania :)

@MajkiIT @F4z happy przegladania moze co nowego do regexu wpadnie 

Tv:

https://darmowetv.pl/tele.php
http://www.goldlive.aaf.pl/news.php
http://telewizjastreamer.rf.gd/?i=1
http://tele-wizja.com/
http://weti.rf.gd/617.html
http://weti.rf.gd/
http://weti.rf.gd/1.html
http://inatv.pl/
http://tvlive.cc/pl/index.php?id=telewizja-online
http://tele-miki.cba.pl/
http://tvnalini.wixsite.com/swirownia
http://nowatv.net/
http://telemaniak.org/
http://kabeltv.pl/
http://1sport-tv.blogspot.com/2017/03/sportowe-online.html
http://serwer1738304.home.pl/
https://videostar.pl/
http://www.telewizjada.net/
http://goldvod.tv/
http://wizja.tv/
http://pierwsza.tv/
http://yoy.tv/
https://www.deltamediaplayer.com/pl/

Filmy:

http://alltube.tv/
http://ekino-tv.pl/
http://www.efilmy.tv/
http://kinostar.tv/
https://cdax.tv/
http://www.kinostacja.pl/
http://filiser.pl/
http://filmy.to/
http://ekinomaniak.tv/
http://www.ogladajonline.pl/
http://superfilm.pl/
http://paczamy.pl/
http://www.maxkino.pl/
http://filmik.tv/
http://www.cda.pl/
http://www.kinoiseriale.tv/
http://nasze-kino.online/
http://zalukaj-filmy-cda.pl/
http://superkino.tv/
https://efilmy.online/
http://cda-hd.pl/
http://cda-x.pl/
http://www.ekinko.pl/
http://www.filmy.cba.pl/
http://dobryseans.pl/
http://www.kinoline.pl/
http://szukajka.tv/
http://kokosik1207.pl/

**Comment by xxcriticxx** [comment]
`||ekino-tv.pl/views/img/reklama_btn2.png$image`

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki, przeglądam i patrzę.

**Comment by xxcriticxx** [comment]
ja pomlu juz zaczelem

**Comment by MajkiIT** [comment]
Dodać 
`/^(http|https):\/\/[a-zA-Z.]{10,}\.com\/[a-zA-Z]{1,}\.\js/$script,domain=ekinko.pl`

**Comment by xxcriticxx** [comment]
@F4z cos dla ciebie 15 sec counter przed filmem 

test link:

http://www.filmyiseriale.net/filmonline/19938/beauty-and-the-beast-2017.html

![capture](https://cloud.githubusercontent.com/assets/15007183/25071293/3c5b9bd6-2281-11e7-8b57-3641957d5dce.PNG)

**Comment by xxcriticxx** [comment]
ekinko.pl nasty shit!

**Comment by MajkiIT** [comment]
@xxcriticxx zaktualizowałeś filtry ?

**Comment by xxcriticxx** [comment]
@MajkiIT zrobilem to dawno jak dodales do regexa

**Comment by MajkiIT** [comment]
@xxcriticxx zaktualizujesz teraz i sprawdzisz?

**Comment by MajkiIT** [comment]
@xxcriticxx dopiero zobaczyłem, ze napisałes reguły wyżej. Sprawdzam

**Comment by xxcriticxx** [comment]
@MajkiIT sorry

**Comment by MajkiIT** [comment]
@xxcriticxx niby za co?

**Comment by F4z** [comment]
@xxcriticxx te 20 sekund czekania to raczej tylko przy użyciu skryptu da się pominąć.
Teoretycznie chyba najłatwiej byłoby zmienić `var konik = 20;` na `var konik = 1;` wtedy zamiast 20 sekund czekałoby się jedną.
Takie coś działa w Adguardzie - `filmyiseriale.net#%#AG_onLoad(function() { konik = 1; });` - ale najlepiej będzie jak zapytasz się o to kogoś kto zna się na JavaScript.

**Comment by xxcriticxx** [comment]
czyli ad protectora

**Comment by xxcriticxx** [comment]
@F4z ta funkcja juz zostala dodana do ad protectora

**Comment by adamibeata** [comment]
https://cda-tv.pl
