### ISSUE TITLE
Przysłowiowy jeleń 

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2470]
Hej na początek chciał bym was przeprosić za ten kłopot który sprawiłem z chorym Player.pl i za to jaka ze mnie niezdara :D Ale to o co teraz zapytam myślę ze przyda się nie tylko mnie ale wielu innym 

Czy dali byście rade napisać tutorial co z czym się je itd np UBO z którym ja mam najwiekrzy problem co robią te wszystkie opcje które można po zaznaczać (Może poza filtrami na kraje itd) :D 

albo tak jak wy piszecie w niektórych tematach skryptowo to np gdzie to wkleić jak to aktywować itd wiem dla was to banalne rzeczy ale dla laika który dopiero zaczyna opowiedzenie co jest czym i z czym się je naprawdę wiele daje

**Comment by xxcriticxx** [comment]
@gzenio22 ale to nie czarna magia wszystko wklejasz MY FILTERS pod opcjami na ublock o

**Comment by gzenio22** [comment]
A dlaczego np nie chce mi opera dodac filtra gdy klikam np w odnosnik z tad?

https://www.certyficate.it/pomijanie-wykrywania-adblocka-portalach-wp/

Gdy klikam ok nigdzie mnie nie przenosi a lista moje filtry jest pusta

Dodam ze dla pewnosci wszystko zainstalowalem od zera kazdy dodatek

**Comment by F4z** [comment]
@gzenio22 tak żeby było jasne, klikasz w przycisk "Install" pod napisem "Oraz dodać wymagane filtry:", tak?
Jeśli tak, to ta lista powinna być widoczna w zakładce "Zewnętrzne filtry" na samym dole, w kategorii "Specjalne".

**Comment by gzenio22** [comment]
Jest :)

Kurcze naprawde przepraszam za swoją głupote :(

A mam pytanie kolejne juz dzis XD poradzicie sobie z tym bugiem? 
![screenshot 2017-04-17 22-58-53](https://cloud.githubusercontent.com/assets/21177361/25104654/7750c5cc-23c1-11e7-96a8-0d552d68a761.jpg)

Ten napis wyskakuje przy aktywnym adblock protectorze na FB

**Comment by F4z** [comment]
To raczej nie jest błąd, a jedna z opcji tego skryptu,

Otwórz tę stronę - https://jspenguin2017.github.io/AdBlockProtector/settings.html - i wyłącz opcję "Facebook Mod: Jump To Top"

**Comment by xxcriticxx** [comment]
stalo sie adam do pomocy!

**Comment by gzenio22** [comment]
faktycznie :D znikło w takim razie co mi daje aktywna ta opcja po za tym ze widze ten napis? Niby jest klikalny ale gdy na to klikam nic sie nie dzieje

**Comment by xxcriticxx** [comment]
Whether a "Jump To Top" button should be added to Facebook.

**Comment by xxcriticxx** [comment]
adam powiedzial to bardziej bardziej fachowo

**Comment by gzenio22** [comment]
lol to ja to zostawiam aktywne :D powiedzcie mi jeszcze jedno czy moge jakos wam pomoc testować skrypty itd zauwarzylem ze na WP skrypt do zdejmowania blokady na filmy przestal działać np

**Comment by xxcriticxx** [comment]
@gzenio22 zapraszam na github reguly poda podawe pod adresem strony. wszyscy sie przucilismy na ad protector tam jest wp.pl wbudowane.

**Comment by xxcriticxx** [comment]
@gzenio22 mozesz zrobic donacje jak dasz rade na https://patronite.pl/polskiefiltry

**Comment by gzenio22** [comment]
Ja mowie wlasnie o adprotectorze kiedy wchodze np na jakies wiadomosci na WP gdzie jest jakies video protector probuje zdjac blokade czekam kilka sekund wraca strona dalej zablokowana wiec operacja sie powtarza i ten efekt jest zapentlony

**Comment by xxcriticxx** [comment]
wyczysc historie i cookies podaj test link

**Comment by gzenio22** [comment]
http://tech.wp.pl/nie-tylko-lajka-zwierzeta-tracily-zycie-by-czlowiek-polecial-w-kosmos-6111194585208961a

**Comment by xxcriticxx** [comment]
ad protector w akcji

![capture](https://cloud.githubusercontent.com/assets/15007183/25106021/643fff74-2395-11e7-84b3-ff20fc12f88d.PNG)

**Comment by gzenio22** [comment]
hm pokaz mi no twoje skrypty co masz pozaznaczane a co nie :)

**Comment by gzenio22** [comment]
a i klikales cos tutaj? 
![screenshot 2017-04-17 23-47-32](https://cloud.githubusercontent.com/assets/21177361/25106141/61006302-23c8-11e7-9d30-27963b3cc445.jpg)

**Comment by xxcriticxx** [comment]
always allow domain

**Comment by xxcriticxx** [comment]
@gzenio22 a pokaz to bylo w szkole

**Comment by gzenio22** [comment]
teraz bede juz wiedzial :) dzieki za dzisiaj wszystkim jestescie wielcy

**Comment by xxcriticxx** [comment]
@gzenio22 zapraszamy jutro!

**Comment by gzenio22** [comment]
a jeszcze tak z ciekawosci jak czesto aktualizuje sie skrypt? :) Robi sie to z automatu czy ja musze cos robic?

**Comment by MajkiIT** [comment]
@gzenio22 robi się to automatycznie i częstotliwość jest rożna, w zależności od potrzeby.

**Comment by gzenio22** [comment]
Dziekuje za wszelką pomoc miłego dnia :)
