### ISSUE TITLE
interia.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2471]
Komunikat o cookies

![1](https://cloud.githubusercontent.com/assets/26026382/25127769/6bbd7a90-2437-11e7-82ae-f61ac2349129.png)

**Comment by got3n** [comment]
Hmm dziwna sprawa, odświeżyłem stronę i komunikat zniknął...!?

**Comment by xxcriticxx** [comment]
@got3n sprobuj w private mode ja nic niemam
