### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2472]
Pasek od komunikatu o cookies, dziwna sprawa z tym bo teraz raz mam a raz nie...

![schowek01](https://cloud.githubusercontent.com/assets/26026382/25128452/18109870-243a-11e7-86e9-6f88ad43d1e6.png)

**Comment by xxcriticxx** [comment]
@got3n wyczysc historie i cookies browsera i sprawdz jeszcze raz. 

zobacz czy cookies filtery masz zaznaczone czy odznaczone
