### ISSUE TITLE
kinostar.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2473]
test link:

http:///serial/dawno-dawno-temu-once-upon-a-time/28787/odcinek-15

ruszajac suwakiem w filmie strona miga

**Comment by MajkiIT** [comment]
@xxcriticxx u mnie nie miga. Sprawdzę później na 2 kompie.

**Comment by MajkiIT** [comment]
@xxcriticxx 
to przez to https://www.screencast.com/t/nhF3fGlFSH

**Comment by xxcriticxx** [comment]
@MajkiIT i @F4z 

mozna tutaj uzyc tego co zawsze `kinostar.tv##script:inject(noeval.js)`?

**Comment by F4z** [comment]
@xxcriticxx to raczej nic nie da, bo strona `kinostar.tv` nie ma żadnej funkcji `eval`, a przynajmniej ja takiej nie widzę.
To raczej coś ze strony `streamin.to`, tylko że u mnie nic nie miga.
Możesz sprawdzić coś takiego - `streamin.to##script:inject(noeval-if.js, RTCPeerConnection)`

**Comment by MajkiIT** [comment]
@F4z Już sprawdzam

**Comment by MajkiIT** [comment]
@F4z Na moje oko jest OK. @xxcriticxx sprawdź proszę u siebie.

**Comment by xxcriticxx** [comment]
tez mysle ze jest ok 

@F4z thx
