### ISSUE TITLE
Onet.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2474]
UbO 
Opera
adprotector

Taki efekt 
![screenshot 2017-04-18 17-56-59](https://cloud.githubusercontent.com/assets/21177361/25140440/9c95a326-2460-11e7-962c-e688ff880d56.jpg)

**Comment by F4z** [comment]
@gzenio22 zaktualizuj polską listę, powinno być ok.

**Comment by gzenio22** [comment]
problem w tym ze nie jest ok bo wyskakuje mi ten monit o nieznanym protokole :(

**Comment by MajkiIT** [comment]
@gzenio22 wyczyść ustawienia witryn oraz cache + ciasteczka. Potem sprawdź ponownie.

**Comment by gzenio22** [comment]
Nadal nie znany protokol zaznacze ze wyskakuje to z opery nie z filtrow

**Comment by MajkiIT** [comment]
ale nie klikaj w przycisk, tylko zaktualizuj filtry w Ubo.

**Comment by F4z** [comment]
Ten "nieznany protokół" pojawia się po kliknięciu na przycisk "Ok" na onetowym potworku i dotyczy on dodania listy proponowanej przez onet, żeby wyświetlały się reklamy na stronie. Tylko że uBlock widocznie tego nie obsługuje, więc takie coś się pokazuje.

Mi chodziło o to żebyś wszedł w ustawienia uBlocka, potem w "Zewnętrzne filtry" znalazł polską listę "POL: polskie filtry do Adblocka i uBlocka", następnie kliknął w ikonkę zegarka obok, a na koniec w przycisk "Aktualizuj teraz" na górze.

**Comment by gzenio22** [comment]
chwyclo juhuu :) sorki za to pewnie znowu bylo banalne pytanie

**Comment by gzenio22** [comment]
Przy okazji dacie rade usunac autoplay z onetu tak jak to zrobiliscie np na komputerswiat? :)

**Comment by MajkiIT** [comment]
@gzenio22 takie rzeczy najczęściej da się załatwić skryptem JS, a niestety ciągle borykamy się z problemem posiadania takiej osoby w zespole. Może znasz kogoś takiego?

**Comment by gzenio22** [comment]
niestety nie znam a sam niedawno szukalem kogoś do pythona

**Comment by xxcriticxx** [comment]
@gzenio22 ma pythona w akwarium

btw napisalem do ad protectora o auto play zobaczymy czy da sie cos zrobic.

**Comment by MajkiIT** [comment]
@xxcriticxx dzięki

**Comment by gzenio22** [comment]
Zobaczymy co sie stanie sie :)

**Comment by gzenio22** [comment]
To tez mozna by ubic :) znalazlem to na ang githubie ale na Ubo tez nie ogarnia 

http://www.maxisciences.com/experience/ce-qu-039-il-se-passe-lorsqu-039-il-tire-au-pistolet-sur-un-lac-gele-est-juste-dingue_art38040.html?utm_source=cma&utm_medium=cpc&utm_campaign=cma#

**Comment by F4z** [comment]
Tak na szybko, to ta reguła powinna wystarczyć:
`@@||maxisciences.com/jsad/advertisement.js$xmlhttprequest,domain=maxisciences.com`

Tylko to jest francuska strona, więc to powinno być zgłoszone tutaj - https://forums.lanik.us/viewforum.php?f=91 - i z tego co widzę to już to ktoś zrobił - https://forums.lanik.us/viewtopic.php?f=91&t=36384&p=116635

**Comment by MajkiIT** [comment]
@F4z Dzięki

**Comment by MajkiIT** [comment]
@gzenio22 @F4z @xxcriticxx 
Możecie zerknąć czy macie adblocka na komputerswiat.pl ?

**Comment by xxcriticxx** [comment]
no adblock found

**Comment by F4z** [comment]
@MajkiIT z uBlockiem działa prawidłowo, ale z rozszerzeniem "Adblock" mam komunikat "Reklamy
nie są takie złe..."

**Comment by MajkiIT** [comment]
@F4z czy możesz zerknąć co to powoduje, bo ja mam na obu czysto ?

**Comment by F4z** [comment]
@MajkiIT sprawdzałeś w trybie prywatnym?
U mnie to wina zablokowanego gemiusa.
Po dodaniu tych reguł działa:
`@@||gapl.hit.gemius.pl/gemiuslib.js$script,domain=komputerswiat.pl`
`@@||gapl.hit.gemius.pl/gplayer.js$script,domain=komputerswiat.pl`
`@@||ocdn.eu/static/mastt/xgemius.js$script,domain=komputerswiat.pl`
`@@||onet.hit.gemius.pl/*/rexdot.js$script,domain=komputerswiat.pl`
`@@||onet.hit.gemius.pl/*/redot.js$script,domain=komputerswiat.pl`

Link do testów - `http://www.komputerswiat.pl/nowosci/aplikacje/2017/17/google-chce-stworzyc-w-chrome-wklejanie-bez-kopiowania-tekstu.aspx`

**Comment by xxcriticxx** [comment]
@F4z inne domeny onetu sa ok?

**Comment by F4z** [comment]
Nie patrzyłem jeszcze.

Wcześniej napisałem "Adblock" a chodziło mi o "Adblock Plus".

**Comment by F4z** [comment]
Tutaj w momencie kiedy wideo się próbuje załadować, to ten komunikat też się pojawia (z Adblock Plus, bo z uBlock Origin działa prawidłowo) -`http://wiadomosci.onet.pl/swiat/zrodlo-projekt-wytycznych-ws-negocjacji-brexitowych-uzgodniony/4g94k4y`

**Comment by MajkiIT** [comment]
@F4z Tak, czyściłem cache, tryb prywatny i nic to nie dało.

**Comment by MajkiIT** [comment]
@F4z sprawdzę jeszcze raz na tym video.

**Comment by MajkiIT** [comment]
@F4z Mi się film wogóle nie ładuje, ale to wina blokowania domen na routerze.

**Comment by F4z** [comment]
@MajkiIT a na routerze blokujesz też gemiusa, bo może przez to nie widzisz tego komunikatu?

**Comment by MajkiIT** [comment]
@F4z tak, właśnie widzę, że całą listę tam sobie wrzuciłem. Czyli wybrane wykierowałem za pomocą DNSa w kosmos. Już to wywalam.

**Comment by F4z** [comment]
W zasadzie to nawet chyba nie kwestia wczytania wideo, tylko tego, że po kilku sekundach ładuje się ten skrypt:
`http://onet.hit.gemius.pl/_1493052934814/rexdot.js?l=90&id=bDtFNtRW9Z5iZ1X1PUIOMuUVXrGpNqOz5O5PArPEj1D.97&et=view&hsrc=1&extra=&fr=1&tz=-120&fv=-&href=http%3A%2F%2Fwiadomosci.onet.pl%2Fswiat%2Fzrodlo-projekt-wytycznych-ws-negocjacji-brexitowych-uzgodniony%2F4g94k4y&ref=http%3A%2F%2Fwww.onet.pl%2F&screen=1920x975r1000&col=24&window=1920x845&ltime=10000&lsdata=-TIMEDOUT&fpdata=erlqNBuITombQnXsMX0FAp5dWTdD4xA5VunF1i4BsXD.V7&vis=1`

Jak go odblokuje to wtedy nie mam komunikatu.
`@@||onet.hit.gemius.pl/*/redot.js$script`

**Comment by MajkiIT** [comment]
@F4z dodać tą regułę?
@@||onet.hit.gemius.pl/*/redot.js$script

**Comment by F4z** [comment]
@MajkiIT a u Ciebie cały czas nie ma tego komunikatu?
Jeszcze chwilę popatrzę.

Swoją drogą, to się tam pomyliłem i edytowałem poprzednią swoją wypowiedź, bo zgubiłem "x" w regule.

**Comment by MajkiIT** [comment]
@F4z 
Niestety nie mam. Już poczyściłem co mogłem. Zrestartowałem routery. Nadal mam czysto.

**Comment by xxcriticxx** [comment]
ja blokuje gemiusa hostem i film dziala

```
Apr 24 13:18:04 dnsmasq[14966]: /etc/pihole/gravity.list onet.hit.gemius.pl is 192.168.1.131
Apr 24 13:18:04 dnsmasq[14966]: /etc/pihole/gravity.list onet.hit.gemius.pl is fe80::9e85:682d:25:5dea
```

**Comment by MajkiIT** [comment]
@xxcriticxx ja blokowałem i doubleclick itp. Ok 30 domen.

**Comment by xxcriticxx** [comment]
@MajkiIT z mojej listy host?

**Comment by MajkiIT** [comment]
tak, ale nie tylko.

**Comment by F4z** [comment]
@MajkiIT ok, wolałbym takie wyjątki dawać pod konkretne domeny.

```
@@||gapl.hit.gemius.pl/gemiuslib.js$script,domain=auto-swiat.pl|businessinsider.com.pl|fakt.pl|forbes.pl|komputerswiat.pl|noizz.pl|onet.pl|plejada.pl|vod.pl
@@||gapl.hit.gemius.pl/gplayer.js$script,domain=auto-swiat.pl|businessinsider.com.pl|fakt.pl|forbes.pl|komputerswiat.pl|noizz.pl|onet.pl|plejada.pl|vod.pl
@@||onet.hit.gemius.pl/*/rexdot.js$script,domain=auto-swiat.pl|businessinsider.com.pl|fakt.pl|forbes.pl|komputerswiat.pl|noizz.pl|onet.pl|plejada.pl|vod.pl
@@||onet.hit.gemius.pl/*/redot.js$script,domain=auto-swiat.pl|businessinsider.com.pl|fakt.pl|forbes.pl|komputerswiat.pl|noizz.pl|onet.pl|plejada.pl|vod.pl
```

**Comment by MajkiIT** [comment]
@F4z Oczywiście. Już dodaje. Dziękuję.

**Comment by F4z** [comment]
Ok, dzięki :)

**Comment by MajkiIT** [comment]
@F4z 
Masz może pomysł na ten element po prawej przy przewijaniu na http://forum.pclab.pl/ ?

**Comment by xxcriticxx** [comment]
przegladsportowy.pl nie jest czasem czescia onetu?

**Comment by F4z** [comment]
@MajkiIT dla uBlocka coś takiego:
`forum.pclab.pl###nitro-block:style(position: absolute!important; left: -3000px!important;)`
nie powinno łapać jako ukryty element, więc nie powinno być komunikatu o adblocku.

@xxcriticxx raczej tak, ale tam nie widzę komunikatu o adblocku.

**Comment by F4z** [comment]
@MajkiIT ta reguła nie działa:
`###nitro-block:style(position: absolute!important; left: -3000px!important;)`
a to wynika z tego, że reguły z `:style()` nie działają jako ogólne.

Może po prostu tak?
`auto-swiat.pl,businessinsider.com.pl,komputerswiat.pl,noizz.pl,onet.pl,pclab.pl,plejada.pl,vod.pl###nitro-block:style(position: absolute!important; left: -3000px!important;)`

**Comment by MajkiIT** [comment]
@F4z @gzenio22 @xxcriticxx 
Macie adblocka na onet.pl i komputerswiat.pl ?

@F4z dopiero zobaczyłem. Już poprawiam.

**Comment by MajkiIT** [comment]
Ja nic nie mam, ale może to przez to? `onet.pl##span.newsAdd`

**Comment by F4z** [comment]
@MajkiIT u mnie działa prawidłowo, sprawdzałem z uBlockiem i Adblockiem Plus.

**Comment by MajkiIT** [comment]
@F4z ok dziękuję.
