### ISSUE TITLE
zippyshare.com

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2478]
Hej tym razem reklama ktorej serio UBO nie blokuje nie mam jak tego pokazac screenem ale opisze krok po kroku jak ja wywołać

Wejdz w link np : http://www11.zippyshare.com/v/l3ynnRct/file.html
Kliknij download Co spowoduje prawdopodobnie otwarcie nowej karty z reklama albo na tej samej karcie wbije sie nowa strona z owa reklamą

**Comment by F4z** [comment]
@gzenio22 możesz sprawdzić czy po dodaniu tej reguły jest ok?

`||go.onclasrv.com/apu.php$script,redirect=noopjs,important`

**Comment by gzenio22** [comment]
Dla pewnosci mam to wkleic w moje filtry tak?

**Comment by F4z** [comment]
Tak, w zakładce "Moje filtry".

**Comment by gzenio22** [comment]
Nie działa nadal musze 2 razy klikac w download

**Comment by F4z** [comment]
U mnie działa, ale jeśli u Ciebie nadal to wyskakuje, to sprawdź to:

`zippyshare.com##script:inject(noeval.js)`

**Comment by gzenio22** [comment]
Nie wyskakuje mi juz reklama tylko strona za pierwszym kliknieciem sie przeładowuje a dopiero za drugim kliknieciem zaczyna sie pobierac plik

**Comment by F4z** [comment]
No to wygląda tak jakby te reguły które podałem nie działały u Ciebie, bo strona nie powinna się przeładować.
W zakładce "Zewnętrzne filtry" masz zaznaczone "Moje filtry"?

**Comment by gzenio22** [comment]
Tak

**Comment by gzenio22** [comment]
historie przegladania i cache tez czyscilem

**Comment by gzenio22** [comment]
Panowie reklama juz nie wyskakuje tylko strone mi przeladowuje mysle ze mozna to wstawic do skryptu ogolnego :)

**Comment by F4z** [comment]
"to" czyli to - `||go.onclasrv.com/apu.php$script,redirect=noopjs,important`, tak❔

**Comment by gzenio22** [comment]
Tak

Ale chyba mozna dodac jeden i drogi

**Comment by F4z** [comment]
Dodałem tylko pierwszą, skoro działała, a oprócz tego jest bardziej ogólna i powinna też działać w przypadku innych stron, które korzystają z tego samego skryptu do wyświetlania tych reklam/popupów.
