### ISSUE TITLE
Nie mogę zamontować Adblock Protector dla Edge.

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#2479]
Tak jak w temacie. Mam Edge, UBO, Tampermonkey (pomijam dodane filtry ze strony certificate IT) oraz wyłączony killer reek w UBO. Jak próbuję zamontować script Protector, to strona github autora Protectora zaczyna mielić i na tym się kończy.

**Comment by MajkiIT** [comment]
A jak dodajesz skrypt ze strony https://www.certyficate.it/pomijanie-wykrywania-adblocka-portalach-wp/ ?

**Comment by seba2282** [comment]
Twój link umożliwił mi dodanie na Edge. I teraz działa. A przydałaby się edycja strony działające i na razie do listy dodać miniminiplus.pl A i nie wiem co jest z tym github, ale na komputerze nie mogę pisać, a na telefonie już tak.

**Comment by xxcriticxx** [comment]
@seba2282 zamontowales tampermonkey for edge?

https://tampermonkey.net/?browser=edge#

**Comment by seba2282** [comment]
@xxcriticxx tak. Tylko jakaś awaria strony z Protectorem, to skorzystałem z linku wyżej. I jest ok. Prócz tego, że desktopowa wersja GitHub.com uniemożliwia mi pisanie postów (i to któraś przeglądarka), a na Android w telefonie mogę pisać normalnie.

**Comment by xxcriticxx** [comment]
@seba2282 zobacz co masz pod MY FILTERS napewno cos sobie przez przypadek zablokowales

**Comment by seba2282** [comment]
@xxcriticxx moje filtry brak. Po prostu jakieś nawiedzenia oprogramowań. Ważne, że link od @MajkiIT umożliwił mi zamontowanie do końca Protectora.

**Comment by xxcriticxx** [comment]
@seba2282 ale to nie jest normalne co u ciebie sie dzieje

**Comment by xxcriticxx** [comment]
@seba2282 idz do setting i zrob reset to default settings

**Comment by F4z** [comment]
@seba2282 próbowałeś z wyłączonym uBlockiem?
Tak pytam, bo z tego co pamiętam masz włączone wszystkie albo prawie wszystkie filtry, a to może powodować problemy. W japońskiej liście (`JPN: ABP Japanese filters (日本用フィルタ)`) jest reguła (`-ads-`), która powoduje problem z dodawaniem komentarzy w tym repozytorium.

**Comment by xxcriticxx** [comment]
@F4z czemu japonia nas nie lubiec?

**Comment by F4z** [comment]
Bo w nazwie jest `-ads-` - github.com/MajkiIT/polish **-ads-** filter/

**Comment by xxcriticxx** [comment]
da rade poprawic ten filter dziek naszej liscie czy mam pisac do nich?

**Comment by seba2282** [comment]
A... Wchodzę na telefonie i jakoś github działa. Ale uciążliwe są filtry na mobilnego ubo w ff. Zamiast blokować reklamy na stronach, przepuszczają popupy adoceanu i reszty. Nie będę pisał enty jaka strona, ale nic nie pomaga. A taka ciekawostka. Google planuje wbudować adblockera do chrome. Pytanie czy też będzie tak lipny, jak w operze. xD

**Comment by seba2282** [comment]
A tak swoją drogą sprawdzę wyłączając ubo w edge jutro na github. Ale przy dodawaniu postów dostaję non stop komunikat po angielsku : "nie możesz postować w tym czasie".

**Comment by F4z** [comment]
@xxcriticxx pisać do nich nie ma sensu, bo raczej i tak tego nie poprawią, mają bardzo restrykcyjną politykę - https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy

@seba2282 ja dostaję dokładnie taki sam komunikat, gdy mam włączoną japońską listę.

**Comment by F4z** [comment]
![image](https://cloud.githubusercontent.com/assets/11742596/25253982/988a990c-2623-11e7-9bce-5bfa5038d660.png)

**Comment by xxcriticxx** [comment]
moze @seba2282 jest w .jp

**Comment by seba2282** [comment]
@F4z dokładnie to. @xxcriticxx nie wiem. Wydaje mi się, że ubo ma reguły już wykluczające github, ze względu na to aby pobierał aktualizacje filtrów.

**Comment by xxcriticxx** [comment]
@seba2282 to zrob restore to defaults tak jak pisalem

**Comment by F4z** [comment]
@seba2282 aktualizacje filtrów pobierane są jako "ukryte żądanie", które jest dodane do wyjątków - `behind-the-scene` - przez co nie są filtrowane.
Natomiast dodawanie komentarzy na githubie traktowane jest jako "normalne połączenie" (nie wiem jak to lepiej nazwać) więc reguła z japońskiej listy je blokuje.

**Comment by xxcriticxx** [comment]
panowie have fun its time for some traffic!

**Comment by seba2282** [comment]
@xxcriticxx "panowie have fun its time for some traffic!"

 ??? A może czas dopracować te filtry, aby nie były wykrywane przez strony typu wp, tvn, player, minimini oraz żeby ubo Android normalnie blokował i też nie był wykrywany ? Wtedy obeszłoby się bez Protectorów. A gdzieś pisali, że niebawem powstanie idealny, niewykrywalny adblocker.

**Comment by F4z** [comment]
Myślisz, że nie próbowaliśmy?
Jest wiele tematów poświęconych tym stronom.
https://github.com/MajkiIT/polish-ads-filter/issues?utf8=%E2%9C%93&q=is%3Aissue%20player.pl
https://github.com/MajkiIT/polish-ads-filter/issues?utf8=%E2%9C%93&q=is%3Aissue%20wp.pl

Było też zgłaszane do twórcy uBlocka.
`https://github.com/uBlockOrigin/uAssets/issues/268`
`https://github.com/uBlockOrigin/uAssets/issues/293`

Tylko na razie bez żadnego dobrego rozwiązania, które by działało dłuższy czas, bo twórcy tych stron też co jakiś czas coś zmieniają.
Dlatego w tej chwili jedyne co pozostaje, to korzystać z AdBlockProtectora albo z Adguarda w wersji dla Windowsa, bo on też sobie z tymi stronami radzi, ze względu na to, że ma większe możliwości niż zwykłe rozszerzania.

**Comment by seba2282** [comment]
@F4z A Android ? FF + UBO , ten zestaw zamiast blokować reklamy, przepuszcza je. Gdzie desktopy/laptopy są jasne i w miarę wszystko blokuje, to Android jest gorzej. Kiedyś blokowało, teraz przepuszcza...

**Comment by MajkiIT** [comment]
@seba2282 Daj adres strony gdzie masz takie reklamy. Wezmę z pracy telefon z androidem i sprawdzę.

**Comment by seba2282** [comment]
Zwykła strona miniminiplus.pl/filmy . Z dwa albo trzy filmiki przejdą, a potem się zaczną te popupy. Przynajmniej u mnie się pojawiają przy normalnych ustawieniach bez killera reek i ignorowania filtrów kosmetycznych. Reszta filtrów zaznaczona. I życzę szczęścia po którymś włączeniu kolejnego filmiku. Bo ja takowego nie mam.

**Comment by seba2282** [comment]
@xxcriticxx UBO w FF na Android blokował wszystko do czasu. Chyba od ok miesiąc lub dwa jest te słabe blokowanie, albo twórca ubo dogadał się z Google i innymi i mamy, co mamy.

**Comment by xxcriticxx** [comment]
@seba2282 mysle ze masz cos z ustawieniami pomieszane znowu

**Comment by F4z** [comment]
@seba2282 ja na Androidzie korzystam z Adguarda i Google Chrome. Włączyłem sobie dzisiaj na miniminiplus.pl kilka/kilkanaście odcinków Molanga i Stacyjkowa i żadnych popupów nie miałem, natomiast widziałem komunikat o blokowaniu reklam.
Dodałem tę regułę:
`||adocean.pl/*ad.xml$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/,important`
i komunikat więcej się już nie pojawił.

**Comment by xxcriticxx** [comment]
👍

**Comment by seba2282** [comment]
Piszę wyraźnie, że ff + ubo. Adquard nie blokuje wszystkiego. I ubo przepuszcza mi reklamy w ff na miniminiplus. Adquard z kolei i chrome, fakt blokują filmiki, ale za to jak sito openload.co przekierowuje chrome na słynne zaktualizuj wtyczkę, usuń wirusa czy wygrałeś iphone. Już nie wspomnę o raptu, gdzie ubo blokuje te przekierowania w ff Android. :)

**Comment by MajkiIT** [comment]
@seba2282 jak napisał @xxcriticxx na andoidzie jest ciężko. @F4z dał ci gotowe i sprawdzone rozwiązanie. Testowałem Ubo i FF i mam to samo co ty. Mi kiedyś pomysł podsunął @xxcriticxx aby pobawić się blokowaniem reklam za pomocą OpenDNS. Testowałem to na nowej sieci wifi i ma to jakiś plus, ale zobaczymy jak to będzie na dłużej.

**Comment by F4z** [comment]
Odnośnie raptu i openload, to jest kwestia odpowiednich reguł i ustawień w przypadku Adguarda w wersji dla Androida.
Takie rzeczy najlepiej zgłaszać tutaj - https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by seba2282** [comment]
@MajkiIT A mógłbyś napisać jak to działa ?

**Comment by xxcriticxx** [comment]
@seba2282 to jest tak zwane blokowanie hostem

mozesz sie pobawic pi-hole tylko potrzebujesz do tego linux 

privoxy.org nastepny fajny project 

adaway.org ale root potrzebny 

https://forum.xda-developers.com/showthread.php?t=1916098

tak jak widzisz jest tego pelno. ja by sprawdzil te twoje ustawiena jak kiedys blokowalo to i teraz powino blokowac. i wyloncz te .jp filtry :)

**Comment by seba2282** [comment]
@xxcriticxx jp filtry nie mają nic wspólnego z MiniMini+ :)

**Comment by xxcriticxx** [comment]
@seba2282 ja bym dotej pory strone juz zmienil :)

**Comment by seba2282** [comment]
@xxcriticxx można i tak. Ale to tylko ucieczka przed błędami w ubo. xD

**Comment by xxcriticxx** [comment]
jest platna ver adgarda na android moze tego sprubujesz

**Comment by seba2282** [comment]
@xxcriticxx mam licencję do 2019 w ramach udzielania się z sugestiami dla supportu. I działa tak samo, z tym, że ma antyphishing i ochronę jakąś przed malware. A żeby korzystać z blokowania reklam w apps, musisz mieć root. A u mnie bez bl ani rusz. A szkoda gwarancji.

**Comment by xxcriticxx** [comment]
@seba2282 czyli host file z rootem tobie zostalo
