### ISSUE TITLE
android.com.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2481]
Reklama - `http://android.com.pl/`

![image](https://cloud.githubusercontent.com/assets/11742596/25243993/486d738c-25ff-11e7-95b6-2617165b3bb0.png)

Na przykład:
`android.com.pl##.vertical-banner`
`||android.com.pl/images/user-images/2017/04/Neffos_380x720.jpg`

Myślę, że można też dodać ogólną regułę:
`##a[href^="http://delivery.clickonometrics.pl/campaign="]`

**Comment by gzenio22** [comment]
Dziala banner po prawej znikł

**Comment by MajkiIT** [comment]
@F4z Dzięki

**Comment by gzenio22** [comment]
Nie powiesz mi chyba ze juz to dodales? :D

**Comment by MajkiIT** [comment]
@gzenio22 ja?

**Comment by gzenio22** [comment]
tak

**Comment by MajkiIT** [comment]
zbieram się do dodania, ale jeszcze nie dodałem.

**Comment by gzenio22** [comment]
ok daj cynk jak pojdzie

wgl tak mnie zastanawia to co robicie jest legalne?

**Comment by MajkiIT** [comment]
@gzenio22 ok. A czemu ma być nielegalne?

**Comment by gzenio22** [comment]
nie mowie ze nie jest tylko wiesz jak to w polszy na wszystko znajda paragraf

**Comment by MajkiIT** [comment]
@gzenio22 zmiany naniesione. A co do legalności to nikt na to nie zwraca uwagi. My robimy swoje.
