### ISSUE TITLE
www.polskieradio.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2485]
Czesc. Sprawdz prosze http://www.polskieradio.pl/9/299/Artykul/1752073,Marek-Sawicki-problemem-jest-Antoni-Macierewicz-a-nie-Bartlomiej-Misiewicz wg mnie wycina video na Polskim Radio

@F4z @xxcriticxx @seba2282 

zerkniecie? U mnie jest ok

**Comment by gzenio22** [comment]
Co typ ma na mysli piszac wycina? U mnie jest player z filmem trwajacym ponad 15 minut i sie odtwarza bez problemu

**Comment by F4z** [comment]
@MajkiIT u mnie też jest w porządku.

**Comment by xxcriticxx** [comment]
u mnie smiga

**Comment by MajkiIT** [comment]
@gzenio22 wycina, to jak mniemam chodzi, ze player znika. 
@seba2282 @F4z @xxcriticxx dzięki
