### ISSUE TITLE
Nuteczki.eu

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2486]
Panowie co wy na to zeby delikatnie zablokowac klik w ten maly banner pobierz MP3 na przykladowo tej stronie?

http://nuteczki.eu/muzyka/disco-polo/164721-mariusz-sobczyk-jedyna-w-moich-snach-extended-2017.html

Obecnie klikniecie w ten banerek przekierowuje na strone ktora ubo juz blokuje z jakiegos skryptu ale jednak klikniecie w to dziala a gdyby tak przestalo dzialac i banner byl tylko nie klikalnym obrazkiem?

**Comment by xxcriticxx** [comment]
niewiem czy dobrze rozumiem ale chyba cos takiego 

`||nuteczki.eu/templates/KlubowaMuza/images/pobierz.png$image`

**Comment by gzenio22** [comment]
czesciowo sie zgadza ale te zakladki w playerze dalo by rade zostawic i tylko je aktywowac czy to juz za duze wymagania? :)

**Comment by xxcriticxx** [comment]
@gzenio22 podaj jakis obrazek skresc co jest nie potrzebne

**Comment by gzenio22** [comment]
kurde mala poprawka tamta linijka jest good ale dodatkowo 

http://nuteczki.eu/muzyka/disco-polo/

Tutaj jak klikniesz play na ktoryms playerze bedziesz na nim mial wyszażone przyciski dasz rade zdjąć z nich blokade? czytaj wyszarzenie tak aby byly znowu klikalne i poprawnie przekierowywały?

**Comment by xxcriticxx** [comment]
nie rozumiem ale moze ktos inny pomoze

**Comment by gzenio22** [comment]
chodzi mi o te wyszażale przyciski pod glosnikiem da sie z nich zdjac blokade klikania?

http://screenshot.sh/odWtrLB1i7W8m

**Comment by xxcriticxx** [comment]
nieda rady caly player zniknie 

maybe @F4z cos wymyslis

**Comment by F4z** [comment]
Ten odtwarzacz jest we flashu chyba i jak patrzyłem na to wcześniej to nic ciekawego nie wymyśliłem.
Może potem jeszcze raz spojrzę.

**Comment by gzenio22** [comment]
Reguła jest ok bannerek znika z niczym sie to nie gryzie jest ok :)
