### ISSUE TITLE
www.onet.pl

### ISSUE THREAD

**Issue by BladYPL** [MajkiIT/polish-ads-filter#2487]
I have a problem with obtrusive advertising that detects AdBlock and changes the text of the article to text that should not block ads

http://wiadomosci.onet.pl/kraj/paul-jones-stany-zjednoczone-zrobily-wszystko-co-mogly-ws-katastrofy-smolenskiej/yw3y970

This is the lock screen. Monster holding a cloud with the words 
 "Ads are not so bad..."  " Reklamy nie są takie złe..."  

https://www.dropbox.com/s/pfyi0wjc12m91ld/Zrzut%20ekranu%202017-04-21%2020.40.42.png?dl=0

**Comment by gzenio22** [comment]
Możesz tu pisać po polsku jeśli chcesz chyba ze sie myle i nie jestes Polakiem :)

**Comment by F4z** [comment]
@BladYPL masz zaktualizowaną polską listę?

**Comment by BladYPL** [comment]
Sorki pisałem po angielsku aby więcej osób zrozumiało. Tak mam zaktualizowaną i dalej na podstronach onetu wyskakuje potworek z chmurką :)

**Comment by F4z** [comment]
A to w takim razie mógłbyś napisać z jakiego rozszerzenia do blokowania reklam korzystasz i jakie masz włączone/dodane listy?

**Comment by BladYPL** [comment]
Standardowo mam włączony język Polski i tyle. Dodatkowych filtrów własnych na tej domenie nie robiłem i dodatkowych list filtrów nie mam.  Onet.pl zaproponował mi jakieś ich filtry ale one polegają na tym że wyłączają blokowanie banerów na onet.pl

**Comment by BladYPL** [comment]
ustawienia mam takie :  https://www.dropbox.com/s/dlilm5gnwa6mft7/Zrzut%20ekranu%202017-04-21%2020.59.34.png?dl=0

**Comment by F4z** [comment]
Ok, z Adblockiem jestem w stanie odtworzyć problem, zaraz postaram się coś wymyślić.

**Comment by F4z** [comment]
@BladYPL mógłbyś sprawdzić, czy jak dodasz to - `@@||onet.hit.gemius.pl^$domain=onet.pl` - do własnych filtrów, to będzie prawidłowo działało?

**Comment by BladYPL** [comment]
Tak. Dziękuje teraz jest dobrze. Czy nie warto tego filtra dodać do paczki standardowej ? Onet to dość znana strona a ten baner co chwile utrudnia życie.

**Comment by BladYPL** [comment]
a taka sama chmurka działa tutaj
 https://vod.pl/programy-tv/dom-i-drewno-klej-na-goraco-jako-klej-do-drewna/e5lyvmg 

jak będzie wyglądała regułka blokowania dla tej podstrony ?

**Comment by F4z** [comment]
Tak, warto dodać. Podobna reguła była wcześniej na liście, tylko że ostatnio ją usunęliśmy, bo uznaliśmy, że nie jest potrzebna - https://github.com/MajkiIT/polish-ads-filter/issues/2307#issuecomment-294857788
Jak widać w przypadku Adblocka trzeba odblokować ten skrypt, a ja testowałem w uBlocku, gdzie ta reguła nie jest potrzebna.
Zaraz dodam tę regułę z powrotem, powinno też działać na vod.pl.

**Comment by gzenio22** [comment]
Dodam tu ze pod ubo hmurka nie wyskakuje ale w prawym dolnym rogu  pokazuje sie komunikat o cookis a i niestety autoplay sie wbija

**Comment by F4z** [comment]
@MajkiIT skoro w uBlocku działa bez odblokowywania tych skryptów, to może warto je zablokować w dodatkowej liście, co o tym myślisz?

Na przykład coś takiego:
`||onet.hit.gemius.pl/fpdata.js$script,important`
`||onet.hit.gemius.pl/xgemius.js$script,important`

**Comment by MajkiIT** [comment]
@F4z Dzięki za dodanie reguły. Jeśli nie psuje w uBlocku to masz rację wrzucimy je do filtrów dodatkowych.
