### ISSUE TITLE
Panowie jak dodac wasz filtr do  fraierfoxa? :D

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2489]
Hej sorki ze zakladam znowu nowy temat mam juz na firefoxie ublocka i Greesemonkey (Czy jakos tak) 

I takie pytanie jak dodac tu wasza liste? :D

**Comment by xxcriticxx** [comment]
ublock o ->3-rd party filters -> jezykowe sa na dole

**Comment by gzenio22** [comment]
nie ogarniam wczesniej na operze mialem od kogos z githaba wasz filtr

**Comment by xxcriticxx** [comment]
adblocker protector?

**Comment by gzenio22** [comment]
tak

**Comment by xxcriticxx** [comment]
https://github.com/jspenguin2017/AdBlockProtector

**Comment by gzenio22** [comment]
dzieki :) Jak masz mozliwosc to zamknij :)

**Comment by gzenio22** [comment]
Albo czekaj sluchaj znalazlem cos do bloka 

Mam limitowanego neta a na interii jak jestem na czacie i do kogos sie odzywam zawsze wyskakuje autoplayer z reklamami po prawej na dole 

Przykład : http://screenshot.sh/mLfW2HUqHHnMS

Nie wiem czy dasz rade cos wykminic bo sam w zablokuj element nie widze zadnego odnosnika do tego

**Comment by xxcriticxx** [comment]
uzyj tego najedz na reklame przycisniesz program zrobi tobie filt automatycznie. nie jest to 100% ale czasami dziala

![capture](https://cloud.githubusercontent.com/assets/15007183/25304840/7673b504-273d-11e7-8e50-a679155ca420.PNG)

**Comment by xxcriticxx** [comment]
chyba tego szukales wczesnej https://www.certyficate.it/pomijanie-wykrywania-adblocka-portalach-wp/

**Comment by gzenio22** [comment]
To jest na jedna reklame kolejne juz wyskakuja zobacz prosze czy ty cos wywalczysz :(

**Comment by xxcriticxx** [comment]
tak to powino dzialac

**Comment by gzenio22** [comment]
Ten trik blokuje tylko jedna reklame ale gdy pisze do kogos innego wyskakuje kolejna

**Comment by xxcriticxx** [comment]
skad te reklamy sa? jakis program?

**Comment by gzenio22** [comment]
Nie czateria


wejdz sobie na czat i napisz do kogos na pw to ci sie to wysunie

**Comment by xxcriticxx** [comment]
znalazlem otworze nowy temat

**Comment by gzenio22** [comment]
oki :)
