### ISSUE TITLE
czateria.interia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2490]
@MajkiIT @F4z help!

reklama 25 sec jak nie zamkniesz gra caly czas pokazuje sie tylko na private rozmowach 

![capture](https://cloud.githubusercontent.com/assets/15007183/25305059/8890ceb6-2742-11e7-980e-6363fb52ab1c.PNG)

**Comment by gzenio22** [comment]
a tamci sobie zarabiaja na wyswietleniach co nie?

**Comment by xxcriticxx** [comment]
czateria.interia.pl##.video-player-container

**Comment by gzenio22** [comment]
Dziala :)

hula az milo Musze zapytac jak wy wyszukujecie te węzły?

**Comment by xxcriticxx** [comment]
naciskasz prawa myszka potem inspect/inspect elment i pokazuje sie tobie kod strony

**Comment by gzenio22** [comment]
o tym wiem ale ja sam potrafie zablokowac tylko jedna reklame a tobie sie udalo caly ten smierdzacy player

**Comment by xxcriticxx** [comment]
potestuj na inch stronach a dojdziejsz do wprawy

**Comment by gzenio22** [comment]
Widze ze usuwa reklame i nie widze zeby sie z czymś grysło :)

**Comment by xxcriticxx** [comment]
:+1:

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki

**Comment by gzenio22** [comment]
Coś mi skrypt tej reklamy nie ogarnoł po usunieciu mojego filtru

**Comment by xxcriticxx** [comment]
@MajkiIT @F4z zerkniecje please

**Comment by MajkiIT** [comment]
@xxcriticxx ja tego nie widzę. Sprawdzę na 2 komputerze.

**Comment by xxcriticxx** [comment]
@MajkiIT pokazuje sie tylko jak do kogos napiszesz na private

**Comment by MajkiIT** [comment]
@xxcriticxx nadal to samo. Na obu kompach.

**Comment by xxcriticxx** [comment]
ok zostawie otwarte niech @F4z jeszcze sprawdzi

**Comment by gzenio22** [comment]
Jak by cos u mnie juz dziala blokada na czaterii ze skryptu @xxcriticxx Mozesz potwierdzic ostatecznie?
