### ISSUE TITLE
http://discopolonew.cba.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2494]
Reklama banner u gory strony screen  
![screenshot 2017-04-22 20-17-45](https://cloud.githubusercontent.com/assets/21177361/25306963/d22a353e-2798-11e7-98aa-11cd6c5aa486.jpg)

**Comment by MajkiIT** [comment]
cba.pl##img[src="https://www.cba.pl/cba1.jpg"]
cba.pl##body > div:nth-of-type(1)

**Comment by gzenio22** [comment]
dodasz do filtrow? :)

**Comment by MajkiIT** [comment]
tak, już to robię

**Comment by gzenio22** [comment]
sorki ze ostatnio daje wam roboty

**Comment by F4z** [comment]
@MajkiIT reguła którą dodałeś ukrywa tutaj treść - https://www.cba.pl/pl

**Comment by MajkiIT** [comment]
@F4z Dzieki
