### ISSUE TITLE
Jeja.pl - do przegadania 

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2496]
Co sądzicie ? @xxcriticxx @F4z 

Dzień dobry,

Na Jeja.pl przechodzimy od maja na reklamy Google AdExchange. Obecnie zrobiłem mały test i podczas weekendu włączyłem reklamy AdSense. Niestety jest problem, bo poprzez filtr specjalnie pod jeja.pl nie działają reklamy, które powinny działać poprzez zaznaczenie opcji: "Zezwalaj na nie natrętne reklamy". Czy możemy usunąć w ogóle filtr jejapl#top-wrap z filtrów? Wydaje mi się, że i tak reklamy inne niż nienatrętne będą się blokować po domenie. Skoro AdBlock pozwala na nienatrętne reklamy to mam nadzieję, że Państwo, jako twórcy filtrów nie będą tego blokować.

**Comment by xxcriticxx** [comment]
zdejmij wszystko ja i tak w maja sprawdze co tam sie dzieje

**Comment by F4z** [comment]
Moim zdaniem twórcy strony powinni przeczytać to - https://adblockplus.org/en/acceptable-ads a potem zgłosić to tutaj - https://eyeo.com/acceptable-ads-application.html
Wtedy do tej listy - https://easylist-downloads.adblockplus.org/exceptionrules.txt - powinny zostać dodane odpowiednie wyjątki i użytkownicy korzystający z Adblocka z włączoną funkcją "Zezwalaj na nie natrętne reklamy" będą widzieli reklamy.

**Comment by MajkiIT** [comment]
@F4z Dzięki. Tak przekaże.
