### ISSUE TITLE
http://www.speedtest.net/pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2498]
Panowie nie jestem pewny ale ta notka powinna być widoczna?
![screenshot 2017-04-23 14-59-07](https://cloud.githubusercontent.com/assets/21177361/25313769/a25c78ce-2835-11e7-9e22-a67605cd7ab4.jpg)

**Comment by xxcriticxx** [comment]
cookies?

**Comment by gzenio22** [comment]
na to mi wyglada

**Comment by gzenio22** [comment]
! 23.04.2017, 17:36:24 http://www.speedtest.net/pl
www.speedtest.net##.notification-container > div > .notification

Ta notka u mnie to ubiła
