### ISSUE TITLE
my-mobile.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2499]
Reklama w tle oraz u góry i przy okazji warto usunąć banerek z info o reklamowaniu się na tej stronie.
![my-mobile](https://cloud.githubusercontent.com/assets/23176832/25342587/bd89fe82-290c-11e7-923f-2f7b2a4b169b.jpg)

**Comment by MajkiIT** [comment]
Może coś takiego

`||my-mobile.pl/html/*.jpg$image`
`www.my-mobile.pl##body > center`

**Comment by gzenio22** [comment]
Działa co do info o reklamowaniu to akurat zle nie jest :)

**Comment by xxcriticxx** [comment]
jest wiecej na innych artykulach

test link:

http://www.my-mobile.pl/index.php/2017/04/23/adam-malysz-reklama-play/

![capture](https://cloud.githubusercontent.com/assets/15007183/25346667/36602d1c-28e6-11e7-99df-c0f3130e75b9.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki. Przeoczyłem.

**Comment by xxcriticxx** [comment]
@MajkiIT na main na dole tez jest

**Comment by blocker999** [comment]
Trochę za dużo ucieło tzn na pewno na główne ma być info o rankingu i chyba tyle, ewentualnie jutro coś więcej.
 
![my](https://cloud.githubusercontent.com/assets/23176832/25356501/a492a68a-293a-11e7-98da-d70250a3046f.png)

**Comment by blocker999** [comment]
`my-mobile.pl###main-right > center` usuwa przy okazji ranking więc lepiej ją usunąć.
