### ISSUE TITLE
miniminiplus.pl Zrzuty z logów ubo ff android.

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#2502]
Tak jak w temacie @MajkiIT @F4z @xxcriticxx 
![screenshot_2017-04-24-19-37-10](https://cloud.githubusercontent.com/assets/16944478/25351293/89b835f8-2928-11e7-860f-4238a66de2df.png)
![screenshot_2017-04-24-19-37-52](https://cloud.githubusercontent.com/assets/16944478/25351304/8db16242-2928-11e7-9b48-8b6292e267f3.png)
![screenshot_2017-04-24-19-38-07](https://cloud.githubusercontent.com/assets/16944478/25351308/911337e4-2928-11e7-8e5e-0817d479b7a5.png)

**Comment by xxcriticxx** [comment]
@seba2282 podaj test link na ta barbie

**Comment by seba2282** [comment]
Dowolny film. Możesz stacyjkowo, możesz jeszcze boby budownicze i itp. Nie pamiętam która, jakaś Dreamtopia. Bo jest kilka części. Ale te popupy atakują na wszystkich filmikach. :)

**Comment by seba2282** [comment]
W logu jest kraina długowłosych część 1 czy jakoś  tak. Zobacz screeny. Któraś rubryka. :)

**Comment by xxcriticxx** [comment]
ja nie bede takich horrorow ogladal nie jestem pelnoletny

**Comment by F4z** [comment]
Barbie jest spoko ;)
@seba2282 te popupy to masz na myśli to co na obrazku poniżej?
Czy jakieś reklamy wyskakujące w nowej karcie?
<details><summary>Obrazek</summary>

![m](https://cloud.githubusercontent.com/assets/11742596/25354255/98a8c2da-2932-11e7-857f-a130af1b0638.png)

</details>

**Comment by seba2282** [comment]
Tak. I nieważne jaki filmik. Dałem pierwszy lepszy. To się dotyczy wszystkich filmików na minimini+. Są reklamy, jak ta, lego czy snuzzless (jakoś tak). Te trzy widziałem i cały ekran prawie zasłaniają. I bajek nie idzie na Android oglądać.

**Comment by F4z** [comment]
Ok, to mi wygląda na jakiś problem/błąd uBlocka Origin, tak jakby nie mógł zablokować rzeczy oznaczonych jako `media` w mobilnym Firefoksie, mimo że dziennik zdarzeń pokazuje, że zablokował.

Możesz sobie dodać taką regułę:
`||tvn.adocean.pl/ad.xml$xmlhttprequest,domain=miniminiplus.pl,important`
wtedy nie będzie tego popupa, ale pokaże się komunikat o adblocku, tak jak na komputerze.

**Comment by seba2282** [comment]
A tak w chrome Android bez obsługi Adblockerów na dzień dzisiejszy.
![screenshot_2017-04-24-21-46-23](https://cloud.githubusercontent.com/assets/16944478/25355666/b0c489a8-2937-11e7-8e12-f84e3a55b425.png)

**Comment by seba2282** [comment]
Wyżej przykład, jak chrome widzi. Jak dodam wspomnianą regułę, to wychodzi tak jak Windows bez protector. Dobrze rozumiem ? Gdzie dodać ? Bo próbowałem w regułach, gdzie te scene i nie zapisuje mi.

**Comment by seba2282** [comment]
Ok. Mam jako moje filtry.
![screenshot_2017-04-24-21-54-18](https://cloud.githubusercontent.com/assets/16944478/25355917/a8c3e28e-2938-11e7-846c-ca3e22126ae2.png)

**Comment by F4z** [comment]
Dokładnie tak.
Niestety na razie nic lepszego raczej nie da się zrobić przy użyciu samego uBlocka.

**Comment by seba2282** [comment]
Muszę się spytać, ale czy ten błąd to wina twórcy ubo czy po stronie już osób zajmujących się filtrami ? Ten błąd z zablokowaniem tych śmieci na minimini. I czy zostanie to naprawione ? :)

**Comment by F4z** [comment]
W `EasyList` jest ta reguła `-adserver/` i ona blokuje te reklamy na komputerze, więc wychodzi na to, że to problem z uBlockiem, ewentualnie coś z mobilnym Firefoksem.

**Comment by seba2282** [comment]
Najpierw był problem z ubo, że aby dostać się do panelu ustawień, musiałeś​ na Android wyłączyć, potem włączyć ubo. A następnie dopiero widziałeś panel ustawień i w niego mogłeś wejść. Mógłby ktoś twórcę poprosić o fixa ? Będę wdzięczny. FF, to chyba trochę wątpię, choć Adquard Extension robi chyba tak samo...

**Comment by xxcriticxx** [comment]
nie posiadam android telephone ale mam android tv box z kodi

tak to wyglonda umnie 

<details>
![img_5133](https://cloud.githubusercontent.com/assets/15007183/25363857/e8e34146-292b-11e7-8d63-c8c041b7bf47.JPG)
![img_5134](https://cloud.githubusercontent.com/assets/15007183/25363860/ebc7ee5c-292b-11e7-977f-c8a3d9fc7ccf.JPG)
![img_5135](https://cloud.githubusercontent.com/assets/15007183/25363863/f10b6b0a-292b-11e7-8198-18730a108193.JPG)
![img_5136](https://cloud.githubusercontent.com/assets/15007183/25363866/f591483e-292b-11e7-8274-147af0e318db.JPG)
![img_5137](https://cloud.githubusercontent.com/assets/15007183/25363868/f7e7ca7c-292b-11e7-8878-b86e0ae0a917.JPG)
</details>

**Comment by MajkiIT** [comment]
U mnie na tel z Andoid 5.1 są reklamy. U @xxcriticxx jest 4.2. Na andoidzie 6.x jest bez reklam. @seba2282 ty jakiego masz? 
@xxcriticxx  ilu letni masz ten tv?

**Comment by MajkiIT** [comment]
@seba2282 a masz w ublocku zaznaczone filtry reek i Easylist, ale nie easylist without.... ?

**Comment by seba2282** [comment]
Mam 6.0.1 Android. Mam wszystkie filtry bez reek i bez opcji ignorowania kosmetycznych i reguła, co została podana wcześniej i ubo blockuje teraz jak na PC bez protector.

**Comment by xxcriticxx** [comment]
@MajkiIT to nie tv to tv box minix x8 z androidem 

![minix-x8-h-1](https://cloud.githubusercontent.com/assets/15007183/25381593/60d8c38c-2982-11e7-9077-6db99bf36c30.jpg)

**Comment by seba2282** [comment]
Ten usi nie chciał u mnie działać w FF Android. Nie wiem czemu.

**Comment by xxcriticxx** [comment]
sorry ja niemam innej ver zeby przetestowac 

jest jakis blad w montowaniu? ja motowalem z firefoxa strony z pluginami

**Comment by seba2282** [comment]
Raczej taki, że nie wyświetla się ile rzeczy zablokował i ostatnio reklamy wchodziły, a to nie chroniło. Zobaczymy jak teraz po tej regule w ubo Android.

**Comment by xxcriticxx** [comment]
@seba2282 nacisni na te 3 kropki po prawej stronie

**Comment by MajkiIT** [comment]
@xxcriticxx dzięki

**Comment by seba2282** [comment]
Mając tą regułę jest w końcu blokowane te adocean jak należy. Podmontowałem na chwilę usi z Protectorem i tak jak był, tak jest komunikat o Adblockerze. :) Czyli Android 6.0.1, FF 53 oraz UBO 1.12.x i nic nie daje ochrona UBO.

**Comment by xxcriticxx** [comment]
@seba2282 wyczysc historie i cookies :)

po drugie niewiem wyglonda ze na androidzie 4.2 dziala niewiem czy bendzie dzialac na androdzie 6

**Comment by seba2282** [comment]
Testowałem nie raz te czyszczenie. Te popupy są od około 2 miesięcy. Że ubo tego nie blokuje. USI nie działał u mnie od początku, jak podałeś kiedyś, abym spróbował.

**Comment by xxcriticxx** [comment]
ok sorry wiecej nie moge pomoc

**Comment by seba2282** [comment]
Jak znajdziecie jakiś fix na problemy mobilne, to dajcie znać. :)

**Comment by xxcriticxx** [comment]
ja na mobile uzywam host files

**Comment by seba2282** [comment]
Czyli tak. Zainstalowałem dziś ff beta 54 na Android i mam to samo, czyli wina ubo. Czy mógłby ktoś zgłosić to do twórcy ubo ? Ja próbowałem i u niego w ogóle nie chce mi dodawać zgłoszeń czy komentarzy na GitHub.

**Comment by MajkiIT** [comment]
@seba2282 da się :D https://github.com/gorhill/uBlock/issues

**Comment by seba2282** [comment]
Niestety, co napiszę i spróbuję dodać do zgłoszenia, to mam cały czas ten komunikat.
![screenshot_2017-04-26-09-16-00](https://cloud.githubusercontent.com/assets/16944478/25422431/2a904cca-2a61-11e7-8def-7c075f4251e2.png)

**Comment by MajkiIT** [comment]
@seba2282 dziwne. A  jak wchodzisz w ISSUES to masz ten błąd?

**Comment by seba2282** [comment]
Biorę issues, czytając tego niw widzę. Jak chcę dodać komentarz, bądź napisać nowy issue, to mam wspomniany komunikat.

**Comment by MajkiIT** [comment]
`https://github.com/education/classroom/issues/364`

**Comment by seba2282** [comment]
Tylko, że ja potwierdzenie email miałem, bo musiałem aktywować konto. Więc nie do końca rozumiem. Jak mam akceptować email i itp. Miałem konto zweryfikowane, a nie mogę nic pisać u reek czy też u twórcy ubo. Z tego co widziałem, to na razie tylko u tych dwóch. U reszty mogę, o ile mam wyłączone blokowanie reklam na github.

**Comment by xxcriticxx** [comment]
@seba2282 filtry masz default czy wszystko znowu pozaznaczles?

**Comment by seba2282** [comment]
Piszę wyraźnie, na PC i na FF Android dałem do wyjątków github.com - czyli przepuszcza wszystko na tej domenie. A z Android piszę na github z chrome, bo mi wygodniej, a on na dziś dzień nie ma adblockera. Na ff też spróbowałem napisać to samo. A mam wyjątek github.

**Comment by xxcriticxx** [comment]
a .jp lista wyjatek cczy wylonczona?

**Comment by seba2282** [comment]
Wyłączony. Chrome Android nie ma adblockera i tak samo. Do reszty pisać mogę, ale nie do reek czy tego gorhill czy jak mu tam.

**Comment by seba2282** [comment]
A wyjątki w ubo pomijają wszystkie filtry. Bo ubo wtedy całkiem wyłączone na wykluczonej stronie.

**Comment by xxcriticxx** [comment]
wylacz kompletnie ubo i zobacz co sie dzieje

**Comment by seba2282** [comment]
A jak wyjaśnisz chrome Android bez Adblockerów i to samo ? Na wyłączonym to samo. Czyli punkt wyjścia.

**Comment by xxcriticxx** [comment]
wyloncz tez tampermonkey i scripty wykasuje historie i cookies i potestuje

**Comment by seba2282** [comment]
Zrobione i to samo tylko przy gorhillu i reeku. Do reszty jak mogłem pisać, tak mogę.

**Comment by xxcriticxx** [comment]
zandych innych programow do blokowania nie posiadasz?

**Comment by seba2282** [comment]
Nie posiadam. A powinienem ?

**Comment by xxcriticxx** [comment]
nope tak tylko pytam czyli zostal format androida

**Comment by seba2282** [comment]
Bez kitu. Od razu. Piszę jeszcze raz. Komunikaty te mam tylko przy zgłoszeniach do Gorhill (UBO) i Reek (Anti Adblock Killer). A wszędzie indziej mogę pisać.

**Comment by xxcriticxx** [comment]
co @MajkiIT podal sprawdzales tego emaila?

**Comment by seba2282** [comment]
@MajkiIT podał link. W tym linku ktoś napisał, że ma zweryfikowane konto, jakieś repozytoria i coś jeszcze i ma to samo. Ja nie mam z kolei repozytoriów i mam ten błąd tylko przy tych dwóch użytkownikach.

**Comment by MajkiIT** [comment]
@seba2282 a próbowałeś to zrobić na PC dla testu?

**Comment by seba2282** [comment]
Na PC z Edge wyłączyłem wszystkie rozszerzenia. W IE bez rozszerzeń to samo tylko dla tej dwójki.

**Comment by MajkiIT** [comment]
@seba2282 możesz napisać do Supportu GitHUba?

**Comment by seba2282** [comment]
Nie wiem czy dobrze napisałem. Ale wziełem w Google wpisałem support github, znalazłem coś. I napisałem. Ale czy w dobrym miejscu... To się dowiem.
