### ISSUE TITLE
adguard - forum

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2503]
https://forum.adguard.com/index.php?threads/important-polish-filter-addon-list.21172/

**Comment by F4z** [comment]
Jeśli jest taka potrzeba, to myślę, że można stworzyć też oddzielną listę dla Adguarda.
W zasadzie to część reguł z tej dodatkowej listy dla uBlocka jest w angielskiej liście Adguarda, bo część rzeczy im zgłaszałem. Niektóre reguły są tylko kompatybilne z uBlockiem, ale nie powinno być problemu żeby je tak zmodyfikować aby działały w Adguardzie.

**Comment by MajkiIT** [comment]
@F4z Dzięki. No potrzeba pewnie by się znalazła, ale nie chcę Cie zawalać dodatkowymi listami, bo i tak dużo już robicie. Z tego co widzę to ludzie z PL korzystają z Adguarda.

**Comment by xxcriticxx** [comment]
nie moze byc wszystko na jednej liscie?

**Comment by xxcriticxx** [comment]
@MajkiIT jak zaczynalismy tutaj podalem link tych filtrow do adguarda to by bylo w 2015 pamietasz

**Comment by MajkiIT** [comment]
@xxcriticxx reguły z uBlocka powodowały problem z Adblockiem. Nie wiem jak będzie to z Adguardem. Poszukam tych filtrów.

**Comment by F4z** [comment]
Tak na szybko, bo niestety teraz nie mam czasu.
Te reguły są już przerobione pod Adguarda, może jeszcze kilka dodam, ale to dopiero wieczorem.

```
! http://alltube.tv/
! Ominięcie czekania
alltube.tv###please-wait-container
alltube.tv#$##iframe-container { display: block !important; }
!
! http://chip.pl/
! Usunięcie komunikatu o ciasteczkach i poprawa położenia niebieskiego paska
chip.pl###polityka-cookies
chip.pl###body[class^="template-"] { background-position: 50% top !important; }
!
! http://www.efilmy.tv/
! Ominięcie przycisku "Close Ad and Watch as Free User"
efilmy.tv###step1
efilmy.tv###hideOnClick
efilmy.tv#$##playerVidzer { display: block !important; }
!
! http://gahe.pl/
! Ominięcie czekania
gahe.pl###gameloader
gahe.pl#$##flashgame { visibility: visible; display: block; }
!
! http://www.jeja.pl/
! Ominięcie czekania
jeja.pl##.gameLoading
jeja.pl###adLoading
jeja.pl#$##swf { visibility: visible !important; position: static !important; left: 0px !important; }
jeja.pl#$##game { visibility: visible !important; position: static !important; left: 0px !important; }
!
! http://www.national-geographic.pl/
! Puste miejsce po reklamie
@@||national-geographic.pl/bundles/burdacore/js/adv.js$script
national-geographic.pl#$#.advertising-billboard { height: 0px !important; }
!
! http://www.vidzer.net/
! Ominięcie przycisku "Close Ad and Watch as Free User"
vidzer.net###step1
vidzer.net###hideOnClick
vidzer.net#$##playerVidzer { display: block !important; }
!
! http://zalukaj.com/
! Ominięcie jednosekundowej reklamy
zalukaj.com###freePlayerWatch
zalukaj.com#$##free_player { display: block !important; }
!
! http://www.friv12com.com/
! Ominięcie czekania
friv12com.com###ava-advert_container
friv12com.com#$##ava-game_container { display: inherit !important; }
!
! http://gry-online.poszkole.pl/
! Ominięcie czekania
gry-online.poszkole.pl###mr-tomato
gry-online.poszkole.pl#$##fgame { width: 850px !important; height: 600px !important; }
!
! http://stooq.pl/
! Ukrycie pozostałości po reklamach
stooq.pl,stooq.com##td[align="center"] > [id]:contains(REKLAMA)
stooq.pl,stooq.com##table[border="0"][cellpadding="0"][cellspacing="0"]:not([width])[-ext-has='[id="ads_goog_1"]']
!
! http://www.cda.pl/
! Ominięcie czekania przy ładowaniu gier
cda.pl###aa_ad
cda.pl#$##obiekt { display: block !important; }
cda.pl#$##kolumnaSrodkowa { height: auto !important; }
!
! http://www.komputerswiat.pl
! Adblock
komputerswiat.pl#@#.adsbygoogle
komputerswiat.pl#$#.adsbygoogle { height: 1px !important; }
!
! http://www.bankier.pl/
bankier.pl##.boxContent > ul > li[class^="item-"][-ext-has=".premium-link"]
!
! senda.pl
! Ukrycie pustego miejsca po reklamie
senda.pl#$#.advert_box > div > .tablebg { height: 1px !important; visibility: hidden !important; }
!
! www.ps4forum.pl
www.ps4forum.pl##.googleheader
www.ps4forum.pl#$#.forumsTabLinks.tabLinks { top: 60px !important; }
!
! kurnik.pl
kurnik.pl#$#.adsbygoogle { height: 1px !important; width: 1px !important; }

```

**Comment by F4z** [comment]
Muszę też przejrzeć czy wszystkie te reguły są potrzebne i czy te strony działają jeszcze.

**Comment by xxcriticxx** [comment]
@MajkiIT https://github.com/MajkiIT/polish-ads-filter/issues/303

**Comment by gzenio22** [comment]
Tak z ciekawosci Adguard jest free? :)

**Comment by xxcriticxx** [comment]
jest i free version jest i pay version

**Comment by gzenio22** [comment]
Ta free jest w pełni darmowa czy na określony czas? :) Chciał bym wam pomagać na tyle ile mogę testować wasze reguły Nie jestem w stanie wpłacić nic na patronite ale uwielbiam pomagać coś testować bawić się to mi sprawia przyjemność :)

**Comment by MajkiIT** [comment]
@F4z dzięki. Spokojnie. Bez pośpiechu

**Comment by xxcriticxx** [comment]
tak ver free jest 100% free bez okreslonego czasu 

@gzenio22 podawaj strony z reklamami

**Comment by gzenio22** [comment]
@xxcriticxx a podał bys adres? :)

**Comment by xxcriticxx** [comment]
na adguard?

https://adguard.com/en/welcome.html

**Comment by gzenio22** [comment]
Tam przy download adguard pisze ze free jest tylko 14 dni :(

**Comment by MajkiIT** [comment]
@F4z dodam plik do repo.

**Comment by MajkiIT** [comment]
@F4z https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_adguard.txt

**Comment by MajkiIT** [comment]
@F4z do usunięcia
vidzer.net - strona już nie działa

**Comment by MajkiIT** [comment]
@gzenio22 na rok na tel to 10 zł ==> https://adguard.com/en/license.html#new 

Chłopaki tą $ przeznaczają na rozwój.

**Comment by F4z** [comment]
@MajkiIT ok, dzięki.
To z komputerswiat, to było do tego żeby pozbyć się pustej przestrzeni po reklamie, ale teraz już tego nie widzę.

@gzenio22 do przeglądarki jest rozszerzenie - https://adguard.com/en/adguard-adblock-browser-extension/overview.html
Są też wersje na Windowsa i na Maca , które są płatne, ale mają więcej możliwości niż rozszerzenie.
Jeśli się nie mylę to na Androida można korzystać za darmo, ale wtedy filtrowane są tylko przeglądarki, a w wersji płatnej wszystkie aplikacje.
Na iOS podobnie jak na Androidzie z tym, że wersja na iOS jest bardziej ograniczona.

**Comment by gzenio22** [comment]
Panowie zostanę przy tym co mam czyli przy was i postaram się wam pomagać :)

**Comment by xxcriticxx** [comment]
@gzenio22 unas duze bezrobocie i niema co robic

**Comment by MajkiIT** [comment]
@xxcriticxx :D jesteś szczery

**Comment by xxcriticxx** [comment]
@gzenio22 bendziesz podawal strony bendzie gralo nawet dostaniesz zlota gwiazdke od @MajkiIT

**Comment by MajkiIT** [comment]
@xxcriticxx i nie tylko :D

**Comment by seba2282** [comment]
Czy nadal rozważacie dodawanie dodatkowych filtrów dla AdQuard Android ? Dalibyście radę, aby blokował te przekierowania z openload i raptu np do stron typu usuń wirusa, aktualizacja wtyczek, wygrałeś iphone i innych ?

**Comment by xxcriticxx** [comment]
@seba2282 od tego sa filtry KAD https://github.com/azet12/KAD

```
/assets/js/license.$domain=oload.tv|openload.co
/assets/js/script.$domain=oload.tv|openload.co
@@|https://easylist.club/*.js|$script,domain=oload.tv|openload.co
@@|https://easylist.club/*.js|$script,domain=oload.tv|openload.co
||raptu.com^$popup,~third-party
```

**Comment by seba2282** [comment]
Niby na chwilę się uspokoiło, jak włączyłem filtrowanie https Android. A na Edge zobaczę, czy ubo zamienić na AQ :)

**Comment by F4z** [comment]
Sprawdziłem przed chwilą i nie mam żadnych popupów z raptu i openload z Adguardem w wersji na Androida. Natomiast mam popupy z rapidvideo i zaraz to im zgłoszę.

@seba2282 jeśli widzisz gdzieś niezablokowane reklamy/popupy z Adguardem, to zgłaszaj im na forum albo na githubie. Ewentualnie pisz tutaj, a ja w wolnej chwili im to zgłoszę jeśli będę mógł odtworzyć problem u siebie.

**Comment by seba2282** [comment]
Masz aktywne filtrowanie https ? Daj link do filmiku raptu. :)

**Comment by seba2282** [comment]
Sorry z rapidvideo.

**Comment by xxcriticxx** [comment]
@seba2282 masz jakies strony z polskim filami + reklama open new issue please

**Comment by F4z** [comment]
`https://www.rapidvideo.com/embed/FEXYFN0CJO`

Reguła do Adguarda, która zablokuje te popupy:
`rapidvideo.com#%#(function(){var b=window.setTimeout;window.setTimeout=function(a,c){if(!/RTCPeerConnection[\s\S]*?new MouseEvent\("click"/.test(a.toString()))return b(a,c)};})();`

**Comment by F4z** [comment]
Tak, mam aktywne filtrowanie https i metodę filtrowania ustawioną na "wysokiej jakości".

**Comment by seba2282** [comment]
Mam aktywne filtruj dns i https i odpaliłem filmik. Włączyło się jakieś nowe okno z ip i po chwili się zamknęło. A filmik działa Chrome Android.

**Comment by F4z** [comment]
Tak, ale mi chodzi o to żeby to w ogóle nie wyskakiwało :)

**Comment by seba2282** [comment]
Zaraz testuję. To do filtrów użytkownika ?

**Comment by F4z** [comment]
Tak.

**Comment by seba2282** [comment]
Niby działa. Ja bym zgłosił dodanie protectora do aq :) A na PC jako extension też juz aq porządnie blokuje te reklamy, czy nadal słabo ?

**Comment by F4z** [comment]
Nie korzystam z Adguarda jako rozszerzenia, więc nie odpowiem.
Odnośnie AdBlockProtectora, to oni wiedzą o tym, ostatnio dodali listę do programu, a skrypt można zawsze dodać sobie samemu (mam na myśli komputery).
Podobno mają też stworzyć jakiś własny skrypt/rozszerzenie/listę na "anty-adblocki", ale kiedy to będzie, to na razie nie wiadomo - `https://github.com/AdguardTeam/AdguardForWindows/issues/1609`

**Comment by seba2282** [comment]
Mógłbyś podać regułę dla AQ Android, aby odblokować cdnplayer.pl , ale żeby ukryć AQ przed adocean, jak to właściwie działa Protector ? Zauważyłem, że takie coś skrypt robi, że ukrywa się przed tym adocean, jednocześnie go blokując.

**Comment by F4z** [comment]
Masz na myśli player.pl, tak?
Z tego co wiem, to AdBlockProtector podmienia odtwarzacz wideo i pobiera do niego odpowiedni film.

U mnie jest jakiś problem z player.pl na Androidzie, bez żadnego blokowania reklam mogę odtworzyć tylko zwiastun, pełny film u mnie nie działa.
Z Adguardem mam komunikat o Adblocku i prawdopodobnie dlatego, że ta reguła - `||adocean.pl/*ad.xml$empty,domain=player.pl,important` - jakoś inaczej działa na Androidzie niż na Windowsie.
Żeby się tego komunikatu pozbyć musiałbyś wyłączyć angielską listę i dodać tę regułę:
`||adocean.pl/*ad.xml$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/,domain=player.pl,important`
Wtedy u mnie film rusza, ale tylko na jedną sekundę, potem się nic nie dzieje, czyli w zasadzie tak samo jak i bez Adguarda.

Jak Ci bardzo na tym zależy to im to po prostu zgłoś, bo mi ciężko w takim przypadku pomóc.
