### ISSUE TITLE
tvlive.cc/pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2504]
Przy pierwszym wejściu na stronę przyciemnia stronę i na samym środku wyskakuje ich profil FB wydaje mi się ze jest to nie potrzebne skoro maja FB na belce u góry strony :)

**Comment by F4z** [comment]
Na przykład:
`||webfrik.pl/script/popup-fb$script,third-party`

**Comment by gzenio22** [comment]
Działa mozna dodac :)
