### ISSUE TITLE
naekranie.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2505]
Reklamy - `https://naekranie.pl/`
![image](https://cloud.githubusercontent.com/assets/11742596/25400888/43b0ea4c-29f4-11e7-9cda-37650d39fa01.png)

Na przykład:
`naekranie.pl##a[href="http://onskr.in/yokai"]`
`naekranie.pl###adocean-screening-layer > .inner-wrap`
`||naekranie.pl/wp-content/themes/naekranie/resources/img/yokai.png`

**Comment by MajkiIT** [comment]
@F4z Dzięki. Zaraz dodam.
