### ISSUE TITLE
tractors.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2508]
reklama Ubi ius

test link:

http://tractors.pl/traktory-walcza-na-polu-i-daja-rade-a-na-poczatek-tulipany-dla-pan.html

![capture](https://cloud.githubusercontent.com/assets/15007183/25408016/8a244b00-29da-11e7-9055-26d4fb64626a.PNG)

**Comment by MajkiIT** [comment]
`||tractors.pl/banner*.png$image`
