### ISSUE TITLE
Filmy.to (Flashx.tv)

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2509]
screen: https://scr.hu/ONrkVD

**Comment by xxcriticxx** [comment]
@gzenio22 wyczysc histore i cookies dodaj adguard english filters https://filters.adtidy.org/extension/chromium/filters/2.txt + adblock protector i bendzie dzialac

**Comment by gzenio22** [comment]
@xxcriticxx Ten link co poslales wyswietla mi tylko tekst

**Comment by xxcriticxx** [comment]
to sa filtry dodaj je sobie na dole w 3rd party filters w costume

a tutaj jest post z adblocker protectora https://github.com/jspenguin2017/AdBlockProtector/issues/130

**Comment by gzenio22** [comment]
nie umiem ich dodac :(

**Comment by gzenio22** [comment]
dobra mam ale ja glupi :D

**Comment by xxcriticxx** [comment]
gratuluje sukcesu
