### ISSUE TITLE
dziennikzachodni.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#2511]
Reklama na topie

![bez tytulu](https://cloud.githubusercontent.com/assets/26026382/25446732/c43adbb4-2ab2-11e7-8715-7149592cdb49.png)

**Comment by xxcriticxx** [comment]
`||d-pt.ppstatic.pl/k/r/1/56/a3/58fb15273284c.jpg`

**Comment by got3n** [comment]
@xxcriticxx działa!

**Comment by MajkiIT** [comment]
lub tak` dziennikzachodni.pl##figure`

**Comment by got3n** [comment]
@MajkiIT twoja reguła chyba lepsza, możesz dodawać... ;)

**Comment by xxcriticxx** [comment]
@MajkiIT moze ten caly ppstatic zablokowac?

**Comment by xxcriticxx** [comment]
wchodzac na strone masz Forbidden You don't have permission to access / on this server.

**Comment by F4z** [comment]
@xxcriticxx jak zablokujesz całe `ppstatic.pl` to strona będzie się nieprawidłowo wyświetlać, zresztą nie tylko ta.

**Comment by xxcriticxx** [comment]
@F4z ok zrobilem sobie test i masz racje thx

**Comment by MajkiIT** [comment]
@xxcriticxx Gdzieś właśnie popełniłem ten błąd i był problem.

**Comment by gzenio22** [comment]
regułka ładnie śmiga :)
