### ISSUE TITLE
Pikio.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2512]
Cos mi blokuje widget FB ale strona sie wyszarza 

https://scr.hu/lBeLm8

**Comment by xxcriticxx** [comment]
@gzenio22 screenshoty podawaj direct w tej boxie co piszesz

**Comment by gzenio22** [comment]
![shu_lbelm8](https://cloud.githubusercontent.com/assets/21177361/25454612/6062fd68-2acd-11e7-9aef-b56bd760692c.png)

**Comment by MajkiIT** [comment]
do social
`pikio.pl###ffbp-bg`
