### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by halwiefal** [MajkiIT/polish-ads-filter#2516]
Sytuacja jak w https://github.com/MajkiIT/polish-ads-filter/issues/2302 - nie wiem jak otworzyć tamto zgłoszenie, więc utworzyłem nowe.

> http://shinden.pl/external-video/3049-luckystar/view/29646

**Comment by F4z** [comment]
Ja już otworzyłem, ale jak jest nowe, to tamto zamknę, a to zostawię.
Zaraz postaram się coś wymyślić.

**Comment by halwiefal** [comment]
Super, dzięki.

**Comment by halwiefal** [comment]
Działa ok po dodaniu 

> @@||reklama.shinden.eu/adpeeps.php$script,domain=shinden.pl
z zalinkowanego zgłoszenia

**Comment by F4z** [comment]
Ok, dzięki, ale chciałem odblokować możliwe jak najmniej i żeby działało też w Adguardzie.
Możesz sprawdzić, czy to też działa?

`@@||reklama.shinden.eu/adpeeps.php?*showad&*bzone=video$domain=shinden.pl`

**Comment by halwiefal** [comment]
Wygląda na to, że działa.

**Comment by F4z** [comment]
Ok, dzięki.
Zaraz dodam.
