### ISSUE TITLE
Nowy temat - pytanie.

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#2523]
Czy już wiadomo, czy Reek Killer powróci ? Bo męczące jest oddzielne dogrywanie tego protectora, co i tak w 100 % nie gwarantuje, że będzie ok. No i kiedy powróci ten dobry UBO na FF Android, co blokował wszystkie reklamy, jak np. na miniminiplus ?

**Comment by xxcriticxx** [comment]
@seba2282 reeka filtry sa dead adprotecotr jest forkem czyli kopia i kontynuacja reeka repo 

jak cos nie dziala to pisz na https://github.com/jspenguin2017/AdBlockProtector/issues

**Comment by seba2282** [comment]
A drugie pytanie. UBO blokował dwa miesiące temu wszystkie reklamy, a teraz blokuje jak chce.

**Comment by xxcriticxx** [comment]
umnie lapie wszystko nawet na miniminiplus :)

cos nie zlapie na polskich stronach utworz nowy temat unas

**Comment by gwarser** [comment]
>No i kiedy powróci ten dobry UBO na FF Android, co blokował wszystkie reklamy

Domyślnie na Androidzie jest zaznaczone by ignorował ogólne filtry kosmetyczne - może w tym problem?

**Comment by seba2282** [comment]
Wyłączam ten domyślny haczyk. I nie zaznaczam Reek. Reszta on. xD
