### ISSUE TITLE
flarrow.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2528]
![shu_rzplrv](https://cloud.githubusercontent.com/assets/21177361/25564840/f0dcda58-2dbb-11e7-9d39-b871e8c3b38b.png)
FB button na starcie strony

**Comment by MajkiIT** [comment]
@blocker999 dodasz?

**Comment by MajkiIT** [comment]
`flarrow.pl###ffbp`
`flarrow.pl###ffbp-bg`
