### ISSUE TITLE
dorzeczy.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#2529]
Boxy po reklamach
![image-20170430-001](https://cloud.githubusercontent.com/assets/9846948/25564866/804fa8a0-2dbc-11e7-95d4-c9f061fd9dda.png)
![image-20170430-002](https://cloud.githubusercontent.com/assets/9846948/25564871/9e032fc0-2dbc-11e7-975c-bb416d461c84.png)

**Comment by MajkiIT** [comment]
`dorzeczy.pl##.page-rectangle-inner`

**Comment by MajkiIT** [comment]
@FadeMind Dzięki
