### ISSUE TITLE
takmam.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2533]
Button FB na starcie strony

![shu_bngwv4](https://cloud.githubusercontent.com/assets/21177361/25565635/fed40f50-2dca-11e7-8fb2-62894ae5b49e.png)

**Comment by MajkiIT** [comment]
`###cboxOverlay`
`###colorbox`

**Comment by Isamaul** [comment]
@MajkiIT Jeżeli to możliwe, to proszę dodaj tą regułę tylko na ten serwis - bardzo wiele stron opiera np. galerie o skrypt colorboxa, spowoduje to pewien problem, ponieważ nie będą się one wyświetlać :)

**Comment by MajkiIT** [comment]
@Isamaul ok. Mówisz i masz. Poprawiłem.

**Comment by Isamaul** [comment]
Dzięki!
