### ISSUE TITLE
Pytania nadal bez odpowiedzi.

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#2542]
Tak jak w temacie. Z racji tego, że nikt chyba nie żyje w dziale teamu Adquard, to spytam się wam tutaj, bo może macie jakieś odpowiedzi.

Co dalej z AQ ? Kiedy dadzą własnego anti adblock i wywalą tego nieaktualizowanego Reek (to samo przydałoby się dla ubo) ?
Czy dodadzą tą regułę dla rapidvideo, co podał jeden z Was ?
Czy odblokują filmiki np na minimini+, aby działały, jak ubo + protector (zablokowane śmieci, a działający filmik z bajką) ? 

Na razie tylko tyle.

**Comment by xxcriticxx** [comment]
dla adguard zawsze troche zajmuje zeby odpowiedziec. ubo ostatni wymienial filtry reeka na adprotectora czyali adguard nie dlugo napewno tez. dla rapidvideo masz MY FILTERS sobie sam dolacz. o minimini to adguard tobie odpowie.

**Comment by seba2282** [comment]
Czyli ubo dziala na Android już jak należy dla minimini+ , czy nadal kwiatki ? Reklamy niezablokowane i te popupy ? Na pc dla edge nie widzę jeszcze protector w ubo i na razie mam ze skryptem.

**Comment by xxcriticxx** [comment]
umnie na android 4 cos tam dziala robilismy testy przeciesz. na edge jest fork ubo podawalem tobie linka

**Comment by seba2282** [comment]
Na Edge mam ubo 1.12.1 ze store, tampermonkey i protector z skryptem. O jakim forku mowa ? Jak piszesz, że testy... To widzę, że nic się nie zmieniło od teraz już ttzech miesięcy...

**Comment by xxcriticxx** [comment]
@seba2282 trzeba cierpliwie czekać

**Comment by seba2282** [comment]
@xxcriticxx Oby się ruszyło z ubo na Android, po tych wprowadzeniach protectora do filtrów. 😊

**Comment by xxcriticxx** [comment]
@seba2282 paciorek zmowisz bedzie gitara

**Comment by seba2282** [comment]
@@xxcriticxx Zaśpiewam Hallelluyah ze Shreka i powinno być git... Ale jak będzie jakieś info, to proszę o informacje. :)

**Comment by F4z** [comment]
Jesteś niecierpliwy 😛

> Co dalej z AQ ? Kiedy dadzą własnego anti adblock i wywalą tego nieaktualizowanego Reek (to samo przydałoby się dla ubo) ?

Wydaje mi się, że dostałeś tutaj odpowiedź - `https://github.com/AdguardTeam/AdguardForWindows/issues/1609`
a w ogóle to skąd my mamy to wiedzieć?

> Czy dodadzą tą regułę dla rapidvideo, co podał jeden z Was ?

Na 99% dodadzą.

> Czy odblokują filmiki np na minimini+, aby działały, jak ubo + protector (zablokowane śmieci, a działający filmik z bajką) ?

Jeśli chodzi o minimini to jak dodasz tę regułę, to będą filmy działały bez reklam:
`||adocean.pl/*ad.xml$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/,important`

Widzę, że im to zgłosiłeś tutaj - `https://github.com/AdguardTeam/AdguardForAndroid/issues/1199`
i fajnie. Warto też dodać konkretny link przy takim zgłoszeniu, bo i tak pewnie się o niego zapytają.
A ogólnie "problemy" ze stronami najlepiej zgłaszać tutaj - https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by seba2282** [comment]
@F4z u mnie twoja reguła do AQ nic nie daje - komunikat o wykrywaniu adblockera

**Comment by F4z** [comment]
@seba2282 na stronie miniminiplus.pl i w Adguardzie na Androida?

**Comment by seba2282** [comment]
Co do reszty, to konkretny odpowiedzi nie ma zbytnio. xD

**Comment by seba2282** [comment]
@F4z tak. Ta reguła na adocean nic nie daje. I tak zablokowane. Android i AQ.

**Comment by F4z** [comment]
U mnie to działa, przed chwilą sprawdzałem.
Jakie masz włączone listy w Adguardzie?

**Comment by seba2282** [comment]
Tak jak w ubo, wszystko bez reek. A w AQ dodatkowo bez użytecznych reklam.

**Comment by F4z** [comment]
Jeśli masz włączoną opcję "filtruj zapytania DNS" to nie będzie działało.

**Comment by seba2282** [comment]
Tak myślałem, czyli jest wada, bo dns wywala śmieci typu masz wirusy, uaktualnij Android/wtyczkę, wygrałeś iphone.

**Comment by F4z** [comment]
Jak kiedyś sprawdzałem, to nie wszystkie tego typu rzeczy byłe "wywalane" z włączoną tą opcją.
W przypadku kiedy wyskakuje taka reklama z jakiejś strony najlepiej dodać odpowiednią regułę do tego.

**Comment by seba2282** [comment]
W takim razie co daje ten filtr dns ?

**Comment by xxcriticxx** [comment]
@seba2282 blokuje tobie wszystko zanim strona sie pokaze

**Comment by F4z** [comment]
Tutaj jest trochę na ten temat - https://forum.adguard.com/index.php?threads/what-exactly-is-filter-dns-requests.8367/

**Comment by seba2282** [comment]
Ok. Dzięki. :)

**Comment by seba2282** [comment]
To są jaja na Androidzie z MiniMini+ 

![screenshot_2017-05-02-15-55-07](https://cloud.githubusercontent.com/assets/16944478/25620944/45d7bd94-2f50-11e7-83b7-404a7fb7c5b7.png)
![screenshot_2017-05-02-15-54-38](https://cloud.githubusercontent.com/assets/16944478/25620961/4dca3fe0-2f50-11e7-8e2c-39602ab47a63.png)

**Comment by xxcriticxx** [comment]
dziala? unbelievable!

**Comment by seba2282** [comment]
Czy dobrze się przyjrzałeś ? Zaznaczone protector, a mimo to wielkie popup tradycyjnie na Android. Zauważyłem, że w logach ubo tvn.adocean i hit gemiu tvn są na żółto. Nie powinny być na fioletowo, jeżeli niby mają być blokowane ?

**Comment by seba2282** [comment]
A protector w końcu zintegrowany z ubo. I chwała

**Comment by xxcriticxx** [comment]
@seba2282 spelnily sie wszystkie twoje marzenia !

**Comment by seba2282** [comment]
@xxcriticxx W Edge działa już bez skrypt i bez tampermonkey. Na Android nadal jest tak samo, jak bez aktywnego protector - przepuszcza popupy np na minimini. I to jakoś filtrami możecie już ruszyć. 😊

**Comment by F4z** [comment]
To reguła z tego tematu (https://github.com/MajkiIT/polish-ads-filter/issues/2502) nie działa?
`||tvn.adocean.pl/*ad.xml$xmlhttprequest,domain=miniminiplus.pl,important`

**Comment by seba2282** [comment]
Próbowałem dodać ją w moje filtry i reguły w ubo ff Android i zero reakcji. Mało tego, gdzie masz te scene w regułach, po zapisaniu tej reguły adocean i tak są tylko te scene, a nowych reguł nie zapamiętuje. A w moich filtrach nie działa.

**Comment by F4z** [comment]
Wcześniej pisałeś, że działało - https://github.com/MajkiIT/polish-ads-filter/issues/2502#issuecomment-296804316

**Comment by seba2282** [comment]
W AQ bez DNS. A w ubo nie.

**Comment by seba2282** [comment]
Ma ktoś chrome 58 na Android już ? Sprawdzicie bez AQ i innych tak normalnie, klikając na różne filmiki na miniminiplus.pl , czy nie włączy się wam kilkusekundowa reklama w którymś rzędu playerze ? Bo mam wrażenie, że Google rozwiązał problem.

**Comment by seba2282** [comment]
Może ta reguła została zablokowana ze starszego postu, która tu została przytoczona. Może ktoś u siebie sprawdzić w ubo ff Android :
||tvn.adocean.pl/ad.xml$xmlhttprequest,domain=miniminiplus.pl,important

U mnie na razie nie działa i są te popupy. A w Chrome jednak się pojawia jako krótki filmik w playerze, rzadko, ale są.

**Comment by seba2282** [comment]
Na FF Android 54 beta nie widzę tych popupów na razie przy normalnym użytkowaniu bez reguł i z aktywnym protector list. Czyli muszę poczekać za finalnym FF 54 😊

**Comment by seba2282** [comment]
Panowie... Jakimś cudem ominęli zintegrowanego protectora w ubo Edge Windows i materiały znowu nieosiągalne. Ten protector, to chyba faza alfa albo beta w ubo.

**Comment by seba2282** [comment]
Chyba rozwiązałem problem z miniminiplus.pl W MS Edge zamiast UBO użyłem Adquard Extension i zaznaczyłem wszystkie filtry oprócz reek i zezwalaj na nienatrętne reklamy (dodatkowo dodałem githun.com do białej listy). To samo na Android z tymże Firefox, a Chrome wyłączyłem. 😊

**Comment by seba2282** [comment]
player.pl też mi działa. master chef odpaliłem :)
