### ISSUE TITLE
pinka.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2553]
Link przykład ; http://pinka.pl/pin/289141/Sarah-J-Maas-Imperium-burz-ebook

FB button albo i cala ta strona smierdzi?

**Comment by blocker999** [comment]
Poprawi sie

**Comment by MajkiIT** [comment]
`pinka.pl###cboxOverlay`
`pinka.pl###colorbox`

@gzenio22 zerkniesz?

**Comment by gzenio22** [comment]
Good :)
