### ISSUE TITLE
google.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2554]
Nie wiem czy mozna to na dole usunac czy lepiej zostawic Pokazuje na prywatnym bo nie chce mi sie stale ciastek czyscic

![shu_gn0kmz](https://cloud.githubusercontent.com/assets/21177361/25591215/f90b2fc4-2eb3-11e7-866c-6a182734290b.png)

**Comment by MajkiIT** [comment]
@gzenio22 jutro ogarnę

**Comment by gzenio22** [comment]
Spoko tylko nie wiem czy powinniscie to likwidowac bo to jakis tam regulamin nie?

**Comment by MajkiIT** [comment]
@gzenio22 Kiedyś blokowaliśmy.
