### ISSUE TITLE
kodi.org.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2556]
zajefajny FB button na stronie glownej zjedz lekko na dol to ci wyskoczy na kilka sec i zfreezuje strone

![shu_xny1yg](https://cloud.githubusercontent.com/assets/21177361/25593548/5c4daffe-2ebd-11e7-9785-9158663823b4.png)

**Comment by xxcriticxx** [comment]
@gzenio22 jaki filtry proponujesz?

**Comment by gzenio22** [comment]
kurde odziwo juz mi nie wyskakuje nie mam jak go sprobowac zablokowac

**Comment by xxcriticxx** [comment]
umnie ten fb nie wyskakuje

**Comment by xxcriticxx** [comment]
maybe cos takiego na te wszystkie puste boxy po reklamach 

`kodi.org.pl##.Fixed.box`
`kodi.org.pl###gkMainbodyTop`
`kodi.org.pl###gkMainbodyBottom`

**Comment by gzenio22** [comment]
Wszystko good tylko taki maly krzaczek sie zrobil 
![shu_rnj3zn](https://cloud.githubusercontent.com/assets/21177361/25606880/12c98de2-2f14-11e7-887e-38d602829def.png)

**Comment by MajkiIT** [comment]
@gzenio22 to powód braku obrazka https://kodi.tv/wp-content/uploads/Kodi_Xmas-600x336.jpg
