### ISSUE TITLE
fantube.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2558]
FB button na starcie strony

**Comment by xxcriticxx** [comment]
@gzenio22 ty chyba fb bardzo nie lubisz

**Comment by gzenio22** [comment]
nie lubie jak mi shit wyskakuje banner z boku jest ok ale wyciemnienie strony i jebitne polub nas juz jest natrenctwem

**Comment by MajkiIT** [comment]
@gzenio22 sprawdzisz ?

`fantube.pl##.fb_iframe_widget`
`fantube.pl##.in.fade.modal-backdrop`

**Comment by gzenio22** [comment]
działa :) brawo
