### ISSUE TITLE
Z ciekawosci (Pytanie)

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2563]
Hej :) normalnie blokujecie reklamy wiadomo ale przyszla mi do glowy glupia mysl a raczej glupie pytanie mianowicie 

Czy wy skryptem albo raczej regułami jestescie w stanie np nadac konto premium np w jakims serwisie VOD albo grze typu plemiona? Wiem glupie ale mnie to ciekawi na ile wam pozwala znajomosc skryptow na danej stronie np hociażby na stronie plemiona.pl

**Comment by MajkiIT** [comment]
@gzenio22 
Regułami tego nie zrobisz. Dane o koncie premium są przechowywane w bazie danych. Jeśli znasz dobrze jak pisać skrypty i znasz strukturę bazy danych to możesz przeprowadzić atak SQL Injection na aplikację o ile jest ona podatna na taki atak. Dodatkowo jest to karalne. Lepiej znaleźć podatność, opisać ją i wysłać do tej firmy a w zamian poprosić o dożywotnie konto premium.

**Comment by gzenio22** [comment]
zeby nie bylo pytalem tylko z ciekawosci interesuje mnie to na ile wam pozwala skrypt ktorym sie bawicie tzn blokowanie reklam to wiadomo ale ciekawi mnie czy na cos wiecej tez pozwala? :)

**Comment by MajkiIT** [comment]
@gzenio22 spokojnie. Akurat w IT ciekawość jest wskazana, bo dzięki temu się rozwijasz.

**Comment by gzenio22** [comment]
Mnie obecnie ogranicza mobilny internet chce sie troche nauczyc tego z kanalem pasja informatyki :D ale 156 GB miesiecznego limitu mi w tym nie pomaga yebany plus
