### ISSUE TITLE
pl.ign.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2564]
maybe?

http://pl.ign.com/project-scorpio/11016/news/project-scorpio-wideo-z-dev-kitem-nowej-platformy

![capture](https://cloud.githubusercontent.com/assets/15007183/25723332/9b04fc46-30e5-11e7-9d05-8d92f8e422b8.PNG)

**Comment by MajkiIT** [comment]
to link do tej samej strony.

**Comment by gwarser** [comment]
Zgłoszenie na wykopie, że ta strona strasznie muli z uBlockiem http://pl.ign.com/destiny-2-1/13464/news/w-destiny-2-gra-juz-ponad-milion-graczy
