### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2571]
Bardzo Was proszę abyście sprawdzili na stronie olx.pl ( w jakim kolwiek ogłoszeniu, bez logowania ) czy po kliknięciu w nr. telefonu ( pokaż  ) Macie Captcha bo ja mam od niedawna a chciałbym go automatycznie wyłączyć a nie bawić się w obrazki..

Robiłem format systemu i dalej bez zmian, więc proszę Was o sprawdzenie bo niemam gdzie to sprawdzić czy to umnie z lapkiem coś nie tak czy to mądre pomysły olx-a.

![olx](https://cloud.githubusercontent.com/assets/23176832/25746426/aff22ebc-31a3-11e7-91ae-351c831f32a6.jpg)

**Comment by gzenio22** [comment]
u mnie 15 prob kapeć nie wyskoczył

**Comment by blocker999** [comment]
@gzenio22 ale bez zalogowanego konta?

**Comment by gzenio22** [comment]
@blocker999 Oczywiscie nawet sie tam nie rejestrowalem

**Comment by F4z** [comment]
@blocker999 u mnie się pojawia Captcha.

**Comment by blocker999** [comment]
@gzenio22  ok, dzięki.

@F4z  No właśnie ja też tak mam tzn cześciej są te captchy ale czasami odrazu się pojawia nr. telefonu więc niewiem co robić, może macie jakiś patent na ich ominięcie?.

**Comment by Isamaul** [comment]
Olx tylko podpięło captchę w celu odrzucenia robotów. Pewnie masz zablokowane usługi google (analytics i inne), które nie oznaczyły Cię jako człowieka - wtedy problemu nie ma i od razu Cie przepuszcza. 
Blokowanie ich skryptów, czy 3rd party cookie zawsze będzie skutkować wyświetleniem tej captchy - to samo w trybie inprivate.
