### ISSUE TITLE
Pornhub.com 

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2572]
Nie zebym byl jakims fanem pornoli ale od tak se wbilem i mnie przywitala taka przestrzen a nawet wpieniajaca reklama screena dam staralem sie zlapac moment jak naj mniej ten tego no 

![shu_5o2pee](https://cloud.githubusercontent.com/assets/21177361/25751764/5c48aa8a-31b6-11e7-983d-0908bb97db59.png)

**Comment by xxcriticxx** [comment]
@gzenio22 wszystkie porno strony prosze zaznaczac NSFW

NSFW. Not Safe For Work. Usually seen in the Subject line of an e-mail message, "NSFW" indicates that the contents of the message are sexual, or rude, or something that is not suitable to be seen at the workplace.
