### ISSUE TITLE
Twój filtr blokuje mi forko

### ISSUE THREAD

**Issue by smutnyadmin** [MajkiIT/polish-ads-filter#2575]
http://mortis.cba.pl/index.php Pokazuje się tylko tło. Mimo tego adblock nie informuje mnie co właściwie wywala (albo jestem informatycznym ziemniakiem). Jeszcze trochę i skończę w szpitalu z podciętymi żyłami

**Comment by Isamaul** [comment]
```cba.pl##body > div:nth-of-type(1)```

ta reguła ukrywa pierwszego diva na stronie - w twoim przypadku ukrywa całą stronę. 
Możesz to sobie na szybko poprawić dając w <body> jakiś jeden pusty div.

@MajkiIT ta reguła jest zbyt szeroka i psuje :)

**Comment by xxcriticxx** [comment]
@Isamaul troche tobie zajelo sie pokazac z nowu!

**Comment by smutnyadmin** [comment]
Działa. Dzięki wielkie
