### ISSUE TITLE
Prośba o sprawdzenie reguł dla blokerów. miniminiplus.pl

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#2588]
Tak jak w temacie. Dla AQ z filtrowaniem HTTPS i DNS te dwie : 
![screenshot_2017-05-07-22-24-37](https://cloud.githubusercontent.com/assets/16944478/25784863/a5bc8ff0-3374-11e7-951e-12323a9a5db1.png)

Ewentualnie jeszcze dodatkowo  ||redcdn.pl 
A dla ubo wszystkie z zrzutu + dodatkowa.

**Comment by seba2282** [comment]
![screenshot_2017-05-07-22-36-37](https://cloud.githubusercontent.com/assets/16944478/25784930/ad28e47c-3375-11e7-83f5-e915ce56c742.png)

Albo tak wszystkie trzy.

**Comment by seba2282** [comment]
Testuję te trzy reguły w UBO Origin w FF Android i odpukać, na razie brak śmieci w postaci popupów na minimini+.

**Comment by seba2282** [comment]
@MajkiIT @F4z @xxcriticxx Czy u Was też nie wyskakują reklamy czy też nie są blokowane filmiki na miniminiplus.pl, po dodaniu tych trzech reguł co napisałem ? Zarówno na Windows, jak i Android. 😊

**Comment by F4z** [comment]
@seba2282 u mnie w tej chwili na Windowsie z uBlockiem Origin działają filmy na minimini bez dodawania żadnych reguł. Tak jak już pisałem wcześniej, to jest kwestia tego, czy reklama "chce" się załadować, czy nie.

**Comment by F4z** [comment]
Tak samo na na Androidzie, Firefox + uBO ustawienia domyślne z polską listą. Filmy działają, nie ma reklam, bez dodawania nowych reguł.

**Comment by MajkiIT** [comment]
@seba2282 tak jak mówi @F4z normalne reguły i wszystko się działa. Przeklinałem 10 filmów i żadnej reklamy. Wieczorem poproszę swojego testera aby sprawdził. :D.

**Comment by seba2282** [comment]
Mi chyba po 15 filmie na 16 załączył się ten redcdn.pl i wyświetlał reklamy. A na Android to nagminnie, to dodałem​ te reguły i już nic nie mam. :)

**Comment by xxcriticxx** [comment]
mozna zamknac?

**Comment by seba2282** [comment]
@xxcriticxx Tym razem ja zamknę. :D 
@MajkiIT Nie wiem na jakiej zasadzie to działa, ale z wbudowanym protectorem zdażył się nieosiągalny film, ze skryptem przez Tampermonkey jest ok. Bez skryptów i z tymi regułami co podałem, też ok. Ale czekam na twoje informacje od testera.

**Comment by MajkiIT** [comment]
@seba2282 ten tester to moja siostrzenica. Ma 8 lat i daje jej telefon i ogląda bajki. Ma liczyć ile razy widziała reklamy :D/ Taka nauka matematyki :)

**Comment by seba2282** [comment]
@MajkiIT Teraz sobie żartujesz. xD

**Comment by MajkiIT** [comment]
@seba2282 no nie mówię serio. a co?

**Comment by seba2282** [comment]
@MajkiIT to fajnie mieć pomocnika, co pomaga ci wyłapać śmieci na stronach. Teraz testuję bez tych reguł w ubo. Ale przy filtrowaniu dns w AQ niestety są te reguły potrzebne :) Domontowałem jeszcze filtry z certificate.it i widzę, że popupy jakby sobie odpuściły. Ale trzeba potestować.

**Comment by MajkiIT** [comment]
@seba2282 Ona nie zdaje sobie z tego sprawy co się tak naprawdę dzieje. Dla niej to zabawa. Po 3h bajek pojawiły się reklamy tylko wtedy gdy się chciały pojawić. Czyli nadal to samo co u F4z.

**Comment by seba2282** [comment]
@MajkiIT domniemam, że dodane są już do filtrów reguły : 
||gemius.pl 
@@||tvn.adocean.pl
@@||cdntvn.pl

Dodaj regułę ||redcdn.pl
I niech się pobawi. :)

**Comment by seba2282** [comment]
Niestety nic nie działa. Próbuję zablokować śmieciowe popup z użyciem informacji z dziennika żądań w ubo.

**Comment by seba2282** [comment]
@F4z @MajkiIT @xxcriticxx ten popup, to gemius.pl/gstream.js Normalnie reguły blokują jako http, to te diabelstwo ucieka na https. W dzienniku żądań ubo wszystko jest. Czy można prosić o dobre reguły do user filters na te dodatki http/https ?

**Comment by xxcriticxx** [comment]
`||gemius.pl` to powino blokowac wszystko http i https

**Comment by seba2282** [comment]
@xxcriticxx jakoby pisałem, wcześniej pisałem. Na tej regule http blokowało, a https wyskakiwało i na odwrót. W dzienniku żądań ubo wszystko widać. Zrobiłem wczoraj test, zezwoliłem na adocean i cdn oraz zostawiałem minimini+  (bez tego red), a resztę zablokowałem z poziomu listy domen i tak zostawiłem. I działało z tymi fioletowymi kratkami prawie przy wszystkim. Na domyślnych, to podłączał się gemius oraz jakiś google analistics. Można to prześwietlić w dzienniku żądań.

**Comment by F4z** [comment]
W tym przypadku to nie jest kwestia tego, czy to jest `http` czy `https`, a tego, że na liście `EasyPrivacy` jest wyjątek `@@||gemius.pl/gstream.js` i dlatego to nie jest blokowane.
Możesz sobie dodać regułę - `||gemius.pl/gstream.js$script,domain=miniminiplus.pl,important` - ale to i tak nie zablokuje tych reklam.

**Comment by MajkiIT** [comment]
@seba2282 ale jest tak jak pisał @F4z 
https://www.screencast.com/t/nHp193KNnBEx

**Comment by F4z** [comment]
@seba2282 sprawdzałem to i podałem Ci regułę, która zablokuje ten skrypt gemiusa.

**Comment by seba2282** [comment]
Mam teraz w ubo ff Android coś takiego : ||gemius.pl
||gemius.pl/gstream.js$script,domain=miniminiplus.pl,important
||redcdn.pl
||adocean.pl
@@||cdntvn.pl

Niby coś blokuje, ale pop jakim czasie ich skrypt to minie...

**Comment by F4z** [comment]
W zasadzie to nie wiem co chcesz osiągnąć blokowaniem gemiusa, w tym przypadku to nie przez ten skrypt wyświetlane są reklamy. Tutaj pisałem dlaczego tak się dzieje - `https://github.com/MajkiIT/polish-ads-filter/issues/2502#issuecomment-296820909` - i od tamtej pory nic się nie zmieniło.
Możesz dodać coś takiego - `||adocean.pl^$domain=miniminiplus.pl,important` ale wtedy będziesz miał komunikat o adblocku.

**Comment by seba2282** [comment]
Bo zauważyłem coś dziwnego. Jak włączają się te reklamy, to jak w to klikniesz, to gemius przekierowuje tu i tu... Takie żądanie nie raz u mnie wykonywała ta reklama. Może przypadek, ale wątpię. To dowodzi tego, że ciężko wytępić reklamy na html 5.

**Comment by seba2282** [comment]
@MajkiIT mógłbyś sprawdzić u siebie dwie reguły dla miniminiplus.pl czy po nich nie masz reklam już ?
@@||tvn.adocean.pl
@@||s1-player5.cdntvn.js

Mam jeszcze ||gemius.pl/gstream.js , ale nie wiem czy to ma jakiś wpływ.

**Comment by seba2282** [comment]
Jeszcze testuję to : ||r.dcs.redcdn.pl
Choć nie wiem co to za domena. Prawdopodobnie
 r.dcs.redcdn.pl serwuje te popupy typu lego, nuzzles, smerfy, etc.

**Comment by xxcriticxx** [comment]
to jest domain tvn player ja bym tego nie blokowal tam sa filmy/seriale

**Comment by seba2282** [comment]
Tylko, że ten player, jak zauważyłem w raporcie filtrowania ubo, to przemyca ads.mp4, natomiast główny player mieści się pomiędzy adocean, a cdn s1-player5.cdntvn.pl Zazwyczaj jest pokazywany w raporcie jako ten do filmów zamieszczonych na minimini. A redcdn to dystrybucja reklam (tam było ad server coś skrypt).

**Comment by xxcriticxx** [comment]
zablokuj ja bendzie za duzo blokowac to od blokujesz

**Comment by seba2282** [comment]
Zablokowałem też ||gemius.pl/gstream.js i jak wchodzę na tą stronę, to zamiast komunikat ubo, mam 404 not found na stronie gemiusa. Co świadczy, że ubo ignoruje user filters dla gemius Android.

**Comment by seba2282** [comment]
Tak jak myślałem, ||s1-player5.cdntvn.pl wyłącza playera.

**Comment by xxcriticxx** [comment]
nie mozesz wykorzystac mx playera albo kodi?

**Comment by seba2282** [comment]
A już nie blokują kodi i jego wtyczek ?

**Comment by xxcriticxx** [comment]
niewiem ale sa wtyczki na bakji

**Comment by seba2282** [comment]
Powiem tak, ogólnie kanał minimini mam, ale chodzi o te krótko metrażowe filmiki, co na kanale nie ma, a są na stronie. A tak na marginesie, player.pl odblokowaliście już po filtrach, co potrzebne, a reklamy wywalone ? Jeżeli nie, to polecam się przyjrzeć głównemu playerowi, co siedzi na s256-player5.cdntvn.pl , a reszta to śmieci. Tak jak minimini ma s1, ten s256. :) Może da radę zgłosić do protectora część. Ale na FF podobno zbugowany jest ten webextension czy jakoś tak i ubo dziala, jakby nie chciał. Twórca protector gdzieś się wypowiadał u siebie na github parę dni temu. Ale nie pamiętam numeru issue.

**Comment by xxcriticxx** [comment]
@seba2282 napisz u niego na githubie

**Comment by seba2282** [comment]
@xxcriticxx wychodzi na to, że protector preferuje chrome/chromium. Trzeba chyba czekać za Adquard protectorem.

**Comment by F4z** [comment]
@seba2282 możesz zrobić mały eksperyment i spróbować zablokować filmy na minimini całkowicie.
Na przykład dodaj sobie taką regułę:
`||miniminiplus.pl/video/*.mp4$domain=miniminiplus.pl`

Na komputerze z Chrome i uBO po dodaniu tej reguły blokowane są filmy i wygląda to tak jak na obrazku ponizej, czyli film się nie wyświetla.
<details><summary>Obrazek 1</summary>

![image](https://cloud.githubusercontent.com/assets/11742596/26172371/7a7c5a24-3b48-11e7-9c0d-cf25589a6edd.png)
</details>

<br>

Natomiast na Androidzie z Firefoxem i uBO, tak.
<details><summary>Obrazek 2</summary>

![mmp](https://cloud.githubusercontent.com/assets/11742596/26173381/e6129bc4-3b4b-11e7-9e36-c6f3706ac9d8.png)
</details>

<br>

Jak widzisz u mnie wyświetla się to tak samo jak ten "popup" z reklamą, a film powinien być zablokowany (dziennik zdarzeń uBlocka pokazuje, że go zablokował), więc wnioskuję przez to, że coś nieprawidłowo działa i po prostu nie da się w mobilnym Firefoksie przy użyciu uBo* zablokować czegoś co jest w formacie `mp4`/oznaczone jako `media`.
Może dałoby się jakoś to zmienić w Firefoxie w `about:config`, ale trzeba by było poszukać czegoś na ten temat.

*nie sprawdzałem innych Adblocków, więc może to nie kwestia uBO a samego Firefoksa

**Comment by seba2282** [comment]
Dobre spostrzeżenie, ale testowałem AQ jak extension dla FF mobile i robi to samo. A jako Android apk filtrowanie dns + https i dodanie user filter : @@||tvn.adocean.pl i @@||cdntvn.pl i w Chrome jakby te reklamy kilkusekundowe się uspokoiły. Z kolei player.pl - odtwarzacze wykrywają adblockera z przyjemnym komunikatem nam znanym.

**Comment by seba2282** [comment]
Sprawdziłem jeszcze ff Android + Adneuseam. Niby fork ubo 1.9.7.4 a radzi sobie lepiej niż AQ i ubo w nowszych wersjach. Wniosek dla mnie, Google dało w łapę AQ i UBO. I na Android jako extensions przepuszczają śmieci.
