### ISSUE TITLE
www.appki.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#259]
ad block 

Wykryliśmy AdBlocka. Proszę, przeczytaj wiadomość.

Wykryliśmy, że korzystasz z AdBlocka lub innego oprogramowania blokującego reklamy.

Zapewniamy, że nie mamy na naszej stronie inwazyjnych reklam z dźwiękami lub chowającymi się krzyżykami do zamknięcia baneru.

Dlatego też prosimy o wyłączenie AdBlocka, ponieważ w ten sposób zarabiamy na dalszy rozwój strony.

Prosimy, dodaj www.appki.com.pl do białej listy i przestań blokować reklamy. Dziękujemy! :)

**Comment by MajkiIT** [comment]
https://github.com/reek/anti-adblock-killer/issues/901
