### ISSUE TITLE
eurogamer.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2590]
reklama PRAY

![capture](https://cloud.githubusercontent.com/assets/15007183/25800433/5eec392a-33b7-11e7-8394-c9dc70275568.PNG)

**Comment by F4z** [comment]
`@@||cdn.gamer-network.net/2017/scripts/ads.js`

**Comment by xxcriticxx** [comment]
👍 💯
