### ISSUE TITLE
mobila.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2595]
![capture](https://cloud.githubusercontent.com/assets/15007183/25801439/989c2118-33bb-11e7-8750-ed54dadd494d.PNG)

**Comment by MajkiIT** [comment]
||mobila.pl^
Filtr znajduje się na liście: KAD - Przekręty

**Comment by gzenio22** [comment]
Potwierdzam jak chce tam wejść UBO mi z automatu to zdejmuje i wyskakuje komunikat z KAD

**Comment by xxcriticxx** [comment]
moze KAD mam wylonczonego
