### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#26]
jak sie sprawdza czy niema doubles i dead links?

**Comment by MajkiIT** [comment]
dead links to ręcznie...
redundant np ==> https://arestwo.org/famlam/redundantRuleChecker.html

**Comment by xxcriticxx** [comment]
a doubles?

**Comment by MajkiIT** [comment]
ten sam adres (https://arestwo.org/famlam/redundantRuleChecker.html) wykrywa takie same reguły.
