### ISSUE TITLE
swiat-gier.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2600]
Tło, button i część górnego panelu

![swiat-gier](https://cloud.githubusercontent.com/assets/23176832/25902916/3479e256-359b-11e7-813c-dd28fef0128f.jpg)

**Comment by MajkiIT** [comment]
||swiat-gier.com/themes/swiat-gier/img/background$image
swiat-gier.com###paczkomaty_icon
