### ISSUE TITLE
grymel.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2601]
Tło oraz jak by podciągnąć strone do góry było by ok.

**Comment by MajkiIT** [comment]
`||www.grymel.pl/image/subpages/*bg*.jpg$image`

@F4z pomożesz jakoś podciągnąć elementy do góry?

**Comment by F4z** [comment]
Tak będzie w porządku?
`www.grymel.pl###layout:style(margin-top: 5px !important;)`

**Comment by MajkiIT** [comment]
@F4z Super. Dziękuję.
