### ISSUE TITLE
Stop auto play on onet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2602]
funkcja zostala dodana do adprotectora prosze testowac

info od autora

![capture](https://cloud.githubusercontent.com/assets/15007183/25906126/cf679670-3571-11e7-8ec0-e30e39902484.PNG)

**Comment by gzenio22** [comment]
@xxcriticxx Dał bys link do adprotectora dla opery tak jak kiedys mi podzuciles do angielskich filtrow?

**Comment by MajkiIT** [comment]
U mnie niestety nadal jest autoplay.

**Comment by MajkiIT** [comment]
@gzenio22 o tym mówisz?

https://jspenguin2017.github.io/AdBlockProtector/

**Comment by xxcriticxx** [comment]
@gzenio22 

filtry 

https://raw.githubusercontent.com/jspenguin2017/AdBlockProtector/master/AdBlockProtectorList.txt

**Comment by gzenio22** [comment]
@MajkiIT @xxcriticxx Dzieki 

Co do playerow na onecie niestety nadal mi je odpala z automatu

**Comment by xxcriticxx** [comment]
@gzenio22 clear cookies i historie always

**Comment by xxcriticxx** [comment]
wlasnie zrobilem testa i mi cos tez za bardzo to niedziala

**Comment by xxcriticxx** [comment]
ok rozwiazalem sprawe trzeba w ustawienieach wlaczyc opcjie i dziala

**Comment by gzenio22** [comment]
U mnie kurdelebele to nie dziala dalej mi odpala mimo ze mam wlaczona opcje w settings
