### ISSUE TITLE
onet.pl - autoplay video

### ISSUE THREAD

**Issue by PrzemyslawKlys** [MajkiIT/polish-ads-filter#2604]
Wiem, że to nie do końca reklama, ale może w ramach filtrów można zatrzymać autoplay dla onet.pl. Mam co prawda dobre łącze internetowe/komputer, ale chciąłbym miec kontrolę nad tym co leci w danej chwili. A czasami lecę na roamingu, lub po wifi z ograniczeniem i onet wciąga mb jak szalony.

**Comment by MajkiIT** [comment]
Już jet to zrobione. Zerknij tutaj 
https://github.com/MajkiIT/polish-ads-filter/issues/2602
