### ISSUE TITLE
superstyler.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2605]
maybe?

http://www.superstyler.pl/dziecko/nasze-ulubione-bajki-dla-dzieci/

![capture](https://cloud.githubusercontent.com/assets/15007183/25965739/db9f3110-3656-11e7-985d-cf5fdd6f770c.PNG)

**Comment by MajkiIT** [comment]
`||pushcrew.com$cript`

maybe?

**Comment by xxcriticxx** [comment]
maybe tak
