### ISSUE TITLE
stooq.pl/stooq.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2608]
strona caly czas sie laduje dziura po reklamach 

![capture](https://cloud.githubusercontent.com/assets/15007183/25973230/2be6e36a-3671-11e7-91af-db92aecb95ec.PNG)

**Comment by F4z** [comment]
`stooq.pl,stooq.com##tbody > tr > td[width="1"]`
`stooq.pl,stooq.com##tbody > tr > td[align="center"] > div[style="width:300;height:250"]`
`stooq.pl,stooq.com##tbody > tr > td > table[width="300"][height="250"][border="0"][cellpadding="0"][cellspacing="0"][align="center"]`

**Comment by xxcriticxx** [comment]
regula jest good ale umnie dalej strona sie caly czas laduje 

![screenshot from 2017-05-19 09-01-20](https://cloud.githubusercontent.com/assets/15007183/26248787/c2ecfde8-3c71-11e7-9301-e1f46c713a12.png)

**Comment by F4z** [comment]
@MajkiIT myślę, że reguły, które usunąłeś są nadal potrzebne.
Mógłbyś sprawdzić?

**Comment by MajkiIT** [comment]
U mnie wydaje się ok, ale zaraz przywrócę. Dzięki za uwagę.
