### ISSUE TITLE
czateria.interia.pl (Nowa ankieta)

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2609]
![shu_mk7bmm](https://cloud.githubusercontent.com/assets/21177361/25999488/97b1c9d4-3725-11e7-9263-7b132eb30916.png)

Takie cos mnie dzisiaj przywitalo podczas logowania Ktos moze sprawdzic? :)

**Comment by MajkiIT** [comment]
@xxcriticxx już sprawdzam

**Comment by MajkiIT** [comment]
U mnie czysto . Może ktoś jeszcze zerknąć?

**Comment by xxcriticxx** [comment]
@MajkiIT ja tego tematu nie otwieralem

**Comment by xxcriticxx** [comment]
@MajkiIT trzeba sie zalogowac

**Comment by gzenio22** [comment]
znaczy przy wpisywaniu nicku na czaterie mi to wbilo

**Comment by MajkiIT** [comment]
@xxcriticxx sorry pomyłka
