### ISSUE TITLE
zippyshare dziwna akcja

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2611]
Hej od jakichs 2 dni mam maly problem z playerem na zippy i nie wiem czy nie jest to forma walki z blokowaniem ich popupa mianowicie 

Przykladowy link http://nuteczki.eu/muzyka/disco-polo/166152-zajefajni-zajefajna-dziewczyna-dance-2-disco-remix.html

powiedzcie mi czy u kogos z was @xxcriticxx @F4z @MajkiIT po kliknieciu play player sie buforuje zaczyna grac czy automatycznie robi sie stop i nie buforuje nuty?

**Comment by xxcriticxx** [comment]
@gzenio22 nie posiadam glosnikow ale gra od razu

**Comment by MajkiIT** [comment]
@gzenio22 u mnie jest ok.

**Comment by gzenio22** [comment]
kurde... ja nic nie mieszalem w skryptach :(

**Comment by MajkiIT** [comment]
inna przeglądarka?

**Comment by gzenio22** [comment]
Opera w tym wypadku

**Comment by gzenio22** [comment]
@MajkiIT Zamknij proszę to musiał być jakiś wal od strony hostera już mi działa :) ale naprawdę długo nie ogarniało to było dziwne
