### ISSUE TITLE
nationalgeographic.com

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#2612]
http://www.nationalgeographic.com/magazine/2017/06/dinosaur-nodosaur-fossil-discovery/?sf78249449=1

Cała strona ukryta przez `com##[class^="ad-"]`

Właściwie to `~wpolityce.pl,~box.com,~hardcorowo.pl,~gumtree.com,~hulu.com,com,pl##[class^="ad-"]`

**Comment by MajkiIT** [comment]
@gwarser dzięki
