### ISSUE TITLE
tinypic.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2613]
Baner " LIKE PLUS "

**Comment by F4z** [comment]
Jakiś czas temu widziałem to też na kilku innych stronach, więc myślę, że można dodać ogólną regułę:
`##a[href="http://www.likeplus.eu/clickback"]`

**Comment by xxcriticxx** [comment]
kiedys to juz chyba bylo na liscie

**Comment by MajkiIT** [comment]
Dzięki

**Comment by blocker999** [comment]
aha jeszcze dopiero teraz zauważyłem że zastała reklama radia stars, więc na to powinna pasować ta reguła:

`###nexus_ban`
