### ISSUE TITLE
sjp.pwn.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2617]
Komunikat o adblocku - http://sjp.pwn.pl/

![image](https://cloud.githubusercontent.com/assets/11742596/26035741/6554004e-38d1-11e7-88ec-06c0af7cf2c4.png)

Powinno wystarczyć:
`@@||sjp.pwn.pl/ads.js$script,domain=sjp.pwn.pl`
Ewentualnie do uBlocka:
`sjp.pwn.pl##script:inject(abort-on-property-write.js, adblock)`

https://github.com/reek/anti-adblock-killer/issues/3201

**Comment by MajkiIT** [comment]
@F4z Dzięki
