### ISSUE TITLE
irytujący problem

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2626]
Mam dość irytujący problem a mianowicie przeglądam często ogłoszenia na olx.pl i widzę często żółte paski co mnie wkurza więc proszę was o pomoc w ich usunięciu. Konkretnie to chodzi mi tylko o usunięcie tylko tego żółtego tła a nie całego ogłoszenia.

![olx](https://cloud.githubusercontent.com/assets/23176832/26037440/c1cfe2d6-38f2-11e7-84e9-db46a37b2c90.jpg)

**Comment by F4z** [comment]
Nie wiem czy dobrze rozumiem.
Chodzi o to żeby zamiast czegoś takiego:

<details><summary>Obrazek 1</summary>

![image](https://cloud.githubusercontent.com/assets/11742596/26037472/7d65856e-38f3-11e7-8333-2321677d0b1b.png)
</details>
<br>

było tak?

<details><summary>Obrazek 2</summary>

![image](https://cloud.githubusercontent.com/assets/11742596/26037485/a30b712a-38f3-11e7-8133-ec77e40d2e99.png)
</details>
<br>

Jeśli tak, to możesz sprawdzić tę regułę:
`olx.pl##.offer.promoted:style(background: none !important;)`

Gdyby jednak chodziło o coś innego albo ta reguła nie działała, to podaj proszę link.

**Comment by blocker999** [comment]
Dokładnie oto mi chodziło

@F4z Wielkie dzięki
