### ISSUE TITLE
obcyjezykpolski.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2627]
maybe?

test link:

http://obcyjezykpolski.pl/polszczyzna-od-reki-pana-literki/o-domu-o-synu-po-panu/

![capture](https://cloud.githubusercontent.com/assets/15007183/26054173/a3b8c852-3939-11e7-94e8-e54bc88e3de6.PNG)

**Comment by MajkiIT** [comment]
No właśnie nie wiem. To jakiś konkurs.

**Comment by xxcriticxx** [comment]
to zostaw na razie nie przeszkadza w sumie
