### ISSUE TITLE
Ponownie WP sie popsuło

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2631]
![shu_75omga](https://cloud.githubusercontent.com/assets/21177361/26072665/9f263504-39ac-11e7-8722-2a9e4101d015.png)
![shu_ky8w8y](https://cloud.githubusercontent.com/assets/21177361/26072666/9f29540a-39ac-11e7-98d0-ef9b95370952.png)

taki typ reklam jest na calej str glownej dodatkowo jak zleci sie na prawie sam dol wylatuje reklama butow
Sa tez te calkiem puste z logiem WP

**Comment by MajkiIT** [comment]
Która wersja filtrów?

**Comment by gzenio22** [comment]
najnowsza 5 min temu aktualizowalem

**Comment by MajkiIT** [comment]
tak widzisz stronę tylko?

**Comment by gzenio22** [comment]
![shu_znpy2p](https://cloud.githubusercontent.com/assets/21177361/26072927/8cfb4bf2-39ad-11e7-8bd4-3a9f084c4b44.png)
![shu_2rwvjx](https://cloud.githubusercontent.com/assets/21177361/26072928/8cfdb662-39ad-11e7-9e31-10c06cd34f52.png)


Tak widze strone te 2 to tylko przyklad

**Comment by MajkiIT** [comment]
log z ubo?

**Comment by gzenio22** [comment]
why? jak go wygenerowac?

**Comment by MajkiIT** [comment]
dziennik żądań, chyba tak to się nazywa

**Comment by xxcriticxx** [comment]
@MajkiIT mam tez reklamy

**Comment by gzenio22** [comment]
@MajkiIT Nie mam w ubo takiej zakladki ani funkcji generacji loga

**Comment by MajkiIT** [comment]
a takie coś Ci blokuje ?
||https://www.wp.pl/NrrQPTJvJ$script

**Comment by xxcriticxx** [comment]
@MajkiIT  ta regula jest git pomogla

**Comment by gzenio22** [comment]
@Majkit po dodaniu tego do moich filtrow zostalo teraz jeszcze to 
![shu_ovjr8z](https://cloud.githubusercontent.com/assets/21177361/26073362/eda858b8-39ae-11e7-95ff-2627e59f6ff8.png)

**Comment by MajkiIT** [comment]
ale ta reguła jest w filtrach. 

https://github.com/MajkiIT/polish-ads-filter/commit/d59ddffd0b84053bf06aff0bc1b8533f6c56a731#diff-711027ed0794992ae3b8710d874f3df7

**Comment by xxcriticxx** [comment]
@MajkiIT logy z ubo

http://imgur.com/a/6BRfH

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki wrócę do domu to zerknę.

**Comment by gzenio22** [comment]
@xxcriticxx jak ty w to wlazles ja nie widze u siebie takich logow jak bym o tym wiedzial ulatwilo by wam to robote

**Comment by xxcriticxx** [comment]
@gzenio22 moment zaraz zrobje tobie zdjecje jak tam sie dostac

**Comment by xxcriticxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/15007183/26074391/ac11463c-397f-11e7-945f-bad132a46d78.PNG)

**Comment by gzenio22** [comment]
@xxcriticxx Dzieki mam :)

**Comment by xxcriticxx** [comment]
@MajkiIT poprawka bendzie?

**Comment by MajkiIT** [comment]
Ale tą regułę dodałem wczoraj, a coś jest nie tak?

**Comment by xxcriticxx** [comment]
@MajkiIT dalej mam reklamy z `v.wpimg.pl` cookies i cache czysilem from the beginning

filtry mam z v.2017051601 aktualizacja: wt, 16 maja 2017, 00:45:00

![screenshot from 2017-05-16 16-07-52](https://cloud.githubusercontent.com/assets/15007183/26125975/e8f7acee-3a51-11e7-906d-0a548ef76ef6.png)

**Comment by xxcriticxx** [comment]
@MajkiIT idiot zemnie cookies nie wykasowalem w foxie po kasowaniu mam jeszcze kilka drobnych reklam 

![capture](https://cloud.githubusercontent.com/assets/15007183/26126743/d3a05b68-3a54-11e7-9a60-db6e4cc8f096.PNG)
![capture1](https://cloud.githubusercontent.com/assets/15007183/26126747/d6f0a75a-3a54-11e7-94a7-802bc81656e4.PNG)

**Comment by F4z** [comment]
@xxcriticxx ta reguła u Ciebie nie działa?
`www.wp.pl##script:inject(abort-on-property-write.js, testMess)`

**Comment by xxcriticxx** [comment]
@F4z moment po 4 refreszach strony reklamy wrocily musz znowu cookies wypierdolic i cache

**Comment by xxcriticxx** [comment]
nic nie pomaga wykasowalem wszystko i dalej mam regkalmy kasuje jeszcze raz i reboot zrobie

**Comment by xxcriticxx** [comment]
dalej ten sam problem nic nie pomaga

**Comment by MajkiIT** [comment]
@xxcriticxx u mnie reguła podana przez @F4z zadziałała. Zaraz dodam ją do filtrów uBlocka. 

A sprawdź taką regułę `||www.wp.pl/6yEDzl$script,domain=www.wp.pl`

**Comment by gzenio22** [comment]
he kurde nowe reklamy wbily zerknijcie na gorze baner z meblami Homebook.PL nizej reklama eobowie kolejny jakis wielki banner dermika (Jakis krem) Nizej w dziale sport jakis naroznik kolejne to jebitny banner wakacji w Grecji JPRDL XD Dzial biznes reklama lidla i domodi Dzial biznes Fasardi Bonprix i jakas promocja na czerwona sukienke Motoryzacja to jebitne tlo Bi Pi i 2 reklamy jakichs butow i lezaka miedzy stylem zycia znowu domodi 

Jezu ile tego jeszcze XD 

Mam najnowsze filtry i obie reguly

**Comment by xxcriticxx** [comment]
@MajkiIT jest tak jak @gzenio22 pisal reklamy sa wszendzie kasowanie cookies i cache nic nie daje. jak raz zalapiesz tak jak wirus wykasowac nie mozna.

**Comment by xxcriticxx** [comment]
Bingo naprawilem! mam tylko kilka pustych box ze slowem reklama i niemam prawej strony z tv

**Comment by MajkiIT** [comment]
@xxcriticxx dodałem regułę do list adblock.txt stąd nie masz reklam ale wywala pasek po prawej.

**Comment by MajkiIT** [comment]
@gzenio22 @xxcriticxx @F4z 
Macie napisy reklama
http://wiadomosci.wp.pl/markus-nie-mowil-prawdy-to-rzuca-cien-na-jego-wersje-6123528250615937a

**Comment by xxcriticxx** [comment]
tak ja mam

**Comment by gzenio22** [comment]
Tak mam

**Comment by F4z** [comment]
Na te napisy "reklama" to powinno wystarczyć:
`wp.pl##div[class^="_"] > style + div[class]`

**Comment by xxcriticxx** [comment]
@F4z a prawa strona?

**Comment by F4z** [comment]
@xxcriticxx a prawa strona jest "blokowana" przez tę regułę:
`||www.wp.pl/6yEDzl$script,domain=www.wp.pl`

Możesz sobie dodać coś takiego:
`||www.wp.pl/6yEDzl$script,domain=www.wp.pl,badfilter`
wtedy ta reguła zostanie wyłączona, ale najprawdopodobniej zobaczysz reklamy.
Napisałem, że najprawdopodobniej, bo u mnie poniższa reguła działa i reklam nie widzę:
`www.wp.pl##script:inject(abort-on-property-write.js, testMess)`
ale u Was niestety to nie pomaga.
Możesz jeszcze wstawić sceenshota z loggera uBlocka (w tym polu na górze wpisać "script", bo reszta mi nie jest potrzebna), i źródło strony, to znaczy kliknąć "Ctrl + U" skopiować wszystko i wkleić na jakiegoś pastebina, czy cokolwiek podobnego.
Moooże coś wymyślę.
Ewentualnie jeszcze można spróbować z wyrażeniem regularnym, ale to i tak w tym przypadku raczej będzie chwilowo działało.

Zauważyłem też reklamy na podstronach wp, ta reguła powoduje, że ich już nie widzę:
`~www.wp.pl,~poczta.wp.pl,wp.pl##script:inject(abort-on-property-write.js, habahaba)`
ale pamiętam, że u niektórych to psuło stronę główną - https://github.com/MajkiIT/polish-ads-filter/issues/2497#issuecomment-297974797

Niestety ostatnio mam mało czasu, więc fajnie by było, gdyby osoby którym pokazują się reklamy podawały jak najwięcej informacji, bo ułatwiłoby to zadanie, a co za tym idzie mniej czasu musiałbym poświęcić na próbach odtworzenia problemu.

**Comment by xxcriticxx** [comment]
https://pastebin.com/fk6edwQi

![screenshot from 2017-05-17 15-00-10](https://cloud.githubusercontent.com/assets/15007183/26171049/91262174-3b11-11e7-9570-9159955c1344.png)

**Comment by F4z** [comment]
Dzięki, niejasno napisałem, chodziło mi o źródło strony wp.pl, a nie o dziennik zdarzeń uBlocka :)

**Comment by F4z** [comment]
A i rozumiem, że w momencie kiedy zrobiłeś screena z loggera uBlocka, to reklam nie było, tylko ten panel po prawej nie działał?

**Comment by xxcriticxx** [comment]
@F4z tak nie bylo reklam niema tylko prawej strony

**Comment by F4z** [comment]
@xxcriticxx ok, a możesz jeszcze pokazać źródło strony wp.pl?

**Comment by xxcriticxx** [comment]
https://pastebin.com/pgZxqwry

**Comment by F4z** [comment]
Ok dzięki, to wygląda tak jak u mnie.
To możesz jeszcze sprawdzić te niżej reguły?
Ta pierwsza żeby "prawa strona" działała, a reszta na reklamy.

```
||www.wp.pl/6yEDzl$script,domain=www.wp.pl,badfilter
www.wp.pl##script:inject(abort-on-property-write.js, testMess)
~www.wp.pl,~poczta.wp.pl,wp.pl##script:inject(abort-on-property-write.js, habahaba)
wp.pl##div[class^="_"] > style + div[class]
```

Jeśli to nadal nie rozwiąże problemu, to na razie nie mam pomysłu jak zablokować te reklamy żeby nie zepsuć działania strony. Może ktoś inny coś jeszcze wymyśli :)

**Comment by xxcriticxx** [comment]
mam kasowac cache i cookies?

**Comment by F4z** [comment]
Nie trzeba, u mnie bez kasowania działa.

**Comment by xxcriticxx** [comment]
na main stronie sa puste boxy ze slowem reklama

**Comment by xxcriticxx** [comment]
filmy leca ale obrazu niema

**Comment by xxcriticxx** [comment]
ale to moze byc z powodu cookies

**Comment by F4z** [comment]
Wydaje mi się, że film nie działa, bo najpierw chce wyświetlić reklamę, która jest blokowana. Mam na myśli te filmy na stronie głównej tam z tej "prawej strony".

Te "puste boxy" są na stronie głównej?

Rozumiem, że nie masz reklam po kilku odświeżeniach strony?

**Comment by xxcriticxx** [comment]
Filmy mi chodzilio na sekcj sport 

Tak puste boxy są na main

Niemam reklam po odświeżeniach strony

**Comment by F4z** [comment]
Nie widzę tych pustych boxów na stronie głównej.
Możesz podać link do filmu który Ci nie działa?

**Comment by xxcriticxx** [comment]
![screenshot from 2017-05-17 18-01-51](https://cloud.githubusercontent.com/assets/15007183/26178231/258e1e52-3b2b-11e7-9b7f-fb5409de637c.png)

**Comment by xxcriticxx** [comment]
filmu szukam bo nagle magicznie zaczely wszystkie dzialac

**Comment by xxcriticxx** [comment]
ten film mi sie pokazuje i znika 

http://opinie.wp.pl/marcin-makowski-trwa-polityczna-gra-uchodzcami-a-czy-ich-ktos-pyta-o-zdanie-6123600329582209a

**Comment by xxcriticxx** [comment]
tutaj podobnie 

http://wiadomosci.wp.pl/trump-w-tarapatach-republikanski-kongresmen-nie-wyklucza-impeachmentu-6123739223480449a

**Comment by F4z** [comment]
Ok, ale to już kiedyś o tym pisaliśmy, że dzieje się tak w momencie, gdy zamiast filmu/odtwarzacza ma się pojawić reklama.

Odnośnie tego napisu "Reklama" na stronie głównej, to u mnie w Chrome go nie widzę, ale w Firefoxie już tak, zaraz postaram się podać regułę.

**Comment by xxcriticxx** [comment]
reklama jest w kilku miescach nie tylko w sporcje

**Comment by F4z** [comment]
Nie wiem czemu reguła, która działa w Chrome nie działa w Firefoksie.

Możesz sprawdzić te dwie, powinno być ok:
`www.wp.pl##div[class]:matches-css(width: 300px):matches-css(height: 250px)`
`www.wp.pl##div[class]:matches-css(width: 309px):matches-css(height: 182px)`

**Comment by xxcriticxx** [comment]
regula jest dobra

**Comment by xxcriticxx** [comment]
adam lece postac w korkach zobacz na otwarte tematy stooq i inne 

dzieki za pomoc!

**Comment by F4z** [comment]
Nie ma sprawy, fajnie, że działa.

Tutaj lista wszystkich reguł do testowania jakby ktoś chciał jeszcze sprawdzić.

```
||www.wp.pl/6yEDzl$script,domain=www.wp.pl,badfilter
www.wp.pl##script:inject(abort-on-property-write.js, testMess)
~www.wp.pl,~poczta.wp.pl,wp.pl##script:inject(abort-on-property-write.js, habahaba)
www.wp.pl##div[class]:matches-css(width: 300px):matches-css(height: 250px)
www.wp.pl##div[class]:matches-css(width: 309px):matches-css(height: 182px)
wp.pl##div[class^="_"] > style + div[class]
```

Ta pierwsza jest po to żeby "wyłączyć" tę regułę -` ||www.wp.pl/6yEDzl$script,domain=www.wp.pl`

Na inne strony spojrzę jak się wyśpię i będę miał trochę wolnego czasu :)

**Comment by F4z** [comment]
@gzenio22 no tak, pisałem o tym, że u niektórych ta reguła - `~www.wp.pl,~poczta.wp.pl,wp.pl##script:inject(abort-on-property-write.js, habahaba)` - może psuć stronę główną. To chyba wina tego, że u Ciebie strona główna jest jako `wp.pl`, i w zasadzie to nie wiem czemu tak się dzieje, bo mnie zawsze przekierowuje do `www.wp.pl`. Ewentualnie wina jest w innej regule, a po prostu masz ustawione żeby nie pokazywało pełnego adresu.

Zamiast poprzednich reguł możesz sprawdzić te:
```
||www.wp.pl/6yEDzl$script,domain=www.wp.pl,badfilter
wp.pl##script:inject(abort-on-property-write.js, testMess)
facet.wp.pl,film.wp.pl,gry.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,moto.wp.pl,opinie.wp.pl,sportowefakty.wp.pl,tech.wp.pl,turystyka.wp.pl,wiadomosci.wp.pl##script:inject(abort-on-property-write.js, habahaba)
wp.pl##div[class^="_"] > style + div[class]
```

**Comment by MajkiIT** [comment]
@F4z Dzięki wielkie. Jeszcze dopytam. 

||www.wp.pl/6yEDzl$script,domain=www.wp.pl,badfilter - to do usuniecia z listy adblock
www.wp.pl##script:inject(abort-on-property-write.js, testMess) - dodane już do listy ublock
~www.wp.pl,~poczta.wp.pl,wp.pl##script:inject(abort-on-property-write.js, habahaba) - dodać do listy ublock
www.wp.pl##div[class]:matches-css(width: 300px):matches-css(height: 250px) - adblock
www.wp.pl##div[class]:matches-css(width: 309px):matches-css(height: 182px) - adblock
wp.pl##div[class^="_"] > style + div[class] - adblock

**Comment by F4z** [comment]
@MajkiIT 

1. `||www.wp.pl/6yEDzl$script,domain=www.wp.pl` - tak, to do usunięcia.
2. `www.wp.pl##script:inject(abort-on-property-write.js, testMess)` - tak, to jest dodane już do listy ublocka, ale nie wiem, czy nie warto usunąć `www.` z początku tej reguły.
3. `~www.wp.pl,~poczta.wp.pl,wp.pl##script:inject(abort-on-property-write.js, habahaba)` - to psuło niektórym osobom stronę główną, więc chyba coś takiego będzie lepsze:
`facet.wp.pl,film.wp.pl,gry.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,moto.wp.pl,opinie.wp.pl,sportowefakty.wp.pl,tech.wp.pl,turystyka.wp.pl,wiadomosci.wp.pl##script:inject(abort-on-property-write.js, habahaba)`
Nie wiem czy to wszystkie strony, więc najwyżej będzie trzeba dodać kolejne do tej reguły.
4. Tak
5. Tak
6. Tak

**Comment by gzenio22** [comment]
@F4z 

Z kolei po tych jest lepiej wszystko dziala ale zostaly mi napisy reklama w dzialach sport biznes i styl zycia

**Comment by lukjan32** [comment]
najnowsze filtry nie pomagaja

**Comment by MajkiIT** [comment]
@lukjan32 Adblock? Adblock Plus? ublock? Ublock Origin?... PC ? tel?

**Comment by gzenio22** [comment]
U mnie odziwo juz jest good :) zadnych reklam chyba ze za reklame wezmiemy ten quiz o niemcach na topie

**Comment by lukjan32** [comment]
ublock origins, filtry najnowssze, na pc.

**Comment by MajkiIT** [comment]
@lukjan32 tryb prywatny?

**Comment by lukjan32** [comment]
nie

**Comment by xxcriticxx** [comment]
@lukjan32 co dokladnie sie dzieje napisz wiecej czego juz probowales

**Comment by lukjan32** [comment]
prawie dzienne pojawiaja sie reklamy, nawet po aktualizacji filtrow, dzienne.

**Comment by xxcriticxx** [comment]
na main czy stronach? cookie cache czysciles?

**Comment by xxcriticxx** [comment]
masz jakies inne wtyczki co blakuja? inny browser to testow?

**Comment by lukjan32** [comment]
czyscilem, nie uzywam innych.

**Comment by xxcriticxx** [comment]
cookies tez? 

glupie pytanie dasz rade odmontowac browser i zamontowac jeszcze raz?

**Comment by lukjan32** [comment]
cookies tez. moge.

**Comment by xxcriticxx** [comment]
@lukjan32 windows tak?

**Comment by xxcriticxx** [comment]
@lukjan32 open cmd as admin and enter `ipconfig /flushdns` i potem enter

**Comment by lukjan32** [comment]
no, win 10.

**Comment by xxcriticxx** [comment]
@lukjan32 zrobiłeś flush DNS?

**Comment by lukjan32** [comment]
tak, i dalej niekiedy sa reklamy

**Comment by xxcriticxx** [comment]
cos maz nie wyczyszczone dlatego masz rekalamy

**Comment by lukjan32** [comment]
aha, ale co :(

**Comment by xxcriticxx** [comment]
cookies historie bookmari

**Comment by xxcriticxx** [comment]
nasza ulubiona strona ma puste boxy ze slowem reklama

**Comment by xxcriticxx** [comment]
na main page

**Comment by gzenio22** [comment]
lol znowu :/ a bylo ok

**Comment by MajkiIT** [comment]
Która wersja filtrów?

**Comment by xxcriticxx** [comment]
v.2017052803 aktualizacja: nie, 28 maja 2017, 20:20:00

**Comment by MajkiIT** [comment]
@xxcriticxx ty też masz reklamy?

**Comment by xxcriticxx** [comment]
puste boxy po reklamach na main page

![capture](https://cloud.githubusercontent.com/assets/15007183/26531367/9fe4f440-43b5-11e7-8ff2-d622620896bc.PNG)

**Comment by lukjan32** [comment]
tez mam, i te same filtry

**Comment by lukjan32** [comment]
juz sa w calej domenie reklamy.
