### ISSUE TITLE
Auto play na pudelku? 

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2637]
Hej trafiłem na ten  portal z linka na FB ale co mnie zaciekawiło 

Test Link: http://www.pudelek.tv/video/Agresywne-gimnazjalistki-z-Gdanska-WYJA-W-SADZIE-Blagaly-o-wybaczenie…-WIDEO-15982/?src01=6a4c8&src02=facebook_wp

Jak wbijecie na stronę to Player zaraz pod nagłówkiem artykułu rusza bez mojej ingerencji ale dalej... skończy się jedno wideo to 3 sekundy potem rusza kolejne sorry ale tak chyba być nie powinno :)

**Comment by xxcriticxx** [comment]
tak powino byc 

pudelek jest czescia onetu.pl mozna poprosic ad protectora zeby dodal

**Comment by gzenio22** [comment]
@xxcriticxx Weś ty tam napisz jeśli możesz mój angielski sam wiesz jaki jest

**Comment by xxcriticxx** [comment]
taki sam jak moj

**Comment by gzenio22** [comment]
taa ja lece z translatora XD

**Comment by xxcriticxx** [comment]
Ja tez z hiszpańskiego 🔥👹💩
