### ISSUE TITLE
Filmweb.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2638]
Ciekawa reklama przed ponownym wejściem na strone.

<img width="698" alt="filmweb" src="https://cloud.githubusercontent.com/assets/23176832/26119636/3b5552fe-3a6e-11e7-8bbd-f4d37555c072.png">

**Comment by gzenio22** [comment]
o kurna netflix sie reklamuje w koncu poszli w slady showmaxa :D

**Comment by F4z** [comment]
Możecie sprawdzić czy to pomaga?
`||filmweb.pl/iri-welcomeScreenJS`

**Comment by gzenio22** [comment]
u mnie nie wyskoczyla :)

**Comment by blocker999** [comment]
@F4z Tak ta reguła pomaga.

**Comment by MajkiIT** [comment]
@F4z dzięki
