### ISSUE TITLE
Bez oglądania na thevideo.me

### ISSUE THREAD

**Issue by maxoku** [MajkiIT/polish-ads-filter#2643]
Po kliknięciu na "Proceed to video" odtwarzacz z filmem się nie otwiera tylko strona jest zwyczajnie odświeżana. Po wyłączeniu polskich filtrów wszystko działa bez problemu. uBlock.

**Comment by xxcriticxx** [comment]
test link please?

**Comment by maxoku** [comment]
proszę: https://thevideo.me/dcn2cartxgcn

**Comment by F4z** [comment]
Sprawdziłem tutaj - `https://thevideo.me/f39rdloubumj` - i u mnie normalnie wszystko działa.
Na podanym wyżej linku też.

Jedyna reguła dotycząca `thevideo.me`, którą znalazłem na polskiej liście, to ta:
`||thevideo.me/assets/*popjs$script`
Możesz sprawdzić tę regułę:
`@@||thevideo.me/assets/*popjs$script`
Dodaj to sobie w zakładce "Moje filtry", jak pomoże to fajnie, a jak nie, to będzie trzeba szukać innego rozwiązania.

Swoją drogą uBlock, w sensie uBlock Origin, tak?
Wolę się zapytać, bo czasami były osoby, które korzystały ze "zwykłego" uBlocka, a on jest już od dłuższego czasu nieaktualizowany i może sprawiać problemy.

**Comment by xxcriticxx** [comment]
umnie jest ok 

![capture](https://cloud.githubusercontent.com/assets/15007183/26228069/69a13668-3c04-11e7-89d6-c36729df73c6.PNG)

**Comment by maxoku** [comment]
A rzeczywiście po dodaniu tej reguły pomogło, wielkie dzięki ;p. 
Od kiedy to **uBlock Origin** pozwala na to? Pamiętam jak po przejściu z AdBlock Plusa miałem z tym problemy i twórcy mówili, że się nie da^^.

**Comment by MajkiIT** [comment]
U mnie też jest ok. Sprawdzę czy nie będzie zaraz problemów po usunięciu tej reguły.
