### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2647]
Adblock - `https://shinden.pl/external-video/201-dragon-ball/view/5175`

![image](https://cloud.githubusercontent.com/assets/11742596/26249188/c5840270-3ca5-11e7-9756-e22736f2668a.png)

Reguła:
`@@||reklama.shinden.eu/adpeeps.php?bzone=$domain=shinden.pl`

**Comment by xxcriticxx** [comment]
ja mam cos extra w pliku host ze zjadlo dwie linie

**Comment by MajkiIT** [comment]
@F4z dzięki
