### ISSUE TITLE
morele.net

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2656]
left right + 400 zl

![capture](https://cloud.githubusercontent.com/assets/15007183/26263079/3031bdc0-3ca5-11e7-80d5-3c42b817e354.PNG)

**Comment by MajkiIT** [comment]
Chwilowo tego nie widzę.

**Comment by xxcriticxx** [comment]
```
morele.net##.ears-right
morele.net##.ears-left
morele.net##.hidden.citibank-popup
```
