### ISSUE TITLE
seciki.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2667]
![capture](https://cloud.githubusercontent.com/assets/15007183/26283693/c609f050-3dfa-11e7-8b24-06bacfe3871c.PNG)

**Comment by MajkiIT** [comment]
Może tak ?
`seciki.pl##.crek > .lb`

**Comment by xxcriticxx** [comment]
najlepjej calosc sorry sety zagraniczne

`seciki.pl##.crek`
