### ISSUE TITLE
nflix.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2669]
ad block 

https://www.nflix.pl/kategoria/netflix-pl/

![capture](https://cloud.githubusercontent.com/assets/15007183/26284091/2900d9b6-3e01-11e7-8fea-f545e56c4462.PNG)

**Comment by F4z** [comment]
Chyba wystarczy to ukryć:
`nflix.pl##body > div[class][style*="z-index: 999999"]`

Do AdBlockProtector może być coś takiego:
```
if (a.domCmp(["nflix.pl"])) {
    a.always(function () {
        a.cookie("anCookie", "true");
        a.win.anOptions = {};
    });
}
```

W zasadzie to jest odpowiednie rozwiązanie w skrypcie, wystarczy dodać tylko tam domenę nflix.pl:
```
if (a.domCmp(["gametransfers.com", "winandmac.com", "free-steam-giveaways.com", "canalwp.com",
    "alphahistory.com", "nordpresse.be", "sospc.name", "baboo.com.br"])) {
    a.always(function () {
        a.cookie("anCookie", "true");
        a.win.anOptions = {};
    });
}
```

**Comment by xxcriticxx** [comment]
added to ad protector thank you @F4z

**Comment by F4z** [comment]
Dzięki :)
