### ISSUE TITLE
benchmark.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2670]
Cookies na dole strony a na forum na gorze

**Comment by xxcriticxx** [comment]
na media markt na topie

`benchmark.pl##.screenContainer`

![capture](https://cloud.githubusercontent.com/assets/15007183/26285563/592ae752-3e20-11e7-9a2e-3def5a9876e6.PNG)

**Comment by F4z** [comment]
Chyba nie wystarczy, nawet jak to ukryjesz, to gdy klikniesz gdzieś z boku strony, to wtedy otwiera się reklama w nowej karcie.
Do adblocka mogą być takie reguły:
`benchmark.pl##.screenContainer`
`||www.benchmark.pl/uploads/backend_img/c/marketing/`
`||benchmark.pl/screen-container-target.html$popup`

Wydaje mi się, że oni sprawdzają, czy wysokość elementu `bannerDBB` jest mniejsza niż 10px i jeśli jest, to wyświetlają te reklamy.
Do uBlocka/Adguarda można coś takiego dodać:
`benchmark.pl###bannerDBB:style(height: 10px !important;)`

**Comment by gzenio22** [comment]
cos nie pykło Ubo origin opera dodalem to co mialo na ubo dzialac nizej po lewej reklama BP nie dalem rady zlapac screenem
![shu_drjl9e](https://cloud.githubusercontent.com/assets/21177361/26287215/e716447a-3e76-11e7-9915-caabeeca4c6e.png)

**Comment by F4z** [comment]
Reguła dotyczy strony benchmark.pl, a na obrazku widoczna jest strona Media Markt.
Chyba nie wiem o co chodzi.

**Comment by xxcriticxx** [comment]
@F4z moze cos dadac do ad protectora?

**Comment by F4z** [comment]
@xxcriticxx raczej nie.
Ta reguła - `benchmark.pl###bannerDBB:style(height: 10px !important;)` - u Ciebie działa?

**Comment by xxcriticxx** [comment]
@F4z a jak mam to przetestowac jak sciagnlelem juz najnowsze filtry?

**Comment by F4z** [comment]
@xxcriticxx jak masz najnowsze filtry, to i tak powinno zostać tło z reklamą.

**Comment by xxcriticxx** [comment]
@F4z tak dziala na ubo i foxie 53.0.3

**Comment by F4z** [comment]
@xxcriticxx ok, dzięki za sprawdzenie.

**Comment by xxcriticxx** [comment]
maybe?

http://www.benchmark.pl/aktualnosci/wiedzmin-jako-serial-od-netflix-baginski-wsrod-rezyserow.html

![capture](https://cloud.githubusercontent.com/assets/15007183/26287585/c7eb187a-3e4c-11e7-99b3-676c1173393a.PNG)
