### ISSUE TITLE
speedtest.net (Nowe cookies)

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2674]
![shu_j3z4eq](https://cloud.githubusercontent.com/assets/21177361/26317295/47a7441a-3f17-11e7-92bc-51704b95bdb1.png)

**Comment by xxcriticxx** [comment]
@gzenio22 strona nie polska

**Comment by gzenio22** [comment]
ale polacy korzystaja to speedtest :)

**Comment by xxcriticxx** [comment]
@gzenio22 mowiles ze masz limitowany internet :)
