### ISSUE TITLE
pikio.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#2675]
Adblock:
`http://pikio.pl/zycie-spedzal-w-zamknieciu-teraz-sam-wybiera-sobie-zabawke/`

![image](https://cloud.githubusercontent.com/assets/11385099/26322489/97039694-3f2b-11e7-96f9-5c1643f596f0.png)

**Comment by xxcriticxx** [comment]
@mathew85 masz wlonczony ad block protector?

**Comment by F4z** [comment]
`pikio.pl##script:inject(fuckadblock.js-3.2.0)`
