### ISSUE TITLE
gadzetomania.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2677]
po chwili krecenia kulkiem wyskakuje cos takiego 
![shu_gvr7mz](https://cloud.githubusercontent.com/assets/21177361/26368298/8bab8b1e-3ff1-11e7-90cd-43cd33fdd31b.png)

test link: http://gadzetomania.pl/1243,xanadu-zapomniany-przodek-www-kto-naprawde-wymyslil-hipertekst

**Comment by MajkiIT** [comment]
Może coś takiego ?
`gadzetomania.pl###exit-intent-modal`

**Comment by gzenio22** [comment]
chyba dziala :)
