### ISSUE TITLE
Speedtest.net maly dodatek

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2678]
Na ten bialy pasek w lewym dolnym rogu powinno pomoc 
![shu_zx733j](https://cloud.githubusercontent.com/assets/21177361/26368775/f2de3c22-3ff2-11e7-8312-5941a92522aa.png)

##.privacy-update

**Comment by MajkiIT** [comment]
Zostało to dodane wczoraj
https://github.com/MajkiIT/polish-ads-filter/commit/b0a00313790db7d5eb7449dcc93d05ba46235f97
