### ISSUE TITLE
allezestaw.prv.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2679]
U góry w tych dwóch miejscach co jakiś czas zmieniają się reklamy.

![allezestaw](https://cloud.githubusercontent.com/assets/23176832/26391987/3e56f726-4065-11e7-8cd7-9cded2a4abef.jpg)

**Comment by xxcriticxx** [comment]
`allezestaw.prv.pl###prvAliasBanner`
`allezestaw.prv.pl##span`
