### ISSUE TITLE
mmorpg.org.pl

### ISSUE THREAD

**Issue by larwiasty** [MajkiIT/polish-ads-filter#2682]
![2017-05-26 1](https://cloud.githubusercontent.com/assets/26480899/26497572/e1699652-4223-11e7-956d-ae02e0eace21.png)
![2017-05-26](https://cloud.githubusercontent.com/assets/26480899/26497585/e58da674-4223-11e7-921f-c2634a5c1f7e.png)

Komunikat pojawia sie sporadycznie. Prosze odswiezyc kilka razy na glownej stronie.

**Comment by F4z** [comment]
Można to po prostu ukryć:
`mmorpg.org.pl##div[id][style*="background-image: url(/images/komunikat.jpg);"]`
albo dodać takie wyjątki, wtedy nie powinno wykrywać adblocka:
`@@||mmorpg.org.pl^$generichide`
`@@||mmorpg.org.pl/expop.js$script`

Jeszcze jest popup jak kliknie się na lewą lub prawą część strony:
`||bit.ly/2pRoyalQ_2$popup`

**Comment by larwiasty** [comment]
Dzieki :)

**Comment by MajkiIT** [comment]
@F4z dzięki
