### ISSUE TITLE
wcograc.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2684]
Tutaj nie chodzi o reklamę ale mam dziwne wrażenie ze twórcy strony blokują dostęp do strony głównej wielkimi bannerami gier może ktoś zerknąć?

**Comment by MajkiIT** [comment]
JS lub JQuery im się rozjechało i zamiast slideru jest ciąg obrazków.

`wcograc.pl###slider`

**Comment by MajkiIT** [comment]
ale to można dodać do filtrów 
`wcograc.pl##.click`

**Comment by gzenio22** [comment]
Dzieki fajnie to teraz wygląda :)
