### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2690]
no thx!

![capture](https://cloud.githubusercontent.com/assets/15007183/26530000/a08ea4f6-439a-11e7-863a-84a2814218f5.PNG)

**Comment by MajkiIT** [comment]
||www.dobreprogramy.pl$inline-script,domain=www.dobreprogramy.pl

ale nie wiem czy czegoś nie popsuje.

**Comment by F4z** [comment]
Niestety `inline-script` sprawi, że komentarze nie będą się wyświetlać.

Może coś takiego?
`||gstatic.com/firebasejs/*/firebase-messaging.js$domain=dobreprogramy.pl`

**Comment by MajkiIT** [comment]
Jest super dzięki.

**Comment by MajkiIT** [comment]
@xxcriticxx @F4z 
Możecie zerknąć czy macie czarne tło?

**Comment by F4z** [comment]
@MajkiIT w Chrome/Operze mam tło z reklamą https://github.com/MajkiIT/polish-ads-filter/issues/2589#issuecomment-302949444

**Comment by MajkiIT** [comment]
@F4z Dziękuję. Jutro dodam.

**Comment by F4z** [comment]
@MajkiIT ta reguła tam podana nie jest dobra, bo blokuje część funkcji strony.

W zasadzie to chyba tutaj najlepiej byłoby znowu o tym napisać - `https://github.com/uBlockOrigin/uAssets/issues/312`

**Comment by MajkiIT** [comment]
Ok jutro to uczynię dziękuję.
