### ISSUE TITLE
trybawaryjny.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2692]
maybe?

![capture](https://cloud.githubusercontent.com/assets/15007183/26530173/e476e6d0-439d-11e7-945d-254a4f3af144.PNG)

**Comment by blocker999** [comment]
Przy okazji warto usuną ten pasek na dole.

![trybawaryjny](https://cloud.githubusercontent.com/assets/23176832/26530555/46b4e9b2-43d7-11e7-94fc-bccbd140624f.jpg)

**Comment by MajkiIT** [comment]
trybawaryjny.pl###bottom-bar
###arlington-optin
