### ISSUE TITLE
intercity.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2694]
Brak obrazka, prawdopodobnie to wina easylist, proszę to sprawdzić i zgłosić

![intercity](https://cloud.githubusercontent.com/assets/23176832/26530279/84753720-43d2-11e7-98fe-a05ff16b756c.jpg)

**Comment by MajkiIT** [comment]
@@_reklama_$domain=intercity.pl

**Comment by gwarser** [comment]
Artykuł zablokowany przez `##[id*="reklama"]`

`https://www.intercity.pl/pl/site/dla-pasazera/informacje/reklamacje-i-skargi/podstawowe-informacje-na-temat-rozpatrywania-skarg,-reklamacji-i-wnioskow.html`

**Comment by gwarser** [comment]
@MajkiIT

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/61863392207bef7bdc563b57518fcfcc84cc10fd#diff-711027ed0794992ae3b8710d874f3df7
