### ISSUE TITLE
pks-czestochowa.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2700]
Jakaś reguła blokuje część informacji na stronie

**Comment by MajkiIT** [comment]
Dla mnie jest wszystko ok.

**Comment by blocker999** [comment]
O brak info o uldze studenckiej jest oczywisty, to 3 banery pod spodem są dyskusyjne bo ja uważam że te reklamy mają charakter informacyjny i powinny być, natomiast nie wiem jakie jest twoje zdanie ?.

![pks](https://cloud.githubusercontent.com/assets/23176832/26544714/0cbe983e-4463-11e7-8621-3d6a71440d29.jpg)

**Comment by MajkiIT** [comment]
@blocker999 ok masz rację
`pks-czestochowa.pl#@#.widget-advertisement`
