### ISSUE TITLE
popup blockera - pytanie

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2702]
Hej @blocker999 rzucił hasło aby dodać część filtrów https://github.com/azet12/PopupBlocker/blob/master/PPB.txt do polskich filtrów. 

Ja jestem za tylko nie chcę robić polskich filtrów kobyły. Co na ten temat sądzicie?

**Comment by xxcriticxx** [comment]
@MajkiIT zrob glosowanie na fb/stonie zobaczymy jak sie sprawa skonczy

**Comment by gzenio22** [comment]
tak jak @xxcriticxx  mowi :)
