### ISSUE TITLE
Anti-Adblock Killer Continued

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2703]
adblock protector zmienil nazwe i platforme na gitlab.com

https://xuhaiyang1234.gitlab.io/AAK-Cont/

**Comment by got3n** [comment]
Same filtry będą działać na AdBlocku/AdBlock Plus bez instalacji skryptu?

**Comment by xxcriticxx** [comment]
dla adblaku jest specialan lista

**Comment by xxcriticxx** [comment]
Extra explanation about AdBlock / Adblock Plus extension filter

For technical reasons, it is not always possible to block ads while breaking anti-adblock with only AdBlock / Adblock Plus. If you are using the Userscript (AAK-Cont Script), then do not subscribe to this filter.

What this extension filter does is it turns AdBlock / Adblock Plus off for you when it is known that there is no other solution without the Userscript, if this is what you want, then subscribe to this extension filter.

This does not apply to uBlock Origin or Adguard, if you are using them, then subscribe to the extension filter.

**Comment by MajkiIT** [comment]
No a co z pracą i filtrami https://jspenguin2017.github.io/uBlockProtector/ ?

**Comment by xxcriticxx** [comment]
Only chrome I violent monkey setup

**Comment by xxcriticxx** [comment]
[Announcement] What happened recently and why the name change 

https://github.com/jspenguin2017/uBlockProtector/issues/237

**Comment by uBlock-magic** [comment]
Nie chcę nic mówić ale to only to chyba support, bo w sumie wciąż działa kod uBlock Protectora w FF, nawet na próbę używam Violetmonkey.

AAK-Cont za to nie radzi sobie z komunikatami w klipach wideo (np. wiadomosci.wp.pl, błąd chyba 13 o wykryciu adblocka), niby coś tam poprawił ale zniknął raport z gitlab o zgłoszeniu błędu.
Testowane na dwóch zalecanych listach do uBlock i  skrypcie AAK-Cont.

**Comment by xxcriticxx** [comment]
aak-cont jest 6 miesiecy do tylu niedlugo bendzie update zeby listy byly takie same
