### ISSUE TITLE
lubimyczytac.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2706]
Tło
![shu_gva4aj](https://cloud.githubusercontent.com/assets/21177361/26555379/079d8964-4495-11e7-8c23-6b4671e65cb5.png)

**Comment by MajkiIT** [comment]
U mnie pusto.

**Comment by gzenio22** [comment]
kurde znowu czasem u mnie cos jest a u was nie ma (Juz u mnie tez nie ma) Dziwne

**Comment by F4z** [comment]
Wczoraj było :)

**Comment by MajkiIT** [comment]
@gzenio22 Po prostu coś zmienili lub reguły się zaktualizowały.
