### ISSUE TITLE
Nie można pisać mailów w wp.pl

### ISSUE THREAD

**Issue by maxoku** [MajkiIT/polish-ads-filter#271]
Cały box w którym wpisuje się wiadomości w poczcie wp.pl jest zablokowany/ukryty. Dodawanie wyjątków do białej listy (@@) nie działa. Po wyłączeniu filtru "pol" problem nie występuje.
![wp poczta](https://cloud.githubusercontent.com/assets/16660144/12272524/37532184-b961-11e5-8f4a-fb7e22f960cf.jpg)

**Comment by MajkiIT** [comment]
Witam dzięki za info.

Ja mam tak, więc problemu nie ma. 
![wp](https://cloud.githubusercontent.com/assets/11302675/12277718/44317772-b97d-11e5-8f77-cccc4a62bf35.png)

**Comment by maxoku** [comment]
Najprościej napisać, że problemu nie ma, bo u mnie nie występuje. Zapomniałem napisać, że korzystam teraz z uBlocka zamiast AdBlock Plusa.

**Comment by MajkiIT** [comment]
??? A czy ja napisałem, że mam to w nosie?

na uBlocku też pole jest aktywne. Filtry POL z jakiego dnia? 
![wp2](https://cloud.githubusercontent.com/assets/11302675/12278008/e81ea570-b97e-11e5-897a-5b1c4fccfeff.png)

**Comment by MajkiIT** [comment]
widzę, że otwarciu nowego okna z wiadomością generowany jest inny url.

**Comment by F4z** [comment]
Wydaje mi się, że to jest kwestia wyglądu, jeśli ustawi się jakiś klasyczny motyw, to wtedy nie widać tego pola.
Ta reguła powinna rozwiązać problem:
poczta.wp.pl#@#[id^="e"]

**Comment by maxoku** [comment]
Filtry z wczoraj, a screen ucięty i nie widać czy pole jest aktywne.
I pisałem, że po odznaczeniu polskich filtrów wszystko działa dobrze, właśnie piszę maila, bo wyłączyłem te filtry. A jak tą regułę dodać?

**Comment by F4z** [comment]
Wchodzisz w ustawienia uBlocka, potem w zakładkę "Moje filtry" i tam to wklejasz, a na koniec klikasz żółty przycisk "Zastosuj zmiany".

**Comment by MajkiIT** [comment]
Update gotowy.

**Comment by MajkiIT** [comment]
@F4z Dziękuję za pomoc.

**Comment by maxoku** [comment]
Dziękuję za rozwiązanie problemu.
