### ISSUE TITLE
atrakcjelubuskie.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2718]
Brak obrazka na dole strony " znajdź lubuskie ".

**Comment by MajkiIT** [comment]
Jest. Może masz jakieś inne filtry?

**Comment by blocker999** [comment]
Jakie filtry, jaśniej prosze.

**Comment by MajkiIT** [comment]
jakieś niestandardowe. Ja mam Easylist+2x Polskie+Ciasteczka+kad i widzę.

**Comment by blocker999** [comment]
w sensie ustawienia ublocka?

**Comment by MajkiIT** [comment]
tak

**Comment by blocker999** [comment]
Przepraszam to moje social media blokowały więc to odrazu uwzględnię przy następnej aktualizacji, jeszcze raz przepraszam.
