### ISSUE TITLE
AdAway for android 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#272]
moze da sie rade napisac jakis host file do tej apk?

**Comment by MajkiIT** [comment]
Spróbuję coś wykombinować, ale podobnie jak robiłem to pod IE, nie było to za rewelacyjne.

**Comment by xxcriticxx** [comment]
moze zrob glosowanie na fb zobaczymy czy jest jakies zainteresowanie

**Comment by xxcriticxx** [comment]
gdzie sa filtry do IE?

**Comment by MajkiIT** [comment]
http://www.certyficate.it/polskie-filtry-reklam-ie-9-11/

**Comment by xxcriticxx** [comment]
lidz reklamy przechodza i jest duzo duzo pustych box

**Comment by MajkiIT** [comment]
bo to blokuje tylko urle a nie div-y.

**Comment by xxcriticxx** [comment]
czytalem o tych div

pozatym adp jest jusz hyba na ie
