### ISSUE TITLE
videostar.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#2720]
Wideo nie działa - `https://videostar.pl/tv`
Reguła:
`@@||static.videostar.pl/static/assets/js/adcheck.min.js^`

**Comment by xxcriticxx** [comment]
ja jestem geolock

przepraszamy materiał niedostępny w twoim kraju

zalozy mi ktos proxy na polish ip :)

**Comment by MajkiIT** [comment]
@F4z Dzięki 
@xxcriticxx coś pomyślę na ten temat.
