### ISSUE TITLE
korektoronline.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2722]
reklama 

![capture](https://cloud.githubusercontent.com/assets/15007183/26594895/85e0e3d2-4537-11e7-8969-425e717ae882.PNG)

**Comment by blocker999** [comment]
Tych reklam jest więcej wystarczy odświeżać strone.

**Comment by xxcriticxx** [comment]
`korektoronline.pl###footer`

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki
