### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by pySilver** [MajkiIT/polish-ads-filter#2728]
@MajkiIT thanks for your great work!

Can you please comment on this: https://github.com/MajkiIT/polish-ads-filter/commit/5ff16b03c5ae97e316126342f731487771061953#commitcomment-22308543 ?

Thanks

**Comment by xxcriticxx** [comment]
@MajkiIT robisz zajebista robotę 👍👌🏿👊🗣💋🙀

**Comment by MajkiIT** [comment]
@xxcriticxx chyba robimy. Każdy jest potrzebny z naszego Github-owego składu.
