### ISSUE TITLE
kurnik.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2739]
nowy typ ad blockera Andrzej Duda

![screenshot from 2017-06-04 14-40-37](https://cloud.githubusercontent.com/assets/15007183/26764376/f361a162-4933-11e7-96ed-9868fc808f66.png)

**Comment by MajkiIT** [comment]
może coś takiego?
`kurnik.pl##[style="background: #f21; color: #fff; font-weight: bold; text-align: center; text-transform: uppercase; padding: 10px; margin-bottom: 2em; "]`

**Comment by xxcriticxx** [comment]
dziala
