### ISSUE TITLE
zumi.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2742]
maybe

http://www.zumi.pl/sklepy+elektroniczne+Tychy,namapie.html

![capture](https://user-images.githubusercontent.com/15007183/26899493-469bed7c-4b9d-11e7-9c5c-a07245b22a56.PNG)

**Comment by MajkiIT** [comment]
to lokalizacja. Jedni chcą drudzy nie.
