### ISSUE TITLE
forum.gazeta.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2746]
maybe?

http://forum.gazeta.pl/forum/w,252,55786341,55786341,Czy_znacie_jakies_sklepy_elektroniczne_.html

![capture](https://user-images.githubusercontent.com/15007183/26900022-ead5b8ea-4b9e-11e7-9e6a-15964b2f2291.PNG)

**Comment by MajkiIT** [comment]
lokalizacja.
