### ISSUE TITLE
eltrox.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2747]
maybe?

https://www.eltrox.pl/pointofsale

![capture](https://user-images.githubusercontent.com/15007183/26901629-821c78ba-4ba4-11e7-835d-f02fe7ad2c2d.PNG)

**Comment by MajkiIT** [comment]
Na bank to ten skrypt, ale zablokowanie psuje stronę.

`||www.eltrox.pl/media/js/e227d50bb7c620172334d7cd56a447ee.js?last_mod=1480414626$script,domain=www.eltrox.pl`

**Comment by xxcriticxx** [comment]
znajduje tego coraz wiecej czy mam podawac?

**Comment by MajkiIT** [comment]
pewnie

**Comment by xxcriticxx** [comment]
chyba podlega pod privacy?

**Comment by MajkiIT** [comment]
No właśnie nie wiem co o tym sądzić.
