### ISSUE TITLE
Proszę użytkowników z Polski o "pomoc".

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#2749]
Witam
http://www.spaste.com/s/xmh86z
Moglibyście proszę zobaczyć czy wyświetla Wam się link po rozwiązaniu captchy na tej stronie?
Powinno to wyglądać tak:
![](https://user-images.githubusercontent.com/18214146/26921866-a749d80a-4c3d-11e7-99ca-7fa27e585a02.PNG)
A ja mam tak:
![](https://user-images.githubusercontent.com/18214146/26921876-b43d23be-4c3d-11e7-9cd9-6709c5b61639.PNG)
Czy jestem jedyny który tak ma?

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/26942403-e39bb492-4c4f-11e7-8389-181a963203be.PNG)

**Comment by xxcriticxx** [comment]
dziala jak wyloncze adbypasser i aak-cont

![capture](https://user-images.githubusercontent.com/15007183/26942577-8c594554-4c50-11e7-8460-c2d540739dc3.PNG)

**Comment by adreporter** [comment]
@xxcriticxx Masz polski adres IP?

**Comment by xxcriticxx** [comment]
mam usa ip

**Comment by adreporter** [comment]
Rozumiem. 
Chciałbym aby ktoś z polskim IP mieszkający w Polsce zobaczył ten link.

**Comment by xxcriticxx** [comment]
maybe twoj isp filtruje cos

**Comment by adreporter** [comment]
Nie wiem. Mógłbyś proszę odświeżyć ten link kilka razy i napisać mi czy za każdym razem Ci się wyświetla?

**Comment by xxcriticxx** [comment]
co sie wyswietla?

**Comment by MajkiIT** [comment]
Ja mam tak samo jak @xxcriticxx.
@adreporter może sprawdź inną przeglądarkę

**Comment by xxcriticxx** [comment]
ja sprawdzalem na chromie i foxie i jest to samo

**Comment by gzenio22** [comment]
Opera polskie IP ta sama bajka
![shu_gvqzzm](https://user-images.githubusercontent.com/21177361/26949794-906c81f6-4c9b-11e7-9779-359d08dfdb41.png)

**Comment by adreporter** [comment]
Czyli nie jestem jedyny, któremu się nie pokazuje link. Jestem ciekaw czy jest jakieś rozwiązanie.

**Comment by adreporter** [comment]
Niestety nie ma rozwiązania.
