### ISSUE TITLE
pfmrc.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2750]
strona przyciemniona chyba cookies 

http://pfmrc.eu/index.php?/topic/4882-gdzie-s%C4%85-sklepy-elektroniczne-w-warszawie/

**Comment by gzenio22** [comment]
Moze to? 

###document_modal

**Comment by xxcriticxx** [comment]
maybe @MajkiIT napewno sprawdzic

**Comment by MajkiIT** [comment]
@gzenio22 @xxcriticxx 
Dzięki jest ok.
