### ISSUE TITLE
allekoszyk.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2752]
" Korzystanie z naszej strony jest darmowe i utrzymujemy się wyłącznie z reklam. Proszę wyłącz adblock."

**Comment by gzenio22** [comment]
u mnie wyglada to tak 
![shu_gvqzzm](https://user-images.githubusercontent.com/21177361/26971561-f374374a-4d0d-11e7-990f-65328986010a.png)

**Comment by blocker999** [comment]
Też tak miałem do niedawna ale teraz odrazu przekierowuje mnie do komunikatu o adblocku, raczej to niepomyłka bo sprawdzałem to na kilku przeglądarkach z różnymi filtrami ale dobrze by było aby ktoś to potwierdził. 

![allekoszyk](https://user-images.githubusercontent.com/23176832/26972156-d5441512-4d10-11e7-8a99-d4fda59d6eb3.jpg)

**Comment by xxcriticxx** [comment]
cookies 

![capture](https://user-images.githubusercontent.com/15007183/26975316-45877a72-4ced-11e7-8691-2e24f227f751.PNG)

**Comment by xxcriticxx** [comment]
widze to samo co @gzenio22
