### ISSUE TITLE
filmik.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2757]
cos player zjadlo

http://filmik.tv/video/265222/ukryte-dzialania-hd-hidden-figures-2016-hd/

![capture](https://user-images.githubusercontent.com/15007183/27002887-388b3160-4dba-11e7-87a3-6003029ac6c8.PNG)

**Comment by F4z** [comment]
To oszustwo i reguła z KAD zjadła odtwarzacz.

![image](https://user-images.githubusercontent.com/11742596/27003212-be0f0b12-4df2-11e7-9d3e-2f7e48eea780.png)

**Comment by xxcriticxx** [comment]
ok zamykamy
