### ISSUE TITLE
Poradniazdrowie.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2760]
Hej mam tu wyskakujące okno jak zjeżdża się nizej komunikat zobacz tez 

Przykład : http://www.poradnikzdrowie.pl/zdrowie/choroby-pasozytnicze/pasozyty-przewodu-pokarmowego-objawy_39997.html

###slidebox To powinno pomoc sprawdzi ktos? :)

**Comment by xxcriticxx** [comment]
`poradnikzdrowie.pl###slidebox`
