### ISSUE TITLE
radioftb.net

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2767]
TYm razem nie podrzucam reklamy ale bug w filtrach (Nie wiem co nie gra dokladnie) ale jak mam aktywne ubo z filtrami to panel logowania znika  
![shu_kvpl2w](https://user-images.githubusercontent.com/21177361/27051997-810c8c9a-4fb8-11e7-988c-65a1f22c5491.png)

**Comment by xxcriticxx** [comment]
wylaczajac ubo te pola tez nie dzialaja

jest jeszcze to 

![capture1](https://user-images.githubusercontent.com/15007183/27052421-a3657c88-4f87-11e7-8bb5-5c65adab4ad7.PNG)
![capture2](https://user-images.githubusercontent.com/15007183/27052426-a59eca90-4f87-11e7-95af-9fffd30d4c5a.PNG)

**Comment by blocker999** [comment]
Dokładnie jest tak jak mówi @xxcriticxx 
a te ikonki sugerują że by posłuchać trzeba się zarejestrować lub zalogować, więc jeśli ci zależy na stronce to skontakyuj się z jej administacją, namiary masz w zakładce " reddakcja"

**Comment by gzenio22** [comment]
faktycznie mi sie cos po merdalo :( closed please
