### ISSUE TITLE
prostoomuzyce.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2769]
maybe

![capture](https://user-images.githubusercontent.com/15007183/27053439-593f30e6-4f8b-11e7-845f-aef5d28da1b3.PNG)

**Comment by gzenio22** [comment]
Na zamowienie prenumeraty 

###block-views-banery-block-2

i na froncie mam jakis grycan tiramisu i jakies pierdy ale to ktos inny musi obadac ja nie umiem zablokowac zmieniajacych sie bannerow

**Comment by xxcriticxx** [comment]
@gzenio22 jak podajesz to adres strony music byc bez adresu bendzie blkowac to globalnie
