### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by MrReevo** [MajkiIT/polish-ads-filter#2770]

**Comment by xxcriticxx** [comment]
?

**Comment by xxcriticxx** [comment]
test link:

https://film.wp.pl/89-mln-w-24-godziny-zwiastun-czarnej-pantery-w-pierwszej-trojce-najchetniej-ogladanych-zapowiedzi-disneya-wideo-6133096898881153a

mam ktos puste boxy z REKLAMA?

**Comment by MajkiIT** [comment]
@xxcriticxx niestety tak

**Comment by blocker999** [comment]
Potwierdzam a z wyłączonym tampermonkey mam nawet reklamy

**Comment by MajkiIT** [comment]
@F4z wspomożesz ?

**Comment by MajkiIT** [comment]
@blocker999 @xxcriticxx 
A sprawdzałeś CTRL+F5 ? Po tym problem znikł.

**Comment by F4z** [comment]
Możecie sprawdzić, czy to niczego nie psuje i ukrywa u Was te pozostałości po reklamach?
`wp.pl##div[class^="_"] > div[class^="_"]:has(:scope > img[class^="_"][src][alt="wp"])`

Ja na https://tech.wp.pl/ nada to widzę.

**Comment by MajkiIT** [comment]
@F4z Dzięki. Na moje oko jest OK. Możecie zerknąć u siebie ?

**Comment by blocker999** [comment]
@MajkiIT teraz jest ok ale wcześniej rzeczywiście były puste boxy, więc może zachwile coś zmienią, warto to monitorować.

**Comment by MajkiIT** [comment]
@blocker999 zobacz na link jaki wrzucił F4z

**Comment by xxcriticxx** [comment]
ja nic niemam nawet na test linku zniklo nawet filmy zaczely dzialac znowu. za godzine jestem na innym networku tam sprawdze i dam znac. 

</3 ulubiona strona

**Comment by blocker999** [comment]
Na na tech.wp raczej jest ok lecz na https://film.wp.pl/89-mln-w-24-godziny-zwiastun-czarnej-pantery-w-pierwszej-trojce-najchetniej-ogladanych-zapowiedzi-disneya-wideo-6133096898881153a

brak pierwszego filmiku.

![wp film](https://user-images.githubusercontent.com/23176832/27081914-ea9c9f08-5042-11e7-8c4a-9d776b477702.jpg)

**Comment by MajkiIT** [comment]
@blocker999 u jest ten filmik

**Comment by blocker999** [comment]
@MajkiIT mówisz o tym drugim, to dubel czy masz obydwa?.

**Comment by MajkiIT** [comment]
https://www.screencast.com/t/oQhJKUfPial

**Comment by blocker999** [comment]
Rzeczywiście przepraszam to umnie znowu coś w ustawieniach.

**Comment by xxcriticxx** [comment]
ok jestem na innym networku wszys5tko zapiernicza jak trzeba chlopaki z ulubionej strony jakies testy chyba robja

**Comment by gzenio22** [comment]
odziwo wszystko dziala bez problemu a juz sie balem Xd

**Comment by xxcriticxx** [comment]
zamykamy!

**Comment by MajkiIT** [comment]
@F4z @xxcriticxx @gzenio22 Mogę Was prosić abyście sprawdzili czy na głównej stronie pod Adblockiem macie reklamy?

**Comment by F4z** [comment]
U mnie są reklamy.
