### ISSUE TITLE
tvlinks.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2773]
Aby obejrzeć wybierz język i link z poniższej tabeli oraz wyłącz adblock.

http://www.tvlinks.pl/izombie/3x11-77/

**Comment by gzenio22** [comment]
Haslo? :O

**Comment by xxcriticxx** [comment]
seriale

**Comment by F4z** [comment]
Ten komunikat jest nawet jak wyłączysz blokowanie reklam.
Jak komuś przeszkadza to może go ukryć, na przykład taką regułą:
`tvlinks.pl##.content > .sub.header`
