### ISSUE TITLE
teletoonplus.pl problem Adguard.

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#2777]
Tak jak w temacie. Na Android mam filtrowanie dns i https oraz reguły @||s1-player5.cdntvn.pl i @@||tvn.adocean.pl . A na PC Edge i Adguard nie potrzebuję reguł. Android (+reguły) i PC (bez reguł), miniminiplus.pl chodzi bez problemu. Natomiast na teletoonplus.pl już są blokowane filmiki miłym znanym komunikatem. W opcjach filtrowania obu stron zauważyłem, że bazują na wspomnianych regułach, które wymagane są na Android, a na PC Edge z AG już nie. Nie wiem, jaką jeszcze regułę utworzyć, aby i teletoon działał.

**Comment by F4z** [comment]
Sprawdź dodatkowo te dwie:
`@@||teletoonplus.pl^$generichide`
`@@||tvn.adocean.pl/*ad.xml$xmlhttprequest,domain=teletoonplus.pl`

**Comment by seba2282** [comment]
To samo.

**Comment by F4z** [comment]
To samo, gdzie?
Na Androidzie, czy na PC z Edge?

Na Androidzie u mnie działa, tylko ja mam wyłączone filtrowanie DNS.
Możesz zamiast tej drugiej reguły sprawdzić tę:
`@@||tvn.adocean.pl/*ad.xml$domain=teletoonplus.pl`
chociaż to nie powinno mieć znaczenia, bo i tak masz dodane `@@||tvn.adocean.pl` ze względu na to, że korzystasz z filtrowania DNS.

Na Edge zaraz sprawdzę.

**Comment by F4z** [comment]
Na PC z Edge też działa u mnie.

**Comment by seba2282** [comment]
Na Edge i AG u ciebie działa ze wspomnianą regułą ? Nie miałem jak sprawdzić PC, ale Android  z DNS i bez te dwie reguły moje nie działają.

**Comment by seba2282** [comment]
Android na pewno u mnie bez zmian. Nie wiem jak z Edge, bo na razie na PC nie byłem. Wyłączyłem na chwilę DNS, ale to nic nie zmieniło. Dobrze, że Chrome na wiosnę trochę zmieni, zwłaszcza mobilny, to skończy się wtedy używanie wtyczek.

**Comment by seba2282** [comment]
Taki mały artykuł. To chyba gwóźdź do trumny Google i jego Chrome. 

http://www.rmf.fm/magazyn/news,9572,google-wprowadzi-oplaty-za-blokowanie-reklam.html

**Comment by F4z** [comment]
> Na Edge i AG u ciebie działa ze wspomnianą regułą ?

Tak, po dodaniu tych dwóch reguł:
`@@||teletoonplus.pl^$generichide`
`@@||tvn.adocean.pl/*ad.xml$domain=teletoonplus.pl`
działa zarówno na Edge, jak i na Androidzie. Obie platformy z Adguardem.

> Android na pewno u mnie bez zmian.

Jeśli się nie mylę, to korzystasz z prawie wszystkich list i szczerze mówiąc nie chce mi się ich wszystkich aktywować i sprawdzać.
Jak Ci się chce, to możesz po kolei wyłączać każdą i sprawdzać czy działa, a potem napisać, która lista sprawia problem, to wtedy sprawdzę.

> Taki mały artykuł. To chyba gwóźdź do trumny Google i jego Chrome.
http://www.rmf.fm/magazyn/news,9572,google-wprowadzi-oplaty-za-blokowanie-reklam.html

Z tego co wiem, to działa na podobnej zasadzie jak inne blokady adblocków i da się to obejść 😃

**Comment by seba2282** [comment]
Krótko, u mnie na wstępie wykryto adblockera w playerze. Może to wina jakiegoś filtra, ale pogłowię się przy chwili, jak będę na PC i Edge. Na  Android nie wiem też jak to uszczypnąć. Ale przy włączonym dns reklamy są lepiej filtrowane. A https na Android chyba masz też włączony, bo to potrzebne, aby wywalać reklamy na https. Szkoda, że jest rozdzielone na http i https. Mogłoby być razem.
