### ISSUE TITLE
intel.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#278]
cookies trzeba naprawic strona jest cala biala

http://www.intel.pl/content/www/pl/pl/architecture-and-technology/connect-mobile-device-tv-wireless.html

Informacja o plikach cookie na tej witrynie:
Niniejszy portal wykorzystuje pliki cookie w celach funkcjonalnych, analitycznych i reklamowych opisanych w naszej Informacji o stosowaniu plików cookie i podobnych technologii. Nasze Narzędzie do akceptacji plików cookie zawiera informacje o plikach cookie, których używamy, i umożliwia ustawienie preferencji. Jeżeli wyrażają Państwo zgodę na wykorzystanie przez nas plików cookie, prosimy o dalsze korzystanie z naszego portalu.

**Comment by MajkiIT** [comment]
nic takiego nie ma.

**Comment by xxcriticxx** [comment]
strona pokazujie sie przez chwile potem robij sie cala biala

**Comment by mathew85** [comment]
U mnie też pusta. Nawet po wyłączeniu polskich filtrów. Działa ok bez adblocka.

**Comment by xxcriticxx** [comment]
MajkIT zobacz czy niema google logistics czasem
