### ISSUE TITLE
e-bajkidladzieci.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2789]
reklamy na player

http://e-bajkidladzieci.pl/liv-i-maddie/sezon-1-odcinek-20/

![capture](https://user-images.githubusercontent.com/15007183/27260408-8e185ed8-53f9-11e7-8bca-073ea3ab4a2f.PNG)

**Comment by F4z** [comment]
Sprawdź proszę tę regułę:
`anyfiles.pl##[id^="adsbox_"]`
