### ISSUE TITLE
domain name change 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2791]
@MajkiIT zamienisz na regexie 

http://filiser.pl/ = https://fili.tv/

@F4z  cos player nie dziala lookniesz please 
 
https://fili.tv/film/dziki-cel-2010/9398

**Comment by MajkiIT** [comment]
@xxcriticxx regex zmieniony
Player się zakorkował przez AAK-Cont

**Comment by xxcriticxx** [comment]
ok napisze tam
