### ISSUE TITLE
bzwbk.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2806]
2 x powiadomienia od wbk oraz ciasteczka.

**Comment by xxcriticxx** [comment]
nic niemam o ciasteczkach mam zato 2x powiadomenia o ofertach i ten script mozna bylo zablokowac

**Comment by MajkiIT** [comment]
`||cdn.pushwoosh.com/webpush/*.js$script`
`bzwbk.pl###pushwoosh-pop`
