### ISSUE TITLE
tczewska.pl

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#2807]
http://www.tczewska.pl/wiadomosci/14357,czytelnik-nie-uwzglednili-reklamacji-bo-za-mocno-w

`##[id*="reklama"]` ukrywa `<html>`, bo pasuje do `id="14357,czytelnik-nie-uwzglednili-reklamacji-bo-za-mocno-w-page"`

**Comment by MajkiIT** [comment]
Dzięki
