### ISSUE TITLE
drhtv.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2835]
@MajkiIT regexem by sie przydalo 

http://www.drhtv.com.pl/drhtv2.html

WLACZONY DODATEK 'ADBLOCK' MOZE BLOKOWAC DZIALANIE PLAYERA

**Comment by MajkiIT** [comment]
w co klikasz aby mieć popup ?

**Comment by xxcriticxx** [comment]
dzisaj niema ale jak dobrze pamietam to bylo cos pod play podlonczone 

wszystko zalezy jaki player

**Comment by hawkeye116477** [comment]
@xxcriticxx Jest dziadostwo.
![screenshot_20170802_232637](https://user-images.githubusercontent.com/19818572/28895780-0fcaa09a-77da-11e7-8d0a-7950cd5a63c4.png)

**Comment by hawkeye116477** [comment]
@xxcriticxx @MajkiIT  Jest dziadostwo.
![screenshot_20170802_232637](https://user-images.githubusercontent.com/19818572/28895780-0fcaa09a-77da-11e7-8d0a-7950cd5a63c4.png)

**Comment by MajkiIT** [comment]
No to close.
