### ISSUE TITLE
Opensubtitles.org

### ISSUE THREAD

**Issue by PrzemyslawKlys** [MajkiIT/polish-ads-filter#2839]
Hey,

Nie jest to do końca problem z waszymi filtrami, ale może dodacie jako "kolejny" pakiet filtrów. 

Znalazłem coś takiego, do adblocka i po wstępnych testach wygląda, że działa... 

https://help.getadblock.com/support/solutions/articles/6000140002-custom-filters-for-opensubtitles-org

Bez tego koszmarnie cokolwiek działa. Każde naciśnięcie ściągania, logowania, cokolwiek przekierowuje na strony z tyłka wzięte.

**Comment by blocker999** [comment]
Zainteresuj się filtrem KAD : 

https://github.com/azet12/KAD

**Comment by MajkiIT** [comment]
@blocker999 ale on nic nie wyłapuje.
