### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by kasper93** [MajkiIT/polish-ads-filter#2841]
Jakaś nowa akcja reklamowa.

```
wykop.pl##[id^=nivea]
wykop.pl##[id^=banner_rectangle]
```

**Comment by FX54** [comment]
Mnie wskoczyła dopiero po odblokowaniu blokady reklam.

**Comment by MajkiIT** [comment]
U mnie się to nie pojawia.

**Comment by xxcriticxx** [comment]
jeszcze nie widze ale napewno gdzies sie znajdzie dodac mozna

**Comment by kasper93** [comment]
Zniknęło dzisiaj. Może się akcja skończyła. Wydaje mi się, że można zamknąć temat na razie.

**Comment by kasper93** [comment]
Otwieram :)

`banner_rectangle` i `screening-displace` czasem się pojawiają, Warto dodać. Dwa ostatnie filtry naprawiają "wykopowe urwisko". Tam zawsze pierwszy element to reklama, ale kolejne (o ile są) to normalne znaleziska. Te dwa style to trochę hack na to, że po ukryciu pierwszego nie przełączamy na inne. Banalnie prosto to naprawić w JS, ale w CSS to trochę zabawa. Ogólnie działa to tak, że jeżeli są inne elementy to pokaże ten ostatni (bo tylko tak się da w css to zrobić, nie można skoczyć do poprzedniego siblinga to później jest problem z ukryciem tego który pokazaliśmy). Jedyny efekt uboczny to taki, że strzałka w prawo nie zawija do pierwszego elementu jak jesteśmy na ostatnim. mało istotne. Reszta działa poprawnie.

```
wykop.pl##.screening-displace
wykop.pl##[id^=banner_rectangle]
wykop.pl###dyingLinksBox > .dying-links[hidden] ~ .dying-links:last-child:style(display:list-item !important)
wykop.pl###dyingLinksBox > .dying-links[hidden] ~ .dying-links[style="display: list-item;"] ~ .dying-links:style(display: none !important)
```

**Comment by MajkiIT** [comment]
@kasper93 szacun 👍  . Ty znasz dobrze JS?

**Comment by kasper93** [comment]
Wystarczająco dobrze, żeby coś sobie w nim napisać, ale ekspertem nie jestem.

**Comment by xxcriticxx** [comment]
@kasper93 

@MajkiIT napewno ciebie to czegos zatrudni

**Comment by MajkiIT** [comment]
@kasper93 to może podziałamy z JS jako dodatki do filtrów?
