### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by FX54** [MajkiIT/polish-ads-filter#2842]
![obraz](https://user-images.githubusercontent.com/29596321/27530770-6230f4a8-5a5a-11e7-8b69-6b8a5f521902.png)

Można rozbudować filtr na brak reklamowego tła o blokowanie samego zdjęcia mimo że to base64?

Opcja z przekolorowywaniem przycisków nie zdaje rezulatów - za dużo koloruje bez doprecyzowania i działa tylko kolorowanie text-shadow (obramowanie, nie udało mi się osiągnąć czegoś lepszego).

Jakoś nie widzi mi się pamiętać by zmieniać kolor domyślny tła w przeglądarce na kolor pośredni (np. szary).

---

Inne rozwiązanie:
```
html {
    background: #efefef repeat-y url(../../img/skin_green/page-background.png) center;
    background-attachment: fixed;
}
```
Jak dla elementu [html] włączymy blokowanie tła to wraca jasnoszare tło i przyciski są czytelniejsze.

[html]: https://css-tricks.com/html-vs-body-in-css/ "off-topic"

**Comment by xxcriticxx** [comment]
Access to the following site has been blocked:
dobreprogramy.pl
If you have an ongoing use for this website, please ask the owner of the Pi-hole in your network to have it whitelisted.
This page is blocked because it is explicitly contained within the following block list(s):

list.27.hosts-file.net.domains 
list.preEventHorizon

**Comment by MajkiIT** [comment]
@FX54 Filtry nie umożliwiają podmianę htmla. Trzebaby to ogarnąć skryptem.

**Comment by xxcriticxx** [comment]
@MajkiIT moze @FX54 by sie wziol za napsanie scriptu dla nas

**Comment by MajkiIT** [comment]
No jeśli chce to czemu nie. Bardzo chętnie skorzystamy.

**Comment by FX54** [comment]
https://github.com/FX54/polish-ads-filter/commit/733c2a905a0e5d378ec29d4afc87839fd9e77181?diff=split

Może coś takiego wystarczy, na Operze działa ok poza jednym motywem dostępnym dla zalogowanych (jakiś dodatkowy element).

Dziwi mnie że nagle wtedy są różnie wykrywane filtry użyte (skacze od 102 do 105 a nic się nie aktualizuje) - wyłączam testowo podpięty właściwy filtr.
Jak nie wyłączę to dla właściwego mam 1 i najczęściej dla testowego liczba wynosi 103).

**Comment by MajkiIT** [comment]
@FX54 Dzięki sprawdzę

**Comment by PrzemyslawKlys** [comment]
Ja mam dzisiaj pustą stronę. Z poziomu facebooka wchodzę w artykuł -> https://www.dobreprogramy.pl/Atak-ransomware-ofiary-pozbawione-mozliwosci-odszyfrowania-danych,News,81882.html 
![image](https://user-images.githubusercontent.com/15063294/27640273-17c59d36-5c19-11e7-855f-8419a29369db.png)

Jak się wyłączy to jest ok

![image](https://user-images.githubusercontent.com/15063294/27640293-2a186fc2-5c19-11e7-9b08-c47fa05838c9.png)

**Comment by MajkiIT** [comment]
@FX54 po dodaniu reguły `dobreprogramy.pl##body#top:style(background-image: none !important;)` tło jest klikalne i kieruję na reklamę.

**Comment by PrzemyslawKlys** [comment]
Ja tam zawsze mam pustą stronę.

**Comment by MajkiIT** [comment]
@xxcriticxx sprawdzisz u siebie ?

**Comment by PrzemyslawKlys** [comment]
Wygląda na to, że https://raw.githubusercontent.com/azet12/PopupBlocker/master/PPB.txt odpowiada za moj problem. Sorry.

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/27745008-c73e2acc-5d8f-11e7-817b-d6ca2c776a36.PNG)

**Comment by blocker999** [comment]
Poprawione, ale na przyszłość proszę to zgłaszać bezpośrednio domnie:

https://github.com/azet12/PopupBlocker/issues

**Comment by FX54** [comment]
Można zamknąć aż znów nie będzie białych przycisków logowania, na białym tle po unieszkodliwieniu reklamy.

**Comment by F4z** [comment]
W niektórych miejscach nadal te przyciski do logowania/rejestracji są niewidoczne, na przykład tu - https://www.dobreprogramy.pl/Znasz-kogos-komu-przydalby-sie-serwer-w-chmurze-Konkurs-trwa,News,81111.html

Myślę, że zmiana tej reguły - `dobreprogramy.pl##body#top:style(background: none !important;)`
na tę - `dobreprogramy.pl##body#top:style(background-image: none!important;)` - to dobry pomysł, zaraz to poprawię.
