### ISSUE TITLE
downloadmoreram.com

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2843]
zablokowac to scierwo chyba trzeba w KAD

**Comment by FX54** [comment]
Zgłoszone przez https://azet12.github.io/KAD/informacje.html

**Comment by MajkiIT** [comment]
@gzenio22 mam zgłosić czy co bo nie rozumiem?

**Comment by gzenio22** [comment]
Chyba tak to mi wali wirusem przeciez nie da sie pobrac 32 GB ramu z internetu i z ubgrejdowac PC XD

**Comment by azet12** [comment]
Na dole strony jest:
`This isn't a scam, there isn't a virus, it's just a joke website. Made in jest, keep smiling`

Ale i tak przetestowałem - nic złego witryna nie robi.
