### ISSUE TITLE
https://www.wp.pl/ - reklamy przy pierwszym wejściu na stronę

### ISSUE THREAD

**Issue by takenek** [MajkiIT/polish-ads-filter#2844]
Cześć,
Wyczyśćcie cache przeglądarki wejdźcie na www.wp.pl i będzie od groma reklam.
Co ciekawe przy drugim wejściu reklam już nie ma... 
Mam ustawionego CCleanera, że przy wyjściu z przeglądarki czyści cały cache itp i za każdym razem jak wchodzę na www.wp.pl za pierwszym razem mam od groma reklam. Wystarczy stronę "odświeżyć" i reklamy giną.
Pozdrawiam

**Comment by takenek** [comment]
![image](https://user-images.githubusercontent.com/4953735/27537906-0bf76f56-5a76-11e7-9f61-399e1c73c868.png)

Po odświeżeniu tej samej strony:
![image](https://user-images.githubusercontent.com/4953735/27537918-199cb224-5a76-11e7-81e2-8826df9e58ae.png)

**Comment by xxcriticxx** [comment]
@takenek podaj jaki masz setup please?

**Comment by gzenio22** [comment]
To fakt kolega ma racje ale tego sie chyba przeskoczyc nie da

**Comment by takenek** [comment]
uBlock Origin z filtrami polskimi.
Ale testowałem u kolegi i dokładnie to samo jest - to nie wina setupa mojego tylko jakaś magia na wp.pl.

**Comment by MajkiIT** [comment]
@takenek a wyłącz na chwile czyszczenie cache przeglądarki i wtedy sprawdź.

**Comment by takenek** [comment]
Oczywiście reklamy się nie pokazują.

**Comment by xxcriticxx** [comment]
@takenek ta reklama sie pokazuje z wlonczonimy filtrami?

**Comment by takenek** [comment]
Reklama pokazuje się tylko za pierwszym razem jak kliknę przycisk odśwież stronę bądź kliknę przycisk na klawiaturze "F5" to reklamy giną, więc filtry są włączone.
Aby nie było, inne strony działają poprawnie tylko www.wp.pl za pierwszym razem pokazuje reklamy.

**Comment by FX54** [comment]
Sprawdź jak w trybie incognito / prywatnym (zezwól uBlockowi na pracę w trybie prywatnym - Chromowate np. Opera 15+).

**Comment by takenek** [comment]
No to ciekawy przypadek - w Incognito nie wyskakują mi te reklamy....

**Comment by FX54** [comment]
Możesz zrobić też kopie kodu strony z opcji "pokaż źródło strony" i wkleić np. na [wklej.org](http://wklej.org).

---

- https://support.google.com/chrome/answer/2364824&hl=pl
- https://support.mozilla.org/pl/kb/zarzadzanie-profilami

Spróbuj zrobić nowy profil i w nim zainstalować obecnie posiadane dodatki.

**Comment by takenek** [comment]
Z jakiegoś powodu przestała mi wyskakiwać ta reklama....
Jak znów się pojawi to otworze to zgłoszenie i umieszczę kod strony.
