### ISSUE TITLE
mojadieta.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2845]
![capture](https://user-images.githubusercontent.com/15007183/27556504-d6b63b8e-5a83-11e7-94ad-6be7500c2bdc.PNG)

**Comment by gzenio22** [comment]
moze byc?

mojadieta.pl###text-5

Nie wiem czy dobrze link wkleilem nie umiem jeszcze tego albo nie ogarniam raczej

**Comment by MajkiIT** [comment]
@gzenio22 jest Git.
