### ISSUE TITLE
ulubiona strona notification 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2851]
![capture](https://user-images.githubusercontent.com/15007183/27608027-e95844aa-5b53-11e7-8815-b065a8451eef.PNG)

**Comment by gzenio22** [comment]
tego blokowac jeszcze sie nie nauczylem

**Comment by hawkeye116477** [comment]
Na konkretnie tą stronę jak na razie nie znalazłem rozwiązania, ale wiem jak zablokować powiadomienia na wszystkich stronach.
Firefox: wpisz do paska adresu about:config, znajdź dom.push.enabled, ustaw to na false i sprawa załatwiona, na wszystkich stronach nie będzie powiadomień.
Chrome/Chromium/Vivaldi - wpisz do paska adresu chrome://settings/content/notifications, przełącz na zablokowane i sprawa załatwiona, na wszystkich stronach nie będzie powiadomień.

**Comment by hawkeye116477** [comment]
@MajkiIT @xxcriticxx Znalazłem dziadostwo: `||www.wp.pl/sw.js$script,domain=behind-the-scene` . A tak właściwie, to nie wiem czy to dobrze, że tak to dodajesz do głównego fitlra. Może od powiadomień powinien być osobny filtr, bo może komuś się to przydaje.

**Comment by MajkiIT** [comment]
@hawkeye116477 wow szacun. No może i masz rację, ale obecnie nikt się na to nie skarżył. Jeśli trzeba to się to wydzieli.

**Comment by MajkiIT** [comment]
@hawkeye116477 wykrakałeś
```

Jeśli dobrze się doszukałem to obsługjecie listę Adblocka: https://github.com/MajkiIT/polish-ads-filter Jakiś czas temu trafiła na listę nasza domena za webpushe, nie do końca rozumiem tej polityki skoro user może jawnie nie zgodzić się ale ok. Gorsze dla nas i naszych klientów, że przez wycięcie webpushy została wycięta cała funkcjonalność którą udostępniamy np chat, promocje koszykowe, kupony rabatowe, itp.
Pytanie czy jeśli podeślemy jak zablokować webpushe z naszego systemu możemy liczyć podmianę reguły?
```

**Comment by hawkeye116477** [comment]
@MajkiIT Widzisz, miałem rację, czyli robimy kolejny filtr "polskie filtry powiadomień typu web push" :smiley:
