### ISSUE TITLE
Czy jestem jedyny?

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#2852]
https://portal.abczdrowie.pl/pytania/skutki-picia-octu-spirytusowego
Wy też nie możecie obejrzeć filmiku?

**Comment by FX54** [comment]
Nie mogę z użyciem AAK-Cont (Opera / Firefox) a Chrome nie aktualizuje się automatycznie to poleciał.

**Comment by MajkiIT** [comment]
@adreporter znowu coś zmienili. @xxcriticxx zgłosisz ?

**Comment by blocker999** [comment]
Chyba nietylko ten filmik ale wszystkie na podstronach wp mi niechodzą.

**Comment by xxcriticxx** [comment]
@MajkiIT 

@adreporter juz zglosil aad protector twierdzic ze dziala nie wiem czy bendzie fix

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki

**Comment by MajkiIT** [comment]
@adreporter 
Nastąpiła zmiana w https://jspenguin2017.github.io/uBlockProtector/

**Comment by xxcriticxx** [comment]
tak samo w aak-cont
