### ISSUE TITLE
mzkzg.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2853]
Cookies

**Comment by xxcriticxx** [comment]
`mzkzg.pl##.kom_polityka_prywatnosci`

podciagniecie strony by sie tez przydalo ale tego jeszcze w szkole nie uczyli

**Comment by MajkiIT** [comment]
to może coś takiego ?
`mzkzg.pl##[class^="kom_polityka_prywatnosci"]`
