### ISSUE TITLE
basic tutorial

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2855]
@MajkiIT by sie przydale jakies basic tutorial albo wiki how to dla nowych uzytkownikow

maybe by zaczelo nas wiecej tutaj dzialac/blokowac

to kiedy pierwsze lekcje angielskiego?

**Comment by MajkiIT** [comment]
How to jak blokować reklamy?

**Comment by xxcriticxx** [comment]
cos takiego i jak uzywac ubo i innych bajerow potem moze ad block blah blah

**Comment by MajkiIT** [comment]
Ok wieczorem coś wrzucę

**Comment by xxcriticxx** [comment]
@MajkiIT czekamy na twego pierwszego youtuba!

**Comment by gzenio22** [comment]
obejrze uważnie :)

**Comment by MajkiIT** [comment]
to może na chwilę obecną to wystarczy :)

http://www.serwisantka.pl/2017/03/jak-zablokowac-upierdliwe-reklamy-w-przegladarce.html

**Comment by xxcriticxx** [comment]
@MajkiIT lazy!

@MajkiIT zaprosimy Anie do nas?

**Comment by MajkiIT** [comment]
@xxcriticxx 
Jutro coś napiszę lub zrobię tutorial. I nie jestem lazy! 

@xxcriticxx no postaram się zaprosić.

**Comment by xxcriticxx** [comment]
mi chodzilo bardziej troche advance a nie takie basic 

example:

pokazac jak sie ubo logera uzywa
jak sie szuka nazw div
jak sie uzywa console tools

**Comment by MajkiIT** [comment]
ok

**Comment by xxcriticxx** [comment]
kazdy znas wie jak zamontowac ubo i dodac listy

**Comment by gzenio22** [comment]
ja sie serio chetnie po ucze bo do teraz nie wiem jak wy robicie takie krotkie reguly :D

**Comment by hawkeye116477** [comment]
Może tutorial jak zainstalować uBlock Protector Extension na Firefoksie?
1. Zainstaluj Chrome Store Foxified z https://addons.mozilla.org/pl/firefox/addon/chrome-store-foxified/ i zrestartuj Firefoxa.
2. Wejdź w about:config, znajdź xpinstall.signatures.required i ustaw na false.
3. Wejdź na https://chrome.google.com/webstore/detail/ublock-protector-extensio/ggolfgbegefeeoocgjbmkembbncoadlb i kliknij add to Firefox, a następnie save unsigned addon to file.
4. Przeciągnij zapisany plik xpi na pasek adresu i zgódź się na instalację.
5. Uruchom ponownie i ciesz się z działającego uBlock Protector Extension. Tylko pamiętaj, że twórca rozszerzenia nie udziela wsparcia dla Firefoksa.

Działa to poprawnie, dzięki niemu filmik odpala się na `https://wiadomosci.wp.pl/tvp-info-przekracza-kolejne-granice-zobaczcie-jak-nazwali-kontrmanifestantow-6142973419370113a`. 

Tylko tego rozwiązania wada jest taka, że pewnie jak wyjdzie update, to trzeba będzie pewnie te kroki powtórzyć. Można też te rozszerzenie wysłać do AMO, wtedy zostanie podpisane i będzie można pominąć krok 2.

**Comment by hawkeye116477** [comment]
@MajkiIT A może tutorial jak zainstalować uBlock Protector Extension na Firefoksie?
1. Zainstaluj Chrome Store Foxified z https://addons.mozilla.org/pl/firefox/addon/chrome-store-foxified/ i uruchom ponownie Firefoxa.
2. Wejdź w about:config, znajdź xpinstall.signatures.required i ustaw na false.
3. Wejdź na https://chrome.google.com/webstore/detail/ublock-protector-extensio/ggolfgbegefeeoocgjbmkembbncoadlb i kliknij add to Firefox, a następnie save unsigned addon to file.
4. Przeciągnij zapisany plik xpi na pasek adresu i zgódź się na instalację.
5. Uruchom ponownie Firefoksa i ciesz się z działającego uBlock Protector Extension. Tylko pamiętaj, że **twórca rozszerzenia nie udziela wsparcia dla Firefoksa**.

Działa to poprawnie, dzięki niemu filmik odpala się na `https://wiadomosci.wp.pl/tvp-info-przekracza-kolejne-granice-zobaczcie-jak-nazwali-kontrmanifestantow-6142973419370113a`, bez niego w ogóle nie rusza.  Ta strona --> https://blockadblock.com/ , również działa prawidłowo, nie wykrywa uBlocka. Tutaj też nie wykrywa uBlocka --> https://zrabatowani.pl/.

Tylko tego rozwiązania wada jest taka, że jak wyjdzie update, to trzeba będzie pewnie te kroki powtórzyć. Można też te rozszerzenie wysłać do AMO, wtedy zostanie podpisane i będzie można pominąć krok 2, ale do tego trzeba mieć oczywiście konto developera na AMO.
Zaleta tego jest taka, że jak jakaś strona nie działała z AAK Cont, a dali aktualizację. żeby działało na Protectorze, to można go zainstalować i nie czekać na aktualizację AAK Cont.

![screenshot_20170715_095336](https://user-images.githubusercontent.com/19818572/28237613-8cc01350-6943-11e7-8535-0a7d0eab49ca.png)

**Comment by xxcriticxx** [comment]
@hawkeye116477 maybe bys napisal cos to dodamy do wiki

**Comment by hawkeye116477** [comment]
Trochę poprawiłem. Nie wiem czy nie dopisać, że wszystko może nie dzialać. Gdyż część rzeczy jest chyba w EMCA Script 2017 i to chyba może nie dzialać, tzn. tak przynajmniej twierdzi twórca. Jednakże ostatnio czytałem, to pisało parę osób, że Protector na Foxie działa o niebo lepiej niż AAK Cont.
Trochę lipa z tym, bo jeśli pojawi się aktualizacja, to sama się nie zainstaluje. Ja chyba jednak spróbuję ułatwić ten proces i wykombinuję jakiś system aktualizacji, może przez GitHuba. Jeśli znajdzie się coś co działa na AAK Cont, a nie będzie na Protectorze, to najwyżej spróbuję przepisać to od AAK Cont i będzie gitara :smiley:

**Comment by xxcriticxx** [comment]
@hawkeye116477 możesz napisać na inny temat niż Ad protektor. Każdy How to się przyda!

**Comment by hawkeye116477** [comment]
Mam pytanie do znawców, co to znaczy: „Declining to grant rights under trademark law for use of some
trade names, trademarks, or service marks", jeśli robię forka to nazwę mogę zachować czy trzeba zmieniac?

**Comment by xxcriticxx** [comment]
jak dobrze rozumiem to chyba musisz zmienic zeby ciebie nikt nie oskarzal o prawa autorskie

**Comment by hawkeye116477** [comment]
Nie jestem tego do konća pewien, uBlock Origin ma tą samą licencję, a przygotował ktoś forka na Edge i nazwę rozszerzenia zostawił taką samą. 
https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4

Udało mi się przerobić Protectora bez pomocy Chrome Store Foxified, by działał na Foxie. Jeszcze tylko system aktualizacji. Tylko właśnie nie wiem co z nazwą czy mogę ją zachować czy lepiej zmienić na jakąś inną,np uBlock Defender.

**Comment by xxcriticxx** [comment]
@hawkeye116477 zmien na co chcesz project jest twoj

**Comment by hawkeye116477** [comment]
[uBlockProtector.zip](https://github.com/MajkiIT/polish-ads-filter/files/1162591/uBlockProtector.zip)
Kto chce może testować, na razie niepodpisane. Trzeba zmienić rozszerzenie na xpi, przeciągnąć na pasek adresu i wykonać pkt.2 z tamtego tutorialu.

**Comment by hawkeye116477** [comment]
Tadam, nawet już aktualizacje działają. Zostawiłem nazwę rozszerzenia taka jak była, w końcu to jest port dla Foxa. Jak na razie, to „kompiluję" rozszerzenie sam skryptem bez tego całego Travisa.

https://github.com/hawkeye116477/uBlockProtector/blob/master/xpi/uBlockProtector-10.146.xpi

**Comment by hawkeye116477** [comment]
Aktualizacje też działają, ale najwyraźniej to wszystko nie będzie takie proste.
https://github.com/hawkeye116477/uBlockProtector/issues/1

Chętnych do pomocy rozumiem, że nadal brak, więc chyba jednak zrezygnuję, skoro mogą być nawet jakieś problemy z bezpieczeństwem, jeśli dobrze zrozumiałem.

**Comment by hawkeye116477** [comment]
@MajkiIT @xxcriticxx A może poradnik jak zrobić, by wujek G nie zmieniał linków, jak się kliknie PPM?
Zainstaluj rozszerzenie Google Search Link Fix 
Firefox: https://addons.mozilla.org/pl/firefox/addon/google-search-link-fix/
Chrome/Chromium/Vivaldi: https://chrome.google.com/webstore/detail/google-search-link-fix/cekfddagaicikmgoheekchngpadahmlf
(Chr)Opera: https://addons.opera.com/pl/extensions/details/google-search-link-fix/?display=en

Mogę też napisać jak zablokować reklamy w Skype.

**Comment by MajkiIT** [comment]
@hawkeye116477 
Pierwszy temat to blokowanie prywatności. Zawsze się można tym zająć.
Drugi temat bardziej bym uderzył w blokowanie za pomocą DNSa.

**Comment by hawkeye116477** [comment]
@MajkiIT Wiki zaktualizowane. 
https://github.com/MajkiIT/polish-ads-filter/wiki

**Comment by hawkeye116477** [comment]
@MajkiIT https://github.com/MajkiIT/polish-ads-filter/wiki/Jak-zapobiec-zamienianiu-link%C3%B3w-przez-Google-przy-klikni%C4%99ciu-PPM%3F
Dodałem też na głównej stronie wiki link do tutorialu „Jak zablokować i usunąć reklamy w Skype 7 na Windowsie?".

**Comment by hawkeye116477** [comment]
@MajkiIT Ewentualnie można trochę przerobić ten tutorial. W 1 części zamiast wchodzić w opcje internetowe, można znaleźć plik hosts i dopisać na końcu w nowej pustej linii: `127.0.0.1 apps.skype.com`, a potem zapisać. A co do drugiej części, to chyba jest ok.

**Comment by MajkiIT** [comment]
@hawkeye116477 dzięki

**Comment by hawkeye116477** [comment]
@MajkiIT A może coś o blokowaniu reklam na Andku?
Pisałeś już o zestawie Firefox+uBlock, ale jest jeszcze zestaw Yandex Browser+Adguard Content Blocker. Adguarda też można zainstalować jako samodzielną aplikację, ale wtedy działa tylko za free przez pewien czas. Jest jeszcze dla niego darmowa alternatywa open-source - Blokada: http://blokada.org/pl/index.html.
Są jeszcze nawet przecież przeglądarki z wbudowanym adblokerem, jak np. Brave (przeglądarka byłego CEO Mozilli). W Chrome Dev też jest wbudowany adbloker.
A dla zrootowanych urządzeń jest Adaway.

**Nie wiem tylko czemu na wp.pl Yandex+Adguard nie blokuje reklam.**

**Comment by hawkeye116477** [comment]
@MajkiIT Odkryłem inny zestaw. Yandex pozwala na instalację rozszerzeń z Chrome i Opery, jednak twierdzi, że uBlock Origin nie jest obsługiwany, ale można go oszukać (tylko Beta i Alpha). Wystarczy tylko pobrać zipa uBlock Origin z githuba, rozpakować, potem wpisać do paska adresu: `chrome://extensions`, nacisnąć "Load unpacked extension", wskazać manifest.json z rozpakowanego uBlocka i gitara, uBlock Origin działa świetnie. Niestety uBlock Protector w ten sposób nie chce się zainstalować, Yandex podaje, że nie podoba mu się kładka w nazwie jednego folderu, można to zmienić, ale poda znowu, że z tą wersją niekompatybilny, też to można zmienić, ale na końcu się okaże, że i tak nie będzie działać. Ale można zainstalować normalnie ze sklepu Opery lub Chrome - Tampermonkey i do niego AAK Cont.
