### ISSUE TITLE
tygodniknarodowy.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2856]
resztki po reklamie 

![screenshot_1](https://user-images.githubusercontent.com/21177361/27644384-ab0d8c48-5c23-11e7-9784-00a1467069f9.png)

Rozwiązanie: tygodniknarodowy.pl###Process       Zamknij na dole
tygodniknarodowy.pl###sticky  bialy pasek po prawej u gory jak pokrecisz scrollem w dol strony

Ktos sprawdzi czy jest ok? :)

**Comment by MajkiIT** [comment]
A takie coś nie wystarczy?

`tygodniknarodowy.pl###BusyBox`
