### ISSUE TITLE
accorhotels.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2860]
https://www.accorhotels.com/pl/hotel-3383-novotel-warszawa-centrum/index.shtml

Dalsze przeglądanie tej strony jest różnoznaczne z wyrażeniem przez użytkownika zgody na wykorzystywanie plików cookie, których celem jest dostarczenie statystyk odnośnie przeglądania stron internetowych, ruchu generowanego przez osoby odwiedzające i zachowaniem podczas przeglądania, a także określenie spersonalizowanych usług i ofert dostosowanych do zainteresowań użytkownika, udostępnianie danych stronom trzecim oraz przekierowywanie użytkowników z serwisów stron trzecich. Aby dowiedzieć się więcej, kliknij tutaj.

**Comment by xxcriticxx** [comment]
https://www.accorhotels.com/pl/hotel-3385-mercure-warszawa-centrum/index.shtml

Dalsze przeglądanie tej strony jest różnoznaczne z wyrażeniem przez użytkownika zgody na wykorzystywanie plików cookie, których celem jest dostarczenie statystyk odnośnie przeglądania stron internetowych, ruchu generowanego przez osoby odwiedzające i zachowaniem podczas przeglądania, a także określenie spersonalizowanych usług i ofert dostosowanych do zainteresowań użytkownika, udostępnianie danych stronom trzecim oraz przekierowywanie użytkowników z serwisów stron trzecich. Aby dowiedzieć się więcej, kliknij tutaj.

**Comment by xxcriticxx** [comment]
http://www.ibis.com/pl/hotel-2894-ibis-warszawa-centrum-hostel-warszawa-centrum/index.shtml

Dalsze przeglądanie tej strony jest różnoznaczne z wyrażeniem przez użytkownika zgody na wykorzystywanie plików cookie, których celem jest dostarczenie statystyk odnośnie przeglądania stron internetowych, ruchu generowanego przez osoby odwiedzające i zachowaniem podczas przeglądania, a także określenie spersonalizowanych usług i ofert dostosowanych do zainteresowań użytkownika, udostępnianie danych stronom trzecim oraz przekierowywanie użytkowników z serwisów stron trzecich. Aby dowiedzieć się więcej, kliknij tutaj.

**Comment by xxcriticxx** [comment]
https://www.accorhotels.com/pl/polska/index.shtml

Dalsze przeglądanie tej strony jest różnoznaczne z wyrażeniem przez użytkownika zgody na wykorzystywanie plików cookie, których celem jest dostarczenie statystyk odnośnie przeglądania stron internetowych, ruchu generowanego przez osoby odwiedzające i zachowaniem podczas przeglądania, a także określenie spersonalizowanych usług i ofert dostosowanych do zainteresowań użytkownika, udostępnianie danych stronom trzecim oraz przekierowywanie użytkowników z serwisów stron trzecich. Aby dowiedzieć się więcej, kliknij tutaj.

**Comment by xxcriticxx** [comment]
list of domains 

![capture](https://user-images.githubusercontent.com/15007183/27802499-1be58a34-5ff2-11e7-9ce9-e25612e35317.PNG)

**Comment by hawkeye116477** [comment]
`com##.is-ready.is-shown.cnil-banner`
