### ISSUE TITLE
wp.tv

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#2868]
http://wp.tv/i,prognoza-pogody-na-17-lutego,mid,1997971,cid,2303759,klip.html
Panowie, dałoby się naprawić odtwarzacz jakimiś regułami?

**Comment by MajkiIT** [comment]
Niestety nie. Tutaj tylko skrypty.

**Comment by xxcriticxx** [comment]
podane dla ad protectora

**Comment by kasper93** [comment]
Ograniczcie ten filtr tylko do skryptów, albo chociaż do nie xhrów. I będzie działać. 

```
/:\/\/(?!biuropodrozy)(?!mistrzowiebezpieczenstwa)(?!prezentownik)(?!nowapoczta)(?!swiecsie)(?!swieta)(?!websocket)(?!liveblog)(?!relacje)(?!opinie)(?!zalacznik)(?!magazyn)(?!newsletter)(?!facet)(?!wyleczto)(?!kuchnia)(?!film)(?!moto)(?!gwiazdy)(?!teleshow)(?!finanse)(?!kobieta)(?!dom)(?!pogoda)(?!tech)(?!historia)(?!czat)(?!ksiazki)(?!gryonline)(?!hotele)(?!narty)(?!samoloty)(?!wycieczki)(?!hosting)(?!irlandia)(?!multikurs)(?!casino)(?!foto)(?!tech)(?!www)(?!stg)(?!doladowania)(?!fantasyliga)(?!funduszeue)(?!imperiumstylu)(?!kodyrabatowe)(?!alefolwark)(?!angielski)(?!arenamody)(?!beniamin)(?!bon)(?!bsg)(?!casino)(?!diety)(?!dlaprasy)(?!dlugi)(?!doladowania)(?!dom)(?!dysk)(?!ebiznes)(?!ebooki)(?!empire)(?!fantasyliga)(?!film)(?!fundusze)(?!ogloszenia)(?!orangekinoletnie)(?!rekrutacja)(?!rycerzeiksiezniczki)(?!speedwaymanager)(?!sportowefakty)(?!sportowybar)(?!talesofmagic)(?!ubezpieczenia)(?!warofdragons)(?!wiadomosci)(?!gazetki)(?!gry)(?!horoskop)(?!kalendarz)(?!katalog)(?!khanwars)(?!komiks)(?!konflikty)(?!kontakty)(?!korsarze)(?!kultura)(?!mini)(?!mmho)(?!mobilna)(?!morizon)(?!moto)(?!muzyka)(?!narty)(?!naryby)(?!onas)(?!orangekinoletnie)(?!piraci)(?!poczta)(?!pomoc)(?!praca)(?!profil)(?!programtv)(?!pytamy)(?!rekrutacja)(?!rss)(?!rtvagd)(?!rycerzeiksiezniczki)(?!smeet)(?!speedwaymanager)(?!szkola)(?!szukaj)(?!tech)(?!teleshow)(?!triviador)(?!turystyka)(?!twojeip)(?!ulubiency)(?!warodfragons)(?!wycieczki)(?!zdrowie)(?!zoomumba)(?!topnews)(?!erotyka)(?!dzieci)(?!fitness)(?!gielda)(?!finansomat)(?!biznes)(?!sport)[a-zA-Z0-9]{4,9}\.wp\.pl\/.{200,}/$script
```

**Comment by MajkiIT** [comment]
Niestety bez zmian.

**Comment by kasper93** [comment]
Bo dwa razy jest ten sam filtr na liście. Poprawiłeś w jednym miejscu, a tutaj jeszcze zostało https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock.txt#L1759

**Comment by kasper93** [comment]
Teraz też, nie zadziała. Bo pomysł był, żeby nie blokować xmlhttprequest. Bo i tak nie ładuje reklam wtedy.

**Comment by MajkiIT** [comment]
Już poprawiłem.

**Comment by MajkiIT** [comment]
@kasper93 jeszcze raz dziękuję.

**Comment by adreporter** [comment]
@MajkiIT @F4z @xxcriticxx @kasper93 @hawkeye116477
http://wp.tv/i,prognoza-pogody-na-17-lutego,mid,1997971,cid,2303759,klip.html
Panowie, proszę odtwórzcie filmik od mniej więcej połowy. Też macie problemy z odtwarzaczem?

**Comment by adreporter** [comment]
Już myślałem, że jestem jedyny. A jednak https://github.com/jspenguin2017/uBlockProtector/issues/52#issuecomment-316768426

**Comment by adreporter** [comment]
Teraz ja to mam tak, że filmik zatrzymuje się po 7 sekundach.

**Comment by kasper93** [comment]
Można by przewrócić blokowanie xhr tylko przekierować na pusty plik `$xmlhttprequest,redirect=nooptext` Naprawia to odtwarzanie, co prawda nadal jest problem bo się blokują kontrolki, ale lepiej niż nic nie wyświetlać. Nie chce mi się ich skryptów czytać, bo pewnie da się to jakoś sprytnie ominąć.
