### ISSUE TITLE
euro.com.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2869]
KAD blokuje wejscie na RTV euroagd

Test link: https://www.euro.com.pl/procesory/amd-a10-7870k-3-9-ghz-4mb-.bhtml?utm_source=2466193%7Cconvertiser.com&utm_medium=TradeDoubler&utm_campaign=%28TradeDoubler%29&utm_content=%2Fclick%3Fp%28118512%29a%282466193%29g%2818030892%29url%28https%253A%252F%252Fwww.euro.com.pl%252Fprocesory%252Famd-a10-7870k-3-9-ghz-4mb-.bhtml%29epi%282fb7690b519a0b589ebed5ae41f437b0-2706%29

**Comment by xxcriticxx** [comment]
umnie jest ok i mam kad wlonczone 

![capture](https://user-images.githubusercontent.com/15007183/27761756-8e0a44e2-5e30-11e7-8618-2a94f43849a8.PNG)

**Comment by gzenio22** [comment]
http://bit.ly/2sxx98z

A teraz?

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/27762699-f0e979d4-5e44-11e7-99ba-1d6f095c718a.PNG)

**Comment by MajkiIT** [comment]
ale to nie KAD :)

**Comment by gzenio22** [comment]
A co to jest? Cos z filtrow napewno

**Comment by xxcriticxx** [comment]
@gzenio22 peter loews host file toc masz podane na niebieszko

**Comment by gzenio22** [comment]
@xxcriticxx Mogl bys mu to zglosic?

**Comment by MajkiIT** [comment]
ale to normalne. Wątpię aby usunął regułę
