### ISSUE TITLE
twojeapteki.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2871]
cookies

Strona używa ciasteczek (cookies). Korzystając ze strony wyrażasz zgodę na używanie cookies, zgodnie z aktualnymi ustawieniami przeglądarki. Czytaj więcej. - OK, zamknij

**Comment by hawkeye116477** [comment]
`www.twojeapteki.com##body > div:nth-of-type(4)`
