### ISSUE TITLE
tygodnikpowszechny.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2876]
![capture](https://user-images.githubusercontent.com/15007183/27763722-1ff7a69e-5e57-11e7-9de4-3d0798b28be0.PNG)
![capture1](https://user-images.githubusercontent.com/15007183/27763723-2293cd06-5e57-11e7-8ae7-e1056e0da6a9.PNG)

**Comment by MajkiIT** [comment]
Ja tego nie widzę ...

**Comment by xxcriticxx** [comment]
ja mam jakies resztki 
 jedna jest na topie druga srodek prawa strona

**Comment by gzenio22** [comment]
gora www.tygodnikpowszechny.pl###block-views-simpleads-block-example-block > h2
prawa strona tygodnikpowszechny.pl###block-views-simpleads-block-example-block-1 > h2

**Comment by MajkiIT** [comment]
Uprościmy to trochę

`www.tygodnikpowszechny.pl##[id*="-simpleads-"] > h2`
