### ISSUE TITLE
zory.dlawas.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2883]
cookies

W ramach naszej witryny stosujemy pliki cookies w celu świadczenia Państwu usług na najwyższym poziomie. Korzystanie z witryny bez zmiany ustawień dotyczących cookies oznacza, że będą one zamieszczane w Państwa urządzeniu końcowym. Więcej informacji o wykorzystaniu plików cookies znajdą Państwo na stronie z regulaminem.

**Comment by hawkeye116477** [comment]
Na komunikat o ciastkach powinno pomóc: `zory.dlawas.pl###popupDiv`
A to filtry na tą zamykaną reklamę: ```
zory.dlawas.pl##.modal-dialog
zory.dlawas.pl##.in.fade.modal-backdrop
```
![reklama](https://user-images.githubusercontent.com/19818572/27997756-8c54dd44-64ff-11e7-8079-96db3787827c.png)
