### ISSUE TITLE
radiopoznan.fm

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2885]
cookies

 POLITYKA PRYWATNOŚCI radiopoznan.fm

W ramach naszych serwisów internetowych stosujemy pliki cookies. Używamy cookies, żeby zrozumieć, w jaki sposób użytkownicy korzystają z witryny i  dostosować ją tak, aby korzystanie z niej było dla niech przyjemniejsze i ciekawsze. Stosujemy cookies także w celach reklamowych i statystycznych. Cookies mogą być również stosowane przez współpracujących z nami reklamodawców oraz przez firmy badawcze.

W każdej chwili mogą Państwo zmienić swoje ustawienia dotyczące cookies. Korzystanie z naszych serwisów internetowych bez zmiany ustawień dotyczących cookies oznacza, że będą one zamieszczone w Państwa urządzeniu końcowym. Szczegółowe informacje dotyczące stosowania cookies, w tym możliwość dokonania zmiany ustawień w zakresie cookies znajdą Państwo w naszej "POLITYCE PRYWATNOŚCI"

**Comment by hawkeye116477** [comment]
`||radiopoznan.fm/v2/js/javascripts.js`

**Comment by F4z** [comment]
Wygląda na to, że ta reguła popsuła działanie strony.
Jak się kliknie w przycisk "PROGRAM" to powinno wyświetlać się menu, a tak się nie dzieje, oprócz tego przewijanie zdjęć w galerii nie działa.
Link - http://radiopoznan.fm/informacje/pozostale/czysciciel-kamienic-w-poznaniu

![image](https://user-images.githubusercontent.com/11742596/28239664-f88c2604-6971-11e7-92e3-fe9e7268ad29.png)

![image](https://user-images.githubusercontent.com/11742596/28239671-08aa47f0-6972-11e7-83e8-3104f3c6e569.png)

Może lepiej będzie tak:
`||radiopoznan.fm//homepage/privacyPolicy`
ewentualnie reguła kosmetyczna
`radiopoznan.fm###privacyPolicyBox`

**Comment by hawkeye116477** [comment]
Potwierdzam, mój błąd.

**Comment by MajkiIT** [comment]
@hawkeye116477 nie ma problemu. Każdy się myli.

**Comment by hawkeye116477** [comment]
@MajkiIT To już jest w najnowszym commitcie, powinienem napisać #2885 zamiast #2855, nastąpiła drobna pomyłka z mojej strony, także sorry.

**Comment by xxcriticxx** [comment]
@hawkeye116477 mowilem ze bylo na szybkiego

**Comment by hawkeye116477** [comment]
@xxcriticxx Oj tam, tylko 2 błędy, ale to tylko w commit message, reguły są rzecz jasna poprawne 😛

**Comment by MajkiIT** [comment]
@hawkeye116477 luzik nie ma problemu.
