### ISSUE TITLE
www.vectra.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#289]
cookies

W ramach naszej witryny stosujemy pliki cookies w celu świadczenia Państwu usług na najwyższym poziomie dostosowując serwis do Państwa indywidualnych potrzeb. Korzystanie z witryny bez zmiany ustawień dotyczących cookies oznacza, że będą one zamieszczane w Państwa urządzeniu końcowym. W każdym momencie możecie Państwo dokonać zmiany ustawień dotyczących cookies. Więcej szczegółów w naszej "Polityce Cookies".

**Comment by MajkiIT** [comment]
element jest blokowany.

**Comment by xxcriticxx** [comment]
jak zrobic zeby filtry sie nie przycinaly?

**Comment by MajkiIT** [comment]
zdefiniuj słowo przycinały..

**Comment by xxcriticxx** [comment]
jak zaladowalem pierwszy raz strone vectra pokazal mi sie napis o cookies tak jak bym niemial filtrow zrobilem refresh i tak jak pisales element jest blokowany

**Comment by MajkiIT** [comment]
używasz ublocka?

**Comment by xxcriticxx** [comment]
tak

**Comment by xxcriticxx** [comment]
masz jakiś pomysł z tym?

**Comment by MajkiIT** [comment]
jedyne co mi przychodzi do głowy to fakt, że używasz innych list które mają element blokujący cookies taki jak mam ja, tylko u mnie jest wyjątek i ładuje się raz jedna lub druga reguła.

**Comment by xxcriticxx** [comment]
uzywam tylko twojej listy

**Comment by MajkiIT** [comment]
musiałbym mieć export twoich ustawień z ublocka, bo na razie to wróżenie z fusów.

**Comment by xxcriticxx** [comment]
napisz jak to ci wysle 

zamontowane mam ublock origins standard filtry + polskie filtry + polskie cookies
