### ISSUE TITLE
pclab.pl

### ISSUE THREAD

**Issue by kasper93** [MajkiIT/polish-ads-filter#2896]
```
||pclab.pl/css/extra
pclab.pl###spon_left
pclab.pl###spon_right
pclab.pl##.logoS:style(width: 275px; padding: 11px 0 0 5px; height: 74px; float: left;)
pclab.pl##[class*=offer]
```
Niestety nie da się loga przywrócić, bo w ich originalnym cssie nie ma linku, a ublock blokuje `url()` w stylach.

**Comment by MajkiIT** [comment]
Ja nic nie widzę ... Masz to na głównej stronie?

**Comment by kasper93** [comment]
## Przed
![screen shot 2017-07-02 at 20 11 39](https://user-images.githubusercontent.com/1126053/27772431-b9a5e6d2-5f62-11e7-9e0a-3ce47352633a.png)
## Po
![screen shot 2017-07-02 at 20 11 04](https://user-images.githubusercontent.com/1126053/27772430-b99bd282-5f62-11e7-9b4a-c5634abfe1ed.png)

**Comment by MajkiIT** [comment]
Dobra już czaję. Dziękuję.
