### ISSUE TITLE
gry-online.pl

### ISSUE THREAD

**Issue by PrzemyslawKlys** [MajkiIT/polish-ads-filter#2897]
http://www.gry-online.pl/S016.asp?ID=32661 -> filmiku się nie da odpalić przy odbalonym Ublocku

![image](https://user-images.githubusercontent.com/15063294/27773375-9f9c0e40-5f78-11e7-90ba-4381be6220d1.png)

**Comment by MajkiIT** [comment]
U mnie jest ok. Jakich filtrów używasz?

**Comment by PrzemyslawKlys** [comment]
Kilka uzywałem, ale dla testu wyłączyłem wszystko

![image](https://user-images.githubusercontent.com/15063294/27773486-06823eb6-5f7b-11e7-8ebf-1314390cf7e5.png)

Zostawiłem tylko te 2. Potem jak zostawiłem tylko 1 to nie działało dalej. Jak tylko drugi to działało.

**Comment by gzenio22** [comment]
@xxcriticxx Zerkniesz? ja teraz nie mam jak bo mi plus limit predkosci wkopal je*ana mobilka

**Comment by PrzemyslawKlys** [comment]
Jak wyłączam uBlocka

![image](https://user-images.githubusercontent.com/15063294/27780025-df40acd8-5fc6-11e7-8bd3-514e156c2d69.png)


Jak go załączam

![image](https://user-images.githubusercontent.com/15063294/27780038-f7dd3810-5fc6-11e7-880e-6dd1f7433977.png)

Typowo przywiesza się na reklamie.

**Comment by xxcriticxx** [comment]
@PrzemyslawKlys blokujest host na ubo?

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/27790640-a2b68b72-5ff1-11e7-9534-1617c2fd77e6.png)

![image](https://user-images.githubusercontent.com/15063294/27790645-a91846d6-5ff1-11e7-9348-111233fe8fbb.png)


![image](https://user-images.githubusercontent.com/15063294/27790656-b6b09596-5ff1-11e7-8072-aea3a4c6472d.png)


![image](https://user-images.githubusercontent.com/15063294/27790666-bd377f38-5ff1-11e7-8c39-c4c43d8525f1.png)


Pliku hosts nie uzywam

**Comment by MajkiIT** [comment]
Próbowałeś wyczyścić cache?

**Comment by PrzemyslawKlys** [comment]
Tak, ale dla pewnosci zrobilem teraz tez + restart przegladarki:

![image](https://user-images.githubusercontent.com/15063294/27794323-fa76a6ca-6001-11e7-80d1-4f8adbcd35ee.png)

**Comment by xxcriticxx** [comment]
@MajkiIT dziala to u cibie z hostem? moja lista blokuje wszystkie gemius.pl i tego odpalic nie moge

**Comment by MajkiIT** [comment]
@xxcriticxx masz rację. Jak dodam w hosts gemius.pl film się nie wyświetla 
@PrzemyslawKlys może masz wpisane w hosts w Windowsie?

**Comment by PrzemyslawKlys** [comment]
Nie korzystam z Hosts. Wiedziałbym :-) Natomiast typowo widzę w Ublocku, że gemius.pl jest przyblokowane.

![image](https://user-images.githubusercontent.com/15063294/27803667-f389a8e8-602a-11e7-8895-2ad447827d68.png)

A wyłączyłem wszystkie inne filtry poza polskimi.

**Comment by xxcriticxx** [comment]
@MajkiIT w privacy filter mamy to `||gemius.pl^`

**Comment by hawkeye116477** [comment]
To powinno pomóc: `@@||spl.hit.gemius.pl/gstream.js$script,domain=www.gry-online.pl`

**Comment by hawkeye116477** [comment]
@PrzemyslawKlys To powinno pomóc: `@@||spl.hit.gemius.pl/gstream.js$script,domain=gry-online.pl`

**Comment by PrzemyslawKlys** [comment]
Rzeczywiscie rozwiązuje problem. Dzięki
