### ISSUE TITLE
lg.gadzetomania.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2900]
![capture](https://user-images.githubusercontent.com/15007183/27806711-1f3510f2-600a-11e7-84fa-e31dadd9321e.PNG)

**Comment by gzenio22** [comment]
lg.gadzetomania.pl##.top-box--sponsored.top-box

Po odjeciu tej reklamy jakos mi to dziwnie wyglada ale raczej nie da sie inaczej Zerknijcie prosze

**Comment by MajkiIT** [comment]
Jest Ok. Jak zjedziesz w dół pojawia się logo LG.
