### ISSUE TITLE
wefix.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2902]
cookies

Strona korzysta z plików cookie. Możesz określić warunki przechowywania lub dostępu do plików cookie w Twojej przeglądarce. Więcej o Polityce P

**Comment by gzenio22** [comment]
wefix.pl##body > div:nth-of-type(5) > div

Jak sie nie przyjzysz to mozna powiedziec ze tego nie widac :D
