### ISSUE TITLE
zagadkidladzieci.net

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2907]
![capture11](https://user-images.githubusercontent.com/15007183/27806960-c7c1c444-600b-11e7-8153-0415ef1c39fc.PNG)

**Comment by gzenio22** [comment]
http://zagadkidladzieci.net###opiekunka

**Comment by MajkiIT** [comment]
@gzenio22 jest git.... ale powinno być `zagadkidladzieci.net###opiekunka`
