### ISSUE TITLE
Mały problem z YouTube

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#2911]
Czytając komentarze pod filmikami z YouTube, jak zaznaczy się tekst, to:
<img width="453" alt="immagine2" src="https://user-images.githubusercontent.com/18214146/27808970-056c6fe8-604c-11e7-91ed-6c63ee6c7f94.png">
działa, otwiera się nowa karta z wynikami Google, czyli jest wszystko w porządku. 

A oto problem:
<img width="460" alt="immagine" src="https://user-images.githubusercontent.com/18214146/27808882-46b86e8a-604b-11e7-8a7f-854eedc45e4b.png">
Nie działa, karta się nie otwiera z powodu następującej reguły:
<img width="548" alt="cattura" src="https://user-images.githubusercontent.com/18214146/27808878-3edcfe56-604b-11e7-9162-a1c5c20094c3.PNG">

Filtr: `/^http:\/\/[a-zA-Z0-9]{5,20}\.com\/watch\?/$popup`

Mógłbyś proszę to naprawić?

EDIT: Mam też inny "problem" z komentarzami na YT: jak czytam komentarze, to czasami zdarza mi się, że muszę odświeżyć stronę, aby pokazał mi się przycisk "Pokaż więcej" w danym (długim) komentarzu.
Czy jestem jedyny?

**Comment by MajkiIT** [comment]
@adreporter co do 1 części poprawione. Co do 2 to patrzę u siebie

**Comment by MajkiIT** [comment]
@adreporter co do 2 części to u mnie jest ok. Jaka przeglądarka ?

**Comment by adreporter** [comment]
@MajkiIT Aktualnie używam Chrome, ale z tego co pamiętam to ten problem występował również jak używałem Firefoxa.

**Comment by xxcriticxx** [comment]
@MajkiIT please check this out

https://github.com/anudeepND/youtubeadsblacklist

**Comment by MajkiIT** [comment]
Hmmm dzięki

**Comment by MajkiIT** [comment]
używasz tego ?

**Comment by xxcriticxx** [comment]
nope

**Comment by MajkiIT** [comment]
Sprawdzę w weekend.

**Comment by xxcriticxx** [comment]
nie mam 3 letnich testrow tak jak ty

**Comment by MajkiIT** [comment]
:) na razie muszę to wrzucić na router.
