### ISSUE TITLE
sportowebeskidy.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2919]
![capture](https://user-images.githubusercontent.com/15007183/27837944-733ca452-60b5-11e7-8065-6cd4abf8d830.PNG)

**Comment by gzenio22** [comment]
sa tam jeszcze bannery reklam gier ja nie dam rady

**Comment by xxcriticxx** [comment]
@gzenio22 postaraj sie trzeba zablokowac system bannerowy z gwiazdka

**Comment by MajkiIT** [comment]
@gzenio22 dasz... więcej wiary w siebie.

**Comment by xxcriticxx** [comment]
@gzenio22 przeczytales inspect element?

**Comment by MajkiIT** [comment]
@gzenio22 może to ci pomoże 
https://www.certyficate.it/adblock-pisanie-wlasnych-regul/

**Comment by xxcriticxx** [comment]
@gzenio22 chyba na spiki english

**Comment by MajkiIT** [comment]
hmmm zaraz zobaczymy
