### ISSUE TITLE
radomsport.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2920]
prawa i lewa strona

**Comment by gzenio22** [comment]
||radomsport.pl/img/banery/banner_medjana_5.png
zostaja boxy ale nie wiem jak je usunac pojedyncza regula

**Comment by xxcriticxx** [comment]
@gzenio22 skyscraper

**Comment by gzenio22** [comment]
@xxcriticxx Tak ale 2 razy a nie wiem czy ktos tego jedna polaczona regula by nie zdjoł

**Comment by xxcriticxx** [comment]
nieda bo sie nazywaja innaczej

**Comment by MajkiIT** [comment]
@gzenio22 odnośnie tego ||radomsport.pl/img/banery/banner_medjana_5.png to nie za bardzo. Blokujemy elementy na stronie a nie pojedyńcze obrazki. 

Coś Ci wytłumaczyć?

**Comment by xxcriticxx** [comment]
@MajkiIT ja mu nie potrzebnie pokazalm element picker w ubo i teraz on te filtry podaje :(

**Comment by MajkiIT** [comment]
@xxcriticxx niech się uczy. Inaczej nie osiągnie sukcesu.

**Comment by gzenio22** [comment]
przepraszam w takim razie poczekam na twoie szkolenie @MajkiIT Przepraszam jesli cos popsulem zrobilem to nie swiadomie

**Comment by xxcriticxx** [comment]
@gzenio22 nic nie zepsules poczwicz sobie wszystko wyskajuje my filters w ubo zawsze mozesz skasowac

**Comment by MajkiIT** [comment]
@gzenio22 nic się nie dzieje. Masz się uczyć jak chcesz. Nic nie twoi na przeszkodzie abyś się uczył. Nie masz za co przepraszać. Pamiętaj, że nie masz za co przepraszać.

**Comment by gzenio22** [comment]
@MajkiIT Tylko ze to na Elektrodzie to byl chyba moj kod XD a ty dostales przyslowiowa zjebke a ja nie lubie jak ktos obrywa za mnie...

**Comment by MajkiIT** [comment]
to była moja reguła i nie przejmuj się tym. Ja wiem, że nie jestem idealny i popełniam błędy. Więc głowa do góry.

**Comment by gzenio22** [comment]
idealny nikt nie jest :) ale teraz z kolejnymi kodami zaczekam na tutorial :)

**Comment by MajkiIT** [comment]
o nie.... masz trenować... czekam na reguły.

**Comment by gzenio22** [comment]
ale jak cos poprawiaj byki :D

**Comment by MajkiIT** [comment]
chcesz się uczyć to Ci pomożemy. Zawsze możemy się zgadać na skype.

**Comment by gzenio22** [comment]
jestem za :) tylko kiedy? :)

**Comment by MajkiIT** [comment]
Niedziela ?

**Comment by gzenio22** [comment]
Niedziela o 21? :)

**Comment by MajkiIT** [comment]
idealnie. Może wyrobie się z nowym kompem. 
wyślij mi na maila swój nick na skype to się zgadamy.
@xxcriticxx @F4z @kasper93 dołączacie?

**Comment by gzenio22** [comment]
Nick skype ten sam co tu :D

**Comment by MajkiIT** [comment]
wysłane zaproszenie
