### ISSUE TITLE
hotelpanorama.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2925]
cookies

Informacja

Aby przeglądanie naszego serwisu było bardziej komfortowe wykorzystujemy pliki Cookies (tzw. ciasteczka). Korzystanie z serwisu oznacza wyrażenie zgody na stosowanie cookie.

Warunki przechowywania lub dostępu do plików cookies w możesz określić w swojej przeglądarce.

Szczegółowe informacje znajdują się tutaj.

**Comment by gzenio22** [comment]
hotelpanorama.pl###_mo
