### ISSUE TITLE
pclab.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2928]
Filtry"POL: polskie filtry do Adblocka i uBlocka​" nagle zaczęły powodować rozjeżdżanie się strony pclab.pl - po wczytaniu strony na samej góeze mamy olbrzymie czarne pole na kilkanaście/kilkadziesiąt ekranów, dopiero pod spodem znajduje się właściwa strona. Wyłączenie tego filtra przywraca właściwe funkcjonowanie strony.

**Comment by xxcriticxx** [comment]
@F4z wrocil z wakacji?

**Comment by F4z** [comment]
@xxcriticxx jeszcze nie. Wracam w najbliższą niedzielę :)

**Comment by xxcriticxx** [comment]
@F4z nastepnym razem zabieram sie z toba

**Comment by MajkiIT** [comment]
@xxcriticxx masz ten błąd z 1 postu ?

**Comment by gzenio22** [comment]
ja problemu nie widze

![screenshot_2](https://user-images.githubusercontent.com/21177361/27903309-216c96c0-6239-11e7-836c-8fa06dff4b4d.png)

**Comment by xxcriticxx** [comment]
@MajkiIT u mnie jest git widze to samo co @gzenio22 nic rozmytego

**Comment by MajkiIT** [comment]
Ok dzięki

**Comment by F4z** [comment]
Ten problem jest tylko w Adblocku/Adblocku Plus.
To wina tych reguł:
`pclab.pl##.logoS:style(width: 275px; padding: 11px 0 0 5px; height: 74px; float: left;)`
`||pclab.pl/css/extra`

W zasadzie to bardziej tej pierwszej niż tej drugiej, ale ta druga też trochę psuje wygląd, dlatego myślę, że te dwie reguły powinny zostać przeniesione do specjalnej listy dla uBlocka.


<details><summary>Obrazek</summary>

![image](https://user-images.githubusercontent.com/11742596/27997995-11835f00-6504-11e7-9ff6-0a5ef71d7975.png)
</details>
