### ISSUE TITLE
tvgorzow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2930]
![capture](https://user-images.githubusercontent.com/15007183/27877489-d8f3f97a-6188-11e7-956d-3acb2862aea2.PNG)

**Comment by gzenio22** [comment]
tvgorzow.pl###testimonialrotatorwidget-5

Upewnijcie sie czy nie wale byka i pytanie reklamy ze stopki strony tez usuwamy bo zbaranialem?
