### ISSUE TITLE
polskaniepodlegla.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2931]
https://polskaniepodlegla.pl/kraj-swiat/item/3329-komorowski-wrocil-z-wakacji-udzielil-wywiadu-i-juz-nagadal-glupot

![capture](https://user-images.githubusercontent.com/15007183/27877523-fd47dd00-6188-11e7-9dc9-08001a94d842.PNG)

**Comment by gzenio22** [comment]
hmmm u mnie jest tylko pusty box reklama dziiwne?

polskaniepodlegla.pl###gkInset > .nomargin.box
