### ISSUE TITLE
katowice.gosc.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2932]
maybe?

![capture](https://user-images.githubusercontent.com/15007183/27877549-184975be-6189-11e7-898e-6346e20ce8cb.PNG)

**Comment by gzenio22** [comment]
katowice.gosc.pl###ReleasePromo

Chyba tak bedzie naj lepiej bo jak sama reklame daje to zostaje kawalek szarego? sorry ze dopytuje ale nie chce fuckupu popelnic
