### ISSUE TITLE
niezlomni.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2933]
maybe social?

![capture](https://user-images.githubusercontent.com/15007183/27877591-4033b134-6189-11e7-8dee-4d7493fcb050.PNG)

**Comment by blocker999** [comment]
ok

**Comment by hawkeye116477** [comment]
`niezlomni.com###hwm`

**Comment by hawkeye116477** [comment]
A widgety Facebooka z prawej wywalamy?
`niezlomni.com##.widget_facebook.widget`

**Comment by hawkeye116477** [comment]
@blocker999 @MajkiIT A widgety Facebooka z prawej wywalamy?
`niezlomni.com##.widget_facebook.widget`

**Comment by blocker999** [comment]
@hawkeye116477 Które proszę o screen.

**Comment by hawkeye116477** [comment]
@blocker999 
![screenshot_20170725_125741](https://user-images.githubusercontent.com/19818572/28569145-e35f2aa0-7138-11e7-860d-cb35be35cc40.png)

**Comment by blocker999** [comment]
@xxcriticxx  Poprawione, zaktualizuj filtry.
