### ISSUE TITLE
hpe.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2934]
cookies 

https://www.hpe.com/pl/en/networking/location-based-services.html

Na stronach HPE są używane narzędzia do zbierania danych, np. pliki cookie. Powiedz nam, w jakim zakresie firma HPE może korzystać z tych narzędzi:
Zbierane są również anonimowe informacje statystyczne w celu zwiększenia funkcjonalności i wydajności witryny.
Zbierane są również anonimowe informacje statystyczne w celu zwiększenia funkcjonalności i wydajności witryny.
Czy firma HPE moze spersonalizowac dzialanie stron HPE?
Czy firma HPE moze spersonalizowac dzialanie stron HPE?
Tak
Nie
Czy firma HPE i jej partnerzy moga wyswietlac na innych stronach reklamy zwiazane z Twoimi zainteresowaniami?
Czy firma HPE i jej partnerzy moga wyswietlac na innych stronach reklamy zwiazane z Twoimi zainteresowaniami?
Tak
Nie

Kliknij przycisk Kontynuuj, aby wyrazić zgodę na używanie plików cookie przez HPE. Aby zmienić preferencje lub wycofać swoją zgodę, przejdź na stronę Oświadczenie o ochronie prywatności .

**Comment by gzenio22** [comment]
hpe.com##.open.privacy-banner
