### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2941]
info o gierce " zagraj teraz "

![ks](https://user-images.githubusercontent.com/23176832/27956889-1fee426a-631c-11e7-8d83-db852d68378a.jpg)

**Comment by gzenio22** [comment]
||www.komputerswiat.pl/media/2016/267/4807019/tg_tl_roa_komputerswiat_320x250.jpg

Domyslam sie ze ten kod jest nie do konca dobry ale nie wiem co usunac zeby byl ok

**Comment by MajkiIT** [comment]
`komputerswiat.pl##.sidebar_html_embed`

**Comment by gzenio22** [comment]
@MajkiIT Ty to z kosmetycznych wyciagnoles? Dobrze widze?

**Comment by xxcriticxx** [comment]
@gzenio22 mowilem tobie poczytaj sobie o Inspect Element i developer tools duzo pomoze

**Comment by gzenio22** [comment]
@xxcriticxx A jest jakis polski artykuł o tym? :)

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/27969369-92fe1b58-6318-11e7-8b90-c51b30e2be10.PNG)

**Comment by gzenio22** [comment]
Daj jakiegos linkacza do addona :) bede wdzieczny

**Comment by xxcriticxx** [comment]
to nie jest plugin to jest czescia browsera

To open Opera Dragonfly, take one of the following steps:

    Right-click an element of the page, and select Inspect Element from the context menu.
    From the main menu, select Page > Developer Tools > Opera Dragonfly.
    Use the keyboard shortcut Ctrl + Shift + I .

**Comment by gzenio22** [comment]
aaa widze :D kurde nauka HTMLa mnie nie ominie

**Comment by xxcriticxx** [comment]
@gzenio22 podawaj strony to co widzisz i slyszysz to jest najwazniejsze 👍

**Comment by gzenio22** [comment]
wiem :) ale fajnie by bylo nauczyc sie czegos nowego
