### ISSUE TITLE
ciekawa sytuacja

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2943]
http://prntscr.com/fsy7fh

Link do problematycznej gry XD: http://www.gry.jeja.pl/36037,hakowanie-multiplayer.html

**Comment by xxcriticxx** [comment]
@gzenio22 aak-cont jaka ver masz?

![capture](https://user-images.githubusercontent.com/15007183/27976952-a381bd54-6336-11e7-87a9-ea38066d0c90.PNG)

**Comment by gzenio22** [comment]
aak mi sie wgl nie aktualizuje mim,o ze zmienilem na to co mi kiedys podeslales

**Comment by xxcriticxx** [comment]
najnowsza ver jest 1.085 sprawdz co masz umnie gra dziala

**Comment by gzenio22** [comment]
nigdy sie nie nauczylem sprawdzac tych wersji eh :(

**Comment by xxcriticxx** [comment]
@gzenio22 tampermoneky potem dashboard
