### ISSUE TITLE
binarne.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2947]
reklama na main page

![screenshot from 2017-07-08 07-58-11](https://user-images.githubusercontent.com/15007183/27985126-453458e2-63b3-11e7-9d56-db721ad4d2f1.png)

**Comment by gzenio22** [comment]
binarne.com##.wrapper > center:nth-of-type(1) (Na gorze strony)
binarne.com##.tborder2:nth-of-type(6) > tbody (po prawej) 
binarne.com##center:nth-of-type(2) (W stopce)

Sporo linijek jak na jedna strunę ale nie wiem czy da sie pojedynczo

**Comment by hawkeye116477** [comment]
![rek](https://user-images.githubusercontent.com/19818572/28021778-57225932-6589-11e7-82d3-2e96ad32f971.PNG)

Jeszcze jeden mały element po prawej zostaje.
`binarne.com##.tborder2:nth-of-type(5)`
