### ISSUE TITLE
bdip.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#2949]
brak strony, biale tlo.

**Comment by xxcriticxx** [comment]
u mnie dziala 

![capture](https://user-images.githubusercontent.com/15007183/27988141-ddaa0042-63e8-11e7-9462-7baa346ce0c3.PNG)

**Comment by xxcriticxx** [comment]
ok widze co nie dziala dolna czesc strony problem jest z `/cookielaw$script`

**Comment by lukjan32** [comment]
no, dolna czesc

**Comment by hawkeye116477** [comment]
`@@||*/wp-content/plugins/cookie-law-info/js/cookielawinfo.js$script`

**Comment by lukjan32** [comment]
prosze dodac
