### ISSUE TITLE
wszystkotujest.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2950]
cookies

![capture](https://user-images.githubusercontent.com/15007183/27988310-10800026-63ed-11e7-93c0-7f25d938d2e1.PNG)

**Comment by gzenio22** [comment]
wszystkotujest.pl##body > div:nth-of-type(3)

hmm powinno poleciec :)

**Comment by hawkeye116477** [comment]
Są tutaj też reklamy kredytu, to powinno pomóc na nie - `wszystkotujest.pl##.box-banners`
