### ISSUE TITLE
Ulubieńcy 

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2952]
> Witam!
> 
> Korzystam z AdGuarda i niestety znowu są problemy z wp.pl - wszędzie pełno reklam...
> Da Pan radę coś zaradzić?
> 
> Dziękuję i pozdrawiam!

Może ktoś to potwierdzić ?

**Comment by xxcriticxx** [comment]
Ja znam tylko jednego usera z adguardem @F4z

**Comment by F4z** [comment]
Potwierdzam, postaram się niedługo to naprawić ;)

Swoją drogą, u mnie film tutaj nie działa - `https://www.wp.pl/tv/telewizjawp`
To wina tej reguły z EasyList - .`stream^$third-party,xmlhttprequest`
Po dodaniu tego jest ok:
`@@||av-cdn-*.wpimg.pl/*:wp*.stream^$domain=wp.pl`

@MajkiIT te dwie reguły są nadal potrzebne?
`/^http:\/\/www\.wp\.pl\/[a-zA-Z0-9_\-=]{400,}/$script,domain=www.wp.pl`
`/^https:\/\/www\.wp\.pl\/[a-zA-Z0-9_\-=]{500,}/$script,domain=www.wp.pl`
Pytam, bo jak się korzysta z Adguarda to one psują odtwarzacz.

**Comment by MajkiIT** [comment]
@F4z zaraz poprawię. Dzięki za info.
