### ISSUE TITLE
mywrestling.com.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2953]
wykryto adblocka

mywrestling.com.pl##.kf422b-hide.kf422b-1.kf422b-container

sprawdzi ktos czy sie nie wali?

**Comment by gzenio22** [comment]
mywrestling.com.pl##.kf422b-hide.kf422b-1.kf422b-container

sprawdzi ktos czy sie nie wali?

**Comment by xxcriticxx** [comment]
postowalem na ad protector
