### ISSUE TITLE
kryminalnapolska.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#2959]
wielki banner cookies na operze pusty na firefoxie komunikat o cookies

kryminalnapolska.pl###adnp

**Comment by xxcriticxx** [comment]
podobne do wrealu24.pl

**Comment by gzenio22** [comment]
@xxcriticxx Nawet takie same bym powiedzial

**Comment by gzenio22** [comment]
@xxcriticxx @MajkiIT wescie wbijcie na wrealu i wybiezcie jaki kolwiek artykul nie przekieruje was na jakas przedszkolanke czy inne gowno?

**Comment by xxcriticxx** [comment]
@gzenio22 na foxie jest good

**Comment by MajkiIT** [comment]
@gzenio22 chyba odwzorowałem to co ty masz.

**Comment by xxcriticxx** [comment]
spyware/malware?

**Comment by MajkiIT** [comment]
to coś na wzór tego co jest na stronach z filmami. 

`||com/js/a.js$script,domain=wrealu24.pl `

**Comment by xxcriticxx** [comment]
regexem nie lepjej?

**Comment by MajkiIT** [comment]
@xxcriticxx właśnie coś tworzę.

**Comment by gzenio22** [comment]
ale powiem wam sie zdziwilem jak to zobaczylem Xd
