### ISSUE TITLE
augustyna.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2960]
resztki 

http://www.augustyna.pl/prognozy/gdansk.php

![capture](https://user-images.githubusercontent.com/15007183/27996760-6452d6b8-64b7-11e7-8ecd-54199641e0d0.PNG)

**Comment by gzenio22** [comment]
tutaj to chyba ja nie dam rady

**Comment by MajkiIT** [comment]
```
augustyna.pl##TD[align="left"]
augustyna.pl##IMG[alt="REKLAMA"]
```

**Comment by gzenio22** [comment]
@MajkiIT W skrocie jak tys to wyrwal? :D ja probuje i ubo i tym w budowanym w opere ale w tym wbudowanym malo rozumiem

**Comment by xxcriticxx** [comment]
tylko 3 kropki zostana mam nadzieje ze nazwa gif sie nie zmienia 

`||augustyna.pl/r1.gif$image`
`||augustyna.pl/r2.gif$image`
