### ISSUE TITLE
 konkurs

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2964]
@MajkiIT maybe jakis konkurs zrobimy?

**Comment by MajkiIT** [comment]
Odnośnie czego ?

**Comment by xxcriticxx** [comment]
kto zgadnie ile @gzenio22 ma lat

**Comment by gzenio22** [comment]
@xxcriticxx a co do wygrania? :D

**Comment by MajkiIT** [comment]
Router dlink z wifi w standardzie G

**Comment by xxcriticxx** [comment]
pendrive z elektrody.pl *cough* *cough*

**Comment by gzenio22** [comment]
hahahaha a ktos wgl wie ile mam lat? :D

**Comment by xxcriticxx** [comment]
@gzenio22 masz zadznie na dzisaj masz pomysliesc oczym bendzie konkurs

**Comment by xxcriticxx** [comment]
22

**Comment by gzenio22** [comment]
@xxcriticxx Błędna odpowiedz :P

**Comment by gzenio22** [comment]
@xxcriticxx Mowisz powaznie czy sie nabijamy?

**Comment by xxcriticxx** [comment]
powaznie!

**Comment by gzenio22** [comment]
jak powaznie to jakiej muzyki slucham ciekawe czy ktos utrafi ale kto funduje nagrode?

**Comment by xxcriticxx** [comment]
nagrode funduje @MajkiIT 

@gzenio22 techno

**Comment by gzenio22** [comment]
@xxcriticxx nie

**Comment by xxcriticxx** [comment]
to niedostane pendriva shit

**Comment by gzenio22** [comment]
zobaczymy co inni wymysla

rada wpiszcie moj nick w google :D

**Comment by xxcriticxx** [comment]
@gzenio22 niechce sie przestraszyc przed snem

**Comment by gzenio22** [comment]
@xxcriticxx Czyli sie juz domyslasz :D

**Comment by xxcriticxx** [comment]
nie robie update flashu na jubuntu :)

**Comment by gzenio22** [comment]
a co do wieku mam 24 :P
