### ISSUE TITLE
Uniwersalna reguła

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#2968]
Przygotowując aktualizacje do sociali spotykam się ostatnio z takimi regułami  
które dobrze by było aby zastąpić  jedną uniwersalną, co oszczędziło by mi roboty a urzytkownikom sporo nerwów, generalnie załatało by to luke w liście. Oto kilka przykładów:
```

www.augustyna.pl##a[href="http://www.facebook.com/augustyna.jastarnia"]

media2.pl##a[href=\\\"https://www.facebook.com/media2pl/\\\"]

netokracja.pl##a[href^=\\\"http://www.facebook.com/sharer.php\\\"]

strona.piaski-wlkp.pl##a[href^=\\\"https://www.facebook.com/Gmina-Piaski-111408545858299/\\\"]

www.dobreprogramy.pl##a[href=\\\"http://www.facebook.com/dobreprogramy\\\"]

www.inbook.pl##a[href="http://www.facebook.com/InBookpl"]
```
 
Bardzo proszę o pomoc, szczególnie @F4z .

**Comment by MajkiIT** [comment]
jedynie co przychodzi mi do głowy to 
```
pl##a[href=\\\"http://www.facebook.com/"]
pl##a[href=\\\"https://www.facebook.com/"]
```

**Comment by blocker999** [comment]
@MajkiIT Dzięki 

Ok potestuje i mam nadzieje że ta regułka pomorze ale jeszcze poczekam na jakiekolwiek info .

**Comment by blocker999** [comment]
@F4z Pomóż, prosze

**Comment by F4z** [comment]
@blocker999 te reguły nie działają prawdopodobnie przez to, że mają 3 ukośniki z przodu.
Tak powinno być prawidłowo:
`pl##a[href^="http://www.facebook.com/"]`
`pl##a[href^="https://www.facebook.com/"]`

Spojrzę wieczorem jak będę miał trochę więcej czasu :)

**Comment by MajkiIT** [comment]
@F4z boję się, że jest to za ogólne.

**Comment by blocker999** [comment]
@F4z Pasują te reguły do tych stron idealnie lecz mam pewne obawy że na innych stronach mogą one coś " uszkodzić " ale tak czy siak je dodam najwyżej międzyczasie się je poprawi.

**Comment by blocker999** [comment]
Niektóre stony oprócz 
```
pl##a[href^="http://www.facebook.com/"]
pl##a[href^="https://www.facebook.com/"]
```
potrzebóją reguł bez www. tzn:
```
pl##a[href^="http://facebook.com/"]
pl##a[href^="https://facebook.com/"]
```
wiec zamiast dwóch są cztery reguły, @F4z idzie to jakoś scalić w całość?
A na strone netokracja.pl żedna z tych reguł niepasuje, dalej proszę o pomoc.

**Comment by MajkiIT** [comment]
A co chcesz na tej stronie zablokować konkretnie?

**Comment by blocker999** [comment]
Jeśli chhodzi o strone netokracja.pl to odnośnik do fb który jest pod każdym artykułem.

**Comment by blocker999** [comment]
Dobra z tą stroną dajmy se spokój bo jest ona w " Fanboy’s Social Blocking List " natomiast proszę o potwierdzenie czy da się uwzględnić www. i bez innymi słowy z 4 reguł zrobić 2 na przykładzie faceboka.
