### ISSUE TITLE
zmiana regułki

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#2969]
wp.pl##[class^="_"][href^="https://"][target="_blank"]>FIGURE[class^="_"]
wp.pl##[class^="_2"][href^="https://"][target="_blank"]
wp.pl##[class^="_2"][href^="https://"] + SPAN[class^="_2"]

**Comment by gzenio22** [comment]
na glownej czysto :)

**Comment by MajkiIT** [comment]
@gzenio22 chodziło mi o to 
`https://film.wp.pl/nie-zyje-bernard-hanaoka-aktor-i-projektant-mial-68-lat-6142628782540417a `

pod komentarzami
