### ISSUE TITLE
netto.pl

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#2970]
https://netto.pl/gazetka-netto/
Zjedźcie proszę trochę na dół strony i kliknijcie w "ZOBACZ GAZETKĘ NETTO". 
Też Wam nie wyświetla się gazetka?

EDIT: Następująca reguła rozwiązuje problem: `@@||assets.adobedtm.com^$script,domain=netto.pl`

**Comment by gzenio22** [comment]
Jak by gdzies Hiperłącza zbraklo?
