### ISSUE TITLE
Android lubi ciastka

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#2975]
Niestety na Androidzie na Lisku, na niektórych stronach wyświetlają się komunikaty o ciasteczkach, na których na PC nie ma takich komunikatów.

Na razie tyle znalazłem:
```
satkurier.pl##.cc_container--open.cc_container.cc_banner
www.dobreprogramy.pl###cookiesPanel
www.tablety.pl###cookie-law
allegro.pl###cookie-policy-banner
www.x-kom.pl###popup-cookie
```

Aktualizacja:
```
pl###cookie-bar  (euro.com.pl, carrefour.pl)
www.neonet.pl###notice-cookie-block
www.mediaexpert.pl##.cookieBox
pl###js-cookieInfo (mediamarkt.pl, saturn.pl)
auchan.pl###cookies
atrium-biala.pl##.cookies
www.biedronka.pl###cookiepopupdiv
www.lidl.pl###cookie-banner
stokrotka.pl###cookies-message
www.kaufland.pl##.cookieInfo
netto.pl##.col-lg-offset-1.col-lg-6.col-xs-8
m.interia.pl###inpl_cp_cnt
freeisoft.pl##.pea_cook_bottomright.pea_cook_wrapper
ncplus.pl###cookies_info
forum.ncplus.pl##.cc_container--open.cc_container.cc_banner
www.cyfrowypolsat.pl##.cookieboks
wirtualnemedia.pl###cookiebar
```

pl###cookies_info - podobna reguła już jest w filtrze, ale bez pl przed #, na PC działa bez pl i z pl, a na Androidzie działa tylko z pl przed #.

Aktualizacja (12 lipca):
`pssite.com###cookies-overlay`
`komputronik.pl##.active.cookies-bar`
`instalki.pl###ciasteczka`

**Comment by hawkeye116477** [comment]
Dziwne, zauważyłem, że na niektórych z tych stron (np. wirtualnemedia.pl) na PC komunikat o ciasteczkach pojawia się, po czym szybko znika. Po dopisaniu pl przed hashami, już coś takiego nie występuje.

**Comment by xxcriticxx** [comment]
@hawkeye116477 widze ze przewaznie to sa jakies sklepy

**Comment by FX54** [comment]
Ja po tygodniu ogarnąłem że uBlock na mobilnym Firefox ma wyłączone filtry kosmetyczne i trzeba ręcznie włączyć.

**Comment by hawkeye116477** [comment]
@FX54 Niestety u mnie są włączone.

**Comment by hawkeye116477** [comment]
@FX54 Ok, wygląda na to, że jakimś cudem nie zauważyłem zaznaczonej opcji „Ignoruj ogólne filtry kosmetyczne", teraz jest jak na PC, nadal się pojawia, ale szybko znika.
