### ISSUE TITLE
kpmg.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2981]
cookies 

https://home.kpmg.com/pl/pl/home.html

Ta strona używa plików cookies. Korzystanie ze strony bez zmiany ustawień przeglądarki w tym zakresie, oznacza zgodę na ich używanie. Więcej informacji na ten temat znajduje się w naszej polityce prywatności.
Wyrażam zgodę

**Comment by hawkeye116477** [comment]
`home.kpmg.com##.privacy-container`
