### ISSUE TITLE
fantastyka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2984]
lewa i prawa strona maybe

**Comment by MajkiIT** [comment]
`fantastyka.pl##.tapeta`

**Comment by hawkeye116477** [comment]
![reklama](https://user-images.githubusercontent.com/19818572/28111641-7bf59e22-66f6-11e7-81d9-081dbf4c4037.png)

Można też schować ten banner reklamowy.
www.fantastyka.pl##.banner
