### ISSUE TITLE
pssite.com

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#2987]
### Co trzeba zrobić aby reklama/element się pojawił
1. Wejść na stronę główną i spojrzeć w prawo (1-sze puste miejsce po reklamie)
2. Przewinąć trochę stronę i spojrzeć w prawo (2-gie puste miejsce po reklamie)
3. Przewinąć trochę stronę i spojrzeć w prawo (3-cie puste miejsce po reklamie)
4. Przejść do jakiegoś newsa i spojrzeć w prawo (4-te i 5-te puste miejsce po reklamie)

### Twoja konfiguracja
**Przeglądarka:**
Waterfox 54.0.0.1/Firefox
**Operating system:**
Manjaro Linux 17.0.2
**Blocker:**
uBlock Origin 1.13.4
**Używane filtry:**
1. Wszystkie uBlock filters oprócz experimental
2. Adblock Warning Removal List
3. EasyList
4. EasyPrivacy
5. Malware Domain List​​​​​
6. Malware domains
7. Peter Lowe’s Ad and tracking server list
8. POL: polskie filtry do Adblocka i uBlocka
9. POL: polskie filtry do uBlocka uzupelnienie
10. AAK-Cont Filter For uBlock Origin
11. Adblock & uBlock polish cookies filters
12. KAD - Przekręty

### Zrzut ekranu
![screenshot_20170712_121828](https://user-images.githubusercontent.com/19818572/28113299-53126e1c-66fc-11e7-9d54-1699982acdf8.png)

`http://pssite.com/`
`http://pssite.com/news/57651/wrc-7-prezentuje-nowy-tryb-epic-stages.html`

### Moje rozwiązanie problemu
```
pssite.com##.tb-content:nth-of-type(1) > .bgisneed.container > .incontainer > .clearfix.bricks > .adv.flr.s1_2.brick
pssite.com##.adv.s1_1.brick
pssite.com##.clearfix:nth-of-type(5) > .pb15.pt15.bgcDARK.container > .incontainer > .clearfix.bricks > .adv.flr.s1_2.brick
pssite.com##.adv.flr.s1_2.brick
pssite.com##.adv.s1_2.brick
```

**Comment by MajkiIT** [comment]
@hawkeye116477 to template dla osób które zgłaszają i są tu rzadko. Możesz usunąć template i wpisać co masz wpisać.

**Comment by hawkeye116477** [comment]
Zapomniałem o jeszcze jednym pustym miejscu, dodałem kolejną regułę. Trochę się tego nazbierało. Da się coś połączyć w jedno?

**Comment by F4z** [comment]
> Da się coś połączyć z czymś w jedno?

To powinno wystarczyć:
`pssite.com##.adv`

**Comment by hawkeye116477** [comment]
@F4z Działa, dzięki.
