### ISSUE TITLE
gry.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2991]
@MajkiIT please check this out! nowe testy maybe?

https://github.com/jspenguin2017/uBlockProtector/issues/384

**Comment by hawkeye116477** [comment]
To jest już fixed. 
https://github.com/jspenguin2017/uBlockProtector/commit/7a15454c5d989bf5df6bcc87b16fb6776880adf6

**Comment by adreporter** [comment]
<img width="483" alt="asasaas" src="https://user-images.githubusercontent.com/18214146/28182686-3536be9a-680d-11e7-817d-8703e58c9395.PNG">
Też wam nie działa?
