### ISSUE TITLE
gry.misiakowo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2992]
![capture](https://user-images.githubusercontent.com/15007183/28141536-fdeccd22-672a-11e7-9b5e-93f071859fbb.PNG)

**Comment by gzenio22** [comment]
gry.misiakowo.pl##div:nth-of-type(5)
gry.misiakowo.pl##div:nth-of-type(4)
gry.misiakowo.pl##h2:nth-of-type(6)


Nie wiem czy przejdzie sprawdzcie prosze

**Comment by hawkeye116477** [comment]
Przeszło, ale chyba aż za bardzo, teraz widać tylko logo strony :smiley:

2 z tych reguł są poprawne, a 1 wymaga małej poprawki.
Tak powinno być gites:

```
gry.misiakowo.pl##h2:nth-of-type(6)
gry.misiakowo.pl##div:nth-of-type(5)
gry.misiakowo.pl###content > div:nth-of-type(4)
```

**Comment by MajkiIT** [comment]
Ja zbiłem do takiego 
```
gry.misiakowo.pl##[style$="width:346px;height:290px;"]
gry.misiakowo.pl##[style="width:100%;max-width:800px;overflow:auto;"] + H2
```
