### ISSUE TITLE
domowyprzedszkolak.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2993]
resztki 

http://www.domowyprzedszkolak.pl/item/labirynt-ciuchcia-296

![capture](https://user-images.githubusercontent.com/15007183/28141609-5815af58-672b-11e7-9af1-acadfa3d6766.PNG)

**Comment by gzenio22** [comment]
domowyprzedszkolak.pl##h2:nth-of-type(1)

Nie mam pewnosci

**Comment by hawkeye116477** [comment]
Jeszcze jest na dole:
`domowyprzedszkolak.pl##h2:nth-of-type(2)`
