### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#2995]
http://www.komputerswiat.pl/wideo/pan-appka/cala-seria/odcinki/pan-appka-130.aspx
<img width="508" alt="dsfsfsf" src="https://user-images.githubusercontent.com/18214146/28153616-9ea2cffc-67a6-11e7-86ff-9f2930ce605f.PNG">
Też nie możecie odtworzyć filmiku?

**Comment by gzenio22** [comment]
tak cos sie pizdlo...

**Comment by hawkeye116477** [comment]
Tak, problem powoduje pewnie jakaś reguła z filtrów polskie filtry do Adblocka i uBlocka, gdyż po jej wyłączeniu filmik normalnie się odpala, ale tylko na Chromium i Vivaldim (do Vivaldiego musiałem doinstalować plugin widevine do obsługi DRM). Na Waterfoksie podaje, że muszę zainstalować soft do odtwarzania treści chronionych przez DRM. Zrobiłem to oczywiście i filmik nadal nie działa, mimo, że wyłączyłem polskie filtry do Adblocka i uBlocka. To spróbowałem czegoś innego, włączyłem filtry uBlock Protector i czary mary, działa, ale muszą być odpalone oba fitlry - AAK Cont i uBlock Protector, inaczej to nie wypali, przynajmniej na Firefoksie i spółce, na Chromowatych nie potrzeba AAK Cont. Więc wynika z tego, że problem jest gdzieś w regułach na polskich filtrach i w filtrze AAK Cont.

**Comment by F4z** [comment]
To najprawdopodobniej wina tego filtra - `onet.pl,komputerswiat.pl##script:inject(abort-on-property-read.js, dlApi)`
Tylko po jego usunięciu może być komunikat o adblocku.

Moglibyście sprawdzić, czy działa Wam film jak dodacie to?
`onet.pl,komputerswiat.pl#@#script:inject(abort-on-property-read.js, dlApi)`

Jeśli będziecie mieli komunikat o adblocku, to wtedy dodajcie jeszcze tę regułę:
`komputerswiat.pl#@##ks_breaking_news`

**Comment by hawkeye116477** [comment]
@F4z Nie trzeba dodawać `onet.pl,komputerswiat.pl#@#script:inject(abort-on-property-read.js, dlApi)`. Wystarczy tylko `komputerswiat.pl#@#script:inject(abort-on-property-read.js, dlApi)`.

**Comment by xxcriticxx** [comment]
yep! dziala z `onet.pl,komputerswiat.pl#@#script:inject(abort-on-property-read.js, dlApi)`

**Comment by adreporter** [comment]
Potwierdzam, działa po dodaniu `komputerswiat.pl#@#script:inject(abort-on-property-read.js, dlApi)`
