### ISSUE TITLE
gizchina.com.pl/forum/

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#2997]
![screenshot_20170713_191250](https://user-images.githubusercontent.com/19818572/28178610-651a756a-67ff-11e7-9305-dbf46a1194ad.png)

`gizchina.com.pl###adBlockDetectedMessage` :smiley:

**Comment by xxcriticxx** [comment]
nie mam nic takiego z aak-cont

**Comment by xxcriticxx** [comment]
ok zrobilem kilka refresh i wyskoczylo

**Comment by hawkeye116477** [comment]
Albo jeszcze lepiej: `||gizchina.com.pl/forum/uploads/*/*fuckadblock.min.js`

**Comment by hawkeye116477** [comment]
Albo może lepiej dać coś takiego: `||gizchina.com.pl/*fuckadblock.min.js$script`
