### ISSUE TITLE
vivaldi.start.me

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#2999]
![screenshot_20170713_203559](https://user-images.githubusercontent.com/19818572/28184948-bd9c5544-6815-11e7-9c79-efc357b697fa.png)

Komunikat o ciastkach
`start.me##.alert.notification-bar`

**Comment by xxcriticxx** [comment]
@hawkeye116477 widze ze z nyc jestes

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie, jestem z Polski.

**Comment by xxcriticxx** [comment]
ja tez :)
