### ISSUE TITLE
wiadomosci.wp.pl

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#3000]
https://wiadomosci.wp.pl/tvp-info-przekracza-kolejne-granice-zobaczcie-jak-nazwali-kontrmanifestantow-6142973419370113a
Player znika.
https://github.com/jspenguin2017/uBlockProtector/issues/384#issuecomment-315177534

**Comment by hawkeye116477** [comment]
Co tu się dzieje... Dopiero jak wyłączyłem wszystkie filtry, to zaczęło działać. Coś kombinują...

**Comment by MajkiIT** [comment]
To wynik tego, że player chce wyświetlić reklamy.

**Comment by hawkeye116477** [comment]
https://github.com/jspenguin2017/uBlockProtector/issues/397#issuecomment-315394440

Problem w tym, że to tylko zadziała, jeśli wyłączymy uzupełnienie do polskich filtrów dla uBlocka.

**Comment by adreporter** [comment]
@MajkiIT Proponuję dodać @hawkeye116477 do listy
`! Collaborators: Adam W, Dominik, Wiesiek, Robert, Marek, buuuuuuu190, Caleb, Ryszard, Kruk, Weronika, Adam, xxcriticxx, maxoku, F4z, mathew85,Piter432, Adam K, Piotr S, Szymon D, Marek R, adreporter, kacper93, FadeMind, kerbenii, gzenio22, adreporter, blocker999,  FX54`
Ja tutaj nic nie robię a nawet dwa razy występuję na liście :smiley:

**Comment by xxcriticxx** [comment]
@adreporter ale jest popularny!

**Comment by adreporter** [comment]
@xxcriticxx Anyway, Tobie też pokazuje się i działa player po dodaniu tych filtrów?
```
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=noopjs,domain=wiadomosci.wp.pl
||static.criteo.net/js/ld/publishertag.js$script,redirect=noopjs,domain=wiadomosci.wp.pl
@@||wp.hit.gemius.pl/gplayer.js$script,domain=wiadomosci.wp.pl
@@||wp.hit.gemius.pl/gdejs/xgde.js$script,domain=wiadomosci.wp.pl
wiadomosci.wp.pl#@#script:inject(abort-on-property-write.js, habahaba)
```

**Comment by hawkeye116477** [comment]
Zapomniałem dodać, że testowałem to na Vivaldi z uBlock Protector. A teraz sprawdziłem na Waterfoksie i wywala się. To włączylem oba fitlry - uBlock Protector i AAK Cont i teraz działa.

**Comment by adreporter** [comment]
Niestety poprawka nie działa na innej stronie
https://github.com/jspenguin2017/uBlockProtector/issues/397#issuecomment-315433911

**Comment by adreporter** [comment]
https://wiadomosci.wp.pl/archiwalna-wypowiedz-blaszczaka-kiedys-skrytykowal-po-a-teraz-pis-robi-to-samo-6142419287754369a
Pierwszy raz działało, ale wystarczyło nacisnąć ctrl+r i znowu player zniknął.

**Comment by adreporter** [comment]
Działa po usunięciu ciasteczek. Ale po kilku odświeżeń już nie działa.

**Comment by xxcriticxx** [comment]
@adreporter film znika z filtrami i bez filtrow

**Comment by adreporter** [comment]
@xxcriticxx Masz rację, teraz niestety już nie działa.

**Comment by adreporter** [comment]
@F4z Mógłbyś proszę nam pomóc?

**Comment by adreporter** [comment]
Dodając następujące reguły, player jest ale niestety nie można odtworzyć filmiku:
```
wiadomosci.wp.pl#@#script:inject(abort-on-property-write.js, habahaba)
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=noopjs,domain=wiadomosci.wp.pl
||static.criteo.net/js/ld/publishertag.js$script,redirect=noopjs,domain=wiadomosci.wp.pl
||wiadomosci.wp.pl/*$xmlhttprequest
```

**Comment by hawkeye116477** [comment]
U mnie na Vivaldim reszta strony się ładuje, filmiki oba da radę odtworzyć, ale po odświeżeniu znikają :smiley: Zaktualizuj uBlock Protector Extension.

**Comment by F4z** [comment]
Wydaje mi się, że odpowiadają za to te XHR, które zawierają `VAST`, na przykład to - https://wiadomosci.wp.pl/YWFmYzcwKzxpGzgeTQ80O3kfPAkTGDckIzs8CBAeNjl7XH8IBhwwM3tfak5URGlxNQNkDQoWPTgrAioZClEGanNaa01RQn9xFCgSDgIQMGo2DDUTFBh8ZAQAOAgKAiotGQ81GxANOi0nBn8KCwM0O3saMBsHGDQ4NQ4wVBQHdycqQjgIAB8wICcBNxtOACAnKRowHwcNdDUqDCoAAA04PCdAMhMGEyAkax4yCBoDIDwpGjgWTgc2eidALR8RFiN6NgQqVxEYOz5rGTZXEBY0OGtbaE5RQ2hudFVuTVZDamF_DH8qNDYqIHtcYEhTUQkABx4xR1pAbHEgHzYXJBg2MCoIZEpFETUkMgwtEwdKbXElGSAKBko4JTIEOhYGUQkABzI4HgETZGZgGiklExs4LiMfBhUQFj0tKQMgR1JRKicvA2QtM1k-NiBDPRsXFnxkBDoJVAQWP3kkAj0TBgR8ZAQ6CVQKGTU-KAh_EgIZPTsjH2RKRRMsJScZMBUNSmhgdEs0Ew0WPjJ7XX8eERYqIy8OZEpFFTohe19_FwoTZGV2XWxIUEF_Jy8JZFwXFj4keyQYOFJGfGUFJBg4VVJrFA8sG0tRUTQyIgQ4Hw4VPDN7ADYeDx4qLS0MfxcTEmQ6KQk1ExANMjZgADAUXkZ_OisYZEs=

Tylko one mają "losowe" adresy, moglibyście sprawdzić, czy po dodaniu tych reguł nadal filmy znikają?
`wiadomosci.wp.pl#@#script:inject(abort-on-property-write.js, habahaba)`
`/^(https|http):\/\/wiadomosci\.wp\.pl\/.{400,}/$xmlhttprequest,domain=wiadomosci.wp.pl`

**Comment by xxcriticxx** [comment]
@F4z film jest ale mam ad block

**Comment by jspenguin2017** [comment]
I added a logic to prevent the player from being removed. Can someone test? https://github.com/jspenguin2017/uBlockProtector/commit/9f822c38d16a695e5f4a5c2ebecb315404225c2f

**Comment by xxcriticxx** [comment]
@jspenguin2017 sure give me second installing extension right now

**Comment by xxcriticxx** [comment]
@jspenguin2017 works first time only after you refresh movie disappears

**Comment by jspenguin2017** [comment]
`Cannot read property 'appendChild' of null`, eh... I guess I need to validate the parent...

**Comment by adreporter** [comment]
@xxcriticxx @jspenguin2017 It's working for me all the time, even if I clear cache, cookies and refresh the page

**Comment by xxcriticxx** [comment]
@adreporter how you clear cookies and cache using chrome or ccleaner?

**Comment by adreporter** [comment]
Chrome

**Comment by jspenguin2017** [comment]
I use DevTools, only affect one site.

**Comment by jspenguin2017** [comment]
Does other domains have collapsing players as well? Or just this one?

**Comment by adreporter** [comment]
Let me test

**Comment by hawkeye116477** [comment]
```
wiadomosci.wp.pl#@#script:inject(abort-on-property-write.js, habahaba)
/^(https|http):\/\/wiadomosci\.wp\.pl\/.{400,}/$xmlhttprequest,domain=wiadomosci.wp.pl
```
This rules works perfectly for me, refreshed even few times and player is still here.

**Comment by adreporter** [comment]
@xxcriticxx To delete cookies on chrome: green lock -> cookies in use -> delete
To clear cache ctrl+f5 and ctrl+r

**Comment by adreporter** [comment]
@jspenguin2017 I'll report not working domains at your repository

**Comment by xxcriticxx** [comment]
with @F4z and firefox i have the movie but with ad block :(

with @jspenguin2017 and chrome extension i have move one time only after i fresh no more movie :(

**Comment by hawkeye116477** [comment]
@xxcriticxx Try @F4z rules and uBlock Protector list and extension. For me it's work on Vivaldi/Chromium 59.0.3071.112.

**Comment by xxcriticxx** [comment]
@hawkeye116477 let me check my chrome ver but i think its 59

**Comment by xxcriticxx** [comment]
Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by jspenguin2017** [comment]
I tweaked the observer rule, it should be 100% stable now. It was having some race conditions. Also the video will be re-inserted to the end of the article, as I don't have a way to know where it was.

**Comment by jspenguin2017** [comment]
I refreshed it 10 times, it worked every time with Extension 10.98.

**Comment by jspenguin2017** [comment]
The anti-collapsing logic will only be triggered if something tries to collapse the player, so if there is a better solution to prevent player from collapsing, the current logic will not interfere. Let me know if the player collapses on other domains.

**Comment by xxcriticxx** [comment]
@jspenguin2017 now this works! when can we expect this in aak-cont?

**Comment by jspenguin2017** [comment]
@xxcriticxx When someone port it over. The latest commits to AAK-Cont are delayed due to maintainers being extremely busy. You can try the filter rules above with AAK-Cont and see if that works.

**Comment by adreporter** [comment]
@hawkeye116477 @xxcriticxx Też Wam znika player na tej stronie? https://portal.abczdrowie.pl/sprzedaz-lodow-na-calym-swiecie-spadla-w-ciagu-zaledwie-dwoch-lat-o-2-6-mld-litrow-poniewaz-konsumenci-wybieraja-zdrowszy-styl-zycia

**Comment by hawkeye116477** [comment]
@adreporter Tak.

**Comment by xxcriticxx** [comment]
@adreporter 

na foxie mam ad block ale aak zamienia player i dziala 
na chromie z ver 10.98 film jest caly czas

**Comment by adreporter** [comment]
@xxcriticxx Na chromie usuń ciasteczka i cache oraz odśwież stronę i zobacz czy będzie się pokazywać filmik.

**Comment by hawkeye116477** [comment]
@xxcriticxx Odśwież stronę na Chromie, to stanie się nieodtwarzalny.

**Comment by jspenguin2017** [comment]
It works for me: 
![image](https://user-images.githubusercontent.com/7283682/28232670-3ec4c2a2-68af-11e7-9760-e2baa681d579.png)

**Comment by adreporter** [comment]
@hawkeye116477 @xxcriticxx Eh mój błąd. Miałem dodane własne reguły do uBlocka. Po ich skasowaniu, player jest ale nie idzie odtworzyć filmiku.

**Comment by hawkeye116477** [comment]
@jspenguin2017 After page refresh, player can't play the movie.

**Comment by jspenguin2017** [comment]
Maybe I should just nuke all the subtitles.

**Comment by adreporter** [comment]
@xxcriticxx @hawkeye116477 Houston mamy problem :smile: 
https://wiadomosci.wp.pl/tvp-info-przekracza-kolejne-granice-zobaczcie-jak-nazwali-kontrmanifestantow-6142973419370113a
Naciśnijcie proszę na play a potem dajcie na pełny ekran.

**Comment by adreporter** [comment]
Naprawione przez @jspenguin2017 
https://wiadomosci.wp.pl/tvp-info-przekracza-kolejne-granice-zobaczcie-jak-nazwali-kontrmanifestantow-6142973419370113a
Nie wiem jak Wy, ale ja czasami mam takie coś
<img width="111" alt="ertlol" src="https://user-images.githubusercontent.com/18214146/28233835-0c0d2f0c-68fa-11e7-8c5a-c71db26645d4.PNG">

**Comment by jspenguin2017** [comment]
I can't understand that. But that's not quite what I see... 
![image](https://user-images.githubusercontent.com/7283682/28233954-fd6f7bc2-68b7-11e7-9062-8d8bb66d0f72.png)

**Comment by adreporter** [comment]
@jspenguin2017 Sorry. I'll write it in English
Go to https://wiadomosci.wp.pl/tvp-info-przekracza-kolejne-granice-zobaczcie-jak-nazwali-kontrmanifestantow-6142973419370113a
Scroll down as fast as you can, click on fullscreen button and then click on the girl. Sometimes I see
<img width="111" alt="ertlol" src="https://user-images.githubusercontent.com/18214146/28233835-0c0d2f0c-68fa-11e7-8c5a-c71db26645d4.PNG">

**Comment by adreporter** [comment]
@jspenguin2017 It's happening not sometimes but rarely.

**Comment by adreporter** [comment]
@HateAds jestes?

**Comment by jspenguin2017** [comment]
I can't reproduce that... I'm just inserting the video to the end of `<article>` which ends before the thumbs up and down bar.

**Comment by adreporter** [comment]
Oh I see

**Comment by adreporter** [comment]
@jspenguin2017 I see. It must be some polish rule.

**Comment by xxcriticxx** [comment]
i think this consider fix now
