### ISSUE TITLE
darmowa-telewizja.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3001]
http://darmowa-telewizja.info/canalsport-2/

![capture](https://user-images.githubusercontent.com/15007183/28187796-ea6ad7a8-67ed-11e7-8d6c-540528e7f2aa.PNG)

**Comment by hawkeye116477** [comment]
Nie wiem czy coś takiego da radę zablokować uBlockiem, ale jak dasz 70 zł dla ncplus, to zniknie...

**Comment by F4z** [comment]
Powinno wystarczyć:
`srkcast.com###table1`

**Comment by F4z** [comment]
Dodatkowo jeszcze te reguły mogą być:
`||eap7gcb.com^$third-party`
`||d1qtf1avwa1wvl.cloudfront.net^`
`darmowa-telewizja.info##script:inject(popads.net.js)`

**Comment by MajkiIT** [comment]
A może coś takiego?

```
/^(http|https):\/\/[a-z]{5,10}\.com\/[a-zA-Z0-9+]{80,}/$subdocument,domain=embed.nowvideo.sx|cloudtime.to|darmowa-telewizja.info
/^http:\/\/[a-zA-Z0-9]{10,}\.cloudfront\.net\/[a-zA-Z0-9%?=]{10,}/$script,domain=devil-torrents.pl|electro-torrent.pl|nitro.to|alltube.tv|darmowa-telewizja.info
/^(http|https):\/\/[a-z0-9]{5,}\.com\/[a-z0-9]{1,}\/[a-z0-9]{1,}\/[a-z0-9]{1,}\/[a-z0-9]{5,}\.js/$script,domain=vidto.me|fili.tv|fileone.tv|alltube.tv|srkcast.com
srkcast.com###table1
```
