### ISSUE TITLE
itporady.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3002]
![capture](https://user-images.githubusercontent.com/15007183/28188800-64e3d04a-67f1-11e7-9ee0-504a2dbae671.PNG)

**Comment by hawkeye116477** [comment]
`itporady.pl##.r_sidebar > .visible-md.visible-lg` (na reklamy o koncie)
`itporady.pl##.well` (na reklamę o hostingu)
