### ISSUE TITLE
blog.nowebrzmienia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3003]
adblock + reklama 

http://blog.nowebrzmienia.pl/kontakt/

![capture](https://user-images.githubusercontent.com/15007183/28189496-2bf30988-67f4-11e7-93be-82e7267eea80.PNG)

**Comment by MajkiIT** [comment]
Adblock` blog.nowebrzmienia.pl###adblockModal`
reklama` blog.nowebrzmienia.pl###text-2 > .widget-title-container`

**Comment by hawkeye116477** [comment]
Na Adblock detect można też coś takiego dać zamiast filtru kosmetycznego: `||blog.nowebrzmienia.pl/wp-content/themes/awaken/js/scripts.js$script`
