### ISSUE TITLE
kompnet.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3004]
![capture](https://user-images.githubusercontent.com/15007183/28189668-eae8361a-67f4-11e7-9438-84369a09f625.PNG)

**Comment by MajkiIT** [comment]
`kompnet.info###warning`

**Comment by hawkeye116477** [comment]
Albo można dać coś takiego: 
`||kompnet.info/menda/test_block.js$script` 
Chyba będzie lepsze, bo kosmetyczne powodują większe zużycie pamięci.
