### ISSUE TITLE
menda.proste.info.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3005]
![capture](https://user-images.githubusercontent.com/15007183/28189826-bee5ae48-67f5-11e7-9329-23558898cbc5.PNG)

**Comment by MajkiIT** [comment]
dobre :)

**Comment by gzenio22** [comment]
XD haha nawet smiechłem :D

**Comment by hawkeye116477** [comment]
Jeszcze na proste.info.pl jest parę elementów do zablokowania.
![screenshot_20170714_112413](https://user-images.githubusercontent.com/19818572/28206689-2ddedad6-6887-11e7-8532-00f795cbd9dd.png)
`proste.info.pl###warning` - to samo co na menda.proste.info.pl
`proste.info.pl###notice_visitor` - to na smakołyki

**Comment by xxcriticxx** [comment]
@MajkiIT tego `menda.proste.info.pl###warning` chyba nie dodales?
