### ISSUE TITLE
gwiazdy.wp.pl

### ISSUE THREAD

**Issue by worldsdream** [MajkiIT/polish-ads-filter#3006]
I'm on adguard web for firefox

When i click an article on this page https://gwiazdy.wp.pl. I do get an ad showing and then it goes away. Also there is a sound playing in background when you open the page and i can't find anywhere to block the sound. 

Thank you

**Comment by MajkiIT** [comment]
I see that you open issue on Adguard and they added fitlers. 
https://github.com/AdguardTeam/AdguardFilters/issues/5669

**Comment by worldsdream** [comment]
This is a different website, correct?

**Comment by xxcriticxx** [comment]
@worldsdream whats different website?

**Comment by worldsdream** [comment]
Wp.pl is different then gwiazdy.wp.pl

**Comment by xxcriticxx** [comment]
@worldsdream gwiazdy is sub domain of wp
