### ISSUE TITLE
mikrokontroler.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3007]
![screenshot from 2017-07-14 06-58-57](https://user-images.githubusercontent.com/15007183/28209779-0178b324-6862-11e7-9af6-ec50a000b452.png)

**Comment by hawkeye116477** [comment]
`mikrokontroler.pl##.g `- to powinno schować wszystkie reklamy

A to na resztki po reklamach:
```
mikrokontroler.pl##.col-md-8.islemag-content-left > .mb30.orange.title-bg-line.title-border
mikrokontroler.pl##.mb30.light_red.title-bg-line.title-border
mikrokontroler.pl##.mb30.green.title-bg-line.title-border
mikrokontroler.pl###text-3 > .title-bg-line.dkgreen.title-border
mikrokontroler.pl###text-5
```

Przydałoby się jeszcze odblokować Aktualności, Artykuły i Polecane.
