### ISSUE TITLE
aupair.aifs.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3010]
Cookies

**Comment by hawkeye116477** [comment]
Ciekawe, na PC pojawia się i szybko znika, a na Androidzie jest cały czas.
`pl###cookies-message`

Podobna reguła już jest w filtrze:
`##[id^="cookies-message"]`

Coś ten uBlock nawala chyba

**Comment by xxcriticxx** [comment]
@hawkeye116477 na jakim androidzie ty testujesz?

**Comment by hawkeye116477** [comment]
Nvidia SHIELD Tablet, Android 7.0, Firefox 54.0.1

**Comment by gzenio22** [comment]
@hawkeye116477 Nie miales jeszcze aktualizacji andka do 7.1 ?

**Comment by hawkeye116477** [comment]
@gzenio22 Nie miałem jeszcze i nie wiem czy dostanę, bo ten tablet jest z 2014 roku (jest jeszcze jeden model K1 z 2015, ja mam LTE z 1 gen). Na początku miał 4.4, to i tak już sporo aktualizacji, nie wiem czy któreś urządzenie miało lepsze wsparcie.

**Comment by hawkeye116477** [comment]
Ok, wygląda na to, że nie zauważyłem opcji „Ignoruj ogólne filtry kosmetyczne", teraz jest jak na PC, nadal się pojawia, ale szybko znika.
