### ISSUE TITLE
saskakepa.waw.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3013]
http://www.saskakepa.waw.pl/news/1189/Uroczyste-otwarcie-zaulka-Marii-i-Aleksandra-Zabczynskich

![screenshot from 2017-07-14 20-15-56](https://user-images.githubusercontent.com/15007183/28234752-5bdc4690-68d1-11e7-8a30-6c1ae2617a8a.png)

**Comment by MajkiIT** [comment]
`saskakepa.waw.pl##.box:last-child`
