### ISSUE TITLE
instalki.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3027]
Promo gry

![instalki - gra](https://user-images.githubusercontent.com/23176832/28238331-a23b9ee4-6951-11e7-9274-13cd981465f8.png)

**Comment by gzenio22** [comment]
Ja tego nie mam

**Comment by adreporter** [comment]
Też tego nie mam.

**Comment by blocker999** [comment]
Bo miałem EasyPrivacy odhaczone
