### ISSUE TITLE
nowoczesne-garaze.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3028]
cookies

 Nasz serwis korzysta z plików cookies, by ułatwić użytkownikom korzystanie z naszych stron oraz w celach reklamowych. Jeśli nie chcesz, by pliki cookies były zapisywane na Twoim dysku zmień ustawienia swojej przeglądarki.

**Comment by hawkeye116477** [comment]
`||nowoczesne-garaze.pl/js/f.min.js$script`

**Comment by F4z** [comment]
@hawkeye116477 to popsuje prawidłowe działanie strony. Na przykład galeria będzie się nieprawidłowo wyświetlać tutaj - http://www.nowoczesne-garaze.pl/galeria-garaze-nowoczesne

**Comment by hawkeye116477** [comment]
@F4z Ciekawe, u mnie wyświetla się prawidłowo. Daj screena.

**Comment by F4z** [comment]
Chodzi mi o to, że na górze te obrazki się nie będą przewijać, a oprócz tego jak klikniesz w zdjęcie z galerii, to zamiast wyświetlić w galerii, to przechodzi bezpośrednio do obrazka.

**Comment by hawkeye116477** [comment]
@F4z Faktycznie. Czyli nie pozostaje nic innego, jak po prostu skorzystać z kosmetycznych.
`nowoczesne-garaze.pl##.polityka_ciastek`

**Comment by F4z** [comment]
@hawkeye116477 dokładnie 👍 😃
