### ISSUE TITLE
portalkomunalny.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3036]
resztki

![capture](https://user-images.githubusercontent.com/15007183/28240673-cd8389d4-6953-11e7-93f5-e4ca94670ba4.PNG)

**Comment by hawkeye116477** [comment]
```
portalkomunalny.pl###paszonecont_353022
portalkomunalny.pl###paszonecont_5485
portalkomunalny.pl###paszonecont_4180
```

**Comment by gzenio22** [comment]
Kurde ja to nie mam tu teraz co robic Xd

**Comment by xxcriticxx** [comment]
@hawkeye116477 tam jest tego wiecej

**Comment by hawkeye116477** [comment]
```
portalkomunalny.pl###paszonecont_783
portalkomunalny.pl###paszonecont_358085
portalkomunalny.pl###paszonecont_356689
portalkomunalny.pl###paszonecont_353023
```
Można też zablokować to okienko z nagle pojawiającym się komunikacie o newsletterze: `portalkomunalny.pl###newsletter-modal`

Ok, teraz powinno być wszystko.

**Comment by xxcriticxx** [comment]
na sub documentach jest wiecej

**Comment by hawkeye116477** [comment]
`portalkomunalny.pl###paszonecont_4182`

Reszta zostaje dla @gzenio22 :smiley:

**Comment by gzenio22** [comment]
@hawkeye116477 Ja sie nabijam :D Poza tym dopiero sie ucze XD

portalkomunalny.pl##.td-category-header

tylko tyle widze po dodaniu twoich reguł

**Comment by hawkeye116477** [comment]
Można jeszcze wywalić ten banner czy co to tam jest "Chcesz zareklamować się" `portalkomunalny.pl##.amc-info-bar`

**Comment by gzenio22** [comment]
Racja :)
