### ISSUE TITLE
yoy.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3039]
maybe ala cookie?

YOY.TV nie zajmuje się rozprowadzaniem plików chronionych prawem autorskim. Strona nie zawiera żadnych plików.   

![capture](https://user-images.githubusercontent.com/15007183/28241307-14e04a54-6960-11e7-91dc-73c93799a9ec.PNG)

**Comment by hawkeye116477** [comment]
@gzenio22 Masz robotę 😃

**Comment by gzenio22** [comment]
yoy.tv##.notice-content

**Comment by hawkeye116477** [comment]
Ja to bym powiedział, że to raczej do PopupBlockera, bo to nie jest komunikat cookie. 
Powiedział bym też, że może dobrze byłoby złączyć filtry cookies i PopupBlocker w jeden filtr polskie filtry annoyance.

**Comment by hawkeye116477** [comment]
@blocker999

**Comment by MajkiIT** [comment]
@hawkeye116477 no można, ale trzeba byłoby tworzyć oddzielną listę, bo ludzie nie zawsze chcą pakiet i robi się problem. Ta sama sytuacja była przy połączeniu PL i Popup Blocker. Zawsze możemy spróbować.

**Comment by hawkeye116477** [comment]
@MajkiIT Ok

**Comment by hawkeye116477** [comment]
@blocker999 Możesz dodać do PopupBlockera?

**Comment by hawkeye116477** [comment]
@xxcriticxx https://github.com/azet12/PopupBlocker/commit/c5e76c72c1b5c32e7c9653bc6dc95a1081b49e7f
