### ISSUE TITLE
CloudFlare "protects" list

### ISSUE THREAD

**Issue by IDKwhattoputhere** [MajkiIT/polish-ads-filter#304]
Since you use CloudFlare to protect the list downloads people who for example use Private Internet Access VPN (which is AFAIK the largest VPN provider) can not download any lists without completing a CloudFlare captcha security check. Since lists are downloaded in the background the user will not see the security check page and therefore will not be informed that they can't download any lists from certyficate.it
Other filter list providers like EasyList know about this problem and don't use CloudFlare.
If you can't drop CloudFlare for some reason you could start hosting the list on GitHub like some other filter list maintainers do.

**Comment by MajkiIT** [comment]
Thank for yours information. I try to stop using cloudflare and move filters to GitHub. Give me few days and I do it.

**Comment by IDKwhattoputhere** [comment]
Sounds awesome. @gorhill should probably change the URL in uBlock Origin then.

**Comment by MajkiIT** [comment]
I know I will write issue on @gorhill site.

**Comment by MajkiIT** [comment]
@IDKwhattoputhere 
https://github.com/gorhill/uBlock/issues/1275

**Comment by IDKwhattoputhere** [comment]
You are awesome. Thanks.
