### ISSUE TITLE
ergokantor.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3040]
bullshit na dole strony 

![capture](https://user-images.githubusercontent.com/15007183/28241399-b43b3248-6961-11e7-8524-8655fc977e23.PNG)

**Comment by gzenio22** [comment]
popup szanowny kliencie tego sie jeszcze blokowac nie nauczylem XD a tego na dole nie rozumiem chodzi ci o ten pasek czy o nasze banki?

**Comment by hawkeye116477** [comment]
Popup to chyba powinno trafić do tego pana @azet12 i jego filtrów PopupBlocker.

Można zablokować popup kosmetycznymi, ale w pewnym momencie strona się blokuje, tzn. nie można scrollować.

`ergokantor.pl###przesuwany_tekst` - to na ten "bullshit"

**Comment by hawkeye116477** [comment]
@MajkiIT `gorlice24.pl##.header-adblock` , to występuje też na innych stronach, może lepiej dać 'pl##.header-adblock`.
Ok, czyli zamykamy temat. Przekazałem już to do azeta.

**Comment by MajkiIT** [comment]
@hawkeye116477 ok dodane.
