### ISSUE TITLE
e-kedzierzynkozle.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3042]
ala cookie?

![capture](https://user-images.githubusercontent.com/15007183/28241954-9e4f2b72-696d-11e7-91eb-95b8b127b9d8.PNG)

**Comment by MajkiIT** [comment]
Gdzieś trzeba głębiej wejść ?

**Comment by xxcriticxx** [comment]
mooment

**Comment by xxcriticxx** [comment]
http://e-kedzierzynkozle.pl/Portal/Default.aspx?portal=Spolecznosciowy

**Comment by gzenio22** [comment]
o kurde nowe sztuczki maja XD

**Comment by hawkeye116477** [comment]
Czy ja wiem, ja bym regulaminu nie chował raczej...

**Comment by xxcriticxx** [comment]
aha

**Comment by gzenio22** [comment]
w sumie racja to juz chyba bylo by za wiele
