### ISSUE TITLE
oscarrak.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3045]
![capture](https://user-images.githubusercontent.com/15007183/28242332-b9645960-6976-11e7-8682-c798e086b58d.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx 
I sposób
Firefox: wpisz do paska adresu `about:config`, znajdź `dom.push.enabled`, ustaw to na `false` i sprawa załatwiona (wszystkie powiadomienia blokowane)
Chrome/Chromium/Vivaldi - wpisz do paska adresu `chrome://settings/content/notifications`, przełącz na `zablokowane` i sprawa załatwiona. A jak nie chcesz blokować powiadomień z wszystkich stron, tylko z wybranych, to też możesz dodać tam strony, na których mają być blokowane i gitara gra :smiley:

II sposób
Wklep to do uBlocka, może nie rozwali strony :smiley: `||oscarrak.pl/cdn-cgi/nexp/dok3v=1613a3a185/cloudflare/rocket.js$script`

**Comment by MajkiIT** [comment]
Mówisz o 1 sposobie ?

**Comment by hawkeye116477** [comment]
@MajkiIT Tak

**Comment by MajkiIT** [comment]
@hawkeye116477 jutro rano wrzucę

**Comment by hawkeye116477** [comment]
@xxcriticxx Why you using Firefox in English, not Polish :smile: ?

**Comment by MajkiIT** [comment]
@hawkeye116477 bo mieszka w USA

**Comment by hawkeye116477** [comment]
@MajkiIT Aha, to by wyjaśniało również dlaczego zawsze mówi po polsko-angielsku.

**Comment by xxcriticxx** [comment]
tak ja caly czas jestem z moda
