### ISSUE TITLE
msn.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3047]
cookies

https://www.msn.com/pl-pl/wiadomosci/other/mityng-w-madrycie-fajdek-zwyci%C4%99zc%C4%85-konkursu-rzutu-m%C5%82otem/ar-BBEqxLl

![screenshot from 2017-07-16 06-51-54](https://user-images.githubusercontent.com/15007183/28246902-525396b4-69f3-11e7-8016-7c0784ea1eee.png)

**Comment by hawkeye116477** [comment]
`msn.com###conditionalbanner`
