### ISSUE TITLE
Webpushe

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3054]
@MajkiIT 

`||www.snrcdn.net/sdk/*/synerise-javascript-sdk.min.js$script` - to jest z Neonetu, to oni się skarżyli tak?
`||oscarrak.pl/cdn-cgi/nexp/dok3v=1613a3a185/cloudflare/rocket.js$script`

Może lepiej byłoby przenieść to do osobnych filtrów w takim razie albo po prostu usunąć i nic z tym nie robić, gdyż i tak w przeglądarce można to zablokować.

**Comment by MajkiIT** [comment]
@hawkeye116477 spokojnie, nie ma spiny. Nie wiem kto to, bo się nie podpisał. Jutro się przekonamy. Nie róbmy nerwowych ruchów. Najwyżej przeniesiemy do oddzielnych filtrów.

**Comment by hawkeye116477** [comment]
@MajkiIT Chodziło o chat, promocje koszykowe, kupony rabatowe, więc to na pewno jest ta reguła.

**Comment by xxcriticxx** [comment]
gdzie ktos otym pisal?

**Comment by hawkeye116477** [comment]
@xxcriticxx Tak, Majki dostał taką wiadomość. Pisali o promocjach, jakiś rabatach, więc to raczej na 100% Neonet.

**Comment by xxcriticxx** [comment]
@MajkiIT znowu dostaniesz pendriva jak zdejmiesz to z listy

**Comment by gzenio22** [comment]
lo luju Xd ostatnio spory tutaj kipisz z tymi pretensjami w sumie jak to jest w opcjach przeglądarki @MajkiIT  wstaw ten tutorial co @hawkeye116477 napisał w którymś temacie na stronę certificate i po bólu się ludzi będzie odsyłać i ruch na stronie się może zwiększy :) Trzeba szukać plusów w negatywach :D

**Comment by hawkeye116477** [comment]
@gzenio22 https://www.certyficate.it/blokowanie-powiadomien-za-pomoca-przegladarki/

**Comment by MajkiIT** [comment]
@hawkeye116477 masz nosa.

> Dokładnie chodzi o to:
> https://github.com/MajkiIT/polish-ads-filter/issues/2732
> 
> Musimy wykonać kilka zmian, tak aby bez czarów wycinać webpush jakąś regułą u was ale  zrobimy to. Chyba, że rekomendujecie jakieś inne rozwiązanie?

**Comment by hawkeye116477** [comment]
@MajkiIT Żadnej innej takiej reguły sklepowej dla webpushy nie było, więc łatwo było się domyślić.

**Comment by xxcriticxx** [comment]
@MajkiIT tutaj pod wiki pozna to dodac

darmowych pendriow nie bendzie?

**Comment by xxcriticxx** [comment]
Powiadomienia Push - zepchnij AdBlocka ze sceny i skutecznie docieraj do swoich klientów! 

Czy chcesz dowiedzieć się jak zwiększać Open Rate o 50% a Click-Through Rate nawet dwukrotnie? Pragniesz znaleźć sposób na to, aby Twoje oferty docierały do użytkowników używających AdBlocka i filtrów antyspamowych? Poznaj Powiadomienia Push. 

http://mamstartup.pl/marketing/10883/powiadomienia-push-zepchnij-adblocka-ze-sceny-i-skutecznie-docieraj-do-swoich-klientow

**Comment by hawkeye116477** [comment]
@xxcriticxx  Pewnie nie, ale rózgę może wyślą 😃

**Comment by MajkiIT** [comment]
Odpowiedź z Neonet

> Dzięki za odpowiedź,
> 
> Jutro do końca dnia wydzielimy webpushe tak aby można było je wyciąć na poziomie blokowania requestu przez regexpa.

**Comment by hawkeye116477** [comment]
@gzenio22 W jakich negatywach? Żadnych negatywów tu nie ma, w przeglądarce jest opcja, można wybrać czy chce się powiadomienia czy nie, od razu po wejściu na stronę się pytają i przeglądarka to zapamiętuje. Więc jak dla mnie zbędne jest blokowanie tego blokerem. 
To tak jakbyście weszli na wp.pl i pojawiło się pytanie „Czy chcesz oglądać nasze superowe reklamy?". Do wyboru Tak, Nie. Po wybraniu nie, strona byłaby bez reklam, oczywiście działało by to na stałe. Też byście mimo to blokowali reklamy regułami w blokerze :smiley: ?

**Comment by xxcriticxx** [comment]
@MajkiIT jaka byla nasz odpowiedz?

@hawkeye116477 browser nie zawsze zapamietuje twoja odpowiedz

**Comment by hawkeye116477** [comment]
@xxcriticxx Znalazłeś jakąś stronę przy której zapomina?

**Comment by xxcriticxx** [comment]
bendziemy sprawe monitorowac zobaczymy co z tego wyjdzie

**Comment by hawkeye116477** [comment]
Mnie się wydaję, że jak tak bardzo chcecie blokować powiadomienia, to może lepiej byłoby to dać do osbnych filtrów. Gdyż np. w przypadku sklepu wydaje mi się, że powiadomienia mogą się  komuś przydać.

**Comment by xxcriticxx** [comment]
@hawkeye116477 mozna

**Comment by MajkiIT** [comment]
@xxcriticxx Nie to była ich odpowiedź. Już poprawiłem Neonet.

**Comment by hawkeye116477** [comment]
I przy okazji pewnie parę innych sklepów, ta domena snrcdn należy do Synerise z Krakowa. 
http://www.money.pl/gospodarka/wiadomosci/artykul/synerise-marketing-startup,240,0,2297328.html
