### ISSUE TITLE
teletrade-dj.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3055]
cookies

Strona TeleTrade korzysta z plików cookies w celu polepszenia nawigacji na stronie. Kontynuując przeglądanie tej strony, zgadzasz się na wykorzystanie cookies. Jeśli nie zgadzasz się z wykorzystaniem plików cookie, możesz zmienić ustawienia przeglądarki w dowolnym momencie. Więcej

**Comment by hawkeye116477** [comment]
`teletrade-dj.pl###pp`
