### ISSUE TITLE
mywrestling.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3056]
moze ktos sprawdzic u mnie adblcok wrocil

**Comment by hawkeye116477** [comment]
Ta, mają mnie na Waterfoxie. Ale uBlock Protector to blokuje.
Zrób tak: 
1. Zainstaluj Chrome Store Foxified z https://addons.mozilla.org/pl/firefox/addon/chrome-store-foxified/ i uruchom ponownie Firefoxa.
2. Wejdź w about:config, znajdź xpinstall.signatures.required i ustaw na false.
3. Wejdź na https://chrome.google.com/webstore/detail/ublock-protector-extensio/ggolfgbegefeeoocgjbmkembbncoadlb i kliknij add to Firefox, a następnie save unsigned addon to file.
4. Przeciągnij zapisany plik xpi na pasek adresu i zgódź się na instalację.
5. Uruchom ponownie Firefoksa i ciesz się z działającego uBlock Protector Extension. Tylko pamiętaj, że **twórca rozszerzenia nie udziela wsparcia dla Firefoksa**.

A potem jak już to zrobisz, to wywal AAK Continued, filtr i skrypt wywal i włącz filtr uBlock Protector w uBlock Origin.

A, tylko jak będzie update Protectora, to będziesz musial znowu z Chrome Store instalować.

A może są jacyś chętni by sforkować Protectora, by działał na Foksie, bo tylko dodać trzeba 1 linijkę i będzie śmigać,  tylko część tego co jest zrobione w EMCA Script 2017 może nie działać, bo Fox jeszcze w pełni tego nie obsługuje. Jak sforkuje ktoś, to można zrobić bota, co by puszczał updaty do AMO i by nie trza było się bawić w ręczne updaty.

**Comment by xxcriticxx** [comment]
Ok teraz sobie przypomialem ze aak-cont jest troche opuzniony

**Comment by gzenio22** [comment]
u mnie na operze tez jest dupki...

**Comment by hawkeye116477** [comment]
@gzenio22 Używasz AAK Cont na Chroperze? Przecież możesz instalować dodatki z Chroma za pomocą https://addons.opera.com/pl/extensions/details/download-chrome-extension-9/  :stuck_out_tongue:

**Comment by hawkeye116477** [comment]
Ja w sumie lubię korzystać z Waterfoksa i mógłbym na jakiś czas się zająć forkiem uBlock Protector for Firefox/Waterfox, tylko nie wiem czy na stałe, gdyż niedługo nadejdą zmiany, nie będzie już dawnych rozszerzeń Firefoksa, więc nie wiem czy kiedyś nie porzucę WF na rzecz Vivaldiego, w którym sporo rzeczy można zmieniać pod siebie, dodają nowe funkcjonalności, zamiast je usuwać, a Mozilla tylko wywala, nie podoba mi się kierunek w jakim zmierza Firefox.
A tylko, jakby coś nie działało na Foxie, tak jak to działa na Chromowatych, to ja bym nie mógł oferować supportu, gdyż nie znam się na tych całych skryptach js, ale to też z czasem Mozilla chyba doda pełne wsparcie ECMAScript 2017, więc może nie będzie problemu.
To jak działamy, jest tu ktoś kto mógłby oferować support dla uBlock Protector for FF/WF?

**Comment by gzenio22** [comment]
@hawkeye116477 Ja sie kurde widze ze serio dopiero ucze :D ale ciezko jest kiedy chcesz sie czegos nauczyc a ogranicza cie mobilny internet nie moge nawet uczyc sie programowania z filmikami na YT bo net spier**

Co do  rozszerzen nie wiedzialem o tym dzieki za cynk :)

**Comment by hawkeye116477** [comment]
@MajkiIT Co o tym sądzisz? Robimy fork uBlock Protectora dla Foxa? Można zrobić oddzielny team dla Foxowego Protectora i na nim stworzyć forka i dać odpowiednim ludziom uprawnienia, by mogli przeprowadzać zmiany w repozytorium. Przydałoby się też utworzyć jakieś konto deweloperskie dla teamu/jednej osoby w AMO. Nie wiem tylko jak z supportem, bo ja na skryptach się nie znam, nie mam pojęcia o przepisywaniu ECMAScript 2017 na te co obecnie działają w FF, niby można też nic nie robić, tylko czekać aż Mozilla da całkowite wsparcie dla ECMAScript 2017, ale nie wiem czy to dobry pomysł....

https://help.github.com/articles/creating-a-team/

**Comment by xxcriticxx** [comment]
@hawkeye116477 unas nie ma takiego magika

**Comment by hawkeye116477** [comment]
@xxcriticxx Serio, nikt się nie zna na skryptach? A szkoda, takie plany miałem

**Comment by xxcriticxx** [comment]
nasz wojsko jest narazie male moze kiedys cos z tego bendzie

**Comment by MajkiIT** [comment]
@hawkeye116477 tak jak mówi @xxcriticxx brak u nas osoby, która umie biegle JS. Oczywiście można się na to rzucić, ale nie będzie to ot tak.
