### ISSUE TITLE
mac-world.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3058]
@MajkiIT jak bendzie blokujemy czy nie?

https://mac-world.pl/2016/01/netflix-w-polsce-ale-tylko-teoretycznie/

![screenshot from 2017-07-18 08-14-13](https://user-images.githubusercontent.com/15007183/28316523-3aac81f2-6b91-11e7-8ad9-1fdd8c63dfe1.png)

**Comment by hawkeye116477** [comment]
@xxcriticxx Naciśnij don't allow i problem rozwiązany. A jak nie chcesz w ogóle mieć żadnych powiadomień to wpisz do paska adresu about:config, znajdź dom.push.enabled, ustaw to na false i sprawa załatwiona

**Comment by hawkeye116477** [comment]
Przy okazji zgłosiłem popupa https://github.com/azet12/PopupBlocker/issues/30

**Comment by xxcriticxx** [comment]
@hawkeye116477 zaczekam na odpowiedz @MajkiIT

**Comment by MajkiIT** [comment]
@xxcriticxx tak zablokujemy.

**Comment by hawkeye116477** [comment]
@MajkiIT To nie będzie takie proste. Można dać coś takiego:
`||mac-world.pl/cdn-cgi/nexp/dok3v=1613a3a185/cloudflare/rocket.js$script`
, ale to wywali tło strony i pewnie inne przydatne rzeczy. A w przeglądarce można nacisnąć blokuj z zaznaczeniem zapamiętaj tę decyzję i więcej nie będą pytać, no chyba że przy czyszczeniu danych zaznaczysz ustawienia witryn.
