### ISSUE TITLE
allonline.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3059]
@F4z da rade cos stym zrobic?

Odtwarzacz pojawi się za 10s.

**Comment by F4z** [comment]
@xxcriticxx raczej tylko skryptem.
Najprościej chyba by było ustawić `count` na `1`.
i od razu "odkryć" odtwarzacz:
`allonline.pl#$##player_counter { display: none!important; }`
`allonline.pl#$##video_url { display: block!important; }`

Przykład takiego skryptu, sprawdzałem w Chrome z Tampermonkey i nawet działa.
```
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://allonline.pl/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    Object.defineProperty(window,'count',{value:1});
})();
```

Możliwe, że da się to lepiej zrobić, ale to musiałbyś się zapytać kogoś kto się lepiej na tym zna :)

**Comment by hawkeye116477** [comment]
@xxcriticxx Wydaje mi się, że jspenguin takie czary robił dla jakiejś innej strony, tylko że on i Fox się nie lubią... Ale skoro da radę zainstalować Protectora na Firefoksie, to pisz do niego, tylko podeślij screen z Chroma do niego.

**Comment by xxcriticxx** [comment]
wszystkie te cuda mial zlikwidowac i skoncetrowac sie tylko na ad blaku tak ostatnio pisal ja te 10 sec przezyje thank you for you help

**Comment by hawkeye116477** [comment]
@xxcriticxx https://openuserjs.org/scripts/levushka/Video_adscounter_skipper

**Comment by xxcriticxx** [comment]
@hawkeye116477 skontaktuj się z Przemekem od skriptu player może tobie pomoże z protektorem

**Comment by hawkeye116477** [comment]
@xxcriticxx Tylko nie wiem czy warto na jedynie ponad miesiąc. Ja pewnie 1 września pożegnam się na dobre z Waterfoksem, gdyż chyba wtedy mają wyłączyć XUL'owe rozszerzenia. Szczególnie jeśli All in One Sidebar przestanie działać, to przejdę na Vivaldiego.
Oczywiście czytałeś to co mi podesłał twórca?
```
Hi, first, thank you for doing this, if you have time, please also consider offer Safari support. 
There are, however, a few things you should keep in mind: 
- Firefox will inject content script to all opened tabs when the extension starts, this can cause it to malfunction, and could, in some case, allow unwanted code execution. I cache function pointers on the real document-start to prevent it, you need to add a check to content script. 
- `a.inject` and `a.injectWithRuntime`, as well as every function that depends on them, will trip on Firefox CSP. The standard says extensions are excluded from CSP, so this is a bug in Firefox, but they seems to be not fixing it. How to workaround this is up to you, good luck. 
- Firefox does not allow redirecting to data URL for XMLHttpRequest, which breaks some of my solutions, you need to fix those. `a.loopback` should be a handy function. 
- Modifying headers can cause conflicts with uBlock Origin, even CSP and Allow-Access can be patched by editing headers, you should think twice before doing that. 
- You need a way to sync upstream solutions as it is a fast moving project. 
- If you are wondering why I'm not offering Firefox support, now you know. 
```
Jak się z nim skontaktować, jaki on ma nick?

**Comment by xxcriticxx** [comment]
@hawkeye116477 

https://greasyfork.org/en/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod-autor-przemek

**Comment by hawkeye116477** [comment]
@xxcriticxx https://greasyfork.org/en/forum/discussion/27360/x

Napisałem w Feedback, bo nie ma tam żadnego maila, ni nic, miejmy nadzieję, że odpisze.

**Comment by xxcriticxx** [comment]
@hawkeye116477 powodzenia

**Comment by hawkeye116477** [comment]
@xxcriticxx Mam złą wiadomość dla ciebie:
```
Niestety, osobiście nie lubię JavaScriptu (co widać po jakości kodu) i nie potrafiłbym naprawiać takich rzeczy dla zewnętrznych rozszerzeń. Szczerze mówią nie miałbym na to zbytniej ochoty.

Z doświadczenia mogę napisać ze Firefox jest problematyczny i osobiście po prostu odradzałbym używanie go. Nie wiem czemu, ale Firefox komplikuje wszystko (np. w tym skrypcie trzeba było używać innych metod wyświetlania linków na nowo otwartej karcie, itp.). Nie dziwię się, że developerzy po prostu nie wydają rozszerzeń na tą przeglądarkę, bo nikomu nie chce się siedzieć kilka godzin, czytać dokumentację i zastanawiać się dlaczego akurat na Firefoxie dana opcja nie działa. 
```

**Comment by xxcriticxx** [comment]
@hawkeye116477 chyba muszę się z tobą zgodzić to chyba pora na chroma

**Comment by hawkeye116477** [comment]
@xxcriticxx Niekoniecznie Chroma, jest jeszcze Vivaldi i Opera.

**Comment by HateAds** [comment]
@xxcriticxx @hawkeye116477 Tak z ciekawości ( ja Chromea używam ) czy u Was na Firefoxie / Vivaldim dzieją się takie same cuda jak u mnie? To jest z linku który dałeś wyżej. Dałem full screena, później minimalizuje i taka akcja ...
![123](https://user-images.githubusercontent.com/29756590/28493400-9e2fb590-6f16-11e7-9c1f-d487af985cae.png)

**Comment by hawkeye116477** [comment]
@HateAds Na Firefoksie, ten filmik nawet się nie odpala, bo w AAK Cont się obijają i może dopiero za rok ten player odblokują.

**Comment by xxcriticxx** [comment]
@HateAds przetestuje za godzinke i dam znac

**Comment by hawkeye116477** [comment]
@HateAds Na Vivaldim jest wszystko ok. Pożegnaj się więc ze swoją starą nudną przeglądarką i pobierz przeglądarkę Vivaldi już dziś.

**Comment by hawkeye116477** [comment]
@HateAds Specjalnie zainstalowałem Chrome i tam jest ten efekt o którym mówisz. Także pobierz Vivaldiego albo Chromium, tam nic takiego nie występuje.

**Comment by HateAds** [comment]
@hawkeye116477  Zainstalowałem Vivaldi i u mnie jest ten sam problem co na Chromie. Ciekawe z czego to wynika, że u Ciebie działa ok a u mnie już nie.

**Comment by hawkeye116477** [comment]
@HateAds Sprawdzilem jeszcze raz i jednak występuje ten problem. Ale to jest tak, że raz tak nie ma, a raz jest.

**Comment by HateAds** [comment]
Widzę, że był ten temat otwarty przez @adreporter, ale został zamknięty.
https://github.com/MajkiIT/polish-ads-filter/issues/3000
@xxcriticxx I jak masz też ten problem ?

**Comment by xxcriticxx** [comment]
@HateAds na jakiej przeglondarce?

**Comment by HateAds** [comment]
@xxcriticxx  Na Chromie.

**Comment by xxcriticxx** [comment]
@HateAds na chromie mam ten sam effect co ty na foxie film mi znika

**Comment by xxcriticxx** [comment]
![screenshot from 2017-07-22 15-59-28](https://user-images.githubusercontent.com/15007183/28494270-1553ee36-6ef7-11e7-96ab-537bb385c474.png)

**Comment by xxcriticxx** [comment]
@jspenguin2017 can you look in to this please we have ghost player while playing vid

**Comment by HateAds** [comment]
@hawkeye116477 @xxcriticxx Wygląda na to, że pingwin naprawił.

**Comment by jspenguin2017** [comment]
`wp.pl` is the worst pain in the rear, my hack is falling apart, I think we should start from scratch and find a good and reliable solution that lasts.

**Comment by xxcriticxx** [comment]
@jspenguin2017 great idea we can test any time

**Comment by jspenguin2017** [comment]
Are you guys expecting me to do everything alone?

**Comment by xxcriticxx** [comment]
Nobody knows java here as good as you.

**Comment by hawkeye116477** [comment]
@jspenguin2017  And this one @uBlock-user can't help, does not know about it?

**Comment by jspenguin2017** [comment]
I don't really know Java either, but they aren't using it. Java doesn't really run in browsers anymore.

**Comment by xxcriticxx** [comment]
@jspenguin2017 we are willing to help any possible way

**Comment by jspenguin2017** [comment]
I need help investigating what their player is expecting and what their player is checking. 
The old `hasSentinel` patching seems to be now dysfunctional.

**Comment by xxcriticxx** [comment]
@jspenguin2017 any type of instructions would help

can we always ask @szymon1118 he was big help before with our favorite site

**Comment by jspenguin2017** [comment]
Do it your way, my way doesn't really work, or I would have fixed it.

**Comment by hawkeye116477** [comment]
@xxcriticxx He uses JavaScript, not Java. https://www.java.com/pl/download/faq/java_javascript.xml

**Comment by xxcriticxx** [comment]
close issue
