### ISSUE TITLE
bardotti.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3060]
strona jest cala przyciemniona cookie fix potrzebny

**Comment by hawkeye116477** [comment]
`bardotti.pl###a86bcb8250622e078b2d285b834198636`

**Comment by hawkeye116477** [comment]
`bardotti.pl##.no-subtitle.no-title.wdpu-823400.rounded.style-simple.no-img.wdpu-background.wdpu-container.wpmui-popup`
@xxcriticxx Działa?

**Comment by xxcriticxx** [comment]
nie mam teraz czasu sprawdzic sorry

**Comment by gzenio22** [comment]
@hawkeye116477 Dziala :)
