### ISSUE TITLE
mojeauto.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3064]
maybe?

![screenshot from 2017-07-18 20-05-14](https://user-images.githubusercontent.com/15007183/28344922-bc717ee6-6bf4-11e7-907b-dcfd876f56e2.png)

**Comment by gzenio22** [comment]
mojeauto.pl###ma-top-layer

Kurde XD chyba sie udalo

**Comment by hawkeye116477** [comment]
A to nie do PopupBlockera? 

![screenshot_20170719_092831](https://user-images.githubusercontent.com/19818572/28355553-cdbfe712-6c64-11e7-97f5-553ba23e8858.png)

A to zobacz więcej, blokujemy?
`mojeauto.pl##.pdr-contener.ui-helper-clearfix`

**Comment by gzenio22** [comment]
@hawkeye116477 Tez sie nad tym zastanawialem utwierdziles mnie w tym ze tak :)

**Comment by hawkeye116477** [comment]
https://github.com/azet12/PopupBlocker/commit/1cf2ef2bc0bf182bb940c853ced4ef97f4e76fac i gitara gra, można temat zamknąć

**Comment by hawkeye116477** [comment]
@xxcriticxx https://github.com/azet12/PopupBlocker/commit/1cf2ef2bc0bf182bb940c853ced4ef97f4e76fac i gitara gra, można temat zamknąć
