### ISSUE TITLE
kulturaonline.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3066]
http://kulturaonline.pl/literatura,kulturaonline.pl,literatura.html

![screenshot from 2017-07-19 08-11-41](https://user-images.githubusercontent.com/15007183/28366281-051595c8-6c5a-11e7-860e-dcef9d64857c.png)

**Comment by gzenio22** [comment]
kulturaonline.pl###movieBox
