### ISSUE TITLE
jellinek.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3073]
cookies

Strona korzysta z plików cookie w celu realizacji usług zgodnie z Polityką dotyczącą cookies. Możesz określić warunki przechowywania lub dostępu do cookie w Twojej przeglądarce.

**Comment by hawkeye116477** [comment]
`jellinek.pl###okno_18only`

**Comment by hawkeye116477** [comment]
@MajkiIT To już raczej można zamknąć.
