### ISSUE TITLE
jbzd.pl

### ISSUE THREAD

**Issue by mumaguma** [MajkiIT/polish-ads-filter#3076]
### Co trzeba zrobić aby reklama/element się pojawił
1. pojawia się blur z webkitu w css. Element container.blur w css
https://jbzdy.pl/application/assets/web/styles/styles.min.css?v=98
jest:
#container.blur{-webkit-filter:blur(5px);-moz-filter:blur(5px);-o-filter:blur(5px);-ms-filter:blur(5px);filter:blur(5px)}
2.
3.

### Twoja konfiguracja
**Przeglądarka:**
Firefox 54.0.1 32bity
**Operating system:**
win7pro 64 bity z sp1

**Blocker:**
ublock origin

**Używane filtry:**
1.POL: polskie filtry do Adblocka i uBlocka​​​​​
​​2. POL: polskie filtry do uBlocka uzupelnienie​
3. uBlockFilters
4.

### Zrzut ekranu
http://i.share.pho.to/e489ef14_o.png

**Comment by gzenio22** [comment]
adblock detect ja tego nie umiem zdjac

**Comment by F4z** [comment]
Powinno wystarczyć:
```
jbzdy.pl#@#.pub_300x250
jbzdy.pl#@#.pub_300x250m
jbzdy.pl#@#.pub_728x90
jbzdy.pl#@#.text-ad
jbzdy.pl#@#.textAd
jbzdy.pl#@#.text_ad
jbzdy.pl#@#.text_ads
jbzdy.pl#@#.text-ads
jbzdy.pl#@#.text-ad-links
```

**Comment by xxcriticxx** [comment]
podam na ad protectora

**Comment by mumaguma** [comment]
F4z: wystarczyło, bardzo dziękuję!
