### ISSUE TITLE
tvswinoujscie.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3077]
![capture](https://user-images.githubusercontent.com/15007183/28436272-53d764e2-6d64-11e7-97ae-9881f7b021aa.PNG)

**Comment by gzenio22** [comment]
widze 3 reguły nie wiem ktora bedzie naj odpowiedniejsza

1tvswinoujscie.pl##.visible-lg > a[href="https://tixer.pl/dirty-dancing-music-dance-show-5-swinoujscie-2017-07-26-2000,417,10443.html"]
2 tvswinoujscie.pl##.advert-A1.text-center.col-lg-12 > .visible-lg
3 ##.advert-A1.text-center.col-lg-12

**Comment by hawkeye116477** [comment]
Może takie coś lepsze?
tvswinoujscie.pl##.rbox.row:nth-of-type(1)

To na reklamy po lewej:
```
tvswinoujscie.pl##.advert-B1
tvswinoujscie.pl##.boards.widget
```
