### ISSUE TITLE
google.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3078]
Filtry social nawalają trochę, blokują tytuly stron w Google, jeśli prowadzą do Facebook'a, YouTube'a albo Twitter'a.
Czy tak miało być, efekt zamierzony?
![screenshot_20170720_230650](https://user-images.githubusercontent.com/19818572/28438929-23df858a-6da0-11e7-9c56-09327942cfcb.png)

![screenshot_20170720_233334](https://user-images.githubusercontent.com/19818572/28439818-e5701496-6da3-11e7-94bb-90bce782335f.png)

![screenshot_20170720_233222](https://user-images.githubusercontent.com/19818572/28439781-b6020660-6da3-11e7-9f32-1d28d71b7398.png)

Zgaduję, że to wszystko powoduje taki problem właśnie:
```
pl##a[href^="http://facebook.com/"]
pl##a[href^="http://instagram.com/"]
pl##a[href^="http://plus.google.com/"]
pl##a[href^="http://twitter.com/"]
pl##a[href^="http://vimeo.com/"]
pl##a[href^="http://youtube.com/"]
pl##a[href^="http://linkedin.com/"]
pl##a[href^="http://pinterest.com/"]
pl##a[href^="http://www.facebook.com/"]
pl##a[href^="http://www.instagram.com/"]
pl##a[href^="http://www.plus.google.com/"]
pl##a[href^="http://www.twitter.com/"]
pl##a[href^="http://www.vimeo.com/"]
pl##a[href^="http://www.youtube.com/"]
pl##a[href^="http://www.linkedin.com/"]
pl##a[href^="http://www.pinterest.com/"]
pl##a[href^="https://facebook.com/"]
pl##a[href^="https://instagram.com/"]
pl##a[href^="https://plus.google.com/"]
pl##a[href^="https://twitter.com/"]
pl##a[href^="https://vimeo.com/"]
pl##a[href^="https://youtube.com/"]
pl##a[href^="https://linkedin.com/"]
pl##a[href^="https://pinterest.com/"]
pl##a[href^="https://www.facebook.com/"]
pl##a[href^="https://www.instagram.com/"]
pl##a[href^="https://www.plus.google.com/"]
pl##a[href^="https://www.twitter.com/"]
pl##a[href^="https://www.vimeo.com/"]
pl##a[href^="https://www.youtube.com/"]
pl##a[href^="https://www.linkedin.com/"]
pl##a[href^="https://www.pinterest.com/"]
```

**Comment by blocker999** [comment]
@hawkeye116477 

Ok dzięki że to zgłaszasz, przyjrzę się temu bliżej i coś zaradzimy, chociaż nieukrywam że i wtym wypadku licze na pomoc @F4z .

" Czy tak miało być, efekt zamierzony? " raczej uboczny.

**Comment by hawkeye116477** [comment]
@blocker999 Jaki uboczny? Jako ahref są linki i to po prostu blokuje linki które zaczynają się od https://www.youtube.com/ , itd. 
Nie wiem co chcialeś w ten sposób zablokować, ale nie tędy droga.

**Comment by MajkiIT** [comment]
@hawkeye116477 no to mnie złapałeś ... wyszło, że się nie skupiłem. Poprawię dzisiaj błędy to będzie już Ok.

**Comment by blocker999** [comment]
@hawkeye116477 

Co do tych reguł z " ahref " to domyślałem się że coś namieszają ale cały  czas wierze że da się to jakoś nabie jest prawić i o opinie proszę @F4z 

Poprostu dla Cie to oczywiste niestety dlamnie nie.

I teraz te reguły całkowicie usunąć czy da się to naprawić dodatkowymi regułami albo może poczekajmy na opinie @F4z ?.

**Comment by blocker999** [comment]
@F4z  BARDZO PROSZĘ O POMOC !!!

**Comment by F4z** [comment]
Moim zdaniem najlepiej będzie to usunąć, bo może za dużo ukrywać.
Taki najprostszy przykład; wystarczy, że ktoś na stronie w domenie `.pl` wstawi odnośnik do filmu na YouTubie albo do samego YouTuba, to jedna z powyższych reguł to wytnie, a raczej nie takie było założenie.
`<a href="http://www.youtube.com/">YouTube</a>`

Zresztą napisał już o tym hawkeye116477

**Comment by xxcriticxx** [comment]
@F4z a nieda rady tego regexem załatwić co @blocker999 chce uzyskać

**Comment by F4z** [comment]
@xxcriticxx żeby cokolwiek zrobić najpierw musiałbym zobaczyć element, który trzeba ukryć :)

**Comment by xxcriticxx** [comment]
Gdzie jest ten @blocker999

**Comment by blocker999** [comment]
@xxcriticxx TU, zaraz się tym zajme

**Comment by blocker999** [comment]
@F4z 
Tych elementów jest pełno, np na antyweb.pl na głównej u góry, generalnie chodziło mi głównie o blokade widzetów a nie blokade linków, nieda się dodać jakiegoś uniwersalnego wyjątku?.

**Comment by xxcriticxx** [comment]
@blocker999 link i screenshot please

**Comment by hawkeye116477** [comment]
@blocker999 
antyweb.pl##.fb.btn-tools
antyweb.pl##.tw.btn-tools

**Comment by hawkeye116477** [comment]
@xxcriticxx On ma dylemat https://github.com/azet12/PopupBlocker/issues/34 . Komuś ten popup z polityką w ogóle ostatnio się wyświetlał, pytam tych oczywiście co mają wyłączony PopupBlocker?

**Comment by blocker999** [comment]
@hawkeye116477 wiem że można to różnymi regułami zablokować ale użyłem " ahref " gdyż chciałem sobie oszczędzić roboty lecz niespodziewałem się że to przysporzy tyle problemów.

**Comment by hawkeye116477** [comment]
@blocker999 Cwaniak, no niestety, nie możesz iść taką drogą na skróty.

**Comment by blocker999** [comment]
@hawkeye116477 Szkoda, ale poczekajmy na opinie innych, co ?.

**Comment by hawkeye116477** [comment]
@blocker999 Mistrz @F4z już odpowiedział, ale ok.

**Comment by xxcriticxx** [comment]
@hawkeye116477  delikatnej please

**Comment by hawkeye116477** [comment]
@xxcriticxx Ok

**Comment by blocker999** [comment]
@MajkiIT a Ty co o tym wszystkim sądzisz?

**Comment by hawkeye116477** [comment]
Racja, sorry, powinienem trochę delikatnej

**Comment by xxcriticxx** [comment]
@hawkeye116477 dzieki

**Comment by MajkiIT** [comment]
@blocker999 wiem, że chciałeś zrobić to jak najogólniej, ale tak się czasami zdarza. Usuńmy te reguły i będziemy to prostować. Mam usunać?

**Comment by blocker999** [comment]
@MajkiIT OK usuń

**Comment by hawkeye116477** [comment]
@blocker999 @MajkiIT Problem jest już rozwiązany, więc zamykam temat. 
@blocker999 A gdybyś potrzebował pomocy z widgetami FB czy czegoś tam innego, to załóż nowy temat.
