### ISSUE TITLE
simet.com.pl 

### ISSUE THREAD

**Issue by maciejtarmas** [MajkiIT/polish-ads-filter#3079]
### Co trzeba zrobić aby reklama/element się pojawił
1. Wejdź na stronę :)
2. ???
3. PROFIT!!!

### Twoja konfiguracja
**Przeglądarka:** Safari 10.1.2 (12603.3.8)

**Operating system:** macOS 10.12.6 (16G29)

**Blocker:** uBlock Origin v1.12.5.100

**Używane filtry:**
1. uBlock Filters
2. Adblock Warning Removal List
3. EasyList
4. EasyPrivacy
5. Malware domains
6. Anti-ThirdpartySocial
7. Fanboy’s Annoyance List
8. Fanboy’s Social Blocking List
9. Peter Lowe’s Ad and tracking server list
10. POL: polskie filtry do Adblocka i uBlocka
11. POL: polskie filtry do uBlocka uzupelnienie
12. AlleBlock

### Zrzut ekranu

![screen shot 2017-07-21 at 07 07 45](https://user-images.githubusercontent.com/3435387/28449838-5e70d698-6de3-11e7-86ae-e684dabb8769.png)

**Comment by hawkeye116477** [comment]
Ciekawe, nigdy nie słyszałem o takich filtrach: https://github.com/maciejtarmas/AlleBlock .
Kolejne filtry pewnie będą się nazywać WPBlock 😃  .

@maciejtarmas Jakie ciacha, Delicje czy Pieguski, a może Jeżyki? 😺 
Na PC nic nie widzę, za to na Androidzie na Foxie już tak. Na Andku niestety ten filtr nie działa: `##div[class*="cookie"]`. Za to działa ten: `pl##div[class*="cookie"]`.
Zaraz zaraz, ty nie masz odpowiednich filtrów. Ściągnij odpowiednie filtry z https://www.certyficate.it/adblock/ .

**Comment by maciejtarmas** [comment]
Aaa, dzięki. Jakoś nie pomyślałem, że jest tego więcej niż dwa domyślne w uBlocku :)

"Adblock & uBlock polish cookies filters" wycięło to w cholerę i po sprawie.

> Ciekawe, nigdy nie słyszałem o takich filtrach: https://github.com/maciejtarmas/AlleBlock .
> Kolejne filtry pewnie będą się nazywać WPBlock 😺 .

Spokojnie, nie planuję kolejnych  :)

Ale jakby co to zapraszam do zgłaszania błędów, tym bardziej, że jak znajdę chwilę czasu to dojdzie tam parę dodatkowych serwisów i sam pewnie przestanę to ogarniać w takim stopniu, jak teraz.

**Comment by hawkeye116477** [comment]
@maciejtarmas Jeszcze oprócz tego co tam jest na tej stronie, jest PopupBlocker: https://raw.githubusercontent.com/azet12/PopupBlocker/master/PPB.txt

**Comment by xxcriticxx** [comment]
Pop up wymyślił blocker999 z KAD dlatego unas tego niema

**Comment by hawkeye116477** [comment]
@xxcriticxx Ok, w takim razie dlaczego KAD tam jest wymieniony, a PopupBlockera nie ma?

**Comment by xxcriticxx** [comment]
@hawkeye116477 pytaj @MajkiIT

**Comment by maciejtarmas** [comment]
> AlleBlock może też powinien trafić na stronę.

Byłbym zaszczycony, z tym że dobrze by było wrzucić jakiś opis, bo to jest naprawdę bardzo brutalna lista ;)

Dodatkowo może linki do głównych stron czy projektów na GitHubie tych list z zewnątrz, żeby nie było wątpliwości, do kogo zgłaszać błędy.

**Comment by xxcriticxx** [comment]
@maciejtarmas widze ze masz plana na gumtree i nokaut

**Comment by maciejtarmas** [comment]
Pewnie w przyszłym tygodniu albo jeszcze następnym dodam.

**Comment by xxcriticxx** [comment]
maybe ebay.pl in the future?

**Comment by MajkiIT** [comment]
Buduje nowy template na stronę ==> https://www.certyficate.it/adblock/ . Myślałem o czyms na wzór ==> https://filterlists.com/ Jeśli dobrze pójdzie w niedziele skończę. Wypiszę wszystkie filtry jakie znamy.

**Comment by maciejtarmas** [comment]
@xxcriticxx 

> maybe ebay.pl in the future?

Właśnie nie wiem czy dorzucać eBay do AlleBlocka. Relatywnie mało użytkowników w Polsce.

Chodzi mi natomiast po głowie nowa lista traktująca eBay globalnie. I Amazona. Ale to kiedyś nie wiem kiedy i czy w ogóle.

**Comment by xxcriticxx** [comment]
@maciejtarmas Bendziesz musial nazwę filtrów zmienić

**Comment by maciejtarmas** [comment]
@xxcriticxx Coś wymyślę, ale wtedy target będzie i tak pod użytkownika anglojęzycznego/operującego językiem angielskim, więc to będzie na trochę innych zasadach niż AlleBlock, którego kieruję w zasadzie tylko do polskich użytkowników.

Na razie tematu nie ruszam z braku czasu i tego, że o ile kiedyś robiłem bardzo dużo zakupów na eBay i Amazonie w różnych częściach świata (np. płyty z Niemczech, Włoch, USA, czasami nawet Australii), to teraz z różnych względów za bardzo z tych serwisów nie korzystam.

Ale pomysł mam cały czas z tyłu głowy i jak ogarnę AlleBlocka na tyle, żeby pokryć duże polskie serwisy handlowe i uda mi się rozkręcić zgłaszanie błędów na GitHubie, to czemu nie. Jak czas pozwoli, to rozkręcę temat.

**Comment by hawkeye116477** [comment]
@maciejtarmas Amazon też ma polską stronę: https://www.amazon.de/?language=pl_PL

**Comment by xxcriticxx** [comment]
@maciejtarmas znasz kogos co sie zna na java? szukamy takiej osoby do tego projektu.

**Comment by xxcriticxx** [comment]
@hawkeye116477 w usa nie moge odpalic prime vid z polskim jezykem

**Comment by hawkeye116477** [comment]
@maciejtarmas Tak konkretniej to chodzi o javascript i https://github.com/jspenguin2017/uBlockProtector

**Comment by maciejtarmas** [comment]
@hawkeye116477 

>Amazon też ma polską stronę od jakiegoś czasu: https://www.amazon.de/?language=pl_PL

Wiem, ale na razie nie ruszam. Skupiam się na polskich serwisach.

> Tak konkretniej to chodzi o javascript w https://github.com/jspenguin2017/uBlockProtector

Zobaczymy. W przyszłem tygodniu sobie to pooglądam. Niestety, córka ma priorytet 0 i z wolnym czasem różnie bywa ;]

Tymczasem, skoro zamieniliśmy już tego głupiego buga w kółko dyskusyjne, to czy macie może chody w EasyList?

Dwie kwestie:

Przede wszystkim wywalenie wyjątku w EasyPrivacy dla OLX.pl. Nie wiem dlaczego on tam w ogóle jest.

bug: https://github.com/easylist/easylist/issues/477

Drugi, to wywalanie skryptów na mobilnym interfejsie OLX z katalogu /ajax/ad/, a
 to psuje nawigację, więc potrzebny jest nowy wyjątek.

bug: https://github.com/easylist/easylist/issues/476

**Comment by xxcriticxx** [comment]
@maciejtarmas 

easylist forum link tylko easy tam z językiem bo banuja za wszystko

https://forums.lanik.us/viewforum.php?f=62

**Comment by xxcriticxx** [comment]
z smedem79 daleko dojdziesz jest dobry chłopak tylko wytłumacz wczym problem

@MajkiIT może moje słowa potwierdzić

**Comment by xxcriticxx** [comment]
@maciejtarmas moze sprawdz czy `$badfilter` pomoze

 A new filter option is available as of 1.11.3b2: badfilter, to prevent a filter from being loaded in memory.

 Using the current case as an example, one would use `https:*_ad_$badfilter` to prevent the filter `https:*_ad_` from being loaded in memory. The `badfilter` option indicates to uBO to not load in memory the functional form of a filter. For example, `https:*_ad_$badfilter` would not prevent loading into memory the filter `https:*_ad_$script`, or `https:*_ad_$domain=example.com`.

@MajkiIT / @F4z da sie ta regule z easylist jakos odwrocic?

**Comment by MajkiIT** [comment]
Co do reguł to można tak
```
||ninja.onap.io/ninja-cee.js$domain=olx.pl,important
Noi dodanie do PL @@||olx.pl/i2/ajax/ad/$xmlhttprequest
```

@xxcriticxx masz rację SMed79 , pomoże tylko musisz to umotywować.

**Comment by maciejtarmas** [comment]
@MajkiIT Dzięki :)

`||ninja.onap.io/ninja-cee.js$domain=olx.pl,important`

To jest dobre z **important**, nie znałem.

`@@||olx.pl/i2/ajax/ad/$xmlhttprequest`

To tak, oczywiste.

Wrzuciłem obydwie reguły i chyba na razie odpuszczę sobie przepychanki.

**Comment by MajkiIT** [comment]
@maciejtarmas tylko important działa tylko na uBlock. Adblock nie daje takiej możliwości.

**Comment by hawkeye116477** [comment]
@maciejtarmas To jak byś się zdecydował pomóc przy forku uBlock Protector na Firefoxa, to pisz na maila: hawkeye116477@gmail.com albo po prostu zacznij sam działać, bo ja to tylko potrafię i mogę zamienić na webextension i ewentualnie zrobić updaty przez GH i sync robić, ale sync to może lepiej, żeby jakiś bot robił, bo updaty są dość często.

**Comment by MajkiIT** [comment]
@maciejtarmas który url do filtrów jest zawsze aktualny? z twojej strony czy github ?

**Comment by maciejtarmas** [comment]
@MajkiIT 

> który url do filtrów jest zawsze aktualny? z twojej strony czy github ?

Ze strony. https://alleblock.pl/alleblock/alleblock.txt

> mportant działa tylko na uBlock. Adblock nie daje takiej możliwości.

Tak też myślałem. Generalnie obecność tego skryptu nie objawia się niczym innym, niż spowolnieniem ładowania wersji mobilnej OLX, więc nie będzie to moim dużym priorytetem. Ale dzięki wszystkim za namiary, powalczę i spróbuję się dowiedzieć, dlaczego ktoś to dodał do wyjątków, bo to jest bez sensu.

**Comment by MajkiIT** [comment]
@maciejtarmas Ok dzięki. Zaczniemy trochę promować twoje filtry. 

Co do reguł to jest lepiej, ale jak coś to mów będziemy pomagać.

**Comment by maciejtarmas** [comment]
Jeżeli ktoś ma ochotę potestować reguły dla Sprzedajemy.pl, to tu jest wersja testowa:

https://alleblock.pl/alleblock/alleblock_sprzedajemy.pl.txt

Jeśli nie będzie uwag, to w przyszłym tygodniu dorzucę do głównej listy.

Sugestie mile widziane u mnie:

https://github.com/maciejtarmas/AlleBlock/issues

**Comment by MajkiIT** [comment]
@maciejtarmas link jest martwy https://alleblock.pl/alleblock/alleblock_sprzedajemy.pl.txt

**Comment by maciejtarmas** [comment]
Dzisiaj reguły trafiły do wersji głównej, więc testową wersję usunąłem.

**Comment by MajkiIT** [comment]
:P aha ok. No to się nie wyrobiłem.
