### ISSUE TITLE
bilgorajska.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3080]
rekalama na main

**Comment by gzenio22** [comment]
bilgorajska.pl##.pod_reklamy

**Comment by hawkeye116477** [comment]
Tutaj jest nieco więcej niż tylko 1 reklama, ale Popup Blocker wyłapuje wszystko, więc nie wiem czy jest sens dawać reguły.

**Comment by hawkeye116477** [comment]
@blocker999 `bilgorajska.pl###spolecznosciowe_lewa`
