### ISSUE TITLE
nowagazeta.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3082]
reklama

**Comment by gzenio22** [comment]
nowagazeta.pl##.vc_row-has-fill.vc_custom_1481848069605.td-pb-row.wpb_row.vc_row:nth-of-type(4) Na te skaczace na srodku 

Medycyna estetyczna : nowagazeta.pl##.td-pb-span4.vc_column_container.wpb_column > .vc_column-inner > .wpb_wrapper > .wpb_content_element.wpb_text_column:nth-of-type(4)

Długie te regoly Niech ktos zerknie moze bedzie cos prostrzego

**Comment by hawkeye116477** [comment]
`nowagazeta.pl##.vc_row-has-fill`

Medycyna estetyczna:
`nowagazeta.pl##.wpb_text_column:nth-of-type(4)`

Pozostałość po reklamie:
`nowagazeta.pl##.td-ss-row.td-pb-row.wpb_row.vc_row:nth-of-type(12) > .td-pb-span4.vc_column_container.wpb_column > .vc_column-inner > .wpb_wrapper > .wpb_content_element.wpb_text_column`

Jeszcze coś jest na dole, ale to chyba można zostawić.

**Comment by MajkiIT** [comment]
A może po prostu tak?

nowagazeta.pl##.wpb_text_column.wpb_content_element

**Comment by hawkeye116477** [comment]
@MajkiIT Trochę za dużo to chowa, nawet napis rozkład jazdy i autobusów i te bezpłatne dodatki dostępne w redakcji.

**Comment by MajkiIT** [comment]
Na pewno to `nowagazeta.pl##.vc_row-has-fill` reszty szukam

**Comment by MajkiIT** [comment]
Możecie przetestować
```

nowagazeta.pl##.g-single > A > IMG[src^="http://nowagazeta.pl/wp-content/uploads/"]
nowagazeta.pl##.td-pb-row.wpb_row.vc_row:nth-of-type(1) > .td-pb-span12.vc_column_container.wpb_column > .vc_column-inner
nowagazeta.pl##.td-container-border:nth-of-type(1) > .vc_row-has-fill.vc_custom_1481848069605.td-pb-row.wpb_row.vc_row > .td-pb-span12.vc_column_container.wpb_column
nowagazeta.pl##.vc_row-has-fill.vc_custom_1481848069605.td-pb-row.wpb_row.vc_row:nth-of-type(3) > .td-pb-span12.vc_column_container.wpb_column > .vc_column-inner > .wpb_wrapper
```

**Comment by hawkeye116477** [comment]
@MajkiIT 
Ostatnia regułę można trochę skrócić: `nowagazeta.pl##.vc_row-has-fill.vc_custom_1481848069605.td-pb-row.wpb_row.vc_row:nth-of-type(3)`

A to do reszty reklam z głównej i reszty stron:
```
nowagazeta.pl##.td-ss-row.td-pb-row.wpb_row.vc_row:nth-of-type(2) > .td-pb-span8.vc_column_container.wpb_column > .vc_column-inner > .wpb_wrapper > .wpb_content_element.wpb_text_column
nowagazeta.pl##.td-ss-row.td-pb-row.wpb_row.vc_row:nth-of-type(9) > .td-pb-span4.vc_column_container.wpb_column
nowagazeta.pl##.vc_row-has-fill.vc_custom_1481848069605.td-pb-row.wpb_row.vc_row:nth-of-type(18)
nowagazeta.pl##.td-pb-row.wpb_row.vc_row:nth-of-type(17)
nowagazeta.pl##div.wpb_text_column:style(padding-top: 0px!important;)
nowagazeta.pl##.widget_text.widget:nth-of-type(5)
nowagazeta.pl##.td-ss-main-sidebar > .widget_text.widget:nth-of-type(1)
```
