### ISSUE TITLE
styl.fm

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3084]
reklama organic w polowie strony pod zdjeciami

https://styl.fm/newsy/227350.tatuaze-rekawy-galeria-wyjatkowych-motywow-dla-kobiet-ktore-podbija-twoje-serce

![screenshot from 2017-07-21 18-53-24](https://user-images.githubusercontent.com/15007183/28485346-dc0f6318-6e46-11e7-985b-269a2e73c1e6.png)

**Comment by gzenio22** [comment]
styl.fm##a[href="https://goo.gl/fRBVFL"]

Meybe?

**Comment by hawkeye116477** [comment]
@gzenio22 Nie, bo pojawi się coś innego i trzeba będzie zmienić tą regułę.
`styl.fm##.content-left.col-xs-8 > div:nth-of-type(6)`

**Comment by MajkiIT** [comment]
@gzenio22 widzę, że już coraz lepiej ci idzie.
