### ISSUE TITLE
edziecko.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3085]
macie reklame na playerze?

http://www.edziecko.pl/rodzice/7,79361,21272676,najpopularniejsze-imiona-dla-dzieci-2016-w-polsce.html

![screenshot from 2017-07-21 18-55-29](https://user-images.githubusercontent.com/15007183/28485363-ed87def4-6e46-11e7-9b87-0a034e58fe6e.png)

**Comment by gzenio22** [comment]
Tak nawet ta sama co ty XD

**Comment by F4z** [comment]
Moglibyście sprawdzić tę regułę:
`||a.uzekrs.com^`

**Comment by xxcriticxx** [comment]
@MajkiIT nope nadal mam reklame na foxie

**Comment by hawkeye116477** [comment]
@xxcriticxx Chyba będziesz musiał przejść na coś Chromowatego, np. Vivaldi, gdyż uBlock Protector wycina te reklamy.

**Comment by hawkeye116477** [comment]
Znalazłem coś takiego: https://openuserjs.org/scripts/levushka/Video_adscounter_skipper , tylko pewnie by to jakoś przerobić trzeba by było, żeby działało z tą strona.

**Comment by hawkeye116477** [comment]
Albo takie coś: https://video-adblock-for-chrome.en.softonic.com/ , jeśli to nie jakaś podpucha?

**Comment by F4z** [comment]
@xxcriticxx nie działa na Foxie, bo to połączenie jest jako `behind-the-scene`, które jest dodane do wyjątków (https://github.com/gorhill/uBlock/wiki/Behind-the-scene-network-requests).
Mógłbyś sprawdzić tę regułę:
`||static.gazeta.pl/static/video/playerjs/deploy/app/*/misc/uponit-*.min.jsgz$domain=video.gazeta.pl`

**Comment by xxcriticxx** [comment]
@F4z na jednej linijce czy dwie odzienne?

**Comment by F4z** [comment]
@xxcriticxx tylko to:
`||static.gazeta.pl/static/video/playerjs/deploy/app/*/misc/uponit-*.min.jsgz$domain=video.gazeta.pl`
po dodaniu tego nie powinno być już połączenia z `a.uzekrs.com`

**Comment by xxcriticxx** [comment]
tak dziala thx
