### ISSUE TITLE
ladnydom.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3086]
puste miesca `Materiały partnera`

http://ladnydom.pl/inspiracje/1,153170,22116617,jak-pielegnowac-storczyki-by-kwitly-jak-szalone.html?utm_source=AB09&utm_medium=cpcAB09&utm_content=LadnyDom&utm_campaign=AB&utm_type=attr#AB

**Comment by MajkiIT** [comment]
@xxcriticxx Dasz jakiś zrzut, bo nie widzę?

**Comment by xxcriticxx** [comment]
@MajkiIT teraz mam lepszy bajer 

![screenshot from 2017-07-22 07-05-34](https://user-images.githubusercontent.com/15007183/28490607-3dba3da8-6eac-11e7-9325-a3f695489277.png)

**Comment by MajkiIT** [comment]
@xxcriticxx Może najprościej
`
ladnydom.pl##.mod_adblock_prompt`

**Comment by xxcriticxx** [comment]
@MajkiIT pod msg od adblacka nic nie jest ukryte?

**Comment by xxcriticxx** [comment]
@MajkiIT jak wyloncze ubo widze 2 zendy po 3 produkty z twoja jeden zand 3 produkty

moze ktos przetestowac?

**Comment by MajkiIT** [comment]
@xxcriticxx zaraz zerkne

**Comment by F4z** [comment]
To może po prostu tak?
`||bi.ladnydom.pl/pub/ips/`
`||ladnydom.pl/aliasy/ladnydom/adblock_prompt.htm`

**Comment by xxcriticxx** [comment]
@F4z tak tez moze byc wszystkie produkty pochowane :)

**Comment by MajkiIT** [comment]
@F4z ok. Tak dodamy. Dzięki
