### ISSUE TITLE
tvswinoujscie.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3091]
@MajkiIT 
Znowu się za bardzo śpieszysz. 
https://github.com/MajkiIT/polish-ads-filter/issues/3077

Został jeszcze kanał planszowy.
`tvswinoujscie.pl##.boards.widget`

![screenshot_20170723_103526](https://user-images.githubusercontent.com/19818572/28497922-fdaa7f9c-6f92-11e7-8e60-309ebd17d5ea.png)

PS: Dlaczego @mention nie działa na Majka?

**Comment by MajkiIT** [comment]
Nie tyle nie działa, co to wynik przemęczenia. Od 2 ms nie było mnie w domu. Naginam dobę i już nie kontaktuje.

**Comment by MajkiIT** [comment]
@hawkeye116477 a tego kanału planszowego nie widziałem.

**Comment by hawkeye116477** [comment]
@MajkiIT Ok, to odpoczywaj

**Comment by MajkiIT** [comment]
@hawkeye116477 Nie o to chodzi. Już poprawiam. Siedzę na lotnisku i działam. Daje Ci +100 do zajebistości za łapanie mnie na błędach.

**Comment by xxcriticxx** [comment]
💯 +
