### ISSUE TITLE
Co sądzicie ?

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3094]
https://www.certyficate.it/adblock/new/

**Comment by hawkeye116477** [comment]
@MajkiIT Trochę jest błędów: podstawowe polskich filtry (globalne) , chyba powinno być podstawowe polskie filtry (globalne). Jeszcze brakuje paru filtrów. A tak to po za tym chyba wszystko jest ok

**Comment by MajkiIT** [comment]
@hawkeye116477 tak, tam jest więcej błędów. Bardziej mi chodzi o wizję ...

**Comment by MajkiIT** [comment]
@hawkeye116477 resztę filtrów też dodam.

**Comment by gzenio22** [comment]
wizja jest spoko z błędow widze ze zdjecia są chyba blokowane

**Comment by MajkiIT** [comment]
@gzenio22 już poprawiłem

**Comment by hawkeye116477** [comment]
@MajkiIT Wizja jest raczej ok. A te loga, to bym trochę powiększył albo wcale usunął, bo obecnie to może jak wezmę lupę, to coś zobaczę 😸 :

**Comment by xxcriticxx** [comment]
kolory i loga 

tlo inne maybe

ps wyglonda jak bym sobie wykupwal hosta na sciaganie filmow 

![screenshot from 2017-07-23 08-59-38](https://user-images.githubusercontent.com/15007183/28499500-7aa5d84c-6f85-11e7-9c2b-fdef6970aad5.png)

**Comment by adreporter** [comment]
> Co sądzicie ?
> https://www.certyficate.it/adblock/new/

Mnie się podoba.

**Comment by MajkiIT** [comment]
@hawkeye116477 
Co do  wielkości loga to wystarczy zmienić w css . Linki do zgłaszania/homepage też będą . Obecnie chcę to zrobić w responsive html . Docelowo będzie to pobierane z bazy i oparte o PHP.  

@xxcriticxx no bez kitu tak to wygląda 

@adreporter dzięki

**Comment by xxcriticxx** [comment]
@MajkiIT gdzie reszta filtrow? kad i AlleBlock

**Comment by MajkiIT** [comment]
@xxcriticxx będzie niżej, ale nie wyrobiłem się z 2 wierszem.

**Comment by xxcriticxx** [comment]
jak zaczynamy pisac wierszem to jest juz problem

**Comment by blocker999** [comment]
Super sprawa, wszystko w jednym miejscu, @MajkiIT oby tak dalej

**Comment by MajkiIT** [comment]
No już czas najwyższy aby to zrobić :)

**Comment by gzenio22** [comment]
Tak troche estetycznie ale dajmy jakies tlo zeby nie bylo tak bialo moze jasny niebieski?

**Comment by hawkeye116477** [comment]
Czegoś tu jeszcze brakuje i faktycznie może tło powinno byc w innym kolorze. Choć ja bym powiedział, że jednak może lepiej wygląda tabelka na https://filterlists.com/ , po prostu tabelka jest jakaś taka bardziej przejrzysta.

**Comment by gzenio22** [comment]
@hawkeye116477 U nas czytelniej

**Comment by hawkeye116477** [comment]
@gzenio22 Ja bym powiedział, że raczej u nich jest czytelniej, mniej chaotycznie.

**Comment by gzenio22** [comment]
Haos masz przez wiele kolorow na bialym tle jak by dac inne tlo bylo by idealnie :)

**Comment by hawkeye116477** [comment]
A mi się ta tabelka spodobała, naprawdę wg. mnie o niebo lepiej wygląda.

**Comment by gzenio22** [comment]
fakt za bardzo jebie po oczach XD daj zwykle czarne a ramki wokol nazw wielokolorowe

**Comment by hawkeye116477** [comment]
Obecnie trochę to wygląda tak jak @xxcriticxx mówi.

**Comment by MajkiIT** [comment]
@hawkeye116477 @gzenio22 te recenzenci sztuki, czekam na Wasze propozycje :)

**Comment by hawkeye116477** [comment]
@MajkiIT To moja propozycja jest taka, tabela taka jak na https://filterlists.com/, tylko, że dałbym więcej kolorów niż oni (nazwy filtrów, np. na zielono, opis na czarno, a tekst na przyciskach niebieski albo czarny, tylko ramka niebieska) i byłoby gites. Bo teraz to wygląda jak ten hosting :smile:.

**Comment by gzenio22** [comment]
zgadzam sie z @hawkeye116477

**Comment by MajkiIT** [comment]
@hawkeye116477 @gzenio22 no to czekam na HTMLa lub PHP :P

**Comment by hawkeye116477** [comment]
A nie da rady podejrzeć trochę kodu od nich :smiley ?

**Comment by MajkiIT** [comment]
@hawkeye116477 ja wiem jak się robi tabelki w HTMLu. 

Chciałem abyś przedstawił swoją wersję czyli gotowy plik html+css+JS.

**Comment by xxcriticxx** [comment]
panowie i panie please

**Comment by MajkiIT** [comment]
@xxcriticxx co tam ?

**Comment by xxcriticxx** [comment]
@MajkiIT nic myslalem ze bendzie goronco :)

**Comment by hawkeye116477** [comment]
@xxcriticxx Gorąco z wrażeń :smiley:

**Comment by hawkeye116477** [comment]
@MajkiIT Ewentualnie zostaw swoją wizję, tylko daj szare tło (#6e797e) i niebieskie obramowania ramek (#478199 albo #1f97c9) i na te linki daj może trochę ciemniejszy kolor.

**Comment by MajkiIT** [comment]
@xxcriticxx Nie coś ty :P Spoko luz
@hawkeye116477 ok. Coś podziałam.

**Comment by xxcriticxx** [comment]
@MajkiIT sa nato tabletki

**Comment by MajkiIT** [comment]
@xxcriticxx Viagra? :)

**Comment by hawkeye116477** [comment]
Jeszcze wypełnienie ramki w środku można dać może na jakiś jasnoniebieski kolor (np. #6fecff) i czarne napisy może zmień na biały kolor, jeśli tło ma być szare.

A tak BTW to co to za offtop robicie  ....

**Comment by xxcriticxx** [comment]
@MajkiIT tak blue pill tak jak w matrix
