### ISSUE TITLE
superkinomaniak.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3095]
pod search podlaczone sa glupoty regexem please

**Comment by MajkiIT** [comment]
Kod wrzucony w kod strony, więc można tak: `||superkinomaniak.pl^$popup`

**Comment by xxcriticxx** [comment]
dziala 

tutaj tez trzeba sie logowac

**Comment by F4z** [comment]
A jakbyśmy zablokowali ten skrypt?
`||superkinomaniak.pl/js/show-promote.min.js`

**Comment by MajkiIT** [comment]
wydaje się ok. Szacunek
