### ISSUE TITLE
czy ublock blokuje fb

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#3100]
od czasu do czasu, blokuje mi sie fb, nie mozna przewijac strony za pomoca strzalek ani zamkniac rozmowy za pomoca esc.

mam ublock i opera 46, win 10 64bit

**Comment by hawkeye116477** [comment]
@lukjan32 A jakich filtrów używasz?

**Comment by lukjan32** [comment]
tylko z ublock i nowsze

**Comment by hawkeye116477** [comment]
Czyli jakich? Wypisz konkretnie, co masz (np. mam EasyList i Fanboy+Easylist-Merged Ultimate List).

**Comment by lukjan32** [comment]
![1](https://user-images.githubusercontent.com/17565773/28521552-7c95f4c6-7074-11e7-98c0-f416fd3a1cd3.jpg)
![2](https://user-images.githubusercontent.com/17565773/28521553-7c98a7a2-7074-11e7-983a-a4c56ff39cb1.jpg)

**Comment by hawkeye116477** [comment]
@lukjan32 Ok, po pierwsze to wyłącz Anti Adblock Killer, jego używanie obecnie nie jest raczej bezpieczne, gdyż ktoś przejął domenę Reeka, on nie ma nad nią kontroli raczej i być może nawet 0-daya da się złapać. Po drugie, masz Operę, więc tam uBlock Protector nie działa, wiem można zainstalować uBlock Protector Extension przez Download Chrome Extension, ale niestety nie działa on tak jak trzeba, bo brakuje pewnych API. Także wyłącz uBlock Protector i zainstaluj AAK Cont, wg. instrukcji: https://gitlab.com/xuhaiyang1234/AAK-Cont#anti-adblock-killer-continued .
A co do Facebooka, to z niego raczej nie korzystam, więc nie pomogę, ale pewnie reszta ekipy coś wymyśli.

**Comment by lukjan32** [comment]
aha, dobra, wyłączyłem.

**Comment by hawkeye116477** [comment]
@MajkiIT Możesz zerknąć?

**Comment by MajkiIT** [comment]
Testowałem na 2 kompach i na obu jest ok. Poszukam jeszcze na innych.

**Comment by lukjan32** [comment]
to sie po kilkuniastu minut

**Comment by hawkeye116477** [comment]
@lukjan32 Czyli dalej się to dzieje, nawet po wyłączeniu Anti Adblock Killer (filtru i skryptu)?

**Comment by lukjan32** [comment]
musialbym sprawdzic przez kilka dni

**Comment by xxcriticxx** [comment]
@lukjan32 skasuj browsing historie i cookies

**Comment by hawkeye116477** [comment]
@lukjan32 Zamień Windows 10 na 7 lub 8.1, bo 10 to wieczne kłopoty, ciągła beta, a przynajmniej tak było, jak go kiedyś używałem :smiley:
http://nonsensopedia.wikia.com/wiki/Windows_10

**Comment by lukjan32** [comment]
@xxcriticxx mogę tylko cookies od fb?

**Comment by hawkeye116477** [comment]
@lukjan32 Ciasteczka, pamięć podręczna i dane witryb trybu offline - tyle powinno wystarczyć.

**Comment by lukjan32** [comment]
dobra, oby coś dało

**Comment by lukjan32** [comment]
dalej sie zawiesza

**Comment by hawkeye116477** [comment]
@lukjan32 Kiedy się dokładnie zawiesza, po jakim czasie? Czy dzieje się to jak oglądasz filmik?
Bo z tego co widzę, to trochę osób ma z tym problem: http://forums.opera.com/discussion/1883860/tab-freeze-on-facebook-com/p1

**Comment by lukjan32** [comment]
u mnie sie dzieje nagle, po kilkuniastu minutach.

**Comment by hawkeye116477** [comment]
@lukjan32 Ktoś na forum ChrOpery też pisał, że to dzieje się w losowych sytuacjach, nagle. Więc bardzo możliwe, że to wina ChrOpery.
A spróbuj zainstalować Vivaldi i sprawdź czy tam też ten problem występuje.
https://vivaldi.com/download/

**Comment by hawkeye116477** [comment]
@lukjan32 Ktoś na forum ChrOpery też pisał, że to dzieje się w losowych sytuacjach, nagle. Więc bardzo możliwe, że to wina ChrOpery.
A spróbuj zainstalować Vivaldi, doinstalować uBlocka i sprawdź czy tam też ten problem występuje.
https://vivaldi.com/download/

**Comment by hawkeye116477** [comment]
http://forums.opera.com/discussion/1884835/out-of-memory-especialy-on-facebook/p1
