### ISSUE TITLE
www.dvbtmap.eu

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#3101]
na stronie www.dvbtmap.eu, jest komunikat

**Comment by gzenio22** [comment]
musze sie jakos nauczyc tej konsoli z zablokuj element w operze bo nie ogarniam tam nawet jak je blokowac

**Comment by hawkeye116477** [comment]
@lukjan32 @gzenio22  Obawiam się, że tego nie da się zablokować uBlockiem, trzeba to zgłosić do uBlock Protector Extension lub AAK Cont, a najlepiej to do obu, bo Opera nie obsługuje poprawnie Protectora, a na Protectorze i AAK Cont jest ten sam problem.

**Comment by F4z** [comment]
Moglibyście sprawdzić?
`||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$important,script,redirect=noopjs,domain=dvbtmap.eu`

**Comment by hawkeye116477** [comment]
@F4z Działa. Przy okazji znalazłem puste miejsce po reklamie w helpie.

**Comment by lukjan32** [comment]
dziala

**Comment by hawkeye116477** [comment]
```
dvbtmap.eu##.advertcontent2.left
dvbtmap.eu##.advertcontent
```

**Comment by hawkeye116477** [comment]
@MajkiIT Możesz zerknąć?

**Comment by MajkiIT** [comment]
@xxcriticxx reguła podana przez @F4z jest ok. Dodatkowo do zablokowania pozostałości reguła `dvbtmap.eu##[class*="advertcontent"]`

**Comment by xxcriticxx** [comment]
@MajkiIT nie mam nic wspolnego stym tematem 👍

**Comment by MajkiIT** [comment]
@xxcriticxx sorry

**Comment by xxcriticxx** [comment]
@hawkeye116477 ladnie rysujesz

**Comment by hawkeye116477** [comment]
@xxcriticxx Jasne, jestem mistrzem Gimpa 😺

**Comment by F4z** [comment]
Powinno podnieść do góry mapę i ten element po lewej:
`dvbtmap.eu###leftCol:style(top: 51px!important)`
`dvbtmap.eu###content-container:style(margin-top: 0px!important;)`

**Comment by xxcriticxx** [comment]
@hawkeye116477 `sudo apt-get install shutter`

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie mam apt, mam Pacmana :smile:
<img src="https://linuxsuperuser.com/wp-content/uploads/2015/11/arch-linux-pacman.png"/>

**Comment by xxcriticxx** [comment]
archa i miety nie uzywam zamontuj sobie shutter jak to kolwiek sie montuje u ciebie na linuxie

**Comment by hawkeye116477** [comment]
@xxcriticxx Tak właściwie to ja mam Manjaro Linux, nie jestem jeszcze taki zaawansowany, by korzystać z Archa.

**Comment by hawkeye116477** [comment]
@F4z Działa jak natura chciała :smile:

**Comment by MajkiIT** [comment]
@F4z to zadziała z Adguard ?
```
dvbtmap.eu###leftCol:style(top: 51px!important)
dvbtmap.eu###content-container:style(margin-top: 0px!important;)
```

**Comment by F4z** [comment]
@MajkiIT tak, zadziała.
Chociaż generalnie reguły "CSS" w przypadku Adguarda wyglądają w ten sposób:
`dvbtmap.eu#$##leftCol { top: 51px!important; }`
`dvbtmap.eu#$##content-container { margin-top: 0px!important; }`

**Comment by lukjan32** [comment]
dzieki, dziala
