### ISSUE TITLE
wnet.fm

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3102]
http://wnet.fm/

Boxy po reklamach i z zawartością: 
![image-20170724-007](https://user-images.githubusercontent.com/9846948/28532801-2a8c3876-709b-11e7-85e5-53293b5c23d4.png)

![image-20170724-008](https://user-images.githubusercontent.com/9846948/28532814-3d54d6f2-709b-11e7-8020-102418cd9626.png)

![image-20170724-009](https://user-images.githubusercontent.com/9846948/28532857-5f1e3daa-709b-11e7-9357-c09d4b8d1b4f.png)

**Comment by MajkiIT** [comment]
`wnet.fm##.prom-block
`
