### ISSUE TITLE
krs-pobierz.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3104]
reklama przeswietl.pl

http://krs-pobierz.pl/dobro-my-i5889108

**Comment by gzenio22** [comment]
krs-pobierz.pl##img[src="/landing_pages/banner_landing_4.jpg"]   Gora
krs-pobierz.pl##img[src="/katalog/baners/Przeswietl-new-457_300-v2.jpg"]   z boku

Sprawdzcie

**Comment by MajkiIT** [comment]
Może coś takiego?
`krs-pobierz.pl##[target="_blank"] > IMG[width="750px"][height="200px"]`
