### ISSUE TITLE
glamrap.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3105]
reklama urbancity

http://glamrap.pl/1/43036-planet-anm-flashback-liner-notes-do-wszystkich-utworow

**Comment by gzenio22** [comment]
##img[src="/images/rk6/art_szorty_678768.jpg"]

**Comment by MajkiIT** [comment]
`glamrap.pl##[onclick*="Reklama"][target="_blank"] > IMG:`

**Comment by gzenio22** [comment]
@MajkiIT Kurde cos czego ja nie widze a ty potrafisz to pewnie rozpisac recznie Xd

**Comment by MajkiIT** [comment]
@gzenio22 no wiesz 3 lata patrzenie na to, powoduje swoje :)
