### ISSUE TITLE
pogoda.onet.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3106]
onet chce sie o nas dowiedziec czegos wiecej lol @MajkiIT
![screenshot_1](https://user-images.githubusercontent.com/21177361/28546856-707a1f48-70cc-11e7-8f09-911cff107228.png)

Blokujemy to filtrami czy jest moze jakas opcja w przegladarkach na pushe o lokalizacje?

**Comment by xxcriticxx** [comment]
@gzenio22 lokalizacja jest ok

**Comment by hawkeye116477** [comment]
@gzenio22 Onetowi twoja lokalizacja potrzebna jest do pogody, musi wiedzieć gdzie chcesz zobaczyć czy jest słońce czy deszcz 😄 .
