### ISSUE TITLE
repostuj.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3107]
http://www.repostuj.pl
![image-20170725-003](https://user-images.githubusercontent.com/9846948/28570885-756a2aa6-7140-11e7-9c3f-5b605fdbfe9e.png)

**Comment by MajkiIT** [comment]
`||www.repostuj.pl/static/repostujpl/js/js.cookie.js$script,domain=www.repostuj.pl`
