### ISSUE TITLE
polygamia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3110]
dziura po tapecie nintendo 2ds xl

http://polygamia.pl/gra-narobila-mi-mnostwo-smrodu-i-gowna-sapkowski-obraza-chmielarza-graczy-i-fanow/

**Comment by hawkeye116477** [comment]
Resztki po widgetcie FB: `polygamia.pl##.fbpost-iframe`

**Comment by xxcriticxx** [comment]
@hawkeye116477 nato trzeba trafic dzisaj jest inna tapeta i niema dziury

**Comment by hawkeye116477** [comment]
`pl###text-6` - chowa newsletter
