### ISSUE TITLE
Strona z filtrami

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3115]
@MajkiIT 
![screenshot_20170728_111820](https://user-images.githubusercontent.com/19818572/28711137-db32affa-7386-11e7-8849-a2d6dbd300bd.png)

Jest parę błędów na stronie z filtrami. Homepage przy AlleBlock też chyba powinien być inny i raczej powinno pisać Filtry do Allegro, Ceneo i OLX.

**Comment by hawkeye116477** [comment]
Nadal widzę małe błędy, w 2 miejscach powinno być chyba z wielkiej, a nie z małej litery.

**Comment by maciejtarmas** [comment]
Moim skromnym zdaniem trzeba by napisać dłuższe opisy każdej z list.

Jak wrócę w poniedziałek z drobnych weekendowych wakacji, to podejmuję się coś wyprodukować.

**Comment by hawkeye116477** [comment]
Ja to bym zmienił też tło i linki może powinny być trochę ciemniejsze, albo to tak po prostu nie za dobrze wygląda na tym tle.

**Comment by MajkiIT** [comment]
Ta wersja to taka proteza. Obecnie widzę, że pomysł był chybiony i szukam alternatyw bazujących na liście w postaci tabeli.

**Comment by hawkeye116477** [comment]
@MajkiIT Może coś w tym stylu: https://hawkeye116477.github.io/test/ ?
![screenshot_20170730_003628](https://user-images.githubusercontent.com/19818572/28749172-296eedb2-74bf-11e7-86b8-9942c707bc0a.png)

**Comment by hawkeye116477** [comment]
@MajkiIT Może coś w tym stylu: https://hawkeye116477.github.io/test/ ?
![screenshot_20170730_144736](https://user-images.githubusercontent.com/19818572/28753557-1ac08af6-7536-11e7-9aba-455fb2120693.png)

**Comment by xxcriticxx** [comment]
Tak jak bylo kiedys na parasolkach bylo zajebiscie

**Comment by hawkeye116477** [comment]
Tło zawsze można zmienić, bardziej chodzi mi o inne rzeczy.

**Comment by xxcriticxx** [comment]
ja bym rozbudowal github README.md na main page I tam dodal wszystkie linky

**Comment by hawkeye116477** [comment]
@gzenio22 A tobie jak się podoba?

**Comment by hawkeye116477** [comment]
@xxcriticxx Czyli EasyList, EasyPrivacy i resztę mam dodać, tzn. wszystko z filterlists.com? To trochę sporo dodawania 😛 .

**Comment by MajkiIT** [comment]
@hawkeye116477 twój template nie jest responsywny.
@xxcriticxx to nie głupi pomysł.

**Comment by hawkeye116477** [comment]
@MajkiIT To jest zadanie dla profesjonalisty, gdyż nie wiem jak zrobić z tego responsywny. Ja to tylko w LO Writer zrobiłem i przekonwerterowałem za pomocą http://wordtohtml.net/ 😄

**Comment by hawkeye116477** [comment]
@MajkiIT 
[tttt(1).zip](https://github.com/MajkiIT/polish-ads-filter/files/1185785/tttt.1.zip)
Takie coś się nada?

**Comment by hawkeye116477** [comment]
@MajkiIT To jest zadanie dla profesjonalisty. Ja takich rzeczy raczej nie potrafię.
[filtry_LO.zip](https://github.com/MajkiIT/polish-ads-filter/files/1185836/filtry_LO.zip)

**Comment by MajkiIT** [comment]
@hawkeye116477 teraz to przykozaczyłeś... sam robiłeś?

**Comment by hawkeye116477** [comment]
@MajkiIT Ale co sam robiłem? Strona jest nadal taka jak była.

**Comment by xxcriticxx** [comment]
@MajkiIT ja tylko mam zajebiste pomysly

**Comment by gzenio22** [comment]
@hawkeye116477 nie ma zle tlo tylko na jasne dac :) i gitara

**Comment by hawkeye116477** [comment]
@gzenio22 Ja tam wolę ciemne tło, w Linuxie też mam ciemny motyw. Jasne, czyli jakie, białe? 
https://cloudspace.idrsolutions.com:8181/HTML_Page_Extraction/output/d827a688-92f4-44e6-9949-92a237e1122b/filtry/index.html?page=1

**Comment by gzenio22** [comment]
@hawkeye116477 Bomba :) Podoba mi sie

**Comment by hawkeye116477** [comment]
@gzenio22 Jak dla mnie to trochę za biało, ale na szczęście można przełączyć na ciemny motyw. Tylko linki od subskrypcji nie działają, skopiowałem linki od subskrypcji i dałem to normalnie jako odnośnik, nie wiem czy coś trzeba więcej zrobić. Wyszukiwarkę też trzeba pewnie poprawić, bo poucinało niektóre rzeczy.

**Comment by MajkiIT** [comment]
@hawkeye116477 generator :( fuja ble ...
Nie ma jak widać strony która by pasowała każdemu

**Comment by xxcriticxx** [comment]
readme black & white text simple

**Comment by hawkeye116477** [comment]
@xxcriticxx Simple text, tzn? 
@MajkiIT Nie lubisz generatorów, ok, to przerób to na responsywny html po swojemu, mistrzu. Tło może być i białe, choć wolę czarne, ale białe też nie jest złe.
[filtry_LibreOffice.zip](https://github.com/MajkiIT/polish-ads-filter/files/1187024/filtry_LibreOffice.zip)

**Comment by MajkiIT** [comment]
@hawkeye116477 nie lubię generatorów, go narzucają za dużo zbędnego kodu. Co ja Ci poradzę, że jeden chce tak, drugi inaczej. Ja zrobiłem swoją wersję i tyle. Chcesz abym obrobił twoją wersję to ogarnę tylko, że zaraz następnemu coś innego nie będzie pasowało. Dla mnie ma być to lekkie i przejrzyste.

**Comment by hawkeye116477** [comment]
@MajkiIT To może zrobimy głosowanie i najlepszy wygra?

**Comment by xxcriticxx** [comment]
@hawkeye116477 jak mam pokazac jak nie mam access do readme.md

**Comment by hawkeye116477** [comment]
@xxcriticxx Sklonuj repo i będziesz miał.

**Comment by xxcriticxx** [comment]
zostawie to dla was klonowac nic nie bende

**Comment by hawkeye116477** [comment]
Ewentualnie wersja czarno-biała ![screenshot_20170731_120435](https://user-images.githubusercontent.com/19818572/28773082-764ece66-75e8-11e7-83d1-917956a2c1e9.png)

**Comment by hawkeye116477** [comment]
@xxcriticxx Wejdź tu --> https://github.com/MajkiIT/polish-ads-filter/blob/master/README.md i tam masz ołówek taki, naciskasz i możesz edytować.

**Comment by xxcriticxx** [comment]
super :+1:

**Comment by xxcriticxx** [comment]
@hawkeye116477 dodaj do readme zobaczymy jak bendzie wyglondac

**Comment by MajkiIT** [comment]
@hawkeye116477 zrobiłem, ale nie uważam, że chybiony. Po prostu ile osób tyle wersji. Chcesz konkursu to podaj warunki.

**Comment by hawkeye116477** [comment]
@MajkiIT Przecież pisałeś: 

> Ta wersja to taka proteza. Obecnie widzę, że pomysł był chybiony i szukam alternatyw bazujących na liście w postaci tabeli.

**Comment by MajkiIT** [comment]
Był chybiony, bo każdy ma inną wersję co do tej strony/listy. Siądę napisze to w PHP i będzie tyle z tego. Dorobię color maker aby każdy mógł będzie zmienić sobie kolor tła, linków itp.

**Comment by hawkeye116477** [comment]
@xxcriticxx Gotowe: https://hawkeye116477.github.io/test/

**Comment by hawkeye116477** [comment]
@MajkiIT Czyli będzie tabela z możliwością zmieniania kolorów. To git.

**Comment by hawkeye116477** [comment]
@MajkiIT Możesz poprawić link do subskrybcji filtra ciasteczkowego? Bo na Androidzie z Yandexem i uBlockiem nie mogę zasubskrybować.
`abp:subscribe?location=abp:subscribe?location=https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt&title=Polish_Cookies`
Chyba za jedne abp:subscribe by wystarczyło.

**Comment by MajkiIT** [comment]
@xxcriticxx poprawione . Dzięki
