### ISSUE TITLE
fotka.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3118]
push

https://fotka.com/forum/muzyka/238480,Czy_uwazacie_ze_Pols/2

![capture](https://user-images.githubusercontent.com/15007183/28736511-18feaede-73b8-11e7-9a3a-75510c19832c.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Don't Allow twoim przyjacielem, naciskasz raz i problem z głowy :smiley: .

Powinno pomóc: `||www.gstatic.com/firebasejs/4.1.2/firebase.js$script,domain=fotka.com`, ale nie gwarantuję, że nie rozwali przy okazji czegoś innego przydatnego.
