### ISSUE TITLE
dom.elka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3119]
reklama 

![capture](https://user-images.githubusercontent.com/15007183/28736638-d392a20a-73b8-11e7-87c5-ccf85c7ca74a.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Na górze: `dom.elka.pl###wrapperPrawa`

A z tym na dole to nwm co zrobić.
