### ISSUE TITLE
polski-tenis.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3121]
![capture](https://user-images.githubusercontent.com/15007183/28737004-953daf5c-73ba-11e7-8834-54709c3b9a4f.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx 
`polski-tenis.pl##.hidden-xs.col-lg-5.col-md-5.col-sm-12.col-xs-12`
