### ISSUE TITLE
pingpong.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3123]
cookies

Strona wykorzystuje cookies i technologie pochodne w ramach świadczonych usług, statystyk oraz reklam. Korzystanie z witryny bez zmiany ustawień oznacza wyrażenie zgody na umieszczanie ich na Twoim urządzeniu. Więcej informacji.

**Comment by hawkeye116477** [comment]
`pingpong.com.pl##body > div:nth-of-type(6)`
