### ISSUE TITLE
premierywtv.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3124]
@blocker999 Znowu jest drobny problemy z socialowymi filtrami. Otóż pewna reguła blokuje wyświetlanie obrazów na stronie -`pl##.alignleft` .

Przykładowy link: http://premierywtv.pl/canal-premiery-filmowe-5-11-sierpnia-2017

**Comment by blocker999** [comment]
@hawkeye116477 Poprawione, zaktualizuj filtry.
