### ISSUE TITLE
zuzelend.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3128]
![capture](https://user-images.githubusercontent.com/15007183/28746212-bfdd0334-7455-11e7-98ff-cefb8db0c30f.PNG)

**Comment by hawkeye116477** [comment]
@blocker999 Z prawej Facebook `zuzelend.com##.facebook_box`

**Comment by hawkeye116477** [comment]
A z tym bannerem to nie wiem co zrobić, gdyż jeśli go schowamy to logo strony też się schowa, no chyba, że nikt się nie obrazi jak logo schowamy :smile: .

**Comment by blocker999** [comment]
@hawkeye116477 w tym wypadku, Fanboy's Social Blocking List to blokuje

**Comment by hawkeye116477** [comment]
@blocker999 Ok

**Comment by hawkeye116477** [comment]
Login with Facebook: `zuzelend.com###login_facebook`
