### ISSUE TITLE
kuszotv.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3129]
prawa strona 

![capture](https://user-images.githubusercontent.com/15007183/28746264-cac1ed04-7456-11e7-8e0b-8c803693efd4.PNG)

**Comment by hawkeye116477** [comment]
```
www.kuszotv.pl###right > div:nth-of-type(1)
www.kuszotv.pl###right > center
```

A to na te puste okienko:
```
www.kuszotv.pl###pa
www.kuszotv.pl###pab
```

Za NC+/CP nie płaci, tylko przez neta ogląda, nie ładnie 😛
