### ISSUE TITLE
www.stawiamnapiwo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#313]
cookies 

Niniejsza strona internetowa korzysta z plików cookies, które mogą być zapisywane na twardym dysku Twojego komputera. Wpisując swoją datę urodzenia wyrażasz zgodę na wykorzystywanie jej przez pliki cookies. Więcej informacji na temat plików cookies znajdziesz tutaj

**Comment by MajkiIT** [comment]
element statyczny
