### ISSUE TITLE
router

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3133]
@MajkiIT twoj router wytrzyma liste 2.5 mil hostow?

**Comment by gzenio22** [comment]
eeee ile? :D

**Comment by xxcriticxx** [comment]
2.5 duzo zer na koncu

**Comment by gzenio22** [comment]
dobra wtryniam sie w cos czego nie znam nie wiem o czym mowa co zrobicie z tymi hostami?

**Comment by xxcriticxx** [comment]
magic ma magiczny router i je tam laduje

**Comment by MajkiIT** [comment]
@xxcriticxx tak spokojnie. Jedynie może mieć lekki problem przy imporcie takiej ilości, ale pewnie tylko przez 10 s max.

**Comment by hawkeye116477** [comment]
@gzenio22 https://expressit.pl/porady-komputerowe/plik-hosts-jak-zablokowac-strony/

**Comment by xxcriticxx** [comment]
@MajkiIT zrobisz test i daj znac 

https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist

**Comment by gzenio22** [comment]
@hawkeye116477 u mnie to nie pykło :(

**Comment by hawkeye116477** [comment]
@gzenio22 Trzeba to dopisać do C:\Windows\System32\drivers\etc\hosts na końcu, zrobić nową linię i tam wkleić, a potem tylko 2 część stąd --> http://szymkiewicz.pl/rozmaitosci/jak-zablokowac-i-usunac-reklamy-w-skypeie/ . No chyba, że masz ten nowy systemowy Skype, który jest w Windows 10, to wtedy może to nie zadziałać.

**Comment by gzenio22** [comment]
jednak sobie odpuszcze wytnie to tez ekran startowy a adguard jak to wycina?

**Comment by hawkeye116477** [comment]
@gzenio22 Serio, on ci jest potrzebny? Jak dla mnie jest zbędny. Jest jeszcze coś takiego: https://toolslib.net/downloads/viewdownload/175-skype-adblocker/  . A Adguard jest tylko 14 dni za free, potem trzeba bulić.

**Comment by MajkiIT** [comment]
@xxcriticxx w nocy wrzucę i dam rano znać.

**Comment by xxcriticxx** [comment]
ok

**Comment by hawkeye116477** [comment]
@gzenio22 Ewentualnie: https://gist.github.com/joielechong/d0042338fd3132013aec4ee56045e558

**Comment by MajkiIT** [comment]
@xxcriticxx dodane i działa.

**Comment by MajkiIT** [comment]
@xxcriticxx coś mam więcej robić?

**Comment by xxcriticxx** [comment]
@MajkiIT poskacz po swoich stalych stronach zobacz czy zaduzo nie blokuje i daj znac

**Comment by xxcriticxx** [comment]
@MajkiIT zablokowalo jakies ulubione strony?

**Comment by MajkiIT** [comment]
Nie siadłem w pełni do tego. Dzisiaj do tego siądę na kilka h.

**Comment by MajkiIT** [comment]
@xxcriticxx blokuje zawirusowane strony. Podczas moich testów żadna strona nie została przyblokowana. Korci mnie wrzucić te domeny ludziom np. 700 osób do testu :P .

**Comment by xxcriticxx** [comment]
@MajkiIT nie za bardzo rozumiem

**Comment by MajkiIT** [comment]
@xxcriticxx ta lista którą prosiłeś abym spojrzał blokuje zawirusowane strony. Testowałem to przez 2 dni i nie miałem problemów przez tą listę. Dodatkowo wrzuciłem ją ludziom w pracy a w tym oddziale pracuje ok 700 osób i zobaczymy czy ktoś nie będzie się skarżył.

**Comment by xxcriticxx** [comment]
@MajkiIT blokuje fb i twitter napewno bendziesz mial fanow

**Comment by MajkiIT** [comment]
@xxcriticxx blokuje, ale nie w pełni. Najwyżej będę usuwał wybrane wpisy.

**Comment by xxcriticxx** [comment]
@MajkiIT podaje dla autora co znajde dont worry

**Comment by MajkiIT** [comment]
@xxcriticxx dzięki

**Comment by xxcriticxx** [comment]
@MajkiIT bendzie dzieki jak to bendzie dzialas teraz to dalej testy

**Comment by xxcriticxx** [comment]
@MajkiIT bendzie dzieki jak to bendzie dzialas teraz to dalej testy

**Comment by xxcriticxx** [comment]
@MajkiIT jak test?

**Comment by MajkiIT** [comment]
@xxcriticxx wydaje się ok, nikt nie narzekał. Chcę to rozszerzyć o kolejne listy jak np. ta od YT.

**Comment by xxcriticxx** [comment]
ja z lista do yt nie mialem najlepszych rezultatow

**Comment by MajkiIT** [comment]
Mówisz o tym?
https://github.com/anudeepND/youtubeadsblacklist

**Comment by xxcriticxx** [comment]
tej listy nigdy chyba nie zalatowalem

**Comment by xxcriticxx** [comment]
@MajkiIT cos takiego posiadasz?

https://www.amazon.com/Mikrotik-Routerboard-RB2011UiAS-2HnD-Port-Ethernet/dp/B00BGIXOHQ

**Comment by MajkiIT** [comment]
@xxcriticxx Mam coś innego 
1. https://www.cyberbajt.pl/produkt/9137/mikrotik-cloud-core-router-ccr10097g1cpc.html
+
2. https://www.mikrotik.org.pl/?produkt,4648

**Comment by xxcriticxx** [comment]
firmware orginaly czy cos innego?

**Comment by MajkiIT** [comment]
Oryginalny

**Comment by xxcriticxx** [comment]
@MajkiIT lista host została poprawiona ma teraz 1.5 mil host było za dużo duplikatów 

@hawkeye116477 masz czas przetestować na win10?

**Comment by MajkiIT** [comment]
@xxcriticxx Ok dzięki

**Comment by hawkeye116477** [comment]
@xxcriticxx Co przetestować? A tak w ogóle to ja nie mam Windows 10. Miałem, ale wróciłem do 7, bo 10 powodował tylko problemy, ale i tak raczej rzadko zaglądam na Windę, częściej Manjaro Linux :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 then plik host jet teraz ver na windows

**Comment by hawkeye116477** [comment]
@xxcriticxx A po jakiemu ty teraz piszesz? Brzmi jak tłumaczenie z Google Translate. Sorry, ale nie kumam o co biega :smiley:.

**Comment by hawkeye116477** [comment]
@xxcriticxx Sorry, ale nie rozumiem języka wujka translatora :smiley:.
