### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3134]
![screenshot_20170731_185059](https://user-images.githubusercontent.com/19818572/28789207-b1689018-7624-11e7-9c6e-4e188f903b32.png)

@MajkiIT @F4z Dacie radę coś z tym zrobić czy raczej mam odwołać się do specjalisty?

**Comment by xxcriticxx** [comment]
u specialisty to jusz bylo https://github.com/jspenguin2017/uBlockProtector/issues/416

**Comment by hawkeye116477** [comment]
@xxcriticxx No i coś nie działa nadal.
@blocker999 Do PopupBlockera do dodania, bo blokuje playera: `pilot.wp.pl#@##Player0`.

**Comment by hawkeye116477** [comment]
Znalazłem rozwiązanie: `@@||adv.wp.pl^$xmlhttprequest,domain=pilot.wp.pl`

**Comment by HateAds** [comment]
@hawkeye116477 @xxcriticxx Działało wcześniej. Po prostu na wp często coś zmieniają i takie akcje są.

**Comment by hawkeye116477** [comment]
@HateAds Ok. W sumie można byłoby to zgłosić, ale reklam zadaje się nie ma pod odblokowaniu tej reguły, więc chyba nie trzeba zawracać gitary specjaliście :smile: .

**Comment by xxcriticxx** [comment]
@hawkeye116477 on chyba za bardzo za instrumentami nie przepada
