### ISSUE TITLE
wyborcza.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3135]
![capture](https://user-images.githubusercontent.com/15007183/28794584-c5ee527c-7604-11e7-8912-75c34dfab2c8.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Ich własna reklama artykułów, więc może to zostawimy. Daj zarobić gazecie :smiley: .
wyborcza.pl##.day-images.mod-day-images
