### ISSUE TITLE
stroer.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3136]
Strona używa cookies
×
Ta strona używa cookies. Korzystając ze strony wyrażasz zgodę na ich używanie, zgodnie z bieżącymi ustawieniami przeglądarki. Aby uzyskać więcej informacji na temat celu używania cookies i możliwości zmiany ustawień dot. cookies przejdź do Polityka prywatności.

**Comment by hawkeye116477** [comment]
@xxcriticxx Nic tam takiego nie widzę.

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/28799633-5fded98a-7617-11e7-9a8b-68925e58291e.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Popup Blocker to wycina, ale i wycina coś za dużo, nawet ten tekst przy slajdach. Może warto dopisać przy Popup Blocker, że to alpha/beta.
`stroer.pl##.top`

**Comment by xxcriticxx** [comment]
@hawkeye116477 moze bys zrobil poprawki i puscil pull requesta?

**Comment by hawkeye116477** [comment]
@xxcriticxx Już zgłosiłem: https://github.com/azet12/PopupBlocker/issues/41
