### ISSUE TITLE
ookla.com

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3138]
@MajkiIT 
![screenshot_20170801_180243](https://user-images.githubusercontent.com/19818572/28834837-c3a6fe1c-76e3-11e7-95a5-8070eb1d77f0.png)
`||consent.truste.com/get?name=notice.js$script`

Aktualizacja: Jest to już w ciasteczkowym potworze Fanboya, więc blokujemy to czy zostawiamy?

**Comment by MajkiIT** [comment]
zablokujemy

**Comment by hawkeye116477** [comment]
@MajkiIT Jest to już w najnowszym commitcie, tylko coś zdaje się, że nie dopisałem tego do message :smiley: .
