### ISSUE TITLE
lastfm.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3142]
@blocker999 cos dla ciebie 

from easylist forum

`lastfm.pl#@#.social-sharing`

**Comment by blocker999** [comment]
@xxcriticxx Ok, dodam

**Comment by hawkeye116477** [comment]
@blocker999 @xxcriticxx Fanboye już to dodali.
A to na obserwuj nas:
`last.fm##.footer-top-col:nth-of-type(5)`
