### ISSUE TITLE
mzdik.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3143]
Strona wykorzystuje pliki cookies. Szczegóły w polityce prywatności.

**Comment by hawkeye116477** [comment]
`mzdik.pl###webDataTime > span`

**Comment by hawkeye116477** [comment]
@MajkiIT Majkel kiedy update naszego ciasteczkowego potwora, bo już zdaje się trochę się tego nazbierało?
