### ISSUE TITLE
hurtidetal.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3144]
reklama expressowo

**Comment by gzenio22** [comment]
hurtidetal.pl##.clearfix.row > .col-xs-12 > .a.ads

Sprawdz bo ja mam jeszcze osla zamiast internetu Xd

**Comment by hawkeye116477** [comment]
@gzenio22 Można krócej: `hurtidetal.pl##.clearfix.row`

**Comment by hawkeye116477** [comment]
Można krócej: `hurtidetal.pl##.ads`

**Comment by xxcriticxx** [comment]
@gzenio22 testowales kiedys lynx browser na linux

https://en.wikipedia.org/wiki/Lynx_(web_browser)

**Comment by hawkeye116477** [comment]
A to @gzenio22 ma Linuksa? A ta przeglądarka wygląda jak z 19 wieku :smiley:

**Comment by hawkeye116477** [comment]
A to @gzenio22 ma Linuksa? Nie sądzę, by chciał skorzystać z 20-wiecznej przeglądarki. To już chyba lepiej skorzystać z Turbo w ChrOperze.

**Comment by xxcriticxx** [comment]
@hawkeye116477 gzenio22 ma limit na necje

**Comment by hawkeye116477** [comment]
@xxcriticxx Jest zawsze jeszcze 1 opcja: https://aero2.pl/1_bezplatny-internet/1_jak-to-dziala .

**Comment by xxcriticxx** [comment]
to juz ty sobie pogadaj z @gzenio22

**Comment by gzenio22** [comment]
@hawkeye116477 wytrzymam jeszcze do tego grodnia i biere cos innego

**Comment by hawkeye116477** [comment]
@gzenio22 Szybciej ci wyślą kartę, a tylko raz płacisz i potem masz za friko, ale 512 kb/s pobieranie jest i co godzinę musisz captcha wpisywać.
