### ISSUE TITLE
lycamobile.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3145]
resztki po ciastkach na dole 

![capture](https://user-images.githubusercontent.com/15007183/28848954-d7fff98c-76e2-11e7-8471-d411edf54416.PNG)

**Comment by gzenio22** [comment]
hm u mnie tego nie ma

**Comment by hawkeye116477** [comment]
@gzenio22 Może masz ciasteczkowego potwora Fanboya i dlatego. Powinni już dawno zamienić w uBlocku listę EU: Prebake na EU: Fanboy's Cookiemonster List, ponieważ Prebake już nie jest aktualizowany. Więc nie wiem czy to blokujemy czy nie, blocker999 traktuje listę social jako uzupełnienie Fanboy's Social, więc równie dobrze można uznać naszą listę ciasteczek jako uzupełnienie ciasteczkowego potwora fanboya.
`lycamobile.pl##.cc-banner`
