### ISSUE TITLE
sonymobile.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3147]
dziura po ciastkach 

https://www.sonymobile.com/pl/products/phones/

![capture](https://user-images.githubusercontent.com/15007183/28849215-13365018-76e4-11e7-9ab2-738a0bd30f9d.PNG)

**Comment by hawkeye116477** [comment]
Nie wiem jak tego się pozbyć, tym chyba musi zająć się wielki mistrz blokady @F4z.

**Comment by MajkiIT** [comment]
`||www.sonymobile.com/wp-content/assets/js/app-global-0d8c2e7741ec32df708375c99f52af2f.js$script,domain=www.sonymobile.com`

Zerkniecie?

**Comment by hawkeye116477** [comment]
@MajkiIT Działa jak natura chciała.

**Comment by hawkeye116477** [comment]
@MajkiIT Niestety tego nie możemy dać, bo to zablokuje możliwość zalogowania się (nie można nacisnąć w przycisk ludzika).

**Comment by hawkeye116477** [comment]
@F4z Mistrzu możesz zerknąć?

**Comment by MajkiIT** [comment]
@hawkeye116477 tak przypuszczałem.

**Comment by F4z** [comment]
Może tak?
`sonymobile.com##.bnw-module.header[style="margin-top: 80px;"]:style(margin-top: 0px!important;)`

**Comment by MajkiIT** [comment]
dla mnie bomba. @F4z Dzięki

**Comment by hawkeye116477** [comment]
@F4z Jest git.
