### ISSUE TITLE
vrpolska.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3148]
resztki po ciastach 

http://forum.vrpolska.eu/viewtopic.php?t=416&start=10

![capture](https://user-images.githubusercontent.com/15007183/28849259-450e1a80-76e4-11e7-896c-1bc5bb2a7f84.PNG)

**Comment by gzenio22** [comment]
u mnie czysto?

**Comment by hawkeye116477** [comment]
@gzenio22 Pewnie dlatego, że ciasteczkowy potwór Fanboya zjada to na śniadanie.

**Comment by MajkiIT** [comment]
@hawkeye116477 postaram się dzisiaj, jak odzyskam kompa.
