### ISSUE TITLE
technowinki.onet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3149]
skapiec na dole

http://technowinki.onet.pl/nokia-9210-pl/hw6f0

![capture](https://user-images.githubusercontent.com/15007183/28849365-bc18c86e-76e4-11e7-8746-fbe4699a58b1.PNG)

**Comment by gzenio22** [comment]
technowinki.onet.pl##.lazyContent

Sprawdzcie czy po lewej za duzo nie zjadlo ale chyba bedzie ok

**Comment by hawkeye116477** [comment]
@gzenio22 Nie za dużo.
