### ISSUE TITLE
filmowe strony

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#315]
zobacz co sie da zrobic zeby wyczyscic z reklam czasami maja podlonczone cos pod play czasami druga strona sie otwiera

http://wkinie.tv/
http://www.tvseriesonline.pl/
http://kinofan.tv/
http://nocnyseans.pl/

**Comment by MajkiIT** [comment]
Ok jutro coś dodam do filtrów.

**Comment by MajkiIT** [comment]
Na moje oko kinofan.tv to fake...

**Comment by xxcriticxx** [comment]
masz cos lepszego?

**Comment by MajkiIT** [comment]
Reklamy na w/w stronach zablokowałem.

Zobacz tutaj http://ekino-tv.pl/
