### ISSUE TITLE
kwejk.pl - blur

### ISSUE THREAD

**Issue by mumaguma** [MajkiIT/polish-ads-filter#3150]
### Co trzeba zrobić aby reklama/element się pojawił
1. otworzyć https://kwejk.pl/
2. przejść 3-4 strony w ramach serwisu (obojętne, czy kolejne strony z obrazami, czy strony poszczególnych obrazów)
3.

### Twoja konfiguracja
**Przeglądarka:**
Firefox 54.0.1 32bity

**Operating system:**
win7 64bity sp1

**Blocker:**
ublock origin 1.13.8

**Używane filtry:**
1.POL: polskie filtry do Adblocka i uBlocka​​​​​
​​2. POL: polskie filtry do uBlocka uzupelnienie​
3. uBlockFilters

### Zrzut ekranu
```
http://i.share.pho.to/4a56f61c_o.png
```

**Comment by hawkeye116477** [comment]
@mumaguma Przeszedłem 6 stron i niestety tego blura dalej nie widzę.

**Comment by MajkiIT** [comment]
@mumaguma Ja też mam pusto. Jak dodasz tą listę to problem znika ?
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt

**Comment by F4z** [comment]
Ja to widzę. To jest to samo co tutaj - https://github.com/MajkiIT/polish-ads-filter/issues/3076

```
kwejk.pl#@#.pub_300x250
kwejk.pl#@#.pub_300x250m
kwejk.pl#@#.pub_728x90
kwejk.pl#@#.text-ad
kwejk.pl#@#.textAd
kwejk.pl#@#.text_ad
kwejk.pl#@#.text_ads
kwejk.pl#@#.text-ads
kwejk.pl#@#.text-ad-links
```

**Comment by MajkiIT** [comment]
@F4z dziękuję

**Comment by mumaguma** [comment]
@MajkiIT tak, nadal widziałem po dodaniu do list tej od Ciebie.
@F4z  dziękuję, pomogło :-)
