### ISSUE TITLE
mgsm.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3153]
http://www.mgsm.pl/pl/katalog/apple/iphone7plus/Apple-iPhone-7-Plus.html

![screenshot from 2017-08-02 06-45-08](https://user-images.githubusercontent.com/15007183/28870500-87ee7042-774e-11e7-9973-1d89af343045.png)

**Comment by MajkiIT** [comment]
`##.columns.small-12.medium-8.large-8 > .text-center.padding-bottom10.padding-top10.columns.small-12`
