### ISSUE TITLE
poranny.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3154]
resztki po reklamie w kilku miescach 

http://www.poranny.pl/polska-i-swiat/a/iphone-7-nowy-smartfon-od-apple-juz-jest-kosinski-siodemka-nie-jest-innowacyjna-ale-to-nic-zlego,10605366/

![screenshot from 2017-08-02 06-49-33](https://user-images.githubusercontent.com/15007183/28870577-c9df45bc-774e-11e7-8a28-6cca6f60a6a1.png)

**Comment by MajkiIT** [comment]
`poranny.pl###dfp-prawa1`

**Comment by xxcriticxx** [comment]
@MajkiIT jest w kilku miejscach na stronie nie tylko z prawej

**Comment by hawkeye116477** [comment]
@xxcriticxx Ja widzę tylko z prawej.
Jeszcze to: `poranny.pl##h2 > span`

**Comment by MajkiIT** [comment]
@hawkeye116477 Dzięki 
```
poranny.pl##h2 > span
poranny.pl###dfp-prawa1
```

**Comment by hawkeye116477** [comment]
@MajkiIT Jeszcze znalazłem reklamy gier: 
```
poranny.pl###LinkArea\:gry
poranny.pl##.gry
```
