### ISSUE TITLE
cookie monster

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3155]
@MajkiIT ja bym przekopiował te generic z listy cookie mknster i dodał .pl do nich

hawkej napewno po moze!

**Comment by hawkeye116477** [comment]
@xxcriticxx A nie lepiej po prostu dodać ich listę i traktować jako uzupełnienie naszej?

**Comment by hawkeye116477** [comment]
@xxcriticxx A tak BTW, mówisz o „Polish Site Generic Hiding Rules" tak?

**Comment by xxcriticxx** [comment]
@hawkeye116477 mozesz rozbudowac liste cookies widze ze masz duzo wolnego czasu

**Comment by hawkeye116477** [comment]
@xxcriticxx Jasne, mógłbym. Ale powtarzam pytanie, czy chodzi o „Polish Site Generic Hiding Rules" czy o coś jeszcze innego?

BTW, fajną nazwę fanboye wybrali dla ich listy - ciasteczkowy potwór :smile:

**Comment by xxcriticxx** [comment]
chodzic o ta liste https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt zeby dodac troche genetic filtrow typu ###pasek_ciasteczka

**Comment by hawkeye116477** [comment]
@xxcriticxx To ja wiem, że chodzi o to, żeby dodać do naszej. Ja pytałem czy chodzi o Polish Site Generic Hiding Rules z ciasteczkowego potwora fanboyów. Ale skoro mówisz o ###pasek_ciasteczka, to chyba o to chodzi, ale to tylko 1 filtr brakujący zdaje się.

**Comment by xxcriticxx** [comment]
@hawkeye116477 ok to masz prace domowa na wakacje!

**Comment by hawkeye116477** [comment]
@xxcriticxx Heh, odrobione :smiley:
https://github.com/hawkeye116477/polish-ads-filter/commit/27e8ec3127442c2efb0438646d7a61d97abaed19

**Comment by xxcriticxx** [comment]
@hawkeye116477 slabo sie starales na szybkiego to bylo

**Comment by hawkeye116477** [comment]
@xxcriticxx polish generic+18 issues, czyli prawie wszystko. A co byś jeszcze chciał?
