### ISSUE TITLE
pkssuwalki.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3157]
cookies

Ta strona wykorzystuje pliki cookies. Jeśli nie wyrażasz zgody na zapisywanie cookies na twoim urządzeniu, zmień ustawienia cookies w swojej przeglądarce. Jeśli potrzebujesz więcej informacji na ten temat, przejdź do zakładki Polityka prywatności dotycząca plików Cookies.

**Comment by gzenio22** [comment]
pkssuwalki.pl###ciasteczka_tresc

**Comment by hawkeye116477** [comment]
@MajkiIT To już raczej można zamknąć.
