### ISSUE TITLE
jung.de/pl/

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3158]
cookies

Informacje o ciasteczkach
Drogi Użytkowniku, w ramach naszej strony stosujemy pliki cookies. Ich celem jest świadczenie usług na najwyższym poziomie, w tym również dostosowanych do Twoich indywidualnych potrzeb. Korzystanie z witryny bez zmiany ustawień przeglądarki dotyczących cookies oznacza, że będą one umieszczane w Twoim urządzeniu. Więcej informacji znajdziesz tutaj.

**Comment by gzenio22** [comment]
jung.de/pl/###language-redirection-layer

**Comment by hawkeye116477** [comment]
@MajkiIT To już raczej można zamknąć.
