### ISSUE TITLE
eglobalcentral.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3159]
lewa prawa strona maybe

**Comment by gzenio22** [comment]
@MajkiIT Stanie sie cos na tej stronie albo innych jak uzyjemy tego?

||cdn.eglobalcentral.pl/images/banners/2017/SummerSale/17_8w1_SummerSale-side-CPL.jpg

**Comment by hawkeye116477** [comment]
@gzenio22 Ale to jest obrazek, raczej nie blokujemy bezpośrednio obrazków.

**Comment by hawkeye116477** [comment]
@xxcriticxx To jest reklama promocji na sprzęt na ich stronie, więc raczej bym to zostawił.

**Comment by MajkiIT** [comment]
Ja bym tylko usunął możliwość klikania w to` eglobalcentral.pl##[id^="publi"]`
