### ISSUE TITLE
cmg24.pl

### ISSUE THREAD

**Issue by cmg24** [MajkiIT/polish-ads-filter#316]
http://www.cmg24.pl/

AdBlock przestał wykrywać reklamy. Wcześniej blokował.

**Comment by MajkiIT** [comment]
Dziękuję. Dodam stosowne reguły.

**Comment by xxcriticxx** [comment]
malo ze strony zostanie jak reklamy znikna

**Comment by MajkiIT** [comment]
Na to wpływu nie mam, ale warto to zrobić.

**Comment by xxcriticxx** [comment]
cmg24 fajny nick cmg24.pl fajna strona 

lol...
