### ISSUE TITLE
cartests.net

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3160]
Przeglądając listę ciasteczkową fanboya zauważyłem, że na tej stronie jest dziura po reklamie.

**Comment by MajkiIT** [comment]
tam jest coś pomieszane. Trzeba będzie podciągnąć to do góry.

**Comment by hawkeye116477** [comment]
@F4z Mistrzu możesz zerknąć?

**Comment by F4z** [comment]
Moglibyście sprawdzić?
`cartests.net###td-outer-wrap > .td-header-wrap:style(margin-bottom: 0px!important;)`
`cartests.net##.td-container > .td-header-sp-recs`

**Comment by hawkeye116477** [comment]
@F4z Pierwsza reguła działa prawidłowo, a ta druga to nie wiem co ma schować.

**Comment by F4z** [comment]
Bez tego jest "niewidzialny" prostokąt, który zasłania część rzeczy i nie da się kliknąć.

![image](https://user-images.githubusercontent.com/11742596/28896568-37e3bba4-77dd-11e7-881a-e5f8208a797a.png)

**Comment by hawkeye116477** [comment]
@F4z Aha,ok. To też działa prawidłowo. Dzięki.

**Comment by MajkiIT** [comment]
@F4z Dzięki
