### ISSUE TITLE
motorolasolutions.com/pl_pl.html

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3166]
big cookie 

![capture](https://user-images.githubusercontent.com/15007183/28939475-6f1f6348-785f-11e7-9149-f9bcc7ca45ec.PNG)

**Comment by MajkiIT** [comment]
```
www.motorolasolutions.com##.ui-widget.ui-dialog
www.motorolasolutions.com##.ui-widget-overlay

```

**Comment by hawkeye116477** [comment]
@MajkiIT Tym sposobem zablokujesz linki do menu na stronie.
@xxcriticxx Szanują prywatność, a ty chcesz ich blokować, można nawet wybrać czy chcesz żeby ciebie śledzili :smiley: .

**Comment by hawkeye116477** [comment]
@MajkiIT Jaka jest twoja opinia?

**Comment by MajkiIT** [comment]
@hawkeye116477 
Wrzucimy to do polskich filtrów do sekcji prywatność. Dzięki
