### ISSUE TITLE
abbvie.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3168]
cookies

http://www.abbvie.pl/?trackingSelection=Ask

W ramach naszej witryny stosujemy pliki cookies w celu świadczenia państwu usług na najwyższym poziomie, w tym w sposób dostosowany do indywidualnych potrzeb. Korzystanie z witryny bez zmiany ustawień dotyczących cookies oznacza, że będą one zamieszczone w Państwa urządzeniu końcowym. Możecie Państwo dokonać w każdym czasie zmiany ustawień dotyczących cookies. Więcej szczegółów w naszej Polityce Prywatności.

![capture](https://user-images.githubusercontent.com/15007183/28939907-e08337ca-7860-11e7-8da9-2eef5ac250d9.PNG)

**Comment by hawkeye116477** [comment]
`abbvie.pl###omniTrackDiv`
