### ISSUE TITLE
mkidn.gov.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3169]
cookies

Używamy plików cookies, by ułatwić korzystanie z naszych serwisów.
Jeśli nie chcesz, by pliki cookies były zapisywane na Twoim dysku zmień ustawienia swojej przeglądarki.  Kliknij "Zamknij" aby zaakceptować naszą politykę.

**Comment by gzenio22** [comment]
Przyciemnienie

mkidn.gov.pl##.in.fade.modal-backdrop

Cookie

mkidn.gov.pl##.modal-body
mkidn.gov.pl##.modal-footer

**Comment by gzenio22** [comment]
jakis lepszy XD moge zamaskowac kilkoma regulami ale strona sie blokuje

**Comment by hawkeye116477** [comment]
@gzenio22 Wystarczy tylko `mkidn.gov.pl###myModal` i po sprawie :smile:.

**Comment by hawkeye116477** [comment]
Nowe sztuczki stosują :smiley:

**Comment by hawkeye116477** [comment]
Stara sztuczka ze scrollem. @F4z Mistrzu możesz zerknąć?
