### ISSUE TITLE
payback.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#3170]
Adblock.

![image](https://user-images.githubusercontent.com/11385099/28941599-d362e148-7898-11e7-99e2-c94e97042931.png)

**Comment by gzenio22** [comment]
em u mnie nie ma XD

**Comment by mathew85** [comment]
jesteś zalogowany?

**Comment by gzenio22** [comment]
nie to ktos inny by musial

**Comment by hawkeye116477** [comment]
Ja tam konta nie posiadam, ale może Corvo, zwany także @F4z coś na to poradzi :smile:.

**Comment by hawkeye116477** [comment]
@mathew85 A takie coś pomaga: `@@||payback.pl/statics/common/js/adverts.js` ?

**Comment by mathew85** [comment]
Hej. Próbowałem dzisiaj odtworzyć problem i na Chrome ani FF komunikat się nie pojawia.
Myślę, że na ten moment można zamknąć.
