### ISSUE TITLE
lexus-polska.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3171]
cookies

https://www.lexus-polska.pl/#Introduction

![capture](https://user-images.githubusercontent.com/15007183/28942072-ff01e5a0-7867-11e7-99bf-419565beb745.PNG)

**Comment by gzenio22** [comment]
lexus-polska.pl##.disclaimer__content

**Comment by hawkeye116477** [comment]
Albo po prostu: `lexus-polska.pl##.disclaimer`.

**Comment by gzenio22** [comment]
wlasnie kurde ej z kad wy wiecie co mozecie usunac z linijki zeby byla krotsza ale dzialala? nie potrafie tego ogarnac

**Comment by hawkeye116477** [comment]
@gzenio22 Były 2 takie reguły w trybie zaznaczania elementów, wybrałem po prostu tą krótszą.
Generalnie to ja po prostu usuwam to co jest przed kropkami i sprawdzam czy działa poprawnie :smile:.

**Comment by gzenio22** [comment]
@hawkeye116477 ja jak probuje edytowac te regolki to sie zawsze cos krzaczy boje sie z lekka usuwac cos czego nie rozumiem nie wiem brakuje mi moze wykrztaucenia jakiegos Xd jestem samoukiem lece zywiolowo

**Comment by hawkeye116477** [comment]
@gzenio22 W poprawnej pisowni to może tak, wykształcenia pisze się przez sz i ł , a regułki przez u zwykłe 😛 . Nie masz sprawdzania pisowni? Zdaje się, że każda przeglądarka to ma, a na Androidzie też coś tam jest, Swiftkey, Gboard i inne - mają sprawdzanie pisowni.

**Comment by gzenio22** [comment]
@hawkeye116477 sorry XD ja nigdy na orto nie zwracam zbytniej uwagi Xd chodziło mi raczej o to ze czesto nie rozumiem co dane frazy w regulach oznaczają albo do czego sie odnoszą
