### ISSUE TITLE
film.wp.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3173]
Prośba czy jak wejdziecie na stronę https://film.wp.pl/zmarl-evan-helmuth-6146521665177217a i klikniecie obrazek pod "Oglądaj: #dziejesiewkulturze: Sandra Bullock gotowa na wielki powrót" to blokuje Wam popup ?

**Comment by hawkeye116477** [comment]
@MajkiIT Tak właściwie to nie jest obrazek, tylko film. Na Vivaldim to działa mi poprawnie, bo uBlock Protector to naprawia, ale na Waterfoksie z AAK Cont już nie.

**Comment by hawkeye116477** [comment]
Zgłosiłem już to do speca.
https://github.com/jspenguin2017/uBlockProtector/issues/397

**Comment by MajkiIT** [comment]
@hawkeye116477 po prostu czytają co piszemy.

**Comment by hawkeye116477** [comment]
Już działa, chyba to był tylko chwilowy problem po mojej stronie albo update videwinde czyli wtyczki do DRM pomógł.

**Comment by hawkeye116477** [comment]
@MajkiIT Już działa, chyba to był tylko chwilowy problem po mojej stronie albo to update widevine, czyli wtyczki do DRM, pomógł. Jedynie nie ma opcji zmiany jakości i „inni widzieli także", ale tego wcześniej chyba też nie było.

**Comment by hawkeye116477** [comment]
@MajkiIT Można dać coś takiego i chyba wtedy uBlock Protector nie będzie potrzebny: `@@||wp.hit.gemius.pl/gplayer.js$script`.

**Comment by hawkeye116477** [comment]
@MajkiIT Można dać coś takiego i chyba wtedy uBlock Protector nie będzie potrzebny: `@@||wp.hit.gemius.pl/gplayer.js$script`.

**Comment by HateAds** [comment]
@hawkeye116477 @MajkiIT Panowie wp to "magia" tego nie idzie ogarnąć co z tą stroną się wyprawia. Zauważyłem, że jak wyłączę ublocka to i tak są problemy z ich playerem. Raz działa raz nie. Patrzcie przykładowo na ten link http://wp.tv/i,audi-a4-b9-avant-20-tdi-2016-test-autokultpl,mid,1991017,cid,8053,klip.html
Jedyna przeglądarka na której udało mi się to odpalić to Internet Explorer.
Ogólnie całe to wp jakieś chore, zobaczcie sobie chociażby na to.  
![image](https://user-images.githubusercontent.com/29756590/28969633-9ddf2b16-7925-11e7-97b3-d230fa11463f.png)
![image](https://user-images.githubusercontent.com/29756590/28969686-e44896dc-7925-11e7-98e8-860035cb4c43.png)
To są screeny z wp   https://parenting.pl/#
Widzicie jedną różnicę ? Raz góra jest na różowo, raz na biało jak się usunie cookies.
A w czym to przeszkadza, a no w tym, że jak jest ta góra z białym tłem to player nie chce działać :smiley::smiley::smiley:

**Comment by hawkeye116477** [comment]
@HateAds Mi ten filmik http://wp.tv/i,audi-a4-b9-avant-20-tdi-2016-test-autokultpl,mid,1991017,cid,8053,klip.html działa poprawnie z Vivaldi+uBlock Origin+uBlock Protector.

**Comment by HateAds** [comment]
@hawkeye116477 Po aktualizacji przez pingwina mi też zaczął filmik działać, ale widzę, że strasznie tnie. Ogólnie wp to ma chyba największy bajzel na tych swoich stronach. Nie widziałem tak źle działającej stron(y) nigdzie indziej.

**Comment by hawkeye116477** [comment]
@HateAds Jak góra jest z białym tłem, to nawet uBlock Protector nie pomaga.

**Comment by hawkeye116477** [comment]
@HateAds Pingwin naprawił już drugą wersję strony.

**Comment by HateAds** [comment]
@hawkeye116477 Działa szybko to naprawił. 
Mam jeszcze jedno pytanie do Ciebie. Czy są filtry na takie coś? 
![image](https://user-images.githubusercontent.com/29756590/28973520-b8b2ff72-7933-11e7-93db-7f1c3cbf6b60.png)

**Comment by hawkeye116477** [comment]
@HateAds Ta, mamy takie coś: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt + Fanboy's Social Blocking List.

**Comment by hawkeye116477** [comment]
@blocker999
![screenshot_20170804_165208](https://user-images.githubusercontent.com/19818572/28974075-6dde5a26-7935-11e7-8b3c-5881e451af62.png)
Możesz to dodać do socialów: `parenting.pl##.exitintent`?

**Comment by blocker999** [comment]
Ok dodam ale póżniej

**Comment by HateAds** [comment]
@MajkiIT Miałeś rację, popup blokuje playera.

**Comment by hawkeye116477** [comment]
@HateAds Na Chrome z Protectorem na pewno nie blokuje. A na Firefoxie z AAK Cont blokuje, bo AAK Cont jest sporo w tyle za Protectorem i tego nie naprawili.

**Comment by HateAds** [comment]
@hawkeye116477 Z ublock protectorem extension nie blokuje. Ale Mike chyba tego nie używa. Więc wyłączyłem extension, żeby zobaczyć jak to wygląda i próbuje mi jakieś 2 okienko wyskoczyć.

**Comment by hawkeye116477** [comment]
A tak BTW to Protector działa nie tylko na Chrome, ale też i na Chromium i Vivaldi oraz ChrOperze, trzeba tylko doinstalować Download Chrome Extension, choć ChrOpera chyba nie obsługuje wszystkich API z Chroma, więc może coś się zdarzyć, iż nie zadziała tak, jak trzeba.
@MajkiIT Nie korzystasz z uBlock Protector Extension?

**Comment by MajkiIT** [comment]
@hawkeye116477 Niestety nie, jadę na FF .

**Comment by hawkeye116477** [comment]
@MajkiIT Aha. Ja korzystam głównie z Waterfoksa, ale mam w zapasie Vivaldi i Chromium. Z Chromium czasem korzystam, bo na Vivaldim udostępnianie ekranu w Hangoutach nie działa, powiedzieli niby, że naprawią to, ale nie ma jeszcze terminu, więc muszę mieć Chromium.
Siedzę głównie na Waterfoksie z powodu rozszerzeń, tj. DownThemAll, All in One Sidebar, Classic Theme Restorer, a jak już rozszerzeń XUL/XPCOM nie będzie, to pewnie przesiądę się na Vivaldi. No chyba, że nagle wszyscy przerobią rozszerzenia na webextensions/experiments, ale zanim te eksperymenty wejdą do stable, to pewnie to potrwa trochę. Choć Waterfoks ma niby w planach zachowanie dawnych rozszerzeń, będą szli nieco inną drogą niż FF, ale zobaczymy jeszcze jak to się potoczy.
To chyba będziesz musiał mieć w zapasie drugą przeglądarkę lub się całkowicie przesiąść na inną, jeśli chcesz oglądać tam filmy. No ewentualnie wyłączyć uBlocka :smiley:. Bo u nas coś jak widać nie ma chętnych, by zrobić fork Protectora na Firefoksa, a drugi Maciej coś chyba nie ma na to czasu.

Chyba, że wielki mistrz @F4z zaproponuje jakiś whitelist czy coś.

**Comment by MajkiIT** [comment]
@hawkeye116477 jakoś nie ubolewam nad filmami na WP :P .

**Comment by HateAds** [comment]
@hawkeye116477 Czy z hackiem pingwina filmy na wp odpalają Ci się w najgorszej jakości ?

**Comment by hawkeye116477** [comment]
@MajkiIT Player.pl też nie działa z AAK Cont.
https://player.pl/filmy-online/weiser,57865.html

@HateAds Podaj przykładowy link. Mnie się wydaje, że ja on to zrobił tak:
```
if (item.quality === "HQ" && item.type.startsWith("mp4")) {
                                url = item.url;
                                break;
}
```
to powinny w najlepszej jakości.

**Comment by HateAds** [comment]
@hawkeye116477 https://opinie.wp.pl/niemieckie-media-milcza-o-rocznicy-powstania-warszawskiego-to-oczywiste-czy-jednak-troche-zaskakujace-6151140400264833a
U mnie w lq się odpala.

**Comment by hawkeye116477** [comment]
@HateAds A gdzieś jest napisane, że to LQ? Bo kiedyś zdaje się był wybór jakości, jak wyłączyłem oba uBlocki, a teraz tak zrobiłem i nie ma wyboru, od razu odpala się chyba w gorszej.

**Comment by HateAds** [comment]
@hawkeye116477 Jest wybór. 
![image](https://user-images.githubusercontent.com/29756590/29072164-e849d542-7c46-11e7-8846-26fd846b5318.png)

**Comment by hawkeye116477** [comment]
@HateAds U mnie na Chromium i Vivaldi nie ma wyboru jakości, ale na Waterfoksie jest, dziwne.
