### ISSUE TITLE
https://piwniczkamemow.pl/

### ISSUE THREAD

**Issue by Marcosoccer** [MajkiIT/polish-ads-filter#3174]
https://piwniczkamemow.pl/

Cała strona jest blokowana.

**Comment by hawkeye116477** [comment]
@Marcosoccer To już jest chyba wyższa szkoła jazdy. Raczej to do https://github.com/jspenguin2017/uBlockProtector albo https://gitlab.com/xuhaiyang1234/AAK-Cont .

**Comment by F4z** [comment]
Niekoniecznie, to jest podobne do tego co na kwejku było.
To powinno wystarczyć:
```
piwniczkamemow.pl#@#.pub_300x250
piwniczkamemow.pl#@#.pub_300x250m
piwniczkamemow.pl#@#.pub_728x90
piwniczkamemow.pl#@#.text-ad
piwniczkamemow.pl#@#.textAd
piwniczkamemow.pl#@#.text_ad
piwniczkamemow.pl#@#.text_ads
piwniczkamemow.pl#@#.text-ads
piwniczkamemow.pl#@#.text-ad-links
```

**Comment by MajkiIT** [comment]
@F4z Działa. Dzięki
