### ISSUE TITLE
naszemiasto.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3175]
Box po reklamach:
http://poznan.naszemiasto.pl

![image-20170804-001](https://user-images.githubusercontent.com/9846948/28967307-d5503226-791a-11e7-84a2-31348346f002.png)

![image-20170804-002](https://user-images.githubusercontent.com/9846948/28967436-6082d934-791b-11e7-86ca-00ad6360c00c.png)

Trudno określić kod blokowania elementu 
```
naszemiasto.pl###kol-prawa > DIV.row > DIV.large-12.medium-6.small-12.columns:nth-child(2)
```

**Comment by hawkeye116477** [comment]
Reklama gier: `poznan.naszemiasto.pl##.show-for-large-up.sbGry.sekcjaSzeroka`.

A reszty nie widzę. To jest na głównej stronie czy gdzieś indziej?

**Comment by MajkiIT** [comment]
Ja też bez tego elementu

**Comment by FadeMind** [comment]
![image-20170804-004](https://user-images.githubusercontent.com/9846948/28967893-ac0efc0a-791d-11e7-9a7e-0c57f8cfa0f5.png)

**Comment by hawkeye116477** [comment]
@FadeMind Ja tego nie widzę, gdzie ty to masz. A z jakiego blokera korzystasz, bo widzę tam jakieś C na czerwonym tle, co to w ogóle jest?

**Comment by FadeMind** [comment]
Korzystam z Adguard (takie zielone po prawej na dole, przezroczyste). Mam zasubskrybowane tylko filtry od CertificateIT. C to Click and Clean > https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod

**Comment by hawkeye116477** [comment]
@FadeMind A to pewnie dlatego ci ta reguła nie działa. Ja na Andku mam Yandex+Adguard i tam na wp.pl nie blokuje mi reklam, a na Firefoksie z uBlockiem 0 reklam.
Na tej stronie też widzę napis reklama, jeśli korzystam z Yandex+Adguard, czyli chyba któreś reguły nie są kompatybilne z Adguardem.
Wejdź na wp.pl z Adguardem i powiedz, czy też widzisz tam reklamy?

**Comment by xxcriticxx** [comment]
@FadeMind a liste pl adguard dodales?

**Comment by F4z** [comment]
Adguard w wersji dla Windowsa działa trochę inaczej niż rozszerzenia, ale nie wiem dlaczego w tym przypadku tego nie ukrywa.
Potem podam odpowiednią regułę.

Swoją drogą, ja napis "reklama" widzę i z uBlockiem.

<details><summary>Obrazek</summary>

![image](https://user-images.githubusercontent.com/11742596/28974974-9c2a3190-7938-11e7-8ca3-d7c9864297a3.png)

</details>
<br>

> na Andku mam Yandex+Adguard

Adguard Content Blocker?
Jeśli tak, to on nie obsługuje wszystkich reguł, dlatego tak może się dziać.
Ogólnie z Adguardem* te reklamy powinny być blokowane i filmy też powinny normalnie działać na wp.pl.

*nie uwzględniając rozszerzenia dla Opery i Firefoxa, bo tam z jakiegoś powodu reguły `JS` nie mogą być aktualizowane

**Comment by hawkeye116477** [comment]
@F4z Ta, https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker&hl=pl.

**Comment by F4z** [comment]
@hawkeye116477 no tak, pełna wersja powinna blokować te reklamy, tylko ona jest płatna.

**Comment by hawkeye116477** [comment]
@F4z Na Waterfoksie widzę napis reklama, a na Vivaldim już nie. 
Pewnie masz włączoną ochronę przed śledzeniem jak ja, wyłącz ją i napis „reklama" zniknie.

**Comment by FadeMind** [comment]
![image-20170804-010](https://user-images.githubusercontent.com/9846948/28975683-3d4f7cfe-793b-11e7-9446-63375c9ab2f3.png)

Używam pełnej wersji Adguard For Windows. Spełnia swoje zadanie, Niektóre reguły dla uBlocka/ADP mogą być niekompatybilnie składniowo z Adguardem i stąd te kwiatki.

Zrzut ekranu włączonych filtrów: (W filtrach użytkownika mam tylko białą listę stron, gdzie blokowanie nie jest mi potrzebne)

**Comment by hawkeye116477** [comment]
@F4z Na Waterfoksie widzę napis reklama, a na Vivaldim już nie. 
Pewnie masz włączoną ochronę przed śledzeniem jak ja, wyłącz ją i napis „reklama" zniknie.

**Comment by hawkeye116477** [comment]
@F4z Teraz to i mi na Vivaldim, jakimś cudem się pojawiło.
![screenshot_20170804_174206](https://user-images.githubusercontent.com/19818572/28975949-485e4a2a-793c-11e7-8e13-727cd01c2a79.png)

**Comment by F4z** [comment]
Wygląda na to, że oni tam sprawdzają, czy korzysta się z "Adblocka", i jeśli tak jest, to wtedy zmieniają nazwy elementów.

W zasadzie w przypadku Adguarda najlepiej będzie dodać coś takiego:
`naszemiasto.pl#%#window.adBlockTest = true;`

Dla uBlocka takie coś:
`naszemiasto.pl##script:inject(abort-on-property-write.js, czy_wlaczony_adblock)`

A dla Adblocka/Adblocka Plus takie dwie:
`naszemiasto.pl##center > a[href^="http://www.gratka.pl/"][target="_blank"] > img[src*="/tymczasowe/"]`
`naszemiasto.pl##.columns > p[style="margin-left: 40px; margin-bottom: 2px; text-align: left; font-size: 7pt; font-family: Verdana, Tahoma; color: #9d9d9d;"]`

I na te gry na dole:
`||pp.funhub.pl^$domain=naszemiasto.pl`
`naszemiasto.pl##.sekcjaSzeroka.sbGry`

Zaraz dodam te reguły w odpowiednie miejsca.
