### ISSUE TITLE
gamestough.com/pl/

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3178]
lewa i prawa strona 

![capture](https://user-images.githubusercontent.com/15007183/28982714-d7d7a4d4-7924-11e7-94dd-e9aacf3c93e3.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Ja tego nie mam. Flash jest wymagany?

**Comment by xxcriticxx** [comment]
`gamestough.com##.sbs_1000.left_sb`
`gamestough.com##.sbs_1000.right_sb`
