### ISSUE TITLE
gragra.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3179]
cookies

Wykorzystujemy pliki cookie do spersonalizowania treści i reklam, aby oferować funkcje społecznościowe i analizować ruch w naszej witrynie. Informacje o tym, jak korzystasz z naszej witryny, udostępniamy partnerom społecznościowym, reklamowym i analitycznym. Zobacz szczegółyUmowa

![capture](https://user-images.githubusercontent.com/15007183/28983378-783c6dcc-7927-11e7-902d-3b70104caf94.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Sprawdź czy za dużo nie blokuje: `||gragra.pl/js/cookies.min.js` .
Albo można dać coś takiego, tylko czy to nie jest losowe: `gragra.pl###WGsswwfyyt`?

**Comment by hawkeye116477** [comment]
`gragra.pl###WGsswwfyyt`
