### ISSUE TITLE
alawar.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3180]
![capture](https://user-images.githubusercontent.com/15007183/28985525-018f43d4-7931-11e7-8fba-7b0c7d97c0f9.PNG)

**Comment by gzenio22** [comment]
www.alawar.pl##.b-game-list__bnr-title-wrapper_offset.b-game-list__bnr-title-wrapper:nth-of-type(1) > .b-game-list__bnr-title_left.b-game-list__bnr-title

www.alawar.pl##.b-game-list__bnr-title-wrapper:nth-of-type(3) > .b-game-list__bnr-title_left.b-game-list__bnr-title

www.alawar.pl##.b-game-list__bnr-title-wrapper_offset.b-game-list__bnr-title-wrapper:nth-of-type(5) > .b-game-list__bnr-title_left.b-game-list__bnr-title

Da sie to skrocic? :D

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie ma takiej strony w ogóle, jest alawar.pl.
@gzenio22 Tak, od razu 3 znikną: `alawar.pl##.b-game-list__bnr-title_left.b-game-list__bnr-title`.

**Comment by MajkiIT** [comment]
@hawkeye116477 ale jest www.alamar.pl
