### ISSUE TITLE
anyfiles.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3182]
resztki dwa puste kwadraty

https://anyfiles.pl/index.jsp

![screenshot from 2017-08-05 07-48-59](https://user-images.githubusercontent.com/15007183/28995277-1c3b2270-79b3-11e7-8028-a4898bd777f1.png)

**Comment by hawkeye116477** [comment]
Ta, problem w tym, że te kwadraty pojawiają się raz tu, a raz tu po odświeżeniu strony.
Może @F4z pomoże.

**Comment by F4z** [comment]
Podobne zgłoszenie już kiedyś było - https://github.com/MajkiIT/polish-ads-filter/issues/1453#issuecomment-260127743

Wtedy proponowałem te dwie reguły i z tego co widzę dalej działają:
`anyfiles.pl###SearchVideosLoadDiv > .media-list > .media > .thumbnail:not([title])`
`anyfiles.pl###AllVideosLoadDiv > .media-list > .media > .thumbnail:not([title])`

Raczej nie powinno niczego psuć.

**Comment by MajkiIT** [comment]
@F4z dzięki
