### ISSUE TITLE
poczta.interia.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#3183]
Na zalogowanej poczcie, prze próbie kliknięcia na "opróżnij" dla Kosza czy Spamu strona przygasa, ale okienko się nie pojawia.

![image](https://user-images.githubusercontent.com/11385099/28996217-cb746ef2-79fb-11e7-89ce-311035262a36.png)

**Comment by F4z** [comment]
Nie jestem w stanie tego odtworzyć.

![image](https://user-images.githubusercontent.com/11742596/28996393-03135f90-7a00-11e7-81f6-cc3f8c289c83.png)

Z jakich filtrów korzystasz?

**Comment by mathew85** [comment]
Dziwa sprawa. Zacząłem po kolei odznaczać listy i po odznaczeniu 

> Popup Blocker PLUS ( PL )

okienko zaczęło się pojawiać.

Tylko jak zaznaczyłem z powrotem już nie mogę tego odtworzyć, bo działa prawidłowo. W trybie incognito też.

**Comment by F4z** [comment]
To widocznie po odznaczeniu i ponownym zaznaczeniu lista `Popup Blocker PLUS ( PL )` się zaktualizowała i problem został rozwiązany.
Z tego co widzę, to ta reguła mogła stanowić problem - https://github.com/azet12/PopupBlocker/blob/56f4aba76ed17f25f364521ce00c4d93465f8724/PPB.txt#L505
`~wykop.pl,pl##.overlay`
A dzisiaj została usunięta - https://github.com/azet12/PopupBlocker/commit/37daa62d22af00ab365ee3f962d24a02d2d41885#diff-e8b662a22222e5fb9f02df67781b8dccL505

**Comment by blocker999** [comment]
@mathew85 Niewiem ale umnie jest ok, prawdopodobnie była to wina popubblockera bo masz stare filtry zaktualizuj je i napisz czy pomogło.

**Comment by mathew85** [comment]
Wygląda, że teraz jest OK.

Znalazłem jeszcze jedną rzecz. Jak klikniemy na wyloguj przez pocztę to przechodzimy do strony:

> http://www.interia.pl/wyloguj.html#utm_source=konto&utm_medium=pasek_portalowy&utm_campaign=Wylogowania_z_poczty&iwa_source=layer_logout_mail

na której nic nie możemy kliknąć:

![image](https://user-images.githubusercontent.com/11385099/29001037-0144cfa4-7a7e-11e7-964a-4a40288e68f7.png)


po kilku sekundach przenosi nas na:

> http://www.interia.pl/#iwa_source=timeout

i jest już dobrze.

**Comment by blocker999** [comment]
Ok, przyjrze się itemu ale na przyszłość pisz bezpośrednio `_https://github.com/azet12/PopupBlocker/issues_`
tak będzie szybciej.

**Comment by MajkiIT** [comment]
@blocker999 pewnie myślał, że to Polska lista blokowała.
