### ISSUE TITLE
Tutorial o blokowaniu reklam na Androidzie (w przeglądarce Yandex)

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3184]
Jak blokować reklamy w przeglądarce Yandex na Androidzie?
A) Najlepszy sposób — Yandex z uBlock Origin i AAK Cont
Yandex Browser pozwala na instalację rozszerzeń z Chrome i (Chr)Opery. Jednakże po tapnięciu zainstaluj, w przypadku blokerów/adblokerów, podaje, że ich nie supportuje. Jednakże można to obejść, ale wymagana jest wersja Alpha lub Beta Yandexa, gdyż obecnie tylko na nich rozszerzenia takie jak uBlock Origin, działają prawidłowo.
Aby zainstalować uBlock Origin dla Yandexa, powinieneś wykonać parę kroków:
1. Po zainstalowaniu Yandex Browser możesz wejść w jego ustawienia (settings) i odznaczyć show Yandex Zen (Zen pokazuje newsy z różnych stron, wg. zainteresowań, historii, lokalizacji i innych czynników) i show ads above Tableau (to są oczywiście reklamy), następnie wejdź w notifications i odznacz show Tableau in the notifications bar (Tableau to widgety najczęściej odwiedzanych stron, w tym przypadku wyświetlane na pasku). Potem wróć do głównych ustawień i ustaw Shocking ad blocker na Disabled.
2. Potrzebny będzie eksplorator/menedżer plików. Jeśli nie masz żadnego, to polecam MiXplorer, którego pobierzesz z <a href="https://forum.xda-developers.com/showthread.php?t=1523691">xda-developers</a> lub aplikacji XDA Labs. A spolszczenie do MiXplorer pobierzesz <a href="http://www.mixplorer.com/language">stąd</a>.
3. Pobierz uBlock0.chromium.zip z https://github.com/gorhill/uBlock/releases.
4. Po pobraniu włącz MiXplorer, wejdź do katalogu, w którym plik się pobrał, prawdopodobnie jest to pamięć wewnętrzna/Download, odnajdź pobranego zipa, dotknij i przytrzymaj go, dotknij 3 kropki i wybierz — wypakuj.
5. Utwórz nowy katalog w dowolnym katalogu (dotknij + i katalog), wpisz jakąś nazwę, np. Rozszerzenia.
6. Wejdź do poprzednio utworzonego katalogu Rozszerzenia i dotknij na  górze na ikonę listy i na wypakuj i wybierz, że chcesz wypakować do bieżącego katalogu i dotknij ok.
7. Wróć do Yandexa, wpisz do paska adresu - `chrome://extensions` i potwierdź Enterem.
8. Zaznacz Developer mode, dotknij Load unpacked extension, wybierz MiXplorer i wejdź do katalogu, w którym masz rozpakowane rozszerzenie (Pamięć wewnętrzna/Rozszerzenia/uBlock0.chromium) i wybierz manifest.json.
9. Dotknij options przy uBlocku lub 3 kropki, a potem Extensions i wybierz uBlock Origin oraz dotknij zębatki, by wejść w ustawienia uBlocka.
10. Wybierz filtry, jakie chcesz. A jeśli 2 polskie ci nie wystarczają, to wejdź na certyficate.it/adblock i subskrybuj dodatkowe.
11. Po włączeniu filtrów sprawdź, czy uBlock Origin działa. Wejdź np. na wp.pl, jeśli tam nie ma reklam, to znaczy, że uBlock Origin działa. A jeśli są, to być może zrobiłeś coś nie tak, jak trzeba.
12. Gotowe!

Po poprawnym zainstalowaniu uBlocka nie będzie on automatycznie się aktualizował. Za każdym razem, jak pojawi się aktualizacja, należy to zrobić ręcznie zgodnie z instrukcją:
1. Usuń stary uBlock0.chromium.zip.
2. Pobierz nowy uBlock0.chromium.zip z https://github.com/gorhill/uBlock/releases.
3. Wypakuj nowy uBlock w te samo miejsce co stary — z nadpisaniem plików.
4. Włącz Yandex, następnie wpisz do paska adresu `chrome://extensions, potwierdź Enterem i dotknij Reload pod uBlock Origin.
5. Gotowe!

Do tego zestawu warto jeszcze doinstalować Anti-Adblock Killer Continued, który zajmie się skryptami typu „wyłącz Adblocka, bo inaczej nie pozwolimy ci wejść na stronę". Aby to zrobić:
1. Do AAK Cont potrzebny będzie ci Violentmonkey (otwartoźródłowy) lub Tampermonkey (zamkniętoźródłowy), więc po uruchomieniu Yandexa wejdź na https://chrome.google.com/webstore, następnie wpisz to, co wolisz mieć i dotknij — dodaj do Chrome, a następnie — add extension.
2. Zainstaluj skrypt AAK Cont z https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-script-ubo.user.js.
3. Subskrybuj filtr AAK Cont z https://xuhaiyang1234.gitlab.io/AAK-Cont/index.html#filterlist.
4. Włącz filtr Adblock Warning Removal List w uBlocku.
5. Sprawdź, czy działa. Wejdź na http://antiblock.org/?p=v3&demo. Jeśli wyświetli się komunikat „Please disable your ad blocker!", to znaczy, że być może zrobiłeś coś nie tak, jak trzeba, a jeśli nie, to gotowe!

B) Yandex + Adguard Content Blocker (ACB nie obsługuje wszystkich reguł)
1. Po zainstalowaniu Yandex Browser możesz wejść w jego ustawienia (settings) i odznaczyć show Yandex Zen (Zen pokazuje newsy z różnych stron, wg zainteresowań, historii, lokalizacji i innych czynników) i show ads above Tableau (to są oczywiście reklamy), następnie wejdź w notifications i odznacz show Tableau in the notifications bar (Tableau to widgety najczęściej odwiedzanych stron, w tym przypadku wyświetlane na pasku). Potem wróć do głównych ustawień i ustaw Shocking ad blocker na Disabled.
2. Zainstaluj Adguard Content Blocker z Google Play.
3. Wróć do Yandex, wejdź w jego ustawienia (settings), następnie tapnij na Content blocker extensions i wybierz Adguard Content Blocker.
4. Uruchom Adguard Content Blocker, następnie wejdź w filters i wybierz filtry, jakie chcesz. Jeśli nie ma tam filtrów, których szukasz, to tapnij 3 kreski, następnie user filter i import, a potem wpisz URL do filtru.
5. Sprawdź, czy działa, jeśli tak, to gotowe! A jeśli nie, to być może zrobiłeś coś nie tak, jak trzeba.

**Comment by hawkeye116477** [comment]
@MajkiIT Może taki tutorial na główną? Można też coś napisać o Adguard jako samodzielnej aplikacji i o Blokadzie jako alternatywy open-source: http://blokada.org/pl/index.html. Są też przecież przeglądarki z wbudowanym adblokerem, jak np. Brave (przeglądarka byłego CEO Mozilli), Dolphin Browser czy NoChromo, choć nie tak skuteczne jak zestawy z Yandexem czy Firefoxem. A dla zrootowanych urządzeń jest Adaway.

**Comment by xxcriticxx** [comment]
@hawkeye116477 rzuc to wszystko do wiki najlepjej

**Comment by hawkeye116477** [comment]
@xxcriticxx Tylko coś niestety nie wiem czemu, nie mogę teraz pisać w wiki.

**Comment by xxcriticxx** [comment]
@hawkeye116477 bo ostatnio byles niegrzeczny!

**Comment by MajkiIT** [comment]
hahahahahaha zerknę wieczorem ...

**Comment by hawkeye116477** [comment]
@xxcriticxx Heh, dobry żart :smiley: .

**Comment by MajkiIT** [comment]
@hawkeye116477 sprawdź teraz

**Comment by hawkeye116477** [comment]
@MajkiIT Dzięki, teraz mogę pisać na wiki. Może dołożę jeszcze filmik, tak jakby komuś nie chciało się tyle czytać :smile:.

A tak BTW, to czy Adguard dla Androida, nie ten Content Blocker, tylko zwykły, nie obsługuje niektórych reguł, bo na wp.pl nie chce blokować reklam?

**Comment by MajkiIT** [comment]
Niektóre reguły nie zawsze są zgodne z uBlockiem.

**Comment by hawkeye116477** [comment]
@MajkiIT Ale ja piszę o **Adguardzie**.

**Comment by MajkiIT** [comment]
No wiem, reguły do uBlocka nie pasują do Adguarda. Pewnie funkcjoinalność też jest mniejsza.

**Comment by MajkiIT** [comment]
@F4z ty na pewno znasz odpowiedź.

**Comment by hawkeye116477** [comment]
@MajkiIT Tyle, że ja korzystałem z głównych reguł, nie tych specyficznych dla uBlocka. A @F4z twierdził, że Content Blocker nie obsługuje niektórych reguł, a pełna wersja tak. No to zainstalowałem pełną wersję dla Androida, a i tak nie blokował, mimo, że nawet zainstalowałem certyfikat do https. Chyba, że @F4z miał na myśli pełną wersję dla Windowsa.

**Comment by MajkiIT** [comment]
@hawkeye116477 powiem Ci, że nigdy nie korzystałem z Adguard. Poczekajmy na odpowiedz F4z . Może być tak, że na androida funkcjonalność jest ograniczona. Celowo aby nie zamulić tel.

**Comment by xxcriticxx** [comment]
@hawkeye116477 ja z adguardem na iphonie nie mialem za dobrych rezultatow na wp

**Comment by hawkeye116477** [comment]
@xxcriticxx Adguard na iOS jest open-source tak jak Adguard Content Blocker dla Yandexa i Samsunga na Android. Na Androida jest jeszcze Adguard closed-source. Mają one jakieś różnice, bo np. Content Blocker to on korzysta z Content Blocker API przeglądarki, on sam nie jest adblokerem, on tylko przekazuje filtry do przeglądarki, która sama się zajmuje blokowaniem. Na iOS jest tak samo, on korzysta z Content Blocker API, czyli nie obsługuje wszystkich reguł. 
Tylko właśnie nie wiem co z tym closed-source Adguard for Android.

**Comment by F4z** [comment]
Adguard dla Androida z odpowiednimi ustawieniami obsługuje te same reguły co wersja na Windowsa.
@hawkeye116477 jaką masz ustawioną metodę filtrowania?
Żeby obsługiwał wszystkie reguły powinna być ustawiona na "Wysokiej jakości".
Oprócz tego, które listy masz włączone?
Do zablokowania reklam na wp.pl powinny wystarczyć `Angielski filtr` plus `Adblock & uBlock polish filter`.

@xxcriticxx niestety na iOS są ograniczenia i tam Adguard też nie obsługuje wszystkich reguł.

**Comment by F4z** [comment]
A odnośnie reguł, które Adguard obsługuje, to tutaj można przeczytać - https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters

**Comment by hawkeye116477** [comment]
@F4z To tak miałem i niestety na wp.pl nie chował reklam. A na pssite resztki zostawiał.

**Comment by F4z** [comment]
@hawkeye116477 u siebie reklam na wp.pl nie widzę, co prawda ja sprawdzałem w Chrome i Frefoksie, a nie w Yandex.
Mógłbyś podać linki do obu stron konkretnie?

**Comment by hawkeye116477** [comment]
@F4z W Chrome też sprawdzałem, było tak samo.
www.wp.pl www.pssite.com
A ty sprawdzasz na Androidzie czy Windowsie?

**Comment by F4z** [comment]
Na Androidzie.
Dzięki.

**Comment by F4z** [comment]
Nie wiem z czego ta różnica wynika, sprawdziłem obie strony na Androidzie w wersji mobilnej jak i komputerowej, reklam oraz resztek niestety nie widzę.
Jedynie mogę się zapytać, z którego trybu filtrowania korzystałeś i czy próbowałeś wyczyścić pamięć cache przeglądarki?

**Comment by hawkeye116477** [comment]
@F4z Z wysokiej jakości, na tablecie. Mnie się wydaje, że to ma związek z tym, że mam Noguata bez roota: https://blog.adguard.com/en/android-nougat-release-and-what-does-it-mean-for-adguard-users/. Choć pssite nie ma https, więc nie wiem czemu zostawiał resztki. Nie czyściłem cache, spróbuję potem jeszcze raz.

**Comment by F4z** [comment]
@hawkeye116477 no tak, o "wysoką jakość" pytałem się już wcześniej, chodziło mi o to czy tryb `VPN`, czy `Proxy`?
Z tym Nougatem, to też na forum Adguarda widziałem, że ktoś zgłaszał jakieś problemy, ale niestety w tej chwili nie pamiętam czego to dokładnie dotyczyło.

**Comment by xxcriticxx** [comment]
vpn or proxy to lista host?

**Comment by hawkeye116477** [comment]
@F4z VPN. Proxy jest chyba tylko dla zrootowanych, a ja nie mam roota. 
@xxcriticxx Nie

**Comment by hawkeye116477** [comment]
@F4z Sprawdziłem ponownie, tym razem na Androidzie 5.1 na smartfonie i jest tak samo, nie chowa wszystkiego. Może tryb proxy jest lepszy?

**Comment by F4z** [comment]
@hawkeye116477 raczej nie jest lepszy, ja korzystam z trybu VPN.
Na pewno masz wszystko włączone tak jak trzeba i zaktualizowane filtry?
Pytam, bo ja te reklamy widzę tylko jak wyłączę Adguarda, ewentualnie jeśli możesz to zrób screenshota żebym mógł sprawdzić, w którym miejscu szukać tych reklam/resztek.

**Comment by hawkeye116477** [comment]
@F4z Faktycznie, jakimś cudem miałem nieaktualne. Zaktualizowałem teraz i już działa poprawnie. Ale Adguard sam się wyłącza, powiedział, że się włączy, jak się inna apka z VPN wyłączy, tyle, że ja innej nie mam.

**Comment by F4z** [comment]
@hawkeye116477 a to już zupełnie nie wiem czemu tak się dzieje.
W zasadzie jak u Ciebie Adguard sprawia problemy, to myślę, że warto skorzystać z czegoś innego :)
Ewentualnie jeśli Ci zależy, to możesz zgłosić problemy tutaj - https://github.com/AdguardTeam/AdguardForAndroid/issues
Niestety nie ma odpowiedniej wiedzy żeby pomóc, może to kwestia jakichś ustawień, a może czegoś innego.

**Comment by xxcriticxx** [comment]
problem os trzeba zmienic

**Comment by hawkeye116477** [comment]
@F4z Mnie się wydaje, że to jakiś bug albo to dlatego, że ustawiłem inteligentne utrzymywanie w tle.
Yandex+uBlock Origin jest chyba the best :smile:.
@xxcriticxx Jasne, może to wina Flyme OS 6. Tam już 2 bugi znalazłem.

**Comment by xxcriticxx** [comment]
ja mam jedna box androida dalej jestem na 4.2

**Comment by hawkeye116477** [comment]
@xxcriticxx @MajkiIT Teledysk dla moich fanów: https://www.youtube.com/watch?v=DgSkfzSb5BI :smiley:.

**Comment by MajkiIT** [comment]
@hawkeye116477 Wow szacun. Mogę wrzucić na stronę i FB ?

**Comment by hawkeye116477** [comment]
@MajkiIT Tak.

**Comment by hawkeye116477** [comment]
@MajkiIT Jakby co, wersja tekstowa też już jest --> https://github.com/MajkiIT/polish-ads-filter/wiki/Jak-blokowa%C4%87-reklamy-w-przegl%C4%85darce-Yandex-na-Androidzie-(uBlock-i-AAK-Cont-lub-Adguard)

**Comment by MajkiIT** [comment]
@hawkeye116477 jesteś niezastąpiony :P

**Comment by MajkiIT** [comment]
@hawkeye116477 robisz furorę :P

**Comment by xxcriticxx** [comment]
@hawkeye116477 muzyka cienka! ale tutorial super dzieki

**Comment by hawkeye116477** [comment]
@xxcriticxx To co Taylor Swift byś wolał albo https://www.youtube.com/watch?v=cwLRQn61oUY :smiley: ?

**Comment by xxcriticxx** [comment]
despacito

**Comment by hawkeye116477** [comment]
@xxcriticxx To chyba jednak Confident byłoby lepsze, ale obu utworów raczej nie można wykorzystywać w ramach dozwolonego użytku. Dlatego ja brałem utwory do filmików głównie stąd ---> http://nocopyrightsounds.co.uk/.

**Comment by xxcriticxx** [comment]
@hawkeye116477 jaja sobie robie stym despacito

**Comment by blocker999** [comment]
@xxcriticxx  a może lepiej to : https://www.youtube.com/watch?v=daiHp-Sc7d8

**Comment by MajkiIT** [comment]
@blocker999 to pójdą spać po 1 min :D

**Comment by xxcriticxx** [comment]
dj już mamy @hawkeye116477 czekamy na pierwsze CD

**Comment by xxcriticxx** [comment]
https://www.youtube.com/watch?v=O9dqLWocnvI

https://www.youtube.com/watch?v=1dHOuroDoVs

**Comment by MajkiIT** [comment]
https://youtu.be/qN9WMu_uHH8
