### ISSUE TITLE
vod.tvp.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3187]
Podczas oglądania któregokolwiek filmiku pojawia się na ekranie odtwarzacza info o adblocku.

![vod tvp](https://user-images.githubusercontent.com/23176832/29003306-8a143fa0-7ab4-11e7-9974-e0dc43fa349b.png)

**Comment by hawkeye116477** [comment]
@blocker999 A skrypt AAK Cont albo rozszerzenie uBlock Protector zainstalowane?

**Comment by hawkeye116477** [comment]
@blocker999 A AAK Cont albo uBlock Protector zainstalowany?

**Comment by hawkeye116477** [comment]
@blocker999 U mnie nic takiego się nie pojawia. Jakie filtry masz i jakiego blokera?

**Comment by blocker999** [comment]
@hawkeye116477 Niewiem jakim cudem ale miałem filtry językowe odhaczone 2x POL w ublocku teraz jest ok.
