### ISSUE TITLE
repostuj.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3188]
```
||mrex.exs.pl^$third-party
||repostuj.pl/static/repostujpl/js/js.cookie.min.js$domain=repostuj.pl
||repostuj.pl/static/repostujpl/arrow_right.jpg$domain=repostuj.pl
```

1. usuwa reklamę flash
2. usuwa powiadomienie o ciasteczkach
3. usuwa strzałkę w prawo, która nic nie robi

**Comment by hawkeye116477** [comment]
@FadeMind Wydaje mi się, że zablokowanie js.cookie.min.js dodatkowo może coś popsuć.
https://github.com/js-cookie/js-cookie
Lepsze chyba będzie coś takiego: `repostuj.pl##.cc-window`

**Comment by hawkeye116477** [comment]
@MajkiIT Jeszcze reklamy zostały.
