### ISSUE TITLE
przeznaczeni.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3193]
@MajkiIT cos dla ciebie 

Portal randkowy dla ludzi z wartościami

Serwis korzysta z plików cookies w celu realizacji świadczonych usług. Możesz zarządzać plikami cookies określając ustawienia przeglądarki internetowej. Dalsze korzystanie z Serwisu oznacza zgodę na korzystanie z plików cookies zgodnie z Polityką Prywatności.

**Comment by MajkiIT** [comment]
@xxcriticxx Super dzięki. Już się rejestruje. :P

**Comment by hawkeye116477** [comment]
@xxcriticxx A może dla ciebie raczej, ty tak często wchodzisz na takie portale,

**Comment by xxcriticxx** [comment]
@hawkeye116477 bo wiem ze tam benda swierze ciastka

**Comment by hawkeye116477** [comment]
@xxcriticxx Jasne, świeże ciastka :smiley:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 a ile myslales ze mam lat?

**Comment by hawkeye116477** [comment]
@xxcriticxx 40

**Comment by xxcriticxx** [comment]
69

**Comment by hawkeye116477** [comment]
@xxcriticxx 😲

**Comment by hawkeye116477** [comment]
`##.cookies-box:not(body):not(html)`
