### ISSUE TITLE
mcksokol.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3198]
cookies

Strona korzysta z plików cookie w celu realizacji usług zgodnie z Polityką prywatności. Korzystając ze strony wyrażasz zgodę na używanie cookie, zgodnie z aktualnymi
ustawieniami przeglądarki. Warunki przechowywania lub dostępu do plików cookies możesz określić w Twojej przeglądarce.

**Comment by hawkeye116477** [comment]
`mcksokol.pl###overflow-content`
