### ISSUE TITLE
okocim.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3202]
nie moge wesc do dalej do strony moze ktos sprawdzic co blokuje 

![capture](https://user-images.githubusercontent.com/15007183/29006338-aaa96e1e-7abb-11e7-9b4d-fa67d5ea0b75.PNG)

**Comment by xxcriticxx** [comment]
jade po piwo bo okocim nie chcial mnie wpuscic

**Comment by MajkiIT** [comment]
to celowe, wynikające z polskiego prawa.

**Comment by xxcriticxx** [comment]
wiem ale przesc dalej nie da rady

**Comment by F4z** [comment]
Bo niepełnoletni jesteś 😝

**Comment by F4z** [comment]
A tak na poważnie, jak kliknę "Zapamiętaj mnie", a potem "Tak", to przechodzi dalej.
