### ISSUE TITLE
bezprawnik.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3204]
Reklama - mytaxi

**Comment by gzenio22** [comment]
bezprawnik.pl##.hidden-sm.hidden-xs.col-md-4 > .row:nth-of-type(1)

**Comment by MajkiIT** [comment]
`bezprawnik.pl##.ads`

@gzenio22 ciut prościej :)

**Comment by gzenio22** [comment]
bardzo prosciej Xd ja kurde nie wiem czesto jak wy skracacie albo skad bierzecie takie krotkie

**Comment by hawkeye116477** [comment]
@gzenio22 Magia :smiley:
@MajkiIT Tutaj jeszcze reklamy zostały --> #3188.
