### ISSUE TITLE
cocomoda.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3205]
coocies

**Comment by gzenio22** [comment]
cocomoda.pl###content > .container:nth-of-type(1)

**Comment by blocker999** [comment]
Nie lepiej `cocomoda.pl##.message_cookie.info`

**Comment by hawkeye116477** [comment]
@blocker999 Można jeszcze krócej: `pl##.message_cookie`.

**Comment by blocker999** [comment]
@hawkeye116477 Tez jestem za ale wątpie by @MajkiIT się na to zgodził.

**Comment by MajkiIT** [comment]
@hawkeye116477 może i warto tak dodać. 
@blocker999 będziemy próbować, jak coś to się poprawi.

**Comment by hawkeye116477** [comment]
@MajkiIT W I don't care about cookies jest podobna reguła: `##.message_cookie:not(body):not(html)`.

**Comment by MajkiIT** [comment]
jest obwarowanie, może warto dodać taką samą, skoro oni tak zrobili.

**Comment by hawkeye116477** [comment]
@MajkiIT Oni do wszystkich ogólnych dodali `:not(body):not(html)`. Gorhillowi chyba coś to się nie spodobało.
> That list is quite suboptimal for uBO to say the least, it prefixes all generic cosmetic filters with body [#.], which prevents uBO from optimizing their use. Unless somebody removes instances of body for filters matching /^##body [#.]/, I would advise strongly against using it with uBO.

**Comment by hawkeye116477** [comment]
@MajkiIT Oni do wszystkich ogólnych dodali `:not(body):not(html)`.
