### ISSUE TITLE
WPR Ulubiona

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3206]
https://media2.pl/internet/143815-Reklama-daje-wolnosc-mediom-w-nowej-kampanii-Wirtualnej-Polski.html

**Comment by hawkeye116477** [comment]
Jaka niespodzianka od WPR, na prawdę nie spodziewałem się 😲
![screenshot_20170808_112919](https://user-images.githubusercontent.com/19818572/29065573-d765ff54-7c2c-11e7-91a9-427eb054d9a8.png)
