### ISSUE TITLE
www.se.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#321]
adblock

http://www.se.pl/wiadomosci/ciekawostki/hipotermia-wyziebienie-organizmu-co-jest-objawy-jak-reagowac-najslynniejsze-przypadki_475858.html

Nasz serwis jest całkowicie darmowy. Pokazujemy reklamy, żeby taki pozostał.

Wyłącz Adblock (lub podobny program) i przeglądaj portal bez ograniczeń.
Przypomnij mi później

**Comment by xxcriticxx** [comment]
stym nic?

**Comment by MajkiIT** [comment]
https://github.com/reek/anti-adblock-killer/issues/992
