### ISSUE TITLE
direct.money.pl i money.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3210]
https://money.pl/
https://direct.money.pl/
```
money.pl##.recommended
direct.money.pl##.main-menu__submenu__offer
```

Reguły usuwają promowane produkty (box na money.pl oraz box w menu po prawej stronie każdej z kategorii na direct.money.pl

**Comment by MajkiIT** [comment]
@FadeMind Dzięki
