### ISSUE TITLE
fm.tuba.pl [AntyAdblock][Adguard]

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3211]
http://fm.tuba.pl/play/10/2/radio-tok-fm?appId=03

![image-20170808-005](https://user-images.githubusercontent.com/9846948/29087398-129895de-7c76-11e7-952b-29e952c5b0f1.png)

![image-20170808-006](https://user-images.githubusercontent.com/9846948/29087537-95621b5c-7c76-11e7-8272-d622986b1553.png)

Adguard For Windows Beta 6.2.390.2018 (build z dzisiaj) 
Chrome (najnowszy, stable)

@F4z @MajkiIT

**Comment by F4z** [comment]
Mógłbyś sprawdzić?
`@@||images.fm.tuba.pl/tuba3/_js/banner/advertisement.js`
Ewentualnie dla Adguarda:
`tuba.pl#%#window.adsOk = true;`

**Comment by MajkiIT** [comment]
@F4z dzięki

**Comment by hawkeye116477** [comment]
Już takiego coś podobnego jest w AAK Cont i uBlock Protector: `@@/advertisement*.js$first-party,script`.

**Comment by FadeMind** [comment]
@MajkiIT powtórka z rozrywki, 
![image-20170828-001](https://user-images.githubusercontent.com/9846948/29766092-e41b9c7a-8bdd-11e7-95b3-6eec3faefded.png)

dodanie 
```
tuba.pl#%#window.adsOk = true;
@@||images.fm.tuba.pl/tuba3/_js/banner/advertisement.js
```
nie pomaga.

CC @F4z

**Comment by hawkeye116477** [comment]
@FadeMind Na uBlocku mam to samo teraz.

**Comment by MajkiIT** [comment]
@FadeMind na jakiej przeglądarce to masz?

**Comment by FadeMind** [comment]
Chrome Stable Lastest

**Comment by hawkeye116477** [comment]
@MajkiIT U mnie to zarówno jest i na Waterfoksie, jak i Vivaldim oraz Chromium. Nawet reguła z generichride nie pomaga.
https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/218

**Comment by FadeMind** [comment]
@MajkiIT 

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by hawkeye116477** [comment]
@FadeMind A po co 2 Adguardy? Jeden nie wystarczy? Ten na Windę słyszałem, że lepszy niż rozszerzenie.

**Comment by FadeMind** [comment]
@hawkeye116477 https://adguard.com/pl/adguard-adblock-browser-extension/integration-mode.html#integration-mode

**Comment by MajkiIT** [comment]
@FadeMind sprawdź proszę to
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=fm.tuba.pl`

**Comment by FadeMind** [comment]
@MajkiIT  reguła działa
![image-20170828-004](https://user-images.githubusercontent.com/9846948/29771441-0851fa24-8bf4-11e7-9eaa-9749ca6cc2e5.png)

**Comment by hawkeye116477** [comment]
@MajkiIT Prawie sytuacja opanowana, na Waterfoksie to działa, ale na Vivaldim z włączonym Protectorem już nie. Także chyba to trzeba będzie do pingwina zgłosić.

**Comment by MajkiIT** [comment]
@hawkeye116477 ok, dzięki. Wykreuję sobie kolejną wirtualkę z ublock + Protekctorem aby testować.

**Comment by hawkeye116477** [comment]
@MajkiIT Zgłosiłem to już: https://github.com/jspenguin2017/uBlockProtector/issues/547. Może pingwin to naprawi.

**Comment by FadeMind** [comment]
@MajkiIT  @F4z  nowe blokady
![2017-09-18 12_18_18-radio tok fm - sluchaj online na tuba fm opera](https://user-images.githubusercontent.com/9846948/30537835-999cb208-9c6b-11e7-9b22-0d043f26d08b.png)

**Comment by hawkeye116477** [comment]
Serio, znowu? A to dranie 😃 . A nie lepiej posłuchać radia na smartfonie za pomocą aplikacji Scrobble FM albo TuneIn? A można też i w TV i na tunerze satelitarnym z Linuxem (np. w OpenPLi), tam przynajmniej nie ma takich reklam 😄 .
