### ISSUE TITLE
tele-wizja.com

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3213]
http://tele-wizja.com/polsat-sport/

![image-20170808-008](https://user-images.githubusercontent.com/9846948/29088941-13f3ce76-7c7b-11e7-99e9-222890811586.png)

Przycisk na odtwarzaczu.

**Comment by hawkeye116477** [comment]
@FadeMind Wykup abo w CP, to zniknie :smiley:.
Chyba to jest coś podobnego do #3001, ale do tego niestety to nie działa.

**Comment by F4z** [comment]
`srkcast.com###table2`
albo
`srkcast.com##[id^="table"]`
jakby dodali/zmienili na table3

**Comment by MajkiIT** [comment]
@F4z Dzięki
