### ISSUE TITLE
newsweb.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3215]
![image-20170808-010](https://user-images.githubusercontent.com/9846948/29090097-c9e47944-7c7e-11e7-946c-68dd034ff003.png)

```
newsweb.pl##.adsbygoogle
```

**Comment by hawkeye116477** [comment]
@FadeMind To już jest w EasyList: `##.adsbygoogle`.

**Comment by FadeMind** [comment]
Adguard ma swoje listy :P Muszę im dać znać zatem ;)

**Comment by F4z** [comment]
Adguard korzysta z EasyList i ma regułę `##.adsbygoogle`.
Tutaj jest taka sytuacja, że ten element ma ustawione `display: block !important;` i przez to nie jest schowany.
Z tego co wiem, to uBlock trochę inaczej ukrywa elementy niż Adblock/Adblock Plus (one też nie ukrywają tego elementu) i Adguard, stąd ta różnica.
Można dodać taką regułę:
`newsweb.pl##body .td-header-style-11 .td-g-rec-id-header .adsbygoogle`
wtedy wszystkie "adblocki" powinny to ukryć.

**Comment by FadeMind** [comment]
@F4z
![s](http://zzapolowy.com/wp-content/uploads/2017/03/Pochettino-Yoda.jpg)
