### ISSUE TITLE
prostozmostu.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3216]
Pozostałość `Zamknij` po banerze PopUp. Przesuwa się. Nie mogę uzyskać kodu blokady, bo po kliknięciu w trybie zaznaczania elementu przycisk znika. 

![image-20170808-011](https://user-images.githubusercontent.com/9846948/29090294-59e4b414-7c7f-11e7-889d-2f36058a2e33.png)

**Comment by MajkiIT** [comment]
@FadeMind Adguard?

**Comment by FadeMind** [comment]
tak

**Comment by MajkiIT** [comment]
pl##.contentsystem-slide-link

**Comment by xxcriticxx** [comment]
@F4z dorabiasz na adguardzie pod innym nickem? https://github.com/AdamWr

**Comment by F4z** [comment]
@xxcriticxx tak :)
