### ISSUE TITLE
polsatnews.pl [adguard][fix]

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3217]
![image-20170808-012](https://user-images.githubusercontent.com/9846948/29092854-0778575e-7c88-11e7-8046-d12c7edf924f.png)

```
@@||polsatnews.pl/templates/pnews/js/fingerprint2.min.js
```

FIX dla polsatnews.pl odblokowujący sondę programu TAK czy NIE.

**Comment by MajkiIT** [comment]
@FadeMind Dzięki

**Comment by Nalapl3** [comment]
Ten skrypt ([fingerprintjs2](https://github.com/Valve/fingerprintjs2)), służy do fingerprintingu, czyli wirtualnego "odcisku palca" użytkownika, na podstawie danych serwowanych przez przeglądarkę w JavaScripcie. Dane te, uzyskiwane są, jak mniemam w celu blokowania manipulacji głosami, ale może on także stanowić zagrożenie dla prywatności (te dane mogą być później wykorzystywane w celu identyfikacji użytkownika). Dlatego uważam, że nie powinien on być odblokowany. 

[Tutaj](https://github.com/Valve/fingerprintjs2#list-of-fingerprinting-sources) można zobaczyć dokładnie, jakie dane pobiera ten skrypt.
