### ISSUE TITLE
kwejk.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3219]
![image-20170809-002](https://user-images.githubusercontent.com/9846948/29110909-9c27d8f6-7ce8-11e7-96a3-24a1428a1241.png)

![image-20170809-003](https://user-images.githubusercontent.com/9846948/29110952-bfb6dff6-7ce8-11e7-8860-1105e747e3d4.png)

FIX

```
||*.spolecznosci.net^
```

**Comment by MajkiIT** [comment]
Ale to jest w polskich filtrach 
`||spolecznosci.net^$script `

@F4z ta reguła z PL też jest zła ?

**Comment by hawkeye116477** [comment]
@FadeMind U mnie jest ok, zapewne to tylko Adguarda dotyczy.

**Comment by FadeMind** [comment]
@MajkiIT  w polskich regułach mam tak:
```
||spolecznosci.net^$image,subdocument,script,popup
```
ale to nie działa w Adguard. 

Dopiero 
```
||spolecznosci.net^
```
(nawet bez prefixu `*.` ) załatwia sprawę.

**Comment by MajkiIT** [comment]
@FadeMind 
Regułę `||spolecznosci.net^$script` wyciągnąłem z blokowanych elementów, która jest kawałkiem reguły `||spolecznosci.net^$image,subdocument,script,popup ` . A możesz sprawdzić taką regułę `||spolecznosci.net^$script`

**Comment by FadeMind** [comment]
```
||spolecznosci.net^$script
```
działa poprawnie.

**Comment by MajkiIT** [comment]
@FadeMind 
Ok dziękuję. A jak dodasz `||spolecznosci.net^$script,popup`

**Comment by FadeMind** [comment]
```
||spolecznosci.net^$script,popup
```
nie działa w Adguard. Reklama się wyświetla.

**Comment by MajkiIT** [comment]
@FadeMind 
wychodzi, że nie ma reguły popup `https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters`

Jeśli możesz to sprawdź` ||spolecznosci.net^$image,subdocument,script`

**Comment by FadeMind** [comment]
Popup jest osobno:
![image-20170809-005](https://user-images.githubusercontent.com/9846948/29113450-4dac4316-7cf1-11e7-9529-bf1c37667e37.png)
Reguła 
```
||spolecznosci.net^$image,subdocument,script
```
działa. Zalecam dodanie `third-party` do identyfikacji:
```
||spolecznosci.net^$image,subdocument,script,third-party
```

**Comment by MajkiIT** [comment]
Dodałem do filtrów do Adguarda. Co do `third-party` to potestuję chwilę.
