### ISSUE TITLE
eholiday.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3225]
https://www.eholiday.pl/noclegi-de6781.html

![capture](https://user-images.githubusercontent.com/15007183/29133714-5d03f438-7d02-11e7-86ba-b4e48d019143.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Rozumiem, że górny banner się nie podoba?
```
eholiday.pl##.box-top-baner
eholiday.pl###appear_event
```
