### ISSUE TITLE
ios soft

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3227]
@xxcriticxx widziałeś 
https://itunes.apple.com/US/app/id1167551053?mt=8

**Comment by xxcriticxx** [comment]
@MajkiIT trzeba placic blah $0.99

**Comment by xxcriticxx** [comment]
jego drugi app to co dla @hawkeye116477 

Słownik Rymów - polskie rymy
By Michal Buczek
View More by This Developer

Open iTunes to buy and download apps.
Description

Jedyna w aplikacja na rynku wyszukująca poprawnie polskie rymy. Dosyć zagranicznych odpowiedników z polskim słownikiem, które wykładają się na rodzimych znakach (nie wyszukają rymu zasuwka-borówka)

**Comment by xxcriticxx** [comment]
@MajkiIT zapros do nas 

https://github.com/vsemaphore

**Comment by hawkeye116477** [comment]
@xxcriticxx A mi niby po co słownik rymów?

**Comment by xxcriticxx** [comment]
@hawkeye116477 na twoje pierwsze cd

**Comment by hawkeye116477** [comment]
@xxcriticxx To raczej dla mojego tekściarza :smiley:.

**Comment by MajkiIT** [comment]
@xxcriticxx Ok zaproszę

**Comment by xxcriticxx** [comment]
![img_6120](https://user-images.githubusercontent.com/15007183/29147819-882741bc-7d37-11e7-8e9a-c9f3e8a78ebd.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx co to?

**Comment by hawkeye116477** [comment]
Jest jeszcze coś takiego, tyle że za free: https://itunes.apple.com/app/id1025729002. Pewnie coś jeszcze jest za free, więc po co przepłacać, no chyba, że coś tam unikalnego posiada ten polski adbloker.
A tak BTW to, coś widzę mocno ograniczone te adblokery na iOS, wszystkie chyba korzystają z content blocker API Safari. Dobrze, że ja mam Androida i mogę korzystać z uBlocka :smile:.

**Comment by xxcriticxx** [comment]
@MajkiIT pihole blokowanie host file to samo co u ciebie router

**Comment by xxcriticxx** [comment]
@hawkeye116477 mam tez adguarda na iphonie

**Comment by hawkeye116477** [comment]
@xxcriticxx A tak, coś wspominałeś ostatnio. Ponoć 1Blocker zżera mniej zasobów niż Adguard, ale blokuje tylko reklamy za free, za resztę chcą cwaniaki 9.99$, coś mocno się cenią :smiley:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 zakup i powiec czy dziala :)

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie mam iOS.
<img src="http://www.quertime.com/wp-content/uploads/2014/05/apples_are_great_for_eating.jpg">
