### ISSUE TITLE
pl.jooble.org

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3228]
reklama infopraca.pl prawa strona

https://pl.jooble.org/praca-inspektor/Warszawa

**Comment by gzenio22** [comment]
pl.jooble.org###popup

Ktos musi jeszcze tylko jakos odblokowac scrolla

**Comment by hawkeye116477** [comment]
@gzenio22 Popup to raczej do PopupBlockera. 
A co do reklamy po prawej, to można też tak, będzie trochę krócej: `##.banner-wrap`.
