### ISSUE TITLE
mediaexpert.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3229]
@MajkiIT Reguła `mediaexpert.pl##.nletter_popup` blokuje pojawianie się popupu newslettera, z którego można zgarnąć 10 zł na zakupy. Wydaje mi się, że ta reguła powinna raczej być w PopupBlockerze, a nie tu.

**Comment by MajkiIT** [comment]
@hawkeye116477 reguła jest na liście PL. Zaraz usunę.
