### ISSUE TITLE
www.x-kom.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#323]
Cookies:

http://www.x-kom.pl/

**Comment by xxcriticxx** [comment]
ja nic nie widze 

masz zamotowane Adblock & uBlock polish cookies filters‎ : 648 used out of 649purge cache???

**Comment by mathew85** [comment]
Tak. Listę miałem nie najnowszą, ale po aktualizacji to samo:

http://imgur.com/0lCsXUu

**Comment by xxcriticxx** [comment]
otym co mowilem filtry czasami przycinaja

**Comment by MajkiIT** [comment]
na ublocku jest ok.

**Comment by xxcriticxx** [comment]
filtry sie czasem zacinaja i dlatego wyskoczyl cookies msg
