### ISSUE TITLE
Zippyshare.com

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3231]
Hej sluchajcie namierzylem cos co dosc zadko sie zdarza ale jednak sie zdarza a ja wiem jak sie tego pozbyc 

![screenshot_1](https://user-images.githubusercontent.com/21177361/29183597-9102cb22-7e03-11e7-95b8-7d925c4c4963.png)

To calkowicie blokuje strone do chwili odswierzenia nie umiem tego stricte wywolac to sie pojawia sporadycznie ale mam na to regułke 

regulka: Zippyshare.com###hiddenDropArea

**Comment by F4z** [comment]
To się powinno pojawiać w momencie kiedy jesteś na stronie zippyshare i "przeniesiesz" jakiś plik do okna przeglądarki.
Myślę, że nie powinniśmy tego blokować.

**Comment by gzenio22** [comment]
@F4z problem w tym ze ja nic nie przenosilem :D to sie tak z glupa pojawia a orginalnie u mnie ten sposob nie dziala
