### ISSUE TITLE
rolpetrol.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3235]
Coocies oraz w tym notowaniu reklama " TRANSROL " : 
http://www.rolpetrol.com.pl/notowania/zboza/

**Comment by gzenio22** [comment]
Cookies
rolpetrol.com.pl##body > div:nth-of-type(1)

reklama
rolpetrol.com.pl###advertisments

**Comment by hawkeye116477** [comment]
@gzenio22 Albo można nieco krócej:`||rolpetrol.com.pl/cookies.js$script`.
