### ISSUE TITLE
twojepajeczno.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3236]
```
twojepajeczno.pl##.rekslide
```

usuwa pokaz slajdów z banerami w dwóch miejscach (TOPHEADER & RIGHTSIDE)

![image-20170811-001](https://user-images.githubusercontent.com/9846948/29203600-5c67dcc6-7e72-11e7-970f-6b97ab71a764.png)

![image-20170811-002](https://user-images.githubusercontent.com/9846948/29203602-621715b0-7e72-11e7-8879-b30a601ce9e1.png)

**Comment by MajkiIT** [comment]
@FadeMind dzięki
