### ISSUE TITLE
niemarkowe.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3240]
Cookies

**Comment by hawkeye116477** [comment]
@blocker999 Nie ma ciastek, tylko Facebook z prawej.
`niemarkowe.pl###likebox_1`

**Comment by blocker999** [comment]
faceboka niedało się niezauważyć, natomiast ciastka są całkiem na dole

**Comment by MajkiIT** [comment]
Ale to static.
