### ISSUE TITLE
kino.krakow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3244]
cookies

http://www.kino.krakow.pl/film/jestem-morderca.html

Pliki cookies

W ramach naszych serwisów internetowych stosujemy cookies. Używamy cookies żeby zrozumieć jak użytkownicy korzystają z witryny i dostosować ją tak, aby korzystanie z niej było łatwiejsze i przyjemniejsze. Stosujemy Cookies również w celach statystycznych oraz reklamowych. Cookies mogą być również stosowane przez współpracujących z nami reklamodawców oraz przez firmy badawcze.
W każdej chwili mogą Państwo zmienić swoje ustawienia dotyczące cookies. Korzystanie z naszych serwisów internetowych bez zmiany ustawień dotyczących cookies oznacza, że będą one zamieszczone na Państwa urządzeniu końcowym. Szczegółowe informacje dotyczące stosowania cookies, w tym możliwości dokonania zmiany ustawień w zakresie cookies znajdą Państwo w naszej polityce prywatności 

![capture](https://user-images.githubusercontent.com/15007183/29221413-b040f6ec-7e8c-11e7-8d25-f93e54f1064b.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx To się mają z tymi ciasteczkami, a I don't care about cookies to blokuje oczywiście.
`##.privacy_policy_info:not(body):not(html)`
