### ISSUE TITLE
meble.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3246]
cookies 

Zamknij komunikatX
Używamy plików cookies dla celów reklamowych, statystycznych i dla wygody używania strony.

![capture](https://user-images.githubusercontent.com/15007183/29224167-2da8d712-7e97-11e7-8d5e-5cd081c64bb8.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx To też już jest w I don't care about cookies.
`###cookiePolisyInfo:not(body):not(html)`

**Comment by xxcriticxx** [comment]
@hawkeye116477 ale te ciastko i mleczko jest zajebiste musisz przyznac
