### ISSUE TITLE
wpolityce.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3248]
Filtr jest zbyt restrykcyjny i blokuje sekcję video.
BEZ ADB
![image-20170811-011](https://user-images.githubusercontent.com/9846948/29225480-beab578a-7ece-11e7-9e64-4ddbad064bf1.png)

Z ADB
![image-20170811-012](https://user-images.githubusercontent.com/9846948/29225521-f1261e8e-7ece-11e7-9ff6-62d9cf4dbffd.png)

**Comment by MajkiIT** [comment]
`@@||exs.pl^$domain=wpolityce.pl` może coś takiego?

**Comment by hawkeye116477** [comment]
Bardzo dobrze, blokuje propagandę, ale może coś takiego będzie lepsze `||wpolityce.pl^` :smile:
