### ISSUE TITLE
adblock nie blokuje reklam

### ISSUE THREAD

**Issue by crossy421** [MajkiIT/polish-ads-filter#325]
adblock is running, filters are updated, but ads, popups and other stuff like that still appears. do something wiht that

**Comment by MajkiIT** [comment]
But there? What page?

**Comment by xxcriticxx** [comment]
what website please?

**Comment by crossy421** [comment]
solar-picks.com

2016-01-25 22:14 GMT+01:00 xxcriticxx <notifications@github.com>:

**Comment by xxcriticxx** [comment]
i don't see any pop up please provide link
