### ISSUE TITLE
holidaycheck.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3250]
cookies

Serwis HolidayCheck.pl używa plików cookies w celu identyfikacji, konfiguracji, utrzymywania sesji, prowadzenia statystyk oraz obsługi emisji reklam. Korzystanie z serwisu HolidayCheck.pl oznacza wyrażenie zgody na wykorzystywanie plików cookies. Więcej szczegółów tutaj. 

![capture](https://user-images.githubusercontent.com/15007183/29227975-014d7dd0-7ea6-11e7-927d-f67c6067deb2.PNG)

**Comment by hawkeye116477** [comment]
`holidaycheck.pl###infoCloseableBoxContainer`
