### ISSUE TITLE
koncertomania.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3251]
resztki 

http://www.koncertomania.pl/newsy/100598-Rodzina-Benningtona-zdecyduje-co-z-Carpool-Karaoke.html

![capture](https://user-images.githubusercontent.com/15007183/29228093-6ff4955c-7ea6-11e7-9652-c3c3a03cad8c.PNG)

**Comment by gzenio22** [comment]
koncertomania.pl###banner-side
