### ISSUE TITLE
wspolczesna.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3252]
![capture](https://user-images.githubusercontent.com/15007183/29230742-3c9781cc-7eb2-11e7-8226-c1b5d5bc9427.PNG)

**Comment by gzenio22** [comment]
wspolczesna.pl###LinkArea\:region > .row > .hide-for-medium-down

Bardziej skrocic nie da rady chyba

**Comment by hawkeye116477** [comment]
@gzenio22 Twoja reguła nie działa w ogóle, uBlock wywala error.
`wspolczesna.pl###dfp-prawa1`

**Comment by FadeMind** [comment]
@hawkeye116477 
```
pl##.ppa-slot
```
https://github.com/MajkiIT/polish-ads-filter/issues/3254
