### ISSUE TITLE
kryminalnapolska.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3256]
![image-20170812-004](https://user-images.githubusercontent.com/9846948/29239961-104cb7c8-7f5b-11e7-88fd-0d7249e98ae4.png)

```
kryminalnapolska.pl###adnp
```

**Comment by xxcriticxx** [comment]
@FadeMind no more host file?

**Comment by xxcriticxx** [comment]
@FadeMind `kryminalnapolska.pl###adnp` dodaj sobie cookie liste to juz tam jest
