### ISSUE TITLE
wszystkotujest.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3257]
Cookies

**Comment by hawkeye116477** [comment]
`wszystkotujest.pl##DIV[style="position: fixed; left: 0px; bottom: 0px; right: 0px; z-index: 100000; cursor: pointer;"]`

**Comment by hawkeye116477** [comment]
To już było kiedyś zgłaszane i chyba trzeba zmienić tą regułę, gdyż jak widać ona nic nie daje, bo jak się zablokuje div o danym stylu, to po odświeżeniu lub wyczyszczeniu ciastek, styl się zmienia i trzeba zacząć od nowa zabawę.
`wszystkotujest.pl##body > div:nth-of-type(3)`

**Comment by FadeMind** [comment]
@blocker999 
@hawkeye116477 
Pełna formułka:
```
wszystkotujest.pl##DIV[style="background: rgb(0, 0, 0); opacity: 0.8; position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px; z-index: 100001;"]
```

**Comment by hawkeye116477** [comment]
@FadeMind Nadal widać komunikat, to tylko chowa ramkę.

**Comment by FadeMind** [comment]
Zwracam honor ;P 
Dla adguard:
```
wszystkotujest.pl##div:nth-child(25) > div:first-child
```

**Comment by hawkeye116477** [comment]
@FadeMind A dla Adguarda moja reguła nie działa? Ciekawe, z Adguard Adblocker niby działa. Ten windowsowy nie obsługuje takich reguł?

**Comment by FadeMind** [comment]
@hawkeye116477  kolego twoja reguła działa, podałem tylko składnię z ADG dla przykładu ;) 
W sumie to STATIC DIV i trudno go okiełznać ;P

**Comment by F4z** [comment]
A tutaj działa Wam ta podana reguła?
https://wszystkotujest.pl/motoryzacja/samochody-osobowe/opel/mokka/49816,opel-mokka

**Comment by hawkeye116477** [comment]
@F4z Nie działa. Więc chyba coś takiego będzie lepsze: `wszystkotujest.pl##body > div:not([id]):not([class])`

**Comment by F4z** [comment]
Tak powinno być ok, ewentualnie coś w takim stylu też powinno działać:
`wszystkotujest.pl##body > div[style^="position: fixed; left: 0px; bottom: 0px; right: 0px; z-index: 100000; cursor: pointer;"]`
Ale to już jak kto woli :)

**Comment by hawkeye116477** [comment]
Tak też działa. A można też tak: `wszystkotujest.pl##body > div:not([id]):not([class])[style*="position"][style*="fixed"]`, ale na razie dam krótszą wersję, jak będzie coś nie tak, to najwyżej się zmieni.
