### ISSUE TITLE
prostozmostu.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3258]
Obrazy dla linków po prawej stronie są blokowane `POPULARNE`
http://prostozmostu.pl/tyrada-walesy-quotdokonalem-osobiscie-ja-ja-ja-ja-rzeczy-nieprawdopodobnychquot,8932.html
![image-20170812-009](https://user-images.githubusercontent.com/9846948/29242674-53d098bc-7f91-11e7-8879-34e62476509f.png)

bez ADB

![image-20170812-008](https://user-images.githubusercontent.com/9846948/29242681-60d2d46c-7f91-11e7-8248-e274cd6f597c.png)

**Comment by hawkeye116477** [comment]
Tym razem to nie nasz polski filtr, tylko EasyList. Nie wiem po co dali regułę `/300x250/*.

`@@||prostozmostu.pl/imgcache/300x250/*$image`

**Comment by MajkiIT** [comment]
@hawkeye116477 dzięki . Dodali bo reklamy mają w adresie taki katalog.
