### ISSUE TITLE
arnicaapteka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3260]
cookies

Strona korzysta z plików cookies w sposób opisany w Polityce Prywatności. Korzystając z tego serwisu wyrażasz na to zgodę. AKCEPTUJĘ

![capture](https://user-images.githubusercontent.com/15007183/29243752-ee480370-7f74-11e7-89bd-22ea382a7d19.PNG)

**Comment by hawkeye116477** [comment]
`arnicaapteka.pl##.warning`
