### ISSUE TITLE
Typo na /adblock/

### ISSUE THREAD

**Issue by azet12** [MajkiIT/polish-ads-filter#3261]
https://www.certyficate.it/adblock/
Nie działa "homepage" dla mojego filtra, bo zamiast `https` jest `hhttps`.

A poza tym nie lepiej po prostu nazwać ten link "strona", "witryna" lub coś w tym stylu?

**Comment by hawkeye116477** [comment]
Może strona domowa byłoby lepiej.

**Comment by MajkiIT** [comment]
@azet12 poprawione

@hawkeye116477 dzięki
