### ISSUE TITLE
reserved.com

### ISSUE THREAD

**Issue by azet12** [MajkiIT/polish-ads-filter#3262]
http://www.reserved.com/pl/pl/
![cr](https://user-images.githubusercontent.com/18347726/29244435-10e2f906-7fb8-11e7-8560-c0ff93937bfe.png)

cookies

**Comment by azet12** [comment]
`www.reserved.com###cookies-container`

**Comment by hawkeye116477** [comment]
@azet12 Albo `###cookies-container:not(body):not(html)`.
