### ISSUE TITLE
mmarocks.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3263]
reklama

**Comment by hawkeye116477** [comment]
@xxcriticxx Można dać coś takiego:
```
mmarocks.pl##.wpb_text_column
mmarocks.pl##.widget_text.widget:nth-of-type(2)
mmarocks.pl##.wp-image-140885.size-full.alignnone
mmarocks.pl##.wp-image-169504.size-full.alignnone
mmarocks.pl##.widget_text.widget:nth-of-type(5)
```
Tyle, że to są reklamy ich własnego sklepu, więc nie wiem, może lepiej to zostawić.

**Comment by xxcriticxx** [comment]
decyzja jest @MajkiIT ja tu tylko sprzatam

**Comment by MajkiIT** [comment]
@hawkeye116477 no to jak do ich to zastawiamy.
@xxcriticxx uwierz mi, że masz większą władzę :P
