### ISSUE TITLE
stypendia.sejmik.kielce.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3264]
cookies

http://www.stypendia.sejmik.kielce.pl/szkoly-zawodowe/15-stypendia-dla-uczniow-szkol-zawodowych/2-o-projekcie

Ta strona korzysta z plików cookie. Więcej informacji w polityce prywatności.
Pozostając na tej stronie wyrażasz zgodę na korzystanie z plików cookie.

![capture](https://user-images.githubusercontent.com/15007183/29249536-154cceda-7fff-11e7-9249-db32a5167b3e.PNG)

**Comment by hawkeye116477** [comment]
`stypendia.sejmik.kielce.pl##.mod_pa_sci`
