### ISSUE TITLE
dziwnekomiksy.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3265]
![image-20170813-004](https://user-images.githubusercontent.com/9846948/29250169-e2b2fe2e-803d-11e7-83d2-8d98a88605b9.png)

**Comment by xxcriticxx** [comment]
@F4z lookniesz please

**Comment by F4z** [comment]
Ogólnie:
`@@||dziwnekomiksy.pl/_themes/zoltan/js/ads.js`
Dla Adguarda:
`dziwnekomiksy.pl#%#window.canRunAds = true;`
Dla uBlocka:
`dziwnekomiksy.pl##script:inject(abort-on-property-read.js, canRunAds)`
Ale moim zdaniem pierwsza reguła wystarczy, jeszcze ewentualnie można to zawsze ukryć.

**Comment by FadeMind** [comment]
@F4z  `@@||dziwnekomiksy.pl/_themes/zoltan/js/ads.js` rozwiązuje sprawę.

**Comment by hawkeye116477** [comment]
Dla uBlocka nic nie trzeba, skrypt AAK Cont to blokuje.

**Comment by F4z** [comment]
Pod warunkiem, że ktoś korzysta ze skryptu.

**Comment by xxcriticxx** [comment]
@hawkeye116477 na androidzie to dziala?

**Comment by hawkeye116477** [comment]
@xxcriticxx Tak, działa z Firefox z Violentmonkey i usi (w przypadku usi, trzeba przed zainstalowaniem AAK Cont, przestawić Greasymonkey functions always activated na Yes) i Yandex Browser z Violentmonkey. Z Violentmonkey na Firefoksie tylko problem jest taki, że skryptu nie można zaktualizować, bo nie można wejść w opcje Violentmonkey.  Natomiast z usi, kiedyś był taki problem, że po wyczyszczeniu danych Firefoksa, AAK Cont wyleciał, ale teraz nie wiem jak to jest, może już to naprawili.

**Comment by xxcriticxx** [comment]
@hawkeye116477 android jeszcze sie rozwija

**Comment by hawkeye116477** [comment]
@xxcriticxx Chyba raczej te rozszerzenia na androidowym Firefoksie się rozwijają. Ciekawe jak to będzie jak już przestawią się na tylko webextensions, czy Firefox na Andku nadal będzie miał rozszerzenia. Choć ja tam i tak wolę Yandexa, śmiga szybciej niż Firefox :smile:.
