### ISSUE TITLE
yafud.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3269]
macie dziure?

http://www.yafud.pl/31394/

![capture](https://user-images.githubusercontent.com/15007183/29251012-4d80bae8-801b-11e7-8787-1b782b38cc77.PNG)

**Comment by gzenio22** [comment]
Tak

yafud.pl##.commentsbox > center

**Comment by MajkiIT** [comment]
`yafud.pl##center`

**Comment by F4z** [comment]
Samo center za dużo zablokuje.
Może po prostu tak?
`yafud.pl##.adsbygoogle`
