### ISSUE TITLE
www.kafeteria.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#327]
reklama

lotto prawa strona

**Comment by MajkiIT** [comment]
Nie widzę takiej reklamy

**Comment by xxcriticxx** [comment]
ja naprawde mam cos popierdolone z filtrami na jedej maszynie jest reklama na drugiej nie mam

**Comment by xxcriticxx** [comment]
http://kafeteria.pl/ziu/zdrowie-okolic-intymnych-jak-wybierac-plyny-do-higieny-intymnej-a_10136

adblock detected dodaj to listy wp.pl domains

**Comment by xxcriticxx** [comment]
http://kafeteria.tv/Kochani-rodzice-przyslijcie-pieniadze-Co-zrobic-gd-eYIWrRIcHSt

a nadej wykrywa i dziala poprawnie

**Comment by xxcriticxx** [comment]
http://kafeteria.pl/seks-i-zwiazki/kamasutra-dla-chorych-na-raka-a_9898

tutaj znowu wykrywa adblock

**Comment by MajkiIT** [comment]
https://github.com/reek/anti-adblock-killer/issues/979
