### ISSUE TITLE
poradnikzdrowie.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3270]
http://www.poradnikzdrowie.pl/zdrowie/laryngologia/angina-przyczyny-objawy-leczenie-w-pytaniach-i-odpowiedziach_34431.html

![capture](https://user-images.githubusercontent.com/15007183/29251048-487be04e-801c-11e7-8239-4fb7580403ce.PNG)

**Comment by gzenio22** [comment]
poradnikzdrowie.pl###art_body > .rw_intext.big_pic

**Comment by MajkiIT** [comment]
@gzenio22 niestety pod tym jest player

```
@@||cdn.muratordom.smcloud.net/t/advert.js$script,domain=www.poradnikzdrowie.pl
@@||sascdn.com^$object-subrequest,script,domain=poradnikzdrowie.pl
@@||smartadserver.com^$script,domain=poradnikzdrowie.pl
```
