### ISSUE TITLE
pogonszczecin.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3279]
http://pogonszczecin.pl/newsy/20170810134653

![capture](https://user-images.githubusercontent.com/15007183/29251543-765314b2-8024-11e7-950f-4c6ed4206817.PNG)

**Comment by gzenio22** [comment]
pogonszczecin.pl##.ng-scope.adv > .ng-scope.row > .col-xs-12

**Comment by hawkeye116477** [comment]
Albo `pogonszczecin.pl##.adv`

**Comment by MajkiIT** [comment]
`pl##.adv`
