### ISSUE TITLE
www.gry-online.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#328]
reklama jak strona pierwszy raz sie otworzy

**Comment by MajkiIT** [comment]
Nie widzę niczego takiego. Jakiś zrzut?

**Comment by xxcriticxx** [comment]
pracujie na kilku innych komputerach nieiwm dla czego od czasu do czasu widze reklamy 

hyba musze filtry updatowac wszedzie zanim szukam stron
