### ISSUE TITLE
www.zalukaj.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#329]
do guzika play jest podlonczona jakas reklaam 

http://zalukaj.tv/zalukaj-film/20821/remedium_the_treatment_de_behandeling_2014_.html

**Comment by xxcriticxx** [comment]
trzeba cos poprawic player w ogole sie nie pokazuje

**Comment by MajkiIT** [comment]
bo tam nie ma playera... pod adresem Ogladaj na vShare.io jest link

**Comment by xxcriticxx** [comment]
zawsze byl player na stronie zalukaj.tv tylko od jakiegos czasu reklama byla podpienta pod play
