### ISSUE TITLE
dekoder.ml

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3291]
looks dead ok to remove

**Comment by hawkeye116477** [comment]
Po wyłączeniu uBlocka próbuje przekierować na jakieś dziadostwo.

**Comment by hawkeye116477** [comment]
Tam tylko są przekierowania na jakieś dziadostwa, ale uBlock to blokuje.

**Comment by MajkiIT** [comment]
wyłącz ublocka i zrób redirect :P
