### ISSUE TITLE
advatus.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3307]
cookies

Ta strona używa cookies. Dowiedz się więcej o celu ich używania i zastosowania w przeglądarce.
Korzystając ze strony wyrażasz zgodę na używanie cookies, zgodnie z aktualnymi ustawieniami przeglądarki.
nie pokazuj ponownie

![capture](https://user-images.githubusercontent.com/15007183/29288484-edd62adc-8106-11e7-9b72-af091471431d.PNG)

**Comment by hawkeye116477** [comment]
`advatus.pl###myModal`
