### ISSUE TITLE
tylkodywan.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3308]
cookies

Ta strona używa cookies. Dowiedz się więcej o celu ich używania i zastosowania w przeglądarce.
Korzystając ze strony wyrażasz zgodę na używanie cookies, zgodnie z aktualnymi ustawieniami przeglądarki. 

![capture](https://user-images.githubusercontent.com/15007183/29288627-6b5fa0b4-8107-11e7-96fc-a3c2dc0caace.PNG)

**Comment by hawkeye116477** [comment]
`tylkodywan.pl##.myModal-box`
