### ISSUE TITLE
www.biztok.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#331]
reklamy volvo, orange

http://www.biztok.pl/lifestyle/tego-w-polsce-nie-kupisz-czyli-25-marek-niedostepnych-w-naszych-sklepach_a22825

http://ptefjzciey.wp.pl/Uk0vY2xpY2tfbHguYWRzL0JpenRvay5wbC9hcnR5a3VsLmh0bWwvTDIyLzEwNzk0NTI5NjUveDA2L09hc0RlZmF1bHQvOTMzNjhfMjA5NjM0X1ZvbHZvX3d5cHJ6ZWRhel9zdHkxNl9CSVpUT0svOTMzNjhfMjA5NjM0X3Y0MC5odG1sLzQ3NGM3NjYyNGI2YzU5NWE1NDZlMzA0MTQzNDc1ODMyP1BXQV9hZGJkPTEmX1JNX1JFRElSXz1odHRwOi8vYnMuc2VydmluZy1zeXMuY29tL0J1cnN0aW5nUGlwZS9hZFNlcnZlci5icz9jbj10ZiZjPTIwJm1jPWNsaWNrJnBsaT0xNjI2Nzc0MyZQbHVJRD0wJm9yZD0xMDc5NDUyOTY1

http://ptefjzciey.wp.pl/Uk0vY2xpY2tfbHguYWRzL0JpenRvay5wbC9hcnR5a3VsLmh0bWwvTDIyLzEzOTg1NTI0NDEveDAzL09hc0RlZmF1bHQvOTIyMDlfMjA3MTQ0X09yYW5nZV9TdXBlcm5vdmFfQ1BDX3dpZGVib2FyZF9DVFIvMjA3MTQ0MS5odG1sLzQ3NGM3NjYyNGI2YzU5NWE1NDZlMzA0MTQzNDc1ODMyP3NlZ249MyZzdmxlPTEuMDAmc3ByZT0wJlBXQV9hZGJkPTEmX1JNX1JFRElSXz1odHRwOi8vdC5xc2VydnouY29tL2NsLmFzcHg/dGM9NDViYzk4N2UxNjNlMmQ5ODAwYWI0YzdmNDVhMTAyYzAmdXJsPWh0dHA6Ly93d3cub3JhbmdlLnBsL2tpZCw0MDAyMDA5NTAxLGlkLDQwMDIyMzU1NjUsdGl0bGUsTmVvc3RyYWRhLGFydGljbGUuaHRtbCNTdXBlcm5vdmE=

http://ptefjzciey.wp.pl/Uk0vY2xpY2tfbHguYWRzL0JpenRvay5wbC9hcnR5a3VsLmh0bWwvTDIyLzg5NjMyMzI4NC94MzcvT2FzRGVmYXVsdC85MjIwOV8yMDcxNDdfT3JhbmdlX1N1cGVybm92YV9DUENfZmxvYXRfaGFsZi1DVFIvMjA3MTQ3My5odG1sLzQ3NGM3NjYyNGI2YzU5NWE1NDZlMzA0MTQzNDc1ODMyP3NlZ249MyZzdmxlPTEuMDAmc3ByZT0wJlBXQV9hZGJkPTEmX1JNX1JFRElSXz1odHRwOi8vdC5xc2VydnouY29tL2NsLmFzcHg/dGM9ZGJmNmM2Mzg3YTllZGU2NWYwMGVjNGZhYWM3YTBhZjAmdXJsPWh0dHA6Ly93d3cub3JhbmdlLnBsL2tpZCw0MDAyMDA5NTAxLGlkLDQwMDIyMzU1NjUsdGl0bGUsTmVvc3RyYWRhLGFydGljbGUuaHRtbCNTdXBlcm5vdmE=

**Comment by xxcriticxx** [comment]
bon prix it's me! reklama

**Comment by xxcriticxx** [comment]
tchibo reklama

**Comment by MajkiIT** [comment]
masz aktualne filtry? Maciek

**Comment by xxcriticxx** [comment]
v.2016012602 aktualizacja: wt, 26 stycznia 2016, 13:15:00

**Comment by MajkiIT** [comment]
2016012802 :P

**Comment by xxcriticxx** [comment]
wkurwia mnie ten ublock mam ustatwione na auto update a mam filtry 2 dni stare

**Comment by MajkiIT** [comment]
może za często wydaję zmiany. Nie denerwuj się :+1:

**Comment by xxcriticxx** [comment]
a jusz tak sie cieszylem ze cos nowego znalazlem

**Comment by MajkiIT** [comment]
Dzisiaj koło południa była akcja, więc wydałem nową wersję. Ok next time będę się ociągał.
