### ISSUE TITLE
netweber.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3310]
cookies

Ta strona używa plików cookies do poprawnego działania.
Korzystając ze strony wyrażasz zgodę na używanie cookies, zgodnie z aktualnymi ustawieniami przeglądarki. Dowiedz się więcej o celu ich używania i zmianie ustawień cookies w przeglądarce.

![capture](https://user-images.githubusercontent.com/15007183/29292889-e2f6c4a4-8116-11e7-857d-247196535807.PNG)

**Comment by gzenio22** [comment]
netweber.pl##.flash-info
