### ISSUE TITLE
allegro.pl - problem z nth-of-type na lazyloaded

### ISSUE THREAD

**Issue by maciejtarmas** [MajkiIT/polish-ads-filter#3315]
Problem dotyczy poniższej reguły:

`allegro.pl##.lazyloaded:nth-of-type(6) > .opbox-sheet-wrapper`

Wywala w kosmos div-a z polecanymi kategoriami z zakładki <a href="https://allegro.pl/dzial/firma-i-uslugi">"Firma i usługi"</a>, a zamysł na którymś etapie był pewnie inny.

Moim zdaniem nie da się blokować za pomocą nth-of-type śmieci na Allegro, bo występują w różnych miejscach w różnej kolejności.

Ja w <a href="https://alleblock.pl">AlleBlock</a> blokuję wszystko konkretnie po data-box-name. Też pierwotnie chciałem wykorzystać nth-of-type czy podobne, ale nie dało rady.

<img width="786" alt="screen shot 2017-08-15 at 20 53 28" src="https://user-images.githubusercontent.com/3435387/29331426-af4ffdfa-81fc-11e7-9af8-815c15f24d1d.png">

**Comment by hawkeye116477** [comment]
@MajkiIT Obrazy nad linkami zostały celowo zablokowane? Wg. mnie powinny zostać odblokowane, gdyż to są promocje sklepu własnego alledrogo
![screenshot_20170815_212155](https://user-images.githubusercontent.com/19818572/29332390-28396d66-8200-11e7-90e9-e70db72c1be3.png)

**Comment by MajkiIT** [comment]
Możliwe, że to była moja radosna twórczość. Zaraz usunę.
