### ISSUE TITLE
allegro.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3316]
@MajkiIT Obrazy nad linkami zostały celowo zablokowane? Wg. mnie powinny zostać odblokowane, gdyż to są promocje sklepu własnego alledrogo. No chyba, że to nie są opłacalne promocje, więc reguła została dodana, by uchronić ludzi od przepłacania, to wtedy może lepiej jeszcze dodatkowo schować linki: `allegro.pl##.carousel-indicators` :smiley:.
![screenshot_20170815_212155](https://user-images.githubusercontent.com/19818572/29332390-28396d66-8200-11e7-90e9-e70db72c1be3.png)

**Comment by MajkiIT** [comment]
Dzięki, no to zaraz usuniemy.
