### ISSUE TITLE
Ciekawostka 

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3320]
http://antyweb.pl/addaps-nowa-przegladarka-internetowa-inna-niz-wszystkie/

Jak ktos ma czas i ochote niech przebada cos nowego :D

**Comment by hawkeye116477** [comment]
@gzenio22 
Ta i wszystko przechodzi przez wujaszka Google. Do tego te elementy społecznościowe.
Dziękuję, postoję, Waterfox i Vivaldi lepszy :smile:.
