### ISSUE TITLE
pl.pinterest.com

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3321]
https://pl.pinterest.com/explore/tatua%C5%BCe-dla-m%C4%99%C5%BCczyzn/

Też macie tło i wymuszenie rejestracji ?

`pl.pinterest.com##DIV[style="background: rgba(0, 0, 0, 0.75) none repeat scroll 0% 0%; transition: height 0.5s cubic-bezier(0.26, 0.87, 0.74, 0.93) 0s; backface-visibility: hidden; bottom: 0px; color: rgb(255, 255, 255); height: 100%; position: fixed; width: 100%;"]
`

**Comment by hawkeye116477** [comment]
@MajkiIT Tak
