### ISSUE TITLE
nuda dzisaj

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3323]

**Comment by MajkiIT** [comment]
:P hmmm przepraszamy @xxcriticxx

**Comment by MajkiIT** [comment]
@xxcriticxx Nie ma nudy. Przyszła paczka z elektrody :package:

**Comment by xxcriticxx** [comment]
@MajkiIT photo plz

**Comment by MajkiIT** [comment]
Jutro zrobię, bo ją odbiorę dopiero :P

**Comment by xxcriticxx** [comment]
okie dokie

**Comment by MajkiIT** [comment]
![img_0930](https://user-images.githubusercontent.com/11302675/29486720-25d3917e-84ed-11e7-9c1e-32f9d515b2ea.JPG)

**Comment by MajkiIT** [comment]
@gulson Dzięki wielkie :D Jesteś wielki

**Comment by xxcriticxx** [comment]
zapalniczka?

**Comment by MajkiIT** [comment]
tak. Chcesz?

**Comment by hawkeye116477** [comment]
@xxcriticxx się nudzi, to mam tu dla niego coś do poczytania i wypowiedzenia się w tej sprawie -> https://github.com/azet12/PopupBlocker/issues/68

**Comment by xxcriticxx** [comment]
@MajkiIT wysylanie tego do usa niema sensu

@hawkeye116477 lol numeru 68
