### ISSUE TITLE
wikar.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3326]
cookies 

Ta strona korzysta z cookies OK, rozumiem Więcej informacji

![capture](https://user-images.githubusercontent.com/15007183/29475705-f3214fdc-842e-11e7-9014-19bbab088d49.PNG)

**Comment by hawkeye116477** [comment]
`wikar.com.pl##.popupContent`

**Comment by gzenio22** [comment]
Cookies

wikar.com.pl##.popupContent

Reklama

##.slider   

@hawkeye116477 przesadzilem?

**Comment by hawkeye116477** [comment]
@gzenio22 Tak, ta tzw. reklama to oferty promocyjne w ich własnym sklepie, więc nie blokujemy.
