### ISSUE TITLE
mistrzowie.org

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3328]
box po cookies 

![capture](https://user-images.githubusercontent.com/15007183/29476103-79eb9508-8430-11e7-94bb-647916f6f6ee.PNG)

**Comment by hawkeye116477** [comment]
`mistrzowie.org##div[style="position: fixed; left:0; right:0; bottom:0; height:40px; background-color:#eee; border-top: 1px solid black; z-index:1000; overflow: auto"]`
