### ISSUE TITLE
halogorlice.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3330]
![capture](https://user-images.githubusercontent.com/15007183/29478572-6f29f578-843b-11e7-85b1-6cbd0c498398.PNG)

**Comment by gzenio22** [comment]
halogorlice.info######Mod226 > .module-inner
halogorlice.info###Mod459
halogorlice.info###Mod488
halogorlice.info###Mod311

**Comment by hawkeye116477** [comment]
@gzenio22 Tylko pierwsza reguła działa, reszta nie.

Na stronę główną: `halogorlice.info##.center.module`
Na pozostałe strony:
```
halogorlice.info##hr
!halogorlice.info##.bannergroup
halogorlice.info##.itemFullText > .custom
```
