### ISSUE TITLE
chojnow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3332]
cookies + dziura 

![capture](https://user-images.githubusercontent.com/15007183/29488168-69d059b2-84d3-11e7-9057-5bdc3d9d7aa1.PNG)

**Comment by gzenio22** [comment]
Ja zeby cookie ukryc musial bym wywalic cala wyszukiwarke XD a dziury nie wiem jak sie lata

**Comment by MajkiIT** [comment]
@F4z zerkniesz w wolnej chwili ?

**Comment by hawkeye116477** [comment]
@gzenio22 Trzeba pobawić się stylami, by schować cookies: `chojnow.pl##div#belka:style(font-size:0px!important;)` i gitara gra.

**Comment by hawkeye116477** [comment]
@MajkiIT Takie coś może być ?
```
chojnow.pl###logo_box
chojnow.pl##div#top:style(height: 37px!important;)
```
A co do ciastek, to nie wiem czy lepiej je nie zostawić, bo to w sumie static.

**Comment by xxcriticxx** [comment]
razem z google mozna schowac

`chojnow.pl###belka-contener > div:nth-of-type(2)`

**Comment by gzenio22** [comment]
@xxcriticxx Ja to samo mialem dla tego tu nie wstawialem bo wyszukiwarke to zabiera a nie wiedzialem czy powinno jak chcecie :)

**Comment by xxcriticxx** [comment]
@hawkeye116477 maybe this `chojnow.pl###top`

**Comment by hawkeye116477** [comment]
@xxcriticxx To schowa menu, więc moje 2 reguły są lepsze.

**Comment by xxcriticxx** [comment]
ok sorry nawet nie zauwazylem

**Comment by hawkeye116477** [comment]
@xxcriticxx Ok. Tylko nie wiem czy z Adblockiem to zadziała, ale chyba dla Adblocka nie da się coś innego zrobić, by poprawnie działało, można tylko schować menu twoją regułą, a menu raczej komuś się przyda, także trudno, ci co używają Adblocka będą musieli się z tym pogodzić :smiley:.
