### ISSUE TITLE
tvsudecka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3333]
http://www.tvsudecka.pl/wiadomosci/63599,bmw-kontra-bmw-w-bielawie

![capture](https://user-images.githubusercontent.com/15007183/29488216-5628013e-84d4-11e7-8ae1-30a09b679c01.PNG)

**Comment by gzenio22** [comment]
tvsudecka.pl##.content > div:nth-of-type(2)
