### ISSUE TITLE
kursyuniversum.ksiezyc.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3338]
cookies

![capture](https://user-images.githubusercontent.com/15007183/29488397-2baf1880-84d8-11e7-9912-3a0086c25dca.PNG)

**Comment by gzenio22** [comment]
kursyuniversum.ksiezyc.pl##img[src="IMG/cookiess.png"]

Dziwna regula zerknie ktos? Niby hula no ale takich krzaczkow jeszcze nie widzialem

**Comment by MajkiIT** [comment]
`kursyuniversum.ksiezyc.pl##a[href="cookies.php"]`
