### ISSUE TITLE
czekoladacortez.pl/pl/

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3340]
@MajkiIT moze tutaj jakies sample dostaniesz :)

cookies

![capture](https://user-images.githubusercontent.com/15007183/29488514-b793a116-84da-11e7-9385-ad2584c8eb56.PNG)

**Comment by gzenio22** [comment]
u mnie nie mam tego

**Comment by MajkiIT** [comment]
`czekoladacortez.pl##.activebar-container`

**Comment by MajkiIT** [comment]
@xxcriticxx no smakowite
