### ISSUE TITLE
itvpiaseczno.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3341]
![capture](https://user-images.githubusercontent.com/15007183/29488884-f9cc008a-84e1-11e7-9e41-580af08131c8.PNG)

**Comment by gzenio22** [comment]
itvpiaseczno.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
