### ISSUE TITLE
nolesnica.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3342]
![capture](https://user-images.githubusercontent.com/15007183/29488900-53bb2e2c-84e2-11e7-8262-96c5fccf474d.PNG)

**Comment by gzenio22** [comment]
nolesnica.pl###TXhkUvZljBCga

Nie to samo co pietro nizej? :P

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
