### ISSUE TITLE
imokotow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3343]
![capture](https://user-images.githubusercontent.com/15007183/29488913-80a76fea-84e2-11e7-8790-64907ebcaf13.PNG)

**Comment by gzenio22** [comment]
imokotow.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
