### ISSUE TITLE
lipno-cli.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3344]
![capture](https://user-images.githubusercontent.com/15007183/29488925-d304ef2e-84e2-11e7-9c28-8cd3ef3a9498.PNG)

**Comment by gzenio22** [comment]
lipno-cli.pl###TXhkUvZljBCga

trzeba to chyba bedzie polaczyc jakos w kilka domen

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
