### ISSUE TITLE
szczecinek.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3345]
![capture](https://user-images.githubusercontent.com/15007183/29488933-05b63a54-84e3-11e7-8188-d451c57dc673.PNG)

**Comment by gzenio22** [comment]
szczecinek.com###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
