### ISSUE TITLE
iotwock.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3346]
![capture](https://user-images.githubusercontent.com/15007183/29488952-4b33f710-84e3-11e7-91d7-0956df3955a8.PNG)

**Comment by gzenio22** [comment]
szczecinek.com###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
