### ISSUE TITLE
golub-cgd.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3347]
![capture](https://user-images.githubusercontent.com/15007183/29488964-751e93b4-84e3-11e7-9b57-1cb4a9a485e7.PNG)

**Comment by gzenio22** [comment]
golub-cgd.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
