### ISSUE TITLE
rypin-cry.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3348]
![capture](https://user-images.githubusercontent.com/15007183/29488975-a263ede2-84e3-11e7-89cd-74588aea4c10.PNG)

**Comment by gzenio22** [comment]
rypin-cry.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
