### ISSUE TITLE
infosiedlce.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3349]
![capture](https://user-images.githubusercontent.com/15007183/29488984-d5330cb2-84e3-11e7-9d24-99a23eebb4e1.PNG)

**Comment by gzenio22** [comment]
infosiedlce.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
