### ISSUE TITLE
wabrzezno-cwa.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3350]
![capture](https://user-images.githubusercontent.com/15007183/29488993-16d625dc-84e4-11e7-936b-d7476aad3ff5.PNG)

**Comment by gzenio22** [comment]
wabrzezno-cwa.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
