### ISSUE TITLE
ciechanowinaczej.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3351]
![capture](https://user-images.githubusercontent.com/15007183/29488997-381aac86-84e4-11e7-8925-44972817ce21.PNG)

**Comment by gzenio22** [comment]
ciechanowinaczej.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
