### ISSUE TITLE
wterenie.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3352]
![capture](https://user-images.githubusercontent.com/15007183/29488999-581d8a12-84e4-11e7-9365-ff06bfb8a657.PNG)

**Comment by gzenio22** [comment]
wterenie.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
