### ISSUE TITLE
ibielsk.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3353]
![capture](https://user-images.githubusercontent.com/15007183/29489006-7da7db7a-84e4-11e7-8022-12e5f6cebf52.PNG)

**Comment by gzenio22** [comment]
ibielsk.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
