### ISSUE TITLE
e-wyszogrod.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3354]
![capture](https://user-images.githubusercontent.com/15007183/29489018-e9e94e0e-84e4-11e7-9274-8d41da54fb61.PNG)

**Comment by gzenio22** [comment]
e-wyszogrod.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
