### ISSUE TITLE
ikampinos.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3355]
![capture](https://user-images.githubusercontent.com/15007183/29489033-3273fcc8-84e5-11e7-89e5-0d42b2df6080.PNG)

**Comment by gzenio22** [comment]
ikampinos.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
