### ISSUE TITLE
iskierniewice.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3356]
![capture](https://user-images.githubusercontent.com/15007183/29489058-807cdf7a-84e5-11e7-81f2-25f6d67f3349.PNG)

**Comment by gzenio22** [comment]
iskierniewice.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
