### ISSUE TITLE
ikrakow.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3357]
![capture](https://user-images.githubusercontent.com/15007183/29489062-ad0a6c92-84e5-11e7-9d45-854f95739ee3.PNG)

**Comment by gzenio22** [comment]
ikrakow.info###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
