### ISSUE TITLE
iminsk.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3358]
![capture](https://user-images.githubusercontent.com/15007183/29489077-e70cee88-84e5-11e7-8964-ea24767149bd.PNG)

**Comment by gzenio22** [comment]
iminsk.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
