### ISSUE TITLE
irembertow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3359]
![capture](https://user-images.githubusercontent.com/15007183/29489089-370e4698-84e6-11e7-9632-864d8cecd390.PNG)

**Comment by gzenio22** [comment]
irembertow.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
