### ISSUE TITLE
www.linuxiarze.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#336]
adblock?
http://linuxiarze.pl/polecane/

Prawdopodobnie używasz oprogramowania AdBlock.
Zauważyliśmy, że odwiedziłeś/aś nasz serwis 2 razy.

Cieszymy się, że znajdujesz w nim użyteczne treści, ale jesteśmy również smutni, ponieważ blokujesz reklamy na naszej witrynie.

Bez przychodu z reklam nie będziemy w stanie w dalszym ciągu bezpłatnie dostarczać wysokiej jakości treści. Jeśli korzystasz z naszych treści, prosimy - rozważ wsparcie nas przez którykolwiek z następujących sposobów:

    Wyłącz oprogramowanie AdBlock dla naszej witryny (patrz obrazek po prawej stronie) - zyski z reklam generujemy tylko wtedy, gdy ktoś kliknie w reklamy wyświetlane na naszej stronie.
    Przekaż małą (lub dużą) darowiznę.
    Zamieść link do nas lub napisz o nas na swoim blogu.

Z góry bardzo dziękujemy za wsparcie i zrozumienie!

Click here to close
You will no longer receive this message after 999999 visit(s) (cookies required).

Powered by Anti-AdBlock

**Comment by MajkiIT** [comment]
https://github.com/reek/anti-adblock-killer/issues/991
