### ISSUE TITLE
egorzow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3360]
![capture](https://user-images.githubusercontent.com/15007183/29489092-548df66e-84e6-11e7-9e00-a6f2551169d6.PNG)

**Comment by gzenio22** [comment]
egorzow.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3362
