### ISSUE TITLE
splendo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3361]
![capture](https://user-images.githubusercontent.com/15007183/29489098-7860dee4-84e6-11e7-8fb2-91ab3209ddcc.PNG)

**Comment by gzenio22** [comment]
splendo.pl###TXhkUvZljBCga

**Comment by MajkiIT** [comment]
To samo co https://github.com/MajkiIT/polish-ads-filter/issues/3362
