### ISSUE TITLE
portel.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3367]
![screenshot_20170821_114653](https://user-images.githubusercontent.com/19818572/29513724-77c831c2-8666-11e7-97aa-f1632fddc2f3.png)

@MajkiIT uBlock Protector niby już to naprawił, ale jeśli ktoś ma AAK Cont albo nie ma ani jednego albo drugiego, to będzie miał problem. A rozwiązanie jest proste: `@@||portel.pl/js/adsrv.js`. W skrypcie adsrv.js nie ma reklam, jest tylko pułapka, która załącza anti-adblock, więc można spokojnie odblokować to.

**Comment by xxcriticxx** [comment]
@hawkeye116477 u pingwina jest kilka innych stron pl może je tutaj przerzucić ?

**Comment by hawkeye116477** [comment]
@xxcriticxx Może, zależy co. Choć chyba raczej to pytanie powinno być do @MajkiIT, on tutaj jest szefem, a nie ja :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 ty jesteś directorem działu do ciastek!

Może ten przeglądnąć sportowy?

**Comment by MajkiIT** [comment]
@hawkeye116477 dodałem. Dzięki. 
No właśnie nie wiem gdzie to teraz pchać czy do Pingwina czy do AAK-Cont?

**Comment by xxcriticxx** [comment]
@MajkiIT na nasza liste nie kazdy używa pingwina. Teraz jest więcej miejsca po wielkim sprzątaniu!

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale tam nie ma ciastek. A z anty-adblockiem to raczej nie będzie u nich tak łatwo. To raczej nie amatorzy jak portel.pl, to profesjonaliści :smiley:.

**Comment by xxcriticxx** [comment]
Jak da się radę to się doda zawsze jest pingwin
