### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3368]
![image-20170821-008](https://user-images.githubusercontent.com/9846948/29525927-7ea828c0-8694-11e7-8754-7a711a517cac.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by gzenio22** [comment]
Elektroda mhm @MajkiIT co robimy?

**Comment by hawkeye116477** [comment]
Skrypt AAK Cont to blokuje:
```
if (a.domCmp(["elektroda.pl"])) {
    a.filter("setTimeout", a.matchMethod.string, "adBlockTest.offsetHeight");
}
```

A reguła dla Adguarda, to chyba już raczej zadanie dla @F4z.

**Comment by xxcriticxx** [comment]
nic nie robimy @MajkiIT  sie dogadal z wlascicielem strony

**Comment by hawkeye116477** [comment]
@xxcriticxx To może w ogóle usuniemy reguły na elektrode i odblokujemy reklamy :smiley:?
Żartowniś. 
Reguły na ukrycie anti-adblocka elektrody już są w filtrze, ale widać coś zmienili i teraz się znowu wyświetla. AAK Cont i uBlock Protector to blokują. Jeśli jednak ktoś nie ma ani skryptu ani rozszerzenia, to raczej to `elektroda.pl##script:inject(abort-on-property-write.js, adBlockTest)` powinno pomóc. Nie wiem tylko czy z Adguardem to działa. @FadeMind sprawdź czy działa.

**Comment by FadeMind** [comment]
`elektroda.pl##script:inject(abort-on-property-write.js, adBlockTest)` nie ma poprawnej składni dla Adguard i nie można jej dodać.

**Comment by hawkeye116477** [comment]
@FadeMind Ok, więc czekamy na mistrza @F4z / @AdamWr.

**Comment by xxcriticxx** [comment]
poczekamy na @MajkiIT i sie dowiemy

**Comment by F4z** [comment]
Dla Adguarda może być coś takiego:
`elektroda.pl#%#var _st = window.setTimeout; window.setTimeout = function(a, b) { if(!/adBlockTest\.remove/.test(a)){ _st(a,b);}};`

Ta reguła `elektroda.pl##script:inject(abort-on-property-write.js, adBlockTest)` psuje trochę stronę, bo jak klikniesz w "szukaj", to nie da się zamknąć, tak powinno być lepiej:
`elektroda.pl##script:inject(setTimeout-defuser.js, adBlockTest.remove)`

Dla Adblocka może być tak:
```
elektroda.pl#@#.adsbox
elektroda.pl#@#.ads
elektroda.pl#@#.adsframe
elektroda.pl#@#.ad
elektroda.pl#@#.ads-box
elektroda.pl#@#.ads-frame
```

**Comment by hawkeye116477** [comment]
To chyba 3 opcja jest najlepsza, bo zadziała dla wszystkich adblokerów.

**Comment by MajkiIT** [comment]
Dodałem. Właściciel chciał aby zostawić 4 banerki i nie psuć strony.
