### ISSUE TITLE
Pytanie do ekspertów - znikające video na stronach

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#3369]
Wejdźcie w link poniżej i powiedzcie mi czy u Was też ten filmik z włączonym UBlockiem znika ? 
https://www.o2.pl/short/hiszpanskiemu-plywakowi-odmowiono-minuty-ciszy-po-zamachu-zobacz-co-zrobil-6157530797786753s

**Comment by FadeMind** [comment]
Jakie masz aktywne filtry?

**Comment by MajkiIT** [comment]
@HateAds U mnie na razie jest ok.

**Comment by HateAds** [comment]
@FadeMind 
![image](https://user-images.githubusercontent.com/29756590/29533629-ffe35c98-86b2-11e7-9413-d7e599feebf0.png)

![image](https://user-images.githubusercontent.com/29756590/29533647-132eb518-86b3-11e7-952c-1d9db2597128.png)

**Comment by HateAds** [comment]
@MajkiIT A jak wygląda sprawa jak odświeżysz stronę ? 
U mnie coś takiego...
![image](https://user-images.githubusercontent.com/29756590/29533697-55760386-86b3-11e7-85fe-fca46c381726.png)

**Comment by FadeMind** [comment]
U mnie jest OK (Adguard)

**Comment by MajkiIT** [comment]
@HateAds U mnie na 2 kompach jest ok. Tylko mam 23 zablokowane elementy a ty 41. Nie ma czegoś wpisane w moje filtry?

**Comment by HateAds** [comment]
@MajkiIT Pusto tam mam, zainstaluje od nowa UBlocka i zobaczę czy pomoże.

**Comment by hawkeye116477** [comment]
@HateAds Też mam pusto jak jest włączony uBlock Protector. Po wyłączeniu Protectora filmik się pojawia.

**Comment by HateAds** [comment]
@hawkeye116477 No to mamy winowajce, pingwin będzie musiał naprawiać.

**Comment by HateAds** [comment]
@MajkiIT Możesz zamknąć temat jak coś, później do pingwina napisze.

**Comment by HateAds** [comment]
@hawkeye116477 Miałem już pisać do pingwina, ale problemem może nie być tylko jego skrypt. Zobacz na tą stronę czy video się pojawia U Ciebie ? 
http://skijumping.pl/wiadomosci/23500/Adam-Malysz-Pomysl-Pucharu-Beskidow-spodobal-sie-FIS/

**Comment by FadeMind** [comment]
@HateAds  Potwierdzam. Film z YT nie jest widoczny przy aktywnej ochrone ADG. Podejrzewam, że to kwestia polskich filtrów. Dziwne.

**Comment by HateAds** [comment]
@FadeMind Ok dzięki za info. @MajkiIT chyba jednak będzie trzeba otworzyć temat ponownie.

**Comment by hawkeye116477** [comment]
@HateAds W tym przypadku to zgadza się, ta reguła jest do zmiany: `skijumping.pl##.news > center`. Ale na o2 to pingwin musi naprawić.

**Comment by HateAds** [comment]
@hawkeye116477 Dzięki, zaraz napiszę do pingwina żeby naprawił.

**Comment by HateAds** [comment]
@MajkiIT  Dodasz później te reguły które podał hawke ?

**Comment by MajkiIT** [comment]
@HateAds Już dodaje
