### ISSUE TITLE
filtry mi sie nie sciagaja

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#337]
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it): 0 used out of 0
 Adblock & uBlock polish cookies filters‎ : 0 used out of 0out of date

**Comment by xxcriticxx** [comment]
hyba naprawilem 
na github sa tylko czwartkowe
v.2016012802 aktualizacja: czw, 28 stycznia 2016, 20:45:00

**Comment by MajkiIT** [comment]
strona https://www.certyficate.it/adblock/adblock.txt ma błąd certyfikatu ssl. Jutro będzie nowy, kiedyś ssl dawał mi Cloudflare, teraz z niego uciekłem.

**Comment by xxcriticxx** [comment]
naprawilem certyfikat ale dalej widze filtry tylko z czwartku

**Comment by MajkiIT** [comment]
Bo ostatnia wersja jest z czwartku...

**Comment by xxcriticxx** [comment]
ok dzieki za info
