### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3370]
Dziura po komunikacie o polityce wujka: `youtube.com##div#masthead-positioner-height-offset:style(height: 80px!important;)`

![screenshot_20170821_224004](https://user-images.githubusercontent.com/19818572/29537366-bf8bcf4a-86c1-11e7-8269-83685621689a.png)

**Comment by FadeMind** [comment]
![image-20170821-011](https://user-images.githubusercontent.com/9846948/29537687-ee143720-86c2-11e7-8300-138f8aefe413.png)

**Comment by xxcriticxx** [comment]
ciocia google
