### ISSUE TITLE
ambit.gda.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3372]
![capture](https://user-images.githubusercontent.com/15007183/29539320-5828fab4-8697-11e7-918d-eb0b89bd905f.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx To jest static, także nie blokujemy, a nawet nie da rady tego schować bez chowania stopki.

**Comment by xxcriticxx** [comment]
@hawkeye116477 ok zamykamy
