### ISSUE TITLE
instalki.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3373]
`http://www.instalki.pl/aktualnosci/software/27675-android-oreo-lista-smartfonow.html`

**BEFORE**

![image-20170822-001](https://user-images.githubusercontent.com/9846948/29559036-3d75000e-872e-11e7-9b29-e9e544f91561.png)

**FIX**
```
instalki.pl##.banner_article_center
```

**AFTER**

![image-20170822-002](https://user-images.githubusercontent.com/9846948/29559066-564d2d04-872e-11e7-9e0d-bda334e976fa.png)

**Comment by MajkiIT** [comment]
@FadeMind Dzięki
