### ISSUE TITLE
wcograc.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3374]
Cos zeżarło tapetę która nie była klikalna i obrazki z gier na gorze strony 

![screenshot_1](https://user-images.githubusercontent.com/21177361/29564168-f02e2664-8740-11e7-9f1f-4021c84f5d84.png)

**Comment by MajkiIT** [comment]
Jak wyłączysz blokera nie masz tak samo?

**Comment by MajkiIT** [comment]
Już wiem `https://promocjagier.pl/img/3435/960x300/1.jpeg`

Ten certyfikat utracił ważność poniedziałek, 21 sierpnia 2017, 11:29. Bieżący czas: wtorek, 22 sierpnia 2017, 14:06.

**Comment by gzenio22** [comment]
ha czyli to nie z naszej winy
