### ISSUE TITLE
Zippyshare.com

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3375]
POnownie przenosi po kliknieciu w download na nową karte 

Przykład : http://www71.zippyshare.com/v/fIUAFrWG/file.html

**Comment by FadeMind** [comment]
Potwierdzam.

**Comment by MajkiIT** [comment]
sprawdźcie to `/^http:\/\/p[0-9]{6,10}\.[a-z]{5,10}\.[a-z]{3,3}\/itab\//$popup`

**Comment by FadeMind** [comment]
![image-20170822-003](https://user-images.githubusercontent.com/9846948/29567634-2d64a924-874e-11e7-8098-5969a6912d0a.png)

**Comment by gzenio22** [comment]
U mnie działa :)

**Comment by MajkiIT** [comment]
@gzenio22 moja reguła czy to co wysłał @FadeMind  ?

**Comment by MajkiIT** [comment]
Dodałem tylko to nie PL strona :)

**Comment by gzenio22** [comment]
twoja @MajkiIT wiem ze nie PL ktos musi to zglosic AAK albo komus moj ang lezy

**Comment by MajkiIT** [comment]
@gzenio22 luzik :p to chyba do Easylist.

**Comment by MajkiIT** [comment]
@gzenio22 widzę, to Easylist nie dodaje teguł do tej strony.
https://easylist-downloads.adblockplus.org/easylist.txt`
