### ISSUE TITLE
diffchecker.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3377]
nie wiem moze to czegos sie przyda 

Diff Checker is an online diff tool to compare text differences between two text files.
Enter the contents of two files and click Find Difference!

**Comment by hawkeye116477** [comment]
@xxcriticxx Ja z tego korzystam czasem, przydatne narzędzie :smile:.

**Comment by xxcriticxx** [comment]
Do sprawdzania listy jest w sam raz

**Comment by gomoku** [comment]
Takich diff checkerów jest więcej: https://www.google.pl/search?q=diff+checker+online

**Comment by xxcriticxx** [comment]
@gomoku thx buddy!
