### ISSUE TITLE
onet.pl - reklama wrocila

### ISSUE THREAD

**Issue by PrzemyslawKlys** [MajkiIT/polish-ads-filter#3385]
### Co trzeba zrobić aby reklama/element się pojawił
1. Wejsc na strone onet.pl

### Twoja konfiguracja
**Przeglądarka:**
Chrome 

**Operating system:**
Windows 10

**Blocker:** 
Ublock

**Używane filtry:**
1. POL: polskie filtry do Adblocka i uBlocka
2. POL: polskie filtry do uBlocka uzupelnienie​

### Zrzut ekranu

![image](https://user-images.githubusercontent.com/15063294/29654046-e98f5f50-88ab-11e7-98cb-c783417517f3.png)

**Comment by gzenio22** [comment]
potwierdzam

**Comment by MajkiIT** [comment]
`onet.pl#@#.miniSlot`

zerknijcie

**Comment by PrzemyslawKlys** [comment]
Działa :)

**Comment by hawkeye116477** [comment]
Tyle, że wtedy w 1 miejscu wróci resztka po reklamie, o której wspominał parę dni temu @Fademind.
Ale chyba jak damy coś takiego: `onet.pl##.miniSlot:style(min-height: 0rem!important;margin-bottom: 0rem!important;)`, to będzie ok.

**Comment by PrzemyslawKlys** [comment]
@hawkeye116477 po twojej zmianie wróciło wszystko (zamieniłem wpis @MajkiIT)

**Comment by MajkiIT** [comment]
@PrzemyslawKlys Musisz dodac 2 .

**Comment by PrzemyslawKlys** [comment]
Ok oba działają

**Comment by MajkiIT** [comment]
Podmienione. Dzięki

**Comment by PrzemyslawKlys** [comment]
Ale to nie powinno byc dwoch wpisow? Ty podmieniłeś jedno na drugie

![image](https://user-images.githubusercontent.com/15063294/29661566-bc035794-88c4-11e7-8d9a-bd7bb02622e8.png)

U mnie działa kiedy są oba:
onet.pl#@#.miniSlot
onet.pl##.miniSlot:style(min-height: 0rem!important;margin-bottom: 0rem!important;)

**Comment by MajkiIT** [comment]
Bo na PL filtrach było onet.pl##.miniSlot. A to onet.pl#@#.miniSlot wyłącza onet.pl##.miniSlot . :D

**Comment by xxcriticxx** [comment]
@MajkiIT macie cos takiego

http://film.onet.pl/katie-holmes-na-premierze-serialu-the-tick/bhef16

![screenshot from 2017-08-24 06-07-58](https://user-images.githubusercontent.com/15007183/29661695-da359088-8892-11e7-9293-dbbd9ad0071f.png)

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/29661726-3a82fe3a-88c5-11e7-9800-802643aba30d.png)

Ja tam się nie znam więc już się nie odzywam :)

**Comment by xxcriticxx** [comment]
mam jeszcze to samo na zdjeciach 

![screenshot from 2017-08-24 06-10-51](https://user-images.githubusercontent.com/15007183/29661800-1d93bc10-8893-11e7-8149-ca4cd1f4628f.png)

**Comment by MajkiIT** [comment]
która wersja filtrów ? @xxcriticxx

**Comment by xxcriticxx** [comment]
! v.2017082401 aktualizacja: czw, 24 sierpnia 2017, 07:45:00

**Comment by MajkiIT** [comment]
zrób update do ! v.2017082402 @xxcriticxx

**Comment by MajkiIT** [comment]
@PrzemyslawKlys znasz się znasz :P

**Comment by xxcriticxx** [comment]
sprawa rozwiazana thx

i thx za test hosta na win10

**Comment by xxcriticxx** [comment]
zamykam
