### ISSUE TITLE
czyli po polsku rozszerzenia

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3386]
jest jakis plugin do szybkiego wyczysczenia hist/cook dla firefox/chrome? 

@hawkeye116477 twoj departament

**Comment by hawkeye116477** [comment]
@xxcriticxx Może coś takiego: 
Firefox -> https://addons.mozilla.org/pl/firefox/addon/clear-recent-history/?src=ss albo ewentualnie https://addons.mozilla.org/pl/firefox/addon/all-in-one-sidebar/?src=ss

Chrome -> https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews

Ale jakby co to ja tego nie testowałem. Na Vivaldim i tak jest szybko, wciska się `ctrl+shift+del` i po sprawie. Zresztą zdaje się, że na Chromium/Chrome, a nawet i Firefoksie/Waterfoksie też to działa.

**Comment by xxcriticxx** [comment]
@hawkeye116477 mam za tani latop niemam guzika `delete`

**Comment by xxcriticxx** [comment]
@hawkeye116477 click&clean bendzie chyba dzialac

**Comment by hawkeye116477** [comment]
@xxcriticxx Aha, tego się nie spodziewałem. W Vivaldim można skróty klawiszowe sobie zmienić. A Firefoks i Chrome widać coś nie pomyśleli, by dodać coś takiego.

Dla Chrome jest: https://chrome.google.com/webstore/detail/keyconfig/okneonigbfnolfkmfgjmaeniipdjkgkl
Dla Firefoksa: https://addons.mozilla.org/pl/firefox/addon/keybinder/

**Comment by xxcriticxx** [comment]
@hawkeye116477 poradzimy dont worry

**Comment by hawkeye116477** [comment]
@xxcriticxx Ok, jakbyś kiedyś planował przesiąść się z Firefoksa na Waterfoksa, to polecam skorzystać z mojego repo APT -> https://hawkeye116477.github.io/waterfox-deb/ :smile:.

**Comment by hawkeye116477** [comment]
https://www.dobreprogramy.pl/Firefox-zbiera-za-malo-danych-Mozilla-planuje-rozszerzyc-telemetrie,News,82750.html
Kolejną funkcję zerżnęli z Chrome :smiley:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 fajnie bendziemy mieli co blokowac

**Comment by hawkeye116477** [comment]
@xxcriticxx Co blokować, telemetrię? Lepiej Waterfoksa zainstalować, Alex to wywalił, nawet wywalił Google Analytics z about:addons.

**Comment by xxcriticxx** [comment]
Czytałem gdzieś ze waterfox no more production

**Comment by hawkeye116477** [comment]
@xxcriticxx To nie Waterfox, tylko Cyberfox. Jeszcze niby jest, ale aktualizacje są tylko do ESR, chyba głównie dlatego, że twórca Toady ma jakieś problemy zdrowotne. 
A Waterfox nadal będzie, Alex ma wielkie plany, będą i są stare rozszerzenia, będzie sklep z rozszerzeniami dla Waterfoksa, team też chyba ma się powiększyć, w ogóle chyba ma powstać nowa przeglądarka, której głównym językiem ma być C++, a nie Rust i będzie Waterfox na Androida.

A słyszałeś o tym, że Mozilla łączy siły z Sorosem, by blokować nieprawdziwe informacje? Pewnie już nie będziesz mógł wchodzić na wpolityce.pl :smiley:. Ale userzy Waterfoksa nie mają czego się obawiać, Alex nie zamierza "cenzurować" i mieszać się w politykę i tego nie doda.
