### ISSUE TITLE
Blokowanie ofert na pclab

### ISSUE THREAD

**Issue by krzys1u** [MajkiIT/polish-ads-filter#3387]
https://github.com/MajkiIT/polish-ads-filter/blob/38fb17e0451ea373a118e94e3df1c43f1b356f97/polish-adblock-filters/adblock.txt#L1001

linia 1001 blokuje oferty na pclabie proszę o poprawę

![image](https://user-images.githubusercontent.com/12277541/29677568-cd0badb6-88fb-11e7-9459-0d189f82c1f2.png)

**Comment by MajkiIT** [comment]
@krzys1u Dzięki
