### ISSUE TITLE
przegladsportowy.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#3388]
![image](https://user-images.githubusercontent.com/29756590/29712119-8dfe1ec2-8998-11e7-8a3b-529232e7f7ae.png)
Panowie da radę się tego pozbyć ?
@hawkeye116477 Pisałem do pingwina w tej sprawie, ale nie mógł tego odtworzyć u siebie i zamknął temat.

**Comment by hawkeye116477** [comment]
@HateAds Ja też tego u siebie nie widzę, podobnie jak pingwin.

**Comment by HateAds** [comment]
@hawkeye116477 Nie potrafię dokładnie odpowiedzieć na Twoje pytanie. Przeglądałem tam różne newsy i nagle to wyskoczyło. Teraz usunąłem cookies i na razie się nie pojawia.

**Comment by hawkeye116477** [comment]
@HateAds Coś chyba musiałeś im podpaść, gdyż mi się nie wyświetla :smiley:.

**Comment by MajkiIT** [comment]
@HateAds sprawdź to:

```
przegladsportowy.pl#@#.pub_300x250
przegladsportowy.pl#@#.pub_300x250m
przegladsportowy.pl#@#.pub_728x90
przegladsportowy.pl#@#.text-ad
przegladsportowy.pl#@#.textAd
przegladsportowy.pl#@#.text_ad
przegladsportowy.pl#@#.text_ads
przegladsportowy.pl#@#.text-ads
przegladsportowy.pl#@#.text-ad-links
```

**Comment by HateAds** [comment]
@MajkiIT Sprawdzę jak mi się ten antyadblock pojawi.

**Comment by MajkiIT** [comment]
ok

**Comment by xxcriticxx** [comment]
umnie adblock lapje tylko na foxie reguly @MajkiIT pomogly nie ma problemu z chromem

**Comment by xxcriticxx** [comment]
po ponownym uruchomieniue fox adblock wraca nawet z @MajkiIT regulami

**Comment by xxcriticxx** [comment]
btw

![capture](https://user-images.githubusercontent.com/15007183/29719607-cb5475f0-8984-11e7-8905-06906c8eb64d.PNG)

![capture1000000](https://user-images.githubusercontent.com/15007183/29719609-cdfd22ac-8984-11e7-931c-d4ea60ef1c33.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx A co jak dodasz do foxowego uBlocka `przegladsportowy.pl^$generichide`?

**Comment by hawkeye116477** [comment]
@xxcriticxx A co jak dodasz do foxowego uBlocka `@@||przegladsportowy.pl^$generichide`?

**Comment by xxcriticxx** [comment]
sie zdaje ze dziala potestuje jeszcze troche i dam znac

**Comment by MajkiIT** [comment]
@hawkeye116477 @xxcriticxx @HateAds Oni chyba testowali coś. .... teraz nie ma tych elementów.
