### ISSUE TITLE
http://www.mpc-g.com/the-escapists/

### ISSUE THREAD

**Issue by kerbenii** [MajkiIT/polish-ads-filter#339]
Please disable your AdBlock :(    We work hard on this website, support our work.

Blokowanie własne elementu <b>B</b> (pogrubienia)  również nie działa.

**Comment by kerbenii** [comment]
Jakikolwiek komentarz?

**Comment by MajkiIT** [comment]
Nie jest to strona polska noi nic się nie wyświetla takiego.
