### ISSUE TITLE
transfery.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3400]
http://transfery.info/104870,oficjalnie-ibrahimovic-podpisal

![capture](https://user-images.githubusercontent.com/15007183/29742482-1346996e-8a4e-11e7-89c4-326ce7dc509d.PNG)

**Comment by hawkeye116477** [comment]
Reklama: `transfery.info##.blok:nth-of-type(4) > .head_blok`
Facebook: 
```
transfery.info##.blok:nth-of-type(5)
transfery.info##.blok:nth-of-type(3)
```

**Comment by hawkeye116477** [comment]
@MajkiIT Reklamy już nie ma, więc chyba do zamknięcia.

**Comment by xxcriticxx** [comment]
@hawkeye116477 dalej jest puste miesce po reklamie
