### ISSUE TITLE
kino.ck.przemysl.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3401]
cookies

http://www.kino.ck.przemysl.pl/kino/repertuar.html?sEventDate=2017-01-24

![capture](https://user-images.githubusercontent.com/15007183/29742909-90eb153c-8a55-11e7-80ff-d755098b5edb.PNG)

**Comment by hawkeye116477** [comment]
`kino.ck.przemysl.pl###widget-12`
