### ISSUE TITLE
wio.waw.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3403]
![capture](https://user-images.githubusercontent.com/15007183/29742985-b24b90a2-8a56-11e7-8c81-031698d886c0.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Jeszcze reklamy nie ma, dopiero miejsce szykują, a ty już zgłaszasz, nie dajesz im się rozkręcić :smiley:.

Reklamy:
```
wio.waw.pl##a[href="http://mpgmedia.pl/"]
wio.waw.pl##.fl.w1000
wio.waw.pl##.row:nth-of-type(3) > .fr.w250
wio.waw.pl##.row:nth-of-type(18) > .fl.w250:nth-of-type(3)
```

Odblokowanie filmików i komentarzy:
`@@||*.exs.pl^$domain=wio.waw.pl`

**Comment by MajkiIT** [comment]
```
wio.waw.pl##.fr.w250
@@||*.exs.pl^$domain=wio.waw.pl
```
