### ISSUE TITLE
splendo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3407]
facebook z prawej

**Comment by hawkeye116477** [comment]
@xxcriticxx Niestety tam fejsa nie ma.

**Comment by gzenio22** [comment]
ja tez nie widze

**Comment by hawkeye116477** [comment]
No jasne, @xxcriticxx ma pewnie Fanboya wyłączonego. A jak mawiał @blocker999 - nie blokujemy tego co Fanboy blokuje.

**Comment by blocker999** [comment]
@xxcriticxx Potwierdzam niedublijemy Fannboyi : https://www.certyficate.it/polskie-filtry-elementow-spolecznosciach/

**Comment by hawkeye116477** [comment]
@blocker999 A co tak narozrabiałeś, że banana dostałeś?

**Comment by xxcriticxx** [comment]
tak jak pisalem nie kozystam z social niewiedzialem ze jakie inne listy trzeba wlonczyc

**Comment by hawkeye116477** [comment]
@xxcriticxx No to @MajkiIT może powinien zmienić trochę linka do subscribe, dołożyć do PL listy, że wymaga EasyList, a do sociala, że wymaga Fanboya.
https://www.certyficate.it/adblock/

**Comment by xxcriticxx** [comment]
@hawkeye116477 najlepjej social i uzywac i po problemie

**Comment by hawkeye116477** [comment]
Coś w tym stylu i każdemu od razu by 2 filtry się dodały i po problemie:
`<a href="abp:subscribe?location=https%3A%2F%2Fraw.githubusercontent.com%2FMajkiIT%2Fpolish-ads-filter%2Fmaster%2Fadblock_social_filters%2Fadblock_social_list.txt&amp;title=Polskie%20filtry%20social&amp;requiresLocation=https%3A%2F%2Feasylist-downloads.adblockplus.org%2Ffanboy-social.txt&amp;requiresTitle=Fanboy's%20Social%20Blocking%20List">Subscribe</a>`

**Comment by xxcriticxx** [comment]
@hawkeye116477 do you approve this change?

**Comment by hawkeye116477** [comment]
@xxcriticxx Jaką zmianę?

**Comment by xxcriticxx** [comment]
Miało być @majkiit złe wybrałem z listy

**Comment by MajkiIT** [comment]
@xxcriticxx już poprawiam

**Comment by hawkeye116477** [comment]
@MajkiIT A to dlatego nie dodałeś, w sumie sprawdziłem teraz i na uBlocku coś też te podwójne filtry nie chcą działać. Dlatego też moja tabelka zapewne byłaby lepsza.
[filtry_czern_biel.zip](https://github.com/MajkiIT/polish-ads-filter/files/1255909/filtry_czern_biel.zip)
![screenshot_20170828_111514](https://user-images.githubusercontent.com/19818572/29767282-302dde8a-8be2-11e7-8998-2c13c233a1c4.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 dodałem, ale później cofnąłem zmianę.
