### ISSUE TITLE
przegladsportowy.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3414]
![image-20170826-001](https://user-images.githubusercontent.com/9846948/29744105-25dbe4a8-8a9e-11e7-8e20-13607c56a170.png)

```
przegladsportowy.pl##.lazy
```

**Comment by MajkiIT** [comment]
@FadeMind Dzięki

**Comment by GrzegorzWziatek** [comment]
Hej,
reguła ta zgasiła również wszystkie obrazki zajawek doczytywane przez lazy-loading w serwisie - wystarczy załadować stronę a następnie zacząć przewijać w dół stronę
