### ISSUE TITLE
pomponik.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3419]
![image-20170827-001](https://user-images.githubusercontent.com/9846948/29748421-e535a9f6-8b16-11e7-8c4a-92cac70e4d19.png)

```
pomponik.pl##.ppg__signin
```

**Comment by hawkeye116477** [comment]
To macie się z tym pushami. Przecież można je w przeglądarce zablokować. A tak zablokujemy, a ktoś może będzie chciał znać te ploty i się nie dowie :smiley:.

**Comment by MajkiIT** [comment]
Dodaliśmy je do PL filtrów :P a co chcesz oddzielną?

**Comment by hawkeye116477** [comment]
@MajkiIT Ta, jestem raczej za oddzielną, bo niektóre mogą jednak się przydać, np.media expert, pewnie jakieś powiadomienia o promocjach czy gazetkach są, choć ja w sumie nie korzystam, od tego mam Tropiciela okazji na Androidzie :smiley:.
