### ISSUE TITLE
umatrix

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3421]
https://niebezpiecznik.pl/post/umatrix-dodatek-do-google-chrome-i-firefoksa-z-ktorego-kazdy-powinien-korzystac/

**Comment by hawkeye116477** [comment]
To raczej nie dla każdego, a dla profesjonalistów. Dla tych mniej zaawansowanych to chyba filtry do uBlocka są.

**Comment by xxcriticxx** [comment]
dawno temu uzywalem noscript na foxie
