### ISSUE TITLE
Co to ?

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3424]
Fajna ankieta mi dziś wyskoczyła, proszę to zablokować lub przekazać osobą zajmującym się tym.

http://competition1904.cdn-network4-server5.biz/default.aspx?u=bl3pte4&o=xbkkvzb&m=1&t=main2_desk&f=1

![ankieta](https://user-images.githubusercontent.com/23176832/29772182-d92284ae-8bf7-11e7-996b-02fd19f86c4a.png)

**Comment by hawkeye116477** [comment]
@blocker999 To chyba raczej do twojego kolegi @azet12.

**Comment by blocker999** [comment]
@hawkeye116477 Ok chyba to jednak ddo KAD.

Nie dzięki niechce szansy na 500zł bo mogę się rozczarować, a pozatym niewiedziałbym naco wydać tą kase w IKEI.
