### ISSUE TITLE
histmag.org [adguard]

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3425]
https://histmag.org/Wal-Hadriana-Mur-ktory-chronil-przed-dzikimi-11312

![image-20170828-006](https://user-images.githubusercontent.com/9846948/29772826-b6297ffe-8bfa-11e7-96ea-ea3d9034a8f6.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by hawkeye116477** [comment]
@FadeMind `@@||histmag.org/themes/histmag/assets/js/ads.js`

**Comment by MajkiIT** [comment]
Dzięki
