### ISSUE TITLE
chip.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3426]
http://www.chip.pl/
- reklama w tle
![image-20170828-008](https://user-images.githubusercontent.com/9846948/29772926-441706b0-8bfb-11e7-874c-eee96fa14be6.png)

![image-20170828-007](https://user-images.githubusercontent.com/9846948/29772930-4e3dc0ac-8bfb-11e7-96ee-cd23b85f0ef0.png)
- adguard ukrył logo CHIP po lewej stronie na czerwonej belce
![image-20170828-009](https://user-images.githubusercontent.com/9846948/29772944-57b02760-8bfb-11e7-870f-22ccdcebdbb6.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

![image-20170828-010](https://user-images.githubusercontent.com/9846948/29773015-cb4f9e1c-8bfb-11e7-8e72-16cc0632cc96.png)

**Comment by hawkeye116477** [comment]
@FadeMind Ta reklama jest na głównej stronie? Bo jeżeli tak, to w takim razie, dotyczy to tylko Adguarda.

**Comment by MajkiIT** [comment]
@hawkeye116477 od razu przesadził :D
