### ISSUE TITLE
miastons.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3427]
Cookies i reklamy :)

Cokies
miastons.pl###overflow-content
miastons.pl###overflow-close
Reklamy
miastons.pl###banner_top
miastons.pl###top > .cms_module:nth-of-type(1)
miastons.pl###col_left > .cms_module:nth-of-type(2)
miastons.pl###spotlight > .cms_module:nth-of-type(2)
miastons.pl###main_right > .cms_module:nth-of-type(2)
miastons.pl###main_right > .cms_module:nth-of-type(4)
miastons.pl##.cms_module:nth-of-type(6)
miastons.pl##.cms_module:nth-of-type(9)

Spoooro XD da sie to jakos skrocic? :)

**Comment by xxcriticxx** [comment]
`||miastons.pl`

**Comment by MajkiIT** [comment]
a może tak ?
`miastons.pl##IMG[src^="http://www.miastons.pl/media/Banners/"]`

**Comment by hawkeye116477** [comment]
@gzenio22 Ciastka można krócej: `miastons.pl##[id^="overflow"]` :smile:
