### ISSUE TITLE
nczas.com

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3428]
http://nczas.com/

![image-20170828-013](https://user-images.githubusercontent.com/9846948/29785763-12d85878-8c29-11e7-9d08-269914887015.png)

**Comment by xxcriticxx** [comment]
@FadeMind adguard?

**Comment by FadeMind** [comment]
tak

**Comment by hawkeye116477** [comment]
@FadeMind Ja też to widzę.
`nczas.com##.td-pb-row.wpb_row.vc_row:nth-of-type(1)`

**Comment by FadeMind** [comment]
@hawkeye116477 usuń swoją regułę, sprawdź te:
```
nczas.com##.td-g-rec-id-header
nczas.com##.td-pb-span12
```

**Comment by hawkeye116477** [comment]
@FadeMind 1 reguła u mnie nic nie robi, a druga za dużo chowa, na dole artykuły znikają.

**Comment by gzenio22** [comment]
nczas.com##.td-pb-row.wpb_row.vc_row:nth-of-type(1)
nczas.com##.td-pb-row.wpb_row.vc_row:nth-of-type(4)

Hmm?

**Comment by MajkiIT** [comment]
`nczas.com##A[target="_self"] > .vc_single_image-img:last-child`

Moja propozycja :D

**Comment by xxcriticxx** [comment]
@MajkiIT da rade pociagnac jeszcze?

**Comment by MajkiIT** [comment]
@xxcriticxx jedynie co mi przychodzi do głowy to `nczas.com##.td-pb-row.wpb_row.vc_row:nth-of-type(1)`

**Comment by xxcriticxx** [comment]
@MajkiIT to zostaw to ja tych north nie za bardzo lubie zawsze cos mieszaja na stronie

**Comment by MajkiIT** [comment]
@xxcriticxx ok

**Comment by xxcriticxx** [comment]
Thx
