### ISSUE TITLE
ublock for FF

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3429]
Ublock wtyczka przestarzala hahaha takie cudo po zaktualizowaniu sie przegladarki

**Comment by MajkiIT** [comment]
@gzenio22 nie tylko ubo, ale Adblock Plus itp

**Comment by xxcriticxx** [comment]
pokazaly sie reklamy na fb?

**Comment by gzenio22** [comment]
@MajkiIT o kurwa jak cos zjebac to na calego brawo mozilla haha

**Comment by gzenio22** [comment]
@xxcriticxx wszystko jeblo nie tylko FB haha

**Comment by xxcriticxx** [comment]
@gzenio22 wytlumacz oco lata please

**Comment by MajkiIT** [comment]
https://support.mozilla.org/pl/kb/modernizacja-technologii-dodatkow-dla-firefoksa?as=u&utm_source=inproduct

**Comment by xxcriticxx** [comment]
@gzenio22 nie strasz mnie przed obiadem

**Comment by gzenio22** [comment]
@xxcriticxx na FF chyba obecnie zaden adblock nie ogarnia :D

**Comment by xxcriticxx** [comment]
Fajnie stracą klientelę

**Comment by MajkiIT** [comment]
@gzenio22 już jest wersja 1.14 i nie jest przestarzała :)
