### ISSUE TITLE
finanse.wp.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3430]
https://finanse.wp.pl/rossmann-stosuje-podwojne-ceny-na-niekorzysc-polakow-siec-tlumaczy-w-polsce-jest-wiecej-promocji-6159337241139329a

![image-20170829-002](https://user-images.githubusercontent.com/9846948/29818967-d6810032-8cbe-11e7-94b8-ae9d67253a8c.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by MajkiIT** [comment]
`@@|https://imasdk.googleapis.com/js/sdkloader/ima3.js*$script`

Sprawdź proszę

**Comment by FadeMind** [comment]
@MajkiIT Działa. Co ciekawe czasami ponownie załącza się blokada, ale po zamknięciu strony i otwarciu jej ponownie w nowej karcie player działa poprawnie.

**Comment by MajkiIT** [comment]
@FadeMind czyli dodać?

**Comment by FadeMind** [comment]
@MajkiIT tak. dodać.
