### ISSUE TITLE
biznes.interia.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3431]
http://biznes.interia.pl
```
biznes.interia.pl##.fb_iframe_widget
```
![image-20170829-006](https://user-images.githubusercontent.com/9846948/29829541-fe7cb84e-8cdf-11e7-859f-33adce3cad5c.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by MajkiIT** [comment]
to chyba wpada pod social :P

**Comment by blocker999** [comment]
@MajkiIT a propo social odbierasz poczte?

**Comment by MajkiIT** [comment]
@blocker999 widziałem i próbuję ogarnąć. Mam wrzucić to co mi wysłałeś ? Z tego co widzę w pull to jest sporo konfliktów.

**Comment by FadeMind** [comment]
@MajkiIT Nie mam blokady social (patrz aktywne listy).

**Comment by MajkiIT** [comment]
@FadeMind zaraz zerknę co tam powinno być.

**Comment by blocker999** [comment]
@MajkiIT Napisz do @hawkeye116477 i podajmu na poczte mój adres meila bo być może on to ogarnie, bo ja zielony jestem i brak czasu na nauke.

**Comment by MajkiIT** [comment]
@blocker999 ogarnę to max do jutra będzie update. Spoko loko.

**Comment by hawkeye116477** [comment]
@blocker999 A to jeszcze coś nowego jest? Czy tylko to co pisałeś w komentarzu na pull?

**Comment by blocker999** [comment]
@hawkeye116477 Możesz wejś na gmaila żeby niezaśmiecać wątku tam masz wiadomość odemnie ale najpierw zajmij się tym pullem + nowa reguła ta w pierwszym poście, dalsze wskazówki meilowo .
( prosze, zajmij się tym )

**Comment by FadeMind** [comment]
@MajkiIT  jak już przy social jesteśmy:
![image-20170829-007](https://user-images.githubusercontent.com/9846948/29832613-16a9da9c-8ce9-11e7-8e81-c05798573c61.png)
http://www.instalki.pl/aktualnosci/gry/27771-absurd-w-zemscie-za-brak-half-life-3-gracze-gnebia-dota-2.html

Brakuje share buttons (widok bez włączonego ADG)
![image-20170829-008](https://user-images.githubusercontent.com/9846948/29832673-3c3d2c14-8ce9-11e7-9057-2025e64df903.png)

**Comment by blocker999** [comment]
@FadeMind 

https://www.certyficate.it/polskie-filtry-elementow-spolecznosciach/

żeby było ok należy dodać  liste Fanboi + polskie no chyba że na pomimo to niedziała

**Comment by FadeMind** [comment]
Czytałeś pierwszy post? @blocker999 
NIE BLOKUJĘ social w ogóle, a mimo to są poukrywane elementy :P

**Comment by blocker999** [comment]
ok, nieczytałem dokładnie przepraszam

**Comment by MajkiIT** [comment]
@FadeMind ten Adguard to w twoim przypadku wtyczka do przeglądarki czy wersja Windows?

**Comment by FadeMind** [comment]
`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
![image-20170829-010](https://user-images.githubusercontent.com/9846948/29834304-b40d19e8-8cee-11e7-8e94-42a09103fe3c.png)

**Comment by MajkiIT** [comment]
Ok dziękuje

**Comment by MajkiIT** [comment]
@F4z mogę poprosić o pomoc.?
Na Ubo po wejściu na stronę http://biznes.interia.pl/ widzę FB. Jak wejdę na tą stronę z Adguard jako dodatek do FF nie widzę tego. Co najlepsze wyłączam Aguard i nadal nie widzę?

**Comment by F4z** [comment]
Szczerze mówiąc nie wiem czemu tak się dzieje.
Wygląda na to, że to jakiś błąd w rozszerzeniu, jutro postaram się kogoś o to zapytać.
Dzięki za sprawdzenie.

**Comment by MajkiIT** [comment]
@F4z Dziękuję
