### ISSUE TITLE
trzeba będzie walczyć

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3434]
http://innpoland.pl/136955,nowy-reklamy-sa-skuteczniejsze-od-spamu-i-sa-odporne-na-adbloka-zwrot-nawet-do-6tys-proc-ledwie-weszly-a-juz-podbijaja-rynek

**Comment by hawkeye116477** [comment]
@MajkiIT Ale przecież te powiadomienia można normalnie zablokować w przeglądarce.

**Comment by xxcriticxx** [comment]
push or not to push?

**Comment by hawkeye116477** [comment]
![screenshot_20170829_202031](https://user-images.githubusercontent.com/19818572/29837116-936c013c-8cf7-11e7-9efb-7c5b27f00c36.png)
![screenshot_20170829_202048](https://user-images.githubusercontent.com/19818572/29837129-9d53ac40-8cf7-11e7-8a08-7cd5c76380c3.png)

**Comment by FadeMind** [comment]
@MajkiIT 
![image-20170829-012](https://user-images.githubusercontent.com/9846948/29837386-45465d44-8cf8-11e7-8781-c2d9065eb378.png)

![s](https://media.giphy.com/media/Ent2j55lyQipa/giphy.gif)

**Comment by hawkeye116477** [comment]
@Fademind Można też to zablokować bezpośrednio w przeglądarce -> https://www.certyficate.it/blokowanie-powiadomien-za-pomoca-przegladarki/.

**Comment by xxcriticxx** [comment]
@hawkeye116477 jaki ty mi browser kazales sprawdzic?

**Comment by gzenio22** [comment]
@hawkeye116477 Musze cie zmartwic ja mam to wylaczone a i tak czasem mi te smrody wyskakuja wiec tak trzeba bedzie walczyc

**Comment by MajkiIT** [comment]
@FadeMind no to tysiak do zajebistości :D

**Comment by hawkeye116477** [comment]
@gzenio22 W jakiej przeglądarce?
@xxcriticxx Vivaldi

**Comment by hawkeye116477** [comment]
@gzenio22 W jakiej przeglądarce?
@xxcriticxx Ja kazałem coś sprawdzić? A no tak pewnie chodzi o Waterfox, w którym nadal mają być stare dodatki.

**Comment by gzenio22** [comment]
@hawkeye116477 Opera i frajerfox ktory wczoraj zrobil psikusa wszystkim blockerom

**Comment by hawkeye116477** [comment]
@gzenio22 Wyłączyłeś całkowicie w ustawieniach czy tylko masz podane co ma blokować? A w przypadku Firefoksa to jeżeli tam masz tylko podane strony które ma blokować, to uważaj by przy czyszczeniu danych nie czyścić ustawień witryn, a jeśli na stałe, to tam jeszcze jest parę wpisów do about:config, które można dodać, ale ja nie wiedziałem dokładnie, które, bo każdy co innego podaje, nie mogli tego wsadzić do ustawień czy jak? A co do Chropery to nie wiem czemu tam nie działa, może bug jakiś czy coś.

**Comment by hawkeye116477** [comment]
@gzenio22 W przypadku Firefoksa to jeżeli tam masz tylko podane strony które ma blokować, to uważaj by przy czyszczeniu danych nie czyścić ustawień witryn, a jeśli na stałe, to tam jeszcze jest parę wpisów do about:config, które można dodać, ale ja nie wiedziałem dokładnie które, bo każdy co innego podaje, nie mogli tego wsadzić do ustawień czy jak?
Spróbuj ustawić `dom.webnotifications.enabled` na `false`.
A co do Chropery to nie wiem czemu tam nie działa, może bug jakiś czy coś.
U mnie na Vivaldim mam włączone blokowanie powiadomień i na wp są grzeczni, nie pytają w ogóle.
@xxcriticxx Polecam skorzystać z mojego repo APT -> https://hawkeye116477.github.io/waterfox-deb/ :smile:.

**Comment by xxcriticxx** [comment]
ja mam ten problem co @gzenio22 ze na foxie mi sam ublock znika 

trzeba skoczyc na chroma na pare dni

**Comment by hawkeye116477** [comment]
@xxcriticxx  @gzenio22 
https://github.com/gorhill/uBlock/releases 
Notki do 1.3.10:
> Important: If you are having issue with uBO being irremediably broken with the 1.13.10 update, try to un-install the re-install uBO -- possibly quitting Firefox before re-installing. See issue #2909 / https://bugzilla.mozilla.org/show_bug.cgi?id=1372750 (reportedly fixed in Firefox 56).
Tam jest tego więcej, poczytajcie do końca

**Comment by xxcriticxx** [comment]
@hawkeye116477 ok powodzenia

**Comment by hawkeye116477** [comment]
@xxcriticxx Już zrobiłem reinstall uBlocka i wszystko jest jak na razie ok. A jeśli znowu coś się przytrafi to najwyżej wypróbuję betę full webextension zamaist webextension/hybrid.

**Comment by xxcriticxx** [comment]
@hawkeye116477 ja z hybrid zamykałem foxa extension sama znikała dzisaj miałem testować beta ver

**Comment by hawkeye116477** [comment]
@xxcriticxx A robiłeś reinstall?

**Comment by xxcriticxx** [comment]
Tak zamykam fox i niemam ublocka muszę znowu montowac

**Comment by gzenio22** [comment]
mam to samo co @xxcriticxx

**Comment by hawkeye116477** [comment]
@xxcriticxx @gzenio22 No to dziwne, bo u mnei coś takiego się nie dzieje. A może źle to zrobiliście powinniście odinstalować uBlocka, a potem zrobić restart Foxa i dopiero zainstalować uBlocka. 
A jeśli to wam nie pomaga, to pozostaje wam tylko zainstalować czystą wersję webext -> https://addons.mozilla.org/firefox/downloads/file/709305/ublock_origin-1.13.11rc0-an+fx.xpi .
Albo cofnąć się do 1.13.8, ale wtedy trzeba będzie wyłączyć autoupdate dla uBlocka i dopiero go ponownie włączyć jak będziecie mieli FF 56/WF 56.

**Comment by xxcriticxx** [comment]
ja narazie zamontowalem ver 1.13.11

**Comment by gzenio22** [comment]
gdzie wkleic ten plik co sie pobiera?

**Comment by hawkeye116477** [comment]
@gzenio22 Wklep to paska adresu i wciśnij enter.

**Comment by hawkeye116477** [comment]
@gzenio22 Wklep to paska adresu i wciśnij enter albo jeśli pobierałeś to jakimś menedżerem pobierania to przeciągnij ten plik na pasek adresu i wciśnij Enter.

**Comment by gzenio22** [comment]
@hawkeye116477 Dziala :)
