### ISSUE TITLE
tosiedzieje.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3438]
http://tosiedzieje.pl/p3572-swiat-na-granicy-wojny-rakieta-z-polnocnej-korei-przeleciala-nad-japonia/

Pozostałość po reklamie po prawej stronie
![image-20170829-015](https://user-images.githubusercontent.com/9846948/29841822-2b1f4386-8d07-11e7-9348-cbf62c7add58.png)

**Comment by gzenio22** [comment]
tosiedzieje.pl##.clr.ai_widget

**Comment by xxcriticxx** [comment]
Adguard?

**Comment by gzenio22** [comment]
u mnie tez to bylo niech ktos zerknie

**Comment by xxcriticxx** [comment]
Ja testa zrobię za 30 min

**Comment by xxcriticxx** [comment]
`tosiedzieje.pl##.widget-title`

**Comment by gzenio22** [comment]
ummm czyli za daleko skrocilem u mnie bez title ogarnelo dziiwne

**Comment by xxcriticxx** [comment]
@gzenio22 :+1:

**Comment by gzenio22** [comment]
@xxcriticxx mam banalne pytanie dla czego wam te reguly pokazuje na szarym tle a mi zawsze normalnie co robie nie tak? XD

**Comment by xxcriticxx** [comment]
@gzenio22 dodaj ' reguła '
