### ISSUE TITLE
fronda.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3440]
http://www.fronda.pl
![image-20170830-003](https://user-images.githubusercontent.com/9846948/29865023-b4986cce-8d74-11e7-95b7-caa69678cb62.png)

```
fronda.pl##.selfpromotion-ticker
```

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by MajkiIT** [comment]
`fronda.pl##.selfpromotion-ticker.pull-left` może coś takiego?
