### ISSUE TITLE
wgospodarce.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3442]
http://wgospodarce.pl/
Z ADG
![image-20170830-006](https://user-images.githubusercontent.com/9846948/29867300-674567d6-8d7b-11e7-9a86-d9d3c3bd9bf7.png)
BEZ ADG
![image-20170830-007](https://user-images.githubusercontent.com/9846948/29867320-764a9044-8d7b-11e7-9b55-3055dd245839.png)

**Comment by MajkiIT** [comment]
`@@||exs.pl/$script,subdocument,domain=wgospodarce.pl`
