### ISSUE TITLE
mgsm.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3443]
Open http://www.mgsm.pl
Go to http://www.mgsm.pl/pl/konto/

![image-20170830-009](https://user-images.githubusercontent.com/9846948/29870034-e02ff814-8d85-11e7-80a7-0321bab43717.png)
```
mgsm.pl###AdAreaH2
```

![image-20170830-010](https://user-images.githubusercontent.com/9846948/29870106-3908da78-8d86-11e7-809a-6fc2b07edcae.png)

```
mgsm.pl##.recommends
```
ADsign:
![image-20170830-011](https://user-images.githubusercontent.com/9846948/29870146-6d25db44-8d86-11e7-822e-d49eb22d443b.png)

```
mgsm.pl##.large-6, .medium-7, .small-12, .columns, .padding-top10, .text-center
```

```
<small style="display: block; color: #c0c0c0; font-size: 9px; text-align:center; "> R E K L A M A  </small>	</div>
```

**Comment by hawkeye116477** [comment]
@FadeMind 1-szy filtr nie działa, 2-gi jest ok, a trzeci za dużo chowa.

**Comment by FadeMind** [comment]
`mgsm.pl##.text-center.padding-top10.columns.small-12.medium-7.large-6` jest OK

**Comment by MajkiIT** [comment]
@FadeMind ja tego niestety nie mam.

**Comment by hawkeye116477** [comment]
@MajkiIT Co nie masz? Tego pierwszego czy tego wszystkiego? Tego pierwszego też nie mam.

**Comment by FadeMind** [comment]
@MajkiIT  @hawkeye116477  box z ceneo pojawia się sporadycznie. Nie mam pojęcia od czego to zależy.

**Comment by hawkeye116477** [comment]
@FadeMind Jaki box z ceneo, jak na foto masz skąpca? Może to pojawia się tylko dla wielkich fanów skąpca, a ja to raczej tam nie wchodzę, tylko na ceneo, więc mi się nie pojawia :smile:.

**Comment by MajkiIT** [comment]
znalazłem coś takiego 
`||www.mgsm.pl/js/getSkapiecSkycraper.xhtml$xmlhttprequest,domain=www.mgsm.pl`

**Comment by FadeMind** [comment]
@hawkeye116477  przejęzyczyłem się 😁  oczywiście chodzi o skąpiec pe el
