### ISSUE TITLE
muzyka.dziennik.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3445]
http://muzyka.dziennik.pl/news/artykuly/557119,60-lat-temu-urodzil-sie-grzegorz-ciechowski-wokalista-lider-republiki.html

![image-20170830-015](https://user-images.githubusercontent.com/9846948/29877997-96b2eb9e-8da1-11e7-8e05-d84bcb28fb9e.png)

Reguła usuwa header `Powiązane` - pozostałość po boxie z reklamami
```
muzyka.dziennik.pl##.widget-headertext-area
```

**Comment by MajkiIT** [comment]
@FadeMind dziękuję
