### ISSUE TITLE
super-torent.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3446]
resztki po reklamie 

![capture](https://user-images.githubusercontent.com/15007183/29886747-3171bd72-8d89-11e7-9ad7-dddbd60c8295.PNG)

**Comment by gzenio22** [comment]
##td:nth-of-type(4) > .raised:nth-of-type(2)

**Comment by xxcriticxx** [comment]
`super-torent.pl##.block`

**Comment by MajkiIT** [comment]
nie za dużo wycina? @xxcriticxx

**Comment by FadeMind** [comment]
@MajkiIT 
> `super-torent.pl###lapacz > table:nth-child(10) > tbody > tr > td:last-child > div.raised:nth-child(4) > div.boxcontent:nth-child(2) > table.lista > tbody`


![image-20170830-021](https://user-images.githubusercontent.com/9846948/29891354-0f100e04-8dcb-11e7-966d-10791c230770.png)

**Comment by xxcriticxx** [comment]
@MajkiIT no clue

**Comment by MajkiIT** [comment]
@xxcriticxx coś wymyślimy

**Comment by xxcriticxx** [comment]
@MajkiIT nie korzystam ze strony na codzien
