### ISSUE TITLE
anyfiles.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3447]
anyfiles.pl
Sample https://anyfiles.pl/Astro-Conquest-Cheats-How-to-get-titanium/Gry-i-komputery/video/186852

1. Kliknij na odtwarzacz wideo.  Rozpocznij odtwarzanie i zapauzuj.
2. Pojawi się popup i momentalnie zniknie z adresem `https://go.oclasrv.com/afu.php?id=1348802` (kod ID jest chyba losowy)

**Comment by MajkiIT** [comment]
```
||brand.ad/^
anyfiles.pl##[class^="bp-wrapp"]
```

@FadeMind Sprawdzisz?

**Comment by xxcriticxx** [comment]
sorry ja tego na foxie nie widze

**Comment by MajkiIT** [comment]
@xxcriticxx a nie masz reklam ?

**Comment by FadeMind** [comment]
@MajkiIT  bez zmian

**Comment by xxcriticxx** [comment]
@MajkiIT gdzie ma byc ta reklama film jest zapauzowany

![capture](https://user-images.githubusercontent.com/15007183/29892436-8ca75b1c-8d9c-11e7-9bc0-018391800c13.PNG)

**Comment by FadeMind** [comment]
To Popup znikający po pojawieniu się - trudno go uchwycić. Jedyny ślad to wpis w historii przeglądarki

**Comment by xxcriticxx** [comment]
tak jak pisalem na nie mam sorry

**Comment by gzenio22** [comment]
u mnie na chroperze tez nie mam nic

**Comment by F4z** [comment]
U mnie to się pojawia za każdym razem jak klikam w odtwarzacz, zarówno z uBlockiem jak i Adguardem.

Sprawdź proszę tę regułę:
`anyfiles.pl#%#Object.defineProperty(window, 'launchOpenWindow', { get: function() { return {}; } });`

**Comment by xxcriticxx** [comment]
@F4z jaki browswer? jakies scripty masz zaladowane?

**Comment by F4z** [comment]
Chrome i Firefox, żadnych skryptów.

**Comment by xxcriticxx** [comment]
@F4z jak wylaczylem script to okno mi sie pokazalo ale twoja regula nic nie pomaga

**Comment by F4z** [comment]
Bo to reguła dla Adguarda.
Do uBlocka powinno być coś takiego:
`anyfiles.pl##script:inject(abort-on-property-read.js, launchOpenWindow)`

**Comment by xxcriticxx** [comment]
@F4z ta jest 💯 % good

**Comment by MajkiIT** [comment]
@F4z Dziękuję

**Comment by FadeMind** [comment]
@F4z Dziękuję

**Comment by FadeMind** [comment]
@MajkiIT dodaj też regułę do Adguard, reguła przeznaczona do uBlocka nie działa w Adgaurd.

**Comment by F4z** [comment]
Wydaje mi się, że reguły oparte o JavaScript nie mogą być dodawane do "zewnętrznych" list.
To znaczy, nawet jak zostanie taka reguła dodana, to i tak będzie ignorowana.
Na razie aktualizacja jest z wczoraj - https://filters.adtidy.org/windows/filters/238.txt więc trzeba poczekać, ale jak do jutra nie będzie reguły to dodam ją Angielskiego filtra.
Możliwe też, że się mylę.

Dziękuję wszystkim za odpowiedzi :)

**Comment by F4z** [comment]
No i jest aktualizacja, ale reguły nie ma, zaraz ją dodam w odpowiednie miejsce.
