### ISSUE TITLE
meteoprog.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3448]
ruskie reklamy na polskich stronach?

https://www.meteoprog.pl/pl/weather/Poznan/

![capture](https://user-images.githubusercontent.com/15007183/29891593-a391d382-8d99-11e7-8d42-b10510ee13b4.PNG)

**Comment by FadeMind** [comment]
Sprawdź proszę

```
meteoprog.pl##.reclama
```

**Comment by xxcriticxx** [comment]
@FadeMind dlamnie wyglonda ok niech jeszcze ktos sprawdzic

**Comment by xxcriticxx** [comment]
moze ktos sprawdzic wiadomosci bo takie cuda mam 

https://www.meteoprog.pl/pl/news/news/

![capture](https://user-images.githubusercontent.com/15007183/29892581-1d3ed2ea-8d9d-11e7-9ca5-c29f117b483d.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx jak wyłączysz ubo nie masz tak samo?

**Comment by xxcriticxx** [comment]
@FadeMind mam ale sie wiecej zdjec sie laduje mam tylko 1 albo 2 dziury

**Comment by MajkiIT** [comment]
@FadeMind ja nie blokuję tych obrazków https://www.screencast.com/t/LIJ3U6so46
@xxcriticxx ok przyjrzę się temu
