### ISSUE TITLE
licznik

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#345]
czy da sie wstawic licznik do .txt file z filtrami taki jak widze na ublock?

chodzi mi zeby wiedziec ile jest filtrow w calym .txt

POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it): 1,539 used out of 1,548
Adblock & uBlock polish cookies filters‎ : 650 used out of 651

**Comment by MajkiIT** [comment]
Będzie ciężko, bo czasami jest kilka domen podpiętych pod 1 regułę.

**Comment by xxcriticxx** [comment]
pomysl taki mialem
