### ISSUE TITLE
newseria.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3450]
https://biznes.newseria.pl/news/polska-moze-sie-stac,p872521962
![image-20170831-001](https://user-images.githubusercontent.com/9846948/29910299-a726c134-8e29-11e7-8cb4-56d519148262.png)

```
newseria.pl##.container > .banner-nagl
```

Czasami nie wyświetla się grafika "partnera serwisu" po prawej:
![image-20170831-002](https://user-images.githubusercontent.com/9846948/29910414-2d5f1fb2-8e2a-11e7-8561-b5b264b322f5.png)

https://innowacje.newseria.pl/

![image-20170831-003](https://user-images.githubusercontent.com/9846948/29910419-30993de8-8e2a-11e7-902f-10522fd60e06.png)

https://biznes.newseria.pl/news/polska-moze-sie-stac,p872521962

**Comment by MajkiIT** [comment]
@FadeMind dzięki
