### ISSUE TITLE
forum.kodiwpigulce.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3451]
Resztki reklamy

forum.kodiwpigulce.pl##.wrapper > center
Na reklame po wejsciu w jakis wątek
forum.kodiwpigulce.pl###posts > div:nth-of-type(2)

**Comment by FadeMind** [comment]
Dodatkowo 
```
forum.kodiwpigulce.pl##.dsbygoogle
```

![image-20170831-003](https://user-images.githubusercontent.com/9846948/29931426-8899cf34-8e71-11e7-9676-da6fac88023a.png)
