### ISSUE TITLE
innpoland.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3452]
http://innpoland.pl/136875,ekonomisci-lapia-sie-za-glowy-szykuja-sie-nowe-podatki-rzad-ma-juz-projekt-przyszlorocznego-budzetu

![image-20170831-001](https://user-images.githubusercontent.com/9846948/29929997-70f0b0d6-8e6d-11e7-801f-fd1cfc26cec0.png)

```
pl##.onnetwork-video
```
(dotyczy całej grupy natemat (mamadu, innpoland, natemat etc.)
bez ADG
![image-20170831-002](https://user-images.githubusercontent.com/9846948/29930040-91daf13a-8e6d-11e7-9724-9551fd2c075e.png)

**Comment by MajkiIT** [comment]
@FadeMind dzięki
