### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3458]
Pozmieniali wygląd strony, więc warto ich przejrzeć.

**Comment by gzenio22** [comment]
Napewno player dalej sie wali Xd przetestowane :D

**Comment by FadeMind** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/6564

**Comment by xxcriticxx** [comment]
@blocker999 moze ten popup skasujemy?

![capture](https://user-images.githubusercontent.com/15007183/29976709-ea6e5c60-8f08-11e7-8c46-9784a72f2532.PNG)

**Comment by xxcriticxx** [comment]
na tej nowej ver cookies mamy

![capture](https://user-images.githubusercontent.com/15007183/29976735-085a68d6-8f09-11e7-869b-0cfc0e379a68.PNG)

**Comment by xxcriticxx** [comment]
@gzenio22 cos dla siebie znajdziesz tutaj:

https://player.pl/bajki-dla-dzieci/male-krolestwo-bena-i-holly-odcinki,4946/?pl_source=driver_10

**Comment by hawkeye116477** [comment]
Ciastka: `player.pl##.cBox`.
Widzę, że mechanizmy wykrywające blokery podmienili i chyba trzeba będzie napisać do pingwina, jeśli chcecie nadal oglądać. Choć ja tam mam TVN Player w TV, więc nie potrzebuje tego na stronie.
