### ISSUE TITLE
Flarrow.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3461]
Resztki po reklamach z prawej strony

Flarrow.pl##.td-pb-border-top.td_uid_8_59a95008bcf03_rand
Flarrow.pl##.td-pb-border-top.td_uid_9_59a95008c5f96_rand.td_block_widget.td_block_text_with_title.td_block_wrap > .block-title

Ta 2 przydala by sie krotsza ale kurde ja nie widze jak to zrobic

**Comment by xxcriticxx** [comment]
@gzenio22 uzyj inspect element (Q)

![capture](https://user-images.githubusercontent.com/15007183/29976922-b5f54c2c-8f09-11e7-8748-f9eb055cd4c6.PNG)

**Comment by gzenio22** [comment]
Opera :D

**Comment by xxcriticxx** [comment]
@gzenio22 Opera Dragonfly is built right into the browser and updates automatically behind the scenes. Launch Opera Dragonfly with Ctrl + Shift + I on Windows and Linux, or ⌘ + ⌥ + I on Mac. Alternatively, you can target a specific element by right-clicking in the page and selecting “Inspect Element”.

**Comment by gzenio22** [comment]
@xxcriticxx tak wiem mam to wbudowane ale u mnie nie ma opcji inspect element q

**Comment by MajkiIT** [comment]
flarrow.pl##[class^="td_block_wrap td_block_text_with_title td_uid_"]

**Comment by xxcriticxx** [comment]
DOM and Style Inspector press Ctrl + Shift + C albo F12 i zakladka Inpector
