### ISSUE TITLE
e-konkursy.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3463]
![capture](https://user-images.githubusercontent.com/15007183/29981602-3c84f6c2-8f1c-11e7-9fce-11a76d2b1b7d.PNG)

**Comment by MajkiIT** [comment]
Ja nic takiego nie widzę.

**Comment by xxcriticxx** [comment]
pigwina mialem wylonczony teraz jest git zamykam
