### ISSUE TITLE
jasnet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3470]
![capture](https://user-images.githubusercontent.com/15007183/30004564-e75f6fbc-909f-11e7-8e98-ed4bb391ae7c.PNG)

**Comment by gzenio22** [comment]
jasnet.pl###adBox1

**Comment by MajkiIT** [comment]
@gzenio22 Dzięki. Jak możesz wyślij do mnie maila, bo mam do ciebie sprawę.
