### ISSUE TITLE
mvno-gsm.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3471]
![capture](https://user-images.githubusercontent.com/15007183/30004601-75221110-90a0-11e7-8eca-e15e7757ba6f.PNG)

**Comment by gzenio22** [comment]
mvno-gsm.pl###colormag_featured_posts_vertical_widget-8 > .first-post > .clearfix.single-article > figure

dlugie kurde...

**Comment by blocker999** [comment]
@xxcriticxx  Niewiem czy to reklama czy tylko info o promocji ?

**Comment by xxcriticxx** [comment]
tez niewiem

**Comment by MajkiIT** [comment]
kieruje do ich artykułu. Może zostawmy.
