### ISSUE TITLE
kobieta.onet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3474]
dziala wam tutaj galeraia?

https://kobieta.onet.pl/dziecko/pierwszy-dzien-w-szkole-zdjecia-przed-i-po-obnazaja-prawde/jb3fsk3

**Comment by HateAds** [comment]
@xxcriticxx Nawet przy wyłączonym adblocku nie działa :smiley:

**Comment by xxcriticxx** [comment]
ulubiona strona versia 2
