### ISSUE TITLE
beko.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3476]
menu sie zacina 

![capture](https://user-images.githubusercontent.com/15007183/30030419-23d1d686-915b-11e7-827a-f8d145b52ea8.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Menu się nie zacina, ale raczej w ogóle nie w tym miejscu co powinno wylądowało.
`beko.pl##.cookies-margin:style(top: 0px!important;)`
