### ISSUE TITLE
biznesnafali.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3477]
reklama

![capture](https://user-images.githubusercontent.com/15007183/30031080-17ff1afa-915e-11e7-82ed-293fc621cfef.PNG)

**Comment by gzenio22** [comment]
biznesnafali.pl##.no-border-bottom.vc_align_center
biznesnafali.pl##.vc_align_center.wpb_content_element.wpb_single_image:nth-of-type(3)

Kurde zerknijcie czy reg nr 1 nie ukrywa za duzo? mam zle przeczucia Xd

**Comment by MajkiIT** [comment]
`biznesnafali.pl##[target="_blank"] > .vc_single_image-img.attachment-full`
