### ISSUE TITLE
sklepbiegowy.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3478]
cookies

![capture](https://user-images.githubusercontent.com/15007183/30031569-1089f176-9160-11e7-9f98-93955685f66b.PNG)

**Comment by gzenio22** [comment]
sklepbiegowy.com##body > div:nth-of-type(1)

**Comment by hawkeye116477** [comment]
Albo `sklepbiegowy.com##div[style="background: rgb(73, 73, 73); color: rgb(255, 255, 255); font-size: 10px; font-family: sans-serif; position: fixed; bottom: 0px; left: 0px; padding: 10px 15%; opacity: 0.9; z-index: 9999; line-height: 18px;"]`
Można jeszcze tak:` sklepbiegowy.com##body > div:not([id]):not([class])`

**Comment by xxcriticxx** [comment]
@hawkeye116477 number 2 please
