### ISSUE TITLE
se.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3480]
dziala wam ta strona

http://www.se.pl/seks/porady/pupka-jak-marzenie-zobacz-najlepsze-tyleczki-ever-zdjecia_407343.html

**Comment by FadeMind** [comment]
Po wejściu na http://www.se.pl/seks/ a następne na Twój link strona działa. Bez tego popup o +18 dostaje pętli.

**Comment by MajkiIT** [comment]
Nawet bez blokowania reklam nie działa prawidłowo.

**Comment by xxcriticxx** [comment]
coraz gorsze te strony internetowe
