### ISSUE TITLE
drabex.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3481]
cookie ale chyba static 

![capture](https://user-images.githubusercontent.com/15007183/30032373-88795318-9163-11e7-8b89-6adf50879e18.PNG)

**Comment by FadeMind** [comment]
Static
![image-20170904-004](https://user-images.githubusercontent.com/9846948/30032743-e1503a7c-9197-11e7-8136-a570728f878a.png)

**Comment by hawkeye116477** [comment]
`drabex.com###footer`
