### ISSUE TITLE
reedukacja.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3482]
cookies + reklama 

![capture](https://user-images.githubusercontent.com/15007183/30032479-215b8060-9164-11e7-8623-6730b141fc4d.PNG)

**Comment by hawkeye116477** [comment]
`reedukacja.pl##div[style^="text-align: center; background: #FFF7BD; font-size: 10pt; color: #000; padding: 15px;"]`

**Comment by MajkiIT** [comment]
`reedukacja.pl###ctl00_divAdverts`
