### ISSUE TITLE
sklepkoszykarza.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3484]
cookies

![capture](https://user-images.githubusercontent.com/15007183/30032537-771d1e50-9164-11e7-838e-48dd4185b453.PNG)

**Comment by hawkeye116477** [comment]
`sklepkoszykarza.pl##div[style="background: rgb(73, 73, 73); color: rgb(255, 255, 255); font-size: 12px; font-family: sans-serif; position: fixed; bottom: 0px; left: 0px; padding: 10px 15%; opacity: 0.9; z-index: 9999; line-height: 18px;"]`

**Comment by hawkeye116477** [comment]
`sklepkoszykarza.pl##div[style="background: rgb(73, 73, 73); color: rgb(255, 255, 255); font-size: 12px; font-family: sans-serif; position: fixed; bottom: 0px; left: 0px; padding: 10px 15%; opacity: 0.9; z-index: 9999; line-height: 18px;"]`
albo
`sklepkoszykarza.pl##body > div:not([id]):not([class])`

Co o tym sądzisz @MajkiIT, które lepsze ?

**Comment by MajkiIT** [comment]
Hmmm wydaje mi się, że 2, bo jest bardziej ogólna
