### ISSUE TITLE
truckstore.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3487]
cookies

https://www.truckstore.com/PL/pl/uslugi/export.html

![capture](https://user-images.githubusercontent.com/15007183/30033686-a2dcebdc-916a-11e7-8fbc-29cc975eeeff.PNG)

**Comment by hawkeye116477** [comment]
```
truckstore.com##.tso-popup-footer
truckstore.com##.tso-popup-overlay
```
@xxcriticxx To ty tyle pobrań dziś nabiłeś? :smiley:.
![screenshot_20170904_184726](https://user-images.githubusercontent.com/19818572/30034421-92980694-91a1-11e7-9bd4-a5a78c8bb7b2.png)

**Comment by xxcriticxx** [comment]
@hawkeye116477 myslalem ze na ciebie nie mozna liczyc bo szkola sie znowu zaczela

**Comment by hawkeye116477** [comment]
@xxcriticxx Ja mam dopiero od października, gdyż jestem studentem,

**Comment by xxcriticxx** [comment]
aha to trzeba cie wykorzystac jeszcze troche

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale szalejesz, dzisiaj rekord pobiliśmy 😺  Ale tak na poważnie to pobierałeś już WF z mojego repo?
![screenshot_20170904_200402](https://user-images.githubusercontent.com/19818572/30035616-676307a2-91ac-11e7-9718-de3d509e0eb8.png)

**Comment by xxcriticxx** [comment]
Tak 75 razy tak jak graf pokazuje

**Comment by hawkeye116477** [comment]
@xxcriticxx Ogólnie z USA 63 pobrań, więc nie bajeruj, a to śmieszek 😸 . A z Polski, słabo, tylko 6 i pewnie większość to ja, sprawdzałem czy dobrze się ściąga.
