### ISSUE TITLE
dhl.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3494]
cookies

http://www.dhl.com.pl/pl.html

Stosujemy pliki cookie na naszej stronie internetowej. Pliki cookie są stosowane do poprawy działania i korzystania z naszej strony Internetowej, a także dla celów analitycznych i reklamowych. Aby dowiedzieć się więcej na temat plików cookie, sposobu ich wykorzystania oraz sposobu zmiany ustawień cookie, dowiedz się więcej tutaj. Korzystając z tej strony bez zmiany ustawień, wyrażasz zgodę na stosowanie plików cookie.

![capture](https://user-images.githubusercontent.com/15007183/30071540-10c2add8-9235-11e7-92be-ff4944aa972b.PNG)

**Comment by hawkeye116477** [comment]
Oczywiście konkurencja z I don't care about cookies już to ma: `##.dhl-cgk:not(body):not(html)` :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 mozna by bylo wszystkie polskie adresy pozyczyc ten projekt jest chyba dead

**Comment by hawkeye116477** [comment]
@xxcriticxx Polskie adresy już od nich chyba wszystkie pożyczyłem oprócz tego DHLa. Nie sądziłem, że ten projekt jest już dead, ostatni update był: 2017-07-25, ale oni mają tam sporo tych reguł, dużo więcej od Fanboyów, więc może ten co się tym zajmuje, uznał, że tyle na razie starczy i zrobił sobie wakacje :smiley:.

**Comment by hawkeye116477** [comment]
@xxcriticxx Polskie adresy już od nich chyba wszystkie pożyczyłem oprócz tego DHL'a. Nie sądziłem, że ten projekt jest już dead, ostatni update był: 2017-07-25, ale oni mają tam sporo tych reguł, dużo więcej od Fanboyów, więc może ten co się tym zajmuje, uznał, że tyle na razie starczy i zrobił sobie wakacje :smiley:.

Mogłem jeszcze coś tam pominąć, gdyż pewnie jakieś tam reguły ogólne mogą działać na polskie strony, ale nie wiadomo które, a chciałem dodać wszystkie ogólne z IDCAC, których w naszym filtrze nie ma, ale @MajkiIT mówi, że w takim układzie lepiej korzystać z obu filtrów.

**Comment by xxcriticxx** [comment]
@hawkeye116477 ktoras lista byla dead moe IDCAC gdzies cos czytalem. mysle ze mozna by bylo poszukac duzych firm (dhl) i je tutaj dodac

@MajkiIT sluchamy opini na temat

**Comment by MajkiIT** [comment]
@xxcriticxx Możemy wysupłać co się nam przyda, ale nie chciałbym wrzucać wszystkiego na siłę, bo zrobi się lekki śmietnik. 

@hawkeye116477 nie wiem czy ona jest dead, bo może ktoś wypuszcza update bardzo rzadko. Poczekajmy jeszcze chwilę .... może na prawdę jest dead.

**Comment by xxcriticxx** [comment]
@MajkiIT poczekamy

**Comment by hawkeye116477** [comment]
@MajkiIT Ja tam myślę, że gość sobie zrobił wakacje, bo i tak jego lista jest spora.

**Comment by xxcriticxx** [comment]
@hawkeye116477 tak jak pisalem bys wylapal wieksze firmy i korporacje

**Comment by hawkeye116477** [comment]
@xxcriticxx O tej liście, co piszesz, że była dead, to zapewne chodzi o EU:Prebake - Filter Obtrusive Cookie Notices, gorhill już dawno powinien to podmienić, już rok aktualizacji nie ma. Sugerowali więc ludzi, by dodał I don't care albo Fanboy's Cookiemonster, ale gorhill powiedział, że I don't care raczej odpada, bo twórca twierdzi, że jego własne rozszerzenie jest lepsze niż uBlock czy tam Adblock.
