### ISSUE TITLE
możecie sprawdzić? (vidoza.net)

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3495]
Czy możecie sprawdzić na linku poniżej /player vidoza.net/ czy przy odpaleniu filmu wyskakuje Wam POPup co jest spowodowane przez regułę `@@||vidoza.net/js/pop.js$script`

http://cda-hd.pl/18074/transformers-ostatni-rycerz-transformers-the-last-knight-2017-online/

**Comment by FadeMind** [comment]
Nie pojawia mi się żaden Popup.

**Comment by MajkiIT** [comment]
masz ?
`AAK-Cont Filter For uBlock Origin`

**Comment by FadeMind** [comment]
@MajkiIT przypominam: mam Adguard a on ma własne wewnętrzne reguły blokujące >> https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/antiadblock.txt
https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/antiadblock.txt

**Comment by HateAds** [comment]
@MajkiIT U mnie działa normalnie.

**Comment by FadeMind** [comment]
@MajkiIT  CSS jest rozwalony
![image-20170905-009](https://user-images.githubusercontent.com/9846948/30078362-3bb52988-927d-11e7-8c1a-57667046aa9c.png)

**Comment by MajkiIT** [comment]
@FadeMind a to poprawia CSSa ? `cda-hd.pl##.s_left`

**Comment by FadeMind** [comment]
`cda-hd.pl##.s_left` nie poprawia CSSa.

**Comment by MajkiIT** [comment]
@FadeMind mój błąd powinno być `cda-hd.pl#@#.s_left`

**Comment by FadeMind** [comment]
![image-20170905-010](https://user-images.githubusercontent.com/9846948/30079863-f327cdba-9281-11e7-8415-43fe77e22860.png)

Dziękuję

**Comment by xxcriticxx** [comment]
@MajkiIT css dziala z ta regula tak jak @FadeMind pisal 

bez aak wyskakuje okno ale szybko znika z aak niema tekiego problemu

**Comment by MajkiIT** [comment]
@FadeMind @HateAds @xxcriticxx 
Dzięki
