### ISSUE TITLE
tv-wschod.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3497]
Po prawej stronie są resztki po reklamach.

**Comment by MajkiIT** [comment]
`tv-wschod.pl##[class*="advert"]`

**Comment by hawkeye116477** [comment]
`tv-wschod.pl##section.container:style(padding-top: 0px!important;)` - zbędny odstęp na górze

**Comment by hawkeye116477** [comment]
@MajkiIT A co z resztkami?
