### ISSUE TITLE
tv-wschod.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3500]
@MajkiIT Zostały resztki:
`tv-wschod.pl##section.container:style(padding-top: 0px!important;)` - zbędne wolne miejsce na górze
`tv-wschod.pl##.widget:style(margin: 10px -15px 0 0!important;)` - poprawa marginesów po prawej stronie (było 30, zmieniłem na 10, chyba tak powinno być ok, można dać też na 0, ale nie wiem czy napis pogoda nie będzie trochę za blisko)

**Comment by MajkiIT** [comment]
U mnie jest ok i dlatego pominąłem to...
@xxcriticxx zerkniesz u siebie?

**Comment by hawkeye116477** [comment]
@MajkiIT 

Przed
![screenshot_20170907_153502](https://user-images.githubusercontent.com/19818572/30166092-8f61bbb2-93e2-11e7-8c81-96a4fa53c4b6.png)


Po
![screenshot_20170907_153630](https://user-images.githubusercontent.com/19818572/30166026-60c29dbc-93e2-11e7-963c-8fba474a82b7.png)

**Comment by xxcriticxx** [comment]
@MajkiIT mam tak jak na zdjeciu u @hawkeye116477
