### ISSUE TITLE
iiv.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3503]
cookies

![screenshot from 2017-09-08 06-44-14](https://user-images.githubusercontent.com/15007183/30208376-28c94558-9461-11e7-93af-7eb9f0321210.png)

**Comment by gzenio22** [comment]
u mnie czysto Xd

**Comment by xxcriticxx** [comment]
zajebiscie znowu mi filtry nie dzialaja?

**Comment by xxcriticxx** [comment]
clerowalem browsing historie i znowu mam 

![screenshot from 2017-09-08 06-57-30](https://user-images.githubusercontent.com/15007183/30208787-03c80e7c-9463-11e7-9e4c-511796e4b9ea.png)

**Comment by gzenio22** [comment]
@hawkeye116477 @MajkiIT 

Zerknijcie u mnie serio czysto :D

**Comment by hawkeye116477** [comment]
@gzenio22 To się pojawiło zapewne dlatego, że @xxcriticxx dodał generichride, co spowodowało, że wyłączyly się wszystkie reguły ogólne dla tej strony, pomaga to niby na „adblock detect", tyle, że ja tam nie widziałem wcześniej „adblock detect", więc nie wiem czy to konieczne.
`iiv.pl###cookie-info-container`

**Comment by gzenio22** [comment]
@hawkeye116477 ja tez nie widze adblock detect wiec mysle ze to zbedne ale decyduje wiekrzosc

**Comment by xxcriticxx** [comment]
@hawkeye116477 doklanie zdjelem reguly z generchride i jest gitara

**Comment by hawkeye116477** [comment]
Adblock detect pojawia się z wyłączonym skryptem AAK Cont lub wyłączonym rozszerzeniem uBlock Protector, więc ci co ich nie mają lub korzystają z Adguarda to mogą mieć problem. Czyli jednak whitelist generichride chyba będzie konieczny.

**Comment by hawkeye116477** [comment]
@MajkiIT @xxcriticxx Skoro generichride nie dodaliśmy, to w takim razie to jest raczej do zamknięcia.
