### ISSUE TITLE
tvregionalna.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3505]
bannery top i bottom maybe?

**Comment by gzenio22** [comment]
Jezeli to zdejme to poleci tez logotyp strony albo ja mam cos innego niz ty

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale to są bannery informujące, że w ich TV będzie mecz, więc nie blokujemy. Temat do zamknięcia.

**Comment by xxcriticxx** [comment]
to jakies darmowe tv dlatego
