### ISSUE TITLE
cardsplitter.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3506]
Hmmm zdejmujemy chyba tego łosia nie? :D 

cardsplitter.pl##img[src="/images/loga/cuk-01.jpg"]

**Comment by MajkiIT** [comment]
`cardsplitter.pl##[target="_blank"] > IMG[src^="/images/loga/"][height="249"]`

**Comment by hawkeye116477** [comment]
@MajkiIT Jeszcze po tym zostaje puste miejsce -> `cardsplitter.pl##center > center:nth-of-type(1)`

**Comment by hawkeye116477** [comment]
@MajkiIT @blocker999 A to do sociala, resztka po Facebooku -> `cardsplitter.pl##center > center:nth-of-type(1)`

**Comment by xxcriticxx** [comment]
@gzenio22 za satelity sie bierzesz?
