### ISSUE TITLE
bluecity.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3510]
@blocker999 Facebook -> `##.toolbar-fb`

**Comment by gzenio22** [comment]
nie wiem czy plakac czy sie cieszyc ale zauwazyliscie ze ostatnio mamy mniej zabawy? :D

**Comment by xxcriticxx** [comment]
@gzenio22 do nikt nie podaje nowych issues

**Comment by gzenio22** [comment]
bo nikt nie biega po stronach ktore nie sa znane

**Comment by FadeMind** [comment]
@xxcriticxx  wypraszam sobie 😁

**Comment by blocker999** [comment]
@hawkeye116477 coś wymysle

@gzenio22 skoro się nudzisz to ściągnij tu jakich ludzi to i tematów przybędzie
