### ISSUE TITLE
kwejk.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3511]
Macie ten błąd?

https://screenshots.firefox.com/jdzGlD4XuIoT531f/www.facebook.com

**Comment by hawkeye116477** [comment]
@MajkiIT Tak

**Comment by hawkeye116477** [comment]
@MajkiIT Tak, ale to jest wina reguł z listy social, czyli znowu @blocker999 narozrabiał :smiley:.

**Comment by blocker999** [comment]
@hawkeye116477  w takim razie się temu przyjrze, @MajkiIT Zaraz się zato zabieram

**Comment by hawkeye116477** [comment]
@blocker999 Problemem jest ta reguła -> `pl##.plus`. Także nie wiem, może by dać jakiś wyjątek albo usunąć ją.

**Comment by MajkiIT** [comment]
@blocker999 @hawkeye116477 poprawione. Dzięki

**Comment by hawkeye116477** [comment]
@MajkiIT To nie ta reguła, jest jeszcze druga z kropką i to ta z kropką to właściwa.

**Comment by blocker999** [comment]
@MajkiIT Usuń jeszcze `pl##.fb` bo niepotrzebnie blokuje info o logowaniu przez facebooka
