### ISSUE TITLE
spidersweb.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3512]
http://www.spidersweb.pl
![image-20170909-001](https://user-images.githubusercontent.com/9846948/30238977-98e32fd8-9552-11e7-8b47-ccaca08f4667.png)
### Fix
```
spidersweb.pl##.mfp-wrap
```

**Comment by hawkeye116477** [comment]
@FadeMind To jest Popup, a więc zadanie dla @blocker999, choć on to już chyba dodał.
Także załaduj filtr https://raw.githubusercontent.com/azet12/PopupBlocker/master/PPB.txt.
