### ISSUE TITLE
filmosy.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3513]
obrazki wam sie laduja?

![capture](https://user-images.githubusercontent.com/15007183/30241335-78e2a5a4-954f-11e7-8f7b-99e2dc6e3e17.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx obrazki pochodzą z alltube np. to http://alltube.tv/static/normal/s1qw696zz6k9.jpg. U mnie jest ok.

**Comment by hawkeye116477** [comment]
@xxcriticxx U mnie też jest ok. Ale jeśli masz jakieś rozszerzenia „legacy",  to któreś z nich może sprawiać problem, tak przynajmniej twierdzi gorhill. Choć ja mam legacy All-in-One Sidebar, DownThemAll, Star-Button In Urlbar, Turbo Download Manager i żadne z nich nie sprawia problemów.

**Comment by xxcriticxx** [comment]
mam tylko ublock i ublock proctor

**Comment by hawkeye116477** [comment]
@xxcriticxx Na Firefoksie?

**Comment by xxcriticxx** [comment]
chrome

**Comment by xxcriticxx** [comment]
propblem rozwiozany musialem wesc an alltube i rozwiazac captcha

**Comment by FadeMind** [comment]
![image-20170909-003](https://user-images.githubusercontent.com/9846948/30241960-62f24004-958d-11e7-8605-cd1697820a0b.png)

**Comment by hawkeye116477** [comment]
@xxcriticxx Aha, a ja pisałem o lisku. Z Chrome korzystasz, Chromium nie lepszy, open-source? Choć jak dla mnie, to Vivaldi przebija obie przeglądarki :smile:.
A już chciałem napisać, że może komp się zestarzał i nie domaga. Słyszałem, że na takie stare kompy dobry jest Pale Moon.

**Comment by xxcriticxx** [comment]
wazne ze dziala
