### ISSUE TITLE
pihole

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3514]
@xxcriticxx 
Może zrobimy coś takiego dla PL filters?
https://www.reddit.com/r/pihole/comments/4p2tp7/adding_easylist_and_other_adblocklike_sources_to/

**Comment by xxcriticxx** [comment]
@MajkiIT jak zrobisz mi liste to przetestuje ale mysle ze moze za duzo blokowac

**Comment by xxcriticxx** [comment]
@MajkiIT czekam na liste

**Comment by MajkiIT** [comment]
chcesz jako link czy tutaj wrzucić?

**Comment by xxcriticxx** [comment]
link raw format

bendzie polska lista?

**Comment by MajkiIT** [comment]
`https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt`

**Comment by xxcriticxx** [comment]
@MajkiIT tylko 4 domeny?

**Comment by MajkiIT** [comment]
chwilowo tak

**Comment by xxcriticxx** [comment]
```
::: Getting raw.githubusercontent.com list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
```

**Comment by xxcriticxx** [comment]
```
Sep 11 16:22:08 dnsmasq[6029]: /etc/pihole/gravity.list ads.businessclick.com is 192.168.1.131
Sep 11 16:22:49 dnsmasq[6029]: /etc/pihole/gravity.list pubads.g.doubleclick.net is 192.168.1.131
Sep 11 16:22:50 dnsmasq[6029]: /etc/pihole/gravity.list ad.doubleclick.net is 192.168.1.131
```

**Comment by xxcriticxx** [comment]
a tak wyglonda browser 

![screenshot from 2017-09-11 16-24-50](https://user-images.githubusercontent.com/15007183/30295231-de0006c4-970d-11e7-9388-904bf2f9e8ba.png)

**Comment by xxcriticxx** [comment]
@MajkiIT na routerze masz to samo poco tobie pihole

**Comment by MajkiIT** [comment]
aby się nauczyć i potestować.

**Comment by xxcriticxx** [comment]
@MajkiIT masz takie hobby?

**Comment by MajkiIT** [comment]
tak, dlatego w domu mam kupę sprzętu :P

**Comment by xxcriticxx** [comment]
Ok teraz wiadomo kto po śmietnikach nurkuje

**Comment by MajkiIT** [comment]
:P nikt chyba nie wyrzuca sprzętu za kilka tysięcy na śmietnik, ale jak wiesz gdzie taki wyrzucają to daj namiary :D

**Comment by xxcriticxx** [comment]
@MajkiIT new york city!

**Comment by MajkiIT** [comment]
@xxcriticxx really? no to kupuję bilet i przygotuj listę najlepszych miejsc gdzie tak wyrzucają :D

**Comment by xxcriticxx** [comment]
@MajkiIT ten `ppstatic.pl` moze na liste dodac?

**Comment by MajkiIT** [comment]
@xxcriticxx Właśnie się boję, bo to jakiś hosting `https://d-pt.ppstatic.pl/k/r/1/2d/7e/57024ddae1ffd_p.jpg?1459788683 `

**Comment by xxcriticxx** [comment]
super sprawa

**Comment by xxcriticxx** [comment]
@MajkiIT dziala tobie na ubuntu?

**Comment by MajkiIT** [comment]
tak, a coś miało nie działać?

**Comment by xxcriticxx** [comment]
tak sprawdzam tylko
