### ISSUE TITLE
magazynbasista.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3517]
reklama prawa strona

**Comment by MajkiIT** [comment]
u mnie pusto

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/30242153-3b1fdc54-955f-11e7-81ed-28406d55aa76.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx @MajkiIT 
Reklama -> `magazynbasista.pl###text-6`
Partnerzy -> `magazynbasista.pl###text-8`
Social -> `magazynbasista.pl###text-9`
