### ISSUE TITLE
dogizycka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3530]
![capture](https://user-images.githubusercontent.com/15007183/30242738-32134406-956a-11e7-83b9-53e3d9600580.PNG)

**Comment by hawkeye116477** [comment]
Serio, znowu to samo co #3520, co oni nie mogą wymyślić czegoś lepszego :smiley:?

**Comment by MajkiIT** [comment]
to gotowy skrypt :P
