### ISSUE TITLE
andy-academy.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3536]
cookies

![capture](https://user-images.githubusercontent.com/15007183/30243191-8bc788ec-9572-11e7-8ec1-72594f390ec6.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Co ty znowu avastujesz? Nie widzę tych ciastek nawet z wyłączonym uBlockiem.

**Comment by hawkeye116477** [comment]
http://www.andy-academy.com/wydarzenia.html
