### ISSUE TITLE
siemianowice.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3543]
cookies

![screenshot from 2017-09-10 07-44-07](https://user-images.githubusercontent.com/15007183/30248745-eece6846-95fb-11e7-8d36-6b252db1632c.png)

**Comment by hawkeye116477** [comment]
@xxcriticxx To samo co #3542, ewentualnie pewnie można coś wykombinować ze stylem, ale style zawsze się mogą zmienić, więc chyba tak będzie lepiej.
