### ISSUE TITLE
efilmy.online

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3549]
Możecie zerknąc czy na stronie https://efilmy.online/gwiezdne-wojny-historie-lotr-1/11541/ po wciśnięciu play macie popup ?

**Comment by hawkeye116477** [comment]
@MajkiIT Nie ładnie, zamiast obejrzeć w Netflixie albo kupić w Empiku, Merlinie czy cdp, to piraci :smile:.

**Comment by MajkiIT** [comment]
@hawkeye116477 a ty jak sie do mnie nie przyczepisz do żyć nie możesz :D . Ja kupuje filmy i patrzę czy w necie jest to samo  :) . Wiesz ile mnie nerwów kosztuje wyszukiwanie różnic :D

**Comment by hawkeye116477** [comment]
@MajkiIT Ok, spoko, hehe :smiley:.
Przy okazji, jest sprawa do obgadania -> https://github.com/MajkiIT/polish-ads-filter/pull/3541.

**Comment by xxcriticxx** [comment]
@MajkiIT tak mnie przekerowalo 

`https://vdtrack.com/PTZ5dc?sub_id_1=35937e34256cf4e5b2f7da08871d2a0b&sub_id_2=efilmy.online`

**Comment by hawkeye116477** [comment]
@MajkiIT Ok, spoko, hehe :smiley:. 
Mam popup.
Przy okazji, jest sprawa do obgadania -> https://github.com/MajkiIT/polish-ads-filter/pull/3541.

**Comment by MajkiIT** [comment]
to wina  tego @@||vidoza.net/js/pop.js$script . jak zablokuje to jest adblock.
