### ISSUE TITLE
otodom.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3550]
https://www.otodom.pl/oferta/mieszkanie-lublin-krysztalowa-46-25m-ID3lSoo.html#gallery[1]

`
  ||urbanone-widget.pl/widget/`

**Comment by xxcriticxx** [comment]
@MajkiIT no more warszawa?

**Comment by MajkiIT** [comment]
nie, spokojnie. Link znalazłem na FB i popatrzyłem kontrolnie i znalazłem :D
