### ISSUE TITLE
brainly.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3551]
adblock???

https://brainly.pl/zadanie/13826822

![screenshot from 2017-09-10 09-16-22](https://user-images.githubusercontent.com/15007183/30249355-e08673ca-9608-11e7-84e5-b6d00ceada3f.png)

**Comment by MajkiIT** [comment]
`brainly.pl##.brn-ads-box--billboard.brn-ads-box`
