### ISSUE TITLE
AAK by Reek

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3556]
https://github.com/gorhill/uBlock/commit/651da7157ae2962062d9f20002fe1d3dd86a506b

Gorhill usunął Reeka

**Comment by hawkeye116477** [comment]
@MajkiIT To bardzo dobrze, jeszcze Prebake powinien usunąć. A dodać powinien I don't care about cookies i/lub Fanboy's Cookiemonster i AAK Cont dla niechromowych przeglądarek.

**Comment by MajkiIT** [comment]
@hawkeye116477 mówisz i masz :D https://github.com/gorhill/uBlock/issues/2997

**Comment by hawkeye116477** [comment]
@MajkiIT Nie musiałeś pisać, już to inni pisali, a gorhill wciąż się chyba zastanawia czy to usunąć, a jeżeli tak, to czym zastąpić, bo facet z I don't care about cookies zaleca by korzystać z jego rozszerzenia, bo niby adbloki mają limity i wszystkiego nie zablokują „Be aware that it can not be as good as a real browser extension due to technical limitations of ad blocking software but it will cover 99% of cookie warnings.". No tyle, że przecież uBlock zalicza się do innej kategorii... :smile:.

**Comment by MajkiIT** [comment]
@hawkeye116477 po prostu podbiłem temat :P

**Comment by hawkeye116477** [comment]
https://github.com/gorhill/uBlock/issues/1609

**Comment by hawkeye116477** [comment]
@MajkiIT A co z naszymi filtrami? Trzeba napisać, niech doda PopupBlockera, bo za mało chwali i za mało osób narzeka :smiley:. Social i ciastka też chyba powinny tam trafić.

https://github.com/gorhill/uBlock/issues/1609
Fanboya niechce dodać, bo niby jest już Annoyance, ale w sumie idąc tym tropem, to po co jest Ultimate w takim razie, a nawet gdyby to nie każdy chce blokować to wszystko, niektórzy wolą tylko ciastka :smile:.

**Comment by MajkiIT** [comment]
a co powiesz o tym ?
https://github.com/r4vi/block-the-eu-cookie-shit-list/blob/master/filterlist.txt

**Comment by hawkeye116477** [comment]
@MajkiIT Była już dyskusja o tym i zdaje się, że oni za mocne reguły dodają.
https://github.com/gorhill/uBlock/issues/103

**Comment by hawkeye116477** [comment]
@MajkiIT Była już dyskusja o tym i zdaje się, że oni za mocne reguły dodają. Ja raczej jestem za Fanboyami, gdyż I don't care jest niepewny, nie wiadomo czy facet będzie nadal aktualizował czy też nie.
https://github.com/gorhill/uBlock/issues/103

**Comment by MajkiIT** [comment]
@hawkeye116477 Dzięki

**Comment by MajkiIT** [comment]
@hawkeye116477 widzisz udało się :p

**Comment by hawkeye116477** [comment]
@MajkiIT Jeszcze przydałoby się jakby więcej polskich filtrów dodał, to więcej ludzi by o nich wiedziało i pewnie więcej zgłoszeń by spływało: Bo na razie to u blockera z PopupBlockerem słabo, tylko 1 osoba narzeka, no może jeszcze ja od czasu do czasu ponarzekam :smiley:.

**Comment by MajkiIT** [comment]
Gorhill nie doda tego, ale spróbuje napisać do niego. Jak się nie uda to może promocja na FB?

**Comment by hawkeye116477** [comment]
@MajkiIT Ok, a skąd wiesz, że nie doda, co ty takim pesymistą jesteś? Może jeśli więcej Polaków podpisze się pod tym, to wtedy może doda :smile:.

**Comment by MajkiIT** [comment]
Bo jak doda polskie filtry, to odezwą się kolejni :P

**Comment by hawkeye116477** [comment]
@MajkiIT A Ruskie i Chińczyki mają po 3 filtry i jeden z nich to typu annoyances 😛 . Także myślę, że gorhill powinien dodać też nasz typu annoyances, czyli PopupBlocker.

**Comment by MajkiIT** [comment]
@hawkeye116477 to zgłosić 
1. ciasteczka 
2. Popupblocker

@blocker999 chcesz aby dodać twoje filtry?

**Comment by hawkeye116477** [comment]
@MajkiIT Pytanie tylko czy blocker jest gotowy na większą krytykę? Jak teraz tak się denerwował, to boję się co dopiero będzie jak gorhill doda PopupBlocker i na GH przybędzie więcej osób.

**Comment by blocker999** [comment]
@MajkiIT TAK ale pod jednym warunkiem że @hawkeye116477 przyjmie propozycje wspópracy tzn równy dostęp do paczki na githubie by mógł bez mej zgody dowolnie ją modyfikować, @hawkeye116477 to jak?

**Comment by hawkeye116477** [comment]
@blocker999 Ok, zgadzam się. Ale pamiętaj, że jeśli gorhill doda PopupBlockera, to może się pojawić większa fala krytyki i trzeba będzie to wziąć na klatę :smile:.

**Comment by FadeMind** [comment]
`https://github.com/AdguardTeam/AdguardForWindows/issues/1923`

**Comment by hawkeye116477** [comment]
@blocker999 Tylko jeszcze jedno, ta współpraca rozumiem, że będzie się również opierać na tym, że będziesz konsultował wszystko ze mną przed dodaniem? No bo jeśli mamy współpracować, to chyba tak to powinno wyglądać.

**Comment by blocker999** [comment]
@hawkeye116477 OK to w takim razie formalności na maila a co do fali krytyki to już się boje no ale Ty też będziesz w to zamieszany, także uważaj.

@MajkiIT Teraz morzesz śmiało pisać do Gorhilla z prośbą o dodanie PopupBlockera, natomiast info o mej paczce dodaj jeśli ona pojawi sie w Ublocku.

**Comment by hawkeye116477** [comment]
@MajkiIT Nic z tego, gorhill nie doda PopupBlockera. A Chińczykom i Ruskim usunie 1 filtr, bo mają za dużo :smiley:.

> There is already two lists for Polish, I don't want to keep adding lists in there, it's a convenience for the lists which it makes sense to use for majority of users.

https://github.com/gorhill/uBlock/issues/3014

**Comment by blocker999** [comment]
@hawkeye116477 Trudno i żyje sie dalej, @MajkiIT może chociaż małe info na FB by było więcej zgłoszeń?

**Comment by MajkiIT** [comment]
@hawkeye116477 a nie mówiłem :P Luz damy radę

@blocker999 Ok jutro coś napiszę 👍

**Comment by hawkeye116477** [comment]
No to ładnie, Fanboye chyba sobie zrobili wakacje od ciasteczek, a I don't care widzę, że ruszył ponownie, 2 dni temu zrobił update :smile:.

**Comment by hawkeye116477** [comment]
@MajkiIT 
To zasugerował jeden z userów:
> You should attempt to make the creators of those Polish filters to work together on one of the already existing lists to avoid the fragmentation of your small community.

Więc można by połączyć oba filtry reklamowe w jeden, reguły ze style i tak są w końcu w głównym filtrze również. A zamiast tej specyficznej dla uBlocka zrobić jeden wielki filtr Annoyance, w którym byłyby reguły z PopupBlockera+Social+Cookies i to by trafiło do gorhilla zamiast tego supplement. Oczywiście pojedyncze filtry nadal byłyby. Przeszło by coś takiego czy to raczej słaby pomysł i lepiej nie kombinować :smile:?

**Comment by MajkiIT** [comment]
Już tak robiliśmy czyli połączyliśmy ublock z resztą i filtry z uBo powodowały problemy z Adblockiem. A co do połączenia to znowu będzie Burza, że on chce tylko ciastka itp . Już chciałem dodać do PL Popup i dostałem wrzask. Niestety weź pod uwagę, że teraz z tych filtrów korzysta 6 mln ludzi .... :( po ataku WP dostałem w ciągu 24h 200 maili ponad...

**Comment by hawkeye116477** [comment]
@MajkiIT Mi raczej chodziło o to, że nadal zostaną oddzielne listy, ale będzie też połączona, która trafi do uBlocka. Ale skoro filtry z uBlocka powodują problemy z Adblockiem, no to w takim razie, chyba parę filtrów z głównej listy będzie do przeniesienia do tej uBlockowej, bo tam są też filtry style i script:inject, a Adblock tego nie obsługuje, tak?

**Comment by hawkeye116477** [comment]
@MajkiIT Mi raczej chodziło o to, że nadal zostaną oddzielne listy, ale będzie też połączona, która trafi do uBlocka. Ale skoro filtry z uBlocka powodują problemy z Adblockiem, to ok, zamykam temat.

**Comment by MajkiIT** [comment]
ublock to tylko kawalek ... zrobimy kampanie na wszysstkie blockery

**Comment by blocker999** [comment]
@MajkiIT Proponuje Billboardy : 

![billboard-crop](https://user-images.githubusercontent.com/23176832/30511015-4e92762c-9ad0-11e7-9ff9-312a5f11902c.jpg)

**Comment by MajkiIT** [comment]
@hawkeye116477 na bilbordy mnie nie stać, ale myślałem o ==> https://certyficateit.cupsell.pl/k/all

**Comment by hawkeye116477** [comment]
@All Gorhill stwierdził, że uBlock nie powinien promować własnościowego oprogramowania jakim jest Google Chrome, więc usunął filtr bezlotka, a zamiast niego dał AAK Cont. Kto się cieszy z tego powodu? 😃 
https://github.com/gorhill/uBlock/commit/dec5e3e839044bdb724456faaf2ed1bf0292c729

**Comment by hawkeye116477** [comment]
@All Gorhill stwierdził, że uBlock nie powinien promować Google Chrome kosztem Firefoksa, więc usunął filtr bezlotka, a zamiast niego dał AAK Cont. Kto się cieszy z tego powodu? 😃 
https://github.com/gorhill/uBlock/commit/dec5e3e839044bdb724456faaf2ed1bf0292c729

**Comment by MajkiIT** [comment]
ja już się pogubułem

**Comment by hawkeye116477** [comment]
@MajkiIT W czym? Jeszcze gorhill usunął ruskom jeden filtr, bo mieli za dużo 😃 . Jeszcze za Koreańczyków i Chińczyków powinien się wziąć, bo oni mają po 3 listy, a my tylko 2, gdzie tu sprawiedliwość 😃 .
