### ISSUE TITLE
cmjordan.krakow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3559]
![capture](https://user-images.githubusercontent.com/15007183/30252384-64ebfa28-963f-11e7-8e3e-855752ce852c.PNG)

**Comment by gzenio22** [comment]
cmjordan.krakow.pl##body > div

**Comment by hawkeye116477** [comment]
Tak chyba będzie bezpieczniej:
`cmjordan.krakow.pl##body > div:not([id]):not([class])`

**Comment by xxcriticxx** [comment]
@hawkeye116477 te cookies sa dobre bo patrze ze mi znowu ublock na foxie sie wylaczyl
