### ISSUE TITLE
tabletkinaerekcjepl.pw

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3565]
![capture](https://user-images.githubusercontent.com/15007183/30252467-29d81bc2-9641-11e7-94be-1c54254cb809.PNG)

**Comment by gzenio22** [comment]
a tutaj cos nowego nie moge zaznaczyc pola odrazu mi cala strone zaznacza :D doobre jaja

**Comment by MajkiIT** [comment]
bo to frame :D a poza tym to fake. Wrzucam do KAD
