### ISSUE TITLE
npa.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3566]
cookies

**Comment by gzenio22** [comment]
tutaj z kolei mi cala strone wywala przy aktywnym ublocku a jak mam wylaczonego to hula normalnie

**Comment by hawkeye116477** [comment]
@gzenio22 Wywala stronę, bo to @blocker999 robi jakieś testy... robienia sobie jaj :smiley:. Trzeba będzie to wywalić z sociala -> `pl##.test`.
@blocker999 chłopie, przystopuj z tymi ogólnymi pl, dawaj dopiero jak będzie to samo na co najmniej 10 stronach albo jak u konkurencji będą mieli podobną regułę jako ogólną :smile:. 

Tak czy siak, to samo co #3560.

**Comment by blocker999** [comment]
@hawkeye116477 Jak znajdziesz. jakiś darmowych pszeszukiwaczy którzy przejrzą 3mln ston, wyłapią i posegregują je to spoko naawet i od 20 zrobie, albo wykasuje połowe listy, co?

**Comment by gzenio22** [comment]
@blocker999 Spokojnie lekkim wkurw** zalecialo

**Comment by hawkeye116477** [comment]
@blocker999 Po prostu nie dawaj od razu ogólnej jak zobaczysz tylko na paru stronach, bo to może zrobić więcej pożytku niż szkody. Trochę ostrożniej. „Ostrożności nigdy nie za wiele". No i przede wszystkim ogólne ja bym dał na pewniejsze nazwy, a nie na nazwy typu „test". To nic, że od razu nie zablokujesz tych 3 milionów stron, lepiej mniej, a bez skutków ubocznych w sporej ilości. 

@MajkiIT Chyba też nieco jest z tym ostrożniejszy. Prawda @MajkiIT?

**Comment by MajkiIT** [comment]
@hawkeye116477 ja stałem się ostrożniejszy, bo z PL filtrów korzysta ok 6 mln ludzi i jak popełnię błąd to potem mam mailing, że coś nie działa. Ponadto sam wiesz jak mnie łapiesz na błędach i wiem, że nie raz je popełnię. 

@blocker999 nie denerwuj się, bo nie ma to sensu najmniejszego. Jeśli chcesz to możemy wrzucić na FB post, że szukasz pomocnika/testera filtrów. Co ty na to?

**Comment by gzenio22** [comment]
@MajkiIT  Poszło

**Comment by hawkeye116477** [comment]
@MajkiIT Czasem cię łapię, to prawda, ale u blockera to naprawdę wydaje mi się, że jest to jakość częściej, dlatego proszę go, żeby był ostrożniejszy.

**Comment by MajkiIT** [comment]
@hawkeye116477 to ja przepraszam ze swojej strony i obiecuję poprawę :( ....

**Comment by hawkeye116477** [comment]
@MajkiIT Nic nie szkodzi, nie robisz tak często błędów. To chyba raczej powinien powiedzieć @blocker999, ale nie chce to trudno, dobrze, że chociaż zgodził się by konsultować niepewności ze mną.
