### ISSUE TITLE
portaltatrzanski.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3581]
cookies

**Comment by gzenio22** [comment]
Cookies brak za to ubezpiecz sie 

portaltatrzanski.com###k2ModuleBox419

**Comment by hawkeye116477** [comment]
Potwierdzam

**Comment by hawkeye116477** [comment]
@MajkiIT Label social można już zdjąć, została tylko reklama.

**Comment by hawkeye116477** [comment]
@MajkiIT Może tak będzie lepiej: `portaltatrzanski.com##.promo-baner`?
