### ISSUE TITLE
mobimaniak.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3587]
Co sądzicie o banerze " łowcy promocji " oraz info o ceneo ?

**Comment by hawkeye116477** [comment]
No nie wiem, łowcy promocji to chyba coś do sociala, choć można też uznać to za reklamę. Natomiast Ceneo to może do tego drugiego Macieja, do AlleBlocka.

**Comment by blocker999** [comment]
@hawkeye116477 wsumie " łowcy promocji " przekierowują do profilu na FB, więc można to do sociali wrzucić, a ceneo to wątpie by było do alleblocka bo on raczej zbiera śmieci z wewnętrznej strony ceneo.pl a nie z każdej strony co zawiera ich odnośnik, no chyba że ja czegoś niewiem?

A i więcej adresów do stron z tymi samymi odnośnikami znajdziecie w temacie #1379 w drugim komentarzu.

**Comment by hawkeye116477** [comment]
Niespodzianka, na gsmmaniak też jest ta okazja i reguła jest w głównym polskim filtrze. Także sam już nie wiem, gdzie to powinno trafić. Może czasem pojawia się tam jeszcze lepsza reklama, dlatego @MajkiIT to dodał.
A więc to wszystko zostało jeszcze do dodania:
`acermaniak.pl,activemaniak.pl,agdmaniak.pl,appmaniak.pl,blogomaniak.pl,fotomaniak.pl,gizmaniak.pl,luxmaniak.pl,mobimaniak.pl,tabletmaniak.pl###okazja-dnia`

@blocker999 A z tym AlleBlockiem, to no tak, faktycznie mój błąd.

**Comment by MajkiIT** [comment]
Wcześniej tam była reklama.... związana z ceneo lub skąpiec. To mam usunąć?

**Comment by hawkeye116477** [comment]
@MajkiIT Nie, skoro pojawiają się tam lepsze reklamy, to dopisz jeszcze resztę tych stron.

**Comment by xxcriticxx** [comment]
ktora reklama
![capture222](https://user-images.githubusercontent.com/15007183/30285099-ff17784c-96ea-11e7-9ea9-80bd557aa9b4.PNG)

![capture](https://user-images.githubusercontent.com/15007183/30285090-f54d4274-96ea-11e7-8ca0-b2ffe6a3ed8c.PNG)

**Comment by xxcriticxx** [comment]
albo ta?

![capture](https://user-images.githubusercontent.com/15007183/30285197-59c6d648-96eb-11e7-99fd-f13fe035689f.PNG)
