### ISSUE TITLE
cookie generic filters 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3588]
@hawkeye116477 pozbierasz wiecej tych cookie generic filtrow

**Comment by hawkeye116477** [comment]
@xxcriticxx Skąd mam zebrać? Wszystkie te co miałem pewność, że są polskie , to skopiowałem od Fanboya i I don't care, a żeby dodać resztę z tych list, to @MajkiIT raczej nie podoba mi się ten pomysł. Także raczej po prostu będę dodawał na bieżąco, jak ktoš coś zgłosi.

**Comment by xxcriticxx** [comment]
@hawkeye116477 dzieki za info
