### ISSUE TITLE
euro.com.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3589]
@MajkiIT Tą wielką reklamę smartfona blokujemy czy raczej nie?
`euro.com.pl##.scroll-footer`
![screenshot_20170911_182142](https://user-images.githubusercontent.com/19818572/30285344-172dc5ca-971e-11e7-9992-80d1c991d133.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 no pewnie :D

**Comment by gzenio22** [comment]
looo ale monstrum :D
