### ISSUE TITLE
vivaldi.com

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3592]
https://vivaldi.com/?lang=pl_PL

Resztki po ikonkach social -> `vivaldi.com##.social`

**Comment by blocker999** [comment]
@MajkiIT dodaj

**Comment by xxcriticxx** [comment]
@blocker999 

ty albo @hawkeye116477 zrobcie pull requesta i sie doda

**Comment by MajkiIT** [comment]
@blocker999 daj pulla to będzie można do ciebie przypisywać zgłoszenia.
