### ISSUE TITLE
assigness

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3593]
@MajkiIT na liscie assignees nie widze @blocker999

**Comment by MajkiIT** [comment]
bo nie dał nigdy pulla

**Comment by hawkeye116477** [comment]
@MajkiIT Jak to nie, raz dał, ale commit nie trafił w odpowiednie miejsce.
https://github.com/MajkiIT/polish-ads-filter/pull/3116

**Comment by MajkiIT** [comment]
@hawkeye116477 to wolałbym aby trafił w dobre miejsce :)

**Comment by MajkiIT** [comment]
Już wiem ... ktoś musi napisać w wątku aby go oznaczyć.
