### ISSUE TITLE
manjaro.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3596]
![13f52c01-ff3a-4041-8231-02c03b322c29](https://user-images.githubusercontent.com/19818572/30318469-76be7a5e-97ad-11e7-979f-f9fc899cf37d.png)

To chyba jakaś pułapka na blokery, gdyż po zwhitelistowaniu, komunikat znika, a reklam jak nie było, tak nie ma -> `@@||manjaro.pl/abd/adserver/adlogger_tracker.php`

**Comment by xxcriticxx** [comment]
To jest Linux co fademind używa

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie tylko on, ja też z niego korzystam :smile:.

**Comment by xxcriticxx** [comment]
to namierzyli was pakowac manele

**Comment by hawkeye116477** [comment]
@xxcriticxx Kto nas niby namierzył i niby po co mieliby to robić :smiley:?

**Comment by MajkiIT** [comment]
@hawkeye116477 dzięki
