### ISSUE TITLE
bankier.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3598]
![image-20170912-001](https://user-images.githubusercontent.com/9846948/30327858-dfec03fa-97cd-11e7-8cc1-93511c655d40.png)

```
bankier.pl###boxPromoTool3
```

**Comment by hawkeye116477** [comment]
Jeszcze na dole są polecane -> `bankier.pl###boxBankierPick`

**Comment by MajkiIT** [comment]
@FadeMind @hawkeye116477 Dzięki
