### ISSUE TITLE
Kodiwpigulce.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3600]
Z tym cudenkiem tez chyba trzeba cos z działać 

http://prntscr.com/gkbbi9

**Comment by hawkeye116477** [comment]
@gzenio22 Już to dzisiaj zostało dodane.

**Comment by gzenio22** [comment]
właśnie u mnie to nie pykło znaczy latajacy zebrak zniknol ale to na dole nie

**Comment by hawkeye116477** [comment]
@gzenio22 Ale to to było do PopupBlockera, a te nowe cudeńko już dziś zgłaszałem i @MajkiIT to dodał -> `kodiwpigulce.pl##.sweet-alert`.

**Comment by hawkeye116477** [comment]
@gzenio22 Ale to to było do PopupBlockera, a te nowe cudeńko już dziś zgłaszałem i @MajkiIT to dodał -> `kodiwpigulce.pl##.sweet-alert`

**Comment by gzenio22** [comment]
ta strona jest jakas dziwna... teraz tamto zniklo a zebrak za mna lata fuck this shit Xd

**Comment by hawkeye116477** [comment]
@gzenio22 Coś masz nie tak, poczekaj aż do końca się zaktualizują filtry, bo może jeszcze PopupBlocker się ściąga i dlatego tak jest. Wyczyść też delicje :smiley:.

**Comment by gzenio22** [comment]
dobra zalapalo Xd ale to jest dziwne wgl mam cos dla Popupa prawdopodobnie ale musze to sprawdzic

**Comment by MajkiIT** [comment]
@blocker999 zerkniesz?

**Comment by blocker999** [comment]
@MajkiIT  Teraz chyba jest ok, @gzenio22 potwierdzisz?.

**Comment by gzenio22** [comment]
@MajkiIT Zamknij jest ok :)
