### ISSUE TITLE
AdBlock Cookies psuje nowe Allegro

### ISSUE THREAD

**Issue by maciejtarmas** [MajkiIT/polish-ads-filter#3601]
Ta reguła ukrywa cały tag `HTML` na nowej stronie Allegro i w związku z tym nic się nie wyświetla:

`##[class*="cookie-policy"]`

Wszystko dlatego, że `HTML` ma taką klasę:

`<html class="cookie-policy-banner-not-dismissed installments-banner-not-dismissed loyalty-program-banner-not-dismissed">`

Jako że oficjalnie Allegro nie odpaliło nowej wersji u wszystkich, potestować można tutaj:

https://alleblock.pl/allegro/

Podziękowania dla @blocker999 za podesłanie kodu źródłowego nowej strony, bo u mnie cały czas jest wszędzie stara wersja.

**Comment by hawkeye116477** [comment]
@MajkiIT To co dajemy na to wyjątek czy usuwamy całkowicie a może lepiej zamienić na coś innego, co proponujesz mistrzu?

**Comment by MajkiIT** [comment]
@maciejtarmas Dzięki
@hawkeye116477 dałem wyjątek, ale możemy coś pomyśleć.

**Comment by maciejtarmas** [comment]
Myślę, żeby na razie nie zamykać buga i poobserwować co się dzieje, dopóki nie skończą przy tym grzebać.

**Comment by hawkeye116477** [comment]
@MajkiIT A może tak -> `##[class*="cookie-policy"]:not(body):not(html)`?

**Comment by gzenio22** [comment]
Reklama durexa wtopiona w stopke mnie rozjebala Xd hahaha

**Comment by MajkiIT** [comment]
no to możemy zmienić :D

**Comment by hawkeye116477** [comment]
@MajkIT Widzę, że taki sam wyjątek jest dany również dla zadane.pl, tyle tylko, że ta strona zmieniła nazwę na brainly, ale jakoś na razie nie widzę problemu mimo, że ta reguła działa. Więc nie wiem, albo zmieniamy nazwę albo do usunięcia.

**Comment by xxcriticxx** [comment]
@hawkeye116477 brainly podalem 

https://github.com/MajkiIT/polish-ads-filter/issues/3551

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale tym razem chodzi o filtr ciasteczkowy :smile:.
