### ISSUE TITLE
ulubiency :D Bug

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3602]
na glownej jak zjedziecie na sam dol strony ona chce wam jako pusta leciec dalej? :D

**Comment by hawkeye116477** [comment]
@gzenio22 Na jakiej stronie tak się dzieje?

**Comment by xxcriticxx** [comment]
na ulubionej

**Comment by gzenio22** [comment]
wp :D

**Comment by hawkeye116477** [comment]
@xxcriticxx Czyli tu -> http://www.restauracja-ulubiona.pl/ 😃 ?

**Comment by HateAds** [comment]
@gzenio22 Zjechałem na dół i się zatrzymało normalnie. Inna sprawa, że trwa to bardzo długo, myślałem, że komp mi się zawiesił :smiley:

**Comment by MajkiIT** [comment]
@hawkeye116477 narobiłeś smaka tym jedzenie :( noi trzeba pojechać tam na obiad :P

**Comment by gzenio22** [comment]
oni juz nie wiedza jak z nami walczyc buahahaha :D
