### ISSUE TITLE
forum.elportal.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3603]
Reklamy na górze

**Comment by xxcriticxx** [comment]
@blocker999 podaj link po ja na main nic nie mam

**Comment by blocker999** [comment]
@xxcriticxx na głównej nad logo

**Comment by hawkeye116477** [comment]
`forum.elportal.pl##.scale-with-grid`

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/30346622-5cd1b604-97d7-11e7-885a-d26c8d378471.PNG)

**Comment by hawkeye116477** [comment]
@blocker999 To niemożliwe, sprawdziłem zarówno na Waterfoksie jak i Vivaldim i jest reklama. A może to Chrome blokuje, bo przecież wujek dodał ostatnio jakiegoś natywnego Adblocka, zgadza się?

**Comment by blocker999** [comment]
@hawkeye116477 Nie wiem czy to możliwe że tam są reklamy ale twoja reguła je blokuje.

**Comment by hawkeye116477** [comment]
@blocker999 To miało być do @xxcriticxx, ale ok.

**Comment by HateAds** [comment]
@hawkeye116477 U mnie na Chromie jest reklama.

**Comment by xxcriticxx** [comment]
@hawkeye116477 na foxie nie ma na chromie jest

**Comment by xxcriticxx** [comment]
@hawkeye116477 to chyba przez 



Static filter `_beacon?` found in:

    EasyPrivacy

**Comment by HateAds** [comment]
@xxcriticxx To fox ma coś wbudowanego do blokowania reklam >

**Comment by hawkeye116477** [comment]
@HateAds Do reklam nie ma, jest tylko ochrona przed śledzeniem.

**Comment by MajkiIT** [comment]
A u mnie na FF ... :D
