### ISSUE TITLE
money.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3612]
My blokujemy ta strone? wyskakuje mi komunikat zeby na to nie wbijac Xd

Przykład: https://www.money.pl/gospodarka/wiadomosci/artykul/onelife-network-uokik,5,0,2364933.html?src01=6a4c8&src02=facebook_wp

czy to jakis blad w sztuce? :D

**Comment by hawkeye116477** [comment]
@gzenio22 Trzeba odblokować reklamy, gdyż nie ma wolności mediów bez oglądalności reklam 😄 .

**Comment by gzenio22** [comment]
o kurwa hahahaha taaa

a tak serio jakos to sie da przeskoczyc?

**Comment by hawkeye116477** [comment]
@gzenio22 Ta włączyć Protector albo AAK Cont. Z jednym i drugim nie ma takiego komunikatu.
Ale widzę, że reklamy z wp się pojawiły :smile:.

**Comment by gzenio22** [comment]
kurwa i love WP :D chyba trzeba kombinować cos z tym

**Comment by hawkeye116477** [comment]
@gzenio22 Na stronę główną chyba coś takiego powinno pomóc -> 
`money.pl##DIV[style^="display: block; min-height: 0px;"]`

**Comment by MajkiIT** [comment]
Nie macie tam reklam? https://www.screencast.com/t/rUspwiWq

**Comment by FadeMind** [comment]
@MajkiIT  Nie mam reklam, video działa.

**Comment by gzenio22** [comment]
@MajkiIT Reklam nie mam a reguła @hawkeye116477 Działa :)

**Comment by MajkiIT** [comment]
@gzenio22 @hawkeye116477 u mnie film działa, tylko nawaliło reklam.

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/30388560-13160194-987e-11e7-8a20-8dc09b130fa6.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki bo już myślałem, że zwariowałem ...

**Comment by xxcriticxx** [comment]
nope mucho reklama

**Comment by xxcriticxx** [comment]
i push push

**Comment by gzenio22** [comment]
kurw... wyczyscilem ciastka i u mmnie tez jest :O

**Comment by xxcriticxx** [comment]
@gzenio22 damy rade dotn worry

**Comment by MajkiIT** [comment]
@gzenio22 @xxcriticxx 
Wrzuciłem update. Można testować.

**Comment by xxcriticxx** [comment]
@MajkiIT jest good tylko push push zostalo jak dasz rade please

**Comment by MajkiIT** [comment]
@xxcriticxx ja tego nie widzę, ale może tak?
`||www.wp.pl/webpush/static/js/webpush.desktop.js$script,domain=www.money.pl`

**Comment by xxcriticxx** [comment]
@MajkiIT dziala zajebiscie na push push

**Comment by hawkeye116477** [comment]
@xxcriticxx @MajkiIT Ale przecież możecie to w przeglądarce wyłączyć :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 zip it! :)
