### ISSUE TITLE
wish.com

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3613]
To mi śmierdzi przekrętem na sporą skale zerknie ktos?

**Comment by xxcriticxx** [comment]
`||wish.com

**Comment by gzenio22** [comment]
znaczy inaczej wymuszaja rejestracje nim zobaczy sie produkt da rade to przeskoczyc?

**Comment by xxcriticxx** [comment]
to jakis b.s.

**Comment by MajkiIT** [comment]
```
www.wish.com###login-modal-overlay
www.wish.com###new-login-modal
```
Ale tło jest animowane.
