### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3616]
https://sportowefakty.wp.pl/boks/710577/saleta-krytycznie-o-polskim-boksie-waga-ciezka-jest-w-fatalnym-stanie?utm_source=Serwisy_WP&utm_medium=LStream

macie reklamy?

**Comment by xxcriticxx** [comment]
yes

![capture](https://user-images.githubusercontent.com/15007183/30393913-88f39500-988f-11e7-9e30-51d92e48e0fd.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx zrób proszę update i sprawdź proszę.

**Comment by xxcriticxx** [comment]
zostalo kilka prawa strona i na dole 

![capture](https://user-images.githubusercontent.com/15007183/30394660-bc12993e-9891-11e7-9ed3-2f3e91639213.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx Już powinno być ok

**Comment by xxcriticxx** [comment]
nastepne artykow maja dalej rekalam tak zrobilem update 

v.2017091304 aktualizacja: sr, 13 wrzesnia 2017, 21:15:00

![capture](https://user-images.githubusercontent.com/15007183/30396497-d4822830-9897-11e7-9b8a-e6c255802d97.PNG)
![capture1](https://user-images.githubusercontent.com/15007183/30396502-d825e0d0-9897-11e7-9076-b3fdef867ad5.PNG)

**Comment by xxcriticxx** [comment]
@MajkiIT teraz zostaly tylko reklamy pomiedzy artykolami 

![capture](https://user-images.githubusercontent.com/15007183/30397904-5c32742a-989c-11e7-9eb4-ac20dce4c8b3.PNG)

**Comment by MajkiIT** [comment]
Potestuj proszę z wersją 2017091306. Wydaje mi się, że już to łapią filtry.

**Comment by xxcriticxx** [comment]
tak mam ta ver  `v.2017091306 aktualizacja: sr, 13 wrzesnia 2017, 21:55:00`

teraz reklamy sa co drugi artykul

![capture](https://user-images.githubusercontent.com/15007183/30398934-2093eb02-98a0-11e7-9a3c-6c2e0b3f2a12.PNG)

**Comment by xxcriticxx** [comment]
![fireshot screen capture 002 - saleta krytycznie o polskim boksie_ _waga ciezka jest w fatalnym stanie_ - sportowefakty_wp_pl_boks_710577_saleta-kry](https://user-images.githubusercontent.com/15007183/30399350-5de364b4-98a1-11e7-98de-5bcbfd6c529f.png)

**Comment by MajkiIT** [comment]
@xxcriticxx już powinno być ok.

**Comment by xxcriticxx** [comment]
@MajkiIT teraz jest gitara

**Comment by MajkiIT** [comment]
@xxcriticxx dzięki
