### ISSUE TITLE
Link do aak cont

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3617]
@xxcriticxx kopsnij mi linka tego do wklejenia w konsole Tego AAK Cont :D

**Comment by xxcriticxx** [comment]
https://gitlab.com/xuhaiyang1234/AAK-Cont

**Comment by gzenio22** [comment]
ale ja mam na mysli tego do wklejenia w konsole ublocka

**Comment by xxcriticxx** [comment]
orinalny link pokazuje 404

znalazlem jakis backup https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-list-ubo.txt

**Comment by gzenio22** [comment]
@xxcriticxx daj jeszcze do angielskich stron

**Comment by xxcriticxx** [comment]
@gzenio22 need more info

**Comment by gzenio22** [comment]
mam na mysli angielskie filtry AAK te co kiedys dawales

**Comment by xxcriticxx** [comment]
https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt
