### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#362]
ostatnio pojawiły się bardzo uciążliwe reklamy w serwisie filmweb.pl przy odtwarzaniu filmów/trailerów. mianowicie przed każdym filmem jest wymuszona reklama, która trzeba oglądać co najmniej 20 sekund aby można było ją pominąć. czy jest jakaś szansa je zablokować?

**Comment by xxcriticxx** [comment]
kto podal info?

**Comment by MajkiIT** [comment]
komentarz na stronie.

**Comment by xxcriticxx** [comment]
najnowsze filtry z niedz 2/7?
