### ISSUE TITLE
nowy.tlen.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3627]
paczcie jaka ciekawostke dzis na stronie poczty po zalogowaniu i przejsciu w oferty znalazlem

![screenshot_1](https://user-images.githubusercontent.com/21177361/30429443-cbb92562-9957-11e7-8ac4-9141ce446e25.png)

**Comment by xxcriticxx** [comment]
@gzenio22 to jest znak ze trzeba jechac na wakacje

**Comment by gzenio22** [comment]
chcial bym :D

**Comment by xxcriticxx** [comment]
https://www.earthcam.com/cams/newyork/timessquare/?cam=tsrobo1
