### ISSUE TITLE
pudelek.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#3628]
Reklamy, reklamy i jeszcze raz reklamy.
![image](https://user-images.githubusercontent.com/29756590/30440238-41200ca8-9976-11e7-892f-ce42a8a9b123.png)
![image](https://user-images.githubusercontent.com/29756590/30440260-558dbcb2-9976-11e7-893b-fa0ae3a703ec.png)
![image](https://user-images.githubusercontent.com/29756590/30440282-5fdfa1d0-9976-11e7-8a67-a2a1b2368d17.png)
![image](https://user-images.githubusercontent.com/29756590/30440297-69d56706-9976-11e7-903c-0fe227e732f3.png)
![image](https://user-images.githubusercontent.com/29756590/30440307-7176ac4a-9976-11e7-8d51-e8ae63b26927.png)

**Comment by xxcriticxx** [comment]
@MajkiIT help!

**Comment by MajkiIT** [comment]
@xxcriticxx wrzuciłem update

**Comment by xxcriticxx** [comment]
@MajkiIT zostalo jeszcze troche

**Comment by MajkiIT** [comment]
właśnie nie zawsze mi się pojawia, ale będę walczył.

**Comment by xxcriticxx** [comment]
pudelek tez dziala super

**Comment by HateAds** [comment]
Potwierdzam.

**Comment by MajkiIT** [comment]
@HateAds @xxcriticxx Dziękuję. A możecie zerknąć tutaj ? http://pudelekx.pl/

**Comment by HateAds** [comment]
@MajkiIT Reklama jakiejś gry na samej górze ( ja osobiście bym to usunął bo na to nie da się wejść i tak )
![image](https://user-images.githubusercontent.com/29756590/30447087-3ea46130-998b-11e7-82f7-c15142941fe8.png)

**Comment by MajkiIT** [comment]
@HateAds Dzięki. Poprawione

**Comment by xxcriticxx** [comment]
@MajkiIT jest git
