### ISSUE TITLE
silesion.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3641]
https://silesion.pl

Z włączoną ochroną Adguard nie jest wyświetlana zawartość działów

![2017-09-15 09_41_59-silesion pl wiecej niz portal - silesion pl opera](https://user-images.githubusercontent.com/9846948/30471765-3ad019fe-99fa-11e7-88fe-e7dda7fe1339.png)

![2017-09-15 09_42_22-silesion pl wiecej niz portal - silesion pl opera](https://user-images.githubusercontent.com/9846948/30471766-3adc5e4e-99fa-11e7-8429-dbe5261cfdae.png)

**Comment by hawkeye116477** [comment]
Na uBlocku jest ok, więc to raczej jakiś bug Adguarda.

**Comment by MajkiIT** [comment]
@FadeMind możesz odłączać i testować kolejne filtry?

**Comment by F4z** [comment]
@FadeMind jak dodasz tę regułę, to wyświetla się prawidłowo?
`silesion.pl##body .banner-ad`

**Comment by FadeMind** [comment]
@F4z Twoja reguła zdziałała cuda :D Treść się wyświetla:
![2017-09-15 12_24_26-](https://user-images.githubusercontent.com/9846948/30478313-db86e362-9a10-11e7-8945-050b7b714498.png)

**Comment by MajkiIT** [comment]
@F4z Dzięki
