### ISSUE TITLE
wizaz.pl/forum

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3643]
Reklamy kosmetyków między komentarzami

**Comment by gzenio22** [comment]
wizaz.pl/forum###kwc_promo_box_1
wizaz.pl/forum###kwc_promo_box_2
wizaz.pl/forum###kwc_promo_box_3
wizaz.pl/forum###kwc_promo_box_4
wizaz.pl/forum###kwc_promo_box_5
wizaz.pl/forum###kwc_promo_box_6

Da rade to zdjac jedną?

**Comment by hawkeye116477** [comment]
@gzenio22 Tak -> `wizaz.pl##[id^="kwc_promo_box_"]` :smile:.

**Comment by xxcriticxx** [comment]
`||static.wizaz.pl/system/kwc/promo/kwc_promo_box_*.html$subdocument`

**Comment by gzenio22** [comment]
@hawkeye116477 kurrde :D magik
