### ISSUE TITLE
motomi.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3644]
https://motomi.pl/oferty/Subaru/Forester/okazja-2-0-xt-turbo-177-km-automat-serwisowany/0635a1d0-a552-4860-a922-b461249eae75

![image](https://user-images.githubusercontent.com/15007183/30479673-4baf6b32-99e4-11e7-8619-032aaf5192c2.png)

**Comment by MajkiIT** [comment]
`motomi.pl##A > .img-responsive`

**Comment by hawkeye116477** [comment]
Social, resztka -> `motomi.pl##.col-sm-4`
