### ISSUE TITLE
moto.gratka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3645]
macje taki sam problem czy ja hostem za duzo blokuje

http://moto.gratka.pl/tresc/bmw-seria-1-22493593.html

![capture](https://user-images.githubusercontent.com/15007183/30479714-78f6ad58-99e4-11e7-8756-9a0c96ab0df4.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx tam jest reklama 
`moto.gratka.pl##.nieSkacz`
