### ISSUE TITLE
gg.pl (Prebake)

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3646]
@MajkiIT W Prebake jest reguła, która psuje logowanie na gg. A najwyraźniej są jeszcze osoby, które korzystają z gg i z listy Prebake. Więc nie wiem czy warto dać whitelist na nasz filtr czy nie, co o tym sądzisz?
https://github.com/azet12/PopupBlocker/issues/68#issuecomment-329763381

**Comment by MajkiIT** [comment]
Dodamy wyjątek ...
