### ISSUE TITLE
forum.szafa.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3648]
Rabaty -50% oraz -80% no i może coś jeszcze niewiem ale to jest po prawej

**Comment by hawkeye116477** [comment]
Reklamy
```
forum.szafa.pl##a[href*="converti.se"]
forum.szafa.pl##a[href^="//agrest.pl/"]
```

Social -> `forum.szafa.pl##.section-right:nth-of-type(3) > .dosis.header`

**Comment by hawkeye116477** [comment]
@MajkiIT Reklamy nadal są.

**Comment by MajkiIT** [comment]
@hawkeye116477 poprawione Kierowniku.

**Comment by hawkeye116477** [comment]
@MajkiIT Heh :smiley:. Został jeszcze pasek agrest -> `forum.szafa.pl##a[href^="//agrest.pl/"]` :smile:.,

**Comment by MajkiIT** [comment]
@hawkeye116477 a może ja lubię agresr?
