### ISSUE TITLE
Nagrody za pomoc przy tworzeniu filtrów

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3650]
Dostałem od zielonych kod na parę rzeczy do gry Paragon, ale ja nie mam aktywnej subskrybcji GeForce Now i raczej nie przepadam za grami Moba, więc trochę szkoda byłoby gdyby się zmarnowało.
Więc chce ktoś :smile:?
![screenshot_20170915_171343](https://user-images.githubusercontent.com/19818572/30490086-43abcd7c-9a39-11e7-8d11-258648ea2ae6.png)

> *Oferta Paragon ważna jest wyłącznie w Stanach Zjednoczonych, Kanadzie, Czechach, Danii, Finlandii, Francji, Niemczech, Włoszech, Holandii, Norwegii, Polsce, Rosji, Hiszpanii, Szwecji i Wielkiej Brytanii. Niniejsze postanowienia nie obowiązują tam, gdzie jest to zabronione. Niniejsza oferta nie ma wartości pieniężnej. Aby skorzystać z oferty Paragon, uprawniony klient musi zrealizować dostarczony przez firmę NVIDIA kod za pośrednictwem powyższego odnośnika (lub zrealizować kod pod adresem rewardsportal.nvidia.com). **Wymagana jest subskrypcja usługi GeForce NOW oraz konto Epic Games.** **Oferta traci ważność 22 września 2017**. Oferta obowiązuje do wyczerpania zapasów i może ulec zmianie bez wcześniejszego powiadomienia.

**Comment by MajkiIT** [comment]
@hawkeye116477 Gdzieś ty się zarejestrował?

**Comment by hawkeye116477** [comment]
@MajkiIT Tutaj -> https://www.nvidia.pl/shield/rewards/. To jest taki specjalny program tylko dla tych, co mają urządzenia SHIELD.

**Comment by MajkiIT** [comment]
@hawkeye116477 jesteś z tego zadowolony?

**Comment by hawkeye116477** [comment]
@MajkiIT Z tego programu? Jak na razie to dostałem tylko ten jeden kod, ale w czerwcu się rejestrowałem. A program chyba był już w lutym, ale update'u do Nougata nie robiłem, więc nie wiedziałem o nim, bo notka o tym programie wyświetliła mi się po updatcie. A wcześniej chyba rozdawali kody na filmy z Google Play.

**Comment by hawkeye116477** [comment]
@All Brak chętnych na kod, nikt nie chce nagrody za swą pracę? Ok, to rozdam dla biednych na redditcie 😃 .

**Comment by MajkiIT** [comment]
@hawkeye116477 ja niestety nie gram ... PS4 Pro leży a grałem na niej 30 min ...

**Comment by hawkeye116477** [comment]
No i mamy chętnych -> https://www.reddit.com/r/paragon/comments/70hxhh/giveaway_paragon_nvidia_shield_rewards_pack/, to pobawimy się w losowanie 😃 .
