### ISSUE TITLE
http://www.spidersweb.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3652]
http://www.spidersweb.pl/2017/09/blueborne-atak-bluetooth.html

![2017-09-15 20_15_05-cfosspeed v10 22](https://user-images.githubusercontent.com/9846948/30497292-9f66e660-9a52-11e7-8bea-c6a926ba6b0e.png)

> `https://ocs-pl.oktawave.com/v1/AUTH_2887234e-384a-4873-8bc5-405211db13a2/spidersweb/reklamy/play/1180x400/index.html$domain=spidersweb.pl`

### Fix

```
spidersweb.pl##.play_iframe
```
albo
```
/spidersweb/reklamy/play^$domain=spidersweb.pl
```

**Comment by gzenio22** [comment]
@MajkiIT Nie dawalem na to ostatnio tej pierwszej reguły od @FadeMind ?

**Comment by MajkiIT** [comment]
Hhmmm możliwe . Jeśli tak to sorry @gzenio22 

@FadeMind dzięki
