### ISSUE TITLE
pikio.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3653]
cdn.pushalert.co
http://pikio.pl/wiadomosci/#

**Comment by xxcriticxx** [comment]
takie cos bendzie dzialasc?

`||*.pushalert.co`

**Comment by MajkiIT** [comment]
`||pushalert.co` tak będzie ok.

**Comment by hawkeye116477** [comment]
@MajkiIT Sociala to tu nie widzę, ale za to są resztki po reklamach.

**Comment by hawkeye116477** [comment]
@MajkiIT Sociala to tu nie widzę, ale za to są resztki po reklamach.
`pikio.pl##.widget_text.widget`
