### ISSUE TITLE
smaker.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3654]
https://smaker.pl/przepis-ciasto-jablkowo-sliwkowe,153860,izaa-a.html

**Comment by MajkiIT** [comment]
to z komentarza 

> Proszę zadziałać na str: http://pikio.pl/wiadomosci/ coś przesłania stronę. Podobna sytuacja na https://smaker.pl/przepis-ciasto-jablkowo-sliwkowe,153860,izaa-a.html z tym, że tu komunikat o polubieniu na fb.

**Comment by hawkeye116477** [comment]
@MajkiIT A ok, to napisz niech włączy Fanboy's Social Blocking List.

**Comment by hawkeye116477** [comment]
Ok, widzę dziadostwo, dodam też do PopupBlockera, bo to popup, błagają, by ich polubić 😃 .

**Comment by MajkiIT** [comment]
@hawkeye116477 dzięki

**Comment by hawkeye116477** [comment]
@MajkiIT Problem jest taki, że scroll się blokuje, a oni dali coś takiego:
```
body.scrollingDisabled {
    overflow: hidden!important;
```
Jak nadpisać important?

**Comment by MajkiIT** [comment]
Łooo Panie nie wiem ... @F4z może ty wiesz?

**Comment by hawkeye116477** [comment]
@MajkiIT @F4z chyba napracował się w teamie Adguarda i teraz chrapie. A ja tymczasem znalazłem rozwiązanie -> `smaker.pl##html > body.scrollingDisabled:style(overflow:visible!important;)` 😄 .

**Comment by MajkiIT** [comment]
@hawkeye116477 Wow jesteś genialny :P
