### ISSUE TITLE
poczta.wp.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#3657]
Przed zalogowaniem na pocztę oto jaki piękny widok mnie przywitał. Reklama "łongi" mało tego zmieniająca kolor, aż mnie oczy rozbolały.
![image](https://user-images.githubusercontent.com/29756590/30504587-fe0ed886-9a6f-11e7-8bc8-70ea788c7759.png)

**Comment by xxcriticxx** [comment]
@HateAds to jest znak ze jestes w starszym wieku

**Comment by MajkiIT** [comment]
`profil.wp.pl##A[target="_blank"] > IMG[src^="https://v.wpimg.pl/"][style*=" width: 100%; "]`

**Comment by MajkiIT** [comment]
`/^https:\/\/[a-z]{4,10}\.wp\.pl\/[a-zA-Z0-9_-]{200,}/$domain=profil.wp.pl`

**Comment by HateAds** [comment]
@MajkiIT To było szybkie. Dzięki

**Comment by HateAds** [comment]
@xxcriticxx Jak to mówią, starość nie radość.

**Comment by HateAds** [comment]
@MajkiIT Oj jeszcze coś wyskoczyło.
![image](https://user-images.githubusercontent.com/29756590/30505617-154e497c-9a76-11e7-8d6b-d3f46c5cd349.png)
