### ISSUE TITLE
gorzowianin.com

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3659]
http://gorzowianin.com
![2017-09-16 10_53_42-gorzowianin com - najprawdopodobniej najlepszy portal w miescie opera](https://user-images.githubusercontent.com/9846948/30510876-69c2fa32-9acd-11e7-97bb-891988e48c19.png)
@F4z

**Comment by hawkeye116477** [comment]
@FadeMind A po co jego tym kłopotać, sami sobie poradzimy :smile:.

```
@@||gorzowianin.com/js/ads.js$script
gorzowianin.com##a[href*="http://gorzowianin.com/rotator"]
```

**Comment by MajkiIT** [comment]
@FadeMind nam nie ufa :(

**Comment by hawkeye116477** [comment]
@MajkiIT Reklamy też są.

**Comment by MajkiIT** [comment]
@hawkeye116477 Już Kierowniku ... przepraszam ...
