### ISSUE TITLE
*.wp.pl mnie śledzi (dobreprogramy.pl)

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#3660]
### Co trzeba zrobić aby reklama/element się pojawił
1. Przykładowo tutaj https://www.dobreprogramy.pl/Koparki-kryptomonet-w-reklamach-przegladarki-pracuja-na-oszustow,News,83150.html
2. każda interakcja ze stroną powoduje requesty `image` do `losowesłowo?.wp.pl` z parametrami mojego komputera, czasami zakodowane w base64

### Twoja konfiguracja
**Przeglądarka:**
Firefox Nightly
**Operating system:**
Mint 18.2
**Blocker:**
UBO 1.14.11
**Używane filtry:**
1. domyślne + POLx2

### Zrzut ekranu
![screenshot_20170916_123809](https://user-images.githubusercontent.com/886325/30511557-f72c1d32-9adb-11e7-9b0a-4ec1eba87d80.png)

Ja to przyblokowałem filtrowaniem dynamicznym, ale może warto to jakoś dodać do listy (jeśli za dużo nie popsuje). Coś w rodzaju `||*.wp.pl$image,third-party` albo może da się przyciąć ten skrypt co się ładuje na samym początku `https://i.wp.pl/a/i/stg/wpjslib-nojq.js` i wystarczy?

**Comment by hawkeye116477** [comment]
@gwarser A Moz://a też cię śledzi i planują jeszcze więcej danych zbierać, to co przesiadasz się na Waterfox?

**Comment by gwarser** [comment]
Mocno się bronię, ale jakby co to przesiądę się na Google Ultron!

**Comment by MajkiIT** [comment]
@gwarser to powinno być ok ... Sprawdź proszę

`/^https:\/\/[a-z]{4,10}.\wp\.pl\/[a-zA-Z0-9-_]{250,}/$image,domain=dobreprogramy.pl`

**Comment by hawkeye116477** [comment]
@gwarser Pierwsze słyszę o takiej przeglądarce, chyba jakaś zmyślona, ale wujek G też ma wielkie oczy. Waterfox jest o tyle dobry, że nadal tam będą dodatki starego typu, Classic Theme Restorer i te sprawy oraz nie będą mieszać się w politykę, no i trochę ma tam pousuwane zbędnych rzeczy i jest szybszy.

**Comment by gwarser** [comment]
@MajkiIT nie łapie `dom.wp.pl` i `gry.wp.pl`

**Comment by MajkiIT** [comment]
`/^https:\/\/[a-z]{3,10}.\wp\.pl\/[a-zA-Z0-9-_]{250,}/$image,domain=dobreprogramy.pl`

**Comment by gwarser** [comment]
Tego co podałem koment wyżej (request nie zakodowany base64) chyba nie blokuje, ale nie mogę teraz na niego trafić.

**Comment by MajkiIT** [comment]
@gwarser tego na pewno nie zablokuje. Na to napiszemy 2 filtr.

**Comment by MajkiIT** [comment]
`/^https:\/\/[a-z]{3,10}\.wp\.pl\/[a-z]{1,2}\/r[0-9]{10,20}\//$domain=dobreprogramy.pl`

@gwarser Może coś takiego

**Comment by MajkiIT** [comment]
@gwarser wrzuciłeś sobie tą regułę?

**Comment by gwarser** [comment]
Tak, ale nie mogłem trafić na ten typ żądania. Jutro jeszcze popatrzę, albo jak jakiś nowy news wrzucą.

**Comment by MajkiIT** [comment]
@gwarser potestuj i najwyżej wrzucimy do filtrów

**Comment by xxcriticxx** [comment]
wp nas lubiec mocno

**Comment by MajkiIT** [comment]
@xxcriticxx My ich też :D to miłość obustronna

**Comment by xxcriticxx** [comment]
@MajkiIT tak dokładnie

**Comment by gwarser** [comment]
Ten pierwszy działa.
Podobny jest już na liście `/^https:\/\/[a-z]{3,10}\.wp\.pl\/[a-zA-Z0-9_-]{200,}/$domain=profil.wp.pl|poczta.o2.pl` tylko, że bez `image`. Tutaj https://github.com/MajkiIT/polish-ads-filter/issues/3663#issuecomment-329978375 proponowałeś też `/^https:\/\/[a-z]{3,10}\.wp\.pl\/[a-zA-Z0-9_-]{200,}/$domain=pilot.wp.pl` - hawkeye116477 napisał, że blokuje filmy, ale może z `$image` nie będzie? (Niestety chwilowo nie mogę sprawdzić, bo mam lejek, a tak poza tym to mi wywala info o adblokerze i nie mogę się go w żaden sposób pozbyć.)

Na drugi nie mogę trafić już od trzech dni. Może jak tez z base64 jest zablokowany, to ten drugi już się nie pojawia? ... Właśnie sprawdziłem i wygląda na to, że tak jest.

**Comment by MajkiIT** [comment]
@gwarser Dzięki . Podane reguły z innych wątków miały na celu coś innego. Tutaj chcemy blokować te obrazki. Ja testuję i nie widzę problemów. Dziękuję za pomoc.

**Comment by MajkiIT** [comment]
@gwarser dodałem regułę.

**Comment by hawkeye116477** [comment]
@MajkiIT Nadal są tam jakieś dziwne połączenia do dziwnych stron wp.
A może coś takiego `||wp.pl^$third-party` będzie lepsze 😃 ?

**Comment by MajkiIT** [comment]
@hawkeye116477 możesz podać takie dziwne połączenie ? Twój filtr może coś popsuć.

**Comment by gwarser** [comment]
To `https://i.wp.pl/a/i/stg/wpjslib-nojq.js`?

**Comment by MajkiIT** [comment]
@gwarser Dzięki ... widzę, że tego jest sporo ==> `https://www.google.pl/search?q=i.wp.pl%2Fa%2Fi%2Fstg%2Fwpjslib-nojq.js&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&dcr=0&ei=WevJWe_WDMXi8AeT5o-QCA`

**Comment by MajkiIT** [comment]
`||wp.pl/*/wpjslib-nojq.js$script` do potestowania.

**Comment by hawkeye116477** [comment]
@MajkiIT Takie dziwne połączenia -> https://kobieta.wp.pl/do/r1506454405/dotn?sw=1280&sh=1024.... . Ale tak zablokowanie tego skryptu pomaga.

**Comment by gwarser** [comment]
@hawkeye116477 właśnie o tym jest to zgłoszenie. Nadal to masz? U mnie zniknęło jak jest zablokowany ten zakodowany w base64.

**Comment by hawkeye116477** [comment]
@gwarser Tak, nadal to mam. Ale po zablokowaniu tego skryptu, to znika.

**Comment by MajkiIT** [comment]
@gwarser @hawkeye116477 ten skrypt odpowiada za generowanie tych requestów. Protestujmy kilka dni i dodamy do filtrów.

**Comment by xxcriticxx** [comment]
@MajkiIT co bendziemy protestowac?

**Comment by MajkiIT** [comment]
@xxcriticxx miało być potestujemy :D . Dzięki za poprawkę.

**Comment by MajkiIT** [comment]
@xxcriticxx @gwarser @hawkeye116477 
Coś zmienili możecie przetestować to ?
`/^(http|https):\/\/[a-z.]{4,7}\.pl\/[a-z]\/[a-z]\/[a-z]{3,3}\/wpjslib-[a-z]{5,7}\.js/$script`

**Comment by xxcriticxx** [comment]
@MajkiIT ja ta zmiane protestuje! co mam zrobic z lista do pihole?

**Comment by F4z** [comment]
@MajkiIT może to nie w temacie, ale to u mnie psuje sportowefakty - https://sportowefakty.wp.pl/pilka-nozna/713546/grzegorz-krychowiak-daje-wba-nowe-mozliwosci-jest-tak-dobry-ze-moze-zagrac-w-kaz

**Comment by xxcriticxx** [comment]
@F4z podaj jak screenshot please

**Comment by F4z** [comment]
uBO + Chrome, bez żadnych skryptów.

![image](https://user-images.githubusercontent.com/11742596/31036046-d6382280-a56a-11e7-993e-49d2e09ee0fc.png)

A niżej film w ogóle się nie pojawia.

**Comment by xxcriticxx** [comment]
tak samo mam na foxie + film sie nie pojawia

**Comment by gwarser** [comment]
Tych skryptów jest kilka.

Na sportowefakty `https://a.wpimg.pl/a/i/stg/wpjslib-prebid.js` jest whitelistowany w liście, a `https://a.wpimg.pl/a/i/stg/wpjslib-pwpnojq.js` blokowany regułą którą podałeś.

Na dobreprogramy jest `https://i.wp.pl/a/i/stg/wpjslib-nojq.js` i blokowało go `||wp.pl/*/wpjslib-nojq.js$script` z postu wyżej, ale teraz jest odblokowany.

**Comment by MajkiIT** [comment]
@xxcriticxx co do host to zrobiłem update
@F4z chyba masz nieaktualne filtry. Poprawiałem to 
@gwarser 
`/^(http|https):\/\/[a-z].[a-z]{2,5}.pl\/[a-z]\/[a-z]\/[a-z]{3,3}\/wpjslib-[a-z]{4,7}.js/$script`

**Comment by F4z** [comment]
@MajkiIT przed sprawdzeniem aktualizowałem filtry.
Chodziło mi o regułę, którą podałeś do testu:
`/^(http|https):\/\/[a-z.]{4,7}\.pl\/[a-z]\/[a-z]\/[a-z]{3,3}\/wpjslib-[a-z]{5,7}\.js/$script`

![image](https://user-images.githubusercontent.com/11742596/31044574-38742e1e-a5d2-11e7-9659-34b6519b2973.png)

**Comment by gwarser** [comment]
To jest chyba wile skryptów w jednym pliku, zależnie jak dla strony skonfigurują i te ostatnie litery w nazwie chyba oznaczają co jest w środku. Przykładowo "nojq" wysyła te dziwne requesty, a "pwp" odtwarza filmiki na sportowefakty.
