### ISSUE TITLE
profil.wp.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3661]
https://profil.wp.pl/login.html?url=https%3A%2F%2Fpoczta.wp.pl%2Findexgwt.html%3Fflg%3D1&serwis=nowa_poczta_wp

Rekamy na oknie logowania do poczty wp

**Comment by MajkiIT** [comment]
@blocker999 która wersja filtrów?

**Comment by blocker999** [comment]
@MajkiIT sorry coś namieszałem
