### ISSUE TITLE
sport.pl

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#3662]
http://www.sport.pl/sport/7,144964,22373787,crotone-inter-transmisja-meczu-w-telewizji-i-online-w-internecie.html
Też tak macie?
<img width="488" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/30511854-046fdc80-9ae2-11e7-97e5-f5255e623f8a.PNG">

**Comment by xxcriticxx** [comment]
tak to balonik po social 

![screenshot from 2017-09-16 07-33-44](https://user-images.githubusercontent.com/15007183/30511934-69af11e6-9ab1-11e7-919b-e6fac1f273e1.png)

**Comment by hawkeye116477** [comment]
@xxcriticxx @MajkiIT @adreporter To już jest w filtrach Social, także temat do zamknięcia.

**Comment by MajkiIT** [comment]
@hawkeye116477 dzięki
