### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#3663]
Reklama na górze. 
![image](https://user-images.githubusercontent.com/29756590/30513060-63ac7d8c-9afd-11e7-8ebe-8bfd414a3bcc.png)

**Comment by hawkeye116477** [comment]
`pilot.wp.pl##.top-section`

**Comment by MajkiIT** [comment]
@HateAds @hawkeye116477 
Możecie sprawdzić to ? Chodzi mi czy czegoś nie popsuje.
`/^https:\/\/[a-z]{3,10}\.wp\.pl\/[a-zA-Z0-9_-]{200,}/$domain=pilot.wp.pl`

**Comment by hawkeye116477** [comment]
@MajkiIT Psuje, TV nie działa, kręci się i kręci i nic się nie dzieje.

**Comment by MajkiIT** [comment]
@hawkeye116477 Dzięki
