### ISSUE TITLE
benchmark.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3667]
http://www.benchmark.pl

Blokujemy ten pasek Hamag ?

**Comment by hawkeye116477** [comment]
@MajkiIT Tak
`benchmark.pl##.colWide.threeTilesAndLogo[style="background: rgb(235, 104, 120);"]`

**Comment by xxcriticxx** [comment]
@MajkiIT znowu odkurzacze

**Comment by MajkiIT** [comment]
@xxcriticxx gdzie odkurzacze?

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/30520425-f37144ca-9b7a-11e7-8c9c-cbf224de9984.PNG)
