### ISSUE TITLE
www.isobar.com/pl/home

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#37]
cookies trzeba poprawic strona pokazujie sie i znika

W ramach naszej witryny stosujemy pliki cookies w celu świadczenia Państwu usług na najwyższym poziomie. Korzystając ze strony wyrażasz zgodę na używanie cookie, zgodnie z aktualnymi ustawieniami swojej przeglądarki. Więcej szczegółów w naszej „Polityce Cookies”.

**Comment by MajkiIT** [comment]
poprawione
