### ISSUE TITLE
cmielow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3708]
cookies

**Comment by xxcriticxx** [comment]
@hawkeye116477 please add `###politykaprywatnosci`

**Comment by hawkeye116477** [comment]
@xxcriticxx Tak chyba będzie lepiej -> `###politykaprywatnosci:not(body):not(html)` :smile:.

**Comment by xxcriticxx** [comment]
podaj pulla to zatwierdze

**Comment by hawkeye116477** [comment]
@xxcriticxx Chłopie, na razie, to sporo jest do dodania. Jeszcze i PopupBlocker jest w kolejce 😄 .

**Comment by xxcriticxx** [comment]
@hawkeye116477 sam tego chciales ja ide dalej szukac

**Comment by hawkeye116477** [comment]
@xxcriticxx Heh, dzisiaj to normalnie jakieś oblężenie, tak sporo jeszcze nie było 😃 .

**Comment by xxcriticxx** [comment]
@hawkeye116477 i tak trzeba nas tutaj wiecej
