### ISSUE TITLE
mmarocks.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3710]
cos filmow nie wyswietla jakis fix potrzebny

**Comment by MajkiIT** [comment]
`@@||www.mmarocks.pl/wp-content/plugins/cookie-law-info/js/cookielawinfo.js$script,domain=www.mmarocks.pl`

**Comment by hawkeye116477** [comment]
Ale zaraz zaraz, przecież takie coś jest już w filtrach -> `@@||*/wp-content/plugins/cookie-law-info/js/cookielawinfo.js$script`. Dlaczego to nie działa? A jak dopisałem zamiast * pl, to o dziwo zaczęło działać.

**Comment by hawkeye116477** [comment]
@xxcriticxx To co piszemy wypracowanie dla gorhilla 😃 ?

**Comment by xxcriticxx** [comment]
@hawkeye116477 to cos dla ciebie napewno dostaniesz zlota gwiazdke

**Comment by hawkeye116477** [comment]
@xxcriticxx @MajkiIT Zgłoszone -> https://github.com/gorhill/uBlock/issues/3034.
PS: 1.13.10 jest ostatnią wersją, na której ta reguła działa poprawnie.

**Comment by xxcriticxx** [comment]
@hawkeye116477 dostales odpowiedz

**Comment by hawkeye116477** [comment]
@xxcriticxx Ok, zaraz poprawimy.

**Comment by xxcriticxx** [comment]
ok
