### ISSUE TITLE
nasygnale.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3712]
Od @gomoku
> Do przekazania na listę POL: polskie filtry do Adblocka i uBlocka:
> 
> `nasygnale.pl###wpAdvTop` resztki - pusty szary marnujący dużo miejsca konterner u góry oraz
> `nasygnale.pl###adv34` reklama po prawej, przykładowy url dla obydwu filtrów: 
> http://nasygnale.pl/kat,1025343,name,Kryminal,kategoria.html
> 
> `nasygnale.pl###adv05` resztki - pusty marnujący dużo miejsca kontener po środku, przykładowy url: http://nasygnale.pl/gid,17183403,img,17183486,page,5,title,Ptasznik-w-bagazu-studenta,galeria.html

https://github.com/azet12/PopupBlocker/issues/109

**Comment by xxcriticxx** [comment]
@hawkeye116477 a gomoku wpas tutaj nie moze?

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie może, bo @MajkiIT dał dla niego banana 😃 .

**Comment by MajkiIT** [comment]
Już mu zdjąłem

**Comment by xxcriticxx** [comment]
@hawkeye116477 teraz zapraszamy

**Comment by gomoku** [comment]
Dzięki i sorry za tamto.
