### ISSUE TITLE
jakwylaczyccookie.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3715]
cookies

**Comment by hawkeye116477** [comment]
@xxcriticxx Fajne ciastka, ale nasza lista to już chowa.

**Comment by xxcriticxx** [comment]
Ale moja tego nie schowała

**Comment by hawkeye116477** [comment]
@xxcriticxx No to komp do wymiany albo trzeba włączyć kosmetyczne, bo może jakimś cudem niechcący wyłączyłeś.
