### ISSUE TITLE
prawdaobiektywna.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3718]
Delicje
prawdaobiektywna.pl###mcpc > p 
prawdaobiektywna.pl###mcpc

Socjal
prawdaobiektywna.pl###hwm

**Comment by gzenio22** [comment]
mozna by tez bylo usadzic na tylku ostatnio dodane bo biega za nami na str glownej

**Comment by hawkeye116477** [comment]
Jeszcze to do sociala -> prawdaobiektywna.pl##h2:has-text(Polub nas)
A to na usadzenia w miejscu -> `prawdaobiektywna.pl##.theiaStickySidebar:style(position: static!important;)`, ale to chyba raczej do PopupBlockera, co sądzicie?

**Comment by gzenio22** [comment]
chyba tak bo gdzie indziej? te biegajace okna mozna traktowac jak popup

**Comment by hawkeye116477** [comment]
W I don't care już to mają, ale najwyraźniej pominąłem to, bo nie patrzyłem na strony pl, a tam mają z ponad 500 reguł na strony.pl.

**Comment by hawkeye116477** [comment]
W I don't care już to mają, ale najwyraźniej pominąłem to, bo nie patrzyłem na strony.pl, a tam mają z ponad 500 reguł na strony.pl. Może przydałby się jakiś skrypt co by wyłapał reguły strony.pl, których u nas nie ma. Co @MajkiIT?

**Comment by MajkiIT** [comment]
Spoko coś napiszę. Nie wiem czy dzisiaj ale będę miał to to do :D
