### ISSUE TITLE
z cyklu ciekawostka na dzis :D

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3719]
hmmm chyba niebawem nie tylko reklamy bedziemy musieli blokowac :D 

http://www.komputerswiat.pl/nowosci/internet/2017/37/the-pirate-bay-bez-reklam-mozliwe-ale-w-zamian-strona-obciazy-ci-cpu-do-100.aspx?utm_source=fb_KS&utm_medium=social&utm_campaign=fb_redakcja

**Comment by HateAds** [comment]
@gzenio22  No to nieźle :worried: Mój komputer to złom, który muli, a jak mu się jeszcze obciąży procka do 100 procent to będzie kaput.

**Comment by gzenio22** [comment]
moj jeszcze 8 miesiecy temu nie wytrzymal by minuty na takim obciazeniu

**Comment by MajkiIT** [comment]
:D fajny sposób .... @HateAds jak to złom?

**Comment by hawkeye116477** [comment]
@xxcriticxx Chyba też ma grata PC, bo sporo false-positivów ostatnio było z jego strony, a te reguły o których on pisał, to na liście ciastek były już z parę dni temu 😃 .

**Comment by xxcriticxx** [comment]
@hawkeye116477 critic ma zaduzo sprzentu a wina to chyba firefoxa i tej jednej ubo ver

**Comment by HateAds** [comment]
@MajkiIT Złom bo jest tak przestarzały.

**Comment by hawkeye116477** [comment]
Mój komp też stary, mam procesor AMD Athlon II X4 620 i sporo grzeje się w kółko dziadostwo. Ale w sumie to AMD, a PS4 Pro też ma AMD i też się nagrzewa sporo, więc chyba one już tak mają.

**Comment by xxcriticxx** [comment]
@hawkeye116477 dmuchales wiatrak ostatnio na cpu?

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie.

**Comment by blocker999** [comment]
@HateAds A co ja mam powiedzie o swoim ponad 7 letnim lapku, też myslałem że to złom ale wgrałem mu  moda z tąd : https://winclub.pl/
i chodzi jak rakieta, no i może kiedyś mu zmienie dysk na SSD, to nówki z marketu niemają szans, jak nówki to tylko poleasingowe.

**Comment by hawkeye116477** [comment]
@All To co, blokujemy koparę -> `||coin-hive.com^` ?

**Comment by hawkeye116477** [comment]
Widzę, że w filtrach uBlockowych gorhill dodał blokowanie kopary, no i super.

https://forum.dobreprogramy.pl/t/blokada-kryptokoparki-coin-hive-com-i-jej-serwerow-proxy/541474
Jeszcze to z forum jest przydatne, w razie jakby jakiś cwaniaczek wpadł na pomysł, by dodać do jakiegoś rozszerzenia po cichu koparę.
