### ISSUE TITLE
portal.abczdrowie.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3720]
Reklama u góry na głównej, w artykułach oraz social np tu : https://portal.abczdrowie.pl/7-naturalnych-sproszkowanych-substancji-dobrych-dla-jelit

**Comment by FadeMind** [comment]
Ja nic nie mam :( 
![2017-09-18 12_12_31-walka z wzdeciami i zaparciami - 7 naturalnych sproszkowanych substancji dobrych](https://user-images.githubusercontent.com/9846948/30537627-b2ed3c56-9c6a-11e7-9904-09711eeebfbb.png)

**Comment by blocker999** [comment]
@FadeMind rzeczywiście, pomyłka
