### ISSUE TITLE
arimr.gov.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#3722]
`/cookie.js$script` uwala www.arimr.gov.pl - efekt strona jest rozjechana - bo wszystkie obrazki wyjechały z banera w dół + zniknęło kilka kwadratowych kafelków, co widać na zrzucie ekranu "uwalone", więc trzeba dodać do whitelist:

!----------------Whitelist---------------------------
`@@||www.arimr.gov.pl/fileadmin/templates/js/cookie.js$script`
efekt naprawienia widoczny na zrzucie ekranu "poprawione"

Dodałem także taki filtr `www.arimr.gov.pl##body > .hidden-xs` ale już nie pamiętam po co, ale chyba usuwa jakiś zbędny element.

### Twoja konfiguracja
**Przeglądarka:**     
FF 55.0.3 32bit   

**Operating system:**
Windows 7 SP1 U 64bit

**Blocker:**
uBO v1.14.11b1

**Używane filtry:**
1. POL: polskie filtry do Adblocka i uBlocka​​​​​
2. POL: polskie filtry do uBlocka uzupelnienie​
3. Adblock & uBlock polish cookies filters

### Zrzut ekranu
1) [uwalone](https://s3.dodajfote.pl/2017/09/18/screenshot-www.arimr.gov.pl-nieprawidlowofb023.png)
2) [naprawione](https://s3.dodajfote.pl/2017/09/18/screenshot-www.arimr.gov.pl-prawidlowo31d88.png)

**Comment by xxcriticxx** [comment]
@hawkeye116477 related to #3710

**Comment by hawkeye116477** [comment]
@xxcriticxx Tutaj chyba chodzi o inny skrypt.

**Comment by hawkeye116477** [comment]
@gomoku Naprawione.

**Comment by gomoku** [comment]
@hawkeye116477 dodałeś bez `www.`, a ja specjalnie je dałem, bo na http://www.portalogloszen.arimr.gov.pl nie trzeba dawać bo tam problemów nie ma żadnych i można spokojnie blokować cookie.js, a w ogóle to znalazłem jeszcze http://m.arimr.gov.pl na którym trzeba, i żadnych innych poddomen nie znalazłem, więc proponuję już tak ostatecznie jeden z trzech wariantów:

1) zamienić
`@@||arimr.gov.pl/fileadmin/templates/js/cookie.js$script` na 
`@@||www.arimr.gov.pl/fileadmin/templates/js/cookie.js$script` oraz dodać
`@@||m.arimr.gov.pl/fileadmin/templates/js/cookie.js$script`
2) zamienić 
`@@||arimr.gov.pl/fileadmin/templates/js/cookie.js$script` na
`@@||arimr.gov.pl/fileadmin/templates/js/cookie.js$script,domain=www.arimr.gov.pl|m.arimr.gov.pl`

3) zamienić 
`@@||arimr.gov.pl/fileadmin/templates/js/cookie.js$script` na
`@@||arimr.gov.pl/fileadmin/templates/js/cookie.js$script,domain=~www.portalogloszen.arimr.gov.pl`

**Comment by hawkeye116477** [comment]
@gomoku Tak właściwie to z tego co widzę to na http://www.portalogloszen.arimr.gov.pl/ nie ma w ogóle skryptu cookie.js, więc teoretycznie mogło by tak zostać jak jest. Ale jeśli mam zamienić to chyba zrobimy to jednak tak: `@@/fileadmin/templates/js/cookie.js$script,domain=www.arimr.gov.pl|m.arimr.gov.pl`.
Ale skoro tam nie ma i jest ok, to nie wiem czy warto. Prosiłbym, by @MajkiIT wypowiedział się w tej kwestii.

**Comment by gomoku** [comment]
Masz rację nie ma cookies.js, więc dobrze zrobiłeś, niech zostaje tak jak jest, ja po prostu w loggerze w uBlocku miałem pewnie załadowane www.arimr.gov.pl albo m.arimr.gov.pl i zapomniałem zmienić na www.portalogloszen.arimr.gov.pl

**Comment by gomoku** [comment]
Tak czy inaczej, zanim to zostanie zamknięte, to mam takie pytanie czy też macie takie zniekształcone strzałki na banerze? (zaznaczyłem czerwonym kółkiem):
1) [Firefox](https://s3.dodajfote.pl/2017/09/18/firefoxbc717.png)
2) [Opera](https://s3.dodajfote.pl/2017/09/18/operaef207.png)

W Operze czasem gdy kliknie się w baner, który załaduje stronę, a potem cofnie stronę strzałką w lewo (czasem trzeba powtórzyć kilka razy) to strzałki się naprawiają (ale w Firefoxie nie):

3) [Opera dobre](https://s3.dodajfote.pl/2017/09/18/opera_dobrze7f915.png)

O co kaman, zwłaszcza, że testowałem z wyłączonymi dodatkami, jakiś glitch na stronie?

**Comment by hawkeye116477** [comment]
@gomoku Ta, też mam te zniekształcone strzałki na Vivaldim i Waterfoksie. A co do tej emotki, to u mnie na Waterfoksie 55.0.2 jest ok, wyświetla się prawidłowo.

**Comment by gomoku** [comment]
Ten defekt ze zniekształconymi strzałkami przestał się pojawiać, ale nie wykluczone, że kiedyś wróci, a u ciebie @hawkeye116477 też już ten defekt się nie pojawia?

**Comment by hawkeye116477** [comment]
@gomoku Też już nie mam, może admin strony przeczytał to co pisaliśmy i poprawił 😄 .
