### ISSUE TITLE
Polskie reguly social

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3725]
@MajkiIT Houston mamy problem, bo polskie reguły social nie działają na Adblocku. Więc może lepiej byłoby dopisać, że to jest tylko dla uBlocka albo coś poprawić. Tylko nie wiem co tu poprawiać, bo nawet ta wersja -> https://github.com/MajkiIT/polish-ads-filter/commit/b313199479d739727acab3793e42e321f459f015#diff-acd94f710b1c64f468452b4bff0e6a1b nie działa na Adblocku.

**Comment by gzenio22** [comment]
@MajkiIT  

No teraz dostanie mayla :D

**Comment by hawkeye116477** [comment]
Myślałem, że może to przez to, że dawałem te reguły typu has tekst. Ale wychodzi na to, że to już tak jest od działalności @blocker999. Przynajmniej lista z 29 lipca nie działa, a może i jeszcze wcześniejsza nie działa, tego nie sprawdzałem.

**Comment by MajkiIT** [comment]
A czemu tak twierdzisz?

**Comment by hawkeye116477** [comment]
@MajkiIT No, bo chyba Adblock nie obsługuje has czy obsługuje a ja się mylę i Adblock wcale nie jest taki ograniczony 😃 ?

**Comment by blocker999** [comment]
@hawkeye116477 Niewiem ja zawsze korzystałe z ublocka

**Comment by hawkeye116477** [comment]
@blocker999 No ja też właśnie, a tak z ciekawości zainstalowałem Adblock by zobaczyć czy wszystko tam działa, no i okazuje się, że lista Social tam nie działa. Znaczy tak właściwie to kiedyś korzystałem z Adblock Plus jak jeszcze nie było uBlocka, a jak już beta się pojawiła to trochę testowałem uBlocka i potem już jak stable wyszło, to wywaliłem Adblock Plus i już only uBlock 😃

**Comment by MajkiIT** [comment]
@hawkeye116477 Adblock nie zaznacza filtrów jako błędne. To może być wina dodania pl.

**Comment by hawkeye116477** [comment]
@MajkiIT https://www.virustotal.com/#/file/31a95d7af8c65a500f30fb0361e50c2cfdc5468f8f1cfeb447692f601f881222/relations . Chyba ten uBlock z AMO ma jakiegoś wirusa, no albo to false-positive. A uBlock z githuba gorhilla tego nie ma, więc może to Mozilla coś dokłada extra, by śledzić userów.

**Comment by hawkeye116477** [comment]
@MajkiIT To nie wina filtrów jak się okazuje, gdyż jak się okazuje w Waterfoksie, Adblock Plus blokuje wszystko. Wniosek z tego jest taki, że w Adblock i Adblock Plus na Chromium/Chrome jest jakiś bug, który powoduje to, że reguły kosmetyczne nie działają.

**Comment by hawkeye116477** [comment]
@MajkiIJak się okazuje w Waterfoksie, Adblock Plus blokuje wszystko. Więc to jest chyba jakiś bug tej wersji z Chromium.

**Comment by hawkeye116477** [comment]
@MajkiIT Jak się okazuje w Waterfoksie, Adblock Plus blokuje wszystko. Więc to jest chyba jakiś bug tej wersji z Chromium.
