### ISSUE TITLE
ulubiona main page

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3727]
![capture](https://user-images.githubusercontent.com/15007183/30565968-3665b374-9c98-11e7-82a7-3d4ea694955d.PNG)

**Comment by HateAds** [comment]
@MajkiIT na głównej wp został jeden pusty box ( migający ) po reklamie
![wp 1](https://user-images.githubusercontent.com/29756590/30566078-dfcc66d8-9cca-11e7-877f-fb3e3553ea0d.png)
Na sportowych faktach po wejściu w jakiś artykuł reklama suzuki
![wp 2](https://user-images.githubusercontent.com/29756590/30566091-ea72c15e-9cca-11e7-9f72-af322d5ca788.png)
I pytanie o money.pl czy ten pasek można zablokować ? ( pojawia się jak zjedziesz na dół )
![wp 3](https://user-images.githubusercontent.com/29756590/30566190-4deef5ea-9ccb-11e7-8e06-7c1502dfcb9e.png)

**Comment by HateAds** [comment]
Kolejna niespodzianka na głównej 
![image](https://user-images.githubusercontent.com/29756590/30567172-6ee3100c-9ccf-11e7-8471-1f5b0e7257de.png)

**Comment by MajkiIT** [comment]
@HateAds zostało tylko money i ten pasek

**Comment by hawkeye116477** [comment]
@MajkiIT Nic z tego, to się nadal wyświetla.

**Comment by hawkeye116477** [comment]
@MajkiIT Została jeszcze zasłona po popupie.

**Comment by MajkiIT** [comment]
@hawkeye116477 zasłona?

**Comment by hawkeye116477** [comment]
@MajkiIT Kurtyna
![screenshot_20170919_122446](https://user-images.githubusercontent.com/19818572/30588052-90018ab4-9d35-11e7-9417-0a7160d9b9d1.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 sprawdzisz?
`www.wp.pl##[style="position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; background-color: rgba(255, 255, 255, 0.6); opacity: 1; z-index: 100000;"]`

**Comment by hawkeye116477** [comment]
@MajkiIT Ta, teraz 🎸 gra 😄 .
