### ISSUE TITLE
domena.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3729]
Uwaga!
Strona korzysta z plików cookies. Odwiedzając nasz serwis zgadzasz się na ich przyjmowanie. Szczegółowe informacje w Polityce prywatności
Nie pokazuj komunikatu ponownie

**Comment by hawkeye116477** [comment]
`domena.pl###alert_container_id`
No i znowu w I don't care już to mają, chyba trzeba będzie wykombinować jakiś skrypt by wyciągnąć strony.pl, które są w i don't care, a u nas nie ma 😄 .
