### ISSUE TITLE
mamkomputer.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3730]
![screenshot from 2017-09-18 20-35-28](https://user-images.githubusercontent.com/15007183/30570707-fab8a91c-9cb0-11e7-8209-edc442e99fc9.png)

**Comment by hawkeye116477** [comment]
`mamkomputer.info###text-17` -> trochę reklam
A to to nie wiem czy to reklama czy do sociali "portal społecznościowy futurenet działa z ogromnymi sukcesami na rynku portali społecznościowych nieprzerwanie od r co różni nas facebooka"? -> mamkomputer.info##tr
`mamkomputer.info##a[href="https://plus.google.com/+Interset24Plit/about"]` -> social

**Comment by xxcriticxx** [comment]
@hawkeye116477 dziala
