### ISSUE TITLE
poczta.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3731]
@MajkiIT zrobimy wersje PRO za friko bez reklam?

poda ktos konto testowe?

![screenshot from 2017-09-18 20-42-16](https://user-images.githubusercontent.com/15007183/30570878-02561384-9cb2-11e7-8787-a71fb00b47e4.png)

**Comment by MajkiIT** [comment]
poczty ?

**Comment by xxcriticxx** [comment]
tak sure poczty
