### ISSUE TITLE
discopolonew.cba.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3737]
Pusty box po prawej na dole strony

**Comment by xxcriticxx** [comment]
@gzenio22 strona co podales jest `Firefox can’t find the server at discopolonew.cda.pl.`

na main jest pusty box na dole i na topie

**Comment by MajkiIT** [comment]
http://discopolonew.cba.pl/

`discopolonew.cba.pl##ul:nth-of-type(7)`
