### ISSUE TITLE
elblag.net

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3742]
Reklamy, z lewej, prawej, u góry i w środku chyba coś do zablokowania.
![screenshot_20170919_190621](https://user-images.githubusercontent.com/19818572/30605247-a983fbb0-9d6d-11e7-98e5-0a9d072bb4b3.png)

**Comment by MajkiIT** [comment]
```
www.elblag.net##[class^="baner"]
www.elblag.net##a[href^="http://elblag.net/redirect.php"]
```

**Comment by hawkeye116477** [comment]
@MajkiIT Jeszcze te „super tło" po bokach.

**Comment by MajkiIT** [comment]
@hawkeye116477 ale ja go nie posiadam u siebie :P . Taka sytuacja?

**Comment by hawkeye116477** [comment]
@MajkiIT Parę razy poodświeżaj, pokasuj dane i się pojawi. Bo nie zawsze się pojawia.

**Comment by gomoku** [comment]
U mnie na tych filtrach nie mam żadnych reklam (no chyba, że ta statyczna po środku się zalicza do usunięcia):
```
EasyPrivacy
EasyList
POL: polskie filtry do Adblocka i uBlocka​​​​​
POL: polskie filtry do uBlocka uzupelnienie​
Adblock & uBlock polish cookies
KAD - Przekręty​​
Popup Blocker PLUS ( PL )​​
```

![](https://s3.dodajfote.pl/2017/09/19/fffefed6cde.png)

**Comment by hawkeye116477** [comment]
`<body style="background-image: url("img/banery/203_odwierty-eu_supertlo.jpg"); background-attachment: fixed; background-repeat: no-repeat; background-position: center top;">`

@MajkiIT `www.elblag.net##body:style(background-image: none!important;)`

**Comment by MajkiIT** [comment]
```

elblag.net##[class^="baner"]
elblag.net##a[href^="http://elblag.net/redirect.php"]
elblag.net##[style="height:300px;padding-bottom:12px; margin-top: 13px; border-bottom: 1px dashed #ccc"]
elblag.net##body:style(background-image: none!important;)
```

**Comment by hawkeye116477** [comment]
@MajkiIT No i teraz 🎸 gra 😃 .

**Comment by gomoku** [comment]
Potwierdzam ze swojej strony, że teraz jest wszystko w porządku: pasek u góry mi wrócił, a i ta reklama po środku została usunięta, bo faktycznie też była do wycięcia.
