### ISSUE TITLE
nowastrategia.org.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3743]
**Information**                         | **Value**
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Opera Stable
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
Site: | http://www.nowastrategia.org.pl/stanislaw-pietrow-czlowiek-ktory-uratowal-swiat-od-zaglady-nie-zyje/

### Screenshoot
![2017-09-19 19_37_15-sklep](https://user-images.githubusercontent.com/9846948/30606446-0f7326ea-9d72-11e7-8774-d16f96e11699.png)

### Fix
```
/wp-content/uploads/*/URODZENI-PATRIOCI.gif$image,domain=nowastrategia.org.pl
/wp-content/uploads/*/msi-banner.png$image,domain=nowastrategia.org.pl
```

**Comment by MajkiIT** [comment]
`nowastrategia.org.pl###ticker-box`
