### ISSUE TITLE
evertiq.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#375]
Na głównej wszystko OK, ale jak wejdziemy w jakiegoś newsa to pojawia się reklama w tle. 
Na przykład:
http://evertiq.pl/design/16280

**Comment by mathew85** [comment]
Reklama w tle.

**Comment by F4z** [comment]
`||evertiq.pl/go/$popup`
`||static.evertiq.pl/bximg/1farnellnew/wallpaper-evertiq-pl.jpg$image`
Pierwsza reguła zablokuje wyskakujące okienka, druga tło z reklamą.

W przypadku uBlocka można użyć jeszcze tych reguł:
`evertiq.pl##script:inject(abort-on-property-write.js, window.open)`
`evertiq.pl##body:style(cursor: auto !important;)`
Mam nadzieję, że za dużo nie blokują.

**Comment by mathew85** [comment]
Zmienili coś i na głównej pojawia się reklama w tle.

**Comment by MajkiIT** [comment]
`||evertiq.pl/go/$popup`
`||static.evertiq.pl/bximg/*.png$image`
