### ISSUE TITLE
gloswielkopolski.pl & gazetawroclawska.pl & dzienniklodzki.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3751]
http://www.gloswielkopolski.pl/wiadomosci/poznan/komunikacja/a/mpk-kupilo-37-autobusow-przetestuje-tez-pojazd-elektryczny-zdjecia,12501074/
http://www.gazetawroclawska.pl/strefa-biznesu/wiadomosci/z-regionu/a/90-mln-zl-dla-przedsiebiorcow-kto-moze-je-dostac,12500602/

„W internecie treści i usługi nie są bezpłatne. Płaci reklama"

**Comment by xxcriticxx** [comment]
na pierwszej mam i jest w base64

a drugej mam tylko contentstream

**Comment by hawkeye116477** [comment]
http://www.dzienniklodzki.pl/serwisy/ekologia/akcja-segregacja/a/dlaczego-potrzebne-byly-nowe-zasady-segregacji-odpadow,12434046/

**Comment by MajkiIT** [comment]
To aktualne?

**Comment by hawkeye116477** [comment]
@MajkiIT  4 dni temu to było, a teraz już widzę, że tego nie ma.
