### ISSUE TITLE
krs-online.com.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3756]
![2017-09-21 12_17_47-cfosspeed v10 22](https://user-images.githubusercontent.com/9846948/30691123-f491a788-9ec6-11e7-816f-04717b7a9063.png)

**Comment by xxcriticxx** [comment]
@FadeMind podaj link? adguard?

**Comment by FadeMind** [comment]
@xxcriticxx http://www.krs-online.com.pl

**Comment by xxcriticxx** [comment]
ja tego nie widze na foxie/chromie
