### ISSUE TITLE
urle.co

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#3757]
nie mozna zaczac sciagac plikow, np, http://urle.co/28OJ

**Comment by xxcriticxx** [comment]
@lukjan32 easylist to blokuje nie polskie filtry

**Comment by lukjan32** [comment]
tam wyslac?

**Comment by xxcriticxx** [comment]
tak

nacisniesz na click to continue dwa razy i dziala potem jest timer 5 sec

**Comment by xxcriticxx** [comment]
ps strona jest nie polska 

@MajkiIT prosze dodaj tag `INVALID`

**Comment by lukjan32** [comment]
no, jak dodam do wyjatkow

**Comment by lukjan32** [comment]
juz to zmienili

**Comment by xxcriticxx** [comment]
ok zamykam
