### ISSUE TITLE
archiwum.rp.pl & info.rp.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3758]
Dziura po ciastkach: `archiwum.rp.pl,info.rp.pl##html > body:style(margin-top: 0px!important;)`
Podziękowania należą się dla @gomoku 😄 .
https://github.com/azet12/PopupBlocker/issues/127

**Comment by MajkiIT** [comment]
@hawkeye116477 @xxcriticxx sorry za moją nieaktywność. Jestem na imprezie integracyjnej i nie za bardzo mam jak siąść do kompa.

**Comment by hawkeye116477** [comment]
@MajkiIT Ok
