### ISSUE TITLE
xperiasite.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3759]
pusty box

@hawkeye116477 jest to w social?

![capture](https://user-images.githubusercontent.com/15007183/30711344-7096fe6e-9ed6-11e7-85ef-641e79f8feda.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie ma -> `xperiasite.pl###fbox-background`.

Ale jeszcze kicius mnie prosi, by wyłączyć Adblocka 😃 .

**Comment by xxcriticxx** [comment]
@hawkeye116477 kotek nie static?

**Comment by hawkeye116477** [comment]
@xxcriticxx Może, ale jakie oczy proszące ma. Ale nie ładnie, tego kota ściągnęli ze Shreka .... 😄 .

**Comment by MajkiIT** [comment]
To static.

**Comment by hawkeye116477** [comment]
@MajkiIT Czyli nie blokujesz? Mówisz, niech kiciuś zostanie i namawia innych do wyłączenia uBlocka na tej stronie 😄 .

**Comment by hawkeye116477** [comment]
@MajkiIT Czyli nie chowasz kota do wora? Mówisz, niech kiciuś zostanie i namawia innych do wyłączenia Adblocka/uBlocka na tej stronie 😄 .

**Comment by MajkiIT** [comment]
Tak niech zostanie. Chyba dużej krzywdy nie robi.

**Comment by hawkeye116477** [comment]
@MajkiIT No niby tak, racja, tylko się patrzy i mówi „ej stary wyłącz tego uBlocka, nie bądź taki, potrzebuję kasy na mleko i whiskasa 😃 ".
