### ISSUE TITLE
zmiksowani.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3760]
to jest wiadomosc czy ad block 

![capture](https://user-images.githubusercontent.com/15007183/30711389-9108e9aa-9ed6-11e7-8e76-5c8262f6f585.PNG)

**Comment by gzenio22** [comment]
jakas niby notka ale zdjac mozna 

zmiksowani.pl##.text-center.alert-danger.alert
