### ISSUE TITLE
noizz.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3764]
Przez przypadek chyba psujemy tam mozliwosc wyswietlenia zdjecia z instagrama 

Przykładowy link: https://noizz.pl/lifestyle/serafin-kontra-wroclawski-bar-znany-youtuber-pokazal-jak-nie-nalezy-wykorzystywac/ykl4jjw?utm_source=fb&utm_medium=social&utm_campaign=TA_Onet

kreci sie pol ksiezyc niebieski ale screen nie wskakuje

**Comment by xxcriticxx** [comment]
@gzenio22 jakis screenshot please

**Comment by gzenio22** [comment]
http://prntscr.com/gobszo

A powinno pokazac to 

http://prntscr.com/gobtjq

**Comment by xxcriticxx** [comment]
u mnie dziala 

zapytaj @hawkeye116477 on jest social guru

![capture](https://user-images.githubusercontent.com/15007183/30747559-a74a56d6-9f7b-11e7-85e4-407164c25c0e.PNG)

**Comment by hawkeye116477** [comment]
Jeśli to filtry social i psują Instagram, no to tak ma być, w końcu to antysocjalistyczne 😃 .

**Comment by hawkeye116477** [comment]
@gzenio22 U mnie też ok, a to nie dobrze, trzeba to dodać do sociala:
```
noizz.pl##a[href*="facebook.com"]
noizz.pl##.contentShareButtons
||www.facebook.com/*/plugins/*$domain=pulsembed.eu
```

**Comment by gzenio22** [comment]
@hawkeye116477 to nic nie zmienilo :(

Ja tez nie mam wlaczonego nic czego ty nie masz :P

**Comment by hawkeye116477** [comment]
@gzenio22 Ale ty chciałeś to odblokować, ja natomiast dałem reguły na blokadę, bo u mnie tego nie blokuje 😄 .

**Comment by gzenio22** [comment]
@hawkeye116477 czyli blokujemy nawet zdjecia z portali spolecznosciowych jesli sa czescia artykulu? hmmm nie uwazasz ze to zbyt drastyczne?

**Comment by hawkeye116477** [comment]
@gzenio22 No może i masz rację, ale z drugiej strony jest to jednak widget socialowy. Ok, na razie to zostawiam.

**Comment by gzenio22** [comment]
teraz pytanie jaka regula to u mnie blokuje? Xd

**Comment by hawkeye116477** [comment]
@gzenio22 Zerknij do loggera uBlocka, szukaj tam pulsembed.

Czyli to do dodania:
```
noizz.pl##a[href*="facebook.com"]
noizz.pl##a[href*="twitter.com"]
noizz.pl##a[href*="instagram.com"]
noizz.pl##.socialButtons
noizz.pl##.socialMiniBox
noizz.pl##.contentShareButtons
```

**Comment by gomoku** [comment]
U mnie to zdjęcie także normalnie ładuje się na: FF, Operze i Vivaldi + uBO.
A w ogóle to u @gzenio22 wcięło nie tylko zdjęcie, ale także cały ten panel po prawej...
@gzenio22musisz podać więcej szczegółów: jaka przeglądarka / adbocker / listy fitlrów / system?

**Comment by gzenio22** [comment]
system W 10
ublock 
http://prntscr.com/guch5a
http://prntscr.com/guchbv

Plus te 2 polskie dostepne oryginalnie w ubo

**Comment by hawkeye116477** [comment]
@gzenio22 Wywal Adguard supplement, to dla Adguarda, a nie uBlocka, English filter też zbędny, Easy List without element hiding albo EasyList, zdecyduj się, obie listy są podobne, tyle że jedna jest bez ukrywania elementów, no i oczywiście albo AAK Cont albo uBlock Protector.

**Comment by gzenio22** [comment]
ktora to easy list bo sie juz pogubilem @hawkeye116477

**Comment by hawkeye116477** [comment]
@gzenio22 EasyList masz pod Reklamy, ona jest z ukrywaniem elementów, a  Easy List without element hiding jest bez ukrywania elementów. 
Fanboy's Anthirdparty social psuje te zdjęcia z Instagrama, tam nawet masz ostrzeżenie napisane, że może psuć komentarze facebookowe, itd, itp.

**Comment by gomoku** [comment]
Podstawowa sprawa to jest taka, czy zanim założyłeś tutaj wątek to czy w ogóle sprawdzałeś czy problem występuje przy włączonych tylko samych 4 polskich listach?:
`POL: polskie filtry do Adblocka i uBlocka​​​​​`
`POL: polskie filtry do uBlocka uzupelnienie​`
`Adblock & uBlock polish cookies filters​​​​​`
`Polskie reguly social​`

Ale to raczej pytanie retoryczne, bo już wiem, że tego nie zrobiłeś, bo to nie nasze listy uwalają ci tę stronę, tylko ta lista: `Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​`, więc kolego nie ten adres do zażaleń, na następny raz pofatyguj się bardziej zanim coś zgłosisz i nie marnuj naszego czasu, czy to takie trudne, tak czy inaczej tu masz filtry naprawcze:
`@@||connect.facebook.net/pl_PL/sdk.js$script,domain=pulsembed.eu`
`@@||staticxx.facebook.com/connect/xd_arbiter/r/*$subdocument,domain=pulsembed.eu`

**Comment by gzenio22** [comment]
@gomoku ok dałeś mi tu wywód życia nie mam zamiaru się z tobą kłócić spierdzieliłem tym razem przyznaje się bez bicia ale to nie znaczy ze nie czytam stworzyłem jeden temat gdzie się pomyliłem a ty na mnie wyskakujesz jak bym zrobił takich tematów setkę każdemu możne zdazyc się pomyłka nawet komuś takiemu kto w czymś siedzi latami a ja bawię się i staram się wam pomagać zaledwie od kilku miesięcy wiec proszę nie unos się bo nie gadasz z gimbusem

**Comment by gomoku** [comment]
No dobra może i moja krytyka była zbyt szybka, ale nie miałem złych intencji, ani zamiaru się unosić, i wiem, że każdemu pomyłki się zdarzają nawet mi, tylko, że zanim to napisałem to specjalnie 2 razy się zastanowiłem gdzie i jak mogłeś się pomylić, żeby znaleźć jakieś usprawiedliwienie dla ciebie i żeby właśnie niepotrzebnie cię nie skrytykować, ale nie znalazłem odpowiedzi na czym miałaby polegać ta pomyłka?

**Comment by gomoku** [comment]
No to ujawnisz w końcu na czym polegała ta tajemnicza pomyłka, czy to tylko taki wykręt i linia obrony żeby móc się na mnie odszczekać?

**Comment by gzenio22** [comment]
Moja pomylka polegala na tym ze mialem zle filtry a błąd na tym ze ich faktycznie nie sprawdziłem przepraszam za zamieszanie moja wina moja wina moja bardzo wielka wina bije sie w piers mam nadzieje ze to nie schszani w przyszlosci kontaktu miedzy nami tak jak mowie nadal sie ucze a w tym wypadku popelnilem blad nowicjusza

**Comment by gomoku** [comment]
Słuchaj nie miałem i nie mam zamiaru cię linczować / krzyżować / zmuszać do przeprosin / klękania na kolanach, tylko chciałem dowiedzieć się na czym niby polegała ta pomyłka, bo jeśli się widzi, że się ma prawie 30 list włączonych, to nie wiem jak można się pomylić i zapomnieć ich wyłączyć, bo to tak jak wjeżdżać samochodem w ostry zakręt, który się wyraźnie widzi z daleka i zapomnieć o istnieniu kierownicy, przez co nie skręcić i wjechać prosto w drzewo, więc nie wiem, czy ktoś w to uwierzy w takie tłumaczenie, bo jest z deka dziwne, tak czy inaczej jeżeli zbyt mocno naskoczyłem na ciebie to też przepraszam ze swojej strony, a ja się na ciebie nie obrażam czy coś, a kontakt pozostanie ok bo umiesz się pokajać, więc zapominam o sprawie.
