### ISSUE TITLE
opensubtitles.org/pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3765]
Patrzcie jaka niespodzianka mnie spotkala

http://prntscr.com/goe6no

Update 17,38
opensubtitles.org/pl###fadeSub
opensubtitles.org/pl###lightSub

update 17,44 

@blocker999 zdejmij wyszarzenie przy logowaniu w sesie dodaj do popupblockerplus

opensubtitles.org/pl###fade

**Comment by blocker999** [comment]
OK

Na przyszło bardzo prosze bezpośrednio

**Comment by gzenio22** [comment]
@blocker999 ok nie ma problemu :)
