### ISSUE TITLE
bgzoptima.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#3766]
nie mozna sie zalogowac na konto www.bgzoptima.pl

musialem dodac do wyjatkow.

**Comment by MajkiIT** [comment]
ja nie mam tam konta ... może jakiś zrzut lub opis...

**Comment by lukjan32** [comment]
po wpisaniu hasla, jak daje na przejdz, to nic sie nie dzieje.

**Comment by MajkiIT** [comment]
u mnie jest ok ...

**Comment by lukjan32** [comment]
aha, dziwne

**Comment by lukjan32** [comment]
pomoglo czyszczenie ciasteczek na stronie banku.

**Comment by krystian3w** [comment]
@Lukjan37 jak ci działa nowe https://www.bnpparibas.pl/gooptima

**Comment by Lukjan37** [comment]
nie mam jiuz konta w banku, zrezygnowalem juz przed tym przenoszeniem.
