### ISSUE TITLE
otomoto.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#3769]
Z regułami włączonymi nie wyświetla się cała strona:

`https://mbmotors-poznan.otomoto.pl/`

![image](https://user-images.githubusercontent.com/11385099/30774520-1eaddfaa-a084-11e7-92f7-4ab76ca5984f.png)

**Comment by MajkiIT** [comment]
otomoto.pl#@#[class$="-ads"]

**Comment by MajkiIT** [comment]
@mathew85 Dzięki
