### ISSUE TITLE
www.mediaexpert.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#377]
nowe reklamy lewa prawa tylko teraz z id=

idzie to zablokowac przez imie jpg pliku?

http://www.mediaexpert.pl/ad.php?id=894
http://www.mediaexpert.pl/temp/filemanager_up/ucho_darmowa.png

http://www.mediaexpert.pl/ad.php?id=7818
http://www.mediaexpert.pl/temp/filemanager_up/ME_ucho_dj.jpg

**Comment by MajkiIT** [comment]
to usuwa za dużo www.mediaexpert.pl##a[href^="http://www.mediaexpert.pl/ad.php"
podobnie to ||www.mediaexpert.pl/temp/filemanager_up/

**Comment by xxcriticxx** [comment]
a cala temp folder?

**Comment by MajkiIT** [comment]
będzie to samo.

**Comment by xxcriticxx** [comment]
rozwiazania niema

**Comment by xxcriticxx** [comment]
uzywajac element picker 


    Net filters
        ||www.mediaexpert.pl/temp/filemanager_up/ucho_darmowa.png
    Cosmetic filters Click, Ctrl-click
        ###editorimg-11451309158921[alt="darmowa dostawa right"]
        ##div
        ##a[href^="http://www.mediaexpert.pl/ad.php"]
        ##.bann
        ###ban_left
        ##.clearfix2.relative.contact_bar
        ##.page_header
