### ISSUE TITLE
fili.tv

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#3770]
Przy próbie przewinięcia pojawia się popup:

![image](https://user-images.githubusercontent.com/11385099/30774580-0730d138-a085-11e7-95e7-db9b7bc2f6df.png)

`https://fili.tv/serial/mr-robot/s01e08/eps17wh1ter0sem4v/9386`

**Comment by xxcriticxx** [comment]
strona jest dead `||fili.tv`

**Comment by MajkiIT** [comment]
@mathew85 dodaj sobie filtry kad /stop przekrętom/ https://www.certyficate.it/adblock/
