### ISSUE TITLE
tygodniksiedlecki.com

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#3776]
! http://tygodniksiedlecki.com
! http://tygodniksiedlecki.com/t7366-to.nie.kurort..to.wiezienie.htm

! reklama flash po środku
`tygodniksiedlecki.com##body > .container > .post-wrapper.row > .col-xs-12.col-sm-12.co-md-8.col-lg-8 > .article > .article-wrapper > .avoid-print-this:nth-of-type(3)`
! reklama środkowy tekst
`tygodniksiedlecki.com##body > .wrapper > .container > .post-wrapper.row > .col-xs-12.col-sm-12.co-md-8.col-lg-8 > .article > .article-wrapper > .avoid-print-this:nth-of-type(3)`
! reklama u góry nad headerem (zrzut ekranu 3)
! reklama u góry pod headerem (również zrzut ekranu 3)
! reklama pod zdjęciem pod headerem (zrzut ekranu 4)
! resztki po reklamie pusty średni kontener po prawej
! resztki po reklamie pusty mały kontener na środku (zrzut ekranu 5)
! resztki po reklamie pusty mały kontener na dole 1
! resztki po reklamie pusty mały kontener na dole 2 (zrzut ekranu 7)
! resztki po reklamie pusty duży kontener na dole  (zrzut ekranu 6)
! resztki po reklamie pusty wielki kontener na dole 1 (również zrzut ekranu 7)
! resztki po reklamie pusty wielki kontener na dole 2 (również zrzut ekranu 7)
`tygodniksiedlecki.com###banner-top-top, .mb-5.row, #baner_glowna_polecamy, #baner_publicystyka1, #baner_dyzur1, #baner_prawa_dyzur1, #baner_glowna_dol1, #baner_lewy, #baner_prawa_aktualnosci, #baner_prawy1` lub
`tygodniksiedlecki.com###banner-top-top, .mb-5.row, div[id^="baner"]`

Zrzut ekranu 3:
![](https://s3.dodajfote.pl/2017/09/23/reklamy135e2b.png)

Zrzut ekranu 4:
![](https://s3.dodajfote.pl/2017/09/23/reklamy2a8f28.png)

Zrzut ekranu 5:
![](https://s3.dodajfote.pl/2017/09/23/kontenery2d66e0.png)

Zrzut ekranu 6:
![](https://s3.dodajfote.pl/2017/09/23/kontenery33488e.png)

Zrzut ekranu 7:
![](https://s3.dodajfote.pl/2017/09/23/kontenery1e752b.png)

**Comment by MajkiIT** [comment]
Na moje oko wystarczy tylko tak ...
`tygodniksiedlecki.com##[id^="wrap_scale_"]`

**Comment by gomoku** [comment]
Ostatecznie musi być tak: 
`tygodniksiedlecki.com##[id^="wrap_scale_"], #banner-top-top`
bo na tylko twoim zostaje czarny margines nad headerem:

![](https://s3.dodajfote.pl/2017/09/24/czarnymarginesc6a24.png)
