### ISSUE TITLE
strony filmowe

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3780]
@hawkeye116477 zerkniesz moze cos zlapiesz jakies social albo cos innego

http://www.boxfilm.pl/
http://cda-x.pl 
http://ekinomaniak.tv/
http://seriale.co/
https://openkatalog.com/
http://paczamy.pl

**Comment by FadeMind** [comment]
Na http://cda-x.pl po kliknięciu na odtwarzacz pojawia się na chwilę popup.
Sample http://cda-x.pl/filmy/gunned-down-gotowy-na-zemste/

Do tego CSS 
![2017-09-24 14_17_45-pogoda](https://user-images.githubusercontent.com/9846948/30782469-2bc2ca2a-a133-11e7-8772-3d4d136e93aa.png)

**Comment by xxcriticxx** [comment]
Podwójny search bar

**Comment by MajkiIT** [comment]
@FadeMind otwiera się pusty popup i potem go zamykam. Więcej nie zrobię za pomocą filtrów.
@xxcriticxx Tak jest strona zrobiona.

**Comment by AdamWr** [comment]
@FadeMind na ten popup możesz sprawdzić tę regułę:
`vidoza.net#%#Object.defineProperty(window,'pus_disabled',{value:"1"});`
A to dodatkowo żeby dwa razy się przycisk do odtwarzania nie wyświetlał:
`vidoza.net#%#document.cookie = "soP0=1";`

**Comment by hawkeye116477** [comment]
Nic tam nie do listy Social.

**Comment by xxcriticxx** [comment]
ok zamykamy

**Comment by adamibeata** [comment]
https://cda-tv.pl
