### ISSUE TITLE
eglobalcentral.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3785]
socjal na dole ja bym musial zakryc caly banner a i nie wiem czy zabieramy cos wiecej?

**Comment by xxcriticxx** [comment]
@gzenio22 spać nie możesz?

**Comment by gzenio22** [comment]
puki moge to kopie zaraz mi limit zaskoczy :D

**Comment by xxcriticxx** [comment]
Kiedy zmiana netu?

**Comment by gzenio22** [comment]
@xxcriticxx w grodniu koniec umowy

**Comment by hawkeye116477** [comment]
@gzenio22 Tego nie da się zablokować bez zakrywania bannera z info o zniżce, gdyż to jest jako jeden obrazek.

**Comment by gomoku** [comment]
Czy dwa i pół tygodnia to za mało żebyście się w końcu zdecydowali i zamknęli ten wątek?

**Comment by hawkeye116477** [comment]
Właściciela zmienili i zaczęli oszukiwać?
