### ISSUE TITLE
kon-sul.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3786]
Cookies

**Comment by gzenio22** [comment]
kon-sul.pl###BortosCookie

Powinno zaradzic :)

**Comment by blocker999** [comment]
@xxcriticxx To chyba ten czas.

@gzenio22 pasuje

**Comment by hawkeye116477** [comment]
Pewnie @xxcriticxx ma I don't care about cookies, oni to dali jako regułę ogólną -> `###BortosCookie:not(body):not(html)`.

**Comment by gzenio22** [comment]
@hawkeye116477 ze ci sie chce przekopywac inne listy :D

**Comment by hawkeye116477** [comment]
@gzenio22 A co to taka fatyga, ctrl+f, kopiuj wklej regułę i od razu znajduje 😛 .

**Comment by xxcriticxx** [comment]
@gzenio22 nie drudno sprawdzic

**Comment by gzenio22** [comment]
Dobrze ze nie korzystamy wszyscy z tych samych filtrow bo nikt z nas by nic nie widzial Xd

**Comment by xxcriticxx** [comment]
@gzenio22 dame rade luknie na script 

https://cookie.bortos.pl/BortosCookie-latest.js

**Comment by hawkeye116477** [comment]
@xxcriticxx A więc można też zrobić tak -> `||cookie.bortos.pl^$third-party`. Tylko czy to czegoś nie sknoci? Bo ja się na tych skryptach js nie znam 😃 .
Dlatego proszę o opinie @MajkiIT co tu lepiej dać.

**Comment by xxcriticxx** [comment]
@MajkiIT jak bendzie lepjej?

@hawkeye116477 znalazlem tylko 8 stron stym scriptem

**Comment by MajkiIT** [comment]
Dla świętego spokoju zrobiłbym tak `==> ||cookie.bortos.pl/*cookie*.js$script` nie wiem co może być serwowane na tym serwerze.
