### ISSUE TITLE
Ulubiona kolejny raz

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#3788]
Nasza ukochana strona wpReklama powraca z kolejnymi reklamami na głównej.
![image](https://user-images.githubusercontent.com/29756590/30834635-50b6afaa-a254-11e7-8724-6bebf70e62be.png)

**Comment by xxcriticxx** [comment]
na chromie mam to samo co @HateAds na foxie mam migajaca reklama empik

**Comment by FadeMind** [comment]
![2017-09-26 06_01_22-](https://user-images.githubusercontent.com/9846948/30842091-30771b54-a280-11e7-807b-b2710f8288d1.png)

**Comment by MajkiIT** [comment]
Już powinno być ok.
