### ISSUE TITLE
www.filmyiseriale.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#379]
http://www.filmyiseriale.tv/odcinek/14376/Odcinek-22.html

Jeśli korzystasz z wtyczki blokującej reklamy, możesz mieć problemy z odtwarzaniem odcinków!
Aby tego uniknąć, odblokuj reklamy na całej powierzchni filmyiseriale.tv lub wykup konto VIP w naszym serwisie

adblocker ??
+
15 sec reklamy before movie starts

**Comment by MajkiIT** [comment]
Kiedyś przysiadałem do tego i nie znalazłem wyjścia, ale siądę jeszcze raz.

**Comment by MajkiIT** [comment]
Problem rozwiązany
https://github.com/reek/anti-adblock-killer/issues/1057
