### ISSUE TITLE
finanse.wp.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#3791]
https://finanse.wp.pl/dowod-osobisty-dla-przestepcy-jest-wazniejszy-niz-karta-kredytowa-pozwala-wyludzic-nawet-30-tys-zl-6169576540039297a
Reklama na górze ( jak się nie pojawi za 1 razem to musicie odświeżyć stronę )
![image](https://user-images.githubusercontent.com/29756590/30865873-0ea98b9e-a2d8-11e7-9614-1361a253c797.png)

**Comment by gzenio22** [comment]
finanse.wp.pl##body > div:nth-of-type(1)

Ktos moze podniesc gorna belke w miejsce reklamy?

**Comment by MajkiIT** [comment]
Dzięki ...
