### ISSUE TITLE
wyborcza.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#3793]
http://wyborcza.pl/reklamaGW

Ten filtr `pl##[class*="reklama"]` z POL: polskie filtry do Adblocka i uBlocka uwala http://wyborcza.pl/reklamaGW oraz wszystkie jej podstrony, nie wiem czy to zamierzone czy nie:

![](https://s3.dodajfote.pl/2017/09/26/ss0506d.png)

**Comment by MajkiIT** [comment]
@gomoku Dzięki .
