### ISSUE TITLE
play.google.com, translate.google.pl & maps.google.com

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3795]
Niespodzianka, wujek coś zmienił i wskoczył komunikat ciasteczkowy 😃 .
![screenshot_20170927_000708](https://user-images.githubusercontent.com/19818572/30886597-eb8adcc2-a317-11e7-9759-fa2995e4858e.png)

**Comment by gzenio22** [comment]
@hawkeye116477 wes jeszcze dodatkowo zerknij czy jak wejdziesz na google tlumacz nie wyskakuje ci doslownie na setna sekundy okienko jakies?

**Comment by hawkeye116477** [comment]
@gzenio22 Okienko nie wyskakuje, jedynie na translate.google.pl widzę przypomnienie o polityce wujka.
```
google.*##.gb_g.gb_Nc.gb_nd
google.*###gba:style(height: 60px!important;)
```
