### ISSUE TITLE
film.wp.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#3796]
Znowu imperium wp w akcji ( reklama na górze )
![image](https://user-images.githubusercontent.com/29756590/30905198-630996ba-a374-11e7-9670-00bdbbe1738a.png)
@MajkiIT Sorki, że aż tyle roboty przez "łupe" masz, ale z tego co widzę oni często coś zmieniają.

**Comment by MajkiIT** [comment]
@HateAds Dzięki
