### ISSUE TITLE
mokotow.waw.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3798]
Cookies

**Comment by gzenio22** [comment]
u mnie nie ma

**Comment by xxcriticxx** [comment]
@blocker999 zobacz co masz za ver ubo u mnie tez czasami przycina

**Comment by blocker999** [comment]
@xxcriticxx Ubo to 1.14.10 niewiem może się znowu myle ale sprawdzałem to na kilku przeglądarkach i dalej są ciastka, może @MajkiIT to zobaczy ?

**Comment by MajkiIT** [comment]
U mnie ta reguła to łapie ... `##[id^="cookies-message"]`

**Comment by blocker999** [comment]
@MajkiIT to umnie?

**Comment by MajkiIT** [comment]
@blocker999 nie, u mnie...

**Comment by xxcriticxx** [comment]
@MajkiIT jest to na liscie?

@blocker999 jaki masz setup?

**Comment by MajkiIT** [comment]
@xxcriticxx oczywiście https://github.com/MajkiIT/polish-ads-filter/blob/55bd4c1579c77adb1035c2d42594283798f36fd5/cookies_filters/adblock_cookies.txt#L1209
