### ISSUE TITLE
www.mediaexpert.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#38]
reklama

**Comment by MajkiIT** [comment]
Zablokowanie ukryje elementy które podlegają promocjom.

**Comment by xxcriticxx** [comment]
po lewej stronie
http://www.mediaexpert.pl/ad.php?id=6592
po prawej stronie 
http://www.mediaexpert.pl/ad.php?id=6630

**Comment by MajkiIT** [comment]
Filtr nieoptymalny. Za chwilę zmienią id i będzie widać. Musiałbym dodać ||www.mediaexpert.pl/ad.php?id= ale to ukrywa wszystko.

**Comment by xxcriticxx** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/365
