### ISSUE TITLE
krotoszyn.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3800]
Cookies

**Comment by gzenio22** [comment]
pusciutko :)

**Comment by blocker999** [comment]
niewiem ale chyba to jest bo na cztery przeglądarki na trzech były ciasteczka, więc zapraszam kogoś trzeciego na ciastka

@gzenio22 na jakiej przeglądarce patrzałeś?

**Comment by gzenio22** [comment]
(Chr) opera i FF

**Comment by blocker999** [comment]
Na operze też ich niemiałem a FF niesprawdzałem natomiast mam to na slimjet, waterfox i vivaldi.
