### ISSUE TITLE
skrstrzelce.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3802]
Reklamy na dole

**Comment by gzenio22** [comment]
skrstrzelce.pl##a[href="http://www.pulawy.com/507-filmy-reklamowe/lang/pl-PL/default.aspx"] 
skrstrzelce.pl##a[href="http://www.pulawy.com/362-agrolider/lang/pl-PL/default.aspx"]

@MajkiIT @hawkeye116477 sprawdzcie to prosze bo sie troche tego [href kurde obawiam
