### ISSUE TITLE
aptekacentrum.lublin.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3804]
Tło - " Bebilon "

**Comment by xxcriticxx** [comment]
ja mam cookies

![capture](https://user-images.githubusercontent.com/15007183/30938005-970a23f8-a3a6-11e7-9dea-f24c1ab1a78f.PNG)

**Comment by blocker999** [comment]
@xxcriticxx ja też ale ja niejestem wiarygodny, może @MajkiIT też?

**Comment by xxcriticxx** [comment]
@blocker999 jestes dont worry ja @MajkiIT od poczatku nie wierze :)

@hawkeye116477 cos generic da rade? mam wiecej stron stym sammym scrptem

**Comment by MajkiIT** [comment]
`||aptekacentrum.lublin.pl/images/*1920x1080.jpg$image`

@xxcriticxx musiałeś to powiedzieć?

**Comment by hawkeye116477** [comment]
@xxcriticxx Jasne, w I don't care mają to z dodatkiem, więc raczej też tak zrobimy -> ###div_ciastka_info:not(body):not(html) 😄 .
