### ISSUE TITLE
kidl.org.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3808]
cookies

**Comment by gzenio22** [comment]
u mnie czysto nawet po wylaczeniu ubo lol dziwne

**Comment by hawkeye116477** [comment]
@gzenio22 Tu jest -> http://kidl.org.pl/index.php?page=kontakt. To to samo co na poprzednich stronach.

**Comment by gzenio22** [comment]
kurde cwaniaki sie ukryli
