### ISSUE TITLE
wmeritum.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#381]
Strona podczas ładowania robi się pusta.

**Comment by xxcriticxx** [comment]
umnie dziala poprawnie jakie cookie filtry masz?

**Comment by mathew85** [comment]
Polskie (v.1.54) oraz Prebake. Jest OK jak się raz załaduje bez filtrów. Jeżeli wyczyszczę cache (Ctrl+F5) to będzie znikała.

**Comment by xxcriticxx** [comment]
wyloncz prebake zostaw tylko polskie i testuj

**Comment by mathew85** [comment]
Jest OK też z obiema listami, ale jak odświeżę kilka razy to potrafi się załadować pusta. W logach znalazłem, że trochę inaczej wygląda kolejność wywoływania reguł:
http://imgur.com/jU1ZLfw

Jeżeli działa, to zawsze to wygląda tak jak z lewej strony. Jak nie to tak jak z prawej.
Nie jestem pewien czy ma to jakiś związek.
