### ISSUE TITLE
tamizo.p

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3835]
cookies

**Comment by gzenio22** [comment]
tamizo.pl###dc1-1506610434695
tamizo.pl###dcc-1506610434695

**Comment by hawkeye116477** [comment]
@gzenio22 To jest random. Tutaj lepiej dać coś ze style albo `||www.tamizo.pl/js/jquery.cookiesinfo.js$script`. Tylko nie wiem czy zablokowanie skryptu czegoś nie sknoci, dlatego proszę o opinię @MajkiIT.

**Comment by MajkiIT** [comment]
@hawkeye116477 filtr będzie ok.
