### ISSUE TITLE
studiotg.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3836]
cookies

**Comment by gzenio22** [comment]
studiotg.pl###stg-privacy-bar

u mnie ublock to blokuje musialem wylaczyc ubo zeby to zobaczyc

**Comment by hawkeye116477** [comment]
@gzenio22 Czyli masz I don't care about cookies albo ciasteczkowego potwora fanboya 😃 .
Oni mają coś takiego -> `###stg-privacy-bar:not(body):not(html)`, ale ja to bym jednak chyba zablokował ten skrypt -> `/stg-privacy-bar.js$script`.
