### ISSUE TITLE
eneva.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3838]
cookies

**Comment by gzenio22** [comment]
@hawkeye116477 mielismy na to juz jakas ogolna regule chyba nie?

**Comment by hawkeye116477** [comment]
@gzenio22 Nie. Zamierzałem dać coś w tym stylu -> `eneva.pl##body > div:not([id]):not([class])`, ale to zablokuje logo strony, więc trzeba chyba będzie dać coś ze style, może tak -> `eneva.pl##body > div:not([id]):not([class])[style*="position"][style*="fixed"]`, jeszcze potestuję to tak czy siak.
