### ISSUE TITLE
bialagwiazda.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3841]
cookies fix strona cala biala 

http://www.bialagwiazda.com.pl/cookies

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale główna jest w porządku, tylko problem jest z tą stroną od ich polityki. No i gdzie ty tą podstronę znalazłeś? Bo mi się wydaje, że jak komunikat jest blokowany to i link do polityki jest niewidoczny. A skoro nie ma linku, to fix zbędny.
