### ISSUE TITLE
bimsplus.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3843]
cookies

**Comment by hawkeye116477** [comment]
`bimsplus.pl##DIV[style*="url(images/cookies_tlo.png)"]`

**Comment by gzenio22** [comment]
@hawkeye116477 jak wy sie uczyliscie tego wszystkiego? ja do dzis wiekszosci slow w tych kodach nie ogarniam nie wiem co do czego sluzy Xd
