### ISSUE TITLE
brogshop.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3845]
cookies fix strona biala

**Comment by hawkeye116477** [comment]
@xxcriticxx U mnie jest ok, może za dużo kopcisz, że aż biało się zrobiło 😃.

**Comment by xxcriticxx** [comment]
@hawkeye116477 trawy z 10 lat nie palilem ale jak rekomeduejsz

**Comment by gzenio22** [comment]
u mnie tez jest ok

**Comment by xxcriticxx** [comment]
@gzenio22 tylko z polska lista?

**Comment by gzenio22** [comment]
juz kookam

**Comment by xxcriticxx** [comment]
@gzenio22 flush historia/cache i kuka?

**Comment by gzenio22** [comment]
jak naj bardziej

**Comment by gomoku** [comment]
U mnie też jest ok na FF/Operze + uBO na polskiej liście + polskiej kuki liście.
