### ISSUE TITLE
pyszne.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3846]
cookies 

https://www.pyszne.pl/jedzenie-na-telefon-warszawa

![capture](https://user-images.githubusercontent.com/15007183/30988387-49e03668-a468-11e7-80fd-22ace45516cf.PNG)

**Comment by gzenio22** [comment]
jedzenie smaczne ale ciastek nie dowiezli :D

**Comment by hawkeye116477** [comment]
@gzenio22 No to chyba miałeś pecha, bo mi dowieźli.
`##.privacybanner_notice:not(body):not(html)`

**Comment by xxcriticxx** [comment]
👍

**Comment by kasper93** [comment]
Włączcie sobie Adguard’s Annoyance List tam są takie rzeczy poukrywane.

**Comment by hawkeye116477** [comment]
@kasper93 Ale Adguard Annoyance nie uznajemy za uzupełnienie naszego filtra, Adguard Annoyance blokuje nie tylko cookies, a nie wszyscy tego chcą. I don't care to niby blokuje, ale my polski filtr ciasteczkowy traktujemy jako samodzielny.
