### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by kasper93** [MajkiIT/polish-ads-filter#3848]
Naprawienie filmików embedowanych na stronie. Na przykład tutaj `http://www.filmweb.pl/person/David.Fincher`

```
@@||gfx.filmweb.pl/adbetween/adx.js
filmweb.pl##script:inject(abort-on-property-write.js, sas)
```

**Comment by MajkiIT** [comment]
Dzięki

**Comment by gomoku** [comment]
Czy 2 tygodnie to za mało, żeby to ogarnąć, z tego co testowałem to filtr działa.

**Comment by MajkiIT** [comment]
@gomoku nie wiedziałem, że mam SLA na dodawanie reguł.... Jak tak Cię to boli?
