### ISSUE TITLE
Sport.pl

### ISSUE THREAD

**Issue by got3n** [MajkiIT/polish-ads-filter#3849]
banner na górze
![1](https://user-images.githubusercontent.com/26026382/31007907-6ff11972-a502-11e7-8676-0a68228c23ee.png)

**Comment by MajkiIT** [comment]
@got3n  u mnie jest ok. 
@xxcriticxx @hawkeye116477 sprawdzicie?

**Comment by xxcriticxx** [comment]
@MajkiIT czysto na foxie i chromie

@got3n stare filtry maybe?

**Comment by got3n** [comment]
Być może dlatego, że nie używam żadnych skryptów.. filtry wszystkie mam aktualne.

**Comment by gomoku** [comment]
U mnie na FF i Operze czysto na samej liście `POL: polskie filtry do Adblocka i uBlocka`.

**Comment by hawkeye116477** [comment]
Natywny Adblock Opery wygląda chyba nieco inaczej, ten to jest raczej zwykły Adblock -> https://addons.opera.com/pl/extensions/details/adblockforopera/?display=pl .

**Comment by got3n** [comment]
Nie używam Opery..... tylko Chrome'a + AdBlock. 

Ato mój config:
![1](https://user-images.githubusercontent.com/26026382/31297611-0542b1f4-aae7-11e7-8567-1f707bd8a858.png)

**Comment by got3n** [comment]
No działa :) jakoś nie pomyślałem o tym szczególnie, że od lat mam włączone Acceptable And i na innych stronach niczego nie zauważyłem... tylko na tej ten banner był. 

No i jeszcze mam problem na  Onecie ze słynnym już potworkiem... ale to już wiem żeby się go pozbyć to trzeba skrypty wgrać.

**Comment by gomoku** [comment]
@got3n OK, to możesz już ten wątek zamknąć.
