### ISSUE TITLE
prntscr.com

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#3852]
cos chyba spsulismy filtrami spolecznosciowymi

http://prntscr.com/gr40r3

**Comment by blocker999** [comment]
@gzenio22 W którym momencie to masz?

**Comment by gzenio22** [comment]
ladowanie galerii screenow

zalusz konto pobierz aplikacje zaloguj sie i wbij w galerie

**Comment by blocker999** [comment]
@gzenio22 OK, zajmne się tym ale póżniej

**Comment by blocker999** [comment]
@gzenio22 umnie " Moja galeria " ładuje się, wiec niewiem, może niech ktoś inny spojrzy, albo sprawdż to jeszcze raz być może jakieś inne rozszerzenie blokuje tą galerie

**Comment by gzenio22** [comment]
@blocker999 dziwne bo ja kurde zadnych innych rozszerzen nie urzywam no poza lastpassem ale to do haseł

**Comment by blocker999** [comment]
@gzenio22 Niewiem umnie jest ok na slimjet z rozszerzeniem do chrome po zalogowaniu do gmaila no i oczywiście mam ublocka z socialami, może sprawdź na innej aplikacji.

**Comment by gzenio22** [comment]
ej dobra wiem co nie gralo wylogowalo mnie a ze tu trzeba sie logowac socjalem to nie moglo mi wyswietlic przyciskow logowania ciekaawe

**Comment by hawkeye116477** [comment]
@gzenio22 U mnie normalnie przyciski logowania się wyświetlają tutaj -> https://prntscr.com/gallery.html. Po wylogowaniu znikają?

**Comment by gzenio22** [comment]
@hawkeye116477 wlasnie nie wiem jak to wyjasnic... 

sprobuj wejsc w galerie zalogowany a potem sie wyloguj powinno zadzialac wywoujac moj efekt na (Chr) Operze

**Comment by hawkeye116477** [comment]
Na Vivaldim jest ok.

**Comment by gomoku** [comment]
@gzenio22 zdecyduj się: podaj jakieś szczegóły:  jaka przeglądarka / adbocker / listy filtrów / system / zrzut ekranu żebyśmy mogli ci pomóc albo zamknij wątek...

**Comment by hawkeye116477** [comment]
Ja to podejrzewam, że pewnie znowu Fanboy's Antythirdparty Social sprawia problemy. A @gzenio22 to zapewne czeka na Godota 😃  .

**Comment by gomoku** [comment]
Do cholery niech ktoś zamknie ten wątek, a ty @gzenio22 znowu w kulki lecisz, tego nie wątku nie  zamknąłeś, pomimo upomnień, ale kolejne zakładasz jeden po drugim, i co zaraz będziesz znowu zasłaniał się pomyłką.

**Comment by gzenio22** [comment]
o nie nie nie niczym sie nie zaslonie przepraszam nie zauwazylem po prostu juz zamykam
