### ISSUE TITLE
bsmalawies.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3860]
maybe?
+ 
cookies na dole ale to staic

http://bsmalawies.pl/nowa/

![capture](https://user-images.githubusercontent.com/15007183/31028065-9641875c-a51a-11e7-912d-7541916feef5.PNG)

**Comment by gzenio22** [comment]
bsmalawies.pl##.module:nth-of-type(3) > .clearfix

**Comment by gomoku** [comment]
Nie rozumiem czy 2 tygodnie to za mało, żeby to ogarnąć.
