### ISSUE TITLE
polskihurtworld.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3862]
adblock 

![capture](https://user-images.githubusercontent.com/15007183/31028369-9c655b58-a51b-11e7-88fc-c6c4ae530954.PNG)

**Comment by gzenio22** [comment]
polskihurtworld.eu###myModal

@xxcriticxx zerknij czy styka :)

**Comment by hawkeye116477** [comment]
Jakiś marny ten królik, kiciuś na xperiasite lepszy 😄 .

**Comment by xxcriticxx** [comment]
@hawkeye116477 przekaze

**Comment by hawkeye116477** [comment]
@gzenio22 Potwierdzam, działa. @MajkiIT może dodać.
