### ISSUE TITLE
angielski.slowka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3863]
![capture](https://user-images.githubusercontent.com/15007183/31028447-0280c7b0-a51c-11e7-8bc0-1b4777266dff.PNG)

**Comment by gzenio22** [comment]
angielski.slowka.pl##.box_green_reklamy
a na puste boxy ja jakos nie umiem znalesc takiej reguly ktora ukrywala by oba

**Comment by hawkeye116477** [comment]
@gzenio22 Można tak zrobić -> `angielski.slowka.pl##.box_green:has-text(REKLAMA)`, tylko tyle, że to zadziała, tylko dla uBlocka o ile się nie mylę 😄 .

**Comment by gzenio22** [comment]
szczerze? nie widzi mi sie tworzenie 2 osobnych list dla 2 dodatkow nie sadzicie ze to by byla kupa roboty? z 2 strony gdybym sie znal wiedzial bym dokladnie co robie sprobowal bym przyjemnie jest widziec ze cos twoiego nawet w niewielkim stopniu dziala i w jakis sposob pomaga ludziom :)

**Comment by MajkiIT** [comment]
To może tak?
```
angielski.slowka.pl##.rc-box-white + .box_green
angielski.slowka.pl##.srodek_strefa > .box_green
angielski.slowka.pl##.box_green_reklamy
```

**Comment by hawkeye116477** [comment]
@MajkiIT Drugi filtr za dużo za blokuje.

**Comment by gzenio22** [comment]
@MajkiIT potwierdzam slowa @hawkeye116477

**Comment by hawkeye116477** [comment]
@MajkiIT Tu nadal są resztki po reklamach.
