### ISSUE TITLE
puma.com & mkidn.gov.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3867]
@MajkiIT Mamy problem, bo na tej stronie wyskakuje popup ciasteczkowy, który jest blokowany, ale problem jest w tym, że on blokuje scrolla. Na uBlocka mogę dać regułę na odblokowanie scrolla, tylko co z Adblockiem, tam przecież będzie scroll się blokował, to co mam dać wyjątek, by nie blokowało ciasteczkowego popupu?

`puma.com##.modal-backdrop` - fix na przyciemnienie
`puma.com##.modal-open:style(overflow: visible!important;)` - odblokowanie scrolla

**Comment by MajkiIT** [comment]
@hawkeye116477 dzięki za diagnozę.

**Comment by hawkeye116477** [comment]
@MajkiIT Ale to co w takim razie proponujesz? Bo mi to się wydaje, że najlepiej będzie dać tak:
Do filtrów ciasteczkowych -> `puma.com#@#:not(input)[id*="cookie"]`
A to może do filtrów dla uzupełniających dla uBlocka albo do ciastek zrobić nowy filtr „polski filtr ciasteczkowy do uBlocka - uzupełnienie" i do niego dodać te reguły?
```
puma.com###modal-geoip-cookies,important
puma.com##.modal-backdrop
```
Oprócz tego to również byłoby do przeniesienia:
```
mkidn.gov.pl###myModal
mkidn.gov.pl##body.modal-open:style(padding-right: 0px!important; overflow: visible!important;)
```
