### ISSUE TITLE
tv.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3870]
![capture](https://user-images.githubusercontent.com/15007183/31045641-48beb616-a5b6-11e7-9227-51ed3acfb24e.PNG)

**Comment by hawkeye116477** [comment]
Na górze -> `tv.wp.pl##DIV[style="text-align:center; padding:10px;"]`
Jeszcze jest na dole, ale na razie nie mam pomysłu na regułę.

**Comment by MajkiIT** [comment]
`tv.wp.pl##SECTION > DIV.wide > DIV + DIV[class]`
`tv.wp.pl##DIV[style="text-align:center; padding:10px;"]`
