### ISSUE TITLE
cyberkino.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3874]
fake player 

http://cyberkino.pl/film/barry+seal+krol+przemytu+american+made+online+zalukaj/21647

![capture](https://user-images.githubusercontent.com/15007183/31050624-eedaf336-a61d-11e7-916d-282feed78d82.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx nie uważasz, że ta cała strona to fake?

**Comment by xxcriticxx** [comment]
@MajkiIT nie wiem filmy sie odpalaja ale strasznie chopie
