### ISSUE TITLE
gazetatrybunalska.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3875]
**Site Sample** | 
----|
http://gazetatrybunalska.pl

### Issue

Boxy z reklamami po prawej stronie i na górze obok logo strony.

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Opera Stable x64
AdGuard version:                    | **6.2.419.2110**
Stealth mode: | **enabled**

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

Stealth mode options enabled |
---------------------|
`hide search passwords ** send Do-Not-Track header ** remove X-Client-Data header ** remove tracking data from urls ** self-destroying third-party cookies  ** disable third-party request cache  ** block API browser (except flash) ** hide refferer against third-party ** hide user-agent header ** hide IP address`

**Comment by hawkeye116477** [comment]
@xxcriticxx @FadeMind @MajkiIT To nie dotyczy tylko Adguarda, ja też to mam.
```
gazetatrybunalska.pl##img[src*="reklama"]
gazetatrybunalska.pl##.widget-title:has-text(Reklama)
```

**Comment by gomoku** [comment]
Jeśli już iść w filtr uBO to prostszy i skuteczniejszy będzie taki:
`gazetatrybunalska.pl##aside[class="widget bns-corner-logo clearfix"]:has-text(Reklama)`

Prostszy bo 1 filtr zamiast 2, a skuteczniejszy bo z tego co patrzyłem to te kombo wyżej czasem nie blokuje jakiejś reklamy np. tej pomarańczowej reklamy po prawej na dole, dlatego, że obrazek tej reklamy nie zawiera słowa "reklama", i  z tego co testowałem mój filtr nie ma takich problemów:

![](https://s3.dodajfote.pl/2017/10/07/reklab57c89c3fd50092e.png)

**Comment by gomoku** [comment]
Ludzie zamknijcie w końcu ten wątek, przecież te reklamy już dawno usunięte.
