### ISSUE TITLE
promocyjni.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#3876]
Zrzut ekranu 1 - przy włączonej liście Fanboy’s Social Blocking List filtr `##.social-box` zostawia resztki panelu social po lewej:
![](https://s3.dodajfote.pl/2017/09/30/interia_promocyjni_socialbar_left_minif8041.png)

Zrzut ekranu 2 - przy wyłączonej liście Fanboy’s Social Blocking List - cały panel social po lewej: 
![](https://s3.dodajfote.pl/2017/09/30/interia_promocyjni_socialbar_left_full94418.png)

Zrzut ekranu 3 - zdublowany panel social na dole po środku
![](https://s3.dodajfote.pl/2017/10/02/bauer_promocyjniebb6855fa995bded.png)

Filtr który usunie obydwa panele to 
`www.promocyjni.pl##.socials-float, .footer-socials` lub prościej 
`www.promocyjni.pl##div[class*="socials"]` lub jeszcze prościej
`www.promocyjni.pl##[class*="socials"]`

**Comment by hawkeye116477** [comment]
Wystarczy tylko -> `www.promocyjni.pl##.socials-float`, reszta jest u Fanboya.
