### ISSUE TITLE
kdowqlpt.info / cda-hd.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3877]
Hej mam do Was prośbę. Czy po wejściu na stronę http://cda-hd.pl/20702/malzenskie-porachunki-draeberne-fra-nibe-2017-online/ pojawiają Wam się requesty do kdowqlpt.info a jak tak to czy nagle wam CPU nie skacze? 

Pytam, bo u mnie nagle zamulił komp i znalazłem skrypt kopiący bitcoin...

**Comment by xxcriticxx** [comment]
@MajkiIT nie mam takiego polonczenia u mnie cpu okolo 17% smiga na tej stronie

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/31054237-6d89b024-a67c-11e7-97ae-cbc46fcd134b.PNG)

**Comment by hawkeye116477** [comment]
To chyba do KAD powinno trafić, Kaspersky wykrywa tam jakieś dziadostwo 😃 
https://www.virustotal.com/#/url/be63fa283e568578d0d524a20748386f437616b3b20d5454146588df3e9feb0c/detection
https://www.virustotal.com/#/domain/kdowqlpt.info

**Comment by xxcriticxx** [comment]
@hawkeye116477 na cda-hd.pl?

**Comment by hawkeye116477** [comment]
@xxcriticxx Na tej stronie kdowqlpt.info, do której macie połączenia na cda-hd.pl. Także ta strona cała jest do zablokowania -> `||kdowqlpt.info^`.

**Comment by xxcriticxx** [comment]
@hawkeye116477 zamulilo tobie cpu?

**Comment by HateAds** [comment]
@xxcriticxx U mnie nie zamuliło.

**Comment by MajkiIT** [comment]
@xxcriticxx @hawkeye116477 @HateAds Dzięki ... sprawdzę czy ten url się nie będzie zmieniał.

**Comment by xxcriticxx** [comment]
@MajkiIT dobra robota!

**Comment by MajkiIT** [comment]
@xxcriticxx czemu? :)

**Comment by xxcriticxx** [comment]
@MajkiIT teraz mozna bezpiecznie filmy oglondac :)

**Comment by MajkiIT** [comment]
https://kryptopomocnik.pl/opis-monero-xmr/

**Comment by xxcriticxx** [comment]
@MajkiIT check out https://github.com/hoshsadiq/adblock-nocoin-list

**Comment by MajkiIT** [comment]
Pandemiana stronie ==> http://cda-hd.pl/20726/sinobrody-bluebeard-2017/ `||azvjudwr.info^$websocket,domain=openload.co`

**Comment by xxcriticxx** [comment]
@MajkiIT jak to dziala openload kase sobie kopie?

**Comment by MajkiIT** [comment]
@xxcriticxx yes :(

**Comment by MajkiIT** [comment]
@xxcriticxx skąd wyłapałeś tą listę?

**Comment by xxcriticxx** [comment]
github/google

**Comment by xxcriticxx** [comment]
Sie przyda na strony filmowe :)

**Comment by HateAds** [comment]
@MajkiIT Sorki za offtop (usunę wpis później), jestem na githubie od niedawna i nie wiem jak to działa w 100%. Czy jak zamykasz issues to widzisz późniejsze wpisy czy trzeba zakładać od nowa kolejne issue ?

**Comment by xxcriticxx** [comment]
@HateAds tak zamknienta sa po zamknietymi I tak widac nowe wpisy na zamkniętych

**Comment by HateAds** [comment]
@xxcriticxx Ok dzięki za info.

**Comment by xxcriticxx** [comment]
@HateAds już otworzyłem spowrotem

👍👎😊👊🍴💀💩😂🗣👹👆🏾👿👌💍🙂👺☹️😘🙀💋👊🏿😤🤧😷😼🤡😽😆☠️

**Comment by MajkiIT** [comment]
@xxcriticxx ktoś szybko blokuje te domeny .... już te co podałem są dead.

**Comment by xxcriticxx** [comment]
@MajkiIT jakto dead? dns wylonczony?

**Comment by MajkiIT** [comment]
Domeny kierowały na Cloudflare i oni wycieli.

**Comment by xxcriticxx** [comment]
@MajkiIT widze ze polowanie na ostro
