### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#388]
Od wczoraj mam problem ze stroną sportowefakty.wp.pl a mianowicie z samoczynnie odtwarzającymi się filmikami. Przestało blokować mi reklamy i teraz, każdy filmik automatycznie się odtwarza razem z reklamą. Wcześniej było ok, uBlock blokował reklamę i uniemożliwiał autoodtwarzanie.

**Comment by xxcriticxx** [comment]
podaj jakis link prze testuje

**Comment by MajkiIT** [comment]
Damian dodał jeszcze coś takiego:
Nie używam AAK,
Jeśli wyłączę w ustawieniach uBlocka Polskie filtry do Adblocka i uBlocka i jadąc na domyślnych filtrach easylist itp. to normalnie blokuje autoodtwarzanie i reklamy, no tyle że wtedy na wp.pl bez waszych filtrów mam masę reklam :-(

**Comment by xxcriticxx** [comment]
to polskie filtry problem?
