### ISSUE TITLE
przepisyjoli.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3882]
reklama na dole 

![capture](https://user-images.githubusercontent.com/15007183/31055226-08a0c33e-a68e-11e7-973e-8c2367f8fd2e.PNG)

**Comment by hawkeye116477** [comment]
Social -> `przepisyjoli.com##.header-social`
Reklama -> `przepisyjoli.com###text-25`

**Comment by HateAds** [comment]
@hawkeye116477 Mam to samo, połowa komentarzy niewidoczna.

**Comment by gomoku** [comment]
U mnie na takich ustawieniach: https://github.com/MajkiIT/polish-ads-filter/issues/3901#issuecomment-334236072 na podanej stronie są wszystkie komentarze, czyli 7, bo tyle samo jest przy wyłączonym uBO, więc nie mam pojęcia co wam chowa komentarze, czy macie jakąś listę filtrów inną niż ja, a jakie przeglądarki?

**Comment by hawkeye116477** [comment]
Dziwne, u mnie na Waterfoksie jest ok, a na Vivaldim komentarze się chowają. Zapewne problem jedynie dotyczy przeglądarek opartych o Chromium,

**Comment by HateAds** [comment]
@gomoku @hawkeye116477 U mnie na Chromie z włączonym uBO komentarze są schowane ( widać tylko 2 pierwsze ) dopiero po wyłączeniu uBO wyświetlają się wszystkie.

**Comment by gomoku** [comment]
Sprawdziłem na Vivaldi + uBO / ADP + sama Polska Lista i faktycznie wcina komentarze, po dodaniu tego filtru: `#@#[id^="nokaut_ads_category_"]`, komentarze się pojawiają. 

O dziwo to samo dzieje się gdy się włączy samą EasyList,  tym, że tutaj żeby odblokować komentarze, trzeba dodać: `@@||widget.nokaut.pl/pp/nokaut.php$script,domain=przepisyjoli.com`

**Comment by hawkeye116477** [comment]
U mnie muszą być 2 reguły, by komentarze się pojawiły:
```
@@||widget.nokaut.pl/pp/nokaut.php$script,domain=przepisyjoli.com
przepisyjoli.com#@#[id^="nokaut_ads_category_"]
```

Ale wtedy lipa, bo oczywiście reklamy Nokauta się pojawiają, więc chyba trzeba będzie coś innego na nie wykombinować.
