### ISSUE TITLE
megawrzuta.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3886]
adblock?

https://megawrzuta.pl/download/5d40e6af888e34ff21c8e8121c060dea.html

![capture](https://user-images.githubusercontent.com/15007183/31057304-87920ef8-a6ae-11e7-91df-d89ea97acbc7.PNG)

**Comment by MajkiIT** [comment]
`megawrzuta.pl###popup-1`

Dalej wrzucamy adblocka do PL czy pchamy to w AAK?

**Comment by xxcriticxx** [comment]
i tu i tu jak da rade

**Comment by xxcriticxx** [comment]
podane do pigwina
