### ISSUE TITLE
ulubiona 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3888]
@MajkiIT EMERGENCY! na main i all sub domains. 

@HateAds  potwierdzisz?

![capture](https://user-images.githubusercontent.com/15007183/31087033-8c78e732-a769-11e7-96a5-8ac42be257ca.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx już patrzę.

**Comment by MajkiIT** [comment]
@xxcriticxx gotowe

**Comment by xxcriticxx** [comment]
mala reklama stihl pod pogada i migajaca reklama w sekcje `GWIAZDY`

**Comment by xxcriticxx** [comment]
`sportowefakty.wp.pl` crazy rekamy na main

**Comment by MajkiIT** [comment]
Nie mam nic na sportowefakty.

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/31089316-8ed2d6f2-a771-11e7-902d-1357c196570e.PNG)

**Comment by MajkiIT** [comment]
Ok, będę odświeżał.

**Comment by MajkiIT** [comment]
@xxcriticxx, sprawdzisz?
`sportowefakty.wp.pl##HEADER + DIV#matchtable + DIV[class]`

**Comment by xxcriticxx** [comment]
zostalo jeszcze po bokach i na dole 

![fireshot screen capture 009 - pilkarze legii warszawa rozwiaza kontrakty z winy klubu_ _nie ma na to szans_ - sportowefakty_wp_pl_pilka-nozna_71405](https://user-images.githubusercontent.com/15007183/31092277-dbb092ca-a77b-11e7-85ba-52186c95d9a2.png)

**Comment by HateAds** [comment]
@xxcriticxx Mnie ta strona już dołuje. Wiecznie coś zmieniają i też miałem rano reklamy, ale nie miałem czasu zgłosić. Pewnie za parę dni znowu coś pozmieniają i znowu będą wpReklamy wszędzie.

**Comment by xxcriticxx** [comment]
dluzszego czasu juz tak mowie`||wp.pl`

**Comment by xxcriticxx** [comment]
@MajkiIT robimy dalej wp czy zamykamy?
