### ISSUE TITLE
vod.pl / player.pl - wykrywanie ublock origin i blokowanie wideo.

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#3889]
Tak jak w temacie. Firefox PC / Android + ublock origin (wszystkie filtry bez ignorowania kosmetycznych) + violentmonkey + aak cont

I mam coś takiego : 
![vodpliplayerpl](https://user-images.githubusercontent.com/16944478/31130224-1d60d28a-a857-11e7-859c-013aef69291b.PNG)

**Comment by xxcriticxx** [comment]
geo locked

![capture](https://user-images.githubusercontent.com/15007183/31132612-3de33ff6-a82b-11e7-8b6c-06a4f85aa59e.PNG)

**Comment by xxcriticxx** [comment]
odcinek moge scriptem wyciagnac

**Comment by seba2282** [comment]
Żadnych sugestii ?

**Comment by xxcriticxx** [comment]
@seba2282 testowales w chrome i protectorem?

**Comment by xxcriticxx** [comment]
druga sugestia script 


Skrypt umożliwiający pobieranie materiałów ze znanych serwisów VOD. Autor: Przemek

SKrypt umożliwiający pobieranie materiałów z serwisów Ipla.tv, Player.pl, Vod.pl

https://greasyfork.org/pl/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod-autor-przemek/code

**Comment by seba2282** [comment]
Nie testowałem chrome z protectorem. Na Android uciekłem z chrome na firefox. Nie wiem dlaczego, ale nie przemawia do mnie chrome. :) Co do sugestii nr dwa, to bardziej zależy mi trochę pooglądać online niż wszystko ściągać.

**Comment by hawkeye116477** [comment]
@seba2282 Na Androida polecam Yandex Browser, w trybie dewelopera można doinstalować uBlock Origin i różne inne rozszerzenia z Chrome, ale uBlock Protector to chyba niestety tam nie działa, pewnie też dlatego, że Yandex jest parę numerków do tyłu z Chromium. Jakby co, to na wiki masz opisane jak zainstalować uBlock Origin w Yandex Browser na Androidzie 😄 .

Co do tego wykrywania Adblocka, to niestety, ale u nas raczej nie ma takich speców. Pisz tu -> https://gitlab.com/xuhaiyang1234/AAK-Cont, a może ktoś coś tam wykombinuje. Ewentualnie możesz zainstalować coś z Chromium, np. Vivaldi i do tego uBlock Protector, tam na 100% jest wszystko ok.

No chyba, że @F4z coś wykombinuje, ale na niego to będziesz musiał trochę poczekać.

**Comment by xxcriticxx** [comment]
@seba2282 script podaje linky i oglondasz w przeglondarce

**Comment by gomoku** [comment]
Ja na player.pl od dawien dawna oglądam tymi skryptami:  https://github.com/MajkiIT/polish-ads-filter/issues/1216#issuecomment-269330124 a dokładniej pobieraczek HD, zawsze działało i działa nadal na PC & Firefox.
