### ISSUE TITLE
money.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#3890]
3 jebutne reklamy:

U góry:
![](https://s3.dodajfote.pl/2017/10/03/reklama_wp_money_12233298c668828cb.png)

Po prawej 1:
![](https://s3.dodajfote.pl/2017/10/03/reklama_wp_money_2f41883a81806aac5.png)

Po prawej 2:
![](https://s3.dodajfote.pl/2017/10/03/reklama_wp_money_34355282e180e7ad9.png)

**Comment by xxcriticxx** [comment]
see https://github.com/MajkiIT/polish-ads-filter/issues/3888
