### ISSUE TITLE
pogoda.wp.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#3891]
3 jebutne reklamy:

U góry:
![](https://s3.dodajfote.pl/2017/10/03/reklama_wp_pogoda_1941bf2cedcf015d9.png)

Dwie po prawej jedna pod drugą
![](https://s3.dodajfote.pl/2017/10/03/reklama_wp_pogoda_2091b706c0fd0e0b3.png)

**Comment by xxcriticxx** [comment]
see https://github.com/MajkiIT/polish-ads-filter/issues/3888

**Comment by gomoku** [comment]
Wycięło część dolnej połowy strony przedstawioną na zrzucie ekranu (+ jeszcze trochę w dół):

![](https://s3.dodajfote.pl/2017/10/04/reklama_wp_pogoda_wyciete7b48a7c00c571769.png)
![](https://s3.dodajfote.pl/2017/10/04/reklama_wp_pogoda_wyciete224a84b7656fed451.png)

**Comment by gomoku** [comment]
@MajkiIT a teraz wyskoczyła dodatkowo u góry reklama:

![](https://s3.dodajfote.pl/2017/10/04/pogoda_gora57782d9adc1a33cd.png)
