### ISSUE TITLE
m.sportowefakty.wp.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#3893]
Jebutna reklama na samym dole:
![](https://s3.dodajfote.pl/2017/10/03/wp_reklama_m_sportowefakty8ad3dff595152577.png)

**Comment by xxcriticxx** [comment]
see https://github.com/MajkiIT/polish-ads-filter/issues/3888

**Comment by gomoku** [comment]
Resztka:

![](https://s3.dodajfote.pl/2017/10/04/wp_m_sportowefakty_resztka7d785642dafcd76e.png)

**Comment by gomoku** [comment]
@MajkiIT DODANE 20:33 na FF już tej resztki nie ma, ale z kolei jest na Operze...
