### ISSUE TITLE
sportowybar.wp.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#3895]
http://sportowybar.wp.pl/gid,17041713,kat,1726,page,8,title,Pilkarski-wtorek-tak-graly-europejskie-reprezentacje,galeria.html

5 jebutnych reklam:

U góry:
![](https://s3.dodajfote.pl/2017/10/03/reklama_wp_sportowybar_1a81abf055550cc94.png)

3 po prawej jedna po środku:
![](https://s3.dodajfote.pl/2017/10/03/reklama_wp_sportowybar_255135b3117d0ed98.png)
![](https://s3.dodajfote.pl/2017/10/03/reklama_wp_sportowybar_34e6b347723cbaaa2.png)

**Comment by xxcriticxx** [comment]
see https://github.com/MajkiIT/polish-ads-filter/issues/3888
