### ISSUE TITLE
domodi.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#3896]
! social panel z przyciskami na dole po prawej:
`domodi.pl##.dm-1of5.dm-gcf__item.dm-footer-section:nth-of-type(3) > nav`

![](https://s3.dodajfote.pl/2017/10/03/wp_domodi_social_panel2119b7562c663b68.png)

**Comment by hawkeye116477** [comment]
`domodi.pl##.dm-1of5:has-text(Social media)`
