### ISSUE TITLE
kuchnia.wp.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#3898]
! social stopka na https://kuchnia.wp.pl/katalog-przypraw-6054905381082241a

![](https://s3.dodajfote.pl/2017/10/03/wp_kuchnia_social_stopkad36d4f2dd1cb0d34.png)

**Comment by hawkeye116477** [comment]
`kuchnia.wp.pl##div[class^="_"]:matches-css(position: fixed):matches-css(backface-visibility: hidden):matches-css(bottom: 0)`
