### ISSUE TITLE
bigfarm.wp.pl / empire.wp.pl / naryby.wp.pl - uwalone

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#3899]
`POL: polskie filtry do Adblocka i uBlocka` 
blokuje całkowicie wejście na te strony:
http://lowcyzombi.wp.pl
http://railnation.wp.pl
http://techsterowniki.wp.pl 
https://forgeofempires.wp.pl

A tych nie blokuje:
http://bigfarm.wp.pl
http://empire.wp.pl
http://naryby.wp.pl

Czy to błąd i te strony są przypadkowo blokowane czy to efekt zamierzony?

**Comment by xxcriticxx** [comment]
@gomoku regex to wylapuje ta sa jakies pierdoly nic powaznego
