### ISSUE TITLE
money.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#3901]
Resztki/dziury po reklamach na serwisach `*.money.pl` i przy okazji jeszcze 2 reklamy:

**_1__** Najpierw reklama nr 1, wyskoczyła mi 1 raz losowo, teraz już nie chce, więc być może jakiś przypadek i fałszywy alarm, https://m.money.pl/:
![](https://s3.dodajfote.pl/2017/10/04/REKreklama_wp_m_moneye0bef29a267dbfd9.png)

version 2017100501:
![](https://s3.dodajfote.pl/2017/10/05/wp_m_money_dziura_1i2a22134504c56e201.png)

A teraz resztki/dziury:
**_2__** https://manager.money.pl/ po prawej i po środku:
![](https://s3.dodajfote.pl/2017/10/04/reklama_wp_manager_money_2dziury7e4650c38e46c63a.png)

**_3__** https://tech.money.pl/ po prawej:
![](https://s3.dodajfote.pl/2017/10/04/reklama_wp_tech_money_dziura0f3bfe9cb4271d53.png)

**_4__** https://pogoda.money.pl/ po prawej:
![](https://s3.dodajfote.pl/2017/10/04/reklama_wp_pogoda_money_dziurabe71516e148a46b6.png)

**_5__** https://www.money.pl/pieniadze/
![](https://s3.dodajfote.pl/2017/10/04/reklama_wp_money_pieniodze188b5657f715e56a5.png)

![](https://s3.dodajfote.pl/2017/10/04/mon_pieniadzedb0a14247916872a.png)

**_6__** https://moto.money.pl/ po prawej:
![](https://s3.dodajfote.pl/2017/10/04/reklama_wp_moto_money_dziura08517bf94eba7ba6.png)

**_7__** http://biztok.money.pl/gospodarka/artykul/polski-rynek-pracy-eksperci-prognozuja-udana,236,0,1898476.html po prawej:
![](https://s3.dodajfote.pl/2017/10/04/wp_biztok_resztka795044ef0de6cb0d.png)

**_8__** https://prawo.money.pl/ po prawej:
![](https://s3.dodajfote.pl/2017/10/04/reklama_wp_prawo_money_dziura886b339b0883baf1.png)

**_9__** https://msp.money.pl/ po środku:
![](https://s3.dodajfote.pl/2017/10/04/reklama_wp_mspmoney_dziurad848d079de02e941.png)

A teraz reklama nr 2 + 6 dziur po reklamach....
**_10__** https://www.money.pl/gospodarka/wiadomosci/artykul/vistal-gdynia-sprawozdanie-finansowe-straty,18,0,2372370.html 
![](https://s3.dodajfote.pl/2017/10/04/screenshot-www.money.pl-2017-10-04-13-10-581d6e0cbbfabf36bd.png)

**Comment by gomoku** [comment]
Nie wiem czy już skończyłeś wszystkie, no ale zakładając, że tak, to na 5 stronach resztek i dziur już nie ma, ale na 3 jeszcze są:
- w pkt 2 jeszcze została ta na środku
- w pkt 5 dalej są obydwie - czasem zmieniają położenie więc dodałem drugi zrzut ekranu
- w pkt 7 dalej jest czyli po prawej

**Comment by MajkiIT** [comment]
@gomoku nie skończyłem w pełni. Tam jest skrypt i on generuje randomowe div-y .

**Comment by HateAds** [comment]
@MajkiIT Widzę że znowu masa roboty z tym syfem od wp... Tak przy okazji u mnie na chromie po updacie filtrów pojawił się problem na money.pl rozwaliło niemal całkowicie player https://www.money.pl/gospodarka/wiadomosci/artykul/vistal-gdynia-sprawozdanie-finansowe-straty,18,0,2372370.html
![image](https://user-images.githubusercontent.com/29756590/31168993-8f60c49e-a8f7-11e7-99ee-94afe5ed7eda.png)
Jeszcze coś irytującego się pojawiło co lata za mną jak dam w dół strony ( ten dzwoneczek po lewej na obrazku po wyżej )

**Comment by gomoku** [comment]
- no sporo syfu, a wszedłem pod link, który podałeś i wyskoczyła 1 reklama + 6 dziur po reklamach...(zrzut ekranu niżej)
- a to coś irytującego to widżet typu "następny artykuł" o to się nie martw to pójdzie jeszcze dziś tutaj https://github.com/azet12/PopupBlocker , jako element [Grupy Wirtualna Polska Holding], którą właśnie usadzam od wczoraj i zbliżam się ku końcowi, stąd przy okazji ten wysyp stron WP ode mnie tutaj bo ogarniając tę masywną grupę ponatrafiałem na sporo reklam i dziur po reklamach, jeśli chcesz tymczasowy filtr na ten widżet: `www.money.pl##.float.more-news`

![](https://s3.dodajfote.pl/2017/10/04/screenshot-www.money.pl-2017-10-04-13-10-581d6e0cbbfabf36bd.png)

**Comment by HateAds** [comment]
@gomoku Nie wiedziałem gdzie zgłosić ten "dzwoneczek" na przyszłość już będę wiedział żeby do popupa wysyłać takie sprawy. Inna sprawa, że dziś przykładowo zablokujemy wpReklamy, a oni za maks 7 dni znowu dadzą kolejne i od nowa trzeba blokować. Swoją drogą dziwne, że taki onet do dziś ma reklamy skasowane ( od czasu do czasu wyskoczy jakaś jedna reklama ) a na wp co chwila walą całą masę nowych reklam.

**Comment by MajkiIT** [comment]
@gomoku @HateAds zerknijcie już powinno być ok.

**Comment by xxcriticxx** [comment]
@MajkiIT znowu chyba pora na script 

na foxie mam puste boxy ze slowem REKLAMA 

na chrome mam mieszanke i puste i pelne z reklamami

jebac wp

**Comment by gomoku** [comment]
A więc u mnie wygląda to tak:

FF 56 64bit & Opera 48 64bit

- pkt 1 na Operze
- pkt 2 na Operze, na FF tylko ta po środku
- pkt 5 na FF, na Operze tylko ta po prawej
- pkt 7 na Operze i FF
- pkt 10 na Operze (z tym że ta jedna reklama zamieniła się na dziurę), na FF tylko 1 dziura po środku pod tekstem "Rok temu w analogicznym okresie był na plusie 12,5 mln zł netto."

**Comment by MajkiIT** [comment]
@gomoku która wersja PL filtrów?

**Comment by gomoku** [comment]
Najnowsze - wszystkie listy zaktualizowałem tuż przed sprawdzeniem.

**Comment by xxcriticxx** [comment]
v.2017100404 aktualizacja: sr, 4 pazdziernika 2017, 18:55:00

**Comment by HateAds** [comment]
@MajkiIT Player jak coś już działa. ( Chrome )

**Comment by gomoku** [comment]
> Update to version 2017100501

- pkt 1 już nie ma reklamy ani na FF ani na Operze, ale z kolei wyskoczyły dwie dziury na FF i Operze (dodałem drugi zrzut ekranu do pkt 1 w pierwszym poście)
- pkt 2 tylko ta po środku zarówno na FF jak i Operze
- pkt 5, 7, 8 na FF i Operze

**Comment by gomoku** [comment]
@MajkiIT zmiany 2017100501 vs 2017100502 - odświeżyłem post wyżej

**Comment by MajkiIT** [comment]
@gomoku update i weryfikacja

**Comment by HateAds** [comment]
@MajkiIT Możesz zobaczyć czy player u Ciebie się wyświetla ? ( u mnie nie ma playera pod "Paski pielęgniarek. Ile naprawdę zarabiają?" a powinien być ) https://www.money.pl/gospodarka/wiadomosci/artykul/wynagrodzenia-place-dane-gus-srednia-krajowa,128,0,2373248.html

**Comment by gomoku** [comment]
Weryfikacja przeprowadzona, w odświeżonym poście wyżej.

**Comment by gomoku** [comment]
Czy moglibyście przetestować ten filtr: `/wp\.pl\/.{457,}/$script,domain=money.pl` ?
Z tego co testowałem po krótce to na wszystkich serwisach *.money.pl wycina ładnie wszystkie reklamy nie pozostawiając żadnych pustych pól czy resztek.

**Comment by MajkiIT** [comment]
@gomoku ja bym poszedł w coś takiego 
`/^https:\/\/[a-z]{3,10}.wp.pl\/[a-zA-Z0-9_-]{450,}/$script,domain=money.pl`

**Comment by gomoku** [comment]
Może być, jak chcesz, tylko nie zapominaj https://github.com/MajkiIT/polish-ads-filter/issues/3914#issuecomment-335255894
