### ISSUE TITLE
wp poczta - LINK

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3909]
Po wylogowaniu pojawia się okienko z reklamą ale są różne, wystarczy F5 by się przekonać.

![poczta wp](https://user-images.githubusercontent.com/23176832/31237419-33c19536-a9f7-11e7-8d46-f01dab1aa6e0.png)

http://www.wp.pl/wylogowano_z_poczty.html?pfba=1507320538.305&advdyn=1

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/31299056-bb185696-aaba-11e7-96f0-18143890166c.PNG)
