### ISSUE TITLE
dodac do listy ciastkowej

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3913]
@hawkeye116477 

`###cooinfo`

jest na okolo 50 stron

exp: tysol.pl

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale na tysol.pl nie widzę żadnego komunikatu dot. ciasteczek. Podaj jakiś inny przykład może.

**Comment by xxcriticxx** [comment]
@hawkeye116477 wyloncz twoje ciastkowe listy i wyczysc browswer

**Comment by xxcriticxx** [comment]
@hawkeye116477 nauczyli cie czegos w tej szkole dzisiaj?

**Comment by hawkeye116477** [comment]
@xxcriticxx Wyłączyłem, nawet uBlocka wyłączyłem i nie widzę tam żadnego komunikatu dot. ciastek. Może jakiś screen?
Akurat piątek mam wolny, ale czwartek to od 8-20.

**Comment by xxcriticxx** [comment]
@hawkeye116477 open new private window 

![capture](https://user-images.githubusercontent.com/15007183/31293885-d35d482e-aaa6-11e7-9be5-748f54b2f06f.PNG)

**Comment by xxcriticxx** [comment]
exp:

systim.pl
astcon.pl
greattrade.pl
alles-bhp.pl
szkolnaspizarnia.pl
sklep.meqonline.pl

**Comment by hawkeye116477** [comment]
Ok, na tysol tego nie mam, ale na reszcie stron widzę.

**Comment by xxcriticxx** [comment]
@hawkeye116477 ok to zrobisz pull request i zamykamy
