### ISSUE TITLE
taka sobie stronka 

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3914]
@F4z możesz zerknąć jak usunąć te szare elementy ?
https://gry.wp.pl/wiadomosci

**Comment by xxcriticxx** [comment]
wiecej reklam

**Comment by xxcriticxx** [comment]
nvm update filtrow zalatwil rekalmy 👍

**Comment by HateAds** [comment]
@MajkiIT Reklamy ładnie usunięte, ale 1 mały problem pokasowały się niektóre artykuły. 
![p1](https://user-images.githubusercontent.com/29756590/31289070-de3a8808-aac7-11e7-9626-738475bedf1f.png)
![p2](https://user-images.githubusercontent.com/29756590/31289081-e501e6b8-aac7-11e7-9f8e-fdb67b2e58ac.png)
![p3](https://user-images.githubusercontent.com/29756590/31289082-e51c7082-aac7-11e7-8e26-632ff7943433.png)
![p4](https://user-images.githubusercontent.com/29756590/31289083-e5301f92-aac7-11e7-9f73-673b9ce72b0e.png)

**Comment by xxcriticxx** [comment]
@HateAds ta napewno sa rekalmy

**Comment by MajkiIT** [comment]
Poprawione.

**Comment by F4z** [comment]
@MajkiIT Nadal aktualne?
Jeśli tak, to proszę sprawdź tę regułę:
`wp.pl##div[class^="_"]:matches-css(position: relative):matches-css(box-sizing: content-box):matches-css(background-color: rgba):matches-css(pointer-events: none)`
Sprawdziłem ją i raczej nie powinna za dużo ukrywać, ale i tak dobrze by było jakby ktoś jeszcze ją sprawdził i ewentualnie poprawił :)

**Comment by MajkiIT** [comment]
@F4z dziękuję i jest ok, ale potestujemy

**Comment by gomoku** [comment]
> @MajkiIT:  i jest ok,

To coś krótko było ok, bo tylko godzinę...

**Comment by F4z** [comment]
A co jest nie tak?
Ta reguła miała ukryć szare miejsca po reklamie/reklamach i u mnie nadal działa.
Chrome i Firefox z uBO.

Bez reguły:
![image](https://user-images.githubusercontent.com/11742596/31311580-b0b3c9a6-abaf-11e7-9b27-588ca772d143.png)

Z regułą:
![image](https://user-images.githubusercontent.com/11742596/31311585-bf7a2bba-abaf-11e7-8178-0b54ba3bdbcf.png)

**Comment by HateAds** [comment]
@F4z @MajkiIT Mała poprawka jest potrzebna 
Tak jest bez blockera włączonego
![1](https://user-images.githubusercontent.com/29756590/31311723-9ec615de-abb2-11e7-9e4d-73384801bad6.png)
A tak z blockerem włączonym
![image](https://user-images.githubusercontent.com/29756590/31311729-adf14e2a-abb2-11e7-8061-77d30583aa3f.png)

**Comment by F4z** [comment]
To wina tej reguły:
`wp.pl##[class^="_3"][data-reactid] + [class^="_3"][data-reactid] > DIV[class]`
Po odblokowaniu powinno być w porządku:
`wp.pl#@#[class^="_3"][data-reactid] + [class^="_3"][data-reactid] > DIV[class]`

**Comment by gomoku** [comment]
> @F4z:
> A co jest nie tak?
> Ta reguła miała ukryć szare miejsca po reklamie/reklamach i u mnie nadal działa.
> Chrome i Firefox z uBO.

Sam zobacz...też mam uBO, i o ile u mnie na Operze 48 wszystko jest ok, to na FF 56 po prostu jak były, tak dalej są te szare pola:

https://gry.wp.pl/wiadomosci:
![](https://s3.dodajfote.pl/2017/10/08/1466372fcd423b231.png)

https://wiadomosci.wp.pl/wiadomosci-tvp-wlasnie-zbankrutowaly-tak-prosza-o-reklamy-6152942736307841a:
![](https://s3.dodajfote.pl/2017/10/08/screenshot-wiadomosci.wp.pl-2017-10-08-13-25-36f86920f2b3f9f06d.png)

**Comment by F4z** [comment]
To widocznie ja mam jakieś szczęście, bo u mnie w FF działa.
<details><summary>Obrazki</summary>

![image](https://user-images.githubusercontent.com/11742596/31316547-dbb7fd90-ac2f-11e7-8c93-8625a9adad19.png)

![image](https://user-images.githubusercontent.com/11742596/31316550-e96391f2-ac2f-11e7-8c7b-6553c41833f5.png)

![image](https://user-images.githubusercontent.com/11742596/31316556-042b8f3a-ac30-11e7-9f06-37324acaa1e9.png)

</details>

**Comment by xxcriticxx** [comment]
@MajkiIT jest na main 

![screenshot from 2017-10-08 08-05-56](https://user-images.githubusercontent.com/15007183/31316654-9dc4956e-abff-11e7-83d3-628f17b9bb47.png)

**Comment by gomoku** [comment]
@F4z u mnie FF 56 64bit + uBO v1.14.11rc14, a u ciebie?

**Comment by F4z** [comment]
FF 56 64bit + uBO v1.14.10

**Comment by gomoku** [comment]
Sprawdziłem na uBO v1.14.10 i wszystko jest ok, więc v1.14.11rc14 chyba jakaś zabugowana...sam sprawdź jak chcesz.

**Comment by MajkiIT** [comment]
@xxcriticxx poprawione.

**Comment by xxcriticxx** [comment]
@MajkiIT git

**Comment by F4z** [comment]
@gomoku rzeczywiście ta reguła nie działa w uBO v1.14.11rc14.
Ta powinna działać:
`wp.pl##div[class^="_"]:matches-css(position: relative):matches-css(box-sizing: content-box):matches-css(background-color: /rgba/):matches-css(pointer-events: none)`

**Comment by gomoku** [comment]
No teraz jest ok, ten filtr działa na obydwu wersjach uBO, czyli co - tamten poprzedni filtr był nie do końca poprawny czy któraś z wersji uBO miała buga, czy przyczyną była jakaś zmiana w tej nowszej? A tak przy okazji dosłownie prze chwilą wyszła oficjalna 1.14.12 na FF: 
https://addons.mozilla.org/pl/firefox/addon/ublock-origin/

**Comment by F4z** [comment]
Problem był z `:matches-css(background-color: rgba)`, po zmianie na `:matches-css(background-color: /rgba/)` zaczęło, działać. W polskim filtrze jest już jedna reguła, która też zawiera coś takiego, więc moim zdaniem to wynika z jakiejś zmiany albo błędu w nowszej wersji.

**Comment by gomoku** [comment]
Przed chwilą wyszła oficjalna wersja uBO 1.14.14 bo znowu jakiś bug był...

**Comment by gomoku** [comment]
A skoro wątek dotyczy wp.pl i także piszemy o błędach to przy okazji - @MajkiIT czy w tym filtrze: `/^https:\/\/[a-z]{2,10}.\wp\.pl\/[a-zA-Z0-9-_.?=?&%]{250,}/$image` który jest na liście, nie ma oby zbędnej literówki? Chodzi mi o `\w` - czy ten ukośnik nie jest oby zbędny i nie dałeś go tam z rozpędu?

**Comment by MajkiIT** [comment]
@gomoku to jest dobrze. jeśli jest ".\" to oznacza ktopkę a nie dowolny znak.

@hawkeye116477 @xxcriticxx @gzenio22 Macie na stronie wp.pl odłowołania do czegoś takiego? `https://ma.wp.pl/man.gif?clid=`

**Comment by F4z** [comment]
@MajkiIT to w takim przypadku ukośnik powinien być raczej przed kropką.
`/^https:\/\/[a-z]{2,10}\.wp\.pl\/[a-zA-Z0-9-_.?=?&%]{250,}/$image`

**Comment by gzenio22** [comment]
@MajkiIT Ja nie mam :)

**Comment by xxcriticxx** [comment]
@MajkiIT nope

**Comment by hawkeye116477** [comment]
@MajkiIT Nie mam.

**Comment by HateAds** [comment]
@MajkiIT Nie
