### ISSUE TITLE
szwajcaria.net

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3917]
Reklamy

**Comment by MajkiIT** [comment]
```
szwajcaria.net###ali
szwajcaria.net###casa
szwajcaria.net##[id^="banner"]
szwajcaria.net###reklamtex
szwajcaria.net###cas1
szwajcaria.net###lifeboat
szwajcaria.net###lewydolny
```

**Comment by hawkeye116477** [comment]
@MajkiIT Jeszcze po prawej: `szwajcaria.net##[id^="prawareklam"]`
A więc po skróceniu to będzie wyglądać tak:
```
szwajcaria.net###ali, #cas1, #casa, #reklamtex, #lewydolny, #lifeboat
szwajcaria.net##[id^="banner"]
szwajcaria.net##[id^="prawareklam"]
```

**Comment by gomoku** [comment]
Może to dziwne, ale polatałem po tej stronie i podstronach i żadnych reklam o wymienionych id tam nie było, więc zapytam które to reklamy (jakiś przykładowy link/zrzut erkanu)?
