### ISSUE TITLE
krakusik.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#3919]
Reklamy

**Comment by gomoku** [comment]
Polatałem po tej stronie i gdzie nie wejść to w tym panelu po prawej tylko reklamy, więc myślę, że cały prawy panel po prostu do wywalenia: `www.krakusik.pl##.site-right-re`

**Comment by xxcriticxx** [comment]
@MajkiIT dodac do commit 8c07ddf

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki
