### ISSUE TITLE
JS support

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3927]
@gregolsky szukamy specialisty do javy czy jestes w stanie pomoc?

**Comment by gregolsky** [comment]
W Javie nie pisałem nic od czasu studiów. A co dokładnie jest do zrobienia? Mogę spróbować kogoś polecić/przekazać dalej.

**Comment by xxcriticxx** [comment]
@MajkiIT co my dokladnie potrzebujemy? script?

@gregolsky poczekamy chwile niech @MajkiIT sie pokaze?

**Comment by MajkiIT** [comment]
Hej, najlepiej skrypt. Nie zawsze coś można ogarnąć filtrami.

**Comment by xxcriticxx** [comment]
@MajkiIT myslalem ze nie dasz rady po meczu : )

**Comment by MajkiIT** [comment]
@xxcriticxx siedzę na lotnisku :D ... mecz widziałem ale nie było PIWA

**Comment by gregolsky** [comment]
Ja nie bardzo w temacie jestem sorry. Skrypt co ma robić dokładnie i co ma
Java do skryptów :) może chodzi o JavaScript? :P

niedz., 8.10.2017, 20:19 użytkownik Maciej M. <notifications@github.com>
napisał:

**Comment by MajkiIT** [comment]
@gregolsky tak, @xxcriticxx zastosował skrót myślowy :D

**Comment by gregolsky** [comment]
W takim razie tytuł issiołka jest nieadekwatny, a jego opis nie bardzo pomaga w zrozumieniu wymagań. Chętnie pomogę, jeśli nie ograniczają was za bardzo ramy czasowe, tylko muszę wiedzieć o co konkretnie chodzi :)

**Comment by xxcriticxx** [comment]
@gregolsky potrzebny script który by się pozbył reklam na wp.pl

**Comment by gregolsky** [comment]
OK, możesz mi wskazać których? U mnie to wygląda tak z defaultowymi ustawieniami Chrome/uBlock:
![zrzut ekranu z 2017-10-08 23-08-03](https://user-images.githubusercontent.com/1541805/31320982-294429be-ac7e-11e7-91d9-e9a0f7a9880e.png)

**Comment by xxcriticxx** [comment]
@gregolsky jeśli używasz naszych w ubo to łapiemy większość ale jest cieszko. Dlatego scriptem było by łatwiej i szybciej

**Comment by gregolsky** [comment]
Zerknąłem w opcjach. Tak, używam waszych filtrów. Zdaje się, że są defaultowo przez uBlocka włączone, więc git. Czy możesz podesłać screenshot z zaznaczonymi reklamami, o których piszesz, a które chciałbyś żebym usunął JSem?

Dodatkowo chciałem zaznaczyć, że nigdy nie zajmowałem się tworzeniem takich filtrów (chyba że tych prostych po selektorze CSS) i będę musiał zapoznać się z dokumentacją odnośnie pisania tychże - zapewne uBlock ma jakieś reguły, API itp.

**Comment by xxcriticxx** [comment]
@gregolsky chodzi o to żeby nie korzystać z ubo tylko ze scriptu co można odpalić w tampermonkey

**Comment by gregolsky** [comment]
Aaa, zwykły user script. Ok czaję.

pon., 9.10.2017, 00:10 użytkownik xxcriticxx <notifications@github.com>
napisał:

**Comment by xxcriticxx** [comment]
@gregolsky jak znowu sie pokaze @MajkiIT napewno napisze wiecej

**Comment by gomoku** [comment]
Nie rozumiem dlaczego @xxcriticxx nie poprawił do tej pory błędu w tytule.

**Comment by MajkiIT** [comment]
@gregolsky potrzebujemy czegoś co zneutralizuje skrypty JS na WP . Generują one randomowe div itp.

**Comment by gregolsky** [comment]
OK, looknę jutro jak to tam wygląda, bo dziś wieczór idę na Blade Runner'a
;)

pon., 9 paź 2017 o 14:13 użytkownik Maciej M. <notifications@github.com>
napisał:

**Comment by MajkiIT** [comment]
@gregolsky no to dziękuję i udanej zabawy.

**Comment by gomoku** [comment]
> @gregolsky: bo dziś wieczór idę na Blade Runner'a

Również udanego seansu sequelu, z sentymentu do pierwszej części Łowcy Androidów, którą kiedyś dawno temu oglądałem: http://www.filmweb.pl/Lowca.Androidow

**Comment by xxcriticxx** [comment]
@gregolsky co tam slychac po filmie?

**Comment by gregolsky** [comment]
Film ok. Co do Tampermonkey i wp muszę jeszcze popatrzeć. Tam react
generuje te classy server-side a skrypty wszystkie zminifikowane jak
trzeba, więc łatwo nie ma. Muszę przejrzeć wasze filtry może cos mi wpadnie
do głowy. Chcialem usunąć lub podmienić kłopotliwy kod (wybierając trochę
na razie na czuja - js z pubads w nazwie) ale w momencie kiedy Tampermonkey
uruchamia swoje rzeczy jest już po ptakach. Ktoś z was ma jakieś
doświadczenie w pisaniu takich skryptów blokujących reklamy?

czw., 12.10.2017, 21:48 użytkownik xxcriticxx <notifications@github.com>
napisał:

**Comment by gregolsky** [comment]
Znalazłem trochę materiałów dot modyfikacji resourców strony on-the-fly za
pomocą TM. Muszę się podszkolić i popróbować - dam znać jak będzie jakiś
progres.

czw., 12 paź 2017 o 22:05 użytkownik Grzegorz Lachowski <
gregory.lachowski@gmail.com> napisał:

**Comment by xxcriticxx** [comment]
@gregolsky moze webextension bendzie lepsze tak jak twoj luncher

**Comment by xxcriticxx** [comment]
@gjedeer jak bedziesz sie nudzil na githabie szukamy js supportu napisz czy dasz rade cos pomoc

**Comment by gjedeer** [comment]
@xxcriticxx to wp naprawde uzywa sie do czegos innego niz sprawdzanie pingiem czy internet dziala? 😮 

Zobaczę ale nie wiem kiedy, w ten weekend zaszalalem na githubie ale nie wiem kiedy nastepnym razem bede mial chwile.

**Comment by xxcriticxx** [comment]
@gjedeer roger ok

**Comment by gjedeer** [comment]
Napisałem takie arcydzieło ale chyba dość mało odporne na zmiany w stronie.

```js
$('div:contains("REKLAMA")').filter(function(i) {return /^[a-z0-9_]{7}$/g.test(this.className) && this.outerText=="REKLAMA"}).parent().hide()
```

**Comment by xxcriticxx** [comment]
@gjedeer jak bendzie to dzialalo jako user script?

**Comment by gjedeer** [comment]
Nie wiem, na razie skupilem sie na tym zeby dzialalo po wklejeniu do konsoli w przegladarce. Zeby zrobic z tego userscript trzeba chyba tylko wkleic na gorze ten ich naglowek mowiacy na jakich stronach ma sie odpalac itp. 

On October 30, 2017 10:16:53 PM GMT+01:00, xxcriticxx <notifications@github.com> wrote:
>@gjedeer jak bendzie to dzialalo jako user script?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/MajkiIT/polish-ads-filter/issues/3927#issuecomment-340587099

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xxcriticxx** [comment]
@MajkiIT testowales to?

**Comment by MajkiIT** [comment]
Nie, ale potestuje to.

**Comment by xxcriticxx** [comment]
@gjedeer u mnie cos takiego wyskoczylo

Object { length: 0, prevObject: Object, context: HTMLDocument → /, selector: "div:contains("REKLAMA").filter(func…" }

**Comment by xxcriticxx** [comment]
@rysson jak bedziesz sie nudzil to wpadnij nas odwiedzic

**Comment by gjedeer** [comment]
Chociaz wklej caly blad a nie z ... na koncu

On October 31, 2017 7:49:04 PM GMT+01:00, xxcriticxx <notifications@github.com> wrote:
>@gjedeer u mnie cos takiego wyskoczylo
>
>Object { length: 0, prevObject: Object, context: HTMLDocument → /,
>selector: "div:contains("REKLAMA").filter(func…" }
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/MajkiIT/polish-ads-filter/issues/3927#issuecomment-340869396

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xxcriticxx** [comment]
@gjedeer wiecej nic nie bylo zrobie screenshot

![capture](https://user-images.githubusercontent.com/15007183/32287249-8fb6c9e6-bf06-11e7-937b-b72a7ee698ab.PNG)

**Comment by xxcriticxx** [comment]
@gmaslowski jest w stanie pomoc z JS?

**Comment by xxcriticxx** [comment]
@RikoDEV zapraszamy do tego projektu

**Comment by hawkeye116477** [comment]
To może https://github.com/Fratik

**Comment by HateAds** [comment]
@Fratik Jesteś w stanie pomóc nam uporać się z reklamami na wp ?

**Comment by Ravizz** [comment]
Panowie administratorzy chciałem zgłosić, że osoba o nicku @gjedeer mi ubliżyła bez powodu, w tym samym wątku w którym mi ubliżyła już wcześniej pierwsza osoba, czyli tu: https://github.com/MajkiIT/polish-ads-filter/issues/6142 

Z tą pierwszą osobą już wyjaśnione i problemu nie ma, natomiast zaraz jak skończyła tamta osoba, to zaczęła kolejna czyli @gjedeer, oczywiście nie uzasadnił dlaczego mnie tak nazwał, coś tylko wkleił linka do mojego komentarza, w którym nikomu nie ubliżałem, więc nie wiadomo o co mu chodzi.

Nie wiem czy to repozytorium się szanuje czy nie, ale jeśli tak to powinno reagować i nie pozwalać byle chamom obrażać drugich ludzi bez powodu.

Proszę wybaczyć, że piszę w tym  wątku a nie w tamtym, w tamtym nie mogę bo komentarze nie wchodzą, prawdopodobnie autor wątku założył mi blokadę, chociaż możliwe, że jakaś usterka, ale jeszcze skontaktuję się z githubem w tej sprawie, żeby się upewnić.

**Comment by xxcriticxx** [comment]
@Ravizz bardzo przypominasz usera @gomoku

jesli chodzi o userow to staramy podchodzic do tego neutralnie i nie przyjmujemy zadnej strony

**Comment by Ravizz** [comment]
@xxcriticxx ja tu nikomu nie ubliżam, a mi się ubliża, więc najlepiej byłoby gdybyś zajął się/wypowiadał/nagłaśniał/koncentrował na osobach, które to robią, anie na osobach, które są tego ofiarami.

@xxcriticxx jesli chodzi o userow to staramy podchodzic do tego neutralnie i nie przyjmujemy zadnej strony

No widzisz, i ta neutralność jest ok wtedy gdy są sytuacje, że racja/wina obydwu userów jest gdzieś po środku, ale jest nie za bardzo ok w czarno-białej sytuacji jeśli osoba A ubliża bez powodu osobie B, nie powinno się wtedy zrównywać obydwu osób do tego samego poziomu bo to jest obraźliwe dla osoby B, i wtedy powinno się zdecydowanie reagować w stosunku do osoby A, np. skasować/edytować jej komentarz, dać jakieś ostrzeżenie, na tym repo tego nie ma, tylko jakieś zamykanie wątków / zrównywanie wszystkich / wsadzanie do jednego worka / nie rozwiązywanie prostych czarno-białych spraw, które są ewidentne.
