### ISSUE TITLE
gazetatrybunalska.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3930]
Reklamy
`gazetatrybunalska.pl##aside[id*="bns-corner-logo-"]`

**Comment by gomoku** [comment]
Przecież już jest taki wątek: https://github.com/MajkiIT/polish-ads-filter/issues/3875 ?

**Comment by gomoku** [comment]
Tak czy inaczej ten filtr jest lepszy od mojego, ja taki sam filtr brałem pod uwagę wcześniej, ale były tam 3 elementy `##aside[id*="bns-corner-logo-"]`, których nie należało usuwać, i dlatego tego filtru nie utworzyłem, ale teraz spojrzałem jeszcze raz na te 3 elementy i to są: `##section[id*="bns-corner-logo-"]`, po prostu nie zwróciłem uwagi na to, że to `section` a nie `aside`, więc rzeczywiście filtr: `##aside[id*="bns-corner-logo-"]` będzie jednak odpowiedni.
