### ISSUE TITLE
cda-hd.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3942]
@MajkiIT looknie sobie na byle jaki film z flashx. nie otwiera sie tobie nic extra poza regexem?

http://cda-hd.pl/20944/dom-wygranych-the-house-2017-online/

**Comment by MajkiIT** [comment]
@xxcriticxx sprawdź po update

**Comment by xxcriticxx** [comment]
@MajkiIT teraz mi sie otwieraja xtr okna ktore od razu sie zamykaja

**Comment by xxcriticxx** [comment]
@MajkiIT dont worry jest lepjej niz bylo

**Comment by xxcriticxx** [comment]
@MajkiIT testowalem dalej jest problem z flashx linkami

**Comment by MajkiIT** [comment]
@xxcriticxx zrobiłeś update?

**Comment by xxcriticxx** [comment]
tak flashx dalej otwiera xtr okna na foxie

**Comment by MajkiIT** [comment]
@xxcriticxx U mnie jest ok. @hawkeye116477 zerkniesz u siebie?

**Comment by xxcriticxx** [comment]
@MajkiIT dla hawkeye zaczela sie szkolo no more internet.

**Comment by hawkeye116477** [comment]
@MajkiIT Na Waterfoksie jest ok.

**Comment by xxcriticxx** [comment]
@mat41997 zapraszamy na polskie filtry!

**Comment by mat41997** [comment]
Gdzie się włącza tego filtra by działało : )
https://i.gyazo.com/138e16cae8b36b54a969e382339b5f29.mp4

**Comment by xxcriticxx** [comment]
@mat41997 masz juz wlaczone

**Comment by mat41997** [comment]
nie działa : D

**Comment by hawkeye116477** [comment]
Ale który filtr chcesz włączyć? Tam piszesz, że posiadasz uBlock Protector Extension, więc powinieneś raczej włączyć ten filtr -> https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt zamiast AAK Cont.
