### ISSUE TITLE
purepc.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3950]
@hawkeye116477 @F4z  może wam przyjdzie do głowy jak się tego pozbyć, czyli tapety... 

https://www.purepc.pl/karty_graficzne/asus_gtx_1080_ti_strix_zdjecia_i_pelna_specyfikacja

**Comment by F4z** [comment]
Można spróbować tych reguł:
`purepc.pl##a[href^="https://www.purepc.pl/redir2.php"]`
`purepc.pl##script:inject(setTimeout-defuser.js, ubo_fix())`
`purepc.pl##html > body:style(background: #d5d5d5!important;)`

Pierwsza ogólna dla każdej wtyczki, druga i trzecia pod uBlocka, a do AdGuarda dodam odpowiednią regułę.
Tylko sprawdź proszę, czy ta druga reguła nie psuje niczego.

**Comment by MajkiIT** [comment]
@F4z Dziękuję

**Comment by F4z** [comment]
@MajkiIT a tę pierwszą regułę też dodasz?
Ona miała blokować reklamy, które są po prawej stronie - https://www.purepc.pl/karty_graficzne/asus_gtx_1080_ti_strix_zdjecia_i_pelna_specyfikacja

<details><summary>Obrazek</summary>

![image](https://user-images.githubusercontent.com/11742596/31440356-e5381d5c-ae8f-11e7-8564-9dc335a80dbe.png)

</details>

**Comment by MajkiIT** [comment]
@F4z https://github.com/MajkiIT/polish-ads-filter/commit/9057054b725cc498c0cf15a84ec631824a258e45#diff-711027ed0794992ae3b8710d874f3df7

**Comment by F4z** [comment]
@MajkiIT wybacz, nie sprawdziłem tego.

**Comment by MajkiIT** [comment]
@F4z Luzik... lepiej dopytać niż aby coś umknęło.

**Comment by F4z** [comment]
@MajkiIT to jeszcze jedno pytanie.
Nie powinno tam być http**s** zamiast http?
`purepc.pl##a[href^="http://www.purepc.pl/redir"]`

`purepc.pl##a[href^="https://www.purepc.pl/redir"]`

**Comment by MajkiIT** [comment]
`purepc.pl##a[href*="://www.purepc.pl/redir"]`

Tak będzie idealnie :P
