### ISSUE TITLE
lubliniak.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3967]
reklama + cookies 

Strona korzysta z plików cookies w celu realizacji usług - korzystanie z serwisu oznacza ich akceptację. Możesz to zmienić w ustawieniach swojej przeglądarki.

**Comment by MajkiIT** [comment]
`||lubliniak.com.pl/images/re/$image`

**Comment by hawkeye116477** [comment]
`lubliniak.com.pl##DIV[style="background: #fff; padding: 5px; text-align: center; font-size: 11px;"]`
