### ISSUE TITLE
bezprawnik.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#3970]
https://bezprawnik.pl
```
bezprawnik.pl##.ad_desktop_loader
```

![s](https://i.imgur.com/I6h1h1M.png)

Nie wiem jak ogarnąć:
![s](https://i.imgur.com/6HJMAV5.png)

**Comment by gomoku** [comment]
U mnie tego nie ma, (FF/Opera) + uBO + polska lista + polskie kuki +, więc podaj jakieś szczegóły typu: blocker, przeglądarka, listy i przede wszystkim konkretne URL.

**Comment by FadeMind** [comment]
@gomoku 
### SETUP
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Opera Stable x64
AdGuard version:                    | **6.2.424.2123 (beta)**
Stealth mode: | **disabled**

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

**Comment by gomoku** [comment]
@FadeMind mam rozumieć, że na samej polskiej liście main + kuki dalej problem też występuje? 
Czy tylko przy tych wszystkich włączonych listach?

**Comment by FadeMind** [comment]
@gomoku podałem ci setup przy którym problem występuje.

**Comment by gomoku** [comment]
Rozumiem, ale obowiązkiem zgłaszającego jest przed zgłoszeniem poodznaczać po kolei listy i upewnić się czy problemem nie jest któraś lista, bo to jest repozytorium polskich list, a nie repozytorium adguard, KAD, czy I don't care about cookies, pomyliłeś adresy, no chyba, że to jest jako prośba ogólna żeby ktoś poświęcił prywatny czas na rozwiązywanie problemów nie związanych z tym repozytorium.

**Comment by F4z** [comment]
Jeśli chodzi o ten biały prostokąt z pierwszego obrazka, to może wynikać z tego, że AdGuard w wersji dla Windowsa trochę inaczej działa niż rozszerzenia do przeglądarek i nie zawsze "wycina" wszystkie "ramki".

Swoją drogą ja z uBO + Chrome/Firefox też to widzę.

<details><summary>Obrazek</summary>

![image](https://user-images.githubusercontent.com/11742596/31498076-54225080-af61-11e7-860e-c1c162cd0a49.png)

</details>

**Comment by gomoku** [comment]
@F4z tylko na polskiej liście + polskie kuki też?

**Comment by F4z** [comment]
Nawet jak wyłączę pozostałe listy i zostawię tylko `polskie filtry do Adblocka i uBlocka` i `Adblock & uBlock polish cookies filters` nadal to widzę.

**Comment by gomoku** [comment]
U mnie tego nie ma:

<details> 
<summary>Zrzut ekranu:</summary>

![](https://s3.dodajfote.pl/2017/10/12/bezprawnike992f23c4c1f438b.png)

</details>

**Comment by F4z** [comment]
To najprawdopodobniej kwestia szerokości okna.
Jeśli jest mniej niż 1025px to nie wyświetla tej reklamy/inaczej się elementy układają i jest to ukryte.

**Comment by gzenio22** [comment]
ja tez widze to co @FadeMind ja na Ubo

**Comment by gomoku** [comment]
> @F4z: To najprawdopodobniej kwestia szerokości okna.

Tak, potwierdzam, z tym, że mam 1280x1024 i nie mam tej reklamy i dopiero po zmianie na 1366 na 768 wyskakuje więc to gdy jest więcej niż 1280px to wyskakuje.

**Comment by gomoku** [comment]
@FadeMind a te reguły testowałeś - czy usuwają ci wszystkie białe dziury?

**Comment by FadeMind** [comment]
@gomoku zostają białe boxy:
![s](https://i.imgur.com/g06oWC6.png)

![s](https://i.imgur.com/9VYlG2u.png)

**Comment by gomoku** [comment]
Dodałem dwa nowe filtry, skopiuj-wklej wszystkie i sprawdź jeszcze raz.

**Comment by FadeMind** [comment]
@gomoku dobra robota. Dziękuję.
