### ISSUE TITLE
kuchniawedwoje.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3971]
strona jest zielona resztki box

![capture](https://user-images.githubusercontent.com/15007183/31544062-1ca61052-afe7-11e7-97d0-f48b68ef6a2b.PNG)

**Comment by gomoku** [comment]
`kuchniawedwoje.pl##[id^="ffbp"]`

**Comment by hawkeye116477** [comment]
Ja tam tego nie widzę, tylko mały pasek na dole, a na to trafi reguła na listę social -> `kuchniawedwoje.pl###ffbp`.
