### ISSUE TITLE
lososwkuchni.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3972]
http://lososwkuchni.pl/tag/kapary/

![capture](https://user-images.githubusercontent.com/15007183/31544146-687d8758-afe7-11e7-9afe-4e5e98b2e776.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx u mnie pusto

**Comment by HateAds** [comment]
U mnie też pusto.

**Comment by xxcriticxx** [comment]
@MajkiIT moze cos z host file

**Comment by gomoku** [comment]
A u mnie jest, zdążyłem utworzyć filtr, zanim strona [padła](https://s3.dodajfote.pl/2017/10/13/lososwkuchni02c426f4982ecb1e.png): 
`lososwkuchni.pl###heateor_ss_browser_popup_bg, #the_champ_sharing_more_providers`
ale nie zdążyłem dobrze go przetestować.

**Comment by xxcriticxx** [comment]
@hawkeye116477 zerkniesz na te facebukki?

**Comment by hawkeye116477** [comment]
To lepiej zostawić, od tego jest raczej filtr Fanboy's Antithirdparty Social.
Ale można usunąć resztkę -> `lososwkuchni.pl###text-6:has-text(ŁOSOŚ NA FB)`
