### ISSUE TITLE
easypaste.org

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3975]
push push 

https://www.easypaste.org/?lang=pl

**Comment by MajkiIT** [comment]
bez skryptu nie da rady ...

**Comment by hawkeye116477** [comment]
Najlepiej zablokować to za pomocą przeglądarkowej funkcji blokowania powiadomień i po sprawie 😄 .

**Comment by xxcriticxx** [comment]
@gregolsky na takie cos znajdziesz jakies czary mary?
