### ISSUE TITLE
interhotel.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3976]
cookie fix 

W ramach naszej witryny stosujemy pliki cookies w celu świadczenia Państwu usług na najwyższym poziomie, w tym w sposób dostosowany do indywidualnych potrzeb. Korzystanie z witryny bez zmiany ustawień dotyczących cookies oznacza, że będą one zamieszczane w Państwa urządzeniu końcowym. Możecie Państwo dokonać w każdym czasie zmiany ustawień dotyczących cookies. Więcej szczegółów w Polityce cookies.

**Comment by gzenio22** [comment]
ja nie widze niestety

**Comment by hawkeye116477** [comment]
Komunikatu nie widzę, ale fix by się przydał, bo widać tylko tło -> `interhotel.pl#@#:not(input)[id*="cookie"]`

**Comment by xxcriticxx** [comment]
@hawkeye116477 no school today?

**Comment by hawkeye116477** [comment]
@xxcriticxx Ta, piątek, sobotę i niedzielę mam wolną.
Ja bym w ogóle zamienił tą długą regułę -> interhotel.pl##[style="width:1200px; margin:5px auto; padding:10px;background-color:#fff;color:#666; text-align:justify;font-size:13px;border:solid 1px #666;"] na krótszą -> /cookiewarning*.js.
Albo zamiast gwiazdki wpisać 4, ale chyba lepiej będzie dać gwiazdkę, to wtedy przy okazji zablokują się też poprzednie wersje skryptów, które zapewne są na innych stronach, dlatego Fanboy dodał taką regułę.
`https://github.com/Heather-Herbert/CookieWarning`
