### ISSUE TITLE
lafe.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3977]
cookies

![capture](https://user-images.githubusercontent.com/15007183/31567352-17cd1462-b03d-11e7-9999-7cf47f8c38b4.PNG)

**Comment by gzenio22** [comment]
lafe.pl###cinfo

**Comment by hawkeye116477** [comment]
Jeszcze margines -> `lafe.pl##.cinfo:style(padding-bottom: 0px!important;)`
