### ISSUE TITLE
pudelek.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3981]
puste miejsca po reklamach

**Comment by hawkeye116477** [comment]
Resztka na głównej -> `pudelek.pl##.cb.ptb10.mtb15.mbb:nth-of-type(11)`
Resztka w artykułach -> `pudelek.pl##.mtb10`
No i social -> `pudelek.pl###o2FBFanbox`
Oraz reklama po prawej -> `pudelek.pl##DIV[style="position: relative; padding-bottom: 4px;"]`

**Comment by MajkiIT** [comment]
@hawkeye116477 nie ma nic na głównej oraz reklamy po prawej. @xxcriticxx zerkniesz?

**Comment by hawkeye116477** [comment]
@MajkiIT Tej resztki już nie widzę, ale reklama po prawej pojawia się jak przescrollujesz w dół, a potem z powrotem na górę.
![screenshot_20171015_115518](https://user-images.githubusercontent.com/19818572/31583660-dcc005e6-b19f-11e7-8e88-1b20e2a1bce9.png)

**Comment by hawkeye116477** [comment]
@MajkiIT Tej resztki już nie widzę, ale reklama po prawej pojawia się jak przescrollujesz w dół, a potem z powrotem na górę.
No i oczywiście są jakieś dziwne requesty do wp.
![screenshot_20171015_115518](https://user-images.githubusercontent.com/19818572/31583660-dcc005e6-b19f-11e7-8e88-1b20e2a1bce9.png)

**Comment by xxcriticxx** [comment]
@MajkiIT widze to samo reklame co @hawkeye116477 pokazal

**Comment by MajkiIT** [comment]
@xxcriticxx @hawkeye116477 dodałem. Dzięki

**Comment by xxcriticxx** [comment]
@MajkiIT teraz jest git

**Comment by mat41997** [comment]
@MajkiIT nie jest git
![2017-10-18 06_39_36-pudelek - sensacja plotka komentarz](https://user-images.githubusercontent.com/5884000/31701244-32ffa7c8-b3cf-11e7-9839-1d70411c948d.png)
