### ISSUE TITLE
superfilm.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#3985]
http://superfilm.pl/film-Arirang

Macie tutaj adblocka? jeśli tak to czy pomaga reguła.
`@@||polvod.pl/advertisement.js$script,domain=superfilm.pl`

**Comment by xxcriticxx** [comment]
@MajkiIT sorry geo locked

Ten film nie jest dostępny w Twojej lokalizacji

**Comment by MajkiIT** [comment]
@xxcriticxx Dziekuję

**Comment by xxcriticxx** [comment]
@MajkiIT zrobisz mi na jakies firmie pl proxy na password?

**Comment by hawkeye116477** [comment]
@MajkiIT Ta, pomaga.

**Comment by MajkiIT** [comment]
@hawkeye116477 dzięki 
@xxcriticxx chcesz cały ruch przepuścić przez to proxy?

**Comment by xxcriticxx** [comment]
@MajkiIT nie tylko geolock stuff

**Comment by MajkiIT** [comment]
Ok. To coś przygotuje.
