### ISSUE TITLE
konkurs 10000+

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#3987]
kto pierwszy stworzy issue numer 4000 wygra nagrode

@MajkiIT poda info na temat nagrody nobla!

**Comment by mat41997** [comment]
ok. wygrałem ; )
https://github.com/MajkiIT/polish-ads-filter/issues/4000

**Comment by xxcriticxx** [comment]
Trzeba bendzie zmienić konkurs na 5000+

@MajkiIT nagrody?

**Comment by mat41997** [comment]
no i kto teraz w to uwierzy?

**Comment by xxcriticxx** [comment]
poczekamy na @MajkiIT cos da sie zalatwic

**Comment by MajkiIT** [comment]
Jedynie co mogę zaproponować to jakieś koszulki projektu ... nikt nie daje funduszy to będę coś fundował z własnej kieszeni.

**Comment by xxcriticxx** [comment]
@MajkiIT jak zrobisz z napisem `xxcriticxx` to zrzuce pare zlotych

**Comment by mat41997** [comment]
darmowa gierka przez tydzień
https://www.dobreprogramy.pl/Watch-Dogs-na-PC-za-darmo-przez-tydzien,News,84068.html

**Comment by mat41997** [comment]
ok. wygrałem ; )
#5000

**Comment by MajkiIT** [comment]
To nie sztuka zawalić kogoś 200 zgłoszeniami ... no ale ok

**Comment by xxcriticxx** [comment]
@mat41997 nowy challenge!

**Comment by mat41997** [comment]
znowu darmowe gierki, tym razem do 23 grudnia
https://freetrial.ubisoft.com/

**Comment by xxcriticxx** [comment]
zeby bylo szybciej i prosciej

**Comment by KonoromiHimaries** [comment]
@xxcriticxx nie ma już konkursu na 6000?

**Comment by xxcriticxx** [comment]
@KonoromiHimaries dla ciebie jest!

**Comment by krystian3w** [comment]
A i nie ma 😜 😝
