### ISSUE TITLE
kurnik.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#3988]
https://www.kurnik.pl/gomoku/

filtry
https://i.gyazo.com/138e16cae8b36b54a969e382339b5f29.gif
&
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt

ss
![2017-10-15 16_54_30-gomoku](https://user-images.githubusercontent.com/5884000/31585929-52fc5988-b1ca-11e7-8491-2768ce7a9dcd.png)
jak widać na ss'ie prostokącik jest pusty w środku po zastosowaniu filtru ``adblock_social_list``

chrome 61.0.3163.100
uBO + uBO-PE 12.14

**Comment by xxcriticxx** [comment]
@mat41997 masz cos jeszcze xtra umnie z protectorem dziala

![capture](https://user-images.githubusercontent.com/15007183/31586542-78ff32b0-b1a0-11e7-9cb1-6a46d7cb9a02.PNG)

**Comment by mat41997** [comment]
Filtry protektora i reszte filtrów z waszego repozytorium.

Spróbuj zamknąć karte i wejść do gry jeszcze raz.

**Comment by hawkeye116477** [comment]
@mat41997 `kurnik.pl#@#.fb`
