### ISSUE TITLE
techmaniachd.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#3992]
Reklamy u góry oraz z prawej:
```
techmaniachd.pl##img[src*="amazon-adsystem.com"]
techmaniachd.pl##a[href*="s.click.aliexpress.com"]
```

Resztki po reklamach -> `techmaniachd.pl##.HTML.widget`
Social -> `techmaniachd.pl##.PlusBadge.widget`

**Comment by mat41997** [comment]
@MajkiIT zerknij
![2017-10-19 16_23_37-blog techmaniachd_ strona glowna - techmaniachd](https://user-images.githubusercontent.com/5884000/31775865-1d4d6b6a-b4ea-11e7-8dbd-e822c3a5305c.png)
