### ISSUE TITLE
tabletowo.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#3997]
![2017-10-16 03_19_16-tabletowo pl - twoje zrodlo informacji o swiecie mobilnym](https://user-images.githubusercontent.com/5884000/31591576-386feeac-b221-11e7-8136-14f69e6881b8.png)
![2017-10-16 03_20_27-tabletowo pl - twoje zrodlo informacji o swiecie mobilnym](https://user-images.githubusercontent.com/5884000/31591578-3ccde4d6-b221-11e7-8774-61c9c88daf74.png)

filtry i ustawienia
https://gist.github.com/mat41997/20465841380e6bd59bf7ff52fd301d01

chrome 61.0.3163.100
uBO 1.14.12 + uBO-PE 12.15
win 10 x64

**Comment by gzenio22** [comment]
tabletowo.pl##.textwidget2

To ukrywa o jeden obrazek za dużo @hawkeye116477 @MajkiIT zerkniecie? pewnie dacie rade coś poprawić

**Comment by hawkeye116477** [comment]
Już było niedawno blokowane, widać p. Katarzynie i jej ekipie się nudzi 😃 .
Reklama górna -> `tabletowo.pl##.rektop.rb_widget_text.widget`
Komputronik -> `tabletowo.pl##.sidebar > .rb_widget_text.widget:nth-of-type(2)`
Hosting -> `tabletowo.pl##.rb_widget_text.widget:nth-of-type(3)`

**Comment by hawkeye116477** [comment]
@MajkiIT Te 2 reguły za dużo chowają
 ```
tabletowo.pl##.srodek
tabletowo.pl##.rb_widget_text.widget
```
