### ISSUE TITLE
btc-sms.eu

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#3998]
![2017-10-16 03_27_46-btc-sms - kup bitcoin za sms](https://user-images.githubusercontent.com/5884000/31591683-2d443ce4-b222-11e7-81af-0ae39e853752.png)

filtry i ustawienia
https://gist.github.com/mat41997/20465841380e6bd59bf7ff52fd301d01

chrome 61.0.3163.100
uBO 1.14.12 + uBO-PE 12.15
win 10 x64

**Comment by gzenio22** [comment]
Moze tak?

btc-sms.eu##.banner
