### ISSUE TITLE
dbnao.net

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#3999]
![2017-10-16 03_57_05-dragon ball nao im akiry toriyamy - polski serwis o dragon ballu z gt kai s](https://user-images.githubusercontent.com/5884000/31592159-93a367fe-b226-11e7-8b69-e4202465b473.png)

![2017-10-16 03_57_19-dragon ball nao im akiry toriyamy - polski serwis o dragon ballu z gt kai s](https://user-images.githubusercontent.com/5884000/31592162-9bcb55b8-b226-11e7-8bea-f34be6b47906.png)

filtry i ustawienia
https://gist.github.com/mat41997/20465841380e6bd59bf7ff52fd301d01

chrome 61.0.3163.100
uBO 1.14.12 + uBO-PE 12.15
win 10 x64

**Comment by gzenio22** [comment]
dbnao.net###goo_cb2.ad

Nie mam pewności
