### ISSUE TITLE
www.ingservicespolska.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#40]
cookies

Ważne: strona wykorzystuje pliki cookies.

Używamy informacji zapisanych w plikach cookies m.in. w celach statystycznych oraz w celu dopasowania serwisu do indywidualnych potrzeb użytkownika. W programie służącym do obsługi internetu możesz zmienić ustawienia dotyczące akceptowania plików cookies. Korzystanie ze strony bez zmiany ustawień dotyczących plików cookies oznacza, że będą one zapisane w pamięci urządzenia. Więcej informacji, wraz ze wskazówkami dotyczącymi zmiany ustawień, można znaleźć w Polityce cookies

**Comment by MajkiIT** [comment]
poprawione
