### ISSUE TITLE
craftportal.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4000]
![2017-10-16 04_07_50-minecraft portal - craftportal pl - najswiezsze nowosci prosto ze swiata minecra](https://user-images.githubusercontent.com/5884000/31592337-d8fa2cc4-b227-11e7-93ec-7cc76188fd1f.png)

filtry i ustawienia
https://gist.github.com/mat41997/20465841380e6bd59bf7ff52fd301d01

chrome 61.0.3163.100
uBO 1.14.12 + uBO-PE 12.15
win 10 x64

**Comment by gzenio22** [comment]
craftportal.pl###secondary

**Comment by mat41997** [comment]
ostało się jeszcze trochę tych reklam

![2017-10-18 06_09_58-minecraft portal - craftportal pl - najswiezsze nowosci prosto ze swiata minecra](https://user-images.githubusercontent.com/5884000/31700645-18d87996-b3cb-11e7-841c-ef9c1b45a860.png)

https://craftportal.pl/forum/index.php?/topic/103344-t%C5%82umacze-poszukiwani/
![2017-10-18 06_07_13-tlumacze poszukiwani - inne - minecraft forum - craftsite pl](https://user-images.githubusercontent.com/5884000/31700622-ec700b1c-b3ca-11e7-99a5-2ede10904139.png)

**Comment by mat41997** [comment]
@xxcriticxx sprawdź bo @MajkiIT mi nie wierzy
