### ISSUE TITLE
bithub.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#4003]
Reklamy

**Comment by MajkiIT** [comment]
`||bithub.pl/polecamy/$image`

**Comment by mat41997** [comment]
po zastosowaniu ``||bithub.pl/polecamy/$image``

![2017-10-16 13_43_55-bithub pl _ bitcoin informacje bitcoin kryptowaluty blockchain](https://user-images.githubusercontent.com/5884000/31610513-95916b0e-b278-11e7-9ef5-104d535e9b46.png)
![2017-10-16 13_44_18-bithub pl _ bitcoin informacje bitcoin kryptowaluty blockchain](https://user-images.githubusercontent.com/5884000/31610514-9ad9b292-b278-11e7-89cc-e8a416039784.png)
![2017-10-16 13_44_32-bithub pl _ bitcoin informacje bitcoin kryptowaluty blockchain](https://user-images.githubusercontent.com/5884000/31610517-9e2e15c8-b278-11e7-8bec-17f455a94e5e.png)
