### ISSUE TITLE
chillizet.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4006]
http://www.chillizet.pl/News/Ludzie/Czy-warto-malowac-sie-do-pracy-Najnowsze-badania-wykazaly-ktore-kobiety-zarabiaja-wiecej-5742

![2017-10-16 14_55_51-naukowcy pokazali czy warto malowac sie do pracy - chillizet pl](https://user-images.githubusercontent.com/5884000/31613126-6bf23242-b282-11e7-9394-08154efba918.png)

moje filtry
https://gist.github.com/mat41997/0c13a6c7c74f5010f5d567cf3b2812a4

ubo 1.14.12 & ubo-pe 12.15
chrome 61.0.3163.100
win10 x64

**Comment by gzenio22** [comment]
chillizet.pl##.banner-radiostacja
