### ISSUE TITLE
slodkipomysl.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4007]
cookie fix

https://slodkipomysl.pl/tort-ciasteczkowy-potwor/

**Comment by hawkeye116477** [comment]
@xxcriticxx Jaki tu fix jest potrzebny? Wszystko jest raczej ok, jedynie po prawej stronie reklama z jakimś syfem jest „junk removal" -> slodkipomysl.pl##a[href="http://www.bestdumpsterdeals.com/"]
