### ISSUE TITLE
ddob.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4016]
cookie

**Comment by hawkeye116477** [comment]
@xxcriticxx Gdzie? Nie widzę ich nawet z wyłączonym uBlockiem.

**Comment by MajkiIT** [comment]
u mnie też bez ciastek ...

**Comment by xxcriticxx** [comment]
no dzisaj niema ciasteczek ale zrobie czyszczenie i dam znac

**Comment by xxcriticxx** [comment]
nie wiem co tam widzialem chyba zamykamy
