### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by zbysiu172** [MajkiIT/polish-ads-filter#4017]
### Co trzeba zrobić aby reklama/element się pojawił
1.odpalic yt i wlaczyc film
2.
3.

### Twoja konfiguracja
**Przeglądarka:**
chrome
**Operating system:**
win10 
**Blocker:**
adblocker
**Używane filtry:**
1
2.
3.
4.

### Zrzut ekranu
```
wstaw tutaj link
```
https://www.youtube.com/watch?v=uKT2IJYMumE
![bez tytulu](https://user-images.githubusercontent.com/25231735/31633659-68300faa-b2c1-11e7-9530-c63db061967e.png)

**Comment by gzenio22** [comment]
Podaj prosze liste swoich filtrow i powiedz co jest problemem bo na screenie nie widze nic niepokojacego?

**Comment by zbysiu172** [comment]
![bez tytulu](https://user-images.githubusercontent.com/25231735/31649459-4cd58bac-b313-11e7-8778-f3d8937854ae.png)
włączają sie reklamy przy wlaczonym adblocku

**Comment by mat41997** [comment]
polecam gorąco ublock'a origin, ma więcej fitrów i mniej ramu zjada : D
nie ma sensu dodawać do polskich filtrów anglojęzycznych stron gdy anglojęzyczne filtry już je wspierają.

**Comment by blocker999** [comment]
@zbysiu172  Jak tam dalej masz te reklamy na yt bo ja ich niewidze, aha a testowałeś ublocka?

Najlepiej op szczegółowo kiedy one wyskakują, coś zaradzimy.
