### ISSUE TITLE
wiescimiechowskie.prv.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4018]
![2017-10-17 11_48_39-wiesci miechowskie - gazeta informacyjno-reklamowa](https://user-images.githubusercontent.com/5884000/31658495-7027bb0c-b331-11e7-984f-fad90a4a0206.png)

moje filtry
https://gist.github.com/mat41997/d049ba53dd0fca8c3dad404ac58c701f

ubo 1.14.12 & ubo-pe 12.15
chrome 61.0.3163.100
win10 x64

**Comment by MajkiIT** [comment]
@F4z zerkniesz swoim okiem?

**Comment by xxcriticxx** [comment]
albo okularami

**Comment by xxcriticxx** [comment]
to jest chyba orginaly url 

http://www.wiesci.info.pl/

**Comment by gomoku** [comment]
```
wiescimiechowskie.prv.pl##.menu, #prvAliasBanner
wiesci.info.pl###rightSide
```
