### ISSUE TITLE
jablonka.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4020]
pusta miesce po reklamie + newsletter popup

**Comment by MajkiIT** [comment]
```
jablonka.info###gkTop1
jablonka.info###gkSidebar > .nomargin.box
jablonka.info###gkMainbodyTop > .box + .box
```

**Comment by hawkeye116477** [comment]
Ten newsletter to raczej reklama.
![screenshot_20171025_121313](https://user-images.githubusercontent.com/19818572/31993589-f1810a3a-b97d-11e7-93ee-43fc961a4428.png)
`jablonka.info###gk-newsletter-popup`

**Comment by hawkeye116477** [comment]
Social -> `jablonka.info###gkSocialMenu`
