### ISSUE TITLE
ikrotoszyn.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4021]
reklama

**Comment by gzenio22** [comment]
ikrotoszyn.pl##.items2

Ktos musi tylko podniesc teraz strone

**Comment by MajkiIT** [comment]
`ikrotoszyn.pl##.partners2`

**Comment by hawkeye116477** [comment]
Social -> `||ikrotoszyn.pl/tmpl/images/*_top_belka.png$image`
