### ISSUE TITLE
money.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4024]
![2017-10-18 05_39_12-money pl - portal finansowy - wiadomosci notowania kursy wskazniki gieldy f](https://user-images.githubusercontent.com/5884000/31699995-b9d03a8c-b3c6-11e7-93ad-290886d438cd.png)

http://biztok.money.pl/gospodarka/artykul/polski-rynek-pracy-eksperci-prognozuja-udana,236,0,1898476.html
![2017-10-18 07_35_56-polski rynek pracy eksperci prognozuja udana jesien i koncowke roku](https://user-images.githubusercontent.com/5884000/31702422-2c7056f2-b3d7-11e7-9a81-470957d27c68.png)

moje filtry
https://gist.github.com/mat41997/d049ba53dd0fca8c3dad404ac58c701f

ubo 1.14.12 & ubo-pe 12.16
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
`biztok.money.pl##.news:nth-of-type(2)`
