### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4026]
![2017-10-18 06_56_27-elektroda pl - elektronika forum dyskusyjne forum komputerowe forum gsm foru](https://user-images.githubusercontent.com/5884000/31701608-d32a5980-b3d1-11e7-9a30-49d3a112860e.png)

moje filtry
https://gist.github.com/mat41997/d049ba53dd0fca8c3dad404ac58c701f

ubo 1.14.12 & ubo-pe 12.16
chrome 62.0.3202.62
win10 x64

**Comment by xxcriticxx** [comment]
@mat41997 znajoma nam firma nie blokujemy

**Comment by mat41997** [comment]
@xxcriticxx Nie żartuj bo zrobię wam zaraz konkurencje..

**Comment by xxcriticxx** [comment]
@mat41997 dodaj sobie filtry lokalnie jak tam jesteś często

**Comment by mat41997** [comment]
poszło
https://github.com/mat41997/polish-ads-filter/commit/a104ada9d2f491f4c2695e7ceb25c65ca87d9692
