### ISSUE TITLE
coinroom.com

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4027]
blokuje mi kantorek : /
![2017-10-18 10_40_03-coinroom _ strona glowna](https://user-images.githubusercontent.com/5884000/31708969-de6de158-b3f0-11e7-9ece-e03e2d778f8a.png)

filtr odpowiedzialny za błąd
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt

moje filtry
https://gist.github.com/mat41997/d049ba53dd0fca8c3dad404ac58c701f

ubo 1.14.12 & ubo-pe 12.16
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
`@@||coinroom.com/Modules/UI/Cookie/Cookie.js?0d3d1e$script`
