### ISSUE TITLE
odcinki-seriali.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4029]
cookie fix + ad block (na foxie)

https://odcinki-seriali.pl/coma-when-the-music-is-a-flame-czworka/

![capture](https://user-images.githubusercontent.com/15007183/31783864-baa4c3f8-b4cd-11e7-8af5-b57a097ef7ba.PNG)

**Comment by MajkiIT** [comment]
`@@||odcinki-seriali.pl^$generichide`

**Comment by xxcriticxx** [comment]
z protectorem dziala ? niema teraz chroma i jak sprawdzic

**Comment by mat41997** [comment]
nope
![2017-10-20 09_11_43-blad dotyczacy prywatnosci](https://user-images.githubusercontent.com/5884000/31809199-d692aebe-b576-11e7-99bb-b3babfef693f.png)
![2017-10-20 09_12_30-odcinki seriali - seriale filmy wiadomosci i muzyka online](https://user-images.githubusercontent.com/5884000/31809200-d7f81582-b576-11e7-9a5c-79e84853fc80.png)

**Comment by mat41997** [comment]
@xxcriticxx a prawdź jak działa z killerem XD
https://gitlab.com/xuhaiyang1234/AAK-Cont#anti-adblock-killer-continued

**Comment by xxcriticxx** [comment]
z aak jest tak jak na pierwszym obrazku

**Comment by mat41997** [comment]
a z aak-cont?

**Comment by xxcriticxx** [comment]
@mat41997 tak robie to od 2 lat :)

**Comment by mat41997** [comment]
strona coś padła
![2017-10-20 14_48_03-404 page not found](https://user-images.githubusercontent.com/5884000/31821537-bb579b44-b5a5-11e7-93d4-37fb18c87fab.png)

**Comment by xxcriticxx** [comment]
bylo za duzo polaczen *dead*

**Comment by mat41997** [comment]
koledzy od protektora naprawili ^^

**Comment by xxcriticxx** [comment]
@mat41997 I tak oglondam używając kodi
