### ISSUE TITLE
twitch.tv

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#4030]
Pojawiły sie reklamy na Twitchu moze ktos potwierdzic i zbadac sytuacje? w trakcie streamu wskakuje reklama dzis trafilem na reklame Dastiny 2

**Comment by xxcriticxx** [comment]
to bendzie chyba robota na easylist

**Comment by gzenio22** [comment]
kurde przepraszam :(

**Comment by xxcriticxx** [comment]
na easyforum pisze zeby uzywac Streamlink and VLC

**Comment by gzenio22** [comment]
what? VLC wiem co to ale stream link? Xd

**Comment by xxcriticxx** [comment]
@gzenio22 https://github.com/streamlink/streamlink

**Comment by mat41997** [comment]
@gzenio22 wgraj ublock origin > odpal wszystkie filtry w tym 2 polskie > opcjonalnie możesz dograć jeszcze ublock protector extension

powinno być wtedy ok. jeśli nadal nie będzie działać to zgłoś się do jednego z anglojęzycznych dostawców filtrów : adguard, easylist, fanboy..

**Comment by xxcriticxx** [comment]
Na easylist podają ze rekama jest częścią filmu

**Comment by gzenio22** [comment]
Dzieki chyba trzeba przywyknac :)
