### ISSUE TITLE
slodkipomysl.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4034]
„Junk removal" z prawej -> `slodkipomysl.pl##a[href="http://www.bestdumpsterdeals.com/"]`

**Comment by MajkiIT** [comment]
dasz zrzut?

**Comment by hawkeye116477** [comment]
@MajkiIT Proszę bardzo.
![screenshot_20171020_220701](https://user-images.githubusercontent.com/19818572/31839839-1bd4129e-b5e3-11e7-8379-663b05209268.png)

**Comment by xxcriticxx** [comment]
@hawkeye116477 to nie link to strony?

ja mam takie cos jak zjade do dolu

![capture](https://user-images.githubusercontent.com/15007183/31840118-d73c76fc-b5b1-11e7-9056-3c4c0d006c7c.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx No link, ale prowadzi do syfu, więc raczej do wywalenia.

**Comment by xxcriticxx** [comment]
@hawkeye116477 ok

**Comment by hawkeye116477** [comment]
@xxcriticxx A co do tego u ciebie na zdjęciu, to to jest pozostałość po social, ale Fanboy's Social Blocking to blokuje, więc zapewne masz włączoną polską listę Social, a wyłączoną od Fanboya.

**Comment by xxcriticxx** [comment]
@hawkeye116477 tak jade na nowym skadaku starszy od ciebie

**Comment by MajkiIT** [comment]
@hawkeye116477 dzięki
