### ISSUE TITLE
iholandia.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4045]
@MajkiIT need regex!

www.iholandia.tv/index.php/tvn/

**Comment by MajkiIT** [comment]
Sprawdź proszę to
`||algorun.top/$subdocument,domain=openkatalog.ml`

**Comment by xxcriticxx** [comment]
na ten shit z prawej strony

`||openkatalog.ml/epg/?channel=*$subdocument`
