### ISSUE TITLE
filmowoonline.cba.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4046]
ad block strona maybe fake!

![capture](https://user-images.githubusercontent.com/15007183/31851513-3aca2e20-b635-11e7-9bfe-4b78c569a723.PNG)

**Comment by MajkiIT** [comment]
`filmowoonline.cba.pl##[class^="k9a002-"]`
Ale to chyba fake.

**Comment by xxcriticxx** [comment]
@MajkiIT no good no working

**Comment by gomoku** [comment]
Bo losowa klasa, trzeba dać np. tak:
`filmowoonline.cba.pl##[class$="-hide"]` lub
`filmowoonline.cba.pl##html > body > div[class]:nth-of-type(5)`
