### ISSUE TITLE
dekoder.ws

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4049]
@MajkiIT regex please jak przelaczasz zrodla

http://dekoder.ws/channel/discovery-channel/

![capture](https://user-images.githubusercontent.com/15007183/31853168-478ed38c-b652-11e7-9c18-763d3200def9.PNG)

**Comment by gomoku** [comment]
`www.zajefajna.com##img[alt="Pobierz plik"][title="Pobierz plik"]` albo z samym alt lub title.
