### ISSUE TITLE
firstonetv.net

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4050]
https://www.firstonetv.net/Live/Poland/Discovery-Channel-23

![capture](https://user-images.githubusercontent.com/15007183/31853200-d5419890-b652-11e7-800c-17aef37163af.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Wyższa szkoła jazdy. Raczej to jest sprawa dla reportera 😃 .

**Comment by gomoku** [comment]
To jest anty-adblock, a że ogólnie strona jest angielskojęzyczna to powinno się to zgłosić raczej na https://xuhaiyang1234.gitlab.io/AAK-Cont/

**Comment by xxcriticxx** [comment]
@mat41997 widze ze masz jakiegos developera stron w znajomych moze bys zapytal o js support/script?

**Comment by mat41997** [comment]
@xxcriticxx Naprawdę? Nie wiedziałem że mam.. A kogo konkretnie mam zapytać? Bo nie wiem.

**Comment by xxcriticxx** [comment]
@mat41997 ten laski Haylee Schafer

**Comment by mat41997** [comment]
@xxcriticxx kilka razy zgłosiłem mu błąd w pluginie, nie znam go zbyt dobrze i nie znam angielskiego na tyle dobrze by namówić go na pisanie skryptów blokujących mu zarobek z reklam..

na jakiś forach kogoś poszukaj, tematy pootwieraj, popytaj.. może ktoś się znajdzie?
ja dużo na mpcforum jestem, tam jest masa developerów.

**Comment by xxcriticxx** [comment]
@mat41997 ja tylko jestem na githubie to jest wszystko

**Comment by hawkeye116477** [comment]
Na mpcforum to oni zajmują się głównie oszukiwaniem w grach 😄  .

> ja dużo na mpcforum jestem

Czyli często korzystasz z cheatów i botów, nie ładnie 😃 .

**Comment by gomoku** [comment]
Wydaje mi się, że pośpieszyłeś się z osądem, bo nie wszyscy używają czitów w złym celu, tak jak nie każdy używa pistoletu do zabijania, niektórzy używają czitów do obrony przed innymi cziterami lub zemsty na nich,  sam kiedyś dużo grałem w różne gry przez neta, i trudno nie zauważyć po jakimś czasie, że ilość oszustów i chamów jest ogromna, i żeby gra z cziterem była "uczciwa" to często samemu trzeba było czitować.

**Comment by mat41997** [comment]
@hawkeye116477 a czy wiesz chociaż czym się zajmuje? zrób jakiś research i wtedy rzucaj oskarżenia..

**Comment by hawkeye116477** [comment]
@mat41997 Ok, sorry, pośpieszyłem się z osądem.
