### ISSUE TITLE
turystyka.wp.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#4057]
Ten sam problem jak w #4044
![image](https://user-images.githubusercontent.com/29756590/31854435-7a3babb0-b699-11e7-9c79-d772d75808f4.png)

**Comment by MajkiIT** [comment]
@HateAds Dziękuję poprawione.

**Comment by HateAds** [comment]
@MajkiIT Bądźmy szczerzy ja dużo nie robię, chciałbym móc bardziej pomóc, ale niestety nie mam wiedzy, jak blokować poszczególne elementy.

**Comment by mat41997** [comment]
@HateAds odpalasz ublocka, klikasz strzykawkę, zaznaczasz element, kopiujesz kod lub klikasz utwórz aby utworzyć tylko dla siebie.

**Comment by HateAds** [comment]
@mat41997 Sorki nie wyraziłem się jasno. Pisząc o braku wiedzy, miałem na myśli reklamy, które generują się losowo jak te na wp i zablokowanie ich tym zwykłym sposobem nic nie da. O to mi chodziło, że nie mam wiedzy, jak blokować takie reklamy.

**Comment by gomoku** [comment]
Nie czaję, przecież wiedzy jest pełno w internecie, są tutoriale do CSS i HTML po polsku, które łatwo znaleźć
