### ISSUE TITLE
niezalezna.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#4058]
To usuwa adblocka ale jest wysyp reklam. Jakieś pomysly?
`
@@||www.adiode.com/http$xmlhttprequest,domain=niezalezna.pl`

**Comment by MajkiIT** [comment]
https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/309

**Comment by xxcriticxx** [comment]
z protectorem bendzie szybcej zrobiona @mat41997 podasz do pingwina?

**Comment by gomoku** [comment]
`niezalezna.pl##script:inject(noeval.js)`

**Comment by xxcriticxx** [comment]
@gomoku dziala thank you
