### ISSUE TITLE
instagram photos

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4059]
blokuje wam photo z instagramu?

https://sportowefakty.wp.pl/pilka-nozna/717636/niedaleko-pada-jablko-od-jabloni-ronaldo-junior-strzelcem-wspanialego-gola

![capture](https://user-images.githubusercontent.com/15007183/31861740-57365fc2-b700-11e7-87f5-8cfe8b657a9a.PNG)

**Comment by HateAds** [comment]
@xxcriticxx Nie
![image](https://user-images.githubusercontent.com/29756590/31904500-b83b04f4-b82b-11e7-8cb8-ea971c615447.png)

**Comment by hawkeye116477** [comment]
Nie

**Comment by xxcriticxx** [comment]
ok czyli ja musze sprawdzic host file
