### ISSUE TITLE
rzeszow-news.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4060]
![2017-10-22 14_20_10-pomoz bezdomnym kotom - rzeszowska mapa pomocy felineuskom](https://user-images.githubusercontent.com/5884000/31861866-cd52f196-b734-11e7-823d-afa151efe649.png)
http://rzeszow-news.pl/pomoz-bezdomnym-kotom-rzeszowska-mapa-pomocy-felineuskom/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
`rzeszow-news.pl##IMG[class^="td-animation-stack-"][src^="http://rzeszow-news.pl/wp-content/uploads/201"]`
