### ISSUE TITLE
ketrzynnews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4062]
![2017-10-22 14_28_31-ketrzynnews pl serwis informacyjny ziemi ketrzynskiej](https://user-images.githubusercontent.com/5884000/31861921-ad29dfc8-b735-11e7-9f4e-d305d4f2d80a.png)

![2017-10-22 14_27_50-ketrzynnews pl serwis informacyjny ziemi ketrzynskiej](https://user-images.githubusercontent.com/5884000/31861923-b19c6738-b735-11e7-9e7a-75b1354929e9.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by gomoku** [comment]
```
||ketrzynnews.pl/wp-content/uploads/2017/01/r_klimatyzacja_internet.jpg
||ketrzynnews.pl/wp-content/uploads/2017/01/r_magtech_internet.jpg
||ketrzynnews.pl/wp-content/uploads/2017/01/r_na%C5%82ysnyk_internet.jpg
||ketrzynnews.pl/wp-content/uploads/2017/01/r_pietras_internet.jpg
||ketrzynnews.pl/wp-content/uploads/2017/08/eldom.jpg
ketrzynnews.pl##.wpb_raw_html
```
