### ISSUE TITLE
ostrowiecnews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4063]
![2017-10-22 14_36_42-strona glowna - ostrowiecnews pl](https://user-images.githubusercontent.com/5884000/31861999-eea7ea7a-b736-11e7-974e-6bd90abe0114.png)

![2017-10-22 14_37_48-sciezki rowerowe na polnej - ostrowiecnews pl](https://user-images.githubusercontent.com/5884000/31862001-f2684e16-b736-11e7-807c-cee7b072bcd2.png)
http://ostrowiecnews.pl/2017/10/21/sciezki-rowerowe-polnej/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by gomoku** [comment]
! panel z reklamami po lewej +
! panel z reklamami po prawej +
! reklama na dole pod artykułem
`ostrowiecnews.pl###text-4, #text-2 > .textwidget > p:nth-of-type(n+2), .text-center`
