### ISSUE TITLE
news.o.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4064]
![2017-10-22 14_47_24-news o pl](https://user-images.githubusercontent.com/5884000/31862080-79c757f2-b738-11e7-9afd-066373dcee25.png)

![2017-10-22 14_51_06-konkurs dom jutra model budownictwa dostepnego - news o pl](https://user-images.githubusercontent.com/5884000/31862082-7dd67788-b738-11e7-8a92-7cb7a208348a.png)
http://news.o.pl/2017/10/21/konkurs-dom-jutra-model-budownictwa-dostepnego-politechnika-warszawska-bgk-nieruchomosci-fundacja-bgk-warszawa/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by gomoku** [comment]
! na listę social oraz popup blocker
! scrollujący popup-stopka na dole newsletter / social
`o.pl###email-bar, #nl-icon`

! na główną listę
! pozioma reklama u góry +
! pionowy blok-panel reklamowy po prawej +
! kwadratowa reklama na dole +
! kwadratowa reklama po prawej u góry
`o.pl###wa, #s-rotator, #server-rectangle, #server-button`

**Comment by hawkeye116477** [comment]
`o.pl##.social.newsletter-col`

**Comment by gomoku** [comment]
Zgadza się, moje przeoczenie.

**Comment by gomoku** [comment]
Zgadza się, moje przeoczenie.
