### ISSUE TITLE
wawalove.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4066]
![2017-10-22 15_08_40-wawalove wiadomosci i informacje kulturalne z warszawy](https://user-images.githubusercontent.com/5884000/31862264-4d184cc2-b73b-11e7-84db-817eec9be2dc.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
U mnie pusto 

https://github.com/MajkiIT/polish-ads-filter/issues/4065

**Comment by xxcriticxx** [comment]
@MajkiIT mam na dole z fresh cookie
