### ISSUE TITLE
krknews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4067]
![2017-10-22 15_17_50-krknews - krakowski serwis informacyjny](https://user-images.githubusercontent.com/5884000/31862338-9bf1a054-b73c-11e7-9ca6-df00ae44912e.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
`krknews.pl##[class*="adxx"]`
