### ISSUE TITLE
bowlingnews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4068]
![2017-10-22 15_27_48-bowling kregielnie pro shop newsy kule strike spare](https://user-images.githubusercontent.com/5884000/31862405-9e920168-b73d-11e7-9fd6-667c48d3ad48.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
`bowlingnews.pl##IMG[class^="alignnone size-"]`
