### ISSUE TITLE
handballnews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4069]
![2017-10-22 15_30_26-strona glowna - pilka reczna - handballnews pl](https://user-images.githubusercontent.com/5884000/31862452-2b0bfb6c-b73e-11e7-974b-32413c980a57.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
`handballnews.pl##A > IMG[src^="http://www.handballnews.pl/image/strona750x500"]`
