### ISSUE TITLE
mmanews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4070]
![2017-10-22 15_35_09-mmanews](https://user-images.githubusercontent.com/5884000/31862491-e63b0edc-b73e-11e7-895f-4621424aacda.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
```
www.mmanews.pl##.clickPanel
||www.mmanews.pl/wp-content/uploads/20*/*/*tapeta$image
mmanews.pl##DIV[class^="rekBlok"]
```
