### ISSUE TITLE
resellernews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4071]
![2017-10-22 15_39_16-news - reseller news - magazyn branzy it - var vendor dystrybutor](https://user-images.githubusercontent.com/5884000/31862502-4017e2ae-b73f-11e7-9a0d-1f9ef6edf4ad.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
`resellernews.pl##A[target="_blank"] > IMG`
