### ISSUE TITLE
marihuana.info.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4073]
![2017-10-22 15_59_29-fabryka najwiekszego producenta marihuany na swiecie - marihuana info pl](https://user-images.githubusercontent.com/5884000/31862675-10762ff8-b742-11e7-8382-c256362e86d4.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by gomoku** [comment]
`www.marihuana.info.pl###header-right-section, #text-5, #text-10, #text-11`
