### ISSUE TITLE
zielonanews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4074]
![2017-10-22 16_07_18-zielona gora - wiadomosci wydarzenia informacje artykuly](https://user-images.githubusercontent.com/5884000/31862733-29eb756e-b743-11e7-8b0c-103e90fe2ae8.png)

![2017-10-22 16_06_44-zielona gora - wiadomosci wydarzenia informacje artykuly](https://user-images.githubusercontent.com/5884000/31862735-2dcde950-b743-11e7-8ed4-e50540ed3c31.png)

![2017-10-22 16_06_58-zielona gora - wiadomosci wydarzenia informacje artykuly](https://user-images.githubusercontent.com/5884000/31862736-2ec8e0da-b743-11e7-8631-3ae5a3c5ca65.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
`zielonanews.pl##A.gofollow > IMG`
