### ISSUE TITLE
faktykonopne.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4075]
![2017-10-22 16_14_47-fakty konopne - najwiekszy portal konopny w polsce](https://user-images.githubusercontent.com/5884000/31862801-490b6db8-b744-11e7-8f8d-3483269238a2.png)

![2017-10-22 16_15_22-fakty konopne - najwiekszy portal konopny w polsce](https://user-images.githubusercontent.com/5884000/31862804-52fb861e-b744-11e7-93fb-e17ccfd14abc.png)

![2017-10-22 16_16_35-knockout palenie marihuany i picie piwa jednoczesnie](https://user-images.githubusercontent.com/5884000/31862808-720e7ce6-b744-11e7-851a-d0c557d63ebb.png)
https://faktykonopne.pl/knockout-palenie-marihuany-i-picie-piwa-jednoczesnie/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
```
faktykonopne.pl##.td-visible-desktop > A > IMG:last-child
faktykonopne.pl##ASIDE.widget_text.td_block_template_14.widget.widget_custom_html
```
