### ISSUE TITLE
cannabisnews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4076]
![2017-10-22 16_19_34-topowe newsy ze swiata marihuany - cannabisnews pl](https://user-images.githubusercontent.com/5884000/31862828-d32d4d22-b744-11e7-99e3-9eb32c153bcd.png)

![2017-10-22 16_18_33-topowe newsy ze swiata marihuany - cannabisnews pl](https://user-images.githubusercontent.com/5884000/31862829-d608c760-b744-11e7-8440-7092c362772e.png)

![2017-10-22 16_20_44-topowe newsy ze swiata marihuany - cannabisnews pl](https://user-images.githubusercontent.com/5884000/31862837-044cce32-b745-11e7-8ccf-193322c1f500.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
```
cannabisnews.pl##[class^="cn-ad-"]
cannabisnews.pl##.td-visible-desktop
cannabisnews.pl##A[target="_blank"] > [src]
cannabisnews.pl##[id^="snp-pop-"]
cannabisnews.pl##.bld-el
```
