### ISSUE TITLE
medycznamarihuana.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4077]
![2017-10-22 16_25_55-zastosowanie konopi w leczeniu raka _ medyczna marihuana serwis edukacyjno inf](https://user-images.githubusercontent.com/5884000/31862874-cfa7fad4-b745-11e7-9088-057d71385cdd.png)
http://medycznamarihuana.pl/konopie-w-procesie-leczenia-nowotworow/

![2017-10-22 16_24_10-medyczna marihuana serwis edukacyjno informacyjny _ znajdziesz tu rzetelne i n](https://user-images.githubusercontent.com/5884000/31862862-8d1ce1ca-b745-11e7-9a1e-b214dccec1c9.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.29
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
`medycznamarihuana.pl##.footer-ad-wrap`
