### ISSUE TITLE
Filtry z atrybutem [hidden] mogą nie działać w nowym uBlocku

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#4080]
Bo to on dodawał ten atrybut w wersji 1.14.16 i starszych.

Teraz widzę cztery takie filtry, trzeba będzie sprawdzić jak działają.
Oczywiście jest możliwe, że tak było na stronie - wtedy jest OK.

https://github.com/gorhill/uBlock/issues/2984#issuecomment-338487727

```
wykop.pl###dyingLinksBox > .dying-links[hidden] ~ .dying-links:last-child:style(display:list-item !important)
wykop.pl###dyingLinksBox > .dying-links[hidden] ~ .dying-links[style="display: list-item;"] ~ .dying-links:style(display: none !important)
www.wp.pl##SECTION[class^="_3"] > DIV[hidden] + DIV[class]
pudelek.pl##LI > DIV[class][hidden] + DIV[class]
```

**Comment by kasper93** [comment]
Te dwa filtry dla wykopu trzeba będzie usunąć, bo nie ma żadnej opcji, żeby to inaczej zrobić. Jedynie przy pomocy skryptu. Trzeba jakoś wykryć, czy element był/jest reklamą i pokazać inne. Jako, że proceduralne filtry nie obsługują `:style` to `[hidden]` było jedyną opcją wykrywania tego.

**Comment by MajkiIT** [comment]
@gwarser @kasper93 Dzięki za info. Usunąłem hide z wp i pudelka. Co do wykopu to musimy się zastanowić.

**Comment by gwarser** [comment]
@MajkiIT a tak w ogóle, to czemu te filtry są w głównej liście, a nie w tej dla uBlocka? Przecież to nie działało w ABP. 
Jesta cała masa filtrów z `:has`, a ABP obsługuje chyba tylko `:-abp-has()`?
Daliście sobie spokój z ABP?

**Comment by mat41997** [comment]
@gwarser ABP sprzedaje pozycje na wh.

**Comment by gwarser** [comment]
Przeskanowałem grepem jakieś 300 list z filterlists.com, i tylko my używamy [hidden] :)

**Comment by MajkiIT** [comment]
@gwarser nie coś ty nie daliśmy sobie spokoju. Przy najbliższej możliwości przeniosę to. filtrów ubo. Z tego co testowaliśmy z @F4z te reguły nie psuły nic na stronach. Ale jak mówiłem przeniosę to.

**Comment by kasper93** [comment]
@MajkiIT: Filtry używające `matches-css` są bardzo wolne. Ogólnie wymagają przeliczania layouty, bo prosimy przeglądarkę o prawdziwy wymiar po kompozycji css. Na stronie takie jak wp.pl znacząco zmniejsza to responsywność strony. 

Czy te dwa filtry mogłyby być zmienione na statyczne? Czy są na pewno potrzebne?
```
www.wp.pl##div[class]:matches-css(width: 309px):matches-css(height: 182px)
www.wp.pl##div[class]:matches-css(max-width: 300px):matches-css(max-height: 250px)
```

WP jest ciężkim przypadkiem bo robią pełno updajtów DOMa co powoduje ponowne przeliczanie tych filtrów.

**Comment by F4z** [comment]
> Czy te dwa filtry mogłyby być zmienione na statyczne? Czy są na pewno potrzebne? Może je uszczegółowić? Bo odpalanie matches-css dla każdego div[class] to samobójstwo.

Jeśli dobrze widzę, to w tej chwili ta druga reguła ukrywa 3 reklamy.
Ciężko tam coś wymyślić, bo te klasy są "losowe".
Jest jakiś sposób żebym mógł sobie sprawdzić/przetestować jaki wpływ na stronę mają reguły używające `matches-css`?
Reguły z `has/if` będą "szybsze"?
Na przykład:
`www.wp.pl##div[class]:if(>div[class] > div[class]:has-text(REKLAMA):if-not(>*))`

Ktoś ma jakieś inne pomysły albo wskazówki?

**Comment by kasper93** [comment]
Jeżeli chodzi o zmierzenie wpływu to najlepiej odpalić profiler i sprawdzić dokładnie. Na Firefoxie https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler

Ten pierwszy filtr sprawdza width/height co powoduje przeliczenie layout. max-width/max-height nie powoduje, więc tak na prawdę głównym winowajcą jest ten pierwszy filtr. Ogólnie chodzi o to, że po ukryciu jednego elementu, szerokość każdego diva mogła się zmienić więc jest to na nowo przeliczane.

`has/if` w tym przypadku pewnie będzie szybsze. Ale trzeba zmierzyć dla pewności. `has/if` też musi każdy element sprawdzić.

Tak przy okazji to mam wrażenie, że te dwa filtry za dużo ukrywają. Spojrzę też na to, bo widzę, że wp dość nieprzyjemne jest.

**Comment by kasper93** [comment]
@F4z: 

Tak ten filtr będzie dużo lepszy. Dodaj jeszcze `:first-child`, żeby tylko pierwsze dzieci sprawdzać.
```
www.wp.pl##div[class]:if(>div[class]:first-child:has-text(REKLAMA):if-not(>*))
```

**Comment by F4z** [comment]
Ok, dzięki za odpowiedź.
Tak, jest więcej reguł z `matches-css`, ale na razie usunąłem te dwie wyżej wymienione i dodałem zaproponowaną przez Ciebie regułę z `if.`
Z tego co widzę, to teraz zamiast reklam jest napis "WP REKLAMA".
Potem postaram się to ukryć oraz sprawdzić też inne reguły z `matches-css` i ewentualnie zastąpić je czymś wydajniejszym (co pewnie trochę czasu mi zajmie).

Oczywiście wszystkie propozycje i pomysły nadal mile widziane :)

Dzięki za pomoc.

**Comment by kasper93** [comment]
Można jeszcze wywalić, bo on nic nie łapie. Przynajmniej ja nie widzę.
```
wp.pl##div[class^="_"]:matches-css(min-width: 300px):matches-css(background-color: rgba)
```

> Z tego co widzę, to teraz zamiast reklam jest napis "WP REKLAMA".

Tak czy inaczej zostaje tam puste miejsce, to nie wiem czy ten znak wodny nie warto po prostu zostawić, żeby nie komplikować zbytnio filtrów. 

Dla tej reklamy na górze. 
```
www.wp.pl##div[style="position: relative; display: block; width: 100%; height: 60px; overflow: hidden; z-index: 310;"]
```

**Comment by HateAds** [comment]
Ja osobiście wolę puste pola niż napis, ale to tylko moje zdanie.
Co do reguły, którą podałeś na reklamę na samej górze, to ona coś dziwnie działa. Reklama chowa się i pojawia się co chwilę, a jak już się schowa to jak zjadę myszką na dół i dam znowu do góry to powraca na kilka sekund.

**Comment by kasper93** [comment]
> Co do wykopu to musimy się zastanowić.

@MajkiIT: W przypadku wykopu pierwszy link w `#dyingLinksBox` jest *zawsze* reklamą. Więc możemy trochę oszukać i zamiast używać `[hidden]` użyć `first-child`. Te filtry działają tak jak wcześniej: 

```
wykop.pl###dyingLinksBox > .dying-links:first-child ~ .dying-links:last-child:style(display:list-item !important)
wykop.pl###dyingLinksBox > .dying-links:first-child ~ .dying-links[style="display: list-item;"] ~ .dying-links:style(display: none !important)
```

**Comment by MajkiIT** [comment]
@xxcriticxx zerknij proszę u siebie a ja zerknę u mnie

**Comment by xxcriticxx** [comment]
@MajkiIT naco mam lookac?

**Comment by MajkiIT** [comment]
@kasper93 dziękuję

**Comment by kasper93** [comment]
@MajkiIT:

Wrzuć jeszcze to do filtrów, to będzie lepiej działało, bez migotania.

```
wykop.pl###dyingLinksBox > .dying-links:first-child
```
