### ISSUE TITLE
czat.wp.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4082]
![2017-10-23 11_46_20-czat - platforma nowych znajomosci - wp pl](https://user-images.githubusercontent.com/5884000/31882662-d10ac62a-b7e7-11e7-8bf1-2b1dd886f23f.png)

![2017-10-23 11_48_32-czat - platforma nowych znajomosci - wp pl](https://user-images.githubusercontent.com/5884000/31882763-2018cafa-b7e8-11e7-93ab-7c9fa749ae8a.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.31
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
@mat41997 
tak jest ok?
`czat.wp.pl##[id*="adv"]`

**Comment by mat41997** [comment]
@MajkiIT nope
![2017-10-23 12_41_29-czat - platforma nowych znajomosci - wp pl](https://user-images.githubusercontent.com/5884000/31885094-a16b12b4-b7ef-11e7-9f64-25d99b8f090b.png)

**Comment by gomoku** [comment]
Zaobserwowałem następujące zjawiska

na Firefoxie + uBO:
- a) reklam w ogóle nie ma, przy włączonej polskiej liście + kilku innych (w tym Fanboy’s Enhanced Tracking List)

na Operze + uBO:
- b) przy wyłączonych wszystkich listach i dodanym samym filtrze `czat.wp.pl##[id*="adv"]` reklam nie ma
- c) przy włączonej tylko polskiej liście, która zawiera taki sam filtr, reklamy dalej są
- d) dodanie tych reguł "naprawia" polską listę:
`@@||wp.hit.gemius.pl/gdejs/xgde.js$script,domain=czat.wp.pl`
`@@||wp.hit.gemius.pl/gplayer.js$script,domain=czat.wp.pl`
powoduje, że reklam nie ma (chociaż czasem może jako skutek uboczny wyskoczyć pojedyncza reklama-popup na cały ekran jak tu: https://s3.dodajfote.pl/2017/10/23/reklamapopup045f16f1f392261d.png)

- e) gdy włączymy listę Fanboy’s Enhanced Tracking List reklamy znowu się pojawią
- f) dodanie tej reguły "naprawia" powyższą listę Fanboy's:
`@@||www.googletagservices.com/tag/js/gpt.js$script,domain=czat.wp.pl`

Nie wiem czy to jakieś filtry się gryzą, czy WP wdrożyło jakiś nowy mechanizm zabezpieczający...

**Comment by MajkiIT** [comment]
@gomoku Dzięki za ianalizę.
