### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4083]
![2017-10-23 14_40_56-mahou sensei negima anime final odcinek_ 1 - shinden](https://user-images.githubusercontent.com/5884000/31889551-88345632-b800-11e7-9760-53087b47006a.png)
https://shinden.pl/external-video/50393-black-clover-tv/view/161080

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.31
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
U mnie jest ok. @hawkeye116477 @xxcriticxx zerkniecie?

**Comment by xxcriticxx** [comment]
u minie strona dziala ok

**Comment by xxcriticxx** [comment]
@hawkeye116477 cookie mam na dole

![capture](https://user-images.githubusercontent.com/15007183/31902684-b145351c-b7f3-11e7-81fa-52f817b76143.PNG)

**Comment by gomoku** [comment]
(F+O)+uBO:
- a) tego co w pierwszym poście nie sprawdzę, bo nie mam tam konta, a pisze, że trzeba się zalogować, żeby kontynuować
- b) komunikatu o ciasteczkach nie mam
- c) natomiast statyczny przycisk Facebook po lewej na dole na listę social: `##.przycisk.btnfa`

**Comment by hawkeye116477** [comment]
@MajkiIT Jest ok. Tylko przycisk social trzeba schować.
@xxcriticxx Nie avastuj 😄 .

**Comment by xxcriticxx** [comment]
@hawkeye116477  ta nasza lista cos wolno lapie zrobilem tobie zdjecie zebys widzial sam

**Comment by hawkeye116477** [comment]
@xxcriticxx U mnie jest ok.
A jak dodasz te 2 reguły:
```
shinden.pl#@#:not(input)[id*="cookie"]
shinden.pl#@#[id*="cookie-"]
```
to coś to zmienia?

**Comment by xxcriticxx** [comment]
@hawkeye116477 check czy masz 

`##.pasek`

**Comment by hawkeye116477** [comment]
@xxcriticxx Pasek to ten z ikoną Facebooka i innymi elementami.
A `###cookie-bar:not(body):not(html)` jest już u nas na liście i pokazuje się w loggerze.
U mnie na WF jest git.

**Comment by xxcriticxx** [comment]
@hawkeye116477 to git
