### ISSUE TITLE
polscygracze.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4086]
![2017-10-23 21_30_03-sivir z neo pax i epickie kapsuly](https://user-images.githubusercontent.com/5884000/31909163-77c2ff22-b839-11e7-9898-02bbbea22024.png)
https://polscygracze.pl/sivir-neo-pax-epickie-kapsuly/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.31
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
`polscygracze.pl##.gridlove-sidebar > .LfUW8dL1Hl-widget.gridlove-box.widget`
