### ISSUE TITLE
NSFW polskie-aktorki-porno.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4088]
popup po odpaleniu filmu

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.31
chrome 62.0.3202.62
win10 x64

**Comment by xxcriticxx** [comment]
@mat41997 wszystkie strony porno i inne glupoty dostaja tag NSFW (not safe for work)

**Comment by gomoku** [comment]
O jaki popup ci chodzi, bo jeśli o ten z anty-adblockiem to było to już zgłaszane w tym wątku https://github.com/MajkiIT/polish-ads-filter/issues/3141 i zostało zamknięte więc, nie wiem czy a) miało to być blokowane też na polskiej liście, czy b) uznano, że wystarczy, że jest blokowane na https://xuhaiyang1234.gitlab.io/AAK-Cont/, ale przyjmując, że b) i jednocześnie biorąc pod uwagę, że ty korzystasz z https://jspenguin2017.github.io/uBlockProtector/ to zdaje się, że powienienieś to zgłosić tam.
