### ISSUE TITLE
NSFW woor.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4089]
![2017-10-23 22_36_10-polskie sex filmy sex filmy i filmiki](https://user-images.githubusercontent.com/5884000/31912027-efd427b2-b842-11e7-817c-a55873a8c180.png)
``https://www.woor.pl/polskie/``

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.31
chrome 62.0.3202.62
win10 x64

**Comment by gomoku** [comment]
`www.woor.pl##.main > p:nth-of-type(1)`
