### ISSUE TITLE
NSFW sexrura.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4090]
![2017-10-23 22_41_13-ruchanie polskiej aktorki porno natalia starr - sexrura pl](https://user-images.githubusercontent.com/5884000/31912467-47dda838-b844-11e7-95d7-9c5e3d11d3e1.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.31
chrome 62.0.3202.62
win10 x64

**Comment by gomoku** [comment]
Ale musisz podać jakiś konkretny link bo gdy kliknąć na jakikolwiek film to otwiera się film z innej porno tuby.

**Comment by mat41997** [comment]
@gomoku również jakikolwiek film
``http://www.sexrura.pl/film-porno/662891/latwa-blondi-799267``

**Comment by gomoku** [comment]
`www.sexrura.pl##.bimg-sidebar, .sidebar-img-container`, 

- a) przy okazji a z ciekawości zapytam jak na te filmy wchodzisz, bo z głównej http://www.sexrura.pl nie wchodzą filmy first-party, bo gdy się kliknie na jakikolwiek film to się otwiera film na innej porno tubie

**Comment by mat41997** [comment]
@gomoku tylko wybrane filmy ze strony głównej działają.
po włączeniu jakiegokolwiek filmu, działającego lub nie. po jego bokach są reklamy które zostały zaznaczone u mnie różowym.

**Comment by gomoku** [comment]
Skoro tylko wybrane filmy, to dlaczego tego nie napisałeś w pierwszym poście albo nie podałeś przykładowego linka.

**Comment by mat41997** [comment]
wtedy jeszcze o tym nie wiedziałem.. dopiero musiałem chwile poświęcić żeby się tego domyślić.

**Comment by gomoku** [comment]
No ok, rozumiem, że sam nie widziałeś, zdarza się każdemu, natomiast drugiego zdania nie bardzo rozumiem, czy mógłbyś wyjaśnić...

**Comment by mat41997** [comment]
@gomoku tzn. że twoja spina jest zupełnie bez znaczenia dla rozwiązania tego problemu.

**Comment by gomoku** [comment]
Nie bardzo rozumiem, a na podstawie czego twierdzisz, że się spinam? Bo ja tylko normalnie dyskutuję żeby wyjaśnić kwestie.

**Comment by mat41997** [comment]
na podstawie mojej interpretacji formy twojej wypowiedzi. 
to jak się wypowiadasz jasno stawia sprawę ( szukasz zaczepki )
dobra, wszystko co ważne zostało już wyjaśnione. 
teraz niech ktoś naprawi i zamknę ten temat.

**Comment by gomoku** [comment]
No właśnie o tą twoją interpretację pytałem, na czym ona polega...? 
Niby w jaki sposób się spinam i szukam zaczepki? 
Bo z tego co widzę, to ty mnie zaczepiasz...

**Comment by mat41997** [comment]
@gomoku polega ona na technicznej analizie.
"No ok, rozumiem, że sam nie wiedziałeś, zdarza się każdemu," - tutaj obrażasz mnie aby ukryć swój błąd
"natomiast 3-go i 4-go zdania nie bardzo rozumiem, czy mógłbyś wyjaśnić..." - tutaj robisz ze mnie głupka, udając że nie wiesz o co chodzi bo nie chcesz przyznać się do swojego błędu.

"Bo z tego co widzę, to ty mnie zaczepiasz..." - tutaj szukasz powodu do oskarżenia mnie.

ja staram się w miarę wyprostować sytuację.

prosiłem byśmy skończyli tą rozmowę, to nie jest odpowiednie miejsce.

**Comment by gomoku** [comment]
> "No ok, rozumiem, że sam nie wiedziałeś, zdarza się każdemu," - tutaj obrażasz mnie aby ukryć swój błąd

moje intencje, myślenie i zamiary były zupełnie odwrotne, napisałem tak dokładnie po to żebyś nie poczuł się winny, bo przecież każdemu się to zdarza (nawet mi)...aż dziw mnie bierze, że ktoś/ty mógł to odebrać/zinterpretować całkowicie na odwrót i uznać pomoc za atak...

> aby ukryć swój błąd

jaki błąd? Bo to znowu ogólnik, i nie kumam, więc dopytuję, ale tak na serio, a nie żeby robić głupka czy coś...

> "natomiast 3-go i 4-go zdania nie bardzo rozumiem, czy mógłbyś wyjaśnić..." - tutaj robisz ze mnie głupka udając że nie wiesz o co chodzi, bo nie chcesz przyznać się do swojego błędu.

Nie, po prostu nie rozumiem tego "reklamy wyświetlają się obok działających i nie działających filmów.", nie wiem o które filmy ci chodziło, które to działające, a które niedziałające, więc zwyczajnie dopytałem...

> "Bo z tego co widzę, to ty mnie zaczepiasz..." - tutaj szukasz powodu do oskarżenia mnie.

To ty mnie dopiero co oskarżałeś o spinanie się i szukanie zaczepki, a teraz jeszcze oskarżasz mnie o oskarżanie ciebie...dobre sobie, to już masło maślane produkujesz...ale to tak ogólnikowo się odniosłem, a przyjmując to twoje oskarżenie mnie o oskarżanie ciebie poważnie i odnosząc się do niego bezpośrednio, to ty jeśli ty mi coś zarzucałeś personalnie i to w dodatku ogólnikowo bez podania konkretów, gdy ja prowadziłem dyskusję trzymającą się wątku, to kto tu kogo zaczepiał...

> ja staram się w miarę wyprostować sytuację.

Którą sam skomplikowałeś...

> prosiłem byśmy skończyli tą rozmowę.

Nie ma to jak kogoś oskarżyć i pomówić ogólnikami, a gdy ten ktoś się z tym nie zgadza bo nie wie o co jest tak naprawdę oskarżany, więc poprosi grzecznie o konkrety/argumenty żeby mógł się odnieść, to zamiast odpowiedzieć i wyjaśnić to kończyć niewyjaśnioną dyskusję pełną pomówień...gdybyśmy zakończyli dyskusję w połowie, bez wyjaśniania, tak jak tego chciałeś, to jeszcze ktoś by uwierzył ci w te twoje błędne interpretacje, że ja cię obraziłem...kiedy ja a tak naprawdę chciałem pomóc, no sorry, ale dziwisz się, że cię za język pociągnąłem, bo po prostu nie nie pozwolę sobie na to, żeby ktoś mi coś imputował...

![](https://yt3.ggpht.com/-rXUumPbv_Qw/AAAAAAAAAAI/AAAAAAAAAAA/e3j7Oh-wv44/s48-c-k-no-mo-rj-c0xffffff/photo.jpg)

**Comment by mat41997** [comment]
"aż dziw mnie bierze, że ktoś/ty mógł to odebrać/zinterpretować całkowicie na odwrót" - następnym raz nie pisz tak dwuznacznie, bo jeszcze ktoś inny wpadnie w błąd i nawiąże z tobą toksyczne relacje.

"uznać pomoc za atak..." - lepiej nie pomagać komuś kto pomocy nie chce lub ewidentnie o nią nie prosił. to również się wiąże z toksyczną relacja.

"jaki błąd? Bo to znowu ogólnik" - moim celem było użyć ogólniak, ma to zachęcić do rozważań.

"a nie żeby robić głupka" - głupka, nie. ale podważyć mój autorytet, moją osobę już tak.

"nie wiem o które filmy ci chodziło, które to działające, a które niedziałające, więc zwyczajnie dopytałem..." - w skrócie: o wszystkie. ( proszę tego nie nadinterpretowywać )

"To ty mnie dopiero co oskarżałeś o spinanie się i szukanie zaczepki," - o nic nie oskarżałem, to była interpretacja. proszę czytaj uważniej co piszę.

"to w dodatku ogólnikowo bez podania konkretów" - tak jak już pisałem, miało to zachęcić do dalszych rozważań.

"gdy ja prowadziłem dyskusję trzymającą się wątku" - obecnie prowadzimy ustalenia mające na celu poprawę naszych relacji by móc w pełni sił powrócić do głównego wątku bez popełniania kompromisów.

"Którą sam skomplikowałeś..." - oczywiście, musiałem wejść w pewne niuanse by dojść do konsensusu.

"Nie odpowiadając na moje pytanie o co tak naprawdę jestem oskarżany" - jak już pisałem, ja cie o nic nie oskarżam. dlatego też dobrze by było zakończyć już tą rozmowę.
