### ISSUE TITLE
NSFW gej-porno.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4091]
![2017-10-23 22_56_10-polskie chlopaki jada sie na kanapie](https://user-images.githubusercontent.com/5884000/31912875-a43f26fa-b845-11e7-88ce-3226c8c06f32.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.31
chrome 62.0.3202.62
win10 x64

**Comment by gomoku** [comment]
U mnie tego nie da, podaj konkretny link, przy okazji jest tam anty-adblock ten sam co tu https://github.com/MajkiIT/polish-ads-filter/issues/4088#issuecomment-338952682

**Comment by mat41997** [comment]
@gomoku jaki film
``https://gej-porno.pl/dwoch-zolnierzy-oddaje-sie-analnej-przyjemnosci,5598``

**Comment by gomoku** [comment]
`||gej-porno.pl/images/bannery/ali-sex-banner.jpg$image`
