### ISSUE TITLE
komorkomania.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4094]
![2017-10-24 10_31_08-gadzetomania pl - informacje komentarze opinie](https://user-images.githubusercontent.com/5884000/31932551-dd81fea4-b8a6-11e7-9d56-4ad793741387.png)

podobna reklama na wszystkich innych podserwisach

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.34
chrome 62.0.3202.62
win10 x64

**Comment by hawkeye116477** [comment]
A u mnie taka fajna reklama nagle wyskoczyła :smile:.
https://komorkomania.pl/13819,problemy-z-budzikiem-w-iphonie
![screenshot_20171024_143021](https://user-images.githubusercontent.com/19818572/31943157-0e25740c-b8c8-11e7-877d-8123337bfb29.png)
