### ISSUE TITLE
cda.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4097]
![2017-10-24 16_44_20-lochy i smoki 2000 pl - wideo w cda pl](https://user-images.githubusercontent.com/5884000/31949953-d6ba694c-b8da-11e7-9ed2-91db910d8168.png)
https://www.cda.pl/video/12851785

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.34
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
@mat41997 @xxcriticxx @hawkeye116477 
To niby reklama lokalna cda blokujemy>?

**Comment by mat41997** [comment]
niby nie, ale wg. mnie nie jest to odpowiednia sekcja na takie "linki".

**Comment by MajkiIT** [comment]
@mat41997 ok to już blokujemy. Dzięki

**Comment by mat41997** [comment]
opcjonalnie możesz podzielić listę filtrów na stopnie agresywności blokowania reklam.
