### ISSUE TITLE
błąd na ulubionej poczcie

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#4099]
Macie tutaj reklamę?

http://www.wp.pl/wylogowano_z_poczty.html?pfba=1507320538.305&advdyn=1

**Comment by mat41997** [comment]
pewnie
![2017-10-24 20_34_30-wylogowano z poczty](https://user-images.githubusercontent.com/5884000/31961348-c4cfdae4-b8fa-11e7-9ce1-73d7dd5b6478.png)

p.s moją ulubioną pocztą jest gmail

**Comment by MajkiIT** [comment]
chrome?

**Comment by mat41997** [comment]
ta sama konfiguracja co zawsze

**Comment by xxcriticxx** [comment]
tak na chromie 

![capture](https://user-images.githubusercontent.com/15007183/31962020-61501248-b8ca-11e7-97da-010b907b89ee.PNG)

**Comment by MajkiIT** [comment]
sprawdzicie??
`www.wp.pl##A[class][href*=".wp.pl/"] IMG[class][src^="https://v.wpimg.pl/"]`

**Comment by xxcriticxx** [comment]
@MajkiIT u mnie to nic nie zmienia mam dalej reklamie

**Comment by xxcriticxx** [comment]
cookies

`###WP-cookie-info`

![capture](https://user-images.githubusercontent.com/15007183/32351086-a856fb00-bff2-11e7-85ad-fc6327cf3b3b.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Ja mam lepsze rozwiązanie -> `||a.wpimg.pl/a/i/stg/wpjslib-chunk-cookie-info.js$script` 😄 .

**Comment by MajkiIT** [comment]
@mat41997 potwierdź proszę, że już u ciebnie jest ok.
