### ISSUE TITLE
portal.abczdrowie.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4101]
puste okna po reklamach
![2017-10-24 22_32_10-przesadzanie z aspiryna moze skonczyc sie ciezkim przebiegiem grypy wideo _ wp](https://user-images.githubusercontent.com/5884000/31966518-3b6e4d88-b90b-11e7-8bcd-8fa26df7e364.png)
https://portal.abczdrowie.pl/przesadzanie-z-aspiryna-moze-skonczyc-sie-ciezkim-przebiegiem-grypy

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.34
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
nadal to masz? U mnie czysto

**Comment by xxcriticxx** [comment]
czysto jestem na chromie

**Comment by mat41997** [comment]
mam
![2017-10-25 13_06_35-strefa kobiety _ wp abczdrowie](https://user-images.githubusercontent.com/5884000/31995815-4a2c7c34-b986-11e7-8b05-7220506438ac.png)

![2017-10-25 13_07_07-strefa kobiety _ wp abczdrowie](https://user-images.githubusercontent.com/5884000/31995819-4f293e70-b986-11e7-9509-07e00aaafd04.png)
https://portal.abczdrowie.pl/strefa-kobiety

**Comment by HateAds** [comment]
U mnie jest 
![image](https://user-images.githubusercontent.com/29756590/32009426-6131ee90-b9af-11e7-9479-7479673b9da3.png)
I są 2 wersje tej strony. ( To samo co z https://parenting.pl/ kiedyś było ) Zwróćcie uwagę na samą górę strony. Raz jest biała, a innym razem czerwona. Na tej czerwonej mam puste boxy.

**Comment by MajkiIT** [comment]
@F4z zerkniesz swoim okiem?

**Comment by MajkiIT** [comment]
@mat41997 update i sprawdź proszę.

**Comment by mat41997** [comment]
![2017-10-27 11_00_43-forum psychologia _ abczdrowie pl](https://user-images.githubusercontent.com/5884000/32096243-27d1fdcc-bb06-11e7-996b-98f606a984e8.png)

![2017-10-27 11_00_52-forum psychologia _ abczdrowie pl](https://user-images.githubusercontent.com/5884000/32096248-2b9ed6f0-bb06-11e7-9039-c5837f366f05.png)
https://forum.abczdrowie.pl/
