### ISSUE TITLE
spigot.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4109]
![2017-10-25 00_33_08-forum - spigot pl - download spigot _ polskie centrum spigot](https://user-images.githubusercontent.com/5884000/31971436-221daac0-b91c-11e7-91da-d9f7d62b4b0d.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.34
chrome 62.0.3202.62
win10 x64

**Comment by xxcriticxx** [comment]
@mat41997 to `PARTNERZY` a nie reklamy

**Comment by xxcriticxx** [comment]
@mat41997 tak dokładnie parterów i sponsorów ni blokujemy chyba ze mruga i się obkreca

**Comment by mat41997** [comment]
@xxcriticxx tak więc odblokujcie co zablokowaliście : )

**Comment by xxcriticxx** [comment]
@mat41997 jutro Ok? Teraz komputer składam bo twardy dysk poszedł do Abrahama.

**Comment by mat41997** [comment]
a ja na swojej stronie zrobię reklamy i dam tabelkę partnerzy : ))
a wy już nie blokujcie tych partnerów na tabletowo.

**Comment by xxcriticxx** [comment]
Tam for Sure blokujemy bo czytają co podajesz tutaj

**Comment by mat41997** [comment]
nie rozumiem

**Comment by xxcriticxx** [comment]
Zabawa w kotka i myszkę

**Comment by MajkiIT** [comment]
`spigot.pl##.ipsBox.ipsWidget_vertical.ipsWidget:nth-of-type(1)`
