### ISSUE TITLE
naekranie.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#4110]
Podobno przez filtry social nie można uruchomić filmów zerkniecie?
@xxcriticxx @gomoku @hawkeye116477 

https://naekranie.pl/aktualnosci/37-zwiastunow-do-obejrzenia-w-ten-weekend-lista-obowiazkowa-2490305

**Comment by gomoku** [comment]
Mógłbym zerknąć, jeśli ty mógłbyś najpierw zerknąć i łaskawie odpisać tu https://github.com/MajkiIT/polish-ads-filter/pull/3953, dopóki ty nie zerkniesz, ja też nie zerknę.

**Comment by MajkiIT** [comment]
@gomoku powiem szczerze, że masz takie problemy do jakich dorosłeś. Nie chcesz to nie rób, a ja nie mam zamiaru ciągnąc tego tematu., bo to będzie wałkowanie w kółko tego samego.

**Comment by MajkiIT** [comment]
@hawkeye116477 wyślij mi proszę maila na `errors@certyficate.it`

**Comment by hawkeye116477** [comment]
Tak, zgadza się, problem powoduje filtr `pl##.youtube`.

**Comment by xxcriticxx** [comment]
@MajkiIT tak dokladnie filmy znikaja jak wlonczysz filtry social

**Comment by hawkeye116477** [comment]
Problem powoduje reguła `pl##.youtube`.

**Comment by xxcriticxx** [comment]
rozwiazanie whitelist yt na naekranie wystarczy?

**Comment by gomoku** [comment]
@MajkiIT jeśli chcesz robić smród to lepiej tu: https://github.com/MajkiIT/polish-ads-filter/pull/3953 i tam właśnie ci odpisałem, tylko zastanawiam się czy odpiszesz, czy umiesz tylko pomówić a potem ignorować...
