### ISSUE TITLE
purepc.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4114]
![2017-10-25 13_22_35-jak to jest z intel z270 i coffee lake_ moglo dzialac a nie dziala _ purepc pl](https://user-images.githubusercontent.com/5884000/31996157-a8808522-b987-11e7-8155-9066c9f85b3f.png)
https://www.purepc.pl/felietony/jak_to_jest_z_intel_z270_i_coffee_lake_moglo_dzialac_a_nie_dziala

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.35
chrome 62.0.3202.62
win10 x64

**Comment by hawkeye116477** [comment]
`www.purepc.pl##a[href^="https://www.purepc.pl/r3dir.php"]`

**Comment by MajkiIT** [comment]
@mat41997 Dzięki za wszystkie zgłoszenia.
@hawkeye116477 będzie zaraz zmieniona.
