### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by Opera48** [MajkiIT/polish-ads-filter#4129]
Reklama wot na bokach w Operze (i chyba w chrome bez uBO Extra też) tylko w działach, opisach programów, wyszukiwarce.
Brak na głównej i w artykułach - narazie.

### Twoja konfiguracja
**Przeglądarka:** Opera 48

**Operating system:** Windows 7

**Blocker:** uBlock Origin 1.14.8

**Używane filtry:**
* standardowe oraz:

  1. AAK-Cont Filters For uBlock Origin
  2. Adblock Warning Removal List
  3. Fanboy’s Cookiemonster List

### Zrzut ekranu

![dział programy](https://user-images.githubusercontent.com/33114475/32038466-5bb78b66-ba2a-11e7-9e7f-37042cef604b.png "dział programy")
![image](https://user-images.githubusercontent.com/33114475/32038493-7f7e84d2-ba2a-11e7-8519-8578927afeb5.png "strona pobierania Opery")

```
https://www.dobreprogramy.pl/Programy,Windows.html
https://www.dobreprogramy.pl/Opera,Program,Windows,12614.html
```

**Comment by gzenio22** [comment]
ummm to jest dziwne ale nawet ciasteczka mi wyskakuja

**Comment by blocker999** [comment]
Znowu  promują jakąś gierke

**Comment by mat41997** [comment]
nwm. ja tam nie mam żadnych reklam ^^

**Comment by xxcriticxx** [comment]
@Opera48 polskie listry masz?

**Comment by Opera48** [comment]
Mam oba aktywne i nawet dodałam te do ciasteczek pod polskie strony.

> ***mat41997** commented:*
> nwm. ja tam nie mam żadnych reklam ^^

Bo się zalogowałeś i masz klasyczny motyw zielony.

**Comment by hawkeye116477** [comment]
Te ciastka też mam tak jak wy, ale reguła na nie jest już na liście, więc raczej jest to bug uBlocka dla Chromium, bo na Waterfoxie jest wszystko ok. Nawet próbowałem dodać taką regułę i komunikat nadal jest, więc to bug, z tym tłem pewnie tak samo.

**Comment by MajkiIT** [comment]
@Opera48 update i sprawdz

**Comment by hawkeye116477** [comment]
@MajkiIT No i teraz jest git, nawet komunikat ciasteczkowy zniknął 😄 .

**Comment by MajkiIT** [comment]
@hawkeye116477 no to gitara

**Comment by Opera48** [comment]
Zadziało po ponownym uruchomieniu Opery (aktualizacja / czyszczenie pamięci podręcznej jakby strajkowało w uBO dla Opery).
