### ISSUE TITLE
geekweek.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4130]
![2017-10-26 17_31_26-to nie bajka ale skandynawskie zielone dachy - geekweek pl - wszystko o nowych](https://user-images.githubusercontent.com/5884000/32062008-889a19d4-ba73-11e7-8ed8-7ebd66025884.png)
http://www.geekweek.pl/galerie/4771/to-nie-bajka-ale-skandynawskie-zielone-dachy

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.38
chrome 62.0.3202.62
win10 x64

**Comment by xxcriticxx** [comment]
@mat41997 ile razy to bendziesz zmienial ?

**Comment by mat41997** [comment]
@xxcriticxx co takiego?

**Comment by xxcriticxx** [comment]
twojapogoda i geekweek

**Comment by mat41997** [comment]
nadal nie rozumiem

**Comment by xxcriticxx** [comment]
obrazki chyba pomieszales

**Comment by mat41997** [comment]
@xxcriticxx ale tylko raz, nie tutaj i na dodatek specjalnie.

**Comment by xxcriticxx** [comment]
@mat41997 ok
