### ISSUE TITLE
smartage.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4132]
![2017-10-26 17_48_01-smartage pl - portal ludzi ciekawych swiata](https://user-images.githubusercontent.com/5884000/32062831-ede12240-ba75-11e7-87b5-a55391c33530.png)

![2017-10-26 17_49_47-polestar 1 - luksusowa hybryda od volvo - smartage pl](https://user-images.githubusercontent.com/5884000/32062895-1ce37660-ba76-11e7-9b10-730f7b4edbfd.png)
http://www.smartage.pl/polestar-1-luksusowa-hybryda-od-volvo/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.38
chrome 62.0.3202.62
win10 x64

**Comment by gzenio22** [comment]
smartage.pl###text-17
smartage.pl###media_image-3
smartage.pl###custom_html-2
