### ISSUE TITLE
horizongamer.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4133]
![2017-10-26 17_52_29-horizon gamer](https://user-images.githubusercontent.com/5884000/32063043-80d2a3b2-ba76-11e7-9798-0253f421fdaa.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.38
chrome 62.0.3202.62
win10 x64

**Comment by hawkeye116477** [comment]
Social -> `horizongamer.pl##.widgettitle:has-text(Dołącz do nas na Facebooku)`
A reklamy zostawiam dla innych 😄 .

**Comment by gzenio22** [comment]
horizongamer.pl###custom_html-2
