### ISSUE TITLE
Filtering using ###ads

### ISSUE THREAD

**Issue by Firminator** [MajkiIT/polish-ads-filter#4137]
Breaks https://android.izzysoft.de/help.php?topic=modwarnings
![screenshot from 2017-10-26 12-53-39](https://user-images.githubusercontent.com/12078737/32066229-17e6c49c-ba4d-11e7-86f3-e511c1cba434.png)

See also (but using ###popup): https://github.com/farrokhi/adblock-iran/issues/4

**Comment by MajkiIT** [comment]
@Firminator thanks
