### ISSUE TITLE
studentnews.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#4138]
Co prawda na głównej niema ale na tej podstronie są reklamy: https://sklepy.muzyczne.studentnews.pl/serwis.php?s=1877&pok=45932&c1=3&c1m=188

**Comment by hawkeye116477** [comment]
Social -> `sklepy.muzyczne.studentnews.pl##.menulnk:has-text(facebook)`

**Comment by MajkiIT** [comment]
`studentnews.pl##.s_dodatkowa`
