### ISSUE TITLE
katalog.wp.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4139]
![2017-10-26 21_04_53-edukacja - katalog - wp pl](https://user-images.githubusercontent.com/5884000/32072028-885bff5a-ba91-11e7-8b23-3cc6a930d316.png)
http://katalog.wp.pl/edukacja/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.38
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
@mat41997 dzięki
