### ISSUE TITLE
tabletowo.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4140]
![2017-10-16 03_19_16-tabletowo pl - twoje zrodlo informacji o swiecie mobilnym](https://user-images.githubusercontent.com/5884000/31591576-386feeac-b221-11e7-8136-14f69e6881b8.png)
![2017-10-16 03_20_27-tabletowo pl - twoje zrodlo informacji o swiecie mobilnym](https://user-images.githubusercontent.com/5884000/31591578-3ccde4d6-b221-11e7-8774-61c9c88daf74.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.38
chrome 62.0.3202.62
win10 x64

**Comment by mat41997** [comment]
nie zamykajcie proszę

**Comment by MajkiIT** [comment]
@hawkeye116477 hahahaha draźnią się z tobą :P

**Comment by hawkeye116477** [comment]
Ekspresowe tempo mają 😃 .
`tabletowo.pl##[rel="nofollow"][target="_blank"]` -> góra
`tabletowo.pl##a[href^="http://dhosting.pl"]` -> dhosting
`tabletowo.pl##a[href^="https://goo.gl"]` -> Komputronik Dell Gaming

**Comment by hawkeye116477** [comment]
@MajkiIT A linki do Komputronika na górze obok loga i w menu chowamy czy zostawiamy?
```
tabletowo.pl###menu-item-komputronik, #re_kk_near_logo
```
