### ISSUE TITLE
sport.wp.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4143]
![2017-10-26 21_46_57-co zniszczylo kazimierza deyne_ - sport - wp pl](https://user-images.githubusercontent.com/5884000/32073731-4e3b0310-ba97-11e7-8f45-9954ae6257c7.png)

![2017-10-26 21_47_09-co zniszczylo kazimierza deyne_ - sport - wp pl](https://user-images.githubusercontent.com/5884000/32073740-52e45de4-ba97-11e7-8a8d-30713b2c42fb.png)
http://sport.wp.pl/kat,1726,title,Co-zniszczylo-Kazimierza-Deyne,wid,11436540,wiadomosc.html?

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.38
chrome 62.0.3202.62
win10 x64

**Comment by MajkiIT** [comment]
@mat41997 Dzięki
