### ISSUE TITLE
play.google.com & translate.google.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4144]
Znowu wujek coś zmienił i polityka oraz komunikat ciasteczkowy się pojawiły. `play.google.com,translate.google.pl##.gb_g`

**Comment by mat41997** [comment]
ten, ale to chyba do naszych angielskich przyjaciół musisz się kierować?
https://github.com/uBlockOrigin/uAssets/issues
https://github.com/easylist/easylist/issues
https://github.com/AdguardTeam/AdguardFilters/issues
https://github.com/ryanbr/fanboy-adblock/issues

**Comment by Opera48** [comment]
Jakby jeszcze ktoś stosował **cookiemonster** od *fanboy* lub **I don't care about cookies* od *Kiko* / *kiboke-studio*.

**Comment by mat41997** [comment]
@Opera48 ja stosuje I don't care about cookies

**Comment by Opera48** [comment]
Ale pewnie większość nie wycbodzi poza 6 flitrów z:

https://www.certyficate.it/adblock/

:(

**Comment by mat41997** [comment]
podobnie jak z 
https://filterlists.com/

**Comment by xxcriticxx** [comment]
kad + popup blocker <3
