### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4147]
![2017-10-27 11_26_53-lotto ekstraklasa - pilka nozna - wp sportowefakty](https://user-images.githubusercontent.com/5884000/32097559-3b5cfabe-bb0a-11e7-8aaf-4998ec3491d4.png)
https://sportowefakty.wp.pl/pilka-nozna/lotto-ekstraklasa

![2017-10-27 11_33_32-zuzel - aktualne informacje - wp sportowefakty](https://user-images.githubusercontent.com/5884000/32097696-b03c9128-bb0a-11e7-98e4-73efc43dab3c.png)
https://sportowefakty.wp.pl/zuzel

![2017-10-27 11_36_13-holder jako babysitter bedzie jezdzil ale i tez opiekowal sie mlodymi zawodnik](https://user-images.githubusercontent.com/5884000/32097828-15837a60-bb0b-11e7-92aa-b20ce24965f6.png)
https://sportowefakty.wp.pl/zuzel/718541/holder-jako-babysitter-bedzie-jezdzil-ale-i-tez-opiekowal-sie-mlodymi-zawodnikam

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.39
chrome 62.0.3202.75
win10 x64

**Comment by SebaK666** [comment]
Prosiłbym na drugi raz, żeby zwłaszcza na SF sprawdzić czy filtr blokuje tylko reklamy. Bo ostatnio widzę, ze przez ich działania, dodawanie filtrów strona często nie jest wyświetlana kompletnie, a blokowała zdjęcia z instagrama, tabelki, komentarze czytelników w relacjach live

Teraz dla przykładu nowa poprawka zablokowała reklamy, ale też na górnym pasku relacje live
![sf](https://user-images.githubusercontent.com/33153803/32104254-ec962602-bb23-11e7-8a68-f4708536611c.jpg)

**Comment by mat41997** [comment]
@MajkiIT zerknij up

**Comment by HateAds** [comment]
@MajkiIT  Muszę potwierdzić to co napisał @SebaK666 . na sportowych faktach są problemy z poprawnym funkcjonowaniem strony. Warto byłoby przyjrzeć się wszystkim regułom dla tej domeny.

**Comment by SebaK666** [comment]
Jestem tu nowy, nie będę was pouczać, ale zwłaszcza stronami z portalu wp.pl trzeba się dokładniej przyjrzeć, bo kombinują, zmieniają niesamowicie, praktycznie codziennie.

Teraz zauważyłem, że także na tej samej stronie brak rozwijanego menu "więcej" na czarnym górnym pasku za napisem SGP. Blokowane chyba są też galerie ze zdjęciami pod quizem z prawej strony, a także Sportowy Bar w tym samym miejscu ze zdjęciami do innych artykułów

**Comment by mat41997** [comment]
@SebaK666 otwórz nowy wątek, bo @MajkiIT nie widzi.

**Comment by HateAds** [comment]
Tu na githubie źle jest rozwiązana 1 sprawa, a mianowicie, ktoś kto założył wątek powinien móc go otworzyć ponownie, nie wiem czemu jak admin zamyka temat to później założyciel tematu nie może go ponownie otworzyć. Zauważyłem, że można to zrobić tylko wtedy, kiedy sam zamkniesz swój temat.
Dziwne.
