### ISSUE TITLE
pato.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4148]
![2017-10-27 11_54_32-przerabianie zdjec foto efekty graficzne obrobka edycja generator](https://user-images.githubusercontent.com/5884000/32098651-ab432058-bb0d-11e7-8bef-8e2cf3e3ff9c.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.39
chrome 62.0.3202.75
win10 x64

**Comment by hawkeye116477** [comment]
Social -> `pato.pl###nasza_klasa_side_bar`
Reklama -> `pato.pl##a[href="http://nocnik.pl/"]`
