### ISSUE TITLE
Strona z filtrami

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4150]
@MajkiIT Możesz dodać nowy filtr na stronę www.certyficate.it/adblock - **Popup Blocker PLUS - uzupełnienie do uBlocka i AdGuarda**?
`<a href="abp:subscribe?location=https%3A%2F%2Fraw.githubusercontent.com%2Fazet12%2FPopupBlocker%2Fmaster%2FPPB_uBlock_AdGuard.txt&amp;title=PPB_uBlock_AdGuard">Subskrybuj</a>`
https://raw.githubusercontent.com/azet12/PopupBlocker/master/PPB_uBlock_AdGuard.txt

Jeszcze przy okazji znalazłem mały błąd, do poprawy jest link do zgłoszeń do Popup Blockera, powinien być https://github.com/azet12/PopupBlocker/issues .

**Comment by MajkiIT** [comment]
gotowe.

**Comment by hawkeye116477** [comment]
@MajkiIT Dzięki, ale opis do poprawy, coś ci się chyba pomyliło, Popup Blocker PLUS - uzupełnienie do uBlocka i AdGuarda to jest filtr typu annoyances, a nie social 😄 .

**Comment by mat41997** [comment]
wszystkie moje filtry możesz dodać do listy http://www.certyficate.it/adblock

**Comment by xxcriticxx** [comment]
@mat41997 jakie masz filtry?

**Comment by mat41997** [comment]
@xxcriticxx  https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

**Comment by xxcriticxx** [comment]
@mat41997  Myślałem ze masz jakieś swoją listę
