### ISSUE TITLE
animes.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4151]
![2017-10-27 12_53_00-animes pl _ forum o tematyce anime manga kultura japonska](https://user-images.githubusercontent.com/5884000/32100863-cbb31926-bb15-11e7-86e2-57e824d29110.png)

![2017-10-27 12_54_33-re_ zero _ animes pl](https://user-images.githubusercontent.com/5884000/32100913-0d50c554-bb16-11e7-9bf3-dca8d3256747.png)
https://animes.pl/watek-re-zero--4117?

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.39
chrome 62.0.3202.75
win10 x64

**Comment by hawkeye116477** [comment]
Social:
```
animes.pl###ougcannbars_bar_1
animes.pl##.register:has-text(Logowanie z FB)
```

Reklamy:
```
animes.pl##.section-side > .mini-box:nth-of-type(2)
animes.pl##.mini-title:nth-of-type(1) > p > a[href="#"]
||animes.pl/jscripts/myadvertisements.js$script
```
