### ISSUE TITLE
wakai.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4153]
![2017-10-27 13_05_32-radio azjatyckie wakai pl - nowosci ciekawostki myzka anime manga](https://user-images.githubusercontent.com/5884000/32101324-04b3168e-bb18-11e7-8136-aeb218b8618e.png)
popup

![2017-10-27 13_07_52-radio azjatyckie wakai pl - nowosci ciekawostki myzka anime manga](https://user-images.githubusercontent.com/5884000/32101330-0c404480-bb18-11e7-96bf-072e25c76460.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.39
chrome 62.0.3202.75
win10 x64

**Comment by hawkeye116477** [comment]
A to łobuzy, nawet koparę mają 😃 .
Sklepik -> `wakai.pl###text-html-widget-5`
Polecane kanały YT -> `wakai.pl##.youtube-widget`
Współpraca medialna -> `wakai.pl###text-html-widget-6`
