### ISSUE TITLE
brw.com.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4154]
![2017-10-27 13_52_53-black red white - meble i akcesoria - internetowy salon meblowy brw](https://user-images.githubusercontent.com/5884000/32102810-37bdb01a-bb1e-11e7-8d5a-193eba04101b.png)
nie ma zdjęć

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.39
chrome 62.0.3202.75
win10 x64

**Comment by hawkeye116477** [comment]
Pusty popup, nic nie ma, nawet bez uBlocka, admin strony najwyraźniej coś sknocił.
A co do tych zdjęć, to u mnie jest ok.

**Comment by mat41997** [comment]
@hawkeye116477 po wyczyszczeniu cache jest, sprawdź na innej przeglądarce.
![2017-10-27 14_41_32-brw com pl issue 4154 majkiit_polish-ads-filter](https://user-images.githubusercontent.com/5884000/32104498-fc77f6da-bb24-11e7-8f89-ba30e9efbc9a.png)

ale ciekawy anty adblock

**Comment by MajkiIT** [comment]
Niestety nie jestem w stanie tego odtworzyć ...

**Comment by mat41997** [comment]
naprawione
