### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4157]
https://github.com/MajkiIT/polish-ads-filter/issues/4147#issuecomment-339959113

**Comment by SebaK666** [comment]
Także nie działają te cztery przyciski:
![sf2](https://user-images.githubusercontent.com/33153803/32133411-80703b48-bbd7-11e7-9e26-07002e0d6b82.jpg)

**Comment by HateAds** [comment]
@mat41997 @SebaK666 U mnie niemal wszystko na tej stronie przestało funkcjonować ( musiałem wyłączyć pol filtry ) @MajkiIT help please.

**Comment by MajkiIT** [comment]
widziałem wasze komentarze ale dopiero dorwałem się do kompa. Już patrzę.

**Comment by HateAds** [comment]
@MajkiIT OK testuje. Jak na razie działa ok.

**Comment by SebaK666** [comment]
Jest dużo lepiej. Widzę nieraz jednak reklamę:

![ads](https://user-images.githubusercontent.com/33153803/32137908-382a529a-bc29-11e7-913a-2a5518527427.jpg)


Na głównej stronie blokowany jest jednak program tv
Porównanie z wyłączonym i włączonym filtrem:

![program](https://user-images.githubusercontent.com/33153803/32137931-ed165802-bc29-11e7-8b29-9edce4aacea7.jpg)


podobnie na stronie z żużlem, gdzie brak z boku galerii
Wyłączony  filtr:

![pasek2](https://user-images.githubusercontent.com/33153803/32137948-3dbd7bdc-bc2a-11e7-9080-0ffd53ce621c.jpg)

Włączony filtr:
![pasek2](https://user-images.githubusercontent.com/33153803/32137954-4e1eb0e0-bc2a-11e7-911f-b1f1497d5cae.jpg)

Możliwe że to cena za blokowanie reklam i odblokowanie tych ramek będzie skutkowało pokazywaniem się znów reklam.

**Comment by HateAds** [comment]
Potwierdzam u mnie to samo co u @SebaK666. Jeszcze parę poprawek jest potrzebnych @MajkiIT.

**Comment by MajkiIT** [comment]
@SebaK666 masz adblocka?

**Comment by SebaK666** [comment]
Używam Adblock Plus - co mówisz w domyśle ma znaczenie? Bo pewnie chcesz powiedzieć, że uBlock to blokuje?

**Comment by MajkiIT** [comment]
@SebaK666 tak ma a w tym przypadku kluczowe. Dzięki @kasper93 ublock blokuje reklamy a Adblock jest ograniczony funkcjonalnie i ogranicza nasze możliwości, bo WP ciągle zmienia strony i podowuje błędy.

**Comment by mat41997** [comment]
@SebaK666 polecam uBlock Origin wraz z uBlock Protector Extension
https://jspenguin2017.github.io/uBlockProtector/
