### ISSUE TITLE
wirtualnemedia.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4158]
![2017-10-27 19_05_22-agora sprzedaje za 19 mln zl dzialke przy swojej glownej siedzibie zyska na tym](https://user-images.githubusercontent.com/5884000/32116179-dbd79b40-bb49-11e7-9385-2428cd9fc2cc.png)
http://www.wirtualnemedia.pl/artykul/agora-sprzedaje-za-19-mln-zl-dzialke-przy-swojej-glownej-siedzibie-zyska-na-tym-w-br-8-3-mln-zl

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.39
chrome 62.0.3202.75
win10 x64

**Comment by hawkeye116477** [comment]
Jeśli chodzi o ten baner, to on prowadzi do ich własnego serwisu, więc raczej nie blokujemy 😄 .

**Comment by mat41997** [comment]
@hawkeye116477 ale jest bardzo duży i w złym miejscu
obowiązują pewne standardy, a ten baner podpada właśnie pod reklame

**Comment by xxcriticxx** [comment]
@mat41997 to jest z tego samego domeny tego niema sensu blokowac

**Comment by mat41997** [comment]
@xxcriticxx tak samo jak nie ma sensu blokować partnerów, a zablokowaliście komutronik na tabletowo.

na argument z domeną powiem że mogę sobie zrobić subdomenę i tak samo twierdzić.

**Comment by hawkeye116477** [comment]
Ja tam zmieniam zdanie, blokujemy 😄 .
`wirtualnemedia.pl##a[href="http://www.wirtualnemedia.pl/praca/"]`

**Comment by xxcriticxx** [comment]
@mat41997 ale przewaznie tak sie nie dzieje :)

**Comment by mat41997** [comment]
@xxcriticxx w każdej chwili może się to zmienić jeżeli nadal będziecie to tolerować. wystarczy że ktoś z tabletowo zobaczy ten post i wtedy słowo "przeważnie" straci znaczenie.

**Comment by xxcriticxx** [comment]
Zapytaj @MajkiIT co otym myśli

**Comment by mat41997** [comment]
@xxcriticxx  zobacz jaka akcja na wykopie
https://www.wykop.pl/link/3987679/comment/49740549

**Comment by xxcriticxx** [comment]
@mat41997 jednyne wyjscie musisz strzelic nam reklame na wykopie moze wtedy bendzie wiekszy ruch u nas
