### ISSUE TITLE
cyberkino.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4160]
fake player zmienil nazwe i znowu sie pokazuje + footer na dole 

@MajkiIT sie zdaje ze bylo kilka inych stron stym 

http://cyberkino.pl/film/czarny+diament+diamant+noir+online+zalukaj/21942

![capture](https://user-images.githubusercontent.com/15007183/32134198-ffe3cbd2-bbb5-11e7-8882-2d68752c2063.PNG)

**Comment by MajkiIT** [comment]
Dzięki
