### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by FortinOne** [MajkiIT/polish-ads-filter#4161]
### Co trzeba zrobić aby reklama/element się pojawił
1.usunąc to co widac na dole zrzutu
2.
3.

### Twoja konfiguracja
**Przeglądarka:**
Comodo Dragon
**Operating system:**
Windows 10 Home
**Blocker:**
Adblock
**Używane filtry:**
1.
2.
3.
4.

### Zrzut ekranu
```
![zrzut ekranu 45](https://user-images.githubusercontent.com/33182318/32136577-75238edc-bc10-11e7-9c44-4ff28e95201f.png)

wstaw tutaj link
```
http://www.filmweb.pl/film/(dowolny film) np http://www.filmweb.pl/film/Thor%3A+Ragnarok-2017-707970

**Comment by MajkiIT** [comment]
@hawkeye116477 @xxcriticxx macie adblocka? U mnie czysto.

**Comment by xxcriticxx** [comment]
yes sir na chromie adlbock i cookies 

![capture](https://user-images.githubusercontent.com/15007183/32136725-e80f3b60-bbe0-11e7-8ba8-e9634b349962.PNG)

**Comment by xxcriticxx** [comment]
@MajkiIT podane do pigwina

**Comment by xxcriticxx** [comment]
@MajkiIT sorry liste protectora mialem wylonczonna jak wlonczylem wszystko jest ok

**Comment by MajkiIT** [comment]
@hawkeye116477 już chyba mam

**Comment by MajkiIT** [comment]
@FortinOne zaktualizuj filtry do min wersji 2017102801 i sprawdź

**Comment by mat41997** [comment]
u mnie czysto

wgraj ublock origin + ublock origin protector extensions
https://jspenguin2017.github.io/uBlockProtector/

**Comment by xxcriticxx** [comment]
@MajkiIT od pigwina 

`filmweb.pl##script:inject(setTimeout-defuser.js, notDetected)`

**Comment by FortinOne** [comment]
@xxcriticxx Jak to dodać?
@MajkiIT zaktualizowałem
@mat41997 Nie chce to współpracować z Comodo Dragon

**Comment by xxcriticxx** [comment]
@FortinOne dodac pod moje fitlry w ublocku

@mat41997 co to za nowy browser?

**Comment by mat41997** [comment]
@xxcriticxx jakiś fork chromium 58 od sławnej firmy comodo zajmującej się produkcją mniej bezpiecznych anty virusów od windows defender

ostatnio było o niej głośno z powodu
- "Sprzedawanie certyfikatów SSL twórcom wirusów komputerowych. Dzięki temu ich malware może atakować użytkowników z poziomu “bezpiecznego” protokołu HTTPS"
- "Dorzucanie do swojego oprogramowania toolbaru (dawniej SafeSurf, obecnie HopSurf"
- "Comodo Internet Security (Firewall, AntyVirus i AntiMalware), Comodo Backup, Comodo system Cleaner, Comodo SecureEmail i Comodo EasyVPN od najnowszych wersji zaczęły zbierać dane na temat tego, jak użytkownicy korzystają z oprogramowania"

**Comment by hawkeye116477** [comment]
@FortinOne No bo uBlock Protector Extension działa jedynie z Chromium 60+, czyli Comodo Dragon odpada, bo to jest Chromium 58. Poleciłbym zamianę na Vivaldi, w stable jest tylko 1 numerek do tyłu za Google i nie ma problemów z bezpieczeństwem 😄 .
https://threatpost.com/chromodo-browser-disables-same-origin-policy/116131/
