### ISSUE TITLE
pudelek.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4163]
![2017-10-29 14_37_01-paulina smaszcz-kurzajewska - pudelek](https://user-images.githubusercontent.com/5884000/32144292-ea3a41ba-bcb6-11e7-999f-4b176de87a4d.png)
http://www.pudelek.pl/tag/Paulina+Smaszcz-Kurzajewska/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.44
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
`pudelek.pl##.results__entry.toRight`
