### ISSUE TITLE
vape.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4164]
![2017-10-29 14_42_35-wasp nano rda ultra mala beczulka pelna smaku _ vape pl](https://user-images.githubusercontent.com/5884000/32144339-aa4f5c42-bcb7-11e7-81a1-c7c7b75f8b19.png)
https://vape.pl/pin/wasp-nano-rda-ultra-mala-beczulka-pelna-smaku-3/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.44
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
`vape.pl###single-pin-above-ad`
