### ISSUE TITLE
cshacked.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4171]
cookies

![capture](https://user-images.githubusercontent.com/15007183/32146589-f3ee0b26-bcaf-11e7-9723-dc7c29733e24.PNG)

**Comment by hawkeye116477** [comment]
`cshacked.pl###elGuestTerms`
@xxcriticxx Czyli w gry nie grasz, bot za ciebie gra 😃  .
