### ISSUE TITLE
sgforum.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4172]
![2017-10-29 19_16_55-sgforum - siec serwerow counter strike 1 6 _ go](https://user-images.githubusercontent.com/5884000/32146844-e322daa0-bcdd-11e7-90e9-b8d37962d52a.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.45
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
`sgforum.pl###partnerzy`
