### ISSUE TITLE
gocs.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4173]
![2017-10-29 19_22_08-cs go portal - gocs pl - nowosci porady forum liga counter-strike_ global of](https://user-images.githubusercontent.com/5884000/32146928-e59b82b8-bcde-11e7-99a2-6f69dcb2fdd3.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.45
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
`gocs.pl##.ads_widget`
