### ISSUE TITLE
dobra-mama.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4174]
![2017-10-29 19_28_35-dobra mama - magazyn inspirowany dzieckiem](https://user-images.githubusercontent.com/5884000/32146971-6ff614be-bcdf-11e7-9fb6-db4731b4823b.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.45
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
dobra-mama.pl###slideshow
