### ISSUE TITLE
crypto-trader.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4175]
![2017-10-29 21_42_47-crypto trader _ porady analiza kursu dla kryptowalut bitcoin litecoin progno](https://user-images.githubusercontent.com/5884000/32148128-6462ddc2-bcf2-11e7-9880-c82c9d98a220.png)

![2017-10-29 21_43_30-crypto trader _ porady analiza kursu dla kryptowalut bitcoin litecoin progno](https://user-images.githubusercontent.com/5884000/32148129-667275fa-bcf2-11e7-8cac-2a1dd4362d34.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.45
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
`crypto-trader.pl##.wp-image-1528`
