### ISSUE TITLE
teleshow.wp.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4176]
![2017-10-29 22_30_59-wp teleshow](https://user-images.githubusercontent.com/5884000/32148545-00f4abec-bcf9-11e7-8062-fa49b1617212.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.45
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
@mat41997 sprawdzisz?
`teleshow.wp.pl##A[href*=".wp.pl/"] > DIV > IMG[class][src^="https://v.wpimg.pl/"] `

**Comment by mat41997** [comment]
chyba działa
tylko jeszcze wyświetlające/migające przez kilka sekund puste okna po reklamach.

**Comment by xxcriticxx** [comment]
@mat41997 testowales nowe filtry?
