### ISSUE TITLE
meczelive.tv

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4179]
![2017-10-29 23_05_30-mecze na zywo skroty meczow wyniki na zywo transmisje online filmiki sportow](https://user-images.githubusercontent.com/5884000/32148929-be08f18a-bcfd-11e7-9762-3a1b6fe84fa5.png)

![2017-10-29 23_05_47-mecze na zywo skroty meczow wyniki na zywo transmisje online filmiki sportow](https://user-images.githubusercontent.com/5884000/32148974-5c83d186-bcfe-11e7-8236-4e18ad314050.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.45
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
`meczelive.tv##[target="_blank"] > IMG[src^="http://meczelive.tv/new/300/"]`

@mat41997 Partnerzy tez?

**Comment by mat41997** [comment]
@MajkiIT jak uważasz, @xxcriticxx mówił że partnerów nie blokujecie.
ja uważam że jak są to przydatne linki tzn. "valuable" inaczej wartościowe to mogą zostać.
