### ISSUE TITLE
Advert in video.

### ISSUE THREAD

**Issue by xisarcher** [MajkiIT/polish-ads-filter#418]
In this video is an advert on the start and couple times during the film. Always AdBlock was blocking them but now it's not working.

**Comment by xxcriticxx** [comment]
what website?

**Comment by xisarcher** [comment]
I gave you an adress to video. It's www.vider.pl. I'm using it to watching online films and couple weeks ago adblock was working there but now every few minutes I have an ad.

**Comment by F4z** [comment]
`||vider.pl/static/player/v*/vast.js$script`

**Comment by MajkiIT** [comment]
@F4z thanks I will add it.

**Comment by MajkiIT** [comment]
@xisarcher update polish filters.
