### ISSUE TITLE
grodzisknews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4180]
![2017-10-30 04_18_19-kto wygral bilety na dodatkowy wystep neo-nowki w grodzisku_ sprawdz grodziskne](https://user-images.githubusercontent.com/5884000/32153234-85934158-bd29-11e7-8af5-37d3da72774b.png)
http://grodzisknews.pl/wygraj-bilety-na-dodatkowy-wystep-neo-nowki-w-grodzisku/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.46
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
`##.ad_Handle`
