### ISSUE TITLE
livespot.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4182]
![2017-10-30 15_23_21-tak wyglada ocenzurowany wolfenstein ii_ the new colossus w niemczech](https://user-images.githubusercontent.com/5884000/32175873-753b8772-bd86-11e7-89df-51ab32a1832d.png)

![2017-10-30 15_23_33-tak wyglada ocenzurowany wolfenstein ii_ the new colossus w niemczech](https://user-images.githubusercontent.com/5884000/32175878-77c6042c-bd86-11e7-8582-ac14e999bb50.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.46
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
`livespot.pl##.text-center`
