### ISSUE TITLE
bezprawnik.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4184]
puste miejsce po reklamach
![2017-10-30 15_38_30-bezprawnik pl - prawo spoleczenstwo opinie](https://user-images.githubusercontent.com/5884000/32176639-8c98860c-bd88-11e7-8cdd-258d8ca985f8.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.46
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
`bezprawnik.pl##.show-for-large.columns`
