### ISSUE TITLE
fpiec.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4187]
![2017-10-30 15_51_32-pracownia godny na poznanskiej wildzie ndash miejsce w kt oacute rym kupicie](https://user-images.githubusercontent.com/5884000/32177318-4f3bbb42-bd8a-11e7-8585-30f832acc2dc.png)
http://www.fpiec.pl/post/2017/10/28/pracowniachlebka

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.46
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
`fpiec.pl###a-slot-content-13047-blog-body-7`
