### ISSUE TITLE
historykon.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4188]
![2017-10-30 15_55_31-historykon pl](https://user-images.githubusercontent.com/5884000/32177508-cb9a8614-bd8a-11e7-95c0-62c50526f619.png)
http://historykon.pl/publicystyka/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.46
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
`historykon.pl###text-3`
