### ISSUE TITLE
ndie.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4189]
![2017-10-30 16_28_10-nie dla islamizacji europy _ ndie pl](https://user-images.githubusercontent.com/5884000/32179319-663e79a6-bd8f-11e7-89a3-68d06bf9399d.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.46
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
`ndie.pl##.textwidget`
