### ISSUE TITLE
newsbook.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4191]
![2017-10-30 16_34_10-newsbook _ polski portal nie tylko o polsce](https://user-images.githubusercontent.com/5884000/32179646-3d2ae9f4-bd90-11e7-8e5f-cd878b9f42e6.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.46
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
```
newsbook.pl##.blocker.jquery-modal
newsbook.pl###popup
```
