### ISSUE TITLE
polskieradio.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4194]
brak player'a
![2017-10-31 01_42_34-polskieradio pl - serwis informacyjny polskiego radia](https://user-images.githubusercontent.com/5884000/32202419-e3394aba-bddc-11e7-815e-580143e17ca6.png)

https://github.com/MajkiIT/polish-ads-filter/blob/master/adblock_social_filters/adblock_social_list.txt

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.46
chrome 62.0.3202.75
win10 x64

**Comment by hawkeye116477** [comment]
Problem powoduje reguła `pl##.listen`, zgaduję, że pewnie gdzieś jeszcze będzie powodować problem, więc jest do usunięcia.
