### ISSUE TITLE
parenting.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4196]
![2017-10-31 02_31_13-ciaza objawy ciazy kalendarz ciazy porod polog _ wp parenting](https://user-images.githubusercontent.com/5884000/32203475-c3734580-bde3-11e7-94d1-66ba8138b06a.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.46
chrome 62.0.3202.75
win10 x64

**Comment by MajkiIT** [comment]
Ma to ktoś u siebie ?

**Comment by mat41997** [comment]
ja
![2017-11-02 19_48_23-niedoceniana soda oczyszczona dzieki niej pozbedziemy sie chemii z powierzchni](https://user-images.githubusercontent.com/5884000/32344348-dfac9ec0-c006-11e7-8406-4032a26b7431.png)
https://parenting.pl/niedoceniany-proszek-do-pieczenia-naukowcy-odkryli-ze-dzieki-niej-pozbedziemy-sie-az-96-proc-pestycydow-z-powierzchni-owocow

**Comment by xxcriticxx** [comment]
yes sir on chrome 

![capture](https://user-images.githubusercontent.com/15007183/32344625-db93f21c-bfdd-11e7-97e6-240660c942ef.PNG)

**Comment by MajkiIT** [comment]
@mat41997 Zaktualizuj filtry

**Comment by mat41997** [comment]
@MajkiIT brak efektu

**Comment by xxcriticxx** [comment]
@mat41997 lepiej niz bylo

**Comment by mat41997** [comment]
@xxcriticxx nie mędrkuj.

**Comment by MajkiIT** [comment]
@kasper93 możesz zerknąć na te szare pola ?

**Comment by kasper93** [comment]
Dla uBO:

```
parenting.pl##:xpath(//div[count(*)=1][*[count(*)=1]/*[count(*)=1]/*[count(*)=1]/*[count(*)=0]])
parenting.pl##:xpath(//div[count(*)=1][*[count(*)=1]/*[count(*)=1]/*[count(*)=1]/*[count(*)=1]/*[count(*)=0]])
```

Ten drugi jest taki sam jak dla wp, więc można po prostu domenę dodać.

**Comment by MajkiIT** [comment]
@kasper93 Dziękuję
