### ISSUE TITLE
kabeltv.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4204]
regex please

http://kabeltv.pl/discovery-channel/

**Comment by MajkiIT** [comment]
Nie mogę tego wyłapać

**Comment by xxcriticxx** [comment]
sie otwiera tylko za pierwszym razem jak play nacisniesz

**Comment by hawkeye116477** [comment]
Social -> `kabeltv.pl##.widget-title:has-text(Facebook)`
