### ISSUE TITLE
fiskars.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4208]
Po schowaniu komunikatu ciasteczkowego trzeba podnieść menu do góry. `fiskars.pl##.desktop:style(top: 0px!important;)`

Resztki - social -> `fiskars.pl##.h2::abp-contains(Znajdź nas)`

**Comment by xxcriticxx** [comment]
@hawkeye116477 zostaniesz ogrodnikem
