### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4210]
Ciasteczka -> `filmweb.pl##.webPage.cookieInfo`.
Oprócz tego widzę, że wrócił antyadblock, ale to pewnie raczej zadanie dla bezlotka.

**Comment by mat41997** [comment]
@hawkeye116477 na protektorze nic nie mam.

**Comment by hawkeye116477** [comment]
@mat41997 Mam uBlock Protector i właśnie nie jest czysto. Ale tak czy siak, już ktoś to zgłosił
https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/335 😄 .

**Comment by xxcriticxx** [comment]
@hawkeye116477 sprawdzales to z ostatniego razu?

`filmweb.pl##script:inject(setTimeout-defuser.js, notDetected)`

**Comment by hawkeye116477** [comment]
@xxcriticxx Ta, to już nie działa.

**Comment by xxcriticxx** [comment]
ok

**Comment by MajkiIT** [comment]
@hawkeye116477 Ja tego nie mam na 3 przeglądarkach i 2 kompach :( @xxcriticxx ty widzisz ?

**Comment by xxcriticxx** [comment]
@MajkiIT u pingwina pisze kilka razy trzeba stronę zaladowac

**Comment by hawkeye116477** [comment]
@MajkiIT Pingwin już to naprawił, ale tylko w Protectorze. 
https://github.com/jspenguin2017/uBlockProtector/commit/f7d9d2975bda5babefc0d23188a0b6c354055ff7
AAK Cont tak w ogóle ma już przestać być rozwijany, zamiast tego będzie Adblock Protector 2, który ma już nie być skryptem, a rozszerzeniem dla przeglądarek Quantum, Chrome, Chromium i Opera 😄 .

**Comment by MajkiIT** [comment]
Ok, dodałem regułe. Dzięki.

**Comment by hawkeye116477** [comment]
@MajkiIT Tyle, że niestety te 2 reguły, które dodałeś, działają tylko na raz, odświeżysz i antyadblock już jest. Dlatego pingwin usunął je i dodał blokowanie tego do rozszerzenia. Na AAK Cont na razie nie ma rozwiązania, więc ci co chcą oglądać filmweb z Adblockiem muszą przesiąść się na uBlocka i coś Chromium-based albo czekać aż powstanie Adblock Protector 2 😃 .

**Comment by Zawodowiec1532** [comment]
Co mam dodać do uBlocka, żeby się pozbyć tego skurwysyństwa?

**Comment by mat41997** [comment]
@Zawodowiec1532 ublock protector jeśli masz chrome
https://jspenguin2017.github.io/uBlockProtector/

aak-cont jeśli masz firefoxa
https://gitlab.com/xuhaiyang1234/AAK-Cont#anti-adblock-killer-continued

dodatkowe filtry
https://www.certyficate.it/adblock/

**Comment by hawkeye116477** [comment]
@mat41997 AAK Cont niestety na to nie pomaga, tylko uBlock Protector pomaga.

**Comment by mat41997** [comment]
@hawkeye116477 to pozostaje mi polecić twój poradnik jak zainstalować protectora na firefoxie
https://github.com/MajkiIT/polish-ads-filter/wiki/Jak-zainstalowa%C4%87-uBlock-Protector-Extension-na-Firefoksie-lub-Waterfoksie%3F

**Comment by Zawodowiec1532** [comment]
Mam Operę..

**Comment by xxcriticxx** [comment]
@Zawodowiec1532 widzialem ze sie uczeszczasz na easylist forum

**Comment by hawkeye116477** [comment]
@Zawodowiec1532 No to uBlock Protector tam też będzie działał. Trzeba tylko pobrać https://addons.opera.com/pl/extensions/details/download-chrome-extension-9/?display=en , a potem postępować wg. instrukcji na: https://jspenguin2017.github.io/uBlockProtector/.

**Comment by gwarser** [comment]
Ciekawe dlaczego nie działa w UBO, bo wygląda na to, że to ten sam filtr.

**Comment by Zawodowiec1532** [comment]
Ale czym to się różni w ogóle od zwykłego uBlocka do opery? Dlaczego po prostu nie można zablokować tego skryptu zwykłym filtrem. :D

@xxcriticxx Nom, kazali mi napisać tutaj.

@hawkeye116477 Dzięki, przetestuję wieczorem.

**Comment by hawkeye116477** [comment]
@Zawodowiec1532 uBlock Protector Extension stosuje pewne obejścia, które niestety nie są możliwe na zwykłym uBlocku, ale lista z filtrami też jest do tego potrzebna. uBlock Protector Extension to taki odpowiednik skryptu AAK Cont, tyle tylko, że on ma więcej możliwości, wszystko robi lepiej i szybciej.
Tak jest blokowany ten antyadblock filmwebu -> https://github.com/jspenguin2017/uBlockProtector/commit/f7d9d2975bda5babefc0d23188a0b6c354055ff7

A czemu to nie jest możliwe na uBlock Origin, to pytanie chyba raczej do twórcy.

**Comment by mat41997** [comment]
@hawkeye116477 mógłbyś rozwinąć poradnik o instalacje protektora na operze : )

**Comment by hawkeye116477** [comment]
Ok, ale jakby co, to nie gwarantuję, że Protector będzie prawidłowo działał na ChrOperze, coś tam może nie działać, gdyż ChrOpera nie obsługuje pewnych rzeczy, które Chrome obsługuje.

**Comment by gwarser** [comment]
Właśnie próbuję załatać AAK dla filmwebu i widzę, że jak mam w UBO ten filtr, to AAK wywala błąd.

**Comment by mat41997** [comment]
@hawkeye116477 a ten poradnik
https://github.com/MajkiIT/polish-ads-filter/wiki/Jak-blokowa%C4%87-reklamy-w-przegl%C4%85darce-Yandex-na-Androidzie-(uBlock-i-AAK-Cont-lub-Adguard)%3F

mógłbyś rozwinąć o ublock protektora.

**Comment by hawkeye116477** [comment]
@mat41997 A na Yandex na Andku działa uBlock Protector? Ostatnio sprawdzałem i zdaje się, że nie działało, krzyczał, że błędna nazwa jakiegoś katalogu i wersja Chrome jest za stara. Chyba, że można by spróbować zmienić minimalną wersję wymaganą w plikach. Tylko, że będzie problem z updatami, bo one są dość często, a trzeba będzie je robić ręcznie. Tak czy siak jeszcze to obadam czy coś dadzą te tricki ze zmianą nazwy i wersji.

**Comment by mat41997** [comment]
@hawkeye116477 gdzieś tam poklikałem i działa
![screenshotcapture_2017_11_08_18_24_33](https://user-images.githubusercontent.com/5884000/32563717-40d070e6-c4b2-11e7-8c2d-66b3a5f4ab5e.png)

**Comment by hawkeye116477** [comment]
@mat41997 Sprawdziłem i minimalna wymagana wersja Chromium to 58, a Yandex ma już wyższą, więc pewnie dlatego się zainstalował. W takim razie sprawdzę czy naprawdę działa na filmwebie i coś tam niedługo napiszę.

**Comment by Zawodowiec1532** [comment]
Dzięki za pomoc. :)
Zainstalowałem te 2 dodatki i w końcu nie ma reklam na filmwebie. <3

**Comment by hawkeye116477** [comment]
@mat41997 Zaktualizowałem poradnik i zmontowałem  nawet filmik jak zainstalować Protectora w Yandex na Andku -> https://www.youtube.com/watch?v=XulYmxjJszY .
https://github.com/MajkiIT/polish-ads-filter/wiki/Jak-blokowa%C4%87-reklamy-w-przegl%C4%85darce-Yandex-na-Androidzie-(uBlock-i-AAK-Cont,-uBlock-i-uBlock-Protector-lub-Adguard)%3F

**Comment by mat41997** [comment]
@hawkeye116477 niestety pominąłeś w nim instalacje ublock origin i niezaznajomieni ze sztuką władania reklam dzielni magowie nie dadzą sobie z tym rady.

**Comment by hawkeye116477** [comment]
@mat41997 Przecież instalacja uBlock Origin jest już w poprzednim filmiku, tak samo w podpunkcie A, też masz opisane jak zainstalować uBlock Origin.

**Comment by mat41997** [comment]
@hawkeye116477 który trwa ponad 10 minut i nikt go przez to nie obejrzy. a nawet jak obejrzy to nie zrozumie bo w międzyczasie zaśnie ze znużenia.

**Comment by hawkeye116477** [comment]
@mat41997 A tam, czepiasz się, 86 wyświetleń i 2 lajki już ma. A jak się komuś nie będzie chciało oglądać, to przeczyta sobie poradnik na wiki.

**Comment by hawkeye116477** [comment]
@mat41997 Poprawiłem filmik, za ok. 2h powinien być dostępny -> https://youtu.be/nmEs0J4M-7I .

**Comment by hawkeye116477** [comment]
@MajkiIT Możesz dodać na fejsa 
Instalowanie uBlock Origin i uBlock Protector w Yandex Browser na Androidzie -> https://youtu.be/nmEs0J4M-7I
Aktualizowanie uBlock Origin i uBlock Protector w Yandex Browser na Androidzie -> https://youtu.be/k9t9PRDn5MU

**Comment by SebaK666** [comment]
Jako ciekawostkę podam, że stworzenie takiego prostego nowego skryptu dla Greasemonkey usuwa komunikat i odblokowuje Filmweb:
```
// ==UserScript==
// @name Filmweb
// @namespace all
// @include https://filmweb.pl/*
// @include http://filmweb.pl/*
// @include http://www.filmweb.pl/*
// @noframes
// @version 1
// @grant none
// @run-at document-end
// ==/UserScript==
document.onreadystatechange = function() {}
```
