### ISSUE TITLE
wakai.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#4216]
link do hostingu

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.53
chrome 62.0.3202.75

**Comment by mat41997** [comment]
można dodać do filtrów ublocka samo wykonanie linku, a grafikę zostawić.

**Comment by OtakuPL** [comment]
Przecież e-neko.pl to strona sklepu i allegro a nie reklama ani kampania od żadnej sieci, co to ma do adblocka? Jak to właściciel sobie tam dodał...
Przesadzacie, tak samo jak logo player radiowego, co to przeszkadza? ;p "radio online"...
Powinniście banować takich agentów.

**Comment by KonoromiHimaries** [comment]
@OtakuPL w logo był odnośnik do hostingu
