### ISSUE TITLE
jedzbawsie.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4218]
![2017-11-03 00_07_51-jedz baw sie _ troche inny blog podrozniczy brewy](https://user-images.githubusercontent.com/5884000/32354723-53fce7c0-c02b-11e7-859f-95a36bd1351f.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.53
chrome 62.0.3202.75

**Comment by MajkiIT** [comment]
`jedzbawsie.pl###text-7
`
