### ISSUE TITLE
gazetaprawna.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4220]
![2017-11-03 00_22_34-gazetaprawna pl - biznes podatki prawo finanse wiadomosci praca](https://user-images.githubusercontent.com/5884000/32355138-49007ca4-c02d-11e7-99e2-b7c83091de9d.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.53
chrome 62.0.3202.75

**Comment by MajkiIT** [comment]
`gazetaprawna.pl##.tpl_stc-content.tpl_std_module`
