### ISSUE TITLE
polskamafia.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4222]
![2017-11-03 00_49_25-strona glowna - polskamafia pl](https://user-images.githubusercontent.com/5884000/32355770-182b959c-c031-11e7-8793-35f077a96f6f.png)

facebook niewidzialny : O

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.53
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
`polskamafia.pl###fpw_widget`
