### ISSUE TITLE
biznesalert.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4226]
szarość + reklama
![2017-11-03 17_05_55-strona glowna - biznesalert pl](https://user-images.githubusercontent.com/5884000/32383876-7ede44b4-c0b9-11e7-86c6-68d4b08d2917.png)

![2017-11-03 17_06_16-strona glowna - biznesalert pl](https://user-images.githubusercontent.com/5884000/32383881-80c616c6-c0b9-11e7-9630-782f91406936.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.54
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
@mat41997 Szarość to chyba od Popup Blockera, ale u mnie jest newsletter i szarość, pewnie masz PPB nie zaktualizowany, bo część reguł przeniosłem do uzupełnienia dla uBlocka i AdGuarda i wywaliłem parę ogólnych kosmetycznych, dlatego też u mnie newsletter się pojawia. A widzę też, że nie masz tego -> https://raw.githubusercontent.com/azet12/PopupBlocker/master/PPB_uBlock_AdGuard.txt . Tak czy siak, zaraz dodam odpowiednie reguły.
