### ISSUE TITLE
sport.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4235]
![2017-11-04 02_55_10-formula 1 robert kubica otrzymal propozycje kontraktu od williamsa polak wezmi](https://user-images.githubusercontent.com/5884000/32401255-ab3252ce-c10b-11e7-8206-43a414794c42.png)
http://www.sport.pl/F1/7,96296,22597098,formula-1-robert-kubica-otrzymal-propozycje-kontraktu-od-williamsa.html

same ciasteczka i reklamy

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.55
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
@mat41997 Nie widzę tam ani tego ani tamtego.

**Comment by hawkeye116477** [comment]
@mat41997 Reklamy widzę, a ciasteczka to gdzie?

**Comment by mat41997** [comment]
@hawkeye116477 aa wydawało mi się że są
