### ISSUE TITLE
rynekinwestycji.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4237]
![2017-11-04 03_17_24-rynek inwestycji - magazyn gospodarczy](https://user-images.githubusercontent.com/5884000/32401440-d87545fe-c10e-11e7-9716-b8bb37239e61.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.55
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
Social -> `rynekinwestycji.pl##.site-title:-abp-contains(FACEBOOK)`
