### ISSUE TITLE
magazynfakty.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4238]
![2017-11-04 03_20_32-polska gospodarka - fakty - magazyn gospodarczy](https://user-images.githubusercontent.com/5884000/32401465-362f61ac-c10f-11e7-842c-87c5a0548a6c.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.55
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
Social -> `magazynfakty.pl##.site-title:-abp-contains(Facebook)`
