### ISSUE TITLE
wgospodarce.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4240]
![2017-11-04 03_23_52-wgospodarce pl](https://user-images.githubusercontent.com/5884000/32401490-ba768dd2-c10f-11e7-8615-4fb3a6fe14e0.png)
http://wgospodarce.pl/tagi/innowacje

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.55
chrome 62.0.3202.75

**Comment by MajkiIT** [comment]
@mat41997 U mnie pusto 
@xxcriticxx zerkniesz u ciebie?

**Comment by hawkeye116477** [comment]
@MajkiIT 0 reklam, ale resztki social są.
`wgospodarce.pl##.widget--social-media`

**Comment by xxcriticxx** [comment]
top clean
