### ISSUE TITLE
viralz.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4246]
![2017-11-04 04_09_14-viralz pl](https://user-images.githubusercontent.com/5884000/32401756-fddc2fcc-c115-11e7-8bcb-53204775afe3.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.55
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
`viralz.pl##.spu-bg, .spu-box`
