### ISSUE TITLE
nietylkopasta.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4249]
![2017-11-04 04_28_10-olbrzymi zbior przepisow na dania na kolacje](https://user-images.githubusercontent.com/5884000/32401899-261913da-c119-11e7-9b83-c0774cdc2360.png)
http://nietylkopasta.pl/25-przepisow-na-dania-na-kolacje/

facebook niewidzialny : O

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.55
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
```
nietylkopasta.pl##.widget-text:-abp-contains(Obserwuj bloga na:)
nietylkopasta.pl##.widget-ws_fb_like_box, #dbx_light
```
