### ISSUE TITLE
reporters.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4258]
![2017-11-04 05_43_19-szminka z opryszczka kobieta pozywa sephore reporters pl](https://user-images.githubusercontent.com/5884000/32402391-4302ee94-c123-11e7-8f5e-c855792d4235.png)
https://reporters.pl/10359/szminka-z-opryszczka-kobieta-pozywa-sephore/

facebook niewidzialny : O

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.55
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
@mat41997 To jest RSS, a nie Facebook, dodam to do PPB.

**Comment by xxcriticxx** [comment]
@hawkeye116477 fb halloween edition
