### ISSUE TITLE
obcasy.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4261]
![2017-11-04 06_27_14-portal dla kobiet - moda zdrowie dieta milosc _ obcasy pl](https://user-images.githubusercontent.com/5884000/32402671-d0a34fc2-c129-11e7-9203-44aaea51ea90.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.55
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
To samo co #4246.
