### ISSUE TITLE
fakty.plportal.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4262]
![2017-11-04 06_32_35-wyrok wloskiego sadu otwiera polsce droge do reparacji wojennych od niemiec _ fa](https://user-images.githubusercontent.com/5884000/32402683-177715f0-c12a-11e7-9de8-6346e96acefe.png)
http://fakty.plportal.pl/artykuly/polska-swiat-historia/wyrok-wloskiego-sadu-otwiera-polsce-droge-do-reparacji-wojennych-od-0

facebook ukryty : O

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.55
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
`fakty.plportal.pl##.block:-abp-contains(FACEBOOK)`
@MajkiIT Reklamy też tu są.

**Comment by MajkiIT** [comment]
@hawkeye116477 a to ukrywa?

`fakty.plportal.pl##[id^="block-simple-adsense-simple-adsense-slot"]`

**Comment by hawkeye116477** [comment]
@MajkiIT Tak
