### ISSUE TITLE
politycznyislam.info

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#4267]
! przyciski social Facebook i Twitter na dole
! https://www.politycznyislam.info
`www.politycznyislam.info##.wpb_start_animation.wpb_bottom-to-top.wpb_animate_when_almost_visible.wpb_content_element.wpb_text_column:nth-of-type(3)`

![](https://s3.dodajfote.pl/2017/11/04/politycznyislam_info_social8ec0fa90f3173eec.png)

**Comment by hawkeye116477** [comment]
`www.politycznyislam.info##.fa-facebook.fa-twitter`

**Comment by gomoku** [comment]
Mój filtr w przeciwieństwie do twojego nie pozostawia dziury/kontenera po reklamie, i dlatego celowo go takiego dałem, naprawdę chcesz zostawiać dziury? Takie jak tu: https://github.com/MajkiIT/polish-ads-filter/issues/4037#issuecomment-341883845 ?

**Comment by hawkeye116477** [comment]
@gomoku Ale tutaj nie było i nie ma reklamy... . Ok, zamienię to na twój filtr.
