### ISSUE TITLE
mgsm.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4270]
Resztki po reklamach

Przykładowy link -> http://www.mgsm.pl/pl/aktualnosci/8294/Asus-Pegasus-4S-premiera-juz-wkrotce.html

`www.mgsm.pl##.text-center.row:-abp-contains(R E K L A M A)`

**Comment by blocker999** [comment]
@hawkeye116477 Tego jest znacznie więcej wiec jak byś mógł to przejrzyj pozostałe zakładki na tej stronie.

**Comment by gomoku** [comment]
Bravo, że w końcu ktoś stosuje https://github.com/MajkiIT/polish-ads-filter/issues/4037#issuecomment-341760968 pkt 3_, tylko, że musi być tak `#?#`:
` www.mgsm.pl#?#.text-center.row:-abp-contains(R E K L A M A)`
bo bez tego znaku zapytania to pod uBO owszem działa, ale już pod ABP wywala:
 `'.text-center.row:-abp-contains(R E K L A M A)' nie jest poprawnym selektorem CSS`

**Comment by hawkeye116477** [comment]
@gomoku No to mamy problem, bo na uBlocku nie działa z `#?#`

**Comment by blocker999** [comment]
Dodam przy okazji jeszcze:

http://www.mgsm.pl/pl/wjakiejsieci/

http://www.mgsm.pl/pl/slowniczek/

http://www.mgsm.pl/pl/katalog/nokia/8/test/1095/Dlugo-oczekiwany-flagowiec-Nokii.html

http://www.mgsm.pl/pl/katalog/nokia/8/galeria/Nokia-8.html

http://www.mgsm.pl/pl/katalog/nokia/8/zdjecia/Nokia-8.html

http://www.mgsm.pl/pl/katalog/nokia/8/ceny/Nokia-8.html

http://www.mgsm.pl/pl/katalog/nokia/8/pytania/Nokia-8.html

http://www.mgsm.pl/pl/katalog/nokia/8/extimageinfo/Nokia-8.html

http://www.mgsm.pl/pl/porownanie/

Oraz w katalogu, po wejściu na dana marke jest resztka, dlatego proponoje dać regułe ogólną bo tego jest wile a ja jako przykład podaje " imcosys " ; 

http://www.mgsm.pl/pl/katalog/imcosys/
mcosys/

**Comment by hawkeye116477** [comment]
Ok, w takim razie tak powinno być lepiej -> `www.mgsm.pl#?#small:-abp-contains(R E K L A M A)`. 
Nie wiem tylko jak te kreski wywalić.

**Comment by blocker999** [comment]
@hawkeye116477 Wchodząc dziś na strone mgsm.pl spotkała mnie miła niespodzianka ale wzamian mamy lotto sms.

![mgsm](https://user-images.githubusercontent.com/23176832/32510254-3fc8d17e-c3f0-11e7-86ab-e216cbaffcb8.png)
