### ISSUE TITLE
focus.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#4271]
! panel social Facebook, Twitter, Instagram + newsletter po prawej (nie wiem czy prenumerata też kwalifikuje się)
! http://www.focus.pl/artykul/trzmiel-czy-bk-czy-dobrze-je-nazywasz
`www.focus.pl##.box-obserwuj-newsletter`

![](https://s3.dodajfote.pl/2017/11/04/focus_social_prawa5df42216b6edda7a.jpg)

**Comment by hawkeye116477** [comment]
Newsletter zostawiamy, od tego jest PPB.
```
www.focus.pl##.social-icon-box
www.focus.pl#?#.box-obserwuj-newsletter > h2:-abp-contains(Obserwuj nas)

```

**Comment by gomoku** [comment]
Ale może nie szalej za bardzo tak z tymi selektorami, bo bardziej zaawansowanych selektorów, ze względów wydajnościowych używa się w ostateczności - wtedy gdy nie da się ukryć elementu za pomocą prostszych, wydajniejszych selektorów, co jest wyraźnie napisane w instrukcji: https://adblockplus.org/filters#elemhide-emulation, przecież wystarczy taki, wydajniejszy selektor: 
`www.focus.pl##.box-obserwuj-newsletter > h2:first-of-type`
Dodatkowo taki selektor można jeszcze dodatkowo uprościći przyspieszyć, zbijając go z drugim selektorem w 1 filtr:
`www.focus.pl##.box-obserwuj-newsletter > h2:first-of-type, .social-icon-box`

No chyba, że swój selektor dałeś żeby był trwalszy, ale nie widzę sensu, bo to nie wp.pl żeby miało się co chwilę coś zmieniać...

**Comment by hawkeye116477** [comment]
@gomoku No właśnie o to chodziło, żeby był trwalszy, układ strony zmienią i może coś się posypać. 
Ale skoro to może powodować lagi to zmienię na twój filtr.

**Comment by gomoku** [comment]
A jaki to link? Bo u mnie jest ciągle po prawej

**Comment by hawkeye116477** [comment]
Częściowo usuwa, ale trzeba też dodać to, żeby schować tą panią -> `www.focus.pl##.box-obserwuj-newsletter > a[href="https://www.instagram.com/focus.pl/"]` 😃 .

**Comment by gomoku** [comment]
Usuwa w całości to co miał usuwać, a babki nie usuwa bo nie wiedziałem, że babka też do usunięcia...więc w tym sensie to częściowo usuwa, ale nie żeby coś było z filtrem nie tak samym w sobie, po prostu trzeba doczepić jeszcze babkę:

To chyba prościej tak tę babkę: 
`www.focus.pl##.box-obserwuj-newsletter > a[target="_blank"]`
No chyba, że chcesz usunąć tylko ten konkretny obrazek/odnośnik, a nie każdy obrazek/odnośnik który się tam pojawi?

Tak czy inaczej jeszcze prościej wszystko razem:
`www.focus.pl##.box-obserwuj-newsletter > h2:first-of-type, .social-icon-box, a[target="_blank"]`
