### ISSUE TITLE
sklep.milicon.eu

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#4272]
! https://sklep.milicon.eu/kolby-c3930
! scrollujący panel/przycisk social Facebook + Koszyk po prawej (nie wiem czy poczta też się kwalifikują, koszyk na pewno bo jest u góry drugi i dodatkowo przy każdym przedmiocie)
Filtr jest taki:  `sklep.milicon.eu###fbBox` ale że na liście social jest już `pl###fbBox` więc zdaje się, że >> `eu,pl###fbBox` + koszyk i przy okazji poczta od razu w razie czego jeśli się kwalifikuje: `sklep.milicon.eu###cartBox, #contactBox`

No chyba, że wszystkie 3 pójdą do jednego filtra:  `sklep.milicon.eu###cartBox, #contactBox, #fbBox`

![](https://s3.dodajfote.pl/2017/11/04/sklep_kolbyc222da44042f4612.jpg)

**Comment by hawkeye116477** [comment]
Czyli tak: `sklep.milicon.eu###fbBox, #instaBox`, a reszta do PPB.
