### ISSUE TITLE
gunfire.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#4273]
! 4.11.2017, 15:54:40 https://gunfire.pl/product-pol-1152198488-Kolba-typu-SF-do-M4.html
! ciasteczka na dole `gunfire.pl###ck_dsclr`
na liście ciasteczek jest już filtr: `###ck_dsclr:not(body):not(html)` ale on nie łapie tego ciasteczka

![](https://s3.dodajfote.pl/2017/11/04/ciasteczka936e417d006ad8e9.jpg)

**Comment by hawkeye116477** [comment]
@gomoku U mnie tego nie ma.

**Comment by MajkiIT** [comment]
@hawkeye116477 u mnie jest wyłapywane przez filtr `###ck_dsclr:not(body):not(html)`

**Comment by xxcriticxx** [comment]
@hawkeye116477 no cookies

**Comment by hawkeye116477** [comment]
@MajkiIT No to tak jak u mnie. A więc to u @gomoku jest coś nie halo.

**Comment by gomoku** [comment]
Problem zdecydowanie występuje, u mnie ciasteczko wyskakuje na najnowszej wersji uBO czyli 1.14.17rc1, a na starszej np. uBO 1.14.17b10 już nie wyskakuje, nie wiem której wersji wy używacie...

**Comment by gomoku** [comment]
Stabilnej ale chyba z nazwy...bo ostatnio uBO jest tak zabugowany, że ja świadomie korzystam z wersji rozwojowych bo często są bardziej stabilne niż te oficjalne, a że teraz akurat trafiło się odwrotnie, to się trafiło, ale przynajmniej nie sypie się to co się sypie na wcześniejszych wersjach. A np. z Firefoxa korzystam z oficjalnej, a nie rozwojowej, bo Firefox oficjalny w przeciwieńdtwie do uBO jest stabilny nie tylko z nazwy.

**Comment by gomoku** [comment]
Stabilnej ale tylko z nazwy....ja świadomie korzystam z wersji rozwojowych uBO, bo uBO jest tak zabugowany, że często wersje rozwojowe są stabilniejsze od oficjalnych, a że się teraz trafiło odwrotnie to się trafiło, a np. z Firefoxa korzystam z wersji oficjalnej bo je st stabilna ni tylko z nazwy.

**Comment by gomoku** [comment]
Stabilnej ale tylko z nazwy....ja świadomie korzystam z wersji rozwojowych uBO, bo uBO jest tak zabugowany, że często wersje rozwojowe są stabilniejsze od oficjalnych, a że się teraz trafiło odwrotnie to się trafiło, a np. z Firefoxa korzystam z wersji oficjalnej bo je st stabilna ni tylko z nazwy.

**Comment by gomoku** [comment]
Stabilnej ale chyba z nazwy...bo ostatnio uBO jest tak zabugowany, że ja świadomie korzystam z wersji rozwojowych bo często są bardziej stabilne niż te oficjalne, a że teraz akurat trafiło się odwrotnie, to się trafiło, ale przynajmniej nie sypie się to co się sypie na wcześniejszych wersjach. A np. z Firefoxa korzystam z oficjalnej, a nie rozwojowej, bo Firefox oficjalny w przeciwieństwie do uBO jest stabilny nie tylko z nazwy.

**Comment by gomoku** [comment]
Co jest do cholery z tymi komentarzami, mój komentarz pojawia się nad twoim zamiast pod twoim, czy to tylko u mnie tak się dzieje, czy github jest równie zabugowany jak uBO.

**Comment by hawkeye116477** [comment]
@gomoku My zawsze używamy wersji stabilnej, obecnie 1.14.16 😄 .

**Comment by gomoku** [comment]
Dlaczego ten komentarz jest nad twoim.

**Comment by xxcriticxx** [comment]
ver 1.14.12

**Comment by hawkeye116477** [comment]
@gomoku Cofnął się w czasie o 2 minuty 😃.

**Comment by gomoku** [comment]
Nom - [Powrót do przyszłości](http://www.filmweb.pl/film/Powr%C3%B3t+do+przysz%C5%82o%C5%9Bci-1985-8823)

From: https://github.com/MajkiIT/polish-ads-filter/issues/4225#issuecomment-342001929 

> @hawkeye116477: Na razie zamykam, skoro problem tymczasowo rozwiązany w uBlock dev.

I ja też tak uczynię, zamykam więc.

**Comment by strict-block** [comment]
#18975
