### ISSUE TITLE
lowking.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4276]
![2017-11-04 18_50_29-ceremonia prezentacji zawodnikow przed ufc 217 - transmisja na zywo - lowking pl](https://user-images.githubusercontent.com/5884000/32407990-2df1a9e6-c191-11e7-8a52-54df01ced6bb.png)
http://www.lowking.pl/ceremonia-prezentacji-zawodnikow-ufc-217-transmisja-zywo/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.56
chrome 62.0.3202.75

**Comment by MajkiIT** [comment]
`lowking.pl###sidebar-wrapper > UL > [id^="text-"]`
