### ISSUE TITLE
kamienskie.info

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4277]
![2017-11-04 18_57_28-kobieta i mezczyzna czy cukrzyca ma plec_ _ kamienskie info](https://user-images.githubusercontent.com/5884000/32408061-40d96c78-c192-11e7-9603-dfbcfbe3644f.png)
http://www.kamienskie.info/kobieta-i-mezczyzna-czy-cukrzyca-ma-plec/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.56
chrome 62.0.3202.75

**Comment by MajkiIT** [comment]
`kamienskie.info##.ads-subpage`
