### ISSUE TITLE
pielegniarki.info.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4280]
![2017-11-04 19_17_00-zapraszamy do lektury najnowszego wydania gazety branzowej ogolnopolska gazeta p](https://user-images.githubusercontent.com/5884000/32408225-c447073a-c194-11e7-9f5b-3b6ffb67f63c.png)
http://www.pielegniarki.info.pl/article/view/id/8146

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.56
chrome 62.0.3202.75

**Comment by xxcriticxx** [comment]
duplicate of https://github.com/MajkiIT/polish-ads-filter/issues/4230
