### ISSUE TITLE
biznesalert.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4282]
![2017-11-04 19_24_18-krajowe rozwiazania w zakresie bezpieczenstwa infrastruktury energetycznej - biz](https://user-images.githubusercontent.com/5884000/32408282-c7f611c2-c195-11e7-8df3-32c7c66fb279.png)
http://biznesalert.pl/events/event/krajowe-rozwiazania-zakresie-bezpieczenstwa-infrastruktury-energetycznej/

strona ukryta

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.56
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
@MajkiIT Reguła do wywalenia -> `biznesalert.pl##.container > .row:nth-of-type(5)`.

**Comment by MajkiIT** [comment]
`biznesalert.pl##A[target="_blank"] > IMG.img-responsive`
