### ISSUE TITLE
itporady.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4285]
dhosting na dole 

https://itporady.pl/android-ios-wp/zawieszony-iphone-nie-reaguje-na-dotyk-co-zrobic/

**Comment by hawkeye116477** [comment]
`itporady.pl##a[href="//itporady.pl/go/dhosting"]`

Coś im te iPhony ostatnio nie wychodzą, SMSy resetowały iPhony, iPhone nie umiał dodawać (no ale w końcu chyba już się nauczył 😺 ), a teraz jeszcze na dotyk nie reagują 😃 .

**Comment by MajkiIT** [comment]
`itporady.pl##A > IMG.img-responsive.center-block`
