### ISSUE TITLE
ifon.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4288]
cookies

Polityka Cookies. Informacje zarejestrowane w plikach 'cookies' używamy w celu dostosowania naszych serwisów do indywidualnych potrzeb użytkowników. Możesz zmienić ustawienia dotyczące 'cookies' w swojej przeglądarce internetowej. Jeżeli pozostawisz aktualne ustawienia bez zmian 'cookies' zostaną zapisane w pamięci urządzenia. Zmiana ustawień plików 'cookies' może ograniczyć funkcjonalność serwisu. Zapoznaj się z

**Comment by hawkeye116477** [comment]
`www.ifon.pl##.region-top.region
`
