### ISSUE TITLE
my-mobile.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#4301]
Na stronie głównej są dwie reguły do odblokowania :
 ###main-right > center i ||www.my-mobile.pl/html/*.jpg$image
oraz jedna do sociali
``[`www.my-mobile.pl###text-376458011`
](url)`![bez tytulu](https://user-images.githubusercontent.com/23176832/32415327-80146b9e-c238-11e7-908d-657ab1584eec.png)

`

**Comment by hawkeye116477** [comment]
Tak chyba będzie lepiej -> `www.my-mobile.pl##.widget_text.widget` 😄 .

**Comment by blocker999** [comment]
@hawkeye116477 chodzi ci oto okienko z fejsem?, przecież to blokuje Fanboy's Social Blocking List, jeśli widzisz coś innego to daj screena.

**Comment by hawkeye116477** [comment]
@blocker999 
![screenshot_20171105_214440](https://user-images.githubusercontent.com/19818572/32418936-8e2acda6-c272-11e7-9249-24180799b271.png)

**Comment by blocker999** [comment]
@hawkeye116477 A faktycznie więc to i do sociali oraz do PB.
