### ISSUE TITLE
animezone.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4311]
![2017-11-06 12_14_04-animezone pl - twoja strefa anime online pl](https://user-images.githubusercontent.com/5884000/32438789-1b3b3806-c2ec-11e7-9d2f-d13e2a504b2b.png)

po wyczyszczeniu cookie/cache i przejściu na drugą stronę

![2017-11-06 12_15_30-chrome-extension___cjpalhdlnbpafiamejdnhcphjbkeiagm_document-blocked html_detail](https://user-images.githubusercontent.com/5884000/32438817-35d9283a-c2ec-11e7-91ab-93c3d634b808.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.58
chrome 62.0.3202.75

**Comment by xxcriticxx** [comment]
popup ads regex lapie

**Comment by mat41997** [comment]
@xxcriticxx to nie popup, to anty adblock.

**Comment by gomoku** [comment]
`animezone.pl##script:inject(noeval.js)`

**Comment by MajkiIT** [comment]
@mat41997 to reklamy :P pojawiają się reklamy w nowym oknie.

**Comment by mat41997** [comment]
@MajkiIT nie w nowym, a w tym samym i tylko wtedy gdy masz adblocka.

**Comment by MajkiIT** [comment]
@mat41997 Ja mam w nowym oknie to ==> https://screenshots.firefox.com/9Djx5inknv9KXQvo/application-77my.com

**Comment by mat41997** [comment]
ja mam dodatek popup blocker
https://add0n.com/popup-blocker.html

**Comment by gomoku** [comment]
> @mat41997: to nie popup, to anty adblock.


Dokładnie a podany przeze mnie filtr go unieszkodliwiał, ale już tego nie robi, bo albo coś zmienili na stronie albo ma to związek z nową wersją uBO.

**Comment by mat41997** [comment]
gomoku jak już się ze sobą zgadzamy, to możesz mnie odblokować : P

**Comment by gomoku** [comment]
Te 2 filtry załatwiają sprawę:
`animezone.pl##script:inject(noeval.js)`
`animezone.pl##script:inject(abort-on-property-read.js, o6c6e)`
