### ISSUE TITLE
eurogamer.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4315]
![2017-11-06 14_34_45-rozbudowany mod do gothic 2 obiecuje ponad 250 godzin rozgrywki _ eurogamer](https://user-images.githubusercontent.com/5884000/32443548-af161218-c2ff-11e7-912a-a5ff832722bf.png)
http://www.eurogamer.pl/amp/2017-11-06-rozbudowany-mod-do-gothic-2-obiecuje-ponad-250-godzin-rozgrywki

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.58
chrome 62.0.3202.75

**Comment by MajkiIT** [comment]
@mat41997 u mnie ok.
@hawkeye116477 zekrniesz?

**Comment by hawkeye116477** [comment]
@MajkiIT Pod udostępnij jest sporo wolnego miejsca, gdyż tam były reklamy.
`www.eurogamer.pl##.container:nth-of-type(2) > .i-amphtml-unresolved.amp-unresolved.i-amphtml-layout-size-defined.i-amphtml-layout-responsive.amp-notbuilt.i-amphtml-notbuilt.i-amphtml-element`

**Comment by MajkiIT** [comment]
@hawkeye116477 dziękuję

**Comment by xxcriticxx** [comment]
strona dziala
