### ISSUE TITLE
autokult.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4320]
![2017-11-06 15_05_04-swieca zarowa pelni wiecej funkcji niz myslisz](https://user-images.githubusercontent.com/5884000/32444727-e871861a-c303-11e7-959d-28b32a57c732.png)
https://autokult.pl/24689,swieca-zarowa-pelni-wiecej-funkcji-niz-myslisz

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.58
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
@MajkiIT Reklamy to ja nie widzę, ale ciastka są i coś dla PPB 😃 .
Ciastka -> `##.cookie-disclaimer:not(body):not(html)`

**Comment by xxcriticxx** [comment]
zero reklam ale mam cookies na dole 

@hawkeye116477 mial byc nato fix?

![capture](https://user-images.githubusercontent.com/15007183/32462886-010dac8a-c309-11e7-93e5-56c711861e9a.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Cookie są, ale tylko na przeglądarkach Chromium-based. Fix już niby jakiś był, ale najwyraźniej nadal coś jest nie tak, coś kombinują, bo mimo, że dałem na to regułę, to i tak to ciągle jest, a korzystam z uBlocka dev.
A no i reklama teraz mi się pojawiła.

**Comment by xxcriticxx** [comment]
Ja mam chyba dobre ciastka bo dalej reklam nie widzę

**Comment by gomoku** [comment]
> @hawkeye116477: a korzystam z uBlocka dev.

Z najnowszej wersji? Mi np. dzisiaj na https://fokusfashion.com/ na Opera 48 + uBO 1.14.17rc1 wyskoczyło ciastko , dopiero gdy zaktualizowałem do1.14.17rc2 to ciastko zniknęło, a teraz już nawet jest wersja uBO 1.14.19b0.

**Comment by hawkeye116477** [comment]
@gomoku 1.14.17rc2. A tego mechanika to już wczoraj schowałem, ale inną regułą -> `||widgets.dobrymechanik.pl/grupawp/autokult/search_mechanic.js$script`. Więc zaktualizuj PPB i się schowa.

**Comment by gomoku** [comment]
Ale ten widżet wyskakuje dalej sprawdź sobie, nie wiem, może to inny widżet dzisiaj jest albo zmutował.

**Comment by hawkeye116477** [comment]
@gomoku Ok. Wygląda na to, że to jest drugi widget na stronie głównej.
