### ISSUE TITLE
ministerstwonaukijazdy.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4324]
![2017-11-06 15_27_52-ministerstwo nauki jazdy - pozaresortowy serwis o nauce jazdy](https://user-images.githubusercontent.com/5884000/32445765-17ff5f62-c307-11e7-9746-707636ecbcd0.png)

![2017-11-06 15_28_25-czy bedzie zwolnienie z oplaty egzaminacyjnej_ - ministerstwo nauki jazdy](https://user-images.githubusercontent.com/5884000/32445786-28bd31a8-c307-11e7-84b5-325ca8b86460.png)
http://ministerstwonaukijazdy.pl/bedzie-zwolnienie-oplaty-egzaminacyjnej/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.58
chrome 62.0.3202.75

**Comment by MajkiIT** [comment]
@mat41997 najnowsze firmy też?

**Comment by xxcriticxx** [comment]
ja prawo jazdy juz posiadam wiec omijam takie strony
