### ISSUE TITLE
nportal.no

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4325]
![2017-11-06 15_30_50-nportal no - film kieslowskiego uznany za drugi najlepszy film wszech czasow](https://user-images.githubusercontent.com/5884000/32445923-826e8a3a-c307-11e7-95bb-acffe1ae557a.png)
http://www.nportal.no/articles/3778-film-kieslowskiego-uznany-za-drugi-najlepszy-film-wszech-czasow

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.58
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
`www.nportal.no###fb-overlay, .social`

**Comment by hawkeye116477** [comment]
@MajkiIT Tu są też reklamy -> `www.nportal.no##.commercial-top, #commercial-300, .three-commercials`.
