### ISSUE TITLE
optyczne.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4328]
![2017-11-06 16_36_14-optyczne pl - testy aparatow testy obiektywow testy lornetek inne testy apar](https://user-images.githubusercontent.com/5884000/32449010-c07a05e4-c310-11e7-969b-a4dfa0fbcd9e.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.58
chrome 62.0.3202.75

**Comment by MajkiIT** [comment]
@mat41997 partnerzy i oferta też?
