### ISSUE TITLE
playpuls.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#4332]
Czarna strona, dopiero jak się wyłączy PL to pojawia się filmik.

Przykładowy link:

http://playpuls.pl/seriale/lombard-zycie-pod-zastaw/vod/lombard-zycie-pod-zastaw-odc-1-s0-e1

**Comment by MajkiIT** [comment]
@blocker999 poprawione

**Comment by jspenguin2017** [comment]
Broke. See https://github.com/uBlockOrigin/uAssets/issues/3256

**Comment by MajkiIT** [comment]
@jspenguin2017 Thanks
https://github.com/MajkiIT/polish-ads-filter/commit/aec76491b748aa9a262fd5fe3a0643eb89a99085#diff-711027ed0794992ae3b8710d874f3df7
