### ISSUE TITLE
grafmag.pl

### ISSUE THREAD

**Issue by userOperaFF** [MajkiIT/polish-ads-filter#4333]
```
http://grafmag.pl/artykuly/kolory-w-projektowaniu-znaczenie-i-odbior-barwy-czarnej/
```
Nie można przeczytać artykułu.

### Co trzeba zrobić aby został wycięty element funkcjonalny
1. mieć aktywne podstawowe filtry + Polski w uBlock
2. otworzyć stronę

### Twoja konfiguracja
**Przeglądarka:** Firefox 49 / Opera 48

**Operating system:** Windows 7

**Blocker:** uBlock Origin 1.14.16 / 1.14.8

**Używane filtry:**
1. jw. standardowe + Polski w uBlock
2. filtr cookies pl

### Zrzut ekranu

|włączony uBlock (brak artykułu)| wyłączony uBlock (jest artykuł)|
|---|---|
|![z](https://i.imgur.com/PtRvNvC.png)|![bez](https://i.imgur.com/QI3PsAV.png)|

**Comment by MajkiIT** [comment]
@userOperaFF poprawione. Dzięki
