### ISSUE TITLE
nowiny24.pl

### ISSUE THREAD

**Issue by agncup** [MajkiIT/polish-ads-filter#4334]
Usuńcie proszę ten filtr, bo to blokuje również menu na stronie
`nowiny24.pl##.hide-for-medium-down`

Jeśli już miałaby być blokowana reklama zgłoszona w [https://github.com/MajkiIT/polish-ads-filter/issues/2884](2884) to należałoby dać `nowiny24.pl###dfp-prawa1`

**Comment by gomoku** [comment]
OK jak widać trzeba będzie usunąć: `nowiny24.pl##.hide-for-medium-down` 
ale nie rozumiem po co dodawać: `nowiny24.pl###dfp-prawa1`
skoro już jest reguła na to: `pl##.ppa-slot`

( blokowany element to `<div id="dfp-prawa1" class="ppa-slot">` )

**Comment by agncup** [comment]
Tej reguły `pl##.ppa-slot ` nie zauważyłam, to zgadzam się nie trzeba dodawać :)
