### ISSUE TITLE
Cookies na filmikach z twittera

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#4338]
Przed filmikem z twittera jest info o cookies.

Przykład:

http://www.wirtualnemedia.pl/artykul/truskawka-na-torcie-od-tomasza-hajto-z-polsatu-trafila-do-spotu-tvp-sport-wideo

![tw](https://user-images.githubusercontent.com/23176832/32515234-d232411c-c3ff-11e7-8026-27815220deb8.png)

**Comment by hawkeye116477** [comment]
To chyba raczej coś dla @MajkiIT albo kogoś innego, ja nie potrafię blokować elementów w playerze bez chowania playera 😄 .

**Comment by blocker999** [comment]
Tak tylko to dodałem może @F4z da rade rozgryźć a jak nie to trudno,

**Comment by hawkeye116477** [comment]
Niekoniecznie @F4z, @gwarser też jest mistrz 😄

**Comment by blocker999** [comment]
Może być i @gwarser

**Comment by gwarser** [comment]
Jestem za cienki na to.

Z tego co mi się wydaje: 
 - ciężko się dostać do kodu od strony window by cokolwiek zablokować (zaciemnianie i domknięcia)
 - kod jest na promisach i jak jedna zawiedzie to i tak komunikat się pokaże w funkcji podpiętej do odrzucenia promisy
 - jak by była funkcja do dodawania ciasteczek, to może by pomogło ustawienie eu_cn 1
 - jak by była funkcja kasująca noda to może by się funkcja od ciastek nie odpaliła, bo nie miała by się na czym pokazać

**Comment by blocker999** [comment]
Ok dzięki @gwarser , zaraz jaśniej a co myślicie o podaniu tego do pingwina od protektora?

**Comment by mat41997** [comment]
@blocker999 ja tego nie podam bo mnie pingwin już banem straszy.

**Comment by MajkiIT** [comment]
sprawdzicie ?
`||platform.twitter.com/widgets/twitter_cookies.html$subdocument,domain=www.wirtualnemedia.pl`

**Comment by hawkeye116477** [comment]
@MajkiIT Niestety to nie działa. Czyli potrzebna jest pomoc wielkiego mistrza @F4z 😄 .

**Comment by hawkeye116477** [comment]
@MajkiIT Niestety to nie działa. Czyli potrzebna jest pomoc wielkiego mistrza @F4z 😄 .
@mat41997 To co ty taki rozrabiaka 😃 .
