### ISSUE TITLE
bankobranie.blogspot.com

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#4341]
Dużo syfu na:
http://bankobranie.blogspot.com/2017/04/bz-wbk-dodatkowe-premie-w-programie-polecaj-bank.html

! reklama u góry + popup-prawa-dół +  newsletter +  2 popupy: anty-adblock & polub + panel social po lewej + 9 reklam (7 po prawej i 2 na dole) + panel social po prawej
`bankobranie.blogspot.com###topHintBar, #hint, #topNewsletter, #overlay, #sideSocial, .widget.Image, #logoSocial`

Jeśli chodzi o `#logoSocial` to wycina cały panel a tam też jest przycisk RSS nie wiem czy zostawiamy go, ale jeśli tak to:
`bankobranie.blogspot.com###topHintBar, #hint, #topNewsletter, #overlay, #sideSocial, .widget.Image, #logoSocial > .social > li:nth-child(-n+4)`

Jeśli chodzi o `#hint` i `#topHintBar`, to można alternatywnie w taki sposób:
`bankobranie.blogspot.com##script:inject(abort-on-property-read.js, showHint)`
`bankobranie.blogspot.com##script:inject(abort-on-property-read.js, showTopBar)`

Część filtrów pewnie pójdzie na PopupBlocker w tym jeszcze nagłówek do usadzenia.

! 1 reklama u góry + 7 po prawej ( w tym 1 duża)
![](https://s3.dodajfote.pl/2017/11/08/3_reklama23d9af6c3ef4064d.png)

! 7 reklam po prawej ( w tym 1 duża)
![](https://s3.dodajfote.pl/2017/11/08/4_rek_prawa4056e7265fd53cb9.png)

! 2 reklamy na dole
![](https://s3.dodajfote.pl/2017/11/08/5_rek_dol98937ff05729bfaf.png)

! popup antyadblock + newsletter + panel social po prawej
![](https://s3.dodajfote.pl/2017/11/08/2_panel_social_po_prawej_oraz_popup_antyadblock78e5e1f91fde874c.png)

! panel social po lewej + popup polub środek + popup-prawa-dół
![](https://s3.dodajfote.pl/2017/11/08/1_panel_social_po_lewej_popup_antyadblock_popup_prawa_dol49f0385bfea19fda.png)

**Comment by hawkeye116477** [comment]
Antyadblock -> `bankobranie.blogspot.com##.adblockNfo`

**Comment by gomoku** [comment]
Widzę, że dałeś `#overlay` na social, ale to chyba ma iść na PopupBlocker, bo to ukrywa te 2 białe popupy (obrazek 4 i 5), no chyba, że ten drugi popup celowo zaliczyłeś bardziej do kategorii social niż popup, tylko pytam bo nie jestem pewien.

A te twoje reguły: `.fb, .in, .tw, .gp`, które dałeś na social zamiast moich `#sideSocial, #logoSocial > .social > li:nth-child(-n+4)` to zostawiają po lewej:

![](https://s3.dodajfote.pl/2017/11/10/hydhdtrc5221fece3da7af5.png)

**Comment by hawkeye116477** [comment]
@gomoku Co do overlay, to tak, celowo zaliczyłem.
A co do tego paska po lewej, no to RSS i e-mail powinien zostać, dlatego dałem inną regułę. A #sideSocial trafiło do PPB.

**Comment by gomoku** [comment]
Sorry, zaktualizowałem POL listę i Social listę, a przeoczyłem zakutalizować PopupBlocker i dlatego mi nie zbierało tego panela po lewej, więc to co napisałem już nieaktualne, więc te zmiany, które dałeś nie są konieczne, więc możesz je cofnąć jeśli chcesz.
