### ISSUE TITLE
pogoda.onet.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#4342]
https://pogoda.onet.pl/artykuly/nadciaga-orkan-marcin-w-weekend-przyniesie-ulewy-i-wichury/qervg1l

![20171108-170324-001](https://user-images.githubusercontent.com/9846948/32559238-fba8f2be-c4a6-11e7-9a9a-c20d07585fad.png)

```
pogoda.onet.pl##.ssListaContainer
```

**Comment by xxcriticxx** [comment]
@FadeMind co to jest orkan?

**Comment by xxcriticxx** [comment]
@FadeMind co za organy ty mi tu podajesz

**Comment by hawkeye116477** [comment]
@xxcriticxx Orkan to taki wiatr 😛 .

**Comment by xxcriticxx** [comment]
@hawkeye116477 huragan? 🌪

**Comment by hawkeye116477** [comment]
@xxcriticxx To nie do końca to samo.
http://natemat.pl/84491,czym-rozni-sie-orkan-od-huraganu-a-huragan-od-cyklonu-wyjasniamy

**Comment by xxcriticxx** [comment]
@hawkeye116477 Organy kościelne

**Comment by hawkeye116477** [comment]
@xxcriticxx  Zacytuję Wikipedię 

> orkany, czyli wiatry, których prędkość przekracza 33 m/s

A ten Marcin to ściema, nazwa zmyślona i tyle 😃 .
http://www.expressbydgoski.pl/pogoda/a/orkan-marcin-nie-przyjdzie-powod-orkan-marcin-to-bzdura,12659912/

**Comment by xxcriticxx** [comment]
czyli b.s.
