### ISSUE TITLE
poradnikzdrowie.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4345]
![2017-11-08 21_30_40-zdrowie odchudzanie diety ciaza psychologia - poradnikzdrowie pl](https://user-images.githubusercontent.com/5884000/32572987-bd80d800-c4cc-11e7-971b-c70e25d9e151.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.60
chrome 62.0.3202.89

**Comment by gzenio22** [comment]
U mnie na (Chr)operze tez jest

poradnikzdrowie.pl##.shopping

**Comment by hawkeye116477** [comment]
Social -> `www.poradnikzdrowie.pl##.big_socials_fb, .big_socials_tw, .big_socials_gp`
