### ISSUE TITLE
wlaczoszczedzanie.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4346]
![2017-11-08 22_01_31-wlacz oszeczdzanie - jak oszczedzac i zyc w zgodzie z przyroda](https://user-images.githubusercontent.com/5884000/32574167-ad21ac74-c4d0-11e7-9c81-b6e438137587.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.60
chrome 62.0.3202.89

**Comment by hawkeye116477** [comment]
```
wlaczoszczedzanie.pl##a[href="https://www.facebook.com/wlaczoszczedzanie/"] > .fm-icon
wlaczoszczedzanie.pl##a[href^="https://www.youtube.com/channel/UCEO8Mm72kk79BtIHoEAOlXQ/playlists"] > .fm-icon
wlaczoszczedzanie.pl##a[href="https://pl.pinterest.com/wlaczoszczedzanie/"] > .fm-icon
wlaczoszczedzanie.pl##a[href="https://twitter.com/LukasPajak"] > .fm-icon
```
