### ISSUE TITLE
pomyslnawszystko.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4347]
![2017-11-08 22_05_33-pomysl na wszystko _ znajdziesz pomysl na wszystko](https://user-images.githubusercontent.com/5884000/32574285-05ddbab0-c4d1-11e7-80f3-82991d494f9e.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.60
chrome 62.0.3202.89

**Comment by gzenio22** [comment]
pomyslnawszystko.pl###secondary

powinno pomoc

**Comment by mat41997** [comment]
@gzenio22 jak dajesz jakąś regułę to możesz używać `bez spacji` tu text `bez spacji`

**Comment by xxcriticxx** [comment]
@gzenio22 myslalem ze juz zapomniales onas

**Comment by gzenio22** [comment]
a gdzie tam :D zyje tylko czasu malo ostatnio :)

**Comment by xxcriticxx** [comment]
@gzenio22 jak z netem?

**Comment by gzenio22** [comment]
@xxcriticxx 15 Grodnia bede mial nowy

**Comment by xxcriticxx** [comment]
Minimum 50 Mb up 25 down

**Comment by mat41997** [comment]
@xxcriticxx ja mam radiowy 6 up i 1down

**Comment by xxcriticxx** [comment]
@mat41997 slow!

**Comment by hawkeye116477** [comment]
Ja też mam radiowy, ale pobieranie 20 Mb (ale czasem nawet do 21 Mb dochodzi), a wysyłanie niby 2 Mb, ale speedtest pokazuje 3 Mb, a czasem 4 Mb. Mógłbym i mieć też fiber, ale od Orange, ale słyszałem, że od niech to kiepsko chodzi, więc wolałbym nie zamieniać 😃 .

**Comment by MajkiIT** [comment]
@hawkeye116477 możesz mieć swiatło ftth od lokalnego dostawcy :P
