### ISSUE TITLE
kantorbitcoin.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4348]
![2017-11-08 22_22_27-hardfork bitcoin segwit2x odwolany - kantor bitcoin](https://user-images.githubusercontent.com/5884000/32575100-5db0c85c-c4d3-11e7-8812-19c5f1a9cff2.png)
https://kantorbitcoin.pl/hardfork-bitcoin-segwit2x-odwolany/

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.60
chrome 62.0.3202.89

**Comment by hawkeye116477** [comment]
@mat41997 Kupujesz Bitcoiny czy sprzedajesz?

**Comment by mat41997** [comment]
@hawkeye116477 tylko kupuje XD
