### ISSUE TITLE
ddz.doba.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4349]
![2017-11-08 22_53_04-doba pl dobrze poinformowani](https://user-images.githubusercontent.com/5884000/32576587-aa776a3e-c4d7-11e7-9153-61ab33aaf880.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.60
chrome 62.0.3202.89

**Comment by hawkeye116477** [comment]
Social -> `ddz.doba.pl###panel, .social`
Reklamy:
```
ddz.doba.pl##a[href^="http://beta.doba.pl/adserver"]
ddz.doba.pl##.sliderads
```
