### ISSUE TITLE
bitcoin-info.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4351]
![2017-11-09 03_13_34-bitcoin-info pl](https://user-images.githubusercontent.com/5884000/32585098-0f8a2a78-c4fc-11e7-8394-d4bcd07c20a7.png)

![2017-11-09 03_13_48-bitcoin-info pl](https://user-images.githubusercontent.com/5884000/32585104-133d9bb4-c4fc-11e7-80e0-ff154e45bd18.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by hawkeye116477** [comment]
@mat41997 Co ty się masz z tymi bitcoinami, zamierzasz kopać i sprawdzasz czy się opłaca czy jak 😃 ?

**Comment by MajkiIT** [comment]
`bitcoin-info.pl##IMG[src^="/data/banner/"]`

**Comment by mat41997** [comment]
@hawkeye116477 planuje stworzyć własną kryptowalutę.
