### ISSUE TITLE
odkryjbitcoin.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4353]
![2017-11-09 03_33_09-bitcoin_ co to jest i jak na tym zarobic_](https://user-images.githubusercontent.com/5884000/32585683-ec387838-c4fe-11e7-9af8-794a03670dd4.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`odkryjbitcoin.pl##A[target="_blank"] > IMG`
