### ISSUE TITLE
gieldykryptowalut.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4354]
![2017-11-09 03_45_44-gieldy kryptowalut kryptowaluty bitcoin ethereum ranking](https://user-images.githubusercontent.com/5884000/32585992-82ad588c-c500-11e7-87dd-41705e04a608.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`gieldykryptowalut.pl##A[target="_blank"] > IMG`
