### ISSUE TITLE
cashowsky.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4355]
![2017-11-09 03_58_10-portfel btc i gielda bitbay jak zaczac z bitcoinami _ ca howsky pl](https://user-images.githubusercontent.com/5884000/32586334-4c9bd924-c502-11e7-8934-6fac64337ad1.png)
http://cashowsky.pl/jak-zaczac-z-bitcoinami

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`cashowsky.pl##IMG[alt^="Baner"]`
