### ISSUE TITLE
btc-jak-bitcoin.blog.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4356]
![2017-11-09 04_00_25-dobry na wszystko _ btc jak bitcoin](https://user-images.githubusercontent.com/5884000/32586395-958b83aa-c502-11e7-9fd2-fbfdec421379.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`btc-jak-bitcoin.blog.pl##A > IMG[width="250"]`
