### ISSUE TITLE
prostaekonomia.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4357]
![2017-11-09 04_03_27-ekonomia _ oszczedzanie _ gospodarka _ nauka _ prosta ekonomia](https://user-images.githubusercontent.com/5884000/32586469-fdd1ec6a-c502-11e7-924b-6966162719d7.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`prostaekonomia.pl###layerslider_2`
