### ISSUE TITLE
mobilitynews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4358]
![2017-11-09 04_17_36-home - mobilitynews pl](https://user-images.githubusercontent.com/5884000/32586782-03bf4030-c505-11e7-8b6f-9393ffbfe598.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by hawkeye116477** [comment]
`mobilitynews.pl##.a-single, .banner_header`
