### ISSUE TITLE
legiobiznes.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4360]
![2017-11-09 04_26_25-legiobiznes pl _ marketing social media bezpieczenstwo it e-biznes zarabianie](https://user-images.githubusercontent.com/5884000/32587006-5b852ef0-c506-11e7-83db-ccf221b1632c.png)

![2017-11-09 04_26_55-legiobiznes pl _ marketing social media bezpieczenstwo it e-biznes zarabianie](https://user-images.githubusercontent.com/5884000/32587015-6323f736-c506-11e7-9d7e-b89b1afc9d88.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
```
legiobiznes.pl##A[target="_blank"] > IMG[style="max-width: 100%;"]
legiobiznes.pl###widget_sp_image-9 
```
