### ISSUE TITLE
kkozle.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4362]
![2017-11-09 04_34_47-imprezy kedzierzyn-kozle - kkozle pl](https://user-images.githubusercontent.com/5884000/32587213-67786668-c507-11e7-8d80-c83cdcd3efa8.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`kkozle.pl##.adboxbline`
