### ISSUE TITLE
kryptowalutykoparka.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4363]
![2017-11-09 04_37_13-bitcoin newsy kurs handel wydobycie](https://user-images.githubusercontent.com/5884000/32587268-b68d2e5a-c507-11e7-9509-5a74ac5d07b6.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`kryptowalutykoparka.pl###text-14`
