### ISSUE TITLE
lwowecki.info

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4365]
![2017-11-09 06_27_18-home](https://user-images.githubusercontent.com/5884000/32589824-2bb602f6-c517-11e7-88a7-0d26bc6c61d0.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`lwowecki.info##.banner_box_frame`
