### ISSUE TITLE
bielsko.info

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4366]
![2017-11-09 06_33_49-bielsko info - swieze spojrzenie na miasto](https://user-images.githubusercontent.com/5884000/32589960-02008e4e-c518-11e7-8f3f-b713f4a97c0c.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`bielsko.info##DIV[data-ads-id] > [class$="970x250"]`
