### ISSUE TITLE
tychy.info

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4367]
![2017-11-09 06_37_09-tychy info - swieze spojrzenie na miasto](https://user-images.githubusercontent.com/5884000/32590027-702e4eba-c518-11e7-9da1-9e6b8b0ce2cc.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`tychy.info##[data-ads-id] > DIV[class$="970x250"]
`
