### ISSUE TITLE
inowroclaw.info.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4368]
![2017-11-09 06_42_13-inowroclaw info pl - mobilni do bolu](https://user-images.githubusercontent.com/5884000/32590202-6b27325a-c519-11e7-834b-3166acfb9ab9.png)

![2017-11-09 06_44_03-inowroclaw info pl - mobilni do bolu](https://user-images.githubusercontent.com/5884000/32590204-6e71b57a-c519-11e7-8de9-89f44405bf30.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
```
inowroclaw.info.pl##A[target="_blank"] > IMG
inowroclaw.info.pl##CENTER > A > IMG
```
