### ISSUE TITLE
info.elblag.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4369]
![2017-11-09 06_46_28-info elblag pl - elblaski dziennik internetowy](https://user-images.githubusercontent.com/5884000/32590251-c413f358-c519-11e7-89f3-037b007db06a.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
@mat41997 nadal to masz?

**Comment by mat41997** [comment]
mam, mam
![2017-11-09 20_04_12-info elblag pl - elblaski dziennik internetowy](https://user-images.githubusercontent.com/5884000/32624328-335e60ee-c589-11e7-8868-08376efac2b1.png)

![2017-11-09 20_05_17-_halas jest nie do zniesienia_ mieszkancy osiedla debowa marza o ciszy - info e](https://user-images.githubusercontent.com/5884000/32624360-56ab47ec-c589-11e7-8646-7a4f72af0654.png)
https://info.elblag.pl/37,52246,Halas-jest-nie-do-zniesienia-Mieszkancy-osiedla-Debowa-marza-o-ciszy.html

**Comment by MajkiIT** [comment]
@xxcriticxx @hawkeye116477 zerkniecie u siebie?

**Comment by hawkeye116477** [comment]
@MajkiIT Resztki po reklamach + siłownia -> `info.elblag.pl##.ADinfo, #banner-33`
