### ISSUE TITLE
infostrow.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4370]
![2017-11-09 06_49_32-infostrow pl - najwiekszy portal informacyjno - rozrywkowy w regionie](https://user-images.githubusercontent.com/5884000/32590345-3a8a0202-c51a-11e7-82e3-c35215d25a3f.png)
http://infostrow.pl/strona-glowna

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
@mat41997 U mnie jest ok. @hawkeye116477 @xxcriticxx zerkniecie?

**Comment by gzenio22** [comment]
u mnie rozjechane tez jest

**Comment by hawkeye116477** [comment]
Ja tam tylko przez chwilę mam taki efekt, a jak już strona się do końca wczyta to jest ok.

**Comment by userOperaFF** [comment]
U mnie się rozwala i załadowanie się do końca nic nie daje.

**Comment by xxcriticxx** [comment]
@MajkiIT u mnie sie nie laduje do konca duzo lapie `.pl/*/ads/`

@hawkeye116477  script sie caly czas laduje `/cookiesEU-latest.min.js`

**Comment by hawkeye116477** [comment]
`||ciasteczka.eu/cookiesEU-latest.min.js`

**Comment by hawkeye116477** [comment]
@xxcriticxx To już było 2 lata temu zdaje się zgłaszane, ciekawe tylko dlaczego MajkiIT dał kosmetyczną zamiast filtru sieciowego.
