### ISSUE TITLE
dotnetomaniak.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4372]
![2017-11-09 07_04_56-dotnetomaniak pl - najnowsze artykuly o net](https://user-images.githubusercontent.com/5884000/32590784-59d97f78-c51c-11e7-8c56-3c54ebb6a70b.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`dotnetomaniak.pl##.recommend-left-column`
