### ISSUE TITLE
zywiecinfo.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4374]
![2017-11-09 07_13_47-zywiec _ informacje _ aktualnosci _ wydarzenia _ historia - zywiecinfo pl](https://user-images.githubusercontent.com/5884000/32591023-b20a2c14-c51d-11e7-9cec-f6f0326d3fe1.png)

![2017-11-09 07_14_17-zywiec _ informacje _ aktualnosci _ wydarzenia _ historia - zywiecinfo pl](https://user-images.githubusercontent.com/5884000/32591030-b6e9a854-c51d-11e7-83ed-dff7dd705bfa.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
```
zywiecinfo.pl##.col-md-12
zywiecinfo.pl##.promoted.wow.fadeIn
zywiecinfo.pl###blockadblock
```
