### ISSUE TITLE
baltic.info.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4375]
![2017-11-09 07_19_46-baltic info pl - opinie tworza rzeczywistosc](https://user-images.githubusercontent.com/5884000/32591189-6c5bea4e-c51e-11e7-80ec-1811623f9504.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`baltic.info.pl##IMG[style="display: block; margin-left: auto; margin-right: auto;"]`
