### ISSUE TITLE
hokej.net

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4376]
push + pushAd

Notyfikacje
Czy chcesz otrzymywać najważniejsze informacje? Włącz powiadomienia:

**Comment by MajkiIT** [comment]
`||hock.pushad.io^`

**Comment by xxcriticxx** [comment]
`||*.pushad.io^`

@MajkiIT to bendzie dzialac? jest wiecej stron stym poczatek strony pokazuje sie tam gdzie `*`

**Comment by MajkiIT** [comment]
`||pushad.io^`
