### ISSUE TITLE
legalniewsieci.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4377]
![2017-11-09 17_04_53-bezpieczenstwo i zagrozenia w sieci - portal legalniewsieci pl](https://user-images.githubusercontent.com/5884000/32615562-6100756e-c570-11e7-80eb-81d13b2afd6c.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by gzenio22** [comment]
'legalniewsieci.pl##.col-sm-6.col-xs-12:nth-of-type(2) > .col-xs-12:nth-of-type(3)'

**Comment by MajkiIT** [comment]
`legalniewsieci.pl##.col-xs-12.col-sm-6.filelist + .col-xs-12`
