### ISSUE TITLE
mediagroupinfo.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4379]
![2017-11-09 17_35_42-media group info portal informacyjny](https://user-images.githubusercontent.com/5884000/32617121-7110e7b4-c574-11e7-8a74-7c326c4c852f.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`mediagroupinfo.pl##DIV > IMG[src^="http://"][alt]:last-child`
