### ISSUE TITLE
www.zeiss.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#438]
cookies 

to hyba stacionarne ale mozna schowac

Nasza witryna wykorzystuje pliki cookies w celu świadczenia Państwu usług na najwyższym poziomie, m.in. w celach statystycznych oraz odpowiedniego dostosowania serwisu do preferencji użytkowników. Dalsze korzystanie z naszej witryny oznacza zgodę na wykorzystywanie plików cookies zgodnie z naszą polityką prywatności. Warunki przechowywania i dostępu do plików cookies można zmienić w ustawieniach przeglądarki.

**Comment by MajkiIT** [comment]
Wartość statyczna.
