### ISSUE TITLE
zakliczyninfo.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4380]
![2017-11-09 17_37_29-oficjalna strona zakliczynskiego centrum kultury](https://user-images.githubusercontent.com/5884000/32617257-d196197e-c574-11e7-8b07-b00ef851347c.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`zakliczyninfo.pl##A[target="_blank"] > IMG`
