### ISSUE TITLE
mazury.info.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4381]
![2017-11-09 17_39_33-mazury info pl - absolutnie wszystko o mazurach czarter noclegi](https://user-images.githubusercontent.com/5884000/32617335-07398110-c575-11e7-93e1-b22d6c090772.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`mazury.info.pl##A[href^="http://"] > IMG[src*="logo"]`
`mazury.info.pl##A[href^="https://"] > IMG`
