### ISSUE TITLE
zeglarski.info

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4382]
![2017-11-09 17_41_56-strona glowna - portal informacyjny zeglarski info](https://user-images.githubusercontent.com/5884000/32617499-6e2ca35c-c575-11e7-8f8c-691f53b89b0f.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`eglarski.info##[style="margin-bottom: 20px; "] > A`
