### ISSUE TITLE
wien.info

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4386]
![2017-11-09 17_56_56-internetowy-przewodnik turystyczny po wiedniu - wieden teraz na zawsze](https://user-images.githubusercontent.com/5884000/32618270-801c727a-c577-11e7-8161-e15777050dd0.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`wien.info##A[target="_blank"] > IMG`
