### ISSUE TITLE
eluban.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4387]
![2017-11-09 18_00_07-luban w skrocie - eluban pl - portal informacyjny o lubaniu aktualnosci z luban](https://user-images.githubusercontent.com/5884000/32618435-04ca2b2a-c578-11e7-82f8-e4e1d538e13e.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
```
eluban.pl##[target="blank_"] > IMG
||eluban.pl/uploads/baners/$image
```
