### ISSUE TITLE
przemysl.info.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4388]
![2017-11-09 18_04_08-przemysl info pl - historia przemysla i aktualne wydarzenia](https://user-images.githubusercontent.com/5884000/32618617-85a1316c-c578-11e7-96c3-1e080bdf59fb.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`przemysl.info.pl##A[target="_blank"] > IMG`
