### ISSUE TITLE
www.lasy.gov.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#439]
cookies do poprawki nie mozna wesc do strony 

Strony internetowe Lasów Państwowych używają plików cookies. Dzięki nim możemy dostosowywać nasze serwisy do preferencji użytkowników oraz zbierać anonimowe dane do celów statystycznych. Jeżeli nie zgadzasz się na zapisywanie informacji zawartych w plikach cookies, musisz zmienić ustawienia swojej przeglądarki internetowej. Szczegóły znajdziesz w naszej sekcji o prywatności.

**Comment by MajkiIT** [comment]
blokowane już przez filtry.
