### ISSUE TITLE
infopodkarpacie.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4391]
![2017-11-09 18_09_55-infopodkarpacie pl_ brzozow sanok krosno rzeszow - wiadomosci informacje z p](https://user-images.githubusercontent.com/5884000/32618868-3a1fac9a-c579-11e7-99d6-444e595cf8c9.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`infopodkarpacie.pl#@#.bg_ad`
`infopodkarpacie.pl##A[href^="/ads/"] > IMG`
