### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#4392]
jest blokada odtworzenia materialow.

**Comment by MajkiIT** [comment]
można obejść gotowymi skryptami

**Comment by hawkeye116477** [comment]
@lukjan32 Zainstaluj uBlock Protector Extension.

**Comment by xxcriticxx** [comment]
nie pomoze jak jestes za gorami za lasami

**Comment by xxcriticxx** [comment]
@HateAds vpn @MajkiIT mi obieca od 3 lat

**Comment by MajkiIT** [comment]
na łączu 10/1 Mbps dużo nie zdzialam

**Comment by hawkeye116477** [comment]
https://kodiwpigulce.pl/jak-ogladac-player-pl-za-granica-bez-vpn-poradnik/

**Comment by xxcriticxx** [comment]
@hawkeye116477 to dziala testowalem

**Comment by lukjan32** [comment]
czyli nie ma szans, dla ublocka skryptu?

**Comment by HateAds** [comment]
@lukjan32 Zainstaluj to co Ci napisał w 1 komentarzu @hawkeye116477 i normalnie będą Ci się filmy odpalać ( chyba, że jesteś poza Polską to wtedy jeszcze trzeba musisz poszukać VPNa )

**Comment by lukjan32** [comment]
dla opery nie ma :(

**Comment by hawkeye116477** [comment]
@lukjan32 Masz tu tutorial jak zainstalować uBlock Protector Extension na ChrOperze -> https://github.com/MajkiIT/polish-ads-filter/wiki/Jak-zainstalowa%C4%87-uBlock-Protector-Extension-na-Firefoksie-lub-Waterfoksie-albo-(Chr)Operze%3F

**Comment by lukjan32** [comment]
nie instaluje sie.

**Comment by hawkeye116477** [comment]
@lukjan32 No to coś musisz źle robić. Jak już wykonałeś krok 2, to chwilę trzeba zaczekać i Protector powinien pojawić się w opera://extensions i wtedy 2 razy naciskasz zainstaluj i powinno pójść.

**Comment by hawkeye116477** [comment]
Zainstalować się powinien, ale sprawdziłem i niestety na Operze uBlock Protector o ile prawidłowo działa na filmwebie, to już nie działała prawidłowo na player.pl, powoduje on to, że nie można odtwarzać filmiku.

Także @lukjan32 polecam przesiadkę na Vivaldi albo czekać aż powstanie Adblock Protector 2 😄 .

**Comment by hawkeye116477** [comment]
@lukjan32 To coś źle robisz. Przeczytaj tutorial jeszcze raz i rób od nowa 😄 .
U mnie jedynie filmik się nie chce odtwarzać, ale to chyba u mnie coś nie tak, bo tak samo jest i bez tych uBlocków.

**Comment by lukjan32** [comment]
ja robie krok 2. mam opera 49.

**Comment by hawkeye116477** [comment]
A to ja mam jeszcze wersję 48. A wyświetla ci się jakiś błąd czy nic się nie dzieję tak po prostu?

**Comment by lukjan32** [comment]
pierwsze rozszerzenie sie zainstalowalo, a drugie juz nie.

**Comment by hawkeye116477** [comment]
@lukjan32 Zainstalowałem nowszą Operę i jest ok, więc musisz coś źle robić. Pasek postępu powinien załadować się do końca i powinno pisać, że rozszerzenie zostało wyłączone, a wtedy klikasz przejdź i 2 razy zainstaluj obok uBlock Protector Extension. Może zmontuje jakiś filmik to wtedy załapiesz o co kaman :smile: .

**Comment by lukjan32** [comment]
nagraj.

**Comment by hawkeye116477** [comment]
@lukjan32 https://www.youtube.com/watch?v=R5iB1-6B1A0 . Tylko wyłącz tego Avasta 😃 .

**Comment by lukjan32** [comment]
u mnie sie nie pojawia przejdz. 

ja juz dawno nie mam avasta.

**Comment by hawkeye116477** [comment]
@lukjan32 Zamiast przejdź możesz też wklepać do paska `opera://extensions`. A jeżeli w rozszerzeniach nie widzisz Protectors, to Może trzeba chwilę zaczekać aż ściągnie rozszerzenie, pasek powinien dojść do końca albo wyłącz Comodo, firewalla czy tam Windows Defender czy co ty tam masz 😃 .

**Comment by lukjan32** [comment]
tez nie

**Comment by hawkeye116477** [comment]
@lukjan32 No to w takim razie nie wiem co ty za trojany tam masz. Może zrób nowy profil i odpal Operę w nowym. A jak to nie pomoże to AdwCleaner ściągnij, zainstaluj i przeskanuj 😄 .

**Comment by userOperaFF** [comment]
Opera może w wersji 49 nie trawi dodatku, już tak z jakimś miałem i po prostu wywalony został.

**Comment by lukjan32** [comment]
moze.

**Comment by hawkeye116477** [comment]
@userOperaFF Ale ja to sprawdzałem też na Operze 49 na Windzie i tam działa ok, więc to u @lukjan32 coś nie tak.

**Comment by hawkeye116477** [comment]
@MajkiIT Dodaj to
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=player.pl
@@||tvn.adocean.pl/*ad.xml?$xmlhttprequest,domain=player.pl
@@/TVN-Adserver/*.mp4$xmlhttprequest,domain=player.pl
@@||cdntvn.pl/adscript.js$xmlhttprequest,domain=player.pl
```

**Comment by lukjan32** [comment]
zeby nie zakladac nowego tematu. nadal mam blokada.

**Comment by MajkiIT** [comment]
@lukjan32 noi ? U mnie jest ok tak jak to od dłuższego czasu,

**Comment by lukjan32** [comment]
dziwne, u mnie jest

![1](https://user-images.githubusercontent.com/17565773/41540128-c55f9d6c-730f-11e8-886e-ff523192e566.jpg)

**Comment by hawkeye116477** [comment]
No to w takim razie, jedyne wyjście, sesja TeamViewer z @lukjan32 :smile:

**Comment by lukjan32** [comment]
hehe

**Comment by hawkeye116477** [comment]
Co się śmiejesz @lukjan32, ślij maila ze swoim id i hasłem, to pomożemy :smile:.

**Comment by xxcriticxx** [comment]
@lukjan32 jest versia na android (pamietam ze ty kochasz anroida) bez reklam czy jestes zainteresowany?

**Comment by lukjan32** [comment]
@hawkeye116477 nie mam konta.

@xxcriticxx mam lineage, nie jesteem zainteresowany.

**Comment by hawkeye116477** [comment]
@lukjan32 Do TeamViewera nie potrzeba konta. Uruchamiasz i od razu masz podane id i hasło :smile:

**Comment by KonoromiHimaries** [comment]
jeszcze jest opcja że udostępnisz ekran na discordzie ( bez możliwości zdalnej kontroli )

**Comment by KonoromiHimaries** [comment]
@lukjan32 jeszcze jest opcja że udostępnisz ekran na discordzie ( bez możliwości zdalnej kontroli )

**Comment by xxcriticxx** [comment]
@lukjan32 LineageOS Android Distribution? 

ja mam zamontowane player na chrome os i dziala 

tag wyglonda teamviewer ta aplikacja co @hawkeye116477 reklamuje
![capture](https://user-images.githubusercontent.com/15007183/41559817-3da944dc-7313-11e8-9944-f4a73c5a2284.PNG)

**Comment by xxcriticxx** [comment]
@hawkeye116477 https://en.wikipedia.org/wiki/Chrome_OS

Chrome OS is an operating system designed by Google that is based on the Linux kernel and uses the Google Chrome web browser as its principal user interface. As a result, Chrome OS primarily supports web applications.

**Comment by lukjan32** [comment]
@hawkeye116477 ufam, ale boje sie.

**Comment by hawkeye116477** [comment]
@xxcriticxx No to nie to samo, niby jedno i drugiego korzysta/bazuje na kernelu Linuxa, ale jednak różnice mają :stuck_out_tongue:

**Comment by xxcriticxx** [comment]
@hawkeye116477 ale jakos applikaje linux/androida montuje bez problemu

**Comment by krystian3w** [comment]
Bo Google dodał wsparcie od jakieś wersji albo naokoło dodatkiem co przebuduje APK (ale wtedy nie zawsze rusza).

**Comment by lukjan32** [comment]
dobra, zdecydowalem sie, dam dostep do lapka, tam tez mam ten problem. 

program i laptop, musza byc wlaczone? moze byc wersja portable?

**Comment by hawkeye116477** [comment]
@lukjan32 Zgadza się, obie rzeczy muszą być włączone, bo inaczej nic nie zdziałamy. Nie korzystałem z Portable, ale na stronie pisze, że posiada te same funkcje, więc raczej może być.

**Comment by krystian3w** [comment]
Tak może być przenośna wersja.

**Comment by lukjan32** [comment]
ok, to kiedy?

**Comment by hawkeye116477** [comment]
@lukjan32 Za jakieś 15-20 minut zaczynamy, tylko wyślij do mnie na maila - id i hasło :smile:

**Comment by lukjan32** [comment]
dzis nie da rady, jutro rano lub o 20?

**Comment by hawkeye116477** [comment]
@lukjan32 To jutro o 20 niech będzie :smile:

**Comment by lukjan32** [comment]
ok, juz wysylam

**Comment by hawkeye116477** [comment]
Dodałem 1 wyjątek => `@@||tools.services.tvn.pl/_ads/advert.js`, teraz kółko się kręci i nie wiem czy coś z tego wyniknie, czy to tak długo trwa, bo może masz taki net. Także sprawdź potem czy to pomogło.

**Comment by lukjan32** [comment]
ok, sprawdze

**Comment by lukjan32** [comment]
jest, po reklamach poszlo.

inaczej nie mozna, aby reklam przed nie bylo?

**Comment by hawkeye116477** [comment]
@lukjan32 Tak właściwie, to reklam nie powinno być. Ten wyjątek co dałem to tylko taki skrypt pułapka. Jeżeli są reklamy, to pewnie teraz trzeba byłoby coś wykombinować na reklamy albo wyczyść dane w Operze, może coś to pomoże.

**Comment by lukjan32** [comment]
te czarne tla to sa reklamy.

czyszczenie nie pomoglo.

**Comment by hawkeye116477** [comment]
@lukjan32 No to nie wiem co z tym fantem, teraz może @MajkiIT albo @F4z  niech zajrzy, oni specjaliści od reklam :smile:

**Comment by lukjan32** [comment]
aha, oby chcieli :(

**Comment by hawkeye116477** [comment]
Powiem jeszcze tyle, że ja teraz sprawdziłem na Operzę i Chromium 66 i mam te same atrakcje. Na Vivaldim, który bazuje na Chromium 65 i Waterfoksie, jest ok. Także jakiś tu spec musiał by zajrzeć.

**Comment by lukjan32** [comment]
aha, dziwne

**Comment by krystian3w** [comment]
https://net.geo.opera.com/opera_portable/beta/windows - 54  (Chrome/67.0.3396.87)
https://net.geo.opera.com/opera_portable/developer/windows - 55 (Chrome/68.0.3440.15)

Po uruchomieniu instalatora wybierz przycisk "opcje", odznacz zaimportuj zakładki i dane z domyślnej przeglądarki.

Spróbuj z samym [uBlock Origin](https://addons.opera.com/pl/extensions/details/ublock/) i polskim filtrem regionalnym.


---

Opcjonalnie można sprawdzić Windowsa pod kontem adware / malware:

https://pl.malwarebytes.com/adwcleaner/
https://pl.malwarebytes.com/mwb-download/thankyou/

**Comment by hawkeye116477** [comment]
@krystian3w To nic nie daje, oni albo wykrywają blockera albo próbują ładować reklamy przez co niebieskie kółko się kręci i o dziwo to jest tylko na Chromium 66+. Tutaj raczej trzeba jakąś regułę wykombinować, żeby jakoś pominąć te reklamy, bo ewidentnie z konsoli wynika, że cały czas próbuje się łączyć z redcdn, by ładować reklamy.

**Comment by krystian3w** [comment]
Trzeba przetestować tą pod w wp 1 sekundową mp3 po zmodyfikowaniu pod TVN.

**Comment by MajkiIT** [comment]
@hawkeye116477 @krystian3w Kiedyś tak było ale odwrotnie, czyli na FF był alert a na chrome było ok., Kiedyś Reek to poprawił i było ok. Wydaje mi się, że coś musiało się zmienić w Chrome. Reek obszedł to skryptem który przy odpaleniu skryptu który ma wywołać reklamę zmieniał wartość, że reklama już była wyświetlona. Jeśli skrypt się wykona a reklama się nie wyświetli to kręci się kółko.

**Comment by krystian3w** [comment]
U mnie dochodzi do przeciążenia strony jak próbowałem na chrome 69 spróbować załadować tą mp3.

**Comment by hawkeye116477** [comment]
W Firefoxie/Waterfoxie nie może odtwarzać w ogóle, w konsoli pisze, że brak jakiś kodeków.

**Comment by hawkeye116477** [comment]
Dziwne requesty się pojawiły
```
hb.kumma.com
robaki.services.tvn.pl
```

**Comment by hawkeye116477** [comment]
@gwarser Sprawdź `https://player.pl/programy-online/kuchenne-rewolucje-odcinki,114`. Twoje reguły nie pomagają za bardzo, kręci się długo kółko i dopiero po jakimś czasie się wczytuje, tak jakby nadal próbuje załadować reklamy.

**Comment by gwarser** [comment]
>kręci się długo kółko i dopiero po jakimś czasie się wczytuje

Bo każda reklama jest podmieniona na jednosekundowy pusty filmik, a walą ich tam z dziesięć.

**Comment by xxcriticxx** [comment]
@hawkeye116477 pora na pingwina zapytaj ładnie

**Comment by hawkeye116477** [comment]
Jeszcze te rozwiązanie nie zawsze działa, bo czasem tak bywa, że jest napis, jest czas i nic nie ma i jeszcze takie coś z konsoli wyskakuje.
> Failed to load https://n-1-34.dcs.redcdn.pl/file/o2/TVN-Adserver/y2016/v/f442d33fa06832082290ad8544a8da27/b288f755-bb48-46b6-94ae-a20bdbb8bb31-www.mp4: Redirect from 'https://n-1-34.dcs.redcdn.pl/file/o2/TVN-Adserver/y2016/v/f442d33fa06832082290ad8544a8da27/b288f755-bb48-46b6-94ae-a20bdbb8bb31-www.mp4' to 'chrome-extension://gabbbocakeomblphkmmnoamkioajlkfo/web_accessible_resources/7f7127b0b406fcd719b081372b7ce451.mp4?secret=hfav8fgi6p17' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://player.pl' is therefore not allowed access.

**Comment by krystian3w** [comment]
A tu co się stało ktoś usuwał post?

**Comment by hawkeye116477** [comment]
Ja usunąłem swój własny.
A tak wracając do tematu, to @lukjan32 niech zainstaluje Nano Defender i będzie działać, bo chyba raczej na samego uBO nic nie wykombinują.

**Comment by lukjan32** [comment]
mam w ublock nano filters, to nie to samo?

**Comment by hawkeye116477** [comment]
@lukjan32 Nie, chodzi o `https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb`, w przypadku Opery pewnie jeszcze musisz zainstalować `https://addons.opera.com/pl/extensions/details/install-chrome-extensions/` a dopiero potem ND :smile:.

**Comment by lukjan32** [comment]
aha, ok

**Comment by lukjan32** [comment]
zaraz ide, na dwor

**Comment by xxcriticxx** [comment]
@hawkeye116477 lukjan32 poszedl sie bawic w piaskownicy

**Comment by lukjan32** [comment]
jestem niepelnosprawny, to musze sie ruszac.

**Comment by krystian3w** [comment]
Jak nie masz na liście dodatków ND to odśwież ustawienia Opery z dodatkami i powinien skoczyć i potem "zainstaluj" / "włącz".

**Comment by lukjan32** [comment]
to install-chrome-extensions, sie dobrze instaluje, a nd, nie chce sie zainstalowac, ikona opery na dole, na pasku, jest czerwona.

**Comment by krystian3w** [comment]
Dziwne... a nie znika po kliknięciu w pop-up?

![obraz](https://user-images.githubusercontent.com/35370833/42342843-9515c2c2-8097-11e8-809a-b544efcac525.png)

**Comment by lukjan32** [comment]
u mnie 
![1](https://user-images.githubusercontent.com/17565773/42343260-cfd021fe-8098-11e8-9901-dd4c37e3961d.jpg)

**Comment by lukjan32** [comment]
ok, jutro to zrobie, dzieki

**Comment by hawkeye116477** [comment]
Ewentualnie metoda z Extension Source Viewer `https://github.com/MajkiIT/polish-ads-filter/wiki/Jak-zainstalowa%C4%87-Nano-Defender-na-Firefoksie,-Waterfoksie-albo-(Chr)Operze%3F#iii-chropera`

**Comment by lukjan32** [comment]
dziala.

**Comment by krystian3w** [comment]
Aha... spróbuj Opery portable:

https://www.opera.com/pl/computer/portable
https://portableapps.com/apps/internet/opera_portable

Jak w niej nie będzie się usuwać to bym zabezpieczył konfiguracje dodatków, zapisane hasła i zakładki z normalnej Opery i potem próbował opcji resetowania (w 54 "aktualizacja&odzyskiwanie" > Zresetuj moje dane i ustawienia Opery).

Na 53 i starszej trzeba by ręcznie usunąć folder "`Opera Stable`" z `%localappdata%\Opera Software`. Przy zamkniętej Operze, po otwarciu odtworzy się czysty profil.

**Comment by lukjan32** [comment]
aha, dobra

**Comment by lukjan32** [comment]
jaki skrypt, maja te reklamy?

**Comment by lukjan32** [comment]
ten skrypt, ktory napisal @gwarser, to dziala, jest szybkie odtwarzanie reklam. tylko, trzeba poprawic, aby nie bylo reklam.

**Comment by hawkeye116477** [comment]
Jaki skrypt? Jeżeli chodzi o te reguły z `https://github.com/MajkiIT/polish-ads-filter/issues/4392#issuecomment-402552813`, to u mnie właśnie nie ma reklam ale przez jakieś 2 minuty okropnie się tnie.

**Comment by krystian3w** [comment]
U mnie Opera / Chrome eksploduje i nie pomaga na to nawet 4 GB RAM-u.

**Comment by lukjan32** [comment]
tez mam 4gb

**Comment by lukjan32** [comment]
znow cos zmienili :(

**Comment by xxcriticxx** [comment]
@lukjan32 maja ciebie na celowniku

**Comment by lukjan32** [comment]
chyba, ten skrypt od @gwarser nie dziala :(

**Comment by xxcriticxx** [comment]
@lukjan32 przerzuc sie na kodi

**Comment by lukjan32** [comment]
zresetowalem opera i dalej to samo. nie da sie dodac nd.

**Comment by krystian3w** [comment]
W Portable się dodawała czy nie sprawdzałeś?

**Comment by lukjan32** [comment]
nie sprawdzalem, bedzie tak samo

**Comment by lukjan32** [comment]
aha, wylacze defendera

**Comment by krystian3w** [comment]
Hmm... powodzenia 😉 

https://www.sordum.org/9480/defender-control-v1-3/
http://soisk.pl/wylaczenie-uslugi-windows-defender-security-center/

**Comment by lukjan32** [comment]
tez nic

**Comment by krystian3w** [comment]
Zrób sobie kopię "`Opera Stable`" przy zamkniętej Operze, potem usuń z oryginalnej lokalizacji i sprawdź czy się uda zainstalować:

https://addons.opera.com/pl/extensions/details/install-chrome-extensions/
https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb

**Comment by lukjan32** [comment]
dzisiaj tak juz zrobilem.

**Comment by krystian3w** [comment]
https://www.opera.com/pl/computer/beta - najwyżej będziesz mieć przeglądarkę Operę Beta / Dev jak tam się zainstaluje / nie będzie znikał pod `player.pl` 
(opcjonalnie jak lubisz testować to z bety / dev możesz zrobić główną przeglądarkę).

**Comment by lukjan32** [comment]
aha, zostawie to, tak jak jest.

**Comment by hawkeye116477** [comment]
A co się tak cykasz? Coś nie będzie działać, to najwyżej wrócisz do stabilnej :smile:

**Comment by lukjan32** [comment]
wiem, ze bedzie tak samo.

**Comment by lukjan32** [comment]
na proba dalem adguard, to dziala ok

**Comment by lukjan32** [comment]
aha. dobra

**Comment by krystian3w** [comment]
Oj to sobie ręcznie je doda, aż taka magia to nie jest.

**Comment by hawkeye116477** [comment]
Ale jak ręcznie doda, to nie będzie aktualizacji.

**Comment by krystian3w** [comment]
Hmm... w sumie tak, bo importuje na listę filtrów ręcznych.

To jeszcze bym polecił wyłączyć "Automatycznie aktywuj najbardziej odpowiednie filtry" potem nagle rosyjskie filtry będą psuć polskie strony i tak dalej...

...i może wyłączyć subskrypcje "EasyList Polish", chyba że będziesz do Krzyśka zgłaszał błędy mailowo, na forum lanik.us a ostatecznie w repo na github.

**Comment by kulfoon** [comment]
Zdaje się, że czas najwyższy to zamknąć: FF / O + uBO + ND i bez problemu odtwarzają się filmiki na player.pl np. ten https://player.pl/programy-online/kuchenne-rewolucje-odcinki,114, czy komuś nie działa?

**Comment by krystian3w** [comment]
Tu się rozchodzi o jego <ins>wadliwą</ins> **Operę** / **Windows 10** i trudność instalacji Nano Defender.

**Comment by kulfoon** [comment]
Hmm, 
1) a po czym poznajesz, że chodzi o Windows 10? Bo wyszukuję w tym wątku w przeglądarce frazę "windows 10" / "win 10" / "w 10" (a także bez spacji) i nic nie znajduje, nie widzę takżę żadnego posta wspominającego o Windows 10, czy coś przeoczyłem?
2) skoro:
- to coś u niego z Operą / Windowsem, a inni tego problemu nie mają,
- nie udało nam się mu pomóc
- wątek wisi od 3 miesięcy i chłopak się nie udziela w nim

to wąztek można zamknąć, a chłopak niech zreinstaluje Operę albo Windowsa, definitywnie nie jest to problem po stronie POL listy filtrów.

**Comment by kulfoon** [comment]
1) A po czym poznajesz, że chodzi o Windows 10? Bo szukałem w tym wątku frazy "windows 10" / "win 10"  / "w 10" (a także bez spacji) i nic nie znalazło, nie znalazłem także komentarzy wspominających o Windows 10, czy coś przeoczyłem?
2) Skoro:
- to problem u niego z Operą / Windowsem, a inni tego problemu nie mają
- staraliśmy się mu pomóc ale nie udało się
- chłopak nie udziela się tu już od 3 miesięcy

to wątek kwalifikuje się do zamknięcia, bo definitywnie nie jest to problem POL listy filtrów, a chłopak niech sobie zreinstaluje Operę / Windowsa

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/4392#issuecomment-402825713 - obrazkowo.

Raczej nie jest to Windows 8 / 8.1 ani starszy z modyfikacją wyglądu na 10.

**Comment by lukjan32** [comment]
juz jest dobrze, juz mam nano defender.
