### ISSUE TITLE
puls.wrzesnia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4395]
cookies

**Comment by MajkiIT** [comment]
@hawkeye116477 sprawdź to `puls.hedrych.pl##DIV[style="position: fixed; z-index: 99; bottom:0; padding: 0 20px 10px 20px; color: #fff; background-color:#2E2F31; text-align:justify;"]`

Celowo domena jest inna

**Comment by hawkeye116477** [comment]
@MajkiIT Działa.
Można też na wszelki wypadek dać krótszą regułę:
`puls.hedrych.pl##body > div:not([id]):not([class])[style*="position"][style*="fixed"]` 😄
