### ISSUE TITLE
kryptowalutykoparka.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4397]
![2017-11-09 22_46_40-bitcoin newsy kurs handel wydobycie](https://user-images.githubusercontent.com/5884000/32631258-f0703534-c59f-11e7-8c35-2d9d8b45edbc.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`kryptowalutykoparka.pl###text-20`
