### ISSUE TITLE
tychy.info

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4398]
![2017-11-09 22_51_05-tychy info - swieze spojrzenie na miasto](https://user-images.githubusercontent.com/5884000/32631474-ad0fc6fa-c5a0-11e7-8102-e872c8900f63.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`tychy.info##.header_img`
