### ISSUE TITLE
inowroclaw.info.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4399]
![2017-11-09 06_42_13-inowroclaw info pl - mobilni do bolu](https://user-images.githubusercontent.com/5884000/32590202-6b27325a-c519-11e7-834b-3166acfb9ab9.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
@mat41997 zaktualizowałeś filtry?

**Comment by mat41997** [comment]
@MajkiIT tak i jeszcze specjalnie odczekałem 2 godziny żeby mieć pewność.

**Comment by mat41997** [comment]
po kliknięciu w start znowu się pojawiło.

**Comment by mat41997** [comment]
znowu zniknęło, nie wiem co o tym myśleć.

**Comment by MajkiIT** [comment]
`##[class^="advert-"]` zerknij na to

**Comment by mat41997** [comment]
@MajkiIT null, nic nie dało.

**Comment by MajkiIT** [comment]
`inowroclaw.info.pl##[class*="advert"]`to dziala u mnie

**Comment by mat41997** [comment]
@MajkiIT nie mam pojęcia, ale narazie wydaje się działać.

**Comment by MajkiIT** [comment]
@mat41997 poczekamy kilka dni i sprawdzimy

**Comment by hawkeye116477** [comment]
Social -> `www.inowroclaw.info.pl##.youtube`
