### ISSUE TITLE
dotnetomaniak.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4400]
![2017-11-09 23_07_59-dotnetomaniak pl - najnowsze artykuly o net](https://user-images.githubusercontent.com/5884000/32632190-f44073f6-c5a2-11e7-8099-3d3acb92577c.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
to ich sklep

**Comment by mat41997** [comment]
@MajkiIT ale link zewnętrzny.
