### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4404]
założyłby kto jakiego discorda
https://discordapp.com/

> discord to taki ts, tylko lepszy

**Comment by hawkeye116477** [comment]
@mat41997 Mógłbym założyć, ale pytanie jest raczej czy to by się przyjęło i czy ktoś by tam zaglądał. No i tak właściwie, to Discord jest dla graczy.

**Comment by mat41997** [comment]
@hawkeye116477 dla deweloperów też.
nie ważne czy się przyjmie, ważne że wy będziecie używać i budować społeczność.

**Comment by hawkeye116477** [comment]
Ok, gotowe, zapraszam -> https://discord.gg/tWCGPZn .
Ale jak minie miesiąc i będą pustki, to zapewne usunę serwer.

**Comment by xxcriticxx** [comment]
blah za hardkorowy ten mirc dla mnie

**Comment by mat41997** [comment]
@hawkeye116477 nie pochwalam takiego podejścia. przecież go nie reklamujesz, to oczywiste że będą pustki.

**Comment by mat41997** [comment]
@hawkeye116477 możesz podpiąć discorda pod githuba, tak by na discordzie wyświetlało się wszystko co się dzieje na githubie.

**Comment by hawkeye116477** [comment]
@mat41997 Na razie nie reklamuję, ale skoro założyłem, no to chyba trzeba będzie zrobić jakąś reklamę. 
@xxcriticxx A co tu jest takiego hardkorowego w Discordzie, pisze się jak na GH, tyle, że są kanały osobne do ciastek, sociala i innych spraw. Nawet można wchodzić bez rejestracji.

**Comment by mat41997** [comment]
@hawkeye116477 zgadnij kto to może być? I nie, nie jest to Koronkowa Księżniczka..

**Comment by hawkeye116477** [comment]
@mat41997 Wujek Google już cię wydał 😄 .

**Comment by xxcriticxx** [comment]
@hawkeye116477 xchat nie moge uzywac?

**Comment by mat41997** [comment]
@xxcriticxx XD
http://xchat.org/img/xcshot.jpg

**Comment by xxcriticxx** [comment]
@mat41997 starosc nie radosc mlodosc nie wiecznosc

**Comment by hawkeye116477** [comment]
> Zorro się pojawił. Koniec imprezy 😃 

A kim jest ten cały Zorro?

**Comment by gzenio22** [comment]
Zapro sie przedawnilo

**Comment by hawkeye116477** [comment]
@gzenio22 Nie przedawniło się, jest ono na czas nielimitowany, musisz tylko się zarejestrować, bo inaczej to nie przejdzie. Zrobiliśmy wymóg potwierdzenia maila, bo spamerzy wchodzili.

**Comment by gzenio22** [comment]
kumam czacze :D

**Comment by hawkeye116477** [comment]
@mat41997 Zrobiłem reklamę na wykopie -> https://www.wykop.pl/tag/adblock/wszystkie/ i na razie 2 nowe osoby dołączyły na serwer.

**Comment by mat41997** [comment]
@hawkeye116477 link zapraszający można pod jakąś subdomenę podpiąć ^^
