### ISSUE TITLE
noweinfo.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4405]
![2017-11-10 02_53_58-nowe info - tygodnik regionalny](https://user-images.githubusercontent.com/5884000/32639118-9e35da08-c5c2-11e7-919f-a55754dd1ab9.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.63
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`noweinfo.pl##.td-adspot-title`
