### ISSUE TITLE
btc-jak-bitcoin.blog.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4410]
![2017-11-10 21_29_30-dobry na wszystko _ btc jak bitcoin](https://user-images.githubusercontent.com/5884000/32677350-5d72baee-c65e-11e7-989a-14bdefc02615.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.66
chrome 62.0.3202.89

**Comment by gzenio22** [comment]
btc-jak-bitcoin.blog.pl###text-7 > .textwidget

**Comment by mat41997** [comment]
@gzenio22 używaj ''
