### ISSUE TITLE
telepolis.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4415]
Po prawej reklama smartfona „stworzonego przez Xiaomi, zasilanego przez Google'a".

#xiaomilepsze -> `www.telepolis.pl##a[href^="http://partnerzy.comperia.pl/ads.php"]`
Tło -> `www.telepolis.pl##body:style(background: none!important;)`

**Comment by gwarser** [comment]
Starajcie się proszę blokować pobieranie, a nie tylko ukrywać. Coś w stylu:

    ||www.telepolis.pl/gfx/screening/telepolis_euro$image

**Comment by MajkiIT** [comment]
@gwarser sprawa dyskusyjna, bo czasami jest div i ma jakąś wielkość i zablokuje pobranie ale puste pole zostaje.

**Comment by gwarser** [comment]
@MajkiIT tak, ale wtedy to dwa filtry - sieciowy i kosmetyczny. Bo to wszystko się i tak w tle ładuje potem.

**Comment by gomoku** [comment]
@gwarser i @hawkeye116477 to jest zabawni hipokryci 

@gwarser dopiero co twierdził, że mu część sekundy w te czy we różnicy nie robi: 
https://github.com/azet12/PopupBlocker/issues/208, a teraz nagle już mu robi.

@hawkeye116477 odwrotnie: tu różnicę mu robiło: https://github.com/MajkiIT/polish-ads-filter/pull/4286 a tu: https://github.com/azet12/PopupBlocker/issues/208 już nie.

Zabawni kolesie, jacyś niezdecydowani.

**Comment by hawkeye116477** [comment]
A @gomoku jest mądrzejszy od papieża 😃  .

**Comment by gwarser** [comment]
Nic nie widzę tutaj o sekundach które miałyby mi robić różnicę.
Nie denerwuj się tak - to tylko głupia lista do adbloka, każdy może zrobić swoją.
Bardzo mi przykro, że nie podobają ci się moje emotki. Nie obserwuję też tego repo i nie widziałem twojej odpowiedzi - bardzo niegrzecznie, że mnie nie zawołałeś, ale jak nie chcesz dalej rozmawiać, to to uszanuję.

**Comment by gomoku** [comment]
> @gwarser: Nic nie widzę tutaj o sekundach które miałyby mi robić różnicę.

Dopiero co w komentarzach 2 i 4 zalecałeś używać filtrów sieciowych, żeby się w tle niepotrzebnie nie ładowały niepotrzebne elementy, czyli nie obciążały łącza, pamięci i cpu, co przekłada się na szybsze ładowanie strony i o to przecież chodzi, o wydajność, a teraz, palisz głupa, że nie widzisz różnicy i że nie o wydajność ci tu chodzi, może po prostu przestań trolować i się wykręcać od tego co napisałeś...przejechałeś się na własnej hipokryzji i trudno ci się do tego przyznać.

> @gwarser: nie denerwuj się tak

Generalnie nie denerwuję się, po prostu nie lubię troli, hipokrytów itp. więc ich tępię za wszelką cenę, bo szkodliwe insekty się tępi.

> @gwarser: to tylko głupia lista do adbloka, 

Zgadzam się.

> @gwarser: każdy może zrobić swoją.

To idź i zrób swoją, najlepiej dwie, jedną zoptymalizowaną pod wydajność, a drugą niezoptymalizowaną, bo w jednym wątku wydajność ci różnicy nie robi, w już w innym robi (czyli hipokryzja).

> @gwarser: Bardzo mi przykro, że nie podobają ci się moje emotki. 

Bo lepsze byłyby argumenty / wyniki testów, no ale trole ich nie mają, więc zaczynają stosować emotki.

> @gwarser: Nie obserwuję też tego repo i nie widziałem twojej odpowiedzi - bardzo niegrzecznie, że mnie nie zawołałeś, ale jak nie chcesz dalej rozmawiać, to to uszanuję.

Nie wiem o którą odpowiedź ci chodzi (link proszę), i jakie niepowiadomienie  ale taka właśnie jest (i była od początku) z tobą (podobnie jak z trolem  @mat41997) ~~rozmowa~~ patologiczna rozprawka, często o czymś piszesz, ale nie wiadomo o czym.

> @gwarser: bardzo niegrzecznie

Jak już wspomniałem nie wiem o którą, wypowiedz ci chodzi itp., ale tak czy inaczej, nie wiem dlaczego się czepiasz byle czego na siłę i dodatkowo wyolbrzymiasz i przekoloryzowujesz ("bardzo"), sam jesteś trolem-hipokrytą co wykazałem (i co jest niegrzeczne samo w sobie jeśli już), więc wygląda na to, że  teraz się wykręcasz, dodatkowo pozując na grzecznego  aniołka i ofiarę, i wyszukując trolowe haki na mnie, czyli wyolbrzymiasz i próbujesz zrobić ze mnie, osobę nader denerwującą się/bardzo niegrzeczną, czyli napastnika, ale niestety daleko mi do bycia trolem jak ty czy @mat41997, wygląda na to, że chcesz rozdmuchać wszystko żeby zrobić na mnie nagonkę, bo inaczej nie umiesz się obronić w bardziej cywilizowany sposób. A jeśli zarzucasz mi, że jestem bardzo niegrzeczny (chociaż póki co nie wiem o co chodzi), to spójrz na siebie i na @kacper93 nie odpisaliście na mój komentarz https://github.com/MajkiIT/polish-ads-filter/issues/4037#issuecomment-341915987 i nie  wyjaśniliście kwestii technicznej, tylko wkleiłeś prześmiewczą emotkę, zamiast odpowiedź tylko nie wiedzieć co tam było takiego śmiesznego, może oświecisz? A może zabolało was, że zauważyłem waszą pomyłkę techniczną, więc zamiast się przyznać to strolowałeś emotką, a on strolował ignorem.

> @gwarser: ale jak nie chcesz dalej rozmawiać, to to uszanuję.

Doceniam twój zabawny sakrazm, ale wystarczy zauważyć proste fakty, żeby było jasne kto tu unika konfrontacji/dyskusji:

- troll @mat41997 zaatakował mnie i gdy przegrywał ze mną dyskusję i na ratunek przyszedł mu tzw. "admin" @xxcriticxx i zamknął wątek po jego wypowiedzi, zmuszając mnie do założenia drugiego wątku o takiej samej nazwie i napisania odpowiedzi, ale troll @mat41997 już nie odpisał bo widział, że przegrywa, a tzw "admin" @xxcriticxx znowu zamknął drugi wątek. 

- z tobą trolu @gwarser było podobnie, tyle, że na repo PopupBlocker, przegrywałeś na argumenty, nie potrafiłeś podać sensownych wyników testów, forsowałeś swoją rację siłą, i w końcu ciebie również uratował hipokryta-admin @hawkeye116477 który zamknął wątek, (przyklaskując tobie, że mu też różnicy nie robi 0,5 sek, a jeszcze nie dawno pozmieniał :-abp-contains właśnie w celu optymalizacji wydajności) zmuszając mnie do założenia nowego wątku o takiej samej nazwie i napisania odpowiedzi, ale nie odpisałeś, więc wątek zamknąłem.

- na repo uBlock też kilku troli się znalazło (w tym np. uBlock-user ), z którymi gdy wszedłem w dyskusję na argumenty to zaczęli jak wy hejtować emotkami, zamiast udzielać merytorycznych odpowiedzi), a niektórzy zarzucili ignora, bo dyskusję przegrywali, gdy uBlock-user przegrywał na argumenty, to znowu to samo czyli przyszedł tzw. "admin" (goryl) i obronił @uBlock-user 'a, czyli  zablokował wątek i mnie zbanował,(pomijając fakt, że jeszcze wcześniej gdy z samym gorylem wszedłem w dyskusję na argumenty w innym wątku, to sam mnie strolował ignorem i zablokowaniem wątku)

Nie wliczając w to identycznych sytuacji, w wielu innych miejscach w internecie, każda próba udowodnienia racji trolowi za pomocą twardych argumentów, kończy się agresywnym trolowaniem trola (wykręcanie się, pomówienia, hipokryzja, hejt za pomocą emotek, odwracanie kota ogonem itd.) połączonym z wsparciem zaprzyjaźnionego admina, który w odpowiedniej chwili (gdy troll będzie przegrywał) zablokuje wątek, zarzuci bana na wygrywającego z trolem.

Wyjątkiem był jeden przypadek gdy tzw. "admin" nie zamknął wątku, dzięki czemu miałem przyjemność rozłożyć trola "estoril2" do poziomu atomów, czyli do momentu, w którym zaczął powtarzać się jak zacięta płyta, a ja mu nie musiałem odpisywać, bo już mu wcześniej na to samo odpisywałem, więc przestałem się po prostu odzywać. Temat dyskusji był podobny co z tobą, czyli zaczął twierdzić coś technicznego, czego jak się okazało nie umiał technicznie udowodnić, i gdy mu już to udowodniłem, że to co pisze to nieprawda, to tak się biedak wkurzył, że ..sami możecie zresztą poczytać: http://www.szachista.com/ftopict-3946.html

Nie chce się jeszcze więcej rozpisywać na temat sparszywiałego zachowaniu wielu troli w całym internecie, z którymi miałem przyjemność, wliczając w to tzw. "adminów" (w cudzysłowiu oznacza, że to są admini od bronienia koleżków)

Więc, nie pisz, że to ja unikam dyskusji, bo to, że zawsze admin się wpier.ala nieproszony z butami między wódkę a zakąskę i blokuj wątek, żeby was uratować przed porażką na argumenty, to ja nic na to nie poradzę, ja zawsze byłem za tym, że dyskusja kończy się naturalnie, czyli wtedy gdy jednej ze stron wyczerpią się argumenty, albo argumenty się zrównają i będzie remis, więc jedynym wyjściem jest przeniesienie się w inne miejsce gdzie będziemy mogli dokończyć w spokoju dyskusję, 

> @gwarser: bardzo niegrzecznie, że mnie nie zawołałeś, ale jak nie chcesz dalej rozmawiać, to to uszanuję.

No co ty, nigdy nie mógłbym nie dokończyć dyskusji, nie wspominając o fakcie o którym napisałem wyżej, że to nie ja przerywam rozmowy, więc żeby nie było, właśnie cię wołam, i nie tylko ciebie, zapraszam także trola @mat41997, bo też mamy niedokończoną "rozmowę". @MajkiIT 'ego też zapraszam, bo unika konfrontacji na argumenty, ze strachu biedak zarzucił ignora. Każdego osobno na 1vs1 zapraszam, mam nadzieję, że się nie boicie dokończyć rozmowy w innym neutralnym miejscu? Tylko lepiej pospieszcie się z decyzją i propozycją miejsca, bo zaraz przyjdzie tzw. "admin" (@xxcriticxx) i znowu zablokuje wątek, a potem będziecie skomleć, że to ja unikam dyskusji. Czekam z niecierpliwością.
