### ISSUE TITLE
odszkodowania-torun.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#4418]
http://www.odszkodowania-torun.pl/

Ciasteczka:
```
||www.odszkodowania-torun.pl/wp-content/plugins/wp-cookies-alert/style.css
www.odszkodowania-torun.pl###wpca-box
```

![](https://s3.dodajfote.pl/2017/11/11/odszkodowania_torun_1c0ee31a746de63ed.png)

**Comment by hawkeye116477** [comment]
`###wpca-box:not(body):not(html)`

**Comment by gomoku** [comment]
A dlaczego bez filtra `||`.
