### ISSUE TITLE
parenting.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4427]
![2017-11-11 13_09_14-_70 proc skladu matki to wyrzuty sumienia ja jestem tego typowym przykladem_](https://user-images.githubusercontent.com/5884000/32689274-b2eefaa4-c6e1-11e7-8812-dae98a772640.png)

![2017-11-11 13_09_36-_70 proc skladu matki to wyrzuty sumienia ja jestem tego typowym przykladem_](https://user-images.githubusercontent.com/5884000/32689275-b80516a4-c6e1-11e7-85cd-c13098b3e801.png)

![2017-11-11 13_10_15-_70 proc skladu matki to wyrzuty sumienia ja jestem tego typowym przykladem_](https://user-images.githubusercontent.com/5884000/32689277-bd891d5a-c6e1-11e7-8324-6974bec3efa2.png)
https://parenting.pl/70-proc-skladu-matki-to-wyrzuty-sumienia-ja-jestem-tego-typowym-przykladem-rozmowa-z-patrycja-markowska

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.66
chrome 62.0.3202.89

**Comment by xxcriticxx** [comment]
clean 

![capture](https://user-images.githubusercontent.com/15007183/32689361-0fff959a-c6b1-11e7-8400-2fdc97364fe5.PNG)

**Comment by MajkiIT** [comment]
@mat41997 zaktualizuj filtry do Ubo

**Comment by mat41997** [comment]
@MajkiIT nic, nadal są

**Comment by xxcriticxx** [comment]
@mat41997 cookies browsing histrie next

**Comment by mat41997** [comment]
@xxcriticxx nawet po wyczyszczeniu cookie nadal to mam.

**Comment by xxcriticxx** [comment]
testowales na foxie?

**Comment by gomoku** [comment]
U mnie czysto na F&O.

**Comment by hawkeye116477** [comment]
A ja mam to samo co @mat41997 na Waterfoksie i Vivaldim.

**Comment by MajkiIT** [comment]
```
/^https:\/\/[a-z]{2,14}\.wp\.pl\/[a-zA-Z0-9_-]{450,}/$script,domain=avent-ugrow.wp.pl
avent-ugrow.wp.pl##[class$="BgClick"]
```
