### ISSUE TITLE
adwokat-gostkowski.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#4429]
https://adwokat-gostkowski.pl/

Resztki po reklamach (zaufali nam + pasek + 3 kropki) + social panel:

```
adwokat-gostkowski.pl###page > .wiersz:nth-of-type(2)
||adwokat-gostkowski.pl/img/socjal/fb.jpg
||adwokat-gostkowski.pl/img/socjal/gp.jpg
||adwokat-gostkowski.pl/img/socjal/kon.jpg
```

![](https://s3.dodajfote.pl/2017/11/11/gostowski48df14bf9cc08515.png)

**Comment by MajkiIT** [comment]
`adwokat-gostkowski.pl###blok_partnerzy2`
