### ISSUE TITLE
www.strefawalkingdead.pl

### ISSUE THREAD

**Issue by Piter432** [MajkiIT/polish-ads-filter#443]
Parę filtrów, które by się przydały. Pierwsze dwa są do ukrycia powiadomienia o polubieniu strony na Facebooku (żeby nie było – zgłaszałem to twórcom i zero reakcji) i wolałbym, by były użyte w liście filtrów „Adblock polskie reguly social” (chyba że wszystkie reguły w tej liście już są w ogólnej liście filtrów do polskich stron od Was, bo nie sprawdzałem). Trzecie służy do ukrycia takiego małego szarego pola, w którym się pojawia/ją reklama/y, a to pole zasłania przycisk (i pojawia się w tym samym momencie, co ten przycisk), który służy do przewinięcia na samą górę strony).

www.strefawalkingdead.pl###spu-bg-53171
www.strefawalkingdead.pl###spu-53171
www.strefawalkingdead.pl##.adk-position-right.adk-fixed

**Comment by MajkiIT** [comment]
Ok dodam. Dziękuję.
