### ISSUE TITLE
cvninja.pl

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#4431]
https://cvninja.pl/

Anty-adblock z rozmyciem + powiązany z nim popup:

Na anty-adblock z rozmyciem + popup, do wyboru jeden z tych:
```
cvninja.pl##script:inject(abort-on-property-write.js, FuckAdBlock)
cvninja.pl##script:inject(abort-on-property-read.js, fuckAdBlock)
cvninja.pl##script:inject(abort-on-property-write.js, fuckAdBlock)
```

Na sam popup (ale to raczej na Popup-Blocker): `cvninja.pl##.modal-dialog`

![](https://s3.dodajfote.pl/2017/11/11/cvninja613e2af18edcec74.png)

**Comment by hawkeye116477** [comment]
Skrypt AAK Cont i uBlock Protector Extension najwyraźniej to blokują, bo ja tego nie mam.
