### ISSUE TITLE
antybook.pl

### ISSUE THREAD

**Issue by Piter432** [MajkiIT/polish-ads-filter#444]
antybook.pl###wpad

Odnosi się do pustego miejsca po reklamie na dole strony~~, a przynajmniej w dowolnym artykule. Nie wiem jak ze stroną główną~~.

#Edit
Wróć. Jednak odnosi się to do dowolnej strony z artykułem i strony głównej.

**Comment by MajkiIT** [comment]
Ok dodam. Dziękuję.

**Comment by MajkiIT** [comment]
w kodzie strony tego nie widzę.

**Comment by Piter432** [comment]
Hmm, ciekawe. Też zajrzałem właśnie teraz, gdy piszę ten komentarz i również tego nie widzę. Może któryś z tamtejszych adminów się zorientował albo dostawał sporo zgłoszeń odnośnie tego pustego po reklamie na dole strony głównej i na dole każdej strony z artykułem, więc usunął to z kodu. Trochę szkoda (dla mnie :P), ale trudno.

Jeśli się coś jednak zmieni (a kiedyś na pewno), to dam znać.
