### ISSUE TITLE
tygodnikprzeglad.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4446]
![2017-11-11 20_35_01-przeglad _ internetowe wydanie tygodnika przeglad](https://user-images.githubusercontent.com/5884000/32692864-15dfaddc-c720-11e7-8af9-9220c9eb30ef.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.67
chrome 62.0.3202.89

**Comment by gomoku** [comment]
Popup + overlay + newsletter pójdzie na PopupBlocker:
```
||www.tygodnikprzeglad.pl/wp-content/uploads/2017/11/banner-popup-p56.jpg
www.tygodnikprzeglad.pl###sgcolorbox, #sgcboxOverlay
www.tygodnikprzeglad.pl###sidebar > .widget.widget-2
```

Dalej to co na POL listę:

Reklama u góry + kontenter po reklamie:
```
||www.tygodnikprzeglad.pl/wp-content/plugins/ml-slider/assets/sliders/flexslider/jquery.flexslider-min.js
||www.tygodnikprzeglad.pl/wp-content/plugins/ml-slider/assets/metaslider/public.css
||www.tygodnikprzeglad.pl/wp-content/plugins/ml-slider/assets/sliders/flexslider/flexslider.css
||www.tygodnikprzeglad.pl/wp-content/uploads/2017/05/baner-miejsce-na-reklame1000x149.jpg
||www.tygodnikprzeglad.pl/wp-content/uploads/2017/07/powstanie_banner_1000x149.jpg
||www.tygodnikprzeglad.pl/wp-content/uploads/2017/06/ogien_gorny.png
www.tygodnikprzeglad.pl##.metaslider
```

Reklama po prawej na dole + kontener po reklamie + darowizna(też?):
```
||www.tygodnikprzeglad.pl/wp-content/uploads/2017/06/hisotryk.logo-2.jpg
www.tygodnikprzeglad.pl##.widget-9, .footer-darowizna-widgets
```

**Comment by MajkiIT** [comment]
```
tygodnikprzeglad.pl##.widget-9.last.widget
tygodnikprzeglad.pl##.widget-6.widget
tygodnikprzeglad.pl##A > [class^="slider-"][draggable="false"]
```

**Comment by gomoku** [comment]
1) Po co `.widget-9.last.widget` skoro wystarczy to `.widget-9`
2) Po co `.widget-6.widget` skoro wystarczy `.widget-6`
3) Dlaczego nie w jednym filtrze, `tygodnikprzeglad.pl##.widget-6, .widget-9`
3) (`.widget-5` i `.widget-6`, widziałem i nie przeoczyłem, po prostu to reklamy własne, więc dlatego ich nie uwzględniłem, być może też się kwalifikowały,) Ale skoro już dałeś `.widget-6` to dlaczego nie także `.widget-5` bo `.widget-5` prowadzi do serwisu własnego Przegląd.
4) Rozumiem, że nie chcesz blokować całego tego skryptu slide (filtry `.js` + `.css` + `##metaslider`) Hmm a dlaczego, bo ten cały slide to raczej żeby reklamy się zmieniały, no chyba, że zakładasz, że pojawi się tam coś co nie jest reklamą zewnętrzną (np. że pojawi się logo, reklama własna, przydatny komunikat)?
5)  Dlaczego nie blokować banerów/obrazków (filtry `||`) tak jak zalecał @gwarser tu: https://github.com/MajkiIT/polish-ads-filter/issues/4415#issuecomment-343615185, żeby nie zjadały łącza/pamięci i cpu, czy dlatego, że banery/obrazki mogą się zmieniać? Ale z drugiej strony mogą też się nie zmieniać, albo zmieniać rzadko, skąd wiesz, że będą się zmieniać często? Znasz tę stronę?
