### ISSUE TITLE
historyk.eu

### ISSUE THREAD

**Issue by gomoku** [MajkiIT/polish-ads-filter#4448]
http://historyk.eu/

```
! 4 Reklamy po prawej + kontenery po reklamach:
||historyk.eu/include/styles/historyk/img/sponsor.png
||historyk.eu/include/styles/historyk/img/forum.png
||historyk.eu/include/styles/historyk/img/ksiazka-na-urlop.jpg
||historyk.eu/include/styles/historyk/img/historyk_ludzie_honoru.jpg
historyk.eu###sponsor, #banner-book, a[href="http://warszawskagrupawydawnicza.pl/produkt/ludzie-honoru/"], #sidebar > a[href="http://forum.historyk.eu/"]
! Reklama po prawej na dole + kontener po reklamie:
||webax.pl/images/bannergif.gif
historyk.eu##a[href="http://webax.pl/"]
```

! Newsletter na PopupBlocker: `historyk.eu###newsletter`

![](https://s3.dodajfote.pl/2017/11/11/hist_4420d467fd9bb8b2e.png)

![](https://s3.dodajfote.pl/2017/11/11/historyk_105163d222c60a431.png)

![](https://s3.dodajfote.pl/2017/11/11/hist_3d3cb43c354b413c6.png)

![](https://s3.dodajfote.pl/2017/11/11/hist_28856c179cca50077.png)

**Comment by MajkiIT** [comment]
```
historyk.eu###banner-book + A > IMG:last-child
historyk.eu##DIV > A > IMG[style^="width: "]:last-child
historyk.eu##A[target="_blank"] > IMG
```

**Comment by gomoku** [comment]
Kilka pytań z ciekawości, bo rozbieżności w naszych filtrach są spore:

1) Pytanie 5 to samo co tu: https://github.com/MajkiIT/polish-ads-filter/issues/4446#issuecomment-343731518
2) Dlaczego nie zdejmujesz tej Reklamy-loga-Forum po prawej, skoro:
- link do "Forum" jest tuż nad tą reklamą
- takie samo logo jest u góry po lewej
3) Dlaczego nie zdejmujesz reklamy po prawej "Szukasz książki na urlop"
