### ISSUE TITLE
cookiealert.sruu.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#4453]
Może warto to dodać http://cookiealert.sruu.pl/CookieAlert-latest.min.js

**Comment by xxcriticxx** [comment]
for sure

**Comment by xxcriticxx** [comment]
ten script jest na 1422 stronach

**Comment by hawkeye116477** [comment]
`/cookiealert.` - tak jest u Fanboya.

**Comment by xxcriticxx** [comment]
@hawkeye116477  nie lepjej dac 

`/CookieAlert-latest.min.js`

**Comment by hawkeye116477** [comment]
@xxcriticxx No w sumie, można i tak.
