### ISSUE TITLE
tapeciarnia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4455]
http://www.tapeciarnia.pl/tapeta-szczeniaczek-golden-retrievera

![capture](https://user-images.githubusercontent.com/15007183/32701480-b0455cbc-c7a4-11e7-9e48-7d65b5042790.PNG)

**Comment by MajkiIT** [comment]
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=www.tapeciarnia.pl`
