### ISSUE TITLE
mebloo.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4457]
![2017-11-12 18_47_57-meble narozniki fotele kanapy stoly krzesla warszawa - mebloo pl](https://user-images.githubusercontent.com/5884000/32701686-55ebe3b8-c7da-11e7-8744-9eaf85a02a97.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.72
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
`mebloo.pl###fabryka_sypialni > [target="_blank"] > IMG`
