### ISSUE TITLE
fabrykasypialni.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4458]
![2017-11-12 18_51_32-materace - lozka - meble - warszawa - fabrykasypialni pl](https://user-images.githubusercontent.com/5884000/32701704-92d15376-c7da-11e7-9360-9fb713ef13c0.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.72
chrome 62.0.3202.89

**Comment by MajkiIT** [comment]
to sklep internetowy

**Comment by hawkeye116477** [comment]
Chyba chodzi o ten pasek z mebloo.pl, ale to jest ich drugi sklep.

**Comment by mat41997** [comment]
@MajkiIT ach tak!
https://github.com/MajkiIT/polish-ads-filter/issues/4457#issuecomment-343768829

**Comment by MajkiIT** [comment]
@mat41997 dobra już teraz załapałem co chcesz zablokować
`fabrykasypialni.pl###mebloo`
