### ISSUE TITLE
moviesroom.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4462]
![capture](https://user-images.githubusercontent.com/15007183/32704645-86a17670-c7d6-11e7-9005-a02214d22b38.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx Ja tego nie widzę.

**Comment by hawkeye116477** [comment]
![z](https://user-images.githubusercontent.com/19818572/32718208-ab6fa77a-c85c-11e7-8bf2-f752cf82a3c8.PNG)

**Comment by xxcriticxx** [comment]
@hawkeye116477 windows 10 ma chyba jakis darmowy soft?

**Comment by hawkeye116477** [comment]
@xxcriticxx Windows 10 ma Windows Defender, ale ja mam W7. Wywaliłem już F-Secure, teraz mam Bullguard IS na rok za free 😄 .

**Comment by xxcriticxx** [comment]
@hawkeye116477 ja mam mr format i mr image :)
