### ISSUE TITLE
top-strony.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4464]
reklama sponsorowanna

**Comment by MajkiIT** [comment]
@xxcriticxx to jest cały header `http://www.top-strony.com.pl/templates/default/images/header.jpg`

**Comment by userOperaFF** [comment]
`https://i.imgur.com/XnkApsG.png`

jakby się uprzeć można by podmienić tło w ublocku ale to prowizorka / sztuka dla sztuki.

Z przesunięciem na lewo diva lub wyśrodkowania nie próbowałem (bez zmiany tła nie ma to sensu).
