### ISSUE TITLE
ostrzeszowinfo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4470]
podobne do #4370  strona sie rozlewa 

![capture](https://user-images.githubusercontent.com/15007183/32777589-b56d7240-c904-11e7-9f2a-6c8bde6c3e62.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx U mnie jest ok. A jaką przeglądarkę i wersję uBlocka masz?

**Comment by xxcriticxx** [comment]
@hawkeye116477 

ubo 1.14.16
chrome 62.0.3202.94

**Comment by mat41997** [comment]
u mnie to samo

**Comment by hawkeye116477** [comment]
Nie posiadam Chrome 62, mam Vivaldi, który jest oparty o Chromium 61. Zapewne to jest bug związany z Chromium 62. Google dodało chyba ostatnio jakieś blokowanie reklam czy coś w tym stylu, może to u was powoduje problemy.

**Comment by hawkeye116477** [comment]
@xxcriticxx @mat41997 Sprawdzilem na Chromium 62 i mam ten sam efekt jak wy, ale to jest wina pingwina, uBlock Protector Extension to powoduje, po wyłączeniu jego, jest ok.

**Comment by xxcriticxx** [comment]
@hawkeye116477 racja na foxie jest good

**Comment by hawkeye116477** [comment]
https://github.com/jspenguin2017/uBlockProtector/commit/8a55bcaadc8120c402f1aa952ad41d4c4c5e17b3
