### ISSUE TITLE
AdNauseam

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4472]
ktos rozumie o co chodzi w tym projekcie

https://github.com/dhowe/AdNauseam

**Comment by mat41997** [comment]
o mieszanie w reklamach, dlatego google zablokowało ten projekt w swoim sklepie

**Comment by hawkeye116477** [comment]
https://www.dobreprogramy.pl/Google-usunelo-AdNauseam-ze-sklepu-Chrome-dodatek-ktory-dezorientowal-trackery-reklamowe,News,78363.html
