### ISSUE TITLE
Redundant Rule Checker

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4473]
@MajkiIT pokazuje 75 blendy czy jest czym sie martwic?

The following 75 errors, warnings or optimalizations were encountered while checking the rules:

https://arestwo.org/famlam/redundantRuleChecker.html

**Comment by MajkiIT** [comment]
przejrzę. Dzięki

**Comment by hawkeye116477** [comment]
Jest parę powtórzeń,np:
> ||naekranie.pl/wp-content/themes/naekranie/templates/welcome_screen.mustache has been made redundant by ||naekranie.pl/wp-content/themes/naekranie/templates/welcome_screen.mustache

>opolak.pl,poznaniak.pl,szczeciniak.pl,toruniak.pl,szczeciniak.pl,warszawiak.pl,wroclawiak.pl,katowiczak.pl,bialostoczak.pl,kaliszak.pl,gdyniak.pl,gdanszczak.pl,czestochowiak.pl,bydgoszczak.pl,krakusik.pl##ins[data-baner="true"] : Domain 'szczeciniak.pl' exists multiple times

Są też niepotrzebne spacje i wcięcia w paru miejscach.

**Comment by xxcriticxx** [comment]
no widze jest tego troche

**Comment by MajkiIT** [comment]
@xxcriticxx  @hawkeye116477 jutro zerkne

**Comment by MajkiIT** [comment]
@hawkeye116477 @xxcriticxx Pierwsza czystka zrobiona.

**Comment by krystian3w** [comment]
https://www.certyficate.it/redundant_checker/redundantRuleChecker.html
