### ISSUE TITLE
stooq.pl / stooq.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4474]
@MajkiIT strona caly czas cos laduje

**Comment by MajkiIT** [comment]
chce pobierać to `https://aq.stooq.com/?q=aqdat1+aqmrk1+wig1+wig201+fw201+wig20usd1+mwig401+swig801+^spx1+^ndq1+eurpln1+usdpln1+eurusd1+cl.f1+xauusd1+cdr1+eur1+pko1+ink1+mci1+bml1+idt1+kzs1+qmk1`

**Comment by xxcriticxx** [comment]
gielda?

**Comment by MajkiIT** [comment]
tak.
