### ISSUE TITLE
antyradio.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4478]
radiostacja 

http://www.antyradio.pl/Film/Seriale/Twin-Peaks-z-3-sezonem-trafi-do-polskiej-telewizji-14244

![capture](https://user-images.githubusercontent.com/15007183/32864339-cbdcc6d8-ca2c-11e7-979c-c408ccabe0d3.PNG)

**Comment by gzenio22** [comment]
antyradio.pl##.banner-radiostacja

nadal nie umiem znalesc tych kresek co daja regule na klawiaturze slepy jestem
