### ISSUE TITLE
resortpro.ht-int.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4479]
cookies

**Comment by gzenio22** [comment]
ja widze tu tylko popup z jakims bodaj newsletterem i 10 % znizki za zapisanie sie do niego @hawkeye116477 zdecyduj czy to ukrywaciejak tak to

resortpro.ht-int.com##.newsletter-overall

**Comment by hawkeye116477** [comment]
@gzenio22 Popupy, newslettery, itp to do PopupBlockera
Ciastka są -> `resortpro.ht-int.com##.top-disclaimer`
Ale też widzę tu jakieś podejrzane skrypty z http://x.sare25.com/, znowu jakieś kopary 😃 ?

**Comment by MajkiIT** [comment]
@hawkeye116477 to skrypt to badania tego co robi user w tym klikanie myszką.
