### ISSUE TITLE
chip.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4480]
![2017-11-16 00_47_00-test_ samsung dex w praktyce czesc 1 - chip](https://user-images.githubusercontent.com/5884000/32866380-ca361254-ca67-11e7-91c7-ac85a96a2532.png)
`http://www.chip.pl/2017/11/test-samsung-dex-praktyce-czesc-1/`

puste klikalne miejsce po reklamie

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.84
chrome 62.0.3202.94

**Comment by gzenio22** [comment]
chip.pl###banner-top

@mat41997 Nadal nie wiem gdzie na klawiaturza sa te kreski co tworza regule :D haha

**Comment by mat41997** [comment]
@gzenio22 mnie nie pytaj, ja mam podświetlaną. chociaż nie, możesz spróbować sobie policzyć używając osi xy
![akyxxw](https://user-images.githubusercontent.com/5884000/32866781-a4d7a3fe-ca69-11e7-9d80-e6aae3f994ca.png)

ewentualnie zbinduj sobie gdzieś indziej.
