### ISSUE TITLE
chomikuj.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4482]
`http://chomikuj.pl/cechu_rc/Audio+book/audiobooki/Peter+V+Brett+Pustynna+Wlocznia+II,4301087693.mp3(audio)`

po pół godziny materiał się zatrzymuje/restartuje

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.84
chrome 62.0.3202.94

**Comment by userOperaFF** [comment]
W operze 49 poleciał aż do 42 minuty, potem już mi się nie chciało czekać.

**Comment by xxcriticxx** [comment]
lektor kiepski

**Comment by mat41997** [comment]
u mnie tylko raz pojawił się ten błąd, mimo to postanowiłem go zgłosić.
