### ISSUE TITLE
[ciacha] serwis.currenda.pl

### ISSUE THREAD

**Issue by maciejtarmas** [MajkiIT/polish-ads-filter#4483]
Prośba o dodanie dla tych wszystkich 3 ludzi, którzy tam wchodzą z Adblockiem i kłuje ich w oczy info o ciastkach ;]

``serwis.currenda.pl##div#sign_up``

<img width="1439" alt="screen shot 2017-11-16 at 06 36 31" src="https://user-images.githubusercontent.com/3435387/32875503-98eb0034-ca98-11e7-873c-c0d8b3f09b73.png">

**Comment by mat41997** [comment]
@maciejtarmas "Dla aż 3 ludzi"

**Comment by hawkeye116477** [comment]
Jeszcze trzeba usunąć margines -> `serwis.currenda.pl##div:style(margin-top: auto!important;)`
