### ISSUE TITLE
nacjonalista.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4484]
![2017-11-17 00_07_35-nacjonalista pl - dziennik narodowo-radykalny nowoczesny nacjonalizm trzecia p](https://user-images.githubusercontent.com/5884000/32920908-82de2fda-cb2b-11e7-8d0a-25c3269a6313.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.86
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
```
nacjonalista.pl##DIV[align="center"]
nacjonalista.pl##.napis
```
