### ISSUE TITLE
movieway.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4485]
![2017-11-17 00_14_00-movieway - droga przez kino](https://user-images.githubusercontent.com/5884000/32921045-43aaa900-cb2c-11e7-83d4-5d32497f3951.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.86
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`movieway.pl##IMG[alt="Image Widget"]`
