### ISSUE TITLE
strefawolnejprasy.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4486]
![2017-11-17 00_17_33-strefa wolnej prasy - przeglad prasy i mediow felietony recenzje](https://user-images.githubusercontent.com/5884000/32921178-d72a776e-cb2c-11e7-92e5-808b4bc7a75c.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.86
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
Powiadomienia -> `||cdn.pushassist.com/account/assets/psa-swp.js`
