### ISSUE TITLE
computerworld.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4487]
![2017-11-17 00_28_04-computerworld - wiadomosci it biznes it praca w it konferencje](https://user-images.githubusercontent.com/5884000/32921566-786a2ee8-cb2e-11e7-87e5-86f49ee51ab3.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.86
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`computerworld.pl###tui-animation`
