### ISSUE TITLE
kliknijwzdrowie.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4488]
![2017-11-17 00_38_02-zdrowie - choroby porady leczenie odzywianie zdrowie i uroda](https://user-images.githubusercontent.com/5884000/32921873-a862d180-cb2f-11e7-860f-bebc8453c1fe.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.86
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
U mnie ok. @xxcriticxx @hawkeye116477 zerkniecie ?

**Comment by hawkeye116477** [comment]
@MajkiIT U mnie też ok.

**Comment by xxcriticxx** [comment]
dziala nawet reklama jest 

![capture](https://user-images.githubusercontent.com/15007183/32967575-199a6152-cbac-11e7-9617-15e8142e78b6.PNG)

**Comment by mat41997** [comment]
Fanboy’s Annoyance List​

**Comment by MajkiIT** [comment]
kliknijwzdrowie.pl##.image_link
