### ISSUE TITLE
purepc.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4489]
![2017-11-17 00_46_18-purepc - wiemy co sie kreci](https://user-images.githubusercontent.com/5884000/32922168-4371739c-cb31-11e7-905f-2483953f0aa2.png)

wyczyść cookie/cache

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.86
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
Takie rzeczy tylko na Chromowatych przeglądarkach, one nie obsługują styli użytkownika, przez co cwaniaczki mogą robić takie sztuczki.

**Comment by userOperaFF** [comment]
`purepc.pl##script:inject(setTimeout-defuser.js, ub_fix())`

wycieli "`o`".

Tylko czekać aż jakoś zamaskują / zaciemnią kod.

**Comment by xxcriticxx** [comment]
@hawkeye116477 cookies na dole 

Wydawca serwisu PurePC.pl informuje, że na swoich stronach www stosuje pliki cookies (tzw. ciasteczka). Kliknij zgadzam się, aby ta informacja nie pojawiała się więcej. Kliknij polityka cookies, aby dowiedzieć się więcej, w tym jak zarządzać plikami cookies za pośrednictwem swojej przeglądarki.

**Comment by hawkeye116477** [comment]
@xxcriticxx Ciastka są dlatego, że oni stosują takie sztuczki, ale po dodaniu reguły od @userOperaFF , znikają.

**Comment by xxcriticxx** [comment]
@hawkeye116477 prosimy nowego pull request

**Comment by userOperaFF** [comment]
Jak coś to w Firefox link zostaje klikany, trzeba by wciąć dla Firefox?

**Comment by hawkeye116477** [comment]
`www.purepc.pl##a[href^="https://www.purepc.pl/r3dir.php"]`
