### ISSUE TITLE
wawalove.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4490]
![2017-11-17 00_54_06-wawalove wiadomosci i informacje kulturalne z warszawy](https://user-images.githubusercontent.com/5884000/32922315-e155c1e4-cb31-11e7-8208-7479976d8be7.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.86
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
```
wawalove.pl##.floating-ad.advertisement
wawalove.pl##a[href="http://dajsygnal.pl/"]
```
