### ISSUE TITLE
marihuanamedyczna.com

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4491]
![2017-11-17 00_55_20-marihuana medyczna_ badania dzialanie na choroby informacje thc i cbd](https://user-images.githubusercontent.com/5884000/32922354-0ea91c72-cb32-11e7-8213-6ee150d6f5e9.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.86
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
@mat41997 ty tylko bitcoiny i marihuana medyczna *tisk*tisk*

**Comment by MajkiIT** [comment]
```
marihuanamedyczna.com##.x-content-dock.right.x-content-dock-on
marihuanamedyczna.com##A[target="_blank"] > IMG
```
