### ISSUE TITLE
ndie.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4492]
![2017-11-17 03_55_24-szwedka zgwalcona przez syryjskiego imigranta popelnila samobojstwo _ ndie pl](https://user-images.githubusercontent.com/5884000/32927124-36fd8f28-cb4b-11e7-8aae-d5cf4e707557.png)
`https://ndie.pl/szwedka-zgwalcona-syryjskiego-imigranta-popelnila-samobojstwo/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.86
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`ndie.pl##DIV + A > IMG[style="width:100%;"]`
