### ISSUE TITLE
drhtv.com.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#4497]
Porcja reklam w playerze pewnie potrzebny bedzie @F4z albo ktos kto siedzi w playerach 

Przyklad:  http://www.drhtv.com.pl/drhtv1.html

![screenshot_1](https://user-images.githubusercontent.com/21177361/32966174-327d9a36-cbd9-11e7-8657-7a643bdf9733.png)

**Comment by F4z** [comment]
Z listy AdGuarda (możliwe, że nie wszystkie są potrzebne):
`bro.adca.st###propis`
`||images.futbolbase.us/*.html$domain=bro.adca.st`
`||assets.bro.adca.st/rectangular.html`
`||assets.bro.adca.st/cuadrado.html`
`||static.bro.adca.st/promo.html`

Dodatkowo:
`||d1f5rbi95y1icu.cloudfront.net^`

Wydaje mi się, że tam jest jeszcze coś do zablokowania, ale w tej chwili nie chce mi się dokładniej sprawdzać.

**Comment by xxcriticxx** [comment]
chyba widze ducha nie to tylko @F4z
