### ISSUE TITLE
www.gry-online.pl + tvgry.pl

### ISSUE THREAD

**Issue by Piter432** [MajkiIT/polish-ads-filter#450]
Pierwszy filtr kosmetyczny do gry-online.pl w liście „Adblock polskie reguly social” powoduje, że ukrywana jest cała górna belka na tej stronie i nie da się ani zalogować, ani zarejestrować, chyba że wyłączy się kosmetyczne filtrowanie.

Proponowałbym tamten pierwszy filtr zamienić na te (ukrywa przycisk logowania za pomocą Facebooka oraz strony gry-online.pl na Google'u+, Facebooku i Twitterze na górnej belce, zamiast ukrywać całą górną belkę, co chyba jest lepsze, jeśli chce się zarejestrować lub zalogować na gry-online.pl, prawda? ;]):
>www.gry-online.pl###topbar > .super-bot > .sbut2.sbut
>www.gry-online.pl###topbar > .super-bot > .sbuts8.sbuts[href="http://www.facebook.com/golpl"]
>www.gry-online.pl###topbar > .super-bot > .sbuts7.sbuts[href="https://twitter.com/golpl"]
>www.gry-online.pl###topbar > .super-bot > .sbuts6.sbuts[href="https://plus.google.com/u/0/114553949128568327951"]

---

Natomiast filtr `www.gry-online.pl##.gc-m5.gc` ukrywa puste miejsce po stronie Facebookowej gry-online.pl i reklamie obok tej strony na witrynach z informacją o grze, oczywiście po wybraniu dowolnej platformy dla danej gry.

Te pierwsze filtry proszę dać do listy „Adblock polskie reguly social”, a ten drugi pojedynczy do ogólnej listy filtrów dla polskich stron.

**Comment by xxcriticxx** [comment]
peter ty hyba duzo grasz?

**Comment by Piter432** [comment]
@xxcriticxx: Nie, ale chyba ogarnąłem o co chodzi z filtrami kosmetycznymi w uBlocku Origin, więc staram się pomóc :P

**Comment by xxcriticxx** [comment]
@Piter432 ja uzywam element picker mode z uBlocka do robiena filtrow kosmetycznych

**Comment by MajkiIT** [comment]
@Piter432 dzięki za pomoc. Jutro dodam to do filtrów.

**Comment by Piter432** [comment]
Jeszcze jeden filtr ukrywający przycisk Facebooka obok przycisku zalogowania się na konto na górnej belce strony. Co prawda na tvgry.pl, ale strona należy do gry-online.pl, więc... :P 

`tvgry.pl###wrapper > header > .nav-t > .mbut-fb.mbut`

**Comment by Piter432** [comment]
@xxcriticxx: Tak, tak. Właśnie o tym piszę ;) Z początku nie bardzo ogarniałem, o co biega, ale już zaczęło się to zmieniać :)
