### ISSUE TITLE
cryptoweb.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4509]
![2017-11-18 18_29_32-cryptoweb pl - piszemy o bitcoinie ethereum i innych kryptowalutach](https://user-images.githubusercontent.com/5884000/32983023-88adcf10-cc8e-11e7-8cd5-159f47e8776c.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.87
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
i zaraz bendzie marycha

**Comment by hawkeye116477** [comment]
`||ad.bitbay.net^`
