### ISSUE TITLE
fishki.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4511]
na tej stronie sie otwiera ankieta 

http://fishki.pl/fishka,Lubia-imprezowac,111156,3,1.html

http://lab.ankieta-online.pl/q/programytelewizyjne_031017/a/invitation.html?g=14659&src=2&o=6047&id=YQzAuUa.270M4SreYf8BBPh7&v=0&c=6047&xc=CB6EF021&debugtimes=1511035161474,1511035165286,1511035088079,1511035092347

![capture](https://user-images.githubusercontent.com/15007183/32984256-364af058-cc71-11e7-8fb4-4c03439030eb.PNG)

**Comment by MajkiIT** [comment]
Ja tego nie mam . @hawkeye116477 zerkniesz?

**Comment by mat41997** [comment]
ja mam szarą mgiełke i nic nie mg. kliknąć
![2017-11-19 17_15_30-lubia imprezowac - fishki pl](https://user-images.githubusercontent.com/5884000/32992647-55da0f9e-cd4d-11e7-9498-bdfd339eb92f.png)

**Comment by MajkiIT** [comment]
@mat41997 mgiełka to pozostałość social

**Comment by hawkeye116477** [comment]
@MajkiIT Ja nie mam ankiety, ale po kliknięciu na zdjęcie, powinno się raczej wyświetlić powiększone w popupie, a tak się nie dzieje, bo jest dana reguła -> `fishki.pl###fancybox-wrap`, która najwyraźniej to blokuje.

**Comment by xxcriticxx** [comment]
@hawkeye116477 czyli moj komputer i5 3.0 ghz jest za wolny?

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie wiem,  ja mam AMD Athlon II X4 620 2,6 GHz, więc to niby mój powinien być wolniejszy
