### ISSUE TITLE
holenderskiskun.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4513]
![2017-11-18 23_01_35-nasiona marihuany - sklep internetowy - holenderskiskun pl](https://user-images.githubusercontent.com/5884000/32985163-91484bde-ccb4-11e7-867f-f859d61bad76.png)

puste miejsce

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.87
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`holenderskiskun.pl##.banner-slider.slider`
