### ISSUE TITLE
Pytanie o Ublock Origin.

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#4518]
Dlaczego Ublock Origin nadal nie blokuje adserver od tvn na domenie redcdn.pl ? Adguard już sobie dawno z tym radzi i takie strony, jak miniminiplus.pl , teletoonplus.pl czy player.pl działają bez reklam. Reguła z Adguard : ||redcdn.pl/*Adserver/*.mp4$media,empty,important nie działa z Ublock Origin i są wyświetlane 30s wideo. 
I co zrobiliście, że przy obecności Adguard jest wszystko blokowane tutaj i niedostępne?

**Comment by userOperaFF** [comment]
Może ten filtr nie jest obecnie zgodny z "składnią uBO" mimo że Gorhill ją dodał.

Albo w AdGurad coś przebudowali by działał.

**Comment by seba2282** [comment]
Np. ten link : 
http://www.miniminiplus.pl/filmy/pokaz/my-little-pony-duchy
Ublock Origin + Firefox lub Microsoft Edge (wszystkie filtry bez ignorowania kosmetycznych) i widzę 30s reklamy. Dlatego mam teraz chwilowo Adguard. Druga sprawa: gdy Adguard jest aktywny, to linki do zgłoszeń jak i odpowiednich działów certificate it są ukrywane, jakby ktoś nałożył celową blokadę dla aktywnego Adguard.

**Comment by hawkeye116477** [comment]
A to ciekawe, bo u mnie na tym linku 0 reklam.

**Comment by seba2282** [comment]
Bo to pojawia się praktycznie po którymś tam obejrzeniu któregoś z rzędu filmiku. Ja podałem link, gdzie najczęściej to się zaczyna pojawiać.

**Comment by userOperaFF** [comment]
Ja mam praktycznie czysty odtwarzacz html5, dynamicznie go podmieniają / wciskają reklamę...?

https://addons.mozilla.org/en-US/firefox/addon/html5-video-everywhere/ - możesz zobaczyć czy będzie działać, ja usunęłam bo na YT przedłużał czas rozpoczęcia odtwarzania o 5 sek (przebudowa na czysty odtwarzacz html5 przeglądarki).

**Comment by seba2282** [comment]
Z MS Edge to nie zadziała. Z Firefox jak ponownie go jeszcze zainstaluję, to się pobawię. Ale to i tak połowiczne rozwiązanie (o ile zadziała na Firefox).

**Comment by seba2282** [comment]
@MajkiIT Jakieś sugestie? Dlaczego Adguard normalnie sobie radzi z playerami TVN, a Ublock Origin nie?

**Comment by MajkiIT** [comment]
@seba2282 mówisz o Adguard jako dodatek do przeglądarki?

**Comment by mat41997** [comment]
@seba2282 ubo z ubo-pe radzi sobie doskonale z playerem tvn'u.
https://jspenguin2017.github.io/uBlockProtector/

**Comment by hawkeye116477** [comment]
Tylko, że niestety Protectora nie ma na Edge, także @seba2282 musi czekać aż pojawi się Adblock Protector 2 na Edge albo korzystać z Adguarda albo załadować jako rpozkowane rozszerzenie z https://github.com/AdBlockProtector2/AdBlockProtector2 jeśli się da, bo ja nie mam W10, więc nie wiem jak to w tym M$ tam to jest 😄 .

**Comment by seba2282** [comment]
@MajkiIT Mówię o AG jako rozszerzenie. Nie wiem dlaczego z kolei znowu UBO przestał blokować ten Adserver. AG miał ten sam problem i chłopaki dodali regułę, o której wspomniałem. Ale ta reguła nie działa niestety z UBO.

**Comment by seba2282** [comment]
@MajkilT Jakieś szczegóły, dlaczego UBO znowu tak robi? Kiedy poprawki dla Edge, Firefox i itp.?

**Comment by hawkeye116477** [comment]
@seba2282 uBlockiem dla Edge zajmuje się inny koleś niż tym dla Firefoxa i Chroma i jak widać rozwój obecnie stoi w miejscu -> https://github.com/nikrolls/uBlock-Edge. U mnie na Vivaldim z uBlockiem i Protectorem, normalnie reklamy są blokowane na player.pl.
