### ISSUE TITLE
expresselblag.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4519]
![2017-11-20 00_49_12-expresselblag pl - calodobowe wydarzenia - elblag - region](https://user-images.githubusercontent.com/5884000/32997184-a9d43cde-cd8c-11e7-8934-583874e1ddac.png)

![2017-11-20 00_45_21-_doprowadzacie mnie do smierci_ elblazanin napisal list do zus - expresselblag](https://user-images.githubusercontent.com/5884000/32997189-b823d2f4-cd8c-11e7-90e7-fde86701e1f5.png)
http://expresselblag.pl/wydarzenia/doprowadzacie-mnie-do-smierci-elblazanin-napisal-list-do-zus/

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.87
chrome 62.0.3202.94

**Comment by gzenio22** [comment]
expresselblag.pl##.all-services

**Comment by MajkiIT** [comment]
@mat41997 @gzenio22 nadal to widzicie?

**Comment by mat41997** [comment]
@MajkiIT tak

**Comment by gzenio22** [comment]
Ja nie widze

**Comment by xxcriticxx** [comment]
@MajkiIT  yes

![capture](https://user-images.githubusercontent.com/15007183/33127375-3d368a7a-cf56-11e7-9c38-6e9bbf882864.PNG)
