### ISSUE TITLE
pudelekx.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4523]
![2017-11-20 20_31_54-pudelekx](https://user-images.githubusercontent.com/5884000/33037499-075bdb96-ce32-11e7-9dd0-b0751611ae69.png)

wyczyść cookie/cache

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.89
chrome 62.0.3202.94

**Comment by gzenio22** [comment]
pudelekx.pl##.fixed-advertisement

U mnie to byla biegajaca reklama gry big farm Xd sprawdz czy to pomoze
