### ISSUE TITLE
pudelek.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4524]
![2017-11-20 20_38_15-edukacja seksualna w _klanie__ grazynka uczy macka seksu na preclach wideo - p](https://user-images.githubusercontent.com/5884000/33037739-c6db6efa-ce32-11e7-8728-1c5ec5b07eeb.png)
https://www.pudelek.pl/artykul/119628/edukacja_seksualna_w_klanie_grazynka_uczy_macka_seksu_na_preclach_wideo/

wyczyść cookie/cache

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.89
chrome 62.0.3202.94

**Comment by gzenio22** [comment]
pudelek.pl##.bbtext.single-entry-text > .mtb15

Pewnie ktos da cos lepszego te reklamy sa generowane losowo
