### ISSUE TITLE
easycoin.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4527]
![2017-11-20 20_54_52-gielda bitcoin polcoin](https://user-images.githubusercontent.com/5884000/33038554-56ab3694-ce35-11e7-892e-ea65d630295b.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.89
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
@mat41997 U mnie jest ok.
@hawkeye116477 @xxcriticxx zerkniecie?

**Comment by xxcriticxx** [comment]
@MajkiIT ja widze cala strone

**Comment by hawkeye116477** [comment]
@mat41997 To znowu wina Fanboy's Annoyance List. Napisz do fanboya, niech doda wyjątek `@@||www.easycoin.pl/directive/cookies-info.html` .

**Comment by mat41997** [comment]
@hawkeye116477 ich responsywność jest mocno ograniczona : P
