### ISSUE TITLE
tvs.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4533]
![2017-11-21 16_28_40-telewizja tvs](https://user-images.githubusercontent.com/5884000/33080929-801fe642-ced9-11e7-8d6f-09a59a9865b2.png)

wyczyść cookie/cache

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.93
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
`@@||tvs.pl/wp-content/plugins/uk-cookie-consent/assets/js/uk-cookie-consent-js.js`

**Comment by xxcriticxx** [comment]
@hawkeye116477 juz po szkole?

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie, jeszcze zajęcia mam, teraz przerwa jest, jeszcze do 23:30 😃 .

**Comment by xxcriticxx** [comment]
nocne studia :)

**Comment by MajkiIT** [comment]
@hawkeye116477 co to za uczelnia ?

**Comment by xxcriticxx** [comment]
Uniwersytet trzeciego wieku

**Comment by hawkeye116477** [comment]
@MajkiIT @xxcriticxx Heh, no co wy, ja sobie jaja robię 😄 , Najpóźniej to mam w czwartek do 20:15.
