### ISSUE TITLE
sadistic.pl 

### ISSUE THREAD

**Issue by Nalapl3** [MajkiIT/polish-ads-filter#4536]
![image](https://user-images.githubusercontent.com/9704046/33097814-9d51daea-cf0b-11e7-986b-386506126bb7.png)

**Comment by xxcriticxx** [comment]
@mat41997 zgloszone do pigwina?

**Comment by mat41997** [comment]
@xxcriticxx pingwin zastrzega sobie żeby nie zgłaszać do niego jak da się to zablokować inaczej.

dacie radę to zablokować bez protektora?

**Comment by Nalapl3** [comment]
Moje filtry (ktore nie daly sobie rady):
uBlock filters​
* ​​​​2,110 used out of 2,147​​
* ​​
* uBlock filters – Badware risks​
* ​​uBlock filters – Experimental​
* ​​​​uBlock filters – Privacy​​​​​
* ​uBlock filters – Resource abuse​​​​​
* ​​uBlock filters – Unbreak​​​​​
* Adblock Warning Removal List​
* Adguard Base Filters​
* ​​​​EasyList​
* ​​​​EasyPrivacy​
* ​​​​Malvertising filter list by Disconnect​​​​​
* ​​Malware Domain List​​​​​
* Malware filter list by Disconnect​​​​​
* Fanboy’s Annoyance List​
* ​​​​POL: polskie filtry do Adblocka i uBlocka​
* POL: polskie filtry do uBlocka uzupelnienie​
* AAK-Cont Filter For uBlock Origin​​​​
* AakList (Anti-Adblock Killer)​​​
* Block-EU-Cookie-Shit-List​​
* NoCoin Filter List​​
* ​​Polskie filtry cookies​​
* ​​Popup Blocker PLUS​​
* Prebake - Filter Obtrusive Cookie Notices​​
* uBlock Protector List​​
* YouTube blocking filters for uBlock Origin​​

**Comment by mat41997** [comment]
@Nalapl3 ahh.. chodzi o to czy @xxcriticxx & @MajkiIT dadzą radę zablokować to samodzielnie.

**Comment by hawkeye116477** [comment]
U mnie jest ok, nie ma żadnego anty adblocka.

**Comment by xxcriticxx** [comment]
@hawkeye116477 pigwin poprawil wczoraj

**Comment by hawkeye116477** [comment]
@xxcriticxx Tyle, że u mnie nie ma tego nawet jak mam wyłączony Protector, zapewne jest tak jak pisze ublock-user, czyli wyłączyli ten skrypt i będą jeszcze pewnie coś kombinować.
