### ISSUE TITLE
dostawczakiem.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4544]
![2017-11-23 03_39_21-dostawczaki samochody dostawcze furgony - testy porady aktualnosci](https://user-images.githubusercontent.com/5884000/33157121-00016f76-d000-11e7-8a62-07fe6e87ea60.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.98
chrome 62.0.3202.94

**Comment by gzenio22** [comment]
dostawczakiem.pl##.dosta-widget.widget
dostawczakiem.pl###reklamowkaBottom

Sorki ze nie na szaro no ale no nie widze tych znaczkow co to powoduja na klawiaturze

**Comment by mat41997** [comment]
@gzenio22 pod esc masz, wyklikaj.
