### ISSUE TITLE
gamedot.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4545]
![2017-11-23 03_41_09-newsy recenzje video oraz artykuly o grach i sprzecie dla graczy - gamedot pl](https://user-images.githubusercontent.com/5884000/33157153-3905707e-d000-11e7-8696-89682e88b4a8.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.98
chrome 62.0.3202.94

**Comment by gzenio22** [comment]
gamedot.pl##.content-columns-right-inner.content-module:nth-of-type(1)

**Comment by MajkiIT** [comment]
@mat41997 co jest nie tak?

**Comment by mat41997** [comment]
@MajkiIT sekcja "zobacz w sklepie"

**Comment by MajkiIT** [comment]
@mat41997 ale to link wewnętrzny

**Comment by mat41997** [comment]
@MajkiIT dlatego musisz zrobić listę dla filtrów wewnętrznych ^^
https://github.com/MajkiIT/polish-ads-filter/pull/4555

**Comment by mat41997** [comment]
@MajkiIT w przeciwnym razie reklamodawcy będą srogo nadużywać tego że nie blokujesz treści wewnętrznych.
