### ISSUE TITLE
sitemag.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4546]
![2017-11-23 03_44_45-sitemag pl - najlepszy strumien informacji magazyn online](https://user-images.githubusercontent.com/5884000/33157221-c81c3932-d000-11e7-93d0-62b992b74c3a.png)

![2017-11-23 03_45_09-sitemag pl - najlepszy strumien informacji magazyn online](https://user-images.githubusercontent.com/5884000/33157224-cd1fb3b4-d000-11e7-99a5-3520da481dc8.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.98
chrome 62.0.3202.94

**Comment by gzenio22** [comment]
sitemag.pl##.td-header-rec-wrap
sitemag.pl##.td_block_template_8.td_uid_47_5a16a02417d3a_rand
@hawkeye116477  instagram do socjali?

**Comment by hawkeye116477** [comment]
```
||static.whatshelp.io/widget-send-button/js/init.js$script
sitemag.pl##.td-instagram-element, .td-instagram-header
```
