### ISSUE TITLE
ads is like aids

### ISSUE THREAD

**Issue by hasuu** [MajkiIT/polish-ads-filter#4548]
### Co trzeba zrobić aby reklama/element się pojawił
1.Streamer ma swoje reklamy
2.
3.

### Twoja konfiguracja
**Przeglądarka:**
chrome
**Operating system:**
win10
**Blocker:**
adblock
wstaw tutaj link https://www.twitch.tv
```

**Comment by mat41997** [comment]
wgraj ublock origin i ublock protector
https://jspenguin2017.github.io/uBlockProtector/
