### ISSUE TITLE
Nie typowa prośba

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#4549]
Hej słuchajcie znalazłem mały ewenement w internetach niestety nie związany z listami jako takimi ale potrzebuje pomocy 

Strona : http://bestforkodi.com/? Blokuje mozliwość kopiowania czy zaznaczania tekstu :D pierwszy raz sie z tym spotykam mozna to jakos odblokowac?

**Comment by MajkiIT** [comment]
dodaj w Ubo ==> `||bestforkodi.com/**$inline-script`

**Comment by gzenio22** [comment]
@MajkiIT nie pomaga nadal nie moge zaznaczac tekstu

**Comment by MajkiIT** [comment]
ubo ?

**Comment by gzenio22** [comment]
yes

**Comment by MajkiIT** [comment]
@gzenio22 a może wyczyść cache. U mnie od razu pomaga.

**Comment by gzenio22** [comment]
@MajkiIT czyscilem nawet CC Cleanerem

**Comment by xxcriticxx** [comment]
@MajkiIT no work na chromie

**Comment by mat41997** [comment]
@gzenio22 ja zawsze używam trybu programistycznego
![2017-11-24 06_22_09-upcoming televised football - where to watch the games - best for kodi](https://user-images.githubusercontent.com/5884000/33196534-1032be3c-d0e0-11e7-8fe1-bff4265f5758.png)

**Comment by userOperaFF** [comment]
- https://greasyfork.org/pl/scripts/29755-select-click-copy-enabler
- https://greasyfork.org/pl/scripts/23772-absolute-enable-right-click-copy

:warning:  twórcy ostrzegają że może psuć strony :warning:

komunikaty czy skrót <kbd>Ctrl</kbd>+<kbd>A</kbd> wyłączysz  wspomnianym: `||bestforkodi.com/**$inline-script`

**Comment by userOperaFF** [comment]
```
||bestforkodi.com/**$inline-script
bestforkodi.com##body:style(-webkit-touch-callout: text !important; -webkit-user-select: text !important;-moz-user-select: text !important;-ms-user-select: text !important;user-select: text !important;)
```

blokada skryptów liniowych odblokuje skróty klawiszowe, prawoklik; css odblokuje zaznaczenie.

<div align="center">

:small_red_triangle:  z grafikami jest problem ich tak nie zaznaczysz :small_red_triangle: 

</div>

---

- https://greasyfork.org/pl/scripts/29755-select-click-copy-enabler
- https://greasyfork.org/pl/scripts/23772-absolute-enable-right-click-copy

Będzie można zaznaczać normalnie z grafikami (czerwone ostrzeżenia i skróty klawiszowe wyłącza podany już wcześniej filtr).

**Comment by gzenio22** [comment]
@userOperaFF @MajkiIT  wielkie dzieki dziala :) zamykam :) jestescie wielcy :D

**Comment by krystian3w** [comment]
@gzenio22 sprzątnij sobie reguły, bo strona padła a masz ciągle na liście filtrów własnych.

**Comment by krystian3w** [comment]
Jak coś, to jest to też w uBO Annoyance:

<ul> 

 [uBO annoyance - Subskrybuj][uBO annoyance - Subscribe] <sup>(Proszę <ins>**odświeżyć**</ins> stronę zgłoszenia przed próbą automatycznej subskrypcji by się powiodła)</sup>



[uBO annoyance - Subscribe]: https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances.txt&title=annoyances%20uBO

</ul>

w łagodniejszej formie.
