### ISSUE TITLE
www.commit.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#455]
cookies

Ten serwis wykorzystuje pliki cookies. Wszystkie zasady ich używania wraz z informacjami
o sposobie wyrażania i cofania zgody na używanie cookies, opisaliśmy w Polityce Prywatności.
Korzystając z serwisu akceptujesz jej postanowienia.

**Comment by MajkiIT** [comment]
wartość statyczna.
