### ISSUE TITLE
centrum-dramy.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4562]
![2017-11-24 12_27_43-kamen rider blade 31 pl centrum dramy pl najnowsze dramy online hd](https://user-images.githubusercontent.com/5884000/33208814-5e3d4ce0-d113-11e7-8721-1faac4effbda.png)
https://centrum-dramy.pl/video/kamen-rider-blade-31-pl/

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.104
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`/^(http|https):\/\/[a-z.-]{5,30}\/client\?party/$script,domain=openkatalog.com`
