### ISSUE TITLE
pomponik.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4564]
nacisnelem na logo strony 

strona:
http://www.pomponik.pl/#iwa_source=logo

ankieta:
http://lab.ankieta-online.pl/q/programytelewizyjne_031017/a/invitation.html?g=14659&src=2&o=6047&id=y_j8WysnOehi9TSQtgrtp.p7&v=0&c=6047&xc=CB6EF021&debugtimes=1511548729994,1511548782590,1511548654885,1511548708067

![capture](https://user-images.githubusercontent.com/15007183/33221400-215feef4-d11d-11e7-8740-77e360b1ee46.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx na FF ?

**Comment by xxcriticxx** [comment]
chrome

**Comment by xxcriticxx** [comment]
teraz nacisnelem nato i znowu ankieta

strona:
http://forum.interia.pl/wodka-nie-tylko-do-picia-tematy,dId,3113923

ankieta:
http://lab.ankieta-online.pl/q/programytelewizyjne_031017/a/invitation.html?g=14659&src=2&o=6047&id=ikdQgaQjEBxIUg8egJx2nfJ7&v=0&c=6047&xc=CB6EF021&debugtimes=1511633919774,1511633946366,1511633923490,1511633950650

![capture](https://user-images.githubusercontent.com/15007183/33233405-bbf0d73c-d1e3-11e7-99e2-467140707022.PNG)

**Comment by MajkiIT** [comment]
@hawkeye116477 masz to? U mnie na żadnym kompie tego nie ma.

**Comment by xxcriticxx** [comment]
@MajkiIT zaczniemy od tego zobaczymy co bendzie dalej 

`||lab.ankieta-online.pl^`
