### ISSUE TITLE
plotek.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4565]
30 sec reklama przed filmem

http://www.plotek.pl/plotek/7,78649,22690940,internauci-nie-mieli-litosci-nad-polska-barbie-ona-sie-nie.html

![capture](https://user-images.githubusercontent.com/15007183/33221445-96f09812-d11d-11e7-91e2-cea2fabd50f0.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx @hawkeye116477 
sprawdzicię tą regułę?

`||dfp.gazeta.pl/c.servlet?cn=dfpreferrer&cv=DIRECT$xmlhttprequest,domain=www.plotek.pl`

**Comment by xxcriticxx** [comment]
sie zdaje ze git potem wiczora cache wyczyszcze

**Comment by maciejtarmas** [comment]
A po co czyścić cache? Wystarczy wejść w tryb prywatny.

**Comment by xxcriticxx** [comment]
@maciejtarmas nie zawsze dziala example wp.pl

**Comment by xxcriticxx** [comment]
dalej sa reklamy 

http://www.plotek.pl/plotek/7,78649,22648050,partnerka-ronaldo-pokazala-corke-doswiadczam-najwyzszego-szczescia.html

![capture](https://user-images.githubusercontent.com/15007183/33242240-a3dab2f0-d29f-11e7-8147-a729ceca8c11.PNG)

**Comment by MajkiIT** [comment]
@F4z zerkniesz?
