### ISSUE TITLE
www.oleole.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#458]

**Comment by xxcriticxx** [comment]
cookies fix

Wykorzystujemy ciasteczka (ang. cookies) oraz podobne technologie w celu świadczenia usług, dostosowania serwisu do indywidualnych preferencji użytkowników oraz w celach statystycznych i reklamowych. Możesz zawsze wyłączyć ten mechanizm w ustawieniach przeglądarki. Korzystanie z naszego serwisu bez zmiany ustawień przeglądarki oznacza, że cookies będą zapisane w pamięci urządzenia. Więcej w Polityce prywatności

**Comment by MajkiIT** [comment]
nic nie widze.
