### ISSUE TITLE
lubsko.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4602]
![2017-11-25 01_08_31-lubsko _](https://user-images.githubusercontent.com/5884000/33225711-5b7f1eec-d17d-11e7-924c-7d9f2ef479d4.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.104
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
```
lubsko.pl##.view-mode-bez_spo_eczn
lubsko.pl##.tp-banner-container
```
