### ISSUE TITLE
gwiazdy.wp.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4604]
![2017-11-25 15_51_32-wp gwiazdy - pikantne zycie gwiazd plotki i skandale](https://user-images.githubusercontent.com/5884000/33231695-e1f59dda-d1f9-11e7-90c4-2ea45e9fe02a.png)

https://github.com/azet12/PopupBlocker/issues/214#issuecomment-346950630

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.111
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
ja tego nie widzę. Zerknij proszę czy to pomoże `wp.pl##[class^="css-"]`

**Comment by hawkeye116477** [comment]
Na Waterfoksie też tego nie mam, ale na Vivaldim jest. Czyżby znowu jakiś bug uBlocka dla Chromium?

**Comment by hawkeye116477** [comment]
@MajkiIT A ja widzę i reguła pomaga.

**Comment by mat41997** [comment]
@MajkiIT po odświeżeniu strony trochę miga, podobnie jak puste miejsce nad artykułem.

![2017-11-25 17_35_45-wp gwiazdy - pikantne zycie gwiazd plotki i skandale](https://user-images.githubusercontent.com/5884000/33232466-3faddb88-d207-11e7-8651-02099f52c667.png)

![2017-11-25 17_36_33-wp gwiazdy - pikantne zycie gwiazd plotki i skandale](https://user-images.githubusercontent.com/5884000/33232468-429c4e56-d207-11e7-917c-afaaaa6d6c4c.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 Dzięki
