### ISSUE TITLE
radio.kielce.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4606]
![2017-11-25 19_32_19-radio kielce](https://user-images.githubusercontent.com/5884000/33233538-aa6372e8-d217-11e7-9674-211ec2a2b14f.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.111
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`radio.kielce.pl##.folkRadioLink`
