### ISSUE TITLE
upolujebooka.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4608]
![2017-11-26 10_44_45-tanie ebooki online na czytnik kindle kobo pocketbook pdf mobi epub](https://user-images.githubusercontent.com/5884000/33238892-f7f1af0a-d296-11e7-9f54-d7cfae325f15.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.112
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
@mat41997 ale to znowu wewnętrzne. Zaraz zrobię ankietę.

**Comment by xxcriticxx** [comment]
@MajkiIT gdzie ta ankieta bo chce zaglosowac

**Comment by MajkiIT** [comment]
@xxcriticxx https://docs.google.com/forms/d/e/1FAIpQLSd-BhB6x391ubI_X_eb4OSj4f-E-pzbmCAjlwYOZq_meYM0kA/viewform

**Comment by xxcriticxx** [comment]
@MajkiIT Your response has been recorded.
