### ISSUE TITLE
wiesci.info.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#4616]
![2017-11-26 19_53_51-wiesci miechowskie - gazeta informacyjno-reklamowa](https://user-images.githubusercontent.com/5884000/33243292-9b661b98-d2e3-11e7-8f0b-3b8518ea1b4b.png)
`wiescimiechowskie.prv.pl`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.112
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
Tego nie ogarniesz bez skryptu, bo zostaje ci biały pasek.

**Comment by xxcriticxx** [comment]
juz dwa lata szukamy kogos do scriptow

**Comment by MajkiIT** [comment]
@xxcriticxx ja wygrzebałem jednegoi chciał 2-3 tys ms. Jak mówiłem mu, że my to robimy za free to powiedział, że tym free nie da rodzinie jedzenia.

**Comment by xxcriticxx** [comment]
trzeba zaczac zbierac donacje na piwo/kawe/server
