### ISSUE TITLE
dbpolska.net

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#4617]
![2017-11-26 19_58_00-dragon ball polska - dragon ball z gt kai oraz super odcinki z napisami do p](https://user-images.githubusercontent.com/5884000/33243325-37c92930-d2e4-11e7-8b28-d5ae4c934812.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.112
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
```
dbpolska.net###dwa_panel > center
dbpolska.net##.conntent > center:-abp-contains(Reklama)
```
