### ISSUE TITLE
regiopraca.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4618]
contentstream na dole

http://www.regiopraca.pl/portal/rynek-pracy/miejsca-pracy/amazon-poszukuje-pracownikow-w-polsce-oferty-pracy-wroclaw-poznan-szczecin

**Comment by MajkiIT** [comment]
Nie widzę tego

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/33287698-8bb4fc92-d387-11e7-88d2-c78e57bb84ae.PNG)

**Comment by MajkiIT** [comment]
`##.gwt-Anchor`
