### ISSUE TITLE
natemat.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4620]
contentstream

http://natemat.pl/223313,wciaz-cos-go-boli-saryusz-wolski-szaleje-gotowy-stanac-do-walki-z-tuskiem-w-obronie-honoru-najjasniejszej

![capture](https://user-images.githubusercontent.com/15007183/33243753-0eab8dd8-d2ba-11e7-96f7-7974842ca208.PNG)

**Comment by gzenio22** [comment]
natemat.pl##div > .kd_ns_logo

**Comment by MajkiIT** [comment]
`natemat.pl##.kd_ns_logo`
