### ISSUE TITLE
unileverfoodsolutions.pl

### ISSUE THREAD

**Issue by userOperaFF** [MajkiIT/polish-ads-filter#4627]
Po usunięciu komunikatu Cookies:
> ![image](https://user-images.githubusercontent.com/33114475/33260742-2126d68c-d361-11e7-8434-89e5e2d591b6.png)

https://www.unileverfoodsolutions.pl

---

Filtry standardowe uBlock + Cookies PL.

---

Dla uBlock supplement (eksperymentalne):
```
unileverfoodsolutions.pl##body:style(overflow: auto !important;)
unileverfoodsolutions.pl##body.blurred>*:style(box-shadow: none !important;-webkit-filter:blur(0px) !important; filter:blur(0px)  !important;)
```

Przywraca suwak / przewijanie; usuwa rozmazanie i cień pod rozmazaniem.

**Comment by xxcriticxx** [comment]
filtry sa dobre

**Comment by hawkeye116477** [comment]
Jest ok, ale drugą regułę można zapisać krócej -> `unileverfoodsolutions.pl##body.blurred>*:style(box-shadow: none!important; filter:none!important;)`

**Comment by userOperaFF** [comment]
Kwestia kompatybilności z jakimś archaicznym chrome.

**Comment by LArtCrime** [comment]
`~autocentrum.pl,~ideabank.pl,~intel.com,~pkn.pl,~topsecret.pl,~starbucks.pl,~isobar.com,~morizon.pl,~abctygodnik.pl,~wykop.pl,~bt4.pl,~kolba.pl,~tablety.pl,~tesco.pl,`**`~unileverfoodsolutions.pl`**`,~lomza.pl##div[class*="cookie"]` 

nie chce działać w chromowatych?
