### ISSUE TITLE
tychy.info

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4629]
Resztki po reklamach.
http://www.tychy.info/
![screenshot_20171127_141728](https://user-images.githubusercontent.com/19818572/33268514-ca76322a-d37d-11e7-8216-28f7158fe75b.png)
http://rozrywka.tychy.info/2429-mlodzi-prezentowali-swoje-umiejetnosci-final-vii-t-jak-talent-tychy
![screenshot_20171127_141702](https://user-images.githubusercontent.com/19818572/33268520-d000379a-d37d-11e7-8def-5523421e264b.png)
http://wiadomosci.tychy.info/2429-mlodzi-prezentowali-swoje-umiejetnosci-final-vii-t-jak-talent-tychy
http://sport.tychy.info/2431-siedmiobramkowe-zwyciestwo-trojkolorowych-w-meczu-z-janowem-tychy
http://cgk.tychy.info/2430-lech-walesa-spotka-sie-z-tyszanami-w-hotelu-tychy-tychy

Resztki social -> `tychy.info##.kol2 > .small.pasek-white, .kol3 > .small.pasek-white`

**Comment by MajkiIT** [comment]
```
tychy.info##main > .small.pasek-gray:nth-of-type(3)
tychy.info##main > .serwis.small.pasek-gray

```

**Comment by hawkeye116477** [comment]
@MajkiIT To nie wszystko, jeszcze zostały 2 resztki po reklamach -> `tychy.info##.linki-sponsorowane-col, .skyscraper`
