### ISSUE TITLE
sporteuro.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4631]
![2017-11-27 17_38_40-jutro w bydgoszczy rozpoczynaja sie ms do lat 23 w zapasach starty polakow](https://user-images.githubusercontent.com/5884000/33277896-3096f866-d39a-11e7-806a-a6da5beb24bc.png)
`http://sporteuro.pl/jutro-w-bydgoszczy-rozpoczynaja-sie-ms-do-lat-23-w-zapasach-starty-polakow/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.113
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`sporteuro.pl##.g`
