### ISSUE TITLE
swiatoze.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4636]
![2017-11-27 21_46_21-polska firma z patentem na panele fotowoltaiczne z grafenem _ swiatoze pl](https://user-images.githubusercontent.com/5884000/33288453-a5a33918-d3bc-11e7-9b5b-e99019cc2217.png)
`http://swiatoze.pl/polska-firma-patentem-panele-fotowoltaiczne-grafenem/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.113
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
```
||swiatoze.pl/wp-content/uploads/20*/*/banner-$image
swiatoze.pl###text-11
```
