### ISSUE TITLE
spottedlublin.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4637]
![2017-11-27 21_59_29-wiadomosci z lublina i regionu lubelskie lubelszczyzna i okolice](https://user-images.githubusercontent.com/5884000/33289011-6005c34c-d3be-11e7-87ec-6aa856a8f23f.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.113
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`spottedlublin.pl##[role="main"] > .row`
