### ISSUE TITLE
farmer.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4639]
![2017-11-27 22_18_18-farmer pl - portal rolniczy_ hodowla uprawa maszyny doplaty](https://user-images.githubusercontent.com/5884000/33289803-01302152-d3c1-11e7-9ca5-959540617e62.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.113
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`farmer.pl###top`
