### ISSUE TITLE
swiatdronow.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4640]
![2017-11-27 22_23_28-swiat dronow - pierwszy polski portal o dronach](https://user-images.githubusercontent.com/5884000/33290081-def6937c-d3c1-11e7-95f0-c3f67d281515.png)

![2017-11-27 22_24_03-swiat dronow - pierwszy polski portal o dronach](https://user-images.githubusercontent.com/5884000/33290085-e36e6aa6-d3c1-11e7-8f28-845555d33b2e.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.113
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
```
swiatdronow.pl##A[rel="nofollow"] > IMG
swiatdronow.pl##A[target="_blank"] > IMG
```
