### ISSUE TITLE
esanok.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4642]
![2017-11-27 22_39_38-esanok pl - sanocki portal informacyjny _ telewizja sanok _ wiadomosci sanok _ o](https://user-images.githubusercontent.com/5884000/33290753-fa829b2a-d3c3-11e7-8ab2-aa1e934350a9.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.113
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`esanok.pl##A[target="_blank"] > IMG`
