### ISSUE TITLE
expressilustrowany.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4643]
![2017-11-27 22_51_49-express ilustrowany - wiadomosci lodz wiadomosci lodzkie](https://user-images.githubusercontent.com/5884000/33291304-aa7c3e5e-d3c5-11e7-96d5-a532981e2d11.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.113
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`expressilustrowany.pl###scoopshot`
