### ISSUE TITLE
pos-poland.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4644]
![2017-11-27 23_07_32-proof of stake - pierwsza polska strona o wydobywaniu metoda pos](https://user-images.githubusercontent.com/5884000/33291934-d2145fee-d3c7-11e7-981f-0ce206582c15.png)

refy

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.113
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
to jakieś rejestracje
