### ISSUE TITLE
gloswielkopolski.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4645]
![2017-11-27 23_25_09-glos wielkopolski - wiadomosci poznan informacje poznan](https://user-images.githubusercontent.com/5884000/33292705-7d13aed4-d3ca-11e7-8fef-abdb71b3949b.png)
`http://www.gloswielkopolski.pl/strefa-agro/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.113
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`gloswielkopolski.pl##.partner`
