### ISSUE TITLE
[Grupa Pless Intermedia] bielsko.info,czecho.pl...

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4646]
Na prawie wszystkich stronach tego wydawcy są resztki po reklamach i socialu.
Na www.pless-intermedia.pl na dole są wypisane adresy.

**Comment by xxcriticxx** [comment]
wszystko bendzie `##.skyscraper` `##.linki-sponsorowane-col` cos jeszcze?

**Comment by hawkeye116477** [comment]
Na pewno będzie to do wywalenia -> `tychy.info##main > .small.pasek-gray:nth-of-type(3)`, bo za dużo chowa.

`bielsko.info, czecho.pl, pless.pl, tychy.info##.linki-sponsorowane-col, .skyscraper`

Jeszcze tu inne atrakcje:
http://www.djfranek.pl/
http://www.mojelokum.pl/
http://www.wujekfranek.pl/
http://www.turboportal.pl/
http://www.mojapraca.pl/

**Comment by xxcriticxx** [comment]
dzialaja wam strony ja dzisaj mam wiekszosc 403 Forbidden You don't have permission to access this document.

**Comment by userOperaFF** [comment]
Działają, może wchodzisz w jakiś konkretny artykuł i coś u nich jest z nim nie tak.

**Comment by xxcriticxx** [comment]
@userOperaFF photo please
