### ISSUE TITLE
newsbook.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4647]
![2017-11-27 23_59_46-newsbook _ polski portal nie tylko o polsce](https://user-images.githubusercontent.com/5884000/33294085-59a0cb26-d3cf-11e7-87b4-de3d0c388bbd.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.113
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`newsbook.pl##.newsb-widget.widget`
