### ISSUE TITLE
perepele.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4648]
![2017-11-28 00_08_27-perepele](https://user-images.githubusercontent.com/5884000/33294339-7d271702-d3d0-11e7-8af3-6361c1fc19c7.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.113
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`perepele.pl##A > IMG.ccm-image-block`
