### ISSUE TITLE
discovery.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4649]
co musze z whistlistowac zeby guzik `SIGN IN` zaczol dzialac przeszkadza lista easyprivacy

**Comment by MajkiIT** [comment]
U mnie jest ok, bez WL https://www.screencast.com/t/eZgffQx7

**Comment by xxcriticxx** [comment]
u mnie dopiero dziala jak wyloncze easyprivacy to wczoraj pomadalo dzisaj juz nie dziala 


`@@||googletagmanager.com/gtm.js$script,domain=discovery.com`
