### ISSUE TITLE
prawicowyinternet.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4651]
![2017-11-28 20_24_05-prawicowy internet pl prawa strona sieci](https://user-images.githubusercontent.com/5884000/33339676-3d67459c-d47a-11e7-9855-4dc87dc409ea.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.114
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
`prawicowyinternet.pl##.ns_bottom_slider`

**Comment by xxcriticxx** [comment]
co ty na to

@MajkiIT @hawkeye116477  

`||http://emisja.contentstream.pl^`

**Comment by xxcriticxx** [comment]
btw contenstreamer jest na okolo 500 stronach

**Comment by MajkiIT** [comment]
@mat41997 @xxcriticxx już to jest blokowane przez obecne filtry.

**Comment by xxcriticxx** [comment]
@MajkiIT ja mam to samo to @mat41997 na obrazku z najnowszymi filtrami z v.2017112805 aktualizacja: wt, 28 listopada 2017, 19:45:00

**Comment by MajkiIT** [comment]
@xxcriticxx no to może tak? `||emisja.contentstream.pl/$script`

**Comment by xxcriticxx** [comment]
to bendzie blokowac tylko scripty?

**Comment by MajkiIT** [comment]
@xxcriticxx tak
