### ISSUE TITLE
tylkonauka.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4655]
![2017-11-29 06_05_56-tylkonauka pl _ rzeczywistosc jest dziwniejsza od fikcji](https://user-images.githubusercontent.com/5884000/33358885-a146f25a-d4cb-11e7-88b5-d01017b56eb7.png)
`http://tylkonauka.pl/main`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.114
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`tylkonauka.pl##[id^="block-block-"]`
