### ISSUE TITLE
camdivision.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4659]
Ciasteczka -> `###w357_cpnb:not(body):not(html)`

**Comment by xxcriticxx** [comment]
nie widze tego na duzo stronach

**Comment by hawkeye116477** [comment]
@xxcriticxx No to może nie jest tak dużo polskich stron co mają ten skrypt, ale w I don't care about cookies jest to dane jako ogólna reguła, dlatego tak zaproponowałem.

**Comment by xxcriticxx** [comment]
@hawkeye116477 widze ze clonujemy liste Nie obchodzi mnie ciasteczka

**Comment by hawkeye116477** [comment]
Oni mają od nich skrypt -> https://www.web357.eu/joomla-extensions/cookies-policy-notification-bar
Także na wszelki wypadek dam ogólną, jakby się ktoś jeszcze zdecydował zamieścić gdzieś ten skrypt.
