### ISSUE TITLE
pulshr.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4662]
Zabawię się w @xxcriticxx, push 😃 .
`||cdn.gravitec.net/sites/www-pulshr-pl/client.js`

Ewentualnie zamiast tego coś w tym stylu -> `||cdn.gravitec.net/sites/*/client.js`, gdyż ten skrypt jest oczywiście nie tylko na pulshr.
https://publicwww.com/websites/.pl+cdn.gravitec.net/

**Comment by xxcriticxx** [comment]
@hawkeye116477 nazwa `client.js` nie za generic?

**Comment by hawkeye116477** [comment]
@xxcriticxx Oni i tak tylko pushe dostarczająca.
https://pl.gravitec.net/
