### ISSUE TITLE
rp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4664]
maybe do popup blocker

`||api.traq.li/$script`

http://www.rp.pl/ZUS/311299854-Morawiecki-Najbardziej-naturalne-byloby-zniesienie-limitu-skladek-na-ZUS-od-2019-r.html

![capture](https://user-images.githubusercontent.com/15007183/33403335-fc8442a0-d52d-11e7-8885-930a7da06e1f.PNG)

**Comment by MajkiIT** [comment]
dobry pomysł :P
