### ISSUE TITLE
akademiaversum.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4668]
![2017-11-30 05_49_10-jak stworzyc unikalne spa_ - akademia versum](https://user-images.githubusercontent.com/5884000/33414333-8bb1d212-d592-11e7-8dd7-857dc41fe739.png)
`https://www.akademiaversum.pl/stworzyc-unikalne-spa/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.115
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
To do popup filters
