### ISSUE TITLE
kryminalnapolska.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4670]
![2017-11-30 08_11_35-kryminalna polska](https://user-images.githubusercontent.com/5884000/33418437-1e77f550-d5a6-11e7-8981-950951a3f80c.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.115
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
@mat41997 boisz sie do pigwina podawac?

**Comment by mat41997** [comment]
@xxcriticxx Nie wiem co jesteście w stanie zablokować, a bana mam obiecanego.

**Comment by xxcriticxx** [comment]
@mat41997 nic nie jestesmy w stanie zablokowac :)
