### ISSUE TITLE
tasteandtravel.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4675]
![2017-11-30 09_56_22-subiektywny przewodnik po kubie dwie waluty srednia krajowa wartosci 100 pln i](https://user-images.githubusercontent.com/5884000/33422127-dfa98eb0-d5b4-11e7-872d-5cfaa3f9a315.png)
`https://tasteandtravel.pl/2017/11/29/przewodnik-po-kubie/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.115
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
@mat41997 chodzi Ci, że nie widzisz treści?

**Comment by mat41997** [comment]
@MajkiIT o scrollowanie chodzi i o treść też.

**Comment by MajkiIT** [comment]
U mnie jest ok.

**Comment by xxcriticxx** [comment]
u mnie gut

**Comment by hawkeye116477** [comment]
U mnie też ok.

**Comment by HateAds** [comment]
U mnie też działa ok. @mat41997 może już czas na wymianę myszki :smile:

**Comment by mat41997** [comment]
@HateAds Mam touchpada na stałe zamontowanego z laptopem.
