### ISSUE TITLE
oleole.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4676]
![2017-11-30 17_41_31-manta led5501u telewizor led - cena i opinie - oleole](https://user-images.githubusercontent.com/5884000/33442735-2d7c8f02-d5f6-11e7-99f8-9525dc628273.png)
`https://www.oleole.pl/telewizory-led-lcd-plazmowe/manta-led5501u.bhtml`

brak paska do przewijania strony

by odtworzyć
- wyczyść cookie/cache
- wejdź tu
`https://www.oleole.pl/cms/przebijemy-ceny-innych-sklepow.bhtml?product=1133883&link=rotator`
- kliknij szczegóły
![2017-11-30 17_43_28-prze bijemy ceny innych sklepow](https://user-images.githubusercontent.com/5884000/33442853-775808fe-d5f6-11e7-84bb-dc0196012faf.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.115
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
@mat41997 To wina PPB. Ale niestety będę musiał przenieść filtry chowające popup do listy uzupełniającej dla uBlocka i AdGuarda, więc jeśli będzie ci ten popup przeszkadzać, to będziesz musiał zasubskrybować -> https://raw.githubusercontent.com/azet12/PopupBlocker/master/PPB_uBlock_AdGuard.txt .

**Comment by userOperaFF** [comment]
Jeszcze te żółte kropeczki można wyciąć chyba po banerach reklamowych.

**Comment by hawkeye116477** [comment]
Te kropki są po banerach z ofertami promocyjnymi na oleole.pl, także to powinno raczej zostać przywrócone.
