### ISSUE TITLE
cookies skrypt

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#4681]
@hawkeye116477 
Może dodamy ? `https://cookieq.com/cdn/tg.js`

**Comment by hawkeye116477** [comment]
@MajkiIT Tak w zasadzie, to jest już na to kosmetyczna `###cqcqPanel:not(body):not(html)`, ale może nie zaskodzi zamienić to na sieciową.
Z tym, że ten skrypt miewa zdaje się różne nazwy, np. `https://cookieq.com/scripts/cc.js` . Dlatego też zapewne lepiej byłoby wziąć przykład z fanboya i dodać taką regułę -> `||cookieq.com^$third-party`
