### ISSUE TITLE
certyficate.it/adblock - link do AlleBlock

### ISSUE THREAD

**Issue by maciejtarmas** [MajkiIT/polish-ads-filter#4683]
Hello,

prośba o zmianę linka do subskrypcji filtrów AlleBlock na https://alleblock.pl/alleblock/alleblock.txt

Tak było wcześniej, ale widzę, że teraz jest link do GitHuba.

**Comment by mat41997** [comment]
Nie pojmuje jakie to ma znaczenie.
> To tak jak ja bym się wtrącał do googla że ma dwa oo w nazwie i kazał mu to zmieniać.

poza tym takie sprawy załatwia się tutaj
https://www.certyficate.it/kontakt/

**Comment by MajkiIT** [comment]
@maciejtarmas poprawione.
