### ISSUE TITLE
Powiadomienia gravitec.net

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4684]
@MajkiIT Do poprawy jest ten filtr -> `||cdn.gravitec.net/sites/*/client.js,$script`
Ten przecinek między s a $ psuje działanie, ale na https://www.e-biurowce.pl/pl/ i paru innych stronach też jest ten skrypt, tylko, że na podstronach storage/losowyciąg, np.
`https://cdn.gravitec.net/storage/0ac8766e39e39edc747f1818d0345699/client.js`
Więc proponuję zrobić tak: 
```
||cdn.gravitec.net/sites/*/client.js
||cdn.gravitec.net/storage/*/client.js
```
Albo po prostu -> `||cdn.gravitec.net^$third-party`
Oni i tak raczej zajmują się tylko pushami. Tutaj można poczytać o ich działalności -> https://pl.gravitec.net/

**Comment by MajkiIT** [comment]
@hawkeye116477 dzięki
