### ISSUE TITLE
prawodrogowe.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4686]
![2017-12-01 17_18_10-strona glowna __ prawo drogowe](https://user-images.githubusercontent.com/5884000/33491832-b5516a7c-d6bb-11e7-9fe3-452363332089.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.116
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
Masz wzrok jastrzębia czy kreta?

**Comment by mat41997** [comment]
@xxcriticxx obstawiam bardziej susła albo leniwca.

w każdym bądź razie jest link zewnętrzny
`https://www.l-instruktor.pl/warsztaty-rodo/zgloszenie.html`

**Comment by hawkeye116477** [comment]
Fejs -> `www.prawodrogowe.pl##div:nth-of-type(4) > .img-responsive`
