### ISSUE TITLE
astroweb.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4688]
![2017-12-01 21_11_07-przepowiednie 2018 najwazniejsze informacje na temat naszej przyszlosci _ astr](https://user-images.githubusercontent.com/5884000/33501358-952e365a-d6dc-11e7-9602-7fe60720b3b2.png)
`http://astroweb.pl/przepowiednie-2018.php`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.116
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
@mat41997 do pigwina please

**Comment by F4z** [comment]
Na przykład:
`astroweb.pl##script:inject(abort-on-property-read.js, checkAds)`

**Comment by hawkeye116477** [comment]
Social:
```
astroweb.pl##.col-md-8 > div:nth-of-type(4)
astroweb.pl##.well:nth-of-type(1)
```
