### ISSUE TITLE
laczynaspilka.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4692]
![2017-12-02 00_07_44-strona glowna - laczy nas pilka](https://user-images.githubusercontent.com/5884000/33507434-fcab3608-d6f4-11e7-9991-9e730c33b45b.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.116
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
@mat41997 nie wiem czy jest sens blokowac te sklepiki

**Comment by hawkeye116477** [comment]
Social -> `laczynaspilka.pl##.box-standard.social-side`
