### ISSUE TITLE
zawiszafans.net

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4693]
![2017-12-02 00_35_47-zawiszafans - serwis kibicow bydgoskiego zawiszy](https://user-images.githubusercontent.com/5884000/33508143-e1e71626-d6f8-11e7-836f-daaf10f0410f.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.116
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
@mat41997 lewa prawa strona? napisz wiecej

**Comment by mat41997** [comment]
obie

**Comment by hawkeye116477** [comment]
Ja to widzę też reklamy po środku.
```
zawiszafans.net##body > p
zawiszafans.net###najblizszyMeczk, #wspieraja-nas
zawiszafans.net##table
```
