### ISSUE TITLE
obserwatorfinansowy.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4694]
![2017-12-02 05_25_18-obserwator finansowy biznes makroekonomia i finanse publiczne dla ekspertow](https://user-images.githubusercontent.com/5884000/33511755-9cdfa826-d721-11e7-82f1-db88b6a0c042.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.116
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
?
