### ISSUE TITLE
wszczecinie.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4695]
![2017-12-02 05_30_55-strona glowna - szczecin](https://user-images.githubusercontent.com/5884000/33511788-60903312-d722-11e7-91a5-18ddb7b2ac90.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.116
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
@mat41997 banner na topie?
