### ISSUE TITLE
mytastepol.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4696]
cookies jestem na na avast pc 

Korzystając z serwisu myTaste wyrażasz zgodę na naszą politykę plików cookie.. Więcej informacji

**Comment by hawkeye116477** [comment]
`##.cookie-disclaimer:not(body):not(html)`

**Comment by xxcriticxx** [comment]
czyli nie avast?

**Comment by hawkeye116477** [comment]
Dziwne, na Waterfoksie tego nie widzę, a na Vivaldim jest. Tak czy siak, moja reguła to ukrywa
