### ISSUE TITLE
zblogowani.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4697]
http://zblogowani.pl/wpis/27479049/nivea-carehold-lakier-i-pianka-do-wlosow

@MajkiIT maybe?

`http://webfrik.pl/widgets/popup/popup.min.js`

**Comment by hawkeye116477** [comment]
@xxcriticxx To raczej do Popup Blockera 😄 .

**Comment by xxcriticxx** [comment]
@hawkeye116477 znalazlem to na w logerze nie zaglonalem glembiej
