### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#4698]
Adblock detect

![screenshot_1](https://user-images.githubusercontent.com/21177361/33518682-7f11ba50-d799-11e7-9988-be2444a0f341.png)

**Comment by mat41997** [comment]
na szybko mogę polecić ublock protector
https://jspenguin2017.github.io/uBlockProtector/

**Comment by xxcriticxx** [comment]
@gzenio22 przejscie z onetu?

**Comment by xxcriticxx** [comment]
u mnie gitara

![capture](https://user-images.githubusercontent.com/15007183/33518839-e711dee4-d769-11e7-9bc9-a496f079cd65.PNG)

**Comment by mat41997** [comment]
@xxcriticxx postaraj się nie być takim opryskliwym dla innych
https://sjp.pl/opryskliwy

**Comment by gzenio22** [comment]
to nie u mnie Xd kolega jest tak slaby ze nawet listy subnac nie umie :D

**Comment by hawkeye116477** [comment]
Sama lista raczej nie usunie detekcji, wymagane jest rozszerzenie. U mnie na Vivaldim 1.13.1008.32 z uBlock Protector Extension i Waterfoksie 56 z Adblock Protector 2 jest ok.

**Comment by xxcriticxx** [comment]
@gzenio22 co mam kompu przekazac?

mi no spiki inglish gut

**Comment by gzenio22** [comment]
@xxcriticxx Ta regole co podalem wyzej niech dodadza do protectora wtedy zniknie potforek

**Comment by hawkeye116477** [comment]
@gzenio22 A zainstalowałeś rozszerzenie uBlock Protector Extension? Bo jeśli tak, to twoja reguła jest zbędna i potworka nie powinno być.

**Comment by gzenio22** [comment]
@hawkeye116477 Exstension robi za kolejna wtyczke do przegladarki zauwazylem co nie?

**Comment by hawkeye116477** [comment]
@gzenio22 Robi za kolejne rozszerzenie, a nie wtyczkę.

**Comment by gzenio22** [comment]
dobra Działa dzieki chlopaki :)
