### ISSUE TITLE
booklips.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4699]
![2017-12-02 20_26_25-booklips pl - ksiazki komiksy pisarze - literatura w xxi wieku](https://user-images.githubusercontent.com/5884000/33519047-3a83df20-d79f-11e7-95ae-5f837dbd3135.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.118
chrome 62.0.3202.94

**Comment by gzenio22** [comment]
booklips.pl###custom_html-2

**Comment by hawkeye116477** [comment]
Resztka po reklamie -> booklips.pl###custom_html-24 > .widget-wrap.widget_text > .custom-html-widget.textwidget
Tło -> `booklips.pl##.home:style(background-image: none !important;)`

No i nie wiem czy przypadkiem te patronujemy też nie do wywalenia -> `booklips.pl#?#.widget-wrap.widget_text:-abp-contains(Patronujemy)`
