### ISSUE TITLE
www.dvt.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#47]
please fix cookies page dont display

**Comment by MajkiIT** [comment]
u mnie jest ok.

**Comment by xxcriticxx** [comment]
zdjelem wszystkie cookie listy strona dalej sie nie wyswietal

**Comment by MajkiIT** [comment]
dodatek do ciasteczek?

**Comment by xxcriticxx** [comment]
na tym pc niema plugin do ciastek. 

strona na IE 11 dziala bez problemu masz racjie nie widze zadnego cookies wiadomosci
