### ISSUE TITLE
dailyvibes.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4700]
![2017-12-02 20_32_27-20 filmow na babski wieczor - czesc pierwsza _ dailyvibes _ kultura _ lifestyle](https://user-images.githubusercontent.com/5884000/33519105-3c646886-d7a0-11e7-9ca4-204a977912d5.png)
`https://www.dailyvibes.pl/single-post/2017/01/03/filmy-na-babski-wieczor`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.118
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
```
dailyvibes.pl##[aria-label="Social bar"]
||inffuse-fbpopup.appspot.com/widget.html
```
