### ISSUE TITLE
a-o.ninja

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4701]
![2017-12-02 22_17_52-highschool dxd 02 pl online hd a-o ninja anime online pl 2018 emitowane](https://user-images.githubusercontent.com/5884000/33519812-ceed649c-d7ae-11e7-8296-310b6d39ee17.png)
`https://a-o.ninja/anime/high-school-dxd/2`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.118
chrome 62.0.3202.94

**Comment by mat41997** [comment]
przycisk next nie działa za każdym razem.

**Comment by xxcriticxx** [comment]
u nie poszlo 

@MajkiIT trzeba regex zmienic 

![capture](https://user-images.githubusercontent.com/15007183/33520880-0da55e74-d791-11e7-80b3-2fc6373e83b4.PNG)

**Comment by mat41997** [comment]
ach.. skrypty kopiące
![2017-12-03 17_11_34-highschool dxd new 08 pl online hd a-o ninja anime online pl 2018 emitowane](https://user-images.githubusercontent.com/5884000/33527232-4a6febaa-d84d-11e7-93ae-b3341366ec69.png)

kopią mimo anty-miner'a
![2017-12-03 17_11_52-menedzer zadan](https://user-images.githubusercontent.com/5884000/33527234-55e327ea-d84d-11e7-9d52-22f2209bf33b.png)

**Comment by MajkiIT** [comment]
@mat41997 zrób aktualizację to filtrów 2017120402 i sprawdź.

**Comment by mat41997** [comment]
@MajkiIT przycisk następny odcinek działa dopiero za drugim bądź trzecim razem po wypuszczeniu samo-zamykającego się popupa.

**Comment by MajkiIT** [comment]
@mat41997 ale tak musi być, bo ja blokuje przy popupach konsekwencję skryptu stąd miganie. Dodatkowo zablokowałem koparki.

**Comment by mat41997** [comment]
@MajkiIT nadal kopie
![2017-12-07 01_42_20-menedzer zadan](https://user-images.githubusercontent.com/5884000/33692959-54060816-daf0-11e7-9b2f-e460f45b5a46.png)

![2017-12-07 01_44_40-a-o ninja anime online pl 2018 emitowane anime online pl hd anime pl full hd a](https://user-images.githubusercontent.com/5884000/33692962-57627b52-daf0-11e7-8f9e-8ad422537c9d.png)

**Comment by MajkiIT** [comment]
Znowu coś zmienili. Zaraz poprawię
