### ISSUE TITLE
nslowo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4713]
bestcontent solution

**Comment by MajkiIT** [comment]
`||bestcontent.solutions/images/baner/$image` to chyba rozwala stronę?

**Comment by xxcriticxx** [comment]
strona jest wogole zepsuta chyba

**Comment by MajkiIT** [comment]
@xxcriticxx no jest, bo się wszystko rozleciało

**Comment by hawkeye116477** [comment]
Tak będzie git, ale tylko dla uBlocka i AdGuarda:
```
||bestcontent.solutions/images/baner$image
nslowo.pl###gkTopBar:style(position: static !important;)
```
