### ISSUE TITLE
booklips.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4717]
![2017-12-03 20_44_31-booklips pl - ksiazki komiksy pisarze - literatura w xxi wieku](https://user-images.githubusercontent.com/5884000/33529033-e160e3bc-d86a-11e7-8b5b-7059abf6f971.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.118
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
`booklips.pl###custom_html-2`
