### ISSUE TITLE
xlomza.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4718]
![2017-12-03 22_18_21-xlomza pl - informacje w formacie xl - witamy](https://user-images.githubusercontent.com/5884000/33529963-6f4fd6da-d878-11e7-88d8-63536450a1c6.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.121
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
xlomza.pl##A > IMG[src^="/site/assets/files/"]

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/10777
