### ISSUE TITLE
oscarrak.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4719]
![2017-12-03 22_17_24-mirkomowa dla poczatkujacych poznaj jezyk uzytkownikow czyli slownik wykopowic](https://user-images.githubusercontent.com/5884000/33529972-9eba7722-d878-11e7-8eff-d3af81aac6fc.png)

`https://oscarrak.pl/blog/mirkomowa-dla-poczatkujacych-poznaj-jezyk-uzytkownikow-wykopowiczow/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.121
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
```
oscarrak.pl##.clearfix.cb-column.cb-one
oscarrak.pl##a[href="http://www.blogodpodstaw.pl"]
```
