### ISSUE TITLE
jezykiobce.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4727]
cookies

Aby zapewnić wysoką jakośc usług i bezpieczeństwo korzystania w księgarni internetowej www.jezykiobce.pl wykorzystujemy informacje przechowywane w przeglądarce internetowej, pliki cookie.ZOBACZ WIĘCEJ >>>ZAMKNIJ [X]

**Comment by hawkeye116477** [comment]
`##.eupopup-container:not(body):not(html)`

**Comment by xxcriticxx** [comment]
@hawkeye116477 do szkoly na lekcje zasuwac

**Comment by hawkeye116477** [comment]
@xxcriticxx O godzinie 21 nie mam nigdy zajęć, najpóźniej mam do 20:15 😛 .
