### ISSUE TITLE
tornadosklep.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4728]
cookies

Szanowni Państwo, w celu świadczenia usług na najwyższym poziomie, w ramach naszego serwisu stosujemy pliki cookies. Korzystanie z witryny bez zmiany ustawień dotyczących cookies oznacza, że będą one zamieszczane w Państwa urządzeniu końcowym. Jeśli nie wyrażają Państwo zgody, uprzejmie prosimy o dokonanie stosownych zmian w ustawieniach przeglądarki internetowej.
Zamknij

**Comment by hawkeye116477** [comment]
To samo co #4727 .
