### ISSUE TITLE
informacjenews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4729]
![2017-12-05 21_40_47-informacjenews - 24_7 live](https://user-images.githubusercontent.com/5884000/33629665-2780be80-da05-11e7-842d-961effbdec38.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.128
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
`informacjenews.pl##.popmake`
