### ISSUE TITLE
auto-czesci-lipiec.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4738]
cookies

![capture](https://user-images.githubusercontent.com/15007183/33635520-3d1c4e54-d9e6-11e7-974a-94f1b62ca882.PNG)

**Comment by hawkeye116477** [comment]
Ciężka sprawa, bo tutaj jest scroll blokowany, można byłoby zablokować jquery, ale obawiam się, że coś się może popsuć.
Więc zabawiamy się inaczej 😃 
```
auto-czesci-lipiec.pl###mAll
auto-czesci-lipiec.pl##.modal-open:style(overflow: visible !important; padding-right: 0px !important;)
```
