### ISSUE TITLE
zblogowani.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4739]
![2017-12-06 03_12_21-najlepsze polskie blogi internetowe _ fajne blogi online _ zblogowani](https://user-images.githubusercontent.com/5884000/33640861-4d0ae4a4-da33-11e7-95c0-b778475f24fb.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.128
chrome 62.0.3202.94

**Comment by mat41997** [comment]
![2017-12-06 03_21_44-gesty sos grzybowy z suszona sliwka _ kulinaria _ zblogowani](https://user-images.githubusercontent.com/5884000/33641167-a8682ec8-da34-11e7-81a0-6b25bdca7269.png)
`http://zblogowani.pl/wpis/290848/gesty-sos-grzybowy-z-suszona-sliwka`

**Comment by MajkiIT** [comment]
`zblogowani.pl##.hidden-xs.container`
