### ISSUE TITLE
edziecko.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4740]
![2017-12-06 03_25_27-kupowac dziecku zabawki militarne_](https://user-images.githubusercontent.com/5884000/33641305-4062b752-da35-11e7-9d29-25a1226ef0ae.png)
`http://www.edziecko.pl/przedszkolak/1,79345,7346434,Kupowac_dziecku_zabawki_militarne_.html`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.128
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
@mat41997 u mnie dziala wyc wyczysc cookies i cache co raz

**Comment by mat41997** [comment]
@xxcriticxx nadal to samo

**Comment by xxcriticxx** [comment]
za duzo blokujesz na filtrach

**Comment by mat41997** [comment]
@xxcriticxx proszę o konkrety. co za dużo zablokowałem.

**Comment by xxcriticxx** [comment]
@mat41997 dziala ze stanard filtrami z ubo

@hawkeye116477 @MajkiIT  mozecie sprawdzic

**Comment by hawkeye116477** [comment]
U mnie jest ok
