### ISSUE TITLE
technologiczna.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4748]
![2017-12-06 10_02_25-technologiczna pl - nowosci ze swiata technologii](https://user-images.githubusercontent.com/5884000/33653240-b9b5d8a0-da6c-11e7-8e77-74937692586f.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.128
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`technologiczna.pl##.wpb_raw_html.wpb_content_element.wpb_raw_code:nth-of-type(2) > .wpb_wrapper`
