### ISSUE TITLE
applemobile.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4749]
![2017-12-06 10_07_35-serwis iphone szczecin applemobile pl](https://user-images.githubusercontent.com/5884000/33653430-6dc3f6d8-da6d-11e7-8030-17a2d1a1ac67.png)

![2017-12-06 10_07_50-serwis iphone szczecin applemobile pl](https://user-images.githubusercontent.com/5884000/33653436-71812610-da6d-11e7-84ef-06e7adc46a63.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.128
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
@mat41997 zamykamy?

**Comment by MajkiIT** [comment]
`applemobile.pl##A[target="_blank"] > IMG`
