### ISSUE TITLE
bham.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4757]
![2017-12-06 18_26_28-bham pl - polonia birmingham - praca w anglii ogloszenia forum poradnik bene](https://user-images.githubusercontent.com/5884000/33675514-1bd5ad6c-dab3-11e7-8b39-e20af6442f79.png)

![2017-12-06 18_26_44-bham pl - polonia birmingham - praca w anglii ogloszenia forum poradnik bene](https://user-images.githubusercontent.com/5884000/33675520-1f4a3396-dab3-11e7-92ee-b54521e8ae26.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.128
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
```
bham.pl###ba
bham.pl##[class$="_sponsored"]
```
