### ISSUE TITLE
epainfo.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4758]
![2017-12-06 18_33_15-strona glowna - pabianice - portal informacyjny](https://user-images.githubusercontent.com/5884000/33675829-2c6f1eaa-dab4-11e7-9e64-047b887d377c.png)

![2017-12-06 18_33_58-strona glowna - pabianice - portal informacyjny](https://user-images.githubusercontent.com/5884000/33675832-300da0d6-dab4-11e7-9df7-b17076b5345e.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.128
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
```
epainfo.pl##A.gofollow > IMG
epainfo.pl##DIV.g-single > IMG
```
