### ISSUE TITLE
cda.pl

### ISSUE THREAD

**Issue by 127001tk** [MajkiIT/polish-ads-filter#4760]
Nowe video-reklamy na cda.pl:
vstatic3.cda.pl/v/qFFC3efTR3M.mp4
vstatic3.cda.pl/v/V1prj4WQSwA.mp4
vstatic3.cda.pl/v/7l4MHahGfxg.mp4
vstatic3.cda.pl/v/Q3_bxGfMZng.mp4

chrome: 62.0.3202.94
ublock:  v1.14.20 + filtry Adblock & uBlock polish filters 2017120503

**Comment by MajkiIT** [comment]
@127001tk Dzięki
