### ISSUE TITLE
mieszkaniectargowka.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4771]
![2017-12-07 05_05_28-mieszkaniec targowka - warszawa targowek informacje wiadomosci gazeta](https://user-images.githubusercontent.com/5884000/33698358-459947ea-db0c-11e7-8b48-da356a63ef96.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.130
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
`mieszkaniectargowka.pl##A[target="_blank"] > IMG`
