### ISSUE TITLE
zdrowyportal.org

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#4783]
![2017-12-07 17_36_20-kategoria - ziola - zdrowyportal org - portal o zdrowiu](https://user-images.githubusercontent.com/5884000/33726414-418844e4-db75-11e7-847e-797374614177.png)
`http://www.zdrowyportal.org/ziola/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.130
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
duplicate of https://github.com/MajkiIT/polish-ads-filter/issues/4762

@mat41997 please updatuj filtry!

**Comment by mat41997** [comment]
@xxcriticxx Version: 2017120704

**Comment by xxcriticxx** [comment]
@MajkiIT co lepsze?

`##img[src="http://www.zdrowyportal.org/wp-content/plugins/revolweb/js/rw_adrotator"]`

or

`##a[href="http://poczta.tv"]`

**Comment by MajkiIT** [comment]
@mat41997 łapie to reguła `zdrowyportal.org###text-8`
