### ISSUE TITLE
eostroleka.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4787]
![2017-12-07 20_05_50-eostroleka __ twoje wirtualne miasto](https://user-images.githubusercontent.com/5884000/33733480-3001b7ae-db8a-11e7-8011-607f58abe5cb.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.130
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
`||eostroleka.pl/luba/main/ajax_fuckadbloker.php`
Oprócz tego masa reklam jest tutaj.
