### ISSUE TITLE
cda.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4797]
![2017-12-08 00_20_00-sakasama no patema](https://user-images.githubusercontent.com/5884000/33743555-9b42d1ba-dbad-11e7-8c24-a8370fa7c6d6.png)
`http://ebd.cda.pl/711x425/1626727f`

`https://prezent.cda.pl/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.130
chrome 62.0.3202.94

**Comment by MajkiIT** [comment]
gdzie ty to masz ?

**Comment by mat41997** [comment]
@MajkiIT pod przyciskiem home

**Comment by xxcriticxx** [comment]
mam reklame tak jak u @mat41997 

![capture](https://user-images.githubusercontent.com/15007183/33762540-d4f9ab18-dbda-11e7-84f9-a0dd83575674.PNG)

**Comment by xxcriticxx** [comment]
@MajkiIT mysle ze mozna zostawic prowadzi do kupna gift karty

![capture](https://user-images.githubusercontent.com/15007183/33762639-3f96ba06-dbdb-11e7-9981-ede85b061ea4.PNG)

**Comment by xxcriticxx** [comment]
maybe this?

`https://g.cda.pl/xml2.php?ads&vi=MjA_MWFhOWQyYzM3NWQyZWM0N2ZlODkzNDE0ZDExZTFiOGE_NTIy&t=1512730049`

**Comment by MajkiIT** [comment]
możesz odtworzyć kroki jak to testujesz?

**Comment by xxcriticxx** [comment]
@MajkiIT kopuje link co podal @mat41997  

http://ebd.cda.pl/711x425/1626727f

a prezent znalazlem na main po prawej stronie

**Comment by xxcriticxx** [comment]
https://www.cda.pl/video/51572974/vfilm

![capture](https://user-images.githubusercontent.com/15007183/33788377-daf590a8-dc3f-11e7-9270-bee442c33059.PNG)

**Comment by xxcriticxx** [comment]
@MajkiIT 

`cda.pl##.muimERPIa`
