### ISSUE TITLE
creativecommons.org

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4798]
@mat41997 
https://creativecommons.org/licenses/by-nc-sa/4.0/deed.pl
![screenshot_20171208_121417](https://user-images.githubusercontent.com/19818572/33763583-59067cac-dc11-11e7-89e7-9626be6156d6.png)

**Comment by userOperaFF** [comment]
![image](https://user-images.githubusercontent.com/33114475/33764691-cc42f00c-dc15-11e7-839b-0cc59b802a8d.png)


Ale kodem się nie różni - oparte o [Media Query][mq].

[mq]: https://www.w3schools.com/css/css_rwd_mediaqueries.asp

**Comment by xxcriticxx** [comment]
@MajkiIT moze zrobimy `WESPRZYJ FINANSOWO` ?

**Comment by gzenio22** [comment]
jestem troche nie w temacie co to je?

**Comment by hawkeye116477** [comment]
Jak to co, dotacje do zablokowania do nowych filtrów dla chciwusów 😃

**Comment by gzenio22** [comment]
@hawkeye116477  tylko zeby nie narobilo sie tak jak z Bildami do kodi Xdddd gdzie taki jeden sie napuszyl bo ktos twozy builda do kodi ulatwiajac ludziom zycie Xd

**Comment by mat41997** [comment]
@hawkeye116477 zagranicznych nie blokuje, ale w tym wypadku mogę zrobić wyjątek.
