### ISSUE TITLE
naekranie.pl

### ISSUE THREAD

**Issue by userOperaFF** [MajkiIT/polish-ads-filter#4799]
https://github.com/MajkiIT/polish-ads-filter/issues/4541

![image](https://user-images.githubusercontent.com/33114475/33765404-f40bd36c-dc18-11e7-834b-04f4e30b240a.png)

```
naekranie.pl##.s69f742b1
naekranie.pl##a[href*="naekranie.pl/ff019a9682"]
||cont6.naekranie.pl/wp-content/uploads/2017/12/spellforce_sd1.jpg$image
```

**Comment by hawkeye116477** [comment]
Na razie się nie zmieniają, ale jutro pewnie będą inne. Także raczej trzeba coś innego wykombinować.
