### ISSUE TITLE
gamedot.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#4801]
https://gamedot.pl/sklep

Ciasteczka
`gamedot.pl##.policy_warning`

Oprócz tego na głównej są artykuły sponsorowane, może to do wewnętrznych filtrów?

**Comment by mat41997** [comment]
sklep, to sklep.
nie mam zamiaru ograniczać funkcjonalności strony w filtrach wewnętrznych.

**Comment by hawkeye116477** [comment]
Z tym, że artykuły sponsorowane to jednak też pewnego rodzaju reklama.

**Comment by mat41997** [comment]
@hawkeye116477 gdzie?
na artykuły sponsorowane trzeba by było zrobić jeszcze jedną listę, bo za dużo tego i trzeba zgadywać które to sponsorowane. poza tym nie wszyscy chcą blokować artykuły sponsorowane bo one też zawierają dużo ciekawej treści i niektóre strony jak np. dobreprogramy mają tylko takie w swoim portfolio.

**Comment by hawkeye116477** [comment]
@mat41997 `gamedot.pl##.content-columns-right-inner.content-module:nth-of-type(6)` -> to są recenzje
