### ISSUE TITLE
forum.abczdrowie.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4802]
![2017-10-27 11_00_43-forum psychologia _ abczdrowie pl](https://user-images.githubusercontent.com/5884000/32096243-27d1fdcc-bb06-11e7-996b-98f606a984e8.png)

![2017-10-27 11_00_52-forum psychologia _ abczdrowie pl](https://user-images.githubusercontent.com/5884000/32096248-2b9ed6f0-bb06-11e7-9039-c5837f366f05.png)

![2017-12-08 20_01_37-forum zywienie i fitness _ abczdrowie pl](https://user-images.githubusercontent.com/5884000/33780881-a9a8e0e6-dc52-11e7-9600-5b567c39214a.png)
`https://forum.abczdrowie.pl/forum-zywienie-i-fitness`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.130
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
u mnie czysto mam tylko jedna na dole 

![capture](https://user-images.githubusercontent.com/15007183/33780996-e2234fb0-dc20-11e7-9a89-c7e46a35d8e8.PNG)
