### ISSUE TITLE
centralagier.wp.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4803]
![2017-12-08 20_07_40-elvenar - centrala gier](https://user-images.githubusercontent.com/5884000/33781086-89cf53da-dc53-11e7-9e4b-3727c1ea9a3f.png)
`https://centralagier.wp.pl/elvenar/graj`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.130
chrome 62.0.3202.94

**Comment by xxcriticxx** [comment]
ja widze cala strone

**Comment by mat41997** [comment]
Dan Pollock’s hosts file
