### ISSUE TITLE
openkatalog.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4804]
@MajkiIT 

koparki dalej sie odpalaja cpu 50% 

`https://openkatalog.com/static/anyemotionsalready/c.wasm`
`https://openkatalog.com/static/anyemotionsalready/m.js?hm=x?proxy=wss://getrichordietrying1.now.sh?pool=pool.supportxmr.com:3333`

@mat41997 

zeskanujesz to twoja magiczna extension od koparek

**Comment by mat41997** [comment]
@xxcriticxx lepiej, podzielę się tą magią z tobą
`https://chrome.google.com/webstore/detail/anti-miner-no-1-coin-mine/abgnbkcdbiafipllamhhmikhgjolhdaf`

**Comment by SMed79** [comment]
```
||openkatalog.com/static/openkatalog/cpuproject.php
```

**Comment by MajkiIT** [comment]
@xxcriticxx @mat41997 oni codziennie zmieniają skrypt.

**Comment by xxcriticxx** [comment]
@MajkiIT nowy script nieda tego rady regexem ogarnac?

**Comment by MajkiIT** [comment]
@xxcriticxx na razie tak zablokuje a później pomyślę nad regexem.

**Comment by xxcriticxx** [comment]
@MajkiIT thx!
