### ISSUE TITLE
welcome bot 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4805]
@MajkiIT fyi...

https://github.com/apps/welcome

**Comment by mat41997** [comment]
no właśnie, to genialny pomysł.

**Comment by mat41997** [comment]
wtedy @MajkiIT nie będzie już musiał wszystkim dziękować XD

**Comment by mat41997** [comment]
popieram

**Comment by userOperaFF** [comment]
W sumie po co, jeszcze pewnie brak polskiego na starcie.

**Comment by xxcriticxx** [comment]
@userOperaFF ¿Hay alguien que hable inglés?

**Comment by userOperaFF** [comment]
¡Yo no hablo español!
