### ISSUE TITLE
ciekawostkihistoryczne.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4806]
![2017-12-08 23_28_13-ciekawostkihistoryczne pl _ najpopularniejszy magazyn o historii w polsce](https://user-images.githubusercontent.com/5884000/33787858-7d772c68-dc6f-11e7-8790-06489850b996.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.130
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
```
ciekawostkihistoryczne.pl##.tinylittlepicture
ciekawostkihistoryczne.pl##.page:style(background: #dbdbdb !important;)
ciekawostkihistoryczne.pl##.single:style(background: #dbdbdb !important;)
```
