### ISSUE TITLE
Facebook.com

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#4807]
Hej ktoras z naszych list zabiera ikonke messengera z gornej belki FB na PC 

z UBO: 
![screenshot_1](https://user-images.githubusercontent.com/21177361/33793912-7e98c348-dcc1-11e7-8288-40c66c107ecd.png)

Bez UBO: 
![screenshot_2](https://user-images.githubusercontent.com/21177361/33793954-057a233e-dcc2-11e7-9839-613e163a27ef.png)

**Comment by mat41997** [comment]
u mnie jest ok.

**Comment by gzenio22** [comment]
kurde nie ogarniam odznaczam listy a ikona dalej sie nie pokazuje dopiero jak cale ubo wylacze ikona wraca

**Comment by mat41997** [comment]
@gzenio22 to teraz powłączaj od końca.

**Comment by gzenio22** [comment]
wylaczalem po kolei Xd i sprawdzalem kazdy filtr moze ktos to bd mial

**Comment by mat41997** [comment]
zrób kopie zapasową i przywróć domyślną konfigurację.

po czym pobierz jeszcze raz wszystkie filtry
https://www.certyficate.it/adblock/

**Comment by gzenio22** [comment]
not work :(

**Comment by mat41997** [comment]
a sprawdź mojego nano adblockera, czy na nim masz to samo
`https://chrome.google.com/webstore/detail/nano-adblocker/gabbbocakeomblphkmmnoamkioajlkfo`

**Comment by gzenio22** [comment]
daj mi chwile doinstaluje filtry :D

**Comment by mat41997** [comment]
@gzenio22 rzuć tu swoją kopie zapasową i podaj link
https://gist.github.com/

**Comment by gzenio22** [comment]
@mat41997 zabrzmie jak noob ale jak moge skopiowac liste? XD

**Comment by mat41997** [comment]
trzeba będzie dodać do wiki.

**Comment by gzenio22** [comment]
wybacz Xd

**Comment by mat41997** [comment]
spx. dawno się przyzwyczaiłem do takich rzeczy.
przez 5 lat pomagałem na forum miencrafta, tam to dopiero jest ciekawie.

**Comment by gzenio22** [comment]
Wiesz ja pomagam ludziom na FB w kilku kwestjach Xd jezusie niektuzy naprawde nie rozumieją banalnych zeczy ostatnio znajomemu doinstalowywalem filtry no i daje mu strone bodaj AAK zeby zasubował ich liste a ten do mnie wejdz mi na TeamVievera bo ja nie umiem a ja takie ja pierdale Xd

**Comment by mat41997** [comment]
@gzenio22 wystarczyło podać mu link do naszego wiki

**Comment by mat41997** [comment]
gotowe

https://github.com/MajkiIT/polish-ads-filter/wiki/Jak-stworzy%C4%87,-opublikowa%C4%87-i-za%C5%82adowa%C4%87-kopie-zapasow%C4%85-ustawie%C5%84-uBlock-Origin-&-Nano-Adblocker

**Comment by gzenio22** [comment]
https://gist.github.com/gzenio22/fbc6e4e1f8f3e556e1ea6aca8f85ac10

**Comment by mat41997** [comment]
u mnie wszystko w porządku
![2017-12-09 11_36_52-facebook](https://user-images.githubusercontent.com/5884000/33794918-75f97cf0-dcd5-11e7-9935-71d9a6b4a2b7.png)

wychodzi na to że albo istnieje jakaś procedura uruchamiania tego buga, albo masz masz jakieś inne rozszerzenie które to blokuje.

próbowałeś czyścić cookie/cache?

**Comment by mat41997** [comment]
oo.. wgl masz starą wersje ublocka
  "version": "1.14.16"

**Comment by gzenio22** [comment]
no wlasnie ubo mi sie kurde sam nie aktualizuje... a powinien

**Comment by mat41997** [comment]
@gzenio22 spróbuj usunąć ublocka, po czym zainstaluj jeszcze raz. ewentualnie wymuś aktualizacje w trybie programistycznym.

**Comment by hawkeye116477** [comment]
Może to znowu Fanboy's Antithirdparty Social

**Comment by gzenio22** [comment]
@hawkeye116477 wlasnie problem w tym ze tym razem nie... sprawdzilem kazda liste po kolei i zadna z list tego nie rozwala a mimo to gdy wylacze ubo ikonka wraca

**Comment by gzenio22** [comment]
Moze tak cos rozkminicie 

https://pastebin.com/s5SXvAxf

**Comment by xxcriticxx** [comment]
@gzenio22 cookies i cache czysciles?

**Comment by gzenio22** [comment]
tak zqa kazdym razem

**Comment by xxcriticxx** [comment]
wyloncz wszystkie listy social i privacy potem czyszczenie cache from beginning of time

i ciastka recznie skasuj just in case

**Comment by gzenio22** [comment]
@xxcriticxx To teraz daj mi screeny tego co ty masz po wlanczane zrobie tak samo u siebie Xd

**Comment by xxcriticxx** [comment]
ja fb nie uzywam i mam host file wlonczone 

fb napewno sprawdza czy masz dobre ciastka

**Comment by gzenio22** [comment]
Po reinstallu calego zestawu sie wszystko ogarneło dzieki za pomoc wszystkim :)
