### ISSUE TITLE
nano defender

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4809]
@hawkeye116477 trzeba pozmieniac wszystko w wiki

**Comment by hawkeye116477** [comment]
@xxcriticxx Zrobione, na razie tylko nie ma instrukcji jak to zrobić w Firefoksie, bo się okazuje, że wyłączenie podpisywania działa tylko w Nightly i Waterfoksie.

**Comment by xxcriticxx** [comment]
@hawkeye116477 thank you

**Comment by userOperaFF** [comment]
Jak coś to dodaję czasem nagłówki i jak się da to spis treści, ucinam z wyglądu linków http  / https.

**Comment by hawkeye116477** [comment]
`Note: If you have another User Resources in use, then you would need to either switch to Nano Adblocker or manually merge resources. It takes an eternity to get any resources into uAssets, I have tried.`

O co tutaj chodzi?

**Comment by xxcriticxx** [comment]
@hawkeye116477 na firefox zrobil fork ubo o nazwie nano adblocker tak mi chyba sie zdaje. i jak masz jakis sensny filtr to z dodaniem do uassets troche zajmuje. chyba pingwin bendzie sam dodawal.

**Comment by hawkeye116477** [comment]
@xxcriticxx Bardziej mi chodziło o User Resources. A Nano Adblocker jest tylko dla Chromium.

**Comment by xxcriticxx** [comment]
@hawkeye116477 zapytaj na jego forum

**Comment by userOperaFF** [comment]
> 2. Wejdź w about:config, znajdź `xpinstall.signatures.required` i ustaw na false.

a

>Allow running of unsigned extensions

Może przełączenie nie ma sensu (nie mam jak sprawdzić bo mam 32 bitowy system).

**Comment by hawkeye116477** [comment]
@userOperaFF W przypadku Waterfoxa nie ma sensu, bo jest to już domyślnie ustawione, ale w przypadku Nightly może mieć sens.

**Comment by userOperaFF** [comment]
Dodałam opcje instalacji real nano defender (beta), jak macie czas możecie dopracować na podstawie opisu z:

https://jspenguin2017.github.io/uBlockProtector/

Trochę dziwne że wcześniej po instalacji to od razu działało.

**Comment by hawkeye116477** [comment]
Tylko nie wiem czy dla Firefoxa konieczna jest instrukcja, w końcu pingwin ją napisał, dla Chroma tak samo jest. Bardziej przydałaby się dla Waterfoksa, na którym sposób dla Firefoxa nie działa, bo Waterfox jest na wersji 56.

**Comment by userOperaFF** [comment]
Mnie najbardziej zastanawia co robi zmiana tych źródeł, że same wskoczą na listę wyżej?

**Comment by hawkeye116477** [comment]
Ok, tylko, że instrukcja dla Waterfoxa trochę za długa, zaraz poprawię 😄 .

**Comment by userOperaFF** [comment]
A ja już chyba rozumiem do czego ta opcja z źródłami - dodatkowe skrypty blokujące.

**Comment by LArtCrime** [comment]
Dziwna sprawa jeden z tych dwóch dodatków do instalowania defendera na Operze sam mi ją aktualizuje.

Będzie trzeba prześledzić githuby ich i zobaczy który to dodał czy może funkcja w Operze.

**Comment by krystian3w** [comment]
@hawkeye116477 [Jak zainstalować Nano Defender  Waterfoksie](https://github.com/MajkiIT/polish-ads-filter/wiki/Jak-zainstalowa%C4%87-Nano-Defender-na-Firefoksie,-Waterfoksie-albo-(Chr)Operze%3F#ii-waterfox "https://github.com/MajkiIT/polish-ads-filter/wiki/Jak-zainstalowa%C4%87-Nano-Defender-na-Firefoksie,-Waterfoksie-albo-(Chr)Operze%3F#ii-waterfox")

Link do dodatku wyłączającego sprawdzanie kompatybilności nie działa, jakimś cudem ma na końcu `"`.
