### ISSUE TITLE
numery na main 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4810]
te numery to sie zmieniaja?

![capture](https://user-images.githubusercontent.com/15007183/33796708-0fb799a2-dcc8-11e7-9b04-1808192e8fc4.PNG)

**Comment by hawkeye116477** [comment]
Jak na razie to się coś nie zmieniły. Ale jeszcze chyba nie było tak, żeby otwartych issues było więcej niż 1%.  A issue resolution to średni czas na rozwiązywanie problemów, widocznie mało było szybciej rozwiązanych spraw albo wcale, dlatego zapewne to się nie zmieniło.

**Comment by hawkeye116477** [comment]
Te z shields.io są trochę inne, bo nie ma issue resolution, a open issues jest w liczbach a nie procentowo oraz można sobie zmieniać kolor i długość życia HTTP cache w sekundach.

**Comment by xxcriticxx** [comment]
moze zmieszamy?

**Comment by MajkiIT** [comment]
Nic nie stoi na przeszkodzie :P

**Comment by xxcriticxx** [comment]
@MajkiIT to dodaj co ma sens
