### ISSUE TITLE
popularne.net

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4811]
![2017-12-09 23_04_44-niecodzienny widok w warszawie na brzegu wisly pojawil sie 15-metrowy wieloryb](https://user-images.githubusercontent.com/5884000/33799914-94d078c6-dd35-11e7-908b-deed38cd816a.png)

![2017-12-09 23_04_56-niecodzienny widok w warszawie na brzegu wisly pojawil sie 15-metrowy wieloryb](https://user-images.githubusercontent.com/5884000/33799915-98bcfffe-dd35-11e7-9e28-3adfb4de7a01.png)
`https://popularne.net/wieloryb/?utm_source=Facebook&utm_medium=cpm&utm_campaign=special_soft`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.3
Nano Defender 12.134
Chrome 63.0.3239.84

**Comment by xxcriticxx** [comment]
@mat41997 dziura na topie i na dole?

**Comment by hawkeye116477** [comment]
`popularne.net##.devel-billboard`
