### ISSUE TITLE
wiadomosci.wp.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4812]
![2017-12-10 01_14_28-walesa skomentowal zmiany w rzadzie padly mocne slowa - wp wiadomosci](https://user-images.githubusercontent.com/5884000/33800767-96d2e4a8-dd47-11e7-8866-b0b94f6c3642.png)
`https://wiadomosci.wp.pl/zostali-zatrzymani-bo-obrzucili-rzadowe-limuzyny-jajkami-zdjecie-pisarki-rozchodzi-sie-po-sieci-6196459536631937a`

stopka nie rozwija

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.3
Nano Defender 12.134
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
U mnie jest ok. @hawkeye116477 @xxcriticxx zerkniecie?

**Comment by xxcriticxx** [comment]
@MajkiIT u mnie jest giteks

@mat41997 bo to jest koniec strony zobacz na suwak z prawej strony

**Comment by hawkeye116477** [comment]
@MajkiIT Nie jest ok. Po naciśnięciu więcej powinno się pokazać coś takiego:
![screenshot_20171210_204817](https://user-images.githubusercontent.com/19818572/33808726-7d67905a-ddeb-11e7-8f1c-26f79e476437.png)

**Comment by xxcriticxx** [comment]
@hawkeye116477 tego umnie nie ma 

jak @mat41997 by napisal naco kliknoc to by bylo szybcej

**Comment by mat41997** [comment]
@xxcriticxx to na co klinął @hawkeye116477

**Comment by xxcriticxx** [comment]
tak nie ma wiecej tematow 

@mat41997 

@hawkeye116477 ma lepszy setup :)

**Comment by hawkeye116477** [comment]
@xxcriticxx Jak przewiniesz na sam dół to powinno się to pojawić.

**Comment by xxcriticxx** [comment]
@hawkeye116477 pokazalo sie
