### ISSUE TITLE
histografy.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4813]
![2017-12-10 01_21_47-robot _the beetle_ _ histografy](https://user-images.githubusercontent.com/5884000/33800809-be67fb56-dd48-11e7-938e-118cef15a0d2.png)
`http://histografy.pl/robot-the-beetle/`

puste tabelki + zenbox

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.3
Nano Defender 12.134
Chrome 63.0.3239.84

**Comment by hawkeye116477** [comment]
Resztki reklamowe -> `histografy.pl###text-9`
Resztki socialowe -> `histografy.pl###text-2`
