### ISSUE TITLE
forum.abczdrowie.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4816]
![2017-12-10 01_58_06-forum zywienie i fitness _ abczdrowie pl](https://user-images.githubusercontent.com/5884000/33801019-d060a3a8-dd4d-11e7-9825-e10fefdcbe9c.png)

![2017-12-10 01_58_32-forum zywienie i fitness _ abczdrowie pl](https://user-images.githubusercontent.com/5884000/33801020-d4d156bc-dd4d-11e7-8fb6-d30f2ad9c66c.png)
`https://forum.abczdrowie.pl/forum-zywienie-i-fitness`

wyczyść cookie/cache

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.3
Nano Defender 12.134
Chrome 63.0.3239.84

**Comment by xxcriticxx** [comment]
nie mam reklam ale mam cookies na topie `###WP-cookie-info`

![capture](https://user-images.githubusercontent.com/15007183/33805002-1031e6f0-dd7f-11e7-916b-528f6d58dd45.PNG)

**Comment by hawkeye116477** [comment]
Nie ma ciastek.

**Comment by xxcriticxx** [comment]
sorry avast againt
