### ISSUE TITLE
nasztomaszow.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4817]
![2017-12-10 04_02_22-tomaszow mazowiecki](https://user-images.githubusercontent.com/5884000/33801559-236ea638-dd5f-11e7-81c5-45d3ceccc8b4.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.3
Nano Defender 12.134
Chrome 63.0.3239.84

**Comment by hawkeye116477** [comment]
![screenshot_20171210_110340](https://user-images.githubusercontent.com/19818572/33803858-d2887d12-dd99-11e7-8f9b-8db8ff8b26ad.png)
