### ISSUE TITLE
mybank.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4822]
cookies

Serwis MyBank.pl korzysta z plików cookies w celu realizacji usług i zgodnie z Polityką Plików Cookies.
Możesz określić warunki przechowywania lub dostępu do plików cookies w Twojej przeglądarce. [Zamknij tą informację]

**Comment by hawkeye116477** [comment]
Ciasteczek niby nie ma, ale regułę ciasteczkową trzeba będzie poprawić, bo blokuje header.
Jest też jeszcze czarny pasek reklamowy -> `mybank.pl###pasek-gora`
