### ISSUE TITLE
ciekawostkihistoryczne.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4823]
![2017-12-10 20_52_57-w tym europejskim kraju wydobywano jedna trzecia swiatowego zlota i dotad nie m](https://user-images.githubusercontent.com/5884000/33808776-2513cab2-ddec-11e7-949e-3e93fa5a29d9.png)
`http://ciekawostkihistoryczne.pl/2017/11/21/w-tym-europejskim-kraju-wydobywano-jedna-trzecia-swiatowego-zlota-i-dotad-nie-miales-o-tym-pojecia/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.6
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
`ciekawostkihistoryczne.pl###sidheight`
