### ISSUE TITLE
pyszne.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4827]
cookies

`###iprivacybanner`

**Comment by hawkeye116477** [comment]
@xxcriticxx Ciasteczek nie ma, znowu avastujesz 😄 .

**Comment by mat41997** [comment]
@xxcriticxx może zmień antyvira, polecam kaspera

**Comment by hawkeye116477** [comment]
Kasper jest ciężki, potrafi zamulić. Eset jest the best po wyłączeniu wykrywania potencjalnie niebezpiecznych czy tam niepożądanych rzeczy 😄 .

**Comment by xxcriticxx** [comment]
kasperski zglasza do putina wszystko 
avast do trumpa

**Comment by hawkeye116477** [comment]
Jeśli tak lubicie Kaspra, to jest konkurs -> https://programyzadarmo.net.pl/threads/konkurs-pzd-kaspersky-internet-security-2018.34087/ , do wygrania 3 roczne licencje KIS 2018.

**Comment by mat41997** [comment]
@hawkeye116477 weź nie dobroprogramuj

**Comment by xxcriticxx** [comment]
@hawkeye116477 to kosztuje przecietnie z $10 w usa
