### ISSUE TITLE
szalonewalizki.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4828]
![2017-12-10 23_43_12-szalone walizki - blog podrozniczy doroty i jarka _ szukasz ciekawych przygod i](https://user-images.githubusercontent.com/5884000/33810366-00d48c5a-de04-11e7-9df4-4cfd12049118.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.6
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
`szalonewalizki.pl##.widget-ads-content`
