### ISSUE TITLE
AdguardTeam/AdguardForAndroid

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#483]
https://github.com/AdguardTeam/AdguardForAndroid/issues/354

**Comment by xxcriticxx** [comment]
czemu cookies nie na githubie?

**Comment by MajkiIT** [comment]
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt

**Comment by xxcriticxx** [comment]
poprawilem
