### ISSUE TITLE
twojahistoria.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4830]
![2017-12-11 00_28_18-muzeum inne niz wszystkie_ w nowo otwartej krakowskiej placowce mozna podgladac](https://user-images.githubusercontent.com/5884000/33810827-4a273d84-de0a-11e7-899b-274b0f506ac8.png)
`http://twojahistoria.pl/2017/12/07/muzeum-inne-niz-wszystkie-w-nowo-otwartej-krakowskiej-placowce-mozna-podgladac-konserwatorow-przy-pracy/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.6
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
```
twojahistoria.pl##.topbn.row
twojahistoria.pl##.backbglink
||twojahistoria.pl/uploads/20*/*/*-bg.jpg$image
```
