### ISSUE TITLE
nacjonalista.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4831]
![2017-12-11 00_34_00-neokolonia_ polak na mieszkanie pracuje srednio 36 lat _ nacjonalista pl](https://user-images.githubusercontent.com/5884000/33810871-034b31b2-de0b-11e7-85c9-cec7a6cc51eb.png)
`http://www.nacjonalista.pl/2017/12/09/neokolonia-polak-na-mieszkanie-pracuje-srednio-36-lat/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.6
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
```
||www.nacjonalista.pl/wp-content/uploads/20*/*/*.gif$image
www.nacjonalista.pl##center
```
