### ISSUE TITLE
money.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4835]
![2017-12-11 05_37_31-polacy odrzucili prosbe gazpromu morawiecki zapowiada _uniezaleznienie sie_ od](https://user-images.githubusercontent.com/5884000/33815896-68f14b62-de35-11e7-924a-48c19b275bbc.png)
`https://www.money.pl/gospodarka/unia-europejska/wiadomosci/artykul/gazprom-pgnig-prosba-kontakt-jamalski,140,0,2393228.html`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.7
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
@mat41997 ja tego nie widzę.
@hawkeye116477 @xxcriticxx  zerkniesz?

**Comment by hawkeye116477** [comment]
@MajkiIT Nie ma wody na pustyni 😃

**Comment by xxcriticxx** [comment]
@MajkiIT u mnie jest ok
