### ISSUE TITLE
nexto.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4837]
![2017-12-11 08_46_05-nexto pl - ebooki i e-prasa kindle mobi epub pdf audiobooki mp3 - eksiegarnia](https://user-images.githubusercontent.com/5884000/33820527-25d123a0-de50-11e7-80f0-a68a364220a9.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.8
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
@mat41997 u mnie ok.
@hawkeye116477 zerkniesz?

**Comment by hawkeye116477** [comment]
Social jest, ale tak po za tym to ok.

**Comment by xxcriticxx** [comment]
@MajkiIT ja blokuje hostem `rec.quartic.pl is 192.168.1.131` @mat41997 napewno tez
