### ISSUE TITLE
interia.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4838]
![2017-12-11 09_17_19-interia - polska i swiat_ informacje sport gwiazdy](https://user-images.githubusercontent.com/5884000/33821454-27a2bf14-de54-11e7-9115-968a92f4045e.png)

jackpot

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.8
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
`interia.pl##.entertainment-li.i10 > .entertainment-a`
