### ISSUE TITLE
radio.opole.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4840]
![2017-12-11 09_59_27-radio opole](https://user-images.githubusercontent.com/5884000/33823053-0065b504-de5a-11e7-89c6-2e81790ff918.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.8
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
@mat41997 u mnie jest ok.
@xxcriticxx @hawkeye116477 zerkniecie?

**Comment by hawkeye116477** [comment]
To wina Popup Blocker PLUS.

**Comment by xxcriticxx** [comment]
@MajkiIT jest kilka dziur po miedzy artykulami na main page `.bannerplace`
