### ISSUE TITLE
konflikty.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4849]
![2017-12-12 01_08_56-konflikty pl](https://user-images.githubusercontent.com/5884000/33860484-5138f78c-ded9-11e7-8942-48837c71389e.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.9
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
`konflikty.pl##.vwpc-section-custom_content`
