### ISSUE TITLE
portel.pl

### ISSUE THREAD

**Issue by makxx** [MajkiIT/polish-ads-filter#4853]
### Zrzut ekranu
![007183ad-5c66-41f7-832e-e5428c39b27e](https://user-images.githubusercontent.com/34417956/33903715-8c3dd0e6-df79-11e7-9296-3b860b6ada70.jpg)

### Link bezpośredni
www.portel.pl

### Moja konfiguracja
**Przeglądarka internetowa:**

Vivaldi | 1.13.1008.36
**Rozszerzenia i skrypty:**
ublock 1.14.20
**Filtry:**
https://gist.github.com/makxx/1e284a99787685e77a18a4948d3a6912

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Do sprawdzenia, ewentualnie poprawienia.
/^(http|https):\/\/www\.portel\.pl\/[r0-9]{2,}/$image,subdocument,domain=www.portel.pl

**Comment by xxcriticxx** [comment]
@makxx ostatnie filtry wylapuja wiekszosc rzeczy
