### ISSUE TITLE
niezalezna.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4860]
![2017-12-13 05_40_29-niezalezna - wiadomosci _ informacje _ wydarzenia - polska i swiat](https://user-images.githubusercontent.com/5884000/33922045-4f8155d4-dfc8-11e7-9a3d-9cb91350bde3.png)

link zewnętrzny

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.10
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
to zwykły link.
