### ISSUE TITLE
pomponik.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4862]
![2017-12-13 10_31_31-dorota r na aferze traci fortune_ to dla niej bardzo zla wiadomosc - pomponik](https://user-images.githubusercontent.com/5884000/33931641-e26ea7d4-dff0-11e7-90a2-1cabf48aeec6.png)
`http://www.pomponik.pl/plotki/news-dorota-r-na-aferze-traci-fortune-to-dla-niej-bardzo-zla-wiad,nId,2476106`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.10
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
`||shoperia.pl/$subdocument`
