### ISSUE TITLE
dziwnekomiksy.pl

### ISSUE THREAD

**Issue by arturkulig** [MajkiIT/polish-ads-filter#4863]
### Zrzut ekranu
<img width="1141" alt="zrzut ekranu 2017-12-13 o 12 16 54" src="https://user-images.githubusercontent.com/4066587/33936408-ae41902a-dfff-11e7-96ed-269fcfb6fc28.png">

### Link bezpośredni
http://dziwnekomiksy.pl

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. wejść

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

aby usunąć komunikat, należy usunąć node o id `adbk` i zniwelować styl
```
body > * {
    filter: blur(5px);
}
```

**Comment by mat41997** [comment]
na szybko mogę polecić dodatek do ublocka : nano defender
`https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb`

**Comment by hawkeye116477** [comment]
Do filtrów tylko dla uBo
```
dziwnekomiksy.pl###adbk
dziwnekomiksy.pl##body>*:style(filter: blur(0px) !important;)
```

Coś słaby ich ten antyadblock 😄 .
