### ISSUE TITLE
echodnia.eu

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4864]
![2017-12-13 14_35_29-podkarpackie - najnowsze wiadomosci z tarnobrzegu i okolic](https://user-images.githubusercontent.com/5884000/33941473-14ddb4a4-e013-11e7-9a7a-47a0dfee5c13.png)

![2017-12-13 14_35_49-podkarpackie - najnowsze wiadomosci z tarnobrzegu i okolic](https://user-images.githubusercontent.com/5884000/33941479-199129ae-e013-11e7-9296-ce121b211367.png)
`http://www.echodnia.eu/podkarpackie/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.10
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
```
echodnia.eu##.typBaner
echodnia.eu##.promoBox
```
