### ISSUE TITLE
gospodarkamorska.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4865]
![2017-12-13 15_29_16-gospodarka morska - portal branzowy portal morski](https://user-images.githubusercontent.com/5884000/33943814-6dc18eea-e01a-11e7-92e7-e1f102214d06.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.10
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
@mat41997 u mnie jest ok. @hawkeye116477 zerkniesz?
