### ISSUE TITLE
metalnews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4866]
![2017-12-13 16_47_01-metalnews pl - metalowy serwis informacyjny](https://user-images.githubusercontent.com/5884000/33950141-e59d7c38-e02b-11e7-8fe4-3216e129036e.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.10
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
`metalnews.pl##.custom-html-widget`
