### ISSUE TITLE
wieliczkacity.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4867]
![2017-12-13 18_21_23-wieliczka city - portal miasta wieliczka](https://user-images.githubusercontent.com/5884000/33952574-87599826-e032-11e7-9ebc-050bc4d000bf.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.10
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
```
wieliczkacity.pl##A[target="_blank"] > IMG
wieliczkacity.pl##A[target="_self"] > IMG
```
