### ISSUE TITLE
androidpolska.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4869]
![2017-12-14 06_45_38-androidpolska pl - android gry i aplikacje](https://user-images.githubusercontent.com/5884000/33977290-8169743c-e09a-11e7-9694-a07bc0041ad2.png)

![2017-12-14 06_47_39-android snapchat](https://user-images.githubusercontent.com/5884000/33977353-c1709790-e09a-11e7-8a5d-4f480f1698f2.png)
`http://androidpolska.pl/view/snapchat/8303`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.12
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
`androidpolska.pl###widget_data_placement`
