### ISSUE TITLE
agrokapital.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4871]
![2017-12-14 07_02_53-portal dla rolnikow _ agrokapital pl](https://user-images.githubusercontent.com/5884000/33977839-1a06cd46-e09d-11e7-8a5b-9d695f801df6.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.12
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
`agrokapital.pl##A[target="_blank"] > IMG`
