### ISSUE TITLE
poradnikprzedsiebiorcy.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4878]
![2017-12-14 14_18_53-poradnik przedsiebiorcy](https://user-images.githubusercontent.com/5884000/33994180-ccaa105c-e0d9-11e7-83fd-f47626ca977d.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.12
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by MajkiIT** [comment]
@hawkeye116477 to hcyab pozostałość po popup ?

**Comment by hawkeye116477** [comment]
To jest reklama -> ![screenshot_20171214_183722](https://user-images.githubusercontent.com/19818572/34006227-e0ce351c-e0fd-11e7-99dd-0593f652fb8d.png)
Popup Blocker to blokuje, ale scroll się blokuje.

**Comment by MajkiIT** [comment]
@hawkeye116477 Ok, dziękuję

**Comment by hawkeye116477** [comment]
Tego tu jest trochę w ogóle więcej niż popup, na dole to samo się powtarza, ale moja reguła to usuwa.  Na górze też coś jest po rozwinięciu i nie wiem czy to też nie do wywalenia.
