### ISSUE TITLE
player.pl - kolko

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#4881]
jak wylaczyc te kolko w player.pl ?

![1](https://user-images.githubusercontent.com/17565773/34012073-aa1dc784-e112-11e7-9bbb-a973c1fc9a5f.jpg)

**Comment by hawkeye116477** [comment]
@lukjan32 Wykupić szybszy net 😄 .

**Comment by lukjan32** [comment]
mam 20 mb

**Comment by hawkeye116477** [comment]
@lukjan32 W Orange? Jeśli tak, to do 20, czyli pewnie za wolno 😃  Speedtest co pokazuje?

**Comment by lukjan32** [comment]
tak, orange. 14 mb

**Comment by MajkiIT** [comment]
u mnie tego nie ma, Może komp ? CPU?

**Comment by hawkeye116477** [comment]
Ja to bym raczej bym obstawiał problem z netem, wielu pisało, że w Orange 20 mb=2 mb. Pewnie czasem jest więcej, czasem mniej, bardzo mało i dlatego kółko się ładuje. Trzeba zmienić ISP na jakiegoś lokalnego to problem zniknie.

**Comment by hawkeye116477** [comment]
@lukjan32 Zrób test zgodności -> https://player.pl/przetestuj-usluge.html

**Comment by xxcriticxx** [comment]
@MajkiIT proxy please

![capture](https://user-images.githubusercontent.com/15007183/34016679-ce52847c-e0f0-11e7-9ddd-a19e231e09a0.PNG)

**Comment by blocker999** [comment]
@lukjan32 jaki masz router/modem, od operatora?, jak możesz to sprawdź to na innym sprzęcie.

**Comment by lukjan32** [comment]
@hawkeye116477 jest za slaba predkosc

@blocker999 mam od tp-linka. nie mam mozliwosci

**Comment by mat41997** [comment]
@lukjan32 wbij na discorda, spróbuje pomóc indywidualnie
https://discord.gg/ZsnUqNT

**Comment by lukjan32** [comment]
@MajkiIT nie mam konta w discord

**Comment by mat41997** [comment]
@lukjan32 jak każdy przed jego założeniem ^^
poleciłem ci discorda żeby móc być bardziej responsywnym.

**Comment by lukjan32** [comment]
juz mam tyle kont, ze nie pamietam, gdzie mam.

**Comment by blocker999** [comment]
OK możesz podać model tego tp- linka ?

**Comment by lukjan32** [comment]
TD-W8960N v.3

**Comment by blocker999** [comment]
Najlepiej zapytaj tu: http://www.bez-kabli.pl/index.php  lub tu:http://www.telepolis.pl/forum/viewforum.php?f=4 prawdopodobnie to coś z konfiguracją a ja raczej tu nic nieździałam a jak tam zawiele nie pomogą to chyba tylko wypowiedzenie umowy.

**Comment by lukjan32** [comment]
aha, i tak chce zrezygnowac z neostrady, jak sie skonczy umowa.

**Comment by lukjan32** [comment]
juz nie ma kolka, ktos zmienil

**Comment by blocker999** [comment]
To że teraz niema to nieznaczy że znowu się niepojawi, więc ja bym napisał na te fora no chyba że wolisz płacić i się męczyć, tylko pytanie ile ?

**Comment by hawkeye116477** [comment]
Moim zdaniem to nie jest problem po stronie routera, to wina Orange i tyle, wielu ludzi pisało, że u nich po prostu tak jest i tyle.

**Comment by lukjan32** [comment]
no, oby. 

byle do maja wytrzymac :)

**Comment by blocker999** [comment]
Masz neta przez wifi więc niedziwota że czasami masz " kółko ", jak chcesz stabilnie oglądać player.pl to załatw se kabel do routera.

**Comment by xxcriticxx** [comment]
Netflix na 4 nie lepsze investycja?

**Comment by hawkeye116477** [comment]
Przez wifi też potrafi stabilnie działać, trzeba tylko dobrać dobrego ISP lokalnego.
@blocker999 Pracujesz w Orange?
