### ISSUE TITLE
donation message

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#4885]
@MajkiIT moze cos takiego?

polish-ads-filter may be free but running the project costs money. Support polish-ads-filter by making a donation which helps grow the project.

**Comment by mat41997** [comment]
toż to rak, ale to tylko moje zdanie.

**Comment by mat41997** [comment]
toż to rak, ale to tylko moje zdanie.
za to można dodać tag z linkiem do patronite na readme

**Comment by xxcriticxx** [comment]
Patrionite mieliśmy nie działało za dobrze może potestujemy paypal albo bitcoin albo coś innego może pomieszamy tak jak zawsze

**Comment by mat41997** [comment]
@xxcriticxx bitcoin ma teraz zbyt wielkie opłaty transakcyjne.
