### ISSUE TITLE
Use `!#include` directive to remove need for two filter lists in uBO

### ISSUE THREAD

**Issue by gorhill** [MajkiIT/polish-ads-filter#4898]
uBlock Origin 1.14.23b0 is now able to load sublists using the `!#include sublist-filename` directive.

See <https://github.com/AdguardTeam/AdguardBrowserExtension/issues/917> for details of outcome of discussing the core issue raised at <https://github.com/gorhill/uBlock/issues/3331>.

In uBO, there are two POL lists: one which is fully compatible with Adblock Plus, and another one which makes use of extended filter syntax understood by uBO, but which can break Adblock Plus.

Ideally, from the perspective of a uBO user, there should be no such thing as two POL lists in the _"3rd-party filters"_ pane. The new `!#include` directive, agreed upon with Adguard's @ameshkov (along with other directives to seamlessly extend capabilities of blockers), addresses this.

If you add the following `!#include` directive in [_Adblock & uBlock polish filters_](https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt):

    !#include adblock_ublock.txt

uBO will transparently fetch the list [_uBlock polish filters - supplement_](https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt) and concatenate it to the embedding list.

Result: one single POL list from the user's perspective, and since the new directive syntax starts with a `!`, it keeps the embedding list compatible with ABP.

Furthermore, this new directive removes an obstacle for all current filter list maintainers to use extended filter syntax: all the existing lists will still be compatible with ABP, but uBO's extended filter syntax can now be safely leveraged by telling the blockers who care about such extended syntax to load extra lists from within the main list using the `!#include` directive.

Once the base list for POL supports the `!#include` directive and the new capability in uBO is published and widespread, this will allow me to remove the extraneous POL list.

Keep in mind this will also be supported by Adguard, so you can also use such `!#include` directive to ask a blocker to load Adguard-specific filter as well from the main list:

    !#include adblock_adguard.txt

**Comment by MajkiIT** [comment]
@gorhill ok thanks

**Comment by MajkiIT** [comment]
@F4z widzisz sens dodawania do main równiez filtrów do Adguard ?

**Comment by hawkeye116477** [comment]
Ja tam bym po prostu połączył filtry uBlocka i AdGuarda w jedną listę - uzupełnienie do uBlocka i AdGuarda, a jeśli coś robi problem na AG, to zawsze można napisać:
```
!+ PLATFORM(ext_ublock)
||example.org^
```

**Comment by ameshkov** [comment]
Guys, we'll add the `#include` directive support, but it'll take a couple of months to implement it in every AG product and roll this out to everybody. Sorry for the delays, it's difficult to do anything when there're multiple different products.

I can alert you once it's done.

**Comment by MajkiIT** [comment]
@ameshkov Ok thanks.
