### ISSUE TITLE
www.axn.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#492]
film sie zaczyna player jest czarny cos leci przez 2 sec i tak w kolko

http://www.axn.pl/axn-player/wiecej/pelne-odcinki/w-sercu-oceanu-104
http://www.axn.pl/axn-player/wiecej/ziemia-buntownikow/ziemia-buntownikow-205
http://www.axn.pl/axn-player/wiecej/jazda-probna/jazda-probna-101

**Comment by MajkiIT** [comment]
u mnie jest OK.

**Comment by xxcriticxx** [comment]
hyba geo lock ja jestem w usa
