### ISSUE TITLE
miastokolobrzeg.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4952]
![2017-12-15 20_51_44-informacje kolobrzeg - miastokolobrzeg pl](https://user-images.githubusercontent.com/5884000/34058006-c9d76522-e1d9-11e7-8565-a96f4ee36ca4.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by hawkeye116477** [comment]
@MajkiIT Tu jest reklama.
