### ISSUE TITLE
instrukcja.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5000]
![2017-12-16 03_22_46-portal praktycznej wiedzy najwieksza baza instrukcji instrukcje obslugi pora](https://user-images.githubusercontent.com/5884000/34066537-6f415d70-e210-11e7-859d-b6cfaaa6198c.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by xxcriticxx** [comment]
@mat41997 gratulacje!
