### ISSUE TITLE
probasket.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5026]
![2017-12-16 06_09_06-plk_ sensacyjna porazka stelmetu w lublinie mistrz pokonany _ probasket](https://user-images.githubusercontent.com/5884000/34067492-a612c6e2-e227-11e7-8005-4ff9728572ab.png)
`http://probasket.pl/plk-sensacyjna-porazka-stelmetu-w-lublinie-mistrz-pokonany/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`||video.vid4u.org^`
