### ISSUE TITLE
tyna.info.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5038]
![2017-12-16 06_58_39-tygodnik nadwislanski jestesmy z wami od 1981 roku](https://user-images.githubusercontent.com/5884000/34067742-9452b12c-e22e-11e7-9abf-3505cfceebff.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`tyna.info.pl##A[target="_self"] > IMG`
