### ISSUE TITLE
typosfera.net

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5039]
![2017-12-16 07_00_52-przypadkowosc w zakladach sportowych](https://user-images.githubusercontent.com/5884000/34067754-e282091a-e22e-11e7-8bab-1904afe5aec5.png)
`http://www.typosfera.net/zaklady/n-3602-Przypadkowo%C5%9B%C4%87_w_zak%C5%82adach_sportowych.html`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`typosfera.net##.pull-bottom`
