### ISSUE TITLE
vetopedia.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5041]
![2017-12-16 07_04_25-weterynarz online - twoja lecznica w internecie - opinie o weterynarzach - porta](https://user-images.githubusercontent.com/5884000/34067781-61e32072-e22f-11e7-976e-f473bdb22fc3.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`vetopedia.pl##A[target="_blank"] > IMG`
