### ISSUE TITLE
wronieckibazar.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5043]
![2017-12-16 07_26_07-wroniecki bazar _ wronki wronczanie wiadomosci informacje newsy](https://user-images.githubusercontent.com/5884000/34067909-6b4e773a-e232-11e7-827f-516c7cf88408.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
wronieckibazar.pl##A[target="_blank"] > IMG
wronieckibazar.pl###custom_html-2
```
