### ISSUE TITLE
wsus.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5044]
![2017-12-16 07_28_16-_ wyzsza szkola umiejetnosci spolecznych](https://user-images.githubusercontent.com/5884000/34067924-b45b6db6-e232-11e7-8c76-1fa84770d764.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`wsus.pl##A[target="_blank"] > IMG`
