### ISSUE TITLE
zawiercianskie.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5045]
![2017-12-16 07_30_25-zawiercianskie pl twoje zrodlo informacji z zawiercia powiatu i regionu](https://user-images.githubusercontent.com/5884000/34067936-02d1f726-e233-11e7-9f69-71c413f880f2.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
zawiercianskie.pl###media_image-2
zawiercianskie.pl##A[target="_blank"] > IMG
```
