### ISSUE TITLE
zyciepabianic.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5046]
![2017-12-16 07_34_58-pabianice - miejski portal informacyjny i gazeta zycie pabianic](https://user-images.githubusercontent.com/5884000/34067971-a33e5628-e233-11e7-8f23-8bd6c0086a7f.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`zyciepabianic.pl##A[target="_blank"] > IMG`
