### ISSUE TITLE
nasz-glos.com

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5047]
![2017-12-16 07_40_36-strona glowna](https://user-images.githubusercontent.com/5884000/34067998-73e6f190-e234-11e7-9181-12a383da7339.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`nasz-glos.com##A[target="_blank"] > IMG`
