### ISSUE TITLE
wisport.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#505]
cookies 

Strona korzysta z plikw cookie w celu realizacji usug zgodnie z Polityk cookies. Moesz samodzielnie okreli warunki przechowywania lub dostpu mechanizmu cookie w Twojej przegldarce.
[ Rozumiem, nie pokazuj wicej tego komunikatu. ]

**Comment by MajkiIT** [comment]
alert o zagrożeniach.
