### ISSUE TITLE
elka.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5051]
![2017-12-16 08_01_24-elka pl - inwestor zrezygnowal](https://user-images.githubusercontent.com/5884000/34068167-5ade43da-e237-11e7-9f07-fe09fadcd708.png)
`http://elka.pl/content/view/86870/81/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`elka.pl##A[target="_blank"] > IMG`
