### ISSUE TITLE
tugazeta.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5052]
![2017-12-16 08_08_29-wieruszow - wiadomosci lokalne - lacznik - tugazeta pl](https://user-images.githubusercontent.com/5884000/34068252-5fc17c22-e238-11e7-9c05-f98047a65d02.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`||www.tugazeta.pl/reklamy_new/`
