### ISSUE TITLE
echopowiatu.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5054]
![2017-12-16 08_12_37-echo powiatu - tygodnik powiatu sochaczewskiego](https://user-images.githubusercontent.com/5884000/34068317-ecc12afa-e238-11e7-8ccf-4ab06d061221.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`echopowiatu.pl##A[target="_blank"] > IMG`
