### ISSUE TITLE
miasto.koszalin.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5056]
![2017-12-16 08_26_05-dzis w gazecie](https://user-images.githubusercontent.com/5884000/34068475-d2d7d79a-e23a-11e7-83ab-4bbf541cabcf.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
miasto.koszalin.pl##A[target="_blank"] > IMG
miasto.koszalin.pl###ja-topsl
```
