### ISSUE TITLE
korsosanockie.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5057]
![2017-12-16 08_27_37-korsosanockie pl](https://user-images.githubusercontent.com/5884000/34068483-ff7cdd04-e23a-11e7-81a3-34459d2512f3.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
korsosanockie.pl##[class*="advert"]
korsosanockie.pl##.no-bg.widget
```
