### ISSUE TITLE
mamywsieci.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5058]
![2017-12-16 08_28_48-mamywsieci pl _ warsztaty i atrakcje dla dzieci _ torun bydgoszcz](https://user-images.githubusercontent.com/5884000/34068491-286a256e-e23b-11e7-99f3-b68f17ee2ca7.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`mamywsieci.pl###block-block-20--2`
