### ISSUE TITLE
plonskwsieci.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5059]
![2017-12-16 08_29_54-aktualnosci_ plonsk i powiat plonski](https://user-images.githubusercontent.com/5884000/34068497-53d77ada-e23b-11e7-823e-29064ce8885d.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
||plonskwsieci.pl/images/reklamy_$image
plonskwsieci.pl##.ic_marquee0
plonskwsieci.pl###jm-header-container > .jm-module:nth-of-type(5)
plonskwsieci.pl###jm-header-container > .jm-module:nth-of-type(7)
```
