### ISSUE TITLE
radomnews.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5060]
![2017-12-16 08_34_07-radomnews pl - radomski portal informacyjny](https://user-images.githubusercontent.com/5884000/34068520-ee020896-e23b-11e7-96eb-d3fce5543ee4.png)

pusto

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
radomnews.pl#@#DIV[align="center"]
radomnews.pl##A[target="_blank"] > IMG
```
