### ISSUE TITLE
trybunaczestochowska.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5061]
![2017-12-16 08_58_41-nowa trybuna czestochowska tygodnik lokalny](https://user-images.githubusercontent.com/5884000/34068650-57c564fa-e23f-11e7-8f03-866b96b9f8f9.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`trybunaczestochowska.pl##center`
