### ISSUE TITLE
aferyprawa.eu

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5062]
![2017-12-16 09_01_52-aferyprawa - afery prawa - bezprawie a prawo](https://user-images.githubusercontent.com/5884000/34068674-c7dc4c72-e23f-11e7-9ca6-e3a8d06e142f.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
aferyprawa.eu##A[target="_self"] > IMG
aferyprawa.eu##A[target="_blank"] > IMG
```
