### ISSUE TITLE
dlp-expert.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5064]
![2017-12-16 09_04_45-dlp expert - ochrona przed wyciekiem danych - bezplatny kwartalnik](https://user-images.githubusercontent.com/5884000/34068699-3b3d8dc0-e240-11e7-98e7-7f019556ed2e.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.13
Nano Defender 13.0
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
@mat41997 przestań wrzucać, bo się nie wykopię z tego.
