### ISSUE TITLE
partneragdrtv.com.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#5066]
Blokowane są oferty promocyjne.

A powinno to wyglądać tak
![screenshot_20171216_213743](https://user-images.githubusercontent.com/19818572/34074148-640ba8ae-e2a9-11e7-9756-593f48de99c3.png)

`@@||partneragdrtv.com.pl/temp/adrotator_filemanager/*$image`

**Comment by MajkiIT** [comment]
Ale to Easylist :P

**Comment by hawkeye116477** [comment]
@MajkiIT No to co, przecież jest sekcja Easylist bugs w głównych filtrach 😄

**Comment by xxcriticxx** [comment]
@hawkeye116477 to teraz wszystkie strony agd przelecimy?
