### ISSUE TITLE
polskihurtworld.eu

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#5067]
Królik Marcin sobie kica 😄 . 
![screenshot_20171216_231520](https://user-images.githubusercontent.com/19818572/34074807-9e5b6fb8-e2b7-11e7-9143-5d97f3aa5ac7.png)
`polskihurtworld.eu###myModal`

**Comment by xxcriticxx** [comment]
dup https://github.com/MajkiIT/polish-ads-filter/issues/3862

**Comment by hawkeye116477** [comment]
@MajkiIT Najwyraźniej o tym zapomniał i zamknął temat.
