### ISSUE TITLE
miastokolobrzeg.pl

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#5122]
![2017-12-17 09_51_35-informacje kolobrzeg - miastokolobrzeg pl](https://user-images.githubusercontent.com/5884000/34077949-33857ba8-e310-11e7-80be-0201c4ac208f.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.14
Nano Defender 13.3
Chrome 63.0.3239.108

**Comment by hawkeye116477** [comment]
```
miastokolobrzeg.pl##a[href*="/component/banners/click/"]
miastokolobrzeg.pl###panel_baner, #sp-right
```
