### ISSUE TITLE
przegladbaltycki.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#5129]
Nie widać trochę strony, ciasteczkowy fix -> `@@||przegladbaltycki.pl/wp-content/plugins/uk-cookie-consent/assets/js/uk-cookie-consent-js.js`

**Comment by mat41997** [comment]
![2017-12-17 14_24_48-przeglad baltycki - piszemy o regionie morza baltyckiego](https://user-images.githubusercontent.com/5884000/34079883-160e8dbe-e336-11e7-911e-ef3ed3526e69.png)
