### ISSUE TITLE
dailyweb.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#5134]
Wygląda na to, że blokujesz reklamy :( -> `dailyweb.pl##.row:nth-of-type(4)`

**Comment by xxcriticxx** [comment]
:(

**Comment by MajkiIT** [comment]
`dailyweb.pl##DIV[style="border: 1px solid;margin: 20px 0;max-width:750px;margin:0 auto; line-height: 1.4;text-align:justify;padding:15px;background-repeat: no-repeat;background-position: 10px center;background-color: #ef7163;color:#fff;font-family: Domine, Georgia, serif;"]`
