### ISSUE TITLE
Streamarmy.co.uk

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#5135]
wykrywa adblocka i kupa reklam ktora ang lista to ogarnie? Xd przekazcie to prosze jakims angielskim filtrom

**Comment by hawkeye116477** [comment]
@gzenio22 Już to chłopaki od filtrów uBlocka ogarnęli :smile:,

**Comment by gzenio22** [comment]
Dzieki @hawkeye116477 Wiem moj english jest kiepski Xd dziala wiec tu tez zamykam
