### ISSUE TITLE
pikio.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#5136]
Adblock detect -> `pikio.pl##.adBlockDetectModal, .swal2-fade`

**Comment by xxcriticxx** [comment]
z nano nic nie widze

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale na pewno są tacy co nie posiadają Nano Defendera.

**Comment by xxcriticxx** [comment]
@hawkeye116477 for sure
