### ISSUE TITLE
bitbay.net

### ISSUE THREAD

**Issue by mellrebook** [MajkiIT/polish-ads-filter#5142]
### Zrzut ekranu

![screenshot_2](https://user-images.githubusercontent.com/6104315/34117589-6b1841ce-e41c-11e7-88ff-7dfd925f56a5.png)

### Link bezpośredni
https://app.bitbay.net, https://auth.bitbay.net, https://bitbay.net/pl/kursy-walut
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Po prostu wejść na które kolwiek z tych stron z włączonym adblockiem

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome Wersja 63.0.3239.108 (Oficjalna wersja) (64-bitowa)
**Rozszerzenia i skrypty:**
Tylko Adblock Plus.
**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. EasyList

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Blokowanie załączania elementów z domen bitbay.net powoduje, że giełda całkowicie przestaje działać, przez co muszę usunąć ten zestaw filtrów do momentu rozwiązania problemu.
Rozumiem, że bitbay trafił na listę z względów na linki afiliacyjne, z tego co wiem, wszystkie linki afiliacyjne mają konkretną strukturę:
`https://auth.bitbay.net/ref/{refCode}`
Można by to zawęzić do linków z tej subdomeny z końcówką /ref/
Przykładowo
`auth.bitbay.net/ref/*`

**Comment by Quorce** [comment]
Hm... chyba nie tylko o reflinki chodziło https://github.com/MajkiIT/polish-ads-filter/issues/4877

**Comment by mellrebook** [comment]
Właśnie nie mogłem znaleźć jakiś konkretów.
Tamten issue jest powiązany z filmtu.pl, a że obie linijki "sąsiadują" to pewnie tylko dlatego się BB pojawił.

**Comment by MajkiIT** [comment]
@mellrebook @Quorce dzięki
