### ISSUE TITLE
applemobile.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#5144]
Masz włączoną blokadę reklam.

**Comment by MajkiIT** [comment]
Ja tego nie mam :(

**Comment by hawkeye116477** [comment]
@MajkiIT Może masz włączony Nano Defender. Z wyłączonym pojawia się popup.
![screenshot_20171219_111141](https://user-images.githubusercontent.com/19818572/34152084-a86d38ea-e4ad-11e7-986e-a7fb9ea91cef.png)
Niby tak to można zablokować `applemobile.pl###DtUFNpOuBnPa`, ale pytanie jest ile to podziała :smile:.
