### ISSUE TITLE
bezprawnik.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5146]
![2017-12-19 04_53_44-dlug uczelniany - sad najwyzszy zajal sie windykatorami](https://user-images.githubusercontent.com/5884000/34140098-b6506afc-e478-11e7-9015-59e222d0dbce.png)
`https://bezprawnik.pl/sad-najwyzszy-dlug-uczelniany/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.15
Nano Defender 13.3
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
@mat41997 u mnie jest ok.

**Comment by KonoromiHimaries** [comment]
@MajkiIT wyłącz dodatkowe filtry i spróbuj jeszcze raz.
