### ISSUE TITLE
likemag.com/pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#5150]
Hej kolega ma moja kopie listy filtrow u niego wyskakuje takie cudo a u mnie nie

https://prnt.sc/hpm7uj

Mozecie zerknac?

**Comment by KonoromiHimaries** [comment]
u mnie czysto

**Comment by xxcriticxx** [comment]
clean cache + cookies + dns flush

@gzenio22 jak dlugo twoj friend ma twoja liste? 5min czy 5 mies?

**Comment by gzenio22** [comment]
@xxcriticxx od wczoraj prawde mowiac bo to nie ten pajac co to sie boi wszystkiego a czemu pytasz to zle ze mu dalem swoia liste filtrow?

**Comment by xxcriticxx** [comment]
czysciles cookies i reszte?

**Comment by gzenio22** [comment]
wlaczone ma autoclean przy kazdym ponownym uruchomieniu opery

**Comment by xxcriticxx** [comment]
windows? zrob ipconfig /flushdns

**Comment by gzenio22** [comment]
ta winda ale glupek mnie kurde wyrolowal mial wylaczone filtry jak mi dawal screena :/ zamykam i przepraszam za zamieszanie
