### ISSUE TITLE
kobieceporady.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5152]
![2017-12-19 20_53_58-kobieceporady pl - portal kobiet](https://user-images.githubusercontent.com/5884000/34176055-d999736a-e4fe-11e7-9649-71bda830a85f.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by xxcriticxx** [comment]
co nato pingwin?
