### ISSUE TITLE
tygodnikponidzia.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5188]
![2017-12-20 06_14_41-tygodnik ponidzia oficjalny serwis informacyjny gazeta lokalna busko pinczow swi](https://user-images.githubusercontent.com/5884000/34192240-20a8f70a-e54d-11e7-9a4f-26e62f23826b.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
@KonoromiHimaries to wewnętrzne

**Comment by KonoromiHimaries** [comment]
@MajkiIT nie wszystko. nie powinieneś dyskryminować jednego ze względu na drugie.
