### ISSUE TITLE
www.nokiahacking.pl

### ISSUE THREAD

**Issue by pmoniewski** [MajkiIT/polish-ads-filter#519]
Witam, jestem administratorem niniejszego serwisu i od wczoraj zauważyłem, że został dodany wadliwy filtr, który, prócz rzeczywistej reklamy w topie, blokuje również cały widok strony głównej, tzn. wszystkie działy na forum, z całej strony pozostawiając jedynie nagłówek i stopkę: https://i.imgur.com/Uq1SULB.jpg

Chodzi o filtr `nokiahacking.pl##.forabg`, przy czym klasa `forabg` odpowiada właśnie za obramowanie wszystkich elementów na stronie głównej. Żeby rozróżnić elementy reklamowe od standardowych, dodałem właśnie w kodzie strony nową klasę `nh_ads`.

Prosiłbym więc o podmianę reguły na `nokiahacking.pl##.nh_ads` (jeśli jest to konieczne, bo dbam o to, by istniejące reklamy nie były inwazyjne), ale przede wszystkim o zdjęcie obecnego, całkowicie wadliwego filtru, który uniemożliwia internautom przeglądanie zasobów forum.

Pozdrawiam,
Paweł aka pawelooss

**Comment by MajkiIT** [comment]
Filtr podmieniony. Widziałem, że stosujesz też skrypt antyadblock. 
Zainteresuj się może tym https://www.startssl.com/ aby przepuścić chociaż logowanie przez https.
