### ISSUE TITLE
www.dakowski.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#52]
cookies

Nasza strona korzysta z plikow cookies w celu gromadzenia anonimowych statystyk, jesli nie blokujesz tych plikow, to zgadzasz sie na ich uzycie oraz zapisanie w pamieci urzadzenia. Mozesz samodzielnie zarzadzac plikami cookies w ustawieniach przegladarki.

**Comment by MajkiIT** [comment]
stały element
