### ISSUE TITLE
gorzowianin.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5200]
![2017-12-20 06_37_16-gorzowianin com - najprawdopodobniej najlepszy portal w miescie](https://user-images.githubusercontent.com/5884000/34192760-4d801b0c-e550-11e7-842c-38ecbf12ab14.png)

puste

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
Easylist
