### ISSUE TITLE
przewodnicywedkarscy.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5202]
![2017-12-20 06_42_41-wyprawy wedkarskie na ryby - jeziora rzeki szkiery i wedkarstwo morskie - prze](https://user-images.githubusercontent.com/5884000/34192904-12a041f0-e551-11e7-8042-af0d16d5d7f0.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`przewodnicywedkarscy.pl###sidebar > p`
