### ISSUE TITLE
gorydlaciebie.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5203]
![2017-12-20 06_44_37-gory dla ciebie _ najciekawsze wycieczki gorskie ferraty rowery narty - gotow](https://user-images.githubusercontent.com/5884000/34192943-556e0918-e551-11e7-9cb0-48c2feb09818.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`gorydlaciebie.pl##.widget_text.text-3.widget.row`
