### ISSUE TITLE
widzewtomy.net

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5204]
![2017-12-20 06_47_46-widzewtomy - oficjalny portal kibicow widzewa lodz](https://user-images.githubusercontent.com/5884000/34193023-cbf0a8ca-e551-11e7-8439-e87628b06863.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`widzewtomy.net##.widget_text`
