### ISSUE TITLE
wschodnik.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5205]
![2017-12-17 07_41_36-wschodnik _ portal informacyjny aktualnosci z ukrainy - wschodnik _ portal infor](https://user-images.githubusercontent.com/5884000/34077199-d9b17166-e2fd-11e7-9ea9-b508e0de6d14.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`/images/banners/$image,domain=wschodnik.pl`
