### ISSUE TITLE
lowiczanin.info

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5207]
![2017-12-20 06_56_02-lowiczanin - serwis lokalny](https://user-images.githubusercontent.com/5884000/34193247-f075dcfa-e552-11e7-9410-b740e25d633d.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
img blank
