### ISSUE TITLE
magazyngitarzysta.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5208]
![2017-12-20 06_59_25-strona glowna](https://user-images.githubusercontent.com/5884000/34193326-67ee337c-e553-11e7-8337-5f1c2b05504b.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`magazyngitarzysta.pl##.visible-lg.visible-md`
