### ISSUE TITLE
szkolasen.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5209]
![2017-12-20 07_01_24-polska szkola w dublinie](https://user-images.githubusercontent.com/5884000/34193374-a33ae7d6-e553-11e7-8f93-8fd8281229af.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
IMG _blank
