### ISSUE TITLE
wiadomosci.olsztyn.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5210]
![2017-12-20 07_03_03-wiadomosci olsztyn pl - wiadomosci informacje z olsztyna](https://user-images.githubusercontent.com/5884000/34193426-f751445a-e553-11e7-80bb-8cdd003f0a88.png)

brak obrazków

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
U mnie jest ok.
