### ISSUE TITLE
ogrodinfo.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5211]
![2017-12-15 22_14_08-portal ogrodniczy ogrodinfo pl sadownictwo ogrodnictwo portal sadowniczy](https://user-images.githubusercontent.com/5884000/34060749-5946e150-e1e5-11e7-8f2b-25c3363f862b.png)

puste

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by hawkeye116477** [comment]
@MajkiIT Tak chyba powinno być dobrze -> `www.ogrodinfo.pl###header:style(padding-top: 64px !important;)`.

**Comment by MajkiIT** [comment]
@hawkeye116477 dziękuję
