### ISSUE TITLE
naszamlawa.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5212]
![2017-12-20 07_08_00-nasza mlawa - informacyjny serwis lokalny - naszamlawa pl](https://user-images.githubusercontent.com/5884000/34193549-9d1c7332-e554-11e7-9de6-7309b1ee9118.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
Easylist
