### ISSUE TITLE
benchmark.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5213]
![2017-12-20 07_15_15-benchmark pl _ recenzje testy newsy rankingi](https://user-images.githubusercontent.com/5884000/34193755-a9733cc8-e555-11e7-8690-30aa1329c648.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
włącz Easylist
