### ISSUE TITLE
polacywewloszech.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5214]
![2017-12-20 07_20_22-polacy we wloszech - portal informacyjny _ polacy we wloszech portal informacy](https://user-images.githubusercontent.com/5884000/34193890-56e3cd96-e556-11e7-827f-03f87fd2aab7.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`||polacywewloszech.com/wp-content/uploads/20*/*/*reklama*.jpg`
