### ISSUE TITLE
tarnowiak.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5215]
![2017-12-20 07_22_09-tarnowiak pl _ ogloszenia tarnow _ kupie sprzedam praca nieruchomosci uslugi](https://user-images.githubusercontent.com/5884000/34193957-9e9ab230-e556-11e7-8a89-42e756d3fb0e.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`tarnowiak.pl/grafika/super_*/$image`
