### ISSUE TITLE
iknurow.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5216]
![2017-12-20 07_27_08-iknurow pl i knurow informacje z naszej okolicy na czasie o wszystkim o](https://user-images.githubusercontent.com/5884000/34194084-4baca078-e557-11e7-9a2f-cacd40c475ad.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`iknurow.pl###text-91`
