### ISSUE TITLE
sww.w.szu.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5217]
![2017-12-20 07_38_42-ii wojna swiatowa - najlepszy portal poswiecony historii](https://user-images.githubusercontent.com/5884000/34194456-231357fe-e559-11e7-9b4e-76c1559b2cc5.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`sww.w.szu.pl##.dodatki.row`
