### ISSUE TITLE
ligapolska.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5218]
![2017-12-20 07_47_17-ligapolska pl - ekstraklasa - puchar polski - puchar ekstraklasy - i liga](https://user-images.githubusercontent.com/5884000/34194674-1b955be8-e55a-11e7-96b5-b8ec53b0dfee.png)

puste

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
włącz Easylist
