### ISSUE TITLE
www.moje-filmy.tk

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#522]
http://www.moje-filmy.tk/film/transformers-wiek-zaglady-1

znowu hyba cos sie zmienilo 30 sec reklama przed filmem

**Comment by MajkiIT** [comment]
https://github.com/reek/anti-adblock-killer/issues/1010#issuecomment-199213078

**Comment by xxcriticxx** [comment]
jak zaczynamy sie bawic strona jest tylko otwarta dla zarejestrowanych uzytkownikow

**Comment by xxcriticxx** [comment]
reek/anti-adblock-killer Kill: moje-filmy.tk (ads)
