### ISSUE TITLE
ebelchatow.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5220]
![2017-12-20 07_57_13-sprzedawali luksusowa podrobiona bizuterie _ ebelchatow - portal informacyjny be](https://user-images.githubusercontent.com/5884000/34194939-71bd707c-e55b-11e7-88b5-8e2ffa84c0b1.png)
`http://www.ebelchatow.pl/content/sprzedawali-luksusow%C4%85-podrobion%C4%85-bi%C5%BCuteri%C4%99`

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`ebelchatow.pl###region-middle-poleca`
