### ISSUE TITLE
dziennikzwiazkowy.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5221]
![2017-12-20 07_59_42-dziennik zwiazkowy _ polish daily news informacje usa wiadomosci amerykanskie](https://user-images.githubusercontent.com/5884000/34195063-f84a6258-e55b-11e7-80fd-8c635d83dddc.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`dziennikzwiazkowy.com##.widget-28`
