### ISSUE TITLE
forum.haszysz.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5223]
![2017-12-20 08_06_19-forum haszysz com - dyskusje o uprawie konopi](https://user-images.githubusercontent.com/5884000/34195259-e21ee02a-e55c-11e7-99a1-fd6d52ec2520.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`||www.forum.haszysz.com/baner_$image
`
