### ISSUE TITLE
fresh-market.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5224]
![2017-12-20 08_09_06-austria popyt na cebule wciaz rosnie - fresh-market pl](https://user-images.githubusercontent.com/5884000/34195313-2484e126-e55d-11e7-92af-785b78b8b072.png)
`https://www.fresh-market.pl/owoce_i_warzywa/warzywa/cebula/austria_popyt_na_cebule_wciaz_rosnie,p131541792`

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
dodaj Easylist
