### ISSUE TITLE
goal.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5225]
![2017-12-20 08_11_43-pilka nozna euro 2016 reprezentacja polski ligi europejskie](https://user-images.githubusercontent.com/5884000/34195374-821b4e42-e55d-11e7-9708-d61102b4e2e9.png)

puste

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
dodaj Easylist
