### ISSUE TITLE
politykaglobalna.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5227]
![2017-12-20 08_26_15-politykaglobalna pl _ polityka bezpieczenstwo gospodarka i stosunki miedzynaro](https://user-images.githubusercontent.com/5884000/34195779-88b7970e-e55f-11e7-9c90-b7e4eaa48c17.png)

moje filtry
tylko polskie filtry

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
dodaj Easylist
