### ISSUE TITLE
polacywewloszech.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5236]
![2017-12-21 15_17_13-polacy we wloszech - portal informacyjny _ polacy we wloszech portal informacy](https://user-images.githubusercontent.com/5884000/34259339-30bee6e8-e662-11e7-8fd1-a77f9ce001e9.png)

moje filtry
polskie filtry + easylist

Nano Adblocker 1.0.0.15
Nano Defender 13.8
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`polacywewloszech.com###text-16, #text-17, #text-19`
