### ISSUE TITLE
forum.haszysz.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5238]
![2017-12-21 15_34_24-forum haszysz com - dyskusje o uprawie konopi](https://user-images.githubusercontent.com/5884000/34259963-7f1a2594-e664-11e7-8519-5884e1866dbd.png)

moje filtry
polskie filtry + easylist

Nano Adblocker 1.0.0.15
Nano Defender 13.8
Chrome 63.0.3239.108

**Comment by userOperaFF** [comment]
![obraz](https://user-images.githubusercontent.com/33114475/34322707-508d2330-e82f-11e7-9625-3704abf49d1e.png)


A wycinać zaczął cookiemonster po aktywacji lub raz się wyświetla i zamka komunikat (jak kiedyś onetowe).

---

reklamę ze stopki wycina `##table`, szablon forum na szczęście oparty nie o tabele, raczej tabel do odpowiedzi nie mogą dodawać więc od biedy mogłoby być.

`##font > table[width="900"]` , jak nie mogą zmieniać fontu w odpowiedzi  lub tabele mają tam inny rozmiar.

**Comment by MajkiIT** [comment]
IMG BLANK
