### ISSUE TITLE
jaw.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5240]
![2017-12-21 15_50_18-jaw pl - portal spolecznosciowy jaworzno](https://user-images.githubusercontent.com/5884000/34260584-bfb34c14-e666-11e7-8dc5-6f6d4ce45bbc.png)

moje filtry
polskie filtry + easylist

Nano Adblocker 1.0.0.15
Nano Defender 13.8
Chrome 63.0.3239.108

**Comment by userOperaFF** [comment]
`jaw.pl##.td-a-rec` z  easylist Polish.

Zostawili motylka.
