### ISSUE TITLE
podkarpackahistoria.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5249]
![2017-12-21 16_27_51-podkarpackahistoria pl](https://user-images.githubusercontent.com/5884000/34262190-ed584408-e66b-11e7-9d6a-1ce047fb1a19.png)

puste miejsce

moje filtry
polskie filtry + easylist

Nano Adblocker 1.0.0.15
Nano Defender 13.8
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
@hawkeye116477 zerkniesz?

**Comment by userOperaFF** [comment]
`###main-nav1:style(height: 100px !important)`

![obraz](https://user-images.githubusercontent.com/33114475/34279178-93c35f88-e6af-11e7-9561-e5fbb7327890.png)


błąd webmastera raczej z jakotakim sztywnym układem pod PC - na mniejszym ekranie czy telefonie to się rozjeżdża czy nawet reklama jest w tym samym divie co hamburger mobilnej nawigacji.

**Comment by hawkeye116477** [comment]
100 to trochę raczej za mało, tak powinno być ok -> `podkarpackahistoria.pl###main-nav1:style(height: 50px !important;)` 
Jeszcze po prawej zostały reklamy i resztki po nich -> `podkarpackahistoria.pl###widget_sp_image-9, #widget_sp_image-10, #widget_sp_image-14, #widget_sp_image-15, #widget_sp_image-16, #widget_sp_image-17, #widget_sp_image-22, #widget_sp_image-25, #widget_sp_image-27, #widget_sp_image-32, #widget_sp_image-33, #widget_sp_image-36`

**Comment by userOperaFF** [comment]
50px źle wygląda na mobilnym:

![obraz](https://user-images.githubusercontent.com/33114475/34307079-a7c00c1a-e746-11e7-8fe5-48f75fe714d4.png)

Jako tako poprawia to: `podkarpackahistoria.pl##.pad.group > .pad.group:style(clear: both !important)`

Ale wtedy odstęp praktycznie na PC wraca do ~100px:

grafiki |
---|
![obraz](https://user-images.githubusercontent.com/33114475/34307528-e05402f0-e748-11e7-93a9-c146d638cacd.png) |
![obraz](https://user-images.githubusercontent.com/33114475/34307547-f2dc2baa-e748-11e7-9411-01c28dadf368.png) |


Zauważam że jakiś coś co jakiś czas chyba odsłania środkowe reklamy z lotto,  i innymi firmami - ta reklama za 2 złote dziennie.

**Comment by userOperaFF** [comment]
50px źle wygląda na mobilnym:

![obraz](https://user-images.githubusercontent.com/33114475/34307079-a7c00c1a-e746-11e7-8fe5-48f75fe714d4.png) |
---|

Jako tako poprawia to:
```
podkarpackahistoria.pl##.pad.group > .pad.group:style(clear: both !important)
```

Ale wtedy odstęp praktycznie na PC wraca do ~100px:

grafiki |
---|
![obraz](https://user-images.githubusercontent.com/33114475/34307528-e05402f0-e748-11e7-93a9-c146d638cacd.png) |
![obraz](https://user-images.githubusercontent.com/33114475/34307547-f2dc2baa-e748-11e7-9411-01c28dadf368.png) |

może dla mobilnego trzeba by sprawdzić czy są jakieś proste reguły ograniczenia poza próbą wciśnięcia do reguły [Media Queries](https://www.w3schools.com/css/css3_mediaqueries_ex.asp).

---

Zauważam że jakiś coś co jakiś czas chyba odsłania środkowe reklamy z lotto,  i innymi firmami - ta reklama za 2 złote dziennie. Być może to jakiś błąd w Firefox 57 - bo muszę w nowej karcie otwierać stronę bo dodane filtry nie chcą działać nawet po odświeżaniu <kbd>Ctrl</kbd>+<kbd>R</kbd> / <kbd>Ctrl</kbd>+<kbd>F5</kbd>
