### ISSUE TITLE
portalgorski.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5250]
![2017-12-21 16_30_42- start - portal gorski - gory skaly wspinanie scianki wspinaczkowe - portalg](https://user-images.githubusercontent.com/5884000/34262345-71291262-e66c-11e7-8e08-d2099d68c6a0.png)

moje filtry
polskie filtry + easylist

Nano Adblocker 1.0.0.15
Nano Defender 13.8
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
wewnętrzne
