### ISSUE TITLE
mamywsieci.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5257]
![2017-12-21 18_02_23-mamywsieci pl _ warsztaty i atrakcje dla dzieci _ torun bydgoszcz](https://user-images.githubusercontent.com/5884000/34266385-2c5a7ac4-e679-11e7-9a70-ec5289c21637.png)

moje filtry
polskie filtry + easylist

Nano Adblocker 1.0.0.15
Nano Defender 13.8
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
A co  w tym złego?

**Comment by KonoromiHimaries** [comment]
w blokowaniu reklam? sam nie wiem
