### ISSUE TITLE
gosc.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5258]
![2017-12-21 19_00_53-may o uruchomieniu art 7 1_ kwestie konstytucyjne to wewnetrzna sprawa poszczego](https://user-images.githubusercontent.com/5884000/34268531-6077c840-e681-11e7-8c02-b120088e85d7.png)
`http://gosc.pl/doc/4391551.May-o-uruchomieniu-art-7-1-Kwestie-konstytucyjne-to-wewnetrzna`

puste miejsce

moje filtry
polskie filtry + easylist

Nano Adblocker 1.0.0.15
Nano Defender 13.8
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
@hawkeye116477 zerkniesz?

**Comment by hawkeye116477** [comment]
Chyba tak powinno być ok -> `gosc.pl##.webpart-wrap-HeaderMobile.has-promo:style(padding-top: 50px !important;)`

**Comment by MajkiIT** [comment]
@hawkeye116477 dziękuję
