### ISSUE TITLE
dlalejdis.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5259]
![2017-12-21 23_36_11-dlalejdis pl - portal dla kobiet](https://user-images.githubusercontent.com/5884000/34277866-dc949e6e-e6a7-11e7-9917-22b94b075356.png)

puste miejsce

moje filtry
polskie filtry + easylist

Nano Adblocker 1.0.0.17
Nano Defender 13.9
Chrome 63.0.3239.108

**Comment by userOperaFF** [comment]
Testowo działa:

`##.pageContent > div:nth-of-type(1) > div`
