### ISSUE TITLE
przebudzenie mocy easylist polska is back

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5268]
https://easylist-downloads.adblockplus.org/easylistpolish.txt

**Comment by KonoromiHimaries** [comment]
https://www.fanboy.co.nz/fanboy-polish.txt

**Comment by userOperaFF** [comment]
Fanboy: 

<h3>

```
! Updated: 19 Feb 2017

!!!!!!!!!!!!!!!! Officially unsupported !!!!!!!!!!!!!!
```

</h3>

**Comment by MajkiIT** [comment]
@xxcriticxx te filtry jakieś dziwne.

**Comment by xxcriticxx** [comment]
@MajkiIT jest nowy admin poprawia blendy niby

**Comment by xxcriticxx** [comment]
pozatym lista jest mala mozemy przerobic w pare dni

**Comment by xxcriticxx** [comment]
panowie mam prosbe bysmy sprawdzili liste z pierwszego postu i bendzie z glowy

**Comment by userOperaFF** [comment]
A ta lista jest dostępna już w Adblock Plus jako domyśla lub gdzieś na stronie easy list ponownie dodana do subskrypcji jak inne linkiem?

Filterslist.com raczej mnie nie interesuje, to bardziej dla "zaawansowanych".
