### ISSUE TITLE
funfashion.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5269]
![capture](https://user-images.githubusercontent.com/15007183/34319966-cb8fd442-e7bc-11e7-864c-ccc57201bbbc.PNG)

**Comment by userOperaFF** [comment]
Ramka po like na FB.

Widać masz jakiś filtr na wycinanie mediów społecznościowych.

![obraz](https://user-images.githubusercontent.com/33114475/34322184-48b1afe0-e821-11e7-8314-a8b8a3727d13.png)

reguła | opis
-|-
`funfashion.pl###ffbp-bg` | ciemne tło
`funfashion.pl###ffbp` | ramka z FB i ten krzyżyk

Można połączyć `funfashion.pl###ffbp-bg, #ffbp` jak to robi @hawkeye116477

**Comment by xxcriticxx** [comment]
@userOperaFF szybcej host file
