### ISSUE TITLE
em.kielce.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5271]
kielcach jest dominos ameriacan hot upgrade 

![capture](https://user-images.githubusercontent.com/15007183/34326156-435eb562-e874-11e7-9800-cc3860fb6824.PNG)

**Comment by hawkeye116477** [comment]
Pizza -> `em.kielce.pl##img[src="http://em.kielce.pl/bannery/pizza/300x250nie.jpg"]`
Społecznościowe -> `em.kielce.pl##.module_prawa:nth-of-type(4)`
