### ISSUE TITLE
kuchnia.wp.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#5274]
https://kuchnia.wp.pl/co-mysli-rodowity-wloch-o-polskiej-wigilii-marco-ghia-odpowiada-6201429472176257v
Strona się nie wczytuje z włączoną listą : POL: polskie filtry do Adblocka i uBlocka
![image](https://user-images.githubusercontent.com/29756590/34328722-e1e88402-e8e6-11e7-8622-8f5188b14786.png)
Screen z wyłączoną listą POL: polskie filtry do Adblocka i uBlocka
![image](https://user-images.githubusercontent.com/29756590/34328744-6d5e9be8-e8e7-11e7-9d4d-bf393a3c832b.png)

**Comment by xxcriticxx** [comment]
u mnie tak samo

@F4z help

**Comment by MajkiIT** [comment]
@xxcriticxx @HateAds już poprawiłem

**Comment by HateAds** [comment]
@MajkiIT Dzięki Majk, Teraz jest ok. Zamykam.
