### ISSUE TITLE
pocisk.org

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5275]
prawa strona 

mozesz wygrac nowy iphone7

**Comment by gzenio22** [comment]
ja tu widze tylko cos dla socjal

pocisk.org##.right-panel-social-box

**Comment by MajkiIT** [comment]
@xxcriticxx ja tego nie widzę. 
@hawkeye116477 zerkniesz?

**Comment by xxcriticxx** [comment]
dzisaj tego tez nie widze ale zucilem link do kad zeby zablokowal 

http://juicywin.pl/loader.php?partner=iph7_jw_pl_cn&pca=A&transaction_id=DglExC325yX4xklld4ExT8OMF2jAX9pyKVlL0u2r&aff_id=subid&sid=ek8tkg944j3i4ljsghc31h8ne5-4837&pl=1
