### ISSUE TITLE
Polska lista hosts

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#5279]
@xxcriticxx Jest robota dla ciebie, trzeba powiększyć Polską listę hosts, bo jest za mała. Proponuję pożyczyć coś od nich -> http://mobione.pl/adaway.txt lub http://someonewhocares.org/hosts/, ale może i też dodać coś brakującego od siebie :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 zamontuj sobie pihole na twego Linux mięta i sam się pobawisz

**Comment by xxcriticxx** [comment]
@hawkeye116477 zapraszam do wspolnej zabawy

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale ja nie mam Miętówki, mam (Kili)Manjaro Linux 😄 . A tak poza tym to ja już jestem zajęty trzema listami filtrów, może razem z @KonoromiHimaries się pobawicie, bo on tak najbardziej tego chciał i on zajmuje się tylko 2 listami 😄 .

**Comment by MajkiIT** [comment]
@hawkeye116477 wystarczy użyć tego skryptu `https://newspaint.wordpress.com/2014/08/18/filtering-easylist-for-hosts-file-style-adblock/` . Po przepuszczeniu polskich filtrów mamy coś takiego. 
[adblock2.txt](https://github.com/MajkiIT/polish-ads-filter/files/1587362/adblock2.txt)

**Comment by KonoromiHimaries** [comment]
Ja zaproponowałem to samo co majki up.

Poza tym w moich dwóch listach można znaleźć kilka pomniejszych list, np. prenumeraty, albo sklepy.

**Comment by xxcriticxx** [comment]
jest jeden fakt ze niema dobrej listy host moja dziala na 50-75%

**Comment by xxcriticxx** [comment]
@MajkiIT jakos za duzo tych hostow nie wyskoczylo

**Comment by MajkiIT** [comment]
No wiem, tylko tyle domen blokujemy w filtrach POL

**Comment by hawkeye116477** [comment]
Dzisiaj po prostu nie ma tak dużo polskich stron, na których można byłoby wyciąć reklamy tylko plikami hosts.

**Comment by xxcriticxx** [comment]
ja na pihole mam okolo 1.7 miliona hostow do blokuje tylko 25% trafiku reklamowego 

@MajkiIT juz to chyba kilka razy przerabialismy

**Comment by userOperaFF** [comment]
```
127.0.0.1	ad.polskiprzemysl.com.pl
127.0.0.1	ad.prv.pl
127.0.0.1	ajax.rutracker.org.pl
127.0.0.1	fntajkb.wp.pl
127.0.0.1	market.bia24.pl
127.0.0.1	owabgxis.wp.pl
127.0.0.1	pasaz.goryonline.com
```

z Przebudzonej mocą EasyList Polish.

**Comment by xxcriticxx** [comment]
Trzeba bendzie dodać

**Comment by MajkiIT** [comment]
@userOperaFF to `fntajkb.wp.pl` jest już dead.

**Comment by xxcriticxx** [comment]
blokowanie wp powoduje ad block

**Comment by userOperaFF** [comment]
Skrypt nie ma sprawdzania czy domena działa, widać admin nie odświeżył tej listy wystarczająco.

**Comment by MajkiIT** [comment]
@userOperaFF luz nie ma problemu.
