### ISSUE TITLE
otymsiemowi.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#5280]
Push do zdjecia na firefoxie

**Comment by MajkiIT** [comment]
@gzenio22 push nie są już filtrach POL . @hawkeye116477 je zabrał do siebie

**Comment by xxcriticxx** [comment]
shit no more push push

**Comment by MajkiIT** [comment]
dodaj sobie "https://github.com/azet12/PopupBlocker/blob/master/PPB.txt" tam to teraz jest

**Comment by xxcriticxx** [comment]
@gzenio22 fyi...

**Comment by hawkeye116477** [comment]
Ja je przygarnąłem, dlatego, że Fanboy i AdGuard również mają je w listach Annoyance i ja się z nimi zgadzam, w końcu są to powiadomienia dotyczące głównie promocji, zniżek, nowości, itd, a więc coś jak newslettery, które również główny filtr nie blokuje, a są w listach elementów irytujących :smile:.
