### ISSUE TITLE
medianarodowe.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5282]
![2017-12-26 19_30_27-abp glodz_ _polskich spraw nie rozstrzygnie ani ulica ani zagranica ani reka p](https://user-images.githubusercontent.com/5884000/34362475-355096be-ea74-11e7-8d87-7c4257c78296.png)
`https://medianarodowe.com/papiez-franciszek-prawdziwy-duch-bozego-narodzenia-radosc-tego-ze-bog-nas-kocha/`

elementy textowe

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.21
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`medianarodowe.com##center`
