### ISSUE TITLE
KALENDARZ 2018

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5287]
@MajkiIT kalendarze na 2018 powysylales ludziom bo ja swego jeszcze nie dostalem?

**Comment by MajkiIT** [comment]
hahahaha nie mam kalendarzy :p A chcesz?

**Comment by xxcriticxx** [comment]
od roku czekam na vpn, koszulki firmowe i kalendzrz

**Comment by KonoromiHimaries** [comment]
a ja na dwa kubki

**Comment by xxcriticxx** [comment]
i torbe swiezej kawy

**Comment by MajkiIT** [comment]
Nie mam funduszy aby sfinansować to. Próbowałem coś zrobić, ale nakład mnie przeraził. Na utrzymanie VPNów itp potrzeba kasy nikt nie chce tego finansować. Robienie tego na Cupsell mija się z celem, bo koszt koszulki to ok. 57 zł. Znalazłem firmę która może mi to zrobić za ok 15 zł ale nakład to ok 100 szt.

**Comment by MajkiIT** [comment]
@xxcriticxx jak ludzie wpłacą datki to weźmiemy to https://www.mydevil.net/vpn.html

**Comment by KonoromiHimaries** [comment]
@MajkiIT a masz jakiś programik do boostowania prędkości łącza kosztem wysokiego pingu?

**Comment by xxcriticxx** [comment]
@MajkiIT zalatw te koszulki lepjej ja bez vpn przezyje
