### ISSUE TITLE
prawicowyinternet.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5290]
![2017-12-27 08_02_54-ponad 30 osob zasiadzie na lawie oskarzonych za wyludzenie dziesiatek milionow z](https://user-images.githubusercontent.com/5884000/34373609-77785a82-eadc-11e7-8d4c-86b432173acf.png)
`http://prawicowyinternet.pl/ponad-30-osob-zasiadzie-na-lawie-oskarzonych-za-wyludzenie-dziesiatek-milionow-zlotych-ze-skok-w-wolominie/`

sekcja reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.21
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`prawicowyinternet.pl##.widget_text.widget.td_block_template_1:nth-of-type(4)`
