### ISSUE TITLE
zdrowyportal.org

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5291]
![2017-12-27 08_33_07-czeremcha zwyczajna pomoc w leczeniu](https://user-images.githubusercontent.com/5884000/34374275-979bcbce-eae0-11e7-9e74-4909f66ebbf5.png)
`http://www.zdrowyportal.org/5103/czeremcha-zwyczajna-pomoc-leczeniu/`

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.21
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`zdrowyportal.org###text-10`
