### ISSUE TITLE
em.kielce.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5293]
![34326156-435eb562-e874-11e7-9800-cc3860fb6824](https://user-images.githubusercontent.com/5884000/34374771-24cf2c00-eae3-11e7-9998-38951922cc42.PNG)

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.21
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`/bannery/$image,domain=em.kielce.pl`
