### ISSUE TITLE
businesswomanlife.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5294]
![2017-12-27 08_56_05-businesswoman life _ z pasji do sukcesu](https://user-images.githubusercontent.com/5884000/34374905-ed33f6d0-eae3-11e7-83ba-98d809fb66c0.png)

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.21
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`businesswomanlife.pl##[class*="sidebar-cat-box-"]`
