### ISSUE TITLE
bielenda.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#530]
fix cookies

1. Strona internetowa http://bielenda.pl, używa plików cookie. Informacja o plikach cookie jest dostępna na stronie: Pliki cookies. 2. Użytkownik ma możliwość korzystania ze strony internetowej http://bielenda.pl bez wykorzystywania mechanizmu cookies, ale może to oznaczać, że niektóre funkcje lub usługi zawarte na stronie internetowej, nie będą działać poprawnie

**Comment by MajkiIT** [comment]
Blokowane już przez filtry.
