### ISSUE TITLE
konto real debrid

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5302]
@gzenio22 bys kupil dla mnie konto please?

**Comment by gzenio22** [comment]
Musial bys kupic PSC gdzies i wtedy kupic ja tylko tak kupowalem a cos sie stalo?

**Comment by KonoromiHimaries** [comment]
przecież jest wiele innych darmowych hostingów, nie rozumiem czemu chcesz korzystać akurat z tego.

**Comment by gzenio22** [comment]
@KonoromiHimaries a widziales jakosc tych DARMOWYCH hostingow? Xddd

**Comment by KonoromiHimaries** [comment]
tak i nie mam z nimi problemów.

**Comment by xxcriticxx** [comment]
ja z openload i z mega wyciagam okolo 10-15 mb per sec

rapidgator byl tez dobry 

w plandzie to wszystko tanjej kosztuje @gzenio22 kase podesle paypalem

**Comment by gzenio22** [comment]
@xxcriticxx Kup PSC na alledrogo i doladuj z PSC alledrogo powinno akceptowac PayPala

**Comment by xxcriticxx** [comment]
@gzenio22 problem jest ze przelicznik jest ostry i drozej wyjdzie

**Comment by xxcriticxx** [comment]
@gzenio22 podaj jakiegos linka

**Comment by gzenio22** [comment]
a u siebie w kiesku nie masz PSC czy cos? Xd

**Comment by xxcriticxx** [comment]
w nyc tego w kiosku nie ma

**Comment by gzenio22** [comment]
ja z kolei nie mam jak kupic musial bym mame prosic Xd

**Comment by xxcriticxx** [comment]
podaj mi linka do psc na alegro/ebay

moze nam @MajkiIT fundnje na choinke

**Comment by xxcriticxx** [comment]
@KonoromiHimaries od ciebie konto do rapidgator prosze

**Comment by KonoromiHimaries** [comment]
@xxcriticxx taki scam? absolutnie!
![2017-12-28 20_48_39-rapidgator net_ szybkie i bezpieczne przechowywanie plikow](https://user-images.githubusercontent.com/5884000/34421597-8b15f966-ec10-11e7-8470-10b9ee65b4ab.png)

**Comment by xxcriticxx** [comment]
@KonoromiHimaries 

https://rapidgator.net/article/premium

**Comment by KonoromiHimaries** [comment]
@xxcriticxx drogo

**Comment by xxcriticxx** [comment]
@KonoromiHimaries sure ze tak ale ciagne z tego 10-15 mb na secunde

**Comment by gzenio22** [comment]
jaki nominal? :P

**Comment by xxcriticxx** [comment]
what happen sie stalo?

**Comment by gzenio22** [comment]
Pytam jaka wartosc PSC potrzebujesz na allegro?

**Comment by xxcriticxx** [comment]
@gzenio22 a tak po naszemu? ile rekomendujesz?

**Comment by gzenio22** [comment]
nie wiem Xd na allegro i tak trzeba doplacac zeby sprzedawca cos z tego mial Xd

**Comment by gzenio22** [comment]
poza tym z tego co widze paypalem tez idzie zaplacic

**Comment by xxcriticxx** [comment]
@gzenio22 link please

**Comment by gzenio22** [comment]
http://allegro.pl/paysafecard-50-zl-automat-24-7-psc-w-2-minuty-i6922177198.html?bi_s=ads&bi_m=listing%3Adesktop%3Aquery&bi_c=OGQ1NjUwZDItMzI3My00N2VjLWFhOWYtOGMxY2QyOWNhNjE1AA&bi_t=ape&referrer=proxy&emission_unit_id=c13292a6-3f03-48b6-be9f-93d774ce7b6e

 5 dych

**Comment by xxcriticxx** [comment]
@gzenio22 a teraz link do real d kupna please

**Comment by gzenio22** [comment]
https://real-debrid.com/premium

**Comment by gzenio22** [comment]
@xxcriticxx Dales rade?

**Comment by xxcriticxx** [comment]
nope

**Comment by gzenio22** [comment]
Pod lista opcji do wyboru masz sprzedawcy wybierz swój kraj powinieneś mieć możliwość zapłaty PayPalem

**Comment by xxcriticxx** [comment]
ostatnio nie bylo jakos czasu mialem awarie servera i inne glupoty

na piatek mam ciagnecie kabla cat 6 shield ostatnio jakos nie bylo czasu

**Comment by xxcriticxx** [comment]
nie widze tam paypal

![capture](https://user-images.githubusercontent.com/15007183/34542236-c1efe486-f0a9-11e7-918c-e76634ee204c.PNG)
