### ISSUE TITLE
poznan.naszemiasto.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5303]
![2017-12-28 20_03_28-poznan - naszemiasto pl](https://user-images.githubusercontent.com/5884000/34420522-57bde8ea-ec0a-11e7-9119-58e32239542b.png)

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.21
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`poznan.naszemiasto.pl##.sekcjaWaska:nth-of-type(1)`
