### ISSUE TITLE
prawapolityka.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5309]
![2017-12-29 08_08_07-prawapolityka pl - zycie to polityka](https://user-images.githubusercontent.com/5884000/34431452-90326cd6-ec6f-11e7-96a2-537d5052a360.png)

sekcja reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.21
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`prawapolityka.pl###text-8`
