### ISSUE TITLE
appki.com.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5312]
![2017-12-29 11_44_16-appki com pl - aplikacje i gry mobilne](https://user-images.githubusercontent.com/5884000/34435413-c8c83bac-ec8d-11e7-892c-bbf1129047c1.png)

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.21
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`appki.com.pl###text-8`
