### ISSUE TITLE
NSFW cichodaje.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#5319]
Data Zone

nie zeby mnie interesowalo :D

**Comment by MajkiIT** [comment]
@gzenio22 nie, no spoko. Nie wrzuciłeś screenu to ok. Po prostu kolega, kolegi Ci powiedział :D

**Comment by xxcriticxx** [comment]
@gzenio22 nie widze DATE ZONE na main bedziesz musial podaj swoj tajny link

**Comment by gzenio22** [comment]
tffu blad w linku

**Comment by xxcriticxx** [comment]
host file mi ta strone zjada

**Comment by MajkiIT** [comment]
https://github.com/azet12/KAD/issues/540
