### ISSUE TITLE
version of filters 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#532]
1. nie lepjej bylo zmienic ver wszyskich filtrow na ten styl? Version: 2016031901

**Comment by MajkiIT** [comment]
w filtrach reklam ciągle mogą wystąpić zmiany w ciągu dnia. W innych filtrach tego nie ma, ale może masz racje.

**Comment by xxcriticxx** [comment]
ale poprawki moga byc tez od czasu do czasu 

pytaniej 2 czy by mialo sens zrobic jeden duzy filtry zamiast 3 odzielnych

**Comment by MajkiIT** [comment]
ad 1 Ok poprawię to :+1: 

ad 2 nie, bo nie każdy chce używać wszystkiego ...
