### ISSUE TITLE
endurorider.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5321]
![2017-12-30 11_56_31-strona glowna - endurorider pl](https://user-images.githubusercontent.com/5884000/34453601-a850dd36-ed58-11e7-8cf0-53662c17ea63.png)

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
img blank
