### ISSUE TITLE
toyotaklub.org.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5324]
![2017-12-30 12_23_36-toyota klub o toyotach wiemy prawie wszystko](https://user-images.githubusercontent.com/5884000/34453754-5d8bc6d6-ed5c-11e7-902e-8cede0c396c5.png)

sekcja reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`toyotaklub.org.pl###text-6`
