### ISSUE TITLE
wavepc.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5325]
![2017-12-30 12_38_13-wavepc _ twoje miejsce w swiecie it](https://user-images.githubusercontent.com/5884000/34453885-ae920eee-ed5e-11e7-8791-3d2653d4be63.png)

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`wavepc.pl##.wavep-widget`
