### ISSUE TITLE
kresy.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5326]
![2017-12-30 12_54_50-new york times poparl uzycie wobec polski artykulu 7 kresy](https://user-images.githubusercontent.com/5884000/34453974-b352de84-ed60-11e7-984e-2294db18e836.png)
`https://kresy.pl/wydarzenia/regiony/ameryka/new-york-times-poparl-uzycie-wobec-polski-artykulu-7/`

sekcja reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`kresy.pl##.widgetAfterContent`
