### ISSUE TITLE
optyczne.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5328]
![2017-12-30 13_12_09-optyczne pl - testy aparatow testy obiektywow testy lornetek inne testy apar](https://user-images.githubusercontent.com/5884000/34454076-2600febe-ed63-11e7-87d0-4ba8e34e1460.png)

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`optyczne.pl##.sidebar-left.main-content-right`
