### ISSUE TITLE
kawiarniany.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5329]
![2017-12-30 13_41_19-kawiarniany pl - kawiarnie w krakowie kawiarnie we lwowie restauracje zwiedz](https://user-images.githubusercontent.com/5884000/34454224-26b8a362-ed67-11e7-84ad-ab97c4cdf721.png)

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
img blank
