### ISSUE TITLE
businesstraveller.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5338]
![2017-12-30 16_53_10-podroze sluzbowe hotele spa restauracje _ businesstraveller pl](https://user-images.githubusercontent.com/5884000/34455588-3c7db3f2-ed82-11e7-8262-a44d7e3ebdd3.png)

sekcja fb + reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by hawkeye116477** [comment]
Po kliknięciu na zdjęcie, otwiera się jakieś dziadostwo.
http://businesstraveller.pl/wiadomosci/swiat-wiadomosci/zeby-leciec-trzeba-siedziec-przewodnik-kabinach-air-france-klm

**Comment by MajkiIT** [comment]
@hawkeye116477 dzięki zrobię tak ...` /wp-content/plugins/wp-words-links-change/j$script`
