### ISSUE TITLE
tabelka na froncie repo

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5342]
@MajkiIT @hawkeye116477 

nie da rady zmienic linki z `raw` na `adp://` by automatycznie dodawalo do blockera?

**Comment by MajkiIT** [comment]
Niestety github tego nie przewiduje.

**Comment by xxcriticxx** [comment]
jak dodasz `abp://subscribe/?location=` nie bendzie dzialac?

**Comment by hawkeye116477** [comment]
@xxcriticxx Sprawdź czy działa -> https://hawkeye116477.github.io/test/ :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 ty masz `abp:subscribe?location=` a powino byc `abp://subscribe/?location=`

**Comment by hawkeye116477** [comment]
@xxcriticxx Ok, zmieniłem jeden link i nadal coś niestety nie działa.

**Comment by KonoromiHimaries** [comment]
spróbuj tu w czat to wkleić tak żeby działało.

**Comment by xxcriticxx** [comment]
@hawkeye116477 masz tak `subscribe?` a powino byc tak `subscribe/?`

**Comment by hawkeye116477** [comment]
@xxcriticxx Ok, zmieniłem i nadal nie działa, a w README to wcale nie wyświetla się to jako link. Pierwsza wersja chyba też zresztą powinna być dobra, przecież tak jest na https://filterlists.com/ i na certyficate.it/adblock. Generator tak samo generuje https://adblockplus.org/abp_linkfactory .

**Comment by xxcriticxx** [comment]
czyli tak jak @MajkiIT pisal nie bendzie dzialc na githubie

**Comment by userOperaFF** [comment]
No długo nie będzie, musi starczyć uruchomiona strona githubowa pod starym adresem [/adblock/](https://www.certyficate.it/adblock/ "www.certyficate.it/adblock/").

**Comment by userOperaFF** [comment]
@hawkeye116477  na testowej githubowej stronie nie działa bo musi być link. A masz:

```html
<a>
    <span>
         <span>
            Subskrybuj
        </span>
   </span>
</a>
```

A jako opis pod plikami źródłowymi to jak wyżej, nie przewidują.

**Comment by KonoromiHimaries** [comment]
co do wywoływania subskrybuj na readme.md, to można zrobić przekierowanie za pomocą subdomeny(
