### ISSUE TITLE
stolicazdrowia.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5343]
![2017-12-30 20_02_07-stolica zdrowia - portal o zdrowiu medycyna naturalna chodoby leczenie](https://user-images.githubusercontent.com/5884000/34456663-796e494c-ed9c-11e7-972d-39af047115b5.png)

sekcja fb

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by hawkeye116477** [comment]
A to draństwo, najwyraźniej na głównej dali podobny element co na podstronach, ale z inną klasą, a ja go przeoczyłem.
