### ISSUE TITLE
ikamien.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5345]
![2017-12-30 22_57_34-powiat kamienski - ikamien pl kamien pomorski dziwnow wolin miedzyzdroje g](https://user-images.githubusercontent.com/5884000/34457570-e456413e-edb4-11e7-8ff2-e7d4afd87423.png)

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
ikamien.pl###ads
ikamien.pl##.adsSpecial
```
