### ISSUE TITLE
groupon.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#5346]
Czy podczas ładowania ofert na na grouponie zużycie pamięci też u Was tak wzrasta. U mnie na jednej zakładce potrafi dość do ponad 2GB?

Na przyklad : https://www.groupon.pl/deals/dream-car-sp-z-o-o-4

![image](https://user-images.githubusercontent.com/11385099/34460046-3c965386-ee03-11e7-889e-55433be08d65.png)

po załadowaniu wraca do normalnego poziomu. Ogólnie ofery długo się ładują.

Powoduje to chyba ta reguła:

![image](https://user-images.githubusercontent.com/11385099/34460075-28031b88-ee04-11e7-83fc-cea116b45e10.png)

**Comment by MajkiIT** [comment]
@mathew85 u mnie wzrasta o ok 200MB więcej, ale u mnie to tak nie leci ciurkiem... 2 requesty i koniec

**Comment by mathew85** [comment]
U mnie leci do 150-200 requestow.

**Comment by MajkiIT** [comment]
@mathew85 dziwne
@hawkeye116477 zerkniesz u siebie?

**Comment by xxcriticxx** [comment]
@MajkiIT u mnie jest ok 9 polonczen zakladka ma 117mb

**Comment by hawkeye116477** [comment]
U mnie na Vivaldim na Manjaro karta ma 140 mb, po czym szybko spada do ok. 100 mb.

**Comment by mathew85** [comment]
Hmm. Zainstalowalem sobie Chroma i Firefoxa w wersji portable. W nich jest OK. Widocznie coś jest nie tak z moją instalką przeglądarki.
