### ISSUE TITLE
twojeip.wp.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5348]
![2017-12-31 13_56_44-twoje ip - jakie jest moje ip i szybkosc lacza_ - wp pl](https://user-images.githubusercontent.com/5884000/34461727-b34bbeb0-ee32-11e7-9ca2-953bdb3ef2cc.png)

adblock detect

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`@@||twojeip.wp.pl/js/ads.js$script,xmlhttprequest,domain=twojeip.wp.pl`

ale to chyba niczemu nie przeszkadza, że wykrywa?
