### ISSUE TITLE
Happy New Year!

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5358]
miejsce na zyczenia noworoczne

**Comment by MajkiIT** [comment]
@ALL 
Happy New Year!

**Comment by xxcriticxx** [comment]
@ALL +1 more Happy New Year!

**Comment by KonoromiHimaries** [comment]
@ALL
Życzę wam wszystkim by w tym roku nic się nie zmieniło, byście nie musieli pracować jeszcze ciężej by utrzymać rodzinę i nakarmić chorę od wciąż zatrutego powietrza dzieci.
Życzę wam wszystkim żeby ten rok podatkowy był tak samo dobry jak ten poprzedni, by partia rządząca nie wprowadziła żadnej `dobrej` zmiany i by żaden polityk nie został już zamordowany.
Życzę wam wszystkim żebyście zdołali przeżyć chociaż do 40stki, bez chronicznych chorób wywołanych przez experymentalne jedzenie i leki.

Happy New Year!

**Comment by hawkeye116477** [comment]
@all Szczęśliwego Nowego Roku 2018!
