### ISSUE TITLE
cda.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5362]
![2018-01-01 12_40_39-14 ostrzy 2010 lektor pl 720p - wideo w cda pl](https://user-images.githubusercontent.com/5884000/34467406-12f2a11c-eef1-11e7-8d2d-102667a599ff.png)
`https://www.cda.pl/video/54620539/vfilm`

reklama w playerze

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by xxcriticxx** [comment]
To wideo jest niedostępne w Twoim kraju
