### ISSUE TITLE
blogomaniak.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5367]
takie cos na dole wycinamy?
![capture](https://user-images.githubusercontent.com/15007183/34468364-286873f8-eed5-11e7-9c3f-952b961bcecb.PNG)

https://www.blogomaniak.pl/1318/konkursy-fotograficzne-facebooku-dzik-spoko/

**Comment by MajkiIT** [comment]
`blogomaniak.pl##.anal-post-popularne`
