### ISSUE TITLE
majkrafci.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5370]
![2018-01-01 15_55_09-majkrafci pl](https://user-images.githubusercontent.com/5884000/34468579-3e47360a-ef0c-11e7-873a-4f5eef0bd1c8.png)

brak sekcji fb

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
@hawkeye116477 zerkniesz?

**Comment by hawkeye116477** [comment]
A to nie powinno być blokowane? Przecież to jest widget social.

**Comment by KonoromiHimaries** [comment]
@MajkiIT ale jest to główna treść strony. dodawanie tego typu rzeczy do listy byłoby sprzeczne z naszymi zasadami.
