### ISSUE TITLE
dsw.doba.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5378]
![2018-01-01 18_25_12-doba pl dobrze poinformowani](https://user-images.githubusercontent.com/5884000/34469525-32c04adc-ef21-11e7-889b-67106be678ae.png)

pusta sekcja

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
dsw.doba.pl##.sliderads
