### ISSUE TITLE
tygodnikzamojski.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5379]
![2018-01-01 18_29_42-tygodnik zamojski - tygodnik zamojski zamosc bilgoraj tomaszow](https://user-images.githubusercontent.com/5884000/34469554-dbf6e2a0-ef21-11e7-9ae4-c36d7d31648b.png)

reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
/banner/*$image,domain=tygodnikzamojski.pl
