### ISSUE TITLE
petronews.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5383]
![2018-01-01 19_56_13-mieszkancy walcza o zabytek przyrody mozna podpisywac petycje](https://user-images.githubusercontent.com/5884000/34470252-fde96502-ef2d-11e7-9194-36b4bd202a7a.png)
`http://petronews.pl/mieszkancy-walcza-o-zabytek-przyrody-mozna-podpisywac-petycje/`

reklama + sekcja reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
petronews.pl###text-22 do ogólnych ale reszta wewnętrzne.

**Comment by KonoromiHimaries** [comment]
@MajkiIT sekcja reklama pozostała na podanym linku
