### ISSUE TITLE
polskieradio.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5384]
![2018-01-01 20_12_13-polskieradio com - oficjalna strona radia 104 7fm 1030am 1300am 107 1fm chicago](https://user-images.githubusercontent.com/5884000/34470457-541d0e94-ef31-11e7-865d-8ab7df51ae88.png)

![2018-01-01 20_11_47-polskieradio com - oficjalna strona radia 104 7fm 1030am 1300am 107 1fm chicago](https://user-images.githubusercontent.com/5884000/34470458-58cae448-ef31-11e7-8832-b2c7525f0783.png)

sekcja reklama + sekcja fb

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
polskieradio.com##.post-widget.widget:nth-of-type(2)
polskieradio.com##.categories-widget
polskieradio.com##.col-md-4:nth-of-type(2)
```
