### ISSUE TITLE
alefunny.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#5385]
Adblock detect 

Nano adblocker 1.0.0.22
Nano defender
Lista filtrow: https://gist.github.com/gzenio22/d658f7e8f89fb5225fbd0d603fa5c048

![screenshot_1](https://user-images.githubusercontent.com/21177361/34471185-8e2a7700-ef42-11e7-9c40-cc698ec71ad0.png)

Rozwiązanie
alefunny.pl###myModal
alefunny.pl##.in.fade.modal-backdrop
trzeba jeszcze zdjac blokade scrolla tego nie umiem
Sprawdźcie

@hawkeye116477 dla ciebie :D 

alefunny.pl###like-box

**Comment by hawkeye116477** [comment]
```
alefunny.pl###myModal, .modal-backdrop
alefunny.pl##.modal-open:style(overflow: auto !important; padding-right: 0px !important;)
```

**Comment by gzenio22** [comment]
@hawkeye116477 Działa można dodać twoje regułki i ładnie zamknąć :D

**Comment by hawkeye116477** [comment]
Jasne, tylko trzeba je dodać do uzupełnienia dla uBlocka i AG. Ja bym w ogóle połączył te 2 listy i zaczął używać `!+ PLATFORM`, ale to już chyba najlepiej zrobić jak w AG dodadzą `#include`, bo trochę bez sensu by dodawać tu i tu to samo, skoro mogłoby być to na jednej liście, bo sporo wspólnych reguł uBlocka i AG jest.
