### ISSUE TITLE
e-play.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5388]
![2018-01-02 00_39_46-e-play pl portal branzy hazardowej](https://user-images.githubusercontent.com/5884000/34471922-8e798346-ef55-11e7-8606-e183b509b192.png)

reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by xxcriticxx** [comment]
duplikat #5368

**Comment by xxcriticxx** [comment]
@KonoromiHimaries filtry nowe ściągnie

**Comment by userOperaFF** [comment]
@KonoromiHimaries  też powinieneś mieć opcje zamknięcia  :1st_place_medal:

**Comment by KonoromiHimaries** [comment]
@userOperaFF wolałbym mieć do tego bota.
