### ISSUE TITLE
polskieradio.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5391]
![2018-01-01 20_12_13-polskieradio com - oficjalna strona radia 104 7fm 1030am 1300am 107 1fm chicago](https://user-images.githubusercontent.com/5884000/34470457-541d0e94-ef31-11e7-865d-8ab7df51ae88.png)

![2018-01-02 01_00_59-polskieradio com - zwyciestwo kamila stocha w garmisch-partenkirchen](https://user-images.githubusercontent.com/5884000/34472052-6ee49cde-ef58-11e7-9f34-fea429d4bab1.png)
`http://www.polskieradio.com/news_det.aspx?id=115668&kat=64`

sekcja reklama + sekcja fb

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
polskieradio.com##.post-widget.widget:nth-of-type(1)
polskieradio.com##.right-post > .title-section
```

**Comment by hawkeye116477** [comment]
@MajkiIT Filtry social dodane, więc można raczej zamknąć.
