### ISSUE TITLE
regionfan.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5396]
![2018-01-02 09_54_04-regionfan pl](https://user-images.githubusercontent.com/5884000/34478776-0de2094e-efa3-11e7-890f-3ef99b6d459a.png)

reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`regionfan.pl###dyzur`
