### ISSUE TITLE
slupca.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5399]
![2018-01-02 10_03_24-slupca - portal powiatu slupeckiego aktualnosci ogloszenia](https://user-images.githubusercontent.com/5884000/34478984-4bfce1ee-efa4-11e7-8464-bc52770d2119.png)

reklama + sekcja reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
slupca.pl###text-9
slupca.pl##.a-76.g-single > div
slupca.pl###text-7
```
