### ISSUE TITLE
magazynfakty.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5400]
![2018-01-02 10_07_01-polska gospodarka - fakty - magazyn gospodarczy](https://user-images.githubusercontent.com/5884000/34479093-ea4cfdb6-efa4-11e7-84b8-222e02dc695f.png)

sekcja najnowsze wydanie +  sekcja partnerzy

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by hawkeye116477** [comment]
Najnowsze wydanie to trzeba raczej odblokować.
