### ISSUE TITLE
belchatow.bai.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5401]
![2018-01-02 10_11_48-belchatow - portal informacyjny aktualnosci i informacje lokalne z miasta i pow](https://user-images.githubusercontent.com/5884000/34479181-708fdd6c-efa5-11e7-9cbc-0c16463011e9.png)

sekcja reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`belchatow.bai.pl##.rekls`
