### ISSUE TITLE
radio.kielce.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5402]
![2018-01-02 10_14_34-radio kielce](https://user-images.githubusercontent.com/5884000/34479248-de9e4410-efa5-11e7-81a3-ccb247d31399.png)

reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
/adv/$image,domain=www.radio.kielce.pl
