### ISSUE TITLE
extra.info.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5404]
![2018-01-02 10_21_24-extra - w jaworznie jest extra](https://user-images.githubusercontent.com/5884000/34479388-c3aa0a76-efa6-11e7-819c-4b590093d2d0.png)

reklama + sekcja reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
extra.info.pl###leader-wrap
extra.info.pl###text-38
```
