### ISSUE TITLE
dyskoteka.co

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5406]
![2018-01-02 10_28_41-www dyskoteka co](https://user-images.githubusercontent.com/5884000/34479546-c6aed962-efa7-11e7-9dc7-76fdc7f81e54.png)

niebieska reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`dyskoteka.co##.block_min`
