### ISSUE TITLE
sokolka.tv

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5408]
![2018-01-02 10_34_16-wydarzenia](https://user-images.githubusercontent.com/5884000/34479690-88b7eda0-efa8-11e7-9936-d3d253369b52.png)

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
sokolka.tv###jm-top1
sokolka.tv## .hidden-phone.white-ms.jm-module
sokolka.tv###jm-content-top
```
