### ISSUE TITLE
wrc.net.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5412]
![2018-01-02 11_20_07-druga polowa](https://user-images.githubusercontent.com/5884000/34480828-f3729c98-efae-11e7-96ba-3f627cd235bb.png)
`http://wrc.net.pl/druga-polowa`

szara sekcja

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
wrc.net.pl##.g
wrc.net.pl##.sidebar.col-sm-4.col-xs-12
```
