### ISSUE TITLE
swiatoze.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5413]
![2018-01-02 11_21_47-swiatoze pl - odnawialne zrodla energii](https://user-images.githubusercontent.com/5884000/34480876-3ac70732-efaf-11e7-8082-d380c2781dd0.png)

reklama + sekcja fb + widget polub nas

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`swiatoze.pl###text-10`
