### ISSUE TITLE
plusforum.pl

### ISSUE THREAD

**Issue by userOperaFF** [MajkiIT/polish-ads-filter#5414]
![image](https://user-images.githubusercontent.com/33114475/34482115-58ad3d46-efb6-11e7-8240-60ade2a02354.png)

http://plusforum.pl/viewtopic.php?f=99&t=18239&start=30

Element po reklamie w każdym 1. poście danej strony wątku.

---

Proponowany filtr uBlock (`plusforum.pl##p > .adsbygoogle`) się nie sprawdza, bo taki układ występuje przed wykryciem blokerów (nie wykrywają disconnect - stąd puste pole), po wykryciu blokera coś usuwa ten układ (serwer / skrypt po stronie klienta).

### Testowo gdy wykryją bloker reklam:

- `plusforum.pl##.content > p`
- `plusforum.pl##.content > p[style="float: left; width: 300px; height: 250px; margin-right: 4px;"]`

**Comment by MajkiIT** [comment]
`plusforum.pl##.content > p`

@userOperaFF Dziękuję
