### ISSUE TITLE
greencanoe.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5435]
![2018-01-03 11_31_44-smog - jak sobie z nim radzic w domach_ - green canoe](https://user-images.githubusercontent.com/5884000/34517045-ba4d5e1e-f079-11e7-8523-6a4d02813d02.png)
`http://greencanoe.pl/smog-nim-radzic-domach/`

sekcja reklama + sekcja fb

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
@KonoromiHimaries jak możesz to wystarczy mi na dzisiaj.
