### ISSUE TITLE
www.komputerswiat.pl

### ISSUE THREAD

**Issue by crazyjack79** [MajkiIT/polish-ads-filter#5442]
### Zrzut ekranu
![komputerswiat](https://user-images.githubusercontent.com/35058050/34524232-061cd330-f09b-11e7-888f-8fcf114a3b6f.jpg)

-->

### Link bezpośredni

http://www.komputerswiat.pl/
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. wejść na stronę http://www.komputerswiat.pl/
2. przekierowanie z onetu
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**
Slimjet
**Rozszerzenia i skrypty:**
Ublock Origin
**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. 
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by KonoromiHimaries** [comment]
na szybko mogę polecić dodatek do ublocka, nano defender
`https://jspenguin2017.github.io/uBlockProtector/`

**Comment by userOperaFF** [comment]
Na operze zablokowało z nano defenderem i chyba da się przeglądać tereść a nie jakieś fake w stylu:

![image](https://user-images.githubusercontent.com/33114475/34524563-420fe836-f09c-11e7-8e44-5b1ae5622f7f.png)

**Comment by hawkeye116477** [comment]
Zgłoszone do specjalistów https://github.com/uBlockOrigin/uAssets/issues/1157 :smile:.

**Comment by userOperaFF** [comment]
W sumie mam drugi profil i tam ani uBlock, ani Nano Adblocker nie umieją zablokować, była nadzieja że po subskrypcji cookiemonster jakimś cudem zniknie ale po odświeżeniu wskoczyło a cookies zniknęło.

**Comment by F4z** [comment]
To pewnie taka sama sytuacja jak tutaj - https://github.com/MajkiIT/polish-ads-filter/issues/5426
Powinno wystarczyć:
`komputerswiat.pl#@#.adsense`

**Comment by F4z** [comment]
Taki sam problem jest na vod.pl i innych stronach należących do tej samej grupy, więc trzeba wykluczyć te strony z tej reguły - `~onet.pl,pl##.adsense`
`~fakt.pl,~forbes.pl,~auto-swiat.pl,~noizz.pl,~plejada.pl,~businessinsider.com.pl,~komputerswiat.pl,~onet.pl,~vod.pl,~onet.pl,pl##.adsense`

**Comment by hawkeye116477** [comment]
Coś nadal jest nie halo, bo nie widać zdjęć przy artykułach.
http://www.komputerswiat.pl/nowosci/aplikacje/2018/01/snapchat-moze-wprowadzic-kontrowersyjny-sposob-wyswietlania-reklam.aspx

**Comment by MajkiIT** [comment]
@F4z dzięki
