### ISSUE TITLE
mbank.pl

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#5443]
Przy próbie zalogowania wyskakują błędy/biała strona

`https://online.mbank.pl/pl/Login `

Problemem jest:

>Static filter /adv/ found in:
>    POL: polskie filtry do Adblocka i uBlocka

### Moja konfiguracja
Firefox Nightly
Ublock dev

**Comment by MajkiIT** [comment]
@gwarser Dzięki

**Comment by gwarser** [comment]
Coś nie działa.

Zmodyfikowałeś `/_adv/` a problemem jest `/adv/` (?)

**Comment by xxcriticxx** [comment]
@MajkiIT poprawka potrzebna

**Comment by xxcriticxx** [comment]
thank you @F4z

**Comment by F4z** [comment]
Poprawione.
@gwarser mógłbyś proszę sprawdzić czy teraz prawidłowo działa?

**Comment by xxcriticxx** [comment]
@lukjan32 please sprawdz czy dziala

**Comment by gwarser** [comment]
Nie chciało mi pobrać aktualizacji przez chwilę.

Już jest OK, mogę się zalogować.

**Comment by F4z** [comment]
Ok, dziękuję za sprawdzenie.

**Comment by lukjan32** [comment]
dziala
