### ISSUE TITLE
colian.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5447]
cookies

Serwis internetowy www.colian.pl wykorzystuje pliki cookies, które umożliwiają i ułatwiają Ci korzystanie z jego zasobów. 
Jeżeli nie wyrażasz zgody - zmień ustawienia swojej przeglądarki. Przeczytaj naszą Politykę Prywatności.

![capture](https://user-images.githubusercontent.com/15007183/34533739-8aad998e-f089-11e7-90d9-1da0e5de8095.PNG)

**Comment by hawkeye116477** [comment]
`colian.pl##.red`

**Comment by userOperaFF** [comment]
>  Szanowni Państwo, 
> 
> Jest nam niezwykle miło poinformować, że jako pierwsi w Polsce otrzymaliśmy prestiżową nagrodę European Candy Kettle Award. 
> Stowarzyszenie European Candy Kettle Club wyróżniło nas za innowacyjność i wkład w rozwój rynku słodyczy.

A to może do pop-up / wewnętrznych

**Comment by hawkeye116477** [comment]
@userOperaFF Dodam to do Polskich filtrów elementów irytujących.

**Comment by hawkeye116477** [comment]
@MajkiIT Tak w sumie to nie wiem czy ten komunikat ciasteczkowy chować czy nie, bo tam nawet jest informacja copyright i kto stronę stworzył, to jest taka stopka, więc chyba raczej to zostawimy.

**Comment by MajkiIT** [comment]
zostawiamy
