### ISSUE TITLE
msfera.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5456]
![2018-01-04 01_36_08-meska sfera - serwis dla facetow i nie tylko](https://user-images.githubusercontent.com/5884000/34545829-ce0ecb06-f0ef-11e7-9461-a2ff6edf56e2.png)

sekcja reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
na głównej nic nie widze.
