### ISSUE TITLE
mbank.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#5467]
po zalogowaniu sie do konta pojawia sie komunikat

![1](https://user-images.githubusercontent.com/17565773/34569637-a907165e-f169-11e7-981a-c64e1cf8cf81.jpg)

**Comment by devofdisaster** [comment]
A konkretniej, blokowane są poniższe żądania:

![obraz](https://user-images.githubusercontent.com/4033768/34570808-2567036e-f16d-11e7-878c-11bf6f0951e2.png)

**Comment by lukjan32** [comment]
mozna cos zrobic, dodac?

**Comment by KonoromiHimaries** [comment]
aktualizacja filtrów nie pomaga? był niedawno zgłaszany ten problem
https://github.com/MajkiIT/polish-ads-filter/issues/5443

**Comment by lukjan32** [comment]
ok, czekam

**Comment by xxcriticxx** [comment]
please see #5443

**Comment by KonoromiHimaries** [comment]
pojawiła się aktualizacja

**Comment by lukjan32** [comment]
dziala
