### ISSUE TITLE
spidersweb.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5468]
![2018-01-04 19_59_55-spider s web - blog blisko technologii](https://user-images.githubusercontent.com/5884000/34579654-22efc7c0-f18a-11e7-8233-3cf6a1cf5f67.png)

reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
zaktualizuj filtry

**Comment by MajkiIT** [comment]
@hawkeye116477 zerkniesz?

**Comment by hawkeye116477** [comment]
@MajkiIT `spidersweb.pl##.after-audibg`

**Comment by MajkiIT** [comment]
@hawkeye116477 za dużo blokuje
