### ISSUE TITLE
ironmangdynia.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5469]
![2018-01-04 20_15_48-ironman 70 3 gdynia - ruszaja zapisy na enea ironman 70 3 gdynia](https://user-images.githubusercontent.com/5884000/34580122-133535c0-f18c-11e7-85b0-e6dbb778af83.png)
`http://ironmangdynia.pl/pl/newsy/item/625-ruszaja-zapisy-na-enea-ironman-70-3-gdynia`

sekcja reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
`ironmangdynia.pl##.adverts-sidebar`
