### ISSUE TITLE
gieldaigospodarka.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5470]
![2018-01-04 20_20_35-gielda i gospodarka pl rynki makroekonomia nowe technologie](https://user-images.githubusercontent.com/5884000/34580305-c79a1d1e-f18c-11e7-812b-1706279498dd.png)

sekcja reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
```
gieldaigospodarka.pl##.footer-widget-area > .col-md-4:nth-of-type(3)
gieldaigospodarka.pl##.footer-widget-area > .col-md-4:nth-of-type(2)
```
