### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by letarg0** [MajkiIT/polish-ads-filter#5472]
![zrzut ekranu 2018-01-04 o 20 20 09](https://user-images.githubusercontent.com/35114178/34580421-3f3b87a4-f18d-11e7-8549-5d94e4a6a3f6.png)

wredne reklamy na samej gorze

**Comment by MajkiIT** [comment]
adblock?

**Comment by gwarser** [comment]
Estetyczna biel ;) `||dobreprogramy.pl^$csp=img-src 'self' *.dpcdn.pl`

**Comment by letarg0** [comment]
no właśnie nie działa

**Comment by KonoromiHimaries** [comment]
@letarg0 zainstaluj ublock origin lub nano adblocker i zaktualizuj filtry do najnowszej wersji
