### ISSUE TITLE
Ciekawostka To działa?

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#5482]
http://antyweb.pl/opera-nocoin-cryptojacking-adblock/

**Comment by userOperaFF** [comment]
sprawdź gdzieś gdzie kopią:

https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt

Powinno teoretycznie działać, bo opera wtedy blokuje filtrami głównie  sieciowymi i uBlock dobija resztki - chciaż ja i tak tego nie używam.

**Comment by xxcriticxx** [comment]
w ubo jest uBlock filters – Resource abuse​​​​​ automatycznie wlonczona

**Comment by userOperaFF** [comment]
> uBlock filters – Resource abuse

![image](https://user-images.githubusercontent.com/33114475/34607875-eab1b224-f215-11e7-9570-c435f6d201f7.png)


I mnie w Oprze się nie włączyła coś chrzanili przy aktualizacji dodatku.

---

Przydałaby się funkcja, zobacz używane filtry z listy.

**Comment by xxcriticxx** [comment]
@userOperaFF toc masz zaznaczone resource abuse

**Comment by userOperaFF** [comment]
**Ale po ręcznym zaznaczeniu** - powiedzmy że to wina utrudnień Opery i wydań uBlock na nią, poza tym widać że blisko 50 filtrów mogli by chyba dodać (nie mam jak przejżeć - ublock nie daje opcji, a skrypt redundancyjny raczej może nie działać).

**Comment by xxcriticxx** [comment]
@userOperaFF https://pastebin.com/T8HjY1AP

**Comment by userOperaFF** [comment]
Tyle to też mogę podejrzeć, chodzi o użyte **49 z 57** / **17 z 77** z list projektu [nocoins](/hoshsadiq/adblock-nocoin-list/).

Chcę wiedzieć czy to dublowanie ochrony czy dodatkowe zablokowanie możliwych 61 innych ataków kopania.

**Comment by xxcriticxx** [comment]
@userOperaFF doubles i ubo uzywa roznice

**Comment by userOperaFF** [comment]
A jak je wykryć bez pomocy gorhilla, diff-checker da na to radę lub jakieś dużo lepsze narzędzie do porównywania?

**Comment by xxcriticxx** [comment]
@userOperaFF ubo jest tak napisany ze podwojne sam wyeliminuje

**Comment by userOperaFF** [comment]
Ale po co mi 3 jak można by zgłosić tego co nie mają na liście i by się ustosunkowali że ubijają koparki inną regułą np. z zaawansowanym regexem.
