### ISSUE TITLE
gadzetomania.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#5483]
AdBlock Detect

**Comment by MajkiIT** [comment]
@KonoromiHimaries @xxcriticxx @F4z @hawkeye116477 macie to ?

**Comment by KonoromiHimaries** [comment]
![2018-01-05 19_45_56-gadzetomania pl - informacje komentarze opinie](https://user-images.githubusercontent.com/5884000/34623308-15153690-f251-11e7-9a7b-676da3bf27a8.png)

**Comment by KonoromiHimaries** [comment]
bardzo ładnie z ich strony, stworzyli własną whiteliste : )

**Comment by KonoromiHimaries** [comment]
![2018-01-05 19_47_49-gadzetomania pl - informacje komentarze opinie](https://user-images.githubusercontent.com/5884000/34623361-533fe424-f251-11e7-85a1-cb1ecb5c28e4.png)

**Comment by xxcriticxx** [comment]
@MajkiIT yes sir!

**Comment by xxcriticxx** [comment]
@hawkeye116477 dla ciebie cookies na dole!

**Comment by hawkeye116477** [comment]
U mnie to jest, ale tylko na Vivaldim, na Waterfoksie jest ok. 
Ciastka zgaduję, że są z powodu antyadblocka, jak się z nim rozprawimy, to zapewne i komunikat ciasteczkowy zniknie.

**Comment by xxcriticxx** [comment]
od piwina 

`gadzetomania.pl##.modal__body-adblock`
`gadzetomania.pl##script:inject(abort-on-property-write.js, __serviceAbModal)`
