### ISSUE TITLE
plonskwsieci.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5484]
![2018-01-05 14_06_53-aktualnosci_ plonsk i powiat plonski](https://user-images.githubusercontent.com/5884000/34610615-33b1c2d2-f222-11e7-9936-2075e695b959.png)

reklama + pusta sekcja + pusta sekcja ogloszenia

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by MajkiIT** [comment]
plonskwsieci.pl##.clearfix.jm-module-content > .custom
