### ISSUE TITLE
playpuls.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#549]
30 sec reklamy przed kazdym filmem

http://playpuls.pl/seriale/dokumentalne/z-archiwum-policji

**Comment by xxcriticxx** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/1171

**Comment by F4z** [comment]
Myślę, że teraz można użyć tej reguły żeby te reklamy się nie wyświetlały:
`playpuls.pl##script:inject(abort-on-property-write.js, ads)`

**Comment by F4z** [comment]
@xxcriticxx możesz sprawdzić czy u Ciebie ta reguła działa?
`playpuls.pl##script:inject(abort-on-property-write.js, ads)`
