### ISSUE TITLE
film auto play 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#551]
player wyglonda ten sam 

http://www.poranny.pl/sport/sporty-walki/art/9058119,wach-powietkin-transmisja-tv-relacja-online-stream-za-darmo-ppv-gdzie-obejrzec-walke-wideo,id,t.html

http://www.gk24.pl/sport/a/ksw-34-online-gdzie-ogladac-za-darmo-transmisja-na-zywo-live-stream-tv-5032016,9464179/

http://www.gs24.pl/sport/sporty-walki/a/ksw-34-online-transmisja-w-tv-za-darmo-streamy,9464737/

**Comment by xxcriticxx** [comment]
auto start 

http://ofsajd.onet.pl/newsy/ile-zarabiaja-selekcjonerzy-jak-adam-nawalka-wypada-na-tle-innych-szkoleniowcow/mpq0jy

**Comment by MajkiIT** [comment]
nie da się tego zrobić za pomocą filtrów.

**Comment by xxcriticxx** [comment]
https://greasyfork.org/en/scripts/6487-pause-all-html5-videos-on-load/code
