### ISSUE TITLE
parenting.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5524]
![2018-01-06 19_29_15-ciaza objawy ciazy kalendarz ciazy porod polog _ wp parenting](https://user-images.githubusercontent.com/5884000/34642708-f1cd1d5c-f317-11e7-8c0b-2272b4e2fab0.png)

sklep

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.25
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
Blokujemy to ?

**Comment by MajkiIT** [comment]
To nie jest oferta handlowa
