### ISSUE TITLE
pogoda.wp.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5526]
![2018-01-06 19_32_37-ten superwulkan to gigant zadziwil naukowcow - pogoda - wp pl](https://user-images.githubusercontent.com/5884000/34642735-6ba1b142-f318-11e7-9446-c565435be1dc.png)
`https://pogoda.wp.pl/gid,17509380,kat,1035571,title,Ten-superwulkan-to-gigant-Zadziwil-naukowcow,galeria.html`

pusta sekcja

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.25
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by hawkeye116477** [comment]
@MajkiIT Przytniemy, nie zaszkodzi :smile:.
`pogoda.wp.pl##.apc:style(min-height: auto !important;)`

**Comment by userOperaFF** [comment]
Może jakoś odblokować, tam nie było reklam.

EasyList Polish zostawili zawartość zakładek:

![obraz](https://user-images.githubusercontent.com/33114475/34643799-147834be-f32b-11e7-804c-a6a5d1b17c16.png) |
--- |
