### ISSUE TITLE
fitness.wp.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5536]
![2018-01-06 20_03_49-fitness - informacje komentarze opinie](https://user-images.githubusercontent.com/5884000/34642986-c7a5b746-f31c-11e7-9bf2-3fd854e0c8b4.png)

anty-adblock

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.25
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by userOperaFF** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/5483#issuecomment-355664766 + https://github.com/MajkiIT/polish-ads-filter/issues/5483#issuecomment-355679170
