### ISSUE TITLE
fotoblogia.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5538]
migający komunikat anty-adblock

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.25
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
U mnie nic nie miga . @xxcriticxx @hawkeye116477 zerkniecie?

**Comment by hawkeye116477** [comment]
@MajkiIT Jak otworzysz główną i przejdziesz do jakiegoś artykułu, to miga.

**Comment by hawkeye116477** [comment]
Nic nie miga, @KonoromiHimaries niech zaktualizuje filtry uzupełniające dla uBlocka.

**Comment by xxcriticxx** [comment]
@MajkiIT nie widze zadnego adblocka

@hawkeye116477 cookie na dole masz?

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie
