### ISSUE TITLE
bezprawnik.pl

### ISSUE THREAD

**Issue by LArtCrime** [MajkiIT/polish-ads-filter#5542]
https://bezprawnik.pl/umowa-najmu-mieszkania/

za mocno wycięta prawa kolumna, może w filtrach wewnętrznych powinna być wycięta lektura proponowanych artykułów.

tak wygląda po dezaktywacji:

> ![image](https://user-images.githubusercontent.com/33114475/34667215-5afc77d6-f468-11e7-91f0-be4e00d63e50.png) |
> --- |

---

Został też div po górnej reklamie:

> ![image](https://user-images.githubusercontent.com/33114475/34667263-974ec70c-f468-11e7-9944-477650f086b3.png) |
> --- |

**Comment by MajkiIT** [comment]
```
bezprawnik.pl#@#.show-for-large.columns
bezprawnik.pl##.margin-bottom40.sidebar
bezprawnik.pl##.margin-bottom40.headline
```
