### ISSUE TITLE
GROUP! maniak.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5548]
<details>

![2018-01-08 16_03_45-techmaniak pl _ najwieksza polska siec blogow profesjonalnych nt](https://user-images.githubusercontent.com/5884000/34676575-94f10888-f48d-11e7-8524-4dfe319b93d0.png)

</details>

`https://www.techmaniak.pl/`

sekcja reklama

---

<details>

![2018-01-08 16_05_12-gizmaniak pl - gadzety elektroniczne hdtv hifi](https://user-images.githubusercontent.com/5884000/34676719-13ff503a-f48e-11e7-9a0c-1d1674b004d3.png)

![2018-01-08 16_08_00-gizmaniak pl - gadzety elektroniczne hdtv hifi](https://user-images.githubusercontent.com/5884000/34676732-1f67f8be-f48e-11e7-9caf-c6c7a2fd6107.png)

</details>

`https://www.gizmaniak.pl/`

sekcja reklama po prawej i na dole

---

<details>

![2018-01-08 16_20_55-blogomaniak _ o blogowaniu maniakalnie po mesku](https://user-images.githubusercontent.com/5884000/34677296-f70f807e-f48f-11e7-94a2-984f2a3f2cda.png)

</details>

`https://www.blogomaniak.pl/`

prośba o stosowanie jednej polityki do wszystkich podserwisów
prośba o usunięcie reguły ukrywającej sekcje wewnętrzną

---

<details>

![2018-01-08 16_26_26-acer switch 7 black edition elegancka hybryda za 2 tysiace euro](https://user-images.githubusercontent.com/5884000/34677547-cf74e35a-f490-11e7-8c88-961cac4c06f9.png)

</details>

`https://www.mobimaniak.pl/271616/acer-switch-7-black-edition-elegancka-hybryda-2-tysiace-euro/`

prośba o stosowanie jednej polityki do wszystkich podserwisów
prośba o usunięcie reguły ukrywającej tabele ceneo i traktowanie ich jako linki afiliacyjne

---

<details>

![2018-01-08 16_32_44-fotomaniak pl _ fotografia cyfrowa apararty cyfrowe foto - nowosci zapowiedzi](https://user-images.githubusercontent.com/5884000/34677816-9c8c952c-f491-11e7-8161-d261990cb9d0.png)

![2018-01-08 16_32_32-fotomaniak pl _ fotografia cyfrowa apararty cyfrowe foto - nowosci zapowiedzi](https://user-images.githubusercontent.com/5884000/34677823-a01aa562-f491-11e7-8849-2de8f6702acd.png)

</details>

`https://www.fotomaniak.pl/`

sekcja reklama po prawej i na dole strony

---

<details>

![2018-01-08 16_34_31-acer blog](https://user-images.githubusercontent.com/5884000/34677926-f46054b4-f491-11e7-900f-7441b31c8c7e.png)

</details>

`https://www.acermaniak.pl/`

sekcja reklama po prawej

---

<details>

![2018-01-08 16_57_16-agdmaniak pl - recenzje i testy sprzetu agd aktualnosci rankingi porady opin](https://user-images.githubusercontent.com/5884000/34679070-1a43bfce-f495-11e7-94e2-bc014568c9dc.png)

![2018-01-08 16_57_25-agdmaniak pl - recenzje i testy sprzetu agd aktualnosci rankingi porady opin](https://user-images.githubusercontent.com/5884000/34679076-1f235edc-f495-11e7-8e4f-5fcbb6951dd9.png)

</details>

`https://www.agdmaniak.pl/`

sekcja reklama po prawej i na dole strony

<details>

![2018-01-08 16_37_32-test hurom one stop h-ai czy to najlepsza wyciskarka wolnoobrotowa_ _ agdmaniak](https://user-images.githubusercontent.com/5884000/34678939-d1ac4dc6-f494-11e7-8d90-1bc221365817.png)

</details>

`https://www.agdmaniak.pl/51082/hurom-one-stop-h-ai-test-recenzja/?utm_medium=srdtxt&utm_campaign=4094#pid=srdtxt_hurom_4094`

prośba o stosowanie jednej polityki

<details>

![2018-01-08 16_59_23-lg wprowadza sztuczna inteligencje do kuchni dzieki lodowce instaview thinq oraz](https://user-images.githubusercontent.com/5884000/34679170-65013f32-f495-11e7-9b50-de1f8e50601f.png)

</details>

`https://www.agdmaniak.pl/51632/lg-instaview-thinq-quadwash-easyclean/`

sekcja reklama

---

<details>

![2018-01-08 17_02_23-tabletmaniak pl - recenzje i testy tabletow meskim okiem aktualnosci rankingi](https://user-images.githubusercontent.com/5884000/34679289-cd076f66-f495-11e7-8a9b-7fc3f054d4f3.png)

![2018-01-08 17_02_39-tabletmaniak pl - recenzje i testy tabletow meskim okiem aktualnosci rankingi](https://user-images.githubusercontent.com/5884000/34679294-d1cfc476-f495-11e7-884b-39af18393abb.png)

</details>

`https://www.tabletmaniak.pl/`

sekcja reklama po prawej i na dole strony

---

<details>

![2018-01-08 17_10_31-rtvmaniak pl - recenzje i testy sprzetu aktualnosci rankingi porady](https://user-images.githubusercontent.com/5884000/34679675-fc953456-f496-11e7-96ec-34e0e7a91a47.png)

![2018-01-08 17_10_40-rtvmaniak pl - recenzje i testy sprzetu aktualnosci rankingi porady](https://user-images.githubusercontent.com/5884000/34679683-01607478-f497-11e7-9b25-489c4ee617fd.png)

</details>

`https://www.rtvmaniak.pl/`

sekcja reklama po prawej i na dole strony

<details>

![2018-01-08 17_12_56-hykker smart czy warto kupic bezprzewodowa klawiature z touchpadem z biedronki](https://user-images.githubusercontent.com/5884000/34679794-5173758c-f497-11e7-9149-0feb86b4b590.png)

</details>

`https://www.rtvmaniak.pl/9551568/hykker-smart-klawiatura-telewizor/`

sekcja reklama

---

<details>

![2018-01-08 17_17_34-luxmaniak pl - blog rzeczy luksusowych testy recencje i opisy](https://user-images.githubusercontent.com/5884000/34680012-0a0410ca-f498-11e7-99c9-894aeb58490a.png)

![2018-01-08 17_17_44-luxmaniak pl - blog rzeczy luksusowych testy recencje i opisy](https://user-images.githubusercontent.com/5884000/34680015-0ded87ac-f498-11e7-9c54-46a3c0f7c56f.png)

</details>

`https://www.luxmaniak.pl/`

sekcja reklama po prawej i na dole strony

<details>

![2018-01-08 17_20_57-lexus zaprezentowal koncepcyjna lodz motorowa _ luxmaniak](https://user-images.githubusercontent.com/5884000/34680102-52030f2a-f498-11e7-8072-bf0866bbb1f9.png)

</details>

`https://www.luxmaniak.pl/40824/lexus-sport-yacht/`

sekcja reklama
prośba o stosowanie jednej polityki do wszystkich podserwisów

---

<details>

![2018-01-08 17_22_57-activemaniak - portal dla aktywnych _ gadzety dla aktywnych maniakow](https://user-images.githubusercontent.com/5884000/34680208-ac994076-f498-11e7-9fdd-fb53c4f470ea.png)

![2018-01-08 17_23_08-activemaniak - portal dla aktywnych _ gadzety dla aktywnych maniakow](https://user-images.githubusercontent.com/5884000/34680216-afe0abca-f498-11e7-9850-fd14ec147a62.png)

</details>

`https://www.activemaniak.pl/`

sekcja reklama po prawej i na dole strony

---

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by hawkeye116477** [comment]
@MajkiIT Napisów reklama nie chowasz?

**Comment by KonoromiHimaries** [comment]
@MajkiIT nie są to elementy wewnętrzne, a bardziej kosmetyczne i do takiej też listy powinny trafić jeśli nie chcesz ich dodawać do ogólnej.

**Comment by MajkiIT** [comment]
@hawkeye116477 @KonoromiHimaries dzisiaj to ogarnę.
