### ISSUE TITLE
fotoblogia.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#5553]
Komunikat antyadblockowy miga.
Zdaje się, że to pomaga -> `fotoblogia.pl##script:inject(abort-on-property-write.js, __serviceAbModal)` :smile:

**Comment by userOperaFF** [comment]
Też podmiot wp jak gadzetomania?

**Comment by HateAds** [comment]
@userOperaFF Tak.
