### ISSUE TITLE
URGENT! alltube.tv

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5559]
![2018-01-09 13_34_47-menedzer zadan](https://user-images.githubusercontent.com/5884000/34721168-012fbf94-f542-11e7-9632-ed802d306f1a.png)

krypto koparka

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by xxcriticxx** [comment]
@KonoromiHimaries a ten magiczny plugin co miales szybcej co pokazuje?

**Comment by xxcriticxx** [comment]
@KonoromiHimaries podaj test link please 

@MajkiIT regex fix na streamago

test link:
http://alltube.tv/teoria-wielkiego-podrywu-the-big-bang-theory/the-matrimonial-metric/odcinek-12-sezon-11/132700

**Comment by KonoromiHimaries** [comment]
@xxcriticxx podałem

![2018-01-09 16_14_13-menedzer zadan](https://user-images.githubusercontent.com/5884000/34727796-3f530c70-f558-11e7-8333-326eccf927b7.png)
