### ISSUE TITLE
bieganieuskrzydla.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5567]
![2018-01-10 01_19_52-bieganieuskrzydla pl bieganie trening maraton](https://user-images.githubusercontent.com/5884000/34749924-74a1dbee-f5a4-11e7-8257-e74562710e4b.png)

sekcja promocja

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by xxcriticxx** [comment]
matt more thc

**Comment by KonoromiHimaries** [comment]
@xxcriticxx nobody submits you requests

**Comment by MajkiIT** [comment]
`bieganieuskrzydla.pl###text-5`
