### ISSUE TITLE
drewno.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5569]
![2018-01-10 14_23_39-drewno pl - przemysl drzewny gielda drewno tartaki tarcica meble pellets podlogi](https://user-images.githubusercontent.com/5884000/34775001-e3026b04-f611-11e7-873c-f4a0c4edb902.png)

reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
```
www.drewno.pl##.nm_box_out:nth-of-type(10)
www.drewno.pl##.nm_box_out:nth-of-type(22)
www.drewno.pl##.nm_box_out:nth-of-type(18)
www.drewno.pl##.nm_box_out:nth-of-type(6) > .nm_box
```
