### ISSUE TITLE
se.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5570]
![2018-01-10 14_25_14-ikamien pl - artykuly zdjecia wiadomosci - archiwum - se pl](https://user-images.githubusercontent.com/5884000/34775105-3ede0514-f612-11e7-936a-dd581b2943ed.png)

`http://www.se.pl/ikamienpl,38139/`

puste sekcje

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
Powyłączeniu uBo sekcja "Zobacz także" jest i tak pusta.
