### ISSUE TITLE
lawka.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5571]
![2018-01-10 14_55_13-lawka pl - twoj vortal rozrywkowy _ rozrywka _ gry online _ smieszne filmy _ smi](https://user-images.githubusercontent.com/5884000/34776369-ec56a1a2-f616-11e7-927d-65691548e704.png)

pusta sekcja reklama + cookies

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
```
lawka.pl##table:nth-of-type(2) > tbody > tr > td > table
lawka.pl###szesc
```
