### ISSUE TITLE
komorkomania.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5572]
![2018-01-10 15_13_19-komorkomania pl - informacje komentarze opinie](https://user-images.githubusercontent.com/5884000/34776940-dd472982-f618-11e7-9da6-e706a20c67f7.png)

anty-adblock

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by userOperaFF** [comment]
podmiot wp, powinno działać rozszerzenie reguły dla wp/gadzetomanii.
