### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#5573]
https://screenshotscdn.firefoxusercontent.com/images/a649efe2-607c-4b52-8219-e8cae74bff06.png

https://www.dobreprogramy.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Przejść na stronę z włączonym adblockiem

### Moja konfiguracja
**Przeglądarka internetowa:** Firefox 58.0b14 (64 bit)

**Rozszerzenia i skrypty:**
uBlock 1.14.23b17
Nano Defender 13.17

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. Polskie filtry do Adblocka i uBlocka uzupełnienie
3. EasyList
4. EasyPrivacy
5. Adguard Base Filters
6. Nano Defender Integration

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by KonoromiHimaries** [comment]
na chromie czysto
