### ISSUE TITLE
portalsamorzadowy.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5579]
![2018-01-11 12_35_28-wody opadowe nowe prawo wodne sprawi ze zaplacimy za deszczowke - gospodarka k](https://user-images.githubusercontent.com/5884000/34823734-035125ac-f6cc-11e7-8650-ef51a4a1e9dd.png)
`http://www.portalsamorzadowy.pl/gospodarka-komunalna/wody-opadowe-nowe-prawo-wodne-sprawi-ze-zaplacimy-za-deszczowke,102410.html`

sekcja partner portalu

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
`www.portalsamorzadowy.pl##.box-1 > .left`
