### ISSUE TITLE
ciapkowo.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5581]
![2018-01-11 14_09_29-ciapkowo _ schronisko dla bezdomnych zwierzat w gdyni adopcje psow i kotow int](https://user-images.githubusercontent.com/5884000/34827054-3128cfea-f6d9-11e7-8b88-a45ef0a12466.png)

pusta sekcja reklama + puste sekcje fb

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
`ciapkowo.pl###execphp-3`
