### ISSUE TITLE
proto.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5584]
![2018-01-11 19_04_11-proto wszystko o public relations](https://user-images.githubusercontent.com/5884000/34839566-4c4f1788-f702-11e7-8195-d76d5cad6261.png)

reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
```
proto.pl###zone-header-wrapper
proto.pl###block-block-1
```
