### ISSUE TITLE
dobrewiadomosci.net.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5585]
![2018-01-11 19_11_55-pies dziekuje ratownikowi ktory ocalil mu zycie - dobre wiadomosci](https://user-images.githubusercontent.com/5884000/34839854-658fce8a-f703-11e7-953f-301b1ce9e52c.png)
`http://dobrewiadomosci.net.pl/17560-pies-dziekuje-ratownikowi-ktory-ocalil-mu-zycie/`

duży baner na topce

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
`dobrewiadomosci.net.pl##center`

**Comment by krystian3w** [comment]
regresja #21308
