### ISSUE TITLE
businessinsider.com.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5586]
![2018-01-11 19_14_16-business insider polska](https://user-images.githubusercontent.com/5884000/34839951-b4294f44-f703-11e7-8930-0cded432dfc2.png)

pusta sekcja reklama + pusta sekcja obserwuj nas

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
`businessinsider.com.pl###adSS-Detal`
