### ISSUE TITLE
przegladsportowy.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5587]
![2018-01-11 20_38_39-sport_ serwis przegladu sportowego - przegladsportowy pl](https://user-images.githubusercontent.com/5884000/34843709-89eeff9c-f70f-11e7-8790-0dbb3c071701.png)

https://github.com/MajkiIT/polish-ads-filter/issues/5583

reklama

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by KonoromiHimaries** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/5583

**Comment by MajkiIT** [comment]
`przegladsportowy.pl###region-item21626`
