### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by crazyjack79** [MajkiIT/polish-ads-filter#5588]
### Zrzut ekranu

![opera](https://user-images.githubusercontent.com/35058050/34872862-fc1d744e-f792-11e7-919a-cd516c71e3b8.jpg)
### Link bezpośredni

https://www.dobreprogramy.pl/
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na stronę https://www.dobreprogramy.pl/
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**
Slimjet
**Rozszerzenia i skrypty:**
Ublock Origin 1.14.22
**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. 
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by userOperaFF** [comment]
było, zostawiamy chyba dla @jspenguin2017

**Comment by KonoromiHimaries** [comment]
na adguardzie jest ok.
