### ISSUE TITLE
Nawet główna strona Rzeczpospolitej kopie kryptowaluty na Waszych komputerach

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5589]
please read 

https://zaufanatrzeciastrona.pl/post/nawet-glowna-strona-rzeczpospolitej-kopie-krytowaluty-na-waszych-komputerach/

https://www.dobreprogramy.pl/Strona-Rzeczpospolitej-zawiera-skrypty-kopiace-kryptowaluty-aktualizacja,News,85358.html

**Comment by LArtCrime** [comment]
http://cdn.adblockcdn.com/filters/nominers.txt

Coś dużo tych list nagle.

**Comment by MajkiIT** [comment]
@LArtCrime tzn ?

**Comment by LArtCrime** [comment]
To, że nie wiem dalej czy sens jest jakieś aktywować poza domyślną z uBlock.

A jaką nie dodam:

 - `http://cdn.adblockcdn.com/filters/nominers.txt`
 - `https://raw.github.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt`
    - `https://raw.github.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt`

to ma więcej niż 0 użytych flitów i ciężko mi zweryfikować czy chroni czy filtr nic nie zablokuje, bo uBlockowy już zablokował.

![obraz](https://user-images.githubusercontent.com/33114475/34918848-2996e1da-f95a-11e7-84d4-ad376fd7a4ed.png)

**Comment by MajkiIT** [comment]
@LArtCrime to jesdt zbędne `https://raw.github.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt` bo to domeny z `https://raw.github.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt`

**Comment by xxcriticxx** [comment]
ubo na standardzie ma filtry do tego

 `uBlock filters – Resource abuse​​​​​163 used out of 165`
