### ISSUE TITLE
katowice-airport.com

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#5591]
zle dzialaja rozklady lotow, nie zmieniaja sie jak naciskam przyloty i odloty, na podstronie rozklady lotow.

**Comment by krystian3w** [comment]
> https://www.katowice-airport.com/pl/pasazer/tablica-lotow

U mnie działa, jaki bloker reklam, przeglądarka i system.

**Comment by KonoromiHimaries** [comment]
u mnie to samo

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by lukjan32** [comment]
opera 50, ubvlock

**Comment by userOperaFF** [comment]
W sumie - https://www.katowice-airport.com/pl/pasazer/rozklad-lotow - na pewno to nie podstrona padła?

Po kliknięciu tej zielonej strzałeczki (![image](https://user-images.githubusercontent.com/33114475/34879207-be0e33cc-f7ac-11e7-8d6f-2f27bd5ef6be.png)) się odświeża, może tak bardzo słabo to zaprogramowali?

**Comment by MajkiIT** [comment]
`@@||www.katowice-airport.com/js-libraries/cookie.js$script,domain=www.katowice-airport.com`

**Comment by userOperaFF** [comment]
Wrzucili tam js do automatycznego przełączania się bez klikania strzałki... 🤣

**Comment by userOperaFF** [comment]
Teraz to kosmetycznie trzeba wyciąć cookies:

![screenshot-2018-1-14 katowice airport](https://user-images.githubusercontent.com/33114475/34916303-64da8e0a-f936-11e7-9dd1-9d4d043dec6b.png)

**Comment by lukjan32** [comment]
dzieki, dziala.
