### ISSUE TITLE
fakt.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#5593]
Adblock detect 

Nano defender nie pomaga

**Comment by KonoromiHimaries** [comment]
u mnie czysto
a zainstalowałeś filtr wymagany przez nano defender?

**Comment by userOperaFF** [comment]
Mam "reklamy nie są takie złe" z Adblock Plus na trybie prywatnym (FX 57).

**Comment by MajkiIT** [comment]
@userOperaFF sprawdź to `fakt.pl#@#.smallAd`

**Comment by LArtCrime** [comment]
Wychodzi że pudło 😰, miałam wcześniej jako ogólną dla każdej i po ograniczeniu do faktu nie zniknęło.

**Comment by LArtCrime** [comment]
Wychodzi że pudło 😰, miałam wcześniej jako ogólną dla każdej i po ograniczeniu do faktu nie znikło.

**Comment by xxcriticxx** [comment]
nope @MajkiIT  smallad nie pomaga

**Comment by MajkiIT** [comment]
czyszczenie cookies nic nie daje ?

**Comment by gzenio22** [comment]
@MajkiIT nie pomaga Cookie czyste reg dodana a i tak mam potworka
