### ISSUE TITLE
focustelecom.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5595]
![2018-01-12 22_21_11-aplikacja contact center aplikacja call center focus contact center](https://user-images.githubusercontent.com/5884000/34895640-fd59d45c-f7e6-11e7-83d9-de022ebfb08c.png)

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
@KonoromiHimaries ja tego nie mam. @xxcriticxx @hawkeye116477 zerkniecie ?

**Comment by xxcriticxx** [comment]
@MajkiIT ja widze cala strone jest good
