### ISSUE TITLE
newsbook.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5599]
![2018-01-13 03_22_10-newsbook _ polski portal nie tylko o polsce](https://user-images.githubusercontent.com/5884000/34901884-22ab1e58-f811-11e7-8dc6-b5c8fa5e39e6.png)

pusta sekcja + pusta sekcja nie przegap + pusta sekcja dobre rady

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.19
Chrome 63.0.3239.132

**Comment by hawkeye116477** [comment]
Sociala tu nie widzę, ale dobre rady zostały do wycięcia albo przywrócenia :smile:.
