### ISSUE TITLE
potplayerclub.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#5603]
https://potplayerclub.pl/portfolio/

![obraz](https://user-images.githubusercontent.com/35370833/34916912-7531b676-f93f-11e7-917a-93d3c475d3ba.png)

```
potplayerclub.pl##.jgcabd-notice-wrapper
potplayerclub.pl##.jgcabd-container
```

**Comment by Ravizz** [comment]
Brakuje tagu "adblock detect".

**Comment by Ravizz** [comment]
@MajkiIT , @xxcriticxx : brakuje tagu "adblock detect".
