### ISSUE TITLE
Wsparcie dla Opery

### ISSUE THREAD

**Issue by Dreknar** [MajkiIT/polish-ads-filter#5605]
Cześć
Zamierzacie wprowadzić wsparcie dla wbudowanego adblocka Opery? Niestety nie działają filtry dla:
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/anti-donate-filters/adblock_anty-dotacje.txt
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/inside-filters/adblock_wewnetrzne.txt

Niestety w momencie dodania mam błąd: 
![image](https://user-images.githubusercontent.com/24864886/34949427-5d70db44-fa10-11e7-94f3-b9ff77d0ab39.png)

**Comment by KonoromiHimaries** [comment]
nie planowałem wsparcia dla adblockerów innych niż ublock origin/adguard lub ich aktualnych forków ( gdyż są o wiele bardziej skuteczne, niż skorumpowany adblocker opery )

![](https://user-images.githubusercontent.com/35114178/34580421-3f3b87a4-f18d-11e7-8549-5d94e4a6a3f6.png)

wymienione wyżej listy są prowadzone tylko przeze mnie i nie mam ochoty dbać o kompatybilność ze wszystkimi adblockerami. muszę dodać wiele nowych reguł i wole ten czas poświęcić właśnie na to.

oczywiście możesz zrobić commita i zadbać o kompatybilność z operą.
jednak nie gwarantuje że z czasem po dodaniu nowych reguł do list, adblocker opery znowu nie zarzuci wsparcia.

może z czasem rosnącej ich popularności postanowie wesprzeć inne adblocki, jednak na razie rekomendowałbym instalacje dodatku ublock origin.
`https://addons.opera.com/pl/extensions/details/ublock/`

**Comment by MajkiIT** [comment]
@KonoromiHimaries a masz jakiś wzór takich filtrów ?

**Comment by xxcriticxx** [comment]
pora zamontowac opere portable

**Comment by Dreknar** [comment]
Rozumiem i szanuję taką taką decyzję. Trzeba zatem dorzucić uBlock do Opery.

**Comment by LArtCrime** [comment]
Jak dla mnie marne wsparcie jest nawet dla reguł ABP, nie działa kontekstowe wycinanie pól a przynajmniej w 2 na 10 przypadkach.
