### ISSUE TITLE
a-o.ninja adblock blokuje każdy player na stronie z anime online

### ISSUE THREAD

**Issue by OtakuPL** [MajkiIT/polish-ads-filter#5606]
### Zrzut ekranu

https://scr.hu/Y9N6Pk

### Link bezpośredni

(https://a-o.ninja/)
Przykład: (https://a-o.ninja/anime/kirakira-precure-a-la-mode-2017/47)

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Nie żeby coś ale ta strona jest stworzona tylko na potrzeby playerów z anime a adblock je blokuje wszystkie na stronie.
2. Poprawić filtry tak by wyświetlały playery.
3. Strona bez playerów staje się pustą domeną co się moja z celem blokowania reklam a nie playerów.

### Moja konfiguracja
**Przeglądarka internetowa:**
chrome 64bit (najnowsze)
firefox 64bit (najnowsze)
**Rozszerzenia i skrypty:**
adblock

**Comment by MajkiIT** [comment]
u mnie jest ok. Jakie filtry masz ?

**Comment by OtakuPL** [comment]
Nic dodatkowego nie instalowałem, mam tylko to: (https://scr.hu/9olnwa)

**Comment by MajkiIT** [comment]
jestem ciekaw co jest w liście Afblock Custom filters. Możesz ją wyłączyć na chwilę i sprawdzić?

**Comment by OtakuPL** [comment]
Wyłączyłem, odświeżyłem stronę i wszytko gra :)
Tylko pewnie nie tylko ja mam ten problem i przydałoby się to poprawić. Jak pisałem wyżej, pobrałem zainstalowałem adblocka i nic nie ruszałem.

**Comment by KonoromiHimaries** [comment]
potwierdzam
![2018-01-15 17_44_52-takunomi 01 pl full hd a-o ninja anime online pl 2018 emitowane](https://user-images.githubusercontent.com/5884000/34952989-d5142e8e-fa1b-11e7-9e99-68f7b863df17.png)

**Comment by MajkiIT** [comment]
Pewnie blokowanie koparek na stronie tak się skończyło.

**Comment by OtakuPL** [comment]
Ja niestety nie znam adresów do tych filtrów :/

**Comment by KonoromiHimaries** [comment]
@OtakuPL wejdz tutaj
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt

+ kliknij ctrl+f
+ wpisz `a-o.ninja`
+ skopiuj wszystkie wpisy zawierające tą domene do własnej listy będącej w zakładce dostosuj
+ każdy wpis w następnej linii, tak jak w pliku `polish-adblock-filters/adblock.txt`
+ wyłącz `polskie filtry do AdBlocka`
+ sprawdź czy player na a-o.ninja działa
+ jeśli działa, to nie czytaj dalej i czekamy na interwencje majkiego
+ jeśli nie działa to wycinaj po jednym filtrze(wpisie)  aż odgadniesz który psuje player
+ wtedy majki go usunię lub przeniesie do listy ublocka
+ wtedy będziemy gdybać jakie reguły dać na adblocka

**Comment by MajkiIT** [comment]
@OtakuPL to nie ta lista a nie masz włączonej tej ? Cryptocurrency (Bitcoin) Mining Protection List

**Comment by MajkiIT** [comment]
@OtakuPL @KonoromiHimaries ta regułą wszystko psuje 
`/^((?!(^https?):\/\/(vidfile\.net|(www\.)?youtube\.com|openload\.co|docs\.google\.com|video\.sibnet\.ru|oload\.stream|streamango\.com|vidlox\.tv|(www\.)?rapidvideo\.com|tune\.pk|(www\.)?dailymotion\.com|estream\.to)\/).)*$/$subdocument,domain=a-o.ninja|centrum-dramy.pl|love-drama.pl|vidfile.net`

**Comment by OtakuPL** [comment]
No mam włączoną Cryptocurrency (Bitcoin) Mining Protection List, wyłączyłem i też player zaczęły się pojawiać. Masz rację z tą regułą.  
Co do: domain=a-o.ninja|centrum-dramy.pl|love-drama.pl|vidfile.net to tam to samo znikają całe playery.
Idzie to jakoś globalnie naprawić?

**Comment by MajkiIT** [comment]
zgłosiłem to do Adblocka. Można dodać to do Whitelisty, ale nie wiem czy nie zrobię gorszego bigosu.

**Comment by OtakuPL** [comment]
OK, w każdym razie dziękuję za pomoc ;)
Będę obserwował czy coś się zmienia i czy poprawili.
Pozdrawiam

**Comment by MajkiIT** [comment]
@rhanajoy FYI

**Comment by rhanajoy** [comment]
@MajkilT dziękuję za heads-up! Przekażę raport naszym programistom do zbadania.

**Comment by Gumcajs** [comment]
podpinam się do tematu, korzystam akurat z ublocka i mam ten sam problem co kolega tego tematu chociaż bardziej on wynika z tego że wprowadzili jakiś nowy rodzaj blockowania użytkowników adblock i ublock, co powoduje poważne problemy z oglądaniem, a wygląda to tak:
![problem](https://user-images.githubusercontent.com/38502849/38942801-1545a502-4330-11e8-9dd3-15124fe5320f.png)

po zablokowania tego obrazu, i tak odtwarzacze są za blankowane i nie mam pomysłu jak sobie już z tym poradzić, dodatkowo pojawiły się małe natrętne śmieciowe reklamy ale to już w blokowałem i sprawdzam czy mu pasuje na innych, żeby syf się nie pojawiał, ale jak by była jakaś rada co do ublocka to chętnie bym prosił o rozwiązanie

**Comment by KAROLEK003** [comment]
Jest na to jedyny sposób. Wyłącz adblocka jak każą :)

**Comment by KAROLEK003** [comment]
To spadaj oglądać do Netflixa, tacy tak ty powinni nie istnieć.

**Comment by Gumcajs** [comment]
ach dziękuje za ten komplement, ale cóż jak to powiedział cejrowski, z głupkami nie ma sensu dyskutować :)

**Comment by KAROLEK003** [comment]
Z głupkiem nie będę dyskutował.

**Comment by RukashiChan** [comment]
Karolek to pewnie ktoś od ao, z nimi nie warto gadać
