### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#5609]
brak daty i mozliwosci pobrania innych wersji. 

opera 50 i ublock.

![1](https://user-images.githubusercontent.com/17565773/34983748-cfa1d210-faae-11e7-9dbe-586ed4aa08ed.jpg)

**Comment by MajkiIT** [comment]
Zaktualizuj filtry

**Comment by lukjan32** [comment]
ok, jest.

rano tez zaktualizowalem

**Comment by xxcriticxx** [comment]
@lukjan32 gitara?

**Comment by lukjan32** [comment]
dziala
