### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by joksik** [MajkiIT/polish-ads-filter#5613]
1) witam. od kilku dni mecze sie z reklamą Opery na stronie www.dobreprogramy.pl testowałem różne filtry a nawet zainstalowałem je wszystkie dla ublocka z tej strony:
https://www.certyficate.it/adblock/
niestety problem ciagle wystepuje. nawet jak zablokuje reklame recznie to i tak co odświeżenie strony wraca

2) czy wszystkie filtry dostepne na stronie https://www.certyficate.it/adblock/ mozna rowniez uzywac z nano adblockerem + nano defender ?

**Comment by KonoromiHimaries** [comment]
https://github.com/NanoAdblocker/NanoFilters/issues/3#issuecomment-358305356

**Comment by KonoromiHimaries** [comment]
@joksik możesz sprawdzić czy wszystko dobrze po aktualizacji?

**Comment by LArtCrime** [comment]
Za mocno coś działa ta reguła na forum na linki txt, nawet dodanie "`www.`" nie pomogło.
