### ISSUE TITLE
minecraftpolska.net

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5615]
cookies

![capture](https://user-images.githubusercontent.com/15007183/35070088-38882f44-fbaa-11e7-8414-af1ea7657c84.PNG)

**Comment by gzenio22** [comment]
![screenshot_1](https://user-images.githubusercontent.com/21177361/35073174-130ff65a-fbe8-11e7-83fa-9cea374d7f4d.png)

Mam tu coś lepszego :D

**Comment by hawkeye116477** [comment]
@MajkiIT Masz tego antyadblocka? Bo ja nie mam.

**Comment by MajkiIT** [comment]
@hawkeye116477 nie, nie mam.
