### ISSUE TITLE
GROUP! twojawierzbica.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5618]
![2018-01-18-przerwy w dostawie pradu 08 01 2018 wierzbica _ portal wierzbicy - twojawierzb](https://user-images.githubusercontent.com/5884000/35082013-c0a2d7d6-fc17-11e7-87f3-c6cbd63997e4.png)
`https://twojawierzbica.pl/artykul/przerwy-w-dostawie-pradu/361734`

`https://twojwolanow.pl/artykul/zagrozenie-asf-co-zrobic/352254`

`http://twojskaryszew.pl/artykul/ruszyl-konkurs-fotograficzny/359073`

`https://twojzwolen.pl/artykul/korona-europy-dla-miasta/314430`

pusta sekcja

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.27
Nano Defender 13.22
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
Tam będą filmy.
