### ISSUE TITLE
m.se.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5620]
![2018-01-18-piekna i bestia w tancu z gwiazdami popek zatanczy z kaczorowska - m se pl](https://user-images.githubusercontent.com/5884000/35084406-169db3de-fc24-11e7-9982-046f891f2c67.png)
`http://m.se.pl/wiadomosci/gwiazdy/piekna-i-bestia-w-tancu-z-gwiazdami-popek-zatanczy-z-kaczorowska_1036545.html`

brak playera

moje filtry
https://gist.githubusercontent.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3/raw/dff65bff59597c82f387c3f0880cb32cce146e67/nano.txt

Nano Adblocker 1.0.0.27
Nano Defender 13.22
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
To jest reklama

**Comment by KonoromiHimaries** [comment]
@MajkiIT w każdym bądź razie pusta sekcja została
