### ISSUE TITLE
swiatfilmow.com

### ISSUE THREAD

**Issue by Ravizz** [MajkiIT/polish-ads-filter#5639]
### Zrzut ekranu
![swiatfilmow](https://user-images.githubusercontent.com/35421792/35324452-0ce5a7b2-00f1-11e8-9381-7b2b666e2c93.png)

### Link bezpośredni
https://www.swiatfilmow.com/watch.php?vid=94a072607

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść bezpośrednio pod podany link z filmem albo wejść na stronę główną serwisu i kliknąć jakiś film, pojawi się 30 sekundowy timer.

### Moja konfiguracja
**Przeglądarka internetowa:**
FF 57.0.4 / O 50.0.2762.58 (PGO)

**Rozszerzenia i skrypty:**
Nano Defender 13.20
uBO v1.14.25rc1

**Filtry:**
1. POL: polskie filtry do Adblocka i uBlocka​​​​​
2. POL: polskie filtry do uBlocka uzupelnienie
3. Polskie filtry ciasteczkowe
4. KAD - Przekręty​
5. Adblock & uBlock polish filter - Adguard supplement
6. EasyList
7. Adblock Warning Removal List
8. Adguard Base Filters
9. uBlock filters
10. uBlock filters – Unbreak
11. Nano Defender Integration
12. NanoBase
13. NanoTimer
14. NanoWhitelist

**Comment by MajkiIT** [comment]
@Ravizz Jedynie co możemy zrobić to odblokowanie przycisku skip już od początku. Pasuje Ci to ?

**Comment by Ravizz** [comment]
Ok, lepszy rydz niż nic.

**Comment by MajkiIT** [comment]
@Ravizz update filtrów uzupełniających do uBo.

**Comment by Ravizz** [comment]
@MajkiIT Działa, jednak żeby wyglądało bardziej elegancko to powinno się dodać jeszcze regułę ukrywającą zdublowany niepotrzebny przycisk: `www.swiatfilmow.com##.preroll_skip_countdown.btn-success.btn-sm.btn`.

**Comment by Ravizz** [comment]
@MajkiIT: analogicznie jak w  https://github.com/MajkiIT/polish-ads-filter/issues/5693, tutaj też można dać:
`swiatfilmow.com##script:inject(nano-setTimeout-booster.js, function, 1000, 0.02)`
tylko żeby działało, to trzeba najpierw usunąć, tę regułę, którą dodałeś.
