### ISSUE TITLE
ark.intel.com

### ISSUE THREAD

**Issue by Ravizz** [MajkiIT/polish-ads-filter#5641]
### Zrzut ekranu
![](https://s3.dodajfote.pl/2018/01/18/intelfa9ed338012489bb.png)

### Link bezpośredni
https://ark.intel.com/pl/products/75122/Intel-Core-i7-4770-Processor-8M-Cache-up-to-3_90-GHz

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść bezpośrednio pod podany przykładowy link i kliknąć na ikonkę 'niebieskiego znaku zapytania w czarnym kółeczku' przy parametrze, powinien pojawić się dymek z opisem parametru, a nie pojawia się.
2. Błąd jest spowodowany filtrem `/cookie.js$script` znajdującym się w Polskie filtry ciasteczkowe

### Moja konfiguracja
**Przeglądarka internetowa:**
FF 57.0.4 / O 50.0.2762.58 (PGO)

**Rozszerzenia i skrypty:**
Nano Defender 13.20
uBO v1.14.25rc1

**Filtry:**
1. POL: polskie filtry do Adblocka i uBlocka​​​​​
2. POL: polskie filtry do uBlocka uzupelnienie
3. Polskie filtry ciasteczkowe
4. KAD - Przekręty​
5. Adblock & uBlock polish filter - Adguard supplement
6. EasyList
7. Adblock Warning Removal List
8. Adguard Base Filters
9. uBlock filters
10. uBlock filters – Unbreak
11. Nano Defender Integration
12. NanoBase
13. NanoTimer
14. NanoWhitelist

**Comment by MajkiIT** [comment]
@Ravizz Dzięki
