### ISSUE TITLE
pan-doradca.pl

### ISSUE THREAD

**Issue by Ravizz** [MajkiIT/polish-ads-filter#5643]
### Zrzut ekranu
![](https://s3.dodajfote.pl/2018/01/19/www_pan-doradca_pl802589dae5126633.png)

> Zalecamy zamknięcie AdBlocka
> 
> W celu optymalnego korzystania z tej strony zalecamy zamknięcie Adblocka i przeładowanie tej strony.

### Link bezpośredni
Strona główna czyli http://www.pan-doradca.pl
lub jakiś artykuł np. http://www.pan-doradca.pl/korepetycje-jpolski/szafa-gra-pot.asp

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść bezpośrednio pod podany przykładowy link

### Moja konfiguracja
**Przeglądarka internetowa:**
FF 57.0.4 / O 50.0.2762.58 (PGO)

**Rozszerzenia i skrypty:**
Nano Defender 13.20
uBO v1.14.25rc1

**Filtry:**
1. POL: polskie filtry do Adblocka i uBlocka​​​​​
2. POL: polskie filtry do uBlocka uzupelnienie
3. Polskie filtry ciasteczkowe
4. KAD - Przekręty​
5. Adblock & uBlock polish filter - Adguard supplement
6. EasyList
7. Adblock Warning Removal List
8. Adguard Base Filters
9. uBlock filters
10. uBlock filters – Unbreak
11. Nano Defender Integration
12. NanoBase
13. NanoTimer
14. NanoWhitelist

Przykładowe rozwiązania:
1) Wyrwanie chwastu z korzeniami:
 `www.pan-doradca.pl##script:inject(setTimeout-defuser.js)`

lub

2) Zamiatanie pod dywan / ukrywanie czyli
! usunięcie komunikatu + usunięcie przyciemnionego tła):
`www.pan-doradca.pl##.in.noaidb.page-modal.fade.modal, .in.fade.modal-backdrop`  
! (można skrócić do `www.pan-doradca.pl##.in.noaidb, .modal-backdrop`)
! naprawa scrolla:
`www.pan-doradca.pl##.modal-open:style(overflow: auto!important;)`

**Comment by hawkeye116477** [comment]
Albo można po prostu dać taką regułę -> `||www.pan-doradca.pl/index/noaidb/*$xmlhttprequest` i wtedy będą zadowoleni również korzystający z AdBlocka :smile:.

**Comment by Ravizz** [comment]
@hawkeye116477: graty, dobra robota za wyłapanie tych rzeczy, umknęło mi to.
