### ISSUE TITLE
worms.fora.pl & qus.fora.pl

### ISSUE THREAD

**Issue by Ravizz** [MajkiIT/polish-ads-filter#5644]
Masywne i liczne dziury po reklamach

### Zrzut ekranu

Dwa przykładowe zrzuty: (cały komplet zrzutów zrzutów niżej w spojlerze):

![fora_worms](https://user-images.githubusercontent.com/35421792/35325089-0710db52-00f3-11e8-8742-038d3b96461e.png)

![fora_worms1b](https://user-images.githubusercontent.com/35421792/35325097-0b1e8168-00f3-11e8-9965-7b00e130ddc5.png)

<details>
  <summary>SPOJLER - WSZYSTKIE ZRZUTY EKRANU</summary>

Dziury po reklamach na stronach głównych czyli:

worms.fora.pl
![fora_worms](https://user-images.githubusercontent.com/35421792/35325133-214c18e2-00f3-11e8-94d9-bd2ea8f2e3f1.png)

qus.fora.pl:

![fora_qus1](https://user-images.githubusercontent.com/35421792/35325152-2ab16fae-00f3-11e8-8321-a85c53709571.png)

![fora_qus2](https://user-images.githubusercontent.com/35421792/35325163-2ffb1050-00f3-11e8-9c61-28b54abc338a.png)

oraz w przykładowych działach:

worms.fora.pl

![fora_worms1a](https://user-images.githubusercontent.com/35421792/35325174-38f02768-00f3-11e8-8d85-a8a250f20353.png)

![fora_worms2a](https://user-images.githubusercontent.com/35421792/35325179-3fc15166-00f3-11e8-8934-28aefcaa2924.png)

qus.fora.pl:

![fora_qus1a](https://user-images.githubusercontent.com/35421792/35325187-4b11bcf4-00f3-11e8-8441-53319442e9fd.png)

![fora_qus2a](https://user-images.githubusercontent.com/35421792/35325191-50a61368-00f3-11e8-9f9a-bf497d4128bd.png)

Dziuro-posty po reklamach między normalnymi postami w wątkach:

worms.fora.pl

![fora_worms1b](https://user-images.githubusercontent.com/35421792/35325210-5ba90c84-00f3-11e8-922f-2998ebd73090.png)

![fora_worms2b](https://user-images.githubusercontent.com/35421792/35325222-61441a26-00f3-11e8-8f7b-aeafb8c5b2ec.png)

![fora_worms3b](https://user-images.githubusercontent.com/35421792/35325232-66846810-00f3-11e8-83e3-9d211ca65724.png)

qus.fora.pl:

![fora_qus1b](https://user-images.githubusercontent.com/35421792/35325245-6dfa0a96-00f3-11e8-9a0b-99a0bb20ea66.png)

![fora_qus2b](https://user-images.githubusercontent.com/35421792/35325252-711a25ee-00f3-11e8-9e12-d93a40ab6a17.png)

![fora_qus3b](https://user-images.githubusercontent.com/35421792/35325253-72722950-00f3-11e8-87ec-5bffe06d16f2.png)

![fora_qus4b](https://user-images.githubusercontent.com/35421792/35325256-737d7566-00f3-11e8-82a6-94bf770a6c4f.png)

</details>

### Link bezpośredni
Dziury po reklamach na stronach głównych czyli:
http://www.worms.fora.pl/ 
http://www.qus.fora.pl
oraz w przykładowych działach:
http://www.worms.fora.pl/ogolnie-o-worms,17/
http://www.qus.fora.pl/ogolnie-o-wszystkich-czesciach-worms,30/
Dziuro-posty po reklamach między normalnymi postami w wątkach:
http://www.worms.fora.pl/ogolnie-o-worms,17/czy-ktos-gral-w-stare-wormsy-na-windows-7,399.html
http://www.qus.fora.pl/ogolnie-o-wszystkich-czesciach-worms,30/nt-zrobmy-najdluzszy-temat-na-fora-pl,3135.html

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść bezpośrednio pod podany przykładowy link

### Moja konfiguracja
**Przeglądarka internetowa:**
FF 57.0.4 / O 50.0.2762.58 (PGO)

**Rozszerzenia i skrypty:**
Nano Defender 13.20
uBO v1.14.25rc1

**Filtry:**
1. POL: polskie filtry do Adblocka i uBlocka​​​​​
2. POL: polskie filtry do uBlocka uzupelnienie
3. Polskie filtry ciasteczkowe
4. KAD - Przekręty​
5. Adblock & uBlock polish filter - Adguard supplement
6. EasyList
7. Adblock Warning Removal List
8. Adguard Base Filters
9. uBlock filters
10. uBlock filters – Unbreak
11. Nano Defender Integration
12. NanoBase
13. NanoTimer
14. NanoWhitelist

Przykładowe rozwiązanie:

! dziury po reklamach na stronach głównych i w działach:
`www.worms.fora.pl##tr:nth-of-type(6), tr:nth-of-type(7), tr:nth-of-type(55)`
`www.qus.fora.pl##tr:nth-of-type(6), tr:nth-of-type(29), tr:nth-of-type(53)`
! dziuro-posty po reklamach pomiędzy normalnymi postami w wątkach
`www.worms.fora.pl,www.qus.fora.pl##[id^="optS-"]`

**Comment by LArtCrime** [comment]
```
www.worms.fora.pl##tr:nth-of-type(6), tr:nth-of-type(7), tr:nth-of-type(55)
www.qus.fora.pl##tr:nth-of-type(6), tr:nth-of-type(29), tr:nth-of-type(53)
```

To by trzeba jakoś lepiej ogarnąć, bo u mnie wycięło by temat na pozycji 7.

**Comment by MajkiIT** [comment]
@Ravizz Dziękuję

**Comment by Ravizz** [comment]
@MajkiIT : A o co chodzi (dlaczego usunąłeś) tu: https://github.com/MajkiIT/polish-ads-filter/commit/8b449932a45e9f37ebdc77ef01c03c5b43b884ef ? Bo bez tych reguł są dziury.

**Comment by MajkiIT** [comment]
Bo plują stronę.

**Comment by Ravizz** [comment]
@MajkiIT: To dlaczego nie poinformowałeś od razu? (to bym poprawił)

Nowe reguły do wyboru:
`worms.fora.pl,qus.fora.pl##tr[height="280"], tr[height="300"]` lub
`worms.fora.pl,qus.fora.pl##[colspan][valign="middle"][align="left"]`

**Comment by Ravizz** [comment]
@MajkiIT co jest, dlaczego nie dodajesz, te nowe też coś psują?
