### ISSUE TITLE
astrosalus.pl

### ISSUE THREAD

**Issue by Ravizz** [MajkiIT/polish-ads-filter#5645]
Nie wyświetla się logo-baner własny strony, reguła powodująca błąd to: `astrosalus.pl##.ad`
(Nie jestem pewien czy to było zamierzone ukrycie tego banera, ale raczej to pomyłka, bo ten baner to logo własne, a nie reklama)

### Zrzut ekranu
Banera nie ma
![](https://s3.dodajfote.pl/2018/01/19/astralus1cb3834ee8e1d41f1.png)

Baner jest
![](https://s3.dodajfote.pl/2018/01/19/astralus2c8f9042168a74bf7.png)

### Link bezpośredni
http://astrosalus.pl

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść bezpośrednio pod podany przykładowy link

### Moja konfiguracja
**Przeglądarka internetowa:**
FF 57.0.4 / O 50.0.2762.58 (PGO)

**Rozszerzenia i skrypty:**
Nano Defender 13.20
uBO v1.14.25rc1

**Filtry:**
1. POL: polskie filtry do Adblocka i uBlocka​​​​​
2. POL: polskie filtry do uBlocka uzupelnienie
3. Polskie filtry ciasteczkowe
4. KAD - Przekręty​
5. Adblock & uBlock polish filter - Adguard supplement
6. EasyList
7. Adblock Warning Removal List
8. Adguard Base Filters
9. uBlock filters
10. uBlock filters – Unbreak
11. Nano Defender Integration
12. NanoBase
13. NanoTimer
14. NanoWhitelist

**Comment by MajkiIT** [comment]
Dziękuję
