### ISSUE TITLE
autocentrum.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5654]
![2018-01-20-niezalezny portal motoryzacyjny autocentrum pl](https://user-images.githubusercontent.com/5884000/35187227-b93df948-fe20-11e7-963f-7864f59e975f.png)

anty-adblock

moje filtry
easylist + polskie filtry

Adblock 3.22.1
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
@KonoromiHimaries u mnie jest ok. 
@xxcriticxx @hawkeye116477 zerkniecie ?

**Comment by hawkeye116477** [comment]
@MajkiIT Pewnie ma Nano Defendera.
`@@||www.autocentrum.pl/system/modules/adblock/js/advertisement.js` albo jeszcze lepsza reguła z Nano -> `@@/advertisement*.js$first-party,script` :smile:

**Comment by MajkiIT** [comment]
@hawkeye116477 pytanie czy jest sens to dublować .

**Comment by KonoromiHimaries** [comment]
@MajkiIT jest sporo lajków
```
https://www.wykop.pl/wpis/29455181/jedyna-znana-mi-polska-strona-ktora-nie-pokazuje-f/
```

**Comment by KonoromiHimaries** [comment]
myślę że tak
`https://www.wykop.pl/wpis/29455181/jedyna-znana-mi-polska-strona-ktora-nie-pokazuje-f/`

**Comment by hawkeye116477** [comment]
@MajkiIT Jest sens, bo zapewne nie wszyscy posiadają Nano Defendera.

**Comment by xxcriticxx** [comment]
@MajkiIT  u mie dziala ale ja mam nano pozdrowienia z las vegas
