### ISSUE TITLE
[ciacha] wykop.pl

### ISSUE THREAD

**Issue by maciejtarmas** [MajkiIT/polish-ads-filter#5655]
Wywala info o ciastkach na Wykopie.
<img width="1436" alt="screen shot 2018-01-20 at 23 39 15" src="https://user-images.githubusercontent.com/3435387/35188719-797b9af2-fe3b-11e7-98c0-6de1a24ab254.png">

**Comment by MajkiIT** [comment]
Dzięki

**Comment by hawkeye116477** [comment]
@maciejtarmas To już jest w Ciasteczkowych filtrach uzupełniających https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/cookies_uB_AG.txt, ale @maciejtarmas zapewne posiada uBo w wersji 1.14.24, który nie obsługuje dyrektywy #include, a więc wymagana jest subskrypcja tej dodatkowej listy.

**Comment by maciejtarmas** [comment]
My na Makach mamy wersję 1.14.14, bo aktualizacja do 1.14.24 (aktualna dla Safari) jest zwalona i nie idzie w żaden sposób.

**Comment by hawkeye116477** [comment]
@maciejtarmas Kto to "my"? Ale tak właściwie to przecież jest Firefox i Chrome na MacOS, więc możecie mieć nowszą wersję uBo albo nawet zainstalować Nano Adblocker :smile: .

**Comment by KonoromiHimaries** [comment]
![2018-01-21-krakow_ mniej meleksow zakaz nagabywania do klubow nocnych - wykop pl](https://user-images.githubusercontent.com/5884000/35189007-304a8e2c-fe42-11e7-9465-b020bb48a035.png)
`https://www.wykop.pl/link/4121437/krakow-mniej-meleksow-zakaz-nagabywania-do-klubow-nocnych/`

pusta sekcja + nie działa udostępnij

**Comment by maciejtarmas** [comment]
My, w sensie te kilkadziesiąt osób, które używają tego oficjalnie pobłogosławionego portu:

https://github.com/el1t/uBlock-Safari

Na Firefoksa bym się chętnie przesiadł, ale baterię zajeżdża w tempie ekspresowym (nawet jakiś bug report na to jest), a Chrome nie dotknę nawet kijem - Google i tak o mnie wie za dużo, mimo moich starań.

**Comment by KonoromiHimaries** [comment]
@maciejtarmas a ff quantum 58 z wyłączoną telemetrią?

**Comment by hawkeye116477** [comment]
@maciejtarmas Jest jeszcze Waterfox, Vivaldi, Opera, Ungoogled-chromium, Iridium i pewnie jeszcze jakieś inne forki, do wyboru do koloru :smile:

**Comment by maciejtarmas** [comment]
Wybrałem Safari. Taki masochista ze mnie :D

**Comment by hawkeye116477** [comment]
@maciejtarmas No najwyraźniej :smiley: Tak czy siak dyrektywa #include jest obecnie jedynie w uBo dev i Nano Adblockerze (ale o Nano nie ma co gadać, bo go pewnie raczej na Safari nie będzie, bo trzeba bulić 99$ za rok za certyfikat). Trochę może zbyt wcześnie zrobiłem ten podział na 2 listy, ale uznałem, że gorhill szybko da #include do stable, a jemu coś to wolno idzie najwyraźniej. A może są tacy co lubią czytać takie komunikaty, więc raczej to nie powinno być na głównej liście uzupełniającej, bo w sumie to w końcu na głównej liście nie ma reguł na te komunikaty :smiley:.

@KonoromiHimaries Pusta sekcja to resztka po reklamie, więc to robota dla @MajkiIT .
