### ISSUE TITLE
radiogra.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5658]
![2018-01-21-radio gra wroclaw](https://user-images.githubusercontent.com/5884000/35195383-e6a451dc-fec2-11e7-8f99-fba902ecc890.png)

strona nie działa

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.27
Nano Defender 13.22
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
@KonoromiHimaries Ja wszystko widzę.
@hawkeye116477 zerkniesz?

**Comment by HateAds** [comment]
@KonoromiHimaries @hawkeye116477 @KonoromiHimaries U mnie działa
![image](https://user-images.githubusercontent.com/29756590/35196750-79c3f310-fed6-11e7-8a03-cd093860fea2.png)

**Comment by xxcriticxx** [comment]
ja tez wszystko widze jestem na samolocie z las vegas
