### ISSUE TITLE
cda.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#5660]
Panowie macie ( https://www.cda.pl/video/54555737/vfilm ) reklamy w playerze ?
Wyczyściłem przeglądarke z cookies itd i mam reklamy w playerze na całym cda na Chromie.

**Comment by MajkiIT** [comment]
@HateAds mam już poprawiam

**Comment by HateAds** [comment]
@MajkiIT Dzięki za szybk odpowiedź Majk. Myślałem, że u mnie coś się rozwaliło w przeglądarce.

**Comment by MajkiIT** [comment]
Gotowe.
