### ISSUE TITLE
calcoolator.pl

### ISSUE THREAD

**Issue by Ravizz** [MajkiIT/polish-ads-filter#5661]
1_ Pierwsze 3 zrzuty ekranu:
Anty-adblock - komunikat na czerwonym tle w 3 miejscach na stronie z artykułami, i w 1 miejscu (na dole) na stronie głównej:
> Wygląda na to, że używasz programu do blokowania reklam!
> Calcoolator.pl utrzymywany jest wyłącznie z wyświetlania reklam.
> Będziemy wdzięczni, jeśli dodasz naszą stronę do wyjątków w filtrze blokującym reklamy.
> Z góry dziękujemy za zrozumienie.

Przykładowe rozwiązania:
a) `calcoolator.pl##script:inject(setTimeout-defuser.js, no-ads-info)` 
b) `calcoolator.pl##.ad-container:style(height: 1px!important;)` 
c) `||calcoolator.pl/inc/js/inc-js.js` - rozwiązanie najgorsze, niepolecane

2_ Ostatni zrzut ekranu:
Dodatkowo ostatni zrzut ekranu to inny komunikat adblock (typu popup) na tej samej stronie, 

> Wygląda na to, że używasz programu do blokowania reklam!
> 
> Calcoolator.pl utrzymywany jest wyłącznie z wyświetlania reklam.
> 
> Wyłączając blokowanie reklam docenisz pracę włożoną w budowę strony, podziękujesz za pomoc w uzyskaniu informacji, pomożesz w rozbudowie i utrzymaniu strony.
> Będziemy wdzięczni, jeśli dodasz naszą stronę do wyjątków w filtrze blokującym reklamy.
> Z góry dziękujemy za zrozumienie.

i on już jest blokowany przez listę Nano Defender, ale go wrzuciłem bo:
a) nie jestem pewien czy POL lista jest zależna czy nie od Nano Defender, w razie jeśli nie jest to właśnie dlatego wrzuciłem ten popup
b) niezależnie od powyższego, Nano Defender albo blokuje ten popup omyłkowo albo nieoptymalnie, oczywiście efekt jest bo popupa nie ma, ale zastosowane zostały fltry maskujące:
`###adbuddy-no-adb-container ` i `###adbuddy-overlay`
kiedy poprawniejszym filtrem jest: `||calcoolator.pl/inc/js/adblockill_copy.js`
czyli wyrwanie chwasta z korzeniami, więc niezależnie od a) i b) i tak trzeba ten filtr również dodać

### Zrzut ekranu
![calcoolator1a](https://user-images.githubusercontent.com/35421792/35326008-af2f9b50-00f5-11e8-83a0-05919929b50d.png)
![calcoolator1b](https://user-images.githubusercontent.com/35421792/35326009-af4dbc3e-00f5-11e8-8e2a-b90e48b9d32c.png)
![calcoolator1c](https://user-images.githubusercontent.com/35421792/35326010-af6bf1a4-00f5-11e8-876b-403788541814.png)
![calcoolator2](https://user-images.githubusercontent.com/35421792/35326011-af8a8d1c-00f5-11e8-9158-b5d3fe336e48.png)

### Link bezpośredni
(komunikat w 1 miejscu - na dole) czyli Strona główna:
http://calcoolator.pl
lub 
(komunikat w 3 miejscach) czyli jakiś artykuł np.:
http://calcoolator.pl/dzienny_kalkulator_kalorii.html

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść bezpośrednio pod podany przykładowy link

### Moja konfiguracja
**Przeglądarka internetowa:**
FF 57.0.4 / O 50.0.2762.58 (PGO)

**Rozszerzenia i skrypty:**
Nano Defender 13.20
uBO v1.14.25rc1

**Filtry:**
1. POL: polskie filtry do Adblocka i uBlocka​​​​​
2. POL: polskie filtry do uBlocka uzupelnienie
3. Polskie filtry ciasteczkowe
4. KAD - Przekręty​
5. Adblock & uBlock polish filter - Adguard supplement
6. EasyList
7. Adblock Warning Removal List
8. Adguard Base Filters
9. uBlock filters
10. uBlock filters – Unbreak
11. Nano Defender Integration
12. NanoBase
13. NanoTimer
14. NanoWhitelist
15. Polskie filtry elementów irytujących
16. Polskie filtry wewnętrzne

@MajkiIT tak z ciekawości: nie dodałeś tego żółtego tagu "adblock detect" do poprzedniego wątku:
https://github.com/MajkiIT/polish-ads-filter/issues/5643 (i być może do tego także nie dodasz), więc zapytam czy już przestałeś używać tego tagu, czy zapomniałeś?

**Comment by xxcriticxx** [comment]
@Ravizz pasuje?

**Comment by Ravizz** [comment]
@xxcriticxx nie wiem dlaczego ma mi pasować, bo o nic nie prosiłem, więc co zrobicie z tymi etykietami to wasza sprawa, ja jedynie poinformowałem w razie gdyby ktoś zapomniał ich dodać, w każdym bądź razie na pewno mi nie przeszkadza, a nawet pasuje, że etykiety zostały dodane.

**Comment by xxcriticxx** [comment]
@Ravizz yes sir!

**Comment by MajkiIT** [comment]
@Ravizz Zapomniałem dodać i tyle.

**Comment by Ravizz** [comment]
Dziwne, we wszystkich moich wątkach (poza tym jednym) poznikały zrzuty ekranu, gdy edytuję komentarz, skopiuję link od zrzutu (https://s3.dodajfote.pl/2018/01/18/swiatfilmow_comf3bebc8ab91f0098.png), a potem wkleję bezpośrednio do przeglądarki to pokazuje się błąd:


![](https://s4.dodajfote.pl/2018/01/24/errorf87c1a128cbc4fe0.png)

**Comment by Ravizz** [comment]
@MajkiIT : nad czym się tak zastanawiasz, masz podane działające filtry.

**Comment by MajkiIT** [comment]
Bo to powinno iść do filtrów Adblock, bo ludzie mają żal, że im wycina adblocki.

**Comment by Ravizz** [comment]
To niech się przesiądą na uBO...bo w AdBlocku to takie zamiatanie pod dywan, tak czy inaczej filtr pod AdBlock jak coś: `##.no-ads-info`

**Comment by MajkiIT** [comment]
@Ravizz Dodaje tą regułę a komu to przeszkadza to będzie robił sobie WL strony.  Nie chcę też robić protezy aby zaraz problemy były.

**Comment by Ravizz** [comment]
@MajkiIT OK, jeszcze to można dodać: ||calcoolator.pl/inc/js/adblockill_copy.js (pisałem o tym w pierwszym komentarzu)
