### ISSUE TITLE
wizaz.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5667]
![2018-01-22-strobing oczu - wizaz pl](https://user-images.githubusercontent.com/5884000/35203518-dc4d6b04-ff28-11e7-8fd4-0d442f1bf2f0.png)
`http://wizaz.pl/Makijaz/Jak-malowac-oczy`

reklama w lewym oku

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.24
Chrome 63.0.3239.132

**Comment by MajkiIT** [comment]
@KonoromiHimaries Niezły rodzyn :D
