### ISSUE TITLE
telewizor.eu/forum

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#5670]
Reklamy na dole

**Comment by MajkiIT** [comment]
```
telewizor.eu###block
telewizor.eu##div:nth-of-type(6) > p
```

**Comment by Ravizz** [comment]
Taka ciekawostka, tę kolorową reklamę na dole na głównej i na forum, Adguard Base Filters blokuje za pomocą: `##img[width="468"][height="60"]`

**Comment by MajkiIT** [comment]
@blocker999 miejsca na reklamę nie mogę zablokować, bo niby w ten sposób łamię ustawę o niewłaściwej konkurencji.
