### ISSUE TITLE
pasja-informatyki.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5672]
![2018-01-22-strona glowna - pasja informatyki](https://user-images.githubusercontent.com/5884000/35235002-30681e80-ffa3-11e7-9ac7-0bd6591fe128.png)

reklama

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.24
Chrome 63.0.3239.132

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/21376
