### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by Ravizz** [MajkiIT/polish-ads-filter#5673]
Jakiś problem: https://mozillapl.org/forum/viewtopic.php?f=24&t=49480

**Comment by KonoromiHimaries** [comment]
https://github.com/NanoAdblocker/NanoFilters/issues/3#issuecomment-358764658

**Comment by Martina-Neumayer** [comment]
@Ravizz Szczerze? To nie problem. To złośliwość. Kij im w te ich reklamy.. ale to obciążanie procka to przegięcie kompletne. W dodatku wypieranie się w żywe oczy "buu to nie my". Nie, kurr.. wróżki! :/
Czytałeś mój wątek na forum? Nie tylko ja to miałam, ale nas jakby inaczej zakrzyczano.
Olewam.. po prostu, jak tak dalej będzie, wywalę konto z dp i niech się cmokną. Moja bateria w lapku i w telu nie jest za darmochę. Sprzęt kosztuje kasę, a za wymianę nikt mi nie zwróci. Bo niestety strona klocka żre, a jak wiadomo to w konsekwencji żre baterie.
Przepraszam za dosłowność, ale jestem zwyczajnie zła na tą sytuację.

**Comment by Ravizz** [comment]
> Czytałeś mój wątek na forum?

Nie wiem, chyba nie, a jaki link?

Natomiast co do DP, to podobnie z WP też kiedyś były problemy, przez 2 lata walczono z reklamami, które co parę dni wyskakiwały w nowych miejscach, wątków z WP są tu setki:
https://github.com/MajkiIT/polish-ads-filter/issues?utf8=%E2%9C%93&q=WP
aż w końcu udało się uwalić injectem i jest od jakiegoś czasu święty spokój:
https://github.com/MajkiIT/polish-ads-filter/issues/4037#issuecomment-340295025
,nie wiem jak będzie z DP.

**Comment by Martina-Neumayer** [comment]
@Ravizz Jeden tu: https://forum.dobreprogramy.pl/t/strona-dp-nadmierne-uzycie-cpu-ram/551198
Drugi (niejako kontynuacja) tu: https://forum.dobreprogramy.pl/t/sady-i-przesady-z-reklamami-na-portalu/554964
Wpadłam właśnie na pomysł zblokowania całkiem dwu domen na routerze (criteo and wpimg) i coś jakby mniej zjada mi cpu. Steściam sobie właśnie.. zobaczę jak to będzie dalej ;)

**Comment by Ravizz** [comment]
> Powiedzcie mi proszę, czy wam także podczas otwierania DP skacze momentalnie i dość mocno użycie zasobów procka, czy to tylko u mnie się takie cudactwa wyprawiają?

U mnie nic takiego się nie dzieje, otworzyłem dla próby jednocześnie 3 karty z dobreprogramy: 
1 karta: strona główna 
2 karta: podany przez ciebie pierwszy link do forum + poprzewijałem żeby wszystkie komentarze się doładowały
3 karta: artykuł https://www.dobreprogramy.pl/Firefox-58-juz-jest-Aplikacje-w-przegladarce-nawet-kilkunastokrotnie-szybsze,News,85523.html + poprzewijałem żeby wszystkie komentarze się doładowały

Wszystkie karty ładowały się szybko i płynnie, średni czas ładowania każdej z kart od 1 do 2s, i podczas tego ładowania CPU skacze tylko na chwilę z idle do 50% i zaraz po załadowaniu wraca do idle, podczas przewijania strony i doładowywania komentarzy skacze do 30% i po chwili wraca do idle, krótko podsumowując, kompletnie żadnych problemów wydajnościowych z tą stroną u mnie nie ma.

Pod drugi link, który dałaś niestety nie wejdę, bo nie mam tam konta:

> Musisz się zalogować, aby zobaczyć ten temat.

**Comment by krystian3w** [comment]
Problem na Firefox 57.0.4 z tymi linkami do plików txt robi:

`dobreprogramy.pl##script:inject(abort-on-property-read.js, Element.prototype.attachShadow)`

Nie wiem może wystarczy dopisać `www.`, chyba że też blokuje forumowe reklamy to zostaje skrypt na dezaktywacje liczenia kliknięć lub sprawdzenie jak w Firefox 59 czy błąd wraca (w 58 nie występuje).

---

Może to bug na łatanie ![image](https://user-images.githubusercontent.com/35370833/35268419-5c0b32f8-0029-11e8-8ef7-96ae6399aeaf.png) Spectre i ![image](https://user-images.githubusercontent.com/35370833/35268376-385af91a-0029-11e8-8c79-ba6e16596b72.png) Meltdown...

**Comment by Martina-Neumayer** [comment]
@Ravizz Niestety u mnie na portalu (głównej) gdy mam wyłączonego Nano użycie jak włazi na wysoki poziom, tak nie spada. Póki nie włączę Nano. Wtedy owszem, schodzi do poziomu 13-15 i na nim się trzyma. Czasem jest nawet mniej. Ale bez blokera strona staje się nieużywalna. Strona, a nie forum. Forum działa okay obojętnie czy bloker jest włączony, czy nie.
Alle portal tak tnie, że po powiedzmy 15-20 minutach nie zrobisz już nic.
Na FF nie sprawdzałam, bo go nie mam. Używam jedynie Chrome. Ostatnia dostępna wersja z guglowych linuksowych repozytoriów.
I uprzedzę pytania.. system czysty, sprzęt sprawny. Nie jest to jakaś rakieta, bo zwykły lapciok, ale problemów nie sprawiał nigdy. Jedyne co - tak jak już to tam na forum wspomniałam - cyrki z obciążeniem pojawiły się zaraz po wprowadzeniu tych reklam opery. Już nie pamiętam, czy w ten sam dzień, czy na następny.. ale można by rzec, że praktycznie razem.

**Comment by krystian3w** [comment]
Niestety dalej się dokleja jakiś krótszy js (pobrane nowsze listy z dodany wyłączeniem po przez `!`).

```
forum.dobreprogramy.pl#@#script:inject(setTimeout-defuser.js, o = null, n || e.apply(r, i))
forum.dobreprogramy.pl#@#script:inject(abort-on-property-read.js, _0x373f)
```

**Comment by Ravizz** [comment]
@Martina-Neumayer: powtórzyłem testy z wyłączonym uBO & Nano Defenderem i dalej bez problemów u mnie, jeśli chcesz rozwiązać swój problem, to musisz podać dane z profilera:
https://translate.google.pl/translate?sl=en&tl=pl&js=y&prev=_t&hl=pl&ie=UTF-8&u=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FMozilla%2FPerformance%2FReporting_a_Performance_Problem&edit-text=&act=url

**Comment by Martina-Neumayer** [comment]
@Ravizz A zerknę w wolniejszej chwili.
I nie musisz mi wklejać tłumaczonego.. nie mam problemów z j. angielskim ;)
Z FF nie sprawdzę, ponieważ nie wolno mi instalować na tym lapcioczku nic innego, poza tym co jest. To służbówka.

**Comment by Ravizz** [comment]
@Martina-Neumayer: OK

Co do angielskiego to fakt, sorry, zupełnie zapomniałem, że znasz angielski, bo udzielałaś się po angielsku np. tu.: https://github.com/NanoAdblocker/NanoFilters/issues/3, wyleciało mi z głowy.

Co do FF, to dobrze wiem, że masz służbówkę i nie możesz nic instalować, tego akurat nie zapomniałem, dlatego napisałem przecież żeby:

>  podać dane z profilera na Chrome

A link do profilera pod FF był tylko dla przykładu

> tak jak np. 

więc może jakieś czytanie ze zrozumieniem...

Bywaj towarzyszko.

**Comment by Martina-Neumayer** [comment]
@Ravizz Spoksik.. pisałam w biegu, zalatana dziś byłam kosmicznie. Dopiero co usiadłam na pupie. Także się nie gniewaj ;)
Co do profillera, patrzyłam i jakby coś od któregoś js'a ale co dokładnie.. ciężko wyczaić. Naćkane jest niesamowicie i odpuściłam jakieś głębsze szukanie. Nie mam dziś na to mocy ;)

**Comment by xxcriticxx** [comment]
ummm o co tutaj biega?

**Comment by Ravizz** [comment]
@Martina-Neumayer:
spoko, a co do sugerowania/imputowania że niby gniewam się, to z twojej strony bezczelność/hipokryzja/odwracanie kota ogonem/przyganiał kocioł garnkowi... gdybym był taki złośliwy jak ty, to bym ci wcześniej to samo napisał, czyli: nie gniewaj się (o te linki po polsku)...

A teraz trochę zbytów z ciebie:

> pisałam w biegu

Biegłaś z laptopem, w jednej ręce go trzymałaś, a drugą pisałaś...no to nadajesz się na kelnerkę, do biegania z talerzami.

> pisałam w biegu, zalatana dziś byłam

To w końcu biegałaś czy latałaś? Zdecyduj się.
A może bieg i lot na przemian?
Zalatana kosmicznie, a którym promem kosmicznym latałaś?

> ciężko wyczaić

Trudno, a nie ciężko, ciężko to może być wstać z łóżka...

narq

**Comment by KonoromiHimaries** [comment]
@xxcriticxx chyba jakieś zaloty

**Comment by xxcriticxx** [comment]
this will end right now!
