### ISSUE TITLE
ewa-gotuje.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5682]
cookies

Strona wykorzystuje pliki cookies, które są zapisywane na komputerze Użtkownika. Więcej szczegółów w Polityka prywatności

**Comment by hawkeye116477** [comment]
@xxcriticxx @MajkiIT Tyle, że to statyczne, no i nie da rady tego schować bez ukrycia headera.

**Comment by xxcriticxx** [comment]
dokladnie zamykamy?
