### ISSUE TITLE
przepis-kulinarny.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5683]
cookies 

Strona wykorzystuje pliki cookies, które są zapisywane na komputerze Użtkownika. Więcej szczegółów w Polityka prywatności

**Comment by KonoromiHimaries** [comment]
ohh mógłbyś ciasteczkowe zgłaszać na discordzie, a github zostawić do spraw poważnych.

**Comment by MajkiIT** [comment]
@KonoromiHimaries a czemu tak ?

**Comment by xxcriticxx** [comment]
@KonoromiHimaries doklanie co to za nowosc?

**Comment by KonoromiHimaries** [comment]
@xxcriticxx majki nie ma czasu na głupoty.

**Comment by xxcriticxx** [comment]
@MajkiIT matt twierdzi ze nie masz czasu prawda?

**Comment by KonoromiHimaries** [comment]
no tak twierdze. bo gdyby miał to już dawno by wprowadził wszystkie moje świetne pomysły w życie. a tak tłumaczy mi że nie ma na to czasu. więc ja staram się jak mogę trochę tego czasu wygospodarować.

**Comment by MajkiIT** [comment]
Nie mam czasu na 50 zgłoszeń na raz, ale na dawanie etykiet zawszę znajdę czas, poza tym @xxcriticxx sam dodaje etykiety. Dla mnie GitHUB jest lepszy, bo nic nie ucieka. Widać nad czym się pracuje itp.

**Comment by xxcriticxx** [comment]
@KonoromiHimaries musisz sie wziasc za to co podajesz jakosc ma byc lepsza :)

**Comment by KonoromiHimaries** [comment]
@xxcriticxx nie rozumiem aluzji

**Comment by xxcriticxx** [comment]
@KonoromiHimaries tresc zgloszen ma byc lepsza

**Comment by KonoromiHimaries** [comment]
@xxcriticxx proszę o przykład

**Comment by xxcriticxx** [comment]
@KonoromiHimaries mniej zenecznych i wewnetrzych i donacjie a wiecej reklam i takiej akje jak z dobreprogramy

**Comment by KonoromiHimaries** [comment]
@xxcriticxx od jakiegoś czasu prawie wcale nie zgłaszam takich rzeczy.

weź mnie nie szkaluj : /
szukasz na siłę czegoś żeby móc się mnie czepiać

**Comment by xxcriticxx** [comment]
@KonoromiHimaries jaja sobie robie poprostu jest za duzo zgloszen i @MajkiIT nie wyrabia z nowymi filtrami

**Comment by KonoromiHimaries** [comment]
@xxcriticxx ale to ja się zajmuje filtrami wewnętrznymi. tak samo hawk zajmuje się cookie i nie ma co majka do tego mieszać. po prostu chciałem żebyś wbił do nas na discorda i zobaczył jak się tam pozmieniało.

no i ten jak zamykasz jakąś rozmowę, ucinasz czy coś. to również mógłbyś zapraszać na discorda, żeby nie zostawiać pustki tak jak to zrobiłeś tutaj `https://github.com/MajkiIT/polish-ads-filter/issues/5673`

**Comment by KonoromiHimaries** [comment]
@MajkiIT majki jak masz czas to napisz do hawka by przeimigrował z filtrami elementów irytujących do twojego repo.

**Comment by xxcriticxx** [comment]
@KonoromiHimaries my dzialamy na githabie why sie dobrze bawcie na discourse

**Comment by hawkeye116477** [comment]
Nie będę migrował, bo wtedy link się zmieni i starzy użytkownicy nie będą mieli dostępu.

**Comment by MajkiIT** [comment]
@hawkeye116477 Mówisz i masz :P 

> ! Redirect: http://example.com/list.txt
> 
> This comment indicates that the filter list has moved to a new download address. Adblock Plus will ignore any file contents beyond that comment and immediately try downloading from the new address. In case of success the address of the filter list will be updated in the settings. This comment is ignored if the new address is the same as the current address, meaning that it can be used to enforce the "canonical" address of the filter list.

**Comment by hawkeye116477** [comment]
@MajkiIT Ale to nie działa w uBo ani Nano.

**Comment by hawkeye116477** [comment]
@MajkiIT To raczej do zamknięcia. No chyba, że uważacie, że to dobry pomysł, by dać font-size na 0 dla headera.

**Comment by Ravizz** [comment]
> @MajkiIT :ale na dawanie etykiet zawszę znajdę czas

@MajkiIT : 

No coś nie bardzo, tak przeleciałem repo i jest sporo zgłoszonych stron (wątków), bez żadnej etykiety (oczywiście nie piszę tu o wątkach które nie kwalifikują się do nadania im etykiety - bo takie też są, lecz o tych, którym brakuje etykiet i powinny je mieć). 

Jeśli dałbyś mi na kilka dni możliwość nadawania etykiet, to chętnie bym pouzupełniał całe repo o brakujące etykiety, oczywiście nie chodzi mi o etykiety dodać / dodać do filtrów ublock / reguły gotowe/testowanie itp. bo to twoja działka, ale pozostałe etykiety, te informujące o rodzaju zgłoszenia.

**Comment by KonoromiHimaries** [comment]
@Ravizz chcesz to możesz pomóc zindexować listy wewnętrzną i dotacyjną

zapraszam
https://github.com/KonoromiHimaries/polish-ads-filter/tree/master/inside-filters

szczegóły możemy obgadać na discordzie
https://discord.me/polskiefiltry

**Comment by MajkiIT** [comment]
@Ravizz dodaje etykiety do tych zgłoszeń które pozostają. Te które od razu rozwiązuje nie klikam. Jakoś nie widzę sensu. W 90% i tak temat nie wróci.

**Comment by Ravizz** [comment]
@MajkiIT: ja widzę pewien sens, bo chodzi o statystyki, ile jest zgłoszeń danego rodzaju, czego jest najwięcej na stronach, wystarczy, że kliknie się na etykietę, i github wyszukuje i pokazuje wszystkie zgłoszenia tego typu, po prostu to jest ciekawa wiedza i materiał statystyczny, a czasem nawet może się przydać do rozwiązania bieżącego podobnego problemu, tobie to niepotrzebne, ale innym może się przydać, więc mam prośbę, żebyś dał mi na kilka dni możliwość etykietowania, przecież nikomu nie zaszkodzi uzupełnienie etykiet.
