### ISSUE TITLE
bramka-proxy.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#5684]
cookies 

Aby działać lepiej nasz serwis korzysta z plików cookie. Czym są cookie, do czego są wykorzystywane i jak je wyłączyć znajdziesz tutaj.Zamknij

**Comment by hawkeye116477** [comment]
`bramka-proxy.pl##div[style="font-family: Tahoma; margin-bottom: 6px; padding: 5px; font-size: 10px; color: rgb(0, 0, 0); background-color: rgb(204, 204, 204); border-bottom: 1px solid black;"]`

**Comment by Ravizz** [comment]
Tak będzie prościej: `||www.bramka-proxy.pl/themes/default/cookies.js`
