### ISSUE TITLE
Alltube.tv

### ISSUE THREAD

**Issue by AndrzejAA** [MajkiIT/polish-ads-filter#5687]
Witam, część odtwarzaczy z których oglądam filmiki przestała działać. Mianowicie cda.pl oraz streamango.com, możliwe że jest ich jeszcze kilka.

**Comment by MajkiIT** [comment]
@AndrzejAA Zaktualizuj filtry. Dziękuję za informację.

**Comment by MajkiIT** [comment]
@AndrzejAA jeszcze mały szlif.
