### ISSUE TITLE
dom.wp.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#5691]
https://dom.wp.pl/silikonowe-akcesoria-kuchenne-szkodza-prawda-i-mity-6210330028205697a

![image](https://user-images.githubusercontent.com/35370833/35342802-40d78332-0129-11e8-9605-2e308af9abee.png)

Reklamy gier online nad nawigacją.

[nano-kopia-zapasowa_2018-01-24_17.09.23.txt](https://github.com/MajkiIT/polish-ads-filter/files/1660551/nano-kopia-zapasowa_2018-01-24_17.09.23.txt)

**Comment by Ravizz** [comment]
@krystian3w: https://github.com/MajkiIT/polish-ads-filter/issues/4037#issuecomment-360187926
