### ISSUE TITLE
ekino-tv.pl

### ISSUE THREAD

**Issue by Ravizz** [MajkiIT/polish-ads-filter#5693]
Po wciśnięciu play (zrzut ekranu 1), wyskakuje timer (zrzut ekranu 2):

> Materiał dostępny będzie za: 4 sek.

http://ekino-tv.pl/movie/show/matrix-rewolucje-the-matrix-revolutions-2003-lektor/837

Zrzut ekranu 1:
![kino1](https://user-images.githubusercontent.com/35421792/35355838-e5bda258-014e-11e8-9ba2-049134c153d9.png)

Zrzut ekranu 2:
![kino2](https://user-images.githubusercontent.com/35421792/35355842-e885053a-014e-11e8-8cf3-fed14db87b81.png)

**Comment by MajkiIT** [comment]
@Ravizz noi co z tym ?

**Comment by hawkeye116477** [comment]
Zapewne chodzi o przyśpieszenie timera, `nano-setTimeout-booster.js`, `nano-setInterval-booster.js` i te sprawy.

**Comment by xxcriticxx** [comment]
@hawkeye116477 potrzebny do tego script czy nano ma bypass

**Comment by hawkeye116477** [comment]
@xxcriticxx Nano posiada takie reguły, uBlock też ma podobne zdaje się -> `setInterval-defuser.js` i `setTimeout-defuser.js`.

**Comment by xxcriticxx** [comment]
@hawkeye116477 dziala na tej stronie?

**Comment by hawkeye116477** [comment]
@xxcriticxx Ta, działa -> `ekino-tv.pl##script:inject(nano-setTimeout-booster.js)`, ale to tylko reguła dla Nano, dla uBlocka niestety nie wiem co wykombinować, tam chyba nie ma tak prosto :smile:.

**Comment by xxcriticxx** [comment]
mysle ze wystarczy dla @Ravizz 

@hawkeye116477 thank you for your continuous support

**Comment by Ravizz** [comment]
> @MajkiIT: @Ravizz noi co z tym ?

Dziwne pytanie, jak to co, no przecież timer wyzerować.

Propozycja @hawkeye116477 załatwia sprawę.
