### ISSUE TITLE
cryptonews.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5704]
![2018-01-26-cryptonews pl bitcoin litecoin _ bitcoin informacje - news _ kryptowaluty](https://user-images.githubusercontent.com/5884000/35417090-24b5c69c-022c-11e8-9f61-da81f72f5eec.png)

puste sekcje polecamy i subskrybuj

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.25
Chrome 64.0.3282.119

**Comment by MajkiIT** [comment]
@KonoromiHimaries polecamy to reklama a subskrybuj ukrywa @hawkeye116477 w irytujących.

**Comment by hawkeye116477** [comment]
Jaki błąd, to są po prostu niedojedzone resztki :smile:
