### ISSUE TITLE
mybboard.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#5724]
### Zrzut ekranu

![screenshot-2018-1-26 mybb pl - polskie wsparcie techniczne](https://user-images.githubusercontent.com/18230443/35445680-a954f4e6-02b2-11e8-9c7b-83e377925cae.png)
![screenshot-2018-1-26 inne ikony przy dzialach - mybb pl](https://user-images.githubusercontent.com/18230443/35447723-b6f06800-02b8-11e8-8884-05300006317c.png)

### Link bezpośredni

https://mybboard.pl/index.php (banner w headerze)
https://mybboard.pl/thread-73634.html (banner pod postem)

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na stronę

### Moja konfiguracja
**Przeglądarka internetowa:**
Firefox 59.0b3

**Rozszerzenia i skrypty:**
1. uBlock
2. Nano Defender

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. EasyList

**Comment by RikoDEV** [comment]
Filtr wycina logo strony @MajkiIT

**Comment by hawkeye116477** [comment]
@MajkiIT Do usunięcia -> `mybboard.pl##a[href^="https://"] > IMG`.

**Comment by lukasamd** [comment]
Jako właściciel MyBB PL muszę zapytać - dlaczego ta "reklama" jest w ogóle blokowana? Nie jest animowana, nie jest upierdliwa, nie śledzi użytkownika (to zwykły obrazek z linkiem), nie ładuje dodatkowych skryptów, jest za to tematycznie związana z serwisem. Ok, ja wiem, jakie zamierzenia ma adbock, ale fuckup jaki tu zrobiono (blokada loga) pokazuje, że chyba ktoś mocno przesadza.

Proszę o informację co tu nie pasuje - jeśli nie będzie argumentów, niestety będę musiał powalczyć z adblockiem bo takie działanie IMO nie ma żadnego sensu.

**Comment by KonoromiHimaries** [comment]
@lukasamd wiele się ostatnio pozmieniało. od niedawna partnerów i afiliacje również agregujemy w naszych listach.

nie mamy nic wspólnego z firmą `eyeo GmbH` i nie prowadzimy programu `Acceptable Ads`.
