### ISSUE TITLE
app.convertiser.com/publisher/dashboard

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#5734]
E niee no tak się nie robi Xd smutna bożka na cały ekran? Xd to już przesada bez jaj 

![screenshot_1](https://user-images.githubusercontent.com/21177361/35476303-bd9f64b2-03ad-11e8-9258-6f29106c2bad.png)

**Comment by hawkeye116477** [comment]
`@@||app.convertiser.com/scripts/*.advert.js`

**Comment by gzenio22** [comment]
@hawkeye116477 przekierujesz? szczerze? maly monit o adblocku bym olal ale to? beez przesadyzmu

**Comment by hawkeye116477** [comment]
@gzenio22 https://forums.lanik.us

**Comment by krystian3w** [comment]
Do białej listy: "`@@||`".
