### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5744]
![2018-01-28-znakomity start piotra liska w berlinie zwyciestwo i minimum na ms - wp sportow](https://user-images.githubusercontent.com/5884000/35479177-367d059a-03f1-11e8-9ec1-2b657435e4aa.png)
`https://sportowefakty.wp.pl/alpinizm/734700/przyjaciel-elisabeth-revol-dziekuje-wszystkim-polakom-i-dziele-wasz-potezny-bol`

reklama w sekcji polecane

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.27
Chrome 64.0.3282.119

**Comment by MajkiIT** [comment]
na głównej nic nie ma

**Comment by Ravizz** [comment]
U mnie też czysto (na moich ustawieniach):

<details>
  <summary>moje ustawienia</summary>

![capture_013_28012018_150428](https://user-images.githubusercontent.com/35421792/35482973-9401faae-043c-11e8-861e-c34e9ff4a7b7.png)

</details>
.
<details>
  <summary>moje ustawienia</summary>

```
O 50.0.2762.67 (PGO) & 
uBO 1.14.25.101 & 
ND 13.27

Adblock & uBlock polish filter - Adguard supplement​​
Adblock Warning Removal List​
Adguard’s Annoyance List​
Adguard Base Filters​
AlleBlock
EasyList​
Fanboy’s Annoyance List​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​
Fanboy’s Cookiemonster List​
Fanboy’s Social Blocking List​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt​​
I don't care about cookies​​
KAD - Przekręty
Nano Defender Integration​​
POL: polskie filtry do Adblocka i uBlocka​
POL: polskie filtry do uBlocka uzupelnienie​
Polskie filtry anty-dotacyjne​​
Polskie filtry ciasteczkowe​​
Polskie filtry elementów irytujących
Polskie filtry społecznościowe​​
Polskie filtry społecznościowe - uzupełnienie do uBlocka i AdGuarda​​
Polskie filtry wewnętrzne
uBlock filters​
uBlock filters – Annoyances​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
```

</details>

**Comment by KonoromiHimaries** [comment]
między polecanymi
`https://sportowefakty.wp.pl/alpinizm/734700/przyjaciel-elisabeth-revol-dziekuje-wszystkim-polakom-i-dziele-wasz-potezny-bol`

**Comment by HateAds** [comment]
@MajkiIT @KonoromiHimaries @Ravizz Wejdźcie w artykuł tutaj przykładowop https://sportowefakty.wp.pl/skoki-narciarskie/735926/piotr-zyla-trener-powiedzial-ze-teraz-musze-go-sluchac
U mnie jest reklama jak na srceenie
![1](https://user-images.githubusercontent.com/29756590/35783068-087c03b4-0a02-11e8-8feb-5ae7a485b5f8.png)

**Comment by xxcriticxx** [comment]
posiadam takie same reklamy w polecone jak @HateAds ma na zdjeciach

**Comment by MajkiIT** [comment]
@HateAds @xxcriticxx update i można testować.

**Comment by KonoromiHimaries** [comment]
![2018-02-05-piotr zyla_ trener powiedzial ze teraz musze go sluchac - wp sportowefakty](https://user-images.githubusercontent.com/5884000/35831278-70da34cc-0ac9-11e8-9d8f-44457235533e.png)
`https://sportowefakty.wp.pl/skoki-narciarskie/735926/piotr-zyla-trener-powiedzial-ze-teraz-musze-go-sluchac`

pusta sekcja reklama

**Comment by xxcriticxx** [comment]
po updacje dalej mam reklamy + push

![capture](https://user-images.githubusercontent.com/15007183/35832000-9fcb16f0-0a99-11e8-8d36-cc4258d6fbf6.PNG)

**Comment by MajkiIT** [comment]
https://www.screencast.com/t/92OQ3zYKgE u mnie jest ok. 

push jest @hawkeye116477

**Comment by xxcriticxx** [comment]
ta reklama caly czas gdzies indziej sie pokazuje skacze w tych poleconych

**Comment by hawkeye116477** [comment]
Push jest już blokowany przez Polskie filtry elementów irytujących :smile:.

**Comment by MajkiIT** [comment]
@xxcriticxx ja nie blokuje pola wybranego, tylko element o pewnej charakterystyce.

**Comment by HateAds** [comment]
Mogę potwierdzić to co @xxcriticxx napisał. Ta reklama zmienia miejsce w polecanych co jakiś czas po odświeżeniu strony.

**Comment by HateAds** [comment]
@MajkiIT Napis reklama zniknął i w większości blokuje dobrze, ale przykładowo tutaj ( https://sportowefakty.wp.pl/mma/wideo/31047/klatka-po-klatce-17-owczarz-i-narkun-przed-gala-ksw-42-wideo  ) wciąż można wejść w link gdzie jest reklama.
![2](https://user-images.githubusercontent.com/29756590/35858186-d6a93da8-0b3b-11e8-9327-3ca5a0ef3763.png)

**Comment by MajkiIT** [comment]
U mnie blokuje ... a dokładniej ukrywa

**Comment by HateAds** [comment]
@MajkiIT Ja wyczyściłem dane przeglądarki, cookies itd. U mnie cały czas się wyświetlają te linki do reklam, jedynie co na nich zniknęło to napis reklama.

**Comment by MajkiIT** [comment]
@HateAds a takie coś?
```
sportowefakty.wp.pl##a[href*=".wp.pl"] > .articleteaser__title
sportowefakty.wp.pl##a[href*=".wp.pl/"] > .inview.articleteaser__photo
```

**Comment by HateAds** [comment]
@MajkiIT Chyba to będzie dobre. Potestuję jeszcze, ale na razie z tego co widzę to te reguły zablokowały te linki z reklamami.

**Comment by HateAds** [comment]
@MajkiIT Po załadowaniu tych reguł i kilkukrotnym odświeżaniu strony w większości przypadków reklamy się pochowały, ale potrafią jeszcze wyskoczyć 
![1](https://user-images.githubusercontent.com/29756590/35991381-56110e6e-0d07-11e8-9d5b-68c658630c37.png)

**Comment by HateAds** [comment]
@MajkiIT Po dłuższej obserwacji reklamy w polecanych się pochowały i na ten moment żadnej nie widzę, ale przy okazji inny problem się pojawił.
Kilka razy sprawdzałem i po którymś wejściu z kolei w artykuł X przykładowo ten https://sportowefakty.wp.pl/pilka-nozna/736656/neymar-zarabia-krocie-w-social-mediach
Jak zjedziesz na SAM DÓŁ to czasami video się nie pojawia
<details>

![image](https://user-images.githubusercontent.com/29756590/36004490-48c261be-0d33-11e8-9a96-ee3034a7f804.png)

</details>

**Comment by MajkiIT** [comment]
@HateAds Dziękuję za info. Potestuj proszę tą regułę a ja jakoś ją dopracuje aby była bardziej optymalna. Co do tego filmiku to poklimam i posprawdzam.
