### ISSUE TITLE
[Off-topic] YouTube - kryptowaluty.

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#5782]
http://antyweb.pl/youtube-monero-miner-kryptowaluty/
Wrzucam jako ciekawostkę, sam problem ponoć został rozwiązany przez "Guggla" ale to tylko pokazuje, że w dzisiejszych czasach używanie różnych blockerów to konieczność.

**Comment by MajkiIT** [comment]
@HateAds wszędzie chcą coś wykopać i nabić kasę, ale to staje się to plagą.

**Comment by HateAds** [comment]
@MajkiIT U mnie na dość starym komputerze jak mam 100% obciążenia procesora to nie mogę nic zrobić. Dzięki bogu, że są możliwości żeby to blokować.

**Comment by MajkiIT** [comment]
@HateAds ale ja to wiem. Nawet jak ktoś ma nowego kompa to też szkoda aby ktoś korzystał z twojego procesora.

**Comment by HateAds** [comment]
Wiadomo, że jest tak jak napisałeś, też bym nie chciał, żeby na moim nowym kompie z procka ktoś korzystał. Niestety dziś mamy takie czasy, że kopią gdzie się dać i trzeba kontrolować jaki % procka zjada strona x.
