### ISSUE TITLE
softhard.com.pl

### ISSUE THREAD

**Issue by Ravizz** [MajkiIT/polish-ads-filter#5791]
reklama:   http://www.softhard.com.pl/serwis

![capture_033_28012018_160131](https://user-images.githubusercontent.com/35421792/35483601-7f2638e0-0444-11e8-8d53-2df62c9aabfd.png)

<details>
  <summary>moje ustawienia</summary>

```
O 50.0.2762.67 (PGO) & 
uBO 1.14.25.101 & 
ND 13.27

Adblock & uBlock polish filter - Adguard supplement​​
Adblock Warning Removal List​
Adguard’s Annoyance List​
Adguard Base Filters​
AlleBlock
EasyList​
Fanboy’s Annoyance List​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​
Fanboy’s Cookiemonster List​
Fanboy’s Social Blocking List​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt​​
I don't care about cookies​​
KAD - Przekręty
Nano Defender Integration​​
POL: polskie filtry do Adblocka i uBlocka​
POL: polskie filtry do uBlocka uzupelnienie​
Polskie filtry anty-dotacyjne​​
Polskie filtry ciasteczkowe​​
Polskie filtry elementów irytujących
Polskie filtry społecznościowe​​
Polskie filtry społecznościowe - uzupełnienie do uBlocka i AdGuarda​​
Polskie filtry wewnętrzne
uBlock filters​
uBlock filters – Annoyances​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
```

</details>

**Comment by MajkiIT** [comment]
to strona firmy

**Comment by Ravizz** [comment]
? Gdzie tu widzisz stronę firmy, ta reklama na dole prowadzi do: https://www.microsoft.com/pl-pl/

**Comment by MajkiIT** [comment]
To strona firmy softHard która jest partnerem MS

**Comment by Ravizz** [comment]
Nie pomyliłeś przypadkiem czasu przeszłego z teraźniejszym? Była strona, ale już nie ma:

> We are sorry, the page you requested cannot be found.
> 
> The URL may be misspelled or the page you're looking for is no longer available.

![capture_221_07022018_085525](https://user-images.githubusercontent.com/35421792/35904768-aba520e6-0be4-11e8-9885-89b054ecb498.png)

**Comment by KonoromiHimaries** [comment]
błąd strony. zgłoś to za pomocą formularza kontaktowego:
`http://www.softhard.com.pl/kontakt#formularz`
