### ISSUE TITLE
tychy.naszemiasto.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#5796]
czy na stronie tychy.naszemiasto.pl, musi byc puste miejsce, ponizej strony?

**Comment by MajkiIT** [comment]
@lukjan32 dasz jakiś zrzut, bo ja tego nie widzę.

**Comment by lukjan32** [comment]
prosze
![1](https://user-images.githubusercontent.com/17565773/35486729-903e0620-0472-11e8-85ec-251eaef2b4c4.jpg)

**Comment by MajkiIT** [comment]
Niestety nawet jak wyłączysz blokowanie reklam to tak jest. Tak stronę ktoś zbudował.

**Comment by lukjan32** [comment]
aha, trzeba do nich napisac?

**Comment by MajkiIT** [comment]
Hmmm no można ale nie wiem czy zgodzą coś zmienić.

**Comment by lukjan32** [comment]
ok. napisalem.

**Comment by Lukjan38** [comment]
nie dziala logowanie, po wylaczeniu ublock origin jest ok.
