### ISSUE TITLE
Change URLs for Polish filters

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#580]
https://github.com/AdguardTeam/AdguardForWindows/issues/992

**Comment by MajkiIT** [comment]
Dziękuję,

**Comment by xxcriticxx** [comment]
dodaj ich logo to facebook albo website

**Comment by MajkiIT** [comment]
Tak zrobię, Dzięki za podpowiedź.

**Comment by xxcriticxx** [comment]
you welcome sir
