### ISSUE TITLE
gry-online.pl

### ISSUE THREAD

**Issue by Ravizz** [MajkiIT/polish-ads-filter#5803]
Timer, przykładowy link (example url): https://www.gry-online.pl/S030.asp?ID=15943

Po kliknięciu przycisku "Pobierz plik za darmo"
(After clicking at "Download file for free" button):

![capture_007_29012018_174829](https://user-images.githubusercontent.com/35421792/35522418-8f369814-051c-11e8-848d-55d5e5ca1d8e.png)

Wyskakuje przycisk "Czekaj" i propozycja wykupienia konta Premium
("Wait" button appears together with buy Premium account offer if you don't want to wait):

> Pobieranie Premium
> 
> Pobieranie Premium pozwala Ci pobrać plik na swój dysk lokalny bez czekania, z maksymalną prędkością łącza i bez innych ograniczeń.
> 
> Pobieranie Premium jest częścią Abonamentu Premium na GRYOnline.pl

> 
> Premium download
> 
> Premium download allows you to download the file to your local drive without waiting, at the maximum link speed and without any other restrictions.
> 
> Premium download is part of the Premium subscription for GRYOnline.pl

![capture_005_29012018_174551](https://user-images.githubusercontent.com/35421792/35522301-3a9f43aa-051c-11e8-9555-541a042636e9.png)

A tak wygląda gdy Timer się skończy - pojawiają się 2 przyciski "Pobierz z serwera Alamo / Krypta"
(And this is how it looks after Timer is out, 2 buttons appear "Download from Alamo / Krypta server"):

![capture_008_29012018_175114](https://user-images.githubusercontent.com/35421792/35522543-f21f9d40-051c-11e8-8d5f-c65a62823390.png)

<details>
  <summary>moje ustawienia</summary>

```
O 50.0.2762.67 (PGO) & 
uBO 1.14.25.101 & 
ND 13.28

Adblock & uBlock polish filter - Adguard supplement​​
Adblock Warning Removal List​
Adguard’s Annoyance List​
Adguard Base Filters​
AlleBlock
EasyList​
Fanboy’s Annoyance List​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​
Fanboy’s Cookiemonster List​
Fanboy’s Social Blocking List​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt​​
I don't care about cookies​​
KAD - Przekręty
Nano Defender Integration​​
POL: polskie filtry do Adblocka i uBlocka​
POL: polskie filtry do uBlocka uzupelnienie​
Polskie filtry anty-dotacyjne​​
Polskie filtry ciasteczkowe​​
Polskie filtry elementów irytujących
Polskie filtry społecznościowe​​
Polskie filtry społecznościowe - uzupełnienie do uBlocka i AdGuarda​​
Polskie filtry wewnętrzne
uBlock filters​
uBlock filters – Annoyances​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
```

</details>

**Comment by MajkiIT** [comment]
@hawkeye116477 Mistrzu od timerów, zerkniesz?

**Comment by hawkeye116477** [comment]
@MajkiIT Nie jestem misrzem od timerów, po prostu zerknąłem na listę pingwina i akurat tamta reguła pasowała. W tym przypadku to niestety, ale `gry-online.pl##script:inject(nano-setTimeout-booster.js)` nie chce to działać poprawnie, tzn. czas owszem idzie do przodu, ale potem nie pokazują się linki do pobierania. Także chyba trzeba będzie spytać o pomoc pingwina.

**Comment by Ravizz** [comment]
@MajkiIT dlaczego nie odzywasz się? I zajmujesz się następnymi zgłoszeniami, bez ogarnięcia poprzednich:

https://github.com/MajkiIT/polish-ads-filter/issues/5644#issuecomment-360048539
https://github.com/MajkiIT/polish-ads-filter/issues/5661#issuecomment-361492990

**Comment by jspenguin2017** [comment]
Can you guys supply an English translation when pinging me?

**Comment by Ravizz** [comment]
Done, I've edited (translated) first comment.

**Comment by jspenguin2017** [comment]
I think they validate it on server side.
