### ISSUE TITLE
onet.pl

### ISSUE THREAD

**Issue by SebaK666** [MajkiIT/polish-ads-filter#5815]
Dziwię się że nikt jeszcze nie zgłosił. Dziś znów pojawił się w artykułach znany i lubiany komunikat. Najpierw wchodzi normalnie, ale potem kółko wczytywania strony się kilka razy kręci, strona jakby odświeża i na końcu wyskakuje blokowanie.
Na szybko zrobiłem sobie działające ukrywanie elementów
wiadomosci.onet.pl##.headerBar
wiadomosci.onet.pl##.statementBox

Ali liczę że się dokładnie przyjrzycie i zrobicie globalny filtr. Bo jak Onet, to możliwe że i Komputerswiat.pl, Przegladsportowy.pl itp. będzie mieć to samo.

Edit:
Jednak moja metoda nie działa, bo napisy są zamazane, zamiast tekstu mamy szare cegłówki. Czyli to co już wielokrotnie było wcześniej. Ale liczę że jak zwykle to naprawicie.

**Comment by crazyjack79** [comment]
To samo co w zgłoszeniu onet.pl #5583

**Comment by MajkiIT** [comment]
@SebaK666 @crazyjack79 
Dzięki już poprawiam.

**Comment by MajkiIT** [comment]
@SebaK666 @crazyjack79 
Jak możecie zróbcie update i sprawdźcie proszę.

**Comment by SebaK666** [comment]
Na Onecie chyba dobrze - nie uruchamiają się automatycznie filmiki w artykułach, co uznałbym za świetne, bo na głównej stronie filmików Onet24 nie można tego zablokować, a plugin-container puchnie do olbrzymich rozmiarów. Tu bym tak chętnie to zostawił.

Ale niestety na vod.pl wcale nie włącza się odtwarzacz
https://vod.pl/programy-onetu/onet-rano-karol-wojcicki-3001/0qhccnt

**Comment by Ravizz** [comment]
Jeszcze jest przycisk social po lewej, przykładowy link: 
https://wiadomosci.onet.pl/tylko-w-onecie/spor-z-izraelem-polacy-nie-sa-odpowiedzialni-za-zaglade-zydow-opinia/mrqqh1f

![capture_001_30012018_210517](https://user-images.githubusercontent.com/35421792/35588523-3555f6ba-0601-11e8-9f52-b4a82a7e3843.png)



<details>
  <summary>moje ustawienia</summary>

```
O 50.0.2762.67 (PGO) & 
uBO 1.14.25.101 & 
ND 13.28

Adblock & uBlock polish filter - Adguard supplement​​
Adblock Warning Removal List​
Adguard’s Annoyance List​
Adguard Base Filters​
AlleBlock
EasyList​
Fanboy’s Annoyance List​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​
Fanboy’s Cookiemonster List​
Fanboy’s Social Blocking List​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt​​
I don't care about cookies​​
KAD - Przekręty
Nano Defender Integration​​
POL: polskie filtry do Adblocka i uBlocka​
POL: polskie filtry do uBlocka uzupelnienie​
Polskie filtry anty-dotacyjne​​
Polskie filtry ciasteczkowe​​
Polskie filtry elementów irytujących
Polskie filtry społecznościowe​​
Polskie filtry wewnętrzne
uBlock filters​
uBlock filters – Annoyances​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
```

</details>

**Comment by crazyjack79** [comment]
Potwierdzam, onet i przegląd działa. Do zamknięcia
