### ISSUE TITLE
centrum-dramy.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5828]
![2018-01-31-piekielna gra 2002 lektor pl centrum dramy pl najnowsze dramy online hd](https://user-images.githubusercontent.com/5884000/35599902-638a4eee-062b-11e8-9d6f-82cceac918ac.png)
`https://centrum-dramy.pl/video/piekielna-gra-2002-lektor-pl/`

player cda nie działa

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.28
Chrome 64.0.3282.119

</details>

**Comment by MajkiIT** [comment]
@KonoromiHimaries ale to nie moja wina
![2018-01-31_0805](https://user-images.githubusercontent.com/11302675/35609453-a7201922-065d-11e8-8980-5a118eee858b.png)

**Comment by MajkiIT** [comment]
https://github.com/hoshsadiq/adblock-nocoin-list/issues/127
