### ISSUE TITLE
Create FAQ (Frequently Asked Questions/Często Zadawane Pytania)

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#585]
przydaloby sie jakies wiki/faq/sticky napisac

**Comment by MajkiIT** [comment]
Ok .... słuszna uwaga coś zrobię w weekend.

**Comment by xxcriticxx** [comment]
na weekend to hyba piwo :+1:

**Comment by MajkiIT** [comment]
czego oczekujesz od tego wiki?

**Comment by xxcriticxx** [comment]
co montowac gdzie kiedy linki do filtrow proste rzeczy

cos z obraskami bendzie proste jak dla dzieci
