### ISSUE TITLE
skomp.pl

### ISSUE THREAD

**Issue by Ravizz** [MajkiIT/polish-ads-filter#5872]
reklama resztki

![capture_022_01022018_184401](https://user-images.githubusercontent.com/35421792/35693908-ed3fbe76-077f-11e8-932a-6f6cab5dd510.png)

<details>
  <summary>moje ustawienia</summary>

```
FF 58.0.1 & 
uBO 1.14.25rc1 & 
ND 13.29

Adblock & uBlock polish filter - Adguard supplement​​
Adblock Warning Removal List​
Adguard’s Annoyance List​
Adguard Base Filters​
AlleBlock
EasyList​
Fanboy’s Annoyance List​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​
Fanboy’s Cookiemonster List​
Fanboy’s Social Blocking List​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt​​
I don't care about cookies​​
KAD - Przekręty
Nano Defender Integration​​
POL: polskie filtry do Adblocka i uBlocka​
POL: polskie filtry do uBlocka uzupelnienie​
Polskie filtry anty-dotacyjne​​
Polskie filtry ciasteczkowe​​
Polskie filtry elementów irytujących
Polskie filtry społecznościowe​​
Polskie filtry społecznościowe - uzupełnienie do uBlocka i AdGuarda​​
Polskie filtry wewnętrzne
uBlock filters​
uBlock filters – Annoyances​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
```

</details>

**Comment by MajkiIT** [comment]
tak jest nawet bez uBo

**Comment by Ravizz** [comment]
@MajkiIT 

np. na Operze tak, ale w Firefoxie jest reklama flash  (musimy mieć w dodatkach ustawione "pytaj o aktywacje):

![capture_039_01022018_192517](https://user-images.githubusercontent.com/35421792/35695730-b1032bd6-0785-11e8-8040-17bb8c12090b.png)

gdy klikniemy to później czarne tło zamienia się w białe tło (troszkę jaśniejsze od tła strony):

![capture_040_01022018_192607](https://user-images.githubusercontent.com/35421792/35695838-f65076d0-0785-11e8-824d-a02838a723b0.png)
