### ISSUE TITLE
www.mikrokontroler.pl

### ISSUE THREAD

**Issue by mathew85** [MajkiIT/polish-ads-filter#590]
Reklamy w tle oraz jedna nie do końca usunięta: http://imgur.com/CPLLpf9

**Comment by xxcriticxx** [comment]
@mathew85 dawno ciebie nie bylo witam ponownie

**Comment by mathew85** [comment]
@xxcriticxx widze za to, że Ty razem z @MajkiIT ostro działacie. Dobra robota!

**Comment by xxcriticxx** [comment]
trzeba jakos czas wolny w robocie zabijac ;)
