### ISSUE TITLE
www.wykop.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#591]
cookies wrocily!

Ciastka!

Strona korzysta z plików cookies w celu realizacji usług i zgodnie z Polityką Plików Cookies. Możesz określić warunki przechowywania lub dostępu do plików cookies w Twojej przeglądarce.

**Comment by MajkiIT** [comment]
Filtrami tego nie wyłapię.

**Comment by xxcriticxx** [comment]
shit to samo co przedtem bylo ja napewno filtry mam wylonczone dlatego sie pokazalo

**Comment by xxcriticxx** [comment]
sorry
