### ISSUE TITLE
vorek.pl - informacja o wykryciu AB

### ISSUE THREAD

**Issue by anti-adblock-fan** [MajkiIT/polish-ads-filter#5942]
### Zrzut ekranu
![obraz](https://user-images.githubusercontent.com/13084298/35749255-4d19d44a-0851-11e8-8490-a681204287c2.png)

### Link bezpośredni

vorek.pl

### Moja konfiguracja
**Przeglądarka internetowa:**

**Rozszerzenia i skrypty:**

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. Easylist
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
- informacja o wykryciu AB
- brak linków w strefie download

**Comment by MajkiIT** [comment]
Sprawdź to 
```
@@||vorek.pl^$generichide 
@@||vorek.pl/*/js/ads.js$script,first-party
```

**Comment by anti-adblock-fan** [comment]
nie pomaga, nadal wyskakuje

**Comment by MajkiIT** [comment]
@jspenguin2017 Can you help me ?

**Comment by jspenguin2017** [comment]
What do you mean? Your filters are good.

**Comment by MajkiIT** [comment]
@jspenguin2017 
But now are not working,unfortunately.

**Comment by krystian3w** [comment]
Jaki bloker reklam @anti-adblock-fan

**Comment by anti-adblock-fan** [comment]
FF: Nano Adblocker + Nano Defender, filtry standardowe dodawane podczas instalacji łącznie z:
POL: Polskie filtry do Adblocka i uBlocka​​​​​
​​POL: Polskie filtry do uBlocka uzupelnienie​
+
Polskie filtry ciasteczkowe

**Comment by MajkiIT** [comment]
@anti-adblock-fan 
Sprawdź to 
```
@@||vorek.pl/*/js/ads.js$script,first-party
vorek.pl#@#.ad
vorek.pl#@#.ads
vorek.pl#@#.adsbox
```

**Comment by krystian3w** [comment]
U mnie z tym drugim zestawem przestało wyskakiwać.

**Comment by anti-adblock-fan** [comment]
dokładnie ##.adsbox, stary adblock mi pokazał, bo NAdblocker w konsoli nie pokazywał że to blokował.

Dzięki i oczywiście bardzo dobra robota za pracę jaką w to wkładacie ;)

**Comment by jspenguin2017** [comment]
I can't reproduce it: 
![image](https://user-images.githubusercontent.com/7283682/35753565-83845df4-081d-11e8-9fee-22a0e72c1f1a.png)

**Comment by jspenguin2017** [comment]
Could have loaded updated filters. Either way, this is good now?

**Comment by krystian3w** [comment]
MajkiIT merged second excetion rules https://github.com/MajkiIT/polish-ads-filter/issues/5942#issuecomment-362680784 to PL list.

Now working ok (I do not have account in vorek.pl to test after log in).
