### ISSUE TITLE
vorek.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5944]
![2018-02-03-22 rybnicka jesien kabaretowa 2017 pl web-dl x264-yl4 _ polski program vorek](https://user-images.githubusercontent.com/5884000/35760434-5f1c00bc-0880-11e8-8f7f-c9e02858994a.png)
`http://vorek.pl/kabarety-skecze/411466-22-rybnicka-jesien-kabaretowa-2017-plweb-dlx264-yl4-polski-program.html`

baner

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.30
Chrome 64.0.3282.140

</details>

**Comment by MajkiIT** [comment]
@KonoromiHimaries musiałeś dorzucić zgłoszeń ?
