### ISSUE TITLE
skript.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5945]
![2018-02-03-forum - skript pl - najlepsze skrypty minecraft](https://user-images.githubusercontent.com/5884000/35760505-e7e69dbc-0880-11e8-88d1-93c3edd8366c.png)

anty-adblock

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.30
Chrome 64.0.3282.140

</details>

**Comment by Reedzev** [comment]
wystarczy js `alert=undefined;`

**Comment by MajkiIT** [comment]
ale regułami tefgo nie wyłapiesz
