### ISSUE TITLE
blog.spigot.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5951]
![2018-02-03-blog spigot pl opisy pluginow i nie tylko](https://user-images.githubusercontent.com/5884000/35761215-8409b116-0886-11e8-93a8-3b6b7b3ff8b8.png)

puste sekcje reklama/fb

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.30
Chrome 64.0.3282.140

</details>

**Comment by MajkiIT** [comment]
`###text-6`
