### ISSUE TITLE
zapytaj.onet.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5964]
![2018-02-03-jak nauczyc tego psa_ - zapytaj onet pl -](https://user-images.githubusercontent.com/5884000/35762764-40e57b2e-089d-11e8-9a35-0cbda50d241b.png)
`https://zapytaj.onet.pl/Category/010,001/2,31261649,Jak__nauczyc_tego_psa.html`

pusta sekcja przeczytaj także

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.30
Chrome 64.0.3282.140

</details>

**Comment by krystian3w** [comment]
U mnie też wyciekają reklamy  Noizz 

![obraz](https://user-images.githubusercontent.com/35370833/35767723-e9630cae-08f1-11e8-824f-50bc2051dd29.png) |
--- |
