### ISSUE TITLE
cs-creativ.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#5974]
### Zrzut ekranu
https://screenshotscdn.firefoxusercontent.com/images/863e04c2-97aa-44c6-aef0-5224fa06d71d.png

Sekcja z reklamami w głównej części strony.

### Link bezpośredni
http://cs-creativ.pl/

<details>
<summary>Moja konfiguracja</summary>
<br>
**Przeglądarka internetowa:**
Firefox 59.0b6

**Rozszerzenia i skrypty:**
uBlock 1.14.25rc1
Nano Defender 13.30

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka + uzupełnienie
2. EasyList
<details>

**Comment by MajkiIT** [comment]
nic takiego nie widzę.
