### ISSUE TITLE
cs-escape.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#5976]
### Zrzut ekranu
https://screenshotscdn.firefoxusercontent.com/images/5e6fc77b-b4a3-42e2-8df9-e4c8a694c0a1.png
https://screenshotscdn.firefoxusercontent.com/images/e8e1dfde-6eee-4895-b214-d61d3b8b623f.png

Pusta sekcja "Polub nas na fb" + sekcja "Partnerzy & Sponsorzy" + wsparcie (darowizna) z prawej strony.

### Link bezpośredni
https://cs-escape.pl/

<details>
<summary>Moja konfiguracja</summary>
<br>
**Przeglądarka internetowa:**
Firefox 59.0b6

**Rozszerzenia i skrypty:**
uBlock 1.14.25rc1
Nano Defender 13.30

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka + uzupełnienie
2. EasyList
<details>

**Comment by MajkiIT** [comment]
`##.ipsBox.ipsWidget_vertical.ipsWidget:nth-of-type(3)`
