### ISSUE TITLE
cs-kopytko.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#5980]
### Zrzut ekranu
https://screenshotscdn.firefoxusercontent.com/images/cdfc80e2-310e-4946-a632-d29d0c3366bc.png
https://screenshotscdn.firefoxusercontent.com/images/0bc64c60-e6a6-4b35-8b81-6cddbf1f1859.png

Irytujący banner + reklama pukawki + pusta sekcja fb + sekcja partnerzy z prawej strony + sekcja mini reklam w stopce.

### Link bezpośredni
http://www.cs-kopytko.pl/

<details>
<summary>Moja konfiguracja</summary>
<br>
**Przeglądarka internetowa:**
Firefox 59.0b6

**Rozszerzenia i skrypty:**
uBlock 1.14.25rc1
Nano Defender 13.30

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka + uzupełnienie
2. EasyList
<details>

**Comment by MajkiIT** [comment]
`##.__xX20facebook`
