### ISSUE TITLE
csopole.eu

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#5981]
### Zrzut ekranu
https://screenshotscdn.firefoxusercontent.com/images/92176835-d500-4e5d-89ff-742b6f61f4e2.png

Pusta sekcja fb + sekcja partnerzy z prawej strony.

### Link bezpośredni
http://csopole.eu/forums/

<details>
<summary>Moja konfiguracja</summary>
<br>
**Przeglądarka internetowa:**
Firefox 59.0b6

**Rozszerzenia i skrypty:**
uBlock 1.14.25rc1
Nano Defender 13.30

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka + uzupełnienie
2. EasyList
<details>

**Comment by MajkiIT** [comment]
`##.ipsBox.ipsWidget_vertical.ipsWidget:nth-of-type(5)`
