### ISSUE TITLE
pykownia.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#5982]
### Zrzut ekranu
https://screenshotscdn.firefoxusercontent.com/images/9f9b211d-1040-4b7c-91e4-aafd6a80117b.png

Sekcja partnerzy z prawej strony + 

### Link bezpośredni
http://pykownia.pl/

<details>
<summary>Moja konfiguracja</summary>
<br>
**Przeglądarka internetowa:**
Firefox 59.0b6

**Rozszerzenia i skrypty:**
uBlock 1.14.25rc1
Nano Defender 13.30

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka + uzupełnienie
2. EasyList
<details>

**Comment by MajkiIT** [comment]
To nie reklama
