### ISSUE TITLE
jbzdy.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5985]
![2018-02-04-jbzdy pl - najgorsze obrazki w internecie](https://user-images.githubusercontent.com/5884000/35775246-99337d10-0985-11e8-8078-92265ff457ca.png)

pusta sekcja

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.30
Chrome 64.0.3282.140

</details>

**Comment by MajkiIT** [comment]
U mnie jest ok.
