### ISSUE TITLE
kreskoweczki.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#5988]
![2018-02-04-anime dragon ball super - odcinek 126 - kreskoweczki pl](https://user-images.githubusercontent.com/5884000/35775800-39078c1e-0990-11e8-84c9-136d30598654.png)
`https://www.kreskoweczki.pl/kreskowka/100819/dragon-ball-super_odcinek-126`
`https://www.kreskoweczki.pl/fullscreen/100819`

sklep

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.30
Chrome 64.0.3282.140

</details>

**Comment by xxcriticxx** [comment]
nie mam tego sklepu ale mam push push

**Comment by MajkiIT** [comment]
@hawkeye116477 push

**Comment by hawkeye116477** [comment]
@MajkiIT Już to dodałem, dałem nawet refa 22 godziny temu 😛 .
