### ISSUE TITLE
cs-4frags.pl, forum.cs-4frags.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#5990]
### Zrzut ekranu
1. https://screenshotscdn.firefoxusercontent.com/images/f153bb16-e33a-40fc-81db-b400c4c82332.png
2. https://screenshotscdn.firefoxusercontent.com/images/cb5fbb3c-5f8f-4236-a445-81d16d24e2ba.png https://screenshotscdn.firefoxusercontent.com/images/c1f50093-e76b-4e09-a17b-ad873fa1c005.png

### Opis
1. Sekcja partnerzy
2. Sekcja partnerzy + dotacje

### Link bezpośredni
1. http://cs-4frags.pl/
1. http://forum.cs-4frags.pl/

<details>
<summary>Moja konfiguracja</summary>
<br>
**Przeglądarka internetowa:**
Firefox 59.0b6

**Rozszerzenia i skrypty:**
uBlock 1.14.25rc1
Nano Defender 13.30

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka + uzupełnienie
2. EasyList
<details>

**Comment by MajkiIT** [comment]
@RikoDEV Nie dorzucaj zgłoszeń, bo za Chiny nie można się z tego wygrzebać.
