### ISSUE TITLE
programosy.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#6013]
Informator o reklamie nad opisami programów.

![obraz](https://user-images.githubusercontent.com/35370833/35781587-4a9cc5d2-09ec-11e8-8969-1d4cfc252d3b.png)

http://www.programosy.pl/program,dzielenie-plikow.html

**Comment by MajkiIT** [comment]
Już jest w filtrach.

**Comment by krystian3w** [comment]
Ok 👌04.02.2018 21:40 "Maciej M." <notifications@github.com> napisał(a):Już jest w filtrach.
