### ISSUE TITLE
purepc.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#6015]
Adblock detect
`https://www.purepc.pl/oprogramowanie/comodo_cloud_antivirus_antywirus_i_sandbox_w_chmurze`
![screenshot_20180204_211814](https://user-images.githubusercontent.com/19818572/35781948-f3aaf820-09f0-11e8-8988-d8e6637aef50.png)

**Comment by MajkiIT** [comment]
`purepc.pl#@#.reklama `
