### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#6016]
Baner z reklamami : 

![wp pil](https://user-images.githubusercontent.com/23176832/35782413-df40462c-09f7-11e8-9dab-c95fc3c7bceb.png)

**Comment by MajkiIT** [comment]
Ja tego nie mam. 
@hawkeye116477 @xxcriticxx zerkniecie ?

**Comment by KonoromiHimaries** [comment]
nawet na zintegrowanym adblocku opery czysto

**Comment by hawkeye116477** [comment]
@MajkiIT U mnie też czysto.

**Comment by HateAds** [comment]
Czysto.
