### ISSUE TITLE
zapytaj.onet.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6022]
![2018-02-05-spadlas kiedys z betonowych schodow na zewnatrz_ - zapytaj onet pl -](https://user-images.githubusercontent.com/5884000/35790433-b9e1e606-0a42-11e8-8d5e-fe4d39bb535b.png)
`https://zapytaj.onet.pl/Category/027,004/2,31265185,Spadlas_kiedys_z_betonowych_schodow_na_zewnatrz.html`

pusta sekcja przeczytaj także po zalogowaniu

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.29
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by MajkiIT** [comment]
jest już blokowany.

**Comment by krystian3w** [comment]
A co blokuje ci noizz.pl?

`||noizz.pl/_cdf/actions/getCustomPromoBlock?partner=zapytaj.onet.pl$subdocument`
