### ISSUE TITLE
allegro.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6038]
![2018-02-05-allegro pl najlepsze ceny najwiekszy wybor i zawsze bezpieczne zakupy online](https://user-images.githubusercontent.com/5884000/35798642-b1d086ae-0a63-11e8-861c-8dc7bc4dba86.png)

reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.29
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by KonoromiHimaries** [comment]
@MajkiIT treść zewnętrzna, partner

**Comment by KonoromiHimaries** [comment]
@MajkiIT zewnętrzny odnośnik

**Comment by MajkiIT** [comment]
`||asa.allegrostatic.com/display-pl/*-reklama.jpg$image`
