### ISSUE TITLE
bednarek.com.pl

### ISSUE THREAD

**Issue by Ravizz** [MajkiIT/polish-ads-filter#6059]
ikona/przycisk społecznościowy

![capture_141_05022018_183144](https://user-images.githubusercontent.com/35421792/35819383-dce9361c-0aa2-11e8-8761-de1c4be18b9e.png)

<details>
  <summary>moje ustawienia</summary>

```
FF 58.0.1 & 
uBO 1.15.4 & 
ND 13.31

Adblock & uBlock polish filter - Adguard supplement​​
Adblock Warning Removal List​
Adguard’s Annoyance List​
Adguard Base Filters​
Adguard Spyware Filters​​​​​
AlleBlock
EasyList​
EasyPrivacy​
Fanboy’s Annoyance List​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​
Fanboy’s Cookiemonster List​
Fanboy’s Enhanced Tracking List
Fanboy’s Social Blocking List​
I don't care about cookies​​
KAD - Przekręty
Nano Defender Integration​​
POL: polskie filtry do Adblocka i uBlocka​
POL: polskie filtry do uBlocka uzupelnienie​
Peter Lowe’s Ad and tracking server list
Polskie filtry anty-dotacyjne​​
Polskie filtry ciasteczkowe​​
Polskie filtry elementów irytujących
Polskie filtry społecznościowe​​
Polskie filtry społecznościowe - uzupełnienie do uBlocka i AdGuarda​​
Polskie filtry wewnętrzne
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt​​
uBlock filters​
uBlock filters – Annoyances​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
```

</details>

**Comment by hawkeye116477** [comment]
Fanboy już to ukrywa.

**Comment by Ravizz** [comment]
@hawkeye116477 tzn. jak to? Przecież ja miałem tę listę ciągle aktywną, po twoim komentarzu sprawdziłem i oczom nie wierzę, lista aktywna ale 0 użytych:

![hmmm](https://user-images.githubusercontent.com/35421792/35822727-73b04ae0-0aad-11e8-8aa5-55afe47cc44d.png)

O co kaman?

**Comment by hawkeye116477** [comment]
@Ravizz Wczoraj czy tam parę dni miałeś wyłączoną, więc nic nie wiadomo. Sprawdzałem i jeśli wyłączę Fanboy's Social to wtedy to się pojawia, z aktywnym nie mam tych ikon. Może to panowie z AdGuarda dali **$generichide** i dlatego to masz.

**Comment by Ravizz** [comment]
> @hawkeye116477 @Ravizz Wczoraj czy tam parę dni miałeś wyłączoną, więc nic nie wiadomo.

Było minęło, pomyłka, która każdemu się czasem zdarza, bo nikt nie jest nieomylny, teraz jak już pisałem, sprawdzałem i mam ją włączoną, ile razy jeszcze mam ci to jeszcze powtórzyć, żebyś w końcu to zrozumiał i odpuścił.

Dalej sugerowałeś, że to może któraś lista od AdGuard, ale powyłączałem wszystkie od AdGuard i dalej to mam.

A żeby było jeszcze ciekawiej mam to nawet przy włączonych tylko tych listach, zarówno na FF 58.0.1 jak i na O 50:

```
EasyList
Fanboy’s Social Blocking List
POL: polskie filtry do Adblocka i uBlocka​​​​​
POL: polskie filtry do uBlocka uzupelnienie​
Polskie filtry społecznościowe​
```

Żeby się zaraz nie okazało, że to po twojej stronie jest jakaś pomyłka i że ty tego nie masz, a nie że ja to mam...najlepiej będzie też zapytać się kogoś jeszcze, @blocker999 masz to?

**Comment by hawkeye116477** [comment]
@Ravizz Na Vivaldim, reguła z Fanboy's Social `##.social_icons` to ukrywa.

**Comment by blocker999** [comment]
Ja tego niemam ani na foxie ani na vivaldim

**Comment by Ravizz** [comment]
@blocker999 : @Ravizz: albo za dużo blokujesz.

Co masz na myśli? Chodzi ci o listy? Tzn. wg ciebie minimalny zestaw 5 podstawowych list to za dużo https://github.com/MajkiIT/polish-ads-filter/issues/6059#issuecomment-363376881 ? To chyba z konia spadłeś.

@blocker999 : @Ravizz: albo to inna rozdziałka

Dokładnie, czyli tak jak ja też sugerowałem wcześniej, ja mam rozdzielczość 1280x1024 i mam tę ikonę, a gdy wszedłem w tryb responsywny w rozdzielczość 1366x768 tej ikony już nie ma, wyszedłem z trybu i znów jest. Więc ta ikona na rozdzielczościach mniejszych od około 1366x768 się pokazuje, a na większych nie. Jaka jest tego przyczyna, być może jakiś błąd w kodzie strony.

> @hawkeye116477 : @Ravizz Na Vivaldim, reguła z Fanboy's Social ##.social_icons to ukrywa.

Nieprawda, nie ukrywa bo nie może tego ukryć, element ma nazwę `##.social_icons_rwd` i reguła `##.social_icons` tego nie ukryje, może ci się pomyliło, a może się nie znasz, gdyby element miał dwie klasy czyli `##.social_icons.rwd`  (czyli zamiast drugiego `_` miałby `.`) to wtedy tak, reguła `##.social_icons` , by ukryła. Przyjrzałem się tej stronie w dzienniku żądań i fakt pojawia się tam reguła  `##.social_icons` , ale po chwili przyjrzałem się stronie również w inspektorze (kod) i ta regułą ukrywa inną ikonę, wyglądającą identycznie:

![capture_175_06022018_135123](https://user-images.githubusercontent.com/35421792/35860688-3b675622-0b45-11e8-9ccb-14d64c5f38b7.png)

jak widać są dwie takie, jedna u góry a druga na dole, tylko ta u góry jest ukrywana przez `##.social_icons` , a ta na dole znika sama z siebie przy rozdzielczości większej niż 1366x768 lub większej, sprawdź sobie, dodaj wyjątek #@#.social_icons i zmień rozdzielczość ekranu na moją albo coś koło niej 1280x1024, i zobaczyć, że ta ikona na dole i tak zniknie.  Przy rozdziałce 1280x1024 ta ikona po lewej na dole ma atrybut: ~~display:none~~ (przekreślony czyli nieaktywny, dlatego się u mnie pokazuje, a w trybie responsywnym w 1366x768 ma już aktywny (nieprzekreślony) atrybut `display:none`, dlatego się nie pokazuje.

Przyczyną jest błąd w kodzie strony lub zamierzone działanie (dostosowanie szaty strony do rozdzielczości ekranu).

**Comment by blocker999** [comment]
Nieporozumienie powstało z braku wiedzy że są dwa f miałem tylko to u góry gdyż mam 1920x1080 a po zmianie na 1280x720 mam obie f no i dodatkowo żeby było śmieszniej YT na dole, także niech @hawkeye116477 się bawi.

![f](https://user-images.githubusercontent.com/23176832/35861842-ca566f72-0b49-11e8-9525-ce4405b1c115.png)

**Comment by hawkeye116477** [comment]
@Ravizz Ja mam rozdzielczość 1280x1024. Faktycznie jest social_icons_rwd, ale u mnie jest to nieaktywne.

**Comment by Ravizz** [comment]
A sprawdzałeś na innych przeglądarkach?, może jakiś zbieg okoliczności, polegający na tym, że niezależnie od tego cyrku z tymi ikonami/rozdzielczościami, to i Vivaldi dorzucił jakąś zabawną niespodziankę, bo z tego co pamiętam kiedyś też różne rzeczy się na nim działy, albo strona reaguje inaczej nie tylko na różne rozdzielczości, ale też na różne przeglądarki.

**Comment by blocker999** [comment]
@Ravizz Co przeglądarka to obyczaj tzn te 1280x720 to było na vivaldim natomiast na foxie tego niema ale po zmianie rozdziałki na 1152x864 już sociale są na obu.

**Comment by Ravizz** [comment]
No takie cuda, no to @hawkeye116477 musi pobawić się różnymi przeglądarkami/rozdzielczościami, aż to ogarnie, a jeśli by ni mógł to jak coś to wystarczy po prostu dodać: `##.social_icons_rwd` do listy oraz regułę do tej ikony youtube, @blocker999 jaka to będzie reguła.

**Comment by hawkeye116477** [comment]
Na 1024x768 widzę ten Social, zaraz dodamy :smile:.
