### ISSUE TITLE
stare adresy 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#606]
na stronie masz jeszcze stare adressy do filtrow

Polskie filtry komunikatów cookies

Kolejne polskie filtry do adblock/ublock przestały być rozwijane. Od 1 kwietnia 2014 lista LubieCiasteczka.net przestała być wspierana. Jak wiadomo rynek reklam i komunikatów podobnie jak z polskimi reklamami nie lubi próżni i jest stale rozwijany, co powoduje, że w końcu denerwujące komunikaty są wyświetlane.

Jak wiadomo globalne filtry ciasteczek nie zawsze pozwalają na blokowanie komunikatów w języku polskim, dlatego CertyficateIT postanowiło wskrzesić polskie filtry ciasteczek.

Wzięliśmy zawartość filtrów LubieCiasteczka.net i zaktualizowaliśmy je o nowe reguły. Dostępne są one pod adresem:

    www.certyficate.it/adblock/adblock_cookies.txt Polskie filtry komunikatów cookies(changelog)
    automatyczne dodanie do uBlock/Adblock

Filtry są dostępne na licencji GNU GPL v3, więc proszę śmiało korzystać. Mamy jedynie prośbę: jeśli korzystacie z naszych filtrów polubcie nasz na FB (www.facebook.com/CertyficateIT) . Jest to dla nas informacja, że jest zainteresowanie naszymi filtrami.

więcej filtrów jakie tworzy CertyficateIT dostępne są na stronie.

**Comment by MajkiIT** [comment]
Ok poprawię

**Comment by xxcriticxx** [comment]
przekierowanie jest
