### ISSUE TITLE
Komentarz z Facebooka na portalach

### ISSUE THREAD

**Issue by SebaK666** [MajkiIT/polish-ads-filter#6067]
Wszedłem na artykuł w Onecie, ale zauważyłem że brakuje komentarzy:
https://sport.onet.pl/pjongczang-2018/dmitrij-miedwiediew-mkol-podjal-haniebna-decyzje/7dj21sx

Okazuje się, że jest teraz moda zamieszczania komentarzy z osadzonej ramki z Facebooka typu "https://web.facebook.com/plugins/comments.php?api_key="
Blokowane jest to w Polskich Filtrach Społecznościowych, dokładnie filtr:
`pl##.fb_iframe_widget`
Po jego wyłączeniu komentarze w artykule są widoczne.

Teraz moje pytanie: może to nie błąd, czy ten zestaw filtrów ma blokować wszystkie elementy z mediów społecznościowych, nie tylko przyciski, linki, ale też rzeczy użyteczne np. komentarze?
Zależy od założenia czy ma blokować absolutnie wszystko, czy jednak zostawiać właśnie np. komentarze na stronach. Wtedy należy ten wpis usunąć z filtra.

**Comment by hawkeye116477** [comment]
Lista Social nie blokuje komentarzy, to błąd.
