### ISSUE TITLE
gazetaprawna.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6074]
![2018-02-06-gazetaprawna pl - biznes podatki prawo finanse wiadomosci praca](https://user-images.githubusercontent.com/5884000/35853992-587c779e-0b2f-11e8-828c-cd804e39725a.png)

pusta sekcja reklama po prawej

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.29
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by Ravizz** [comment]
Po prawej.
