### ISSUE TITLE
aternos.org

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#6075]
### Zrzut ekranu
![c7b37369-fd3d-495e-a824-5e036ec633fb](https://user-images.githubusercontent.com/18230443/35856560-acffc472-0b36-11e8-8264-30bdd07b7a14.png)

Anty adblock (tylko panel **zalogowanego** użytkownika)

### Link bezpośredni
https://aternos.org/options/

### Moja konfiguracja
**Przeglądarka internetowa:** Firefox 59.0b6 (64 bit, beta)

**Rozszerzenia i skrypty:**
uBlock 1.15.3rc0
Nano Defender 13.31

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. EasyList

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Div z informacją z tego co widzę generuje się losowo po przeładowaniu strony, kod jsa odpowiadającego za anty adblock: https://hastebin.com/raw/holicumulu. Natomiast prawidłowa strona otrzymuje css `display: none;`.

**Comment by KonoromiHimaries** [comment]
u mnie w porządku, wgraj nano adblocker i zaktualizuj filtry.

**Comment by RikoDEV** [comment]
Zaktualizowałem filtry + mam nano adblocker. Nadal dostaje ten modal.

**Comment by Ravizz** [comment]
Nie mam tego.

typ elementu



<details>
  <summary>moje ustawienia</summary>

```
FF 58.0.1 & 
uBO 1.15.4 & 
ND 13.31

Adblock & uBlock polish filter - Adguard supplement​​
Adblock Warning Removal List​
Adguard’s Annoyance List​
Adguard Base Filters​
Adguard Spyware Filters​​​​​
AlleBlock
EasyList​
EasyPrivacy​
Fanboy’s Annoyance List​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​
Fanboy’s Cookiemonster List​
Fanboy’s Enhanced Tracking List
Fanboy’s Social Blocking List​
I don't care about cookies​​
KAD - Przekręty
Nano Defender Integration​​
POL: polskie filtry do Adblocka i uBlocka​
POL: polskie filtry do uBlocka uzupelnienie​
Peter Lowe’s Ad and tracking server list
Polskie filtry anty-dotacyjne​​
Polskie filtry ciasteczkowe​​
Polskie filtry elementów irytujących
Polskie filtry społecznościowe​​
Polskie filtry społecznościowe - uzupełnienie do uBlocka i AdGuarda​​
Polskie filtry wewnętrzne
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt​​
uBlock filters​
uBlock filters – Annoyances​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
```

</details>

**Comment by RikoDEV** [comment]
@Ravizz modal występuje po logowaniu.

**Comment by Ravizz** [comment]
Zapomniałeś napisać tego w pierwszym komentarzu, więc już wszystko jasne, ja nie mam tam konta i nie korzystam z tej strony, więc niech ktoś inny się bawi.

**Comment by RikoDEV** [comment]
Podobny issue https://github.com/jspenguin2017/uBlockProtector/issues/453

**Comment by Ravizz** [comment]
No tam już napisane że naprawili.

**Comment by RikoDEV** [comment]
@Ravizz scroll w dół.

**Comment by Ravizz** [comment]
Dzięki, nie skorzystam z rady, bo już to robiłem i przeczytałem cały wątek i ostatni komentarz też, tam jest podany filtr, działa ci on?

**Comment by RikoDEV** [comment]
@Ravizz właśnie testuje i działa.

**Comment by Ravizz** [comment]
To w czym problem?

**Comment by RikoDEV** [comment]
@Ravizz w tym że nie jest on domyślnie dodany do filtrów?

**Comment by Ravizz** [comment]
Faktycznie, może pingwin zapomniał/przegapił, ale to w takim przypadku to raczej powinno się to zgłosić do pingwina, no chyba, że przypominałeś mu a on pomimo tego, nie dodał?

**Comment by KonoromiHimaries** [comment]
ping @jspenguin2017

**Comment by RikoDEV** [comment]
Strona jest też polska, więc kwalifikuje się do polskich filtrów.

**Comment by Ravizz** [comment]
@RikoDEV jak najbardziej jest też polska i kwalifikuje się, ale dopiero jeśli pingwin jej nie doda u siebie, bo może to zwykłe nieporozumienie/przegapienie, trzeba to wyjaśnić z pingwinem, jeśli pingwin jej nie doda, to z pewnością my dodamy.

**Comment by RikoDEV** [comment]
@Ravizz bez ND strona działa tak samo, nic się nie psuje. Filtry ND mam "dla zasady" nie interesowałem się kto jest ich twórcą oraz nie wchodziłem na repo "pingwina". Dopiero dzisiaj dowiedziałem się kim on jest za sprawą tego issue.

**Comment by Ravizz** [comment]
To są osoby nieświadome, co tracą, a dalej to zależy od konkretnego przypadku/strony, część adblock detectów da się ogarnąć zwykłymi filtrami, a część tylko za pomocą ND. Jeżeli ktoś nie używa ND, a trafi na jakąś stronę z takim trudniejszym przypadkiem to rzeczywiście zostanie z adblock detectem.

**Comment by MajkiIT** [comment]
@RikoDEV @Ravizz to wrzucamy to do ND?
