### ISSUE TITLE
cda.pl

### ISSUE THREAD

**Issue by Ubuntuslav** [MajkiIT/polish-ads-filter#6079]
Reklama video

<img src='https://i.imgur.com/Jiqr5LN.png' />

http://www.cda.pl/video/1952678f4

* Moje ustawienia
  * Chrome 64.0.3282.140 (x64)
  * uBlock Origin 1.14.24
  * <a href="https://openload.co/f/69pT__74A2E">Filtry</a>

**Comment by Ravizz** [comment]
I nie tylko, pod filmikiem też coś wyskoczyło:

![capture_176_06022018_165142](https://user-images.githubusercontent.com/35421792/35868866-12d81228-0b5e-11e8-8cfe-4ab895520192.png)

**Comment by MajkiIT** [comment]
@Ubuntuslav update filtrów. Dzięki
@Ravizz to wewnętrzna reklama. @KonoromiHimaries FYI
