### ISSUE TITLE
www.spidersweb.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#61]
reklama

http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=tf&c=20&mc=click&pli=15737741&PluID=0&ord=[timestamp]

http://ceneoadpl.hit.gemius.pl/hitredir/id=10ZKtm9_K2YdTuGmh3Wer5PZLTAGos9Mo3VtMPvWrt7.v7/stparam=mmcsqwhhlm/fastid=nlzvxfsmnvufvbmndecohucnjvmr/url=http://www.ceneowybory.pl/?slide=3

https://mobilevikings.pl/pl/offer/?utm_source=home&utm_medium=banner&utm_term=pl&utm_content=viking24-1180x250&utm_campaign=spidersweb

http://www.ceneo.pl/39108078#pid=7786&crid=26657&cid=9638

**Comment by MajkiIT** [comment]
nic nie widzę takiego

**Comment by xxcriticxx** [comment]
http://imgur.com/a/Xw42q

pierwszy obrazek ublock wlonczony reszta wylonczona dzisaj jest duza ladna box
