### ISSUE TITLE
sms phishing2

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#613]
dodać z listę z maila

**Comment by xxcriticxx** [comment]
Spam filter?

**Comment by MajkiIT** [comment]
to te strony gdzie musisz podać maila a oni cię kasują za smsa za 9 zł.

**Comment by xxcriticxx** [comment]
wiem oco chodzi ale oco chodzic z lista z maila?

dostales liste emailem?

**Comment by MajkiIT** [comment]
Tak dostałem mailem.

**Comment by xxcriticxx** [comment]
duza?

**Comment by MajkiIT** [comment]
41 linków.

**Comment by xxcriticxx** [comment]
nice
