### ISSUE TITLE
cyfrowe.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#6135]
Reklama Panasonica między urządzeniami w tym dziale : 

https://www.cyfrowe.pl/drukarki-urzadzenia-wielofunkcyjne,6,20,600/p/2/Canon.html

**Comment by MajkiIT** [comment]
ja tego nie widzę... @KonoromiHimaries @xxcriticxx @hawkeye116477 zerkniecie ?

**Comment by hawkeye116477** [comment]
Też tego nie widze.

**Comment by xxcriticxx** [comment]
nope czysto

**Comment by Rzeszow** [comment]
`www.cyfrowe.pl##.banner-750x100`
@blocker999 Czy ci chodzi o reklamę (aktualnie foto-książki) pomiędzy ofertami?
![www cyfrowe pl_drukarki-urzadzenia-wielofunkcyjne 6 20 600_p_2_canon html](https://user-images.githubusercontent.com/6783135/35984391-9eefe690-0cf4-11e8-8d20-be3d4f1a19ab.png)

**Comment by xxcriticxx** [comment]
@Rzeszow jaki os? browser?

**Comment by Rzeszow** [comment]
@xxcriticxx Windows 10 Enterprise / Chrome - Wersja 64.0.3282.140 (Oficjalna wersja) (64-bitowa) / uBlock Origin 1.14.24

**Comment by xxcriticxx** [comment]
@Rzeszow lista filtrow please?

@blocker999 dalej to masz?

**Comment by Rzeszow** [comment]
@xxcriticxx 
**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. uBlock filters
3. uBlock filters – Privacy​​​​​
4. uBlock filters – Resource abuse​​​​​
5. uBlock filters – Unbreak
6. EasyList
7. EasyPrivacy
8. Peter Lowe’s Ad and tracking server list
9. KAD - Przekręty

**Comment by HateAds** [comment]
U mnie na Chromie tego nie ma.

**Comment by Rzeszow** [comment]
Już naprawione ♥
![1](https://user-images.githubusercontent.com/6783135/35995662-61b6be8c-0d14-11e8-80ab-b355ffb8801d.PNG)

**Comment by MajkiIT** [comment]
@Rzeszow ale ta reguła jest od dawna. Hmmm dziwne.
