### ISSUE TITLE
katowicedzis.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6137]
![2018-02-08-aktualnosci](https://user-images.githubusercontent.com/5884000/35961353-9d9d0d5a-0cad-11e8-9d36-7f9f7f9a7427.png)

puste sekcje reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.29
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by krystian3w** [comment]
`###g-sidebar > .g-grid > .size-100.g-block > .g-content` :question:

**Comment by krystian3w** [comment]
- `###g-sidebar > .g-grid > .size-100.g-block > .g-content` :question: 

- `###g-container-main > .g-grid > .size-75.g-block:style(flex: 100%;)` - jak w prawej kolumnie nic nie ma to opcjonalnie można sobie powiększyć. Jakby ktoś chciał użyć `auto`, to by trzeba było ją ukrywać a `100%` ją wypcha gdzieś pod nawigacje z liczbą stron bez suwaków (pierwsza reguła sprawia że nie widać jej po "spadku").

**Comment by Ravizz** [comment]
@krystian3w 
Nie sprawdzałem, więc tylko tak na kolanie przy okazji, chodzi mi o to czy nie zapomniałeś `!important`?
`:style(flex: 100%;)` >> `:style(flex: 100% !important;)` czy bez tego `!important` styl będzie się trzymał / nic go nie nadpisze?

**Comment by krystian3w** [comment]
W nano działało bez, ale czasem bez important niestety nie działa---08.02.2018 19:07 "Maciej M." <notifications@github.com> napisał(a):Closed #6137.
