### ISSUE TITLE
crazynauka.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6140]
![2018-02-08-ile wazy 1 kilogram maki na innych planetach_ crazy nauka](https://user-images.githubusercontent.com/5884000/35962357-5cfd79ca-0cb1-11e8-9f1c-18ba597f972f.png)
`https://www.crazynauka.pl/ile-wazy-1-kilogram-maki-na-innych-planetach/`

pusta sekcja reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.29
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by Rzeszow** [comment]
`www.crazynauka.pl###text-6`?
