### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by Rzeszow** [MajkiIT/polish-ads-filter#6142]
### Zrzut ekranu

![1](https://user-images.githubusercontent.com/6783135/35966118-2f9ea984-0cbd-11e8-9b40-7d285f5cb859.PNG)
### Link bezpośredni

`https://www.wp.pl/`
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1.  Wejść na stronę.
2.  Odświeżyć ją kilka razy kiedy za pierwszym razem się nie pojawiła.

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome - Wersja 64.0.3282.140 (Oficjalna wersja) (64-bitowa)
**Rozszerzenia i skrypty:**
uBlock Origin 1.14.24
**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. uBlock filters
3. uBlock filters – Privacy​​​​​
4. uBlock filters – Resource abuse​​​​​
5. uBlock filters – Unbreak
6. EasyList
7. EasyPrivacy
8. Peter Lowe’s Ad and tracking server list
9. KAD - Przekręty

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by MajkiIT** [comment]
@Rzeszow sprawdź z najnowszą wersją.

**Comment by Rzeszow** [comment]
Raczej nie działa.

**Comment by krystian3w** [comment]
`##SECTION#section_topnews > DIV[class]:nth-of-type(2)` ale wystarczy że jakoś przeniosą między miejscami i nie zadziała.

**Comment by krystian3w** [comment]
`##SECTION#section_topnews > DIV[class]:nth-of-type(2)` - ale czasem przeskakuje div nawet na 3 więc to by się nie nadawało.

**Comment by Rzeszow** [comment]
Sorry to musiałem nie zauważyć, ale szukałem czy jest jakiś inny na ten temat i nie znalazłem. Jak byś był miły to daj linka. Ja chciałem tylko zgłosić, że po prostu widzę reklamę i tyle.

**Comment by krystian3w** [comment]
Na drugiej stronie w otwartych był: https://github.com/MajkiIT/polish-ads-filter/issues/4037

**Comment by Ravizz** [comment]
@Rzeszow spoko, nie musisz klękać na kolanach i przepraszać, tu nie kościół tym bardziej nie ambona,  tym bardziej, że pomyłki nawet proste, zdarzają się każdemu, oczywiście jeśli chcesz to możesz przepraszać, nie zabraniam.

> @Rzeszow : Jak byś był miły to daj linka. 

Jesteś niemiły skoro mnie obrażasz, bo ja nie jestem twoim sługą od podawania wątków:
- wątek jest publicznie widoczny
- są ledwo 2 strony wątków a to naprawdę mało, wystarczy jedno kliknięcie żeby przejść na drugą stronę
- jest funkcja wyszukiwania, wystarczy wpisać wp.pl

Więc masz wędkę i przynętę, a prosisz o łatwą rybę, a ja nie z tych co takim leniwym usługują, rusz tyłek i sobie sam znajdź, a ode mnie odbij gościu, bo zawołam moderatora, jeśli dalej będziesz mi ubliżał.

**Comment by MajkiIT** [comment]
@Rzeszow sprawdzisz to?
`www.wp.pl##SECTION#section_topnews > DIV:first-child + * + DIV[class]`

**Comment by Rzeszow** [comment]
@MajkiIT Przykro mi ale nic, dalej niestety jest widoczne. Tego tak prosto nie usuniemy.

**Comment by MajkiIT** [comment]
@Rzeszow spokojnie , nie poddamy się

**Comment by Rzeszow** [comment]
@MajkiIT https://github.com/MajkiIT/polish-ads-filter/issues/3927#issuecomment-340512834 Przynajmniej mi to działa. Dzięki @gjedeer

**Comment by MajkiIT** [comment]
@Rzeszow ale to działa Ci na uBo? jak coś poszedł update, to tez powinno pomóc.

**Comment by Rzeszow** [comment]
@MajkiIT Jeśli chodzi ci o ten skrypt JS to wklejam w konsoli to działa. A ten twój kod do UBlocka to nie nie działa :( - https://github.com/MajkiIT/polish-ads-filter/issues/6142#issuecomment-364191021.

@Ravizz Przepraszam. Ale ja nie chciałem Cię obrazić mi bardziej o to chodziło, że na prawdę ja tu nie bywam jestem na tym repo z drugi raz. Po prostu chciałem zgłosić, że widzę reklamę na wp. Znalazłem tamten poprzedni temat ale nie chciałem tam pisać, bo od dotyczył innych reklam. Myślałem, że dla każdej reklamy tworzy się tu oddzielnego ticketa aby potem prościej było ustalić co jest już naprawione a co jeszcze trzeba zrobić. Według mnie przynajmniej tak powinno być aby potem @MajkiIT połapał się że np ta reklama jest już naprawiona (a ta akurat jest zupełnie inna od tych wszystkich innych).

**Comment by Ravizz** [comment]
> @Rzeszow : @Ravizz  Przepraszam.

I wystarczy.

> @Rzeszow :  @Ravizz Ale ja nie chciałem Cię obrazić

Ale to zrobiłeś, może zaraz jeszcze powiesz, że kot ci wszedł na klawiaturę i przypadkowo napisał przymiotnik w moją stronę.

Co do całej reszty czyli tłumaczenie się - to nie ma ono nic wspólnego z tym przymiotnikiem, to tłumaczenie dotyczy innej kwestii - zdublowania wątku, a to już mamy za sobą, więc nie wiem po co się powtórnie z tego tłumaczysz, widocznie dlatego, że nie umiesz się wytłumaczyć z przymiotnika.

Zostawmy to już, koniec tematu.

**Comment by gjedeer** [comment]
Klimat przyjemny jak na elektrodzie, proszę mnie więcej nie wołać do tego projektu, nie chcę takiego [raka](https://github.com/MajkiIT/polish-ads-filter/issues/6142#issuecomment-364105248) w skrzynce odbiorczej.
