### ISSUE TITLE
seriale.co

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#6148]
http://seriale.co/the-flash/
<details>

![image](https://user-images.githubusercontent.com/29756590/36035443-3834266e-0db7-11e8-8d42-028bc71a96cb.png)
</details>
Informacja o adblocku wyskakuje kiedy przy opcji Wybierz player wybieramy host streamango ( openload wyświetla normalnie odcinek bez napisu o adblocku )

**Comment by MajkiIT** [comment]
@HateAds ja tego nie mam. 
@KonoromiHimaries @xxcriticxx @hawkeye116477 zerkniecie ?

**Comment by KonoromiHimaries** [comment]
na zintegrowanym adblocku opery czysto

**Comment by HateAds** [comment]
@MajkiIT @KonoromiHimaries @xxcriticxx @hawkeye116477 Teraz zauważyłem, że ten problem pojawia się tylko jak EasyList jest włączone.
Teraz mam do Was pytanie, gdzie się powinno zgłosić problem z listą EasyList ?

**Comment by KonoromiHimaries** [comment]
@HateAds https://github.com/easylist/easylist/issues

**Comment by xxcriticxx** [comment]
ta jest bardziej aktywna

https://forums.lanik.us/viewforum.php?f=62&sid=4e5321abf975111596988ef1fbf13d97
