### ISSUE TITLE
serialosy.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6151]
streamango adblock

http://www.serialosy.pl/zagraniczne-seriale9/12-malp/12559-12-malp-12-monkeys-s03e09-napisy-pl.html

![capture](https://user-images.githubusercontent.com/15007183/36063945-badeea3c-0e51-11e8-86e4-81acee5fb68f.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx u mnie jest ok.
@hawkeye116477 zerkniesz?

**Comment by hawkeye116477** [comment]
U mnie jest ok. Niech @xxcriticxx sprawdzi czy mu któraś lista przypadkiem nie blokuje `https://streamango.com/assets/js/license.adbl.js`, bo nie powinna.

**Comment by MajkiIT** [comment]
@hawkeye116477 Dziękuję

**Comment by xxcriticxx** [comment]
mam standardowe filtry ubo + pl filtry
