### ISSUE TITLE
telewizjanazywo.ml

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6153]
mucho redirect

`||telewizjanazywo.ml^`

**Comment by MajkiIT** [comment]
skąd to wytrzasnąłeś ? Na jakiej to stronie było?

**Comment by xxcriticxx** [comment]
gdzies z internetu

**Comment by MajkiIT** [comment]
aha.... ona jest na 10 stronach z filmami, ale ogarniam to regexem. Dziękuję
