### ISSUE TITLE
a-o.ninja

### ISSUE THREAD

**Issue by camyc** [MajkiIT/polish-ads-filter#6156]
https://i.imgur.com/g4TuQXq.png

https://a-o.ninja/anime/overlord-2/5 - powtarza się w sumie wszędzie

Chrome

Nano Adblocker, Nano Defender, NoCoin, Disconnect

Polskie filtry do Adblocka i uBlocka (w sumie to nie wiem jakie inne mogą być ważne, pobrałem dziś wszystkie dostępne i je zaktualizowałem, sorki jak coś, bo jestem newbie - ale na pozostałych tego typu stronach działają)

**Comment by camyc** [comment]
przez chwilę zeszło, jednak dalej to samo

**Comment by MajkiIT** [comment]
@camyc POPRAWIONE.

**Comment by OtakuPL** [comment]
Fajne te a-o.ninja nie polecam ich blokować.
