### ISSUE TITLE
telewizjarepublika.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6169]
![2018-02-11-telewizja republika - wiadomosci _ informacje _ wydarzenia - polska i swiat](https://user-images.githubusercontent.com/5884000/36071441-da76fde0-0f0e-11e8-8850-cb62a863c8f9.png)

pusta sekcja

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.30
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by MajkiIT** [comment]
tego nie da się zablokować. To część większego kawałka.
