### ISSUE TITLE
zapinamypasy.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6200]
1. Na Chromium i Vivaldi player działa dopiero po wyłączeniu Nano Adblocker.
2. W Chromium pyta o lokalizację (??)
![qri1awj](https://user-images.githubusercontent.com/36385327/36079795-4f8361e6-0f87-11e8-9180-617785ad3dc0.png)
3. Również można spotkać ikony social https://zapinamypasy.pl/news/14d11ed5-4185-4d8b-9573-6257ad668b3a
![qri1awj](https://i.imgur.com/aRkEpTE.png)
<details>
 <summary><b>Moja konfiguracja:</b></summary>

- Vivaldi 1.14.1077.45/Chromium 64.0.3282
-  Nano Adblocker v1.0.0.30
-  Nano Defender 13.31
-  Filtry https://gist.github.com/xMaap/0a1cbcdef8d23ef6bd73e8a0c8b9b8bc
</details>

**Comment by xMaap** [comment]
Ech chyba jednak tego tutaj nie powinienem zgłaszać, ponieważ po odznaczeniu Adguard Spyware Filters i​​​​​​​​​ EasyPrivacy player zaczął działać.

**Comment by MajkiIT** [comment]
@xMaap jak możesz to zgłoś to proszę do twórców tych list.
