### ISSUE TITLE
pcworld.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6204]
Od góry po sam dół jest mnóstwo reklam.

<details>
 <summary><b>Moja konfiguracja:</b></summary>

- Vivaldi 1.14.1077.45
-  Nano Adblocker v1.0.0.30
-  Nano Defender 13.31
-  Filtry https://gist.github.com/xMaap/0a1cbcdef8d23ef6bd73e8a0c8b9b8bc
</details>

**Comment by MajkiIT** [comment]
@xMaap nie wiem czy ten sposób blokady jest optymalny, ale innego nie znalazłem.

**Comment by KonoromiHimaries** [comment]
![2018-02-12-najlepsze karty microsd czyli ktore_ - pc world - testy i ceny sprzetu pc rtv](https://user-images.githubusercontent.com/5884000/36091812-5f9998da-0fe5-11e8-916b-5895a432692e.png)
`https://www.pcworld.pl/ranking/Najlepsze-karty-microSD-czyli-ktore,408558.html`

sklep

**Comment by xMaap** [comment]
W sumie to jeszcze tutaj jest tego sporo, ale nie wiem czy takie coś się nadaje do blokowania https://www.pcworld.pl/amazon

**Comment by KonoromiHimaries** [comment]
> W sumie to jeszcze tutaj jest tego sporo, ale nie wiem czy takie coś się nadaje do blokowania https://www.pcworld.pl/amazon

główny kontent podstrony, nie dotykamy
