### ISSUE TITLE
dailyweb.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#6208]
### Zrzut ekranu
![dailyweb](https://screenshotscdn.firefoxusercontent.com/images/ea8983dd-b8e9-4e7c-9a85-0a7c1a5fe8d3.png)
![dailyweb](https://screenshotscdn.firefoxusercontent.com/images/6e67b2ed-fa00-49eb-b6ae-f545831787d1.png)

Adblock info + sekcja fb + ikony społecznościowe

### Link bezpośredni
https://dailyweb.pl/kupilem-elektrycznego-longboarda-z-indiegogo-poznajcie-backfire-galaxy-pierwsze-wrazenia/

<details>
<summary>Moja konfiguracja</summary>
<br>

**Przeglądarka internetowa:**
Firefox 59.0b8

**Rozszerzenia i skrypty:**
uBlock 1.15.5b0
Nano Defender 13.31

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka + uzupełnienie
2. EasyList
<details>

**Comment by MajkiIT** [comment]
`dailyweb.pl##.row:nth-of-type(4)`

**Comment by hawkeye116477** [comment]
@MajkiIT Sociala to tu nie ma, bo Fanboy's Social czyści, ale ja tam widzę jakaś ruchomą reklamę z prawej.

**Comment by MajkiIT** [comment]
`dailyweb.pl##.user-widgets`
