### ISSUE TITLE
forbes.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6212]
Ukrywa logo.

<details>
 <summary><b>Moja konfiguracja:</b></summary>

- Vivaldi 1.14.1077.45
-  Nano Adblocker v1.0.0.30
-  Nano Defender 13.31
-  Filtry https://gist.github.com/xMaap/0a1cbcdef8d23ef6bd73e8a0c8b9b8bc
</details>

**Comment by KonoromiHimaries** [comment]
ukrywa, ale błąd nie jest spowodowany którąś z naszych list.

**Comment by KonoromiHimaries** [comment]
ciekawy ten błąd, ujawnia się tylko po bezpośrednim przejściu na stronę

listy odpowiedzialne za błąd
- Fanboy’s Annoyance List
- Fanboy’s Social Blocking List
