### ISSUE TITLE
Lista do Pi-Hole

### ISSUE THREAD

**Issue by Eva850** [MajkiIT/polish-ads-filter#6225]
Witam, myślę że można by dodać następujące domeny do listy dla pi-hole:
ipla.hit.stat24.com
ipla.hit.gemius.pl

Po zablokowaniu tych domen aplikacja Ipla na telewizorze Panasonic przestała wyświetlać reklamy video.

**Comment by MajkiIT** [comment]
@Eva850 dzięki za info. Tak oczywiście dodam.

**Comment by xxcriticxx** [comment]
@Eva850 przetestuj moje repo please

https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt

**Comment by Eva850** [comment]
@xxcriticxx Lista wygląda fajnie, dodam ją do źródeł hosts i sprawdzę, dzięki za link

**Comment by MajkiIT** [comment]
@xxcriticxx mogę wrzucić to do PL ?

**Comment by xxcriticxx** [comment]
sure
