### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6230]
![](https://user-images.githubusercontent.com/36385327/36239564-fc351e68-120a-11e8-91fd-617a600783ea.png)

Oraz na samym dole ikonka youtube 
<details>
 <summary><b>Moja konfiguracja:</b></summary>

- Vivaldi 1.14.1077.45
-  Nano Adblocker v1.0.0.31
-  Nano Defender 13.32
-  Filtry https://gist.github.com/xMaap/28140ee9c3269f8b0ef356986563418a
</details>

**Comment by MajkiIT** [comment]
@gulson stare warunki obowiązują?

**Comment by gulson** [comment]
@MajkiIT oczywiście, że tak. Nie wiem czemu zgłoszono małe elementy reklamowe w niczym nie przeszkadzające, które dodatkowo możesz zamknąć. Rozumiem jakieś duże bannery, czy coś jak wyskakuje, ale jak widzisz te rzeczy blokuje AdBlock skutecznie i żadnych takich reklam nie ma :)
 
Mało tego, miesiąc temu dostałem raport od Google, że spełniamy zasady Coalition for Better Ads.

**Comment by MajkiIT** [comment]
@gulson Ok dzięki. Ale te pasek na dole i równy róg mogę zablokować?

**Comment by gulson** [comment]
@MajkiIT  Możesz zablokować, ja później zmienię nazwy klasy, jest to naprawdę obojętne :)
Prośba tylko o nieuszkodzenie strony :)

**Comment by MajkiIT** [comment]
@gulson nie chcę się bawić w takie rzeczy, ale ok masz do tego prawo.

**Comment by gulson** [comment]
@xMaap jak Ci takie "reklamy" przeszkadzają, które są zintegrowane z stroną to prośba nie zaglądaj na elektroda.pl, umowa stoi? :) I co Ci chodzi z ikonką youtube?

**Comment by krystian3w** [comment]
Nie zablowowany kanał social media?

Macie swoje jakieś poradniki wideo i stąd link do nich w szabloonie forum?

**Comment by gulson** [comment]
Nie za bardzo rozumiem, to nie można linkować do swojego kanału youtube w stopce? :)

**Comment by krystian3w** [comment]
Można ale też mamy prawo wyciać to listą fanboya / adguard czy polskim uzupełnieniem do takiej listy.

**Comment by gulson** [comment]
Kto ustanawia to prawo? :) Maciej?

**Comment by krystian3w** [comment]
Tworcy dodatków co wycinają reklamy czy modyfikują css np. stylish.

**Comment by krystian3w** [comment]
Teraz masz do sprawdzania z 4 listy 😀😀😀😀😀😀😀😀

**Comment by gulson** [comment]
Które listy jeszcze monitorować? :)

**Comment by MajkiIT** [comment]
@gulson to traktowane jest jako społecznościowe. Są ludzie których to irytuje i mają prawo to blokować.

**Comment by gulson** [comment]
@MajkiIT ale przecież to link a href do kanały youtube.
Rozumiem jakby to był jakiś iframe. Chyba społeczność zaczyna lekko przesadzać.

**Comment by krystian3w** [comment]
* https://secure.fanboy.co.nz/fanboy-annoyance.txt
* https://filters.adtidy.org/extension/chromium/filters/14.txt

**Comment by gulson** [comment]
Dzięki.

**Comment by MajkiIT** [comment]
@gulson no tak, ale podchodzi pod całą sekcję social.

**Comment by gulson** [comment]
Wygląda to trochę słabo, zarżnięcie finansowo wszystkie portale internetowe. Pozostanie Wam taplatanie się błotku facebooka, który ma dedykowaną aplikację i nie dopuści do siebie filtrów :) 
To tyle, dziękuję, reklamy widzę, że już usunęliście.

**Comment by MajkiIT** [comment]
ale to social a nie reklamy. Tak samo jak filtry ciasteczek itp. No wizja przedstawiona przez ciebie jest interesująca. Ja nie wciskam nikomu na siłę niczego. Chce to dodaje filtry które go interesują. Co do reklam to twoje "kwadraciki" zostawiłem.

**Comment by xMaap** [comment]
@MajkiIT Zostały resztki po tym dolnym dolnym pasku

**Comment by gulson** [comment]
@xMaap to nie wchodź na stronę i nie będziesz się denerwował resztkami pasków :)

**Comment by krystian3w** [comment]
¿Czemu w koszu?15.02.2018 10:30 xMaap <notifications@github.com> napisał(a):@MajkiIT Zostały resztki po tym dolnym dolnym pasku

**Comment by MajkiIT** [comment]
@gulson dziwne masz podejście do swoich odwiedzających. .

**Comment by gulson** [comment]
Mam dobre podejście do użytkowników, wspieram ich, wysyłam upominki, pomagam w problemach.
Jednak jeżeli komuś przeszkadzają reklamy dzięki którym portal się utrzymuje, dzięki którym mogę kupić gadżety dla userów do tego je Tobie raportuje i jeszcze po zablokowaniu nie jest zadowolony, bo został mu pasek to lepiej niech taki user nie zagląda, aby nie musiał się irytować.

**Comment by MajkiIT** [comment]
@gulson znasz moje stanowisko... cenię twoją pracę i nie chcę jakiś nagonek itp. Wiem, że nie trawisz mnie i mojej listy.

**Comment by gulson** [comment]
Bo lista jest dość słaba, ingeruje za mocno w kod stron internetowych a przez to pojawiają się często błędy - czyli blokowane są elementy, które nie powinny być blokowane.

@MajkiIT chociaż Ci @xMaap podziękował za to co zrobiłeś? Zaraportował szereg stron do blokad, narobiłeś się jak głupi, narobiłeś strat serwisowym internetowym i nie ma zwykłego dziękuję?  :)

**Comment by MajkiIT** [comment]
@gulson no na początku była mega słaba :P teraz nie jest tak źle :D . Wiem, że traktujesz mnie jak trutnia który tylko robi straty. Nie chcę robić Ci pod górkę itp. 

Podziękował ale nie wprost. Tym, że dodaje co znajdzie itp.

**Comment by xMaap** [comment]
@gulson gdyby twoim użytkownikom zakażało na elektrodzie to by wyłączyli adblocki, ale jak widać im nie zależy na tej twojej elektrodzie.
A co ja mam mu co każdy wątek pisać "ooooo dziękuje, że zablokowałeś reklamy na stronie X"?
Ja mu dziękuje jak 7 mln polskich internautów, którzy korzystają z jego filtra http://di.com.pl/ponad-75-mln-polskich-internautow-blokuje-reklamy-jak-reaguja-wydawcy-56205

**Comment by KonoromiHimaries** [comment]
> Bo lista jest dość słaba, ingeruje za mocno w kod stron internetowych

lista nie ingeruje w kod stron internetowych, nie ma takiej możliwości. musiała by być zainstalowana na serwerze wydawcy by cokolwiek takiego mogła zrobić. to użytkownicy listy na swoim końcu modyfikują kod strony poprzez oprogramowanie typu adblock. nasza lista nie jest niczemu winna, my tylko agregujemy elementy w postaci kluczy wygenerowanych maszynowo.

**Comment by gulson** [comment]
@xMaap bardzo dobrze, że wskazałeś ten artykuł. To teraz przeczytaj ten artykuł z zrozumieniem, cytuję "Żeby zatrzymać spadek, trzeba zacząć stosować mniej inwazyjne formy, które akceptują internauci. ". Dlatego zacząłem stosować mniej inwazyjne formy. Ale, jak widzisz to też chcesz blokować. To mam pytanie do Ciebie, jaką formę reklamy akceptujesz? Żadną? Skoro nawet link do youtube Ciebie razi.....

@KonoromiHimaries nie musisz mi tłumaczyć podstaw AdBlocka, lista ingeruje za bardzo kod w stron internetowych, eliminuje również nieinwazyjne formy reklamowe, często też uszkadza strony internetowy ukrywając treści niereklamowe. To, gdzie się odbywa ingerencja czy w przeglądarce klienta czy na serwerze nie ma znaczenia.

**Comment by xMaap** [comment]
@gulson Jak nie wiesz Kamilu po co są te linki blokowane to zapytaj się twoich słynnych moderatorów po co są blokowane, ale najlepiej to poszukaj w Google.

**Comment by gulson** [comment]
@xMaap standardowa odpowiedź osoby, która nie ma już więcej argumentów i zaczyna się w tym wszystkim gubić :)

**Comment by xMaap** [comment]
@gulson nie mam ochoty z tobą dalej prowadzić rozmowy, bo to nie ma sensu. Ty wiesz swoje ja wiem swoje.

**Comment by KonoromiHimaries** [comment]
> lista ingeruje za bardzo kod w stron internetowych, eliminuje również nieinwazyjne formy reklamowe

nie prowadzimy programu `"acceptable ads"` i nie mamy nic wspólnego z firmą `"eyeo GmbH"`

projekt jest tworzony przez społeczność na zasadach open source, dlatego też bardzo liczymy na to że wszystkie "błędy" będą zgłaszane za pomocą odpowiedniego formularza.

lista nie może ingerować w kod strony bez oprogramowania typu adblock lub innego zgodnego z jej formatem. to użytkownicy decydują się na "blokowanie treści" w waszym portalu, my nic takiego nie robimy.

nie odpowiadamy za wykorzystanie naszej listy w złej wierze i nie będziemy bierni w stosunku do oszczerstw kierowanych w naszą stronę.

**Comment by gulson** [comment]
"nie będziemy bierni w stosunku do oszczerstw kierowanych w naszą stronę.'

Nie za bardzo rozumiem, czy jestem zastraszany? :) 

To napiszę ponownie, tworzycie fatalnej jakości filtry, które uszkadzają strony internetowe (nie ma znaczenia, że w sposób pośredni przy pomocy AdBlock) a wydawcy z powodu Waszych działań ponoszą wymierne straty finansowe.

**Comment by xMaap** [comment]
A jak nie chcesz aby twoja strona była blokowana to pisz do twórców Adblock, Adblock Plus, uBlock Origin, AdGuard, AdClear, Nano Adblocker, AdNauseam, Opery, Brave, Firefox, DuckDuckGo Privacy Essentials, Decentraleyes, Ghostery, Disconnect, Privacy Badger, Pi-hole, Blokada, AdAway

Nie zapomnij jeszcze o NoScript, uMatrix, ScriptSafe, ponieważ one tak blokują twoją elektrodę, że ho ho.

**Comment by gulson** [comment]
@xMaap ale ja piszę do twórców filtrów, którzy piszą filtry eliminujące nawet najmniejsze, nieintruzyjne formy reklamowe. Do blokowania pozostałych reklam się już przyzwyczaiłem :)

Piszę też do twórców, którzy piszą filtry uszkadzające strony internetowe, na przykład kiedyś nie można było gifa otworzyć w nowym oknie przez Wasz filtr.
