### ISSUE TITLE
telemagazyn.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6232]
Autoplay
![](https://i.imgur.com/MeQ5QqF.png)

<details>
 <summary><b>Moja konfiguracja:</b></summary>

- Vivaldi 1.14.1077.45
-  Nano Adblocker v1.0.0.31
-  Nano Defender 13.32
-  Filtry https://gist.github.com/xMaap/28140ee9c3269f8b0ef356986563418a
</details>

**Comment by hawkeye116477** [comment]
@xMaap Wypróbuj to https://greasyfork.org/pl/scripts/30974-autoplay-disabled-for-html5-videos-pause-on-switch-tab albo https://greasyfork.org/pl/scripts/30271-html5-video-autoplay-blocker. Nano/uBlock niestety nie posiada możliwości blokowania autoplay, jak chcesz, żeby coś takiego było to może napisz do pingwina.
