### ISSUE TITLE
znaczkijakrobaczki.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#6238]
![image](https://user-images.githubusercontent.com/35370833/36250927-a68f0944-123f-11e8-9caf-30e4a55c137b.png) |
--- |

http://znaczkijakrobaczki.pl/

resztka komunikatu z facebookiem przy pierwszych odwiedzinach:

```
###ppsPopupBgOverlay
###ppsPopupShell_100_80828
```

Nie sprawdzane czy blokuje to lepiej social lub lista elementów natrętnych.

**Comment by krystian3w** [comment]
PPB.txt / Social.txt:

```
telewizja-cyfrowa.com##.ppsPopupFbLikeShell, #ppsPopupBgOverlay
```

czyli by raczej nie wycięło.

**Comment by KonoromiHimaries** [comment]
podawaj proszę linki w ` `
możesz też dołączyć do nas na discorda

**Comment by krystian3w** [comment]
15.02.2018 11:25 KonoromiHimaries <notifications@github.com> napisał(a):podawaj proszę linki w 
możesz też dołączyć do nas na discorda

**Comment by KonoromiHimaries** [comment]
@krystian3w martwię się że może stać się to samo co z xMaap 
wbij na discorda żeby zawsze być w kontakcie.
