### ISSUE TITLE
Google’s Chrome ad blocking arrives

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6239]
@MajkiIT napewno znajdziesz pl ver 

https://www.theverge.com/2018/2/14/17011266/google-chrome-ad-blocker-features

**Comment by xxcriticxx** [comment]
znalazlem

https://www.dobreprogramy.pl/Google-Chrome-sam-zablokuje-reklamy-dodatki-nie-sa-juz-potrzebne,News,86099.html

**Comment by MajkiIT** [comment]
@xxcriticxx Dziękuję

**Comment by krystian3w** [comment]
Blokada reklam co nie są user friendly... takie sobie i nie kompatybilne np. Z slimjet 17.
