### ISSUE TITLE
tag

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6243]
![capture](https://user-images.githubusercontent.com/15007183/36306105-4962e056-12e4-11e8-9d96-92eacc5c6598.PNG)

chyba cos sie zacielo bo nie widac 90 issues open

**Comment by MajkiIT** [comment]
hmmmm dziwne. Zobaczymy czy się samo naprawi.

**Comment by MajkiIT** [comment]
Tylko u nas jest ten błąd.

**Comment by xxcriticxx** [comment]
raczej idzie do gory 94 teraz

**Comment by hawkeye116477** [comment]
> If your GitHub badge errors, it might be because you hit GitHub's rate limits.
> You can increase Shields.io's rate limit by going to this page to add Shields as a GitHub application on your GitHub account. 

https://img.shields.io/github-auth

**Comment by xxcriticxx** [comment]
ta issue resolution tez chyba sie zaciela

**Comment by xxcriticxx** [comment]
dalej stock

**Comment by MajkiIT** [comment]
@hawkeye116477 @xxcriticxx zgłosiłem i już się poprawiło, ale nie do końca. Czekam na oficjalnego maila.

@xxcriticxx btw o wszystko Cię posądzałem, ale tym mnie zaskoczyłeś :D No ładnie tańczysz https://youtu.be/_jTjycyu7Dw

**Comment by xxcriticxx** [comment]
@MajkiIT widze ze union square odkryles w nyc :)
