### ISSUE TITLE
realmadryt.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6244]
![2018-02-16-realmadryt pl](https://user-images.githubusercontent.com/5884000/36307954-db7ff548-131e-11e8-97d6-d1d17b8ef5be.png)

puste sekcje reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.31
Nano Defender 13.33
Chrome 64.0.3282.167

</details>

**Comment by MajkiIT** [comment]
tego nie da się wyciąć, bo ukryję kolejny element.

**Comment by hawkeye116477** [comment]
@MajkiIT Jak się nie da, jak się da -> `realmadryt.pl#?#.bg:-abp-contains(reklama)`:smile:
