### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by SebaK666** [MajkiIT/polish-ads-filter#6245]
Czy jest możliwość zablokowania dolnego, czarnego paska zachęcającego do rejestracji? 
https://www.instagram.com/instagram/
Nawet zamknięcie go na jednym profilu powoduje, że na innym znów się pojawia. Z tego co widzę jest to niestety wartość zmienna. Sprawdźcie czy coś da się z tym zrobić.

**Comment by MajkiIT** [comment]
@SebaK666 a to nie pomaga ?
`instagram.com##._2pnef._cqw45`

**Comment by xxcriticxx** [comment]
@MajkiIT to sie caly czas zmienia

**Comment by hawkeye116477** [comment]
`instagram.com##div>section`
