### ISSUE TITLE
Quartic.pl - znowu wycięty

### ISSUE THREAD

**Issue by KerbenII** [MajkiIT/polish-ads-filter#6247]
Słuchajcie, rozumiem, że wrzucenie "na pałę":
`
||quartic.pl/$script,domain=~quartic.pl
`
rozwiązuje większość problemów dla dowolnej domeny, ale nie tędy droga.

Pisałem, że w razie problemów z zablokowaniem jakiejś naszej reklamy (chociaż na ten moment przeglądając zgłoszenia nie zauważyłem, żadnego takiego zgłoszenia) pomogę - i nawet podałem w którymś zgłoszeniu regułkę skutecznie wycinającą wszystkie nasze adservery (która cały czas działa).

Dlatego naprawdę nie jestem w stanie zrozumieć, dlaczego znowu wycinacie wszystkie nasze usługi, które świadczymy legalnie  (m.in. badania behawioralne, analitykę stron, podmiany produktów w ramkach sklepowych, cdn).

Mieliśmy już kiedyś rozmowę na temat danych, które zbieramy w sesji:
Zbieramy w sesji jedynie adresy produktów jakie użytkownik odwiedził (można to zweryfikować poprzez filtr TT w Network trackerze),
oraz robimy cookie maching, który dokonują adservery (już przez was zablokowane).

Byłym wdzięczny za ustosunkowanie się do powyższego, oraz jeszcze raz przypominam, że w razie jakichś problemów z regułką służę pomocą. Wystarczy mnie albo oznaczyć, albo wysłać maila.

### Zrzut ekranu
![panel](https://user-images.githubusercontent.com/15047492/36309831-60c6cd10-1326-11e8-9112-c62c2001f719.png)

### Link bezpośredni

- Adresy podane w networku

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1.  Zalogować się do naszego panelu
lub skorzystać z dowolnej naszej usługi

### Moja konfiguracja

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. 
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by xxcriticxx** [comment]
@KerbenII ty zyjesz wow ale jestem w szoku

**Comment by KerbenII** [comment]
Żyje, i jak widzisz odpowiadam na każde mention :)

**Comment by MajkiIT** [comment]
@KerbenII Nikt nie robi niczego na pałę. Twoje reguły nie są już aktualne a reklamy się pojawiły ==> https://github.com/MajkiIT/polish-ads-filter/issues/6221 . Nie ma konta ani nie jestem pracownikiem Waszej firmy aby móc to zweryfikować. Prośba o dokumentację aby ją przeanalizować.

**Comment by KerbenII** [comment]
Tutaj masz linka do rejestracji:
https://cp.quarticon.com/register/stepone

Możesz bez problemu założyć sobie konto
(po wyłączeniu adblocka, bo blokujecie
wszystkie nasze assety - nawet na serwerach
używanych tylko do serwowania panelu).

Nie mamy dokumentacji - w panelu możesz sobie
wszystko "wyklikać" (jeżeli chodzi o rekomendacje).

**Comment by gulson** [comment]
@KerbenII też mam z nimi problem, może połączymy siły? :)
Może też innych właścicieli portalów powiadomimy, co tu się wyprawia :)

**Comment by MajkiIT** [comment]
zapraszam serdecznie :P jak to było ... każdy ma takie problemy do jakich dorósł.

**Comment by MajkiIT** [comment]
@KerbenII nie macie dokumentacji swojego API ? Dziwne

**Comment by KerbenII** [comment]
Nie mamy - mamy tylko informację co trzeba wkleić na stronę.
