### ISSUE TITLE
rtvmaniak.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6251]
zacznij zakupy od CENEO + reklama

https://www.rtvmaniak.pl/9540548/premiery-netflix/

![capture](https://user-images.githubusercontent.com/15007183/36341180-400e9c00-13b8-11e8-989a-4c770034d8ab.PNG)

**Comment by xMaap** [comment]
Ja nie mam tego Ceneo
![](https://i.imgur.com/f7BYqye.png)

Ale za to mam 
![](https://i.imgur.com/m5Ga28l.png)
