### ISSUE TITLE
gtasite.net

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6254]
Reklama
![](https://user-images.githubusercontent.com/36385327/36343061-94cbc232-1407-11e8-8cd7-d229a01710a3.png)
Facebook + Google
![](https://user-images.githubusercontent.com/36385327/36343062-95e1709a-1407-11e8-9e66-c323db19b0a1.png)
![](https://user-images.githubusercontent.com/36385327/36343063-96ccfb8c-1407-11e8-87fd-1d951697cf88.png)

**Comment by hawkeye116477** [comment]
Na dole ikonkę mam, ale na górze nie widzę. Czyżby znowu tak jak kiedyś, na mojej rozdzielczości tego nie widać?

**Comment by xMaap** [comment]
@hawkeye116477 to chyba @MajkiIT dodał, że nie ma, ponieważ ja teraz również nie widzę i na gole i na górze.
![](https://user-images.githubusercontent.com/36385327/36363698-4d49b3e0-153f-11e8-8b91-27c2beedf2be.png)

Ale za to reklama jest 
![](https://user-images.githubusercontent.com/36385327/36363710-6ca4a2ae-153f-11e8-8c4f-5f3de8becf61.png)
