### ISSUE TITLE
Onet

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6257]
http://wzgodziezesoba.onet.pl/z-portfelem/zakladasz-start-i-inwestujesz-w-nowe-technologie-moze-po-pro.html
![](https://user-images.githubusercontent.com/36385327/36347281-f35ef836-1453-11e8-9c52-ac737f6a5d3c.png)
![](https://user-images.githubusercontent.com/36385327/36347283-ffe009ba-1453-11e8-99f5-a69d8fd23a20.png)

http://gotowanie.onet.pl http://magia.onet.pl http://magia.onet.pl

![](https://user-images.githubusercontent.com/36385327/36347301-4cd3952a-1454-11e8-9d13-6ff8c8a28cfa.png)

<details>
 <summary><b>Moja konfiguracja:</b></summary>

- Vivaldi 1.14.1077.50
-  Nano Adblocker v1.0.0.31
-  Nano Defender 13.32
-  Filtry https://gist.github.com/xMaap/28140ee9c3269f8b0ef356986563418a
</details>

**Comment by xxcriticxx** [comment]
@xMaap strzalki ladne robisz
