### ISSUE TITLE
motomi.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6259]
![](https://i.imgur.com/DBG3kJx.png)
https://motomi.pl/oferty/Peugeot/Partner/gwarancja-mechaniczna-klimatyzacja-100-przebieg/946f1979-9cb0-4522-a898-5f971d156a4f
![](https://i.imgur.com/P2pwqJo.png)
<details>
 <summary><b>Moja konfiguracja:</b></summary>

- Vivaldi 1.14.1077.50
-  Nano Adblocker v1.0.0.31
-  Nano Defender 13.32
-  Filtry https://gist.github.com/xMaap/28140ee9c3269f8b0ef356986563418a
</details>

**Comment by MajkiIT** [comment]
@KonoromiHimaries @hawkeye116477 macie ten baner ?

**Comment by xxcriticxx** [comment]
@MajkiIT ja mam WW van na main i serwiskredytowy na sub page
