### ISSUE TITLE
kresy.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6270]
![2018-02-21-reuters_ modernizacja przejsc granicznych miedzy ue a ukraina zakonczyla sie fia](https://user-images.githubusercontent.com/5884000/36470749-4529e1d6-16ec-11e8-97df-2d93004fd0fc.png)
`https://kresy.pl/wydarzenia/regiony/ukraina/reuters-modernizacja-przejsc-granicznych-miedzy-ue-a-ukraina-zakonczyla-sie-fiaskiem/`

sklep + wielki baner

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.32
Nano Defender 13.35
Chrome 64.0.3282.167

</details>

**Comment by MajkiIT** [comment]
@KonoromiHimaries sklepu nie mam... @hawkeye116477 @xxcriticxx zerkniecie ?

**Comment by xxcriticxx** [comment]
@KonoromiHimaries ja mam 14 lat i taxu nie place za granica

@MajkiIT wysprzyj kresy.pl sie pokazuje jak zejdziesz na dol i do gory znowu

mam takie cos jeszcze

![capture](https://user-images.githubusercontent.com/15007183/36534551-e90e7f66-1794-11e8-8fb0-34b02d4d977e.PNG)

**Comment by hawkeye116477** [comment]
Resztka na górze -> `kresy.pl##.avia_codeblock`
