### ISSUE TITLE
cksport.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6280]
![2018-02-22-cksport pl - sport kielce](https://user-images.githubusercontent.com/5884000/36535411-d49a2226-17c9-11e8-920d-6906a8b1361a.png)

puste sekcje reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.32
Nano Defender 13.35
Chrome 64.0.3282.167

</details>

**Comment by MajkiIT** [comment]
```
www.cksport.pl##.box:nth-of-type(1)
www.cksport.pl##.box:nth-of-type(3)
```
