### ISSUE TITLE
przewodnikduchowy.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6283]
![2018-02-22-10 falszywych przekonan o zwiazkach _ na czym polega zwiazek dwojga ludzi_](https://user-images.githubusercontent.com/5884000/36563326-100365ac-181a-11e8-9c21-4616fcfe6a73.png)
`http://przewodnikduchowy.pl/a/10-falszywych-przekonan-o-zwiazkach.php`

anty-adblock

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.32
Nano Defender 13.35
Chrome 64.0.3282.167

</details>

**Comment by MajkiIT** [comment]
`przewodnikduchowy.pl##.col-md-8 > div:nth-of-type(2)`
