### ISSUE TITLE
olx.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6287]
![2018-02-23-ogloszenia - sprzedam kupie na olx pl](https://user-images.githubusercontent.com/5884000/36599036-58e5656a-18ae-11e8-80cf-0dc7970a1565.png)

nie działa klik

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.33
Nano Defender 13.36
Chrome 64.0.3282.186

</details>

**Comment by hawkeye116477** [comment]
U mnie działa.

**Comment by MajkiIT** [comment]
@KonoromiHimaries u mnie też ok.

**Comment by KonoromiHimaries** [comment]
https://github.com/uBlockOrigin/uAssets/issues/1610#issuecomment-368133273

**Comment by MajkiIT** [comment]
@KonoromiHimaries ta reguła rozwiązuje problem ?

**Comment by hawkeye116477** [comment]
@MajkiIT U mnie działa, jak również takie coś podane przez @F4z działa -> `||googletagmanager.com/gtm.js$important,script,redirect=noopjs,domain=olx.pl`. Z tym, że oczywiście obie reguły należy dodać do listy tylko dla uBO, bo AdBlock/ABP i AdGuard nie obsługuje noopjs ani noopmp3, itp. Więc resztę podobnych reguł też należałoby przenieść, choć chyba tylko 2 są takie.

**Comment by MajkiIT** [comment]
@KonoromiHimaries @hawkeye116477 Dziękuje
