### ISSUE TITLE
chinytolubie.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6289]
![2018-02-23-strona o chinach najwazniejsze informacje- chinytolubie pl](https://user-images.githubusercontent.com/5884000/36602117-7694a8c4-18b7-11e8-868c-f8332474f459.png)

przycisk + tło

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.33
Nano Defender 13.36
Chrome 64.0.3282.186

</details>

**Comment by MajkiIT** [comment]
@hawkeye116477 popup od newslettera do ciebie ?

**Comment by hawkeye116477** [comment]
@MajkiIT Tak, zajmę się tym :smile:.

**Comment by MajkiIT** [comment]
@hawkeye116477 dziękuję
