### ISSUE TITLE
evertiq.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#6294]
Tło reklamowe do wycięcia.
Reguła dla uBlocka i AdGuarda -> `evertiq.pl##.centerCarpet:style(background-image: none !important;)`

Pozostaje tylko link, który jest nadal klikalny.

Ewentualnie: `||evertiq.pl/bin/evqNewsBot.js` lub `||evertiq.pl/bin/evqNewsTop.js` (wtedy powinno zniknąć tło i link również, ale jakieś długie te skrypty, nie wiem czy zablokowanie ich czegoś nie popsuje).

**Comment by krystian3w** [comment]
W chrome blokada skryptu nic nie daje, jakoś są doładowywane.

**Comment by hawkeye116477** [comment]
@MajkiIT W artykułach nadal w tle jest niewidzialny link. Trzeba jeszcze dodatkowo zablokować -> `||evertiq.pl/bin/evqReadBot.js`
