### ISSUE TITLE
cyfrowaekonomia.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6313]
![2018-02-24-cyfrowa ekonomia _ informacje blockchain kryptowaluty bitcoin litecoin](https://user-images.githubusercontent.com/5884000/36625484-999c08e4-1920-11e8-9c93-4d55ffbb2dff.png)

pusta sekcja partnerzy

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.33
Nano Defender 13.36
Chrome 64.0.3282.186

</details>

**Comment by hawkeye116477** [comment]
@MajkiIT Nadal jest pusta => `cyfrowaekonomia.pl##div.td-pb-row:nth-of-type(2)`
