### ISSUE TITLE
subiektywnieofinansach.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6314]
![2018-02-24-dostal rachunek za uslugi premium na 80 zl zablokowal je i stalo sie cos dzi](https://user-images.githubusercontent.com/5884000/36625596-e86935bc-1922-11e8-911d-7651e0feffa6.png)
`https://subiektywnieofinansach.pl/dostal-rachunek-za-uslugi-premium-t-mobile-80-zl-zablokowal-je-ale-stalo-sie-cos-dziwnego/`

uszkodzona strona

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.33
Nano Defender 13.36
Chrome 64.0.3282.186

</details>

**Comment by MajkiIT** [comment]
@KonoromiHimaries u mnie jest ok
@xxcriticxx @hawkeye116477 zerkniecie ?

**Comment by hawkeye116477** [comment]
@MajkiIT Dodaj `subiektywnieofinansach.pl#@#[class*="reklama"]` i będzie ok.

**Comment by MajkiIT** [comment]
@hawkeye116477 dziękuję
