### ISSUE TITLE
niedziela.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6315]
![2018-02-24-niedziela pl - artykul - wkrotce duze zmiany w kurii rzymskiej](https://user-images.githubusercontent.com/5884000/36625641-bbdf39f0-1923-11e8-9c92-4da0622d6837.png)
`http://niedziela.pl/artykul/34031/Wkrotce-duze-zmiany-w-Kurii-Rzymskiej`

uszkodzona strona

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.33
Nano Defender 13.36
Chrome 64.0.3282.186

</details>

**Comment by MajkiIT** [comment]
@KonoromiHimaries U mnie jest ok.
@xxcriticxx @hawkeye116477 zerknięcie ?

**Comment by hawkeye116477** [comment]
Jak zwykle, znowu lista Fanboy's Social Blocking List zawiniła.

**Comment by xxcriticxx** [comment]
umnie jest ok
