### ISSUE TITLE
flarrow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6334]
prawa strona

https://flarrow.pl/2018/wally-west-dolacza-do-legend-na-zdjeciach-z-odcinka-no-country-for-old-dads/

**Comment by krystian3w** [comment]
Widzę kolejno elementy:

- ramkę facebooka (wycinają filtry fanboy social lub nasze społecznościowe),
- może wewnętrzny sklep (lista matiego nie wycina),
- resztkę po reklamie (element oddzielający "reklama"):
`##.td_block_template_1.td-pb-border-top.td_uid_8_5a92dadb4eee4_rand.td_block_widget.td_block_text_with_title.td_block_wrap`,
- snapchat (społecznościówka):
`##.td_block_template_1.td-pb-border-top.td_uid_9_5a92dadb50180_rand.td_block_widget.td_block_text_with_title.td_block_wrap`.

 i w sumie tyle.

**Comment by krystian3w** [comment]
Widzę kolejno elementy:

- ramkę facebooka (wycinają filtry fanboy social ~~lub nasze społecznościowe~~),
- może wewnętrzny sklep (lista matiego nie wycina),
- resztkę po reklamie (element oddzielający "reklama"), czasem nawet dwa razy:
<sup><sub>~~`##.td_block_template_1.td-pb-border-top.td_uid_8_5a92dadb4eee4_rand.td_block_widget.td_block_text_with_title.td_block_wrap`~~</sub></sup> (losowe cyfry uid) <ul>`##.td_block_wrap:-abp-has(.td-pulldown-size:-abp-contains(Reklama))`,</ul>
- snapchat (społecznościówka):
<sup><sub>~~`##.td_block_template_1.td-pb-border-top.td_uid_9_5a92dadb50180_rand.td_block_widget.td_block_text_with_title.td_block_wrap`~~</sub></sup> (losowe cyfry uid) <ul>`##.td_block_wrap:-abp-has(.td-pulldown-size:-abp-contains(Snapchat))`.</ul>

 i w sumie tyle.

**Comment by hawkeye116477** [comment]
Wszystko prawie ok, tylko jeszcze trzeba wstawić znak zapytania pomiędzy hashami. uBlockowi niby odpowiada i tak i tak, ale ABP akceptuje tylko coś w stym stylu #?# :smile:

**Comment by krystian3w** [comment]
Na pewno  - o jedno sprawdzanie mniej, jeszcze chyba szybsze niż by spróbować to potraktować jakby to były znaczniki bez class / id i np. nth-of-type:

```
!flarrow.pl##.td-ss-main-sidebar > div:nth-of-type(2)
!flarrow.pl##.td-ss-main-sidebar > div:nth-of-type(3)
!flarrow.pl##.td-ss-main-sidebar > div:nth-of-type(4)
```
