### ISSUE TITLE
online-tv.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6336]
ad block na dole static?

http://online-tv.pl/bibliotekarze-4-cda-odcinek-7-ogladaj-online-ipla-player/2018/02/24

**Comment by krystian3w** [comment]
Raczej static, a przynajmniej w locie js nie generuje komunikatu na dole na nowo.

Raczej też nie dochodzi do blokowania odtwarzaczy / treści - linkują do ipli.

```
online-tv.pl###adblocktitle
online-tv.pl###modal
```
