### ISSUE TITLE
online-tv.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#6340]
Coś za dużo jest blokowane przez główny polski filtr.
`http://online-tv.pl/kolo-fortuny-odcinek-161-ipla-online-vod-tvp-ogladaj/2018/02/25`

**Comment by MajkiIT** [comment]
`online-tv.pl#@#[class*="reklama"]`

**Comment by MajkiIT** [comment]
@hawkeye116477 dziękuję
