### ISSUE TITLE
kreskowkazone.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#6343]
Przekierowania na strony z informacją o fałszywej wygranej. Wystarczy wcześniej kliknąć PPM i od razu widać, że link się zmienił na jakiś podejrzany.

`kreskowkazone.pl##a[href="//69oxt4q05.com/1451282.html"]`

**Comment by xxcriticxx** [comment]
@kasper93 Spider-Man oglondales? Czy sąsiadów tak jak ja?
