### ISSUE TITLE
kwejk.pl

### ISSUE THREAD

**Issue by mumaguma** [MajkiIT/polish-ads-filter#6348]
### Zrzut ekranu
http://i.share.pho.to/cd80e53e_o.png

### Link bezpośredni
kwejk.pl

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. wejście na stronę

### Moja konfiguracja
FF 58.0.2

**Rozszerzenia i skrypty:**
ublock origin

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. ublock filters
3. uBlock filters – Privacy​​​​​
4. uBlock filters – Abuse
5. EasyList
6. Polskie filtry ciasteczkowe

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
blur, ale chyba nie tylko: po ręcznym wywaleniu wartstwy z blurem widzę tylko dwa obrazki zamiast ośmiu (jak w przypadku bez ublocka)

**Comment by krystian3w** [comment]
Adblock alert - widać coś wycina żabę i komunikat.

U mnie problem omija [Nano Defender Integration](https://jspenguin2017.github.io/uBlockProtector/):

```
@@||kwejk.pl^$generichide
```

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję.

**Comment by mumaguma** [comment]
@krystian3w Dziękuję, działa :+1:
