### ISSUE TITLE
radiowroclaw.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6352]
![2018-02-28-portal radia wroclaw - radio wroclaw](https://user-images.githubusercontent.com/5884000/36791590-87e816c6-1c98-11e8-9177-b299abc9f2f2.png)

pusta sekcja reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.33
Nano Defender 13.36
Chrome 64.0.3282.186

</details>

**Comment by krystian3w** [comment]
`radiowroclaw.pl###BannerHolder`
