### ISSUE TITLE
zyciepabianic.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6355]
![2018-02-28-pabianice - miejski portal informacyjny i gazeta zycie pabianic](https://user-images.githubusercontent.com/5884000/36814901-415c4722-1cd9-11e8-8410-0ad4d3c28c81.png)

puste sekcje reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.33
Nano Defender 13.36
Chrome 64.0.3282.186

</details>

**Comment by krystian3w** [comment]
Napisy reklama jak są [chrome] (cyfry dziesiątek i jedności raczej się nie zmieniają szybko): `###ad_ban_5xx`

----

luki w lewej kolumnie robią `<br>`, po widoczności tagów `<center>` raczej twórca je wstawił ręcznie do szablonu.

Jakimś sprawnym filtrem można spróbować zablokować ich nadmiar `###col1 > br + br, #col1 > a + br` (pewnie część się pokrywa, więc ten by był nawet do optymalizacji).

----

Unoszenie prawej kolumny:
`###col3 > center:nth-of-type(1), #col3 > br:nth-of-type(1)`

----

Na chrome coś blokuje link do przetargu:

> ![image](https://user-images.githubusercontent.com/35370833/36845333-9b344574-1d56-11e8-97e5-7b00dbe498c5.png)

Link / grafikę do strony powiat.pabanice.pl można by odblokować (jeśli nie odblokuje to reklam jakie wycina reguła blokująca linki otwierające się w nowej karcie):

> 
![image](https://user-images.githubusercontent.com/35370833/36845416-efb8372c-1d56-11e8-8171-c62d64cc4ba6.png)
