### ISSUE TITLE
chelmno.com.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6361]
![2018-03-01-isi chelmno com pl](https://user-images.githubusercontent.com/5884000/36842574-575bbe68-1d4c-11e8-8190-7dae47be06d8.png)

reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.30
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by xxcriticxx** [comment]
`||chelmno.com.pl/wp-files/e32/5obspzf.png$image`
