### ISSUE TITLE
gazetalubliniecka.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6364]
![2018-03-01-gazeta lubliniecka tygodnik lokalny](https://user-images.githubusercontent.com/5884000/36842999-ccd725f0-1d4d-11e8-8703-1dc2cf010509.png)

reklama + pusta sekcja reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.30
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by krystian3w** [comment]
**Ja mam to w pop-upie**, coś go tobie rozwala i umieszcza statycznie treść (najprawdopodobniej).

`gazetalubliniecka.pl###popmake-15544`

`###text-2` - małe puste pole w lewej kolumnie
`###text-5` - patronaci

----

Za to po testach widzę że Easylist pl na przykładzie tej strony psuje przewijanie :confused:.

**Comment by MajkiIT** [comment]
`||gazetalubliniecka.pl/wp-content/plugins/popup-maker/assets/js/site.min.js$script` na brak suwaka
