### ISSUE TITLE
inforiders.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6365]
![2018-03-01-inforiders pl laczymy spolecznosci motocyklowe](https://user-images.githubusercontent.com/5884000/36843274-b8105bb8-1d4e-11e8-8909-549d0971c2b3.png)

reklama po prawej

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.30
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by krystian3w** [comment]
U mnie już coś wycina grafikę  (`||inforiders.pl^*^tvp.berlin.`) i zostaje sam widget z tekstem w nagłówku `###text-7`

**Comment by MajkiIT** [comment]
@krystian3w dziękuję
