### ISSUE TITLE
SMS do przemyslenia

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#637]
na sportowych stronach sie troche pozmienialao teraz SD sygnal leci za darmo a za HD trzeba wyslac sms. co chcesz zrobic z tym fantem?

**Comment by MajkiIT** [comment]
podaj jakiś adres a zobaczę.

**Comment by xxcriticxx** [comment]
http://mecze-hd.com/

http://imgur.com/HayNMyS

**Comment by xxcriticxx** [comment]
ta strona jest zablokowana http://darmowetransmisjehd24.pl/eurosport ale SD sygnal gra http://imgur.com/2CSwZki

**Comment by MajkiIT** [comment]
Mam już koncepcję. 

 http://darmowetransmisjehd24.pl/ do poprawy + reguły

**Comment by xxcriticxx** [comment]
ok
