### ISSUE TITLE
skionline.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#6371]
Reklama ( tło )

**Comment by krystian3w** [comment]
Y... blokują prawy klawisz myszy 😢 

```
||www.skionline.pl/system_banerowy/banery/gorna-austria_17-18_tapety/hochficht_tapeta_1920x1080.jpg
skionline.pl###tapeta_l
skionline.pl###tapeta_r
```
Chyba nie trzeba sięgać po blokadę skryptów, tło ukrywać css w uBlock / Adguard.

@hawkeye116477 / @KonoromiHimaries   `###popup_newsletter`, `###popup_tlo`  newsletter:

> ![obraz](https://user-images.githubusercontent.com/35370833/36937831-60004cd6-1f19-11e8-9197-99d0b4c1eb4d.png)

**Comment by hawkeye116477** [comment]
@krystian3w Ten popup dodałem już dzisiaj o 11:42 :smile:.

**Comment by krystian3w** [comment]
powinno działać bez spacji pomiędzy `none`, tylko funkcje obliczania wymiarów typu calc ich wymagają.
