### ISSUE TITLE
telepolis.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6373]
W sumie to nie wiem czy się coś takiego opłaca blokować, ale przekierowuje do Ceneo.
![](https://i.imgur.com/iNci4eJ.png)
<details>
 <summary><b>Moja konfiguracja:</b></summary>

- Vivaldi 1.14.1077.55
-  Nano Adblocker v1.0.0.33
-  Nano Defender 13.39
-  Filtry https://gist.github.com/xMaap/28140ee9c3269f8b0ef356986563418a
</details>

**Comment by KonoromiHimaries** [comment]
treść sekcji wydaje się być `kontentowa do reszty strony`, można to sklasyfikować jako `specjalizacja strony` i zachować ze względu na `akceptacje społeczną`.

dobro kulturowe przede wszystkim.

**Comment by hawkeye116477** [comment]
Mi się jeszcze pojawia antyadblock.
Fix na antyadblock -> `@@||www.telepolis.pl/js/ads_adv_telepolis_skrypt.js`
