### ISSUE TITLE
jedna lista pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6375]
@MajkiIT jest tylko jedna lista pl trzeba by to wlonczyc 

`#include adblock_ublock.txt`

**Comment by KonoromiHimaries** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock.txt#L24

**Comment by MajkiIT** [comment]
ale to wrzuca filtry dla Ubo do ogólnych

**Comment by xxcriticxx** [comment]
@MajkiIT przed tym jest `|` pajpa (czy jak tam to sie nazywa) czy ona tam powinna byc?

**Comment by KonoromiHimaries** [comment]
@xxcriticxx jest wykrzyknik `!` który powinien tam być by reguła działała poprawnie.
https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock.txt#L24

Sprawdzałeś czy to działa przed wykonaniem zgłoszenia?

**Comment by hawkeye116477** [comment]
Jest wszystko ok, przecież to `!#include adblock_ublock.txt` już tam jest.

**Comment by krystian3w** [comment]
https://pl.wikipedia.org/wiki/Kreska_pionowa i nie wiem po co spolszczasz do jednego słowa.

**Comment by xxcriticxx** [comment]
@hawkeye116477 thx za info
