### ISSUE TITLE
ziemiadrawska.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#6379]
http://www.ziemiadrawska.pl/Gangsterzy_z_Drawska_Pomorskiego_zatrzymani,n2712.html

Czerwony blur na cala strone przy wlaczonym nano adblockerze 

Moje listy : https://gist.github.com/gzenio22/4cee955ffac6ffce44cc00799ca76330

Pewnie przy okazji dostane opiermandol bo pewnie mam nie aktywne już jakieś listy wybaczcie ale ostatnio troche mi na głowę spadło mama po operacji tata do swojej się szykuje

**Comment by xxcriticxx** [comment]
@gzenio22 zmiany w kodi swiecie widziales?

**Comment by gzenio22** [comment]
Taaa i tak nie korzystalem z wtyczek Ramica wystarczy ze raz mi wyjebalo Virtualboxa w kosmos wole Incrusion np

**Comment by gzenio22** [comment]
Wiesz naj bardziej brakowalo by mi szukajki zauwazylem tez ze resolveurl robi wała i nie wszystkie linki widzi w kodi moze mi brakowac co najwyzej wtyczki szukajka

**Comment by xxcriticxx** [comment]
wejdziesz na strone:)

**Comment by gzenio22** [comment]
to nie to samo Xd

**Comment by xxcriticxx** [comment]
dont worry znajdzie sie cos nowego

**Comment by hawkeye116477** [comment]
@gzenio22 Do usunięcia:
 "https://raw.githubusercontent.com/azet12/PopupBlocker/master/PPB_uBlock_AdGuard.txt" (te filtry są już zintegrowane z główną listą Polskie Filtry Elementów Irytujących)
Reszta już nie jest rozwijana:
"https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt",
 "https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-list-ubo.txt",
"https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-list-notubo.txt",

**Comment by gzenio22** [comment]
to postawie od zera to wszystko powiedzcie mi tylko ktore filtry polecacie? :)
