### ISSUE TITLE
trt.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6380]
mam podwojny player

https://www.trt.pl/film/qbqg82xojw/VID-20170618-153208

![capture](https://user-images.githubusercontent.com/15007183/36936266-041f10ca-1ed1-11e8-9924-0f8b954bba00.PNG)

**Comment by krystian3w** [comment]
Błąd trt.pl - raczej nie blokujemy jakiegoś skryptu co psuje nakładkę na odtwarzacz.

Ewentualnie można by prostym skryptem ukryć pasek przeglądarki (biały) jakimś prostym javascript co usunie atrybut "`controls`" i zostanie ten z nakładki od trt.pl

**Comment by xxcriticxx** [comment]
@krystian3w posiadasz nano?

**Comment by krystian3w** [comment]
W Firefox (13.31 - przed tym jak mozilla zbanowała) / Vivaldi / Chrome tak, ale on nie blokuje - chyba że w wideo jest komunikat o adblocku, to takiego nie mam

**Comment by xxcriticxx** [comment]
ok przewaznie nano dublowal playery
