### ISSUE TITLE
strefammo.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6381]
![2018-03-03-strefammo pl - portal o grach mmo](https://user-images.githubusercontent.com/5884000/36937415-2e011a5e-1f13-11e8-9bc5-f916a3945199.png)

sekcja reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.30
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by krystian3w** [comment]
`###text-3`
