### ISSUE TITLE
forumrowerowe.org

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6388]
cookies

![capture](https://user-images.githubusercontent.com/15007183/36947544-3011719e-1f9b-11e8-8e2b-ae3081cf50c8.PNG)

**Comment by hawkeye116477** [comment]
`###elGuestTerms[data-role="guestTermsBar"]:not(body):not(html)`

**Comment by krystian3w** [comment]
> Filtr statyczny **`###elGuestTerms`** znajdujący się w:
>
> * [Fanboy’s Cookiemonster List](https://raw.githubusercontent.com/ryanbr/fanboy-adblock/master/fanboy-cookiemonster.txt)

> Filtr statyczny **`###elGuestTerms[data-role="guestTermsBar"]:not(body):not(html)`** znajdujący się w:
>
> * [I don't care about cookies](https://www.i-dont-care-about-cookies.eu/abp/)
