### ISSUE TITLE
webinsider.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6392]
![2018-03-04-wtyczka ublock origin blokuje tresc niektorych artykulow czyli wyraz reklama](https://user-images.githubusercontent.com/5884000/36950263-fb1bb180-1ff3-11e8-8b6e-4e7277811525.png)
`https://webinsider.pl/www-ublock-origin-blokuje-artykuly-z-kategoria-tag-reklama/`

anty-adblock + uszkodzona strona

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.30
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by hawkeye116477** [comment]
`webinsider.pl#@#[class*="reklama"]`
