### ISSUE TITLE
webinsider.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6395]
![2018-03-05-webinsider - internet widziany od srodka _ blog nie tylko o technologii finan](https://user-images.githubusercontent.com/5884000/36967984-80e76b7a-2061-11e8-9ba8-6f47040cb0f9.png)

anty-adblock

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.30
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Znowu to masz? U mnie już tego nie ma. Aktualizowałeś filtry?

**Comment by MajkiIT** [comment]
@hawkeye116477 

```
Postanowiłem jednak wdrożyć prosty mechanizm, którego zadaniem jest wykryć sytuację, gdy kontener z artykułem został zablokowany, i wyświetlić informację dla „ofiary uBlocka/AdBlocka” o tym, że treści nie ma, bo… blokuje reklamy:

<script type="text/javascript">
 jQuery(document).ready(function($) {
 if(!$('article').is(":visible")) {
 // AdBlock info
 setTimeout(function() {
 alert("Info dla osoby z AdBlockiem/uBlockiem");
 }, 5000);
 }
 });
</script>
```

**Comment by hawkeye116477** [comment]
No to @KonoromiHimaries musi podać link do tego artykułu.

**Comment by xxcriticxx** [comment]
trzeba prosic pingwina o pomoc?

**Comment by MajkiIT** [comment]
@xxcriticxx jeśli można prosić, to tak.

**Comment by xxcriticxx** [comment]
done

**Comment by hawkeye116477** [comment]
Od pingwina -> `webinsider.pl##script:inject(setTimeout-defuser.js, AdBlock)`
