### ISSUE TITLE
towideo.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6398]
![2018-03-05-to wideo zawsze i wszedzie](https://user-images.githubusercontent.com/5884000/36975464-75f50786-207a-11e8-9586-fcb145c9359c.png)

anty-adblock

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.33
Nano Defender 13.39
Chrome 64.0.3282.186

</details>

**Comment by MajkiIT** [comment]
`@@/showads.js$script,domain=towideo.pl`
