### ISSUE TITLE
Alltube.tv

### ISSUE THREAD

**Issue by Ubuntuslav** [MajkiIT/polish-ads-filter#6401]
Alltube zmieniło domenę z .TV na .PL
Proszę o aktualizację filtrów

**Comment by MajkiIT** [comment]
@Ubuntuslav ale nie ma przekierowania z tv na pl ...

**Comment by MajkiIT** [comment]
@Ubuntuslav @KonoromiHimaries pojawiło się dużo nowych skryptów. Obleciałem regexem ... powinno być OK

**Comment by xxcriticxx** [comment]
narazie dziala zajebiscie!

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/37029755-85cf4982-2106-11e8-86bb-a1790ad1c309.PNG)

**Comment by Ubuntuslav** [comment]
Chodzi o konkretne playery. streamcherry.com i streamango.com...
