### ISSUE TITLE
Na nowo z konfigurowana lista filtrow

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#6405]
Jest ok czy czegoś mi brakuje? :)

https://gist.github.com/gzenio22/a70d696f7848b31b079a7a471b4d0b2e

**Comment by MajkiIT** [comment]
1. KAD ?
2. No coin?
3. Polish Privacy ?

**Comment by xxcriticxx** [comment]
No coin sie przyda na strony z filmami

**Comment by gzenio22** [comment]
@MajkiIT a Kad nie jest juz wspierany?

**Comment by KonoromiHimaries** [comment]
@gzenio22 ostatnia aktualizacja 14 dni temu, więc raczej jest.
https://raw.githubusercontent.com/azet12/KAD/master/KAD.txt

**Comment by xxcriticxx** [comment]
Napewno się przyda na twoja limitowana internet

**Comment by hawkeye116477** [comment]
@gzenio22 Fanboy's Social Blocking List jeszcze brakuje.

**Comment by gzenio22** [comment]
@xxcriticxx Nie mam juz limitu na neta :D @hawkeye116477 Podeslesz linka? bo nie bardzo wiem ktora to lista na Certyficate

**Comment by hawkeye116477** [comment]
@gzenio22 Ta lista jest już w Nano do wyboru.

**Comment by gzenio22** [comment]
@hawkeye116477 wielkie dzięki zrobione :)

**Comment by gzenio22** [comment]
Wszystko śmiga zamykam :)
