### ISSUE TITLE
czasnahistorie.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6406]
![2018-03-06-blekitna krew polskiej gospodarki ksiaze drucki-lubecki czyli patriota gospoda](https://user-images.githubusercontent.com/5884000/37006294-fe736492-20d7-11e8-93f3-5a13866fa6d0.png)
`http://czasnahistorie.pl/redakcja-czashistorii-pl/blekitna-krew-polskiej-gospodarki-ksiaze-drucki-lubecki-czyli-patriota-gospodarczy/`

pusta sekcja reklama + tło

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.30
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by MajkiIT** [comment]
```
czasnahistorie.pl##.td-title-align.td-block-title
||czasnahistorie.pl/wp-content/uploads/20*/*/*tlo*.jpg
```
@hawkeye116477 masz jakiś pomysł na klikalne tło?

**Comment by hawkeye116477** [comment]
Usunięcie tła:
```
czasnahistorie.pl##body:style(background-image: none !important;)
```
A z tym linkiem, można by to jakoś tak zrobić:
`czasnahistorie.pl##.td-ad-background-link:style(pointer-events: none;)`. Ale wtedy popsuje się zaznaczanie tekstu, więc może @F4z coś lepszego wymyśli.
