### ISSUE TITLE
bonprix.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6410]
![2018-03-06-bonprix sklep internetowy odziez damska meska i dziecieca](https://user-images.githubusercontent.com/5884000/37031947-1b7ad566-2141-11e8-953d-4eab3ee6121a.png)

uszkodzona strona

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.30
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by MajkiIT** [comment]
u mnie ok... @hawkeye116477 zerkniesz ?

**Comment by hawkeye116477** [comment]
@MajkiIT To jest zdaje się jakaś kurtyna po popupie. U mnie popup się wyświetla, bo korzystam tylko z naszych Polskich Filtrów Annoyance :smile:. Także można zamknąć, ja się tym zajmę.
