### ISSUE TITLE
Shinden.pl

### ISSUE THREAD

**Issue by hiroszi** [MajkiIT/polish-ads-filter#6415]
Shinden.pl nie działa na firefox z ADP
![obraz](https://user-images.githubusercontent.com/11850685/37049336-e36b6de0-2170-11e8-8c22-7d8992aa12a4.png)

**Comment by MajkiIT** [comment]
@hiroszi jakiś link, bonie mogę wygrzebać tego ...

**Comment by MajkiIT** [comment]
@hiroszi update i test proszę.

**Comment by hiroszi** [comment]
@MajkiIT wielkie dzięki! wszystko działa sprawnie 👍  🔥

**Comment by MajkiIT** [comment]
@hiroszi Prośba. Możesz sprawdzić czy po dodaniu tej reguły pojawi Ci się alert o włączonym adblocku ?
`shinden.pl##iframe[src^="https://reklama.shinden.eu/"]`
