### ISSUE TITLE
Fili.tv

### ISSUE THREAD

**Issue by Ubuntuslav** [MajkiIT/polish-ads-filter#6416]
Reklama showmax-a

<img src='https://i.imgur.com/fkcQFws.png' />

[https://fili.tv/film/holy-terror-2017/10163](https://fili.tv/film/holy-terror-2017/10163)

* Moje ustawienia
  * Chrome  64.0.3282.186 (x64)
  * uBlock Origin  v1.15.2
  * <a href="https://openload.co/f/69pT__74A2E">Filtry</a>

**Comment by MajkiIT** [comment]
Ja tego nie mam .... @KonoromiHimaries @hawkeye116477 zerkniecie ?

**Comment by KonoromiHimaries** [comment]
@MajkiIT ja mam

**Comment by xxcriticxx** [comment]
geo lock @MajkiIT VPN please 

![capture](https://user-images.githubusercontent.com/15007183/37057516-a23d3ec2-2155-11e8-908c-034ac599dc52.PNG)

**Comment by krystian3w** [comment]
U mnie też nie ma.

**Comment by KonoromiHimaries** [comment]
@MajkiIT u mnie było, ale teraz nie ma.

**Comment by Ubuntuslav** [comment]
U mnie też reklama zniknęła...
