### ISSUE TITLE
firesub.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6417]
![2018-03-06-firesub net _ strona glowna](https://user-images.githubusercontent.com/5884000/37051451-c04b18f0-2176-11e8-84b4-d06b8c9f9192.png)

uszkodzona strona

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.30
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by MajkiIT** [comment]
ta strona jest na KAD
