### ISSUE TITLE
euractiv.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6427]
![2018-03-07-astronomiczne ceny gazu w polsce i europie - euractiv pl](https://user-images.githubusercontent.com/5884000/37088573-193f142a-21fe-11e8-9c47-13be297867fa.png)
`https://www.euractiv.pl/section/energia-i-srodowisko/news/astronomiczne-ceny-gazu-polsce-europie/`

puste sekcje po reklamie

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.30
Nano Defender 13.31
Chrome 64.0.3282.140

</details>

**Comment by krystian3w** [comment]
* `##h6:-abp-contains(Advertisement)` / `##h6 > span`
* `##.ea-sponsorship-section-wrap.ea-sponsorship-section-logo`

:question:
