### ISSUE TITLE
Błąd Ublock Origin na Firefox Android i jedno pytanie.

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#6432]
Tak jak w temacie. Chodzi o Ublock Origin na Firefox Android. Filtry mam wszystkie + wszystkie z certificate.it (z wyłączoną opcją ignoruj filtry kosmetyczne). Błąd już jest dłuższy czas. Polega na tym, że UBO nie ukrywa napisu "reklama" np. dobreprogramy.pl.
![screenshot_2018-03-07-18-21-49](https://user-images.githubusercontent.com/16944478/37108027-36c91c2e-2236-11e8-81ab-de908c38597d.png)
I
![screenshot_2018-03-07-18-22-05](https://user-images.githubusercontent.com/16944478/37108048-42b3d01a-2236-11e8-801b-f8d94a85a450.png)

Czy można coś zaradzić na to?

I pytanie. Czy posiadacie jakiś filtr ochrony przed anty adblock dla UBO ?

Bo nie wierzę takim wynalazkom jak nano adblocker/defender.

**Comment by hawkeye116477** [comment]
@seba2282 Adblock Warning Removal List i nasza polska lista też chroni przed antyadblockiem. Ale dlaczego nie wierzysz Nano? Kod źródłowy obu jest na GitHubie, więc nie ma powodu by nie ufać, co innego uBlock Plus Adblocker, uBlock Plus, uBlock Adblocker Plus, to zwykłe klony zapewne z jakimś malware

**Comment by KonoromiHimaries** [comment]
ja mam ten napis na ff nightly z nano

**Comment by KonoromiHimaries** [comment]
> to zwykłe klony zapewne z jakimś malware.

to po prostu śmieszne
![2018-03-07-ublock plus - chrome web store](https://user-images.githubusercontent.com/5884000/37112841-efe076dc-2243-11e8-88e9-c1aec75d818e.png)

**Comment by seba2282** [comment]
Na PC nie mam tego napisu z UBO + Firefox (1920x1080), natomiast na Android z FF + UBO tak. Nie wierzę w żadne nano, bo to twory tego samego autora, który stworzył aak cont (zbytnio nie działało) i te niemiłe doświadczenie mnie urzekło. Sorka

**Comment by krystian3w** [comment]
U mnie też są na telefonie z Nano Defender i Firefox 58.0.2

Można by spróbować sobie ręcznie je zablokować, są chyba maksymalnie 6 takich tekstów, jedynie raz widziałem problem, że się zmienia kolejność i może wyciąć treść artykułu.

**Comment by MajkiIT** [comment]
@krystian3w wychodzi na to, że strona mobilna jest inaczej zbudowana niż ta na PC. Coś podziałamy.

**Comment by seba2282** [comment]
@MajkiIT, jeszcze jedno pytanie. Dlaczego po jakimś czasie (najczęściej drugiego dnia) filtry ciasteczkowe (te wasze) za china nie chcą się aktualizować w ublock origin dla Microsoft Edge?

**Comment by MajkiIT** [comment]
@seba2282 ale jest jakiś błąd czy pobierają się i nic się nie zmienia?

**Comment by xxcriticxx** [comment]
@hawkeye116477 jakies idea why?

**Comment by seba2282** [comment]
@majkiit, Przeinstaluję UBO, jest przez chwilę dobrze. Potem jak pojawi się aktualizacja filtrów, to ciasteczka w ogóle się nie aktualizują. Jest taki trójkąt i symbol załącznika na czerwono. Biorę klikam aktualizuj i nadal błąd. I tak w kółko.

**Comment by hawkeye116477** [comment]
@seba2282 uBO dla Edge z tego co wiem, to ma masę błędów. Sporo osób mówi, że jest słabej jakości. Lepiej napisany jest Nano Adblocker, którego chyba nie ma jeszcze w M$ Store, ale możesz ręcznie go załadować -> `https://github.com/NanoAdblocker/NanoCore/releases`.

**Comment by krystian3w** [comment]
Błąd możesz spróbować zobaczyć w dzienniku żądań (niestety nie zwróci raczej konkretnego numeru błędu a np. błąd połączenia - mam taki przy liście domen malware (za duża albo antywirus utrudnia aktualizacje)).

---

Przy okazji Nano informuje o błędach w regułach:

> Cosmetic filtering – invalid filter: `#bannerDBB:style(height: 10px !important;)!`
> Cosmetic filtering – invalid filter: `#popmake-15544, #text-2, ###text-5`
> 

https://github.com/MajkiIT/polish-ads-filter/blob/856010d098a5941b2849fa0d64dde18b5545b8b4/polish-adblock-filters/adblock.txt#L894

https://github.com/MajkiIT/polish-ads-filter/blob/45d91fadc2192367c699ec92852e7ed2a787949b/polish-adblock-filters/adblock_ublock.txt#L198

W pierwszej problem robią trzy kratki (na końcu), w drugiej widać przypadkowy wykrzyknik (na końcu).

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję

**Comment by seba2282** [comment]
Odnośnie tego błędu dla ciasteczek. Mam tylko tyle : błąd sieci i nie można zaktualizować. Co ciekawe, reszta (12 filtrów ze strony certificate it) aktualizuje się bezproblemowo.

**Comment by krystian3w** [comment]
Sprawdź czy nie masz starego linka co robi dodatkowe przekierowanie na github (jak przywracasz ustawienia z starej kopii - jakieś takiej 2-3 letniej bez odświeżenia). Chociaż pewnie to nie to :thinking:.

**Comment by seba2282** [comment]
Jeżeli z FF działa... Tylko nie z Edge... To raczej nie to.

**Comment by krystian3w** [comment]
Hey dałoby radę sprawdzić te "reguły" co wycinają w wersji PC:

https://github.com/MajkiIT/polish-ads-filter/blob/9185cb395597eeeff5d41277f0f28ea0aa824505/polish-adblock-filters/adblock.txt#L3868

:question: 

Wstępnie wycina połowę, a resztę musiałbym sprawdzić w podglądzie źródła lub debugując po USB/Wi-Fi, czymś się jakoś różnią w liniowym stylu.

**Comment by MajkiIT** [comment]
@krystian3w z tego kojarzę to tło ...

**Comment by krystian3w** [comment]
OK, niefortunnie użyłem "co", chodziło mi na ile ona psują  mobilny portal / mobilnego bloga.

Bo ma "lepszą" skuteczność niż np. kilka reguł z obliczaniem elementów w drzewie.

**Comment by seba2282** [comment]
Ciekawostka. UBO na FF Android sobie u mnie nadal nie radzi, natomiast Adguard extension ze wszystkimi filtrami już tak.

**Comment by KonoromiHimaries** [comment]
@seba2282 jeśli uważasz że to błąd rozszerzenia, zgłoś tutaj
https://github.com/gorhill/uBlock/issues

**Comment by seba2282** [comment]
@krystian3w , masz może recepturę jak naprawić ten błąd z brakiem ukrywania "reklama" na DP przez Ublock Origin i (jak pisałeś) przez Nano Adblocker?

**Comment by hawkeye116477** [comment]
@seba2282 Może wypróbuj Yandex Browser i uBO dev albo Nano Adblocker z Chrome Store

**Comment by krystian3w** [comment]
@seba2282 Dodałem sobie tamtą regułę **z wyłączeniem, że ma działać tylko w szablonie desktopowym** i wycięła 3/5 tekstów, te dwa muszą mieć inny kolor czy inną wartość dla stylu liniowego.


Wtedy dla drugiej reguły można by dodać by się aktywowała tylko w widoku mobilnym  - niestety uBlocki nie chętnie chcą podpowiedzieć co kryje się w `style="..."` i nie mogę skonfigurować debugowania zdalnego po USB / Wi-fi.

**Comment by seba2282** [comment]
@krystian3w, ok. @MajkiIT jakieś pomysły?

**Comment by krystian3w** [comment]
U mnie chyba już zniknęło, nie chciało mi się szukać czy doszły jakieś dwie nowe reguły pod wersje mobilną albo wywalenie Nano Defendera rozwiązało problem - dla przykładu jego lista do uBlock / Nano odblokowywała reklamy na softpedii (może ktoś do niego zgłosił źle zablokowany element strony przez Easylist / Easyprivacy).

**Comment by seba2282** [comment]
U mnie na DP nadala wyświetla napis "reklama".

**Comment by krystian3w** [comment]
http://krystian3w.5v.pl - próbowałem, bez strony ale frame powoduje blokadę subskrypcji.

**Comment by krystian3w** [comment]
Jakby reguła przestała wycinać, to najpewniej przez przebudowanie reklam: https://github.com/MajkiIT/polish-ads-filter/issues/6791

**Comment by seba2282** [comment]
@MajkiIT zgłaszam kolejny błąd. Nie będę zakładać kolejnego tematu. MS Edge/Firefox Android + Ublock Origin. Wszystkie filtry bez ignorowania kosmetycznych + filtry z cerificate.it Po naprawieniu błędu związanego z dobreprogramy.pl, coś jakby zaczęło blokować niektóre filmy na stronach miniminiplus.pl i teletoonplus.pl Tzn. jest to w momencie, kiedy ubo zablokuje reklamę z tvn adserver redcdn, po naciśnięciu play przy filmiku jest czarny ekran i się nie ładuje. Myślę, że przypadkowo są blokowane jakieś reguły związane z playerami TVN. Czy możnaby prosić o przyjrzenie się sprawie?

**Comment by MajkiIT** [comment]
@seba2282 tutaj masz ten błąd ?
https://www.miniminiplus.pl/minisite/bob-budowniczy/wideo/poznajcie-druzyne-bob/

**Comment by seba2282** [comment]
Jeżeli wpiszę normalnie www.miniminiplus.pl/filmy i wybiorę film, np. ten:
https://www.miniminiplus.pl/filmy/z/bob-budowniczy 
I w każdym jednym przy którym jest blokowane redcdn wśród domen. Moim zdaniem przypadkowo usunęliści reguły na tvn adocean i cdn tvn. 
Na miniplus+ : 
@@||s1-player5.cdntvn.pl 
I
@@||tvn.adocean.pl

Teletoon+ :
@@||teletoonplus.pl^$generichide 
I
@@||tvn.adocean.pl^$domain=teletoonplus.pl

Bo domniemam, że blokująca reguła redcdn (co jest najważniejsza), jest dobra : 

||redcdn.pl/*Adserver/*.mp4$media,empty,important

**Comment by seba2282** [comment]
@MajkiIT, jakieś informacje?

**Comment by seba2282** [comment]
Sprawa nie jest prosta. nano defender też nic nie daje. Takie same efekty, z tymże po instalacji nano adblocker są przepuszczane śmieci z redcdn. Adguard też ma podobny problem, co ubo. Z tymże, jak z ubo wyłączę filtr ciasteczek i dodam wspomniane reguły (bez redcdn adserver) to tak jakby trochę ruszyło. Teraz AG z kolei jest blokowany przez odtwarzacze tvn player. A UBO na Edge nadal nie posiada aktywnych opcji z WebRT... Ale wracając, to coś jest skopane na filtrach i skryptach anti adblock. I to polskich.

**Comment by xxcriticxx** [comment]
@seba2282 dalej jesteśmy na stronie mobile czy na full website?

**Comment by seba2282** [comment]
MS Edge + Adguard. Coś tam działa (wszystkie filtry bez Reek I z odznaczonym "nie blokuj pożądanych reklam").
I np. ten film ładuje się - czarny ekran i nic dalej. 
https://www.teletoonplus.pl/filmy/pokaz/ogon-w-ruch-my-little-pony-equestria-girls-rainbow-rocks

**Comment by seba2282** [comment]
A co do mobile, to Adguard.apk + Chrome. Włączone wszystkie filtry (bez Reek) + filtrowanie DNS i HTTPS. I tu jest komunikat o używaniu adblockera.

**Comment by F4z** [comment]
Jeśli chodzi o Edge to proszę dodaj te dwie reguły i sprawdź czy działa:
`@@||redcdn.pl/*/TVN-Adserver/*.mp4$xmlhttprequest,domain=teletoonplus.pl`
`||redcdn.pl/*/TVN-Adserver/*.mp4$media,empty,important,domain=teletoonplus.pl`

W przypadku Androida dodaj do wykluczeń z filtrowania DNS adocean.
`@@||adocean.pl^$app=com.adguard.dns`

**Comment by seba2282** [comment]
Dodałem bez ",domain=" i niby działa też z miniminiplus.pl. Sprawdzę teraz AG 
Czy tam masz reklamy (na android)?

**Comment by F4z** [comment]
Jak sprawdzałem tutaj - https://www.teletoonplus.pl/filmy/pokaz/ogon-w-ruch-my-little-pony-equestria-girls-rainbow-rocks to po dodaniu tej reguły `@@||adocean.pl^$app=com.adguard.dns` do filtrów użytkownika film wyświetlał się bez reklam.

**Comment by seba2282** [comment]
Powiem uczciwie. Bez ",domain=" nawet playe.pl działa. A sprawdź na Android jeszcze:
https://www.miniminiplus.pl/filmy/pokaz/my-little-pony-duchy

**Comment by seba2282** [comment]
Dobra. Na razie działa wszystko (minimini+, teletoon+). Na PC Edge do Adguard dodałem:
@@||redcdn.pl/*/TVN-Adserver/*.mp4$xmlhttprequest
I
||redcdn.pl/*/TVN-Adserver/*.mp4$media,empty,important

A do Adguard.apk:
@@||adocean.pl^$app=com.adguard.dns
