### ISSUE TITLE
Prośba o usunięcie domeny firmowej z listy

### ISSUE THREAD

**Issue by pySilver** [MajkiIT/polish-ads-filter#6436]
https://github.com/MajkiIT/polish-ads-filter/blob/5d733514dc8a54f6cc4db10523e6d2a88c6ce228/polish-pihole-filters/adguard_host.txt#L3662

Witam, proszę o usunięcie z listy adresu strony firmowej: **convertiser.com** (Nie rozumiem, czemu tam trafiła).

**Comment by MajkiIT** [comment]
@pySilver to lista Adguarda. Ja tylko wyciągnąłem domeny. Skrypt parsuje plik i tyle. Najlepiej napisz do nich.

**Comment by MajkiIT** [comment]
@pySilver może dlatego jest na liście http://make-cash.pl/convertiser-program-partnerski-do-automatycznej-monetyzacji-tre%C5%9Bci-t10026/
