### ISSUE TITLE
gala.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6448]
![2018-03-08-malgorzata godlewska_ remix parodie i memy z siostrami godlewskimi foto wideo](https://user-images.githubusercontent.com/5884000/37162348-4eb3aba0-22f5-11e8-822e-eac4ba3f8dac.png)
`http://www.gala.pl/artykul/malgorzata-godlewska-parodie-memy-remix-siostry-godlewskie-171222041649`

sklep

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by MajkiIT** [comment]
`gala.pl##.tracdelight-box`
