### ISSUE TITLE
kropleinternetu.biz

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#6459]
cookies - `###cooc_container`

**Comment by blocker999** [comment]
Przy okazji jeszcze reklama:

![kropleinternetu biz](https://user-images.githubusercontent.com/23176832/37222508-aada34ca-23cd-11e8-967b-575d88778031.png)

**Comment by krystian3w** [comment]
Filtry sieciowe

 *   `||www.kropleinternetu.biz/images/mobilevikings400x185.jpg`

Filtry kosmetyczne

 *  `##img[src="images/mobilevikings400x185.jpg"]`
 *   `##a[href="https://mobilevikings.pl/polecam/rz4lPasi"]`

**Comment by krystian3w** [comment]
telefonii nie wycina jeszcze :wink:
