### ISSUE TITLE
teleshow.wp.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#6461]
Tło

https://teleshow.wp.pl/nie-wiadomo-czy-sie-smiac-czy-krytykowac-take-me-out-to-kuriozum-6227780063065729a

**Comment by MajkiIT** [comment]
u mnie tła brak ... 
@blocker999 @KonoromiHimaries zerkniecie ?

**Comment by gzenio22** [comment]
Tez nie mam tla czysto

**Comment by blocker999** [comment]
@MajkiIT Teraz niemam ale było niewiem alboi czekaj abo zamykaj.
