### ISSUE TITLE
wnp.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6463]
![2018-03-10-parlamentarny pl_ z zycia sejmu senatu i rzadu rp](https://user-images.githubusercontent.com/5884000/37237832-b455b7e4-2419-11e8-9de5-558bfa823d3f.png)

puste sekcje reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by MajkiIT** [comment]
@KonoromiHimaries Nadal to masz ?
