### ISSUE TITLE
historykon.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6464]
![2018-03-10-historykon _ historia w zasiegu reki](https://user-images.githubusercontent.com/5884000/37242546-8b9e8f68-246b-11e8-8fcc-e8735ce98d89.png)

reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by gzenio22** [comment]
historykon.pl###custom_html-2

Chyba działa? :)
