### ISSUE TITLE
inowroclaw.info.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6465]
![2018-03-10-inowroclaw portal informacyjny miasta inowroclawi okolic - inowroclaw info pl](https://user-images.githubusercontent.com/5884000/37242850-495e0804-2470-11e8-9af0-5c5553cbc7b3.png)

reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by gzenio22** [comment]
inowroclaw.info.pl###__cmcmedia_upid_26
Resztka po wysuwającym sie bannerze

inowroclaw.info.pl##.row:nth-of-type(4) > .fl.w250

Reklamy ze screena ale pewnie ktoś wymyśli coś lepszego
