### ISSUE TITLE
wiadomosci.dziennik.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6472]
![capture](https://user-images.githubusercontent.com/15007183/37253575-c14293be-2509-11e8-8932-8d8462b345a2.PNG)

**Comment by MajkiIT** [comment]
`wiadomosci.dziennik.pl##.tpl_static_html`

**Comment by KonoromiHimaries** [comment]
`dziennik.pl##.tpl_static_html`

**Comment by xxcriticxx** [comment]
jest wiecej na main 

![capture](https://user-images.githubusercontent.com/15007183/37253701-83ed0ca4-250b-11e8-9a16-9eaf1e9cb969.PNG)

**Comment by MajkiIT** [comment]
```
dziennik.pl##.tpl_static_html
dziennik.pl###br-box-partner
```
