### ISSUE TITLE
Za szeroki filtr [id*="reklama"] ukrywa pozycję menu "reklamacja"

### ISSUE THREAD

**Issue by malpka** [MajkiIT/polish-ads-filter#6491]
### Informacje o stronie
Własna aplikacja webowa. Problem powoduje menu programu, które zawiera pozycje "reklamacje".  Definicja filtra wycina słowo "reklama" występujące w `id`. Problem wydaje mi się na dość szeroki i może zablokować sporo polskich webowych systemów ;) . Nie mogę określić domeny, ponieważ nie wiem gdzie docelowo będzie stał serwer.

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
Wstawić na stronie element z atrybutem `<div title="Reklamacje" id="rozliczenia/reklamacje"><!--bindings={}-->Reklamacje<!--bindings={}--></div>`

### Techniczne szczegóły błędu
Wpis który sprawia problem: 
`~wirtualnemedia.pl,~tczewska.pl,~procamp.agency,~rp.pl,~sportowememy.pl,~intercity.pl##[id*="reklama"]`

### Moja konfiguracja
**Przeglądarka internetowa:** Chrome 65.0.3325.162

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka

**Comment by MajkiIT** [comment]
@malpka dziękuję. Na razie wyłączyłem ten filtr. Coś pomyślę.
