### ISSUE TITLE
skript.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#6498]
### Zrzut ekranu
![shu_ao7mpo](https://user-images.githubusercontent.com/18230443/37410345-b74c90fa-27a0-11e8-8544-9f63c1b419c9.png)

### Link bezpośredni
https://skript.pl/

adblock detect + belka reklam z prawej strony + przycisk usuń reklamy w nagłówku (anty-dotacyjne)

### Moja konfiguracja
**Przeglądarka internetowa:** Firefox 59.0

**Rozszerzenia i skrypty:**
- uBlock 1.15.11b13
- Nano Defender 13.43

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. Integracyjne filtry nano defender
3. EasyList

**Comment by Libter** [comment]
Forum za darmo się nie utrzymuje, a 1.5 zł miesięcznie za usunięcie reklam nie uważam za wygórowaną cenę. Wstyd zgłaszać coś takiego.

**Comment by KonoromiHimaries** [comment]
pusta sekcja na topce

![2018-03-14-forum - skript pl - najlepsze skrypty minecraft](https://user-images.githubusercontent.com/5884000/37412104-9450af2e-27a4-11e8-87eb-3bd2de537d59.png)

```
skript.pl###ipsLayout_contentWrapper > .adsbygoogle:nth-of-type(1)
```

**Comment by MajkiIT** [comment]
@RikoDEV @KonoromiHimaries adblocka nie mam .... @hawkeye116477 zerkniesz?

**Comment by xxcriticxx** [comment]
ja tez nie mam

**Comment by krystian3w** [comment]
```
! prawa
skript.pl###ipsLayout_sidebar

! topka
skript.pl###ipsLayout_contentWrapper > .adsbygoogle:nth-of-type(1)

! stopka
skript.pl##.adsbygoogle:nth-of-type(2)
```

Brak okienka o adblocku i opcji opłaty - może dla zalogowanych aktywne 🤣

**Comment by krystian3w** [comment]
```
pl##.adsbygoogle
```

Na ich stronie nie działa ani w podglądzie blokowania nano 🤔

**Comment by RikoDEV** [comment]
Skrypt w stopce od adblocka:
```

      	<script>
          $(function() {
            if($('.adsbygoogle').html() !== undefined && $('.adsbygoogle').children().length == 0) {
              alert('Korzystanie z forum jest darmowe dzięki reklamom, prosimy o wyłączenie adblocka i kliknięcie OK.\nBanery można wyłączyć za symboliczną opłatą na skript.pl/reklamy');
              location.reload();
            }
          });
      	</script>
```
