### ISSUE TITLE
kuchenny.com.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6514]
![2018-03-14-kuchnia nie tylko do gotowania - porady - _sniezka_ - kuchenny com pl](https://user-images.githubusercontent.com/5884000/37425785-de94c302-27c4-11e8-8231-f1a480951985.png)
`http://www.kuchenny.com.pl/2108-9-kuchnia-nie-tylko-do-gotowania.html`

reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by MajkiIT** [comment]
@KonoromiHimaries nie dorzucaj, bo nie wyrabiam :P
