### ISSUE TITLE
zblogowani.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6521]
![2018-03-15-babka cytrynowa _ kulinaria _ zblogowani](https://user-images.githubusercontent.com/5884000/37481305-b2677dfc-2881-11e8-8dfb-3aced098e5b1.png)
`https://zblogowani.pl/wpis/31511122/babka-cytrynowa`

uszkodzona strona

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by hawkeye116477** [comment]
U mnie jest ok.
