### ISSUE TITLE
czatek.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6522]
![2018-03-15-czatek pl](https://user-images.githubusercontent.com/5884000/37481724-c369afc0-2882-11e8-9ff8-3850e45aa9b4.png)

uszkodzona strona

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Logger się kłania. A z niego wynika, że Polskie Listy nic tu nie blokują.
