### ISSUE TITLE
bejsment.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6523]
![2018-03-15-bejsment polish newspaper toronto](https://user-images.githubusercontent.com/5884000/37482938-c50e2984-2885-11e8-987b-9e0336ac3118.png)

reklamy

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by MajkiIT** [comment]
`bejsment.com##.widget_sp_image-image-link`
