### ISSUE TITLE
blog.pl - oczyszczenie filtrów

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#6524]
Blogi onetu (blog.pl) zostały usunięte. Z tego względu proponuje oczyszczenie filtrów z blogów w tej domenie.

### Link bezpośredni
blog.pl

### Moja konfiguracja
**Przeglądarka internetowa:** Firefox 59.0

**Rozszerzenia i skrypty:**
- uBlock 1.15.11b13
- Nano Defender 13.43

**Comment by krystian3w** [comment]
bloog.pl (WP) też zostanie zamknięty z końcem marca, jak ma jakieś reguły to też można pomyśleć nad ich usunięciem w kwietniu.

**Comment by MajkiIT** [comment]
@krystian3w @RikoDEV Dziękuję

**Comment by blocker999** [comment]
to ja od siebie dorzuce ze dopiero ma być zamknięty " ding " ( interia )

![ding](https://user-images.githubusercontent.com/23176832/37513867-8dc5ee04-2906-11e8-99df-060e86d63c4a.png)

**Comment by MajkiIT** [comment]
@blocker999 również dziękuję

**Comment by blocker999** [comment]
A to dorzuce jeszcze że Onet zamyka serwis Republika WWW 30 marca a agora już zamkła strone Ludzie.gazeta.pl
