### ISSUE TITLE
GROUP intel strony w wersji europejskiej

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#6525]
https://github.com/MajkiIT/polish-ads-filter/blob/dfd6e7a0b2196fbdc7907ae20d96a285df00c3a2/cookies_filters/adblock_cookies.txt#L1285

`##div[class*="cookie"]` Wycina treść strony:

> ![image](https://user-images.githubusercontent.com/35370833/37508479-8109abd2-28f3-11e8-962c-9de78c6ebaea.png) |
> --- |

```
intel.*#@#div[class*="cookie"]
```

---

<div align="center">

**`https://www.intel.pl/content/www/pl/pl/support/detect.html`**

</div>

---

Wycina też na innych stronch europejskich np. angielskiej czy francuskiej - więc jakby jakaś Polonia z Europy chciała zaktualizować sterowniki  to też im pewnie wytnie.

<div align="center">

**`https://www.intel.co.uk/content/www/uk/en/support/detect.html`**

</div>

<div align="center">

**`https://www.intel.fr/content/www/fr/fr/support/detect.html`**

</div>

Tyle, że w Nano nie można zignorować reguły  z 1285 linii lub wycinana jakoś inna (Nano jakby zignorował listę domen).

> ![image](https://user-images.githubusercontent.com/35370833/37509516-f02eb5d0-28f7-11e8-80ac-6bea69bd553a.png) |
> --- |

Pomaga coś w rodzaju:

```
intel.*#@#div[class*="cookie"]
```

**Comment by krystian3w** [comment]
Wycina też na innych strona europejskich np. angielskiej czy francuskiej - więc jakby jakaś Polonia z Europy chciała zaktualizować sterowniki  to też im pewnie wytnie.

**Comment by MajkiIT** [comment]
@krystian3w dziękuję za analizę.
