### ISSUE TITLE
antyradio.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6531]
Cookies
![zrzut ekranu z 2018-03-16 19-42-29](https://user-images.githubusercontent.com/36385327/37538844-367d5848-2952-11e8-82c0-3368d36da815.png)

**Comment by hawkeye116477** [comment]
Tutaj tak samo, to jest generowane przez skrypt, więc najpierw skrypt musi wygenerować element, a potem dopiero reguły mogą ukryć, dlatego są lagi. Może `script:inject` coś pomoże, ale to już @F4z musiałby się tu wypowiedzieć.
