### ISSUE TITLE
azorek.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6532]
Cookies
![zrzut ekranu z 2018-03-16 19-47-58](https://user-images.githubusercontent.com/36385327/37539073-f766f0c8-2952-11e8-9d6d-182084af347e.png)

**Comment by krystian3w** [comment]
U mnie wycina:

![obraz](https://user-images.githubusercontent.com/35370833/37540239-86a44620-2956-11e8-8466-2480b5a0e287.png)

Trochę wolno działa i na sekundę widzę animacje jak się wysuwa i po chwili znika.

**Comment by krystian3w** [comment]
Dziwne jakby filtr wycinał natychmiastowo:

><table><tr><td>
>
>Filtr statyczny **`azorek.pl##.giodoContainer`** znajdujący się w:
>
> *   I don't care about cookies
>
></td></tr></table>

**Comment by hawkeye116477** [comment]
> Trochę wolno działa i na sekundę widzę animacje jak się wysuwa i po chwili znika.

Niestety tak działają filtry kosmetyczne, elementy chowają się dopiero po załadowaniu.

**Comment by krystian3w** [comment]
Ale jak dodałem sobie listę "I don't care about cookies" z regułą dla tej strony to ona działa wyjątkowo szybciej niż ogólna z Polskiej pod "giodo.Containery".

**Comment by hawkeye116477** [comment]
To nie wiem czy opłaca się dać taką nieogólną, bo to chyba nie tylko na tej stronie taki jest problem.
Niech @MajkiIT się wypowie, bo to tak w ogóle to chyba jego reguła.

**Comment by MajkiIT** [comment]
Jeśli jest to możliwe to zostawmy tak jak jest. Tak jak mówi @hawkeye116477 takich stron może być dużo. Może to wynikać z tego, że blocker przeszukuje kod strony i szuka *cookies* a 2 drugiej regule szuka konkretnego tekstu.
