### ISSUE TITLE
poki.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6536]
http://poki.pl/g/slither-io
Cookies + pozostałości po reklamie + social (na dole strony również jest)
![zrzut ekranu z 2018-03-17 01-02-36](https://user-images.githubusercontent.com/36385327/37549310-ec4d24ba-297e-11e8-8724-37e23ae57cb8.png)

**Comment by hawkeye116477** [comment]
Ciastek nie ma, Mikuś już zjadł :smiley:.
