### ISSUE TITLE
miniminiplus.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6538]
Cookies
![zrzut ekranu z 2018-03-17 01-14-07](https://user-images.githubusercontent.com/36385327/37549459-9b45feaa-2980-11e8-86ea-dafa2501f2a6.png)
Reklama
![zrzut ekranu z 2018-03-17 01-14-26](https://user-images.githubusercontent.com/36385327/37549461-a001102e-2980-11e8-8a75-a607c161b778.png)

**Comment by krystian3w** [comment]
> <table><tr><td>
>
> Filtr statyczny `miniminiplus.pl##.cookies` znajdujący się w:
>
> *   Polskie Filtry Ciasteczkowe
>
> </td></tr></table>

i


> <table><tr><td>
>
> Filtr statyczny `pl##div[class*="cookie"]` znajdujący się w:
>
> *  Polskie Filtry Ciasteczkowe
>
> </td></tr></table>

**Comment by hawkeye116477** [comment]
@xMaap Nie ma wody na pustyni.
