### ISSUE TITLE
alekinoplus.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6539]
Wycięta treść 

![zrzut ekranu z 2018-03-17 01-23-00](https://user-images.githubusercontent.com/36385327/37549574-c62a1380-2981-11e8-91cb-e7ec688846f2.png)

**Comment by MajkiIT** [comment]
@xMaap u mnie jest ok.
@KonoromiHimaries @hawkeye116477 zerkniecie ?

**Comment by hawkeye116477** [comment]
@MajkiIT U mnie też ok

**Comment by KonoromiHimaries** [comment]
![2018-03-17-z milosci do filmu - ale kino](https://user-images.githubusercontent.com/5884000/37556413-d676b6de-29f5-11e8-8fca-4c50edb32a9a.png)

**Comment by xxcriticxx** [comment]
strona jest ok i nawet geo lock nie posiada
