### ISSUE TITLE
tvnplayer.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#654]
prosty sposob na zablokowanie reklam na tvnplayer.pl:
edycja jako administrator pliku hosts (c:\windows\system32\drivers\etc) i dopisanie na koncu dwoch linijek:
127.0.0.1 tvn.adocean.pl
127.0.0.1 r.dcs.redcdn.pl/http/o2/tvn-adserver

**Comment by MajkiIT** [comment]
testowałeś to?

**Comment by xxcriticxx** [comment]
ja jestem po za granicami kraju bez proxy niedam radu umnie. o adocean.pl gdzies pisalem hyba wczesnej https://github.com/MajkiIT/polish-ads-filter/issues/491. ty hyba to szybcej przetestujesz odemnie

**Comment by xxcriticxx** [comment]
ja to znalazlem na innym forum

**Comment by xxcriticxx** [comment]
for player.pl try:

Code: Select all
    @@|http://tvn.adocean.pl/_*/ad.js?*
    @@||tvn.adocean.pl/files/js/ado.js
    @@||pagead2.googlesyndication.com/pagead/show_ads.js*$domain=player.pl
    @@||googleads.g.doubleclick.net^$image,domain=player.pl
    @@||google.com^$image,domain=player.pl
    @@||s2.tvnplayer.cdntvn.pl/bundles/tvnplayer/img/*

**Comment by xxcriticxx** [comment]
@@||player.pl$elemhide
