### ISSUE TITLE
gosc.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6540]
Cookies

**Comment by krystian3w** [comment]
> <table><tr><td>
>
> Filtr statyczny `gosc.pl##body > div:not([id]):not([class])[style*="position"][style*="fixed"], body > div:not([id]):not([class])[style*="position"][style*="absolute"]` znajdujący się w:
>
>  *  I don't care about cookies
>
> </td></tr></table>

> <table><tr><td>
>
> Filtr statyczny `gosc.pl##body > div:not([id]):not([class])[style*="position"][style*="fixed"] znajdujący się w:
>
>  *  Polskie Filtry Ciasteczkowe
>
> </td></tr></table>

**Comment by hawkeye116477** [comment]
@xMaap Nie ma wody na pustyni.

**Comment by krystian3w** [comment]
@xMaap  a wielbłądy nie chcą dalej iść.
