### ISSUE TITLE
kryptoraport.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6545]
![2018-03-17-kryptoraport wszystko o kryptowalutach i technologii blockchain](https://user-images.githubusercontent.com/5884000/37554885-6466a79a-29df-11e8-9a82-17764d5bed92.png)

pusta sekcja reklama + ukrywa wykresy giełdowe

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by MajkiIT** [comment]
@hawkeye116477 #@#.ccc-widget:not(body):not(html)
