### ISSUE TITLE
Blocker (CHR) Opery a filtry zewnętrzne

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#6547]
Hej wpadłem na coś ciekawego :D jak wszyscy wiem w operze jest bloker reklam wbudowany ale wcześniej tez nie wiedziałem że można tam dodać własną liste filtrow myślicie że warto o tym powiadomić ludzkość? :D czy to gra nie warta świeczki?

**Comment by KonoromiHimaries** [comment]
nadal bardziej opłaca się zainstalować ublock origin niż używać zintegrowanego adblockera opery.

**Comment by krystian3w** [comment]
Nie wycina elementów kontekstowo, więc robią się luki na stronach.
