### ISSUE TITLE
ysf.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#656]
http://ysf.pl/2/687474703A2F2F7261706964752E6E65742F323131343432383437342F5A6F6F746F7069612E323031362E4D442E504C4455422E484443414D2E587669442D4B69542E617669

Wyłącz reklamę i przejdź do pobierania pliku >>

**Comment by MajkiIT** [comment]
tak samo jest bez adblocka

**Comment by xxcriticxx** [comment]
reklama http://ifilefinder.com/
