### ISSUE TITLE
eskago.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6583]
http://www.eskago.pl/radio/eska-warszawa
![zrzut ekranu z 2018-03-19 05-29-12](https://user-images.githubusercontent.com/36385327/37578051-7d99aff2-2b36-11e8-8798-73c403babc00.png)

**Comment by MajkiIT** [comment]
@xMaap a nie masz alertu nawet mimo wyłączonego ADB?

**Comment by xxcriticxx** [comment]
@MajkiIT z wylaczonym ubo i nano wszystko dziala

![capture](https://user-images.githubusercontent.com/15007183/37590127-ad68ab64-2b3d-11e8-8d2e-ffab6e9785cb.PNG)

**Comment by krystian3w** [comment]
```
@@||eskago.pl^$generichide
```

Niby coś odtwarza.

Ale potem blokuje Nano Defender, po włączeniu - chyba pingwin musiałby się przyjrzeć.

**Comment by xMaap** [comment]
@MajkiIT z wyłączonym Nano Adblocker dalej wyskakuje aby wyłączyć, ale po wyłączaniu jeszcze Defender już jest ok.

**Comment by krystian3w** [comment]
Trzeba by przekleić do pingwina, bo na białe listy w nano defender możemy się nie doczekać :rofl:

**Comment by krystian3w** [comment]
Nano defender 13.47 zaktualizowany, jak macie Firefox to musicie poprosić xlollomanx o nową wersje (nie wiem czy dodaje poprawki pod Firefox poza testowaniem zmian).

I chyba na obecną chwilę nie trzeba dodawać `@@||eskago.pl^$generichide` (a poszukać co blokuje okładkę i tytuł muzyki - może jakiś skrypt / xmlrequest) - chyba, że pod Adblock / Adblock Plus (jak tam odblokowuje).

**Comment by MajkiIT** [comment]
@krystian3w dziękuje
