### ISSUE TITLE
bzykanie.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#659]
sie przezucam na porno wiecej reklam :)

**Comment by MajkiIT** [comment]
hmmm zaskoczyłeś mnie :D

**Comment by xxcriticxx** [comment]
naprawde jest coraz ciezej znales reklamy/cookies

**Comment by MajkiIT** [comment]
wiem wiem. Z jednej strony to dobrze :D

**Comment by xxcriticxx** [comment]
hyba wszystkie popularne strony jusz sa przerobione

**Comment by MajkiIT** [comment]
I know
