### ISSUE TITLE
tryton.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#661]
reklama

http://tryton.com.pl/promo/Intel_ComputeStick/Intel_ComputeStick.html

**Comment by MajkiIT** [comment]
to jakiś baner czy przekierowanie?

**Comment by xxcriticxx** [comment]
http://tryton.com.pl/index.php jest na samym dole

banner inter stick 

teraz jest kingston ssd

**Comment by xxcriticxx** [comment]
po lewej jest flash ad multikino 2 bilety
