### ISSUE TITLE
zgorzelec.info

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#6622]
Cookies

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/37791497-aa671ec2-2e09-11e8-93ba-58b72ecb200f.png)

**Comment by xxcriticxx** [comment]
@krystian3w zgorzelec.inf,o = zgorzelec.info

poprawilem tytul tego watku

`zgorzelec.info##.l-cookie-law`
