### ISSUE TITLE
forum.purepc.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6632]
![zrzut ekranu z 2018-03-21 07-37-09](https://user-images.githubusercontent.com/36385327/37697024-bb23222c-2cda-11e8-9a1d-bd2fcb406540.png)

**Comment by MajkiIT** [comment]
U mnie jest to wycinane.

**Comment by xMaap** [comment]
Nie mam pojęcia. Aktualizowałem filtry, sprawdzałem na Firefox, Vivaldi, Opera, Chrome i dalej mam to samo. Jak coś to forum.purepc.pl###elGuestTerms i co ciekawe w Fanboy’s Cookiemonster List jest już ###elGuestTerms.
Nawet sprawdzałem w Moje Reguły samo ###elGuestTerms i informacji o Cookes nie blokuje. Blokuje dopiero po dopisaniu forum.purepc.pl.

**Comment by xxcriticxx** [comment]
ja tez tego nie widze

**Comment by KonoromiHimaries** [comment]
![2018-03-21-forum - purepc pl - forum dyskusyjne](https://user-images.githubusercontent.com/5884000/37714316-8bcd4194-2d19-11e8-8bfd-adef9c9f1450.png)

**Comment by krystian3w** [comment]
Może na stronie jest jakaś reguła podobna do `^$generichide` lub błąd jak z wp `autokult.pl`

Jak nie było jakiś poprawek to u mnie też nie ma i wycina `###elGuestTerms[data-role="guestTermsBar"]:not(body):not(html)`

**Comment by hawkeye116477** [comment]
Nie ma wody na pustyni.
