### ISSUE TITLE
grupa gazet z pustym polem nad headerem

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#6664]
https://plonszczak.pl/
https://gpr24.pl/
https://gazetabilgoraj.pl/
https://golub-cgd.pl/
https://rypin-cry.pl/
https://wabrzezno-cwa.pl/
https://brodnica-cbr.pl/

Oto kilka gazet z pustym polem nad hederem ale zapewne jest ich więcej dlatego proponuje regółe ogólną: 
`pl###top-reklama`

**Comment by krystian3w** [comment]
plonszczak.pl - adblock alert, z losowym id
