### ISSUE TITLE
salesbeehive.com

### ISSUE THREAD

**Issue by matt08** [MajkiIT/polish-ads-filter#6666]
salesbeehive.com - skrypt śledzący od salesbee.co/pl / www.salesbee.pl

Proponuję dodanie do filtrów prywatności.

Używany np. na www.alkoholeswiata.com

**Comment by xxcriticxx** [comment]
@matt08 jaka jest nazwa tego skryptu?

**Comment by matt08** [comment]
`salesbeehive.com/salesbee.js`

**Comment by MajkiIT** [comment]
@matt08 Dziękuję
