### ISSUE TITLE
jak dodac filtry w wbudowanym blokerze w operze 52

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#6667]
czy jest jakis sposob, aby, wbudowanym blokerze w operze 52, dodac filtry cookies, miejsca po reklamach itp? jak daje to nie dziala.

**Comment by KonoromiHimaries** [comment]
jak opera, to tylko z ublockiem

**Comment by xxcriticxx** [comment]
bylo gdzies opisane ze nie da rady

**Comment by xxcriticxx** [comment]
see #6547

**Comment by hawkeye116477** [comment]
Jak to się nie da, jak się da, klikacie zarządzaj listami i tam gdzie macie dodaj witrynę, to wklepujecie link do listy i entera robicie.

**Comment by lukjan32** [comment]
tak mam i nadal sa

**Comment by KonoromiHimaries** [comment]
@lukjan32 musisz zgłosić problem do supportu opery
https://bugs.opera.com/wizard/desktop

**Comment by lukjan32** [comment]
dawno juz zglosilem

**Comment by hawkeye116477** [comment]
@lukjan32 Ale co jest, ciasteczka? Jeżeli gdzieś są, to po prostu oznacza tyle, że ten ich bloker nie obsługuje takich reguł. Na liście ciasteczkowej są reguły `abp-contains` i `abp-has,` które ABP obsługuje, a zwykły Adblock chyba nie, ten od Opery to nie wiem jak tam jest, to jedna wielka niewiadoma, nie ma nigdzie napisane co on konkretnie obsługuje.

**Comment by lukjan32** [comment]
mi chodzilo o komunikaty o cookies. jak dodalem do wbudowanego blokera, to nadal byly komunikaty.

**Comment by hawkeye116477** [comment]
@lukjan32 A na której stronie te komunikaty? Bo jak ja sprawdzałem, to znikały, ale to zależy jeszcze gdzie, bo on pewnych reguł nie obsługuje, dlatego na niektórych stronach nadal mogą być komunikaty o ciasteczkach.

**Comment by lukjan32** [comment]
np, napisy24.pl lub satkurier.pl

**Comment by krystian3w** [comment]
Coś popsuli w 52 (a niby mieli roszerzyć funkcjonalność wbudowanego blokera), bo 51 wycina na `statkurier.pl` (nawet umie usuwać wykrywać adblocka - jak włączyłem polską listę główną to komunikaty zniknęły o tym zniknęły).

Po aktualizacji już na obu cookies nie wycinała.

Próbowałem pliku z dysku z dwoma wariantami na 52 i oba nie działały:
<table><tr><td>

```
[Adblock Plus 2.0]
!napisy24.pl
###ca_banner

!satkurier.pl
##.cc_banner-wrapper
```

</td><td> 


```
[Adblock Plus 2.0]
!napisy24.pl
napisy24.pl###ca_banner

!satkurier.pl
satkurier.pl##.cc_banner-wrapper
```

</td></tr></table>

Bo myślałem, że selektory css `not(...)` to dla Opery za duże wyzwanie.

**Comment by lukjan32** [comment]
aha, zglosze problem.

**Comment by krystian3w** [comment]
>  Na liście ciasteczkowej jest parę reguł `:-abp-contains(...)`, które ABP obsługuje, a zwykły Adblock chyba nie.

Jak sprawdzałem to też obsługuje. Opera oczywiście takiej reguły nie rozumie ☀️.

Ogólnie to wygląda jakby Opera nie radziła sobie z dynamicznymi elementami z javascript, gdzie inne dodatki sobie radzą choćby po "lagu".
