### ISSUE TITLE
ekologia.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6668]
![2018-03-23-zmiana czasu na letni wskazowki zegara do przodu - czas letni _ ekologia pl](https://user-images.githubusercontent.com/5884000/37803583-e9b3dfc2-2e2f-11e8-91f9-490646bb8fef.png)
`http://www.ekologia.pl/ciekawostki/zmiana-czasu-z-zimowego-na-letni-czemu-sluzy-zmiana-czasu,15110.html`

sklep

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.18
 ND 13.47
 Chr 65.0.3325.181
</details>

**Comment by KonoromiHimaries** [comment]
@xxcriticxx przecież nie możemy jednych traktować gorzej, a drugich lepiej.

**Comment by xxcriticxx** [comment]
@KonoromiHimaries  bys niechcial sobie kupic olejku z konopii?

**Comment by KonoromiHimaries** [comment]
@xxcriticxx jak będę chciał, to znajdzie najodpowiedniejszy sklep i dokonam zakupu.
nie ma potrzeby żeby wyświetlały mi się reklamy produktów których nie potrzebuje.

**Comment by MajkiIT** [comment]
@xxcriticxx bo linki kierują do stron zewnętrznych. To teraz jakaś moda się zrobiła.
