### ISSUE TITLE
nowapoczta.wp.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6674]
Reklamy. Też przydałoby się zalogować i zobaczyć czy nie ma tam reklam.

**Comment by MajkiIT** [comment]
@xxcriticxx @hawkeye116477 @KonoromiHimaries zerkniecie u mnie czysto

**Comment by xxcriticxx** [comment]
@xMaap stworz nam konto testowe i ktos sie loguje i sprawdzi co tam sie dzieje

![capture](https://user-images.githubusercontent.com/15007183/37862790-549fb460-2f29-11e8-8499-62959ddb1211.PNG)

**Comment by blocker999** [comment]
wystarczy zalogować się na stare dane akurat mam tam jedno konto i po zalogowaniu się stwierdzam że jest czysto

**Comment by xxcriticxx** [comment]
Czyli mamy wersie Pro za darmo

**Comment by blocker999** [comment]
prawie bo spamu to tu niebrakuje

**Comment by krystian3w** [comment]
Musi być to najlepiej stare konto co ma około tyle co wirtualna polska gdy uruchomiła pocztę +/- 5 lat.

Na koncie z 2008 mam wciąż starą pocztę - nie przenieśli mnie na nowe serwery i ograniczony panel zarządzania kontem.
