### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#6692]
adblock detect

![29514142_1985070358189255_1599451770_o](https://user-images.githubusercontent.com/21177361/37908205-c7cdd78e-3107-11e8-9db9-ef34fa21d20a.png)

**Comment by MajkiIT** [comment]
@krystian3w @gzenio22 update i testujemy.

**Comment by gzenio22** [comment]
@MajkiIT U mnie hula jak talala :)

**Comment by krystian3w** [comment]
U mnie też: 

> 
![obraz](https://user-images.githubusercontent.com/35370833/37929796-30ef3ac6-3141-11e8-89c1-b7623b71ec2f.png)

chociaż atakuje czasem pop-up o pakiecie za 85 złotych, nie używam listy na pop-upy to może jest to wycinane bez wzbudzania alarmów.

**Comment by MajkiIT** [comment]
@krystian3w ja tego nie mam ale poszukamy.
