### ISSUE TITLE
docer.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#6693]
Przy wlaczonym Nano adblockerze znika wyszukiwarka 

Z blockerem
![z blokerem](https://user-images.githubusercontent.com/21177361/37922373-aa6d8a16-312c-11e8-8ef2-c63f7d1e1c1c.png)

Bez blockera
![bez blockera](https://user-images.githubusercontent.com/21177361/37922410-be389e82-312c-11e8-9363-44cb75db1ef4.png)

**Comment by MajkiIT** [comment]
@gzenio22 ale to do Pingwina :P

**Comment by gzenio22** [comment]
Na to inne forum?

**Comment by gzenio22** [comment]
Zgłoszone niezdarnie ale chyba po screenach ogarną :D zamykam

**Comment by gzenio22** [comment]
@Majkit nie wiem czemu ale tamci nie potrafią odtworzyć sytuacji z mojego screena :D a tobie sie udało? 

https://github.com/NanoAdblocker/NanoFilters/issues/51

Taa moja lamana angielszczyzna Xd

**Comment by KonoromiHimaries** [comment]
mam to samo, a gdy wyłączę `polskie filtry - ogólną listę` to wszystko wraca do normy.

**Comment by xxcriticxx** [comment]
@MajkiIT zobacz w konsoli bo jest bogato strona caly czas cos laduje

**Comment by krystian3w** [comment]
Próbuje ładować kilkukrotnie reklamy / skrypty reklam.

```
||ad.freedisc.pl^$subdocument,domain=docer.pl
||adk.freedisc.pl^$subdocument,domain=ad.freedisc.pl
||adk.musody.com^$subdocument,domain=ad.musody.com
||adk.docer.pl^$subdocument,domain=ad.docer.pl
```

I jakby się uspokaja.
