### ISSUE TITLE
speedtest.pl

### ISSUE THREAD

**Issue by kubagp1** [MajkiIT/polish-ads-filter#6694]
left

**Comment by krystian3w** [comment]
Jakby ktoś chciał w uBlock / Nano Adblocker / Adguard trochę przywrócić stary układ:

```
speedtest.pl##.liveresults:style(margin-top:100px!important;)
speedtest.pl##.meter:style(left: 33%!important;margin-left: -12.5em!important;)
```

**Comment by krystian3w** [comment]
Jakiś Filip z Warszawy / z T-Mobile kontratakuje.

> ![obraz](https://user-images.githubusercontent.com/35370833/38522099-dadca77e-3c47-11e8-8ffe-39d5616d2763.png) |
> --- |

**Comment by krystian3w** [comment]
`speedtest.pl##.wynik-background,#sctm:style(background:#1974cb!important;)`
