### ISSUE TITLE
gazety

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#6696]
Reklamy : 

![trzy reklamy](https://user-images.githubusercontent.com/23176832/37967646-54c7a588-31cc-11e8-8de8-8f1128ffd245.png)
na głównych : 
https://golub-cgd.pl/
https://brodnica-cbr.pl/
https://wabrzezno-cwa.pl/

odnośniki do googla są aż 2 ( u góry ) : 
https://golub-cgd.pl/artykul/w-wegiersku-lacza/428230
https://brodnica-cbr.pl/artykul/kino-wraca-do-brodnicy/198991

Pozostałości po reklamach:

![5 resztek](https://user-images.githubusercontent.com/23176832/37969548-4f0e46ba-31d1-11e8-9a6f-4632a780b6a9.png)

https://golub-cgd.pl/
https://brodnica-cbr.pl/
https://rypin-cry.pl/
https://wabrzezno-cwa.pl/
A tu dodatkowo do odblokowania " kontakt do redakcji " : 
https://lipno-cli.pl/

Gdyż na każdej stronie jest ta sama resztka można ją usunąć regułą `pl##.reklama-rectangle`

A na miejsca na reklamy w artykułach : 
```

lipno-cli.pl###__cmcmedia_upid_21
brodnica-cbr.pl###__cmcmedia_upid_21
golub-cgd.pl###__cmcmedia_upid_21
rypin-cry.pl###__cmcmedia_upid_21
wabrzezno-cwa.pl###__cmcmedia_upid_21
```

```

golub-cgd.pl###__cmcmedia_upid_23
brodnica-cbr.pl###__cmcmedia_upid_23
rypin-cry.pl###__cmcmedia_upid_23
wabrzezno-cwa.pl###__cmcmedia_upid_23
lipno-cli.pl###__cmcmedia_upid_23
```

oraz ogólna `pl##.art-reklama`

**Comment by krystian3w** [comment]
```
brodnica-cbr.pl,golub-cgd.pl,lipno-cli.pl,rypin-cry.pl,wabrzezno-cwa.pl###__cmcmedia_upid_6,#__cmcmedia_upid_21,#__cmcmedia_upid_23,#__cmcmedia_upid_25
```

Co do `#__cmcmedia_upid_25` nie mam pewności, po zawartości iframe to raczej reklama. Podobnie te szare prostokąty np. obok zablokowanego kontaktu z redakcją `pl##.reklama-rectangle`. `#__cmcmedia_upid_6` z filtrów co blokują formularz kontaktowy.

----

Takie filtry wycinają te kontakty z strony głównej (`##.fl.w250:nth-of-type(1)`).

```
lipno-cli.pl###__cmcmedia_upid_6, .fl.w250:nth-of-type(1), .fl.w250:nth-of-type(2), .fl.w250:nth-of-type(3), .fl.w250:nth-of-type(4)
```

**Comment by MajkiIT** [comment]
@blocker999 @krystian3w dziękuję
