### ISSUE TITLE
miastons.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6697]
![2018-03-27-miastons pl - portal informacyjny _ nowy sacz](https://user-images.githubusercontent.com/5884000/37983501-fb2f5c96-31f3-11e8-92cb-82265aec6506.png)

reklamy

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.18
 ND 13.47
 Chr 65.0.3325.181
</details>

**Comment by gzenio22** [comment]
Kurde chcial bym sie w koncu wiecej nauczyc ale jak widze losowe cyferki to juz wiem ze ja tu nie pomoge

**Comment by xxcriticxx** [comment]
@gzenio22 przestan siedziec na kodi caly dzien

**Comment by KerbenII** [comment]
No bez przesady xD
MiastoNS to nie jest Onet czy tam Interia aby mieć z nimi jakieś problemy:

- id="sidebar" - całość tutaj jest reklamą, div dla zmyłki się tak nazywa
-body > div.main-wrap.content-main-wrap > div.container.adcontainer
-id=better-ads-4 (tutaj zamiast 4 dać gwiazdkę i wywali większość reklam)

**Comment by gzenio22** [comment]
@KerbenII Tylko problem w tym ze ja tych kodow regół prawie nie ogarniam gubie sie w tym po lekku @xxcriticxx Ja nie siedze w kodi :D

**Comment by KerbenII** [comment]
Tu masz poradnik, ale najlepiej to w sumie spis filtrów sobie otworzyć i przekopiować.
https://adblockplus.org/filters

**Comment by KerbenII** [comment]
A tutaj masz reguły:

(te dwie to obstawiam, że jakaś wtyczka)
[id^="better-ads-"] - blokuj na wszystkich stronach wszystko co zawiera better-ads-* jako id
##.bsac-container - blokuj na wszystkich stronach klasę .bsac-container

do oceny @MajkiIT zostawiam blokadę partnerów.
Dla mnie akurat ci partnerzy, to firmy, które w danym miesiącu wykupiły reklamę, a nie jakieś firmy współpracujące.
miastons.pl##.row-partners

**Comment by xxcriticxx** [comment]
@KerbenII witamy from the dead again!

**Comment by KerbenII** [comment]
Akurat ataki w plemionach puszczam to sobie wszedłem :D

**Comment by xxcriticxx** [comment]
@KerbenII aha

@gzenio22  widze ciebie na pigulce

@all spieprzam w trafik z nyc see you all tomorrow

**Comment by KerbenII** [comment]
Ten moment kiedy @xxcriticxx oznacza jakąś noname'ową organizację zamiast wszystkich :trollface:
