### ISSUE TITLE
bbcpolska.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#6698]
Cookies

**Comment by krystian3w** [comment]
`bbcpolska.com##body > iframe` takie coś stosuje **`i don't care about cookies`**.

**Comment by hawkeye116477** [comment]
@krystian3w Nie prawda, margines nadal się pojawia na trochę.

**Comment by krystian3w** [comment]
U mnie nie ma, nawet jak poczekam minutę w trybie prywatnym.

Coś chyba nawalają powiadomienia mailowe...

**Comment by krystian3w** [comment]
Ja tam widzę tylko regułę od "kibo(l)ka".

**Comment by hawkeye116477** [comment]
@krystian3w https://github.com/MajkiIT/polish-ads-filter/commit/ec9e717b0cfa76b4bcf8c75040847cd64067e4e4 :smile:
