### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by wykopki** [MajkiIT/polish-ads-filter#6706]
<img width="1423" alt="screen shot 2018-03-29 at 14 54 36" src="https://user-images.githubusercontent.com/18431213/38089950-5e8452a6-3361-11e8-97bd-f83619635630.png">

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
Pliki reklamy przychodza z takich adres
ow: 
1. http://www.filmweb.pl/JnYcyZs670Ksf29-aJ0zFJifboVAqifU5yW0gJntz/kfc/bsmart-mentos/tapeta_v2.jpg
2. http://www.filmweb.pl/JnNjs_Dt94xOmPNhG9Ak7QSBm2yNIcpsC/8gt6PmJnlsget.html

### Moja konfiguracja
**Przeglądarka internetowa:**
Firefox
**Rozszerzenia i skrypty:**

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka

### Tymczasowe rozwiązanie
Pomaga regułka: 
`/1010x200/$script,domain=filmweb.pl` - wymaga dopracowania.

**Comment by MajkiIT** [comment]
@wykopki zrób update i sprawdź proszę.

**Comment by wykopki** [comment]
@MajkiIT Działa jak złoto.
