### ISSUE TITLE
mistrzowie.org

### ISSUE THREAD

**Issue by Rzeszow** [MajkiIT/polish-ads-filter#6708]
Występuję zazwyczaj po połowie strony. Reklama wewnętrzna (kubki, koszulki itp).

**Comment by MajkiIT** [comment]
Sprawdź proszę może tak 
`mistrzowie.org##.clearfix.lbox.pic:nth-of-type(5)`

**Comment by Rzeszow** [comment]
Właśnie miałem pisać abyś to dodał, ale zaciekawiły mnie list do Pi-Hole. Czyli w skrócie "Dzięki! Działa!". I jeszczę pytanie czy polecasz jakieś list do Pi-Hole?

**Comment by Rzeszow** [comment]
Dzięki @MajkiIT. Już to wcześniej dodałem, tylko zależało mi na twojej opinii czy może nie znasz jakiś innych. Ale dobra testuje i chyba wystarczają.

**Comment by MajkiIT** [comment]
@Rzeszow to moja lista. Na chwilę obecną nie narzekam.

![screenshot-2018-3-29 pi-hole admin console](https://user-images.githubusercontent.com/11302675/38108689-e6d02f02-3395-11e8-8e46-f7afae652613.png)

**Comment by xxcriticxx** [comment]
@MajkiIT ile masz domains?

**Comment by xxcriticxx** [comment]
@MajkiIT fyi...

**Comment by MajkiIT** [comment]
@xxcriticxx ponad 1 700 000 :D

**Comment by xxcriticxx** [comment]
@MajkiIT ok to testuj i daj znac co tobie blokuje
