### ISSUE TITLE
demotywatory.pl

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6725]
Anti-Adblock

### Zrzut ekranu

![capture_006_31032018_141133](https://user-images.githubusercontent.com/37474031/38163026-6f740042-34ed-11e8-9375-2df106cdd29d.png)

### Link bezpośredni

https://demotywatory.pl/4757168

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page
2. Scroll down a bit

### Moja konfiguracja
Win 7 SP1 [64bit]
Chrome 65.0.3325.181 [64bit]
Firefox 59.0.2 [64bit]
Opera 52.0.2871.30 [64bit]
uBlock Origin 1.15.18

**Filtry:**

uBlock filters
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard Base Filters
Adblock Warning Removal List
EasyList
EasyPrivacy
Fanboy’s Cookiemonster List
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry Wewnętrzne

**Comment by hawkeye116477** [comment]
`demotywatory.pl###adblock_info`

**Comment by WowDude** [comment]
Working.

**Comment by MajkiIT** [comment]
@WowDude Maybe report this bug. Can you do it ?

**Comment by hawkeye116477** [comment]
@MajkiIT https://github.com/jspenguin2017/uBlockProtector/commit/3cf73f965089e0da23206c190ccc50f1fc068e0b
