### ISSUE TITLE
audiklub.org

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6726]
Anti-Adblock

### Zrzut ekranu

![capture_008_31032018_150519](https://user-images.githubusercontent.com/37474031/38163475-2586a482-34f5-11e8-9fe7-47202e329e4a.png)

### Link bezpośredni

http://www.audiklub.org/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Chrome 65.0.3325.181 [64bit]
Firefox 59.0.2 [64bit]
Opera 52.0.2871.30 [64bit]
uBlock Origin 1.15.18

**Filtry:**

uBlock filters
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adblock Warning Removal List
EasyList
EasyPrivacy
Fanboy’s Cookiemonster List
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry Wewnętrzne

Enabling "Adguard Base Filters" fixes it.

**Comment by hawkeye116477** [comment]
`@@||www.audiklub.org/js/ads.js`

**Comment by WowDude** [comment]
Working.
