### ISSUE TITLE
darmowyskin.pl

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6727]
Anti-Adblock

### Zrzut ekranu

![capture_009_31032018_152946](https://user-images.githubusercontent.com/37474031/38163677-700a4b96-34f8-11e8-88a1-bdab53a24c8a.png)

### Link bezpośredni

http://darmowyskin.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Chrome 65.0.3325.181 [64bit]
Firefox 59.0.2 [64bit]
Opera 52.0.2871.30 [64bit]
uBlock Origin 1.15.18

**Filtry:**

uBlock filters
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard Base Filters
Adblock Warning Removal List
EasyList
EasyPrivacy
Fanboy’s Cookiemonster List
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry Wewnętrzne

**Comment by hawkeye116477** [comment]
`darmowyskin.pl##.info_add_block`

**Comment by WowDude** [comment]
Working.
