### ISSUE TITLE
imeds.pl

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6728]
Anti-Adblock

### Zrzut ekranu

On Firefox If Polskie Filtry Ciasteczkowe​ disabled (Anti-Adblock):
![capture_012_31032018_153851](https://user-images.githubusercontent.com/37474031/38163756-9eb31dd2-34f9-11e8-9932-64849f7ed486.png)

On Firefox If Polskie Filtry Ciasteczkowe​ enabled (broken website)
also on Opera / Chrome always broken website even if Polskie Filtry Ciasteczkowe disabled.
![capture_011_31032018_153644](https://user-images.githubusercontent.com/37474031/38163752-858fc972-34f9-11e8-9654-996647771c6d.png)

### Link bezpośredni

https://imeds.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Chrome 65.0.3325.181 [64bit]
Firefox 59.0.2 [64bit]
Opera 52.0.2871.30 [64bit]
uBlock Origin 1.15.18

**Filtry:**

uBlock filters
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard Base Filters
Adblock Warning Removal List
EasyList
EasyPrivacy
Fanboy’s Cookiemonster List
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Elementów Irytujących
Polskie Filtry Wewnętrzne

**Comment by xxcriticxx** [comment]
@WowDude are you using nano defender?

**Comment by hawkeye116477** [comment]
To w zasadzie wina EasyList, bo to ich reguły, ale tak czy siak to powinno pomóc: ```
imeds.pl#@#.pub_300x250
imeds.pl#@#.pub_300x250m
imeds.pl#@#.pub_728x90
imeds.pl#@#.text_ad
imeds.pl#@#.text-ad
imeds.pl#@#.textAd
imeds.pl#@#.text-ad-links
imeds.pl#@#.text_ads
imeds.pl#@#.text-ads
```

**Comment by WowDude** [comment]
@xxcriticxx Nano Defender fixes the Anti-Adblock
@hawkeye116477 your filters fixes the webpage breakage

**Comment by xxcriticxx** [comment]
@WowDude welcome to the community!

**Comment by MajkiIT** [comment]
@hawkeye116477 Dzięki

**Comment by WowDude** [comment]
@xxcriticxx : thanks
