### ISSUE TITLE
vitalia.pl 

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6730]
Anti-Adblock

### Zrzut ekranu

![capture_002_31032018_212543](https://user-images.githubusercontent.com/37474031/38166867-362651f8-352b-11e8-87ba-2ae26f5efc41.png)

### Link bezpośredni

https://vitalia.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Chrome 65.0.3325.181 [64bit]
Firefox 59.0.2 [64bit]
Opera 52.0.2871.30 [64bit]
uBlock Origin 1.15.18

**Filtry:**
Nano Defender 13.49
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard Base Filters
Adblock Warning Removal List
EasyList
EasyPrivacy
Fanboy’s Cookiemonster List
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry Wewnętrzne

**Comment by MajkiIT** [comment]
`vitalia.pl###topbborlayer`

**Comment by WowDude** [comment]
Working
