### ISSUE TITLE
Ublock Origin, AlleBlock i olx.pl

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#6732]
Witam. Odnośnie tego tematu, to mam problem. Zasubskryptowałem AlleBlock Filter do Ublock Origin i... Jak mój brat chciał odpowiedzieć na wiadomość prywatną jednego użytkownika olx.pl, to wysyłanie było blokowane przez UBO. Dopiero, jak dodałem olx.pl do wyjątków, można było wysyłać wiadomości. Więc moje pytanie. Czy ten filtr ma blokować całe olx.pl czy tylko irytujące elementy na nim? Czy można poprosić o przyjrzenie się temu problemowi i dać poprawkę? Pozdrawiam

**Comment by KonoromiHimaries** [comment]
@maciejtarmas zapraszamy!

**Comment by xMaap** [comment]
Pisz tutaj https://github.com/maciejtarmas/AlleBlock/issues
