### ISSUE TITLE
tvpstream.vod.tvp.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6733]
![opera zdjecie_2018-04-01_000944_tvpstream vod tvp pl](https://user-images.githubusercontent.com/36385327/38167999-18729fc0-3541-11e8-8343-51cf904ffdc3.png)

**Comment by krystian3w** [comment]
```
@@||myao.adocean.pl^$xmlhttprequest,domain=tvpstream.vod.tvp.pl
```

Jak coś wycieka, to trzeba by dodatkowo zablokować.

**Comment by xxcriticxx** [comment]
geo lock

**Comment by krystian3w** [comment]
U mnie pomaga dopuszczenie ruchu xml i reklamy są wycinane, bo są obrazkami.

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję
