### ISSUE TITLE
money.pl 

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6742]
Popular and important website broken - wrong filter:

### Zrzut ekranu

Screenshoot 1 - Error - the webpage broken:
![capture_004_01042018_080216](https://user-images.githubusercontent.com/37474031/38170336-8d0af548-3583-11e8-975b-a57af5336814.png)

Screenshoot 2 - The webpage unbroken after adding `money.pl#@#DIV[class^="ad"]`
![capture_003_01042018_080206](https://user-images.githubusercontent.com/37474031/38170344-b3d28600-3583-11e8-8b87-2ab613bf73ef.png)

Screenshoot 3 -The bad filter `~praca.money.pl,money.pl##DIV[class^="ad"]` in POL: polskie filtry do Adblocka i uBlocka:
![capture_b](https://user-images.githubusercontent.com/37474031/38170390-b7d6434e-3584-11e8-9c40-cdb435362725.png)

### Link bezpośredni

https://www.money.pl/forum/kiedy-sa-dni-powszednie-t2510386.html

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Chrome 65.0.3325.181 [64bit]
Firefox 59.0.2 [64bit]
Opera 52.0.2871.30 [64bit]
uBlock Origin 1.15.18

**Filtry:**
Nano Defender 13.49 (on Firefox 13.48)
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard Base Filters
Adblock Warning Removal List
EasyList
EasyPrivacy
Fanboy’s Cookiemonster List
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry Wewnętrzne

**Comment by krystian3w** [comment]
Good job
