### ISSUE TITLE
pilot.wp.pl 

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6743]
Anti-Adblock

Also ADS (on Chrome / Opera only):

### Zrzut ekranu

ADS:

![capture_011_01042018_092916](https://user-images.githubusercontent.com/37474031/38170878-27667f4e-358f-11e8-855d-f1b37562217e.png)

Anti-Adblock

![capture_013_01042018_093755](https://user-images.githubusercontent.com/37474031/38170973-63fb1acc-3590-11e8-83c1-72d1430997c3.png)

### Link bezpośredni

https://pilot.wp.pl/tv

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page (ADS)
2. Click Video Play button (Anti-Adblock)

### Moja konfiguracja
Win 7 SP1 [64bit]
Chrome 65.0.3325.181 [64bit]
Opera 52.0.2871.30 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.18

**Filtry:**
Nano Defender 13.49 (on Firefox 13.48)
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard Base Filters
Adblock Warning Removal List
EasyList
EasyPrivacy
Fanboy’s Cookiemonster List
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry Wewnętrzne

**Comment by hawkeye116477** [comment]
I even see advertisement too.

**Comment by krystian3w** [comment]
Bug in nano defender 13.48 - 13.49, disconnect or Firefox privacy module:

**Comment by hawkeye116477** [comment]
You mustn't disable Nano Defener, you can just refresh page and antiadblock disappears too.

**Comment by krystian3w** [comment]
Chyba użyli swojego kodu, on był zbugowany tak, że po odświeżeniu przepuszczał.

**Comment by MajkiIT** [comment]
@krystian3w ale tak jest. Jest adblock a zaraz znika.
