### ISSUE TITLE
Prima aprilisowe żarty lanik.us

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#6744]
```
||forums.lanik.us/ext/hifikabin/aprilfools/styles/prosilver/theme/images/spider-sprite.png$image
||forums.lanik.us/ext/hifikabin/aprilfools/styles/prosilver/theme/images/fly-sprite.png$image
```

Polecam dodać jak ktoś się boi much i pająków.

**Comment by MajkiIT** [comment]
hahahaha dobre :P

**Comment by WowDude** [comment]
I remember having similarly many years ago: [plastic flies](https://www.google.com/search?q=plastic+fly&source=lnms&tbm=isch&sa=X), you can put it on a table or like so, also very realistic :)
