### ISSUE TITLE
ocen-piwo.pl

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6747]
Adblock detect

### Zrzut ekranu

![capture_017_01042018_150940](https://user-images.githubusercontent.com/37474031/38173428-d5c4ad20-35be-11e8-9494-073a7df16236.png)

### Link bezpośredni

https://ocen-piwo.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Chrome 65.0.3325.181 [64bit]
Opera 52.0.2871.30 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.18

**Filtry:**
Nano Defender 13.49 (on Firefox 13.48)
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard Base Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Cookiemonster List
I don't care about cookies
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry Wewnętrzne

**Comment by MajkiIT** [comment]
@WowDude this is information that you are 18 years old

**Comment by WowDude** [comment]
@MajkiIT : Not only, because also anti-adblock message on the bottom:

> Koszty funkcjonowania serwisu pokrywa emisja reklam.
> Prosimy o wyłączenie wszystkich wtyczek typu AdBlock.
