### ISSUE TITLE
discard

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#6753]
@KonoromiHimaries celowo usunąłeś kanał ?

**Comment by KonoromiHimaries** [comment]
@MajkiIT to hawk się bawi w mlp

**Comment by MajkiIT** [comment]
@KonoromiHimaries Aha dziękuję za info.

**Comment by xxcriticxx** [comment]
znalazlem zdjecie @hawkeye116477 w necie

![capture](https://user-images.githubusercontent.com/15007183/38175975-d30e2a12-35b3-11e8-9351-29a63eed1107.PNG)

**Comment by hawkeye116477** [comment]
Heh, to taki Prima Aprilis z mojej strony, 1 kwietnia jest, trzeba świętować :smiley:

**Comment by xxcriticxx** [comment]
@hawkeye116477 photo super! rozumiem juz wszystko
