### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#6754]
Reguła `##DIV[class^="ad"]` ukrywa „pick your reaction" na GitHubie. Nie wiem czy raczej ona nie kwalifikuje się do całkowitego wywalenia.

**Comment by WowDude** [comment]
It also completely break https://www.nationalgeographic.com/:

![capture_020_01042018_220336](https://user-images.githubusercontent.com/37474031/38176943-898580b2-35f8-11e8-8e7a-c0d2fbd514a3.png)

**Comment by F4z** [comment]
Poprawione, dzięki.
