### ISSUE TITLE
mail.google.com

### ISSUE THREAD

**Issue by gwarser** [MajkiIT/polish-ads-filter#6755]
### Zrzut ekranu

Jest:
![](https://screenshotscdn.firefoxusercontent.com/images/2607b6d3-23da-4a7c-959a-61b911ea5b8e.png)

![spectacle j13118](https://user-images.githubusercontent.com/886325/38176916-ecee2736-35f7-11e8-8782-e65f9d4fec19.png)

A powinno być:
![](https://screenshotscdn.firefoxusercontent.com/images/512491f4-166f-47a1-9db3-7b7550d901c9.png)

### Link bezpośredni

https://mail.google.com/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Otwórz gmaila
2. Wejdź w odebraną wiadomość
3. Treść wiadomości jest _zapadnięta_

### Moja konfiguracja
**Przeglądarka internetowa:**
Firefox Nightly

**Rozszerzenia i skrypty:**
UBO dev

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. Ehhhhh.. nie chce mi się pisać wszystkiego

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Problemem jest 

Static filter `##DIV[class^="ad"]` found in:
POL: polskie filtry do Adblocka i uBlocka

**Comment by F4z** [comment]
Poprawione, dzięki.

**Comment by gwarser** [comment]
Ten sam filtr ukrywał listę wyboru emotek do komentarza, tutaj na githubie ^
