### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6758]
https://github.com/MajkiIT/polish-ads-filter/issues/6743 ADS has been fixed but Anti-Adblock still appears, why issue closed then?

**Comment by hawkeye116477** [comment]
@WowDude For me also there are no antiadblock too.

**Comment by WowDude** [comment]
@hawkeye116477 & @MajkiIT 

All filters updated:
- I've Anti-Adblock on all 3 browsers everytime I visit the wepage first time (after clearing cache & cookies) 
- if another visit (no clearing cache & cookies) I've no Anti-Adblock anymore and Video plays
- but also if try to reload the webpage several times and click Play I even sometimes get this:

> Your watching time has expired without subscribtion.
> Without subscription you can only watch the canal only several minutes.
> 
> Log In, Register

![capt3](https://user-images.githubusercontent.com/37474031/38213549-ee720936-36c1-11e8-9f83-221cf47f8047.png)

**Comment by hawkeye116477** [comment]
I discovered cause -> EasyPrivacy when it's checked, then antiadblock appears.

**Comment by WowDude** [comment]
@hawkeye116477 yes, the issue is fixed with EasyPrivacy disabled or your filter added.

**Comment by MajkiIT** [comment]
@hawkeye116477 I don't see this, but if it works I added.

**Comment by krystian3w** [comment]
U mnie działa ta reguła, od razu na świeżym profilu nie ma tego jednorazowego pytania "wyłącz adblock", więc chyba może zostać na liście.
