### ISSUE TITLE
ocen-piwo.pl

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6759]
Still Anti-Adblock message not fixed, https://github.com/MajkiIT/polish-ads-filter/issues/6747#issuecomment-377809548, why not replying to my comment?

**Comment by KonoromiHimaries** [comment]
@WowDude majki not respond in closed topics.

**Comment by WowDude** [comment]
@KonoromiHimaries : ok, I was suscpecting so, but wasn't sure, but why?

**Comment by KonoromiHimaries** [comment]
@WowDude I think it has notifications turned off

**Comment by MajkiIT** [comment]
@WowDude it's static element.

**Comment by xxcriticxx** [comment]
@MajkiIT can you apply cosmetic filter to hide it?

**Comment by MajkiIT** [comment]
@xxcriticxx @WowDude done

**Comment by WowDude** [comment]
Working.
