### ISSUE TITLE
motomi.pl

### ISSUE THREAD

**Issue by ghost** [MajkiIT/polish-ads-filter#6773]
![2018-04-03-ogloszenia motoryzacyjne - nowe i uzywane samochody _ motomi pl](https://user-images.githubusercontent.com/5884000/38229110-5cc5662c-3707-11e8-92d4-f48e608f1ce0.png)

pusta sekcja

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.18
 ND 13.49
 Chr 65.0.3325.181
</details>

**Comment by MajkiIT** [comment]
zablokowanie elementu ukrywa też pożądane elementy
