### ISSUE TITLE
anime-centrum.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6787]
![2018-04-03-anime odcinki online pl - anime centrum - twoje centrum anime](https://user-images.githubusercontent.com/5884000/38234737-057acfca-371f-11e8-86b5-19ee2dc2fb1f.png)

przycisk fb na dole strony

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.18
 ND 13.49
 Chr 65.0.3325.181
</details>

**Comment by krystian3w** [comment]
`##.button-social-1` / `##.social`
