### ISSUE TITLE
theillest.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6788]
![2018-04-03-the illest streetwear and sneakers magazine](https://user-images.githubusercontent.com/5884000/38236192-b6db5e02-3723-11e8-9011-2142f1b608ff.png)

pusta sekcja `Advertisement`

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.18
 ND 13.49
 Chr 65.0.3325.181
</details>

**Comment by krystian3w** [comment]
U mnie pusto :confused:  (coś już wycina) 

https://gist.github.com/krystian3w/815db3cf86b0a787726b3dff10dfb138
