### ISSUE TITLE
farmer.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6789]
![2018-04-03-rolnik trafil za kratki za ukrywana w belach slomy uprawe - fakty](https://user-images.githubusercontent.com/5884000/38236689-46efb9c4-3725-11e8-926e-225df5f07391.png)
`http://www.farmer.pl/fakty/rolnik-trafil-za-kratki-za-ukrywana-w-belach-slomy-uprawe,77332.html`

pusta sekcja reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.18
 ND 13.49
 Chr 65.0.3325.181
</details>

**Comment by krystian3w** [comment]
`farmer.pl##.advB`
