### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#6791]
> Reklamy pojawiają się raz na x przeładowań strony.

### Zrzut ekranu
![07f13ead-78ff-4488-a768-22869ae42ee4](https://user-images.githubusercontent.com/18230443/38242894-3f3b26b2-3736-11e8-8c8e-160c5b3b5e6f.png)

dobreprogramy.pl##.block-content.list > div:nth-of-type(3)

![screenshot-2018-4-3 dobreprogramy pl](https://user-images.githubusercontent.com/18230443/38243156-e7d14fea-3736-11e8-8e8d-68c903c1893a.png)

||v.wpimg.pl/eF8oMykuBCIXPQBWKRodaQpffEFGRVZpWg4-CgAUSncPX2IpWkU6cQ1fNUtbRRU-Z0d-UEUfFSE=$image
dobreprogramy.pl##.torz3jl
dobreprogramy.pl##.kynzhw4.ame2qr5

### Link bezpośredni
https://www.dobreprogramy.pl/

### Moja konfiguracja
**Przeglądarka internetowa:** Firefox 61.0 (nightly)

**Rozszerzenia i skrypty:**
uBlock Origin v1.15.25b0
Nano Defender 13.43

**Comment by RikoDEV** [comment]
Vivaldi z aktualnymi listami + nano defenderem.

![hm](https://user-images.githubusercontent.com/18230443/38246913-9e30cd54-3743-11e8-807d-f614451ad901.PNG)

**Comment by gzenio22** [comment]
Opera mam to samo

**Comment by krystian3w** [comment]
```
dobreprogramy.pl##.torz3jl
dobreprogramy.pl##.kynzhw4.ame2qr5
```

Najpewniej nie zadziała pod odświeżeniu, podobna metoda jak z reklamą Opery.

**Comment by RikoDEV** [comment]
@krystian3w klasy są losowe, więc statyczne reguły tu nie działają.

**Comment by WowDude** [comment]
<details>
  <summary>I confrim the issue, I also have ads:</summary>

### Zrzut ekranu

Screenshoot 1
![capture_031_03042018_171726](https://user-images.githubusercontent.com/37474031/38258569-1d913150-3763-11e8-9ac1-481d6b542d3d.png)

Screenshoot 2
![capture_032_03042018_172411](https://user-images.githubusercontent.com/37474031/38258871-e41ebda6-3763-11e8-854c-74f15fb066b2.png)

### Link bezpośredni

https://www.dobreprogramy.pl/
https://www.dobreprogramy.pl/Nowy-Linux-calkiem-odporny-na-luki-Spectre-wytrzyma-tez-dluzej-na-baterii,News,87257.html

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Chrome 65.0.3325.181 [64bit]
Opera 52.0.2871.40 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.18

**Filtry:**
Nano Defender 13.49 (on Firefox 13.48)
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
I don't care about cookies
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry Wewnętrzne

</details>

**Comment by MajkiIT** [comment]
Może coś takiego 
```
www.dobreprogramy.pl###slide-menu > DIV[class]:first-child + DIV[class] + DIV[class]
www.dobreprogramy.pl##.block-content.list > div:nth-of-type(3)
```

**Comment by hawkeye116477** [comment]
@MajkiIT Tak średnio to działa, czasem tak, a czasem nie.
Ale można przyblokować ten skrypt generujący reklamy => `||a.wpimg.pl/a/i/stg/wpjslib-pwpnojq.js$domain=dobreprogramy.pl`, wtedy problem zniknie całkowicie :smile:

**Comment by MajkiIT** [comment]
a to nie wina tego ?
/^https:\/\/[a-z]{2,14}\.wp\.pl\/[a-zA-Z0-9_-]{450,}/$script,domain=www.dobreprogramy.pl

**Comment by WowDude** [comment]
@MajkiIT : these filters are invalid, instead of `##@#.` should be `#@##.`:

```
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,4free.waw.pl,imeds.pl##@#.pub_300x250
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,4free.waw.pl,imeds.pl##@#.pub_300x250m
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,4free.waw.pl,imeds.pl##@#.pub_728x90
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,4free.waw.pl,imeds.pl##@#.text_ad
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,4free.waw.pl,imeds.pl##@#.text-ad
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,4free.waw.pl,imeds.pl##@#.textAd
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,4free.waw.pl,imeds.pl##@#.text-ad-links
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,4free.waw.pl,imeds.pl##@#.text_ads
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,4free.waw.pl,imeds.pl##@#.text-ads
```

**Comment by krystian3w** [comment]
To jeszcze uBlock takie coś uznaje za błąd:

Cosmetic filtering – invalid filter: `#top-header, #[id^="wo-poz-"], #jmMobile`
Cosmetic filtering – invalid filter: `.mod-blank.modulegazeta-olawa.pl##.bf-advertisement-code`

Niestety wyszła, z tego taka papka, że nie wiem czy to namierzę.

**Comment by seba2282** [comment]
Mam coś takiego:
![screenshot_2018-04-03-18-16-20](https://user-images.githubusercontent.com/16944478/38262268-032874cc-376d-11e8-959b-03da3bd6d4c6.png)

**Comment by hawkeye116477** [comment]
@MajkiIT To też zdaje się pomaga.

**Comment by krystian3w** [comment]
U mnie ucho było raz i zniknęło 👂

**Comment by MajkiIT** [comment]
@hawkeye116477 moja reguła rozwala video

**Comment by WowDude** [comment]
Fixed.

**Comment by seba2282** [comment]
Czy u was też nie działa ten filmik?
https://www.miniminiplus.pl/filmy/pokaz/my-little-pony-duchy 
Bo mi się nie ładuje. Zablokowana chyba jakaś reguła na playery tvn-u.

**Comment by xMaap** [comment]
@seba2282 u mnie działa, ale ten przycisk player mi nie znika. Później zobaczę może coś mi blokuje.

![](https://i.imgur.com/JN44cSX.png)

**Comment by seba2282** [comment]
Ja mam tak po naciśnięciu play. 
![screenshot_2018-04-03-23-16-23](https://user-images.githubusercontent.com/16944478/38276444-501f9288-3795-11e8-898d-58992987c6e6.png)
