### ISSUE TITLE
ototorun.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#6793]
Przenoszę sprawę => https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/625
Dodatkowo tutaj jakiś głodomor zjadł filmik => `https://ototorun.pl/artykul/torun-rzadzi-w-regionie/429341`

**Comment by krystian3w** [comment]
> głodomor zjadł filmik

Odblokowałem, ale wpuściłem kupę badziewia:

```
ototorun.pl#@#[id*="cmcmedia_upid_"]
@@||bbcdn-static.bbelements.com^$script,domain=cdn.gallery
ototorun.pl#@#A[target="_blank"] > IMG
pl#@##top-reklama
@@||go.eu.bbelements.com^$xmlhttprequest,domain=cdn.gallery
||go.eu.bbelements.com/please/*$script,domain=cdn.gallery
@@||bbcdn-bbnaut.ibillboard.com^$script,domain=cdn.gallery
@@||bbnaut.ibillboard.com/initidmatch?force=1$script,domain=cdn.gallery
@@||bbnaut.ibillboard.com/g/njs/*$script,domain=cdn.gallery
@@||pagead2.googlesyndication.com/pagead/show_ads.js$script,domain=cdn.gallery
@@||mr1a.exs.pl/embed5.php$script,domain=ototorun.pl
@@||mr1-1a.exs.pl/frame71.php$subdocument,domain=ototorun.pl
```

Może komuś przeszkadzało, że wyje.

**Comment by MajkiIT** [comment]
@krystian3w a po update filtrów nie jest OK ?

**Comment by krystian3w** [comment]
Tak, odtwarzacz jest i mniej wpuszcza (chodziarz był problem bo strona czekała aż on się załaduje, ale to raczej wina ototorun).

**Comment by MajkiIT** [comment]
@krystian3w dziękuje
