### ISSUE TITLE
lg.com/pl/

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6805]
cookies

`lg.com##.agree-cookie-wrap`

http://www.lg.com/pl/wsparcie/tv/smartshare-oprogramowanie-smartshare-dla-pc

Ta strona korzysta z plików cookie. Kontynuując przeglądanie strony zgadzasz się na używanie plików cookie. Więcej informacji zamieszczono wnaszej Polityce prywatności oraz Polityce dotyczącej plików cookie.

**Comment by krystian3w** [comment]
Albo można zablokować skrypt i css od komunikatu cookies:

`/eprivacy-cookie.`

by **_Cookiemonster_**.

---

Tyle, że trzeba się liczyć z tym, że ktoś może niechlujnie zbudować własny js strony (np. uzależnić go od pliku js cookies lub do niego wrzucić większość kodu i klops).

---

Kibo(l)ek ma dodatkowo zabezpieczenie z wykluczeniem body i html (`:not(body):not(html)`).
