### ISSUE TITLE
support.hp.com/pl-pl/

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6806]
cookies

https://support.hp.com/pl-pl/product/compaq-mini-700-pc-series/3834716/model/3876861/manuals

Wykorzystujemy pliki cookie do personalizowania treści i reklam, aby oferować funkcje społecznościowe i analizować ruch w naszej witrynie internetowej. Udostępniamy również informacje o sposobie, w jaki korzystasz z naszej witryny partnerom społecznościowym, reklamowym i analitycznym przy zachowaniu naszych Zasad poufności. Możesz zarządzać swoimi preferencjami w ustawieniach plików cookie. Poprzez korzystanie z witryny zgadzasz się na wykorzystywanie plików cookie.

**Comment by krystian3w** [comment]
`###optanon`
`##.optanon-alert-box-wrapper`

by _**Cookiemonster**_.

---
`###optanon:not(body):not(html)`

by _**I don't care about cookies**_.
