### ISSUE TITLE
nomoresecrets.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6807]
![2018-04-04-nomoresecrets seo blog and forum darmowe wsparcie przy tworzenie bloga skle](https://user-images.githubusercontent.com/5884000/38283274-64f22c64-37b5-11e8-834f-27c7c2bb2704.png)

komunikat

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.18
 ND 13.49
 Chr 65.0.3325.181
</details>

**Comment by MajkiIT** [comment]
@hawkeye116477 widzisz to?

**Comment by hawkeye116477** [comment]
@MajkiIT Tak generalnie to raczej to kwalifikuje się do Sociala, ale ja tego nie widzę.

**Comment by WowDude** [comment]
@MajkiIT I see it too
