### ISSUE TITLE
gaiakodi.com

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#6808]
Hej sluchajcie ja wiem ze to nie jest polska strona ale sami wiecie ze moj angielski pisany jest do dupy nie do nieba  a mam wrazenie ze na tej stronie pachnie koparka krypto mogl by ktos zrobić test? ostrzegam ja wczoraj wszedlem na ta strone a dzis rano defender wykryl mi bitcoinminnera malwarebytes dodatkowe 2 XD

**Comment by gzenio22** [comment]
@WowDude thank you

**Comment by WowDude** [comment]
@gzenio22 no problem, just forgot to tell you that you must also tell your settings:

> ### Describe the issue
> 
> I have the impression that on this page smells a crypto miner could someone do a test? I warn you yesterday I entered this page and this morning my defender detected me bitcoinminner malwarebytes extra 2 XD
> 
> ### Versions
> 
> - Browser/version: [here] **(przeglądarka)**
> - uBlock Origin version: [here] 
> 
> ### Settings
> 
> - [List here all the changes you made to uBO's default settings] **(listy filtrów)**
>

**Comment by gzenio22** [comment]
@WowDude zaskakujesz mnie Wybacz ze pisze po polsku duzo mi łatwiej hoc tobie utrudniam za co przepraszam o kopii filtrow zapomniałem moglem faktycznie wstawic gista ale widze ze ktos tam podal regułe
