### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by bitex1200x** [MajkiIT/polish-ads-filter#6809]
### Zrzut ekranu
![zaznaczenie_001](https://user-images.githubusercontent.com/38071647/38305269-9132c35e-380c-11e8-9199-ad1adf55fa4e.png)
![zaznaczenie_002](https://user-images.githubusercontent.com/38071647/38305276-9a05e52e-380c-11e8-9704-8285fae2f174.png)

### Link bezpośredni
https://www.dobreprogramy.pl/
i podstrony (na dodatkowym zrzucie podstrona https://www.dobreprogramy.pl/VeraCrypt-szybciej-zaszyfruje-Twoje-dane-na-dysku-nowym-rosyjskim-szyfrem,News,87289.html )

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Nic

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome - Linux
Wersja 65.0.3325.181 (Oficjalna wersja) (64-bitowa)
**Rozszerzenia i skrypty:**
AdBlock
Poper Blocker
**Filtry:**
![zaznaczenie_003](https://user-images.githubusercontent.com/38071647/38305211-51d809d0-380c-11e8-92a7-4892688633df.png)

**Comment by KonoromiHimaries** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/master/nano_defender/readme.md

**Comment by krystian3w** [comment]
Wystarczy wymienić Adblock / Adblock Plus na uBlock Origin.

**Comment by MajkiIT** [comment]
@bitex1200x niestety adblock nie ma takich możliwości jak uBlock czy Nano. Musisz zmienić blokera.

**Comment by krystian3w** [comment]
Albo doinstaluj Diconnect - whatever. Tak na próbę zainstalowałem AdBlock i reklamy nie ma ale... Disconnect zablokował. Dodaje do whitelisty i nagle wycieka MediaMarkt.

https://chrome.google.com/webstore/detail/disconnect/jeoacafpbcihiomhlakheieifhpjdfeo?hl=pl

Tylko on potem może generować fałszywe komunikaty o wykryciu AdBlock / wyciąć coś na stronie a nie jakaś lista antyreklamowa.

**Comment by WowDude** [comment]
@bitex1200x Switch from ADP to [uBO](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?) or to [NA](https://chrome.google.com/webstore/detail/nano-adblocker/gabbbocakeomblphkmmnoamkioajlkfo).

**Comment by hawkeye116477** [comment]
Albo można zablokować ten skrypt => `||a.wpimg.pl/a/i/stg/wpjslib-pwpnojq.js$domain=dobreprogramy.pl`, ale wtedy zapewne jeszcze coś innego przy okazji się zepsuje.
