### ISSUE TITLE
opoka.org.pl

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6811]
empty grey ADS containers

### Zrzut ekranu

Screenshoot 1
![capture_052_04042018_183851](https://user-images.githubusercontent.com/37474031/38321361-b987a628-3837-11e8-9ca3-c0debf53d6cb.png)

Screenshoot 2
![capture_053_04042018_183858](https://user-images.githubusercontent.com/37474031/38321364-be257da4-3837-11e8-8f93-72deb02928fb.png)

### Link bezpośredni

https://opoka.org.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.24

### Filtry:

<details>
  <summary>Click to expand</summary>

Nano Defender 13.48
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard’s Annoyance List
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Annoyance List
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
Fanboy’s Social Blocking List
I'm OK with cookies​
I don't care about cookies
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Anty-Donacyjne
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry RSS​
Polskie Filtry Społecznościowe​
Polskie Filtry Wewnętrzne
KAD - Przekręty

</details>

**Comment by MajkiIT** [comment]
`opoka.org.pl###bl4, #bl1444, #bl1490`

**Comment by WowDude** [comment]
Not working, they set random names, now it is: `###bl169`, `###bl26`

<details>
  <summary>Screenshoots</summary>

# https://opoka.org.pl/

![capture_058_04042018_192225](https://user-images.githubusercontent.com/37474031/38323511-bbab4846-383d-11e8-99d2-c55187eebed3.png)

![capture_057_04042018_192221](https://user-images.githubusercontent.com/37474031/38323510-bb858b7e-383d-11e8-9ee2-d3aafa8935bc.png)

# https://biblioteka.opoka.org.pl/

![capture_060_04042018_192300](https://user-images.githubusercontent.com/37474031/38323515-bc113642-383d-11e8-8763-56ad0592c5cc.png)

![capture_059_04042018_192255](https://user-images.githubusercontent.com/37474031/38323513-bbce9f3a-383d-11e8-9d23-20a4bdfb1524.png)

</details>

**Comment by MajkiIT** [comment]
@WowDude maybe like this `opoka.org.pl##.front_block.content_source_reklamy`

**Comment by WowDude** [comment]
@MajkiIT : yes, working, fixed.
