### ISSUE TITLE
optyczne.pl

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6812]
empty grey ADS container, (just like in https://github.com/MajkiIT/polish-ads-filter/issues/6811)

### Zrzut ekranu

![capture_054_04042018_185231](https://user-images.githubusercontent.com/37474031/38322019-7ad35cd6-3839-11e8-8e82-7d9128f5e54c.png)

### Link bezpośredni

https://www.optyczne.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.24

### Filtry:

<details>
  <summary>Click to expand</summary>

Nano Defender 13.48
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard’s Annoyance List
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Annoyance List
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
Fanboy’s Social Blocking List
I'm OK with cookies​
I don't care about cookies
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Anty-Donacyjne
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry RSS​
Polskie Filtry Społecznościowe​
Polskie Filtry Wewnętrzne
KAD - Przekręty

</details>

**Comment by MajkiIT** [comment]
```
www.optyczne.pl##.panel:nth-of-type(3)
www.optyczne.pl##.panel.shop-offer
```

But I don't see any grey elements.

**Comment by WowDude** [comment]
`Fanboy's Polish` is causing it, disabling this list fixes the issue.
