### ISSUE TITLE
vpn

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#6826]
@MajkiIT zakupisz?

https://www.mydevil.net/vpn.html

**Comment by MajkiIT** [comment]
Ok, na razie dla testu na miesiąc czy od razu na 1/2 roku?

**Comment by xxcriticxx** [comment]
1 month please

**Comment by gzenio22** [comment]
Naj szybszy z jakiego korzystam a przetestowalem i exspress i nord i HMA no i tego zielonego androida naj szybszy jest pureVPN i ma sporo funkcji

**Comment by xxcriticxx** [comment]
@gzenio22 nie zapomni ze ja na drugim końcu świata

**Comment by MajkiIT** [comment]
@xxcriticxx wyślij mi maila ...

**Comment by xxcriticxx** [comment]
poszlo na mm.....ski@certyficate.it

**Comment by xxcriticxx** [comment]
@MajkiIT podaj paypal info

**Comment by xxcriticxx** [comment]
@MajkiIT ciekawe czy pociagnie POLANDIE

**Comment by xxcriticxx** [comment]
@MajkiIT wykupiles vpn na nastepne miesciace? mam tobie kase przelac paypalem? bo juz sie pogubilem w temacie
