### ISSUE TITLE
kobieta.wp.pl

### ISSUE THREAD

**Issue by DagmaraG** [MajkiIT/polish-ads-filter#6827]
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na stronę
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:** Chrome, Mozilla FF

**Rozszerzenia i skrypty:**

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. 
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by MajkiIT** [comment]
@DagmaraG i co jest nie tak?

**Comment by MajkiIT** [comment]
Adblock ?

**Comment by DagmaraG** [comment]
Tak, to AdBlock kazał mi właśnie przejść przez tę procedurę po kolei. Ja bym sama nie wiedziała, co sprawdzić i gdzie. ;)
 
W dniu 2018-04-04 23:04:51 użytkownik Maciej M. <notifications@github.com> napisał:
Adblock ?

**Comment by MajkiIT** [comment]
Adblock jest przestarzały . Nie ma takich możliwości jak uBlock czy Nano. Możesz przesiąść się na nowsze rozwiązanie?

**Comment by DagmaraG** [comment]
Tak zrobiłam. Reklamy znikły całkowicie! Dziękuję bardzo! Za rady i cierpliwość. ;)
 
 
W dniu 2018-04-04 23:21:12 użytkownik Maciej M. <notifications@github.com> napisał:
Wrzuć sobie Nano Defender + Nano Adblocker
https://www.certyficate.it/blokowanie-alertow-informacji-o-adblock/

**Comment by MajkiIT** [comment]
@DagmaraG No to super. Nie ma problemu.
