### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by Asussonicmasterr** [MajkiIT/polish-ads-filter#6828]
### Zrzut ekranu
 https://www.wykop.pl/cdn/c3201142/comment_fWZhO2ogoQYavXw2h40omub1sVnJSND8.jpg
### Link bezpośredni
 https://www.dobreprogramy.pl/Juz-wkrotce-Windows-sam-pozbedzie-sie-zbednych-plikow-i-zwolni-miejsce-na-dysku,News,87300.html

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na stronę.
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**
Opera 
52.0.2871.40
**Rozszerzenia i skrypty:**
Ublock origin POl: polskie skrypty do adblocka i ublocka
Adblock Plus 
Ghostery
Adguard
Opera Block

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. 
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
Na Operze wycieka, możesz doinstalować Disconnect **ale może on potem generować fałszywe alarmy i dodania wieku stron na białą listę i kłócić z posiadanym Ghostery!**

https://addons.opera.com/pl/extensions/details/disconnect/

**Comment by seba2282** [comment]
Próbowałeś nano adblocker? Mi blokuje na szczęście już reklamy.

**Comment by krystian3w** [comment]
I i najlepiej wywal nadmierną ilość blokerów - powinien zostać uBlock lub Adguard i go dobrze skonfigurować.

Dla przykładu Adguard i adblock plus nie zablokował ci nic lub ukryłes ikonkę ile zablokował.

**Comment by seba2282** [comment]
Chociaż nie wiem czy jest dla opery...

**Comment by krystian3w** [comment]
Nie jest trzeba używać portowanego z chrome web store a jak testowałem to działał spoko.

**Comment by MajkiIT** [comment]
@Asussonicmasterr 

A po co aż 3 ?

- Ublock origin POl: polskie skrypty do adblocka i ublocka
- Adblock Plus
- Adguard

**Comment by Asussonicmasterr** [comment]
@MajkiIT Myślałem, że im więcej tym lepiej :dagger:

**Comment by Asussonicmasterr** [comment]
Chyba blocker Dissconect rozwiązał problem

**Comment by krystian3w** [comment]
Tak, bo sieciowo blokuje łączenie z WP przez dobreprogramy.

**Comment by xxcriticxx** [comment]
@Asussonicmasterr welcome to the jungle!

**Comment by MajkiIT** [comment]
@Asussonicmasterr no nie, wystarczy 1 najlepiej uBo lub Nano.
