### ISSUE TITLE
expresselblag.pl

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6840]
Empty AD container

### Zrzut ekranu

![capture_118_05042018_172308](https://user-images.githubusercontent.com/37474031/38375233-05016dfa-38f6-11e8-89ec-4ede28d2b4a3.png)

![tytyt](https://user-images.githubusercontent.com/37474031/38375275-2118f044-38f6-11e8-890e-23a4122cbe8c.png)

![wwwww](https://user-images.githubusercontent.com/37474031/38375399-6211b356-38f6-11e8-989e-584e91db3fdd.png)

### Link bezpośredni

 http://expresselblag.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.24

### Filtry:

<details>
  <summary>Click to expand</summary>

Nano Defender 13.48
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard’s Annoyance List
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Annoyance List
Fanboy’s Anti-Thirdparty Social (see warning inside list)
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
Fanboy’s Social Blocking List
I'm OK with cookies​
I don't care about cookies
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Anty-Donacyjne
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry RSS​
Polskie Filtry Społecznościowe​
Polskie Filtry Wewnętrzne
AlleBlock​
KAD - Przekręty

</details>

**Comment by MajkiIT** [comment]
@WowDude I don't see thus. @hawkeye116477 zerkniesz?

**Comment by hawkeye116477** [comment]
Ja tam widzę resztkę, ale nieco niżej pod napisami wiadomości, lifestyle, itd.

**Comment by WowDude** [comment]
@MajkiIT 
@hawkeye116477 

Similiar case to https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/639#issuecomment-379018990

I have it on 125% DPI, but I also have it on 100% DPI but in different place:

![kfjfg](https://user-images.githubusercontent.com/37474031/38441379-caac8a8c-39e4-11e8-94d2-8b6f6c5ad0e9.png)

**Comment by MajkiIT** [comment]
@WowDude Thanks
