### ISSUE TITLE
kobietymedycyny.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6862]
![zrzut ekranu z 2018-04-06 07-41-54](https://user-images.githubusercontent.com/36385327/38405355-b82d758a-396f-11e8-8b6f-054451e6c332.png)

**Comment by krystian3w** [comment]
<b>

```
kobietymedycyny.pl##script:contains(Żeby głosować musisz mieć włączoną obsługę cookies)
```

</b>

---

<sup>

```
<script type="text/javascript">
			$(document).ready(function() {
				alert("Żeby głosować musisz mieć włączoną obsługę cookies");
			});
		</script>
```
</sup>

**Comment by hawkeye116477** [comment]
@krystian3w W Chromium to nie działa, tylko w przypadku Firefoksa jest ok.

**Comment by WowDude** [comment]
@krystian3w 
@hawkeye116477

Also this filter is invalid, should be `##^`

**Comment by krystian3w** [comment]
We used other method, no HTML filtering.

**Comment by hawkeye116477** [comment]
@krystian3w U mnie działa to co dodałem :smile:.
