### ISSUE TITLE
utrzymanieruchu.pl

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6867]
1 .Social icons/buttons
2. Paid subscription (Płatna prenumerata)

### Zrzut ekranu

![capture_019_06042018_102259](https://user-images.githubusercontent.com/37474031/38410696-9438067a-3985-11e8-876b-417d468d46eb.png)

### Link bezpośredni

http://www.utrzymanieruchu.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.24

### Filtry:

<details>
  <summary>Click to expand</summary>

Nano Defender 13.48
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard’s Annoyance List
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Annoyance List
Fanboy’s Anti-Thirdparty Social (see warning inside list)
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
Fanboy’s Social Blocking List
I'm OK with cookies​
I don't care about cookies
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Anty-Donacyjne
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry RSS​
Polskie Filtry Społecznościowe​
Polskie Filtry Wewnętrzne
AlleBlock​
KAD - Przekręty

</details>

**Comment by krystian3w** [comment]
`###portale_spolecznosciowe`

`###zamow_prenumerate`

**Comment by KonoromiHimaries** [comment]
wolałbym nie agregować przycisków manipulacyjnych znajdujących się w panelu kontrolnym na topce

wymusza to konieczność agregacji innych przycisków podobnych przycisków w przyszłości. dlatego uważam że lepiej jest nie agregować, z uwagi na większe korzyści użytkowników końcowych.

jeśli przycisk przeszkadza, jest irytujący lub nadmiernie intruzywny to chętnie pomogę. jednak niczego takiego w tym przypadku nie widzę.

**Comment by WowDude** [comment]
@KonoromiHimaries ok.

**Comment by hawkeye116477** [comment]
@krystian3w Trochę za mocne, RSS też wytnie.

**Comment by krystian3w** [comment]
`target="_blank"` można by po tym spróbować zrobić 1 filtr.

`###portale_spolecznosciowe >a[target="_blank"]`, RSS-a nie wymuszają w nowej karcie a ograniczenie do id społecznościówki nie powinno wyciąć nadmiaru linków.

No chyba, że będzie mega wolny / obciążający niż 3.
