### ISSUE TITLE
waran.pl

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6870]
Social scrolling widgets

### Zrzut ekranu

![capture_025_06042018_103823](https://user-images.githubusercontent.com/37474031/38411147-ae1bf776-3986-11e8-94e4-afc57904a2ea.png)

### Link bezpośredni

 http://www.waran.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.24

### Filtry:

<details>
  <summary>Click to expand</summary>

Nano Defender 13.48
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard’s Annoyance List
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Annoyance List
Fanboy’s Anti-Thirdparty Social (see warning inside list)
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
Fanboy’s Social Blocking List
I'm OK with cookies​
I don't care about cookies
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Anty-Donacyjne
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry RSS​
Polskie Filtry Społecznościowe​
Polskie Filtry Wewnętrzne
AlleBlock​
KAD - Przekręty

</details>

**Comment by krystian3w** [comment]
`##div[style="width: 42px; height: 100px; position: fixed; top: 240px; z-index: 99999; right: 0px;"]`
`##div[style="width: 42px; height: 100px; position: fixed; top: 340px; z-index: 99999; right: 0px;"]`

or uBO 1.11.0+:

`##div[style]:matches-css(width: 42px):matches-css(height: 100px):matches-css(position: fixed):matches-css(z-index: 99999):matches-css(right: 0px)`

**Comment by hawkeye116477** [comment]
@krystian3w Za bardzo kombinujesz :stuck_out_tongue: 
```
||waran.pl/wp-content/uploads/2018/02/f1.png
||waran.pl/wp-content/uploads/2018/02/t1.png
```
