### ISSUE TITLE
dbpolska.net

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#6878]
![2018-04-06-dragon ball polska - dragon ball z gt kai oraz super odcinki z napisami do p](https://user-images.githubusercontent.com/5884000/38417477-c17f5454-3998-11e8-91e7-d8225b779de3.png)

refy

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.24
 ND 13.51
 Chr 65.0.3325.181
</details>

**Comment by MajkiIT** [comment]
`dbpolska.net##[id^="reklama_bok"]`
