### ISSUE TITLE
radiopoznan.fm

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#6899]
1. Ad
2. Social icons/buttons

### Zrzut ekranu

1
![capture_055_06042018_162259](https://user-images.githubusercontent.com/37474031/38426393-d468596c-39b6-11e8-9bec-f01645c876d2.jpg)

2
![capture_056_06042018_162308](https://user-images.githubusercontent.com/37474031/38426395-d486e1c0-39b6-11e8-97f4-a4829b84ef3a.jpg)

### Link bezpośredni

http://radiopoznan.fm/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.24

### Filtry:

<details>
  <summary>Click to expand</summary>

Nano Defender 13.48
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard’s Annoyance List
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Annoyance List
Fanboy’s Anti-Thirdparty Social (see warning inside list)
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
Fanboy’s Social Blocking List
I'm OK with cookies​
I don't care about cookies
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Anty-Donacyjne
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry RSS​
Polskie Filtry Społecznościowe​
Polskie Filtry Wewnętrzne
AlleBlock​
KAD - Przekręty

</details>

**Comment by hawkeye116477** [comment]
Nie wiem co jest grane na tej stronie, ale od razu wszystko się chowa.

**Comment by MajkiIT** [comment]
@hawkeye116477 tam jest jakiś iframe ... nie mogę go rozgryźć.

**Comment by hawkeye116477** [comment]
@MajkiIT `||radiopoznan.fm/v2/js/javascripts.js` i po problemie :smile:

**Comment by hawkeye116477** [comment]
`hawkeye116477 your filter breaks the menu, the menu won't open after adding the filter:`
Nic nie szkodzi, można tymczasowo dodać taki filtr, by móc skorzystać z pickera :smile:.
