### ISSUE TITLE
astroweb.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#696]
http://astroweb.pl/pl/k/feng-shui/

**Comment by xxcriticxx** [comment]
niemoge dzisaj nic znalesc :(

**Comment by MajkiIT** [comment]
spokojnie. Zobacz ile już znalazłeś. 99% zgłoszeń jest od ciebie.

**Comment by xxcriticxx** [comment]
wiem ale tak jak mowie jest coraz ciezej

**Comment by MajkiIT** [comment]
to z jednej strony dobrze, bo filtry zapewniają to co być powinno.
