### ISSUE TITLE
fotoblogia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6967]
fotoblogia.pl

![opera zdjecie_2018-04-07_210626_fotoblogia pl](https://user-images.githubusercontent.com/36385327/38459241-aab8306e-3aa7-11e8-8b56-72990dd6657b.png)

https://fotoblogia.pl/12077,jego-zdjecia-sa-naprawde-glosne-radek-zawadzki-i-jego-fotografia-koncertowa
Czasami po odświeżeniu strony pojawia się reklama
![opera zdjecie_2018-04-07_210805_fotoblogia pl](https://user-images.githubusercontent.com/36385327/38459258-d7b1fe60-3aa7-11e8-8366-c02cea727766.png)

Social w artykułach 
https://fotoblogia.pl/12077,jego-zdjecia-sa-naprawde-glosne-radek-zawadzki-i-jego-fotografia-koncertowa
![opera zdjecie_2018-04-07_210951_fotoblogia pl](https://user-images.githubusercontent.com/36385327/38459277-0dffbe1c-3aa8-11e8-88c5-2811ef13cec0.png)
![opera zdjecie_2018-04-07_211051_fotoblogia pl](https://user-images.githubusercontent.com/36385327/38459290-2f2558a4-3aa8-11e8-90bb-726e2cb48253.png)

**Comment by hawkeye116477** [comment]
Nie wiem co z tym fantem zrobić, daję regułę, a i tak to znowu się pojawia.

**Comment by krystian3w** [comment]
```
gadzetomania.pl,fotoblogia.pl,komorkomania.pl##a[href^="https://www.facebook.com/sharer.php"]:style(visibility:hidden!important)
gadzetomania.pl,fotoblogia.pl,komorkomania.pl##a[href^="http://twitter.com/intent/tweet"]:style(visibility:hidden!important)
gadzetomania.pl,fotoblogia.pl,komorkomania.pl##a[href^="http://pinterest.com/pin/create/link/"]:style(visibility:hidden!important)
```

głupie ale działa, nie umieją na razie podmienić `visibility`.

**Comment by xMaap** [comment]
Działa. Jeszcze zostało na gadzetomania.pl fotoblogia.pl komorkomania.pl

![opera zdjecie_2018-04-16_154512_fotoblogia pl](https://user-images.githubusercontent.com/36385327/38812821-9f04c5a6-418d-11e8-9f93-44531c645026.png)

I na samej fotoblogia.pl
![opera zdjecie_2018-04-16_155100_fotoblogia pl](https://user-images.githubusercontent.com/36385327/38812975-017419e4-418e-11e8-9e31-253c829ee24a.png)
