### ISSUE TITLE
gadzetomania.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6968]
https://gadzetomania.pl/60126,tin-audio-t2-test-i-recenzja
![opera zdjecie_2018-04-07_211347_gadzetomania pl](https://user-images.githubusercontent.com/36385327/38459336-a44d88fe-3aa8-11e8-918a-b61b67682572.png)
![opera zdjecie_2018-04-07_211447_gadzetomania pl](https://user-images.githubusercontent.com/36385327/38459350-c00525d4-3aa8-11e8-8af5-8adfb5b6b3c6.png)

**Comment by krystian3w** [comment]
Zobacz podobnie jak dla komorkomani @xMaap
