### ISSUE TITLE
komorkomania.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6969]
https://komorkomania.pl/35812,jaki-byl-twoj-pierwszy-telefon
![opera zdjecie_2018-04-07_211600_komorkomania pl](https://user-images.githubusercontent.com/36385327/38459367-eab20aea-3aa8-11e8-93d8-f317ad078fa5.png)
![opera zdjecie_2018-04-07_211638_komorkomania pl](https://user-images.githubusercontent.com/36385327/38459377-0295c84a-3aa9-11e8-8ce2-c55683b2c369.png)

**Comment by blocker999** [comment]
Dziwne ja nic niemam

@xMaap A masz  "Fanboy’s Social Blocking List " włączone?
Bo z tego co wiem to paczka z elementami społecznościowymi jest tylko uzupełnieniem : 
https://www.certyficate.it/polskie-filtry-elementow-spolecznosciach/

![social](https://user-images.githubusercontent.com/23176832/38459870-c210af04-3aaf-11e8-8dc2-0123bbea0a75.png)
https://www.certyficate.it/adblock/

**Comment by xMaap** [comment]
@blocker999 oczywiście 
![zrzut ekranu z 2018-04-07 22-16-08](https://user-images.githubusercontent.com/36385327/38459985-57c935ce-3ab1-11e8-8d4d-c0d837ee1606.png)

**Comment by krystian3w** [comment]
U mnie zostaje YT i przyciski obok ładowania komentarzy.


![obraz](https://user-images.githubusercontent.com/35370833/38460548-6d45eb80-3abc-11e8-936a-9a3b9ac731e9.png) |
--- |

`##.link-youtube`

![obraz](https://user-images.githubusercontent.com/35370833/38460510-82ab63a2-3abb-11e8-9a58-d1070f4f96e6.png) |
--- |

`##.post-article-links > .social-links.share-links > a:not(:last-child)` ❓

**Comment by krystian3w** [comment]
A miesza Annoyance jak nie było aktualizacji polskiej listy, odznaczyłem i przyblokowało.

**Comment by krystian3w** [comment]
Wyczyść pamięć podręczną filtrów i zaktualizuj.

Polską listę zasubskrybuj spod githubowego adresu.

`Adguard’s Annoyance List​​​` i ​​​​​`Fanboy’s Annoyance List` wyłącz jeśli będą wciąż elementy na  komórkomanii.

**Comment by krystian3w** [comment]
Mam winnego, Nano Defender Integration.

**Comment by krystian3w** [comment]
OK, chyba ślepa uliczka z Nano Defenderem...

**Comment by WowDude** [comment]
I don't have it too, it's removed by one of flollowing lists:
- Fanboy’s Annoyance List
- Fanboy’s Social List
- Web Annoyances Ultralist

**Comment by xMaap** [comment]
Ok, powyłączałem wszystko z Adguard, ale tutaj chyba jest winne ślinik Chrome, bo wszystko Chromopodobne ma to. a na Firefox jest jak należy.

**Comment by WowDude** [comment]
@xMaap I agree, there is diffeerence:

1 on Firefox I don't see it, nor "Komentarze":

![firefox](https://user-images.githubusercontent.com/37474031/38466014-ea1b51b6-3b22-11e8-9a58-bb8e8ab1aa70.png)

2 but on Chrome I still see it + "Komentarze":

![chrome](https://user-images.githubusercontent.com/37474031/38466015-ecc9b75e-3b22-11e8-8949-21b10195f585.png)

**Comment by hawkeye116477** [comment]
Zdaje się, że problem ten nie występuje na ABP.
