### ISSUE TITLE
Kiedy wróci instrukcja instalacji uBlock w Yandex

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#6974]
Zniknęła i nie ma.

**Comment by MajkiIT** [comment]
@hawkeye116477 masz gdzieś to ?

**Comment by hawkeye116477** [comment]
@MajkiIT Nie mam. Może niedługo coś zrobię. Ale tak w zasadzie to tylko stable wymaga specjalnej metody, uBO dev i Nano Adblocker można zainstalować normalnie z Chrome Store.

**Comment by MajkiIT** [comment]
@krystian3w wróciło
