### ISSUE TITLE
topagrar.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6985]
topagrar.pl
![opera zdjecie_2018-04-08_052855_www topagrar pl](https://user-images.githubusercontent.com/36385327/38462869-cae52928-3aed-11e8-925c-d63b0c319cdf.png)
![opera zdjecie_2018-04-08_053000_www topagrar pl](https://user-images.githubusercontent.com/36385327/38462877-e95312ee-3aed-11e8-9181-09bd21b20a87.png)
![opera zdjecie_2018-04-08_053052_www topagrar pl](https://user-images.githubusercontent.com/36385327/38462885-09245c22-3aee-11e8-875b-91b0c3c88d31.png)
![opera zdjecie_2018-04-08_053135_www topagrar pl](https://user-images.githubusercontent.com/36385327/38462894-268e42c8-3aee-11e8-8388-80320d344da1.png)
![opera zdjecie_2018-04-08_053216_www topagrar pl](https://user-images.githubusercontent.com/36385327/38462898-3e336bd8-3aee-11e8-82fd-ae5cdc36cd10.png)
Najechać kursorem myszki na menu
![opera zdjecie_2018-04-08_053310_www topagrar pl](https://user-images.githubusercontent.com/36385327/38462909-75acdf9a-3aee-11e8-9344-b4336497b539.png)

topagrar.pl/articles/aktualnosci/zakaz-pasz-gmo-od-2024-roku-rzad-zglasza-nowelizacje-ustawy/
![opera zdjecie_2018-04-08_053709_www topagrar pl](https://user-images.githubusercontent.com/36385327/38462947-ebd42390-3aee-11e8-807f-56063dcf611f.png)
![opera zdjecie_2018-04-08_053744_www topagrar pl](https://user-images.githubusercontent.com/36385327/38462953-fee55238-3aee-11e8-89ad-575576203cc7.png)
![opera zdjecie_2018-04-08_053822_www topagrar pl](https://user-images.githubusercontent.com/36385327/38462961-163e5cc2-3aef-11e8-9fb0-34a676ff6421.png)
![opera zdjecie_2018-04-08_053854_www topagrar pl](https://user-images.githubusercontent.com/36385327/38462966-2777c334-3aef-11e8-8f4b-bcf9dfcebf7c.png)

**Comment by MajkiIT** [comment]
@xMaap u mnie czysto 
@KonoromiHimaries @hawkeye116477 zerkniecie ?

**Comment by hawkeye116477** [comment]
@MajkiIT wyłączy Polish Privacy, to reklamy się pojawią.
