### ISSUE TITLE
di.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#6987]
Social
![opera zdjecie_2018-04-08_062910_di com pl](https://user-images.githubusercontent.com/36385327/38463246-66c00a68-3af6-11e8-92d7-3d9468f7f341.png)

Ja się na kilka dni wyłączam aż wszystko zostanie ogarnięte, bo widzę, ze nie nadążacie  :full_moon_with_face:

**Comment by krystian3w** [comment]
`##.subbelka > ul > li:nth-of-type(7)` - FB
`##.subbelka > ul > li:nth-of-type(6)` - RSS
`##.subbelka > ul > li:nth-of-type(5)` - Newsletter
