### ISSUE TITLE
magazif.com

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#7010]
1 Ads
2 Ad empty container

### Zrzut ekranu

1a
![capture_010_09042018_124005](https://user-images.githubusercontent.com/37474031/38493699-553916a6-3bf3-11e8-9a2b-c37d8b8c4a38.png)

1b
![capture_011_09042018_124028](https://user-images.githubusercontent.com/37474031/38493701-567e8000-3bf3-11e8-9491-7ce9c5833047.png)

2
![capture_012_09042018_124032](https://user-images.githubusercontent.com/37474031/38493702-57710bfe-3bf3-11e8-9e92-a226f174d981.png)

### Link bezpośredni

http://magazif.com/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.24

### Filtry:

<details>
  <summary>Click to expand</summary>

Nano Defender 13.48
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard’s Annoyance List
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Annoyance List
Fanboy’s Anti-Thirdparty Social (see warning inside list)
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
I'm OK with cookies​
I don't care about cookies
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Anty-Donacyjne
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry RSS​
Polskie Filtry Społecznościowe​
Polskie Filtry Wewnętrzne
AlleBlock​
KAD - Przekręty
Web Annoyances Ultralist

</details>

**Comment by MajkiIT** [comment]
@WowDude Please, do not create new issue. We must close old.

**Comment by KonoromiHimaries** [comment]
@WowDude join to discord `https://discord.me/polskiefiltry`

**Comment by WowDude** [comment]
@KonoromiHimaries why, what's the problem? I don't have discord, I don't use it.

**Comment by MajkiIT** [comment]
@WowDude Because there are too many entries. Can you respect that?

**Comment by WowDude** [comment]
@MajkiIT why is it too many for you? What is the problem with 80 issues?

**Comment by krystian3w** [comment]
Ok, I sorry, I said a little jokingly.

A little bit less in the users value collaborators (I am fix only readme file and add new nano defender xpi) - listen more to the Owner and Contributors they create filter lists to the greatest extent.

They have (Owner and Contributors) to test the filters well to add the least affecting the other pages to a negative extent.

**Comment by krystian3w** [comment]
Ok, I sorry, I said a little jokingly.

Listen more to the **Owner (MajkiIT), KonoromiHimaries, hawkeye116477, F4z**,  they create filter lists to the greatest extent.

They have to time to test the filters, well to add the least affecting the other pages to a negative extent.

**Comment by WowDude** [comment]
1) As far as I see noone enforces them to fix all the issues at the same time (day)... they can fix as much as they can per a day and leave the rest for another day(s).
2) I see that @krystian3w suggests filters in issues, write permissions to Polish Social Filters can be granted to him and he will help a lot.

**Comment by krystian3w** [comment]
I do not know, I rather do not want to support Social List (I would not want to destroy her), I can toss the cosmetic / network rules to better start block given page.

**Comment by MajkiIT** [comment]
@WowDude You remind me of someone. If someone asks you for something, it would be nice to respect it.

**Comment by WowDude** [comment]
stfy, fyi
