### ISSUE TITLE
glogow-info.pl

### ISSUE THREAD

**Issue by WowDude** [MajkiIT/polish-ads-filter#7027]
1 Ads
2 Ads empty containers

### Zrzut ekranu

1a
![capture_044_09042018_161050](https://user-images.githubusercontent.com/37474031/38502847-d64ba44e-3c10-11e8-906e-4ab21f2ba2ae.png)

1b
![capture_047_09042018_161104](https://user-images.githubusercontent.com/37474031/38502848-d676cc14-3c10-11e8-80f9-ac77aff137d9.png)

1c
![capture_048_09042018_161111](https://user-images.githubusercontent.com/37474031/38502850-d69ed13c-3c10-11e8-8368-13bfdc38b501.png)

2a
![capture_043_09042018_161047](https://user-images.githubusercontent.com/37474031/38502878-e7003a7a-3c10-11e8-920f-c85dce5b483c.png)

2b
![capture_045_09042018_161057](https://user-images.githubusercontent.com/37474031/38502879-e72ecb60-3c10-11e8-8534-776026be9d38.png)

2c
![capture_046_09042018_161100](https://user-images.githubusercontent.com/37474031/38502880-e754b096-3c10-11e8-864e-2e39730c196b.png)

### Link bezpośredni

http://glogow-info.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.24

### Filtry:

<details>
  <summary>Click to expand</summary>

Nano Defender 13.48
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard’s Annoyance List
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Annoyance List
Fanboy’s Anti-Thirdparty Social (see warning inside list)
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
I'm OK with cookies​
I don't care about cookies
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Anty-Donacyjne
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry RSS​
Polskie Filtry Społecznościowe​
Polskie Filtry Wewnętrzne
AlleBlock​
KAD - Przekręty
Web Annoyances Ultralist

</details>

**Comment by MajkiIT** [comment]
#6359
