### ISSUE TITLE
Times Square z włączonym Adblockiem.

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#704]
Times Square z włączonym Adblockiem.

http://x3.cdn03.imgwykop.pl/c3201142/comment_FKtnJQzdCxe27IMbEKwMdoVzDod1gKqe.jpg

**Comment by xxcriticxx** [comment]
a potem 


dondon 2 dni temu

+1

Polecicie jakiś polski filtr? Bo w adblocku nie mam takiego do wyboru, a przechodzą mi niektóre reklamy
#adblock #firefox	
+: marsellus

    link 

‹ embed ›

     
    Prezes_roku 2 dni temu

    +1

    @dondon: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt	
    +: dondon
        link 
     
    dondon 2 dni temu

    0

    @Prezes_roku: Dzięki

**Comment by MajkiIT** [comment]
dzieki
