### ISSUE TITLE
olx.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#7063]
Witam, chciał bym złościć problem ze stroną olx.pl przy włączonym ublock origin niemożna przełączać na kolejne strony ogłoszeń?

@KonoromiHimaries @xxcriticxx @hawkeye116477 macie to?

![30629012_1949835985050499_8701234035206127616_n](https://user-images.githubusercontent.com/11302675/38576610-e561e13e-3cfe-11e8-9f49-679c49e353fc.png)
![30571762_1949835978383833_4369586533087313920_n](https://user-images.githubusercontent.com/11302675/38576611-e5867094-3cfe-11e8-88b4-7ca6b57892c0.png)
![30594958_1949835971717167_7588536265125920768_n](https://user-images.githubusercontent.com/11302675/38576612-e5ab8dde-3cfe-11e8-93ad-161fefb8916b.png)

**Comment by gzenio22** [comment]
![screenshot_1](https://user-images.githubusercontent.com/21177361/38577989-da23fe0c-3d02-11e8-810e-c6f8046aeff3.png)

Koles ma racje to kolko kreci sie w nieskonczonosc jak chce przejsc na kolejna strone ofert

**Comment by MajkiIT** [comment]
`@@/js/tracking/$script,domain=www.olx.pl`

**Comment by blocker999** [comment]
o dokładnie to samo miałem niedawno

**Comment by blocker999** [comment]
@MajkiIT No i teraz jest ok
