### ISSUE TITLE
gry-planszowe.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#7095]
![2018-04-13-gry-planszowe pl - wykaz forow](https://user-images.githubusercontent.com/5884000/38728573-8a552a44-3f10-11e8-8b88-51d4a9be3956.png)
`http://gry-planszowe.pl/forum/index.php?`

anty-adblock + reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.24
 ND 13.51
 Chr 65.0.3325.181
</details>

**Comment by krystian3w** [comment]
`gry-planszowe.pl#@#.adsbox`
`gry-planszowe.pl##.phpbb-ads-center`
