### ISSUE TITLE
rynekzdrowia.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#7098]
`http://www.rynekzdrowia.pl/Technologie-informacyjne/Telemedycyna-Infoscan-chce-wejsc-na-rynek-francuski,181887,7.html`

pusta sekcja reklama pod sekcją komentarzy

**Comment by krystian3w** [comment]
```
||www.rynekzdrowia.pl/images/www/advB.png
##.advB
```

Jak zbyt agresywne, to można dodać więcej klas: `##.belka2.marginB.marginT.advB`
