### ISSUE TITLE
plus.polskatimes.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7099]
![opera zdjecie_2018-04-14_105853_plus polskatimes pl](https://user-images.githubusercontent.com/36385327/38766458-d91a8d82-3fd2-11e8-930b-433fdf063dbe.png)

**Comment by krystian3w** [comment]
Stopka, statyczna, **`@`hawkeye116477**  by nie ruszał pewnie.

**Comment by krystian3w** [comment]
`##.listaIkon`
