### ISSUE TITLE
vod.tvp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#7104]
nie wiem czy to czasem nie przez host file

zrobic ktos test

http://tvpstream.vod.tvp.pl/?channel_id=745680

![capture](https://user-images.githubusercontent.com/15007183/38772906-7d4d8c1a-400f-11e8-9d34-39ce73716a84.PNG)

**Comment by xMaap** [comment]
Działa z włączonym i wyłączonym Nano Defender.
![zrzut ekranu z 2018-04-15 12-00-24](https://user-images.githubusercontent.com/36385327/38777215-9ab7de14-40a4-11e8-95c8-f6c60e8d6f27.png)

**Comment by gzenio22** [comment]
tez mam adblocka ktoras z list jest wykrywana

**Comment by MajkiIT** [comment]
@gzenio22 jak przeglądarka ?

**Comment by gzenio22** [comment]
ja chropera najnowsza nano adb i defender w zestawie

**Comment by xxcriticxx** [comment]
@gzenio22 podaj do pingwina zobaczymy co napisze

**Comment by xMaap** [comment]
To moje na górze to Chromium 65.0.3325.181

A tutaj Opera 52.0.2871.64
![opera zdjecie_2018-04-15_175953_tvpstream vod tvp pl](https://user-images.githubusercontent.com/36385327/38780481-71964808-40d7-11e8-8166-f1f2bb4ade13.png)

**Comment by krystian3w** [comment]
W Firefox upewnijcie się czy macie włączoną ochronę prywatności, trzeba wyłączyć ją dla `tvpstream.vod.tvp.pl`:

<div align="center">

 
![obraz](https://user-images.githubusercontent.com/35370833/38780799-667f10da-40dc-11e8-941f-1c1723e19d7d.png) |
--- |

</div>

**Comment by MajkiIT** [comment]
@xxcriticxx niestety mam adblocka z pihole

**Comment by xxcriticxx** [comment]
@MajkiIT jest jakies lekarstwo?

**Comment by krystian3w** [comment]
Przeanalizować ruch jakich idzie przez pihole przy próbie otwarcia VOD?

**Comment by MajkiIT** [comment]
@xxcriticxx dodanie tego do WL powinno pomóc "myao.adocean.pl"

**Comment by MajkiIT** [comment]
@RobertLaudan chwilowo tylko dziala na uBo, że warto zmienić?

**Comment by RobertLaudan** [comment]
@MajkiIT Dzięki!

**Comment by lukjan32** [comment]
jest blokada

**Comment by krystian3w** [comment]
Na Firefox działa dalej:

`https://tvpstream.vod.tvp.pl/?channel_id=745680`

Link może i czy tylko nie działa w Operze / Chrome..,
