### ISSUE TITLE
njumobile.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7110]
![opera zdjecie_2018-04-16_144521_www njumobile pl](https://user-images.githubusercontent.com/36385327/38809764-f1c7d1b0-4184-11e8-9e08-86ff5746a528.png)

**Comment by krystian3w** [comment]
`##li > .sun-orb` - takie najprostsze bez `:not(:last-child)`, `:nth-last-child(1n+2)`.
