### ISSUE TITLE
eurogamer.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7112]
https://www.eurogamer.pl/articles/2018-04-16-polski-horror-agony-poddany-autocenzurze
![opera zdjecie_2018-04-16_171211_www eurogamer pl](https://user-images.githubusercontent.com/36385327/38817806-738c0004-4199-11e8-8246-4c50667e3d82.png)

**Comment by krystian3w** [comment]
`##.social` lub `##.circle.button`
