### ISSUE TITLE
a-o.ninja

### ISSUE THREAD

**Issue by bato3** [MajkiIT/polish-ads-filter#7118]
### Screen

https://screenshots.firefox.com/gZfRO5NGyXW9FkB8/a-o.ninja

### Link bezpośredni

https://a-o.ninja/anime/tachibanakan-triangle/2

### Moja konfiguracja
**Przeglądarka internetowa:**
FF x64, win 10
**Rozszerzenia i skrypty:**

Ublok orgin

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. AakList (Anti-Adblock Killer)​​
3. KAD - Przekręty​​
4. Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for uBlock​​
5. Polskie filtry anty-dotacyjne​​
6. Polskie filtry ciasteczkowe​​
7. Polskie filtry elementów irytujących​​
8. Polskie filtry elementów irytujących - uzupełnienie do uBlocka​​
9. Polskie filtry wewnętrzne​​

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

Zablokowany odtwarzacz i pojawia się ramka z aukcjami

**Comment by MajkiIT** [comment]
@bato3 wyłącz to AakList (Anti-Adblock Killer)​​ bo nie jest wspierane. Dodatkowo aktualizacja filtrów.

**Comment by bato3** [comment]
@MajkiIT odtwarzacz już jest, allegro nadal się pojawia (2 boksy)

https://screenshots.firefox.com/n1rksa75StmUR6ec/a-o.ninja
