### ISSUE TITLE
Co się stało z Francuzem?

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#7121]
Nagle przestał dodawać zgłoszenia.

**Comment by hawkeye116477** [comment]
@krystian3w A był tu jakiś francuz? Pierwsze słyszę.

**Comment by KonoromiHimaries** [comment]
@krystian3w zapewne masz na myśli wowude
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/770#issuecomment-381996018

**Comment by xxcriticxx** [comment]
@krystian3w tesknisz?

z tego co wiem dostal banna od @MajkiIT
