### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by ads-eater** [MajkiIT/polish-ads-filter#7128]
### Zrzut ekranu

<img width="519" alt="wp" src="https://user-images.githubusercontent.com/38489173/38936584-632e375c-4321-11e8-9d26-db6279b85c44.png">

### Link bezpośredni

https://wp.pl
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
Wystarczy wejść na str główną

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome
**Rozszerzenia i skrypty:**
Adblock (v. 3.10.0)
**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. EasyList
1.   EasyPrivacy
1.    Fanboy's Annoyances
1.   ochrona przed kopaniem
1.    ochrona przez malware

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by MajkiIT** [comment]
Na ADB nie ma rozwiązania. Jest za ułomny.

**Comment by KonoromiHimaries** [comment]
możesz zgłosić błąd tutaj https://help.getadblock.com/support/tickets/new

**Comment by MajkiIT** [comment]
@KonoromiHimaries ja już 3 tydzień o naprawę błędów w w ich liście antykoparkowej.

**Comment by hawkeye116477** [comment]
@MajkiIT A oni mają własną listę koparkową? O ile dobrze kojarzę, to lista koparkowa należy do `https://github.com/hoshsadiq`, a on chyba nie należy do AdBlock Team.

**Comment by MajkiIT** [comment]
@hawkeye116477 oni zrobili swoją ... kupa błędów ... ukrywają co popadnie.

**Comment by krystian3w** [comment]
Się poddali i zmienili na `hoshsadiq` bo w wersji `3.11.0` (FX), `3.28.0` (Chrome) nie ma na liście.

https://cdn.adblockcdn.com/filters/nominers.txt

```
![Adblock Plus 2.0]
! Title: Cryptocurrency (Bitcoin) Mining Protection List
! Last update: 2018-20-02
! Last modified: 2018-20-02
! Please report any problems
! in the forums (https://help.getadblock.com/support/home)
!
! Redirect: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
```

**Comment by HateAds** [comment]
Wycięło newsy na głównej. Też tak macie ?
![1](https://user-images.githubusercontent.com/29756590/40079190-4720a7c2-5887-11e8-8827-62d7d729e8e0.png)

**Comment by HateAds** [comment]
@MajkiIT Dzięki.
