### ISSUE TITLE
1,756 used out of 1,768

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#713]
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it): 1,756 used out of 1,768 purge cache

wszystkich filtrow nie uzywa?

**Comment by MajkiIT** [comment]
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it): użytych 1 768 z 1 768 

zaraz po aktualizacji tak jest jak u ciebie.
