### ISSUE TITLE
pssite.com zmienili na neosite.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#7140]
Pewnie trzeba podmienić reguły, gdyż pssite.com zmienili na neosite.pl i oczywiście pojawiły się resztki po reklamach, Sociale i inne elementy.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/ba37476f33f6938bdb264e4d9a7cec74b96653a8/polish-adblock-filters/adblock.txt#L2410

https://github.com/MajkiIT/polish-ads-filter/blob/ba37476f33f6938bdb264e4d9a7cec74b96653a8/polish-adblock-filters/adblock.txt#L3322

---

https://github.com/MajkiIT/polish-ads-filter/blob/6f52e2c984d859e8e4d0d1c0329d5e40968643a7/adblock_social_filters/adblock_social_list.txt#L1890
https://github.com/MajkiIT/polish-ads-filter/blob/6f52e2c984d859e8e4d0d1c0329d5e40968643a7/adblock_social_filters/adblock_social_list.txt#L1891
