### ISSUE TITLE
matzoo.pl

### ISSUE THREAD

**Issue by bruno300** [MajkiIT/polish-ads-filter#7156]
Anty-adblock + reklama ("strefa bez reklam")

### Zrzut ekranu

1
![capture_060_20042018_135910](https://user-images.githubusercontent.com/38558520/39049836-58dedc6a-44a3-11e8-8f98-52ed54a8c05b.png)

2
![capture_061_20042018_135918](https://user-images.githubusercontent.com/38558520/39049837-5908ba12-44a3-11e8-8457-60aacf7d2375.png)

3
![capture_062_20042018_140111](https://user-images.githubusercontent.com/38558520/39049838-5936cd6c-44a3-11e8-88ec-98bf9a26926b.png)

### Link bezpośredni

1 http://matzoo.pl/lamiglowki/edytor-tekstu-tinymce_68_490
2 http://matzoo.pl
3 http://matzoo.pl/strefa-bez-reklam

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na stronę
2. 

### Moja konfiguracja: 
FF 59.0.2 [64bit] & uBO 1.15.25rc3 & ND 13.48

**Filtry:**

<details>
  <summary>Szczegóły</summary>

**(Nano Defender filtry:)**

1. Nano Defender filter
2. Nano Base filter
3. Nano Whitelist filter

**(uBlock filtry:)**

4. uBlock filters
5. uBlock filters – Annoyances
6. uBlock filters – Badware risks
7. uBlock filters – Privacy
8. uBlock filters – Resource abuse​​​​​
9. uBlock filters – Unbreak

**(Adguard filtry:)**

10. Adguard’s Annoyance List
11. Adguard Base Filters
12. Adguard Spyware Filters
13. Adblock & uBlock polish filter - AdGuard supplement

**(Adblock filtry:)**

14. Adblock Warning Removal List
15. EasyList
16. EasyList Polish
17. EasyPrivacy

**(Fanboy’s filtry:)**

18. Fanboy’s Annoyance List
19. Fanboy’s Anti-Thirdparty Social (see warning inside list)
20. Fanboy’s Cookiemonster List
21. Fanboy’s Enhanced Tracking List
22. Fanboy's Polish

**(Ad and tracking filtry:)**

23. hpHosts’ Ad and tracking servers
24. Peter Lowe’s Ad and tracking server list

**(Ciastka filtry)**

25. I'm OK with cookies​
26. Block-EU-Cookie-Shit-List​
27. Prebake - Filter Obtrusive Cookie Notices
28. I don't care about cookies

**(Polskie filtry)**

29. POL: polskie filtry do Adblocka i uBlocka
30. Polish Privacy Filters
31. Polskie Filtry Anty-Donacyjne
32. Polskie Filtry Ciasteczkowe​
33. Polskie Filtry Elementów Irytujących
34. Polskie Filtry RSS​
35. Polskie Filtry Społecznościowe​
36. Polskie Filtry Wewnętrzne
37. AlleBlock​
38. KAD - Przekręty

</details>

**Comment by krystian3w** [comment]
`##.log_form`

anty - adblock :left_right_arrow:  wywalić Fanboy Polish, nikt nie łata, brak wsparcia.

```
[Adblock Plus 1.1]
! Checksum: 8FSssJU3mAwFGX/drd9wFQ
! Title: Fanboy's Polish
! Updated: 19 Feb 2017
! License: http://creativecommons.org/licenses/by/3.0/
! Homepage: http://www.fanboy.co.nz/
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!! Officially unsupported !!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! ---------- Generic Blocking Rules ----------
```

**Comment by bruno300** [comment]
Faktycznie, po wyłączeniu Fanboy's Polish​, juz nie wyskakuje Anty-Adblock.
