### ISSUE TITLE
resinet.pl

### ISSUE THREAD

**Issue by bruno300** [MajkiIT/polish-ads-filter#7174]
Podobnie jak tu: https://github.com/MajkiIT/polish-ads-filter/issues/7164 - cała strona (główna oraz podstrony) od góry do dołu w pustych kontenerach i napisach po reklamach, 3 przykładowe zrzuty ekranu, reszta w spojlerze.

### Zrzut ekranu

1
![capture_099_20042018_184518](https://user-images.githubusercontent.com/38558520/39063480-8b66684c-44cb-11e8-8a52-bb3f21dcf3b7.png)

2
![capture_100_20042018_184523](https://user-images.githubusercontent.com/38558520/39063481-8b97c540-44cb-11e8-9b5a-7b9d06c5fa96.png)

3
![capture_101_20042018_184528](https://user-images.githubusercontent.com/38558520/39063482-8bc16a3a-44cb-11e8-83e4-e500cae5b5db.png)

### Więcej zrzutów ekranu:

<details>
  <summary>Więcej zrzutów ekranu</summary>

4
![capture_102_20042018_184530](https://user-images.githubusercontent.com/38558520/39063483-8beb1740-44cb-11e8-91b4-22b700a7938f.png)

5
![capture_103_20042018_184536](https://user-images.githubusercontent.com/38558520/39063484-8c145cd6-44cb-11e8-9072-0cfd31a06c2f.png)

</details>

### Link bezpośredni

 http://www.resinet.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na stronę
2. 

### Moja konfiguracja: 
FF 59.0.2 [64bit] & uBO 1.15.25rc3 & ND 13.48

**Filtry:**

<details>
  <summary>Szczegóły</summary>

**(Nano Defender filtry:)**

1. Nano Defender filter
2. Nano Base filter
3. Nano Whitelist filter

**(uBlock filtry:)**

4. uBlock filters
5. uBlock filters – Annoyances
6. uBlock filters – Badware risks
7. uBlock filters – Privacy
8. uBlock filters – Resource abuse​​​​​
9. uBlock filters – Unbreak

**(Adguard filtry:)**

10. Adguard’s Annoyance List
11. Adguard Base Filters
12. Adguard Spyware Filters
13. Adblock & uBlock polish filter - AdGuard supplement

**(Adblock filtry:)**

14. Adblock Warning Removal List
15. EasyList
16. EasyList Polish
17. EasyPrivacy

**(Fanboy’s filtry:)**

18. Fanboy’s Annoyance List
19. Fanboy’s Anti-Thirdparty Social (see warning inside list)
20. Fanboy’s Cookiemonster List
21. Fanboy’s Enhanced Tracking List
22. Fanboy's Polish

**(Reklamy i śledzenie filtry:)**

23. hpHosts’ Ad and tracking servers
24. Peter Lowe’s Ad and tracking server list

**(Ciastka filtry:)**

25. I'm OK with cookies​
26. Block-EU-Cookie-Shit-List​
27. Prebake - Filter Obtrusive Cookie Notices
28. I don't care about cookies

**(Polskie filtry:)**

29. POL: polskie filtry do Adblocka i uBlocka
30. Polish Privacy Filters
31. Polskie Filtry Anty-Donacyjne
32. Polskie Filtry Ciasteczkowe​
33. Polskie Filtry Elementów Irytujących
34. Polskie Filtry RSS​
35. Polskie Filtry Społecznościowe​
36. Polskie Filtry Wewnętrzne
37. AlleBlock​
38. KAD - Przekręty

</details>

**Comment by MajkiIT** [comment]
`resinet.pl##.bb`

**Comment by bruno300** [comment]
Na głównej jest ok (FF & O) ale na podstronach  jeszcze jakieś pojedyńcze zostają, przykładowo:

http://www.resinet.pl/aktualnosci/rzeszow/dyrektor-szpitala-przy-ul-lwowskiej-przedstawil-wyniki-finansowe-placowki-istnieje-koncepcja-przebudowy.html

![capture_122_20042018_193604](https://user-images.githubusercontent.com/38558520/39065593-95259ee6-44d2-11e8-8cdc-4107a8df77c9.png)
