### ISSUE TITLE
wypowiadamoc.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7243]
Wycina treść 
https://wypowiadamoc.pl/generator-wypowiedzenia
![opera zdjecie_2018-04-21_164746_wypowiadamoc pl](https://user-images.githubusercontent.com/36385327/39085518-db7c73f4-4583-11e8-9887-2ad63f8ecf45.png)

**Comment by MajkiIT** [comment]
`@@||wypowiadamoc.pl/wp-content/plugins/uk-cookie-consent/assets/js/uk-cookie-consent-js.js?ver=2.3.0$script,first-party`
