### ISSUE TITLE
olx.pl

### ISSUE THREAD

**Issue by salionPL** [MajkiIT/polish-ads-filter#7246]
# **Nie działa przycisk "Ogłoszenia użytkownika"**

### **Zrzut ekranu:**
![z1](https://user-images.githubusercontent.com/38588787/39085884-f4364252-4589-11e8-9fd4-cdd13382fafa.jpg)

### **Adres strony:** 
https://www.olx.pl/oferta/wynajem-uslugi-minikoparka-koparka-wypozyczalnia-nowy-sacz-CID619-IDsZllH.html

**Moja konfiguracja:**

Windows 10 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.16.0

**Moje listy filtrów:**
<details>

![filtry](https://user-images.githubusercontent.com/38588787/39085912-5416804c-458a-11e8-8c29-e12f47352638.jpg)
</details>

**Comment by MajkiIT** [comment]
@KonoromiHimaries @hawkeye116477 @xxcriticxx zerkniecie? U  mnie jest ok.

**Comment by salionPL** [comment]
Po wyłączeniu samych "Polskich filtrów" też działa (z włączonym uBlock filters – Privacy)

**Comment by krystian3w** [comment]
Dziwny błąd u mnie działa przy obu aktywnych listach.
