### ISSUE TITLE
komorkomania.pl

### ISSUE THREAD

**Issue by salionPL** [MajkiIT/polish-ads-filter#7247]
# **Blokowane są niektóre zdjęcia w artykule**

### **Zrzut ekranu:**
![z2](https://user-images.githubusercontent.com/38588787/39086352-5d942bf0-4590-11e8-8dd7-c3c02736db04.jpg)

### **Adres strony:** 
https://komorkomania.pl/35420,storyboard-selfissimo-scrubbies-aplikacje-fotograficzne-google

**Moja konfiguracja:**

Windows 10 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.16.0

**Moje listy filtrów:**
<details>

![filtry](https://user-images.githubusercontent.com/38588787/39085912-5416804c-458a-11e8-8c29-e12f47352638.jpg)
</details>

**Comment by krystian3w** [comment]
Winny: `[class^="insert insert-"]` - ale to blokuje też prawą kolumnę i "zobacz również".

**Comment by MajkiIT** [comment]
@krystian3w dziękuję
