### ISSUE TITLE
@MajkiIT zbanował @bruno300

### ISSUE THREAD

**Issue by bruno302** [MajkiIT/polish-ads-filter#7258]
@MajkiIT pochwal się innym, że przed chwilą zbanowałeś mi konto @bruno300, nie bądź psycholem i przestań banować nicki, ktore tu tylko pomagają czyli zgłaszają reklamy i błędy, daj spokój o co ci chodzi...przywróć mi mój nick, jeśli mam nie zgłaszać za dużo na raz to nie będę, wystarczy dać znać.

**Comment by xxcriticxx** [comment]
@MajkiIT nowy fan club?

**Comment by krystian3w** [comment]
A mnie gorhill w uBlocku.

**Comment by xxcriticxx** [comment]
@krystian3w gratuluje sukcesu

**Comment by bruno302** [comment]
> @krystian3w : A mnie gorhill w uBlocku.

Masz rację, goryl to też psychol taki sam jak MajkiIT, w ogóle większość adminów w internecie to psychole / prostytutki, którzy bezkarnie nadużywają funkcji administracyjnych: (zablokuj wątek / zbanuj / skasuj / przenieś / zmień nazwę), i dziwnym zbiegiem okoliczności nigdy nie banują swoich kolegów nawet gdy udowodnisz takiemu winę, czyli niekonsekwencja, podwójne standardy, kolesiostwo, hipokryzja. Już dawno zauważyłem, że w internecie nie liczy się racja i argumenty, a jedynie układy i znajomości, a modzi i admini to zwykłe prostytutki. A zwłaszcza GitHub jest miejscem, które sprzyja takiej prostytucji, bo bany są po cichutku, nie ma nic o tym, kto, kogo, za co, kiedy i na ile, a gdy dostaniesz od administracji GitHuba to całkowicie wyparowujesz, znika twój profil, repozytoria, wątki, komentarze, wszystko, nie ważne, że siedziałeś tam 5 czy 10 lat.

@MajkiIT pochwal się innym, że przed chwilą zbanowałeś mi kolejne konto `@bruno304`, stalinizm w czystej postaci.

**Comment by MajkiIT** [comment]
@bruno302 nie mam zamiaru z tobą dyskutować.

**Comment by bruno305** [comment]
@MajkiIT 

1 Bo nie umiesz uzasadnić banów i udzielić prostej odpowiedzi co ci zrobiły nicki bruno, więc rzucasz jakimś zbywającym wykrętem/wymówką, odpowiem za ciebie - nic ci nie zrobiły. 

2 Ja też nie mam zamiaru ani ochoty z tobą dyskutować, ale sam rozpocząłeś tę dyskusję swoimi banami.

3 Nawet gdyby próbować z tobą dyskutować to nie ma to sensu, ty nie potrafisz dyskutować, tylko co najwyżej trolować.

Jeszcze raz powtarzam w internecie dostaje się bany nie w oparciu o sprawiedliwość, prawdę, rację czy argumenty tylko w oparciu o układy, kolesiostwo i prywatne widzi mi się admina-cebuli, który w tym przypadku na pytanie za co te bany - zbywa i nie umie udzielić odpowiedzi, to jest właśnie internetowa sprawiedliwość.
