### ISSUE TITLE
@MajkiiIT zbanował @bruuno300

### ISSUE THREAD

**Issue by bruno304** [MajkiIT/polish-ads-filter#7268]
@MajkiIT pochwal się innym, że przed chwilą zbanowałeś mi konto `https://github.com/bruno300`, nie bądź psycholem i przestań banować nicki, które tu tylko pomagają czyli zgłaszają reklamy i błędy, daj spokój o co ci chodzi...przywróć mi mój nick, jeśli mam nie zgłaszać za dużo na raz to nie będę, wystarczy dać znać.

**Comment by krystian3w** [comment]
A mnie gorhill w uBlocku.
