### ISSUE TITLE
regexa @ wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#727]
podaj mi info to przetestuje

**Comment by MajkiIT** [comment]
dodaj te filtry https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/dev/polish-adblock-filters/wp_regex.txt

**Comment by xxcriticxx** [comment]
tego nie blokuje to jest hyba ztej exception ze wczoraj wyjątek rodzinnawycieczka.wp.pl/ na main page sa te niektore reklamy 

tego nie blokuje 

https://f.shoplov.in/r/0cb0462e-40bb-4e4d-a6cf-0f7fde4a0612,30c3bf83-e199-4b2a-9e29-51d283bb8e08?r=http%3A%2F%2Fdot.wp.pl%2Fredir%3FSN%3Dshoplov%26url%3Dhttps%253A%252F%252Fwww.eobuwie.com.pl%252Fpolbuty-menbur-004345-ivory-marfil-004.html%253Futm_campaign%253Dteleshow6p%252520-%252520suknie%252520%2525C5%25259Blubne%252520eobuwie%2526utm_medium%253Dteleshow.wp.pl%2526utm_source%253Dserwisy_WP
