### ISSUE TITLE
kartaskup.pl

### ISSUE THREAD

**Issue by bruno304** [MajkiIT/polish-ads-filter#7274]
Otwieram ponownie bo https://github.com/MajkiIT/polish-ads-filter/issues/7173 nienaprawione.

**Comment by krystian3w** [comment]
chyba nie ma szans na blokowanie tych reklam home.pl dla nieopłaconych domen / usług.

Ogólna reguła wygląda, że a dodatkowo by trzeba było śledzić czy strona wróciła.

**Comment by MajkiIT** [comment]
@krystian3w no niestety trudno to łapać. Jak sam widzisz.

**Comment by krystian3w** [comment]
Ja bym to zamknął, taka strona raczej nie istniała, ale jest `www.kartaskup.pl`.
