### ISSUE TITLE
bestcena.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7275]
Po dodaniu do kosza np. https://bestcena.pl/smartfony-i-telefony/huawei-p20-lite-64gb-dual-sim-czarny następnie po kliknięciu "Dalej" nie pojawia się formularz do wypełnienia.

![opera zdjecie_2018-04-21_203858_bestcena pl](https://user-images.githubusercontent.com/36385327/39087668-a58e3892-45a4-11e8-8acd-44edd8b9ea5c.png)

**Comment by MajkiIT** [comment]
`#@#:not(input)[id*="cookie"]`

**Comment by krystian3w** [comment]
Dokładnie.

**Comment by MajkiIT** [comment]
@xMaap u mnie jest ok. 
@krystian3w zerkniesz?

**Comment by krystian3w** [comment]
U mnie się ładują:

> ![obraz](https://user-images.githubusercontent.com/35370833/39088726-6bc37d3a-45b7-11e8-8bcf-9a32b07f1c02.png) |
> --- |

**Comment by xMaap** [comment]
Dobra widzę, ze to przez "Adguard’s Annoyance List".

**Comment by MajkiIT** [comment]
@F4z może wyjątek?

**Comment by krystian3w** [comment]
```
@@||bestcena.pl/includes/templates/mozen%20temp/jscript/jscript_8_jquery.cookiebar.js$script,first-party
```

Ale jak to ma się, ze składnią Adguard to nie wiem.
