### ISSUE TITLE
minecraft-list.pl

### ISSUE THREAD

**Issue by RikoDEV** [MajkiIT/polish-ads-filter#7298]
### Zrzut ekranu
![screenshot-2018-4-22 lista serwerow minecraft spis serwerow minecraft prywatne serwery minecraft serwery minecraft - lis](https://user-images.githubusercontent.com/18230443/39095271-0cf90130-463e-11e8-8891-7ddb242dd4ce.png)

Reklamy

### Link bezpośredni
http://www.minecraft-list.pl/

### Moja konfiguracja
**Przeglądarka internetowa:** Firefox 61

**Rozszerzenia i skrypty:**

- uBlock Origin v1.16.1rc1

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka

**Comment by krystian3w** [comment]
`##.smutnazabajpg_container.transparent_container`
