### ISSUE TITLE
fili.cc

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#7300]
URL: https://fili.cc/serial/zywe-trupy/s08e16/wrath/34811
Blocker: uBlock Origin 1.16.0
Przeglądarka: Chrome Stable x86_64 @ Manjaro Linux
```
Filtry sieciowe: 101 710 + filtry kosmetyczne: 113 489 z:
>>> Wbudowane (6/7)
uBlock filters​​​​​ użytych 5 218 z 5 219​​​​
uBlock filters – Annoyances​​​​​ użytych 103 z 103​​​​
uBlock filters – Badware risks​​​​​ użytych 11 z 11​​​​
uBlock filters – Privacy​​​​​ użytych 65 z 66​​​​
uBlock filters – Resource abuse​​​​​ użytych 249 z 251​​​​
uBlock filters – Unbreak​​​​​ użytych 357 z 357​​​​
>>> Reklamy (2/4)
Adguard Base Filters​​​​​ użytych 15 397 z 16 193​​​​
EasyList​​​​​ użytych 80 663 z 80 810​​​​
>>> Prywatność (3/3)
Adguard Spyware Filters​​​​​ użytych 2 489 z 6 272​​​​
EasyPrivacy​​​​​ użytych 14 627 z 14 773​​​​
Fanboy’s Enhanced Tracking List​​​​​ użytych 2 342 z 2 373​​​​
Domeny ze złośliwym oprogramowaniem (3/4)
Malvertising filter list by Disconnect​​​​​ użytych 2 807 z 4 089​​​​
Malware domains​​​​​ użytych 20 525 z 20 541​​​​
Spam404​​​​​ użytych 6 534 z 6 534​​​​
>>> Elementy irytujące (2/5)
Adguard’s Annoyance List​​​​​ użytych 9 653 z 11 494​​​​
Fanboy’s Annoyance List​​​​​ użytych 36 757 z 36 786​​​​
>>> Wielofunkcyjne (0/4)
>>> Regiony, języki (1/36)
POL: polskie filtry do Adblocka i uBlocka​​​​​ użytych 5 225 z 5 288​​​​
>>> Własne (7/7)
AlleBlock​​​​​ użytych 434 z 448​​​​
I don't care about cookies​​​​​ użytych 11 263 z 12 059​​​​
Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for uBlock​​​​​ użytych 0 z 181​​​​
Polskie Filtry Ciasteczkowe​​​​​ użytych 1 524 z 1 576​​​​
Polskie Filtry Ciasteczkowe - uzupełnienie do uBlocka i AdGuarda​​​​​ użytych 0 z 42​​​​
Polskie Filtry Społecznościowe​​​​​ użytych 2 299 z 2 303​​​​
Polskie Filtry Społecznościowe - Uzupełnienie do uBlocka i AdGuarda​​​​​ użytych 0 z 18​​​​
```

Błąd: 
Popup po kliknięciu **oglądaj** na dowolnym streamie:
![screenshot_20180422_204957](https://user-images.githubusercontent.com/9846948/39098676-bf4f80e0-466e-11e8-8880-bca2f3518b4d.png)

Bez dodania `||fboost.pl^` pojawiał się na mały popup - blank page. 

Podczas oglądania dowolnego streama podczas bezczynności użytkownika obciążenie CPU skakało do około 70% CPU - zamknięcie strony eliminowało obciążenie CPU.

**Comment by MajkiIT** [comment]
@FadeMind jakiś konkretny player ?

**Comment by FadeMind** [comment]
Dowolny z dostępnych w danym momencie na stronie.

**Comment by MajkiIT** [comment]
@FadeMind a takie coś jest blokowane ?
`//so1.fili.cc:2083/`

**Comment by FadeMind** [comment]
Nie, ale dodam i sprawdzę ;)

**Comment by MajkiIT** [comment]
`/:\/\/[\w\W]{5,15}\.[a-z]{2,3}:[0-9]{3,4}\//$domain=fili.cc`

**Comment by FadeMind** [comment]
> `/:\/\/[\w\W]{5,15}\.[a-z]{2,3}:[0-9]{3,4}\//$domain=fili.cc` <br/>

Popup nadal się pojawia i znika po chwili...

**Comment by MajkiIT** [comment]
@FadeMind niestety nie mogę tego odwzorować. 
@KonoromiHimaries @hawkeye116477 zerkniecie u siebie ?

**Comment by MajkiIT** [comment]
@FadeMind nadal masz z tym problem ?

**Comment by FadeMind** [comment]
@MajkiIT  na fili cc nic się nie zmieniło, nadal mam z tym problem.

**Comment by MajkiIT** [comment]
@F4z masz może to samo ?

**Comment by MajkiIT** [comment]
@FadeMind blokujesz coś za pomocą hosts ?

**Comment by FadeMind** [comment]
Plik hosts mam domyślny. Nic przez niego nie blokuję.

**Comment by xxcriticxx** [comment]
@MajkiIT 

main
![capture](https://user-images.githubusercontent.com/15007183/39382239-da4813d6-4a32-11e8-9435-a1c08f2c48de.PNG)
 
test link:
https://fili.cc/serial/riverdale/s01e01/rozdzial-pierwszy-brzeg-rzeki/8400
![capture1](https://user-images.githubusercontent.com/15007183/39382256-e9eaf1a0-4a32-11e8-9599-02db57bfa82b.PNG)

**Comment by FadeMind** [comment]
@MajkiIT domeny fili trafiły na **CoinBlockerList** 

https://github.com/ZeroDot1/CoinBlockerLists/blob/master/hosts_browser#L413
