### ISSUE TITLE
MS Edge + UBO - problem z filtrem Cookies.

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#7302]
Tak jak w temacie. Filtr nie chce pobierać zawartości. Błąd 211731. Czy możecie coś zaradzić?

**Comment by hawkeye116477** [comment]
@seba2282 Tak, zainstalować Nano Adblocker. uBO na Edge jest słabo rozwijany.

**Comment by seba2282** [comment]
I przy Nano Adblockerze na wszystkich filtrach patrzeć na reklamy redcdn w playerach TVN-u? To dziękuję. To przepuszcza jak sito.

**Comment by hawkeye116477** [comment]
@seba2282 A to ciekawe, bo u mnie Nano blokuje te reklamy. Cześć redcdn musi przepuścić oczywiście, bo są wyjątki. 
![screenshot_20180423_092507](https://user-images.githubusercontent.com/19818572/39112262-3ec26374-46d8-11e8-8c07-31b77d24ce2b.png)
Może to tylko taka przypadłość wersji na Edge z tymi reklamami, A jeżeli tak, to zawsze można to zgłosić => https://github.com/NanoAdblocker/NanoCore/issues, pingwin może prędzej naprawi niż ten gość, co na niego się ostatnio skarżyli. A uBlock Edge też nie wszystko blokuje jak widać => https://github.com/nikrolls/uBlock-Edge/issues/60 :smile:.

**Comment by seba2282** [comment]
To widocznie już ekipa dodała te reguły, co dostałem w zgłoszeniu o niemożliwości odtwarzania filmów z playerów TVN-u przy obecności Adguarda. :) Bo ze swoimi wbudowanymi filtrami Nano jest cieniutki. To UBO więcej blokuje z wbudowanymi fitrami. :)

**Comment by seba2282** [comment]
A jednak na Firefox Android UBO przepuszcza znowu. 
https://www.miniminiplus.pl/filmy/pokaz/my-little-pony-duchy

**Comment by hawkeye116477** [comment]
@seba2282 To EasyList blokuje ten redcdn. A tak w ogóle to Nano ma przecież również filtry uBlocka. U mnie Nano świetne się sprawuje, nie wiem czemu taki czarny PR mu robisz :stuck_out_tongue:  Może na Edge coś tam nie blokuje, ale uBO też miewa problemy jak widać po zgłoszeniach/skargach. Zawsze możesz zgłaszać też do Nano problemy, moze tam szybciej zareagują, kto wie :smile:.
`https://github.com/gorhill/uBlock/issues/3465`

**Comment by seba2282** [comment]
Zgłaszam problem z tym redcdn zwłaszcza na Firefox Android i x czasu nadal się te śmieci pokazują. A jakoś Adguard je wycina, a UBO i Nano je przepuszczają. Wróć... Chciałem pobrać nano na ff android, ale nie widzę go jakoś teraz... Czyżby twórca sobie odpuścił całkiem FF ?

**Comment by krystian3w** [comment]
Wrzuć może jakąś listę z adguarda np. bazową angielską albo polską, może nagle problem zniknie?

https://kb.adguard.com/en/general/adguard-ad-filters#english
https://kb.adguard.com/en/general/adguard-ad-filters#polish-ads

W najgorszym wypadku będziesz musiał np. wyłączyć domyślną polską czy EasyList i bazować na Adugardowych.

> Błąd 211731. Czy możecie coś zaradzić?

`https://raw.github.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt` - może bez "`usercontent`" będzie dało radę pobierać.

**Comment by krystian3w** [comment]
> Zgłaszam problem z tym redcdn zwłaszcza na Firefox Android i x czasu nadal się te śmieci pokazują.

Wrzuć może jakąś listę z adguarda np. bazową angielską albo polską, może nagle problem zniknie?

https://kb.adguard.com/en/general/adguard-ad-filters#english
https://kb.adguard.com/en/general/adguard-ad-filters#polish-ads

W najgorszym wypadku będziesz musiał np. wyłączyć domyślną polską czy EasyList i bazować na Adugardowych.


---

> Chciałem pobrać nano na ff android, ale nie widzę go jakoś teraz... Czyżby twórca sobie odpuścił całkiem FF 

No usunął / wyłączył / zbanowała go Mozilla.

W przyszłości tak może być np. nie podoba mu się `userCSS`, możliwe że przez to nie wróci. Dodatkowo pisał że nie używa Firefox co może mu utrudniać na bieżąco testowanie.


> Błąd 211731. Czy możecie coś zaradzić?

```
https://raw.github.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt
```

 \- może bez "`usercontent`" będzie dało radę pobierać.

**Comment by seba2282** [comment]
Chwilowo zaraportowałem twórcy ubo dla Edge (zarówno polskie cookies, jak i norskie filters) i wymieniłem z UBO na AG.

**Comment by krystian3w** [comment]
Dobrze.

**Comment by seba2282** [comment]
Chodzi na razie wymieniłem rozszerzenia (ubo->adguard) tymczasowo (jeżeli napisałem niezrozumiałe) i problemy z filtrami zgłosiłem do twórcy ubo Edge.

**Comment by hawkeye116477** [comment]
@seba2282 @krystian3w 
> Edge version is ready for release, when it is officially released, the Firefox version will be dropped

Czyli już nie będzie wersji na FF, trochę lipa, bo ja korzystam z Waterfoksa i Nano mi się spodobał. Będzie tylko na Chrome i Edge.
Ale najnowsza wersja  na FF jest nadal tu => `https://github.com/NanoAdblocker/NanoCore/releases`.

**Comment by seba2282** [comment]
A jak z tym Nano Defender? Też będzie na Edge? Czy to jest Nano combo dla Edge (zintegrowany Defender w Adblocker)?

**Comment by hawkeye116477** [comment]
@seba2282 Nano Defender też będzie.
No i ważna wiadomość dla ciebie:

> The Edge builds are still experimental, please report problems you encounter, even minor ones! We ca not fix bugs that we are not aware of!

Czyli buildy na Edge nadal są eksperymentalne i trzeba zgłaszać problemy (`https://github.com/NanoAdblocker/NanoCore/issues`), które napotkasz, nawet te drobne. Pingwin nie może naprawić błędu, o którym on nie wie :smile:
Najnowsza wersja ND na Edge => https://github.com/NanoAdblocker/NanoCore/releases/download/v1.0.0.29.2/Nano_Edge_Defender.zip

. Na razie instrukcja instalacji taka => `https://github.com/NanoAdblocker/NanoCore/blob/master/notes/install-in-edge.MD#install-in-edge`

**Comment by seba2282** [comment]
To poczekamy i zobaczymy, jak zadebiutują official releases MS Store. I popatrzę na opinie ludzi. Chwilowo zostaję na AG. :)

**Comment by hawkeye116477** [comment]
@seba2282 Nie wiem, nie korzystam z Edge, wolę raczej Waterfoksa i Vivaldiego oraz Linuksa, na którym nawet nie ma Edge, Windy czasem też używam, ale siódemki tylko, w przypadku nowszych brak wsparcia od MSI. Chyba jesteś u nas jedynym fanem Edge'a :smiley:

**Comment by hawkeye116477** [comment]
> W przyszłości tak może być np. nie podoba mu się userCSS, możliwe że przez to nie wróci. 
@krystian3w Ten userCSS psuje whitelisty, dlatego pingwin go wyłączył.

**Comment by seba2282** [comment]
@MajkiIT, @hawkeye116477, @krystian3w Czy w NanoAdblocker dla Edge działa już te ukrywanie ip na webrt (jedna z trzech opcji nieaktywnych w UBO dla Edge)?

**Comment by hawkeye116477** [comment]
@seba2282 Ja nie mam Edge ani W10, mam tylko Windows 7 i Manjaro Linux Hakoila KDE Plasma, więc nie wiem. Ale na pewno Nano dla Edge jest lepszy niż uBO, zwłaszcza, że Nik Rolls rzadko robi updaty dla uBO i jak już robi to głównie merge od gorhilla. No i tak w ogóle to w przypadku rozszerzeń dla Edge, trzeba czekać tygodniami na update w MS Store, tak mówi pingwin :smile:.

**Comment by seba2282** [comment]
Czyli to samo czeka Nano - rzadkie update.

**Comment by hawkeye116477** [comment]
@seba2282 Do uBO na pewno rzadziej będzie update, a w przypadku Nano, to pewnie możesz też z GH załadować aktualizację, bo aktualizacje generalnie będą często, tylko że do MS Store będą sporo później trafiały niestety, ale to już taka polityka MS jest :smile:.

**Comment by seba2282** [comment]
A masz może link pobrania Nano Defender? bo ten z plików Pingwina mi krzyczy błąd w jakimś assents podczas załadowywania.

**Comment by hawkeye116477** [comment]
@seba2282 Taki jedynie jest => `https://github.com/NanoAdblocker/NanoCore/releases/download/v1.0.0.29.2/Nano_Edge_Defender.zip`, w sklepie MS jeszcze nie ma, pingwin mówi, że nie jest jeszcze do końca gotowy i nadal nad nim pracuje.

**Comment by seba2282** [comment]
"Błąd analizy manifestu : nieprawidłowo sformatowany lub brak pliku manifestu" 

Ot instalacja z opcjami developer w Edge.

**Comment by krystian3w** [comment]
Może rozpakuj i wskaż `manifest.json`

**Comment by seba2282** [comment]
Sprawdzę za małą chwilę i dam znać.

**Comment by krystian3w** [comment]
To chyba zostaje zgłosić do pingwina jak bezpośrednio nano edge defender miesza...?

**Comment by seba2282** [comment]
Dodałem sobie do UBO Edge fajny filtr. Zwie się Web Annoyances UltraList. I nie widzę teraz blacklist UBO. :) A były i na Adguard i na UBO i na NanoAdblocker z i bez NanoDefender. Polecam.

**Comment by seba2282** [comment]
Ponawiam temat, gdyż dotyczy on się też nano adblocker. Jak dodam filtr cookies nano adblocker w MS EDGE, to się nie załącza. Jest adres.txt i użytych 0/0 oraz błąd aktualizacji. Problem też ma norweski filtr. Włączam go w językach i nie chce się zaktualizować. Gdzie jest problem? P.S. Te trzy opcje, gdzie jest webrtc w NANO/UBO, są wyszarzałe. Wie ktoś, czemu z MS Edge nie działają?

**Comment by hawkeye116477** [comment]
@seba2282 Pisz z tym do pingwina.

**Comment by seba2282** [comment]
A on pomoże czy zrobi tak jak ten od Ublock Origin Edge i oleje sprawę?

**Comment by hawkeye116477** [comment]
@seba2282 Jak napiszesz, to pewnie pomoże. Tak jak pisałem, ten od uBlock Edge to słabo się tym wszystkim zajmuje, rzadko coś poprawia.

**Comment by seba2282** [comment]
Pingwin stwierdził, że co do tych webrtc, to w Edge nie zadziałają te opcje: polish cookies, to ekipa @MajkiIT może coś zaradzić. 
![polish cookies](https://user-images.githubusercontent.com/16944478/40556415-d65ecbb8-604c-11e8-868f-e8c39131db4d.png)

Natomiast norske filter, to mam pisać do autora tego filtru. :)

**Comment by KonoromiHimaries** [comment]
spróbuj przez cdn
```
https://cdn.rawgit.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt
```

**Comment by seba2282** [comment]
Których? Bo chyba mam z dwa. A te irytujące uzupełnienie u mnie jest zero użytych.

**Comment by hawkeye116477** [comment]
Ale co zaradzić, jak to na innych przeglądarkach normalnie działa, może to coś u ciebie nie tak? :smile:. Ja nie wiem Edge nie mam ani W10.

**Comment by seba2282** [comment]
Mam teraz takie dodatkowe:
![polish](https://user-images.githubusercontent.com/16944478/40562783-aeb3aece-6062-11e8-8197-02ab98b9a7ac.png)

Czy to są wszystkie? Czy jakiś brakuje?

**Comment by hawkeye116477** [comment]
@seba2282 Niby wszystko, ale czy aby nie za dużo, nawet koreańskie, japońskie, ruskie... na pewno tyle potrzebujesz :smile:?

**Comment by seba2282** [comment]
Pytałem się o polish filters… Czy jakieś pominąłem?

**Comment by hawkeye116477** [comment]
@seba2282 Są niby jeszcze polskie wewnętrzne i antydonacyjne, ale nie wiem czy chcesz, czy ci potrzeba :smile:

**Comment by seba2282** [comment]
To lipa... A potrzebuje filtr, który wywali mi zgoda np. na warunki z korzystania z google...  Masz taki filtr?

**Comment by hawkeye116477** [comment]
@seba2282 Ciasteczkowe/EI powinny raczej wywalić :smile:
