### ISSUE TITLE
treningkrakow.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7330]
![opera zdjecie_2018-04-24_025126_www treningkrakow pl](https://user-images.githubusercontent.com/36385327/39160234-6bf91620-476a-11e8-91a3-a06c72685590.png)

**Comment by krystian3w** [comment]
`||www.treningkrakow.pl/files/footer_yt.png` - social

**Comment by MajkiIT** [comment]
`treningkrakow.pl##.id-2.location-0.type-10.widget`
