### ISSUE TITLE
biznesradar.pl

### ISSUE THREAD

**Issue by mpro7** [MajkiIT/polish-ads-filter#7339]
### Zrzut ekranu

![image](https://user-images.githubusercontent.com/29251288/39183026-f1624c2e-47be-11e8-9c8b-bf96ba82269c.png)

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Kliknąć na jakikolwiek link spółki giełdowej w celu pezejścia do jej szczegółow.

### Moja konfiguracja:
**Przeglądarka internetowa:**
Google Chrome Wersja 66.0.3359.117 (Oficjalna wersja) (64-bitowa)
FireFox ESR 52.7.3 (32 bity)

**Rozszerzenia i skrypty:**
uBlock Origin 1.16.0

**Filtry:**
1. https://gist.github.com/mpro7/6655acd5b7342b5fbf5883867fcf083e

**Comment by MajkiIT** [comment]
`@@/js/ads/showads.js$script,domain=www.biznesradar.pl`
