### ISSUE TITLE
epiotrkow.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#7347]
Reklamy i cookies

**Comment by xxcriticxx** [comment]
@MajkiIT @hawkeye116477 @krystian3w

dziwne cookies sa na liscie ale dalej sie pokazuja

`epiotrkow.pl##.user_politic`

![capture](https://user-images.githubusercontent.com/15007183/39274811-2ad90a0e-48b1-11e8-9dd6-28bb0e649b93.PNG)

**Comment by krystian3w** [comment]
Po wymuszeniu aktualizacji wycina mi już.

Ułomność uBlock przy szybkim cyklu wydawania listy?

**Comment by hawkeye116477** [comment]
U mnie też ok.

**Comment by MajkiIT** [comment]
@krystian3w filtry aktualizują się co 2 dni chyba.

**Comment by krystian3w** [comment]
No tak co dwa dni, najważniejsze że, to nie jakiś problem jak z autokult.pl.

**Comment by xxcriticxx** [comment]
RODO is back!

`epiotrkow.pl##.user_politic_pop` or `epiotrkow.pl##user_politic_rodo`
