### ISSUE TITLE
misterwhat.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#7359]
Ads by google np tu : https://www.misterwhat.pl/company/308230-alf-sklep-spozywczy-niewiadomska-bednarek-i-konstantynow-lodzki

![ads](https://user-images.githubusercontent.com/23176832/39239362-e3dcf582-4880-11e8-8c79-5459a775784c.png)

**Comment by MajkiIT** [comment]
`##.adsbyg`
