### ISSUE TITLE
webcamera.pl

### ISSUE THREAD

**Issue by raszpl** [MajkiIT/polish-ads-filter#7363]
Dzisiaj wprowadzili nowy antiadblock:

![clipboard01](https://user-images.githubusercontent.com/2623127/39255237-51b1303e-48ac-11e8-9d27-6bd7d857c0e5.jpg)

np http://jezioro-biale-wlodawa.webcamera.pl/

z moich eksperymentow przy uzyciu 
-ContentBlockHelper
-uBlock Origin
-Ghostery

doszedlem do obejscia poprzez :
1 odblokowanie http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
2 wylaczenie Ublock cosmetic filters dla .webcamera.pl

tragedii nie ma, bo pagead2.googlesyndication samo z siebie reklam nie laduje, tylko upycha iframe z doubleclick.net/pagead. Po whitelistowaniu pagead2.googlesyndication i wylaczeniu cosmetic filtering reklamy i tak sie nie laduja, bo doubleclick.net jest zablokowany, ale pozostaja wielkie dziury na stronie.

Grzebiac dalej  dochodze do wniosku ze moga oni po prostu wykrywac wywalajacy sie adsbygoogle.push() ?

> Uncaught G {message: "adsbygoogle.push() error: No slot size for availableWidth=0", stack: "TagError: adsbygoogle.push() error: No slot size f…syndication.com/pagead/js/adsbygoogle.js:1:70659)", name: "TagError"}

blad jest rezultatem filtru kosmetycznego usuwajacego aswift_0_expand z 

`<div class="app-align-center"> <ins class="adsbygoogle" <ins id="aswift_0_expand" ..`

wyjsciem moze byc albo wstrzykniecie stylu dla class="adsbygoogle" style="height: 0px;" albo przechwycenie adsbygoogle.push() ?

**Comment by F4z** [comment]
Bez odblokowywania `pagead2.googlesyndication.com` można na przykład w taki sposób:
`webcamera.pl##script:inject(googlesyndication.com/adsbygoogle.js)`
`webcamera.pl#@#.adsbygoogle`
`webcamera.pl##.adsbygoogle:style(height: 0px!important;)`

**Comment by MajkiIT** [comment]
@raszpl @F4z Dziękuję. Postawiłem na zgodność z ADB, aby problem zaraz nie wrócił.

**Comment by raszpl** [comment]
dostalem telefon od Mamy o 11:00 dzisiaj ze znowu nie dziala :o) 
chyba czytaja githuba bo dodali sprawdzanie obecnosci aswift_ , to zalatwia sprawe:
`webcamera.pl#@#[id^="aswift_"]`
zaczeli tez sprawdzac obecnosc obcych stylesheetow i dodanie czegokolwiek do 
`webcamera.pl##[class^="adsbygoogle"]:style(`
tez wywala popup :)
nawet 
`webcamera.pl##[class^="adsbygoogle"]:style(height: 90px !important)`
nie dziala mimo ze height jest orginalnie 90

**Comment by raszpl** [comment]
pogrzebalem troche, sprawdzaja czy kazdy `aswift_ `i `adsbygoogle` ma odpowiednia wielkosc, wiec trzeba grzebnac glebiej/plyciej

```
webcamera.pl#@#[id^="aswift_"]
webcamera.pl##.a-wrap:style(display:block !important; height: 0px !important;)
webcamera.pl##.ad:style(display:block !important; height: 0px !important;)
```

i zalatwione

**Comment by MajkiIT** [comment]
@raszpl poprawiłem

**Comment by raszpl** [comment]
Przepraszam, nie sciagnalem najnowszej wersji zeby sprawdzic zanim napisalem dzisiejszego posta :( Poprawiles juz w wersji 2018042602 10 godzin temu dodajac `~webcamera.pl##[id^="aswift_"]`
odblokowanie doubleklika nie jest konieczne.

**Comment by MajkiIT** [comment]
@raszpl już jest :(

**Comment by raszpl** [comment]
w miedzyczasie znalazlem https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt#L598 i wyoralem cos takiego
```
||googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=googlesyndication.com/adsbygoogle.js,domain=webcamera.pl
webcamera.pl#@#.adsbygoogle
webcamera.pl##.a-wrap
webcamera.pl##.ad,important
```

dziala, w dodatku bez szpar w miejscach gdzie mialy byc reklamy. redirect kompletnie wycina googla udajac prawdziwy skrypt. Mialem tylko problem z odpaleniem tego redirecta , na poczatku EasyList i "Peter Lowe’s Ad and tracking server list" nadrzedne blokowaly pagead albo googlesyndication. Jeszcze nie znam ublocka za dobrze i nie wiem w jaki sposob miec pewnosc ze moja regulka jest wazniejsza :(
Na moim komputerze zadzialalo od razu, zalogowalem sie zdalnie na drugi, dodatem te same reguly i EasyList bylo nadrzedne, wylaczylem i wlaczylem EasyList recznie i to naprawilo kolejnosc. Nie wiem czemu ta regulka nie dzialala z palca :( Jesli wiesz jak sobie z tym poradzic to sprawa bedzie zalatwiona.

Mozesz wtedy rowniez wykasowac:
```
~webcamera.pl##[id^="aswift_"]
@@||webcamera.pl^$generichide
@@||doubleclick.net/pagead/$subdocument,domain=webcamera.pl
```
i wykasowac webcamera z tych:
```
@@/fuckadblock.js$script,domain=shinden.pl|webcamera.pl|webcamera.live
24opole.pl,webcamera.pl#@#.ad
@@||pagead2.googlesyndication.com^$domain=dobreprogramy.pl|bolotv.pl|tapeciarnia.pl|mybank.pl|www.emag.pl|pebx.pl|pilot.wp.pl|skript.pl|webcamera.pl
```

**Comment by raszpl** [comment]
i dzisiejszy dodatek

```
||devhub.pl/count$domain=webcamera.pl
||static.webcamera.pl/ads.png$image,redirect=1x1-transparent.gif,domain=webcamera.pl

```

**Comment by raszpl** [comment]
i dzisiejsza modyfikacja 
`@@||static.webcamera.pl/ads.png$domain=webcamera.pl`
ewentualnie
`||static.webcamera.pl/ads.png$image,redirect=3x2-transparent.png,domain=webcamera.pl`

chlopaki tam ciezko pracuja, obfuscated inline skrypt + poupychane w zmodyfikowanym jQuery pod webcamera.pl/js/concatjs.js. cos w ten desen
```
var thisOption = $('<img>');
      thisOption.on(error, function() {
        buildOptions();
      });
      thisOption.on(load, function(data) {
        if (envset.indexOf(data.target.width + data.target.height) > -1) {
          buildOptions();
        }
      });
      thisOption.attr(src, '//static.webcamera.pl/ads.png');
```

**Comment by xxcriticxx** [comment]
@raszpl sie uwzieles na te kamery

**Comment by raszpl** [comment]
widze ze skapitulowales i pelne odblokowanie :(
u mnie lokalnie nadal dziala 100% wyciecie przy uzyciu

```
webcamera.pl#@#.adsbygoogle
webcamera.pl##.a-wrap
webcamera.pl##.ad,important
||googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=googlesyndication.com/adsbygoogle.js,domain=webcamera.pl
```

btw chyba im juz przeszlo, bo przestali wstrzykiwac losowe jpgi z nazwami ads/reklama

**Comment by MajkiIT** [comment]
@raszpl nie, tylko od 3 dni jest OK.
