### ISSUE TITLE
ANKIETY

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#7378]
@MajkiIT Ciągle mam te ankiety, można je dodać choćby do Polish Privacy Filters,co ?

![moz](https://user-images.githubusercontent.com/23176832/39306171-af2e443c-495f-11e8-8d1e-2cfa8299b888.jpg)

**Comment by krystian3w** [comment]
A nie są od tego KAD Przekręty?

**Comment by hawkeye116477** [comment]
@blocker999 To jest raczej do KADa, jak mówi @krystian3w

**Comment by blocker999** [comment]
Chyba macie racje, lecz można to interpretować jako wyłudzenie danych, zresztą niewiem ale itak poczekam na @MajkiIT

**Comment by MajkiIT** [comment]
@blocker999 podaj proszę link testowy.

**Comment by blocker999** [comment]
Tu masz kilka ale wątpie żeby jeszcze były online dlatego proponuje dodać same domeny.
http://competition8396.herewego5.loan/?utm_medium=NQ3aDvyuBCtafRQJPeFC66tm%2bMNW8T%2baflxP0d0AJGo%3d&t=main3

http://game9555.herewego50.loan/?utm_medium=NQ3aDvyuBCtafRQJPeFC66tm%2bMNW8T%2baflxP0d0AJGo%3d&t=main5

http://competition2696.herewego40.loan/?utm_medium=NQ3aDvyuBCtafRQJPeFC66tm%2bMNW8T%2baflxP0d0AJGo%3d&t=main4

http://competition1904.cdn-network4-server5.biz/default.aspx?u=bl3pte4&o=xbkkvzb&m=1&t=main2_desk&f=1

aha kiedyś podawałem coś do KAD-u ale link był offline i temat ucichł

https://github.com/azet12/KAD/issues/459

**Comment by xxcriticxx** [comment]
@blocker999 co dobrego wygrales?

**Comment by hawkeye116477** [comment]
Pewnie iPhone, mi też ostatnio proponowali :smiley:

**Comment by xxcriticxx** [comment]
posiadam iphona X i nie narzekam

**Comment by krystian3w** [comment]
A ja tam tylko "wirusy" klikając w reklamy w Chrome - za duży ekran i klikam częścią kciuka co nie powinna dotykać ekranu (zachciało się kupić 5,5″ smartfon).

Praktycznie w każdej blinkowej przeglądarce mobilnej działa Bitwarden ale nie w Firefox.

**Comment by krystian3w** [comment]
@blocker999  4 link "padł", a pozostałe 3 blokuje ochrona przed phishingiem Google (chyba, że masz przeglądarkę bez niej lub wyłączone na własne życzenie).

**Comment by hawkeye116477** [comment]
@xxcriticxx Ja tam generalnie wolę smartfony z zielonym robotem na pokładzie, dobrze jest mieć wybór custom romów, co kto lubi. A ten iPhone to taki drogi, a ostatnio co raz cześciej piszą o problemach z nim.

**Comment by blocker999** [comment]
@xxcriticxx Nic nie wygrałem bo niebrałem udziału

@krystian3w co proponujesz, bo ja wrzucić całe adresy serwerów by mieć spokój z tym ustrojstwem, bo tylko zabiera mi czas tzn przeglądam jakąś stronke i wyskakuje mi ankieta więc aby z powrotem wrócić do ostatniej stronki trzeba zamknąć ankiete i ponownie wybrać nową karte i wyszukać tą strone bo niema możliwości cofania.

**Comment by hawkeye116477** [comment]
Ja kiedyś ujrzałem takie podobne ankiety i one były na stronie gdzie patrzyłem rozkład jazdy autobusów, wg wujka Google - sprawka hakerów, a za parę dni już nie było ankiet, a strona normalnie działała.

**Comment by hawkeye116477** [comment]
@blocker999 Może podaj link do tej strony, na której nagle ci wyskoczyła ankieta, a nie do tej już z ankietą, to zobaczymy co da się zrobić. Choć to raczej robota dla KADa albo Spam404.
Ewentualnie skan `https://pl.malwarebytes.com/adwcleaner/`.

**Comment by blocker999** [comment]
@hawkeye116477 Niestety stron niepamientam a skan zrobie jutro i podeśle

**Comment by MajkiIT** [comment]
@blocker999 to najlepiej wrzucić do KAD. @azet12 co sądzisz ?

**Comment by hawkeye116477** [comment]
Azet już 17 dni się nie odzywa, więc chyba trochę sobie poczekamy zanim odpowie.

**Comment by blocker999** [comment]
Niby podłapałem jakiegoś wirusa a temat zamykam i poczekam w KAD na @azet12

**Comment by azet12** [comment]
Jak najbardziej blokuję te cholerstwa i możecie je do mnie zgłaszać. Najgorsze w tych stronach jest to, że szybko padają, dlatego lepiej się zająć ich źródłem.
