### ISSUE TITLE
regexa @ wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#738]
tego nie blokuje to jest hyba ztej exception ze wczoraj wyjątek rodzinnawycieczka.wp.pl/ na main page sa te niektore reklamy

tego nie blokuje

https://f.shoplov.in/r/0cb0462e-40bb-4e4d-a6cf-0f7fde4a0612,30c3bf83-e199-4b2a-9e29-51d283bb8e08?r=http%3A%2F%2Fdot.wp.pl%2Fredir%3FSN%3Dshoplov%26url%3Dhttps%253A%252F%252Fwww.eobuwie.com.pl%252Fpolbuty-menbur-004345-ivory-marfil-004.html%253Futm_campaign%253Dteleshow6p%252520-%252520suknie%252520%2525C5%25259Blubne%252520eobuwie%2526utm_medium%253Dteleshow.wp.pl%2526utm_source%253Dserwisy_WP

**Comment by MajkiIT** [comment]
gdzie ty to masz?

**Comment by xxcriticxx** [comment]
bylo gdzies w sporcie

**Comment by xxcriticxx** [comment]
http://gwiazdy.wp.pl/artykul/5985276973773953/marta-wierzbicka-zerwala-z-chlopakiem-przez-zosie-zborowska.html

adblock na filmie (http://imgur.com/DOmUHrA) + reklama domodi.pl (http://imgur.com/nvuHEEv)

**Comment by xxcriticxx** [comment]
http://wiadomosci.wp.pl/kat,1026059,title,dziejesienazywo-ONR-w-bialostockim-kosciele-Demirski-to-jakas-paranoja-powinni-byc-zdelegalizowani-bo-to-sa-po-prostu-faszysci,wid,18282560,wiadomosc.html?ticaid=116dff

adblock

**Comment by MajkiIT** [comment]
u mnie jest ok. Którą wersję filtrów masz?

**Comment by xxcriticxx** [comment]
[Adblock Plus 2.0] ! Title: Adblock & uBlock polish filters - wp regex ! polskie filtry do Adblocka i uBlocka ! Collaborators: Adam W ! Homepage: http://www.certyficate.it/ ! Last modified: 14 April 2016 ! Expires: 8 hours (update frequency) ! Version: 2016041401 ! Contact: errors@certyficate.it ! Support: https://github.com/MajkiIT/polish-ads-filter/issues ! License: https://creativecommons.org/licenses/by-nc-sa/4.0/ ! Copyright (C) 2016 Certyficate IT ! Najnowsza wersja zawsze na: http://www.certyficate.it/polski-filtr-adblock/ ! v.2016041401 aktualizacja: czw, 14 kwietnia 2016, 13:50:00

**Comment by xxcriticxx** [comment]
@MajkiIT wyloncz polskie filtry wloncz tylko regexa

**Comment by MajkiIT** [comment]
oba filtry współpracują.

**Comment by xxcriticxx** [comment]
ok myslalem ze mam polskie filtry wylonczyc kompletnie
