### ISSUE TITLE
wzory-cv.com

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#7383]
Antyadblock, ciasteczka i social.
![screenshot_20180427_120039](https://user-images.githubusercontent.com/19818572/39357255-9f7a3e0c-4a12-11e8-9f5a-8dd779fa815f.png)

Antyadblock tylko dla uBO => `wzory-cv.com##script:inject(bab-defuser.js)`

**Comment by krystian3w** [comment]
```
@@||wzory-cv.com^$generichide
wzory-cv.com##.adsbygoogle
```

```
wzory-cv.com##.gatewayContainer
```

```
wzory-cv.com##.shareStackWrapper
```

---

Ma to swoje minusy jak widać.

**Comment by hawkeye116477** [comment]
No to chyba opcja @krystian3w lepsza, będzie działać również na Adblocku i pewnie wydajniej, bo nie wstrzykuje js.

**Comment by krystian3w** [comment]
Ten bab-defuser, to chyba by wymagał aktualizacji, widziałem wersje odporną na niego.
