### ISSUE TITLE
parenting.pl & wp.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#7384]
Reklama czołgów, coś dla @raszpl :smile:
`https://parenting.pl/unikaj-jedzenia-soli-zobacz-dlaczego-wideo`
![screenshot_20180427_144946](https://user-images.githubusercontent.com/19818572/39363340-3e3e8ad6-4a2a-11e8-98ac-12f435aa8b1c.png)

**Comment by xxcriticxx** [comment]
@hawkeye116477  `||wp.pl^`

**Comment by hawkeye116477** [comment]
A na głównej wp.pl ktoś wyciął sekcję z lokalnymi newsami z miast. Powinna ona być przed sekcją sport.
