### ISSUE TITLE
zippyshare.com powiadomienie push 

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#7386]
Na chroperze ciagle wyskakuje mi push o powiadomieniach na pulpicie tak wiem to nie jest polska domena no ale wkurza to namietnie Xd

Przyklad : https://www50.zippyshare.com/v/85jZpNoS/file.html

**Comment by xxcriticxx** [comment]
@gzenio22 dla @hawkeye116477 takie sprawy teraz

**Comment by gzenio22** [comment]
wlasnie go oznaczyles wiec nie bede powielal :)

**Comment by xxcriticxx** [comment]
@gzenio22 on na pewno gdzies siedzi w barze

**Comment by hawkeye116477** [comment]
Pushe teraz tutaj => `https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues`. Potem zerknę i zobaczę co da się zrobić :smile:.

**Comment by krystian3w** [comment]
Push zniknął, plik się odtwarza, upload działa.

**Comment by MajkiIT** [comment]
@hawkeye116477 
jak coś możesz wrzucić /sw.js$script , to jest tez na ninja, YT itp.

**Comment by hawkeye116477** [comment]
Z tego co widzę, to nie są takie same skrypty, ale powiadomienia również tam bywają. Zrobię tak `/sw.js$script,domain=zippyshare.com|youtube.com|a-o.ninja` :smile:.
