### ISSUE TITLE
forum.alfaholicy.org

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7392]
http://www.forum.alfaholicy.org/159_brera_brera_spider/160588-_jest_tym_miastem_dieslem.html
![opera zdjecie_2018-04-29_151531_www forum alfaholicy org](https://user-images.githubusercontent.com/36385327/39407076-db025586-4bc0-11e8-9356-3587fd0b2c9b.png)

**Comment by krystian3w** [comment]
```
forum.alfaholicy.org##.postcontainer.postbitim.postbitlegacy:nth-of-type(2)
```

```
forum.alfaholicy.org###sidebar > li:nth-of-type(1)
```
