### ISSUE TITLE
techfresh.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#7395]
Reklamy morele.net

**Comment by seba2282** [comment]
Sprawdź regułę ||i.imgur.com/eHCiDKG.png jeżeli chodzi o ten obrazek po prawej stronie z reklamą karta kredytowa.

**Comment by seba2282** [comment]
Sprawdź następujące reguły : ||widget.morele.net i ||i.imgur.com
