### ISSUE TITLE
portal.abczdrowie.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#7405]
Tło z reklamą.
`https://portal.abczdrowie.pl/wplyw-chorob-onkologicznych-na-stan-odzywienia-pacjentow`
Może `portal.abczdrowie.pl##html>body>div>a>div`?

**Comment by krystian3w** [comment]
U mnie nie ma tła

![obraz](https://user-images.githubusercontent.com/35370833/39470648-1fdd8d04-4d3f-11e8-9404-358cf43e40af.png) |
--- |

**Comment by xMaap** [comment]
Jeszcze tutaj
https://portal.abczdrowie.pl/quiz,6246755537217153
![opera zdjecie_2018-05-01_133043_portal abczdrowie pl](https://user-images.githubusercontent.com/36385327/39471574-1d85a384-4d44-11e8-9d50-93ee77a81f31.png)

A po kliknięciu "Zamknij quiz" mam 
![opera zdjecie_2018-05-01_133343_gabbbocakeomblphkmmnoamkioajlkfo](https://user-images.githubusercontent.com/36385327/39471615-4feb6764-4d44-11e8-85cf-fafa0509a418.png)

**Comment by hawkeye116477** [comment]
`portal.abczdrowie.pl##.quiz-app__addTop`

**Comment by xMaap** [comment]
Jeszcze podczas robienia quizu + migają reklamy
![opera zdjecie_2018-05-01_141521_portal abczdrowie pl](https://user-images.githubusercontent.com/36385327/39472523-43ea5fa0-4d4a-11e8-9ede-02a4f05bcfe3.png)

Po zrobieniu
![opera zdjecie_2018-05-01_141606_portal abczdrowie pl](https://user-images.githubusercontent.com/36385327/39472535-551596e6-4d4a-11e8-9096-627e4870c6a5.png)

**Comment by MajkiIT** [comment]
@xMaap @hawkeye116477 za 10 min update i można testować.

**Comment by xMaap** [comment]
@MajkiIT chyba jest dobrze.

**Comment by hawkeye116477** [comment]
@MajkiIT Potwierdzam
