### ISSUE TITLE
pcformat.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#7407]
`https://www.pcformat.pl/News-Nowa-wersja-ALLPlayer-77-Lite,n,18517`

Linki reklamowe:

> ![obraz](https://user-images.githubusercontent.com/35370833/39470560-b7656f08-4d3e-11e8-9bd3-65bc117ad90d.png) |
> --- |

Jakiś JavaScript je generuje i są aktywne na coś podobnego do "`onClick`".

**Comment by hawkeye116477** [comment]
`||emisja.adsearch.pl/_/intext_static/*$script`

**Comment by MajkiIT** [comment]
@hawkeye116477 dziękuję
