### ISSUE TITLE
polygamia.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#7417]
![2018-05-03-predzej czy pozniej musiala powstac strona oceniajaca stopien pazernosci tworcow](https://user-images.githubusercontent.com/5884000/39579251-8d1fcbcc-4ee6-11e8-8da6-fe6059bf0fd3.png)
`http://polygamia.pl/predzej-czy-pozniej-musiala-powstac-strona-oceniajaca-stopien-pazernosci-tworcow-poszczegolnych-gier/`

uszkodzona strona

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/c05bf7f6dd6dcb2d3beb090871985baa

 uBO 1.16.2
 ND 14.4
 Chr 66.0.3359.139
</details>

**Comment by MajkiIT** [comment]
U mnie jest ok. 
@hawkeye116477 zerkniesz?

**Comment by hawkeye116477** [comment]
@MajkiIT U mnie tak samo, nawet załadowałem kopię Konoromi i jest ok.

**Comment by gzenio22** [comment]
Panowie wiem co mu nie gra zjedzcie na sam dol strony bedzie puste tlo tak jak by strona byla pusta sama strona dziala tylko to widze

**Comment by hawkeye116477** [comment]
@gzenio22 Ja tego nie mam, może to tylko na wyższych rozdzielczościach.

**Comment by gzenio22** [comment]
@hawkeye116477 1920 na 1080 

Wyzszej od cb napewno nie mam XD

**Comment by krystian3w** [comment]
Ja tam mam pasek o maksymalnej wysokości 100 px (w Firefox nie mam, po zdjęciu blokad ma około 20px).

`polygamia.pl###mainSection:style(margin-bottom: 505px !important)` - częściowo pomaga, ale i psuje przy oknie niezmaksymalizowanym, w Firefox, wersje mobilną (RWD - raczej bez możliwości wykrycia).

**Comment by gzenio22** [comment]
@hawkeye116477 o kurde :D to teraz powiedz mi czy to wina filtrow czy tak dziala strona? bo sie już pogubilem jak to strona to jak szukać przyczyn

**Comment by krystian3w** [comment]
Jak dla mnie słabi webdeveloperzy.

**Comment by MajkiIT** [comment]
A może to to ==> https://screenshots.firefox.com/igV5SjfRRGRqJI1V/polygamia.pl
