### ISSUE TITLE
tokfm.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#7423]
http://www.tokfm.pl/Tokfm/0,0.html

![screenshot_20180504_124019](https://user-images.githubusercontent.com/9846948/39624095-53829342-4f98-11e8-9216-8d6866c61163.png)

ublock Origin @ Chrome @ Manjaro Linux x86_64
Filtry:
```
Wbudowane (6/7)
uBlock filters​​​​​użytych 5 442 z 5 444​​​​
uBlock filters – Annoyances​​​​​użytych 122 z 122​​​​
uBlock filters – Badware risks​​​​​użytych 11 z 11​​​​
uBlock filters – Privacy​​​​​użytych 65 z 66​​​​
uBlock filters – Resource abuse​​​​​użytych 250 z 252​​​​
uBlock filters – Unbreak​​​​​użytych 380 z 380​​​​
Reklamy (2/4)
Adguard Base Filters​​​​​użytych 15 778 z 16 509​​​​
EasyList​​​​​użytych 81 364 z 81 467​​​​
Prywatność (2/3)
Adguard Spyware Filters​​​​​użytych 2 526 z 6 297​​​​
EasyPrivacy​​​​​użytych 14 683 z 14 813​​​​
Domeny ze złośliwym oprogramowaniem (0/4)
Elementy irytujące (1/5)
Adguard’s Annoyance List​​​​​użytych 11 715 z 11 746​​​​
Wielofunkcyjne (0/4)
Regiony, języki (1/36)
POL: polskie filtry do Adblocka i uBlocka​​​​​użytych 5 319 z 5 373​​​​
Własne (4/4)
AlleBlock​​​​​użytych 434 z 448​​​​
I don't care about cookies​​​​​użytych 11 987 z 12 059​​​​
Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for uBlock​​​​​użytych 2 z 191​​​​
```

**Comment by MajkiIT** [comment]
@FadeMind u mnie nie ma tego...
@KonoromiHimaries @xxcriticxx @hawkeye116477 zerkniecie?

**Comment by xxcriticxx** [comment]
@MajkiIT z nano no adblock

takie cos mam

![capture](https://user-images.githubusercontent.com/15007183/39624630-04bcf9d0-4f68-11e8-9f60-c2b82f81a40e.PNG)

**Comment by FadeMind** [comment]
@MajkiIT problem jest w regule
```
/advert.$domain=~advert.ae|~advert.io|~motortrader.com.my
```
z easylist, która blokuje
`http://ssl.images.audycje.tokfm.pl/prodstatic/banner/advert.js?a=tok360_03_04_2018`
Jak wyłączę easylist to strona działa poprawnie.

**Comment by krystian3w** [comment]
U mnie listy pingwina ubijają.

**Comment by hawkeye116477** [comment]
Też mam ten komunikat Adblock detect, po prostu @MajkiIT powinien dodać tą regułę z listy pingwina i będzie ok.
