### ISSUE TITLE
sferadomen.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#7425]
Reklamy ( po prawo )

**Comment by krystian3w** [comment]
`###secondary  A[target="_blank"] > img` - nie wiem czy ten nagłówek też ma wycinać - reklama aftermarketu jak i zjazdy: 

> ![image](https://user-images.githubusercontent.com/35370833/39627960-c83ce0fc-4fa7-11e8-840e-4694aed05d42.png) |
> --- |
