### ISSUE TITLE
goldenline.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#7426]
Reklama J.P.Morgan " tu : https://www.goldenline.pl/grupy/Komputery_Internet/domeny/

**Comment by krystian3w** [comment]
`###adv_rect, #adv_sidebar` - nie powodowały wykrycia AdBlock?

**Comment by MajkiIT** [comment]
@krystian3w z tego co pamiętam to nie. Dziękuję
