### ISSUE TITLE
terrarium.com.pl [Anti-Adblock]

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#7437]
https://github.com/uBlockOrigin/uAssets/issues/2177#issuecomment-386700956

**Comment by krystian3w** [comment]
<kbd>Nano Defender 14.5</kbd> ogarnia bez filtrów dla uBO / Nano Adblocker.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/7437

**Comment by krystian3w** [comment]
https://github.com/olegwukr/polish-privacy-filters/issues/30
