### ISSUE TITLE
Naekranie.pl

### ISSUE THREAD

**Issue by rogacz88** [MajkiIT/polish-ads-filter#7446]
Nie działa galeria zdjęć w artykułach, używają jakiegoś dziwnego pluginu do wordpress-a

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. 
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**

**Rozszerzenia i skrypty:**

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. 
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by kasper93** [comment]
### Do usunięcia
```
naekranie.pl##script:inject(abort-on-property-read.js, showEntryWelcomescreen)
```
### Do dodania
```
naekranie.pl##script:inject(set-constant.js, showEntryWelcomescreen, false)
naekranie.pl##div[style*='content:']
```

**Comment by MajkiIT** [comment]
@kasper93 dziękuję
