### ISSUE TITLE
mojanorwegia.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#7469]
![2018-05-06-slub na trolltundze lub przez skype a_ w norwegii to mozliwe](https://user-images.githubusercontent.com/5884000/39671736-6087e2a4-511e-11e8-9e2d-2e72c449bb32.png)
`https://www.mojanorwegia.pl/rozrywka/slub-na-trolltundze-lub-przez-skypea-w-norwegii-to-mozliwe-14366.html`

uszkodzona strona

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/c05bf7f6dd6dcb2d3beb090871985baa

 uBO 1.16.4
 ND 14.8
 Chr 66.0.3359.139
</details>

**Comment by MajkiIT** [comment]
@KonoromiHimaries to wewnętrzne.
