### ISSUE TITLE
antyradio.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#7471]
cookies

test link:
https://www.antyradio.pl/Film/Seriale/Netflix-nowosci-na-kwiecien-2018-premiery-filmow-i-seriali-21314

![capture](https://user-images.githubusercontent.com/15007183/39672617-b29e9934-50fb-11e8-8164-ed2d00aef8c4.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie ma ciastek na pustyni :smiley:
![screenshot_20180506_133517](https://user-images.githubusercontent.com/19818572/39672845-559601f0-5132-11e8-9f0b-f5472e2464ff.png)

**Comment by xxcriticxx** [comment]
@hawkeye116477 ubo sie opiernicza czy pc za wolne?

**Comment by hawkeye116477** [comment]
@xxcriticxx Stawiałbym raczej, że PC za wolne. W ogóle reguły z * są nieco wolniejsze niż normalne, bo musi znaleźć wszystko co jest przed i po napisie cookie, a nie tylko samo cookie.

**Comment by xxcriticxx** [comment]
old cpu ale dziala






```
critic@critic:~$ sudo lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 58
Model name:            Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Stepping:              9
CPU MHz:               1766.804
CPU max MHz:           3900.0000
CPU min MHz:           1600.0000
BogoMIPS:              6784.62
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb spec_ctrl retpoline kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
```

**Comment by hawkeye116477** [comment]
@xxcriticxx No to nie wiem jak to jest, a ja mam raczej słabszy.
![screenshot_20180506_140825](https://user-images.githubusercontent.com/19818572/39673141-f78856ee-5136-11e8-9a57-159c6346119d.png)
