### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#7475]
jak wylczyc, aby nie bylo komunikatow o ublock?

**Comment by MajkiIT** [comment]
ale player działa z ublock origin

**Comment by krystian3w** [comment]
Może błąd w nano defender, wyłącz na próbę jak używasz.

**Comment by lukjan32** [comment]
wylaczylem nano i nie dziala

**Comment by lukjan32** [comment]
![bez tytulu](https://user-images.githubusercontent.com/17565773/39688722-5c731e7a-51d4-11e8-86e3-3d57916429f6.jpg)

**Comment by krystian3w** [comment]
To teraz listę Nano Defender (raczej wątpię, że winna jest Adblock Warning Removal List), jakby ona blokowała to raczej będzie w miarę łatwo to poprawić bez nowej wersji Nano Defender.

Jakby jednak blokowała Adblock Warning Removal List, to może do swojej pingwin by dodał wyjątek.

Najlepiej będzie upolować regułę co blokuje, by nie było że pingwin nie może odtworzyć błędu.
