### ISSUE TITLE
ingbank.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#7479]
fyi @MajkiIT 

https://forums.lanik.us/viewtopic.php?f=64&t=40612&p=135872&hilit=.pl#p135872

**Comment by MajkiIT** [comment]
@xxcriticxx dziękuję

**Comment by xxcriticxx** [comment]
smed79 20 hours ago
Already fixed in easyprivacy 9 days ago easylist/easylist@c4c904d

**Comment by MajkiIT** [comment]
@xxcriticxx dziękuję
