### ISSUE TITLE
gazetapraca.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#7482]
FB w ogłoszeniu ( na dole ) np tu : https://gazetapraca.pl/ogl/2759113/pracownik+produkcji+form+z+tworzywa+sztucznego#miasta%20nie%20podano

**Comment by krystian3w** [comment]
`##.external_link_other` jakby gdzieś miał coś innego, to może po sprawdzaniu czy zawiera tekst (`:-abp-contains(Facebooku)`)
