### ISSUE TITLE
ikamien.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#7485]
![2018-05-07-powiat kamienski - ikamien pl kamien pomorski dziwnow wolin miedzyzdroje g](https://user-images.githubusercontent.com/5884000/39717434-8a32b262-5233-11e8-84f0-be5da6495f93.png)

pusta sekcja reklama po lewej

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/c05bf7f6dd6dcb2d3beb090871985baa

 uBO 1.16.4
 ND 14.8
 Chr 66.0.3359.139
</details>

**Comment by krystian3w** [comment]
`##div.box:nth-of-type(2)` do sprawdzenia czy może nie wycina za dużo.
