### ISSUE TITLE
traveladvisor.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#7489]
![2018-05-08-traveladvisor pl - opinie o podrozach i turystyce](https://user-images.githubusercontent.com/5884000/39762953-3473f454-52dc-11e8-9fd8-6e477b28bc3b.png)

uszkodzona strona

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/c05bf7f6dd6dcb2d3beb090871985baa

 uBO 1.16.4
 ND 14.8
 Chr 66.0.3359.139
</details>

**Comment by MajkiIT** [comment]
Jest OK. @KonoromiHimaries

**Comment by hawkeye116477** [comment]
U mnie też ok.

**Comment by yourduskquibbles** [comment]
This should be [fixed](https://github.com/yourduskquibbles/webannoyances/commit/6247dbc46f09d104d4fa8b844ce129c26916cd83), please force an update of filterlist.
