### ISSUE TITLE
bonavita.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#7496]
Resztka oraz reklamy na głównej i w artykułach

**Comment by MajkiIT** [comment]
```
bonavita.pl###undermenu
bonavita.pl##.header-slogan
```

**Comment by krystian3w** [comment]
`bonavita.pl###share-nav`

> ![image](https://user-images.githubusercontent.com/35370833/39869979-f61b029e-545f-11e8-833a-6f3a344a3150.png) |
> --- |
