### ISSUE TITLE
lecnawakacje.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#7497]
Cookies

**Comment by krystian3w** [comment]
Nie mam, widocznie wycięło: `##:not(input)[id*="cookie"]`

**Comment by hawkeye116477** [comment]
Fejsik jest, a ciastek już nie ma, turyści zjedli już wszystkie :smile:.

**Comment by blocker999** [comment]
@MajkiIT zmień etykiete na social
