### ISSUE TITLE
studentnews.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#7503]
Reklamy i cookies w witrynach: https://grupa.studentnews.pl/#studentnewspl1

**Comment by hawkeye116477** [comment]
@blocker999 Nic tam nie ma, komputer grat do wymiany :smile:.

**Comment by blocker999** [comment]
@hawkeye116477 Z chęcią bym zmienił komputer no ale za free nikt nic mi nieda więc jeszcze troche się pomęcze na tym a avasta nieużywam no ale skoro nic niema to zamykam.
