### ISSUE TITLE
Drupal sites 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#7510]
Nearly 400 Drupal sites infected with malware that secretly mines cryptocurrency

https://thenextweb.com/hardfork/2018/05/08/coinhive-malware-victimizes-another-400-websites-including-us-govt-lenovo-and-ucla/

https://pastebin.com/raw/a1TPEPfP

`||szybka.pl^`
`||vaks.pl^`

**Comment by krystian3w** [comment]
No trochę kopią, obciążenie skacze z 0 - 5% do 20 - 24% na CPU.

**Comment by MajkiIT** [comment]
@xxcriticxx Dziękuję
