### ISSUE TITLE
ubisoft.com/pl-pl/

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#7513]
nie mozna sie zalogowac na strona ubisoft.com/pl-pl/

**Comment by MajkiIT** [comment]
@hawkeye116477 
`@@||static2.cdn.ubi.com/uplay-connect/v2/live/default/js/jquery.cookie.min.js$script,domain=connect.ubi.com`

**Comment by MajkiIT** [comment]
@lukjan32 tak.

**Comment by lukjan32** [comment]
czekam :)

**Comment by hawkeye116477** [comment]
Szczęśliwcy, którzy mają Polskie Filtry Elementów Irytujących, wcześniej dostali update => `https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/748e014ec158702dc4df12841fbfdd538a3bd077` :smile:.

**Comment by krystian3w** [comment]
Wersje mobilną smakera dałoby się tam ogarnąć?

**Comment by hawkeye116477** [comment]
@krystian3w A o co konkretnie się rozchodzi? Załóż nowe zgłoszenie i podaj bardziej szczegółowe informacje, zrzut ekranu, etc.

**Comment by lukjan32** [comment]
dzieki, dziala, ciekawe na jak dlugo :(
