### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by vesterlay** [MajkiIT/polish-ads-filter#7520]
Poddaje się.. mógłby ktos pomóc?  
Patrzyłem na poprzednie posty związane z tym tematem i nic nie zadziałało.
Firefox developer edition 61.0b4 (64-bit)
Source: https://shinden.pl/external-video/51229-relife-kanketsu-hen/view/160519
ScreenShot: http://imgbox.com/4VvNXnhl
Wtyczki:

1. Ublock
2. Mining blocker
3. Nano defender 

Filtry: http://imgbox.com/n5Lgk5Bd - wszystkie zaktualizowane

**Comment by krystian3w** [comment]
Wymuś w uBO aktualizacje filtrów, nie zaszkodzi wszystkich.

**Comment by krystian3w** [comment]
<details><summary> dumanie nad problemem, czemu mi działa...  (...) </summary>

Wymuś w uBO aktualizacje filtrów, nie zaszkodzi wszystkich.
_Na oko masz za mało reguł głównych uBlock (ja mam: użytych 5 578 z **5 630**)_.


U mnie działa na Firefoksie:

> ![obraz](https://user-images.githubusercontent.com/35370833/39947879-d15ea2a2-5573-11e8-8218-e46e67ab46bb.png)

---


Problemem może być, że udostępniam Defendera raz z wstawkami dev a raz bez (14.12 i 14.17) lub Firefox 61 dev (aurora / prawie nightly).
</details>
<br>
(...) Dodatkowo ja nie używam bazy aguarda / spyware adguard list. Jak je włączyłem to i wskoczył adblock @MajkiIT  / @F4z?

**Comment by krystian3w** [comment]
Wygląda, że teraz padło nawet po dodaniu wyjątków dla uBlock.

**Comment by MajkiIT** [comment]
@vesterlay @krystian3w zaktualizujcie filtry i sprawdźcie proszę.

**Comment by krystian3w** [comment]
W sumie to u mnie działa tylko z ochroną prywatności Firefox / Disconnect.
Wyłączyłem i chyba dlatego zaczęły się problemy.
Usunięcie ładowanego skryptu raczej też pomogło https://github.com/MajkiIT/polish-ads-filter/commit/36d8a8f12f9b6c4f17c5a5484d781de290123ccb - tego "Diconnect" też nie umiał oszukać.

Co nie zmienia faktu, że pod listy adguard (bazy i na spyware) przydałaby się jakaś poprawka - na to nie pomaga "Disconnect".

Bardzo popsuta strona 📉

**Comment by vesterlay** [comment]
Zaktualizowałem filtry i jak mówiłeś wyłączyłem filtry adgurada. Zadziałało, dzięki.

**Comment by MajkiIT** [comment]
@F4z zerkniesz?

**Comment by F4z** [comment]
Poprawiłem, ale aktualizacja filtrów AdGuarda pewnie będzie za jakieś 2-3 godziny, do tego czasu możecie dodać te reguły w zakładce moje filtry:
shinden.pl#@#.ads:style(height: 0px!important; width: 0px!important; visibility: hidden!important;)
shinden.pl##.ads:style(height: 0px!important; width: 0px!important;)

Jeśli po 30 sekundach zostaną zablokowane przyciski, to możecie dodać tę regułę:
||popads.net/pop.js^$important,badfilter

**Comment by MajkiIT** [comment]
@F4z Dziękuję

**Comment by vesterlay** [comment]
Uch.. po kliku dniach znowu zaczął się pojawiać komunikat  :(
Próbowałem użyć reguł powyżej, ale bez żadnego efektu.
Filtry - http://imgbox.com/wk3WHOm8
