### ISSUE TITLE
tvgry.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7521]
https://tvgry.pl/wideo.asp?ID=7518
Ukryte ikony łapek i komentarzy
Włączony
![opera zdjecie_2018-05-11_231508_tvgry pl](https://user-images.githubusercontent.com/36385327/39947218-5d624e8c-5571-11e8-84d2-05ed0ce71a3f.png)
Wyłączony
![opera zdjecie_2018-05-11_231713_tvgry pl](https://user-images.githubusercontent.com/36385327/39947251-8a961b18-5571-11e8-88a6-23a9502548d1.png)

tvgry.pl#@#.social-16

**Comment by krystian3w** [comment]
[![obraz](https://user-images.githubusercontent.com/35370833/39667344-06f00984-50b4-11e8-9acc-7c10ba5df607.png)](http://grupazywiec.pl/wp-content/uploads/2018/04/Warka-Radler-0-alkoholu-pełen-luz.mp4)

**Comment by xMaap** [comment]
@hawkeye116477 mam nadzieje, że to nie żart.

**Comment by krystian3w** [comment]
Zobaczmy czy będzie mu się chciało - do oceny ile będzie trzeba uzupełnić lub co powiemy osobom dalej używających AdBlock / Adblock Plus (do widzenia, zalecamy migracje?).

**Comment by hawkeye116477** [comment]
Oczywiście, że to nie było na serio, nie możemy teraz powiedzieć, że wymagamy filtrów AdGuarda, a Fanboya tylko na własną odpowiedzialność, dlatego, że nasze filtry są też dla AdBlocka, a filtry AdGuarda nie są kompatybilne z AdBlockiem.

**Comment by krystian3w** [comment]
Mam nadzieje, że wyczuje ironię / sarkazm i nie będzie trzeba za 6 dni nowego zgłoszenia dla `tv-gry.pl`.
