### ISSUE TITLE
wp mobile

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#7523]
Nowość na wp mobile site na cały ekran telefonu

![aecb72c1-131a-456e-b01b-6d2d0ad8d8fb](https://user-images.githubusercontent.com/15007183/39956328-18318fae-55ac-11e8-9ace-96537a17ab45.jpeg)

**Comment by krystian3w** [comment]
Na iOS Safari chyba nie da rady...

**Comment by xxcriticxx** [comment]
maybe adguard ale nie testowalem jeszcze

**Comment by xxcriticxx** [comment]
@hawkeye116477 nigdy nie testowalem

**Comment by xxcriticxx** [comment]
@hawkeye116477 ubogie te listy filtrow w 1blocker

**Comment by hawkeye116477** [comment]
@xxcriticxx Może nowa wersja X `https://itunes.apple.com/us/app/1blocker-x/id1365531024?platform=ipad&preserveScrollPosition=true#platform/ipad` posiada więcej, ale ona jest już płatna i pewnie trochę inna od poprzedniej, piszą, że niby od nowa napisali i zrobili tak, że jest parę blockerów w jednym, dzięki czemu mogą ominąć limit 50 000 reguł, bo normalnie tyle max pozwala blokować api Content Blocker Safari.

**Comment by xxcriticxx** [comment]
@hawkeye116477 a jak zmienie browser?

**Comment by hawkeye116477** [comment]
@xxcriticxx A to nie wiem, tam generalnie wszystkie przeglądarki korzystają z tego samego silnika, bo innego zabraniają. AdBlock i Weblock z opisu wynika, że działają również z innymi przeglądarkami niż Safari, natomiast 1Blocker i AdGuard chyba tylko z Safari.

**Comment by xxcriticxx** [comment]
@hawkeye116477 iphone/safari zawsze 40 lat za murzynami

**Comment by hawkeye116477** [comment]
@xxcriticxx No właśnie, Xiaomi lepsze, co nie :smile:  ?
`https://mi-home.pl/telefony-mi/mi-mix-2-special-edition-128gb-white`

**Comment by xxcriticxx** [comment]
@hawkeye116477 tutaj albo iphone albo galaxy nic innego się nie liczy

**Comment by KonoromiHimaries** [comment]
@xxcriticxx maybe except one plus 6
https://www.oneplus.com/pl/launch-6

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie znaczy, że nie można nic innego kupić, po prostu nie trzeba podążać za tą modą :stuck_out_tongue: W EU/PL, Apple i Samsung zaliczają spadki sprzedaży, a Huawei na 3 miejscu, Xiaomi na 4 i ciągle jest wzrost sprzedaży.

**Comment by xxcriticxx** [comment]
@hawkeye116477 postaram sie przy nastepnym zakupie telefonu
