### ISSUE TITLE
przegladpiaseczynski.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#7530]
`http://www.przegladpiaseczynski.pl/aktualnosci`

 
![image](https://user-images.githubusercontent.com/35370833/39984908-fab76f68-575c-11e8-987a-703b53381e14.png) |
--- |

https://github.com/MajkiIT/polish-ads-filter/blob/c0972374b94f809663e63f6bf890a9a1ff70fd7e/polish-adblock-filters/adblock.txt#L1977

Powinno być `143` zamiast `1433`

**Comment by xxcriticxx** [comment]
@krystian3w poprawione
