### ISSUE TITLE
iszczecinek.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#7535]
![2018-05-16-iszczecinek pl _ miejski portal informacyjny](https://user-images.githubusercontent.com/5884000/40129860-accceaa0-5935-11e8-90e8-6ed7d01c041e.png)

pusta sekcja reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/c05bf7f6dd6dcb2d3beb090871985baa

 uBO 1.16.4
 ND 14.28
 Chr 66.0.3359.181
</details>

**Comment by krystian3w** [comment]
`iszczecinek.pl###Popup`, a jakby blokować tylko ten to może dodać `iszczecinek.pl#?##Popup:-abp-has(.advclick)` (tylko wtedy może dłużej wycinać).

**Comment by MajkiIT** [comment]
@krystian3w dziękuję
