### ISSUE TITLE
komorkomania.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#7540]
https://komorkomania.pl/35942,aktualizacja-oprogramowania-wady
Reklamy w playerze.
||wpimg.pl^$media,redirect=noopmp3-0.1s,domain=komorkomania.pl

**Comment by krystian3w** [comment]
`||v.wpimg.pl/$media,redirect=noopmp3-0.1s,domain=wp.pl|~www.wp.pl|autokult.pl|parenting.pl|echirurgia.pl|money.pl|o2.pl|portal.abczdrowie.pl|komorkomania.pl`

Jeszcze coś z grupy WP ma odtwarzacz?

**Comment by HateAds** [comment]
@krystian3w Będę sprawdzał i jak coś otworzę nowe issue. :grimacing:

**Comment by MajkiIT** [comment]
@krystian3w @HateAds Dziękuję
