### ISSUE TITLE
gadzetomania.pl + fotoblogia.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#7542]
https://fotoblogia.pl/12278,gorskie-wyprawy-fotograficzne-recenzja-ksiazki
https://gadzetomania.pl/60168,to-nie-tak-jak-myslisz-obalamy-4-popularne-mity-o-sztucznej-inteligencji
Tutaj na obu stronach włączony filtr ( POL: Official Polish filters for AdBlock, uBlock Origin & AdGuard ) wycina zdjęcia i odtwarzacz wp.

**Comment by MajkiIT** [comment]
@HateAds Dziękuję
