### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by vesterlay** [MajkiIT/polish-ads-filter#7544]
_W odniesieniu do  #7520_ 
Uch.. po kliku dniach znowu zaczął się pojawiać komunikat  :(
Filtry - http://imgbox.com/wk3WHOm8
Mógłby ktoś pomóc?

**Comment by krystian3w** [comment]
## Workaround

Po 3 sekundach klikać stop i strona nie zdąży podmienić przycisków, ale jak masz wolniejszy internet to możesz nie wyczuć.

**Comment by MajkiIT** [comment]
@vesterlay update i powinno być OK

**Comment by vesterlay** [comment]
Dzięki, działa.
