### ISSUE TITLE
gadzetomania.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#7545]
Reklamy w playerze.
||wpimg.pl^$media,redirect=noopmp3-0.1s,domain=gadzetomania.pl

**Comment by krystian3w** [comment]
<code>||v.wpimg.pl/$media,redirect=noopmp3-0.1s,domain=wp.pl|~www<i>.</i>wp.pl|autokult.pl|parenting.pl|echirurgia.pl|money.pl|o2.pl|portal.abczdrowie.pl|komorkomania.pl|fotoblogia.pl|<b>gadzetomania.pl</b></code>
