### ISSUE TITLE
wp.pl (wersja statyczna)

### ISSUE THREAD

**Issue by salionPL** [MajkiIT/polish-ads-filter#7547]
# **Nie działa przewijanie na stronie wp.pl w wersji statycznej (bez panelu po prawej stronie) https://www.wp.pl/static.html**

### **Adres strony:** 
https://www.wp.pl/static.html

**Moja konfiguracja:**

Windows 10 [64bit]
Firefox 60.0.1 [64bit]
uBlock Origin 1.16.6

**Moje listy filtrów:**
<details>

![filtry](https://user-images.githubusercontent.com/38588787/39085912-5416804c-458a-11e8-8c29-e12f47352638.jpg)
</details>

**Comment by krystian3w** [comment]
`wp.pl##html:style(overflow:auto!important)`

Ale i tak się nie ładuje dół strony, brak grafik i końcówka urwana jakaś:

![obraz](https://user-images.githubusercontent.com/35370833/40269648-a5d5688c-5b81-11e8-8734-837e3a2e842e.png) |
--- |

**Comment by krystian3w** [comment]
Jak przeszkadza sam panel to w uBlock można usunąć go i lukę:

```
www.wp.pl###newsfeed-player-column
www.wp.pl###section_topnews:style(padding-right:0!important;)
www.wp.pl###header.header > header:style(padding-right:0!important;)
```

**Comment by salionPL** [comment]
Super, te trzy ostatnie załatwiają sprawę z panelem i nie trzeba używać wersji statycznej. Dzięki wielkie.

**Comment by krystian3w** [comment]
"Jedną" to tylko w Stylish/Stylus - uBlock Origin/Adguard AdBlocker nie pozwalają połączyć reguł w jedną z CSS-em.

Albo eksperymentalnie po uproszczeniu do: `[id^="section_"]`

```
www.wp.pl###newsfeed-player-column
www.wp.pl###header.header > header:style(padding-right:0!important;)
www.wp.pl##div > section[id^="section_"]:style(padding-right:0!important)
```

Jakby przymulały WP to można uprościć sprawdzanie  `div#header.header > header` i `div > section[id^="section_"]`.

**Comment by salionPL** [comment]
Coś nie działa ta reguła na wyśrodkowanie.

**Comment by MajkiIT** [comment]
@hawkeye116477

**Comment by krystian3w** [comment]
Za dużo kratek zamiast szukać `<div>`-a z klasą szukało czegokolwiek z identyfikatorem `div`.

**Comment by hawkeye116477** [comment]
Ten prawy panel kiedyś tam dodawałem i potem przywróciłem, bo ktoś miał pretensje, że schowałem.

**Comment by krystian3w** [comment]
No to chyba zostaje stworzenie repozytorium `salionPL/MyAnnoyanceFilters` jak chcesz sobie "ułatwić" przenoszenie tego na nowe jednostki lub bardzo razi na liście filtrów własnych.

**Comment by krystian3w** [comment]
Mały przełom uBlock Origin 1.8.0+ od samego początku wspiera łączenie tagów z css:

```
www.wp.pl###newsfeed-player-column
www.wp.pl###header.header > header, div > section[id^="section_"]:style(padding-right:0!important;)
```

Podobnie nowsze wersje AdGuard AdBlocker, przy czym wersja dla chrome nie umie nadpisywać `!important`.

**Comment by xxcriticxx** [comment]
@krystian3w jakas dziwan ta ver. nie czasem ma byc 1.18.0?

**Comment by krystian3w** [comment]
Chodzi o wersje z 2016 jak dodali wsparcie CSS (i nowsze).

Zdziwiłem się jak Gorhill dodał regułę odblokwując scroll jako jedną a zablokowano na dwóch elementach html (`<html>` oraz `<body>`).

- https://addons.mozilla.org/pl/firefox/addon/ublock-origin/versions/1.8.0 - specjalnie zainstalowałem Firefox 52 ESR Portable.
- https://crx.dam.io/source/crxviewer.html?crx=https://crx.dam.io/files/cjpalhdlnbpafiamejdnhcphjbkeiagm/1.8.0.zip > **CRX**  (jakby ktoś chciał próbować na Chromium o ile ruszy).

**Comment by krystian3w** [comment]
Trzeba by odblokować scroll na `<html>`

**Comment by krystian3w** [comment]
W sumie to mam tylko w trybie prywatnym, wciąż strona statyczna wygląda na porzuconą / mniej ważną.

```
||www.wp.pl/static.html$inline-script,domain=www.wp.pl
www.wp.pl##html:style(overflow: visible !important;)
```

Można by próbować lepiej to jakoś ogarnąć ale nie mam pomysłu chęci, wiedząc że jest popsuta obecnie strona przez WP.

**Comment by hawkeye116477** [comment]
No trochę słabo, inline-script lepiej nie używać, bo coś może popsuć.

**Comment by krystian3w** [comment]
To i tak jest dość mocno zepsute przez webmasterów, oceń na ile dynamiczne WP traci obsługę skryptów.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/0836e699ccf7d790e7a9d821ac7762df24844ab4/polish-adblock-filters/adblock_ublock.txt#L130

To jest dalej potrzebne do przewijania, bo dziwnie psuje obecnie wersje statyczną (przewijanie tego popsutego bubla bez części CSS i JS).
