### ISSUE TITLE
lajt.co.uk

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7552]
![opera zdjecie_2018-05-19_184408_lajt co uk](https://user-images.githubusercontent.com/36385327/40270851-c1a22f74-5b94-11e8-99fc-89a1aa6bfb8e.png)
![opera zdjecie_2018-05-19_184423_lajt co uk](https://user-images.githubusercontent.com/36385327/40270852-c1c34ee8-5b94-11e8-8e16-191512bc0241.png)

**Comment by krystian3w** [comment]
`##.ebFooter__headerLinks--lajt`
