### ISSUE TITLE
wielkopolskamagazyn.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7557]
![opera zdjecie_2018-05-19_231212_wielkopolskamagazyn pl](https://user-images.githubusercontent.com/36385327/40273089-17bdfb48-5bba-11e8-8fe8-e808cc63be49.png)

**Comment by krystian3w** [comment]
`wielkopolskamagazyn.pl###owl-carousel-1373283222` / `wielkopolskamagazyn.pl###owl_widget-2`
