### ISSUE TITLE
breakplan.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7560]
![opera zdjecie_2018-05-19_235503_breakplan pl](https://user-images.githubusercontent.com/36385327/40273411-1f55eefa-5bc0-11e8-927c-f1e8e1ece8e8.png)
![opera zdjecie_2018-05-19_234840_breakplan pl](https://user-images.githubusercontent.com/36385327/40273412-21c2a732-5bc0-11e8-9f83-038320babd00.png)

**Comment by krystian3w** [comment]
`##nav.bottom:nth-of-type(2)`
`##.social`

albo wycinając obrazki:

```
//images/fb2.png
//images/instagram192.png
//images/instagram19.png
```
