### ISSUE TITLE
businessinsider.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7562]
https://businessinsider.com.pl/wiadomosci/pgnig-zawiesza-projekt-gazowy-w-iranie/ldc0rdk
![opera zdjecie_2018-05-20_022538_businessinsider com pl](https://user-images.githubusercontent.com/36385327/40274362-1b7d90f2-5bd5-11e8-9edc-f0d5519bacff.png)

**Comment by krystian3w** [comment]
Grupa Onet, wystarczy rozbudować regułę Majkiego.
