### ISSUE TITLE
radiozet.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7567]
![opera zdjecie_2018-05-20_025624_www radiozet pl](https://user-images.githubusercontent.com/36385327/40274560-70d83c10-5bd9-11e8-9f8f-5efd71202dae.png)

**Comment by krystian3w** [comment]
Social? A nie Annoyance (push notification)?

**Comment by hawkeye116477** [comment]
No właśnie, @MajkiIT etykieta do zmiany :smile:.
