### ISSUE TITLE
nowastrategia.org.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7570]
![opera zdjecie_2018-05-20_030450_www nowastrategia org pl](https://user-images.githubusercontent.com/36385327/40274591-9d4b7176-5bda-11e8-80c9-cf0e9b09ac23.png)

**Comment by krystian3w** [comment]
`###footer-widgets > div.home-widget:nth-of-type(2)` i stopka się przesunie

Jakby nie przesuwać i wyciąć tekst "znajdziesz nas także na:"

```
www.nowastrategia.org.pl##div.home-widget:nth-of-type(2) > .widget_text.widget > .textwidget > p:nth-of-type(1)
```
```
/uploads/2016/01/fb_ikona.png$domain=www.nowastrategia.org.pl,image
/uploads/2016/01/tt.png$domain=www.nowastrategia.org.pl,image
```

obrazki można by ostatecznie kosmetycznie po parametrze `href` jak lepsze to od sieciowej wersji.
