### ISSUE TITLE
tytus.edu.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7571]
![opera zdjecie_2018-05-20_030651_tytus edu pl](https://user-images.githubusercontent.com/36385327/40274602-eb660f06-5bda-11e8-96c0-b6fb0050ae87.png)

**Comment by krystian3w** [comment]
`##._image._mi` / `###menu-item-27`

lub

`/uploads/2017/11/fb.png$domain=tytus.edu.pl,image` - może nie będzie aktualizacji grafiki
