### ISSUE TITLE
polityczek.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7573]
![opera zdjecie_2018-05-20_030848_polityczek pl](https://user-images.githubusercontent.com/36385327/40274613-2a3dace8-5bdb-11e8-814d-41b264732467.png)

**Comment by krystian3w** [comment]
`##.Menu.moduletable`  - nie wiem co robi koperta jakby mail z poziomu strony do nich (nawet nie newsletter?), jak nie dodadzą RSS to może `###mainMenu`.
