### ISSUE TITLE
strefainwestorow.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7574]
https://strefainwestorow.pl/czaty-inwestorskie/20180518/unimot-robert-brzozowski-marek-moroz
![opera zdjecie_2018-05-20_031016_strefainwestorow pl](https://user-images.githubusercontent.com/36385327/40274624-8f406f7c-5bdb-11e8-90f3-56641a282bb1.png)

**Comment by krystian3w** [comment]
`##.leaf:nth-of-type(1) > .ext` / `###strefainwestorow-menu > .leaf:nth-of-type(1)` - FB

`###block-block-56, #block-block-75, #block-block-81` - po reklamach
