### ISSUE TITLE
interwencja.polsatnews.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7575]
http://www.interwencja.polsatnews.pl/Interwencja__Oficjalna_Strona_Internetowa_Programu_INTERWENCJA,5781/Archiwum,5794/News,6271/index.html#1631618
Ukrywa treść
![opera zdjecie_2018-05-20_031801_www interwencja polsatnews pl](https://user-images.githubusercontent.com/36385327/40274657-82990bf2-5bdc-11e8-999a-e77bbc4453c7.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 błąd
`polsatnews.pl#@#script:inject(abort-on-property-read.js, parseFloat)`
