### ISSUE TITLE
tygodnikzamojski.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7578]
Reklama
![opera zdjecie_2018-05-20_095127_www tygodnikzamojski pl](https://user-images.githubusercontent.com/36385327/40276810-dad4b0a0-5c13-11e8-8361-f7ab359b49b1.png)

Reklama + social
http://www.tygodnikzamojski.pl/artykul/90564/ranking-liceow.html
![opera zdjecie_2018-05-20_095324_www tygodnikzamojski pl](https://user-images.githubusercontent.com/36385327/40276816-f0d583de-5c13-11e8-8faf-a91f97e29e20.png)

**Comment by RikoDEV** [comment]
https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/de02562fdc72d8aa8cc61ff30169f4649f84c403
