### ISSUE TITLE
polsat.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7580]
Social

```
http://www.polsat.pl/program/kabaret-na-zywo/
http://www.polsatmusic.pl/program/tylko-hity/
http://www.discopolomusic.pl/program/disco_polo_life/
http://www.polsatplay.pl/program/poszukiwacze-historii/
http://www.polsatcafe.pl/program/demakijaz/
http://www.tv6.com.pl/program/galileo/
http://www.tv4.pl/serial/esmeralda/
http://www.polsatmusic.pl/program/tylko-hity/
http://www.polsat1.pl/serial/oszukane/
http://www.polsat2.pl/serial/gliniarze/
http://www.polsatfilm.pl/news/2018-04-26/prawie-oscar-fenomen-filmu-twoj-vincent_1628699/
```
![opera zdjecie_2018-05-20_113236_www polsatfilm pl](https://user-images.githubusercontent.com/36385327/40277588-88a1f9d8-5c21-11e8-989b-b6c5178c2f8c.png)

http://www.polsatsport.pl
Wycięta treść + napisy na siebie najeżdżają 
![opera zdjecie_2018-05-20_113335_www polsatsport pl](https://user-images.githubusercontent.com/36385327/40277596-c3f40b8e-5c21-11e8-8420-3b0de5bffc68.png)

http://www.polsatsport.pl/siatkowka/
Wycięta treść
![opera zdjecie_2018-05-20_113536_www polsatsport pl](https://user-images.githubusercontent.com/36385327/40277613-1aec020c-5c22-11e8-9994-fdff04179b6f.png)

**Comment by RikoDEV** [comment]
https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/f046ee5899241c9ccaeeb61cead5a877fe75bb28
