### ISSUE TITLE
tv.pudelek.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7582]
![opera zdjecie_2018-05-20_120318_tv pudelek pl](https://user-images.githubusercontent.com/36385327/40277826-d48ded9e-5c25-11e8-8442-c84aef9d1c7b.png)

**Comment by krystian3w** [comment]
`##.aside-youtube-channel`
`##.header-fb-link`

**Comment by RikoDEV** [comment]
https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/692935717a9a7719311f8f01438e592c65529330
