### ISSUE TITLE
parenting.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7583]
https://parenting.pl/myslala-ze-bedzie-miec-blizniaki-prawda-okazala-sie-inna
![opera zdjecie_2018-05-20_120405_parenting pl](https://user-images.githubusercontent.com/36385327/40277828-ebe6137c-5c25-11e8-8052-f93a580ccc3c.png)

**Comment by krystian3w** [comment]
`##.fb-container` lub `##.fb-share-text, .btn__facebook`

**Comment by RikoDEV** [comment]
U mnie brak, @hawkeye116477 ty dodałeś już do listy?

**Comment by hawkeye116477** [comment]
U Fanboya to już jest.

**Comment by RikoDEV** [comment]
@xMaap jeśli nie masz jeszcze fanboy social to polecam zainstalować, ponieważ bazujemy na tej liście zanim dodamy element do naszej listy. 👍

**Comment by krystian3w** [comment]
Może dodali niedawno (nie chce mi się kopać w blame history list) lub w chrome jest to ignorowane i trzeba `visibility: hidden` CSS-em?

**Comment by hawkeye116477** [comment]
@krystian3w W najnowszym jest wsparcie dla styli użytkownika, więc raczej wątpię, a sam korzystam czasem z Vivaldiego, który bazuje na Chromium 65, gdzie jeszcze nie było wsparcia dla styli użytkownika, więc trzeba było się bawić czasem z visibility, ale w tym przypadku jest ok.

**Comment by krystian3w** [comment]
OK, no to może wina Opery 52 i starszej z uBlock Origin - nazwy zdjęć wstawianych wskazują na operę.

**Comment by hawkeye116477** [comment]
Takiej starej Opery u mnie w repo już nie ma, ale na 53 jest ok :smile:.

**Comment by xMaap** [comment]
@hawkeye116477 szczegóły?
Manjaro, Opera 53.0.2907.57, Nano Adblocker 1.0.0.50, Nano Defender 14.39.
Mam Fanboy Social zaznaczony.

**Comment by hawkeye116477** [comment]
@xMaap No to sprawdziłem na tych samych wersjach Nano i Opery i ja tego nie mam. Może zrób update filtrów, wyczyść dane i sprawdź ponownie.
