### ISSUE TITLE
kongresobywatelski.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7584]
![opera zdjecie_2018-05-20_120434_www kongresobywatelski pl](https://user-images.githubusercontent.com/36385327/40277829-ffccd0ec-5c25-11e8-8084-d3392abdec77.png)

**Comment by krystian3w** [comment]
`###header-top .textwidget` ❓

**Comment by RikoDEV** [comment]
@krystian3w w ten sposób zablokujesz też link d strony, która nie jest socialem więc odpada.

https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/692935717a9a7719311f8f01438e592c65529330
