### ISSUE TITLE
swiatbaterii.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7588]
swiatbaterii.pl
![opera zdjecie_2018-05-20_172729_swiatbaterii pl](https://user-images.githubusercontent.com/36385327/40280424-50b9db12-5c53-11e8-9ba7-108ecde2a37c.png)
https://blog.swiatbaterii.pl
![opera zdjecie_2018-05-20_172813_blog swiatbaterii pl](https://user-images.githubusercontent.com/36385327/40280426-58cde15e-5c53-11e8-9333-4699d17ac34f.png)

**Comment by krystian3w** [comment]
`##.aspexi_facebook_button` lub  `##.aspexifbsidebox` - wysuwany box

`##.col-md-3 > div.row:nth-of-type(2)` lub blokując ich 4 dziwnie nazwane obrazki
