### ISSUE TITLE
Wycinanie filmow w grupie wp

### ISSUE THREAD

**Issue by DajMiliona** [MajkiIT/polish-ads-filter#7593]
Przykład:
https://teleshow.wp.pl/aleksandra-wozniak-wycofala-sie-z-show-biznesu-zobaczcie-jak-teraz-wyglada-gwiazda-13-posterunku-6254299589580417a

Po tekscie a przed komentarzami jest film. Jest on blokowany i jak sie przewija strone widzimy go po czym szybko znika (jest wycinany).

Dzieje sie tak w wielu linkach ze strony wp do jakiegos materiału.

**Comment by MajkiIT** [comment]
@DajMiliona u mnie jest ok. Nie wiem jakich filtrów ożywasz. 

https://www.screencast.com/t/aMHVfcwlj9

**Comment by krystian3w** [comment]
U mnie też OK:

> ![image](https://user-images.githubusercontent.com/35370833/40356708-3416c2f0-5dba-11e8-9160-7c4dda309571.png) |
--- |

**Comment by DajMiliona** [comment]
Mam Firefox, ublock origin nano defender najnowszy. 
[ublock-kopia-zapasowa_2018-05-22_13.51.55.txt](https://github.com/MajkiIT/polish-ads-filter/files/2026433/ublock-kopia-zapasowa_2018-05-22_13.51.55.txt)

**Comment by DajMiliona** [comment]
Na Chrome ok na Firefox nie ...

**Comment by xMaap** [comment]
Firefox 60, uBlock Origin v1.16.6, Nano Defender 14.37
![zrzut ekranu z 2018-05-22 13-58-28](https://user-images.githubusercontent.com/36385327/40361093-782d294e-5dc8-11e8-9e9a-bf517dc91dec.png)

**Comment by krystian3w** [comment]
Może polskie uzupełnienie adugard nawala, nie żeby coś bo nie używam.

**Comment by DajMiliona** [comment]
Jak mozesz wrzuc swoje filtry (kopie) bo niestety u mnei nie dziala wylaczanie filtrow itp.

**Comment by xMaap** [comment]
> bo niestety u mnei nie dziala wylaczanie filtrow itp.

To coś masz zepsute. Masz uBlock Origin czy uBlock?

**Comment by DajMiliona** [comment]
ublock Origin

**Comment by xMaap** [comment]
Nie wiem może usuń i zainstaluj jeszcze raz.
Ja mam tak:
![zrzut ekranu z 2018-05-22 15-01-32](https://user-images.githubusercontent.com/36385327/40363884-1d11f8ba-5dd1-11e8-9f2c-16f6bb966179.png)
W
moz-extension://35cb939c-cdea-4edb-98b7-9edf25487798/advanced-settings.html mam tak
![zrzut ekranu z 2018-05-22 15-06-38](https://user-images.githubusercontent.com/36385327/40364137-cda988f0-5dd1-11e8-98bb-98138ebe7352.png)

```
           assetFetchTimeout 30
  autoUpdateAssetFetchPeriod 120
            autoUpdatePeriod 7
       ignoreRedirectFilters false
   ignoreScriptInjectFilters false
manualUpdateAssetFetchPeriod 500
               popupFontSize unset
       suspendTabsUntilReady false
       userResourcesLocation https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt
```

![zrzut ekranu z 2018-05-22 15-09-37](https://user-images.githubusercontent.com/36385327/40364303-43608738-5dd2-11e8-881d-db076b4092e2.png)
![zrzut ekranu z 2018-05-22 15-10-48](https://user-images.githubusercontent.com/36385327/40364338-5f8d112e-5dd2-11e8-8846-0127ec5af876.png)
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt​​​​​ 
​​https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt​​
​​https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt​​
​​https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt
https://alleblock.pl/alleblock/alleblock.txt
https://raw.githubusercontent.com/azet12/KAD/master/KAD.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt
https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt

**Comment by DajMiliona** [comment]
Dzieki teraz dziala :)
Tam jest opcja exportu filtrów :)
Szybsze to jak wklejanie screenow :)

**Comment by xMaap** [comment]
Wiem o tym, ale mam też ustawione aby blokowało skrypty na stronach coś jak w NoScript czy uMatrix i by wszystko się skopiowało.
