### ISSUE TITLE
sklep.carrefour.pl + carrefour.pl + douglas.pl + intersport.pl + hebe.pl + carry.pl + bluestop.pl + castorama.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7598]
Social

**Comment by krystian3w** [comment]
* `carrefour.pl##li.m-t-sm:nth-of-type(4)`

* `douglas.pl##.rd__col--md-push-6.rd__col--md-6.rd__col--sm-12.rd__col > .rd__footer__block`

* `intersport.pl##.header__top--social`

* `hebe.pl##li.pad1y:nth-of-type(1), li.pad1y:nth-of-type(2), li.pad1y:nth-of-type(3)`

* `bluestop.pl` - nie widzę / wycina Disconnect (dodatkowo mają jakby stronę popsutą - nawigacja)

<ul><li>

`||carry.pl//themes/default/img/instagram1.png`
`||carry.pl//themes/default/img/fb.png`
`||carry.pl//themes/default/img/newsletter1.png` - na osobną listę, jak nie wycina.

(opcjonalnie po parametrze `href`)

</ul>

* `castorama.pl##.so-ico, #div.col-md-2.col-xs-3:nth-of-type(5) > p`
