### ISSUE TITLE
przeklej.org

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#76]
http://przeklej.org/file/Zzvd7p/14489957458581.zip

dalej sa reklamy system12.pl

**Comment by xxcriticxx** [comment]
v.2015120702 aktualizacja: pon, 7 grudnia 2015, 17:30:00 

cos filtry mi sie nie updtetuja dalej widze rekalmy przyciskalem F5 i wyczyscilem cache

**Comment by MajkiIT** [comment]
nie dodałem jeszcze reguł.
