### ISSUE TITLE
energetyka24.com + cyberdefence24.pl + defence24.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7610]
energetyka24.com
cyberdefence24.pl
Social i Orlen(?)
![opera zdjecie_2018-05-23_112957_www energetyka24 com](https://user-images.githubusercontent.com/36385327/40416269-297fb036-5e7d-11e8-83ac-d786c6f3ad8d.png)

defence24.com
Puste miejsce po reklamie
![opera zdjecie_2018-05-23_113456_www defence24 com](https://user-images.githubusercontent.com/36385327/40416354-5daf21fc-5e7d-11e8-985e-1673ed830c16.png)

**Comment by krystian3w** [comment]
`##.header-bottom-social`
`##.header-bottom-partner-info`

---

`defence24.com##body > section.section:nth-of-type(1), #section.section:nth-of-type(2)` - ja mam aż dwie luki po reklamach.
