### ISSUE TITLE
zeropln.antyweb.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7623]
![opera zdjecie_2018-05-24_040027_zeropln antyweb pl](https://user-images.githubusercontent.com/36385327/40460441-0712b22a-5f07-11e8-94ed-28276e7eac6e.png)

**Comment by MajkiIT** [comment]
```
zeropln.antyweb.pl##.relative.bg-white
zeropln.antyweb.pl##.bg-black.opacity-50
```

**Comment by hawkeye116477** [comment]
Trochę to chyba za dużo przyblokuje.

**Comment by krystian3w** [comment]
`antyweb.pl##body[style]:style(overfolow:auto!important)` :question: 

Chyba, że znajdzie się coś pod AdBlock / Adblock Plus.

**Comment by hawkeye116477** [comment]
@MajkiIT To nic nie szkodzi, można go odblokować, najwyżej ci co mają Adblocka będą musieli jakoś żyć z tym komunikatem :smile:.
