### ISSUE TITLE
agdlab.pl + jakdojade.pl + vod.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7625]
![opera zdjecie_2018-05-24_041748_agdlab pl](https://user-images.githubusercontent.com/36385327/40461172-5b66046e-5f0a-11e8-9475-762506c8d194.png)
![opera zdjecie_2018-05-24_042003_jakdojade pl](https://user-images.githubusercontent.com/36385327/40461173-5b8c4df4-5f0a-11e8-841e-4b67d00edf49.png)
![opera zdjecie_2018-05-24_042224_vod pl](https://user-images.githubusercontent.com/36385327/40461174-5bae37e8-5f0a-11e8-8162-b34adfbacc99.png)

**Comment by MajkiIT** [comment]
dodać do `##.cmp-popup_popup`
