### ISSUE TITLE
czy dobre filtry

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#7628]
czy te filtry sa dobre, dla player.pl i innych stron(dla roznych stron)?

![ublock](https://user-images.githubusercontent.com/17565773/40469485-02c7c14a-5f31-11e8-9777-72efc95bc729.jpg)

mam win 10, opera 53, ublock origin

**Comment by MajkiIT** [comment]
w gruncie rzeczy tak... brakuje mi privacy i nano filters.

**Comment by lukjan32** [comment]
aha, bedzie dobrze, tak?

**Comment by krystian3w** [comment]
Jakby znów coś blokowało to może Opery wina:

> ![Imgur](https://i.imgur.com/UoWE9U5.png) https://portableapps.com/apps/internet/iron_portable

> ![Imgur](https://i.imgur.com/BpJ1UbW.png?1) https://portableapps.com/apps/internet/google_chrome_portable

**Comment by lukjan32** [comment]
skad dodac ten privacy, o ktorym pisal @MajkiIT ?

**Comment by krystian3w** [comment]
Z repo na głównej można już go subskrybować.

> ![image](https://user-images.githubusercontent.com/35370833/40471116-fea08070-5f35-11e8-807c-edef33ea4893.png) |
> --- |

Nad ciasteczkowymi.

**Comment by lukjan32** [comment]
Polish Privacy Filters ?

**Comment by krystian3w** [comment]
Tak.

**Comment by lukjan32** [comment]
dzieki. i tak mi sie pokazuje na player.pl, blokada :(

**Comment by krystian3w** [comment]
Spróbuj więc na wersji portable ![Imgur](https://i.imgur.com/UoWE9U5.png?1)  Iron / ![Imgur](https://i.imgur.com/wOnDNt9.png?1) Cent browser /  ![Imgur](https://i.imgur.com/2GQu1xO.png?1) Slimjet lub ostatecznie ![Imgur](https://i.imgur.com/BpJ1UbW.png?1)  Chrome.

https://github.com/MajkiIT/polish-ads-filter/issues/7628#issuecomment-391617510

**Comment by lukjan32** [comment]
przeciez opera, to juz chrome.

**Comment by krystian3w** [comment]
Ale pewnie dalej części API webextension nie obsługuje czy jakoś swoimi opcjami może blokuje nawet jak nie włączałeś blokowania reklam / opcji blokowania natrętnych reklam chrome https://github.com/MajkiIT/polish-ads-filter/issues/6239.

Albo `player.pl` nie pasuje (jak kiedyś Google i Bing - MS) `useragent` (i ładowali wersje dla Internet Explorer / starych przeglądarek).

**Comment by lukjan32** [comment]
to trzeba do opery napisac, aby dodali.

**Comment by krystian3w** [comment]
https://bugs.opera.com/wizard/
https://bugs.opera.com/wizard/desktop

**Comment by lukjan32** [comment]
poszlo

**Comment by krystian3w** [comment]
Jeszcze możesz próbować odznaczać listy i zobaczyć kiedy wskoczy wideo :movie_camera: lub reklama przed wideo i po niej wideo :movie_camera:. 

Potem przywracać stan i w miarę przejrzeć listę, która "uwala" `player.pl` w Operze ![Imgur](https://i.imgur.com/Zrxrzzv.png).

Może będzie się dało regułę lub kilka usunąć lub dla `player.pl` wyłączyć.

**Comment by lukjan32** [comment]
odznaczylem easylist, i jest

**Comment by krystian3w** [comment]
Po reklamie rusza wideo czy nie bardzo.

Możesz zobaczyć czy na połowie reguł z kwietnia ruszy, jednak lepiej było by używać wspieranej wersji EasyList i pewnie pełnej. EasyList Lite wygląda na porzucone przez AdBlock i chyba wspierali to tylko na Firefox. 

`https://cdn.adblockcdn.com/filters/easylist_lite.txt`  (<a href="https://subscribe.adblockplus.org/?location=https://cdn.adblockcdn.com/filters/easylist_lite.txt&amp;title=AdBlock%20EasyList%20Lite" rel="nofollow">Subskrybuj</a>)

**Comment by lukjan32** [comment]
po wylaczeniu easylist, po reklamach jest serial.

**Comment by krystian3w** [comment]
Jeszcze możesz sprawdzić bez Nano Defendera chromowego i wgrać tylko chrome uBlock Origin Extra:

[install-chrome-extensions](https://addons.opera.com/pl/extensions/details/install-chrome-extensions/) lub [extension-source-viewer](https://addons.opera.com/pl/extensions/details/extension-source-viewer/)

:heavy_plus_sign: 

https://chrome.google.com/webstore/detail/ublock-origin-extra/pgdnlhfefecpicbbihgmbmffkjpaplco

**Comment by krystian3w** [comment]
A jeszcze takie pytanie: może masz Disconnect z ukrytą ikoną, on na pewno psuje stream tvp i trzeba dodać do białej listy w nim.

**Comment by krystian3w** [comment]
Takie coś:

![obraz](https://user-images.githubusercontent.com/35370833/40562894-213b1cc0-6063-11e8-940b-be173802631d.png) |
--- |

**Comment by lukjan32** [comment]
tak samo

**Comment by krystian3w** [comment]
* OK, jak dodałeś do wyjątków / wyłączyłeś dodatek. 
* Dodatkowo jak nie rusza na EasyList Lite to ją wywal - możliwe, że ona obecnie rozwaliła tvp (brak aktualizacji przez miesiąc wg opisu listy).

---

* `||player.pl^$generichide` - działa na player czy nie daje nic.

**Comment by lukjan32** [comment]
nie mam easylist lite.

ten skrypt nie dziala

**Comment by Lukjan39** [comment]
mam AdGuard, czy tak mam dobrze?
![1](https://github.com/MajkiIT/polish-ads-filter/assets/104568362/eaa3bdb0-2cb8-45d2-8181-a8e9cb5ec2dc)
![2](https://github.com/MajkiIT/polish-ads-filter/assets/104568362/dc0d731b-511a-447b-a2bb-1151dc49db8b)
![3](https://github.com/MajkiIT/polish-ads-filter/assets/104568362/0099e6d9-ec84-4a3a-8498-c31910a982b7)
![4](https://github.com/MajkiIT/polish-ads-filter/assets/104568362/6f9e01b1-0943-4199-827c-bf4a9db3282c)
