### ISSUE TITLE
oknonet.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#7633]
![2018-05-24-chec stworzenia czegos wlasnego zaczatkiem powstania aluglobal - oknonet pl](https://user-images.githubusercontent.com/5884000/40489416-56588bd6-5f69-11e8-8b78-e539813b3db4.png)
`https://www.oknonet.pl/okna/typy_okien/news,26883.html`

pusta sekcja reklama po prawej

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.6
 ND 14.39
 Chr 66.0.3359.181
</details>

**Comment by krystian3w** [comment]
`##.oknoad-news`
