### ISSUE TITLE
chip.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#7634]
![2018-05-24-google zebralo o mnie 11 gigabajtow danych _ chip](https://user-images.githubusercontent.com/5884000/40489530-9e0c56a6-5f69-11e8-89b6-2e8abb6e7bf6.png)
`https://www.chip.pl/2018/03/google-zebralo-o-mnie-11-gigabajtow-danych/`

pusta sekcja reklama po prawej

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.6
 ND 14.39
 Chr 66.0.3359.181
</details>

**Comment by krystian3w** [comment]
`###banner-3`
