### ISSUE TITLE
ppe.pl + terazmuzyka.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7637]
![opera zdjecie_2018-05-24_195722_www ppe pl](https://user-images.githubusercontent.com/36385327/40503039-0b267c6c-5f8d-11e8-87dc-bb3a6c9cd920.png)

**Comment by krystian3w** [comment]
`###rodo-overlay`

a skrypt jakoś liniowo ładowany... ❓
