### ISSUE TITLE
Grupa Agora

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7638]
http://wyborcza.pl/
![opera zdjecie_2018-05-24_213509_wyborcza pl](https://user-images.githubusercontent.com/36385327/40509862-14873108-5f9b-11e8-8388-23d72216cf33.png)
Po scrollowaniu strony 
![opera zdjecie_2018-05-24_213639_wyborcza pl](https://user-images.githubusercontent.com/36385327/40509864-14a92ff6-5f9b-11e8-84b4-4e98bf866a74.png)

**Comment by krystian3w** [comment]
`###rodoNotificationWrapper`

lub

`||rodo.agora.pl/agreement/check?gid=1$script`

**Comment by xMaap** [comment]
Najlepiej chyba będzie to pierwsze, bo to drugie nie wszędzie ukrywa np. w tokfm.pl

**Comment by krystian3w** [comment]
Tam mają inną cyfrę, dzięki!

Zawsze do testu można uprościć do `||rodo.agora.pl^$script`

**Comment by MajkiIT** [comment]
@krystian3w @xMaap Dziękuję
