### ISSUE TITLE
Github się zmienia...

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#7639]
* Przez kilka dni nie działał mi, bot do requestów; 
* Przebudowali stronę po zalogowaniu;
* a teraz można podejrzeć każdą edycje odpowiedzi, 
    * nawet taką ukryciem elementów w komentarzu html (oczywiście komentarza nie widać bez użycia api),
    * stare edytowane odpowiedzi nie są tym objęte na razie.

**Comment by xxcriticxx** [comment]
@krystian3w tak jest co pare miesiecy
