### ISSUE TITLE
ipla.tv

### ISSUE THREAD

**Issue by kavillock** [MajkiIT/polish-ads-filter#7641]
### Zrzut ekranu
https://prnt.sc/jm8oxn

### Link bezpośredni
np. https://www.ipla.tv/wideo/serial/Policjantki-i-policjanci/5003132/Policjantki-i-policjanci-Odcinek-423/87abc6b5be47607072de900fd9a9c45a

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. czasami nic
2. odpala się czasami zaraz przed blokiem reklamowym
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**
chrome
**Rozszerzenia i skrypty:**
nano defender ublock
**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. domyslne ublock origina
3. te co byly potrzebne dla nano defendera
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by MajkiIT** [comment]
@hawkeye116477 cookies 'www.ipla.tv##.rodo-rules-modal'
