### ISSUE TITLE
e-biznes.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7643]
https://e-biznes.pl/nazwa-pl-wycofuje-oferty-sklepy-internetowe/
Ukrywa teks artykułu
![opera zdjecie_2018-05-25_002600_e-biznes pl](https://user-images.githubusercontent.com/36385327/40516735-47d1c9ee-5fb2-11e8-83b4-cfa3e07d441e.png)
![opera zdjecie_2018-05-25_002620_e-biznes pl](https://user-images.githubusercontent.com/36385327/40516736-47f3253a-5fb2-11e8-9436-307e67c522ea.png)

Oraz social
![opera zdjecie_2018-05-25_002652_e-biznes pl](https://user-images.githubusercontent.com/36385327/40516746-5b5640a8-5fb2-11e8-801c-4d5c80611951.png)

**Comment by hawkeye116477** [comment]
Nic nie ukrywa, to oni schowali i trzeba polubić, by zobaczyć tekst, tylko komunikat o tym wyciął Fanboy.

**Comment by krystian3w** [comment]
Albo niech sobie skopiują do notatnika / WordPada - nie zablokowali zaznaczania i kopiowania

**Comment by hawkeye116477** [comment]
No nie wiem, chyba lepiej odblokować, bo mogą jeszcze pomyśleć, że to my psujemy, choć w sumie to wina Fanboya, więc na razie ja dodam te wyjątki i też napiszemy do niego :smile:.
