### ISSUE TITLE
morele.net

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7645]
![opera zdjecie_2018-05-25_010128_www morele net](https://user-images.githubusercontent.com/36385327/40517770-53db6b32-5fb7-11e8-9154-c4ea14c85b47.png)

**Comment by hawkeye116477** [comment]
Nie ma wody na pustyni, może to tylko dla zalogowanych?

**Comment by krystian3w** [comment]
Mam po kilku minutach:

`###content_info_popup` - zablokowany scroll
`##html.overflow:style(overflow:auto!important)` - odblokowanie scrolla i puszcza mimo dodatkowej blokady na `body`

Sieciowo za bardzo nie umiem namierzyć, może wywołują liniowo lub przyklejając do czegoś innego.

**Comment by hawkeye116477** [comment]
Tutaj niby jest, ale ja bym tego jednak nie ruszał `||morele.net/static/js/home.app.js` :smile:
