### ISSUE TITLE
animezone.pl

### ISSUE THREAD

**Issue by Morph21** [MajkiIT/polish-ads-filter#7654]
### Zrzut ekranu
![image](https://user-images.githubusercontent.com/38075691/40546044-5142e356-602e-11e8-93d8-bd90ca419719.png)

### Link bezpośredni
https://www.animezone.pl/odcinek/nanatsu-no-taizai-imashime-no-fukkatsu/17

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Nacisnąć w przycisk odtwórz

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome

**Rozszerzenia i skrypty:**
Adbloc, ublock

**Filtry:**

1. Polskie filtry do Adblocka i uBlocka
2. EasyList
3. EasyPrivacy

**Comment by krystian3w** [comment]
`Adbloc, ublock` - polecam zostawić ten drugi i upewnić się, że to uBlock Origin.

**Comment by krystian3w** [comment]
Na Firefox działa, jakiś konkretny hosting klikać?
