### ISSUE TITLE
salesmanago.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#7659]
@hawkeye116477 cos do twego repo tak samo jest na salesmanago.com tylko po angielsku

![capture](https://user-images.githubusercontent.com/15007183/40546639-c90eca98-5ffd-11e8-9d7e-51a87a8cc2f9.PNG)

**Comment by hawkeye116477** [comment]
Komunikat to chyba do ciasteczkowych, a reszta to owszem do mnie.

**Comment by krystian3w** [comment]
Push już nie ma u mnie (pewnie Adguard Annoyance mi wycina). Zostało z lewego rogu rodo.

```
||salesmanago.pl/static/sm.js
```

**Comment by hawkeye116477** [comment]
@krystian3w Nasze Annoyance wycinają push :smile:.

**Comment by krystian3w** [comment]
Ja mam tylko zdarzenie z Adugardowej listy na tej stronie :wink:
