### ISSUE TITLE
wpolityce.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7662]
![opera zdjecie_2018-05-25_154025_wpolityce pl](https://user-images.githubusercontent.com/36385327/40547425-1cc57a9a-6032-11e8-9f85-2e84fcc71300.png)

**Comment by krystian3w** [comment]
`##.rhododendron-popup-overlay, #TOS-POPUP` - pop-up
`##body.rhododendron-body-with-popup:style(overflow:auto!important)` - scroll

**Comment by hawkeye116477** [comment]
Albo `||static.wpolityce.pl/rhododendron/css/rhododendron-popup.css`

**Comment by hawkeye116477** [comment]
Zamiast reguły na scroll , można po prostu css wyciąć `||static.wpolityce.pl/rhododendron/css/rhododendron-popup.css`
