### ISSUE TITLE
*.tvp.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7669]
Coś się zepsuło, ze się kręci i kręci
```
http://tvp1.tvp.pl
http://tvp2.tvp.pl
http://polonia.tvp.pl
http://historia.tvp.pl
http://hd.tvp.pl
http://seriale.tvp.pl
http://tvprozrywka.tvp.pl
```
![opera zdjecie_2018-05-25_160929_historia tvp pl](https://user-images.githubusercontent.com/36385327/40548810-065537ec-6036-11e8-9175-6812bd6c125e.png)

**Comment by hawkeye116477** [comment]
`@@||myao.adocean.pl/files/js/ado.js$script,domain=tvp.pl`
