### ISSUE TITLE
tuba.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#7675]
![capture](https://user-images.githubusercontent.com/15007183/40566770-4445541a-6040-11e8-86c7-7456a83af2db.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale to jest już blokowane.

**Comment by hawkeye116477** [comment]
Podobnie https://github.com/MajkiIT/polish-ads-filter/issues/7698#issuecomment-392253637
