### ISSUE TITLE
fm.tuba.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#7676]
![capture](https://user-images.githubusercontent.com/15007183/40566808-728fc620-6040-11e8-9a63-0aa2340a39fe.PNG)

**Comment by hawkeye116477** [comment]
To tak samo już jest.
https://github.com/MajkiIT/polish-ads-filter/issues/7675

**Comment by hawkeye116477** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/7698#issuecomment-392253637
Tak samo
