### ISSUE TITLE
aszdziennik.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7696]
![opera zdjecie_2018-05-26_040112_aszdziennik pl](https://user-images.githubusercontent.com/36385327/40571463-8c7035f8-6099-11e8-9d62-3857f5bc5736.png)

**Comment by MajkiIT** [comment]
`mamadu.pl##[class^="popup_popup--"]`

**Comment by hawkeye116477** [comment]
`aszdziennik.pl##div[class^="app_gdpr"]`
