### ISSUE TITLE
innpoland.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7697]
![opera zdjecie_2018-05-26_040410_innpoland pl](https://user-images.githubusercontent.com/36385327/40571478-ddb8c4ac-6099-11e8-80a7-607e219f23c2.png)

**Comment by MajkiIT** [comment]
`mamadu.pl##[class^="popup_popup--"]`

**Comment by hawkeye116477** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/7698#issuecomment-392253637
