### ISSUE TITLE
mamadu.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7698]
![opera zdjecie_2018-05-26_040430_mamadu pl](https://user-images.githubusercontent.com/36385327/40571483-ece6e3aa-6099-11e8-8511-0a6ee4b70c3b.png)

**Comment by MajkiIT** [comment]
`mamadu.pl##[class^="popup_popup--"]`

**Comment by hawkeye116477** [comment]
Najwyraźniej pominąłem to w komentarzu zamykającym, tak czy siak można zamknąć :smile:
