### ISSUE TITLE
edufinanse.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7702]
![opera zdjecie_2018-05-26_123928_www edufinanse pl](https://user-images.githubusercontent.com/36385327/40575260-fd061948-60e1-11e8-86e0-f71e17755a6c.png)

**Comment by krystian3w** [comment]
jak na Interii / pcformat:

`##.rodo-popup`

lub testować:

* `||prywatnosc.interia.pl/rodo-iframe$subdocument`
* `||prywatnosc.interia.pl/rodo-iframe$inline-script`
