### ISSUE TITLE
komixxy.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7703]
komixxy.pl
retro.pewex.pl
stylowi.pl
![opera zdjecie_2018-05-26_125937_komixxy pl](https://user-images.githubusercontent.com/36385327/40575410-dc6b950c-60e4-11e8-9589-5b5e08c4c320.png)

**Comment by krystian3w** [comment]
`###pp-bg-overlay`  / `||static.demotywatory.pl/res/js/privacy_policy.js$script`
