### ISSUE TITLE
radiowroclaw.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7704]
![opera zdjecie_2018-05-26_130334_www radiowroclaw pl](https://user-images.githubusercontent.com/36385327/40575430-40558f96-60e5-11e8-8b2b-bfe15e20cf67.png)

**Comment by krystian3w** [comment]
`###rodo`

albo testować:

`||www.radiowroclaw.pl/min-js?f=js/rodo.js$script,domain=www.radiowroclaw.pl`
`||www.radiowroclaw.pl/min-css?f=css/rodo.css$stylesheet,domain=www.radiowroclaw.pl`
