### ISSUE TITLE
infobrzeszcze.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7706]
![opera zdjecie_2018-05-26_131454_infobrzeszcze pl](https://user-images.githubusercontent.com/36385327/40575529-d789e618-60e6-11e8-8108-78061d9042d9.png)
![opera zdjecie_2018-05-26_131512_infobrzeszcze pl](https://user-images.githubusercontent.com/36385327/40575530-d7ab0adc-60e6-11e8-873f-a93ffed9cfed.png)

**Comment by krystian3w** [comment]
`##A[target="_blank"] > IMG`

`##.td-a-rec-id-sidebar` lub `##.td-a-rec`
