### ISSUE TITLE
spottedlublin.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7709]
![opera zdjecie_2018-05-26_131844_spottedlublin pl](https://user-images.githubusercontent.com/36385327/40575558-68b6118e-60e7-11e8-8e35-11624c1b96a8.png)
![opera zdjecie_2018-05-26_131855_spottedlublin pl](https://user-images.githubusercontent.com/36385327/40575559-68d8ee16-60e7-11e8-8fa8-8e11fb6d11de.png)

**Comment by krystian3w** [comment]
Filter | Opis
--- | ---
`##A[target="_blank"] > IMG` | top reklama, prostą regułą
`##center > p` | tekst "`reklama`" nad top reklamą, trzeba by chyba dopracować, jak wyśrodkowują np. artykuły `<center>`-em a nie tylko reklamy np. dostosowanie mogło wyglądać by tak:<br><br> `##center:nth-of-type(1)` i wtedy wycinanie linka z grafiką nie było by konieczne
`##[id^="post-"]> .g1-row-inner` | w artykułach przed ich rozpoczęciem, <br><br>można też sieciowo przyblokować:<br><br> `\|\|spotted.atthost24.pl$subdocument` <br><br>ramkę ale zostanie napis "Partner serwisu", który by trzeba wyciąć.
