### ISSUE TITLE
biokurier.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7710]
http://biokurier.pl/jedzenie/przepisy/muffinki-ze-szpinakiem-i-bananami-przepis/
![opera zdjecie_2018-05-26_132105_biokurier pl](https://user-images.githubusercontent.com/36385327/40575584-b99b0faa-60e7-11e8-8fbc-931ed93bad9a.png)
![opera zdjecie_2018-05-26_132114_biokurier pl](https://user-images.githubusercontent.com/36385327/40575585-b9bc94cc-60e7-11e8-8a74-815480b1da40.png)

**Comment by krystian3w** [comment]
```
##A[target="_blank"] > IMG
```

<details><summary> jakby przebudowali linki </summary>
<br>

`##.td-header-sp-recs` ❓ 

`##.td-post-content > [id^="sh"]` ❓ 

</details>
