### ISSUE TITLE
tylkomedycyna.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7711]
https://tylkomedycyna.pl/wiadomosc/jedzenie-ryb-znacznie-zmniejsza-ryzyko-choroby-wiencowej-i-zawalu-serca
Puste miejsce po reklamie
![opera zdjecie_2018-05-26_132428_tylkomedycyna pl](https://user-images.githubusercontent.com/36385327/40575604-30119f14-60e8-11e8-9ba2-e7b852360468.png)

Social
![opera zdjecie_2018-05-26_132511_tylkomedycyna pl](https://user-images.githubusercontent.com/36385327/40575609-3d581734-60e8-11e8-9d5f-03e9c1d1b1c9.png)

**Comment by krystian3w** [comment]
`##div[style="width:300px;height:250px;"]`

`##.service-links--pl-sledzik, .service-links--pl-wykop`

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję za reguły.

**Comment by krystian3w** [comment]
Ale śledzik i wykop nie na social?
