### ISSUE TITLE
szukajka.tv

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7714]
![opera zdjecie_2018-05-26_215934_szukajka tv](https://user-images.githubusercontent.com/36385327/40579787-32b43cc0-6130-11e8-8d2b-f1aec716e8e1.png)

**Comment by MajkiIT** [comment]
`szukajka.tv###rodo-popup` @hawkeye116477 może zrobić tego global ?

**Comment by hawkeye116477** [comment]
No nie wiem, na alltube jest taka sama reguła i jest blokada scrolla.
