### ISSUE TITLE
fakro.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7720]
![opera zdjecie_2018-05-27_132937_www fakro pl](https://user-images.githubusercontent.com/36385327/40585389-2bc30428-61b2-11e8-8cda-d321bc020eca.png)

Social
![opera zdjecie_2018-05-27_133109_www fakro pl](https://user-images.githubusercontent.com/36385327/40585391-3cf2f96a-61b2-11e8-8196-f39fafc1b945.png)

**Comment by krystian3w** [comment]
Tło to, po reklamie / autopromocji: `https://player.vimeo.com/video/230894581` - **najprawdopodobniej**

`fakro.pl#?#.fancybox-overlay:-abp-has([id^="fancybox-frame"])` lub coś podobnego, powiększanie grafik robią jeszcze czym innym.

Nie wiem co wycina ❌  i wideo, żadna z naszych list ani żadne międzynarodowe Annoyance.


----

Social:

`##.footer-col:nth-of-type(4)` - razem z napisem

samą ikonę `/layout/ico_instargram.png` lub inną metodą (`href` / `alt="ODWIEDŻ NAS"`)

**Comment by hawkeye116477** [comment]
Ja tam mam ten filmik autopromocyjny.

**Comment by krystian3w** [comment]
O to tam mają fancybox, więc byle jakie wycięcie reklamy przy pierwszym wejściu, by upośledziło odblokowaną sekcje.

**Comment by hawkeye116477** [comment]
@krystian3w Ale to autoreklama, więc raczej na główną listę się nie kwalifikuje :smile:.

**Comment by MajkiIT** [comment]
@KonoromiHimaries zainteresowany ?

**Comment by hawkeye116477** [comment]
@MajkiIT Jeszcze jest bug do poprawy, a wszelkie popupy wewnętrzne idą do Annoyance :smile:.

**Comment by MajkiIT** [comment]
@hawkeye116477 Ok dziękuję za info.
