### ISSUE TITLE
zmianynaziemi.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7721]
Social
https://zmianynaziemi.pl/wiadomosc/potezny-cyklon-mekunu-zniszczyl-sokotre-i-wtargnal-do-omanu
![opera zdjecie_2018-05-27_133629_zmianynaziemi pl](https://user-images.githubusercontent.com/36385327/40585426-0f208cfe-61b3-11e8-81b5-f3956dc75daa.png)

**Comment by krystian3w** [comment]
@MajkiIT usuń z listy polskiej i niech @hawkeye116477  doda na socialową.

https://github.com/MajkiIT/polish-ads-filter/issues/7711
