### ISSUE TITLE
krakow.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7726]
http://krakow.pl/aktualnosci/220424,29,komunikat,meteorolodzy_ostrzegaja_przed_burzami_z_gradem.html
Social
![opera zdjecie_2018-05-27_165147_krakow pl](https://user-images.githubusercontent.com/36385327/40587339-46f072e6-61ce-11e8-9930-f8627c61ad6a.png)

**Comment by krystian3w** [comment]
Social:
`##.sumary_add_to`
`##.spr010_facebook, .spr011_twitter,.spr013_youtube`

RSS:
`##.spr014_rss` - bo nie wycina
