### ISSUE TITLE
chilitonka.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7728]
![opera zdjecie_2018-05-27_171727_chilitonka com](https://user-images.githubusercontent.com/36385327/40587614-dadd0b88-61d1-11e8-861e-17b3ee63de88.png)

**Comment by krystian3w** [comment]
`##.wpcnt-header` / `##.wpcnt` - do sprawdzenia jak reagują na inne blogi lub jakiś bardziej kojarzący tag z reklamą.
