### ISSUE TITLE
kochamwroclaw.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7730]
![opera zdjecie_2018-05-27_174021_kochamwroclaw pl](https://user-images.githubusercontent.com/36385327/40587836-0f0b1820-61d5-11e8-91f9-2289fdb8860c.png)

**Comment by krystian3w** [comment]
`##.td-header-rec-wrap` / `##.td-header-sp-recs`

**Comment by hawkeye116477** [comment]
@MajkiIT Jeszcze jest reklama.

**Comment by MajkiIT** [comment]
@hawkeye116477 chyba coś nie blokuje :(

**Comment by hawkeye116477** [comment]
@MajkiIT Bo dzisiaj coś zmienili, wredni walnęli 3 komunikaty na raz. Wcześniej to w ogóle coś było nie tak, bo było coś tam napisane i jakoś to słabo wyglądało, słabo sformatowane i zaraz znikało wszystko. Teraz chyba też coś nie tak... A reklamy już nie ma, bo zmienili układ strony.
![screenshot_20180529_100750](https://user-images.githubusercontent.com/19818572/40646007-51c0080c-6328-11e8-9192-f1d555b8683f.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 spokojnie tylko mówię.
