### ISSUE TITLE
lovekrakow.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7731]
![opera zdjecie_2018-05-27_174223_lovekrakow pl](https://user-images.githubusercontent.com/36385327/40587874-59c59890-61d5-11e8-965a-2603b05c8358.png)

**Comment by krystian3w** [comment]
`###modal-rodo`
`##body.modal-open:style(overflow:auto!important)` - scroll uBlock Origin / AdGuard

lub jak nie psuje:

`||lovekrakow.pl/js/jquery.cookie.js$script,first-party` - wrzucili RODO do cookies (lub bazują na wtyczce), nawet miło 🐇.
