### ISSUE TITLE
radioram.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7732]
![opera zdjecie_2018-05-27_174749_www radioram pl](https://user-images.githubusercontent.com/36385327/40587920-1ae2933e-61d6-11e8-87d9-95fa7aeaf037.png)

**Comment by krystian3w** [comment]
`###rodo` / `##.rodo`

lub jak nie psuje:

`||www.radioram.pl/js/rodo_ram.js$script`
