### ISSUE TITLE
tuwroclaw.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7733]
![opera zdjecie_2018-05-27_175135_www tuwroclaw com](https://user-images.githubusercontent.com/36385327/40587956-c21c28cc-61d6-11e8-802e-7c13485f2f52.png)

https://www.tuwroclaw.com/wiadomosci,trwa-10-edycja-wroclawskiej-bitwy-na-taniec-zdjecia,wia5-3270-41459.html
![opera zdjecie_2018-05-27_175254_www tuwroclaw com](https://user-images.githubusercontent.com/36385327/40587960-cdaf2da6-61d6-11e8-9ab7-726f2b7609e2.png)

**Comment by krystian3w** [comment]
`###pd-modal`
`##body.modal-open:style(overflow: auto!important)` - scroll uBlock Origin / AdGuard

---

`##.addv-container` - puste po reklamie, jak generuje adblocka to trzeba inaczej usunąć np.:
 
<div align="right">

_`##.addv-container:style(height:4px; width:4px)`
`##.addv-container:style(left:-9999px;position:fixed)`_

</div>
