### ISSUE TITLE
wio.waw.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7734]
![opera zdjecie_2018-05-27_175411_wio waw pl](https://user-images.githubusercontent.com/36385327/40587971-ff82f1aa-61d6-11e8-98d4-eb4c6bee21b3.png)

**Comment by krystian3w** [comment]
`##.modal-backdrop, #RODOCOOKIE`

Na Firefox nie mam tła i nie mam takiego białego pola.

**Comment by hawkeye116477** [comment]
@MajkiIT Nie widać obrazków do artykułów, ktoś narozrabiał => `@@||wio.waw.pl/static/files/gallery/$image` :smile:.

**Comment by krystian3w** [comment]
Co to za wolne bez wolnego 🤣
