### ISSUE TITLE
kreskowki.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#774]
reklama Nostale Graj Teraz Gameforge

http://panel.portmmo.com/scripts/click.php?aid=Milanos&bid=ea25a1dd&a_rid=48893be2

**Comment by MajkiIT** [comment]
nie widzę tego

**Comment by xxcriticxx** [comment]
ja tego tez nie widze

**Comment by xxcriticxx** [comment]
dzisaj tego tez nie ma :/
