### ISSUE TITLE
forum.juvepoland.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7743]
![opera zdjecie_2018-05-28_025152_www forum juvepoland com](https://user-images.githubusercontent.com/36385327/40592652-33dd0fbc-6222-11e8-9794-135382d187e1.png)

Czasami pojawia się reklama, a czasami samo "X".

**Comment by MajkiIT** [comment]
@xxcriticxx @hawkeye116477 widzicie to ?

**Comment by MajkiIT** [comment]
@krystian3w @hawkeye116477 Dziękuję
