### ISSUE TITLE
highlab.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#7744]
Resztka po reklamie po prawej

### Zrzut ekranu
![screenshot_20180528_123639](https://user-images.githubusercontent.com/19818572/40610718-cd1a503a-6273-11e8-8496-5b925aeec46d.png)

### Link bezpośredni
`http://highlab.pl/rosja-blokuje-telegram/`

**Comment by krystian3w** [comment]
`highlab.pl###custom_html-7`
