### ISSUE TITLE
portalspozywczy.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7751]
```
portalspozywczy.pl
rynekzdrowia.pl
farmer.pl
dlahandlu.pl
propertynews.pl
portalsamorzadowy.pl
rynekaptek.pl
infodent24.pl
housemarket.pl
pulshr.pl
propertydesign.pl
rynekseniora.pl
sadyogrody.pl
ckl.pl
```

![opera zdjecie_2018-05-28_153944_www portalspozywczy pl](https://user-images.githubusercontent.com/36385327/40617043-6123b136-628d-11e8-9639-d0ffae78797d.png)

**Comment by hawkeye116477** [comment]
@xMaap ckl.pl nie działa.

**Comment by krystian3w** [comment]
padło po 25 latach 🤣

**Comment by xMaap** [comment]
@hawkeye116477 ckl.pl znowu działa 
![opera zdjecie_2018-05-29_114245_www ckl pl](https://user-images.githubusercontent.com/36385327/40651234-7671d524-6335-11e8-81c6-a589173bd515.png)
