### ISSUE TITLE
dobrzemieszkaj.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7752]
![opera zdjecie_2018-05-28_154443_www dobrzemieszkaj pl](https://user-images.githubusercontent.com/36385327/40617243-12eb4096-628e-11e8-8101-f204a786f581.png)
Social
![opera zdjecie_2018-05-28_154510_www dobrzemieszkaj pl](https://user-images.githubusercontent.com/36385327/40617280-2ed00904-628e-11e8-9609-eba9f6b98998.png)
![opera zdjecie_2018-05-28_154522_www dobrzemieszkaj pl](https://user-images.githubusercontent.com/36385327/40617281-2ef3c272-628e-11e8-9fca-b5a1b9c0188d.png)

**Comment by krystian3w** [comment]
`dobrzemieszkaj.pl###axnBodyContainer`
**`dobrzemieszkaj.pl###body.nlOpen:style(overflow:auto!important)`**

---

Social:

```
##.right.box-6 > .desc
```

RSS nie ma to raczej nie trzeba się męczyć z wycinaniem i zostawianiem jakiś elementów matematycznie.
