### ISSUE TITLE
meble.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7753]
![opera zdjecie_2018-05-28_154603_www meble com pl](https://user-images.githubusercontent.com/36385327/40617328-4f6d938e-628e-11e8-865a-50a2bb8fbf55.png)
Social
![opera zdjecie_2018-05-28_154623_www meble com pl](https://user-images.githubusercontent.com/36385327/40617334-52ba2a48-628e-11e8-940a-fee2eabbbfbb.png)

**Comment by krystian3w** [comment]
`meble.com.pl###axnBodyContainer`
