### ISSUE TITLE
update filtrow 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#776]
jakos mi same filtry ostatnio nie sciagaja mam kilka maszyn  na kazdym inna ver 

v.2016042502 aktualizacja: pon, 25 kwietnia 2016, 19:30:00

**Comment by MajkiIT** [comment]
zaktualizowałem filtry. Sprawdź proszę teraz.

**Comment by xxcriticxx** [comment]
manualine jak zrobie jest ok automatycznie nie dzialaja

v.2016042902 aktualizacja: ptk, 29 kwietnia 2016, 15:20:00

**Comment by MajkiIT** [comment]
w ublocku mozesz sprawdzić kiedy pobrał filtry.
