### ISSUE TITLE
astar.czest.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#7780]
nie mam nano blocka teraz 

![capture](https://user-images.githubusercontent.com/15007183/40621710-ebdea118-626b-11e8-9503-e7a338cc49cc.PNG)

**Comment by krystian3w** [comment]
I tak by nie dał rady, jakaś nietypowa blokada.

@hawkeye116477  resztka po rodo - `##.lean-overlay` może wina braku aktualizacji filtra u mnie.

**Comment by hawkeye116477** [comment]
@krystian3w Też to mam, ale ja tam nie chowałem rodo, z tego co widzę tam jest tylko jakaś ogólna reguła blokująca skrypt z alertem ciasteczkowym.
Na antyadblock => `@@||astar.czest.pl/js/ads.js`
No i jeszcze na deser zostały resztki po reklamach dla @MajkiIT :smile:

**Comment by krystian3w** [comment]
Pewnie wykorzystali bibliotekę lub do niej dopakowali 🐇.
