### ISSUE TITLE
gokf.gda.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7786]
![opera zdjecie_2018-05-28_195506_www gokf gda pl](https://user-images.githubusercontent.com/36385327/40625165-130532d0-62b1-11e8-8efd-21fabdc0b9ba.png)

**Comment by krystian3w** [comment]
Po rodo 😉 

```
##.modal-backdrop
##body.modal-open:style(overflow:auto!important)
```

![obraz](https://user-images.githubusercontent.com/35370833/40627599-31ea068a-62c0-11e8-8db8-86c754d283c9.png) |
--- |

**Comment by hawkeye116477** [comment]
Jeszcze trzeba dać wyjątki dla tych co mają Adblocka, bo inaczej nie przescrollują strony.

**Comment by krystian3w** [comment]
> Jeszcze trzeba dać wyjątki dla tych co mają Adblocka

Tego nie umiem (nie wiem jak testować wykluczenie / odblokowanie by nie skończyło się na użyciu `,important` na końcu reguły w uzupełnieniu), o marginesie czy pozycjonowaniu statycznym raczej nie zapamiętam lub nie będę widział czy konieczne.

**Comment by hawkeye116477** [comment]
@krystian3w 
```
gokf.gda.pl#@#:not(input)[id*="cookie"]
gokf.gda.pl#@##cookies:not(body):not(html):not(.section)
gokf.gda.pl###zgoda_cookie
gokf.gda.pl##.modal-open:style(overflow: auto !important; padding-right: 0px !important;)
gokf.gda.pl##.rodo, .modal-backdrop
```
:smile:
