### ISSUE TITLE
wsensie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7788]
wsensie.pl
![opera zdjecie_2018-05-28_231544_www wsensie pl](https://user-images.githubusercontent.com/36385327/40629645-16c0fd84-62cd-11e8-9872-f48589a179ac.png)
Social
![opera zdjecie_2018-05-28_231814_www wsensie pl](https://user-images.githubusercontent.com/36385327/40629689-6adbba4e-62cd-11e8-81cd-a897ecea3e08.png)

wsensie.tv
![opera zdjecie_2018-05-28_231544_www wsensie pl](https://user-images.githubusercontent.com/36385327/40629645-16c0fd84-62cd-11e8-9872-f48589a179ac.png)
Social
![opera zdjecie_2018-05-28_231845_wsensie tv](https://user-images.githubusercontent.com/36385327/40629727-8ce5cd8c-62cd-11e8-8c57-9d338327a3fc.png)
![opera zdjecie_2018-05-28_231855_wsensie tv](https://user-images.githubusercontent.com/36385327/40629728-8d02f682-62cd-11e8-989e-fa2a84b25504.png)

**Comment by hawkeye116477** [comment]
Tutaj to dopiero się zabawili, jakieś rozmycie zrobili, ale nie wiem jak to naprawić, jak to oni zrobili, chyba bez pomocy @F4z nie obejdzie się.
