### ISSUE TITLE
automatykab2b.pl 

### ISSUE THREAD

**Issue by wmyrda** [MajkiIT/polish-ads-filter#7791]
Odwiedzając stronę [url=https://automatykab2b.pl/gospodarka/49588-automatyzacja-moze-byc-zbyt-duza-elon-musk-przeinzynierowalismy]automatykab2b[/url] pojawia się okno u góry ekranu z informacją o ciasteczkach

Do usunięcia informacji należy dodać do filtrów
||cookie.avt.pl/cookie-noscript

**Comment by krystian3w** [comment]
A może dasz się przekonać na `###cookieInfoMsgOuter:not(body):not(html)` / `###cookieInfoMsgOuter`

**Comment by hawkeye116477** [comment]
Dziwne, u mnie tego nie ma, nawet się nie łączy z tą stroną cookie.avt.pl.
