### ISSUE TITLE
haloursynow.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7798]
https://www.haloursynow.pl/artykuly/pierwszy-sondaz-przedwyborczy-na-ursynowie-kto-wygrywa-kto-przegrywa,9775.htm
![opera zdjecie_2018-05-29_124620_www haloursynow pl](https://user-images.githubusercontent.com/36385327/40654351-5a287dc4-633e-11e8-9c5e-8e51e3349ed0.png)
![opera zdjecie_2018-05-29_124634_www haloursynow pl](https://user-images.githubusercontent.com/36385327/40654352-5a49a062-633e-11e8-8eaa-7a6f296b3b0b.png)

**Comment by krystian3w** [comment]
`##.baner > span` :question:
