### ISSUE TITLE
URGENT possible bug in adblock.txt

### ISSUE THREAD

**Issue by sintell** [MajkiIT/polish-ads-filter#7802]
Hello,
I want to report a possible error in https://github.com/MajkiIT/polish-ads-filter/blob/38771e2708b1e34eb1b69f2f91cc508075536cca/polish-adblock-filters/adblock.txt#L4096

Is it intended to block any request that contains _wss_ or _proxy_ as it part?

Currently, this rule applied to such requests:
https://i.hh.ru/jsbuild/bloko/blocks/compositeSelection/tagListProxy.h4b93.js
https://i.hh.ru/jsbuild/bloko/blocks/compositeSelection/nestedTagListProxy.ha80b
https://i.hh.ru/jsbuild/bloko/blocks/compositeSelection/treeSelectorPopupProxy.hca40.js
https://i.hh.ru/jsbuild/bloko/blocks/compositeSelection/suggestProxy.ha97c.js

The _proxy_ word there is used as JS file name.

My guess is that this rule is missing `domain` part in it.

**Comment by xxcriticxx** [comment]
@sintell i think this was intended for crypto miners

cc @MajkiIT

**Comment by sintell** [comment]
@xxcriticxx the main question is whether it is intended to block any request that has a word proxy in it or not, regardless of the domain

**Comment by xxcriticxx** [comment]
@sintell i believe that was that was @MajkiIT intentions to block both `proxy` and `wss`

**Comment by MajkiIT** [comment]
@sintell Thanks, I removed this rule

**Comment by sintell** [comment]
Thanks a lot :)
