### ISSUE TITLE
finanse.wp.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#7803]
Reklama na górze i na bokach strony
![image](https://user-images.githubusercontent.com/29756590/40664578-850ef56e-635b-11e8-993f-ad01713dd439.png)

**Comment by HateAds** [comment]
Mały update reklamy zniknęły teraz filtry mam aktualne. Nie wiem czemu wcześniej były. 
Możecie sprawdzić czy u Was są reklamy ? Jak nie to issue do zamknięcia.

**Comment by hawkeye116477** [comment]
@HateAds Nie ma, można zamknąć.
