### ISSUE TITLE
wpolityce.pl

### ISSUE THREAD

**Issue by wmyrda** [MajkiIT/polish-ads-filter#7805]
Pojawia się popup z RODO, który znika po dodaniu

###TOS-POPUP

**Comment by hawkeye116477** [comment]
@wmyrda Ok. Może ten Privoxy po prostu nie przyjmuje reguł po przecinku.
`wpolityce.pl,wgospodarce.pl,wpolsce.pl##.rhododendron-popup, .rhododendron-popup-overlay`
Bo tutaj jest ##.rhododendron-popup i ##.rhododendron-popup-overlay, tyle tylko, że to jest taka skrócona reguła, dwa w jednym, AdGuard na Chrome też z tym miewał problemy, teraz już chyba od najnowszej wersji jest ok.
Oprócz tego jest też oczywiście `/rhododendron/css/rhododendron-popup.css$domain=wpolityce.pl|wgospodarce.pl|wpolsce.pl`, bo bez tego scroll by nie działał :smile:.

**Comment by wmyrda** [comment]
Akurat tego rodzaju reguły skrypt konwertujący tworzy prawidłowo jak i miało miejsce w tym przypadku odpowiedni plik .css w stosownym miejscu dla każdej ze stron powstał i oba zawierały `.rhododendron-popup` i ` .rhododendron-popup-overlay`. Nie wiem może mu ta spacja przed drugim wpisem nie pasuje, albo w jakiś sposób kłuci się z jakąś inną regułą. Będę weryfikował i jak coś znajdę dam znać.

**Comment by wmyrda** [comment]
Co ustaliłem na pewno to że żadna spacja w pliku CSS przeglądarce nie przeszkadza. Problem leży w tym, że patrząc po logach apache przeglądarka z jakiś powodów nie zawsze się pyta o odpowiedni plik CSS. Nie mogę tylko wyłapać zależności dlaczego tak się dzieje. Np na Chrome (Android, Windows, Linux) pobiera, a na Firefox (Windows, Linux) bez względu na wy/włączenie dodatków czy ustawienia proxy bądź ich brak już nie.
Także znając życie chodzi o jakąś głupotę, ale na pewno ani nie o filtr z listy jaki jego przekonwertowaną postać.

**Comment by wmyrda** [comment]
Najbardziej prawdopodobna przyczyna dla której serwer apache nawet nie otrzymuje zapytań wygenerowanych przez przeglądarki
"most browsers will not accept unencrypted redirects as response for https:// requests anyway:"
https://sourceforge.net/p/ijbswa/actionsfile-feedback/931/
Zobaczę jak się uda z ze stroną lokalną po HTTPS

**Comment by wmyrda** [comment]
Dokładnie tak jak napisałem w poprzednim poście kwestia tkwiła w sposobie działania przeglądarki. Więcej na ten temat w wątku na temat privoxy https://github.com/MajkiIT/polish-ads-filter/issues/579
