### ISSUE TITLE
goodie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7807]
![opera zdjecie_2018-05-29_220046_goodie pl](https://user-images.githubusercontent.com/36385327/40682391-e0eebfe2-638b-11e8-831c-2989d2ca53ee.png)

**Comment by krystian3w** [comment]
`goodie.pl##.bp_br`

**Comment by hawkeye116477** [comment]
@krystian3w To dobrze, a tak generalnie to nie musisz wstawiać alfabetycznie, skrypt i tak potem to sortuje. Muszę tylko naprawić skrypt dla Travisa, bo ostatnio coś się zepsuł i sortował to, czego nie powinien, dlatego na razie Travis jest wyłączony, a tak to z automatu wszystko robi :smile:.
