### ISSUE TITLE
rynekzdrowia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7820]
Nie działa scrollowanie strony.

**Comment by MajkiIT** [comment]
`rynekzdrowia.pl#@#.rodo`

**Comment by hawkeye116477** [comment]
@MajkiIT Trochę słaby pomysł, nie poddajemy się, trzeba cssem po prostu się pobawić i ustawić overflow na auto, tylko najpierw przenieść tą regułę z rodo na drugą listę only for uBO and AG :smile:.
`##.windowOpen:style(overflow: auto !important;)`

**Comment by krystian3w** [comment]
Ale przynajmniej wiemy co wycięło scroll to już coś 😉
