### ISSUE TITLE
azorek.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7824]
![opera zdjecie_2018-05-30_104510_www azorek pl](https://user-images.githubusercontent.com/36385327/40709537-970af8bc-63f6-11e8-95c4-1c56684d1bba.png)

**Comment by hawkeye116477** [comment]
To już do zamknięcia, ale niestety niechcący najwyraźniej wstawiłem parę spacji i komentarz nie zadziałał :smile:.
