### ISSUE TITLE
musiclovers.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7833]
![opera zdjecie_2018-05-30_234642_musiclovers pl](https://user-images.githubusercontent.com/36385327/40749313-d2a6dbda-6463-11e8-8296-87ffd6343bac.png)
![opera zdjecie_2018-05-30_234651_musiclovers pl](https://user-images.githubusercontent.com/36385327/40749314-d2c5222a-6463-11e8-8521-00c15bbd0c85.png)
![opera zdjecie_2018-05-30_234701_musiclovers pl](https://user-images.githubusercontent.com/36385327/40749316-d2e1c3ee-6463-11e8-9b10-a47a90b9a947.png)

http://musiclovers.pl/the-kvb-nowy-singl-i-koncerty-w-polsce/
![opera zdjecie_2018-05-30_234752_musiclovers pl](https://user-images.githubusercontent.com/36385327/40749329-e926859a-6463-11e8-9175-8393f9709704.png)
![opera zdjecie_2018-05-30_234800_musiclovers pl](https://user-images.githubusercontent.com/36385327/40749330-e946605e-6463-11e8-8b00-1c5a6ea74347.png)

**Comment by krystian3w** [comment]
`##.wpb_text_column:nth-of-type(3) > .wpb_wrapper` - nagłówek

`##.td-header-sp-recs` lub `##.td-header-rec-wrap` - boczna

`##.wpb_content_element` - dół i boczna jednocześnie

`##.td-a-rec` - w artykłach

**Comment by krystian3w** [comment]
A sieciowo nawet łatwiej:

```
||musiclovers.pl/wp-content/uploads/*/reklamakonoba.gif$image
||musiclovers.pl/wp-content/uploads/*/RO-x-KONOBA-Plakat-*.jpg$image
```
aż nie zmienią nazw plików,
