### ISSUE TITLE
goldenline.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#7837]
`https://www.goldenline.pl/grupy/Komputery_Internet/seo/text-indent-9999px-czym-to-mozna-zastapic,3045330/`

> ![obraz](https://user-images.githubusercontent.com/35370833/40781002-9cd7c614-64da-11e8-8528-698791374649.png) |
> --- |

`##.modal-backdrop, #profiling-agreement`

**Comment by hawkeye116477** [comment]
Ok, w dev już jest, na razie tylko tam, czekam aż więcej się pojawi, bo nie opłaca się dla tylko 1 strony robić final update :smile:.

**Comment by krystian3w** [comment]
W sumie to ich forum nie przeglądam przez ukrywanie treści dla niezalogowanych. A to znalazłem, bo chciałem sobie przypomnieć co robił ten `text-indent`.
