### ISSUE TITLE
crowdmedia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7840]
![opera zdjecie_2018-06-01_042840_crowdmedia pl](https://user-images.githubusercontent.com/36385327/40817763-6b9e5804-6554-11e8-8dfc-c79d5eacd25f.png)

**Comment by krystian3w** [comment]
`#menu-herald-social-1`, ciekawe co wycina 2 - ze stopki lub zmienili numer?
