### ISSUE TITLE
apra.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7847]
apra.pl
![opera zdjecie_2018-06-02_071740_www apra pl](https://user-images.githubusercontent.com/36385327/40871071-1296a84c-6635-11e8-9511-5e4911bc8ad0.png)

agropolska.pl
![opera zdjecie_2018-06-02_071856_www agropolska pl](https://user-images.githubusercontent.com/36385327/40871089-3bc2721e-6635-11e8-9139-407fd1bb9d28.png)
![opera zdjecie_2018-06-02_071933_www agropolska pl](https://user-images.githubusercontent.com/36385327/40871098-70956b72-6635-11e8-92cf-0bf89f7f6abe.png)
![opera zdjecie_2018-06-02_071956_www agropolska pl](https://user-images.githubusercontent.com/36385327/40871099-70b45f14-6635-11e8-8a71-3925cac5990a.png)
![opera zdjecie_2018-06-02_072008_www agropolska pl](https://user-images.githubusercontent.com/36385327/40871100-70d2edda-6635-11e8-99ad-ae41c94c5241.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 masz te reklamy ?

**Comment by xxcriticxx** [comment]
`||www.agropolska.pl/gfx/agropolska/pl/media/*/1/*.*$image`

**Comment by xxcriticxx** [comment]
na podstronach jest wiecej
```
agropolska.pl##[href="http://www.agroplast.pl/"]
agropolska.pl##[href="http://www.josera-agrar.pl/"]
agropolska.pl##[href="http://www.blattin.pl/produkty,kategoria,7,dodatki_do_zakiszania.html"]
```
