### ISSUE TITLE
kinoman.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#786]
http://kinoman.tv/film/jauja

strony podpiente po play button

https://www.searchincognito.com/landing/aff?implementation_id=aff65-pp&offer_id=399&aff_id=65&source=e7ac41c1-e6b8-4c14-9be1-415a4ee1cff4&aff_sub=wA8GJHBU0H0BH6KS06NURQ4J

**Comment by MajkiIT** [comment]
masz aktualne filtry?

**Comment by xxcriticxx** [comment]
napewno nie v.2016050302 aktualizacja: wt, 3 maj 2016, 16:40:00

**Comment by xxcriticxx** [comment]
automatycznie sie nie sciagaja musze manualnie teraz mam 

v.2016050502 aktualizacja: czw, 5 maj 2016, 20:40:00

**Comment by MajkiIT** [comment]
I masz na kinoman to o czym pisałes?

**Comment by xxcriticxx** [comment]
opdalam stone i testuje teraz

**Comment by xxcriticxx** [comment]
ok wszystko jest super! thx

**Comment by MajkiIT** [comment]
Ok dzięki.
