### ISSUE TITLE
autogielda.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#7873]
Popup po cookies

**Comment by krystian3w** [comment]
`##.modal-backdrop`

mam nadzieje, że nie namieszałem na szablonach dev za bardzo.

**Comment by hawkeye116477** [comment]
@krystian3w Jest ok, dobrze się spisujesz :smile:
Nawet tak dobrze, że może cię przyjmiemy jako pełnoprawnego członka PFT, ale najpierw muszę pogadać z całym zarządem spółki :smile:.

**Comment by hawkeye116477** [comment]
@krystian3w  Pogadałem z zarządem i mówią, że przyjmujemy ciebie na praktyki na razie do końca września :smile:. Więc wysłałem zaproszenie => `https://github.com/PolishFiltersTeam`.
