### ISSUE TITLE
weather.com/pl-PL

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#7877]
RODO

**Comment by hawkeye116477** [comment]
To samo co na wunderground najwyraźniej. Tej samej firmy strona, ciekawe na co im 2 strony od pogody :smile:.

**Comment by xxcriticxx** [comment]
wecej reklam :)

**Comment by hawkeye116477** [comment]
@krystian3w Są 2 okienka, jedno duże i na to działa truste i drugie małe i na tamto małe działa lite-msg.

**Comment by krystian3w** [comment]
Dużego u mnie nie ma, może efekt użycia Cookiemonster.

**Comment by hawkeye116477** [comment]
@krystian3w Przecież można to schować kosmetycznymi regułami :smile:
`##.truste_overlay, .truste_box_overlay`
