### ISSUE TITLE
wzp.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7880]
RODO + social
![opera zdjecie_2018-06-04_104707_wzp pl](https://user-images.githubusercontent.com/36385327/40907640-c0959786-67e4-11e8-8d55-7505ed80af87.png)

**Comment by krystian3w** [comment]
`###myrodoinfo` - pop-up RODO.

`###rslider-face` - panel z lewej FB,
`###rslider-write` - panel kontaktowy, nie wiem co z nim zostawię dla innych na razie.
