### ISSUE TITLE
polska.travel

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7883]
![opera zdjecie_2018-06-04_105610_polska travel](https://user-images.githubusercontent.com/36385327/40908213-5fe38342-67e6-11e8-843d-14cc65088325.png)

Nie wiem, ale w niektórych miejscach mi się obrazki nie ładują np.:
https://polska.travel/pl/regiony/dolnoslaskie
https://polska.travel/pl/regiony/lubuskie
https://polska.travel/pl/regiony/malopolskie
https://polska.travel/pl/regiony/mazowieckie

slaskie.travel
![opera zdjecie_2018-06-04_110059_www slaskie travel](https://user-images.githubusercontent.com/36385327/40908292-9b5a836c-67e6-11e8-8a15-08a8c5a72b8f.png)

swietokrzyskie.pro
![opera zdjecie_2018-06-04_110135_www swietokrzyskie pro](https://user-images.githubusercontent.com/36385327/40908325-aee840cc-67e6-11e8-8123-485050628783.png)

grafithotel.pl
![opera zdjecie_2018-06-04_110235_www grafithotel pl](https://user-images.githubusercontent.com/36385327/40908376-d5b7716e-67e6-11e8-9dce-0dafc016e388.png)

mazury.travel - pozostałość po social
![opera zdjecie_2018-06-04_110320_www mazury travel](https://user-images.githubusercontent.com/36385327/40908404-f3c96b76-67e6-11e8-8ff7-b9a7e83dabc0.png)

**Comment by krystian3w** [comment]
`polska.travel###icons`
`slaskie.travel##.social-media-widget-display, .widget-LikeBox-slaskietravel`
`swietokrzyskie.pro##.hdr_links1 > li:nth-of-type(3), .hdr_links1 > li:nth-of-type(4)`
`grafithotel.pl##.facebookSlide`
`mazury.travel##.social-rss.social-add-icon`

---

### _`mazury.travel`_:
 do tego mam dylemat bo tam jest guzik RSS (Fanboy Social wycina ich duszka CSS - `/social_media_`, przez co go nie widać) 

> ![image](https://user-images.githubusercontent.com/35370833/40912268-5df782b2-67f1-11e8-94fd-7929a52e949a.png) |
> --- |


### _`świętokrzyskie.pro`_:
 wrzucę testowo obliczanie `1n+3`

---

Nie wiem jakie grafiki się nie ładują, więc nie pomogę dodać/zapropnować wyjątków.
