### ISSUE TITLE
nowymarketing.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#7884]
Blokada archiwalnych artykułów, np tu : https://nowymarketing.pl/a/11746,w-web-push-encyklopedia-marketingu?_r=1

**Comment by hawkeye116477** [comment]
@blocker999 A bilet gdzie masz? Bez bileciku nie wpuszczają :smiley:. Bilet w tym przypadku to zapis do newslettera, więc to chyba raczej do naszych Polskich Filtrów EI :smile:.

**Comment by blocker999** [comment]
@hawkeye116477 newsleter tak ale blur to chyba tu, zresztą niewiem.

**Comment by krystian3w** [comment]
To da się odCCS-ować w uBlock Origin / AdGuard.

```
nowymarketing.pl##.group.accessInfoBox
nowymarketing.pl##.blured:style(filter: none !important)
```

**Comment by hawkeye116477** [comment]
No nie wiem, niby po zapisie newslettera odblokowują artykuł, więc ja bym powiedział, że raczej oba elementy kwalifikują się do EI, zresztą zobaczymy co @MajkiIT powie :smile:

**Comment by MajkiIT** [comment]
@hawkeye116477 jak chcesz to bierz :D

**Comment by hawkeye116477** [comment]
@MajkiIT Tak właściwie ja już to wcześniej dodałem, ale jeżeli ty chcesz, to wtedy usunę, by nie dublować :smile:.

**Comment by MajkiIT** [comment]
@hawkeye116477 Dziękuję . Niech zostaje u ciebie.
