### ISSUE TITLE
budownictwo.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7890]
RODO
![opera zdjecie_2018-06-05_030536_budownictwo pl](https://user-images.githubusercontent.com/36385327/40949233-61e8be96-686d-11e8-8b4c-a2c651bc134e.png)

Cookies
eniro.pl
eniroweb.pl
amawid.pl

![opera zdjecie_2018-06-05_030732_www eniro pl](https://user-images.githubusercontent.com/36385327/40949288-9f1f0946-686d-11e8-9f57-a1f4b0be0e30.png)

**Comment by krystian3w** [comment]
`budownictwo.pl###rodoLayer, .modal-backdrop`
`budownictwo.pl##.modal-open:style(overflow: auto !important;)`

`eniro.pl,eniroweb.pl,amawid.pl###kb-container` - weebly z własną domeną :smile:
