### ISSUE TITLE
naszpradnik.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7896]
![opera zdjecie_2018-06-05_032349_naszpradnik pl](https://user-images.githubusercontent.com/36385327/40949773-e48bc1de-686f-11e8-8663-2e87ee111e78.png)

**Comment by krystian3w** [comment]
`naszpradnik.pl##.menu-social-fb`

`naszpradnik.pl##.menu-social-env`

`naszpradnik.pl##.menu-social-feed`
