### ISSUE TITLE
gieldarolna.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7897]
gieldarolna.pl
frsih.pl
![opera zdjecie_2018-06-05_045001_www gieldarolna pl](https://user-images.githubusercontent.com/36385327/40952596-248982ba-687c-11e8-9c8a-f178e1d9c3d6.png)

**Comment by krystian3w** [comment]
`gieldarolna.pl##.open.rodo`

`frsih.pl##.open.rodo`
`frsih.pl##.windowOpen:style(overflow: auto !important;)`
`frsih.pl##.stickSocial`
