### ISSUE TITLE
mowimyjak.se.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7899]
![opera zdjecie_2018-06-05_051116_mowimyjak se pl](https://user-images.githubusercontent.com/36385327/40953187-f3ee61ae-687e-11e8-8bf4-8f9d656ff17e.png)

http://sklep.grupazpr.pl
![opera zdjecie_2018-06-05_051221_sklep grupazpr pl](https://user-images.githubusercontent.com/36385327/40953214-0c247cc2-687f-11e8-9a1c-252eb31c50a0.png)

**Comment by krystian3w** [comment]
`mowimyjak.se.pl##.butony > a:nth-child(3), .butony > a:nth-child(4)`
`sklep.grupazpr.pl##.tab_promo`
