### ISSUE TITLE
zdrowie.tvn.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7902]
https://zdrowie.tvn.pl/a/nefropatia-przyczyny-przebieg-i-leczenie-choroby-nerek
![opera zdjecie_2018-06-05_052946_zdrowie tvn pl](https://user-images.githubusercontent.com/36385327/40953776-7aed91d2-6881-11e8-959a-bb5d0a9cab7e.png)

**Comment by krystian3w** [comment]
`##.social-btn--fb`
