### ISSUE TITLE
vod.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#7904]
Strona: https://vod.pl/programy-onetu/onet-rano-wlodzimierz-czarzasty-406/71fgvqy#0
Błąd:
![20180605-001-screenshoot](https://user-images.githubusercontent.com/9846948/40965610-7db94032-68ae-11e8-8869-2504b17ebccd.png)
Fix:
```
vod.pl##.v_shortShare, .v_shortTwShare
vod.pl##.v_shortShare, .v_shortFbShare
```

ADG for Windows Beta

**Comment by MajkiIT** [comment]
@F4z mam poprawić czy ty to zrobisz u siebie?

**Comment by krystian3w** [comment]
Mnie buttony wycina i wideo leci, nie ruszam bo nie ogarniam.

**Comment by FadeMind** [comment]
@MajkiIT @F4z  dla jasności:

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 1803 x64
Browser:                            | Chrome Stable x64
AdGuard version:                    | **6.3.974.3223** beta
Stealth mode: | disabled

| Filters enabled |
|-----------------|
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| EasyList Polish 
| I don't care about cookies
| KAD - fraud/scam 
| Malware Domains List
| NoCoin Filter List
| Peter Lowe's list 
| Polish Adguard Suplement
| Polish Annoyances Adguard Suplement
| Polish Annoyances Main 
| Polish Cookies Filter
| Polish Main
| Polish Social

**Comment by F4z** [comment]
Chodzi tylko o te przyciski społecznościowe, czy też o coś innego?
Jeśli tylko o te przyciski, to ta reguła z listy `Polskie Filtry Społecznościowe` powinna to ukrywać (i u mnie ukrywa):
`vod.pl##.v_shortTwShare, .v_shortFbShare`

**Comment by krystian3w** [comment]
U mnie właśnie też tyle, że nie używam w tej chwilo AdGuarda dla systemu.

**Comment by FadeMind** [comment]
@F4z  chodzi tylko o te przyciski (TW i FB). Pozdrawiam ;)

**Comment by F4z** [comment]
A jak dodasz tę regułę do filtrów użytkownika to działa?
`vod.pl##.v_shortTwShare, .v_shortFbShare`

Pozdrawiam :)

**Comment by xxcriticxx** [comment]
jak sie pozdrawiamy to ja tez pozdrawiam

**Comment by FadeMind** [comment]
@F4z Twoja reguła działa poprawnie. przyciski FB i TW są blokowane.

**Comment by krystian3w** [comment]
Spróbuj wymusić więc aktualizacje filtrów.

https://github.com/MajkiIT/polish-ads-filter/blob/06511869830fd585e00af8f90d6965d6b8a7c7d3/adblock_social_filters/adblock_social_list.txt#L2084

Od 27 maja na liście. Chyba, że ta lista nie jest używana w AdGuardzie.

**Comment by FadeMind** [comment]
@krystian3w @MajkiIT w Adguard używany jest taki nagłówek:

![20180605-002-screenshoot](https://user-images.githubusercontent.com/9846948/40974310-793afba4-68c7-11e8-9099-ebef56a316a4.png)
Tych reguł tam nie ma:
![20180605-003-screenshoot](https://user-images.githubusercontent.com/9846948/40974372-a994dad6-68c7-11e8-996e-7945d8db4ac4.png)
Dodam, że **Polish Annoyances Adguard Suplement** dodałem ręcznie (jako prywatną listę), ponieważ adguard nie aktualizuje listy z oryginalnego adresu > `https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB_uBlock_AdGuard.txt` (nie jest jeszcze obecna w dostępnych), podobnie jak suplement do Polish Social

**Comment by F4z** [comment]
To wygląda jakbyś miał nieaktualną listę.
W AdGuardzie jest dostępna lista `Polskie Filtry Społecznościowe` i tam jest ta reguła.
<details><summary>Obrazek</summary>

![image](https://user-images.githubusercontent.com/11742596/40974794-fd078a6e-68c8-11e8-984f-06ef46537841.png)

</details>

**Comment by FadeMind** [comment]
@F4z mam aktywną tę listę i jeszcze nie mam tej aktualizacji (adguard nie widzi na serwerach nowszej wersji niż 2.0.0.47 
![20180605-006-screenshoot](https://user-images.githubusercontent.com/9846948/40975126-2e81b7f8-68ca-11e8-8740-da47de2f17c4.png)

**Comment by F4z** [comment]
Na serwerze jest wersja z wczoraj - https://filters.adtidy.org/windows/filters/221.txt i tam jest ta reguła.
U Ciebie jest wersja z 5 marca.
Może spróbuj usunąć tę listę, potem dodaj ponownie i zaktualizuj?

**Comment by FadeMind** [comment]
@F4z  już to wykonałem przed poprzednim moim postem. Pobiera listę:
```
! Expires: 2 days
! Expires: 2 days (update frequency)
!
! Checksum: qgYc7AMNdBzg58LkNJzTaA
! Title: Polskie Filtry Społecznościowe
! Polish Social Filters
! Codename: Social
! Description: Filtry ukrywające i blokujące elementy sieci społecznościowych, tj. widgety, wyskakujące okienka i inne elementy społecznościowe.
! Required: Do poprawnego działania wymagana jest lista Fanboy's Social Blocking List!
! Collaborators: blocker999, hawkeye116477, xxcriticxx, KonoromiHimaries
! Homepage: https://www.certyficate.it/
! OriginalVersion: 201803052133
! Last modified: 05 Mar 2018 21:33:49 UTC+01
! Checksum: cW+zc2Ij1q1mm6x97sPT1g
! Title: Polski social filtr
! Description: Polski social filtr
! Version: 2.0.0.36
! TimeUpdated: 2018-03-05T21:01:47+00:00
```

**Comment by F4z** [comment]
Nie mam pojęcia dlaczego tak się dzieje, u mnie dostępna jest wersja z wczoraj.
Może napisz do "supportu", bo ja tu już raczej nic nie wymyślę.
Ewentualnie możesz zainstalować najnowszą wersję "nightly" i sprawdzić czy tam działa.

**Comment by FadeMind** [comment]
@F4z zobaczę za godzinę jak sprawy się potoczą. To kwestia usrtawień
![20180605-008-screenshoot](https://user-images.githubusercontent.com/9846948/40976381-4c53ea72-68ce-11e8-9b8a-2d237fb952f3.png)

Wcześniej miałem ustawienie domyślne (pobiera nową listę jak tylko lista wygaśnie - expired). 
Teraz wymusiłem aktualizację co godzinę. Pozdrawiam. Pozostanę w gałęzi BETA. ;)

**Comment by FadeMind** [comment]
@F4z dopiero dzisiejsze aktualizacje automatyczne pobrały najnowszą wersję
