### ISSUE TITLE
emt-systems.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7913]
![opera zdjecie_2018-06-06_002855_emt-systems pl](https://user-images.githubusercontent.com/36385327/41006146-a4764798-6920-11e8-9e54-fd073fcc0cbf.png)

Social
![opera zdjecie_2018-06-06_002949_emt-systems pl](https://user-images.githubusercontent.com/36385327/41006196-c63466d0-6920-11e8-9114-d3e930bfc5f6.png)
![opera zdjecie_2018-06-06_003022_emt-systems pl](https://user-images.githubusercontent.com/36385327/41006206-d369e3d4-6920-11e8-92e4-7ebe8d15fded.png)

**Comment by krystian3w** [comment]
`###rodoBG`

---

`emt-systems.pl##.top-main > li:nth-of-type(13), .social.footer-menu`
