### ISSUE TITLE
tuzdrowie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7914]
RODO
![opera zdjecie_2018-06-06_003729_www tuzdrowie pl](https://user-images.githubusercontent.com/36385327/41006448-e0979e92-6921-11e8-8236-23b6b5b862e8.png)

Social
![opera zdjecie_2018-06-06_003827_www tuzdrowie pl](https://user-images.githubusercontent.com/36385327/41006469-f68d186c-6921-11e8-9f11-316ca409bbb4.png)

**Comment by krystian3w** [comment]
`tuzdrowie.pl##.modal-open:style(overflow: auto !important; padding-right: 0px !important;)`
`tuzdrowie.pl###popupModal, .modal-backdrop`

---

`tuzdrowie.pl##.tr-facebook`
