### ISSUE TITLE
medpolonia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7915]
RODO + social
![opera zdjecie_2018-06-06_003940_www medpolonia pl](https://user-images.githubusercontent.com/36385327/41006530-359ac914-6922-11e8-9e97-4db67a64a37e.png)

**Comment by krystian3w** [comment]
`medpolonia.pl###bannerPopup`

---

`medpolonia.pl##.set-abs.helper-yt`
