### ISSUE TITLE
goldenline.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7917]
https://www.goldenline.pl/firma/centrum-szkolen-inzynierskich-emt-systems/
Nie działa scrollowanie strony.

**Comment by krystian3w** [comment]
`##.modal-open:style(overflow: auto !important;)`

Pewnie trzeba będzie jeszcze dodać wyjątek dla adblocka lub poszukać jaki CSS/JS można niegroźnie wyciąć do usunięcia RODO.

**Comment by hawkeye116477** [comment]
`||assets.goldenline.io/assets/user/profilingAgreement.*.js`
