### ISSUE TITLE
bezwypadkowy.net

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7922]
https://www.bezwypadkowy.net/newsy
![opera zdjecie_2018-06-06_072506_www bezwypadkowy net](https://user-images.githubusercontent.com/36385327/41018600-e138cdb0-695a-11e8-8b3d-12da68582fa1.png)
![opera zdjecie_2018-06-06_072528_www bezwypadkowy net](https://user-images.githubusercontent.com/36385327/41018602-e15add10-695a-11e8-8df0-850eff6adef0.png)
![opera zdjecie_2018-06-06_072701_www bezwypadkowy net](https://user-images.githubusercontent.com/36385327/41018633-0b1c500c-695b-11e8-87a1-c034928332a2.png)

**Comment by krystian3w** [comment]
`bezwypadkowy.net##.fa-google-plus-square, .fa-facebook, .fa-twitter, .jf_sidebuttons, .rt-grid-3:nth-of-type(3)`
