### ISSUE TITLE
panoramafirm.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#7935]
https://panoramafirm.pl/wielkopolskie,,pozna%C5%84,stare_miasto,pl._andersa,7/recruitme_adrian_gorny-zfbdne_fph.html

![capture](https://user-images.githubusercontent.com/15007183/41071429-9a85f63e-69c5-11e8-93fd-31223a2ff9b2.PNG)

**Comment by xxcriticxx** [comment]
cc @lashus

**Comment by MajkiIT** [comment]
```
panoramafirm.pl###rodoLayer
panoramafirm.pl##.in.fade.modal-backdrop
```

**Comment by krystian3w** [comment]
gdzieś to już jest wystarczy dopisać domenę

**Comment by MajkiIT** [comment]
@krystian3w wiem, wiem, ale jakoś mi się tak wkleiło :P
