### ISSUE TITLE
wp.pl atakuje

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#794]
reklama 

lidl
empire graj
4f tshirts

**Comment by MajkiIT** [comment]
Ja nic nie widzę ..

**Comment by xxcriticxx** [comment]
filtry mam z 5/8 jest cos nowszego?

v.2016050801 aktualizacja: nie, 8 maj 2016, 08:20:00

**Comment by xxcriticxx** [comment]
zrobilem purche cache sciagnelem nowe filtry i jest ok
