### ISSUE TITLE
pragma.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7946]
Social
![opera zdjecie_2018-06-08_101315_www pragma pl](https://user-images.githubusercontent.com/36385327/41146749-965405d4-6b04-11e8-815e-02d6698540bb.png)

**Comment by krystian3w** [comment]
`##.visible-lg:nth-of-type(1)` / `##.social`

---

@hawkeye116477  jest sens łączyć w jedno "`##.social`" (tylko tam gdzie nie ma dopisanych innych elementów), z dwa razy dopisałem, a tak z 8 wisi sobie osobno - "redundancja".

**Comment by hawkeye116477** [comment]
@krystian3w Trochę tego jest pozostawione pojedyńczo z social, raczej szkoda czasu szukać teraz i to dodawać w jedno, ale jak chcesz to możesz połączyć, ja to zostawię :smile:
