### ISSUE TITLE
abcalkoholu.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7956]
![opera zdjecie_2018-06-08_140516_www abcalkoholu pl](https://user-images.githubusercontent.com/36385327/41157159-ff6957e8-6b24-11e8-8845-9998b5c43297.png)

**Comment by krystian3w** [comment]
Age wall

**Comment by krystian3w** [comment]
`abcalkoholu.pl#@#.cookielaw` - Nadpobudliwość Cookiemonster / Fanboy Annoyance.

Jak było mówione nie wspieramy.

**Comment by RikoDEV** [comment]
@krystian3w na Adguard’s Annoyance List też strona nie działa

**Comment by RikoDEV** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/17780

**Comment by RikoDEV** [comment]
Adguard naprawił w swoich filtrach https://github.com/AdguardTeam/AdguardFilters/commit/14361af55b8413d97d394c4301956ad5a9e37447

**Comment by krystian3w** [comment]
Też na podstawie tamtej listy nie budujemy nic - jedynie polecana jako bardziej przyjazna bo nie wycina np. RSS.

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/b43988ad38842f7b2fb214e31bc525e33a574cb6 - możemy zamknąć a @xMaap wymusić aktualizacje Fanboys Annoyance List.
