### ISSUE TITLE
euro.com.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#7965]
Zniknęły promocyjne oferty Days of Play w Euro.
`https://www.euro.com.pl/gry-playstation-4/sony-uncharted-zaginione-dziedzictwo.bhtml`
`euro.com.pl#@#.banners-header`

**Comment by hawkeye116477** [comment]
No tak, o to chodziło :smile:.

**Comment by krystian3w** [comment]
Niech zrobią sobie zakładkę do menu poziomego lub pionowego i problem "z głowy".
