### ISSUE TITLE
neosite.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#7967]
Nie widać autora artykułu, daty publikacji i nie przegap. Co ciekawe, problem u mnie występuje jedynie na 
Waterfoksie/Firefoksie. Na Vivaldim jest ok.
`https://neosite.pl/news/64242/days-of-play-promocja-na-gry-w-sklepach.html`

Waterfox
![screenshot_20180608_232342](https://user-images.githubusercontent.com/19818572/41181705-099d1ddc-6b73-11e8-80d1-4b4175222768.png)

Vivaldi
![screenshot_20180608_232352](https://user-images.githubusercontent.com/19818572/41181715-12091a48-6b73-11e8-880b-c4b4d6e0e0e2.png)

Tak chyba powinno być git:
```

!#if env_firefox
neosite.pl##.kokpit:style(padding: 0 !important;)
!#endif
```

**Comment by krystian3w** [comment]
Nie chcę nic mówić ale mam inny layout lub popsułeś stronę 😉

**Comment by krystian3w** [comment]
Nie wiem czemu ale coś wycina mi przycisk layoutu i muszę mocno zoomować stronę by się pojawił w wersji mobilnej.

Próbowałem bawić się zoomem i mi nie opada wyszukiwarka - może neosite nas czyta i poprawiło szablon, bo zauważyli, że to nie problem reklam.

**Comment by hawkeye116477** [comment]
@krystian3w Ja tam nadal mam ten problem i moja reguła pomaga :smile:.

**Comment by krystian3w** [comment]
A jakie listy, bo nawet cofnąłem do domyślnych uBO i na FX60 / 61 mam OK.

> ![obraz](https://user-images.githubusercontent.com/35370833/41192186-a68336c2-6bfa-11e8-95da-cce30287b9c8.png)


Może to problem z serii "GNU/Linux - no to rasizm".

**Comment by hawkeye116477** [comment]
@krystian3w Bez uBO wyszukiwarka też opada, tyle, że wtedy widać te napisy. 
A jaką rozdzielczość masz? Bo możesz masz wyższą i dlatego problemu nie widać.
Listy generalnie wszystkie uBO prócz experimental i Annoyances, Adblock Warning, EasyList, Malware domains, Spam404, Fanboy's Social, Peter Lowe's, Polskie Reklamowe, Kad, Polskie EI, Polskie Społecznościowe.

**Comment by krystian3w** [comment]
1366 x 768 - bawiłem się suwakiem / zoomem / trybem responsywnym.

![obraz](https://user-images.githubusercontent.com/35370833/41192338-6b56a604-6bfc-11e8-81d3-1a0630f6b562.png)

**Comment by hawkeye116477** [comment]
@krystian3w No to rozdzielczość trochę inna, ja 1280x1024. Ale sprawdziłem na Windzie i tam jest ok... Więc wychodzi na to, że to coś nie halo z Linuksowym Firefoksem...

**Comment by hawkeye116477** [comment]
@krystian3w Raczej nie chodzi o forki/FF56, bo sprawdzałem na Windzie też na Waterfoksie. A i na Linuksie zmieniałem useragent na FF Windows/Chrome Windows i nadal jest tak samo.

**Comment by krystian3w** [comment]
A to dziwne, ja mam tylko Archa do zaorania nie umiem ustawić startowania XFCE.
