### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#7982]
Strona logowania (overlay) nie wyświetla się w ogóle na player.pl 

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 1803 x64
Browser:                            | Chrome Stable x64
AdGuard version:                    | **6.3.1118.3511** beta
Stealth mode: 						| disabled

| Filters enabled |
|-----------------|
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| CoinBlockerLists
| EasyList Polish 
| I don't care about cookies
| KAD - fraud/scam 
| Malware Domains List
| Peter Lowe's list 
| Polish Adguard Suplement
| Polish Annoyances Adguard Suplement
| Polish Annoyances Main 
| Polish Cookies Filter
| Polish Main
| Polish Social

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/7651

Trzeba by doprecyzować blokadę pop-up RODO i Cookies z dołu.

**`player.pl#@#.modal-dialog`** - dopuściłem i mam po chwili iframe z logowaniem:

 _`https://konto.tvn.pl/oauth/authorization`_


---

@hawkeye116477 - masz jakiś pomysł?

**Comment by FadeMind** [comment]
@krystian3w reguła `player.pl#@#.modal-dialog` rozwiązuje problem ;) Dziękuję. 
![20180609-001-screenshoot](https://user-images.githubusercontent.com/9846948/41195093-7a16a628-6c27-11e8-8079-03d166fe409b.png)

**Comment by hawkeye116477** [comment]
`player.pl#?#.modal-dialog:-abp-has(.rodo-popup-header)`
