### ISSUE TITLE
fn.org.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7984]
http://www.fn.org.pl
http://www.repozytorium.fn.org.pl
http://fototeka.fn.org.pl
![opera zdjecie_2018-06-10_094153_www fn org pl](https://user-images.githubusercontent.com/36385327/41199444-87ca5fd8-6c92-11e8-8416-07230e2d535c.png)

http://www.nitrofilm.pl
![opera zdjecie_2018-06-10_094216_www nitrofilm pl](https://user-images.githubusercontent.com/36385327/41199446-93ed60d0-6c92-11e8-8119-dbe4e219f7dd.png)

**Comment by krystian3w** [comment]
"_`www.fn.org.pl`_" - padła strona główna "`To change this page, upload a new index.html to your private_html folder`". 
Na kopii działa: `fn.org.pl##.col-md-4:nth-of-type(2)`

`repozytorium.fn.org.pl###block-block-11`
`fototeka.fn.org.pl##.col-lg-3:nth-of-type(4)`

---

`||www.nitrofilm.pl/public/naglowki/gdzie-jestesmy-pl.gif`
`nitrofilm.pl##div:nth-of-type(2) > div:nth-of-type(4), div:nth-of-type(2) > div:nth-of-type(5)`

**Comment by xxcriticxx** [comment]
@xMaap jedna strona per zgloszenie please!
