### ISSUE TITLE
taksiegra.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7987]
http://taksiegra.pl
![opera zdjecie_2018-06-10_094801_taksiegra pl](https://user-images.githubusercontent.com/36385327/41199493-6e8aff7c-6c93-11e8-9612-85c76615cd34.png)
![opera zdjecie_2018-06-10_094815_taksiegra pl](https://user-images.githubusercontent.com/36385327/41199494-70129792-6c93-11e8-86f6-94529ecdf178.png)

http://radiogol.pl
![opera zdjecie_2018-06-10_094948_radiogol pl](https://user-images.githubusercontent.com/36385327/41199509-c774d950-6c93-11e8-923f-8beb42d083e8.png)
![opera zdjecie_2018-06-10_094958_radiogol pl](https://user-images.githubusercontent.com/36385327/41199510-c7981faa-6c93-11e8-8b32-cb59fca5fd76.png)
![opera zdjecie_2018-06-10_095013_radiogol pl](https://user-images.githubusercontent.com/36385327/41199511-c7b8c3ea-6c93-11e8-846b-219daea4130f.png)
![opera zdjecie_2018-06-10_095037_radiogol pl](https://user-images.githubusercontent.com/36385327/41199512-c7dea308-6c93-11e8-86c0-7282f03eee09.png)

**Comment by krystian3w** [comment]
## `taksiegra.pl`

<ul>

....

</ul>

----

## `radiogol.pl`

<ul>

### Ważne, coś mi generuje wykrywanie Adblocka.

---

`##.widget-do-etfw, .widget_cardoza_fb_like`

</ul>

**Comment by xxcriticxx** [comment]
@xMaap / @krystian3w  radiogol juz byl https://github.com/MajkiIT/polish-ads-filter/issues/7962

**Comment by krystian3w** [comment]
Ale sekcja społecznościowa nie została wycięta dwa dni temu.

> ![obraz](https://user-images.githubusercontent.com/35370833/41201656-de18ee62-6cbb-11e8-8479-08a2e371c8b1.png) |
--- |

**Comment by xxcriticxx** [comment]
@krystian3w z tym to juz do @hawkeye116477
