### ISSUE TITLE
gsim.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7988]
![opera zdjecie_2018-06-10_095150_gsim pl](https://user-images.githubusercontent.com/36385327/41199523-fe43d724-6c93-11e8-8130-42646c625a07.png)
![opera zdjecie_2018-06-10_095201_gsim pl](https://user-images.githubusercontent.com/36385327/41199524-fe62585c-6c93-11e8-8547-d308565d9458.png)
![opera zdjecie_2018-06-10_095212_gsim pl](https://user-images.githubusercontent.com/36385327/41199525-fe85887c-6c93-11e8-9800-a2fbf693dbf8.png)

**Comment by krystian3w** [comment]
`###execphp-7 > .execphpwidget, .footer-banner`

---

`##.fa-google-plus.fa`
