### ISSUE TITLE
zwiedzam-stadiony.eu

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7990]
![opera zdjecie_2018-06-10_095349_zwiedzam-stadiony eu](https://user-images.githubusercontent.com/36385327/41199541-3864bca2-6c94-11e8-820c-92bc5ef71acb.png)

**Comment by krystian3w** [comment]
`###text-8` - resztka po reklamie

`###instagal_widget-3` - insta
