### ISSUE TITLE
nowyolechow.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7992]
![opera zdjecie_2018-06-10_095618_www nowyolechow pl](https://user-images.githubusercontent.com/36385327/41199566-8aad1bda-6c94-11e8-9ed2-697812a4ae37.png)

http://prbbudomal.pl
![opera zdjecie_2018-06-10_100056_prbbudomal pl](https://user-images.githubusercontent.com/36385327/41199611-31857a9c-6c95-11e8-894b-02e6bfce3443.png)

**Comment by krystian3w** [comment]
`nowyolechow.pl###fb`
`prbbudomal.pl##.nav-social-media`
