### ISSUE TITLE
pruszynski.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7994]
![opera zdjecie_2018-06-10_095808_pruszynski com pl](https://user-images.githubusercontent.com/36385327/41199595-ccff8c70-6c94-11e8-96d1-9f210bea0ef5.png)

**Comment by krystian3w** [comment]
`/icon_social_` - Fanboy Social List.

Nie wiem co ci przywraca ikonę `─\_(O_O)_/─`.
