### ISSUE TITLE
pzu.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#7995]
![opera zdjecie_2018-06-10_095849_www pzu pl](https://user-images.githubusercontent.com/36385327/41199599-e601d368-6c94-11e8-9c0b-bccc7ba1d6f0.png)

**Comment by krystian3w** [comment]
`pzu.pl##ul:nth-of-type(3) > li:nth-of-type(n+1):nth-of-type(-n+7)`

**Comment by xxcriticxx** [comment]
@hawkeye116477 nie placz ewka!

**Comment by xxcriticxx** [comment]
@hawkeye116477 my jestesmy old school bot niepotrzebny

**Comment by hawkeye116477** [comment]
@xxcriticxx Potrzebny, bo wraz z @MajkiIT macie mało czasu. Wydajność pracy wzrośnie dzięki niemu. Można też tak zrobić, że jak np jest label „ciasteczka", to będzie mnie wołał :smile:. Więcej na => `https://github.com/bkeepers/workflow/blob/master/docs/examples.md` :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 dont worry ja zawolam

@krystian3w zglos sie

**Comment by hawkeye116477** [comment]
Jak to nie ma, są przecież powiadomienia na GitHuba, no chyba, że ktoś odznaczył :smile:.

**Comment by krystian3w** [comment]
Ale na e-mailu, nie dostaje pusza a mam tylko powiadomienia o tym że ktoś dał mi gwiazdę lub sforkował NanoDefendera.

Maila jak przeglądam to mam po 100 maili githuba w podfolderze do tego i większość wywalam na podstawie opisu bez otwierania.

**Comment by hawkeye116477** [comment]
![screenshot_20180610_170312](https://user-images.githubusercontent.com/19818572/41202886-2df25ab8-6cd0-11e8-92fd-3cff64624a88.png)
Po co wywalać, wystarczy odznaczyć i zaznaczyć, by przychodziły powiadomienia tylko na stronie :smile:.
