### ISSUE TITLE
pianomedia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8]
cookies

Cookies na stronie PIANOMEDIA

 

Szanowny użytkowniku, aby umożliwić Tobie korzystanie z naszej strony internetowej używamy ciasteczek (ang. cookies).

 

Dzięki cookies możemy optymalizować naszą stronę dla Ciebie m.in. automatycznie udostępniając strony wydawców bez konieczności powtórnego logowania. Jeżeli zdecydujesz się kontynuować przeglądanie bez zmiany dotychczasowych ustawień, zakładamy, że akceptujesz otrzymywanie wszystkich naszych plików cookies.

 

Bez akceptacji cookies system Piano nie działa prawidłowo. W każdym czasie możesz zmienić ustawienia dotyczące cookies za pomocą programu wykorzystywanego przez Ciebie do obsługi internetu.

**Comment by MajkiIT** [comment]
Zaktualizuj filtry.
