### ISSUE TITLE
polsat.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8002]
http://www.polsat.pl/seriale/

![capture](https://user-images.githubusercontent.com/15007183/41205260-26861d26-6cbe-11e8-9b03-c2b712375354.PNG)

**Comment by hawkeye116477** [comment]
`||www.polsat.pl/rodo/*$xmlhttprequest` albo `www.polsat.pl/templates/rodo/rodo.js`
