### ISSUE TITLE
serialowa.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8003]
cookies

![capture](https://user-images.githubusercontent.com/15007183/41205336-895007d6-6cbf-11e8-9d74-3fcabb3c1187.PNG)

**Comment by krystian3w** [comment]
`###pum-176166`
`##,pum-open-overlay:style(overflow: auto !important;)`

**Comment by hawkeye116477** [comment]
```
||www.serialowa.pl/wpr/wp-content/plugins/popup-maker/assets/css/site.min.css
serialowa.pl##.popmake-overlay
```
