### ISSUE TITLE
serialowy.info

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8004]
broken page + social 

![capture](https://user-images.githubusercontent.com/15007183/41205368-fd8d7e08-6cbf-11e8-9b04-b3cceb14a13f.PNG)

**Comment by krystian3w** [comment]
`serialowy.info##.hustle-modal-body` - social, niby można wyciąć większy obszar - jakby było zablokowanie klikanie na stronie (chwilo mnie nie atakuje pop-up).

`@@||serialowy.info/wp-content/plugins/uk-cookie-consent/assets/js/uk-cookie-consent-js.js` - naprawa zdjęć, niestety wymieszali cookies ze wszystkim lub za bardzo wykorzystują tą bibliotekę do wyświetlania wszystkiego.
