### ISSUE TITLE
queer.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8009]
RODO + adblock 

https://queer.pl/news/201402/qlturalne-podsumowanie-tygodnia

![capture](https://user-images.githubusercontent.com/15007183/41205521-cf734068-6cc2-11e8-910d-139b765776fa.PNG)

**Comment by MajkiIT** [comment]
```
queer.pl##.bg
queer.pl##.box-rodo


```
`queer.pl##.box-block`

**Comment by xxcriticxx** [comment]
@hawkeye116477 znalazlem dla ciebie odpowiedni portal bedziesz mial gdzie porozmawiac o rainbow pony

**Comment by hawkeye116477** [comment]
Ja nie gadam nic o Pony, jedynie raz zrobiłem żart na 1 kwietnia na ten temat :stuck_out_tongue:

**Comment by xxcriticxx** [comment]
@hawkeye116477 wiedzielismy ze jestes inny
