### ISSUE TITLE
estrzelce.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8019]
https://estrzelce.pl/index.php/start/2064-strzelce-kraj-wlamywacz-zostawil-but-w-mieszkaniu-ktore-probowal-okrasc-estrzelce-pl

![opera zdjecie_2018-06-12_145217_estrzelce pl](https://user-images.githubusercontent.com/36385327/41291548-43cf09a4-6e50-11e8-9670-0659c607969c.png)
![opera zdjecie_2018-06-12_145226_estrzelce pl](https://user-images.githubusercontent.com/36385327/41291549-43efd418-6e50-11e8-8d48-0d585a1006cf.png)

**Comment by krystian3w** [comment]
`###ac-wrapper`
`##div.moduletable:nth-of-type(2) > .custom` / `###nav > div.moduletable:nth-of-type(2)`
