### ISSUE TITLE
cryptoprofit.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8020]
http://cryptoprofit.pl/ico/safeguard/

![opera zdjecie_2018-06-12_145833_cryptoprofit pl](https://user-images.githubusercontent.com/36385327/41291865-19ec940c-6e51-11e8-9a58-35b386cab549.png)

**Comment by krystian3w** [comment]
`##.mts-coin-social-wrapper` :question:
