### ISSUE TITLE
pomagam.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8021]
![opera zdjecie_2018-06-12_145920_pomagam pl](https://user-images.githubusercontent.com/36385327/41291898-33824556-6e51-11e8-9ef3-4ae003dfc7eb.png)

**Comment by krystian3w** [comment]
`###pp-info` lub `##.bg`

**Comment by hawkeye116477** [comment]
@xMaap O 14:40 był update i właśnie to wtedy dodałem, także zaktualizuj :smile:
