### ISSUE TITLE
popkulturysci.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8024]
https://popkulturysci.pl/goliath-sezon-1-amazon-prime-video-recenzja/
![opera zdjecie_2018-06-12_162849_popkulturysci pl](https://user-images.githubusercontent.com/36385327/41296726-d4bf632a-6e5d-11e8-87ca-32da2411cde7.png)
![opera zdjecie_2018-06-12_162905_popkulturysci pl](https://user-images.githubusercontent.com/36385327/41296727-d4f386be-6e5d-11e8-8019-ca45573ebd04.png)
![opera zdjecie_2018-06-12_162919_popkulturysci pl](https://user-images.githubusercontent.com/36385327/41296728-d51712aa-6e5d-11e8-88ad-4b009dcecc02.png)

**Comment by xxcriticxx** [comment]
more showmax!
