### ISSUE TITLE
f.kafeteria.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8025]
RODO

![capture](https://user-images.githubusercontent.com/15007183/41296531-2207fca6-6e2b-11e8-9830-dad14062da7e.PNG)

@KerbenII ten Tomasz to twoj boss?

**Comment by KerbenII** [comment]
nie, czemu?

**Comment by xxcriticxx** [comment]
@KerbenII jak dobrze pamietam to przez kafeterie znalazles nas

**Comment by KerbenII** [comment]
Nieeee,
zablokowaliście całe quartic.pl co rozwaliło nam m.in. panel klienta- tak was znalazłem 👅 
A z tego co pamiętam chodziło o zablokowanie reklamy leroy merlin na oferii.

Takich rzeczy się nie zapomina :P

**Comment by xxcriticxx** [comment]
@KerbenII co macie pod ‘rec.quartic.pl’ ze każdy blokuje?

**Comment by KerbenII** [comment]
Mógłbyś podrzucić jakiś link do list gdzie jest to zablokowane?
Aż ciekaw jestem co chcieli tym zablokować, bo blokowanie tego jest dosyć dziwne. 

Jedyne co jest pod tym adresem (jeszcze dzisiaj do południa to potwierdzę)
to bardzo legacy rozwiązanie rekomendujące produkty dla kilku sklepów i zbierajace kliknięcia
w te rekomendacje.

Taki widget, który jest doładowywany na stronę klienta i wybierający np. bestsellery.

Tak btw masz może konto na Majkowym Discordzie (Polskie filtry...)?

**Comment by xxcriticxx** [comment]
@KerbenII miałem tam konto ale @hawkeye116477 mnie zablokował bo niechcial więcej rozmawiać o rainbow pony

**Comment by krystian3w** [comment]
:rofl:

**Comment by hawkeye116477** [comment]
@xxcriticxx Ja ciebie nie zablokowałem. To @KonoromiHimaries ciebie wykopał, ale nie zablokował, więc możesz ponownie dołączyć :smiley:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 link please

**Comment by hawkeye116477** [comment]
@xxcriticxx Proszę bardzo => `https://discord.me/polskiefiltry` :smile:

**Comment by xxcriticxx** [comment]
@hawkeye116477 wpadl i wypadl strasznie tam kolorowa i wszystko mruga

**Comment by hawkeye116477** [comment]
@xxcriticxx Sam wypadł czy wyprosili? Jak wyprosili, to pewnie nie zarejestrował konta, nie potwierdził maila, a jeszcze captcha trzeba rozwiązać i podać swój numer, by wysłali kod na SMS'a, bo inaczej nie wpuszczają. A potem jeszcze zaakceptować regulamin na kanale, by móc pisać na czacie :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 advance crap
