### ISSUE TITLE
Grupa WP

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8027]
RODO lub reklamy

```
https://wp.pl
https://o2.pl
https://wawalove.wp.pl
http://tv.wp.pl
https://finanse.wp.pl
http://tv.pudelek.pl
http://pudelek.pl
https://open.fm
https://opinie.wp.pl
https://kobieta.wp.pl
https://facet.wp.pl
https://moto.wp.pl
https://autokult.pl
https://parenting.pl
https://gwiazdy.wp.pl
https://kuchnia.wp.pl
https://turystyka.wp.pl
https://film.wp.pl
https://teleshow.wp.pl
https://ksiazki.wp.pl
https://tech.wp.pl
https://komorkomania.pl
https://gadzetomania.pl
https://fotoblogia.pl
https://domodi.pl
https://allani.pl
https://www.finansowysupermarket.pl

```
Proponuje nie zamykać od razu, bo coś czuje, ze dojdzie tego więcej.

**Comment by xxcriticxx** [comment]
@hawkeye116477 bedziesz mial co robic

**Comment by hawkeye116477** [comment]
@xxcriticxx  Nie ładnie, a ty to co, leniuchujesz? Do roboty :stuck_out_tongue:

**Comment by xxcriticxx** [comment]
@hawkeye116477 wzielem wolne na mecz

**Comment by krystian3w** [comment]
W autobusie mówili że w czwartek.

**Comment by hawkeye116477** [comment]
U mnie na domodi nic nie ma po wycięciu skryptu, a supermarket w ogóle nie działa.

**Comment by MajkiIT** [comment]
@krystian3w @hawkeye116477 a na www.wp.pl ii kobieta.wp.pl macie pomysł ?

**Comment by krystian3w** [comment]
- `domodi.pl` - ok już nie mam
- `finansowysupermarket.pl` - dalej jest listy zaktualizowane strona kilka razy odświeżona
- `www.wp.pl` - u mnie działa reklamy się nie wylewają, może była poprawka i mi ją pobrało z listą EI
- `kobieta.wp.pl` - też działa, reklam nie widzę, może poprawka była w listach EI (lag z ładowaniem reszty strony jest nawet bez blokad reklam).

**Comment by krystian3w** [comment]
`https://web.archive.org/web/20180613104154/https://www.finansowysupermarket.pl/`, jak przyblokuje kosmetycznie / czy sieciowo to znika. Jedynie trzeba wziąć poprawkę na to, że doczepi się `web.archive.org` do filtru sieciowego lub kosmetycznego.

**Comment by xMaap** [comment]
https://direct.money.pl
![opera zdjecie_2018-06-13_133543_direct money pl](https://user-images.githubusercontent.com/36385327/41348999-beb91a24-6f0e-11e8-91bb-012704947fbb.png)
![opera zdjecie_2018-06-13_133552_direct money pl](https://user-images.githubusercontent.com/36385327/41349000-bed6a5e4-6f0e-11e8-82f2-dd3565133d8a.png)

https://manager.money.pl
Wycina
![opera zdjecie_2018-06-13_133850_manager money pl](https://user-images.githubusercontent.com/36385327/41349156-468a1156-6f0f-11e8-96c0-c63080821ee4.png)
![opera zdjecie_2018-06-13_133928_manager money pl](https://user-images.githubusercontent.com/36385327/41349157-46aaa538-6f0f-11e8-87be-edf51415b4ea.png)

https://dom.money.pl/budownictwo/materialy-budowlane/akcesoria-montazowe/
![opera zdjecie_2018-06-13_134135_dom money pl](https://user-images.githubusercontent.com/36385327/41349227-85424abc-6f0f-11e8-9f70-0a7e4a779ede.png)

https://www.money.pl/podatki/
https://www.money.pl/rejestr-firm/kody-pocztowe/
https://www.money.pl/rejestr-firm/
https://www.money.pl/archiwum/wydarzenia/impact18.html
![opera zdjecie_2018-06-13_135515_www money pl](https://user-images.githubusercontent.com/36385327/41349842-71ebf628-6f11-11e8-9f34-58acb7c72a6d.png)

http://targinamedal.wp.pl/najwieksze-targi-przemyslowe-w-polsce-roboty-wycinarki-i-drukarki-3d
![opera zdjecie_2018-06-13_135658_targinamedal wp pl](https://user-images.githubusercontent.com/36385327/41349927-b1863fe6-6f11-11e8-9738-6ce5e489724e.png)

https://www.money.pl/gielda/indeksy_gpw/
![opera zdjecie_2018-06-13_135900_www money pl](https://user-images.githubusercontent.com/36385327/41350020-f941a064-6f11-11e8-963a-90ab431f9678.png)

https://www.money.pl/gielda/indeksy_gpw/wig20/
https://wibor.money.pl
https://www.money.pl/pieniadze/depozyty/zlotowe/WIBORON,depozyty.html
https://www.money.pl/banki/elixir/
https://www.money.pl/pieniadze/kalkulator/

![opera zdjecie_2018-06-13_135946_www money pl](https://user-images.githubusercontent.com/36385327/41350042-0f0759c0-6f12-11e8-8c06-b29c96ef95cb.png)

https://video.wp.pl/i,komenda-dostaje-listy-matrymonialne,mid,2019881,cid,4051,klip.html
http://tv.pudelek.pl/video/Grosiccy-przeprowadza-sie-do-Warszawy-Kamil-jest-lokalnym-patriota-20060/
Nie chce się otwierać video.

**Comment by krystian3w** [comment]
* `video.wp.pl` - leci u mnie automatycznie
* `tv.pudelek.pl` - leci po kliknięciu play (odtwórz), nie wiem czy da się coś zrobić by nie było komunikatu "Oglądasz za darmo dzięki reklamom - 0s"

---

`www.money.pl##.qgijo3163` - [WIG20](https://www.money.pl/gielda/indeksy_gpw/wig20/)

A reszta praktycznie czysto, jedynie to polecanie artykułów można wyciąć:
`targinamedal.wp.pl##.section--socials`

**Comment by krystian3w** [comment]
* `video.wp.pl` - leci u mnie automatycznie
* `tv.pudelek.pl` - leci po kliknięciu play (odtwórz), nie wiem czy da się coś zrobić by nie było komunikatu "Oglądasz za darmo dzięki reklamom - 0s"

---

* `manager.money.pl` - odblokowanie div-a:
   `manager.money.pl #@#.in > DIV[class]:first-child` 
         
     * do naprawy / wymiany.

---

`www.money.pl##.qgijo3163` - na [WIG20](https://www.money.pl/gielda/indeksy_gpw/wig20/)

A reszta praktycznie czysto (nie mam tekstów "`REKLAMA`"), jedynie to polecanie artykułów można wyciąć:
`targinamedal.wp.pl##.section--socials`

**Comment by xMaap** [comment]
@krystian3w video.wp.pl teraz działa, ale w trybie prywatnym po kliknięcie "Play" nie chce się włączyć i też jakby coś chwiało się uruchomić w nowej karcie, ale szybko się zamyka.
tv.pudelek.pl działa z tym, że teraz strona jest cała rozwalona
