### ISSUE TITLE
smart-test.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#8034]
Resztki po reklamach u góry oraz w artykułach po prawo, np tu : http://www.smart-test.pl/aktualnosci/nowosci-z-kategorii-odtwarzacze-multimedialne-mini-pc/846-ferguson-fbox-atv.html

**Comment by krystian3w** [comment]
`###jm-header, .jm-sample-block, .jm-module:nth-of-type(n+2)`
\
\
`.jm-module:nth-of-type(n+2)` - na socialu niby takie liczenie działa.
 Można też niby dobezpieczyć `.jm-module:nth-of-type(n+2):nth-of-type(-n+4)`
