### ISSUE TITLE
pz.gov.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8035]
![opera zdjecie_2018-06-14_002004_pz gov pl](https://user-images.githubusercontent.com/36385327/41381650-0b8ba86c-6f69-11e8-9c1e-d16f922bde78.png)

**Comment by krystian3w** [comment]
`###gdprPopup` - rodo

---

`##.homePageContents > .sizeAndAlignmentWrapper > div:nth-of-type(1)`  - komunikat o porzuceniu SHA1.

Opcjonalnie można go łapać po:
* `##[style^="width: 100%; position: fixed; z-index: 800000; bottom: 20px;"]` czy 
* `##div:matches-css(position:fixed):matches-css(bottom: 20px)`

**Comment by xMaap** [comment]
Ten komunikat o SHA1 chyba bym nie ukrywał

**Comment by krystian3w** [comment]
Ja raczej też nie, zobaczymy czy kwalifikuje się to na EI.
