### ISSUE TITLE
naekranie.pl

### ISSUE THREAD

**Issue by lashus** [MajkiIT/polish-ads-filter#8037]
### Zrzut ekranu
n/d

### Link bezpośredni
https://naekranie.pl/ ( i podstrony )

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
Otwieranie linków w nowym oknie / karcie jest blokowane (ze stopki). Nie można otworzyć np. kontaktu.

### Moja konfiguracja
**Przeglądarka internetowa:**
Google Chrome Wersja 63.0.3239.132 (Oficjalna wersja) (64-bitowa)

**Rozszerzenia i skrypty:**
-

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka

**Comment by MajkiIT** [comment]
@lashus ale ty wymuszasz otworzenie w nowym oknie ?

**Comment by krystian3w** [comment]
`/https:\/\/naekranie\.pl\/[0-9a-z]{7,10}$/$popup` - to psuje

Nie musi wymuszać, strona wymusza.

**Comment by MajkiIT** [comment]
@krystian3w Na FF otwiera się w tym samym oknie. Usunąłem. Dziękuje
