### ISSUE TITLE
icppc.pl

### ISSUE THREAD

**Issue by wmyrda** [MajkiIT/polish-ads-filter#8038]
U góry wyświetlają się ciasteczka

http://www.icppc.pl/antygmo/publikacje/ksiazka-nasiona-klamstwa/

PS Całkiem możliwe, że filtry ogólne blokują w adblock ich wyświetlanie, ale by skorzystać z nich w privoxy poprzez konwertert dla danej witryny musi powstać plik CSS zawierajacy stosowne wpisy, a te się pojawiają jedynie wtedy gdy przynajmniej jedna reguła dotycząca eliminacji elementów odnosi się bezpośrednio do danej witryny. Dopiero wówczas powstaje stosowny plik, a póki co odnośników do tej strony nie znalazłem w żadnym z filtrów.

**Comment by krystian3w** [comment]
Nie wycina tego polska lista.
Nie wycina tego fanboy.
Nie wycina tego kiboke.

I w sumie się nie dziwie, zobacz nazwy identyfikatorów paska:

`###topbar1` / `###wptbheadline1`
