### ISSUE TITLE
radioemka.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#8039]
Reklamy

**Comment by krystian3w** [comment]
`##.advertisemen-block`

**Comment by xxcriticxx** [comment]
@krystian3w nie lepjej tobie robic te reguly w pull requestscie? ja bym to odrazu do listy zatwierdzal

**Comment by krystian3w** [comment]
Nie, zazwyczaj majki wymyśla lepszą lub ulepsza starą.

**Comment by xxcriticxx** [comment]
data i numer ver to jest najprostsza sprawa

**Comment by krystian3w** [comment]
Nie chce mi się bawić na razie gitem i bashem na Windowsie.

**Comment by xxcriticxx** [comment]
@krystian3w editor jest na githubie bash niepotrzebny

**Comment by krystian3w** [comment]
na forku raczej nie zadziała, trzeba by to travsi uruchomić dodatkowo

**Comment by xxcriticxx** [comment]
@krystian3w zrób test pr i zaraz się do wiemy
