### ISSUE TITLE
garwolin.spolem.org.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8041]
![opera zdjecie_2018-06-14_143206_www garwolin spolem org pl](https://user-images.githubusercontent.com/36385327/41412267-c504eb5c-6fdf-11e8-837a-b68fe946cc38.png)

**Comment by krystian3w** [comment]
`garwolin.spolem.org.pl###colorbox`

**Comment by hawkeye116477** [comment]
`garwolin.spolem.org.pl#?##colorbox:-abp-has(#rodo_width_hotfix)`
Musi być tak, bo inaczej zdjęcia w popupach się nie wyświetlą :smile:
