### ISSUE TITLE
eurocash.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8042]
http://eurocash.pl
http://www.payup.pl
![opera zdjecie_2018-06-14_143718_eurocash pl](https://user-images.githubusercontent.com/36385327/41412489-75bdcb58-6fe0-11e8-9300-675f2f7bef65.png)

https://sklepyabc.pl
![opera zdjecie_2018-06-14_143741_sklepyabc pl](https://user-images.githubusercontent.com/36385327/41412502-83ed266a-6fe0-11e8-8be4-7fdd9a4f9197.png)

**Comment by krystian3w** [comment]
`eurocash.pl,payup.pl###info`

`sklepyabc.pl###am_pop-up`
