### ISSUE TITLE
hm.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8052]
http://www2.hm.com/pl_pl/index.html

![opera zdjecie_2018-06-15_061623_www2 hm com](https://user-images.githubusercontent.com/36385327/41449846-c4e48428-7063-11e8-90e3-c81a5e7cb97e.png)

**Comment by krystian3w** [comment]
```
hm.com#?#.modaloverlay:-abp-has(#gdpr-modal)
hm.com##.modal-open, .modal-open body:style(overflow-y: auto !important; position: static !important;)
```

Jak nie ma innych ważnych pop-up to można próbować uprościć do samego `##.modaloverlay` lub na dwa elementy: `##.modalbackground, .fadeInModal`
