### ISSUE TITLE
domeny natemat.pl mamadu.pl innpoland.pl etc.

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#8054]
Header z odnośnikiem do komentarzy (w tym do facebooka) 
![20180615-001-screenshoot](https://user-images.githubusercontent.com/9846948/41452250-4706005a-7071-11e8-9f5a-60675f0eeb82.png)
http://mamadu.pl/137279,9-latka-dreczyla-kolegow-mama-dala-jej-nauczke

FIX
```
natemat.pl,innpoland.pl,aszdziennik.pl,mamadu.pl##.art__header__photo
```

**Comment by MajkiIT** [comment]
@FadeMind Dziekuję
