### ISSUE TITLE
spodekkatowice.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8055]
http://www.spodekkatowice.pl/pl/
http://www.mckkatowice.pl/pl/

![opera zdjecie_2018-06-15_094513_www spodekkatowice pl](https://user-images.githubusercontent.com/36385327/41456508-f5e144ea-7080-11e8-88dc-4db0c08a5baf.png)
![opera zdjecie_2018-06-15_094546_www spodekkatowice pl](https://user-images.githubusercontent.com/36385327/41456509-f601cbc0-7080-11e8-94e5-c262c79c8fdb.png)

**Comment by krystian3w** [comment]
mckkatowice.pl,spodekkatowice.pl##.open.rodo
mckkatowice.pl,spodekkatowice.pl##.windowOpen:style(overflow: auto !important;)
