### ISSUE TITLE
eecpoland.eu

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8056]
![opera zdjecie_2018-06-15_094713_www eecpoland eu](https://user-images.githubusercontent.com/36385327/41456630-5dcfea98-7081-11e8-976d-e093eba77d8e.png)
![opera zdjecie_2018-06-15_094900_www eecpoland eu](https://user-images.githubusercontent.com/36385327/41456633-5ed24576-7081-11e8-972e-5917e6fc611e.png)

**Comment by krystian3w** [comment]
`##.no-absolute.open.rodo` - mogę dodać na listę dla każdego blokera reklam aż nie zablokują przewijania.

Albo tak jak z mck i spodkiem dla uBlock Origin / Adguard.

---

`##.cookie-bar2`

---

`##.stickSocial`

**Comment by hawkeye116477** [comment]
Już zablokowali :smile:.
