### ISSUE TITLE
tvpolsat.info

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#8061]
`tvpolsat.info##CENTER > A[target="_blank"] > IMG + ##div.panel-default.panel:nth-of-type(5)`

https://github.com/MajkiIT/polish-ads-filter/blob/3982e2e1d1b2cd3bab996df2e94b818117546d41/polish-adblock-filters/adblock.txt#L2461

## Powinno być:

**`tvpolsat.info##CENTER > A[target="_blank"] > IMG, div.panel-default.panel:nth-of-type(5)`**

_(z przecinka wymienione elementy do blokady a nie jakimś plusem i haszami "` + ##`")_

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję
