### ISSUE TITLE
grafmag.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#8063]
![2018-06-15-czym jest material design_ - teoria zasady materialy i przyklady](https://user-images.githubusercontent.com/5884000/41486543-36d53952-70e5-11e8-8e91-0d5e4c09c361.png)
`https://grafmag.pl/artykuly/czym-jest-material-design-teoria-zasady-materialy-i-przyklady`

puste sekcje reklama

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.10
 ND 14.54
 Chr 67.0.3396.87
</details>

**Comment by krystian3w** [comment]
`##.money-maker__google-article-under-author, .money-maker__google-under-header`

albo może uprościć do:

`##[class^="money-maker__"]`

**Comment by xxcriticxx** [comment]
jakis dlugi ten div

`grafmag.pl##.money-maker__google-under-header--white.money-maker__google-under-header`

**Comment by krystian3w** [comment]
Bywa, dziwnie ktoś określił kolor w wtyczce.

**Comment by krystian3w** [comment]
@MajkiIT  u mnie nie działa `##.money-maker__articles` - teksty reklama dalej widoczne w Firefox 60 - 61.
