### ISSUE TITLE
onetech.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8068]
Źle ukryty Google + i RSS

![opera zdjecie_2018-06-16_024436_onetech pl](https://user-images.githubusercontent.com/36385327/41494132-7cdaa278-710f-11e8-8cb1-53f648824f02.png)

http://onetech.pl/zlamano-zabezpieczenia-najnowszej-wersji-ios-11-4/
![opera zdjecie_2018-06-16_024654_onetech pl](https://user-images.githubusercontent.com/36385327/41494138-8daee47e-710f-11e8-8dd9-49060c29b4ea.png)

**Comment by hawkeye116477** [comment]
Jaki tam błąd, po prostu zostały resztki :stuck_out_tongue:

**Comment by xxcriticxx** [comment]
@hawkeye116477 nie mamy takiego tagu. nie denerwuj bota :)

**Comment by krystian3w** [comment]
Lepiej to wyglądało z luką, teraz ten czerwony przycisk zlewa się z grafiką.
