### ISSUE TITLE
grajteraz.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8071]
http://www.grajteraz.pl/sport/football-tricks

![capture](https://user-images.githubusercontent.com/15007183/41499951-7271e1fa-7157-11e8-9286-b14b43d7b1b3.PNG)

**Comment by MajkiIT** [comment]
`www.grajteraz.pl##[id^="bannerGameSkyscraper"]`

**Comment by xxcriticxx** [comment]
@MajkiIT jeszcze jedna na topie zostala

![capture](https://user-images.githubusercontent.com/15007183/41507548-52e2a062-7202-11e8-8b71-4b9b5645bc90.PNG)
