### ISSUE TITLE
forumsamochodowe.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#8084]
![2018-06-17-forum samochodowe __ forum motoryzacyjne samochody 4x4](https://user-images.githubusercontent.com/5884000/41511516-798b2aa6-7278-11e8-9953-4271d9331ca2.png)

uszkodzona strona

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.10
 ND 14.54
 Chr 67.0.3396.87
</details>

**Comment by krystian3w** [comment]
`||www.forumsamochodowe.pl/js/jquery.cookie.js$script,domain=www.forumsamochodowe.pl` by nie męczyć się z odblokowywaniem na AdBlock / Adblock Plus i usuwaniem rozmycia w uBlock Origin / AdGuard.

**Comment by hawkeye116477** [comment]
Chyba będzie ok, ale to by musiał potwierdzić ktoś kto ma tam konto, bo może np blokuje logowanie czy tam jakieś inne funkcje dostępne tylko po zalogowaniu.
@KonoromiHimaries Ma tam konto?
