### ISSUE TITLE
Trakt.tv

### ISSUE THREAD

**Issue by SET19724** [MajkiIT/polish-ads-filter#8085]
### Zrzut ekranu

https://i.imgur.com/uMgnvTU.png

### Link bezpośredni

https://trakt.tv/dashboard

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na stronę
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome najnowszy

**Rozszerzenia i skrypty:**
Ublock Origin
NanoDefender
**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. Link do screena:https://i.imgur.com/TfXGEHD.png
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Przy badaniu to ta część kodu:`<div class="sncmp-popup_popup" style="display: flex;"><div class="sncmp-popup_overlay"></div><div class="sncmp-popup_content"></div></div>`
Jeśli chodzi o regułę do ublocka to:
`##.sncmp-popup_content`
`##.sncmp-popup_overlay`
`##.sncmp-popup_popup`

**Comment by KonoromiHimaries** [comment]
filtry ciasteczkowe nie są potrzebne gdy masz filtry elementów irytujących
uzupełnienie filtrów elementów irytujących nie jest potrzebne gdy masz najnowszego ublocka origin

**Comment by hawkeye116477** [comment]
No nie wiem czy to do nas, ta strona nie jest polska ani po polsku :smile:.

**Comment by SET19724** [comment]
Ta ale dużo osób w Polsce korzysta też z tej strony jeśli używają KODI.Tam sobie na liste filmy dodajesz itd więc warto było by to dodać ;)

**Comment by hawkeye116477** [comment]
@krystian3w Jest robota dla ciebie :smile:.

**Comment by xxcriticxx** [comment]
@SET19724 a jakich wtyczek na kodi uzywasz?

**Comment by SET19724** [comment]
@xxcriticxx obecnie polecam placenta zamiast covenanta ;)

**Comment by xxcriticxx** [comment]
@SET19724 krajowych jakis uzywasz?

**Comment by krystian3w** [comment]
Mam:

```
##.sncmp-app_gdpr
```

od Fanboya.

**Comment by xxcriticxx** [comment]
@MajkiIT dodajemy?

**Comment by krystian3w** [comment]
Dodałem, skoro strona ma tylu fanów.

**Comment by SET19724** [comment]
@xxcriticxx Krajowe mi nie podchodzą słabizny bo nie aktualizowane od dawna ogólnie polecam ci obczaić wtyczki na kodiwpigulce.pl. Ewentualnie mogę ci screena zarzucić co ja tam używam ;).Albo fajny patent na iptv jak potrzebujesz coś obejrzeć

**Comment by SET19724** [comment]
@krystian3w @MajkiIT @xxcriticxx Dzieki za dodanie ;)

**Comment by xxcriticxx** [comment]
@SET19724 a fanfilm lite testowales? podpis testowales? 

@MajkiIT sorry za off topic!

**Comment by SET19724** [comment]
@xxcriticxx Nie testowałem bo mi Placenta starczała do oglądania ;)

**Comment by xxcriticxx** [comment]
@SET19724 w ffl sa polskie zrodla chyba ze po angielsku sprechen
