### ISSUE TITLE
tradus.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8089]
https://www.tradus.com/pl

![opera zdjecie_2018-06-18_070647_www tradus com](https://user-images.githubusercontent.com/36385327/41519077-371a9320-72c6-11e8-9440-d1b8e58c08bb.png)
![opera zdjecie_2018-06-18_070657_www tradus com](https://user-images.githubusercontent.com/36385327/41519078-37394680-72c6-11e8-9bdc-bbcb09fddf1e.png)

**Comment by krystian3w** [comment]
`##.app-footer__social`

**Comment by hawkeye116477** [comment]
Ale Wikipedii chyba nie chowamy :smile:

**Comment by krystian3w** [comment]
No to trzeba odliczyć po li.
