### ISSUE TITLE
polsat2.pl + panstwowpanstwie.polsatnews.pl + interwencja.polsatnews.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8091]
![opera zdjecie_2018-06-18_072116_www panstwowpanstwie polsatnews pl](https://user-images.githubusercontent.com/36385327/41519504-d7bb5754-72c8-11e8-9772-3b3337d3877f.png)

**Comment by krystian3w** [comment]
`/rodo/rodo.js$script,domain=polsatnews.pl|polsat2.pl` - do sprawdzenia jak ma się to ze starym.

**Comment by hawkeye116477** [comment]
Chyba tak jak poprzednio też może być => 
`/rodo/*$xmlhttprequest,domain=polsat2.pl|polsatnews.pl`. Nic się nie zmieniło, tak już było, czyli abo js albo xhr, do wyboru do koloru :smile:.

**Comment by hawkeye116477** [comment]
To to samo, podobnie jak tam można albo js zablokować albo xhr, do wyboru do koloru :smile:.

**Comment by krystian3w** [comment]
przy `XHR` to mają raz duże `RODO` a raz małe `rodo` jak patrzyłem.

**Comment by hawkeye116477** [comment]
No to zmienimy na blokowanie js, by było uniwersalniej, raczej blokowanie js nie powoduje problemów, ten skrypt chyba tworzy tylko xhr z elementami, także zamienimy :smile:

**Comment by krystian3w** [comment]
Ok, ok.

**Comment by hawkeye116477** [comment]
I co nikt nie zamknął, już dawno dodane :stuck_out_tongue:

**Comment by xxcriticxx** [comment]
@hawkeye116477 przestan plakac :)
