### ISSUE TITLE
i'm not a robot capatcha

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#81]
mozna to jakos ominac?

tutaj jest przyklad

https://login.teamviewer.com/LogOn

**Comment by MajkiIT** [comment]
teraz tego nie ma. To pewien sposób ochrony przed bot-ami.

**Comment by xxcriticxx** [comment]
ja to caly czas mam na tej stronie co podalem tylko jest pytanie czy cos sie da stym zrobic zeby nie clikac nato caly czas
