### ISSUE TITLE
naszawielkopolska.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8102]
![opera zdjecie_2018-06-19_014612_naszawielkopolska pl](https://user-images.githubusercontent.com/36385327/41567825-92258ab2-7362-11e8-8c76-112cbc75917f.png)
![opera zdjecie_2018-06-19_014648_naszawielkopolska pl](https://user-images.githubusercontent.com/36385327/41567837-a65c0812-7362-11e8-836c-e8b88d738bf4.png)

**Comment by MajkiIT** [comment]
`naszawielkopolska.pl##.g`
