### ISSUE TITLE
publikator.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8103]
![opera zdjecie_2018-06-19_030408_www publikator com pl](https://user-images.githubusercontent.com/36385327/41570083-82be73a8-736d-11e8-96b5-48378b3f9475.png)

**Comment by krystian3w** [comment]
```
publikator.com.pl##body:style(overflow: auto !important;)
publikator.com.pl##body>*:style(filter: none !important;)
publikator.com.pl##.layer
```

**Comment by hawkeye116477** [comment]
> A na AdBlock / AdBlock Plus trzeba ręcznie kliknąć - może zostanie dodane do skryptu uzupełniającego.
Nie ma takiej opcji, skrypt jest tylko do wspomagania uBO/AdGuarda. Nie chcę za bardzo wstrzymywać migracji na lepszy nowocześniejszy bloker :smile:.
