### ISSUE TITLE
zagranie.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8105]
http://zagranie.com/pokaz-sily-belgow-i-wyszarpane-zwyciestwo-synow-albionu-podsumowanie-dnia/
Ukrywa artykuł 
![opera zdjecie_2018-06-19_054003_zagranie com](https://user-images.githubusercontent.com/36385327/41575562-4a57d8a4-7383-11e8-8437-a3aad3fdfed4.png)

Social
![opera zdjecie_2018-06-19_054117_zagranie com](https://user-images.githubusercontent.com/36385327/41575579-6852ebc8-7383-11e8-8e67-0b62ec36ac0a.png)

**Comment by krystian3w** [comment]
`zagranie.com#@#.share-container`

tweety to potem pokombinuje.
