### ISSUE TITLE
trybun.org.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#8111]
![2018-06-21-andrzej turczyn - trybun broni palnej](https://user-images.githubusercontent.com/5884000/41690401-a72f6024-74f5-11e8-83fa-18d226238cde.png)

brak paska wyszukiwania

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.10
 ND 14.54
 Chr 67.0.3396.87
</details>

**Comment by krystian3w** [comment]
U mnie czysto - `trybun.org.pl#@#.social-search` :question:

**Comment by krystian3w** [comment]
Web Annoyances Ultralist - do nich pisz:

> Filtr statyczny `##.social-search` znajdujący się w:
> * Web Annoyances Ultralist
