### ISSUE TITLE
imagazine.pl

### ISSUE THREAD

**Issue by wmyrda** [MajkiIT/polish-ads-filter#8112]
RODO

https://imagazine.pl/2013/09/14/automatyczne-wybieranie-numerow-wewnetrznych/

**Comment by krystian3w** [comment]
U mnie czysto, jak wyłączę uBlock Origin, wyczyszczę ciasteczka to wskakuje.

`imagazine.pl##.overlay-rules` - mamy na liście jak sprawdziłem w Firefox.

lub

`||imagazine.pl/wp-content/plugins/woocommerce/assets/js/js-cookie/js.cookie.min.js` - tak blokuje Fanboy filterm `/js.cookie`

**Comment by wmyrda** [comment]
Faktycznie [jest](https://github.com/MajkiIT/polish-ads-filter/blob/master/cookies_filters/adblock_cookies.txt#L1150). Będę miał nauczkę by użyć CTRL+F a nie tylko sprawdzić [początek](https://github.com/MajkiIT/polish-ads-filter/blob/master/cookies_filters/adblock_cookies.txt#L364) i uznać, że wpisu nie ma :)

W sumie u mnie na privoxy też działa gdyż przy kolejnych odświeżeniach strony ładnie zaciąga css  `192.168.1.99 - - [21/Jun/2018:09:44:22 +0200] "GET /imagazine.pl/ab2p.css HTTP/1.1" 200 8518` który zawiera m.in. `.overlay-rules` czyli ładnie wycina. Będę miał zaś zagwostkę czemu z pierwszym razem Firefox nie skorzystał z tego pliku :/

**Comment by krystian3w** [comment]
Szkoda, że niestety nie sprawdziała się opcja z tym plikiem `/js.cookie.` - nie ładuje jednak RODO.
