### ISSUE TITLE
ztm.poznan.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8115]
![opera zdjecie_2018-06-21_094304_www ztm poznan pl](https://user-images.githubusercontent.com/36385327/41704805-88379ce4-7537-11e8-8e10-516bdb102bcb.png)

**Comment by krystian3w** [comment]
```
ztm.poznan.pl###PopUP, .modal-backdrop
ztm.poznan.pl##.modal-open:style(overflow: auto !important;)
```
