### ISSUE TITLE
domzdrowia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8120]
![opera zdjecie_2018-06-22_072825_www domzdrowia pl](https://user-images.githubusercontent.com/36385327/41759287-dfaeb168-75ed-11e8-9ab5-b7c3a836f642.png)

**Comment by krystian3w** [comment]
hmm... druga "fabryka siły", jak będzie tego więcej to może zmienię blokadę z CSS-a na kosmetyczną  (tak by nie był nagle konieczny regex pod filtr sieciowy)?

```
||www.domzdrowia.pl/tac/pp-t-a-c.css
```

**Comment by krystian3w** [comment]
`/(fs-tac|tac)\/pp-t-a-c\.js/$script`

Jak mogę zapytać czy ten regex jest dobry pod skrypty:
```
<script type="text/javascript" src="//static.fabrykasily.pl/fs-tac/pp-t-a-c.js"></script>
<script type="text/javascript" src="/tac/pp-t-a-c.js?v2"></script>
```
