### ISSUE TITLE
sport.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#8122]
http://www.sport.pl/sport-hp/0,0.html

![20180622-003-screenshoot](https://user-images.githubusercontent.com/9846948/41788725-e2dc3a36-764c-11e8-9c3a-565485e5be15.png)

```
sport.pl##.mod, .mod_uzr_sport6
```

**Comment by krystian3w** [comment]
Ale stop, głupoty proponuje generator 🙈.

> ![obraz](https://user-images.githubusercontent.com/35370833/41804554-eb511000-7698-11e8-972e-6078e2d3b091.png)

Samo `sport.pl##.mod_uzr_sport6` powinno wystarczyć.
