### ISSUE TITLE
cinema-city.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8131]
Wycina

![opera zdjecie_2018-06-24_053940_www cinema-city pl](https://user-images.githubusercontent.com/36385327/41815625-19636cd0-7771-11e8-9ec0-2b734342834f.png)
![opera zdjecie_2018-06-24_054013_www cinema-city pl](https://user-images.githubusercontent.com/36385327/41815626-1981a920-7771-11e8-8a1e-08571fe45cd5.png)

**Comment by hawkeye116477** [comment]
U mnie jest ok.

**Comment by MajkiIT** [comment]
@xMaap masz aktualne filtry ?
