### ISSUE TITLE
fokus.tv

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8133]
Niemożna odtworzyć filmów

Włączony
![opera zdjecie_2018-06-24_054213_www fokus tv](https://user-images.githubusercontent.com/36385327/41815641-6d8ea8b0-7771-11e8-9e32-a974249d0aa2.png)
Wyłączony
![opera zdjecie_2018-06-24_054320_www fokus tv](https://user-images.githubusercontent.com/36385327/41815643-875d025a-7771-11e8-89f4-69be6e95e5da.png)

**Comment by hawkeye116477** [comment]
U mnie jest ok, jedynie na Chromium 67 mam jakiś problem, że nie chce samo wystartować, ale jak klikam na zmianę jakości, to już jest ok.

**Comment by MajkiIT** [comment]
@xMaap U mnie też.
