### ISSUE TITLE
kaliszak.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#8148]
Proszę o usunięcie z tej strony komunikatu Rodo: http://www.kaliszak.pl/dodaj-ogloszenie/kategoria

**Comment by krystian3w** [comment]
`kaliszak.pl##body:style(overflow: auto !important;)`
`kaliszak.pl##.rodo, .rodo_layer`

**Comment by hawkeye116477** [comment]
Albo `kaliszak.pl##script:inject(abort-on-property-write.js, window.GLOBAL_RODO)` :smile:

**Comment by krystian3w** [comment]
Jak chce ci się przebudować style na skrypty to czemu nie, ja tam jeszcze tego nie ogarniam.
