### ISSUE TITLE
Filtr uniemożliwia napisanie listu na WP

### ISSUE THREAD

**Issue by KKopytko** [MajkiIT/polish-ads-filter#8150]
### Zrzut ekranu
![window](https://user-images.githubusercontent.com/2992815/41930554-a5797a0a-797b-11e8-8de6-74383572aef9.png)
![console](https://user-images.githubusercontent.com/2992815/41930558-a9effd52-797b-11e8-948d-16498bf7634b.png)
![m3](https://user-images.githubusercontent.com/2992815/41970883-b0602f22-7a0c-11e8-9c68-740c6638b0f7.png)

### Link bezpośredni
https://poczta.wp.pl/d646/newmail.html?

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Zalogować się na skrzynkę pocztową
2. Kliknąć przycisk "napisz"
3. Nie załaduje się formularz z nową wiadomością.

### Moja konfiguracja
**Przeglądarka internetowa:**
Google Chrome
Wersja 67.0.3396.99 (Oficjalna wersja) (64-bitowa)

**Rozszerzenia i skrypty:**
uBlock Origin
Ghostery

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for uBlock​​​​​

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Metodą prób i błędów (wyłączając inne listy filtrów) doszedłem do tego, że ten zestaw filtrów powoduje błąd.

**Comment by MajkiIT** [comment]
@KKopytko nie wiem jakiego templatu używasz ale ten link jaki podałeś robi przekierowanie na stronę główną poczty a ja widzę nową wiadomość tak...

![inked2018-06-27_0951_li](https://user-images.githubusercontent.com/11302675/41960533-4a8ecaa8-79f0-11e8-8b77-51952762c9c7.jpg)

**Comment by KKopytko** [comment]
@MajkiIT starałem się jak najdokładniej uzupełnić formularz zgłoszenia błędu i było tam pole "bezpośrendi link". Bezpośrednim linkiem jest adres okienka, w którym mam nową wiadomość :(

Szczegółowiej:
Loguję się na: https://profil.wp.pl/login.html?zaloguj=poczta
Przekierowuje mnie na: https://poczta.wp.pl/d613/indexgwt.html#start
Tam klikam przycisk "napisz", by utworzyć nowy email:
![image](https://user-images.githubusercontent.com/2992815/41965637-5399949a-79fd-11e8-8b42-d762df792ba8.png)
Otwiera się nowe okienko pod adresem: https://poczta.wp.pl/d646/newmail.html?

Niestety jest ono puste, bo pod spodem wysypuje się jakiś JS czy coś, ponieważ pewien kluczowy element musiał zostać zablokowany przez któryś z filtrów. Nie wiem jak prześledzić, która reguła dokładnie, dlatego wkleiłem do zgłoszenia wszystko co miałem.

**Comment by xxcriticxx** [comment]
@KKopytko ghostery wyłącz i jeszcze raz testuj

**Comment by KKopytko** [comment]
@xxcriticxx, @MajkiIT  niestety, dalej to samo. Żeby pójść dalej w inwestygacji:

1. Wyłączyłem ghostery i zrestartowałem chrome'a
2. Wyłączyłem tę listę filtrów
3. Jej treść wkleiłem jako "My filters"
4. Po wykomentowaniu poniższych trzech - pojawiło mi się okienko z pocztą:
```
wp.pl,pudelek.pl##script:inject(set-constant.js, WP.gaf.setSlotCreation, noopFunc)

wp.pl##script:inject(abort-on-property-read.js, WP.inline)

wp.pl,echirurgia.pl,kardiolo.pl,money.pl,abczdrowie.pl,komorkomania.pl,fotoblogia.pl##script:inject(set-constant.js, WP.gaf.addCreation, noopFunc)
```
5. Jeśli którykolwiek z powyższych zostanie na liście filtrów - okienko z pocztą się nie włączy.

**Wersja przed:**
![first](https://user-images.githubusercontent.com/2992815/41970740-26eab488-7a0c-11e8-869a-583c9cd4b973.PNG)

**Wersja po:**
![second](https://user-images.githubusercontent.com/2992815/41970741-270d61b8-7a0c-11e8-8bf7-5953668c3bb3.PNG)

**Comment by MajkiIT** [comment]
czyli muszą być 3 zakomentowane ?

**Comment by KKopytko** [comment]
Wszystkie trzy; gdy zostawię którykolwiek z nich - okienko się nie wyświetli. To minimalna ilość, która uruchamia mi pocztę.

**Comment by KKopytko** [comment]
Może, próbując zrozumieć treść pierwszego błędu z konsoli - faktycznie obiekt "WP" jest utworzony i może jakoś utworzył go uBlock regułami?

**Screen ze zobfuskowanego kodu JS "nowej wiadomości" z miejscem istnienia obiektu "WP" zdefiniowanego globalnie (nie jest owrapowany w żadną funkcję):**
![image](https://user-images.githubusercontent.com/2992815/41971958-8c895c5a-7a10-11e8-8246-4de551a66df2.png)

**Comment by MajkiIT** [comment]
@KKopytko poprawiłem, dziękuję. Ale muszę jakoś to złapać, aby poprawić to świadomie.

**Comment by KKopytko** [comment]
@MajkiIT to ja dziękuję :) Po tym commicie okienko wiadomości wyświetla się prawidłowo.

**Comment by krystian3w** [comment]
Pewnie będziesz musiał poszukać maila nieprzerzuconego na `nowapoczta.wp.pl`.
