### ISSUE TITLE
plug.dj

### ISSUE THREAD

**Issue by Gumaa** [MajkiIT/polish-ads-filter#8184]
### Zrzut ekranu
![2018-06-29_22-37-07_firefox](https://user-images.githubusercontent.com/16503469/42113918-62c72b48-7bed-11e8-84d2-7527c68de976.jpg)

### Link bezpośredni
Jakikolwiek kanał na [plug.dj](https://plug.dj/)

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na plug.dj i (prawdopodobnie) założyć konto
2. Odwiedzić jakikolwiek kanał z włączonym uBlockiem

### Moja konfiguracja
**Przeglądarka internetowa:** 
Firefox Quantum 61.0 (64 bity)

**Rozszerzenia i skrypty:** 
uBlock Origin v1.16.12
Tampermonkey
Stylish
Firefox containers

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. 
![2018-06-29_22-49-19_firefox](https://user-images.githubusercontent.com/16503469/42114321-eea56598-7bee-11e8-96fe-2a7d1a5e7825.png)
(moje filtry i reguły są puste)

**Inne ważne informacje mogące mieć znaczenie:**
uBlock na Firefoxie blokuje funkcjonalność strony plug.dj. Film się nie odtwarza, tak jakbym wyłączył player przyciskiem na stronie, jednak przycisk nie reaguje (oba elementy zostały zaznaczone pomarańczową strzałką na screenie). 
Blokowane są jedynie filmy z YT, muzyka puszczana z Soundclouda nadal działa.
Wszystko działa przy kompletnym wyłączeniu uBlocka.
Na Chrome ten problem nie występuje.

**Comment by krystian3w** [comment]
Tampermonkey się nie aktywuje na stronie - żeby nie było, że skrypt uniwersalny lub pod tą stronę gryzie się z uBlock Origin.

**Comment by Gumaa** [comment]
O tego znaku zapytanie mi brakowało.
Tampermonkey owszem uruchamia się, ale to ze względu na dodatek RCS do Pluga. Po jego wyłączeniu problem nie ustępuje. Tego samego dodatku używam na Chromie i wcześniej też na Firefoxie, jednak w przypadku Firefoxa w pewnym momencie coś się stało i odtwarzacz przestał działać i nie jestem w stanie określić kiedy.
Czy jest możliwość w uBlocku ustawiać które z rejestrów w dzienniku żądań mają być blokowane, a które przepuszczane? Mógłbym w ten sposób ręcznie sprawdzić co dokładnie za to odpowiada.

**Comment by krystian3w** [comment]
Można częściowo w Loggerze ale część reguł może się nie pokazać - nie znam przyczyn np. często nie widzę reguł kosmetycznych np. generujące pop-up o wykryciu AdBlocka jak pomaga `generichide`.

<ul>

> ![obraz](https://user-images.githubusercontent.com/35370833/42116019-c78cebb4-7bf5-11e8-9546-cadbc47fca85.png) |
> --- |

</ul>


----

### Czerwone (sieciowe) wyłączysz klikając dwa razy w `--`:

<ul>

> ![obraz](https://user-images.githubusercontent.com/35370833/42116048-edc7c966-7bf5-11e8-8a28-a6b22f8d4df4.png) |
> --- |

</ul>


Potem w oknie wybierasz `Filtrowanie statyczne` z listy wysowanej przełączasz `Blokuj` na `Zezwalaj`.
Adres URL bym uprościł do samego pliku js czy może nawet na początku domeny.

<ul>

> ![obraz](https://user-images.githubusercontent.com/35370833/42116117-2e44a48c-7bf6-11e8-9962-1f8fa6280cb7.png) |
> --- |

> ![obraz](https://user-images.githubusercontent.com/35370833/42116122-383d877e-7bf6-11e8-9906-fd1073d87ea1.png) |
> --- |

</ul>

### Reguły kosmetyczne jakby blokowały można wyłączyć z ikony: `</>`

i tam klikasz w czerwoną regułę, potem w dyskietkę 💾 i `utwórz`.

> ![obraz](https://user-images.githubusercontent.com/35370833/42116167-6a14cf6e-7bf6-11e8-9ea9-ce4bdc61b0c0.png) |
> --- |


### Reguły `inject:script` / `+js` / `:style` wyłączasz tak jakby to była normalna reguła kosmetyczna tyle, że jej nie widać na tej drugiej liście / drzewku z przycisku `</>`.
