### ISSUE TITLE
memy.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8186]
cookies by Quantcast

![capture3](https://user-images.githubusercontent.com/15007183/42116067-b6c31e8e-7bc3-11e8-8c1c-c5e7bef8d1dd.PNG)

**Comment by krystian3w** [comment]
`||quantcast.mgr.consensu.org/cmp.js$script,domain=memy.pl` i nie trzeba CSS do odblokowania scrollowania.

**Comment by krystian3w** [comment]
Jak będą skargi, że coś nie działa na memy to będzie trzeba przejść na blokowanie kosmetyczne i CSS-em odblokować scroll.

---

_Z `consensu.org` wiem, że nie dogaduje się sourceforge - mają dziwny Cookiewall (bez zdecydowania czy zgadamy się lub nie nie rozpoczyna się pobieranie).
Może ktoś to już obszedł skryptem dla małpek (greasemonkey, violentmonkey, tampermonkey)._
