### ISSUE TITLE
jajamioasfalt.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8187]
nie pokazuje nastepnej strony

jest tak
![capture](https://user-images.githubusercontent.com/15007183/42116291-9ebaa298-7bc4-11e8-8210-ab76158370b3.PNG)

powinno byc tak
![capture1](https://user-images.githubusercontent.com/15007183/42116326-b77abf7a-7bc4-11e8-8a29-c8748e5743e7.PNG)

**Comment by krystian3w** [comment]
`jajamioasfalt.pl#@#center` a reklamy / puste sekcje po reklamach trzeba inaczej zablokować.

**Comment by xxcriticxx** [comment]
@krystian3w dziala thx
