### ISSUE TITLE
jednoslad.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#8191]
Antyadblock by Admiral
Może `@@||jednoslad.pl^$generichide` albo coś innego lepszego jeśli ktoś wymyśli.

**Comment by krystian3w** [comment]
`||ad2.onair.pl/www/delivery/asyncjs.php$domain=jednoslad.pl` - lepsze, chyba nie.

**Comment by krystian3w** [comment]
Na Firefox mi działa, ale może Nano Defender wspomaga.

Jest też opcja, że pracują tam w soboty i ogarnęli by plik przenieść.

**Comment by MajkiIT** [comment]
@hawkeye116477 Dziękuję

**Comment by krystian3w** [comment]
`||jednoslad.pl/wp-content/uploads/swPqOZktLZMW/HFNgnAtTxcls.js?ver=2.2.3` ale nazwa brzydka
