### ISSUE TITLE
podlaska.policja.gov.pl

### ISSUE THREAD

**Issue by Rzeszow** [MajkiIT/polish-ads-filter#8193]
### Zrzut ekranu
![image](https://user-images.githubusercontent.com/6783135/42127764-d15dff26-7c9e-11e8-8fd1-74e8c5060cb8.png)

### Link bezpośredni
http://podlaska.policja.gov.pl/pod/dzialania-policji/przestepczosc-gospodar/struktura-wydzialu/zespol-iii/p2p/28414,P2P.html

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Reklama występuje na każdej stronie. Chodzi dokładnie o tą po prawej (reklama wewnętrzna).

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome (chyba najnowsza, bo nie prosi o aktualizacje)
**Rozszerzenia i skrypty:**
uBlock
**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. I inne domyślne

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Sorry musiałem :trollface:

**Comment by Rzeszow** [comment]
`##div:nth-of-type(5)`
Powinno być ok.

**Comment by xxcriticxx** [comment]
@Rzeszow kiedy zostaniesz policjantem pamiętaj o nas

**Comment by hawkeye116477** [comment]
To @MajkiIT chyba raczej tego nie doda. Ale jeżeli nie będzie chciał, to ja to wtedy dodam do Polskich Filtrów EI i do Modułu Inne Widżety :smile:

**Comment by Rzeszow** [comment]
@hawkeye116477 Dzięki tylko w tobie moja nadzieja 😆
Ale jednak reklama to reklama. Każda reklama ma takie sama prawa aby została dodana.

**Comment by hawkeye116477** [comment]
Tylko, że @MajkiIT właśnie raczej wewnętrznych nie dodaje.

**Comment by xxcriticxx** [comment]
@hawkeye116477 Matt nie przerabial internals ads?

**Comment by hawkeye116477** [comment]
@xxcriticxx Nadal przerabia w swoim nowym repo. Ale ja też takie atrakcje dodaję (nie wszystkie, u niego jest szerszy zakres), tak samo jak i zresztą tła zawierające autoreklamy.

**Comment by xxcriticxx** [comment]
Narobiło się teraz 400 pl list

**Comment by Rzeszow** [comment]
Trzeba wszystkie w jedną złączyć i po sprawie. I tak w większości filtry się pewnie powtarzają. I przy okazji sprawdzać czy dana domena ponguje (ping).

**Comment by hawkeye116477** [comment]
@xxcriticxx No na repo PFT jest sporo :smile:. Specjalnie dla ciebie, osobna lista tylko z powiadomieniami Push i inne moduły => `https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/MODULES.md`.

**Comment by xxcriticxx** [comment]
@hawkeye116477 push push

**Comment by MajkiIT** [comment]
@Rzeszow @hawkeye116477 to zwykła informacja.

**Comment by Rzeszow** [comment]
@MajkiIT 
Ok. Zamykam.

**Comment by hawkeye116477** [comment]
@Rzeszow Dodałem => `https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/6fd126fd923b17773b448bca7002ff37b67e9104`, `https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/2450f0dd67b56ca346bf18e817a77621e5502da0` :smile:

**Comment by Rzeszow** [comment]
@hawkeye116477 Dzięki. Ale co to za wolne. Nieładnie tak. Przecież wystarczył by jakiś komunikat,że zgłoszenie zostanie rozpatrzone jutro czy coś.
