### ISSUE TITLE
tygodnik-krapkowicki.info

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#8194]
Reklamy na dole i po środku :smile:

**Comment by Rzeszow** [comment]
Jeszcze informacja o RODO 😢

**Comment by krystian3w** [comment]
`||tygodnik-krapkowicki.info/media/plg_system_eprivacy/js/eprivacy.js`

Albo na dwa tagi kosmetycznie `###sbox-window, #sbox-overlay` a jakby mieli takie pop-upy z jeszcze czymś innym to reguły kosmetyczne dobezpieczyć.

**Comment by hawkeye116477** [comment]
Już dawno komunikat RODO dodany, tylko jeszcze nie zacomitowane.

**Comment by krystian3w** [comment]
Czyli działa też: `###tabfour`?

**Comment by hawkeye116477** [comment]
Ktoś tu chyba zapomniał zamknąć, cookies merged, reklamy usunięte... Czy może coś jeszcze jest :smile:?
