### ISSUE TITLE
gothaer.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8198]
https://sprzedaz.gothaer.pl/turystyczne#!/main
![opera zdjecie_2018-07-01_121003_sprzedaz gothaer pl](https://user-images.githubusercontent.com/36385327/42133290-c9c4c4a0-7d27-11e8-9f65-6befb2c05a3e.png)

**Comment by krystian3w** [comment]
`##.ci-bar-wrapper`
