### ISSUE TITLE
koleje-wielkopolskie.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8200]
![opera zdjecie_2018-07-01_121238_koleje-wielkopolskie com pl](https://user-images.githubusercontent.com/36385327/42133310-11b5217e-7d28-11e8-9509-525a83d1bb8e.png)

**Comment by krystian3w** [comment]
`koleje-wielkopolskie.com.pl##.spu-bg` - rodo
