### ISSUE TITLE
mojmac.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8201]
Ukrywa 
![opera zdjecie_2018-07-01_122957_mojmac pl](https://user-images.githubusercontent.com/36385327/42133446-7da07ec2-7d2a-11e8-9006-f2f330f88230.png)

**Comment by krystian3w** [comment]
> <table><tr><td>
>
>Filtr statyczny `_reklama_$domain=~youtube.com` znajdujący się w:
> 
>   *  EasyList
> 
> </td></tr></table>
