### ISSUE TITLE
newsweek.pl

### ISSUE THREAD

**Issue by wmyrda** [MajkiIT/polish-ads-filter#8202]
na stronie stanadardowej oraz mobilnej wyświetla się w połowie strony wielgaśny baner na cały ekran informacja o dostęności do sprzedaży newsweek plus

Ponadto tylko na mobilnej wersji na dole strony wyświetla się okno z kuponami rabatowymi

**Comment by hawkeye116477** [comment]
Czyli to raczej do Polskich Filtrów EI :smile:
Tylko może przydałby się jakiś zrzut tego „wielgaśnego banera".

**Comment by xxcriticxx** [comment]
![capture](https://user-images.githubusercontent.com/15007183/42135360-fe78e4de-7d17-11e8-9559-fda8a1f21d0f.PNG)

**Comment by hawkeye116477** [comment]
No to nie taki wielki, miał być na cały ekran :smiley:.

**Comment by xxcriticxx** [comment]
na cell napewno na caly :)

**Comment by hawkeye116477** [comment]
A okno z kuponami?

**Comment by wmyrda** [comment]
dziwne, wczesniej sie nie mogłem pozbyć tego okna z kuponami, a teraz się nie wyświetla wcale
