### ISSUE TITLE
weranda.pl

### ISSUE THREAD

**Issue by wmyrda** [MajkiIT/polish-ads-filter#8204]
info o ciasteczkach
przy tym na wersji mobilnej to nawet nie wiadomo gdzie kliknąć by okno zniknęło, gdyż pojawia się jedynie opcja "więcej informacji"

**Comment by krystian3w** [comment]
Nie widzę, nawet na komputerze ❌, ale nawet AdBlock / Adblock Plus powinien dać radę wyciąć.

`weranda.pl##.popup-rodo, .popup-overlay`

---

Upewnij się, że uBlock Origin sobie nie wyłączył filtrów kosmetycznych:

> ![obraz](https://user-images.githubusercontent.com/35370833/42134710-7a02c2c2-7d41-11e8-8aa1-5b11b9598292.png) |
> --- |

**Comment by wmyrda** [comment]
nie wyłączył, mam dokładnie jak napisałeś (pierwsze 2 włączone, a trzeci nie)
.popup-rodo, .popup-overlay to jak rozumiem pownny być już na jakieś liście? Jeśli tak to której może jej mnie brakuje?

**Comment by krystian3w** [comment]
Nie ma - musiałem dodać na dev a na wersji dla wszystkich będą po pull requescie **`@`hawkeye116477** jak to przeanalizuje i przerzuci między dwoma repozytoriami by pasowało do głównego Majkiego.

Mogę jeszcze zerknąć czy mają tam coś poza opcją "więcej informacji" np. ❌  do zamknięcia wycięty źle jakąś regułą.

**Comment by krystian3w** [comment]
Jest przycisk, "tak akceptuje" i wycina go "`pl##.rodo-accept:not(body):not(html)`"

> ![obraz](https://user-images.githubusercontent.com/35370833/42135202-cb65f002-7d47-11e8-989d-ba3d1a65fff2.png) |
> --- |
