### ISSUE TITLE
orionagd.pl

### ISSUE THREAD

**Issue by wmyrda** [MajkiIT/polish-ads-filter#8207]
wersja mobilna - jakiś dziwny błąd (przynamniej na Firefox). Przycisk wstecz na androidzie zamiast cofać  do poprzedniej strony to przewija stronę w dół

**Comment by krystian3w** [comment]
Android 7, Firefox 61, uBlock Origin 1.16.12 - nie umiem zreprodukować żadnym przyciskiem wstecz (dolny z interfejsu Androida, Górny z menu (hamburgera - 3 pionowe kropki)).

**Comment by wmyrda** [comment]
również nie jestem w stanie tego zreprodukować po restarcie firefoxa. może to po porstu była kwestia braku pamięci w telefonie albo coś podobnego
