### ISSUE TITLE
niezlasztuka.net

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8208]
Ukrywa artykuł http://niezlasztuka.net/o-sztuce/historia-obrazu-altana-aleksander-gierymski/
![opera zdjecie_2018-07-01_154605_niezlasztuka net](https://user-images.githubusercontent.com/36385327/42135039-e4a9557e-7d45-11e8-8050-c1c968a2dbda.png)

**Comment by krystian3w** [comment]
Nie umiem odtworzyć, nawet pod zasubskrybowaniu:

Adguard’s Annoyance List​​​
​​​​​​Fanboy’s Annoyance List​
​​​​​​​​

**Comment by xxcriticxx** [comment]
ja tez widze cala strone

**Comment by krystian3w** [comment]
Wrzuć nam plik txt z konfiguracjom uBlock Orign @xMaap.

**Comment by krystian3w** [comment]
`@@||niezlasztuka.net/wp-content/plugins/NKS-subscription/js/nk-sub.min.js`

A do fanboyów trzeba by zgłosić dodanie do wyjątków - `/plugins/NKS-subscription/*` (za dużo wycina).

**Comment by krystian3w** [comment]
Wysuwany panel trzeba by ubić jakoś regułą skrytpową dla uBlock Origin lub CSS - skoro tyle napchali do `nk-sub.min.js`

> ![obraz](https://user-images.githubusercontent.com/35370833/42135831-10767a28-7d51-11e8-8986-c82a1986ca9d.png) |
> --- |

**Comment by hawkeye116477** [comment]
@krystian3w I tak w ogóle to twoja reguła średnio się sprawdza, bo po jakiś 2 minutach wszystko się przesuwa do lewej, robi się margines po prawej i po lewej ucina tekst. Pewnie trzeba byłoby wykombinować jakieś wstrzyknięcie js, ale w przypadku tego elementu to ja nie wiem co z tym fantem zrobić, a nasz ekspert @F4z niestety na urlopie ponoć. Chyba, że @gwarser coś poradzi :smile:.

**Comment by krystian3w** [comment]
Nie wiem jak ona sobie radzi jak nie wykryje elementu po załadowaniu, można by na każdym elemencie próbować od razu wymusić brak transformacji ale za lagi nie odpowiadam jak będą.

**Comment by krystian3w** [comment]
A nie, skrypt różnie generuje przesunięcie np. floatem:

```css
... {
float: left;
padding: 1.5em 3% 2.5em 6%;
}
```

**Comment by gwarser** [comment]
Na sidebar może `niezlasztuka.net##+js(setTimeout-defuser.js, i(), 99000)`, a biała strona to pewnie Fanboy albo inny Annoyances, bo tam są jakieś pluginy na prawoklik blokowane.

**Comment by hawkeye116477** [comment]
@gwarser Jest chyba ok, dzięki :smile:
