### ISSUE TITLE
podhale-sport.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8210]
![opera zdjecie_2018-07-01_160749_www podhale-sport pl](https://user-images.githubusercontent.com/36385327/42135275-14e57918-7d49-11e8-8844-dd8927c478d9.png)
![opera zdjecie_2018-07-01_160759_www podhale-sport pl](https://user-images.githubusercontent.com/36385327/42135279-1e929630-7d49-11e8-87f2-b9558f567d61.png)

**Comment by krystian3w** [comment]
Oni chyba nie wyszli z 1999-2002 roku, tyle tabel i jak chce wyciąć to się strona rozwala,

> ![obraz](https://user-images.githubusercontent.com/35370833/42135382-a0f526c8-7d4a-11e8-81a7-7a85c820c0fa.png) |
> --- |

**Comment by krystian3w** [comment]
`podhale-sport.pl##body > div > table > tbody > tr:nth-of-type(1):style(visibility: hidden !important;)`
