### ISSUE TITLE
magboss.pl

### ISSUE THREAD

**Issue by wmyrda** [MajkiIT/polish-ads-filter#8213]
cookies - okienko po prawej stronie z informacją o ciasteczkach

**Comment by krystian3w** [comment]
`magboss.pl#?#.alert-dismissable:-abp-contains(cookie)`

Nie wiem czy sklep ma inne komunikaty w prawym rogu możliwe do zamykania, jak nie ma to można usunąć sprawdzanie co ma w środku (by działało też w privoxy).
