### ISSUE TITLE
wakacyjnipiraci.pl

### ISSUE THREAD

**Issue by wmyrda** [MajkiIT/polish-ads-filter#8220]
na stronie mobilnej z uBlock - pasek u dołu o konieczności wyłączenia adblokera
PC przez privoxy - pasek u dołu z tekstem "Poprzez kontynuowanie przewijania, zgadzasz sie na korzystanie ze wszystkich zewnętrznych uslug"

#tarteaucitronAlertBig <- prawdopodobna przyczyna

**Comment by MajkiIT** [comment]
@hawkeye116477 @xxcriticxx macie to ?

**Comment by hawkeye116477** [comment]
Pojawia się na chwilę jak przewinię się stronę w dół.
