### ISSUE TITLE
sport.tvp.pl blokada antyublockowa antyfiltrowa

### ISSUE THREAD

**Issue by RafalMakac** [MajkiIT/polish-ads-filter#8227]
### Zrzut ekranu

https://i.gyazo.com/f25e252ac787633f0c6c717b6294e5ef.jpg

### Link bezpośredni

http://sport.tvp.pl/mundial2018/37292901/mundial-2018-18-finalu-brazylia-meksyk-transmisja-mecz-live

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejsc na strone 
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**

**Rozszerzenia i skrypty:**

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. Nano defender wraz z listami
3. Polskie Filtry RODO-Ciasteczkowe
4. Block-EU-Cookie-Shit-List

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by hawkeye116477** [comment]
Duplikat #8225

**Comment by xxcriticxx** [comment]
duplicate please see https://github.com/MajkiIT/polish-ads-filter/issues/8225

**Comment by krystian3w** [comment]
`@@||adservice.google.pl/adsid/integrator.js$script,domain=sport.tvp.pl,tvpstream.vod.tvp.pl`
