### ISSUE TITLE
newtech.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8229]
nie wiem jak to traktowac. @hawkeye116477 cos dla ciebie. 

![capture](https://user-images.githubusercontent.com/15007183/42178253-9af871f4-7dfd-11e8-999a-707aa6c14e5a.PNG)

**Comment by krystian3w** [comment]
Pop-up irytujący albo nowy sposób na detekcje blokady reklam...

**Comment by hawkeye116477** [comment]
@xxcriticxx To są te skutki uboczne czy nie ma?

**Comment by xxcriticxx** [comment]
@hawkeye116477 jakie skutki uboczne?

**Comment by hawkeye116477** [comment]
@xxcriticxx No po zastosowaniu reguły ||newtech.com.pl/js/script-min.js$script czy jest wszystko ok czy coś się psuje, logowanie w sklepie np :smile:

**Comment by xxcriticxx** [comment]
@hawkeye116477 zaponiales ze ja za lasami za gorami? nie kupuje w sklepach pl

**Comment by krystian3w** [comment]
Psuje zakładki: `Modele \ Parametry \ Załączniki`

http://www.newtech.com.pl/produkty/ifrm-05-krotkie-zblizeniowe-czujniki-indukcyjne

Więc zmienię to na blokowanie tylko dla uBlock Origin.

---

Można zamknąć @MajkiIT  / @xxcriticxx.
