### ISSUE TITLE
mobiltek.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#823]
Oferujemy taryfy:

    0,50 PLN + VAT / 0,62 PLN z VAT,
    1 PLN + VAT / 1,23 PLN z VAT,
    2 PLN + VAT / 2,46 PLN z VAT,
    3 PLN + VAT / 3,69 PLN z VAT,
    4 PLN + VAT / 4,92 PLN z VAT,
    5 PLN + VAT / 6,15 PLN z VAT.
    6 PLN + VAT / 7,38 PLN z VAT.
    7 PLN + VAT / 8,61 PLN z VAT.
    9 PLN + VAT / 11,07 PLN z VAT.

**Comment by MajkiIT** [comment]
co w tym złego?

**Comment by xxcriticxx** [comment]
to jest jakis platny service przez sms
