### ISSUE TITLE
syntax highlighting / podświetlenie składni filtrów adblock dla nano

### ISSUE THREAD

**Issue by wmyrda** [MajkiIT/polish-ads-filter#8230]
Ponieważ bez wyróżnienia składni nie wolę nie patrzeć na żaden plik zlewajacy się w identyczny ciąg znaków to też po lekturze [filters](https://adblockplus.org/filters) oraz [filter-cheatsheet](https://adblockplus.org/filter-cheatsheet) uznałem za stosowne by wyróżnić opisane tam sytuacje dla edytora tekstu **nano**, którego używam na codzień w linuksowej konsoli.

Przykład który stworzyłem jest dość prosty i pewnie można by go lepiej zapisać łącznie z innym doborem kolorów, ale zadanie swoje spełnia

_adblock.nanorc_ 
```
syntax adblock "\.txt$"
header "[Adblock Plus [1-9].[0-9]]"
comment "!"

color brightcyan "\.[a-z][a-z](#|,)" "^[a-z][a-z](#|,)" "\.[a-z][a-z][a-z](#|,)" "^[a-z][a-z][a-z](#|,)"
color brightgreen "\|\|"
color cyan "##"
color brightred "(@@\|\||#@#|~)"
color red "#\?#"
color red start=":-abp-(properties|has|contains)" end="\)"
color cyan ","
color magenta start="\[" end="\]"
color magenta start="\:style\(" end="\)"
color green "^!.*$"
color yellow "http.*/$"
color brightyellow "\[Adblock\ Plus\ [1-9].[0-9]\]$"
# Spaces in front of tabs.
color ,red " +  +"
# Trailing whitespace
color ,green "[[:space:]]+$"
```
plik najlepiej umieścić w /usr/share/nano by program załadował go automatycznie gdy używamy kolorowania składni, ewentualnie dodać jego lokalizację w pliku konfiguracyjnych /etc/nanorc tudzież [.nanorc](https://i.imgur.com/HSEhPj1.png)

a efekt wyglada tak [eg1](https://i.imgur.com/lXes87v.png), [eg2](https://i.imgur.com/tmoveLR.png), [eg3](https://i.imgur.com/OR00ZGi.png)

A tak przy okazji to zapisanie reguły bez `||` to poprawne jest jak w tym przypadku? `@@/social_media_$domain=mazury.travel`

**Comment by krystian3w** [comment]
A ja wciąż na swoją stronę nie umiem wrzuć Ace / CodeMirror - nie dogadują się z php i musiałbym napisać bardziej rozbudowany formularz.

**Comment by hawkeye116477** [comment]
Ja tam wolę VS Code `https://marketplace.visualstudio.com/items?itemName=adguard.adblock#review-details`

**Comment by wmyrda** [comment]
programiści mają swoje narzędzia, admini swoje ;) Łącząc się do terminala tekstowego to poza edytorem nano wiele wiecej nie ma także warto w nim czasemcoś pokolorować. A co to pliku jak chcecie to wrzućcie konfigurację gdzieś do dokumentacji, a jak nie to do zamknięcia

**Comment by wmyrda** [comment]
A muszę kolegów opieprzyć za jakieś dziwne spacja na końcach linii ;) Przez przypadek zobaczyłem że na wykopie reguła sed nie zamieniła mnie wpisu na strunkturę css. Sprawdzam czemu a tam w pliku cookies_uB_AG.txt są na końcu linijki jakieś dziwne spacje :P

<a href="https://i.imgur.com/hGKYNwU.png">
  <img src="https://imgur.com/hGKYNwUl.png" />
</a>

Mam nadzieję, że kolorowanie reguł wam to wychwytuje, gdyż one raczej są tam nadmiarowe

**Comment by hawkeye116477** [comment]
Nie kolorowało, ale znalazłem rozszerzenie, które to robi `https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces` :smile:

**Comment by krystian3w** [comment]
Ja spacji nie widzę w edytorze githuba więc to jest ciężkie do poprawy, dodatkowo uBlockowi Origin to wisi, kończy regułę na nawiasie.

**Comment by wmyrda** [comment]
Takich rzeczy się nie robi ręcznie ;)
Ja przed uruchomieniem adblock2privoxy je usunę sobie za pomocą `sed -i 's/[ \t]*$//' *.txt` dla wszystkich blocklist. I tak reguła będzie tam na wszelki wypadek musiała zostać, bo przy ~50 listach nie będę sprawdzał każdej czy jakiś podobny problem się pokazał czy nie :) Jest to całkowicie bezpieczne gdyż `sed` działa tak, że jak nie natrafi na zadaną regułę to poprostu dla danej linii nic nie robi i sprawdza następną.

Natomiast jeśli któryś z was ma dostęp do plików z repozytorium poza githubem i edytuje pod Linuksem to też by mógł przed wysyłką zmian odpalić tą regułe by je wszystkie pliki za jednym zamachem poprawić.

**Comment by krystian3w** [comment]
Ja bym to wywalił w notepad++ jakimś dużo prostszym regexem.
