### ISSUE TITLE
serialomaniak.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#8235]
brak ikon udostepniana artykulow pod tekstem, na stronie serialomaniak.pl

![1](https://user-images.githubusercontent.com/17565773/42210985-ab5372b4-7eb2-11e8-90f2-2d98f439d5e1.jpg)

jak dodam do wyjatkow

![2](https://user-images.githubusercontent.com/17565773/42211124-11c30ff0-7eb3-11e8-8c3d-af80f747ce0c.jpg)

**Comment by hawkeye116477** [comment]
No to chyba prawidłowo, filtr Społecznościowy powinien to ukrywać.

**Comment by hawkeye116477** [comment]
To jest wina EasyPrivacy i uBO Filters Privacy.

**Comment by krystian3w** [comment]
Zgłoś w [uAssets](https://github.com/uBlockOrigin/uAssets/issues) i zobacz co powiedzą, najwyżej Majki zostanie poproszony o dodanie wyjątków.

Wyłączenie important uAsset:
```
||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org,badfilter
```
Dopuszczenie polskiej:
```
||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org|~serialomaniak.pl
```
Wyjątki na EasyPrivacy:
```
@@||addthis.com/live/*$xmlhttprequest,domain=serialomaniak.pl
@@||addthisedge.com/$xmlhttprequest,domain=serialomaniak.pl
```

**Comment by lukjan32** [comment]
kto ma zglosic?

**Comment by hawkeye116477** [comment]
@lukjan32 Ty zgłoś to do `https://github.com/uBlockOrigin/uAssets/issues` i `https://github.com/easylist/easylist/issues/`.

**Comment by lukjan32** [comment]
aha, po angielsku?

**Comment by hawkeye116477** [comment]
@lukjan32 Tak

**Comment by lukjan32** [comment]
ok, a przy okazji tego player.pl. tez moge, w tych stronach?

**Comment by hawkeye116477** [comment]
@lukjan32 Tak, do uAssets jak najbardziej, może tam magicy prędzej coś wykombinują z player.pl :smile:.

**Comment by lukjan32** [comment]
dobra, dzieki, juz pisze

**Comment by lukjan32** [comment]
pomoga tam?

**Comment by hawkeye116477** [comment]
@lukjan32 Przecież już ktoś odpisał.

**Comment by lukjan32** [comment]
w sprawie serialomaniaku, to bedzie dodanie do filtrow?

szkoda, ze player.pl, ma geo lock :(

**Comment by lukjan32** [comment]
aha, szkoda.

**Comment by lukjan32** [comment]
takie cos w serialomaniak.pl.

#article > div:nth-child(5) > div.addthis_inline_share_toolbox.lazyloaded

lub

`<div class="addthis_inline_share_toolbox lazyloaded" data-script="https://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-57fa64b9d6528dd0" data-url="https://serialomaniak.pl/recenzja/sharp-objects-ostre-przedmioty-serial-recenzja" data-title="Rodzina z piekła rodem – przedpremierowa recenzja 7 odcinków „Sharp Objects”" data-description="Seriale oparte na książkach bardzo często muszą stawić czoła podwójnej krytyce, przez co stoi przed nimi o wiele trudniejsze zadanie niż dla innych produkcji. …" style="clear: both;"><div id="atstbx" class="at-resp-share-element at-style-responsive addthis-smartlayers addthis-animated at4-show" aria-labelledby="at-4f62b44a-6d14-4964-9cd1-2a42af8473a8" role="region"><span id="at-4f62b44a-6d14-4964-9cd1-2a42af8473a8" class="at4-visually-hidden">AddThis Sharing Buttons</span><div class="at-share-btn-elements"><a role="button" tabindex="1" class="at-icon-wrapper at-share-btn at-svc-wykop" style="background-color: rgb(251, 128, 63); border-radius: 0px;"><span class="at4-visually-hidden">Share to Wykop</span><span class="at-icon-wrapper" style="line-height: 32px; height: 32px; width: 32px;"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="at-svg-wykop-1" style="fill: rgb(255, 255, 255); width: 32px; height: 32px;" class="at-icon at-icon-wykop"><title id="at-svg-wykop-1">Wykop</title><g><g fill-rule="evenodd"></g><path d="M14.722 19.784l-3.48-6.832-2.667 1.36 3.82 7.497.056-.03.313.61 10.608-5.404-.48-.944-3.65-7.165-2.667 1.36 3.48 6.83-1.332.68-3.48-6.832-2.666 1.358 3.48 6.832-1.332.68z"></path><path d="M7.372 12.77c0-2.38 1.86-4.308 4.152-4.308h8.952c2.294 0 4.152 1.928 4.152 4.308v6.46c0 2.38-1.86 4.308-4.152 4.308h-8.952c-2.294 0-4.152-1.928-4.152-4.308v-6.46zM5 12.77v6.46C5 22.97 7.92 26 11.524 26h8.952C24.08 26 27 22.97 27 19.23v-6.46C27 9.03 24.08 6 20.476 6h-8.952C7.92 6 5 9.03 5 12.77z"></path></g></svg></span><span class="at-label" style="font-size: 11.4px; line-height: 32px; height: 32px; color: rgb(255, 255, 255);">Wykop</span></a><a role="button" tabindex="1" class="at-icon-wrapper at-share-btn at-svc-facebook" style="background-color: rgb(59, 89, 152); border-radius: 0px;"><span class="at4-visually-hidden">Share to Facebook</span><span class="at-icon-wrapper" style="line-height: 32px; height: 32px; width: 32px;"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="at-svg-facebook-2" style="fill: rgb(255, 255, 255); width: 32px; height: 32px;" class="at-icon at-icon-facebook"><title id="at-svg-facebook-2">Facebook</title><g><path d="M22 5.16c-.406-.054-1.806-.16-3.43-.16-3.4 0-5.733 1.825-5.733 5.17v2.882H9v3.913h3.837V27h4.604V16.965h3.823l.587-3.913h-4.41v-2.5c0-1.123.347-1.903 2.198-1.903H22V5.16z" fill-rule="evenodd"></path></g></svg></span><span class="at-label" style="font-size: 11.4px; line-height: 32px; height: 32px; color: rgb(255, 255, 255);">Facebook</span></a><a role="button" tabindex="1" class="at-icon-wrapper at-share-btn at-svc-twitter" style="background-color: rgb(29, 161, 242); border-radius: 0px;"><span class="at4-visually-hidden">Share to Twitter</span><span class="at-icon-wrapper" style="line-height: 32px; height: 32px; width: 32px;"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="at-svg-twitter-3" class="at-icon at-icon-twitter" style="fill: rgb(255, 255, 255); width: 32px; height: 32px;"><title id="at-svg-twitter-3">Twitter</title><g><path d="M27.996 10.116c-.81.36-1.68.602-2.592.71a4.526 4.526 0 0 0 1.984-2.496 9.037 9.037 0 0 1-2.866 1.095 4.513 4.513 0 0 0-7.69 4.116 12.81 12.81 0 0 1-9.3-4.715 4.49 4.49 0 0 0-.612 2.27 4.51 4.51 0 0 0 2.008 3.755 4.495 4.495 0 0 1-2.044-.564v.057a4.515 4.515 0 0 0 3.62 4.425 4.52 4.52 0 0 1-2.04.077 4.517 4.517 0 0 0 4.217 3.134 9.055 9.055 0 0 1-5.604 1.93A9.18 9.18 0 0 1 6 23.85a12.773 12.773 0 0 0 6.918 2.027c8.3 0 12.84-6.876 12.84-12.84 0-.195-.005-.39-.014-.583a9.172 9.172 0 0 0 2.252-2.336" fill-rule="evenodd"></path></g></svg></span><span class="at-label" style="font-size: 11.4px; line-height: 32px; height: 32px; color: rgb(255, 255, 255);">Twitter</span></a><a role="button" tabindex="1" class="at-icon-wrapper at-share-btn at-svc-google_plusone_share" style="background-color: rgb(220, 78, 65); border-radius: 0px;"><span class="at4-visually-hidden">Share to Google+</span><span class="at-icon-wrapper" style="line-height: 32px; height: 32px; width: 32px;"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="at-svg-google_plusone_share-4" class="at-icon at-icon-google_plusone_share" style="fill: rgb(255, 255, 255); width: 32px; height: 32px;"><title id="at-svg-google_plusone_share-4">Google+</title><g><path d="M12 15v2.4h3.97c-.16 1.03-1.2 3.02-3.97 3.02-2.39 0-4.34-1.98-4.34-4.42s1.95-4.42 4.34-4.42c1.36 0 2.27.58 2.79 1.08l1.9-1.83C15.47 9.69 13.89 9 12 9c-3.87 0-7 3.13-7 7s3.13 7 7 7c4.04 0 6.72-2.84 6.72-6.84 0-.46-.05-.81-.11-1.16H12zm15 0h-2v-2h-2v2h-2v2h2v2h2v-2h2v-2z" fill-rule="evenodd"></path></g></svg></span><span class="at-label" style="font-size: 11.4px; line-height: 32px; height: 32px; color: rgb(255, 255, 255);">Google+</span></a></div></div></div>`

**Comment by krystian3w** [comment]
To ty chcesz to odblokować czy dodatkowo ukrywać listą społecznościową?

**Comment by lukjan32** [comment]
odblokowac

**Comment by krystian3w** [comment]
To teraz blokuje ci lista wycinająca elementy społecznościowe?

**Comment by lukjan32** [comment]
tak, na stronie ich brak.

**Comment by lukjan32** [comment]
juz jest dobrze, dodali juz do filtrow

**Comment by lukjan32** [comment]
aha, juz nie ma w filtrach.

**Comment by krystian3w** [comment]
Jak już resetowałeś Operę to pewnie dlatego nie ma; możliwe, że zapomniałeś po teście usunąć z listy ręcznie dodanych filtrów.

**Comment by krystian3w** [comment]
Od resetu nie wróci na listę, jak dla mnie to zostaje jedynie reinstalacja Opery by nie usuwała zainstalowanego Nano Defender.

**Comment by lukjan32** [comment]
aha, lepiej to zostawie.

**Comment by hawkeye116477** [comment]
@lukjan32 To dziwnie ta Opera się zachowuje, ewentualnie wyśle id i hasło TeamViewera po jakiejś 17:00, to może coś wykombinujemy :smile:.

**Comment by lukjan32** [comment]
dodalem do wyjatkow, to mi wystarczy.

**Comment by lukjan32** [comment]
nie bedzie filtrow?

**Comment by krystian3w** [comment]
Wydaje mi się, że to jest dodane do PL listy; przestało działać?

Jak tak, to trzeba zobaczyć co zmodyfikowali w EasyPrivacy i czy była z tym związana aktualizacja w uBO.

**Comment by krystian3w** [comment]
`||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org|~sainsburys.jobs`

trzeba by poprawić negowanie @MajkiIT - dopisali sobie domenę i stare już nie działa.

**Comment by lukjan32** [comment]
aha, oby pomogl @MajkiIT

**Comment by krystian3w** [comment]
Dodaj sobie tymczasowo:

```
||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org|~sainsburys.jobs,badfilter
||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org|~sainsburys.jobs|~serialomaniak.pl
```

**Comment by lukjan32** [comment]
dzieki, dziala

**Comment by lukjan32** [comment]
znow brak :(

**Comment by krystian3w** [comment]
Pewnie kolejna strona popsuta i znów odblokowali to w uBo list.

**Comment by lukjan32** [comment]
aha, szkoda

**Comment by krystian3w** [comment]
Tak to jest jak strona pozwala byle co przemycać twórcom lub sama zbiera więcej niż oferuje.

**Comment by krystian3w** [comment]
Na Firefox po wyłączaniu blokady socialu się załadowują, może teraz coś się skopało dla Chrome / Opery (on wymagał więcej dopuszczeń / innych reguł np. 6 a w Firefox wystarczały 4)

**Comment by lukjan32** [comment]
nie bedzie dodane nowe filtry?

**Comment by krystian3w** [comment]
Dalej nie masz? W Operze 56 nie ma problemów uBo 1.16.16 / Nano Adblocker 1.0.0.69.

---

Na pewno musisz zrezygnować z list wycinających elementy społecznościowe lub dodać sobie ręcznie kilka wyjątków:

```
serialomaniak.pl#@#.addthis-smartlayers
serialomaniak.pl#@#.at-svc-wykop
serialomaniak.pl#@#.at-svc-facebook
serialomaniak.pl#@#.at-svc-twitter
serialomaniak.pl#@#.at-svc-google_plusone_share
serialomaniak.pl#@#.at-share-btn
@@||addthis.com^$third-party,domain=serialomaniak.pl

serialomaniak.pl#@#.fb-like
@@||facebook.com^*/plugins/like.php?$third-party,domain=serialomaniak.pl
```

---

Mogę jeszcze zerknąć czy da się w AdGuardzie (niby przez jakiś czas miałeś).

**Comment by lukjan32** [comment]
mam opera 56, ublock origin 1.16.16. nie mam filtrow wycinajacych elementow. musze dodac strona do wyjatkow, to jest.

**Comment by krystian3w** [comment]
Wyeksportuj kopię ustawień ublock origin do pliku i wrzuć jako załącznik do odpowiedzi lub na gist - [gist.github.com](https://gist.github.com/)

> ![image](https://user-images.githubusercontent.com/35370833/46146802-0028eb80-c264-11e8-8622-6d5ab8a3b626.png)

**Comment by hawkeye116477** [comment]
Musi zrezygnować z EasyPrivacy i uBO Filters Privacy :smile:.

**Comment by lukjan32** [comment]
[ublock-kopia-zapasowa_2018-09-27_15.12.14.txt](https://github.com/MajkiIT/polish-ads-filter/files/2424200/ublock-kopia-zapasowa_2018-09-27_15.12.14.txt)

**Comment by krystian3w** [comment]
![image](https://user-images.githubusercontent.com/35370833/46148367-349ea680-c268-11e8-8f40-5ff8b868d67e.png)

```
serialomaniak.pl#@#.addthis-smartlayers
serialomaniak.pl#@#.at-svc-wykop
serialomaniak.pl#@#.at-svc-facebook
serialomaniak.pl#@#.at-svc-twitter
serialomaniak.pl#@#.at-svc-google_plusone_share
serialomaniak.pl#@#.at-share-btn
@@||addthis.com^$third-party,domain=serialomaniak.pl

serialomaniak.pl#@#.fb-like
@@||facebook.com^*/plugins/like.php?$third-party,domain=serialomaniak.pl
```

bez tego nie ruszy.

**Comment by lukjan32** [comment]
gdzie sa te filtry?

**Comment by krystian3w** [comment]
One "siedzą" w Polskiej liście elementów społecznościowych:

> https://github.com/MajkiIT/polish-ads-filter/blob/149540374f2628ab57b5e6687bcd02c66fe4de2c/adblock_social_filters/adblock_social_list.txt#L357-L363

jak i w Fanboy’s Social Blocking List​​​​​​​​​:

> ![image](https://user-images.githubusercontent.com/35370833/46149538-d8895180-c26a-11e8-962b-f6833328c80b.png)

> ![image](https://user-images.githubusercontent.com/35370833/46149575-edfe7b80-c26a-11e8-8e42-3880b2780789.png)

**Comment by lukjan32** [comment]
aha, dodacie ten skrypt?

**Comment by krystian3w** [comment]
Raczej nie ¯\(°_o)/¯.

**Comment by KonoromiHimaries** [comment]
> aha, dodacie ten skrypt?

skryptów tutaj nie dodajemy
polecam ci usunąć wszystkie listy społecznościowe

**Comment by lukjan32** [comment]
dobra, musze dodac do wyjatkow.

**Comment by lukjan32** [comment]
brak ikon udoostepniania pod tekstem.

**Comment by krystian3w** [comment]
A to trzeba znów zobaczyć jakie postępy zrobili w uAssets i EasyPrivacy.

I pamiętaj, że włączone filtry social i tak wytną button - miałeś je wyłączyć z racji lubienia przycisków udostępniania.

**Comment by lukjan32** [comment]
nie mam filtrow social.

**Comment by krystian3w** [comment]
AMD podobno się psuje:

```
||addthis.com^$important,3p,domain=~missingkids.com|~missingkids.org|~sainsburys.jobs|~sitecore.com|~amd.com,badfilter
```
