### ISSUE TITLE
geekweek.pl

### ISSUE THREAD

**Issue by wmyrda** [MajkiIT/polish-ads-filter#8236]
ciasteczka - okno na cały ekran

stwierdzono na
- ublock na wersji mobilnej
- privoxy na wersji PC

**Comment by xxcriticxx** [comment]
jaka jest reszta domen z geekweek.pl?

![capture](https://user-images.githubusercontent.com/15007183/42215837-bf7387d6-7e8d-11e8-8891-b3e568ea6f96.PNG)

**Comment by hawkeye116477** [comment]
Taki sam skrypt jak na Polsacie, to też strona Zygmunta?
