### ISSUE TITLE
istockphoto.com

### ISSUE THREAD

**Issue by wmyrda** [MajkiIT/polish-ads-filter#8237]
info o ciasteczkach u góry ekranu

**Comment by xxcriticxx** [comment]
zdaje sie strona nie pl jest do tego cookie monster

**Comment by wmyrda** [comment]
Otworzyła się cała po polsku to nie wystarczy?

**Comment by xxcriticxx** [comment]
@wmyrda sorry u mnie po inglish

**Comment by wmyrda** [comment]
może masz w przeglądarce standardowo język angielski, albo mieszkasz poza pl dlatego tak ci się otworzyła. Ja mam wersję pl no chyba że to nie wystarczy to ok. Pozostanę przy stronach w domenie pl

**Comment by xxcriticxx** [comment]
@wmyrda don't worry reportuj co znajdziesz. wystarczylo proste wytlumaczenie.

**Comment by xxcriticxx** [comment]
w grupie (kupie) sila or sila i moc jest tylko w grupie

**Comment by wmyrda** [comment]
no spoko, ale invalid dalej widnieje ;)

**Comment by wmyrda** [comment]
nieważne, niezauważyłem "and removed " Pardon
