### ISSUE TITLE
reklamowy-sklep.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8242]
![opera zdjecie_2018-07-04_023138_reklamowy-sklep pl](https://user-images.githubusercontent.com/36385327/42250637-9670786c-7f32-11e8-8f51-89ba4bfdcad8.png)

**Comment by krystian3w** [comment]
`reklamowy-sklep.pl###rodo, #rodo-bgd`

**Comment by hawkeye116477** [comment]
Albo `||reklamowy-sklep.pl/js/rodo.js`
