### ISSUE TITLE
ctm.gdynia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8243]
![opera zdjecie_2018-07-04_023640_www ctm gdynia pl](https://user-images.githubusercontent.com/36385327/42250701-204df64a-7f33-11e8-93cd-1bf719b51ae9.png)

Plus Facebook
![opera zdjecie_2018-07-04_023723_www ctm gdynia pl](https://user-images.githubusercontent.com/36385327/42250718-39f0f4d0-7f33-11e8-9aa6-07a7a357d1e6.png)

**Comment by hawkeye116477** [comment]
`||ctm.gdynia.pl/js/alertbox.js`
