### ISSUE TITLE
wacetob.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8249]
![opera zdjecie_2018-07-04_035527_www wacetob com pl](https://user-images.githubusercontent.com/36385327/42252710-258c0f1a-7f3e-11e8-9654-4d7583f613f3.png)

**Comment by krystian3w** [comment]
`wacetob.com.pl###container > div:nth-of-type(5)` - można próbować inaczej doprezycować.

**Comment by hawkeye116477** [comment]
`wacetob.com.pl###container > div[style="position:fixed;left:0px;width:100%;height:60px; background-color:white;padding:5px;bottom:0px;opacity:0.85;filter:alpha(opacity=85);text-align:right;"]`
