### ISSUE TITLE
webinsider.pl

### ISSUE THREAD

**Issue by Eva850** [MajkiIT/polish-ads-filter#8258]
Po kilku sekundach od otwarcia część rzeczy na stronie zostaje ukryta i pojawia się komunikat o adblocku
screenshot: https://ibb.co/i4i9Uy
Moja konfiguracja: Firefox, Nano adblocker, Nano defender (unofficial, by @LiCybora)
Przykładowy link: https://webinsider.pl/raspberry-pi-samba-smb/

**Comment by MajkiIT** [comment]
@Eva850 a nie masz włączonej listy "uBlock filters – Experimental​​​​​​​​​" ?

**Comment by Eva850** [comment]
@MajkiIT reguła działa, dzięki

**Comment by hawkeye116477** [comment]
Po wciśnięciu „zbadaj element" włącza się wredny debugger, coś kombinują chyba...
