### ISSUE TITLE
focus.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#8262]
https://www.focus.pl/artykul/11-rzeczy-ktrych-nie-wiedziae-o-swoim-ukadzie-pokarmowym?page=1

![20180705-004-screenshot](https://user-images.githubusercontent.com/9846948/42307246-0d4cdcc8-8032-11e8-9311-dd195a1ff04e.png)

```
focus.pl##.article-social-media, .pull-right
```

**Comment by krystian3w** [comment]
Czysto, chyba znowu problem z Fanboy Social list i brakami.

**Comment by FadeMind** [comment]
Mam fanboy annoyances oraz enhanced tracking list :P

**Comment by krystian3w** [comment]
Sprawdzisz może wersje listy Polish Social, może znów się zawiesiła i nie aktualizuje lub nie aktualizują.

I jak się da to przeszukaj za flitem `.socializer-fb-share`.

**Comment by FadeMind** [comment]
![20180705-006-screenshot](https://user-images.githubusercontent.com/9846948/42309514-0f400526-8039-11e8-83d6-732e86c74711.png)

¯\\\_(ツ)\_/¯

**Comment by krystian3w** [comment]
Sprawdź czy zadziała twoja bez nazwy domeny:

`pl##.article-social-media, .pull-right`

Może AdGuard nie wie jak ma rozumieć tą regułę.

**Comment by krystian3w** [comment]
A już wiem znowu jakaś limitacja AdGuarda już o tym pisałem - nie umie on negować `display: block !important` w Chromium.

**Comment by wmyrda** [comment]
E tam jakiś mały przycisk. Mnie na privoxy to całą stronę rozwala ;) 

<img src="https://i.imgur.com/jHIrcJ7.png" alt="privoxy-focus.png" class="inline"/>

"Wczytanie nie powiodło się" generalnie oznacza, że privoxy zablokowało te elementy. Może dla tej strony któryś z nich jednak powinien działać?

**Comment by krystian3w** [comment]
W sumie nie, bez JavaScript strona się wyświetla, może poza funkcjami interaktywnymi.

A jak już to by się przydało ten pierwszy:

![image](https://user-images.githubusercontent.com/35370833/42322808-20ffdab4-805e-11e8-8b58-c6708cb1ccc7.png)

oraz trzeci CSS:

![image](https://user-images.githubusercontent.com/35370833/42322830-34fea46e-805e-11e8-9e21-130c61d430f8.png)

CSS, powinien przywrócić ład i skład elementów a jQuery może zapewni szczątkowe wsparcie funkcji interaktywnych (jak nie wymagają dodatkowych bibliotek).

----

Pytanie tylko czy przyblokowały to reguły czy niedostosowana konfiguracja serwera.

**Comment by krystian3w** [comment]
W sumie tylko Bootstrap (?), bez JavaScript strona się wyświetla, może poza funkcjami interaktywnymi.

![image](https://user-images.githubusercontent.com/35370833/42322830-34fea46e-805e-11e8-9e21-130c61d430f8.png)

CSS, powinien przywrócić ład, skład i działanie elementów.

Opcjonalnie jQuery do funkcji interaktywnych (jak nie wymagają dodatkowych bibliotek).:

![image](https://user-images.githubusercontent.com/35370833/42322808-20ffdab4-805e-11e8-8b58-c6708cb1ccc7.png)

A resztę jak wyłapie się jak  to ogólnie dopuścić.


----

Pytanie tylko czy przyblokowały to reguły czy niedostosowana konfiguracja serwera.

**Comment by hawkeye116477** [comment]
`Swoją drogą nie rozumiem dlaczego zawsze odsyłacie albo do nanoAdblockera czy zewnętrznych list :D`
Jeżeli to oni psują strony, to wtedy odsyłamy, bo skoro to oni zepsuli, to niech oni naprawiają :smile:. W tym przypadku skoro AdGuard ma problemy z poprawnym przetworzeniem reguły, to odsyłamy do Teamu AdGuarda :smile:.

**Comment by krystian3w** [comment]
Mamy po pół roku rozwiązanie dla chromium AdGuard:

`focus.pl#?#.socializer-fb-share`
