### ISSUE TITLE
programatory.com

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#8264]
RODO + YT i FB

**Comment by hawkeye116477** [comment]
Znwou strona zrobiona przy użyciu jakiejś nowoczesnej techniki, strach ruszać :smiley:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 

maybe `programatory.com###myModal` czy to sie zmienia?

**Comment by wmyrda** [comment]
@xxcriticxx u mnie na privoxy to zadziałało bez problemu

**Comment by xxcriticxx** [comment]
@wmyrda ciekawe czy sie nie zmienia?

**Comment by wmyrda** [comment]
@xxcriticxx  trudno powiedziec, ale skoro po kilku godzinach było dokładnie to samo to strzelam, że jednak nie

**Comment by xxcriticxx** [comment]
@hawkeye116477 regula wystarczy?

**Comment by wmyrda** [comment]
powiedzielem nie? miałem powiedzieć tak. :D
Sąsiadowi się syn urodził to pewnie za dużo spożyłem także na dziś się więcej nie wypowiadam by znowu jakiejś głupoty nie palnąć ;)

**Comment by hawkeye116477** [comment]
Tak właściwie to już dodałem, tylko nie było PR jeszcze, bo mało jest do dodania, nie opłaca się, będzie jutro jak będzie więcej :smile:
