### ISSUE TITLE
mowianamiescie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8270]
![opera zdjecie_2018-07-06_003808_mowianamiescie pl](https://user-images.githubusercontent.com/36385327/42351362-e44eee64-80b4-11e8-8d30-275fd3ee521e.png)

**Comment by krystian3w** [comment]
`mowianamiescie.pl###rodo`
...`,mowianamiescie.pl##.modal-open:style(overflow: auto !important; padding-right: 0px !important;)`

**Comment by hawkeye116477** [comment]
Wystarczy `||mowianamiescie.pl/themes/mnm/js/rodo/rodo.js`
