### ISSUE TITLE
adm-media.pl + otolaryngolodzy24.pl + prow.lubelskie.pl + kociadolina.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8272]
![opera zdjecie_2018-07-06_005122_otolaryngolodzy24 pl](https://user-images.githubusercontent.com/36385327/42351742-e05e2444-80b6-11e8-9bc1-f11e20a4949c.png)

**Comment by krystian3w** [comment]
`adm-media.pl,kociadolina.pl##.policy`
`otolaryngolodzy24.pl,prow.lubelskie.pl###rodo-policy`
