### ISSUE TITLE
tvs.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#8281]
RODO

**Comment by xxcriticxx** [comment]
`tvs.pl##.notify`

**Comment by krystian3w** [comment]
`##.RodoNotyfication`?

**Comment by xxcriticxx** [comment]
@hawkeye116477 napewno w barze again!

**Comment by wmyrda** [comment]
Będę oryginalny :) U mnie na privoxy bez zarzutu zadziałało ###RodoNotificationWrapper

**Comment by krystian3w** [comment]
Ale to to samo co klasa `##.RodoNotyfication` 😉
