### ISSUE TITLE
innpoland.pl + mamadu.pl + aszdziennik.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8285]
http://mamadu.pl/137649,baner-w-opolu-jest-manipulacja-fundacji-pro-life
http://innpoland.pl/144755,znalezli-sposob-na-chronienie-sloni-i-nosorozcow-rozowe-kly-i-rogi
http://aszdziennik.pl/123655,sad-najwyzszy-z-namiotem-na-openerze
Ukrywa opcje skomentuj i obraz

Włączony
![opera zdjecie_2018-07-08_014125_mamadu pl](https://user-images.githubusercontent.com/36385327/42415477-2d9f7f56-8250-11e8-9257-f064822bf540.png)

Wyłączony
![opera zdjecie_2018-07-08_014252_mamadu pl](https://user-images.githubusercontent.com/36385327/42415481-415225e4-8250-11e8-88ba-ae616757ffe9.png)

http://mamadu.pl
Social
![opera zdjecie_2018-07-08_014604_mamadu pl](https://user-images.githubusercontent.com/36385327/42415495-b5e3fe3c-8250-11e8-9379-916f8ae1201f.png)

**Comment by hawkeye116477** [comment]
Obraz i komentarze to nie wina Sociala, to schował łobuziak @MajkiIT => `mamadu.pl#@#.art__header__photo` :smiley:

**Comment by hawkeye116477** [comment]
@MajkiIT Otwieramy ponownie. Trzeba usunąć wadliwą regułę z Listy Reklamowej :smile:.
