### ISSUE TITLE
poloniawroclaw.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8290]
![opera zdjecie_2018-07-08_022105_www poloniawroclaw pl](https://user-images.githubusercontent.com/36385327/42415647-d26661bc-8255-11e8-9127-9aadfeeae808.png)

**Comment by hawkeye116477** [comment]
U mnie wyskakuje normalny pop-up, ale on jest wewnętrzny.

**Comment by krystian3w** [comment]
A u mnie tylko cień i nie wiadomo po czym...
