### ISSUE TITLE
russ.uwm.edu.pl + radioaktywne.pl + centrum.fm

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8294]
Social

https://centrum.fm
![opera zdjecie_2018-07-08_085336_centrum fm](https://user-images.githubusercontent.com/36385327/42417510-72d912b2-828c-11e8-9a58-e73b740bb225.png)

https://radioaktywne.pl
![opera zdjecie_2018-07-08_085414_radioaktywne pl](https://user-images.githubusercontent.com/36385327/42417516-85b2101e-828c-11e8-89d0-d26cc8143d56.png)

http://russ.uwm.edu.pl
![opera zdjecie_2018-07-08_085449_russ uwm edu pl](https://user-images.githubusercontent.com/36385327/42417519-98d3a98c-828c-11e8-8df7-bdf604ef4b08.png)

**Comment by krystian3w** [comment]
```
centrum.fm##.fb

centrum.fm##.rss

radioaktywne.pl###iglogo

radioaktywne.pl###fblogo

russ.uwm.edu.pl##.vc_icon_element-inner
```
