### ISSUE TITLE
gemlord.pl + balneokosmetyki.pl + panlis.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8295]
https://gemlord.pl
![opera zdjecie_2018-07-08_085942_gemlord pl](https://user-images.githubusercontent.com/36385327/42417541-49330df4-828d-11e8-9e64-f7f932af7dbb.png)

http://www.balneokosmetyki.pl
![opera zdjecie_2018-07-08_090003_www balneokosmetyki pl](https://user-images.githubusercontent.com/36385327/42417542-57669666-828d-11e8-866d-8352d26f5d49.png)

https://panlis.pl
![opera zdjecie_2018-07-08_090032_panlis pl](https://user-images.githubusercontent.com/36385327/42417544-67f7af88-828d-11e8-9434-c409cb7c904d.png)

**Comment by krystian3w** [comment]
`gemlord.pl##div.k_footcol:nth-of-type(3)`
`balneokosmetyki.pl##.top-fb`
`||panlis.pl/public/assets/KONTAKT/logo-*.jpg`
`||panlis.pl/public/assets/KONTAKT/snapcode*.jpg`

---

`panlis.pl,gemlord.pl##.up`

---

`panalisa` można po tabelkach czy jakoś tak by mu nie psuć zakładki kontakt - ale to już raczej użytkownik powinien być świadomy, że może zostać tam po liście e-mail, telefon, adres lokalu i raczej nic więcej...
