### ISSUE TITLE
xfactor.tvn.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#8296]
social 

http://xfactor.tvn.pl/wideo,2103,v/tego-nie-bylo-w-tv-czyli-daria-zawialow-na-scenie-x-factor,715600.html

![20180708-001-screenshot](https://user-images.githubusercontent.com/9846948/42420675-9dfb7556-82c9-11e8-99c2-677baaf91c85.png)

`xfactor.tvn.pl##.socialFeedback`

`xfactor.tvn.pl##div:nth-child(6) > div.bgHolder:last-child > div.mainContent:nth-child(3) > article.videoDetail > div.content.hasNext.hasPrev:nth-child(2) > div.socialFeedback:last-child`

**Comment by krystian3w** [comment]
* `xfactor.tvn.pl##.facebook_share, .twitter_share, .gplus_share` 

lub:

* `xfactor.tvn.pl##.socialFeedback > .socialContainer > a:nth-child(-n+3)`

przycisk komentarzy bym zostawił (szary).

+

Na bugi Fanboya:

`@@/img/social_sprite.png$image,domain=tvn.pl`
