### ISSUE TITLE
jesteś popularny na dobreprogramy.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#830]
haxorek   3
#52
10.05.2016 10:08

@dzikiwiepsz: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adbloc...

i 0 reklam na wp.pl :)

**Comment by xxcriticxx** [comment]
xxcriticxx (niezalogowany)
10.05.2016 21:34
Komentarz oczekuje na zatwierdzenie przez moderatora

https://github.com/MajkiIT/polish-ads-filter/issues

**Comment by MajkiIT** [comment]
dzięki
