### ISSUE TITLE
poradnikbudowlany.eu

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8305]
Pełno reklam
http://poradnikbudowlany.eu
http://poradnikbudowlany.eu/krzew-mojzesza-ktory-goreje-dyptam-jesionolistny/
![opera zdjecie_2018-07-09_095605_poradnikbudowlany eu](https://user-images.githubusercontent.com/36385327/42437848-97f728cc-835e-11e8-9172-62f67e8b362e.png)
![opera zdjecie_2018-07-09_095614_poradnikbudowlany eu](https://user-images.githubusercontent.com/36385327/42437849-9817034a-835e-11e8-84a4-e8c716fbd1b4.png)
![opera zdjecie_2018-07-09_095629_poradnikbudowlany eu](https://user-images.githubusercontent.com/36385327/42437850-983f732a-835e-11e8-8cf4-d0f2d17240a4.png)
![opera zdjecie_2018-07-09_095645_poradnikbudowlany eu](https://user-images.githubusercontent.com/36385327/42437851-98621df8-835e-11e8-9e27-1cc4ca62d964.png)
![opera zdjecie_2018-07-09_095659_poradnikbudowlany eu](https://user-images.githubusercontent.com/36385327/42437852-9885edaa-835e-11e8-8178-2bba31d71646.png)
![opera zdjecie_2018-07-09_095709_poradnikbudowlany eu](https://user-images.githubusercontent.com/36385327/42437853-98a93b98-835e-11e8-8102-80b291ca6a39.png)

**Comment by krystian3w** [comment]
`[id^="pb_revive-"]`, na głównej jak patrzyłem to można by tak uprościć teoretycznie do jednej.
