### ISSUE TITLE
starachowice-net.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8312]
![opera zdjecie_2018-07-10_035031_starachowice-net pl](https://user-images.githubusercontent.com/36385327/42484714-9e2941b2-83f4-11e8-92ac-80310d4a4287.png)

**Comment by krystian3w** [comment]
`/ads.js?` - EasyList i ciastka przypadkiem wycieli.

Zaktualizuj listę EasyList?
