### ISSUE TITLE
zmianynaziemi.pl + innemedium.pl + tylkoastronomia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8313]
Ukrywa logo (zmianynaziemi.pl), RSS, Google Play. Jeśli Google Play jednak nie pasuje to przydało by się to ukryć też w innemedium.pl.

**Comment by MajkiIT** [comment]
```
zmianynaziemi.pl#@#[id^="block-block-"]
zmianynaziemi.pl###block-block-27, #block-block-19, #block-block-32, #block-block-16
innemedium.pl###block-block-16, #block-block-19, #block-block-17, #block-views-reklama-block
tylkoastronomia.pl###block-block-16, #block-block-18
```

**Comment by wmyrda** [comment]
Lekki offtop
Z tej grupy jedynie `tylkoprzyroda.pl` oraz `zmianysolarne.pl` ładują pliki css serwowane przez privoxy. Już tydzień się przygladam temu czym się różni np. taka `zmianynaziemi.pl` gdyż nawet info nie ma w przeglądarce by cokolwiek jakiś plik pominęło jak to zwykle robi w przypadku csp/cors czy podobnych. Po stronie privoxy w logach też nic widzę, a konfigi są identyczne dla obu
<a href="https://i.imgur.com/maoRFcNl.png">
  <img src="https://imgur.com/maoRFcNl.png" />
</a> vs <a href="https://i.imgur.com/K9JBUAM.png">
  <img src="https://imgur.com/K9JBUAMl.png" />
</a>

**Comment by xMaap** [comment]
@MajkiIT to jeszcze:

https://tylkonauka.pl/wiadomosc/po-raz-pierwszy-opracowano-sztuczna-inteligencje-z-dna
Ukrywa logo + social
![opera zdjecie_2018-07-10_130036_tylkonauka pl](https://user-images.githubusercontent.com/36385327/42506137-4930108a-8441-11e8-8444-78b1678e0b00.png)

https://tylkomedycyna.pl
![opera zdjecie_2018-07-10_130115_tylkomedycyna pl](https://user-images.githubusercontent.com/36385327/42506160-59f078ce-8441-11e8-882b-304615245c2c.png)
https://tylkomedycyna.pl/wiadomosc/12-najzdrowszych-odmian-salaty
![opera zdjecie_2018-07-10_130132_tylkomedycyna pl](https://user-images.githubusercontent.com/36385327/42506167-693d50d6-8441-11e8-8fff-9211c73c614a.png)
![opera zdjecie_2018-07-10_130644_tylkomedycyna pl](https://user-images.githubusercontent.com/36385327/42506407-1e0f69a4-8442-11e8-8345-2ab72b2b27a1.png)


https://tojuzbylo.pl
Ukrywa RSS
![opera zdjecie_2018-07-10_130207_tojuzbylo pl](https://user-images.githubusercontent.com/36385327/42506191-7f43b532-8441-11e8-9cd9-6cc93fb716d0.png)
![opera zdjecie_2018-07-10_130240_tojuzbylo pl](https://user-images.githubusercontent.com/36385327/42506217-8f245eb6-8441-11e8-8320-7764056e430d.png)
https://tojuzbylo.pl/wiadomosc/w-hiszpanii-odkryto-kapsule-czasu-nie-zgadniecie-gdzie-byla-ukryta
![opera zdjecie_2018-07-10_130320_tojuzbylo pl](https://user-images.githubusercontent.com/36385327/42506252-a492c878-8441-11e8-8b4b-3797e362a6e8.png)
![opera zdjecie_2018-07-10_130527_tojuzbylo pl](https://user-images.githubusercontent.com/36385327/42506358-f3571e6e-8441-11e8-9490-260ce08e0072.png)


https://superdania.pl
![opera zdjecie_2018-07-10_130410_superdania pl](https://user-images.githubusercontent.com/36385327/42506290-c2f64a06-8441-11e8-80df-a22dc4d42184.png)
https://superdania.pl/wiadomosc/pizza-laczy-ludzi
![opera zdjecie_2018-07-10_130505_superdania pl](https://user-images.githubusercontent.com/36385327/42506344-e3edfc7c-8441-11e8-9b56-1b60fd6180c2.png)

https://tylkoastronomia.pl/wiadomosc/nasa-planuje-wyslac-na-tytana-lodz-podwodna
![opera zdjecie_2018-07-10_130809_tylkoastronomia pl](https://user-images.githubusercontent.com/36385327/42506508-5dd9f37e-8442-11e8-8a8c-f244160276dd.png)
![opera zdjecie_2018-07-10_130846_tylkoastronomia pl](https://user-images.githubusercontent.com/36385327/42506520-67a3e5ea-8442-11e8-8461-1b6a2cae6b20.png)

https://innemedium.pl/wiadomosc/starozytna-katastrofa-mogla-zniszczyc-inne-cywilizacje-z-ukladu-slonecznego
![opera zdjecie_2018-07-10_130950_innemedium pl](https://user-images.githubusercontent.com/36385327/42506575-948c17da-8442-11e8-837d-cb0e2ecc9f01.png)
![opera zdjecie_2018-07-10_131000_innemedium pl](https://user-images.githubusercontent.com/36385327/42506580-97d0a1fe-8442-11e8-980e-eb468c8f2518.png)

https://jejportal.pl/wiadomosc/4-pielegnacyjne-zastosowania-ananasa-dla-twojej-skory
![opera zdjecie_2018-07-10_131133_jejportal pl](https://user-images.githubusercontent.com/36385327/42506647-ca810c7e-8442-11e8-8aa4-908827f3aeb7.png)

http://zmianysolarne.pl/wiadomosc/slonce-wciaz-spokojne-kiedy-czeka-nas-wzrost-aktywnosci
![opera zdjecie_2018-07-10_131246_zmianysolarne pl](https://user-images.githubusercontent.com/36385327/42506724-fd55ab0a-8442-11e8-91da-6867eb661951.png)
![opera zdjecie_2018-07-10_131256_zmianysolarne pl](https://user-images.githubusercontent.com/36385327/42506725-fd75ffc2-8442-11e8-9888-98c4224578de.png)
