### ISSUE TITLE
interia.pl + pomponik.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8314]
Reklamy:

https://motoryzacja.interia.pl
![opera zdjecie_2018-07-10_052505_motoryzacja interia pl](https://user-images.githubusercontent.com/36385327/42487533-b67f5b0e-8401-11e8-8411-2760b74e1b9c.png)

https://gry.interia.pl
![opera zdjecie_2018-07-10_052603_gry interia pl](https://user-images.githubusercontent.com/36385327/42487562-d0769a5e-8401-11e8-8cdd-2ebfcff1f1cc.png)
https://gry.interia.pl/newsy/news-ujawniono-date-premiery-darksiders-iii,nId,2604538
![opera zdjecie_2018-07-10_052653_gry interia pl1](https://user-images.githubusercontent.com/36385327/42487582-ed62e640-8401-11e8-9acf-a61e9421d2e6.png)

Ukrywa ikonę skomentuj:

http://biznes.interia.pl/wiadomosci/news/pgg-wydobedzie-prawie-31-mln-ton-wegla-tobiszowski,2578429,4199
https://eurosport.interia.pl/raporty/raport-ms-rosja-2018/aktualnosci/news-mundial-2018-lekarz-rosyjskiej-kadry-potwierdza-pilkarze-wdy,nId,2604541
https://muzyka.interia.pl/raporty/raport-opener-festival-2018/wiadomosci/news-dawid-podsiadlo-na-open-er-festival-2018-nasze-dobro-narodow,nId,2603850
https://www.pomponik.pl/plotki/news-milionerka-wieniawa-nie-chce-slyszec-o-slubie-dlatego-w-nowy,nId,2604250
https://fakty.interia.pl/raporty/raport-brytyjskie-referendum/aktualnosci/news-johnson-strategia-may-w-sprawie-brexitu-to-wywieszenie-biale,nId,2604585

Włączone
![opera zdjecie_2018-07-10_052924_biznes interia pl](https://user-images.githubusercontent.com/36385327/42487653-3b971412-8402-11e8-9461-ed73b09d808a.png)
Wyłączone
![opera zdjecie_2018-07-10_052957_biznes interia pl](https://user-images.githubusercontent.com/36385327/42487676-53266e70-8402-11e8-9577-3ce3a8d694e8.png)

**Comment by xMaap** [comment]
Jeszcze tutaj
https://zapachove.interia.pl/polecamy/news-okazje-do-swietowania-w-lipcu,nId,2603031
![opera zdjecie_2018-07-10_053808_zapachove interia pl](https://user-images.githubusercontent.com/36385327/42487943-86c9918e-8403-11e8-8ce0-a970f50e9da7.png)

https://www.interia.pl
gemius
![opera zdjecie_2018-07-10_054100_www interia pl](https://user-images.githubusercontent.com/36385327/42488064-1a8a8482-8404-11e8-8c82-2213935adc63.png)
click + gemius
![opera zdjecie_2018-07-10_054358_www interia pl](https://user-images.githubusercontent.com/36385327/42488111-4b8432c2-8404-11e8-94e1-fdb9eb22bbb2.png)

**Comment by krystian3w** [comment]
`[href*=".hit.gemius.pl"]` - wycina licznik w `http://m.interia.pl/biznes/news,2578429` (Polish Privacy Filters)
