### ISSUE TITLE
wycena.otodom.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8315]
![opera zdjecie_2018-07-10_124636_wycena otodom pl](https://user-images.githubusercontent.com/36385327/42505546-54259b88-843f-11e8-96a1-4371bf4d3a15.png)

**Comment by wmyrda** [comment]
wycena.otodom.pl##.landend-infobar-dark - ciasteczka
wycena.otodom.pl##.widget-box,.widget-html - socjale na dolnym pasku
