### ISSUE TITLE
transfery.info

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8317]
http://transfery.info
http://transfery.info/publicystyka
http://transfery.info/116283,oficjalnie-ronaldo-w-juventusie

Ukrywa
Wyłączony
![opera zdjecie_2018-07-10_175252_transfery info](https://user-images.githubusercontent.com/36385327/42521860-1bc7aeea-846a-11e8-9e4a-c571a3b3f5df.png)
Włączony
![opera zdjecie_2018-07-10_175345_transfery info](https://user-images.githubusercontent.com/36385327/42521941-3bdfd6a8-846a-11e8-92f6-178623a82ab1.png)

**Comment by krystian3w** [comment]
`transfery.info##.blok` - do aktualizacji
