### ISSUE TITLE
sznyt.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8320]
https://sznyt.pl/2018/07/05/oto-odnowiony-mustang-302-boss-nalezacy-roberta-downey-jr/
Social
![opera zdjecie_2018-07-11_082334_sznyt pl](https://user-images.githubusercontent.com/36385327/42554114-e67835d2-84e3-11e8-91a3-6e4664ec2c27.png)
![opera zdjecie_2018-07-11_082507_sznyt pl](https://user-images.githubusercontent.com/36385327/42554127-f0907b88-84e3-11e8-85c4-03d1f51e5524.png)

**Comment by krystian3w** [comment]
```
sznyt.pl##li.is-hidden-mobile:nth-of-type(-n+3) > .bar-nav-icon
sznyt.pl##.article-comment-button__link--facebook
```
