### ISSUE TITLE
porozmawiajmyoit.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8323]
Ukrywa logo

**Comment by krystian3w** [comment]
Mnie nie ukrywa, rób może jednak zrzut jak wycina i jak wraca po włączeniu reklam.

**Comment by krystian3w** [comment]
Opcjonalnie mogę odblokować tekstową subskrypcje podcastu:

`porozmawiajmyoit.pl#@#.subscribe-text` - chwilowo nie dodaję, bo nie mam pewności.
Podobnie nie wiem czy wyciąć iTunes i YouTube - wycięcie jak dla mnie psuje funkcjonalność jego strony.

**Comment by xMaap** [comment]
Włączony
![opera zdjecie_2018-07-11_174139_porozmawiajmyoit pl](https://user-images.githubusercontent.com/36385327/42583659-be1f4a32-8531-11e8-9207-eed716d91026.png)
Wyłączony
![opera zdjecie_2018-07-11_174155_porozmawiajmyoit pl](https://user-images.githubusercontent.com/36385327/42583675-c38d0e5a-8531-11e8-8893-ad27239fed28.png)

**Comment by krystian3w** [comment]
Stary plik konfiguracyjny Nano Adblockera aktualny?
