### ISSUE TITLE
e-podroznik.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#8329]
" Lubisz nas ? Pokaż to ! " ( na dole )

**Comment by krystian3w** [comment]
`##.DefinitionsSet\:\:SocialNetworks`

**Comment by wmyrda** [comment]
@krystian3w 
przez generator adblock2privoxy jeszcze nie przepuszczałem, ale powinno działać gdyż
`.DefinitionsSet\:\:SocialNetworks{display:none!important;visibility:hidden!important}` zadziałało bez problemu
