### ISSUE TITLE
e-torro.pl

### ISSUE THREAD

**Issue by wmyrda** [MajkiIT/polish-ads-filter#8334]
cisteczka i socjale

e-torro.pl###oiTab
e-torro.pl###facebook
e-torro.pl###cookiesBar

**Comment by krystian3w** [comment]
Znów social w miarę ogarnia baza - Fanboy Social blocking list.

`e-torro.pl###oiTab` - jak to jest widget o opinii to to wycina polska lista EI (elementów irytujących).
