### ISSUE TITLE
solojuve.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8339]
Włączony
![opera zdjecie_2018-07-11_174626_solojuve com](https://user-images.githubusercontent.com/36385327/42583933-5c3a4c76-8532-11e8-976b-5b08683cb8b1.png)
Wyłączony
![opera zdjecie_2018-07-11_174658_solojuve com](https://user-images.githubusercontent.com/36385327/42583961-6ecc53ca-8532-11e8-8d11-b458bfb9ac1a.png)

**Comment by krystian3w** [comment]
`solojuve.com#@##socialWrapper`
