### ISSUE TITLE
magnapolonia.org

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8340]
![opera zdjecie_2018-07-11_174737_www magnapolonia org](https://user-images.githubusercontent.com/36385327/42584029-8a6cd082-8532-11e8-9ffc-e956b15258d5.png)

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/42584188-e8c990ca-8532-11e8-970c-37c3de0aea72.png) |
--- |

Brzydki pop-up z reklamą.
