### ISSUE TITLE
romet.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8341]
Social
https://www.romet.pl/Motocykle,3,0.html
![opera zdjecie_2018-07-11_175237_www romet pl](https://user-images.githubusercontent.com/36385327/42584322-3b841ce0-8533-11e8-85a4-5e170f80e89a.png)

**Comment by krystian3w** [comment]
I zablokowany prawy klik.

**Comment by blocker999** [comment]
@krystian3w Prawy klik to chyba do EI bo MajkiIT  tego niezbiera

**Comment by krystian3w** [comment]
Już dodałem jest na głównej i wersji paf.
