### ISSUE TITLE
triathlonprzechlewo.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8342]
Social
![opera zdjecie_2018-07-11_175340_triathlonprzechlewo pl](https://user-images.githubusercontent.com/36385327/42584408-6e646c50-8533-11e8-98d8-dda6dd45f50b.png)

**Comment by krystian3w** [comment]
`triathlonprzechlewo.pl###menu-triathlon-przechlewo-pl-1 > li:nth-child(7)`
`triathlonprzechlewo.pl##.grve-social`
