### ISSUE TITLE
instalnet.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8350]
![opera zdjecie_2018-07-12_093910_www instalnet pl](https://user-images.githubusercontent.com/36385327/42619161-87db9f3a-85b7-11e8-8a0e-c58737637615.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 to chyba twoje.

**Comment by krystian3w** [comment]
Kij wie to ostrzeżenie, że ktoś się pod firmę podszywa czy coś:

![obraz](https://user-images.githubusercontent.com/35370833/42626867-abd5e12a-85cb-11e8-91a5-9c5e5effd1f7.png)

**Comment by krystian3w** [comment]
Nie nasze, ukrywa to:

> 
> Filtr statyczny `##div[data-cookie]` znajdujący się w:
> 
>    * Fanboy’s Annoyance List
>    * Fanboy’s Cookiemonster List
