### ISSUE TITLE
mikroporady.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8351]
![opera zdjecie_2018-07-12_094010_mikroporady pl](https://user-images.githubusercontent.com/36385327/42619189-9c697db4-85b7-11e8-9d81-f248b41c69c3.png)

**Comment by hawkeye116477** [comment]
Na górze widzę dziurę po ciastkach/RODO, ale reklam nie widzę. Jedynie nachalne komunikaty o wsparciu, starczyłby ten komunikat na górze, ale nie, musieli oczywiście dowalić jeszcze mniejszy jeżdżący za scrollem komunikat.

**Comment by MajkiIT** [comment]
@hawkeye116477 są twoje :P

**Comment by hawkeye116477** [comment]
Coś mocno nachalni, już w 5 miejscach znalazłem informacje o wsparciu.
