### ISSUE TITLE
kobietaxl.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8352]
![opera zdjecie_2018-07-12_094103_www kobietaxl pl](https://user-images.githubusercontent.com/36385327/42619225-b770853a-85b7-11e8-9c41-162c1c2ddb2c.png)

**Comment by MajkiIT** [comment]
```
www.kobietaxl.pl###adblock-belka-container
www.kobietaxl.pl##.public-ad-container > div > span
```
