### ISSUE TITLE
inkipinki.pl + cocoshki.pl + bascat.pl + tinystar.pl + helloforma.com + spodiglyinitki.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8353]
http://www.inkipinki.pl
![opera zdjecie_2018-07-12_120950_www inkipinki pl](https://user-images.githubusercontent.com/36385327/42627158-8115a0f0-85cc-11e8-9e7d-c9db847ecfa0.png)

http://cocoshki.pl
![opera zdjecie_2018-07-12_121014_cocoshki pl](https://user-images.githubusercontent.com/36385327/42627193-956e444e-85cc-11e8-8e2a-d4daaddf3210.png)

http://bascat.pl
![opera zdjecie_2018-07-12_121100_bascat pl](https://user-images.githubusercontent.com/36385327/42627229-ae9abab0-85cc-11e8-89fa-0c0e1099073e.png)

https://www.tinystar.pl
![opera zdjecie_2018-07-12_121129_www tinystar pl](https://user-images.githubusercontent.com/36385327/42627244-bdc0487a-85cc-11e8-93c2-f18577fef2f6.png)

http://www.helloforma.com
![opera zdjecie_2018-07-12_121156_www helloforma com](https://user-images.githubusercontent.com/36385327/42627261-cccd3850-85cc-11e8-9754-e659632f7b14.png)

https://www.spodiglyinitki.pl
![opera zdjecie_2018-07-12_121241_www spodiglyinitki pl](https://user-images.githubusercontent.com/36385327/42627311-eb82811a-85cc-11e8-809a-ecff4c5a5d76.png)

**Comment by krystian3w** [comment]
`#footgroup6 > ul > li:nth-of-type(5)` - "`opineo.pl`" na social?
