### ISSUE TITLE
zepsute.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8355]
![opera zdjecie_2018-07-12_172155_zepsute pl](https://user-images.githubusercontent.com/36385327/42642921-30014ddc-85f8-11e8-926f-cfd2f4726d8c.png)

**Comment by xMaap** [comment]
Jeszcze tutaj reklama i social
https://zepsute.pl/broken_thing,pendrive_sandisk,19
![opera zdjecie_2018-07-12_172350_zepsute pl](https://user-images.githubusercontent.com/36385327/42643005-659a4a16-85f8-11e8-80bb-4e2bf610b794.png)

**Comment by gzenio22** [comment]
glowna

wyciemnienie : zepsute.pl###overlay_uv
Rodo: zepsute.pl###uv_box_data
Socjal: zepsute.pl###fb_share
Reklama: zepsute.pl###adv_main
