### ISSUE TITLE
m.auto-swiat.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8359]
http://m.auto-swiat.pl/wiadomosci,2vfjd1?utm_source
![opera zdjecie_2018-07-13_071233_m auto-swiat pl](https://user-images.githubusercontent.com/36385327/42673552-54ee25ec-866c-11e8-812e-9724191b3af0.png)
![opera zdjecie_2018-07-13_071250_m auto-swiat pl](https://user-images.githubusercontent.com/36385327/42673553-55111cd2-866c-11e8-948a-9f63d4e71ff4.png)

**Comment by krystian3w** [comment]
`m.auto-swiat.pl##.fb_share`
