### ISSUE TITLE
przegladpolityczny.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8363]
![opera zdjecie_2018-07-13_130805_przegladpolityczny pl](https://user-images.githubusercontent.com/36385327/42688813-1d0ff86c-869e-11e8-9f5f-01099bfeaa16.png)

**Comment by xMaap** [comment]
Jeszcze tutaj
https://www.copernicusfestival.com
https://www.naukaireligia.pl
https://www.filozofiawnauce.pl
https://www.copernicuscenter.edu.pl

**Comment by krystian3w** [comment]
```
serialowa.pl,przegladpolityczny.pl##.popmake-overlay
copernicusfestival.com,naukaireligia.pl,filozofiawnauce.pl,copernicuscenter.edu.pl###block-block-31
```
