### ISSUE TITLE
pcworld.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8381]
![opera zdjecie_2018-07-14_125213_www pcworld pl](https://user-images.githubusercontent.com/36385327/42723766-ddbb3fa6-8764-11e8-9ef5-0c4550387e5c.png)

**Comment by krystian3w** [comment]
`||vendorlist.consensu.org/vendorlist.json$xmlhttprequest,domain=www.pcworld.pl`

Albo `##div > div > div > div` by jakoś to chwycić, bo dziwne klasy.
