### ISSUE TITLE
msn.com/pl-pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8394]
### Link bezpośredni
https://www.msn.com/pl-pl/sport/mistrzostwa-swiata/mundial-co-robi%C5%82-30-lat-temu-gwiazdor-chorwacji-nagranie-podbija-internet/ar-AAA5f9d

menu lata all over the place

![capture](https://user-images.githubusercontent.com/15007183/42733266-716c02ca-87fc-11e8-8126-9d6ef6fb7cf9.PNG)

**Comment by hawkeye116477** [comment]
Z tym lataniem to raczej bym powiedział, że to nie błąd, a normalka, tak zrobili tą stronę, np. popatrz na satkurier albo dobreprogramy.
Jedyne co można byłoby poprawić, to przesunąć menu bardziej na górę, bo po komunikacie dot. ciastek zrobiła się dziura.
```
msn.com##.head:style(margin-top: 0 !important;)
msn.com###precontent:style(margin-top: 8rem !important;)
```

**Comment by xxcriticxx** [comment]
@hawkeye116477 tak dokladni tak wyglonda en ver

![image](https://user-images.githubusercontent.com/15007183/42733704-4356df9c-8804-11e8-963f-9e96e4b5cb06.png)

**Comment by hawkeye116477** [comment]
A jeżeli chcesz, by menu nie latało, tylko siedziało na miejscu, to to jest zadanie dla @KonoromiHimaries, on się zajmuje usadzaniem :smile:

**Comment by krystian3w** [comment]
```
www.msn.com##.head:style(margin-top: 0 !important; positon: static !important;)
www.msn.com###precontent:style(margin-top: 8rem !important;)
www.msn.com##.scrolled.head:style(position: static !important)
```

wątpię, że lepiej to jakoś robi Mati.
