### ISSUE TITLE
darmowa-bramkasms.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#840]
nie mysle ze to legalna strona ale ma cookies i adblock

Darmowa bramka sms - prosta, lekka i skuteczna   - Jeśli widzisz ten komunikat, a nie ma bramki sms, wyłącz program blokujący reklamy i odśwież stronę. Wszystko zacznie działać :)

Uwaga! Nasza strona stosuje pliki cookies w celu zapewnienia poprawnego funkcjonowania serwisu i korzystania z naszych usług. Korzystając ze strony wyrażasz zgodę na ich używanie, zgodnie z aktualnymi ustawieniami przeglądarki. W każdej chwili możesz te ustawienia zmienić wykorzystyjąc odpowiednie funkcje przeglądarki. Zamknij

**Comment by MajkiIT** [comment]
https://github.com/reek/anti-adblock-killer/issues/1429
