### ISSUE TITLE
internetstandard.pl + computerworld.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8406]
![opera zdjecie_2018-07-17_011035_www internetstandard pl](https://user-images.githubusercontent.com/36385327/42788179-3e50408c-895e-11e8-92c5-c467d83432c7.png)

**Comment by hawkeye116477** [comment]
||vendorlist.consensu.org/vendorlist.json$xmlhttprequest,domain=internetstandard.pl|computerworld.pl
