### ISSUE TITLE
ipon.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#8408]
https://www.ipon.pl
![20180717-001-screenshot](https://user-images.githubusercontent.com/9846948/42795197-436a3fd0-8983-11e8-8f31-94e0f03aa95c.png)

**Comment by MajkiIT** [comment]
Ja tego nie widzę.

**Comment by hawkeye116477** [comment]
Też tego nie mam, jedynie widzę strzałkę do dodania do EI :smile:

**Comment by FadeMind** [comment]
@F4z 
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 1803 x64
Browser:                            | Chrome Stable x64
AdGuard version:                    | **6.3.1374.4023** RC
Stealth mode: 						| enabled

| Filters enabled |
|-----------------|
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| Coin Blocker List
| EasyList Polish 
| Fanboy's Annoyances
| Fanboy's Enhanced Tracking List
| Fanboy's Social Blocking List
| I don't care about cookies
| KAD - fraud/scam 
| Malware Domains List
| NoCoin Filter List 
| Peter Lowe's list 
| Polish Annoyances
| Polish Main
| Polish Social
| Spam404

**Comment by F4z** [comment]
To chyba kwestia tego w jaki sposób (nie)ukrywane są elementy kiedy jest `style="display: block !important;"`, w przypadku uBO to jest ukryte, ale z tego co widzę Adblock Plus też tego nie ukrywa.

Jeśli chodzi o AdGuarda, to te reguły powinny działać:
`ipon.pl#$#.appAdvContainer { height: 1px!important; }`
`ipon.pl#$#.app_adv_baner { height: 1px!important; }`

**Comment by FadeMind** [comment]
@F4z dziękuję. Reguły dla Adguard działają poprawnie.

**Comment by MajkiIT** [comment]
@F4z wrzucić do filtrów do ADG ?
