### ISSUE TITLE
alltube.pl | alltube.tv

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#8412]
||7vxlfstt.top$script,domain=alltube.pl

**Comment by xxcriticxx** [comment]
Klikając przycisk Przejdź zostaniesz przekierowany do zewnętrznej strony, gdzie znajduje się materiał wideo. Nie mamy wpływu jak działa i co wyświetla zewnętrzny serwis. Mogą pojawić się nieprzyzwoite lub denerwujące reklamy. Zalecamy korzystanie z markowego antywirusa i wtyczek blokujących niechciane treści. Więcej informacji dostępnych w dziale Pomoc.
