### ISSUE TITLE
homebook.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8415]
Niemożna się ani zalogować ani zarejestrować.

**Comment by krystian3w** [comment]
jak na dimondi.pl:


> Filtr statyczny `homebook.pl##.popup-overlay` znajdujący się w:
> 
>     Polskie Filtry Elementów Irytujących


A i widzę, że też wytnie ci przycisk logowania przez FB (bug fanboya):

```
www.homebook.pl#@#.fa-facebook
www.homebook.pl#@#.btn--facebook
```

**Comment by hawkeye116477** [comment]
```
homebook.pl#@#.popup-overlay
homebook.pl##.popup-overlay:has(.popup-content--newsletter)
```

**Comment by krystian3w** [comment]
Aż wyprzedziłem system powiadomień.
