### ISSUE TITLE
ustawlige.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8425]
![opera zdjecie_2018-07-18_173846_ustawlige com](https://user-images.githubusercontent.com/36385327/42892240-a5c7914e-8ab1-11e8-9de5-26e065443d8e.png)
![opera zdjecie_2018-07-18_174335_ustawlige com](https://user-images.githubusercontent.com/36385327/42892457-2e87f596-8ab2-11e8-808d-e39648fb2020.png)

**Comment by hawkeye116477** [comment]
@MajkiIT Do zamknięcia
