### ISSUE TITLE
ipla.tv

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#8428]
https://www.ipla.tv/start filtry mam (Polskie Filtry RODO-Ciasteczkowe​​) w Firefox ok w Chrome komunikat Rodo, proszę o usunięcie.

**Comment by hawkeye116477** [comment]
@MajkiIT Rozumiem, że taki mail przyszedł. A jakiego adblockera ma ta osoba? Bo jeżeli ABP, AdBlocka, to przekichane, bo oni blokują scrolla, a tego nie odblokujemy w tych adblockerach :smile:.
