### ISSUE TITLE
miasto-gazeta.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8434]
cookies

Obowiązek informacyjny.Pamietaj, że poprzez korzystanie z miasto-gazeta.pl bez zmiany ustawień Twojej przeglądarki, wyrażasz zgodę na zapisywanie plików cookies i skryptów w Twoim urządzeniu końcowym oraz na korzystanie z informacji w nich zapisanych. Ustawienia w zakresie cookie możesz zawsze zmienić.

**Comment by hawkeye116477** [comment]
`miasto-gazeta.pl##.wpgdprc`
