### ISSUE TITLE
ztm.kielce.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8442]
![opera zdjecie_2018-07-20_060209_ztm kielce pl](https://user-images.githubusercontent.com/36385327/42982636-7b8e58fe-8be2-11e8-8c5d-59d8aa2866dd.png)

**Comment by hawkeye116477** [comment]
`||ztm.kielce.pl/modules/mod_rppopup/js/jquery.gafancybox.min.js`
