### ISSUE TITLE
skm.pkp.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8444]
![opera zdjecie_2018-07-20_060311_www skm pkp pl](https://user-images.githubusercontent.com/36385327/42982679-b2b683d8-8be2-11e8-83ef-fce590234e9c.png)

**Comment by hawkeye116477** [comment]
```
skm.pkp.pl#?#.ui-dialog:-abp-has(#dialog-message-rodo)
skm.pkp.pl##.ui-widget-overlay
```
