### ISSUE TITLE
zdmikp.bydgoszcz.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8445]
![opera zdjecie_2018-07-20_060438_www zdmikp bydgoszcz pl](https://user-images.githubusercontent.com/36385327/42982715-e9b9d362-8be2-11e8-995e-462d20c9d00b.png)

**Comment by hawkeye116477** [comment]
```
zdmikp.bydgoszcz.pl###customModal, .modal-backdrop
zdmikp.bydgoszcz.pl##.modal-open:style(overflow: auto !important;)
```
