### ISSUE TITLE
Do skasowania.

### ISSUE THREAD

**Issue by adreporter** [MajkiIT/polish-ads-filter#846]
Nie wiem czemu ale w menu uBlocka miałem odznaczone wasze filtry. Przepraszam za spam.

**Comment by xxcriticxx** [comment]
ftadbjgq.wp.pl blokuje regex wp.pl 

masz akualne filtry? podaj jakies zdjecia tych reklam

**Comment by adreporter** [comment]
Tak, mam aktualne filtry.
Dzisiaj te reklamy pochodzą z innego adresu
http://s32.postimg.org/68g4mr7b9/Przechwytywanie.png (adres tej reklamy to http://iwtjxgfu.wp.pl/Uk0vY2xpY2tfbHguYWRzL1NhbW9zaWEucGwvaW5kZXguaHRtbC9MMjEvMTA5MDI1MjMyMS94MDMvT2FzRGVmYXVsdC85ODk1Ml8yMjI3MzBfdGNoaWJvX3Jvc19fc2Nyb2xsLzIxODkyMjY3MTI3NTY3MTI3NjY3MTI3NzY3MzMxMDY3MzMxOTY3MzMyMTY3MzMyNTY3MzMyNjY3MzMyNzY3MzMyODY3MzMyOTY3NDg1NTY3NDg1ODY3NDg2MDY3NDg2MTY3NDg2MjY3NDg2MzY3NDg2NDY3NTA4ODY3NTA5Mi5odG1sLzU3NTU3MDZiNzY0NjYzN2E3NDQ0NmI0MTQyNzc1NDQ3P3NlZ249MiZzdmxlPTAuNjcwMCZzcHJlPTAmUFZJRCZwYz1odHRwJTNBJTJGJTJGd3d3LnNhbW9zaWEucGwlMkYmUFdBX2FkYmQ9MSZfUk1fUkVESVJfPWh0dHA6Ly9jbGlja3NlcnZlLmRhcnRzZWFyY2gubmV0L2xpbmsvY2xpY2s/bGlkPTQzNzAwMDA5NjczNzk4MDA4JmRzX3Nfa3dnaWQ9NTg3MDAwMDEwNDc2ODI5OTMmZHNfdXJsX3Y9MiZkc19kZXN0X3VybD1odHRwOi8vd3d3LnRjaGliby5wbC9kemllY2llY2EtbW9kYS1sZXRuaWEtdWJyYW5pYS1uYS1wbGF6ZS10NDAwMDY2OTM1Lmh0bWw/d2JkYz1DdnhZNGY0YVZKJnV0bV9tZWRpdW09ZGlzcGxheV9lYyZ1dG1fc291cmNlPXdwJnV0bV9jYW1wYWlnbj0yMDE2a3cxOSN2bXA9cG9ydGFsZQ== )
http://s32.postimg.org/5c42k4a85/Przechwytywanie2.png (adres tej reklamy to http://iwtjxgfu.wp.pl/Uk0vY2xpY2tfbHguYWRzL1NhbW9zaWEucGwvaW5kZXguaHRtbC9MMjEvMTY0NjQ2ODk3My94MzQvT2FzRGVmYXVsdC85ODE5MV8yMjA5NjBfYXBsaWthY2phTzJfbWl4Ml8wMS8yMjA5NjBfOTcweDMwMDY2OTY4NjY2OTY4ODY2OTcyOS5odG1sLzU3NTU3MDZiNzY0NjYzN2E3NDQ0NmI0MTQyNzc1NDQ3P1BWSUQmcGM9aHR0cCUzQSUyRiUyRnd3dy5zYW1vc2lhLnBsJTJGJlBXQV9hZGJkPTEmX1JNX1JFRElSXz1odHRwOi8vbzIucGwvYXJ0eWt1bC9iYWR6LXctc2VyY3UtaW50ZXJuZXR1LTU5ODI4MTI5OTc0ODEwODlh )
http://s32.postimg.org/ove69yw91/Przechwytywanie3.png (adres tej reklamy to http://iwtjxgfu.wp.pl/Uk0vY2xpY2tfbHguYWRzL1NhbW9zaWEucGwvaW5kZXguaHRtbC9MMjEvNTgxOTU4MDIyL3gzNy9PYXNEZWZhdWx0Lzk5MDgzXzIyMzAxMF9LRkNfV09fbXNreV8wMS8yMjMwMTAxNjc1NDc3Njc1NDc4Njc1NDc5Lmh0bWwvNTc1NTcwNmI3NjQ2NjM3YTc0NDQ2YjQxNDI3NzU0NDc/UFZJRCZwYz1odHRwJTNBJTJGJTJGd3d3LnNhbW9zaWEucGwlMkYmUFdBX2FkYmQ9MSZfUk1fUkVESVJfPWh0dHBzOi8vd3AuaGl0LmdlbWl1cy5wbC9sc2hpdHJlZGlyL2lkPUFmVkZ6U3JRV2NGb1BvMW1YRzJHQk1SN25LUVdzd3l4TThIY2ZiMVhCQkgudTcvZmFzdGlkPW5xeGtzY2Fsb3phZm1ja2V2b2hwdWZub2lpbGUvc3RwYXJhbT1vamRwbnRnc211L3VybD1odHRwczovL3d3dy5rZmNkb3N0YXdhLnBsP3V0bV9zb3VyY2U9V1BfUGVyZm9ybWFuY2VfR3JhbmRlciZ1dG1fbWVkaXVtPSZ1dG1fY29udGVudD1NaXgmdXRtX2NhbXBhaWduPUtGQ19XZWJvcmRlcl9JVl9W )

**Comment by MajkiIT** [comment]
używasz adblocka czy ublocka?

**Comment by xxcriticxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/15007183/15221414/5382fdc0-1839-11e6-8278-59d116269e4f.PNG)

**Comment by adreporter** [comment]
Używam ublocka

**Comment by xxcriticxx** [comment]
zobacz moje zdjecie ublock zablokowal 16 zeczy i zadnych reklam nie widac 

pokaz foto u ciebie ublock jest wlonczony?

**Comment by xxcriticxx** [comment]
@adreporter jaki byl powod?

na dole masz opcje Close issue

**Comment by adreporter** [comment]
@xxcriticxx Powód to prawdopodobnie przywrócenie ustawień domyślnych uBlocka.

**Comment by xxcriticxx** [comment]
teraz wszystko jusz dziala?

dzieki za wizite mam nadzieje ze nas znowu odwiedzisz?

**Comment by adreporter** [comment]
Tak, wszystko działa. Tak wrócę, jak znajdę jakąś polską stronę z reklamami.

**Comment by xxcriticxx** [comment]
good luck c ya
