### ISSUE TITLE
wysokienapiecie.pl

### ISSUE THREAD

**Issue by wrednamalpa** [MajkiIT/polish-ads-filter#8466]
### Zrzut ekranu
![image](https://user-images.githubusercontent.com/41550681/43048944-263beee2-8df0-11e8-9f38-f6ae40750b7c.png)

A jak się kliknie

![image](https://user-images.githubusercontent.com/41550681/43048932-0bc406ee-8df0-11e8-8bc1-b1d412dcd856.png)

### Link bezpośredni
https://wysokienapiecie.pl/10175-rzad-doplaci-po-25-tys-zl-aut-elektrycznych/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Nic, po prostu się pojawia

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome 67, OS X
**Rozszerzenia i skrypty:**
uOrigin, Ghostery

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for uBlock

**Comment by hawkeye116477** [comment]
@wrednamalpa To już jest w Polskich Filtrach Elementów Irytujących i module **Powiadomienia Web Push**. Także zasubskrybuj Filtry EI albo tylko ten jeden moduł => `https://polishannoyancefilters.netlify.com/modules`
