### ISSUE TITLE
pl.wikia.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8474]
![opera zdjecie_2018-07-24_220701_pl wikia com](https://user-images.githubusercontent.com/36385327/43163293-05a00bba-8f8e-11e8-8b8a-cac04e8f530c.png)

W sumie to proponuje zablokować dla całego wikia.com, bo gzie indziej też będzie się pojawiać np. tutaj http://pl.assassinscreed.wikia.com/wiki/Strona_główna

**Comment by wmyrda** [comment]
Wystarczy poniższy czy trzeba uciekać się do bardziej specyficznych dla adblocka rozwiazań?
wikia.com##body > div:nth-child(23)

Przy okazji. Takie coś nic by nie zepsuło?
||fandom.wikia.com/wp-content/themes/jspm_packages/npm/@wikia/tracking

**Comment by krystian3w** [comment]
Jak kiedyś sprawdzałem to prostymi regułami kosmetycznymi odpada - nie ma przewijania.

A co do blokowania sieciowego to tylko namierzyłem skrypt ale było tam wiele kodu do analizy, przed testami ile padło.

**Comment by hawkeye116477** [comment]
```
wikia.com##div[data-tracking-opt-in-overlay]
wikia.com##html:style(overflow: auto !important;)
```
