### ISSUE TITLE
patrz.pl + pinotv.pl + playa.pl + moblo.pl + jpg.pl + slajdzik.pl + rusz.pl + osobie.pl 

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8476]
![opera zdjecie_2018-07-25_105818_patrz pl](https://user-images.githubusercontent.com/36385327/43190626-cc1bdf4c-8ff9-11e8-9c48-a5066d480306.png)

**Comment by xMaap** [comment]
Jeszcze 
http://rusz.pl/pytanie,2107,ile-wynosilo-pierwsze-ograniczenie-predkosci.html
![opera zdjecie_2018-07-25_110634_rusz pl](https://user-images.githubusercontent.com/36385327/43191123-d072eda0-8ffa-11e8-9fa7-0f87da23258e.png)

http://pinotv.pl/kanal/pinotv
![opera zdjecie_2018-07-25_110704_pinotv pl](https://user-images.githubusercontent.com/36385327/43191159-e4a2b5a8-8ffa-11e8-93b4-476f88523665.png)

**Comment by xMaap** [comment]
I jeszcze tutaj

http://www.prv.pl/ranking/
Włączona
![opera zdjecie_2018-07-25_111807_www prv pl](https://user-images.githubusercontent.com/36385327/43191937-8737bde4-8ffc-11e8-98b9-b9b09a52b555.png)
Wyłączona
![opera zdjecie_2018-07-25_111835_www prv pl](https://user-images.githubusercontent.com/36385327/43191949-8ee3cd8a-8ffc-11e8-99fd-7e19984019b0.png)

http://www.prv.pl/kreator,edycja,62417#kreator
Włączona
![opera zdjecie_2018-07-25_111941_www prv pl](https://user-images.githubusercontent.com/36385327/43191978-a4b773e6-8ffc-11e8-869f-836bc9f8b2b6.png)
Wyłączona
![opera zdjecie_2018-07-25_112000_www prv pl](https://user-images.githubusercontent.com/36385327/43192001-b301a322-8ffc-11e8-814e-e3e35165bd86.png)

Wszyskie strony na *prv.pl *.opx.pl *.htw.pl *.wex.pl *.keep.pl *.pev.pl
http://justynakania.prv.pl
http://fotogotowanie.opx.pl
http://smog.htw.pl
http://kamix.wex.pl
http://aviuss-portfolio.keep.pl
http://portrety.pev.pl
![opera zdjecie_2018-07-25_112026_justynakania prv pl](https://user-images.githubusercontent.com/36385327/43192170-22f4efd6-8ffd-11e8-9930-5f189dce6802.png)

**Comment by krystian3w** [comment]
`www.prv.pl#@##container` - chyba do wywalenia - odblokowuje treść na http://www.prv.pl/ranking/

**Comment by krystian3w** [comment]
> Wszyskie strony na *prv.pl *.opx.pl *.htw.pl *.wex.pl *.keep.pl *.pev.pl

rozumiem, że masz dezaktywowany `Peter Lowe’s Ad and tracking server list` (za dużo ci psuł)?

`||ad.prv.pl/rodo.js` - pożyczone od nich blokują wszystkie pliki z subdomeny `ad`.

**Comment by xMaap** [comment]
@krystian3w Hmm mam włączony i nigdy go nie wyłączałem 
![opera zdjecie_2018-07-25_155923_gabbbocakeomblphkmmnoamkioajlkfo](https://user-images.githubusercontent.com/36385327/43205509-cd734d9c-9023-11e8-917d-2b15a11bb8f8.png)

**Comment by krystian3w** [comment]
OK.

```
||ad.prv.pl/rodo.js - pożyczone od nich blokują wszystkie pliki z subdomeny ad.
||openid.pino.pl/app/static/global/rodo.js
patrz.pl##.rodoaccept
```

Zobacz ile rodo zniknie.

**Comment by xMaap** [comment]
Mi zablokowało wszędzie informacje o RODO oprócz http://playa.pl
