### ISSUE TITLE
kb.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#8485]
`https://kb.pl/porady/przewiercony-przewod-elektryczny-w-scianie-jak-go-naprawic/`
Jeden z ważniejszych raportów na Discordzie, jest tego jeszcze więcej jak widzę, od paru miesięcy nierozwiązane sprawy. Więc jeżeli @MajkiIT będzie miał czas, to dobrze byłoby jakby zerknął na kanał `#reklamowe` :smile:.
Antyadblock => `@@||kb.pl/static/front2.0/js/ads.js`

**Comment by MajkiIT** [comment]
Ok, zerknę. Dziękuję za przypomnienie
