### ISSUE TITLE
esanok.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8486]
https://esanok.pl
Social, napisy REKLAMA, ukrywa treść
![opera zdjecie_2018-07-26_162616_esanok pl](https://user-images.githubusercontent.com/36385327/43268351-b0b097e6-90f0-11e8-8d3d-9a771ff841ea.png)

https://esanok.pl/2018/gmina-sanok-dofinansowanie-do-wymiany-kotlow-grzewczych-00e2mp.html
Luka po reklamie 
![opera zdjecie_2018-07-26_162659_esanok pl](https://user-images.githubusercontent.com/36385327/43268370-c15e1d20-90f0-11e8-9e54-633efb990171.png)

**Comment by hawkeye116477** [comment]
Dziura po reklamie => `esanok.pl##.socialGallery > div:nth-of-type(1)`
