### ISSUE TITLE
cdp.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8487]
https://cdp.pl
![opera zdjecie_2018-07-26_180415_cdp pl](https://user-images.githubusercontent.com/36385327/43274048-55093002-90fe-11e8-8cae-3d80d61c0b63.png)

https://cdp.pl/filmy.html
![opera zdjecie_2018-07-26_180436_cdp pl](https://user-images.githubusercontent.com/36385327/43274063-600584c4-90fe-11e8-86d1-1089783ab8a6.png)

https://cdp.pl/the-crew-2-pud-pc.html
![opera zdjecie_2018-07-26_180449_cdp pl](https://user-images.githubusercontent.com/36385327/43274088-716307e6-90fe-11e8-9d6d-a88be0e87714.png)
![opera zdjecie_2018-07-26_180459_cdp pl](https://user-images.githubusercontent.com/36385327/43274089-71840bee-90fe-11e8-82d4-f03100c0ff68.png)

**Comment by hawkeye116477** [comment]
U mnie jest ok, po prostu trzeba trochę zaczekać aż strona się do końca załaduje.

**Comment by xMaap** [comment]
@hawkeye116477 no właśnie u mnie niby się strona załadowała i nic. Jak wyłączę Nano Adblocker to się wszystko wczytuje.
![opera zdjecie_2018-07-26_192533_cdp pl](https://user-images.githubusercontent.com/36385327/43277876-b1c210c4-9109-11e8-988c-ec1c803553d5.png)

**Comment by hawkeye116477** [comment]
No to pewnie ja nie mam tej listy, która akurat powoduje ten problem. U mnie ta strona wraz z wszystkimi elementami się wczytuje, ale ta strona wolno działa, jakby ktoś tam koparkę dołożył :smiley:

**Comment by krystian3w** [comment]
Pewnie fanoboye wykrywają wyimaginowane EI.

**Comment by krystian3w** [comment]
No i mam - cookies wycinają sieciowo za mocno, coś jak kiedyś z Interią.

`@@||cdp.pl/*/js/*cookies.js,/*$script`

**Comment by hawkeye116477** [comment]
@krystian3w Kto wycina, kim są ci oni?

**Comment by krystian3w** [comment]
Fanboy Cookiemonster / Fanboy Annoyance.

Ja używam pierwszego a @xMaap nijak się nie da przekonać do porzucenia Fanboy Annoyance.

**Comment by xMaap** [comment]
@krystian3w bo jestem upartym osłem

Może być?
![opera zdjecie_2018-07-27_150610_gabbbocakeomblphkmmnoamkioajlkfo](https://user-images.githubusercontent.com/36385327/43322411-a8e2171a-91ae-11e8-98e3-fda066d2a80d.png)
