### ISSUE TITLE
noizz.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#8493]
`https://noizz.pl/fashion/przeglad-sneakersow-na-grubej-podeszwie/kpnbhct`
Nie widać butów.
`@@||widgets.moneteasy.pl^$script,domain=pulsembed.eu`

**Comment by krystian3w** [comment]
to jeszcze te prawe dziury może:

`noizz.pl##[class^="right"][class$="-floating-container"]`
