### ISSUE TITLE
player.polskieradio.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8499]
laduje sie wam ta strona?

https://player.polskieradio.pl/-17

**Comment by krystian3w** [comment]
Nie leci, nie na moją głowę. Odblokowałem jedynie na 15 sekund reklamę skrzyżowania (Carrefour) a tam promocja na pomidory i jak się urwała transmisja, jak z 5 razy polokowało adocean / gemiusa ...
