### ISSUE TITLE
homebrewing.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8502]
![opera zdjecie_2018-07-27_233112_www homebrewing pl](https://user-images.githubusercontent.com/36385327/43347362-40e0dbe6-91f5-11e8-8645-8b0e9e4f21b3.png)

**Comment by xxcriticxx** [comment]
`homebrewing.pl##.rodo-popupbox`

**Comment by krystian3w** [comment]
`###fb_ikona`
`###fb`
