### ISSUE TITLE
piotripawel.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8503]
http://www.piotripawel.pl/promocje.html
![opera zdjecie_2018-07-27_233243_www piotripawel pl](https://user-images.githubusercontent.com/36385327/43347406-63da5ea6-91f5-11e8-806e-acfd658831a7.png)

**Comment by krystian3w** [comment]
U mnie nie ma...

**Comment by krystian3w** [comment]
godzina | -- | filter | -- | element | witryna
-- | -- | -- | -- | -- | --
18:52:37 |   | `##img[alt="facebook"]` |   | dom | `http://www.piotripawel.pl/`
18:52:37 |   | `##.social-media-footer` |   | dom | `http://www.piotripawel.pl/`
18:52:37 |   | `##.social-absolute-home` |   | dom | `http://www.piotripawel.pl/`
18:52:37 |   | `##.newsletter-box` |   | dom | `http://www.piotripawel.pl/`
18:52:37 |   | `##.fa-youtube` |   | dom | http://www.piotripawel.pl/`
18:52:37 |   | `##.fa-twitter.fa` |   | dom | `http://www.piotripawel.pl/`
18:52:37 |   | `##.fa-instagram` |   | dom | `http://www.piotripawel.pl/`
18:52:37 |   | `##.fa-facebook` |   | dom | `http://www.piotripawel.pl/`
18:52:37 |   | `##.btn-youtube` |   | dom | `http://www.piotripawel.pl/`
18:52:37 |   | `##.btn-twitter` |   | dom | `http://www.piotripawel.pl/`
18:52:37 |   | `##.btn-social` |   | dom | `http://www.piotripawel.pl/`
18:52:37 |   | `##.btn-instagram` |   | dom | `http://www.piotripawel.pl/`
18:52:37 |   | `##.btn-facebook` |   | dom | `http://www.piotripawel.pl/`
