### ISSUE TITLE
vimeo.com + soundcloud.com + spotify.com + dailymotion.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8506]
https://vimeo.com
![opera zdjecie_2018-07-28_181430_vimeo com](https://user-images.githubusercontent.com/36385327/43358440-1745e3f6-9292-11e8-8ec7-83407e3bf62d.png)

https://soundcloud.com
![opera zdjecie_2018-07-28_181442_soundcloud com](https://user-images.githubusercontent.com/36385327/43358444-324390d6-9292-11e8-98a3-98e600b42313.png)

https://www.spotify.com/pl/
![opera zdjecie_2018-07-28_181540_www spotify com](https://user-images.githubusercontent.com/36385327/43358448-410b000e-9292-11e8-97ff-84394754117b.png)

https://www.dailymotion.com
![opera zdjecie_2018-07-28_181600_www dailymotion com](https://user-images.githubusercontent.com/36385327/43358450-55c209d4-9292-11e8-8ceb-c07e8d49341c.png)

**Comment by krystian3w** [comment]
```
dailymotion.com#div[class^="CookieGdpr"]
vimeo.com##.gdpr_banner
soundcloud.com##.announcements
spotify.com###js-message-bar-cookie-notice
```

**Comment by hawkeye116477** [comment]
Soundcloud i spotify są po polsku, więc do nas, ale reszta to do Fanboya.

**Comment by krystian3w** [comment]
Ukrywa, jak chcesz to potem wycofasz.
