### ISSUE TITLE
amazon.de + amazon.com + amazon.co.uk

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8509]
W sumie to nie wiem czy nadaje się to do ukrycia
![zrzut ekranu z 2018-07-28 18-27-22](https://user-images.githubusercontent.com/36385327/43358532-e72e1902-9293-11e8-8ba9-a089d3713ceb.png)

**Comment by krystian3w** [comment]
Jak już ukryliśmy na mało popularnym vimeo i dailymotion to tu możemy...

**Comment by krystian3w** [comment]
`amazon.de,amazon.co.uk,amazon.com###desktop-cookie-disclosure`

**Comment by hawkeye116477** [comment]
Niemiecki dodajemy, bo mają też polską wersję, ale reszta idzie do Fanboya albo I don't care :smile:.
