### ISSUE TITLE
a-o.ninja

### ISSUE THREAD

**Issue by OtakuPL** [MajkiIT/polish-ads-filter#8512]
### Zrzut ekranu

Błąd 1 psuje css slidera z ostatnimi dodanymi na całej głównej stronie. : http://scr.hu/2ci4/ggxp9
Błąd 2 nie odtwarza się dosłownie żaden z playerów z włączonymi filtrami anty miner. (strona od 2 miesięcy nie używa minera), playery też.
### Link bezpośredni

Wstaw tutaj link bezpośredni do strony, na której występuje element, reklama albo błąd.

**https://a-o.ninja/**

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Nie wiem, nie znam się na tym, niech działa normalnie slider na głównej i playery.
2. Innych zastrzeżeń nie mam. 

### Moja konfiguracja
chrome wersja 68.0.3440.75 (Oficjalna wersja) (64-bitowa)

**Rozszerzenia i skrypty:**

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. Standard http://scr.hu/2ci4/qoerr

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Nie chodzi o reklamy a o naprawienie bugów.
Pozdrawiam serdecznie.

**Comment by OtakuPL** [comment]
Chyba na waszej :/

**Comment by krystian3w** [comment]
No to tak:

slider CSS/JS psuje proste blokowanie komunikatu o adblocku:

```
@@||a-o.ninja/wp-content/plugins/jgc-adblocker-detector/js/jgcabd-detect-adblock.js

a-o.ninja#@#.text_ad
a-o.ninja#@#.textAd
a-o.ninja#@#.text-ads
a-o.ninja#@#.text-ad-links
a-o.ninja#@#.text-ad
a-o.ninja#@#.pub_728x90
a-o.ninja#@#.pub_300x250m
a-o.ninja#@#.pub_300x250
a-o.ninja#@#.text_ads
```

Odblokowanie skryptu i wyłączenie blokowania kilku elementów - jak są gdzieś przez to reklamy to dla uBO / Adguard trzeba je zamaskować zmniejszając wymiar pustych elementów do 1-5 px lub je przesunąć poza ekran.

Nie mam pomysłu na skuteczne negowanie filtru na koparki:

`@@||a-o.ninja^$csp,first-party` - może być niewystarczający
`@@||a-o.ninja^$csp` - uBO nie pozwala dodać

`@@*$csp=worker-src 'none',domain=a-o.ninja|alltube.tv|biter.tv|byter.tv|centrum-dramy.pl|hentai-online.pl|lewd.ninja|love-drama.pl|milujivareni.cz|tokyodrift.ga|vidfile.net|ya3ale.com` - może za dużo odblokować
`@@*$csp=worker-src 'none',domain=a-o.ninja` - może być olewany

Co do listy hoshsadiq, to jakby już nie blokowała tam koparek - przypadek?

**Comment by krystian3w** [comment]
No to tak:

slider CSS/JS psuje proste blokowanie komunikatu o adblocku:

```js
baitClass: 'pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links',
baitStyle: 'width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -1000px !important;'
```

odblokowanie skryptu i wyłączenie blokowania kilku elementów:

```
@@||a-o.ninja/wp-content/plugins/jgc-adblocker-detector/js/jgcabd-detect-adblock.js

a-o.ninja#@#.text_ad
a-o.ninja#@#.textAd
a-o.ninja#@#.text-ad

a-o.ninja#@#.text-ads
a-o.ninja#@#.text_ads

a-o.ninja#@#.text-ad-links

a-o.ninja#@#.pub_728x90
a-o.ninja#@#.pub_300x250m
a-o.ninja#@#.pub_300x250

```

`generichide` może za dużo zrobić luk - ale nie sprawdzałem, można zobaczyć zawsze mniej reguł jakby nie było potrzebne kolejne kilka do nieinwazyjnego wycięcia reklamy.

... jak są gdzieś przez to reklamy/puste elementy:

<ul>
to dla uBO / Adguard trzeba je zamaskować zmniejszając wymiar pustych elementów do 2-5 px lub je przesunąć poza ekran (chociaż niby skrypt to wykryje).

Opcjonalnie jakaś reguła `script:inject()` / `+js()`.
</ul>

----

Nie mam pomysłu na skuteczne negowanie filtru na koparki:


`@@||a-o.ninja^$csp,first-party` - może być niewystarczający,
`@@||a-o.ninja^$csp` - uBO nie pozwala dodać (coś mu się nie podoba).

`@@*$csp=worker-src 'none',domain=a-o.ninja|alltube.tv|biter.tv|byter.tv|centrum-dramy.pl|hentai-online.pl|lewd.ninja|love-drama.pl|milujivareni.cz|tokyodrift.ga|vidfile.net|ya3ale.com` - może za dużo odblokować,
`@@*$csp=worker-src 'none',domain=a-o.ninja` - może być olewany.

Co do listy hoshsadiq, to jakby już nie blokowała tam koparek - przypadek?

**Comment by MajkiIT** [comment]
@OtakuPL u mnie na FF jest OK . Co do filtrów Anty Coin to poprawiają jak zgłosisz https://github.com/hoshsadiq/adblock-nocoin-list/pull/257

![2018-07-29_1755](https://user-images.githubusercontent.com/11302675/43368139-c5136ffa-9358-11e8-9fe2-bdb6c5f0c546.png)

@krystian3w masz ten błąd ?

**Comment by MajkiIT** [comment]
@OtakuPL Twierdzisz, że nie masz koparek ...  a jednak są ==> `||estream.xyz/embed-wb8rozmy2slr.html$subdocument,domain=a-o.ninja`

**Comment by krystian3w** [comment]
Mam i jak odblokowałem skrypt i dodałem wyjątki to się naprawia galeria, Firefox 61.0.1.

Playerów nie testowałem.

**Comment by OtakuPL** [comment]
@MajkiIT pierwszy raz słyszę, żeby ten odtwarzacz miał miner. Nigdy u nich nie piszę, że go używają.. pozatym to nie miner od a-o.ninja
A-O używa go od lat o nigdy nikt nie zgłaszał nic o minerze więc nie wiem :/

**Comment by MajkiIT** [comment]
@KonoromiHimaries @hawkeye116477 możecie sprawdzić u siebie?
@krystian3w Dziękuję
@OtakuPL Jeśli tak uważasz to poproś o odblokowanie.

**Comment by krystian3w** [comment]
Ale jak będziesz zgłaszać "brak koparek" to chyba do uAssets, ich filter wycina nadrzędnie / aktywuje się nadrzędnie.

**Comment by OtakuPL** [comment]
Zgłaszałem, ale nadal nie działa:
http://scr.hu/2ci4/ls6m3
http://scr.hu/2ci4/1gx0a
czyściłem przeglądarkę, cache itp

**Comment by hawkeye116477** [comment]
@OtakuPL Najwyraźniej ktoś tu ci źle poradził, korzystasz z AdBlocka, więc zapraszam tutaj => `https://github.com/hoshsadiq/adblock-nocoin-list/issues`.

**Comment by krystian3w** [comment]
Ale klapa Francuska / Arabka nie umie zdiagnozować problemu.

**Comment by krystian3w** [comment]
U mnie wrócił komunikat o adblocku, jak już chcemy naprawić slider to i dobrze oszukać ten skrypt dopuszczając jego wygenerowane elementy poza ekranem, które potem blokują generyczne reguły EasyList.

```
a-o.ninja#@#.text_ad
a-o.ninja#@#.textAd
a-o.ninja#@#.text-ad

a-o.ninja#@#.text-ads
a-o.ninja#@#.text_ads

a-o.ninja#@#.text-ad-links

a-o.ninja#@#.pub_728x90
a-o.ninja#@#.pub_300x250m
a-o.ninja#@#.pub_300x250
```

albo wycinać komunikat do czasu aż nie przypiszą mu losowych klas, występowania w drzewie: `##.jgcabd-container`
