### ISSUE TITLE
forsal.pl + edgp.gazetaprawna.pl + inforfk.pl + inforlex.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8515]
http://forsal.pl/artykuly/1194518,brytyjska-izba-gmin-rekomenduje-regulowanie-i-opodatkowanie-facebooka.html
![opera zdjecie_2018-07-29_035802_forsal pl](https://user-images.githubusercontent.com/36385327/43362178-9e04c708-92e3-11e8-90a5-071d87c9c039.png)

https://edgp.gazetaprawna.pl
![opera zdjecie_2018-07-29_035840_edgp gazetaprawna pl](https://user-images.githubusercontent.com/36385327/43362181-b257545a-92e3-11e8-9ffe-d90679a13ac5.png)

https://inforfk.pl
![opera zdjecie_2018-07-29_035905_inforfk pl](https://user-images.githubusercontent.com/36385327/43362183-c2b7210e-92e3-11e8-8da7-ebe63cc8a102.png)

https://www.inforlex.pl
![opera zdjecie_2018-07-29_035929_www inforlex pl](https://user-images.githubusercontent.com/36385327/43362185-d01aa136-92e3-11e8-9260-a8e3c5c3bb0e.png)

**Comment by krystian3w** [comment]
Chyba udało mi się ogarnąć, nawet odblokowanie stockowej grafiki.
