### ISSUE TITLE
blog.wirtualnemedia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8516]
Social
http://blog.wirtualnemedia.pl
![opera zdjecie_2018-07-29_042359_blog wirtualnemedia pl](https://user-images.githubusercontent.com/36385327/43362300-452b51a2-92e7-11e8-99c3-a29230c23e5c.png)

http://blog.wirtualnemedia.pl/renata-lipinska-kondratowicz/post/moj-potwor
![opera zdjecie_2018-07-29_042437_blog wirtualnemedia pl](https://user-images.githubusercontent.com/36385327/43362307-5949f7ce-92e7-11e8-82d5-6007409b437b.png)
![opera zdjecie_2018-07-29_042447_blog wirtualnemedia pl](https://user-images.githubusercontent.com/36385327/43362308-596da53e-92e7-11e8-8f6b-5a346940657e.png)

**Comment by krystian3w** [comment]
Chyba udało mi się ogarnąć.

**Comment by hawkeye116477** [comment]
```
||nk.pl/fajne/widget$third-party
blog.wirtualnemedia.pl###social_ikons_header_fixed:style(visibility: hidden !important;) 
```
Druga reguła po to, by „schować" zbędny element po lewej, trzeba było zrobić to za pomocą visibility, bo inaczej układ strony się psuje.
