### ISSUE TITLE
allrecipes.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8518]
![opera zdjecie_2018-07-30_014845_allrecipes pl](https://user-images.githubusercontent.com/36385327/43371905-cbc53cec-939a-11e8-96e3-07be42409319.png)

**Comment by krystian3w** [comment]
Nie mam pomysłu na obejście poza regułami klikającymi w Nano Adblocker lub dodatkowym skryptem.

Jak 🐧 doda regułę, to upewnij się, że masz aktywowany "Nano Annoyance" i jest on zaktualizowany.

**Comment by hawkeye116477** [comment]
Dodane do skryptu => `https://greasyfork.org/pl/scripts/369153-supplement-for-filterlist-polish-gdpr-cookies-filters-supplement-for-ublock-adguard/code#n105` :smile:

**Comment by xMaap** [comment]
@hawkeye116477 Popraw w tym skrypcie http://www.f1racing.pl bo nie działa

**Comment by krystian3w** [comment]
Po https działa.

**Comment by krystian3w** [comment]
Widać strona miała https i nie ma lub literówka z "`s`".

**Comment by krystian3w** [comment]
Aha już wiem `www.` robi problem... 😉.

**Comment by hawkeye116477** [comment]
@xMaap Poprawione :smile:
`https://greasyfork.org/pl/scripts/369153-supplement-for-filterlist-polish-gdpr-cookies-filters-supplement-for-ublock-adguard/diff?v1=616655&v2=616640`

**Comment by hawkeye116477** [comment]
@xMaap @krystian3w Poprawione :smile:
