### ISSUE TITLE
Linki afiliacyjne

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#8525]
https://www.digitalmoney.pl/porady,czym-rozni-sie-kredyt-i-pozyczka,13.html czy dla Was to reklamy?

**Comment by hawkeye116477** [comment]
Ta strona to w ogóle chyba jakaś popsuta, na górze wielki widżet, a potem menu strony.
Chyba można uznać parę elementów za nachalne reklamy :smile:.
Nie wiem czy nie przesadziłem :smile:
```
||systempartnerski.oferty-kredytowe.pl^
||affiliate44.com.pl^
||cdn.comperia.pl^$domain=www.digitalmoney.pl
||www.comperialead.pl^$domain=www.digitalmoney.pl 
```

**Comment by MajkiIT** [comment]
@hawkeye116477 no właśnie sam uznałem to za reklamy. Nie chciałem podsuwać swojej wizji. Dziękuje.

**Comment by HateAds** [comment]
@MajkiIT Większość z tego co jest na tej stronie to dla mnie reklamy.. Szczególnie wali po oczach ten widżet ( dla mnie to jeden z najgorszych typów reklamy ).

**Comment by HateAds** [comment]
@hawkeye116477 Nie przesadziłeś.
