### ISSUE TITLE
video.wp.pl

### ISSUE THREAD

**Issue by HateAds** [MajkiIT/polish-ads-filter#8529]
Mam pytanie do Was, czy jest możliwość podniesienia do góry kilku elementów na tej stornie ?
Przykładowo w tym linku. https://video.wp.pl/i,naturalne-sposoby-na-oparzenia-sloneczne,mid,2023916,cid,5050,klip.html?ticaid=11bbe0
![image](https://user-images.githubusercontent.com/29756590/43464441-6ceb1cea-94db-11e8-904b-f3d010bfe356.png)
![image](https://user-images.githubusercontent.com/29756590/43464462-75878942-94db-11e8-84a5-64fbc6758390.png)
![image](https://user-images.githubusercontent.com/29756590/43464491-84ee8c96-94db-11e8-842d-55cea29b2814.png)

**Comment by MajkiIT** [comment]
@HateAds zabrzmi to dziwnie .... wyczyść ciasteczka i odśwież stronę ...

**Comment by HateAds** [comment]
@MajkiIT Wyczyściłem, zreinstalowałem ublocka plus mam aktualnego Chromea i nadal mam te odstępy.
Macie tak samo ? @hawkeye116477 @xxcriticxx @krystian3w

**Comment by MajkiIT** [comment]
Używasz ciasteczkowym filtrów ?5

**Comment by HateAds** [comment]
Tutaj wszystkie filtry które mam włączone.
![image](https://user-images.githubusercontent.com/29756590/43471779-208de042-94ec-11e8-9e82-93daa9a426aa.png)

**Comment by krystian3w** [comment]
Prawie zawsze się da, chyba że strona skopana - wtedy lepiej nie ruszać.

**Comment by HateAds** [comment]
@krystian3w Niestety nie pomogło, chyba czas na zmianę przeglądarki.

**Comment by xxcriticxx** [comment]
@HateAds nie widze resztek. dziwie sie ze to dziala u mnie i nie jestem geolock

![capture](https://user-images.githubusercontent.com/15007183/43480652-e0329318-94d1-11e8-8c67-c5db3e32ec4c.PNG)

**Comment by HateAds** [comment]
@xxcriticxx Na Chromie sprawdzałeś ?

**Comment by xxcriticxx** [comment]
@HateAds tak ver Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by HateAds** [comment]
@xxcriticxx Ja jestem na wersji 68.0.3440.75 (Oficjalna wersja) (64-bitowa)
Może to przez tą wersję wycina u mnie.

**Comment by krystian3w** [comment]
https://portableapps.com/apps/internet/google_chrome_portable - zobacz czy w tym ruszy bez luk po skonfigurowaniu uBlock Origin i Nano Defender.

**Comment by xxcriticxx** [comment]
@HateAds zaraz zrobie update dla chroma

**Comment by xxcriticxx** [comment]
na Version 68.0.3440.75 (Official Build) (64-bit) bez zmian

**Comment by xxcriticxx** [comment]
@HateAds nie widze cookie filtrow i KAD filtrow

**Comment by krystian3w** [comment]
Ale one raczej nie pomogą, nie wcisnęli chyba reklam w plik do cookies albo w domeny z przekrętami (sami kręcą, robiąc losowanie z własnych domen, by linków nie dało się blokować).

**Comment by xxcriticxx** [comment]
xtra jest nano filters

**Comment by krystian3w** [comment]
Pingwin reklam / dziur nie odblokowuje.

**Comment by xxcriticxx** [comment]
napewno cookie nie pradwidlowe

**Comment by HateAds** [comment]
Pomogło zainstalowanie filtra 
Polskie Filtry RODO-Ciasteczkowe
Teraz jest ok, do zamknięcia.

**Comment by MajkiIT** [comment]
Ciasteczka pomogły, ale nie mogę napisac tutaj czemu ...
