### ISSUE TITLE
Microsoft

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8531]
https://www.msn.com/pl-pl/
![opera zdjecie_2018-07-31_184925_www msn com](https://user-images.githubusercontent.com/36385327/43474244-9aa2f39e-94f2-11e8-9a05-f2b39ff9573f.png)

Po zalogowaniu się nie ma tego
![opera zdjecie_2018-07-31_185016_www msn com](https://user-images.githubusercontent.com/36385327/43474255-a312551a-94f2-11e8-98b5-d586c279a7a2.png)
![zrzut ekranu z 2018-07-31 18-51-26](https://user-images.githubusercontent.com/36385327/43474298-be707d82-94f2-11e8-8cff-0d3f6eff2f55.png)

https://www.msn.com/pl-pl/styl-zycia
https://www.msn.com/pl-pl/kuchnia
https://www.msn.com/pl-pl/podroze
https://www.msn.com/pl-pl/zdrowie
https://www.msn.com/pl-pl/rozrywka
https://www.msn.com/pl-pl/rozrywka/quizy
https://www.msn.com/pl-pl/motoryzacja
Włączony
![opera zdjecie_2018-07-31_185212_www msn com](https://user-images.githubusercontent.com/36385327/43474335-e28b8b08-94f2-11e8-915f-d0b90598d8ae.png)
Wyłączony
![opera zdjecie_2018-07-31_185252_www msn com](https://user-images.githubusercontent.com/36385327/43474359-f4804510-94f2-11e8-89c6-83abac38756b.png)

https://loty.msn.com/pl-pl/wyszukiwarka-lotow
https://wynajemsamochodow.msn.com/pl-pl/wynajem-samochodow
Włączony
![opera zdjecie_2018-07-31_185624_wynajemsamochodow msn com](https://user-images.githubusercontent.com/36385327/43474531-79f54e48-94f3-11e8-8cb2-069238c7ce74.png)
Wyłączony
![opera zdjecie_2018-07-31_185719_wynajemsamochodow msn com](https://user-images.githubusercontent.com/36385327/43474579-9a77e2fc-94f3-11e8-87bf-49f111f1661f.png)

https://outlook.com
Zwykła wersja
![opera zdjecie_2018-07-31_190003_outlook live com](https://user-images.githubusercontent.com/36385327/43474726-fbe45408-94f3-11e8-9624-d50af1ba45ec.png)
Z włączoną wersją beta
![opera zdjecie_2018-07-31_185855_outlook live com](https://user-images.githubusercontent.com/36385327/43474701-e250c198-94f3-11e8-8000-39edb50d283e.png)

https://web.skype.com/pl
![opera zdjecie_2018-07-31_190341_web skype com](https://user-images.githubusercontent.com/36385327/43474900-753d6132-94f4-11e8-8e3d-7dfb4c3f315a.png)

Konto:
testtestest21512@outlook.com
teeeeeeeeeest123242

**Comment by krystian3w** [comment]
Nie ukradnie nikt tego outlooka?

**Comment by krystian3w** [comment]
msn.com##body.uhf.sp .head:style(transform: none;)

---

`loty.msn.com###precontent :style(margin-top: 0 !important;)`
lub
`loty.msn.com###precontent:style(margin-top: -22px !important;)`

Strzałki ładują się po kilku sekundach - jakieś 3-4 po nazwie miasta.
---

web.skype.com##.info.notification:abp-contains(cookie)

---

`outlook.live.com##.notificationBarSlideIn.ms-bgc-ns` - reklama Edge do używania poczty

---

`outlook.live.com###owaadbar` - od pingwina, na stary interfejs - chyba wycina komunikat po prostu.

**Comment by krystian3w** [comment]
msn.com##body.uhf.sp .head:style(transform: none;)

---

`loty.msn.com###precontent :style(margin-top: 0 !important;)`
lub
`loty.msn.com###precontent:style(margin-top: -22px !important;)`

Strzałki ładują się po kilku sekundach - jakieś 3-4 po nazwie miasta.

---

`web.skype.com##.info.notification:abp-contains(cookie)`

---

`outlook.live.com##.notificationBarSlideIn.ms-bgc-ns` - reklama Edge do używania poczty

---

`outlook.live.com###owaadbar` - od pingwina, na stary interfejs - chyba wycina komunikat po prostu.

**Comment by krystian3w** [comment]
`msn.com##body.uhf.sp .head:style(transform: none;)`

---

`loty.msn.com###precontent :style(margin-top: 0 !important;)`
lub
`loty.msn.com###precontent:style(margin-top: -22px !important;)`

Strzałki ładują się po kilku sekundach - jakieś 3-4 po nazwie miasta.

---

`web.skype.com##.info.notification:abp-contains(cookie)`

---

`outlook.live.com##.notificationBarSlideIn.ms-bgc-ns` - reklama Edge do używania poczty

---

`outlook.live.com###owaadbar` - od pingwina, na stary interfejs - chyba wycina komunikat po prostu.

**Comment by xMaap** [comment]
Jak ktoś ukradnie to mówi się trudno

**Comment by xxcriticxx** [comment]
@krystian3w te na outlook juz nie dzialaja

**Comment by xMaap** [comment]
Strona główna msn.com, skype.com, loty.msn.com działa. Na podstrony msn.com, wynajemsamochodow.msn.com, outlook.com nie działa.

**Comment by xxcriticxx** [comment]
trzeba bedzie zgloszenie u pingiwn otworzyc

@xMaap pozycze konta testowego

**Comment by xMaap** [comment]
A i jeszcze tutaj pozostałości po reklamach
https://www.msn.com/pl-pl/sport
https://www.msn.com/pl-pl/finanse
https://www.msn.com/pl-pl/wiadomosci
![opera zdjecie_2018-07-31_215751_www msn com](https://user-images.githubusercontent.com/36385327/43483874-13134fe4-950d-11e8-833f-d9fc8a12bfc0.png)

**Comment by xMaap** [comment]
I jeszcze tutaj pozostałości
https://www.msn.com/pl-pl/
![opera zdjecie_2018-07-31_220428_www msn com](https://user-images.githubusercontent.com/36385327/43484130-c45fee06-950d-11e8-9f04-9673507bb8fa.png)

**Comment by xMaap** [comment]
Social
https://emea.flow.microsoft.com/pl-pl/
https://channel9.msdn.com
https://azure.microsoft.com/pl-pl/
https://powerapps.microsoft.com/pl-pl/blog/
![opera zdjecie_2018-07-31_222103_emea flow microsoft com](https://user-images.githubusercontent.com/36385327/43485146-b27d9488-9510-11e8-8acd-df4796f1b03b.png)

Cookies
https://www.microsoft.com/pl-PL/servicesagreement/
https://www.microsoft.com/en-us/legal/IntellectualProperty/Trademarks/EN-US.aspx
https://developer.microsoft.com/pl-pl/windows
https://careers.microsoft.com/us/en

**Comment by xxcriticxx** [comment]
@xMaap adblock poprawiony more info u pingwina

**Comment by xxcriticxx** [comment]
mozna zamknac?

**Comment by krystian3w** [comment]
Raczej nie jeszcze są luki od źle powycinanych cookies i wypadało by w uBO to zrobić lepiej / poprawić.

**Comment by xMaap** [comment]
Czasami w poczcie dalej się pojawia
![opera zdjecie_2018-08-16_221354_outlook live com](https://user-images.githubusercontent.com/36385327/44232576-ca431280-a1a1-11e8-9b63-490774b9fc52.png)

**Comment by xxcriticxx** [comment]
@xMaap testowales to od pingwina
```
@@||s.aolcdn.com/ads/adswrappermsni.js$script,domain=outlook.live.com
@@||acdn.adnxs.com/$script,domain=outlook.live.com
```
or
```
live.com##div:if(:scope > div > div[class^="__Microsoft_Owa_Adsbar_"])
live.com##div:if(:scope > div > div > div[id^="owaadbar"])
```

**Comment by xMaap** [comment]
@xxcriticxx oczywiście. To się nie pojawia co chwilę, ale czasami jak wejdziesz, albo odświeżysz stronę.

**Comment by krystian3w** [comment]
Na nowy (beta) może takie coś:

```
outlook.live.com##div#app > div > div:nth-child(2) > div > div > div:nth-child(4)
```

A na stary:

```
outlook.live.com###primaryContainer div[style*="right: 165px;"]:style(right:0 !important;)
```

:question:

**Comment by xMaap** [comment]
@krystian3w Wersje beta jeszcze sprawdzę, ale w wersji starej zauważyłem, że:
- ukrywa po prawej stronie belkę tak jak powinno być
- czy to jest obojętnienie czy z twoją regułą czy bez twojej ukrywa po chwili ukrywa element
![we](https://user-images.githubusercontent.com/36385327/44264475-14b8a380-a223-11e8-9834-933b584899f3.gif)

**Comment by krystian3w** [comment]
U mnie zostaje białe pole po prawej i kosmetyczne zresetowanie do prawej ją usuwa - ale to już taka ostateczna wersja jak nic złego poza komunikatem się nie dzieje.

**Comment by xMaap** [comment]
@krystian3w chyba ta Twoja reguła do bety pomogła.
