### ISSUE TITLE
otomoto.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8536]
https://www.otomoto.pl/oferta/bmw-seria-5-bmw-535d-limuzyna-m-pakiet-alu-19-fotel-komfortowy-led-ID6ARBlp.html

![zrzut ekranu z 2018-08-02 18-45-36](https://user-images.githubusercontent.com/36385327/43598195-6c61c7ce-9684-11e8-8160-a7499b706b35.png)

**Comment by MajkiIT** [comment]
@xMaap u mnie jest ok...

**Comment by krystian3w** [comment]
Jak chodzi o wyskakującą część nawigacji to raczej zamierzony ich dizajn.

**Comment by xMaap** [comment]
Raczej chodzi mi o to, że jak scrollujesz stronę to pomiędzy nawigacją jest tam luka. Tylko teraz patrzę to teraz nawet ta nawigacja nie zjeżdża.

**Comment by krystian3w** [comment]
To zobacz w loggerze co ją przywiesza do góry, ja kojarzę tylko listę matiego i obecnie poprawił jak widzisz.
