### ISSUE TITLE
cdax.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8541]
@MajkiIT please regex pod guzikiem pobierz

Kliknij na wybraną jakość wideo, odczekaj 5 sekund, a następnie naciśnij "SKIP AD" w rogu ekranu

**Comment by krystian3w** [comment]
<sup>

- https://addons.mozilla.org/pl/firefox/addon/video-downloadhelper/

- https://chrome.google.com/webstore/detail/video-downloadhelper/lmjnegcaeklhafolokijcfjliaokphfk?hl=pl

- https://chrome.google.com/webstore/detail/flash-video-downloader/aiimdkdngfcipjohbjenkahhlhccpdbc?hl=pl

- https://addons.opera.com/pl/extensions/details/fvd-video-downloader/ 

</sup>

**Comment by krystian3w** [comment]
<br>
<sup>

- https://addons.mozilla.org/pl/firefox/addon/video-downloadhelper/

- https://chrome.google.com/webstore/detail/video-downloadhelper/lmjnegcaeklhafolokijcfjliaokphfk?hl=pl

- https://chrome.google.com/webstore/detail/flash-video-downloader/aiimdkdngfcipjohbjenkahhlhccpdbc?hl=pl

- https://addons.opera.com/pl/extensions/details/fvd-video-downloader/ 

</sup>

**Comment by MajkiIT** [comment]
@xxcriticxx jakikolwiek link wstawię to dajstaję Nie znaleziono filmu na serwerze cda.pl . Co ty tam sklejasz?

**Comment by xxcriticxx** [comment]
@MajkiIT cda pozmienialo na stronie zostaly tylko premium free material poszedl bye bye

**Comment by MajkiIT** [comment]
@xxcriticxx spróbuj taki filtr 
`/static/js/amvn.js`

**Comment by xxcriticxx** [comment]
@MajkiIT potestuje jak wszystko wroci do normy

**Comment by MajkiIT** [comment]
@xxcriticxx tak możesz przetestować
https://cdax.pl/img/hint.png

**Comment by xxcriticxx** [comment]
test link:
https://cdax.pl/video/201365468/vfilm

@MajkiIT koparki?
`websocket | wss://cdax.pl/socket.io/?EIO=3&transport=websocket&sid=H6OAd1lJ9xrQSn1pAFtD`

**Comment by xxcriticxx** [comment]
@MajkiIT extra karta sie otwiera z popads ale odrazu sie zamyka

Dziękuję za obejrzenie reklamy i życzę miłego seansu :)

**Comment by krystian3w** [comment]
`cdax.pl##script:inject(window.open-defuser.js)` ale nie wiem czy on nie działa podobnie, że coś się przebija i zamyka albo utrudnia używanie strony.

**Comment by xxcriticxx** [comment]
@krystian3w z `cdax.pl##script:inject(window.open-defuser.js)` guzik POBIERZ nie dziala

**Comment by krystian3w** [comment]
OK, to widać trzeba jakąś bardziej zaawansowaną lub olać, że coś się otwiera i zamyka.

**Comment by MajkiIT** [comment]
@xxcriticxx szukam rozwiązania, ale zablokowanie elementu powodu problem z pobraniem pliku.

**Comment by krystian3w** [comment]
Trzeba by chyba wykombinować skrypt co zamieni u nich w skrypcie 'wartości' "`Window`" na "`Self`".

Zakładając, że nie próbujemy blokować jakieś reklamy a tylko ograniczyć by serwis działał w jednej zakładce (karcie) / oknie.

Na pewno problematyczne będzie obejście reflinków jakie się zdarzają.

**Comment by xxcriticxx** [comment]
@MajkiIT dont worry poczekamy

@krystian3w thx for your help

**Comment by MajkiIT** [comment]
@xxcriticxx Niestety nie mam pomysłów
