### ISSUE TITLE
psy.pl + koty.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8550]
![opera zdjecie_2018-08-07_020349_www psy pl](https://user-images.githubusercontent.com/36385327/43746742-61f8e906-99e6-11e8-88c2-c8fdb7de283d.png)

**Comment by krystian3w** [comment]
* `/wp-content/plugins/mm-extensions/assets/js/info-popup.js`

* `/wp-content/plugins/mm-extensions/assets/css/info-popup.css` 
   `###infoPopup`

---

Ale by wymagało ocenienia na ile walą oni jakimiś przyjaznymi pop-upami lub tylko w uBlock Origin / AdGuard odblokowywać przewijanie.

**Comment by hawkeye116477** [comment]
Nie trzeba nic oceniać, ze skryptu wyraźnie wynika, że oni wykorzystują go tylko dla tego komunikatu RODO.
