### ISSUE TITLE
infostrow.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8552]
![opera zdjecie_2018-08-08_022519_infostrow pl](https://user-images.githubusercontent.com/36385327/43809412-529aca3e-9ab2-11e8-985f-940e695a70a3.png)

**Comment by krystian3w** [comment]
`###rodo-modal` i tylko dla uBO / AdGuarda (przewijanie).

**Comment by hawkeye116477** [comment]
Można jeszcze lepiej => `https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/a842a4465de103092286e3ee7fe228e71577c295#commitcomment-30000964` :smile:

**Comment by krystian3w** [comment]
Pudło, EasyList i nie wiem jak odblokować na razie.

**Comment by hawkeye116477** [comment]
@MajkiIT Ciastek nie ma, ale zostały bugi dla ciebie :smile:.
