### ISSUE TITLE
belsat.eu/pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8553]
![opera zdjecie_2018-08-08_022702_belsat eu](https://user-images.githubusercontent.com/36385327/43809459-921ef1e4-9ab2-11e8-9a3b-78b24a53ee8a.png)

**Comment by krystian3w** [comment]
`belsat.eu##.popmake-overlay`
`belsat.eu##.pum-open:style(overflow: auto !important;)`

**Comment by hawkeye116477** [comment]
Dla FF starczy tylko `belsat.eu##^.popmake-overlay`
