### ISSUE TITLE
werandacountry.pl + werandaweekend.pl + astromagia.pl + wrozka.com.pl + gwiazdy.com.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8554]
![opera zdjecie_2018-08-08_085713_www werandaweekend pl](https://user-images.githubusercontent.com/36385327/43821292-101f973e-9ae9-11e8-9dad-ea41e93c5013.png)

https://www.astromagia.pl i https://www.wrozka.com.pl mają jeszcze Social
![opera zdjecie_2018-08-08_090104_www wrozka com pl](https://user-images.githubusercontent.com/36385327/43821488-a2e27f8c-9ae9-11e8-8623-d366d57cd089.png)
![opera zdjecie_2018-08-08_090053_www astromagia pl](https://user-images.githubusercontent.com/36385327/43821489-a3064282-9ae9-11e8-8ded-38b2b393d36a.png)

**Comment by krystian3w** [comment]
###### część 1:

`werandacountry.pl,werandaweekend.pl,astromagia.pl,wrozka.com.pl,gwiazdy.com.pl##.popup-rodo`

**Comment by hawkeye116477** [comment]
Nie cały, tylko newsletter.
