### ISSUE TITLE
cowsierscipiszczy.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8555]
https://cowsierscipiszczy.pl/forum/zachowanie-psa/agresja-psa/

Social
![opera zdjecie_2018-08-08_090228_cowsierscipiszczy pl](https://user-images.githubusercontent.com/36385327/43821559-d01e1420-9ae9-11e8-9a77-e52f3e5dab69.png)

**Comment by krystian3w** [comment]
`##.wpf-sbtn` - wytnie górę i dół:

![image](https://user-images.githubusercontent.com/35370833/43830977-feb77948-9b02-11e8-9712-e1cebc1a36b3.png) |
--- |
