### ISSUE TITLE
chillizet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8560]
laduje wam sie player?

test link:
https://www.chillizet.pl/sluchaj/online/Chilli-ZET-PL.html

**Comment by hawkeye116477** [comment]
Tak, jest gites.

**Comment by krystian3w** [comment]
W Operze 54.0.2952.64 u mnie nie działa - ciągłe ładowanie.

**Comment by hawkeye116477** [comment]
A wasze zestawy filtrów?

**Comment by xxcriticxx** [comment]
U mnie na chromie cały czas ładuje

**Comment by hawkeye116477** [comment]
Ciekawe, teraz sprawdzilem i na Chromium i Operze jest coś nie tak, a na Vivaldim, który bazuje jeszcze na tej wersji co nie było styli użytkownika, to jest ok.

**Comment by xxcriticxx** [comment]
@hawkeye116477 

![capture1](https://user-images.githubusercontent.com/15007183/43905722-a41a87d8-9bbf-11e8-9502-c843d9a78f76.PNG)
![capture2](https://user-images.githubusercontent.com/15007183/43905723-a4281ca4-9bbf-11e8-924b-641f1019f030.PNG)
![capture3](https://user-images.githubusercontent.com/15007183/43905724-a439eb50-9bbf-11e8-98dc-68dedb1111fe.PNG)

**Comment by xxcriticxx** [comment]
@hawkeye116477 ten sam player jest na radiostacja i ten dziala w chromie

http://www.radiostacja.pl/stacje-radiowe/planeta-fm

**Comment by hawkeye116477** [comment]
Ciekawe, nawet jak wszystkie listy się wyłączy, to i tak nie działa. Trzeba wyłączyć Adblockera, by zaczeło działać. Ale na Vivaldim/Chromium 65 ok, tylko wyższe coś nie halo. To chyba kolejna sprawa dla jakiegoś reportera, może @gwarser :smile:.

**Comment by xxcriticxx** [comment]
@gwarser / @F4z good luck!

**Comment by wmyrda** [comment]
dorzucając swoje 3 grosze obstawiam, że któryś ze skryptów wyszukuje wśród pluginów przeglądarki informacji o zainstalowanym adblock, gdyż na privoxy działa bez problemu

**Comment by hawkeye116477** [comment]
@wmyrda Ale Adblocker to extension/rozszerzenie a nie plugin/wtyczka :stuck_out_tongue:

**Comment by gwarser** [comment]
Z odpaloną konsolą działa świetnie :)

**Comment by xxcriticxx** [comment]
@gwarser browser?

**Comment by hawkeye116477** [comment]
Coś dla was do poczytania :
```
 http://colonelpanic.net/2010/08/browser-plugins-vs-extensions-the-difference/
https://developer.mozilla.org/pl/docs/Rozszerzenia
```
@gwarser Co działa? Trzeba radio zreperować, bo nie chce grać :smile:

**Comment by gwarser** [comment]
Chromium 68. Odpal konsolę i działa jak na Firefoksie.

**Comment by xxcriticxx** [comment]
@gwarser bez konsoli nie odpali?

**Comment by krystian3w** [comment]
Ja sprawdzałem na wyłączonych dodatkach - jest jakiś postęp wykrywania dodatków Chrome / Opery gdy są nieaktywne?

**Comment by krystian3w** [comment]
> @gwarser bez konsoli nie odpali?

i jaką... Logger uBlock Origin czy tą z Chromium dev tools.

**Comment by xxcriticxx** [comment]
@krystian3w disconnect to hostem blokuje?

**Comment by krystian3w** [comment]
Hostem / sieciowo ale dziwne, że aż muszę go całkowicie wyłączać i nie działa odświeżanie przy dodaniu domeny do wyjątków <kbd>Ctrl</kbd> + <kbd>F5</kbd> / <kbd>Ctrl</kbd> + <kbd>R</kbd>

**Comment by hawkeye116477** [comment]
To chyba nie tak coś z tą stroną, nawet bez adblockera bywa, że czasem się nie ładuje. Webmaster źle skonfigurował stronę.
`Failed to load https://ch.cdn.eurozet.pl/CHIPOL.mp3: Redirect from 'https://ch.cdn.eurozet.pl/CHIPOL.mp3' to 'https://ch02.cdn.eurozet.pl/CHIPOL.mp3' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.chillizet.pl' is therefore not allowed access.`
Przeglądarka to blokuje ze względów bezpieczeństwa, dlatego, że domyślnie pozwala tylko na requesty do tej samej domeny, jeżeli nie ma headera  'Access-Control-Allow-Origin'.

**Comment by gwarser** [comment]
Mogę zmyślać ( maluję i nawdychałem się farby i nie miałem czasu jeszcze tego obejrzeć): chrome ma taką optymalizację, że jak nie jest włączony Developoer Tools to np. nie są dostępne wersje tekstowe funkcji (funkcja.toString() czy coś w tym stylu) i czasami anty adblokery to wykorzystują do detekcji czy ktoś nie podgląda źródeł a czasami się poprostu skrypt wywala. Takie coś wykorzystuje Instart Logic (ten co go uBO-Extra pomaga blokować). U mnie po wyczyszczeniu ciastek i ctrl+f5 działa pół/pół - nie potwierdzam że adblock jest wykrywany i zawsze nie działa. Jak dodałem trochę wyjątków to działało dłuższy czas, ale oni tam domeny chyba co jakiś czas zmieniają, bo moje wyjątki przestały działać po jakimś czasie.

**Comment by xxcriticxx** [comment]
@gwarser farby wodnej?

**Comment by gwarser** [comment]
Olejnej/ftalowej :)

**Comment by gwarser** [comment]
Heh - gorhill tylko zobaczył i już coś wymyślił - kliknijcie w puste miejsce po lewej od ikony głośnika (ukryta ikonka "Play")

**Comment by hawkeye116477** [comment]
No faktycznie jest, można to naprawić tak, by była widoczna => `chillizet.pl###playerControls .playIcon:style(opacity: 1 !important;)` do list dla uBO i AdGuarda.

**Comment by xxcriticxx** [comment]
@hawkeye116477 fix dziala super

**Comment by gwarser** [comment]
Chyba bug Chroma: odpal `chrome://flags` i zmień `Autoplay policy` na "No user gesture is required"
