### ISSUE TITLE
ferguson-digital.eu

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8561]
cookies

Ta strona korzysta z ciasteczek aby świadczyć usługi na najwyższym poziomie. Dalsze korzystanie ze strony oznacza, że zgadzasz się na ich użycie

**Comment by hawkeye116477** [comment]
U mnie się ładuje niby i potem strona sama się odświeża i nagle znika :smiley:.
Coś z tą stroną nie halo, sami klikają przycisk „zgoda"..
