### ISSUE TITLE
notshinden.pl

### ISSUE THREAD

**Issue by SET19724** [MajkiIT/polish-ads-filter#8569]
### Zrzut ekranu

https://i.imgur.com/yXFrtj6.png

### Link bezpośredni

https://shinden.pl/external-video/52668-isekai-maou-to-shoukan-shoujo-no-dorei-majutsu/view/167417
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na strone obojętnie jakie anime
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome

**Filtry:**
1. Polskie filtry do Adblocka i uBlocka
2. https://i.imgur.com/u4RUbtp.png

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
To co kiedyś było znowu powróciła blokada

**Comment by SET19724** [comment]
Przy tej opcji co jest shinden.eu ładuje się poprawnie
https://i.imgur.com/4ZHF2rT.png

**Comment by xxcriticxx** [comment]
@SET19724 masz filtry najnowsze?

**Comment by SET19724** [comment]
@xxcriticxx Zaktualizowane przed dodaniem posta nic nie dało ;p

**Comment by xxcriticxx** [comment]
Napewno zmieniło się coś znowu na stronie

cc @MajkiIT lookniejsz please

**Comment by MajkiIT** [comment]
@SET19724 @xxcriticxx 
tak, wiem po 30s jest adblock. Szukamy rozwiązania.

**Comment by xxcriticxx** [comment]
@MajkiIT testowalem i mam dalej adblock

**Comment by SET19724** [comment]
@MajkiIT Ta nic to nie daje ;)

**Comment by krystian3w** [comment]
Ja nie mam nawet 30 sekund, od razu wykrywają adblock.

**Comment by MajkiIT** [comment]
@SET19724 @xxcriticxx @krystian3w 
A to sprawdzicie ?
```
@@||smartadserver.com/*ac$script,domain=shinden.pl
@@||shinden.pl^$generichide
```

**Comment by krystian3w** [comment]
mnie to nie działa, chyba że psuje to fanboy cookiemonster jakoś.

**Comment by xxcriticxx** [comment]
@MajkiIT nope

**Comment by MajkiIT** [comment]
@SET19724 @xxcriticxx @krystian3w 
Drugie podejście czyli filtry poniżej + włączcie Adguard Base Filters
```
@@||smartadserver.com/*ac$script,domain=shinden.pl
@@||shinden.pl^$generichide
```

**Comment by xxcriticxx** [comment]
@MajkiIT no good sorry bro!

**Comment by SET19724** [comment]
@MajkiIT @xxcriticxx Ta reguła działa tylko że mam reklame wtedy po lewej screen niżej.I chyba nie mam tych adguard base filters tylko te co w początkowym poście
https://i.imgur.com/zXV7vX5.png

**Comment by krystian3w** [comment]
Napisali by nam nowe reguły skryptowe i najwyżej by się tym co mają AdBlock / Adblock Plus powiedziało na razie bye bye.

**Comment by wxnko** [comment]
Moje spostrzeżenia:
Strona Shinden blokuje oglądanie podczas gdy zablokowana jest jedna z poniższych stron przez skrypt main-obfuscate.js
- cloudflare.com
- doubleclick.net
- sascdn.com
- smartadserver.com

Nie znam się na regułach, ale z trybu zaawansowanego, trzeba to zrobić tak, jak na poniższym obrazku
![image](https://user-images.githubusercontent.com/4311891/44006924-a362bc6e-9e8c-11e8-850b-d2edf3d84eff.png)

Reklamy są wtedy blokowane prawie wszystkie, oprócz jednej(pop up) oraz da się oglądać normalnie 

**To są te reguły z obrazka(nie filtry)**
shinden.pl adform.net * block
shinden.pl cloudflare.com * allow
shinden.pl doubleclick.net * allow
shinden.pl facebook.net * block
shinden.pl google-analytics.com * block
shinden.pl google.com * block
shinden.pl hsufwxpdtddlh.com * block
shinden.pl ntkuokicthbxc.com * block
shinden.pl oclasrv.com * block
shinden.pl onclasrv.com * block
shinden.pl popads.net * block
shinden.pl rtbnow.com * block
shinden.pl rtbnowads.com * block
shinden.pl sascdn.com * allow
shinden.pl shinden.eu * block
shinden.pl smartadserver.com * allow
shinden.pl tqixovpneycfmk.com * block
shinden.pl tradeadexchange.com * block
shinden.pl uwidtpjwh.com * block
shinden.pl wznnfwhwwjkp.com * block
shinden.pl zukxd6fkxqn.com * block

**Comment by krystian3w** [comment]
U mnie, to muszę odblokowywać skrypt na wykrywanie blokowania reklam lub go unieszkodliwiać:

> `@@/fuckadblock.$script$script,domain=shinden.pl`

> `shinden.pl##script:inject(abort-on-property-read.js, FuckAdBlock)`

inaczej nie mam możliwości aktywacji filmiku.

Niby poprawa jest, bo już mi nie uciekają przyciski po 30 sekundach. Dziwne, że na Firefox dopuszczenie nie odblokowywało przycisku a jeszcze nie miałem reguły skryptowej (niestety sam jej nie wymyśliłem, zrobią aktualizacje i padnie).

**Comment by krystian3w** [comment]
U mnie, to muszę odblokowywać skrypt na wykrywanie blokowania reklam (**bez** **EasyList**):

> `@@/fuckadblock.$script$script,domain=shinden.pl`

 lub go unieszkodliwiać (z EasyList):

> `shinden.pl##script:inject(abort-on-property-read.js, FuckAdBlock)`

inaczej nie mam możliwości aktywacji filmiku.

Niby poprawa jest, bo już mi nie uciekają przyciski po 30 sekundach. ~~Dziwne, że na Firefox dopuszczenie nie odblokowywało przycisków~~  a jeszcze nie miałem reguły skryptowej (niestety sam jej nie wymyśliłem, zrobią aktualizacje i padnie). Niby brak EasyList to mógł powodować, że działa i nie działa...

---

Nie mam pojęcia jak to się stało, że mi EasyList się wyłączyło i zapomniałem włączyć.

**Comment by HateAds** [comment]
U mnie adblock jest cały czas. Pewnie obserwują nasz wątek i zaraz fixują u siebie na stronie...

**Comment by xxcriticxx** [comment]
zmienie temat moze sie nie kapna

**Comment by hawkeye116477** [comment]
Na Discordzie lepiej rozmawiać na kanale tylko dla adminów :smile:
