### ISSUE TITLE
burzowo.info 

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#8573]
Patrzcie jakiego kwiatka znalazłem

**Comment by hawkeye116477** [comment]
A jeszcze tutaj => `https://burzowo.info/e6d74787ce4944.js?-ad-util.&-ad-exo-` , hehe :smile:

**Comment by gzenio22** [comment]
zniknely kolory z mapy po zdjeciu adba

**Comment by hawkeye116477** [comment]
@gzenio22 Już łobuzy zmienili nazwę skryptu.

**Comment by gzenio22** [comment]
@hawkeye116477 czyzby pilnowali nas tak jak nasi ulubiency?

**Comment by hawkeye116477** [comment]
@gzenio22 Jednak nie, on się losowo zmienia, przy każdym czyszczeniu cache jest inna nazwa.
Także nie wiem, może tak będzie ok `@@||burzowo.info/*.js?*ad`, a jak nie to można wywalić to wszystko po js i też chyba będzie git :smile:
