### ISSUE TITLE
skript.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#8574]
Alert antyadblockowy.

![screenshot_20180810_225622](https://user-images.githubusercontent.com/19818572/43981044-9e9b1d4a-9cf0-11e8-88da-92117ed64570.png)

`@@||skript.pl/ads.php`

**Comment by xxcriticxx** [comment]
@hawkeye116477 teraz wiemy gdzie ty twoje scripty piszesz

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie zgadłeś, ja tam nawet nie mam konta :stuck_out_tongue:

**Comment by xxcriticxx** [comment]
@hawkeye116477 lvl up bro
