### ISSUE TITLE
powiat.okay.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8584]
![zrzut ekranu z 2018-08-12 23-20-52](https://user-images.githubusercontent.com/36385327/44006545-78634cf0-9e86-11e8-99f4-ed3ef87a589e.png)

**Comment by krystian3w** [comment]
`||powiat.okay.pl/media/system/js/modal.js$script,domain=powiat.okay.pl` ale może wyciąć wszystkie modale.

A tak to raczej uBlock Origin / AdGuard i chyba jakąś regułą przerywającą pop-up (kosmetycznie nie umiem odblokować przewijania, skrypt po chwili ubija strzałki i rolkę - działa ręczne użycie suwaka lub wciśnięcie rolki).

**Comment by hawkeye116477** [comment]
W galerii wykorzystują coś innego, więc raczej blokada skryptu jest git.
