### ISSUE TITLE
docs.ovh.com/pl/

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8587]
cookies

Użytkowanie strony oznacza zgodę na wykorzystywanie plików cookie, w celu zapewnienia prawidłowego działania strony i realizowania statystyk odwiedzin.Więcej informacji i zarządzanie plikami cookie

![capture](https://user-images.githubusercontent.com/15007183/44006908-19e61940-9e5a-11e8-82ee-ca60d4ae7d02.PNG)

**Comment by hawkeye116477** [comment]
`docs.ovh.com###cookiesPop`

**Comment by krystian3w** [comment]
Uciąłem doc niby działa [![crazy face](https://camo.githubusercontent.com/5be2339f518c6cdbb0cd00fba87c27fefab2b2ed/68747470733a2f2f666f72756d2e646f62726570726f6772616d792e706c2f696d616765732f656d6f6a692f6170706c652f6372617a795f666163652e706e673f763d35 ":crazy_face:")]()
