### ISSUE TITLE
abczdrowie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8589]
https://leki.abczdrowie.pl
![opera zdjecie_2018-08-13_124447_leki abczdrowie pl](https://user-images.githubusercontent.com/36385327/44027407-ae3ae8fe-9ef6-11e8-9f4b-463c888cfaaf.png)

https://ranking.abczdrowie.pl
![opera zdjecie_2018-08-13_124515_ranking abczdrowie pl](https://user-images.githubusercontent.com/36385327/44027435-beff3d66-9ef6-11e8-94d2-a0d0842364b4.png)

https://portal.abczdrowie.pl
![opera zdjecie_2018-08-13_124534_portal abczdrowie pl](https://user-images.githubusercontent.com/36385327/44027449-cc37edca-9ef6-11e8-9b6a-a61b7c20b27c.png)

**Comment by krystian3w** [comment]
`ranking.abczdrowie.pl###app > div > div > div[class*=" "] > div` - na cookies

Rodo gdzieś upchali, że nie na moje możliwości.

Białego pasa nie mam, niby znowu lista Matiego i statyczne nawigacje? Jakby dał `static` a lepiej wygląda `absolute`.

**Comment by hawkeye116477** [comment]
To samo co #8588.
