### ISSUE TITLE
modlinbus.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8598]
cookies

Hey! Cookies are Da BOMB! We use them to optimize our website content and decrease loading time and not keep you hangin`. Privacy Policy. Bake me a Cookie

https://www.modlinbus.com/en/strony/page/dojazd-z-lodzi-na-lotnisko-okecie-chopina

![capture](https://user-images.githubusercontent.com/15007183/44174394-05b1e400-a0b1-11e8-9edb-75f078459385.PNG)

**Comment by krystian3w** [comment]
`modlinbus.com##.cc-cookies` - minus, polska wersja ma inną domenę https://www.modlinbus.pl/
