### ISSUE TITLE
polsatnews.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8601]
http://www.polsatnews.pl/wideo/to-nietrafiony-eksperyment-prof-rymsza-o-moscie-w-genui-_6719819/
![opera zdjecie_2018-08-16_130011_www polsatnews pl](https://user-images.githubusercontent.com/36385327/44204822-942b7180-a154-11e8-9064-cfb6422ad774.png)

**Comment by MajkiIT** [comment]
```
@@||ipla.hit.stat24.com/ad.xml$xmlhttprequest,domain=www.polsatnews.pl
polsatnews.pl#@#.ads
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=www.polsatnews.pl
```

**Comment by MajkiIT** [comment]
@krystian3w u mnie się chowa player bez tej reguły.

**Comment by krystian3w** [comment]
Aha czyli to wyeliminowuje miganie przy starcie.

**Comment by MajkiIT** [comment]
@krystian3w dodatkowo Nano Defender powoduje ADB

**Comment by krystian3w** [comment]
Hmm..., albo błąd bo mają "dwa" pliki `ad.xml`:

```
@@||ipla.hit.stat24.com/*ad.xml$xmlhttprequest,domain=www.polsatnews.pl
```

wtedy oba będzie dopuszczać.

**Comment by krystian3w** [comment]
Hmm..., albo błąd, bo mają "dwa" pliki `ad.xml`:

* `https://ipla.hit.stat24.com/__/ad.xml`
* `https://ipla.hit.stat24.com/ad.xml`

```
@@||ipla.hit.stat24.com/*ad.xml$xmlhttprequest,domain=www.polsatnews.pl
```

wtedy oba będzie dopuszczać.

**Comment by xxcriticxx** [comment]
Przepraszamy, wideo nie jest dostepne na terenie Twojego kraju.

**Comment by krystian3w** [comment]
Jak bardzo chcesz obejrzeć:

https://megawrzuta.pl/download/28205ea5c4d76be3cb1f4f00db596af2.html

**Comment by xxcriticxx** [comment]
@krystian3w lol

**Comment by krystian3w** [comment]
Nie stać mnie na VPN ani dobre polskie proxy.

**Comment by hawkeye116477** [comment]
Na głównej pojawiła się reklama o meczach w CP.
