### ISSUE TITLE
confero.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8608]
Cookies + social
![opera zdjecie_2018-08-16_195116_www confero pl](https://user-images.githubusercontent.com/36385327/44225467-e341c880-a18d-11e8-81da-24316a45972b.png)

**Comment by hawkeye116477** [comment]
Kolejne bawią się w WP? Tak czy siak powinno pomóc => `||confero.pl/js/cookies2013$script`.

**Comment by xMaap** [comment]
@hawkeye116477 dalej jest
![opera zdjecie_2018-08-17_171742_www confero pl](https://user-images.githubusercontent.com/36385327/44274050-7ab42380-a241-11e8-8ccf-d80692ce9aa2.png)

**Comment by hawkeye116477** [comment]
@xMaap U mnie nie ma, sprawdź w trybie inkognito :smile:

**Comment by xMaap** [comment]
Wzorowałem się na tym https://github.com/MajkiIT/polish-ads-filter#about aby nie używać filtrów "Polskie Filtry Elementów Irytujących" z "Polskie Filtry RODO-Ciasteczkowe", bo ten pierwszy ma to samo do ten drugi.

**Comment by hawkeye116477** [comment]
@xMaap No co ty, w obu listach jest ta reguła.

**Comment by xMaap** [comment]
@hawkeye116477 z tego co widzę to nie tylko nie ma confero.pl
