### ISSUE TITLE
genesis-zone.com/pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8609]
Social
![opera zdjecie_2018-08-16_195244_genesis-zone com](https://user-images.githubusercontent.com/36385327/44225509-03718780-a18e-11e8-90b3-c8e402c2971d.png)
![opera zdjecie_2018-08-16_195256_genesis-zone com](https://user-images.githubusercontent.com/36385327/44225510-03718780-a18e-11e8-91d7-a07aad7e61c3.png)

**Comment by hawkeye116477** [comment]
@krystian3w ciebie wyprzedził, już dodane do dev, niedługo będzie RTM :smile:

**Comment by krystian3w** [comment]
I u mnie nie było tego na dole... 🦀
