### ISSUE TITLE
rybnik.com.pl + tuzory.pl + slaskibiznes.pl + tuwodzislaw.pl + tujastrzebie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8612]
![opera zdjecie_2018-08-17_031324_www tujastrzebie pl](https://user-images.githubusercontent.com/36385327/44242791-ec518a80-a1cb-11e8-9309-492f3bd12cf7.png)

**Comment by krystian3w** [comment]
* `rybnik.com.pl`, `slaskibiznes.pl`, `tuwodzislaw.pl` - na razie można nawet w AdBlocku / Adblock Plus (aż się nie zablokuje przewijanie przez webmasterów
* `tuzory.pl`, `tujastrzebie.pl` -  HTML filtering / reguła skryptowa (nie wymyśliłem) / CSS 

---

`rybnik.com.pl,slaskibiznes.pl, tuwodzislaw.pl###pd-modal, .modal-backdrop`

`tuzory.pl,tujastrzebie.pl###pd-modal, .modal-backdrop`
`tuzory.pl,tujastrzebie.pl###.modal-open:style(overflow: auto !important;)`

`rybnik.com.pl,slaskibiznes.pl, tuwodzislaw.pl,tuzory.pl,tujastrzebie.pl##^#pd-modal`

**Comment by krystian3w** [comment]
* `rybnik.com.pl`, `slaskibiznes.pl`, `tuwodzislaw.pl` - na razie można nawet w AdBlocku / Adblock Plus (aż się nie zablokuje przewijanie przez webmasterów)
* `tuzory.pl`, `tujastrzebie.pl` -  HTML filtering / reguła skryptowa (nie wymyśliłem) / CSS 

---

`rybnik.com.pl,slaskibiznes.pl,tuwodzislaw.pl###pd-modal, .modal-backdrop`

`tuzory.pl,tujastrzebie.pl###pd-modal, .modal-backdrop`
`tuzory.pl,tujastrzebie.pl###.modal-open:style(overflow: auto !important;)`

`rybnik.com.pl,slaskibiznes.pl,tuwodzislaw.pl,tuzory.pl,tujastrzebie.pl##^#pd-modal`

----

Pliku JS ani zapytania XHR nie widzę by działało w miarę szybko i prosto.

---

Plik "`popupy_polityka_specjalne_instrukcje.txt`" pewnie do lekkiej poprawki, po wklejeniu przez mnie reguł; niby część można połączyć z już istniejącymi wpisami i raczej średnio mi to wyszło :scream:
