### ISSUE TITLE
stalowemiasto.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8615]
![opera zdjecie_2018-08-17_033916_stalowemiasto pl](https://user-images.githubusercontent.com/36385327/44243392-296b4c00-a1cf-11e8-8b1b-b9b1deb05722.png)

**Comment by krystian3w** [comment]
`stalowemiasto.pl##.header-parent > .container > .slot-1280px.slot` :question:
