### ISSUE TITLE
bolec.info

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8616]
Pełno reklam

**Comment by MajkiIT** [comment]
```
bolec.info##A[target="_blank"] > IMG
www.bolec.info##div.bottom:nth-of-type(6) > .bbbb
www.bolec.info##div.bottom:nth-of-type(9) > .bbbb
www.bolec.info##div.bottom:nth-of-type(10) > .bbbb > div:nth-of-type(1) > .center-cropped > div:nth-of-type(1)
www.bolec.info##div.bottom:nth-of-type(11) > .bbbb > div:nth-of-type(3) > .center-cropped
www.bolec.info##div.bottom:nth-of-type(12)
www.bolec.info##div.bottom:nth-of-type(17) > .bbbb
www.bolec.info##div.bottom:nth-of-type(20) > .bbbb
www.bolec.info##div.bottom:nth-of-type(23) > .bbbb
```

**Comment by xMaap** [comment]
https://www.bolec.info/index.php

Napisy reklama + reklama
![opera zdjecie_2018-08-17_130801_www bolec info](https://user-images.githubusercontent.com/36385327/44263290-a1149780-a21e-11e8-9f80-03cc12e37d18.png)
![opera zdjecie_2018-08-17_130750_www bolec info](https://user-images.githubusercontent.com/36385327/44263296-a5d94b80-a21e-11e8-9534-d2afe4336d6c.png)

**Comment by krystian3w** [comment]
`##table.tlo0:nth-of-type(1) > tbody > tr:nth-of-type(10) > td:nth-of-type(2)`

Na wycięcie nk.
