### ISSUE TITLE
rynekinfrastruktury.pl + rynek-lotniczy.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8619]
https://www.rynekinfrastruktury.pl/wiadomosci/drogi/warszawa-ulice-wybrzeze-szczecinskie-i-wybrzeze-helskie-zostana-rozbudowane--63959.html

Social
![opera zdjecie_2018-08-17_135753_www rynekinfrastruktury pl](https://user-images.githubusercontent.com/36385327/44265135-a45f5180-a225-11e8-8d3e-00ed6ca896a3.png)
![opera zdjecie_2018-08-17_135811_www rynekinfrastruktury pl](https://user-images.githubusercontent.com/36385327/44265136-a45f5180-a225-11e8-9c2e-03c0d8dd45b2.png)
![opera zdjecie_2018-08-17_135819_www rynekinfrastruktury pl](https://user-images.githubusercontent.com/36385327/44265137-a45f5180-a225-11e8-9843-6b47f4552571.png)

https://www.rynek-lotniczy.pl/wiadomosci/ulc-informacje-na-temat-nowych-unijnych-przepisow-dotyczacych-bezzalogowych-statkow-powietrznych-4196.html

Social
![opera zdjecie_2018-08-17_135907_www rynek-lotniczy pl](https://user-images.githubusercontent.com/36385327/44265184-d2dd2c80-a225-11e8-9e6a-b7f8cb4a1155.png)
![opera zdjecie_2018-08-17_135920_www rynek-lotniczy pl](https://user-images.githubusercontent.com/36385327/44265185-d2dd2c80-a225-11e8-98df-ccd9c743f899.png)
![opera zdjecie_2018-08-17_135934_www rynek-lotniczy pl](https://user-images.githubusercontent.com/36385327/44265186-d2dd2c80-a225-11e8-9231-46ab58b7ceb8.png)

**Comment by krystian3w** [comment]
```
rynekinfrastruktury.pl##.sledzNasContainer > .naglowek > .tekst
rynekinfrastruktury.pl,rynek-lotniczy.pl##.sledzNasContainerStopka > .naglowek > .tekst, .wiadomoscSocial, .wiadomoscSocialBig

/themes/fbLogo.jpg$image,domain=rynekinfrastruktury.pl|rynek-lotniczy.pl
/themes/twLogo.jpg$image,domain=rynekinfrastruktury.pl|rynek-lotniczy.pl
```

Sieciowe wycinanie grafik coś u mnie nie halo jak coś a chciałem z 4 reguł zrobić 2 (nawet bez regex, bo ten też po chwili padł i nic nie blokował).
