### ISSUE TITLE
newsweek.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8628]
Ukrywa
![opera zdjecie_2018-08-17_173748_www newsweek pl](https://user-images.githubusercontent.com/36385327/44275181-51e15d80-a244-11e8-86f4-5876e5643349.png)

**Comment by hawkeye116477** [comment]
U mnie jest ok, nie wiem może to @KonoromiHimaries tym razem łobuzuje :smiley:.

**Comment by xMaap** [comment]
Już teraz jest ok.

**Comment by xxcriticxx** [comment]
thank you and goodnight
