### ISSUE TITLE
basiasmoter.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8634]
Social
![opera zdjecie_2018-08-17_225422_www basiasmoter pl](https://user-images.githubusercontent.com/36385327/44288404-8bc85900-a270-11e8-80d1-fe952e8fa99c.png)
![opera zdjecie_2018-08-17_225432_www basiasmoter pl](https://user-images.githubusercontent.com/36385327/44288405-8bc85900-a270-11e8-93a8-3156cf67df8f.png)

**Comment by krystian3w** [comment]
###HTML1 .fa-pinterest-p, #HTML1 .fa-google-plus, #HTML1  .fa-heart, .footter_icons
