### ISSUE TITLE
gieldaklasykow.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8641]
cookies

Serwis wykorzystuje pliki cookies, czyli tzw. ciasteczka. Jeżeli zablokujesz możliwość użycia ciasteczek, część funkcji na stronie może nie działać prawidłowo. Więcej o ciasteczkach, a także naszą politykę prywatności, możesz przeczytać na stronie {{privacy_page}}.

**Comment by hawkeye116477** [comment]
`gieldaklasykow.pl##.ginger_banner-wrapper`
