### ISSUE TITLE
spedycje.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8642]
cookies

Zapoznaj się z polityką prywatności oraz zasadami przetwarzania danych osobowych

**Comment by hawkeye116477** [comment]
`spedycje.pl###privacy`

**Comment by MajkiIT** [comment]
@hawkeye116477 to zostawię. Dziękuję.

**Comment by krystian3w** [comment]
@@||spedycje.pl/img/icon_reklama_2017.png$image,first-party

Ja bym odblokował by tak łyso nie wyglądał.
