### ISSUE TITLE
baramundi.de / baramundi.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8644]
cookies

Dla optymalnego korzystania z naszej strony internetowej stosujemy Cookies. Poprzez używanie tej strony warażają Państwo na to zgodę. Więcej informacji OK

**Comment by hawkeye116477** [comment]
@xxcriticxx Nic tam nie ma, przynajmniej na polskiej stronie, niemiecka to do I don't care about :cookie: albo Ciasteczkowego Potwora :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 strona niemiecka ma cookie info po polsku dlatego podalem

**Comment by hawkeye116477** [comment]
@xxcriticxx 
![screenshot_20180819_131433](https://user-images.githubusercontent.com/19818572/44308236-d56c8d00-a3b1-11e8-9d49-62fc34b29294.png)
To chyba jakiś nowoczesny ten polski :smiley:

**Comment by xxcriticxx** [comment]
@hawkeye116477 masz racje jak wyczyscilem cache i cookies przegladarki teraz mam po niemiecku
