### ISSUE TITLE
warsztat.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8645]
RODO

https://warsztat.pl/artykuly/retroprojekty-czekaja-idzie-nowe-pokolenie-fanow,64838,bm9uZSE2NDgzOCEhbm93b2N6ZXNueXdhcnN6dGF0LnBsL2FydHlrdWx5L29zdGF0bmkvcmVnZW5lcmFjamEvMQ

**Comment by hawkeye116477** [comment]
`warsztat.pl###myModal, .modal-backdrop`
