### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#8649]
30 sekundowe reklamy w filmach zaczely mi sie pokazywac

**Comment by hawkeye116477** [comment]
A to nie lepiej do uAssets z tym?

**Comment by gzenio22** [comment]
reklama wskakuje mi w playerze 

![screenshot_1](https://user-images.githubusercontent.com/21177361/44311472-90178200-a3e8-11e8-9b2b-51661911697d.png)

Nie da sie jej tez pominac

**Comment by gzenio22** [comment]
Moze to pomoze

![screenshot_2](https://user-images.githubusercontent.com/21177361/44311518-3a8fa500-a3e9-11e8-938c-77b2a3c4e378.png)

**Comment by hawkeye116477** [comment]
@gzenio22 Proszę o plik z kopią zapasową uBO i podanie konfiguracji. Gdyż u mnie jest ok, może to w W10 dorzucili jakiś :gift: ...

**Comment by gzenio22** [comment]
https://gist.github.com/gzenio22/6690388a5b4015ab1556fa5093e415d7

Opera w 10 pro 64 bit nano adblock nano defender
