### ISSUE TITLE
dbamoswojafirme.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8655]
http://dbamoswojafirme.wp.pl/artykul/chwila-nieuwagi-i-masz-kredyt-tak-konczy-sie-kradziez-tozsamosci

![capture](https://user-images.githubusercontent.com/15007183/44336708-4f4e5600-a446-11e8-8e9b-112adb85c461.PNG)

**Comment by hawkeye116477** [comment]
`@@||dbamoswojafirme.wp.pl/js/ads.js`
