### ISSUE TITLE
parenting.wp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8656]
@hawkeye116477 nowa czy stara?

https://parenting.wp.pl/sa-smaczne-i-dobrze-wplywaja-na-nasz-organizm-oto-5-sokow-ktore-pokocha-twoja-watroba-wideo

![capture](https://user-images.githubusercontent.com/15007183/44336861-c388f980-a446-11e8-975e-95ae40b0a9a1.PNG)

**Comment by hawkeye116477** [comment]
Nie wiem, ale jest jeszcze ta sama strona bez dopisku wp :smile:

**Comment by krystian3w** [comment]
Może nowa, bo ostatnio pisałem, że Disconnect / Ochrona przed śledzeniem Firefox psuje `parenting.pl` a zgłosić za bardzo nie ma gdzie by ktoś jakoś naprawił gdziekolwiek.

**Comment by MajkiIT** [comment]
```
parenting.wp.pl##.article__textbox
parenting.wp.pl##.article__container > .article__side
```

**Comment by hawkeye116477** [comment]
`parenting.pl,parenting.wp.pl##.article__textbox, .article__container > .article__side`
Trzeba też dodać do tej samej strony bez dopisku wp :smile:
