### ISSUE TITLE
motocaina.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8660]
Ukrywa logo + social
![opera zdjecie_2018-08-20_183004_www motocaina pl](https://user-images.githubusercontent.com/36385327/44353394-201c0100-a4a7-11e8-9bc9-c19782ba58d0.png)

**Comment by hawkeye116477** [comment]
@MajkiIT `@@||bmc.statics.d404.pl/bundles/spoonsite/*$image,domain=www.motocaina.pl`
