### ISSUE TITLE
gazeo.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8661]
![opera zdjecie_2018-08-20_190332_gazeo pl](https://user-images.githubusercontent.com/36385327/44355044-c0742480-a4ab-11e8-8d3d-2e484d6d3b0d.png)
![opera zdjecie_2018-08-20_190353_gazeo pl](https://user-images.githubusercontent.com/36385327/44355065-d2ee5e00-a4ab-11e8-8c86-67d8d414fa89.png)

**Comment by hawkeye116477** [comment]
`gazeo.pl###rodo_accept`
