### ISSUE TITLE
autogespot.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8662]
![opera zdjecie_2018-08-20_191704_www autogespot pl](https://user-images.githubusercontent.com/36385327/44355744-af2c1780-a4ad-11e8-8ffb-f32313c3897b.png)

**Comment by hawkeye116477** [comment]
```
autogespot.pl##div[class^="popup"]:not(.fancybox-margin)
autogespot.pl##li.px1
```
