### ISSUE TITLE
wtkplay.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#8674]
Czesc! Moze bedziecie chcieli zrobic filtr ktory umozliwi ogladanie filmow na portalu epoznan.pl (np: https://epoznan.pl/news-news-88082-Pluskwy_w_bloku_na_osiedlu_Piastowskim._Gniazdo_ma_znajdowac_sie_w_jednym_z_mieszkan) i https://wtkplay.pl/. Obecnie filmy sie nie odtwarzaja gdyz skrypt wykryl blokowanie reklam

@hawkeye116477  @KonoromiHimaries @xxcriticxx @krystian3w  Macie to ?

**Comment by xxcriticxx** [comment]
dziala no adblock 

![capture](https://user-images.githubusercontent.com/15007183/44398576-65294d00-a512-11e8-9300-d5f1320758be.PNG)

**Comment by krystian3w** [comment]
W Operze działa, na Firefox wykrywają.

**Comment by MajkiIT** [comment]
@krystian3w u mnie na FF jest ok. Możesz złapać co powoduje adblocka?

**Comment by krystian3w** [comment]
Właśnie nie bardzo, mogę spróbować na Chrome portable zainstalować uBlock Origin i zobaczyć jaki filtr będzie blokował.

Opcjonalnie ręcznie blokując jakiś zasób - o ile taka informacja w czymś pomoże.

**Comment by hawkeye116477** [comment]
U mnie na Vivaldim wykrywa Adblockera.
