### ISSUE TITLE
nowawarszawa.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8675]
cookies

Ta witryna wykorzystuje pliki cookies do przechowywania informacji na Twoim komputerze. Dane są zbierane w ramach korzystania przez Państwa z usług strony internetowej, w tym zapisywanych w plikach cookies w celach analizowana i profilowania w celach marketingowych przez portal nowawarszawa.pl. Wyrażenie zgody jest dobrowolne i możesz ją dowolnym momencie wycofać korzystając z narzędzia dostępnego TUTAJ z tym, że wycofanie zgody nie będzie miało wpływu na zgodność z prawem przetwarzania na podstawie zgody, przed jej wycofaniem. Polityka prywatności

**Comment by hawkeye116477** [comment]
Znowu Fanboy łobuzuje, schował artykuł drań => `https://nowawarszawa.pl/atypical-wystawa-fotografii-mierjskiej/`.
