### ISSUE TITLE
korso.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8678]
RODO

Uprzejmie informujemy, że w związku z rozpoczęciem stosowania z dniem 25 maja 2018 roku Rozporządzenia Parlamentu Europejskiego w sprawie ochrony danych osobowych stworzyliśmy zgodną z nim politykę prywatności. W związku z tym zwracam się do Państwa z prośbą o zaakceptowanie jej postanowień, jednocześnie informujemy, że nie zwiększamy naszych uprawnień.
Prosimy zapoznać się z polityką prywatności stosowaną na naszej stronie i zaakceptować jej postanowienia."

**Comment by krystian3w** [comment]
`||www.korso.pl/ajax/privacy_popup$xmlhttprequest,domain=www.korso.pl`
