### ISSUE TITLE
ekspedyt.org

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8682]
Social
https://www.ekspedyt.org/2018/08/03/fotografia-prawde-ci-powie/
![opera zdjecie_2018-08-22_153104_www ekspedyt org](https://user-images.githubusercontent.com/36385327/44466379-6fd20800-a620-11e8-8dba-160727aa7d6e.png)

**Comment by hawkeye116477** [comment]
`ekspedyt.org##.simplesocialbuttons, .ssb_inline-share_heading`
