### ISSUE TITLE
planszowkiwedwoje.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8686]
![opera zdjecie_2018-08-23_144947_www planszowkiwedwoje pl](https://user-images.githubusercontent.com/36385327/44526343-03204180-a6e4-11e8-80ba-af883ee6c968.png)

**Comment by hawkeye116477** [comment]
`planszowkiwedwoje.pl###HTML1, [href="https://www.instagram.com/planszowkiwedwoje/"], [href^="http://www.blogger.com/follow-blog.g"]`
