### ISSUE TITLE
wiemy.to

### ISSUE THREAD

**Issue by kocid** [MajkiIT/polish-ads-filter#8687]
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. RODO
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**

**Rozszerzenia i skrypty:**

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by hawkeye116477** [comment]
```
||cdnjs.cloudflare.com/ajax/libs/fancybox/*/css/jquery.fancybox.min.css$domain=wiemy.to
||cdnjs.cloudflare.com/ajax/libs/fancybox/*/js/jquery.fancybox.min.js$domain=wiemy.to
```
