### ISSUE TITLE
bezux.pl + bezlitosne.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8688]
Social
![opera zdjecie_2018-08-24_031910_bezux pl](https://user-images.githubusercontent.com/36385327/44559908-3ea32600-a74d-11e8-8ecb-100ded1f0303.png)
![opera zdjecie_2018-08-24_032308_bezlitosne pl](https://user-images.githubusercontent.com/36385327/44559909-3ea32600-a74d-11e8-9050-e52effeac3f2.png)

**Comment by hawkeye116477** [comment]
`bezux.pl,bezlitosne.pl##.c-social-link--fb`
