### ISSUE TITLE
pl.sputniknews.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8695]
cookies

Ta strona wykorzystuje pliki cookies, aby poprawić działanie serwisu i sposób interakcji pomiędzy witryną a użytkownikiem. Za pomocą plików cookies zbieramy i tymczasowo przechowujemy niektóre dane osobowe. Możesz zmienić ustawienia cookies w swojej przeglądarce. Więcej informacji: Polityka prywatności

**Comment by hawkeye116477** [comment]
`pl.sputniknews.com###cookieContainer`
