### ISSUE TITLE
photodate.club

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#870]
http://lp.photodate.club/ph1?acid=eyJBY3Rpb25JZCI6IjUyYTQ4MDViLTlkYzQtNDA1MC05ZmE1LTg1NjY2NWU3MTUwOSJ9

Koszt usługi to 6,15 zł brutto za każdy SMS otrzymany w ramach subskrypcji

**Comment by MajkiIT** [comment]
już blokowane

**Comment by xxcriticxx** [comment]
http://lp.photodate.club/ph1?acid=eyJBY3Rpb25JZCI6IjUyYTQ4MDViLTlkYzQtNDA1MC05ZmE1LTg1NjY2NWU3MTUwOSJ9

strona jakos sie wyswietla czyli raczej nie blokowane

**Comment by xxcriticxx** [comment]
photodate.club najlepjej caly domain zablokowac
