### ISSUE TITLE
id.sonyentertainmentnetwork.com

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8700]
cookies

https://id.sonyentertainmentnetwork.com/signin/?client_id=55950157-ae9d-4b10-b0de-94dbef199f2c&scope=openid%2Ckamaji%3Aprivacy_control%2Ckamaji%3Aactivity_feed_get_feed_privacy%2Ckamaji%3Aactivity_feed_set_feed_privacy&request_locale=pl_PL&state=e30%3D&redirect_uri=https%3A%2F%2Faccount.sonyentertainmentnetwork.com%2Foauth_security_check&response_type=code&prompt=login&ui=pr&noEVBlock=false&error=login_required&error_code=4165&error_description=User+is+not+authenticated#/signin?entry=%2Fsignin

![capture](https://user-images.githubusercontent.com/15007183/44620772-2aa01700-a868-11e8-934c-fcfe00d268b8.PNG)

**Comment by hawkeye116477** [comment]
`id.sonyentertainmentnetwork.com###js-SIEWS1lib-header`
