### ISSUE TITLE
studiosante.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8707]
![opera zdjecie_2018-08-26_162328_www studiosante pl](https://user-images.githubusercontent.com/36385327/44629230-6a402f00-a94c-11e8-8c7b-d2faa0a34294.png)

**Comment by hawkeye116477** [comment]
@xMaap Przewiń do dołu, a na dole pop-up :smile: Więc to do `https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters`.
