### ISSUE TITLE
wymarzonyogrod.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8717]
https://www.wymarzonyogrod.pl/zakladanie-ogrodu/owoce-i-warzywa-w-ogrodzie/papryka-chili-uprawa-papryczki-chili-w-doniczce-na-balkonie-i-w-ogrodzie,29_3262.html

![opera zdjecie_2018-08-28_120607_www wymarzonyogrod pl](https://user-images.githubusercontent.com/36385327/44716521-d9d42c80-aaba-11e8-9120-870b6f0a2a6c.png)

**Comment by hawkeye116477** [comment]
`@@/advert.js$script,domain=wymarzonyogrod.pl`

Odblokowanie filmiku:
```
@@||sascdn.com/diff/video$domain=wymarzonyogrod.pl
@@||sascdn.com/video/flowplayer-plugin.swf$object,domain=wymarzonyogrod.pl
```
