### ISSUE TITLE
ekologia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8718]
https://www.ekologia.pl/dom-i-ogrod/pielegnacja-ogrodu/kwiaty-doniczkowe-pielegnacja-bez-uzycia-chemii,24284.html

Socail
![opera zdjecie_2018-08-28_120738_www ekologia pl](https://user-images.githubusercontent.com/36385327/44716587-0ee07f00-aabb-11e8-9581-fa992b688b1e.png)

**Comment by hawkeye116477** [comment]
`ekologia.pl##.linkWykop`
