### ISSUE TITLE
aquapark.wroc.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8724]
https://aquapark.wroc.pl
![opera zdjecie_2018-08-28_123013_aquapark wroc pl](https://user-images.githubusercontent.com/36385327/44717749-3553e980-aabe-11e8-9e82-ffc86f6a52ac.png)

http://www.basenymineralne.pl
![opera zdjecie_2018-08-28_123141_www basenymineralne pl](https://user-images.githubusercontent.com/36385327/44717810-5ae0f300-aabe-11e8-8aa7-3b6ee3ed6122.png)

https://aquapark.lodz.pl
![opera zdjecie_2018-08-28_123219_aquapark lodz pl](https://user-images.githubusercontent.com/36385327/44717832-721fe080-aabe-11e8-8c3a-7140d93b9b12.png)

https://www.parkwodny.pl
![opera zdjecie_2018-08-28_123536_www parkwodny pl](https://user-images.githubusercontent.com/36385327/44718004-fa9e8100-aabe-11e8-9ba3-adc136bd7ff1.png)

http://www.zoo.wroclaw.pl/pl/
![opera zdjecie_2018-08-28_123247_www zoo wroclaw pl](https://user-images.githubusercontent.com/36385327/44717845-7fd56600-aabe-11e8-993b-65658b81851b.png)

http://zoo.bydgoszcz.com
![opera zdjecie_2018-08-28_123328_zoo bydgoszcz com](https://user-images.githubusercontent.com/36385327/44717869-967bbd00-aabe-11e8-8c77-12fc44ec807d.png)

http://www.zoo.torun.pl/pl
![opera zdjecie_2018-08-28_124025_www zoo torun pl](https://user-images.githubusercontent.com/36385327/44718183-8dd7b680-aabf-11e8-9c9c-f261eea01f09.png)

**Comment by hawkeye116477** [comment]
```
aquapark.wroc.pl##.sticky-container
aquapark.wroc.pl###header:style(top: 0 !important;)
basenymineralne.pl##.foo-bot
aquapark.lodz.pl##.box > .section-header.ce-header, div.grid-phone-add-gutter-bottom.col-6--phone.col-6--tablet.col-3:nth-of-type(2)
parkwodny.pl##.footer-social-box
parkwodny.pl##.ppsPopupShell, #ppsPopupBgOverlay
zoo.wroclaw.pl###okno_18only
zoo.bydgoszcz.com##.f
zoo.torun.pl##.trip-rp, p > [href="http://pl-pl.facebook.com/pages/Ogr%C3%B3d-Zoobotaniczny-w-Toruniu/334822023239568"]
```
