### ISSUE TITLE
inforail.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8725]
http://inforail.pl/jest-zarzut-dla-egzaminatora-po-wypadku-na-przejezdzie-kolejowym-aktualizacja-_more_107723.html
http://transinfo.pl/etzt-2018-w-warszawie-%60przesiadz-sie-i-jedz%60_more_107488.html
http://infobus.pl/autosan-tlumaczy-sie-z-braku-oferty-na-wojskowe-autobusy_more_107751.html
http://infotram.pl/kampania-2018-stolica-lepszej-komunikacji-metro-i-tramwaje-na-mokotow-i-stegny-_more_107692.html
http://infobike.pl/krakow-zaprasza-na-edukacyjne-wycieczki-rowerowe_more_107717.html
http://infoair.pl/lot-i-tysiac-kandydatow-na-pilotow_more_107621.html
http://infoship.pl/13-statkow-do-konca-gdynskiego-sezonu-wycieczkowcow-2018-_more_107629.html
![opera zdjecie_2018-08-28_161832_inforail pl](https://user-images.githubusercontent.com/36385327/44729053-3ac12c00-aade-11e8-822c-1798974113cf.png)

A tak pomijając to proponuje usunięcia z Polskich filtrów darkwarez.pl

**Comment by hawkeye116477** [comment]
`inforail.pl,transinfo.pl,infobus.pl,infotram.pl,infobike.pl,infoair.pl,infoship.pl##.dolaczFB`
