### ISSUE TITLE
gameplanet.onet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8726]
cookies 

test link
https://gameplanet.onet.pl/gry/wladca-smokow/d1wvsqz?graj

![capture](https://user-images.githubusercontent.com/15007183/44748662-4f9dbf80-aade-11e8-922f-9fe672a8931d.PNG)

**Comment by hawkeye116477** [comment]
`espritgames.com###easy-cookies-policy-main-wrapper`
