### ISSUE TITLE
poczta.interia.pl

### ISSUE THREAD

**Issue by azet12** [MajkiIT/polish-ads-filter#8731]
Czasami po usunięciu ich reklamy cała strona ciemnieje i pojawia się na środku okienko "Wyłącz reklamy na stałe" i nie da się go zamknąć (pewnie wasze filtry usuwają niektóre przyciski na nim). Niestety już mi to zniknęło i nie zrobiłem screena.
`poczta.interia.pl##.maximized-wrapper` powinno naprawić

**Comment by MajkiIT** [comment]
@azet12 Dziękuję

**Comment by krystian3w** [comment]
Pop-up trzeba by identyfikować po zawartości a to kuleje w uBO.

![obraz](https://user-images.githubusercontent.com/35370833/50550890-1e91ef00-0c78-11e9-9394-25ca1d5858e6.png) |
--- |
