### ISSUE TITLE
znanylekarz.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8732]
![opera zdjecie_2018-08-31_142256_www znanylekarz pl](https://user-images.githubusercontent.com/36385327/44912072-61bf6e00-ad29-11e8-87b6-cb52101f23b2.png)

**Comment by hawkeye116477** [comment]
`znanylekarz.pl##[href="https://www.facebook.com/ZnanyLekarz"]`
