### ISSUE TITLE
lot.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8734]
https://www.lot.com/pl/pl/planowanie
![opera zdjecie_2018-08-31_142521_www lot com](https://user-images.githubusercontent.com/36385327/44912220-c7135f00-ad29-11e8-9b69-92dc1714a60b.png)

http://airkiosk.lot.com
![opera zdjecie_2018-08-31_142541_airkiosk lot com](https://user-images.githubusercontent.com/36385327/44912217-c2e74180-ad29-11e8-9ac0-aad767fca6ea.png)

**Comment by hawkeye116477** [comment]
```
lot.com###cookies
airkiosk.lot.com###rodoModal
```
