### ISSUE TITLE
muratordom.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8735]
https://muratordom.pl/wnetrza/kuchnia/zatkany-zlew-brodzik-wanna-zobacz-jak-odetkac-odplyw-bez-pomocy-hydraulika-aa-t3cC-bzFV-5W63.html

![opera zdjecie_2018-08-31_142706_muratordom pl](https://user-images.githubusercontent.com/36385327/44912302-fd50de80-ad29-11e8-8814-31a8fed9cbe6.png)
![opera zdjecie_2018-08-31_142716_muratordom pl](https://user-images.githubusercontent.com/36385327/44912303-fd50de80-ad29-11e8-8781-f8253623d3f9.png)

**Comment by hawkeye116477** [comment]
Rozwiązanie tylko dla Nano Adblockera=> `muratordom.pl##+js(nano-remove-elements-onready.js, .player-block-info)`
