### ISSUE TITLE
mserwery.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#8738]
### Zrzut ekranu
![screenshot_20180831_174612](https://user-images.githubusercontent.com/19818572/44922496-c4befe00-ad45-11e8-96a1-a8f3b7ea3937.png)

Reklama kalkulatora.

**Comment by xxcriticxx** [comment]
@hawkeye116477 grasz w micrafta i roloblox?

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie, przeglądałem filtry Annoyance konkurencji w poszukiwaniu polskich stron i tak znalazłem tę stronę :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 comprende
