### ISSUE TITLE
pl.chili.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8740]
![opera zdjecie_2018-09-01_072922_pl chili com](https://user-images.githubusercontent.com/36385327/44942716-c37ae900-adb8-11e8-98ff-354a4ea6095b.png)

**Comment by hawkeye116477** [comment]
`pl.chili.com##div.col-sm-3.col-xs-12:nth-of-type(4) > div.imageCont.pageFooter__section:nth-of-type(1)`
