### ISSUE TITLE
pkt.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8741]
https://www.pkt.pl/firma/kot-katarzyna-kancelaria-adwokacka-4493245#reviews
![opera zdjecie_2018-09-01_072949_www pkt pl](https://user-images.githubusercontent.com/36385327/44942718-dab9d680-adb8-11e8-9278-2442268bbdb2.png)

**Comment by hawkeye116477** [comment]
`pkt.pl##.sharing-toolbox > ul > li:nth-child(-n+5)`
