### ISSUE TITLE
crystal-launcher.pl

### ISSUE THREAD

**Issue by rico-et22** [MajkiIT/polish-ads-filter#8744]
### Zrzut ekranu

![fireshot capture 1 - strona glowna - crystal launcher - https___www crystal-launcher pl_p_main](https://user-images.githubusercontent.com/28688352/44948335-05894680-ae1c-11e8-8aca-e74c5efbbac5.png)
### Link bezpośredni

https://www.crystal-launcher.pl/p/main
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Odpalony uBlock Origin

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome 68
**Rozszerzenia i skrypty:**
uBlock Origin + Nano Defender +AAK
**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda

**Comment by hawkeye116477** [comment]
Może => `crystal-launcher.pl##script:inject(set-constant.js, adsbygoogle.loaded, trueFunc)`.
Ewentualnie dać wyjątek `@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain= crystal-launcher.pl`, jeżeli nie spowoduje to dokładki reklam.
No i resztka jeszcze => `crystal-launcher.pl###adcnt`, która się pojawia w obu przypadkach :smile:.

**Comment by rico-et22** [comment]
@hawkeye116477 Dopisałem pierwszy i trzeci filtr i wszystko chodzi
