### ISSUE TITLE
wyspagier.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#8750]
adblock detect

**Comment by hawkeye116477** [comment]
@gzenio22 To jest na głównej? U mnie nic nie ma :smile:.

**Comment by gzenio22** [comment]
http://www.wyspagier.pl/2048.htm

![screenshot_1](https://user-images.githubusercontent.com/21177361/44955227-459a0900-aeb0-11e8-85c9-e305dabf4220.png)

**Comment by hawkeye116477** [comment]
@gzenio22 Dziwne, problem najwyraźniej występuje tylko w przypadku ChrOpery. Zalecane rozwiązanie => przesiadka na Vivaldi :smiley:.
