### ISSUE TITLE
tinypic.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8753]
https://tinypic.pl/dbdlo671wtwo
![opera zdjecie_2018-09-03_022037_tinypic pl](https://user-images.githubusercontent.com/36385327/44962403-06a39c00-af20-11e8-83b0-28e3bb5fe9b5.png)
![opera zdjecie_2018-09-03_022049_tinypic pl](https://user-images.githubusercontent.com/36385327/44962404-06a39c00-af20-11e8-952b-e71a68739cb5.png)

**Comment by hawkeye116477** [comment]
`tinypic.pl##.media-toolbox:nth-of-type(4)`

**Comment by xxcriticxx** [comment]
@MajkiIT radio stars to nie reklama?

**Comment by MajkiIT** [comment]
###nexus_ban

**Comment by xxcriticxx** [comment]
@MajkiIT you welcome
