### ISSUE TITLE
iv.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8754]
Reklama i ukrywa galerie 
https://iv.pl/galerie.html
![opera zdjecie_2018-09-03_023800_iv pl](https://user-images.githubusercontent.com/36385327/44962547-6438e800-af22-11e8-97fb-c8700e64e4a2.png)

**Comment by MajkiIT** [comment]
```
iv.pl#@#.text_align_center
||webstat.pl/rkm/$image

```
