### ISSUE TITLE
pl.search.yahoo.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8755]
![opera zdjecie_2018-09-03_024027_guce oath com](https://user-images.githubusercontent.com/36385327/44962584-cf82ba00-af22-11e8-9b2a-d2596ae38b2f.png)

**Comment by hawkeye116477** [comment]
Ah, chyba znowu trzeba będzie zrobić skrypt. Ewentualnie napisać do :penguin:, ale jest wybór, więc wątpię by się zgodził na dodanie reguły klikającej OK.
