### ISSUE TITLE
tele-wizja.ru

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8768]
http://tele-wizja.ru/tvn-24-bis/

![capture](https://user-images.githubusercontent.com/15007183/45058831-e0891380-b067-11e8-8af5-e1b9d36b0b8b.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx U mnie tego nie ma. 
@hawkeye116477 zerkniesz?

**Comment by hawkeye116477** [comment]
@MajkiIT Też tego nie mam, EasyList już blokuje fuckadblock.
