### ISSUE TITLE
chrome 69 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8770]
kaka design podobne do firefoxa

**Comment by hawkeye116477** [comment]
Podobny, ale do starego :fox_face:, natomiast aktualna wersja :fox_face: przypomina te stare Chrome :smile:

**Comment by xxcriticxx** [comment]
firefox 62 na mojej posesji

![img_1659](https://user-images.githubusercontent.com/15007183/45114448-06bbbb80-b11b-11e8-9bff-81a690424a1f.jpeg)

**Comment by KonoromiHimaries** [comment]
https://www.dobreprogramy.pl/Nie-podoba-ci-sie-nowy-Chrome-Pokazujemy-jak-przywrocic-stary-wyglad,News,90699.html

**Comment by xxcriticxx** [comment]
@KonoromiHimaries thx

**Comment by krystian3w** [comment]
A nie na hybrid niby coś już namieszali.

**Comment by xxcriticxx** [comment]
@krystian3w NO ENTIENDO ¿?

**Comment by hawkeye116477** [comment]
Też nie kumam o co biega Krystianowi.
