### ISSUE TITLE
telepolis.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8779]
Social
![opera zdjecie_2018-09-07_124644_www telepolis pl](https://user-images.githubusercontent.com/36385327/45214938-20384100-b29c-11e8-8d08-43a617a07d0a.png)

Ukrywa
![opera zdjecie_2018-09-07_124718_www telepolis pl](https://user-images.githubusercontent.com/36385327/45214968-2fb78a00-b29c-11e8-866a-38231757e9c2.png)

**Comment by hawkeye116477** [comment]
U mnie wykrywa też adblockera => `@@||www.telepolis.pl/home/_js/ads.js`.
A tak po za tym, to znowu standard, fanboy łobuzuje. Może @xMaap następnym razem powinien pisać od razu do niego :smile:.
