### ISSUE TITLE
pl.vpnmentor.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8780]
https://pl.vpnmentor.com/blog/10-prostych-sposobow-na-odblokowanie-youtube-i-ogladanie-wszystkiego/?PageSpeed=noscript
![opera zdjecie_2018-09-07_125201_pl vpnmentor com](https://user-images.githubusercontent.com/36385327/45215159-eb78b980-b29c-11e8-805f-b89e5ec42bde.png)
![opera zdjecie_2018-09-07_125237_pl vpnmentor com](https://user-images.githubusercontent.com/36385327/45215160-eb78b980-b29c-11e8-8477-277e7dcb58dd.png)

**Comment by hawkeye116477** [comment]
@MajkiIT Po zjechaniu w dół pojawia się pop-up z reklamą Nord VPN.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/10662
