### ISSUE TITLE
rynekzdrowia.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#8781]
http://www.rynekzdrowia.pl

 RODO na Firefox 62.0.1 (**mobile**) blokuje przewijanie, jak wymuszę tryb PC to działa.

Filtry poaktualizowałem w uBo dev 1.16.21b5.

**Comment by hawkeye116477** [comment]
Sprawdziłem i u mnie jest ok. A jaki fon masz?

**Comment by krystian3w** [comment]
A to jeszcze pomacham później, najwyżej coś będę kombinować na własną rękę jak wyzdrowieje.

**Comment by krystian3w** [comment]
A dla mnie niewygodny - zobaczymy jak rozbudują brave na androida (mniej konfiguracji blokady reklam niż na PC).
