### ISSUE TITLE
tanibus.com

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#8786]
![screenshot_1](https://user-images.githubusercontent.com/21177361/45254563-b3e03f00-b37a-11e8-93a2-bfd89270afa3.png)

Takie cudenko :D poza tym zauwarzylem ze majac wlaczone filtry nie kupie biletu

**Comment by hawkeye116477** [comment]
`tanibus.com###rodoModal`

**Comment by hawkeye116477** [comment]
@gzenio22 Ale które Filtry? Proszę o wyłączanie po kolei i sprawdzanie :smile:.
