### ISSUE TITLE
pajacyk.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#8789]
### Zrzut ekranu
![screenshot_20180908_160545](https://user-images.githubusercontent.com/19818572/45254961-218f6980-b381-11e8-9d2f-9d47b581066f.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Rozwiązanie => `@@||static.pajacyk.pl/wp-content/themes/pajacyk/advertisement.js`

**Comment by xMaap** [comment]
A na tym pajacu to nie czasem dzięki odwiedzinom i tym reklamom nie dają tych posiłków?

**Comment by hawkeye116477** [comment]
To co, odblokowujemy reklamy :smile:?

**Comment by xxcriticxx** [comment]
czy blokuje wszystkie reklamy czy tylko niektore?

**Comment by xMaap** [comment]
Nie wiem, ale w sumie to już kilka razy czytałem, że takie coś nic nie daje i lepiej już zrobić przelew niż w coś takiego się bawić.

**Comment by MajkiIT** [comment]
ja bym niczego nie odblokowywał.
