### ISSUE TITLE
dw.com/pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8792]
https://www.dw.com/pl/
![opera zdjecie_2018-09-09_015127_www dw com](https://user-images.githubusercontent.com/36385327/45259706-12d1a280-b3d3-11e8-896e-bec9b6c2bc09.png)

https://www.dw.com/pl/sąd-przyznał-zaległe-świadczenia-ofiarom-wojny-z-polski/a-44633294
![opera zdjecie_2018-09-09_015307_www dw com](https://user-images.githubusercontent.com/36385327/45259711-20872800-b3d3-11e8-9d50-3c9481636a90.png)

https://www.dw.com/pl/poznaj-dw/social-media/s-30780
![opera zdjecie_2018-09-09_015400_www dw com](https://user-images.githubusercontent.com/36385327/45259723-43194100-b3d3-11e8-8f74-69d885875740.png)

**Comment by hawkeye116477** [comment]
`dw.com##div.col2:nth-of-type(3) > .basicTeaser.col2, .bluedw.bottom.imgTeaserS, div.externalWindowTeaser.col1, .bordeaux.bottom.imgTeaserS, .bordeaux.bottom.imgTeaserM`
