### ISSUE TITLE
epiotrkow.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#8795]
### Zrzut ekranu
![screenshot_20180910_205115](https://user-images.githubusercontent.com/19818572/45317794-50513f80-b53b-11e8-9360-e101e442c505.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Antyadblock wrócił i dali specjalną nazwę skryptu. Widać uwielbiają @MajkiIT :smiley:.
`@@||epiotrkow.pl/reklama/ads.reklama-MajkiIT.js`

**Comment by xxcriticxx** [comment]
@MajkiIT popularny jestes

**Comment by MajkiIT** [comment]
@hawkeye116477 Dziękuję
@xxcriticxx No mowa :P
