### ISSUE TITLE
tokfm.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8796]
wlacz radio jest na dole strony

http://www.tokfm.pl/Tokfm/56,130517,23817709,air-show-2018-w-radomiu-pokazy-akrobacji-i-sprzetu.html

![capture](https://user-images.githubusercontent.com/15007183/45357379-0e081c80-b594-11e8-920a-603b7c42bee9.PNG)

**Comment by MajkiIT** [comment]
@KonoromiHimaries to chyba dla ciebie
