### ISSUE TITLE
twojapogoda.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8797]
![capture](https://user-images.githubusercontent.com/15007183/45357950-f762c500-b595-11e8-9dd0-1b226ba795a4.PNG)

**Comment by MajkiIT** [comment]
@hawkeye116477 dodałem więcej ale NANO DEFENDER psuje

**Comment by hawkeye116477** [comment]
@MajkiIT No to trzeba zgłosić do :penguin: `https://github.com/jspenguin2017/uBlockProtector/issues` :smile:

**Comment by hawkeye116477** [comment]
@MajkiIT Ty też chyba zepsułeś, filmik miga po dodaniu tej reguły => `||redirector.redefine.pl/r/*.mp4$media,domain=polsatnews.pl|polsatsport.pl|twojapogoda.pl`
