### ISSUE TITLE
accuweather.com/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8798]
cookies + reklama 

https://www.accuweather.com/pl/es/moja/1456704/weather-forecast/1456704

![capture](https://user-images.githubusercontent.com/15007183/45358439-6a207000-b597-11e8-88a2-78e4b4928f7f.PNG)

**Comment by hawkeye116477** [comment]
Jest też RODO czy jak to tam nazwać `||fundingchoices.google.com^$script,domain=www.accuweather.com`
![screenshot_20180911_201457](https://user-images.githubusercontent.com/19818572/45379051-5f012a80-b5ff-11e8-95c5-1419f6beff02.png)
