### ISSUE TITLE
polsatsport.pl & polsatnews.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#8812]
### Zrzut ekranu
![screenshot_20180912_123244](https://user-images.githubusercontent.com/19818572/45419618-15a8ed80-b688-11e8-8876-c978250eb11f.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Reklama po prawej + reklamy w filmikach.
Reklamy w filmikach:
```
||polsatsport.pl/templates/psport2014/js/videoPlayer.js
||polsatnews.pl/templates/pnews/js/videoPlayer.js
```
ale to do przetestowania, bo zdaje się niby działać ok, ale może jednak gdzieś coś nie zadziała.
`http://www.polsatnews.pl/wiadomosc/2018-09-12/wlamywali-sie-do-sklepow-wjezdzajac-w-nie/?ref=kafle`
`http://www.polsatsport.pl/wiadomosc/2018-09-12/dziekanowski-milikowi-przydalaby-sie-przerwa-od-kadry/?ref=slider`

**Comment by MajkiIT** [comment]
`/js/videoPlayer.js$script,domain=polsatnews.pl|polsatsport.pl`

**Comment by hawkeye116477** [comment]
@MajkiIT A co z reklamą LM w CP po prawej?
