### ISSUE TITLE
cda-hd.cc

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#8820]
**Site Sample** | 
-----------------------------|
http://cda-hd.cc/33247/upgrade-2018-online/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1803 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.4.1544.4363**
Stealth mode:					       | enabled

| Filters enabled |
|-----------------|
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| EasyList Polish 
| Fanboy's Annoyances
| Fanboy's Cookiemonster List
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| KAD - fraud/scam 
| Malware Domains
| NoCoin Filter List 
| Peter Lowe's List
| Polish Annoyances
| Polish Main
| Polish Social
| Spam404

### Issue:

Adguard block some site: (safe browsing).
Little X button leftover player 

<details><summary><b>Screenshot:</b></summary>

![20180913152621-screenshot](https://user-images.githubusercontent.com/9846948/45491299-b28f8780-b769-11e8-9d05-efb37724f911.png)
![20180913152719-screenshot](https://user-images.githubusercontent.com/9846948/45491302-b3281e00-b769-11e8-9fdb-e04ee5e80905.png)

</details><br/>

<details><summary><b>Chrome Dev Console Output</b></summary>

![20180913153149-screenshot](https://user-images.githubusercontent.com/9846948/45491540-39dcfb00-b76a-11e8-80f6-1bd6383665f8.png)

</details><br/>

**Comment by MajkiIT** [comment]
na pewno trzeba zablokować skrypt 
`||9utwbj08.top/$script,domain=cda-hd.cc`
