### ISSUE TITLE
wp.pl oraz sportowefakty.wp.pl  REKLAMA

### ISSUE THREAD

**Issue by rakos944** [MajkiIT/polish-ads-filter#8822]
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1.  wejdz na strone :) - pojawiają się reklamy
2. 
3. 

### Moja konfiguracja
chrome

**Rozszerzenia i skrypty:**
i z nimi i bez dalej są reklamy
**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. 
4. 
![image](https://user-images.githubusercontent.com/43271861/45551817-4ecf9200-b82f-11e8-9bb8-75ae5505e891.png)

**Comment by hawkeye116477** [comment]
@rakos944 A na pewno masz Oficjalne Polskie Filtry czy tylko EasyList Polish? Tak po za tym, to duplikat, bo już jest https://github.com/MajkiIT/polish-ads-filter/issues/7533 :smile:.

**Comment by xxcriticxx** [comment]
duplicate please see #7533
