### ISSUE TITLE
ebaje.pl

### ISSUE THREAD

**Issue by bartekmad** [MajkiIT/polish-ads-filter#8823]
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. wejść na stronkę z włączonym blokerem
2. odtworzyć bajkę
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**
Google Chrome

**Rozszerzenia i skrypty:**
Ublock Origin + Ublock Origin Extra

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by bartekmad** [comment]
Coś się machnąłem w formularzu i nie wyświetla linku oraz screena:
https://i.imgur.com/6rPxp7U.png
https://ebaje.pl/bajka-online/dragon-ball-z/S14E38

**Comment by KonoromiHimaries** [comment]
https://github.com/MajkiIT/polish-ads-filter/wiki/Jak-zainstalowa%C4%87-Nano-Defender-na-Firefoksie,-Waterfoksie-albo-(Chr)Operze%3F

**Comment by xxcriticxx** [comment]
@KonoromiHimaries look up

```
Moja konfiguracja
Przeglądarka internetowa:
Google Chrome
```

**Comment by hawkeye116477** [comment]
Nic nie trzeba montować, wystarczy tylko dodać `@@||ovh.webshark.pl/adserver/1/main_script.js?advertise_check=1` :smile:

**Comment by xxcriticxx** [comment]
@hawkeye116477 thanks
