### ISSUE TITLE
pihole regex

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8834]
@MajkiIT da rade cos wykombinowac na polskie strony?

https://github.com/mmotti/pihole-regex/blob/master/regex.list

**Comment by MajkiIT** [comment]
Coś spróbuje dopasować. Dziękuję.

**Comment by MajkiIT** [comment]
1. gemius
2. doubleclick

**Comment by MajkiIT** [comment]
@xxcriticxx dodałem trochę regex-ów bazujących na domenach. Następny krok będzie urywek domeny.
