### ISSUE TITLE
skm.pkp.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8844]
Pojawia się informacja RODO i później znika.

**Comment by hawkeye116477** [comment]
@xMaap Jest już na to reguła `skm.pkp.pl#?#.ui-dialog:-abp-has(#dialog-message-rodo)`. Efekt ninja występuje zapewne z powodu użycia abp-has, bo musi wyszukać element ui-dialog, w którym jest dialog-message-rodo, a to trochę czasu zajmuje. W przypadku uBO, chyba to powinno rozwiązać ten problem => `skm.pkp.pl##+js(abort-current-inline-script.js, $, dialog-message-rodo)`.
