### ISSUE TITLE
telepizza.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#8847]
http://www.telepizza.pl/menu

Po cookies zostaje na mobilu opadła nawigacja.

Firefox 62.0.1
uBo 1.16.21rc0

listy poaktualizowane.

**Comment by hawkeye116477** [comment]
@krystian3w Może jakiś screen?

**Comment by hawkeye116477** [comment]
@krystian3w Tak, najwyraźniej to jakiś problem po twojej stronie, choć ja sprawdzałem na Yandexie, nie lisie. A może to ten łobuziak @KonoromiHimaries eksperymentował z headerem :smile:.

**Comment by krystian3w** [comment]
A chyba naprawiłem opcją resetu uBo do ustawień domyślnych. Widać nie wolno nadpisywać uBo stable wersją dev.

I `rynekzdrowia.pl` przy okazji już mogę przewijać.

List na statyczne nawigacje i reklamy wewnętrzne nie używam.
