### ISSUE TITLE
heineken.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8848]
cookies

https://heineken.com.pl/age-gate.html

W ramach naszej witryny stosujemy pliki cookies w celu zbierania informacji, które pomagają nam usprawnić obsługę witryny, dostosować nasze reklamy do Twoich preferencji oraz ulepszyć nasze produkty i usługi.
Zgadzając się, akceptujesz zasady dot. prywatności i plików cookies obowiązujące w niniejszej witrynie internetowej. Ustawienia cookies (w tym ich blokadę) możesz zmieniać w ustawieniach Twojej przeglądarki w każdej chwili. Tu znajdziesz szczegółowe informacje o polityce plików cookies i polityce prywatności.

**Comment by hawkeye116477** [comment]
`heineken.com.pl###infobx2`
