### ISSUE TITLE
krs-online.com.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#8850]
### Zrzut ekranu
![screenshot_20180916_203318](https://user-images.githubusercontent.com/19818572/45599658-ce0bc400-b9ef-11e8-9945-6636cf50d6b2.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Antyadblock i reklama wtyczki kontaktowej.
```
@@||krs-online.com.pl/js/showads.js
krs-online.com.pl###cleader

```

**Comment by xxcriticxx** [comment]
@hawkeye116477 a ten telefon po prawej?

**Comment by hawkeye116477** [comment]
@xxcriticxx To jest od tej reklamy.

**Comment by hawkeye116477** [comment]
No nie wiem, zobaczymy co @MajkiIT powie, ale ja tam bym powiedział, że to jest reklama zewnętrzna oprogramowania, więc do głównej listy.

**Comment by xxcriticxx** [comment]
Trzeba podnieść telefon i zgłosić tam @hawkeye116477

**Comment by krystian3w** [comment]
Widać na normalnych reklamach już nie zarabiają.
