### ISSUE TITLE
envelo.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8854]
![opera zdjecie_2018-09-17_041542_www envelo pl](https://user-images.githubusercontent.com/36385327/45604009-5e69f900-ba30-11e8-9c48-0011c072bd78.png)

**Comment by hawkeye116477** [comment]
`envelo.pl##.envelo-facebook, .envelo-twitter, .envelo-gplus, .envelo-in, .envelo-instagram`
