### ISSUE TITLE
Listy w formacie JSON - Safari Content-Blocking

### ISSUE THREAD

**Issue by matt08** [MajkiIT/polish-ads-filter#8858]
Propozycja: Może warto by udostępnić listy także formacie JSON, który używany jest w mechanizmie Content Blocking w Safari na MacOS i iOS.
https://developer.apple.com/library/archive/documentation/Extensions/Conceptual/ContentBlockingRules/Introduction/Introduction.html#//apple_ref/doc/uid/TP40016265-CH1-SW1

Content blockery typu 1Blocker, KA-Block! czy Wipr i inne, pewnie chętnie by z takich list skorzystały.

**Comment by xxcriticxx** [comment]
@matt08 ios ma limit do 50k filtrow nawet polowa easylisty sie nie zaladuje

@MajkiIT co myslisz o tym?

**Comment by matt08** [comment]
@xxcriticxx no niestety. 
1Blocker X obszedł to tworząc kilka list: https://backstage.1blocker.com/say-hello-to-1blocker-x-8b55efe1ae36
Pewnie inni robią podobnie.

**Comment by xxcriticxx** [comment]
@matt08 tak dokladnie adguard to samo planuje https://github.com/AdguardTeam/AdguardForiOS/issues/819

**Comment by hawkeye116477** [comment]
Ten content blocking jest słaby, słabszy niż nawet Adblock/ABP, nie ma `-abp-has/-abp-contains`, więc nie wiem czy się opłaci. Ja bym powiedział, że na Macu to są lepsze alternatywy , na iOS jest AdGuard Content Blocker i nie wiem czy działa tak samo jak ten na Androidzie, jeżeli tak, to listy w json są zbędne.

**Comment by xxcriticxx** [comment]
@hawkeye116477 na ios jest limit 50k w guardzie na wp wiekszosci nie wycina. ver pro ma extra dns blocking host file.

**Comment by hawkeye116477** [comment]
@xxcriticxx Na WP często bywa tak, że potrzebne są reguły rozszerzone, a AdGuard na iOS ich raczej nie posiada. Tak samo nie wiem co z tym wyjątek na gerichide, jak go nie ma, to nie wiem czy warto, bo ludzie też mogą narzekać, że im antyadblock wyskakuje, a wtedy trzeba byłoby odblokować reklamy. 
Na szczęście też nie trzeba samemu robić listy, znalazłem takie coś => `https://github.com/adblockplus/abp2blocklist`, ale pytanie kto to będzie testował czy wszystko ok, ja nie mam Maca ani iOS, @MajkiIT też nie wiem czy ma, chyba jedynie @xxcriticxx.

**Comment by xxcriticxx** [comment]
@hawkeye116477 na macu zamontowalem chrome i ubo dawno z safari zrezygnowalem. problem jest tylko z iphonem. 

mysle ze @matt08 cos by po testowal

**Comment by hawkeye116477** [comment]
Na próbę => [polish_ads.json](https://github.com/MajkiIT/polish-ads-filter/files/2397318/polish_ads.json.txt),
Trzeba usunąć .txt by działało. Pewnie będą jakieś błędy, niby abp-contains dodał do filtrów, ale obawiam się, że pewnie zignoruje cały filtr albo tylko -abp-contains i wtedy za dużo rzeczy schowa. A tam
 gdzie jest dane generichide, to dał wyjątek na całą stronę, też niezbyt dobrze

**Comment by MajkiIT** [comment]
Limity na iOS są ciezkie do ogarnięcia, bo chyba Apple chce reklam. Potestuję to ale WP i inne portale trudno będzie ogarnąć.

**Comment by hawkeye116477** [comment]
A propo Mac OS, wiadomość dla zainteresowanych, jakiś gość w wątku dla uBO pisał, że nadchodzi fork Safari => https://browser.kagi.com/, który obsługuje rozszerzenia z FF i Chrome, z obu sklepów można instalować, ale na razie jest to prywatna beta. Niby ma być też wersja dla iOS.
