### ISSUE TITLE
szczecinek.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8865]
![opera zdjecie_2018-09-21_054715_szczecinek com](https://user-images.githubusercontent.com/36385327/45859313-f550f100-bd61-11e8-925c-dc3f478863ec.png)

**Comment by hawkeye116477** [comment]
@MajkiIT Jeszcze na dole w stopce jest coś o jakiejś reklamie i brakuje jednego linku, nie wiem czy to do odblokowania czy zablokowania, chodzi dokładnie o ten link => `https://szczecinek.com/reklama`.

**Comment by MajkiIT** [comment]
@hawkeye116477 Dziękuję
