### ISSUE TITLE
gazetawroclawska.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8878]
https://gazetawroclawska.pl
https://dziennikbaltycki.pl
https://dzienniklodzki.pl
https://dziennikpolski24.pl
https://dziennikzachodni.pl
https://echodnia.eu
https://expressbydgoski.pl
https://nowiny24.pl
https://gazetakrakowska.pl
https://gazetalubuska.pl
https://pomorska.pl
https://wspolczesna.pl
http://katowice.naszemiasto.pl
https://nto.pl
https://gp24.pl
https://gloswielkopolski.pl
https://gol24.pl
https://kurierlubelski.pl
https://poranny.pl
https://to.com.pl
https://polskatimes.pl
https://strefaagro.pl
![zrzut ekranu z 2018-09-23 23-53-20](https://user-images.githubusercontent.com/36385327/45933485-054d1880-bf8e-11e8-81cf-767af80a2bc2.png)

https://plus.gazetawroclawska.pl
https://plus.to.com.pl
https://naszahistoria.pl
https://plus.nto.pl
https://plus.gp24.pl
https://plus.gloswielkopolski.pl
https://plus.kurierlubelski.pl
https://plus.poranny.pl
https://plus.dziennikbaltycki.pl
https://plus.dzienniklodzki.pl
https://plus.dziennikzachodni.pl
https://plus.echodnia.eu
https://plus.expressbydgoski.pl
https://plus.gazetakrakowska.pl
https://plus.gazetalubuska.pl
https://plus.pomorska.pl
https://plus.wspolczesna.pl
![opera zdjecie_2018-09-24_000830_plus gazetawroclawska pl](https://user-images.githubusercontent.com/36385327/45933491-51985880-bf8e-11e8-917d-737b1f6840d2.png)

**Comment by hawkeye116477** [comment]
@krystian3w Robota jest dla ciebie :smile:.

**Comment by xxcriticxx** [comment]
@hawkeye116477 laughing out loud

**Comment by krystian3w** [comment]
`pl,echodnia.eu##.listaIkon > li > .ikona` wszystkie pod jeden szablon.

**Comment by hawkeye116477** [comment]
Powiedziałbym raczej, że lepiej dać pod konkretne strony, bo ikony mogą być różne.

**Comment by krystian3w** [comment]
OK, to są już domeny zamiast pod wszystkie polskie.

 `###stopka > .linki > .row > div > .listaIkon > li > .ikona` - pewnie przekombinowane.

**Comment by krystian3w** [comment]
@MajkiIT  / @xxcriticxx  - dalej gratka jest.

```
||ppstatic.pl/assets/gratka/*/promoButton.css$stylesheet
gazetawroclawska.pl,dziennikbaltycki.pl,dzienniklodzki.pl,dziennikpolski24.pl,dziennikzachodni.pl,echodnia.eu,expressbydgoski.pl,nowiny24.pl,gazetakrakowska.pl,gazetalubuska.pl,pomorska.pl,wspolczesna.pl,katowice.naszemiasto.pl,nto.pl,gp24.pl,gloswielkopolski.pl,gol24.pl,kurierlubelski.pl,poranny.pl,to.com.pl,polskatimes.pl,strefaagro.pl,nowosci.com.pl##.promoContainer
```

wycinanie CSS raczej opcjonalne - nie ukryje elementu na 100% a jest w szablonie stron.
