### ISSUE TITLE
zus.pl

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#8884]
brak konta po zalogowaniu sie na zus.pl, jest biala strona.

**Comment by krystian3w** [comment]
Filtr statyczny `/cookie.js$domain=pl` znajdujący się w:

  * Polskie Filtry RODO-Ciasteczkowe
  * Polskie Filtry Elementów Irytujących

**Comment by krystian3w** [comment]
`@@/cookie.js$domain=zus.pl`

**Comment by lukjan32** [comment]
aha, jak beda w pliku?

**Comment by krystian3w** [comment]
Są jako jedna, zaktualizuj listę i nie będzie trzeba dodawać.

https://github.com/MajkiIT/polish-ads-filter/blob/a064e0a898e22ed4547b12370f748d4796334e16/cookies_filters/adblock_cookies.txt#L1359
