### ISSUE TITLE
kinonet.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#8892]
showmax 

http://kinonet.pl/filmy-online/Pozycja_obowiazkowa/10411

![capture](https://user-images.githubusercontent.com/15007183/46247268-ebb93000-c3d6-11e8-9cbe-1691893a9c5f.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx Chyba już nie ma

**Comment by xxcriticxx** [comment]
@MajkiIT dokladnie moze jutro sie sie ukaze
