### ISSUE TITLE
senpai.fora.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#8900]
![2018-10-01-forum senpai - www senpai fora pl](https://user-images.githubusercontent.com/5884000/46292824-261afc80-c592-11e8-8ba6-49b305a70e8e.png)

cookie + pusta sekcja

chr latest
ubo latest
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by krystian3w** [comment]
Mam czysto - nawet jak patrzę to Cookiemonster wyłączone.

```
fora.pl##DIV[style="position:relative;display:block;margin:0 auto;visibility:visible;overflow:hidden;font-size:0.8em;color:#232000;background-color:#fcfc9a;-moz-box-shadow:0 2px 4px #bbb;-webkit-box-shadow:0 2px 4px #bbb;-khtml-box-shadow:0 2px 4px #bbb;box-shadow:0 2px 4px #bbb;filter:progid:DXImageTransform.Microsoft.Shadow(color='#969696', Direction=145, Strength=4);"]
```

**Comment by krystian3w** [comment]
`/pp-t-a-c.js$domain=fabrykasily.pl|toplista.pl|domzdrowia.pl|fora.pl|torrent.top-100.pl|dieta.pl
` - ta reguła też powinna wycinać, ma z przynajmniej miesiąc.

ostatecznie się na takie coś może przywróci zakomentowane: `fora.pl##.pp-t-a-c` (wyłączone bo nie znalazłem po tygodniu przykładu gdzie by wycinanie skryptu nie działało).

**Comment by krystian3w** [comment]
Luka z reklamami to jakiś `##.row1`

**Comment by xxcriticxx** [comment]
`##.row1` schowa tylko biale pole po reklamie ale nie podciagnie strony do gory

**Comment by hawkeye116477** [comment]
@xxcriticxx Zamiast tego proponuję `senpai.fora.pl##tr[height="280"]`. A tego RODO też nie mam.

**Comment by xxcriticxx** [comment]
@hawkeye116477 regula jest dobra dzieki

**Comment by hawkeye116477** [comment]
@MajkiIT Luka po reklamie dla ciebie. A tak po za tym, jak już zajmiesz się luką, to można zamykać, gdyż zacytuję Konoromi => `co do tego rodo to trzeba wyłączyć ubo, żeby potem włączyć i wtedy można odświeżyć strone`, a więc ja raczej nic na to nie poradzę, że jak tak się będzie bawić i za drugim razem załaduje skrypt z cache, trzeba po prostu po takiej zabawie wyczyścić pamięć podręczną :smile:.
