### ISSUE TITLE
chceauto.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8905]
![opera zdjecie_2018-10-03_015352_www chceauto pl](https://user-images.githubusercontent.com/36385327/46383206-789e0b00-c6af-11e8-87be-dfb6ffab3478.png)

**Comment by krystian3w** [comment]
`##.rek12` ale za wysoko uniesie, więc raczej stare `##A[target="_blank"] > IMG` zrobi to lepiej :walking_man:.

**Comment by krystian3w** [comment]
@MajkiIT  reguła nie działa przez spacje przed hashami.

https://github.com/MajkiIT/polish-ads-filter/blob/15c67c6b53358835cf1e557eeb7a7154f7d4613b/polish-adblock-filters/adblock.txt#L2128

```
,chceauto.pl ##A[target="_blank"] > IMG
            ^
           /|\
            |
            |
```
