### ISSUE TITLE
prnews.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#8907]
https://prnews.pl/apple-pay-banku-millennium-moze-przyszlosci-437804

```
||request.dqst.pl/$xmlhttprequest
prnews.pl##[id^="sas_"]
prnews.pl##.entry > DIV[id]
```

Zostało jeszcze przysłonięcie obrazu.

**Comment by MajkiIT** [comment]
@krystian3w @hawkeye116477 macie pomysł na to przysłonienie obrazu?

**Comment by MajkiIT** [comment]
Chyba mam. Do testu:
```
||request.dqst.pl/$xmlhttprequest
prnews.pl##[id^="sas_"]
prnews.pl##script:contains(adblock__link)
```

**Comment by krystian3w** [comment]
Jak dla mnie zbyt skompresowanie i po dekompresji nie ogarniam kodu.

**Comment by MajkiIT** [comment]
@hawkeye116477 Nie wiem czy dobrze cię rozumiem. 

To do ogólnej 
```
||request.dqst.pl/$xmlhttprequest
prnews.pl##[id^="sas_"]
```

A do uBo dodać do sekcji !#if cap_html_filtering dodać.
`prnews.pl##^script:has-text(adblock__link)`

**Comment by krystian3w** [comment]
Raczej całość, bo tak to blokujesz tym z Chrome - niech sobie wypełniają n arazie ankietę reklamową / zgadywankę?

**Comment by hawkeye116477** [comment]
@MajkiIT Tak właściwie, to do ogólnej tylko `prnews.pl##[id^="sas_"]`, sieciowa raczej zbędna, zablokowanie jej powoduje antyadblocka i nie można wtedy odpowiedzieć na pytanie, by odblokować artykuł. A to `script:has-text` tak jak mówisz :smile:

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/8908#issuecomment-426900609
