### ISSUE TITLE
weszlo.com

### ISSUE THREAD

**Issue by Jakeeeeeeee** [MajkiIT/polish-ads-filter#8908]
### Zrzut ekranu
![questo](https://user-images.githubusercontent.com/29839335/46436834-34b41000-c75a-11e8-91ed-c5571171d48b.PNG)

### Link bezpośredni
http://weszlo.com/2018/10/03/wart-imponujacy-start-krzysztofa-piatka/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. otworzyc artykul i zjechac nieco w dol strony
2. 
3. 

### Moja konfiguracja
chrome

**Rozszerzenia i skrypty:**

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Polish Privacy Filters
4. Polskie Filtry Elementów Irytujących
5. Polskie Filtry RODO-Ciasteczkowe
**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

"Adquesto - rewolucja w reklamie internetowej. Adquesto jest pierwszą bramką treści bazującą na idei questvertisingu." podobno ma byc nie do obejscia przez adblocki i skrypty, prawda to?

**Comment by MajkiIT** [comment]
@Jakeeeeeeee u mnie tego nie ma, ale zapewne zaraz będzie.

**Comment by Jakeeeeeeee** [comment]
hm serio nie ma? odpalam strone w incognito tylko z ublockiem aktywnym i za kazdym razem wyskakuje ale faktycznie moze to dopiero pierwszy probny artykul bo na starszym nie ma

http://weszlo.com/2018/10/03/wart-imponujacy-start-krzysztofa-piatka/

**Comment by MajkiIT** [comment]
@Jakeeeeeeee 
Na FF 
```
weszlo.com##.center-main > DIV[id]
weszlo.com##script:contains(adblock__link)
```

**Comment by Jakeeeeeeee** [comment]
na weszlo.com faktycznie nie ma, wyedytowalem i podalem link do konkretnego artykulu, mozliwe ze dopiero od teraz bedzie wyskakiwac dopiero gdy sie wejdzie w artykul ale nie na głównej.

**Comment by Jakeeeeeeee** [comment]
![blok](https://user-images.githubusercontent.com/29839335/46439507-1271c080-c761-11e8-9d6a-d8ff38754431.PNG)

hm po updejcie polskie filtry do Adblocka i uBlocka

**Comment by MajkiIT** [comment]
@Jakeeeeeeee a jak dodasz to do moich filtów jest OK ?
`@@||request.dqst.pl/$xmlhttprequest`

**Comment by Jakeeeeeeee** [comment]
bez zmian tu i tu

**Comment by MajkiIT** [comment]
@Jakeeeeeeee 
a jak dodasz to ?
`weszlo.com##.center-main > DIV[id]`

**Comment by Jakeeeeeeee** [comment]
ale gdzie?

**Comment by MajkiIT** [comment]
@Jakeeeeeeee Ok. To super. Poczekajmy na rozwój sytuacji. Na razie nie mam pomysłów, co się dzieje w incoglito.

**Comment by Jakeeeeeeee** [comment]
wszystko smiga, w incognito tez, moze sie filtry nie odswiezaja w biezacej sesji w tym trybie

**Comment by krystian3w** [comment]
Możesz mieć racje, sam też coś miałem, że aktualizacja w Incognito nie zaktualizowała w normalnej sesji mi listy.

**Comment by krystian3w** [comment]
`https://mambiznes.pl/wlasny-biznes/stworzyl-dropboxa-dla-wydarzen-sportowych-na-jego-serwisie-dodano-juz-200-tys-zdjec-87460`, też ma adquesto - w AdGuard już zablokowali skryptem.

**Comment by MajkiIT** [comment]
@krystian3w 
https://github.com/MajkiIT/polish-ads-filter/commit/2cdf9b1abf4e51948421d9e4571b94733fdc4805#diff-ca815c4f5fe404637a9387f434740d25
