### ISSUE TITLE
polsatnews.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8909]
Znowu reklamy w filmikach jak tu https://github.com/MajkiIT/polish-ads-filter/issues/8812.

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. 
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**

**Rozszerzenia i skrypty:**

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by xxcriticxx** [comment]
@kulfoon wypelnij polski formularz please

**Comment by kulfoon** [comment]
@xxcriticxx ja z tych bardziej obeznanych jak wy, więc raczej nie muszę go wypełniać jak wy, ewentualnie jeśli zajdzie taka potrzeba to wtedy...

**Comment by hawkeye116477** [comment]
Najwyraźniej zmienili ścieżkę do skryptu, ale nazwa ta sama.
`||www.polsatnews.pl/templates/pnews2018/build/static/videoPlayer.js`

**Comment by MajkiIT** [comment]
@hawkeye116477 Dziękuję
