### ISSUE TITLE
wpolityce.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8910]
Problem wywodzący się stąd https://github.com/MajkiIT/polish-ads-filter/issues/7805#issuecomment-392887145 - problem występujący przy pierwszym wejściu na stronę (wyczyszczone ciasteczka) jest ona częściowo popsuta np. `https://wpolityce.pl/lifestyle/77536-lincz-za-jedzenie-grzybow` znika scroll, więc nie można przewinąć i przeczytać artykułu, po odświeżeniu strony  i przy kolejnych wejściach scroll już się pojawia. Problem znika po wyłączeniu filtrów `Polskie Filtry RODO-Ciasteczkowe` a dokładniej tego filtru `wpolityce.pl##.rhododendron-popup, .rhododendron-popup-overlay`.

Edytowane: 

> @kulfoon: przy kolejnych wejściach scroll już się pojawia.

Dziwna sprawa, teraz mam tak, że za każdym razem scrolla nie ma...

**Comment by xxcriticxx** [comment]
@kulfoon wypelnij formularz

**Comment by krystian3w** [comment]
Na moje oko wywalili plik `/rhododendron/css/rhododendron-popup.css`

**Comment by kulfoon** [comment]
> @krystian3w : Na moje oko wywalili plik `/rhododendron/css/rhododendron-popup.css`

Albo nie tyle co wywalili, a zmienili nazwę na losową i trudniejszą do wyłapania:

`https://static.wpolityce.pl/snippy/4e5c282583d774e12f217b9112de791a.css`

Zablokowanie tego, czyli np.
`||static.wpolityce.pl/snippy/4e5c282583d774e12f217b9112de791a.css$stylesheet,~third-party` 
skutkuje tym samym co zablokowanie niegdyś  `/rhododendron/css/rhododendron-popup.css`, czyli scroll działa. Tyle że tam są 3 takie style css o losowej podobnej do siebie nazwie:

```
https://static.wpolityce.pl/snippy/4e5c282583d774e12f217b9112de791a.css
https://static.wpolityce.pl/snippy/bdb29ffa0e59bc6f0a2d15d7c5153b16.css
https://static.wpolityce.pl/snippy/5fac257be664af934635040608d22558.css
```

Więc bez zajrzenia do środka każdego z nich nie za bardzo filtr ma wiedzieć który to który, a dodatkowo  nazwy mogą co jakiś czas zmieniać się i mutować przy kolejnych wizytach. W skrócie - poszli na wojnę z nami i się wycwanili, więc jeśli nie uda się nic wymyślić, to być może za pomocą filtra uBO style:() da się coś na sztywno ustawić i nadpisaćto co jest w tym pliku css i przywrócić ten scroll.

**Comment by krystian3w** [comment]
Wiem, dlatego reguła jest tylko na wersji dev (najpewniej nie trafi do wydania RTM).

Jak będą się więcej bawić nazwą, to lepiej tak jak piszesz, przywracać przewijanie tylko dla uBlock Origin i AdGuard CSS-em (`:style(...)`), pomocniczo filtrowaniem html jak odblokuje przewijanie (musi być co wyciąć i skrypt "głupieć" i przerywać działanie).

`,~third-party` - wątpię by gdzieś dzielili się swoją ścieżką do CSS (więc nawet wykasowałem domyślne `first-party` i `stylesheet`).

**Comment by hawkeye116477** [comment]
Najwyraźniej coś zmienili. Skoro jest losowa nazwa, to raczej taka zabawa się nie opłaci, damy reguły tylko dla uBO i AG :smile:.

**Comment by krystian3w** [comment]
W sumie plik  od miesiąca nie zmienił nazwy.
