### ISSUE TITLE
zdajmyrazem.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8914]
rodo/cookies/polityka

![zdajmyrazem pl](https://user-images.githubusercontent.com/43844449/46523939-91611900-c887-11e8-9965-dff872422be0.png)

**Comment by krystian3w** [comment]
kosmetycznie w uBlock Origin / Adguard - nie udało mi się robić skryptowej reguły ani nie widzę sensu wycinać `<script>` z aktywatorem w jQuery.

**Comment by hawkeye116477** [comment]
Dla FF wystarczy tylko `zdajmyrazem.pl##^#gdprModal` :smile:.

**Comment by kulfoon** [comment]
Albo taka propozycja na wszystkie przeglądarki: `zdajmyrazem.pl##+js(abort-on-property-read.js, showRodo)`

A przy okazji dopiero zauważyłem napis/resztkę po reklamie:

![impr](https://user-images.githubusercontent.com/43844449/46569868-b7f08400-c95b-11e8-8721-c1ef6957d04f.png)

**Comment by krystian3w** [comment]
miałem pop-upy fail.

**Comment by kulfoon** [comment]
@hawkeye116477 zrobił najlepiej, czyli zwykłe filtry kosmetyczne + przywrócenie scrolla, mi z głowy wyleciało jak się przywraca scrolla, teraz już sobie przypomniałem.

Tak już ciekawości tylko, @krystian3w u mnie popupów fail nie widziałem (bez zalogowania), czy miałeś je będąc zalogowanym, czy nie? Jakie kroki żeby je wywołać? A jeśli zamiast tamtego dasz te 2:
```
zdajmyrazem.pl##+js(abort-on-property-read.js, showGdprInfo)
zdajmyrazem.pl##+js(abort-on-property-read.js, showGdprAdv)
```
to dalej masz te popupy fail?

**Comment by kulfoon** [comment]
@krystian3w czy ty ignorujesz mó komentarz wyżej czy go omyłkowo przegapiłeś / zapomniałeś o nim? Bo czekam na odpowiedź i się nie mogę doczekać...

**Comment by krystian3w** [comment]
Problem był, że zostawiłem sobie liniowe ubijanie skryptu, a tam trzeba najczęściej dwóch przełączników (lub po prostu na część nie zadziała).

Niestety zacząłem od `abort-current-inline-script.js`  i potem po zmianach głupiało pewnie przez cache.
