### ISSUE TITLE
forsal.pl

### ISSUE THREAD

**Issue by Matgoeth** [MajkiIT/polish-ads-filter#8922]
### Zrzut ekranu
https://imgur.com/a/U8PejVk

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na stronę
2. Poczekać moment aż załaduje się skrypt (tekst jest widoczny od razu ale po sekundzie-dwóch znika za reklamą)
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**
Chromium 66.x
**Rozszerzenia i skrypty:**
uBlock
**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. AAK-Cont Filter For uBlock Origin
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

**Comment by krystian3w** [comment]
`forsal.pl##:script-inject(abort-current-inline-script.js, parseInt, adblock)` - awaryjne.

upewnij się, że masz właściwy uBlock Origin: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=pl

 

> ![image](https://github.com/gorhill/uBlock/blob/master/src/img/icon_128.png?raw=true) |
> ---|

W tym rzadko aktualizowanym od  `chris aljoudi` / `uBlockAdmin / uBlock-LLC` nie zadziała reguła.

**Comment by krystian3w** [comment]
`forsal.pl##script:inject(abort-current-inline-script.js, parseInt, adblock)` - awaryjne.

upewnij się, że masz właściwy uBlock Origin: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=pl

 

> ![image](https://github.com/gorhill/uBlock/blob/master/src/img/icon_128.png?raw=true) |
> ---|

W tym rzadko aktualizowanym od  `chris aljoudi` / `uBlockAdmin / uBlock-LLC` nie zadziała reguła.

---

U mnie nie wyskakuje w artykule: `http://forsal.pl/swiat/aktualnosci/artykuly/1284828,rewolucja-kapitalistyczna-mozliwa-takze-w-korei-polnocnej.html`

![image](https://user-images.githubusercontent.com/35370833/46535521-ef9ff300-c8ab-11e8-89ea-fc0f00234ccc.png)

**Comment by krystian3w** [comment]
`forsal.pl##script:inject(abort-current-inline-script.js, parseInt, adblock)` - awaryjne.

upewnij się, że masz właściwy uBlock Origin: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=pl

 

> ![image](https://github.com/gorhill/uBlock/blob/master/src/img/icon_128.png?raw=true) |
> ---|

W tym rzadko aktualizowanym od  `chris aljoudi` / `uBlockAdmin / uBlock-LLC` nie zadziała reguła.

---

U mnie nie wyskakuje w artykule: `http://forsal.pl/swiat/aktualnosci/artykuly/1284828,rewolucja-kapitalistyczna-mozliwa-takze-w-korei-polnocnej.html`

> ![image](https://user-images.githubusercontent.com/35370833/46535521-ef9ff300-c8ab-11e8-89ea-fc0f00234ccc.png) |
> --- |

Działają widać proste reguły sieciowe i kosmetyczne.

**Comment by Matgoeth** [comment]
> U mnie nie wyskakuje w artykule: `http://forsal.pl/swiat/aktualnosci/artykuly/1284828,rewolucja-kapitalistyczna-mozliwa-takze-w-korei-polnocnej.html`

Potwierdzam, choć od wczoraj była zarówno na tych jak i innych artykułach. Tak czy inaczej dzięki za odzew @krystian3w !

**Comment by MajkiIT** [comment]
PUSTO
