### ISSUE TITLE
chorzowianin.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8929]
napis/resztka po reklamie

![ss1](https://user-images.githubusercontent.com/43844449/46570478-238b1f00-c965-11e8-83c8-44f55ca74a95.png)

**Comment by krystian3w** [comment]
Socialu nie ma - chyba on nie wycina.

> ![obraz](https://user-images.githubusercontent.com/35370833/46573192-d70a0880-c991-11e8-950b-81586482a888.png) |
> --- |

**Comment by krystian3w** [comment]
`###subpage_left`

`##span.left_header:nth-of-type(1), span.left_header:nth-of-type(2)`

❓
