### ISSUE TITLE
bibliotekarium.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8938]
reklama wewn.? (w każdym bądź razie jest napis reklama)

![ss1](https://user-images.githubusercontent.com/43844449/46583425-45fd6500-ca57-11e8-8b86-8dfa23304838.png)

**Comment by krystian3w** [comment]
Sociala nie ma, zgłaszający nie wycina:

> ![obraz](https://user-images.githubusercontent.com/35370833/46584911-aa292480-ca69-11e8-9881-4f7959807d41.png)
