### ISSUE TITLE
filtr ##.step1

### ISSUE THREAD

**Issue by konradkg** [MajkiIT/polish-ads-filter#894]
Taki filtr jak ##.step1 to trochę nie porozumienie, albo zbyt ogólna reguła. Wycina wiele stron gdzie są zrobione wizzardy, konfiguratory itp., a klasa CSS zakładek to step1, step2, step3 itp. Jest chyba jakis js który domyślnie tak je nazywa.

**Comment by MajkiIT** [comment]
Dzięki za info. Poprawione.
