### ISSUE TITLE
infobowling.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8941]
2 x puste kontenery / napisy / resztki po reklamach wewn.

1
![ss1](https://user-images.githubusercontent.com/43844449/46583560-7e9e3e00-ca59-11e8-80ca-86c819db0ed6.png)

2
![ss2](https://user-images.githubusercontent.com/43844449/46583561-7fcf6b00-ca59-11e8-9ae5-837d64c8a698.png)

**Comment by krystian3w** [comment]
`###fb-side-like`
