### ISSUE TITLE
exerim.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8942]
pusty kontener / resztka po jakiejś reklamie (po prawej)

![ss1](https://user-images.githubusercontent.com/43844449/46583602-e3f22f00-ca59-11e8-9bfb-ecb338190825.png)

**Comment by krystian3w** [comment]
cookies statyczne, wkomponowane w stopkę - takiego mam nie ruszać.

`##.socialSubscribe, #sidebar > article:nth-of-type(2) > h3`  - resztki (dwa buttony z 6 i nagłówek.
