### ISSUE TITLE
zpleszewa.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8944]
napisy / resztki po reklamach rozsiane po całej stronie w losowych miejsach  (na głównej i podstronach też)

1
![ss1](https://user-images.githubusercontent.com/43844449/46583994-6c72ce80-ca5e-11e8-9076-11b6a8dba311.png)

2
![ss2](https://user-images.githubusercontent.com/43844449/46584006-9af0a980-ca5e-11e8-870c-56a514de9109.png)

3
![ss3](https://user-images.githubusercontent.com/43844449/46584008-9f1cc700-ca5e-11e8-8b0a-3bd929da70a5.png)

4
![ss4](https://user-images.githubusercontent.com/43844449/46584011-b360c400-ca5e-11e8-8307-b7b295583923.png)

**Comment by krystian3w** [comment]
`##div > .txt`

ale do sprawdzenia czemu cały blog z wpisem koloruje uBO a wycina sam napis reklama.
