### ISSUE TITLE
okazik.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8945]
jakaś resztka / overlay / tło po czymś zakrywające całą stronę

![ss1](https://user-images.githubusercontent.com/43844449/46584096-8e208580-ca5f-11e8-95e4-7efb9f47c6d1.png)

**Comment by krystian3w** [comment]
Po rodo...

**Comment by krystian3w** [comment]
`[id*="cookie-"]` - wycięło za dużo i z braku przewijania poleci do kolejnych wyjątków po domenie.

**Comment by kulfoon** [comment]
```
~okazik.pl,~linuxiarz.pl,~piekarniaanka.pl,~xboxarcade.pl,~appki.com.pl,~mvno-gsm.pl,pl##[id*="cookie-"]
~okazik.pl,~piekarniaanka.pl,~xboxarcade.pl,~wmeritum.pl,~zumi.pl,~komunikacja.bialystok.pl,~dobreprogramy.pl,~lomza.pl,pl##:not(input)[id*="cookie"]
okazik.pl##.mfp-ready
okazik.pl##html:style(overflow: auto !important;)
```

**Comment by kulfoon** [comment]
> @krystian3w `.mfp-ready` u mnie było za wolne,

U mnie też jest wolne, miga ten cookies komunikat na moment, przy klikaniu na przyciski w menu, html filtering wiadomo szybszy, więc nic nie miga, też można dodać dodatkowo, nie zaprzeczam, to przynajmniej na FF będzie szybszy filtr i nic nie będzie migało.

**Comment by krystian3w** [comment]
> EDIT 2: W sumie nie trzeba dodawać żadnych wyjątków, wystarczy dodać to:

To wyjątki pod prehistorię, nic mi nie wiadomo by MajkiIT porzucał jakiekowliek wsparcie dla AdBlock / Adblock Plus.

Tym musimy wyświetlić komunikat, by sobie zamknęli i mogli użyć strony - ich wybór, jak strona straci odsłony to też po części wina webmasterów i już nie tylko upartości fanboyów AdBlock / Adblock Plus.

**Comment by kulfoon** [comment]
No racja z tymi wyjątkami, zapomniałem o tym dinozaurze ABP.
