### ISSUE TITLE
wiescirolnicze.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8950]
cookies / rodo / polityka

![ss1](https://user-images.githubusercontent.com/43844449/46584231-fde34000-ca60-11e8-886d-4b0f61f5bdab.png)

**Comment by krystian3w** [comment]
OMG - mam czysto. Aż sprawdzę potem w Operze / Chrome.

**Comment by krystian3w** [comment]
> Filtr statyczny `wiescirolnicze.pl###popup_newsletter` znajdujący się w:
> 
>  *   Polskie Filtry Elementów Irytujących - Wyskakujące Okienka

Poszli na największą łatwiznę...
