### ISSUE TITLE
pryzmat.com.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8951]
cookies / polityka

![ss1](https://user-images.githubusercontent.com/43844449/46584240-24a17680-ca61-11e8-944b-2f9ae578995f.png)

**Comment by krystian3w** [comment]
`||www.pryzmat.com.pl/wp-content/plugins/popup-builder/javascript/jquery.sgcolorbox-min.js`

pewnie jak reszta, do niczego innego użyte?
