### ISSUE TITLE
zinfo.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8954]
rodo komunikat

![ss1](https://user-images.githubusercontent.com/43844449/46584513-9929e480-ca64-11e8-8a14-51bd76109e89.png)

**Comment by krystian3w** [comment]
I resztka po reklamie:

```
##.mb10.mt10.container
```

> ![obraz](https://user-images.githubusercontent.com/35370833/46585400-b4025600-ca70-11e8-9ccf-9949f07235dd.png)
