### ISSUE TITLE
pornohd.pl NFSW

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8955]
Cała strona się nie ładuje:

![ss1](https://user-images.githubusercontent.com/43844449/46584661-405b4b80-ca66-11e8-93ff-4d6dd310347c.png)

 przez filtr: 

`~przegladsportowy.pl,~playpuls.pl,~fakt.pl,~forbes.pl,~auto-swiat.pl,~noizz.pl,~plejada.pl,~businessinsider.com.pl,~komputerswiat.pl,~onet.pl,~vod.pl,~gry-online.pl,~tv6.com.pl,~trojmiasto.pl,~otomoto.pl,~dziennikwschodni.pl,~obalamyglupote.pl,pl##[class$="-ads"]`

dodanie wykluczenia domeny `~pornohd.pl`  do filtra naprawia ten problem.

**Comment by krystian3w** [comment]
Wywal grafikę, tylko rozciąga post.
