### ISSUE TITLE
tvnturbo.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8957]
https://www.tvnturbo.pl/programy/pomoc-drogowa-24h,14657.html
![opera zdjecie_2018-10-07_192855_www tvnturbo pl](https://user-images.githubusercontent.com/36385327/46584743-3f76e980-ca67-11e8-914a-afcc039fdd8c.png)

**Comment by krystian3w** [comment]
OK, chyba muszę poprawić, bo ostatnio odblokowywałem przycisk komentarzy na tvn.

```
##.facebook_share, .gplus_share, .twitter_share
```

Sprawdź działanie w Operze z Nano Adblockerem.

**Comment by krystian3w** [comment]
Dziwne,  `##.socialFeedbackFooter` miało wycinać.

Nie kopiuj proszę z maili jak masz aktywne na nich powiadomienia.

---

Wrzucę sobie na chwilę Nano Adblocker i zobaczę teraz - najwyżej się dorobi reguły CSS awaryjne.

**Comment by krystian3w** [comment]
[Dev adblock_social_list.txt](https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/master/adblock_social_filters/adblock_social_list.txt&title=Polskie%20Filtry%20Społecznościowe%20Dev) - tylko pamiętaj o usunięciu po zobaczeniu czy wtedy ruszy i będzie bez przycisków i wróci ikona komentarzy:

> ![image](https://user-images.githubusercontent.com/35370833/46602490-a68cb080-caf0-11e8-9b6b-d3dba448d409.png) |
> --- |

> ![image](https://user-images.githubusercontent.com/35370833/46602510-b5736300-caf0-11e8-9f0f-660cdb02d2a9.png) |
> --- |

**Comment by xMaap** [comment]
```
https://19plus.tvn.pl/aktualnosci,3325,n/jak-walczyc-o-swoje-marzenia,268208.html
https://amerykaexpress.tvn.pl/wideo,3303,v/uczestnicy-ameryka-express-porzuceni-na-wysypisku-smieci,1778371.html
https://amerykaexpress.tvn.pl/wideo,3303,v/uczestnicy-ameryka-express-porzuceni-na-wysypisku-smieci,1778371.html
https://kuchennerewolucje.tvn.pl/wideo,847,v/skwierczacy-tluszcz-gyrosa-i-marokanska-herbata-bez-swiezej-miety,1776970.html
https://masterchef.tvn.pl/uczestnicy,1614,p/bartek-kazimierczak,3857.html
https://szkola.tvn.pl/aktualnosci,2735,n/zycie-w-szkole-nigdy-nie-jest-nudne,268266.html
https://topmodel.tvn.pl/wideo,2100,v/zwiastun-6-odcinka-top-model,1777614.html
https://ukrytaprawda.tvn.pl/aktualnosci,774,n/co-w-nowym-sezonie-ukrytej-prawdy,175347.html
https://szpital.tvn.pl/aktualnosci,2029,n/szpital-tu-liczy-sie-kazda-minuta,268268.html
https://cozatydzien.tvn.pl/wideo,1227,v/antonio-banderas-o-wyrafinowanych-zapachach-ktore-tworzy,1768973.html
https://drzewomarzen.tvn.pl/aktualnosci,3488,n/5-odcinek-drzewa-marzen-za-nami-zobaczcie-najlepsze-momenty,275631.html
https://kuba.tvn.pl/aktualnosci,836,n/michal-szpak-i-sebastian-fabijanski-najlepsze-momenty-odcinka,275262.html
https://www.tvn.pl/programy/mam-talent,19,pc/aktualnosci,3607/karolina-szkiladz-spiewa-swoja-piosenke-w-mam-talent,275501,n.html
https://milionerzy.tvn.pl/aktualnosci,3387,n/ty-tez-mozesz-zostac-milionerem,275310.html
https://zdrowie.tvn.pl/a/fakty-i-mity-na-temat-zapalenia-pecherza-moczowego
https://www.tvn.pl/programy/mam-talent,19,pc
```

Później jak znajdę czas to znajdę więcej i wrzucę.
W zdrowie.tvn.pl jest jeszcze reklama.

**Comment by krystian3w** [comment]
To jak są w większości pod jeden kanon, to najprościej będzie skrócić w regułach kosmetycznych do `tvn.pl` - na tę chwilę tylko `tvnturbo.pl` to osobna domena a nie podpięta jako "subdomena".

----

### reklama na tvn.zdrowie.pl:

@MajkiIT  ja mam tylko takie coś:
```
zdrowie.tvn.pl##section.entry_section-3.sponsored_section:nth-of-type(5) > .entry_section-3__label
```

> ![obraz](https://user-images.githubusercontent.com/35370833/46627283-3efb5300-cb3a-11e8-976e-ebb053a09ba1.png)
