### ISSUE TITLE
tvgorzow.pl (2)

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8958]
@MajkiIT Reopen https://github.com/MajkiIT/polish-ads-filter/issues/8939, bo jedna reklama (ta na dole po prawej) została zlikwidowana za pomocą `###text-6`, ale nadal ta druga (na dole po lewej) nie. Zdaje się, że pomyłkę masz jakąś bo dla tej niezlikwidowanej dałeś: `24legnica.pl,bieganieuskrzydla.pl,aletorcik.pl,tvgorzow.pl##text-5`, czyli `##text-5`  a reklama żeby zniknęła musi być  `###text-5` czyli chyba zjedzony jeden dodatkowy podwójny krzyżyk.

**Comment by krystian3w** [comment]
Cała reguła jest popsuta, tam powinny być 3 hasze. Żadna strona nie genruje tagu html:

```
<text-5>
jestem reklamą w niestandardowym tagu text-5
</text-5>
```

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/46587529-1c136500-ca8e-11e8-9548-e825ac55d2c9.png) |
---- |
