### ISSUE TITLE
zpleszewa.pl (2)

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8959]
@MajkiIT reopen https://github.com/MajkiIT/polish-ads-filter/issues/8944 bo dalej są te napisy, bo dałeś omyłkowo do `warsztat.pl,lakiernictwo.net,zpleszewa.pl##[class*="baner"]` a te napisy mają klasę `txt` a nie `baner`.

**Comment by krystian3w** [comment]
Wycięło te z góry i prawej kolumny.

Pewnie z lewej zostawił, bo uBo koloruje cały opis a wycina tylko sam `span`.

**Comment by kulfoon** [comment]
Nie wiem co u ciebie zostało a co nie, ale u mnie zostały na głównej 3:

<details> 
<summary> (a) u góry</summary>

![ss1](https://user-images.githubusercontent.com/43844449/46593840-61a45200-cacf-11e8-908a-9329fce98ec5.png)

</details>

<details> 
<summary> (b) po środku</summary>

![ss2](https://user-images.githubusercontent.com/43844449/46593959-4d148980-cad0-11e8-896b-cd10ff83fe59.png)

</details>

<details>
<summary> (c) na dole </summary>

(![ss3](https://user-images.githubusercontent.com/43844449/46593842-623ce880-cacf-11e8-81bb-3744d3a5f9ee.png))

</details>

.
i w przykładowym  artykule 4 ( http://www.zpleszewa.pl/galerie/piatka-dobrzyca,17787/544117 ):

<details> 
<summary> (d) u góry: 1 po lewej + 1 po środku</summary>

![ss4](https://user-images.githubusercontent.com/43844449/46594211-ceb8e700-cad1-11e8-98fa-9a4500b94726.png)

</details>

<details>
<summary> (e) na dole: 1 po lewej + 1 po prawej</summary>

![ss5](https://user-images.githubusercontent.com/43844449/46594214-d6788b80-cad1-11e8-9c09-376ca74ef0ec.png)

</details>

A po dodaniu `zpleszewa.pl.txt` wszystkie ładnie znikają, i nic nie jest omyłkowo wycinane po drodze, a to podświetlenie w uBO całych opisów to może jakiś bug w uBO do zgłoszenia, który w praktyce nie wpływa na końcowy efekt filtra. Oczywiście może być tak, że bug ten polega na tym, że jest odwrotnie, czyli że filtr nie wycina tego co podświetla a powinien, i wtedy po naprawienu tego błędu w uBO, mogłby by poznikać opisy przy tym `.txt.`

**Comment by krystian3w** [comment]
> podświetlenie w uBO całych opisów to może jakiś bug w uBO do zgłoszenia, który w praktyce nie wpływa na końcowy efekt filtra

<ul>

Strona ma jakiś "zepsuty" CSS / HTML:

`zpleszewa.pl##div > .txt:style(background: red !important; color: white !important;)`

![image](https://user-images.githubusercontent.com/35370833/46594510-e1ccb680-cad3-11e8-8195-d5af6bd2f82d.png) | ![image](https://user-images.githubusercontent.com/35370833/46594524-f8730d80-cad3-11e8-9f25-43dd0df65195.png)
--- | --- 

Zabrakło im np. `clear: both;`, widać "cud", że reklamy nie są pod tekstami.

</ul>
