### ISSUE TITLE
alemeksyk.eu

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#8960]
### Zrzut ekranu

> ![image](https://user-images.githubusercontent.com/35370833/46593965-57368800-cad0-11e8-81b2-42a4b4a1d10d.png) |
> --- |

### Link bezpośredni

`https://www.alemeksyk.eu/smaki-swiata/item/539-rozgrzewajacy-grzaniec-z-herbaty-na-chlodne-wieczory.html`

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1.  wejść na stronę
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:** Opera 56

**Rozszerzenia i skrypty:** uBo 1.17.0

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Polskie ciasteczkowe
4. Polskie społecznościowe

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**

###### Resztka po reklamach:

`##.advertisement.box > .box-wrap > .header`

###### Uwaga:

sam `##.advertisement` chyba wycina za dużo.

**Comment by kulfoon** [comment]
Tam jest jeszcze druga taka sam resztka na dole:

![ss1](https://user-images.githubusercontent.com/43844449/46595325-1f334300-cad8-11e8-8cb1-1356c5cff5fb.png)

**Comment by krystian3w** [comment]
`##.advertisement.box > .box-wrap > .header`
