### ISSUE TITLE
slawomirambroziak.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8963]
rodo / polityka

![ss1](https://user-images.githubusercontent.com/43844449/46598899-0fbaf680-cae6-11e8-9b04-be37ad298d65.png)

**Comment by krystian3w** [comment]
`##.privacy_policy`

`##li > a[href="https://www.facebook.com/pages/slawomirambroziakpl/114501685327245"]` - to nie przyblokowane

---

`##[href="https://slawomirambroziak.pl/feed/"]` - RSS
