### ISSUE TITLE
allegro.pl

### ISSUE THREAD

**Issue by wooles** [MajkiIT/polish-ads-filter#8965]
https://allegro.pl/

Po wejściu na stronę główną, lub jakąkolwiek podstronę, jesteśmy witani oknem z RODO.

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Polish Privacy Filters​​​​​
4. Polskie Filtry Elementów Irytujących​​​​​
5. Polskie Filtry RODO-Ciasteczkowe​​​​​
6. Polskie Filtry Społecznościowe

![eoddrse 1](https://user-images.githubusercontent.com/9068595/46599408-98866200-cae7-11e8-935b-cc2cbae41b7e.png)

**Comment by krystian3w** [comment]
Ja nie mam, jakiś nowszy Layout masz niż zwykle?

> ![image](https://user-images.githubusercontent.com/35370833/46603231-cb822300-caf2-11e8-98d4-827f9e8b7504.png) |
>--- |

###### stare:

`allegro.pl##div[data-box-name="allegro.rodoConsentModal"]`
`||assets.allegrostatic.com/opbox-rodo-consent-modal/index*.css`

Przy pliku CSS możesz sprawdzić czy jak masz AdBlock / Adblock Plus czy może pomaga dopisanie:

*`||assets.allegrostatic.com/opbox-rodo-consent-modal/index*.css$stylesheet`

* `||assets.allegrostatic.com/opbox-rodo-consent-modal/index*.css$stylesheet,domain=allegro.pl`

**Comment by kulfoon** [comment]
Też tego nie mam.

**Comment by krystian3w** [comment]
Sprawdź w trybie Incognito @kulfoon.

**Comment by kulfoon** [comment]
@wooles 

- na pierwszym zrzucie ekranu zamiast uBO masz włączonego wbudowanego w Operę adblockera...

- na drugim zrzucie masz uBO, więc w tym sensie jest ok, ale coś jest nie tak bo masz zbyt dużą ilość zablokowanych żądań 30, u mnie jest tylko 8, więc nie wiem o co kaman:

![ss1](https://user-images.githubusercontent.com/43844449/46605622-734f1f00-cafa-11e8-961a-133c8da28289.png)

**Comment by krystian3w** [comment]
Jakiś błąd dla Chromowatych, nie już skryptu jako osobny plik to nie mam jak ubić. W ogóle nie mogę odpalić potem ":zap:"  ani "![image](https://user-images.githubusercontent.com/35370833/46605819-0daf6280-cafb-11e8-9a4e-8d49133f4305.png)", spod menu też nie mam "zablokuj element".

----

Po części dobre, że drugie odświeżenie i już nie ma.

---

Raczej to nie jest limitacja userCSS - ale sięgnę po AdBlock / Adblock Plus by wiedzieć jak one sobie radzą.

**Comment by wooles** [comment]
Problem rozwiązuje włączenie filtrowanie kosmetycznego, problemem jest tylko to, że wtedy allegro wygląda mniej więcej tak (wycięte są wszystkie oferty ze strony głównej)
![9ixkghs 1](https://user-images.githubusercontent.com/9068595/46611289-ac44bf00-cb0d-11e8-9107-239d41b1e3b1.png)

**Comment by krystian3w** [comment]
A to dziwne:

> ![image](https://user-images.githubusercontent.com/35370833/46612547-288cd180-cb11-11e8-8767-bdf4287b0ac8.png)  |
> --- |

 i mnie tak mocno nie wycina.

**Comment by kulfoon** [comment]
Mi też nie wycina.

@wolees filtrowanie kosmetyczne jest domyślnie włączone w uBO, więc musiałeś zmodyfikować domyslne ustawienia uBO i je (filtrowanie kosmetyczne) wcześniej ręcznie wyłączyć (co w praktyce oznacza wyłączenie połowy filtrów), a potem się dziwisz, że ci coś (rodo) wyskakuje, więc jeden problem (rodo) sam stworzyłeś i rozwiązałeś, a teraz masz drugi, czyli że ci coś wycina, który prawdopodobnie również sam stworzyłeś bo nam nic nie wycina. Wypełnij formularz proszę i użyj w uBO w zakładce ustawienia przycisku "Przywróć ustawienia domyślne" a potem sobie swoje listy pozaznaczaj i daj znać.

**Comment by krystian3w** [comment]
Albo wyeksportuj ustawienia, wrzucę potem w Operę Beta lub DEV.

**Comment by kulfoon** [comment]
@wooles 

Jeszcze jedno, to NIE jest błąd na Allblock że wycina te oferty z Allegro, ona robi to celowo, bo po to została stworzona,  np. na głównej stronie Allegro jest natłok natrętnych ofert promowanych, które tylko spamują, zajmują miejsce i zamulają przeglądarkę, dlatego zostały wycięte, czyli jakby są zbędne, natomiast normalne oferty nie są powycinane, o to się nie bój. No chyba, że interesują cię i korzystasz z tych ofert promocyjnych, które spamują ci główną stronę Allegro, w końcu niektórzy korzystają z promocji.
