### ISSUE TITLE
prawnik-rodzinny.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8968]
cookies / rodo / polityka

![ss1](https://user-images.githubusercontent.com/43844449/46600685-3f203200-caeb-11e8-8f4e-306c0fde7a78.png)

**Comment by krystian3w** [comment]
```
prawnik-rodzinny.pl###modalBackdrop
prawnik-rodzinny.pl###formalAgreementModal
```
