### ISSUE TITLE
lubiegrac.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8972]
rodo / polityka / cookies na cały ekran...

![ss1](https://user-images.githubusercontent.com/43844449/46601955-1ac65480-caef-11e8-89f2-b4ae2b3456cc.png)

**Comment by krystian3w** [comment]
`||lubiegrac.pl/api/Agreements/AgreementsCheck?RodoCookie=$xmlhttprequest`
