### ISSUE TITLE
forumdermatologiczne.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8975]
polityka / rodo / cookies

![ss1](https://user-images.githubusercontent.com/43844449/46603611-d7bab000-caf3-11e8-8a6e-a650be42fe69.png)

**Comment by krystian3w** [comment]
`forumdermatologiczne.pl##.ui-widget-overlay, .ui-widget-content.ui-widget.ui-dialog`
