### ISSUE TITLE
aptekarzpolski.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8979]
polityka / rodo / cookies

![ss1](https://user-images.githubusercontent.com/43844449/46606553-df7f5200-cafd-11e8-96e8-6331b7110444.png)

**Comment by krystian3w** [comment]
```
||www.aptekarzpolski.pl/wp-content/plugins/popup-builderPro/style/sgcolorbox/colorbox4.css
aptekarzpolski.pl###sgcolorbox.colorbox4
```

CSS opcjonalny - taka lekka oszczędność transferu przy pierwszych odwiedzinach.
