### ISSUE TITLE
telepizza.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#898]
Jedna z reguł z filtrów ciasteczkowych ukrywa prawidłową część strony - http://www.telepizza.pl/
`##div[class*="cookie"]`

![image](https://cloud.githubusercontent.com/assets/11742596/15327987/ac0dade6-1c53-11e6-9d30-a7d09dfa0ec4.png)

![image](https://cloud.githubusercontent.com/assets/11742596/15328052/e229718a-1c53-11e6-849a-87a0b8d507ea.png)

To powinno pomóc `telepizza.pl#@#div[class*="cookie"]`

**Comment by MajkiIT** [comment]
Dziękuję.
