### ISSUE TITLE
opiniodajnia.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#8982]
cookies / polityka / rodo

![ss1](https://user-images.githubusercontent.com/43844449/46606777-c7f49900-cafe-11e8-851d-d56b638d7fbc.png)

**Comment by krystian3w** [comment]
```
opiniodajnia.pl###eu-consent
opiniodajnia.pl##body:style(overflow: auto !important;)
```

Brak opcji html filteringu raczej, nie namierzam reguły skryptowej.
