### ISSUE TITLE
gwiazdy.wp.pl

### ISSUE THREAD

**Issue by salionPL** [MajkiIT/polish-ads-filter#8985]
### Nie wyświetla się wideo z facebooka (na którym śpiewa Zenek).

Adres strony: https://gwiazdy.wp.pl/zenek-martyniuk-z-zona-spiewaja-na-weselu-syna-mamy-wideo-6303751126132353a

**Moja konfiguracja:**

Windows 10 [64bit]
Firefox 62.0.3 [64bit]
uBlock Origin 1.17.0

**Moje listy filtrów:**
<details>

![filtry](https://user-images.githubusercontent.com/38588787/46001848-b3e77b00-c0ac-11e8-8bea-8d49d88b01ba.png)
</details>

**Comment by kulfoon** [comment]
Następny po https://github.com/MajkiIT/polish-ads-filter/issues/8965#issuecomment-427853145, tamtemu Alleblock wycinało, temu wycina Fanboy’s Anti-Thirdparty Social (see warning inside list).

Propnuję zmienić https://github.com/MajkiIT/polish-ads-filter/blob/master/CONTRIBUTING.md 

I do sekcji:

> 
> Przed zgłoszeniem
> 
>     Sprawdź otwarte zgłoszenia
> 
>     Sprawdź czy masz zainstalowane wymagane do działania listy filtrów

Dodać coś takiego:

>    `Sprawdź czy problem nie jest spowodowany zmienionymi ustawieniami w twoim adblockerze (np. zrestetuj / przywróć ustawienia domyślne) lub innymi / zagranicznymi listami filtrów, powyłączaj je`

**Comment by krystian3w** [comment]
To powinno być aż w formularzu zgłoszenia, nikt nie przeczyta tego Contributing (nie na polskie realia).

**Comment by kulfoon** [comment]
Hehe, fakt, i to nie tylko na polskie realie, bo i u goryla doszło do takiego momentu, że CONTRIBUTING wrzucił właśnie do formularza z polami do pozaznaczania, że "zapoznałem się z tym", "zapoznałem się z tamtym", "zrobiłem to", "zrobiłem tamto", "sprawdziłem to", "sprawdziłem tamto".

**Comment by salionPL** [comment]
Jednak wyłączenie " Anti-Thridparty Social" nie działa, przynajmniej nie do końca. Wyłączyłem jak pisałeś tą listę, ale wideo z facebooka nadal nie było. 
Wideo pojawiło się dopiero po wyłączeniu również listy "Polskie filtry do Adblocka...". Jak jedna z tych list bądź obie jest załączona to nie wyświetla się wideo. Potrzeba chyba jakiegoś wykluczenia w naszej polskiej liście?

**Comment by krystian3w** [comment]
Chyba tylko dla Chromowatych - Firefox daje radę.

Skończę robić zimowe strony, odbiorę zakupy, to spróbuje na to zerknąć w Operze stable/beta/dev.

**Comment by salionPL** [comment]
Sorry, nie wiem jak ja wyłączałem te listy (chyba nie poczekałem na załadowanie wideo), ale faktycznie po wyłączeniu tylko listy " Anti-Thridparty Social" wideo się pojawia. Więc racja że problem jest tylko w tej liście. Zwracam honor i przepraszam za zamieszanie.
