### ISSUE TITLE
chceauto.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#8993]
![d6cf9a1a-e65d-4abc-a08a-cf499d7d9aca](https://user-images.githubusercontent.com/36385327/46691465-4b001700-cc05-11e8-8f27-d8d3927fe663.png)

**Comment by MajkiIT** [comment]
@xMaap Nie mam tego ...
@hawkeye116477 @krystian3w zerkniecie ?

**Comment by xxcriticxx** [comment]
@MajkiIT bo masz liste vip

`||www.chceauto.pl/common/img/Ford_NowyFocus.jpg`
`chceauto.pl##.rek12`

**Comment by krystian3w** [comment]
Spacja w regule zobacz starsze zgłoszenie o tej stronie.

**Comment by krystian3w** [comment]
A `#.rek12` odpada, bo za wysoko unosi treść - nad nawigacje.

**Comment by xxcriticxx** [comment]
@xMaap zaktualizuj liste filtrow

**Comment by xMaap** [comment]
@xxcriticxx działa.

Jeszcze jest social
![27a4c101-f166-4247-8602-6882ca7e84c8](https://user-images.githubusercontent.com/36385327/46709091-650c1a80-cc42-11e8-9deb-caaa64865a47.png)

**Comment by krystian3w** [comment]
Sprawdź konfiguracje Nano Adblockera, w uBlock Origin nie ma:

> ![image](https://user-images.githubusercontent.com/35370833/46716507-8e3da280-cc64-11e8-8027-1ac9534ec081.png) |
> --- |

Sam też sprawdzę i najwyżej się je ukryje CSS-em "`visibility: hidden !important;`".

**Comment by xMaap** [comment]
Nie wiem o co chodzi, ale teraz nie widzę social.
![3fd202a8-c55e-4383-be0b-37c7a0391aa1](https://user-images.githubusercontent.com/36385327/46734050-636a4300-cc92-11e8-958a-91225b6c5f14.png)

**Comment by krystian3w** [comment]
Może lista Fanboya ci się zaktualizowała, jak patrzyłem to ona wycina obrazki i ja tylko doblokowałem RSS na polskiej liście RSS.

**Comment by krystian3w** [comment]
@kulfoon - ale sprawdzasz z aktywnym `Fanboy's Social Blocking List` i `Polskie Filtry Społecznościowe`, bo tak to nie ma sensu, że widzisz, bo będziesz widział.

**Comment by krystian3w** [comment]
Plus, najlepiej sprawdzajcie po użyciu <kbd>Ctrl</kbd> + <kbd>F5</kbd>  / <kbd>Ctrl</kbd> + R</kbd>, tak by nie trzeba było męczyć się z cache, które przyblokowało stronę (mam coś takiego w Operze).

Niby można by dodatkowo dociąć np. po linkach ("kosmetycznie") zamiast sieciowo.

**Comment by krystian3w** [comment]
> Nie wiem o co chodzi, ale teraz nie widzę social.

Może lista Fanboya ci się zaktualizowała, jak patrzyłem to ona wycina obrazki i ja tylko doblokowałem RSS na polskiej liście RSS.

> A ja ją widzę w uBO.

@kulfoon - ale sprawdzasz z aktywnym `Fanboy's Social Blocking List` i `Polskie Filtry Społecznościowe`, bo tak to nie ma sensu, że widzisz, bo będziesz widział.

I co konkretnie widzisz - resztkę reklamy, czy social załadowany z Cache?


---

Plus, najlepiej sprawdzajcie po użyciu <kbd>Ctrl</kbd> + <kbd>F5</kbd> / <kbd>Ctrl</kbd> + <kbd>R</kbd>, tak by nie trzeba było męczyć się z cache, które przyblokowało stronę (mam coś takiego w Operze).

Niby można by dodatkowo dociąć np. po linkach ("kosmetycznie") zamiast sieciowo, tyle czy to ma jakiś sens (jak dla mnie nie).

**Comment by kulfoon** [comment]
> 
> > A ja ją widzę w uBO.
> 
> @kulfoon - ale sprawdzasz z aktywnym `Fanboy's Social Blocking List` i `Polskie Filtry Społecznościowe`, bo tak to nie ma sensu, że widzisz, bo będziesz widział.
> 
> I co konkretnie widzisz - resztkę reklamy, czy social załadowany z Cache?

Skoro napisałeś post wyżej

> widzę reklamę / resztkę:

To do czego niby miałbym innego się odnosić...tak, widzę reklamę / resztkę dokładnie tak samo jak u ciebie na zrzucie o tutaj: https://github.com/MajkiIT/polish-ads-filter/issues/8993#issuecomment-428452719, sociali żadnych nie widzę (z włączonymi listami, które wymieniłeś) , jest tylko ikona RSS, któa także znika po dodaniu listy Polskie Filtry RSS​, więc jedyne co widzę to ta resztka / reklama.

> Plus, najlepiej sprawdzajcie po użyciu Ctrl + F5 / Ctrl + R, tak by nie trzeba było męczyć się z cache, 
> które przyblokowało stronę (mam coś takiego w Operze).

Zawsze tak robię gdy zajmuję się filtrami.
