### ISSUE TITLE
epuap.gov.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9]
cookies

UWAGA! W trakcie korzystania z ePUAP na komputerze użytkownika przechowywane są informacje (tzw. „ciasteczka”, ang. „cookies”), które pozwalają na dostosowanie świadczonych usług elektronicznych do indywidualnych potrzeb użytkowników. Warunki przechowywania lub dostępu do plików cookie mogą być określone przez użytkownika w ustawieniach przeglądarki internetowej. Kontynuacja korzystania z ePUAP bez dokonania wyżej wspomnianych zmian w ustawieniach przeglądarki internetowej uznana zostaje za wyrażenie zgody przez użytkownika na wykorzystywanie plików cookie. Więcej znajdziesz w Polityce Cookies

**Comment by MajkiIT** [comment]
Czy wyświetla Ci się to od razu po wejściu?

**Comment by xxcriticxx** [comment]
na samym dole strony

**Comment by MajkiIT** [comment]
Ok dzięki. Już patrzę.

**Comment by MajkiIT** [comment]
Zaktualizuj filtry.
