### ISSUE TITLE
obud.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9003]
Resztka / napis / pusty kontener po reklamie
http://www.obud.pl/art,17322,burzenie-murow--mastertop-na-biennale-architettura-2018,d_wnetrza

![ss1](https://user-images.githubusercontent.com/43844449/46727702-6d377a80-cc81-11e8-91b5-7f311bda88de.png)

**Comment by krystian3w** [comment]
W nagłówku też jakaś reklama kleju tytan 

`http://www.swb.nevicom.pl/redirect.php?b=1061&s=153` :arrow_right: `https://60sekund.tytan.pl/`
