### ISSUE TITLE
zabkowice.express-miejski.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9011]
2 x resztka / napis po reklamach
http://zabkowice.express-miejski.pl/wiadomosc/34598,oszczednosci-i-splata-zadluzenia-priorytetem-rzadzenia-alicja-bira-podsumowuje-kadencje

![ss1](https://user-images.githubusercontent.com/43844449/46729591-0ff1f800-cc86-11e8-8bfd-b198e7479a07.png)

**Comment by krystian3w** [comment]
W nagłówku też pustki po reklamach
