### ISSUE TITLE
winicjatywa.pl NFSW

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9019]
cookies

![ss1](https://user-images.githubusercontent.com/43844449/46731386-cfe14400-cc8a-11e8-98ed-cd90eeeaca4c.png)

**Comment by hawkeye116477** [comment]
Nie zajmujemy się stronami NFSW.
Zostawimy to, tym bardziej, że są tu ważne informacje :smile:
