### ISSUE TITLE
tubawyszkowa.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9020]
1) od pyty resztek / napisów po reklamach, zarówno na głównej (naliczyłem x 14) jak i w artykułach (naliczyłem x6 np. tu https://tubawyszkowa.pl/aktualnosci/czytaj/10288-jesienne-sprzatanie-lasow-zabrodzia)
2) rodo / cookies / polityka

![ss1](https://user-images.githubusercontent.com/43844449/46731652-8cd3a080-cc8b-11e8-9062-258d073daf01.png)

![ss3](https://user-images.githubusercontent.com/43844449/46731653-8e04cd80-cc8b-11e8-9e64-00a0642e045a.png)

**Comment by krystian3w** [comment]
A mnie jakiś pop-up z wyciętą reklamą atakuje:

> ![image](https://user-images.githubusercontent.com/35370833/46731993-83970380-cc8c-11e8-88c3-c89f8dfe03ec.png) |
> --- |

**Comment by krystian3w** [comment]
ad. 2. `##.rodo`

**Comment by hawkeye116477** [comment]
@MajkiIT `Tamtą regułę proponuję usunąć, a to dodać do listy uBO => `tubawyszkowa.pl##+js(abort-current-inline-script.js, $, #AdPopup)` i to na resztki do głównej => `tubawyszkowa.pl##.active.aligned.center.segment.basic.stackable.ui`
