### ISSUE TITLE
github avatar

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9025]
@kulfoon w prezencie od wszystkich z polish filter list twoj nowy avator :)

![kulfon_400x400](https://user-images.githubusercontent.com/15007183/46743680-98b56780-cc77-11e8-8f6e-b3bc642e6071.jpg)

**Comment by xxcriticxx** [comment]
@kulfoon mucho love!

**Comment by kulfoon** [comment]
@xxcriticxx 

![](https://yt3.ggpht.com/a-/AN66SAwCS7hehCBhakRlqQuPUnoWyYpRoWuMlaf_9g=s900-mo-c-c0xffffffff-rj-k-no)

**Comment by klakieer** [comment]
@xxcritixx

![obraz](https://user-images.githubusercontent.com/44292328/47231652-c57f2280-d3cd-11e8-942b-08bd0307431a.png)
