### ISSUE TITLE
Kilka pytań

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9026]
Mam kilka pytań:

1
Co się stało z filtrami wewnętrznymi, które prowadził @KonoromiHimaries, tzn dlaczego przestały być wspierane w polskich filtrach, bo wiem, że jeszcze jakiś czas temu były one wymienione w polskich listach na spisie list: 
https://github.com/MajkiIT/polish-ads-filter#about

a teraz zniknęły ze spisu i napisane, że nie wspierane: 
https://github.com/MajkiIT/polish-ads-filter/tree/master/inside-filters_nie_wspierane

i @KonoromiHimaries prowadzi je tylko u siebie:
https://github.com/KonoromiHimaries/PolishSubFilters

Jakieś spięcie, że teraz nawet nie ma jej wymienionej w polskich filtrach? A może różnica w polityce.

2
Gdzie zgłaszać reklamy wewnętrzne bo na https://github.com/KonoromiHimaries/PolishSubFilters nie ma Issue trackera, a tutaj zauważyłem, że zamykane są takie zgłoszenia bez naprawiania ich w POL liście:

https://github.com/MajkiIT/polish-ads-filter/issues/8921 https://github.com/MajkiIT/polish-ads-filter/issues/8928 https://github.com/MajkiIT/polish-ads-filter/issues/8931 https://github.com/MajkiIT/polish-ads-filter/issues/8937 https://github.com/MajkiIT/polish-ads-filter/issues/8938 https://github.com/MajkiIT/polish-ads-filter/issues/8940 https://github.com/MajkiIT/polish-ads-filter/issues/8943 https://github.com/MajkiIT/polish-ads-filter/issues/8947 https://github.com/MajkiIT/polish-ads-filter/issues/8988 https://github.com/MajkiIT/polish-ads-filter/issues/9005 https://github.com/MajkiIT/polish-ads-filter/issues/9008 https://github.com/MajkiIT/polish-ads-filter/issues/9012 https://github.com/MajkiIT/polish-ads-filter/issues/9023

 ani  więc domniemam, że POL: polskie filtry do Adblocka i uBlocka nimi się nie zajmują, a po dodaniu:
https://raw.githubusercontent.com/KonoromiHimaries/PolishSubFilters/master/internal-filters/wewnetrzne.txt 
niektóre (chyba nawet większość, ale nie sprawdzałem wszystkich )  nie są naprawione np. https://github.com/MajkiIT/polish-ads-filter/issues/8928 https://github.com/MajkiIT/polish-ads-filter/issues/8931 https://github.com/MajkiIT/polish-ads-filter/issues/8947

3
Dlaczego dzisiaj zamykane  i nienaprawiane są także niektóre zgłoszenia  zwykłych resztek / napisów po reklamach np:

https://github.com/MajkiIT/polish-ads-filter/issues/9001 https://github.com/MajkiIT/polish-ads-filter/issues/9003 https://github.com/MajkiIT/polish-ads-filter/issues/9006 https://github.com/MajkiIT/polish-ads-filter/issues/9010 https://github.com/MajkiIT/polish-ads-filter/issues/9011 https://github.com/MajkiIT/polish-ads-filter/issues/9017 https://github.com/MajkiIT/polish-ads-filter/issues/9018 https://github.com/MajkiIT/polish-ads-filter/issues/9021 https://github.com/MajkiIT/polish-ads-filter/issues/9022

kiedy niektóre inne są naprawiane, bo dotychczas były naprawiane wszystkie takie, co się nagle zmieniło?  No bo coś jest chyba nie tak, żebym musiał otwierać prawie 10 wątków typu "reopen". A może zaraz pójdzie jakiś commit do ww. zgłoszeń i trzeba poczekać? A może z jakiegoś powodu się nie kwalifikują, jeśli tak to z z jakiego?

**Comment by KonoromiHimaries** [comment]
> Co się stało z filtrami wewnętrznymi, które prowadził @KonoromiHimaries, tzn dlaczego przestały być wspierane w polskich filtrach, bo wiem, że jeszcze jakiś czas temu były one wymienione w polskich listach na spisie list

chciałem zmienić nazwę filtrów wewnętrznych z inside na internal

> Gdzie zgłaszać reklamy wewnętrzne

nie zgłaszaj, opisz/otaguj wszystko dokładnie i pull-requestuj

> nie ma Issue trackera

mamy kanał na discordzie

**Comment by xxcriticxx** [comment]
@kulfoon widze ze jestes z kumatych (jak kolwiek sie to pisze) to prosmy o pull requests zrobic tak samo jak @hawkeye116477

**Comment by kulfoon** [comment]
Jednak muszę zwrócić część honoru i poprawić siebie:

> 3
> Dlaczego dzisiaj zamykane i nienaprawiane są także niektóre zgłoszenia zwykłych resztek / napisów po reklamach np:
>
> #9001 #9003 #9006 #9010 #9011 #9016 #9017 #9018 #9021 #9022

Otóż przyjrzałem się dzisiaj dokładniej, i z tych 10 wymienionych przez mnie zgłoszeń, dokładnie połowa czyli 5 okazało się reklamami wewnętrzymi, więc dlatego zostały odrzucone, a dokładniej: 

https://github.com/MajkiIT/polish-ads-filter/issues/9003 https://github.com/MajkiIT/polish-ads-filter/issues/9010 https://github.com/MajkiIT/polish-ads-filter/issues/9011 https://github.com/MajkiIT/polish-ads-filter/issues/9016 https://github.com/MajkiIT/polish-ads-filter/issues/9017

A więc tylko 5 wymaga naprawy, utworzyłem filtry:

https://github.com/MajkiIT/polish-ads-filter/issues/9001 `forum.przyroda.org##table:nth-of-type(2) > tbody > tr > td > table`
https://github.com/MajkiIT/polish-ads-filter/issues/9006 (www.sprzedajsuknie.pl/ natemat.sprzedajsuknie.pl) `sprzedajsuknie.pl##.adsblock1`
https://github.com/MajkiIT/polish-ads-filter/issues/9018 `www.onlinecenter.pl##.componentheading_small:nth-of-type(3)`
https://github.com/MajkiIT/polish-ads-filter/issues/9021 `mynaszlaku.pl###text-2`
https://github.com/MajkiIT/polish-ads-filter/issues/9022 `www.kazimierzdolny.pl##.sidebar__widget:nth-of-type(1)`

PR === > https://github.com/MajkiIT/polish-ads-filter/pull/9029

**Comment by kulfoon** [comment]
> 
> > @kulfoon : 
> > Co się stało z filtrami wewnętrznymi, które prowadził @KonoromiHimaries, tzn dlaczego przestały być wspierane w polskich filtrach, bo wiem, że jeszcze jakiś czas temu były one wymienione w polskich listach na spisie list

> @KonoromiHimaries :
> chciałem zmienić nazwę filtrów z inside na internal

Ech, szkoda, chłopaki pokłócili się on nazwę, jeśli chodzi o nazwę to wg. mnie czy pierwsza nazwa czy ta druga to bez znaczenia, obydwie pasują tak samo, no ale ja, nie trzymając żadnej ze stron, chciałbym po prostu, żeby te filtry znowu wróciły:

https://github.com/MajkiIT/polish-ads-filter/tree/master/inside-filters_nie_wspierane
https://github.com/MajkiIT/polish-ads-filter/tree/master/anti-donate-filters_nie_wspierane

Chłopaki no dogadajcie się jakoś, niech któryś ustąpi drugiemu, najważniejsze żeby wszystkie nasze filtry trzymały się razem, w jedności siła...(chociaż czasem również i podziały jak widać) albo może po prostu rzucicie monetą? Np. orzeł - zostaje `inside`, reszka - będzie `internal`.

Wasz Wielkouchy Kulfon !

**Comment by KonoromiHimaries** [comment]
> chciałbym po prostu, żeby te filtry znowu wróciły:

majki kiedyś pisał że planuje oddać filtry wewnętrzne które są na jego repo komuś innemu, 
może ty kulfoon będziesz chciał je przejąć i dalej rozwijać niezależnie od moich.

> Chłopaki no dogadajcie się jakoś, niech któryś ustąpi drugiemu

nie mam pojęcia jak możemy się dogadać. majki nawet kazał usunąć swój nick z listy collaboratorów bo nie chce mieć ze mną nic wspólnego.

**Comment by xxcriticxx** [comment]
@krystian3w prosimy o PR

**Comment by kulfoon** [comment]
> @KonoromiHimaries 
> nie mam pojęcia jak możemy się dogadać. majki nawet kazał usunąć swój nick z listy collaboratorów bo nie chce mieć z moimi filtrami nic wspólnego.

Aż nie chce mi się wierzyć, że poszło tylko o nazwę, a nie np. o politykę (filtrów wewn.) albo w ogóle jeszcze o coś innego, przecież o samą nazwę mogłyby się co najwyżej dzieci pokłócić, może już wcześniej coś między wami było, coś musiało być na rzeczy.

**Comment by KonoromiHimaries** [comment]
@kulfoon zmiana nazwy wiązała się ze zmianą adresu url listy, co sprawiło by że wszyscy którzy zasubskrybowali listę stracili by auto-aktualizacje i musieli by zasubskrybować jeszcze raz.

**Comment by krystian3w** [comment]
Niby Adblock Plus obsługuje przekierowanie w starym pliku, ale uBlock Origin już nie ma czegoś takiego.

```
[Adblock Plus 2.0]
! Redirect: tu nowy url
```

Wiem, że niby lista była tylko pod Nano Adblocker / uBlock Origin, ale tam chyba tylko CSS był pod niego (potem już nie sprawdzałem czy używasz jakiś `xpath`, `matches-css-before`, `script:inject` itp.)?

**Comment by hawkeye116477** [comment]
Ta, nie ma redirect w uBO i nie będzie, gorhill uznał to za niezbezpieczne czy coś.

**Comment by hawkeye116477** [comment]
Jeszcze były też anty-dotacje i zostały zmienione na anty-donacje, dlatego, że dotacje to raczej są od rządu, więc raczej było błędnie.

**Comment by kulfoon** [comment]
>  @KonoromiHimaries:
> Majki szuka kogoś nowego do prowadzenia filtrów wewn. może ty @kulfon być się nimi zajął

@KonoromiHimaries skoro wy się pokłóciliście, to być może zajmę się prowadzeniem filtrów wewn. ale jak coś to za jakiś czas (tydzień albo dwa), bo na chwilę obecną jestem zajęty dobijaniem zwykłych reklam oraz wyszukiwaniem rodo/ciasteczek bo ich jeszcze "trochę" zostało. Acha no jeszcze jedno, w filtrach wewn. nie będzie w nich tego `!#include zewnetrzne_listy.txt ` bo to są listy zewnętrzne , które każdy może sobie sam osobno dodać jak będzie chciał. Bo includować listy zewnętrzne to tak jakby do POL filtrów zaincludować EasyList, albo do https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/adblock.txt zaincludować EasyPrivacy, po co, te listy istnieją jako osobne, stworzone przez innych ludzi, i każdy sobie sam je doda jeśli będzie chciał, nie można zmuszać ludzi do ich includowania, a więc będą tylko twoje oryginalne autorskie listy, czyli główna +:

```
!#include paid-subscriptions/prenumeraty.txt
!#include anti-donate-filters/anty-donacje.txt
!#include e-commerce-filters/wizjer_e-handlu.txt
!#include floating-elements/plywajace-elementy.txt
!#include danger-domians/elementy-niebezpieczne.txt
```

Ale będziesz mi musiał pomagać w prowadzeniu tych filtrów wewn. bo ty jesteś ich oryginalnym autorem i najlepiej orientujesz się do której kategorii jaki element zaliczyć, no i po prostu też pomagać (pull requesty).

I tak sobie myślę, skoro chodzą pogłoski, że te filtry https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/adblock.txt powoli umierają, i żeby ktoś się nimi zajął (https://github.com/MajkiIT/polish-ads-filter/issues/9064) to może:
- skopiować te filtry prywatności do polskiego repo i niech @trackerless je prowadzi
- zaliczyć je do filtrów wewn. jako `!#include privacy-filters/filtry-prywatnosci.txt`

**Comment by KonoromiHimaries** [comment]
> są listy zewnętrzne , które każdy może sobie sam osobno dodać jak będzie chciał

moje filtry są modułowe więc nie wymagam dodawania wszystkich modułów.

> includować listy zewnętrzne to tak jakby do POL filtrów zaincludować EasyList

nie includuje list bazowych jak EasyList, tylko listy poboczne jak iploggerfilter z własnymi poprawkami

> Ale będziesz mi musiał pomagać w prowadzeniu tych filtrów wewn.

no jasne, wołaj jak coś. chociaż nie sądzę żebym miał takie jak umiejętności jak hawk, majki czy faz

>  najlepiej orientujesz się do której kategorii jaki element zaliczyć

najlepiej odchudź trochę listę z tych kategorii żeby łatwiej było się w tym połapać

**Comment by kulfoon** [comment]
> nie includuje list bazowych jak EasyList, tylko listy poboczne jak iploggerfilter z własnymi poprawkami

Rozumiem, być może podany przeze mnie przykład nie był idealnie trafiony w tym sensie, mniejsza o to, chodziło o to, że zaincludowane listy zewnętrzne miały zdaje się więcej filtrów niż wewnęrzne (jeszcze kilka dni temu filtry wewn łącznie mialy o ile pamiętam 10000 czy 12000 filtrów, teraz już około 4600)  stąd mój przykład z EasyList i EasyPrivacy (może jednak trochę przesadzony be listy są znacznie większe), ale chodziło po prostu o to żeby nie includować osobnych list zewnętrznych bo za dużo się tego robi, a nie da się tych poprawek (samych poprawek) wrzucić do osobnej listy np. `!#include zewnetrzne-poprawki.txt` ? Albo tak patrzę teraz i jest tych wszystkich filtrów ponad 4600 zamiast 10000 czy 12000 więc zdaje się, że elegancko je już odchudziłeś?

> najlepiej odchudź trochę listę z tych kategorii żeby łatwiej było się w tym połapać

No i nie wiem czy załapię twoje "hierglify" :)

**Comment by krystian3w** [comment]
To kiedyś miało opis jak nadawać ale lepszy już był by chyba link gdzie łapnięta reklama.

**Comment by kulfoon** [comment]
> @krystian3w 
> A porządki były - KonoromiHimaries/PolishSubFilters@cd66abd - 5,845 poszło.

No i elegancko, teraz jest o połowę filtrów mniej bo wyrzucona lista POPADS, która chyba i tak zrezszto była raczej do anieglskojęzycznych stron? Tak może być, a jeszcze o co chodzi z tą listą KAD? Tu też różnica w polityce?

**Comment by kulfoon** [comment]
Acha, to też do wyrzucenia i to też: 
`Source: https://github.com/HexxiumCreations/threat-list/blob/gh-pages/hexxiumthreatlist.txt`

Nic do tych list zewnetrznych nie mam (Anti popads.net, KAD - przekręty, hexxiumthreatlist) bo sam ich używam , ale jako osobnych, i w ogóle to są host listy blokujące całe domeny, czyli jakby inny typ list, a nie listy zawierające filtry blokujące poszczególne elementy/reklamy/banery wewn. na stronach. Jaki te listy mają związek z filtrami wewn.? Bo wydaje mi sie, że wszystkie 3 zostały dodane bo za dużo miałeś w panelu uBO.

**Comment by xxcriticxx** [comment]
@kulfoon zles z kompa i mecz oglondaj

**Comment by krystian3w** [comment]
Ja tam się męczę z podmianą CSS-em awatara i mam tylko połowiczne efekty, jak nie chcę do akcji wprowadzać Stylus.

**Comment by kulfoon** [comment]
Witam, padam ofiarą kolejnych represji ze strony admina: https://github.com/MajkiIT/polish-ads-filter/pull/9091 

Zatem, chciałem zgłosić, że admin tej strony o nicku @MajkiIT agresywnie uniemożliwa mi branie udziału we współtworzeniu tej listy ponieważ:

- zamyka moje zgłoszenia bez słowa wyjaśnienia, przez co muszę się sam dopytywać o co chodzi, co jest zwyczajnie poniżające i chamskie
- gdy już dostałem odpowiedź od drugiego admina xxcriticxx, że mam robić pull requesty, to gdy je robię to znowu admin @MajkiIT je odrzuca bez słowa wyjaśnienia, co jest zwyczajnie poniżające i chamskie
- gdy pytam się o co chodzi z odrzuconym pull requestem i z tym ignorowaniem mnie, to nie dostaję odpowiedzi i admin @MajkiIT zwyczajnie ignoruje i olewa ciepłym moczem

Zachowanie tego admina jest ohydne oraz uniemożliwające mi wkład w rozwój listy, robi co chce, zamyka co chce, ignoruje jak chce i nie liczy się z drugim człowiekiem i z jego pracą, jako że on się nie odzywa, i nie potrafi podać żadnych argumentów na usprawiedliwienie swojego parszywego zachowania, to chciałem zapytać @KonoromiHimaries albo innych osób:
- dlaczego ten admin taki jest, i czy taka postawa jest godna admina polskiej listy?
- w jaki sposób mam brać udział we współtworzeniu tej listy skoro admin mi to fizycznie uniemożliwa,a następnie ignoruje zamiast odpowiedzieć o co chodzi? Czuje się zdyskryminowany, chciałbym dużo pomóc, i chciałem po prostu zwyczajnie zapytać czym sobie zasłużyłem na takie traktowanie?

**Comment by KonoromiHimaries** [comment]
kiedyś był tutaj taki użytkownik o nicku gomoku który na złość zrobił kilka zgłoszeń więcej gdy majki prosił go aby wstrzymał się na chwilę i wydaje mi się że teraz pewnie przez to majki woli wgl. nic nie odpisywać żeby nie podkręcać atmosfery.

**Comment by blocker999** [comment]
@MajkiIT Czuje się winny twym podejrzenią bo to odemnie zaczeła się z przeczka z gamoku, dziś wiem że miał sporo racji lecz niechciał zrozumieć mojego braku czasu i zwyczajnie rozstaliśmy się w kłutni.

Niechce aby to samo miało tu miejsce tu bo : ' w przypadku coraz większej ilości stron w internecie i reklam się na nich pojawiających, kolejna para rąk do pracy będzie mile widziana`

Mam tylko jedno pytanie czy to jest lista prywatna czy publiczna?

@kulfoon A Ciebie proszę o cierpliwość, wyrozumienie i ewentualny kompromis.

**Comment by kulfoon** [comment]
> @KonoromiHimaries : który na złość

Nie na złość, tylko dla zabawy, o czym wyraźnie wspominał, nie wiem czy to przekręcanie na złość faktów z twojej strony czy przeoczenie...Poza tym ten gość obiecał i zdaje się, że przeprosił chyba też, że nie będzie już takich żartów robił, nie wiem czy to także z twojej strony na złosć zatajenie czy kolejne przeoczenie...

> @KonoromiHimaries : kiedyś był...to lepiej nie wchodzić w dysputę.

I już go nie ma, teraz jest kulfoon, z którym można dyskutować i który zachowuje się w porządku i nie robi takich żartów, co najwyżej trochę popajacuje razem z xxcriticxx i kłapnie uszami dla zabawy.

> @blocker999 :  @kulfoon A Ciebie proszę...

Spoko, jak widzisz, z mojej strony jest wszystko w porządku, tylko nie wiem czy to admin ma ciągle jakieś stare wąty czy może się mści do 5 pokolenia wprzód, ja się nie zamierzam kłócić, tylko niech napisze co nie tak z PR, to poprawię.

**Comment by kulfoon** [comment]
> @KonoromiHimaries : który na złość

Nie na złość, tylko dla zabawy, o czym wyraźnie wspominał...poza tym ten gość obiecał i zdaje się, że przeprosił chyba też, że nie będzie już takich żartów robił.

> @KonoromiHimaries : kiedyś był...to lepiej nie wchodzić w dysputę.

I już go nie ma, teraz jest kulfoon, z którym można dyskutować i który zachowuje się w porządku i nie robi takich żartów, co najwyżej trochę popajacuje razem z xxcriticxx / krystian3w i kłapnie uszami dla zabawy.

> @blocker999 :  @kulfoon A Ciebie proszę...

Spoko, jak widzisz, z mojej strony jest wszystko w porządku, tylko nie wiem czy to admin ma ciągle jakieś stare wąty czy może się mści do 5 pokolenia wprzód, zreszto poza tym admin chyba zawsze był taki, że często ignorował tak po prostu (co jest wkurzające), ja się nie zamierzam kłócić, tylko niech ktoś napisze co nie tak z PR, to poprawię, no chyba, że PR był poprawny, a odrzcuił bo odrzucił...to zrobię nowego.

**Comment by MajkiIT** [comment]
@blocker999 to do mnie ?

> 
Mam tylko jedno pytanie czy to jest lista prywatna czy publiczna?

**Comment by xxcriticxx** [comment]
public

**Comment by blocker999** [comment]
Pytanie retoryczne

**Comment by kulfoon** [comment]
> @kulfoon KonoromiHimaries: to lepiej nie wchodzić w dysputę.

Jak już pisałem nie chcę się kłócić, czy nazbyt ostro dyskutować,  (bo kulfoon nie przyszedł się tu kłócić itp.), tylko rozmawiać w normalny sposób i zwyczajnie dowiedzieć sie dlaczego PR odrzucony, jeśli jest jakiś błąd czy problem to go naprawię, wystarczy wskazać ten problem. 

A jeśli nie podoba mu sie styl moich filtrów to generalnie uważam, że skoro lista jest na zasadach open source, to każdy obeznany może kodować w swoim stylu (bo jak wiadomo ten sam filtr można zapisać na kilka sposobów) i jeden koder nie powinien drugiemu zaglądać i narzucać swojego stylu, bo wtedy robi się lista prywatna, a nie publiczna, no chyba, że wykaże, że jego sposoby pisania filtrów są lepsze to się dostosuję (mam np, je bardziej upakowywać albo mniej itp., jakieś wskazówki?) jestem otwarty i nie będę się kłócił. Czekam.

**Comment by KonoromiHimaries** [comment]
> Jak już pisałem nie chcę się kłócić, czy nazbyt ostro dyskutować, (bo kulfoon nie przyszedł się tu kłócić itp.), tylko rozmawiać w normalny sposób i zwyczajnie dowiedzieć sie dlaczego PR odrzucony, jeśli jest jakiś błąd czy problem to go naprawię, wystarczy wskazać ten problem.

ah tak

![2018-10-17-update to version 2018101501 by kulfoon pull request 9091 majkiit_polish-ad](https://user-images.githubusercontent.com/5884000/47113891-88465380-d25a-11e8-9ef6-929e0018384c.png)
`https://github.com/MajkiIT/polish-ads-filter/pull/9091#issuecomment-429865919`
