### ISSUE TITLE
find useless filters

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9030]
its time again to check your list

https://adblockplus.org/en/redundancy_check

**Comment by kulfoon** [comment]
Ten jest lepszy i bardziej zaawansowany: 
https://arestwo.org/famlam/redundantRuleChecker.html

**Comment by xxcriticxx** [comment]
@kulfoon zapraszamy do wspolnej zabawy

**Comment by kulfoon** [comment]
Kulfon się bawić!

**Comment by krystian3w** [comment]
On jest zamykany i w filtrach jest adres do nowego, który ma na jego kodzie rozwijać MajkiIT.

**Comment by kulfoon** [comment]
> On jest zamykany i w filtrach jest adres do nowego, 

O tym wiedziałem.

> który ma na jego kodzie rozwijać MajkiIT.

O tym nie.

**Comment by krystian3w** [comment]
> its time again to check your list
> 
> https://adblockplus.org/en/redundancy_check

W sumie wywaliło tylko wyjątki pod anty-adblock.
Więc do przejrzenia na spokojnie czy jest tam coś sensownego podanego. Automatyczna automatyzacja ich może je przywrócić.

A dodatkowo w optymalizatorze **`@`falama** już widzę, że są znowu jakieś reguły pod uBlock Origin, na głównej liście.


- `stooq.com#?##f13 > table:if(#f13 > b:-abp-contains(Artykuł Sponsorowany))` : The selector isn't a valid CSS3 selector
- `stooq.pl#?##f13 > table:if(#f13 > b:-abp-contains(Artykuł Sponsorowany))` : The selector isn't a valid CSS3 selector
- `stooq.pl,stooq.com##:xpath(//*[@align="center"]/*[@id][contains(text(),"REKLAMA")])` : The selector isn't a valid CSS3 selector
- `torebunia.pl###adv_on_post, #small,` : The selector isn't a valid CSS3 selector
- `money.pl##div[class]:if(>div[class]:first-child:has-text(REKLAMA):if-not(>*))` : The selector isn't a valid CSS3 selector

jak już to powinno to być np. `:-abp-has(...)` (nie wydaje mi się, by aż uprościli składnię do `if`) i `xpath` chyba dalej niezaimplementowany w Adblock Plus / Adblock.


---

- `||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org,badfilter` : Unknown option 'important'
- `||addthis.com/*/addthis_widget.js$script,badfilter` : Unknown option 'badfilter'
- `||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org|~sainsburys.jobs,badfilter` : Unknown option 'important'


to też by można rozdzielić by na głównej było tylko dopuszczenie wyjątków EasyPrivacy / EasyList a negacja uBO Privacy w pliku dla uBlock Origin.

**Comment by kulfoon** [comment]
Zastanawiałem się dlaczego nagle ubyło ponad 120 filtrów z listy, było jakieś 6005 a teraz jakieś 5885​, myślałem, że to porządki związne z tym wątkiem, ale prawda jest bardziej bolesna, te filtry tam są, ale zostały zepsute, cały blok został zepsuty: https://github.com/MajkiIT/polish-ads-filter/commit/f7eb2fab0d3db0fa97e21f8a87e942c84c8dced3

 ```
Cosmetic filtering – invalid filters:

jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,imeds.pl,pl.aleteia.org,overwatch.pl,waw4free.pl,dziwneobrazki.pl,fm.tuba.pl##@#.pub_300x250
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,imeds.pl,pl.aleteia.org,overwatch.pl,jackcaleib.com,waw4free.pl,dziwneobrazki.pl#,fm.tuba.pl#@#.pub_300x250m
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,imeds.pl,pl.aleteia.org,overwatch.pl,jackcaleib.com,waw4free.pl,dziwneobrazki.pl,fm.tuba.pl##@#.pub_728x90
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,imeds.pl,pl.aleteia.org,overwatch.pl,jackcaleib.com,waw4free.pl,dziwneobrazki.pl,fm.tuba.pl##@#.text_ad
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,imeds.pl,pl.aleteia.org,overwatch.pl,jackcaleib.com,waw4free.pl,dziwneobrazki.pl,fm.tuba.pl##@#.text-ad
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,imeds.pl,pl.aleteia.org,overwatch.pl,jackcaleib.com,waw4free.pl,dziwneobrazki.pl,fm.tuba.pl##@#.textAd
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,imeds.pl,pl.aleteia.org,overwatch.pl,jackcaleib.com,waw4free.pl,dziwneobrazki.pl,fm.tuba.pl##@#.text-ad-links
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,imeds.pl,pl.aleteia.org,overwatch.pl,jackcaleib.com,waw4free.pl,dziwneobrazki.pl,fm.tuba.pl##@#.text_ads
jbzdy.pl,kwejk.pl,piwniczkamemow.pl,eszkola.pl,dobreprogramy.pl,interia.pl,kwantowo.pl,katowickisport.pl,imeds.pl,pl.aleteia.org,overwatch.pl,jackcaleib.com,waw4free.pl,dziwneobrazki.pl,fm.tuba.pl##@#.text-ads 
```

Omyłkowo dodano zbędne hasze do filtrów `#@#` robiąc niepoprawne `##@#`
A tutaj nawet jeden hasz zabawnie się zaplątał: `dziwneobrazki.pl#,fm.tuba.pl#@#.pub_300x250m`

Tu się zaplątał na końcu zbędny przecinek:
`Cosmetic filtering – invalid filter: #adv_on_post, #small,`

A tu zdublowane dolary i jakieś zbędne spacje:
```
Network filtering – invalid filter: hdtvpolska.com$$script[tag-content="#sdWelcomeScreen"]
Network filtering – invalid filter: czasdzieci.pl$$html body.cdb div#allPage script
```

**Comment by krystian3w** [comment]
Ostatnie to magia html filteringu w wykonaniu AdGuarda, widać im nie odpowiadał daszek.

**Comment by kulfoon** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/a0b0edc659b65871609ccdb1781d9ce987bbf9a8

The following error, warning or optimalization was encountered while checking the rules:

 The following domain of 

`tubagliwic.pl,tubawyszkowa.pl##.active.aligned.center.segment.basic.stackable.ui > small, .aligned.center.column.one.grid.stackable.ui > p > small, .active.aligned.center.segment.basic.stackable.ui > p > small` 

can be removed: `tubawyszkowa.pl`

**Comment by krystian3w** [comment]
Dopatruje się podobieństwa dziecka i wnuka ale wcale nie analizuje rodzica (dziadka).

Niby można uprościć do samego `#p > small`, raczej rzadko w artykule prasowym piszą coś małym druczkiem (do sprawdzenia, by się nie ugryźć potem w język) lub ktoś na kolanie robił cały szablon.

**Comment by xxcriticxx** [comment]
bo silnik z malucha :+1:

**Comment by kulfoon** [comment]
> Dopatruje się podobieństwa dziecka i wnuka ale wcale nie analizuje rodzica (dziadka).

buahahaha

> bo silnik z malucha 

buahahaha

Tutaj jak w cyrku normalnie

Kulfon Czerwonouchy

**Comment by klakieer** [comment]
Znalazłem filtr bezużyteczny dla użytkowników ABP, zwyczajnie nie działa pod ABP bo nie poprawna składnia:

https://github.com/MajkiIT/polish-ads-filter/blob/a4103f650f013ed7d78828a1d10355c3f9c00a8f/polish-adblock-filters/adblock.txt#L4226

Powinno być `~third-party` zamiast `first-party` żeby filtr działał pod ABP, zwłaszcza, że filtr dotyczy EasyList.

**Comment by krystian3w** [comment]
Jak to, wykluczenie z blokowania i tylko w domenie spedycje...

**Comment by krystian3w** [comment]
W sumie tak...

```
Wiersz 2 397: ':xpath(//*[@align="center"]/*[@id][contains(text(),"REKLAMA")])' nie jest poprawnym selektorem CSS
Wiersz 2 797: '.bbbb:-abp-has([data-original*="/pictures/informacje/"])' nie jest poprawnym selektorem CSS
Wiersz 2 798: '.bbbb > div > div > div:-abp-contains(reklama)' nie jest poprawnym selektorem CSS
Wiersz 2 801: '.bottom:nth-of-type(n+5):nth-of-type(-n+6) > .bbbb:-abp-contains(reklama)' nie jest poprawnym selektorem CSS
Wiersz 2 802: '.bottom:nth-of-type(20) > .bbbb:-abp-contains(reklama)' nie jest poprawnym selektorem CSS
Wiersz 4 042: Nieznana opcja filtra
Wiersz 4 043: Nieznana opcja filtra
Wiersz 4 181: 'div[class*=" "]:-abp-has(> img[src$="/i.wp.pl/a/i/stg/pkf/bg.png"])' nie jest poprawnym selektorem CSS
Wiersz 4 205: 'div[class]:if(>div[class]:first-child:has-text(REKLAMA):if-not(>*))' nie jest poprawnym selektorem CSS
Wiersz 4 226: Nieznana opcja filtra
Wiersz 4 227: Nieznana opcja filtra
Wiersz 4 240: Nieznana opcja filtra
Wiersz 4 246: Nieznana opcja filtra
Wiersz 4 247: Nieznana opcja filtra
Wiersz 4 248: Nieznana opcja filtra
Wiersz 4 249: Nieznana opcja filtra
Wiersz 4 426: Nieznana opcja filtra
```

**Comment by krystian3w** [comment]
Aż sam się dziwię, że twoje reguły z `.bbbb` nie są poprawne dla AdBlock Plus 3.3.1.

**Comment by gargaamel** [comment]
Nie są bo admin z nieznanych przyczyn nie dodał `?` (`#?#`) odrzucając PR, który to naprawiał: https://github.com/MajkiIT/polish-ads-filter/pull/9091, a bez tego pytajnika są niepoprawne pod ABP.

**Comment by gargaamel** [comment]
Znalazłem aż 5 takich samych filtrów:
```
!14#---------------------------------Anti Adblock Rules element hide----------------------------------!
24opole.pl,webcamera.pl,darmowe-torenty.pl#@#.ad
dziennikwschodni.pl,vorek.pl#@#.ad
katowickisport.pl,torrentcity.pl#@#.ad
wtkplay.pl,epoznan.pl#@#.ad
webcamera.pl##.ad
```
Czy coś stoi na przeszkodzie żeby je scalić w jeden? @MajkiIT

**Comment by krystian3w** [comment]
Ładniej wyglądają rozbite na 4 linie, od biedy można skleić w jedną.

**Comment by gargaamel** [comment]
> krystian3w : Ładniej wyglądają

Buahaha, krystian3w rozumiem, że to kolejna taka ironia jak z tymi kilkoma wiernymi subskrybentami: https://github.com/MajkiIT/polish-ads-filter/issues/9822#issuecomment-439033033, tzn. tam kilka wiernych subskrybentów, a tutaj kilka ładnych filtrów, buahahaha.

> krystian3w : rozbite na 4 linie

Nie tylko rozbite, ale i także dodatkowo porozrzucane co ileś wierszy.

> krystian3w : od biedy można skleić w jedną.

Po co, lepiej rozbić jeszcze bardziej: 1 domena na 1 filtr.

**Comment by MajkiIT** [comment]
@gargaamel dzięki

**Comment by gargaamel** [comment]
Duplikaty: https://github.com/MajkiIT/polish-ads-filter/issues/9621#issuecomment-439287529

**Comment by krystian3w** [comment]
```
Finished (after 4 seconds)!  1 redundant rule found!

istotne.pl##.advert has been made redundant by ~allegro.pl##.advert
```

Ale to widać ma jakieś generichide

**Comment by krystian3w** [comment]
Z racji, że został usunięty post o duplikatach na EasyPrivacy i nie było podanej propozycji redundancji to też usuwam posty.

Z komunikatów jakie mamy jest jeden:

```
Finished (after 4 seconds)!  1 redundant rule found!

istotne.pl##.advert has been made redundant by ~allegro.pl##.advert
```

Ale go nie można zoptymalizować przez `generichide` i zasięg jak ma mieć filtr `##.advert`  (globalny z wykluczeniem Allegro.

Warningi co do filtrów uBlockowych na liście pod wszystkie blokery reklam wynikają z testów nieszkodliwości.

**Comment by MajkiIT** [comment]
@krystian3w Ok, dziękuję

**Comment by krystian3w** [comment]
Albo anti-adblock - tyle że nie mogę teraz powiedzieć ile już naprawiliśmy takich wywołanych przez EasyPrivacy (raczej to jakieś efekty uboczne webmasterów / nieoczekiwane działanie).

**Comment by gargaamel** [comment]
Dalej twierdzisz, że to nie bug EasyPrivacy: https://github.com/MajkiIT/polish-ads-filter/issues/9621#issuecomment-438220129
