### ISSUE TITLE
wielodzietni.org

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9032]
1) cookies 

`||ad.ipolska.pl/cookies/cookiecheck.js$script,domain=wielodzietni.org` (nie wiem czy czegoś nie uwali), w razie czego bezpieczniej tym: `wielodzietni.org##.ui-pnotify`

2) reklama i puste kontenery po reklamach `wielodzietni.org##[id^="reklama-"]`

![ss1](https://user-images.githubusercontent.com/43844449/46808368-794c3680-cd6c-11e8-9315-5e57f9719f25.png)

**Comment by krystian3w** [comment]
Raczej nie uwali, to nie skrypt bezpośrednio silnika forum.
