### ISSUE TITLE
chojnow.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9034]
rodo / polityka

![ss1](https://user-images.githubusercontent.com/43844449/46810204-6b001980-cd70-11e8-908d-662b7265ae10.png)

Można spróbować tak: `chojnow.pl##+js(abort-on-property-read.js, confirm)` - działać działa, tylko może uwalić inne podobne komunikaty (jeśli są na stronie)

**Comment by hawkeye116477** [comment]
`chojnow.pl##+js(abort-current-inline-script.js, confirm, rodoConfirm)`

**Comment by kulfoon** [comment]
Racja, zapomniałem.

**Comment by kulfoon** [comment]
@xxcriticxx, zła etykieta, komunikat dotyczy RODO a nie cookies.

**Comment by xxcriticxx** [comment]
@kulfoon just for you!

**Comment by krystian3w** [comment]
Jeszcze by można usuwać labele by stare zgłoszenia były czyste.
