### ISSUE TITLE
fm.tuba.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#9037]
### Zrzut ekranu
![screenshot_20181011_184845](https://user-images.githubusercontent.com/19818572/46820376-5595ea00-cd86-11e8-8290-6988afd91565.png)

### Link bezpośredni
`http://fm.tuba.pl/play/41216/4/radio-tuba-top-hits?&void=42`

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wybierz jakieś radio z głównej.
2. Poczekaj aż się załaduje.
3. Looknij, pojawił się sweetaśny komunikat :smiley:

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Próbowałem Nano Defender, ale on też najwyraźniej niezbyt sobie z tym radzi.

**Comment by krystian3w** [comment]
U mnie pomogło tylko "`generichide`", ale wtedy trzeba nowe metody na blokady reklam, bo wyciekają na maksa.

Plik `adblockDetector.js` też nie bardzo jestem w stanie dobrze zrozumieć - co on sprawdza sieciowego lub jak go przerwać.

**Comment by hawkeye116477** [comment]
A to ciekawe, bo u mnie nie pomaga generichide.

**Comment by hawkeye116477** [comment]
U mnie nic nie wycieka, ale ten detektor też musi być odblokowany, bo inaczej nadal wywala komunikat. No i zdaje się, że tak też będzie ok:
```
fm.tuba.pl#@#.pub_300x250
fm.tuba.pl#@#.pub_300x250m
fm.tuba.pl#@#.pub_728x90
fm.tuba.pl#@#.text_ad
fm.tuba.pl#@#.text-ad
fm.tuba.pl#@#.textAd
fm.tuba.pl#@#.text-ad-links
fm.tuba.pl#@#.text_ads
fm.tuba.pl#@#.text-ads
@@||fm.tuba.pl/adblockDetector.js
```

**Comment by krystian3w** [comment]
Jeszcze ubić reklamę promocji bezdomki, bo to nie leci na żywo i utwory na kilku kanałach lecą losowo.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/46830696-b8e14580-cda1-11e8-9a67-56990012e437.png)
