### ISSUE TITLE
kiep.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9038]
2 x resztka / napis po reklamach, po prawej i na dole

```
www.kiep.pl###cright > div:nth-of-type(3) > div > .btitemp
www.kiep.pl##div:nth-of-type(12) > .btitemp
```

1
![ss1](https://user-images.githubusercontent.com/43844449/46822449-cd1a4800-cd8b-11e8-98b8-0dd7fbb73f5f.png)

2
![ss2](https://user-images.githubusercontent.com/43844449/46822451-cd1a4800-cd8b-11e8-8f08-bb94436ebc33.png)

**Comment by MajkiIT** [comment]
@kulfoon u mnie tego nie ma

**Comment by kulfoon** [comment]
@MajkiIT tej pierwszej też u mnie nie ma, ale ta druga na dole dalej jest.
