### ISSUE TITLE
stooq.com

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#904]
Reklama na http://stooq.com/

![image](https://cloud.githubusercontent.com/assets/11742596/15370470/7d4ed2fc-1d37-11e6-9bf1-2488e42898b4.png)

Na przykład coś takiego
`stooq.com##[onclick*="http://stooq.com/ads/"]`
`stooq.com##a[href^="ads/f/"]`

**Comment by MajkiIT** [comment]
dziękuję
