### ISSUE TITLE
psychiatria.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9041]
rodo / polityka / cookies

![ss1](https://user-images.githubusercontent.com/43844449/46823711-351e5d80-cd8f-11e8-9a38-c43d21574dc1.png)

**Comment by xxcriticxx** [comment]
kto jest pierwszy w kolejce?

**Comment by krystian3w** [comment]
`||static.medforum.pl/portale/vendors/jquery.cookie/jquery.cookie.js` ale nie jest to bezpośrednio plik z rodo - on tylko ma pomóc sprawdzić ciastekcza.
