### ISSUE TITLE
filman.cc

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9044]
cookies

W ramach naszej strony stosujemy pliki cookies w celu świadczenia usług na najwyższym poziomie. Korzystanie z witryny bez zmiany ustawień cookies oznacza, że będą one zamieszczane w Twoim urządzeniu końcowym. Możesz w każdym czasie dokonać zmiany ustawień dotyczących cookies.

**Comment by krystian3w** [comment]
`###cookies > div` / `###cookies > .container`

bo zostaje brzydka kreska i nie wiem skąd ona jest.

**Comment by krystian3w** [comment]
Namierzyłem kreskę, pochodzi od stopki, ale co robi w nagłówku...

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/ac09a2ef15992ff88b5f2f5c9761152f502d2f07/cookies_filters/adblock_cookies.txt#L288
