### ISSUE TITLE
swiatebookow.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9047]
Ukrywa logowanie przez Facebooka
https://www.swiatebookow.pl/login/?next=/
![opera zdjecie_2018-10-12_015119_www swiatebookow pl](https://user-images.githubusercontent.com/36385327/46840035-6c0d6700-cdc1-11e8-8c8b-9f019e57600d.png)

**Comment by krystian3w** [comment]
```
! 12.10.2018, 10:10:25 https://www.swiatebookow.pl/login/?next=/
www.swiatebookow.pl#@#.fa-facebook-official.fa
www.swiatebookow.pl#@#.facebook-button
www.swiatebookow.pl#@#.fa-facebook
www.swiatebookow.pl#@#.social-label
```
