### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#905]
Żuber :stuck_out_tongue_winking_eye: na wykopie - http://www.wykop.pl/

![image](https://cloud.githubusercontent.com/assets/11742596/15370625/17c3b7b2-1d38-11e6-9f0f-d22fa283b0fd.png)

Może coś takiego?
`||*wykop.pl/static/nowywykoppl/css/prawykop.css$stylesheet`

**Comment by MajkiIT** [comment]
dziękuję. Jutro dodam do filtrów.

**Comment by xxcriticxx** [comment]
@F4z  masz cos na cookie na wykop.pl?

 widze ze u ciebie na screenshotcie niema alertu.

**Comment by F4z** [comment]
@xxcriticxx korzystam z Adguarda w wersji na Windowsa (nie jako rozszerzenie do przeglądarki, tylko jako program) i on ma tam odpowiednie reguły, które ukrywają ten komunikat o ciasteczkach.

Swoją drogą, zawsze można go zamknąć krzyżykiem i też nie będzie widoczny :stuck_out_tongue_closed_eyes:

**Comment by F4z** [comment]
Dzięki za aktualizację filtrów, na stronie głównej wykopu nie ma już żubra, ale nadal go mam przy logowaniu - https://www.wykop.pl/zaloguj/

![image](https://cloud.githubusercontent.com/assets/11742596/15389420/16ac38a2-1db7-11e6-8ee4-a78b423a8998.png)

**Comment by MajkiIT** [comment]
Dzięki za info. Poprawiłem. Moja wina. Przepraszam.

**Comment by F4z** [comment]
Nic nie szkodzi, dzięki :smiley:

**Comment by F4z** [comment]
Od dzisiaj przez tę regułę `*wykop.pl/static/nowywykoppl/js/visual.script.js$script` belka na górze strony jest u mnie niewidoczna.

Z regułą:
![image](https://cloud.githubusercontent.com/assets/11742596/15465658/03883b82-20d6-11e6-9631-fd145f45d333.png)

Bez tej reguły:
![image](https://cloud.githubusercontent.com/assets/11742596/15465541/4e7823f6-20d5-11e6-925d-9f284df1f1eb.png)

**Comment by MajkiIT** [comment]
poprawione dziękuję.
