### ISSUE TITLE
dieroten.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9058]
Resztka / napis po reklamie bielizny damskiej: `www.dieroten.pl##.col-sm-12.col-md-8 > div:nth-of-type(3)`

https://www.dieroten.pl/art/show/huebner-rebic-marzyl-aby-wspolnie-z-kovacem-pojsc-do-fcb/28602

![ss1](https://user-images.githubusercontent.com/43844449/46888681-78e19780-ce61-11e8-8f95-5eee37e10cbf.png)

**Comment by kulfoon** [comment]
``

**Comment by AarmsS** [comment]
Podana reguła powoduje problemy z prawidłowym wyświetlaniem wszystkich komentarzy.
https://github.com/MajkiIT/polish-ads-filter/issues/9285
