### ISSUE TITLE
Tracker: meblem4.pl savecart.pl

### ISSUE THREAD

**Issue by trackerless** [MajkiIT/polish-ads-filter#9064]
### Link bezpośredni

https://meblem4.pl/podnozek-do-fotela-uszak,id8055.html
http://savecart.pl
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1.  wejdź na stronę
2. włącz narzędzia developerskie
3.  sprawdź Network

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Pull request: https://github.com/MajkiIT/polish-ads-filter/pull/9063/commits/b3d5c5581ab6d3e9ce543031ce06077d74a127b3

Nie dodaję third-party, bo używają trackera również na swojej stronie.
Testowane, nie blokujemy im nic poza zbieraniem danych.

**Comment by hawkeye116477** [comment]
W takim razie to raczej do `https://github.com/olegwukr/polish-privacy-filters`.

**Comment by krystian3w** [comment]
Gazeta wyborcza też śledzi 1 px gifem w ajaxie.

Ale teraz nie mam jak go namierzyć - nie załadowuje się.

**Comment by MajkiIT** [comment]
@hawkeye116477 On się chyba poddał. Przydało by się kogoś złapać i aby kontynuował dzieło.

**Comment by xxcriticxx** [comment]
@MajkiIT maybe @kulfoon pociagnie dalej?

**Comment by trackerless** [comment]
Znaleziono tutaj na przykład:
||p.gazeta.pl

**Comment by kulfoon** [comment]
Z https://github.com/MajkiIT/polish-ads-filter/issues/9026#issuecomment-429606968 :

> @kulfoon: skopiować te filtry prywatności do polskiego repo i niech @trackerless je prowadzi

@trackerless chcesz prowadzić filtry prywatności na polskim repo?

**Comment by kulfoon** [comment]
No to git majonez :)

**Comment by hawkeye116477** [comment]
Te opcje raczej odpadają ze względów prawnych.
A z tego co teraz widzę, to repo olega ponownie ruszyło.

**Comment by kulfoon** [comment]
Rozumiem, że jednak znowu ruszyło, a hipotetycznie gdyby nie ruszyło, to w co wchodziło w opcje, a dokładniej co miano na myśli poprzez "kogoś złapać i aby kontynuował dzieło" i "pociagnie dalej?" ?), czy chodziło o to, że @trackerless (albo ktoś inny) miałby sforkować repo i u siebie prowadzić samodzielnie?
