### ISSUE TITLE
finanse.rankomat.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9075]
Cookies
https://finanse.rankomat.pl
https://sowafinansowa.pl
https://komorkomat.pl
https://wakacyjnapolisa.pl
https://wypowiadamoc.pl
https://autoumowa.pl
![opera zdjecie_2018-10-14_050337_finanse rankomat pl](https://user-images.githubusercontent.com/36385327/46912175-8f294980-cf6e-11e8-8ccc-a9a20af54cee.png)

Social
https://autoumowa.pl
![opera zdjecie_2018-10-14_050417_autoumowa pl](https://user-images.githubusercontent.com/36385327/46912180-a0725600-cf6e-11e8-99de-60bc2929c014.png)

**Comment by krystian3w** [comment]
Z tej stopki to mogę wyciąć, ale dziwne wygląda, zamazać można białym kwadratem z CSS, ale to się na 90% będzie rozjeżdżać.

Niby można z linka usunąć tag href, ale Firefox lub Chrome strajkowały (np. też nie usuwają id i class a na innym silniku już tak - jakiś bug?)...
