### ISSUE TITLE
wxv.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9082]
reklama czy reklama wewn. ?

![ss1](https://user-images.githubusercontent.com/43844449/46915778-9a9d6480-cfb0-11e8-94a8-b6276daf793c.png)

**Comment by krystian3w** [comment]
Jak dla mnie zewnętrzna, nawet jakby stawiali stronę na hekko.pl, raczej ich hekko do marketingu na siłę nie potrzebuje.
