### ISSUE TITLE
auto-motor-i-sport.pl (2)

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9089]
Reopen https://github.com/MajkiIT/polish-ads-filter/issues/9072 bo:
- dalej są niektóre resztki / napisy po reklamach:

### 1
![ss1](https://user-images.githubusercontent.com/43844449/46918313-26bf8400-cfd1-11e8-9779-3da9752fc10a.png)

### 2
![ss2](https://user-images.githubusercontent.com/43844449/46918314-26bf8400-cfd1-11e8-9748-3d9eb0352e87.png)

- jak pisałem, ogólnie resztki / napisy są nie tylko na `auto-motor-i-sport.pl`, ale też na kilku innych domenach bliżniaczych ("poddomenach"):

https://www.menshealth.pl/
https://www.womenshealth.pl/
http://www.runners-world.pl/
https://www.motocykl-online.pl/

na które to domeny odsyła `auto-motor-i-sport.pl` oraz wszystkie te domeny do siebie nawzajem za pomocą przycisków w swoim menu:

![ss3](https://user-images.githubusercontent.com/43844449/46918357-ac433400-cfd1-11e8-9eb0-0e59a9d6c203.png)

- jak już pisałem trzeba utworzyć najlepiej jeden wspólny filtr (jeśli się da) dla wszystkich tych domen oraz sprawdzić, czy gdzieś nie wycina za dużo.

**Comment by krystian3w** [comment]
`##[style="display:block;font-size: 14px;font-weight: 700;color: #999;text-align: left;max-width: 1130px;margin:auto;padding:0 0 10px"]`

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję
