### ISSUE TITLE
youtubehosts.txt

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9094]
@MajkiIT testowales?

**Comment by MajkiIT** [comment]
@xxcriticxx Testuje, ale to wydaje się lepsze 
https://raw.githubusercontent.com/CitizenXVIL/Hosts/master/Youtube%20hosts.txt

**Comment by xxcriticxx** [comment]
@MajkiIT ja nigdy nie mialem dobry rezultatow z tymi listami

**Comment by xxcriticxx** [comment]
@MajkiIT nie lepjej to teraz regexem zrobic?

**Comment by MajkiIT** [comment]
@xxcriticxx lepiej ale chcę mieć pewność, że te listy działają i na ich podstawie budować regex.

**Comment by xxcriticxx** [comment]
@MajkiIT toc miales 6 letniego asystenta ostatnio
