### ISSUE TITLE
forum.dobreprogramy.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9096]
RODO

https://forum.dobreprogramy.pl/t/router-blokuje-strony/428612

![capture](https://user-images.githubusercontent.com/15007183/47083232-fc8ee180-d1dd-11e8-8aa4-86f421ab7853.PNG)

**Comment by krystian3w** [comment]
@hawkeye116477  `pl##:not(input)[id*="Cookie"]` to wyparowało już?

a na listę można pod forum przywrócić stare `###rodoCookie`, do momentu aż WP nie przejmie dla siebie forum.
