### ISSUE TITLE
wififorum.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9097]
cookies

https://www.wififorum.pl/forum/16-access-pointy-i-routery/

Informujemy, że przechowujemy na Państwa urządzeniu dane potrzebne do korzystania z naszego serwisu internetowego. W danych tych zawarta jest informacja pozwalająca na rozróżnianie osób przeglądających nasze strony (tzw. ciasteczko sesyjne), o preferencjach, np. wybranym języku i do celów statystycznych. Mogą Państwo na to zezwolić lub tego zabronić w ustawieniach używanego oprogramowania (opcja "cookies" lub "ciasteczka"). Jeśli zdecydują się Państwo na blokowanie zapisu tych danych, serwis może nie działać prawidłowo.

**Comment by krystian3w** [comment]
`###CookieInfo`
