### ISSUE TITLE
tp-link.com/pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9099]
cookies

https://www.tp-link.com/pl/faqs.html

![capture](https://user-images.githubusercontent.com/15007183/47083615-2c8ab480-d1df-11e8-9483-a288af664a10.PNG)

**Comment by krystian3w** [comment]
I jeszcze brzydkie po angielsku!

**Comment by xxcriticxx** [comment]
@krystian3w ja mam browser na inglish ustawiony :)

**Comment by krystian3w** [comment]
Ja nie, dali ciała z tłumaczami / webmasterem.
