### ISSUE TITLE
mobilet.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9101]
![opera zdjecie_2018-10-17_175754_www mobilet pl](https://user-images.githubusercontent.com/36385327/47099728-355aa500-d236-11e8-97ec-bc4b95240f5c.png)

**Comment by krystian3w** [comment]
`mobilet.pl##.popmake-overlay`
`mobilet.pl#$#.pum-overlay { overflow: auto !important;}`
