### ISSUE TITLE
skycashdlafirm.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9103]
![opera zdjecie_2018-10-17_180010_skycashdlafirm com](https://user-images.githubusercontent.com/36385327/47099885-8cf91080-d236-11e8-9b85-24725d756efe.png)

**Comment by krystian3w** [comment]
"LinkedIn", no dobra będzie do wycięcia - Fanboye wycinają.

`##.footer_soc_icon` - nie widzę, by tam był RSS.
