### ISSUE TITLE
polsatnews.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9105]
http://www.polsatnews.pl
![opera zdjecie_2018-10-17_180559_www polsatnews pl](https://user-images.githubusercontent.com/36385327/47100228-540d6b80-d237-11e8-934f-d5dc1f6a1735.png)

http://www.polsatnews.pl/wiadomosc/2018-10-17/zniknela-tablica-z-nazwiskiem-tuska-wiszaca-w-polskim-przedstawicielstwie-w-brukseli/?ref=slider
![opera zdjecie_2018-10-17_180624_www polsatnews pl](https://user-images.githubusercontent.com/36385327/47100242-5ff92d80-d237-11e8-96c6-898e37412669.png)

**Comment by krystian3w** [comment]
OK, to jeszcze pomyślę czy może nie przejść na klasy, niby każdy ma swoją.
