### ISSUE TITLE
leftlane.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9106]
![opera zdjecie_2018-10-17_184024_leftlane pl](https://user-images.githubusercontent.com/36385327/47102118-27a81e00-d23c-11e8-90ff-f473d86112a6.png)

**Comment by krystian3w** [comment]
`##a[href="//www.youtube.com/c/LeftlanePl"], a[href="//www.instagram.com/leftlanepl/"], a[href="//web.facebook.com/leftlanepl/"]`
