### ISSUE TITLE
infoplanet.pl/pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9107]
Reklamy
https://infoplanet.pl/pl/

https://infoplanet.pl/pl/news/portal/polska/wydarzenia/polska-predkosc-zguba-polakow/
![opera zdjecie_2018-10-17_184219_infoplanet pl](https://user-images.githubusercontent.com/36385327/47102214-65a54200-d23c-11e8-9aea-3c02809107f3.png)

**Comment by MajkiIT** [comment]
@KonoromiHimaries twoje
