### ISSUE TITLE
innpoland.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9108]
https://innpoland.pl/147009,stylistyka-zywnosci-i-food-porn-coraz-bardziej-popularny-w-restauracjach
![opera zdjecie_2018-10-17_184607_innpoland pl](https://user-images.githubusercontent.com/36385327/47102400-f11ed300-d23c-11e8-9457-c0e874eae09c.png)

**Comment by krystian3w** [comment]
`##.art__body__instagram-container`
