### ISSUE TITLE
kisiel.wprost.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9109]
Włączony
![opera zdjecie_2018-10-17_185132_kisiel wprost pl](https://user-images.githubusercontent.com/36385327/47102717-ba958800-d23d-11e8-87d6-523d1e73b2f0.png)

Wyłączony
![opera zdjecie_2018-10-17_185142_kisiel wprost pl](https://user-images.githubusercontent.com/36385327/47102720-bec1a580-d23d-11e8-9dea-490251ccc223.png)

**Comment by krystian3w** [comment]
U mnie poprawnie, nie wróciłeś do jakiegoś Annoyance Fanboya/AdGuard?
