### ISSUE TITLE
eskago.pl

### ISSUE THREAD

**Issue by gzenio22** [MajkiIT/polish-ads-filter#9114]
Adblock detect 

po odpaleniu jakiegokolwiek kanau wskakuje okno z instrukcja dezaktywacji ABP

**Comment by krystian3w** [comment]
Ja tam miałem z 3 dni temu problem i sam minął.

Wymuś aktualizacje wszystkich filtrów i uruchom ponownie przeglądarkę.

**Comment by gzenio22** [comment]
Hmmm zrobilem dokladnie to co napisales zanim wyslalem to zgłoszonko

**Comment by krystian3w** [comment]
OK, mnie to wyskakiwało nawet przez jakiś czas w czystych profilach bez dodatków.
