### ISSUE TITLE
bolec.info (2)

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9115]
Reopen https://github.com/MajkiIT/polish-ads-filter/issues/8616 bo jest błąd, niektóre filtry nie działają pod ABP, bo brakuje `?` pomiędzy `##` , odrzucony PR https://github.com/MajkiIT/polish-ads-filter/pull/9091/files naprawiał to.

**Comment by krystian3w** [comment]
Trzeba było napisać, że modyfikacja była konieczna.

**Comment by kulfoon** [comment]
To nie mój problem, wszystko jest widoczne w PR, jeśli ktoś odrzuca PR bez zaglądania do niego, to nawet nie wie co odrzuca, a jeśli nie wie co odrzuca, to nie mój problem i  pytanie dlaczego odrzuca coś o czym nie ma pojęcia.
