### ISSUE TITLE
testwiedzy.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9120]
rodo / cookies / polityka

![ss1](https://user-images.githubusercontent.com/43844449/47137917-464bfa80-d2b8-11e8-90df-213f26a96bd8.png)

**Comment by krystian3w** [comment]
Ja mam czysto, ale pewnie w trybie prywatnym wskoczy.

Potem popróbuję skryptów, bo ciężko to CSS-em usunąć.
