### ISSUE TITLE
inwestinfo.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9122]
1 cookies
2 napisy / resztki po reklamach

### 1
![ss1](https://user-images.githubusercontent.com/43844449/47138104-cbcfaa80-d2b8-11e8-851b-3cb0196f897f.png)

### 2
![ss2](https://user-images.githubusercontent.com/43844449/47138105-cc684100-d2b8-11e8-900e-e6c2b241140b.png)

**Comment by krystian3w** [comment]
`inwestinfo.pl##div[style="position:fixed;bottom:0px;width:100%;height:65px;border:#c0c0c0 1px solid; text-align:center;padding:5px;background:#e7e7e7;"]`
