### ISSUE TITLE
polnord.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9123]
cookies

![ss1](https://user-images.githubusercontent.com/43844449/47138173-f9b4ef00-d2b8-11e8-9c56-1d25f9320827.png)

**Comment by krystian3w** [comment]
`pl##:not(input)[id*=Cookie]` - wraca (w najbliższym RTM) po optymalizacji listy ogólnej, by nie były tam wpisywane wyjątki.
