### ISSUE TITLE
auto-motor-i-sport.pl (3)

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9124]
Reopen https://github.com/MajkiIT/polish-ads-filter/issues/9089, bo dalej są niektóre resztki / napisy na głównej jak i w artykułach:

0 https://www.auto-motor-i-sport.pl/ciezarowki-i-autobusy/Premierowy-dwupaliwowy-GAZelle-NEXT-CNG,35037,1
![ss5](https://user-images.githubusercontent.com/43844449/47141146-4f40ca00-d2c0-11e8-8c99-511dac2f5479.png)

1 https://www.menshealth.pl/
![ss1](https://user-images.githubusercontent.com/43844449/47140646-12280800-d2bf-11e8-88d6-dcc239f12789.png)

2 https://www.womenshealth.pl/
![ss2](https://user-images.githubusercontent.com/43844449/47140648-12c09e80-d2bf-11e8-99c5-39a42dd27caf.png)

3 https://www.runners-world.pl/
![ss3](https://user-images.githubusercontent.com/43844449/47140731-4bf90e80-d2bf-11e8-9b76-9874b711ee4d.png)

4 https://www.motocykl-online.pl/
![ss4](https://user-images.githubusercontent.com/43844449/47140820-8367bb00-d2bf-11e8-9728-39e17ef1eb60.png)

**Comment by krystian3w** [comment]
Czyli nawet stara z `style="..."` się zdezaktualizowała?
