### ISSUE TITLE
seriea.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9137]
1 reklama 
2 cookies (jak wspominał krystian3w `pl##:not(input)[id*=Cookie]` niedługo wróci)

https://www.seriea.pl/374317-luka-modric-mysli-o-transferze.html

![ss1](https://user-images.githubusercontent.com/43844449/47153876-1402c300-d2e1-11e8-9378-2f63f754311b.png)

**Comment by krystian3w** [comment]
Jak usunąłem i muszę przywrócić.

Są wyjątki pod problematyczne domeny, to szkoda by było dodawać nowe specyficzne pod polskie domeny.
