### ISSUE TITLE
miedziowe.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9143]
Wielka reklama na całą stronę

![ss1](https://user-images.githubusercontent.com/43844449/47154977-11559d00-d2e4-11e8-9713-61a3b5dbadd9.png)

**Comment by krystian3w** [comment]
i resztka czegoś po wysuwanej reklamie (tło)

![image](https://user-images.githubusercontent.com/35370833/47155955-45ca5880-d2e6-11e8-85a1-efb36694f809.png) |
--- |
