### ISSUE TITLE
gazetkonosz.pl

### ISSUE THREAD

**Issue by kulfoon** [MajkiIT/polish-ads-filter#9154]
napisy / resztki po reklamach na całej stronie

1
![ss3](https://user-images.githubusercontent.com/43844449/47156416-634bf200-d2e7-11e8-8752-b2b931e8b2e1.png)

2
![ss1](https://user-images.githubusercontent.com/43844449/47156414-634bf200-d2e7-11e8-940e-3fe293056946.png)

3
![ss2](https://user-images.githubusercontent.com/43844449/47156415-634bf200-d2e7-11e8-8eff-b3190c37c02e.png)

**Comment by krystian3w** [comment]
@xxcriticxx  otworzysz?

**Comment by gargaamel** [comment]
@MajkiIT @xxcriticxx https://github.com/uBlockOrigin/uAssets/issues/4122
