### ISSUE TITLE
kulfoon na dzisaj starczy teraz prosimy o PR

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9158]
@kulfoon prosimy o PR

**Comment by pomidoor** [comment]
> @xxcriticxx : @kulfoon prosimy o PR

1 Nie mogę bo @MajkiIT mnie zbanował przed chwilą, o czym jak widać nikogo nie poinformował, skoro o tym nie wiesz, no ale on słynie z cichych banów.

2 Nawet gdyby mnie nie zbanował to on zabronił mi robić PR i ograniczył mnie do zgłoszeń, o czym doskonale wiesz, więc dziwi mnie wasza prośba o PR, po tym jak PR zostały mi zabronione, ale rozumiem, że to taki dowcip.


https://github.com/MajkiIT/polish-ads-filter/issues/9157#issuecomment-431008496

> MajkiIT @kulfoon po złości ?

Nie, to nie było ze złości, ani wtedy co tyle nazgłaszałem, ani teraz, po prostu jestem uzależniony od githuba / od filtrów i jeśli nie zażyję odpowiednio dużej dawki, to się męczę jak na głodzie, bana się spodziewałem, tylko nie spodziewałem się, że nawet nie dasz mi odpowiedzieć na pytanie które mi zadałeś (ban), więc nasuwa się wniosek po co je zadałeś, skoro wiedziałeś, że nie będę mógł na nie odpowiedzieć, czyżby to było pytanie retoryczne, ale w ten sposób sugerujesz ludziom nieprawdę, bo to nie było po złości, jestem łagodny jak baranek, jestem uzależniony.

pozdro chłopaki! 

![](https://memotywatory.pl/upload/64d07c3292db31d21caceeeec8417e96.jpg)

**Comment by MajkiIT** [comment]
@pomidoor bo zobaczyłem twoje wypociny na mój temat.

**Comment by pomidoor** [comment]
@MajkiIT po pierwsze lepsze moje "wypociny", niż twoja niemota, a po drugie co zrobiłeś i z powodu których wypocin, bo nie łapię do czego się odnosisz.

**Comment by klakieer** [comment]
@MajkiIT, 
dziwnie i chamsko się zachowujesz, najpierw rozpoczynasz ze mną rozmowę i coś do mnie piszesz, a gdy ja zwyczajnie pytam o co ci chodziło i sie z tobą absolutnie nie kłócę (bo napisałeś w niejasny sposób) to zamiast odpowiedzieć jak człowiek i dokończyć jakoś rozmowę, to nagle **po złości** przerywasz rozmowę, którą sam rozpoczęłeś ze mną, zamykasz wątek i wlepiasz mi kolejnego bana, zachowując się po prostu jak jakiś pedał / komunistyczny prokurator, wiesz co ja ci powiem...bo ty mi zarzucałeś, że ja robię coś po złości, a ja już wyjaśniłem, że robiłem tylko dlatego bo mam słabośc do github i filtrów, natomiast  ja ci powiem tyle, że to ty robisz wiele rzeczy po złości np. tak jak teraz się zachowujesz, i to jeszcze ty lubisz komuś zarzucać, że robi coś po złości (np. mi), a sam robisz po złości, poza tym co mogę jeszcze o tobie napisać, jako admin tego repo jesteś dyktatorem i autokratą, wymuszasz wiele rzeczy siłą nie mając na to argumentów i nie podając żadnego wyjaśnienia, po prostu ignorując (zamykanie zgłoszeń pomimo, że dalej są resztki / napisy po reklamach na stronie, zamykanie wątków bez słowa, odrzucanie PR bez słowa, nieodpowiadanie na wiele kwestii, wliczając w to takie, które sam poruszyłeś np. w tym wątku), jesteś po prostu bardzo złośliwy i jesteś ostatnim człowiekiem, który może komuś zarzucać złośliwość. Dalej drwisz, że moje wypowiedzi poparte solidnymi argumentami to wypociny, bo najwidoczniej nie masz żadnych kontr-argumentów na nie, więc najłatwiej wydrwić i napisać, że wypociny, z resztą jak już pisałem lepsze moje "wypociny" niż twoja zasrana niemota, jakbyś języka w gębie nie miał, albo był niedorozwinięty, a jeśli już się odezwiesz, to wydukasz i wypocisz jakieś jedno niezrozumiałe zdanie jakbyś był niedorozwinięty, ja przynajmniej umiem wypocić długą merytoryczną popartą solidnymi argumentami wypowiedź, dla ciebie to problem wypocić jedno sensowne zdanie, z resztą ty się nie musisz za bardzo pocić, po co skoro łatwiej ci się jest masturbować za pomocą przycisków w panelu admina "ban", "odrzucenie PR", "zamknięcie zgłoszenia", "zamknięcie wątku", jak milicjant, który bije i ucisza pałką bo nie ma innych argumentów, ja takich możliwości nie posiadam, więc muszę nadrabiać wypowiedziami, (które nazywasz wypocinami), tak jak ci, którzy idą na marszu wolności i skandują hasła, broniąc się przed złym rządem, ale pewnie wg ciebie to są tylko jakieś ich wypociny, a rząd jest wspaniały i uczciwy. Zapamiętaj jedno, za to jak się zachowujesz, (wiem, że nie jestem święty) ale to co ty wyprawiasz jest jeszcze bardziej podłe, mam nadzieję, że wszyscy po kolei się od ciebie odwrócą jeden po drugim i, że zostaniesz na tym repo sam, i nie nazywaj tego repo publicznym, bo uprawiasz tu swoją dykatutrę ,autokrację i prywatę, jak już pisałem bez powodu i wyjaśnienia odrzucasz PR, zamykasz zgłoszenia i wątki, nie odpowiadasz na wązne kwestie, ignorujesz, nie dopuszczasz do listy, wymuszasz wszystko siłą bo na nic nie masz argumentów. Nienawdzidziłem cię od pierwszego momentu od kiedy tu się pojawiłem kilka lat temu, bo odrazu wyczułem, że zwyczajnie śmierdzisz jak końskie góówno, mam nosa do ludzi i wyczuwam ścierwo na kilometr, ścierwo które na pozór jest miłe (słownie), ale to tylko taka maska na pokaz, bo za nią ukrywa się komunistyczna gnida, która wymusza posłuszeństwo pałką i masturbuje się przyciskami w panelu admina. Ludzi, którzy tu są traktujesz jak niewolników i murzynów, trzymasz wszystkich uwiązanych w kagańcu i na smyczy, jak psy, traktujesz ludzi jak bydło, nie wiem, może oni lubią być tak traktowani, ale nie ja. najprawdopodobniej jesteś zbyt głupi i ograniczony, żeby zrozumieć moją bogatą wypowiedź, która świadczy tylko o tym, że mam coś w głowie, w przeciwieńśtwie do ciebie, bo masz tam tylko balon, i umiesz napisać zdanie pokroju "ala ma kota", gratulacje ileż musisz się napocić, żeby takie zdanie skonstruować, zastanawiam się czy z takim zasobem umysłowym potrafisz książkę przeczytać, albo chociaż instrukcję od TV, to chyba już małpa jest bardziej rozwinięta.

Tak tak, możesz to znowu wydrwić i nazwać to wypocinami, elaboratem, albo ja też cię kocham, albo wyznaniem miłości itp możesz to strolować itp. ale podsumuję cię krótko i dam ci taką skróconą wersję w razie jeślibyś był niedorozwinięty i tej pełnej nie umiał zrozumieć i piszę to zupełnie na spokojnie, nie po złości, po prostu trzeba żeby ktoś to w końcu napisał: jesteś zwykłym śmierdzącym końskim panoszącym się gównem, a argumenty znajdziesz w tej dłuższej wersji, nara pedale.

**Comment by KonoromiHimaries** [comment]
@klakieer nie możemy pracować z tobą gdy tak się zachowujesz, pisałeś że jesteś inteligentny więc udowodnij to i zacznij zachowywać się w sposób odpowiedzialny.

pisałeś że majki jest autokratą, bo rości sobie prawa do zachowania odpowiedniej kultury na jego własnym repo i że ja go w tym popieram. no cóż, to prawda i nie widzę nic w tym złego.
