### ISSUE TITLE
jezykipodroze.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9161]
![opera zdjecie_2018-10-19_125810_jezykipodroze pl](https://user-images.githubusercontent.com/36385327/47214580-a61cd100-d39e-11e8-9881-2a11a6f5ec90.png)

**Comment by krystian3w** [comment]
`##.widgets-5.widgets-list`

**Comment by krystian3w** [comment]
chyba już go nie mają, teraz jakaś cookies katapulta
