### ISSUE TITLE
zadluzenia.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9163]
![opera zdjecie_2018-10-19_130154_www zadluzenia com](https://user-images.githubusercontent.com/36385327/47214732-2c391780-d39f-11e8-86dc-4f727c87b6f7.png)

**Comment by krystian3w** [comment]
`##.footer > .container > .row > div.col-sm-3:nth-of-type(4)`

**Comment by krystian3w** [comment]
`zadluzenia.com###CookiesInfo`
