### ISSUE TITLE
opony.net

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9192]
![opera zdjecie_2018-10-19_162702_www opony net](https://user-images.githubusercontent.com/36385327/47224465-dd4dab00-d3bb-11e8-896a-43b9232b915b.png)

**Comment by krystian3w** [comment]
`opony.net###cookiefy_bar`

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/ffc95e6bc0272fc49efc7225a086cc2dd8e80257/cookies_filters/adblock_cookies.txt#L825
