### ISSUE TITLE
infobus.pl

### ISSUE THREAD

**Issue by klakieer** [MajkiIT/polish-ads-filter#9193]
jakiś nagłówek / resztka i tło po jakimś komunikacie, po wyłączeniu POL listy coś tam wyskakuje, po włączeniu znowu ta resztka

![ss1](https://user-images.githubusercontent.com/44292328/47224659-577e2f80-d3bc-11e8-9fe2-cbfa5b94e47e.png)

**Comment by krystian3w** [comment]
Czas na cyfrowy detkos, nie mamy takiej mocy przerobowej by bardzo dobrze przeanalizować - AdGuard na przykład przeklikuje wszystkie linki by wyciąć tylko konkretny pop-up a nie rozwalić stronę.
