### ISSUE TITLE
abfoto.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9197]
![opera zdjecie_2018-10-19_181458_abfoto pl](https://user-images.githubusercontent.com/36385327/47230583-e85c0780-d3ca-11e8-8593-e3d1e5c07955.png)

**Comment by krystian3w** [comment]
`abfoto.pl##.abfoto_popup_bg`

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/ffc95e6bc0272fc49efc7225a086cc2dd8e80257/cookies_filters/adblock_cookies.txt#L31
