### ISSUE TITLE
ironsky.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9210]
![opera zdjecie_2018-10-20_002606_ironsky pl](https://user-images.githubusercontent.com/36385327/47246557-ca0fff00-d3fe-11e8-9c5b-a042b1b5e3fe.png)

**Comment by krystian3w** [comment]
Newsletter?

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/47252864-afb04280-d44b-11e8-8dc0-530651456598.png) |
--- |
