### ISSUE TITLE
poradnikzdrowie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9211]
https://www.poradnikzdrowie.pl/zdrowie/laryngologia/najlepsze-domowe-sposoby-na-bol-gardla-i-chrypke-aa-zBtM-WWjE-9M9Z.html
![opera zdjecie_2018-10-20_002701_www poradnikzdrowie pl](https://user-images.githubusercontent.com/36385327/47246584-f297f900-d3fe-11e8-9e3d-90c0b58a63db.png)
![opera zdjecie_2018-10-20_002714_www poradnikzdrowie pl](https://user-images.githubusercontent.com/36385327/47246585-f297f900-d3fe-11e8-8d52-0dc32c692231.png)

**Comment by krystian3w** [comment]
Na telefonie od dawna nie działało wideo, jakby i ten anty-adblock dało się naprawić to było by fajnie.
Nie wiem czy mobilnego nie generuje lista pod mobilne reklamy AdGuarda.
