### ISSUE TITLE
topshop.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9212]
http://www.topshop.pl
http://www.mango.pl
http://www.dormeo.pl
http://www.delimano.pl
http://www.walkmaxx.pl
![opera zdjecie_2018-10-20_003056_www topshop pl](https://user-images.githubusercontent.com/36385327/47246661-6df9aa80-d3ff-11e8-9dd3-a633d602ac9c.png)

**Comment by krystian3w** [comment]
```
topshop.pl,dormeo.pl,delimano.pl,walkmaxx.pl##.fn-social
www.mango.pl##.fn-social > ul > li:nth-of-type(n+2)
```

**Comment by krystian3w** [comment]
Inspiracje na mango to nie social więc nie wycinam.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/ffc95e6bc0272fc49efc7225a086cc2dd8e80257/adblock_social_filters/adblock_social_list.txt#L2206

https://github.com/MajkiIT/polish-ads-filter/blob/ffc95e6bc0272fc49efc7225a086cc2dd8e80257/adblock_social_filters/adblock_social_list.txt#L1465
