### ISSUE TITLE
trojmiasto.tv

### ISSUE THREAD

**Issue by salionPL** [MajkiIT/polish-ads-filter#9213]
### Wyświetla się info o adbocku.

![screenshot_2018-10-20 nocny pozar samochodu na siedlcach](https://user-images.githubusercontent.com/38588787/47254062-aa0f2880-d45c-11e8-9de0-ad0d281cf656.png)

**Adres strony:** https://trojmiasto.tv/Nocny-pozar-samochodu-na-Siedlcach-30322.html

**Moja konfiguracja:**

Windows 10 [64bit]
Firefox 62.0.3 [64bit]
uBlock Origin 1.17.2

**Moje listy filtrów:**
<details>

![filtry](https://user-images.githubusercontent.com/38588787/46001848-b3e77b00-c0ac-11e8-8bea-8d49d88b01ba.png)
</details>

**Comment by krystian3w** [comment]
U mnie nie:

time  | | filter |   | type | where find
-- | -- | -- | -- | -- | --
12:34:36 |   | `@@/advertisement*.js$first-party,script` | ++ | script | `https://trojmiasto.tv/_js/advertisement.el.js?80951.14`
12:34:36 |   | `@@/advertisement*.js$first-party,script` | ++ | script | `https://trojmiasto.tv/_js/advertisement.js?80951.14`

**Comment by salionPL** [comment]
Jest już filtr na to, tylko że dla trójmiasto.pl (trojmiasto.pl###block_info_wrap).

Trzeba więc dodać taki sam ale z końcówką .tv

Czyli: `trojmiasto.tv###block_info_wrap`

**Comment by krystian3w** [comment]
A co kto woli, niby można wycinać jak nie uszkadzają strony by tylko włączyć reklamy.
