### ISSUE TITLE
trojmiasto.pl/kamery

### ISSUE THREAD

**Issue by salionPL** [MajkiIT/polish-ads-filter#9214]
### Błędy wyświetlania i brak wszystkich obrazków.
![screenshot_2018-10-20 portal trojmiasto pl](https://user-images.githubusercontent.com/38588787/47254886-12afd280-d468-11e8-91a4-8cc562240a19.png)

Adres strony: https://www.trojmiasto.pl/kamery/

**Moja konfiguracja:**

Windows 10 [64bit]
Firefox 62.0.3 [64bit]
uBlock Origin 1.17.2

**Moje listy filtrów:**
<details>

![filtry](https://user-images.githubusercontent.com/38588787/46001848-b3e77b00-c0ac-11e8-8bea-8d49d88b01ba.png)
</details>

**Comment by krystian3w** [comment]
@MajkiIT `www.trojmiasto.pl#@#A[target="_blank"] > IMG`

I by trzeba w sumie przeprogramować starą regułę jak to wycinało jakieś reklamy i dalej je wycina.
