### ISSUE TITLE
dziennikwschodni.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#9215]
![obraz](https://user-images.githubusercontent.com/35370833/47255141-9966ae80-d46c-11e8-9a0b-9191007939b8.png) |
--- |

Niby pomaga dopuszczenie obrazków z nawigacji np. ikona usera.

`@@?ads=$image,first-party,domain=dziennikwschodni.pl`

Nie sprawdzałem czy Chrome wymaga dodatkowych reguł lub jak to dezaktywować np. wstrzykiwaniem skryptów w uBlock Origin.

**Comment by krystian3w** [comment]
`dziennikwschodni.pl##.adblock-article` - niby chyba nic skrypt nie psuje i tylko komunikat wyświetla.

**Comment by blocker999** [comment]
#9160
