### ISSUE TITLE
darmowyskin.pl

### ISSUE THREAD

**Issue by klakieer** [MajkiIT/polish-ads-filter#9216]
Anty-adblock

<details>
  <summary>Komunikat 1</summary>

![ss1](https://user-images.githubusercontent.com/44292328/47255978-cf119480-d478-11e8-8d00-c1b3d14658cc.png)

</details>
.

Po wciśnięciu OK przekierowuje do http://darmowyskin.pl/index.php/Home/blokada i pokazuje następny komunikat:

<details>
  <summary>Komunikat 2</summary>

![ss2](https://user-images.githubusercontent.com/44292328/47255979-cf119480-d478-11e8-85fe-f52feaa8451b.png)

</details>
.

Można dodać wyjątek:

`vorek.pl,gryplanszowe.pl,darmowetorenty.pl,torrentcity.pl,bitnova.info,waw4free.pl,darmowyskin.pl#@#.adsbox` ale wtedy zostaje taka biała kreska

<details>
  <summary>Kreska</summary>

![ss3](https://user-images.githubusercontent.com/44292328/47255980-cf119480-d478-11e8-99d1-4a1495ee5662.png)

</details>
.

Więc można dodać dodatkowo:
`darmowyskin.pl##.adsbox:style(background-color: black;) ` żeby ta kreska zrobiła się czarna i zlała z tłem, wtedy jest niewidoczna (tylko, że jeśli ktoś ma jakieś dodatki np. stylish albo po prostu ma ustawione tło na inny kolor, to może dalej być widać) no chyba, że ta kreska nikomu nie przeszkada.

Albo takie rozwiązanie:
`darmowyskin.pl##+js(setTimeout-defuser.js, adsbox)`

**Comment by krystian3w** [comment]
`darmowyskin.pl##.adsbox:style(background-color: transparent !important;)`

Lepsze pod tych co by sobie modyfikowali wygląd na jasny.

**Comment by klakieer** [comment]
Ja tam widzę kolor tła: `#181B22`, to co ty widzisz to raczej obrazek tła: http://darmowyskin.pl/assets/img/bg.jpg, który w  różnych miejsach ma nieco inny odcień, być może w którymś miał `#0b0b0d`.

**Comment by krystian3w** [comment]
Przecież nawigacja ma dodatkowe tło, to reklam jest pod?

**Comment by xxcriticxx** [comment]
u mnie jeszcze co innego `body style="margin: 0px; background: #0e0e0e;"`

**Comment by krystian3w** [comment]
Ale źle zbadałeś, to masz inny kod, nie mówię o tle `<body>` a tle nagłówka, pod nim jest kreska i nie ma odstępu.`

**Comment by klakieer** [comment]
> @krystian3w : Ale źle zbadałeś, to masz inny kod, nie mówię o tle <body> a tle nagłówka, pod nim jest kreska i nie ma odstępu.`

Więc się nie do końca jasno wyraziłeś, czy chodzi ci o kolor tła czy nagłówka, przez to pomyślałem, że chodzi ci o kolor tła, bo kreskę można zlać tak samo z tłem, jak i z nagłówkiem, tylko, że skoro i tak się okazało, że tam jest tło obrazkowe o różnych odcieniach, to twoja propozycja #13151a będzie lepsza.

**Comment by klakieer** [comment]
@krystian3w a może coś takiego: `darmowyskin.pl##.left:style(background-color: inherit !important;)` ?
