### ISSUE TITLE
tabakiera.com.pl 

### ISSUE THREAD

**Issue by klakieer** [MajkiIT/polish-ads-filter#9250]
Dowcip dnia - błąd w POL RODO-ciasteczkowych - wycinają przycisk "tak":

![ss1](https://user-images.githubusercontent.com/44292328/47264820-f7070380-d51d-11e8-928b-26c4e3808d77.png)

![](https://www.wroclaw.pl/go/download/img-148315022df7bd081e76ae70cd821814/pat-a-mat-2-jpg-standa-jpg.jpg)

**Comment by KonoromiHimaries** [comment]
https://www.youtube.com/watch?v=gBCcnazy88U

**Comment by klakieer** [comment]
Wszyscy Tańczymy Sambę  albo Makarenę !

**Comment by krystian3w** [comment]
Widać stronie zależało na tym by nie weszli ludzie.

`tabakiera.com.pl#@#:not(input)[id*="cookie"]`

`tabakiera.com.pl##span#cookiesClose.button` -  mogli użyć LocalStorage...
