### ISSUE TITLE
mago.com

### ISSUE THREAD

**Issue by klakieer** [MajkiIT/polish-ads-filter#9257]
rodo / polityka

![ss1](https://user-images.githubusercontent.com/44292328/47266610-59213200-d539-11e8-91fb-10e83978359f.png)

**Comment by krystian3w** [comment]
<kbd>`mago.com###yl-popup-wrapper-popupRodo, #yl-popup-shadow-popupRodo`</kbd>
<kbd>`mago.com##html:style(overflow: auto !important;)`</kbd>
