### ISSUE TITLE
supermemo.com/pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9259]
https://www.supermemo.com/pl
![opera zdjecie_2018-10-21_153921_www supermemo com](https://user-images.githubusercontent.com/36385327/47267687-8379ec00-d547-11e8-81b8-3cc5e3dddb35.png)

https://www.supermemo.pl
![opera zdjecie_2018-10-21_153947_www supermemo pl](https://user-images.githubusercontent.com/36385327/47267691-9096db00-d547-11e8-9c12-6d66d359bbcc.png)

**Comment by krystian3w** [comment]
`supermemo.com##.cookie`
`supermemo.pl##,#block-block-42 > .content > h4 #profiles`
