### ISSUE TITLE
uber.com/pl/pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9261]
https://www.uber.com/pl/pl/
![opera zdjecie_2018-10-21_154128_www uber com](https://user-images.githubusercontent.com/36385327/47267718-e4a1bf80-d547-11e8-90e8-cb67ce203147.png)

https://www.uber.com/business/?mainSite=true
![opera zdjecie_2018-10-21_154249_www uber com](https://user-images.githubusercontent.com/36385327/47267728-fbe0ad00-d547-11e8-8783-92bf0c892d24.png)

https://www.ubereats.com/pl-PL/
![opera zdjecie_2018-10-21_154329_www ubereats com](https://user-images.githubusercontent.com/36385327/47267735-1450c780-d548-11e8-9216-1486a769c4d0.png)

**Comment by krystian3w** [comment]
`uber.com##.fd.fc > .ed.fp.fo.ci, ._j4._j3._j2`
`ubereats.com##.ue-l.palm-one-whole.lap-one-half.one-third.layout__item > div:nth-of-type(2)`

A przy okazji może bym to zgłosił do Fanboya, na pewno smed lepiej wytnie.
