### ISSUE TITLE
ipla.tv

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9264]
ad block

https://www.ipla.tv/wideo/serial/Septagon/5014684/Septagon-Odcinek-29/a32ecc89926070e5e30e3157f1e8ebd9

ma ktos ad block czy tylko u mnie?

**Comment by xMaap** [comment]
![opera zdjecie_2018-10-21_163905_www ipla tv](https://user-images.githubusercontent.com/36385327/47268338-d6f03800-d54f-11e8-8d49-bc65ad92177e.png)

**Comment by xxcriticxx** [comment]
@xMaap thx

**Comment by klakieeer** [comment]
U mnie to samo co u @xMaap .

**Comment by xxcriticxx** [comment]
@klakieeer thx
