### ISSUE TITLE
videopenny.net

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9288]
https://videopenny.net/seriale-pl/pod-powierzchnia-2018/pod-powierzchnia-s01e01-odc-1-sez-1,76065,1mox
![opera zdjecie_2018-10-23_011837_videopenny net](https://user-images.githubusercontent.com/36385327/47324822-9f71b080-d661-11e8-8a79-633942a9aab9.png)

**Comment by krystian3w** [comment]
U mnie działa. Reklamy podczas odtwarzania?

**Comment by MajkiIT** [comment]
@xMaap masz uBlocka? Masz filtry Adguard włączone?

**Comment by xMaap** [comment]
@MajkiIT Nano Adblocker + Nano Defender.
![opera zdjecie_2018-10-23_105352_gabbbocakeomblphkmmnoamkioajlkfo](https://user-images.githubusercontent.com/36385327/47348536-fdc67f80-d6b1-11e8-93be-169a10f51f69.png)

**Comment by krystian3w** [comment]
A coś musi się otwierać w nowej karcie?

**Comment by xMaap** [comment]
1. Klikam aby się otworzyło.
![opera zdjecie_2018-10-23_110111_videopenny net](https://user-images.githubusercontent.com/36385327/47349105-269b4480-d6b3-11e8-9386-d5322db45307.png)
2. Wyskakuje 
![opera zdjecie_2018-10-23_110251_videopenny net](https://user-images.githubusercontent.com/36385327/47349137-3adf4180-d6b3-11e8-9f58-57385ed79ed9.png)
3. Klikam na player aby otworzyć film i otwiera się https://r.wallstrads.com/api/direct/59846?sub_id_1=1216a1bca4361c39d1d77965c5d95ee3&sub_id_2=videopenny.net

**Comment by xMaap** [comment]
Pobawiłem się i wychodzi na to, że to nie jest wina filtrów tylko skryptu od AdGuard który ma blokować... wyskakujące reklamy.
Jak wyłączyłem nawet nie myśli aby się nawet przez sekundę coś pojawiło.
https://github.com/AdguardTeam/PopupBlocker

**Comment by xxcriticxx** [comment]
Więcej narzędzi nie znaczy ze bendzie działać lepjej

@xMaap nie wiedziałem ze siedzisz w Kodi

**Comment by MajkiIT** [comment]
@F4z zerknij proszę.

**Comment by F4z** [comment]
U mnie z AdGuardem + ten skrypt żaden popup się nie pojawia, może to jakiś konflikt między uBlockiem a skryptem blokującym wyskakujące okienka.

Z uBlockiem + skrypt widzę tylko komunikat o zablokowanym popupie, więc w sumie nie wiem skąd ten problem.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/11742596/47369056-26b33880-d6e3-11e8-8fbc-b3c9b15e2eba.png)

</details>

**Comment by krystian3w** [comment]
A mój post z rzutem chyba ktoś zgłosił i wykasowali bez śladu moderatorzy githuba.

**Comment by MajkiIT** [comment]
@krystian3w @F4z Dziękuję
