### ISSUE TITLE
glamrap.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9291]
![opera zdjecie_2018-10-24_030503_glamrap pl](https://user-images.githubusercontent.com/36385327/47399628-ac61d300-d739-11e8-83d4-ff04eef0cc7b.png)

**Comment by krystian3w** [comment]
`glamrap.pl###mvp-leader-wrap`
`glamrap.pl###mvp-site-main:style(margin-top: 0 !important;)`
