### ISSUE TITLE
klubjagiellonski.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9292]
![opera zdjecie_2018-10-24_180909_klubjagiellonski pl](https://user-images.githubusercontent.com/36385327/47444992-1456fe80-d7b8-11e8-84b4-50c63661e4b9.png)

**Comment by krystian3w** [comment]
Ja bym to wyciął jako widżet irytujący, czeka aż sami klikniemy zamknij i jeszcze tam wrzucili, że niby używają cookies.
