### ISSUE TITLE
iitvx.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9298]
showmax is back

http://iitvx.pl/arrow

**Comment by MajkiIT** [comment]
@xxcriticxx chyba dzisiaj już nie ma.

**Comment by xxcriticxx** [comment]
@MajkiIT no masz racje dzisiaj tego niem ma zobaczymy jutro

**Comment by xMaap** [comment]
Już chyba jest
![opera zdjecie_2018-10-25_125454_iitvx pl](https://user-images.githubusercontent.com/36385327/47495735-32bf0780-d855-11e8-86c0-8a67d0402d80.png)

**Comment by xxcriticxx** [comment]
@xMaap podaj link please gdzie znalazles

**Comment by xMaap** [comment]
@xxcriticxx http://iitvx.pl/arrow
http://iitvx.pl/flash
http://iitvx.pl/better-call-saul
![opera zdjecie_2018-10-25_141614_iitvx pl](https://user-images.githubusercontent.com/36385327/47499569-8e42c280-d860-11e8-9c17-83a6302aeeb4.png)

**Comment by xxcriticxx** [comment]
`||track.omgpl.com/i/?CRID=175357&AID=1262703&PID=31159&WID=83305`

@MajkiIT my napewno bokujemy `track.omgpl.com` hostem

**Comment by xxcriticxx** [comment]
albo regexem `^track(ers?|ing)?[0-9]*[-.]`

**Comment by MajkiIT** [comment]
`||track.omgpl.com^$image`

**Comment by MajkiIT** [comment]
@xxcriticxx @xMaap Dziękuję
