### ISSUE TITLE
EasyPrivacy a lista RODO-Ciasteczkowa

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#9300]
Chciałbym zapytać czy uzupełniać polską listę, gdy ktoś z jakiś powodów nie używa EasyPrivacy i ono wytnie komunikat cookies.

np. `norauto.pl###privacy`, w ABP było by zalecane do momentu ręcznej subskrypcji EasyPrivacy.

**Comment by MajkiIT** [comment]
Pytanie ile jest takich przypadków.

**Comment by KonoromiHimaries** [comment]
pisałem kiedyś do gorhilla, ale odpisał że nie ma przekonujących przypadków by taka dyrektywa była rzeczywiście potrzebna
https://github.com/gorhill/uBlock/issues/3651

**Comment by krystian3w** [comment]
@MajkiIT 

Na razie taki jeden, bo sprawdzam konieczność starych reguł, gdy było zablokowane przewijanie.

```
pl##:not(input)[id*="Cookie"]:not(body):not(html):not(.fade)
pl##:not(input)[id*="cookie"]:not(body):not(html):not(.fade)
```

Filtry:

* `#@#:not(input)[id*="Cookie"]` 
* `#@#:not(input)[id*="cookie"]`

 bez `:not(body):not(html):not(.fade)` nic nie naprawiają / nie odblokowują jeśli już nie ma starszej reguły.



---

@KonoromiHimaries 

Jak dla mnie również, raczej wielkiego obciążenia nie generuje to.
