### ISSUE TITLE
polonia.nl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9302]
https://polonia.nl/2018/10/22/ferie-z-dziecmi-odwiedzcie-hage/
![opera zdjecie_2018-10-25_125748_polonia nl](https://user-images.githubusercontent.com/36385327/47495924-b7118a80-d855-11e8-96f0-6b3df1a74ed0.png)
![opera zdjecie_2018-10-25_125759_polonia nl](https://user-images.githubusercontent.com/36385327/47495925-b7118a80-d855-11e8-95e9-c8166951e13d.png)

**Comment by krystian3w** [comment]
`###pasek.cookie-bar`

`##.facebook-like-us`

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/9acd397060e2d6966b473287a5e4e3451e9af297/adblock_social_filters/adblock_social_list.txt#L1811

https://github.com/MajkiIT/polish-ads-filter/blob/9acd397060e2d6966b473287a5e4e3451e9af297/cookies_filters/adblock_cookies.txt#L345

**Comment by hawkeye116477** [comment]
@MajkiIT So to close :smile:
