### ISSUE TITLE
flashscore.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9303]
https://www.flashscore.pl
![opera zdjecie_2018-10-25_131928_www flashscore pl](https://user-images.githubusercontent.com/36385327/47496917-9f87d100-d858-11e8-9ad0-fcdc3305cf4c.png)

https://pl.futbol24.com
![opera zdjecie_2018-10-25_132009_pl futbol24 com](https://user-images.githubusercontent.com/36385327/47496943-b9c1af00-d858-11e8-99b8-6b6fc5ab11c1.png)

**Comment by krystian3w** [comment]
`flashscore.pl##.selfPromo__box--social`
`pl.futbol24.com##.facebook`
