### ISSUE TITLE
norwegian.com/pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9304]
https://www.norwegian.com/pl/
![opera zdjecie_2018-10-25_132159_www norwegian com](https://user-images.githubusercontent.com/36385327/47497070-1ae98280-d859-11e8-961e-9a7aecca3d47.png)

https://www.aerlingus.com/html/pl-PL/home.html
![opera zdjecie_2018-10-25_132139_www aerlingus com](https://user-images.githubusercontent.com/36385327/47497078-1fae3680-d859-11e8-8e62-18c8272e330e.png)

**Comment by krystian3w** [comment]
```
norwegian.com##.page-footer__social
aerlingus.com##.col-xs-20pc.col

norwegian.com##.alert:-abp-has(.cookie-disclaimer)
aerlingus.com##.bg-tealGreen-opacity:-abp-has(#cookie-desc)
```
