### ISSUE TITLE
fitness.wp.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9306]
![opera zdjecie_2018-10-25_155056_fitness wp pl](https://user-images.githubusercontent.com/36385327/47505115-c8ff2780-d86d-11e8-858f-adb9f44d60eb.png)

https://morizon.wp.pl
https://gryonline.wp.pl
https://tv.pudelek.pl
![opera zdjecie_2018-10-25_155128_morizon wp pl](https://user-images.githubusercontent.com/36385327/47505149-dae0ca80-d86d-11e8-93dd-385033f92d10.png)

**Comment by xMaap** [comment]
Nie wiem czy ja tylko tak mam
https://www.money.pl
![opera zdjecie_2018-10-25_160045_www money pl](https://user-images.githubusercontent.com/36385327/47505830-2cd62000-d86f-11e8-8bed-1954aa8521cf.png)

https://www.wakacje.pl
![opera zdjecie_2018-10-25_155808_www wakacje pl](https://user-images.githubusercontent.com/36385327/47505852-38294b80-d86f-11e8-8612-487bc88091b1.png)

**Comment by xxcriticxx** [comment]
@xMaap ja mam tak samo

**Comment by krystian3w** [comment]
Po usunięciu Cookies `money.pl` znika wam reklama?

**Comment by krystian3w** [comment]
Na wakacjach nie widzę socialu i tego cookies, może wada chromowatych.

**Comment by krystian3w** [comment]
Rodo WP nie na moje progi, social i rss z fitnesu dodam do list.

**Comment by xxcriticxx** [comment]
> Po usunięciu Cookies `money.pl` znika wam reklama?

@krystian3w nope

**Comment by krystian3w** [comment]
Dziwne, że ich stać na layout pod Firefox i Chrome osobny.

**Comment by xMaap** [comment]
W tych wakacjach teraz nic nie widzę.

A tutaj macie? https://www.wp.pl/?404&src01=99f53
![opera zdjecie_2018-10-25_220313_www wp pl](https://user-images.githubusercontent.com/36385327/47527046-d9c99080-d8a1-11e8-91ab-47e1b2e5dbb5.png)

**Comment by krystian3w** [comment]
U mnie link nie działa, wgrywa się bez "`?404&src01=99f53`"

**Comment by xxcriticxx** [comment]
@krystian3w ja testowalem na chromie
