### ISSUE TITLE
pecetowicz.pl

### ISSUE THREAD

**Issue by Pecetowicz** [MajkiIT/polish-ads-filter#9308]
Witam w /polish-adblock-filters/adblock.txt znajduje się zablokowana klasa ipsType_center oraz ipsPos_center_fix

Klasy te są domyślnie stosowane na skrypcie IPS Community Suite i usunięcie ich przez AdBlock skutkuje wieloma problemami z złym wyświetlaniem różnych bloków. Klasa wykorzystywana jest do wycentrowania tekstu. 

Proszę o usunięcie tych linii z filtra. Reklam na forum nie ma od ponad roku.

**Comment by MajkiIT** [comment]
@Pecetowicz Dziękuję za informację.
