### ISSUE TITLE
eska.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9314]
reklama

https://www.eska.pl/cinema/news/wojtus-z-rodziny-zastepczej-jak-dzisiaj-wyglada-michal-wlodarczyk-mma-aa-cRrs-NeMX-Urov.html

![capture](https://user-images.githubusercontent.com/15007183/47596925-15bf2d00-d958-11e8-901c-6e2616328292.PNG)

**Comment by xxcriticxx** [comment]
@MajkiIT jest tego wiecej 4, 5 etc

**Comment by MajkiIT** [comment]
@xxcriticxx Tak wiem, wpadnie w odpowiednią regułę. Dziękuję za pilnowanie.
