### ISSUE TITLE
miniminiplus.pl i teletoonplus.pl 

### ISSUE THREAD

**Issue by seba2282** [MajkiIT/polish-ads-filter#9316]
Witam. Chwilowo powróciłem do Windows 7 i firefox. Mam aktywny ublock origin. Zaznaczone wszystkie filtry + dodatkowe z wewnętrznymi i web ultralist annoyances. I... Jakiś czas był spokój z miniminiplus.pl i teletoonplus.pl. i znowu zaczęło się pojawiać w odtwarzaczu filmików komunikat o blokerze reklam. Wspomnę też iż u brata na laptopie z Windows 10 MS Edge i Nano Adblocker z dodanymi filtrami i wbudowanymi jest to samo (było ok. I powrócił komunikat o blokerze). Problem jest od mniej więcej dwóch dni. Czy możecie sprawdzić reguły dla tych stron? 

Pozdrawiam

**Comment by krystian3w** [comment]
Sprawdź najpierw wyłączając filtry do minimum, by nie było, że musimy dezaktywować japoński filtr a w Japonii "polski internet" z filtrem pod "japoński" oglądają 2 osoby na krzyż.

**Comment by seba2282** [comment]
Czyli tak. Zrobiłem szybki test. Wiedząc, że problem nie występuje z chrome z nano Adblocker + Nano Defender, a występuje w Firefox/MS Edge Nano Adblocker/Ublock Origin (gdyż te dwie nie mają nano Defender oficjalnie). Zainstalowałem Firefox na Android na szybko, włączyłem tryb stacjonarny, użyłem Ublock Origin i zaktualizowałem tylko te pierwotne filtry co są zaznaczone na samym początku po instalacji UBO. Nic nie dodałem. Efekt wykrycie adblockera. Nie ustawiałem też nic w samym Firefox. On ma domyślnie wyłączoną tą opcję, co pojawia się taka tarcza. To chyba się nazywa tryb chroniony. On jest wyłączony w FF.

**Comment by seba2282** [comment]
Tak, chodziło o sklepy z rozszerzeniami.

https://www.miniminiplus.pl/filmy/z/my-little-pony

**Comment by hawkeye116477** [comment]
@seba2282 U mnie z tym => `@@||tvn.adocean.pl/*ad.xml$xmlhttprequest,domain=tvnturbo.pl|miniminiplus.pl|teletoonplus.pl|player.pl` jest ok, ale to jest już na liście :smile:.

**Comment by hawkeye116477** [comment]
@seba2282 Tak

**Comment by seba2282** [comment]
Nie wiem już od czego to zależy. Teraz raz mi działa, a raz nie.

**Comment by krystian3w** [comment]
Może z innej domeny i nie ma reguły oszukującej (`$media,redirect=noopmp3-0.1s`).

**Comment by seba2282** [comment]
Pamiętam, że pomagały dwa filtry w większości. Polskie filtry elementów irytujących + web ultralist annoyances. A od dwóch/trzech dni, non stop wykryto Adblocker.

**Comment by krystian3w** [comment]
U mnie wykrywa tylko z Ochroną prywatności Firefox przed śledzeniem, ale to martwy element i polskie strony nie mają opcji zgłoszenia (na demie mozilli wyskakuje pod opcją wyłączenia link "[report a problem](#issuecomment-433698924)") a repo na githubie ma nawet zgłoszenia od dwóch lat nie ruszone ([/disconnectme/disconnect-tracking-protection/issues](/disconnectme/disconnect-tracking-protection/issues)). Może jest i jakieś nowsze repo ale nie szukałem.

**Comment by krystian3w** [comment]
U mnie wykrywa tylko z Ochroną prywatności Firefox przed śledzeniem, ale to martwy element:

* polskie strony nie mają opcji zgłoszenia (na demie mozilli wyskakuje pod opcją wyłączenia link "[report a problem](#issuecomment-433699481)")
* repo na githubie ma nawet zgłoszenia od dwóch lat nie ruszone ([/disconnectme/disconnect-tracking-protection/issues](/disconnectme/disconnect-tracking-protection/issues)). Może jest i jakieś nowsze repo ale nie szukałem.

**Comment by seba2282** [comment]
Sprawdź jedną rzecz, jak możesz. Uaktywniłem informuj witryna, że nie chcę być śledzony i jakby na chwilę zaczęło działać. Czy u ciebie jest tak samo w Firefox?

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/47615920-5339cc80-dab6-11e8-8d43-215c76833378.png) |
--- |

Kolorem tła się nie przejmuj Firefox 63.

Jak wyjątek to wyłącza, to nie od tego zależy czy wykryją blokowanie reklam.

**Comment by seba2282** [comment]
Ja na Android uaktywniłem opcję informuj witryny, że użytkownik nie chce być śledzony i u mnie na razie nie wykrywa Adblocker. Jak wyłączam tą opcję, to go wykrywa. Co jest na rzeczy?

**Comment by krystian3w** [comment]
Może nie serwują wtedy żadnych reklam by nie było, że nie działa u nich mechanizm losowania a są personalizowane mimo opcji.
