### ISSUE TITLE
allegro.pl 

### ISSUE THREAD

**Issue by szypuser** [MajkiIT/polish-ads-filter#9319]
### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. 
2. 
3. 

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome
**Rozszerzenia i skrypty:**
Ublock
**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. 
4. 

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Po wyłączeniu filtra POL: polskie filtry do Adblocka i uBlocka​​​​​użytych 5 691 z 6 105​​​​ cena jest widoczna

![download](https://user-images.githubusercontent.com/15007183/47615215-a6922780-da82-11e8-91e2-39083c2a8c97.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 @KonoromiHimaries @xxcriticxx macie konto na allegro ?

**Comment by szypuser** [comment]
Nie widać linka w zgłoszeniu https://prnt.sc/lbdhs6

**Comment by xxcriticxx** [comment]
ja ceny widze ale napewno jestem w zlym miejscu

![capture](https://user-images.githubusercontent.com/15007183/47615263-2e783180-da83-11e8-9a5b-6aa26e3ef401.PNG)

**Comment by xxcriticxx** [comment]
zapytaj specjaliste od allegro @maciejtarmas zglosic sie

**Comment by MajkiIT** [comment]
@szypuser  @xxcriticxx @krystian3w @F4z 
Dziekuję

**Comment by szypuser** [comment]
Trochę byłem zabiegany i nie miałem czasu podziękować.
Wszystko działa. Dziękuję.
