### ISSUE TITLE
acer.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9320]
cookies

https://www.acer.com/ac/pl/PL/content/home

Aby zapewnić jak największą wygodę korzystania, na naszej witrynie używamy plików cookie umożliwiających śledzenie firm zewnętrznych. Kliknij tutaj, aby dowiedzieć się więcej o plikach cookie i metodach zmiany ustawień. Zamknięcie tego okna lub dalsze przeglądanie witryny jest równoznaczne z wyrażeniem zgody na pliki cookie.

**Comment by hawkeye116477** [comment]
`acer.com##.cookieBox`
