### ISSUE TITLE
dead domain

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9324]
dekoder.ws = dead
fili.tv = fili.cc

**Comment by xxcriticxx** [comment]
centrum-dramy.pl = dramazone.pl

**Comment by krystian3w** [comment]
Można by sprawdzić listy cookies / social?

Chyba, że są wpięte w ten nowy projekt i nic nie wykrył dla nich.

**Comment by xxcriticxx** [comment]
@krystian3w ja to sprawdzilem recznie @MajkiIT ma jakis magic tool :)

**Comment by krystian3w** [comment]
Coś podobne do trzeciej opcji:

 `https://www.2daygeek.com/check-find-dns-records-of-domain-in-linux-terminal/`

 tyle, że jednak trochę czasu zajmuje wyłuskanie domen z reguł kosmetycznych i z sieciowych jeszcze trochę więcej (niby można zrobić to kilkoma regexami).

**Comment by xxcriticxx** [comment]
@krystian3w check out https://github.com/funilrys/PyFunceble

**Comment by krystian3w** [comment]
A domen jest jakieś ~1760, nie czyściłem z duplikatów i nie robiłem regexów by wydobyć `memy.pl|pwn.pl|translatica.pl` i `static.quantcast.mgr.consensu.org`

**Comment by xxcriticxx** [comment]
i jest jescze tajny tool @MajkiIT

**Comment by xxcriticxx** [comment]
jest jeszcze cos takiego https://github.com/blechschmidt/massdns

**Comment by MajkiIT** [comment]
@xxcriticxx @hawkeye116477 

Mój skrypt wyciągnął z ciasteczkowych 
```
Host szkolnaspizarnia.pl not found: 3(NXDOMAIN) UNKNOWN
Host bravekingdoms.com not found: 3(NXDOMAIN) UNKNOWN
Host curvefever.pl not found: 3(NXDOMAIN) UNKNOWN
Host dobrekosmetyki.co.uk not found: 3(NXDOMAIN) UNKNOWN
Host nadnarie.pl not found: 3(NXDOMAIN) UNKNOWN
Host e-fajek.pl not found: 3(NXDOMAIN) UNKNOWN
Host e-fajek.pl not found: 3(NXDOMAIN) UNKNOWN
Host forum.mcwiki.pl not found: 3(NXDOMAIN) UNKNOWN
Host hoteldladoroslych.pl not found: 3(NXDOMAIN) UNKNOWN
Host kinofilmyonline.pl not found: 3(NXDOMAIN) UNKNOWN
Host wezsietato.pl not found: 3(NXDOMAIN) UNKNOWN
Host klublife.pl not found: 3(NXDOMAIN) UNKNOWN
Host kursyuniversum.ksiezyc.pl not found: 3(NXDOMAIN) UNKNOWN
Host ogllo.pl not found: 3(NXDOMAIN) UNKNOWN
Host whichwatch.pl not found: 3(NXDOMAIN) UNKNOWN
Host cookie-law-popup.js not found: 3(NXDOMAIN) UNKNOWN
Host www.pianomedia.pl not found: 3(NXDOMAIN) UNKNOWN
```

Wiem, że ma błędy, ale dopracuję go.

**Comment by xxcriticxx** [comment]
@MajkiIT czemu to zlapalo `cookie-law-popup.js`?

sprawdzilem recznie wszystko dead

**Comment by MajkiIT** [comment]
@xxcriticxx Napisałem "Wiem, że ma błędy, ale dopracuję go." i to jest właśnie ten błąd
.

**Comment by hawkeye116477** [comment]
A tego to ja nie widzę w ogóle `klublife.pl` :stuck_out_tongue:

**Comment by krystian3w** [comment]
Dziwne, że od lutego jest niby.

**Comment by MajkiIT** [comment]
@hawkeye116477 zapewne chodziło o "klublifestyle.pl" :D

**Comment by hawkeye116477** [comment]
@MajkiIT To w takim razie skrypt się pomylił, bo taka strona istnieje i ma się dobrze :smile:

**Comment by MajkiIT** [comment]
Wiem, już poprawiam :D

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/907adb2724ba641b17fac189d55f32c1a7bfdc5b#diff-13329614a1ac5aa1dcecd2fa4fe32826
usuwać linię gdzie na końcu jest kropka

**Comment by xxcriticxx** [comment]
@MajkiIT please fix 

`Host konkurs24h.pladvalue not found: 3(NXDOMAIN) UNKNOWN`

**Comment by krystian3w** [comment]
```
Host redir.atmcdn.plswf not found: 3(NXDOMAIN) UNKNOWN
```

```
Host livemecz not found: 3(NXDOMAIN) UNKNOWN
```

**Comment by krystian3w** [comment]
> `Host businessclick not found: 3(NXDOMAIN) UNKNOWN` brakuje .pl?
> `Host livemecz not found: 3(NXDOMAIN) UNKNOWN` brak .pl?

Nie, mają więcej typów domen to mamy `.*`, by ich nie wymieniać / szukać.

**Comment by MajkiIT** [comment]
@xxcriticxx Tak poprawię.

**Comment by xxcriticxx** [comment]
@MajkiIT you the bomb diggity

**Comment by MajkiIT** [comment]
Host konkurs24h.pladvalue - usunięcie wpisu gdzie jest * w środku
Host businessclick not found: 3(NXDOMAIN) UNKNOWN brakuje .pl?  - usunięcie wpisu gdzie jest * na końcu
Host livemecz not found: 3(NXDOMAIN) UNKNOWN brak .pl? - usunięcie wpisu gdzie jest * na końcu
Host redir.atmcdn.plswf not found: 3(NXDOMAIN) UNKNOWN cos xtra .swf file 
redir.atmcdn.pl = 404 ale main domain atmcdn.pl dziala - usunięcie wpisu gdzie jest * w środku

**Comment by MajkiIT** [comment]
@xxcriticxx Wedle życzenia :D

```
Host fullon.tv not found: 3(NXDOMAIN) UNKNOWN
streamin.to has address 127.0.0.1
Host streamin.to not found: 3(NXDOMAIN)
Host streamin.to not found: 3(NXDOMAIN) UNKNOWN
```

**Comment by xxcriticxx** [comment]
@MajkiIT thanks

**Comment by MajkiIT** [comment]
@krystian3w @hawkeye116477 
FYI https://github.com/MajkiIT/polish-ads-filter/tree/master/dead-domains

**Comment by krystian3w** [comment]
Nie umiem zrobić RTM ale poprawiłem.

**Comment by MajkiIT** [comment]
@krystian3w Dziękuję. 
A to `cookie-law-popup.js` to masz rację. Poprawię.

**Comment by xxcriticxx** [comment]
@MajkiIT 

tutaj jest pomylka te strony dzialaja

`Host cardsplitter.pl.sklepmaniek.pl not found: 3(NXDOMAIN) UNKNOWN`

**Comment by krystian3w** [comment]
Poprawione, na szczęście tylko 4 dni te dwie strony miały przycisk "zgłoś błąd na stronie" który się przewijał z ruchem strony.

**Comment by MajkiIT** [comment]
@xxcriticxx U @krystian3w był błąd a nie w skrypcie.

**Comment by xxcriticxx** [comment]
wazne ze poprawione
