### ISSUE TITLE
hentai-online.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9325]
ad block

![capture](https://user-images.githubusercontent.com/15007183/47622376-cd7c4800-dada-11e8-8362-7a7f41d75dc1.PNG)

**Comment by seba2282** [comment]
@xxcriticxx Chciałem spróbować odpalić to na Firefox z Ublock Origin i włączoną opcją "informuj witryny, że użytkownik nie chce być śledzony". Ale Eset blokuje stronę z powodu szkodliwego elementu javascript.

**Comment by krystian3w** [comment]
Raczej by nic nie dało skoro szukają jakiś elementów z EasyList jako generyczne.
