### ISSUE TITLE
overwatch.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9327]
Białe tło z włączonym Nano Adblocker
https://overwatch.pl/wspolpraca
https://overwatch.pl/spolecznosc
https://overwatch.pl/o-nas

Włączony
![opera zdjecie_2018-10-29_044557_overwatch pl](https://user-images.githubusercontent.com/36385327/47628364-98511380-db35-11e8-95ac-f98048e186d8.png)

Wyłączony
![opera zdjecie_2018-10-29_044613_overwatch pl](https://user-images.githubusercontent.com/36385327/47628369-9d15c780-db35-11e8-87c0-e75018b91a6e.png)

**Comment by krystian3w** [comment]
`overwatch.pl#@#.page`  - @xMaap  w filtrach Elementów Irytujących - już usuwam.
Do 15 minut i powinno dać się pobrać listy bez tej reguły.

---


I @MajkiIT  dalej oni mają AntyAdblocka:

![image](https://user-images.githubusercontent.com/35370833/47637785-14128680-db5d-11e8-8dbe-c16554d31b5d.png)


Na adminowym discordzie podrzuciłem rozwiązanie pod AdBlock / ABP (kilka wyjątków, by nie wykryli blokady reklam) lub skrypt upośledzający, ale ten mało testowałem czy jest jakiś lżejszy lub lepszy.

Nie wiem czy przez miesiąc się czasem nie zdezkaktualizowało, a w AdGuardzie dopisali to do jakiegoś dziwnego skryptu.
