### ISSUE TITLE
autoklub.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9334]
http://www.autoklub.pl
![opera zdjecie_2018-10-29_082735_www autoklub pl](https://user-images.githubusercontent.com/36385327/47635219-8a5ebb00-db54-11e8-84dc-0134290ce0f0.png)

http://rajdy.autoklub.pl
![opera zdjecie_2018-10-29_082927_rajdy autoklub pl](https://user-images.githubusercontent.com/36385327/47635299-c8f47580-db54-11e8-9a9e-e6c79f2880ab.png)

http://terenowe.autoklub.pl
![opera zdjecie_2018-10-29_083004_terenowe autoklub pl](https://user-images.githubusercontent.com/36385327/47635323-ddd10900-db54-11e8-87bf-be4c6b2f99f7.png)

http://karting.autoklub.pl
![opera zdjecie_2018-10-29_083028_karting autoklub pl](https://user-images.githubusercontent.com/36385327/47635342-ec1f2500-db54-11e8-96f6-0213f675c330.png)

**Comment by MajkiIT** [comment]
```
www.autoklub.pl###toppage_shadow
autoklub.pl##[href^="http://www.autoklub.pl/redirect.php"]
```
