### ISSUE TITLE
blogojciec.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9336]
![opera zdjecie_2018-10-29_093251_www blogojciec pl](https://user-images.githubusercontent.com/36385327/47638030-be8aa980-db5d-11e8-9957-fdc13d92f67a.png)

**Comment by krystian3w** [comment]
U mnie gorzej sam krzyżyk.

![image](https://user-images.githubusercontent.com/35370833/47640028-f5af8980-db62-11e8-8ed4-1ac7cc5a35de.png) |
--- |
