### ISSUE TITLE
Globalnie padły etykiety wymaganych filtrów?

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#9341]
|![image](https://user-images.githubusercontent.com/35370833/47658784-e0068800-db93-11e8-9b7c-d9dad4e91edb.png) |
| :---: |

**Comment by xxcriticxx** [comment]
@krystian3w good catch

**Comment by krystian3w** [comment]
A kopiowało się ten link do subskrypcji polskich filtrów i wali mi po oczach napis "kolor".

**Comment by krystian3w** [comment]
![EasyList][EasyList]
![Polskie filtry][Polskie filtry]     
![Uzupełnienie uBO][Uzupełnienie uBO]  
![Uzupełnienie AG][Uzupełnienie AG]   
![Uzupełnienie uBO_AG][Uzupełnienie uBO_AG] 
![Skrypt uzupełniający][Skrypt uzupełniający] 
![Polskie Filtry Cookies][Polskie Filtry Cookies] 
![Fanboy Social][Fanboy Social]
![Polskie Filtry Social][Polskie Filtry Social]  
![Polskie Filtry Elementów Irytujących][Polskie Filtry Elementów Irytujących]

[EasyList]: https://img.shields.io/badge/color-EasyList-brightgreen.svg
[EasyPrivacy]: https://img.shields.io/badge/color-EasyPrivacy-green.svg
[Polskie filtry]: https://img.shields.io/badge/color-Polskie%20Filtry-red.svg
[Uzupełnienie uBO]: https://img.shields.io/badge/color-Uzupełnienie%20do%20uB%20*-yellowgreen.svg
[Uzupełnienie AG]: https://img.shields.io/badge/color-Uzupełnienie%20do%20AG%20*-yellowgreen.svg
[Uzupełnienie uBO_AG]: https://img.shields.io/badge/color-Uzupełnienie%20do%20uB%20i%20AG%20*-yellowgreen.svg
[Skrypt uzupełniający]: https://img.shields.io/badge/color-Skrypt%20uzupełniający%20***-blue.svg
[Polskie Filtry Cookies]: https://img.shields.io/badge/color-Polskie%20Filtry%20Cookies-orange.svg
[Fanboy Social]: https://img.shields.io/badge/color-Fanboy%20Social-blue.svg
[Polskie Filtry Social]: https://img.shields.io/badge/color-Polskie%20Filtry%20Social-0066FF.svg?
[Polskie Filtry Elementów Irytujących]: https://img.shields.io/badge/color-Polskie%20Filtry%20Annoyance-yellow.svg

```
[EasyList]: https://img.shields.io/badge/color-EasyList-brightgreen.svg
[EasyPrivacy]: https://img.shields.io/badge/color-EasyPrivacy-green.svg
[Polskie filtry]: https://img.shields.io/badge/color-Polskie%20Filtry-red.svg
[Uzupełnienie uBO]: https://img.shields.io/badge/color-Uzupełnienie%20do%20uB%20*-yellowgreen.svg
[Uzupełnienie AG]: https://img.shields.io/badge/color-Uzupełnienie%20do%20AG%20*-yellowgreen.svg
[Uzupełnienie uBO_AG]: https://img.shields.io/badge/color-Uzupełnienie%20do%20uB%20i%20AG%20*-yellowgreen.svg
[Skrypt uzupełniający]: https://img.shields.io/badge/color-Skrypt%20uzupełniający%20***-blue.svg
[Polskie Filtry Cookies]: https://img.shields.io/badge/color-Polskie%20Filtry%20Cookies-orange.svg
[Fanboy Social]: https://img.shields.io/badge/color-Fanboy%20Social-blue.svg
[Polskie Filtry Social]: https://img.shields.io/badge/color-Polskie%20Filtry%20Social-0066FF.svg?
[Polskie Filtry Elementów Irytujących]: https://img.shields.io/badge/color-Polskie%20Filtry%20Annoyance-yellow.svg
```

Ale nie ustaliłem co `shields.io` nazmieniało i czemu stare wyłączyli.

**Comment by krystian3w** [comment]
![EasyList][EasyList]
![Polskie filtry][Polskie filtry]     
![Uzupełnienie uBO][Uzupełnienie uBO]  
![Uzupełnienie AG][Uzupełnienie AG]   
![Uzupełnienie uBO_AG][Uzupełnienie uBO_AG] 
![Skrypt uzupełniający][Skrypt uzupełniający] 
![Polskie Filtry Cookies][Polskie Filtry Cookies] 
![Fanboy Social][Fanboy Social]
![Polskie Filtry Social][Polskie Filtry Social]  
![Polskie Filtry Elementów Irytujących][Polskie Filtry Elementów Irytujących]

[EasyList]: https://img.shields.io/badge/INT-EasyList-brightgreen.svg
[EasyPrivacy]: https://img.shields.io/badge/INT-EasyPrivacy-green.svg
[Polskie filtry]: https://img.shields.io/badge/POL-Polskie%20Filtry-red.svg
[Uzupełnienie uBO]: https://img.shields.io/badge/POL-Uzupełnienie%20do%20uB%20*-yellowgreen.svg
[Uzupełnienie AG]: https://img.shields.io/badge/POL-Uzupełnienie%20do%20AG%20*-yellowgreen.svg
[Uzupełnienie uBO_AG]: https://img.shields.io/badge/POL-Uzupełnienie%20do%20uB%20i%20AG%20*-yellowgreen.svg
[Skrypt uzupełniający]: https://img.shields.io/badge/POL-Skrypt%20uzupełniający%20***-blue.svg
[Polskie Filtry Cookies]: https://img.shields.io/badge/POL-Polskie%20Filtry%20Cookies-orange.svg
[Fanboy Social]: https://img.shields.io/badge/INT-Fanboy%20Social-blue.svg
[Polskie Filtry Social]: https://img.shields.io/badge/POL-Polskie%20Filtry%20Social-0066FF.svg?
[Polskie Filtry Elementów Irytujących]: https://img.shields.io/badge/POL-Polskie%20Filtry%20Annoyance-yellow.svg

```
[EasyList]: https://img.shields.io/badge/INT-EasyList-brightgreen.svg
[EasyPrivacy]: https://img.shields.io/badge/INT-EasyPrivacy-green.svg
[Polskie filtry]: https://img.shields.io/badge/POL-Polskie%20Filtry-red.svg
[Uzupełnienie uBO]: https://img.shields.io/badge/POL-Uzupełnienie%20do%20uB%20*-yellowgreen.svg
[Uzupełnienie AG]: https://img.shields.io/badge/POL-Uzupełnienie%20do%20AG%20*-yellowgreen.svg
[Uzupełnienie uBO_AG]: https://img.shields.io/badge/POL-Uzupełnienie%20do%20uB%20i%20AG%20*-yellowgreen.svg
[Skrypt uzupełniający]: https://img.shields.io/badge/POL-Skrypt%20uzupełniający%20***-blue.svg
[Polskie Filtry Cookies]: https://img.shields.io/badge/POL-Polskie%20Filtry%20Cookies-orange.svg
[Fanboy Social]: https://img.shields.io/badge/INT-Fanboy%20Social-blue.svg
[Polskie Filtry Social]: https://img.shields.io/badge/POL-Polskie%20Filtry%20Social-0066FF.svg
[Polskie Filtry Elementów Irytujących]: https://img.shields.io/badge/POL-Polskie%20Filtry%20Annoyance-yellow.svg
```

Ale nie ustaliłem co `shields.io` nazmieniało i czemu stare wyłączyli. Jakby zlikwidowali label jako etykietę.
