### ISSUE TITLE
frazpc.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#9343]
> ZAMKNIĘCIE SERWISU
> 
> Cyfrowy Polsat S.A. z siedzibą w Warszawie, adres: ul. Łubinowa 4a, 03-878 Warszawa, wpisana do rejestru przedsiębiorców Krajowego Rejestru Sądowego pod numerem 0000010078, dla której akta rejestrowe prowadzi Sąd Rejonowy dla m. st. Warszawy w Warszawie, XIII Wydział Gospodarczy Krajowego Rejestru Sądowego, o kapitale zakładowym 25 581 840,64 zł w całości wpłaconym, NIP 7961810732, niniejszym informuje, że kończy działalności w zakresie działalności Serwisu FrazPC.pl. Zamknięcie Serwisu **nastąpi w dniu 31 grudnia 2018 roku**. Do dnia 31 grudnia 2018 roku serwis będzie działał na dotychczasowych zasadach. Zachęcamy aby w tym okresie pobrać z Serwisu potrzebne użytkownikom materiały, gdyż **po dniu 31 grudnia 2018 roku żadne materiały nie będą dostępne**.

https://github.com/MajkiIT/polish-ads-filter/search?q=frazpc.pl

https://github.com/MajkiIT/polish-ads-filter/blob/9acd397060e2d6966b473287a5e4e3451e9af297/cookies_filters/adblock_cookies.txt#L1286

https://github.com/MajkiIT/polish-ads-filter/blob/47bb6b1c6aea0072c71788e228c75456374e9d1b/polish-adblock-filters/adblock.txt#L981

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/10599#issue-390254522

**Comment by xxcriticxx** [comment]
zamykamy?

**Comment by krystian3w** [comment]
Niech jeszcze powisi, może Cyfrowy Polsat jeszcze nie wytrzeźwiał.

5 dni i coś im nie wypaliła apokalipsa a komunikatu też nie usunęli.

**Comment by krystian3w** [comment]
<a href="https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/fanboy-cookie.txt&amp;title=Fanboy%20Cookie%20List" rel="nofollow">https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/fanboy-cookie.txt&amp;title=Fanboy%20Cookie%20List</a>

**Comment by krystian3w** [comment]
na `boardpc.pl` mają tylko push bar jak na `forum.dobreprogramy.pl`

**Comment by hawkeye116477** [comment]
Niespodzianka, zmienili nazwę strony na `geekweek` :smile:

**Comment by krystian3w** [comment]
@MajkiIT możesz usunąć: 

https://github.com/MajkiIT/polish-ads-filter/blob/e8c9441c590c67493f6cfef4ee459f604a0a9ad5/polish-adblock-filters/adblock.txt#L994
