### ISSUE TITLE
jambox.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9344]
cookies

https://www.jambox.pl/o-nas

**Comment by krystian3w** [comment]
Ja tam nie mam, nie widzę też by to była fałszywa strona główna jak kiedyś z `powiatslubicki.pl`

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/47681876-f419ac00-dbca-11e8-9520-6373df512a6a.png)

> Filtr statyczny ###sliding-popup:not(body):not(html) znajdujący się w:
> 
>  *   Polskie Filtry RODO-Ciasteczkowe

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/9acd397060e2d6966b473287a5e4e3451e9af297/cookies_filters/adblock_cookies.txt#L1557
