### ISSUE TITLE
zachodniemazowsze.info

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9348]
![opera zdjecie_2018-10-30_101736_zachodniemazowsze info](https://user-images.githubusercontent.com/36385327/47707892-34aa1180-dc2d-11e8-97fa-0e0880c0d06c.png)
![opera zdjecie_2018-10-30_101756_zachodniemazowsze info](https://user-images.githubusercontent.com/36385327/47707893-3542a800-dc2d-11e8-872a-938aae4e93d5.png)

**Comment by MajkiIT** [comment]
`##.g`
