### ISSUE TITLE
mapa.um.warszawa.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9359]
" Komunikat " : http://www.mapa.um.warszawa.pl/mapaApp1/mapa?service=cmentarze&L=pl

**Comment by krystian3w** [comment]
Można by wyciąć jako Element Irytujący, RODO tam za bardzo nie widzę, reklamy też nie.

**Comment by hawkeye116477** [comment]
A co @MajkiIT o tym sądzi?

**Comment by xxcriticxx** [comment]
lord @MajkiIT zglos sie!

**Comment by krystian3w** [comment]
Jakby to było rodo, to przypmnijcie by ty wyciąć z listy widgetów lub przenieść jak polskie EI by wycinało.

Fanboy Annoyance jest bezlitosne nawet na pop-up-y by uważać na podszywanie się pod firmę czy sklep.

**Comment by MajkiIT** [comment]
@hawkeye116477 @xxcriticxx @krystian3w 
Dla mnie to coś irytującego najbardziej. Bo na pewno nie reklama itp .

**Comment by hawkeye116477** [comment]
@MajkiIT No tak, ale nam chodziło o to czy to do listy :cookie: czy do EI, choć chyba bardziej pasuje do EI :smile:

**Comment by krystian3w** [comment]
To nie cookies ani RODO (chodzi, że Urzędnik żaden nie kontroluje poprawności danych na mapie), więc tylko EI.
