### ISSUE TITLE
Zarabiam.com

### ISSUE THREAD

**Issue by Marko7192** [MajkiIT/polish-ads-filter#9363]
https://scr.hu/VgB2B4K
https://scr.hu/07BnBND
https://scr.hu/PYGmGmX

http://zarabiam.com

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. wystarczy sie sprobowac zarejestrowac a nie pojawi sie capcha, po rejestracji nie mozna pisac w postow w tematach ani wysylac prywatnych wiadomosci do kogokolwiek, niezbedne jest wylaczniee adbloka. 

### Moja konfiguracja
Problem wystepuje na kazdej przegladarce jaką używam chrom/opera/firefox

Problem pojawia się również u moich znajomych, nie chcemy wyłączać adbloka ale uniemozliwia on korzystanie z tej strony. Proszę o naprawienie tego problemu, czy poprawienie filtrow.

**Comment by krystian3w** [comment]
Ja tam nie mam nawet pola z kapciem...

**Comment by krystian3w** [comment]
`zarabiam.com#@#table > tbody > tr > td > div > div`

ja bym wywalił "`##table > tbody > tr > td > div > div`"

**Comment by MajkiIT** [comment]
@krystian3w jeśli tak chcesz to tak będzie. 
@Marko7192 Dziękuje

**Comment by krystian3w** [comment]
Za dużo może być w tabeli z dwoma divami i nie widzę by to już coś konkretnego blokowało.

**Comment by Marko7192** [comment]
Dziękuję Wam Panowie za zainteresowanie, jednak aktualnie dalej adblock nie pozwala mi napisać posta czy odpisać na prywatne wiadomości. Wciąż textboxy są blokowane.

**Comment by Marko7192** [comment]
aaa przepraszam zrobiłęm aktulizację list i jest już wporządku! mogę odpowiedać dziękuje za pomoc !

**Comment by krystian3w** [comment]
Niestety opóźnienie może być do 15 minut, ja tak mam z listami ostatnio.

**Comment by Marko7192** [comment]
Panowie jeszcze jeden mały błąd nie wiem czy nie robię problemu zgłaszając to ale to akurat nie powinno być blokowane, po wejsciu w dowolny temat, forum pokazuje w jakim dziale się znajdujemy, powinno to wyglądać tak:
https://scr.hu/22Onyvv (oczywiscie bez reklamy:D)
a wyglada tak:
https://scr.hu/7O9ngOa

znacznie wiecej ten adblok blokuje niz powinien :)

**Comment by krystian3w** [comment]
Ja tam nie wiem czy to nie była by nagle reklama wewnętrzna, czyli byłaby wycinana inną listą albo dobrana reklama pod tematykę forum.

**Comment by Marko7192** [comment]
tam jest i zawsze była tylko informacja w jakim dziale jest wątek i jak się nazywa, teraz adblok ucina te informacje i nie wie się gdzie ani co się czyta, nigdy tam zadnych reklam nie było prócz tej w nagłówku którą pokazałem na powyższym screenie.

**Comment by krystian3w** [comment]
`zarabiam.com#@#center`
