### ISSUE TITLE
wtk.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9367]
![opera zdjecie_2018-10-31_092006_wtk pl](https://user-images.githubusercontent.com/36385327/47774820-5ae3b600-dcee-11e8-9415-c061631a0a46.png)

**Comment by krystian3w** [comment]
```
wtk.pl#@#.privacy-container:not(body):not(html):not(.content-container)
wtk.pl##^#GDPR-modal
wtk.pl$$#GDPR-modal
wtk.pl###GDPR-modal, .modal-backdrop
wtk.pl##.modal-open:style(overflow: auto !important; padding-right: 0 !important;)
```

**Comment by krystian3w** [comment]
Popsute wideo:

`https://wtk.pl/news/42188-vademecum-lokatora-miejskie-biuro-najmu`

**Comment by hawkeye116477** [comment]
@MajkiIT Trzeba posprzątać po EasyList :smile:.

**Comment by krystian3w** [comment]
A bo tu wideo 🎃.

**Comment by hawkeye116477** [comment]
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=games.cdn.famobi.com|grydladzieci.pl|fm.tuba.pl|wp.pl|player.pl|animezone.pl|ipla.tv|www.polsatnews.pl|playpuls.pl|polsatsport.pl|twojapogoda.pl|wtk.pl`
