### ISSUE TITLE
wszczecinie.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9369]
https://wszczecinie.pl/aktualnosci,filharmonia_znow_zaskakuje_niezwykle_koncerty_i_wybitni_artysci_na_100_rocznice_odzyskania_niepodleglosci,id-30580.html
![opera zdjecie_2018-10-31_102933_wszczecinie pl](https://user-images.githubusercontent.com/36385327/47778869-13622780-dcf8-11e8-81d6-8bb5ac023cfe.png)
![opera zdjecie_2018-10-31_102944_wszczecinie pl](https://user-images.githubusercontent.com/36385327/47778870-13622780-dcf8-11e8-81ae-d224f6881f3f.png)

**Comment by krystian3w** [comment]
`wszczecinie.pl##.adv_container` :question:

**Comment by MajkiIT** [comment]
@krystian3w 
Nawet bym się pokusił o `##.adv_container`
