### ISSUE TITLE
polki.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9373]
https://polki.pl
https://mamotoja.pl
http://wizaz.pl
http://viva.pl
https://gotujmy.pl
http://party.pl
![opera zdjecie_2018-10-31_161842_polki pl](https://user-images.githubusercontent.com/36385327/47798485-be8ad500-dd28-11e8-86d0-c0c7ebe5e44d.png)

**Comment by hawkeye116477** [comment]
U mnie tego nie ma.
