### ISSUE TITLE
moviesroom.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9374]
![zrzut ekranu z 2018-10-31 18-14-45](https://user-images.githubusercontent.com/36385327/47805967-e08c5380-dd38-11e8-808c-ea0ce1851950.png)

**Comment by xxcriticxx** [comment]
`moviesroom.pl###frame`

**Comment by krystian3w** [comment]
Ramka po reklamie:

![obraz](https://user-images.githubusercontent.com/35370833/47819468-e561ff00-dd5a-11e8-9106-f9b88ecf870b.png) |
--- |

**Comment by xMaap** [comment]
Ramka i jeszcze tło na stronie.

**Comment by krystian3w** [comment]
Tło nie ma reklamy czegoś, chyba że kojarzysz klatkę z filmu lub masz wstręt do krwi.

> ![obraz](https://user-images.githubusercontent.com/35370833/47855001-96ac7780-dde3-11e8-9d69-ca2cc7ff188f.png) |
> --- |

Niby storytel ale nie ma tam ich logo.

`https://moviesroom.pl/wp-content/uploads/2018/10/1920x1080_moviesroom.jpg`

**Comment by krystian3w** [comment]
Niby da się kliknąć to można by zrobić `###screening`

I wróci to:

> ![obraz](https://user-images.githubusercontent.com/35370833/47855112-e9862f00-dde3-11e8-8766-224fb2fc1475.png) |
> --- |

`http://moviesroom.pl/wp-content/themes/moviesroom/assets/background3.jpg`
