### ISSUE TITLE
pamiatki.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9375]
Przyblokowany scroll, prawdopopodobnie to pzostałość po RODO.

Są też sociale tzn you tube i intagram na headerze oraz facebook po boku jako button.

**Comment by krystian3w** [comment]
```html
<script>
var x = document.getElementById("hw_cookie_law").style.display == "none";
if (x==false) document.body.style.overflow = "hidden";
</script>
```

**Comment by krystian3w** [comment]
Czyli odblokować by trzeba na AdBlock / ABP, wyciąć html filteringiem, a gdzie się nim nie da to CSS odblokować scroll.
