### ISSUE TITLE
polygamia.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9376]
https://polygamia.pl/juz-wkrotce-pojawi-sie-nowe-dlc-do-this-war-of-mine/
![opera zdjecie_2018-10-31_184745_polygamia pl](https://user-images.githubusercontent.com/36385327/47807928-93f74700-dd3d-11e8-8058-cb63741ffe04.png)

**Comment by krystian3w** [comment]
`##div.container.fake-ad` chyba że namierzy ktoś skrypt pułapkę.

**Comment by krystian3w** [comment]
Lepiej nie robić bo znowu Mati będzie narzekał jak kiedyś, że mu się strona psuje a nikt nie umie odtworzyć błędu.

**Comment by hawkeye116477** [comment]
Jeszcze została resztka po reklamie gry na pstryczka :smile:.
