### ISSUE TITLE
lazienki-krolewskie.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9378]
" odwiedż nas " - resztka po fb na dole

**Comment by krystian3w** [comment]
@blocker999 / @hawkeye116477  gdzie wyciąć resztę tej stopki, bo ona nie ma nic poza już wyciętym newsletterem i teraz resztką facebooka.

Bo trochę dziwnie wygląda prawie na środku a jednak po lewej pionowa linia. Chyba, że by inaczej wyciąć social - `##.grid-25` zamiast `##.plub-nas`

**Comment by blocker999** [comment]
@krystian3w Obojętnie, chyba najlepiej dać do sociali `##. grid-25` i ok a jak nie to można poprawić zawsze filt od newslettra, rób jak uważasz.

**Comment by krystian3w** [comment]
To zrobię takie coś: `lazienki-krolewskie.pl##.grid-25:-abp-has(.polub-nas)` na dole to raczej tak szybko nikt nie przewinie i nic innego co by było też gridem-25 nie zostanie wycięte.
