### ISSUE TITLE
paradoxplaza.com

### ISSUE THREAD

**Issue by lukjan32** [MajkiIT/polish-ads-filter#9383]
strona jest zablokowana, nie dzialaja zadne akcje.

**Comment by krystian3w** [comment]
# `paradoxplaza.com###disablingDiv`

ale nie wiem gdzie trafi (EI, Reklamy, Cookies) - nie ma polskiego ale i pewnie niepopularne, więc raczej do żadnej polskiej listy.

----


Najlepiej zgłoś do EasyList i czekaj aż za miesiąc zablokują element.  

### Chociaż pewnie wrzucą to w Annoyance i a tego my nie używamy, i pewnie będziemy im za darmo błędy wyłapywać...

Projekt `uBlock-Origin/uAsset` raczej trąci nosem, zamknie i zawoła **`@`ryanbar**-a.

**Comment by krystian3w** [comment]
- Albo na własną odpowiedzialność dosubskrypbuj Fanboy’s Cookiemonster List​​​​​​​​ i w nim wycinają `#disablingDiv`.

- Opcjonalnie **DODATEK**: [I don't care about cookies](https://www.i-dont-care-about-cookies.eu/), on zamknie komunikat cookies akceptując go i zniknie też Cookie Wall. **Lista nie wycina** (jako substytut dodatku) `#disablingDiv`.

**Comment by lukjan32** [comment]
aha, to gdzie zglosic?

**Comment by krystian3w** [comment]
Już nigdzie, Fanboye wycinają, kiboke wycina w dodatku więc czytaj post - 
https://github.com/MajkiIT/polish-ads-filter/issues/9383#issuecomment-435120248

U nas raczej to Cookie nie będzie wycinane, chyba że udowodnisz popularność strony w Polsce.

**Comment by lukjan32** [comment]
ok, dodam do wyjatkow

**Comment by lukjan32** [comment]
zaczelo dzialac, jak nie ma w wyjatkach.
