### ISSUE TITLE
GitHub zgłupiał (...)

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#9384]
#### (...) powiadomił mnie o moich odpowiedziach i edycji odpowiedzi jakich sam dokonałem

---

Już z pięć powiadomień dostałem z nakierowaniem na mój post dodany z 10 minut wcześniej lub jakiś który raz edytowałem...

**Comment by hawkeye116477** [comment]
Też mi się zdarzyło.

**Comment by xxcriticxx** [comment]
Microsoft usunal ostatnia patch z serwera
