### ISSUE TITLE
opiniodajnia.pl

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#9389]
`https://www.opiniodajnia.pl/biedronka-03-09-wrzesien-gazetka/nowosc-platki-nestle-coco-crush-lion-wild-crush-crazy-crush-cini-minis/#slide/1`

zablokowane przewijanie w Firefox 63 z Android 8.1 + uBO 1.17.2

**Comment by krystian3w** [comment]
```
opiniodajnia.pl##body:style(overflow: visible !important;)
```

Na telefonie w filtrach własnych pomagało.

**Comment by hawkeye116477** [comment]
@xxcriticxx Do zamknięcia.
