### ISSUE TITLE
mlecznepodroze.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9390]
![opera zdjecie_2018-11-02_070458_mlecznepodroze pl](https://user-images.githubusercontent.com/36385327/47896412-b5efe700-de6d-11e8-9e69-5b6b450c4567.png)
![opera zdjecie_2018-11-02_070515_mlecznepodroze pl](https://user-images.githubusercontent.com/36385327/47896413-b5efe700-de6d-11e8-90fc-e276b516152d.png)

**Comment by MajkiIT** [comment]
@krystian3w 
Wystarczy tak
`##.g`
