### ISSUE TITLE
zatorland.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9393]
![zrzut ekranu z 2018-11-02 11-27-14](https://user-images.githubusercontent.com/36385327/47910202-62dc5b00-de92-11e8-993f-f88140a4804c.png)

**Comment by hawkeye116477** [comment]
U mnie wskakuje normalny popup, tak czy siak to jest wewnętrzne, więc do EI :smile:.

**Comment by krystian3w** [comment]
`###spu-6137, #spu-bg-6137`

reklama wewnętrzna jakiś promocji w parku dinozaurów.
