### ISSUE TITLE
hefra.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9397]
cookies i sociale ( buttons )

**Comment by hawkeye116477** [comment]
Przyciski z taxi i ratami też są :smile:

**Comment by blocker999** [comment]
@hawkeye116477  taxi i raty już są w EI

**Comment by hawkeye116477** [comment]
@blocker999 To są zewnętrzne elementy, więc jak dla mnie, to powinny trafić na listę reklamową.

**Comment by blocker999** [comment]
@hawkeye116477 Niewiem jak chcesz to możesz je przenieść ale ja zawsze takie buttony tam dawałem, zresztą niech @MajkiIT się wypowie

**Comment by MajkiIT** [comment]
@blocker999 @hawkeye116477 to nie do końca reklamy. To informacja o ratach i możliwości zwrotu VATu.

**Comment by hawkeye116477** [comment]
Ok, w takim razie zostaje tam gdzie jest :smile:.
