### ISSUE TITLE
pay.google.com/intl/pl_pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9399]
cookies i yt ( na dole )

**Comment by krystian3w** [comment]
> **404.** That’s an error.
> 
> The requested URL /intl/pl_pl was not found on this server. That’s all we know. 

A zalogowani raczej nie mają nic w stopce.

**Comment by hawkeye116477** [comment]
@krystian3w `https://pay.google.com/intl/pl_pl/about/`

**Comment by xxcriticxx** [comment]
`pay.google.com##.cookie-bar`

**Comment by blocker999** [comment]
ok i coś teraz jeszcze na tą luke po cookies a na tą małą ikonke yt co jest na dole proponuje : `##.youtube.social--icon`

**Comment by krystian3w** [comment]
`pay.goole.com##.main-footer--cookie.o-container:style(padding-bottom: 0 !important;)`

**Comment by hawkeye116477** [comment]
@krystian3w @xMaap Może `news.google.com##div[style^="behavior:url(#default#homePage) url(#default#userData)"]`

**Comment by krystian3w** [comment]
Ja nie mam sam może czymś prostszym wycinam, jak robiłem sobie filtry pod pop-up-y z wyszukiwarki.

**Comment by krystian3w** [comment]
`news.google.com##.gb_Id[style]:style(height: 64px !important;)`, bo się robiła jakaś 20 pikselowa luka nad suwakiem a pod `headerem`, może uda się znaleźć lepszy sposób / identyfikator

**Comment by hawkeye116477** [comment]
@krystian3w U mnie ta reguła ze style nie działa, po odświeżeniu zresztą samo się ustawia na 64, ale przy 64 px widzę dziurę.

**Comment by krystian3w** [comment]
Dziwne, może zła wartość lub muszę zobaczyć w Chrome / Operze.

**Comment by hawkeye116477** [comment]
@krystian3w U mnie 40px jest ok.

**Comment by krystian3w** [comment]
Ja resetuje do normala, mniej więcej takiego czegoś:

![obraz](https://user-images.githubusercontent.com/35370833/47943848-6e626d00-def8-11e8-81f6-a6d564e45f35.png) |
--- |

Nie upiększam na siłę, można jeszcze mobilka sprawdzić jak to tam wygląda - może nie wystarczyć wykrywanie atrybutu `style`.

**Comment by hawkeye116477** [comment]
@krystian3w Ok, w takim razie u mnie ten efekt jest bez zmiany css :smile:.

**Comment by krystian3w** [comment]
Na Operze nie mam komunikatu, muszę znowu w incognito zobaczyć lub ustawienia ciastek zmienić do domyślnych z blokowania nieodwiedzonych / thrid party.

**Comment by hawkeye116477** [comment]
@krystian3w To dziwne, u mnie zawsze samo się poprawia po pełnym wczytaniu strony :smile:.
