### ISSUE TITLE
kawro.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9401]
cookies

**Comment by hawkeye116477** [comment]
To chyba jakaś pomyłka, nie ma :cookie:, jest tylko info o jakiś oszustwach.

**Comment by xxcriticxx** [comment]
@hawkeye116477 dokladnie

@blocker999 jakis screenshot please

**Comment by blocker999** [comment]
fakt, przepraszam zagalopowałem się, te info chyba trzeba dać do EI ?

**Comment by hawkeye116477** [comment]
A nie wiem, może lepiej to zostawić.
