### ISSUE TITLE
toyotaplus.pl

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#9404]
Coś chyba za dużo @hawkeye116477 @krystian3w chyba wyczyściliście z listy ciasteczek 
`toyotaplus.pl##.cookie-monster`

**Comment by krystian3w** [comment]
Wyrzuciliśmy reguły co miały po 11 wątków (kolejne `:not()` już nie za wiele dawały i tylko spowalniały regułę przy pierwszych odwiedzinach) i jedną z dwóch "`cookies.js`"
