### ISSUE TITLE
radio.opole.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9416]
Dziwne, cookies w tym artykule: http://radio.opole.pl/index.php?idp=10&tag=Samuel+Frankel&szukaj=Samuel+Frankel
 a na głównej niema, macie tak samo czy to tylko umnie ?

**Comment by xxcriticxx** [comment]
@blocker999 ja mam tylko na main `###monitcookie` fixes the problem

**Comment by blocker999** [comment]
aha na głównej są reklamy i sociale,oraz rss @hawkeye116477 

Są też i apki @KonoromiHimaries
