### ISSUE TITLE
naszemiasto.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9419]
sociale w artykułach, np tu : http://kwidzyn.naszemiasto.pl/artykul/planeta-singli-powraca-na-ekrany-10-listopada-film,4863596,artgal,t,id,tm.html

**Comment by krystian3w** [comment]
`naszemiasto.pl##.component.componentsArticleTools > a:nth-of-type(-n+2)`

**Comment by lukjan32** [comment]
jest blokada w artykulach

**Comment by krystian3w** [comment]
@xxcriticxx otworzysz z etykietą anty-adblock?

**Comment by krystian3w** [comment]
@olegwukr chyba kolejna domena Press Polska do kolekcji.

**Comment by lukjan32** [comment]
jak wam idzie?

**Comment by krystian3w** [comment]
Ja tam nie sprawdzałem jaką pułapkę teraz zastawili.

**Comment by lukjan32** [comment]
aha.

**Comment by lukjan32** [comment]
znow blokuja 
![1](https://user-images.githubusercontent.com/17565773/54231022-f809f300-4507-11e9-9fea-9aa331597a16.jpg)

**Comment by krystian3w** [comment]
Uparci jak filmweb a może bardziej.

**Comment by lukjan32** [comment]
beda filtry, lub mam dodac do wyjatkow?

**Comment by krystian3w** [comment]
Może na tyle ile wygłowkuje to Oleg / Maciek.

Ja tam sobie stosuje rozwiązanie z 26 stycznia - padnie, trudno...

**Comment by lukjan32** [comment]
aha
