### ISSUE TITLE
wroclaw.dlawas.info

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9420]
RODO

**Comment by krystian3w** [comment]
@KonoromiHimaries wycinasz może przycisk rozwiń z nagłówka?

@MajkiIT tu też może `###banner-top`

**Comment by KonoromiHimaries** [comment]
@krystian3w raczej nie, chyba że są w jakiś sposób infamujące.

**Comment by krystian3w** [comment]
Niby reklamują tam opcje dodania ogłoszenia i EasyList mocno to harata, że nic się nie rozwija #8552.
