### ISSUE TITLE
m.circlek.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9432]
http://m.circlek.pl
![opera zdjecie_2018-11-03_174842_m circlek pl](https://user-images.githubusercontent.com/36385327/47954926-bf25a480-df90-11e8-9afb-3d93261f4f8d.png)

https://www.circlek.pl/pl_PL
![opera zdjecie_2018-11-03_174921_www circlek pl](https://user-images.githubusercontent.com/36385327/47954930-d49ace80-df90-11e8-94d8-2b327084bf1b.png)

**Comment by xxcriticxx** [comment]
`###cookiebox`
`###cookieboxM`

**Comment by MajkiIT** [comment]
@KonoromiHimaries to twoje
