### ISSUE TITLE
mirrorace.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [MajkiIT/polish-ads-filter#9447]
reguła `||upvid.co/$popup` psuje mi przycisk "kliknij tutaj" na stronie mirrorace.com

**Comment by krystian3w** [comment]
W Firefox on działa i otwiera mi pierwszoplanowo `https://mirrorace.com/contact` chyba że mamy go szukać gdzieś indziej niż poza twoją propozycją tłumaczenia na język polski.

![obraz](https://user-images.githubusercontent.com/35370833/47966400-25bec700-e052-11e8-8106-c24d5cd787ef.png)

**Comment by KonoromiHimaries** [comment]
link testowy `https://mirrorace.com/m/2Pb5g`

**Comment by KonoromiHimaries** [comment]
chodzi o ten większy przycisk, ten który pojawia się po kliknięciu zielonego przycisku download

**Comment by KonoromiHimaries** [comment]
to nie jest moja propozycja, w wersji polskiej rzeczywiście jest napisane "kliknij tutaj".
jeśli uważasz że to błędne tłumaczenie, zgłoś propozycje poprawy tłumaczenia tutaj
https://mirrorace.com/contact

**Comment by krystian3w** [comment]
Chyba po zalogowaniu u mnie nie aktywuje się tak dobre tłumaczenie i dalej pasek po angielsku.

> ![obraz](https://user-images.githubusercontent.com/35370833/47966708-d8445900-e055-11e8-8903-f131db79c52d.png) |
> --- |

najwyżej się dopisze wykluczenie domeny (`domain=~mirrorace.com`) i już zacznie działać.

**Comment by MajkiIT** [comment]
@KonoromiHimaries @krystian3w Dziękuję
