### ISSUE TITLE
polskieszlaki.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9448]
https://www.polskieszlaki.pl/wycieczki/relacja,11610,lwia-gora-i-staroscinskie-skaly.html?n=860

Ukrywa
Włączony
![opera zdjecie_2018-11-04_165655_www polskieszlaki pl](https://user-images.githubusercontent.com/36385327/47966452-c7deaf00-e052-11e8-8f22-9a9cd71ab0a0.png)
Wyłączony
![opera zdjecie_2018-11-04_165828_www polskieszlaki pl](https://user-images.githubusercontent.com/36385327/47966458-de850600-e052-11e8-8c57-93121b80f0d2.png)

**Comment by MajkiIT** [comment]
@xMaap @krystian3w Dziękuję

**Comment by xMaap** [comment]
https://www.polskieszlaki.pl/babia-gora.htm
Pozostałość po reklamie (chyba?)
![opera zdjecie_2018-11-05_110814_www polskieszlaki pl](https://user-images.githubusercontent.com/36385327/47991677-26576c00-e0eb-11e8-9412-1bda2b16e89d.png)

**Comment by krystian3w** [comment]
Nie do końca, są na zmianę w ostatniej linii 2 wpisy z strony i  2 jakieś z obcej domeny oznaczone jako reklama:

> ![image](https://user-images.githubusercontent.com/35370833/47991898-b72e4780-e0eb-11e8-9320-8256888a9e7a.png) |
>--- |

Jednak trudne do odblokowania - trzeba by dopuścić reklamy Google. Chyba szybciej będzie sprawdzić czy `##.my-5` to bezpieczny filter do zlikwidowania luki
