### ISSUE TITLE
jabra.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9453]
https://www.jabra.pl/bluetooth-headsets/jabra-elite-active-65t
Po kliknięciu Zobacz wideo nic się nie robi dopiero z po wyłączaniu blokera  
![opera zdjecie_2018-11-04_173124_www jabra pl](https://user-images.githubusercontent.com/36385327/47966880-7b49a280-e057-11e8-9a79-d31e5b79289e.png)

**Comment by krystian3w** [comment]
`@@||www.googletagmanager.com/gtm.js$script,domain=www.jabra.pl`

**Comment by krystian3w** [comment]
EasyPrivacy ma długą listę wyjątków pod blogowanie tego:

`adsoup.com|airasia.com|asus.com|bhaskar.com|broadcom.com|computerworlduk.com|desigual.com|drumstick.com|ebuyer.com|elevationscu.com|gamepix.com|git-tower.com|google.com|itv.com|jobs.net|keygames.com|magicjack.com|moviefone.com|nestio.com|newsy.com|optus.com.au|rebtel.com|rockstargames.com|rollingstone.com|rozetka.com.ua|sixflags.com|support.amd.com|talktalk.co.uk|techradar.com|toto.co.jp|usmagazine.com`
