### ISSUE TITLE
*.dlawas.info

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9462]
https://nowemiasto.dlawas.info
https://walbrzych.dlawas.info
Włączony
![opera zdjecie_2018-11-05_112600_nowemiasto dlawas info](https://user-images.githubusercontent.com/36385327/47992646-b3032980-e0ed-11e8-85c6-3ebddc8cac0d.png)
Wyłączony
![opera zdjecie_2018-11-05_112629_nowemiasto dlawas info](https://user-images.githubusercontent.com/36385327/47992659-ba2a3780-e0ed-11e8-8f11-ef35fdb5d0a1.png)

**Comment by krystian3w** [comment]
Przycisk rozwinięcia raczej do wycięcia `###banner-top`, za dużo zachodu by go odblokować i nie dostało się za dużo reklam.

Chyba chodzi ci o brak suwaka po rodo, dopisze się więc domeny do reszty #8552  i #9420.

**Comment by krystian3w** [comment]
`infostrow.pl,wroclaw.dlawas.info,nowemiasto.dlawas.info,walbrzych.dlawas.info#@#A[href$="/reklama"]` 

\- sekcje polecane, filter chyba dla tych domen za mocny.
