### ISSUE TITLE
tubamarek.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9474]
https://tubamarek.pl
https://tubamarek.pl/aktualnosci/czytaj/5787-setna-rocznica-odzyskania-niepodleglości-w-mok-u-oraz-przy-pomniku-(wideo)

RODO + napisy REKLAMA

**Comment by krystian3w** [comment]
`##.rodo`
`##.rodom.message.ui`

**Comment by hawkeye116477** [comment]
@MajkiIT Jesli reklamy już wycięte, to możesz zamykać.

**Comment by krystian3w** [comment]
Jeszcze niepublicznie, tylko wycięcie timera reklamowego na `na|ekranie`.
