### ISSUE TITLE
redundant (cookies & social)

### ISSUE THREAD

**Issue by MajkiIT** [MajkiIT/polish-ads-filter#9495]
@hawkeye116477 @krystian3w FYI

Social

```
pclab.pl###b021, #b037 has been made redundant by pclab.pl###b021, #b037
onet100.vod.pl###socialIcons, .o_footSection3 has been made redundant by onet100.vod.pl###socialIcons, .o_footSection3
odkrywamyzakryte.com##.td-ss-main-sidebar > .widget_fbw_id.widget.td_block_template_1 has been made redundant by kosmicznapropaganda.pl,movieway.pl,cryptodemy.pl,xn--soikowo-njb.pl,magyazyn.pl,ochrona24.info,odkrywamyzakryte.com,retronagazie.eu##.widget_fbw_id
sportowefakty.wp.pl##.fatfooter__panel--observe.fatfooter__panel > ul > li:nth-child(-n+2) has been made redundant by sportowefakty.wp.pl##.fatfooter__panel--observe.fatfooter__panel, .rendered.observe_rss.observe__button.observe__part, .liketag
sportowefakty.wp.pl##.fatfooter__panel--observe.fatfooter__panel > .fatfooter__header has been made redundant by sportowefakty.wp.pl##.fatfooter__panel--observe.fatfooter__panel, .rendered.observe_rss.observe__button.observe__part, .liketag
windowsowo.pl###bpxl_social_widget-2 has been made redundant by pl###bpxl_social_widget-2
||e-stargard.pl/grafika/banery/fb/polubnas*.jpg has been made redundant by /polub
```

Cookies
```
pl###cookieView:not(body):not(html) has been made redundant by pl###cookieView:not(body):not(html)
smakizycia.pl,edarling.pl###info-bar has been made redundant by edarling.pl,foto4u.pl,himountain.pl,opteam.pl,praktiker.pl,smakizycia.pl,zoover.pl###infobarDiv, #infobar, .infobar, #info-bar, #info_c_box, .info-message
applemobile.pl###cookies-message has been made redundant by pl##[id^="cookies-message"]
konkret24.tvn24.pl,kontakt24.tvn24.pl###msgLayer has been made redundant by tvn24.pl###msgLayer
```

**Comment by krystian3w** [comment]
Social:

<pre><strong>sportowefakty.wp.pl##.fatfooter__panel--observe.fatfooter__panel &gt; ul &gt; li:nth-child(-n+2)</strong> &nbsp;has been made redundant by&nbsp; <strong>sportowefakty.wp.pl##.fatfooter__panel--observe.fatfooter__panel, .rendered.observe_rss.observe__button.observe__part, .liketag</strong>
<strong>sportowefakty.wp.pl##.fatfooter__panel--observe.fatfooter__panel &gt; .fatfooter__header</strong> &nbsp;has been made redundant by&nbsp; <strong>sportowefakty.wp.pl##.fatfooter__panel--observe.fatfooter__panel, .rendered.observe_rss.observe__button.observe__part, .liketag</strong></pre>


Cookies:

<pre><strong>smakizycia.pl,edarling.pl###info-bar</strong>&nbsp;has been made redundant by&nbsp;<strong>edarling.pl,foto4u.pl,himountain.pl,opteam.pl,praktiker.pl,smakizycia.pl,zoover.pl###infobarDiv, #infobar, .infobar, #info-bar, #info_c_box, .info-message</strong><br></div>

**Comment by krystian3w** [comment]
Jeszcze bym dopytał o pliki `generichide.txt` w szablonie do tworzenia list, niby większość poprzenosiłem i nagle zapomniałem obu list zapisać? Część filtrów jest w specyficznych ukrywających i na generichide (stąd np. proponowana redukcja "1:1").
