### ISSUE TITLE
www.ekino-tv.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#95]
adblock

http://ekino-tv.pl/movie/show/sinister-2-napisy-pl-2015-napisy/7733

The publisher of the video doesnt allow adblock, please disable and reload

**Comment by MajkiIT** [comment]
Zgłoszone do Reek-a. Dodatkowo dodałem regułę która usuwa ten alert. Zaktualizuj filtry.
