### ISSUE TITLE
zwik.skawina.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9517]
![zrzut ekranu z 2018-11-06 14-27-39](https://user-images.githubusercontent.com/36385327/48067323-43b23600-e1d0-11e8-9355-25c06773e90f.png)

**Comment by krystian3w** [comment]
jakaś reklama, wycinana filtrem sieciowym `.pl/*/ads/$domain=~tubagliwic.pl`:

> `http://zwik.skawina.pl/!data/ads/800.jpg`
>
> ![image](https://user-images.githubusercontent.com/35370833/48068476-3480b780-e1d3-11e8-8677-0867f7fa2e7b.png) |
> --- |


```
###popupDiv, #bgDiv
```
