### ISSUE TITLE
bip.um.szczecin.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9520]
cookies i dobrze by było wyśrodkować tą strone

**Comment by krystian3w** [comment]
do filtrów własnych:
`bip.um.szczecin.pl###Page:style(margin: 0 auto !important;)`
`bip.um.szczecin.pl##.eu:style(top: 55px !important; left: 68% !important;)`

ale nie wiadomo co tam się jeszcze rozwala po wyśrodkowaniu...

**Comment by xxcriticxx** [comment]
`###simplecookienotification_v01`
