### ISSUE TITLE
samouczek.info + aranzujemy.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9528]
Anty-adblock: 
`http://samouczek.info/`
`http://aranzujemy.pl/`

![zrzut1](https://user-images.githubusercontent.com/44813765/48080578-4459c500-e1ee-11e8-8fe3-84527222c227.png)

Na liście jest już:
`@@/adframe.js$script,domain=kobieceporady.pl|allekoszyk.pl`

Wystarczy dokleić domeny.

**Comment by krystian3w** [comment]
`##.gdpr` - rodo
