### ISSUE TITLE
bip.kujawsko-pomorskie.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9533]
cookies

Tak na marginesie. to niewiem adresy podobne a każda strona ma inne " cookies ".
Ale nic jakoś to ogarne i jutro podeśle posegregowane w temacie zbiorczym.

**Comment by krystian3w** [comment]
Ja tam na bieżąco to wrzucam w dev i @hawkeye116477  część przerabia na zasięg domen `.pl`, cookies kosmetycznie się ładnie wycina, rodo już gorzej jak trzeba CSS albo sprawdzać jak działa html filtering.

Ale dzięki, że chcesz to grupować, będzie można w miarę lepiej ogarnąć niż z kilka rodzajów rodo w różnym pluginie do pop-up-ów.
