### ISSUE TITLE
ostrowmaz.com

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#954]
Ukryta treść + pozostałość po reklamach - http://www.ostrowmaz.com/ogloszenia/kategorie/komputery
`@@||ostrowmaz.com/uploads/small_ad_photo/$image`
`ostrowmaz.com#@#.small_ad`
`ostrowmaz.com##.index_advertisement`
`ostrowmaz.com###bottom_advertisement`

**Comment by MajkiIT** [comment]
Dzięki.
