### ISSUE TITLE
srebrnestawy.pl agcbytom.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9542]
adblock detect

**Comment by krystian3w** [comment]
nie wykryli, wygląda jakby z góry informowali.

**Comment by krystian3w** [comment]
```html
<script id="rmv-b5be2a5ac0d840b">
    $(function(){
        var browserAlert = $('<div>');
        browserAlert.attr('id', 'b5be2a5ac0d840b');

        var advertPolicy = false;
        for (var b = document.cookie.split(";"), c = 0; c < b.length; c++) {
            var d = b[c].substr(0, b[c].indexOf("=")),
                e = b[c].substr(b[c].indexOf("=")+1);

            if (d = d.replace(/^\s+|\s+$/g,""), "ADVERT_POLICY" == d && "1" == e) {
                advertPolicy = true;
                break;
            }
        }

        if (advertPolicy === false && typeof window.advertChecker === "undefined") {
            browserAlert.append(
                '<div class="alert alert-warning alert-dismissable">' +
                    '<div class="container">' +
                        '<a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>' +
                        'Do prawidłowego działania i wyświetlania się strony należy wyłączyć wtyczkę adblocka z Twojej przeglądarki!' +
                    '</div>' +
                '</div>');
            $('body').prepend(browserAlert);
            $('#b5be2a5ac0d840b .alert [data-dismiss="alert"]').on('click touch', function() {
                var b = new Date;
                b.setDate(b.getDate()+365);
                document.cookie="ADVERT_POLICY=1; expires="+b.toUTCString()+"; path=/";
                $(this).closest('alert').hide();
            });
            $('head').append('<style>' +
                    '#b5be2a5ac0d840b { width: 100%; font-size: 12px; clear: both; position: absolute; top: 0; z-index: 9999; }' +
                    '#b5be2a5ac0d840b .alert { padding-top: 7px; padding-bottom: 7px; margin-bottom:0; line-height: 21px; border-radius: 0px; }' +
                '</style>');
        }
        $("#rmv-b5be2a5ac0d840b").remove();
    });
</script>
```

**Comment by krystian3w** [comment]
- `agcbytom.pl,srebrnestawy.pl#?#div[id]:-abp-has(.alert.alert-warning.alert-dismissable)`

- `agcbytom.pl,srebrnestawy.pl#?#div[id]:-abp-contains(wyłączyć wtyczkę adblocka)`


Ale może migać, bą wolne a np. `agcbytom.pl,srebrnestawy.pl##body > div[id^="b"]:nth-of-type(1)` może być tak często aktualizowany jak `na|ekranie` i bez sprawdzania ID wycinać może z połowę strony  - `#container-page`, wystarczy, że go się zamknie i po odświeżeniu już nagle wycina za dużo.

**Comment by gargaamel** [comment]
> `agcbytom.pl,srebrnestawy.pl#?#div[id]:-abp-has(.alert.alert-warning.alert-dismissable)`
> `agcbytom.pl,srebrnestawy.pl#?#div[id]:-abp-contains(wyłączyć wtyczkę adblocka)`

A po co tak się męczyć, wystarczy: 
`agcbytom.pl,srebrnestawy.pl##.alert-dismissable.alert-warning.alert` albo nawet samo `agcbytom.pl,srebrnestawy.pl##.alert-dismissable` lub
`agcbytom.pl,srebrnestawy.pl##.alert-warning`

> `agcbytom.pl,srebrnestawy.pl##body > div[id^="b"]:nth-of-type(1)`

Jaki to `id^="b"` ma sens skoro cały id jest losowy, równie dobrze przy następnej wizycie za jakiś czas może wygenerować na początku np. a, c ,d itd.

**Comment by krystian3w** [comment]
Jest "powiedzmy" wolno losujący, cząstka początkowa `b5be2` jeszcze nie przeskoczyła na wyższy numer.

A jak dla mnie blokowanie po klasach bootstrapa może za dużo wyciąć  jak za dużo sięgną po takie formatowanie: 
`https://www.w3schools.com/bootstrap/bootstrap_alerts.asp`
`https://www.w3schools.com/bootstrap4/bootstrap_alerts.asp`
