### ISSUE TITLE
ilewicz.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9544]
![zrzut ekranu z 2018-11-07 03-46-49](https://user-images.githubusercontent.com/36385327/48107405-c7efd200-e23f-11e8-8080-4df53237acce.png)

**Comment by krystian3w** [comment]
> ![image](https://user-images.githubusercontent.com/35370833/48116057-24191d00-e265-11e8-8392-e28c4d84c789.png) |
> --- |

> `http://ilewicz.pl/wp-content/uploads/JESIEN.jpg`
