### ISSUE TITLE
golfkobiet.org

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9545]
![opera zdjecie_2018-11-07_035034_golfkobiet org](https://user-images.githubusercontent.com/36385327/48107530-53696300-e240-11e8-8096-715059a60929.png)

**Comment by xxcriticxx** [comment]
@xMaap partnerzy?

**Comment by krystian3w** [comment]
pewnie tak.

**Comment by xMaap** [comment]
@xxcriticxx strona rozwalona, ale jednak to przez social i tam są zdjęcia z Instagrama.

**Comment by krystian3w** [comment]
> ![image](https://user-images.githubusercontent.com/35370833/48133234-70c91c00-e296-11e8-99cd-7609dabf5156.png) |
> --- |

tylko trochę te etykiety są nie równo, pierwsza wyżej niż pozostałe.
