### ISSUE TITLE
twojepc.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#955]
Puste miejsce po reklamie w testach oraz recenzjach - http://twojepc.pl/artykuly.php?id=Test-Fractal-Design-Define-Nano-S
http://twojepc.pl/artykuly.php?id=Test-Encore-Rockmaster-OE

![image](https://cloud.githubusercontent.com/assets/11742596/15634953/53f5564a-25d1-11e6-8c66-bf183666a126.png)

`twojepc.pl##td[width="300"][align="left"][valign="top"]`

**Comment by MajkiIT** [comment]
Dzięki.
