### ISSUE TITLE
Offtop f..adblock.

### ISSUE THREAD

**Issue by mbebe** [MajkiIT/polish-ads-filter#9552]
Firefox.
Ublock origin z filtrami z:
https://github.com/MajkiIT/polish-ads-filter/wiki/Jak-zainstalowa%C4%87-Nano-Defender-na-Firefoksie,-Waterfoksie-albo-(Chr)Operze%3F
Nanodefender 070.
https://fuckadblock.sitexw.fr/ - nie wykrywa adblocka
https://fuckadblock.sitexw.fr/beta/ - **wykrywa** adblocka

Na chrome takie same ustawienia(filtry) i na 2 powyzszych stronach nie wykrywa adblocka.
Czym to moze byc spowodowane? ;-)

**Comment by KonoromiHimaries** [comment]
> Czym to moze byc spowodowane? ;-)

no jak dla mnie to po prostu nie wykonałeś zalecanego zgłoszenia błędu do twórcy nano defendera.
