### ISSUE TITLE
www.tadepolska.pl

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#96]
cookies 

Ta strona używa ciasteczek "cookies" do budowania statystyk odwiedzin strony internetowej oraz dla świadczenia prawdłowych usług jej użytkownikowi. Jeśli się z tym nie zgadzasz możesz określić sposób przechowywania ciasteczek w swojej przeglądarce internetowej.

**Comment by MajkiIT** [comment]
nie takiego nie widzę
