### ISSUE TITLE
linuxiarze.pl

### ISSUE THREAD

**Issue by hawkeye116477** [MajkiIT/polish-ads-filter#9602]
### Zrzut ekranu

![screenshot_20181109_105727](https://user-images.githubusercontent.com/19818572/48255985-86615180-e40e-11e8-956e-5c11295dcc8a.png)

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Antyadblock, pojawia się po drugiej wizycie.

```
@@||linuxiarze.pl/wp-content/plugins/anti-adblock/images/ad/banner.gif
@@||linuxiarze.pl/images/ad
```
albo
`@@/images/ad$domain=linuxiarze.pl`

**Comment by krystian3w** [comment]
Pingwin dawno chyba wyciął go i nawet nie prosił byśmy przenieśli do siebie:


> Filtr statyczny `@@||linuxiarze.pl/images/ad/$image` znajdujący się w:
>
>  * Nano Defender Integration
> 

Jedno jest dziwne, co u mnie przepuszcza tego gifa (albo pod Gecko), albo to już nieaktualny plik...
