### ISSUE TITLE
smog.pl + pinger.pl + dobramama.pl + testwiedzy.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9611]
rodo / polityka / ciasteczka

Żadna z poniższych list tego nie likwiduje:

Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

![ss1](https://user-images.githubusercontent.com/44292328/47256567-dfc70800-d482-11e8-9ade-2a44afd874eb.png)

**Comment by gargaamel** [comment]
> krystian3w :
> 
> WP nie na moją głowę, mogę tylko przyblokować CSS-em, który nie wszędzie działa (Nano Adblocker, Stare Chromium, Vivaldii - problematyczne).
> 
> CSS hack dla uBlock Origin z userCSS (nie pod Nano Adblocker i stare Chromium):
> 
> ```
> pinger.pl,dobramama.pl,smog.pl##html > body > div[class]:last-of-type:has-text("RODO")
> pinger.pl,dobramama.pl,smog.pl##body > *:style(filter: none !important;)
> pinger.pl,dobramama.pl,smog.pl##html:style(overflow-y: visible !important; height: auto !important;)
> ```
> 
> krystian3w krystian3w referenced this issue 19 days ago
> Merged
> Update 🍪 & 👍 to version 20181021 RTM #9281

**Comment by hawkeye116477** [comment]
@gwarser Mamy zadanie dla specjalisty od WP :smile:.

**Comment by krystian3w** [comment]
I najlepiej sprawdzać w trybie incognito, wtedy prawie zawsze wyskakuje.

I zapomniano o `testwiedzy.pl`.

AdGuard script:

`abczdrowie.pl,autokult.pl,dobramama.pl,dobreprogramy.pl,echirurgia.pl,fotoblogia.pl,gadzetomania.pl,jejswiat.pl,kafeteria.pl,kafeteria.tv,komorkomania.pl,money.pl,nocowanie.pl,o2.pl,open.fm,parenting.pl,pinger.pl,pudelek.pl,pytamy.pl,samosia.pl,snobka.pl,testwiedzy.pl,wp.pl`

```
Object.defineProperty(window, 'wpjs_4', { get: function() { return []; } });
```

**Comment by gargaamel** [comment]
No np. taki regex działa:
/^htt(p|ps):\/\/[a-z.-]{2,14}\.wp\.pl\/[a-zA-Z0-9_-]{460,}/$script,domain=dobramama.pl|smog.pl|pinger.pl




<details not-open>
<summary>Takich reguł jest kilka na POL liście reklam: </summary>

```
!11#---------------------------------Multi Regex----------------------------------!
/\/[0-9a-zA-Z]{5,7}\_(?!adaptiveresize)[a-z]{12,17}\_[0-9]{3,3}\x[0-9]{3,3}\.jpg$/$image,domain=www.pcworld.pl
/:\/\/[a-zA-Z0-9]{3,9}\.quartic\.pl\/Ad\//$script
/^(http|https):\/\/a-o.ninja\/[\w\d]{5,10}\.js\?[a-z]{2,5}/$script
/^(http|https):\/\/www\.chip\.pl\/wp-content\/themes\/_chip\/[a-z]{4,6}\/[a-z]{4,5}-[0-9]{4,5}/$image,domain=chip.pl
/^(http|https):\/\/www\.portel\.pl\/(?!pasaz)[-a-z0-9A-Z_%$&+=[\].]{1,200}\/[-a-z0-9A-Z_%$&+=[\]/.]{2,200}.(html|htm)/$subdocument,domain=www.portel.pl
/^(http|https):\/\/www\.wp\.pl\/[a-zA-Z0-9-_]{50,}/$popup,domain=www.wp.pl
/^https:\/\/[a-z]{2,14}\.wp\.pl\/[a-zA-Z0-9_-]{200,}/$script,domain=profil.wp.pl|poczta.o2.pl|nowy.tlen.pl
/^https:\/\/[a-z]{2,14}\.wp\.pl\/[a-zA-Z0-9_-]{450,}/$script,domain=kafeteria.pl|twojeip.wp.pl|czat.wp.pl|wawalove.pl|niewiarygodne.pl|pogoda.wp.pl|dladzieci.pl|dzieci.pl|sport.wp.pl|topnews.wp.pl|odkrywcy.pl|katalog.wp.pl|kultura.wp.pl|avent-ugrow.wp.pl|pudelekx.pl|nerwica.com|forum.abczdrowie.pl|pytamy.pl|ranking.abczdrowie.pl|profil.tlen.pl
/^https:\/\/[a-z.]{2,17}\.wp\.pl\/[a-zA-Z0-9_-]{450,}/$popup,domain=www.wp.pl
/^https:\/\/eku24.net\/images\/slajdy\/(?!zyczenia)[a-z]{3,10}\/[a-zA-Z0-9_-]{10,50}\.jpg/$image
/^https:\/\/v\.wpimg\.pl\/[a-zA-Z0-9]{90,100}/$image,domain=money.pl
/^(http|https):\/\/[\w]{3,12}\.trojmiasto\.pl\/[\w]{5,10}\/[\w]{5,10}\/[\w]{5,10}\/[\w/]{10,20}/$script,domain=trojmiasto.pl
```
</details>
.

Więc do ciasteczek też można by dać, jeśli blokowanie tego skryptu nic nie zepsuje.

**Comment by hawkeye116477** [comment]
Gemiusa może popsuć :smile:.

**Comment by krystian3w** [comment]
Regex czy AdGuard z nowym skryptem?

**Comment by hawkeye116477** [comment]
Możnaby coś takiego `pinger.pl##script:inject(set-constant.js, window.wpjs_4, noopFunc)`, ale wtedy chyba będzie problem z Gemiusem.

**Comment by gargaamel** [comment]
Działać działa, a z tym Gemiusem to nie wiem o co chodzi, natomiast jedną rzecz zauważyłem (bez dodawania żadnych filtrów tutaj zaproponowanych), tak po prostu, nie działa przycisk "Przechodzę do serwisu", gdy go klikam (za pierwszym razem) to pojawia się tylko scroll bar strony www po prawej stronie.

**Comment by hawkeye116477** [comment]
@krystian3w Tak

**Comment by gargaamel** [comment]
No to zapytam w takim razie czy po wejściu na `pinger.pl` i pokazaniu się komunikatu z Polityką, działa wam przycisk "Przechodzę do serwisu"? Bo u mnie nie (na obydwu przeglądarkach Firefox i Opera), a po wyłączeniu uBO na Operze zadziałało (wcześniej nie chciało), a na Firefoxie dalej nie działa.

<details not-open>
<summary>Opera 56 screenshoot</summary>

![zrzut1](https://user-images.githubusercontent.com/44813765/48272614-49fa1980-e43f-11e8-83e4-77c127ae3bf5.png)
.

</details>

<details not-open>
<summary>Firefox 63.0.1 screenshoot</summary>

![zrzut2](https://user-images.githubusercontent.com/44813765/48272624-52eaeb00-e43f-11e8-81c1-240240f1de1d.png)

</details>

**Comment by hawkeye116477** [comment]
Nie działa. Dopiero po odświeżeniu strony znika komunikat.

**Comment by gargaamel** [comment]
> hawkeye116477 : Nie działa. Dopiero po odświeżeniu strony znika komunikat.

Ale jazda, nie wiadomo czy się śmiać czy płakać.

> hawkeye116477 : krystian3w Tak

To zdaje się, że lepiej regex, bo jeden filtr zgodny z ABP i działający na wszystkie 3 adblockery.

A z tym gemius no to jak chłopaki, trzeba wybrać mniejsze zło, czy ubić te natrętne komunikaty i przy okazji gemiusa, czy zostawić gemiusa przy okazji z tymi natrętnymi komunikatami, trzeba wybrać mniejsze zło.

**Comment by krystian3w** [comment]
"Martwa" platforma, może zamkną w 2019...

**Comment by gwarser** [comment]
`smog.pl,pinger.pl,dobramama.pl,testwiedzy.pl##+js(addEventListener-defuser.js, DOMContentLoaded, default.setTimeout)`


?

**Comment by hawkeye116477** [comment]
@gwarser Chyba może być, dziękujęmy :smile:

**Comment by gargaamel** [comment]
Działa.
