### ISSUE TITLE
stolicawolnosci.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9613]
Jakieś niewidzialne info przed wejściem na strone a na stronie sociale ( u góry )

**Comment by krystian3w** [comment]
https://stolicawolnosci.pl/files/download/wawa.mp4

**Comment by hawkeye116477** [comment]
U mnie na pcozątku nic nie ma, potem po jakiś paru sekundach się pojawia intro.

**Comment by blocker999** [comment]
@krystian3w A widzisz, winowajcą okazał się " Disable HTML5 Autoplay "

Ale tak czy siak ja bym to usunął, czy niewarto ?

@hawkeye116477 Co robimy ?

**Comment by hawkeye116477** [comment]
@blocker999 Teoretycznie można by zostawić, ale jeśli uważacie, że to irytujące, to można dodać do PFEI - Inne elementy/widgety => `stolicawolnosci.pl###vid, #skipIntro`.

**Comment by blocker999** [comment]
@hawkeye116477 Ok
