### ISSUE TITLE
brewa.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9629]
ciasteczka / rodo / polityka

Żadna z poniższych list tego nie likwiduje:

Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

![zrzut1](https://user-images.githubusercontent.com/44813765/48274472-ad864600-e443-11e8-969e-4949f9bafe26.png)

**Comment by krystian3w** [comment]
Jakieś śmieciowe, lista do newsletterów mi to wycina.

@hawkeye116477  - `www.brewa.pl#@#.newsletter:not(#popup_newsletter)`
