### ISSUE TITLE
hiszpanskidlapolakow.com

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9635]
ciasteczka / rodo / polityka

Żadna z poniższych list tego nie likwiduje:

Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

![zrzut1](https://user-images.githubusercontent.com/44813765/48276214-c55fc900-e447-11e8-90cd-7fbb82fbadd5.png)

**Comment by hawkeye116477** [comment]
Tutaj chyba trzeba się zgodzić, bo inaczej nie będzie komentarzy.

**Comment by MajkiIT** [comment]
@hawkeye116477 Promujesz to gdzieś?

**Comment by krystian3w** [comment]
Nie, dopiero to wystartowało.

**Comment by hawkeye116477** [comment]
@MajkiIT Tak, lecz na razie z wersją dla Chromium trochę kiepsko, bo nie będzie automatycznej aktualizacji. Updaty chyba niestety działają tylko dla rozszerzeń z Chrome Web Store, a to trzeba byłoby dać parę dolców dla Google...

**Comment by krystian3w** [comment]
Aktualizacja niby raz dziennie (24h), nie jak kiedyś myślałem w internować 6 - 12h.

Co do przyczepień to na starszej wersji czepiał się automat tylko grafiki icons8 w złym rozmiarze (miał jedną a chciał z 4 w kilku wymiarach).
