### ISSUE TITLE
gsmonline.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9658]
https://gsmonline.pl/artykuly/honor-8x-polski-film-reklamowy
Ukrywa
![opera zdjecie_2018-11-10_022332_gsmonline pl](https://user-images.githubusercontent.com/36385327/48295779-b270e700-e48f-11e8-8bb9-53993e5bede1.png)
![opera zdjecie_2018-11-10_022422_gsmonline pl](https://user-images.githubusercontent.com/36385327/48295787-c1579980-e48f-11e8-8e16-e15ef1c725fb.png)

**Comment by MajkiIT** [comment]
@xMaap EasyList
`@@||fs.siteor.com/gsmonline/articles/photo1s/123526/large/honor_reklama_edytowany-11.jpg?1541424368$image,domain=gsmonline.pl`
