### ISSUE TITLE
rkb.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9662]
ciasteczka / rodo / polityka

Żadna z poniższych list tego nie likwiduje:

Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

![zrzut1](https://user-images.githubusercontent.com/44813765/48298583-eebc3b80-e4bf-11e8-852f-fa230ca2a60a.png)

**Comment by krystian3w** [comment]
Mnie już wycina Fanboy Social, tylko jak on doda wyjątek, to my nie będziemy mogli użyć `rkb.pl##.fb-top`.

**Comment by krystian3w** [comment]
`rkb.pl#@#.fb-top` - do socialu, na **fałszywą / błędną** detekcje

**Comment by krystian3w** [comment]
`rkb.pl##.fb-top.foobar-wrapper` - na zablokowanie paska cookies
