### ISSUE TITLE
mdkgal.edu.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9689]
cookies

**Comment by blocker999** [comment]
@krystian3w Nie

![mdk](https://user-images.githubusercontent.com/23176832/48305310-b4d34f80-e528-11e8-95af-6782d95e3fab.png)

**Comment by krystian3w** [comment]
Takiego nie mam.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/48305427-7b034880-e52a-11e8-9544-42c9d3fd06ad.png) |
--- |

**Comment by blocker999** [comment]
@krystian3w Ja na vivaldim to mam a Ty ten statyczny ?

**Comment by krystian3w** [comment]
Na Firefox 63.

**Comment by krystian3w** [comment]
@blocker999  / @xxcriticxx `###spu-31560` wycina wam go?

![obraz](https://user-images.githubusercontent.com/35370833/48352383-db120000-e68c-11e8-831e-de27b0fdec0f.png)
