### ISSUE TITLE
znak.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9691]
sociale ( u góry i na dole ) oraz mam dziwny popup ( same tło na vivaldim a na innych niema )

**Comment by blocker999** [comment]
@krystian3w spojrzysz co to za popup ?

**Comment by krystian3w** [comment]
Może z newslettera:

![obraz](https://user-images.githubusercontent.com/35370833/48304671-974cb880-e51d-11e8-9fc0-3290e2e6c621.png) |
--- |
