### ISSUE TITLE
dbp.wroc.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9697]
sociale ( po prawo )

**Comment by krystian3w** [comment]
Issuu może zostać?

**Comment by blocker999** [comment]
@krystian3w Niewiem jak to interpretować, @hawkeye116477 co ty na to ?

Bardzo prosze każdego o opinie .

**Comment by krystian3w** [comment]
Ja tam zostawiłem, bo niby jakieś własne książki publikują.

Ostatecznie można zobaczyć czy Fanboy gdzieś wycina.

**Comment by blocker999** [comment]
@krystian3w Ale uzasadnienie a na yutubie ludzie publikują własne filmiki a na instagramie własne fotografie itd, wiem że " issu " to wartościowy serwis społecznościowy ale niewiem czemu robić wyjątek ?, poczekajmy na opinie, może @MajkiIT się wypowie ?
