### ISSUE TITLE
espedytor.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9712]
![opera zdjecie_2018-11-11_042518_www espedytor pl](https://user-images.githubusercontent.com/36385327/48308664-def93180-e569-11e8-83d6-37880d937803.png)

**Comment by hawkeye116477** [comment]
Mogę i zrobić klikanie, ale chyba ciastko będzie lepsze, a i tak zresztą klikanie powoduje utworzenie ciastka, więc na jedno wyjdzie :smile:.
