### ISSUE TITLE
gorski-potok.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9718]
![zrzut ekranu z 2018-11-11 04-29-13](https://user-images.githubusercontent.com/36385327/48308687-6181f100-e56a-11e8-938c-643caa82177f.png)

**Comment by MajkiIT** [comment]
@xMaap u mnie OK

**Comment by krystian3w** [comment]
U mnie też, na Firefox z Fanboy cookiemonster działa, może specyfika Opery.
