### ISSUE TITLE
nieruchomosci.arkei.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9721]
ciasteczka / rodo / polityka

Żadna z poniższych list tego nie likwiduje:

Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

![ss_031](https://user-images.githubusercontent.com/44813765/48314656-bce4cb00-e5cc-11e8-8f7a-20d3d1d23720.png)

**Comment by KonoromiHimaries** [comment]
https://github.com/liamja/Prebake#archived

**Comment by KonoromiHimaries** [comment]
https://github.com/Rudloff/adblock-imokwithcookies/commit/b6f14f90b64a8a24cc1d98ec1a0c3d7f9b1366dd

**Comment by krystian3w** [comment]
Nie wiem po co nam pisze jaka nie usuwa, jedynie przy regułach generycznych podglądamy filtry kiboke (`I don't care about cookies`) i jak coś okazjonalnie **`@`xMaap** tu już wrzuci błędnego z `Fanboy’s Cookiemonster List` to do **@ryanbr**-a.

Jak są zainteresowani polskimi domenami, to nikt im nie zabrania przeglądać naszych zgłoszeń.

**Comment by krystian3w** [comment]
@krystian3w

**Comment by gargaamel** [comment]
Co do https://github.com/MajkiIT/polish-ads-filter/issues/9721#issuecomment-437681888 i https://github.com/MajkiIT/polish-ads-filter/issues/9721#issuecomment-437682167 doskonale zdaję sobie sprawę, że te listy nie są już kontynuowane, ale to nie oznacza odrazu, że nie mają żadnej skuteczności, albo, że jest zakaz ich uzywania, świadomie korzystam z nie jednej nie rozwijanej już listy, bo zawsze jakąś skutecność jednak wciąż mają i wciąż stanowią świetne uzupełnienie.

>  krystian3w  : Nie wiem po co nam pisze jaka nie usuwa

Tak informacyjnie (przy okazji) dla ciekawskich (dla was i dla tych co korzystają z tych list), taka informacja za free, nawet nie zwróciłem uwagi na to, że w ten sposób mogę niejako karmić konkurencję, o to chodzi? Mogę nie wklejać tego.

**Comment by KonoromiHimaries** [comment]
@gargaamel zawsze możesz pozgłaszać braki z jednej listy do drugiej.

**Comment by krystian3w** [comment]
A dwie zmarłe jak chcesz przejąć na swoje konto, może autorzy ci je oddadzą i ponaprawiasz sobie z 200 błędów `Prebake` i `I'm OK with cookies` rozszerzysz poza francuskie domeny?

**Comment by gargaamel** [comment]
Hehe, póki co w praktyce problemów nie zauważyłem z `Prebake`, gdy jakieś zaobserwuję, to pewnie z tej listy zrezygnuję, a w `I'm OK with cookies` faktycznie tak zajrzałem i prawie same fancuskie hehe, no ale nie przeszkadza to w niczym taka mała lista, to ani nie pomaga ani nie przeszkadza, z sympatii ją trzymam pewnie.

**Comment by krystian3w** [comment]
Pewnie stare linki by nawet działały jakby zmienił się właściciel lub przejąć je jako organizacja - github zapisuje sobie przekierowanie.
