### ISSUE TITLE
venus-beauty.com.pl (2)

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9728]
błąd - ciasteczka / rodo / polityka, reopen https://github.com/MajkiIT/polish-ads-filter/issues/9659 bo zostały jakieś resztki / napis na dole po lewej:
`Site.PrivatePolicy.initBar($('#uid5be960e5c08a4'));`
<details not-open>
<summary>screenshoot</summary>

![ss_010](https://user-images.githubusercontent.com/44813765/48344175-9e3a0f00-e674-11e8-81cf-11c0520abddc.png)

</details>
.

Tych resztek/napisu nie ma gdy wyłączymy POL listę ciasteczkową i zaakceptujemy komunikat.

**Comment by xxcriticxx** [comment]
@gargaamel wyluzuj z otwieraniem nowych issues jak znalazles blad podaj poprawke otwierajac PR

**Comment by hawkeye116477** [comment]
Nic nie szkodzi, ogarniemy w devie :smile:.

**Comment by krystian3w** [comment]
Niech nie robi poprawek do ciastek, i tak się nadpiszą jak nie wrzucimy ich na dev przy kolejnym RTM.

**Comment by xxcriticxx** [comment]
@krystian3w thank you
