### ISSUE TITLE
insert.com.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9729]
cookies

**Comment by krystian3w** [comment]
Ja znowu nie mam, podepnij mi tu też ten temat z jakąś stroną "`edu.pl`".

**Comment by xxcriticxx** [comment]
ja mam cookies 

`###privacyAndCookiePolicy`

**Comment by blocker999** [comment]
![insert](https://user-images.githubusercontent.com/23176832/48352222-83739480-e68c-11e8-8bd3-567219753933.png)

**Comment by gargaamel** [comment]
Dla ciekawskich: to jest usuwane przez Fanboy’s Cookiemonster List.

**Comment by krystian3w** [comment]
Tak aż nam nie zablokuje kolejnego systemu kupowania gdzieś biletów na pociąg, samolot, autobus.

**Comment by gargaamel** [comment]
Możliwe, bo widzę, że jakieś zdarzenia tam są przypisane, w ogóle Fanboya list strach używać: https://github.com/ryanbr/fanboy-adblock/issues

**Comment by krystian3w** [comment]
Jak coś to dodałem na dev te `obiektyspa` (ABP kompatybilne, wycinam overlay) i `farmacje` (uBO, AdGuard - html filtering / css).

Jedynie wyjątek od **`@`ryanbr**, będzie psuł działanie wycinania komunikatu u nas - jak zostanie wysłuchany **`@`THEtomaso**.
