### ISSUE TITLE
microsoft.com/pl-pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9732]
cookies

**Comment by gargaamel** [comment]
Dla ciekawskich i pomocniczo: to jest usuwane przez Fanboy’s Cookiemonster List

**Comment by gargaamel** [comment]
> blocker999 gargaamel Polska lista do cookies ( ta od MjkIT ) jest samodzielną listą tzn nie wymaga żadnych dodatkowych list do cookies :+1: 

Jakbym nie wiedział, przecież napisałem:

> gargaamel : Dla ciekawskich i pomocniczo

> blocker999 :  i-dont-care-about-cookies " też to usuwa ale co z tego skoro, nie każdy jej używa,

Nie każe nikomu używać, chodzi o to, że może ktoś przekopiuje (może też zmodyfikuje, albo mu to podsunie jakiś pomysł) filtry do POL listy, takie ułatwienie i oszczędność czasu.

> blocker999 : Mam małą prośbe

Ja też mam prośbę, żeby się mnie inni (krystian3w, KonoromiHimaries, blocker999)  przestali czepiać o moje listy ciasteczkowe.

- używam list ciasteczkowych takich takich jakich mam ochotę używać
- wiem, że "blocker999: Polska lista do cookies ( ta od MjkIT ) jest samodzielną listą tzn nie wymaga żadnych dodatkowych list do cookies"
- wiem, że niektóre są już nierozwijane o czym napisałem tu https://github.com/MajkiIT/polish-ads-filter/issues/9721#issuecomment-437688569
- pomimo, tego, że niektóre są już stare, okazały się przydatne, żadna inna nie blokowałą np. tego: https://github.com/MajkiIT/polish-ads-filter/issues/9731#issuecomment-437953518:
- pisałem także, dlaczego o nich informuję tu https://github.com/MajkiIT/polish-ads-filter/issues/9721#issuecomment-437688569 i tu https://github.com/MajkiIT/polish-ads-filter/issues/9732#issuecomment-437954925

Naprawdę męczą mnie już te uwagi, bo to takie zakładanie z góry, że jestem głupcem, który nie wie czego używa.

> blocker999: Mam małą prośbe

Sam z siebie dużo pomagam na wielu różnych repach, na wielu różnych nikach, zajmuje się wieloma listami, zajmuje mi to całe dnie, jeśli starczy mi ochoty i zapału, to zobaczę. Jeszcze Fanboy chce żeby mu gotowe filtry wklejać do naprawy, i co jeszcze, niech sobie sami swoje bugi naprawiają https://github.com/ryanbr/fanboy-adblock/issues, ja rozumiem, że on jest zajęty, ale ja też k.. jestem, nie on jeden jest.
