### ISSUE TITLE
ezakopane.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9735]
![opera zdjecie_2018-11-13_042334_www ezakopane pl](https://user-images.githubusercontent.com/36385327/48389045-0e3fa800-e6fc-11e8-8b74-d95825b722f1.png)

**Comment by krystian3w** [comment]
`###menpx > A[target="_blank"] > IMG` na reklamę, ale taki sobie, za dużo detekcji 3 - 8 i  tylko 1 widoczna.
