### ISSUE TITLE
it-szkola.edu.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9737]
![opera zdjecie_2018-11-13_042649_it-szkola edu pl](https://user-images.githubusercontent.com/36385327/48389110-5c54ab80-e6fc-11e8-8c65-2444a2800b45.png)

**Comment by krystian3w** [comment]
Reklam chyba nie ma to można zamknąć:

https://github.com/MajkiIT/polish-ads-filter/blob/b77d79effdb81b908c65e30917f2c068a685222d/cookies_filters/adblock_cookies.txt#L507

To już musi działać w Operze  https://github.com/MajkiIT/polish-ads-filter/issues/9550
