### ISSUE TITLE
poczta.interia.pl/next/

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#9757]
### Link:

`https://poczta.interia.pl/next/`

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1041

### Problematyczny filter:

https://github.com/MajkiIT/polish-ads-filter/blob/d024da71f265573e5936d698537e169d92c26e69/polish-adblock-filters/adblock.txt#L1983

### Niby pomaga:

`poczta.interia.pl#@#.maximized-wrapper, .sitebar-block-fake`

### O błędzie:

Przycisk usuwania formatowania rozwala pocztę, czasem nawet nie otwiera się pop-up do pisania nowej wiadomości:

![image](https://user-images.githubusercontent.com/35370833/48407543-5a5c0e00-e737-11e8-8318-3d574934ac74.png) |
--- |

**Comment by MajkiIT** [comment]
@krystian3w Dziekuję

**Comment by krystian3w** [comment]
Pop-up trzeba by identyfikować po zawartości a to kuleje w uBO.

![obraz](https://user-images.githubusercontent.com/35370833/50550890-1e91ef00-0c78-11e9-9394-25ca1d5858e6.png) |
--- |
