### ISSUE TITLE
stukstuk.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9759]
ciasteczka / rodo / polityka

![ss_003](https://user-images.githubusercontent.com/44813765/48410842-20dbd080-e740-11e8-9670-af4ac9d8a336.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
Trochę przeszkadza  ten pop-up z promocją, ale chyba ogarnę co od czego.
