### ISSUE TITLE
false positive on static filter /reklamy/$image

### ISSUE THREAD

**Issue by dw72** [MajkiIT/polish-ads-filter#976]
Poniżej zrzuty ekranu z ublock gdzie filtr chyba nie do końca działa jak trzeba i blokuje normalny obrazek z słowem *reklamy* w nazwie pliku. 

![filtr](https://cloud.githubusercontent.com/assets/1017175/15717619/18f3300e-2828-11e6-926a-bb18bccbaadd.png)

![filtr](https://cloud.githubusercontent.com/assets/1017175/15718037/cff32dda-2829-11e6-8afc-924c9ab5d57f.png)

**Comment by MajkiIT** [comment]
możesz podać dokładny adres strony gdzie to się pojawia?

**Comment by F4z** [comment]
Pewnie chodzi o ten adres `http://www.zsp2.krotoszyn.net/strona/kierunek-ksztalcenia/technik-organizacji-reklamy`
Powinien być widoczny obrazek, ale go nie widać, bo reguła blokuje.
To powinno rozwiązać problem.
`@@||zsp2.krotoszyn.net/*/technik-organizacji-reklamy.jpg$image,domain=zsp2.krotoszyn.net`

**Comment by MajkiIT** [comment]
Może masz rację. Sprawdzę to symulując to co chciałem osiągnąć. Dziękuję.

**Comment by dw72** [comment]
Dokładnie są to pliki o różnych wymiarach, które wyświetlają się przy opisie kierunku kształcenia w szkole. Adresy są dwa www.zsp2.krotoszyn.net i prezentacj.zsp2.krotoszyn.net

Prawdopodobnie podpadnie pod tę regułę każdy obrazek, który ma słowo *reklamy* w nazwie pliku niezależnie od adresu z jakiego pochodzi...
