### ISSUE TITLE
motokobiety.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9762]
ciasteczka / rodo / polityka

![ss_003](https://user-images.githubusercontent.com/44813765/48411002-90ea5680-e740-11e8-807b-7104e4a69830.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
`motokobiety.pl,sklep-bmw.pl##body > div:not(body):not(id):not(class)[style*="position: fixed;"]`

z filtrów jakie mamy, jeszcze jest z 14 "position: fixed" i raczej z 90% będzie wycinać.
