### ISSUE TITLE
glogow.info.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9763]
ciasteczka / rodo / polityka

![ss_003](https://user-images.githubusercontent.com/44813765/48411101-d7d84c00-e740-11e8-9b88-ea1d2893146d.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
czemu nie działa:

`glogow.info.pl##.info1, .tloinfo1`

https://github.com/MajkiIT/polish-ads-filter/blob/b77d79effdb81b908c65e30917f2c068a685222d/cookies_filters/adblock_cookies.txt#L399

**Comment by gargaamel** [comment]
Już działa, po prostu często otwieram wiele kart na raz i wtedy czasem właśnie są takie efekty, że jakiś filtr nie zaskoczy, czasem o tym zapominam.

**Comment by krystian3w** [comment]
Czyli problem z uBlock Orgin i kartami otwartymi w tle, ale nie przypominam sobie bym otwierał stronę z przywracania sesji / zamkniętej karty lub w tle.

**Comment by krystian3w** [comment]
To są chyba jakieś żarty:

![image](https://user-images.githubusercontent.com/35370833/48415551-f729a600-e74d-11e8-818a-4d9b835a030c.png) |
--- |

**Comment by krystian3w** [comment]
O już widzę, mają raz kropkę, raz minusa...

**Comment by krystian3w** [comment]
`glogow.info.pl##.info1, .tloinfo1`
`glogow-info.pl##.info1, .tloinfo1`

**Comment by krystian3w** [comment]
Za mocno się zlała przy foncie z stałą szerokością.
