### ISSUE TITLE
forumstomatologiczne.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9765]
ciasteczka / rodo / polityka

![ss_003](https://user-images.githubusercontent.com/44813765/48411190-20900500-e741-11e8-981f-9f26982bff70.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
Nie umiem złapać dolnego i może być wycinane z opóźnieniem - mają klika pop-up-ów, choćby te dwa z nawigacji

i nie możemy ubić `cookie.jquery.min.js`, bo padną wszelkie pop-up-y.

**Comment by krystian3w** [comment]
Przy okazji postaram się spojrzeć na:

`forumpediatryczne.pl,psychiatria.pl,forumneurologiczne.pl`
