### ISSUE TITLE
sklep-bmw.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9766]
ciasteczka / rodo / polityka

![ss_003](https://user-images.githubusercontent.com/44813765/48411266-56cd8480-e741-11e8-8d30-acc6d86c7cc8.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
`motokobiety.pl,sklep-bmw.pl##body > div:not(body):not(id):not(class)[style*="position: fixed;"]`

z filtrów jakie mamy, jeszcze jest z 14 "position: fixed" i raczej z 90% będzie wycinać.
