### ISSUE TITLE
eurologistics.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9769]
ciasteczka / rodo / polityka na 4 strony

![ss_003](https://user-images.githubusercontent.com/44813765/48411456-deb38e80-e741-11e8-9153-c744470ea512.png)

<details not-open>
<summary>pełny screenshoot</summary>

![ss_003](https://user-images.githubusercontent.com/44813765/48411456-deb38e80-e741-11e8-9153-c744470ea512.png)
![ss_004](https://user-images.githubusercontent.com/44813765/48411457-deb38e80-e741-11e8-9166-0e35c378a832.png)
![ss_005](https://user-images.githubusercontent.com/44813765/48411459-df4c2500-e741-11e8-8cc9-008128dc73eb.png)
![ss_006](https://user-images.githubusercontent.com/44813765/48411460-df4c2500-e741-11e8-9c7d-e634abd831d0.png)

</details>
.

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
brzydki pop-up, blokuje przewijanie.

**Comment by krystian3w** [comment]
chyba zadziała html filtering, jest w podglądzie źródła.

**Comment by gargaamel** [comment]
A dlaczego sięgać po html filtering, anp. tak:
`eurologistics.pl###pum-46738`
`eurologistics.pl##html:style(overflow: auto !important;)`
`eurologistics.pl###wrapper_satyna:style(padding-right: 0px !important;)`

**Comment by krystian3w** [comment]
**`@`hawkeye116477**  porozbijał i staram się po prostu używać, bo i tak pewnie by poprzenosił kiedyś.
Wtedy reguły CSS są opcjonalne i rozumieją je tylko Chromowate i AdGuard  (on jakby olewał wykrywanie userCSS - już nie mówiąc że na chrome ma z tym dwa bugi: https://github.com/MajkiIT/polish-ads-filter/issues/8262#issuecomment-402638964).

Jedynie dla mnie problematyczne są strony gdzie musi być `position: static` i ja zazwyczaj tego nie widzę w css ani rozpadania się strony.

Jednie szkoda, że w AdGuardzie on jakoś czasem kuleje np. na `eobuwie.com.pl` się nie dało zastosować już a w uBlock Origin na Quantum działało.

**Comment by gargaamel** [comment]
Acha, no w sumie tak patrze to na FF taki jeden html: `eurologistics.pl##^#pum-46738` wycina tak dobrze, że zastępuje 3 tamte bo nie trzeba tych dodatkowych 2 do naprawiania scrolla i marginesu.

**Comment by krystian3w** [comment]
A do momentu aż ktoś nie wyłapie żadnego przydatnego pop-upa z pum  / popmake pluginu, to nawet używamy klas: `##.popmake-overlay` i do css `.modal-open`

i tu może się akurat prześlizgnął ten odstęp / margines css zastępujący suwak.

**Comment by krystian3w** [comment]
Moją wymówką na to niech będzie, że kiedyś dodałem takie coś:
`wybielanie.pl##html.pum-open.pum-open-overlay.pum-open-scrollable body>[aria-hidden]:style(padding-right: 0 !important;)`
