### ISSUE TITLE
project KAD

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#977]
https://azet12.github.io/KAD/index.html

https://github.com/azet12/KAD

KAD to darmowy filtr do oprogramowania typu Adblock lub uBlock.

Blokuje on najróżniejsze strony typu przekręt.

Wymagania: Adblock, Adblock Plus lub uBlock Origin.

**Comment by MajkiIT** [comment]
super sprawa :D . Dzięki
