### ISSUE TITLE
webcamera.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9784]
![opera zdjecie_2018-11-14_063354_www webcamera pl](https://user-images.githubusercontent.com/36385327/48462247-b8d8c900-e7d7-11e8-9b54-284f278c4fbd.png)
![opera zdjecie_2018-11-14_063415_www webcamera pl](https://user-images.githubusercontent.com/36385327/48462248-b8d8c900-e7d7-11e8-93a2-af7979b1b13c.png)
![opera zdjecie_2018-11-14_063429_www webcamera pl](https://user-images.githubusercontent.com/36385327/48462249-b8d8c900-e7d7-11e8-8f4c-06c409dbf5a7.png)
![opera zdjecie_2018-11-14_063442_www webcamera pl](https://user-images.githubusercontent.com/36385327/48462250-b8d8c900-e7d7-11e8-98f1-9bacaf158c8a.png)
![opera zdjecie_2018-11-14_063458_www webcamera pl](https://user-images.githubusercontent.com/36385327/48462251-b8d8c900-e7d7-11e8-8f64-ccadcccf4096.png)

**Comment by krystian3w** [comment]
Jakiś błąd w Nano Adblocker z reklamami Google?

Ja tam mam luki bez załadowanych elementów a też pewnie trudno wyciąć by nie wrócił anty-adblock - tam się wszystko przeterminowało po jakiś 24 godzinach / do 7 dni.

**Comment by krystian3w** [comment]
uBlock Origin / AdGuard:

`webcamera.pl##.adsbygoogle:style(position: absolute; left: -3000px)`

Ale jak sobie nie odpuścili, to będą pewnie wykrywać pozycje.
