### ISSUE TITLE
defra.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9792]
ciasteczka / rodo / polityka

![ss_003](https://user-images.githubusercontent.com/44813765/48485635-a54e5200-e819-11e8-9007-4e5f01d5c259.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
`##.popmake-overlay[data-popmake*="cookies"]`

A scroll tak dziwnie zasłonięty to już raz widziałem i nie naprawiamy tego, a przynajmniej ja wolę kupić wózek niż naprawiać nawigacje co jest nad przewijaniem.
