### ISSUE TITLE
drogerium.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9799]
ciasteczka / rodo / polityka

![ss_003](https://user-images.githubusercontent.com/44813765/48486092-cd8a8080-e81a-11e8-962f-84575fa7f0b4.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
@MajkiIT  znowu: 

`###rozwazamy_pozwanie_was_na_drodze_cywilnej.rozwazamy_pozwanie_was_na_drodze_cywilnej`
