### ISSUE TITLE
pihole news

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9821]
@MajkiIT dobre czytanie!

https://www.reddit.com/r/pihole/comments/9w5swx/i_think_ive_managed_to_block_youtube_ads_with/

https://www.reddit.com/r/pihole/comments/9wy6dq/google_ads_are_bypassing_pihole_by_being_served/

**Comment by MajkiIT** [comment]
@xxcriticxx Thanks .... good news.

**Comment by MajkiIT** [comment]
@xxcriticxx Działa CI to ?

**Comment by xxcriticxx** [comment]
@MajkiIT yt nie testowalem te z drugiego mam juz host file

nie zapomnij zrobic restart dnsmasq

**Comment by xxcriticxx** [comment]
@MajkiIT dziala testowalem na ipadzie i iphonie reklam jest minimalnie

na zoltych kropkach na yt film/bajka dalej leci

**Comment by MajkiIT** [comment]
@xxcriticxx Czyli zrobiłeś to?

What should I do?

-     nslookup manifest.googlevideo.com
-     nslookup the IP it returns.
-     if one of the returned hostnames is iad*.googlevideo.com, you're on the right track.
-     EDIT: some users report a single hostname being returned. Try using that if you don't get a second name,
-     edit your pi-hole's /etc/hosts file and create an entry with the IP address you got similar to what I have above.
-     restart dnsmasq

**Comment by xxcriticxx** [comment]
@MajkiIT tak tylko na koncu `pihole restartdns`

przy starcie filmiku na yt od czasu do czasu mam reklame i potem na zoltych kropkach sie nic nie odpala
