### ISSUE TITLE
pogonsportnet.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9822]
Resztka po reklamie i opadający header oraz cookies

**Comment by krystian3w** [comment]
Nawigacje przywiesza tylko @KonoromiHimaries  dla swoich kilku wiernych subskrybentów lub projekt: `yourduskquibbles/webannoyances`.

**Comment by gargaamel** [comment]
> krystian3w : ...dla swoich kilku wiernych subskrybentów...

Buahahaha

**Comment by krystian3w** [comment]
Bo nie wiem co on ma na myśli z opadłą nawigacją, mam tylko tą co się przywiesza (nie opada jakby coś było nad nią) i z taką nic nie robi polska lista EI a Wewnętrzna.

**Comment by krystian3w** [comment]
Mogę poprosić o jakiś łagodny skrypt na porcelanę? #9842

**Comment by blocker999** [comment]
@krystian3w Tak to umnie wygląda : 

![pogon](https://user-images.githubusercontent.com/23176832/48560543-5a523e80-e8ee-11e8-9ff1-63bb63d5e4fc.png)

 a nad headerem jest resztka po reklamie " media markt"

Jeśli to tylko błąd umnie to niema co się głowić, ktoś też to ma, tzn może potwierdzić ?

**Comment by gargaamel** [comment]
<details not-open>
<summary>Ja mogę tylko zaprzeczyć, bo u mnie jest wszystko ok zaraówno na Firefox jak i na Operze:</summary>

![ss](https://user-images.githubusercontent.com/44813765/48561093-8a4e1180-e8ef-11e8-8f27-0498ba6fe608.png)

</details>

**Comment by blocker999** [comment]
OK na firefox i operze jest poprawnie tylko na vivaldim nie może to kwestia rozdzielczości bo jak minimalizuje strone to jest ok a na 1820x1080 nie.

**Comment by krystian3w** [comment]
Ja mam tylko 3/4 FullHD i HD ready i dalej ok.

**Comment by krystian3w** [comment]
Na zoom 50% też błąd sam się nie robi, może wada Nano Adblockera?

**Comment by krystian3w** [comment]
```css
pogonsportnet.pl##.kode-header-absolute:style(top: 0 !important;)
```

Na to skakanie nagłówka, w Vivalidim mocno to widać, w Operze mniej a w Firefox to ja nie widziałem wczoraj w ogóle.
