### ISSUE TITLE
widzewtomy.net

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9824]
cookies

**Comment by krystian3w** [comment]
i jakiś antyadblock:

![image](https://user-images.githubusercontent.com/35370833/48554751-8adeac00-e8df-11e8-9750-fb50cd328625.png) |
--- |

**Comment by gargaamel** [comment]
### CIASTECZKA
Na POL liście ciasteczkowej jest filtr: `@@/wp-content/plugins/cookie-law-info/js/cookielawinfo.js`
Po jego wyłączeniu (np. `$badfilter`) komunikat o ciasteczkach znika, co nie znaczy, że twierdzę, że rozwiązaniem jest dodanie `$domain=~www.widzewtomy.net`, bo w końcu nie bez powodu jest whitelist na ten `cookielawinfo.js`, bo być może blokowanie tego skryptu coś psuło na różnych stronach, więc być może może popsuć też i na tej stronie i być może trzeba będzie zastosować jakieś inne rozwiązanie np. filtry kosmetyczne/html, albo zostawić komunikat w spokoju.

### ANTY-ADBLOCK
Co do anty-adblocka - NanoDefender go usuwa (tylko taka ciekawostka, bo wiem, że POL lista jest samodzielna), więc rozwiązania od najprostszego do najbardziej skomplikowanego:

- `www.widzewtomy.net#@##adsense` (whitelisting EasyList rule)
- `||www.widzewtomy.net/wp-content/uploads/*/*.js$script,domain=www.widzewtomy.net`
- `www.widzewtomy.net##+js(abort-on-property-read.js, anOptions)`

### REKLAMA

> krystian3w : i jakiś antyadblock:

I jakaś reklama:

![ss](https://user-images.githubusercontent.com/44813765/48558447-9931c580-e8e9-11e8-9d9f-b8ad5b219bcf.png)

**Comment by krystian3w** [comment]
@MajkiIT / @xxcriticxx  a anti-adblock i ta raczej zewnętrzna reklama...?
