### ISSUE TITLE
porcelana.com.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9842]
ciasteczka / rodo / polityka

![ss](https://user-images.githubusercontent.com/44813765/48555422-76031800-e8e1-11e8-9948-5ceee860bae2.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
```
   <script>
   window.onload = function() {
      alert("Ten serwis używa plików cookies w celu świadczenia Państwu usług na najwyższym poziomie. Brak zmiany ustawień przeglądarki oznacza akceptację na wykorzystanie plików cookies.");
        
   }
   </script>

```

html filtering / wstrzykiwanie skryptu.

**Comment by krystian3w** [comment]
I buhahaha, bo sami sobie odstraszają kilientów, komunikat wyskakuje bez końca.

**Comment by gargaamel** [comment]
`porcelana.com.pl##+js(abort-on-property-read.js, alert, cookies)`

**Comment by krystian3w** [comment]
Dzięki.
