### ISSUE TITLE
akamai.com/pl/pl/

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9852]
![opera zdjecie_2018-11-15_183846_www akamai com](https://user-images.githubusercontent.com/36385327/48570905-bb394100-e905-11e8-9216-ce4dbc3e4d29.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 a może tak ?
`||www.akamai.com/scripts/preloader.built.1540869889.js$script,domain=www.akamai.com`

**Comment by hawkeye116477** [comment]
Ten skrypt ma trochę tych rzeczy, chaty, itd. Lecz zdaje się, że chyba można też tak `akamai.com##.notification--warning, .modal--overlay` :smile:.

**Comment by krystian3w** [comment]
Nie da się chwycić narzędziami dev?

**Comment by krystian3w** [comment]
```
akamai.com##.disable-sibling-pointer-events~*, .disable-sibling-pointer-events~* *:style(pointer-events: unset !important;)
```

Ale w chromium z AdGuardem na 90% nie zadziała, chyba zostaje im skrypt i czekanie na wersje "2.14" dodatku dla Firefox i Opery.

**Comment by hawkeye116477** [comment]
Na :fox_face: chytruska jest świetne rozwiązanie z filtrowaniem html :smile:

**Comment by krystian3w** [comment]
Zgłoszone do AdGuarda, może wreszcie wprowadzą userCSS dla Chromium? I w wolnym czasie ktoś napisze od nich jakiś skrypt, ja najwyżej mogę im znowu podrzucić ciasteczko.
