### ISSUE TITLE
porcelana.com.pl (2)

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9860]
błąd - ciasteczka / polityka / rodo - reopen https://github.com/MajkiIT/polish-ads-filter/issues/9842 bo co prawda na Operze tego nie ma, ale na Firefoksie dalej jest.

**Comment by krystian3w** [comment]
Czyli co się stało?

Przeterminowany filtr html?

**Comment by gargaamel** [comment]
W loggerze nie ma żadnego filtra html, pokazuje się tylko kosmetyczny: `##span[class*="cookie"]:not(body):not(html)`

**Comment by gargaamel** [comment]
No ten dodany przed chwilą do DEV filtr już działa.
