### ISSUE TITLE
bajeczki.org

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9862]
cookies

`##.cookie-notice-container`

Ta strona korzysta z ciasteczek aby świadczyć usługi na najwyższym poziomie. Dalsze korzystanie ze strony oznacza, że zgadzasz się na ich użycie.Zamknij

ad block

http://bajeczki.org/all-categories/

![capture](https://user-images.githubusercontent.com/15007183/48618446-675f4400-e967-11e8-8df7-133ea70e98c8.PNG)

**Comment by krystian3w** [comment]
```
bajeczki.org#@#.text_ads
bajeczki.org#@#.text_ad
bajeczki.org#@#.textAd
bajeczki.org#@#.text-ads
bajeczki.org#@#.text-ad-links
bajeczki.org#@#.text-ad
bajeczki.org#@#.pub_728x90
bajeczki.org#@#.pub_300x250m
bajeczki.org#@#.pub_300x250
bajeczki.org#@#.adwidget
bajeczki.org#@#.ad-widget
```

I po anty-adblocku.

**Comment by gargaamel** [comment]
Buahahahaa

**Comment by krystian3w** [comment]
Opcjonalnie można też go wyciąć, przewijania nie blokuje, ID nie losuje.

Albo jak nie chce nam się kontrolować to `generichide` i co wycieknie to doblokować.

**Comment by gargaamel** [comment]
krystian3w nie żebym się z ciebie śmiał czy z tego, że podałeś jakieś rozwiązanie, po prostu śmieję się z samego faktu, że tak to rozwiązanie wyglądało (niespowodowanego twoją winą, po prostu tyle filtrów ogólnych nawalone, albo odwrotnie anty-adblock sprawdza tyle elementów), po prostu od wczoraj, z tobą czuję się jak kabarecie. Jak najbardziej takie rozwiązania się kwalifikują, nie żeby moje były super lepsze, ja tylko podam alternatywę, skoro już te najprostsze rozwiązania są podane: `bajeczki.org###modal` - ukrywa anty-adblocka,  ale czy nic nie psuje nie sprawdzałem, nad injectem trzeba będzie trochę pomyśleć (chociaż może w ogóle nie być potrzebny).
