### ISSUE TITLE
fitomento.com

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9870]
ciasteczka / rodo / polityka

![ss_004](https://user-images.githubusercontent.com/44813765/48631472-e2077e00-e9be-11e8-808a-161da9e3d6b2.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
`fitomento.com##.navbar-inner`
