### ISSUE TITLE
porcelana.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9871]
ciasteczka / rodo / polityka - kolejna porcelana buahahaha, uważajcie żeby nie stłuc wazy z dynastii Ming bo jest bardzo drogocenna buahahaha

![ss_004](https://user-images.githubusercontent.com/44813765/48631511-fc415c00-e9be-11e8-9380-32061b9f6be0.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
```
porcelana.pl##.modal-popup
porcelana.pl##body:style(overflow: auto !important;)
```
