### ISSUE TITLE
sklepbiker.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9873]
ciasteczka / rodo / polityka

![ss_004](https://user-images.githubusercontent.com/44813765/48631648-4aeef600-e9bf-11e8-806e-39e430ecdaa9.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
`sklepbiker.pl##+js(abort-current-inline-script.js, $, #rodoModal)`
