### ISSUE TITLE
polstor.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9874]
ciasteczka / rodo / polityka

![ss_004](https://user-images.githubusercontent.com/44813765/48631694-66f29780-e9bf-11e8-82a9-e3a6c780cbc0.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
`polstor.pl##.cookie`
