### ISSUE TITLE
wspanialewesele.com.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9875]
ciasteczka / rodo / polityka

![ss_004](https://user-images.githubusercontent.com/44813765/48631745-8ee1fb00-e9bf-11e8-9619-ffcf2fee7065.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
`wspanialewesele.com.pl###rodomoda`l
