### ISSUE TITLE
kodeksspolek.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9876]
ciasteczka / rodo / polityka

![ss_004](https://user-images.githubusercontent.com/44813765/48631797-a91bd900-e9bf-11e8-9d30-b864286f61d7.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
`kodeksspolek.pl###formalAgreementModal, #modalBackdrop`
