### ISSUE TITLE
luqam.com

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9877]
ciasteczka / rodo / polityka

![ss_004](https://user-images.githubusercontent.com/44813765/48631847-c05ac680-e9bf-11e8-9b50-bbe6b5d2cdd7.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
`luqam.com###cookiesFlyInBox`
