### ISSUE TITLE
bejeans.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9878]
ciasteczka / rodo / polityka - komu dźinsy buahaha

![ss_004](https://user-images.githubusercontent.com/44813765/48631892-d9fc0e00-e9bf-11e8-8399-ab403948eb9d.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
`bejeans.pl###js-cookienotice`
