### ISSUE TITLE
aspsklep.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9880]
ciasteczka / rodo / polityka

![ss_004](https://user-images.githubusercontent.com/44813765/48632008-22b3c700-e9c0-11e8-910a-283009fce75c.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
`aspsklep.pl###fancybox-wrap, #fancybox-overlay`
