### ISSUE TITLE
firmymiesne.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9881]
ciasteczka / rodo / polityka

![ss_004](https://user-images.githubusercontent.com/44813765/48632238-b1284880-e9c0-11e8-92ef-09f139dba677.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
`firmymiesne.pl##[aria-describedby="rodo-dialog"], .ui-widget-overlay`
