### ISSUE TITLE
gazetabaltycka.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9888]
Social
http://gazetabaltycka.pl/promowane/awantura-domowa-po-interwencji-policjantka-jest-w-spiaczce
![opera zdjecie_2018-11-17_095908_gazetabaltycka pl](https://user-images.githubusercontent.com/36385327/48659327-7de0ca80-ea4f-11e8-92f7-65ce6367cd41.png)

**Comment by xxcriticxx** [comment]
@xMaap rss feed?

**Comment by xMaap** [comment]
@xxcriticxx RSS raczej nie tylko te
![opera zdjecie_2018-11-17_164532_gazetabaltycka pl](https://user-images.githubusercontent.com/36385327/48662849-48a49e80-ea88-11e8-98a0-56770c75c178.png)

**Comment by krystian3w** [comment]
Nie jest linkiem, rzuca trochę się w oczy to wyciąłem.
