### ISSUE TITLE
e-prawnik.pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#9894]
" czarny pasek " ( na dole ) to chyba resztka po RODO

**Comment by krystian3w** [comment]
Resztka rodo na vivaldim?

**Comment by hawkeye116477** [comment]
Też to widzę i nie tylko na Vivaldim :smile:.

**Comment by krystian3w** [comment]
chcesz to możesz podpisywać "`:not(p)`".
