### ISSUE TITLE
tvwalbrzych.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9895]
![opera zdjecie_2018-11-17_121146_tvwalbrzych pl](https://user-images.githubusercontent.com/36385327/48660450-1718dc80-ea62-11e8-836d-3cdf20e262ef.png)

**Comment by krystian3w** [comment]
`##.pum-overlay` ale u mnie nawet wycięło zawartość pop-up-a.

**Comment by krystian3w** [comment]
I scroll odblokuje

**Comment by krystian3w** [comment]
@hawkeye116477  masz pop-up z treścią, bo ja nie wiem co na Firefox ją wycina.

**Comment by krystian3w** [comment]
@MajkiIT 

> Filtr statyczny `###gwd-ad` znajdujący się w:
> 
>   *  EasyList

trzeba by dodać wyjątek: **`walbrzych24.com#@##gwd-ad`**

`https://www.walbrzych24.com/upload/upload/Bannery_HTML/polityka/TV/index.html`

---

Chyba że @hawkeye116477  ubije całe `pum` / `popmake` dla użytkowników AdBlock / Adblock Plus.
