### ISSUE TITLE
biblioteka.olawa.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9901]
![opera zdjecie_2018-11-17_122259_www biblioteka olawa pl](https://user-images.githubusercontent.com/36385327/48660548-8fcc6880-ea63-11e8-9b18-88f0d1f82f75.png)

**Comment by hawkeye116477** [comment]
No właśnie, statyczne niezamykane raczej zostawiamy :smile:.
