### ISSUE TITLE
farmacja.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9906]
błąd - ciasteczka / rodo / polityka - cień/tło na Firefoxie (na Operze nie)

![ss008](https://user-images.githubusercontent.com/44813765/48662468-9dddb180-ea82-11e8-977b-4c1179e928fc.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
`farmacja.pl##^script:has-text(rodo)`
