### ISSUE TITLE
siegnijpopiekno.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9907]
błąd ?  - ciasteczka / rodo / polityka - jakieś resztki po komunikacie ciasteczkowym

![ss009](https://user-images.githubusercontent.com/44813765/48662693-c31fef00-ea85-11e8-9dd4-167375ed2236.png)

<details not-open>
<summary>Któraś z tych list to naprawia:</summary>

```
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by krystian3w** [comment]
generyczne reguły, ja tego nie naprawiam bo na innych się sypnie, tylko docinam...
