### ISSUE TITLE
digest.com.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9908]
Czy oby EasyList nie ma błędu i omyłkowo za dużo nie wycina - czy to powinno być wycięte czy nie?
Być może wycina jeszcze coś czego nie zauważyłem, nie sprawdzałem również podstron.

<details not-open>
<summary>Przy wyłączonej EasyList:</summary>

![ss010](https://user-images.githubusercontent.com/44813765/48662956-b69d9580-ea89-11e8-91e7-eadcba9c5064.png)
![ss011](https://user-images.githubusercontent.com/44813765/48662957-b69d9580-ea89-11e8-95b6-6750878ab787.png)

</details>
.

<details not-open>
<summary>Przy włączonej EasyList:</summary>

![ss012](https://user-images.githubusercontent.com/44813765/48662948-a5ed1f80-ea89-11e8-84ff-36a70e31113e.png)
![ss013](https://user-images.githubusercontent.com/44813765/48662950-a5ed1f80-ea89-11e8-9caf-62bd5b4ad277.png)

</details>

**Comment by hawkeye116477** [comment]
Oczywiście, że nie powinno. A to łobuziaki...
