### ISSUE TITLE
poradnikzdrowie.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9911]
Reopen https://github.com/MajkiIT/polish-ads-filter/issues/9211 bo dalej jest anty-adblock.

Może coś takiego:
```
||www.poradnikzdrowie.pl/media/desktop/zpr_videos_web/js/video_blocker.js$script,domain=www.poradnikzdrowie.pl
www.poradnikzdrowie.pl##.player-block-info
```

**Comment by krystian3w** [comment]
ten w wideo jest od 2 lat.

**Comment by gargaamel** [comment]
Mniej mnie obchodzi, co bylo przez 2 lata, a bardziej to czy jest dalej po zaaplikowaniu podanych wyżej filtrow, u mnie go nie ma.

**Comment by krystian3w** [comment]
Na pewno największego zasięgu, lepiej raczej nie da się unieszkodliwić w AdBlock / ABP.

U mnie działa dalej.

-----

A wyjątki dają wyciek reklam w prostych blokerach reklam:
```
! Polish

www.poradnikzdrowie.pl#@#[id^="placement"]
www.poradnikzdrowie.pl#@#[class$="-ads"]

! Easylist
www.poradnikzdrowie.pl#@#.adsbox
www.poradnikzdrowie.pl#@#.ad
www.poradnikzdrowie.pl#@#.doubleclick
www.poradnikzdrowie.pl#@#.ad-placement
www.poradnikzdrowie.pl#@#.carbon-ads

! Block text "reklama"
www.poradnikzdrowie.pl##[id^="inside_"][id$="_article"]
```

uBO / AdGuard może łagodnie wykryć pseudoelement z szarym tłem:

```
! Block gray pseudoelement
www.poradnikzdrowie.pl##[id^="placement"]:after
````

Zamiennie można by go wyrzucić za ekran:

```
! Move out of screen
www.poradnikzdrowie.pl##.article__placement:style(position: absolute !important; left: -3000px !important;)
```

I minusem jest wyciek i wymaganie uBlock Origin / AdGuard dla ukrycia resztek lub ukrycia ich poza ekranem.

----

Podobnie jakby zaburzać wczytywanie skryptu.

**Comment by gargaamel** [comment]
> krystian3w : U mnie działa dalej.

Żebyśmy się dobrze zrozumieli, czy mówimy o tym samym, ja mówię o tym anty-adblocku, który jest drugim screenshocie: https://github.com/MajkiIT/polish-ads-filter/issues/9211#issue-372135836 czyli o tym [link](https://user-images.githubusercontent.com/36385327/47246585-f297f900-d3fe-11e8-8d52-0dc32c692231.png). Moje reguły go usuwają zarówno na uBO jak i na ABP.

**Comment by krystian3w** [comment]
Usuwają ten z wideo, a jaki niby masz inny teraz?

**Comment by gargaamel** [comment]
>  krystian3w : a jaki niby masz inny teraz?

nie ja mam, tylko raczej ty masz bo gdy się spytałem:

> gargaamel : czy jest dalej (w domniemaniu anty-adblock)

to odpowiedziałeś:

> kryastian3w: U mnie działa dalej. (w domniemaniu anty-adblock)

No więc z tej odpowiedzi jasno wynikało, że jest/działa dalej anty-adblock (po zaplikowaniu moich reguł), ale u mnie po zaapilkowaniu moich reguł go nie ma, stąd się dopytuję i dodatkowo też dlatego bo zacząłeś jakieś inne reguły wklejać, więc tym bardziej wyglądało, że ale moje  reguły ci nie działają, albo  piszałeś o jakimś innym antyblocku, no i właśnie tego typu pytanie:

>  krystian3w : a jaki niby masz inny teraz?

raczej ja mógłbym zadać tobie, niż ty mnie.

Z kolei teraz piszesz, że jednak moje reguły go 

> krystian3w : usuwają ten z video

Dopiero z tej odpowiedzi wynika jasno, że moje reguły go usuwają.
