### ISSUE TITLE
wykop.pl 

### ISSUE THREAD

**Issue by Barticf** [MajkiIT/polish-ads-filter#9918]
Na wykopie nie działa odtwarzanie filmików ze strony streamable.com, możecie dodać do filtrów streamable.com##.stm-ad-player  tak by nie trzeba było tego dodawać ręcznie do filtrów ublocka ?

**Comment by hawkeye116477** [comment]
@krystian3w Ale to to samo, `##.cos = .cos{display: none !important;;}

**Comment by hawkeye116477** [comment]
Tego `display: none !important` to raczej nie trzeba, bo to to samo co `streamable.com###play-overlay`.

> może też nie działać dla starych Chromium (od 66?) i Vivaldi (chyba nawet w 2.1?)

Vivaldi od wersji 2 bazuje już na nowszym Chromium, w którym jest userstylesheet.

**Comment by krystian3w** [comment]
Ale użycie Nano Adblockera sprawia że dalej go nie ma? Jak nie to muszę sięgnąć bo legacy 1.X do ponownego sprawdzenia przewijania fancybox.

**Comment by hawkeye116477** [comment]
@krystian3w Zgadza się, Nano Adblocker ma wyłączone userCSS. Pingwin powinien to z powrotem włączyć, bo włączone już raczej nie powoduje problemów, a raczej teraz jest tylko na odwrót :smile:.

**Comment by MajkiIT** [comment]
@krystian3w @hawkeye116477 a ta reguła jest zła ? ==> `streamable.com##.stm-ad-player` była by zgodna z ADB

**Comment by krystian3w** [comment]
Jedynie jak już napisał autor na wykopie wymaga o kliknięcie więcej ale działa dalej.
