### ISSUE TITLE
domhouse.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9929]
ciasteczka / rodo / polityka

![ss037](https://user-images.githubusercontent.com/44813765/48672366-45b3b780-eb35-11e8-8467-e178acf426f3.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
`domhouse.pl##+js(abort-current-inline-script.js, $, rodo)`

**Comment by krystian3w** [comment]
html filtering coś psuje?

Nie sprawdzałem jak to znowu z AdGuardem i ich ułomnością html filteringu.

**Comment by hawkeye116477** [comment]
@krystian3w Nie sprawdzałem jeszcze filtrowania HTML.

**Comment by gargaamel** [comment]
Nie jestem ekspertem w sprawach ciasteczkowych, ale zapytam z ciekawości czy zwykłe  `domhouse.pl##.fancybox-overlay` nie wystarczy? (jakieś efekty uboczne)?

**Comment by krystian3w** [comment]
Brak przewijania.

**Comment by krystian3w** [comment]
Stopki już wtedy nie ujrzymy.

**Comment by gargaamel** [comment]
Brak przewijania. - no zdążyłem się zorientować i chiciałem skasować komentarz, ale byliście szybsi w odpisaniu.

**Comment by krystian3w** [comment]
Jak coś to dopisałem o sensowności ubijania skryptem, fancybox czasem dziwnie mocno go blokuje, że się prawie nie da CSS-em w starych Chromium / Vivaldi / Nano Adblocker.

**Comment by gargaamel** [comment]
Usunę swoje komentarze żeby smrodu więcej tu nie robić, kontynuujcie pracę

**Comment by hawkeye116477** [comment]
Ale i tak dla AG coś trzeba..
```
domhouse.pl##html.fancybox-lock > body, html.fancybox-lock:style(overflow: auto !important;)
domhouse.pl##html.fancybox-margin:style(margin-right: 0 !important;)
domhouse.pl##.fancybox-overlay:has-text(RODO)
```
Trochę wolniej będzie i pojawią się paparazzi, ale lepszy rydz niż nic :smiley: A bez sprawdzania tekstu nie możemy, bo podgląd zdjęć się popsuje.

**Comment by gargaamel** [comment]
> hawkeye116477 : ale lepszy rydz niż nic

hehe albo "lepszy wróbel w garści, niż gołąb na dachu"

**Comment by krystian3w** [comment]
Czyli wracamy do pliku suplement i revert z html filteringu?

**Comment by hawkeye116477** [comment]
@krystian3w Nie, a po co :stuck_out_tongue: Specjalne rozwiązanie tylko dla AG, a dla reszty te lepsze :smile:.
