### ISSUE TITLE
hopea.eu

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9933]
ciasteczka / rodo / polityka

![ss031](https://user-images.githubusercontent.com/44813765/48675503-f16efe80-eb59-11e8-9ab3-43307d301aba.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
`hopea.eu###colorbox, #cboxOverlay`
Miejmy nadzieję, że nic się nie zepsuje, bo jak na razie widać zdjęcia działają.
