### ISSUE TITLE
odr.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9937]
ciasteczka / rodo / polityka

![ss035](https://user-images.githubusercontent.com/44813765/48675535-5165a500-eb5a-11e8-8972-7af694f4ee91.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
A tutaj to cwanie zrobili, strona jest popsuta jak się nie zaakceptuje.

**Comment by gargaamel** [comment]
Ciasteczkowy potwór buahahaha.
