### ISSUE TITLE
itmarket.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9938]
ciasteczka / rodo / polityka

![ss037](https://user-images.githubusercontent.com/44813765/48675564-a1446c00-eb5a-11e8-84c7-6e1addb613d0.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
Nie wiem czy czegoś nie popsuje, nie mam tam konta, ale `||itmarket.pl/modules/prestaboost/views/js/prestaboost-popup.js` to będzie nawet dobre dla ABP :smile:

**Comment by krystian3w** [comment]
Jak nie psuje innych jakiś pop-up-ów np. z grafikami to raczej nie.

**Comment by krystian3w** [comment]
W sumie nie może psuć, jest tylko podczas pierwszego odwiedzenia i się robi ciasteczko akceptacji.
