### ISSUE TITLE
wikia.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9946]
![opera zdjecie_2018-11-19_003512_www wikia com](https://user-images.githubusercontent.com/36385327/48679632-fef4aa80-eb92-11e8-9d3b-2c9c990693f6.png)

**Comment by krystian3w** [comment]
Tylko w dodatku:

https://github.com/PolishFiltersTeam/PolishCookieConsent#jak-zainstalować

Bo przestało działać usuwanie ciasteczka `Geo`, a uBO domyślnie nie może robić ciasteczek jak AdGuard:

- [/sections/cookies_specific.txt#L1720](https://github.com/AdguardTeam/AdguardFilters/blob/45af1b823f56b3e90c82007f2362442261111732/AnnoyancesFilter/sections/cookies_specific.txt#L1720)
- [/sections/cookies_specific.txt#L1752](https://github.com/AdguardTeam/AdguardFilters/blob/45af1b823f56b3e90c82007f2362442261111732/AnnoyancesFilter/sections/cookies_specific.txt#L1752

)

**Comment by hawkeye116477** [comment]
@xMaap Dla Nano :penguin: może doda, jak go ładnie poprosisz :smile:.

**Comment by gargaamel** [comment]
> @xMaap Dla Nano może doda, jak go ładnie poprosisz .

@hawkeye116477 ty możesz nawet mu loda iść zrobić, przecież dla @MajkiIT już nie raz robiłeś.

**Comment by krystian3w** [comment]
Nie  doda, bo jest wybór, bywa...

Trzeba może wyjść z propozycją uprzywilejowania naszych np.:

```
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/cookies_uB_AG.txt
https://raw.githubusercontent.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/master/cookies_filters/cookies_uB_AG.txt
```

Chyba, że to będzie za mały zasięg lub wychwycone będą wybory za użytkownika - i te mogą być trudne jak ktoś blokuje same cookies / pop-up-y bez blokowania reklam i odcinamy mu personalizacje reklam.

**Comment by hawkeye116477** [comment]
Jeżeli już mamy wyjść z propozycją, to dla zgody może lepiej byłoby zrobić osobną listę. 
Choć generalnie osobne rozszerzenie do tego wydaje mi się lepsze, bo np na hiszpanskidlapolakow.com trzeba jeszcze checkboxy zaznaczyć albo gdzieś indziej usunąć element z shadow roota, więc znowu trzeba byłoby prosić kogoś by dodał taką możliwość, itd. No i byłoby to tylko dla Nano, więc wniosek jest taki, że tak średnio się to opłaci.
