### ISSUE TITLE
leddo.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9951]
![opera zdjecie_2018-11-19_144413_leddo pl](https://user-images.githubusercontent.com/36385327/48710755-ac0a0a00-ec09-11e8-99fe-12ebf90da0de.png)

**Comment by krystian3w** [comment]
`leddo.pl##.icon-linkedin`
`leddo.pl##.icon-google-plus`


`leddo.pl##.rodo-block`
