### ISSUE TITLE
e-restauracja.com

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#9984]
https://www.e-restauracja.com
![opera zdjecie_2018-11-19_214201_www e-restauracja com](https://user-images.githubusercontent.com/36385327/48733917-396a5000-ec44-11e8-8dd7-01648062b95e.png)
![opera zdjecie_2018-11-19_214214_www e-restauracja com](https://user-images.githubusercontent.com/36385327/48733918-396a5000-ec44-11e8-8330-04d7fc65f8a2.png)

https://www.rynek-turystyczny.pl
![opera zdjecie_2018-11-19_214408_www rynek-turystyczny pl](https://user-images.githubusercontent.com/36385327/48733974-5bfc6900-ec44-11e8-952f-dcf6e54aedcf.png)
![opera zdjecie_2018-11-19_214429_www rynek-turystyczny pl](https://user-images.githubusercontent.com/36385327/48733975-5bfc6900-ec44-11e8-84b6-46bc82f49efc.png)
![opera zdjecie_2018-11-19_214441_www rynek-turystyczny pl](https://user-images.githubusercontent.com/36385327/48733976-5c94ff80-ec44-11e8-869d-817f7272cca5.png)

**Comment by MajkiIT** [comment]
```
rynek-turystyczny.pl##div.no-padding.col-md-4.col-xs-12:nth-of-type(3) > div:nth-of-type(3)
www.e-restauracja.com###page-content\  > div.container:nth-of-type(1)
www.e-restauracja.com##div:nth-of-type(18)
```
