### ISSUE TITLE
Cookies w grafice muszynianki

### ISSUE THREAD

**Issue by krystian3w** [MajkiIT/polish-ads-filter#9987]
`http://muszynianka.pl/pl/`

----

`###mainContent > .outerContent > .innerContent > .custom.sliderMain > .bx-wrapper > .bx-viewport > ul > li > a > img > #mainContent > .outerContent > .innerContent > .cookie`

![image](https://user-images.githubusercontent.com/35370833/48762391-39516b00-ecab-11e8-86c8-83cd13a1599d.png) |
--- |

![image](https://user-images.githubusercontent.com/35370833/48762439-55eda300-ecab-11e8-8e9b-3cabd77809c2.png) |
--- |

---

Najdziwniejsze, że w Firefox raz tak miałem i potem już się naprawiło a w Operze wciąż sobie tam je doklejają.

**Comment by gargaamel** [comment]
Możesz dokładniej opisać swój problem, bo u mnie na Firefox i Operze to jest ukryte i problemów nie ma, w loggerze są te filtry:

```
##span[class*="Cookie"]:not(body):not(html)
##.cookie.custom
```

**Comment by hawkeye116477** [comment]
U mnie tak samo nie ma tego.

**Comment by gargaamel** [comment]
@hawkeye116477 edytowałem swój post wyżej, u mnie też na początku nie było, alle po kilku razach się zaczęło pojawiać, widać losowo się to dzieje.

**Comment by krystian3w** [comment]
Mnie chodzi o to, że były dwie detekcje i zgłupiałem gdzie jest ta druga i nawet XPath nie pokazywał gdzie ona jest - miałem taką samą regułę "`//*[@id="mainContent"]/div/div/div[12]`".

Potem wpadłem by zrobić taki filtr:

`###mainContent #mainContent > .outerContent > .innerContent > .cookie`

I wtedy zacząłem szukać dalej aż trafiłem że niby:

`###mainContent:nth-of-type(2) > .outerContent > .innerContent > .cookie`

dalej wykrywa cookies w ilości dwóch, więc zacząłem wyliczać `mainContenty`:

`###mainContent:nth-child(4)` - ten w grafice
`###mainContent:nth-child(7)` - ten ukrywany

**Comment by gargaamel** [comment]
@hawkeye116477 screen masz w pierwszym komentarzu na dole, chodzi o ten znacznik na samym dole po prawej `== $0`
