### ISSUE TITLE
pytanieomieszkanie.pl

### ISSUE THREAD

**Issue by gargaamel** [MajkiIT/polish-ads-filter#9997]
ciasteczka / rodo / polityka

![ss066](https://user-images.githubusercontent.com/44813765/48768619-cef3f700-ecb9-11e8-9678-c3be18281290.png)

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>

**Comment by hawkeye116477** [comment]
Dodali, coś słabo patrzyłeś :smile:.

**Comment by krystian3w** [comment]
Nie będę czekać kilka godzin aż skończą pop-up, dodałem bez bo działało.
