### ISSUE TITLE
Znudziły mi się ciastka

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#9999]
Podajcie coś nowego!

**Comment by krystian3w** [comment]
W ciachach ukryty social, ale przy ilości takiej to i tak pewnie nie wycinam wszystkiego i tylko 15% socialu wyciekającego.

**Comment by xxcriticxx** [comment]
Napewno przeciętny użytkownik na te wszystkie strony i tak nigdy nie wejdzie

**Comment by gargaamel** [comment]
> xxcriticxx : Napewno przeciętny użytkownik na te wszystkie strony i tak nigdy nie wejdzie

Tak samo jak nie wejdzie na wszystkie strony z reklamami, anty-adblockami, socialami, komunikatami, elementami irytującymi, rss itp., ciasteczka / rodo / polityka nie są tu wyjątkiem.  Żaden człowiek nie wejdzie na wszystkie strony, niezależnie od tego jakie elementy do zablokowania na nich są.

> xxcriticxx : Podajcie coś nowego!

Jak widać - inne elementy takie jak reklamy, anty-adblocki itp. zostały już dosyć dobrze wybite i trafiają się sporadycznie, coraz rzadziej, coraz trudniej takie znaleźć. Czas masowego zgłaszania reklam przeminął, zostały one wybite, teraz nastał czas ciasteczek / rodo / polityki - lista RODO-ciasteczkowa się rozrasta jak na drożdżach, ale i ona nie jest wyjątkiem, w pewnym momencie się nasyci i issue tracker wróci do normy, no chyba, że zacznie się zgłaszanie elementów social, których też jest od pyty jeszcze.

**Comment by krystian3w** [comment]
> Google przy szukaniu informacji na temat czegoś

Mi się zdarzyło, że przejrzałem pięć stron wyników wyszukiwania za elementami social związanymi z Poznańskimi Targami Technologicznymi, ale długo po prośbie **`@`blocker999** https://github.com/MajkiIT/polish-ads-filter/issues/8325

A szukałem czegoś innego.

> są elementy irytujące, których też mnóstwo, ale one mają osobny issue tracker

Ją chyba nawet `morele` przegląda, na jakieś "10 minut" (efekty pewnie odczuwalne jak do filtra `.pl` - np. do 3 dni, bo uBO nie umie pobrać nowszej listy i wcale nie pomagają wynalazki typu CDN - też się przy nich umie blokować) zepsułem im stronę w Firefox Quantum html filteringiem i teraz nagle już nie blokują przewijania ani klikania w elementy.

**Comment by blocker999** [comment]
@xxcriticxx pretensje do EU to oni wprowadzili to zamieszanie i podobno chcą je sami naprawić, mieli w tym roku ale wzamian dołożyli RODO : https://noizz.pl/nauka-i-technologia/powiadomienia-o-ciasteczkach-unia-europejska-chce-zlikwidowac-banery/hzwl2zf

Reklam prawie niema bo oprócz Polskiej listy jest Easy List które się rozrasta,, ciasteczek jest jeszcze sporo ale skoro one Ci się przejadły to będe przeglądał małe lokalne strony w poszukiwaniu reklam.

Na koniec trochłe statystyki, otóż Polaków jest około 38 mln z tego 80% kożysta z neta więc jedna osoba niewejdzie wszedzie ale 20 pare milionów już tak, o poloni niewspominając.

**Comment by gargaamel** [comment]
> blocker999 : Na koniec trochłe statystyki, otóż Polaków jest około 38 mln z tego 80% kożysta z neta więc jedna osoba niewejdzie wszedzie ale 20 pare milionów już tak, o poloni niewspominając.

Zgadzam się, to jest to samo co ja pisałem:

> gargaamel : tak więc o ile pojedyńczy użytkownik nie wejdzie na wszystkie strony, to wszyscy użytkownicy razem wzięci wejdą, bo się uzupełniają.



> blocker999 : Reklam prawie niema bo oprócz Polskiej listy jest Easy List które się rozrasta

Można się zgodzić, ale to nie jedyny powód, bo inny to ten o którym pisałem:

> gargaamel : Póki co wszystkie 3 listy: Social, RODO-ciasteczkowe i Elementy Irytujące są w półmetku drogi (każda po około 3000 filtrów) więc do 6000 im jeszcze brakuje drugie tyle, pewnie dopiero wtedy ciastka/rodo, sociale i elementy irytujące zostaną wybite co do nogi tak jak reklamy / anty-adblocki teraz.

> gargaamel : Można się zgodzić,

No właśnie, napisałem można się zgodzić, ale nie napisałem "zgadzam się", dlaczego, dlatego, że listy RODO-ciasteczowke oraz Social też mają nad sobą inne listy:
- oprócz listy POL RODO-ciasteczkowej korzystam z innych list w tym dwie są gigantyczne, a pomimo tego mój każdy założony wątek ma dodane, że

<details not-open>
<summary>Żadna z poniższych list tego nie likwiduje:</summary>

```
Polskie Filtry RODO-Ciasteczkowe (+ skrypt)
Fanboy’s Cookiemonster List
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

```
</details>
.

- dla listy POL Social jest też ogromna Fanboy's Social list, i pomimo, że można mieć Fanboy's Social włączoną, to i tak znajdzie się jeszcze od pyty sociali,

więc nie wiem czy EasyList pomaga dla POL listy reklamowej bardziej niż Fanboy's Social dla POL listy Social albo listy ciasteczkowe w spojlerze dla POL listy ciasteczkowej, ale na pewno coś tam pomaga, ale napewno listy Social, RODO-ciasteczkowe i Elementy Irytujące muszą urosnąć z 3000 do 6000 fitlrów (rozmiar POL listy reklamowej) żeby się przeczyściło w końcu od tych rodo-ciasteczek i sociali.

**Comment by krystian3w** [comment]
Najlepszy to jest ten skrypt, zablokowałeś na wersji "`1.19`" czy używasz pustego?

**Comment by gargaamel** [comment]
> krystian3w : Najlepszy to jest ten skrypt, zablokowałeś na wersji "1.19" czy używasz pustego?

Używam dodatku, bo wczoraj czy tam przedwczoraj skrypt już przestał być rozwijany.

**Comment by gargaamel** [comment]
> xxcriticxx: Znudziły mi się ciastka

A w jakim sensie ci się znudziły? Bo ty tylko etykiety przylepiasz, więc co, kolor/nazwa etykiety ci się znudziły?  Buahahahaa.

**Comment by xxcriticxx** [comment]
@blocker999 pozdrowienia z nyc

@gargaamel nudzisz sie to ja ci zaraz jaka robote znajde

**Comment by gargaamel** [comment]
xxcriticxx ale to przecież ty się nudzisz i zakładasz durne topiki:

> xxcriticxx: Znudziły mi się ciastka

więc nie odwracaj kota ogonem, lepiej ty sobie z najdź jakąś robotę, buahahaha.

**Comment by hawkeye116477** [comment]
@xxcriticxx ![Ciasteczka](http://www.xn--oczasu-3ib.pl/upload/tapety/ae1508c25133aec6b216802f502b43ab.jpg) :smiley:

**Comment by xxcriticxx** [comment]
@hawkeye116477 na przymus

**Comment by hawkeye116477** [comment]
@xxcriticxx To może teraz kolej na twoją własną listę filtrów, może fake news :smile:?

**Comment by xxcriticxx** [comment]
@hawkeye116477 azet juz ma taka liste
